### ISSUE TITLE
Exception running source build of engine on Mac

### ISSUE THREAD

**Issue by collinjackson** [flutter/flutter#100]
flutter start --debug
severe: To copy files to iOS devices, please install ios-deploy. You can do this using homebrew as follows:
$ brew tap flutter/flutter
$ brew install ios-deploy
Installing SkyShell.apk on device.
ProcessException: No such file or directory
  Command: /Users/jackson/git/engine/src/out/Debug/clang_x64/sky_snapshot /Volumes/skynet/flutter/examples/hello_world/./lib/main.dart --package-root=packages --snapshot=/var/folders/lx/tvgfzmms2pbb0f8gdvq24djw000_vj/T/flutter_toolsp07MWz/snapshot_blob.bin
severe: 
Exception:
dart:io                                                         Process.start
package:sky_tools/src/process.dart 19                           runCommandAndStreamOutput.<async>
dart:async                                                      Future.Future.microtask
package:sky_tools/src/process.dart                              runCommandAndStreamOutput
package:sky_tools/src/toolchain.dart 22                         Compiler.compile
package:sky_tools/src/commands/build.dart 191                   BuildCommand.build.<async>
dart:async                                                      Future.Future.microtask
package:sky_tools/src/commands/build.dart                       BuildCommand.build
package:sky_tools/src/commands/build.dart 160                   BuildCommand.buildInTempDir.<async>
dart:async                                                      _asyncThenWrapperHelper
package:sky_tools/src/commands/build.dart                       BuildCommand.buildInTempDir
package:sky_tools/src/commands/start.dart 72                    StartCommand.runInProject.<async>
dart:async                                                      _asyncThenWrapperHelper
package:sky_tools/src/commands/start.dart                       StartCommand.runInProject
package:sky_tools/src/commands/flutter_command.dart 59          FlutterCommand.run.<async>
dart:async                                                      Future.Future.microtask
package:sky_tools/src/commands/flutter_command.dart             FlutterCommand.run
package:args/command_runner.dart 178                            CommandRunner.runCommand.<fn>
dart:async                                                      Future.Future.sync
package:args/command_runner.dart 131                            CommandRunner.runCommand
package:sky_tools/src/commands/flutter_command_runner.dart 141  FlutterCommandRunner.runCommand
package:args/command_runner.dart 105                            CommandRunner.run.<fn>
dart:async                                                      Future.Future.sync
package:args/command_runner.dart 105                            CommandRunner.run
package:sky_tools/executable.dart 63                            main.<async>.<fn>.<async>
package:stack_trace                                             Chain.capture
package:sky_tools/executable.dart 62                            main.<async>

**Comment by abarth** [comment]
I think I see the issue.
