### ISSUE TITLE
Changes to properties are not being tested on presubmit

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#100099]
On presubmit the builder should populate the properties from .ci.yaml:

https://cs.opensource.google/flutter/cocoon/+/main:app_dart/lib/src/service/luci_build_service.dart;l=193

**Comment by keyonghan** [comment]
This should have been implemented in https://github.com/flutter/cocoon/pull/1446, https://github.com/flutter/cocoon/pull/1597, https://github.com/flutter/cocoon/pull/1599, https://github.com/flutter/cocoon/pull/1643.
