### ISSUE TITLE
processing phase stack in testflight (bitcode processing)

### ISSUE THREAD

**Issue by ashkryab-fl** [flutter/flutter#100043]
we released the app to the app store more than a year ago, every 2 weeks we release an update. After the text on the button was corrected in the application, I tried to upload the update.

The application is stuck in the "processing" stage. It's been 4 days already.
The application runs on real devices in debug and release mode. The validator does not generate any errors before uploading the archive to the testflight

I have already uploaded more than 5 builds, every time the same thing.

I only receive emails from apple:
Dear ******,
While processing your iOS app, ********, errors occurred in the app thinning process, and your app couldn’t be thinned. If your app contains bitcode, bitcode processing may have failed. Because of these errors, this build of your app will not be able to be submitted for review or placed on the App Store. For information that may help resolve this issue, see [Tech Note 2432](https://developer.apple.com/library/ios/technotes/tn2432/_index.html).
Best regards,
The App Store Team.

**Comment by darshankawar** [comment]
@ashkryab-fl 
The error you are getting may not be specific to Flutter, but we have seen such reports for other frameworks too. See below links for your reference:

https://developer.apple.com/forums/thread/661513
https://docs.microsoft.com/en-us/answers/questions/653529/app-store-connect-processing-stopped-for-app.html
https://stackoverflow.com/questions/71418030/expo-react-native-ios-testflight-errors-occurred-in-the-app-thinning-process

I suggest you to reach out to Apple technical support and see if they help you to resolve the issue.
Closing from here, as this doesn't seem specific to Flutter. If you disagree, write in comments and I'll reopen it.
