### ISSUE TITLE
Minified in live URI link Flutter Web

### ISSUE THREAD

**Issue by ShamshadSani** [flutter/flutter#100046]
![Screenshot 2022-03-14 at 3 13 56 PM](https://user-images.githubusercontent.com/49792885/158154956-6dc26d71-fef3-4052-9cb5-1b643d716778.png)
![Uploading Screenshot 2022-03-14 at 3.13.56 PM.png…]()

Getting this minified text with live flutter web link werfie.com , i am stuck when  reloading page getting refreshed with minified text and returns 404 page not found, you can check it on werfie.com ??? help me to clear this issue thanks to all in advance

**Comment by maheshmnj** [comment]
Hi @ShamshadSani, Thanks for filing the issue. If I understand it right when you launch https://werfie.com/minified:os in browser it throws 404 is that correct? if so please check this https://github.com/flutter/flutter/issues/89763#issuecomment-925040018
