### ISSUE TITLE
Getting error(Unhandled Exception: PlatformException(VideoError, Failed to load video: The operation could not be completed, null, null)) for some of the vedio urls

### ISSUE THREAD

**Issue by vikramsinghrajpoot** [flutter/flutter#100044]
I am using   video_player: ^2.2.17 for some of the urls in iOS getting PlatformException and unable to play those videos.

**Comment by darshankawar** [comment]
@vikramsinghrajpoot 
Can you provide `flutter doctor -v` and an example url that throws the said excpetion ?
See this similar open issue for your reference: https://github.com/flutter/flutter/issues/56665

**Comment by vikramsinghrajpoot** [comment]
**Urls:**
http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4 
http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4

**flutter doctor -v**
[✓] Flutter (Channel stable, 2.5.3, on macOS 11.6 20G165 darwin-x64, locale en-IN)
    • Flutter version 2.5.3 at /Users/vikram/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (5 months ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/vikram/Library/Android/sdk
    • Platform android-31, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.0, Build version 13A233
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.57.1)
    • VS Code at /Users/vikram/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (3 available)
    • iPhone 8 (mobile)  • 70590BD9-28AC-45DD-9D64-4FB44E80D144 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • iPhone 11 (mobile) • 3B7919C4-A627-4D02-9E6A-F70DE423B98C • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 99.0.4844.51

• No issues found!

**Comment by vikramsinghrajpoot** [comment]
this NSAppTransportSecurity tag is already there

**Comment by darshankawar** [comment]
> Channel stable, 2.5.3

Can you upgrade to latest stable and try again ?

**Comment by vikramsinghrajpoot** [comment]
Same error

**Comment by darshankawar** [comment]
@vikramsinghrajpoot 
Thanks for the update. I used the video links you shared above and used them in video_player plugin example, ran it on iOS simulator 15.2 on which both played properly as below:

<img width="355" alt="Screenshot 2022-03-17 at 11 35 04 AM" src="https://user-images.githubusercontent.com/67046386/158747376-d4125d85-65e2-4207-8da0-0193321f5fce.png">


<img width="362" alt="Screenshot 2022-03-17 at 11 36 40 AM" src="https://user-images.githubusercontent.com/67046386/158747386-3074d916-d2cc-48c2-8f14-20982183f3d7.png">

```
@override
  void initState() {
    super.initState();
    _controller = VideoPlayerController.network(
      'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
      closedCaptionFile: _loadCaptions(),
      videoPlayerOptions: VideoPlayerOptions(mixWithOthers: true),
    );

    _controller.addListener(() {
      setState(() {});
    });
    _controller.setLooping(true);
    _controller.initialize();
  }
```

Can you try the same on simulators (different OS versions) and confirm on which it works and on which devices it throws the error ? That way we'll know if this is device or OS specific issue or not.
