### ISSUE TITLE
[Fonts] Icon request: text_increase, text_decrease, density_large, density_small, density_medium

### ISSUE THREAD

**Issue by theFreeman96** [flutter/flutter#100065]
Hi,
I'm trying to do some sort of text format menu and I noticed some material icons are missing.
Could you make these icons?
- text_increase
- text_decrease
- density_large
- density_small
- density_medium

Thanks for your help!

**Comment by maheshmnj** [comment]
Hi @theFreeman96, Thanks for filing the issue. I can see that all the icons you mentioned are already present in the latest stable version of `flutter 2.10.3` . Please ensure that you are using the latest stable release of flutter. 

```dart
Icon(Icons.density_large),
Icon(Icons.text_increase),
Icon(Icons.density_small),
Icon(Icons.text_decrease),
Icon(Icons.density_medium),
```

<img width="184" alt="image" src="https://user-images.githubusercontent.com/31410839/158326673-6c135a38-0a74-439b-b3d3-a6929c290067.png">


Closing as these icons are already available in latest release, In case you disagree feel free to write in the comments and we will reopen it.

Thank you.
