### ISSUE TITLE
New branch request for recipes.

### ISSUE THREAD

**Issue by XilaiZhang** [flutter/flutter#100090]
Please create a branch in the flutter recipes project using:

flutter branching commit: 
branch name: flutter-2.12-candidate.4 (https://github.com/flutter/flutter/commits/flutter-2.12-candidate.4)

Gardener instructions section

Use the date of the provided flutter commit to find the oldest commit in the
recipes repository whose creation date is less than or equal to the creation
date of the flutter commit. Please ensure there were no reverts after the
selected commit.

Once the commit has been identified run the following commands on a clean checkout
of the recipes folder:

* `git clone git checkout -b <branch name>`. Branch name will look like `flutter-2.8-candidate.16`
* `git reset --hard <commit>`.
* `git push origin <branch name>`

The next step is verify the [***testing_ref*** regex](https://flutter.googlesource.com/infra/+/refs/heads/main/config/lib/release_branches/branches.json#3) for beta|stable configurations match
the new branch. Failing to do this will prevent from running postsubmit builds.

The last step in the process is to update the engine and flutter infra configurations for the release channel(only needed for new beta|stable releases). You can run the following commands
to do that:

* `mkdir $HOME/infra_checkout && cd $HOME/infra_checkout`
* `git clone https://flutter.googlesource.com/infra && cd infra && git checkout -b configs`
* `alias generate_jspb="dart $HOME/flutter_checkouts/cocoon/app_dart/bin/generate_jspb.dart"`
* `generate_jspb <flutter|engine> <release_branch> > $HOME/infra_checkout/infra/config/generated/ci_yaml/<flutter|engine>_<beta|stable>_config.json`
* `./config/main.star`
* `git commit`
* `git push origin HEAD:refs/for/main`
* `Wait for the PR to be reviewed and submitted`

**Comment by godofredoc** [comment]
We'll need to land a change similar to https://flutter-review.googlesource.com/c/infra/+/27962/ but for the flutter/flutter repository.

**Comment by godofredoc** [comment]
This is complete now.
