### ISSUE TITLE
[cocoon] Migrate /api/update-task-status to pubsub

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#100071]
If benchmarks are running around Cocoon deployments, it's common for a row to fail in the build dashboard as there's nothing to process them. We could either fix the health check, or move this handler to pubsub.

See https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_ios%20integration_test_test_ios/3454/overview

![image](https://user-images.githubusercontent.com/2148558/158219039-ce4a2e81-12a1-444d-a12e-48f3cc19ba4c.png)

**Comment by keyonghan** [comment]
Now everything is in cocoon scheduler: https://github.com/flutter/flutter/issues/92300, and the task status is updated via pubsub. The remaining work is to clean up the task status update codes from the framework test runner. Will track this in https://github.com/flutter/flutter/issues/92300
