### ISSUE TITLE
[FlutterEngineGroup] 'Rasterizer::SetResourceCacheMaxBytes' has surprising behavior in light weight engines scenario.

### ISSUE THREAD

**Issue by ColdPaleLight** [flutter/flutter#100060]
If the user does not set a custom resource cache max bytes. Eventually it will be set here:
``` c++
// |PlatformView::Delegate|
void Shell::OnPlatformViewSetViewportMetrics(const ViewportMetrics& metrics) {
  ......

  // This is the formula Android uses.
  // https://android.googlesource.com/platform/frameworks/base/+/master/libs/hwui/renderthread/CacheManager.cpp#41
  size_t max_bytes = metrics.physical_width * metrics.physical_height * 12 * 4;
  task_runners_.GetRasterTaskRunner()->PostTask(
      [rasterizer = rasterizer_->GetWeakPtr(), max_bytes] {
        if (rasterizer) {
          rasterizer->SetResourceCacheMaxBytes(max_bytes, false);
        }
      });

  ......
```
It is reasonable in pure flutter app that `max_bytes = physical_width * physical_height * 12 * 4`. But in the case of a lightweight engine, it has unexpected behavior.

Imagine such a scene, there are two FlutterViewController/FlutterFragment displayed at the same time, their engines are all lightweight engines created from the same `FlutterEngineGroup`, so they share the same `GrDirectContext`. Suppose the first FlutterViewController/FlutterFragment is displayed in full screen, and the second FlutterViewController/FlutterFragment is very small, which's size is `100*100`. Then the resource cache max bytes of GrDirectContext will be set to `100 * 100 * 12 * 4`. I believe this is not a reasonable value.

In the above scenario, I think it is more reasonable to set resource cache max bytes to the following value :

#### Option 1  
Use the screen width and height to calculate, not the width and height of `FlutterView`
`max_bytes = screen_width * screen_height * 12 * 4`

#### Option 2  
Set it to the maximum value of `metrics.physical_width * metrics.physical_height` for all engines in the `FlutterEngineGroup`.

c.f.
https://github.com/flutter/engine/blob/a46eae9913b1974b3661e14217a3980344027c04/shell/common/shell.cc#L910-L918

cc @dnfield @gaaclarke

**Comment by dnfield** [comment]
I think option two makes sense.
