### ISSUE TITLE
[ci.yaml] Validation check fails on reruns

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#100081]
https://github.com/flutter/engine/pull/32006/checks?check_run_id=5542883000

`HTTP 500: flutter/engine does not have any targets`

The ci.yaml check triggered all the builds, but failed somewhere at the end (possibly on a retry of the check).

```
Bad state: No element
#0      List.single (dart:core-patch/growable_array.dart:370:22)
#1      Scheduler.processCheckRun (package:cocoon_service/src/service/scheduler.dart:409:88)
#2      GithubWebhook.post (package:cocoon_service/src/request_handlers/github_webhook.dart:76:31)
<asynchronous suspension>
#3      RequestHandler.service.<anonymous closure> (package:cocoon_service/src/request_handling/request_handler.dart:52:22)
<asynchronous suspension>
#4      main.<anonymous closure>.<anonymous closure> (file:///app/bin/server.dart:267:9)
<asynchronous suspension>
```

This may have been because the PR failed a Cocoon check (adding a new dimension), which required an updated to Cocoon. Then the retry was run on the check. The issue being that the retry might not work.

**Comment by CaseyHillers** [comment]
The issue is the retry fails immeditaely on ci.yaml validation retries:

```dart
          final github.PullRequest pullRequest = checkRunEvent.checkRun!.pullRequests!.single;
          await triggerPresubmitTargets(pullRequest: pullRequest);
```

The first line is null, so it re-uses the previous error message

**Comment by keyonghan** [comment]
Is this still repro? Some fix has been rolled in.

**Comment by CaseyHillers** [comment]
\cc @nehalvpatel is running into this

**Comment by nehalvpatel** [comment]
Fixed by https://github.com/flutter/cocoon/pull/2402
