### ISSUE TITLE
[engine] building with local build. fails with errors

### ISSUE THREAD

**Issue by sgehrman** [flutter/flutter#100019]
This use to work, not sure what you guys changed.

flutter build linux --local-engine host_release

💪 Building with sound null safety 💪

ERROR: ../flutter/packages/flutter/lib/src/widgets/focus_manager.dart:1564:9: Error: Final variable 'expectedMode' must be assigned before it can be used.
ERROR:     if (expectedMode != highlightMode) {
ERROR:         ^^^^^^^^^^^^
ERROR: ../flutter/packages/flutter/lib/src/widgets/scrollbar.dart:637:8: Error: A non-null value must be returned since the return type 'bool' doesn't allow null.
ERROR:   bool hitTestInteractive(Offset position, PointerDeviceKind kind, { bool forHover = false }) {
ERROR:        ^
ERROR: ../flutter/packages/flutter/lib/src/widgets/scrollbar.dart:677:8: Error: A non-null value must be returned since the return type 'bool' doesn't allow null.
ERROR:   bool hitTestOnlyThumbInteractive(Offset position, PointerDeviceKind kind) {
ERROR:        ^
ERROR: ../flutter/packages/flutter/lib/src/gestures/converter.dart:15:5: Error: A non-null value must be returned since the return type 'int' doesn't allow null.
ERROR: int _synthesiseDownButtons(int buttons, PointerDeviceKind kind) {
ERROR:     ^
ERROR: ../flutter/packages/flutter/lib/src/gestures/converter.dart:62:13: Error: Switch case may fall through to the next case.
ERROR:             case ui.PointerSignalKind.none:
ERROR:             ^
ERROR: ../flutter/packages/flutter/lib/src/gestures/events.dart:2103:8: Error: A non-null value must be returned since the return type 'double' doesn't allow null.
ERROR: double computeHitSlop(PointerDeviceKind kind, DeviceGestureSettings? settings) {
ERROR:        ^
ERROR: ../flutter/packages/flutter/lib/src/gestures/events.dart:2116:8: Error: A non-null value must be returned since the return type 'double' doesn't allow null.
ERROR: double computePanSlop(PointerDeviceKind kind, DeviceGestureSettings? settings) {
ERROR:        ^
ERROR: ../flutter/packages/flutter/lib/src/gestures/events.dart:2129:8: Error: A non-null value must be returned since the return type 'double' doesn't allow null.
ERROR: double computeScaleSlop(PointerDeviceKind kind) {
ERROR:        ^
Build process failed

**Comment by sgehrman** [comment]
found out it also happens if I just run my app in VSCode debugger.

**Comment by sgehrman** [comment]
steve@5950x:~/development/flutter$ flutter doctor -v
[✓] Flutter (Channel stable, 2.10.3, on Debian GNU/Linux 11 (bullseye) 5.10.0-12-amd64, locale en_US.UTF-8)
    • Flutter version 2.10.3 at /home/steve/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (11 days ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc4)
    • Android SDK at /home/steve/Android/Sdk
    • Platform android-31, build-tools 31.0.0-rc4
    • Java binary at: /home/steve/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Debian clang version 11.0.1-2
    • cmake version 3.15.2
    • ninja version 1.8.2
    • pkg-config version 0.29.2

[✓] Android Studio (version 2020.3)
    • Android Studio at /home/steve/android-studio
    • Flutter plugin version 64.0.2
    • Dart plugin version 211.7798
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.65.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.36.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Debian GNU/Linux 11 (bullseye) 5.10.0-12-amd64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 99.0.4844.51

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Comment by maheshmnj** [comment]
Hi @sgehrman, Thanks for filing the issue. Did you modify any code sample in the SDK or opt in to null safety recently? The error seems related to null safety.

**Comment by AlanGriffiths** [comment]
I see the same errors (with `--local-engine=host_debug_unopt`) using the latest unchanged master

**Comment by wtwsky** [comment]
me too,why close the issue

**Comment by maheshmnj** [comment]
@AlanGriffiths We (Primary triage) are looking for the reproducible steps on this issue. 

Can someone from the engine team, Please check if this is caused by any recent change in the engine?

cc: @jason-simmons

**Comment by AlanGriffiths** [comment]
1. Checkout and build with master (any commit from 4a3e7a5b72363c1f363d3000d04719c6938d963f on)
2. mkdir ~/test && cd ~/test
3. flutter create myapp
4. flutter run --local-engine-src-path ~/flutter/testing/src/ --local-engine=host_debug_unopt
