### ISSUE TITLE
depfile has multiple output paths when build flutter to android app

### ISSUE THREAD

**Issue by jiangxiaoqiang** [flutter/flutter#100034]
## Steps to Reproduce

I am facing this problem when compile the project in MacBook Pro M1 pro, the 2019 MacBook works fine:

https://stackoverflow.com/questions/71458129/depfile-has-multiple-output-paths-when-build-flutter-to-android-app

what should I do to fix this problem.

**Comment by darshankawar** [comment]
@jiangxiaoqiang 
From stackoverflow link, you seem to be on 2.5.1 which is old version. Can you upgrade to latest stable 2.10.3 and try again to see if it helps or issue persists ?

If issue persists, please provide `flutter run -v`. The log will be huge so you can put that in a text file and share it here.
