### ISSUE TITLE
TextField has no way to specify for infinity for maxLines

### ISSUE THREAD

**Issue by KevinTheGray** [flutter/flutter#10006]
maxLines defaults to 1, and setting it to 0 can cause constraint breaks.  I think there should be an option to specify that.

You can reproduce this issue with any TextField

**Comment by Hixie** [comment]
What happens if you set it to null?

**Comment by eseidelGoogle** [comment]
@KevinTheGray notes that this does not block any current app development.  So this is a "medium" priority issue.

**Comment by KevinTheGray** [comment]
Failed assertion that maxLines != null

**Comment by Hixie** [comment]
Ok. We should probably make `null` mean `infinite` in this case.

**Comment by eseidelGoogle** [comment]
@lukef just asked me how hard this would be to fix?  Is this just a simple one-liner? or is there a bunch of additional layout work to be done in the infinite case?
