### ISSUE TITLE
Embedding flutter app to Android using cachedEngine failed with MissingPluginException

### ISSUE THREAD

**Issue by wangmir** [flutter/flutter#100054]
## Steps to Reproduce

I'm trying to follow the guide of flutter official to launch cached engine.
https://docs.flutter.dev/development/add-to-app/android/add-flutter-screen?tab=cached-engine-with-initial-route-kotlin-tab

but I failed because of error something like this,

```
 E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method checkArCoreApkAvailability on channel arcore_flutter_plugin/utils)
    #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:165:7)
    <asynchronous suspension>
    #1      ArCoreController.checkArCoreAvailability (package:arcore_flutter_plugin/src/arcore_controller.dart:26:34)
    <asynchronous suspension>
    #2      RepositoryContainer.initializedDone (package:catcha_module/repositories/repository_container.dart:151:11)
    <asynchronous suspension>
    #3      main (package:catcha_module/main.dart:20:3)
    <asynchronous suspension>

```

Android side code of pre-warming sequence was very same as official guide.

```kotlin

    private val flutterEngine: FlutterEngine by lazy {
        FlutterEngine(context)
    }

    private var isWarmedUp = false

    override fun warmUpFlutterEngine() {

        flutterEngine.navigationChannel.setInitialRoute("/")
        flutterEngine.dartExecutor.executeDartEntrypoint(
            DartExecutor.DartEntrypoint.createDefault()
        )

        FlutterEngineCache
            .getInstance()
            .put(ENGINE_ID, flutterEngine)
        isWarmedUp = true
    }
```

And, flutter side main function does pre-app tasks before launch runApp()

```dart
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  SystemChrome.setPreferredOrientations([DeviceOrientation.portraitUp]);

  globalPreference = await SharedPreferences.getInstance();
  await Log().initialized;
  // run app after repository singleton init
  await RepositoryContainer().initializedDone();

  runApp(App());
}
```

initializedDone() function contains,
```dart
  Future initializedDone() async {

    print('ARCORE IS AVAILABLE?');
    print(await ArCoreController.checkArCoreAvailability());
    print('\nAR SERVICES INSTALLED?');
    print(await ArCoreController.checkIsArCoreInstalled());

    await _signInRepository.initializeDone;

    await _dataRepository.initializationDone;

    _dataRepository.fetchAllFromServer();
  }
```

And I realized that not only ARcoreController, when I commented out the usage of ArCoreController, other plugin was failed in the same way.

If I launch the app with 
```kotlin
startActivity(
      FlutterActivity.createDefaultIntent(currentActivity)
    );
```

it was launched with no problem.

I searched for a while to find similar problem with me, but I couldn't find any. Do u have any idea about this?

**Comment by wangmir** [comment]
If i skip ArcoreController things,

the error was like,

```
E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(ServiceAreNotBounded, service is not bounded, null, null)
E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(SERVICE_STATUS_ERROR, Location service status couldn't be determined, null, null)
    #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
    #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:167:18)
    <asynchronous suspension>
    #2      MethodChannelLocation.serviceEnabled (package:location_platform_interface/src/method_channel_location.dart:130:25)
    <asynchronous suspension>
```

**Comment by darshankawar** [comment]
@wangmir 
`Unhandled Exception: MissingPluginException(No implementation found for method checkArCoreApkAvailability` this seems to be pointing to third party package. 

If you skip it, and getting below errors:

`Unhandled Exception: PlatformException(ServiceAreNotBounded, service is not bounded, null, null)`
`PlatformException(SERVICE_STATUS_ERROR, Location service status couldn't be determined, null, null)`

Seems to also point to third party plugin, `location`, for which a similar issue is open in dedicated repo: https://github.com/Lyokone/flutterlocation/issues/568

If you directly follow the steps mentioned in the [document](https://docs.flutter.dev/development/add-to-app/android/add-flutter-screen?tab=cached-engine-with-initial-route-kotlin-tab) as-is without adding any third party plugins, do you still get any kind of exception ?

**Comment by wangmir** [comment]
Actually, I exactly mean that.

When I remove location library, it also happened at other library too.

```
E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method requestIgnoreBatteryOptimizations on channel flutter.demen.org/android_power_manager)
    #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:165:7)
    <asynchronous suspension>
    #1      AndroidPowerManager.requestIgnoreBatteryOptimizations (package:android_power_manager/android_power_manager.dart:18:7)
    <asynchronous suspension>
    #2      _ShoppingStartAlertDialogState.startingView.<anonymous closure>.<anonymous closure> (package:catcha_module/screens/dialogs/shopping_start_dialog.dart:147:27)
    <asynchronous suspension>
```

I tested with the clean flutter module, and that was running perfectly, but if i use some library which implements functionality using platform channel, it seems to fail.

So, I'm wondering that should i do something more when I use cachedEngine to warm up engine with platform implementation.

Because, it run perfectly when I launch with new engine.

**Comment by wangmir** [comment]
I think this issue can be hint.
https://github.com/flutter/flutter/issues/93968

Are there any guideline for this function? `GeneratedPluginRegistrant.registerWith(flutterEngine)`

**Comment by darshankawar** [comment]
@wangmir 
Thanks for the update. I think you are hitting this https://github.com/flutter/flutter/issues/83000, so please follow-up in it for further updates.
Closing this as a duplicate. If you disagree write in comments and I'll reopen it.

**Comment by wangmir** [comment]
@darshankawar it may be caused by the same reason. But, the case is different. In the case of #83000, it fails when the android application calls the method channel to plugin, and that method channel start flutter activity, but in my case the sequence is just like,

1. prepare flutter module (aar) and Android application which will embed flutter aar.
2. flutter aar references library which contains platform-channel functions.
3. pre warming flutter engine using cached engine.
4. And pre-warming sequence failed with that.

**Comment by darshankawar** [comment]
@wangmir 
Thanks for the feedback. Can you try [this](https://github.com/flutter/flutter/issues/98473#issuecomment-1058500136) solution and see if it helps ?
