### ISSUE TITLE
In iOS15, when webview_flutter exits the webview interface, the following error will be reported!

### ISSUE THREAD

**Issue by WangYiOS** [flutter/flutter#100037]
```
[assertion] Error acquiring assertion: <Error Domain=RBSServiceErrorDomain Code=1 "target is not running or doesn't have entitlement com.apple.runningboard.assertions.webkit" UserInfo={NSLocalizedFailureReason=target is not running or doesn't have entitlement com.apple.runningboard.assertions.webkit}>
[ProcessSuspension] 0x1112fa700 - ProcessAssertion: Failed to acquire RBS assertion 'ConnectionTerminationWatchdog' for process with PID=25324, error: Error Domain=RBSServiceErrorDomain Code=1 "target is not running or doesn't have entitlement com.apple.runningboard.assertions.webkit" UserInfo={NSLocalizedFailureReason=target is not running or doesn't have entitlement com.apple.runningboard.assertions.webkit}
```

> 场景：
点击按钮进入webview界面，使用的库是webview_flutter: ^3.0.1，
webview界面显示正常
但是退出这个界面的时候，控制台会报以上错误！

Scenes:
Click the button to enter the webview interface, the library used is webview_flutter: ^3.0.1,
The webview interface is displayed normally
But when exiting this interface, the console will report the above error!

**Comment by danagbemava-nc** [comment]
Hi @WangYiOS, please provide a complete minimal reproducible code sample as well as the output of `flutter doctor -v`.

Thank you

**Comment by WangYiOS** [comment]
> 嗨@WangYiOS，请提供完整的最小可重现代码示例以及`flutter doctor -v`.
> 
> 谢谢

Hello, big brother
I closed that question.
Because this error does not affect the interface display, debug and release are used normally.
Thank you
