### ISSUE TITLE
pub publish has trouble with plugin examples

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#10001]
While `pub publish`ing the `firebase_storage` plugin, I got the following warning:

```
* line 7, column 1 of example/lib/main.dart: This package doesn't depend on http.
  import 'package:http/http.dart' as http;
```

`example/pubspec.yaml` correctly declares this dependency.

/cc @mit-mit

**Comment by mit-mit** [comment]
@danrubel any idea if this  is related to https://github.com/flutter/flutter/issues/10015 ?

**Comment by eseidelGoogle** [comment]
Is this just a warning?  Or does this block publication?

**Comment by goderbauer** [comment]
It's a warning and `pub` asks you if you want to continue publishing ignoring the warnings.

**Comment by zoechi** [comment]
Closing as dup of #17168 because there is more activity
