### ISSUE TITLE
[macOS] how to make it more macOS style on macOS build?

### ISSUE THREAD

**Issue by jinfagang** [flutter/flutter#100018]
Hi, the titlebar how to make it more like macOS design style?

Current:

<img width="800" alt="image" src="https://user-images.githubusercontent.com/21303438/158049675-722db389-a207-4e52-864c-1c24d4b35932.png">

want more like:

<img width="792" alt="image" src="https://user-images.githubusercontent.com/21303438/158049709-fb1a0ba3-6cf3-4170-b626-2401fd4fe882.png">

**Comment by darshankawar** [comment]
@jinfagang 
Please ask support questions on StackOverflow.
Closing from here.

**Comment by jinfagang** [comment]
@darshankawar this is not question.... feature request...

If you don't want feature requisition, then close this in your GitHub template ??

<img width="1190" alt="image" src="https://user-images.githubusercontent.com/21303438/158136705-1836f25b-5f3e-4322-a903-69f22d0565d4.png">

Besides, you don't answer my question if you don't know what I am talk about.

**Comment by darshankawar** [comment]
@jinfagang 
Apologies, but looking at the way you provided information and not enough details and just mentioned `how to make it more like macOS design style?`, it indicates you were looking for a solution / support on implementing the said feature.

Also, if you knew it was a feature request and also provided screenshot of the template for feature request, why you didn't use it ? If you would have used the feature request template, filled out requested details, it would have been considered as a genuine issue, but considering the fact that you didn't provide much details around it and just asked `how to do this`, either me or anybody else triaging would have done the same thing, as there was no way for us to know it was a feature request or a general question.
