### ISSUE TITLE
Issue in creating flutter build ios. Error in flutter header file

### ISSUE THREAD

**Issue by FirstSource-cyber** [flutter/flutter#100039]
im using flutter 2.10.3. When i run app its working fine. but when i try to to run "Flutter build ios". i get Flutter header issue.
"Flutter/Flutter.h" file not found
"webview_flutter_wkwebview-2.7.1/ios/Classes/FlutterWebView.h:4:8

These are those packages which i m using.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

  image_picker: ^0.8.4+11
  sn_progress_dialog: ^1.0.3
  flutter_spinkit: ^5.1.0
  country_code_picker: ^2.0.2
  cupertino_date_textbox: ^1.0.1
  firebase_auth: ^3.3.10
  toast: ^0.1.5
  firebase_core: ^1.13.1
  email_validator: ^2.0.1  
  dio: ^4.0.4
  shared_preferences: ^2.0.13
  firebase_messaging: ^11.2.10
  cloud_firestore: ^3.1.10
  firebase_storage: ^10.2.9
  dash_chat: ^1.1.16
  flutter_chat_bubble: ^2.0.0
  photo_view: ^0.13.0
  video_player: ^2.3.0
  swipe_to: ^1.0.2
  video_thumbnail: ^0.4.6
  cached_network_image: ^3.2.0
  chewie: ^1.3.0
  rflutter_alert: ^2.0.4
  intl: ^0.17.0
  multi_image_picker2: ^5.0.2
  flutter_html: ^2.2.1
  flutter_launcher_icons: ^0.9.2
  easy_localization: ^3.0.0
  dots_indicator: ^2.1.0
  carousel_slider: ^4.0.0
  flutter_colorpicker: ^1.0.3
  google_sign_in: ^5.2.4
  twitter_login: ^4.0.1
  flutter_login_facebook: ^1.4.1
  email_auth: ^1.0.0
  font_awesome_flutter: ^9.2.0
  sign_in_with_apple: ^3.3.0
  share_plus: ^3.1.0
  flutter_speed_dial: ^5.0.0+1
  pin_code_fields: ^7.3.0

**Comment by darshankawar** [comment]
@FirstSource-cyber 
Can you provide `flutter doctor -v`, `flutter run -v` and `ios/podfile` ?
The verbose log will be huge so you can put that in a text file and share it here.
