### ISSUE TITLE
HtmlElementView cannot be screenshotted in Flutter Web

### ISSUE THREAD

**Issue by venshine** [flutter/flutter#100016]
I wrapped the HtmlElementView widget using the RepaintBoundary, tried to take a screenshot, but reported the error.
```
Unexpected null value.
```
---
flutter doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.3, on macOS 12.2.1 21D62 darwin-x64, locale
    zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.1.2)
[✓] VS Code (version 1.64.2)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

• No issues found!
```

**Comment by darshankawar** [comment]
@venshine 
Can you provide [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that shows the issue ?
Thanks.

**Comment by venshine** [comment]
class RepaintBoundaryPage extends StatefulWidget {
  @override
  _RepaintBoundaryPageState createState() => _RepaintBoundaryPageState();
}

class _RepaintBoundaryPageState extends State<RepaintBoundaryPage> {
  GlobalKey _rootWidgetKey = GlobalKey();
  List<Uint8List> _images = List();

  Future<Uint8List> _capturePng(
    GlobalKey globalKey, {
    double pixelRatio = 1.0, 
  }) async {
    try {
      RenderRepaintBoundary boundary =
          globalKey.currentContext.findRenderObject();
      var image = await boundary.toImage(pixelRatio: pixelRatio);
      ByteData byteData = await image.toByteData(format: ImageByteFormat.png);
      Uint8List pngBytes = byteData.buffer.asUint8List();
      return pngBytes;
    } catch (e) {
      print(e);
    }
    return null;
  }

  ///build
  @override
  Widget build(BuildContext context) {
    return RepaintBoundary(
      key: _rootWidgetKey,
      child: Scaffold(
        appBar: AppBar(
          title: Text("flutter widget screenshot"),
        ),
        body: Column(
          children: <Widget>[
            IframeView(source: "https://www.google.com")),
            FlatButton(
              onPressed: () {
                Future<Uint8List> pngBytes = _capturePng(_rootWidgetKey);
                pngBytes.then((Uint8List value) {
                  _images.add(value);
                });
                setState(() {});
              },
              child: Text("whole screen screenshot"),
            ),
            Expanded(
              child: ListView.builder(
                itemBuilder: (context, index) {
                  return Image.memory(
                    _images[index],
                    fit: BoxFit.cover,
                  );
                },
                itemCount: _images.length,
                scrollDirection: Axis.horizontal,
              ),
            )
          ],
        ),
      ),
    );
  }
}

class IframeView extends StatefulWidget {
  final String source;

  const IframeView({Key key, @required this.source}) : super(key: key);

  @override
  _IframeViewState createState() => _IframeViewState();
}

class _IframeViewState extends State<IframeView> {
  // Widget _iframeWidget;
  final IFrameElement _iframeElement = IFrameElement();

  @override
  void initState() {
    super.initState();
    _iframeElement.src = widget.source;
    _iframeElement.style.border = 'none';

    //ignore: undefined_prefixed_name
    ui.platformViewRegistry.registerViewFactory(
      widget.source, //use source as registered key to ensure uniqueness
      (int viewId) => _iframeElement,
    );
  }

  @override
  Widget build(BuildContext context) {
    return HtmlElementView(
      key: UniqueKey(),
      viewType: widget.source,
    );
  }
}

**Comment by darshankawar** [comment]
@venshine 
The code you provided is giving me compile errors:

<img width="604" alt="Screenshot 2022-03-28 at 10 51 34 AM" src="https://user-images.githubusercontent.com/67046386/160331412-9c3afa91-52c5-4d7f-ac58-2381be364cd6.png">


Please provide a complete runnable code sample.
