### ISSUE TITLE
Cannot run app anymore

### ISSUE THREAD

**Issue by SwiftyFlow** [flutter/flutter#100196]
I was having a perfectly running app. That I published twice on PlayStore but first people couldn't see the app launcher icon, then when they do it's crashing on opening. Trying to resolve all that I have upgraded flutter along with my pubs, and changed a few minSdkVersion and compileSdkVersion. I guess in too many places along with some applicationId and package name. i.e.: 

```
defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.appwithflow.e_scoot_speed"
        minSdkVersion 31 //flutterMinSdkVersion
        targetSdkVersion flutter.targetSdkVersion
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        multiDexEnabled true
    }
```

Now all I get is:

```
Launching lib[/main.dart]() on Android SDK built for x86 in debug mode...
lib/main.dart:1

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Build file '[/Users/flowpottevin/Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/audio_session-0.1.6]()+1[/android/build.gradle]()' line: 29

* What went wrong:
A problem occurred evaluating project ':audio_session'.
> No signature of method: build_c9aak7fa47trju71i8h669gri.android() is applicable for argument types: (build_c9aak7fa47trju71i8h669gri$_run_closure3) values: [build_c9aak7fa47trju71i8h669gri$_run_closure3@bb0a847]

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* Where:
Script '[/Users/flowpottevin/Desktop/flutter/packages/flutter_tools/gradle/flutter.gradle]()' line: 471

* What went wrong:
A problem occurred configuring project ':audio_session'.
> Failed to notify project evaluation listener.
   > Cannot invoke method substring() on null object
   > compileSdkVersion is not specified. Please add it to build.gradle

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at [https://help.gradle.org]()

BUILD FAILED in 2s
Exception: Gradle task assembleDebug failed with exit code 1
Exited
```

**Comment by SwiftyFlow** [comment]
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.appwithflow.e_scoot_speed">
    <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_BACKGROUND_LOCATION" />
   <application
        android:label="eScoot"
        android:name="${applicationName}"
        android:icon="@mipmap/ic_launcher">
        <activity
            android:name=".MainActivity"
            android:exported="true"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            
            <meta-data
              android:name="${applicationName}"
              android:resource="@style/NormalTheme"
              />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
        
        <meta-data
            android:name="flutterEmbedding"
            android:value="2"/>
    </application>
</manifest>

**Comment by SwiftyFlow** [comment]
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '2'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.1'
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

def keystoreProperties = new Properties()
   def keystorePropertiesFile = rootProject.file('key.properties')
   if (keystorePropertiesFile.exists()) {
       keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
   }

android {
    compileSdkVersion flutter.compileSdkVersion
    ndkVersion flutter.ndkVersion

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.appwithflow.e_scoot_speed"
        minSdkVersion 31 //flutterMinSdkVersion
        targetSdkVersion flutter.targetSdkVersion
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        multiDexEnabled true
    }

    signingConfigs {
       release {
           keyAlias keystoreProperties['keyAlias']
           keyPassword keystoreProperties['keyPassword']
           storeFile keystoreProperties['storeFile'] ? file(keystoreProperties['storeFile']) : null
           storePassword keystoreProperties['storePassword']
       }
   }
   buildTypes {
       debug {
           signingConfig signingConfigs.debug
       }
       release {
           signingConfig signingConfigs.release
       }
   }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
}

**Comment by SwiftyFlow** [comment]
flutter doctor -v 
[✓] Flutter (Channel master, 2.13.0-0.0.pre.103, on macOS 12.2.1 21D62 darwin-x64, locale en-AU)
    • Flutter version 2.13.0-0.0.pre.103 at /Users/flowpottevin/Desktop/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 509ddfda5c (4 hours ago), 2022-03-15 21:10:18 -0700
    • Engine revision dc22c4c7fe
    • Dart version 2.17.0 (build 2.17.0-202.0.dev)
    • DevTools version 2.11.4

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/flowpottevin/Library/Android/sdk
    • Platform android-31, build-tools 32.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.65.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.36.0

[✓] Connected device (3 available)
    • Android SDK built for x86 (mobile) • emulator-5554                            • android-x86    • Android 11 (API 30) (emulator)
    • iFlow (mobile)                     • 0379838d26bde736d64b93cf101ac0917dd7a46d • ios            • iOS 15.3.1 19D52
    • Chrome (web)                       • chrome                                   • web-javascript • Google Chrome 99.0.4844.51
    ! Error: iPhone 8 is not connected. Xcode will continue when iPhone 8 is connected. (code -13)

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Comment by SwiftyFlow** [comment]
name: e_scoot_speed
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.1+4

environment:
  sdk: ">=2.17.0-141.0.dev <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  sensors_plus: ^1.3.0
  carousel_slider: ^4.0.0
  just_audio: ^0.9.20
  provider: ^6.0.2
  shared_preferences: ^2.0.13
  unity_ads_plugin: ^0.3.2
  webview_flutter: ^3.0.1
  in_app_review: ^2.0.4
  flutter_mailer: ^2.0.0
  flutter_sms: ^2.3.2
  package_info_plus: ^1.3.0
  geolocator: ^8.2.0
  material_segmented_control: ^3.1.2
  unity_ads_mediation: ^1.0.1
  app_tracking_transparency: ^2.0.2+1
  google_mobile_ads: ^1.1.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.2
  
flutter_icons:
  android: true
  ios: true
  image_path: "dev_images/app-icon.png"
  adaptive_icon_background: "#7F8596"
  adaptive_icon_foreground: "dev_images/app-icon-adaptive.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/assets/
    - lib/assets/images/
    - assets/sounds/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

**Comment by SwiftyFlow** [comment]
pubspec:



name: e_scoot_speed
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.1+4

environment:
  sdk: ">=2.17.0-141.0.dev <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  sensors_plus: ^1.3.0
  carousel_slider: ^4.0.0
  just_audio: ^0.9.20
  provider: ^6.0.2
  shared_preferences: ^2.0.13
  unity_ads_plugin: ^0.3.2
  webview_flutter: ^3.0.1
  in_app_review: ^2.0.4
  flutter_mailer: ^2.0.0
  flutter_sms: ^2.3.2
  package_info_plus: ^1.3.0
  geolocator: ^8.2.0
  material_segmented_control: ^3.1.2
  unity_ads_mediation: ^1.0.1
  app_tracking_transparency: ^2.0.2+1
  google_mobile_ads: ^1.1.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.2
  
flutter_icons:
  android: true
  ios: true
  image_path: "dev_images/app-icon.png"
  adaptive_icon_background: "#7F8596"
  adaptive_icon_foreground: "dev_images/app-icon-adaptive.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/assets/
    - lib/assets/images/
    - assets/sounds/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

**Comment by SwiftyFlow** [comment]
Also can someone explain to me why the **** do I have so many of these /example crap apps because I surely changed shit in there so now what I restart a new project and put all my files in it???

![Screen Shot 2022-03-16 at 9 18 43 am](https://user-images.githubusercontent.com/5778905/158546694-b036f707-7012-4250-a2ce-21355f241540.png)

**Comment by darshankawar** [comment]
> Also can someone explain to me why the **** do I have so many of these /example crap apps because I surely changed shit in there so

@SwiftyFlow I urge you to please visit [github code of conduct](https://docs.github.com/en/site-policy/github-terms/github-event-code-of-conduct#code-of-conduct) and also please refrain commenting like this.

**Comment by darshankawar** [comment]
From the logs you shared, it seems to be pointing to `audio_session` plugin you are using and it seems to be incompatible with changes you made. Also below error shows why it could be throwing the error:

```
* What went wrong:
A problem occurred configuring project ':audio_session'.
> Failed to notify project evaluation listener.
   > Cannot invoke method substring() on null object
   > compileSdkVersion is not specified. Please add it to build.gradle
```

Another error:

```
* What went wrong:
A problem occurred evaluating project ':audio_session'.
> No signature of method: build_c9aak7fa47trju71i8h669gri.android() is applicable for argument types:
```

For which you can check [this](https://stackoverflow.com/questions/66292426/how-do-you-fix-the-following-error-a-problem-occurred-evaluating-project-app) SO link and see if it helps.

With this, I am going ahead and closing this, as the errors are pointing to third party plugin. If you disagree, write in comments and I'll reopen it.
