### ISSUE TITLE
Support tabbar divider

### ISSUE THREAD

**Issue by xpwmaosldk** [flutter/flutter#100191]
Hi there,

It's very simple and many people want
but flutter tabbar is not support.

I can make it somehow(dirty way), but I want to it by default.

Flutter is very cool but I often disappointed with these little things :(

![image](https://user-images.githubusercontent.com/13146337/158522231-075e4783-7cab-4a63-9e0b-5e19d49c4d87.png)

**Comment by darshankawar** [comment]
@xpwmaosldk 
There are lot of solutions available on support channels like StackOverflow where you can find ways to implement it. See below for example:

https://github.com/flutter/flutter/issues/new?assignees=&labels=&template=2_bug.md&title=

You may also check on pub.dev if there's a community plugin which offers this feature already.

Also, not all features and functionalities can be implemented in the framework and hence there are workarounds / solutions or plugins available that provides the features.

The TabBar is implemented based on the material design https://material.io/components/tabs/flutter and hence it may not contain / be feasible to provide divider in it.

Alternatively, you can also take a look at [Divider](https://api.flutter.dev/flutter/material/VerticalDivider-class.html) class and see if it helps to achieve your use case.
With this, I am going ahead and closing this, as your use case can be achieved with existing solutions.
If you disagree, write in comments and I'll reopen it.
