### ISSUE TITLE
Select Widget Mode results in a red screen with error

### ISSUE THREAD

**Issue by jmysliv** [flutter/flutter#100121]
## Steps to Reproduce

1. Run the app
2. In the Flutter DevTools click on `Select Widget Mode`
3. The app screen turns red with an error message displayed

**Expected results:** 

I should be able to use `Select Widget Mode`

**Actual results:** 

Immediately after clicking on `Select Widget Mode` I'm receiving the error like in the attached screenshot.

![Simulator Screen Shot - iPhone 13 - 2022-03-14 at 10 42 55](https://user-images.githubusercontent.com/48885911/158347342-c8e1301e-d1ef-4a0b-b0fb-f3e6f6cdc8ad.png)

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @jmysliv,

Can you please provide your `flutter doctor -v` and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?

Thank you

**Comment by jmysliv** [comment]
@danagbemava-nc 

here's the output of `flutter doctor -v`
```
flutter doctor -v                                                                                                                                                                                                                             
[✓] Flutter (Channel stable, 2.10.3, on macOS 12.0.1 21A559 darwin-arm, locale en-PL)
    • Flutter version 2.10.3 at /Users/jakubmysliwiec/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (13 days ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/jakubmysliwiec/Library/Android/sdk
    • Platform android-32, build-tools 32.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] IntelliJ IDEA Community Edition (version 2021.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.65.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.36.0

[✓] Connected device (2 available)
    • iPhone 13 (mobile) • DEDC6062-A205-4343-8465-C671D1E664ED • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 99.0.4844.51

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

I can't provide you with the full code of the app, I will try to create some an app.

In the meantime could you tell me for what widget exactly `Select Widget Mode` is looking? Do you have any ideas about what might be an issue here?

**Comment by danagbemava-nc** [comment]
That will be difficult to tell as toggling `Select Widget Mode` doesn't automatically select a widget, it does however rebuild your app. See https://github.com/flutter/flutter/issues/31939#issuecomment-949973524 for more information.

**Comment by jmysliv** [comment]
@danagbemava-nc  thanks, however, it didn't help me in resolving my issue.

**Comment by danagbemava-nc** [comment]
Hi @jmysliv, that comment was meant to provide more context as to what might be happening. We will need a minimal reproducible code sample so that we can get to the bottom of whatever is causing this issue.

**Comment by jmysliv** [comment]
Hi @danagbemava-nc after investigation it seemed to be a flutter navigation package issue (`beamer`). After we migrated to `go_router` the problem've disappeared. Thanks for the help anyway! 🙂
