### ISSUE TITLE
Cursor issue in Flutter web in Arabic language - RTL.

### ISSUE THREAD

**Issue by muhammadkamel** [flutter/flutter#100195]
I have an issue with the cursor when I am typing in Text Form Filed - RTL.
![Screen Shot 2022-03-16 at 9 40 06 AM](https://user-images.githubusercontent.com/17657941/158540666-fc8e1acc-5e88-4a23-bda8-9e4ede5039fe.png)

The cursor should be at the end of the text.
![Screen Shot 2022-03-16 at 9 44 11 AM](https://user-images.githubusercontent.com/17657941/158540883-ebe85ace-fbe0-45f5-9f5d-a2a7d3d77093.png)

**Comment by darshankawar** [comment]
@muhammadkamel 
Please check this similar issue and see if it is similar to your case or not: https://github.com/flutter/flutter/issues/81013
The linked issue seems to be happening using html rendering. Is it same for you too ?

**Comment by muhammadkamel** [comment]
No, the main issue related to two things:
1- Text Direction RTL even with (English Text).
2- Arabic Text - RTL.

**Comment by darshankawar** [comment]
Thanks for the update.
I think you are hitting https://github.com/flutter/flutter/issues/78550, so please follow-up in it for further updates.
Closing this as a duplicate.
