### ISSUE TITLE
Shared Preferences Missing Plugin Exception

### ISSUE THREAD

**Issue by Sachinsowri** [flutter/flutter#100114]
While using Shared preference in top level function(Work Manager android Call back funciton)
trigger this Exception how to solve this issue
Unhandled Exception: MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences)

Flutter 2.10.3
shared_preferences: ^2.0.13
workmanager: ^0.4.1

kotlin_version = '1.6.10'
classpath 'com.android.tools.build:gradle:4.1.2'

gradle properties distributionUrl=https\://services.gradle.org/distributions/gradle-6.5-all.zip

**Comment by darshankawar** [comment]
@Sachinsowri 
A similar issue was fixed recently https://github.com/flutter/flutter/issues/98473.
Can you switch to latest master and try again ? Also see [this](https://github.com/flutter/flutter/issues/98473#issuecomment-1058500136) issue comment for your reference.

```
flutter channel master
flutter upgrade
```

**Comment by Sachinsowri** [comment]
@darshankawar  thank you
