### ISSUE TITLE
Google Font Icon request: factory

### ISSUE THREAD

**Issue by Govindbetterlives** [flutter/flutter#100194]
Need this icon for flutter - factory

**Comment by danagbemava-nc** [comment]
The `factory` icon is already available in flutter (stable 2.10.3) under the name `factory`. See screenshots below. 
Closing as this icon already exists.

<img src="https://user-images.githubusercontent.com/88313112/158537506-e9924286-056c-4fa8-8ade-f89c2e530d2f.png" width="200" />
