### ISSUE TITLE
[android] `multidex` and `minSdkVersion`

### ISSUE THREAD

**Issue by asashour** [flutter/flutter#100125]
## Use case

On importing more dependencies, one would encounter the need to enable multidex, with having the below messages, however, it doesn't hint that with only upgrading to `minSdkVersion` of 21 (Android 5, released 2014) can fix the issue.

```Execution failed for task ':app:mergeDexDebug'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: 
     The number of method references in a .dex file cannot exceed 64K.
     Learn how to resolve this issue at https://developer.android.com/tools/building/multidex.html
```

and
```
┌─ Flutter Fix ──────────────────────────────────────────────────────────────────────────────────┐
│ Flutter multidex handling is disabled. If you wish to let the tool configure multidex, use the │
│ --multidex flag.                                                                               │
└────────────────────────────────────────────────────────────────────────────────────────────────┘
```

_Update:_

I am seeing on `master` the below message, still it doesn't hint about `minSdkVersion`

```
Multidex support is required for your android app to build since the number of methods has exceeded 64k. You may pass the --no-multidex flag to skip Flutter's     
    multidex support to use a manual solution.

    Flutter tool can add multidex support. The following file will be added by flutter:

        android/app/src/main/java/io/flutter/app/FlutterMultiDexApplication.java
```

## Proposal

Change the message to be something like:

```
┌─ Flutter Fix ──────────────────────────────────────────────────────────────────────────────────┐
│ Flutter multidex handling is disabled. If you wish to let the tool configure multidex, use the │
│ --multidex flag, or set minSdkVersion to 21                                                    │
└────────────────────────────────────────────────────────────────────────────────────────────────┘
```

**Comment by GaryQian** [comment]
It is reasonable to make a note that increasing min-sdk to 21 would solve this issue, but the reason this was not initially included in the help text is that we don't recommend developers bump the min sdk version to 21 purely to support multidex. Doing so would inadvertently drop support for a non-trivial amount of devices, mostly in developing countries.

If we were to add a hint to suggest bumping to 21, we would have to make it clear that there is a way to support multidex without this bump and the flutter multidex handling system is the preferred way to resolve this issue.

**Comment by christopherfujino** [comment]
> It is reasonable to make a note that increasing min-sdk to 21 would solve this issue, but the reason this was not initially included in the help text is that we don't recommend developers bump the min sdk version to 21 purely to support multidex. Doing so would inadvertently drop support for a non-trivial amount of devices, mostly in developing countries.
> 
> If we were to add a hint to suggest bumping to 21, we would have to make it clear that there is a way to support multidex without this bump and the flutter multidex handling system is the preferred way to resolve this issue.

Ahh, I see. Do we have any Flutter documentation on multidex? It sounds like if we drop a hint in the error message devs will just apply it, without considering the consequences to unblock themselves.

**Comment by GaryQian** [comment]
We currently just depend on the message in the tool when it detects the multidex issue. We should probably link to more detailed documentation on this though.

**Comment by GaryQian** [comment]
https://github.com/flutter/flutter/pull/104558 Adds link to more detailed docs.
