### ISSUE TITLE
Cannot add proguard-rules.pro for flutter aar.

### ISSUE THREAD

**Issue by wangmir** [flutter/flutter#100198]
I have a problem with flutter aar when Android application which embed flutter aar trying to minify the app.

The app is currently like,

Android app reference flutter module.
Flutter module references plugin which uses retrofit2 library.

When using retrofit library, data class should be in proguard-rules.pro to prevent minify.

So, where should we put the proguard-rules.pro and minify enabled.
I saw this manual, https://flutter-ko.dev/docs/deployment/android#step-1---proguard-%EA%B5%AC%EC%84%B1%ED%95%98%EA%B8%B0

but how can we do that when using flutter aar since flutter aar has no editable MainActivity and build.gradle (since .android/ is autogenerated)?

**Comment by darshankawar** [comment]
@wangmir 
Can you try by including the `aar` as `implementation fileTree(dir: 'libs', include: ['*.aar'])` inside plugin's build.gradle ?

If this doesn't help, can you provide all relevant details for below use case you mentioned ?

```
Android app reference flutter module.
Flutter module references plugin which uses retrofit2 library.

When using retrofit library, data class should be in proguard-rules.pro to prevent minify.
```

**Comment by wangmir** [comment]
@darshankawar 
I can't do as u mentioned because currently our aar will be uploaded to AwsCodeArtifact, thus referece should be done with maven repository.

But, in the meanwhile, adding proguard-rules.pro to the host app (Android app) and plugin was working.

In summary,

### Android host application (which uses flutter aar)

Android application should be the only minifyEnabled place.

1. build.gradle of Android app
```gradle
release {
    minifyEnabled true
    proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
    signingConfig signingConfigs.debug
}
```

2. proguard-rules.pro

```
## Flutter wrapper
-keep class io.flutter.app.** { *; }
-keep class io.flutter.plugin.**  { *; }
-keep class io.flutter.util.**  { *; }
-keep class io.flutter.view.**  { *; }
-keep class io.flutter.**  { *; }
-keep class io.flutter.plugins.**  { *; }
-keep class io.flutter.embedding.**  { *; }
-dontwarn io.flutter.embedding.**
```

### Android-side code of Flutter plugin (which will be used by flutter aar)

1. build.gradle
```gradle
release {
    minifyEnabled false
    useProguard true
    consumerProguardFiles 'proguard-rules.pro' // note that consumerProguardFiles
}
```

2. proguard-rules.pro
```
## Flutter wrapper
-keep class io.flutter.app.** { *; }
-keep class io.flutter.plugin.**  { *; }
-keep class io.flutter.util.**  { *; }
-keep class io.flutter.view.**  { *; }
-keep class io.flutter.**  { *; }
-keep class io.flutter.plugins.**  { *; }
-keep class io.flutter.embedding.**  { *; }
-dontwarn io.flutter.embedding.**

## plugin-specifics
-keep class ur.app.data.entities.** { *; }
```

**Comment by darshankawar** [comment]
> thus referece should be done with maven repository.

Does using maven repo help ?



> But, in the meanwhile, adding proguard-rules.pro to the host app (Android app) and plugin was working.

Does this solve your original issue reported ?

**Comment by wangmir** [comment]
> > thus referece should be done with maven repository.
> 
> Does using maven repo help ?
> 
> > But, in the meanwhile, adding proguard-rules.pro to the host app (Android app) and plugin was working.
> 
> Does this solve your original issue reported ?

@darshankawar yes, I think this can be closed.
