### ISSUE TITLE
[integration_test] Not able to tap button while infinite animation is running

### ISSUE THREAD

**Issue by SureshMiOS** [flutter/flutter#100130]
I have a screen which contains infinite animation on top of the screen. I have few buttons on the same screen. I am not able to tap those buttons using tester. I am getting pumpAndSettle timed out exception. I am using package integration_test version ^1.0.2+3. Could you please update me how to do the tap and scroll actions while infinite animation is going on.

I/flutter (31472): ══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
I/flutter (31472): The following assertion was thrown running a test:
I/flutter (31472): pumpAndSettle timed out
I/flutter (31472): 
I/flutter (31472): When the exception was thrown, this was the stack:
I/flutter (31472): #0      WidgetTester.pumpAndSettle.<anonymous closure> (package:flutter_test/src/widget_tester.dart:671:11)
I/flutter (31472): <asynchronous suspension>
I/flutter (31472): #1      TestAsyncUtils.guard.<anonymous closure> (package:flutter_test/src/test_async_utils.dart)
I/flutter (31472): <asynchronous suspension>
I/flutter (31472): 
I/flutter (31472): The test description was:
I/flutter (31472):   End to end app test
I/flutter (31472): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (31472): 11:15 +0: End to end app test [E]
I/flutter (31472):   'package:flutter_test/src/binding.dart': Failed assertion: line 785 pos 14: '_pendingExceptionDetails != null': A test overrode FlutterError.onError but either failed to
return it to its original state, or had unexpected additional errors that it could not handle. Typically, this is caused by using expect() before restoring FlutterError.onError.
I/flutter (31472):   dart:core-patch/errors_patch.dart 46:39       _AssertionError._doThrowNew
I/flutter (31472):   dart:core-patch/errors_patch.dart 36:5        _AssertionError._throwNew
I/flutter (31472):   package:flutter_test/src/binding.dart 785:14  TestWidgetsFlutterBinding._runTest.handleUncaughtError
I/flutter (31472):   package:flutter_test/src/binding.dart 790:9   TestWidgetsFlutterBinding._runTest.<fn>
I/flutter (31472):   dart:async/zone.dart 1109:14                  _Zone._processUncaughtError
I/flutter (31472):   dart:async/zone.dart 1312:5                   _CustomZone.handleUncaughtError
I/flutter (31472):   dart:async/future_impl.dart 717:16            Future._propagateToListeners
I/flutter (31472):   dart:async/future_impl.dart 610:5             Future._completeError
I/flutter (31472):   dart:async-patch/async_patch.dart 274:13      _completeOnAsyncError
I/flutter (31472):   package:flutter_test/src/binding.dart         TestWidgetsFlutterBinding._runTestBody
I/flutter (31472):   
I/flutter (31472): Consider enabling the flag chain-stack-traces to receive more detailed exceptions.
I/flutter (31472): For example, 'dart test --chain-stack-traces'.
I/flutter (31472): 11:15 +0 -1: (tearDownAll)
I/flutter (31472): 11:15 +1 -1: Some tests failed.
All tests passed.

**Comment by maheshmnj** [comment]
Hi @SureshMiOS, Thanks for filing the issue. In order to investigate the issue further, We would need a minimal sample code along with the tests that you are running. Please also share the output of `flutter doctor -v`.

**Comment by maheshmnj** [comment]
Please try using `tester.pumpFrames`, We would need a minimal and complete sample code which has infinite animation to investigate this issue further.

**Comment by SureshMiOS** [comment]
I am using json for animation with Lottie package. Please have a look on sample code

 @override
  Widget build(BuildContext context) {
    return SingleChildScrollView(
      child: Column(
        children: [
          Lottie.network(
              'https://raw.githubusercontent.com/xvrh/lottie-flutter/master/example/assets/Mobilo/A.json'),
          SizedBox(height: 8,),
          TextButton(
              child: Text('Tap here'),
              onPressed: () {
                print('Pressed');
              }
          )
        ],
      ),
    );
  }

**Comment by maheshmnj** [comment]
@SureshMiOS I used `CircularProgressIndicator` as an Infinitely animating widget, This should work even with your Lottie animation. Please take a look at the below sample code and the respective integration test. When you have infinite animation instead of depending on `pump` or `pumpAndSettle` you may use `pumpFrames`

<details>
<summary>integration_test/app_test.dart</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:integration_test/integration_test.dart';

import 'package:test_app/main.dart' as app;

void main() {
  IntegrationTestWidgetsFlutterBinding.ensureInitialized();

  group('end-to-end test', () {
    testWidgets('tap on the button, verify count', (WidgetTester tester) async {
      await tester.pumpFrames(const app.MyApp(), const Duration(seconds: 2));
      final button = find.byType(TextButton);
      final count_0 = find.text('0');
      expect(count_0, findsOneWidget);
      await tester.tap(button);
      await tester.pumpFrames(app.MyApp(), Duration(seconds: 2));
      final count_1 = find.text('1');
      expect(count_1, findsOneWidget);
    });
  });
}
```
</details> 

<details>
<summary>sample app</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      title: 'Counter App',
      home: MyHomePage(title: 'Counter App Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  int count = 0;
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: Text(widget.title),
        ),
        body: SingleChildScrollView(
          child: Column(
            children: [
              const CircularProgressIndicator(),
              const SizedBox(
                height: 8,
              ),
              Text('$count'),
              Center(
                child: TextButton(
                    child: const Text('Tap here'),
                    onPressed: () {
                      print('Pressed');
                      setState(() {
                        count++;
                      });
                    }),
              )
            ],
          ),
        ));
  }
}

```
</details> 
 
#### logs

```console
mahesh@Maheshs-MacBook-Air-M1 test_app % flutter test integration_test/app_test.dart
00:00 +0: loading /Users/mahesh/Desktop/test_app/integration_test/app_test.dart                                                                                   RWarning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
00:16 +0: loading /Users/mahesh/Desktop/test_app/integration_test/app_test.dart                                                                              16.4s
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
00:17 +0: loading /Users/mahesh/Desktop/test_app/integration_test/app_test.dart                                                                                   I00:42 +0: loading /Users/mahesh/Desktop/test_app/integration_test/app_test.dart                                                                              24.8s
00:50 +0: end-to-end test tap on the button, verify count                                                                                                         
Pressed
00:55 +1: All tests passed!                                                                                                                                       
mahesh@Maheshs-MacBook-Air-M1 test_app % 
```


<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel stable, 2.10.3, on macOS 12.1 21C52 darwin-arm, locale en-GB)
    • Flutter version 2.10.3 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (20 hours ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.36.0

[✓] Connected device (3 available)
    • Redmi K20 Pro (mobile) • 192.168.1.5:5555 • android-arm64  • Android 11 (API 30)
    • macOS (desktop)        • macos            • darwin-arm64   • macOS 12.1 21C52 darwin-arm
    • Chrome (web)           • chrome           • web-javascript • Google Chrome 99.0.4844.51

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

Closing as solved, In case you still encounter the issue, feel free to write in the comments and we will reopen it.

Thank you.
