### ISSUE TITLE
[Fonts] Icon request: rocket_launch

### ISSUE THREAD

**Issue by david201606** [flutter/flutter#100102]

**Comment by danagbemava-nc** [comment]
The icon is already available in `stable` 2.10.3, the material icons site just hasn't been updated yet. You can find it under the name `rocket_launch`. Closing as the icon already exists. 

<img src="https://user-images.githubusercontent.com/88313112/158334847-f304cde4-333b-4386-b256-49b81f15e227.png" width="200" />
