### ISSUE TITLE
[Proposal] Add percent Icon

### ISSUE THREAD

**Issue by irshad-hz** [flutter/flutter#100131]

**Comment by maheshmnj** [comment]
Hi @irshad-hz, Thanks for filing the issue. I believe you are proposing to add Percent Icons from Material Icons is that correct? if so, Flutter already has a percent Icon please see https://api.flutter.dev/flutter/material/Icons-class.html

<img width="475" alt="image" src="https://user-images.githubusercontent.com/31410839/158380064-8d4ad62e-0c58-4076-8cfd-63e3bc6c1642.png">
