### ISSUE TITLE
Can not install my flutter app on Android12

### ISSUE THREAD

**Issue by liqiang1995** [flutter/flutter#100107]
My app's targetSdkVersion is 31
I can not install it on Pixel6.
I added `android:exported` to the AndroidManifest.xml file
Also I checked the merged AndroidManifest.xml file.
all activities, services, receivers have `android:exported`.
but i can not install the app on Android12 phones.
What should i do more?

**Comment by maheshmnj** [comment]
Hi @liqiang1995, Thanks for filing the issue. Your issue looks similar to https://github.com/flutter/flutter/issues/98256 which was fixed on the master channel. Please share the output of `flutter doctor -v` and the error logs that you see when the install fails.
