### ISSUE TITLE
linux/mac beta customer testing failing for release

### ISSUE THREAD

**Issue by XilaiZhang** [flutter/flutter#100266]
while running post submit checks for release branch flutter-2.12-candidate.4, linux/mac beta customer testing consistently fail, relevant build logs are: https://luci-milo.appspot.com/ui/p/flutter/builders/prod/Linux%20beta%20customer_testing/130/overview and https://luci-milo.appspot.com/ui/p/flutter/builders/prod/Mac%20beta%20customer_testing/126/overview

**Comment by godofredoc** [comment]
This is happening because git branch is being calculated as:

`GIT_BRANCH: * (HEAD detached at FETCH_HEAD)`

**Comment by XilaiZhang** [comment]
I have learnt a lot about how recipes work, and understood a decent amount of the variables. After a lot of trials I realized that cloning the repo might be the best way to debug.  I haven't quite finished debugging yet, and I have documented the steps I have tried out so far at : https://docs.google.com/document/d/1vF2QNKIQgDrhupO4VYcislU--vKp2qQenJ3jZxdZ0ws/edit?resourcekey=0-t6Xya2ETEX7NU8vjpDYF4w#

**Comment by XilaiZhang** [comment]
cl submitted at https://flutter-review.googlesource.com/c/recipes/+/28563

**Comment by rzr** [comment]
merged in dfdfca1cc7aff0b27be8e9274f391a82f99f68de

**Comment by godofredoc** [comment]
Closing as obsolete, these tests are not running anymore on release candidate branches.
