### ISSUE TITLE
Exception in thread "main" java.lang.RuntimeException

### ISSUE THREAD

**Issue by Ahmedabdelalem61** [flutter/flutter#100211]
I get this message after importing these packages

![Screenshot from 2022-03-16 13-33-04](https://user-images.githubusercontent.com/47370980/158581138-03d3a007-7df0-4cb0-855c-63606879fd17.png)

this happened after upgrading the flutter sdk to Flutter 2.10.3 
and i'm still stuck with that.

**Comment by darshankawar** [comment]
@Ahmedabdelalem61 
`Timeout of 120000 reached waiting for exclusive access`  probably indicates a slow internet network. So try to switch to a high speed network and see if it helps.

Also check [this](https://github.com/flutter/flutter/issues/34210#issuecomment-583773525) issue comment for your reference.

Closing this from here.

**Comment by Ahmedabdelalem61** [comment]
thanks a lot, when I run  `flutter docotor` I founded that the problem from HTTP Host Availability and I found the solution from [here](https://blog.csdn.net/ouhuanquan/article/details/123134340) and it works well .
