### ISSUE TITLE
Disable Marker Position Animation

### ISSUE THREAD

**Issue by haoyuant** [flutter/flutter#100283]
Hello, is there a way to disable the marker animation when changing its position? Currently, if I change the position, the marker will slowly move to the new position which is not good in my use case.

**Comment by darshankawar** [comment]
@haoyuant 
I think your question is better suited for support channels like Stackoverflow where you can get answers on your question.
Closing from here, as this is more of a general question. If you disagree or would like to propose the same as a feature request for the plugin, write in comments and I'll reopen it.
