### ISSUE TITLE
Forgetting to register plugins in add-to-app causes confusing error `PlatformException(unregistered_view_type, trying to create a view with an unregistered type, unregistered view type: 'plugins.flutter.io/google_maps', null)`

### ISSUE THREAD

**Issue by nikhilbhawsar** [flutter/flutter#100241]
Currently we are seeing issue with integrating flutter in our existing iOS project.
We are following document from [here](https://docs.flutter.dev/development/add-to-app/ios/project-setup#option-a---embed-with-cocoapods-and-the-flutter-sdk)
When we are calling flutterViewController (in main.dart file we have added our code for showing Googlemaps), it is just showing an empty view.
I have tested the same via `Runner.xcworkspace` project and there it is working fine, there we are able to see map properly.

I just want to understand is there any bug associated with integrating flutter as module using Pods.

Adding the sample project.
[maps.zip](https://github.com/flutter/flutter/files/8266888/maps.zip)

Steps to get this project running.

## Steps to Reproduce
1. Download the sample project
2. navigate to `maps/flutter/product_flutter` directory
3. run `flutter clean` followed by `flutter pub get`
4. move to main directory `maps`
5. now perform `pod install`
6. update the `API key` in `AppDelegate.swift` file
7. run the app and click on the center button
8. it should launch flutter view, having white screen.

**Expected results:** 

**Actual results:** 

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by darshankawar** [comment]
@nikhilbhawsar 
Thanks for the detailed report. I followed it (added api key) and ran it on device which does give me a white screen upon tapping on center button, as below:




It also throws below error in the console:

```
[VERBOSE-2:ui_dart_state.cc(198)] Unhandled Exception: PlatformException(unregistered_view_type, trying to create a view with an unregistered type, unregistered view type: 'plugins.flutter.io/google_maps', null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:167:18)
<asynchronous suspension>
#2      PlatformViewsService.initUiKitView (package:flutter/src/services/platform_views.dart:236:5)
<asynchronous suspension>
#3      _UiKitViewState._createNewUiKitView (package:flutter/src/widgets/platform_view.dart:639:44)
<asynchronous suspension>
2022-03-17 13:40:53.011912+0530 maps[9734:708287] fopen failed for data file: errno = 2 (No such file or directory)
2022-03-17 13:40:53.012052+0530 maps[9734:708287] Errors found! Invalidating cache...
2022-03-17 13:40:55.180950+0530 maps[9734:708287] fopen failed for data file: errno = 2 (No such file or directory)
2022-03-17 13:40:55.181101+0530 maps[9734:708287] Errors found! Invalidating cache...
```

Indicating it is not able to register the flutterview:

`unregistered_view_type, trying to create a view with an unregistered type, unregistered view type: 'plugins.flutter.io/google_maps', null)`

Can you try to regenerate the pods and try again to see if it helps ?

<img width="343" alt="Screenshot 2022-03-17 at 1 46 43 PM" src="https://user-images.githubusercontent.com/67046386/158766092-670936af-511a-4e8b-adba-dd9468849894.png">

**Comment by nikhilbhawsar** [comment]
Thanks @darshankawar 
I have tried following steps
1. `flutter clean` 
2. `flutter run`
3. `pod deintegrate`, followed by `derived data directory clean`
4. `pod install`
5. ran the project, still seeing the same error

```
2022-03-20 21:40:38.016185+0530 SiteRecon[35908:13700328] [VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: PlatformException(unregistered_view_type, trying to create a view with an unregistered type, unregistered view type: 'plugins.flutter.io/google_maps', null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:177:18)
<asynchronous suspension>
#2      PlatformViewsService.initUiKitView (package:flutter/src/services/platform_views.dart:236:5)
<asynchronous suspension>
#3      _UiKitViewState._createNewUiKitView (package:flutter/src/widgets/platform_view.dart:639:44)
<asynchronous suspension>
```

**Comment by darshankawar** [comment]
Thanks for confirming. I am going ahead and labeling it since I did observe same error. The platform-view getting created is somehow returning as unregistered_type.

<details>
<summary> stable, master flutter doctor -v </summary>

```

[✓] Flutter (Channel stable, 2.10.3, on macOS 12.2.1 21D62 darwin-x64, locale
    en-GB)
    • Flutter version 2.10.3 at /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (11 hours ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.


[✓] Flutter (Channel master, 2.13.0-0.0.pre.166, on macOS 12.2.1 21D62
    darwin-x64, locale en-GB)
    • Flutter version 2.13.0-0.0.pre.166 at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6af40a7004 (30 hours ago), 2022-03-19 19:15:23 -0400
    • Engine revision 900e3c0917
    • Dart version 2.17.0 (build 2.17.0-222.0.dev)
    • DevTools version 2.11.4

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.


```

</details>

**Comment by nikhilbhawsar** [comment]
Thanks @darshankawar 
I have one quick question about the fix for the same.
How long usually does it take to fix any issue?
We are asking as our release is blocked for this specific feature.
We are planning to integrate maps as part of flutter using google maps and targeting release by mid-April.
I have checked the document for releases over here - https://github.com/flutter/flutter/wiki/Flutter-build-release-channels

I see the stable change is over 3 months, which is too much. 
Can we get this resolved over beta and use the same?

**Comment by jmagman** [comment]
You aren't calling `GeneratedPluginRegistrant.register` anywhere.
https://docs.flutter.dev/development/add-to-app/ios/add-flutter-screen?tab=no-engine-vc-swift-tab#create-a-flutterengine
```swift
GeneratedPluginRegistrant.register(with: self.flutterEngine);
```

**Comment by nikhilbhawsar** [comment]
I don't know how come that line got removed from code. probably due to a typo.
The maps are working now for sure.

Thanks for pointing out the issue.

**Comment by jmagman** [comment]
Actually, reopening to improve this error message "Did you remember to call GeneratedPluginRegistrant.register" or similar
https://github.com/flutter/engine/blob/5a319bb4dc272b45bb9dd703a0dfa213939a51d7/shell/platform/darwin/ios/framework/Source/FlutterPlatformViews.mm#L142-L145
https://github.com/flutter/engine/blob/5a319bb4dc272b45bb9dd703a0dfa213939a51d7/shell/platform/darwin/macos/framework/Source/FlutterPlatformViewController.mm#L41-L43

**Comment by dacianf** [comment]
@jmagman I just created I PR to update the error message. #33450
