### ISSUE TITLE
Can't link to FlutterFire

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#10027]
We'd like to link to FlutterFire, a landing page for the new hotness.

**Comment by sethladd** [comment]
Because we envision a day where flutter/plugins/packages/firebase_* becomes firebase/flutterfire , we may want to consider moving flutter/plugins/packages/firebase_* into flutter/flutterfire to make it easy to transfer later. BONUS: if we do that, the landing page for FlutterFire could be (for now) a Wiki page in flutterfire repo. Or a GitHub page on that repo.

**Comment by mit-mit** [comment]
This would not be practical engineering wise. Can you clarify what you are trying to do? Link from where to achieve what?

**Comment by sethladd** [comment]
Things I want to achieve:

* A structure to make it easy to hand FlutterFire over to Firebase.
* A structure that makes it easy to contribute to FlutterFire.
* An easy, engineering-friendly way to host a landing page for FlutterFire that is not on flutter.io.

**Comment by mit-mit** [comment]
> A structure to make it easy to hand FlutterFire over to Firebase.

Moving a few folders from one repo (like `flutter/plugins`) to another (like `firebase/flutter`) is easy. We just moved these plugins from various other repos under flutter into the plugins repo.

> A structure that makes it easy to contribute to FlutterFire.

We have that with the current. Plus it's a huge bonus for developers to easily locate examples of various plugin implementations, which `flutter/plugins` facilitates.

> An easy, engineering-friendly way to host a landing page for FlutterFire that is not on flutter.io.

In your first comment you mentioned this could be a wiki page. Can't we just create a wiki page under `flutter/flutter` and then have a table of the various Firebase plugins ala:

| Plugin | Firebase feature | Source code |
|---|---|---|
| [firebase_analytics](https://pub.dartlang.org/packages/firebase_analytics) | Analytics | [firebase_analytics](https://github.com/flutter/plugins/tree/master/packages/firebase_analytics)
| etc. | etc. | etc. |

This could also be `/flutter/plugins/FlutterFire.md`.
