### ISSUE TITLE
DevTools version mismatched in flutter --version output and live DevTools instance

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/flutter#100247]
The DevTools version displayed in DevTools is not the same that is displayed from `flutter --version` (more details here).

@christopherfujino is there a chance that the version.json file is not getting updated? We grab the devtools version here: https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/cache.dart#L390 for use in the flutter --version output. Originally added in this [PR](https://github.com/flutter/flutter/pull/93065/).

This is reproducible on stable. Run `flutter/bin/dart devtools`, then look at the DevTools version in the bottom left when you open DevTools. Observe that this version is different from the one that is displayed when you run `flutter --version`.

**Comment by maheshmnj** [comment]
Hi @kenzieschmoll, Thanks for filing the issue. I see dev tools version mismatch only on the master channel. Please check the below output. Labeling this issue as a regression.

### stable

```console
mahesh@Maheshs-MacBook-Air-M1 test_app % which dart
/Users/mahesh/Documents/flutter/bin/dart
mahesh@Maheshs-MacBook-Air-M1 test_app % dart devtools
Serving DevTools at http://127.0.0.1:9101.

Hit ctrl-c to terminate the server.

```

<img width="580" alt="image" src="https://user-images.githubusercontent.com/31410839/158768273-f3a33293-c0fa-4d4d-9e47-2f3dd45e548d.png">

```
mahesh@Maheshs-MacBook-Air-M1 test_app % which flutter
/Users/mahesh/Documents/flutter/bin/flutter
mahesh@Maheshs-MacBook-Air-M1 test_app % flutter --version
Flutter 2.10.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 7e9793dee1 (2 weeks ago) • 2022-03-02 11:23:12 -0600
Engine • revision bd539267b4
Tools • Dart 2.16.1 • DevTools 2.9.2
```

### master

```console
mahesh@Maheshs-MacBook-Air-M1 test_app % /Users/mahesh/Documents/flutter_master/bin/dart devtools
Serving DevTools at http://127.0.0.1:9101.

          Hit ctrl-c to terminate the server.
```

<img width="595" alt="image" src="https://user-images.githubusercontent.com/31410839/158769033-95daed6a-9322-4b4f-9b90-d2b4071247f0.png">

```
mahesh@Maheshs-MacBook-Air-M1 test_app % which flutterm
flutterm: aliased to ~/Documents/flutter_master/bin/flutter
mahesh@Maheshs-MacBook-Air-M1 test_app % flutterm --version
Flutter 2.13.0-0.0.pre.103 • channel master • https://github.com/flutter/flutter.git
Framework • revision 509ddfda5c (28 hours ago) • 2022-03-15 21:10:18 -0700
Engine • revision dc22c4c7fe
Tools • Dart 2.17.0 (build 2.17.0-202.0.dev) • DevTools 2.11.4
```

**Comment by DanTup** [comment]
In the stable output above, the DevTools UI shows `2.9.2+1` but in the `flutter --version` output it's missing the `+1` - I believe that's the issue here.

Although the master one I can reproduce too - I think it may be caching issue since clearing application data in Chrome (or using a different port) shows 2.11.4 for me. @kenzieschmoll maybe https://github.com/flutter/devtools/issues/1674 - service worker related?

**Comment by kenzieschmoll** [comment]
Thanks Elliott. However, I think there are still two separate issues here:
1) The devtools version from `flutter --version` is _behind_ what we see in DevTools once launched (the original bug report and the example from stable above).
2) The devtools version from `flutter --version` is _ahead of_ what we see in DevTools once launched (the example from master above). This is the browser caching issue that @elliette is looking into.

But it seems we still have an undiagnosed cause for 1).

**Comment by christopherfujino** [comment]
> Thanks Elliott. However, I think there are still two separate issues here:
> 
> 1. The devtools version from `flutter --version` is _behind_ what we see in DevTools once launched (the original bug report and the example from stable above).
> 2. The devtools version from `flutter --version` is _ahead of_ what we see in DevTools once launched (the example from master above). This is the browser caching issue that @elliette is looking into.
> 
> But it seems we still have an undiagnosed cause for 1).

Thanks for clarifying, I'll take a look at #1

**Comment by maheshmnj** [comment]
> In the stable output above, the DevTools UI shows 2.9.2+1 but in the flutter --version output it's missing the +1 - I believe that's the issue here.

Removing the regression label since this is reproducible on 2.10 too

**Comment by elliette** [comment]
> Thanks Elliott. However, I think there are still two separate issues here:
> 
> 1. The devtools version from `flutter --version` is _behind_ what we see in DevTools once launched (the original bug report and the example from stable above).
> 2. The devtools version from `flutter --version` is _ahead of_ what we see in DevTools once launched (the example from master above). This is the browser caching issue that @elliette is looking into.
> 
> But it seems we still have an undiagnosed cause for 1).


Opened https://github.com/flutter/devtools/issues/3896 to track the work for #2

**Comment by christopherfujino** [comment]
Regarding investigating 1)

I can confirm on latest stable I'm seeing:

```
Flutter 2.10.3 • channel stable • git@github.com:flutter/flutter.git
Framework • revision 7e9793dee1 (2 weeks ago) • 2022-03-02 11:23:12 -0600
Engine • revision bd539267b4
Tools • Dart 2.16.1 • DevTools 2.9.2
```

But from `dart devtools` I see `2.9.2+1`.

In the cache file that we're reading, I see `2.9.2`. Let me check what the package on the website says...

**Comment by christopherfujino** [comment]
This is coming from the Dart SDK official release bundle:

https://storage.googleapis.com/dart-archive/channels/stable/release/2.16.1/sdk/dartsdk-macos-x64-release.zip

`$ cat dart-sdk/bin/resources/devtools/version.json
{"app_name":"devtools_app","version":"2.9.2","build_number":"1","package_name":"devtools_app"}`

I'm guessing this is an issue with whatever is generating this file?

**Comment by christopherfujino** [comment]
@kenzieschmoll it sounds like issue 2) is being tracked in https://github.com/flutter/devtools/issues/3896, and I believe that 1) is the result of `dart-sdk/bin/resources/devtools/version.json` being wrong (https://github.com/flutter/flutter/issues/100247#issuecomment-1072834538). I'm assigning this to you to follow up on how to fix that file.

Let me know if there's any action items in the Flutter tool for me.

**Comment by kenzieschmoll** [comment]
Haven't seen this in over a year, and the suspicion was that the wrong version was generated during this particular DevTools build, so closing as obsolete.
