### ISSUE TITLE
Flutter web app takes longer to load

### ISSUE THREAD

**Issue by pradeep14598** [flutter/flutter#100279]
flutter web app opening sucessfully in pc browser and not opeing in Mobile browser

**Comment by maheshmnj** [comment]
Hi @pradeep14598, Thanks for filing the issue. Does this happen when loading the app for the first time or every time?
 Also, Is this issue with [canvaskit or html renderer](https://docs.flutter.dev/development/tools/web-renderers)?
Please share the output of `flutter doctor -v` and a link to deployed sample app or a minimal reproducible sample for further investigation.

**Comment by pradeep14598** [comment]
> Hi @pradeep14598, Thanks for filing the issue. Does this happen when loading the app for the first time or every time? Also, Is this issue with [canvaskit or html renderer](https://docs.flutter.dev/development/tools/web-renderers)? Please share the output of `flutter doctor -v` and a link to deployed sample app or a minimal reproducible sample for further investigation.

Hello @maheshmnj ,this happen on Everytime while loading app ,i have used default render

[✓] Flutter (Channel stable, 2.10.3, on Ubuntu 21.04 5.11.0-49-generic, locale en_IN)
    • Flutter version 2.10.3 at /home/pradeep/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (2 weeks ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /home/pradeep/Android/Sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /snap/android-studio/119/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[✓] Android Studio (version 2021.1)
    • Android Studio at /snap/android-studio/119/android-studio
    • Flutter plugin version 65.2.2
    • Dart plugin version 211.7808
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code
    • VS Code at /snap/code/current
    • Flutter extension version 3.36.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 21.04 5.11.0-49-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 98.0.4758.102

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Comment by maheshmnj** [comment]
> this happen on Everytime while loading app ,i have used default render

Thanks for the update @pradeep14598, If you are using the default renderer that would be an HTML renderer on mobile phones which should be faster than canvaskit, Please share a minimal sample project or a deployed sample app for us to investigate this further.

Thanks
