### ISSUE TITLE
[Document] Usage of Dart-Define variables in gradle scripts

### ISSUE THREAD

**Issue by Sese-Schneider** [flutter/flutter#100292]
While creating **integration tests** for our Flutter application, we're facing a blocking issue:

Following the [official flutter documentation for integration testing](https://docs.flutter.dev/testing/integration-tests), in the section to automate the tests on Firebase Test Lab, its stated to [build the app with gradle](https://docs.flutter.dev/testing/integration-tests).

```bash
pushd android
# flutter build generates files in android/ for building the app
flutter build apk
./gradlew app:assembleAndroidTest
./gradlew app:assembleDebug -Ptarget=integration_test/<name>_test.dart
popd
```

Unfortuantely, its not stated on how to include `--dart-define` variables into the script so that the created APK is build with the variable defined.

According to a [stackoverflow thread](https://stackoverflow.com/a/67751484/5498155), I've tried setting the variable in `gradle.properties`, with no effect.

As nothing in this matter is documented, I assume its not possible and therefor file this issue.
If it is possible, how can we pass the `dart-define` to the gradle build? Adjusting the documentation here might be helpful :)

**Expected results:** 
Integration testable APK with a `dart-define` variable modified in its source code.

**Actual results:** 
The APK only has default behavior, the variable can't be modified.

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel stable, 2.10.3, on Microsoft Windows [Version 10.0.22000.556], locale de-DE)
    • Flutter version 2.10.3 at X:\Flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (2 weeks ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at X:\SDK
    • Platform android-31, build-tools 31.0.0
    • Java binary at: X:\JetBrains\apps\AndroidStudio\ch-0\211.7628.21.2111.8193401\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.
```

</details>

**Comment by Sese-Schneider** [comment]
@maheshmnj thank you for your triage! as per your investigation it looks like you think its already implemented, and just not documented.
Could you share the way to include the `dart-define` in gradle with us?

**Comment by maheshmnj** [comment]
> Could you share the way to include the dart-define in gradle with us?

@Sese-Schneider, I am not sure about it, nor I could find a way to use the dart define constants in Gradle scripts, Lets wait for the secondary triage to take a look at it, They may have a better understanding of it.

cc: @blasten

**Comment by onkarmonks** [comment]
@Sese-Schneider Did you find a way to do it?
I need to send data on basis of my Android grade flavor to main.dart to set appropriate .env file

**Comment by Sese-Schneider** [comment]
@onkarmonks we also had this issue in the past, but failed to find a way to do this.
What we do is to supply `--flavor`  and a `--dart-define` in the `flutter build` step.

However, this question is about injecting the `--dart-define` in Androids `gradlew assembleDebug` step.

**Comment by roblframpton** [comment]
I found a solution to this.  I inspected the verbose output of `flutter build` and found that the `--dart-define` flags get base64 encoded, comma-separated, and passed to a Gradle via a flag called `-Pdart-defines`. (**Note** the s at the end of this flag, since it contains _all_ the defines).

So for example, the following dart defines passed to Flutter:

```
--dart-define myvar=123 --dart-define anothervar=test
```

turn into the following flag passed to Gradle:

```
-Pdart-defines bXl2YXI9MTIz,YW5vdGhlcnZhcj10ZXN0
```

since, `myvar=123` is `bXl2YXI9MTIz` in base64 and `anothervar=test` is `YW5vdGhlcnZhcj10ZXN0` in base64.  Simply pass this flag to your Gradle command, e.g.:

```
gradlew -Pdart-defines bXl2YXI9MTIz,YW5vdGhlcnZhcj10ZXN0 assembleDebug 
```

This solved the problem for me.

**Comment by Sese-Schneider** [comment]
@roblframpton thank you very much, this solved our issues 🚀 
/cc @onkarmonks 

@maheshmnj given this is documented nowhere, I think the labels are correct as of missing documentation 👍🏼

**Comment by dustin-graham** [comment]
For anyone else struggling to make the solution provided by @roblframpton , remember to base64 encode just the key=value portion of the --dart-define. This is probably obvious to everyone else but me, but I was encoding "--dart-define=key=value". That definitely does not work! @roblframpton explained it perfectly, just encode the key=value.

**Comment by ivan-horchakov** [comment]
@roblframpton & @dustin-graham guys, inside my integration tests I have TEST_ENV var with the default value "develop". When I want to change it to "stage" for the local run via flutter driver - I'm using this:
`flutter drive --driver=test_driver/integration_test.dart --target=integration_test/tests/messaging_test.dart --dart-define=TEST_ENV=staging` and it is working.
But I need to figure out how to pass it during my Jenkins job, which builds and initiates test run in Firebase Test Lab. Here is my steps:
1. `flutter build apk --debug`
2. `./gradlew app:assembleAndroidTest`
3. `./gradlew app:assembleDebug -Ptarget="pwd"/../integration_test/smoke_test.dart`
I tried the approach, mentioned by you in points 2 & 3 (base64 & usual) but it still uses the default value "develop". TIA!

**Comment by krishnakumarcn** [comment]
Hey @ivan-horchakov , I have a similar use case and solved it today :) like this:
```
./gradlew assembleDebug --info -Ptarget=`pwd`/../integration_test/app_test.dart -Pdart-defines="{base64String}"
```
Where `{base64String}` is the encoded key=value pair, in your case `"base64("TEST_ENV=staging")"` 

or directly:

```
./gradlew assembleDebug --info -Ptarget=`pwd`/../integration_test/app_test.dart -Pdart-defines="VEVTVF9FTlY9c3RhZ2luZw=="
```

**Comment by ivan-horchakov** [comment]
Thanks, @[krishnakumarcn](https://github.com/krishnakumarcn) - you've made my day!

**Comment by bartekpacia** [comment]
I'm having a problem with passing dart defines to the `app:connectedDebugAndroidTest` task, which is needed to run integration tests natively on Android.

```
./gradlew app:connectedDevDebugAndroidTest \
  -Ptarget=$(pwd)/../integration_test/hsv_test.dart \
  -Pdart-defines="Q1RTX0RJU0FCTEVfTUFQX1BSRUxPQURJTkc9dHJ1ZQo=" 
```

but it's spitting out really ugly error message:

<details>
<summary>error message</summary>

```
> Task :app:compileFlutterBuildDevDebug
-DCTS_DISABLE_MAP_PRELOADING=true%0A: Error: Error when reading '-DCTS_DISABLE_MAP_PRELOADING=true%0A': No such file or directory


> Task :app:compileFlutterBuildDevDebug FAILED

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Script '/Users/bartek/fvm/versions/stable/packages/flutter_tools/gradle/flutter.gradle' line: 1159

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDevDebug'.
> Process 'command '/Users/bartek/fvm/versions/stable/bin/flutter'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
java.lang.StackOverflowError (no error message)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.5.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 7s
1 actionable task: 1 executed
```
<details>
