### ISSUE TITLE
Stop conflating verbosity with log level in flutter_tools

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#10021]
Right now, `VerboseLogger` both:

1. Logs trace statements
2. Adds decoration around the log msgs

All loggers should be capable of logging trace messages via a mutable `level` property.  Then, once #10020 lands, `VerboseLogger` could set the `level` property of its parent to get the same behavior we get today, but with the ability to pass trace messages through to `trace()` in the parent logger.  This in turn would allow us to make more accurate assertions in tests about what got logged to where.

**Comment by Hixie** [comment]
I don't understand. What's the difference between verbosity and log level?

**Comment by tvolkert** [comment]
I probably could have used better verbiage... what I mean is that `VerboseLogger` currently both:

* [decorates the log message by adding timing info or bolding status messages](https://github.com/flutter/flutter/blob/87d0010adb0b830c01ceecc457ed85e668cc1d25/packages/flutter_tools/lib/src/base/logger.dart#L228)
* [Logs trace messages](https://github.com/flutter/flutter/blob/87d0010adb0b830c01ceecc457ed85e668cc1d25/packages/flutter_tools/lib/src/base/logger.dart#L207) (as compared to `StdoutLogger`, which [doesn't](https://github.com/flutter/flutter/blob/87d0010adb0b830c01ceecc457ed85e668cc1d25/packages/flutter_tools/lib/src/base/logger.dart#L98))

These two concepts need not be tied together.  It causes weird downstream behavior, like you having to call `parent.printStatus()` for trace messages in #10020 (rather than `parent.printTrace()`), or elsewhere in the same PR, where you expect that `mockLogger.traceText` is empty, when in fact log trace statements were indeed recorded.

**Comment by Hixie** [comment]
meh, seems fine to me. :-)

**Comment by Hixie** [comment]
I don't think we need a bug to track this. If someone wants to clean up that part of the code they can do so.
