### ISSUE TITLE
Animations broken in Safari 15.4 on macOS 12.3

### ISSUE THREAD

**Issue by Rexios80** [flutter/flutter#100265]
## Steps to Reproduce

1. Create a flutter app with a circular progress indicator
2. Run with `flutter run -d web-server`
3. Open the given url in Safari

**Expected results:** 

Chrome:

https://user-images.githubusercontent.com/7896519/158718058-b03ee96e-1da1-4209-a848-2fc02b65bf96.mov

**Actual results:** 

Safari:

https://user-images.githubusercontent.com/7896519/158718078-47bc173f-1dcd-4ab9-add7-8fb609cc55f5.mov

<details>
<summary>Code sample</summary>

https://github.com/Rexios80/safari_bad_2_electric_boogaloo

</details>

<details>
  <summary>Logs</summary>

```
There aren't any logs when run as a web server
```

```
Analyzing safari_bad_2_electric_boogaloo...                             
No issues found! (ran in 0.9s)
```

```
[✓] Flutter (Channel stable, 2.10.3, on macOS 12.3 21E230 darwin-arm, locale en-US)
    • Flutter version 2.10.3 at /Users/rexios/dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (2 weeks ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/rexios/Library/Android/Sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • ANDROID_HOME = /Users/rexios/Library/Android/Sdk
    • Java binary at: /Library/Java/JavaVirtualMachines/zulu-8.jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (Zulu 8.54.0.21-CA-macos-aarch64) (build 1.8.0_292-b10)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio
    • Android Studio at /Applications/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] VS Code (version 1.65.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.36.0

[✓] Connected device (3 available)
    • SM R890 (mobile) • 192.168.1.114:5555 • android-arm    • Android 11 (API 30)
    • macOS (desktop)  • macos              • darwin-arm64   • macOS 12.3 21E230 darwin-arm
    • Chrome (web)     • chrome             • web-javascript • Google Chrome 99.0.4844.51
    ! Error: Aaron’s iPhone is not connected. Xcode will continue when Aaron’s iPhone is connected. (code -13)

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

</details>

**Comment by darshankawar** [comment]
@Rexios80 
Thanks for the report, but I am unable to replicate this on latest stable and master using the same command as you provided:


https://user-images.githubusercontent.com/67046386/158769753-0f1863da-7e2d-4487-8c84-f7932cb00e75.mov


My iOS safari version is `Version 15.3 (17612.4.9.1.8)`
and macOS version is `12.2.1 (21D62)`.

Although my config is not same as you, as you seem to be one version ahead of mine.

Is there a way for you to confirm on a lesser version ?

**Comment by Rexios80** [comment]
Unfortunately I don't have any other devices to test on. However I'm certain the macOS and/or safari update is what broke it because I have a few flutter websites that I check every day.

**Comment by Rexios80** [comment]
I can confirm it is not broken on iOS 15.4 safari though.

**Comment by jonasbark** [comment]
I can confirm that it works well using macOS Safari 15.3. After updating to Safari 15.4 it shows the artifact issues that are mentioned.

**Comment by jonasbark** [comment]
A workaround is adding this part to your HTML file:

```
<script type="text/javascript">
    if (platform.name.toLowerCase() == "safari" && parseInt(platform.version.split(".")[0]) >= 15) {
      HTMLCanvasElement.prototype.getContext = function (orig) {
        return function(type) {
          return type !== "webgl2" ? orig.apply(this, arguments) : null
        }
      }(HTMLCanvasElement.prototype.getContext)
    }
  </script>
``` 
It seems to be the same issue as https://github.com/flutter/flutter/issues/89655

**Comment by Rexios80** [comment]
I'm not sure that's the same issue because the behavior on https://gallery.flutter.dev/#/ is very different than described in that issue. Also iOS Safari works fine.

**Comment by Rexios80** [comment]
Actually https://gallery.flutter.dev/#/demo/progress-indicator is behaving fine... Except I have several published flutter web apps that exhibit the issue with progress indicators.

**Comment by jonasbark** [comment]
I assume that iOS Safari works fine because the 'fix' for the issue I mentioned (https://github.com/flutter/engine/pull/29038) did exactly that: force iOS Safari users to use the older webgl version.
The same fix could then be applied to macOS Safari.

As to the Flutter Gallery: may be related to canvaskit vs html renderer

**Comment by eyebrowsoffire** [comment]
I'm able to reproduce this on Safari 15.4.

**Comment by yjbanov** [comment]
Dropping to P3 for now. Some investigation indicates that this is a rare bug, and it only affects WebGL 2, not WebGL 1. What we will do for now is provide an API for developers to choose the version of WebGL in `window.flutterConfiguration` for their app, as a workaround.

**Comment by Rexios80** [comment]
I'm not sure how this is a rare bug if it affects every flutter web app I've ever made and new projects with default configuration. I know Safari isn't that popular of a browser, but it has a significant enough user base that ignoring the issue seems like a bad idea. Requiring developer involvement to implement a workaround is a good way to end up with a bunch of flutter web apps that developers think work fine, but then Safari users complain that it's broken wasting development time investigating the issue when the workaround could have just been included as default configuration.

As @jonasbark said, there is already an implemented workaround for iOS Safari. Would it make sense to just include that workaround for macOS Safari as well?

**Comment by yjbanov** [comment]
@Rexios80 the reason why this looks like a rare bug is because none of the other apps we tried this on reproduced the issue, and it doesn't reproduce on all hardware. For example, I have an Intel MacBook Pro with macOS 12.3 and Safari 15.4, and the bug does not reproduce in any form. @eyebrowsoffire can reproduce it on his M1 laptop, but when he tries isolating the picture produced by your sample app, the issue disappears. It has to be a very specific combination of hardware + OS + Safari + code. It could be an issue specific WebGL 2 or Metal or GPU (e.g. M1 vs Intel).

The `window.flutterConfiguration` solution I propose above is similar to our iOS workaround, except it would allow the developer to decide instead of us making that decision for all developers. Currently it looks like most apps are not affected so it doesn't look reasonable to roll back all apps down to WebGL 1. The iOS Safari situation was different in that the issue happened on much of the iOS hardware, applied to any Flutter app, and was very severe (apps won't launch at all).

**Comment by eyebrowsoffire** [comment]
We've isolated the issue somewhat and filed a bug against the Skia folks to look further into the issue: https://bugs.chromium.org/p/skia/issues/detail?id=13123

**Comment by Rexios80** [comment]
This might have been fixed by the latest safari version. Should this issue be closed?
