### ISSUE TITLE
[Impeller] Improve Path API usability

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#100262]
see for example https://github.com/flutter/impeller/pull/86

Right now it's too easy to misuse the path API - we should be able to make it a bit easier to tell which path builder method(s) to use or not use in a given context, ideally by removing them and making PathBuilder do whatever bookkeeping is necessary and making Path immutable.

**Comment by chinmaygarde** [comment]
Duplicate of https://github.com/flutter/flutter/issues/133880 which was fixed by @jonahwilliams in https://github.com/flutter/engine/pull/45393.
