### ISSUE TITLE
Error when run with android emulators

### ISSUE THREAD

**Issue by oeng-hok-leng** [flutter/flutter#100218]
I got this error when i try to run my app with android emulator.

What can I do?

* What went wrong:
A problem occurred evaluating project ':app'.
> Could not get unknown property 'ndkVersion' for extension 'flutter' of type FlutterExtension.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by darshankawar** [comment]
@oeng-hok-leng 
It seems to be complaining about ndkversion which doesn't exist in your build.gradle.
What's the gradle version are you using. Can you also provide `flutter doctor -v` ?

**Comment by oeng-hok-leng** [comment]
@darshankawar 
this is my `futter doctor -v ` log 
Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/oenghokleng/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

**Comment by oeng-hok-leng** [comment]
and this is after run all command that show from `flutter doctor -v ` log 
[✓] Flutter (Channel stable, 2.10.3, on macOS 12.2.1 21D62 darwin-x64, locale en)
    • Flutter version 2.10.3 at /Users/oenghokleng/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (2 weeks ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/oenghokleng/Library/Android/sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code (version 1.65.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.36.0

[✓] Connected device (2 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 99.0.4844.74

but i still face this problem

**Comment by darshankawar** [comment]
@oeng-hok-leng 
Can you provide your app level and build level `build.gradle` file ? Do you see any `ndkversion` property used in it ?

**Comment by oeng-hok-leng** [comment]
> @oeng-hok-leng Can you provide your app level and build level `build.gradle` file ? Do you see any `ndkversion` property used in it ?

this is my build.grade:
buildscript {
    ext.kotlin_version = '1.6.10'
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:4.1.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.3.10'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

**Comment by darshankawar** [comment]
@oeng-hok-leng 
Can you try to run on a physical device and see if you still get same error or not ?

**Comment by oeng-hok-leng** [comment]
> @oeng-hok-leng Can you try to run on a physical device and see if you still get same error or not ?

Yes, let me try it.

**Comment by oeng-hok-leng** [comment]
@darshankawar  sorry for lately responding, I already test it on the real android device, I got the same issue. and I also try for  run `flutter build apk `, I still got the same issue too.

**Comment by darshankawar** [comment]
I suggest you to ask this in support channels like StackOverflow, because it seems to be a config issue at your end. If you disagree and think this is a bug in framework, write in comments and I'll reopen it.

**Comment by darshankawar** [comment]
Try also [this](https://github.com/flutter/flutter/issues/101011#issuecomment-1082727134) solution and see if it works for you.
