### ISSUE TITLE
Golden file test failure closing tree

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#100276]
On the Engine roll here https://github.com/flutter/flutter/pull/100244, I accepted the diffs, the presubmit check went green, but it looks like something went wrong and the diffs are still getting flagged in post submit, closing the tree:

https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20web_tests_7_last/3935/overview

I need an adult. @Piinks @mdebbar

**Comment by zanderso** [comment]
I should also note that I followed the instructions in the failure logs, clicked through the link to SkiaPerf there, accepted the diff again, and tried a re-run, and that re-run also failed on the diff.

**Comment by mdebbar** [comment]
We have had a similar issue yesterday on the flutter/engine repo. Images are triaged in the PR, then post-submit runs, but images don't make it to Gold. So Gold keeps thinking they are untriaged.

I spoke with @kjlubick who recommended the following fix: https://github.com/flutter/engine/pull/32071

But it looks like that didn't work either. Here are the post-submit [logs](https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8819505170257114497/+/u/felt_test:_chrome-unit-linux/stdout) for the above PR. The `goldctl` exception is gone, but the images still didn't make it to Gold.

**Comment by mdebbar** [comment]
Thanks @kjlubick!

From our discussion offline, @kjlubick identified [the issue](https://bugs.chromium.org/p/skia/issues/detail?id=13072) on Gold's side, and expects it'll take a few days to fix.

In the meantime, I think we have 2 options:

### 1. Disable Gold checks:
Stop checking golden changes. This means we will be accepting all changes without triage, and we'll be flying blind.

### 2. Block golden changes:
Prevent any golden changes from going in. This means we'll probably delay a lot of work and we may need to disable the rollers.

@Piinks what do you think?

**Comment by Piinks** [comment]
Filed https://github.com/flutter/flutter/issues/100304 if previous comment sounds good with everyone else, I am preparing a PR to disable the post submit failure now.

**Comment by kjlubick** [comment]
That's a good plan Kate. Thanks for owning the monitoring.

**Comment by Piinks** [comment]
> We also need to manually re-triage all golden changes once they land in master, right?

I don't think so.

@kjlubick can correct me if I am wrong, but it looks like the images are triaged, the test is just coming back as a failure. The dashboard currently shows there are no images in need of approval https://flutter-gold.skia.org/ 
If the fix on Gold's end means we need to update a few images then I think we can manage that. 

We currently manage all of our image approval in pre-submit, so I am pretty confident disabling post-submit failures will be fine. We only recently enabled it in https://github.com/flutter/flutter/pull/93516 to better identify when something has gone wrong. So it kinda worked as expected! :)

**Comment by Piinks** [comment]
Tree is green.

**Comment by yjbanov** [comment]
This is happening again:

- https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8819409321084715617/+/u/run_test.dart_for_web_tests_shard_and_subshard_7_last/test_stdout
- https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8819412057180872097/+/u/run_test.dart_for_web_tests_shard_and_subshard_7_last/test_stdout
-

**Comment by Piinks** [comment]
https://github.com/flutter/flutter/pull/100332 should disable this for good until we can find out where Gold is broken. It looks like the tree went green, and then more image changes were made that again were not ingested properly.
