### ISSUE TITLE
Document the basics of creating new Widgets

### ISSUE THREAD

**Issue by tain335** [flutter/flutter#1002]
Every Widget should to extend StatelessComponent or StatefulComponent?
What relation between LeafRenderObjectWidget and StatelessComponent?

**Comment by abarth** [comment]
> Every Widget should to extend StatelessComponent or StatefulComponent?

Those are the two most common classes for end-developers to extend.  The other subclasses of Widget are for some more specialized situations that most end-developers won't encounter.

> What relation between LeafRenderObjectWidget and StatelessComponent?

StatelessComponent is a widget that's built out of other widgets (e.g., via the build function).  At some point, the process of building widgets out of other widgets needs to bottom out in a widget that's not built out of other widgets.  A LeafRenderObjectWidget isn't built out of other widgets.  Instead, it's a widget that represents one of the underlying RenderObjects.  If you create a new kind of RenderObject (uncommon for end-developers), then you'll need to create a LeafRenderObjectWidget to use it from the widget tree.

**Comment by Hixie** [comment]
StatefulWidget and co have detailed docs now.
