### ISSUE TITLE
[Proposal]FocusScopes should be escapable via tab-traversal

### ISSUE THREAD

**Issue by craiglabenz** [flutter/flutter#100256]
## Use case

The FocusScope widget cannot be escaped purely via tab-traversal, which is relevant if the rendered UI contains nested FocusScope widgets. (This can happen if there are nested Navigator widgets, as each Navigator includes a FocusScope in its build method.) Clicking somewhere in the UI outside of the FocusScope resets the focus location and does allow a user to escape a FocusScope that does not account for the entire UI. 

## Proposal

Before cycling within a FocusScope, the Focus system could check to see if that FocusScope sits within an outer FocusScope, and if so, surrender Focus back to the wrapping FocusScope. However, this change would make the difference between a FocusScope and a FocusTraversalGroup somewhat unclear (at least, to me).

Alternatively, Navigators could cease to include a FocusScope within their `build` methods, but the implications of this change are much harder for me to anticipate.

## Reproduction

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'FocusScope Demo',
      home: FocusScope(
        child: Column(
          children: const <Widget>[
            FocusableWidget(),
            FocusScope(
              child: FocusableWidget(),
            ),
          ],
        ),
      ),
    );
  }
}

class FocusableWidget extends StatefulWidget {
  const FocusableWidget({Key? key}) : super(key: key);

  @override
  State<FocusableWidget> createState() => _FocusableWidgetState();
}

class _FocusableWidgetState extends State<FocusableWidget> {
  bool _isFocused = false;
  @override
  Widget build(BuildContext context) {
    return Focus(
      onFocusChange: (isFocused) => setState(() => _isFocused = isFocused),
      child: Container(
        color: _isFocused ? Colors.red : Colors.grey,
        height: 100,
        width: 100,
      ),
    );
  }
}
```

This is potentially related to #86972.

**Comment by maheshmnj** [comment]
Leaving this issue open for further thoughts from the team.

**Comment by craiglabenz** [comment]
I just chatted with @gspencergoog and we identified a few options to unblock this issue with nested navigators.

1. Before tab traversal cycles within a FocusScope, it could check to see if it is nested within another FocusScope, and, if so, release focus to that parent FocusScope.
2. Navigators could, by default, not add a FocusScope unless they are the root Navigator.
3. Navigators could expose a new parameter, `shouldAddFocusScope`, which would default to True. This would obviously allow nested navigator scenarios to instruct their `Navigator` widgets to omit the their FocusScopes.

cc @goderbauer

**Comment by johnpryan** [comment]
I think I prefer option 3,  since it's not a breaking change AFAICT. But I'm not sure what the default should be. If you are calling the Navigator constructor, you're either using the Router API and building the root Navigator (so shouldAddFocusScope should be true) or you're building an inner navigator (so shouldAddFocusScope should be false.)

**Comment by chunhtai** [comment]
I vote for 2, but remove the responsibility of Navigator adding the FocusScope. It will be WidgetsApp who creates the focusScope around the navigator entirely.

**Comment by craiglabenz** [comment]
You're certainly most qualified to predict how hard it would be to land such a change, @chunhtai. fwiw, option 2 would also be my favorite if I magically knew it wouldn't cause a logjam of errors in Google apps. And in a scenario where we did decide that option 2 was too uncertain, then I'd be with @johnpryan and prefer option 3, but probably with a non-breaking default value of `true`.

**Comment by chunhtai** [comment]
3 is likely the least breaking way, but the api does not make sense to me, and therefor, will likely confused developer to use that incorrectly.

I think the best way to approach this is to go for 2 and see what breaks.

**Comment by gspencergoog** [comment]
Option number 2 was implemented in https://github.com/flutter/flutter/pull/109702

**Comment by chunhtai** [comment]
closed as fixed
