### ISSUE TITLE
[Android] App doesn't render properly, the button does not display text

### ISSUE THREAD

**Issue by wu-liu-7** [flutter/flutter#100286]
<img src="https://user-images.githubusercontent.com/74497359/158775853-e332aa6b-c833-4026-8779-ef3087dd7fd8.png" width ="300"> 

<img src="https://user-images.githubusercontent.com/74497359/158775869-abb0c39d-20e3-4140-acbf-0e3cc0426e60.jpg" width ="300"> 

跳转到此页面就出现了这个问题，目前发现这个型号的手机出现的频率比较高。

*Translated via Google translate*
Jump to this page and this problem occurs. At present, it is found that the frequency of this model of mobile phone is relatively high.

**Comment by wu-liu-7** [comment]
![image](https://user-images.githubusercontent.com/74497359/158776682-61c2dca7-b3d1-4792-95b0-aac32b53f550.png)

**Comment by maheshmnj** [comment]
Hi @wu-liu-7, Thanks for filing the issue. In order to investigate this issue further we would need a minimal and complete sample code along with the output of `fluttter doctor -v`. Does the issue occur in debug/release/profile or all modes?

**Comment by wu-liu-7** [comment]
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

class PreSalePayPage extends StatelessWidget {

  final double paddingHorizontal = 15.0;
  final double bottomActionBarHeight = 50.0;
  final TextStyle itemKeyTextStyle = TextStyle(fontSize: 14, color: Colors.black45);
  final TextStyle itemValueTextStyle = TextStyle(fontSize: 14, color: Colors.black45);
  final TextStyle itemHintTextStyle = TextStyle(fontSize: 14, color: Colors.black45);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("去结算"),
      ),
      body: _pageBody(context),
      backgroundColor: Colors.white,
    );
  }

  Widget _divider() {
    return Divider(height: 0.5, color: Colors.black38);
  }

  Widget _divider10() {
    return Divider(height: 10, thickness: 10, color: Colors.black12);
  }

  Widget _pageBody(BuildContext context) {
    return Stack(
      children: [
        SingleChildScrollView(
          padding: EdgeInsets.only(bottom: bottomActionBarHeight),
          child: Column(
            children: [
              _userAndAddressModule(), //用户和地址
              _divider10(),
              _goodsModule(), //商品
              _divider10(),
              _useScore(), // 积分支付
              _expressType(context), // 配送方式
              _coupon(context), // 优惠券
              Padding(
                padding: EdgeInsets.only(left: paddingHorizontal, right: paddingHorizontal, top: 10),
                child: _divider(),
              ),
              _remarks(), // 备注
              _divider10(),
              _amount(), // 金额
              _preferential(), // 其他优惠
              _couponDiscount(), // 优惠券折扣
              _integralDiscount(), // 积分优惠
              _freight(), // 配送运费
              _divider10(),
            ],
          ),
        ),
        Align(alignment: Alignment.bottomCenter, child: _bottomActionBar(context)),
      ],
    );
  }

  /// 用户和地址
  Widget _userAndAddressModule() {
    return InkWell(
      onTap: () {},
      child: Container(
        // height: 74,
        padding: EdgeInsets.symmetric(horizontal: paddingHorizontal, vertical: 12),
        child: Row(
          children: [
            Container(
              width: 32,
              height: 32,
              decoration: BoxDecoration(color: Colors.red, borderRadius: BorderRadius.all(Radius.circular(16))),
              child: Icon(Icons.location_on, color: Colors.white),
            ),
            Expanded(
                child: Padding(
              padding: const EdgeInsets.symmetric(horizontal: 12),
              child: Column(
                      mainAxisSize: MainAxisSize.min,
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Row(
                          mainAxisSize: MainAxisSize.min,
                          children: [
                            Flexible(
                              child: Text(
                                  "张三   12345678909",
                                  maxLines: 1,
                                  overflow: TextOverflow.ellipsis,
                                  style: TextStyle(
                                      fontSize: 16, color: Color(0xcc000000), fontWeight: FontWeight.w500)),
                            ),
                            Visibility(
                              visible: true,
                              child: Container(
                                width: 32,
                                alignment: Alignment.center,
                                margin: EdgeInsets.only(left: 5),
                                decoration: BoxDecoration(
                                    color: Colors.red, borderRadius: BorderRadius.all(Radius.circular(2))),
                                child: Text(
                                  '默认',
                                  style: TextStyle(fontSize: 9, color: Colors.white),
                                ),
                              ),
                            ),
                          ],
                        ),
                        Text(
                          "任务分工一个非常关停",
                          style: TextStyle(fontSize: 14, color: Colors.black),
                        ),
                      ],
                    )
            )),
            Text('修改', style: TextStyle(fontSize: 14, color: Colors.red)),
          ],
        ),
      ),
    );
  }

  /// 店铺名
  Widget _shopName() {
    return SizedBox(
        height: 40,
        child: Row(
          children: [
            Icon(Icons.forward),
            Text(
              "乌黑的",
              maxLines: 1,
              overflow: TextOverflow.ellipsis,
              style: TextStyle(fontSize: 14, color: Colors.black),
            )
          ],
        ));
  }

  Widget _goods() {
    return InkWell(
      onTap: () {},
      child: SizedBox(
        height: 96,
        child: Row(
          children: [
            Expanded(
                child: ListView.separated(
              shrinkWrap: true,
              scrollDirection: Axis.horizontal,
              padding: EdgeInsets.symmetric(vertical: 16),
              itemCount: 3,
              itemBuilder: (context, index) {
                return ClipRRect(
                  borderRadius: BorderRadius.all(Radius.circular(2)),
                  child: Image.network(
                    "https://avatars.githubusercontent.com/u/74497359?s=88&v=4",
                    width: 64,
                    height: 64,
                    fit: BoxFit.fill,
                  ),
                );
              },
              separatorBuilder: (context, index) {
                return SizedBox(width: 8);
              },
            )),
            SizedBox(width: 8),
            Text('共 3 件', style: TextStyle(fontSize: 12, color: Colors.black)),
            Icon(Icons.keyboard_arrow_right, size: 12, color: Colors.black),
          ],
        ),
      ),
    );
  }

  /// 店铺名 & 商品
  Widget _shopAndGoods() {
    return Padding(
      padding: EdgeInsets.symmetric(horizontal: paddingHorizontal),
      child: Column(
        children: [
          _shopName(),
          _divider(),
          _goods(),
        ],
      ),
    );
  }

  Widget _goodsModule() {
    return Column(
      children: [
        _shopAndGoods()
      ],
    );
  }

  /// 积分支付
  Widget _useScore() {
    return Visibility(
      visible: true,
      child: Padding(
        padding: EdgeInsets.symmetric(horizontal: paddingHorizontal),
        child: Row(
          children: [
            Expanded(child: Text('是否使用积分支付', style: itemKeyTextStyle)),
            Switch(
                  value: true,
                  activeColor: Colors.blue,
                  onChanged: (_bool) {}),
          ],
        ),
      ),
    );
  }

  Widget _itemKV(String title, {String? value, double paddingTop = 0, double paddingBottom = 0}) {
    TextStyle valueTextStyle = itemValueTextStyle;
      valueTextStyle = TextStyle(fontSize: 14, color: Colors.black);
    return Padding(
      padding:
          EdgeInsets.only(left: paddingHorizontal, right: paddingHorizontal, top: paddingTop, bottom: paddingBottom),
      child: Row(
        children: [
          Expanded(child: Text(title, style: itemKeyTextStyle)),
          SizedBox(width: 15),
          Expanded(child: Text(value ?? '', style: valueTextStyle, textAlign: TextAlign.right)),
        ],
      ),
    );
  }

  Widget _itemKvArrow(
    String title, {
    String hint = '',
    String value = '',
    required GestureTapCallback onTap,
    double paddingTop = 10,
  }) {
    String v = hint;
    TextStyle vts = itemHintTextStyle;
    if (value != null) {
      v = value;
      vts = itemValueTextStyle;
    }

    return InkWell(
      onTap: onTap,
      child: Padding(
        padding: EdgeInsets.only(left: paddingHorizontal, right: paddingHorizontal, top: paddingTop),
        child: Row(
          crossAxisAlignment: CrossAxisAlignment.end,
          children: [
            Expanded(child: Text(title, style: itemKeyTextStyle)),
            SizedBox(width: 15),
            Expanded(child: Text(v, style: vts, textAlign: TextAlign.right)),
            Icon(Icons.keyboard_arrow_right, size: 20, color: Colors.black45),
          ],
        ),
      ),
    );
  }

  /// 配送方式
  Widget _expressType(BuildContext context) {
    return Container(
      child: Padding(
        padding: EdgeInsets.only(left: paddingHorizontal, right: paddingHorizontal, top: 10),
        child: Row(
          mainAxisAlignment: MainAxisAlignment.spaceBetween,
          crossAxisAlignment: CrossAxisAlignment.center,
          children: <Widget>[
            Text('配送类型',style: itemKeyTextStyle,),
            Text('预售-预约发货',style: itemHintTextStyle),
          ],
        ),
      ),

    );
  }

  /// 优惠券
  Widget _coupon(BuildContext context) {
   return Text("优惠");
  }

  /// 备注
  Widget _remarks() {
    return Padding(
      padding: EdgeInsets.only(left: paddingHorizontal, right: paddingHorizontal, top: 20, bottom: 16),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text('备注信息', style: itemKeyTextStyle),
          Container(
            margin: EdgeInsets.only(top: 15),
            padding: EdgeInsets.symmetric(horizontal: 8),
            decoration: BoxDecoration(color: Colors.black12, borderRadius: BorderRadius.all(Radius.circular(4))),
            child: TextField(
              decoration: InputDecoration(
                hintText: '请输入备注信息',
                hintStyle: itemHintTextStyle,
                border: InputBorder.none,
              ),
              style: itemValueTextStyle,
              minLines: 4,
              maxLines: 4,
            ),
          ),
        ],
      ),
    );
  }

  /// 金额
  Widget _amount() {
    return _itemKV('商品金额', value: '1000', paddingTop: 20);
  }

  /// 其他优惠
  Widget _preferential() {
    return _itemKV('其他优惠', value: '12', paddingTop: 20);
  }

  /// 优惠券抵扣
  Widget _couponDiscount() {
    return _itemKV('优惠券抵扣', value: '12', paddingTop: 20);
  }

  /// 积分优惠
  Widget _integralDiscount() {
      return Visibility(child: _itemKV('积分优惠', value: '111', paddingTop: 20));
  }

  /// 配送运费
  Widget _freight() {
    return _itemKV('配送运费', value: '12', paddingTop: 20, paddingBottom: 20);
  }

  Widget _bottomActionBar(BuildContext context) {

    return SizedBox(
      width: double.infinity,
      height: bottomActionBarHeight,
      child: Card(
        margin: EdgeInsets.zero,
        child: Padding(
          padding: EdgeInsets.symmetric(horizontal: paddingHorizontal),
          child: Row(
            children: [
              Padding(
                padding: const EdgeInsets.only(right: 10),
                child: Text('¥111111',
                    style: TextStyle(fontSize: 16, color: Colors.red, fontWeight: FontWeight.w500)),
              ),
              Expanded(
                  child: Text('优惠 ¥123', style: TextStyle(fontSize: 12, color: Colors.black))),
              Padding(
                padding: const EdgeInsets.symmetric(horizontal: 8),
                child: _button('支付订金', Color(0xffFAAB0F), () {
                }),
              ),
              _button('全款结算', Color(0xffEA5504), () {

              }),
            ],
          ),
        ),
      ),
    );
  }

  Widget _button(String text, Color color, GestureTapCallback callback) {
    return InkWell(
      onTap: callback,
      child: Container(
        width: 84,
        height: 32,
        alignment: Alignment.center,
        decoration: BoxDecoration(color: color, borderRadius: BorderRadius.all(Radius.circular(16))),
        child: Text(text, style: TextStyle(fontSize: 13, color: Colors.white)),
      ),
    );
  }
}
以上是代码


flutter doctor -v

[√] Flutter (Channel stable, 2.2.0, on Microsoft Windows [Version 10.0.19043.1526], locale zh-CN)
    • Flutter version 2.2.0 at E:\flutter_2.2.0\flutter
    • Framework revision b22742018b (10 months ago), 2021-05-14 19:12:57 -0700
    • Engine revision a9d88a4d18
    • Dart version 2.13.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at D:\AndroidStudio\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: D:\jdk\bin\java
    • Java version Java(TM) SE Runtime Environment (build 13.0.1+9)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Android Studio (version 4.1.0)
    • Android Studio at D:\AndroidStudio\tool
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    X Unable to determine bundled Java version.
    • Try updating or re-installing Android Studio.

[√] IntelliJ IDEA Ultimate Edition (version 2018.3)
    • IntelliJ at D:\idea\IntelliJ IDEA 2018.3
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] Connected device (3 available)
    • DLT A0 (mobile) • emulator-5554 • android-x86    • Android 7.1.2 (API 25)
    • Chrome (web)    • chrome        • web-javascript • Google Chrome 99.0.4844.74
    • Edge (web)      • edge          • web-javascript • Microsoft Edge 99.0.1150.39
    ! Device 127.0.0.1:5555 is offline.

! Doctor found issues in 1 category.

**Comment by maheshmnj** [comment]
Thanks for the info @wu-liu-7, I ran your code sample on the latest `stable 2.10.3` and I see the UI renders properly, Also, You seem to be on the older version of flutter. I would advise you to try upgrading to latest stable version of flutter by running  `flutter upgrade`. 

<img src="https://user-images.githubusercontent.com/31410839/158945119-6d3cfb72-edd8-4e99-be1b-baef34933220.png" width ="300"> 

<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel stable, 2.10.3, on macOS 12.1 21C52 darwin-arm, locale en-GB)
    • Flutter version 2.10.3 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (20 hours ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.36.0

[✓] Connected device (3 available)
    • Redmi K20 Pro (mobile) • 192.168.1.5:5555 • android-arm64  • Android 11 (API 30)
    • macOS (desktop)        • macos            • darwin-arm64   • macOS 12.1 21C52 darwin-arm
    • Chrome (web)           • chrome           • web-javascript • Google Chrome 99.0.4844.51

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by maheshmnj** [comment]
@wu-liu-7  is this solved?

**Comment by wu-liu-7** [comment]
没有，在特定的机型上面偶尔还会出现

**Comment by maheshmnj** [comment]
If you encounter this issue again on the latest stable channel and have a more info for us feel free to comment on this issue or file a new issue.

_使用谷歌翻译进行翻译_

如果您在最新的稳定频道上再次遇到此问题并有更多信息给我们，请随时评论此问题或提交新问题。
