### ISSUE TITLE
I can't access my PDF file from my local assets in my flutterweb app hosted on firebase

### ISSUE THREAD

**Issue by jake1808** [flutter/flutter#100285]
Hello, I am making a flutter web app that's hosted on firebase. I have a PDF file that's located in my `assets/documents/CV.pdf`. I want my users to be able to download and view the file. When I run the web app on my local machine they are able to do it however when I deploy my web app they are faced with this page:

![image](https://user-images.githubusercontent.com/51802968/158764159-a68d20fd-23e3-4561-bb6d-2df587093066.png)

Here is the line where I call for the file to be downloaded and viewed: `html.window.open('assets/documents/CV.pdf', 'CV');`

Here is the error I get in my browsers console: `Failed to load resource: the server responded with a status of 404 ()`

and here is the link to my web app: https://portfolio-34678.web.app/#/Home

**Comment by darshankawar** [comment]
@jake1808 
`Failed to load resource: the server responded with a status of 404 ()` usually indicates an error between server and browser and Flutter didn't yet get a chance to do anything. The server doesn't seem to recognize it and then correctly sent 404.
You'll probably need to configure the server to respond upon the request you are sending with Flutter's `index.html`. 
You can ask about it on support channels like Stackoverflow.
Closing from here.
