### ISSUE TITLE
Building flutter snapshot is internet speed dependent

### ISSUE THREAD

**Issue by xster** [flutter/flutter#10024]
Delete flutter tool snapshot, connect to GIN-2g or some such, run flutter. Takes a long time to `Building flutter tool...`

**Comment by goderbauer** [comment]
We do download the dependencies of flutter tool with `pub upgrade` before actually creating the snapshot. Both actions happen under the header `Building flutter tool...`. So, I guess it's kinda expected that this action is internet speed dependent...

**Comment by mit-mit** [comment]
I think the more complete fix for this is to create pre-compiled, pre-bundled SDKs on the bots.

**Comment by xster** [comment]
Duping into #6491
