### ISSUE TITLE
[video_player] Proposal to update the Video Player Caption post initialization

### ISSUE THREAD

**Issue by ibrahimcetin** [flutter/flutter#100302]
## Use case

Hi, I am using video_player plugin in my Flutter app and I guess there is no function to add/change ClosedCaptionFile after VideoPlayerController initialization but I need a method or a way to change it dynamically. I have tried a way, I have changed video_player source code on my local machine and added a method called setClosedCaptionFile to the VideoPlayerController and it is working. But I think it's not a good way to me because I want to share my app on GitHub.

## Proposal

So, I am wondering is there any way or method to change captions after controller is initialized?, or Can we add a method to the VideoPlayerController to set/change the ClosedCaptionFile?

I have added this code to VideoPlayerController
```
void setClosedCaptionFile(ClosedCaptionFile? closedCaptionFile) {
  _closedCaptionFile = closedCaptionFile;
  value = value.copyWith(caption: _getCaptionAt(value.position));
}
```

I will be glad, if you inform me.

**Comment by maheshmnj** [comment]
Hi @ibrahimcetin, Thanks for filing the issue. The video player currently doesn't allow updating the captions file during run time. The only way to change the caption is to reinitialize the VideoplayerController. However, I am labeling this issue as a new feature request.

**Comment by ibrahimcetin** [comment]
Thank you for your response. I think I can create a PR to add this feature. But I have a question. Can I remove `closedCaptionFile` parameter?  Because, I think we should have only `_closedCaptionFile` property and to set that `setClosedCaptionFile` method and `ClosedCaptionFile? get closedCaptionFile => _closedCaptionFile` to get. With these we can set captions before or after controller initialization. And they can be nullable to be able to remove the captions.
