### ISSUE TITLE
implement branching support for packaging builders

### ISSUE THREAD

**Issue by XilaiZhang** [flutter/flutter#100336]
New changes have been made to release branch recipe, related PR is https://flutter-review.googlesource.com/c/infra/+/28083 . According to reasoning from @godofredoc, currently recipes from main branch are used rather than from the release branch. would like to request branching support for packaging builders in main branch as well.

**Comment by godofredoc** [comment]
Fixed with https://github.com/flutter/flutter/issues/114943
