### ISSUE TITLE
[file_selector] Add the ability to open a specified directory in the file explorer

### ISSUE THREAD

**Issue by ilgnefz** [flutter/flutter#100361]
like Chrome,  it can directly open the explorer and navigate to the directory where you downloaded the file

**Comment by maheshmnj** [comment]
Hi @ilgnefz, Thanks for filing the issue. If you want to choose a specific path to save a file. Then you can use the first-party plugin [file_selector](https://pub.dev/packages/file_selector) which launches the built int file explorer on the platform.

To be more specific you can use the `getSavedPath()` method.
```dart
final path = await getSavedPath()
```

Closing as this is currently possible with the above-mentioned plugin.

**Comment by ilgnefz** [comment]
Thanks for your advice.  What I want is to be able to open Explorer directly via The Flutter Desktop, not to call a dialog.   For example, if my application stores some files in a folder on the computer, I want my application to be able to launch Explorer and locate that folder. 
like this: 
![无标题](https://user-images.githubusercontent.com/58471330/158991839-8404dd3c-542d-4708-a122-9266061b491f.png)

**Comment by ilgnefz** [comment]
> Hi @ilgnefz, Thanks for filing the issue. If you want to choose a specific path to save a file. Then you can use the first-party plugin [file_selector](https://pub.dev/packages/file_selector) which launches the built int file explorer on the platform.
> 
> To be more specific you can use the `getSavedPath()` method.
> 
> ```dart
> final path = await getSavedPath()
> ```
> 
> Closing as this is currently possible with the above-mentioned plugin.

Thanks for your advice.  What I want is to be able to open Explorer directly via The Flutter Desktop, not to call a dialog.   For example, if my application stores some files in a folder on the computer, I want my application to be able to launch Explorer and locate that folder. 
like this: 
![无标题](https://user-images.githubusercontent.com/58471330/158991839-8404dd3c-542d-4708-a122-9266061b491f.png)

**Comment by maheshmnj** [comment]
Thanks for the clarification @ilgnefz, I looked around for solutions across third-party plugins. But I couldn't find a  plugin that does this. This feature cannot be directly implemented in flutter, But this makes up a valid use case for a first-party plugin [file_selector](https://pub.dev/packages/file_selector). I am labeling this issue as a valid feature request.

**Comment by maheshmnj** [comment]
This issue tracks a proposal to open the Native file directory with the specified path.

**Comment by stuartmorgan** [comment]
> But this makes up a valid use case for a first-party plugin [file_selector](https://pub.dev/packages/file_selector).

This request is out of scope for `file_selector`. That's a plugin for interacting with file selection *dialogs*, which are unrelated to the file explorer.

Also, this can already be done using `file:` urls and the `url_launcher` plugin.
