### ISSUE TITLE
flutter how to work on multiple windows on same time

### ISSUE THREAD

**Issue by abdulrehmananwar** [flutter/flutter#100303]
currently when we navigate to new screen we have to pop that screen to come back and work on previous screen.
requirement:-
want to work on multiple screen on same times . which resizeable or selectable . just like dialog screen. butt dialog screen show single one time. i want to open multiple just like windows forms MDI child.

**Comment by darshankawar** [comment]
Closing this as a duplicate of https://github.com/flutter/flutter/issues/30701
