### ISSUE TITLE
Dart VM compiler crash

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#100375]
A crash was noticed by a customer:
```
  ../../third_party/dart/runtime/vm/compiler/backend/flow_graph_compiler.cc: 685: error: expected: !is_optimizing() || !instr->HasUnmatchedInputRepresentations()
```
Looks like that is a new assert added in https://github.com/dart-lang/sdk/commit/35eef009156c627b6a4962be2e2ce3a029d3c573

Which rolled into the Engine at https://github.com/flutter/engine/commit/a5718ab3c33bc47cbc30f599f1d3e570fb4361d7

And into the framework at https://github.com/flutter/flutter/commit/bf98767e8e5506d826eece89a4e63887f1d7baea

That is in the 2.12 beta.

@a-siva @alexmarkov @dnfield 

@godofredoc will there be a hotfix release for 2.12?

**Comment by godofredoc** [comment]
@itsjustkevin for the details on the hot fixes schedule.

**Comment by luigi-rosso** [comment]
I wasn't able to get around this a flutter clean, btw. Issue persisted.

**Comment by alexmarkov** [comment]
@zanderso Could you provide a reproduction? Can we see a full output of the compiler when it crashed?

**Comment by dnfield** [comment]
@caudetgit or @luigi-rosso are you able to share a project that reproduces this compilation error?

**Comment by a-siva** [comment]
@luigi-rosso normally the compiler dumps a stacktrace when it crashes, is it possible for you to look in the logs when these crashes happen and share the stack trace dump from the logs.

**Comment by Hixie** [comment]
@caudetgit @luigi-rosso We're not able to make further progress without a way to reproduce this, unfortunately.

**Comment by caudetgit** [comment]
@Hixie Sorry about the delay. We'll follow up as soon as we can.

**Comment by a-siva** [comment]
Should we consider lowering the priority of this issue as we don't see to have enough timely information to make any progress.

**Comment by zanderso** [comment]
Yes. I've lowered the priority and added the `waiting for customer response` label.

**Comment by caudetgit** [comment]
Hi all. We appreciate your attention on this, given competing priorities on our end it makes sense to lower the priority of this ticket for now.

**Comment by caudetgit** [comment]
updated to [flutter](https://github.com/flutter/flutter/releases/tag/2.10.5) and the build errors no longer repro

**Comment by dnfield** [comment]
@caudetgit - can you please check the latest Flutter beta and see if they're reproducing? When originally reported, this bug was showing on a revision past 2.10.5.

**Comment by luigi-rosso** [comment]
I was able to repro it on Flutter 3.0. This seems to only happen on Windows. I've tried a flutter clean, issue still presents itself.

```
  ../../third_party/dart/runtime/vm/compiler/backend/flow_graph_compiler.cc: 685: error: expected: !is_optimizing() || !instr->HasUnmatchedInputRepresentations()
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(245,5): error MSB8066: Custom build for 'C:\Users\luigi\Documents\rive\packages\editor\build\windows\CMakeFiles\7a0d611c6c003d0468c6ede5c8d1c0a8\flutter_windows.dll.rule;C:\Users\luigi\Documents\rive\packages\editor\build\windows\CMakeFiles\1290aa185e0b82bfe1dbdd59ce2f1d6f\flutter_assemble.rule' exited with code 1. [C:\Users\luigi\Documents\rive\packages\editor\build\windows\flutter\flutter_assemble.vcxproj]
Building Windows application...
Build process failed.
```


Doctor:
```
[√] Flutter (Channel unknown, 3.0.0, on Microsoft Windows [Version 10.0.19044.1645], locale en-US)
[X] Android toolchain - develop for Android devices
    X Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.1.3)
[!] Android Studio (not installed)
[√] VS Code (version 1.66.0)
[√] Connected device (3 available)
```

```flutter run -dwindows``` works fine.

I don't have an isolated repro but I can try to spend some time on one as time permits, or happy to invite someone from the Dart/Flutter team to our private repository.

**Comment by a-siva** [comment]
Do you have the full log of when the crash happens,  the compiler dumps a stacktrace when it crashes, this would help us debug the problem. Can you capture the stacktrace from the log and post it here.

**Comment by luigi-rosso** [comment]
There's no indication of where a log would've been written to in the terminal. I tried building the runner from vs2022 and it also fails with apparently no indication of a crashlog being written. Is there a known path I should be looking for this at?

![image](https://user-images.githubusercontent.com/454182/169203580-20b74418-13e3-4c1a-b7c5-3bad200a7469.png)

![image](https://user-images.githubusercontent.com/454182/169203647-a38969f8-2473-409b-b978-b96acc7060e9.png)

Building with --verbose dumps a bunch of stuff which looks like what you might be looking for:
[flutter_build_windows_verbose.txt](https://github.com/flutter/flutter/files/8723845/flutter_build_windows_verbose.txt)

**Comment by luigi-rosso** [comment]
That verbose log seems to indicate it fails compiling our websocket code. Attached
[web_socket.zip](https://github.com/flutter/flutter/files/8723873/web_socket.zip)

Note that I'm not including all the imports, some are pretty verbose and I'd prefer not to share them. Happy to give someone access to our repo.

**Comment by alexmarkov** [comment]
Standalone small repro:
```dart
class ReconnectingWebsocketClient {
  int _reconnectAttempt = 0;

  void _reconnect() {
    if (_reconnectAttempt < 1) {
      _reconnectAttempt = 1;
    }
    _reconnectAttempt *= 2;
  }
}

main() {
  ReconnectingWebsocketClient()._reconnect();
}
```

**Comment by luigi-rosso** [comment]
Fantastic thank you both!

**Comment by dnfield** [comment]
Do we want ot CP this to stable?

**Comment by a-siva** [comment]
I will file a request on the Dart side for cherry picking the change into Dart 2.17

**Comment by MrHBS** [comment]
@a-siva Can this be closed now?

**Comment by zanderso** [comment]
This can be closed.
