### ISSUE TITLE
FlutterLogo renders incorrectly in Android Emulator

### ISSUE THREAD

**Issue by lukef** [flutter/flutter#10031]
The `FlutterLogo` widget is rendering the logo incorrectly. The SVG version of the Flutter mark is invalid and it looks like the widget is exhibiting the same issue.

See below:

<img width="46" alt="screen shot 2017-05-12 at 8 48 56 am" src="https://cloud.githubusercontent.com/assets/37941/26006542/ad9e4d50-36f1-11e7-8146-b7361444012f.png">
<img width="291" alt="screen shot 2017-05-12 at 8 51 57 am" src="https://cloud.githubusercontent.com/assets/37941/26006543/ada5d692-36f1-11e7-8232-283f4871c975.png">

**Comment by sethladd** [comment]
Which version of Flutter?

I can't repro on the Flutter Gallery published in the Play Store, when I looked at the drawer.

**Comment by lukef** [comment]
Actually it is linked to #9965. It works fine on an android + ios device. It is android emulator specific.

**Comment by sethladd** [comment]
Ah, thanks for diagnosing!

**Comment by Hixie** [comment]
Woah.

cc @chinmaygarde

**Comment by Hixie** [comment]
If it's caused by the same underlying issue as #9965, then we believe this is no longer possible.
