### ISSUE TITLE
[engine] web_engine_framework.py incorrectly depends on Chromium

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#100334]
From @godofredoc the offending line in recipes is:

https://cs.opensource.google/flutter/recipes/+/master:recipes/engine/web_engine_framework.py;l=137;drc=fa625aedcfce59f89087f01d6bc8418f5f52640c

**Comment by yjbanov** [comment]
Reducing priority to P2. The https://flutter-review.googlesource.com/c/recipes/+/28085 patch fixed the tree and unblocked the Chromium 96 roll. However, the current workaround hard-codes the version number into the recipe, which means it will soon block the Chromium 99 roll.

**Comment by godofredoc** [comment]
@keyonghan can you please help with this refactor?

**Comment by keyonghan** [comment]
This needs two steps:

- [ ] Add deps property to .ci.yaml
- [ ] Inject deps from recipes

**Comment by keyonghan** [comment]
Both config and recipes changes land. We can update only .ci.yaml dependency for future version changes.
