### ISSUE TITLE
there is no "_buildRow" function in new code example

### ISSUE THREAD

**Issue by fizarum** [flutter/flutter#100362]
there is no "_buildRow" function in new code example
UPD: looks like the documentation is totally broken, the issue is in codelab docs: https://codelabs.developers.google.com/codelabs/first-flutter-app-pt2#3
But the link ("report a mistake") in that documentation leads to this repo

**Comment by darshankawar** [comment]
Probably meant in the class declaration below:

```
class _RandomWordsState extends State<RandomWords> {
  final _suggestions = <WordPair>[];
  final _saved = <WordPair>{};     // NEW
  final _biggerFont = TextStyle(fontSize: 18);
  ...
}
```

And couldn't find the said function here : https://github.com/flutter/codelabs/blob/master/startup_namer/step5_add_icons/lib/main.dart

/cc @domesticmouse

**Comment by arcanemachine** [comment]
If anybody else finds this, here's the last committed version that contains the `_buildrow` function:

https://github.com/flutter/codelabs/blob/fdaa0e0f2420e80048b0624230877572c78a8a1d/startup_namer/step4_infinite_list/lib/main.dart

**Comment by domesticmouse** [comment]
Updated the tutorial to remove all mentions of _buildRow and friends.
