### ISSUE TITLE
Android exported Flutter Problem PlayStore

### ISSUE THREAD

**Issue by tadeucosta00** [flutter/flutter#100360]
Hello, when I try to upload my app to the playstore, an error appears "You have uploaded an APK or an Android App Bundle that has an activity, activity alias, service or broadcast receiver with an intent filter, but without the property "android:exported" set. This file cannot be installed on Android 12 or higher. See: developer.android.com/about/versions/12/behavior-changes-12#exported"
but i have android exported declared in manifest.

**Comment by danagbemava-nc** [comment]
Hi @tadeucosta00, open the `android` folder of your app in `Android Studio` and open your `AndroidManifest.xml`. 

Switch from the `Text` view to the `Merged Manifest` view and check if any of your services, etc, are missing the `android:exported` property.

**Comment by navaronbracke** [comment]
As of Android 12, activities require the new flag `android:exported="true"`. You will have to add this flag to the activity in your manifest. This is not a Flutter issue.

```
        <activity
            android:name=".MainActivity"
            android:exported="true"
            android:launchMode="singleTask"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
```

**Comment by kekko7072** [comment]
Sorry but what is Merged Mainfest? Can I add android:exported directly
 in <Activity ?

**Comment by CodeProf14** [comment]
Problem Fixed here : https://youtu.be/hy0J8MNnE6g
