### ISSUE TITLE
[CP] Arm binaries are not showing up on release page

### ISSUE THREAD

**Issue by itsjustkevin** [flutter/flutter#100376]
### issue_link

None

### Commit Hash

875c552

### Impacted Users

All end-customers

### Impact Description

Flutter binaries are filtered out of the release page on flutter.dev. 

### Workaround

None

### Risk

low

### Test Coverage

yes

**Comment by godofredoc** [comment]
Now that the beta release is complete we can cherrypick this in advance. @XilaiZhang can you please help us with this PR?
