### ISSUE TITLE
Enable Multi-sampling Anti-aliasing (MSAA) behind a flag

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#100392]
See discussion in [go/flutter-aa](https://docs.google.com/document/d/1LaBh2R9Ls_JeoJjbxYgg9fu5Aic92hecufTh6-X5U4Y/edit).

@jonahwilliams has a patch for this for CanvasKit Web. I'm going to work on it for GL. Metal should be pretty doable, so should Vulkan.

For non-web, it would be good if the flag specified what sampling rate to use so we can play with different sampling rates easily.

/cc @zanderso @chinmaygarde

**Comment by dnfield** [comment]
On Metal/Skia/Ganesh, this is currently blocked because Skia seems to not support MSAA on Metal. Started a chat with some Skia folks about this to see if there's a bug to track/file or if this is WAI for them.

WIP patch is here: https://github.com/flutter/engine/compare/main..dnfield:mtl_msaa

**Comment by cbracken** [comment]
Tweaked the title to explicitly state "multi-sampling anti-aliasing" for searchability and because MSAA in a Windows context is Microsoft Active Accessibility, which we also use heavily in the Windows embedder.

**Comment by dnfield** [comment]
I think all the work we plan to do on this is done - MSAA is available behind a flag on Android and iOS (and web?), right now efforts are more focused on impeller and unlikely to come back to this.
