### ISSUE TITLE
ios/Flutter/Flutter.framework failed: No such file or directory (2) done flutter

### ISSUE THREAD

**Issue by WFNeIn** [flutter/flutter#100364]
ios/Flutter/Flutter.framework failed: No such file or directory (2) done flutter

ios build failed

how to fix this problem?

**Comment by matteotoma98** [comment]
https://github.com/flutter/flutter/issues/47712

**Comment by darshankawar** [comment]
@WFNeIn 
Can you provide `flutter doctor -v` and `flutter run -v` ? The verbose log will be huge so you can put that in a text file and share it here.

**Comment by WFNeIn** [comment]
[✓] Flutter (Channel unknown, 2.5.0, on macOS 11.3.1 20E241 darwin-x64, locale
    zh-Hans-CN)
    • Flutter version 2.5.0 at /Users/wangfeng512/Library/Application
      Support/fvm/versions/2.5.0
    • Upstream repository unknown
    • Framework revision 4cc385b4b8 (7 months ago), 2021-09-07 23:01:49 -0700
    • Engine revision f0826da7ef
    • Dart version 2.14.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/wangfeng512/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.0, Build version 13A233
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.65.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.36.0

[✓] Connected device (2 available)
    • XX的 iPhone (mobile) • 00008030-0015288E1490402E • ios            • iOS
      14.4.2 18D70
    • Chrome (web)        • chrome                    • web-javascript • Google
      Chrome 99.0.4844.74

**Comment by WFNeIn** [comment]
> #47712
I try it several times, but it does not work in my case.

**Comment by WFNeIn** [comment]
Blow is verbose log of Command _flutter run -v_

[flutter_log.pdf](https://github.com/flutter/flutter/files/8320699/flutter_log.pdf)

It work in debug and profile mode, but doesn't work in release mode. the failure reason is the title

**Comment by darshankawar** [comment]
@WFNeIn 
The pdf is too long to traverse and see the output. As suggested earlier, please put the verbose log in a text file and share it here.

**Comment by WFNeIn** [comment]
[flutter_log.txt](https://github.com/flutter/flutter/files/8328875/flutter_log.txt)

@darshankawar

**Comment by darshankawar** [comment]
@WFNeIn 
The log shows below failure:

```
Build/Intermediates.noindex/Runner.build/Release-ipho
                            neos/Runner.build/Script-94A2EEFB2511A7EC00D6CA9D.sh
                        fatal error: lipo: can't open input file:

/Users/wangfeng512/Desktop/flutter_project/house360/flutter_house730/ios/Flu
                        tter/Flutter.framework/Flutter (No such file or
directory)


ios/Flutter/Flutter.framework/Flutter (No such file or
directory)
```

Can you show Thin Binary from xcworkspace ? `ios/Runner.xcworkspace` and go to your Runner build phases and give us a screen shot.


Did you manually deleted the build phase or edited the Flutter build script phase in Xcode ?

**Comment by WFNeIn** [comment]
<img width="620" alt="截屏2022-03-23 17 14 28" src="https://user-images.githubusercontent.com/6038294/159665071-ae73e52d-ff75-4934-9434-96fef34e9b30.png">
 
It built successfully in debug and release model, but failed in release model.

I thought I didn't do it.

**Comment by darshankawar** [comment]
So, is it resolved ?

**Comment by WFNeIn** [comment]
No

**Comment by WFNeIn** [comment]
Sorry, i maybe mislead you. 

It built successfully in debug and profile model, but failed in release model.

The failure reason is that _ios/Flutter/Flutter.framework failed: No such file or directory (2) done flutter_

I try many ways but can not solve it.

**Comment by darshankawar** [comment]
@WFNeIn 
I noticed that you are on older version of framework, 2.5.0. Please upgrade to latest stable (2.10.3) and try again to see if it helps.

**Comment by WFNeIn** [comment]
I try it with 2.10.3, but it doesn‘t help. it failed with the same reason.

**Comment by darshankawar** [comment]
Try [this](https://github.com/flutter/flutter/issues/57554#issuecomment-631627015) solution and see if it works.

**Comment by WFNeIn** [comment]
Thank you, I solve it. 

I have a run script which has a path reference to the Flutter.framework in my project.

Does the building based on the latest version  not generate Flutter.framework or App.framework?

**Comment by WFNeIn** [comment]
Thank you, I solve it. 

I have a run script which has a path reference to the Flutter.framework in my project.

Does the building based on the latest version  not generate Flutter.framework or App.framework?

**Comment by darshankawar** [comment]
Closing this as resolved.
