### ISSUE TITLE
[Linux] Desktop app fails to run in Android studio ProcessException: Failed to find "ninja" in the search path.

### ISSUE THREAD

**Issue by disburden** [flutter/flutter#100318]
I had no problem running the project (the basic demo) on the terminal using the 'flutter run -d Linux 'command.
But I got the following error in the Android Stuido IDE when I ran the project by clicking the green Run button on the top toolbar
![image](https://user-images.githubusercontent.com/1391188/158859883-68bc7e0a-ca4e-4080-974c-c1a170cfb245.png)
```shell
ProcessException: Failed to find "ninja" in the search path.
Command: ninja
```

I can correctly run the Ninja command from any path on the terminal.
So what's the problem with Android Studio?
How to solve this problem?

================================

flutter doctor:
```shell
Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, 2.11.0-0.1.pre, on Deepin 20.4 5.10.101-amd64-desktop, locale zh_CN.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2020.3)
[!] Proxy Configuration
    ! NO_PROXY does not contain 127.0.0.1
[✓] Connected device (2 available)
[✓] HTTP Host Availability
```

**Comment by maheshmnj** [comment]
Hi @disburden, Thanks for filing the issue. Is ninja accessible in the Android studio terminal?   Also, does `flutter run -d linux` work from the Android studio terminal?

**Comment by disburden** [comment]
Yes, the Ninja command will also run correctly on android Studio terminals.
![image](https://user-images.githubusercontent.com/1391188/159009380-c81754f7-e8f3-41f6-8639-481ef3f40ae0.png)
The "flutter run -d Linux "command can also run properly on an Android Studio terminal.
This problem only appears by clicking the Run button in the toolbar.

**Comment by maheshmnj** [comment]
@stevemessick Any idea why this could be happening?

**Comment by stevemessick** [comment]
It sounds like the PATH environment variable is not being set correctly. There is some discussion about that in this issue:
https://youtrack.jetbrains.com/issue/IDEABKL-7589

@disburden Try one of the suggestions there if you are using bash. If you are using another shell you'll have to check its documentation to find how to properly set PATH. Let us know if that fixes your problem.

**Comment by disburden** [comment]
@stevemessick Thank you very much! I solved the problem according to the web page you provided, but I am not sure which step is effective now. I am busy with a project these days, and I will confirm again when I am free, but I can confirm that the problem is caused by the desktop shortcut icon(or system menu) setting.

Please close this issue.

**Comment by maheshmnj** [comment]
Thanks for the update @disburden
