### ISSUE TITLE
[camera] Camera preview mirrored on Windows

### ISSUE THREAD

**Issue by jgoyvaerts** [flutter/flutter#100374]
Currently, when using the camera_windows plugin, when rendering the camera preview, it shows a mirrored camera image.
When taking a picture, the actual picture is not mirrored and is displayed correctly.

The native Windows camera client included with Windows 10 does not perform any mirroring when showing the preview or taking the picture, so the flutter behavior is not in line with the "default".

Also, it's a very weird user experience to see a preview of an image which is then flipped when you actually take a picture.

cc @stuartmorgan

**Comment by stuartmorgan** [comment]
> Also, it's a very weird user experience to see a preview of an image which is then flipped when you actually take a picture.

How so? I don't think I've ever seen a front-facing phone camera that *doesn't* behave this way, so I would think people would find that very natural.

**Comment by jgoyvaerts** [comment]
The default behavior on phones is to mirror the preview AND the picture taken (tested on my Samsung, but I assume Apple is the same).

The default behavior on Windows desktop Camera app is to perform no mirroring for preview or taken picture for a webcam (as if someone was taking a picture from you, standing right behind your monitor).

The default flutter camera_windows implementation is to mirror only the preview, but not the taken picture.

Whichever way you feel if camera_windows should behave like a phone or a desktop, only mirroring the preview without the taken picture feels like a bug.

**Comment by jgoyvaerts** [comment]
Interesting, apparently I've been stuck on Samsung for a bit too long and got used to this behavior. 
Tested on Sony for completeness, they also mirror the preview but not the photo.

I'll take a look at implementing that feature.
