### ISSUE TITLE
When tests run on Appveyor they don't show errors

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#10033]
When a test fails on Appveyor, it just gets marked as failed, the logs don't actually appear.
This makes debugging tests that fail on Appveyor quite difficult.

cc @goderbauer

**Comment by goderbauer** [comment]
Do you have a link to an invocation where this happens? I usually see the failure exception.

**Comment by Hixie** [comment]
The case I noticed was an error in a flutter_tools test, though it's gone now because I fixed the test. :-)

**Comment by goderbauer** [comment]
I can't reproduce this. It shows a nice failure for me locally and on appveyor: https://ci.appveyor.com/project/flutter/flutter/build/1.0.2631

**Comment by Hixie** [comment]
o_O

I'm going to close this until I can prove I'm not insane.
