### ISSUE TITLE
[Android] The Flutter TextField soft keyboard on Android 12 does not display

### ISSUE THREAD

**Issue by Soda1912** [flutter/flutter#100356]
Phone :
> Android 12的机型

Models with Android 12

Android project info：
compileSdkVersion 29
minSdkVersion 21
targetSdkVersion 28

video：

https://user-images.githubusercontent.com/34225774/158973272-d8507561-c2e2-4922-80af-790c60e214d4.mp4

Descrription

On Android 12, the soft keyboard of Flutter TextField is blank when it gets focus, and the keyboard is normal when it is unlocked again after the screen is locked.

Android native projects embed the Flutter Library as an AAR.

```
Widget get _textField {
    return BlocBuilder<WKPrepayAmountBloc, WKPrepayAmountState>(
      builder: (context, state) {
        return TextField(
          controller: _controller..wkSetText(state.value),
          keyboardType: TextInputType.numberWithOptions(),
          textInputAction: TextInputAction.done,
          decoration: InputDecoration(
            border: InputBorder.none,
            hintText: '请输入',
            hintStyle: TextStyle(
              fontSize: WKFontSize.size15,
              color: WKColors.hex999999,
            ),
          ),
          style: TextStyle(
            fontSize: WKFontSize.size15,
            color: WKColors.hex333333,
          ),
          inputFormatters: [
            WKRegExpTextInputFormatter(_regExr)
          ],
          onChanged: (text) {
            context.read<WKPrepayAmountBloc>().add(WKPrepayAmountChanged(text));
          },
        );
      },
    );
  }
```

Flutter doctor -v：

![image](https://user-images.githubusercontent.com/34225774/158964752-aade8954-0e3b-4618-bc39-11997b364752.png)

**Comment by danagbemava-nc** [comment]
Hi @Soda1912 

Can you please a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) preferably in a repo that we can use to verify this?

Thank you

**Comment by Soda1912** [comment]
> 嗨@Soda1912
> 
> 您可以请一个[最简单的可替代代码示例](https://stackoverflow.com/help/minimal-reproducible-example)，最好在我们使用验证点的完整功能中吗？
> 
> 谢谢

hi @danagbemava-nc 

I found a solution ， add `android:hardwareAccelerated="true"` with AndroidManifest.xml 

We can close this problem
