### ISSUE TITLE
Linux/Wayland: on-screen keyboard does not appear on first text field focus

### ISSUE THREAD

**Issue by wmww** [flutter/flutter#100385]
On Wayland, the first time a text field is focused the on-screen keyboard does not appear. To make it appear, you have to click the text box again. Confusingly, GNOME *always* requires two clicks to open it's OSK. On GNOME, the first time you have to click a text field 3 times and after that it's just 2.

The cause is that `show()` in fl_text_input_plugin.cc calls `gtk_im_multicontext_set_client_window()`. The first time any of the input module functions are called they initialize. However, initializing on Wayland requires multiple a server roundtrips, which the input module doesn't wait for therefor the first enable does not succeed but subsequent ones do.

**Comment by maheshmnj** [comment]
HI @wmww, thanks for filing the issue, I verifies on Linux Ubuntu and I was not able to reproduce the issue the onscreen keyboard shows up on with a single tap on the textfield.

https://user-images.githubusercontent.com/31410839/159222365-39f6010e-71a2-4099-acdb-8b6d26429be3.mp4


Please share the output of `flutter doctor -v`

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      // This call to setState tells the Flutter framework that something has
      // changed in this State, which causes it to rerun the build method below
      // so that the display can reflect the updated values. If we changed
      // _counter without calling setState(), then the build method would not be
      // called again, and so nothing would appear to happen.
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: Column(
          // Column is also a layout widget. It takes a list of children and
          // arranges them vertically. By default, it sizes itself to fit its
          // children horizontally, and tries to be as tall as its parent.
          //
          // Invoke "debug painting" (press "p" in the console, choose the
          // "Toggle Debug Paint" action from the Flutter Inspector in Android
          // Studio, or the "Toggle Debug Paint" command in Visual Studio Code)
          // to see the wireframe for each widget.
          //
          // Column has various properties to control how it sizes itself and
          // how it positions its children. Here we use mainAxisAlignment to
          // center the children vertically; the main axis here is the vertical
          // axis because Columns are vertical (the cross axis would be
          // horizontal).
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            TextField(),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}

```
</details>

<details>
<summary>flutter doctor -v (Linux)</summary>

```
[✓] Flutter (Channel stable, 2.10.3, on Ubuntu 20.04.4 LTS 5.13.0-30-generic, locale en_GB.UTF-8)
    • Flutter version 2.10.3 at /home/mahesh/Development/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (13 days ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /home/mahesh/Android/Sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /home/mahesh/Downloads/android-studio-2020.3.1.25-linux/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 2020.3)
    • Android Studio at /home/mahesh/Downloads/android-studio-2020.3.1.25-linux/android-studio
    • Flutter plugin version 63.2.1
    • Dart plugin version 203.8452
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.64.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.36.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 20.04.4 LTS 5.13.0-30-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 98.0.4758.102

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by AlanGriffiths** [comment]
> HI @wmww, thanks for filing the issue, I verifies on Linux Ubuntu and I was not able to reproduce the issue the onscreen keyboard shows up on with a single tap on the textfield.

Are you sure you are using a GNOME/Wayland session? I see the same problem that @wmww reports when using a Wayland session. (Ubuntu 20.04LTS)

**Comment by maheshmnj** [comment]
Thanks for the info @AlanGriffiths,  I verified on `Ubuntu 20.04.4 LTS 5.13.0-30-generic` could you please help me with How I can use `GNOME/Wayland session` or share a link that I could refer to ?

**Comment by wmww** [comment]
You select "Ubuntu on Wayland" on the login screen. You may have to edit a config file if that's not available. This seems to be a good tutorial: https://linuxconfig.org/how-to-enable-disable-wayland-on-ubuntu-20-04-desktop

**Comment by maheshmnj** [comment]
Thanks for the link @wmww, I logged in using  "Ubuntu on Wayland" selected, and The onscreen keyboard isn't launching for any of the third-party apps and the keyboard shows up fine for the terminal, settings etc. Let me know if I need to make any other configuration to see the keyboard launching in other apps.
 
https://user-images.githubusercontent.com/31410839/159633270-e34edf6b-011d-48c0-8e0f-9f9a21544cd5.mp4

<details>
<summary>flutter doctor -v (Linux)</summary>

```
[✓] Flutter (Channel stable, 2.10.3, on Ubuntu 20.04.4 LTS 5.13.0-30-generic, locale en_GB.UTF-8)
    • Flutter version 2.10.3 at /home/mahesh/Development/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (13 days ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /home/mahesh/Android/Sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /home/mahesh/Downloads/android-studio-2020.3.1.25-linux/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 2020.3)
    • Android Studio at /home/mahesh/Downloads/android-studio-2020.3.1.25-linux/android-studio
    • Flutter plugin version 63.2.1
    • Dart plugin version 203.8452
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.64.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.36.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 20.04.4 LTS 5.13.0-30-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 98.0.4758.102

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by wmww** [comment]
Perhaps you didn't click on the same text field enough times? Or the version of something is different than mine?

I just reprod this on an up-to-date Ubuntu 20.04 VM. My exact steps:
- enable screen keyboard in settings
- log in to Ubuntu on Wayland session
- `sudo snap install purple-task --edge`
- open purple-task
- click three times in text box
- only on the third click the keyboard comes up

**Comment by maheshmnj** [comment]
Thanks for the info @AlanGriffiths, I tried multiple taps on the `Textfield` But for some reason, the keyboard doesn't show up. I tried the purple-task app and the keyboard shows up with two taps (Not sure if that is a native app or flutter app)
 
https://user-images.githubusercontent.com/31410839/159854001-2c9eebf0-13da-497d-9bbb-c4d0d87b2f4f.mp4

Please share your output of `flutter doctor -v`.

<details>
<summary>flutter doctor -v (Linux)</summary>

```
[✓] Flutter (Channel stable, 2.10.3, on Ubuntu 20.04.4 LTS 5.13.0-30-generic, locale en_GB.UTF-8)
    • Flutter version 2.10.3 at /home/mahesh/Development/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (13 days ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /home/mahesh/Android/Sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /home/mahesh/Downloads/android-studio-2020.3.1.25-linux/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 2020.3)
    • Android Studio at /home/mahesh/Downloads/android-studio-2020.3.1.25-linux/android-studio
    • Flutter plugin version 63.2.1
    • Dart plugin version 203.8452
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.64.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.36.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 20.04.4 LTS 5.13.0-30-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 98.0.4758.102

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by wmww** [comment]
Purple-task is a Flutter app.

Are you absolutely sure that the *first* time you focus a text field on purple-task (after launching the app) it takes only two clicks to bring up the OSK, and not three? I suppose it's possible a different GTK input method module is being used or there's a race condition, but that doesn't explain why it's different on our systems.

I've asked someone on my team to try to repro as well.

I'm not surprised Chrome and Electron apps don't bring up the OSK, their Wayland support is less complete than Flutter.

**Comment by Saviq** [comment]
I can confirm this on GNOME on Ubuntu 21.10. You can see that the text field gets focused (at ~8s in) way before the OSK pops up (that's a second tap).

https://user-images.githubusercontent.com/231077/159999700-b30e1566-e5d5-4a7d-89e3-b84ed2207e56.mov

**Comment by maheshmnj** [comment]
I am unable to reproduce the issue. Because the keyboard doesn't show up when running with Wayland session as [mentioned here ](https://github.com/flutter/flutter/issues/100385#issuecomment-1077279238) Labeling this issue for further investigation from the team.

**Comment by AlanGriffiths** [comment]
I think there's confusion appearing here, so I'll try a summary...

There are multiple ways to put focus on a text field, in the above we have both clicking with a mouse and tapping on touchscreen.

On GNOME/Wayland, for GTK apps, it takes one touch tap or two mouse clicks to invoke the OSK.
On GNOME/Wayland, for Flutter apps (for example purple-task), it takes two touch taps or three mouse clicks to invoke the OSK.

Some other toolkits may lack support for the necessary Wayland extensions and not show the OSK at all.

**Comment by maheshmnj** [comment]
Thanks for the clarification @AlanGriffiths, However, I can confirm that with two taps the keyboard shows up in purple-task, while the keyboard doesn't show up at all in flutter apps, chrome, vscode regardless of the number of clicks, when running on Linux Ubuntu with Wayland session.

cc: @cbracken

**Comment by AlanGriffiths** [comment]
> with two taps the keyboard shows up in purple-task, while the keyboard doesn't show up at all in flutter apps

Obviously, there is some difference between your environment and mine as I see the same behaviour for all flutter apps I've tried. Not just purple-task. (You do know purple-task **is** a flutter app?!)

**Comment by maheshmnj** [comment]
> You do know purple-task is a flutter app?!

Looks like it is https://github.com/mivoligo/purple_task

**Comment by wmww** [comment]
To summarize:
- All this only applicable to Wayland sessions
- GNOME OSK does not show up at all on many non-flutter, non-GTK apps (this is not our problem)
- On touchscreen taps, GNOME pops up the OSK with only one interaction, unlike mouse clicks were it takes two (this was not previously known to me)
- This bug is about it taking an *extra* interaction the *first* time the OSK is brought up for a flutter app
- This bug is also present on Ubuntu Frame + Ubuntu Frame OSK, and presumably in other contexts such as Phosh
- As far as I know, this bug is present on all recent versions of Flutter including current main.

If on purple-task or any other Flutter app you see the OSK coming up on the same number of interactions the first time as subsequent times, that would be strange. maheshmnj seems to be the only one who's observed this.
