### ISSUE TITLE
[video_player] Flaky "ExoPlaybackException: Source error" in Android integration tests

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#100373]
Yesterday video_player's Android integration test failed on one of the two devices on the original and the auto-retry, for both of the following tests:
- reports buffering status
- live stream duration != 0

The failure in each case was:
```
java.lang.Exception: ══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞═════════════════
The following PlatformException was thrown running a test:
PlatformException(VideoError, Video player had error
com.google.android.exoplayer2.ExoPlaybackException: Source error,
null, null)
When the exception was thrown, this was the stack
The test description was:
reports buffering status
```

One test uses an asset from our repository, accessed via a GitHub URL, and the other currently uses an external server (https://cph-p2p-msl.akamaized.net), so this may have been a network issue for the device that it was running on. Notably, those tests are the only ones in that test suite that use network-based loading.

If that's the case, the way to prevent this from happening in the future is https://github.com/flutter/flutter/issues/95420.

**Comment by sonanis** [comment]
I have the same problem, but it is due to I forget set that android:usesCleartextTraffic="true"

**Comment by stuartmorgan** [comment]
This specific instance should be fixed by https://github.com/flutter/plugins/pull/5103, so closing. The move to a local server is still tracked in the other issue.
