### ISSUE TITLE
[CP] Fix to verify_binaries_codesigned test

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#100397]
### issue_link

https://github.com/flutter/flutter/issues/100306

### Commit Hash

0adf9671f

### Impacted Users

all users of Flutter beta releases

### Impact Description

This test failing is a blocker to releasing to the beta channel.

### Workaround

In the last beta release, this had to be worked around by a release engineer manually running the test locally and verifying the test passed.

### Risk

low (a new release does not have to be produced, merely merging the cherrypick to the candidate branch will give pass/fail signal)

### Test Coverage

yes

### Validation Steps

Post-merging, the `Mac verify_binaries_codesigned` test should pass.

**Comment by itsjustkevin** [comment]
CC @godofredoc @CaseyHillers @XilaiZhang
