### ISSUE TITLE
master latest run flutter doctor error

### ISSUE THREAD

**Issue by xiaocode337317439** [flutter/flutter#100339]
Failed to download
https://storage.flutter-io.cn/flutter_infra_release/flutter/4ac53a5b86709351aa53
e011c6fd8703ee2bd8fe/flutter_patched_sdk_product.zip. Ensure you have network
connectivity and then try again.
Exception: 404

**Comment by darshankawar** [comment]
@xiaocode337317439 
As the error indicates, it could be happening due to poor / slow network connectivity. Try again with a better / faster network connection. See [this](https://docs.flutter.dev/community/china) for more details.

Closing, as this is related to connectivity.
