### ISSUE TITLE
Icon tree shaking removes ligatures

### ISSUE THREAD

**Issue by michaelspiss** [flutter/flutter#100325]
Font awesome uses two glyphs for the different colored parts of their duotone icons. They recently updated this system to no longer use two separate code points for their primary and secondary glyph. Instead, they opted for ligatures - two consecutive equal code points of the primary are mapped to the secondary glyph.

As there is no way to address ligatures using IconData (because it only allows for one code point), ligatures will always be removed.

I am not sure if this is something that should even be worked on, as this is such a niche case - but I wanted to let you know nevertheless.

Expected (web):
![duotone_expected](https://user-images.githubusercontent.com/17252710/158875328-3e034338-eb20-4e87-b423-35ab8610e71b.png)
Actual (apk with icon tree shaking):
![Screenshot_20220317-193227](https://user-images.githubusercontent.com/17252710/158875390-bfc441a8-dff2-463a-9353-b41deda5aa12.jpg)

**Comment by darshankawar** [comment]
@michaelspiss 
Thanks for the report. Is `duotoneFillDrip` icon coming from https://pub.dev/packages/font_awesome_flutter/install ?
If so, I couldn't find the same trying to use `child: Icon(
          FontAwesomeIcons.`

Also, is the expected rendering of the said icon specific to web only ?

**Comment by michaelspiss** [comment]
I should have specified - they are part of the pro package of font awesome. And no, the icon looked the same as in the web version when disabling icon tree shaking for the apk

**Comment by darshankawar** [comment]
Thanks for the update. Keeping it open and labeling it for further insights from the team.

/cc @guidezpl if you have any input on this.

**Comment by guidezpl** [comment]
@dnfield Hey Dan, I think you wrote icon tree shaking, would love your input on this

**Comment by dnfield** [comment]
Icon data allows for multiple code points (in fact, most icons are multiple code points) - but to work on this we'd really need a complete reproducible example. It would not surprise me if there's something off about the way we're using font-subset for ligatures.

Can you please share a complete example with a font that contains ligatures and the icon data you're trying to use that shows them without icon shaking but fails to show them with it?

**Comment by dnfield** [comment]
This might be a bit nitpicky, but `0xf08b` is two code points.

You could certainly try passing four codepoints for the icon data definition.  I would try doing `0xf08bf08b` for the icon data definition and see if that resolves things.

If it doesn't, there's not much else I can do without a reproducible case.

**Comment by michaelspiss** [comment]
Not nitpicky, actually a welcome clarification.

`0xf08bf08b` is outside the available range, so sadly this is not possible.

You are right, it does not make sense to investigate this any further if I cannot even show you the example code.
Font awesome may be able to provide better resources themselves, should they be interested in duotone icons for flutter.
I am going to close this issue.

Thank you @dnfield for your help!
