### ISSUE TITLE
FLUTTER_FRAMEWORK_DIR didn't exist in Generated.xcconfig, which cause ios build failed.

### ISSUE THREAD

**Issue by WFNeIn** [flutter/flutter#100365]
FLUTTER_FRAMEWORK_DIR didn't exist in Generated.xcconfig, which cause ios build failed.

How to fix this problem?

My Generated.xcconfig is blow:

`// This is a generated file; do not edit or check into version control.
FLUTTER_ROOT=/Users/wangfeng512/Library/Application Support/fvm/versions/2.5.0
FLUTTER_APPLICATION_PATH=/Users/wangfeng512/Desktop/flutter_project/house360/flutter_house730
COCOAPODS_PARALLEL_CODE_SIGN=true
FLUTTER_TARGET=/Users/wangfeng512/Desktop/flutter_project/house360/flutter_house730/lib/main.dart
FLUTTER_BUILD_DIR=build
FLUTTER_BUILD_NAME=1.6.01
FLUTTER_BUILD_NUMBER=1601
EXCLUDED_ARCHS[sdk=iphonesimulator*]=i386 arm64
DART_DEFINES=Zmx1dHRlci5pbnNwZWN0b3Iuc3RydWN0dXJlZEVycm9ycz10cnVl,RkxVVFRFUl9XRUJfQVVUT19ERVRFQ1Q9dHJ1ZQ==
DART_OBFUSCATION=false
TRACK_WIDGET_CREATION=true
TREE_SHAKE_ICONS=false
PACKAGE_CONFIG=/Users/wangfeng512/Desktop/flutter_project/house360/flutter_house730/.dart_tool/package_config.json`

**Comment by darshankawar** [comment]
@WFNeIn 
This might be related to your earlier issue reported, https://github.com/flutter/flutter/issues/100364 so let's track in it.
Closing this as duplicate.
