### ISSUE TITLE
"hot reload" animated gif has "slow mode" banner, fast _and_ slow?

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#10037]
What do we think about removing the Slow Mode banner from our canonical Hot Reload animated gif?

Might send a better message to talk about "fast development" and not have a read slow mode banner :)

**Comment by sethladd** [comment]
cc @mit-mit

**Comment by Hixie** [comment]
The reality is that the banner will be there when doing what that demo shows (unless you manually turn it off, which I guess you could). We could overlay something else over the GIF in that corner, to draw attention away from it, maybe.

**Comment by mit-mit** [comment]
Should we consider changing the banner to 'Debug'? That would also be consistent with the name of the build flavor.

**Comment by sethladd** [comment]
I'm happy to try "dev mode" or "debug mode" and see how users react.

**Comment by Hixie** [comment]
We've considered "DEBUG", "DEV MODE", and various other labels. The reason we went with "SLOW MODE" is that we added it specifically because people would come to us complaining about performance, and we'd discover they were in debug mode, and they didn't understand that debug mode meant slowness.

**Comment by sethladd** [comment]
Did the banner used to say DEBUG MODE ?

**Comment by sethladd** [comment]
Going to close for now. if the product removes the banner, we'll take a new screenshot.
