### ISSUE TITLE
webview_flutter_wkwebview-2.7.1 flutter build ios fail 'Flutter/Flutter.h' file not found 

### ISSUE THREAD

**Issue by ZeeshanJelani** [flutter/flutter#100448]
Im not using this package. but i run flutter build ios/flutter build ipa or archive in xcode.they give me this error.i try different thing like cache clean,update all package to latest one,my code was on sdk 2.0.7 i update whole to latest version of flutter,remove webview_flutter_wkwebview-2.7.1 from pub cache file and after that pub get pod update. but still im facing same error. app run fine on flutter run but its error on build ipa or deploy time?

**Comment by darshankawar** [comment]
@ZeeshanJelani 
Please provide `flutter doctor -v`, `pubspec.yaml` , `flutter run -v` and `ios/podfile`. The verbose log will be huge so you can put that in a text file and share it here.

**Comment by FirstSource-cyber** [comment]
I resolve this problem.By adding!!
dependency_overrides: 
  webview_flutter: 2.0.4

**Comment by ZeeshanJelani** [comment]
Thanks bro.
I resolve this problem.By adding!!
dependency_overrides:
webview_flutter: 2.0.4

**Comment by darshankawar** [comment]
Closing this as resolved.
