### ISSUE TITLE
NestedScrollView example app doesn't remember scroll position 

### ISSUE THREAD

**Issue by tomgilder** [flutter/flutter#100473]
On the sample at https://api.flutter.dev/flutter/widgets/NestedScrollView-class.html, it claims the example will remember the scroll position of each scroll view:

> "In addition, [PageStorageKey](https://api.flutter.dev/flutter/widgets/widgets/PageStorageKey-class.html)s are used to remember the scroll position of each tab's list."

But the scroll position resets after changing tabs:

https://user-images.githubusercontent.com/756862/159236269-3c658ff4-a694-4c25-b0d1-4426c6e709d5.mov

Page is currently on Flutter build 2.10.3.

**Comment by tomgilder** [comment]
@maheshmnj hmm, doesn't seem to be working on https://master-api.flutter.dev/flutter/widgets/NestedScrollView-class.html - is that up-to-date enough? Maybe it's just an issue when embedded in the docs?

**Comment by tomgilder** [comment]
@maheshmnj ah, it seems to be a Flutter bug.

It only happens when scrolling with the trackpad; wrapping the `CustomScrollView` in a `Scrollbar` and using that results in the correct behaviour. 

I'll see if I can find another issue about this.

**Comment by maheshmnj** [comment]
>  doesn't seem to be working on https://master-api.flutter.dev/flutter/widgets/NestedScrollView-class.html

Yes, the interactive sample from the docs doesn't seem to work, But it seems to work locally with the same version, I wonder  if the samples on master are compiled against the latest master. 

```console
Flutter 2.13.0-0.0.pre.191 • channel master • https://github.com/flutter/flutter.git
Framework • revision 69b92f0452 (2 hours ago) • 2022-03-21 21:25:09 -0700
Engine • revision e6233bd30b
Tools • Dart 2.17.0 (build 2.17.0-223.0.dev) • DevTools 2.11.4
```

> It only happens when scrolling with the trackpad; wrapping the CustomScrollView in a Scrollbar and using that results in the correct behaviour.

It May be related to https://github.com/flutter/flutter/issues/23604


@piinks might have more info about this.
