### ISSUE TITLE
WidgetApp.onGenerateInitialRoutes and Navigator.onGenerateInitialRoutes should have the same types/parameters

### ISSUE THREAD

**Issue by oklimberg** [flutter/flutter#100487]
## Use case

I have a deep link to my Flutter web app from an email confirmation mail. This page should not generate any kind of history stack.
As far as I understood the documentation, I should use onGenerateInitialRoutes of the WidgetApp (in my case a MaterialApp)
to overwrite the default behaviour. But only this specific link should behave different than the default. In all other cases, I would like to revert to the default behaviour. But Navigator.defaultGenerateInitialRoutes has a different set of arguments, so I cannot call
this implementation as fallback after checking the initialRouteName parameter.

## Proposal

Change the signature of InitialRouteListFactory to match RouteListFactory

**Comment by maheshmnj** [comment]
Hi @oklimberg, Thanks for filing the issue. 
> I have a deep link to my Flutter web app from an email confirmation mail. This page should not generate any kind of history stack.

Please share the minimal and complete code sample along with the output of `flutter doctor -v` to investigate the issue further.
