### ISSUE TITLE
[Fonts] Icon request: currency_bitcoin

### ISSUE THREAD

**Issue by elankovan-amepay** [flutter/flutter#100462]

**Comment by danagbemava-nc** [comment]
Hi @elankovan-amepay, the `currency_bitcoin` icon already exists in flutter stable 2.10.3 under the name `currency_bitcoin`. The material icon site just hasn't been updated yet. Closing this issue as the icon is already available in stable 2.10.3. Thank you

<img width="200" alt="Screenshot 2022-03-21 at 08 01 55" src="https://user-images.githubusercontent.com/88313112/159223190-7bda0938-b743-4336-a797-d67daf341242.png">
