### ISSUE TITLE
http request not working with server hosted on ESP32

### ISSUE THREAD

**Issue by ilyasRikI** [flutter/flutter#100446]
I connect to the esp 32 using wifi_iot library and works fine (only for android).
I try to call a get request to the hosted server but the dosn't recognize the GET method.
when I try some open url online it works fine.
I tried many libraries such as Dio http and more, and used httpLogger to see what it logs, but shows no response from the device.

codes I tried :

 
`Future connect() async {  `
`    //var url = Uri.parse("http://192.168.4.1:80/getData");  `
`    //var url = Uri.parse("https://api.publicapis.org/entries");  `
`    var url = Uri.parse("http://192.168.4.1:80/getData");  `
`    get(url);  `
`    }`

` getRequest() async {`
`    Uri? url = Uri.tryParse("http://192.168.4.1:80/getData");`
`    httpa.Request request = new httpa.Request("GET", url!);`
`    request.headers.clear();`
`    var letsGo = await request.send();`
`    print(letsGo.statusCode);`
`  }`

`  getRequestWithException() async {`
`    int timeout = 30;`
`    try {`
`      httpa.Response response = await http.get(Uri.tryParse("http://192.168.4.1:80/getData")!).`
`      timeout(Duration(seconds: timeout));`
`      if (response.statusCode == 200) {`
`        print('REQUEST ACCEPTED: HTTP SHST');`
`      } else {`
`        print('REQUEST FAILED: HTTP');`
`      }`
`    } on TimeoutException catch (e) {`
`      print('Timeout Error: $e');`
`    } on SocketException catch (e) {`
`      print('Socket Error: $e');`
`    } on Error catch (e) {`
`      print('General Error: $e');`
`    }`
`  }`

I suspect that http library contain some issues when the endpoint has no internet.

the http request has been tested with the phone browser and native android app and it works fine and return success code 200.
anyone has been throw a similar situation ?

flutter doctor -v
Flutter (Channel master, 2.11.0-0.0.pre.582, on macOS 12.2.1 21D62 darwin-arm, locale en-DE)
    • Flutter version 2.11.0-0.0.pre.582 at /Users/ilyas/Library/Android/sdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9514106108 (5 weeks ago), 2022-02-16 00:00:11 -0500
    • Engine revision b09cf53269
    • Dart version 2.17.0 (build 2.17.0-105.0.dev)
    • DevTools version 2.10.0

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/imrikim/Library/Android/sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] Connected device (3 available)
    • SM A127F (mobile)       • RZ8T100X7CV               • android-arm64  • Android 11 (API 30)
    • Ilyas’s iPhone (mobile) • 00008110-000E592426FA801E • ios            • iOS 15.3.1 19D52
    • Chrome (web)            • chrome                    • web-javascript • Google Chrome 96.0.4664.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Comment by darshankawar** [comment]
> I suspect that http library contain some issues when the endpoint has no internet.

Please open this issue in dedicated repo: https://github.com/dart-lang/http/issues

Closing from here.
