### ISSUE TITLE
Import or depend on compiled binary flutter packages

### ISSUE THREAD

**Issue by trigchen** [flutter/flutter#100412]
I'm planning to create a plug-ins based rich client platform application like Eclipse or VS Code. The flutter main application will include any views (widgets / screens) which are contributed by other flutter packages. Currently to do that, the main application project has to import source codes of the sub-views' packages to build together. I have no ideas how can I depend or import sub-view package in compiled binary format, not in .dart source code format. Any idea or any  RCP application examples based on flutter are welcomed.

**Comment by maheshmnj** [comment]
Hi @trigchen,
 
This issue doesn't seem to describe a bug or a feature request. Please see https://flutter.dev/community#community-grid for resources and asking questions like this. You may also get some help if you post it on Stackoverflow with a minimal code sample that clearly describes your problem.

Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and we will reopen it.

Thank you
