### ISSUE TITLE
[webview_flutter] [ios] Unable to find a specification for `webview_flutter_wkwebview` depended upon by `FlutterPluginRegistrant`

### ISSUE THREAD

**Issue by rgjurgens** [flutter/flutter#100480]
## Steps to Reproduce

Try to include `webview_flutter` in a Flutter module embedded in an iOS app

**Expected results:** 

<img width="572" alt="image" src="https://user-images.githubusercontent.com/3368717/159283780-0d4344b6-827f-4772-b830-d6cd0f97529c.png">

**Actual results:** 

Unable to find a specification for `webview_flutter_wkwebview` depended upon by `FlutterPluginRegistrant`.

When compiling the app in Xcode, Xcode stops on file `GeneratedPluginRegistrant.m` with the error message:

```
@import webview_flutter_wkwebview; - _Module 'webview_flutter_wkwebview' not found_
```

`Edit` I now see that Cocoapods cannot get the dependency `webview_flutter_wkwebview` in the `podspec` of `FlutterPluginRegistrant` - does that give anyone a clue?

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel stable, 2.10.2, on macOS 12.2.1 21D62 darwin-x64, locale
    en-NL)
    • Flutter version 2.10.2 at /Users/rgjurgens/dev/tools/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 097d3313d8 (4 weeks ago), 2022-02-18 19:33:08 -0600
    • Engine revision a83ed0e5e3
    • Dart version 2.16.1
    • DevTools version 2.9.2

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/rgjurgens/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Community Edition (version 2019.2.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.65.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.36.0

[✓] Connected device (2 available)
    • iPhone 11 (mobile) • F898B8B3-56E5-4776-90C4-17FA0AF0C101 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)
    • Chrome (web)       • chrome                               • web-javascript
      • Google Chrome 99.0.4844.74
    ! Error: Dolf’s iPhone is not connected. Xcode will continue when Dolf’s
      iPhone is connected. (code -13)

[✓] HTTP Host Availability
    • All required HTTP hosts are available
```
</details>

**Comment by darshankawar** [comment]
@rgjurgens 
Can you try [this](https://github.com/flutter/flutter/issues/69024#issuecomment-869139468) solution and see if it works for you ?

**Comment by rgjurgens** [comment]
@darshankawar Thank you so much for replying! I've spent loads of time on this issue now. However, the issue seems not even `webview_flutter` related. It seems like `pod install` cannot fetch the dependency for the `FlutterPluginRegistrant`, as defined in `FlutterPluginRegistrant.podspec` : `s.dependency 'webview_flutter_wkwebview'` - this `webview_flutter_wkwebview` is not a pod and Cocoapods cannot fetch it - or something like this...

**Comment by darshankawar** [comment]
@rgjurgens 
I tried a sample add_to_app and added `webview_flutter` plugin to embedded module which compiled and built the app properly:

```
Launching lib/main.dart on iPhone 12 Pro Max in debug mode...
Running pod install...
Running Xcode build...
Xcode build done.                                           50.3s
Debug service listening on ws://127.0.0.1:52918/GlodBnVSkfE=/ws
Syncing files to device iPhone 12 Pro Max...
```

https://github.com/flutter/samples/tree/master/add_to_app/books

In the podspec you referred above:

`s.pod_target_xcconfig = { 'DEFINES_MODULE' => 'YES', 'EXCLUDED_ARCHS[sdk=iphonesimulator*]' => 'i386' }` can you also add `arm64` in it to exclude archs and see if it helps ?

**Comment by rgjurgens** [comment]
@darshankawar I think I accidentally pasted the wrong `podspec` file - sorry. I just changed my post to the actual `FlutterPluginRegistrant.podspec` file. But I will check out your test project right now!

**Comment by rgjurgens** [comment]
So I found the issue! Thanks a lot for your help @darshankawar . It turned out in my `podfile` I had a structure like this:

```
def app_pods
   #Flutter
    install_all_flutter_pods("flutter_application_path")
end

target "MainProject" do
     app_pods
end
```

And, while this solution works perfect for all scenario's, _somehow_ it gave errors when fetching the `podspec` stuff. No clue why,. but maybe this helps anyone!

**Comment by darshankawar** [comment]
Glad to know your issue is resolved. Closing.
