### ISSUE TITLE
Spash-screen not displaying even after trying two different packages

### ISSUE THREAD

**Issue by kavyabhargava** [flutter/flutter#100430]
My splash-screen is a complete black screen for some reason, although the app runs fine and I am not getting any issues in the app too. I tried manually setting up the splash screen from the drawable folder in android and also tried using flutter_native_splash: ^2.1.1 but it is still a black screen.

My flutter doctor:
[√] Flutter (Channel stable, 2.10.2, on Microsoft Windows [Version 10.0.19044.1586], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.   
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2020.3)
[√] VS Code (version 1.65.2)
[√] Connected device (3 available)
[√] HTTP Host Availability

! Doctor found issues in 1 category.

**Comment by darshankawar** [comment]
@kavyabhargava 
See [this](https://docs.flutter.dev/development/ui/advanced/splash-screen#migrating-from-manifest--activity-defined-custom-splash-screens) document section and check if you have already implemented as prescribed in it. The changes were made to splash screen after migration. See if that helps to resolve your issue.

**Comment by kavyabhargava** [comment]
@darshankawar, I checked and yes I have done all this, as I was following a course for the same. I am getting this in my debug console if this tells anything: 
```
W/FlutterJNI( 6888): FlutterJNI.loadLibrary called more than once
W/FlutterJNI( 6888): FlutterJNI.prefetchDefaultFontManager called more than once
I/ResourceExtractor( 6888): Found extracted resources res_timestamp-1-1647899020343
W/FlutterJNI( 6888): FlutterJNI.init called more than once

```
The spash-screen part is comingup completely black

**Comment by darshankawar** [comment]
@kavyabhargava 
Can you provide [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) along with splash screen implementation (without using third party plugin) to see how are you implementing it ?

**Comment by darshankawar** [comment]
@kavyabhargava 
Can you try [this](https://github.com/flutter/flutter/issues/100430) and see if it helps ?
