### ISSUE TITLE
[Fonts] Icon request: workspace_premium

### ISSUE THREAD

**Issue by paybackweb** [flutter/flutter#100460]
![2022-03-20 23_12_15-Icons - Google Fonts](https://user-images.githubusercontent.com/53094724/159200610-3aa434a3-7fb7-40a9-8b94-f8f54135ee8a.png)
Please make this icon available for flutter

**Comment by danagbemava-nc** [comment]
Hi @paybackweb, the `workspace_premium` icon already exists in flutter under the name `workspace_premium` in stable 2.10.3. The material icons site just hasn't been updated yet. Closing as the icon already exists. Thank you

<img width="200" alt="Screenshot 2022-03-21 at 07 10 18" src="https://user-images.githubusercontent.com/88313112/159217956-6c51dea8-44ae-4a5e-bf3c-1a92aaf0d8df.png">

**Comment by paybackweb** [comment]
Thanks! @danagbemava-nc
