### ISSUE TITLE
GestureDetector should take an onDoubleTapDown GestureTapDownCallback argument

### ISSUE THREAD

**Issue by collinjackson** [flutter/flutter#10048]
This will allow clients of GestureRecognizer to determine the position of the double-tap, e.g. for double-tap-to-zoom.

Originally asked in http://stackoverflow.com/questions/43937841/how-do-i-get-tap-locations-gesturedetector

**Comment by collinjackson** [comment]
@abarth

**Comment by modulovalue** [comment]
Just wanted to give my +1.
Use case:
To let the user zoom in to a specific location on a canvas with a double tap
To let the user move the canvas by X to the left or right by double tapping on either side

**Comment by csells** [comment]
You can use onTapDown to capture the position and then use it in your onDoubleTap handler.

**Comment by gschier** [comment]
@csells `onTapDown` does not get called when `onDoubleTap` is triggered.

**Comment by everoo** [comment]
The best cure I've found for this is keeping track of a bool and a point:
`onTapDown: (point){
    if (tapped && (Offset(pointA.dx, point.dx).distance<10 && Offset(pointA.dy, point.dy).distance<10)) {
        //call doubleTapWithLocation(pointA);
    } else {
        pointA = point;
        tapped = true;
    }
    Timer(Duration(milliseconds: 500), (){
        tapped = false;
    })
}`

**Comment by everoo** [comment]
`onTapDown: (pointB) {
        if (pointA != Offset.zero &&
            (pointB.globalPosition.dx - pointA.dx < 20 &&
                pointB.globalPosition.dy - pointA.dy < 20)) {
          if (_scale == 1) {
            if (imageSize.aspectRatio > this.width / this.height) {
              _scale = (imageSize.width / (imageSize.height - 15)) *
                  (this.height / this.width);
            } else {
              _scale = (imageSize.height / imageSize.width) *
                  (this.width / this.height);
            }
          } else {
            _scale = 1;
          }
          _angle = 0;
          if (_scale == 1) {
            _runAnimation(Offset.zero);
          } else {
            _runAnimation(
                Offset(pointA.dx - width / 2, pointA.dy - height / 2));
          }
        } else {
          pointA = pointB.globalPosition;
        }
        Timer(Duration(milliseconds: 500), () {
          pointA = Offset.zero;
        });
      },`

this is my zoom in and zoom out function

**Comment by haidar786** [comment]
Any update! still no 100% working solution to get double tap point location.
