### ISSUE TITLE
[Web][Integration Test] Two Chrome instances launched, and the unnecessary Chrome instance breaks the foundation of the integration test [Edited]

### ISSUE THREAD

**Issue by zpsean** [flutter/flutter#100447]
With example in https://docs.flutter.dev/cookbook/testing/integration/introduction, after executing the command:

```
flutter drive \
  --driver=test_driver/integration_test.dart \
  --target=integration_test/app_test.dart \
  -d chrome
```
One Chrome is opened. Be noticed that it is not labelled with 'chrome is controlled by automated test software'.

<img width="1200" alt="image" src="https://user-images.githubusercontent.com/14213337/159384051-84080cd6-e34c-4ff6-ad71-b074d7dadd36.png">

Then try to execute the command plus arg `--no-headless`:

```
flutter drive \
  --driver=test_driver/integration_test.dart \
  --target=integration_test/app_test.dart \
  -d chrome \
  --no-headless 
```

Two Chrome instances are launched:
- One [backend one] is launched as device [this is NOT intend for test cases execution]
- The other [frontend one] is launched via webdriver (chromedriver this case) [this is intend for test cases execution, labelled with 'chrome is controlled by automated test software']

[**Note**: Mostly, the two Chromes are overlaid, please try to drag it away (up or down), then back one would be visible.]

<img width="1641" alt="image" src="https://user-images.githubusercontent.com/14213337/159163845-67e37dfb-b21d-474d-96ee-7d4c711fa140.png">

Both Chrome instances have test executed. However, the Chrome is launched not via chromedriver has major negative impact to test:
- For js, css loading, increase the networking pressure as need to load two copies
- For some write, delete scenarios, the test will result in unexpected results (as two Chromes both will try to execute delete action)

**That is, the unnecessary Chrome instance breaks the foundation of the integration test (via flutter drive)**

  
---- Source Code Analysis: Flow the flutter drive flow ----  
- (1) 
https://github.com/flutter/flutter/blob/6af40a7004f886c8b8b87475a40107611bc5bb0a/packages/flutter_tools/lib/src/commands/drive.dart#L243-L244
https://github.com/flutter/flutter/blob/6af40a7004f886c8b8b87475a40107611bc5bb0a/packages/flutter_tools/lib/src/commands/drive.dart#L252-L259
https://github.com/flutter/flutter/blob/6af40a7004f886c8b8b87475a40107611bc5bb0a/packages/flutter_tools/lib/src/commands/drive.dart#L274-L275

- (2) 
https://github.com/flutter/flutter/blob/6af40a7004f886c8b8b87475a40107611bc5bb0a/packages/flutter_tools/lib/src/drive/web_driver_service.dart#L93

- (3) 
https://github.com/flutter/flutter/blob/6af40a7004f886c8b8b87475a40107611bc5bb0a/packages/flutter_tools/lib/src/isolated/resident_web_runner.dart#L307-L314

- (4) 
https://github.com/flutter/flutter/blob/6af40a7004f886c8b8b87475a40107611bc5bb0a/packages/flutter_tools/lib/src/web/web_device.dart#L120-L153

Per above code, it shows:
- Per (1) the --no-launch-chrome is set to true if web, but per (3)(4) it is not passed to startApp,  that is, below expression is always true 
https://github.com/flutter/flutter/blob/6af40a7004f886c8b8b87475a40107611bc5bb0a/packages/flutter_tools/lib/src/web/web_device.dart#L143
- However, even the --no-launch-chrome is passed correctly, the code will exit with error, as there exists isAppStarted check
https://github.com/flutter/flutter/blob/6af40a7004f886c8b8b87475a40107611bc5bb0a/packages/flutter_tools/lib/src/drive/web_driver_service.dart#L117-L119

**Comment by darshankawar** [comment]
@zpsean 
I tried to replicate the scenario you mentioned but don't get to see two chrome instances being launched. I see only one as expected:

<img width="1341" alt="Screenshot 2022-03-21 at 2 12 49 PM" src="https://user-images.githubusercontent.com/67046386/159228628-94972544-dc12-4b61-a8c7-142a7b57173e.png">

I am on latest stable (2.10.3) and used the steps as-is mentioned in the link you shared.

**Comment by zpsean** [comment]
@darshankawar Mostly, the two Chromes are overlaid, please try to drag it away (up or down), then back one would be visible.

I'm running on macOS, with latest stable (2.10.3). And this can be reproduced by my mates.

**Comment by darshankawar** [comment]
Thanks. I tried the same but don't see same behavior. Please confirm if the interpretation is not correct to replicate it properly:


https://user-images.githubusercontent.com/67046386/159269478-6ead6f21-048a-442e-b856-7b6c8cabb646.mov

**Comment by zpsean** [comment]
Please refer to my screen capture, as my mac may be slow, give me chance to capture them.

https://user-images.githubusercontent.com/14213337/159275630-66550576-c56e-45bc-a336-5905ec2002d8.mp4

```
% ~/Downloads/flutter/bin/flutter --version                                                                                                                                          
Flutter 2.10.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 7e9793dee1 (3 weeks ago) • 2022-03-02 11:23:12 -0600
Engine • revision bd539267b4
Tools • Dart 2.16.1 • DevTools 2.9.2
```

```
% ~/Downloads/flutter/bin/flutter doctor 
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.3, on macOS 12.0.1 21A559 darwin-x64, locale en-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] IntelliJ IDEA Community Edition (version 2021.3.2)
[✓] VS Code (version 1.64.2)
[✓] Connected device (2 available)
[✓] HTTP Host Availability
```

**Comment by zpsean** [comment]
@darshankawar 
I know the reason we got different results. Sorry, I provided the wrong command in original post, below is the one real used

`flutter drive --driver=test_driver/integration_test_driver.dart --target=integration_test/IT_test.dart -d chrome --driver-port 4444 --no-headless --profile`

More, if use below command, the Chrome opened by chromediver is in headless mode

```
flutter drive \
  --driver=test_driver/integration_test.dart \
  --target=integration_test/app_test.dart \
  -d chrome
```

**Comment by zpsean** [comment]
https://github.com/flutter/website/issues/6942 is raised against the user doc https://docs.flutter.dev/cookbook/testing/integration/introduction, to avoid the misleading.

**Comment by darshankawar** [comment]
Thanks @zpsean for providing detailed updates on the issue. I think this is an interesting find and do see the same behavior , ie, of two chrome instances being opened when running below command:

```
flutter drive \
  --driver=test_driver/integration_test.dart \
  --target=integration_test/app_test.dart \
  -d chrome \
  --no-headless 
```

<img width="1105" alt="Screenshot 2022-03-22 at 11 04 55 AM" src="https://user-images.githubusercontent.com/67046386/159414743-a0cba3d3-00b6-435a-be33-9d013cbe7aee.png">

<details>
<summary> stable, master flutter doctor -v </summary>

```

[✓] Flutter (Channel stable, 2.10.3, on macOS 12.2.1 21D62 darwin-x64, locale
    en-GB)
    • Flutter version 2.10.3 at /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (11 hours ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.


[✓] Flutter (Channel master, 2.13.0-0.0.pre.191, on macOS 12.2.1 21D62
    darwin-x64, locale en-GB)
    • Flutter version 2.13.0-0.0.pre.191 at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 69b92f0452 (3 minutes ago), 2022-03-21 21:25:09 -0700
    • Engine revision e6233bd30b
    • Dart version 2.17.0 (build 2.17.0-223.0.dev)
    • DevTools version 2.11.4

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.


```

</details>

**Comment by jiahaog** [comment]
Apologies, I'm not familiar with this, @yjbanov would you know more?

**Comment by zpsean** [comment]
@darshankawar @yjbanov, any further comments on this?

**Comment by yjbanov** [comment]
This is a duplicate of https://github.com/flutter/flutter/issues/67090

**Comment by zpsean** [comment]
@yjbanov @darshankawar this key point of this issue i want to address is that expecting the Chrome (as device) is not to be opened. In #67090, it is stated as harmless but confusing, but I think, as stated in original post, is harmful, as we can Not reply on the real test results with the Chrome existence (device one). 

----
Both Chrome instances have test executed. However, the Chrome is launched not via chromedriver has major negative impact to test:

For js, css loading, increase the networking pressure as need to load two copies
For some write, delete scenarios, the test will result in unexpected results (as two Chromes both will try to execute delete action)

**Comment by zpsean** [comment]
We can have more discussion how two use option -d and --browser-name, maybe to prevent the Chrome (as device) to be opened have high priority with its impact (negative) to test .
