### ISSUE TITLE
Desktop | Scaffold : Ability to open both Left & Right Drawer without the other closing

### ISSUE THREAD

**Issue by kthecoder** [flutter/flutter#100488]
## Use case

Drawer is exactly what I need but I am having trouble finding a solution to using two on desktop. 

Calling:

```
Scaffold.of(context).openDrawer();
Scaffold.of(context).openEndDrawer();
```

Closes the other Drawer. Which of course is advantageous on mobile but on desktop I have the space to open two.

Is there a way tell the scaffold to open each without using `.openDrawer()`?

## Proposal

![Two Drawers](https://imgur.com/a/bRi2H1Q) : https://imgur.com/a/bRi2H1Q

Ability to open two Drawers.

```
class ScaffoldState extends State {

  void openDrawers() {
    if (_endDrawerKey.currentState != null && _drawerKey.currentState != null)
    _endDrawerKey.currentState?.open();
    _drawerKey.currentState?.open();
  }
```

**Comment by maheshmnj** [comment]
Hi @kthecoder, Thanks for filing the issue. I wonder if that would be possible or if it is right for your use case. Becasue Drawers are basically an overly on top of the Current Widget. As per the current implementation when opening a second drawer first is closed

https://github.com/flutter/flutter/blob/b8f0dde0f8d181630a1a0b0867f3a01404d52821/packages/flutter/lib/src/material/scaffold.dart#L2012-L2016


But even if you manage to launch two drawers simultaneously, You will end up with output that looks like this,  

<img width="1312" alt="Screenshot 2022-03-22 at 1 15 27 PM" src="https://user-images.githubusercontent.com/31410839/159432509-9b3c7c2c-6831-487c-8ecd-aec890fed24d.png">

 Where you will be able to interact with one drawer at a time.
