### ISSUE TITLE
"FileSystemException: Failed to set file modification time, path = '/home/zhl/ai_listener/.packages' (OS Error: Operation not permitted, errno = 1)

### ISSUE THREAD

**Issue by henry892** [flutter/flutter#100440]
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by ryzizub** [comment]
@henry892 Can you please add the steps to reproduce this or at least a brief description of where you encountered such an error?

It looks like you are writing to a directory that the application does not have write access to. Have you tried writing to the temp directory?

**Comment by henry892** [comment]
I  am trying to build a flutter project for Adriod APP.  The environment is Ubuntu 20.04.4 LTS. I have tried to set "chmod 777" for all files. But it does not work.

**Comment by henry892** [comment]
zhl@DESKTOP-6APV0OP:~/ai_listener$ ../flutter_v1/flutter/bin/flutter  pub get
Running "flutter pub get" in ai_listener...                         0.5s

Failed to send crash report due to a network error: SocketException: OS Error: Connection timed out, errno = 110,
address = clients2.google.com, port = 59818
Oops; flutter has exited unexpectedly: "FileSystemException: Failed to set file modification time, path =
'/home/zhl/ai_listener/.packages' (OS Error: Operation not permitted, errno = 1)".
A crash report has been written to /home/zhl/ai_listener/flutter_08.log.

**Comment by danagbemava-nc** [comment]
Hi @henry892, please provide the content of `/home/zhl/ai_listener/flutter_08.log` as well as your `flutter doctor -v`. 

Thank you
