### ISSUE TITLE
Which one is the default on Android: "Virtual Displays" or "Hybrid Composition"?

### ISSUE THREAD

**Issue by noahabe** [flutter/flutter#100407]
[Here](https://codelabs.developers.google.com/codelabs/flutter-webview#:~:text=On%20Android%20you%20have%20a%20choice%20between%20Virtual%20Displays%2C%20currently%20the%20default%20for%20Android%2C%20and%20Hybrid%20composition) it says Virtual Displays is the default for android. 

But [here](https://pub.dev/packages/webview_flutter#:~:text=hybrid%20composition%20(the%20current%20default)) it says hybrid composition is the default.

**Comment by darshankawar** [comment]
@noahabe 
If you are using `webview_flutter` plugin, the hybrid composition is the default as mentioned in the plugin's readMe.

In the codelab link, I don't see anywhere that it mentions virtual display as default ? https://codelabs.developers.google.com/codelabs/flutter-webview#0

But the answer to your question is, `hybrid composition` is the default for Android. See this: https://pub.dev/packages/webview_flutter/changelog#300

Closing as your question is answered. Regarding the codelab link you shared where it shows virtual display as default, please use `report a mistake` button from the link and open new issue.
