### ISSUE TITLE
Re-enable non-network video demos in flutter_gallery__transition_perf

### ISSUE THREAD

**Issue by jason-simmons** [flutter/flutter#100497]
The `flutter/staging/Mac_ios flutter_gallery__transition_perf_e2e_ios` builder has been failing repeatedly when trying to play video:

```
PlatformException(VideoError, Failed to load video: The certificate for this server is invalid., null, null)

02:11 +0 ~1: flutter gallery transitions on e2e all demos [E]
   Test failed. See exception logs above.
```

Example: https://ci.chromium.org/ui/p/flutter/builders/staging/Mac_ios%20flutter_gallery__transition_perf_e2e_ios/1578/overview

**Comment by zanderso** [comment]
@stuartmorgan Do you happen to know what this message from the video player plugin in the flutter gallery might indicate?

**Comment by stuartmorgan** [comment]
Assuming it's this:
https://github.com/flutter/flutter/blob/840e109e0718361f70bcb23a3980e407de10859b/dev/integration_tests/flutter_gallery/lib/demo/video_demo.dart#L370
(that's the only `VideoPlayerController` I'm finding in flutter/flutter) it seems like either some kind of network failure causing the cert validation to fail, or maybe a test machine with really old root certs?

Do we actually need a *network* video test in the gallery? Unless for some reason we really want to test that in flutter/flutter (seems unlikely), restricting the gallery to just assets seems like an easy way to avoid one possible source of test flake.

**Comment by zanderso** [comment]
I think it isn't unreasonable to have in a demo app, but we should remove the network access from CI until it can be refactored https://github.com/flutter/flutter/pull/100666.

**Comment by ditman** [comment]
In order to reenable this demo in the web, Chromium can't play mp4 files, but it *can* play webm files. See this:

* https://github.com/flutter/plugins/commit/f3b5740f867d12a87458fb6227d867f8ab6bc60c
* Or the OG change: https://github.com/flutter/plugins/commit/cb381ced070d356799dddf24aca38ce0579d3d7b#diff-a06c0e302b7fa58d49706f881b36de105fb070c94a7af2aca9707b04530f527b

**Comment by keyonghan** [comment]
The test has been passing for recent 100 commits. shall we close?

**Comment by zanderso** [comment]
We can repurpose this issue to track re-enabling the skipped part of the benchmark.

**Comment by ricardoamador** [comment]
If this is skipping part of the test then this should not be an infra issue. Removed the infra label.

**Comment by ditman** [comment]
These seem to be the problematic videos:

* https://github.com/flutter/flutter/blob/main/dev/integration_tests/flutter_gallery/lib/demo/video_demo.dart#L363-L375

**Comment by Hixie** [comment]
@zanderso I'm assigning this to you since you originally skipped the test, but please don't hesitate to assign it to a specific team if that 's more appropriate (I don't have the context to know where the change would need to be made).

**Comment by ditman** [comment]
Note that @eyebrowsoffire recently changed some of our infra to use "Chrome for Testing" rather than the Chromium builds that we used before (https://github.com/flutter/engine/pull/46683).

This might be a matter of re-enabling the tests without any changes (ensuring that they run on the new browser).

**Comment by zanderso** [comment]
Based on @ditman's comment, routing to `team-web` for triage.

**Comment by yjbanov** [comment]
This is a benchmark, but on the web we let the browser play the video in a `<video>` tag. Are we interested in benchmarking the browser's ability to play video? Not sure what signal we're looking for.
