### ISSUE TITLE
add the ability to take a screenshot from the flutter tool

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter#1004]
Is something like `flutter screenshot` in scope? I've needed to take a screenshot of the running app a few times, and always had to google how to do it with adb (`adb screencap` and then some file copying).

`flutter pic`? `flutter capture`?

Related to https://github.com/dart-atom/dartlang/issues/659.

**Comment by sethladd** [comment]
Thanks!

**Comment by nicolasvac** [comment]
Is this available ?
