### ISSUE TITLE
Flutter DevTools  cpu profile show time consuming data error

### ISSUE THREAD

**Issue by cj3479** [flutter/flutter#100422]
Hi
   When flutter DevTools cpu profile, I found the time cost statistics error，the below is my screenshot
   
   
this is my code statistics time cost

<img width="777" alt="image" src="https://user-images.githubusercontent.com/9412601/159132994-b50d56d8-1e47-48eb-9a96-c1afb2bf2073.png">
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/9412601/159132981-ac2d12e8-2817-404d-a20b-1b9a26e1b01b.png">

 It Actually costs  **798ms**
ps: I when use timeline, the cost time is also **798ms**

this is flutter DeTools cpu profile statistics time cost
<img width="1825" alt="image" src="https://user-images.githubusercontent.com/9412601/159132814-2a666bfa-4b9d-42ac-bc53-66bbc1518249.png">
 The  cpu profile show  costs  **4245ms**

The diff is very huge

The error is obvious, All  method  time cost  showing in cpu profile is  much bigger than  actual time cost 

</br>
</br>
BTW When I use sleep to monitor time-consuming operation, the cpu profile can not detected it.
This is my code
<img width="790" alt="image" src="https://user-images.githubusercontent.com/9412601/159133668-9bff2ade-1bdf-4f7a-ad3d-55f2b209473c.png">

</br>
</br>
</br>
flutter  --version
<img width="851" alt="image" src="https://user-images.githubusercontent.com/9412601/159133338-9877bb94-9671-4625-9a20-5bdc1456749b.png">
</br>
</br>
flutter doctor 

<img width="1172" alt="image" src="https://user-images.githubusercontent.com/9412601/159133361-c64c8482-36f6-4edb-b249-e54a682ac71e.png">

**Comment by maheshmnj** [comment]
Hi @cj3479, Thanks for filing the issue. Please try upgrading to latest `stable 2.10.3` by running `flutter upgrade` and see if that helps fix the issue. If the issue persists please share a minimal and complete reproducible code sample.

Thanks
