### ISSUE TITLE
TextField not getting onSubmitted callback - Flutter Web

### ISSUE THREAD

**Issue by jtmcdole** [flutter/flutter#100435]
TextField not getting submitted on Android Chrome.  Works just fine on Desktop chrome (though no OS keyboard) and Android native.

### Setup
Add a single TextField with an `onSubmit`:

```
 TextField(
              controller: controller,
              autocorrect: false,
              enableSuggestions: false,
              maxLength: 5,
              autofocus: false,
              textInputAction: TextInputAction.search,
              onSubmitted: (String text) {
                setState(() {
  /// do stuff with `text`!
```

### Expected
When hitting "enter" on the keyboard, the keyboard is dismissed and the input fed to `onSubmitted`.

### Actual
* Keyboard remains
* `onSubmitted` never called
* "suggestions" above input flicker

### Horrible work around
Click on the first suggestion; then click enter. This produces the desired outcome.

<details>
<summary>  flutter doctor </summary>

```
[√] Flutter (Channel master, 2.10.0-1.0.pre.307, on Microsoft Windows [Version 10.0.19044.1586], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.2)  
[√] Android Studio (version 2020.3)
[√] VS Code (version 1.65.2)
[√] Connected device (4 available)
[√] HTTP Host Availability        

• No issues found!
```
</details>

**Comment by danagbemava-nc** [comment]
Hi @jtmcdole, there's a similar issue already open describing what you're experiencing in https://github.com/flutter/flutter/issues/89384. Kindly follow up there for updates. 

Closing from here as duplicate. 

Thank you
