### ISSUE TITLE
platform channel example: should setState only fire if invokeMethod doesn't fail?

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#10041]
Just curious, for https://github.com/flutter/flutter/blob/master/examples/platform_channel/lib/main.dart#L32, should setState be inside the try block?

If the invokeMethod fails, do we want to or need to call setState regardless?

**Comment by sethladd** [comment]
cc @mravn-google

**Comment by Hixie** [comment]
The way the code is currently written makes the message show an error when there's an error, which seems valuable.

**Comment by sethladd** [comment]
Fair enough.
