### ISSUE TITLE
[url_launcher] Lauching an IP Address in a web app adds hostname to the url

### ISSUE THREAD

**Issue by kadhikari24** [flutter/flutter#100461]
I am using the url_launcher library to open the new link in the flutter application. I noticed that when I try to open the IP Address in a new tab, it is automatically adding the hostname in front.

Example: I am trying to launch an IP  address like 0.0.0.0 using the url_laucher. I checked the URL of the lanched link which is getting converted into something link this "http.example.0.0.0.0". This is not what I expected. It should have launch the IP address.

**Comment by maheshmnj** [comment]
Hi @kadhikari24, Thanks for filing the issue. Does adding http(s) beforethe ipadddress launch the correct URL?
