### ISSUE TITLE
API docs should be over at api.flutter.io (or "api" should redirect to "docs")

### ISSUE THREAD

**Issue by jhirth** [flutter/flutter#10040]
The Dart website also uses "api" as subdomain:

https://api.dartlang.org/

For the sake of consistency, I'd prefer if "api" would be real one and "docs" redirects, but doing it the other way around would also work.

**Comment by sethladd** [comment]
Thanks for the feedback. We're unlikely to change this domain name at this point, unfortunately.

**Comment by jhirth** [comment]
"api" could still redirect to "docs", though.

**Comment by Hixie** [comment]
I think it would make sense to add a redirect, for people who just instinctively type "api.flutter.io".

**Comment by sethladd** [comment]
How many people will type that, by hand? Don't most people find things by search?

There's a non-trivial cost to maintaining domain names and redirects, and canonical links. It's not crazy expensive, but not sure it's worth the cost.

**Comment by Hixie** [comment]
I always type in the URL, FWIW. I would imagine that someone who is used to the dartdocs URL would type in the equivalent URL for us and be sad that it doesn't work. But I trust your judgement on whether it's worth it.

**Comment by jhirth** [comment]
I filed this because I tried to auto-complete the docs URL by typing "api." but that didn't work. I was kinda baffled since I was on the docs page just a few hours earlier.

When I revisited the homepage, I was surprised that it's actually "docs.".

I generally jump to my frequently used websites by auto-completing their URLs.

**Comment by Hixie** [comment]
Let's close this and see if anyone else hits the same problem, and if they do, we'll reconsider.

**Comment by jcollins-g** [comment]
I've actually done this myself a few times, primarily because api.dartlang.org gets you to the API for Dart.
