### ISSUE TITLE
Switch layers to DlImageFiter, DlColorFilter, and DlColorSource objects

### ISSUE THREAD

**Issue by flar** [flutter/flutter#100454]
The DisplayList code recently created inspectable local objects to replace its use of SkImageFilter, SkColorFilter, and SkShader objects. The engine layers that use those Skia objects should also switch to using the Dl versions to enable some optimizations such as removing saveLayer objects for things like a matrix transform image filter on a compatible group of children, etc.

**Comment by JsouLiang** [comment]
ColorFilterLayer use DlColorFilter: https://github.com/flutter/engine/pull/34744

**Comment by JsouLiang** [comment]
ImageFilterLayer use DlImageFilter: https://github.com/flutter/engine/pull/34837
