### ISSUE TITLE
Allow removing all listeners from a ChangeNotifier

### ISSUE THREAD

**Issue by Fnalsk** [flutter/flutter#100596]
## Use case
Want a way to remove all listeners from a ChangeNotifier. Currently the only way to do this is to remember all listeners you have previously added and remove them one by one. This is especially annoying if one or more listeners you added previously depends on some variable that was provided from elsewhere - in this case, the listener that's added depends on the value of that variable and thus the developer has to know exactly what that value was or the listener is unremovable.

## Proposal
Add a function `removeAllListeners` to `ChangeNotifier` that is just equivalent to calling `removeListener` on every previously added listener.

**Comment by danagbemava-nc** [comment]
Hi @Fnalsk, kindly see https://github.com/flutter/flutter/issues/52404 and the comment in  https://github.com/flutter/flutter/issues/52404#issuecomment-597912018 for a discussion on why this hasn't been added. 

I'm going to close this issue for now. If you disagree with the conversation linked, kindly leave a comment below with your objection and I will reopen this. 

Thank you

**Comment by maheshmnj** [comment]
Also, as per the [docs](https://api.flutter.dev/flutter/foundation/ChangeNotifier/addListener.html). It looks like it is not possible to determine which listener is being removed

> If a listener is added twice, and is removed once during an iteration (e.g. in response to a notification), it will still be called again. If, on the other hand, it is removed as many times as it was registered, then it will no longer be called. This odd behavior is the result of the [ChangeNotifier](https://api.flutter.dev/flutter/foundation/ChangeNotifier-class.html) not being able to determine which listener is being removed, since they are identical, therefore it will conservatively still call all the listeners when it knows that any are still registered.
