### ISSUE TITLE
[video_player_android] surface view artifacts  

### ISSUE THREAD

**Issue by SiarheiSm** [flutter/flutter#100543]
Hi, I've tried to use video_player_android 2.3.1 with custom url (just hordcoded in android_video_player.dart) and noticed some videos have artifacts (vertical green line). No such issues in case I use just exoplayer app. Seems appears only for flutter surface view and for vertical videos only.
for example issue appears with this url: https://20minfeedcachefast.streamboatserver.ch/now/nowteaser.m3u8 
here how it looks like: 
<img width="222" alt="image" src="https://user-images.githubusercontent.com/24812695/159444740-1bbe465d-aad3-4a45-bfad-43a1b7a70d14.png">

**Comment by SiarheiSm** [comment]
reproducible on pixel 5 api 29

**Comment by maheshmnj** [comment]
Hi @SiarheiSm, Thanks for filing the issue.

Hi @,

There is a similar issue describing this case https://github.com/flutter/flutter/issues/34642 and https://github.com/flutter/flutter/issues/46628, Please follow up there for further updates, Closing this issue as a duplicate. If you disagree feel free to write in the comments and we will reopen it.

Thank you.
