### ISSUE TITLE
[windows] File Description

### ISSUE THREAD

**Issue by mbfakourii** [flutter/flutter#100569]
Hi there,

how cheng File Description in windows ?

![159434065-b95b3e7d-f9d7-46ea-8c34-e7f84588bc8e](https://user-images.githubusercontent.com/20955005/159537884-3486615f-ed50-4303-9e1d-4c741ab3ee89.png)

i try change File Description in windows\runner\Runner.rc but hot restart has error !

**Comment by darshankawar** [comment]
@mbfakourii 
Check [this](https://stackoverflow.com/questions/65733963/change-taskbar-name-of-flutter-app-on-windows) similar issue and underlying solution to see if it helps.

Also, this question is better suited for support channels, so if linked solution doesn't work for you, please create a new question there.
Closing from here.
