### ISSUE TITLE
Revert pub dependencies artifact to universal

### ISSUE THREAD

**Issue by Jasguerrero** [flutter/flutter#100530]
### issue_link

https://github.com/flutter/flutter/issues/100350#issuecomment-1074434539

### Commit Hash

50f3e47

### Impacted Users

Flutter devs

### Impact Description

Flutter cli commands (so far just found with "test" but it could impact more than this one) when a user download the flutter sdk 

### Workaround

Build the flutter tool before running any commands (users that downloaded the sdk)

### Risk

medium

### Test Coverage

yes

### Validation Steps

https://github.com/flutter/flutter/pull/100508#event-6280132871

**Comment by itsjustkevin** [comment]
Merged into beta.
