### ISSUE TITLE
Unify plugin names

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#10052]
https://github.com/flutter/plugins/tree/master/packages

Some use names-with-hyphens, others use underscore_style. We should probably unify. I think the we should go with underscore_style because that's what the dart style guide recommends as naming schema for dart packages (this style is also now enforced by `flutter create`.

Plugins to rename:
- [ ] path-provider
- [ ] shared-preferences
- [ ] url-launcher

/cc @collinjackson @mit-mit

**Comment by mit-mit** [comment]
The package names already use underscores, so looks like it's just the folders for the above three that we need to update
