### ISSUE TITLE
[infra] On post-submit, deploy copybara configs

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#100507]
The process is manual, and cause breakages to the copybara workflows while they're out of sync. Additionally, it requires admin privileges which most engineers do not have

**Comment by CaseyHillers** [comment]
\cc @yusuf-goog

**Comment by CaseyHillers** [comment]
This just broke the engine. A commit landed while the workflow was broken, and the builds failed to checkout from the mirror. https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20Android%20Debug%20Engine/14463/overview

**Comment by godofredoc** [comment]
Who is looking at this issue? We are integrating infra P1 and P2s into the critical triage process and we need all the P1s and P2s to be assigned to someone.

**Comment by godofredoc** [comment]
Additionally after the revert of the copybara configs do we need to rerun the update commands?

**Comment by CaseyHillers** [comment]
After the cl revert, we didn't need the update.

I'll take a look and see what the copybara team has to offer for deploying these configs on postsubmit

**Comment by CaseyHillers** [comment]
After investigating, there's no clear path forward. This requires GitHub admin privileges, and this isn't something we want to give to the copybara config.

Instead, I updated some docs to point out a GitHub admin should be added to the internal CLs for the config
