### ISSUE TITLE
google_sign_in tests are failing

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#10050]
https://travis-ci.org/flutter/plugins/jobs/231686941

Fix is probably simple.

**Comment by ajonp** [comment]
Can anyone run the example google_sign_in?
I get I/flutter (26386): PlatformException(canceled, 0, null)

after coming back from selecting my account, in the code just past
Map<String, dynamic> response = await _channel.invokeMethod(method);

**Comment by goderbauer** [comment]
@ajonp in order to run the example successfully on android, you need to make sure it's registered properly as described in the "[Android Integration](https://github.com/flutter/plugins/tree/master/packages/google_sign_in#android-integration)" section of the readme. Did you do that for the example app? If it's still not working after that, please open a new issue as it is unrelated to the test failures this issue is about.

**Comment by ajonp** [comment]
@goderbauer thanks, I actually had the package name incorrect on my console.
I believe I have updated the tests correctly, along with allowing for actual disconnect/signoff to work. [718bd057a8392134e58ff57686b128e755d537ad](https://github.com/ajonp/plugins/commit/718bd057a8392134e58ff57686b128e755d537ad)

I am new to adding to projects...so I hope this works okay.

**Comment by mit-mit** [comment]
@goderbauer is this passing now, or just marked as a known failure?

**Comment by goderbauer** [comment]
The checked-in version is marked as failing (tests are skipped). There is a PR out that supposedly fixes the tests: https://github.com/flutter/plugins/pull/82.

**Comment by sadilek** [comment]
I didn't see flutter/plugins#82 and sent flutter/plugins#93, which I think solves this a bit nicer.
