### ISSUE TITLE
[autosubmit] SecretManager issue when testing checkPullRequest handler

### ISSUE THREAD

**Issue by KristinBi** [flutter/flutter#100502]
when I sent a curl get to test for the checkPullRequest handler, I encountered the 403 issue. Here attached is the detailed issue description.
<img width="1350" alt="Screen Shot 2022-03-21 at 4 21 41 PM" src="https://user-images.githubusercontent.com/98613535/159378805-d6f5e5a7-81dc-414b-8e4c-83e5555d2f1e.png">

From the logs, I think the server successfully received the request and our handler successfully decoded the pr information from the request body, but failed to create the github client without the permission.

**Comment by CaseyHillers** [comment]
I updated the service account to have cloud secret access. @KristinBi can you try again?

**Comment by CaseyHillers** [comment]
The service account was the issue. @KristinBi also added a base64 decode into the secret manager
