### ISSUE TITLE
Slider class accepts identical values for value, min and max, but crashes at rendering.

### ISSUE THREAD

**Issue by paolosoares** [flutter/flutter#10055]
## Steps to Reproduce

Create a widget with this slider:

`new Slider(value: 0.0, min: 0.0, max: 0.0, onChange: (v) {});`

You should see an assertion error about "value" being invalid. In this case, "value" turns out the be NaN.

## Possible cause

This happens because of a [division by zero at slider.dart](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/slider.dart#L164), when `min == max`: 

```
return new _SliderRenderObjectWidget(
      value: (widget.value - widget.min) / (widget.max - widget.min),
      /* ... */
    );
```

**Comment by Hixie** [comment]
Yeah we should assert that the range is non-zero, or maybe support a zero range but disable the slider in that case.

**Comment by abarth** [comment]
We probably want to support it in case folks animate to this state.
