### ISSUE TITLE
Document on flutter's wiki the versioning schema for releases

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#100565]
Flutter is working on following the OSSF best practices and some of those best practices are related to documentation of releases. Even though the information exists it is already spread on multiple places and not easy to find by someone new to the flutter community.

![image](https://user-images.githubusercontent.com/54371434/159527683-e4fee4cb-21e3-40b9-9ec8-191de077e915.png)

**Comment by godofredoc** [comment]
\cc @Hixie @itsjustkevin do you know if we have our release versioning schema documented somewhere?

**Comment by itsjustkevin** [comment]
@godofredoc there is an [issue](https://github.com/flutter/flutter/issues/96282) open on a proposal to change the versioning schema.

**Comment by maheshmnj** [comment]
Closing this issue in favor of https://github.com/flutter/flutter/issues/96282
