### ISSUE TITLE
[plugins] release action sometimes getting incorrect results for tests

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#100557]
<img width="902" alt="Screen Shot 2022-03-21 at 6 19 03 PM" src="https://user-images.githubusercontent.com/1255594/159388469-f74d22d2-6ef6-418f-a27d-3e8b5f2f961f.png">

The latest push to `main` seems to have been released with a failing **android-platform_tests CHANNEL:master PLUGIN_SHARDING:--shardIndex 4 --shardCount 5** check?

Looking here:

* https://github.com/flutter/plugins/runs/5635866276?check_suite_focus=true#step:6:186

It seems that a test that failed according to the Github UI:

* https://github.com/flutter/plugins/runs/5635866813

But it was picked up as `completed (success)` by the wait action?

_Originally posted by @ditman in https://github.com/flutter/flutter/issues/88120#issuecomment-1074589618_

**Comment by stuartmorgan** [comment]
I've seen this happen a couple of times too, and both times it showed as `(success)` in the `release` check. Possibilities I can think of:
- For some reason the test was re-run, and failed the second time? I can't think of a reason that would happen though
- GitHub's API sometimes returns incorrect status?
- It's somehow referencing the wrong run of that test (e.g., one for a different commit)?

**Comment by ditman** [comment]
@stuartmorgan you're gonna love this: https://github.com/flutter/flutter/issues/102801

**Comment by ditman** [comment]
I'm going to close this as fixed by:

* https://github.com/flutter/plugins/pull/5444
* https://github.com/flutter/packages/pull/1663
* https://github.com/flutter/engine/pull/33010
