### ISSUE TITLE
The icons displayed by the emulator and the physical device are different from those defined in the code

### ISSUE THREAD

**Issue by albertoOviedo** [flutter/flutter#100503]
After updating flutter, the icons displayed both on the emulator and on the physical device are different from those defined in the code. Icons are of type IconData.

For example:

If you see in the image, in the code it defines the icon stars_outlined, but the emulator and the physical device show me a different icon. What can I do to make it display the icons defined in the code?

![flutter](https://user-images.githubusercontent.com/102108890/159377601-1ccd1f8c-ff4b-4b11-bdd9-30a1406608cb.png)

**Comment by danagbemava-nc** [comment]
Hi @albertoOviedo,

Can you please provide your `flutter doctor -v`  and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?

Thank you

**Comment by albertoOviedo** [comment]
Hi @danagbemava-nc,

Thanks for answering my message.

My flutter doctor -v:

flutter doctor -v
[√] Flutter (Channel stable, 2.10.3, on Microsoft Windows [VersiÃ³n 10.0.19042.1586], locale es-CO)
    • Flutter version 2.10.3 at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (3 weeks ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\ASUS\AppData\Local\Android\sdk
    • Platform android-31, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.10)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.32126.315
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 4.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] VS Code (version 1.65.2)
    • VS Code at C:\Users\ASUS\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.36.0

[√] Connected device (4 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)           • windows       • windows-x64    • Microsoft Windows [VersiÃ³n
      10.0.19042.1586]
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 99.0.4844.74
    • Edge (web)                  • edge          • web-javascript • Microsoft Edge 99.0.1150.39

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Comment by danagbemava-nc** [comment]
Hi @albertoOviedo, please provide a complete minimal reproducible code sample. In the screenshot you have shared, I do not know which of the icons the `star_outlined` is supposed to be.

**Comment by albertoOviedo** [comment]
Hi [@danagbemava-nc](https://github.com/danagbemava-nc),

Before everything was working fine, but after updating the flutter version all the app icons stopped working.

I have created a new application because I thought it could be a code error, but the same thing happens in any app.

--

Code:

import 'package:flutter/material.dart';

import 'package:charter/user/ui/widgets/app_bar.dart';
import 'package:charter/user/ui/widgets/lateral_nav.dart';
import 'package:charter/travel_service/widgets/banner_image.dart';
import 'package:charter/user/ui/widgets/card_image_list_horizontal.dart';
import 'package:charter/travel_service/widgets/horizontal_underline_listview_bulder.dart';


class DetalleAtractivo extends StatefulWidget {
  const DetalleAtractivo({Key? key}) : super(key: key);

  @override
  State<DetalleAtractivo> createState() => _DetalleAtractivoState();
}

class _DetalleAtractivoState extends State<DetalleAtractivo> {


  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: const PreferredSize(
        child: AppBarSearch('Buscar Atractivo Turístico'),
        preferredSize: Size.fromHeight(50),
      ),
      drawer: const LateralNav(),
      body: SingleChildScrollView(
        child: Column(
          children: const <Widget>[
          SizedBox(height: 20.0,),
          BannerImage(
            Icons.stars_outlined,
            "XXXXXXXXXXXXXXXX", 
            "assets/img/slide1.jpg",
            true,
            true
          ),
          HorizontalUnderlineMenuList(),
          CardImageList(
            titleImageList: "Atractivos cercanos", 
            icon: Icons.star, 
            fontSize: 30.0, 
            isEnableSeeAll: false)
        ],
        )
      ),
    );
  }
}

---
I bring the icon from an iconText variable of type IconData in a StatefulWidget BannerImage
---

import 'package:flutter/material.dart';

import 'package:charter/config/palette.dart';


/* IMAGEN COMO BANNER SIN ANIMACIÓN CON TÍTULO */

class BannerImage extends StatefulWidget {

  final IconData iconText;
  final String textBanner;
  final String routeImageBanner;
  final bool isEnableLike;
  final bool isEnableShare;
  const BannerImage(
    this.iconText, 
    this.textBanner, 
    this.routeImageBanner,
    this.isEnableLike,
    this.isEnableShare,
    {Key? key}) : super(key: key);

  @override
  State<BannerImage> createState() => _BannerImageState();
}

class _BannerImageState extends State<BannerImage> {

  @override
  Widget build(BuildContext context) {
    return Container(
          alignment: Alignment.bottomCenter,
          padding: const EdgeInsets.only(bottom: 0.0),
          height: 250.0,
          decoration: BoxDecoration(
            image: DecorationImage(
              image: AssetImage(widget.routeImageBanner),
              fit: BoxFit.cover
              )
          ), 
          child: Container(
            height: 50.0,
            padding: const EdgeInsets.only(bottom: 5.0, left: 5.0),
            alignment: Alignment.bottomCenter,
            decoration: BoxDecoration(
              color: Palette.darkred.withOpacity(0.5)
            ),
            child: Row(
                mainAxisAlignment: MainAxisAlignment.start,
                children: <Widget>[
                  Container(
                    margin: const EdgeInsets.only(top: 5.0),
                    width: (MediaQuery.of(context).size.width)/2,
                    child: Row(
                      children: <Widget>[
                        // ICONO
                        Icon(
                          widget.iconText,
                          size: 25.0,
                          color: Palette.white,
                        ),
                          Text(
                            widget.textBanner,
                            style: const TextStyle(
                              color: Palette.white,
                              fontFamily: "PrincipalFont",
                              fontSize: 33.0
                            ),
                          ),
                      ]
                    ),
                  ),
                  Container(
                    width: (MediaQuery.of(context).size.width)/2.3,
                    margin: const EdgeInsets.only(right: 5.0),
                    child: Row(
                      mainAxisAlignment: MainAxisAlignment.end,
                      children: <Widget>[
                        if(widget.isEnableLike)
                      GestureDetector(
                        child: const Icon(
                          Icons.favorite_border,
                          size: 30.0,
                          color: Palette.white,
                        ),
                        onTap: (){
                          debugPrint("Presionaste Like");
                        },
                      ),
                    if(widget.isEnableShare)
                      GestureDetector(
                        child: const Icon(
                          Icons.share,
                          size: 30.0,
                          color: Palette.white,
                        ),
                        onTap: (){
                          debugPrint("Presionaste Share");
                        },
                      ) 
                      ],                  
                    ),
                  ),                               
                ],
              ),
          ),            
        );
  }
}


Thanks for your help :)

**Comment by danagbemava-nc** [comment]
Hi @albertoOviedo, I tried out your code sample, and the icons rendered just fine for me. See screenshots below. I had to make some small adjustments so I could get the code running but those adjustments don't have any impact on how the icons are rendered. 

What version of flutter did you upgrade from?

<details>
<summary>screenshots</summary>

| ios | android |
| -- | -- |
| <img src="https://user-images.githubusercontent.com/88313112/159855553-d08ba6e9-7f32-4ea5-8580-7b0ac2bca5e9.png" /> | <img src="https://user-images.githubusercontent.com/88313112/159855867-68a197fa-0633-4357-bdcd-51a6daee827f.png" /> |

</details>

**Comment by albertoOviedo** [comment]
Hi @danagbemava-nc ,

Updated from version 2.10.2.

I just updated flutter to version 2.10.4 and I still have the same problem.

Thanks for your help.

**Comment by danagbemava-nc** [comment]
Hi @albertoOviedo, can you try creating the default flutter app and adding the icons to see if you still experience this issue?

**Comment by albertoOviedo** [comment]
Hi @danagbemava-nc ,

Yes, when creating the Flutter application the problem continued.
![IconFlutter](https://user-images.githubusercontent.com/102108890/160941774-ba9c2bda-36ce-4d3e-b8fc-bd5401a473f2.png)

**Comment by albertoOviedo** [comment]
Hi @danagbemava-nc .

With material design icons it doesn't work. But when I use another library like CupertinoIcons, it works.
![iconsMAterial](https://user-images.githubusercontent.com/102108890/161085254-1d345d9c-47a7-4967-a1be-fd484347c121.png)
![IconsCupertino](https://user-images.githubusercontent.com/102108890/161085288-3c28a015-7666-465a-8cdb-a366fdbe2df5.png)

**Comment by danagbemava-nc** [comment]
Hi @albertoOviedo, can you switch to either the `beta` or `master` channels to see if you still experience this issue? 

You can switch by running the following commands: 

```
flutter channel beta/master
flutter upgrade --force
```

Kindly let me know if this is resolved or not after switching to either channel. 

Thank you

**Comment by albertoOviedo** [comment]
I am very grateful to you. :)

It finally worked for me. 👍

**Comment by danagbemava-nc** [comment]
Glad that helped. 

Closing as solved. 

Thank you
