### ISSUE TITLE
[Fonts] Icon request: edit_calendar

### ISSUE THREAD

**Issue by Pooja289318** [flutter/flutter#100562]
[io.material](https://fonts.google.com/icons)

**Comment by maheshmnj** [comment]
Hi @Pooja289318, Thanks for filing the issue. The requested icon is already present in the latest stable release of flutter.

<img width="350" alt="image" src="https://user-images.githubusercontent.com/31410839/159640060-a223efc1-330d-46eb-9dfc-1a28ea80dfff.png">

```
Flutter 2.10.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 7e9793dee1 (3 weeks ago) • 2022-03-02 11:23:12 -0600
Engine • revision bd539267b4
Tools • Dart 2.16.1 • DevTools 2.9.2
```
  
Closing, as the icon is already present. In case you disagree feel free to write in the comments and we will reopen it.

Thank you.
