### ISSUE TITLE
[Regression]: Scrolling through the list shows spike in performance on latest beta and master.

### ISSUE THREAD

**Issue by b3nni97** [flutter/flutter#100523]
Hi,

Since the 2.11.0-0.1.pre tag, there are major performance issues with our app. 
With version 2.10.1 everything runs smoothly and very performant. 
This problem also exists on the master branch. 

I unfortunately haven't had the time to find out exactly the commit that caused this regression.

Example app:

```
class TestApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return CupertinoApp(
      showPerformanceOverlay: true,
      home: ListView.builder(
        itemBuilder: (context, index) {
          return Text(
            '$index index $index index $index index',
            style: CupertinoTheme.of(context).textTheme.textStyle,
          );
        },
      ),
    );
  }
}

```

Before regression (2.10.1):
https://drive.google.com/file/d/1OIkf6CGloWMy563W6Hqut4gxQP331x_G/view?usp=sharing

After regression (2.11.0-0.1-pre):
https://drive.google.com/file/d/1s6uJuZ3hzIhWT1mph-mwnDP3ztbiJXeP/view?usp=sharing

As you can see from the video, this is not a small regression but causes the app to stop running smoothly at all once you use some text in your widgets.

**Target Platform: iOS**
**Devices: iPhone 12 Pro Max**

## Logs

<details>
<summary>Logs</summary>

```
Flutter (Channel unknown, 2.11.0-0.1.pre, on macOS 12.2.1 21D62 darwin-arm, locale de-DE)
```

</details>

**Comment by darshankawar** [comment]
@b3nni97 
Thanks for the report. I do see difference in the performance when running the sample code on latest stable, beta and master respectively.

1. On latest stable (2.10.3), the scrolling is smooth and there's no noticeable spike in the performance:


https://user-images.githubusercontent.com/67046386/159439657-b8c3d0e5-6c72-4492-86f8-960920777956.mov

2. On latest beta (2.12) and master (2.13.0-0.0.pre.191), using the same code and scrolling the list, shows spike in performance overlay:


https://user-images.githubusercontent.com/67046386/159439805-0dbf0ec3-83a2-4654-90d0-39dede2ed9a1.mov


https://user-images.githubusercontent.com/67046386/159439859-780abd46-9663-43d5-90d5-6758354c0458.mov

The code sample uses `CupertinoApp`, but the same behavior is observed using `MaterialApp` too.

<details>
<summary> runnable code sample </summary>

```

import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() => runApp(CupertinoApp(
  showPerformanceOverlay: true,
  home: TestApp(),
));

class TestApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: ListView.builder(
        itemBuilder: (context, index) {
      return Text(
        '$index index $index index $index index',
        style: CupertinoTheme.of(context).textTheme.textStyle,
      );
    },
      ),
    );
  }
}

```

</details>


I am going ahead and labeling it as regression.

<details>
<summary> stable, master and beta flutter doctor -v </summary>

```

[✓] Flutter (Channel stable, 2.10.3, on macOS 12.2.1 21D62 darwin-x64, locale
    en-GB)
    • Flutter version 2.10.3 at /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (11 hours ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.


[✓] Flutter (Channel master, 2.13.0-0.0.pre.191, on macOS 12.2.1 21D62
    darwin-x64, locale en-GB)
    • Flutter version 2.13.0-0.0.pre.191 at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 69b92f0452 (3 minutes ago), 2022-03-21 21:25:09 -0700
    • Engine revision e6233bd30b
    • Dart version 2.17.0 (build 2.17.0-223.0.dev)
    • DevTools version 2.11.4

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

[✓] Flutter (Channel beta, 2.12.0-4.1.pre, on macOS 12.2.1 21D62 darwin-x64,
    locale en-GB)
    • Flutter version 2.12.0-4.1.pre at /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 680962aa75 (6 days ago), 2022-03-16 13:46:03 -0700
    • Engine revision e9f57b5d0f
    • Dart version 2.17.0 (build 2.17.0-182.1.beta)
    • DevTools version 2.11.1

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 65.1.4
    • Dart plugin version 213.7228

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (3 available)
    • iPhone 12 Pro Max (mobile) • 067D36B1-0434-441F-8683-4842C8ED729A • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-x64     • macOS 12.2.1 21D62 darwin-x64
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 99.0.4844.83

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!


```

</details>

**Comment by b3nni97** [comment]
@darshankawar Could you reproduce the problem on android as well? Unfortunately, I do not currently have an Android device.

The next stable version must not be released with this bug, because this probably affects every app and the performance gets really bad as soon as you use text.

**Comment by darshankawar** [comment]
I verified this on Android as well and see the same behavior, so updating the labels and issue title accordingly.

**Comment by goderbauer** [comment]
Interesting. I looked through the commit history and nothing looked immediately suspicious. We will have to do some bisecting to find the offending commit.

@darshankawar For the future: When looking at performance issues you want to run on a real device in `--release` mode. Performance in debug mode and/or on Simulators/Emulators can be very different from the real deal. Looks like we got lucky and the issue even reproduced under these circumstances, though.

**Comment by jason-simmons** [comment]
I started looking at this and was able to reproduce a major performance problem affecting SkParagraph on iOS and macOS.

The issue that I saw was caused by a call to `CTFontCopyVariationAxes` made by `SkTypeface_Mac::onGetVariationDesignPosition`.  In my measurements `CTFontCopyVariationAxes` was taking several milliseconds.

`ShaperHarfBuzz::shape` calls `create_hb_font` for every text shaping.  `create_hb_font` calls `getVariationDesignPosition` twice, resulting in two of the expensive calls to `CTFontCopyVariationAxes`.

`ShaperHarfBuzz` may be able to avoid doing this on every layout by caching a HarfBuzz font representing the `SkTypeface` in the `HBLockedFaceCache`.  Each `shape` call could then call `hb_font_create_sub_font` to add the `SkFont` specific attributes.

It might also make sense for `SkTypeface_Mac` to cache the `CTFontCopyVariationAxes` results.

@bungeman @rusino

**Comment by bungeman** [comment]
Created https://skia-review.googlesource.com/c/skia/+/524760 to call `CTFontCopyVariationAxes` only when required for all users.

**Comment by b3nni97** [comment]
@jason-simmons could you verify that `CTFontCopyVariationAxes` is more performant in the current stable?

**Comment by jason-simmons** [comment]
The stable branch is still using the older Libtxt text renderer, which does not go through that code path.
