### ISSUE TITLE
[dashboard] webhook for branch or tag creation

### ISSUE THREAD

**Issue by XilaiZhang** [flutter/flutter#100517]
Hello, I am currently working on https://github.com/flutter/flutter/issues/100491 and would like to verify that branch-creation webhooks have already been enabled for repos we would like to monitor. e.g. if we would like to monitor and trigger events from creating a branch in flutter-dashboard repo, we would like to enable the `branch or tag creation` tab under the webhook tab under settings tab of the flutter-dashboard repo (need admin premission), and a list of available webhooks will look like the picture below:
![81121611-25c8ad00-8efd-11ea-9658-cdec1607dbf2](https://user-images.githubusercontent.com/38773539/159387168-f6be2c73-6e00-41fe-8203-8b48be561dcf.png)
It would also be helpful if I could know the end url address of these webhooks if they have been created. e.g. if the url address is abc.com for a `branch or tag creation` webhook of flutter-dashboard repo, then triggered event will be sent to abc.com. And we would be able to process messages from abc.com. 
@godofredoc  can you help check if such webhooks have been created for our interested repos, and instruct on the end url address as well? I lack admin permissions and can't view the settings tab for our repos? Thank you!
cc @CaseyHillers

**Comment by godofredoc** [comment]
We may want to brainstorm about it, enabling these permissions have security implications and flutter-dashboard may not be the right application to enable it.

**Comment by godofredoc** [comment]
Can you please expand? read permission for what section?

**Comment by godofredoc** [comment]
After re-reading I think I understand, you want branch and tag events to be notified to the webhook. Is that correct?

**Comment by XilaiZhang** [comment]
Hello hello, sorry for the delay, wasn’t expecting everyone to reply, thought I would get a response tomorrow. Right right the linked image is just a list of the available options. I was initially wanting the checkbox before ‘creating a branch or tag’ to be ticked. And yes I would like branch creation be enabled through webhook, and send the event to some url endpoint so that we can receive it. And yes I think this might need further thought, because from my understanding we would need to enable webhook for all the repos we would like to monitor. Thanks everyone for the responses!

**Comment by godofredoc** [comment]
The webhook configuration has been updated to forward branch and tag creation events.

**Comment by XilaiZhang** [comment]
Gracias!
