### ISSUE TITLE
Finding the list of plugins, from the website, isn't easy

### ISSUE THREAD

**Issue by jhirth** [flutter/flutter#10051]
There should be a link to the plugins page (https://pub.dartlang.org/flutter/plugins) in the side menu.

**Comment by sethladd** [comment]
I can add this to the new homepage, at least.

I assume also to https://flutter.io/platform-plugins/

**Comment by sethladd** [comment]
cc @mit-mit

**Comment by sethladd** [comment]
It's unlikely that we'll add this link to our side menu. It's pretty long as it is, but we do have a link for the "homepage" of the plugins. From that page, it should give people a good orientation of what plugins are, what they can do, and how to find them.
