### ISSUE TITLE
is the mac workflow with the flutter cli tool current?

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter#1005]
The `flutter` cli tool prints out:

> To copy files to iOS devices, please install ios-deploy.
> You can do this using homebrew as follows:
>  brew tap flutter/flutter
>  brew install ios-deploy

But the brew tap step fails - I suspect this workflow is out of date. We should update and remove any deprecated steps.

**Comment by devoncarew** [comment]
cc @chinmaygarde - I don't know if `ios-deploy` is part of the workflow anymore. Our brew repo doesn't seem to exist anymore:

```
remote: Repository not found.
fatal: repository 'https://github.com/flutter/homebrew-flutter/' not found
```

**Comment by sethladd** [comment]
I just ran into this, too.

**Comment by sethladd** [comment]
Fixed!  (repo now in place, and docs about to be updated)
