### ISSUE TITLE
[video_player]Unhandled Exception: PlatformException(IllegalStateException, java.lang.IllegalStateException: Unsupported type: 4, null, null)

### ISSUE THREAD

**Issue by yousiwu111** [flutter/flutter#100541]
```
[ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: PlatformException(IllegalStateException, java.lang.IllegalStateException: Unsupported type: 4, null, null)
[        ] E/flutter (21069): #0      VideoPlayerApi.create (package:video_player_platform_interface/messages.dart:189:7)
[        ] E/flutter (21069): <asynchronous suspension>
[        ] E/flutter (21069): #1      MethodChannelVideoPlayer.create (package:video_player_platform_interface/method_channel_video_player.dart:50:31)
[        ] E/flutter (21069): <asynchronous suspension>
[        ] E/flutter (21069): #2      VideoPlayerController.initialize (package:video_player/video_player.dart:329:19)
[        ] E/flutter (21069): <asynchronous suspension>
```

**Comment by danagbemava-nc** [comment]
Hi @yousiwu111, please provide a complete minimal reproducible code sample that we can use to verify this as well as the required steps to reproduce.

Please also provide the output of `flutter doctor -v` as well as the version of `video_player` you're using. 

For future reference, when you're filing an issue, please fill out the template and provide as much information as possible. Your error message alone is not enough to tell us what is happening. 

Thank you

**Comment by yousiwu111** [comment]
hello @danagbemava-nc thanks for your reply
video_player version is 2.2.3
this is flutter doctor -v  result 
[√] Flutter (Channel stable, 2.0.5, on Microsoft Windows [Version 10.0.19043.1586], locale zh-CN)
    • Flutter version 2.0.5 at D:\flutterSDK\flutter2
    • Framework revision adc687823a (11 months ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at D:\AndroidSDK
    • Platform android-31, build-tools 30.0.3
    • ANDROID_HOME = D:\AndroidSDK
    • ANDROID_SDK_ROOT = D:\AndroidSDK
    • Java binary at: D:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at D:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (3 available)
    • PRO 7 S (mobile) • 79BMADR5HPRBE • android-arm64  • Android 7.0 (API 24)
    • Chrome (web)     • chrome        • web-javascript • Google Chrome 92.0.4515.159
    • Edge (web)       • edge          • web-javascript • Microsoft Edge 98.0.1108.56

• No issues found!

**Comment by theRealProHacker** [comment]
I think you should also add some code. And I found that when you have a problem that just suddenly happens without any apparent reason just do `flutter create .` or if that still doesn't work delete all the folders you didn't edit yourself (lib, test and any assets) and then run `flutter create .` again.

**Comment by yousiwu111** [comment]
No registered handler for message. Responding to Dart with empty reply message.

**Comment by yousiwu111** [comment]
/**
   * Value returned by {@link Util#inferContentType(String)} for DASH manifests.
   */
  public static final int TYPE_DASH = 0;
  /**
   * Value returned by {@link Util#inferContentType(String)} for Smooth Streaming manifests.
   */
  public static final int TYPE_SS = 1;
  /**
   * Value returned by {@link Util#inferContentType(String)} for HLS manifests.
   */
  public static final int TYPE_HLS = 2;
  /**
   * Value returned by {@link Util#inferContentType(String)} for files other than DASH, HLS or
   * Smooth Streaming manifests.
   */
  public static final int TYPE_OTHER = 3;


throw new IllegalStateException("Unsupported type: " + type);     type == 4

**Comment by yousiwu111** [comment]
i find the reason ,file type is unknow,i support local file path ,but not distinguish

**Comment by yousiwu111** [comment]
I set VideoPlayerController.network(formatHint: VideoFormat.other,) 
It is useful ,play local video or net video
