### ISSUE TITLE
After update to flutter-2.8.1, canvas.setMatrix in skia not work on Android.

### ISSUE THREAD

**Issue by rivalnhwc** [flutter/flutter#100525]
Currently, I am working on Rendering games on Android using flutter, so i need the "setMatrix" API, which is not exposed in flutter.

So, I modified the flutter engine to expose "setMatrix", "resetMatrix", "getLocalToDevice" API on "Canvas", just like https://github.com/flutter/engine/pull/7704 do. 

It works fine on flutter 2.0.0 and 2.5.3, but when i update to 2.8.1, "setMatrix" just not work, when i use "getLocalToDevice" after "setMatrix", it can return the correct result, but when rendering, it shows me the matrix is not applied. I also tried flutter 2.10.3, not work either.

So I was wendering is there sth change in flutter cause this situation? and how can i continue my application? "setMatrix" is quite important in game rendering, is there any solution or replacement？ 

thanks

**Comment by maheshmnj** [comment]
Hi @rivalnhwc, Thanks for filing the issue. Can you share a minimal reproducible code sample along with the expected vs actual output?

Thanks

**Comment by rivalnhwc** [comment]
Hi, @maheshmnj , thanks for your reply, here is the example:

I'm using a CustomPainter, this is the paint function of it.

```
 @override
  void paint(Canvas canvas, Size size) {
    Paint paint = new Paint()..color = Colors.red;

    canvas.drawCircle(Offset(100, 100), 100, paint);

    canvas.setTransform(Float64List.fromList([
      1,0,0,0,
      0,1,0,0,
      0,0,1,0,
      200,200,0,1
    ]));

    paint.color = Colors.blue;

    canvas.drawCircle(Offset(100, 100), 100, paint);
}
```
the result of this code is:

![device-2022-03-22-192735](https://user-images.githubusercontent.com/11538838/159471788-00b358b4-d681-43fb-9f61-23028418b1ad.png)

what I expected  is:

![device-2022-03-22-192902](https://user-images.githubusercontent.com/11538838/159471985-84858e25-b75b-4498-a3d0-fbd2e68cb23d.png)

**Comment by rivalnhwc** [comment]
Yes, @maheshmnj  `setTransform` is `setMatrix` , exposed from engine

**Comment by maheshmnj** [comment]
cc: @dnfield

**Comment by dnfield** [comment]
I'm not really sure how to act on this bug - it's asking about a custom modification of the engine to expose API we don't support and why that might have broken between two flutter versions. I can't think of any reason, but I don't think this is a bug in Flutter either.
