### ISSUE TITLE
Validate the option on converging dart and flutter to use the same VM image

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#100511]
Dart uses an image based on ubuntu and Flutter uses an image based on debian. As an opportunity to standardize workflows we would like to validate flutter/engine and flutter/tests run correctly in the ubuntu based images.

**Comment by godofredoc** [comment]
\cc @athomas @whesse @cbracken

**Comment by godofredoc** [comment]
Validated all the engine builds with the ubuntu image and only the fuchsia tests are failing because of missing kvm support.

**Comment by athomas** [comment]
Good news!

Does that mean we need to install additional packages for kvm support? Which ones are needed?

**Comment by godofredoc** [comment]
Seems like the first step is to move the VMs to a processor that supports virtualization.

**Comment by godofredoc** [comment]
\cc @yusuf-goog please close when the migration is complete

**Comment by yusuf-goog** [comment]
Closing this, since we have validated running on dart ubuntu images and already migrated our fleets over.
