### ISSUE TITLE
Flutter web. Problem only IOS 

### ISSUE THREAD

**Issue by voolf00** [flutter/flutter#100656]
**ios problem in web.**

When you re-pass from Telegram following the link to the browser, all widgets are displayed incorrectly in both safari and chrome (build html)

1. I open a link from Telegram to the web (the browser opens correctly)
2. After I return to Telegram
3. I open again (In 90% of cases the page breaks)

link: https://www.youtube.com/watch?v=ctdjWl8hlWY

If the browser closes all previous pages of Web flutter. Telegram website reopens correctly
There is a similar glitch in android, but it is not so obvious

**Comment by danagbemava-nc** [comment]
Hi @voolf00, can you provide the output of `flutter doctor -v` and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?

This issue seems oddly similar to #92655 but at the time it was only occurring on chrome.

Thank you

**Comment by voolf00** [comment]
C:\Users\voolf\YandexDisk\Flutter\dwof>flutter doctor -v
[√] Flutter (Channel stable, 2.8.1, on Microsoft Windows [Version 10.0.19042.1586], locale ru-RU)
    • Flutter version 2.8.1 at C:\Users\voolf\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (3 months ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at C:\Users\voolf\AppData\Local\Android\sdk
    • Platform android-32, build-tools 32.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] VS Code (version 1.63.2)
    • VS Code at C:\Users\voolf\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] VS Code, 64-bit edition (version 1.63.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 99.0.4844.82
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 99.0.1150.46

• No issues found!

**Comment by voolf00** [comment]
This problem was in Safari too. Wery hard only on iphone.

**Comment by danagbemava-nc** [comment]
HI @voolf00, can you upgrade to the latest version of stable to see if you still experience this issue? If you do please provide the updated `flutter doctor -v` and a [minimal complete reproducible code sample] so that we may verify this. 

Thank you
