### ISSUE TITLE
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR)

### ISSUE THREAD

**Issue by jbsolutions2008** [flutter/flutter#100681]
Thank you for providing a wonderful and amazing SDK. We have facing an issue with our release application. We have got a crash log from the play store.

Can you please guide how to resolve these issues?

 
**# Error Log :**
pid: 0, tid: 0 >>> package name <<<

backtrace:
  #00  pc 0000000000767dd0  /data/app/~~O3DNr9J3gFk_y-Vi0SyaOQ==/package name-ppthErZ5ueEPyrc_gqqRjQ==/split_config.arm64_v8a.apk!libflutter.so
  #00  pc 00000000004c5ec8  /data/app/~~O3DNr9J3gFk_y-Vi0SyaOQ==/package name-ppthErZ5ueEPyrc_gqqRjQ==/split_config.arm64_v8a.apk!libflutter.so
  #00  pc 00000000004c9084  /data/app/~~O3DNr9J3gFk_y-Vi0SyaOQ==/package name-ppthErZ5ueEPyrc_gqqRjQ==/split_config.arm64_v8a.apk!libflutter.so
  #00  pc 0000000000430a64  /data/app/~~O3DNr9J3gFk_y-Vi0SyaOQ==/package name-ppthErZ5ueEPyrc_gqqRjQ==/split_config.arm64_v8a.apk!libflutter.so
  #00  pc 00000000004302f0  /data/app/~~O3DNr9J3gFk_y-Vi0SyaOQ==/package name-ppthErZ5ueEPyrc_gqqRjQ==/split_config.arm64_v8a.apk!libflutter.so
  #00  pc 0000000000430318  /data/app/~~O3DNr9J3gFk_y-Vi0SyaOQ==/package name-ppthErZ5ueEPyrc_gqqRjQ==/split_config.arm64_v8a.apk!libflutter.so
  #00  pc 000000000036da78  /data/app/~~O3DNr9J3gFk_y-Vi0SyaOQ==/package name-ppthErZ5ueEPyrc_gqqRjQ==/split_config.arm64_v8a.apk!libflutter.so
  #00  pc 000000000036db20  /data/app/~~O3DNr9J3gFk_y-Vi0SyaOQ==/package name-ppthErZ5ueEPyrc_gqqRjQ==/split_config.arm64_v8a.apk!libflutter.so
  #00  pc 000000000036db38  /data/app/~~O3DNr9J3gFk_y-Vi0SyaOQ==/package name-ppthErZ5ueEPyrc_gqqRjQ==/split_config.arm64_v8a.apk!libflutter.so
  #00  pc 00000000002d3b58  /data/app/~~O3DNr9J3gFk_y-Vi0SyaOQ==/package name-ppthErZ5ueEPyrc_gqqRjQ==/split_config.arm64_v8a.apk!libflutter.so
  #00  pc 00000000002d7050  /data/app/~~O3DNr9J3gFk_y-Vi0SyaOQ==/package name-ppthErZ5ueEPyrc_gqqRjQ==/split_config.arm64_v8a.apk!libflutter.so
  #00  pc 00000000002d948c  /data/app/~~O3DNr9J3gFk_y-Vi0SyaOQ==/package name-ppthErZ5ueEPyrc_gqqRjQ==/split_config.arm64_v8a.apk!libflutter.so
  #00  pc 0000000000018184  /system/lib64/libutils.so (android::Looper::pollInner(int)+916)
  #00  pc 0000000000017d84  /system/lib64/libutils.so (android::Looper::pollOnce(int, int, int, void**)+116)
  #00  pc 0000000000017510  /system/lib64/libandroid.so (ALooper_pollOnce+104)
  #00  pc 00000000002d959c  /data/app/~~O3DNr9J3gFk_y-Vi0SyaOQ==/package name-ppthErZ5ueEPyrc_gqqRjQ==/split_config.arm64_v8a.apk!libflutter.so
  #00  pc 00000000002d62dc  /data/app/~~O3DNr9J3gFk_y-Vi0SyaOQ==/package name-ppthErZ5ueEPyrc_gqqRjQ==/split_config.arm64_v8a.apk!libflutter.so
  #00  pc 00000000002d8008  /data/app/~~O3DNr9J3gFk_y-Vi0SyaOQ==/package name-ppthErZ5ueEPyrc_gqqRjQ==/split_config.arm64_v8a.apk!libflutter.so
  #00  pc 00000000000b6e44  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+264)
  #00  pc 0000000000053454  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+68)
  
  **Flutter doctor** 
  

√] Flutter (Channel stable, 2.2.0, on Microsoft Windows [Version 10.0.18363.1556], locale en-US)
    • Flutter version 2.2.0 at  "path"
    • Framework revision b22742018b (10 months ago), 2021-05-14 19:12:57 -0700
    • Engine revision a9d88a4d18
    • Dart version 2.13.0

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at "path"
    • Platform android-31, build-tools 30.0.3
    • ANDROID_HOME = "path"
    • Java binary at: "path"
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at "path"

[√] Android Studio (version 4.1.0)
    • Android Studio at "path"
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.64.2)
    • VS Code at "path"
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (4 available)
    • moto g 60 (mobile)                    • ZD2222CWBH    • android-arm64  • Android 11 (API 30)
    • Android SDK built for x86 64 (mobile) • emulator-5554 • android-x64    • Android 12 (API 31) (emulator)
    • Chrome (web)
                          • chrome        • web-javascript • Google Chrome 99.0.4844.82
    • Edge (web)
                            • edge          • web-javascript • Microsoft Edge 99.0.1150.46

• No issues found!
  
  **# Device Detail **

Android version: 9,11 and 12(mostly in 12 version) 

Devices :

Samsung Galaxy S20 5G
Samsung Galaxy S21 Ultra 5G
Samsung Galaxy S21 5G
Samsung Galaxy S10
Others

**Comment by darshankawar** [comment]
@jbsolutions2008 
You are on older version of Flutter, 2.2.0. Even if this is a genuine crash, the fix won't be made on that version. You'll need to upgrade to latest stable that should already have fixed this crash. See this similar crash that was fixed recently: https://github.com/flutter/flutter/issues/100122

I am closing this for now, as this should already be fixed on latest versions.

**Comment by jbsolutions2008** [comment]
Thanks, @darshankawar!
