### ISSUE TITLE
Boiletplate Android Manifest misses required attributes

### ISSUE THREAD

**Issue by stevenroose** [flutter/flutter#1006]
After trying to publish a Flutter-created app to Google Play, it noticed me that some required pieces were missing from the `AndroidManifest.xml` file.

 - the `android:versionCode` and `android:versionName` attributes in `<manifest>`
 - `android:icon` in `<application>`, although this attribute requires the presence of an actual icon drawable

**Comment by devoncarew** [comment]
@stevenroose, the code to generate the manifest file lives here: https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/commands/init.dart#L226 if you want to try your hand at a PR. I'm less familiar with those constants and what they should default to.

**Comment by stevenroose** [comment]
I'm pretty new to Android dev too, but I'll see. Thing is that for me to
fix the icon part, I need to actually upload an icon or else the app cant
run. Should I create a dummy Flutter logo-based icon?

**Comment by devoncarew** [comment]
I think we should have an icon in there, if that's what's needed to to publish the sample. You could probably either just add a comment to the manifest file, or add an icon to the generated app, based off the flutter logo.

**Comment by eseidelGoogle** [comment]
I'm also not 100% sure if the `flutter apk` command signs with the correct key, which you definitely want to do before publishing.  On my system it uses the chromium dev keys, presumably on a non-dev system it would have prompted for personal android signing keys?  I suspect that @jason-simmons thought of this when he wrote `flutter apk`, i just haven't tested proper signing personally.

It looks like `flutter apk` is hardcoded to teh chromium signing key:
https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/commands/apk.dart#L146

You don't want to publish with that key. :(  We will need to fix the command.

**Comment by abarth** [comment]
> On my system it uses the chromium dev keys, presumably on a non-dev system it would have prompted for personal android signing keys?

I believe it always uses the Chromium dev key.  Would you be willing to file a bug about improving the command?

**Comment by sethladd** [comment]
> We will need to fix the command.

Should we open a new issue?

**Comment by eseidelGoogle** [comment]
Filed https://github.com/flutter/flutter/issues/1010

**Comment by eseidelGoogle** [comment]
To answer the earlier question, @stevenroose, we should include a default icon.  I recommend using the simple flutter one from material_gallery (and then we should give material_gallery a nicer one):
https://github.com/flutter/flutter/tree/master/examples/material_gallery/apk

**Comment by eseidelGoogle** [comment]
We probably need this for the Hackathon.  The initial `flutter init` flow needs to produce a working (and ideally store-compatible) app.

**Comment by stevenroose** [comment]
What hackathon when?? :)

**Comment by eseidelGoogle** [comment]
We're holding a flutter-team hackathon in mid march.  Make sure that all of the folks who work on Flutter and its dependencies have written a flutter app themselves. :)  You'll be seeing us make a large push for better developer experience, docs, onboarding, etc between now and then.  Sorry we don't have any plans for a publicly hosted hackathon at this time.

**Comment by stevenroose** [comment]
Bummer. Well, I'm curious. Flutter could indeed benefit from a huge
documentation improvement. However boring to provide, it's inevitable for
adoption.

**Comment by eseidelGoogle** [comment]
Please feel encouraged to file bugs against our documentation shortcomings.  @qchong recently joined our project and is working explicitly on making sure we have a coherent technical writeups of flutter and how to use it.  Other members of the team have slowly been adding more dartdocs to the code, which are generated by our builders and appear at https://docs.flutter.io immediately after they are landed in the repository.
