### ISSUE TITLE
Cannot use firebase_auth plugin

### ISSUE THREAD

**Issue by arashbi** [flutter/flutter#10068]
## Steps to Reproduce

Created a new application, edited pubspec.yaml and added a single line:
`firebase_auth:`
Then I ran :
`flutter packages get`
and
`flutter run`

## Logs

Running 'flutter packages get' in test_plugins...     0.4s
Launching lib/main.dart on iPhone 6 in debug mode...
Running pod install...                                    
Error running pod install: Exit code 1 from: pod install
Error launching application on iPhone 6.

## Flutter Doctor

Running 'flutter packages get' in test_plugins...     0.4s
Launching lib/main.dart on iPhone 6 in debug mode...
Running pod install...                                    
Error running pod install: Exit code 1 from: pod install
Error launching application on iPhone 6.
➜  test_plugins flutter doctor

[✓] Flutter (on Mac OS X 10.12 16A323, channel master)
    • Flutter at /Users/arash/source/flutter
    • Framework revision fc1b5c9ba9 (3 days ago), 2017-05-10 07:45:16 -0700
    • Engine revision cbbf956fcb
    • Tools Dart version 1.23.0-dev.11.11

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at /Users/arash/Library/Android/sdk
    • Platform android-25, build-tools 25.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.3.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3.2, Build version 8E2002
    • ios-deploy 1.9.1
    • CocoaPods version 1.2.1

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Gradle version 3.2
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Ultimate Edition (version 2017.1.2)
    • Dart plugin version 171.4424
    • Flutter plugin version 13.1

[✓] Connected devices
    • iPhone 6 • 369236F5-B245-44E5-A43B-60D6DAAC09DB • ios • iOS 10.3 (simulator)

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by eseidelGoogle** [comment]
@szakarias or @goderbauer would know.  Does `pod install` when run alone (outside of Flutter) provide you an error message?

**Comment by goderbauer** [comment]
You could also try running with `flutter run -v` to get a more detailed error. My guess would be that your pods need updating (`pod repo update`, see https://github.com/flutter/flutter/issues/9993).

**Comment by arashbi** [comment]
`pod repo update` didn't help.
running in verbose mode gave me this:

[ +12 ms] Found plugin firebase_auth at /Users/arash/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.0.1/
[      +38 ms] pod --version
[     +466 ms] pod --version
[     +297 ms] Exit code 0 from: pod --version
[            ] 1.2.1
[            ] Running pod install...
[            ] [ios/] pod install
[     +189 ms] [SYS LOG] May 13 21:33:22 MacBook-Pro com.apple.usbmuxd[2301]: notice    Idle, stopping.
[      +18 ms] [SYS LOG] May 13 21:33:22 MacBook-Pro com.apple.usbmuxd[2767]: notice    usbmuxd-374.913 on Mar 17 2017 at 17:43:50, running 64 bit
[     +651 ms] [DEVICE LOG] May 13 21:33:22 MacBook-Pro CoreSimulatorBridge[68496]: Pasteboard change listener callback port <NSMachPort: 0x7ffe75011950> registered
[     +721 ms] Analyzing dependencies
                       Fetching podspec for `Flutter` from `/Users/arash/Src/flutter/bin/cache/artifacts/engine/ios`
                       Fetching podspec for `firebase_auth` from `/Users/arash/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.0.1/ios`
                       Downloading dependencies
                       Installing Firebase (3.17.0)
                       Installing FirebaseAnalytics (3.9.0)
                       Installing FirebaseAuth (3.1.1)
                       Installing FirebaseCore (3.6.0)
                       Installing FirebaseInstanceID (1.0.10)
                       Installing FirebaseUI (3.1.1)
                       Installing Flutter (1.0.0)
                       Installing GTMOAuth2 (1.1.4)
                       Installing GTMSessionFetcher (1.1.9)
                       Installing Google (3.0.3)
                       Installing GoogleSignIn (4.0.2)
                       Installing GoogleToolboxForMac (2.1.1)
                       Installing firebase_auth (0.0.1)
                       [!] The 'Pods-Runner' target has transitive dependencies that include static binaries: (/Users/arash/Src/flutter-projects/firebase/ios/Pods/FirebaseUI/FirebaseUIFrameworks/FirebaseAuthUI/Frameworks/FirebaseAuthUI.framework, /Users/arash/Src/flutter-projects/firebase/ios/Pods/FirebaseUI/FirebaseUIFrameworks/FirebaseGoogleAuthUI/Frameworks/FirebaseGoogleAuthUI.framework, /Users/arash/Src/flutter-projects/firebase/ios/Pods/Google/Frameworks/GGLCore.framework, and /Users/arash/Src/flutter-projects/firebase/ios/Pods/Google/Frameworks/GGLSignIn.framework)
                       
                       
                       [!] `<PBXGroup UUID=`97C146E51CF9000F007C117D`>` attempted to initialize an object with an unknown UUID. `CF3B75C9A7D2FA2A4C99F110` for attribute: `children`. This can be the result of a merge and  the unknown UUID is being discarded.
                       
                       [!] Automatically assigning platform ios with version 8.0 on target Runner because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.
[       +2 ms] Error running pod install: Exit code 1 from: pod install
[            ] Error launching application on iPhone 6.
[      +12 ms] "flutter run" took 7,141ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:29)
#1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:327)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:210)
<asynchronous suspension>
#3      RunCommand.verifyThenRunCommand (package:flutter_tools/src/commands/run.dart:210)
<asynchronous suspension>
#4      FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:156)
<asynchronous suspension>
#5      CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#6      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:261)
<asynchronous suspension>
#7      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#8      Future.Future.sync (dart:async/future.dart:208)
#9      CommandRunner.run (package:args/command_runner.dart:109)
#10     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:156)
#11     run.<anonymous closure> (package:flutter_tools/executable.dart:140)
<asynchronous suspension>
#12     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#13     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#14     _rootRun (dart:async/zone.dart:1120)
#15     _CustomZone.run (dart:async/zone.dart:1001)
#16     runZoned (dart:async/zone.dart:1465)
#17     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#18     run (package:flutter_tools/executable.dart:113)
<asynchronous suspension>
#19     main (package:flutter_tools/executable.dart:66)
<asynchronous suspension>
#20     main (file:///Users/arash/Src/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
#21     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#22     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)


[     +102 ms] ensureAnalyticsSent: 98ms
[       +1 ms] exiting with code 2

**Comment by jakobr-google** [comment]
You might be hitting #9694. Try removing `use_frameworks!` from `ios/Podfile`, and see if that changes anything.

**Comment by arashbi** [comment]
That solved the problem. Everything is happy now!

**Comment by miketraverso** [comment]
This should be mentioned on https://codelabs.developers.google.com/codelabs/flutter-firebase/index.html?index=..%2F..%2Findex#4 

:)

**Comment by eseidelGoogle** [comment]
FYI @collinjackson

**Comment by FaisalAbid** [comment]
Just ran into this issue too!

**Comment by rajeshzmoke** [comment]
/Users/rajeshkumar/Desktop/flutter_demo/ios/Runner/GeneratedPluginRegistrant.m:6:9: fatal error: 'firebase_analytics/FirebaseAnalyticsPlugin.h' file not found
#import <firebase_analytics/FirebaseAnalyticsPlugin.h>
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by ch-muhammad-adil** [comment]
In your podfile where You see 
```
target 'Runner' do
  use_frameworks!  
```

comment user_frameworks!
```
target 'Runner' do
  # use_frameworks!  
```

and go to path /ios of the project 

run 

`pod install`

and cheers.

**Comment by ch-muhammad-adil** [comment]
@rajeshzmoke I have created this project a month ago than just came back to start over it again. But this is what I had done. It wasn't commented before than i did later on today while integration of firebase..

**Comment by rajeshzmoke** [comment]
@ch-muhammad-adil can u try creating a new one now and check?

**Comment by prasant10050** [comment]
@ch-muhammad-adil  ..Thanks..bro..
u give the better solution for this issue

go to path /ios of the project

run

pod install

**Comment by prasant10050** [comment]
step 1)in mac
**Install homebrew.**
Open the terminal and run these commands to install CocoaPods:
 **brew install cocoapods** or **brew upgrade cocoapods**
 **pod setup**
step 2)
go to path /ios of the project

run

**pod install**

**Comment by kroikie** [comment]
@arashbi

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1009. Any further collaboration will be done there.

**Comment by skye123** [comment]
firebase_auth 
- (void)signInWithCredential:(FIRAuthCredential *)credential
                  completion:(nullable FIRAuthDataResultCallback)completion {
  [self signInAndRetrieveDataWithCredential:credential completion:completion];
}
Error message：
Incompatible block pointer types sending 'void (^)(FIRUser *__strong, NSError *__strong)' to parameter of type 'void (^ _Nullable)(FIRAuthDataResult * _Nullable __strong, NSError * _Nullable __strong)'
