### ISSUE TITLE
Inlining a SurfaceView in a PlatformView in a Flutter hierarchy should have an automated test

### ISSUE THREAD

**Issue by xster** [flutter/flutter#100669]
We need an integration test to cover cases like b/226467394

**Comment by blasten** [comment]
offline conversation with jreck: this needs to use `UiAutomation#takeScreenshot()`, and remove the status/navigation bars

**Comment by xster** [comment]
Understood. Thanks. I was wondering, since we seem to have a bunch of platform view tests in the engine already.

**Comment by blasten** [comment]
Closing in favor of https://github.com/flutter/flutter/issues/97853. That issue is tracking missing integration tests.
