### ISSUE TITLE
Mac_arm64_staging plugin_lint_mac failed with `Undefined symbols for architecture arm64`

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#100638]
Part of https://github.com/flutter/flutter/issues/87508

[Mac_arm64_staging plugin_lint_mac](https://luci-milo.appspot.com/raw/build/logs.chromium.org/flutter/led/keyonghan_google.com/74c2c0b1de7440efecaa0796e7dcb386aad3563310fb202b41ac08f62e829084/+/build.proto)

```
[plugin_lint_mac] [STDOUT] stdout:     ld: warning: ignoring file /opt/s/w/ir/x/t/CocoaPods-Lint-20220322-5341-n64c8s-integration_test_macos/Pods/FlutterMacOS/FlutterMacOS.framework/FlutterMacOS, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
[plugin_lint_mac] [STDOUT] stdout:     Undefined symbols for architecture arm64:
[plugin_lint_mac] [STDOUT] stdout:       "_FlutterMethodNotImplemented", referenced from:
[plugin_lint_mac] [STDOUT] stdout:           integration_test_macos.IntegrationTestPlugin.handle(_: __C.FlutterMethodCall, result: (Any?) -> ()) -> () in IntegrationTestPlugin.o
[plugin_lint_mac] [STDOUT] stdout:       "_OBJC_CLASS_$_FlutterMethodChannel", referenced from:
[plugin_lint_mac] [STDOUT] stdout:           objc-class-ref in IntegrationTestPlugin.o
[plugin_lint_mac] [STDOUT] stdout:     ld: symbol(s) not found for architecture arm64
[plugin_lint_mac] [STDOUT] stdout:     clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by jmagman** [comment]
I don't see that log output in that build, which is failing with `ProcessException: Bad CPU type in executable`, is that log from another build?

**Comment by keyonghan** [comment]
> I don't see that log output in that build, which is failing with `ProcessException: Bad CPU type in executable`, is that log from another build?

Oops, copies the wrong link. Updated.

**Comment by jmagman** [comment]
`ignoring FlutterMacOS, building for macOS-arm64 but attempting to link with file built for macOS-x86_64`

It's pulling in the last published FlutterMacOS pod version 2.10.2 which doesn't support ARM yet.  We should skip moving `plugin_lint_mac` to prod until there are arm binaries in stable...

**Comment by jmagman** [comment]
Flutter 3.0 FlutterMacOS pod with arm64 binary has been published.  @keyonghan can you try again?  Hoping it should work now.

**Comment by keyonghan** [comment]
> Flutter 3.0 FlutterMacOS pod with arm64 binary has been published. @keyonghan can you try again? Hoping it should work now.

With the arm64 ruby, it finally passes!
https://luci-milo.appspot.com/raw/build/logs.chromium.org/flutter/led/keyonghan_google.com/0702c3bfc7a735541edf8d0c997340b988fe384a01fa867e705daa43272ab00d/+/build.proto

**Comment by keyonghan** [comment]
Recipe change is in supporting arm64 ruby, but the test is now flaky with same error as this bug: https://ci.chromium.org/p/flutter/builders/staging/Mac_arm64_staging%20plugin_lint_mac

One observation is the failures happen on only mac4 and mac5, while others pass on other bots. Do you see any bot related issue may cause this? /cc @jmagman

**Comment by jmagman** [comment]
@keyonghan can you point me to a test run flaking on mac4 or 5? I'm not spotting it.

**Comment by keyonghan** [comment]
One build on mac5: https://ci.chromium.org/ui/p/flutter/builders/staging/Mac_arm64_staging%20plugin_lint_mac/1352/overview
One build on mac4: https://ci.chromium.org/ui/p/flutter/builders/staging/Mac_arm64_staging%20plugin_lint_mac/1351/overview
Please see historical ones (top 200): https://ci.chromium.org/p/flutter/builders/staging/Mac_arm64_staging%20plugin_lint_mac?limit=200

**Comment by jmagman** [comment]
Hmm, it's not picking up Flutter 3.0, the old one is cached that doesn't support arm64
```
[plugin_lint_mac] [STDOUT] stdout: -> Installing FlutterMacOS (2.10.2)
[plugin_lint_mac] [STDOUT] stdout:   > Copying FlutterMacOS from `/Users/swarming/Library/Caches/CocoaPods/Pods/Release/FlutterMacOS/2.10.2-d686a` to `../CocoaPods-Lint-20220526-59852-ln1crj-integration_test_macos/Pods/FlutterMacOS`
```
Suspect these machines need a `pod repo update` run?

**Comment by keyonghan** [comment]
`pod repo update` works. Closed assuming fixed.
