### ISSUE TITLE
[Proposal] extend TimePickerEntryMode with dialOnly, inputOnly

### ISSUE THREAD

**Issue by hikachi** [flutter/flutter#100608]
## Use case

I found out that, material timePicker only  has two enums - TimePickerEntryMode {dial, input} in comparision to datePicker that has four of them - DatePickerEntryMode { calendar, input, calendarOnly,inputOnly}. In keyboardless apps, dialOnly is essential.

## Proposal

Extend TimePickerEntryMode with dialOnly and inputOnly enums so that both pickers could have the same behavior.

**Comment by maheshmnj** [comment]
Hi @hikachi, Thanks for filing the issue. Labeling this issue as  proposal to add `inputOnly` and `dialOnly` enums to [TimePickerEntryMode](https://api.flutter.dev/flutter/material/TimePickerEntryMode.html)


<details>
<summary>minimal code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:test_app/app.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        title: 'Flutter Demo',
        theme: ThemeData(
          primarySwatch: Colors.blue,
        ),
        home: MyHomePage());
  }
}

import 'package:flutter/material.dart';

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {

  Future<void> _incrementCounter() async {
    TimeOfDay? picked = await showTimePicker(
      context: context,
      initialTime: TimeOfDay.now(),
      initialEntryMode: TimePickerEntryMode.dial,
      builder: (BuildContext context, Widget? child) {
        return MediaQuery(
          data: MediaQuery.of(context).copyWith(alwaysUse24HourFormat: true),
          child: child!,
        );
      },
    );
  }

  @override
  Widget build(BuildContext context) {
    return Material(
      child: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            ElevatedButton(
              child: const Text("Button 1"),
              onPressed: _incrementCounter,
            ),
          ],
        ),
      ),
    );
  }
}

```
</details>

**Comment by darrenaustin** [comment]
This is a reasonable proposal. If someone wants to take a stab this, we would certainly welcome a PR. You can look at #76343 for an example of how we added a similar feature to Date Picker.

**Comment by mqkotoo** [comment]
Hi!
Is this problem not solved yet?
please tell me..

**Comment by maheshmnj** [comment]
@mqkotoo  unfortunately no, But pull requests are welcome :)
