### ISSUE TITLE
web: create a widget that exceeds the window size

### ISSUE THREAD

**Issue by laurentbernardin** [flutter/flutter#100662]
I need to build a web app that is larger than the browser window. I can't dynamically generate the content because then the browser print mechanism only picks up the visible portions.
I've tried playing with OverflowBox and inheritedMediaQuery and can (almost) get this to work with the html renderer (but there are painting glitches). No luck with canvaskit: Only the content visible in the window is rendered.

**Comment by darshankawar** [comment]
> I need to build a web app that is larger than the browser window.

Can you elaborate by providing a use case with code sample and what exactly are you trying to achieve ?
