### ISSUE TITLE
Cache flutter tool artifact/support package downloads

### ISSUE THREAD

**Issue by lukef** [flutter/flutter#10066]
Whenever flutter master changes or you update flutter it has to download a variety of support packages. e.g.:

```
Downloading android-x86 tools...                      2.6s
Downloading android-x64 tools...                      2.8s
```

I'm not sure how frequently these packages are changing. If they don't change frequently, it would be good to cache these so that you don't have to wait for them to download each time you want to rebuild the flutter tool.

**Comment by abarth** [comment]
They should be cached.  The key for the cache is in `bin/internal/engine.version`.  They should only download once each time you update the Flutter SDK.

**Comment by Hixie** [comment]
@lukef Do you still see this?

**Comment by Hixie** [comment]
Closing. These artifacts are expected to change any time we update the engine. We cache them the rest of the time.
