### ISSUE TITLE
Error in README.md file of url_launcher plugin

### ISSUE THREAD

**Issue by wmleler** [flutter/flutter#10060]
Go to https://pub.dartlang.org/packages/url_launcher
Scroll down to "Supported URL schemes" and look at the table of common schemes.
The column headers "Action" and "Example" are reversed.

Not sure if we should switch the columns or just the headers.

![screen shot 2017-05-12 at 5 04 29 pm](https://cloud.githubusercontent.com/assets/50357/26020590/199782ae-3735-11e7-8786-260db512d958.png)

**Comment by sethladd** [comment]
Thanks for the feedback.

This is probably an issue with the README of the url_launcher plugin. cc @mit-mit 

@wmleler can you rename this issue to be more specific? Thanks!

Also, @wmleler if you're curious, you can probably fix this by sending over a PR: https://github.com/flutter/plugins/blob/master/packages/url-launcher/README.md

**Comment by mit-mit** [comment]
Good catch, yes this is the readme.md. @wmleler PR most welcome. cc @szakarias
