### ISSUE TITLE
`Mac_arm64_staging native_ui_tests_macos` fails with `PhaseScriptExecution` error

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#100636]
Part of https://github.com/flutter/flutter/issues/87508

[Mac_arm64_staging native_ui_tests_macos](https://luci-milo.appspot.com/raw/build/logs.chromium.org/flutter/led/keyonghan_google.com/e33c752d0157e40e23fe702b1df0818a3d1e7799b294fc1f8aa3ee6fc1fb64d5/+/build.proto)

```
[native_ui_tests_macos] [STDOUT] stderr: ** TEST FAILED **
[native_ui_tests_macos] [STDOUT] stderr: 
[native_ui_tests_macos] [STDOUT] stderr: 
[native_ui_tests_macos] [STDOUT] stderr: The following build commands failed:
[native_ui_tests_macos] [STDOUT] stderr: 	PhaseScriptExecution Run\ Script /Users/chrome-bot/Library/Developer/Xcode/DerivedData/Runner-dshsfrcplzatzpawtbtixpfiwrjv/Build/Intermediates.noindex/Runner.build/Release/Flutter\ Assemble.build/Script-33CC111E2044C6BF0003C045.sh (in target 'Flutter Assemble' from project 'Runner')
[native_ui_tests_macos] [STDOUT] stderr: (1 failure)
```

**Comment by keyonghan** [comment]
/ @cbracken could you please help take a lool?

**Comment by jmagman** [comment]
@keyonghan per https://github.com/flutter/flutter/issues/101721 it looks like this test stopped failing on build and was failing further along due to the Xcode harness crash.  Can this be closed?

**Comment by keyonghan** [comment]
SGTM. Closing.
