### ISSUE TITLE
TextField doesn't register keyboard "enter" as onSubmitted trigger.

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#10061]
it should

**Comment by eseidelGoogle** [comment]
I assume this is via a physical keyboard attached to a fuchsia device?

**Comment by abarth** [comment]
Yes, it's an issue with the new IME integration.  The Fuchsia IME is missing a notion of "action", which we can then wire into our text plugin to call onSubmitted.

/cc @poitch

**Comment by dvdwasibi** [comment]
WE NEED THIS!

**Comment by Hixie** [comment]
@abarth Is this your department?

**Comment by poitch** [comment]
A good part is on me actually. The wiring of onSubmitted could be on @abarth though I might be able to do that part too.

**Comment by eseidelGoogle** [comment]
@apwilson was asking about this today.  Is @abarth still the right assignee?

**Comment by Hixie** [comment]
Current status from Flutter team is that we are not working on this because we believe this has upstream dependencies. Please let us know if this is something we should be dealing with in the near future.

**Comment by apwilson** [comment]
https://fuchsia.atlassian.net/browse/SY-193

**Comment by apwilson** [comment]
@poitch @abarth can you confirm who needs to do something to get this done?

**Comment by abarth** [comment]
I believe Flutter just needs to fill in the implementation of OnAction in this file:

https://github.com/flutter/engine/blob/master/content_handler/runtime_holder.cc#L637

**Comment by Hixie** [comment]
Is there any documentation for what to expect in this API?

**Comment by abarth** [comment]
The interface is defined here:

https://fuchsia.googlesource.com/mozart/+/master/services/input/text_input.fidl#55

Basically, when the IME decides the user has performed one of the enumerated actions, it will call this function to inform you of that fact.

It's analogous to https://docs.flutter.io/flutter/services/TextInputClient/performAction.html, although the Flutter framework has many fewer enumerated actions:

https://docs.flutter.io/flutter/services/TextInputAction-class.html
