### ISSUE TITLE
JIT snapshots can't be found on some platforms when just the assets path is specified.

### ISSUE THREAD

**Issue by akbiggs** [flutter/flutter#100640]
The embedder does not appear to work with JIT snapshots on some platforms. In the [GLFW example on Linux](https://github.com/flutter/engine/tree/main/examples/glfw) (which only sets FlutterProjectSettings.asset_path), we get an error that the Dart VM could not be initialized. With `gn --unopt --build-embedder-examples`:

```
% $ENGINE_DIR/out/host_debug_unopt/embedder_example $ENGINE_DIR/flutter/examples/glfw/myapp $ENGINE_DIR/third_party/icu/common/icudtl.dat 
[ERROR:flutter/runtime/dart_vm_data.cc(18)] VM snapshot invalid and could not be inferred from settings.
[ERROR:flutter/runtime/dart_vm.cc(269)] Could not set up VM data to bootstrap the VM from.
[ERROR:flutter/runtime/dart_vm_lifecycle.cc(84)] Could not create Dart VM instance.
[FATAL:flutter/shell/common/shell.cc(143)] Check failed: vm. Must be able to initialize the VM.
zsh: IOT instruction  $ENGINE_DIR/out/host_debug_unopt/embedder_example 
```

We suspect that this is not an issue on Windows and Mac because of this logic: https://github.com/flutter/engine/blob/main/runtime/dart_snapshot.cc#L72

A hack to fix this issue is to add these two lines [here](https://github.com/flutter/engine/blob/main/shell/platform/embedder/embedder.cc#L1179):

```c++
    settings.vm_snapshot_data_path =
        fml::paths::JoinPaths({settings.assets_path, "vm_snapshot_data"});
    settings.isolate_snapshot_data_path =
        fml::paths::JoinPaths({settings.assets_path,
        "isolate_snapshot_data"});
```

But we should add proper support to embedder.h.

**Comment by chinmaygarde** [comment]
Specifying just the assets using `FlutterProjectSettings.asset_path` depends on the snapshots being present in known locations. I think your workaround to explicitly specify the snapshot assets is the right way to go.

I am going to retitle this issue as the current wording indicates that JIT snapshots aren't supported at all. When it looks like one use of the API is not able to resolve these snapshots.

**Comment by akbiggs** [comment]
Sorry, I'm having a hard time telling from the implementation: what do I set instead of just `assets_path` for JIT snapshots?

**Comment by akbiggs** [comment]
@chinmaygarde @iskakaushik Sorry to bother you. I was wondering how to use the current embedder API to resolve JIT snapshots as Chinmay mentioned above. Is there a way to modify the flutter::Settings using the embedder API? I thought that was private.

**Comment by betrevisan** [comment]
I launched the Flutter engine on Linux both when only specifying the assets path and when also explicitly specifying the snapshots. Both versions launched successfully on my end as the SearchMapping function was able to resolve the VM and the Isolate snapshots (https://github.com/flutter/engine/blob/5540f885a8064f72890d444ede44e3986c0a69c5/runtime/dart_snapshot.cc#L53). The difference was that, when explicitly specifying the snapshots, SearchMapping would return a file mapping whereas, when only the assets path was specified, it would return a symbol mapping  after looking into the native library. Even though both seemed to work fine, I will be implementing a feature to allow users to explicitly specify snapshots. This is also to make the JIT mode be consistent with the existing AOT mode, which allows users to explicitly describe such paths.

**Comment by betrevisan** [comment]
This issue has been addressed in https://github.com/flutter/engine/pull/34244, which allows users to explicitly specify the JIT snapshot locations using the embedder's project args.
