### ISSUE TITLE
Gradel uses FLUTTER_HOME but should use FLUTTER_ROOT

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#10065]
It looks like FLUTTER_HOME is a typo:
https://github.com/flutter/flutter/search?utf8=%E2%9C%93&q=FLUTTER_HOME&type=
and should be FLUTTER_ROOT like all the rest:
https://github.com/flutter/flutter/search?utf8=%E2%9C%93&q=FLUTTER_ROOT&type=

Thanks to @dantup for the report.

**Comment by mit-mit** [comment]
Fixed in https://github.com/flutter/flutter/issues/10100
