### ISSUE TITLE
Deeplink URL scheme should also include domain name (iOS and Android)

### ISSUE THREAD

**Issue by naamapps** [flutter/flutter#100624]
## Steps to Reproduce

Setup url scheme for both ios and android, on android without the host data and on ios like normal:
Android:

      <intent-filter>
        <action android:name="android.intent.action.VIEW" />
        <category android:name="android.intent.category.DEFAULT" />
        <category android:name="android.intent.category.BROWSABLE" />
        <data android:scheme="somescheme" />
      </intent-filter>

ios:

		<array>
			<dict>
				<key>CFBundleTypeRole</key>
				<string>Editor</string>
				<key>CFBundleURLName</key>
				<string>com.scheme.app</string>
				<key>CFBundleURLSchemes</key>
				<array>
					<string>somescheme</string>
				</array>
			</dict>
		</array>

After setup, try to launch the app on both platform with the scheme like this:
somescheme://search

You'll see that the search part is ignored.
If we try to launch the app like this:
somescheme://blabla/search
It will work!

**Expected results:** URL schemes should work out of the box with no issues, without ignoring the first URL section.

**Actual results:** Flutter ignores the first URL section when launching the app from a url scheme.

<details>
<summary>Flutter doctor</summary>

```
[✓] Flutter (Channel stable, 2.10.3, on macOS 12.2.1 21D62 darwin-x64, locale en-IL)
    • Flutter version 2.10.3 at /Users/naamapps/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (3 weeks ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/naamapps/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.65.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.36.0

[✓] Connected device (2 available)
    • SM G998B (mobile) • R5CR214C1LM • android-arm64  • Android 12 (API 31)
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 99.0.4844.83

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

This will be done in series of three prs:

- [x] Migrate Android and iOS to pushRouteInformation method https://github.com/flutter/engine/pull/39372
- [x] Update pushRouteInformation method framework binding to be able to handle route strings in both original and entire uri format https://github.com/flutter/flutter/pull/119968
- [x] Update Android and iOS to send entire uri through pushRouteInformation

**Comment by maheshmnj** [comment]
Hi @naamapps, Thanks for filing the issue. I am quite not sure I understood the issue, When I configure the deeplink I am able to launch the app. 
```
adb shell am start -a android.intent.action.VIEW \
    -c android.intent.category.BROWSABLE \
    -d "somescheme://blabala/search"
```

> You'll see that the search part is ignored. If we try to launch the app like this: somescheme://blabla/search

Could you please clarify what exactly you meant by this?

**Comment by naamapps** [comment]
Hey sorry for the confusion.
What I mean is that the blabla is ignored so the search is used.
But if only search is used, then the launched route will empty.

It is launching the app on both cases but the route is not correct.

somescheme://search - launches the app but the 'search' is ignored, so the search route is not the first route.

somescheme://blabla/search - launches the app and directs to the correct search route. (so the blabla is ignored, and only the second section is being used to determine the initial route of the app).

Hope it's clearer

**Comment by maheshmnj** [comment]
Thanks for the clarification @naamapps, Could you please share a minimal reproducible code sample that shows the route is incorrectly fetched?

**Comment by naamapps** [comment]
Put this in your main.dart.
and then run the adb command you sent earlier, and you'll see that if you run `somescheme://blabala/search` only `/search` will show up and not the full url with the blabla.

And if you run `somescheme://search`, you'll see only `/` as the route!
```
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      onGenerateRoute: (settings) {
        return MaterialPageRoute(builder: (_) {
          return BugPage(path: settings.name ?? "Unknown route");
        });
      },
      title: 'Bug',
    );
  }
}

class BugPage extends StatefulWidget {
  final String path;
  const BugPage({Key? key, required this.path}) : super(key: key);

  @override
  State<BugPage> createState() => _BugPageState();
}

class _BugPageState extends State<BugPage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Text("path: " + widget.path),
      ),
    );
  }
}
```

**Comment by maheshmnj** [comment]
Thanks for the code sample @naamapps, I am seeing a different behavior on Android 

`somescheme://blabla/search` launches `/` on Android and '/search` on IOS

`somescheme://search` launches `/` on Android and  '' on IOS



*AndroidManifest.xml*
```xml
<intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="somescheme" android:host = "" />
            </intent-filter>
```

*Info.plist*
```
<key>FlutterDeepLinkingEnabled</key>
	<true/>
    <key>CFBundleURLTypes</key>
	<array>
		<dict>
			<key>CFBundleTypeRole</key>
			<string>Editor</string>
			<key>CFBundleURLName</key>
			<string>com.scheme.app</string>
			<key>CFBundleURLSchemes</key>
			<array>
			<string>somescheme</string>
			</array>
		</dict>
         </array>	
```

**Comment by naamapps** [comment]
@maheshmnj 
Remove the android:host from android manifest. Only provide the scheme like I mentioned in the original message.

But either way, we can clearly see that something is not working here.

**Comment by maheshmnj** [comment]
@naamapps sorry about that, Please ignore the host I accidentally added it. Even without the host with the below Intent-filters

```
<intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="somescheme"/>
            </intent-filter>
```

Running
```
adb shell am start -a android.intent.action.VIEW \
    -c android.intent.category.BROWSABLE -d "somescheme://blabla/search"
```

still returns `/`

Could you please reconfirm if you are seeing the same behavior on Android?

**Comment by naamapps** [comment]
I do not, I see /search.
Did you add this also to the manifest?
`<meta-data android:name="flutter_deeplinking_enabled" android:value="true" /> `

**Comment by naamapps** [comment]
I don't believe it's the intended behavior.
In ios there can't be an host when using a scheme and it's still missing the first section.
I believe that if there is a host - flutter needs to ignore the first section,
If the host is not included (ios, and host-less android scheme) - flutter should include the whole url.

It's 100% a bug

**Comment by goderbauer** [comment]
@chunhtai

**Comment by artahc** [comment]
I'm also facing this issue, when configuring routes using `go_router`

When I launch `myapp://mypage`, the router is not pushing `mypage`. I'm expecting the router should push `/mypage`

**Comment by chunhtai** [comment]
The first part is domain name, and currently router only gets the path part plus query parameter and segment.

**Comment by chunhtai** [comment]
This come up during the discussion for deeplink, this is currently blocking app to handle deeplink from different domain names

**Comment by kuzawa** [comment]
I am actually having trouble with this behavior as well.
This behavior is not what is expected with custom url schemes and ios.

**Comment by chunhtai** [comment]
Close as done

**Comment by maRci002** [comment]
Thanks for finishing this issue.

I knew [`RouteInformation.location`](https://github.com/flutter/flutter/blob/11c8a626b14efa0c9e3b89bbcaaf148b56903a60/packages/flutter/lib/src/widgets/router.dart#L65) cannot be `null` which is mentioned by #116491
