### ISSUE TITLE
TextField's blinking cursor is not customizable (specifically color).

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#10063]

**Comment by abarth** [comment]
You can control it with the `textSelectionColor` on the `ThemeData`.

**Comment by abarth** [comment]
Feel free to re-open of `textSelectionColor` isn't sufficient for your need.

**Comment by balthild** [comment]
I have `textSelectionColor: Colors.black,` set, and the cursor became black together with the selection background. However, the selected text is still black, then they're invisible.

**Comment by quentinleguennec** [comment]
Same as @balthild here. This is quite annoying to be honest.

**Comment by marcglasberg** [comment]
The cursor itself is actually drawn in `editable.dart`, in the method `_paintCaret` of class `RenderEditable`. Apart from the color we should also be able to edit these constants: 

    const double _kCaretGap = 1.0; // pixels
    const double _kCaretHeightOffset = 2.0; // pixels
    const double _kCaretWidth = 1.0; // pixels

These should all be parameters we could provide in the `TextField` constructor.

This is all very easy to fix, 15 minutes work. It's just creating the parameters and passing them down.

**Comment by zoechi** [comment]
There is some ongoing work in #15571
