### ISSUE TITLE
[Fonts] Icon request: diamond

### ISSUE THREAD

**Issue by supto51** [flutter/flutter#100678]

**Comment by supto51** [comment]
This material Icon not available for flutter. Please add this.

**Comment by danagbemava-nc** [comment]
Hi @supto51, this icon is already available in stable 2.10.3, it can be found under the name `diamond`. The material site just hasn't been updated yet. Closing as this icon already exists. Thank you.

<img src="https://user-images.githubusercontent.com/88313112/159883695-026c90e8-2971-4a11-8aed-760768b85bd2.png" width="250" />

**Comment by supto51** [comment]
@danagbemava-nc Thanks for your information.
