### ISSUE TITLE
Flutter app triggering anti-virus checkup on Windows

### ISSUE THREAD

**Issue by gkovac42** [flutter/flutter#100683]
The Windows .exe file of my Flutter developed application triggers an anti-virus checkup by Avast when it's started. The file comes up clean, but it's not a very user-friendly experience, since I'm planning a public release.

Perhaps I'm barking at the wrong tree, and it's entierly Avast's fault... I'm not a windows developer so I'm kinda in the dark here. What could be the cause and is there anything at all I can do to prevent it?

**Comment by maheshmnj** [comment]
Hi @gkovac42, Thanks for filing the issue. Does this happen with a newly created flutter app from `stable 2.10.3`? 
Also, does Avast provide any additional info about what it finds malicious about the app?  Also, I see that there is a similar issue being tracked for this case https://github.com/flutter/flutter/issues/95167

**Comment by gkovac42** [comment]
Thanks for responding, @maheshmnj. Yes, it happens with the stable 2.10.3 version.

Here's what the Avast log says about it:
```
3/24/2022 1:42:11 PM	Autosandbox candidate: D:\gq_win\build\windows\runner\Release\gq_win.exe
	[Source: ]
	[Opened by: D:\gq_win\build\windows\runner\Release\gq_win.exe]
	[Reason: 0x00020000]
	 --> Result: Sandboxing (no custody)
	 --> Instrumentation: Instrumentation inside sandbox requested
```

**Comment by maheshmnj** [comment]
Thanks for the info labeling this issue for further insights from the team.

cc: @stuartmorgan

**Comment by stuartmorgan** [comment]
Questions about how Avast works and what causes it to trigger for any particular application would need to be directed to its developers.
