### ISSUE TITLE
M1 staging tests fail with `code signing error`

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#100639]
Part of https://github.com/flutter/flutter/issues/87508

These builders are newly enabled on M1 bots, but hit code signing error (though no ios device is needed):

[Mac_arm64_staging flutter_gallery_ios__compile](https://ci.chromium.org/ui/p/flutter/builders/staging/Mac_arm64_staging%20flutter_gallery_ios__compile/365/overview)
[Mac_arm64_staging hello_world_ios__compile](https://ci.chromium.org/ui/p/flutter/builders/staging/Mac_arm64_staging%20hello_world_ios__compile/367/overview)
[Mac_arm64_staging native_ui_tests_ios](https://ci.chromium.org/ui/p/flutter/builders/staging/Mac_arm64_staging%20native_ui_tests_ios/366/overview)
[Mac_arm64_staging module_test_ios](https://ci.chromium.org/ui/p/flutter/builders/staging/Mac_arm64_staging%20module_test_ios/365/overview)  
[Mac_arm64_staging ios_content_validation_test ](https://ci.chromium.org/ui/p/flutter/builders/staging/Mac_arm64_staging%20ios_content_validation_test/368/overview)
[Mac_arm64_staging ios_app_with_extensions_test](https://luci-milo.appspot.com/raw/build/logs.chromium.org/flutter/led/keyonghan_google.com/55d7f92dd27aea6758ff7295016c73072f14e18457fd5aed5c9d54ad987afc15/+/build.proto)

Example:
```
[flutter_gallery_ios__compile] [STDOUT] stderr: Or run on an iOS simulator without code signing
[flutter_gallery_ios__compile] [STDOUT] stderr: ════════════════════════════════════════════════════════════════════════════════
[flutter_gallery_ios__compile] [STDOUT] stderr: No development certificates available to code sign app for device deployment
```

**Comment by keyonghan** [comment]
All these are host only tests, and are not expected for code signing. Shall we skip code signing for all of them @jmagman

**Comment by jmagman** [comment]
It's still signing the apps even though it's not deploying them to any devices.  Can we enable code-signing on these machines to test that it successfully works on M1?

**Comment by keyonghan** [comment]
Five of those tests (`intel prod`) are running against a devicelab bot which support code-signing. Here they are running in host-only mode, and these bots are controlled by chromium team. I am not sure if there is an easy way to enable code-signing there. /cc @godofredoc 

As for `Mac_arm64_staging module_test_ios`, it runs in host only mode now in `intel prod` bot, which does not support codesigning neither. However it passes: https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20module_test_ios/5530/overview. Here is the error message from M1 bot side:
```
[module_test_ios] [STDOUT] stdout: Failed to build iOS app
[module_test_ios] [STDOUT] stdout: Error output from Xcode build:
[module_test_ios] [STDOUT] stdout: ↳
[module_test_ios] [STDOUT] stdout:     2022-03-24 12:31:33.043 xcodebuild[7531:62156] [MT] DVTSDK: Skipped SDK /opt/s/w/ir/cache/osx_sdk/XCode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk; its version (10.15.6) is below required minimum (11.0) for the macosx platform.
[module_test_ios] [STDOUT] stdout:     2022-03-24 12:31:33.043 xcodebuild[7531:62156] [MT] DVTSDK: Skipped SDK /opt/s/w/ir/cache/osx_sdk/XCode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.6.sdk; its version (13.6) is below required minimum (15.0) for the iphonesimulator platform.
[module_test_ios] [STDOUT] stdout:     2022-03-24 12:31:33.044 xcodebuild[7531:62156] [MT] DVTSDK: Skipped SDK /opt/s/w/ir/cache/osx_sdk/XCode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.0.sdk; its version (14.0) is below required minimum (15.0) for the iphonesimulator platform.
[module_test_ios] [STDOUT] stdout:     2022-03-24 12:31:33.044 xcodebuild[7531:62156] [MT] DVTSDK: Skipped SDK /opt/s/w/ir/cache/osx_sdk/XCode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.6.sdk; its version (13.6) is below required minimum (15.0) for the iphoneos platform.
[module_test_ios] [STDOUT] stdout:     2022-03-24 12:31:33.044 xcodebuild[7531:62156] [MT] DVTSDK: Skipped SDK /opt/s/w/ir/cache/osx_sdk/XCode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.0.sdk; its version (14.0) is below required minimum (15.0) for the iphoneos platform.
[module_test_ios] [STDOUT] stdout:     ** BUILD FAILED **
[module_test_ios] [STDOUT] stdout: 
[module_test_ios] [STDOUT] stdout: 
[module_test_ios] [STDOUT] stdout: Xcode's output:
[module_test_ios] [STDOUT] stdout: ↳
[module_test_ios] [STDOUT] stdout:     Writing result bundle at path:
[module_test_ios] [STDOUT] stdout:     	/opt/s/w/ir/x/t/flutter_tools.OjcuTv/flutter_ios_build_temp_dir7nGsIp/temporary_xcresult_bundle
[module_test_ios] [STDOUT] stdout: 
[module_test_ios] [STDOUT] stdout: 
[module_test_ios] [STDOUT] stdout:     Failed to package /opt/s/w/ir/x/t/flutter_module_test.pOgjhl/hello.
[module_test_ios] [STDOUT] stdout:     Command PhaseScriptExecution failed with a nonzero exit code
[module_test_ios] [STDOUT] stdout:     note: Using new build system
[module_test_ios] [STDOUT] stdout:     note: Planning
[module_test_ios] [STDOUT] stdout:     note: Build preparation complete
[module_test_ios] [STDOUT] stdout:     note: Building targets in parallel
[module_test_ios] [STDOUT] stdout: 
[module_test_ios] [STDOUT] stdout:     Result bundle written to path:
[module_test_ios] [STDOUT] stdout:     	/opt/s/w/ir/x/t/flutter_tools.OjcuTv/flutter_ios_build_temp_dir7nGsIp/temporary_xcresult_bundle
```

**Comment by jmagman** [comment]
The compilation error isn't actually printing.  Filed https://github.com/flutter/flutter/issues/100723.

**Comment by jmagman** [comment]
Run test verbosely to see what the compilation error actually is: https://github.com/flutter/flutter/pull/100724

**Comment by jmagman** [comment]
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8818774660845700801/+/u/run_flutter_gallery_ios__compile/test_stdout

`flutter build --release` definitely needs a cert unless there's a `--no-codesign` flag.  For example `flutter_gallery_ios__compile ` does seem to be successfully codesigning on the intel machine:
```
[flutter_gallery_ios__compile] [STDOUT] Executing "/opt/s/w/ir/x/w/recipe_cleanup/tmp9s548q47/flutter sdk/bin/flutter build ios --release --tree-shake-icons --split-debug-info=infos/" in "/opt/s/w/ir/x/w/recipe_cleanup/tmp9s548q47/flutter sdk/dev/integration_tests/flutter_gallery" with environment {BOT: true, LANG: en_US.UTF-8}
...
[flutter_gallery_ios__compile] [STDOUT] stdout: Automatically signing iOS for device deployment using specified development team in Xcode project: S8QB4VV633
```
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8818774660845700801/+/u/run_flutter_gallery_ios__compile/test_stdout

**Comment by keyonghan** [comment]
Ran these tests in devicelab M1 bots with code signing, here are the brief summary:

**Succeeded!**
[Mac_arm64_staging ios_app_with_extensions_test](https://luci-milo.appspot.com/raw/build/logs.chromium.org/flutter/led/keyonghan_google.com/6c7a0504ccf554bfd6bfc5b00ee3fc1cc79bf07674d9274b04adda41e58f74c9/+/build.proto) 

**Hit same issue as `module_test_ios` above:**
[Mac_arm64_staging flutter_gallery_ios__compile](https://luci-milo.appspot.com/raw/build/logs.chromium.org/flutter/led/keyonghan_google.com/e7f7b56ce8c9e43730a29edbe628059252f61b6b894be913492ce90ac279635b/+/build.proto)
[Mac_arm64_staging hello_world_ios__compile](https://luci-milo.appspot.com/raw/build/logs.chromium.org/flutter/led/keyonghan_google.com/86e7be679f425d23c1da6968adce1226cfe767f7bc2abf2085e59c47ccc349be/+/build.proto)
[Mac_arm64_staging ios_content_validation_test](https://luci-milo.appspot.com/raw/build/logs.chromium.org/flutter/led/keyonghan_google.com/d05ae8a5eb113a9f3a9e5c60b021264acfa467bd28daf9f5535fbf2cae857800/+/build.proto)

**Testing failure:**
[Mac_arm64_staging native_ui_tests_ios](https://luci-milo.appspot.com/raw/build/logs.chromium.org/flutter/led/keyonghan_google.com/e5e1b62de3dc7c00607fe2506ccbdea938266550b172ca599fa1770d790d75eb/+/build.proto)
```
 *** If you believe this error represents a bug, please attach the result bundle at /opt/s/w/ir/x/t/flutter_xcresult
[native_ui_tests_macos] [STDOUT] stdout: 
[native_ui_tests_macos] [STDOUT] stderr: 2022-03-24 18:04:23.590 xcodebuild[7114:32508] [MT] IDETestOperationsObserverDebug: 0.011 elapsed -- Testing started completed.
[native_ui_tests_macos] [STDOUT] stderr: 2022-03-24 18:04:23.590 xcodebuild[7114:32508] [MT] IDETestOperationsObserverDebug: 0.000 sec, +0.000 sec -- start
[native_ui_tests_macos] [STDOUT] stderr: 2022-03-24 18:04:23.590 xcodebuild[7114:32508] [MT] IDETestOperationsObserverDebug: 0.011 sec, +0.011 sec -- end
[native_ui_tests_macos] [STDOUT] stdout: 
[native_ui_tests_macos] [STDOUT] stdout: Test session results, code coverage, and logs:
[native_ui_tests_macos] [STDOUT] stdout: 	/opt/s/w/ir/x/t/flutter_xcresult.ahYCyn/result
[native_ui_tests_macos] [STDOUT] stdout: 
[native_ui_tests_macos] [STDOUT] stderr: Testing failed:
[native_ui_tests_macos] [STDOUT] stderr: 	RunnerTests:
[native_ui_tests_macos] [STDOUT] stderr: 		The test runner encountered an error (Failed to establish communication with the test runner. If you believe this error represents a bug, please attach the result bundle at /opt/s/w/ir/x/t/flutter_xcresult. (Underlying Error: Couldn’t communicate with a helper application. Try your operation again. If that fails, quit and relaunch the application and try again. The connection to service named com.apple.testmanagerd.control was invalidated: failed at lookup with error 3 - No such process.))
[native_ui_tests_macos] [STDOUT] stderr: 
[native_ui_tests_macos] [STDOUT] stderr: ** TEST FAILED **
[native_ui_tests_macos] [STDOUT] stderr: 
[native_ui_tests_macos] [STDOUT] stdout: Testing started
```

**Comment by jmagman** [comment]
> Run test verbosely to see what the compilation error actually is: #100724

```
Target aot_assembly_release failed: ProcessException: Bad CPU type in executable
```
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8818412221879492849/+/u/run_module_test_ios/test_stdout

Looks the same as https://github.com/flutter/flutter/issues/100637

**Comment by jmagman** [comment]
@keyonghan I think you already fixed this by installing Rosetta, can this be closed?
