### ISSUE TITLE
[webview_flutter] Expose the allowsLinkPreview property in WKWebView for iOS 

### ISSUE THREAD

**Issue by b099l3** [flutter/flutter#100783]
## Use case

I am using the WebView widget in my application and have noticed that users can long-press links to get a preview, aka, peek and pop view (iOS only feature):
![Simulator Screen Recording - iPhone 13 - 2022-03-25 at 17 17 57](https://user-images.githubusercontent.com/877327/160169909-63893694-b4be-42e5-87b2-d63331ae8df5.gif)

I would like to have control over what WebViews have this property enabled on iOS.

This can be set by using the [allowsLinkPreview](https://developer.apple.com/documentation/webkit/wkwebview/1415000-allowslinkpreview) boolean property on WKWebview.

Some other packages do expose this property like [flutter_inappwebview](https://pub.dev/documentation/flutter_inappwebview/latest/flutter_inappwebview/IOSInAppWebViewOptions/allowsLinkPreview.html) - [allowsLinkPreview](https://pub.dev/documentation/flutter_inappwebview/latest/flutter_inappwebview/IOSInAppWebViewOptions/allowsLinkPreview.html)

However, I feel this is a foundational level functionality for webviews on iOS and noticed that flutter_webviews package doesn't expose this property but does expose other iOS only properties like `gestureNavigationEnabled`.

## Proposal

In a similar manner to the `gestureNavigationEnabled` property I was going to propose adding `allowsLinkPreview` and passing that through to the native WKWebView set up.

**Comment by danagbemava-nc** [comment]
Hi @b099l3, it looks like there's already an existing issue requesting this feature, see #69748. 

Kindly update your PR to reference that issue instead. 

Closing from here as duplicate. 

Thank you

**Comment by b099l3** [comment]
Hi @danagbemava-nc 
Sorry I had a look but was searching on the "[webview_flutter]" term, not to worry.

Updated my PR
