### ISSUE TITLE
Do not print last x lines of stderr from xcodebuild when there's error on iOS

### ISSUE THREAD

**Issue by cyanglaz** [flutter/flutter#100721]
After https://github.com/flutter/flutter/pull/94747 lands, xcode errors are parsed from xcrsults and logged to console. It is redundant to log the the error from stderr again. We can remove the logic that logs the errors from stderr to console in flutter_tools

See: https://github.com/flutter/flutter/issues/98298#issuecomment-1077885970

**Comment by jmagman** [comment]
https://github.com/flutter/flutter/issues/100723 should be addressed first.
