### ISSUE TITLE
Rename ObjC plugins to have `FLT` prefix

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#10073]
Per [recommended conventions in Objective C programming](https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/ProgrammingWithObjectiveC/Conventions/Conventions.html), our classes should have a 3-letter prefix that uniquely identifies their namespace.

e.g. `FLTUrlLauncherPlugin`, etc.

**Comment by tvolkert** [comment]
This is a breaking (but required) change.  We should do this ASAP but wait to publish to pub until after I/O so as to not disrupt the stability of our codelabs, talks, etc.

**Comment by tvolkert** [comment]
Also note that the filenames shouldn't change - just the class names therein.

**Comment by mravn-google** [comment]
The ObjC classes in the flutter/engine framework all start with `Flutter`. Should they change too?

**Comment by tvolkert** [comment]
Probably.

On one hand, it's not as urgent because they at least have some common prefix, albeit not adhering to the standard convention.  On the other hand, we should probably adhere to best practices as laid out by Apple, and if we're gonna change them, the earlier the better since it's a breaking change.

**Comment by tvolkert** [comment]
I think we have to change the plugins no matter what.

I could go either way on the engine classes.  How about anyone that has an opinion either thumbs-up or thumbs-down this comment to provide your vote.  If it's unanimous, there's no need for further discussion.  Otherwise, we'll discuss it :-)

@cbracken @collinjackson @mravn-google @Hixie @chinmaygarde

**Comment by collinjackson** [comment]
I think it's really breaking for common plugin use cases because there won't be any plugin-related native code in the app.

For the engine classes, we could deprecate the current ones around and just have them extend the FLT versions. This would give us lots of time for people to switch over.

**Comment by tvolkert** [comment]
> really breaking

rarely breaking?

**Comment by collinjackson** [comment]
yeah, I edited my comment, there was a dropped "not" :)

**Comment by Hixie** [comment]
Please e-mail flutter-dev warning about this change a little while before landing it. Please ask for feedback saying whether it's going to be a problem.

**Comment by tvolkert** [comment]
https://groups.google.com/forum/#!topic/flutter-dev/52UuFHCDLMA
