### ISSUE TITLE
[Infra] Need an in-depth view into the infra structure and roadmap

### ISSUE THREAD

**Issue by itsjustkevin** [flutter/flutter#100767]
With the complexity around releasing the Flutter SDK, it would be beneficial to the entire team to do the following:

1. Map and diagram the infrastructure for flutter release infrastructure.
2. Surface the EngProd roadmap.

**Comment by CaseyHillers** [comment]
@itsjustkevin do you have a preference on where to publish the roadmap? I could add a section to https://github.com/flutter/flutter/wiki/Roadmap for the release roadmap.

**Comment by CaseyHillers** [comment]
@itsjustkevin I've gone ahead and wrote/presented:
* https://github.com/flutter/flutter/wiki/Release-process
* go/flutter-release-train-slides
* go/flutter-ci-yaml-slides
* Several internal g3docs with overviews of the various systems

I'm marking this as completed, however, if there's more specific documentation we need feel free to file follow up issues to this.
