### ISSUE TITLE
[recipes] Give submit access to release team on release branches

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#100738]
Due to https://github.com/flutter/flutter/issues/100736, the release team needs a way to land CPs. The flutter-release-eng@ should be given permissions to submit to CQ on the non-main branches.

**Comment by CaseyHillers** [comment]
![image](https://user-images.githubusercontent.com/2148558/160049622-6a82e4a0-ba51-49a1-9efa-2c5a9575320a.png)

When updating the refs/meta/config, I got this far, but was getting bad request to add it

**Comment by godofredoc** [comment]
Rather than going directly to owners permission let's identify the minimum required permissions and grant those only.

If I understand correctly flutter-release-eng@ needs to temporarily land cherry-picks that fail presubmits while the led tests get fixed, is this correct?

**Comment by CaseyHillers** [comment]
Correct, in the linked screenshot I was trying to only grant the submit permission on the release candidate branches

**Comment by godofredoc** [comment]
I believe this was fixed already can you please confirm and close?

**Comment by CaseyHillers** [comment]
This was fixed. The release eng team has been able to land CPs to the recipes branches.
