### ISSUE TITLE
Overflow warnings are impossible to disable

### ISSUE THREAD

**Issue by esDotDev** [flutter/flutter#100789]
# Problem
There are often times where we intentionally have overflow by design (example below).

Although this will look fine in production, this spamming of the console, and on-screen clutter negatively impacts developer productivity.

This is disruptive to development because it prevents you from clearly seeing the UI you are working on. You can switch to profile mode, but then you lose the ability for hot reload. Further, Android Simulator does not support profile mode.

It also confuses team members who report errors / log bugs, when they spot overflow in the console, when it was intentional by another developer. Causing a lot of wasted time and repetitive discussions.

Essentially feels like we are fighting the framework here, and it won't co-operate with what we want to do.

# Possible Solution
It would be nice if the developer had the option to tell a parent not throw overflow errors at specific points in the tree.

The idea is not to disable Overflow warnings globally, but to tell specific sub-trees to not display an error.

OR

The framework could properly detect when ClipRect is applied, and then not throw the warning. Currently while it  does tell you do add a ClipRect, this seems to have no effect on whether the warning is thrown or not.

# Example 1
Here we have a panel that, when child is changed, it will size itself to match that child. This requires that, when changing children, some of the content is temporarily clipped. **By design.**

https://user-images.githubusercontent.com/736973/160184624-4c1c176d-9460-4452-8ae4-8c5f1c4fbd14.mp4

Example on dartpad here: https://dartpad.dev/?id=8879b345a2f5eef780fa4840c3a4be30
Gist: https://gist.github.com/esDotDev/8879b345a2f5eef780fa4840c3a4be30

Resulting in this error: 

![image](https://user-images.githubusercontent.com/736973/160734099-b87e32f1-0d3e-4391-81f3-6c607c149803.png)

The suggested fixes of adding a `ClipRect` or a `ListView` are not desired. A `ClipRect` is already in place in the parent, and a `ListView` is not desired as it adds a ton of complications and potential bugs, to an otherwise simple implementation. 

# Example 2
In another situation, we have a visual decorator that is already clipped (otherwise the effect wouldn't work), and we want to spin the circle around, to reveal another title, while the previous title is clipped out of view.
![image](https://user-images.githubusercontent.com/736973/161364300-c06c4421-a0fb-4e5d-9ff7-795af2885792.png)

Again the framework decides it knows best, and aggressively tells us we're doing something wrong, when this really a nice elegant approach, and overdraw is minimal (and clipped regardless, as you can see)

You can also see how this blocks me from seeing the top or bottom of the widget, actively slowing down my development, and preventing me from seeing potential errors. 

# Example 3
Here we use an animated container to hide or reveal a child widget. Normally the child would scale-down here, but our design would prefer that the widget keep its natural size, and instead be cropped out of view.
![4wPkvIqrmB](https://user-images.githubusercontent.com/736973/161613657-735cffa9-c6b7-4f40-88c0-84997efcfc9e.gif)

This can be done simply and robustly with something like:
```dart
AnimatedContainer(
  width: _isOpen: 60 : 0,
  child: ClipRect( 
      child: UnconstrainedBox(
         child: FlutterLogo(50);
      )))
```
But again, the overflow error blocks us from really seeing the finer pts of the animation, unless we run in profile mode. Also weird how we are usng a ClipRect, but the framework complains we should be using a ClipRect.

**Comment by maheshmnj** [comment]
Hi @esDotDev, thanks for filing the issue, I believe you are trying to hide the errors shown from the Flutter framework, I believe [onError](https://api.flutter.dev/flutter/foundation/FlutterError/onError.html) can help you to handle the custom error. 
Please take a look at the below code sample which just prints to the console when the overflow error occurs.

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
  FlutterError.onError = (FlutterErrorDetails details) {
    print('flutter error hidden from console');
    // FlutterError.dumpErrorToConsole(details, forceReport: false);
  };
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: PageOne(),
    );
  }
}

class PageOne extends StatelessWidget {
  const PageOne({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Column(
        children: [
          for (int i = 0; i < 100; i++) Text('$i'),
        ],
      ),
      floatingActionButton: FloatingActionButton(
        child: const Icon(Icons.add),
        onPressed: () {},
      ),
    );
  }
}

class PageTwo extends StatelessWidget {
  const PageTwo({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Builder(builder: (context) {
        return Center(
          child: ElevatedButton(
            child: const Text('Show SnackBar'),
            onPressed: () {
              ScaffoldMessenger.of(context).showSnackBar(
                const SnackBar(
                  content: Text('SnackBar!'),
                  behavior: SnackBarBehavior.floating,
                ),
              );
            },
          ),
        );
      }),
    );
  }
}

```
</details>

**Comment by esDotDev** [comment]
It's actually quite disruptive to development. I either have these giant yellow bars that stop me from accurately dialing in my UI, or I am forced to run it in profile mode, which disables hot-reload, also preventing me from efficiently working on the UI.
![image](https://user-images.githubusercontent.com/736973/160529487-31b59389-ec44-409d-8b88-2ad945ac5bde.png)

**Comment by maheshmnj** [comment]
Thanks for the info, Labelling this issue for further insights from the team.

**Comment by esDotDev** [comment]
> Thanks for the info, Labelling this issue for further insights from the team.

Thx! I have updated the original post to include a running example on dartpad: 
https://dartpad.dev/?id=8879b345a2f5eef780fa4840c3a4be30

**Comment by yasinarik** [comment]
Hello @esDotDev. Thumbs up for this issue.  I have a use case too. I want to use `UnconstrainedBox` without overflow warnings (not in the console nor on screen).

In the source code it says:
```dart
  /// Creates a widget that imposes no constraints on its child, allowing it to
  /// render at its "natural" size. If the child overflows the parents
  /// constraints, a warning will be given in debug mode.
```

- I intentionally use it so that a child widget can be rendered at its natural size.
- That child widget has a parent and the width of the parent can be changed. In this case, I want to decrease the parent size and it should act like a masking widget that masks the natural-sized child widget.

As you can see, the overflow warning is shown no matter I do: **a warning will be given in debug mode**

**Comment by yasinarik** [comment]
@esDotDev Oh if it is solved then it is ok to close the issue. I can open another but would you mind showing a snippet of how `OverflowBox` solved the `Example 3`?

I had quite a lot of experiments with OverflowBox but couldn't make it work.

Thanks for your help :)

**Comment by esDotDev** [comment]
For any child that will overflow, you should be able to do this?
```
OverflowBox(
  maxWidth: double.infinity,
  maxHeight: double.infinity,
  child: someHugeChild,
)
```

**Comment by yasinarik** [comment]
Oh, that didn't work. Because the `OverflowBox` needs constraints from the parent whereas `UnconstrainedBox` does not. Setting `maxWidth: double.infinity` for `OverflowBox` is not the solution for my case because I needed the child to build itself as it is, with its naturally free sizing.

However, I copied and modified the `UnconstrainedBox` into some new widget that has the `showDebugModeOverflowWarning` constructor. I might release it as a package while also adding example use-cases.

Because the `UnconstrainedBox` was already working in my case as expected. The only thing missing was it showed an overflow warning even though **the overflow was intentional**.

You can close this issue safely. Thank you for your time. :)

**Comment by esDotDev** [comment]
Hm, did you try OverflowBox + InstrinsicHeight & InstrinsicWidth?

**Comment by knopp** [comment]
Unconstrained box should not show the warning if it has clip behavior set. Instead of `ClipRect` -> `UnconstrainedBox` why not set clip behavior directly on the `UnconstrainedBox`?

Other than that, I agree that Flutter should have an easier way to disable overflow warnings in certain cases. I usually just end up writing a simple render object in that case, but it would be nice not having to do that.
