### ISSUE TITLE
ArgumentError: Invalid argument(s): 0 double.dart in _Double.clamp

### ISSUE THREAD

**Issue by akindone** [flutter/flutter#100749]
The error trace collected by sentry:
```
ArgumentError: Invalid argument(s): 0
  File "double.dart", line 236, in _Double.clamp
  File "scroll_metrics.dart", line 119, in ScrollMetrics.extentInside
  File "scroll_position.dart", line 523, in ScrollPosition._isMetricsChanged
  File "scroll_position.dart", line 558, in ScrollPosition.applyContentDimensions
  File "draggable_scrollable_sheet.dart", line 631, in _DraggableScrollableSheetScrollPosition.applyContentDimensions
  File "single_child_scroll_view.dart", line 509, in _RenderSingleChildViewport.performLayout
  File "object.dart", line 1852, in RenderObject.layout
  File "proxy_box.dart", line 116, in RenderProxyBoxMixin.performLayout
  File "object.dart", line 1852, in RenderObject.layout
```

flutter version 2.8.1/2.10.3

<img width="576" alt="image" src="https://user-images.githubusercontent.com/17843738/160085246-8925f57c-7eea-4502-9724-1d42f8e8550d.png">

**Comment by maheshmnj** [comment]
Hi @akindone, Can you please share a minimal and complete code sample to reproduce the issue? Additionally, can you check if upgrading to `stable 2.10.3` helps fix the issue?

**Comment by akindone** [comment]
> Hi @akindone, Can you please share a minimal and complete code sample to reproduce the issue? Additionally, can you check if upgrading to `stable 2.10.3` helps fix the issue?

I can't reproduce, but I will upgrade flutter to `stable 2.10.3` see if this helps

**Comment by akindone** [comment]
> Hi @akindone, Can you please share a minimal and complete code sample to reproduce the issue? Additionally, can you check if upgrading to `stable 2.10.3` helps fix the issue?

this issue reproduced for `stable 2.10.3`. It is puzzling that the trace‘s first line `File "double.dart", line 236, in _Double.clamp`, but I can't find  `_Double` in double.dart file at all.

**Comment by akindone** [comment]
I searched the `_Double` in dart repo and found this [reference](https://github.com/dart-lang/sdk/blob/e995cb5f7cd67d39c1ee4bdbe95c8241db36725f/sdk/lib/_internal/vm/lib/double.dart#L236)
So this error throw when upperLimit is smaller than lowerLimit. 
<img width="980" alt="image" src="https://user-images.githubusercontent.com/17843738/162110357-f7f07812-950f-488d-b88b-36242c4919ef.png">

**Comment by maheshmnj** [comment]
Thanks for your research @akindone. Since we do not have more info apart from the stack trace, I am labeling this issue for further investigation from the team.

**Comment by goderbauer** [comment]
The problem is likely the data the flutter framework feeds into `_Double.clamp` (not with the implementation of _Double.clamp), but without a reproducible test case this will be hard to debug.

**Comment by yhong-emporia** [comment]
I am seeing the same issue in my sentry logs as well... Any further information would be very helpful!
```
ArgumentError: Invalid argument(s): 86.0
  File "double.dart", line 236, in _Double.clamp
  File "temperature_controller.dart", line 226, in DesiredTemperatureModel.adjustTemperatureWithinRange
```

```dart
void adjustTemperatureWithinRange(final double minTemperature, final double maxTemperature) {
    if (null != desiredTemperature) {
      desiredTemperature = desiredTemperature!.clamp(minTemperature, maxTemperature);
    }
  }
```

**Comment by Piinks** [comment]
Based on the stack traces, I believe #103559 and #107179 fixed the above instances, but please do let us know if this error message presents again.
