### ISSUE TITLE
[flutter_conductor] Conductor should stop mirroring beta releases to dev

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#100714]
Starting from https://github.com/flutter/flutter/commit/481dfec00e96f01cf709ea196a92e4656ebe53ee, the conductor started mirroring all beta releases to the dev channel so that the dev channel would never be behind beta. However, as of https://github.com/flutter/flutter/pull/97028, users on dev have been auto-migrated to the beta channel when issuing `flutter upgrade`. There have been many dev releases since this change, so it is now safe to remove this code.

(Technically we could just flip the boolean at https://github.com/flutter/flutter/blob/master/dev/conductor/core/lib/src/globals.dart#L31; however, we have no future need of that flag so we should just remove it altogether to simplify the code.)

**Comment by CaseyHillers** [comment]
https://github.com/flutter/flutter/pull/100716 fixed this
