### ISSUE TITLE
[desktop] High memory consumption

### ISSUE THREAD

**Issue by SanekLic** [flutter/flutter#100752]
### Details
It consumes too much memory. What we noticed is that if you remove the linter rules, things get a little better. (Up to 3-4 GB)
I'm pretty sure that the flutter team should expect absolutely the same issues with any example project.

Environment
Flutter 2.8.1
Dart 2.15.1

Target Platform:
macOS(latest stable)

[✓] Flutter (Channel stable, 2.8.1, on macOS 12.2.1 21D62 darwin-x64, locale en-RU)
[!] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] Connected device (3 available)

### Logs
<img width="852" alt="image" src="https://user-images.githubusercontent.com/35465290/160096864-1e5c7228-9462-452b-bb75-d977a60a50ac.png">

**Comment by fryette** [comment]
@scheglov would be nice if you can take a look as you fixed pretty same issue before

**Comment by darshankawar** [comment]
@SanekLic 
There's similar issue open describing your case, https://github.com/flutter/flutter/issues/95092.
Please follow-up in it for further updates.
Closing this as a duplicate.
