### ISSUE TITLE
Add User owned products in InApp Purchase Flutter this feature is available in android default biiling client 

### ISSUE THREAD

**Issue by alihassan143** [flutter/flutter#100743]

**Comment by danagbemava-nc** [comment]
Hi @alihassan143, kindly provide some references so that it's easy for us to investigate what you're referring to. 

Thank you

**Comment by alihassan143** [comment]
https://developer.android.com/google/play/billing/integrate
`    //monthly subscription
    private void loadAllSku() {
        try {
            if (mBillingClient.isReady()) {
                runOnUiThread(() -> {
                    mLoading_pb.setVisibility(View.VISIBLE);
                });

                SkuDetailsParams params = SkuDetailsParams.newBuilder().setSkusList(skuList)
                        .setType(BillingClient.SkuType.SUBS).build();

                mBillingClient.querySkuDetailsAsync(params, (billingResult, list) -> {
                    if (billingResult.getResponseCode() == BillingClient.BillingResponseCode.OK && list != null) {
                        for (Object skuDetailsObject : list) {
                            final SkuDetails skuDetails = (SkuDetails) skuDetailsObject;

                            if (skuDetails.getSku().equals(skuMonthly)) {

                                //get the latest purchases of the user
                                Purchase.PurchasesResult result = mBillingClient.queryPurchases(BillingClient.SkuType.SUBS);
                                List<Purchase> purchaseList = result.getPurchasesList();
                                boolean isOwned = false;
                                if (purchaseList != null) {
                                    for (Purchase purchase : purchaseList) {
                                        String thisSku = purchase.getSku();
                                        if (thisSku.equals(skuMonthly)) {
                                            isOwned = true;
                                            status = 1;
                                            runOnUiThread(() -> setOrderValue(purchase.getOrderId(),
                                                    String.valueOf(purchase.getPurchaseState()),
                                                    String.valueOf(purchase.getPurchaseTime()),
                                                    purchase.getPackageName(),
                                                    skuMonthly));
                                            mLoading_pb.setVisibility(View.INVISIBLE);
                                            break;
                                        }
                                    }
                                }

                                if (!isOwned) {
                                    status = 1;
                                    runOnUiThread(() -> {
                                        setOrderValue("NULL", "NULL",
                                                "NULL", "NULL", "NULL");
                                        mLoading_pb.setVisibility(View.INVISIBLE);
                                    });
                                }
                            }
                        }
                    }
                    //if status =1 mean control goes from the above flow
                    if (status == 1) {
                        mLoading_pb.setVisibility(View.GONE);

                        runOnUiThread(() -> {
                            mOrderId_et.setText(mOrderId_builder.deleteCharAt(mOrderId_builder.length() - 1).toString());
                            mPurchaseState_et.setText(mPurchaseState_builder.deleteCharAt(mPurchaseState_builder.length() - 1).toString());
                            mPurchaseTime_et.setText(mPurchaseTime_builder.deleteCharAt(mPurchaseTime_builder.length() - 1).toString());
                            mPackageName_et.setText(mPackageName_builder.deleteCharAt(mPackageName_builder.length() - 1).toString());
                            mSkuId_et.setText(mSkuId_builder.deleteCharAt(mSkuId_builder.length() - 1).toString());
                        });

                    }
                });
            } else {
                runOnUiThread(() -> {
                    utilsModel.callShortToast(getString(R.string.billing_clinet_not_ready));
                });
            }
        } catch (Exception e) {
            Log.d(TAG, "loadAllSku: " + e.getMessage());
        }

    }
   `

**Comment by danagbemava-nc** [comment]
This should already be possible with the in_app_purchase plugin. Kindly check the documentation [here](https://github.com/flutter/plugins/tree/main/packages/in_app_purchase/in_app_purchase) and the example app for a sample implementation https://github.com/flutter/plugins/tree/main/packages/in_app_purchase/in_app_purchase/example

**Comment by alihassan143** [comment]
Ok i am checking then i will let you know

**Comment by alihassan143** [comment]
Yes i can be able to get the past purchases that is i owned in the playstore successfull

**Comment by alihassan143** [comment]
yes this issue resolved
