### ISSUE TITLE
a11y: Text Content and Functionality Scaling [web]

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#100710]
Text and UI need to stay functional when different types of text spacing are configured in Browser.

Minimus to test with:
Relative to font size: line height (line spacing) to at least 1.5x, paragraph spacing 2x, letter spacing (tracking) 0.12x, and word spacing to 0.16x 

Currently, Flutter does not respect these settings. The visual appearance of text in a Flutter web app did not change to respond to the new setting.

Flutter has support for setting line height (via TextStyle.height, relative to font size), letter spacing (via TextStyle.letterSpacing, in logical pixels), and word spacing (via TextStyle.wordSpacing, in logical pixels), but no build-in support for paragraph spacing.

Implementation: If the engine sends the text scaling settings to the framework (e.g. via [AccessibilityFeatures](https://master-api.flutter.dev/flutter/dart-ui/AccessibilityFeatures-class.html)) we can apply them to Text and SelectableText widgets similarly to how we currently enforce the [boldText accessibility feature](https://github.com/flutter/flutter/blob/e7b7ebc066c1b2a5aa5c19f8961307427e0142a6/packages/flutter/lib/src/widgets/text.dart#L523-L524).

**Comment by yjbanov** [comment]
Deduplicating into https://github.com/flutter/flutter/issues/142712
