### ISSUE TITLE
ParagraphConstraints' optional "width" parameter is required

### ISSUE THREAD

**Issue by jhirth** [flutter/flutter#10076]
While the second line of the documentation states that "width" is required, the signature makes it look like it's optional.

When "width" is omitted, an assertion error is thrown.

**Comment by eseidelGoogle** [comment]
Normally we would add `@required` from package:meta, but we can't in this case since the code in question is in dart:ui.  Presumably there is another way we could tell the analyzer/dartdoc that these arguments are required @devoncarew?

**Comment by eseidelGoogle** [comment]
https://docs.flutter.io/flutter/dart-ui/ParagraphConstraints-class.html is the class in question.  @abarth notes that `@immutable` is another annotation we would use in dart:ui if we could.  We can split out a separate analyzer feature request if that's the correct course of action.

**Comment by Hixie** [comment]
@pq If we put classes identical to the package:meta classes in dart:ui itself, would the analyzer be able to recognise them as equivalent? Maybe we could literally embed package:meta in dart:ui?

Alternatively, we could do what we do with `@override` and `@proxy` and move them from meta to dart:core.

**Comment by bwilkerson** [comment]
So far we have required that everything used in the SDK be defined in the SDK, so we would need to move these annotations into the SDK and then update analyzer to know which annotations it was looking for (possibly supporting both for a short time until user code has been converted).

**Comment by pq** [comment]
@bwilkerson : isn't the requirement just that meta annotations are defined in a library called `meta`?

In `ElementImpl` for example we check:

```dart
  @override
  bool get isFactory =>
      element is PropertyAccessorElement &&
      element.name == _FACTORY_VARIABLE_NAME &&
      element.library?.name == _META_LIB_NAME;
```

Why does it matter where the `meta` library is defined?

(Sorry if I'm missing something obvious!)

**Comment by bwilkerson** [comment]
That's the current way of testing for it, but it seems unlikely that we'd add a 'dart:meta' library named 'meta'. More likely we'd end up putting in 'dart:core' (with the other annotations), in which case our tests would need to be extended.

**Comment by pq** [comment]
Ah.  I see my misunderstanding. (I didn't see the  bit about a `dart:meta` to `meta` equivalency.)

**Comment by dnfield** [comment]
Would it help if we defaulted it to `double.infinity`?  

That still wouldn't help someone who _explicitly_ passes null (until runtime unfortunately, unless they tried to do it as a `const` after https://github.com/flutter/engine/pull/7346 in which case they'd get an unhelpful failure), but we could document that the default is no line breaking and perhaps make the API a bit more friendly until we can actually mark it `@required`.

**Comment by darshankawar** [comment]
The current [documentation](https://api.flutter.dev/flutter/dart-ui/ParagraphConstraints-class.html) states below:

`The only constraint that can be specified is the width.` which makes it required and is also indicated in the signature as below:

```
const ParagraphConstraints({
  required this.width,
}) : assert(width != null);
```

Closing this as resolved. If you disagree or think it was closed by mistake, please write in comments and I'll reopen.
Thanks.
