### ISSUE TITLE
Document pub from Flutter's perspective

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#10070]
We seem to have some confusion.

For example, this dart-only package used the Flutter plugin template and thus has needless obj-c/android code:
https://github.com/perlatus/flutter_zoomable_image/tree/master/ios/Classes

Yet as far as I can tell, never calls that code:
https://github.com/perlatus/flutter_zoomable_image/blob/master/lib/src/zoomable_image.dart

This seems like a reasonable thing for this user to have done, since we don't really talk about packages? :)

**Comment by sethladd** [comment]
So the user journeys is: Create shareable/reusable Flutter code ?

In that article, we can explain what a package is (since we can assume the user doesn't know about dart or pub), what kinds of things can go into packages, how to create a new starter package, how to ensure the ecosystem knows the package is intended for Flutter, and how to mark your package as intended for a particular version/point-in-time for Flutter. Did I miss any other sub-journeys?

**Comment by eseidelGoogle** [comment]
Correct.  The user journey is to create shareable/reusable flutter code.  We explain that today, but only in the context of plugins, and thus I think that's how @perlatus (understandably) ended up with the plugin bits in their dart package.

I believe you've covered all the journeys yes.  @mit-mit

**Comment by perlatus** [comment]
Do you have any examples of non-plugin reusable flutter/UI code? If I start deleting the android/iOS bits I can't get the example to run, which is the same problem I had setting up a dart package from scratch.

**Comment by Hixie** [comment]
https://pub.dartlang.org/packages/flutter_markdown is an example of a non-plugin flutter package.

**Comment by sethladd** [comment]
We have a product question that we should answer before we write this doc.

Q: What is the best _command_ to run to create a new Flutter package (which, may or may not contain plugins for iOS and Android) ?

Options:

* `flutter create` which may actually work great. Need to test.
* `stagehand package-flutter` which doesn't exist but rides off of stagehand
* `flutter create --package [--with-plugins]` which doesn't exist, but could, if vanilla `create` doesn't do what we want

The big question is, should the `flutter` tool provide the package creation magic?

I believe the answer is "yes", so I'd like to first explore if `flutter create` is sufficient (and doesn't require manualy rejiggering for a package with and without plugins).

**Comment by mit-mit** [comment]
I don't think `flutter create` is a good fit. We don't want `android` and `ios` for what should be a "pure-dart Flutter package".

**Comment by sethladd** [comment]
sgtm re: https://github.com/flutter/flutter/issues/10377
