### ISSUE TITLE
BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 61

### ISSUE THREAD

**Issue by crtl** [flutter/flutter#100756]
Ive tried upgrading my flutter app to 2.10.3 but it only results in build issues so I tried creating a new project using `flutter create test_app` to create a new app and test it but it also does not build and outputs:
```
FAILURE: Build failed with an exception.

* What went wrong:
Could not open settings generic class cache for settings file 'D:\dev\projects\flutter_test_app\android\settings.gradle' (C:\Users\Marvin\.gradle\caches\6.7\scripts\1fnwrr8g4rohfp291nvlxj5qe).
> BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 61

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
Running Gradle task 'assembleDebug'...
```

## Steps to Reproduce

1. `flutter create test_app`
2. `cd test_app`
3. `flutter run`

**Expected results:**
Fresh app should run without any problems.

**Actual results:** 
Above error message

<details>
<summary>Code sample</summary>

[https://github.com/crtl/flutter_2_10_test](https://github.com/crtl/flutter_2_10_test)

</details>

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel stable, 2.10.3, on Microsoft Windows [Version 10.0.19044.1586], locale en-DE)
    • Flutter version 2.10.3 at C:\Users\User\fvm\versions\2.10.3
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (3 weeks ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\User\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: D:\dev\jdk-17.0.1\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.1+12-39)
    • All Android licenses accepted.
```

</details>

Solutions ive found on stackoverflow recommended to downgrade jdk version which does not seem to be a good solution.
Also why should I have to downgrade java when upgrading flutter?

**Comment by darshankawar** [comment]
@crtl 
As the error says `Unsupported class file major version 61`, it indicates that the class file tool is trying to load has been compiled by Java 17 or 17+ version.

Currently, it seems  Android toolchain support only classes compiled for Java 11 and hence the error.  For it to run properly, you'll need to use Java 11 jdk version. Also this isn't specific to Flutter, a native android app might throw the same error.

With this, I am going ahead and closing this as it is not specific to Flutter and the change might have to come from Android toolchain that Flutter can consume so that the app can run using Java 17.  
If you disagree, write in comments and I'll reopen it.

**Comment by crtl** [comment]
@darshankawar There is very few to none information available related to the flutter build.
It would be nice when the docs would add information on how the gradle configurations should look and what versions are required because the main USP of flutter is to provide platform abstraction so many people dont have a clue about android specifics with java and gradle. The docs just state to install the JDK but do not mention any version requirements.
Also in my case `flutter doctor` shows everything is ok but the build is still not working.
