### ISSUE TITLE
Process 'command '/opt/homebrew/Caskroom/flutter/2.10.3/flutter/bin/flutter'' finished with non-zero exit value 1

### ISSUE THREAD

**Issue by kayson91** [flutter/flutter#100720]
FAILURE: Build failed with an exception.

* Where:
Script '/opt/homebrew/Caskroom/flutter/2.10.3/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 1102

* What went wrong:
Execution failed for task ':app:compileFlutterBuildRelease'.
> Process 'command '/opt/homebrew/Caskroom/flutter/2.10.3/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 42s
Running Gradle task 'bundleRelease'...                             44,0s
Gradle task bundleRelease failed with exit code 1

**Comment by darshankawar** [comment]
@kayson91 
Can you provide `flutter doctor -v` and `flutter run -v` ? The verbose log will be huge so you can put that in a text file and share it here.

**Comment by yihu5566** [comment]
dongfang@bogon ios % cd ..
dongfang@bogon gwadarpro % flutter doctor -v
[✓] Flutter (Channel stable, 2.10.4, on macOS 12.2.1 21D62 darwin-x64, locale zh-Hans-CN)
    • Flutter version 2.10.4 at /Users/dongfang/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (8 天前), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/dongfang/Library/Android/sdk
    • Platform android-31, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code (version 1.66.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 96.0.4664.55

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
dongfang@bogon gwadarpro %

**Comment by nitish-nanda** [comment]
@darshankawar

Have the same issue can you please check the terminal log of my project

[releaseBuildIssueTerminalLog.txt](https://github.com/flutter/flutter/files/8403099/releaseBuildIssueTerminalLog.txt)

Using the latest gradle version        
classpath "com.android.tools.build:gradle:7.0.1"
distributionUrl=https\://services.gradle.org/distributions/gradle-7.0.2-bin.zip
ext.kotlin_version = '1.6.10'
