### ISSUE TITLE
[Fonts] Icon request: percent

### ISSUE THREAD

**Issue by GinilabDev** [flutter/flutter#100742]

**Comment by danagbemava-nc** [comment]
Hi @GinilabDev, the `percent` icon already exists in stable 2.10.3 under the name `percent`. The material icons site just hasn't been updated yet. Closing as the icon already exists. Thank you

<img width="250" alt="Screenshot 2022-03-25 at 07 04 30" src="https://user-images.githubusercontent.com/88313112/160071095-64460999-8ab4-4a4a-9515-583dce249d36.png">
