### ISSUE TITLE
[url_launcher] UniversalLinks not opened from safari on iPhone

### ISSUE THREAD

**Issue by Tom3652** [flutter/flutter#100763]
On my website (also coded in Flutter web), i am hosting a web page where my mobile app users can reset their password. 
When they ask to reset their password from the mobile app, a dynamic link is generated with a `continueUrl` to go back to the app after the action is completed. 

The user click on the link from his mailbox from his iPhone, it redirects to my website.  
Then he is able to change his password, and if successful i use `launch(continueUrl, forceSafariVC: false, universaLinksOnly: true)` to go back to the app. 

But this never happens...

I have found this #25991 but it's not exactly the same use case and i have tested all of the different configs for `launch` : 

```
launch(continueUrl, forceSafariVC: true);
launch(continueUrl, forceSafariVC: false);
launch(continueUrl, forceSafariVC: false, universalLinksOnly: true)
```
And none of them would redirect back to my app.  
After a looong time debugging the deep link, i am now sure that the issue comes from the `url_launcher` because opening the link from iMessage for example is redirecting back to my app.

## Steps to Reproduce

1. Configure Firebase dynamic links to work with Firebase auth with the domain of your choice
2. Generate a reset password with email link with a custom handler that would be like `https://yourdomain.com/redirect` and a continue url from code : 
3. Build for flutter web the sample code 
4. Add a Firebase hosting configuration to host the empty website
5. Deploy the website
6. Click on the link on the iPhone you have the app installed
7. It should redirect you to the "SafariViewController" if my understanding of what this is is correct (with the "Ok" button in the top left) 
8. It opens your website and goes to the `/redirect` page with the arguments.
9. Wait few seconds and see that you don't get redirected to the app
10. As additional step, you can paste the continueUrl in a `iMessage` conversation and click on it to see that you are indeed redirected to the mobile app.

**Expected results:** 

The url_launcher should open the `universalLink` as stated in the documentation and redirect back to the app.

**Actual results:** 

Nothing happens.

<details>
<summary>Code sample</summary>

This is the Flutter web app (running in the browser) :

```dart
import 'package:flutter/material.dart';
import 'package:url_launcher/url_launcher.dart';

void main() async {
  runApp(MaterialApp(
    initialRoute: "/",
    routes: {
      "/": (ctx) => const Scaffold()
    },
    onGenerateRoute: onGenerateRoute,
  ));
}


MaterialPageRoute? onGenerateRoute(RouteSettings settings) {
  Widget? testPage;
  if (settings.name != null) {
    var uriData = Uri.parse(settings.name!);
    print("Param in query : " + uriData.queryParameters.toString());
    switch (uriData.path) {
      case '/redirect':
        testPage = TestPage(continueUrl: uriData.queryParameters["continueUrl"]!);
        break;
    }
  }
  if (testPage != null) {
    return MaterialPageRoute(
        settings: settings,
        builder: (BuildContext context) => testPage!
    );
  }
  return null;
}

class TestPage extends StatefulWidget {
  final String continueUrl;

  const TestPage({Key? key, required this.continueUrl}) : super(key: key);

  @override
  State<TestPage> createState() => _TestPageState();
}

class _TestPageState extends State<TestPage> {
  @override
  void initState() {
    super.initState();
    print("The continue url is : ${widget.continueUrl}");
    Future.delayed(const Duration(seconds: 5)).then((value) {
      launch(widget.continueUrl, forceSafariVC: false);
    });
  }

  @override
  Widget build(BuildContext context) {
    return Container();
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel stable, 2.10.3, on macOS 12.3 21E230 darwin-x64, locale fr-FR)
    • Flutter version 2.10.3 at /Users/foxtom/Desktop/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (3 weeks ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/foxtom/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code (version 1.65.2)
    • VS Code at /Users/foxtom/Desktop/Visual Studio Code.app/Contents
    • Flutter extension version 3.36.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.3 21E230 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 99.0.4844.83

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
Thanks for the update. I suggest you to follow-up in linked issue for further updates.
Closing this as a duplicate.
