### ISSUE TITLE
Cant set background on fixed BottomNavigationBar.

### ISSUE THREAD

**Issue by markmooibroek** [flutter/flutter#10074]
Is there a way to set the background on a BottomNavigationBar when type is set to `fixed`?

# Example code
[https://gist.github.com/markmooibroek/199f1da3e1f3ae686e4063601bf14ca3](url)

**Comment by eseidelGoogle** [comment]
@HansMuller would know. :)

**Comment by rxlabz** [comment]
@markmooibroek you can change it via the canvasColor property from the themeData

**Comment by markmooibroek** [comment]
Thats a start =) However it requires me to change more than only the BottomNavigationBar background. I think it would be a good addition to make it so that we can alter the background color based on BottomNavigationBar.fixedColor

**Comment by rxlabz** [comment]
maybe you can just create a dedicated theme, and apply it just to the BottonNavigationBar ? 
```
new Theme(data:BNBarTheme, child:new BottomNavigationBar )
```

**Comment by markmooibroek** [comment]
Nice, didn't know that was possible =) That will to the trick

**Comment by jxmorris12** [comment]
this advice helped me, too. thanks!

**Comment by nsharma098** [comment]
@rxlabz It worked man , thanks
