### ISSUE TITLE
empty engine/ci/check_gn_format.py

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#100741]
From the comments it seems like the script was migrated to dart and the file was left empty.

**Comment by godofredoc** [comment]
\cc @gspencergoog can we remove the file?

**Comment by andoriyaprashant** [comment]
@godofredoc can you please elaborate 
I want to fix this issue

**Comment by andoriyaprashant** [comment]
hey @godofredoc can you please checkout my pull request #41397

link - 
https://github.com/flutter/engine/pull/41397
