### ISSUE TITLE
Converting from draft causes CI to rerun checks

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#100717]
When converting a PR away from a draft it causes all the CI checks to rerun.  My flow is to get everything green on a draft PR before converting it to a PR and assigning it to someone for review.  The causes everything to rerun which is wasteful.

**Comment by keyonghan** [comment]
@christopherfujino has this been resolved by your change?

**Comment by christopherfujino** [comment]
Yep, fixed by https://github.com/flutter/cocoon/pull/1895
