### ISSUE TITLE
FlutterActivity is incompatible with apps that need FragmentActivity

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#10072]
Android "best practice" is often to use the v4 support library's [`FragmentActivity`](https://developer.android.com/reference/android/support/v4/app/FragmentActivity.html) because it has a strict superset of the functionality in the Android framework's [`Activity`](https://developer.android.com/reference/android/app/Activity.html) class.  In fact, the only reason not to use `FragmentActivity` is if you need to avoid the binary size increase that goes along with bundling the v4 support library JAR in your app.  However, so many Android apps need that support library anyway that virtually all apps include it (and correspondingly use `FragmentActivity`).

Because that's true for non-Flutter Android apps, many native libraries built on top of the Android APIs deal directly with `FragmentActivity`, assuming that apps won't have a problem with the reliance on the v4 support library.

This poses a problem for Flutter plugin authors.  Since they're calling APIs in various Android libraries, they're often going to be faced with APIs that require a `FragmentActivity`.  Yet, `FlutterActivity` extends `Activity` directly rather than `FlutterActivity` specifically to avoid the dependency on the v4 support library.

The solution thus far (used internally in Google) has been to copy/paste `FlutterActivity` into a version that extends from `FragmentActivity` but is identical in all other ways. This is not only a burden on app developers, but it means:

* They won't benefit from new functionality or bug fixes in the engine's `FlutterActivity`
* They'll suffer more from internal API changes like the move to the `PluginRegistry` APIs

The fact that we don't bundle the v4 support library in the Flutter engine is a good thing.  Rather than going down that road, we can probably make better use of composition in `FlutterActivity` with public classes that can easily be composed into an app-specific `FragmentActivity` subclass.

**Comment by tvolkert** [comment]
FYI @mravn-google @collinjackson

**Comment by tvolkert** [comment]
While a lower priority, solving this would also help apps that want to embed a `FlutterView` in a non-fullscreen activity, since otherwise they'd have to reimplement the `PluginRegistry` API manually.

**Comment by tvolkert** [comment]
This materially affects GoogleSignIn plugin as well, because in order to gain the full benefit of the GMS sign in APIs (such as a user dialog when your GMS Core version is out of date), your activity needs to extend `FragmentActivity`.  At the time of this writing, the GoogleSignIn plugin doesn't require `FragmentActivity`, and so it misses out on a lot of the features of the GMS sign in APIs (it has to opt-out of the auto-managed UI).

Here's a full proposal including how it relates to GoogleSignIn:
  1. Refactor `FlutterActivity` in the engine to be more composable, so that other activity classes can use its functionality without having to extend it.
  2. Write a `FlutterFragmentActivity` that depends on the v4 support library and extends `FragmentActivity`, and publish that (Flutter support library?) to Maven.
  3. Change the GoogleSignIn plugin to require the use of `FragmentActivity` (thus requiring apps that use it to depend on the v4 support library), and point users of it to `FlutterFragmentActivity` (though they won't be required to use it if they prefer to use another `FragmentActivity` subclass).

**Comment by b-strauss** [comment]
I know of some tracking libraries which have their own Activity class that needs to be extended. Would this change also help with that?

**Comment by tvolkert** [comment]
Yep.  See https://github.com/flutter/engine/pull/3748, which adds a `FlutterActivityDelegate` (which could be used by any activity)

**Comment by tvolkert** [comment]
Ok, we now have `io.flutter.app.FlutterFragmentActivity` available for apps willing to take the hit of the v4 support library (1.1M before Proguard).

I'm marking this as fixed; there's a separate task of updating the google_sign_in plugin to use it.
