### ISSUE TITLE
Flutter Benchmark Can't Run in Android12.0

### ISSUE THREAD

**Issue by JsouLiang** [flutter/flutter#100760]
When I use the master branch code to run the flutter benchmark like this
in the folder: `/flutter/dev/devicelab` run this cmd `../../bin/cache/dart-sdk/bin/dart bin/run.dart -t color_filter_cache_perf__e2e_summary`

and this is the error:
```
[color_filter_cache_perf__e2e_summary] [STDOUT] stdout:           
adb: failed to install app/outputs/flutter-apk/app.apk: Failure [INSTALL_PARSE_FAILED_MANIFEST_MALFORMED: Failed parse during installPackageLI: /data/app/vmdl1602685650.tmp/base.apk (at Binary XML file line #35): com.example.macrobenchmarks.MainActivity: Targeting S+ (version 31 and above) requires that an explicit value for android:exported be defined when intent filters are present]
```

**Comment by darshankawar** [comment]
Thanks for the report. I do not have Android 12 phone to verify this but I'll keep it open and label for further insights from the team.

/cc @blasten 

A similar fix was merged : https://github.com/flutter/flutter/pull/98076

**Comment by JsouLiang** [comment]
@darshankawar aha, I saw it, but another benchmark program also need this param, and you can review my pr?

**Comment by stuartmorgan** [comment]
Closing, as the referenced PR was landed.
