### ISSUE TITLE
[Fonts] Icon request: man

### ISSUE THREAD

**Issue by tcccdevops** [flutter/flutter#100739]
thank so much.

**Comment by danagbemava-nc** [comment]
Hi @tcccdevops, the `man` icon already exists in stable 2.10.3 under the name `man`. The material icons site just hasn't been updated yet. Closing as the icon already exists. Thank you

<img width="250" alt="Screenshot 2022-03-25 at 07 01 07" src="https://user-images.githubusercontent.com/88313112/160070663-0cba83c0-5353-4c64-a025-7f72ab917fb3.png">
