### ISSUE TITLE
[Proposal] Update animation simulation to fix restart ballistic animation which is used by NestedScrollView

### ISSUE THREAD

**Issue by MxSoul** [flutter/flutter#100748]
see https://github.com/flutter/flutter/pull/96512 and https://github.com/flutter/flutter/pull/100133
After making these changes, the ballistic animation in the ListView works as expected.

But the NestedScrollView is using _NestedOuterBallisticScrollActivity and  _NestedInnerBallisticScrollActivity instead of BallisticScrollActivity, So these changes won't have any effect on NestedScrollView, we need to do something extra to fix NestedScrollView's sliding animation.

**Comment by Piinks** [comment]
I am closing this issue since the associated changes were not made, so nested scroll view does not need to be updated in this way.
