### ISSUE TITLE
How to survey next Android OS issues

### ISSUE THREAD

**Issue by SShayashi** [flutter/flutter#100740]
# Overview
I investigated how Android 12 and Target SDK 31 affect my flutter app by looking through the related issues one by one. As far as I know,  issues related next Android OS are not summarized like [[iOS Platform - next major OS review]](https://github.com/flutter/flutter/projects/160) project and [[☂️ Support Xcode 12 #60133]](https://github.com/flutter/flutter/issues/60133) issue.  ( [[Mobile - Android next adoption review]](https://github.com/flutter/flutter/projects/133) project collects the next Android OS issues, but the project looks not maintained because the last update date was 2020-11. ) So, flutter app engineers have to survey the next Android OS effect individually. It is inefficient for the flutter community. That is why I create this issue. I would like to know the issue summarizing the next Android OS problems if you know. Otherwise,  I propose summarizing the next Android OS issues in the future.

**Comment by darshankawar** [comment]
@SShayashi 
Although I don't see a project specific to Android OS issues, but take a look at the Flutter's roadmap for this year and see if it helps to give you an idea https://github.com/flutter/flutter/wiki/Roadmap#2022

**Comment by SShayashi** [comment]
@darshankawar 
Thank you for your response, but unfortunately, the Flutter's roadmap seems not helpful for this issue.

The Android OS issues I refer to are like degradation issues when updating the Android OS version, not like what the flutter team describes in the roadmap and actively copes with. For example, 
- #82906
- #86187

I was wondering why only iOS related issues are summarized like #61047. It might be a good idea to summarize Android OS issues like #61047 for flutter communities.

**Comment by darshankawar** [comment]
Thanks for the update and feedback. I am keeping this issue open and labeling for further insights from the team.

/cc @Hixie

**Comment by GaryQian** [comment]
Typically, we update the master channel to use the latest APIs shortly after public release.

As a point of reference, we typically do not find any glaring incompatibilities or breakages, but of course, smaller and more nuanced issues do appear over time.

When a new version is released, you should file an issue to upgrade and tag me if the issue does not exist yet.
