### ISSUE TITLE
DecoratedBox doesn't repaint when it is rebuild with a new BoxDecoration that only differs in backgroundBlendMode

### ISSUE THREAD

**Issue by spkersten** [flutter/flutter#100754]
The `operator==` and `hashCode` methods of `BoxDecoration` are ignoring its `backgroundBlendMode` property.

See: https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/painting/box_decoration.dart#L311-L334

```
[✓] Flutter (Channel unknown, 2.10.2, on macOS 12.3 21E230 darwin-arm, locale en-NL)
    • Flutter version 2.10.2 at /Users/.../flutter
    • Upstream repository unknown
    • Framework revision 097d3313d8 (5 weeks ago), 2022-02-18 19:33:08 -0600
    • Engine revision a83ed0e5e3
    • Dart version 2.16.1
    • DevTools version 2.9.2
```

**Comment by darshankawar** [comment]
@spkersten 
Thanks for the report. It does seem to ignore / not have the `backgroundBlendMode` property. Can you provide a use case wherein you would required `backgroundBlendMode` for `BoxDecoration` ?

**Comment by spkersten** [comment]
The property is already there, I'm not asking for new functionality, just for this existing one to not have a bug. Blend modes are used for all kind of visual effects. Having widgets repaint themselves when one of its properties change is basic flutter-functionality.

**Comment by darshankawar** [comment]
Thanks for the feedback.

**Comment by HansMuller** [comment]
It looks like BoxDecoration's `operation ==` overload doesn't include blendMode. Should be a trivial fix.
