### ISSUE TITLE
Prevent Focus-loss if tapped on specific Button / GestureDetector

### ISSUE THREAD

**Issue by Eerey** [flutter/flutter#100755]
How do i still consume e.g. `onTap` event on **another widget** (e.g. GestureDetector) without stealing the Focus from e.g. a TextFormField?

I **explicitly do not want to lose my focus**, I don't want to get the focus and request the focus from the FocusNode that lost the focus.

![image](https://user-images.githubusercontent.com/7249645/160103059-8d5a202f-6a05-48aa-8430-9740c0ba0f18.png)

**Comment by maheshmnj** [comment]
Hi @Eerey, Thanks for filing the issue. I think it is not possible to have two widgets focused at the same time. There will always be one widget that will have the primary focus. You will have to manage the focus of the widget yourself, I am quite not sure what it means to have two widgets focused at the same time or How should two widgets respond simultaneously considering flutter is single-threaded. In case you want help with switching focus between widgets please try asking for support at https://flutter.dev/community

Closing as this is neither a bug nor a feature request, Incase you disagree feel free to write in the comments and we will reopen it.

Thank you.

**Comment by Eerey** [comment]
Hey @maheshmnj ,
I don't want to have two widgets being focused at the same time.
I want to keep my focus on the TextFormField, even if I press on a specific widget.

For example, think about an `on-screen-keyboard` - you press on it, yet the focus remains the same.

**Comment by Eerey** [comment]
If possible, I request to re-open the ticket.

**Comment by maheshmnj** [comment]
> I want to keep my focus on TextFormField, even if I press on a specific widget.

Can you share a minimal code sample for us to take a look?
