### ISSUE TITLE
Does this code snippet from the Tour of the Framework still work?

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#10082]
From https://flutter.io/widgets-intro/#changing-widgets-in-response-to-input

@mit-mit points out that RaisedButton needs to be inside of Material.

We used this snippet on the new homepage. Do we need to update it?

**Comment by sethladd** [comment]
cc @Hixie I think you wrote these snippets and docs?

**Comment by Hixie** [comment]
Should work fine, assuming it's used inside a Material and a MaterialApp and so forth. It's basically a slight variation on the body of the default app.

**Comment by sethladd** [comment]
I guess we'll have to rely on our error messages being actionable and easy to understand. :)
