### ISSUE TITLE
Error is not highlighted in Android Studio.

### ISSUE THREAD

**Issue by bhanuka96** [flutter/flutter#100881]
Error is not highlighted in Android Studio. How can I solve this?

![Screenshot 2022-03-28 at 12 22 30 PM](https://user-images.githubusercontent.com/34953062/160342264-8b755028-a0e1-4906-b0f4-13d5c6b61c79.png)
![Screenshot 2022-03-28 at 12 20 04 PM](https://user-images.githubusercontent.com/34953062/160342274-3a231273-7438-4f9f-9ada-758d47044bdb.png)

**Comment by maheshmnj** [comment]
Hi @bhanuka96, Thanks for filing the issue. Please ensure that you are using the latest dart and flutter plugins in Android Studio and try restarting the Android Studio. Please do share the output of `flutter doctor -v`

**Comment by maheshmnj** [comment]
@bhanuka96 

> Please ensure that you are using the latest dart and flutter plugins in Android Studio and try restarting the Android Studio.

Can you please confirm you have tried this?

And if this issue happens only in Android Studio I believe it should be filed in [flutter-intellij](https://github.com/flutter/flutter-intellij)

**Comment by bhanuka96** [comment]
@maheshmnj Yes, It's only. I will file in there
