### ISSUE TITLE
[web] bundling CanvasKit,fonts instead of CDN

### ISSUE THREAD

**Issue by lyf571321556** [flutter/flutter#100887]
When the web application is deployed in the Intranet environment, the web application cannot be used normally because some resources in CDN cannot be loaded, such as canvaskit, fonts, etc

**Comment by darshankawar** [comment]
@lyf571321556 
Can you try loading fonts using https://api.flutter.dev/flutter/services/FontLoader-class.html and see if it helps your case ?

**Comment by lyf571321556** [comment]
> @lyf571321556 Can you try loading fonts using https://api.flutter.dev/flutter/services/FontLoader-class.html and see if it helps your case ?
I mean, after the flutter project is built into a web package, and  published to the server , the canvas, fonts and other resources are accessed from fonts googleapis. com  or unpkg.com  instead of from my own server,such as canvaskit-wasm @0.25.1/bin/canvaskit.Wasm and woff2 files etc。

**Comment by darshankawar** [comment]
@lyf571321556 
I think you are hitting https://github.com/flutter/flutter/issues/74934, so please follow-up in it for further updates.
Closing this as a duplicate.
