### ISSUE TITLE
Support --local-engine when for single CPU architecture AOT builds on macOS 

### ISSUE THREAD

**Issue by jason-simmons** [flutter/flutter#100804]
I'm seeing errors when I run `flutter run --local-engine host_profile --profile` on a Mac x64 host using the current engine and flutter_tools.

flutter_tools reports that it can't find `gen_snapshot_x64` or `gen_snapshot_arm64` and that the `FlutterMacOS.framework` binaries are x64 only.

This is related to some of the recent flutter_tools changes for enabling ARM64 support (https://github.com/flutter/flutter/commit/a618ca27a76faa546fe7704215e49b2a871e56db, https://github.com/flutter/flutter/commit/fd3c34c9d4b125b7c6bce473b7ff1bc6bcb0ac27)

@jmagman @cbracken

**Comment by jmagman** [comment]
@cbracken looks like macOS needs to be audited for local engine single-architecture issues. https://github.com/flutter/flutter/blob/a618ca27a76faa546fe7704215e49b2a871e56db/packages/flutter_tools/lib/src/ios/xcode_build_settings.dart#L189-L201

**Comment by jmagman** [comment]
`-dDarwinArchs` shouldn't hard-coded, it should come from `ARCHS`
https://github.com/flutter/flutter/blob/71ec251a59dd1a982107a3233fe134713437009d/packages/flutter_tools/bin/macos_assemble.sh#L73
like this:
https://github.com/flutter/flutter/blob/71ec251a59dd1a982107a3233fe134713437009d/packages/flutter_tools/bin/xcode_backend.dart#L418

**Comment by jmagman** [comment]
Jason's logs also show:
```
[        ] [   +2 ms] Target compile_macos_framework failed: ProcessException: Failed to find "/Users/jsimmons/sky/engine/src/out/host_profile/./gen_snapshot_x64" in the search path.

**Comment by jmagman** [comment]
```
"-dDarwinArchs=x86_64 arm64" 
```
is also incorrect since it shouldn't build both in debug mode.

**Comment by jmagman** [comment]
https://github.com/flutter/flutter/pull/100811 and https://github.com/flutter/flutter/pull/100917 have merged.  The last piece is to fix the `gen_snapshot_x64` vs `gen_snapshot`.
So if you hit this issue on x64, the workaround for now is to symlink `out/host_<variant>/gen_snapshot` to `out/host_<variant>/gen_snapshot_x64`.

**Comment by cbracken** [comment]
I'll patch that bit in the engine build rather than in the tool, as we do for iOS.

**Comment by cbracken** [comment]
Patch is out at https://github.com/flutter/engine/pull/32326.

That said, it's important to note that the correct local engine to point to for macOS builds is a local engine built with `--mac` flag; e.g. `mac_release_unopt_arm64` etc. Host builds will likely work for x64 targets, but not currently for arm64, where an x64 gen_snapshot is built instead, since in host builds the target _is_ the host.

**Comment by jmagman** [comment]
> That said, it's important to note that the correct local engine to point to for macOS builds is a local engine built with `--mac` flag; e.g. `mac_release_unopt_arm64` etc. Host builds will likely work for x64 targets, but not currently for arm64, where an x64 gen_snapshot is built instead, since in host builds the target _is_ the host. 

@cbracken can you update https://github.com/flutter/flutter/wiki/Compiling-the-engine#compiling-for-macos-or-linux to make that clear?

**Comment by cbracken** [comment]
Will do. To be clear, https://github.com/flutter/engine/pull/32326 will get things working with a host build (as well as target builds) right now, but long-term I could imagine things diverging enough that it's no longer the case.
