### ISSUE TITLE
Goldens are not consistent across platforms (mac - linux)

### ISSUE THREAD

**Issue by Kleak** [flutter/flutter#100896]
Today I discovered a strange behavior with goldens.

flutter version on our CI and my mac are 2.10.3

Our CI is running the flutter docker image from cirrusci.
I updated the goldens from my mac and at my surprise the goldens did not match when running the test in the CI.

**Comment by Kleak** [comment]
duplicate of #36667

**Comment by maheshmnj** [comment]
Hi @Kleak, Thanks for filing the issue. Can you please share a minimal and complete sample project for us to take a look?  
I tried to use the sample project posted in the linked issue, But it looks like its taken down.
