### ISSUE TITLE
DraggableScrollableSheet scrolling down after release requires a second drag down to lower the sheet

### ISSUE THREAD

**Issue by mprync** [flutter/flutter#100850]
So the DraggableScrollableSheet works fine when you scroll and release upwards, this causes the sheet to animate up and then the scroll view will begin scrolling based on velocity after touch release.

The same can't be said for the scrolling down. If you scroll down on a list, release before it gets to the first item, it will snap the sheet and a second drag downwards is required to lower the sheet.

Is there a way to remove that behaviour?

**Comment by darshankawar** [comment]
@InFaMoUsZero 
Can you provide `flutter doctor -v` and a minimal reproducible code sample that shows the current behavior you are reporting ?

Thanks.

**Comment by InFaMoUsZero** [comment]
It's not an issue with my Flutter setup, Flutter doctor is all fine.

This issue isn't an actual bug or problem, it's by design BUT, I'm asking how I can override this behaviour.

```js
Widget bottomDetailsSheet() {
  return DraggableScrollableSheet(
    initialChildSize: .80,
    minChildSize: .80,
    builder: (BuildContext context, ScrollController scrollController) {
      return CustomScrollView(
        physics: const ClampingScrollPhysics(),
        controller: scrollController,
        slivers: [
          SliverList(
            delegate: SliverChildBuilderDelegate(
              (context, i) => Column(
                children: [
                  ListTile(
                    leading: CircleAvatar(
                      child: Text('$i'),
                    ),
                    title: Text('List tile #$i'),
                  ),
                ],
              ),
              childCount: 100,
            ),
          )
        ],
      );
    },
  );
}
```

This should reproduce it. Scrolling up has no restrictions. It will screen the sheet up and also continue to scroll the list up even if I have let go of touch. The same cannot be said for scrolling down, the list will scroll down until the first index and then won't scroll the sheet down.

**Comment by darshankawar** [comment]
@InFaMoUsZero 
Are you experiencing this on desktop or on mobile ?
If desktop, please check this link and see if it helps. 

Also, try out below code sample and see if it helps.

<details>
<summary> code sample </summary>

```

import 'package:flutter/gestures.dart';
import 'package:flutter/material.dart';

class MyCustomScrollBehavior extends MaterialScrollBehavior {
  // Override behavior methods and getters like dragDevices
  @override
  Set<PointerDeviceKind> get dragDevices => {
        PointerDeviceKind.touch,
        PointerDeviceKind.mouse,
        // etc.
      };
}

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      scrollBehavior: MyCustomScrollBehavior(),
      home: Scaffold(
        appBar: AppBar(
          title: const Text('DraggableScrollableSheet'),
        ),
        body: SizedBox.expand(
          child: DraggableScrollableSheet(
            builder: (BuildContext context, ScrollController scrollController) {
              return Container(
                color: Colors.blue[100],
                child: ListView.builder(
                  controller: scrollController,
                  itemCount: 25,
                  itemBuilder: (BuildContext context, int index) {
                    return ListTile(title: Text('Item $index'));
                  },
                ),
              );
            },
          ),
        ),
      ),
    );
  }
}

```

</details>

**Comment by InFaMoUsZero** [comment]
> @InFaMoUsZero Are you experiencing this on desktop or on mobile ? If desktop, please check this link and see if it helps.
> 
> Also, try out below code sample and see if it helps.
> 
>  code sample

It’s on mobile. I’m not using a list view. I’m using a sliver list in a custom view list.

**Comment by darshankawar** [comment]
Thanks for the update. Below is the behavior I am seeing while scrolling down and then up and noticed that when it reaches the top, the scroll stops and then again scrolling up, it doesn't animate and shows a white space at the top. Is this a correct interpretation ?


https://user-images.githubusercontent.com/67046386/160613097-141c4a7f-1aba-431c-8a9c-a0cacea66337.mov

**Comment by InFaMoUsZero** [comment]
> 

Thanks for taking the time to look at this.

That experience you're having is different to me, I don't get that problem.

My problem is if you scroll down fast and let go, the list will scroll until the first index and then stop. The sheet won't scroll down with the velocity of the scroll from the scroll controller once the list has finished scrolling.

The scroll up works fine.

Hope that explains what I mean.

**Comment by darshankawar** [comment]
Thanks. I am going to keep this issue open and label it for further insights since I am not sure what's the expected behavior in this case is.

/cc @HansMuller @Piinks

**Comment by Piinks** [comment]
Hey @mprync, looking at this issue it is not currently clear what we can do to resolve it. Are you still experiencing this issue? If so can you provide a minimal but runnable code sample and the output of flutter doctor as requested before?
If you are able to provide images or a video clip of the behavior too that would be very helpful. Otherwise this issue is not currently actionable. Thank you!

**Comment by Mohamed-Fakhry** [comment]
@mprync Did u find a solution for it?
