### ISSUE TITLE
"Waiting for tree to go green" silently failing to land PRs

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#100878]
Several PRs with the "waiting for tree to go green" label have been waiting for several hours with no error message.

**Comment by TahaTesser** [comment]
We've experienced this issue, https://github.com/flutter/flutter/pull/100554 was never merged after `waiting for tree to go green` label was applied until it was manually merged.

**Comment by godofredoc** [comment]
The fix has landed and deployed.
