### ISSUE TITLE
[Proposal]Run Skia operations from Flutter

### ISSUE THREAD

**Issue by fzyzcjy** [flutter/flutter#100828]
## Steps to Reproduce

I have a widget showing an image and some `dart:ui Path`s. The problem is, I need some graphics operations to this combination. For example (as a simplified requirement), I need to subtract the image by the Paths, dilate it (Skia does have a dilate image filter), and combine with the image and Paths, etc.

The problem is, I have not found any way to directly manipulate at the Skia level. I wonder how can I do this? Thanks for any hints!

1. N/A

**Expected results:** 
see above

**Actual results:** 
see above

<details>
<summary>Code sample</summary>

```dart
n/a
```

</details>

<details>
  <summary>Logs</summary>

```
n/a
```

```
no error
```

```
latest flutter
```

</details>

**Comment by maheshmnj** [comment]
Hi @fzyzcjy, Thanks for filing the issue. I am not aware of any such way where we could execute skia operations from flutter. However, I believe we could consider exposing those functions to flutter. Labeling this issue for further insights from the team.

**Comment by chinmaygarde** [comment]
Skia is an implementation detail in the Flutter engine and there are no plans to expose the entire API directly. Closing this as won't-fix.

If you want a specific feature, please file a separate proposal specific to that feature.

**Comment by chinmaygarde** [comment]
Oh, I see you filed https://github.com/flutter/flutter/issues/100830.

**Comment by fzyzcjy** [comment]
> Hi @fzyzcjy, Thanks for filing the issue. I am not aware of any such way where we could execute skia operations from flutter. However, I believe we could consider exposing those functions to flutter. Labeling this issue for further insights from the team. @maheshmnj 

I am willing to contribute. Could you please provide some hints?

**Comment by fzyzcjy** [comment]
Get it. Thanks all the same!
