### ISSUE TITLE
Execution of the command buffer was aborted due to an error during execution. Caused GPU Timeout Error

### ISSUE THREAD

**Issue by Tom3652** [flutter/flutter#100854]
I would like to re open #97910 as it is still happening despite no UI logic is impacted or reloaded when app state becomes inactive.
 
I only send 6 `http` requests inside this method, and there is no warning in the Flutter documentation or anywhere else that we should not do that.

If we should not, i would like to know what are the limitations please because the buffer of all my iPhone's GPU seems overloaded when the app is swiped up to go to the `App Switcher` on iOS.  
This has for effect to completely freeze the phone's UI which is highly undesirable.

Thanks for your understanding

**Comment by darshankawar** [comment]
Closing this and reopening the linked issue.
