### ISSUE TITLE
Misspelled Link for Material App's `showPerformanceOverlay` property

### ISSUE THREAD

**Issue by amaan-0331** [flutter/flutter#100814]
Link for showPerformanceOverlay in Material App widget is documented as 

>    /// Turns on a performance overlay.
>   ///
>   /// See also:
>   ///
>   ///  * <https://flutter.dev/debugging/#performanceoverlay>

This should be changed to 

>   /// Turns on a performance overlay.
>   ///
>   /// See also:
>   ///
>   ///  * <https://flutter.dev/debugging/#performance-overlay>

File Location is

>https://github.com/flutter/flutter/blob/e7f211ebcd217033ce3327f18c600bb4f29030f0/packages/flutter/lib/src/material/app.dart#L590

**Comment by darshankawar** [comment]
Currently the stated link https://docs.flutter.dev/testing/debugging#performanceoverlay takes us to the main page of various ways of debugging apps out of which `performance overlay` is one.

The correct link that will take dev directly to `performance overlay` section of the document is: https://docs.flutter.dev/testing/debugging#performance-overlay which opens below section of the page:

<img width="609" alt="Screenshot 2022-03-28 at 5 01 47 PM" src="https://user-images.githubusercontent.com/67046386/160389121-46cb2319-f8b3-4786-add9-c4b6a8eded8d.png">


nice catch @amaan-0331
