### ISSUE TITLE
[Fonts] Icon request: electric_bolt

### ISSUE THREAD

**Issue by this-is-allan** [flutter/flutter#100873]
put the icon: electric_bolt: https://fonts.google.com/icons?selected=Material+Icons&icon.query=electric_bolt

**Comment by shreykinshu** [comment]
can I work on this issue

**Comment by maheini** [comment]
You can use [flash_on](https://api.flutter.dev/flutter/material/Icons/flash_on-constant.html)

**Comment by guidezpl** [comment]
Duplicate of https://github.com/flutter/flutter/issues/100873
