### ISSUE TITLE
[Android]: Thai vowel characters are not getting deleted using keyboard backspace.

### ISSUE THREAD

**Issue by NuzzGunners** [flutter/flutter#100875]
backspace is not delete only vowels

link preview https://youtu.be/g2Y_wAmQo2Q

**Comment by NuzzGunners** [comment]
![Uploading Screen Shot 2565-03-28 at 09.09.06.png…]()

**Comment by NuzzGunners** [comment]
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.4, on macOS 12.2.1 21D62 darwin-x64, locale en-TH)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.65.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

**Comment by darshankawar** [comment]
@NuzzGunners 
Can you provide a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that shows the behavior ?
Also, are you using Gboard keypad or default keyboard that comes with the device ?
Can you also provide sample thai characters for us to verify along with steps to replicate ?

**Comment by NuzzGunners** [comment]
Is code sample.

import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(useMaterial3: true),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  TextEditingController ctrl = TextEditingController();

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Padding(
              padding: const EdgeInsets.all(80),
              child: TextField(
                controller: ctrl,
              ),
            )
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}

**Comment by NuzzGunners** [comment]
I'm use default keyboard that comes with the device.

**Comment by NuzzGunners** [comment]
Is sample thai characters. 

สวัสดีปีใหม่

**Comment by NuzzGunners** [comment]
@darshankawar

**Comment by darshankawar** [comment]
> This is sample thai characters.
> 
> สวัสดีปีใหม่

So the issue is that these characters are not getting deleted completely  when using backspace ? or only certain chars are deleted and other stay as-is ?

**Comment by NuzzGunners** [comment]
@darshankawar 
Project create by android studio.  textfield backspace delete thai vowels working correct.
link preview  https://youtu.be/tgNhLJjazxg

**Comment by darshankawar** [comment]
@NuzzGunners 
Since I don't understand Thai, can you provide what should be the expected result versus actual result ?

**Comment by NuzzGunners** [comment]
@darshankawar 
![Uploading test.png…]()

**Comment by NuzzGunners** [comment]
@darshankawar 
link preview https://drive.google.com/file/d/1PYijMFsxz43YEOHjlm9ZCkoSD8gJ4Afc/view?usp=sharing

**Comment by darshankawar** [comment]
For reference:

<img width="476" alt="Screenshot 2022-03-31 at 11 33 23 AM" src="https://user-images.githubusercontent.com/67046386/160987105-bc0232ff-c91e-4e96-b15a-236942b3d747.png">

Keeping it open for further insights from the team on this behavior as I am unable to verify this on Android device I tried (S10).

A similar but old issue : https://github.com/flutter/flutter/issues/28962

**Comment by darshankawar** [comment]
@NuzzGunners 
The image you were trying to upload didn't attach completely. Please attach is completely for everyone's reference.

**Comment by NuzzGunners** [comment]
![Uploading test.jpg…]()

**Comment by NuzzGunners** [comment]
@darshankawar
