### ISSUE TITLE
Localization fallback language is incorrectly set due to regeneration of localized files

### ISSUE THREAD

**Issue by prateekmedia** [flutter/flutter#100857]
## Steps to Reproduce

1. Clone https://github.com/prateekmedia/locals_bug_demo
2. Set your localization to French or Polish or any other translation except English and Arabic
3. Create an app with only english and arabic locals
4. Execute `flutter run` on the code sample

**Expected results:** 
The app should be localized to English.

**Actual results:** 
The app is localizing to Arabic.

I think it's happening because when it can't find system local in supported locals list then it just picks up the first one which due to alphabetical order is ar / Arabic

Happened both on Android and Linux platform.

### Suggestion
Add fallback locale parameter to Material app.

## Screenshot (Locale was Spanish)
![Captura de pantalla de 2022-03-29 13-37-31](https://user-images.githubusercontent.com/41370460/160565294-aaf02a91-f172-4e13-9c21-49ab1a4e066b.png)

## Related Issues
Linux: https://github.com/prateekmedia/appimagepool/issues/53
Android : https://github.com/prateekmedia/pstube/issues/23

**Comment by Add00w** [comment]
> ## Steps to Reproduce
> 1. Set your localization to Norwegian Bokmål (nb) or French or Polish
> 2. Create an app with only english and arabic locals
> 3. Execute `flutter run` on the code sample
> 
> **Expected results:** The app should be localized to English.
> 
> **Actual results:** The app is localizing to Arabic.
> 
> ## Related Issues
> [prateekmedia/appimagepool#53](https://github.com/prateekmedia/appimagepool/issues/53) [prateekmedia/pstube#23](https://github.com/prateekmedia/pstube/issues/23)

Could you provide reproducible code?

**Comment by prateekmedia** [comment]
Wait I will try to create a demo repository, till then you can also try adding basic localizations and locals for only English and Arabic and try as I said above.

**Comment by maheshmnj** [comment]
Hi @prateekmedia, Thanks for filing the issue. In order to investigate this issue further we would need a minimal and complete code sample along with the output of `flutter doctor -v`.

**Comment by prateekmedia** [comment]
I think it's happening because when it can't find system local in supported locals list then it just picks up the first one which due to alphabetical order is ar / Arabic

**Comment by prateekmedia** [comment]
You can try running appimagepool or pstube, I tried creating a minimal example but it wasn't happening their and i don't know why.

**Comment by maheshmnj** [comment]
@prateekmedia I looked at your project https://github.com/prateekmedia/appimagepool/ But I don't see any localization class as mentioned in the docs https://docs.flutter.dev/development/accessibility-and-localization/internationalization. Looks like some of the files are missing. Clonging the project seems to show that `AppLocalizations` class is missing

Could you please recheck the project?

**Comment by prateekmedia** [comment]
@maheshmnj AppLocalizations class is generated automatically when you run `flutter pub get`

**Comment by prateekmedia** [comment]
Hey @maheshmnj, I got the bug to reproduced, previously I was not adding supportedLocals so it was not getting reproduced.

**Comment by prateekmedia** [comment]
Here is the minimal repo => https://github.com/prateekmedia/locals_bug_demo

**Comment by prateekmedia** [comment]
@maheshmnj  I know, I have already said this earlier, what's the solution?

**Comment by maheshmnj** [comment]
I am able to reproduce the issue on stable and the master channel. I believe preventing the regeneration of the locale files should help fix the issue. 

Minimal reproducible code sample https://github.com/prateekmedia/locals_bug_demo

More details about the issue can be [found here](https://github.com/flutter/flutter/issues/100857#issuecomment-1081876609)

<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel stable, 2.10.4, on macOS 12.3 21E230 darwin-arm, locale en-GB)
    • Flutter version 2.10.4 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (3 days ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.65.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.37.20220301

[✓] Connected device (4 available)
    • Redmi K20 Pro (mobile) • 192.168.1.2:55555                    • android-arm64  • Android 11 (API 30)
    • iPhone 12 Pro (mobile) • 535317A4-921C-488F-B234-C2CC6D4AE5A1 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.3 21E230 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 99.0.4844.83

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

```
[✓] Flutter (Channel master, 2.13.0-0.0.pre.277, on macOS 12.3 21E230 darwin-arm, locale en-GB)
    • Flutter version 2.13.0-0.0.pre.277 at /Users/mahesh/Documents/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 13d2381109 (6 hours ago), 2022-03-27 21:00:08 -0400
    • Engine revision 559e259c54
    • Dart version 2.17.0 (build 2.17.0-246.0.dev)
    • DevTools version 2.11.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! CocoaPods 1.10.2 out of date (1.11.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin
        usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.65.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.37.20220301

[✓] Connected device (4 available)
    • Redmi K20 Pro (mobile) • 192.168.1.2:55555                    • android-arm64  • Android 11 (API 30)
    • iPhone 12 Pro (mobile) • 535317A4-921C-488F-B234-C2CC6D4AE5A1 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.3 21E230 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 99.0.4844.83

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```
</details> 

cc: @christopherfujino

**Comment by prateekmedia** [comment]
A possible solution would be not to pick the first one, this can be done by adding a fallback locale property which defaults to en-US

**Comment by christopherfujino** [comment]
> A possible solution would be not to pick the first one, this can be done by adding a `fallbackLocale` property to `MaterialApp` which defaults to `en-US`

You're assuming the default should be `en-US`--how that is inherently better than alphabetical first?

**Comment by prateekmedia** [comment]
Ok then do alphabetically first but my comment is still to add `fallbackLocale` to be used otherwise use alphabetically first.

**Comment by Add00w** [comment]
> Here is the minimal repo => https://github.com/prateekmedia/locals_bug_demo
> 
> cc @maheshmnj @Add00w

Hello @prateekmedia , sorry for being late, now I can see your issue fortunately there is a solution to that by using 

> recommended `localeListResolutionCallback`  over localeResolutionCallback
 ``` dart 
localeListResolutionCallback: (deviceLocales, supportedLocales) {
        if (deviceLocales != null) {
          for (final locale in deviceLocales) {
            if (supportedLocales.contains(locale)) {
              return locale;
            }
          }
        }
        return const Locale('en');
      }
``` 

or `localeResolutionCallback`  :                   

 ```dart
 localeResolutionCallback: (deviceLocale, supportedLocales) {
        if (supportedLocales.contains(deviceLocale)) {
          return deviceLocale;
        }
        return const Locale('en');
      }
```

**Comment by prateekmedia** [comment]
Ok if that's the only solution then I think it must be documented.

**Comment by prateekmedia** [comment]
Seriously P5? Every app with localization in arabic will have this bug as a app cannot have all the locals.

**Comment by mmahgoub** [comment]
Is there anyone working on an official solution for this from flutter?

**Comment by cachapa** [comment]
Just ran into this, here are my findings:

### Solution 1

Respect the `Intl.defaultLocale` setting, e.g.

``` dart
Intl.defaultLocale = 'en_US';
```

### Solution 2

If default locale isn't set, use locale of `template-arb-file` in `l10n.arb`.

### Workaround

Force your default language to be at the top of `supportedLocales`:

```dart
MaterialApp(
  (…)
  localizationsDelegates: AppLocalizations.localizationsDelegates,
  supportedLocales: const [
    Locale('en'),
    ...AppLocalizations.supportedLocales,
  ],
  (…)
);
```

Note: I'm not 100% sure there won't be any problems with 'en' appearing twice in that list but it seems to work.

**Comment by FluffyBunniesTasteTheBest** [comment]
Wondering how many bad reviews this one's going to cause...

**Comment by bartekpacia** [comment]
You can set `preferred-supported-locales` in `l10n.yaml`. [Learn more here](https://docs.flutter.dev/accessibility-and-localization/internationalization#configuring-the-l10nyaml-file).

**Comment by prateekmedia** [comment]
@bartekpacia Thanks, will try it out!
