### ISSUE TITLE
Proposal to Create `ImageFilter.dilate`/`ImageFilter.erode`

### ISSUE THREAD

**Issue by fzyzcjy** [flutter/flutter#100830]
## Use case

I need to do some graphics operations to some UI subtrees (combination of images and `Path`s). `ImageFilter.dilate`/`ImageFilter.erode` will be quite useful.

## Proposal

I can make a PR for it, probably just mimic the `ImageFilter.blur`, since skia already has a `dilate`/`erode` in addition to `blur`.

If I made the PR (surely, with enough code quality), will you merge it?

**Comment by darshankawar** [comment]
@fzyzcjy 
Can you provide code sample wherein it shows current limitation and these two methods would help you to achieve the same requirement ?

**Comment by dnfield** [comment]
It still would be helpful if you could add the details @darshankawar requested.

**Comment by fzyzcjy** [comment]
@darshankawar @dnfield Hi sorry for the late reply. 

The example, well, is quite specific to my use case, but since dilate/erode is general method that is very widely used (otherwise it cannot be in skia), I believe other people can need it. In my (simplified) case, I have a Painter painting a Canvas (consisting of images and Paths), and let us suppose it has only black and white output colors. Then, I need to dilate the black pixels.

Surely this cannot be done via blur, since I need dilation, not Gaussian blurring which has different visual effects.

**Comment by fzyzcjy** [comment]
Hi, is there any updates? I am willing to make a PR. Just want to be sure, if Flutter is allowed to accept the PR (of course with sufficient code quality etc), I will start working on it.

**Comment by dnfield** [comment]
I think adding this feature is fine and if you want to take a crack at it go for it.

**Comment by fzyzcjy** [comment]
Thanks, I will do that :)

**Comment by fzyzcjy** [comment]
FYI, I have made PRs for engine and flutter repo.

* https://github.com/flutter/engine/pull/32334
* https://github.com/flutter/flutter/pull/101036

**Comment by fzyzcjy** [comment]
@darshankawar @dnfield Hi I have made the PR and looking forward to merging it!

**Comment by zanderso** [comment]
This is done in the above PRs.
