### ISSUE TITLE
[Fonts] Icon request: move_down

### ISSUE THREAD

**Issue by AurianDurand** [flutter/flutter#100886]
Hello, 
Would it be possible to add the move_down and move_up icons to flutter? 
Thanks in Advance! 
Aurian

**Comment by guidezpl** [comment]
Will be done in https://github.com/flutter/flutter/pull/100885

**Comment by darshankawar** [comment]
Please follow-up in umbrella issue: https://github.com/flutter/flutter/issues/99973
Closing from here.
