### ISSUE TITLE
java.lang.IllegalAccessError after release in play store

### ISSUE THREAD

**Issue by MerdanDev** [flutter/flutter#100821]
## Flutter app crashes after update in play store

I had massive amount of crash at google play console with this type of error: java.lang.IllegalAccessError 😥

About 20% of user had this crash when updated app at play store:

```
java.lang.IllegalAccessError: 
  at androidx.room.v.e (Unknown Source:15)
  at d.h.a.k.e.onUpgrade (:2)
  at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked (SQLiteOpenHelper.java:354)
  at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase (SQLiteOpenHelper.java:250)
  at d.h.a.k.e.c (Unknown Source:4)
  at d.h.a.k.f.N (Unknown Source:4)
  at androidx.room.s.k (Unknown Source:2)
  at androidx.room.s.b (Unknown Source)
  at androidx.work.impl.D.j.b (Unknown Source:9)
  at androidx.work.impl.background.systemjob.b.i (Unknown Source:20)
  at androidx.work.impl.utils.f.a (:1)
  at androidx.work.impl.utils.f.run (Unknown Source:31)
  at androidx.work.impl.utils.k.run (Unknown Source:2)
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1162)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:636)
  at java.lang.Thread.run (Thread.java:784)
```
### History of this trouble ⌚->

I'm having trouble with production app, which has been working for a while in flutter old version without null safety(before).
I have migrate app into null safety version of flutter, and added android 12 compatibility. After that I have added it into release at play store. That was app version 1.3.0 and there wasn't any massive case of crash (released at Feb 21, 2022 6:21 PM Rollout halted on Mar 17, 2022 8:20 PM, zero case of mentioned crash).
In that version of app I had this types of dependencies:
```
  auto_orientation: ^2.2.0
  cached_network_image: ^3.2.0
  connectivity: ^3.0.6
  dio: ^4.0.4
  dio_http_cache: ^0.3.0
  dotted_line: ^3.1.0
  path_provider: ^2.0.8
  firebase_analytics: ^9.0.5
  firebase_messaging: ^11.2.5
  flutter_html: ^2.2.1
  google_mobile_ads: ^1.0.1
  video_player: ^2.2.15
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  photo_view: ^0.13.0
  provider: ^6.0.2
  pull_to_refresh: ^2.0.0
  scrollable_positioned_list: ^0.2.3
  share: ^2.0.4
  shared_preferences: ^2.0.11
  shimmer: ^2.0.0
  sqflite: ^2.0.1
  url_launcher: ^6.0.17
```
After that I made some changes in design pattern and state managment in my app. My app was working without any kind of error in debug mode, I have tested it in couple of devices. There wasn't any crash and rolled out my app at play store with version name 2.0.0, (released at Mar 17, 2022 8:20 PM Replaced on Mar 19, 2022 9:39 PM, 13.7K case of before mentioned crash till today, started rollout at 40% and I haven't thought it was big problem, after one day increased into 100%) in which I had this types of dependencies:
```
  auto_orientation: ^2.2.0
  cached_network_image: ^3.2.0
  chewie: ">=1.1.0 <1.1.1"
  connectivity_plus: ^2.2.1
  equatable: ^2.0.3
  dio: ^4.0.4
  dio_cache_interceptor: ^3.2.6
  dio_cache_interceptor_hive_store: ^3.1.1
  ferry: ^0.10.4
  firebase_analytics: ^9.0.5
  firebase_messaging: ^11.2.5
  flutter_html: ^2.2.1
  provider: ^6.0.2
  google_mobile_ads: ^1.0.1
  hive: ^2.0.5
  path_provider: ^2.0.9
  photo_view: ^0.13.0
  pull_to_refresh: ^2.0.0
  scrollable_positioned_list: ^0.2.3
  share_plus: ^3.0.5
  shared_preferences: ^2.0.13
  shimmer: ^2.0.0
  url_launcher: ^6.0.20
```

After that I had panic and halted that release. And I have released into productuion previous release with version name 1.3.1, because it hasn't this type of crash.
Unfortunatly this version of app had plenty amount of same crash type(released at Mar 19, 2022 9:39 PM Replaced on Mar 25, 2022 3:01 PM, rollout at 100% because avoid previous crash but it was useless).
Some kind of cleaned app storage or reinstalling helped in most of phones. After that I thought if I clean app directories and cache date from app side, it won't crash and released 2.0.1 version(from Last updated Mar 25 3:01 PM till now, rollout at 20%, 600 case of crash till submit of this issue) but it wasn't succesfull.

### flutter doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.10.3, on Microsoft Windows [Version 10.0.22000.493], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components       
[√] Android Studio (version 4.1)
[√] VS Code (version 1.65.2)
[√] Connected device (3 available)
[√] HTTP Host Availability
```

#### What do I expect from app:
1. App without this kind of crash in production (if I had this type of crash in debug mode it was way better)
2. Any kind of solution to avoid this crash.
3. What was wrong with it.

If triage team thinks this is not releated to flutter, can close this issue but provide me to solve this issue in releated area. 
Before I had send issue into play console devs and they mailed me couple of links about java error documentation and about crashes but I haven't found any kind of solution there are and in entire internet. If you have question about why I wrote this issue in flutter repo, cause of that is I'm flutter developer and I could solve flutter releted issues in project but I'm not able to solve this because it's more native(android)<->flutter thing🤷‍♂️.

**Comment by darshankawar** [comment]
> java.lang.IllegalAccessError: 
>   at androidx.room.v.e (Unknown Source:15)
>   at d.h.a.k.e.onUpgrade (:2)
>   at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked (SQLiteOpenHelper.java:354)
>   at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase (SQLiteOpenHelper.java:250)
>   at d.h.a.k.e.c (Unknown Source:4)
>   at d.h.a.k.f.N (Unknown Source:4)
>   at androidx.room.s.k (Unknown Source:2)
>   at androidx.room.s.b (Unknown Source)
>   at androidx.work.impl.D.j.b (Unknown Source:9)
>   at androidx.work.impl.background.systemjob.b.i (Unknown Source:20)
>   at androidx.work.impl.utils.f.a (:1)
>   at androidx.work.impl.utils.f.run (Unknown Source:31)
>   at androidx.work.impl.utils.k.run (Unknown Source:2)
>   at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1162)
>   at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:636)
>   at java.lang.Thread.run (Thread.java:784)

There are no Flutter frames in the stack, so this seems to be coming from native Android and not Flutter. Yes, native code can crash Flutter, but we would need proper stacktrace that has Flutter before we can analyze and conclude that due to Flutter you are seeing crash, but currently we can't say that.





> java.lang.IllegalAccessError: 
>   at androidx.room.v.e (Unknown Source:15)
>   at d.h.a.k.e.onUpgrade (:2)
>   at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked (SQLiteOpenHelper.java:354)
>   at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase (SQLiteOpenHelper.java:250)

This seems to indicate that app doesn't have proper permission to read and write from the database and hence it could be throwing the access error. So you need to double check and confirm if there are proper permissions for the app to interact with the db and check if any third party plugin you are using (ex: sqflite) has any compatibility issues.

Currently, we can't conclude from the logs whether this is happening due to Flutter or not as the crash seems to be coming from native. You'll also need to go through the third party plugins you are using since most of them uses native code and see if there's anything that could be causing the crash.

**Comment by MerdanDev** [comment]
I think that only *cached_network_image->flutter_cache_manager->sqflite* uses sqlite, but before it worked without any similar crash, about 10% users who updated app had that crach, other haven't had crash. I have searched for similar issue in that dependencies' github repos but couldn't found something similar. And I think this type of permission given by default (internal storage, for app directories)

![crashes](https://user-images.githubusercontent.com/70772623/160369325-21c73f79-4e05-4ef3-b04e-e70a5eb0dcbd.png)

In this image(crashlytics of last version) shows what kind of phones, android versions and models cought crash. All of them after update, I think.

I had exact same model phone after update didn't crashed but in crash list I have found some model phone in which app crached after update. How it's possible that some devices don't give access and some devices can give access 🤷‍♂️?

Yes sometimes cleaning app storage or reinstalling can solve problem but one user said even it haven't helped.

And if this crash will appear next updates it going to be the worst experience for my users.

**Comment by MerdanDev** [comment]
> @MerdanDev You are using lot of third party plugins through which the error could be coming, but in order to properly address it, we would need a reproducible use case or pattern that leads to such crash.

Okey @darshankawar I will do some tests in google console, if I will find any solution then I will write about it and close it. If you can give any advise to make proper tests it will be great!

**Comment by jayjah** [comment]
@MerdanDev I just want to point out that  you are getting an java error, which may be related to your change to support Android 12. The android error relates to an access to an unknown property or method of a java class, see here:[android docs](https://developer.android.com/reference/java/lang/IllegalAccessError). I think you changed the compile- and target version in your build.gradle file as well to support android 12. I suggest you to check your proguard file and maybe you need to adjust it accordingly to the room api.

**Comment by MerdanDev** [comment]
I have meant by support for android 12 is just adding **android:exported="true"** in android/app/src/mani/AndroidManifest.xml.

> I think you changed the compile- and target version in your build.gradle file as well to support android 12.
Yes, before they was set manually, but in last versions of app it was set automatically like:

**Comment by MerdanDev** [comment]
I forget about mentioning that abdroid 12 support was added in 1.3.0 version and it worked without similar crash. After that I haven't had any change in app/build.gradle, build.gradle, AndroidManifest.xml files in the next versions of app(2.0.0, 1.3.1, 2.0.1)

**Comment by darshankawar** [comment]
@MerdanDev 
Regarding `java.lang.IllegalAccessError: `, the javadocs for the same states below:

```
`Thrown if an application attempts to access or modify a field, or to call a method that it does not have access to.

Normally, this error is caught by the compiler; this error can only occur at run time if the definition of a class has incompatibly changed.`
```

https://developer.android.com/reference/java/lang/IllegalAccessError

So please check the classpath and see if it is leads you to a probable root-cause.

**Comment by darshankawar** [comment]
> If you think it is not flutter issue just redirect me into somewhere it's possible to solve and I will close issue.

I do think this may not be Flutter issue because there's no Flutter frames in the stacktrace. You can ask this on support channels like StackOverflow or in Android community to see if it helps. I'll close for now. If you disagree or come back with proper way to replicate it in Flutter, write in comments and I'll reopen it.
