### ISSUE TITLE
Flutter infra releases JSON is not updated for stable 2.10.4

### ISSUE THREAD

**Issue by helinanever** [flutter/flutter#100883]
The JSON files for Flutter version data are not updated with the latest stable hotfix `2.10.4`. Therefore, the update is not reflected in [Flutter docs](https://docs.flutter.dev/development/tools/sdk/releases?tab=windows) either. The `2.10.4` [tag](https://github.com/flutter/flutter/releases/tag/2.10.4) was pushed 3 days ago.
https://storage.googleapis.com/flutter_infra_release/releases/releases_macos.json
https://storage.googleapis.com/flutter_infra_release/releases/releases_windows.json
https://storage.googleapis.com/flutter_infra_release/releases/releases_linux.json

**Comment by TahaTesser** [comment]
cc: @CaseyHillers @christopherfujino

**Comment by CaseyHillers** [comment]
Unfortunately the weekend got in the way of this release. When @itsjustkevin gets the packaging builds green this will be fixed

**Comment by godofredoc** [comment]
This is fixed, please reopen if you still don't see the version in the Flutter Webpage.
