### ISSUE TITLE
Correction in flutter app tutorial @ codelab

### ISSUE THREAD

**Issue by jithuraj** [flutter/flutter#100960]
It is my first time opening an issue.
I was learning flutter [flutter codelab turorial](https://codelabs.developers.google.com/codelabs/first-flutter-app-pt2#3)

the codelab tutorial is not working, I found it is diffrent from its [source code on github](https://github.com/flutter/codelabs/blob/master/startup_namer/step5_add_icons/lib/main.dart)

Sorry if I am wrong :no_mouth:

**Comment by maheshmnj** [comment]
Hi @jithuraj, Thanks for filing the issue. Looks like the source code is not properly linked clicking on source code in step4 points to source code in step 5.

cc: @domesticmouse

**Comment by jithuraj** [comment]
Hi,
Thanks for your reply.
And there is no `_buildRow(WordPair pair)` method in source code as mentioned in the tutorial.

**Comment by domesticmouse** [comment]
This should now be fixed
