### ISSUE TITLE
Several memory benchmarks running, but not reporting results to SkiaPerf

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#100971]
For example flutter_gallery__back_button_memory is running:

https://ci.chromium.org/p/flutter/builders/prod/Linux_android%20flutter_gallery__back_button_memory

but results are not showing up in SkiaPerf (scroll right for the recent results)

https://flutter-flutter-perf.skia.org/e/?begin=1647625818&end=1648529864&keys=Xe83fe66d2e1be0ef0db6e9a76ac448ba&requestType=0&xbaroffset=28046

**Comment by zanderso** [comment]
Here is another missing results: https://flutter-flutter-perf.skia.org/e/?begin=1647910818&end=1648529864&keys=X0de92a4c17ec94099511c0e292b609c7&requestType=0&xbaroffset=28088m again scroll all the way to the right.

Bumping this up since this seems a bit more widespread.

**Comment by zanderso** [comment]
I think I maybe see what happened. Some properties of the benchmarks changed, causing them to be reported as a different series? It looks like some of them pick up again here:

https://flutter-flutter-perf.skia.org/e/?begin=1648251014&end=1648529864&keys=X01b9c29424152ba00a25ea0f01bb6a1d&requestType=0&xbaroffset=28102

@keyonghan @godofredoc I thought we had these sorts of changes behind us?

**Comment by zanderso** [comment]
The host OS version isn't really relevant to benchmarks running on devices. Can we exclude it from the tags on the benchmarks, so that the updates don't affect what appears (and what SkiaPerf analyzes) as a single series?

**Comment by zanderso** [comment]
(Setting aside that the bots updated automatically, which is also kind of terrifying.)

**Comment by godofredoc** [comment]
This was a minor version update from 10.11 to 10.12 which usually means security patches or important fixes. Should we relax the query on skia perf to use only the major version? e.g. Debian 10

I would expect major versions upgrades to be coordinated and communicated but minor versions updates to be fully automated.

**Comment by keyonghan** [comment]
Removing os version will help.

**Comment by godofredoc** [comment]
CL has been submitted, waiting for validation to close

**Comment by keyonghan** [comment]
Could you use https://flutter-flutter-perf.skia.org/e/?begin=1648066823&end=1648829470&queries=host_type%3Dlinux%26sub_result%3D99th_percentile_layer_cache_memory%26test%3Dhome_scroll_perf__timeline_summary&requestType=0 instead, without filtering the host_version?

But there is no easy way to adjust the alerts, as they are based on specific tags.

**Comment by keyonghan** [comment]
Closing as this is WAI, and removing `host_version` has landed to skip unnecessary effect.
