### ISSUE TITLE
Black screen displayed briefly on iOS when app launches

### ISSUE THREAD

**Issue by gavindoughtie** [flutter/flutter#10099]
Launch an iOS application with a light-colored launch screen storyboard and a light-colored home view. Note that a frame or two of total black is shown between the launch screen and the initial Flutter view. 

This is my workaround for now, in the app delegate:

```objc
- (BOOL)application:(UIApplication *)application
    didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
    // Override point for customization after application launch.
    FlutterViewController *controller = (FlutterViewController*)self.window.rootViewController;
    controller.view.backgroundColor = [UIColor whiteColor];
    [self.window makeKeyAndVisible];
    return YES;
}
```

**Comment by eseidelGoogle** [comment]
I suspect https://github.com/flutter/flutter/issues/8127 is related?

**Comment by gavindoughtie** [comment]
This is a duplicate of https://github.com/flutter/flutter/issues/8127 closing

**Comment by zfha** [comment]
how to solve? @gavindoughtie
