### ISSUE TITLE
Rename dependency `ios_signing` to `apple_signing`

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#100910]
In addition to devicelab tests, host only tests need code signing as well to pass through.
Host only bots are maintained by chromium team where code signing is not easy to control.
A workaround is use devicelab bots run these host only tests via ios code signing.

To avoid confusion, we need to update ios_signing to apple_signing to cover both cases.

This needs changes in infra config, .ci.yaml builder definitions, and recipes dependency module.

**Comment by godofredoc** [comment]
There are so many concepts here that I'll try to explain:

* [.ci.yaml](https://github.com/flutter/flutter/blob/master/.ci.yaml) is the file that contains the build/test definitions
* [ios_signing dependency](https://github.com/flutter/flutter/blob/master/.ci.yaml#L127) refers to this entry in .ci.yaml
* [dependencies module](https://cs.opensource.google/flutter/recipes/+/main:recipe_modules/flutter_deps/api.py;l=454)

The workflow is the following:

* A scheduler reads .ci.yaml and triggers a build
* The builds delegates execution to a recipe. In this case to the [flutter drone recipe](https://cs.opensource.google/flutter/recipes/+/main:recipes/flutter/flutter_drone.py)
* The recipe runs steps in sequence using [RunSteps](https://cs.opensource.google/flutter/recipes/+/main:recipes/flutter/flutter_drone.py;l=57) as the entry point.
* Recipe gets the [dependencies property](https://cs.opensource.google/flutter/recipes/+/main:recipes/flutter/flutter_drone.py;l=71) as passed by the scheduler from .ci.yaml configuration
* [Dependency steps](https://cs.opensource.google/flutter/recipes/+/main:recipes/flutter/flutter_drone.py;l=72) are executed from according to the dependencies property

**Comment by drewroengoogle** [comment]
Thank you both for all of the details!

Does the method need to be renamed to `app_signing` or `apple_signing`? It looks like the title is different from the description, so I wanted to double check.

**Comment by keyonghan** [comment]
> Does the method need to be renamed to app_signing or apple_signing? It looks like the title is different from the description, so I wanted to double check.

Let's use `apple_signing`. Updated the description.

**Comment by godofredoc** [comment]
To make it a non breaking change we probably want to keep `ios_signing` pointing to the new method add and new entry `apple_signing`.

We can also add a TODO to remove ios_signing in two months from now.
