### ISSUE TITLE
Duplicate class com.google.android.exoplayer2.ui.DownloadNotificationHelper found in modules jetified-exoplayer-core-2.17.0-runtime (com.google.android.exoplayer:exoplayer-core:2.17.0) and jetified-exoplayer-ui-2.15.1-runtime (com.google.android.exoplayer:exoplayer-ui:2.15.1)

### ISSUE THREAD

**Issue by sadaqatdev** [flutter/flutter#100948]
Duplicate class com.google.android.exoplayer2.ui.DownloadNotificationHelper found in modules jetified-exoplayer-core-2.17.0-runtime (com.google.android.exoplayer:exoplayer-core:2.17.0) and jetified-exoplayer-ui-2.15.1-runtime (com.google.android.exoplayer:exoplayer-ui:2.15.1)

**Comment by darshankawar** [comment]
@sadaqatdev 
The error indicates a conflict between video_player and any other plugin that you are using wherein both the plugins seems to be using exoplayer. Can you double check all your plugins in `pubspec.yaml` and see if whichever you are not using, you can remove it and see if it helps ?

See this for your reference: https://github.com/driftboat/flutter_zoom/issues/15#issuecomment-979940162

**Comment by takuro-kira** [comment]
I encountered same issues yesterday.
In my case it was conflict with assets_audio_player.
I avoided this issues by specifying video_player to 2.2.17.
I hope it helps.

**Comment by sadaqatdev** [comment]
solver by using I avoided this issues by specifying video_player to 2.2.17.
