### ISSUE TITLE
DeviceLab win2 and win3 dead for weeks

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#100998]
<img width="797" alt="Screen Shot 2022-03-29 at 2 55 19 PM" src="https://user-images.githubusercontent.com/54558023/160713715-5ebd0f1b-5288-4a4c-87e3-664fab952c10.png">

Probably related to salt provisioning issue.

**Comment by keyonghan** [comment]
@yusuf-goog could you help take a look?

**Comment by yusuf-goog** [comment]
Password needed update on win-2 and win-3. 

Win-3 is now running.

Win-2 is having some cert issues, where the salt state is failing to update the cert.

**Comment by yusuf-goog** [comment]
Updated salt states, and changed system time which was off by >5 mins.

win-2 is now up and running.
