### ISSUE TITLE
Check LICENSE in flutter/plugins

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#10098]
Some issues I saw by randomly browsing the repository:
* Some LICENSEs attribute copyright to the Flutter authors, others to the Chromium authors.
* Some code files are missing a license header
* Formatting of LICENSE files are inconsistent

/cc @mit-mit @Hixie

**Comment by mit-mit** [comment]
Regarding LICENSE, is the one in the template repo not the right one?
https://github.com/flutter/oss_project_template

**Comment by Hixie** [comment]
@sethladd can probably comment on this.

**Comment by mit-mit** [comment]
@sethladd we need to get this resolved. Our templates in https://github.com/flutter/oss_project_template say `the Flutter project authors`, but various other files use `Chromium`.

**Comment by Hixie** [comment]
This isn't something that matches our current priority buckets, so I'm not tracking this in the June project, but please let me know if I can help with this as I agree it is important to fix soon.

**Comment by sethladd** [comment]
Let's change our oss_project_template over to Chromium Authors.

**Comment by sethladd** [comment]
https://github.com/flutter/oss_project_template/pull/7 updates the template project

**Comment by mit-mit** [comment]
Looks like @tvolkert fixed the headers in https://github.com/flutter/plugins/pull/104?

I created https://github.com/flutter/plugins/pull/213 for the LICENSE files part, please review

**Comment by mit-mit** [comment]
I think this has been fixed now, closing
