### ISSUE TITLE
skia-gold should not run on release branches

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#100916]
See https://github.com/flutter/engine/pull/32299

Gold should not run on release branches as it is not actionable.

Per @Piinks this looks to be a configuration issue as it correctly no-ops on flutter/flutter, but has issues on flutter/engine

**Comment by mdebbar** [comment]
How does flutter/flutter detect that it's running on a release branch?

**Comment by Piinks** [comment]
I think the bot comment @CaseyHillers is referring to in the linked PR is from the Gold service. It was a long time ago that we hit this in flutter/flutter, so I don't quite remember. Since the comment is from the Gold bot and not the flutter bot, it may just need to be configured on Gold's side.

**Comment by mdebbar** [comment]
The only difference between the configs of [flutter/flutter](https://skia.googlesource.com/buildbot/+/refs/heads/main/golden/k8s-instances/flutter/flutter-periodictasks.json5) and [flutter/engine](https://skia.googlesource.com/buildbot/+/refs/heads/main/golden/k8s-instances/flutter-engine/flutter-engine-periodictasks.json5) was made in this [CL](https://skia-review.googlesource.com/c/buildbot/+/523618) a week ago. Before that, both configs were identical.

**Comment by CaseyHillers** [comment]
Any blockers I can help with?

**Comment by godofredoc** [comment]
@mdebbar any updates on this bug?

**Comment by Piinks** [comment]
> It looks like Gold bot comments are completely disabled for flutter/flutter (see [CL](https://skia-review.googlesource.com/c/buildbot/+/523618)).

![Screen Shot 2022-12-02 at 10 40 10 AM](https://user-images.githubusercontent.com/16964204/205341849-06238b32-b228-4f2c-8142-fbb83b7581cd.png)

^ Comments like the one above come from Gold,  they can be enabled/disabled on Gold's side as in that PR. In flutter/flutter, these are disabled for all branches because we have our own bot handling via flutter/cocoon. Ans sometimes this one would get confused and create confusion for contributors.

![Screen Shot 2022-12-02 at 10 40 16 AM](https://user-images.githubusercontent.com/16964204/205341975-96ef34c5-db85-40f1-8058-7a368e8f9802.png)

^ This is the flutter/cocoon bot. It only comments on PRs staged to land on the master/main branch, and ignores release branches.

**Comment by mdebbar** [comment]
> ^ This is the flutter/cocoon bot. It only comments on PRs staged to land on the master/main branch, and ignores release branches.

That's right. And as far I can tell, the flutter/cocoon bot is configured the same way for flutter/flutter and flutter/engine.


I tried to create a CL similar to [this](https://skia-review.googlesource.com/c/buildbot/+/523618) for flutter/engine but I'm having trouble getting `git cl upload` to work. So I asked Leandro from the Gold team to help with creating the CL. Once that's merged and deployed, there should be no more Gold bot comments on flutter/engine.

**Comment by CaseyHillers** [comment]
We still see the gold bots on the engine releases. There's two issues I see:

1. Someone accidentally approves these, and breaks main
2. We're working on release automation, and checks like this might intefer with the automation workflows if they block submission via autosubmit

**Comment by mdebbar** [comment]
Gold bot's comments have been disabled for flutter/engine here: https://skia-review.googlesource.com/c/buildbot/+/613340

The `flutter-gold` check should already be ignoring any non-main PRs.

Please let me know if there's anything else that needs to be done here.

**Comment by CaseyHillers** [comment]
https://github.com/flutter/engine/pull/38072 is an instance where it was run today.

**Comment by mdebbar** [comment]
AFAICT, the `flutter-gold` check shouldn't be added to the release branch: https://github.com/flutter/cocoon/blob/65e2046f3c19c39dce5dcf5ae5600d924fd88735/app_dart/lib/src/request_handlers/push_gold_status_to_github.dart#L77-L82

The `flutter-gold` check is only added to PRs targeting the `main` branch.

**Comment by itsjustkevin** [comment]
@CaseyHillers and @mdebbar is this still an open issue?

**Comment by CaseyHillers** [comment]
Yes. Similarly, Google Testing needs to be disabled on release branches as well

**Comment by CaseyHillers** [comment]
This is still reproducing on https://github.com/flutter/engine/pull/50410
