### ISSUE TITLE
Unable to use the packages 

### ISSUE THREAD

**Issue by Ankjha12** [flutter/flutter#100958]
Hi my name is Ankit Kumar and I am new to flutter and started learning it but I am facing too many problems when using third party packages like intl for formatting the new Date also I can format it with my own code but it's too lengthy to write also I have visited all the official Documentation of intl package and also gone through all the steps of installing that package but whenever I tried to import it in my main .dart file I always get an error as "Target of URI doesn't exist: 'package:intl/intl.dart'" this . Also I have tested this that the intl is already added in my dependencies with all the correct indentation as listed in the documentation of the intl packages.

I am attaching  a screenshot of the error that I am getting always I tried to install intl package in my main.dart file.
![gitissue](https://user-images.githubusercontent.com/95214617/160573268-7f2e906d-c7f6-4555-adcb-f75191166080.png)

**Comment by maheshmnj** [comment]
Hi @Ankjha12, Thanks for filing the issue.  When you run `flutter pub get` do you see exit code 0?

**Comment by Ankjha12** [comment]
Yeah @maheshmnj please find attached both the screenshot of the pub get , yaml file and the doctor -v.  I did tried to troubleshoot it but it is producing errors 
![gitissue2](https://user-images.githubusercontent.com/95214617/160589118-4e89c50c-c86c-4d47-bbdc-380aefeb9ab3.png)
![gitissue3](https://user-images.githubusercontent.com/95214617/160589159-5606c30f-3b9b-46b6-b3df-5e588895f3d3.png)
![gitissue4](https://user-images.githubusercontent.com/95214617/160589182-c4dafd4f-5113-44b8-bdd7-47e459b44597.png)

**Comment by maheshmnj** [comment]
@Ankjha12, Are you using vscode or visual studio? Please share the complete output of `flutter doctor -v` (Avoid sharing screenshots of code and logs)

**Comment by Ankjha12** [comment]
Yes  I am using flutter in my visual studio code IDE because I am using this as web development right now I haven't configured any emulator I am just running the code snippet in the chrome or edge browser only so is flutter got some bugs to run it in browser cause as per the development guide we can use flutter for everything like IOS , Android , web and windows. here is the complete log of command flutter doctor -v listed below: also I have already configured my Vs code IDE setup required in the beginning. 

[√] Flutter (Channel stable, 2.10.3, on Microsoft Windows [Version 10.0.19042.1586], locale en-IN)
    • Flutter version 2.10.3 at C:\Users\Deepak\development\sdks\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (4 weeks ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[X] Android toolchain - develop for Android devices
    X Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] VS Code (version 1.65.2)
    • VS Code at C:\Users\Deepak\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.36.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19042.1586]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 99.0.4844.84
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 99.0.1150.55

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 3 categories.

**Comment by maheshmnj** [comment]
Thanks for the info, Please make sure you have installed the latest version of the flutter and dart plugin. Can you try adding any other plugin/package and see if you are able to import or have the same error?
Additionally have you tried restarting vscode?

If none of these fix it. I would suggest you to please file the issue here https://github.com/Dart-Code/Dart-Code/issues/new
Since it is mostly related to flutter/dart plugins in vscode.
