### ISSUE TITLE
[flutter_conductor] codesign_integration_test timing out after 5 minutes

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#100937]
I suspect this test was usually finishing in just under 5 minutes, as it needs to clone the framework and download cached binaries from scratch.

https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20framework_tests_misc/4046/overview

```
 05:03 +18 -1: test/codesign_integration_test.dart: validate the expected binaries from the conductor codesign command are present in the cache [E]                                                     
   TimeoutException after 0:05:00.000000: Test timed out after 5 minutes.
   dart:isolate  _RawReceivePortImpl._handleMessage
```

**Comment by christopherfujino** [comment]
Hmm, on the next green build, looks like the test only took 2 minutes: https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8818404367848598225/+/u/run_test.dart_for_framework_tests_shard_and_subshard_misc/test_stdout

**Comment by christopherfujino** [comment]
The real issue is most likely the same as https://github.com/flutter/flutter/issues/88060, which was that copying large amounts of data on mac bots with [fseventsd](https://developer.apple.com/library/archive/documentation/Darwin/Conceptual/FSEvents_ProgGuide/FileSystemEventSecurity/FileSystemEventSecurity.html#//apple_ref/doc/uid/TP40005289-CH6-SW5) running is incredibly slow. At the time (September 2021), the bots were manually fixed by adding `/System/Volumes/Data/.fseventsd/no_log` (https://bugs.chromium.org/p/chromium/issues/detail?id=1247735).

I believe the true solution here would be to have our SALT configurations set write this file. @yusuf-goog can you take this one?

**Comment by godofredoc** [comment]
CL is waiting for review

**Comment by yusuf-goog** [comment]
Fix submitted in CL http://go/ftcl/513178

**Comment by Hixie** [comment]
Closing per @christopherfujino.

**Comment by christopherfujino** [comment]
bot has not re-opened https://github.com/flutter/flutter/issues/101058 so I think we're in the clear.
