### ISSUE TITLE
Hi @romater0  @WeslleyNasRocha

### ISSUE THREAD

**Issue by rockey5520** [flutter/flutter#100994]
Could you please provide the command to upgrade flutter snap to latest `master` please ?

Hi @romater0  @WeslleyNasRocha 
This has been fixed, please upgrade your Flutter snap to latest `master`  https://github.com/canonical/flutter-snap/issues/32
Closing as fixed
Thank you

_Originally posted by @TahaTesser in https://github.com/flutter/flutter/issues/78109#issuecomment-805796560_

**Comment by maheshmnj** [comment]
@rockey5520, I believe you have filed the issue in the wrong repo, flutter-snap is third party tool and is not related to flutter. Issues related to that must be filed in its dedicated repo https://github.com/canonical/flutter-snap
