### ISSUE TITLE
[windows] keyboard show without textfield in tablet mode

### ISSUE THREAD

**Issue by TungWang** [flutter/flutter#100945]
1. Tap textfield to show keyboard.
2. Push to next page.
3. Textfield still show.

Please help me to fix this problem, thanks.

https://user-images.githubusercontent.com/45662066/160526793-1abf7007-5822-4b9d-9090-6f5cb17ee1c8.mp4

**Comment by maheshmnj** [comment]
Hi @TungWang, Thanks for filing the issue. 

There is a similar issue describing this case https://github.com/flutter/flutter/issues/99050, Please follow up there for further updates, Closing this issue as a duplicate. If you disagree feel free to write in the comments and we will reopen it.

Thank you.
