### ISSUE TITLE
LUCI scheduler is not triggering new builds on flutter/flutter

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#100999]
It appears that no tests have been running for hours: https://flutter-dashboard.appspot.com/#/build

**Comment by CaseyHillers** [comment]
Due to the mirroring breaking in https://github.com/flutter/flutter/issues/100992, there was a backlog.

Now with the mirror fixed, I'm trying to figure out how to get the gitiles poller to trigger the builds.

**Comment by CaseyHillers** [comment]
I'm duping this against https://github.com/flutter/flutter/issues/100999 as the core issue wasn't actually fixed

**Comment by CaseyHillers** [comment]
The issue is https://flutter.googlesource.com/mirrors/flutter is out of date (I forgot that https://cs.opensource.google/flutter points to GitHub)
