### ISSUE TITLE
[iOS] Flutter build command stucks at "Compiling, linking, signing..." step

### ISSUE THREAD

**Issue by chamartt** [flutter/flutter#100963]
Hi,

I upgraded my project to Flutter 2.10.3 (it was on 2.2.3) and all pubspec versions to be compatible together.
I also upgraded Xcode from 12.3 to 13.3.

Since, the `flutter build ios` command is always stucked at `└─Compiling, linking and signing...                            ⣯` step.
Before these upgrades, everthing was working normally, at this step, offering me full project for Xcode.

This is the last part of `flutter build ios -v` logs:
```
[  +13 ms] executing: mkfifo /var/folders/9p/5rx3ddtj1mgdzm8mpbbl4sbw0000hw/T/flutter_tools.411yPv/flutter_ios_build_temp_diryrjb8W/pipe_to_stdout
[   +5 ms] Exit code 0 from: mkfifo /var/folders/9p/5rx3ddtj1mgdzm8mpbbl4sbw0000hw/T/flutter_tools.411yPv/flutter_ios_build_temp_diryrjb8W/pipe_to_stdout
[   +3 ms] Running Xcode build...
[        ] executing: [/Users/user215447/Documents/LAlgoDePauloV2/ios/] xcrun xcodebuild -configuration Release VERBOSE_SCRIPT_LOGGING=YES -workspace Runner.xcworkspace -scheme Runner BUILD_DIR=/Users/user215447/Documents/LAlgoDePauloV2/build/ios -sdk iphoneos
-destination generic/platform=iOS SCRIPT_OUTPUT_STREAM_FILE=/var/folders/9p/5rx3ddtj1mgdzm8mpbbl4sbw0000hw/T/flutter_tools.411yPv/flutter_ios_build_temp_diryrjb8W/pipe_to_stdout -resultBundlePath
/var/folders/9p/5rx3ddtj1mgdzm8mpbbl4sbw0000hw/T/flutter_tools.411yPv/flutter_ios_build_temp_diryrjb8W/temporary_xcresult_bundle -resultBundleVersion 3 FLUTTER_SUPPRESS_ANALYTICS=true COMPILER_INDEX_STORE_ENABLE=NO
	[+318630 ms] Running Xcode build... (completed in 318.6s)
[        ]  └─Compiling, linking and signing...
```

This is my `flutter doctor -v` logs:
```
[✓] Flutter (Channel stable, 2.10.4, on macOS 12.1 21C52 darwin-x64, locale en-US)
    • Flutter version 2.10.4 at /Users/user215447/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (4 days ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] IntelliJ IDEA Community Edition (version 2020.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.65.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.36.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 99.0.4844.83

[✓] HTTP Host Availability
    • All required HTTP hosts are available
```

I tried to :
- flutter clean
- flutter pub get
- cd ios
- rm -rf Pods Podfile.lock
- pod install
- pod repo update
- then upgrade Flutter to latest version 2.10.4

In Xcode, Target, Signing & Capabilities, I'm configured (as previously) 'Automatically manage signing' and every thing is ok, well configured. I use my company team to signing, and not my personal one.

I'm using MacinCloud on OS 12.1 (on a new server as before, in order to use last OS version).

I never had this problem before (normally this step is the fastest like 2-3 secs) and didn't find about this kind of problem anywhere else that's why I'm asking to you today, for my first issue.

Thank you in advance for your help.

**Comment by maheshmnj** [comment]
Hi @chamartt, Thanks for filing the issue. Do you have this issue when running the app using `flutter run` too? If so, please share the complete output of `flutter run -v` and if it is only an issue with the build command then please share the verbose logs by running `flutter build ios -v` in a text file.

**Comment by chamartt** [comment]
Hi @maheshmnj ,

Thanks for your fast reply.

How can use 'flutter run' command through VS Code with a simulator ?

In my previous mac OS version, I had a "Simulator" in Lauchpad but now it seems to be moved directly in Xcode, so I don't know how to use the command with a simulator device anymore.
As I use Macincloud, I can not use a physical device.

Thank your for your help.

**Comment by hunterpp** [comment]
Also seeing this. 2.10.4 attaching -v 

[IOS_FREEZE.txt](https://github.com/flutter/flutter/files/8374747/IOS_FREEZE.txt)

**Comment by maheshmnj** [comment]
> In my previous mac OS version, I had a "Simulator" in Lauchpad but now it seems to be moved directly in Xcode, so I don't know how to use the command with a simulator device anymore.
As I use Macincloud, I can not use a physical device.

Oh I see, Can you check with booted simulator in xcode running if `flutter devices` shows any simulator from the root of your project? if it doesn then you should be able to run `flutter run -d <deviceId>`

> This is the last part of flutter build ios -v logs:

Can you please attach the complete logs by running `flutter build ios -v`

**Comment by maheshmnj** [comment]
> Also seeing this.

@hunterpp Are you seeing this issue when running on a physical mac ? Does this happen with a newly created project too?

**Comment by chamartt** [comment]
Hi @maheshmnj,

Thanks for the reply.
I found how to open Simulator on my new mac OS version using `open -a Simulator --args -CurrentDeviceUDID <your device UDID>`

This is the ending result of `flutter run -v`:
[flutter run -v result.txt](https://github.com/flutter/flutter/files/8379475/flutter.run.-v.results.txt)

> Does this happen with a newly created project too?

So I tried to run `flutter build ios` on a sample example flutter project (created from VS code, just replaced all `com.example.testnew` by my actual id) and the `Compiling, linking and signing` step worked well !
```
FF212:testnew user215447$ flutter build ios
Building com.lalgodepaulo.lalgodepaulo for device (ios-release)...
Automatically signing iOS for device deployment using specified development team in Xcode project: P8728Q7B5V
Running Xcode build...                                                  
 └─Compiling, linking and signing...                        11.2s
Xcode build done.                                           41.6s
Built /Users/user215447/Documents/TEST/testnew/build/ios/iphoneos/Runner.app
```

So I think there is some thing is wrong in my project, that I don't understand as nothing changed on except upgrading versions of my environment.

Just to remind you, in Windows-Android with same Flutter version, `flutter build apk` command works well.

Thank you for your help.

**Comment by maheshmnj** [comment]
Thanks for the logs @chamartt, I wonder if this issue is related to xcode, However the logs partially look similar to https://github.com/flutter/flutter/issues/95117. Labeling this issue for further investigation from the team. 

cc: @jmagman

**Comment by chamartt** [comment]
Hi @maheshmnj @jmagman ,

We are still facing the issue and need to update our app as soon as possible.

Were you able to take a look to our issue ?

Please let me know when you have any news of if you need additionals informations.
Thank you in advance for your time and your work.

**Comment by UsmanHaider15** [comment]
I am also facing same issue 

Latest Flutter 2.12.0
Latest Xcode 13.3

**Comment by gopichand77** [comment]
I was also facing the same issue `flutter run` stuck at compiling and signing 
My `flutter doctor -v`
I'm using the new project just added the firebase .plist and .json files

[✓] Flutter (Channel stable, 2.10.4, on macOS 12.3.1 21E258 darwin-x64, locale
    en-IN)
    • Flutter version 2.10.4 at /Users/gopichandbusam/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (10 days ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from:
      https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK
      components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup
      for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /Applications/Brave Browser.app/Contents/MacOS/Brave
      Browser

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup
      for detailed instructions).

[✓] VS Code (version 1.66.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.36.0

[✓] Connected device (3 available)
    • iPhone 13 (mobile) • 91939B71-C9BF-45BE-85B7-C563AC5842BB • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-15-4 (simulator)
    • macOS (desktop)    • macos                                • darwin-x64
      • macOS 12.3.1 21E258 darwin-x64
    • Chrome (web)       • chrome                               • web-javascript
      • Brave Browser 100.1.37.109

[✓] HTTP Host Availability
    • All required HTTP hosts are available

Also has the Xcode 13.3
Need to resolve this **ASAP**
@maheshmnj

**Comment by jmagman** [comment]
> And if I try to build directly in Xcode, it hangs as well.

Can you attach the output from Xcode when it is hanging?
<img width="1262" alt="Screen Shot 2022-04-04 at 12 04 17 PM" src="https://user-images.githubusercontent.com/682784/161613946-5461f5d5-a69b-415f-bacf-95c00e67b6fd.png">

**Comment by chamartt** [comment]
@hunterpp 

> Can you attach the output from Xcode when it is hanging?

**Comment by chamartt** [comment]
Hi @jmagman ,

Do you think that I can help with my environment (Macincloud + XCode 13) ?
I tried to run on simulator but no one seems to be available : 

![image](https://user-images.githubusercontent.com/15814545/162755857-d73da291-b4db-47ae-a076-78790aac70bf.png)


![image](https://user-images.githubusercontent.com/15814545/162755702-3f20ff94-8646-4904-a004-3a7c25aefcf9.png)

This issue is really blocking for us in order to test and deploy a new release.
Need to resolve ASAP as well, if I can help just let me know!

Thank you in advance

**Comment by jmagman** [comment]
@chamartt can you file an issue per problem? It looks like an issue with `google_sign_in` has `EXCLUDED_ARCHS = arm64 i386` which is incorrect, but it's not the same as the stuck problem this is tracking.

**Comment by chamartt** [comment]
@jmagman my main and only problem is that the build command stucks at "Compiling, linking, signing..." step.
In [my last comment](https://github.com/flutter/flutter/issues/100963#issuecomment-1095091030), I just wanted [to respond you](https://github.com/flutter/flutter/issues/100963#issuecomment-1087909519), as @hunterpp doesn't respond anymore.
This problem blocks us in order to test and deploy our next release.

Anyway, I tried to remove `google_sign_in` package and all usings, then retry to run `flutter build ios`, but the result is the same, here you can find the complete command output :

[output.txt](https://github.com/flutter/flutter/files/8471055/output.txt)

Thank you in advance for your help !

**Comment by chamartt** [comment]
Hi everyone,

As the command executed well with a new project created on VSCode as said in [a previous comment](https://github.com/flutter/flutter/issues/100963#issuecomment-1082897622), I tried to move all my custom contents from my project (assets, fonts, lib folders and config files) to this new project and ran the command : the `flutter build ios` command works well now !

So as guessed before, the problem should be in the existing project created on previous environment (old versions) and has to be resolved by creating a new one and moving content in.

Thank you for your help anyway, hope this solution will help community !

**Comment by shafiqaiman96** [comment]
Issue resolved for me.
1. delete iOS folder
2. flutter create (new project with same name)
3. copy iOS folder to the replace deleted file
4. flutter clean
5. flutter run

**Comment by jmagman** [comment]
> So as guessed before, the problem should be in the existing project created on previous environment (old versions) and has to be resolved by creating a new one and moving content in.

Can you tell from source control the difference between what was there before and what you replace it with?  I'd rather fix the underlying issue, "delete your ios directory" isn't an acceptable workaround...

**Comment by chamartt** [comment]
Due to my ios/.gitignore, nothing changed after creating new project and moving my content in.

This is my ios/.gitignore, if it can help you : 
```
*.mode1v3
*.mode2v3
*.moved-aside
*.pbxuser
*.perspectivev3
**/*sync/
.sconsign.dblite
.tags*
**/.vagrant/
**/DerivedData/
Icon?
**/Pods/
**/.symlinks/
profile
xcuserdata
**/.generated/
Flutter/App.framework
Flutter/Flutter.framework
Flutter/Flutter.podspec
Flutter/Generated.xcconfig
Flutter/ephemeral/
Flutter/app.flx
Flutter/app.zip
Flutter/flutter_assets/
Flutter/flutter_export_environment.sh
ServiceDefinitions.json
Runner/GeneratedPluginRegistrant.*

# Exceptions to above rules.
!default.mode1v3
!default.mode2v3
!default.pbxuser
!default.perspectivev3
```

I think you can reproduce it easily by creating project on Flutter version 2.2.3, running `flutter build ios` then upgrading Flutter to 2.10.3 and finally running `flutter build ios` where you should be stucked at "Compiling, linking, signing...".

**Comment by maheshmnj** [comment]
> I think you can reproduce it easily by creating project on Flutter version 2.2.3, running flutter build ios then upgrading Flutter to 2.10.3 and finally running flutter build ios where you should be stucked at "Compiling, linking, signing..." step.

I tried to reproduce this behavior by creating a project on 2.2.3, But I was not able to reproduce it.
Heres a [sample project](https://github.com/flutter/flutter/files/8521569/newapp.zip) created on `stable 2.2.3`


<details>
<summary>logs</summary>

```
mahesh@Maheshs-MacBook-Air-M1 newapp % flutterd build ios         
Building com.triagetest.newapp for device (ios-release)...
Signing iOS app for device deployment using developer identity: "Apple Development: mahesh@nevercode.io (8QBZ8V54QM)"
Running Xcode build...                                                  
 └─Compiling, linking and signing...                         8.1s
Xcode build done.                                           67.8s
Built /Users/mahesh/Desktop/newapp/build/ios/iphoneos.
mahesh@Maheshs-MacBook-Air-M1 newapp % flutterd --version
Flutter 2.2.3 • channel unknown • unknown source
Framework • revision f4abaa0735 (10 months ago) • 2021-07-01 12:46:11 -0700
Engine • revision 241c87ad80
Tools • Dart 2.13.4
mahesh@Maheshs-MacBook-Air-M1 newapp % flutter --version
Flutter 2.10.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 5464c5bac7 (2 days ago) • 2022-04-18 09:55:37 -0700
Engine • revision 57d3bac3dd
Tools • Dart 2.16.2 • DevTools 2.9.2
mahesh@Maheshs-MacBook-Air-M1 newapp % flutter clean
flutCleaning Xcode workspace...                                         1,499ms
Deleting build...                                                   34ms
Deleting .dart_tool...                                              22ms
Deleting .packages...                                                1ms
Deleting Generated.xcconfig...                                       1ms
Deleting flutter_export_environment.sh...                            0ms
mahesh@Maheshs-MacBook-Air-M1 newapp % flutter pub get
Running "flutter pub get" in newapp...                                 ⣟ 1,770ms
mahesh@Maheshs-MacBook-Air-M1 newapp % flutter build ios
Building com.triagetest.newapp for device (ios-release)...
Upgrading AppFrameworkInfo.plist
Updating project for Xcode compatibility.
Upgrading project.pbxproj
Upgrading Runner.xcscheme
Signing iOS app for device deployment using developer identity: "Apple Development: mahesh@nevercode.io (8QBZ8V54QM)"
Running Xcode build...                                                  
 └─Compiling, linking and signing...                         4.8s
Xcode build done.                                           29.9s
Built /Users/mahesh/Desktop/newapp/build/ios/iphoneos/Runner.app.
```
</details>
