### ISSUE TITLE
Rendering a display list to an existing builder does not respect opacity and reset attributes.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#100983]
Added in https://github.com/flutter/engine/pull/32268

**Comment by chinmaygarde** [comment]
cc @flar

**Comment by flar** [comment]
Is this still a problem? Is there a use case to test it? Did https://github.com/flutter/impeller/pull/153 fix it?

@chinmaygarde

**Comment by flar** [comment]
I'm pretty sure that https://github.com/flutter/impeller/pull/153 fixed it combined with https://github.com/flutter/engine/pull/32880

First one implemented Impeller::drawDisplayList, the second one started using drawDisplayList from dl_layer - together they fixed the issue.
