### ISSUE TITLE
Document a clear way to file requests for and collaborate with the TPgM team

### ISSUE THREAD

**Issue by nuritzi** [flutter/flutter#100929]
The TPgM team will be working with Google employees ("internal stakeholders") and people who are part of the wider community ("external stakeholders"). While Flutter & Dart are open source, there are some things that will need to remain internal-to-Google only due to affecting internal-to-Google customers, or things which contain sensitive information. 

As such, the TPgM team will need to create processes that are mindful of the audience, and which allow both types of stakeholders to collaborate with them. 

This issue is meant to help the TPgM team come to a consensus around how to work with each type of stakeholder, and to document the process in order to foster transparency and alignment. 

## TODOs
 * [Document a process](https://docs.google.com/document/d/1DaVBdUaAtt7-BWzcHzbkOUNrJOKwbMCdBUhVk4n14Yo/edit?resourcekey=0-Xum86dqDqBZMmsXA7JnyWw#) for how people can interact with the TPgM team 
 * Figure out where to publish the documented process (most likely will be partly on GitHub and partly on a Google3 site), and publish it

**Comment by itsjustkevin** [comment]
Closing as work is complete on internal website.
