### ISSUE TITLE
Internet Connection Checker

### ISSUE THREAD

**Issue by arslanraza7** [flutter/flutter#100968]
Hello, How can I check the internet connection and be notified in the entire application?

**Comment by Mayb3Nots** [comment]
Hi, please check out this [package ](
https://pub.dev/packages/connectivity_plus) and its documentation. Help with questions can be asked at [StackOverflow](https://stackoverflow.com/tags/flutter).

**Comment by Mayb3Nots** [comment]
@arslanraza7 You can use the method `onConnectivityChanged` to get a stream and listen when the device connection status changes. Read [here](https://pub.dev/packages/connectivity_plus#usage) for more info.

**Comment by darshankawar** [comment]
Please ask support questions on StackOverflow. Also there are various community plugins that offers the feature you are looking for.
Closing from here.
