### ISSUE TITLE
Improve the memory footprint of the zoom page transition

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#100972]
On https://github.com/flutter/flutter/commit/543a7e858828e721258b8fb9ded62d7a2ff05808, several flutter_gallery benchmarks are showing a 10-20MB regression in memory footprint.

https://flutter-flutter-perf.skia.org/e/?begin=1648252513&end=1648446610&keys=X845c9ddf84d6ac62deff51c6cee6ad22&num_commits=50&request_type=1&xbaroffset=28090

Weirdly, SkiaPerf flags the following commit, but it's pretty clear from the chart where the regression happened.

@dnfield @AlexV525

**Comment by zanderso** [comment]
SkiaPerf is also reporting improvements to startup time on the following commit, which I think might be related to this change instead:

https://flutter-flutter-perf.skia.org/e/?begin=1647970222&end=1648529864&keys=X81697c49f65f4df52f48a98a3abb5761&requestType=0&xbaroffset=28090

**Comment by AlexV525** [comment]
Compared to the last regression, it can be treated as the same one, at least they both have the same numbers: https://flutter-flutter-perf.skia.org/e/?begin=1629261122&end=1629326522&keys=X2d2c76f41c39fb3dfadbb3bef0e020cb&num_commits=50&request_type=1&xbaroffset=25489

**Comment by dnfield** [comment]
It sounds like we were concerned this could cause a speed regression but didn't because of opacity peephole optimizations. But instead it's causing higher utilization of the raster cache because of those optimizations. 

We should verify whether we really need the extra raster cache entries. I'd have to look more closely at the visual differences between the old and new transition to understand.

**Comment by dnfield** [comment]
Although if that's the case, I'm not really clear on why it would be impacting the diff-min stat - the raster cache entries should be relatively short lived, and we should be hitting periods where they get evicted and we're back at baseline if my theory is right.

**Comment by flar** [comment]
I'm trying to run the benchmark, but it bombs out almost immediately complaining that I don't have the super-parameters language feature enabled. Shouldn't the benchmark enable that itself?

**Comment by flar** [comment]
From what I can see, the extra memory comes from duplicate caching which could be addressed soon in https://github.com/flutter/engine/pull/31892

I'm still looking at a way that this could be handled more efficiently in the engine.

**Comment by goderbauer** [comment]
Triage: adding the engine tag based on the discussion above.

**Comment by zanderso** [comment]
@flar I'm not following how https://github.com/flutter/engine/pull/31892 will help. Is that PR something that one could patch in now to see if it will help?

@dnfield Are you seeing any feedback from `customer: money`?

cc @jonahwilliams @jason-simmons

**Comment by jonahwilliams** [comment]
PSS sizes from the end of run for the memory_nav benchmark on Android:

<html>
<body>
<google-sheets-html-origin>

  | Old Transition | New Transition | Delta |  
-- | -- | -- | -- | --
Java Heap | 3448 | 2248 | 1200 |  
Native Heap | 23972 | 45180 | 21208 |  
Code | 25724 | 17148 | 8576 |  
Stack | 836 | 768 | 68 |  
Graphics | 53044 | 62352 | 9308 |  
Private Other | 20116 | 19124 | 992 |  
System | 4318 | 5289 | 971 |  
  |   |   |   |  
TOTAL PSS | 131458 | 152109 | 20651 |  


</body>
</html>

**Comment by jonahwilliams** [comment]
So the native heap has grown a lot on the new transition. I _think_ that could be explained by double raster caching (but I thought that would just be graphics memory?) as pointed out by @flar , but I'm surprised I don't see that showing up with the raster cache checkerboard.

**Comment by jonahwilliams** [comment]
Which event do we put that on? I only see a single RasterCachePopulate in the timeline (observatory or devtools) which confirms my observations of the new transition.

**Comment by jonahwilliams** [comment]
![image](https://user-images.githubusercontent.com/8975114/162815179-fce32ce0-99fe-4136-b848-0a61176ab13e.png)

**Comment by jonahwilliams** [comment]
Also experimenting with removing the FadeTransition from the page transition, the PSS stays quite high - which tells me this is more to do with the impact of the translation than it does the raster caching of the opacity layer

**Comment by jonahwilliams** [comment]
Actually, If I add a FilterQuality.low, we drop back down to about the old PSS memory usage. Something I didn't know, when you provide a FilterQuality to a transform, we fall back to using a an ImageFilter instead of pushing a transform. Theoretically this allows raster caching of children to not be defeated, at the cost of small rendering artifacts.

**Comment by dnfield** [comment]
If we use a higher filter quality do we get fewer artifacts?

**Comment by jonahwilliams** [comment]
So something may be wrong with how we have implemented raster caching for the ImageFilterLayer, or in how we can use it through the ScaleTransform widget. Unlike the other transitions, when I usage an ImageFilter via FilterQuality on the ScaleTransform widget, the raster cache checkerboard shows up on the entire screen - more or less permanently, even once the transition is "completed". Further more, this continues to update as various parts of the page itself are interacted with.

This could be related to the issue I observed with the "no-op" blue filter still going through the raster cache path, when instead it could entirely avoid it.

![flutter_01](https://user-images.githubusercontent.com/8975114/162825054-01f98097-4581-4b6a-9729-e808310b10c3.png)

**Comment by jonahwilliams** [comment]
Observing the effects on device, the ImageFilter does not seem to allow us to retain raster cache child entires either, or at least not successfully.  Also oddly enough the ImageFilter seems to impact the preview banner

**Comment by flar** [comment]
When animating a small scale (or any rotation), it is unlikely that a user could see the tiny transform artifacts while the animation is occurring. It would be slight blurring of the edges which would be lost in the motion. A large scale animation (say 1-5x) you'd start to have it look pixelated, but the transition here uses a very small scale.

**Comment by flar** [comment]
Are the transition and opacity animations removed from the tree when it is done?

**Comment by jonahwilliams** [comment]
No, we leave them in the tree. In fact, we leave both the forward and reverse transitions in the tree always.

**Comment by flar** [comment]
That could be the problem with the filter quality solution as it uses an ImageFiltered widget which will attempt to apply an ImageFilter on every frame. I'm not sure if either has a decision during the paint phase that eliminates the layer if the transform is identity. I do remember one RenderObject that tried to avoid a layer if the transform was a translation.

**Comment by jonahwilliams** [comment]
Yeah, that sounds similar to the issue I observed with bluring - even with a radius of `0` we still go through a seemingly more expensive pass. I could solve this in the route transition by forcing FilterQuality to null when the animation is at either `0` or `1` - but it would be ideal if there was a fast way the engine could skip these layers.

**Comment by flar** [comment]
Yes, RenderTransform will omit a layer when the transform is a translation, but only in the case where there is no filterQuality.

The problem with omitting the filter layer when the transform is a translation or an identity is that if your scale animation goes from 0.8x to 1.2x then you will get a glitch when the scale passes through 1.0x. I think I intentionally didn't omit the filter for that reason and relied on the developer only using the filterQuality transforms during animations.

Is there a reason that these widgets are left in the tree even when not transitioning?

**Comment by flar** [comment]
Currently, the engine is able to see the opacity value and make decisions based on that, but the ImageFiltered layer has an opaque SkImageFilter. We recently introduced DlImageFilter which could be smart about omitting itself, but we only use that in DisplayList objects. I filed https://github.com/flutter/flutter/issues/100454 to get the layers to start using the inspectable objects and then we could look into the engine omitting these operations automatically.

**Comment by flar** [comment]
One issue with relying on the engine to reverse engineer the framework's inefficiency is that we have the framework wasting time managing widgets and render objects that are obsolete and building layers that aren't needed and then we have additional work in the engine to notice that the layers are obsolete and so we get everyone doing extra work to avoid the framework omitting the unnecessary layers on its own.

**Comment by jonahwilliams** [comment]
That makes a lot of sense, thanks. I think the right solution at least for these Animated widgets is to use thier knowledge of the animation status to only skip the layer at the beginning and end of an animation.

**Comment by jonahwilliams** [comment]
Separately, I'm going to take a pass at our documentation to ensure we mention that these layers aren't skipped, which I notice isn't mentioned on ImageFiltered at least

**Comment by flar** [comment]
Not having these layers in the tree when they aren't animating might make a difference and it might also make the filterQuality solution work better.

**Comment by flar** [comment]
> @flar I'm not following how [flutter/engine#31892](https://github.com/flutter/engine/pull/31892) will help. Is that PR something that one could patch in now to see if it will help?

Right now if we have nested layers that both want to cache, they both will. Each layer decides independently whether it will cache in its own Preroll method and we execute all Preroll methods to make sure we accumulate the correct bounds up through the tree. But the parent's cache will obviate the need for the child's cache - and yet there they both are in our cache.

That PR will have us collect the requests for caching during Preroll and then evaluate them all during the Paint phase. This way, if a parent caches itself or "all of its children" during the evaluation phase, then it will skip the requests that its children made without any adverse effects on the children (other than their cache request being ignored) and only the parent will end up in the cache.

**Comment by jonahwilliams** [comment]
A quick summary:

The page transition landed in the next build, regressing memory benchmarks. Its not a _huge_ regression, but its not nothing either - so we should probably revert it.

We do have fixes, but these fixes may have other trade offs and we probably shouldn't cherry pick them

**Comment by jonahwilliams** [comment]
Re-opening until we've confirmed the fix

**Comment by zanderso** [comment]
Please file a cherry pick request

**Comment by jonahwilliams** [comment]
On a revert or?

**Comment by zanderso** [comment]
Yeah, it sounded like you were suggesting that the switch to the new transition should be reverted. If so, that would need to be cherry-picked onto the release branch.

**Comment by jonahwilliams** [comment]
Sorry if that was unclear - I was just sumarizing what we know. I have zero idea whether we should cherry pick a revert.

At any rate, with the latest change I landed above we are back to previous memory usage:

https://flutter-flutter-perf.skia.org/e/?begin=1648191600&numCommits=300&queries=test%3Dflutter_gallery__memory_nav&requestType=0

Provided there are no other flagged regressions we can problably close this

**Comment by jonahwilliams** [comment]
Do we have updated docs on our chery pick process?

**Comment by zanderso** [comment]
Yeah there's a new issue template https://github.com/flutter/flutter/issues/new?assignees=&labels=cp%3A+review&template=7_cherry_pick.yml&title=%5BCP%5D+%3Ctitle%3E

**Comment by AlexV525** [comment]
I've submitted an announcement the announce group, please hold it if the transition needs a revert.

**Comment by jonahwilliams** [comment]
So this ended up only needing 2 small changes in the framework. If we're set on announcing that we support this transition, I'd say we either accept the small regression or we could cp both small changes to improve memory usage. Requiring an engine fix might be a bit too much but we might be OK without the other change

**Comment by AlexV525** [comment]
> So this ended up only needing 2 small changes in the framework. If we're set on announcing that we support this transition, I'd say we either accept the small regression or we could cp both small changes to improve memory usage. Requiring an engine fix might be a bit too much but we might be OK without the other change

Yeah but it's not accepted yet. Though I'd upvote for picking small changes.

**Comment by jonahwilliams** [comment]
So unfortunately my changes caused a separate regression, see https://github.com/flutter/flutter/issues/101821 , so while we have fixed some of the issues we're not yet able to switch over to the ImageFilter for the reduced memory usage.

**Comment by jonahwilliams** [comment]
From discussion last week, we've decided not to revert this. Some factors:

* Landing this default change was fairly extensive, and it would be a fairly extensive revert if we rolled into google3.
* Functionally, the transition has changed it is expected that it has different performance characteristics. The cost also appears to be fixed.
* This is a change in the default, but users can opt into one transition type or another themselves.
* We noticed no issues nor received any complaints from already migrated g3 customers.

Given these, we will continue to explore ways to improve the performance but the severity should be downgraded.

**Comment by jonahwilliams** [comment]
I've relanded the switch to use an ImageFilter, this has lowered memory here: 

https://flutter-flutter-perf.skia.org/e/?begin=1650997747&end=1651002848&queries=test%3Dflutter_gallery__memory_nav&xbaroffset=28565

Will mark as fixed as soon as all the benchmarks come back positive

**Comment by flar** [comment]
Is there any jankiness with the IF caching on the first frame?

**Comment by jonahwilliams** [comment]
According to benchmarks yes:  https://flutter-flutter-perf.skia.org/e/?begin=1650989645&end=1651012744&keys=X809a5f88fb68c1b259242471f65ee081&num_commits=50&request_type=1&xbaroffset=28565

reverting again with https://github.com/flutter/flutter/pull/102611

**Comment by jonahwilliams** [comment]
https://flutter-flutter-perf.skia.org/e/?queries=test%3Dflutter_gallery__memory_nav

![image](https://user-images.githubusercontent.com/8975114/180518062-c79e88e3-7626-4399-9c53-5ca413fb9e93.png)

We're now back in the same memory ballpark with https://github.com/flutter/flutter/pull/106621
