### ISSUE TITLE
No problem!

### ISSUE THREAD

**Issue by Ankjha12** [flutter/flutter#100955]
No problem!

_Originally posted by @jonahwilliams in https://github.com/flutter/flutter/issues/18257#issuecomment-395286506_

I have added this intl.dart file in my pubspec.yaml file as the dependencies also i take car of the indentation to avoid errors but i always get one while importing this in my main.dart file also  I worked on other approaches as well by installing it from command line by running commands but it shows the same issue always also I visited the official documentation and the Api reference but nothing could help about it please help me troubleshooting this.

**Comment by darshankawar** [comment]
Please don't open multiple issues for same reason and using comments from others. Please see [this](https://github.com/flutter/flutter/issues/100954#issuecomment-1081586916) comment.
Closing as duplicate.
