### ISSUE TITLE
Draggable wasAccepted returns true if you just click and release mouse

### ISSUE THREAD

**Issue by sgehrman** [flutter/flutter#100953]
If I move the mouse a bit, wasAccepted returns false. (from onDragEnd)

The problem is I'm clicking an item to drag and since wasAccepted return true, I assume it's been moved and delete the source. If I move the mouse a bit it works.

Also how can I have a widget that is both clickable and draggable?

**Comment by sgehrman** [comment]
I fixed it by wrapping it with and Inkwell to handle the tap.  It works for me now, but its still a bug.

**Comment by maheshmnj** [comment]
Hi @sgehrman, Thanks for filing the issue. Please share a [minimal and complete reproducible code](https://stackoverflow.com/help/minimal-reproducible-example) along with the output of `flutter doctor -v`. Are you seeing this issue on the web or on the Desktop app?
