### ISSUE TITLE
Menu items remain interactive after menu has started closing

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#101]
<a href="https://github.com/Hixie"><img src="https://avatars.githubusercontent.com/u/551196?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Hixie](https://github.com/Hixie)**
_Monday Jul 20, 2015 at 20:32 GMT_
_Originally opened as https://github.com/flutter/engine/issues/143_

----

_From @Hixie on April 21, 2015 22:16_

Once a popup menu has been dismissed, tapping the animating-shut menu should have no effect.

_Copied from original issue: domokit/mojo#113_

**Comment by abarth** [comment]
Fixed by ModalRoute.
