### ISSUE TITLE
[web]: PWA is not able to download file

### ISSUE THREAD

**Issue by snorliman** [flutter/flutter#101022]
PWA is not able to download file, how can I download from url a file? i browser it's working

**Comment by maheshmnj** [comment]
Hi @snorliman, PWA's can be downloaded to user's device from the settings or the pop-up that shows on the users phone.

Closing, as this is neither a bug nor feature request. If you disagree, please write in the comments and we will reopen it.

Thank you

**Comment by snorliman** [comment]
Sorry for not precise question. Flutter Web aplication in browser can download file by url and save it like it is in normal downloading from internet with using a browser, but when this file will be tried to download in this flutter app used as PWA there is a problem with downloading, and precise: nothing happening, and I can't track why, why in browser it's works and in PWA isn't

**Comment by maheshmnj** [comment]
@snorliman Can you share a minimal and complete code sample to reproduce this issue?

**Comment by snorliman** [comment]
`class _Annex extends StatefulWidget {
  final ProductDataItem? data;
  const _Annex({required Key key, required this.data}) : super(key: key);
  @override
  State<_Annex> createState() => _AnnexState();
}
class _AnnexState extends State<_Annex> {
  String? path;
  void downloadFile(String url){
   html.AnchorElement anchorElement =  new html.AnchorElement(href: url);
   anchorElement.download = url;
   anchorElement.click();
}
  @override
  Widget build(BuildContext context) {
    double widthScreen = MediaQuery.of(context).size.width;
    return Container(
          padding: const EdgeInsets.all(2),
          width: 1000,
          height: 600,
      child: Column(
              mainAxisSize: MainAxisSize.min,
              mainAxisAlignment: MainAxisAlignment.start,
              crossAxisAlignment: CrossAxisAlignment.center,
              children: [
                showAnnexTable(widget.data?.productData?.attachments , widthScreen),  
                ]));
  }

  showAnnexTable(List<Attachment>? data, screenWidth) {
    if (data != null) {
      return SingleChildScrollView(
        scrollDirection: Axis.horizontal,
        child: SingleChildScrollView(
          controller: ScrollController(),
          child: ConstrainedBox(
            constraints: BoxConstraints(minWidth: 500, maxWidth: 940),
            child: DataTable2(
                headingRowColor: dataTableHeaderColor(),
                headingRowHeight: dataTableRowHeight,
                decoration: dataTableDecoraiton(),
                border: const TableBorder(
                    horizontalInside:
                        BorderSide(color: borderTableColor, width: borderWidth),
                    verticalInside:
                        BorderSide(color: borderTableColor, width: 0.3)),
                dividerThickness: borderWidth,
                dataRowHeight: dataTableRowHeight,
                columnSpacing: 10,
                headingTextStyle: customTableHeaderTextStyle(),
                dataTextStyle: customTableCellTextStyle(),
                columns: [
                  DataColumn(label: const Text('ZLECENIE')),
                  DataColumn(label: const Text('PLIKI')),
                ],
                rows: data
                    .map((Attachment atachment) =>
                        DataRow(
                          color: dataTableColor(), 
                          onSelectChanged:(bool? isSelected) async {
                            if(atachment.path.contains('tiff') || atachment.path.contains('TIFF')) {
                               downloadFile( atachment.path);
                            } else {
                            await launch(atachment.path);
                            }
                       
                          // launch(atachment.path); 
                          },
                          cells: [
                          DataCell(Text(atachment.attachmentName)),
                          DataCell(Text(atachment.path)),
                        ]))
                    .toList()),
          ),
        ),
      );
    } else
      return Card(
        elevation: 15,
        child: ConstrainedBox(
          constraints: BoxConstraints(maxWidth: 940, minWidth: 540),
          child: DataTable(
              headingRowColor: dataTableHeaderColor(),
              headingRowHeight: dataTableRowHeight,
              decoration: dataTableDecoraiton(),
              border: const TableBorder(
                  horizontalInside:
                      BorderSide(color: borderTableColor, width: borderWidth),
                  verticalInside:
                      BorderSide(color: borderTableColor, width: 0.3)),
              dividerThickness: borderWidth,
              dataRowHeight: dataTableRowHeight,
              columnSpacing: 10,
              headingTextStyle: customTableHeaderTextStyle(),
              dataTextStyle: customTableCellTextStyle(),
              columns: [
                DataColumn(label: Text('ZLECENIE')),
                DataColumn(label: Text('PLIKI')),
              ],
              rows: [
                DataRow(color: dataTableColor(), cells: [
                  DataCell(Text("")),
                  DataCell(Text("")),
                ])
              ]),
        ),
      );
  }
}
`
Flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.10.1, on Microsoft Windows [Version 10.0.19043.1586], locale pl-PL)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.9)
[√] Android Studio (version 2021.1)
[√] VS Code (version 1.65.2)
[√] Connected device (3 available)
[√] HTTP Host Availability

• No issues found!

Function downloadFile is going to download file with tiff extension becouse browser have problem to open it. This works on browser when app running but not in PWA

**Comment by maheshmnj** [comment]
@snorliman The code sample above contains lot of unknown variables please simplify the code to contain only the relevant portion of the code and ensure that it is complete so that it can be copied and directly run  

>  html.AnchorElement anchorElement =  new html.AnchorElement(href: URL);
 
Alos it would be great if you can include the URL in the code, so that we will be able to verify the issue.
