### ISSUE TITLE
Website overflow menu causes scrolling of the viewport

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#10105]
## Steps to Reproduce

1. Open flutter.io, and make the window narrow so that the overflow "three dot" menu is shown (alternatively use a mobile device).

1. Scroll down a bit on the page

1. Click the overflow menu button

=> Page scrolls to the top

**Comment by mit-mit** [comment]
cc @sethladd

**Comment by zoechi** [comment]
I haven't found a "three dot" menu even when making the window narrow.
I assume this is stale.
