### ISSUE TITLE
Add PaintOffset widget

### ISSUE THREAD

**Issue by abarth** [flutter/flutter#10103]
Sometimes it's useful to apply a paint-time offset to a widget tree.  For example, if you have a popup that needs to be positioned relative to another widget, you might want to examine the position of the other widget during the paint phase and offset the popup accordingly.

We can encapsulated this pattern with a widget that calls you back during the paint phase and requests an offset, which it then applies as a paint offset (e.g., similar to a `Transform`).

/cc @kleak

**Comment by Kleak** [comment]
An example of what we are trying to do:

Here when we first build the tree we would like to draw the popup with wrong password as soon as possible, but we also want the popup to be at the good position in the screen.

![flutter_01](https://cloud.githubusercontent.com/assets/5434752/26108714/9ff00e78-3a4d-11e7-9e02-7e8280c67f85.png)

**Comment by christian-lefty** [comment]
If you could apply the label customer:lefty kleak is with us now :)

**Comment by abarth** [comment]
We could also make this more special-purpose and have a widget that did all the alignment for you.

**Comment by Hixie** [comment]
As described this won't work in the general case because it won't update the second widget when the first moves. To make that work you'll also need https://github.com/flutter/flutter/issues/3861.

**Comment by Hixie** [comment]
I'm closing this in favour of #3861, which I'm about to fix.
