### ISSUE TITLE
DropdownButtonFormField unable to set initial value (Web)

### ISSUE THREAD

**Issue by haradakunihiko** [flutter/flutter#101091]
## Steps to Reproduce
- Almost same issue as https://github.com/flutter/flutter/issues/96905
- Testing on Flutter 2.10.4 and 2.10.3. Debug is working as expected but when run with release mode, it fails.
- When you set initial value for DropdownButtonFormField, nothing shown.
- After selecting value from the Dropdown, it's successfully set and visible.
- Passing value wrapped by freezed from riverpod provider  causes, but directly passing value would not.
- I have several DropdownButtonField with the same issue in a project. When I directly pass a value to one widget, all widgets works as expected.

**Expected results:** 
Expecting initial value to be shown. 

**Actual results:** 
DropdownButtonFormField shows as empty

<details>
<summary>Code sample</summary>
Here is  the psuedo code since I could not create reproducing simple code, but there is some hint in generated js code.

```dart
class DropDown extends ConsumerWidget {
  const DropDown({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final state = ref.watch(provider);
    return Column(
      children: [
        Form(
            child: DropdownButtonFormField<int>(
          value: state.value, // passing value from riverpod will cause this issue
          // value: 1,   // when you pass value directly, it won't.
          items: [1, 2, 3]
              .map(
                (int item) => DropdownMenuItem<int>(
                  child: Text(item.toString()),
                  value: item,
                ),
              )
              .toList(),
          onChanged: (int? value) {},
        )),
      ],
    );
  }
}

```
</details>

Running with `--profile --web-renderer html` arguments,  there is a slight difference in the generated js code.

**with code which causes the DropdownButtonFormField showing the value**
```js
  A.FormFieldState.prototype = {
    get$_form$_value() {
      var value = this.__FormFieldState__value;
      return value === $ ? this.__FormFieldState__value = this.get$widget().initialValue : value;
    },
```

**with code which causes the DropdownButtonFormField NOT showing the value**
```js
  A.FormFieldState.prototype = {
    get$_form$_value() {
      var value = this.__FormFieldState__value;
      return value;
    },
```

**FormFieldState Implementation**
```dart
class FormFieldState<T> extends State<FormField<T>> with RestorationMixin {
  late T? _value = widget.initialValue;
```

Seems like late keyword causing the problem, but I'm not sure why and could not create simple code to reproduce this. 
Can anyone help with this?

<details>
  <summary>Logs</summary>

```
```

```
 fvm flutter analyze
Analyzing app...                          
No issues found! (ran in 2.6s)
```

```
fvm flutter doctor -v
[✓] Flutter (Channel stable, 2.10.4, on macOS 11.4 20F71 darwin-x64, locale ja-JP)
    • Flutter version 2.10.4 at /Users/kunihikoharada/fvm/versions/2.10.4
    • Upstream repository ssh://git@github.com/flutter/flutter.git
    • Framework revision c860cba910 (6 days ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/kunihikoharada/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Users/kunihikoharada/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/211.7628.21.2111.8193401/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] Android Studio (version 2020.3)
    • Android Studio at /Users/kunihikoharada/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7678000/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.65.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 99.0.4844.84

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```

</details>

**Comment by haradakunihiko** [comment]
I'm using graphql like mentioned at https://github.com/flutter/flutter/issues/96905#issuecomment-1028498072

Wrote an sample code (this does not reproduce, just FYI) https://github.com/haradakunihiko/reproducing_flutter_dropdown_field_bug

**Comment by haradakunihiko** [comment]
[update]

I found a workaround of this issue. Put a code bellow to somewhere in your app, and generated js code changed as expected.
It does not need to be rendered.

```
FormField(builder: (_) => const SizedBox.shrink())
```

**Comment by darshankawar** [comment]
@haradakunihiko 
See if this open issue would also fix your issue https://github.com/flutter/flutter/issues/56725

**Comment by haradakunihiko** [comment]
Thanks you @darshankawar, but I don't think that is related issue because every DropDownMenuItems are created with value props. Selected value is correctly shown in my situation.

**Comment by darshankawar** [comment]
@haradakunihiko 
In order to properly address this, please provide a complete minimal and runnable code sample without third party plugin code that shows the issue you are reporting.

**Comment by 838** [comment]
I also have the same issue in my app.
When I create a demo app without any third party plugins, the dropdown works as expected with the initial value. 
In my case the issue is from one of the plugins, and not sure exactly which one 😅

**Comment by yustapps** [comment]
The same here, but I haven't graphql... On debug works perfectly... Some suggestion?
