### ISSUE TITLE
[Fonts] Icon request: network_wifi_1_bar

### ISSUE THREAD

**Issue by MartinXBcn** [flutter/flutter#101026]
All intermediate icons for signal strength of wifi, cellular etc. are missing.

**Comment by danagbemava-nc** [comment]
Hi @MartinXBcn, the `network_wifi_1_bar` is available on the `master` channel. See https://master-api.flutter.dev/flutter/material/Icons/network_wifi_1_bar-constant.html. I can also see some cellular icons on the master channel in this list https://master-api.flutter.dev/flutter/material/Icons-class.html 

If you feel any icons are missing from the master list, kindly leave a comment in https://github.com/flutter/flutter/issues/99973. 

Closing from here. 

Thank you
