### ISSUE TITLE
Build AARs with Gradle 7.0

### ISSUE THREAD

**Issue by blasten** [flutter/flutter#101083]
Gradle 7.0 removed `org.gradle.api.artifacts.maven.MavenDeployer` currently used to build AARs.

There's a new Maven Publish Plugin that can be used to output the artifacts to a local destination:
https://docs.gradle.org/current/userguide/publishing_maven.html#publishing_maven:install

**Comment by blasten** [comment]
@AesSedai101 Please go ahead :) 
Here's the script used to generate AARs https://github.com/flutter/flutter/blob/master/packages/flutter_tools/gradle/aar_init_script.gradle

**Comment by AesSedai101** [comment]
thanks, I'll try to get a PR up today 🙂
