### ISSUE TITLE
TabBar conflicts with FlexibleSpace within SliverAppBar and NestedScrollView

### ISSUE THREAD

**Issue by namiwang** [flutter/flutter#10102]
Seems having a `TabBar` and a `FlexibleSpaceBar` at the same time within a SliverAppBar causes an issue.

Idk if this is expected.

## Steps to Reproduce

Say a simple stateless widget with a `build` like the following.

(Basically that's the `Tabs` from `Gallery`, plus a `flexibleSpace`.)

```dart
  Widget build(BuildContext context) {
    return new DefaultTabController(
      length: 2,
      child: new Scaffold(
        body: new NestedScrollView(
          headerSliverBuilder: (BuildContext context, bool innerBoxIsScrolled) {
            return <Widget>[
              new SliverAppBar(
                pinned: true,
                expandedHeight: 256.0,
                forceElevated: innerBoxIsScrolled,
                flexibleSpace: new FlexibleSpaceBar(
                  title: new Text('title'),
                  background: new Stack(
                    fit: StackFit.expand,
                    children: <Widget>[
                      new Image.network(
                        "http://placehold.it/640x320",
                        fit: BoxFit.cover,
                        height: 256.0 
                      ),
                    ]
                  )
                ),
                bottom: new TabBar(
                  tabs: [
                    new Tab(text: 'tab1'),
                    new Tab(text: 'tab2'),
                  ],
                ),
              ),
            ];
          },
          body: new TabBarView(
            children: [
              new ListView(),
              new ListView(),
            ]
          )
        )
      ),
    );
  }
```

## Logs
```
I/flutter (23861): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (23861): The following assertion was thrown during performLayout():
I/flutter (23861): RenderFlex children have non-zero flex but incoming height constraints are unbounded.
I/flutter (23861): When a column is in a parent that does not provide a finite height constraint, for example if it is
I/flutter (23861): in a vertical scrollable, it will try to shrink-wrap its children along the vertical axis. Setting a
I/flutter (23861): flex on a child (e.g. using a Flexible) indicates that the child is to expand to fill the remaining
I/flutter (23861): space in the vertical direction.
I/flutter (23861): These two directives are mutually exclusive. If a parent is to shrink-wrap its child, the child
I/flutter (23861): cannot simultaneously expand to fit its parent.
I/flutter (23861): The affected RenderFlex is:
I/flutter (23861):   RenderFlex#725333222 relayoutBoundary=up7 NEEDS-LAYOUT NEEDS-PAINT
I/flutter (23861): The creator information is set to:
I/flutter (23861):   Column ← Padding ← Positioned ← Stack ← Align ← DefaultTextStyle ← AnimatedDefaultTextStyle ←
I/flutter (23861):   _InkFeatures-[GlobalKey ink renderer] ← NotificationListener<LayoutChangedNotification> ←
I/flutter (23861):   PhysicalModel ← AnimatedPhysicalModel ← Material ← ⋯
I/flutter (23861): The nearest ancestor providing an unbounded width constraint is:
I/flutter (23861):   RenderStack#453632780 relayoutBoundary=up5 NEEDS-LAYOUT NEEDS-PAINT
I/flutter (23861):   creator: Stack ← Align ← DefaultTextStyle ← AnimatedDefaultTextStyle ← _InkFeatures-[GlobalKey ink
I/flutter (23861):   renderer] ← NotificationListener<LayoutChangedNotification> ← PhysicalModel ←
I/flutter (23861):   AnimatedPhysicalModel ← Material ← AppBar ← _FlexibleSpaceBarSettings ←
I/flutter (23861):   _SliverPinnedPersistentHeader ← ⋯
I/flutter (23861):   parentData: offset=Offset(0.0, 0.0) (can use size)
I/flutter (23861):   constraints: BoxConstraints(0.0<=w<=411.4, 0.0<=h<=280.0)
I/flutter (23861):   size: Size(411.4, 280.0)
I/flutter (23861):   alignment: FractionalOffset(0.0, 0.0)
I/flutter (23861):   fit: StackFit.loose
I/flutter (23861):   overflow: Overflow.clip
```

## Flutter Doctor

Got a bunch of `[✓]` from the doctor.

```
    • Framework revision ce2c834f70
    • Engine revision 6fef702cfa
    • Tools Dart version 1.23.0-dev.11.11
```

**Comment by eseidelGoogle** [comment]
@HansMuller would know.

**Comment by Hixie** [comment]
I can't reproduce this. I tried the following app:

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(
    new MaterialApp(
      home: new DefaultTabController(
        length: 2,
        child: new Scaffold(
          body: new NestedScrollView(
            headerSliverBuilder: (BuildContext context, bool innerBoxIsScrolled) {
              return <Widget>[
                new SliverAppBar(
                  pinned: true,
                  expandedHeight: 256.0,
                  forceElevated: innerBoxIsScrolled,
                  flexibleSpace: new FlexibleSpaceBar(
                    title: new Text('title'),
                    background: new Stack(
                      fit: StackFit.expand,
                      children: <Widget>[
                        new Image.network("http://placehold.it/640x320",
                            fit: BoxFit.cover, height: 256.0),
                      ],    
                    ),
                  ),
                  bottom: new TabBar(
                    tabs: [
                      new Tab(text: 'tab1'),
                      new Tab(text: 'tab2'),
                    ],
                  ),
                ),
              ];
            },
            body: new TabBarView(
              children: [
                new ListView(),
                new ListView(),
              ],
            ),
          ),
        ),
      ),
    ),
  );
}
```

...and I don't see any exceptions, dragging up or down, or changing tabs.

Please don't hesitate to reopen if you still see this, though if you do, please provide more code.

**Comment by RobertYeYu** [comment]
How to make FlexibleSpaceBar title overflow to appBar?

**Comment by diegoveloper** [comment]
Hello I have an issue related to this widget, I tried to achieve something similar to CollapsingToolbarLayout + TabLayout , using the example below,  but the result is weird.

Screenshots attached.

Code:

`   @override
     Widget build(BuildContext context) {
       var imageHero = new Hero(
         tag: "${widget._event.id}",
         child: new SizedBox.expand(
          child: new CachedNetworkImage(
            imageUrl: widget._event.image,
            fit: BoxFit.cover,
          ),
        ),
       );

    return new DefaultTabController(
        length: 3,
        child: new Scaffold(
            body: new NestedScrollView(
                headerSliverBuilder:
                    (BuildContext context, bool innerBoxIsScrolled) {
                  return <Widget>[
                    new SliverAppBar(
                      expandedHeight: 180.0,
                      floating: false,
                      pinned: true,
                      titleSpacing: 20.0,
                       forceElevated: innerBoxIsScrolled,
                      iconTheme: theme.CompanyThemeIcon,
                      bottom: new TabBar(
                        tabs: [
                          new Tab(icon: new Icon(Icons.directions_car)),
                          new Tab(icon: new Icon(Icons.directions_transit)),
                          new Tab(icon: new Icon(Icons.directions_bike)),
                        ],
                      ),
                      elevation: defaultTargetPlatform == TargetPlatform.android
                          ? 5.0
                          : 0.0,
                      flexibleSpace: new FlexibleSpaceBar(
                        title: new Text("Testing Flutter",
                            style: new TextStyle(
                              color: Colors.white,
                              fontSize: 14.0,
                            )),
                        background: new Stack(
                          fit: StackFit.expand,
                          children: <Widget>[
                            imageHero,
                            new Positioned(
                                bottom: 0.0,
                                height: 50.0,
                                left: 0.0,
                                right: 0.0,
                                child: Container(
                                  decoration: new BoxDecoration(
                                      gradient: new LinearGradient(
                                          colors: [
                                        Colors.black54,
                                        Colors.black26
                                      ],
                                          stops: [
                                        0.5,
                                        1.0
                                      ],
                                          begin: FractionalOffset.bottomCenter,
                                          end: FractionalOffset.topCenter,
                                          tileMode: TileMode.repeated)),
                                ))
                          ],
                        ),
                      ),
                    ),
                  ];
                },
                body: new TabBarView(
                  children: [
                    new Icon(Icons.directions_car),
                    new Icon(Icons.directions_transit),
                    new Icon(Icons.directions_bike),
                  ],
                ),
                )));
  }
`

![simulator screen shot - iphone 7 - 2018-06-02 at 01 44 59](https://user-images.githubusercontent.com/4898256/40871724-ad4d3aba-6606-11e8-882d-f72dcb07194b.png)
![simulator screen shot - iphone 7 - 2018-06-02 at 01 45 02](https://user-images.githubusercontent.com/4898256/40871725-ad64dd82-6606-11e8-9a65-6e17447f575a.png)

**Comment by rohan-kadkol** [comment]
I had this same problem as you. I followed the below link and solved the problem.
https://medium.com/@diegoveloper/flutter-collapsing-toolbar-sliver-app-bar-14b858e87abe
