### ISSUE TITLE
DSX for Flutter/Dart - XML Based UI Tree Structuring for Dart (Native or Transpiling)

### ISSUE THREAD

**Issue by sangeethnandakumar** [flutter/flutter#101063]
Can we consider an option to introduce JSX or XML-like syntax for Dart?  We may call it DSX.

The current Dart language is inefficient to the human eye at reading tree-like structures, especially when dealing with big codebases

Alternatives like XML are designed for tree-like structuring and are supported by any parser.
These markups clearly show where a Widget starts and ends. Also, it's familiar to devs, easy to write, parsable too

Appreciate it if someone can consider this at least as an optional syntax for productivity-seeking developers.

The current Dart code may be efficient to run but is not looking good to represent a tree in my opinion. I'm now heavily relying on bracket coloring and similar extensions to find the start and end in a complex code. It'll be a breeze if there's some custom-designed language with XML-like syntax. To me, it's really hard now

**Comment by mraleph** [comment]
This has been discussed a lot: https://github.com/flutter/flutter/issues/15922

**Comment by sangeethnandakumar** [comment]
Thank you @mraleph. Just gone through it. Are there any progress there or the idea is abandoned by Flutter team.
Not sure why so many devs are downgrading this. Anyways thanks for mentioning

**Comment by iapicca** [comment]
quote from https://github.com/flutter/flutter/issues/11609#issuecomment-409440643

> I would like to ask that people do not open new bugs on this topic unless there is something very constructive and new that is worth bringing up.

**Comment by goderbauer** [comment]
Closing this as per previous comment.
