### ISSUE TITLE
DropdownButtonFormField more than one item in list. (Windows Desktop)

### ISSUE THREAD

**Issue by Robjl** [flutter/flutter#101051]
Having more than one item in "items" (List<DropdownMenuItem>) causes error. 

This is resolved by changing == 1 to >= 1 in dropdown.dart. Line 1221. See change that resolved issue for me below:

assert(widget.items!.where((DropdownMenuItem<T> item) => item.value == widget.value).length **_`>=`_** 1);

**Comment by darshankawar** [comment]
@Robjl 
Please check if you are hitting same issue as https://github.com/flutter/flutter/issues/56725

**Comment by Robjl** [comment]
Just had a look, the issue is different. I get the issue when the length of the List passed to items is greater than one.

The error was pointing me towards dropdown.dart. Line 1221. The error also suggested I report the issue and gave me a link. 

Original line:
assert(widget.items!.where((DropdownMenuItem item) => item.value == widget.value).length == 1);

Change that resolved issue for me:
assert(widget.items!.where((DropdownMenuItem item) => item.value == widget.value).length >= 1);

**Comment by darshankawar** [comment]
@Robjl 
Thanks for feedback. Can you provide `flutter doctor -v` and a complete minimal reproducible code sample that shows current issue, so that we can debug and address it properly ?
