### ISSUE TITLE
[iOS] Apple Pencil cannot slide and scribble normally after the system's Scribble is turned on

### ISSUE THREAD

**Issue by yy1300326388** [flutter/flutter#101016]
## Steps to Reproduce

1. Open the system [Settings] [Apple Pencil] [Scribble] [Enable]
2. List swipe or doodle is not normal

--- 
If I turn off step 1 everything works fine

![20220330-134622](https://user-images.githubusercontent.com/8764899/160760361-1b9e2ca5-961f-4e21-a340-9d20027a11dc.png)

**Expected results:** 
1. The list can slide normally
2. Graffiti is normal

**Actual results:**
1. The list does not scroll properly
2. The sliding event cannot be accepted normally

|turn off event | turn on event|
|--|--|
|![关闭随手写](https://user-images.githubusercontent.com/8764899/160760638-2707a004-2c27-4867-8dd5-b089fcf386f8.png)|![开启随手写](https://user-images.githubusercontent.com/8764899/160760645-be5ff203-0767-4dcc-b0be-0be302139b56.png)|

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({
    Key? key,
  }) : super(key: key);

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: ListView.builder(
        itemBuilder: (context, index) {
          return ListTile(
            title: Text('Item $index'),
          );
        },
        itemCount: 100,
      ),
    );
  }
}

```

</details>

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel stable, 2.10.4, on macOS 12.1 21C52 darwin-x64, locale
    zh-Hans-CN)
    • Flutter version 2.10.4 at /Users/zero/fvm/versions/2.10.4
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (5 days ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/zero/sdk/android-sdk-macosx
    • Platform android-31, build-tools 30.0.2
    • ANDROID_HOME = /Users/zero/sdk/android-sdk-macosx
    • Java binary at:
      /Library/Java/JavaVirtualMachines/jdk1.8.0_251.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_251-b08)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code (version 1.65.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.36.0

[!] Proxy Configuration
    • HTTP_PROXY is set
    ! NO_PROXY is not set

[✓] Connected device (4 available)
    • iisimpler (mobile) • 00008027-000561E234E2402E            • ios
      • iOS 15.1 19B74
    • iPhone 13 (mobile) • 465F1905-FC7E-4B57-87B0-2F9910F10A8E • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • macOS (desktop)    • macos                                • darwin-x64
      • macOS 12.1 21C52 darwin-x64
    • Chrome (web)       • chrome                               • web-javascript
      • Google Chrome 99.0.4844.83
    ! Error: XGJiPad is not connected. Xcode will continue when XGJiPad is
      connected. (code -13)

[✓] HTTP Host Availability
    • All required HTTP hosts are available
```

</details>

https://user-images.githubusercontent.com/8764899/160759748-89347017-f396-4dfd-85d3-8514c24aa5f5.MP4

https://user-images.githubusercontent.com/8764899/160759832-ffe3d735-9f2c-4cc6-9849-9f53fa1f91d1.MP4

**Comment by yy1300326388** [comment]
new news
If one of my TextFields is focused, it works。
But if I close the app, it still doesn't work.

**Comment by yy1300326388** [comment]
@fbcouch I see that you have submitted an adaptation PR related to Apple Pencil, can you test it further?

**Comment by nutshare** [comment]
I can reproduce the issue with the gesture recognizer, see the code sample below. 

When the feature `[Settings] [Apple Pencil] [Scribble]` is enabled and I'm drawing fast a _curve_ on the screen, then at the beginning of writing with the stylus (apple pen) the recognizer receives the start point, and then the next point is pretty far from the start, all intermediate points are suppressed. This results that the app can not detect based on events that this was a curve. In the events example below the starting point is Offset(519.5, 761.0) and the next point is at Offset(534.0, 522.5) - too far, no intermediate points.

```
flutter: onStart ScaleStartDetails(focalPoint: Offset(519.5, 761.0), localFocalPoint: Offset(519.5, 681.0), pointersCount: 1)
flutter: onUpdate ScaleUpdateDetails(focalPoint: Offset(534.0, 522.5), localFocalPoint: Offset(534.0, 442.5), scale: 1.0, horizontalScale: 1.0, verticalScale: 1.0, rotation: 0.0, pointerCount: 1, focalPointDelta: Offset(534.0, 442.5))
flutter: onEnd ScaleEndDetails(velocity: Velocity(0.0, 0.0), pointerCount: 0)
```

When the feature is disabled, the recognizer receives all the intermediate points, the distance between points is short or I would say the distance is reasonable. In the output example below, the starting point is Offset(549.5, 907.0), then the next one is Offset(548.5, 908.0), and so on.

```
flutter: onStart ScaleStartDetails(focalPoint: Offset(549.5, 907.0), localFocalPoint: Offset(549.5, 827.0), pointersCount: 1)
flutter: onUpdate ScaleUpdateDetails(focalPoint: Offset(548.5, 908.0), localFocalPoint: Offset(548.5, 828.0), scale: 1.0, horizontalScale: 1.0, verticalScale: 1.0, rotation: 0.0, pointerCount: 1, focalPointDelta: Offset(548.5, 828.0))
flutter: onUpdate ScaleUpdateDetails(focalPoint: Offset(546.0, 910.0), localFocalPoint: Offset(546.0, 830.0), scale: 1.0, horizontalScale: 1.0, verticalScale: 1.0, rotation: 0.0, pointerCount: 1, focalPointDelta: Offset(546.0, 830.0))
flutter: onUpdate ScaleUpdateDetails(focalPoint: Offset(543.5, 911.0), localFocalPoint: Offset(543.5, 831.0), scale: 1.0, horizontalScale: 1.0, verticalScale: 1.0, rotation: 0.0, pointerCount: 1, focalPointDelta: Offset(543.5, 831.0))
flutter: onUpdate ScaleUpdateDetails(focalPoint: Offset(540.5, 911.5), localFocalPoint: Offset(540.5, 831.5), scale: 1.0, horizontalScale: 1.0, verticalScale: 1.0, rotation: 0.0, pointerCount: 1, focalPointDelta: Offset(540.5, 831.5))
flutter: onUpdate ScaleUpdateDetails(focalPoint: Offset(537.5, 911.5), localFocalPoint: Offset(537.5, 831.5), scale: 1.0, horizontalScale: 1.0, verticalScale: 1.0, rotation: 0.0, pointerCount: 1, focalPointDelta: Offset(537.5, 831.5))
flutter: onUpdate ScaleUpdateDetails(focalPoint: Offset(533.5, 911.5), localFocalPoint: Offset(533.5, 831.5), scale: 1.0, horizontalScale: 1.0, verticalScale: 1.0, rotation: 0.0, pointerCount: 1, focalPointDelta: Offset(533.5, 831.5))
flutter: onUpdate ScaleUpdateDetails(focalPoint: Offset(531.5, 911.0), localFocalPoint: Offset(531.5, 831.0), scale: 1.0, horizontalScale: 1.0, verticalScale: 1.0, rotation: 0.0, pointerCount: 1, focalPointDelta: Offset(531.5, 831.0))
flutter: onUpdate ScaleUpdateDetails(focalPoint: Offset(529.5, 910.5), localFocalPoint: Offset(529.5, 830.5), scale: 1.0, horizontalScale: 1.0, verticalScale: 1.0, rotation: 0.0, pointerCount: 1, focalPointDelta: Offset(529.5, 830.5))
flutter: onUpdate ScaleUpdateDetails(focalPoint: Offset(524.5, 909.0), localFocalPoint: Offset(524.5, 829.0), scale: 1.0, horizontalScale: 1.0, verticalScale: 1.0, rotation: 0.0, pointerCount: 1, focalPointDelta: Offset(524.5, 829.0))
flutter: onUpdate ScaleUpdateDetails(focalPoint: Offset(519.0, 906.5), localFocalPoint: Offset(519.0, 826.5), scale: 1.0, horizontalScale: 1.0, verticalScale: 1.0, rotation: 0.0, pointerCount: 1, focalPointDelta: Offset(519.0, 826.5))
flutter: onUpdate ScaleUpdateDetails(focalPoint: Offset(513.0, 903.5), localFocalPoint: Offset(513.0, 823.5), scale: 1.0, horizontalScale: 1.0, verticalScale: 1.0, rotation: 0.0, pointerCount: 1, focalPointDelta: Offset(513.0, 823.5))
flutter: onUpdate ScaleUpdateDetails(focalPoint: Offset(506.5, 899.5), localFocalPoint: Offset(506.5, 819.5), scale: 1.0, horizontalScale: 1.0, verticalScale: 1.0, rotation: 0.0, pointerCount: 1, focalPointDelta: Offset(506.5, 819.5))
flutter: onUpdate ScaleUpdateDetails(focalPoint: Offset(498.5, 894.0), localFocalPoint: Offset(498.5, 814.0), scale: 1.0, horizontalScale: 1.0, verticalScale: 1.0, rotation: 0.0, pointerCount: 1, focalPointDelta: Offset(498.5, 814.0))
flutter: onUpdate ScaleUpdateDetails(focalPoint: Offset(490.0, 888.0), localFocalPoint: Offset(490.0, 808.0), scale: 1.0, horizontalScale: 1.0, verticalScale: 1.0, rotation: 0.0, pointerCount: 1, focalPointDelta: Offset(490.0, 808.0))
flutter: onUpdate ScaleUpdateDetails(focalPoint: Offset(480.5, 880.0), localFocalPoint: Offset(480.5, 800.0), scale: 1.0, horizontalScale: 1.0, verticalScale: 1.0, rotation: 0.0, pointerCount: 1, focalPointDelta: Offset(480.5, 800.0))
flutter: onUpdate ScaleUpdateDetails(focalPoint: Offset(469.0, 870.0), localFocalPoint: Offset(469.0, 790.0), scale: 1.0, horizontalScale: 1.0, verticalScale: 1.0, rotation: 0.0, pointerCount: 1, focalPointDelta: Offset(469.0, 790.0))
flutter: onUpdate ScaleUpdateDetails(focalPoint: Offset(456.0, 856.5), localFocalPoint: Offset(456.0, 776.5), scale: 1.0, horizontalScale: 1.0, verticalScale: 1.0, rotation: 0.0, pointerCount: 1, focalPointDelta: Offset(456.0, 776.5))
flutter: onUpdate ScaleUpdateDetails(focalPoint: Offset(442.0, 840.5), localFocalPoint: Offset(442.0, 760.5), scale: 1.0, horizontalScale: 1.0, verticalScale: 1.0, rotation: 0.0, pointerCount: 1, focalPointDelta: Offset(442.0, 760.5))
flutter: onUpdate ScaleUpdateDetails(focalPoint: Offset(426.0, 819.0), localFocalPoint: Offset(426.0, 739.0), scale: 1.0, horizontalScale: 1.0, verticalScale: 1.0, rotation: 0.0, pointerCount: 1, focalPointDelta: Offset(426.0, 739.0))
flutter: onUpdate ScaleUpdateDetails(focalPoint: Offset(410.0, 793.5), localFocalPoint: Offset(410.0, 713.5), scale: 1.0, horizontalScale: 1.0, verticalScale: 1.0, rotation: 0.0, pointerCount: 1, focalPointDelta: Offset(410.0, 713.5))
flutter: onUpdate ScaleUpdateDetails(focalPoint: Offset(396.0, 764.0), localFocalPoint: Offset(396.0, 684.0), scale: 1.0, horizontalScale: 1.0, verticalScale: 1.0, rotation: 0.0, pointerCount: 1, focalPointDelta: Offset(396.0, 684.0))
flutter: onUpdate ScaleUpdateDetails(focalPoint: Offset(385.0, 730.0), localFocalPoint: Offset(385.0, 650.0), scale: 1.0, horizontalScale: 1.0, verticalScale: 1.0, rotation: 0.0, pointerCount: 1, focalPointDelta: Offset(385.0, 650.0))
flutter: onUpdate ScaleUpdateDetails(focalPoint: Offset(377.0, 693.5), localFocalPoint: Offset(377.0, 613.5), scale: 1.0, horizontalScale: 1.0, verticalScale: 1.0, rotation: 0.0, pointerCount: 1, focalPointDelta: Offset(377.0, 613.5))
flutter: onUpdate ScaleUpdateDetails(focalPoint: Offset(372.5, 656.5), localFocalPoint: Offset(372.5, 576.5), scale: 1.0, horizontalScale: 1.0, verticalScale: 1.0, rotation: 0.0, pointerCount: 1, focalPointDelta: Offset(372.5, 576.5))
flutter: onUpdate ScaleUpdateDetails(focalPoint: Offset(371.0, 637.5), localFocalPoint: Offset(371.0, 557.5), scale: 1.0, horizontalScale: 1.0, verticalScale: 1.0, rotation: 0.0, pointerCount: 1, focalPointDelta: Offset(371.0, 557.5))
flutter: onEnd ScaleEndDetails(velocity: Velocity(-1536.2, -4891.9), pointerCount: 0)
```


Here is the code example:

```
import 'package:flutter/gestures.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  void onStart(ScaleStartDetails details) {
    print("onStart $details");
  }

  void onUpdate(ScaleUpdateDetails details) {
    print("onUpdate $details");
  }

  void onEnd(ScaleEndDetails details) {
    print("onEnd $details");
  }

  @override
  Widget build(BuildContext context) {
    final Map<Type, GestureRecognizerFactory> gestures = <Type, GestureRecognizerFactory>{};

    gestures[ScaleGestureRecognizer] = GestureRecognizerFactoryWithHandlers<ScaleGestureRecognizer>(
      () => ScaleGestureRecognizer(debugOwner: this),
      (ScaleGestureRecognizer instance) {
        instance
          ..onStart = onStart
          ..onUpdate = onUpdate
          ..onEnd = onEnd;
      },
    );

    return Scaffold(
      appBar: AppBar(
        title: const Text("test stylus on iOs"),
      ),
      body: RawGestureDetector(
        behavior: HitTestBehavior.translucent,
        child: Container(
          color: Colors.grey,
        ),
        gestures: gestures,
      ),
    );
  }
}

```

flutter doctor:

```
[✓] Flutter (Channel stable, 2.10.4, on macOS 12.3 21E230 darwin-x64, locale en-RU)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2020.3.3)
[✓] VS Code (version 1.64.2)
[✓] Connected device (4 available)
    
[✓] HTTP Host Availability
```

**Comment by yy1300326388** [comment]
> I can reproduce the issue with the gesture recognizer, see the code sample below.
> 
> When the feature `[Settings] [Apple Pencil] [Scribble]` is enabled and I'm drawing fast a _curve_ on the screen, then at the beginning of writing with the stylus (apple pen) the recognizer receives the start point, and then the next point is pretty far from the start, all intermediate points are suppressed. This results that the app can not detect based on events that this was a curve. In the events example below the starting point is Offset(519.5, 761.0) and the next point is at Offset(534.0, 522.5) - too far, no intermediate points.
> 
> ```
> flutter: onStart ScaleStartDetails(focalPoint: Offset(519.5, 761.0), localFocalPoint: Offset(519.5, 681.0), pointersCount: 1)
> flutter: onUpdate ScaleUpdateDetails(focalPoint: Offset(534.0, 522.5), localFocalPoint: Offset(534.0, 442.5), scale: 1.0, horizontalScale: 1.0, verticalScale: 1.0, rotation: 0.0, pointerCount: 1, focalPointDelta: Offset(534.0, 442.5))
> flutter: onEnd ScaleEndDetails(velocity: Velocity(0.0, 0.0), pointerCount: 0)
> ```
> 
> When the feature is disabled, the recognizer receives all the intermediate points, the distance between points is short or I would say the distance is reasonable. In the output example below, the starting point is Offset(549.5, 907.0), then the next one is Offset(548.5, 908.0), and so on.
> 
> ```
> flutter: onStart ScaleStartDetails(focalPoint: Offset(549.5, 907.0), localFocalPoint: Offset(549.5, 827.0), pointersCount: 1)
> flutter: onUpdate ScaleUpdateDetails(focalPoint: Offset(548.5, 908.0), localFocalPoint: Offset(548.5, 828.0), scale: 1.0, horizontalScale: 1.0, verticalScale: 1.0, rotation: 0.0, pointerCount: 1, focalPointDelta: Offset(548.5, 828.0))
> flutter: onUpdate ScaleUpdateDetails(focalPoint: Offset(546.0, 910.0), localFocalPoint: Offset(546.0, 830.0), scale: 1.0, horizontalScale: 1.0, verticalScale: 1.0, rotation: 0.0, pointerCount: 1, focalPointDelta: Offset(546.0, 830.0))
> flutter: onUpdate ScaleUpdateDetails(focalPoint: Offset(543.5, 911.0), localFocalPoint: Offset(543.5, 831.0), scale: 1.0, horizontalScale: 1.0, verticalScale: 1.0, rotation: 0.0, pointerCount: 1, focalPointDelta: Offset(543.5, 831.0))
> flutter: onUpdate ScaleUpdateDetails(focalPoint: Offset(540.5, 911.5), localFocalPoint: Offset(540.5, 831.5), scale: 1.0, horizontalScale: 1.0, verticalScale: 1.0, rotation: 0.0, pointerCount: 1, focalPointDelta: Offset(540.5, 831.5))
> flutter: onUpdate ScaleUpdateDetails(focalPoint: Offset(537.5, 911.5), localFocalPoint: Offset(537.5, 831.5), scale: 1.0, horizontalScale: 1.0, verticalScale: 1.0, rotation: 0.0, pointerCount: 1, focalPointDelta: Offset(537.5, 831.5))
> flutter: onUpdate ScaleUpdateDetails(focalPoint: Offset(533.5, 911.5), localFocalPoint: Offset(533.5, 831.5), scale: 1.0, horizontalScale: 1.0, verticalScale: 1.0, rotation: 0.0, pointerCount: 1, focalPointDelta: Offset(533.5, 831.5))
> flutter: onUpdate ScaleUpdateDetails(focalPoint: Offset(531.5, 911.0), localFocalPoint: Offset(531.5, 831.0), scale: 1.0, horizontalScale: 1.0, verticalScale: 1.0, rotation: 0.0, pointerCount: 1, focalPointDelta: Offset(531.5, 831.0))
> flutter: onUpdate ScaleUpdateDetails(focalPoint: Offset(529.5, 910.5), localFocalPoint: Offset(529.5, 830.5), scale: 1.0, horizontalScale: 1.0, verticalScale: 1.0, rotation: 0.0, pointerCount: 1, focalPointDelta: Offset(529.5, 830.5))
> flutter: onUpdate ScaleUpdateDetails(focalPoint: Offset(524.5, 909.0), localFocalPoint: Offset(524.5, 829.0), scale: 1.0, horizontalScale: 1.0, verticalScale: 1.0, rotation: 0.0, pointerCount: 1, focalPointDelta: Offset(524.5, 829.0))
> flutter: onUpdate ScaleUpdateDetails(focalPoint: Offset(519.0, 906.5), localFocalPoint: Offset(519.0, 826.5), scale: 1.0, horizontalScale: 1.0, verticalScale: 1.0, rotation: 0.0, pointerCount: 1, focalPointDelta: Offset(519.0, 826.5))
> flutter: onUpdate ScaleUpdateDetails(focalPoint: Offset(513.0, 903.5), localFocalPoint: Offset(513.0, 823.5), scale: 1.0, horizontalScale: 1.0, verticalScale: 1.0, rotation: 0.0, pointerCount: 1, focalPointDelta: Offset(513.0, 823.5))
> flutter: onUpdate ScaleUpdateDetails(focalPoint: Offset(506.5, 899.5), localFocalPoint: Offset(506.5, 819.5), scale: 1.0, horizontalScale: 1.0, verticalScale: 1.0, rotation: 0.0, pointerCount: 1, focalPointDelta: Offset(506.5, 819.5))
> flutter: onUpdate ScaleUpdateDetails(focalPoint: Offset(498.5, 894.0), localFocalPoint: Offset(498.5, 814.0), scale: 1.0, horizontalScale: 1.0, verticalScale: 1.0, rotation: 0.0, pointerCount: 1, focalPointDelta: Offset(498.5, 814.0))
> flutter: onUpdate ScaleUpdateDetails(focalPoint: Offset(490.0, 888.0), localFocalPoint: Offset(490.0, 808.0), scale: 1.0, horizontalScale: 1.0, verticalScale: 1.0, rotation: 0.0, pointerCount: 1, focalPointDelta: Offset(490.0, 808.0))
> flutter: onUpdate ScaleUpdateDetails(focalPoint: Offset(480.5, 880.0), localFocalPoint: Offset(480.5, 800.0), scale: 1.0, horizontalScale: 1.0, verticalScale: 1.0, rotation: 0.0, pointerCount: 1, focalPointDelta: Offset(480.5, 800.0))
> flutter: onUpdate ScaleUpdateDetails(focalPoint: Offset(469.0, 870.0), localFocalPoint: Offset(469.0, 790.0), scale: 1.0, horizontalScale: 1.0, verticalScale: 1.0, rotation: 0.0, pointerCount: 1, focalPointDelta: Offset(469.0, 790.0))
> flutter: onUpdate ScaleUpdateDetails(focalPoint: Offset(456.0, 856.5), localFocalPoint: Offset(456.0, 776.5), scale: 1.0, horizontalScale: 1.0, verticalScale: 1.0, rotation: 0.0, pointerCount: 1, focalPointDelta: Offset(456.0, 776.5))
> flutter: onUpdate ScaleUpdateDetails(focalPoint: Offset(442.0, 840.5), localFocalPoint: Offset(442.0, 760.5), scale: 1.0, horizontalScale: 1.0, verticalScale: 1.0, rotation: 0.0, pointerCount: 1, focalPointDelta: Offset(442.0, 760.5))
> flutter: onUpdate ScaleUpdateDetails(focalPoint: Offset(426.0, 819.0), localFocalPoint: Offset(426.0, 739.0), scale: 1.0, horizontalScale: 1.0, verticalScale: 1.0, rotation: 0.0, pointerCount: 1, focalPointDelta: Offset(426.0, 739.0))
> flutter: onUpdate ScaleUpdateDetails(focalPoint: Offset(410.0, 793.5), localFocalPoint: Offset(410.0, 713.5), scale: 1.0, horizontalScale: 1.0, verticalScale: 1.0, rotation: 0.0, pointerCount: 1, focalPointDelta: Offset(410.0, 713.5))
> flutter: onUpdate ScaleUpdateDetails(focalPoint: Offset(396.0, 764.0), localFocalPoint: Offset(396.0, 684.0), scale: 1.0, horizontalScale: 1.0, verticalScale: 1.0, rotation: 0.0, pointerCount: 1, focalPointDelta: Offset(396.0, 684.0))
> flutter: onUpdate ScaleUpdateDetails(focalPoint: Offset(385.0, 730.0), localFocalPoint: Offset(385.0, 650.0), scale: 1.0, horizontalScale: 1.0, verticalScale: 1.0, rotation: 0.0, pointerCount: 1, focalPointDelta: Offset(385.0, 650.0))
> flutter: onUpdate ScaleUpdateDetails(focalPoint: Offset(377.0, 693.5), localFocalPoint: Offset(377.0, 613.5), scale: 1.0, horizontalScale: 1.0, verticalScale: 1.0, rotation: 0.0, pointerCount: 1, focalPointDelta: Offset(377.0, 613.5))
> flutter: onUpdate ScaleUpdateDetails(focalPoint: Offset(372.5, 656.5), localFocalPoint: Offset(372.5, 576.5), scale: 1.0, horizontalScale: 1.0, verticalScale: 1.0, rotation: 0.0, pointerCount: 1, focalPointDelta: Offset(372.5, 576.5))
> flutter: onUpdate ScaleUpdateDetails(focalPoint: Offset(371.0, 637.5), localFocalPoint: Offset(371.0, 557.5), scale: 1.0, horizontalScale: 1.0, verticalScale: 1.0, rotation: 0.0, pointerCount: 1, focalPointDelta: Offset(371.0, 557.5))
> flutter: onEnd ScaleEndDetails(velocity: Velocity(-1536.2, -4891.9), pointerCount: 0)
> ```
> 
> Here is the code example:
> 
> ```
> import 'package:flutter/gestures.dart';
> import 'package:flutter/material.dart';
> 
> void main() {
>   runApp(const MyApp());
> }
> 
> class MyApp extends StatelessWidget {
>   const MyApp({Key? key}) : super(key: key);
> 
>   @override
>   Widget build(BuildContext context) {
>     return MaterialApp(
>       title: 'Flutter Demo',
>       theme: ThemeData(
>         primarySwatch: Colors.blue,
>       ),
>       home: const MyHomePage(),
>     );
>   }
> }
> 
> class MyHomePage extends StatefulWidget {
>   const MyHomePage({Key? key}) : super(key: key);
> 
>   @override
>   State<MyHomePage> createState() => _MyHomePageState();
> }
> 
> class _MyHomePageState extends State<MyHomePage> {
>   void onStart(ScaleStartDetails details) {
>     print("onStart $details");
>   }
> 
>   void onUpdate(ScaleUpdateDetails details) {
>     print("onUpdate $details");
>   }
> 
>   void onEnd(ScaleEndDetails details) {
>     print("onEnd $details");
>   }
> 
>   @override
>   Widget build(BuildContext context) {
>     final Map<Type, GestureRecognizerFactory> gestures = <Type, GestureRecognizerFactory>{};
> 
>     gestures[ScaleGestureRecognizer] = GestureRecognizerFactoryWithHandlers<ScaleGestureRecognizer>(
>       () => ScaleGestureRecognizer(debugOwner: this),
>       (ScaleGestureRecognizer instance) {
>         instance
>           ..onStart = onStart
>           ..onUpdate = onUpdate
>           ..onEnd = onEnd;
>       },
>     );
> 
>     return Scaffold(
>       appBar: AppBar(
>         title: const Text("test stylus on iOs"),
>       ),
>       body: RawGestureDetector(
>         behavior: HitTestBehavior.translucent,
>         child: Container(
>           color: Colors.grey,
>         ),
>         gestures: gestures,
>       ),
>     );
>   }
> }
> ```
> 
> flutter doctor:
> 
> ```
> [✓] Flutter (Channel stable, 2.10.4, on macOS 12.3 21E230 darwin-x64, locale en-RU)
> [!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
>     ✗ cmdline-tools component is missing
>       Run `path/to/sdkmanager --install "cmdline-tools;latest"`
>       See https://developer.android.com/studio/command-line for more details.
>     ✗ Android license status unknown.
>       Run `flutter doctor --android-licenses` to accept the SDK licenses.
>       See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
> [✓] Xcode - develop for iOS and macOS (Xcode 13.3)
> [✓] Chrome - develop for the web
> [✓] Android Studio (version 2021.1)
> [✓] IntelliJ IDEA Ultimate Edition (version 2020.3.3)
> [✓] VS Code (version 1.64.2)
> [✓] Connected device (4 available)
>     
> [✓] HTTP Host Availability
> ```

thanks for you test

**Comment by fbcouch** [comment]
Can you give it a try on the beta channel? I suspect it may have something to do with the engine PR landing in 2.10, but the framework PR not making it in until 2.12

I will try to test later today as well

**Comment by yy1300326388** [comment]
The ipad is in the company, and I need to come to the company tomorrow morning to test it. I am very happy to test the beta channel version. I will continue to provide feedback as there is progress.

**Comment by cyanglaz** [comment]
@justinmc might have some idea about this?

**Comment by fbcouch** [comment]
I did some testing here, with the following results:

In 2.12:

* If no text fields exist, the problem occurs
* If a text field exists, the problem does not occur

In 2.10:

* If no text fields exist, the problem occurs
* If a text field exists, the problem occurs
* If a text field has received focus (even if unfocused now), the problem does not occur

The problem is definitely caused by the IndirectScribbleInteraction business that I added to the engine; however, I think the difference between 2.12 and 2.10 behavior is that the TextInput instance gets created sooner, and all that really needs to happen is that the text input channel can respond to the TextInput.requestElementsInRect message, even if it responds with nothing.

Here's a wrong (but working) fix for 2.10.4:

```
diff --cc packages/flutter/lib/src/services/text_input.dart
index f546c36ab0,1323765352..0000000000
--- a/packages/flutter/lib/src/services/text_input.dart
+++ b/packages/flutter/lib/src/services/text_input.dart
@@@ -1445,6 -1541,6 +1445,10 @@@ class TextInput 
  
    static final TextInput _instance = TextInput._();
  
++  static ensure() {
++    _instance;
++  }
++
    static const List<TextInputAction> _androidSupportedInputActions = <TextInputAction>[
      TextInputAction.none,
      TextInputAction.unspecified,
```

Then in the `_MyHomePageState` of the above example:
```
@override
void initState() {
  super.initState();
  TextInput.ensure();
}
```

Since that's also a problem in 2.12 if there aren't any text fields yet, let me know if you have thoughts on a better way to go about that – basically the SystemChannels.textInput method channel needs a method call handler

**Comment by nutshare** [comment]
@fbcouch both fixes work, the second one in the `binding.dart` is better since it doesn't introduce dependency in apps. 
appreciate your time and so quick solution, totally awesome!

**Comment by yy1300326388** [comment]
I test method 2 works

**Comment by TahaTesser** [comment]
Hi everyone, I can confirm this issue as well


https://user-images.githubusercontent.com/48603081/161035577-bf0231a8-2fd3-41d5-9758-c64f831dc44e.mp4


<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel master, 2.13.0-0.0.pre.332, on macOS 12.3 21E230 darwin-arm, locale en-GB)
    • Flutter version 2.13.0-0.0.pre.332 at /Users/tahatesser/Code/flutter_nevercode
    • Upstream repository git@github.com:NevercodeHQ/flutter.git
    • Framework revision 7557281fb2 (4 hours ago), 2022-03-31 02:40:11 -0400
    • Engine revision be7fffa8cf
    • Dart version 2.17.0 (build 2.17.0-251.0.dev)
    • DevTools version 2.11.4

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc2)
    • Android SDK at /Users/tahatesser/Code/android-sdk
    • Platform android-32, build-tools 33.0.0-rc2
    • ANDROID_SDK_ROOT = /Users/tahatesser/Code/android-sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] VS Code (version 1.65.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.36.0

[✓] Connected device (4 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554             • android-arm64  • Android 12 (API 31) (emulator)
    • Taha’s iPad (mobile)        • 00008020-000255113EE8402E • ios            • iOS 15.4 19E241
    • macOS (desktop)             • macos                     • darwin-arm64   • macOS 12.3 21E230 darwin-arm
    • Chrome (web)                • chrome                    • web-javascript • Google Chrome 99.0.4844.84

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
	 
</details>

**Comment by theniceboy** [comment]
Can confirm this issue exists in 2.10.5
