### ISSUE TITLE
[google_sign_in] web implemented uses deprecated APIs

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#101004]
Our [`google_sign_in`](https://pub.dev/packages/google_sign_in) plugin is using an old "GSI v2" API that is being deprecated.

The new API library is the "Google Identity Services" API:
 - [ ] Web - https://developers.google.com/identity/gsi/web
 - [ ] ~Android - https://developers.google.com/identity/one-tap/android~

(on iOS, it appears the existing library may still be the recommended API)

**Comment by tvolkert** [comment]
- Beginning April 30th, 2022 new applications must use the Google Identity Services library, existing apps may continue using the Platform Library until the deprecation date.
- On March 31, 2023 we will fully retire the Google Sign-In JavaScript Platform Library and would like to remind you to check if this affects your web application, and if necessary, to plan for a migration.

**Comment by blasten** [comment]
cc @camsim99

**Comment by tvolkert** [comment]
I believe just web.  @brdaugherty

**Comment by tvolkert** [comment]
More info for web (some of the links will only work for Google employees):

* We should provide a new plug-in based on GIS. RP code changes are required for developers to migrate from GSI plug-in to GIS plug-in, since there are so many incompatible changes between GSI and GIS.  More details at [Authentication Changes](http://go/gsi-button-changes) and [Authorization Changes](http://go/3p-auth-changes)
* GIS provides both an [HTML API](https://developers.google.com/identity/gsi/web/reference/html-reference) and a [JavaScript API](https://developers.google.com/identity/gsi/web/reference/js-reference).  They provided equivalent functions. You can try out the [GSI playground](https://gsi-playground.appspot.com/) to get familiar with the APIs
* There's a [code generator](https://developers.google.com/identity/gsi/web/tools/configurator) tool for developers, which may help you to understand GIS API. I am thinking maybe we can extend that tool to generate Dart code (after you have the GIS plug-in ready). Or you have a similar tool for your developers, to generate Dart code for GIS integration.

**Comment by brdaugherty** [comment]
The deprecation applies only to the JavaScript library for web apps.  Android and iOS native apps should continue using their respective SDKs.

Not mentioned in the above resources is the deprecation of the gapi.auth2 module found in the [Google API Client Library for JavaScript](https://github.com/google/google-api-javascript-client). This module is shared with Google Sign-in platform.js library. The deprecation affects both. It is very likely you've reviewed the developer migration guides already, but for completeness: for user [sign-in](https://developers.google.com/identity/gsi/web/guides/migration) and for [authorization](https://developers.google.com/identity/oauth2/web/guides/migration-to-gis#overview ).

**Comment by ditman** [comment]
Deduplicating with: https://github.com/flutter/flutter/issues/88084

**Comment by anggoran** [comment]
Shouldn't the new package (gms.auth.api.identity) be implemented too in Android (?)

The package has setNonce method that is useful for replay attack mitigation in OpenID Oauth, which we don't have in the old package:
[BeginSignInRequest.GoogleIdTokenRequestOptions.Builder](https://developers.google.com/android/reference/com/google/android/gms/auth/api/identity/BeginSignInRequest.GoogleIdTokenRequestOptions.Builder?hl=en)
[GetSignInIntentRequest.Builder](https://developers.google.com/android/reference/com/google/android/gms/auth/api/identity/GetSignInIntentRequest.Builder?hl=en) 

Firebase use nonce optionally because the old android google sign in package doesn't have nonce settings, whilst other provider like apple and facebook have:
[FirebaseAuth (Code Line 210)](https://github.com/firebase/flutterfire/blob/master/packages/firebase_auth/firebase_auth/android/src/main/java/io/flutter/plugins/firebase/auth/FlutterFirebaseAuthPlugin.java) 

[Google OpenID Connect](https://developers.google.com/identity/protocols/oauth2/openid-connect)

**Comment by brdaugherty** [comment]
For Android see the new [One Tap](https://developers.google.com/identity/one-tap/android/get-saved-credentials) sign-in method which includes nonce support.

**Comment by anggoran** [comment]
That is what I meant, the new one tap sign-in method uses gms.auth.api.identity, whilst our current google_sign_in_android (flutter package) uses gms.auth.api.signin, which doesn't come with neither one tap sign in nor setNonce
[google_sign_in_android Java code](https://github.com/flutter/plugins/blob/main/packages/google_sign_in/google_sign_in_android/android/src/main/java/io/flutter/plugins/googlesignin/GoogleSignInPlugin.java)

**Comment by camsim99** [comment]
> That is what I meant, the new one tap sign-in method uses gms.auth.api.identity, whilst our current google_sign_in_android (flutter package) uses gms.auth.api.signin, which doesn't come with neither one tap sign in nor setNonce [google_sign_in_android Java code](https://github.com/flutter/plugins/blob/main/packages/google_sign_in/google_sign_in_android/android/src/main/java/io/flutter/plugins/googlesignin/GoogleSignInPlugin.java)

We do need to migrate Android to this. I'll file a separate issue for this.
