### ISSUE TITLE
Animations on Android do not respect the duration scale value

### ISSUE THREAD

**Issue by philipgiuliani** [flutter/flutter#10101]
On Android its possible to change the speed of the animations in the Developer settings. I have set all of them to `0.5x` but my (first) flutter app does not respect the speed.

**How to reproduce this issue:**
- Go into developer settings
- Set all scales to another value than 1x

**What do I expect?**
The Flutter example app should also change the speeds of the animations

**Whats the result?**
Animation speeds in the Flutter example app are the same.

**Comment by eseidelGoogle** [comment]
Likely an easy fix.  But yes, we have no code to plumb this value up to flutter now.  Not sure if this is just a development issue or if this is also an accessibility option.

**Comment by Hixie** [comment]
I looked into this. There's no official way for us to read the scale value (it's hidden in `ValueAnimator`), and, more importantly, there's no way for us to receive a notification of when the value changes (the notification is a private API with a method ID that varies per device).

See `getWindowSession` in https://android.googlesource.com/platform/frameworks/base/+/master/core/java/android/view/WindowManagerGlobal.java (this is the app side of the framework).
See `UPDATE_ANIMATION_SCALE` in https://android.googlesource.com/platform/frameworks/base/+/master/services/core/java/com/android/server/wm/WindowManagerService.java (this is the OS side).
See `getDurationScale` in https://android.googlesource.com/platform/frameworks/base/+/refs/heads/master/core/java/android/animation/ValueAnimator.java (note that it's marked `@TestApi`).
And finally see https://android.googlesource.com/platform/frameworks/base/+blame/refs/heads/master/core/java/android/view/IWindowSessionCallback.aidl and the code that calls it (this is the way the OS signals the app, but that API isn't ABI-stable).

**Comment by darshankawar** [comment]
Closing based on [this](https://github.com/flutter/flutter/issues/10101#issuecomment-398940831) comment. If you disagree or think it was closed by mistake and should be kept open, please write in comments and I'll reopen.
Thanks.
