### ISSUE TITLE
OOM when using DevTools

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#101002]
## Description
When using DevTools I get an Out-of-memory (OOM) crash consistently after clicking on a few Timeline events.  I'm not sure if this is a DevTools problem or the server running in the engine.

## Log
```
[ +363 ms] The Flutter DevTools debugger and profiler on Aaron’s iPhone is available at:
                    http://127.0.0.1:9103?uri=http://127.0.0.1:62476/lKbnF7dAj0o=/
[+29851 ms] Process 6304 stopped
[   +1 ms] ../../third_party/dart/runtime/platform/allocation.cc: 22: error: Out of memory.
[        ] version=2.17.0-239.0.dev (dev) (Thu Mar 24 23:22:40 2022 -0700) on "ios_arm64"
[        ] pid=6304, thread=43011, isolate_group=main(0x10082c800), isolate=main(0x10083ba00)
[        ] isolate_instructions=1093bc820, vm_instructions=1093b7c50
```

## Doctor
<details>

```
[✓] Flutter (Channel flutter-2.12-candidate.9, 2.13.0-0.0.pre.273, on macOS 12.3 21E230 darwin-x64, locale en-US)
    • Flutter version 2.13.0-0.0.pre.273 at /Users/aaclarke/dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6e164e713d (3 hours ago), 2022-03-29 13:18:36 -0700
    • Engine revision ca2f95c71c
    • Dart version 2.17.0 (build 2.17.0-239.0.dev)
    • DevTools version 2.11.4

[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/aaclarke/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio
    • Android Studio at /Applications/Android Studio with Blaze Beta.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio with Blaze.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.65.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.36.0

[✓] Connected device (3 available)
    • Aaron’s iPhone (mobile) • 00008030-000614363C43802E • ios            • iOS 15.2.1 19C63
    • macOS (desktop)         • macos                     • darwin-x64     • macOS 12.3 21E230 darwin-x64
    • Chrome (web)            • chrome                    • web-javascript • Google Chrome 99.0.4844.84

[✓] HTTP Host Availability
    • All required HTTP hosts are available
```

</details>

cc @kenzieschmoll

**Comment by kenzieschmoll** [comment]
Just to be clear - is this the connected iOS app crashing with an OOM? Are you using a simulator or a real iOS device?

**Comment by chinmaygarde** [comment]
cc @dnfield and @jonahwilliams for filing an issue about the "performance of performance tools".

**Comment by gaaclarke** [comment]
> Just to be clear - is this the connected iOS app crashing with an OOM, not DevTools crashing with an OOM? Are you using a simulator or a real iOS device?

I'm using a real iOS device.

**Comment by gaaclarke** [comment]
> I believe this is the target process running out of memory. 

Yep, it's the target process, but it could be a bug in either location.  If the DevTools makes an unreasonable request the target process will crash and it would be a bug in DevTools.

**Comment by gaaclarke** [comment]
Here is the instruments profile for the default flutter counter app while I click around on the timeline (the app is idle):
<img width="1709" alt="Screen Shot 2022-04-07 at 3 51 00 PM" src="https://user-images.githubusercontent.com/30870216/162332262-82c0d398-931c-4c5d-8d4e-6f2e8cff2186.png">

I looked into the hill at 3m15s and most of the allocations seem to be happening in `dart::ProfilerService::PrintJSON`.
```
  16.02 MB      88.0%	1023	 	     CFRunLoopRunSpecific
  16.02 MB      88.0%	1023	 	      __CFRunLoopRun
  16.02 MB      88.0%	1023	 	       __CFRunLoopDoTimers
  16.02 MB      88.0%	1023	 	        __CFRunLoopDoTimer
  16.02 MB      88.0%	1023	 	         __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__
  16.02 MB      88.0%	1023	 	          fml::MessageLoopDarwin::OnTimerFire(__CFRunLoopTimer*, fml::MessageLoopDarwin*)
  16.02 MB      88.0%	1023	 	           fml::MessageLoopImpl::FlushTasks(fml::FlushType)
  16.00 MB      87.9%	20	 	            std::__1::__function::__func<flutter::DartIsolate::SetMessageHandlingTaskRunner(fml::RefPtr<fml::TaskRunner>)::$_3::operator()(std::__1::function<void ()>) const::'lambda'(), std::__1::allocator<flutter::DartIsolate::SetMessageHandlingTaskRunner(fml::RefPtr<fml::TaskRunner>)::$_3::operator()(std::__1::function<void ()>) const::'lambda'()>, void ()>::operator()()
  16.00 MB      87.9%	20	 	             std::__1::__function::__func<tonic::DartMessageHandler::OnMessage(tonic::DartState*)::$_0, std::__1::allocator<tonic::DartMessageHandler::OnMessage(tonic::DartState*)::$_0>, void ()>::operator()()
  16.00 MB      87.9%	20	 	              tonic::DartMessageHandler::OnHandleMessage(tonic::DartState*)
  16.00 MB      87.9%	20	 	               Dart_HandleMessage
  16.00 MB      87.9%	20	 	                dart::MessageHandler::HandleNextMessage()
  16.00 MB      87.9%	20	 	                 dart::MessageHandler::HandleMessages(dart::MonitorLocker*, bool, bool)
  16.00 MB      87.9%	20	 	                  dart::IsolateMessageHandler::HandleMessage(std::__1::unique_ptr<dart::Message, std::__1::default_delete<dart::Message> >)
  16.00 MB      87.9%	20	 	                   dart::Service::HandleIsolateMessage(dart::Isolate*, dart::Array const&)
  16.00 MB      87.9%	20	 	                    dart::Service::InvokeMethod(dart::Isolate*, dart::Array const&, bool)
  16.00 MB      87.9%	20	 	                     dart::ProfilerService::PrintJSON(dart::JSONStream*, long long, long long, bool)
  16.00 MB      87.9%	20	 	                      dart::ProfilerService::PrintJSONImpl(dart::Thread*, dart::JSONStream*, dart::SampleFilter*, dart::ProcessedSampleBufferBuilder*, bool)
  16.00 MB      87.9%	4	 	                       dart::Profile::PrintProfileJSON(dart::JSONObject*, bool, bool)
  16.00 MB      87.9%	4	 	                        dart::ProfileFunction::PrintToJSONArray(dart::JSONArray*, bool)
  16.00 MB      87.9%	4	 	                         dart::Function::PrintJSONImpl(dart::JSONStream*, bool) const
  16.00 MB      87.9%	2	 	                          dart::Function::PrintJSONImpl(dart::JSONStream*, bool) const
  16.00 MB      87.9%	1	 	                           dart::Function::PrintJSONImpl(dart::JSONStream*, bool) const
  16.00 MB      87.9%	1	 	                            dart::Library::PrintJSONImpl(dart::JSONStream*, bool) const
  16.00 MB      87.9%	1	 	                             dart::JSONWriter::PrintPropertyStr(char const*, dart::String const&, long, long)
  16.00 MB      87.9%	1	 	                              dart::JSONWriter::PrintPropertyName(char const*)
  16.00 MB      87.9%	1	 	                               dart::BaseTextBuffer::EscapeAndAddCodeUnit(unsigned int)
  16.00 MB      87.9%	1	 	                                dart::TextBuffer::EnsureCapacity(long)
```

**Comment by kenzieschmoll** [comment]
@bkonyi

**Comment by bkonyi** [comment]
Are you clicking timeline events in rapid succession by any chance? Each selection of a timeline event can (will?) trigger a CPU sample profile request to the VM.

**Comment by gaaclarke** [comment]
> Are you clicking timeline events in rapid succession by any chance? Each selection of a timeline event can (will?) trigger a CPU sample profile request to the VM.

Yep, all I'm doing is clicking around on the Timeline events.  I wouldn't say I'm doing it at an unreasonable rate, maybe 1-2 per second?

**Comment by bkonyi** [comment]
If there's a lot of samples to be streamed it can easily generate MBs of data. Does it happen if you interact with it more slowly?

**Comment by gaaclarke** [comment]
> If there's a lot of samples to be streamed it can easily generate MBs of data. Does it happen if you interact with it more slowly?

I was encountering these OOMs when I was really using `DevTools` with [`debugProfileBuildsEnabled`](https://api.flutter.dev/flutter/widgets/debugProfileBuildsEnabled.html) turned on so the sample would have been a lot larger.  I wasn't clicking around like a maniac to see what happens lol.  The device was an iPhone SE 2 so it has a reasonable amount of memory.

I didn't have `debugProfileBuildsEnabled` turned on when I was doing the profiling.

**Comment by zanderso** [comment]
I think @bkonyi is doing some investigations around figuring out how to improve this. This is going to take some time, so I'm going to downgrade this to P3.

**Comment by zanderso** [comment]
@bkonyi Is this still on your radar?

**Comment by a-siva** [comment]
@bkonyi @derekxu Now that we have support for Perfetto, Is the OOM issue in devtools solved?

**Comment by bkonyi** [comment]
It's unclear if Perfetto support will resolve the OOM issue for DevTools yet as DevTools still hasn't migrated to the new format. There's a P1 OKR for that work this quarter (cc @kenzieschmoll @CoderDake)

**Comment by kenzieschmoll** [comment]
This work is tracked on the DevTools side at https://github.com/flutter/devtools/issues/4755. When that is resolved, this issue can be readdressed.

**Comment by a-siva** [comment]
@kenzieschmoll this has been closed I presume because devtools now supports Perfetto but the general sentiment expressed at the weekly VM meeting was that this is still an issue if CPU profiles are included in the timeline events and only when devtools directly uses the protozero format for getting perfetto timelines this would be addressed (please see  https://github.com/dart-lang/sdk/issues/47631).
The VM now supports protozero format not sure if there is already an open issue in devtools for adding support to use the protozero support in the VM.

**Comment by kenzieschmoll** [comment]
> this is still an issue if CPU profiles are included in the timeline events

With the Perfetto trace viewer, we do not include any CPU samples with the timeline events, so I closed the issue since the OOM only applies to the legacy trace viewer. When we switch to the protozero based VM Service APIs that Derek added, we will get the CPU samples back in the timeline. This is tracked here (https://github.com/flutter/devtools/issues/4755) and is on the docket for Q1.
