### ISSUE TITLE
Update popup menus to support Material 3

### ISSUE THREAD

**Issue by guidezpl** [flutter/flutter#101017]
As part of the [Material 3 specification](https://m3.material.io/components/menus/overview) there are updates to Popup Menu's visuals:

![image](https://user-images.githubusercontent.com/6655696/169653672-5cb6dd72-9a2c-4814-a341-f318ca1880a0.png)

We should update the `PopupMenuX` classes to support this Material 3 look.

**Comment by TahaTesser** [comment]
Menu tokens are [available](https://github.com/flutter/flutter/blob/master/dev/tools/gen_defaults/data/menu.json), working on this migration.

**Comment by TahaTesser** [comment]
`Popup menu` PR landed
https://github.com/flutter/flutter/pull/103606
