### ISSUE TITLE
The flutter create . command overrides my code in the web directory

### ISSUE THREAD

**Issue by capps096github** [flutter/flutter#101029]
Describe your issue and include the command you're running, flutter_web version, browser version

The flutter create . command overrides my code in the web directory, and this takes me back to recreate some of these files, like the manifest.json, the icons and most of the code in the index.html for example the firebase CDN commands

**Comment by maheshmnj** [comment]
Hi @capps096github, Thanks for filing the issue. What host platform are you using ? Please share the output of flutter doctor -v`, Running `flutter create .`  is only supposed to add the missing files and not rewrite existing files.

the flutter create doc reads

> If run on a project that already exists, this will repair the project, recreating any files that are missing.
