### ISSUE TITLE
[macOS][m1] App crashes in master channel debug mode if hardened runtime is enabled

### ISSUE THREAD

**Issue by TabooSun** [flutter/flutter#101040]
## Steps to Reproduce

1. `flutter channel stable`
2. `flutter upgrade`
3. `flutter create playground_old --platforms macos`
4. `cd playground_old`
5. `flutter run` <-- does not crash
6. `flutter channel master`
7. `flutter upgrade`
8. Open Xcode and remove arm64 from Excluded Architectures
9. `flutter run` <-- crashes

**Expected results:** App does not crash

**Actual results:** App crashes

The flutter run output is too long...I create a [gist for it here](https://gist.github.com/TabooSun/32c67130debd4b2f2ed3da19641fcf29).

<details>
  <summary>Logs</summary>

```

[✓] Flutter (Channel master, 2.13.0-0.0.pre.313, on macOS 12.3 21E230 darwin-arm, locale zh-Hans-MY)
    • Flutter version 2.13.0-0.0.pre.313 at /Users/taboosun/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 02b2c2cde6 (2 hours ago), 2022-03-30 12:50:12 +0300
    • Engine revision 6ad06a5d89
    • Dart version 2.17.0 (build 2.17.0-249.0.dev)
    • DevTools version 2.11.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/taboosun/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/taboosun/Library/Android/sdk
    • Java binary at: /Users/taboosun/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/211.7628.21.2111.8193401/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Users/taboosun/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/211.7628.21.2111.8193401/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] Android Studio (version 2021.1)
    • Android Studio at /Users/taboosun/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/211.7628.21.2111.8139111/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.3)
    • IntelliJ at /Users/taboosun/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 65.2.4
    • Dart plugin version 213.7306

[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.3)
    • IntelliJ at /Users/taboosun/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/213.7172.25/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.2)
    • IntelliJ at /Users/taboosun/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/213.6777.52/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.64.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.34.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.3 21E230 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 99.0.4844.84
    ! Error: 神的iPad is not connected. Xcode will continue when 神的iPad is connected. (code -13)
    ! Error: Kah Wai’s iPhone is not connected. Xcode will continue when Kah Wai’s iPhone is connected. (code -13)

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

</details>

**Comment by TabooSun** [comment]
**Update**

Actually I have tested another round, I can't use the steps above to reproduce.

**Comment by TabooSun** [comment]
**Update**

I have found the correct combination of configurations to trigger this. Follow these steps:
1. `flutter create playground_old --platforms macos`
2. `cd playground_old`
3. `flutter run` <-- does not crash
4. Enable `Hardened Runtime` in Xcode Capabilities
5. Uncheck `Allow Execution of JIT-compiled Code`
6. Check `Disable Library Validation`
<img width="2178" alt="image" src="https://user-images.githubusercontent.com/31196825/160965613-a033aaab-1aa7-4917-8e9f-0b7586b5b4e9.png">

**Comment by darshankawar** [comment]
> * Enable `Hardened Runtime` in Xcode Capabilities
> * Uncheck `Allow Execution of JIT-compiled Code`
> * Check `Disable Library Validation`

Any specific reason you are changing these settings ?

**Comment by TabooSun** [comment]
Anyway, I need `Hardened Runtime` in order to let my app be sent for [Apple Notarization](https://developer.apple.com/documentation/security/hardened_runtime).
As for the reason for unchecking `Allow Execution of JIT-compiled Code`, I can't recall. I tested it just now by checking it and now it works! I probably just wanted to save app resources that time so that everything is AOT. 

Hmm, then I am curious in this case why it worked for me in flutter stable channel with `Allow Execution of JIT-compiled Code` unchecked.

**Comment by darshankawar** [comment]
@TabooSun 
Do you have apple developer account and signed in using Xcode and have signing certificate in place ?
Also checkout this issue and underlying comments and see if they help.

If above isn't relatable, can you provide what's the exact / current status / issue are you facing ?

**Comment by TabooSun** [comment]
Sorry for the messy info. 

The issue is actually considered resolved. I just need to create another `Hardened Runtime` configuration dedicated for Debug so that I can check the `Allow Execution of JIT-compiled Code` in Profile/Release. Something like this:
<img width="1836" alt="image" src="https://user-images.githubusercontent.com/31196825/161064724-94e053f4-7ae6-4ced-850d-a039db015048.png">

Even though the issue is considered resolved, I just want to know the reason why it crashes by unchecking `Allow Execution of JIT-compiled Code`. Because this might be worth to be documented if there is no fix being planned.

I personally don't think this issue is related to code signing because as I mentioned, it worked on `flutter stable channel`. 

In addition, the funny thing is that if I just run the project in Xcode, it will work; however, if I run it in `flutter run`, it will crash.

I have uploaded a dummy project [here](https://github.com/TabooSun/playground_old).

You can try it with a few test cases as shown below:

Test case 1: Use `flutter run` to debug <-- this will crash
Test case 2: Open Xcode using `open macos/Runner.xcworkspace` and do `Product > Run` <-- this will not crash
Test case 3: Switch to flutter stable channel, perform `flutter clean` and finally run `flutter run` <-- this will not crash

**Comment by darshankawar** [comment]
@TabooSun 
Please check below issue comments and see if they help you to understand / resolve your queries further:

https://github.com/flutter/flutter/issues/35651#issuecomment-510887577
https://github.com/flutter/flutter/issues/35651#issuecomment-510888196
https://github.com/flutter/flutter/issues/35651#issuecomment-510931110
https://github.com/flutter/flutter/issues/35651#issuecomment-510931110
