### ISSUE TITLE
Add Material 3 interactive dartpad samples

### ISSUE THREAD

**Issue by guidezpl** [flutter/flutter#101048]
This is a tracking issue for adding interactive code samples (with `{@tool dartpad}`) to components and widgets which support Material 3. 

We should consider leveraging existing existing code samples by either
- wrapping existing samples with a common widget which shows a toggle to switch the sample to Material 3, at some point, have that be the default (preferred, IMO)
- copy the simplest existing sample and adding `useMaterial3: true` 

For new Material 3-only widgets, such as `NavigationBar`, the [API doc](https://master-api.flutter.dev/flutter/material/NavigationBar-class.html) will only show the Material 3 look.

cc @darrenaustin WDYT?

### Components
- [ ] Buttons
- [x] https://github.com/flutter/flutter/pull/101105
- [ ] #100532
- [x] https://github.com/flutter/flutter/pull/101508
- [x] `NavigationBar`
- [x] https://github.com/flutter/flutter/pull/101345
- [x] https://github.com/flutter/flutter/pull/102823 and https://github.com/flutter/flutter/pull/103962

### Other widgets

**Comment by TahaTesser** [comment]
@guidezpl 

i can help with this, let me know :)

**Comment by darrenaustin** [comment]
This sounds reasonable to me. I have started doing this as I am migrating each component (starting with [Card](https://github.com/flutter/flutter/pull/100532) and the still being worked on buttons. But the earlier FAB, NavRail etc, don't yet have M3 examples.

**Comment by TahaTesser** [comment]
@guidezpl 

Working on PRs for FAB and NavRail

**Comment by guidezpl** [comment]
Thanks! Are you able to leverage the existing samples without copying them? @gspencergoog, curious if you have any thoughts on this? Added samples here would be identical, except the bool `ThemeData.useMaterial3`.

**Comment by TahaTesser** [comment]
>  Thanks! Are you able to leverage the existing samples without copying them? @gspencergoog, curious if you have any thoughts on this? Added samples here would be identical, except the bool ThemeData.useMaterial3.

Code would be pretty similar but visual it will look quite different and the example description is also pointing to M3 design specs. When `useMaterial3` is deprecated, regular M2 can be deleted without refactoring the code.

I'm happy to update PR/Example if the code cannot be identical and I also added fab variant examples and tests for each existing example

**Comment by guidezpl** [comment]
That's good point, code duplication for the transition period is acceptable

**Comment by TahaTesser** [comment]
Working on samples for https://github.com/flutter/flutter/pull/107166

**Comment by TahaTesser** [comment]
@guidezpl 
I'm closing this as done as almost M3 widgets have examples now.

**Comment by guidezpl** [comment]
Great thank you! Which are missing?

**Comment by TahaTesser** [comment]
@guidezpl 
https://github.com/flutter/flutter/pull/120855 is missing an example (or an example update)
