### ISSUE TITLE
I got an error when build flutter

### ISSUE THREAD

**Issue by Henglongung** [flutter/flutter#101011]
Building with sound null safety 💪

FAILURE: Build failed with an exception.

* Where:
Build file '/home/henglong/VGo/VGoProject/vgo_app/android/app/build.gradle' line: 32

* What went wrong:
A problem occurred evaluating project ':app'.
> Could not get unknown property 'ndkVersion' for extension 'flutter' of type FlutterExtension.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
Running Gradle task 'assembleRelease'...                         2,713ms
Gradle task assembleRelease failed with exit code 1

**Comment by darshankawar** [comment]
> Could not get unknown property 'ndkVersion' for extension 'flutter' of type FlutterExtension.

Is this error occuring while running your app from IDE ? such as Android studio or VSCode ?
If so, can you try to run the app directly from command line or terminal (ie outside from IDE) and see if you still get same error ?

Also, try to check if you have correct or ndk installed already from `android studio -> SDK manager -> SDK tools`

**Comment by Henglongung** [comment]
thanks u @darshankawar I can resolve it now
