### ISSUE TITLE
[autosubmit] get write permission to autosubmit app

### ISSUE THREAD

**Issue by KristinBi** [flutter/flutter#101008]
Currently, when a pull request with 'autosubmit' label doesn't meet the requirements to be merged, we will remove its label and meanwhile create a comment to this pull request. However, I cannot create the comment. I now only have read permission and get a 403 error saying 'GitHub Error: Resource not accessible by integration' whenever I wants to create the comment. 
<img width="1138" alt="Screen Shot 2022-03-29 at 7 05 50 PM" src="https://user-images.githubusercontent.com/98613535/160736419-56b0cf4f-4fac-4dd7-86d8-2727a44aca70.png">

**Comment by KristinBi** [comment]
Hi @godofredoc, can you help approve the write permission to this APP?

**Comment by godofredoc** [comment]
Can you please open a bug in the internal security component?

**Comment by KristinBi** [comment]
> Can you please open a bug in the internal security component?

Sorry I forgot to reply here. I opened a bug in the internal security component, here is the link: https://b.corp.google.com/issues/227665382.
Thank you very much Godofredo!

**Comment by godofredoc** [comment]
Seems like you are trying to update an issue instead of the PR

**Comment by KristinBi** [comment]
> Seems like you are trying to update an issue instead of the PR

Thank you for the suggestion to the issue Godofredo! I submitted a PR to fix this in https://github.com/flutter/cocoon/pull/1700.

**Comment by godofredoc** [comment]
Should we close this bug?

**Comment by KristinBi** [comment]
Fixed the issue, be granted the write permission, successfully created the comment.
