### ISSUE TITLE
[cocoon] Support checksuite rerun event

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#101132]
GitHub rolled out the rerun functionality for an entire checksuite. Cocoon currently only supports individual checkrun reruns, and this can be extended to support the GitHub functionality.

This is being used by the skia autoroll, but isn't making any changes.

**Comment by godofredoc** [comment]
Closing because the bug has not been updated for more than one year.

Feel free to reopen any bugs that you believe are important but please provide updates on how to resource the fix of the bug and what can be done to prevent the issue from not getting updates for another year.
