### ISSUE TITLE
Debug properties of BackdropFilterLayer missed

### ISSUE THREAD

**Issue by wangying3426** [flutter/flutter#101102]
When debugDumpLayerTree, we found that BackdropFilterLayer's properties are missed.
```
flutter:  │     │ ├─child 6: ClipRectLayer#b154d
flutter:  │     │ │ │ engine layer: ClipRectEngineLayer#6c8d6
flutter:  │     │ │ │ handles: 2
flutter:  │     │ │ │ clipRect: Rect.fromLTRB(39.2, 135.0, 67.2, 162.0)
flutter:  │     │ │ │ clipBehavior: Clip.hardEdge
flutter:  │     │ │ │
flutter:  │     │ │ └─child 1: BackdropFilterLayer#2376b
flutter:  │     │ │   │ engine layer: BackdropFilterEngineLayer#75b16
flutter:  │     │ │   │ handles: 2
flutter:  │     │ │   │
flutter:  │     │ │   └─child 1: PictureLayer#788c9
flutter:  │     │ │       handles: 1
flutter:  │     │ │       paint bounds: Rect.fromLTRB(39.2, 135.0, 67.2, 162.0)
flutter:  │     │ │       picture: Picture#81dd7
flutter:  │     │ │       raster cache hints: isComplex = false, willChange = false
```

**Comment by danagbemava-nc** [comment]
`BackdropFilterLayer` doesn't override `debugFillProperties`  and the code is the same in the latest master

<details>
<summary>code from repo</summary>

https://github.com/flutter/flutter/blob/9bd04bd03a87cc943a6d8736a3e3be24d4f41443/packages/flutter/lib/src/rendering/layer.dart#L1905-L1959

</details>

**Comment by wangying3426** [comment]
> `BackdropFilterLayer` doesn't override `debugFillProperties` and the code is the same in the latest master
> 
> code from repo
> https://github.com/flutter/flutter/blob/9bd04bd03a87cc943a6d8736a3e3be24d4f41443/packages/flutter/lib/src/rendering/layer.dart#L1905-L1959

Yes, you're right, this PR https://github.com/flutter/flutter/pull/101101 fixed it.
