### ISSUE TITLE
WebView receive messages on Window object in JavascriptChannel

### ISSUE THREAD

**Issue by aBuder** [flutter/flutter#101133]
At the moment it is not possible to receive messages on Window object in JavascriptChannel.  I have problem so receive messages from window object, but with current version it seems to be impossible.

I added the Java Script version of send and receive events on Window object.

```javaScript
window.postMessage("do-somthing-cool");
```

```javaScript
window.addEventListener("message", (event) => {
  console.log(event.data);
}, false);
```

```dart
JavascriptChannel(
  name: '', 
  onMessageReceived: (JavascriptMessage message) { print(message.message); }
);
```

**Comment by maheshmnj** [comment]
Hi @aBuder, Thanks for filing the issue. Please share a minimal and complete code sample along with the complete output of `flutter doctor -v`.
