### ISSUE TITLE
Some black backgrounds in the website gif

### ISSUE THREAD

**Issue by xster** [flutter/flutter#10119]
May need some more transparency masking

![screen shot 2017-05-16 at 11 25 36 am](https://cloud.githubusercontent.com/assets/156888/26121854/77f52f20-3a2a-11e7-8921-874061059228.png)

**Comment by sethladd** [comment]
Thanks for filing! I'm not exactly sure how to get rid of this for an animated gif. Help wanted :)

**Comment by xster** [comment]
There's a bunch of stuff we can do in post process http://www.imagemagick.org/Usage/anim_basics/ but it's probably easier to try to do it in the tool used to capture the screen since there's some blending already in the gif

**Comment by zoechi** [comment]
Issue moved to [flutter/website #1828](https://github.com/flutter/website/issues/1828) via [**ZenHub**](https://www.zenhub.com/)
