### ISSUE TITLE
after updating flutter sdk to 2.8.1 and android studio to 2021.1.1 patch 1 code auto completion doesn't work well

### ISSUE THREAD

**Issue by pickupsb** [flutter/flutter#101160]
it works fine partially. for example when you type Text it works fine .but when you type GestureDetector it doesn't.
any suggestion?
platform is mac.

**Comment by pickupsb** [comment]
i just found that text doesn't work either. the text is from dart:html. all the material widgets don't work.
i have already updated the sdk and android studio to latest version.

**Comment by pickupsb** [comment]
i found it has something to do with my project. i start a new project it just works well. does anyone  know how to fix it?

**Comment by darshankawar** [comment]
> i found it has something to do with my project. i start a new project it just works well. does anyone know how to fix it?

Seems like a config or project issue and not framework's. Please ask support questions on StackOverflow. If you think there's a genuine bug in framework after upgrading the sdk, please use new issue template and fill out requested details so that we can address it properly.
Closing for now.
