### ISSUE TITLE
flutter dashboard should support tooltips for the "Tree is closed (...)" message

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#101137]
In https://github.com/flutter/cocoon/pull/1052, Greg added the very helpful list of failing tasks to the "Tree is closed" message at the top of the build dashboard. However, in my narrow tab workflow, this is often truncated with ellipses, like:

![image](https://user-images.githubusercontent.com/7856010/161130714-0253db1e-5e97-4e01-9e5d-386b4f517dc0.png)

This message does not have a tooltip, and thus I have to full screen the window to see the message. This should have a tooltip.

**Comment by christopherfujino** [comment]
Re-opening this as my PR was reverted when it caused a bug in updating the text https://github.com/flutter/cocoon/pull/1701

**Comment by ricardoamador** [comment]
This is implemented.
![image](https://github.com/flutter/flutter/assets/32242716/66be9338-eb81-4c09-9e07-67db8a0535ae)
