### ISSUE TITLE
Build macOS desktop `gen_snapshot_arm64` as arm64 binary to run natively on Apple Silicon

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#101138]
On an arm64 Apple Silicon Mac, the published `gen_snapshot_*` binaries are `x86_64` and therefore run with Rosetta translation.
```
./darwin-x64-profile/gen_snapshot_arm64:          Mach-O 64-bit executable x86_64
./darwin-x64-profile/gen_snapshot_x64:            Mach-O 64-bit executable x86_64
./darwin-x64-profile/gen_snapshot:                Mach-O 64-bit executable x86_64
./darwin-x64/gen_snapshot_arm64:                  Mach-O 64-bit executable x86_64
./darwin-x64/gen_snapshot_x64:                    Mach-O 64-bit executable x86_64
./darwin-x64/gen_snapshot:                        Mach-O 64-bit executable x86_64
./darwin-x64-release/gen_snapshot_arm64:          Mach-O 64-bit executable x86_64
./darwin-x64-release/gen_snapshot_x64:            Mach-O 64-bit executable x86_64
./darwin-x64-release/gen_snapshot:                Mach-O 64-bit executable x86_64
```
Dart does not currently support targeting x64 from a non-x64 host https://github.com/dart-lang/sdk/issues/49768.  However `gen_snapshot_arm64` could be compiled as arm64 and therefore run natively on an arm64 Mac.

Compile macOS `gen_snapshot_arm64` as arm64, and publish in the arm64 Flutter install (`flutter_macos_arm64_*.zip`), as well as the macOS desktop artifacts that get `curl`ed when upgrading on an arm64 Mac.  Leave as `x86_64` in the x64 installers.

**Comment by jmagman** [comment]
@cbracken I know you're working on gen_snapshot refactoring, will that result in gen_snapshot always running natively on arm, even for creating x64 binaries per https://github.com/dart-lang/sdk/commit/4f7bb16cc5cafbb4744e9b4e9cebf527bf30edcd?  Would like to stop requiring Rosetta for our developers, plus I'm getting pushback to installing Rosetta on our luci bots https://bugs.chromium.org/p/chromium/issues/detail?id=1354817#c11

**Comment by cbracken** [comment]
Yes this is part of https://github.com/flutter/flutter/issues/103386

**Comment by TheSin-** [comment]
> Yes this is part of #103386.

is there a channel to help test this?  I can not install Rosetta for work reasons and it's really slowed my flutter dev over the last year+, I'd love to at least test `gen_snapshot_arm64` so I can add an archive. Even if I need to download the binary by hand and add a link in the right path for it

**Comment by TheSin-** [comment]
well [that last commit](https://github.com/NixOS/nixpkgs/commit/03ae92a17d0f9683a1da5eaee77b0497a0d7ba66) isn't promising at all :(

**Comment by karatekid430** [comment]
Can somebody please explain what needs to be done to make an arm64 gen_snapshot binary? Then I will do the work and make the PR.

**Comment by TheSin-** [comment]
if you get this info please share.  incase it the PR takes time I'd like to self build until then.  I haven't had time to track it down myself to build it.

**Comment by karatekid430** [comment]
Okay I just made an arm64 gen_snapshot that runs on arm64 MacOS without Rosetta. I will try dropping it into the dart sdk folder and see if it enables release builds for Flutter.

**Comment by eEQK** [comment]
@karatekid430 I think there is a mismatch between the binary you've built and the Dart SDK you're trying to run it with. See if you can find the SDK version in the engine files or at least try using Flutter master channel

**Comment by karatekid430** [comment]
@eEQK I think you are right. But it still might be the wrong binary period. I found this is gen_snapshot and the one I need is gen_snapshot_arm64 - can someone please help me understand how the build system creates the gen_snapshot_arm64 (which ironically is currently an x86 binary)?

**Comment by jmagman** [comment]
The fix was reverted, reopening https://github.com/flutter/engine/pull/52913

**Comment by jmagman** [comment]
Fixed by https://github.com/flutter/engine/pull/53524
