### ISSUE TITLE
[Fonts] Icon request: expand_circle_down

### ISSUE THREAD

**Issue by Rajbamalwa** [flutter/flutter#101170]
can you please add this icon in fluttter

**Comment by darshankawar** [comment]
@Rajbamalwa 
This icon seems already be present in Flutter. Checked on latest master channel:

<img width="332" alt="Screenshot 2022-04-01 at 1 47 35 PM" src="https://user-images.githubusercontent.com/67046386/161224101-6e92b703-9002-478a-a232-0e924e7e626f.png">

`Channel master, 2.13.0-0.0.pre.352`

Please check and confirm. I am closing this as requested icon is already present.
