### ISSUE TITLE
using FocusNode.requestFocus() on a TextField does not prevent the keyboard from disappearing unless a delay is used

### ISSUE THREAD

**Issue by nathantew14** [flutter/flutter#101163]
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. Tap on the TextField
3. Tap on "done" on your keyboard (or its equivalent)
4. The keyboard disappears, but the blue line below the TextField remains.
5. Now uncomment the line `await Future.delayed(const Duration(milliseconds: 1));` between `myFocusNode.unfocus();` and `requestFocus();`
6. Tap on the TextField
7. Tap on 'done' again

This issue is also referenced at #33305 but the issue has been closed with no apparent resolution.

**Expected results:** 
I expected the keyboard to just remain in place, without moving, and without having to use a `await Future.delayed()`

**Actual results:** 
Using the `await Future.delayed()`, the keyboard remains, but there is some glitchy visual animations of the keyboard disappearing for a moment and the textfield moving up and down.

**Edit:**
I've noted that the amount of time used for the delay seems to vary as I develop my app, and so far I've seen cases where 10 milliseconds is insufficient and the keyboard still disappears, but it's "fixed" by increasing the duration of the delay. Maybe the `FocusNode.unfocus()` function should be asynchronous so we can `await` for it or something?

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main(List<String> args) {
  runApp(const MaterialApp(
    home: MyApp(),
  ));
}

class MyApp extends StatefulWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  late FocusNode myFocusNode;

  @override
  void initState() {
    myFocusNode = FocusNode();
    super.initState();
  }

  @override
  void dispose() {
    myFocusNode.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Padding(
        padding: const EdgeInsets.all(8.0),
        child: Center(
          child: TextField(
            focusNode: myFocusNode,
            onSubmitted: (string) async {
              myFocusNode.unfocus();
              await Future.delayed(const Duration(milliseconds: 1));
              myFocusNode.requestFocus();
            },
          ),
        ),
      ),
    );
  }
}
```

</details>

<details>
  <summary>Logs</summary>

`flutter run --verbose` logs is too long to fit here or in a pastebin

```

```

```
nathan@Nathans-MBP-8 textfield_focus_test % flutter analyze
Analyzing textfield_focus_test...                                       
No issues found! (ran in 4.2s)
```

```
nathan@Nathans-MBP-8 textfield_focus_test % flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.4, on macOS 12.3 21E230 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.65.2)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
@nathantew14 
I think you are hitting same as https://github.com/flutter/flutter/issues/99573, so please follow-up in it for further updates.
Closing this as a duplicate. If you disagree, write in comments and I'll reopen it.

**Comment by nathantew14** [comment]
@darshankawar I'm really new to flutter so I'll take your word that it's a duplicate
