### ISSUE TITLE
Remove "Classes" directories from flutter/plugins/**/ios

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#10116]
They don't serve a purpose, and they just make for more verbose imports (and confusing semantics, since "Classes" as a directory is sometimes used to mean "internal".

**Comment by mravn-google** [comment]
Should we update the plugin template too?
cc @jakobr-google

**Comment by tvolkert** [comment]
Yep - I'll send a PR in the flutter repo

**Comment by jakobr-google** [comment]
I think we'll want to keep '*' in source_files - headers are source code
too, pod-wise, and it'll enable Swift-based plugins as well - but that'd
require putting them in a separate directory... Or you could add .h and
.swift as well.

What's the problem with Classes? The current layout is the default
CocoaPods library layout.



tor. 18. maj 2017 kl. 22.59 skrev Todd Volkert <notifications@github.com>:

**Comment by tvolkert** [comment]
I got pushback from internal Google clients about the verbosity of the paths:

```
#import "third_party/flutter_plugins/shared_preferences/Classes/SharedPreferencesPlugin.h"
```

From discussing with @cbracken and @collinjackson it didn't sound like the "Classes" added any value.  Do they?

**Comment by mravn-google** [comment]
Can't we use imports of the form `#import <plugin/plugin.h>` instead?

**Comment by tvolkert** [comment]
Only if we bundle them as frameworks and load them dynamically - right now we're statically compiling them into the app framework.

**Comment by tvolkert** [comment]
... maybe we should just keep them in `Classes` and work instead on building them as frameworks?  How are they built with the app in the external flow?

**Comment by mravn-google** [comment]
The plugin's header file is imported unqualified in `GeneratedPluginRegistrant.h`: `import "plugin.h"`
Don't know if that answers your question.

**Comment by tvolkert** [comment]
Internally, everything is statically compiled into the app, and modifying the include path is forbidden.  @jakobr-google I'll wait for your LGTM to land this in case you still have objections.

**Comment by tvolkert** [comment]
.. to land https://github.com/flutter/plugins/pull/68, that is

**Comment by jakobr-google** [comment]
The value of 'Classes' is having the source code in a separate directory, so we can refer to it easily in the podspec. I think we should keep it that way, but we can rename the directory if you want.

**Comment by mravn-google** [comment]
Maybe tweak the way we copy this stuff into the internal structure. If the external structure is intended to build dynamic frameworks and the internal structure is intended for static compilation, we may be wrong to impose the same structure on both.

**Comment by jakobr-google** [comment]
External flow builds them as frameworks by default (`use_frameworks!` in the app's `Podfile`). We have some issues with another Google pod that's distributed only as a static library, but apart from that, frameworks should be the default. Ideally, we'd build our apps the same way internally.

And given the already long import string, I don't think dropping 'Classes' from the path really improves things. If we do want to do this, we should just move them in the internal repo, and leave things as they are externally. We have tools that can do this automatically.

**Comment by tvolkert** [comment]
Sounds good - closing this.  Thanks!
