### ISSUE TITLE
fix net::err_unknown_url_scheme whatsapp link on flutter webview

### ISSUE THREAD

**Issue by Bigmee** [flutter/flutter#101145]
I am using the flutter webview plugin.
the problem is that there is a WhatsApp pop-up from the webpage and if i click on the WhatsApp icon from the webpage it displays this error message.
NB: I did not add add this WhatsApp button on my app, but it automatically pops on the webpage 

Below is the code I wrote, please tell me the options i have to solve this 
```
import 'package:flutter/material.dart';
import 'package:flutter_webview_plugin/flutter_webview_plugin.dart';

class Digitalcoin extends StatefulWidget {
  const Digitalcoin({Key? key}) : super(key: key);

  @override
  State<Digitalcoin> createState() => _DigitalcoinState();
}

class _DigitalcoinState extends State<Digitalcoin> {
  @override
  Widget build(BuildContext context) {
    return WebviewScaffold(
        url: "https://www.meechtv.com/#",

      appBar: AppBar(
          title: Text ("Meechtv"),
        backgroundColor: Colors.red,

        centerTitle: true,
        elevation: 0,
    ),
      withJavascript: true,
      withZoom: true,
      withLocalUrl: true,
      withLocalStorage: true,
      withOverviewMode: true,

      initialChild: Center(child: Text("Loading...")),
        bottomNavigationBar: Padding(
    padding: EdgeInsets.all(12),
    child: Text('MeechTv'),
    ),
    );

  }
}

```

**Comment by darshankawar** [comment]
@Bigmee 
First of all, you seem to be using community plugin `flutter_webview_plugin` which is not controlled / maintained by Flutter. 
Flutter's first party plugin is `webview_flutter`.


Coming to your issue, `net::err_unknown_url_scheme`, this indicates that the url scheme you are trying to pass / open doesn't seem to be valid and hence the error. You need to check whether the url you are passing is correct / valid.
Also this type of questions are better to be asked on support channels like StackOverflow.

Closing from here.
