### ISSUE TITLE
Cannot run the example app of a plugin from IDE

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#10115]
## Steps to Reproduce

1. Create a new plugin `flutter create --plugin hello`
1. Open in IDEA: `cd hello; idea .`

=> Would like to be able to launch the example app, but we seem to be missing a launch config, so Run/Debug is disabled.

**Comment by mit-mit** [comment]
@devoncarew any ideas on this? I guess the core issue is that the root folder doesn't have anything to run; the example subfolder does?

**Comment by devoncarew** [comment]
The main IntelliJ project would need to know about the example sub module (and perhaps the example launch config duplicated into the main .idea directory).

Re: generating an `example/` sub dir in the project, that has some drawbacks esp. in terms of all the artifacts and machinery for android and ios. Generating into a parallel project would improve some things while introducing other issues. I have not been able to think of a better way to allow for quick running on the user's plugin code.

**Comment by sethladd** [comment]
I'd like to see this fixed at the package-format-organization level. I think our "ecosystem team" should include a scope of "making packages + examples work better, especially for mobile and Flutter". We can change some assumptions of our packages and single-.packages , and if so, perhaps make higher-level layers of our stack more robust.

**Comment by mit-mit** [comment]
> I'd like to see this fixed at the package-format-organization level.

Sure, we have indeed learned that the `/example/` subdir approach does seem to have some drawbacks. Whether it can be fixed at by re-organizing without a similar (or larger) set of drawbacks is not given yet though.

**Comment by mit-mit** [comment]
@devoncarew if I manually add a Flutter launch config to a plugin project `hello` with these settings:

* Name: `/example/lib/main.dart`
* Dart : `/hello/example/lib/main.dart`

, then the Run/Debug actions seem to work. Specifically for this issue, couldn't we just add that to the plugin template?

**Comment by devoncarew** [comment]
@mit-mit, yup, we could - sounds like a good idea.
