### ISSUE TITLE
Regression in raster time in opacity_peephole_grid_of_opacity_perf__e2e_summary

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#101122]
On the Engine roll here https://github.com/flutter/flutter/commit/9be162402f3686c079d4436b4742f5e1b560881d

SkiaPerf is reporting a regression in 90% raster time

https://flutter-flutter-perf.skia.org/e/?begin=1648245261&end=1648737011&keys=X18d651edad4005b6fb479a01d3433a64&requestType=0&xbaroffset=28147

I'm guessing something about https://github.com/flutter/engine/pull/32268 is confusing the opacity peephole optimization.

@flar @chinmaygarde

**Comment by zanderso** [comment]
After talking with @flar, it turns out that there are no images in the benchmark. Also, the size of the regression is pretty small especially relative to the performance improvement from the optimization he landed, so I don't think the DL image change is defeating it. Therefore, I am dropping the priority of this to P4, and unassigning folks.

**Comment by flar** [comment]
It's worth noting that the animation does not contain any images. The only image that I think might be present would be the back-button on the header to go back a page.

With the ContextDiff stuff limiting our rendering to just the animated parts the back button shouldn't re-rasterize on every frame, but maybe something is happening during preroll?

**Comment by flar** [comment]
I'm not sure if Skia reported it, but if you add "average frame raster" time to the plot you see a similar bump in timings, so this isn't just a 90% case, it is happening on every frame.

**Comment by jonahwilliams** [comment]
I dont think this is actionable anymore
