### ISSUE TITLE
iOS Image Picker Photo Access Issues

### ISSUE THREAD

**Issue by herrchmafi** [flutter/flutter#101128]
I'm running into some issues with `ImagePicker`'s `pickImage` function when providing an `ImageSource.gallery` option that always occurs on the first launch of the application after a hard close. 

My flow works as follows:
- I display a Cupertino Modal Popup with an option to select an asset from your gallery
- If that option is selected, I then dismiss the modal and make a call to `pickImage`
- This immediately displays the camera roll picker with all the user's assets
- Once an image is selected, I then see a "<Your App> Would Like to Access Your Photos" alert with "Select More Photos", "Keep Current Selection" options
- On subsequent calls to `pickImage`, I no longer receive this alert

There's a few things that I don't expect to happen:
- Photo access permissions were already provided so wouldn't expect to see this in the first place
- I have access to all camera roll photos each time this opens rather than the selected ones
- I would expect to see this alert prior to when the camera roll picker opens

Ultimately, I am able to access the image the user selects as needed, but doesn't seem like things are working as intended

Here are some code snippets:
<img width="603" alt="Screen Shot 2022-03-31 at 9 49 31 AM" src="https://user-images.githubusercontent.com/10555443/161108243-e67d9d24-4b1d-4d11-8ac2-38362c6386f9.png">
<img width="611" alt="Screen Shot 2022-03-31 at 9 50 38 AM" src="https://user-images.githubusercontent.com/10555443/161108533-87aeaba6-34de-40d5-b644-000d7b1760f8.png">

**Comment by darshankawar** [comment]
@herrchmafi 
Please provide `flutter doctor -v`, plugin version you are using along with a complete runnable and minimal code sample that shows the behavior you are reporting.

Thanks.

**Comment by herrchmafi** [comment]
Demo widget:
<img width="631" alt="Screen Shot 2022-04-04 at 1 23 20 PM" src="https://user-images.githubusercontent.com/10555443/161626003-b739e1b6-7b18-47c7-a256-989ac21dda4a.png">

Doctor output:
<img width="1052" alt="Screen Shot 2022-04-01 at 12 29 35 PM" src="https://user-images.githubusercontent.com/10555443/161626155-c1dc8a03-0856-45d8-8543-2a92879c2c40.png">

Here's a video of the demo:
https://drive.google.com/file/d/1dHIZpWT5MnUGiGFPofK8aaskmxxlGLYh/view?usp=sharing

**Comment by darshankawar** [comment]
@herrchmafi 
Thanks for the update. It would be best if you could provide the code sample in text format instead of in screenshots, since we can't directly use it when you post as a screenshot.

**Comment by herrchmafi** [comment]
Sure!

```
import 'package:flutter/material.dart';
import 'package:flutter_hooks/flutter_hooks.dart';
import 'package:image_picker/image_picker.dart';

// Demo Page

class ImagePreviewPage extends HookWidget {
  final String src;

  const ImagePreviewPage({Key? key, required this.src}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    final picker = useMemoized(() => ImagePicker(), []);
    final pickAsset = useCallback(() async {
      return await picker.pickImage(source: ImageSource.gallery);
    }, [picker]);

    return Scaffold(
      appBar: AppBar(),
      body: SafeArea(
        child: Column(
          children: [
            TextButton(
              onPressed: pickAsset, 
              child: const Text("Pick Photo!")
            ),
          ],
        ),
      ),
    );
  }
}
```

**Comment by darshankawar** [comment]
Thanks for the update. The code seems to be using `flutter_hooks` which is third party plugin. Does the behavior you are reporting occur without using `flutter_hooks` and just using `image_picker` ? If so, please provide updated code sample without any third party plugin code.

**Comment by herrchmafi** [comment]
Here's an updated sample without hooks:
```
import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';

// Demo Page

class ImagePreviewPage extends StatelessWidget {
  final String src;

  const ImagePreviewPage({Key? key, required this.src}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: SafeArea(
        child: Column(
          children: [
            TextButton(
              onPressed: () async {
                final picker = ImagePicker();
                await picker.pickImage(source: ImageSource.gallery);
              }, 
              child: const Text("Pick Photo!")
            ),
          ],
        ),
      ),
    );
  }
}
```

Still seeing the same behavior for this

**Comment by darshankawar** [comment]
@herrchmafi 
Using your code sample, I don't see any issue related to permissisons. See video below:


https://user-images.githubusercontent.com/67046386/162125382-2e37dc52-f09b-4330-9310-97a556ad1d54.mov

I used `image_picker: ^0.8.4+11` and `Channel master, 2.13.0-0.0.pre.423`

**Comment by herrchmafi** [comment]
@darshankawar 
When you press the "Select Photos" button and choose only the first photo, I would only expect to see the first photo show up as an option going forward when you bring up the camera roll. In the video, all the photos show up

The other behavior I'm seeing is that the permissions dialog shows up each time after hardclosing the app, which I would have expected only after providing permissions the first time around

**Comment by darshankawar** [comment]
@herrchmafi 
I believe you are hitting https://github.com/flutter/flutter/issues/65995, so please follow-up in it for further updates.
Closing this as a duplicate.
