### ISSUE TITLE
Expanded widget not working properly on Android API 30

### ISSUE THREAD

**Issue by rafaelhks** [flutter/flutter#101118]
When using the Expanded widget inside a column with another widget it is taking up all the space, not just filling the available space as usual.

Simple build function for reproducing the problem:
```
Widget build(BuildContext context) {
    return Scaffold(
      key: _scaffoldKey,
      appBar: AppBar(
        title: const Text('Despesa'),
        centerTitle: true,
      ),
      body: Column(
          children: <Widget>[
            Expanded(
              child: Container(
                color: Colors.yellow,
              )
            ), 
            ElevatedButton(child: Text('test button'), onPressed: () {}),
          ],
        ),
      );
  }
```
When testing the code above on API 29 or below it renders the following:
![screenshot_1648731597](https://user-images.githubusercontent.com/32396805/161083292-67d60826-eb64-4383-8004-651e5325a78e.png)

When testing the same code on API 30 it shows only the Expanded:
![Webp net-resizeimage](https://user-images.githubusercontent.com/32396805/161083491-1fdb7223-78c9-4d1e-a8be-b1323967acbd.png)

As stated by the [Flutter documentation](https://api.flutter.dev/flutter/widgets/Expanded-class.html), the _Expanded_ makes a child of a Row, Column, or Flex expand to **fill the available space** along the main axis, but on API 30 it seems to not be working properly.

**Comment by darshankawar** [comment]
@rafaelhks 
Can you provide `flutter doctor -v` ? Can you also try by using `SafeArea` and see if you get same behavior ?
