### ISSUE TITLE
Samsung S10 results are clobbering(?) Moto G4 results in SkiaPerf

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#101220]
The worst_frame_rasterizer_time_millis result for Moto G4 for commit https://github.com/flutter/flutter/commit/28505569463d5510f0feadd53e3ed10726e9b227 in SkiaPerf is recorded as 18.094:

https://flutter-flutter-perf.skia.org/e/?begin=1648581332&end=1648855266&keys=X02af86de85ec7fab80fc22a11016955d&requestType=0

However examining the logs in LUCI, this is neither the result reported for the S10 nor the Moto G4:

S10: https://storage.googleapis.com/flutter_logs/flutter/28505569463d5510f0feadd53e3ed10726e9b227/backdrop_filter_perf__timeline_summary/5d57a33d-a31f-4235-b1f5-de6bc493be8c/backdrop_filter_perf.timeline_summary.json

Moto G4: https://storage.googleapis.com/flutter_logs/flutter/28505569463d5510f0feadd53e3ed10726e9b227/backdrop_filter_perf__timeline_summary/4b729b7c-8ba4-4f57-a616-f95e391439f2/backdrop_filter_perf.timeline_summary.json

But the value recorded in SkiaPerf is close to the S10 result, which makes me think that something is being clobbered, or some wires are crossed somewhere.

Looking back at the results of the benchmark, it looks like this started happening around the time of the commit here: https://github.com/flutter/flutter/commit/ff425fc733018d183a452330de8ffb85e0689862:

https://flutter-flutter-perf.skia.org/e/?begin=1644280799&end=1648855266&queries=device_type%3DMoto_G__4_%26sub_result%3D90th_percentile_frame_rasterizer_time_millis%26sub_result%3D99th_percentile_frame_rasterizer_time_millis%26sub_result%3Daverage_frame_rasterizer_time_millis%26sub_result%3Dworst_frame_rasterizer_time_millis%26test%3Dbackdrop_filter_perf__e2e_summary%26test%3Dbackdrop_filter_perf__timeline_summary&requestType=0

Prioritizing as P2 since we are basically flying blind on lower end devices if this mixup is happening everywhere that we're running benchmarks on S10 devices.

@keyonghan

**Comment by keyonghan** [comment]
Latest commits show different platform data points separately: https://flutter-flutter-perf.skia.org/e/?queries=device_type%3DMoto_G__4_%26device_type%3DSM-A025V%26device_type%3DSM-G973U1%26sub_result%3Dworst_frame_rasterizer_time_millis%26test%3Dbackdrop_filter_perf__timeline_summary&requestType=0

Please reopen if still any issues.

**Comment by zanderso** [comment]
Thanks @keyonghan !
