### ISSUE TITLE
Apple silicon machine on latest master shows x64 cached Dart version

### ISSUE THREAD

**Issue by timsneath** [flutter/flutter#101243]
## Steps to Reproduce

See log: https://gist.github.com/timsneath/0340a7ef006dfda3a981fe4073a13670

I was expecting to see ARM here -- am I misled, @jmagman?

**Comment by jmagman** [comment]
Does it work on the beta channel? I didn't work on this part, cc/ @zanderso  @cbracken

@christopherfujino I thought we disabled `upgrade` on master?

**Comment by christopherfujino** [comment]
> Does it work on the beta channel? I didn't work on this part, cc/ @zanderso @cbracken
> 
> @christopherfujino I thought we disabled `upgrade` on master?

We didn't. The dart SDK is being downloaded from https://github.com/flutter/flutter/blob/master/bin/internal/update_dart_sdk.sh#L63. @timsneath can you share the output of `uname -m`? And also `flutter doctor -v` output?

**Comment by timsneath** [comment]
Sure!

```
$ uname -m
arm64
$ uname -a 
Darwin tims-air.lan 21.3.0 Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_ARM64_T8101 arm64
```
and

```
$ flutter doctor -v     
[✓] Flutter (Channel master, 2.13.0-0.0.pre.366, on macOS 12.2.1 21D62 darwin-arm, locale en-US)
    • Flutter version 2.13.0-0.0.pre.366 at /Users/timsneath/flutter
    • Upstream repository git@github.com:flutter/flutter.git
    • Framework revision 0b97874895 (19 hours ago), 2022-04-01 21:20:01 -0400
    • Engine revision 801d8c530f
    • Dart version 2.17.0 (build 2.17.0-265.0.dev)
    • DevTools version 2.12.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/timsneath/Library/Android/sdk
    • Platform android-31, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] VS Code (version 1.66.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.36.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.2.1 21D62 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 100.0.4896.60

[✓] HTTP Host Availability
    • All required HTTP hosts are available
```

**Comment by christopherfujino** [comment]
> Sure!
> 
> ```
> $ uname -m
> arm64
> $ uname -a 
> Darwin tims-air.lan 21.3.0 Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_ARM64_T8101 arm64
> ```
> 
> and
> 
> ```
> $ flutter doctor -v     
> [✓] Flutter (Channel master, 2.13.0-0.0.pre.366, on macOS 12.2.1 21D62 darwin-arm, locale en-US)
>     • Flutter version 2.13.0-0.0.pre.366 at /Users/timsneath/flutter
>     • Upstream repository git@github.com:flutter/flutter.git
>     • Framework revision 0b97874895 (19 hours ago), 2022-04-01 21:20:01 -0400
>     • Engine revision 801d8c530f
>     • Dart version 2.17.0 (build 2.17.0-265.0.dev)
>     • DevTools version 2.12.1
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
>     • Android SDK at /Users/timsneath/Library/Android/sdk
>     • Platform android-31, build-tools 30.0.3
>     • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
>     • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
>     • All Android licenses accepted.
> 
> [✓] Xcode - develop for iOS and macOS (Xcode 13.3)
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • CocoaPods version 1.11.3
> 
> [✓] Chrome - develop for the web
>     • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
> 
> [✓] Android Studio (version 2021.1)
>     • Android Studio at /Applications/Android Studio.app/Contents
>     • Flutter plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/9212-flutter
>     • Dart plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/6351-dart
>     • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
> 
> [✓] VS Code (version 1.66.0)
>     • VS Code at /Applications/Visual Studio Code.app/Contents
>     • Flutter extension version 3.36.0
> 
> [✓] Connected device (2 available)
>     • macOS (desktop) • macos  • darwin-arm64   • macOS 12.2.1 21D62 darwin-arm
>     • Chrome (web)    • chrome • web-javascript • Google Chrome 100.0.4896.60
> 
> [✓] HTTP Host Availability
>     • All required HTTP hosts are available
> ```

I'll investigate deeper on Monday, but at a glance this looks like it should work...

**Comment by timsneath** [comment]
OK, I'm going to flag this as P1 right now, since it might be ship-blocking.

**Comment by christopherfujino** [comment]
Still stumped on this. Some notes:

When downloading https://storage.cloud.google.com/flutter_infra_release/flutter/801d8c530fc5b0c102d13d5913dbd98376b99c93/dart-sdk-darwin-arm64.zip and checking the arch, I get:

```
$ file dart-sdk/bin/dart
dart-sdk/bin/dart: Mach-O 64-bit executable arm64
```

So I'm pretty sure on engine CI, we didn't grab/upload the wrong binary.

**Comment by jmagman** [comment]
Off the top of my head this script may be running in Rosetta which means `uname -m` will return x86_64 even on an ARM mac https://github.com/flutter/flutter/blob/8f2aaa99abe0726568eac0bcd857808d5728de2c/bin/internal/update_dart_sdk.sh#L61-L63
See https://github.com/flutter/flutter/pull/67970 for details.
I will try to repro now by checking out the last stable and seeing what that resolves to.

**Comment by jmagman** [comment]
I wasn't able to reproduce this, the stable channel and master channel script both resolved ran that script natively, and dart `arm64` was downloaded.

@timsneath any chance you checked this at some point?
![Screen Shot 2022-04-04 at 11 19 35 AM](https://user-images.githubusercontent.com/682784/161607192-b739c60d-49fc-444c-9d6b-19617ada2539.png)

Did you run `flutter upgrade` https://gist.github.com/timsneath/0340a7ef006dfda3a981fe4073a13670 and that `$ uname -m` result in the same session?

**Comment by christopherfujino** [comment]
> Off the top of my head this script may be running in Rosetta which means `uname -m` will return x86_64 even on an ARM mac
> 
> https://github.com/flutter/flutter/blob/8f2aaa99abe0726568eac0bcd857808d5728de2c/bin/internal/update_dart_sdk.sh#L61-L63
> 
> 
> See #67970 for details.
> I will try to repro now by checking out the last stable and seeing what that resolves to.

I'm working on a tool fix that should be more reliable than relying on `uname` (the same fix from https://github.com/flutter/flutter/pull/67970/files)
