### ISSUE TITLE
Engine cocoon dashboard not updating with build results

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#101205]
Milo shows this:

<img width="1667" alt="Screen Shot 2022-04-01 at 12 41 52 PM" src="https://user-images.githubusercontent.com/6343103/161331113-461bd7e8-8b6e-4d5e-8b91-d1657f043c10.png">

Cocoon shows this:

<img width="1155" alt="Screen Shot 2022-04-01 at 12 42 14 PM" src="https://user-images.githubusercontent.com/6343103/161331078-fcea25bc-6e49-4074-bc38-6683d08d937c.png">

cc @CaseyHillers

**Comment by CaseyHillers** [comment]
I have a temporary fix in https://github.com/flutter/cocoon/pull/1698. I'll look into why the task keys aren't being included in the user data

**Comment by CaseyHillers** [comment]
I found the issue in https://github.com/flutter/cocoon/pull/1685. It's because the PR didn't include a write to datastore before passing the tasks to LUCI, so no keys were generated.

**Comment by CaseyHillers** [comment]
I deployed my PR to process the backlog, and it's in review

**Comment by zanderso** [comment]
The cocoon dashboard appears to be recovering. Thanks @CaseyHillers !

**Comment by CaseyHillers** [comment]
Incident has been resolved, see https://pantheon.corp.google.com/monitoring/alerting/incidents/0.mg89mnnl5se8?project=flutter-dashboard.

A nice TODO in the future would be to have these mirror to GitHub so they're publicly visible
