### ISSUE TITLE
[Flutter 2.10.3] ListTile ignores tileColor/selectedTileColor if parent Container has color

### ISSUE THREAD

**Issue by Drumering** [flutter/flutter#101212]
## Steps to Reproduce

1. Create ListTile with some tileColor.
2. Put ListTile in Container.
3. Set the Container color to something different than ListTile.selectedTileColor

![image](https://user-images.githubusercontent.com/34747194/161348089-29cc50a4-aa02-445d-9edc-a3653c70f215.png)

The same error cited in https://github.com/flutter/flutter/issues/83108

If I change de parent to Material instead Container, works fine. Is this the correct workaround?

**Comment by iapicca** [comment]
@Drumering 

it seems to me that the behavior is intended
https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/list_tile.dart#L91

**Comment by Drumering** [comment]
Sounds great! Bro, thank you so much for the clarification!
