### ISSUE TITLE
Get Started button on homepage doesn't need underline

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#10127]
![screen shot 2017-05-16 at 3 58 39 pm](https://cloud.githubusercontent.com/assets/5479/26131735/9ced16a0-3a50-11e7-8af0-b9ec00372033.png)

**Comment by LarkAscending** [comment]
See https://github.com/flutter/website/pull/582 for a proposed simple fix.

**Comment by sethladd** [comment]
Fixed! :)
