### ISSUE TITLE
[google_sign_in] plugin is crashed on iOS platform

### ISSUE THREAD

**Issue by flutterdev9715** [flutter/flutter#101287]
flutter SDK: 2.10.3
google_sign_in: 5.2.4

When sign in with google, it is working well on Android, but for iOS not working. On iOS, sign in with google has been crashed as soon as click on the login with google button. Anyone already have experience with similar issue? I am looking forward to your help.

Thanks

**Comment by theshivamlko** [comment]
Check if u have configured iOS for Firebase if using.
Share your full error log

**Comment by flutterdev9715** [comment]
Configuration  was done successfully and google sign for iOS was working before.

**Comment by maheshmnj** [comment]
Hi @flutterdev9715, Thanks for filing the issue. Please share the complete output of `flutter run -v` when the crash occurs along with the output of `flutter doctor -v`.
