### ISSUE TITLE
A question

### ISSUE THREAD

**Issue by chenchat** [flutter/flutter#101237]
Here's a question that really bothers me:
First of all, https://dart.dev/guides/language/effective-dart/style#avoid-lines-longer-than-80-characters, you can see not in the length of each line of more than 80,
But I found that many of the Source codes for Flutter are over 80.
On what basis is this considered?

**Comment by amanv8060** [comment]
As per [style guide.](https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#prefer-a-maximum-line-length-of-80-characters) 

Aim for a maximum line length of roughly 80 characters, but prefer going over if breaking the line would make it less readable, or if it would make the line less consistent with other nearby lines. Prefer avoiding line breaks after assignment operators.

**Comment by iapicca** [comment]
I agree with @amanv8060 
also personally feel that this "restriction" encourage the user 
to avoid the nesting hell and forces to implement a more modular code

**Comment by stuartmorgan** [comment]
In the future please use other community resources for questions; the issue tracker is specifically for bug reports and feature requests.
