### ISSUE TITLE
TabBar issue, distance between the label and indicator controlled by a hard-coded value within tabs.dart of the source

### ISSUE THREAD

**Issue by therenca** [flutter/flutter#101228]
`const double _kTabHeight = 46.0;`
`const double _kTextAndIconTabHeight = 72.0;`

these two values within the tabs.dart source file determine the distance between the label and the indicator below it, to an extent that you cannot really control that distance without editing the `_kTabHeight` and `_kTextAndIconTabHeight` variables within the flutter's source code

![image](https://user-images.githubusercontent.com/45092633/161370862-d7b48860-2936-4073-8191-09fd0765f8e3.png)

**Comment by darshankawar** [comment]
@therenca 
Can you try by wrapping `TabBar` with `PreferredSize` widget and assign `preferredSize` property to it and see if that helps ?
