### ISSUE TITLE
Framework tree is closed on mirroring failure, jobs not starting

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#101250]
For the jobs that have been triggered, checking out from the mirror is failing:

https://ci.chromium.org/p/flutter/builders/prod/Linux%20web_benchmarks_canvaskit

However, the main issue seems to be that most of the jobs are just not starting.

**Comment by zanderso** [comment]
cc @CaseyHillers

**Comment by CaseyHillers** [comment]
I lack admin privileges to send the copybara updates necessary. I have a fix in cl/438940015, which fixes the release branches on the mirrors (skip gerrit by pushing directly, and pushes all branches to the mirror).

If we decide, we can also revert cl/438937381

**Comment by CaseyHillers** [comment]
We landed cl/438940015 and deployed it. We're seeing the mirrors get fixed and everything is picking builds up again

**Comment by jmagman** [comment]
This is still happening often for `Linux web_benchmarks_canvaskit`
https://ci.chromium.org/p/flutter/builders/prod/Linux%20web_benchmarks_canvaskit/4963
Also see https://ci.chromium.org/p/flutter/builders/prod/Linux%20ci_yaml%20flutter%20roller/2148

@CaseyHillers is there more to do here?
