### ISSUE TITLE
iOS debug mode app crashes when relaunched from the home screen

### ISSUE THREAD

**Issue by jason-simmons** [flutter/flutter#101209]
1) Start an app on iOS using `flutter run --debug`
2) Stop the app using the iOS task switcher
3) Tap on the app's icon in the home screen.

The app will launch and then immediately crash.

This is a regression that started with https://github.com/flutter/engine/commit/f5d47c6702dcf8c0628517b4a28a822ed239ba8e

Before this the app would show a placeholder view with a message saying that debug mode apps can only be launched from the developer tools.

**Comment by bakhtiyarahmadk** [comment]
👍

**Comment by cyanglaz** [comment]
cc @skwingsmt @ColdPaleLight @xiaoxiaowesley

**Comment by chinmaygarde** [comment]
cc @zanderso for guidance on how to CP this. @jason-simmons thinks this is a good candidate for CP.

**Comment by jmagman** [comment]
I think we're using the new cherrypick template, right @itsjustkevin? https://github.com/flutter/flutter/issues/new?assignees=&labels=cp%3A+review&template=7_cherry_pick.yml&title=%5BCP%5D+%3Ctitle%3E
