### ISSUE TITLE
Re-Publish plugins

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#10128]
Unfortunately, I wasn't able to update the following plugins on pub because I am not an uploader of the package (https://www.dartlang.org/tools/pub/cmd/pub-uploader). Please `pub publish` the most recent version whenever you've a chance. Changelog and pubspec version are already updated in the repo. Thanks!

- [ ] url_launcher
- [ ] share
- [ ] shared_preferences
- [ ] path_provider

/cc @mit-mit

**Comment by Hixie** [comment]
We should make sure a bunch of people in the team have that permission.

**Comment by szakarias** [comment]
Published the plugins and added you as uploader.

**Comment by goderbauer** [comment]
@szakarias I added you as co-uploader to the other plugins as well.
