### ISSUE TITLE
Test to ensure accessibility enums remain in sync

### ISSUE THREAD

**Issue by cbracken** [flutter/flutter#101217]
Flutter includes several accessibility-specific enums that must remain in sync. For example, accessibility features are recorded in:
* `FlutterAccessibilityFeature` enum in `shell/platform/embedder/embedder.h`
* `AccessibilityFeatureFlag` enum in `lib/ui/window/platform_configuration.h`
* `AccessibilityFeatures` class in `lib/ui/window.dart`
* `AccessibilityFeatures` class in `lib/web_ui/lib/window.dart`

Similarly, `FlutterSemanticsAction`, `FlutterSemanticsFlag`, and other enums need to be kept in sync.

Currently, a comment at each location reminds developers to keep these enums in sync, but what's needed is a test that automatically enforces this in presubmit.

**Comment by cbracken** [comment]
Work-in-progress patch at: https://github.com/flutter/engine/compare/main...cbracken:enum-check

**Comment by chinmaygarde** [comment]
Just a heads up that `embedder/embedder.h` has API stability guarantees that are perhaps not relevant for the interface in platform_configuration.h

**Comment by cbracken** [comment]
Yes -- this won't eliminate the requirement that we preserve embedder API/ABI stability guarantees, but I suppose this _does_ imply that adding public dart:ui API for these enums requires an embedder API change and therefore requires all the same forethought and care.

I think the more important part here -- and perhaps what you're getting at is that while we _can_ deprecate and remove some dart:ui APIs, we don't have that luxury with the embedder API and therefore, if we ever did so, we'd need to adapt this test to accept that the embedder API retains a superset of the values in the Dart API.

I was going to add consistency checks against the internal enums in lib/ui/semantics_enum.h but perhaps testing against public dart:ui API is sufficient. If we get to the point of removing values from the public dart:ui API, we'd need to update this test to accept the embedder API containing a superset (perhaps via some exceptions list).
