### ISSUE TITLE
`build_tests_3_4` fails with "Failed to find newest available Simulator runtime: Could not find any supported simulator runtimes"

### ISSUE THREAD

**Issue by TahaTesser** [flutter/flutter#101293]
Test result

https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8817820081453931809/+/u/run_test.dart_for_build_tests_shard_and_subshard_3_4/test_stdout

**Comment by godofredoc** [comment]
Duplicate of https://github.com/flutter/flutter/issues/99039. Please rebase your PR to ToT.
