### ISSUE TITLE
The Engine tree is blue?!

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#101241]
<img width="1150" alt="Screen Shot 2022-04-02 at 9 02 37 AM" src="https://user-images.githubusercontent.com/6343103/161391325-3f5ce756-4cde-450b-87b0-a838140a2f80.png">

**Comment by zanderso** [comment]
Mirroring is broken. https://flutter.googlesource.com/mirrors/engine/ is several commits behind. This is also affecting the framework tree https://github.com/flutter/flutter/issues/101250, but I'll keep the issues separate just in case. @CaseyHillers

**Comment by CaseyHillers** [comment]
Rarely do we expect to see blue, but this is intentional. Previously they would show as gray/new which was misleading.
