### ISSUE TITLE
[Proposal] Rethink the AnimationController.upperBound  & Tween.end Apis

### ISSUE THREAD

**Issue by ash0080** [flutter/flutter#101281]
```
var time = Tween<double>(begin: 0, end: 60).animate(_controller)
```

Well, let's look at the code above and answer the question,   
`what do you think is the upper limit of the time value?`

In most other languages, It's easy, maximum value is 60. 
But in flutter, this answer is wrong, the correct answer is  _controller.upperBound  *  Tween.end

I think the .upperBound design is good and is a convenience, and it does make it easier to use the controller, for example, by passing in 34(mins) instead of 34/60.

 But good intentions do bad things.  This design is too anti-human now, because the controller is called controller, because it is a controller, should not be involved in the **DataModel**, controller is only used to control the completion of the animation, 
like a slider, slide to the far right, tween also reached the maximum, this is a mapping relationship. In all the languages I've worked with in the past, Tween is probably designed the same way.

But flutter is acting like a freak right now.

I don't know if this is intentional design, 
or if it's simply that some people, somewhere in the code, forget to divide by upperBound :shrug:

so what about .lowerBound or non-zero .begin? I didn't even dare to try it 🥲

**Comment by ash0080** [comment]
> Hi @ash0080, Thanks for filing the issue. I am quite not sure I understood your proposal.
> 
> > what do you think is the upper limit of the time value?
> 
> The upperBound of time is the end value specified in tween, As mentioned in the docs
> 
> > _animation = Tween(
> > begin: const Offset(100.0, 50.0),
> > end: const Offset(200.0, 300.0),
> > ).animate(_controller);
> > In both cases, the _animation variable holds an object that, over the lifetime of the _controller's animation, returns a value (_animation.value) that depicts a point along the line between the two offsets above.
> 
> Consider the below example which logs the value of `_time` , the end of logs will be `Tween.end`.
> 
> code sample

So this is another **genius design** 🤷 

Consider the case of using a lower bound, 
what happens if the begin of the tween is non-zero and the lowBound of the controller = 0?  
It's bizarre and not unavoidably bad design!

**Comment by maheshmnj** [comment]
Thanks for the info labelling this issue for further insights from the team.

**Comment by nt4f04uNd** [comment]
Hi @ash0080, before engaging here further please take a minute to review our [code of conduct](https://github.com/flutter/flutter/blob/master/CODE_OF_CONDUCT.md), which asks to

> Be kind. Be courteous. Be welcoming.

**Comment by ash0080** [comment]
> Be kind. Be courteous. Be welcoming.

I hope flutter itself can be as kind, courteous, and welcoming as the service team, that would be great!

**Comment by goderbauer** [comment]
You can already have exactly the functionality you seem to want by leaving upper and lower bound of the AnimationController at their default values of 1.0 and 0.0, respectively. 

With that, I am not sure I understand what this issue is asking for? What is the proposal?

**Comment by ash0080** [comment]
> 

You mean that AnimationController is designed with upper and lower borders, but users should not use it, is that right? If you are sure, please keep your opinion to yourself. As an experienced programmer, I can't agree with you.

**Comment by ash0080** [comment]
> You can already have exactly the functionality you seem to want by leaving upper and lower bound of the AnimationController at their default values of 1.0 and 0.0, respectively.
> 
> With that, I am not sure I understand what this issue is asking for? What is the proposal?

You mean that AnimationController is designed with upper and lower borders, but users should not use it, is that right? If you are sure, please keep your opinion to yourself. As an experienced programmer, I can't agree with you.

**Comment by Hixie** [comment]
@ash0080 Thank you for your bug report. Unfortunately, your use of language is not welcoming ("acting like a freak", a sarcastic "genius design", "bizarre and not unavoidably bad design!", "Did you get it right?", "someone forgot to write", "please keep your mind to yourself", "your statement is emotional"), nor is it "technical" as you put it.

I have applied a temporary ban to your account. Please reconsider how to be fun and welcoming when reporting bugs before returning. Thank you.

**Comment by maheshmnj** [comment]
I am going to close this issue for now as non-actionable from the secondary triage due to unclear description. If anyone disagrees feel free to comment on this issue with a clear description of the issue along with a proposed solution or consider filing a new issue.
