### ISSUE TITLE
 [camera] Android Preview Orientation Issues

### ISSUE THREAD

**Issue by fmardini** [flutter/flutter#101290]
Hi,

When starting the example app in the camera plugin on the Android Emulator (Pixel 5 API 31) even though the phone is in portrait mode the preview is in landscape. I initially thought this has to do with preview size, but placing the preview in a sized box and changing the width/height had no effect on the orientation. 

I'm not completely sure if this is a bug or expected behaviour. Furthermore, browsing the code I see that `CameraValue` has some orientation-related properties, but none seems related to this.

Is there a way to change preview orientation without changing device orientation?

Thanks,
Fouad

**Comment by danagbemava-nc** [comment]
Hi @fmardini, can you provide the version of `camera` you're experiencing this with, along with the output of `flutter doctor -v` and a complete minimal reproducible code sample? 

Kindly also check if https://github.com/flutter/flutter/issues/94045 is similar to the issue you're facing. 

Thank you

**Comment by fmardini** [comment]
Thanks @danagbemava-nc 

This is on the sample app coming with the camera plugin, latest git checkout. What is not clear to me, is whether the behaviour of the sample app is intended or buggy.

Yes indeed it seems very related to the issue you linked.

<details>
<summary>flutter doctor -v</summary>
[✓] Flutter (Channel stable, 2.10.1, on Mac OS X 10.15.7 19H1715 darwin-x64, locale en-GB)
    • Flutter version 2.10.1 at /usr/local/Caskroom/flutter/2.10.1/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db747aa133 (8 weeks ago), 2022-02-09 13:57:35 -0600
    • Engine revision ab46186b24
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/fmardini/Library/Android/sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code (version 1.66.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.38.0

[✓] Connected device (2 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 12 (API 31) (emulator)
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 99.0.4844.84

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
</details>

**Comment by danagbemava-nc** [comment]
>  What is not clear to me, is whether the behaviour of the sample app is intended or buggy.

From what I can see, the camera sample doesn't do anything to the preview orientation, so the issue may lie within the plugin code. 

Also, the issue I linked seems related to `startImageStream` but the camera sample doesn't use `startImageStream` so it's possible there's something else going on here.

Can you share a sample that shows how you determined that the orientation on android was "off"? Some logs would also be helpful and any screenshots or recordings as well. 

Thank you

**Comment by fmardini** [comment]
<img width="404" alt="Screenshot 2022-04-06 at 10 40 20" src="https://user-images.githubusercontent.com/2519/161946595-68e66c62-49ec-4526-abe4-80c405dc178f.png">

Here's a screenshot of the app running in the emulator. I would have expected the the preview to be rotated 90 CCW

**Comment by danagbemava-nc** [comment]
Hi @fmardini, I take it you're using the webcam of your host system as the camera for the emulator. In that case, this is not an issue with the camera package, but rather with the emulator itself. You can test this by opening the camera app of the emulator, it should also be rotated. See screenshot below

<details>
<summary>screenshot</summary>

<img width="449" alt="Screenshot 2022-04-07 at 06 36 49" src="https://user-images.githubusercontent.com/88313112/162135563-272a2b85-9937-4e82-9225-05311c60191b.png">
</details>

**Comment by fmardini** [comment]
@danagbemava-nc Thank you. I confirmed the orientation is correct when running on device. I also confirmed by running the Camera2 samples from https://github.com/android/camera-samples 

On the other hand, is it possible to change the orientation of the preview? Simply using a Flutter RotatedBox gives wrong aspect ratio.

Thanks,
Fouad

**Comment by danagbemava-nc** [comment]
Hi @fmardini, I don't think it is necessary for you to do that. 

From what I see in the code for the preview, the preview is already rotated, taking into account the aspect ratio, but if you are so inclined, you can check the code for the preview and modify it to suit your needs. The code can be found here https://github.com/flutter/plugins/blob/main/packages/camera/camera/lib/src/camera_preview.dart

**Comment by fmardini** [comment]
Yeah thanks, I've seen that. But was just wondering if there were an option to set it up relative to current orientation. Many thanks
