### ISSUE TITLE
`Timeline.instantSync` is not shown in DevTools

### ISSUE THREAD

**Issue by fzyzcjy** [flutter/flutter#101260]
## Steps to Reproduce

Hi thanks for the framework! I have some `Timeline.instantSync(...)` to report some events, and I also want to see some events reported in other libraries/the flutter framework. However, in DevTools's Performance panel, I cannot see it. I can only see spans created by `Timeline.startSync`.

1. Execute `flutter run` on the code sample 
2. ... 
3. ... 

**Expected results:** 
see above

**Actual results:** 
see above

<details>
<summary>Code sample</summary>

```dart
n/a
```

</details>

<details>
  <summary>Logs</summary>

```
n/a
```

```
n/a
```

```
latest stable
```

</details>

**Comment by darshankawar** [comment]
@fzyzcjy 
I suggest you to open this issue in devtools dedicated repo: https://github.com/flutter/devtools/issues.
Closing from here. If you get directed here again, write in comments and I'll reopen it.

**Comment by fzyzcjy** [comment]
OK thanks
