### ISSUE TITLE
Where is the code that generates the iOS/Android/etc. "native" output?

### ISSUE THREAD

**Issue by lancejpollard** [flutter/flutter#101211]
I asked this question on Reddit, [How does Dart (or Flutter) compile to iOS, Android, and other "native" code?](https://www.reddit.com/r/FlutterDev/comments/tu4sy8/how_does_dart_or_flutter_compile_to_ios_android/). Wondering how does Flutter (or Dart) generate the iOS-specific or Android-specific code, where is the source code which implements this? Similar to [dart2js](https://github.com/dart-lang/sdk/tree/main/pkg/compiler). Is it in this repo, the flutter/engine repo, or somewhere else? Thank you!

**Comment by darshankawar** [comment]
@lancejpollard 
Are you looking to know how the platform-specific code (Android, iOS) is being called by Flutter ? 
Please check [this](https://stackoverflow.com/a/43854798) SO answer and see if it helps.
