### ISSUE TITLE
Waking up screen without using custom code

### ISSUE THREAD

**Issue by susamongusacedemy** [flutter/flutter#101233]
Hi!

I am developing an alarm app and I want to wake the device whenever the alarm hits. The alarm is set with AndroidAlarmManager. I am able to play music but I want to wake up the device and show custom widget as a reminder UI (Like Time's up and all that).

I have found many different ways to do it, however, I want to know a method / plugin without writing native code.

If there is someone who has achieved this, I would be glad if they wrote down how to do it step by step

`fluttur docker`:

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.3, on EndeavourOS 5.16.15-arch1-1, locale en_IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

• No issues found!
```

**Comment by maheshmnj** [comment]
Hi @susamongusacedemy, Thanks for filing the issue. I believe you will have to write native code to display widgets out of the app. If you need help with achieving the desired result, I would suggest you to please post such questions on [community forums](https://flutter.dev/community) like StackOverflow with some minimal code and a description.

Closing as this is neither a bug nor a feature request.
