### ISSUE TITLE
 NSInternalInconsistencyException Invalid JSON message, decoding failed CoreFoundation ___exceptionPreprocess

### ISSUE THREAD

**Issue by yx-mike** [flutter/flutter#101236]
`flutter --version`
> Flutter 2.5.1025-0.0.pre.2 • channel main • ssh://git@gitlab.vdian.net:60022/flutter/flutter.git
Framework • revision 6cf843d94e (7 hours ago) • 2022-04-02 11:00:09 +0800
Engine • revision b3af521a05
Tools • Dart 2.14.2

`flutter doctor --verbose`
> [✓] Flutter (Channel main, 2.5.1025-0.0.pre.2, on macOS 12.2.1 21D62 darwin-arm, locale zh-Hans-CN)
    • Flutter version 2.5.1025-0.0.pre.2 at /Users/yangxin/Documents/vd_flutter/flutter
    • Upstream repository ssh://git@gitlab.vdian.net:60022/flutter/flutter.git
    • Framework revision 6cf843d94e (8 hours ago), 2022-04-02 11:00:09 +0800
    • Engine revision b3af521a05
    • Dart version 2.14.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

I compile the engine according to [Compiling-the-engine](https://github.com/flutter/flutter/wiki/Compiling-the-engine).
Then I found a crash message，

> #32708180 NSInternalInconsistencyException
Invalid JSON message, decoding failed
CoreFoundation ___exceptionPreprocess

stack：

> 3 -[FlutterJSONMessageCodec decode:] (in Flutter) + 544
4 -[FlutterJSONMethodCodec decodeMethodCall:] (in Flutter) + 68
5 __45-[FlutterMethodChannel setMethodCallHandler:]_block_invoke (in Flutter) + 44
6 flutter::PlatformViewIOS::HandlePlatformMessage(std::__1::unique_ptr<flutter::PlatformMessage, std::__1::default_delete<flutter::PlatformMessage> >) (in Flutter) + 524
7 std::__1::__function::__func<fml::internal::CopyableLambda<flutter::Shell::OnEngineHandlePlatformMessage(std::__1::unique_ptr<flutter::PlatformMessage, std::__1::default_delete<flutter::PlatformMessage> >)::$_16>, std::__1::allocator<fml::internal::CopyableLambda<flutter::Shell::OnEngineHandlePlatformMessage(std::__1::unique_ptr<flutter::PlatformMessage, std::__1::default_delete<flutter::PlatformMessage> >)::$_16> >, void ()>::operator()() (in Flutter) + 92
8 fml::MessageLoopImpl::FlushTasks(fml::FlushType) (in Flutter) + 1584
9 fml::MessageLoopDarwin::OnTimerFire(__CFRunLoopTimer*, fml::MessageLoopDarwin*) (in Flutter) + 32

How do I disable NSAssert in release mode?
Is there any configuration in gn or ninja?

**Comment by maheshmnj** [comment]
Hi @yx-mike, Thanks for filing the issue. Can you please share the complete crash log? Additionally please try upgrading to the latest stable version using `flutter upgrade`
