### ISSUE TITLE
'package:flutter/src/animation/animation_controller.dart': Failed assertion: line 822 pos 12: 'elapsedInSeconds >= 0.0': is not true

### ISSUE THREAD

**Issue by alhamri** [flutter/flutter#101203]
this exception only faced me once, I'm not sure but I think it's a bug!!
I couldn't reproduce the code because I don't know in which line is the issue! as I said everything is working well only one time this issue arise. Also I use GetX in my application for state and Obx purpose,
only i can paste the lines where i used animation:

`animateTo(int page) {
    if (controller.value.hasClients) {
      controller.value.animateToPage(page,
          duration: const Duration(milliseconds: 10), curve: Curves.easeIn);
    }
  }`

--flutter doctor output:
E:\Flutter_UI\hij_greg_temp - Copy>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, 2.10.0-0.3.pre, on Microsoft Windows [Version 10.0.19043.1586], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[√] Chrome - develop for the web
[!] Visual Studio - develop for Windows (Visual Studio Enterprise 2019 16.11.1)
    X Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop development with C++"
      workload, and include these components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK
[√] Android Studio (version 2021.1)
[√] Android Studio (version 2021.1)
[√] Android Studio (version 4.2)
[√] VS Code (version 1.59.1)
[√] Connected device (4 available)
[√] HTTP Host Availability

! Doctor found issues in 1 category.

Exception details on run console:
======== Exception caught by scheduler library =====================================================
The following assertion was thrown during a scheduler callback:
'package:flutter/src/animation/animation_controller.dart': Failed assertion: line 822 pos 12: 'elapsedInSeconds >= 0.0': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      AnimationController._tick (package:flutter/src/animation/animation_controller.dart:822:12)
#3      Ticker._tick (package:flutter/src/scheduler/ticker.dart:238:12)
#4      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
#5      SchedulerBinding.handleBeginFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:1057:11)
#6      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:539:8)
#7      SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:1055:17)
#8      SchedulerBinding._handleBeginFrame (package:flutter/src/scheduler/binding.dart:974:5)
#12     _invoke1 (dart:ui/hooks.dart:170:10)
#13     PlatformDispatcher._beginFrame (dart:ui/platform_dispatcher.dart:286:5)
#14     _beginFrame (dart:ui/hooks.dart:104:31)
(elided 5 frames from class _AssertionError and dart:async)

This exception was thrown in the context of a scheduler callback. When the scheduler callback was _registered_ (as opposed to when the exception was thrown), this was the stack: 
#2      SchedulerBinding.scheduleFrameCallback (package:flutter/src/scheduler/binding.dart:523:49)
#3      Ticker.scheduleTick (package:flutter/src/scheduler/ticker.dart:253:47)
#4      Ticker.start (package:flutter/src/scheduler/ticker.dart:162:7)
#5      AnimationController._startSimulation (package:flutter/src/animation/animation_controller.dart:745:42)
#6      AnimationController.animateWith (package:flutter/src/animation/animation_controller.dart:736:12)
#7      new BallisticScrollActivity (package:flutter/src/widgets/scroll_activity.dart:536:9)
#8      ScrollPositionWithSingleContext.goBallistic (package:flutter/src/widgets/scroll_position_with_single_context.dart:146:21)
#9      ScrollDragController.end (package:flutter/src/widgets/scroll_activity.dart:412:14)
#10     ScrollableState._handleDragEnd (package:flutter/src/widgets/scrollable.dart:652:12)
#11     DragGestureRecognizer._checkEnd.<anonymous closure> (package:flutter/src/gestures/monodrag.dart:485:47)
#12     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:198:24)
#13     DragGestureRecognizer._checkEnd (package:flutter/src/gestures/monodrag.dart:485:5)
#14     DragGestureRecognizer.didStopTrackingLastPointer (package:flutter/src/gestures/monodrag.dart:393:9)
#15     OneSequenceGestureRecognizer.stopTrackingPointer (package:flutter/src/gestures/recognizer.dart:392:9)
#16     DragGestureRecognizer._giveUpPointer (package:flutter/src/gestures/monodrag.dart:402:5)
#17     DragGestureRecognizer.handleEvent (package:flutter/src/gestures/monodrag.dart:321:7)
#18     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:94:12)
#19     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:139:9)
#20     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:539:8)
#21     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:137:18)
#22     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:123:7)
#23     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:439:19)
#24     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:419:22)
#25     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:322:11)
#26     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:374:7)
#27     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:338:5)
#28     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:296:7)
#29     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:279:7)
#33     _invoke1 (dart:ui/hooks.dart:170:10)
#34     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:331:7)
#35     _dispatchPointerDataPacket (dart:ui/hooks.dart:94:31)
(elided 5 frames from class _FrameCallbackEntry and dart:async)
====================================================================================================

**Comment by darshankawar** [comment]
> Channel beta, 2.10.0-0.3.pre

You are on older version of beta. Current version is 2.12. So please upgrade and try again to see if you still get same error.



> Also I use GetX in my application for state and Obx purpose,

If it replicates, please provide us a complete minimal code sample without any third party plugins. GetX is third party. In order to determine the cause of the bug, we would need a reproducible code sample.
