### ISSUE TITLE
Add an AppLifecycleState corresponding to 'applicationDidEnterBackground' on iOS.

### ISSUE THREAD

**Issue by jiajiabingcheng** [flutter/flutter#10123]
Hi Flutter team,

I have a use case which needs to use the iOS 'applicationDidEnterBackground' state. 

Currently flutter has 'AppLifecycleState.paused' which is corresponding to 'applicationWillResignActive' on iOS side. This will see the app is in background when there's an interruption(such as phoneCall, TouchId and etc.) which is not what I want.

So I'm wondering if we could add a new state in flutter which is corresponding to 'applicationDidEnterBackground' on iOS. On Android, we can still use onPaused() for this new state.

Thanks!

**Comment by eseidelGoogle** [comment]
Sounds very reasonable.  @cbracken @Hixie

**Comment by cbracken** [comment]
I've got a couple of WIP patched that get this working for iOS. Looking at whether we expose this as an iOS-only state, or if there's a reasonable way to reconcile this with the Android state transitions.

The [lifecycle states on iOS](https://developer.apple.com/library/content/documentation/iPhone/Conceptual/iPhoneOSProgrammingGuide/TheAppLifeCycle/TheAppLifeCycle.html#//apple_ref/doc/uid/TP40007072-CH2-SW3) differ somewhat from the [lifecycle states on Android](https://developer.android.com/guide/components/activities/activity-lifecycle.html#alc), so I'm looking at whether we add a new iOS-only state, or see if we can reconcile with the Android transitions in some reasonable way.

On iOS `willResignActive` is fired when an app enters a phone call/touchID, or when the app is backgrounded (e.g. via the Home button) from this point you can then transition either back to an active state or into background state, at which point `applicationDidEnterBackground` is fired.

On the surface the transitions on Android appear similar, but Android lacks an equivalent to iOS's inactive foreground state and iOS lacks an equivalent to Android's `onStop()` callback.

My current thought is to model this as an additional `inactivated` state, with transitions that look like: resumed <-> inactive <-> paused. On Android, we'd synthesise the inactive state as we transition between resumed and paused. On iOS we'd respond to the underlying OS events. There's probably a better name than inactive here. I'm open to suggestions :)

**Comment by Hixie** [comment]
What's the difference between the iOS state between willResignActive and applicationDidEnterBackground, and the Android state between onPause and onStop?

**Comment by cbracken** [comment]
The state transition signalled by `willResignActive` between the active foreground state and the inactive foreground state. This is basically a signal that your app is no longer responding to touch (e.g. received a phone call, doing touch ID, etc.) but is still foreground. It's not necessarily an indication that your app will be backgrounded though. Games, for example, might want to pause here. There's no real equivalent of this state for Android.

The state transition signalled by `applicationDidEnterBackground` between the inactive foreground state and the background state is meant to give the app time to launch any necessary tasks before it transitions to the suspended state; time remaining before you get suspended can be got at via `[UIApplication backgroundTimeRemaining]`. Apple [documents](https://developer.apple.com/reference/uikit/uiapplicationdelegate/1622997-applicationdidenterbackground) that you've got approximately 5 seconds to do any cleanup unless you fire off tasks via the background task API. This is roughly equivalent to the state between `onPause` and `onStop` on Android.

**Comment by Hixie** [comment]
Ah! Ok.

I recommend we have four states then:
- foreground (AppLifecycleState.resumed)
- visible but not foreground (AppLifecycleState.somethinged)
- not visible, still running (AppLifecycleState.paused)
- not visible, still running but about to get suspended (AppLifecycleState.suspending)

**Comment by jiajiabingcheng** [comment]
I'm ok with having a 'inactivated' state: *'resumed'-> 'inactivated'
state(willResignActive for iOS, onPause for Android)->
'paused'(didEnterBackground for iOS, still onPause for Android)*.

With Ian's idea, do you think we can match:
Android's *onStart* for iOS's *applictionWillEnterForeground*,
Android's *onResume* for iOS's *applictionDidBacomeActive,*
Android's *onPaused* for iOS's both *applicationWillResignActive* and
*applicationDidEnterBackgroud
*?

Thanks Chris and Ian :)

**Comment by cbracken** [comment]
Fixed by flutter/engine#3713 and flutter/flutter#10306.
