### ISSUE TITLE
`prefer_final_parameters` lint error in `generated_plugin_registrant.dart`

### ISSUE THREAD

**Issue by DetachHead** [flutter/flutter#101252]
## Steps to Reproduce

1. enable `prefer_final_parameters` in `analysis_options.yaml`:
    ```yaml
    linter:
        rules:
            prefer_final_parameters: true
    ```
2. run `dart analyze`

**Expected results:** 
no error, as it's a generated file that should never trigger any lint errors

either `final` should be added to the `registrar` parameter, or the rule should be ignored like the others

**Actual results:** 
```
   info - Prefer final for parameter declarations if they are not reassigned -
          lib\generated_plugin_registrant.dart:13:22 - prefer_final_parameters
```
<details>
<summary>Code sample</summary>

```dart
//
// Generated file. Do not edit.
//

// ignore_for_file: directives_ordering
// ignore_for_file: lines_longer_than_80_chars
// ignore_for_file: depend_on_referenced_packages

import 'package:file_picker/_internal/file_picker_web.dart';
import 'package:flutter_web_plugins/flutter_web_plugins.dart';

// ignore: public_member_api_docs
void registerPlugins(Registrar registrar) {
  FilePickerWeb.registerWith(registrar);
  registrar.registerMessageHandler();
}
```

**Comment by maheshmnj** [comment]
Hi @DetachHead, Thanks for filing the issue. 

There is a similar issue describing this case https://github.com/flutter/flutter/issues/99952, Please follow up there for further updates, Closing this issue as a duplicate. If you disagree feel free to write in the comments and we will reopen it.

Thank you.
