### ISSUE TITLE
Problem with the release version

### ISSUE THREAD

**Issue by EKvince** [flutter/flutter#101258]
Everything is fine in the debug version, but with two problems in the release

1. Use the shared_preferences plugin in the debugging version, and the storage works normally.In the release version, if missing 

   ```dart
   "SharedPreferences.setMockInitialValues ({});".
   ```

   It will be displayed

   ```
   E/flutter (23058): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: MissingPluginException(No implementation found for method requestPermissions on channel flutter.baseflow.com/permissions/methods)
   E/flutter (23058): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156)
   E/flutter (23058): <asynchronous suspension>
   E/flutter (23058): #1      PermissionHandler.requestPermissions (package:permission_handler/src/permission_handler.dart:97)
   E/flutter (23058): <asynchronous suspension>
   E/flutter (23058): #2      LocationFlutterPlugin.requestPermission (package:flutter_bmflocation/bdmap_location_flutter_plugin.dart:85)
   E/flutter (23058): <asynchronous suspension>
   E/flutter (23058):
   E/flutter (23058): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences)
   
   ```

   If  add 

   ```
   "SharedPreferences.setMockInitialValues ({});"
   ```

   When the APP is off, the data is cleared and it cannot be saved,but APP works.
   I have tried adding
   //android/app/src/main/java/com/example/catmap/MainActivity.java

   ```java
   public class MainActivity extends FlutterActivity {
   @Override
   public void configureFlutterEngine(@NonNull FlutterEngine flutterEngine) {
   super.configureFlutterEngine(flutterEngine);
   flutterEngine.getPlugins().add(new InstallAPKPlugin(this));
     }
   }
   ```

   But when I compile it:

* ```
  * What went wrong:
    Execution failed for task ':app:compileReleaseJavaWithJavac'.
  
  > Compilation failed; see the compiler error output for details.
  ```

  if 

  ```java
  import io.flutter.embedding.android.FlutterActivity;
  
  public class MainActivity extends FlutterActivity {
  //    @Override
  //    public void configureFlutterEngine(@NonNull FlutterEngine flutterEngine) {
  //        super.configureFlutterEngine(flutterEngine);
  //        flutterEngine.getPlugins().add(new InstallAPKPlugin(this));
  //    }
  }
  ```

  it works

2. Debug the version of the "image_picker "plugin is working normally.

   Using this plugin in the release gets stuck and the function calls this up again

   ```
   E/flutter (22312): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: PlatformException(already_active, Image picker is already active, null, null)
   E/flutter (22312): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:581)
   E/flutter (22312): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158)
   E/flutter (22312): <asynchronous suspension>
   E/flutter (22312): #2      ImagePicker.pickImage (package:image_picker/image_picker.dart:85)
   E/flutter (22312): <asynchronous suspension>
   E/flutter (22312): #3      getImageByGallery.<anonymous closure> (package:catmap/server/GetImageByGallery.dart)
   E/flutter (22312): <asynchronous suspension>
   ```

   flutter doctor：

   Doctor summary (to see all details, run flutter doctor -v):
   [√] Flutter (Channel stable, 2.0.6, on Microsoft Windows [Version 10.0.19044.1586], locale zh-CN)
   [√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
   [√] Chrome - develop for the web
   [√] Android Studio (version 4.1.0)
   [√] IntelliJ IDEA Ultimate Edition (version 2021.1)
   [√] Connected device (3 available)

   • No issues found!

Please Help!

**Comment by EKvince** [comment]
This is pubspec.yaml:

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter_native_image: ^0.0.6+1
  html: ^0.15.0
#  amap_location: ^0.2.0
  flutter_bmflocation: 1.0.2
  image_picker: ^0.6.0+10
  event_bus: ^2.0.0
  dio: ^4.0.0
  shared_preferences: ^2.0.6
  flutter_drag_scale:
    git: https://github.com/LiuC520/flutter_drag_scale.git
  fluttertoast: ^8.0.7
  transparent_image: ^2.0.0
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

**Comment by darshankawar** [comment]
@EKvince 
You are on very old version of Flutter. Current is 2.10.3. You also don't seem to be using null safety version and older plugin versions. I recommend to upgrade all to latest and try again. There have been updates made to Flutter plugins in recent versions.
I am going ahead and closing this since you are on very old version and using older plugin versions. After upgrade to latest if you still see same issue, write in comments and I'll reopen it.
