### ISSUE TITLE
MissingPluginException for getApplicationDocumentsDirectory at test on M1 macos.

### ISSUE THREAD

**Issue by wangmir** [flutter/flutter#101263]
When I launch this code at x64 linux environment it worked. But when I trying to test this code at M1 macos environment, it fails with MissingPluginException.

When I changed this code into `PathProviderMacOS().getApplicationDocumentsPath()`, the result was same.

```dart
void main() {
  group("test test group", () {

    test("Test", () async {
      await TestWidgetsFlutterBinding.ensureInitialized();
      String path = (await getApplicationDocumentsDirectory()).path;
    });
  });
}

```

**Comment by stuartmorgan** [comment]
Plugins do not work in unit tests, with rare exceptions. See discussion in https://github.com/flutter/flutter/issues/97100

The fact that it works on Linux is a side effect of how it was implemented for Linux, not the expected behavior.
