### ISSUE TITLE
iOS resident screenshot function doesn't always flush

### ISSUE THREAD

**Issue by xster** [flutter/flutter#10124]
Run a flutter app on simulator
Press 's' for screenshot

Not all the screenshots were written to file

![screen shot 2017-05-16 at 2 15 47 pm](https://cloud.githubusercontent.com/assets/156888/26128753/56860bd0-3a42-11e7-9918-770aad0146c5.png)

**Comment by xster** [comment]
Actually I even get this in the console when it happens
```
Taking screenshot for iPhone SE...                   165ms
Screenshot written to flutter_02.png (0kB).
```

**Comment by zoechi** [comment]
I'm not able to reproduce.

**Comment by xster** [comment]
Since it's from 2017 it's very possibly fixed already.
