### ISSUE TITLE
[Linux] App is very slow and logs message: Device returned a target frame rate of 0.0 FPS. Using 60 FPS instead.

### ISSUE THREAD

**Issue by Haidar0096** [flutter/flutter#101362]
## Details

 I am building an image editor app for window and linux. When I run it on linux (debug or release mode all the same), it is very slow although It still has no real heavy logic or widgets or computation happening, I am sure there is something wrong with Flutter for linux in my case. Also, maybe relevant, when I run the app from android studio I get this message `Device returned a target frame rate of 0.0 FPS. Using 60 FPS instead.`

**Linux:**
**Ubuntu 20.04**
**pc with intel core i5 8250U and 16 GB RAM and 1TB SSD**

**Windows 11:**
**same pc**

Note also that I am using an acer 144 Hz external monitor (and my laptops max fps is 60)

## Logs

There are no logs as there is only the error that says `Device returned a target frame rate of 0.0 FPS. Using 60 FPS instead.`

```
Analyzing image_editor...                                               
No issues found! (ran in 1.8s)

```

```
 flutter doctor -v
[✓] Flutter (Channel stable, 2.10.4, on Ubuntu 20.04.4 LTS 5.13.0-39-generic, locale en_US.UTF-8)
    • Flutter version 2.10.4 at /home/haidar/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (11 days ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc1)
    • Android SDK at /home/haidar/Android/Sdk
    • Platform android-32, build-tools 33.0.0-rc1
    • Java binary at: /snap/android-studio/119/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[✓] Android Studio (version 2021.1)
    • Android Studio at /snap/android-studio/119/android-studio
    • Flutter plugin version 65.2.2
    • Dart plugin version 211.7811
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.3)
    • IntelliJ at /snap/intellij-idea-ultimate/348
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code
    • VS Code at /snap/code/current
    • Flutter extension version 3.28.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 20.04.4 LTS 5.13.0-39-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 100.0.4896.60

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```

</details>

**Comment by maheshmnj** [comment]
Hi @Haidar0096, Thanks for filing the issue. Do you see this issue when running the app in any specific mode (debug/profile/release) or all modes? Can you check if this is an issue with a newly created project too by running some sample animations like [Physics Simulation](https://docs.flutter.dev/cookbook/animation/physics-simulation)?

**Comment by Haidar0096** [comment]
> Hi @Haidar0096, Thanks for filing the issue. Do you see this issue when running the app in any specific mode (debug/profile/release) or all modes? Can you check if this is an issue with a newly created project too by running some sample animations like [Physics Simulation](https://docs.flutter.dev/cookbook/animation/physics-simulation)?

the issue occurs in all mode (release debug profile)
but if I build the app with `flutter build linux --release` then the resulting exexcutable runs alot better than the above modes (there are still some lags)

I think this has something to do with pre-compiling the shaders (I asked about it with details on SO https://stackoverflow.com/questions/71764220/how-to-minimize-shader-jank-on-linux)

**Comment by maheshmnj** [comment]
Thanks for the info @Haidar0096, Please share a minimal and complete code sample along with a screen recording of the output and the timeline trace json file. You can find more info about how to do it in this issue https://github.com/flutter/flutter/issues/74833

**Comment by Haidar0096** [comment]
here is what you want:

flutter doctor:

```
 flutter doctor -v
[✓] Flutter (Channel master, 2.13.0-0.0.pre.393, on Ubuntu 20.04.4 LTS
    5.13.0-39-generic, locale en_GB.UTF-8)
    • Flutter version 2.13.0-0.0.pre.393 at
      /home/haidar/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 94fefaa49d (2 hours ago), 2022-04-06 17:17:34 +0530
    • Engine revision 45bedbe841
    • Dart version 2.17.0 (build 2.17.0-266.0.dev)
    • DevTools version 2.12.1

[!] Android toolchain - develop for Android devices (Android SDK version
    33.0.0-rc1)
    • Android SDK at /home/haidar/Android/Sdk
    • Platform android-32, build-tools 33.0.0-rc1
    • Java binary at: /snap/android-studio/119/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[✓] Android Studio (version 2021.1)
    • Android Studio at /snap/android-studio/119/android-studio
    • Flutter plugin version 66.0.1
    • Dart plugin version 211.7811
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.3)
    • IntelliJ at /snap/intellij-idea-ultimate/348
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code
    • VS Code at /snap/code/current
    • Flutter extension version 3.28.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 20.04.4 LTS
      5.13.0-39-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 100.0.4896.75

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```

as for the code: this is the app that I tried and is lagging: https://github.com/Haidar0096/Image-Editor-Desktop-Flutter

even a splash effect on a button lags

**Comment by maheshmnj** [comment]
Thanks for the code sample @Haidar0096, The app seems to work fine to me. Do you see any issue in the below output?
 
https://user-images.githubusercontent.com/31410839/162129762-d76141d3-b6fb-4d67-8a34-b22862b3cb1c.mp4


If not, Could you please share the output that you are seeing?

<details>
<summary>flutter doctor -v (Linux)</summary>

```
[✓] Flutter (Channel stable, 2.10.4, on Ubuntu 20.04.4 LTS 5.13.0-30-generic, locale en_GB.UTF-8)
    • Flutter version 2.10.4 at /home/mahesh/Development/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (12 days ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /home/mahesh/Android/Sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /home/mahesh/Downloads/android-studio-2020.3.1.25-linux/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 2020.3)
    • Android Studio at /home/mahesh/Downloads/android-studio-2020.3.1.25-linux/android-studio
    • Flutter plugin version 63.2.1
    • Dart plugin version 203.8452
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.64.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.38.1

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 20.04.4 LTS 5.13.0-30-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 98.0.4758.102

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

Complete logs can be found here [logs.txt](https://github.com/flutter/flutter/files/8440443/logs.txt)

**Comment by Haidar0096** [comment]
> 

Thank you for taking time to try it, on discord flutter dev also someone tried it and had the same result as you: no issues.

But for me, any mode I run it in (release, profile, debug) has lags even on simple animations like dragging the image or splash effect on a button.

As for the output I am seeing, in the console there are no errors, just normal logs like the ones you shared.

As for dart devtools, I saw jank frames and I included a screenshot in the stackoverflow question (I shared link to it above and here it is again https://stackoverflow.com/questions/71764220/how-to-minimize-shader-jank-on-linux). The screenshot shows  `GrGLProgramBuilder::finalize` in the details of the slow frames of the Raster thread, which is according to this official flutter page a definitive consequence of shader compilation jank https://docs.flutter.dev/perf/rendering/shader#what-is-shader-compilation-jank)

Just one thing to notice is that when I run `flutter build linux` and then run the output file (found in `build/linux/x64/release/bundle`), then the app almost runs normally and alot better than the 3 modes mentioned above.

So maybe this is a shader compilation jank problem and we can fix it by precompiling the shaders needed? But I don't know how to do that for linux, the flutter page above only mentions it for android and ios.

and if it is relevant: I am running on ubuntu 20.04, 16 GB ram, intel i5 8250U, so the machine is not that bad to not lag for such a simple app

thank you

**Comment by Haidar0096** [comment]
![image](https://user-images.githubusercontent.com/49842031/162231132-e5e119c3-c3c7-473d-b43c-8d55f99695cc.png)
here is what I am seeing in the devtools.

and here is what I see in android studio (~24 fps !!!)
![image](https://user-images.githubusercontent.com/49842031/162231848-2435483b-b95e-473f-ae5f-b92209f86ef1.png)


on master channel, I could get the app to run at ~50fps in profile mode, but I am expecting it to run at 60fps at least.



here is the json file , I uploaded it in the project root on github

https://github.com/Haidar0096/Image-Editor-Desktop-Flutter/blob/master/dart_devtools_2022_4_7-1649343826261000.json

**Comment by maheshmnj** [comment]
Thanks for the info @Haidar0096.
I am unable to reproduce the issue. The app is missing frames only on the author's device, Reproducible code sample can be found here https://github.com/Haidar0096/Image-Editor-Desktop-Flutter

Heres the timeline trace from the author's device [timeline_trace.json.zip](https://github.com/flutter/flutter/files/8448961/timeline_trace.json.zip)

**Comment by rajshreeyoga** [comment]
Hi I am getting a similar issue on an AMD Threadripper with an AMD Graphics Card. The app takes a long time to load and is practically unusable. If you need and diagnostic information please let me know, I will be happy to share. 

There's another thing: the app loads an ancient version of the dashboard that I have created even after I have updated it several times since. I'm having no such issues on my windows PC.
