### ISSUE TITLE
CocoaPods not installed. Skipping pod install. CocoaPods not installed or not in valid state.

### ISSUE THREAD

**Issue by Sbenari** [flutter/flutter#101367]
After working on my project for months without a hitch, suddenly out of the blue I get the Warning: `CocoaPods not installed. Skipping pod install` error, when trying to install my app on the simulator. The app works fine when installing it into the Android emulator or when installing it using Android Studios. Following a pandemonium of instructions from various user groups such as StackOverflow and others. trying many different things I reached no resolution to this Major problem, which appears to be ignored by the developer of this system. why is this happening? and why there is no detailed step-by-step instruction on how to fix this problem? Hours and days are spent figuring this thing out. in my case without results. My project is built on macOS and I use Android Studio ArcticFox.

## Steps to Reproduce

1) sudo gem uninstall cocoapods
2)sudo gem install cocoapods
3)restart
4)Invalidate cache and restart
5)pod Install in the ios directory
6)restart
7) brew install cocoapods
8)restart
9) flutter build
10) restart
11) remove podfile.lock
12)restart

none of these worked I have no idea what else I can do

## Logs

```
Warning: CocoaPods not installed. Skipping pod install.
CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
Without CocoaPods, plugins will not work on iOS or macOS.
For more info, see https://flutter.dev/platform-plugins
To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

CocoaPods not installed or not in valid state.
Error launching application on iPhone 12 mini.</summary>
```

## CocoaPods Environment

ℹ ### Stack
```
CocoaPods : 1.11.3
Ruby : ruby 2.6.8p205 (2021-07-07 revision 67951) [universal.x86_64-darwin21]
RubyGems : 3.0.3.1
Host : macOS 12.3 (21E230)
Xcode : 13.3 (13E113)
Git : git version 2.32.0 (Apple Git-132)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

Executable Path: /usr/local/bin/pod

### Plugins

cocoapods-deintegrate : 1.0.5
cocoapods-plugins : 1.0.0
cocoapods-search : 1.0.1
cocoapods-trunk : 1.6.0
cocoapods-try : 1.2.0

### Podfile

```ruby
# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
```

</details>

**Comment by maheshmnj** [comment]
Hi @Sbenari, Thanks for filing the issue. Please share the complete output of `flutter doctor -v`  and `flutter run -v` in a text file. Additionally, please check if the newly created flutter project builds fine?

> The app works fine when installing it into the Android emulator or when installing it using Android Studios.

This is because cocoa pods are only used on the IOS side to configure the dependencies.

**Comment by Sbenari** [comment]
@maheshmnj you can close the case, the problem went away after updating my IDE and flutter's latest version

**Comment by maheshmnj** [comment]
> you can close the case, the problem went away after updating my IDE and flutter's latest version

Thanks for the update. Closing based on the above response.
