### ISSUE TITLE
[camera] android camera plugin camera access permission

### ISSUE THREAD

**Issue by hellohuanlin** [flutter/flutter#101384]
## Use case

This issue is to track work on the camera access permission for camera plugin on Android platform. 

1. Please review [the proposal](https://docs.google.com/document/d/1t_5FYzOTlBWC6arHc4_8VuG0BUOtIyP9xWvbDER5Y9I/edit
) and leave any comments/discussions
2. Investigate if we really need [the "duplicate request" error](https://github.com/flutter/plugins/blob/04f64ec89b65f135fc43e8856af95b7d66e3e38a/packages/camera/camera/android/src/main/java/io/flutter/plugins/camera/CameraPermissions.java#L35). I did some research but I did not find similar practice elsewhere. 
3. Update the Android API to be consistent with other platforms. 

CC: @blasten @camsim99 @GaryQian

**Comment by blasten** [comment]
@camsim99 would you be interested in looking at this issue?

**Comment by camsim99** [comment]
This has been completed in https://github.com/flutter/plugins/pull/5640 and https://github.com/flutter/plugins/pull/6081.
