### ISSUE TITLE
[webview_flutter] Bypass ssl version 3.0.1

### ISSUE THREAD

**Issue by mdmota** [flutter/flutter#101354]
Iin previous versions it had android and ios folders where I could customize the plugin to bypass ssl. How would this customization be with this current plugin?

Files edited:
iOS) FLTWKNavigationDelegate -> didReceiveAuthenticationChallenge
Android )FlutterWebViewClient => onReceivedSslError

**Comment by maheshmnj** [comment]
Hi @mdmota, There is already a feature request filed for the same https://github.com/flutter/flutter/issues/36925. Please follow up there for further updates. Closing this issue as a duplicate.

**Comment by mdmota** [comment]
@maheshmnj  is not the same thing. I already know where to customize and which files to move. But in the current version the plugin no longer has the android and ios folders. Just want to know where I would edit this.
It seems that the plugin downloads other dependencies.

**Comment by maheshmnj** [comment]
@mdmota I do see the webview plugin does have ios and android folder.

**Comment by mdmota** [comment]
@maheshmnj  but in the latest version there is no https://github.com/flutter/plugins/tree/webview_flutter-v3.0.2/packages/webview_flutter/webview_flutter

**Comment by mdmota** [comment]
I understand it's not a good approach, but I copy the folder to my project and customize part of the android and ios code to bypass ssl.
How would I do with this separation of folders and projects from the new version?

**Comment by maheshmnj** [comment]
I am not sure about the changes that needs to be done but you can find ios and android specific folders on the link I shared above.
