### ISSUE TITLE
Text height is different on Web and Desktop

### ISSUE THREAD

**Issue by bernaferrari** [flutter/flutter#101303]
Flutter Web on the left, Flutter on macOS on the right.
<img width="552" alt="image" src="https://user-images.githubusercontent.com/351125/161596955-2a154578-895c-4e50-bcd0-99209140aede.png">

`height: 0` from TextStyle causes this difference.

```dart
import 'package:flutter/material.dart';

const Color darkBlue = Color.fromARGB(255, 18, 32, 47);

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: darkBlue,
      ),
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: Center(
          child: MyWidget(),
        ),
      ),
    );
  }
}

class MyWidget extends StatelessWidget {
  const MyWidget({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return SizedBox(
      width: 172,
      height: 115,
      child: Text(
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        style: TextStyle(
          fontSize: 18,
          height: 0,
        ),
      ),
    );
  }
}
```

```
➜ flutter doctor -v
[✓] Flutter (Channel stable, 2.10.4, on macOS 11.4 20F71 darwin-x64, locale
    en-BR)
    • Flutter version 2.10.4 at /usr/local/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (11 days ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2
```

**Comment by darshankawar** [comment]
@bernaferrari 
Thanks for the report. The desktop behavior seems to be occurring in stable only, as, on latest master, it renders properly as shown below:

![Screenshot 2022-04-05 at 2 17 54 PM](https://user-images.githubusercontent.com/67046386/161717181-eac2b816-8352-4f62-89c5-1f407db37811.png)

Stable (2.10.4):

![Screenshot 2022-04-05 at 2 22 19 PM](https://user-images.githubusercontent.com/67046386/161717271-fc6cecb1-9080-4874-84d9-3d83c15cf742.png)

You may confirm the same by switching to latest master.

I verified this on `Channel master, 2.13.0-0.0.pre.379`

**Comment by darshankawar** [comment]
I am closing this for now since your original issue has been fixed already on master. The web rendering indeed looks like an issue but it is specific to web and html rendering for which you may open a new issue for better tracking.
