### ISSUE TITLE
Flutter PopupMenu - How to detect whether PopupMenu is opened or not

### ISSUE THREAD

**Issue by subinsuresh** [flutter/flutter#101338]
I need to toggle the icon image of the popup menu when its opened n closed.
I think we can get the closed state in onSelect and onDismiss method. 
But how to catch when popup menu is visible??

**Comment by darshankawar** [comment]
@subinsuresh 
Your question is better suited for support channels like StackOverflow, so please ask the same there.
Closing from here as this is more of a code assistance question rather than a bug or feature request.
