### ISSUE TITLE
I have issues with Missing Push Notification Entitlement

### ISSUE THREAD

**Issue by auphantum** [flutter/flutter#101341]
## Steps to Reproduce

1. Add Push Notification Services on IOS
2. Archive the project and upload it on appstore connect
3. I got an email with Missing Push Notification Entitlement

[✓] Flutter (Channel stable, 2.10.1, on macOS 11.6.1 20G224 darwin-x64, locale en-PH)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] IntelliJ IDEA Community Edition (version 2017.2.5)
[✓] VS Code (version 1.60.1)
[✓] Connected device (1 available)
[✓] HTTP Host Availability

**Comment by darshankawar** [comment]
@auphantum 
This doesn't seem to be Flutter specific. See [this](https://developer.apple.com/forums/thread/64417) link and check if it helps to resolve the issue. Else you'll need to raise this with Apple support.
Closing from here.

**Comment by Dalton-Vo** [comment]
Can you help me push notification from webview
