### ISSUE TITLE
DropdownButtonFormField - do not show selected value - only see the hint

### ISSUE THREAD

**Issue by LAPPIT** [flutter/flutter#101340]
After upgrading Flutter the DropdownButtonFormField do not work as expected, when I deploy my project to Firebase Hosting. It works perfect on Android and when starting it for web with: 'flutter run -d chrome -web-port=4000', which makes it hard to debug.

Since I know that you want to have a small reproduction of the problem, I tried to make a small app, with just the DropdownButtonFormField and deploy it to the same project on Firebase Hosting, and then it worked fine :/

It seems like the problem occurs, when the DropDownButtonFormField is deep in the widget-tree and I have the same problem, with all my DropDownButtonFormFields.

To be able to debug the problem, I copied the source code of DropdownButtonFormField to my own project and renamed it to ComboTest (just a name, to make sure my version was used) and added some logging to see what happened.

When deployed to Firebase Hosting, the logg then reached this code:
```dart
           return Focus(
              canRequestFocus: false,
              skipTraversal: true,
              child: Builder(builder: (BuildContext context) {
                _logga('ComboTest - Return InputDecorator');_
                return InputDecorator(
                  decoration: effectiveDecoration.copyWith(errorText: field.errorText),
                  isEmpty: isEmpty,
                  isFocused: Focus.of(context).hasFocus,
                  child: DropdownButtonHideUnderline(

```
after that I get a log saying:
       main.dart.js:4170 [Violation] 'requestAnimationFrame' handler took 668ms

To be able investigate further, I also copied the code from the 'Form' (renamed to FormTest) and saved it with the ComboTest and added some logging there as well.

Depolyed to Firebase Hosting and tested and it suddenly worked fine :)       Just wonder why????

I'm happy that it worked, but do not want to copy the source from the Flutter framework into my project and I guess it is probably not allowed.

As soon as possible, I would like to go back to normal. 

Can you help me, by looking into what the cause might be?

Attach the Dart-file, with the changes I made.

My log from Flutter Doctor:
```
C:\Users\Mariette\IdeaProjects\MinSockerbitGrundDev\minsockerbitgrunddev>flutter doctor -v
[√] Flutter (Channel stable, 2.10.4, on Microsoft Windows [Version 10.0.19044.1586], locale en-SE)
    • Flutter version 2.10.4 at C:\Flutter\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (11 days ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\Mariette\AppData\Local\Android\sdk
    • Platform android-32, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] IntelliJ IDEA Ultimate Edition (version 2021.3)
    • IntelliJ at C:\Users\Mariette\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\213.6777.52
    • Flutter plugin version 65.2.4
    • Dart plugin version 213.7227

[√] VS Code (version 1.52.1)
    • VS Code at C:\Users\Mariette\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.20.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19044.1586]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 99.0.4844.84
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 99.0.1150.46

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```
[combo_test.dart.txt](https://github.com/flutter/flutter/files/8416160/combo_test.dart.txt)

**Comment by maheshmnj** [comment]
Hi @LAPPIT, Thanks for filing the issue. Inorder to investigate this issue further, we would need a [minimal and complete reproducible code](https://stackoverflow.com/help/minimal-reproducible-example) that can be copied and directly run with minimal or no changes. Can you also point the version where it used to work?

**Comment by LAPPIT** [comment]
Hello,

As I said in the description of the issue, I did not succeed in creating a minimal and complete reproducible code, since it always work then. I have made several attempts, but with no luck.


The alternative is that you look at my complete code, since I do not find the part that makes it go wrong. Just seems to be, when the DropdownButtonFormField is deep in the widget-tree. All my DropdownButtonFormFields get the same error.


To try debugging via logging when on Firebase Hosting, I copied the source code of DropdowButtonFormField, FormField and Form into my own project. Then I found that it worked when the ‘Flutter Framework’-code was compiled together with my code, instead of coming from the Flutter SDK. I assume there must be some difference in how the Flutter web is built, with ‘flutter run’ vs ‘flutter build web’.


I can not continue to debug with logs, since it now works, when the code for DropdowButtonFormField, FormField and Form is local to my project.


Get back to me if you are interested in looking at my whole project, since then it must be set up with the database.


I do not remember exactly which version of Flutter I upgraded from, but I upgrade quite frequently, so it should have been 2.10.3 or 2.10.2.


It does not feel right to have a copy the code from the framework directly in my project, since I would like to get your upgrades in the future. Hope it is possible to find a source of the problem.


Kind regards,
Mariette Lindström

**Comment by maheshmnj** [comment]
@LAPPIT, I tried using the above ComboTest widget in a web app and it seems to work fine.  We won't be able to investigate this issue further without a minimal code sample. The ComboTest widgets look fine to me. 

<details>
<summary>minimal code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:new_app/combo.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);
  final String title;
  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;
  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  String? dropdownValue = 'item 1';

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            ComboTest(
                onChanged: (String? x) {
                  setState(() {
                    dropdownValue = x;
                  });
                },
                value: dropdownValue,
                items: List.generate(10, (index) => 'item $index')
                    .toList()
                    .map((String e) =>
                        DropdownMenuItem<String>(value: e, child: Text(e)))
                    .toList()),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}

```
</details> 

I am going to close this issue for now, as this is not actionable further from our side. In case you have more info for us feel free to comment on this issue and we will reopen it.

Thank you.

**Comment by LAPPIT** [comment]
Hello,

The code in ComboTest is a copy of DropDownButtonFormField from the Flutter framework, that I have just renamed.

Since it works when just compiling it locally in my app, I hoped that it would be possible for you to just recompile any precompiled code (if there is any) used when running ‘flutter build web’ and it would work after that. If I where you, I would at least test to do so.

After all the original code for DropDownButtonFormField works perfect in my project on Android and using ‘flutter run -d chrome’ on the same code.  What is the difference?

Hope to be able to use the original code from the Flutter framework in the future, but for now I have to stick with the copy of your code in my ComboTest. Not a good solution, since I will miss any future updates from you on its functionality.

When googling, can see that I’m not the only one, with the same problem.

Regards,
Mariette Lindström

**Comment by maheshmnj** [comment]
@LAPPIT I believe you mean that the dropdownButton isn't working when compile for web using `flutter build web`, if so I tried the code sample, I shared above which uses the `combo_test.dart` and it seems to work fine. You can verify it here https://dropdownbutton.netlify.app/#/

Deployed code can be found here https://github.com/flutter/flutter/issues/101340#issuecomment-1089878415

**Comment by LAPPIT** [comment]
Hi,

What I mean is that the DropdownButtonFormField does not work with ‘flutter build web’, when I use your original widget.

But it works fine when I use my copy of your code (combo_test.dart). It is a copy of your code, that I have just renamed, to be sure which version was used during my tests.

That is why I suggested a recompile of any precompiled code there might be, if any.

Regards,
Mariette Lindström

**Comment by maheshmnj** [comment]
> What I mean is that the DropdownButtonFormField does not work with ‘flutter build web’, when I use your original widget.

Thanks for the clarification. However, you can verify this to be working in the interactive sample on the docs itself https://api.flutter.dev/flutter/material/DropdownButton-class.html 

> It works perfect on Android and when starting it for web with: 'flutter run -d chrome -web-port=4000', which makes it hard to debug.

I do understand that this issue is reproducible only in your application, But this makes it non-actionable on our side. I would suggest you please look for any unusual logs or you could share a reproducible project with us by removing any confidential and unnecessary part of code that doesn't  help reproduce the issue.

**Comment by LAPPIT** [comment]
Hi,

Your pointing to the description of the DropdownButton below. It is the DropdownButtonFormField that does not work.

I have given you the log information that I receive when it does not work and hinted on what you can do, without to much work. When googling I also find that I’m not the only one with this problem.

I have already spent too much time investigating the problem already and it will take me even more time to create a copy of my code that you can test with.

Because of that I have decided to stick with the solution with a copy of you source locally in my project, since it works in my case. It is not the way I want it, but I do not have the time to investigate further from my side.

Hope to get at better solution, sometime in the future.

Kind Regards,
Mariette Lindström
