### ISSUE TITLE
[Windows][PointerEvent] Stylus input recognized as touch on windows.

### ISSUE THREAD

**Issue by igameta** [flutter/flutter#101337]
## Bug details
Inputs which are using a stylus recognize as "touch" not "stylus" on windows.
I checked this issue would not  happen on Android and WebApp(DartPad).
I tried XP-Pen stylus and Wacom stylus, but this issue occured on both devices.
https://user-images.githubusercontent.com/29007466/161700735-2f0d12b7-6654-406c-8685-b0ec95a7a724.mp4

### Environment
OS: Windows11 Version 10.0.22000.556
Flutter: 2.10.2
Tablet:
- XP-Pen Artist12
- Wacom Intuos CTL-4100 

 

## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. Touch and move  a stylus.
3. PointerEvent.kind.toString() return "PointerDeviceKind.touch" 

**Expected results:** 
Stylus inputs will recognize as "stylus".
**Actual results:** 
Stylus inputs recognized as "touch".
<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'StylusInputBug',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'StylusInputBug'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);
  final String title;
  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  double posX = 0;
  double posY = 0;
  double pressure = 0;
  bool isStylus = false;
  String inputType = "None";

  void _penStatus(PointerEvent input) {
    // if (input.kind == ){
    setState(() {
      posX = input.position.dx;
      posY = input.position.dy;
      pressure = input.pressure;
    });
    // }
    inputType = input.kind.toString();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Listener(
        onPointerMove: _penStatus,
        child: SafeArea(
          child: Container(
            width: 500,
            height: 500,
            color: Colors.lightGreen,
            child: Column(children: [
              Text('StylusPosition:($posX,$posY)'),
              Text('StylusPressure:$pressure'),
              Text(inputType),
            ]),
          ),
        ),
      ),
    );
  }
}

```

</details>

I'm sorry for my bad English.
If you wouldn't understand my English, please ask me.

**Comment by darshankawar** [comment]
@igameta 
I believe you are seeing the reported behavior due to https://github.com/flutter/flutter/issues/65248.
So I suggest you to follow-up in it for further updates.
Closing this as a duplicate. If you disagree, write in comments and I'll reopen it.

**Comment by igameta** [comment]
@darshankawar 
Oh, I missed it.
Thank you.
