### ISSUE TITLE
[Fonts] Icon request: arrow_circle_right

### ISSUE THREAD

**Issue by mdshadatrahman** [flutter/flutter#101334]
Need this in flutter icon

**Comment by danagbemava-nc** [comment]
Hi @mdshadatrahman, this icon is already available on the stable channel. See https://api.flutter.dev/flutter/material/Icons/arrow_circle_right-constant.html.

Closing as the icon already exists.

**Comment by mdshadatrahman** [comment]
But I could not find one with the white color and black round
