### ISSUE TITLE
Flutter embedding V2 migration guide results in Android build error.

### ISSUE THREAD

**Issue by Turburlar** [flutter/flutter#101306]
I upgraded to the latest Flutter version.

Afterwards it started giving the error...

   
    Your Flutter application is created using an older version of the Android
    embedding. It is being deprecated in favor of Android embedding v2. Follow the
    steps at
    
    https://flutter.dev/go/android-project-migration
    
    to migrate your project. You may also pass the --ignore-deprecation flag to
    ignore this check and continue with the deprecated v1 embedding. However,
    the v1 Android embedding will be removed in future versions of Flutter.
    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    The detected reason was:
    
      /myAppPath/android/app/src/main/AndroidManifest.xml uses `android:name="io.flutter.app.FutterApplication"`
    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    
    Build failed due to use of deprecated Android v1 embedding.

I then went to the migration guide and implemented the required changes which were changing the first line to the second

    -android:name="io.flutter.app.FlutterApplication"
    +android:name="@{applicationName}"

Now I get the error...

FAILURE: Build failed with an exception.
    
    * What went wrong:
    Execution failed for task ':app:processReleaseResources'.
    > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
       > Android resource linking failed
         /pathToMyApp/android/app/src/main/AndroidManifest.xml:8:5-51:19: AAPT: error: attribute 'android:name' in <application> tag must be a valid Java class name.
    
    
    * Try:
    Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
    
    * Get more help at https://help.gradle.org
    
    BUILD FAILED in 41s
    Running Gradle task 'assembleRelease'...                           41.9s
    Gradle task assembleRelease failed with exit code 1

**Comment by maheshmnj** [comment]
Hi @Turburlar, thanks for filling the issue. Are you seeing this error with a newly created project too? Please share the complete output of `flutter run -v` and `flutter doctor -v`.
