### ISSUE TITLE
Allow Chip background to be state adaptive

### ISSUE THREAD

**Issue by suesitran** [flutter/flutter#101325]
## Use case
When I create a new Chip using Material Chip, I want to be able to set different background color to different material state.

Currently only Text color in chip is state adaptive.

## Proposal
1. Allow background color to receive MaterialStateColor
2. Use MaterialStateProperty to resolve color base on MaterialStateColor

**Comment by TahaTesser** [comment]
Instead of making the `background` property to support `MaterialState`, we've decided to a new more versatile  MaterialState `color` property.
