### ISSUE TITLE
`showDatePicker` documentation sample is not visible

### ISSUE THREAD

**Issue by asashour** [flutter/flutter#101343]
Steps to reproduce:

- Visit https://api.flutter.dev/flutter/material/showDatePicker.html#material.showDatePicker.1
- The screen shows empty sample, which doesn't look right.

![image](https://user-images.githubusercontent.com/2410127/161717156-fad3f565-88b8-40b5-b11e-aa4b807afb3a.png)

**Comment by danagbemava-nc** [comment]
Hi @asashour, this has been fixed on the master channel, so in the interim, you can use https://master-api.flutter.dev/flutter/material/showDatePicker.html#material.showDatePicker.1

The fix will roll out to stable in the future. 

Closing as this has already been fixed. 

Thank you
