### ISSUE TITLE
Pausing at wrong location on Flutter Web only (breakpoints / debugger) 

### ISSUE THREAD

**Issue by elliette** [flutter/flutter#101388]
The following reproduces with the Flutter Gallery example app: https://github.com/flutter/gallery

### Steps to reproduce:
1. start the gallery app with `flutter run -d chrome` (this does not reproduce on other platforms, eg `macos`)
2. set a breakpoint at [this line](https://github.com/flutter/gallery/blob/07e72e69c376ce27f635793323340b5af8bb2e58/lib/demos/material/app_bar_demo.dart#L15)
3. in the gallery app, click material > app bar

**Expected behavior:** the app pauses in `app_bar_demo.dart` at the breakpoint
**Actual behavior:** the app paused in `scheduler/binding.dart`

*Note: interestingly enough, if you open Chrome DevTools for the connected app, it will be paused at the **correct** place.*

#### Paused Flutter DevTools (incorrect location):
![Screen Shot 2022-03-31 at 10 28 01 AM](https://user-images.githubusercontent.com/21270878/161115385-f8a61785-13d5-4ba4-9c0f-f757dce26b51.png)
#### Paused Chrome DevTools (correct location):
![Screen Shot 2022-03-31 at 10 28 16 AM](https://user-images.githubusercontent.com/21270878/161115404-84561ed1-91a3-4fca-a452-63edaca47a73.png)

**Comment by annagrin** [comment]
@jorgesarabia looks like your issue is different and is due to a chrome update, we are working on fixing it currently: 

https://github.com/flutter/flutter/issues/101224

**Comment by elliette** [comment]
Confirmed that the issue described in https://github.com/flutter/flutter/issues/101388#issue-1193769859 will also be fixed by https://github.com/dart-lang/webdev/pull/1559

**Comment by jorgesarabia** [comment]
@annagrin @elliette 
Thanks a lot!! 🙏
