### ISSUE TITLE
Why doesn't the official provide this function directly?

### ISSUE THREAD

**Issue by ddxl123** [flutter/flutter#101353]
example,
```
void mountSetState(){
  if(mounted) setState((){});
}
```
Every asynchronous function always has to `if(mounted) setState((){});`
Obviously commonly used, but not directly provided.

**Comment by maheshmnj** [comment]
Hi @ddxl123,

> Every asynchronous function always has to if(mounted) setState((){}); 

This mainly applies to widgets that are currently mounted in the tree, mounted property helps prevent calling `setState` on a widget that is no longer part of a widget tree(already disposed) You can read more about it in the official docs https://api.flutter.dev/flutter/widgets/State/mounted.html

Closing as this is neither a bug nor a feature request.
