### ISSUE TITLE
images not given their own line on the intellij page

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#10130]
See https://flutter.io/intellij-ide/
![screen shot 2017-05-16 at 5 01 30 pm](https://cloud.githubusercontent.com/assets/5479/26133052/52b67cbc-3a59-11e7-9990-dd01c6c3ef97.png)

**Comment by Sfshaza** [comment]
This page now seems to be called using-ide. At any rate, this is no longer true. Closing.
