### ISSUE TITLE
Need clear documentation how to contribute to Flutter and run Flutter Test before submitting PR

### ISSUE THREAD

**Issue by suesitran** [flutter/flutter#101328]
## Steps to Reproduce
I follow the guideline from [this link](https://github.com/flutter/flutter/wiki/Setting-up-the-Framework-development-environment) to setup Framework development environment, but when i tried to run 'flutter test' in example, it failed to run

## Logs

<details>Log when running 'flutter test' command</details>
<summary>Logs</summary>

```
Because every version of flutter_goldens from sdk depends on vector_math 2.1.1 and flutter depends on vector_math 2.1.2, flutter_goldens from sdk is forbidden.
So, because flutter depends on flutter_goldens from sdk, version solving failed.
Running "flutter pub get" in flutter...                                 
pub get failed (1; So, because flutter depends on flutter_goldens from sdk, version solving failed.)

```

Flutter doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.3, on macOS 11.4 20F71 darwin-x64, locale en-AU)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.53.2)
[✓] Connected device (2 available)
[✓] HTTP Host Availability
```

</details>

**Comment by jonahwilliams** [comment]
Your flutter doctor says "Flutter Stable". I assume you checked out the SDK elsewhere to develop it, but then to run tests against it you need to use the `flutter` from the SDK and not your stable SDK

**Comment by suesitran** [comment]
I used only 1 Flutter SDK, and made changes directly, but i think I realised my issue now, my flutter is in stable channel. Let me try to change it to 'master' and run test
