### ISSUE TITLE
VideoPlayerController.file function improvement

### ISSUE THREAD

**Issue by Jack-Woodearth** [flutter/flutter#101342]
**Problem:**
The _VideoPlayerController.file()_ function doesn't work properly when the file path includes white spaces or utf-8 characters, i.e. the local video file can not be loaded correctly. 

**Sugesstion:**
The source code is like this.

```
VideoPlayerController.file(File file,
      {this.closedCaptionFile, this.videoPlayerOptions})
      : _**dataSource = 'file://${file.path}',**_
        dataSourceType = DataSourceType.file,
        package = null,
        formatHint = null,
        httpHeaders = const <String, String>{},
        super(VideoPlayerValue(duration: Duration.zero));
```

The bold code should be replaced with this code :  **_dataSource = file.uri.toString()._**
I tested it and it worked perfectly when file path includes white spaces or utf-8 characters.

**Comment by maheshmnj** [comment]
Hi @Jack-Woodearth, Thanks for filing the issue. What platform  are you facing this issue on? Can you please share the output of `flutter doctor -v` along with the complete output of `flutter run -v` in a text file?

**Comment by Jack-Woodearth** [comment]
> 
I am using MacOS and iOS physical machine.

[✓] Flutter (Channel stable, 2.10.4, on macOS 12.2.1 21D62 darwin-x64, locale
    zh-Hans-CN)
    • Flutter version 2.10.4 at /Users/dusic/flutter/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (13 days ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from:
      https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK
      components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup
      for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Users/dusic/Downloads/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✗] Chrome - develop for the web (Cannot find Chrome executable at
    /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup
      for detailed instructions).

[✓] VS Code (version 1.66.0)
    • VS Code at /Users/dusic/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.38.1

[✓] Connected device (1 available)
    • iPhone (mobile) • 00008101-000650490041401E • ios • iOS 15.1.1 19B81

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 3 categories.

**Comment by maheshmnj** [comment]
Thanks for the info, is your video file on the target device or on the host machine? Could you please share how you are fetching the video file path?

**Comment by Jack-Woodearth** [comment]
I am very sorry for the delay of replying. 

My video file is on my iPhone ( real machine ). 

The actual video file path:
/var/mobile/Containers/Data/Application/B7D1A2D0-B756-418A-8DF8-C039B5891CAB/Documents/movies/继承之战S02E04.mp4

Part of my code fetching the file path:

```
class VideoPlayerScreen extends StatefulWidget {
  const VideoPlayerScreen({Key? key, required this.videoFile})
      : super(key: key);
  final FileSystemEntity videoFile;

  @override
  State<VideoPlayerScreen> createState() => _VideoPlayerScreenState();
}
class _VideoPlayerScreenState extends State<VideoPlayerScreen> {
   

@override
void initState(){
super.initState();
   var file = File(widget.videoFile.path);
    printInfo(info: file.path);


    try {
      _controller = VideoPlayerController.file(file)
        ..initialize().then((_) {
        
      
          _chewieController = ChewieController(
            allowFullScreen: false,
            videoPlayerController: _controller,
          );
       
          setState(() {});
        });
    } catch (e) {
      printError(info: '$e');
  
   
    }
}

}
```

**Comment by Jack-Woodearth** [comment]
And  the error I am getting is that the video player can not be initialized, i.e. the call back after the video_player initializing method did not  run.
```
_controller = VideoPlayerController.file(file)
        ..initialize().then((_) { }
```
There is nothing displaying on the vscode debug console.

**Comment by Jack-Woodearth** [comment]
In my opinion, the official source code  `dataSource = 'file://${file.path}' ` clearly does not handle file uri encoding at all. It just arbitrarily  creates a uri with the file.path.  As we know, the file.path can contain non-English characters while the uri can not.

**Comment by darshankawar** [comment]
@Jack-Woodearth 


> when the file path includes white spaces or utf-8 characters, i.e. the local video file can not be loaded correctly.

@Jack-Woodearth 
Can you try by using `Uri.encodeFull` method to encode the path ? This way I think it'll handle white spaces and utf-8 chars.
So something like below:

```
final String _localFilePath = "";
final String _encoded = Uri.encodeFull(_localFilePath);
final io.File _videoFile = io.File(_encoded);
controller = VideoPlayerController.file(_videoFile); 
```
