### ISSUE TITLE
List class, part of dart.core, issue: List.indexOf is unavailable for List(growable=true)

### ISSUE THREAD

**Issue by thq919** [flutter/flutter#101327]
List.indexOf is unavailable for List(growable=true)
there is no fucking reference in documentation for it https://api.dart.dev/stable/2.16.2/dart-core/List/indexOf.html
(kinda spend on it like... 5 hours, thanks for understaning)
VisualStudioCode gives me error just indexOf returns -1, there is no index of searched item in list
 sends me to
growable_array.dart
279  @pragma("vm:recognized", "graph-intrinsic")
280  @pragma("vm:external-name", "GrowableList_getIndexed")
281  external T operator [](int index);

What does it mean GrowableList_getIndexed ? Is this prohibited ? Is this allowed ? Is this illegal or legal ?
Please, provide more information on docs, provide more information for this error.

And, im comparing items with hashcode, im totally assure thats there is same item in my list, as i am searching to, i am tried comparing it with hashcode, id, title, not myself override compare - no difference

**Comment by asashour** [comment]
Would you provide minimal case, and your flutter/dart versions used (using `flutter doctor -v`).

With IntelliJ, clicking on the `indexOf` opens the declaration in `list.dart`, and one can see the documentation there, I guess VisualStudioCode does the same thing.

The below case prints `1`:

```dart
void main() {
  var list = <int>[5, 3];
  var i = list.indexOf(3);
  print(i);
}
```

`Dart version 2.17.0 (build 2.17.0-265.0.dev)`

**Comment by darshankawar** [comment]
> there is no fucking reference in documentation for it https://api.dart.dev/stable/2.16.2/dart-core/List/indexOf.html

@thq919 
Please read github [code of conduct](https://docs.github.com/en/site-policy/github-terms/github-community-forum-code-of-conduct) and kindly try not to use such language while reporting issues or commenting.

Also this seems to be related to dart language and not Flutter, so please open this issue in dedicated repo: https://github.com/dart-lang/language/issues

Closing from here.

**Comment by thq919** [comment]
> Would you provide a minimal case, and your flutter/dart versions used (using `flutter doctor -v`).
> 
> With IntelliJ, clicking on the `indexOf` opens the declaration in `list.dart`, and one can see the documentation there, I guess VisualStudioCode does the same thing.
> 
> The below case prints `1`:
> 
> ```dart
> void main() {
>   var list = <int>[5, 3];
>   var i = list.indexOf(3);
>   print(i);
> }
> ```
> 
> `Dart version 2.17.0 (build 2.17.0-265.0.dev)

import 'dart:ui';

class SinglePhoneHomeStore {
  final int id;
  final bool? isNew;
  final String title;
  final String? subtitle;
  final String picture;
  final bool? isBuy;
  final bool? isFavorites;
  final int? priceWithoutDiscount;
  final int? discountPrice;

  SinglePhoneHomeStore({
    this.isFavorites,
    this.priceWithoutDiscount,
    this.discountPrice,
    this.isNew,
    this.subtitle,
    this.isBuy,
    required this.id,
    required this.title,
    required this.picture,
  });

  @override
  bool operator ==(dynamic other) {
    // ignore: unnecessary_this
    if (this.runtimeType == other.runtimeType && hashCode == other.hashCode) {
      return true;
    } else {
      return false;
    }
  }

  @override
  int get hashCode => hashValues(id, title);
}

place where i use index of 
indexOfElementToShow = phoneList!.indexOf(phone);
(phone type SinglePhoneHomeStore)
there is variables in runtime
List (4 items) phonelist
SinglePhoneHomeStore
SinglePhoneHomeStore
SinglePhoneHomeStore
SinglePhoneHomeStore

item that im searching index of has hash 391735408
in list that hash has first element 391735408 and has index 0
why do i get -1 ?

[✓] Flutter (Channel stable, 2.10.3, on Ubuntu 20.04.4 LTS 5.13.0-39-generic, locale en_US.UTF-8)
    • Flutter version 2.10.3 at /home/thq/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (5 weeks ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /usr/lib/android-sdk
    • Platform android-31, build-tools 29.0.2
    • ANDROID_HOME = /usr/lib/android-sdk
    • Java binary at: /home/thq/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/linux#android-setup for more details.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 2021.1)
    • Android Studio at /home/thq/android-studio
    • Flutter plugin version 63.2.2
    • Dart plugin version 211.7798
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code (version 1.66.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.38.0

[✓] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.

**Comment by thq919** [comment]
> Would you provide a minimal case, and your flutter/dart versions used (using `flutter doctor -v`).
> 
> With IntelliJ, clicking on the `indexOf` opens the declaration in `list.dart`, and one can see the documentation there, I guess VisualStudioCode does the same thing.
> 
> The below case prints `1`:
> 
> ```dart
> void main() {
>   var list = <int>[5, 3];
>   var i = list.indexOf(3);
>   print(i);
> }
> ```
> 
> `Dart version 2.17.0 (build 2.17.0-265.0.dev)`

int index = -1;
    int indexCount = 0;
    phoneList?.forEach((element) {
      if (element == phone) {
        index = indexCount;
        return;
      }
      indexCount++;
    });
    indexOfElementToShow = index;

that works properly
