### ISSUE TITLE
Improve the Timeline performance

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#101313]
The poor performance of the Timeline event is causing us to have to hide performance tracking tools behind flags: https://github.com/flutter/flutter/pull/100926

One issue is that `thread_info` calls from the Dart SDK are very slow on iOS ( https://github.com/dart-lang/sdk/issues/47850 ).

This issue is to track all the suggestions and attempts I've made to make things faster over the past few days, hopefully culminating in a change that speeds them up.

**Comment by gaaclarke** [comment]
For the `thread_info` issue I've suggested changing the samplerate of the call and interpolating between them.  The measurements for that are here: https://github.com/dart-lang/sdk/issues/47850#issuecomment-1087889382

The results are promising but we are also gated on the performance of the json encoding.

**Comment by gaaclarke** [comment]
One thing I discovered is that in profile builds the arguments we are sending to the Timeline event are always the same Map that are getting json encoded.  The contents are defined in `timelineArgumentsIndicatingLandmarkEvent`.  We should be able to find a way to not call json encoding on that constantly.

**Comment by gaaclarke** [comment]
I found that just caching the results of jsonArguments with the `build_bench.dart` went from `786.7 µs per iteration` to `829.0 µs per iteration`

```diff
--- a/sdk/lib/developer/timeline.dart
+++ b/sdk/lib/developer/timeline.dart
@@ -361,12 +361,19 @@ class _SyncBlock {
   }
 }
 
+String _jsonCache = '{}';
+Map? _argumentsCache;
 String _argumentsAsJson(Map? arguments) {
+  if (arguments == _argumentsCache) {
+    return _jsonCache;
+  }
   if ((arguments == null) || (arguments.length == 0)) {
     // Fast path no arguments. Avoid calling jsonEncode.
     return '{}';
   }
-  return json.encode(arguments);
+  _jsonCache = json.encode(arguments);
+  _argumentsCache = arguments;
+  return _jsonCache;
 }
```

**Comment by gaaclarke** [comment]
I tried special casing the json encoding for 1 value arguments to capture the case for most of flutter in profile builds, but it didn't make a difference:
```diff
--- a/sdk/lib/developer/timeline.dart
+++ b/sdk/lib/developer/timeline.dart
@@ -366,6 +366,14 @@ String _argumentsAsJson(Map? arguments) {
     // Fast path no arguments. Avoid calling jsonEncode.
     return '{}';
   }
+  if (arguments.length == 1) {
+    Object value = arguments.values.first!;
+    if (value is String) {
+      return '{"${arguments.keys.first}": "$value"}';
+    } else if (value is num) {
+      return '{"${arguments.keys.first}": $value}';
+    }
+  }
   return json.encode(arguments);
 }
```

**Comment by gaaclarke** [comment]
I found an old comment about how using the `{"mode": "basic"}` arguments in timeline events caused a 15% regression in performance: https://github.com/flutter/flutter/pull/12058#issuecomment-329841532

**Comment by gaaclarke** [comment]
https://dart-review.googlesource.com/c/sdk/+/240148/7/runtime/vm/os_macos.cc#111 landed which will have sped up Timeline events for iOS which was the greatest need.

**Comment by gaaclarke** [comment]
I tested the following change in Dart's timeline.dart and it results in a 16.7% increase in performance in the `build_bench.dart` benchmark with `debugProfileBuildsEnabled` turned on.

```diff
-String _argumentsAsJson(Map? arguments) {
+String _argumentsAsJson(Map? arguments, {TimelineEventMode? mode}) {
   if ((arguments == null) || (arguments.length == 0)) {
     // Fast path no arguments. Avoid calling jsonEncode.
-    return '{}';
+    if (mode == null) {
+      return '{}';
+    } else {
+      switch(mode) {
+        case TimelineEventMode.basic:
+          return '{ "mode": "basic" }';
+      }
+    }
+  }
+  if (mode != null) {
+    // TODO(gaaclarke): Move mode from outside of the `arguments` parameter into
+    // its own parameter if every call is supposed to have it.
+    // This is modifying `arguments` instead of editing a copy.
+    switch(mode) {
+      case TimelineEventMode.basic:
+        arguments['mode'] = 'basic';
+        break;
+    }    
   }
   return json.encode(arguments);
 }
```

The question I still have to figure out is if we actually even care about those parameters anymore.  The PR that brought them in says they are for "the new developer centric Timeline Dashboard page in Observatory."  That might not even be a requirement anymore. (https://github.com/flutter/flutter/pull/12058)

**Comment by goderbauer** [comment]
(Triage) @gaaclarke I assigned this to you since you seem to be actively working on this.
