### ISSUE TITLE
MaterialApp.router and friends should take a (single) RouterConfig object for ease-of-use

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#101386]
Right now, you have to pass the `routerDelegate`, `routeInformationProvider`, `routeInformationParser`, and `backButtonDispatcher` separately to `MaterialApp.router`, which makes for some awkward code for third-party routing packages that want to provide these and creates unnecessary boilerplate:

```dart
final MyThirdPartyRouter myThirdPartyRouter = MyThirdPartyRouter(...);
return MaterialApp.router(
  routerDelegate: myThirdPartyRouter.delegate,
  routeInformationProvider: myThirdPartyRouter.informationProvider,
  routeInformationParser: myThirdPartyRouter.infromationParser,
  backButtonDispatcher: myThirdPartyRouter.backButtonDispatcher,
);
```

To improve on this, we could define a `RouterConfig` mixin (or interface):

```dart
mixin RouterConfig { // or "abstract class"
  RouterDelegate get delegate;
  RouterInformationParser get informationParser;
  RouterInformationProvider get informationProvider;
  RouterBackButtonDispatcher get backButtonDispatcher;
  // TODO: figure out which of these are optional and need to be nullable.
}
```

Third-party router packages could implement that interface:

```dart
class MyThirdPartyRouter with RouterConfig {
 // ...
}
```

And `MaterialApp.router` could then take a single RouterConfig object for some much cleaner code:

```dart
return MaterialApp.router(
  routerConfig: MyThirdPartyRouter(...);
);
```

This could be added to `MaterialApp.router` in a backwards-compatible way by keeping the existing config options and adding the `routerConfig` argument as an alternative. We'd have to decide whether we want to disallow using the old API when a `routerConfig` is provided or whether we want to query the routerConfig first and - if it doesn't provide the requested value - fall back to the values from the old API.

**Comment by goderbauer** [comment]
I kinda wish we could define a factory constructor on the `RouterConfig` mixin, so you could also instantiate it directly to create a custom `RouterConfig` given a delegate, informationParser, etc. while also allowing third-party router packages to mix it into their implementation directly without messing with their inheritance hierarchy (which we'd have to do if `RouterConfig` were defined as an (abstract) class).

Unfortunately, dart doesn't allow factory constructors for mixins (yet): https://github.com/dart-lang/language/issues/1803

**Comment by johnpryan** [comment]
I really like this idea. Would it be feasible to add a RouterConfig parameter to the normal `MaterialApp` constructor too? Then maybe we could deprecate the .router constructor...

**Comment by chunhtai** [comment]
This sounds good to me, I also want to make informationParser optional, I have encounter some use case where they don't care about platform message.

**Comment by goderbauer** [comment]
> Would it be feasible to add a RouterConfig parameter to the normal MaterialApp constructor too?

We'd have to take a look what parameters on the regular MaterialApp constructor wouldn't make sense to be used in combination with the new `routerConfig` (e.g. `home`, `initialRoute`) and whether it's too confusing that those parameters are mutually exclusive...

(I believe we added the separate `.router` constructor because the list of possible arguments to MaterialApp was getting to confusing and we wanted to make it clearer what is available when you use the router-based APIs).

**Comment by goderbauer** [comment]
This is the list of parameters, that the regular `MaterialApp` constructor takes, that are unused if you want to use the Router:

```
navigatorKey
home
routes
initialRoute
onGenerateRoute
onGenerateInitialRoutes
onUnknownRoute
navigatorObservers
```

Overall, that is a pretty long list and could be confusing (e.g. why can I not use any of these routing related parameters to configure my router when I use the `routerConfig` parameter?). So, I would be leaning towards keeping the `.router` constructor as a clean interface showing clearly what functionality of `MaterialApp` is available when you use a custom Router.

@johnpryan What do you think? Would you still be in favor of deprecating `.router` altogether?

**Comment by chunhtai** [comment]
I also agree with @goderbauer , the error message when people put in the wrong parameters to original constructor is already quite hard to comprehend. It will be even worse if router api is merged into the original one. I sometimes even think we should separate them out even more, but that adds its own burden too.

**Comment by johnpryan** [comment]
These are good points, I would probably vote to keep `.router` constructor too. `MaterialApp.router(routeConfig: myRouter)` is short enough for me.
