### ISSUE TITLE
Flutter web does not rerender page on zoom in zoom out

### ISSUE THREAD

**Issue by cedvdb** [flutter/flutter#101305]
# Repro

- run any flutter app in chrome, even a new project in dartpad
- zoom out

# Result

page stays the same and just takes less percentage of the screen available

# Expected result

rerendering

**Comment by cedvdb** [comment]
> Are you using a LayoutBuilder?
> 
> https://api.flutter.dev/flutter/widgets/LayoutBuilder-class.html

So, if you go on https://dartpad.dev and create a new flutter project and resize the window, the window resize accordingly. Note that the project generated does not use `LayoutBuilder`. The same does not hold true if you use `ctrl +` or `ctrl -`

**Comment by maheshmnj** [comment]
Hi @cedvdb, Thanks for filing the issue.

There is a similar issue describing this case #77084. Please follow up there for further updates, Closing this issue as a duplicate. If you disagree feel free to write in the comments and we will reopen it.

Thank you.
