### ISSUE TITLE
[Android]AutoFill NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.util.SparseArray.get(int)' on a null object reference

### ISSUE THREAD

**Issue by lavinov-mercury** [flutter/flutter#101348]
Unfortunately, there are no steps to reproduce. Following issue was reported by Sentry as uncaught. There are several events from different users. All events happened on devices with Android 12

```
NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.util.SparseArray.get(int)' on a null object reference
    at io.flutter.plugin.editing.TextInputPlugin.autofill(TextInputPlugin.java:812)
    at io.flutter.embedding.android.FlutterView.autofill(FlutterView.java:1420)
    at android.view.autofill.AutofillManager.autofill(AutofillManager.java:2396)
    at android.view.autofill.AutofillManager.access$2700(AutofillManager.java:176)
    at android.view.autofill.AutofillManager$AutofillManagerClient.lambda$autofill$1(AutofillManager.java:3489)
...
(9 additional frame(s) were not displayed)
```

**Comment by maheshmnj** [comment]
Hi @lavinov-mercury, Thanks for filing the issue. please share the output of `flutter doctor -v` of the machine where the app was built. 
>  Following issue was reported by Sentry as uncaught.

Is this the complete error log?

**Comment by lavinov-mercury** [comment]
@maheshmnj I've found another representation of this stacktrace. Less details, but more lines
```
io.flutter.plugin.editing.TextInputPlugin in autofill at line 812
io.flutter.embedding.android.FlutterView in autofill at line 1420
android.view.autofill.AutofillManager in autofill at line 2396
android.view.autofill.AutofillManager in access$2700 at line 176
android.view.autofill.AutofillManager$AutofillManagerClient in lambda$autofill$1 at line 3489
android.view.autofill.AutofillManager$AutofillManagerClient$$ExternalSyntheticLambda9 in run at line 10
android.os.Handler in handleCallback at line 938
android.os.Handler in dispatchMessage at line 99
android.os.Looper in loopOnce at line 226
android.os.Looper in loop at line 313
android.app.ActivityThread in main at line 8646
java.lang.reflect.Method in invoke
com.android.internal.os.RuntimeInit$MethodAndArgsCaller in run at line 567
com.android.internal.os.ZygoteInit in main at line 1135
```

According to `flutter doctor -v` output, i can't provide it currently, as i haven't access to this machine, but I'll try to collect this later. All i know currently, it definitely uses flutter 2.10.4

**Comment by maheshmnj** [comment]
Thanks for the info from the stack trace the NPE seems related to AutoFill. Labeling this issue for further investigation from the team.

**Comment by jveryspace** [comment]
[✓] Flutter (Channel stable, 2.10.5, on macOS 12.0.1 21A559 darwin-x64, locale
    zh-Hans-CN)


Fatal Exception: java.lang.NullPointerException
Attempt to invoke virtual method 'java.lang.Object android.util.SparseArray.get(int)' on a null object reference
io.flutter.plugin.editing.TextInputPlugin.autofill (TextInputPlugin.java:32)
io.flutter.embedding.android.FlutterView.autofill (FlutterView.java:2)
android.view.autofill.AutofillManager.autofill (AutofillManager.java:1899)

com.android.internal.os.ZygoteInit.main (ZygoteInit.java:873)

**Comment by BenevidesLecontes** [comment]
We have like 300+ users with this issue on our production app.
