### ISSUE TITLE
How can I detect if the currently running app is a debug version?

### ISSUE THREAD

**Issue by ddxl123** [flutter/flutter#101423]
I ran my app with a virtual machine in the project, and the running app was generated by `build\outputflutter-apk\app-debug.apk`.

When the command line is executed and packaged into apk, `app-release.apk` will be generated for users to install and use.

I want to be able to detect whether the currently executing application is `app-debug` or `app-release` in the application, 
how can I do that?

**Comment by julianbraasch** [comment]
There is the ```kDebugMode``` constant in ```package:flutter/foundation.dart``` which does exactly that.

**Comment by darshankawar** [comment]
@ddxl123 
I believe above comment should help you to answer your question. For further details, you can ask the same on support channels like StackOverflow. Closing from here.
