### ISSUE TITLE
Clean up flutter/flutter.py recipes for old SDK sharded tests

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#101404]
We have migrated consolidated builders with shards to separate sub-shard builders (context: go/flutter-migrate-subshard), and it is no longer needed to trigger sub-shards from futter/flutter.py.

We need a clean up to remove this legacy logic: https://flutter.googlesource.com/recipes/+/refs/heads/main/recipes/flutter/flutter.py#34

**Comment by muditatandon** [comment]
CL: https://flutter-review.googlesource.com/c/recipes/+/29480
The old shard logic and tests have been deleted.
