### ISSUE TITLE
Breakpoints are not working in newer Chrome Version - 100.0.4896.75

### ISSUE THREAD

**Issue by idrish-sorathiya** [flutter/flutter#101403]
After automatic upgrade of Chrome version to 100.0.4896.75, breakpoints are stopped working. I believe internally framework crashing at somewhere. 

## Steps to Reproduce

1. Set breakpoints and run application. 
2. Your breakpoint will never hit

**Expected results:** 
Breakpoints should work.

**Actual results:** 
Breakpoints are not hitting. 

<details>
<summary>Code sample</summary>

Application is pausing inside internal framework. Check attached screenshot and log inside that screenshot.
<img width="1437" alt="Screenshot 2022-04-06 at 9 36 16 AM" src="https://user-images.githubusercontent.com/79035059/161893838-370dfb15-ec33-427c-8dbb-7d0fd61889f9.png">

</details>

<details>
  <summary>Logs</summary>

```
packages/mutu/common/model/notification/message_notification_data.dart
[   +1 ms] MetadataProvider: Loaded debug metadata for module: packages/mutu/common/model/notification/info_notification_data.dart
[        ] MetadataProvider: Loaded debug metadata (no sound null safety)
[  +85 ms] DwdsInjector: Injected debugging metadata for entrypoint at http://localhost:49505/main_module.bootstrap.js
[+19159 ms] ChromeProxyService: Initializing expression compiler for main_module.bootstrap.js with sound null safety: false
[ +303 ms] DevHandler: Debug service listening on ws://127.0.0.1:52952/NgaB2SulXxo=/ws
[  +41 ms] This app is linked to the debug service: ws://127.0.0.1:52952/NgaB2SulXxo=/ws
[  +12 ms] Debug service listening on ws://127.0.0.1:52952/NgaB2SulXxo=/ws
[        ] Running with unsound null safety
[        ] For more information see https://dart.dev/null-safety/unsound-null-safety
Connecting to VM Service at ws://127.0.0.1:52952/NgaB2SulXxo=/ws
[ +361 ms] DevHandler: VmService proxy responded with an error:
           {jsonrpc: 2.0, id: 18, error: {code: -32601, message: setLibraryDebuggable: Not supported on web devices}}

```
Logs are tool long and not allowing here as a part of comment. Attaching file with full logs.
[VerboseLogs.txt](https://github.com/flutter/flutter/files/8423568/VerboseLogs.txt)

```
Idrishsorathiya@RSPLMAC052 Utilities % flutter doctor -v
[✓] Flutter (Channel stable, 2.10.4, on macOS 12.2.1 21D62 darwin-x64, locale en-IN)
    • Flutter version 2.10.4 at /Users/Idrishsorathiya/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (12 days ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/Idrishsorathiya/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio 2.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.66.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 100.0.4896.75

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

I am using VSCode for my development but I tried in Android Studio as well. Both are behaving same.

**Comment by pselvaraj-uas** [comment]
Same thing was happening from the last release I guess. This is a Blocker instead of an issue!, Intelli J same issue!!!!! Android Studio will test. ARGHHHH. This needs to be done ASAP.

**Comment by idrish-sorathiya** [comment]
As a temporary workaround I have downgraded chrome and it is working for me but it is inconvenient and tricky to stop upgrade of Chrome.

**Comment by detroxx92** [comment]
Same thing here.
I checked different approaches to fix this by using Flutter & Dart pre-Release version of the VS-Code extensions.
Neither of these fixes it. It is also independend of the used flutter version (2.10.4 / 2.10.3).

Only possible fix is to downgrade Chrome. ( Note here: Reinstallation of chrome + removing chrome profile will also not fix this bug). Edge is also not working

**Comment by desmond206x** [comment]
Version 99.0.4844.84 of Chrome is working without problems. We also downgraded to it.

**Comment by tilmanbeyyer** [comment]
Took the same approach as detroxx92. I am using Mac and also downgraded to a version below 100.

**Comment by maheshmnj** [comment]
Hi @idrish-sorathiya, Thanks for filing the issue. 

This is a known issue and is being tracked here https://github.com/flutter/flutter/issues/101224, Please follow up there for further updates, Closing this issue as a duplicate. If you disagree feel free to write in the comments and we will reopen it.

Thank you.
