### ISSUE TITLE
Firebase Messaging is not working with device_info_plus

### ISSUE THREAD

**Issue by resatkrlc** [flutter/flutter#101462]
<details>
<summary>
When i try to use firebase_messaging, then it gives that error:

( So, because watkit depends on both device_info_plus ^3.2.2 and firebase_messaging ^8.0.0-dev.14, version solving failed.)</summary>

How to fix that? Waiting for answers. Thanks

```dart
```

</details>

<details>
  <summary> Because firebase_messaging >=8.0.0-dev.14 <9.0.0-1.0.nullsafety.0 depends on firebase_messaging_platform_interface ^1.0.0-dev.10 and no versions of firebase_messaging_platform_interface match >1.0.0-dev.10 <2.0.0, firebase_messaging >=8.0.0-dev.14 <9.0.0-1.0.nullsafety.0 requires firebase_messaging_platform_interface 1.0.0-dev.10.
And because firebase_messaging_platform_interface 1.0.0-dev.10 depends on plugin_platform_interface ^1.0.0, firebase_messaging >=8.0.0-dev.14 <9.0.0-1.0.nullsafety.0 requires plugin_platform_interface ^1.0.0.
And because device_info_plus >=3.2.0 depends on device_info_plus_platform_interface ^2.3.0 which depends on plugin_platform_interface ^2.0.0, firebase_messaging >=8.0.0-dev.14 <9.0.0-1.0.nullsafety.0 is incompatible with device_info_plus >=3.2.0.
So, because watkit depends on both device_info_plus ^3.2.2 and firebase_messaging ^8.0.0-dev.14, version solving failed.
pub get failed (1; So, because watkit depends on both device_info_plus ^3.2.2 and firebase_messaging ^8.0.0-dev.14, version solving failed.)</summary>

**Comment by stuartmorgan** [comment]
Issues with third-party packages need to be reported to the developers of those packages.

Although in this case, it looks like the problem is just that you are using an old version of `firebase_messaging`.
