### ISSUE TITLE
Support JUnit tests for plugins in flutter/plugins

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#10140]
We really should be writing and requiring unit tests of our plugins.  We had our first "external" (Googler, not on Flutter team) contribution yesterday, and it yielded the comment "We have no tests for this code so please review carefully."

FYI @collinjackson @mravn-google @szakarias

**Comment by tvolkert** [comment]
Also filed https://github.com/flutter/flutter/issues/10141 for the ObjC equivalent

**Comment by kf6gpe** [comment]
I'm closing this based on all of the testability @collinjackson & co have done this year towards testability; it's obsolete at this point.
