### ISSUE TITLE
enable coverage collection for nested packages in a monorepo

### ISSUE THREAD

**Issue by uditrugman** [flutter/flutter#101486]
## Use case

I have a monorepo with several flutter / dart packages.

some of the tests are written in a client package as that helps to test more use cases.

the problem is that when running tests in a client package, code coverage does not collect code that runs in nested packages.

i could for example write additional tests in nested packages and merge their coverage into a single report. but running tests in a nested package does not always give enough context for the test. 

consider an app with two packages: app1, app2, flutter_commons

now some of the tests in app1 use (indirectly) code that is located in "flutter_commons". but, when running with --coverage, that code is not covered and therefore is considered as not used.

the ability to collect code from flutter_commons when running tests in app1 would help...

## Proposal

it should be possible to specify in the command line which nested packages should be collected.

thanks

**Comment by darshankawar** [comment]
> now some of the tests in app1 use (indirectly) code that is located in "flutter_commons". but, when running with --coverage, that code is not covered and therefore is considered as not used.

This seems to be related to `--coverage` flag which comes from dart package and maintained in dedicated repo: https://github.com/dart-lang/coverage/issues. I suggest you to file this issue there. 

Or are you looking to add a flag / paramter to `flutter test` command to include nested packages ?

**Comment by darshankawar** [comment]
Thanks for the update. Labeling this as a proposal.
