### ISSUE TITLE
[Question] How to access data coming from WES in Flutter Web?

### ISSUE THREAD

**Issue by cdprete** [flutter/flutter#101452]
Hi.
I've a maybe stupid question, but I wasn't able to find any documentation for it.

I've a Web Entry Server in which the users login and, after that, they get a page where they can decide which application to open (in a new tab).
When one of such application is opened, the WES sends to it some headers.
Assuming that the `index.html` from a Flutter Web project is launched, how can the Flutter Web app access those?

Kind regards and thanks for the reply :)

**Comment by darshankawar** [comment]
@cdprete 
I don't think you would get any documentation around it atleast on Flutter official documentation because it may be external to the scope of Flutter web development. I suggest you to ask this question on support channels like StackOverflow or reddit.
Closing from here for now.
