### ISSUE TITLE
Catching all exceptions to avoid app crash

### ISSUE THREAD

**Issue by Solido** [flutter/flutter#10145]
## Steps to Reproduce

Some parts of the framework seems to throw exceptions that we can't catch resulting in the application crash.

My personal experience is trying to parse a Json response instead of the body of it and having all my application to crash. It bypass try catch and even FlutterError.onError = (FlutterErrorDetails details) ...

No exceptions, no stack trace, just 'connection to device lost' and application exit.

I'd like more documentation on how to handle those case locally and a global catch somewhere to be sure my app doesn't crash on case that I can not handle.

Thank you !

**Comment by eseidelGoogle** [comment]
Is there any example code you can share?

**Comment by Solido** [comment]
```dart// Method called by factory
_preloadVotes() async {
      var jsonCategories = await get('vote/categories');
// jsonCategories is not json but response, .length doesn't exist -> FlutterError.onError catch nothing, app crash
      print("Loaded ${jsonCategories.length} categories");
  }
```

Been updated flutter to master from alpha yesterday and today I can locally catch the error with try catch, I lost some hours on it yesterday because debug show me it bypassed. But I'll be glad to catch any non locally catch exceptions with onError.

**Comment by Hixie** [comment]
You can use Zones to catch exceptions that are thrown when your code isn't on the stack, and that aren't caught by FlutterError.onError. We should add some links from onError's documentation to the Zone API docs.

**Comment by eseidelGoogle** [comment]
https://github.com/yjbanov/crashy is an example of doing crash reporting in a Flutter app.   Looks like it also uses zones, if that's helpful.
