### ISSUE TITLE
`flutter drive --help` does not have all valid parameters

### ISSUE THREAD

**Issue by cedvdb** [flutter/flutter#101454]
- --no-headless is missing
- is there a parameter for the port when running web server ?

**Comment by maheshmnj** [comment]
Hi @cedvdb, Thanks for filing the issue. 

>
>--[no-]headless                               Whether the driver browser is going to be launched in headless mode.
                                                  (defaults to on)

fluter drive does support `--headless` and `--no-headless` as I can see from the docs 

> is there a parameter for the port when running web server ?

Can you please try `flutter run -d web-server --web-port <PORT>`

**Comment by cedvdb** [comment]
> > --[no-]headless                               Whether the driver browser is going to be launched in headless mode.
> > (defaults to on)

Okay there is something wrong here, maybe it's on my end. This appears when I use `CMD` but not in git bash. It appears in git bash when I grep it. Do you have git bash for windows ? If so could you please see if `flutter driver --help` does render the --no-headless (do not grep as grep works for me too even with bash). 

It could be on my end.

**Comment by cedvdb** [comment]
> fluter drive does support `--headless` and `--no-headless` as I can see from the docs

There is something wrong. Maybe it's on my end. After reading this I tried again and could not see it. However grepping it I could see it in the grep output. However it was not appearing in the normal output (I quadruple checked), organizing the params by alphabetical order might help too.

I could not manage to reproduce and I'm a bit perplexed. I suspect the problem is on my end as I've add some weird console outputs lately when scrolling up in vs code.

as for `web-port` it works.

**Comment by cedvdb** [comment]
I will close this but I might reopen if I manage to find a repro and if I'm sure the problem is not on my end.
