### ISSUE TITLE
[android] Possible race condition in reporting device physical size in profile/release mode 

### ISSUE THREAD

**Issue by hackware1993** [flutter/flutter#101478]
```dart
void main() {
  print('physicWidth = ${window.physicalSize.width} debugMode = $kDebugMode');
  runApp(const MyApp());
}
```

#### logs
```
2022-04-07 14:05:52.421 24319-24374/? I/flutter: physicWidth = 1080.0 debugMode = true
2022-04-07 14:06:43.139 24651-24688/? I/flutter: physicWidth = 0.0 debugMode = false
```

My flutter version is 2.10.4，I remember the last version was correct。

My environment is Android 10.

**Comment by hackware1993** [comment]
The sizes of all elements on my interface are dynamically calculated according to the device width, and now I can't get the device width, so everything on the interface can't be displayed. It works fine in debug mode, but not in release mode

**Comment by hackware1993** [comment]
This is a very serious problem, all elements of the interface cannot be displayed!

**Comment by hackware1993** [comment]
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.10.4, on Microsoft Windows [Version 10.0.19044.1620], locale zh-CN)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.1.0)
[√] Android Studio (version 2021.1)
[√] IntelliJ IDEA Ultimate Edition (version 2021.3)
[√] Connected device (4 available)
[!] HTTP Host Availability
    X HTTP host https://maven.google.com/ is not reachable. Reason: An error occurred while checking the HTTP host: 信号灯超时时间已到


! Doctor found issues in 1 category.

**Comment by zanderso** [comment]
This is not the correct way to query the size. If you look at the `MediaQuery` API, it will point you in the right direction.

**Comment by hackware1993** [comment]
> This is not the correct way to query the size. If you look at the `MediaQuery` API, it will point you in the right direction.

Why do debug and release behave differently?  MediaQuery also calls window.physicalSize, which is also unavailable

**Comment by hackware1993** [comment]
> This is not the correct way to query the size. If you look at the `MediaQuery` API, it will point you in the right direction.

On mobile, the physical width of the screen is constant, so I wouldn't use MediaQuery.  I'm using minimum screen width fit now.
