### ISSUE TITLE
Execution failed for task ':app:validateSigningRelease'.

### ISSUE THREAD

**Issue by satyabratanayak** [flutter/flutter#101466]
satyabratanayak@Satyabratas-MacBook-Air New-Look-salon-Analytics % flutter build appbundle

💪 Building with sound null safety 💪

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:validateSigningRelease'.
> Keystore file '/android/app/upload-keystore.jks' not found for signing config 'release'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 8s
Running Gradle task 'bundleRelease'...                              9.2s
Gradle task bundleRelease failed with exit code 1
satyabratanayak@Satyabratas-MacBook-Air New-Look-salon-Analytics % 

What should i do ... i check all over internet try all ... check my typo but nothing there to solve please help me with this 

key.properties
storePassword=theNewLookPassword
keyPassword=theNewLookPassword
keyAlias=upload
storeFile=/android/app/upload-keystore.jks

also tried - 
storeFile=android/app/upload-keystore.jks
storeFile=../app/upload-keystore.jks
storeFile=app/upload-keystore.jks
storeFile=/app/upload-keystore.jks

Also full path to the keystore.jks

/// In my bundle file 

def keystoreProperties = new Properties()
def keystorePropertiesFile = rootProject.file('key.properties')
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}

android {
    compileSdkVersion flutter.compileSdkVersion

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.blackminystudio.newlook"
        minSdkVersion 21
        targetSdkVersion 31
        multiDexEnabled true
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }

   signingConfigs {
       release {
           keyAlias keystoreProperties['keyAlias']
           keyPassword keystoreProperties['keyPassword']
           storeFile keystoreProperties['storeFile'] ? file(keystoreProperties['storeFile']) : null
           storePassword keystoreProperties['storePassword']
       }
   }
   buildTypes {
       release {
           signingConfig signingConfigs.release
       }
   }

}

**Comment by darshankawar** [comment]
@satyabratanayak 
Check if you have mis-spelled or mis-placed keystore file. 
Also your question is better suited for support channels like StackOverflow, so closing from here.
