### ISSUE TITLE
Fuchsia CQ for `flutter/flutter` changes

### ISSUE THREAD

**Issue by akbiggs** [flutter/flutter#101420]
We recently had a [breaking change](https://github.com/flutter/flutter/pull/100990) to Flutter on Fuchsia get into google3 (app crashes on startup) because we don't have tests for Flutter on Fuchsia in `flutter/flutter`, only in `flutter/engine`. I would like to have a Fuchsia builder running Flutter tests for `flutter/flutter` changes similar to what's done with Linux Fuchsia FEMU for `flutter/engine` today: https://ci.chromium.org/p/flutter/builders/prod/Linux%20Fuchsia%20FEMU

We just need a test running on `flutter/flutter` changes that starts up an app and renders a frame on Fuchsia to catch breakages like these.

**Comment by godofredoc** [comment]
There is some [previous work](https://cs.opensource.google/flutter/recipes/+/main:recipe_modules/fuchsia_util/api.py) in this area although it was never completed and it was targeting physical devices.

You may want to adapt [fuchsia_util](https://cs.opensource.google/flutter/recipes/+/main:recipe_modules/fuchsia_util/api.py) to spin up and emulator and use the flutter tool with [one of devicelab](https://cs.opensource.google/flutter/flutter/+/master:dev/devicelab/bin/tasks/) tests.

The [runner](https://cs.opensource.google/flutter/flutter/+/master:dev/devicelab/bin/run.dart) is used from this [recipe](https://cs.opensource.google/flutter/recipes/+/main:recipes/devicelab/devicelab_drone.py).

Example tasks are:

* https://ci.chromium.org/p/flutter/builders/prod/Linux_android%20fast_scroll_heavy_gridview__memory/2327
* https://ci.chromium.org/p/flutter/builders/prod/Linux_android%20fast_scroll_large_images__memory/1086

You can also sign up for infra office hours: [go/flutter-infra-office-hours](https://goto.google.com/flutter-infra-office-hours)

**Comment by akbiggs** [comment]
@godofredoc Do you have a pointer to how our existing `flutter/engine` builders works? Since they run on emulator they would be good for me to reference.

**Comment by godofredoc** [comment]
[femu_test recipe](https://cs.opensource.google/flutter/recipes/+/main:recipes/engine/femu_test.py) builds the fuchsia engine artifacts and uses [flutter/vdl](https://cs.opensource.google/flutter/recipes/+/main:recipe_modules/vdl/api.py) to download and run femu.

Testing on flutter/flutter will be different though as there is no need to build fuchsia `flutter precache --fuchsia` will download the fuchsia engine artifacts associated with that commit of the framework.

Most of what is required is already there as long as we can spin up the emulator and make `flutter devices` to identify it the devicelab runner should take care of building the application, running the test and reporting the results.

Some changes may be required in the runner, as far as I remember the problem with running the tests with physical devices is that the runner didn't have a way to identify a single devices from the many devices discovered by `flutter devices`.

To validate the workflow in your desktop you can:

* Spin up FEMU
* checkout flutter/flutter.
* run`flutter precache --fuchsia`
* ensure the device is discovered by `flutter devices`
* run the test using https://github.com/flutter/flutter/wiki/Running-and-writing-tests#running-device-lab-tests-locally

Once the steps above work then adding the tests will be just a matter of translating the steps to recipes.

**Comment by akbiggs** [comment]
Going to sign up for office hours, I think I'm a bit confused about how `devicelab` tests work.

- Does `dev/devicelab` really use `flutter devices`? It looks like there is separate device discovery logic under the devicelab folder.
- https://github.com/flutter/flutter/wiki/Running-and-writing-tests#running-device-lab-tests-locally mentions `dev/devicelab/manifest.yaml` but that doesn't exist.

**Comment by akbiggs** [comment]
From office hours:

- `dev/devicelab` might use `flutter devices` under the hood but it needs investigation.
- `flutter devices` previously used to work with physical devices but currently doesn't find the emulator.
- `.ci.yaml` is where the tasks are defined, `manifest.yaml` doesn't exist anymore and the documentation should be updated.
- @keyonghan You can follow https://fuchsia.dev/fuchsia-src/get-started/sdk#start-the-emulator to `3. Start the emulator` to start a Fuchsia emulator with a prebuilt image. It currently requires a Linux machine.

**Comment by akbiggs** [comment]
With some updates to the documentation I was able to start running devicelab tests locally, e.g. `../../bin/dart bin/run.dart -t analyzer_benchmark`

I *think* `flutter precache --fuchsia` might be broken, it doesn't seem to be fetching and downloading Fuchsia artifacts. At the end of this command it seems to think that neither flutter runner stuff nor fuchsia stuff is required:

```sh
akbiggs@akbiggs ~/flutter/bin/cache/artifacts
 % flutter precache --flutter_runner --fuchsia -v
[  +93 ms] executing: uname -m
[  +45 ms] Exit code 0 from: uname -m
[        ] x86_64
[   +8 ms] executing:
[/usr/local/google/home/akbiggs/Downloads/flutter/] git
-c log.showSignature=false log -n 1 --pretty=format:%H
[  +17 ms] Exit code 0 from: git -c
log.showSignature=false log -n 1 --pretty=format:%H
[        ] c860cba910319332564e1e9d470a17074c1f2dfd
[        ] executing:
[/usr/local/google/home/akbiggs/Downloads/flutter/] git
tag --points-at
c860cba910319332564e1e9d470a17074c1f2dfd
[  +20 ms] Exit code 0 from: git tag --points-at
c860cba910319332564e1e9d470a17074c1f2dfd
[        ] 2.10.4
[  +10 ms] executing:
[/usr/local/google/home/akbiggs/Downloads/flutter/] git
rev-parse --abbrev-ref --symbolic @{u}
[  +11 ms] Exit code 0 from: git rev-parse --abbrev-ref
--symbolic @{u}
[        ] origin/stable
[        ] executing:
[/usr/local/google/home/akbiggs/Downloads/flutter/] git
ls-remote --get-url origin
[  +10 ms] Exit code 0 from: git ls-remote --get-url
origin
[        ] https://github.com/flutter/flutter.git
[ +114 ms] Unable to locate an Android SDK.
[   +6 ms] executing:
[/usr/local/google/home/akbiggs/Downloads/flutter/] git
rev-parse --abbrev-ref HEAD
[  +11 ms] Exit code 0 from: git rev-parse --abbrev-ref
HEAD
[        ] stable
[ +162 ms] Artifact Instance of
'AndroidGenSnapshotArtifacts' is not required, skipping
update.
[        ] Artifact Instance of
'AndroidInternalBuildArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is
not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not
required, skipping update.
[   +1 ms] Artifact Instance of
'WindowsEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of
'WindowsUwpEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'MacOSEngineArtifacts'
is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts'
is not required, skipping update.
[        ] Artifact Instance of
'LinuxFuchsiaSDKArtifacts' is not required, skipping
update.
[        ] Artifact Instance of
'MacOSFuchsiaSDKArtifacts' is not required, skipping
update.
[        ] Artifact Instance of
'FlutterRunnerSDKArtifacts' is not required, skipping
update.
[        ] Artifact Instance of
'FlutterRunnerDebugSymbols' is not required, skipping
update.
[  +61 ms] "flutter precache" took 179ms.
[ +113 ms] ensureAnalyticsSent: 105ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 0

**Comment by akbiggs** [comment]
I had to do `flutter config --enable-fuchsia` first. After that `flutter precache --fuchsia` grabs the Fuchsia SDK with `ffx`.

**Comment by keyonghan** [comment]
Validated existing device discovery works for the fuchsia. Steps to validate:

Create a sample test script under `dev/devicelab/bin/tasks/sample.dart`
```
void main() async {
  deviceOperatingSystem = DeviceOperatingSystem.fuchsia;
  final Device device = await devices.workingDevice;
  print(device.deviceId);
}
```
Start the emulator:
```
ffx emu start --headless --name test workstation.qemu-x64
```
Run the test, and here is the output:
```
dart bin/tasks/sample.dart
Executing "/usr/local/google/home/keyonghan/Documents/work/flutter/bin/cache/artifacts/fuchsia/tools/x64/ffx target list --format s" in "/usr/local/google/home/keyonghan/Documents/work/flutter/dev/devicelab" with environment {BOT: true, LANG: en_US.UTF-8}
stdout: 127.0.0.1 test
Device chosen: device: test
test
```

**Comment by godofredoc** [comment]
Obsolete
