### ISSUE TITLE
`AppBar` with reversed scrollable doesn't properly indicate `scrolledUnder` state

### ISSUE THREAD

**Issue by guidezpl** [flutter/flutter#101416]
When `AppBar` overlaps a reversed scrollable, it incorrectly reports the initial state as not being scrolled under.

Repro:

```dart
import 'dart:math';

import 'package:flutter/material.dart';

void main() => runApp(const ScrolledUnder());

class ScrolledUnder extends StatelessWidget {
  const ScrolledUnder({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        appBar: AppBar(
          backgroundColor: MaterialStateColor.resolveWith((states) {
            if (states.contains(MaterialState.scrolledUnder)) {
              return Colors.red;
            }
            return Colors.blue;
          }),
          title: Text('reverse scrolled under'),
        ),
        body: ListView.builder(
          itemBuilder: (context, index) => Container(
            height: 200,
            color: Color((Random().nextDouble() * 0xFFFFFF).toInt())
                .withOpacity(1.0),
          ),
          reverse: true,
        ),
      ),
    );
  }
}
```

@Piinks would love your input, clues for how to fix this

Internal issue: b/226060628

**Comment by guidezpl** [comment]
Right, that's the issue at hand. When `reverse` is true, the content is beneath the app bar, but the app bar isn't considered scrolled under

**Comment by Piinks** [comment]
I am not familiar with this, I think @HansMuller implemented it. I am guessing the scrolled under state is dependent on the scroll position, or something similar.

When `reverse: false`, and the scroll position is 0, nothing is 'scrolled under'.

When `reverse: true`, and the scroll position is 0, there _could_ be content under the app bar, if the content is long enough to have passed under the app bar. Still only guessing, but it is likely we are assuming a 0 scroll position means nothing is under the app bar. I'll check and see, if so it my be an easy fix.

**Comment by Piinks** [comment]
#80395 introduced this for reference. It may be a bit trickier as the current functionality uses a ScrollNotification. That means the information would not bubble up until someone scrolled. Changing it to a ScrollMetricsNotification is probably the best way to fix it. That way the initial scroll metrics information is available right away before scrolling occurs.

**Comment by Piinks** [comment]
I have a proposed fix for this in https://github.com/flutter/flutter/pull/101460

**Comment by guidezpl** [comment]
Awesome, thanks :)

**Comment by Piinks** [comment]
Reopening since this change was reverted, hoping to re-land it right away, there is an edge case that is not super clear yet.
