### ISSUE TITLE
Add option to create plugin with Swift

### ISSUE THREAD

**Issue by Gustash** [flutter/flutter#10143]
Currently `flutter create --plugin example_plugin` creates a skeleton for a plugin with Obj-C for iOS. There should be an option to start the plugin directory with Swift instead of Obj-C.

**Comment by eseidelGoogle** [comment]
I think this is a dupe of https://github.com/flutter/flutter/issues/7312?

**Comment by Gustash** [comment]
Whoops, I looked but didn't find that one. Sorry. Yes, it is a dupe. Thank you
