### ISSUE TITLE
[Web] some characters are missing from text

### ISSUE THREAD

**Issue by ArpanaSwarnkar** [flutter/flutter#101411]
Hi, when i run the code without any renderer some characters are missing from text but Hindi text comes right:
![WhatsApp Image 2022-04-06 at 13 21 13](https://user-images.githubusercontent.com/17845189/161924574-4a1dedf2-046d-49f5-b82a-bf184ba87a69.jpeg)
![WhatsApp Image 2022-04-06 at 13 21 59](https://user-images.githubusercontent.com/17845189/161924579-be813135-9c08-48ca-bdb7-0132722c34e3.jpeg)
![WhatsApp Image 2022-04-06 at 13 22 43](https://user-images.githubusercontent.com/17845189/161924580-270707f8-51b2-4a0a-ab42-2f0df2957a1d.jpeg)

Nut when i run code with html renderer no missing charcters but hindi text don't come right:
![WhatsApp Image 2022-04-06 at 13 23 10](https://user-images.githubusercontent.com/17845189/161924768-75a2a105-6c80-4c47-a2aa-94146eb06206.jpeg)
![WhatsApp Image 2022-04-06 at 13 23 52](https://user-images.githubusercontent.com/17845189/161924781-9296d5da-cb36-4662-bf93-b736d14e2142.jpeg)

Output of flutter docter -v
[√] Flutter (Channel beta, 2.5.0, on Microsoft Windows [Version 10.0.19042.1586], locale en-IN)
    • Flutter version 2.5.0 at F:\src\flutter_windows_2.5.0-beta\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cc385b4b8 (7 months ago), 2021-09-07 23:01:49 -0700
    • Engine revision f0826da7ef
    • Dart version 2.14.0

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\lenovo\AppData\Local\Android\sdk
    • Platform android-31, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 99.0.4844.84
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 97.0.1072.55

• No issues found!

**Comment by maheshmnj** [comment]
Hi @ArpanaSwarnkar, Thanks for filing the issue.  Are you using any custom font?  Can you check if this issue is related to any specific font?  Also, You seem to be using an older version of flutter. Please try to upgrade to the latest stable version using `flutter upgrade`, If the issue persists then please write back with a minimal and complete code sample.

**Comment by maheshmnj** [comment]
Thanks for the update, Please share a [minimal and complete reproducible code](https://stackoverflow.com/help/minimal-reproducible-example) to investigate further.
