### ISSUE TITLE
[Android][Flutter Engine Group]FlutterJNI.nativeSpawn() appears ANR when a new engine is created using the FlutterEngineGroup

### ISSUE THREAD

**Issue by JunhuaLin** [flutter/flutter#101485]
## Details

FlutterJNI.nativeSpawn() appears ANR when a new engine is created using the FlutterEngineGroup

**Target Platform:** android 10
**Flutter version**  2.5.3

## Logs

```
erorr logs:
1. io.flutter.embedding.engine.FlutterJNI.nativeSpawn(Native Method)    <----- ANR
2. io.flutter.embedding.engine.FlutterJNI.spawn(SourceFile:4)
3. io.flutter.embedding.engine.b.x(SourceFile:3)
4. io.flutter.embedding.engine.e.b(SourceFile:5)
5. io.flutter.embedding.engine.e.a(SourceFile:1)

timeline:
activity.onCreate()
      |
      |   FlutterJNI.nativeSpawn(Native Method)    <----- ANR
      |
activety.onStart()

```

Last login: Thu Apr  7 15:21:29 on ttys002
➜  ~ flutter doctor -v

```

[✓] Flutter (Channel stable, 2.5.3, on macOS 11.6 20G165 darwin-x64, locale
    zh-Hans-CN)
    • Flutter version 2.5.3 at /Library/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (6 months ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/junhualin/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS
      development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] Connected device (2 available)
    • ANA AN00 (mobile) • KXU0221629000993 • android-arm64  • Android 10 (API
      29)
    • Chrome (web)      • chrome           • web-javascript • Google Chrome
      96.0.4664.55

! Doctor found issues in 1 category.

</details>

```

**Comment by darshankawar** [comment]
> **Flutter version** 2.5.3

@JunhuaLin 
Can you try to upgrade to latest stable (2.10.4) and see if the behavior still persists on it ?

**Comment by JunhuaLin** [comment]
The upgrade of FLUTTER will cause the upgrade of some base libraries and tripartite libraries in my project, so it cannot be upgraded for now

Have you ever had a problem with that? How to solve

**Comment by darshankawar** [comment]
@JunhuaLin 
Please provide [complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) along with steps to replicate the behavior you are reporting.
Thanks.

**Comment by JunhuaLin** [comment]
Low probability problems on the line. cannot replicate in demo

**Comment by JunhuaLin** [comment]
Multiple engines are used here. ANR occurs when the second engine is created

**Comment by darshankawar** [comment]
There's not enough details for us to work with. Please provide the complete error log that can help us to debug this further.

**Comment by miroliao** [comment]
> > **Flutter version** 2.5.3
> 
> @JunhuaLin Can you try to upgrade to latest stable (2.10.4) and see if the behavior still persists on it ?
2.10.4 still ANR。use Multiple engines, ANR when the second engine create
------------------------------------------------
1 : ANR_EXCEPTION: ANR Input dispatching timed out (Waiting because the touched window's input channel is full. Outbound queue length: 1. Wait queue length: 52.)
2 : io.flutter.embedding.engine.FlutterJNI.io.flutter.embedding.engine.FlutterJNI nativeSpawn(long,java.lang.String,java.lang.String,java.lang.String,java.util.List)(FlutterJNI.java)
3 : io.flutter.embedding.engine.FlutterJNI.spawn()
4 : io.flutter.embedding.engine.FlutterEngine.spawn()
5 : io.flutter.embedding.engine.FlutterEngineGroup.createAndRunEngine()
6 : io.flutter.embedding.engine.FlutterEngineGroup.createAndRunEngine()
7 : io.flutter.embedding.engine.FlutterEngineGroup.createAndRunEngine()
8 : io.flutter.embedding.engine.FlutterEngineGroup.createAndRunDefaultEngine()

**Comment by miroliao** [comment]
90% happened in Android 9 Device

**Comment by darshankawar** [comment]
What's the verdict here ? Is there a way to replicate and provide code sample that shows this behavior ?
