### ISSUE TITLE
PointerDeviceType Stylus instead of Mouse in Listener Widget's onPointerDown/Up/Move on Ubuntu

### ISSUE THREAD

**Issue by dssimonspoerri** [flutter/flutter#101408]
## Steps to Reproduce

Open https://dartpad.dev/?id=72db351a4c0f4c64f2c2b1af38643067 on Ubuntu Chrome. This is the counter example where the Scaffold is wrapped in a Listener Widget that prints the PointerDeviceKind of the PointerDownEvent to the console. 

**Expected results:** Should Print PointerDeviceKind.mouse

**Actual results:** Does Print PointerDeviceKind.stylus

<details>
<summary>Code sample</summary>

https://dartpad.dev/?id=72db351a4c0f4c64f2c2b1af38643067

![image](https://user-images.githubusercontent.com/100567198/161917130-4c0030ed-1d37-426a-9293-ad215b0e756a.png)

</details>

**Comment by dssimonspoerri** [comment]
Seems to be an upstream issue in chrome actually. `document.addEventListener('pointerdown', e => console.log(e.pointerType))` yields 'pen' upon mouse clicking on my Ubuntu Chrome.

**Comment by nullrocket** [comment]
I believe this is related to this issue https://github.com/flutter/flutter/issues/96197#issuecomment-1100643249.  Are you by chance running Ubuntu in a Vmware guest?

**Comment by yjbanov** [comment]
I'm unable to reproduce this in Chrome on Linux. Could it be, as @nullrocket is suggesting, that this is related to a specific environment configuration?

**Comment by dssimonspoerri** [comment]
Yes, I only tested on virtualized Linux. I guess this is a duplicate of #96197 and actually a chromium issue.
