### ISSUE TITLE
Update `DatePicker` to support Material 3 

### ISSUE THREAD

**Issue by TahaTesser** [flutter/flutter#101481]
https://m3.material.io/components/dialogs/guidelines#754102ae-39d7-47bb-9694-d1ef192beffc

| Preview | 
| --------------- | 
| <img src="https://user-images.githubusercontent.com/48603081/162135827-86ef471a-8784-458c-901a-a6beafbe1f79.png" height="450" />	|

Specs: https://m3.material.io/components/date-pickers/overview

**Comment by TahaTesser** [comment]
cc: @guidezpl @darrenaustin 

Can you please add this to https://github.com/flutter/flutter/issues/91605?

**Comment by guidezpl** [comment]
Done for both, though we'll wait for spec to come out for these

**Comment by TahaTesser** [comment]
> Done for both, though we'll wait for spec to come out for these

Thanks! I had migrated `TimePicker` by matching native specs but if we need to wait for official specs it sounds good to me.

**Comment by TahaTesser** [comment]
https://github.com/flutter/flutter/pull/93981 needs to land for this issue.

**Comment by darrenaustin** [comment]
> #93981 needs to land for this issue.

I think it would be better to wait for the spec to make sure whatever we choose to provide in the theme matches what we need for M3. Otherwise we risk creating properties that we have to deprecate or rename to match possibly match the spec. That said, we could use that as the basis for a date picker theme that can go in with the M3 data picker.

**Comment by TahaTesser** [comment]
> I think it would be better to wait for the spec to make sure whatever we choose to provide in the theme matches what we need for M3. Otherwise we risk creating properties that we have to deprecate or rename to match possibly match the spec. That said, we could use that as the basis for a date picker theme that can go in with the M3 data picker.

Totally agree!

**Comment by TahaTesser** [comment]
https://m3.material.io/components/date-pickers/overview is available, I'm so excited, been waiting for this :)

**Comment by darrenaustin** [comment]
We should use this issue to track just adding a theme for the existing Date Picker and migrating it to M3. #114088 will track the new work for the docked date picker.
