### ISSUE TITLE
[Add to app] Android Build failure

### ISSUE THREAD

**Issue by kxifenger** [flutter/flutter#101401]
i want to Integrate a Flutter module into my Android project
so i use this way
[Integrate a Flutter module into your Android project - Option B - Depend on the module’s source code](https://docs.flutter.dev/development/add-to-app/android/project-setup#option-b---depend-on-the-modules-source-code)
i add some code according to document

![L1VzZXJzL2lmZW5nL0xpYnJhcnkvQXBwbGljYXRpb24gU3VwcG9ydC9EaW5nVGFsa01hYy81NDM3ODU4MzdfdjIvSW1hZ2VGaWxlcy8xNjQ5MjE0MzMwODUzXzk0MkZBRThBLUQ4NEUtNDI2RC04RTZDLTRDQTgwQjgzRDFBQy5wbmc=](https://user-images.githubusercontent.com/77945871/161888429-ea2b553a-0a89-4e45-b3c1-eb1a1fb6dc2b.png)

![L1VzZXJzL2lmZW5nL0xpYnJhcnkvQXBwbGljYXRpb24gU3VwcG9ydC9EaW5nVGFsa01hYy81NDM3ODU4MzdfdjIvSW1hZ2VGaWxlcy8xNjQ5MjE0MDMyMTA1X0I4M0QyMUVGLTZDQTYtNDVGNC1BMThBLThCQTYxMDM4ODI3OC5wbmc=](https://user-images.githubusercontent.com/77945871/161887382-b2378a61-8e12-42dc-9c60-f4270931e86c.png)
but i get this error
![L1VzZXJzL2lmZW5nL0xpYnJhcnkvQXBwbGljYXRpb24gU3VwcG9ydC9EaW5nVGFsa01hYy81NDM3ODU4MzdfdjIvSW1hZ2VGaWxlcy8xNjQ5MjEzMzI3ODQxX0E4QzcyNzIwLUREQjAtNDBBQi1BMjRFLTIyNzZBNEZDNDEwRS5wbmc=](https://user-images.githubusercontent.com/77945871/161887425-3cac7ce0-311f-436a-aa39-fe8c40e2d0dd.png)

here is my environment information
<img width="643" alt="截屏2022-04-06 上午10 50 13" src="https://user-images.githubusercontent.com/77945871/161887469-03d3c75e-c554-4758-876d-e531a62386b2.png">

<img width="1680" alt="截屏2022-04-06 上午10 51 16" src="https://user-images.githubusercontent.com/77945871/161887524-7b03b2ed-9f9d-4f8a-aa90-c029552ffdd0.png">

<img width="951" alt="截屏2022-04-06 上午10 51 24" src="https://user-images.githubusercontent.com/77945871/161887535-ce5c6792-336c-473d-b4dd-ef7f15f1a9eb.png">

![L1VzZXJzL2lmZW5nL0xpYnJhcnkvQXBwbGljYXRpb24gU3VwcG9ydC9EaW5nVGFsa01hYy81NDM3ODU4MzdfdjIvSW1hZ2VGaWxlcy8xNjQ5MjE0MjA3ODA1XzM2NDk1QjUxLUY2QUQtNDdCOS04RUEwLUU4MzY4NzM4NTEwQy5wbmc=](https://user-images.githubusercontent.com/77945871/161887757-1b1f05a4-d89c-4ffd-bd89-074b4c822b6c.png)

**Comment by maheshmnj** [comment]
Hi @kxifenger, Thanks for filing the issue. Can you please attach the minimal reproducible project? Additionally, you may take a look at the add to app samples here 

ps: Please avoid sharing screenshots of codes and logs and prefer sharing them as text.

**Comment by kxifenger** [comment]
there is similar question https://github.com/flutter/flutter/issues/99735 here. the minimal reproducible project is just the empty project created by android studio.And use this way to Integrate a Flutter module into Android project.
 [Integrate a Flutter module into your Android project - Option B - Depend on the module’s source code](https://docs.flutter.dev/development/add-to-app/android/project-setup#option-b---depend-on-the-modules-source-code)

**Comment by maheshmnj** [comment]
Thanks for the info @kxifenger, 

There is a similar issue describing this case https://github.com/flutter/flutter/issues/101347, Please follow up there for further updates, Closing this issue as a duplicate. If you disagree feel free to write in the comments and we will reopen it.

Thank you.
