### ISSUE TITLE
Make Image Picker plugin able to accept a image size

### ISSUE THREAD

**Issue by efortuna** [flutter/flutter#10149]
Feature Request:
Right now Image Picker plugin doesn't do any image scaling. It would be nice to be able to specify how much (if any) scaling down should be done so we're not always sending images at full resolution if it's not necessary

**Comment by roughike** [comment]
I started progress on this today, and would like some feedback as early as possible. 

Two commits so far:

* the [Dart API](https://github.com/roughike/plugins/commit/03dd3addc1b7a449f61f7279f860ed1029735064)
* the [Android implementation](https://github.com/roughike/plugins/commit/3aab08da91ac096534ad10256cfb06df812c1172)

Currently it's Android only, but I'll do iOS once I get the green light that I'm going to the right direction. Also, no docs just yet.

**Comment by roughike** [comment]
The PR was just merged by @collinjackson and is live on image_picker v0.1.2, so this issue can now be closed.
