### ISSUE TITLE
Navigator not working after biometrics auth success on iOS iPhone SE 15.4 simulator. Local_Auth Dart Package

### ISSUE THREAD

**Issue by TreyThomas93** [flutter/flutter#101402]
## Steps to Reproduce

1. Execute `await LocalAuthentication().authenticate(sensitiveTransaction: false, stickyAuth: true)`
2. If authenticated, execute `Navigator.of(context).pushNamed(HomeScreen.id)`

**Expected results:** Expected to "pop" current context and then display home screen.

**Actual results:** current context (screen) stays up and home screen continues in the background.

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @TreyThomas93, please provide the output of `flutter doctor -v` as well as the version of `local_auth` you're using. 

Please also provide a complete minimal reproducible code sample. 

Thank you
