### ISSUE TITLE
Engine -> Framework roll is broken on broken customer test from Dart roll

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#101514]
Starting in the Engine roll here https://github.com/flutter/flutter/pull/101477 containing only the Dart roll here https://github.com/flutter/engine/pull/32459, customer tests started to fail: https://cirrus-ci.com/task/4798879882280960. In particular, we now get the following error from the `flutter_reactive_ble` project:

```
| 00:31 +58 -1: /tmp/flutter_customer_testing.flutter_reactive_ble.TPIKOI/tests/test/reactive_ble_test.dart: FlutterReactiveBle BleStatus stream Get current Ble status It returns last known status from stream [E]
|   Failed assertion: boolean expression must not be null
|   dart:async                         Stream.first
|   test/reactive_ble_test.dart 97:35  main.<fn>.<fn>.<fn>.<fn>
|   test/reactive_ble_test.dart 93:58  main.<fn>.<fn>.<fn>.<fn>
```

The repo for that code is here: https://github.com/PhilipsHue/flutter_reactive_ble

cc @a-siva

**Comment by jason-simmons** [comment]
This regressed with https://github.com/dart-lang/sdk/commit/837ee17b43aa2b5601cad637b9348cc8fd848d99

@mkustermann

**Comment by a-siva** [comment]
I am going to revert https://github.com/dart-lang/sdk/commit/837ee17b43aa2b5601cad637b9348cc8fd848d99 for now so we can make forward progress on the Dart rolls, we are pretty backed up right now because of an earlier issue.

**Comment by a-siva** [comment]
Revert has landed once it moves to the dev channel will trigger a manual dart roll to the engine.

**Comment by goderbauer** [comment]
The revert is in `2.17.0-282.0.dev`.

**Comment by zanderso** [comment]
282 has rolled through to the framework, and I have re-enabled the Dart -> Engine roller.
