### ISSUE TITLE
Add an easy way to add a line via a Widget

### ISSUE THREAD

**Issue by xster** [flutter/flutter#10156]
Consider a simple line like in the following layout
![screen shot 2017-05-17 at 5 10 30 pm](https://cloud.githubusercontent.com/assets/156888/26181271/c067674c-3b23-11e7-940d-de601d2b9418.png)

Would be good to have a widget for just
```dart
const Line(
  orientation: Orientation.horizontal,
  width: 1.5,
  color: const Color(blah)
)
```

**Comment by HansMuller** [comment]
I think Divider does what you want.

**Comment by Hixie** [comment]
You can also just say
```dart
new Container(
  height: 1.5,
  color: const Color(blah),
),
```

**Comment by Hixie** [comment]
I've closed this bug since this appears to already be possible, but please don't hesitate to reopen it if those comments don't solve your problem. Also, if you let us know where we could have put documentation to answer this question (e.g. where did you look for the answer?) we would be very happy to add more documentation to answer the question for other people in the future.

**Comment by xster** [comment]
Ah right. Divider's already in the material section of the widgets catalog. I didn't scroll down far enough. I also first thought to look at the basic section.

**Comment by sethladd** [comment]
Cc @inmatrix

We can add widgets to catalogs. Tell us what you want to add and where :)

**Comment by xster** [comment]
Maybe Divider should be in Basic also (perhaps instead of FlutterLogo and Placeholder (which can go into Layout))

**Comment by HansMuller** [comment]
Divider depends on the Material theme's dividerColor.  Maybe the widget version is just 
```
new Container(
  height: 1.5,
  color: const Color(blah),
)
```
:-)

**Comment by neiljaywarner** [comment]
@sethladd @Hixie @xster  How would you feel about givign Divider a lineHeight parameter; it is a little confusing that it doesn't have one... 1dp is barely visible, it would be nice if it was easy to make it more...

**Comment by Hixie** [comment]
The Divider in the material library is an implementation of the material divider, which is a particular width.
You are welcome to create your own Divider widget with whatever dimensions you like.
The build method for such a widget is very simple, as described above.

**Comment by NoctisShadowzel** [comment]
I want to draw this horizontal line with dashes in Card. How to do this without suffering just to draw a simple line in 4 buttons made out of Cards?
![line_with_dashes](https://user-images.githubusercontent.com/46376183/68086107-28b4e900-fe59-11e9-99bc-da9457131e89.png)

**Comment by Hixie** [comment]
CustomPaint?

**Comment by NoctisShadowzel** [comment]
@Hixie Does it [worth it?](https://stackoverflow.com/questions/54019785/how-to-add-line-dash-in-flutter#answer-57354707) I think it is better to use a PNG in this case...
