### ISSUE TITLE
flutter.io setup instructions don't fit on the screen in narrow mode

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#10153]
The website setup instruction pages don't fit when viewed on a phone:

![screenshot_20170517-121454](https://cloud.githubusercontent.com/assets/13644170/26177595/24aec8e0-3b0f-11e7-8c3f-f74f51240410.png)

**Comment by mit-mit** [comment]
cc @sethladd

**Comment by LarkAscending** [comment]
Hmm, it does resize nicely on desktop and laptop, and also on my Android phone. All with Chrome browser
Can repro w/iPhone 6s and Safari as well as Chrome. 
This appears to be iPhone-specific.

Other interesting detail is, it's only the macOS page. The Windows and Linux setup pages look fine on iPhone. Will look at what small CSS tidbit is different there...

**Comment by LarkAscending** [comment]
The only difference between the page that has this issue and the pages that don't is the following text, under Platform setup:
_macOS supports developing Flutter apps for both iOS and Android. Complete at
least one of the two platform setup steps now, to be able to build and run your
first Flutter app._

It wants to be italic but I believe the leading underscore character is confusing the layout renderer on iPhone. Need to stage to Firebase to test this change, I believe. Committing now...

**Comment by LarkAscending** [comment]
First attempt of https://github.com/flutter/website/pull/581 does not fix this issue. There must be another difference...

**Comment by mit-mit** [comment]
This also repros with Chrome Dev Tools using the 'iPhone 5' device profile.

**Comment by mit-mit** [comment]
Bubbling up from PR discussion: The core of the issue are long strings in back-ticks with no spaces, for example `android/src/main/java/com/yourcompany/hello/HelloPlugin.java`. Kramdown translates these to `white-space: pre-wrap;` which means "dont linebreak".

**Comment by LarkAscending** [comment]
Finished w/setup work, and waiting for platform-plugins to be fixed.
