### ISSUE TITLE
Have some code examples for Animations in docs

### ISSUE THREAD

**Issue by maryx** [flutter/flutter#10157]
## Steps to Reproduce
The doc on Animations is good but it would be great if there could be some simple animation code examples, such as show/hiding a widget.

**Comment by eseidelGoogle** [comment]
@HansMuller we've gotten feedback from multiple folks today that getting-up-to-speed on animation is a weak point.  Something to consider for your current samples effort perhaps?

**Comment by HansMuller** [comment]
I think that's an excellent idea. Will do.

**Comment by iapicca** [comment]
Hi all
give this [docs](https://flutter.dev/docs/development/ui/animations/tutorial)
I feel confident to close this issue,
if you disagree I'll reopen it immediately
thank you
