### ISSUE TITLE
Do not send debugTimelineArguments when `debugProfileBuildsEnabled == true`

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/flutter#101535]
While debugging https://github.com/flutter/flutter/issues/101379, I noticed that with Track Widget Builds enabled (`debugProfileBuildsEnabled`), a large amount of data is getting sent in the trace event args for the 'BUILD' timeline event: https://github.com/flutter/flutter/blob/35b18ba2e902dac1e16f557fa385069f1f5e1069/packages/flutter/lib/src/widgets/framework.dart#L2568-L2575

These additional debugging args were added in https://github.com/flutter/flutter/pull/93086. These events make the trace very heavy and will make the performance impact of Track Widget Builds even worse than it already is. We should create another flag to hide these args behind instead of reusing `debugProfileBuildsEnabled`. 

This may apply to other `debugTimelineArguments` added in https://github.com/flutter/flutter/pull/93086/files#diff-134bc36bd7c045a92ffff29f7efdaa7d375384911475a40343814c76c87b17cb as well. 

CC @Hixie @goderbauer @jacob314

**Comment by goderbauer** [comment]
Placing these behind a separate debug flag sounds good to me.
