### ISSUE TITLE
Offer a way to crop images

### ISSUE THREAD

**Issue by xster** [flutter/flutter#10152]
Maybe something along the line of 
```dart
const CroppedImage(
  topLeft: FractionalOffset.topCenter,
  bottomRight: const FractionalOffset(0.7, 0.4),
  image: const AssetImage('blah.png'),
);
```

**Comment by sethladd** [comment]
+1 for making this, making it a package, and uploading to pub.dartlang.org :)

**Comment by nosmirck** [comment]
I'm in a situation where I need to crop an image (given a point, a height and a width) and this should come in handy. Is this done? How can I use it?

**Comment by MichaelSowah** [comment]
@nosmirck would this help?
https://github.com/hnvn/flutter_image_cropper

**Comment by nosmirck** [comment]
@MichaelSowah not exactly (although it could be helpful for another project).

So, basically what I'm doing is the following:

- user take a picture of a group of people.
- I use ml-kit to detect all faces.
- create and render a list of all the faces.

Ml-kit will return a list of VisionFace. Each one of those objects are basically just the coordinates where the face is located in the image (lefttop pixel and right bottom pixel) plus a bunch of other information not relevant to the cropping (like position of the eyes, how open the mouth is, position of the nose, etc)

So, I need to create a bunch of new images which are nothing more than cropped copies of the original.

I know that given some coordinates I should be able to crop the image and copy into new ones, but it's not out of the box for flutter. It would be great to have something like this original suggestion.

**Comment by VolodymyrLykhonis** [comment]
@nosmirk you can use tools part of the plugin I've just published. If you know relative area of image you need to crop you can use it to get a temp file then load it via Image.file into widget. https://pub.dartlang.org/packages/image_crop

**Comment by lukaville** [comment]
Here is a way to do this using `canvas.drawAtlas`
https://stackoverflow.com/questions/51865503/draw-part-of-an-image-onto-a-widget

**Comment by Shubham-8197** [comment]
https://stackoverflow.com/questions/58076708/how-to-cut-the-parsed-image-in-cross-border-rectagular-shape-in-flutter

**Comment by timsneath** [comment]
Closing this, given that we have a variety of good packages that offer this now.

**Comment by AR553** [comment]
> @MichaelSowah not exactly (although it could be helpful for another project).
> 
> So, basically what I'm doing is the following:
> 
> * user take a picture of a group of people.
> * I use ml-kit to detect all faces.
> * create and render a list of all the faces.
> 
> Ml-kit will return a list of VisionFace. Each one of those objects are basically just the coordinates where the face is located in the image (lefttop pixel and right bottom pixel) plus a bunch of other information not relevant to the cropping (like position of the eyes, how open the mouth is, position of the nose, etc)
> 
> So, I need to create a bunch of new images which are nothing more than cropped copies of the original.
> 
> I know that given some coordinates I should be able to crop the image and copy into new ones, but it's not out of the box for flutter. It would be great to have something like this original suggestion.

Did you find any thing that worked for you in this specific condition??

**Comment by nosmirck** [comment]
@AR553 I used a package that I think doesn't work anymore, but the closest thing to what I used is this one:

https://pub.dev/packages/flutter_native_image

It provides a method for cropping the image giving x, y coordinates for the origin and width, height. It's exactly how the one I used worked.

**Comment by abhishekove** [comment]
I want to crop a part of the image using a path using canvas. How to do it.
