### ISSUE TITLE
[Fonts] Icon request: square & triangle (rounded & filled) in Flutter

### ISSUE THREAD

**Issue by camvrst** [flutter/flutter#101566]

**Comment by danagbemava-nc** [comment]
Hi @camvrst, the square icons are all available on stable. The `square` is the equivalent of `square_filled`. 

https://api.flutter.dev/flutter/material/Icons/square-constant.html
https://api.flutter.dev/flutter/material/Icons/square_rounded-constant.html
https://api.flutter.dev/flutter/material/Icons/square_outlined-constant.html
https://api.flutter.dev/flutter/material/Icons/square_sharp-constant.html

As for the triangle, I can't see any reference to it on the material icons site. See screenshot below, which icon are you referring to?

![Screenshot 2022-04-08 at 08 55 50](https://user-images.githubusercontent.com/88313112/162403743-b3f7b50d-2c12-4090-82e8-2ad4483be741.png)

**Comment by camvrst** [comment]
Hello @danagbemava-nc 
Thanks for your answer. I'm on version 2.10.0 stable and when I use Icons.square, nothing appears on the screen. 
See below the output : 
![image](https://user-images.githubusercontent.com/67645553/162405712-416357bf-0019-482c-9de2-7ec62e3f1e6a.png)

For the triangle, I was surprised that there is no icon that just represent the actual shape of a triangle. If possible, I would like to have the Icons.change_history_rounded to be filled.

**Comment by danagbemava-nc** [comment]
You need to upgrade to stable 2.10.4, there was an issue with icons on the version of stable you're on. 

Unfortunately, the material icons site itself doesn't have a version of `change_history` that is filled

https://user-images.githubusercontent.com/88313112/162407912-2faead52-c5c8-40dc-badc-64b4a602d3d0.mov
