### ISSUE TITLE
How to set app version when run `flutter build windows`?

### ISSUE THREAD

**Issue by liqi1997** [flutter/flutter#101555]
I saw `With Flutter Windows Desktop, the version number must be set during the packaging process` in official doc site, but there is no function to set app version.

**Comment by maheshmnj** [comment]
Hi @liqi1997, Thanks for filing the issue. The windows app release version needs to be manually modified as of today in `windows/runner/Runner.rc`  file by modifying the variables `FLUTTER_BUILD_NUMBER` and `FLUTTER_BUILD_NAME`

However, There is a feature request to change it via `pubspec.yaml` here https://github.com/flutter/flutter/issues/73652
Labeling this issue as a documentation request.

**Comment by darshankawar** [comment]
@liqi1997 
The related issue https://github.com/flutter/flutter/issues/73652 has been fixed and merged. See this comment for your reference: https://github.com/flutter/flutter/issues/73652#issuecomment-1232090165

With this, I am going ahead and closing as resolved. If you disagree, write in comments and I'll reopen it.
