### ISSUE TITLE
App crashes after packaging

### ISSUE THREAD

**Issue by stevenroose** [flutter/flutter#1015]
I just packaged an app (successfully as `flutter apk` suggested). I uploaded it to the Play Store and the app crashes on launch.

This are the logcat logs: https://gist.github.com/stevenroose/4c99c4a539e9992796b1

It's weird that this error does not happen with `flutter start`..

**Comment by abarth** [comment]
`Didn't find class "ch.roose.steven.gaze.app.GazeApplication"`

Does your AndroidManifest.xml reference that class?

**Comment by stevenroose** [comment]
Yes

**Comment by stevenroose** [comment]
Should I have left the `org.domokit.sky.shell.SkyApplication` uri?

**Comment by abarth** [comment]
Yeah.  That line tells Android to look inside your Java code for a class with that name.  Because you're not compiling any new Java code, your APK doesn't have a class named `ch.roose.steven.gaze.app.GazeApplication`.  Instead, you want to use the default `SkyApplication` that's already compiled in.

**Comment by stevenroose** [comment]
Ok, if that was trivial and I just didnt know (I'm new to Android dev), you can close this issue :)

**Comment by stevenroose** [comment]
@abarth Same holds for the Activity?

**Comment by abarth** [comment]
Yes.  We should use this issue to improve the documentation.

**Comment by eseidelGoogle** [comment]
We also probably need an issue about creating a workflow where you *do* add java code.  Since right now `flutter apk` is our only workflow and it doesn't support that.

**Comment by stevenroose** [comment]
@eseidelGoogle Mixing Dart and Java? Shouldn't that be avoided at all costs? What about iOS then? Add Objective C code as well?

**Comment by eseidelGoogle** [comment]
`flutter apk` already includes flutter-team-written java code for talking to the network and keyboard, etc in the apk it generates.  If consumers of flutter also wish to bundle their own Java (or Obj-C/Swift on iOS) code that seems like a reasonable request we should support.

**Comment by eseidelGoogle** [comment]
There is now a plan underway to make using your own Java code/project much easier:
https://docs.google.com/document/d/1DOfwpL6VojCAG_zjjcA_z5ekF7rTIohV8dWn2o7_IME/edit

**Comment by abarth** [comment]
This ill be fixed by ^^ and doesn't need to be tracked separately.
