### ISSUE TITLE
Identify clicks on webview pages

### ISSUE THREAD

**Issue by rodrigonepomuceno** [flutter/flutter#101523]
## Environment

**Flutter version:** Flutter 2.10.4 • channel stable 
**Plugin version:**  webview_flutter: ^3.0.2

## Description

I have a webview that loads a sequence of internal pages that have been created. Within these pages I need to get certain clicks to perform certain actions in Flutter and not on the page.

Example
I have this page made with React, I need to know that the user clicked the back button.

```function App() {
  return (
    <div className="App">
      <button name="button" type="button" onClick={() =>window.history.back()}>
        Back
      </button>
      <p>Page Test</p>
    </div>
  );
}```
Any way to get specific clicks performed within the page loaded in the webview?

**Comment by darshankawar** [comment]
@rodrigonepomuceno 
Your question is best suited for support channels like StackOverflow, so please ask the same there.
See this similar SO link for your reference and check if it helps to answer your question.
Closing from here as this is more of a code assistance question.
