### ISSUE TITLE
[CP] Pick up DWDS fix supporting Chrome 100

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#101531]
### issue_link

https://github.com/flutter/flutter/issues/101224

### Commit Hash

This requires picking up pub release dwds v11.5.2

### Target

stable

### Impacted Users

All Flutter for Web developers who use Chrome 100 (and all Chrome users will be auto-upgraded to it)

### Impact Description

Breakpoints will not work from Chrome >100 and Flutter for web apps.

### Workaround

https://github.com/flutter/flutter/issues/101224#issuecomment-1092324782

### Risk

medium

### Test Coverage

no

**Comment by christopherfujino** [comment]
I created a PR with the fix: https://github.com/flutter/flutter/pull/101529

**Comment by CaseyHillers** [comment]
This is available in 2.10.5
