### ISSUE TITLE
Add an option to remove the shadows of a flutter window on desktop [linux]

### ISSUE THREAD

**Issue by scotch-hub** [flutter/flutter#101573]
I believe that such a feature would allow for better window customisation on desktop and increase the range of possibilities UI wise.

I have been trying to add custom rounded corners to my flutter desktop window on Linux and one way I was thinking about the problem is by making the GTK window transparent and letting flutter itself draw the rounded corner. However, this effect doesn't look good on Linux because there are shadows expanding from the original window

Corner radius was increased to make the shadow more noticeable:
![Screenshot from 2022-04-08 12-37-06](https://user-images.githubusercontent.com/73116038/162419532-b0bc7096-f8fd-43bc-8e83-a5274d5d402d.png)

**Comment by darshankawar** [comment]
@scotch-hub 
I think your issue is similar to https://github.com/flutter/flutter/issues/31373. Once the desktop client side support is implemented, you'll be able to customize the shadows.  Please follow-up in linked issue for further updates.
If you disagree, write in comments and I'll reopen it.

**Comment by scotch-hub** [comment]
I'm aware of the present P5 label, I was just wondering if tackling this feature is something that is on the flutter team's radar for the foreseeable future?
