### ISSUE TITLE
devicelab-mac-1 is dead hanging ios presubmit tests

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#101542]
[devicelab-mac-1](https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-1)

**Comment by keyonghan** [comment]
Brough up mac46 to unblock the workflow. 

Mac1 seems not ssh accessible and needs a lab visit.

**Comment by yusuf-goog** [comment]
rebooted. bot is back up with the following error:

Device healthcheck failed: device_pair: Executable idevicepair failed with exit code 1.;

**Comment by yusuf-goog** [comment]
Trust device needs to be accepted on the phone:

```
idevicepair validate
ERROR: Device 6911fc30[...]4 is not paired with this host
```

**Comment by yusuf-goog** [comment]
accepted trust dialog, bot is back up.
