### ISSUE TITLE
How to run all benchmark test cases

### ISSUE THREAD

**Issue by JsouLiang** [flutter/flutter#101552]
I found in current version we run the benchmark need to use the param `-t` to specified task like this:
`../../bin/cache/dart-sdk/bin/dart bin/run.dart -t test1 -t test2 -t test3`
But in my current scenario, I want to run all the benchmark tasks, how to do this?
If I use `../../bin/cache/dart-sdk/bin/dart bin/run.dart -h` found the param `-a`
<img width="1174" alt="截屏2022-04-08 上午10 17 48" src="https://user-images.githubusercontent.com/10297030/162350197-37ebfc3d-6c7d-44bd-9859-cc99b31be920.png">
but the `manifest.yaml` was deleted.
So In current version(after 2.10) how to run the all benchmarks?
cc @CaseyHillers

**Comment by CaseyHillers** [comment]
Correct, this is no longer supported (nor has it worked for the past year). The issue was the tests are mutually exclusive, like Windows and ios.

You can do something like `find bin/tasks -name *.dart | xargs dart bin/test_runner.dart test` to achieve the same result. However, you should curate the list of tests you're interested in running as well.

**Comment by JsouLiang** [comment]
That sound good. If I have Android device then I want run all benchmarks which environment is Android device, so can I split these benchmark tasks?
`iOS devices run all iOS devices benchmark tasks.`
`Android devices run all Android devices benchmark tasks.`
How to specific tasks by devices type?
Thanks.
@CaseyHillers

**Comment by CaseyHillers** [comment]
You could do `find bin/tasks -name *android*.dart | xargs dart bin/test_runner.dart test`
(1) There's no guarantee the file names indicate a test is to run on Android
(2) This is a subset of the true android tests

If this is something your infrastructure needs, it'd be best to send a PR here to explicitly add this type of flag

**Comment by JsouLiang** [comment]
That's good, I will try it, thank you.

**Comment by JsouLiang** [comment]
hay, I have a question, why not we use a yaml file that control the task can run where?
Like this:
```
tasks:
  task1:
    targets: [iOS, Android]
```
In this we can run the all tasks which are match my device. for example if I have android device, the i run this: `bin/test_runner.dart -d android_device_id` that run all the android benchmark tasks.
@CaseyHillers

**Comment by CaseyHillers** [comment]
That already exists in https://cs.opensource.google/flutter/flutter/+/master:.ci.yaml, the stage format is Linux_android, Mac_ios, etc
