### ISSUE TITLE
Version 2.10.2 App Bundle on Play Store Flutter app crashes on start on Android: couldn't find "libflutter.so" 

### ISSUE THREAD

**Issue by utkudenis** [flutter/flutter#101502]
## Steps to Reproduce

Our application is installed on approximately 3 thousand devices, but we started getting crash reports from these two devices about 2 days ago. Apart from these, we do not have a problem with other devices and android versions before and now. We uploaded it to Google Play as an App bundle.
Before making a bundle, we do flutter clean as standard and pull all the packages from the beginning and throw them away with fastlane automation.
Version The version of flutter we got is 2.10.2.

This problem has also emerged in previous years, but no clear solution and explanation has come.

![image](https://user-images.githubusercontent.com/68633376/162187978-4f7819ab-4809-4557-b4d0-2302261dc3d7.png)
![image](https://user-images.githubusercontent.com/68633376/162188024-856a063f-9fc6-4a4a-9052-5ce55cd809e0.png)

**Comment by darshankawar** [comment]
@utkudenis 
Can you provide the crash log in text format ? From above screenshot, it seems Android 7 is most affected which is api level 25.

**Comment by utkudenis** [comment]
@darshankawar 
also android 8 and 9 :( 

Can they  be rooted devices ? 

that is the text format 


Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.falsepeti.falsepeti/com.falsepeti.falsepeti.MainActivity}: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.falsepeti.falsepeti-1/base.apk", zip file "/data/app/com.falsepeti.falsepeti-1/split_config.ar.apk", zip file "/data/app/com.falsepeti.falsepeti-1/split_config.hdpi.apk", zip file "/data/app/com.falsepeti.falsepeti-1/split_config.tr.apk", zip file "/data/app/com.falsepeti.falsepeti-1/split_config.x86.apk"],nativeLibraryDirectories=[/data/app/com.falsepeti.falsepeti-1/lib/x86, /data/app/com.falsepeti.falsepeti-1/base.apk!/lib/x86, /data/app/com.falsepeti.falsepeti-1/split_config.ar.apk!/lib/x86, /data/app/com.falsepeti.falsepeti-1/split_config.hdpi.apk!/lib/x86, /data/app/com.falsepeti.falsepeti-1/split_config.tr.apk!/lib/x86, /data/app/com.falsepeti.falsepeti-1/split_config.x86.apk!/lib/x86, /system/lib, /vendor/lib, /data/downloads, /data/priv-downloads]]] couldn't find "libflutter.so"
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2668)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2729)
       at android.app.ActivityThread.-wrap12(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1480)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6138)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:893)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)

**Comment by darshankawar** [comment]
@utkudenis 
Looking at the logs, it seems to be similar to https://github.com/flutter/flutter/issues/83596, so please follow-up in it for further updates. Closing this as a duplicate. If you disagree, write in comments and I'll reopen it.
