### ISSUE TITLE
Kotlin native instead of JVM

### ISSUE THREAD

**Issue by lattice0** [flutter/flutter#101510]
## Use case

Creating native plugins for Flutter on Android is a little bit hard because we still need to call JVM code for some stuff, like OpenGL stuff. If kotlin were compiled natively, we could have true native-only plugins and still talk to Android.

## Proposal

Support the plugin method calls to go to a kotlin code directly, so we don't need to call JVM code, which is very annoying and forces us to have JVM and native code for a plugin in separated parts.

**Comment by blasten** [comment]
Someone answered this question on Stackoverflow: https://stackoverflow.com/questions/71615644/how-to-use-kotlin-native-code-with-android-ndk

I don't think there's anything from Flutter that is required.
