### ISSUE TITLE
[CP] Ensure that the engine frame callbacks are installed if the first scheduled frame is a forced frame

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#101585]
### issue_link

https://github.com/flutter/flutter/issues/98419

### Commit Hash

b63c4a6db091a6bb47d5e0e0b32fa5b5b410b28e

### Target

beta

### Impacted Users

All devs and users

### Impact Description

A race on startup occasionally causes the Flutter view not to load, and apps to be unresponsive. We see this issue in ~2-3% of app launches in the devicelab.

### Workaround

There is no workaround

### Risk

low

### Test Coverage

yes

### Validation Steps

The race is difficult to trigger locally. The flaky bot will monitor the flake rate in the device lab.

**Comment by zanderso** [comment]
This is for a cherry-pick against the 2.13 beta.

**Comment by CaseyHillers** [comment]
This was included in https://github.com/flutter/flutter/pull/102193 and will ship in todays beta hotfix.
