### ISSUE TITLE
Running "flutter test --platform chrome --coverage" does not generate a coverage report

### ISSUE THREAD

**Issue by oscarnar** [flutter/flutter#101540]
The command run succeeds, however, no coverage report is generated (which defeats the purpose of wanting to run both commands together). I'm not sure if put `--platform chrome` here is correct.

Steps to repro:

- create a new project: `flutter create sample`
- `cd sample`
- `flutter test --platform chrome --coverage`
- Observe that no coverage directory is created
- `flutter test --coverage`
- Observe that a coverage directory is properly created

For context, running both of these arguments together is useful in order to get code coverage reports when we are running web projects with plugins that contains `dart:html` library. For example, [google_maps](https://pub.dev/packages/google_maps).

Flutter doctor output:
<details>
<summary>➜  ~ flutter doctor -v</summary>
<br>
[✓] Flutter (Channel stable, 2.10.1, on Arch Linux 5.17.1-arch1-1, locale en_US.UTF-8)
    • Flutter version 2.10.1 at /opt/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db747aa133 (8 weeks ago), 2022-02-09 13:57:35 -0600
    • Engine revision ab46186b24
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31)
    • Android SDK at /opt/android-sdk
    • Platform android-31, build-tools 31
    • ANDROID_HOME = /opt/android-sdk
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /opt/google/chrome/chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 13.0.1
    • cmake version 3.23.0
    • ninja version 1.10.2
    • pkg-config version 1.8.0

[✓] Android Studio (version 2021.1)
    • Android Studio at /opt/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Arch Linux 5.17.1-arch1-1
    • Chrome (web)    • chrome • web-javascript • Google Chrome 99.0.4844.82 unknown

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
</details>

**Comment by darshankawar** [comment]
@oscarnar 
The flutter tool doesn't support covering coverage for web platform and hence nothing gets generated.
See [this](https://github.com/flutter/flutter/issues/55437#issuecomment-618182072) issue comment and similar [issue](https://github.com/flutter/flutter/issues/55437) for your reference. Please follow-up in it for further updates.
