### ISSUE TITLE
The github bot should allow tbr reverts further back from top-of-tree

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#101522]
We needed to revert a Dart roll that was one commit back and the bot didn't land it: https://github.com/flutter/engine/pull/32496

The bot should land clean reverts TBR even if they are many commits back.

@godofredoc @keyonghan

**Comment by ricardoamador** [comment]
Yes sir.

**Comment by ricardoamador** [comment]
This is a duplicate of https://github.com/flutter/flutter/issues/108374
