### ISSUE TITLE
Documentation for keytool

### ISSUE THREAD

**Issue by wmleler** [flutter/flutter#10159]
On https://flutter.io/android-release/ we should add some documentation that explains what keytool does and especially say where it leaves the key.jks file. It wasn't in the current directory, nor in the app directory. I had to search and finally found it in my home directory (ick!).

**Comment by jakobr-google** [comment]
Keytool leaves the keystore in your home directory because you told it to (the `-keystore ~/key.jks` part of the command line), and we point you to the directory in the next section, 'Reference the keystore from the app', but of course we can improve the text.

You don't want to keep the keystore with the app, since you'll want to use the same key for other apps as well. There's a ton of information on this in the Studio documentation that we could link to, like https://developer.android.com/studio/publish/app-signing.html.

**Comment by mit-mit** [comment]
@wmleler if you have concrete suggestions for edits, you are very much invited to send a PR!

**Comment by drexel-ue** [comment]
I am getting this error:

Generating 2,048 bit RSA key pair and self-signed certificate (SHA256withRSA) with a validity of 10,000 days
        for: CN=Ikkesh Pack, OU=Development, O=PackApps, L=Columbus, ST=OH, C=US
[Storing ~/key.jks]
keytool error: java.io.FileNotFoundException: ~\key.jks (The system cannot find the path specified)
java.io.FileNotFoundException: ~\key.jks (The system cannot find the path specified)
        at java.base/java.io.FileOutputStream.open0(Native Method)
        at java.base/java.io.FileOutputStream.open(FileOutputStream.java:299)
        at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:238)
        at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:127)
        at java.base/sun.security.tools.keytool.Main.doCommands(Main.java:1308)
        at java.base/sun.security.tools.keytool.Main.run(Main.java:397)
        at java.base/sun.security.tools.keytool.Main.main(Main.java:390)


could you advise?

**Comment by rajeshjeshar** [comment]
@drexel-ue you have to replcae that **~** with any folder path in ur computer

First Create a **Newfolder** in **D** drive then paste this command
"keytool -genkey -v **-keystore D:\Newfolder\key.jks** -keyalg RSA -keysize 2048 -validity 10000 -alias key"

**Comment by zoechi** [comment]
Issue moved to [flutter/website #2066](https://github.com/flutter/website/issues/2066) via [**ZenHub**](https://www.zenhub.com/)

**Comment by marslord** [comment]
> I am getting this error:
> 
> ```
> Generating 2,048 bit RSA key pair and self-signed certificate (SHA256withRSA) with a validity of 10,000 days
>         for: CN=Ikkesh Pack, OU=Development, O=PackApps, L=Columbus, ST=OH, C=US
> [Storing ~/key.jks]
> keytool error: java.io.FileNotFoundException: ~\key.jks (The system cannot find the path specified)
> java.io.FileNotFoundException: ~\key.jks (The system cannot find the path specified)
>         at java.base/java.io.FileOutputStream.open0(Native Method)
>         at java.base/java.io.FileOutputStream.open(FileOutputStream.java:299)
>         at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:238)
>         at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:127)
>         at java.base/sun.security.tools.keytool.Main.doCommands(Main.java:1308)
>         at java.base/sun.security.tools.keytool.Main.run(Main.java:397)
>         at java.base/sun.security.tools.keytool.Main.main(Main.java:390)
> ```
> 
> could you advise?

Just share another way, the command can run by Cmder on windows.

**Comment by hirenvadher95** [comment]
> advise

replace ~\key.jks with a directory where you want to store it.

**Comment by Mastersam07** [comment]
@marslord 

Create a folder then supply path instead of using ~\key.jsk . The generated key would be stored in this created folder.

Say I create a folder key in my app directory, I would run the command below:

`keytool -genkey -v -keystore C:\Users\USER\Downloads\Compressed\flutterApp\key\key.jks -keyalg RSA -keysize 2048 -validity 20000 -alias key`

**Comment by ASHOK1815** [comment]
pleas helpp me

[Storing c:\Users\USER_NAME\key.jks]
keytool error: java.io.FileNotFoundException: c:\Users\USER_NAME\key.jks (Access is denied)
java.io.FileNotFoundException: c:\Users\USER_NAME\key.jks (Access is denied)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(FileOutputStream.java:270)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:101)
        at sun.security.tools.keytool.Main.doCommands(Main.java:1196)
        at sun.security.tools.keytool.Main.run(Main.java:368)
        at sun.security.tools.keytool.Main.main(Main.java:361)

**Comment by Mastersam07** [comment]
@ASHOK1815 it seems you are trying to create the key.jks in c:\Users\USER_NAME and you need administrative privilege or something. You should change the location of the key to somewhere else. It could even be in your flutter project directory, but ensure not to commit the key.jks file.

You might also want to check the previous response.

**Comment by ASHOK1815** [comment]
> @ASHOK1815 it seems you are trying to create the key.jks in c:\Users\USER_NAME and you need administrative privilege or something. You should change the location of the key to somewhere else. It could even be in your flutter project directory, but ensure not to commit the key.jks file.
> 
> You might also want to check the previous response.

sir i try to another folder also it show that path is not found

**Comment by ASHOK1815** [comment]
i tried this also -genkey -v -keystore D:\keyfolder\key.jks -storetype JKS -keyalg RSA -keysize 2048 -validity 10000 -alias key but doesnot work

**Comment by ASHOK1815** [comment]
it show [Storing D:\keyfolder\key.jks]
keytool error: java.io.FileNotFoundException: D:\keyfolder\key.jks (The system cannot find the file specified)
java.io.FileNotFoundException: D:\keyfolder\key.jks (The system cannot find the file specified)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(FileOutputStream.java:270)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:101)
        at sun.security.tools.keytool.Main.doCommands(Main.java:1196)
        at sun.security.tools.keytool.Main.run(Main.java:368)
        at sun.security.tools.keytool.Main.main(Main.java:361)

**Comment by Mastersam07** [comment]
> it show [Storing D:\keyfolder\key.jks]
> keytool error: java.io.FileNotFoundException: D:\keyfolder\key.jks (The system cannot find the file specified)
> java.io.FileNotFoundException: D:\keyfolder\key.jks (The system cannot find the file specified)
> at java.io.FileOutputStream.open0(Native Method)
> at java.io.FileOutputStream.open(FileOutputStream.java:270)
> at java.io.FileOutputStream.(FileOutputStream.java:213)
> at java.io.FileOutputStream.(FileOutputStream.java:101)
> at sun.security.tools.keytool.Main.doCommands(Main.java:1196)
> at sun.security.tools.keytool.Main.run(Main.java:368)
> at sun.security.tools.keytool.Main.main(Main.java:361)

Can you try using the folder housing your flutter project? Something like: 

```
keytool -genkey -v -keystore C:\ProjectPath\key.jks -keyalg RSA -keysize 2048 -validity 20000 -alias key
```

**Comment by ASHOK1815** [comment]
thanks a lot sir its done....

**Comment by ASHOK1815** [comment]
now again i m getting this problem...

Note: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher-5.4.10\android\src\main\java\io\flutter\plugins\urllauncher\WebViewActivity.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:validateSigningRelease'.
> Keystore file not set for signing config release

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

**Comment by Mansoor041** [comment]
> @drexel-ue you have to replcae that **~** with any folder path in ur computer
> 
> Eg:My App name is **[Bing notes](https://play.google.com/store/apps/details?id=mastermind.flutter.notes)**
> 
> First Create a `Newfolder` in `D:\` drive then paste this command
> 
> ```shell
> keytool -genkey -v -keystore D:\Newfolder\bingnotes.jks -keyalg RSA -keysize 2048 -validity 10000 -alias bingnotes
> ```

worked for me thanks

**Comment by achmadrizkin** [comment]
> > > it show [Storing D:\keyfolder\key.jks]
> > > keytool error: java.io.FileNotFoundException: D:\keyfolder\key.jks (The system cannot find the file specified)
> > > java.io.FileNotFoundException: D:\keyfolder\key.jks (The system cannot find the file specified)
> > > at java.io.FileOutputStream.open0(Native Method)
> > > at java.io.FileOutputStream.open(FileOutputStream.java:270)
> > > at java.io.FileOutputStream.(FileOutputStream.java:213)
> > > at java.io.FileOutputStream.(FileOutputStream.java:101)
> > > at sun.security.tools.keytool.Main.doCommands(Main.java:1196)
> > > at sun.security.tools.keytool.Main.run(Main.java:368)
> > > at sun.security.tools.keytool.Main.main(Main.java:361)
> > 
> > 
> > Can you try using the folder housing your flutter project? Something like:
> > ```
> > keytool -genkey -v -keystore C:\ProjectPath\key.jks -keyalg RSA -keysize 2048 -validity 20000 -alias key
> > ```
> 
> Sir help me plse in my problem

same as me, are you still get error like that ? maybe you can help me

**Comment by shahriar5653** [comment]
> I am getting this error:
> 
> ```
> Generating 2,048 bit RSA key pair and self-signed certificate (SHA256withRSA) with a validity of 10,000 days
>         for: CN=Ikkesh Pack, OU=Development, O=PackApps, L=Columbus, ST=OH, C=US
> [Storing ~/key.jks]
> keytool error: java.io.FileNotFoundException: ~\key.jks (The system cannot find the path specified)
> java.io.FileNotFoundException: ~\key.jks (The system cannot find the path specified)
>         at java.base/java.io.FileOutputStream.open0(Native Method)
>         at java.base/java.io.FileOutputStream.open(FileOutputStream.java:299)
>         at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:238)
>         at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:127)
>         at java.base/sun.security.tools.keytool.Main.doCommands(Main.java:1308)
>         at java.base/sun.security.tools.keytool.Main.run(Main.java:397)
>         at java.base/sun.security.tools.keytool.Main.main(Main.java:390)
> ```
> 
> could you advise?

hi bro do you know how to solve that issue?

**Comment by hello-paulvin** [comment]
You can generate with android studio

**Comment by ASHOK1815** [comment]
keytool -genkey -v -keystore C:\Users\ASUS\classwork\test18\key.jks -keyalg RSA -keysize 2048 -validity 20000 -alias key
try to run in this way ... it will help you 

apart from this is you are using   new version dart version so change to  in puspec file the dependencies to 
flutter_svg: ^0.18.0
