### ISSUE TITLE
[autosubmit] The bot has not merged PRs for over 13 hours

### ISSUE THREAD

**Issue by Piinks** [flutter/flutter#101539]
The last PR the bot merged was https://github.com/flutter/flutter/pull/101280
It has not merged any further PRs despite the tree being green since then.

Folks have started to manually merge PRs, but that option is not available to all contributors.

**Comment by keyonghan** [comment]
Currently there are [11 PR](https://github.com/flutter/flutter/pulls?q=is%3Aopen+is%3Apr+label%3A%22waiting+for+tree+to+go+green%22
) labeled `waiting for tree to go green`, and only https://github.com/flutter/flutter/pull/101533 is mergeable. All others either have unfinished tests, or are stuck at `Google Testing` /cc @CaseyHillers 

https://github.com/flutter/flutter/pull/101533 was labeled 1 hour ago, will take a look at the log to see if any issues.

**Comment by keyonghan** [comment]
From backend log, the api failed to process pull request #101345:
```
2022-04-07 13:46:07.616 PDT
_checkPRs error in flutter/flutter: Null check operator used on a null value
```

**Comment by keyonghan** [comment]
The culprit is a null `labelId` is used here: https://github.com/flutter/cocoon/blob/main/app_dart/lib/src/request_handlers/check_for_waiting_pull_requests.dart#L296

**Comment by keyonghan** [comment]
Deploying a new version to pick up the fix. Keep it open before validated.

**Comment by keyonghan** [comment]
Bot is merging PRs: https://github.com/flutter/flutter/pull/101543.
