### ISSUE TITLE
Opacity/FadeTransition should allow child widgets to avoid repainting

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#101597]
In the engine an opacity layer is rendered by rendering child layers, performing a render target switch, and then blending the resulting texture with the opacity. This texture created by child rendering is cached, and if the child layers have not changed (as determined by the layer identity/id), the texture can be re-used on subsequent frames even as the opacity itself updates.

Unfortunately in many circumstances the framework does not hit this fast path. For example, consider the following code which uses AnimatedSwitcher and its default FadeTransition:

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MaterialApp(
    checkerboardRasterCacheImages: true,
    home: Scaffold(
      body: Example(),
    ),
  ));
}

class Example extends StatefulWidget {
  const Example({Key? key}) : super(key: key);

  @override
  State<Example> createState() => _ExampleState();
}

class _ExampleState extends State<Example> {
  bool alternate = false;

  void _switch() {
    setState(() {
      alternate = !alternate;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Column(
      children: <Widget>[
        Container(height: 100),
        TextButton(onPressed: _switch, child: const Text('Switch')),
        AnimatedSwitcher(
          duration: const Duration(milliseconds: 250),
          child: Container(
            key: ValueKey<bool>(alternate),
            child: Column(
              children: <Widget>[
                Container(
                  width: 200,
                  height: 200,
                  color: Colors.red,
                  child:
                      alternate ? const Text('TITLE A') : const Text('TITLE B'),
                ),
              ],
            ),
          ),
        ),
      ],
    );
  }
}

```

If you observe this on device, you will notice that the raster cache checkerboard flashes - because each new frame gets a new entry as the children are not reused. This can also be observed in the timeline, where each frame has a RasterCachePopulate call indicating the texture created by child rendering has been recreated. Note that this is significantly easier to observe if the child rasterization is more complex.

![ezgif-1-9af8f23920](https://user-images.githubusercontent.com/8975114/162498162-058bc930-d252-493f-a3ae-0aee6bb18552.gif)

If we replace the `Container` in the example above with a `RepaintBoundary`, then we get cached rendering:

![ezgif-1-0b4c0c3469](https://user-images.githubusercontent.com/8975114/162498825-d716e95d-5c36-43ba-8cbf-2b7929a9ed93.gif)

To ensure that opacity performance can hit the fast path more frequently, we should update the Opacity and FadeTransition widgets to insert a RepaintBoundary child. This may have an impact on subpixel rendering. To evaluate I will run tests in google3 and report back. The expected impact of this change is improved raster times in applications that use AnimatedSwitcher, FadeTransition, and Opacity.

**Comment by jonahwilliams** [comment]
FYI @goderbauer

**Comment by goderbauer** [comment]
In general, we recommend against animating the Opacity widget (AnimatedOpacity or a FadeTransition should be used instead). Does the repaint boundary here actually buy us anything if you follow that advice?

**Comment by jonahwilliams** [comment]
This isn't particular to animated opacity though. For example, consider the following example in which opacity is constant but a parent is animating. Without the repaint boundary we throw away the child texture for the opacity rendering on every frame, which is tremendously wasteful compared to reusing it.


```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MaterialApp(
    checkerboardRasterCacheImages: true,
    home: Scaffold(
      body: Example(),
    ),
  ));
}

class Example extends StatefulWidget {
  const Example({Key? key}) : super(key: key);

  @override
  State<Example> createState() => _ExampleState();
}

class _ExampleState extends State<Example> with TickerProviderStateMixin {
  late final AnimationController _controller = AnimationController(vsync: this, duration: const Duration(seconds: 1));
  late final Animation<Offset> _position = _controller.drive(
    Tween(begin: const Offset(0.0, 0.0), end: const Offset(1, 1.0)));

  @override
  void initState() {
    super.initState();
    _controller.reset();
    _controller.forward();
    _controller.addStatusListener((status) {
      if (status == AnimationStatus.completed) {
    _controller.reset();
    _controller.forward();
      }
    });
  }

  @override
  Widget build(BuildContext context) {
    return Column(
      children: <Widget>[
        Container(height: 100),
        SlideTransition(
          position: _position,
          child: Opacity(
            opacity: 0.9,
            includeRepaintBoundary: false,
            child: Container(
              child: Column(
                children: <Widget>[
                  Container(
                    width: 200,
                    height: 200,
                    color: Colors.red,
                    child: const Text('A'),
                  ),
                ],
              ),
            ),
          ),
        ),
      ],
    );
  }
}
```

**Comment by jonahwilliams** [comment]
Here is the gif showing repaint on each frame:
![ezgif-1-f77b90492c](https://user-images.githubusercontent.com/8975114/162545119-221272a4-fdce-4be0-a656-f82e833563ae.gif)

**Comment by jonahwilliams** [comment]
Then with the RepaintBoundary inserted:

![ezgif-1-29650cc430](https://user-images.githubusercontent.com/8975114/162545236-eea7a9d5-2b6e-449b-a286-2412a4675470.gif)

**Comment by jonahwilliams** [comment]
I'm going to re-open this issue since I'm not quite satisfied with the solution after reading more details in 101810.

**Comment by flar** [comment]
The SlideTransition should have a RepaintBoundary around its child otherwise it reconstructs the entire tree under it every time it changes its value.

The tree is supposed to reuse objects wherever it can, but I think container widgets have trouble doing this because their children "might" be different if they are repainting and we don't really track "no, you still have the same children and nothing below you changed so you can reuse your layer" except at a RepaintBoundary which is specifically created for that task. If there was a RepaintBoundary under the SlideTransition then not only would the conditions for the opacity remain stable for caching, but it wouldn't have to be reconstructed every frame. Putting a RepaintBoundary underneath it does stabilize it for caching purposes, but the real culprit is the animation above it that is forcing the tree to rebuild on every frame.

**Comment by flar** [comment]
Here is a variation of your first example that works much more smoothly when you click the Add RepaintBoundary button which puts the RepaintBoundary as the child of the animating widget. There is no flashing and the cache is reused between frames.

<details>
  <summary>Variation on first example</summary>
  
```
import 'package:flutter/material.dart';

void main() {
  runApp(const MaterialApp(
    checkerboardRasterCacheImages: true,
    home: Scaffold(
      body: Example(),
    ),
  ));
}

class Example extends StatefulWidget {
  const Example({Key? key}) : super(key: key);

  @override
  State<Example> createState() => _ExampleState();
}

class _ExampleState extends State<Example> {
  bool alternate = false;
  bool isolate = false;

  void _switchChild() {
    setState(() {
      alternate = !alternate;
    });
  }

  void _toggleIsolation() {
    setState(() {
      isolate = !isolate;
    });
  }

  @override
  Widget build(BuildContext context) {
    Widget animatedChild = Container(
      key: ValueKey<bool>(alternate),
      child: Column(
        children: <Widget>[
          for (int i = 0; i < 200; i += 20)
            Container(
              width: 200,
              height: 20,
              color: HSVColor.fromAHSV(1.0, i * 360 / 200, 1.0, 1.0).toColor(),
              child: alternate ? Text('TITLE A'*5) : Text('TITLE B'*5),
            ),
        ],
      ),
    );
    if (isolate) {
      animatedChild = RepaintBoundary(
        key: ValueKey<bool>(alternate),
        child: animatedChild,
      );
    }
    return Column(
      children: <Widget>[
        Container(height: 100),
        TextButton(onPressed: _switchChild, child: const Text('Switch child')),
        AnimatedSwitcher(
          duration: const Duration(seconds: 2),
          child: animatedChild,
        ),
        TextButton(onPressed: _toggleIsolation, child: Text('${isolate ? 'Remove' : 'Add'} RepaintBoundary')),
      ],
    );
  }
}
```
</details>

**Comment by flar** [comment]
In your second example, we're not just throwing away the texture used by the opacity in raster caching, we're throwing away the entire opacity layer and creating a new one from scratch.

Adding a RepaintBoundary around the child of the SlideTransition should fix this. Note that RepaintBoundary would include the OpacityLayer inside it.

Here is the example again with a button to toggle adding a RepaintBoundary around it which makes it run smoother and doesn't thrash the cache.

<details>
  <summary>Click to expand!</summary>
  
```
import 'package:flutter/material.dart';

void main() {
  runApp(const MaterialApp(
    checkerboardRasterCacheImages: true,
    home: Scaffold(
      body: Example(),
    ),
  ));
}

class Example extends StatefulWidget {
  const Example({Key? key}) : super(key: key);

  @override
  State<Example> createState() => _ExampleState();
}

class _ExampleState extends State<Example> with TickerProviderStateMixin {
  late final AnimationController _controller = AnimationController(vsync: this, duration: const Duration(seconds: 1));
  late final Animation<Offset> _position = _controller.drive(
      Tween(begin: const Offset(0.0, 0.0), end: const Offset(1, 1.0)));

  bool isolate = false;

  void _toggleIsolation() {
    setState(() {
      isolate = !isolate;
    });
  }

  @override
  void initState() {
    super.initState();
    _controller.reset();
    _controller.forward();
    _controller.addStatusListener((status) {
      if (status == AnimationStatus.completed) {
        _controller.reset();
        _controller.forward();
      }
    });
  }

  @override
  Widget build(BuildContext context) {
    Widget animatedChild = Opacity(
      opacity: 0.9,
      child: Container(
        child: Column(
          children: <Widget>[
            Container(
              width: 200,
              height: 200,
              color: Colors.red,
              child: const Text('A'),
            ),
          ],
        ),
      ),
    );
    if (isolate) {
      animatedChild = RepaintBoundary(child: animatedChild);
    }
    return Column(
      children: <Widget>[
        Container(height: 100),
        TextButton(onPressed: _toggleIsolation, child: Text('${isolate ? 'Remove' : 'Add'} RepaintBoundary')),
        SlideTransition(
          position: _position,
          child: animatedChild,
        ),
      ],
    );
  }
}
```
</details>

**Comment by jonahwilliams** [comment]
Definitely, I investigated adding the repaint boundary but I wasn't satisfiied with that solution because I suspect that there are more cases in the framework or third party code where we're missing repaint boundary like behavior. Thus I've started investigating whether we can make more Render Objects behave like repaint boundaries. (https://github.com/flutter/flutter/issues/101941) It doesn't quite work yet, but with that change it is possible to avoid rebuild without adding another layer - which triggers the case where we drop the raster cache entries of the displayListLayer on the floor
