### ISSUE TITLE
keytool can't find JDK

### ISSUE THREAD

**Issue by wmleler** [flutter/flutter#10158]
New installation of Flutter. When you go to use keytool, you get an error because the JDK cannot be found.

**Comment by mit-mit** [comment]
Can you clarify? Don't believe keytool is part of flutter...

**Comment by wmleler** [comment]
keytool could not find the Java JDK, not Flutter.

**Comment by mit-mit** [comment]
Right, but `keytool` isn't our binary, so can you clarify how this is a Flutter issue?

**Comment by wmleler** [comment]
Mainly because the Flutter documentation tells you how to build an Android
APK and it doesn't work.

**Comment by mit-mit** [comment]
Ah, got it, yes we can improve docs.
