### ISSUE TITLE
I wish for a plugin sample with Kotlin

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#10150]
Similar to how we have an example with ObjC and Swift, we could now look at producing a sample/example of a Kotlin plugin.

Thanks!

**Comment by sethladd** [comment]
cc @mit-mit

**Comment by mit-mit** [comment]
Related bug for iOS/Swift: https://github.com/flutter/flutter/issues/7312

**Comment by eseidelGoogle** [comment]
@lukef is currently experimenting with this as well.

**Comment by mravn-google** [comment]
https://github.com/flutter/flutter/pull/10259 makes `flutter create` create language-specific starter projects with any choice of ObjC/Swift for iOS and Java/Kotlin for Android. Do we still want a separate Kotlin example?

**Comment by eseidelGoogle** [comment]
Sounds like a reasonable place to start.  Feel free to close this.  That means that `flutter create --plugin -al kotlin` uses kotlin?

**Comment by mravn-google** [comment]
That's the idea. Also without the `--plugin`

...except we are not allowed to have two-letter abbreviations.

**Comment by eseidelGoogle** [comment]
It seems this bug is about the --plugin part, no?

**Comment by mravn-google** [comment]
Yes. And #10259 allows the user to create a Kotlin plugin project. It also allows the user to create a normal Flutter project with a `MainActivity` implemented in Kotlin. Similarly for Swift vs ObjC on iOS.

**Comment by mravn-google** [comment]
Closing per #10259
