### ISSUE TITLE
Getting black screen when open the application running in background

### ISSUE THREAD

**Issue by Yuvaraj-Gajaraj** [flutter/flutter#101673]
## Details

1. Run the below-attached sample, then minimize the application and wait for 30 sec then reopen the application.

2. [custompaintersample.zip](https://github.com/flutter/flutter/files/8459775/custompaintersample.zip)

3. In this sample, we have added the `CustomPaint` widget to a list and wrapped this list of widgets in the `SingleChildScrollView` and Column widget. Here, we have added the `CustomPaint` widget into the list in some time intervals using the `Timer` and rendered the widget. After that, we minimized the application, then reopened it after 30 - 40 sec it shows the black screen and then renders a CustomPaint widget. While analyzing this we found that the Paint method in CustomPaint is not called in the background, but the widget was added to the list while in the background. The paint method gets called only after reopening the application, so we suspect that it is because of paint method is called n number of times for the added widgets when reopening the application. If so can you please help me with how to overcome this.

Screen Record:

https://user-images.githubusercontent.com/61863686/162637849-f74a3918-df14-4d6f-9e7d-cc45330f3355.mp4

## Logs

<details>
<summary>Logs</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.10.3, on Microsoft Windows [Version 10.0.19042.1586], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.2)
[√] Android Studio (version 4.1)
[√] VS Code (version 1.66.1)
[√] Connected device (5 available)
[√] HTTP Host Availability

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
@Yuvaraj-Gajaraj 
From the code you shared, you seem to be using https://pub.dev/packages/flutter_background which is third party plugin. Does the behavior persists without using this plugin's code and only using core framework code ?
If so, please provide complete updated minimal code sample that shows the black screen issue or if it only happens with plugin code added, you might need to open this issue in dedicated repo.
