### ISSUE TITLE
MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences)

### ISSUE THREAD

**Issue by Julianlu1** [flutter/flutter#101635]
I am trying to use shared preferences in a background handler (when receiving a notification and using Firebase Cloud Messaging). However, I get the error message that it could not find an implementation of shared_preferences. I read on Github that in the beta version you have 2 options.

Option 1
DartPluginRegistrant.ensureInitialized();
The above is only for Flutter 2.11+ and is not in the release version yet.

Option 2
Add dependencies on shared_preferences_android and shared_preferences_ios.
At the beginning of your background isolate entry point, add something like:
if (Platform.isAndroid) SharedPreferencesAndroid.registerWith();
if (Platform.isIOS) SharedPreferencesIOS.registerWith();

I want to go for option 2, but I do not know where to put those lines of code. Also, does this mean I have to add 2 new dependencies? I already have the original shared preferences package installed.

Here is the Github Flutter issue: https://github.com/flutter/flutter/issues/98473#issuecomment-1041895729

Thanks for your help!

**Comment by stuartmorgan** [comment]
Please use one of the resources at https://flutter.dev/community#community-grid for help with your own code. The issue tracker is specifically for bug reports and feature requests.

> I do not know where to put those lines of code

That's explained in the comment you linked to. There's no way to be more specific without someone looking at your specific use case, which would be of topic here.

> does this mean I have to add 2 new dependencies?

That is answered in the comment you linked to as well.

**Comment by Julianlu1** [comment]
@stuartmorgan Hey, I finally understood the comment. You were right. However I do have a bug. Now it can find sharedpreferences but it does not find Platform.localeName in the backgroundhandler. I think I should open a new issue for this right?
