### ISSUE TITLE
Flutter: How can I verify that the string entered by the user in the chat is a link?

### ISSUE THREAD

**Issue by mycar98765** [flutter/flutter#101629]
I'm making a chat app with Flutter. Recently encountered a problem, the question is **how can I verify that the string entered by the user in the chat is a link?** I referred [Dart / Flutter - Validating a string for URL](https://stackoverflow.com/questions/52975739/dart-flutter-validating-a-string-for-url/58239541#58239541), but when I type "`google.com`" it shows me false. When I type "`www.google.com`" it shows me false. When I type "`https://www.google.com/`" it shows me true. How can I fix this problem? I will be grateful when some users help me with this problem.

**Comment by stuartmorgan** [comment]
Please use one of the resources at https://flutter.dev/community#community-grid for help with your own code.

**Comment by mycar98765** [comment]
@stuartmorgan, https://flutter.dev/community#community-grid didn't help me.

**Comment by mycar98765** [comment]
@stuartmorgan, can you open my issue?

**Comment by mycar98765** [comment]
I found a solution! I use [validators](https://pub.dev/packages/validators) to solve this problem. Here's an example from someone who had the same problem as me:
```
import 'package:validators/sanitizers.dart';
import 'package:validators/validators.dart';

main() {
  print(toString(1));
  print(trim('  hello '));
  print(toDouble('1.23'));

  print(isDate('1988-01-01'));
  print(isNumeric('123'));
  print(isAlphanumeric('abc123'));
  print('isUrl: ${isURL('example', requireTld: false)}');
}
```
