### ISSUE TITLE
[Fonts] Icon request: whatsapp

### ISSUE THREAD

**Issue by subair-zufi** [flutter/flutter#101621]
WhatsApp became most common to all Android/ iOS users. Adding an icon for WhatsApp will reduce time of importing image manually and maintaining it's size and alignment manually.

**Comment by danagbemava-nc** [comment]
Hi @subair-zufi, the `whatsapp` icon already exists on the stable channel. See https://api.flutter.dev/flutter/material/Icons/whatsapp-constant.html.

Closing as the icon already exists.
