### ISSUE TITLE
Crash when returning StreamHandlerError on Windows

### ISSUE THREAD

**Issue by swift-kim** [flutter/flutter#101682]
## Steps to Reproduce

1. Download the [connectivity_plus](https://github.com/fluttercommunity/plus_plugins/tree/main/packages/connectivity_plus) plugin source code on a Windows machine.
2. Modify `connectivity_plus_windows_plugin.cpp` as follows to simulate a platform error. This makes sure that the constructor of `StreamHandlerError<>` is called.

   ```patch
   --- a/packages/connectivity_plus/connectivity_plus_windows/windows/connectivity_plus_windows_plugin.cpp
   +++ b/packages/connectivity_plus/connectivity_plus_windows/windows/connectivity_plus_windows_plugin.cpp
   @@ -143,7 +143,7 @@ ConnectivityStreamHandler::OnListenInternal(
      auto callback =
         std::bind(&ConnectivityStreamHandler::AddConnectivityEvent, this);

   -  if (!manager->StartListen(callback)) {
   +  if (manager->StartListen(callback)) {
      return std::make_unique<FlStreamHandlerError>(
            std::to_string(manager->GetError()), "NetworkManager::StartListen",
            nullptr);
   ```

3. Run the example app (`connectivity_plus/example`).

**Expected results:**

Prints a Dart exception.

```
══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞══════════════════════════════════════════════════════════
The following PlatformException was thrown while activating platform stream on channel
dev.fluttercommunity.plus/connectivity_status:
PlatformException(0, NetworkManager::StartListen, null, null)

When the exception was thrown, this was the stack:
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:177:18)
<asynchronous suspension>
#2      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:516:9)
<asynchronous suspension>
════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Actual results:**

Program aborted.

<img width="345" src="https://user-images.githubusercontent.com/40190588/162676867-78311126-81d3-4fbb-8939-7d8f5788afbd.png">

## What's the cause?

As you can see in the C++ client wrapper's [event_stream_handler.h](https://github.com/flutter/engine/blob/78da81534b3a0bb6dcb495d50f82bc4dbfcab3bc/shell/platform/common/client_wrapper/include/flutter/event_stream_handler.h#L16-L17), `StreamHandlerError` stores only the references to `error_code` and `error_message`, and the actual values must be retained by the caller of the API until the error information is sent to the framework. However, it is very natural for users of the API to expect that the strings are **copied by value** when the constructor of `StreamHandlerError` is called.

A temporary fix is to simply remove `&` from the code as follows, just like `name_` of [BasicMessageChannel](https://github.com/flutter/engine/blob/78da81534b3a0bb6dcb495d50f82bc4dbfcab3bc/shell/platform/common/client_wrapper/include/flutter/basic_message_channel.h#L104).

```patch
--- a/shell/platform/common/client_wrapper/include/flutter/event_stream_handler.h
+++ b/shell/platform/common/client_wrapper/include/flutter/event_stream_handler.h
@@ -13,8 +13,8 @@ class EncodableValue;

 template <typename T = EncodableValue>
 struct StreamHandlerError {
-  const std::string& error_code;
-  const std::string& error_message;
+  const std::string error_code;
+  const std::string error_message;
   const T* error_details;

   StreamHandlerError(const std::string& error_code,
```

<details>
  <summary>Logs</summary>

```
> flutter doctor -v
[✓] Flutter (Channel unknown, 2.10.1, on Microsoft Windows [Version 10.0.19043.1526], locale ko-KR)
    • Flutter version 2.10.1 at E:\flutter\flutter-tizen\flutter
    • Upstream repository unknown
    • Framework revision db747aa133 (9 weeks ago), 2022-02-09 13:57:35 -0600
    • Engine revision ab46186b24
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Professional 2019 16.10.0)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional
    • Visual Studio Professional 2019 version 16.10.31321.278
    • Windows 10 SDK version 10.0.22000.0

[✓] VS Code, 64-bit edition (version 1.65.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19043.1526]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 100.0.4896.60
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 99.0.1150.39

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
> 1. Download the [connectivity_plus](https://github.com/fluttercommunity/plus_plugins/tree/main/packages/connectivity_plus) plugin source code on a Windows machine.

Does it only happen using this plugin ? Since this is a community plugin and not Flutter's 1P plugin, I am wondering if the crash occurs using any Flutter's first party plugin.

**Comment by swift-kim** [comment]
@darshankawar It happens whenever the `StreamHandlerError` constructor is called but currently there's no 1st-party plugin that uses the API.

**Comment by stuartmorgan** [comment]
This is indeed very broken :( I'm not sure how I missed this in review; I suspect it's because it matches the error call signature for the codec, and not being familiar with the event stream API I somehow didn't notice that this is designed for returning, not as arguments.

Because this is a struct rather than an interface class, I don't see any way we can fix this without it being a hard breaking change, unfortunately. That will be pretty unfortunate for any plugins using this. On the other hand, this is so broken that I'm having a hard time seeing how anyone could successfully be using it, so a breaking change may not actually have much impact.

@cbracken Thoughts?

**Comment by stuartmorgan** [comment]
It's not just the strings, the details needs to be a `unique_ptr`.

**Comment by stuartmorgan** [comment]
> except the two community maintained plugins, battery_plus_windows and connectivity_plus_windows

I missed that this was about a live version of the Plus Plugins. We'd need to figure how to mitigate that breakage.

**Comment by stuartmorgan** [comment]
Actually, it still might not actually break any existing code (or at least almost none). The wrapper code itself may well be the only code that's actually *reading* this error class even though it's public API, so we probably only need to worry about the constructor. And fixing `details` is only a breaking change for non-null values; it looks like at least those plugins are always returning `nullptr`.

Checking [all plugins on GitHub](https://github.com/search?l=C%2B%2B&q=StreamHandlerError+-%22using+StreamHandlerCancel%22+-%22Implementations+should+ideally+consume%22+-EventChannelTest+-%22requests+for+event+stream+setup%22&type=Code), I could only find two other plugins that ever actually created a `StreamHandlerError`, and they also used `nullptr` for details, so we may be in luck here.

**Comment by swift-kim** [comment]
Another related issue: The header file (`event_stream_handler.h`) is also missing `<memory>` and `<string>` includes.

**Comment by swift-kim** [comment]
@yaakovschectman Hi. The crash seems to be fixed thanks to your patch, but now I'm getting this error during my custom embedder build:

https://github.com/flutter-tizen/embedder/actions/runs/4989866016/jobs/8934357267?pr=36
```cpp
In file included from ../../flutter/shell/platform/tizen/channels/app_control_channel.h:13:
../../flutter/shell/platform/common/client_wrapper/include/flutter/event_channel.h:95:27: error: invalid operands to binary expression ('basic_ostream<char>' and 'const std::unique_ptr<EncodableValue>')
                          << (error->error_details);
                          ^  ~~~~~~~~~~~~~~~~~~~~~~
```

The embedder depends on an old libcxx for a technical reason. It seems the `operator<<` overload of `std::uniqut_ptr` is not a legal C++17 standard:

https://en.cppreference.com/w/cpp/memory/unique_ptr/operator_ltlt

I think `.get()` could be added at line 95 of `event_channel.h` or even the line can be removed. What do you think?

**Comment by stuartmorgan** [comment]
> The embedder depends on an old libcxx for a technical reason. It seems the `operator<<` overload of `std::uniqut_ptr` is not a legal C++17 standard

FYI the client wrapper targets VS 2019, which supports C++20, so in general anyone writing on that code is going to assume C++20 support (especially once the engine as a whole moves to C++20). If you are staying in C++17 in the longer term you will likely need to fork it for your use case.

**Comment by stuartmorgan** [comment]
It looks like we just forgot to close this when the PR landed.
