### ISSUE TITLE
skia->flutter autoroller blocked on failed "Removing stale iOS 13.0.simruntime"

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#101603]
We are now 16 commits behind.

log:
```
Step('Removing stale iOS 13.0.simruntime') failed 'EPERM' with: [Errno 1] Operation not permitted: '/opt/s/w/ir/cache/osx_sdk/XCode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 13.0.simruntime'
```

Example failure:
https://ci.chromium.org/ui/p/flutter/builders/try/Mac%20Android%20AOT%20Engine/29554/overview

**Comment by jmagman** [comment]
@godofredoc

**Comment by godofredoc** [comment]
@gaaclarke can you please expand on what commits behind mean? skia rolls, dart sdk rolls?

**Comment by godofredoc** [comment]
By the way I landed a changes ~2:00PM PST to fix this type of problem and it seems like the new builds are all passing https://ci.chromium.org/p/flutter/builders/try/Mac%20Android%20AOT%20Engine

**Comment by godofredoc** [comment]
Uppps, I took a look at the comment only and I didn't read the title. Checking the skia rollers

**Comment by godofredoc** [comment]
Fixed with https://flutter-review.googlesource.com/c/recipes/+/28684
