### ISSUE TITLE
Add to Image.network an event when the image is ready to display 

### ISSUE THREAD

**Issue by Kleak** [flutter/flutter#10166]
It could be cool that Image.network send an event when the image is ready to display.

**Comment by eseidelGoogle** [comment]
What's the effect you're seeking to achieve?  Note that https://github.com/FaisalAbid/pluto exists for showing placeholder images if that's your goal.

**Comment by eseidelGoogle** [comment]
This also sounds similar to https://github.com/flutter/flutter/issues/5741

**Comment by Kleak** [comment]
In fact i try to show a loader instead of a pack of image and not just one
image

**Comment by Kleak** [comment]
Yes exactly

**Comment by zoechi** [comment]
I'm going to close as Duplicate of #9676 (and #5741)
See also https://github.com/flutter/flutter/issues/16592#issuecomment-427179863
