### ISSUE TITLE
Add documentation on making changes to a new Flutter app

### ISSUE THREAD

**Issue by wmleler** [flutter/flutter#10164]
After the user goes through https://flutter.io/getting-started/ it would be really helpful if you have them make a few interesting changes to the default app, just to show them how easy it is to start building an app. You already make a change to show off hot reload, but I'm talking about something more significant, which would require adding additional code.

**Comment by mit-mit** [comment]
I believe @sethladd is looking into this

**Comment by sethladd** [comment]
It's not on my plate or on my radar right now, but I agree that moving from Getting Started into a mini tutorial is a great idea.

**Comment by Sfshaza** [comment]
Yes, this could be a page after "Test drive" and before "Write Your First Flutter app".

**Comment by zoechi** [comment]
Issue moved to [flutter/website #1996](https://github.com/flutter/website/issues/1996) via [**ZenHub**](https://www.zenhub.com/)
