### ISSUE TITLE
Error when creating new app

### ISSUE THREAD

**Issue by alex9153** [flutter/flutter#101630]
When I create new project I receive this error:

FAILURE: Build failed with an exception.

* What went wrong:
Could not open settings generic class cache for settings file '[/Users/aleks/Projects/Flutter/yandex_test/android/settings.gradle]()' ([/Users/aleks/.gradle/caches/6.7/scripts/f0emg6u6oecmxqzgk5g9nn4ui]()).
> BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 61

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at [https://help.gradle.org]()

BUILD FAILED in 531ms
Exception: Gradle task assembleDebug failed with exit code 1

___________________

[flutter] flutter doctor -v
[✓] Flutter (Channel stable, 2.10.4, on macOS 12.2 21D49 darwin-x64, locale ru-RU)
    • Flutter version 2.10.4 at /Users/aleks/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (2 weeks ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/aleks/Library/Android/sdk
    • Platform android-32, build-tools 32.0.0
    • ANDROID_HOME = /Users/aleks/Library/Android/sdk
    • Java binary at: /Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_321-b07)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code (version 1.64.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.38.1

[✓] Connected device (3 available)
    • ZB602KL (mobile) • J6AXB7654974VZ8 • android-arm64  • Android 9 (API 28)
    • SM T970 (mobile) • R52N71EFXPN     • android-arm64  • Android 12 (API 31)
    • Chrome (web)     • chrome          • web-javascript • Google Chrome 100.0.4896.75

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Comment by alex9153** [comment]
related error:


Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugMainManifest'.
> Unable to make field private final java.lang.String java.io.File.path accessible: module java.base does not "opens java.io" to unnamed module @3aa7b774

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 11s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by Srivatsa10** [comment]
What's your current java version?

**Comment by darshankawar** [comment]
> BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 61



> Unable to make field private final java.lang.String java.io.File.path accessible: module java.base does not "opens java.io" to unnamed module @3aa7b774

As the error says `Unsupported class file major version 61`, it indicates that the class file is trying to load has been compiled by Java 17 or 17+ version.

Currently, it seems Android toolchain support only classes compiled for Java 11 and hence the error. For it to run properly, you'll need to use Java 11 jdk version. Also this isn't specific to Flutter, a native android app might throw the same error.

With this, I am going ahead and closing this as it is not specific to Flutter and the change might have to come from Android toolchain that Flutter can consume so that the app can run using Java 17.
