### ISSUE TITLE
Automate the signing of Android apps (keytool, gradle files)

### ISSUE THREAD

**Issue by wmleler** [flutter/flutter#10162]
Would be nice if we could automate the process of using keytool and updating project files in order to sign a new Android app.

**Comment by sethladd** [comment]
Related, I'd love to get analytics about where people fall off installing/getting started. Is it signing? Is it download Android Studio? etc...

**Comment by zoechi** [comment]
Somewhat related https://github.com/flutter/flutter-intellij/issues/3042

**Comment by jonahwilliams** [comment]
This is obsolete via the switch to gradle
