### ISSUE TITLE
Camera error when integrating flutter to existing android app.  

### ISSUE THREAD

**Issue by HieuNT1998** [flutter/flutter#101643]
I'm trying to build a flutter template that integrates into android. My app is camera app.  If I start my template with method 1 the application works.
<img width="896" alt="Screen Shot 2022-04-10 at 00 26 52" src="https://user-images.githubusercontent.com/40411081/162584875-d5858d40-e23e-4953-bb04-1801ba1ae3f0.png">

But if I use cache flutterEngine, I get camera error: 
<img width="1354" alt="Screen Shot 2022-04-10 at 00 29 37" src="https://user-images.githubusercontent.com/40411081/162584962-9bd9db19-873c-49e0-b882-60293efc08e9.png">

my source code: 
<img width="903" alt="Screen Shot 2022-04-10 at 00 28 15" src="https://user-images.githubusercontent.com/40411081/162584925-178c03f1-92df-4232-a72e-963a165df057.png">

Flutter doctor:
<img width="910" alt="Screen Shot 2022-04-10 at 00 30 49" src="https://user-images.githubusercontent.com/40411081/162584996-4074334f-9195-4475-835a-d0277bce8457.png">

Thanks

**Comment by stuartmorgan** [comment]
You haven't registered any plugins with the engine you created; if you are managing the engine instance yourself plugin registration is left to you to manage, [per the docs](https://github.com/flutter/engine/blob/7acec05e90011a6ea61c81bbda2c8f182aaa88e9/shell/platform/android/io/flutter/embedding/android/FlutterActivity.java#L1070-L1082).

Closing as this is the expected behavior.

**Comment by HieuNT1998** [comment]
Thanks @stuartmorgan 

I tried adding " GeneratedPluginRegister.registerGeneratedPlugins(flutterEngine); "
in my code but it still doesn't work.

This is my source image: 
<img width="832" alt="Screen Shot 2022-04-10 at 12 41 59" src="https://user-images.githubusercontent.com/40411081/162604329-9ae07623-d00e-481c-af66-bac8e666a017.png">


Android Config: 
minSdk: 21
targetSdk: 31 
compileSdk: 31

Maybe I'm misunderstanding what you mean. Can you explain more to me or give me more reference.

**Comment by HieuNT1998** [comment]
Also I have tried extending flutterActiviy and overriding the configureFlutterEngine funtion. But when I do startActivity I see the app doesn't execute the configureFlutterEngine function.

Here is my source code: 
CustomFlutterActivity
<img width="832" alt="Screen Shot 2022-04-10 at 12 54 29" src="https://user-images.githubusercontent.com/40411081/162604436-195a1545-a0c5-4535-8099-c2a51719b871.png">

StartActivity
<img width="842" alt="Screen Shot 2022-04-10 at 12 55 48" src="https://user-images.githubusercontent.com/40411081/162604446-5a794a5a-0c82-4e50-a8a9-77c62ba714e5.png">

**Comment by stuartmorgan** [comment]
Re-opening for triage with the updated code.

**Comment by darshankawar** [comment]
I believe this is same as https://github.com/flutter/flutter/issues/89500, so please follow-up in it for further updates.
Closing this as a duplicate.
