### ISSUE TITLE
Questions about Flutter for web

### ISSUE THREAD

**Issue by ylrs** [flutter/flutter#101688]
Requirements: App project developed by Flutter, converted to Web project via Flutter for Web, but eventually running in App

There are many plugins for the conversion of the Flutter App project to the Web, including two types of plugins:
1. Business plugin:
Obtain native basic information through plugin
Implement native logic via plugin
...

2. System plugin:
Such as platform judgments, system life cycles, keyboard events, and so on
flutter/platform
flutter/textinput
flutter/lifecycle
flutter/system
flutter/settings
...

These plugins are not available after a Flutter for Web conversion.
So we allowed the project to run properly in App after being transformed by Flutter for Web.

Also, the positioning of Flutter for Web is based on browser usage. Can't communicate with the App via plugin?

Is there any consideration in this regard?

中文:

需求:  Flutter开发的App项目, 通过Flutter for web转换为web项目,  但最终运行在App中

Flutter App项目转换为web的场景,存在大量plugin,包含两种plugin:
1.业务plugin:
通过plugin获取native基础信息
通过plugin执行native逻辑等等

2.系统plugin:
比如平台判断,系统生命周期,键盘事件等等,如下
flutter/platform    
flutter/textinput
flutter/lifecycle
flutter/system
flutter/settings
等等

这些plugin 在Flutter for web转换后无法使用.
那么我们让项目通过Flutter for web转换后依然能在App中正常运行.

还是说Flutter for web的定位是基于浏览器使用的.无法通过plugin和App交互?

是否有这方面的考虑?

**Comment by ylrs** [comment]
@darshankawar 
Suppose I have a Flutter page, didChangeAppLifecycleState method was used to monitor the lifecycle of the App, then converted into a web page, didChangeAppLifecycleState listening was invalid, what should I do?
Similarly, the following plugins are available:
flutter/platform
flutter/textinput
flutter/lifecycle
flutter/system
flutter/settings

**Comment by darshankawar** [comment]
> didChangeAppLifecycleState listening was invalid, what should I do?

Please follow-up in this open issue for further updates. https://github.com/flutter/flutter/issues/53107

Closing this as a duplicate.
