### ISSUE TITLE
flutter plugin android Multi module error

### ISSUE THREAD

**Issue by libra1010** [flutter/flutter#101651]
df
sdf
use as create a flutter plugin project
run example main.dart success
But when I use as to open the Android directory, I create a new module
buid.gradle add
implementation project(':moudleName')
Re execute
tips: Project with path ':moduleName' could not be found in project ':lpy_demo'.
I try to use pub Dev plug-in

hyper_ lpr

The error is still prompted. The plug-in is a multi module Android projec

flutter --version
Flutter 2.10.4 • channel stable • https://github.com/flutter/flutter.git
Engine • revision 57d3bac3dd
Tools • Dart 2.16.2 • DevTools 2.9.2

**Comment by darshankawar** [comment]
@libra1010 
Can you provide proper and complete error log that shows the issue ?
