### ISSUE TITLE
Check for proper versions of dependencies

### ISSUE THREAD

**Issue by wmleler** [flutter/flutter#10161]
The flutter doctor should check to make sure the user has recent enough versions of Android Studio, Xcode, etc.

While installing Flutter, I ran into a problem where I used the Google Managed Software Center to install Android Studio and Xcode, and it installed very old versions that caused errors.

**Comment by mit-mit** [comment]
@devoncarew I thought we checked for this already?

**Comment by devoncarew** [comment]
This was fixed after this issue was filed - looks like we had duplicate issues (https://github.com/flutter/flutter-intellij/issues/1054).
