### ISSUE TITLE
[flutter] Build is failing

### ISSUE THREAD

**Issue by rahulvyas** [flutter/flutter#101657]
Hi All,

I am trying to build the app using the following command

`flutter build ios -t lib/main_dev.dart`

I'm using a M1 mac so I want to run the pod install command using the following command
`arch -x86_64 pod install`

How I can merge both commands? Is there any place to update where pod install will always be executed with the above command?

Also, I'm getting this error, even though I already have valid code signing and I also have automatic manage signing in XCode.

```
It appears that your application still contains the default signing identifier.
Try replacing 'com.example' with your signing id in Xcode:
  open ios/Runner.xcworkspace
Encountered error while building for the device.
```

**Comment by darshankawar** [comment]
@rahulvyas 
Since you seem to be running flavor based app, you'll probably need to set the signing identifier for each flavor. Currently you may have set the sigining identifier for default `debug` mode, but for each flavor, you'll need to do the same. Please try that and see if it helps.

**Comment by rahulvyas** [comment]
@darshankawar flavors are only in dart code not in IOS or Android code. I have already set the signing identifier using `(flutter config ios-signing-cert)`. Sometimes it works after this command. Sometimes I again get the same error. Also, do you know how we can run the pod install command merged with flutter build -t command
