### ISSUE TITLE
[google_sign_in] Using dart only initialization not working in ios.

### ISSUE THREAD

**Issue by iamsannyrai** [flutter/flutter#101655]
I have used dart only initialization targeting two firebase project (considering one as secondary app). 

I have used google sign in with this new approach. It is working fine in android platform but in ios side, an exception is thrown mentioning missing_config (GoogleService-Info.plist).

**Comment by darshankawar** [comment]
@iamsannyrai 
`google_sign_in` doesn't support Dart-only initialization yet, so we still need the manual installation if the app uses Google sign in. Also check this issue for further reference: https://github.com/flutter/flutter/issues/96391

Closing as duplicate.
