### ISSUE TITLE
IOS Flutter 2.10 version with Microsoft Intune Wrapping tools issue.

### ISSUE THREAD

**Issue by AceChen1** [flutter/flutter#101683]
Hi guys, now us project use Microsoft Intune Wrapping tools to do the MAM, Before 2.10, we found Microsoft Intune Wrapping tools login and flutter run flow is : app willFinishLaunchingWithOptions delegate -> Intune AAD login  -> dart's main function, but after 2.10, we found the flow change , the Intune AAD login & dart's main function will call on the same time, May i know any change on the flutter 2.10 version?  Have any way we can let the Intune AAD login first and then run the dart's main function ?

https://docs.microsoft.com/en-us/mem/intune/developer/app-wrapper-prepare-ios

**Comment by darshankawar** [comment]
@AceChen1 
I can't find anything related to Intune AAD login in 2.10 release [notes](https://docs.flutter.dev/development/tools/sdk/release-notes/release-notes-2.10.0) and change log, so I am not quite sure.
To get faster resolve your question, I suggest you to ask this question on Flutter discord where you can get direct answers from flutter team members.
I am closing this for now.

**Comment by AceChen1** [comment]
> @AceChen1 I can't find anything related to Intune AAD login in 2.10 release [notes](https://docs.flutter.dev/development/tools/sdk/release-notes/release-notes-2.10.0) and change log, so I am not quite sure. To get faster resolve your question, I suggest you to ask this question on Flutter discord where you can get direct answers from flutter team members. I am closing this for now.

Hi @darshankawar , i think it related the IOS performance tuning on the Flutter 2.10 version.

**Comment by darshankawar** [comment]
Thanks for the feedback. Reopening.

**Comment by AceChen1** [comment]
> This may be related to some recent changes around entrypoints, but I don't remember whether they were before or after 2.10. Maybe @gaaclarke knows?

hello @gaaclarke, may i know can you help to check check?

**Comment by AceChen1** [comment]
> This may be related to some recent changes around entrypoints, but I don't remember whether they were before or after 2.10. Maybe @gaaclarke knows?

Hello @zanderso , may i know the issue is following and checking?

**Comment by stuartmorgan** [comment]
Closing; applications that have very specific timing requirements at startup should explicitly set up and run the engine at the desired time rather than rely on internal timing details.
