### ISSUE TITLE
Miss icon "google" for login with google

### ISSUE THREAD

**Issue by chinhlc** [flutter/flutter#101640]
I see you miss icon "Google". Can you update it?

**Comment by maheshmnj** [comment]
Hi @chinhlc, Thanks for filing the issue.  The icon you are suggesting doesn't seem to be a material icon and hence it cannot be included in the material library.

<img width="1128" alt="image" src="https://user-images.githubusercontent.com/31410839/162713473-f54d17ce-68ae-441c-86e0-4531663ff962.png">

Closing as this isn't a valid feature request. In case you disagree feel free to write in the comments and we will reopen it.
 
Thank you.
