### ISSUE TITLE
[shared_preferences] Document the need to use `reload` when using multiple isolates or engines

### ISSUE THREAD

**Issue by Julianlu1** [flutter/flutter#101691]
I am working on this Flutter app and I have implemented Firebase Cloud Messaging. I added the following code to make sure I can use the Shared Preferences package. It seems to work, but the functionality does not work correctly.

```dart
if (Platform.isAndroid) SharedPreferencesAndroid.registerWith();
  if (Platform.isIOS) SharedPreferencesIOS.registerWith();
```
The backgroundhandler in action:
```dart
Future<void> backgroundHandler(RemoteMessage message) async {
  await Firebase.initializeApp();
  if (Platform.isAndroid) SharedPreferencesAndroid.registerWith();
  if (Platform.isIOS) SharedPreferencesIOS.registerWith();
  print("App is in background: Message received ");

 String productId = message.data['productId'];
 SendPort mainToIsolateStream = (await initIsolate()) as SendPort;
  final prefs = await SharedPreferences.getInstance();

  final listOfTopics = prefs.getStringList('out_of_stock_topics') ?? [];
  print('BEFORE unsubscribe, print list of topics: $listOfTopics');
  // Returns locale string in 'en_US'
  // String defaultLocale = Platform.localeName;
  String defaultLocale = prefs.getString('language') ?? "";
  String topic = '${productId}_$defaultLocale';
  print('The topic: ${topic}');
  print("The list of topics: ${listOfTopics}");
  // Check if topic already exists
  if (listOfTopics.contains(topic)) {
    print("Topic deleted");
    LocalNotificationService.unsubscribeToTopic(topic);
    listOfTopics.remove(topic);
    print(listOfTopics.length);
    await prefs.setStringList('out_of_stock_topics', listOfTopics);
  }
}
```

The code above deletes the topic in the list. Then the list is set with prefs.setStringList. I checked, and the code goes into the if statement. It removes the item from the list. But something goes wrong in prefs.setStringList I suppose.

Because later I use the following code to check the items in the 'out_of_stock_topics' list.
```dart
 final prefs = await SharedPreferences.getInstance();
                final listOfTopics =
                    prefs.getStringList('out_of_stock_topics') ?? [];
                print(listOfTopics);
```
But the topic is not correctly deleted and is still there. I think there is something wrong in the backend of the backgroundhandler. I tested this feature with 2 buttons: "add topic" and "delete topic". And with those separate buttons it does delete the item from the 'out_of_stock_topics' list.

Does anyone know how to fix this problem?
Thanks!

**Comment by maheshmnj** [comment]
Hi @Julianlu1, Thanks for filing the issue.

If I am not wrong, `backgroundHandler` function is being executed when the app is in background (terminated state) 
and you are checking the modified string list, When the app is in foreground is that correct?

> final prefs = await SharedPreferences.getInstance();
                final listOfTopics =
                    prefs.getStringList('out_of_stock_topics') ?? [];
                print(listOfTopics);



if so, I think this is because `backgroundhandler` is executed in a separate isolate (not the main isolate) as mentioned in the [firebase docs](https://firebase.flutter.dev/docs/messaging/usage/).  Since each isolate has its own memory the output is intended.

> Handling messages whilst your application is in the background is a little different. Messages can be handled via the [onBackgroundMessage](https://pub.dev/documentation/firebase_messaging/latest/firebase_messaging/FirebaseMessaging/onBackgroundMessage.html) handler. When received, an isolate is spawned (Android only, iOS/macOS does not require a separate isolate) allowing you to handle messages even when your application is not running.

This issue doesn't seem related to SharedPreference, You can verify this by fecthing the modified list after the update in `backgroundHandler` method. Or if you have a IOS device your code should work just fine since `backgrondHandler` seems to run in the same isolate as mentioned in the docs.

>  When received, an isolate is spawned (Android only, iOS/macOS does not require a separate isolate) allowing you to handle messages even when your application is not running.

 Please share the output of `flutter doctor -v` along with a minimal and complete code sample to investigate this further.

**Comment by stuartmorgan** [comment]
> This issue doesn't seem related to SharedPreference

This is specific to `shared_preferences`; it has a per-instance cache that's created at initialization time, which causes this effect when accessed from different isolates. The main isolate needs to call `reload` after foregrounding in an application that is making changes in background isolates.

I think it's worth adding discussion of this use case to the README, as well as updating the API docs of `reload` (which currently only mention making changes without using the plugin).

**Comment by maheshmnj** [comment]
> How can we make sure that they will run in the same isolate? Is an isolate similar to a thread?

Each thread runs in a separate isolate with its own memory, There is a well explained [video on isolates](https://www.youtube.com/watch?v=vl_AaCgudcY) from the flutter team.
Until this issue is resolved , Maybe you could try sending data across [isolates](https://api.flutter.dev/flutter/dart-isolate/Isolate-class.html) using port communication (SendPort, ReceivePort).

**Comment by Julianlu1** [comment]
@maheshmnj I looked into it and I think I am very close. However I don't know how to send data from the isolate to the main isolate.

I added this class isolates:
```dart
import 'dart:io'; // for exit();
import 'dart:async';
import 'dart:isolate';

Future<Future> initIsolate() async {
  Completer completer = new Completer<SendPort>();
  ReceivePort isolateToMainStream = ReceivePort();

  isolateToMainStream.listen((data) {
    if (data is SendPort) {
      SendPort mainToIsolateStream = data;
      completer.complete(mainToIsolateStream);
    } else {
      // TODO: Do something with the data
      print('[isolateToMainStream] $data');
    }
  });

  Isolate myIsolateInstance =
      await Isolate.spawn(myIsolate, isolateToMainStream.sendPort);
  return completer.future;
}

void myIsolate(SendPort isolateToMainStream) {
  ReceivePort mainToIsolateStream = ReceivePort();
  isolateToMainStream.send(mainToIsolateStream.sendPort);

  mainToIsolateStream.listen((data) {
    print('[mainToIsolateStream] $data');
    exit(0);
  });
  // TODO: Make sure I send the correct data, in my case the list of topics
  isolateToMainStream.send('This is from myIsolate()');
}
```
I then call initIsolate in the backgroundhandler ( see original post ). However how can I send a message from isolate to main isolate. I followed this tutorial : https://medium.com/@lelandzach/dart-isolate-2-way-communication-89e75d973f34. But the example is not that clear in my opinion..

Thanks!

**Comment by stuartmorgan** [comment]
> Until this issue is resolved

The resolution will just be adding what I said above to the documentation; `reload` already exists. There's no reason to wait for documentation updates before using it.

**Comment by Julianlu1** [comment]
@stuartmorgan I tried to add 'prefs.reload();' in the backgroundhandler, and in the foreground (when the app restarts) but the shared preferences list is still not updated...

**Comment by stuartmorgan** [comment]
> and in the foreground (when the app restarts)

You need to run it when the app is foregrounded, not when the app restarts. There's no cache to reload on a cold start of the application.

The `reload` call you added to `main` isn't doing anything (other than slowing your application startup), because it's recreating exactly the same cache that was created in the line directly above it.

**Comment by Julianlu1** [comment]
I think you are right. The way I used reload did not make sense at all. I deleted the reload function and it's behavior is indeed the same. I guess I found an alternative method to remove the topic from the list and delete the topic from firebase.

Putting them in a separate list, and when the app is restarted, then I delete the topic from the list and from firebase. I don't think I need to use the reload method anymore since the alternative method is stable.

Because sometimes `FirebaseMessaging.instance.unsubscribeFromTopic(topic);` is not doing it's job consistently, when called in the backgroundhandler. Which means the user still receives a notification regarding to that topic and remains subscribed.

**Comment by EA-YOUHOU** [comment]
I used the following code when using sharedPreferences, i've no issue between my isolate and my app with that.

```dart
/// Add [reload] to have instance updated with Isolate
  Future<SharedPreferences> getSharedPreference() async {
    final SharedPreferences instance = await SharedPreferences.getInstance();
    await instance.reload();
    return instance;
  }
```

**Comment by Hesamedin** [comment]
> I use the following code when using sharedPreferences, i've no issue between my isolate and my app with that.
> 
> ```dart
> /// Add [reload] to have instance updated with Isolate
>   Future<SharedPreferences> getSharedPreference() async {
>     final SharedPreferences instance = await SharedPreferences.getInstance();
>     await instance.reload();
>     return instance;
>   }
> ```

It did indeed fix the problem for me. Thank you.

**Comment by jbxbergdev** [comment]
This behavior is really confusing (more so even when you come from native development). Unless there is a really compelling reason to put an in memory cache layer on top of the system shared preferences, SharedPreferences should always read from disk by default.

**Comment by stuartmorgan** [comment]
> Unless there is a really compelling reason to put an in memory cache layer on top of the system shared preferences

All of the getters would become asynchronous without that layer.

**Comment by EArminjon2** [comment]
Getter from SharedPreferences.getInstance() should be synchronous, but maybe reload() could be call inside the getInstance() ?

**Comment by stuartmorgan** [comment]
> maybe reload() could be call inside the getInstance()

Unless you are calling `getInstance` every time you interact with the shared preferences, that wouldn't help. And if you are, and you want that behavior, then you can trivially just write a wrapper like the one above and use that everywhere, which would give you the behavior you want without making `shared_preferences` dramatically less efficient for the common case of people *not* using plugins in multiple isolates.

**Comment by maheshmnj** [comment]
> Ok, doc should mention that I think (when working with Isolates)

This issue is tracking the same request.

**Comment by jbxbergdev** [comment]
> > Unless there is a really compelling reason to put an in memory cache layer on top of the system shared preferences
> 
> All of the getters would become asynchronous without that layer.

I think for most users, that's far less of a problem than potentially dealing with inconsistent data. (Plus, getInstance() is an asynchronous call to begin with).

**Comment by AbodiSadiqGitHub** [comment]
I face the same problem, I solved it by using:
await prefs.reload();

**Comment by HenriqueGuima** [comment]
I had the same problem and solved it by using `await prefs.reload();` on my `AppLifecycleState.resumed`
