### ISSUE TITLE
Flow should cross link to Wrap

### ISSUE THREAD

**Issue by abarth** [flutter/flutter#10165]
Some developers expect Flow to behave like Wrap because some other frameworks use the term "flow" for the sort of layout that Wrap does.

/cc @Hixie

**Comment by sethladd** [comment]
We might want to add some synonym terms to widget catalog. So if I search
for flow I find wrap.

Cc @inmatrix

**Comment by InMatrix** [comment]
Probably mention Wrap in the "See also" section of the Flow doc?

Adding illustrations of Flow and Wrap in the widget catalog and their API docs should help developers to choose the right one as well.

**Comment by Hixie** [comment]
I've no idea how to illustrate Flow, though we will have to figure it out at some point...
