### ISSUE TITLE
[tool_crash] SocketException: The remote computer refused the network connection., OS Error: The remote computer refused the network connection., errno = 1225

### ISSUE THREAD

**Issue by hasanm08** [flutter/flutter#101624]
## Command
```
flutter drive --dart-define=app.flavor=develop --debug --verbose-system-logs --driver-port 9515 --driver=lib/integration_test/test_driver.dart --target=lib/integration_test/scenarios/user_actions_test.dart -d web-server -v
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
SocketException: The remote computer refused the network connection.
, OS Error: The remote computer refused the network connection.
, errno = 1225
```
#0      _NativeSocket.startConnect (dart:io-patch/socket_patch.dart:682:35)
#1      _RawSocket.startConnect (dart:io-patch/socket_patch.dart:1817:26)
#2      RawSocket.startConnect (dart:io-patch/socket_patch.dart:27:23)
#3      Socket._startConnect (dart:io-patch/socket_patch.dart:2038:22)
#4      Socket.startConnect (dart:io/socket.dart:792:21)
#5      _ConnectionTarget.connect (dart:_http/http_impl.dart:2440:18)
#6      _HttpClient._getConnection.connect (dart:_http/http_impl.dart:2834:12)
#7      _HttpClient._getConnection (dart:_http/http_impl.dart:2839:12)
#8      _HttpClient._openUrl (dart:_http/http_impl.dart:2698:12)
#9      _HttpClient.deleteUrl (dart:_http/http_impl.dart:2590:51)
#10     AsyncIoRequestClient.sendRaw (package:webdriver/src/request/async_io_request_client.dart:34:36)
<asynchronous suspension>
#11     AsyncRequestClient.send (package:webdriver/src/common/request_client.dart:96:33)
<asynchronous suspension>
#12     WebDriverService.startTest (package:flutter_tools/src/drive/web_driver_service.dart:182:5)
<asynchronous suspension>
#13     DriveCommand.runCommand (package:flutter_tools/src/commands/drive.dart:272:28)
<asynchronous suspension>
#14     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1161:27)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#16     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#17     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
```
```
[✓] Flutter (Channel stable, 2.10.4, on Microsoft Windows [Version 10.0.22000.556], locale en-US)
    • Flutter version 2.10.4 at E:\flutter_windows_2.5.2-stable\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (2 weeks ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at E:\SDK
    • Platform android-31, build-tools 30.0.3
    • ANDROID_HOME = E:\SDK
    • Java binary at: D:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 2020.3)
    • Android Studio at D:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] Connected device (3 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 100.0.4896.75
    • Edge (web)       • edge       • web-javascript • Microsoft Edge 100.0.1185.29

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 2.9.0
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: c5a4b4029c0798f37c4a39b479d7cb75daa7b05c
### Plugins
connectivity_plus-2.2.1
connectivity_plus_linux-1.3.0
connectivity_plus_macos-1.2.1
connectivity_plus_web-1.2.0
connectivity_plus_windows-1.2.0
device_info_plus-3.2.2
device_info_plus_linux-2.1.1
device_info_plus_macos-2.2.2
device_info_plus_web-2.1.0
device_info_plus_windows-2.1.1
firebase_analytics-9.1.3
firebase_analytics_web-0.4.0+9
firebase_core-1.14.0
firebase_core_web-1.6.1
firebase_crashlytics-2.6.0
flutter_keyboard_visibility-5.2.0
flutter_keyboard_visibility_web-2.0.0
integration_test
native_device_orientation-1.0.0
path_provider-2.0.9
path_provider_android-2.0.12
path_provider_ios-2.0.8
path_provider_linux-2.1.5
path_provider_macos-2.0.5
path_provider_windows-2.0.5
share_plus-4.0.3
share_plus_linux-3.0.0
share_plus_macos-3.0.0
share_plus_web-3.0.0
share_plus_windows-3.0.0
shared_preferences-2.0.13
shared_preferences_android-2.0.11
shared_preferences_ios-2.1.0
shared_preferences_linux-2.1.0
shared_preferences_macos-2.0.3
shared_preferences_web-2.0.3
shared_preferences_windows-2.1.0
sqflite-2.0.2
text_to_speech-0.2.3
text_to_speech_macos-0.1.1
text_to_speech_web-0.1.2
uni_links-0.5.1
uni_links_web-0.1.0
url_launcher-6.0.20
url_launcher_android-6.0.15
url_launcher_ios-6.0.15
url_launcher_linux-3.0.0
url_launcher_macos-3.0.0
url_launcher_web-2.0.9
url_launcher_windows-3.0.0
video_player-2.3.0
video_player_android-2.3.2
video_player_avfoundation-2.3.1
video_player_web-2.0.7
video_player_web_hls-0.1.11+4
volume_watcher-2.0.1
wakelock-0.6.1+2
wakelock_macos-0.4.0
wakelock_web-0.4.0

**Comment by darshankawar** [comment]
Labeling it since I don't see a similar issue already logged for this error.

/cc @christopherfujino

**Comment by christopherfujino** [comment]
My first instinct is that this could be Windows firewall blocking this.

@hasanm08 also, where did you get `--driver-port 9515` from? And are you sure it is correct?

It looks like this failure is coming from https://github.com/flutter/flutter/blob/stable/packages/flutter_tools/lib/src/drive/web_driver_service.dart#L142.

**Comment by hasanm08** [comment]
> you get `--driver-port 9515` from? And are you sure it is correct?
this was the port that ```chromedriver``` had started on

**Comment by christopherfujino** [comment]
> > you get `--driver-port 9515` from? And are you sure it is correct?
> 
> this was the port that `chromedriver` had started on

Did you check if this is Windows Firewall blocking you?

**Comment by hasanm08** [comment]
> > > you get `--driver-port 9515` from? And are you sure it is correct?
> > 
> > 
> > this was the port that `chromedriver` had started on
> 
> Did you check if this is Windows Firewall blocking you?

yes

**Comment by ditman** [comment]
This is how I normally run drive tests (in linux, admittedly).

1. Ensure chromedriver is running in port 4444 (the default that `flutter drive` wants):
    ```
    chromedriver --port=4444
    ```
2. Then run `flutter drive` like so:
    ```
    flutter drive -d web-server --browser-name=chrome \
    --driver=lib/integration_test/test_driver.dart \
    --target=lib/integration_test/scenarios/user_actions_test.dart
    ```

(I don't see `browser-name` in your original invocation, and there's other values that I don't think are needed for web tests at all)

((You can maybe try running the tests that we have [here](https://github.com/flutter/plugins/tree/main/packages/url_launcher/url_launcher_web/example), for example. Those tests are run in our CI all the time)).
