### ISSUE TITLE
NavigationBar doesn't account for safe area

### ISSUE THREAD

**Issue by xster** [flutter/flutter#101605]
Details in b/228601418. Seems like NavigationBar doesn't internally account for horizontal safe area, which becomes an issue with notches etc when in landscape mode. 

A release blocker for customer, though release is still a few months away.

**Comment by jmagman** [comment]
From b/228601418:
> Were working on improving our Flutter app's landscape experience, and noticed an issue with our `NavigationBar` component. We have 3 items in the component, so the middle one is centered. However, when running on an Android device in landscape, the system navigation bar takes up a portion of the right or left side of the screen. As a result, contents that we have centered are centered between the inner edge of the system navigation bar and the opposite edge of the device. However, the `NavigationBar` does not replicate this behavior, nor does it allow us to replicated it manually. It should either properly apply horizontal padding based on `MediaQuery.of(context).padding`, or it should allow us to do so manually.
>
> Oh, and I should also mention I cannot simply wrap the `NavigationBar` in a `SafeArea` because I want the background color to continue behind the system navigation bar, as in the above screenshot.

**Comment by Piinks** [comment]
More context in https://github.com/flutter/flutter/issues/102263
