### ISSUE TITLE
Having problem while getting release build

### ISSUE THREAD

**Issue by ozyildirim** [flutter/flutter#101687]
Hello! 
I'm having problem with my application while getting release build. Actually there is no problem when I get debug build for emulator but it is not same for building apk process. Does anyone have any experience like that? I'm attaching the output code that I get while getting release build. Thank you.

> `/C:/SDK/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_math_fork-0.3.2+1/lib/src/widgets/selectable.dart:407:7: Error: The non-abstract class 'InternalSelectableMathState' is missing implementations for these members:
>  - TextSelectionDelegate.copySelection
>  - TextSelectionDelegate.cutSelection
>  - TextSelectionDelegate.pasteText
>  - TextSelectionDelegate.selectAll
> Try to either
>  - provide an implementation,
>  - inherit an implementation from a superclass or mixin,
>  - mark the class as abstract, or
>  - provide a 'noSuchMethod' implementation.
> 
> class InternalSelectableMathState extends State<InternalSelectableMath>
>       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
> /C:/SDK/flutter/packages/flutter/lib/src/services/text_input.dart:1034:8: Context: 'TextSelectionDelegate.copySelection' is defined here.
>   void copySelection(SelectionChangedCause cause);
>        ^^^^^^^^^^^^^
> /C:/SDK/flutter/packages/flutter/lib/src/services/text_input.dart:1014:8: Context: 'TextSelectionDelegate.cutSelection' is defined here.
>   void cutSelection(SelectionChangedCause cause);
>        ^^^^^^^^^^^^
> /C:/SDK/flutter/packages/flutter/lib/src/services/text_input.dart:1022:16: Context: 'TextSelectionDelegate.pasteText' is defined here.
>   Future<void> pasteText(SelectionChangedCause cause);
>                ^^^^^^^^^
> /C:/SDK/flutter/packages/flutter/lib/src/services/text_input.dart:1028:8: Context: 'TextSelectionDelegate.selectAll' is defined here.
>   void selectAll(SelectionChangedCause cause);
>        ^^^^^^^^^
> lib/src/widgets/task_ops_deliver_info_page.dart:292:44: Error: The argument type 'Padding Function(BuildContext, {void Function()? onStepCancel, void Function()? onStepContinue})' can't be assigned to the parameter type 'Widget Function(BuildContext, ControlsDetails)?'.
>  - 'Padding' is from 'package:flutter/src/widgets/basic.dart' ('/C:/SDK/flutter/packages/flutter/lib/src/widgets/basic.dart').
>  - 'BuildContext' is from 'package:flutter/src/widgets/framework.dart' ('/C:/SDK/flutter/packages/flutter/lib/src/widgets/framework.dart').
>  - 'Widget' is from 'package:flutter/src/widgets/framework.dart' ('/C:/SDK/flutter/packages/flutter/lib/src/widgets/framework.dart').
>  - 'ControlsDetails' is from 'package:flutter/src/material/stepper.dart' ('/C:/SDK/flutter/packages/flutter/lib/src/material/stepper.dart').
>                           controlsBuilder: (BuildContext context,
>                                            ^
> /C:/SDK/flutter/.pub-cache/hosted/pub.dartlang.org/platform-3.0.0/lib/src/interface/local_platform.dart:46:19: Error: Member not found: 'packageRoot'.
>       io.Platform.packageRoot; // ignore: deprecated_member_use
>                   ^^^^^^^^^^^
> /C:/SDK/flutter/.pub-cache/hosted/pub.dartlang.org/wakelock_platform_interface-0.2.0/lib/messages.dart:100:17: Error: The method 'setMockMessageHandler' isn't 
> defined for the class 'BasicMessageChannel<dynamic>'.
>  - 'BasicMessageChannel' is from 'package:flutter/src/services/platform_channel.dart' ('/C:/SDK/flutter/packages/flutter/lib/src/services/platform_channel.dart').
> Try correcting the name to the name of an existing method, or defining a method named 'setMockMessageHandler'.
>         channel.setMockMessageHandler(null);
>                 ^^^^^^^^^^^^^^^^^^^^^
> /C:/SDK/flutter/.pub-cache/hosted/pub.dartlang.org/wakelock_platform_interface-0.2.0/lib/messages.dart:102:17: Error: The method 'setMockMessageHandler' isn't 
> defined for the class 'BasicMessageChannel<dynamic>'.
>  - 'BasicMessageChannel' is from 'package:flutter/src/services/platform_channel.dart' ('/C:/SDK/flutter/packages/flutter/lib/src/services/platform_channel.dart').
> Try correcting the name to the name of an existing method, or defining a method named 'setMockMessageHandler'.
>         channel.setMockMessageHandler((dynamic message) async {
>                 ^^^^^^^^^^^^^^^^^^^^^
> /C:/SDK/flutter/.pub-cache/hosted/pub.dartlang.org/wakelock_platform_interface-0.2.0/lib/messages.dart:114:17: Error: The method 'setMockMessageHandler' isn't 
> defined for the class 'BasicMessageChannel<dynamic>'.
>  - 'BasicMessageChannel' is from 'package:flutter/src/services/platform_channel.dart' ('/C:/SDK/flutter/packages/flutter/lib/src/services/platform_channel.dart').
> Try correcting the name to the name of an existing method, or defining a method named 'setMockMessageHandler'.
>         channel.setMockMessageHandler(null);
>                 ^^^^^^^^^^^^^^^^^^^^^
> /C:/SDK/flutter/.pub-cache/hosted/pub.dartlang.org/wakelock_platform_interface-0.2.0/lib/messages.dart:116:17: Error: The method 'setMockMessageHandler' isn't 
> defined for the class 'BasicMessageChannel<dynamic>'.
>  - 'BasicMessageChannel' is from 'package:flutter/src/services/platform_channel.dart' ('/C:/SDK/flutter/packages/flutter/lib/src/services/platform_channel.dart').
> Try correcting the name to the name of an existing method, or defining a method named 'setMockMessageHandler'.
>         channel.setMockMessageHandler((dynamic message) async {
>                 ^^^^^^^^^^^^^^^^^^^^^
> 
> 
> FAILURE: Build failed with an exception.
> 
> * Where:
> Script 'C:\SDK\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1102
> 
> * What went wrong:
> Execution failed for task ':app:compileFlutterBuildRelease'.
> > Process 'command 'C:\SDK\flutter\bin\flutter.bat'' finished with non-zero exit value 1
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BU�LD FAILED in 51s`

**Comment by maheshmnj** [comment]
Hi @ozyildirim, Thanks for filing the issue. The error seems related to third party package

> Error: The non-abstract class 'InternalSelectableMathState' is missing implementations for these members:  

There seem to be missing class member implementations in the library. I would recommend reporting that issue with the dedicated maintainer of the plugin.

> when I get debug build for emulator but it is not same for building apk process

But since you are able to run the app in debug mode that makes me think the code should be fine in the plugin. Please attach the complete output of `flutter doctor -v` , `flutter run -v` (in a text file as the output will be long) and the `pubspec.yaml` file.

**Comment by ozyildirim** [comment]
Hi @maheshmnj.

I'm attaching results.
Thank you
[doctor_result.txt](https://github.com/flutter/flutter/files/8463792/doctor_result.txt)
[run_result.txt](https://github.com/flutter/flutter/files/8463793/run_result.txt)
.

**Comment by maheshmnj** [comment]
Thanks for the info @ozyildirim, The logs are fine here could you also please attach `flutter run --release -v` in a text file ?
