### ISSUE TITLE
Tooltip Dartpad example doesn't run

### ISSUE THREAD

**Issue by justinmc** [flutter/flutter#101779]
In the [Tooltip docs](https://master-api.flutter.dev/flutter/material/Tooltip-class.html), the fourth and final Dartpad example doesn't run and has a console error:

```
Error compiling to JavaScript:
/tmp/dartpadGWGFNF/lib/bootstrap.dart: Warning: Interpreting this as package URI, 'package:dartpad_sample/bootstrap.dart'.
/tmp/dartpadGWGFNF/lib/main.dart:26:21: Error: 'TooltipState' isn't a type.
    final GlobalKey<TooltipState> tooltipkey = GlobalKey<TooltipState>();
                    ^^^^^^^^^^^^
/tmp/dartpadGWGFNF/lib/main.dart:26:58: Error: 'TooltipState' isn't a type.
    final GlobalKey<TooltipState> tooltipkey = GlobalKey<TooltipState>();
```

Interestingly, if I copy the code and run it locally on master in Chrome, it does work.

**Comment by TahaTesser** [comment]
Hey!
I added this sample. This is expected as this hasn't landed in the stable channel yet and API docs use stable Dartpad. 
This is a common issue with API docs whenever there is a change on master and it is available on the stable channel. 

ex: https://github.com/flutter/flutter/pull/82733#issuecomment-842642254

**Comment by TahaTesser** [comment]
It would be nice if we can have a channel switcher in API dartpad just like dartpad.dev

![image](https://user-images.githubusercontent.com/48603081/163052459-561b9967-2414-471e-9693-6324cced60ac.png)


cc: @Hixie

**Comment by TahaTesser** [comment]
Just FYI, `TooltipState` is made public on master channel hence the example doesn't run

**Comment by justinmc** [comment]
Got it, thanks for the explanation.  I'll go ahead and close this, but +1 for the channel switcher!
