### ISSUE TITLE
[Fonts] Icon request: battery_5_bar

### ISSUE THREAD

**Issue by Coinmaster123456** [flutter/flutter#101716]

**Comment by maheshmnj** [comment]
Hi @Coinmaster123456,  thanks for filing the issue.   The requested icon is available on the master channel. It should be available on other flutter channels in future releases. 
<img width="579" alt="image" src="https://user-images.githubusercontent.com/31410839/162906198-33a16077-174e-4b48-9988-0545d8b68fc0.png">

Closing as fixed on master
