### ISSUE TITLE
Text under edit should be auto-corrected on submit on iOS

### ISSUE THREAD

**Issue by cbracken** [flutter/flutter#10171]
## Steps to Reproduce

1. Build [FriendlyChat step 2](https://github.com/flutter/friendlychat-flutter/blob/master/full_steps/step_2_sign_in/lib/main.dart#L166).
1. Enter text that will trigger auto-correct into the text field.
1. Hit 'Send'.

Expected behaviour: the auto-corrected text is sent on iOS, the uncorrected text is sent on Android.
Actual behaviour: the uncorrected text is sent on both iOS and Android.

## Flutter Doctor

```
[✓] Flutter (on Mac OS X 10.12.4 16E195, channel master)
    • Flutter at /Users/cbracken/src/flutter/flutter
    • Framework revision bac2f0d01f (52 minutes ago), 2017-05-18 10:08:11 -0700
    • Engine revision 82815836eb
    • Tools Dart version 1.23.0-dev.11.11
```

**Comment by Hixie** [comment]
@cbracken claims this is fixed.
