### ISSUE TITLE
Flutter 2.0 Ripple Effect does not dismiss after you click many times in a short time duration.

### ISSUE THREAD

**Issue by yqjroy** [flutter/flutter#101750]
[](https://stackoverflow.com/posts/71840322/timeline)0

I think it's really puzzling. In flutter 2.0: Click a widget more times in a short time duration, and then the ripple effect does not disappear. How to recover the original status of the widget.

Like this, the button stays the pressed ripple forever. And the more you click, the darker the background-color is.
<img width="280" alt="image" src="https://user-images.githubusercontent.com/30015232/162931811-e7e218a2-f9e5-4d85-b7b9-8c537a35fd1d.png">

**Comment by danagbemava-nc** [comment]
Hi @yqjroy, please provide a complete minimal reproducible code sample so that we may verify this. Please provide the output of `flutter doctor -v` as well. 

Thank you

**Comment by yqjroy** [comment]
@danagbemava-nc 

**$ fvm flutter doctor**
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, 2.8.0, on macOS 11.6 20G165 darwin-x64, locale
    zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] IntelliJ IDEA Community Edition (version 2021.3.3)
[✓] Connected device (1 available)

• No issues found!

**fvm flutter doctor -v**
[✓] Flutter (Channel unknown, 2.8.0, on macOS 11.6 20G165 darwin-x64, locale
    zh-Hans-CN)
    • Flutter version 2.8.0 at /Users/roy/Library/Application
      Support/fvm/versions/2.8.0
    • Upstream repository unknown
    • Framework revision cf44000065 (4 months ago), 2021-12-08 14:06:50 -0800
    • Engine revision 40a99c5951
    • Dart version 2.15.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/roy/Library/Android/sdk
    • Platform android-31, build-tools 30.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 100.0.4896.75

• No issues found!


`OutlinedButton(
                            child: Text(
                              SettingMessages.setting_Logout.tr,
                              style: TextStyle(
                                fontSize: 14,
                              ),
                            ),
                            style: OutlinedButton.styleFrom(
                                side: BorderSide(width: 0.5, color: LocalColors.mainColor,)
                            ),
                            onPressed: () {
                              ShowUtil.showAlertDialog(context, Messages.information.tr, SettingMessages.setting_LogoutAlert.tr, sure: () {
                                c.logout();
                              });
                            },
                          ),`

**Comment by yqjroy** [comment]
Uploading QQ20220413-094203-HD.mp4…
@danagbemava-nc Here is the video.

**Comment by yqjroy** [comment]
![22yxa-ogixh](https://user-images.githubusercontent.com/30015232/163083811-a4cacf9d-24cd-4dce-990e-cc834607857c.gif)
@danagbemava-nc Here is the gif

**Comment by danagbemava-nc** [comment]
Hi @yqjroy, you appear to be on an older version of flutter. Kindly upgrade to the latest version of `stable`, 2.10.4 to see if you still experience this issue. 

If you do, please provide the updated `flutter doctor -v` as well as a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)

Thank you

**Comment by yqjroy** [comment]
Hi, @danagbemava-nc , wrap the MyApp in a GestureDetector Widget.
code as follows:
`import 'package:flutter/material.dart';

void main() {
  int touchTime;

  runApp(GestureDetector(
    child: const MyApp(),
    onTapDown: (detail) {
      touchTime = DateTime.now().millisecondsSinceEpoch;
    },
    onTapUp: (detail) {
      touchTime = DateTime.now().millisecondsSinceEpoch;
    },
    onTapCancel: () {
      touchTime = DateTime.now().millisecondsSinceEpoch;
    },
    onTap: () {
      touchTime = DateTime.now().millisecondsSinceEpoch;
    },
    onDoubleTap: () {
      touchTime = DateTime.now().millisecondsSinceEpoch;
    },
    onLongPress: () {
      touchTime = DateTime.now().millisecondsSinceEpoch;
    },
    onVerticalDragStart: (detail) {
      touchTime = DateTime.now().millisecondsSinceEpoch;
    },
    onVerticalDragEnd: (detail) {
      touchTime = DateTime.now().millisecondsSinceEpoch;
    },
    onVerticalDragCancel: () {
      touchTime = DateTime.now().millisecondsSinceEpoch;
    },
    onVerticalDragUpdate: (detail) {
      touchTime = DateTime.now().millisecondsSinceEpoch;
    },
    onForcePressStart: (detail) {
      touchTime = DateTime.now().millisecondsSinceEpoch;
    },
    behavior: HitTestBehavior.translucent,
  ));
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
            OutlinedButton(onPressed: () {}, child: Text('Button')),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}
`

**Comment by danagbemava-nc** [comment]
Hi @yqjroy, some work was done on the `InkWell` splashes recently and merged into the current master, can you check on the `master` channel to see if you're able to consistently reproduce this issue? I could not find a way to consistently reproduce on `master` although I could consistently reproduce on the `stable` channel. 

To use the `master` channel, use the following commands

```
flutter channel master
flutter upgrade --force
```

Thank you

**Comment by yqjroy** [comment]
你好，邮件已收到！谢谢！

**Comment by yqjroy** [comment]
> 

ok, i may try if i am free.

**Comment by huycozy** [comment]
Hi @yqjroy, This issue has been fixed on `master` channel by [this PR](https://github.com/flutter/flutter/pull/100880). 

<details>
<summary>Sample code</summary>

```dart

import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            InkWell(
              onTap: () {
                print("Tap Called");
              },
              onDoubleTap: () {
                print("Tap Called");
              },
              onTapCancel: () {
                print("Tap Cancelled");
              },
              child: Container(
                padding: EdgeInsets.all(20),
                child: Text(
                  '$_counter',
                  style: Theme.of(context).textTheme.headline4,
                ),
              ),
            ),
            OutlinedButton(onPressed: () {}, child: Text('Button')),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}
```
</details>

<details>
<summary>Demo</summary>


https://user-images.githubusercontent.com/104349824/167602723-713ed551-daec-4479-ac1c-6e24f30c8627.mov


</details>

I'm going to close this issue. If you disagree about this, please drop a comment and I will reopen it.
