### ISSUE TITLE
Android sdkmanager tool was found, but failed to run

### ISSUE THREAD

**Issue by Husteczka** [flutter/flutter#101727]
Hey. I have a problem installing flutter. Once I have everything installed and want to finish, I can't run the android sdk license. Please help

## Steps to Reproduce

1. Open PowerShell
2. Type "flutter doctor --android-licenses

## Logs

<details>

<summary>logs here</summary>

<img width="1057" alt="Zrzut ekranu 2022-04-12 002529" src="https://user-images.githubusercontent.com/91752927/162843634-733633e1-3ad4-424a-98f9-076205f8b397.png">

</details>

**Comment by maheshmnj** [comment]
Hi @Husteczka, Thanks for filing the issue. please share the complete output of `flutter doctor -v` and the output of 
`flutter doctor --android-licenses` as text.

**Comment by Husteczka** [comment]
Flutter doctor -v:
[√] Flutter (Channel stable, 2.10.4, on Microsoft Windows [Version 10.0.19042.1586], locale pl-PL)
    • Flutter version 2.10.4 at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (3 weeks ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[!] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at C:\Users\Franio\AppData\Local\Android\sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.1.3)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.1.32328.378
    • Windows 10 SDK version 10.0.22000.0

[√] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19042.1586]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 100.0.4896.75
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 100.0.1185.36

[√] HTTP Host Availability
    • All required HTTP hosts are available


flutter doctor --android-licenses

Android sdkmanager tool was found, but failed to run
(C:\Users\Franio\AppData\Local\Android\sdk\cmdline-tools\latest\bin\sdkmanager.bat): "ProcessException: Parametr jest
niepoprawny.

  Command: C:\Users\Franio\AppData\Local\Android\sdk\cmdline-tools\latest\bin\sdkmanager.bat --licenses".
Try re-installing or updating your Android SDK,
visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions.

**Comment by maheshmnj** [comment]
Thanks for the info @Husteczka, Please ensure that you have `JAVA_HOME` environment variable set which points to the android JDK, and please also try this StackOverflow answer https://stackoverflow.com/a/60705505/8253662

**Comment by Husteczka** [comment]
Yes I have <code>JAVA_HOME</code> environment variable set. Unfortunately the StackOverflow answer didn't work :/

**Comment by maheshmnj** [comment]
Could you please try reinstalling andorid sdk in that case?

> Try re-installing or updating your Android SDK,
visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions.
