### ISSUE TITLE
Updated dependency in .ci.yaml doesn't propagate to task when re-run

### ISSUE THREAD

**Issue by blasten** [flutter/flutter#101715]
https://github.com/flutter/flutter/pull/101276 for instance.

After many retries, the task's "Input Properties", still show the dependency without the specified version.
For example: https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20build_aar_module_test/15419/overview

**Comment by yusuf-goog** [comment]
@godofredoc has this issue been followed up in a chat stream?

**Comment by godofredoc** [comment]
The problem here is that when the build is initially scheduled it has the correct dimensions, however when the build is triggered with the re-run button dimensions are not populated correctly.

**Comment by yusuf-goog** [comment]
@CaseyHillers do you know if the re-run might be triggering builds of tot or some other commit, missing the input property chagnes?

**Comment by godofredoc** [comment]
Actually the re-run functionality is not propagating the properties. I have a local fix but I don't have a PR that I can test with.

**Comment by CaseyHillers** [comment]
> Actually the re-run functionality is not propagating the properties. I have a local fix but I don't have a PR that I can test with.

Any reason why a unit test wouldn't suffice? We could verify rerun evens are passing expected properties to LuciBuildService

**Comment by godofredoc** [comment]
The unit test can only validate expectations but we need to be sure the build information is actually being populated. https://cs.opensource.google/flutter/cocoon/+/main:app_dart/lib/src/service/luci_build_service.dart;l=381

**Comment by godofredoc** [comment]
I haven't had the chance to test it yet
