### ISSUE TITLE
Extract common icon concept from material to widget

### ISSUE THREAD

**Issue by xster** [flutter/flutter#10177]
So that icons in the generic sense can be reused in cupertino.

Very tentatively tagging API break. Though it shouldn't affect any users, except perhaps if user previously imported widget and also imported/implemented their own Icon class etc.

**Comment by xster** [comment]
Will need for #9926

**Comment by Hixie** [comment]
I don't think we will be able to do this. It would break pretty much every application ever.

**Comment by xster** [comment]
Ok chatted offline:

We're just moving icon, not making a new one. 

To solve some of the icon_theme->theme dependency, let icon theme just find a parent icon theme without referring to Theme directly, by having Theme actually insert IconThemes into the widget tree. Do the same text and let the original theme inherited widget still be an inherited widget as _Theme and let it be the child of a parent Theme grouping container that's a stateless widget which inserts IconTheme
