### ISSUE TITLE
Geolocator 

### ISSUE THREAD

**Issue by AKingNamedSimba** [flutter/flutter#101705]
Performing hot reload...
Syncing files to device AOSP on IA Emulator...
Reloaded 8 of 591 libraries in 718ms.
E/flutter (13257): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method getCurrentPosition on channel flutter.baseflow.com/geolocator)
E/flutter (13257): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
E/flutter (13257): <asynchronous suspension>
E/flutter (13257): #1      MethodChannelGeolocator.getCurrentPosition (package:geolocator_platform_interface/src/implementations/method_channel_geolocator.dart:128:27)
E/flutter (13257): <asynchronous suspension>
E/flutter (13257): #2      QiblaCompass.getLocation (package:qib_redo/QiblaCompass.dart:12:26)
E/flutter (13257): <asynchronous suspension>
E/flutter (13257): 
E/flutter (13257): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method getCurrentPosition on channel flutter.baseflow.com/geolocator)
E/flutter (13257): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
E/flutter (13257): <asynchronous suspension>
E/flutter (13257): #1      MethodChannelGeolocator.getCurrentPosition (package:geolocator_platform_interface/src/implementations/method_channel_geolocator.dart:128:27)
E/flutter (13257): <asynchronous suspension>
E/flutter (13257): #2      QiblaCompass.getLocation (package:qib_redo/QiblaCompass.dart:12:26)
E/flutter (13257): <asynchronous suspension>
E/flutter (13257): 
E/flutter (13257): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method getCurrentPosition on channel flutter.baseflow.com/geolocator)
E/flutter (13257): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
E/flutter (13257): <asynchronous suspension>
E/flutter (13257): #1      MethodChannelGeolocator.getCurrentPosition (package:geolocator_platform_interface/src/implementations/method_channel_geolocator.dart:128:27)
E/flutter (13257): <asynchronous suspension>
E/flutter (13257): #2      QiblaCompass.getLocation (package:qib_redo/QiblaCompass.dart:12:26)
E/flutter (13257): <asynchronous suspension>
E/flutter (13257): 
E/flutter (13257): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method getCurrentPosition on channel flutter.baseflow.com/geolocator)
E/flutter (13257): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
E/flutter (13257): <asynchronous suspension>
E/flutter (13257): #1      MethodChannelGeolocator.getCurrentPosition (package:geolocator_platform_interface/src/implementations/method_channel_geolocator.dart:128:27)
E/flutter (13257): <asynchronous suspension>
E/flutter (13257): #2      QiblaCompass.getLocation (package:qib_redo/QiblaCompass.dart:12:26)
E/flutter (13257): <asynchronous suspension>
E/flutter (13257): 
E/flutter (13257): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method getCurrentPosition on channel flutter.baseflow.com/geolocator)
E/flutter (13257): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
E/flutter (13257): <asynchronous suspension>
E/flutter (13257): #1      MethodChannelGeolocator.getCurrentPosition (package:geolocator_platform_interface/src/implementations/method_channel_geolocator.dart:128:27)
E/flutter (13257): <asynchronous suspension>
E/flutter (13257): #2      QiblaCompass.getLocation (package:qib_redo/QiblaCompass.dart:12:26)
E/flutter (13257): <asynchronous suspension>
E/flutter (13257):

**Comment by AKingNamedSimba** [comment]
I followed the guidelines on the use of geolocator and when I hit the button I have my getLocation function attached to, I get this back (see above)

**Comment by Zazo032** [comment]
That's not an official plugin, so issues shouldn't be posted here. Try stopping your app and running `flutter pub get` before running the app again
