### ISSUE TITLE
 The Linux toolchain CMake build dependency (CMake 3.14 or higher is required. You are running version 3.10.2)

### ISSUE THREAD

**Issue by purencool** [flutter/flutter#101788]
Hi team,

For awareness, I wanted to bring up the issue I faced by compiling my application using the Linux (Ubuntu) Snap. Regression of the CMake dependency might not be an option in this case. However. if someone is searching the web for this issue they have a way forward.

https://github.com/flutter/flutter/issues/101726
https://github.com/canonical/flutter-snap/issues/53

```
build$ flutter run -d Linux
Downloading linux-x64/linux-x64-flutter-gtk tools...               11.6s
Downloading linux-x64-profile/linux-x64-flutter-gtk tools...         7.5s
Downloading linux-x64-release/linux-x64-flutter-gtk tools...         5.0s
Launching lib/main.dart on Linux in debug mode...
CMake Error at flutter/ephemeral/.plugin_symlinks/sqlite3_flutter_libs/linux/CMakeLists.txt:1 (cmake_minimum_required):
  CMake 3.14 or higher is required.  You are running version 3.10.2
```

**Comment by stuartmorgan** [comment]
Please do not intentionally file duplicates of your own issues.

**Comment by purencool** [comment]
Sorry @stuartmorgan I submitted it to the wrong project
