### ISSUE TITLE
Target file "android" not found.

### ISSUE THREAD

**Issue by vashisth00** [flutter/flutter#101755]
My application runs well on Windows same app when on M1 Mac 

# Target file "android" not found.

## Have tried running via android studio and in flutter run android it throws Target file "android" not found. same error for ios simulator

**Comment by maheshmnj** [comment]
Hi @vashisth00, Thanks for filing the issue.  Please share the output of `flutter doctor -v` and `flutter run -v` in a text file.
Also, does this error occur with a newly created project too?

**Comment by Lelelo1** [comment]
This occurred for me as well in every for every target . I just created a new project

**Comment by Lelelo1** [comment]
This occurs for me to with any target in a newly created flutter project
