### ISSUE TITLE
'flutter devices' command displays devices that are running under a different Linux user session.

### ISSUE THREAD

**Issue by safield** [flutter/flutter#101792]
I have two users on my Ubuntu 21.10 install.

-both have separate installs of the android sdk in their home folders. 
-I have install flutter using the official snap package.
-both users have created a separate avd entitled 'my_avd'.

When I start an instance of the emulator running 'my_avd' in one user session, then switch user session to the other user, when I run 'flutter devices' the other users 'my_avd' instance is displayed.

I can then run 'flutter run' on the other user, and flutter will build and try to install the apk on the emulator running in a different user session.

In this case, the install fails...

```
user@user-dev_machine:~/src/myapp/client$ flutter run
Using hardware rendering with device Android SDK built for x86 64. If you notice graphics artifacts, consider enabling
software rendering with "--enable-software-rendering".
Launching lib/main.dart on Android SDK built for x86 64 in debug mode...

Running Gradle task 'assembleDebug'...                             45.9s
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
cmd: Failure calling service activity: Broken pipe (32)
Installing build/app/outputs/flutter-apk/app.apk...                193ms
Error: ADB exited with exit code 1
Performing Streamed Install

adb: failed to install /home/user/src/myapp/client/build/app/outputs/flutter-apk/app.apk: cmd: Can't find service: package
Error launching application on Android SDK built for x86 64.
```

**Comment by maheshmnj** [comment]
Hi @safield, Thanks for filing the issue. Does this issue occur only with the emulator or when installing on physical device too? Can you try starting the emulator with a cold boot from the AVD manager ?

**Comment by safield** [comment]
Happens with cold boot as well. Dont have a physical device. Cheers.

**Comment by maheshmnj** [comment]
> When I start an instance of the emulator running 'my_avd' in one user session, then switch user session to the other user, when I run 'flutter devices' the other users 'my_avd' instance is displayed.

I am quite not sure if emulator instances are the same or different across different user sessions. However this seems more of an issue with adb (if it really is). Can you check if you are able to build and install a native app in a different session running in parallel as you did for flutter?

**Comment by safield** [comment]
I have reported the issue. It in your guys court now. Good luck!

**Comment by maheshmnj** [comment]
Labeling this issue for further investigation from the team 

cc: @christopherfujino any thoughts why this could be happening?

**Comment by blasten** [comment]
`adb` handles device discovery for the Flutter tool.  If you run `adb devices` and you see the emulators running for a different user session, there's very little we can do.

Please confirm, and reopen if you see different results.
