### ISSUE TITLE
Inserting a TabBarSelection doesn't cause its descendants to rebuild

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#1017]
Dynamically adding  a TabBarSelection ancestor of a TabBar or  a TabBarView will not cause the descendants to be rebuilt, which means that the TabBar and TabBarView will not automatically begin listening to the the TabBarSelection's performance. The problem generalizes to any TabBarSelection descendant that uses TabBarSelectionState.registerPerformanceListeners() to track the selection's performance.

It's not clear how to handle this.  Does TabBarSelection need to walk its subtree and rebuild nodes that implement some "I am going to register performance listeners" marking interface?

See also: https://github.com/flutter/flutter/pull/1007

**Comment by Hixie** [comment]
One option might be to have the selection announce its existence on initState.

**Comment by Hixie** [comment]
cc @HansMuller Is this even still relevant? I'm going to close this since we don't have a TabBarSelection anymore, but if this still makes sense in some way please reopen it.
