### ISSUE TITLE
Validate all .ci.yaml dependencies are pinned

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#101712]
The builder config is fragile when dependencies are not pinned to specific versions. Any upstream changes may cause breakage. We should create a test to validate all .ci.yaml dependencies are pinned.

This also requires we pin specific versions for all dependencies.

**Comment by CaseyHillers** [comment]
New ci.yaml validations can be added in https://cs.opensource.google/flutter/cocoon/+/main:app_dart/lib/src/model/ci_yaml/ci_yaml.dart;l=121

The issue is that the integration tests will likely fail until all the ci.yamls have had their dependencies pinned

**Comment by CaseyHillers** [comment]
New ci.yaml validations can be added in https://cs.opensource.google/flutter/cocoon/+/main:app_dart/lib/src/model/ci_yaml/ci_yaml.dart;l=121

The issue is that the integration tests will likely fail until all the ci.yamls have had their dependencies pinned

**Comment by godofredoc** [comment]
@keyonghan can you please reassign to Ricardo?

**Comment by keyonghan** [comment]
@ricardoamador Could you help take a look?

**Comment by ricardoamador** [comment]
Yeah I can look at this one.

**Comment by godofredoc** [comment]
Cocoon is now validating all the repos have pin dependencies and we are waiting on some repo PRs to land before the cocoon validations passes.
