### ISSUE TITLE
Website search bar disappear on mobile

### ISSUE THREAD

**Issue by Solido** [flutter/flutter#10178]
When browsing the API from a mobile search bar is no more accessible anywhere which make the navigation in all classes tedious.

**Comment by sethladd** [comment]
Thanks for the feedback!

**Comment by sethladd** [comment]
@jcollins-g should we move this to dartdoc repo?

**Comment by jcollins-g** [comment]
dart-lang/dartdoc#1348 covers this, and is among the bugs we'd like a designer to help with.

**Comment by sethladd** [comment]
Closing in favor of dartdoc issue.
