### ISSUE TITLE
`Google Testing` is hung after forward fix

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#101719]
I have a PR that broke "Google Testing", it required landing a forward fix inside of Google.  Then I went back to the PR and inside of the "Google Testing" dashboard I hit the "Sync & Test".  It showed an incorrect test CL for a while, now nothing shows up in the dashboard when you click on "Google Testing".

The PR: https://github.com/flutter/flutter/pull/101382

cc @CaseyHillers

**Comment by CaseyHillers** [comment]
I filed b/229007307 for internal discussions

**Comment by Piinks** [comment]
This has been happening consistently on multiple PRs. Beyond blocking PRs from landing in flutter/flutter, it has also been blocking the flutter roll when a revert PR gets stuck.

**Comment by Piinks** [comment]
This is the case of a roll blocker: https://github.com/flutter/flutter/pull/101929
This needs to be reverted for the roll, but I have rebased it multiple times and it is still hanging on the google testing shard

**Comment by yusuf-goog** [comment]
cc @XilaiZhang

**Comment by Piinks** [comment]
Another case of this: https://github.com/flutter/flutter/pull/100475
The contributor has rebased a few times now.

**Comment by jonahwilliams** [comment]
Also happening on https://github.com/flutter/flutter/pull/102085

Any workarounds I can employ from my end?

**Comment by CaseyHillers** [comment]
I'm still investigating this internally. tl;dr is that we're testing these PRs still, but the database is failing to write the PRs, so we lose the state.

Based on this, I'm not sure there's a fix contributors can apply at this time.

**Comment by CaseyHillers** [comment]
After some more debugging, the issue was our Spanner instance wasn't sized appropiately anymore. I've gone ahead and scaled it 6x.

If you still see issues, please report them here. I'll continue manually monitoring for the next week.

**Comment by CaseyHillers** [comment]
I don't see this occurring anymore. Closing, but please reopen if you're seeing this still.
