### ISSUE TITLE
Dilate/Erode filters created bounds warnings indicating inefficient bounds

### ISSUE THREAD

**Issue by flar** [flutter/flutter#101795]
When the Dilate/Erode filters were [added](https://github.com/flutter/engine/pull/32334), the DisplayList canvas unit tests started issuing warnings indicating that the measured bounds of the operations were much smaller than the indicated bounds of the rendering operation.

The bounds tests only "fail" if the rendering draws outside of the indicated bounds. If the bounds are larger, even much much larger, then the tests will pass, but warnings will be emitted to the console. Perhaps we should make the overly generous bounds also cause a failure to prevent future cases like this, but since the bounds functions are intended to allow conservative bounds, it is hard to be too strict on the bounds being tight.

In order to avoid run-away generous bounds in the tests we have a "Tolerance" object which can specify an allowed tolerance for the test in question. First, we try to make sure that the tests are demonstrating the kinds of cases that match the most liberal cases that the bounds account for (for example, using paths that generate large miters that must be accounted for in the bounds). If the theoretical maximum for the bounds can't be demonstrated by the test case, then we modify the tolerance to "forgive" that generous, but theoretically required over-estimate. (i.e. this test should have rendered bounds that are within 1 pixel of the computed bounds, that test might not fill all but 15 pixels of the computed bounds, etc - with an understanding of why these bounds are conservatively over-estimated in each case)

Nevertheless, these warnings should be investigated to see if the bounds we generate here are unnecessarily generous, or if there is an error in the rendering in which the attribute is not having the intended effect.

**Comment by flar** [comment]
Here is an example of the output:

```
[----------] 41 tests from DisplayListCanvas
[ RUN      ] DisplayListCanvas.DrawPaint
[       OK ] DisplayListCanvas.DrawPaint (2722 ms)
[ RUN      ] DisplayListCanvas.DrawColor
[       OK ] DisplayListCanvas.DrawColor (365 ms)
[ RUN      ] DisplayListCanvas.DrawDiagonalLines
[       OK ] DisplayListCanvas.DrawDiagonalLines (1483 ms)
[ RUN      ] DisplayListCanvas.DrawHorizontalLine
[ERROR:flutter/display_list/display_list_canvas_unittests.cc(214)] allowed pad: 4, 1
[ERROR:flutter/display_list/display_list_canvas_unittests.cc(2087)] Overflow for ImageFilter == Erode 1 (DisplayList built directly -> surface)
[ERROR:flutter/display_list/display_list_canvas_unittests.cc(2088)] pix bounds[51, 98 => 149, 102]
[ERROR:flutter/display_list/display_list_canvas_unittests.cc(2092)] dl_bounds[46, 96 => 154, 104]
[ERROR:flutter/display_list/display_list_canvas_unittests.cc(2097)] Bounds overflowed by up to 5, 2 (5.10204%, 50%)
[ERROR:flutter/display_list/display_list_canvas_unittests.cc(2103)] Total overflow area: 472 (+120.408%)
[ERROR:flutter/display_list/display_list_canvas_unittests.cc(2105)] 
[       OK ] DisplayListCanvas.DrawHorizontalLine (659 ms)
[ RUN      ] DisplayListCanvas.DrawVerticalLine
[ERROR:flutter/display_list/display_list_canvas_unittests.cc(214)] allowed pad: 1, 4
[ERROR:flutter/display_list/display_list_canvas_unittests.cc(2087)] Overflow for ImageFilter == Erode 1 (DisplayList built directly -> surface)
[ERROR:flutter/display_list/display_list_canvas_unittests.cc(2088)] pix bounds[98, 51 => 102, 149]
[ERROR:flutter/display_list/display_list_canvas_unittests.cc(2092)] dl_bounds[96, 46 => 104, 154]
[ERROR:flutter/display_list/display_list_canvas_unittests.cc(2097)] Bounds overflowed by up to 2, 5 (50%, 5.10204%)
[ERROR:flutter/display_list/display_list_canvas_unittests.cc(2103)] Total overflow area: 472 (+120.408%)
[ERROR:flutter/display_list/display_list_canvas_unittests.cc(2105)] 

...
```

**Comment by fzyzcjy** [comment]
Interesting question... I am not an expert in Skia implementations, so could you please give some hints what is "outset"/"inset"

**Comment by flar** [comment]
The code you wrote for DlDilate/ErodeImageFilter takes a rectangle in and returns a modified rectangle. You use the "outset" method to grow the rectangle in both cases. One of those should be the reverse computation since one grows the source material and the other shrinks it.

**Comment by flar** [comment]
Here are the 4 lines of code in question...

https://github.com/flutter/engine/blob/98754a64bb50b958fc03cb2008df77522caac8fc/display_list/display_list_image_filter.h#L211

https://github.com/flutter/engine/blob/98754a64bb50b958fc03cb2008df77522caac8fc/display_list/display_list_image_filter.h#L225

https://github.com/flutter/engine/blob/98754a64bb50b958fc03cb2008df77522caac8fc/display_list/display_list_image_filter.h#L271

https://github.com/flutter/engine/blob/98754a64bb50b958fc03cb2008df77522caac8fc/display_list/display_list_image_filter.h#L285

**Comment by fzyzcjy** [comment]
I see. I will try to dig into this problem when having time (I am not currently doing flutter yet).

**Comment by flar** [comment]
Fixed by ~https://github.com/flutter/engine/pull/34146~ https://github.com/flutter/engine/pull/34337
