### ISSUE TITLE
Document extensibility via normal dart package

### ISSUE THREAD

**Issue by xster** [flutter/flutter#10173]
Insightful conversation in Gitter:

User wants XML encoding/decoding, looks at https://pub.dartlang.org/flutter/plugins didn't find one though it's just a non-plugin normal dart package https://pub.dartlang.org/packages/xml

Glancing through the website, it's not evident that users can extend their flutter apps by composing existing dart packages

**Comment by eseidelGoogle** [comment]
@mit-mit is working with @kevmoo to get /flutter/plugins updated to include non-plugin packages.

**Comment by sethladd** [comment]
I think this is a dupe of https://github.com/flutter/flutter/issues/10070

Which should cover the "we need to document packages, in general, for Flutter"
