### ISSUE TITLE
[iOS][A11y] No way to format numbers without breaking voiceover

### ISSUE THREAD

**Issue by chunhtai** [flutter/flutter#101707]
b/227984662

```dart
import 'package:flutter/services.dart';
import 'package:flutter/material.dart';
void main() => runApp(MyApp());
class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}
class MyHomePage extends StatefulWidget {
  MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;
  @override
  _MyHomePageState createState() => _MyHomePageState();
}
class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(
          widget.title,
        ),
      ),
      body: Center(
        child: TextField(
          inputFormatters: [TestFormatter()],
          keyboardType: const TextInputType.numberWithOptions(decimal: true),
        ),
      ),
    );
  }
}
class TestFormatter extends TextInputFormatter {
  @override
  TextEditingValue formatEditUpdate(
      TextEditingValue oldValue,
      TextEditingValue newValue,
      ) {
    var formattedString = newValue.text;
    if (formattedString.length == 3) {
      formattedString = '${formattedString.substring(0, 1)},'
          '${formattedString.substring(1, formattedString.length)}';
    }
    return TextEditingValue(
      text: formattedString,
      selection: TextSelection.collapsed(offset: formattedString.length),
    );
  }
}
```

1. turn on voice over and type 1 2 3 4

expect: voiceover pronounce "one two three four"
actual voiceover pronounce "one two three thirty-four"

The intention is to create number formatting such as built-in Calculator app.

**Comment by LongCatIsLooong** [comment]
Unfortunately, `UITextField` makes the same strange voiceover announcement ("one", "two", "three", "thirty-four"), and I couldn't find a reasonable way to fix that even in a UIKit app. The accessibility runtime seems to have private logic to determine what to announce when text is inserted into a text field, and it doesn't seem to work well when the insertion does not happen at the caret location.

However I've found a workaround. You can announce the new character via the `SemanticsService.announce(String, TextDirection)` API. The new announcement will override the incorrect system announcement if posted immediately after the system announcement. The downside I noticed is the announcement will be made in a different tone. You can try this out by adding this to your `onChanged` callback:
```dart
            onChanged: (String newText) {
              if (newText.isNotEmpty) {
                SemanticsService.announce(newText.characters.last, TextDirection.ltr);
              }
            },
```
It will be a bit tricky to figure out the actual character to announce, it would be easier if the user is forced to use an in-app numpad to enter the text, like the iOS Calculator does.

**Comment by LongCatIsLooong** [comment]
A side note, overriding [`accessibilityValue`](https://developer.apple.com/documentation/uikit/uiaccessibilityelement/1619583-accessibilityvalue?language=objc) unfortunately does not (completely) fix this.  if I override the `accessibilityValue` getter this way: 
```swift
  get { super.accessibilityValue.filter { $0 != "," } }
```
Voiceover would announce "one thousand two hundred and thirty four" when "4" is entered, but would only announce the single digit being entered when there's no comma.

**Comment by chunhtai** [comment]
@LongCatIsLooong the voiceover is listening to textinputplugin change, not the accessibilityValue of the SemanticsObject if i remember correctly.

The voiceover provides API to change the pitch, but we didn't surface it to flutter.

**Comment by LongCatIsLooong** [comment]
@chunhtai I did my test in a UIKit app so what I described above is the behavior of a `UITextField`. The iOS [`UIAccessibilityPostNotification`](https://developer.apple.com/documentation/uikit/1615194-uiaccessibilitypostnotification?changes=l_2&language=objc) API doesn't allow us to specify what pitch to use. I think the system keyboard uses a private notification type thus the different pitch. I noticed the Cash app announces the amount using the same pitch so I'm guessing they're posting an announcement notification too.

**Comment by chunhtai** [comment]
i vividly remember there is a flag to set the tone, but i couldnt find it now, maybe i remembered it wrong. yeah it seems the using announcement may be the right way

**Comment by LongCatIsLooong** [comment]
The only thing i found is https://developer.apple.com/documentation/uikit/uiaccessibilityspeechattributepitch?language=objc

**Comment by chunhtai** [comment]
ah yes, if you sends the NSAttributedString to the announce, I assume it will change the pitch?

**Comment by LongCatIsLooong** [comment]
Ah awesome that did change the pitch.

**Comment by LongCatIsLooong** [comment]
Update: waiting for the original reporter of the issue to confirm the validity of the workaround. I'll close this issue if this does fix their problem.

**Comment by Hixie** [comment]
@LongCatIsLooong if this does work, is there documentation / sample code we should edit to make it clear how to do this?

**Comment by LongCatIsLooong** [comment]
In `TextField`/`CupertinoTextField`/`EditableText`? I'll add something once it's confirmed
