### ISSUE TITLE
[Google maps plugin] Please update underlying iOS SDK 

### ISSUE THREAD

**Issue by neiljaywarner** [flutter/flutter#101723]
re: ios (latest version of flutter maps)
https://github.com/flutter/flutter/issues/101717
`Google Maps SDK for iOS version: 4.2.0.0
New version of Google Maps SDK for iOS available: 6.1.1.0
`

**Comment by stuartmorgan** [comment]
The plugin does not currently pin a version of the iOS maps SDK; Cocoapods should be giving you the latest version that is compatible with the version of iOS you are targeting. If you want a newer maps SDK on iOS, you would have to drop support for older versions of iOS.

See https://developers.google.com/maps/documentation/ios-sdk/releases for support details.
