### ISSUE TITLE
flutter dashboard task detail shows invalid "Running for" time

### ISSUE THREAD

**Issue by yusuf-goog** [flutter/flutter#101845]
See screenshot, the "Running for time looks like its broken":

![image](https://user-images.githubusercontent.com/91688203/163233042-d86d9327-9e7f-40be-9f69-f2c5b301b623.png)

**Comment by CaseyHillers** [comment]
@XilaiZhang can you dedupe this against your open bug?

**Comment by XilaiZhang** [comment]
Yeah I thought Casey kindly fixed this in https://github.com/flutter/cocoon/pull/1611, not sure why this is happening again

**Comment by CaseyHillers** [comment]
This is because these targets are using the luci scheduler. One's using the new scheduler have this fixed

**Comment by XilaiZhang** [comment]
Just asking, what would be the approximate time for the migration from luci scheduler to cocoon scheduler complete?

**Comment by CaseyHillers** [comment]
> Just asking, what would be the approximate time for the migration from luci scheduler to cocoon scheduler complete?

ETA this quarter

**Comment by keyonghan** [comment]
Now everything is in cocoon scheduler: https://github.com/flutter/flutter/issues/92300, and the issue is fixed.
