### ISSUE TITLE
ImageFilter.dilate/ImageFilter.erode not supported on the web.

### ISSUE THREAD

**Issue by fzyzcjy** [flutter/flutter#101874]
Please see https://github.com/flutter/flutter/pull/101036

**Comment by darshankawar** [comment]
@fzyzcjy 
Isn't this issue same as the one you already reported and has been labeled ? https://github.com/flutter/flutter/issues/101085
Closing this as duplicate.

**Comment by fzyzcjy** [comment]
You are right. Was creating this to satisfy code requirement in https://github.com/flutter/flutter/pull/101036 and did not notice the duplicate
