### ISSUE TITLE
[Proposal]: Give more flexibility to place the menu of the PopupMenuButton

### ISSUE THREAD

**Issue by Haidar0096** [flutter/flutter#101849]
When using `PopupMenuButton`, you can only specify the offset of the menu which is not great by itself because if you want to place the menu relative to the button itself there is no way to do that other than either doing  a dirty hack like defining an extension like this for example 
```
extension TextExtension on Text {
  /// Calculates the size of the text inside this text widget.
  /// note: this method supposes ltr direction of text, which is not always true, but it doesn't affect the size that much, so
  /// keep in mind that the size returned may be approximate in some cases.
  /// The text inside this widget must be non-null before calling this method.
  Size getSize({TextDirection? textDirection}) {
    TextPainter tp = TextPainter(
        text: TextSpan(text: data),
        textDirection: textDirection ?? TextDirection.ltr)
      ..layout();
    return tp.size;
  }
}
```
and then using it like this 
```
Widget _dropDownMenu({
    required BuildContext context,
    required String title,
    required List<PopupMenuItem> items,
  }) {
    final text = Text(
      title,
      style: Theme.of(context).textTheme.bodyMedium,
    );
    final textSize = text.size;
    return PopupMenuButton(
        child: text,
        itemBuilder: (context) => items,
        offset: Offset(0, textSize.height),
      );
  }
```

Or you have to modify the source code directly like I did in my answer [here on SO](https://stackoverflow.com/a/71854465/9142279)

Now If someone of the flutter maintainers tell me I may be able to make a pull request implementing this feature. Let me know if it would be a welcomed change.

I want to note that I saw a partial implementation of this feature on channel master (not on stable yet) here at #98979 but that implementation is still defecit imo since it only gives me two options of placing the menu relative to the button which are only `above` or `below`, have a look at my answer on SO (link above) and you will see that it is more flexible solution than the one in #98979.

This is an image of what I am trying to achieve:
![image](https://user-images.githubusercontent.com/49842031/163242832-f9ac92ed-bb03-4a01-8b7a-455256967760.png)

Thank you.

**Comment by darshankawar** [comment]
@Haidar0096 
I tried below code sample and used `position` property of the widget which gave me below result:

![Screenshot 2022-04-14 at 12 13 44 PM](https://user-images.githubusercontent.com/67046386/163329041-177da7c2-4d63-4b20-8618-77c66a0f9bf7.png)


<details>
<summary> code sample </summary>

```
//import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';

void main() {
  runApp(MyApp());
}
class MyApp extends StatefulWidget {
  @override
  _MyState createState() {
    return _MyState();
  }
}
class _MyState extends State<MyApp>
{
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        home: Scaffold(
          appBar: AppBar(
            backgroundColor: Colors.deepPurple,
            title: Text("Flutter Popup Menu Button"),

          ),
          body: Center(
            child: PopupMenuButton(
                offset: Offset(-10,10),
                position: PopupMenuPosition.under,
                itemBuilder: (context) => [
                  PopupMenuItem(
                    child: Text("First"),
                    value: 1,
                  ),
                  PopupMenuItem(
                    child: Text("Second"),
                    value: 2,
                  )
                ]
            ),
          ),
        )
    );
  }
}

```

</details>

From your screenshot, are you looking to not have the gap between button and popup menu or looking to have a way to place the popup menu exactly below the button ?

As you can from the code I shared, I used `offset` and `position` properties. Do they help to achieve your case ?

**Comment by Haidar0096** [comment]
> 

I was originally looking to place the menu exactly under the button as you shown in your example, but then pskink suggested that an offset builder that gives the button size will give more control to the developer on how to place the menu relative to the button size (and starting from an origin offset (0,0) being at top left of the button). Do you think this is better than the currently implemented solution on master channel?

This is how it looks like in implementation in the `showButtonMenu` in the `PopupMenuButtonState`:

```
...
final Offset offset = widget.offsetBuilder(button.size);
    final RelativeRect position = RelativeRect.fromRect(
      Rect.fromPoints(
        button.localToGlobal(offset, ancestor: overlay),
        button.localToGlobal(button.size.bottomRight(Offset.zero) + offset, ancestor: overlay),
      ),
      Offset.zero & overlay.size,
    );
...
```

**Comment by Haidar0096** [comment]
@darshankawar also sorry I was referencing the wrong issue (typo error), I updated the original above to link to the right issue

**Comment by darshankawar** [comment]
@Haidar0096 
I looked at the PR you raised for this change and the fix seem to remove current implementation of using `enum` to make way for `offsetBuilder` you proposed. Can you provide new implementation using it that'll help to achieve the placing of PopupMenuButton's menu ?

**Comment by Haidar0096** [comment]
@darshankawar I am sorry I don't understand what are you asking for, the implementation of the feature is already in the pull request (along with its tests), so what implementation do you mean exactly? 

> @Haidar0096 I looked at the PR you raised for this change and the fix seem to remove current implementation of using `enum` to make way for `offsetBuilder` you proposed. Can you provide new implementation using it that'll help to achieve the placing of PopupMenuButton's menu ?

**Comment by darshankawar** [comment]
> so what implementation do you mean exactly?

I meant `offsetBuilder`'s usage to achieve what you have been looking for, ie, below:

![Screenshot 2022-04-14 at 5 35 14 PM](https://user-images.githubusercontent.com/67046386/163387169-8023cd41-905f-4a9c-965a-00b5d3bbbe80.png)

Does `offsetBuilder` help to remove the gap between button and popupMenu and helps to position it exactly below the button ?

**Comment by Haidar0096** [comment]
you got me wrong I think.
There is no gap problem. This is normal because I added a Container in this example in the picture around the button
The problem is that wherever the popup menu button is, you can't get its size in order to determine where you want the offset of the opened menu to be. So you either have to guess its size or you are constrained with a menu button that only gives you an offset option that you can pass but you can't relate it to the size of the button.
As for how the new PR solves this problem, I put the answer in the SO question mentioned above, should I write it here?

**Comment by darshankawar** [comment]
Thanks for the feedback. That helped to answer my question.

I am labeling it as a proposal.

**Comment by Haidar0096** [comment]
> Thanks for the feedback. That helped to answer my question.
> 
> I am labeling it as a proposal.

thank you too, one last question since this is my first pull request, what does this mean now, may it be accepted or should I do something further?

**Comment by justinmc** [comment]
@Haidar0096 What changed that made you close this as completed?  Was some PR merged that isn't linked here?
