### ISSUE TITLE
[Google_maps_flutter] Unable to tap on maptoolbar and zoomControls on device, however the maptoolbar and zoomControls work with emulator.

### ISSUE THREAD

**Issue by Fluttergam** [flutter/flutter#101880]
I'm using google_maps_flutter from pub.dev for my flutter application.

I'm having an issue where when I click a marker, the map toolbar slides in from the right hand corner of the screen as it should, but I cannot tap on the mapToolbar buttons. The toolbar just slides back out of view when I tap it. I also am not able to tap on the zoomControls buttons. I am able to tap on the compass button just in case that matters.

The weird thing is that I only have this problem when I'm using a real device. If I use an emulator, I am able to tap on the map toolbar buttons which brings me to Google Maps and the zoomControls buttons.

I'm not sure what is going on and googling has led me nowhere.

I have already tried the following,

Remove the Google Map widget from a Stack,

I've tried to add the gestureRecognizers like this,

```
gestureRecognizers: <Factory<OneSequenceGestureRecognize>> [
    new Factory <OneSequenceGestureRecognizer> (
        () => new EagerGestureRecognizer(),
    ),
].toSet()
```
If you don't mind pointing me in the right direction to solve this issue, I'd appreciate it!

**Comment by darshankawar** [comment]
@Fluttergam 
Is this happening on Android or iOS ?
Can you try the plugin [example](https://github.com/flutter/plugins/tree/main/packages/google_maps_flutter/google_maps_flutter/example) and see if you still get same behavior ? You may just need to add your api key to it before running.

**Comment by Fluttergam** [comment]
@darshankawar 

Thanks for getting back to me!

This is happening on Android.

I am very new to coding and I'm not sure how to try the plugin example you linked, if you could provide information on that I would be happy to try the plugin example to see if I get the same behavior. 

I added my generated google maps platform api key to the android/app/src/main/AndroidManifest.xml for my app. 

I checked my cloud console account and I have 371 requests for Maps SDK for Android so I think the api is working. 

Is there anything else you need from me that will help solve this issue?

**Comment by Fluttergam** [comment]
I guess I'll copy and paste everything from the lib file in the example, I bet there is an easier way to do it though!

**Comment by Fluttergam** [comment]
@darshankawar 

Ok I used the plugin example and I am still getting the same behavior. Any idea of what to try next? Thanks for your initial response!

**Comment by darshankawar** [comment]
@Fluttergam 
Thanks for trying out the plugin. Usually you would need to just clone the entire `flutter/plugins` repo so that you'll get all plugins under it and then you can select the maps plugin example and run directly by adding your api key in manifest file.

What device are you verifying this on ? I tried on Samsung S10 but don't get the behavior you are reporting.

**Comment by Fluttergam** [comment]
@darshankawar 

I'm on a Pixel 5a running Android 12.

I tested my app on a Pixel 5a running 11 and the map toolbar works fine. I also tested my app on a Pixel 2XL running Android 11 and it works fine. 

Is your device running Android 11 or 12? 

It seems that the only difference between my devices is that the working one is running 11 and the other is running 12.

**Comment by huycozy** [comment]
Hi, I can not reproduce this issue on my device (Pixel 3a - Android 12). I can use map toolbar button normally (zoom in/out, camera, open google map app...)

- Sample code: https://github.com/flutter/plugins/tree/main/packages/google_maps_flutter/google_maps_flutter/example
- Demo:

https://user-images.githubusercontent.com/104349824/166875459-1fccf1f9-3abb-4a2f-aa19-9596247af14d.mp4
