### ISSUE TITLE
flutter.gradle shrink default settings in the flutter_tools

### ISSUE THREAD

**Issue by LailaiMaster** [flutter/flutter#101893]
I have a problem with using the resouce file.
When I built APK using release, the image resources were not displayed correctly.
I added setting shrinkResources false in the app/build.gradle  file,which is correct.
I read the commits of the  ‘flutter_tools/gradle/flutter.gradle’ file and had some questions.
<img width="1476" alt="wecom-temp-9b80866d35beceadf0d9e1097dc4853c" src="https://user-images.githubusercontent.com/19606597/163354503-f54da95c-42db-4f40-b454-eda854c6f033.png">
<img width="1480" alt="企业微信截图_07e58c46-e974-4e82-8868-926c2443e964" src="https://user-images.githubusercontent.com/19606597/163354894-ebbc5f59-49e5-47eb-be48-8265e1036ddf.png">
<img width="1528" alt="企业微信截图_c56c53e6-b403-4a06-8c62-9d5f85ca1bd7" src="https://user-images.githubusercontent.com/19606597/163355249-d8a2d2ca-e58b-44b3-8dc8-11ddf61939d1.png">
This small change can be confusing for developers, and I think it should be false.

**Comment by maheshmnj** [comment]
Hi @LailaiMaster, Thanks for filing the issue. Can you please share the steps to reproduce the issue along with the output of `flutter doctor -v`? 

> When I built APK using release, the image resources were not displayed correctly.

Can you please explain what exactly the issue is?

**Comment by LailaiMaster** [comment]
> Hi @LailaiMaster, Thanks for filing the issue. Can you please share the steps to reproduce the issue along with the output of `flutter doctor -v`?
> 

[✓] Flutter (Channel stable, 2.10.3, on macOS 12.1 21C52 darwin-arm, locale zh-Hans-CN)
    • Flutter version 2.10.3 at /Users/lijian/work/flutter2.10.3
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (6 weeks ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

> > When I built APK using release, the image resources were not displayed correctly.
> 
> Can you please explain what exactly the issue is?
You can see https://github.com/flutter/flutter/pull/101898.
I think function “shouldShrinkResources”default is ‘true’ has side effects. 
I use " context.resources.getIdentifier(resPath, "drawable", context.packageName)"fetch Drawable is error.Can not be displayed correctly. 
Because ShrinkResources has a side effect, it should default to false.

**Comment by maheshmnj** [comment]
Thanks for the info @LailaiMaster. 

> I use " context.resources.getIdentifier(resPath, "drawable", context.packageName)"fetch Drawable is error.Can not be displayed correctly.
Because ShrinkResources has a side effect, it should default to false.

Labeling this issue as a proposal and for further insights from the team

**Comment by LailaiMaster** [comment]
@maheshmnj  I write a demo https://github.com/LailaiMaster/shrink_demo。
debug run is no problem.


![屏幕录制2022-04-14 下午9 52 18](https://user-images.githubusercontent.com/19606597/163408859-9594b3c6-8462-4828-a338-27df4fa5ffaf.gif)

use “flutter build --release” is error
![屏幕录制2022-04-14 下午9 53 11](https://user-images.githubusercontent.com/19606597/163408987-3a8b61c5-967b-4df9-9a6f-ea7881306f2b.gif)

**Comment by LailaiMaster** [comment]
@maheshmnj  Can you help me about https://github.com/flutter/flutter/pull/101898 checklist “ci.yaml validation Failing after”？

**Comment by christopherfujino** [comment]
As noted on your PR, this function was introduced in https://github.com/flutter/flutter/commit/ee417827323e68560c7e5cb97276474d5ce3cdf0 and has always defaulted to true. The function in the diff of https://github.com/flutter/flutter/pull/40610 that returns false is `shouldUseProguard`.

**Comment by christopherfujino** [comment]
Actually, I see Gary's commit comes AFTER Emmanuel's PR, so I'm confused too.

**Comment by blasten** [comment]
https://github.com/LailaiMaster/shrink_demo/blob/aa1602ea9a740cc98938e75cc92a201413fd4d9e/demo_plugin/android/src/main/kotlin/com/example/demo_plugin/DemoPlugin.kt#L38

I don't think this is meant to work this way. The Android shrinker runs at build time, and uses code analysis. If your code doesn't reference the resource directly, it will be removed from the APK.  See https://developer.android.com/guide/topics/resources/drawable-resource for more.


You can also run `flutter build apk --release --no-shrink`, although I highly doubt we will change the default for this use case.

**Comment by LailaiMaster** [comment]
> 



> Actually, I see Gary's commit comes AFTER Emmanuel's PR, so I'm confused too.

that‘s true, I repeat？

**Comment by LailaiMaster** [comment]
@blasten 
> https://github.com/LailaiMaster/shrink_demo/blob/aa1602ea9a740cc98938e75cc92a201413fd4d9e/demo_plugin/android/src/main/kotlin/com/example/demo_plugin/DemoPlugin.kt#L38
> 
> I don't think this is meant to work this way. The Android shrinker runs at build time, and uses code analysis. If your code doesn't reference the resource directly, it will be removed from the APK. See https://developer.android.com/guide/topics/resources/drawable-resource for more.
> 
> You can also run `flutter build apk --release --no-shrink`, although I highly doubt we will change the default for this use case.
I agree `flutter build apk --release --no-shrink`，but I think 'flutter build apk --release'  is used more frequently than `flutter build apk --release`, unable shrink by default reduces the chance of an error,right?
