### ISSUE TITLE
The text of the tooltip is not centered for --web-renderer=html

### ISSUE THREAD

**Issue by JDongKhan** [flutter/flutter#101885]
![苏宁豆芽图片20220414154326135](https://user-images.githubusercontent.com/4929805/163341949-7a040588-a739-49bd-aac4-7274e0871a7c.png)

[✓] Flutter (Channel stable, 2.10.4, on macOS 12.1 21C52 darwin-x64, locale zh-Hans-CN)
    • Flutter version 2.10.4 at /Users/jd/fvm/versions/2.10.4
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (3 weeks ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

**Comment by darshankawar** [comment]
@JDongKhan 
Can you provide a runnable minimal code sample that shows the issue ?

**Comment by JDongKhan** [comment]
https://github.com/JDongKhan/flutter_admin_universal
@darshankawar  this is my demo.

**Comment by JDongKhan** [comment]
It happens in chrome。 
![苏宁豆芽图片20220414165725108](https://user-images.githubusercontent.com/4929805/163350941-24d52b11-2709-4f86-9df1-e586ddf847b1.png)

**Comment by JDongKhan** [comment]
![image](https://user-images.githubusercontent.com/4929805/163351171-0176f811-fccf-444a-b1eb-9c6ab7633f6e.png)

**Comment by JDongKhan** [comment]
It looks normal on safari

**Comment by darshankawar** [comment]
@JDongKhan 
Thanks for the repo, but it seems to be your entire app, but we only need a minimal reproducible code sample without any third party plugins that would be enough to replicate the behavior you are reporting.

Also, while looking for similar case, I found this issue which looks similar to yours. Please check that and confirm.

https://github.com/flutter/flutter/issues/74810

**Comment by JDongKhan** [comment]
All newly created projects have this problem！
@darshankawar 
[苏宁豆芽图片20220414194413623](https://user-images.githubusercontent.com/4929805/163384693-5b149e74-0c37-4253-8c39-9dcd3b30a486.png)

**Comment by darshankawar** [comment]
@JDongKhan 
I tried by creating new project using latest stable and ran it using html rendering, but didn't observe the behavior you reported. I see the tooltip rendering properly and not cut-off at right:

![Screenshot 2022-04-14 at 5 57 43 PM](https://user-images.githubusercontent.com/67046386/163390798-2ed466d4-984d-45cb-9342-7120b115ba96.png)

```
[✓] Flutter (Channel stable, 2.10.4, on macOS 12.2.1 21D62 darwin-x64, locale
    en-GB)
    • Flutter version 2.10.4 at /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (3 weeks ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2
```

One thing I noticed is, you are on Google chrome browser `100.0.x` which may be a reason. I am on lesser version of it.
Is there a way for you to downgrade chrome browser version and try again to see if it still persists on that version ?

**Comment by JDongKhan** [comment]
My windows computer has the same problem.

[√] Flutter (Channel stable, 2.10.4, on Microsoft Windows [Version 6.1.7601], locale zh-CN)
    • Flutter version 2.10.4 at D:\flutter\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (3 weeks ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

![image](https://user-images.githubusercontent.com/4929805/163400924-8d5ddc38-6047-4dba-a5d6-bcd9a9cc68fe.png)

![image](https://user-images.githubusercontent.com/4929805/163401200-717c57f9-123c-40f6-b1a2-3937ea4dc46a.png)

**Comment by JDongKhan** [comment]
https://github.com/JDongKhan/flutter_web_demo.git

This is my minimal code sample.

**Comment by darshankawar** [comment]
@JDongKhan 
Thanks for the repro. Can you try the same on latest master too ?

`flutter channel master`
`flutter upgrade`
