### ISSUE TITLE
Running with --local-engine doesn't trigger Podfile.lock update

### ISSUE THREAD

**Issue by cbracken** [flutter/flutter#10183]
## Steps to Reproduce

Launch an iOS simulator, then from a Flutter app dir that includes a Podfile:
1. `flutter run`
1. Terminate the run.
1. `flutter run --local-engine ios_debug_sim_unopt`

Expected: app launches with local engine.
Actual: app launches with the engine specified when `pod install` was last run.

In `ios/Flutter/Generated.xcconfig`:
```
FLUTTER_FRAMEWORK_DIR=/Users/cbracken/src/flutter/engine/src/out/ios_debug_sim_unopt
LOCAL_ENGINE=/Users/cbracken/src/flutter/engine/src/out/ios_debug_sim_unopt
```

In Podfile.lock:
```
DEPENDENCIES:
  - Flutter (from `/Users/cbracken/src/flutter/flutter/bin/cache/artifacts/engine/ios`)

EXTERNAL SOURCES:
  Flutter:
    :path: /Users/cbracken/src/flutter/flutter/bin/cache/artifacts/engine/ios

```

The workaround I've been using is to delete `ios/Podfile.lock` then manually run:
```
cd ios
FLUTTER_FRAMEWORK_DIR=$HOME/src/flutter/engine/src/out/ios_debug_sim_unopt  pod install
cd ..
```

## Flutter Doctor

```
[✓] Flutter (on Mac OS X 10.12.5 16F73, channel master)
    • Flutter at /Users/cbracken/src/flutter/flutter
    • Framework revision 9d3fb1f309 (5 hours ago), 2017-05-18 11:26:43 -0700
    • Engine revision 82815836eb
    • Tools Dart version 1.23.0-dev.11.11
```

**Comment by xster** [comment]
Are you using plugins? 
Also when was the project `flutter create`d?

**Comment by cbracken** [comment]
I'm using `examples/layers` with `services/lifecycle.dart` as main.

**Comment by xster** [comment]
It probably doesn't work without --local-engine too right? We should `pod deintegrate` that project

**Comment by cbracken** [comment]
There's a separate issue (#10180) for non-default entrypoints, if that's what you're referring to?

**Comment by cbracken** [comment]
I suspect a quick fix to this would be to add Generated.xcconfig to the inputs to the fingerprinting added in #17274, now that that's landed.

**Comment by cbracken** [comment]
Turns out I *did* add Generated.xcconfig to the set of inputs to fingerprinting in #17274. This should now be working.
