### ISSUE TITLE
I'm unable to run my android emulator. I have already checked flutter doctor in cmd and no issues has been found.

### ISSUE THREAD

**Issue by JunShong99** [flutter/flutter#101877]
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.10.4, on Microsoft Windows [Version 10.0.22000.556], locale en-MY)
[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.1.3)
[√] Android Studio (version 2021.1)
[√] VS Code (version 1.66.1)
[√] Connected device (4 available)
[√] HTTP Host Availability

• No issues found!-

```However, it shows built failed with an exception as below```

Launching lib\main.dart on Android SDK built for x86 in debug mode...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     AAPT: error: failed to open APK: Invalid file.

**Comment by darshankawar** [comment]
@JunShong99 
Can you provide `flutter run -v` ? The log will be huge so you can put that in a text file and share it here.

**Comment by JunShong99** [comment]
Hi @darshankawar, here is how the error shows. 
![image](https://user-images.githubusercontent.com/60839609/163408531-f8b8a987-45e5-49c0-90b3-8d73613a45b5.png))

**Comment by darshankawar** [comment]
@JunShong99 
Please don't provide error log in screenshots as we can't use or search using it. As requested, please run `flutter run -v` and copy entire log in text file and share the file here.
