### ISSUE TITLE
[CP] Always finish the timeline event logged by Element.inflateWidget

### ISSUE THREAD

**Issue by jason-simmons** [flutter/flutter#101867]
### issue_link

https://github.com/flutter/flutter/issues/101379

### Commit Hash

https://github.com/flutter/flutter/commit/c62d103bb651a32f6a502c4ace955a7a05a34510

### Target

beta

### Impacted Users

All devs and users

### Impact Description

The framework will emit timeline events with a start and no matching end in some situations.  This will cause problems for applications like DevTools that expect a timeline in the correct format.

### Workaround

No - all timeline clients such as DevTools would need to apply a workaround

### Risk

low

### Test Coverage

yes

### Validation Steps

Do the steps in https://github.com/flutter/flutter/issues/101379#issuecomment-1097208819 and verify that the warning message is not present

**Comment by CaseyHillers** [comment]
This was included in https://github.com/flutter/flutter/pull/102193 and will ship in todays beta hotfix.
