### ISSUE TITLE
How to make Flutter run on GPU-1

### ISSUE THREAD

**Issue by gaddlord** [flutter/flutter#101808]
## Use case

When running flutter Windows application it defaults to GPU-0.

In my case GPU-0 is the default motherboard Intel UHD Graphics 630 processor which is inferior. I also have a NVIDIA Quadro T1000 as GPU-1.

How I can instruct Flutter to run on GPU-1?

## Proposal

Allow programmatically determine against which GPU to run or at least pick the one which is more powerful by default.

**Comment by maheshmnj** [comment]
Hi @gaddlord, Thanks for filing the issue. I am quite not sure if this is possible as of today. Labeling this issue for further insights from the team.

cc: @chinmaygarde

**Comment by chinmaygarde** [comment]
This isn't possible today but it is a fair ask. We don't have a way for embedders to select the device on engine startup at all.

**Comment by gaddlord** [comment]
Perhaps if not possible to control on the developers end to at least default to the more powerful GPU on boot?

**Comment by zanderso** [comment]
From feature request triage: cc @cbracken for input.

**Comment by cbracken** [comment]
@gaddlord can you provide a bit more information on your use-case? 

I can imagine energy conscious users (e.g. laptop users) may want the opposite behaviour. I imagine what you might want is something like new functionality in the API we expose to the C++ bits of the Flutter template that developers could use to specify whether their app would like to request to take advantage of the more performant GPU? 

For one-off scenarios, you should be able to set this manually for your own use:
https://www.howtogeek.com/351522/how-to-choose-which-gpu-a-game-uses-on-windows-10/

It doesn't appear that there's any such Windows API for doing this, but you could have the C++ runner portion of your Flutter app do this with a registry setting, though it's not picked up until the next run:
https://stackoverflow.com/questions/59732181/programmatically-set-graphics-performance-for-an-app

I'm not a Direct3D wizard, but a bit of quick searching didn't turn up any obvious API for this that wasn't driver-specific. If people have pointers, it's something we might consider. In the meantime, a few pointers to pages I ran into in a quick search: 
* https://stackoverflow.com/questions/6306190/is-there-a-way-to-programmatically-select-the-rendering-gpu-in-a-multi-gpu-envir
* https://stackoverflow.com/questions/16823372/forcing-machine-to-use-dedicated-graphics-card

**Comment by gaddlord** [comment]
Thanks @cbracken. My app is not very GPU intensive, my request was more of curiosity since I wrongly presumed this should have been something easy to choose from. Turned out not to be the case.
This is not a show stopper for me so perhaps we can close the feature request for now.

**Comment by cbracken** [comment]
Sounds good!
