### ISSUE TITLE
The camera customization UI is upside down

### ISSUE THREAD

**Issue by sdqyang** [flutter/flutter#101878]
I saw when send command device left and iOS execute device right, like this:

```
if ([orientation isEqualToString:@"portraitDown"]) {
    return UIDeviceOrientationPortraitUpsideDown;
  } else if ([orientation isEqualToString:@"landscapeLeft"]) {
    return UIDeviceOrientationLandscapeRight;
  } else if ([orientation isEqualToString:@"landscapeRight"]) {
    return UIDeviceOrientationLandscapeLeft;
  } else if ([orientation isEqualToString:@"portraitUp"]) {
    return UIDeviceOrientationPortrait;
}

```
but why 
```
 if (deviceOrientation == UIDeviceOrientationPortrait) {
    return AVCaptureVideoOrientationPortrait;
  } else if (deviceOrientation == UIDeviceOrientationLandscapeLeft) {
    // Note: device orientation is flipped compared to video orientation. When UIDeviceOrientation
    // is landscape left the video orientation should be landscape right.
    return AVCaptureVideoOrientationLandscapeRight;

  } else if (deviceOrientation == UIDeviceOrientationLandscapeRight) {
    // Note: device orientation is flipped compared to video orientation. When UIDeviceOrientation
    // is landscape right the video orientation should be landscape left.
    return AVCaptureVideoOrientationLandscapeLeft;
  } else if (deviceOrientation == UIDeviceOrientationPortraitUpsideDown) {
    return AVCaptureVideoOrientationPortraitUpsideDown;
  } else {
    return AVCaptureVideoOrientationPortrait;
  }

```
The above is based on the value transfer direction of flutter, and the following is based on the direction of real equipment. Are there any special scenes

 **Why does videoOrientation not follow deviceOrientation? 
 Doing so will cause the up and down directions of the custom camera UI to be reversed**

**Comment by darshankawar** [comment]
@sdqyang 
This is because `Flutter` uses `Orientation` while `camera` uses `DeviceOrientation`. I think that's why the orientation may not match.
Also `Orientation` only has `landscape` and `portrait` and it doesn't allow users to differentiate between left vs right landscape mode, or regular portrait vs upside-down portrait and hence the difference you are seeing.

Does this sound helpful ?

**Comment by sdqyang** [comment]
First flutter has landscapeLeft :
enum DeviceOrientation {
  portraitUp,
  landscapeLeft,
  portraitDown,
  landscapeRight,
}

and I mean:Why does videoOrientation not follow deviceOrientation? Doing so will cause the up and down directions of the custom camera UI to be reversed

**Comment by darshankawar** [comment]
@sdqyang 
Check below similar issues and see if they sound same as your case :

https://github.com/flutter/flutter/issues/27201
https://github.com/flutter/flutter/issues/89216
https://github.com/flutter/flutter/issues/98486
