### ISSUE TITLE
Regression in frame build, rasterizer time and image cache usage

### ISSUE THREAD

**Issue by iskakaushik** [flutter/flutter#101821]
https://github.com/flutter/flutter/commit/9984ebbaee6d65b422a295f0e752b88f4e237cea seems to have caused significant regressions in frame build and rasterizer times.

See:

1. https://flutter-flutter-perf.skia.org/e/?begin=1649795346&end=1649827149&keys=X44f2997b935700a584e6171aecc187e7&num_commits=50&request_type=1&xbaroffset=28337
2. https://flutter-flutter-perf.skia.org/e/?begin=1649795346&end=1649827149&keys=Xda7acf4f3f3c170c56436823adfacb57&num_commits=50&request_type=1&xbaroffset=28337

**Comment by zanderso** [comment]
https://github.com/flutter/flutter/pull/101786 was supposed to fix a memory regression, but it looks like it has had unintended side-effects. We should likely revert.

**Comment by jonahwilliams** [comment]
Reverting!

**Comment by jonahwilliams** [comment]
This has been reverted

**Comment by ds84182** [comment]
See #97987 which may affect this.
