### ISSUE TITLE
[url_launcher] if the url changes after call launch(url), could you return the newly changed url when call closeWebView()

### ISSUE THREAD

**Issue by AugustWangVeeva** [flutter/flutter#101800]
## Use case
I want use the url_launcher to do sso login, and after sign up, then URL will change to successfully login URL with parameters, I want get the parameters in the new URL and close the webview.

**Comment by darshankawar** [comment]
@AugustWangVeeva 
Can you provide a practical use case or code sample along with current and expected behavior you are looking for when using this plugin ?

**Comment by AugustWangVeeva** [comment]
like I use await launch(urlA); and there is some process in urlA, and then itself redirect to urlB, then the explorer link changed to urlB, how could I get the urlB?

**Comment by darshankawar** [comment]
@AugustWangVeeva 
I suggest you ask this question on support channels like StackOverflow to check if there's an existing solution which already does that. If not, write in comments and I'll reopen it.
