### ISSUE TITLE
☂️ Significant changes to various metrics as a result of name changes

### ISSUE THREAD

**Issue by iskakaushik** [flutter/flutter#101820]
https://github.com/flutter/flutter/commit/647044c969af6d7ecf08057683731b8f23b17572 seems to have caused multiple regressions which I suspect is due to this commit. It seems to not reflect actual performance, but rather the way we collect the metrics. 

Per https://flutter-flutter-perf.skia.org/t/ :

<img width="1453" alt="image" src="https://user-images.githubusercontent.com/1006071/163194214-08bfd126-e736-4b6d-b5c5-43279b89c074.png">

- [ ] https://github.com/flutter/flutter/issues/101818
- [ ] https://github.com/flutter/flutter/issues/101819

**Comment by iskakaushik** [comment]
cc: @keyonghan  as the author of the commit, could you please advice.

**Comment by keyonghan** [comment]
I believe this is expected.

Earlier metrics are malformed between different platforms. In other words, the metric from motoG4 may be mis-updated to one from samsungS10. So the earlier low numbers of `worst_frame_rasterizer_time_millis` on motoG4 were incorrect, whereas the current `regressed` ones are the actual values.

BTW: test `backdrop_filter_perf__timeline_summary` has been removed https://github.com/flutter/flutter/pull/101372/files.

/cc @zanderso shall we remove `Linux samsung` ones like: https://github.com/flutter/flutter/blob/master/.ci.yaml#L1478?

**Comment by zanderso** [comment]
> BTW: test `backdrop_filter_perf__timeline_summary` has been removed https://github.com/flutter/flutter/pull/101372/files.
> 
> /cc @zanderso shall we remove `Linux samsung` ones like: https://github.com/flutter/flutter/blob/master/.ci.yaml#L1478?

Not simply removed. It should be replaced by the `e2e` variant, but I'm not sure what all the steps to do that are.

**Comment by iskakaushik** [comment]
> I believe this is expected.

Thanks, I've accepted them.
