### ISSUE TITLE
Layer based raster caching is unstable for DisplayListLayer

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#101872]
The logic for this changed recently with https://github.com/flutter/engine/pull/32378, though I've confirmed it doesn't work correctly before that point too.

Each Layer object has a unique id that is assigned when it is created. For most layers, when it is pushed we also add the old layer. This allows us to reuse the ID and recognize that the layer has just had some properties updated - a change in opacity or offset.

While the framework has a concept of a PictureLayer, these are added to the scene directly as pictures, and there is no associated engine object: 

https://github.com/flutter/engine/blob/main/lib/ui/compositing/scene_builder.cc#L266-L290

Now the picture itself has a stable id if it is unchanged, backed by the display list today, but every time it is pushed we generate a new DisplayListLayer with a new id. Normally this is fine, since if we specifically ask the raster cache to cache a display list, it will use the display list id as a key:

https://github.com/flutter/engine/blob/main/flow/raster_cache.cc#L353

However, if instead we try to cache a layer, perhaps from an OpacityLayer, then we'll go through the following code which uses the layer id and not the DisplayList id.

https://github.com/flutter/engine/blob/main/flow/raster_cache.cc#L214

As long as the direct descendant of an Opacity (or other) is a PictureLayer, we will always thrash the raster cache on each frame. See also https://github.com/flutter/flutter/issues/101597, which I may have misdiagnosed. Inserting the repaint boundary inserts an OffsetLayer which does not have this problem.

So we have a few options here:

1. Break the scene builder API so that we return the engine picture layer / display list layer as an opaque object as well as update the method to accept and sync ids if the pictures/display list are identical. This is the strategy we took for the rest of the API.

2. Update the child raster caching strategy to conditionally use the display list id, or to delegate to each child layer somehow. Less sure about this one, I think in theory we would also have to change the type of the raster cache key to ensure there were no collisions between display list and layer ids.

**Comment by jonahwilliams** [comment]
FYI @flar @ColdPaleLight

**Comment by jonahwilliams** [comment]
1. May not work since we don't accept a layer at all, just the picture, and changing the required arguments is going to be significantly more breaking than adding a new optional argument

**Comment by ColdPaleLight** [comment]
> 2. Update the child raster caching strategy to conditionally use the display list id, or to delegate to each child layer somehow. Less sure about this one, I think in theory we would also have to change the type of the raster cache key to ensure there were no collisions between display list and layer ids.

I think option 2 makes sense. I will file a PR for that.

**Comment by jonahwilliams** [comment]
I started experimenting a bit with this sort of hacky approach, I can observe that it works for some cases but I haven't fully though it through. Use it as inspiration if you need it 😆 

```
diff --git a/flow/raster_cache.cc b/flow/raster_cache.cc
index 68072b6f56..e5df5eecbf 100644
--- a/flow/raster_cache.cc
+++ b/flow/raster_cache.cc
@@ -8,6 +8,7 @@

 #include "flutter/common/constants.h"
 #include "flutter/flow/layers/container_layer.h"
+#include "flutter/flow/layers/display_list_layer.h"
 #include "flutter/flow/layers/layer.h"
 #include "flutter/flow/paint_utils.h"
 #include "flutter/fml/logging.h"
@@ -209,12 +210,20 @@ std::optional<RasterCacheKey> RasterCache::TryToMakeRasterCacheKeyForLayer(
         return std::nullopt;
       }
       std::vector<uint64_t> ids;
-      std::transform(children_layers.begin(), children_layers.end(),
-                     std::back_inserter(ids), [](auto& layer) -> uint64_t {
-                       return layer->unique_id();
-                     });
-      return RasterCacheKey(RasterCacheKeyID(std::move(ids)),
-                            RasterCacheKeyType::kLayerChildren, ctm);
+      bool includes_display_list = false;
+      for (auto child : children_layers) {
+        const DisplayListLayer* dl_layer = child->as_display_list_layer();
+        if (dl_layer) {
+          includes_display_list = true;
+          ids.push_back(dl_layer->display_list()->unique_id());
+        } else {
+          ids.push_back(layer->unique_id());
+        }
+      }
+      RasterCacheKeyType keyType = includes_display_list
+        ? RasterCacheKeyType::kLayerChildrenWithDisplayList
+        : RasterCacheKeyType::kLayerChildren;
+      return RasterCacheKey(RasterCacheKeyID(std::move(ids)), keyType, ctm);
   }
 }

diff --git a/flow/raster_cache_key.h b/flow/raster_cache_key.h
index d3152046c2..ced9050bda 100644
--- a/flow/raster_cache_key.h
+++ b/flow/raster_cache_key.h
@@ -45,7 +45,8 @@ enum class RasterCacheKeyType {
   kLayer,
   kPicture,
   kDisplayList,
-  kLayerChildren
+  kLayerChildren,
+  kLayerChildrenWithDisplayList,
 };

 enum class RasterCacheKeyKind { kLayerMetrics, kPictureMetrics };
@@ -74,6 +75,7 @@ class RasterCacheKey {
         return RasterCacheKeyKind::kPictureMetrics;
       case RasterCacheKeyType::kLayer:
       case RasterCacheKeyType::kLayerChildren:
+      case RasterCacheKeyType::kLayerChildrenWithDisplayList:
         return RasterCacheKeyKind::kLayerMetrics;
     }
   }
   ```

**Comment by ColdPaleLight** [comment]
@jonahwilliams  @flar
I refactored `RasterCacheKey` to fix this issue, here is the PR https://github.com/flutter/engine/pull/32676. Any thoughts?

**Comment by flar** [comment]
@jonahwilliams do you have a test case. I found some serious errors in the opacity peephole logic that made propagation of the compatibility flags a little wonky. I have a fix for that logic and want to try it out on a test case that might have led to this issue.

**Comment by flar** [comment]
See this PR which has a big impact on a particular opacity animation scenario.

https://github.com/flutter/engine/pull/32698

**Comment by jonahwilliams** [comment]
There is some example code in https://github.com/flutter/flutter/issues/101597 , however we might need two separate fixes for that. I discovered the problem while prototyping https://github.com/flutter/flutter/pull/101952 which only kind of works.

In short, you need to have a picture layer as the immediate child of an opacity layer, and then somehow animate the opacity without repainting the child to keep the picture stable. As far as I can tell we can only do that today by inserting a RepaintBoundary widget - but then the immediate child becomes an OffsetLayer so you won't see the caching issue in the engine

**Comment by flar** [comment]
Your examples in https://github.com/flutter/flutter/issues/101597 all suffer from animations that don't protect their children. The answer is to add the RepaintBoundary to the animator's child, not to the Opacity. They both run smoothly with stable caching with no changes to the engine.

**Comment by ColdPaleLight** [comment]
@flar @jonahwilliams 
I did some experiments for examples, and the result is in the table of this link https://github.com/flutter/engine/pull/32676#issuecomment-1100007712 .

**Comment by ColdPaleLight** [comment]
fixed by https://github.com/flutter/engine/pull/32676
