### ISSUE TITLE
[web] debugger always stops at web_entrypoint (webOnlyInitializePlatform)

### ISSUE THREAD

**Issue by tgpsantos** [flutter/flutter#101826]
Hello guys,

I'm in the process of converting our flutter mobile app to a web app.

I've been trying to debug some exceptions I've been getting, and for that I'm using the debug tool from Android Studio, just like I do in a mobile project.

The problem is that, no matter where I set the breakpoint, the debugger always stop at the following line (see the [image](https://user-images.githubusercontent.com/48353485/163201601-3d03eeae-d31a-4703-a10e-3225b52296e6.png))

I've also tried to [mute it](https://user-images.githubusercontent.com/48353485/163202813-a02a2b72-cb91-4f6a-9fe5-b0d02d330a0e.png) but behaviour is the same. The more breakpoints I set, the more times it stops at this line of code.

Thanks for the help in advance!

EDIT:

<details><summary> Flutter Doctor summary</summary>

```

[√] Flutter (Channel stable, 2.10.4, on Microsoft Windows [Version 10.0.19044.1645], locale pt-PT)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[√] Chrome - develop for the web
[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 4.2)
[√] VS Code (version 1.66.1)
[√] VS Code, 32-bit edition (version 1.32.3)
[√] Connected device (3 available)
[√] HTTP Host Availability

```

</details>

**Comment by darshankawar** [comment]
@tgpsantos 
Can you provide `flutter doctor -v` ?

**Comment by tgpsantos** [comment]
Hi @darshankawar . I've added it to the first post

**Comment by darshankawar** [comment]
@tgpsantos 
Your `flutter doctor -v` isn't showing what version of Google chrome browser are you using. Can you provide the same ?

**Comment by tgpsantos** [comment]
Chrome 100.0.4896.88

**Comment by darshankawar** [comment]
Thanks. That's what I was looking for, which indicates you are probably hitting https://github.com/flutter/flutter/issues/101224, so please follow-up in it for further updates.
Closing as duplicate. If you disagree, write in comments and I'll reopen it.
