### ISSUE TITLE
[autosubmit] Find a valid method to merge PR

### ISSUE THREAD

**Issue by KristinBi** [flutter/flutter#101803]
In our autosubmit bot, after we processed to check a pull request should be merged, we want to add a method autoMergePR() that can help us auto merge this pull request to our main branch.

To achieve this new feature, I firstly used the Rest API in the github official doc(https://docs.github.com/en/rest/reference/pulls#merge-a-pull-request), you can check this part of codes in #1719. However, even flutter/cocoon has granted the write permission for the content, I still cannot call this function to successfully merge the PR. The error I got is `Can not merge the pull request 1723. Merge commits are not allowed on this repository..` which still seems to be a permission error.

Since we checked once again that the permission we got should be the correct permission, I continued to find other possible APIs we can use.

The one worked is the Rest API for merging branch in this link(https://docs.github.com/en/rest/reference/branches#merge-a-branch). We can use the commit SHA1 as the head, and use the main branch name as the base to merge the latest commit in your branch to the main branch. Please check this logic in #1728.

Now I encounter a new issue. If we used this Rest API to merge the pull request, it will merge all commits in your branch which we don't want to see. We want it to merge the pull request in the squash way which will only show one commit for one pull request. 

Then I tried another two methods. The first method I tried is the first Rest API that [#merge-a-pull-request](https://docs.github.com/en/rest/reference/pulls#merge-a-pull-request) I used, this time I changed its merge method to squash. However, I got the `Can not merge the pull request 1735. Not Found.` error.
The other method I tried is to use graphql mutation to merge the pull request. This time, it succeed in #1738.

**Comment by keyonghan** [comment]
Fixed by https://github.com/flutter/cocoon/pull/1738
