### ISSUE TITLE
web: Service worker downloads NOTICES file directly at the start of the application

### ISSUE THREAD

**Issue by Curvel** [flutter/flutter#101828]
The first time the web application is started, before the service worker is registered, the NOTICES file is downloaded. Since our application uses some packages, this file is **1.1 MB** for us. However, the file is not needed here yet, right? We will use the `showAboutDialog(...)` function later to display the licenses of the packages. Wouldn't it be enough to download the file when it is needed? 1.1 MB is really a huge amount of data for a file that is not yet needed.

Why was the decision made to include the file [here](https://github.com/flutter/flutter/blob/78ae72b0b264bf9b8699ceb0f36f298dbba74299/packages/flutter_tools/lib/src/build_system/targets/web.dart#L550), so it is downloaded before the service worker is started?

## Details

**Target Platform:** web
**Target OS version/browser:** chrome, firefox

## Logs
![image](https://user-images.githubusercontent.com/13559511/163202330-154baf89-8492-4b53-a964-12e0843c3f15.png)

<details>
<summary>Logs</summary>
```
```

[✓] Flutter (Channel master, 2.13.0-0.0.pre.526, on macOS 12.1 21C52 darwin-x64, locale de-DE)
    • Flutter version 2.13.0-0.0.pre.526 at /Users/curvel/dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5fb74db1a9 (8 hours ago), 2022-04-13 02:44:07 -0400
    • Engine revision e7020a6f25
    • Dart version 2.18.0 (build 2.18.0-15.0.dev)
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/curvel/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! CocoaPods 1.10.1 out of date (1.11.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] IntelliJ IDEA Community Edition (version 2021.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.66.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.1 21C52 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 100.0.4896.75

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

• No issues found!

```
```

</details>

**Comment by darshankawar** [comment]
@Curvel 
Thanks for the report. I tried to replicate this but I don't see NOTICES file in the log. I ran `flutter build web` which shows the said file, but running in html rendering mode don't show the file in the chrome debugger. Are there any specific steps for the file to show up ?

**Comment by Curvel** [comment]
I just tested it again and noticed that the file "flutter_service_worker.js" is only created correctly when `flutter build` is executed. With `flutter run` the file is empty. 

It doesn't matter if the web renderer is `html` or `CanvasKit`.

I use the following commands to start the app:
`flutter build web --web-renderer html`
Followed by:
`docker run -it --rm -d -p 4664:80 --name web -v ~/<folderPath>/build/web/:/usr/share/nginx/html/app nginx`

Once the web application has been opened. The service worker must be unregistered to see the NOTICES file download again.

**Comment by darshankawar** [comment]
Thanks for the update. I am not much familiar using docker. Does it replicate without using it ?

I tried the same by using `python -m http.server 8000` and accessed the web app but don't see the said file still.

**Comment by yjbanov** [comment]
cc @ditman

**Comment by ditman** [comment]
This should probably be removed?

https://github.com/flutter/flutter/blob/78ae72b0b264bf9b8699ceb0f36f298dbba74299/packages/flutter_tools/lib/src/build_system/targets/web.dart#L550

**Comment by Curvel** [comment]
@ditman would be my suggestion, if there is no particular reason to download the NOTICES file so early.

**Comment by ditman** [comment]
@Curvel I think the only "need" is for it to be available in a potential offline mode; but that's not very well supported yet, so we can afford to remove it to defer its download until it's really needed.

**Comment by ditman** [comment]
In the latest master, the service worker has stopped automatically downloading the `NOTICES` file.

(Please do a `flutter clean` so the service worker without the NOTICES file gets regenerated on the next `flutter build web`)

**Comment by vixez** [comment]
For now I remove it with a script from the file when the build is done.
`grep -rl 'NOTICES",' flutter_service_worker.js | xargs sed -i '' '/NOTICES",/d'`

Until it is in `stable`.

**Comment by ditman** [comment]
@vixez that's a good trick. We should have better support for build post-processing, it's very common in the rest of the frontend frameworks and would probably enable a lot of self-service fixes like yours!

**Comment by vixez** [comment]
@ditman I found it in other places as well. in `flutter_service_worker.js` there is an additional reference in the assets. And `main.dart.js` also wants to download it.

Removing the three references, stopped the downloading.

```
grep -rl 'NOTICES",' flutter_service_worker.js | xargs sed -i '' '/NOTICES",/d'
grep -rl 'NOTICES":' flutter_service_worker.js | xargs sed -i '' '/NOTICES":/d'
sed -i '' 's/^.*NOTICES",.*$/return/' main.dart.js
```

**Comment by vixez** [comment]
@ditman You are right, we use a `FutureBuilder` and it stopped working on our license page where we use `future: LicenseRegistry.licenses.toList(),`.

Removing `sed -i '' 's/^.*NOTICES",.*$/return/' main.dart.js` from the cleanup script fixed it.
Didn't think about that, thanks for the heads up.
