### ISSUE TITLE
Increased layer-cache usage as a result of enabling shader mask

### ISSUE THREAD

**Issue by iskakaushik** [flutter/flutter#101823]
Seems like https://github.com/flutter/engine/pull/32027 caused this: https://flutter-flutter-perf.skia.org/e/?begin=1649712551&end=1649795045&keys=X206a1405718ff5fb751fc286fdad61f2&num_commits=50&request_type=1&xbaroffset=28316.

On first look this seems like it is to be expected as we could be caching more layers, but wanted to confirm before I accepted the increased usage.

cc: @flar  could you please advice?

**Comment by flar** [comment]
It's the benchmark designed to show the advantage of caching ShaderMask layers. If it didn't also show a big drop in rasterization time then it has failed its task.

**Comment by flar** [comment]
It looks like the memory went from the picture cache to the layer cache.

**Comment by flar** [comment]
Looking at avg_build and avg_raster, the build times had no change, but the raster time is lower after the merge. There was an unfortunate uncommon spike to 15ms on the raster time when the commit was merged in, but ignoring that, the avg raster times after that are all lower than they were before the fix.

**Comment by chinmaygarde** [comment]
Based on @flar s last comment. It seems like this is an acceptable tradeoff. Closing.
