### ISSUE TITLE
[google_sign_in_web] Move js-interop layer out of `generated`

### ISSUE THREAD

**Issue by ditman** [flutter/flutter#101855]
The js-interop layer of the web version of Google Sign In used to be generated by the [js_facade_gen script](https://github.com/dart-lang/js_facade_gen), but it is no longer.

## Proposal

Move the js-interop layer ([`gapi.dart`, `gapiauth2.dart`...](https://github.com/flutter/plugins/tree/main/packages/google_sign_in/google_sign_in_web/lib/src/generated)) outside of `generated` (or rename `generated` to `js_interop` or similar), so the files don't receive any special treatment.

Also: fix tests, and whatever issues the analyzer may start having with the change, of course.

**Comment by wannieman98** [comment]
Hi, is this issue closed with the above PR? If open, can I try working on it?

**Comment by peixinli** [comment]
> @peixinli I believe this can be closed?

Closing this issue.
