### ISSUE TITLE
FlutterView not resizing on keyboard dismissal (plugin)

### ISSUE THREAD

**Issue by LarkAscending** [flutter/flutter#10193]
## Steps to Reproduce

1. Do Firebase codelab, thru step 8 Authenticate users [source code here](https://github.com/flutter/friendlychat-steps/tree/master/full_steps/step_4_auth).
2. Click Run from IntelliJ or command line w/an attached Android device.
3. When Friendlychat app launches, type in the Text field and send the message.
4. When login screen displays, choose an account for Google Sign-In/Firebase Auth.

When you're returned to the main app UI, the Text field is in the middle of the screen, where it would be if the on-screen keyboard were active. And the Text field does not have focus. So the app is non-functional.

Hot restart resets everything and the app runs fine (until the next text is sent).

Unable to get further than step 8 of codelab. Publishing as-is with steps 9 and 10 untested. Quick triage would be appreciated...

@cbracken was able to rewind the framework build to a point ~9 days ago where this bug does not happen. Also, 2 days ago w/an older flutter version (maybe that same vintage) this issue was not present.

## Logs

Run your application with `flutter run` and attach all the log output.
Launching lib/main.dart on Nexus 5X in debug mode...

Built build/app/outputs/apk/app-debug.apk (24.9MB).

E/flutter (11625): [ERROR:../../lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter (11625): PlatformException(exception, An internal error has occurred. [ OPERATION_NOT_ALLOWED ], null)
E/flutter (11625): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:518)
E/flutter (11625): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:140)
E/flutter (11625): <asynchronous suspension>
E/flutter (11625): #2      FirebaseAuth.signInAnonymously (package:firebase_auth/firebase_auth.dart:84)
E/flutter (11625): <asynchronous suspension>
E/flutter (11625): #3      ChatScreenState.initState (file:///Users/eastrue/friendlychat/lib/main.dart:111)
E/flutter (11625): #4      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3262)
E/flutter (11625): #5      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3126)
E/flutter (11625): #6      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2513)
E/flutter (11625): #7      Element.updateChild (package:flutter/src/widgets/framework.dart:2316)
E/flutter (11625): #8      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3163)
E/flutter (11625): #9      Element.rebuild (package:flutter/src/widgets/framework.dart:3052)
E/flutter (11625): #10     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3131)
E/flutter (11625): #11     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3126)
E/flutter (11625): #12     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2513)
E/flutter (11625): #13     Element.updateChild (package:flutter/src/widgets/framework.dart:2316)
E/flutter (11625): #14     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3163)
E/flutter (11625): #15     Element.rebuild (package:flutter/src/widgets/framework.dart:3052)
E/flutter (11625): #16     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3131)
E/flutter (11625): #17     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3126)
E/flutter (11625): #18     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2513)
E/flutter (11625): #19     Element.updateChild (package:flutter/src/widgets/framework.dart:2316)
E/flutter (11625): #20     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4093)
E/flutter (11625): #21     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2513)
E/flutter (11625): #22     Element.updateChild (package:flutter/src/widgets/framework.dart:2316)
E/flutter (11625): #23     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4093)
E/flutter (11625): #24     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2513)
E/flutter (11625): #25     Element.updateChild (package:flutter/src/widgets/framework.dart:2316)
E/flutter (11625): #26     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3163)
E/flutter (11625): #27     Element.rebuild (package:flutter/src/widgets/framework.dart:3052)
E/flutter (11625): #28     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3131)
E/flutter (11625): #29     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3269)
E/flutter (11625): #30     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3126)
E/flutter (11625): #31     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2513)
E/flutter (11625): #32     Element.updateChild (package:flutter/src/widgets/framework.dart:2316)
E/flutter (11625): #33     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3163)
E/flutter (11625): #34     Element.rebuild (package:flutter/src/widgets/framework.dart:3052)
E/flutter (11625): #35     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3131)
E/flutter (11625): #36     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3126)
E/flutter (11625): #37     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2513)
E/flutter (11625): #38     Element.updateChild (package:flutter/src/widgets/framework.dart:2316)
E/flutter (11625): #39     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4093)
E/flutter (11625): #40     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2513)
E/flutter (11625): #41     Element.updateChild (package:flutter/src/widgets/framework.dart:2316)
E/flutter (11625): #42     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4093)
E/flutter (11625): #43     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2513)
E/flutter (11625): #44     Element.updateChild (package:flutter/src/widgets/framework.dart:2316)
E/flutter (11625): #45     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3163)
E/flutter (11625): #46     Elem
I/FA      (11625): Tag Manager is not found and thus will not be used

Run `flutter analyze` and attach any output of that command also.

## Flutter Doctor

[✓] Flutter (on Mac OS X 10.12.4 16E195, channel alpha)
    • Flutter at /Users/eastrue/flutter
    • Framework revision 973304d5fb (2 hours ago), 2017-05-18 17:31:57 -0700
    • Engine revision f99d3ef108
    • Tools Dart version 1.23.0-dev.11.11

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at /Users/eastrue/Library/Android/sdk
    • Platform android-25, build-tools 25.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.3.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3.2, Build version 8E2002
    • ios-deploy 1.9.1
    • CocoaPods version 1.2.1

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Gradle version 3.2
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.1.2)
    • Dart plugin version 171.4424
    • Flutter plugin version 13.1

[✓] Connected devices
    • Nexus 5X • 0048fc9b7c76b7a2                     • android-arm • Android 6.0.1 (API 23)
    • iPhone 7 • 3A916ACD-8555-4077-84A3-683A57F328A6 • ios         • iOS 10.3 (simulator)

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by eseidelGoogle** [comment]
The last thing on the stack is FirebaseAuth calling out to it's Obj-C side.  Is this a plugin bug @collinjackson?

**Comment by LarkAscending** [comment]
Update from control room: we've sync'd to HEAD for alpha branch, and can't repro it anymore. We still get the same exception stack trace but not the UI behavior. Too interesting...

We were able to repo w/main.dart from the friendlychat-steps repo (step_4) as well as my work-in-progress main.dart, and also with recent (last week) versions of the framework. Now not able to, not at all.

**Comment by LarkAscending** [comment]
Update #2 - looks like it could be related to a recent friendlychat change to remove anonymous auth. 
@collinjackson when I remove `|| auth.currentUser.isAnonymous`  from the if statement in `_ensureLoggedIn()`, I see the stack trace in the console but the UI looks normal and the Text field is functional.

**Comment by cbracken** [comment]
Attaching a rough log of when we saw/didn't see this so I don't lose it for future digging:
1. Initial state: framework at dc4ca8db838a81a27672101b94b4679b3c8c9305 (0.0.6 tag). Saw the issue.
2. Sync'ed to 973304d5fbf737510ecc250b93d9ee2e872b563f (HEAD of alpha). Saw the issue.
3. Sync'ed back to dc4ca8db838a81a27672101b94b4679b3c8c9305 (Thu 2017-05-11). Saw the issue.
4. Reverted `lib/main.dart` to an older version. Saw an unrelated issue where the text field wasn't responding to input.
5. Sync'ed back to cc44cc779b4477b6e78be2fd530927f140cca35f (0.0.5 - from Tue 2017-05-10) and re-updated `lib/main.dart`. **Didn't** see the issue.
5. Re-sync'ed forward to 973304d5fbf737510ecc250b93d9ee2e872b563f (HEAD of alpha). **Didn't** see the issue.

The engine rev between 0.0.5 and 0.0.6 flipped the engine from f2581c9bcc32f9e2e7372eb7e94a8aa9f5aab0b2 to f99d3ef1083b9a126b64fab0c576647108c9a7eb which includes only an iOS specific keyboard fix, a Fuchsia build fix, a Fuchsia IME fix, and an asset cache improvement. The engine seems pretty unlikely. On the framework side, there are a couple tests, a script change, and some test deflaking but nothing suspiciously related.

**Comment by cbracken** [comment]
One avenue worth checking is how we respond to the following scenario:
1. Focus a text field to bring up the keyboard.
1. Trigger a plugin that opens a native view while the keyboard is still up.
1. Ensure the keyboard gets dismissed in the native view.
1. Return back to the Flutter app. 

I'd be interested to know if we're failing to get the keyboard dismissal notification on the Flutter end of things in such a scenario and whether we need to mitigate against that by proactively unfocusing the focused text field before navigating to a native view, or other solution.

**Comment by collinjackson** [comment]
We worked through this today and the root issue was that adb was refusing to overwriting an existing build on the device that was signed with a different key. Google Sign In and Firebase Auth didn't recognize the key of the build and was throwing an exception.
