### ISSUE TITLE
Release builds generate app with -Ptrack-widget-creation=true

### ISSUE THREAD

**Issue by feinstein** [flutter/flutter#101922]
If we create a new project from scratch with the command `flutter create test_app` and then run `flutter build apk -v` we can see the following line on the verbose build logs:

```
 executing: [C:\Users\User\Desktop\test_build\test_app\android/]
C:\Users\User\Desktop\test_build\test_app\android\gradlew.bat -Pverbose=true
-Ptarget-platform=android-arm,android-arm64,android-x64 -Ptarget=lib\main.dart
-Pbase-application-name=android.app.Application -Pdart-obfuscation=false -Ptrack-widget-creation=true
-Ptree-shake-icons=true assembleRelease
```
I got this while I was investigating our CI/CD build times and it intrigued me that a release build would pass `-Ptrack-widget-creation=true`. I wonder if this could have some minor performance impacts and if it makes sense to leave it as `true` for a release build.

I am on Flutter 2.10.4.

<details>
<summary>Here's the full output</summary>
 flutter build apk -v

 flutter build apk -v
[ +106 ms] executing: [C:\Programming\Flutter\sdk\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +144 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +2 ms] c860cba910319332564e1e9d470a17074c1f2dfd
[   +1 ms] executing: [C:\Programming\Flutter\sdk\flutter/] git tag --points-at c860cba910319332564e1e9d470a17074c1f2dfd
[ +231 ms] Exit code 0 from: git tag --points-at c860cba910319332564e1e9d470a17074c1f2dfd
[   +1 ms] 2.10.4
[  +13 ms] executing: [C:\Programming\Flutter\sdk\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +81 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] origin/stable
[   +1 ms] executing: [C:\Programming\Flutter\sdk\flutter/] git ls-remote --get-url origin
[  +73 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[ +204 ms] executing: [C:\Programming\Flutter\sdk\flutter/] git rev-parse --abbrev-ref HEAD
[  +88 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] stable
[ +109 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +6 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +90 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[   +8 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[ +144 ms] Skipping pub get: version match.
[ +129 ms] Generating
C:\Users\User\Desktop\test_build\test_app\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[ +139 ms]  Building with sound null safety
[  +27 ms] Running Gradle task 'assembleRelease'...
[   +7 ms] Using gradle from C:\Users\User\Desktop\test_build\test_app\android\gradlew.bat.
[  +20 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
[ +183 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
[   +2 ms] openjdk version "11.0.11" 2021-04-20
           OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
           OpenJDK 64-Bit Server VM (build 11.0.11+9-b60-7590822, mixed mode)
[   +3 ms] executing: [C:\Users\User\Desktop\test_build\test_app\android/]
C:\Users\User\Desktop\test_build\test_app\android\gradlew.bat -Pverbose=true
-Ptarget-platform=android-arm,android-arm64,android-x64 -Ptarget=lib\main.dart
-Pbase-application-name=android.app.Application -Pdart-obfuscation=false -Ptrack-widget-creation=true
-Ptree-shake-icons=true assembleRelease
[+1191 ms] Welcome to Gradle 6.7!
[   +2 ms] Here are the highlights of this release:
[   +1 ms]  - File system watching is ready for production use
[   +1 ms]  - Declare the version of Java your build requires
[   +1 ms]  - Java 15 support
[   +1 ms] For more details see https://docs.gradle.org/6.7/release-notes.html
[+4083 ms] > Task :app:compileFlutterBuildRelease
[   +6 ms] [ +102 ms] executing: [C:\Programming\Flutter\sdk\flutter/] git -c log.showSignature=false log -n 1
--pretty=format:%H
[   +2 ms] [ +138 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] [        ] c860cba910319332564e1e9d470a17074c1f2dfd
[   +1 ms] [        ] executing: [C:\Programming\Flutter\sdk\flutter/] git tag --points-at
c860cba910319332564e1e9d470a17074c1f2dfd
[ +185 ms] [ +227 ms] Exit code 0 from: git tag --points-at c860cba910319332564e1e9d470a17074c1f2dfd
[   +2 ms] [        ] 2.10.4
[   +1 ms] [  +10 ms] executing: [C:\Programming\Flutter\sdk\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +89 ms] [  +79 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] [        ] origin/stable
[   +1 ms] [        ] executing: [C:\Programming\Flutter\sdk\flutter/] git ls-remote --get-url origin
[  +89 ms] [  +68 ms] Exit code 0 from: git ls-remote --get-url origin
[   +2 ms] [        ] https://github.com/flutter/flutter.git
[ +106 ms] [  +82 ms] executing: [C:\Programming\Flutter\sdk\flutter/] git rev-parse --abbrev-ref HEAD
[   +2 ms] [  +81 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] [        ] stable
[  +89 ms] [ +104 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +2 ms] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[ +102 ms] [   +7 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +85 ms] [ +159 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[   +5 ms] [   +7 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +2 ms] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[ +175 ms] [ +139 ms] Initializing file store
[   +2 ms] [  +22 ms] Done initializing file store
[ +199 ms] [ +200 ms] Skipping target: gen_localizations
[   +1 ms] [  +19 ms] Skipping target: gen_dart_plugin_registrant
[+1932 ms] [+1896 ms] Skipping target: kernel_snapshot
[  +37 ms] [  +44 ms] Skipping target: android_aot_release_android-arm
[  +31 ms] [  +59 ms] Skipping target: aot_android_asset_bundle
[   +2 ms] [  +30 ms] Skipping target: android_aot_release_android-arm64
[ +102 ms] [  +28 ms] Skipping target: android_aot_release_android-x64
[   +2 ms] [  +30 ms] Skipping target: android_aot_bundle_release_android-arm
[   +1 ms] [  +27 ms] Skipping target: android_aot_bundle_release_android-arm64
[  +88 ms] [  +30 ms] Skipping target: android_aot_bundle_release_android-x64
[   +2 ms] [        ] Skipping target: _composite
[   +1 ms] [        ] Persisting file store
[        ] [  +22 ms] Done persisting file store
[        ] [  +10 ms] build succeeded.
[        ] [  +22 ms] "flutter assemble" took 2.791ms.
[ +289 ms] [ +262 ms] ensureAnalyticsSent: 256ms
[   +2 ms] [   +1 ms] Running shutdown hooks
[   +1 ms] [        ] Shutdown hooks complete
[        ] [        ] exiting with code 0
[ +109 ms] > Task :app:packLibsflutterBuildRelease UP-TO-DATE
[  +14 ms] > Task :app:preBuild UP-TO-DATE
[   +6 ms] > Task :app:extractProguardFiles UP-TO-DATE
[   +2 ms] > Task :app:preReleaseBuild UP-TO-DATE
[  +15 ms] > Task :app:compileReleaseAidl NO-SOURCE
[   +5 ms] > Task :app:compileReleaseRenderscript NO-SOURCE
[   +5 ms] > Task :app:generateReleaseBuildConfig UP-TO-DATE
[   +2 ms] > Task :app:checkReleaseAarMetadata UP-TO-DATE
[  +37 ms] > Task :app:cleanMergeReleaseAssets
[   +2 ms] > Task :app:mergeReleaseShaders UP-TO-DATE
[        ] > Task :app:compileReleaseShaders NO-SOURCE
[   +1 ms] > Task :app:generateReleaseAssets UP-TO-DATE
[   +2 ms] > Task :app:mergeReleaseAssets
[ +128 ms] > Task :app:copyFlutterAssetsRelease
[  +11 ms] > Task :app:generateReleaseResValues UP-TO-DATE
[ +135 ms] > Task :app:generateReleaseResources UP-TO-DATE
[  +30 ms] > Task :app:mergeReleaseResources UP-TO-DATE
[   +2 ms] > Task :app:createReleaseCompatibleScreenManifests UP-TO-DATE
[   +4 ms] > Task :app:extractDeepLinksRelease UP-TO-DATE
[   +9 ms] > Task :app:processReleaseMainManifest UP-TO-DATE
[  +13 ms] > Task :app:processReleaseManifest UP-TO-DATE
[  +33 ms] > Task :app:processReleaseManifestForPackage UP-TO-DATE
[ +194 ms] > Task :app:processReleaseResources UP-TO-DATE
[  +30 ms] > Task :app:compileReleaseKotlin UP-TO-DATE
[ +233 ms] > Task :app:javaPreCompileRelease UP-TO-DATE
[ +894 ms] > Task :app:compileReleaseJavaWithJavac UP-TO-DATE
[ +124 ms] > Task :app:compileReleaseSources UP-TO-DATE
[ +269 ms] > Task :app:buildKotlinToolingMetadata UP-TO-DATE
[+3016 ms] > Task :app:lintVitalRelease
[  +86 ms] > Task :app:mergeReleaseNativeDebugMetadata NO-SOURCE
[  +17 ms] > Task :app:compressReleaseAssets UP-TO-DATE
[   +9 ms] > Task :app:checkReleaseDuplicateClasses UP-TO-DATE
[   +7 ms] > Task :app:mergeReleaseGeneratedProguardFiles UP-TO-DATE
[  +11 ms] > Task :app:processReleaseJavaRes NO-SOURCE
[  +10 ms] > Task :app:mergeReleaseJavaResource UP-TO-DATE
[   +8 ms] > Task :app:minifyReleaseWithR8 UP-TO-DATE
[  +11 ms] > Task :app:collectReleaseDependencies UP-TO-DATE
[   +2 ms] > Task :app:sdkReleaseDependencyData UP-TO-DATE
[   +2 ms] > Task :app:shrinkReleaseRes UP-TO-DATE
[   +1 ms] > Task :app:mergeReleaseJniLibFolders UP-TO-DATE
[   +2 ms] > Task :app:mergeReleaseNativeLibs UP-TO-DATE
[   +3 ms] > Task :app:stripReleaseDebugSymbols UP-TO-DATE
[   +4 ms] > Task :app:validateSigningRelease UP-TO-DATE
[   +1 ms] > Task :app:packageRelease UP-TO-DATE
[ +181 ms] > Task :app:assembleRelease
[   +2 ms] Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
[        ] Use '--warning-mode all' to show the individual deprecation warnings.
[        ] See https://docs.gradle.org/6.7/userguide/command_line_interface.html#sec:command_line_warnings
[   +1 ms] BUILD SUCCESSFUL in 14s
[        ] 36 actionable tasks: 6 executed, 30 up-to-date
[ +572 ms] Running Gradle task 'assembleRelease'... (completed in 15,5s)
[  +29 ms] calculateSha: LocalDirectory:
'C:\Users\User\Desktop\test_build\test_app\build\app\outputs\flutter-apk'/app.apk
[ +247 ms] √  Built build\app\outputs\flutter-apk\app-release.apk (15.8MB).
[   +3 ms] "flutter apk" took 16.363ms.
[  +98 ms] ensureAnalyticsSent: 93ms
[   +3 ms] Running shutdown hooks
[   +1 ms] Shutdown hooks complete
[   +1 ms] exiting with code 0
</details>

**Comment by DevMukh** [comment]
![f775cc9c-63e8-4455-88e8-90ba9cd9fb8e](https://user-images.githubusercontent.com/100961807/163456471-bf6698d9-5ef4-487c-8969-a763a9e40196.jpg)
kindly sir fix  this i am new here and didnt get any solution

**Comment by feinstein** [comment]
@DevMukh is this your code? Put 2 spaces before the `http`, then delete your question and post further on stackoverlow. You are off topic here diverting this discussion.

**Comment by jonahwilliams** [comment]
https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/build_system/targets/common.dart#L225

**Comment by feinstein** [comment]
@jonahwilliams great to know, I will close this issue then, many thanks!
