### ISSUE TITLE
Update all plugins minimum from iOS 9 to iOS 11

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#101965]
Increase plugin minimum target iOS version from 9.0 to 11.0 [flutter.dev/go/rfc-32-bit-ios-unsupported](http://flutter.dev/go/rfc-32-bit-ios-unsupported).

To paraphrase Stuart from https://github.com/flutter/flutter/issues/84198, the last time this was done:

> Once Flutter stable no longer supports [iOS 9], we should update all the 1P plugins to match. This will eliminate the issue of deprecation warnings from the plugins in the now-common case where people build with projects that use [iOS 11] as the minimum.
> 
> Currently all of our plugins support [iOS 9] so this will affect every plugin that supports iOS, although we'll only need to update  the deprecated plugins if at some point we have CI issues with the [iOS 9] support.
> 
> When we do this, we should make sure the READMEs prominently list the minimum iOS version (see also https://github.com/flutter/flutter/issues/34999)

Example: https://github.com/flutter/plugins/pull/4327

Blocked by https://github.com/flutter/flutter/issues/101961

Also run app migrator https://github.com/flutter/flutter/issues/101960 by building all example projects.

**Comment by stuartmorgan** [comment]
Also from the previous issue:

> We should probably also update the minimum Flutter version at the same time so that we guarantee that nobody trying to build for [iOS 9] with an older version of Flutter resolves to a newer version of the plugin.

A nice bonus since last time is that for any plugin we've federated (which is most of them now) we only need to increase the minimum version on the iOS implementation package, so people still using old versions of Flutter will still be able to get fixes in other packages.

**Comment by jmagman** [comment]
Clean up availability and deprecation pragmas, see https://github.com/flutter/plugins/pull/5765

**Comment by jmagman** [comment]
This should to wait until the plugin package n-2 stable minimum version is Flutter 3.1.0 as that's the first stable containing https://github.com/flutter/flutter/commit/1756ccc541d56670d314f4bc29077ec302f28321.
Example, this set it to 2.10: https://github.com/flutter/plugins/pull/6340

**Comment by stuartmorgan** [comment]
It's fine to update all the iOS implementation packages to 3.3 now as part of upping the minimum iOS version. The N-2 tests are just to prevent accidentally breaking people using older versions by publishing something that the resolver will give them but then doesn't compile. We only commit to actively*supporting* current stable.
