### ISSUE TITLE
[video_player] Google IMA (Interactive Media Ads) support

### ISSUE THREAD

**Issue by apieceofcode1801** [flutter/flutter#101976]
I need to add [Google IMA Ads](https://developers.google.com/interactive-media-ads) to the video_player in my project.
I'm trying to fork the `flutter/plugins` to customize `video_player_avfoundation` but it's hard for me when I don't really know behind the sense the way the package attaches the AVPlayer to the view.
I couldn't find the view which wraps the AVPlayer to assign to `adContainer`, 
```
IMAAdDisplayContainer *adDisplayContainer =
      [[IMAAdDisplayContainer alloc] initWithAdContainer:self.view];
```
Someone can tell me how to find that view.
This is the document of Google IMA for iOS:
https://developers.google.com/interactive-media-ads/docs/sdks/ios/client-side

Thank you!

**Comment by stuartmorgan** [comment]
The issue tracker is specifically for bug reports and feature requests for Flutter. See https://flutter.dev/community#community-grid for discussion resources for your own projects.
