### ISSUE TITLE
More layer types should implement OffsetLayer

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#101990]
In the investigation of https://github.com/flutter/flutter/issues/101941 / https://github.com/flutter/flutter/pull/101952 I've found that we'll be limited in how many addition layer / render object types we can support as repaint boundaries. It is expected that a repaint boundaries layer can accept an offset, but so far only `OffsetLayer`, `TransformLayer`, and `OpacityLayer` meet that criteria.

If its feasible, we should consider making more layer types support accepting an offset so we can expand the support.

**Comment by jonahwilliams** [comment]
Maybe we should also consider loosening this constraint too. For example, the `ImageFilterLayer` can't accept an offset directly, but it can include it in the matrix transform. As long as the offset can be consumed there shouldn't be a problem

**Comment by jonahwilliams** [comment]
> As long as the offset can be consumed there shouldn't be a problem

But from more research, its just way easier if we can set the offset directly. Then we let the framework do it and we can skip conditionally passing the offset into updateCompositedLayer

**Comment by dnfield** [comment]
If ImageFitlererLayer wants to work with a transform we could just have the Offset be a getter that reports the translate of the matrix and a setter that update the translate, right?

**Comment by jonahwilliams** [comment]
I tried that and it didn't quite work because the filters are opaque. Also TBH it was a huge pain trying to make the repaint boundary code generic beyond OffsetLayer - since the framework wants to manage the offset itself

**Comment by jonahwilliams** [comment]
This improved the performance of the animated image filtered benchmark: https://flutter-flutter-perf.skia.org/e/?queries=test%3Danimated_complex_image_filtered_perf__e2e_summary&selected=commit%3D32354%26name%3D%252Carch%253Dintel%252Cbranch%253Dmaster%252Cconfig%253Ddefault%252Cdevice_type%253DMoto_G__4_%252Cdevice_version%253Dnone%252Chost_type%253Dlinux%252Csub_result%253Daverage_frame_rasterizer_time_millis%252Ctest%253Danimated_complex_image_filtered_perf__e2e_summary%252C

Note that this is raster and build, so these improvements still apply to impeller as well

**Comment by jonahwilliams** [comment]
Here is a better link:

https://flutter-flutter-perf.skia.org/e/?begin=1669622400&numCommits=49&queries=test%3Danimated_complex_image_filtered_perf__e2e_summary&requestType=0&selected=commit%3D32354%26name%3D%252Carch%253Dintel%252Cbranch%253Dmaster%252Cconfig%253Ddefault%252Cdevice_type%253DMoto_G__4_%252Cdevice_version%253Dnone%252Chost_type%253Dlinux%252Csub_result%253Dworst_frame_build_time_millis%252Ctest%253Danimated_complex_image_filtered_perf__e2e_summary%252C
