### ISSUE TITLE
Allow RenderObjects with explicitly composited children to behave as repaint boundaries

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#101941]
### What is a repaint boundary?  (conceptually, not the widget)

In Flutter it is common for multiple `RenderObject`s to all paint into the same Picture. When one of those  `RenderObject`s is marked as needing to be repainted, the framework must ensure that all `RenderObject`s which painted into that picture repaint, and in the same order as before.

To ensure this happens, when `markNeedsPaint` is called, the framework walks the render object's parents, marking each dirty until it hits a repaint boundary. From that repaint boundary, the framework begins calling `paint` (we'll come back to this) in depth first order  - only stopping when it his a repaint boundary with children that are not marked dirty, or the leaf. So the repaint boundary literally establishes the boundaries to where the framework must start/stop painting for the sake of correctness. 

In order to ensure the boundaries are correct, the repaint boundary itself must be a render object that has an explicit Layer - today that layer must be an `OffsetLayer`. This enforces any parents or siblings would be drawn into a different picture. The various invariants of this are enforced by the `RenderObject`, `PaintingContext` and `PipelineOwner` classes.

### Why are repaint boundaries good?  (still conceptually, not the widget)

Well less work per frame on the ui side. On the engine side, avoid recreating pictures has numerous raster advantages. The framework does *not* currently deeply compare `Picture` objects, so repainting a picture with the exact same commands will produce a distinct picture. This defeats attempts at caching on the engine side, via the raster cache, or in the future potentially forcing engine tasks like tesselation to re-run.  For example, see https://github.com/flutter/flutter/issues/101597 for the issue with animated opacity. TLDR: animating an opacity forces child to repaint too which defeats `OpacityLayer`s built in raster caching.

### The Repaint Boundary Widget is a trade-off

Consider an app with a loading spinner. Wrapping in an explicit repaint boundary can ensure that the animation does not force all parents/child tor repaint. For the bad cases read https://github.com/flutter/flutter/issues/101810 . TLDR: splitting up pictures can massively increase the numbers of layers in the tree, which is more expensive to traverse and composite. It can be hard for inexperienced users to identify a good place to locate a repaint boundary. Furthermore, as an application grows and develops the location of repaint boundaries may need to change. This implies not only a knowledge burden but an ongoing maintaince cost.

### Overview

We can get more of the benefits of repaint boundaries and side-step some of the downsides by recognizing that many `RenderObject`s have the same characteristics as the much more limited `RenderRepaintBoundary` but cannot be treated as repaint boundaries due to implementation details of the `PaintingContext`/`PipelineOwner`. Consider the `RenderOpacity` widget, it has the following paint method:

https://github.com/flutter/flutter/blob/3af65f179f4f587b0c4e3038881511cebd0686df/packages/flutter/lib/src/rendering/proxy_box.dart#L893-L903

By pushing a new layer, this `RenderObject` could (in theory) repaint its child without affect any parent or sibling layers, and could also (in theory) update its opacity without repainting its children.

There are two general cases of repainting repaint boundaries

1. We call `markNeedsPaint` and walk the tree until we find one. This ends up going through repaintCompositedChild. this conditionally creates an `OffsetLayer` for the render object, though it does not provide an offset since this offset could not have changed if the parent did not change.

https://github.com/flutter/flutter/blob/fe11f57c61d315250d0fbbce72a5781f0a2c1e4a/packages/flutter/lib/src/rendering/object.dart#L87-L104

2. While painting the tree, we hit a render object that is itself a repaint boundary (though not the one we started painting from). This updates the offset and conditionally stops painting based on whether or not that RO is dirty.

https://github.com/flutter/flutter/blob/ae805de4687480beee3c5f46acb84cfc98dd0fed/packages/flutter/lib/src/rendering/object.dart#L191-L211

Now its relatively easy to imagine changing these implementations so that the delegate to some RenderObject method which could provide a different Layer type. However, the part I have yet to fully realize is how to support a RenderObject that is *conditionall* a repaint boundary. For example, in the Opacity case we do not want to be a repaint boundary if we have no children or if our opacity is zero. In fact, we don't want a layer at all. Similarly, a RenderClipRect does not want to be a repaint boundary if it has the setting `Clip.none` which could change after the RO is created.

### Detailed Design

In order to implement this functionality, we need a few more features on RenderObject.

First, in order to allow render objects to become and stop being repaint boundaries, we need to track their previous "isRepaintBoundary" state via `_wasRepaintBoundary`. For example, if a render object becomes a repaint boundary and then is marked for painting, if it wasn't a repaint boundary on the previous frame it may not have a layer yet. Therefore we need to treat it as if it isn't yet a repaint boundary and paint from the parent.

Next, we delegate the creation of the OffsetLayer used for the repaint boundary layer to the RenderObject itself via `RenderObject.updateCompositedLayer`. This allows for both creation and updating of the layer object, though currently it asserts when unnecessarily replacing the layer instance. In the future, this could be relaxed to support repaint boundaries that may need to change their layer type, for example a TransformLayer could be a repaint boundary that conditionally pushes either a TransformLayer or an ImageFilterLayer.

```dart
  /// Update the composited layer owned by this render object.
  ///
  /// This method is called by the framework for render object repaint
  /// boundaries to update the properties on their composited layer, potentially
  /// without repainting their children.
  ///
  /// If [oldLayer] is `null`, this method should return a new [OffsetLayer]
  /// (or subtype thereof). If [oldLayer] is not `null`, then this method should
  /// reuse the layer instance that is provided - it is an error to create a new
  /// layer in this instance.
  ///
  /// The [OffsetLayer.offset] property will be managed by the framework and
  /// does not need to be updated.
  OffsetLayer updateCompositedLayer(covariant OffsetLayer? oldLayer) {
    assert(isRepaintBoundary);
    return oldLayer ?? OffsetLayer();
  }
  ```

As an example, here is what the implementation of the RenderOpacity's method is:

```
  @override
  OffsetLayer updateCompositedLayer(covariant OpacityLayer? oldLayer) {
    final OpacityLayer updatedLayer = oldLayer ?? OpacityLayer();
    updatedLayer.alpha = _alpha;
    return updatedLayer;
  }
  ```
  
  Notice in all of these we do not delegate management of the offset to render object. This is by design since we may need to update offset without modifying other properties of the layer or giving a chance for the render object to change properties. This also means that all render objects that want to be repaint boundaries must create a layer type that implements OffsetLayer - so that they can consume a changing parent offset. I'm tracking that in https://github.com/flutter/flutter/issues/101990
  
 With the changes above (and a bit more plumbing) we have roughly enough to make the whole thing work, however there is a new opportunity for a performance improvement: we could update the properties of the layer without repainting either the parents or the children. This was not implemented before, since OffsetLayer has no interesting properties. OpacityLayer, on the other hand, could update its opacity without repainting its children.
 
 
 To support this, I added a new state to render objects `_needsLayerPropertyUpdate` and a new method to mark this state dirty `markNeedsLayerPropertyUpdate`. When a render object with this state is processed, its children are only painted if it was also marked as needing to be painted. Otherwise, we directly update the layer properties by calling `updateCompositedLayer`
 
 
 
 ### Other Questions
 
* What about the paint method on render object? Painting in a render object that is a repaint boundary is roughly equivalent to calling context.pushLayer and performing some painting in the provided callback. Its not technically incorrect, and is up to the layer itself to mark as needing to be painted.

**Comment by Hixie** [comment]
Dynamically changing status should already work; just mark the compositing bits as dirty and it should recompute everything and repaint what needs repainting.

**Comment by jonahwilliams** [comment]
Ahh yeah, I was able to make that work, I just needed to start tracking whether or not something was a repaint boundary in addition to whether or not it needed compositing before

**Comment by jonahwilliams** [comment]
Ahh yeah, I was able to make that work, I just needed to start tracking whether or not something was a repaint boundary in addition to whether or not it needed compositing before

**Comment by jonahwilliams** [comment]
Actually, new discovery today. Currently RenderRepaintBoundary does not have any properties that can be adjusted via markNeedsPaint, just the offset which is set via the parent paint method.

But if we expand this to opacity layers and others, then we have a new case where the layer's opacity has changed but none of the children have been marked dirty. In theory we could update the opacity's layer and not repaint the children

**Comment by flar** [comment]
Most systems that I've worked on don't use RepaintBoundaries but flag changed and unchanged widgets directly. RepaintBoundary provides a sparse application of what the flags can provide naturally for any widget.

The basic idea is that if a node changes, it marks itself "modified". It then climbs the tree marking all parents to the root as "childModified". Note that the climbing often hits a node that is already marked "childModified" or "modified" and terminates its climb early if there are multiple changes in the tree.

The "childModified" flags detail to the update mechanism which parts of the tree need to be revisited, and the "modified" flag indicates where rebuilding needs to happen.

RepaintBoundary both acts as a "false root" for these propagations, but also requires manual insertion and doesn't really indicate which subtrees need rebuilding. If it is too high in the tree then issues happen like the Opacity widget never having a stable child. I believe that RepaintBoundary objects are also one of the few objects that can add a retained subtree to a new tree. They have this capability because that is what they were designed for, but really any widget/RepaintBoundary should be able to say "I haven't changed whether or not I'm a RepaintBoundary, so we can just reuse my previous incarnation".

With the flag system, the opacity might animate and it might insert a new OpacityLayer, but when it looks at its child it will see no flags on it and simply insert the previous child thereby automatically stabilizing it without any developer intervention and without any heuristics. This is not currently possible (?) with RepaintBoundaries because the ability to add a retained subtree is restricted to them (?).

One thing that RepaintBoundary widgets add to the system is a way to say "always break the display list here" which prevents rebuilding the ancestors. That is worthwhile. The flags don't do that per-se, but they can be modified to achieve that goal or to work in concert with the RepaintBoundary to achieve both goals.

If any RenderObject, not just those from RepaintBoundary widgets, is allowed to say "I haven't changed so reuse my subtree" then the above issues will fall out. The RepaintBoundary objects don't really get in the way of that, but provide an added value to using flags to prevent recreation of stable children.

**Comment by goderbauer** [comment]
> This is not currently possible (?) with RepaintBoundaries because the ability to add a retained subtree is restricted to them (?).

Any layer can be added "as retained" to re-use its subtree. As far as I know, this is not restricted to the layers from RepaintBoundaries:

https://github.com/flutter/flutter/blob/44be0b84ba54a1a0a99304a4793bb30b340b7c15/packages/flutter/lib/src/rendering/layer.dart#L532-L551

**Comment by jonahwilliams** [comment]
I'm actually not sure what the benefit of retained rendering is here. As repaint boundaries have a managed layer, we can already guarantee it is stable and most engine APIs accept the old layer object to ensure identifiers are kept

**Comment by jonahwilliams** [comment]
@flar, I think we're on the same page here.

> With the flag system, the opacity might animate and it might insert a new OpacityLayer, but when it looks at its child it will see no flags on it and simply insert the previous child thereby automatically stabilizing it without any developer intervention and without any heuristics. This is not currently possible (?) with RepaintBoundaries because the ability to add a retained subtree is restricted to them (?).

This is the capability I plan to add. We do not have this capability today because the only render objects which can behave as repaint boundaries have no interesting properties - so we assume that if we have marked one dirty we should repaint the subtree (until we hit another repaint boundary or the leaf)

**Comment by jonahwilliams** [comment]
I updated the PR linked in this issue - it now has the capability for updates to a repaint boundary RO (like an opacity) to only update the layer and not recreate child layers.

**Comment by jonahwilliams** [comment]
Example of the improvement with moderately complex children of a fade transition:

https://flutter-flutter-perf.skia.org/e/?queries=test%3Danimated_complex_opacity_perf__e2e_summary

**Comment by jonahwilliams** [comment]
This is hitting an odd condition in g3 and causing an assert in 1 place. I'm not able to come up with a g3 fix so we're going to revert for now until I can fix  it

**Comment by JsouLiang** [comment]
> It can be hard for inexperienced users to identify a good place to locate a repaint boundary. Furthermore, as an application grows and develops the location of repaint boundaries may need to change.
I think it's very right, some users do not know where to add RepaintBoundary is correct. So if we can add the right RepaintBoundary without the user's perception, it is very helpful to develop a high-performance app.

I hope we can land this feature.

> This is hitting an odd condition in g3 and causing an assert in 1 place. I'm not able to come up with a g3 fix so we're going to revert for now until I can fix it
So what are the specific questions here and can you share them?
cc @jonahwilliams

**Comment by jonahwilliams** [comment]
We actually were able to fix it and land this. For more details into how this works, I would check out the PR - but feel free to file new issues to ask.

I would add that making ROs that were previously not composited into composited layers for the sake of repaint boundaries is generally harmful. But if they're already composited then its OK
