### ISSUE TITLE
SizedBox Issue

### ISSUE THREAD

**Issue by sunsj1** [flutter/flutter#101986]
/[C:/src/flutter/flutter/packages/flutter/lib/src/widgets/basic.dart:2304:44](): Error: The getter 'width' isn't defined for the class 'SizedBox'.
- 'SizedBox' is from 'package:flutter/src/widgets/basic.dart' ('/[C:/src/flutter/flutter/packages/flutter/lib/src/widgets/basic.dart]()').
package:flutter/…/widgets/basic.dart:1
Try correcting the name to the name of an existing getter, or defining a getter or field named 'width'.

    properties.add(DoubleProperty('width', width, defaultValue: null, level: level));

**Comment by danagbemava-nc** [comment]
Hi @sunsj1,

Can you please provide your `flutter doctor -v` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?

Thank you
