### ISSUE TITLE
☂️ Increase minimum support iOS version from 9 to 11

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#101959]
Increase minimum target iOS version from 9.0 to 11.0 [flutter.dev/go/rfc-32-bit-ios-unsupported](http://flutter.dev/go/rfc-32-bit-ios-unsupported).
In particular, this will let us drop OpenGL support on iOS in favor of Metal.

- [x] https://github.com/flutter/flutter/issues/101960
- [x] https://github.com/flutter/flutter/pull/103545
- [x] https://github.com/flutter/flutter/issues/103912
- [x] https://github.com/flutter/flutter/issues/101961
- [x] https://github.com/flutter/flutter/issues/101964
- [x] https://github.com/flutter/flutter/issues/52862
- [x] https://github.com/flutter/engine/pull/33401
- [x] https://github.com/flutter/engine/pull/34919
- [x] https://github.com/flutter/flutter/issues/101965
- [x] https://github.com/flutter/website/issues/7037

Cleanup:
- [x] https://github.com/flutter/flutter/issues/103929

See issues/PRs from when it was bumped 8.0->9.0
https://github.com/flutter/flutter/pull/62902
https://github.com/flutter/flutter/pull/68729
https://github.com/flutter/flutter/issues/84198
https://github.com/flutter/flutter/pull/85174
https://github.com/flutter/flutter/pull/89695
https://github.com/flutter/buildroot/pull/509
https://github.com/flutter/engine/pull/28572
https://github.com/flutter/engine/pull/28743
https://github.com/flutter/website/pull/6057

Though increasing the minimum from 9 to 11 will implicitly drop 32-bit iOS support, additional related work is tracked separately at https://github.com/flutter/flutter/issues/97327

**Comment by jmagman** [comment]
cc @xster for 1p app impact

**Comment by parlough** [comment]
Is there any followup work/cleanup remaining from this minimum change or can this be closed as completed? :)

**Comment by zanderso** [comment]
Yes, I think this can be closed.
