### ISSUE TITLE
Broken link at https://codelabs.developers.google.com/codelabs/first-flutter-app-pt2#6 

### ISSUE THREAD

**Issue by magaum** [flutter/flutter#101994]
# Steps to reproduce

1. Access https://codelabs.developers.google.com/codelabs/first-flutter-app-pt2#6
1. Click on ThemeData from "You can easily change an app's theme by configuring the **ThemeData** class"
1. The hyperlink is https://docs.flutter.io/flutter/material/ThemeData-class.html I guess it should be https://api.flutter.dev/flutter/material/ThemeData-class.html

Searching for related issues I've only seen #93477

**Comment by domesticmouse** [comment]
Googlers: Actually, the fix for this is in cl/443213697.

**Comment by maheshmnj** [comment]
@domesticmouse  should this be closed, considering the linked PR is merged?

**Comment by domesticmouse** [comment]
> @domesticmouse should this be closed, considering the linked PR is merged?

The linked PR wasn't actually a fix for this issue. The fix is in the CL instead, and I believe it is waiting a LGTM from @RedBrogdon =)

**Comment by domesticmouse** [comment]
CL landed
