### ISSUE TITLE
SystemChrome.setPreferredOrientations crash on iOS but not Android

### ISSUE THREAD

**Issue by JacoFourie** [flutter/flutter#101939]
Hi all. I have an app that needs to run in Portrait mode on most of its pages. 
I use this code and it works fine on iOS and Android to keep the app in portrait mode.

```
void main() {
  // We need to call it manually,
  // because we going to call setPreferredOrientations()
  // before the runApp() call
  WidgetsFlutterBinding.ensureInitialized();

  // Then we setup preferred orientations,
  // and only after it finished we run our app
  SystemChrome.setPreferredOrientations([DeviceOrientation.portraitUp])
      .then((value) => runApp(MyApp()));
}
```

Now I need to turn a page to landscape mode as it hosts a time series chart.

I followed this solution https://stackoverflow.com/questions/50322054/flutter-how-to-set-and-lock-screen-orientation-on-demand/50322184

I use this code when the page gets loaded it should flip on its side.

```
void initState() {
    super.initState();

   //Turn the app landscape
    SystemChrome.setPreferredOrientations([      
      DeviceOrientation.landscapeLeft,
    ]);

}

```
On Android, all work 100% but iOS will crash with no error to the debug window. 

How can I force one page to landscape mode?

![image](https://user-images.githubusercontent.com/17771641/163478904-156f6311-d4d6-444b-a747-6ca3d9b7b957.png)

**Comment by JacoFourie** [comment]
OK I got around it using a RotatedBox. Seems to work better than rotating the app anyway. But I still get a crash.

**Comment by darshankawar** [comment]
> But I still get a crash.

@JacoFourie 
Can you provide the error log ? You can try running in verbose mode `flutter run -v` and see if it gives you any crash log and share it here.

**Comment by JacoFourie** [comment]
@darshankawar as stated I do not use this method anymore so I removed the code from the project. You should be able to reproduce it yourself. Kind Regards.

**Comment by darshankawar** [comment]
@JacoFourie 
I tried below code sample based on details you provided and ran it on iOS simulator which shows me below:

<img width="368" alt="Screenshot 2022-04-20 at 10 55 57 AM" src="https://user-images.githubusercontent.com/67046386/164156573-e0d9e5dc-518f-4051-9acc-13f2e224dd35.png">

And it didn't crash for me.  I ran this on latest master `Channel master, 2.13.0-0.0.pre.635`.

<details>
<summary> runnable code sample </summary>

```

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() {
  // We need to call it manually,
  // because we going to call setPreferredOrientations()
  // before the runApp() call
  WidgetsFlutterBinding.ensureInitialized();

  // Then we setup preferred orientations,
  // and only after it finished we run our app
  SystemChrome.setPreferredOrientations([DeviceOrientation.portraitUp])
      .then((value) => runApp(MyApp()));
}

class MyApp extends StatefulWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  _MyAppState createState() => _MyAppState();
}



class _MyAppState extends State<MyApp> {


  void initState() {
    super.initState();

    //Turn the app landscape
    SystemChrome.setPreferredOrientations([
      DeviceOrientation.landscapeLeft,
    ]);

  }

```

</details>

If you run above does it crash at your end ?

**Comment by JacoFourie** [comment]
@darshankawar the code you shared does not compile. It does not have a build method. I can change the code but I would rather use the code you give me to make sure I run what you want me to run.

**Comment by JacoFourie** [comment]
OK I took the sample Flutter app and added the lines to rotate the screen and it works on my iPhone 6. But in my app I have one page that is portrait mode and then if you push to another page that page should be landscape.

**Comment by JacoFourie** [comment]
Mmmmm I can not reproduce the error using a small sample app. Maybe one of the Widgets I have in my app does not like this call and then crashes. I am able to turn the screen to landscape when I call another page in the sample app.
