### ISSUE TITLE
While i'm using getx to go to second route it shows here

### ISSUE THREAD

**Issue by farhansadikgalib** [flutter/flutter#101969]
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by iapicca** [comment]
probably should be addressed [here](https://github.com/jonataslaw/getx/issues)

**Comment by stuartmorgan** [comment]
Issues with third-party packages need to be reported to their developers, rather than the Flutter project.

Closing as this does not describe a Flutter bug report or feature request.
