### ISSUE TITLE
Flutter `Web` apps are not displayed correctly 

### ISSUE THREAD

**Issue by mdpe-ir** [flutter/flutter#101968]
Hello 
None of the Flutter web builds are displayed correctly to me. For example in flutter inspector ,I can not click on the widgets.

![Screenshot from 2022-04-15 10-17-40](https://user-images.githubusercontent.com/57597379/163527397-a022f646-17d7-41d3-8441-52c5338fa4f4.png)
![Screenshot from 2022-04-15 10-29-38](https://user-images.githubusercontent.com/57597379/163527987-b01d59bb-4c19-475a-a43b-8d5198395703.png)
![Screenshot from 2022-04-15 10-30-56](https://user-images.githubusercontent.com/57597379/163528074-87b54bdb-f54e-4914-ae0d-1f411f0a0909.png)
![Screenshot from 2022-04-15 10-34-59](https://user-images.githubusercontent.com/57597379/163528427-e03fe04f-36d5-4623-97c0-bd147f0483f8.png)

`flutter doctor --verbose`

> [✓] Flutter (Channel stable, 2.10.4, on EndeavourOS 5.17.2-arch3-1, locale
>     en_US.UTF-8)
>     • Flutter version 2.10.4 at /home/mahan/development/flutter
>     • Upstream repository https://github.com/flutter/flutter.git
>     • Framework revision c860cba910 (3 weeks ago), 2022-03-25 00:23:12 -0500
>     • Engine revision 57d3bac3dd
>     • Dart version 2.16.2
>     • DevTools version 2.9.2
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
>     • Android SDK at /home/mahan/Android/Sdk
>     • Platform android-32, build-tools 32.1.0-rc1
>     • Java binary at: /usr/bin/java
>     • Java version OpenJDK Runtime Environment (build 11.0.15+3)
>     • All Android licenses accepted.
> 
> [✓] Chrome - develop for the web
>     • Chrome at google-chrome
> 
> [✓] Linux toolchain - develop for Linux desktop
>     • clang version 13.0.1
>     • cmake version 3.23.1
>     • ninja version 1.10.2
>     • pkg-config version 1.8.0
> 
> [!] Android Studio (not installed)
>     • Android Studio not found; download from https://developer.android.com/studio/index.html
>       (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).
> 
> [✓] IntelliJ IDEA Ultimate Edition (version 2022.1)
>     • IntelliJ at /home/mahan/.local/share/JetBrains/Toolbox/apps/IDEA-U/ch-0/221.5080.210
>     • Flutter plugin version 66.0.4
>     • Dart plugin version 221.5177
> 
> [✓] Connected device (2 available)
>     • Linux (desktop) • linux  • linux-x64      • EndeavourOS 5.17.2-arch3-1
>     • Chrome (web)    • chrome • web-javascript • Google Chrome 100.0.4896.88
> 
> [✓] HTTP Host Availability
>     • All required HTTP hosts are available
> 
> ! Doctor found issues in 1 category.

`neofetch`
![Screenshot from 2022-04-15 10-27-25](https://user-images.githubusercontent.com/57597379/163527721-65084a8c-bd2a-4880-b3f3-87ce62df2f40.png)

**Comment by darshankawar** [comment]
> None of the Flutter web builds are displayed correctly to me.

Can you elaborate when you say this ? When you run your web build, are they not rendering on screen properly ? Or you are not able to click on the widget and layout tree explorer in the generated flutter devtools debugger link ?

**Comment by mdpe-ir** [comment]
> > None of the Flutter web builds are displayed correctly to me.
> 
> Can you elaborate when you say this ? When you run your web build, are they not rendering on screen properly ? Or you are not able to click on the widget and layout tree explorer in the generated flutter devtools debugger link ?

I noticed that Flutter could not detect the size of my screen, so it displayed the widgets in a cropped way. But when I changed the browser size with Dev tools to mobile size, everything  worked  fine.

---- 

After executing the following commands to solve the screen sharing (webrtc) problem in Wyland, the Flutter problem was also solved


```
yay -S xdg-desktop-portal-gnome gnome-remote-desktop

systemctl --user enable pipewire-media-session
systemctl --user start pipewire-media-session
systemctl --user restart xdg-desktop-portal-gnome

google-chrome-stable --enable-features=UseOzonePlatform --ozone-platform=wayland &

```


**Still i  not able to click on the widget and layout tree explorer in IntelliJ IDEA but Flutter Dev tools  works fine in chrome  .**

**Comment by darshankawar** [comment]
@mdpe-ir 
I suggest you to open the issue related to not being able to click on widgets here: https://github.com/flutter/flutter-intellij/issues

I am going ahead and closing this issue as resolved based on above comment. If you disagree, write in comments and I'll reopen it.
