### ISSUE TITLE
What is the difference between these two apks?

### ISSUE THREAD

**Issue by ddxl123** [flutter/flutter#101972]
build/app/outputs/apk/release/app-release.apk
build/app/outputs/flutter-apk/app-release.apk

**Comment by mdpe-ir** [comment]
@ddxl123 

> They are the same. Old version of flutter use outputs/apk/release directory but they changed it to outputs/flutter-apk recently. The old directory is kept for compatibility with other building tools.

[source](https://stackoverflow.com/a/62911870)

**Comment by Liberations** [comment]
md5sum build/app/outputs/apk/release/app-release.apk
md5sum build/app/outputs/flutter-apk/app-release.apk
They are the same.

**Comment by ddxl123** [comment]
> @ddxl123
> 
> > 它们是一样的。旧版本的 flutter 使用 outputs/apk/release 目录，但他们最近将其更改为 outputs/flutter-apk。保留旧目录是为了与其他构建工具兼容。
> 
> [源](https://stackoverflow.com/a/62911870)

What is the difference between app.apk and app-release/app-debug?

**Comment by Liberations** [comment]
> @mdpe-ir @Liberations
> 
> What is the difference between app.apk and app-release/app-debug?

no different.

**Comment by stuartmorgan** [comment]
See https://flutter.dev/community#community-grid for Q&A and discussion-style resources.

Closing as this does not describe a Flutter bug report or feature request.
