### ISSUE TITLE
Running simulations in a list aren't dynamically updated when the list dimensions change

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#102]
<a href="https://github.com/Hixie"><img src="https://avatars.githubusercontent.com/u/551196?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Hixie](https://github.com/Hixie)**
_Monday Jul 20, 2015 at 20:32 GMT_
_Originally opened as https://github.com/flutter/engine/issues/146_

----

_From @Hixie on April 21, 2015 19:29_

If you start a fling then change the height of the list by adding a query, the fling doesn't end in the appropriate place.

_Copied from original issue: domokit/mojo#107_

**Comment by Hixie** [comment]
I don't really understand what we're doing now. Sometimes we jump, sometimes we keep scrolling.

STEPS:
1. Load stocks. Maybe make the animations slower.
2. Hit search.
3. Scroll the list.
4. Type a search query.
5. Watch what happens to the list.

**Comment by eseidelGoogle** [comment]
Is this still an issue @Hixie?

**Comment by abarth** [comment]
Yeah, I fixed this as part of the LazyBlock work.
