### ISSUE TITLE
Flutter gradle redownload often

### ISSUE THREAD

**Issue by tootac** [flutter/flutter#102040]
I am working on a MacOS with flutter version 2.10.3. My issue is that I have a bit flaky internet connection so often downloads are slowing down workflow drastically. The issue that I see that almost every day or every other day when I try to build android version of the app it redownloads gradle and all the dependencies.

It all started with pressing build button and waiting for few hours without any no visible progress made. I tried it for several days with no luck. With a bit of lsof'ing I found that it tries to download gradle6.7 and probably failing. Well I just used wget to download it myself and put it into gradle download folder. It accepted the gradle6.7.zip but started downloading other gradle dependencies into temp folder. First of all if something happens internet flakes out it deletes gradle6.7 and start the whole process of downloading everything from scratch (sic!). And it does it over and over it could take many hours or days before it actually succeeds. 

The real problem is not this though. Ever so often (maybe every other day) flutter start this whole process from scratch (nothing changes in the project dependencies). The problem is that it downloads this same gradle6.7 with exact same dependencies. Is there any way to stop this? Can I ask flutter or gradle to settle a bit and not download anything unless I ask it to update or add a new dependency?

**Comment by tootac** [comment]
I forgot to mention that this has been going on for months for the same gradle6.7 version.

**Comment by darshankawar** [comment]
@tootac 
I think your question is better suited for support channels like Stackoverflow, as I don't see it as a bug or an issue. See [this](https://stackoverflow.com/questions/62589406/way-to-stop-android-studio-gradle-build-from-using-internet-data/62589571#62589571) similar SO link and answer and see if it helps.

**Comment by tootac** [comment]
From everything that I have seen in the internet it looks like gradle does downloads only once and then uses caches. So I can assume that flutter is the one doing cache invalidations all the time. I do not have free time to validate this by going though source code and this is the reason I am asking from people doing work on actual source code.

If my assumptions are correct then this is not a question for stackoverflow to solve my issue, it is a systematic problem for flutter build phase which needs to be addressed.

**Comment by maheshmnj** [comment]
related to https://github.com/flutter/flutter/issues/99080
