### ISSUE TITLE
E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: 'package:firebase_core_platform_interface/src/firebase_options.dart': Failed assertion: line 61 pos 16: 'map['apiKey'] != null': 'apiKey' cannot be null.

### ISSUE THREAD

**Issue by Silvia19948** [flutter/flutter#102026]
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
```
W/FlutterActivityAndFragmentDelegate(18135): A splash screen was provided to Flutter, but this is deprecated. See flutter.dev/go/android-splash-migration for migration steps.
E/flutter (18135): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: 'package:firebase_core_platform_interface/src/firebase_options.dart': Failed assertion: line 61 pos 16: 'map['apiKey'] != null': 'apiKey' cannot be null.
E/flutter (18135): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
E/flutter (18135): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
E/flutter (18135): #2      new FirebaseOptions.fromMap (package:firebase_core_platform_interface/src/firebase_options.dart:61:16)
E/flutter (18135): #3      MethodChannelFirebase._initializeFirebaseAppFromMap (package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart:45:23)
E/flutter (18135): #4      ListMixin.forEach (dart:collection/list.dart:86:13)
E/flutter (18135): #5      MethodChannelFirebase._initializeCore (package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart:35:10)
E/flutter (18135): <asynchronous suspension>
E/flutter (18135): #6      MethodChannelFirebase.initializeApp (package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart:73:7)
E/flutter (18135): <asynchronous suspension>
E/flutter (18135): #7      Firebase.initializeApp (package:firebase_core/src/firebase.dart:40:31)
E/flutter (18135): <asynchronous suspension>
E/flutter (18135): #8      main (package:my_firstapp/main.dart:11:3)
E/flutter (18135): <asynchronous suspension>
E/flutter (18135):
Syncing files to device ANE LX1...                                 252ms

Flutter run key commands.
r Hot reload.
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

Running with unsound null safety
For more information see https://dart.dev/null-safety/unsound-null-safety

3. ... <!-- describe steps to demonstrate bug -->
4. ... <!-- for example "Tap on X and see a crash" -->

**Expected results:** <!-- what did you want to see? -->
My app initial screen
```

**Actual results:** 

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:my_firstapp/locator.dart';
import 'package:my_firstapp/models/user_model.dart';
import 'package:my_firstapp/screens/wrapper.dart';
import 'package:provider/provider.dart';
import 'package:my_firstapp/services/auth.dart';
import 'package:firebase_core/firebase_core.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(name: '',options: FirebaseOptions(apiKey: "XXXXX", appId: "XXXXf", messagingSenderId: "XXXX", projectId: "XXXX", storageBucket: "XXX"));
  setupServices();
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return StreamProvider<UserModel>.value(
      value: AuthService().user,
      initialData: null,
      child: MaterialApp(
        theme: ThemeData(
          primaryColor: Color(0xff5FA55A),
          secondaryHeaderColor: Color(0xff5FA55A),
        ),
        home: Wrapper(),
      ),
    );
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
An Observatory debugger and profiler on ANE LX1 is available at: http://127.0.0.1:54415/piR0C4DqRK0=/
The Flutter DevTools debugger and profiler on ANE LX1 is available at:
http://127.0.0.1:9100?uri=http://127.0.0.1:54415/piR0C4DqRK0=/
E/        (18135): [ZeroHung]zrhung_get_config: Get config failed for wp[0x0102]
E/        (18135): [ZeroHung]zrhung_get_config: Get config failed for wp[0x0102]
D/AwareBitmapCacher(18135): handleInit switch not opened pid=18135
E/        (18135): [ZeroHung]zrhung_get_config: Get config failed for wp[0x0102]
E/        (18135): [ZeroHung]zrhung_get_config: Get config failed for wp[0x0102]
V/FA      (18135): Inactivity, disconnecting from the service
E/        (18135): [ZeroHung]zrhung_get_config: Get config failed for wp[0x0102]
E/        (18135): [ZeroHung]zrhung_get_config: Get config failed for wp[0x0102]
E/        (18135): [ZeroHung]zrhung_get_config: Get config failed for wp[0x0102]
E/        (18135): [ZeroHung]zrhung_get_config: Get config failed for wp[0x0102]
E/        (18135): [ZeroHung]zrhung_get_config: Get config failed for wp[0x0102]
E/        (18135): [ZeroHung]zrhung_get_config: Get config failed for wp[0x0102]
E/        (18135): [ZeroHung]zrhung_get_config: Get config failed for wp[0x0102]
E/        (18135): [ZeroHung]zrhung_get_config: Get config failed for wp[0x0102]
E/        (18135): [ZeroHung]zrhung_get_config: Get config failed for wp[0x0102]
E/        (18135): [ZeroHung]zrhung_get_config: Get config failed for wp[0x0102]
E/        (18135): [ZeroHung]zrhung_get_config: Get config failed for wp[0x0102]
E/        (18135): [ZeroHung]zrhung_get_config: Get config failed for wp[0x0102]
E/        (18135): [ZeroHung]zrhung_get_config: Get config failed for wp[0x0102]
E/        (18135): [ZeroHung]zrhung_get_config: Get config failed for wp[0x0102]
E/        (18135): [ZeroHung]zrhung_get_config: Get config failed for wp[0x0102]
E/        (18135): [ZeroHung]zrhung_get_config: Get config failed for wp[0x0102]

```

```
[√] Flutter (Channel stable, 2.10.4, on Microsoft Windows [Versione 10.0.19044.1645], locale it-IT)
    • Flutter version 2.10.4 at C:\Users\tagli\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (3 weeks ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

```

</details>

**Comment by Silvia19948** [comment]
C:\Users\tagli\flutter\bin\flutter.bat doctor --verbose
[√] Flutter (Channel stable, 2.10.4, on Microsoft Windows [Versione 10.0.19044.1645], locale it-IT)
    • Flutter version 2.10.4 at C:\Users\tagli\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (3 weeks ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at C:\Users\tagli\AppData\Local\Android\sdk
    • Platform android-32, build-tools 32.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.1.2)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.1.32319.34
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] VS Code (version 1.65.2)
    • VS Code at C:\Users\tagli\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (4 available)
    • ANE LX1 (mobile)  • 9WVDU19321009347 • android-arm64  • Android 9 (API 28)
    • Windows (desktop) • windows          • windows-x64    • Microsoft Windows [Versione 10.0.19044.1645]
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 100.0.4896.127
    • Edge (web)        • edge             • web-javascript • Microsoft Edge 100.0.1185.36
    ! Device emulator-5554 is offline.

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Comment by maheshmnj** [comment]
Hi @Silvia19948, The error seems to point issue in your code 

> firebase_options.dart': Failed assertion: line 61 pos 16: 'map['apiKey'] != null': 'apiKey' cannot be null. 

I would look at firebase_options.dart file and ensure map['apiKey'] is not null to resolve this error. Incase you need further help I would suggest you to please look for resources at https://flutter.dev/community#community-grid. You may also try seeking help on StackOverflow by posting the complete sample code and clearly describe the problem.

Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and we will reopen it.

Thank you



Closing, as this is neither a bug nor a feature request in flutter. Incase you disagree feel free to write in the comments and we will reopen it.

Thank you.

**Comment by Silvia19948** [comment]
Hi, thanks for the reply. I will close the github issue. I tryied to answer on stackOverflow woth no reply.
my firebase_options.dart is :
part of firebase_core_platform_interface;

/// The options used to configure a Firebase app.
///
/// ```dart
/// await Firebase.initializeApp(
///   name: 'SecondaryApp',
///   options: const FirebaseOptions(
///     apiKey: '...',
///     appId: '...',
///     messagingSenderId: '...',
///     projectId: '...',
///   )
/// );
/// ```
@immutable
class FirebaseOptions {
  /// The options used to configure a Firebase app.
  ///
  /// ```dart
  /// await Firebase.initializeApp(
  ///   name: 'SecondaryApp',
  ///   options: const FirebaseOptions(
  ///     apiKey: '...',
  ///     appId: '...',
  ///     messagingSenderId: '...',
  ///     projectId: '...',
  ///   )
  /// );
  /// ```
  const FirebaseOptions({
    required this.apiKey,
    required this.appId,
    required this.messagingSenderId,
    required this.projectId,
    this.authDomain,
    this.databaseURL,
    this.storageBucket,
    this.measurementId,
    // ios specific
    this.trackingId,
    this.deepLinkURLScheme,
    this.androidClientId,
    this.iosClientId,
    this.iosBundleId,
    this.appGroupId,
  });

  /// Named constructor to create [FirebaseOptions] from a Map.
  ///
  /// This constructor is used when platforms cannot directly return a
  /// [FirebaseOptions] instance, for example when data is sent back from a
  /// [MethodChannel].
  FirebaseOptions.fromMap(Map<dynamic, dynamic> map)
      : assert(map['apiKey'] != null, "'apiKey' cannot be null."),
        assert(map['appId'] != null, "'appId' cannot be null."),
        assert(map['messagingSenderId'] != null,
            "'messagingSenderId' cannot be null."),
        assert(map['projectId'] != null, "'projectId' cannot be null."),
        apiKey = map['apiKey'],
        appId = map['appId'],
        messagingSenderId = map['messagingSenderId'],
        projectId = map['projectId'],
        authDomain = map['authDomain'],
        databaseURL = map['databaseURL'],
        storageBucket = map['storageBucket'],
        measurementId = map['measurementId'],
        trackingId = map['trackingId'],
        deepLinkURLScheme = map['deepLinkURLScheme'],
        androidClientId = map['androidClientId'],
        iosClientId = map['iosClientId'],
        iosBundleId = map['iosBundleId'],
        appGroupId = map['appGroupId'];

  /// An API key used for authenticating requests from your app to Google
  /// servers.
  final String apiKey;

  /// The Google App ID that is used to uniquely identify an instance of an app.
  final String appId;

  /// The unique sender ID value used in messaging to identify your app.
  final String messagingSenderId;

  /// The Project ID from the Firebase console, for example "my-awesome-app".
  final String projectId;

  /// The auth domain used to handle redirects from OAuth provides on web
  /// platforms, for example "my-awesome-app.firebaseapp.com".
  final String? authDomain;

  /// The database root URL, for example "https://my-awesome-app.firebaseio.com."
  ///
  /// This property should be set for apps that use Firebase Database.
  final String? databaseURL;

  /// The Google Cloud Storage bucket name, for example
  /// "my-awesome-app.appspot.com".
  final String? storageBucket;

  /// The project measurement ID value used on web platforms with analytics.
  final String? measurementId;

  /// The tracking ID for Google Analytics, for example "UA-12345678-1", used to
  /// configure Google Analytics.
  ///
  /// This property is used on iOS only.
  final String? trackingId;

  /// The URL scheme used by iOS secondary apps for Dynamic Links.
  final String? deepLinkURLScheme;

  /// The Android client ID from the Firebase Console, for example
  /// "12345.apps.googleusercontent.com."
  ///
  /// This value is used by iOS only.
  final String? androidClientId;

  /// The iOS client ID from the Firebase Console, for example
  /// "12345.apps.googleusercontent.com."
  ///
  /// This value is used by iOS only.
  final String? iosClientId;

  /// The iOS bundle ID for the application. Defaults to `[[NSBundle mainBundle] bundleID]`
  /// when not set manually or in a plist.
  ///
  /// This property is used on iOS only.
  final String? iosBundleId;

  /// The iOS App Group identifier to share data between the application and the
  /// application extensions.
  ///
  /// Note that if using this then the App Group must be configured in the
  /// application and on the Apple Developer Portal.
  ///
  /// This property is used on iOS only.
  final String? appGroupId;

  /// The current instance as a [Map].
  Map<String, String?> get asMap {
    return <String, String?>{
      'apiKey': apiKey,
      'appId': appId,
      'messagingSenderId': messagingSenderId,
      'projectId': projectId,
      'authDomain': authDomain,
      'databaseURL': databaseURL,
      'storageBucket': storageBucket,
      'measurementId': measurementId,
      'trackingId': trackingId,
      'deepLinkURLScheme': deepLinkURLScheme,
      'androidClientId': androidClientId,
      'iosClientId': iosClientId,
      'iosBundleId': iosBundleId,
      'appGroupId': appGroupId,
    };
  }

  // Required from `fromMap` comparison
  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    if (other is! FirebaseOptions) return false;
    return const MapEquality().equals(asMap, other.asMap);
  }

  @override
  int get hashCode => const MapEquality().hash(asMap);

  @override
  String toString() => asMap.toString();
}

However it is a reader mode, can i change in someway?
Thanks for helping,best wishes    Il lunedì 18 aprile 2022, 10:33:03 CEST, Mahesh Jamdade ***@***.***> ha scritto:  
 
 


Hi @Silvia19948, The error seems to point issue in your code


firebase_options.dart': Failed assertion: line 61 pos 16: 'map['apiKey'] != null': 'apiKey' cannot be null.


I would look at firebase_options.dart file and ensure map['apiKey'] is not null to resolve this error. Incase you need further help I would suggest you to please look for resources at https://flutter.dev/community#community-grid. You may also try seeking help on StackOverflow by posting the complete sample code and clearly describe the problem.

Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and we will reopen it.

Thank you

Closing, as this is neither a bug nor a feature request in flutter. Incase you disagree feel free to write in the comments and we will reopen it.

Thank you.
