### ISSUE TITLE
Crash on invalid dynamic method call

### ISSUE THREAD

**Issue by Solido** [flutter/flutter#10200]
I've created a widget whose constructor take a method as a parameter
`MyWidget(bool action(String entry))`

String entry is required but the IDE will not detect if later I call it without 
`action()`

This lead to a app crash.

**Comment by mravn-google** [comment]
IntelliJ IDEA provides me a nice warning. Which version of the Dart plugin are you using? Easiest way is probably to include `flutter doctor` output. Mine says,
```
[✓] IntelliJ IDEA Community Edition (version 2016.3.4)
    • Dart plugin version 163.13137
    • Flutter plugin version 12.0
```

**Comment by Solido** [comment]
IntelliJ IDEA Community Edition (version 2016.3.4) 

I'm using 2017.1.2 and plugin is 13.1 can this explain the difference of behaviour ?

**Comment by eseidelGoogle** [comment]
That seems odd.  Do you have the dart analysis panel open?  Does `flutter analyze` run clean at the command line?

**Comment by Solido** [comment]
Guess you found smth.

`Could not find a command named "analyse".`

[✓] Flutter (on Mac OS X 10.12.4 16E195, channel master)
    • Flutter at /Users/robbie/Install/flutter
    • Framework revision 2da63e4657 (14 hours ago), 2017-05-18 18:09:51 -0700
    • Engine revision 82815836eb
    • Tools Dart version 1.23.0-dev.11.11

**Comment by Solido** [comment]
And to give other idea, Flutter doctor doesn't even find my Intellij installation. So maybe all this is linked.

**Comment by mravn-google** [comment]
`flutter analyze` with a z should work

**Comment by Solido** [comment]
Ok now I understand how it works, this command is the output I get in intellij Dart Analysis.
It doesn't display the case of invalid parameter. I get only 3 errors which concerns Const.

My code is as follow 
`MyWidgetConstructor(bool action(String entry), {
    Key key,
  }) : super(key: key) {
    this.inputEntryAction = action;
  }`

then under build method on a TextField

```
onSubmitted: (value) async {
if (value.trim().length == 0) return;

bool accepted = inputEntryAction(); // Should receive value or crash
if (accepted) {
 _inputController.clear();
}
},```

**Comment by mravn-google** [comment]
What type did you specify for `inputEntryAction`? If it's `dynamic` you basically told the analyzer to back off.

**Comment by mravn-google** [comment]
You may be able to avoid having two names for the same thing, e.g. by using `MyWidgetConstructor(bool this.action(String entry), ...)`

**Comment by Solido** [comment]
Obvious now you've demonstrated it and more readable, Thanks.
Should I use a typedef instead of using `bool this.action(String entry)` to get a error on the IDE ?
Parameter is required by the method but code is behaving like the parameter is optional. Should I use a TypeDef instead to raise a warning ?

**Comment by mravn-google** [comment]
Yes, you need a typedef to declare the `action` field with an explicit type

**Comment by Solido** [comment]
More Dart related than Flutter.
