### ISSUE TITLE
Assets analytics

### ISSUE THREAD

**Issue by a-eniou-pvotal** [flutter/flutter#102047]
## Use case

WebP images and WebM videos are free formats and They have a better file size than other formats I would like to use them only for my applications

## Proposal

We already have static analysis for dart code, but I wonder if there is a way to get a static analysis for the assets folder to use only WebP and WebM formats? (later checking for unused files)

**Comment by darshankawar** [comment]
@a-eniou-pvotal 
I think your issue is bettered to be reported in dedicated repo: https://github.com/dart-lang/sdk/issues
If you get redirected here, write in comments and I'll reopen it.
