### ISSUE TITLE
Webview not working with older ios devices.

### ISSUE THREAD

**Issue by hudatariq20** [flutter/flutter#102034]
## Steps to Reproduce

```
WebView(
  initialUrl: 'https://www.google.com/',
  javascriptMode: JavascriptMode.unrestricted,
)
```
Simply add a web view to your widget.
Using two different devices to run this application (iphone 11 IOS 15 VS iphone 6s Plus IOS 14)

**Expected results:**
Both of the devices should load google homepage inside the webview.

**Actual results:**
Getting expected results on the newer device i.e. IPhone 11 IOS 15 
However on the other device i.e. IPhone 6s Plus IOS 14 it shows a blank page, also upon debugging it via safari it shows about | blank page, also tried on IPhone 7 with IOS 15 but it also shows blank screen,

**Comment by darshankawar** [comment]
@hudatariq20 
I tried the webview_flutter plugin [example](https://github.com/flutter/plugins/tree/main/packages/webview_flutter/webview_flutter/example) on iPhone 6s (OS 15.3) on which it rendered the webview properly:

<img width="343" alt="Screenshot 2022-04-18 at 2 57 37 PM" src="https://user-images.githubusercontent.com/67046386/163788231-957b31fb-bd8f-4964-b481-8764c755496a.png">

I don't have other devices you specified, but that should not be an issue, as I am unable to replicate the behavior on my device.
Can you provide `flutter doctor -v` and run the plugin example on the devices you mentioned and see what you get ?
