### ISSUE TITLE
[Linux] Flutter app on a Linux environment  is distorted

### ISSUE THREAD

**Issue by ydddx** [flutter/flutter#102056]
The problem is similar to #93590 , but not wsl.
I found that it can be avoided as long as the tooltip is not triggered.
Do I need to provide any information?

**Comment by bernaferrari** [comment]
At least `flutter doctor -v` would be nice

**Comment by ydddx** [comment]
@bernaferrari 
sorry.
Dev environment
Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
[✓] Flutter (Channel stable, 2.10.2, on Ubuntu 20.04.4 LTS 5.10.102.1-microsoft-standard-WSL2, locale C.UTF-8)
    • Flutter version 2.10.2 at /home/yu/dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 097d3313d8 (8 weeks ago), 2022-02-18 19:33:08 -0600
    • Engine revision a83ed0e5e3
    • Dart version 2.16.1
    • DevTools version 2.9.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 20.04.4 LTS 5.10.102.1-microsoft-standard-WSL2
    • Chrome (web)    • chrome • web-javascript • Google Chrome 99.0.4844.82

Release environment
null

**Comment by ydddx** [comment]
![image](https://user-images.githubusercontent.com/58802847/163753001-83e35a3c-17ad-4523-ad9b-a34f90ddaeb8.png)

**Comment by bernaferrari** [comment]
Does it happen if you do `flutter create` ?

**Comment by ydddx** [comment]
> Does it happen if you do `flutter create` ?
must have tooltip

**Comment by maheshmnj** [comment]
Hi @ydddx, Thanks for filing the issue. 

> (Channel stable, 2.10.2, on Ubuntu 20.04.4 LTS 5.10.102.1-microsoft-standard-WSL2, locale C.UTF-8)

From your flutter doctor you seem to be using wsl, This issue is the same as the one you pointed?   https://github.com/flutter/flutter/issues/93590

**Comment by ydddx** [comment]
My development environment is WSL.
The publishing environment is not WSL.
The release environment does not have the flutter SDK installed

**Comment by maheshmnj** [comment]
Thanks for the info @ydddx 

> My development environment is WSL.

Since you are building the app on WSL  it could be the same as #93590.
Labeling this issue for further investigation since I do not have the required environment to triage further.
 
cc: @gspencergoog

**Comment by ydddx** [comment]
@maheshmnj 
I tried using other linux host distribution and had the same problem.

**Comment by maheshmnj** [comment]
> I tried using other linux host distribution and had the same problem.

Can you please share the output of `flutter doctor -v` of your machine?

**Comment by ydddx** [comment]
@maheshmnj 
Sorry I've been busy with work lately.

[✓] Flutter (Channel stable, 2.10.1, on Kylin V10 SP1 5.4.18-35-generic, locale zh_CN.UTF-8)
    • Flutter version 2.10.1 at /home/admin/flutter_linux/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db747aa133 (3 个月前), 2022-02-09 13:57:35 -0600
    • Engine revision ab46186b24
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4kylin1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] VS Code (version 1.64.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.38.1

[✓] Connected device (1 available)
    • Linux (desktop) • linux • linux-x64 • Kylin V10 SP1 5.4.18-35-generic

[☠] HTTP Host Availability (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    ✗ HandshakeException: Connection terminated during handshake
    • 

! Doctor found issues in 4 categories.

**Comment by ydddx** [comment]
@maheshmnj 
This is a very serious problem, can it be fixed asap
please.

**Comment by ydddx** [comment]
@maheshmnj 
I made a new attempt
https://github.com/flutter/flutter/issues/93590#issuecomment-1112808706

**Comment by ydddx** [comment]
I think it should be caused by some animation effects

**Comment by ydddx** [comment]
There are recent developments. It is found that because of the use of ‘texture’, the use of interface jumps must close the ‘texture’ in use to avoid this problem

**Comment by maheshmnj** [comment]
Thanks for the confirmation.
