### ISSUE TITLE
Android emulator detection yields false positives

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#10203]
Our [Android emulator detection](https://github.com/flutter/flutter/blob/10decc7c19bd0db30228932ef5d59d297b430977/packages/flutter_tools/lib/src/android/android_device.dart#L94) currently looks for the string "emulator" in the output of `adb shell getprop ro.build.characteristics`

Customer six discovered that on the Samsung Galaxy S8, the output of `adb shell getprop ro.build.characteristics` is "phone,emulator" even though it is obviously a physical device.

In release mode, this is causing the runner to fail with the message "Release mode is not supported for emulators".

Device details:
* Device: Samsung Galaxy S8
* Model: SM-G950F
* Android 7.0
* Samsung Experience 8.1
* Kernel 4.4.13-11168760

**Comment by eseidelGoogle** [comment]
Can someone post (or send to @tvolkert) the full `adb getprop` log from one of these devices? :)

**Comment by tvolkert** [comment]
I have an open request to get that info in the internal sibling of this bug -- I'll paste the output here when I get it (or someone else can -- whichever comes first)

**Comment by tvolkert** [comment]
Comments from internal Android expert:

> `ro.hardware` will be "goldfish" or "ranchu" for qemu or qemu2 based emulators

With regards to 3P emulators:

> all these props get set as part of the build of the system image. 3ps can redefine
> them however they want :(
> There is no standard way of communicating whether or not something is 'an emulator' :(

**Comment by aafa** [comment]
I'm having exactly this case on my device (samsung s7 edge)
```
$ adb shell getprop ro.hardware
samsungexynos8890

$ adb shell getprop ro.build.characteristics
phone,emulator

$ flutter devices
1 connected device:

SM G935F • ad0616030806e2dbae • android-arm • Android 7.0 (API 24) (emulator)
```

**Comment by tvolkert** [comment]
@aafa I just sent https://github.com/flutter/flutter/pull/11056 to add that device to the known-hardware list.

**Comment by aafa** [comment]
@tvolkert thank you! 🙇
