### ISSUE TITLE
Support finding N or more widgets in widget tests

### ISSUE THREAD

**Issue by DanielCardonaRojas** [flutter/flutter#102081]
## Use case

While writing widget tests it is often the case where you want to find n or more widgets
that match certain criteria. The framework currently supports 

findsNothing (None)
findsWidgets  (One or more)
findsNWidgets (Exactly n)
findsOneWidget (Exactly one)

## Proposal

It would be nice if we could use an additional finder that would support 

findsAtLeastNWidgets (n or more)

Looking into the [source](https://github.com/flutter/flutter/blob/c860cba910/packages/flutter_test/lib/src/matchers.dart#L85) the change would be minimal since the underlying (but private) Matcher class already supports this:

```dart
Matcher findsAtLeastNWidgets(int n) => _FindsWidgetMatcher(n, null);
```

I'll be happy to submit a PR if this seems reasonable

**Comment by darshankawar** [comment]
Thanks for the proposal. Feel free to submit PR.
