### ISSUE TITLE
Handles hidden partially by keyboard

### ISSUE THREAD

**Issue by jiangkang** [flutter/flutter#102039]
My solution gives enough spacing to fit the handle including its interactive padding (minimum 48px).  I could have just hardcoded it to 48px of spacing, but I think it looks better for Cupertino whose higher handles don't require as much space.  Also, this should continue to look nice if we add new handles for different platforms.

Native Android actually gives less space, but since we can't show the handles on top of the keyboard right now, this seems better to me.

Material             |  Cupertino
:-------------------------:|:-------------------------:
![flutter_04](https://user-images.githubusercontent.com/389558/58734675-f20c0b80-83ac-11e9-85c2-c584ae596b50.png)  |  ![flutter_03](https://user-images.githubusercontent.com/389558/58734676-f20c0b80-83ac-11e9-9b8c-24d4b1f8d92c.png)

_Originally posted by @justinmc in https://github.com/flutter/flutter/issues/32838#issuecomment-497860922_

**Comment by jiangkang** [comment]
In fact, this problem has not been solved, the pr just increased the bottom spacing, and the ideal solution is to make the widget of flutter displayed on the upper layer of the keyboard instead of being blocked

**Comment by darshankawar** [comment]
@jiangkang 
Can you provide `flutter doctor -v` and Android device on which you are experiencing this issue ? Please provide screenshots of it.

**Comment by jiangkang** [comment]
@darshankawar 

```
Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.5, on macOS 12.0.1 21A559 darwin-x64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[☠] IntelliJ IDEA Ultimate Edition (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    ✗ FormatException: Unexpected extension byte (at offset 5)
[✓] VS Code (version 1.66.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability
```
<img width="334" alt="image" src="https://user-images.githubusercontent.com/12570868/164202421-c07aa15f-e0a0-4088-939f-49b1331c9964.png">

**Comment by darshankawar** [comment]
@jiangkang 
I tried with Samsung A2Core device running API 28 but didn't see the behavior. Can you try the same on a different device and see if the behavior still persists ? Also provide a minimal code sample to take a look properly.
