### ISSUE TITLE
Flutter MDI window with multi Child Window Screen

### ISSUE THREAD

**Issue by abdulrehmananwar** [flutter/flutter#102037]
may i create MDI window with multi child screens. this help to work on multi screens at the same time
![image](https://user-images.githubusercontent.com/62530396/163712595-e5f9e315-f0eb-4f4c-ad5f-8b3823f857eb.png)

**Comment by FusoraTech** [comment]
Currently, Flutter apps acts like a tablet app, support for multiple windows (even the usual SDI) is due.
https://github.com/flutter/flutter/issues/30701

**Comment by danagbemava-nc** [comment]
Closing as duplicate of #30701

Thank you
