### ISSUE TITLE
### Page URL

### ISSUE THREAD

**Issue by macskle1** [flutter/flutter#102028]
### Page URL

@https://docs.flutter.dev/development/add-to-app/ios/project-setup#option-a---embed-with-cocoapods-and-the-flutter-sdk

### Describe the problem

When https://github.com/flutter/flutter/pull/101943 makes it to a tagged release, update `The `flutter_post_install` method (recently added to Flutter),` line to instead indicate the version in which it's available.

Introduced in https://github.com/flutter/website/pull/7032#issuecomment-1100241706.

__Originally posted by @jmagman in https://github.com/flutter/website/issues/7039__

**Comment by danagbemava-nc** [comment]
Closing as this is just a copy of an existing issue on the flutter website repo
