### ISSUE TITLE
[Proposal] Allow disabling smart-quotes in CupertinoSearchTextField

### ISSUE THREAD

**Issue by moffatman** [flutter/flutter#102058]
On `CupertinoTextField` you can set `smartQuotesType` so that the `"` doesn't get turned into `“`. It would be nice to have the same option exposed on `CupertinoSearchTextField` to avoid having to normalize before using the search field contents.

**Comment by justinmc** [comment]
Closing this with https://github.com/flutter/flutter/pull/97980
