### ISSUE TITLE
[tool_crash] _Exception in flutter analyze in Docker

### ISSUE THREAD

**Issue by H-Huang** [flutter/flutter#102082]
## Command
```
flutter analyze
```

## Steps to Reproduce
1. Build docker container with
<details>
<summary>Dockerfile</summary>

    FROM ubuntu:20.04
    
    # Used for tzdata
    ENV DEBIAN_FRONTEND=noninteractive
    
    # Android SDK
    # https://developer.android.com/studio#downloads
    ENV ANDROID_SDK_TOOLS_VERSION 8092744
    ENV ANDROID_HOME=/opt/android-sdk-linux
    # use sdkmanager --list to get list of packages
    ENV ANDROID_PLATFORM_VERSION 30
    ENV ANDROID_BUILD_TOOLS_VERSION 29.0.3
    ENV ANDROID_SDK_ROOT="$ANDROID_HOME"
    ENV PATH=${PATH}:${ANDROID_HOME}/cmdline-tools/tools/bin:${ANDROID_HOME}/platform-tools:${ANDROID_HOME}/emulator
    
    # Flutter SDK
    # https://flutter.dev/docs/development/tools/sdk/releases?tab=linux
    ENV FLUTTER_CHANNEL="stable"
    ENV FLUTTER_VERSION="2.10.4"
    ENV FLUTTER_HOME=/opt/flutter
    ENV PATH=${PATH}:${FLUTTER_HOME}/bin
    
    # This Dockerfile adds a non-root user with sudo access. Use the "remoteUser"
    # property in devcontainer.json to use it. On Linux, the container user's GID/UIDs
    # will be updated to match your local UID/GID (when using the dockerFile property).
    # See https://aka.ms/vscode-remote/containers/non-root-user for details.
    ARG USERNAME=vscode
    ARG USER_UID=1000
    ARG USER_GID=$USER_UID
    
    # Install needed packages, setup user and clean up.
    RUN  apt-get update && \
	    apt-get install -y sudo && \
	    apt-get install -y openjdk-8-jdk-headless --no-install-recommends && \
	    apt-get install -y wget curl git xz-utils zip unzip tzdata --no-install-recommends && \
	    apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev && \
	    # Create a non-root user to use if preferred - see https://aka.ms/vscode-remote/containers/non-root-user.
	    # [Optional] Add sudo support for the non-root user
	    groupadd --gid $USER_GID $USERNAME && \
	    useradd -s /bin/bash --uid $USER_UID --gid $USER_GID -m $USERNAME && \
	    echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME && \
	    chmod 0440 /etc/sudoers.d/$USERNAME
    
    # Android SDK
    RUN cd /opt \
	    && wget -O android-sdk-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-${ANDROID_SDK_TOOLS_VERSION}_latest.zip \
	    && mkdir -p ${ANDROID_SDK_ROOT}/cmdline-tools/ \
	    && unzip -q android-sdk-tools.zip -d ${ANDROID_SDK_ROOT}/cmdline-tools/ \
	    && mv ${ANDROID_SDK_ROOT}/cmdline-tools/cmdline-tools ${ANDROID_SDK_ROOT}/cmdline-tools/tools \
	    && rm android-sdk-tools.zip \
	    && yes | sdkmanager --licenses \
	    && touch $HOME/.android/repositories.cfg \
	    && sdkmanager platform-tools \
	    && sdkmanager emulator \
	    && sdkmanager "cmdline-tools;latest" \
	    && sdkmanager "platforms;android-$ANDROID_PLATFORM_VERSION" "build-tools;$ANDROID_BUILD_TOOLS_VERSION"
    
    # Chrome
    RUN cd /opt \
	    && wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb \
	    && apt-get install -y ./google-chrome-stable_current_amd64.deb
    
    # Flutter SDK
    RUN cd /opt && \
	    wget -O flutter.tar.xz https://storage.googleapis.com/flutter_infra_release/releases/${FLUTTER_CHANNEL}/linux/flutter_linux_${FLUTTER_VERSION}-${FLUTTER_CHANNEL}.tar.xz && \
	    tar xf flutter.tar.xz -C . && \
	    rm flutter.tar.xz
    
    # Change to non-root privilege
    USER $USERNAME
    
    # Install flutter
    RUN sudo chown -R $(whoami) /opt/flutter && \
	    git config --global --add safe.directory /opt/flutter && \
	    yes | flutter doctor --android-licenses && \
	    flutter config --no-analytics && \
	    flutter config --enable-web && \
	    flutter update-packages
</details>

2. `flutter create myapp`
3. `flutter analyze` (fails with error below)
4. `flutter run` (also fails with `the Dart compiler exited unexpectedly.`)

## Logs
_Exception
```
_Exception: Exception: analysis server exited with code -9 and output:
[stdout] {"event":"server.connected","params":{"version":"1.32.8","pid":4574}}
[stdout] {"id":"1"}
[stdout] {"event":"analysis.errors","params":{"file":"/workspaces/flutter_demo/myapp/android/app/src/debug/AndroidManifest.xml","errors":[]}}
[stdout] {"event":"analysis.errors","params":{"file":"/workspaces/flutter_demo/myapp/android/app/src/main/AndroidManifest.xml","errors":[]}}
[stdout] {"event":"analysis.errors","params":{"file":"/workspaces/flutter_demo/myapp/android/app/src/profile/AndroidManifest.xml","errors":[]}}
[stdout] {"event":"analysis.errors","params":{"file":"/workspaces/flutter_demo/myapp/analysis_options.yaml","errors":[]}}
[stdout] {"event":"analysis.errors","params":{"file":"/workspaces/flutter_demo/myapp/pubspec.yaml","errors":[]}}
[stdout] {"id":"2"}
[stdout] {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
```

## flutter doctor
[✓] Flutter (Channel stable, 2.10.4, on Ubuntu 20.04.4 LTS 4.19.121-linuxkit, locale en_US.UTF-8)
    • Flutter version 2.10.4 at /opt/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (3 weeks ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /opt/android-sdk-linux
    • Platform android-30, build-tools 29.0.3
    • ANDROID_HOME = /opt/android-sdk-linux
    • ANDROID_SDK_ROOT = /opt/android-sdk-linux
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_312-8u312-b07-0ubuntu1~20.04-b07)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[!] Android Studio (not installed)
    • Android Studio not found

**Comment by darshankawar** [comment]
> 4\. also fails with `the Dart compiler exited unexpectedly.`

@H-Huang Can you also provide the entire error log that shows this ?

**Comment by H-Huang** [comment]
@darshankawar Sure. Here is the entire log:

```
vscode@38a01b984611:/workspaces/flutter_demo/myapp$ flutter run -v
[ +101 ms] executing: uname -m
[  +65 ms] Exit code 0 from: uname -m
[   +2 ms] x86_64
[  +21 ms] executing: [/opt/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +38 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] c860cba910319332564e1e9d470a17074c1f2dfd
[        ] executing: [/opt/flutter/] git tag --points-at c860cba910319332564e1e9d470a17074c1f2dfd
[  +61 ms] Exit code 0 from: git tag --points-at c860cba910319332564e1e9d470a17074c1f2dfd
[        ] 2.10.4
[  +13 ms] executing: [/opt/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +10 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/opt/flutter/] git ls-remote --get-url origin
[  +12 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +178 ms] executing: [/opt/flutter/] git rev-parse --abbrev-ref HEAD
[  +10 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[ +178 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +9 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +227 ms] executing: /opt/android-sdk-linux/platform-tools/adb devices -l
[  +59 ms] List of devices attached
[   +7 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +308 ms] Skipping pub get: version match.
[ +818 ms] Generating /workspaces/flutter_demo/myapp/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[ +994 ms] Launching lib/main.dart on Chrome in debug mode...
[ +217 ms] Updating assets
[ +198 ms] Waiting for connection from debug service on Chrome...
[ +300 ms] <- reset
[  +27 ms] /opt/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev /opt/flutter/bin/cache/artifacts/engine/linux-x64/frontend_server.dart.snapshot --sdk-root
/opt/flutter/bin/cache/flutter_web_sdk/ --incremental --target=dartdevc --debugger-module-names --experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true
--output-dill /tmp/flutter_tools.ZINFGU/flutter_tool.RPUYPE/app.dill --libraries-spec file:///opt/flutter/bin/cache/flutter_web_sdk/libraries.json --packages
/workspaces/flutter_demo/myapp/.dart_tool/package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-root
/tmp/flutter_tools.ZINFGU/flutter_tools.ELTQHS --filesystem-scheme org-dartlang-app --initialize-from-dill build/b1b715402d823b7fd5c2b68d2edcb2ce.cache.dill.track.dill
--platform file:///opt/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk_sound.dill --sound-null-safety
[  +91 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[+145086 ms] "flutter run" took 148,222ms.
[  +32 ms] the Dart compiler exited unexpectedly.
[   +7 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      DefaultResidentCompiler._compile.<anonymous closure> (package:flutter_tools/src/compile.dart:773:13)
           #2      _rootRun (dart:async/zone.dart:1418:47)
           #3      _CustomZone.run (dart:async/zone.dart:1328:19)
           #4      _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
           #5      _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:394:13)
           #6      _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:404:7)
           #7      _BufferingStreamSubscription._close (dart:async/stream_impl.dart:291:7)
           #8      _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:87:11)
           #9      _EventSinkWrapper.close (dart:async/stream_transformers.dart:21:11)
           #10     _StringAdapterSink.close (dart:convert/string_conversion.dart:251:11)
           #11     _LineSplitterSink.close (dart:convert/line_splitter.dart:154:11)
           #12     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:132:24)
           #13     _rootRun (dart:async/zone.dart:1418:47)
           #14     _CustomZone.run (dart:async/zone.dart:1328:19)
           #15     _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
           #16     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:394:13)
           #17     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:404:7)
           #18     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:291:7)
           #19     _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:87:11)
           #20     _EventSinkWrapper.close (dart:async/stream_transformers.dart:21:11)
           #21     _StringAdapterSink.close (dart:convert/string_conversion.dart:251:11)
           #22     _Utf8ConversionSink.close (dart:convert/string_conversion.dart:305:20)
           #23     _ConverterStreamEventSink.close (dart:convert/chunked_conversion.dart:81:18)
           #24     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:132:24)
           #25     _rootRun (dart:async/zone.dart:1418:47)
           #26     _CustomZone.run (dart:async/zone.dart:1328:19)
           #27     _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
           #28     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:394:13)
           #29     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:404:7)
           #30     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:291:7)
           #31     _SyncStreamControllerDispatch._sendDone (dart:async/stream_controller.dart:782:19)
           #32     _StreamController._closeUnchecked (dart:async/stream_controller.dart:637:7)
           #33     _StreamController.close (dart:async/stream_controller.dart:630:5)
           #34     _Socket._onData (dart:io-patch/socket_patch.dart:2321:21)
           #35     _rootRunUnary (dart:async/zone.dart:1442:13)
           #36     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
           #37     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
           #38     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
           #39     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
           #40     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:774:19)
           #41     _StreamController._add (dart:async/stream_controller.dart:648:7)
           #42     _StreamController.add (dart:async/stream_controller.dart:596:5)
           #43     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1846:35)
           #44     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1315:18)
           #45     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
           #46     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
           #47     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:122:13)
           #48     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:193:5)
           
           
[  +31 ms] Running shutdown hooks
[   +9 ms] Waiting for connection from debug service on Chrome... (completed in 145.6s)
[   +4 ms] Synced 0.0MB.
[   +2 ms] Failed to compile application.
[        ] Shutdown hooks complete
[   +7 ms] exiting with code 1
```

**Comment by darshankawar** [comment]
Thanks for the update. Labeling it for further investigation based on the report.

/cc @christopherfujino

**Comment by christopherfujino** [comment]
@H-Huang can you also share the log output of building your docker image? I suspect there may be some clues as to what went wrong there.

**Comment by H-Huang** [comment]
> can you also share the log output of building your docker image? I suspect there may be some clues as to what went wrong there.

@christopherfujino  Thanks! Sure enough, when I outputted the log it seems like the last line did not complete.
<details>

    #8 [6/6] RUN sudo chown -R $(whoami) /opt/flutter && 	git config --global --add safe.directory /opt/flutter && 	yes | flutter doctor --android-licenses && 	flutter config --no-analytics && 	flutter config --enable-web && 	flutter update-packages
    #8 sha256:a31f19548e80b4d2cf1bd85cbda3c5761d39f71b2e0e0992b5416e5b3ccdd3c5
    #8 33.88 ╔════════════════════════════════════════════════════════════════════════════╗
    #8 33.88 ║ A new version of Flutter is available!                                     ║
    #8 33.88 ║                                                                            ║
    #8 33.88 ║ To update to the latest version, run "flutter upgrade".                    ║
    #8 33.88 ╚════════════════════════════════════════════════════════════════════════════╝
    #8 33.88 
    #8 36.01 
    #8 36.01   ╔════════════════════════════════════════════════════════════════════════════╗
    #8 36.01   ║                 Welcome to Flutter! - https://flutter.dev                  ║
    #8 36.01   ║                                                                            ║
    #8 36.01   ║ The Flutter tool uses Google Analytics to anonymously report feature usage ║
    #8 36.01   ║ statistics and basic crash reports. This data is used to help improve      ║
    #8 36.01   ║ Flutter tools over time.                                                   ║
    #8 36.01   ║                                                                            ║
    #8 36.01   ║ Flutter tool analytics are not sent on the very first run. To disable      ║
    #8 36.01   ║ reporting, type 'flutter config --no-analytics'. To display the current    ║
    #8 36.01   ║ setting, type 'flutter config'. If you opt out of analytics, an opt-out    ║
    #8 36.01   ║ event will be sent, and then no further information will be sent by the    ║
    #8 36.01   ║ Flutter tool.                                                              ║
    #8 36.01   ║                                                                            ║
    #8 36.01   ║ By downloading the Flutter SDK, you agree to the Google Terms of Service.  ║
    #8 36.01   ║ Note: The Google Privacy Policy describes how data is handled in this      ║
    #8 36.01   ║ service.                                                                   ║
    #8 36.01   ║                                                                            ║
    #8 36.01   ║ Moreover, Flutter includes the Dart SDK, which may send usage metrics and  ║
    #8 36.01   ║ crash reports to Google.                                                   ║
    #8 36.01   ║                                                                            ║
    #8 36.01   ║ Read about data we send with crash reports:                                ║
    #8 36.01   ║ https://flutter.dev/docs/reference/crash-reporting                         ║
    #8 36.01   ║                                                                            ║
    #8 36.01   ║ See Google's privacy policy:                                               ║
    #8 36.01   ║ https://policies.google.com/privacy                                        ║
    #8 36.01   ╚════════════════════════════════════════════════════════════════════════════╝
    #8 36.01 
    #8 36.08 Running "flutter pub get" in flutter_tools...                      26.9s
    #8 64.91 Loading local repository...                                                     
    [=========                              ] 25% Loading local repository...       
    [=========                              ] 25% Fetch remote repository...        
    [==========                             ] 26% Fetch remote repository...        
                                                                                
    [==========                             ] 26% Fetch remote repository...        
    Warning: IO exception while downloading manifest
    #8 65.98 [============                           ] 31% Fetch remote repository...        
    [=============                          ] 33% Fetch remote repository...        
    [=============                          ] 34% Fetch remote repository...        
    [==============                         ] 36% Fetch remote repository...        
    [==============                         ] 37% Fetch remote repository...        
    [===============                        ] 38% Fetch remote repository...        
    [===============                        ] 40% Fetch remote repository...        
    [================                       ] 41% Fetch remote repository...        
    [=================                      ] 43% Fetch remote repository...        
    [=================                      ] 44% Fetch remote repository...        
    [==================                     ] 45% Fetch remote repository...        
    [==================                     ] 47% Fetch remote repository...        
    [===================                    ] 48% Fetch remote repository...        
    [===================                    ] 50% Fetch remote repository...        
    [====================                   ] 51% Fetch remote repository...        
    [====================                   ] 53% Fetch remote repository...        
    [=====================                  ] 54% Fetch remote repository...        
    [======================                 ] 55% Fetch remote repository...        
    [======================                 ] 57% Fetch remote repository...        
    [=======================                ] 58% Fetch remote repository...        
    [=======================                ] 60% Fetch remote repository...        
    [========================               ] 61% Fetch remote repository...        
    [========================               ] 62% Fetch remote repository...        
    [=========================              ] 64% Fetch remote repository...        
    [==========================             ] 65% Fetch remote repository...        
    [==========================             ] 67% Fetch remote repository...        
    [===========================            ] 68% Fetch remote repository...        
    [===========================            ] 69% Fetch remote repository...        
    [============================           ] 71% Fetch remote repository...        
    [============================           ] 72% Fetch remote repository...        
    [============================           ] 72% Computing updates...              
    [=============================          ] 75% Computing updates...              
    [=======================================] 100% Computing updates...             
    All SDK package licenses accepted.
    #8 66.25 
    #8 67.47 Analytics reporting disabled.
    #8 67.47 
    #8 67.47 You may need to restart any open editors for them to read new settings.
    #8 68.33 Setting "enable-web" value to "true".
    #8 68.34 
    #8 68.34 You may need to restart any open editors for them to read new settings.
    #8 71.14 Running "flutter pub get" in flutter_update_packages.CDKEAJ...        13.9s
    #8 85.01 Running "flutter pub get" in affected packages...    

</details>

This is surprising to me since the docker image finished building and I am able to attach to the container. When I run `flutter update packages` in the container the command finishes and subsequently `flutter run` now works!

**Perhaps a follow up could be to make sure `flutter update packages` exits with an error code on failure? Not sure why the docker container was still built when the command didn't succeed.**

> Also, is there a reason you need to use a non-root user in your container? I would think this setup would be simpler if you run as root in the container.

No reason, I had run everything as root before, but when using `flutter run` it mentioned about not running as root (think I read something online about not using root as well) so I made a change in set up as well.

I am still not able to use chrome + flutter in a docker container, but that is a separate error :)

**Comment by christopherfujino** [comment]
> > can you also share the log output of building your docker image? I suspect there may be some clues as to what went wrong there.
> 
> @christopherfujino Thanks! Sure enough, when I outputted the log it seems like the last line did not complete.
> 
> This is surprising to me since the docker image finished building and I am able to attach to the container. When I run `flutter update packages` in the container  the command finishes and subsequently `flutter run` now works!

I am very glad that `flutter run` works! It does indeed sound like a bug that `flutter update-packages` did not exit non-zero in this case. However, I would add that that line is not required for this workflow, that command is mainly for our CI tests or for local development, where you will be running an integration test that depends on a sample app being built.

> > Also, is there a reason you need to use a non-root user in your container? I would think this setup would be simpler if you run as root in the container.
> 
> No reason, I had run everything as root before, but when using `flutter run` it mentioned about not running as root (think I read something online about not using root as well) so I made a change in set up as well.

Yes, running as root is usually bad...except I would say in a docker container :). My understanding is that running anything in docker is functionally equivalent to running as root, as the docker daemon needs essentially to run as root, and containers were not designed as security sandboxes. The only reason I can think of to run as non-root in a container is if you will be writing to files mounted as a volume from the host filesystem, in which case you probably don't want those files to be owned by root.

> I am still not able to use chrome + flutter in a docker container, but that is a separate error :)

I am sure, however it's great you've made this much progress. Out of curiosity, are you following a tutorial, or just figuring this out from scratch? If the latter, it would be great if you document the process for the benefit of others.

**Comment by H-Huang** [comment]
Sounds good, thanks again @christopherfujino!

> Out of curiosity, are you following a tutorial, or just figuring this out from scratch? If the latter, it would be great if you document the process for the benefit of others.

I am just figuring this out and new to flutter. Generally I like using vscode and using [devcontainers](https://code.visualstudio.com/docs/remote/containers) as my development environment to easily switch between / combine projects, so I was writing the Dockerfile for that. I can certainly document it by creating a repo or gist, let me know if there is anything in particular you were thinking.

**Comment by christopherfujino** [comment]
I am closing this issue as it sounds like the issue was that docker image was not correctly built (and flutter update-packages is not really intended for this purpose).
