### ISSUE TITLE
iOS: add_to_App Demo can't run in release mode

### ISSUE THREAD

**Issue by dongqihouse** [flutter/flutter#102070]
## Steps to Reproduce

1. Execute `flutter run --release` on the code sample 
2. click the next button 
3. no response 

https://github.com/flutter/flutter/issues/91841 
the issue is closed but not work on iOS.

**Expected results:** 
run normally

**Actual results:** 
no response

<details>
<summary>Code sample</summary>

```dart
void main() => runApp(const MyApp(color: Colors.blue));

@pragma('vm:entry-point')
void topMain() => runApp(const MyApp(color: Colors.green));

@pragma('vm:entry-point')
void bottomMain() => runApp(const MyApp(color: Colors.purple));
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
Analyzing multiple_flutters_ios...
No issues found! (ran in 1.0s)
```

```
➜  multiple_flutters_ios git:(master) ✗ flutter doctor -v
[✓] Flutter (Channel master, 2.13.0-0.0.pre.602, on macOS 12.3.1 21E258 darwin-x64, locale en-CN)
    • Flutter version 2.13.0-0.0.pre.602 at /Users/qd/development/flutter
    • Upstream repository git@github.com:flutter/flutter.git
    • Framework revision f4875ae865 (14 hours ago), 2022-04-17 15:19:07 -0400
    • Engine revision 3c6d4da868
    • Dart version 2.18.0 (build 2.18.0-24.0.dev)
    • DevTools version 2.12.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/qd/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code (version 1.66.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.38.1

[✓] Connected device (3 available)
    • iPhone8 iOS14 (mobile)              • c0d1fe12c1229a887ee58aeea699a456ac17328e • ios            • iOS
      14.4.1 18D61
    • iPhone SE (3rd generation) (mobile) • 812D0FCF-7D6C-4FA4-AC51-22CAAA28365D     • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-15-4 (simulator)
    • Chrome (web)                        • chrome                                   • web-javascript • Google
      Chrome 100.0.4896.88

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

</details>

**Comment by dongqihouse** [comment]
@gaaclarke  how fix this on iOS?

**Comment by maheshmnj** [comment]
Hi @dongqihouse, Thanks for filing the issue. Can you please share a minimal sample project that aligns with your reproducible steps?

**Comment by gaaclarke** [comment]
The title mentions add-to-app but the reproduction steps don't mention it.  Can you please clarify that as well?  Thanks.

**Comment by dongqihouse** [comment]
flutter --version
Flutter 2.13.0-0.0.pre.602 • channel master • git@github.com:flutter/flutter.git
Framework • revision f4875ae865 (29 hours ago) • 2022-04-17 15:19:07 -0400
Engine • revision 3c6d4da868
Tools • Dart 2.18.0 (build 2.18.0-24.0.dev) • DevTools 2.12.2

project:
https://github.com/flutter/samples/tree/master/add_to_app/multiple_flutters

Steps to Reproduce:
1. run `flutter run --release` on iOS device
2.  `@pragma('vm:entry-point')` is not work on iOS

@gaaclarke

**Comment by darshankawar** [comment]
@dongqihouse 
I tried the `multiple_flutters` app and ran it on iOS device in release mode, wherein it worked as expected. See below:


https://user-images.githubusercontent.com/67046386/163981339-dc16d893-ae98-4f30-acaf-e332d1218392.MP4


`Channel master, 2.13.0-0.0.pre.617`

Did you properly compile and built the app using below steps ?

1. cd multiple_flutters_module -> `flutter pub get`.
2. cd multiple_flutters_ios -> `pod install`.
3. Then run in `--release` mode ?

Also, when you say `not work on iOS`, do you get any error ? Can you run `flutter run --release -v` and check if you get any errors in the log while trying to tap on next button ?

Does it work in debug mode as expected ? or if you comment out `@pragma('vm:entry-point')` , does it work in release mode ?

**Comment by dongqihouse** [comment]
sorry.I was wrong for this issue.

I should build the multiple_flutters_ios project with Xcode.
multiple_flutters_module can not runs independently.

thanks for your reply
