### ISSUE TITLE
Should be able to subscribe to changes on properties of MediaQuery instead of all changes

### ISSUE THREAD

**Issue by moffatman** [flutter/flutter#102060]
Since https://github.com/flutter/engine/pull/29281 during keyboard opening animation the root `MediaQuery` will be updated with each frame. There are a lot of widgets which might call `MediaQuery.of(context)` but not all depend on all of the `MediaQuery` properties. It would be more efficient to only rebuild those widgets which depend on the change in screen dimensions, but not the widgets which depend on the text scale factor, which presumably isn't changing with each frame.

Related to https://github.com/flutter/flutter/issues/98115
Somewhat related to https://github.com/flutter/flutter/issues/96044

**Comment by HansMuller** [comment]
[InheritedModel](https://api.flutter.dev/flutter/widgets/InheritedModel-class.html) enables dependency on just one "aspect" of an inherited widget. It might be possible to retrofit MediaQuery to be an InheritedModel.

**Comment by moffatman** [comment]
@HansMuller  See the linked PR #97928. I used InheritedModel and it noticeably improved performance during keyboard animation.

**Comment by jseminck** [comment]
We use MediaQuery a lot to access certain properties like (`padding.bottom`), but are having issues that keyboard animations are triggering unnecessary rebuilds on the pages in the navigator stack, and that causes jankyness. So having the ability to subscribe to certain changes only would be amazing for us.

**Comment by zhangwen0510** [comment]
any update on this?
