### ISSUE TITLE
Command line shows more signing options then Xcode

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#10206]
On the command line I have a choice of:

```shell
~/dev/flutter/examples/flutter_gallery (master *) $ flutter run --local-engine=ios_debug_unopt
Building flutter tool...
Running "flutter packages get" in flutter_gallery...  7.2s
Launching lib/main.dart on iPod touch in debug mode...
Multiple valid development certificates available:
  1) iPhone Developer: Google Development (3F4Y5873JF)
  2) iPhone Developer: Michael Goderbauer (43MBX2N7P7)
  3) iPhone Developer: goderbauer@google.com (8TD5W76VGS)
  4) iPhone Developer: Michael Goderbauer (KY4Q2ZN4ME)
  a) Abort
Please select a certificate for code signing [1|2|3|4|a]:
```

In Xcode I only see one option (and I also don't know to which option on the command line that one maps):
![screen shot 2017-05-19 at 10 10 25 am](https://cloud.githubusercontent.com/assets/1227763/26258934/af2760d2-3c7b-11e7-95d3-3ba6d7dff699.png)

I love that I don't have to open Xcode anymore to sign my app. But I am also slightly confused by the options presented. :)

/cc @xster

**Comment by xster** [comment]
Uber short answer: they all do the same thing

Short answer: the command line shows you certs which map many to many to organizational units whereas based on my 10 minute reverse engineering, Xcode shows you organizational units via private API calls to Apple's developer account backends directly. The primary source available locally on the machine we can use without adding more dependencies is the cert themselves.

Medium answer: normally, average users should have one team/organizational unit and one certificate (for development. We don't show the deployment cert). Though it's possible to revoke and issue more certificates with the same Apple account. Perhaps a nicer quality of life feature to add to the command line is to go to each valid cert, extract the organizational unit, dedupe that and show that instead. Based on some anecdotal testing, the cert output and parsing cost is orders of magnitude lower than a whole bunch of other stuff we do so it's probably ok. 

Long answer: let me take a look at your computer when you have a chance :)

**Comment by xster** [comment]
For record: another observation made: if the user logs off of some account in Xcode, the certificate that account imported is still on the machine and usable. I think that's ok.

**Comment by xster** [comment]
Don't fix. It's not too harmful I think and all this could go away with xcode 9 as well.
