### ISSUE TITLE
[camera] windows camera plugin permission handling

### ISSUE THREAD

**Issue by hellohuanlin** [flutter/flutter#102098]
## Use case

This issue is to track work on the camera access permission for camera plugin on Windows platform. 

We would like to send consistent error code to the dart side, so that developers can re-use code. 
 

CC: @cbracken 

## Proposal

[Proposal here](https://docs.google.com/document/d/1t_5FYzOTlBWC6arHc4_8VuG0BUOtIyP9xWvbDER5Y9I/edit)

**Comment by cbracken** [comment]
You'll find the source for the camera plugin here:
https://github.com/flutter/plugins/tree/main/packages/camera

My recollection is that there may also be some breadcrumbs in the comments of where further error handling is needed.

**Comment by loic-sharma** [comment]
Added in https://github.com/flutter/plugins/pull/6154
