### ISSUE TITLE
Linux Fuchsia CI test is failing on a Fuchsia SDK file that doesn't actually exist in the SDK yet

### ISSUE THREAD

**Issue by richkadel** [flutter/flutter#102013]
Linux Fuchsia CI test is failing with:

[5470/8130] ACTION //flutter/tools/fuchsia/dart:fidl_source_verification(//flutter/tools/fuchsia/dart:dartlang)
FAILED: dartlang/gen/flutter/tools/fuchsia/dart/fidl_source_verification.missing 
python3 ../../flutter/tools/fuchsia/dart/verify_sources.py --source_dir /b/s/w/ir/cache/builder/src/fuchsia/sdk/linux/dart/fidl/lib --stamp /b/s/w/ir/cache/builder/src/out/fuchsia_debug_x64/dartlang/gen/flutter/tools/fuchsia/dart/fidl_source_verification.missing fidl.dart src/bits.dart src/codec.dart src/codegen_common.dart src/enum.dart src/error.dart src/hash_codes.dart src/interface.dart src/interface_async.dart src/message.dart src/struct.dart src/table.dart src/types.dart src/union.dart src/unknown_data.dart src/wire_format.dart

Source files found that were missing from the "sources" parameter:
/b/s/w/ir/cache/builder/src/fuchsia/sdk/linux/dart/fidl/lib/src/optional_nullable.dart

The optional_nullable.dart is not in the current version of the Fuchsia SDK, but may have been cached during a test of a future change, and the builder should have purged it.

**Comment by godofredoc** [comment]
\cc @keyonghan

**Comment by akbiggs** [comment]
Thanks for the fix Rich!
