### ISSUE TITLE
[local_auth] Update README for changes in 2.0

### ISSUE THREAD

**Issue by ArielM24** [flutter/flutter#102164]
I want to customize the messages of the dialog with IOSAuthMessages and AndroidAuthMessages, but I can't find the classes anymore.
The actual version is 2.0.0

**Comment by stuartmorgan** [comment]
In the new federated structure you need to import the implementation packages (`local_auth_android`, `local_auth_ios`) to use platform-specific extensions.

That should have been updated in the README, but was missed in the update.

**Comment by stuartmorgan** [comment]
This would be a good opportunity to try out live code excerpts, to solve the general problem.

**Comment by EdwynZN** [comment]
The imports are also not detected by the IDE (VSCode) and without the README updated there isn't really a hint on what is going on

<img width="656" alt="imagen" src="https://user-images.githubusercontent.com/16828084/164969361-54d0c3da-c90a-4b23-a1de-4fc7ee768314.png">

**Comment by patrick-enzo** [comment]
A migration guide would be greatly appreciated. I'm also having difficulty with the error_code import.

**Comment by Jenry94** [comment]
import this lines:

import 'package:local_auth_ios/local_auth_ios.dart';
import 'package:local_auth_android/local_auth_android.dart';

and lests go

**Comment by AlexV525** [comment]
Regarding the README, all new features are missing from this document, not only the federated structure. e.g. *strong* and *weak* biometric types are not well introduced as supported types and have no links with relevant documents.
