### ISSUE TITLE
[InAppPurchase] InappPurchase's productDetails is always [ ] 

### ISSUE THREAD

**Issue by kotran88** [flutter/flutter#102199]
[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/aIvON.png

I added 2 products in google publish console as picture above. 
buymecoffee , buymecoffee2 and both are active. 

but with my code, it returns list [] 

is there any thing I should do ? code and google play store publish links with package name? because I didn't do anything that is seems connect both  code and google play store . 

code is 

    const Set<String> _kIds = <String>{'buymecoffee', 'buymecoffee2'};
    final ProductDetailsResponse response =
        await InAppPurchase.instance.queryProductDetails(_kIds);
    if (response.notFoundIDs.isNotEmpty) {
      // Handle the error.
    }
    List<ProductDetails> products = response.productDetails;

    // Set<String> ids = Set<String>.from(["buymecoffee"]);
    // final ProductDetailsResponse response =
    //     await _inAppPurchase.queryProductDetails(ids);
    // List<ProductDetails> products = response.productDetails;
    // for (ProductDetails product in products) {
    //   print(
    //       '${product.title}: ${product.description} (cost is ${product.price})');
    // }
    print(products.length);
    print("available333444433");
    print(response.productDetails.toString());

**Comment by darshankawar** [comment]
@kotran88 
Can you provide `flutter doctor -v` and plugin version you are using ?

**Comment by kotran88** [comment]
@darshankawar 
here it is. 
and app is not production on google playstore, 

[✓] Flutter (Channel stable, 2.10.5, on macOS 12.3 21E230 darwin-arm, locale ko-KR)
    • Flutter version 2.10.5 at /Users/pedrojung/Downloads/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (3 days ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/pedrojung/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Users/pedrojung/Downloads/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.66.2)
    • VS Code at /Users/pedrojung/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.38.1

[✓] Connected device (3 available)
    • SM S908N (mobile)           • R3CT10CNYYP   • android-arm64  • Android 12 (API 31)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 12 (API 31) (emulator)
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 100.0.4896.127

[✓] HTTP Host Availability
    • All required HTTP hosts are available

**Comment by darshankawar** [comment]
@kotran88 
I suggest you to check the plugin example for code implementation and see if it helps you to properly check if there's anything missing in your code.

https://github.com/flutter/plugins/blob/main/packages/in_app_purchase/in_app_purchase/example/lib/main.dart#L90
