### ISSUE TITLE
List tile border not animating together with rest elemtns

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [flutter/flutter#102150]
Hello,

I am doing multistep registration and have 7 steps with multiple components. After each step, when pressing 'Next', old step slides away and new one slides in. All steps are working as expected except one. In gender step I have generated list with radios. each ListTile has border. When pressing next radios slides away and border stays until animation ends. I will attach video. Here is my code:

```
import 'package:flutter/material.dart';
import 'package:seven_seven/infrastructure/constants/custom-colors.dart';
import 'package:seven_seven/infrastructure/constants/setting.dart';
import 'package:seven_seven/infrastructure/extensions/string_extensions.dart';

class SevenSevenRadioList<TValue> extends StatefulWidget {
  final List<SevenSevenRadioItem> items;
  final ValueChanged<TValue?> onChanged;
  final TValue? groupValue;
  final String? errorText;

  const SevenSevenRadioList({
    required this.items,
    required this.onChanged,
    required this.groupValue,
    this.errorText,
  });

  @override
  State<SevenSevenRadioList<TValue>> createState() => _SevenSevenRadioListState<TValue>();
}

class _SevenSevenRadioListState<TValue> extends State<SevenSevenRadioList<TValue>> {
  @override
  Widget build(BuildContext context) {
    return Column(
      mainAxisAlignment: MainAxisAlignment.start,
      mainAxisSize: MainAxisSize.min,
      children: <Widget>[
        Row(
          mainAxisAlignment: MainAxisAlignment.start,
          crossAxisAlignment: CrossAxisAlignment.start,
          children: List.generate(widget.items.length, (index) {
            var leftPadding = _getLeftPadding(index, widget.items.length);
            var rightPadding = _getRightPadding(index, widget.items.length);

            return Flexible(
              child: Container(
                margin: EdgeInsets.only(left: leftPadding, right: rightPadding),
                child: ListTile(
                  title: Text(widget.items[index].title, style: Theme.of(context).textTheme.bodyText1),
                  trailing: Radio<TValue>(
                    value: widget.items[index].value,
                    groupValue: widget.groupValue,
                    onChanged: widget.onChanged,
                  ),
                  contentPadding: const EdgeInsets.only(right: 0, left: 16),
                  shape: RoundedRectangleBorder(
                    side: BorderSide(
                      color: widget.errorText.isNullOrEmpty() ? CustomColors.lightGrey : CustomColors.danger,
                      width: 1,
                    ),
                    borderRadius: BorderRadius.circular(Settings.borderRounding),
                  ),
                ),
              ),
            );
          }),
        ),
        if (!widget.errorText.isNullOrEmpty()) ...[
          const SizedBox(height: 8),
          Text(widget.errorText!, style: Theme.of(context).textTheme.bodyText2!.copyWith(color: CustomColors.danger)),
        ],
      ],
    );
  }

  double _getLeftPadding(int index, int itemsCount) {
    return index > 0 ? 5 : 0;
  }

  double _getRightPadding(int index, int itemsCount) {
    if (index < itemsCount - 1) {
      return 5;
    }

    return 0;
  }
}

class SevenSevenRadioItem<TValue> {
  final String title;
  final TValue value;

  SevenSevenRadioItem(this.title, this.value);
}

```

https://user-images.githubusercontent.com/3918999/164042803-772a7a05-302a-4df6-b395-e6be8471718c.mov

**Comment by darshankawar** [comment]
@vytautas-pranskunas- 
Hard to say if it's a bug because there are lot of things going on looking at your code. 
To fix this behavior, you seem to have added `decoration` code implementation inside `Container` which contains `ListTile` as a child, which indicates the animation effect need to be implemented at parent level instead of child to properly animate the screen.

**Comment by vytautas-pranskunas-** [comment]
@darshankawar i do not get is it a question?
But yes, adding decoration on parent fixed the problem - but... there is a but... This component is a kind of container and animation is playing against this container so theoritically animation should not care what components and what structure is inside of container right? but looks like it cares.

**Comment by darshankawar** [comment]
> i do not get is it a question?

It was more of a statement to something to think about. 

Can you show previous screen how the animation works as compared to current screen you showed ? 
Also, in order to address this behavior properly, a minimal code sample replicating the behavior would be useful.

**Comment by darshankawar** [comment]
Looks like you have worked out a solution, so I am not sure if you are still looking to report this as unexpected behavior or a bug.
Moreover, you may try https://api.flutter.dev/flutter/widgets/AnimatedContainer-class.html widget and see if it helps to properly implement your animation.
