### ISSUE TITLE
Get impellerc/libtessellator building on Windows bots

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#102165]
@zanderso says this is failing:

https://logs.chromium.org/logs/flutter/led/zra_google.com/1f17b834611d4fa950cdf57fca5a1cca95376a5cd6ce50bab15c87ff52c50e36/+/u/build_host_debug_flutter_impeller_tessellator:tessellator_shared_flutter_impeller_compiler:impellerc/stdout?format=raw

@jonahwilliams says this builds locally using VS2019. 

@cbracken says we're using VS2019 on the bots.

**Comment by dnfield** [comment]
This is probably a matter of just adding the right `#include`s/definitions for Windows.

**Comment by dnfield** [comment]
Bots are using VS2017.

**Comment by dnfield** [comment]
Some other side notes:

- include-what-you-use might be able to catch this but it runs risks of false positives/negatives and isn't trivial to build/distribute.
- clang-include-fixer might be able to help but we don't seem to have all the bits needed.
- @petrhosek tells me there's an RFC to add some clangd functionality that can catch this to clang-tidy: https://discourse.llvm.org/t/rfc-lifting-include-cleaner-missing-unused-include-detection-out-of-clangd/61228. Once that's available we should definitely turn that on, as it would catch at least some of the errors being seen here.

**Comment by petrhosek** [comment]
`find-all-symbols` which is needed for `clang-include-fixer` will be included in the next Fuchsia Clang toolchain.

**Comment by dnfield** [comment]
This now builds as part of the default engine build on Windows, macOS, and Linux.
