### ISSUE TITLE
[cocoon] Rerunning GitHub checks twice results in check being stuck as pending

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#102162]
On my release PRs to 2.13.0 I've noticed this. I'm dealing with the ios simulator flakes, and everytime I get to a rerun of a rerun (i.e. the 3rd attempt), the check gets stuck.

See https://github.com/flutter/engine/pull/32775/checks?check_run_id=6081715069 for an example.

The expected results is that any N reruns will always schedule the build

**Comment by keyonghan** [comment]
Does this issue still happen?
