### ISSUE TITLE
Flutter tools debugging with web server device is not working with chrome 100.x

### ISSUE THREAD

**Issue by annagrin** [flutter/flutter#102159]
See comment in https://github.com/flutter/flutter/issues/101224#issuecomment-1097565580

The issues are caused by https://github.com/dart-lang/webdev/issues/1581

Related: https://github.com/flutter/flutter/issues/101224

/cc @fhuonder

**Comment by fhuonder** [comment]
Hi @annagrin 

Thanks for fixing webdev. When will it be released? When will it land in flutter?

**Comment by toshiossada** [comment]
Great

**Comment by ugurberkecan** [comment]
any update ?

**Comment by fabianogadenz** [comment]
following
