### ISSUE TITLE
Reuse Xcode build when building for another IOS device

### ISSUE THREAD

**Issue by JustMilan** [flutter/flutter#102132]
## Use case

If I want to test/run my app on multiple IOS devices. For each device the Xcode build step has to be done all over again. 
This step is the most time consuming one.

## Proposal

That when using `flutter run` and choosing an IOS device. That it looks for an already built one and reuses that build to complete the next IOS build.

**Comment by darshankawar** [comment]
@JustMilan 
Have you tried running `flutter run -d all` ? I just now tried with it using a sample app which compiled and built the app on iOS simulator, iPhone and macOS at once and Xcode build ran only once.

**Comment by JustMilan** [comment]
Thanks, `flutter run -d all` runs the app on all devices and the Xcode build will only be executed once. After all these steps the command finishes, but I don't get the hot reload menu. 

this is what I get when I run `flutter run -d all`:
`(base) milandol@MacBook-Pro-van-Milan excelerate % flutter run -d all
Using hardware rendering with device Android SDK built for x86 64. If you notice graphics artifacts, consider enabling software rendering with "--enable-software-rendering".
Launching lib/main.dart on Android SDK built for x86 64 in debug mode...
Launching lib/main.dart on iPhone 13 in debug mode...
Launching lib/main.dart on iPhone SE (3rd generation) in debug mode...
Running Gradle task 'assembleDebug'...                              8.9s
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
Running Xcode build...                                                  
Xcode build done.                                            2.9s
Failed to build iOS app
Error output from Xcode build:
↳
    2022-04-19 12:07:19.539 xcodebuild[3678:1082448] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionSentinelHostApplications for extension
    Xcode.DebuggerFoundation.AppExtensionHosts.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
    2022-04-19 12:07:19.540 xcodebuild[3678:1082448] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionPointIdentifierToBundleIdentifier for extension
    Xcode.DebuggerFoundation.AppExtensionToBundleIdentifierMap.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
    ** BUILD FAILED **


Xcode's output:
↳
    Writing result bundle at path:
    	/var/folders/8s/j7xcf3ts7kv2gvyfl34v_4900000gn/T/flutter_tools.Kz6fis/flutter_ios_build_temp_dirq96x4W/temporary_xcresult_bundle

    note: Using new build system
    error: Build service could not create build operation: unknown error while handling message: Could not acquire lock at path
    `/Users/milandol/Library/Developer/Xcode/DerivedData/Runner-bejfvqvwfforpvfauhsjlfambbfi/Build/Intermediates.noindex/XCBuildData/PIFCache/PROJECT@v11_mod=1650362824.7037988_hash=18c1723432283e0c
    c55f10a6dcfd9e02-Project.lock`

    Result bundle written to path:
    	/var/folders/8s/j7xcf3ts7kv2gvyfl34v_4900000gn/T/flutter_tools.Kz6fis/flutter_ios_build_temp_dirq96x4W/temporary_xcresult_bundle


Error (Xcode): Build service could not create build operation: unknown error while handling message: Could not acquire lock at path
`/Users/milandol/Library/Developer/Xcode/DerivedData/Runner-bejfvqvwfforpvfauhsjlfambbfi/Build/Intermediates.noindex/XCBuildData/PIFCache/PROJECT@v11_mod=1650362824.7037988_hash=18c1723432283e0cc55f
10a6dcfd9e02-Project.lock`


Could not build the application for the simulator.
Error launching application on iPhone 13.
 └─Compiling, linking and signing...                         6.9s
Xcode build done.                                           27.9s
(base) milandol@MacBook-Pro-van-Milan excelerate % 
`

this is what I see after I do `flutter run` -> select device
`(base) milandol@MacBook-Pro-van-Milan excelerate % flutter run 
Multiple devices found:
Android SDK built for x86 64 (mobile) • emulator-5554                        • android-x64    • Android 12 (API 31) (emulator)
iPhone 13 (mobile)                    • 7CC561AB-F15C-43F8-9121-4C5043530BBF • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-4
(simulator)
iPhone SE (3rd generation) (mobile)   • CE4BACB8-B857-4903-BF42-72122357393D • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-4
(simulator)
Chrome (web)                          • chrome                               • web-javascript • Google Chrome 100.0.4896.88
[1]: Android SDK built for x86 64 (emulator-5554)
[2]: iPhone 13 (7CC561AB-F15C-43F8-9121-4C5043530BBF)
[3]: iPhone SE (3rd generation) (CE4BACB8-B857-4903-BF42-72122357393D)
[4]: Chrome (chrome)
Please choose one (To quit, press "q/Q"): 3
Launching lib/main.dart on iPhone SE (3rd generation) in debug mode...
Running Xcode build...                                                  
 └─Compiling, linking and signing...                         8.6s
Xcode build done.                                           27.2s
Syncing files to device iPhone SE (3rd generation)...              118ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

💪 Running with sound null safety 💪

An Observatory debugger and profiler on iPhone SE (3rd generation) is available at: http://127.0.0.1:60629/brx8qBNGLas=/
The Flutter DevTools debugger and profiler on iPhone SE (3rd generation) is available at:
http://127.0.0.1:9100?uri=http://127.0.0.1:60629/brx8qBNGLas=/
`

Do I need to attach all devices separately after `flutter run -d all`?

**Comment by darshankawar** [comment]
Check this article and see if it helps https://flutteragency.com/how-to-hot-reload-to-multiple-devices-in-flutter/
