### ISSUE TITLE
Expected to find ','.

### ISSUE THREAD

**Issue by a120476536** [flutter/flutter#102269]
![bug](https://user-images.githubusercontent.com/7939484/164362444-811493dd-42f2-45dd-9322-1ea461ebf79b.png)

`BannerBean banner = BannerBean()`  error 。。。

**Comment by jonahwilliams** [comment]
`HttpUtil.instance.get(Api.MAINCONTENT).then((value) => {`

Should instead be

`HttpUtil.instance.get(Api.MAINCONTENT).then((value) {`

**Comment by a120476536** [comment]
> 

thank you very much

**Comment by danagbemava-nc** [comment]
Hi @a120476536, has your issue been resolved?
