### ISSUE TITLE
Let smaller headers be perma-linkable

### ISSUE THREAD

**Issue by xster** [flutter/flutter#10225]
If I want to point someone to the 'Set up the iOS simulator' section under https://flutter.io/setup-macos/#ios-setup, I don't seem to be able to.

**Comment by sethladd** [comment]
Thanks for the suggestion. PR's welcome to add ID's :)

**Comment by mit-mit** [comment]
@xster the "trick" is to add small `{#desiredsublink}` annotations to the heading, for example:

```
## Architectural overview: platform channels {#architecture}
```

**Comment by Sfshaza** [comment]
@mit-mit is right, the website generates anchors using header names. This can get gnarly, but it's always possible for the author to override with shorter anchors, as Michael suggests.

For developers, if the page includes a TOC, that's the best way to get the link+anchor. That's how I got this one:  https://flutter.io/flutter-for-ios/#what-is-the-equivalent-to-viewcontrollers-in-flutter

I'm closing this issue.
