### ISSUE TITLE
[webview_flutter_wkwebview] How to customize ios code and reference on pubscpec.xml

### ISSUE THREAD

**Issue by mdmota** [flutter/flutter#102238]
How do I use the webview_flutter plugin but with custom webview_flutter_wkwebview?

In pubspec I reference the webview_flutter and copy the folder from the webview_flutter_wkwebview and make reference to the folder? or do I have to put them all in folders and reference them in pubspec?

**Comment by stuartmorgan** [comment]
Currently you will need to fork webview_flutter to use an alternate implementation package. See https://github.com/flutter/flutter/issues/102245

**Comment by mdmota** [comment]
I read and didn't understand

**Comment by mdmota** [comment]
a fork of webview_flutter won't do. the native codes are in his dependencies([webview_flutter_android](https://pub.dev/packages/webview_flutter_android), [webview_flutter_platform_interface](https://pub.dev/packages/webview_flutter_platform_interface), [webview_flutter_wkwebview](https://pub.dev/packages/webview_flutter_wkwebview)).

**Comment by stuartmorgan** [comment]
> a fork of webview_flutter won't do. the native codes are in his dependencies

I understand that you want to fork a dependency. I'm saying that currently you need to also fork the app-facing package in order to point to your forked dependency.
