### ISSUE TITLE
[flutter_conductor] allow codesign verification script to run on linux machines

### ISSUE THREAD

**Issue by itsjustkevin** [flutter/flutter#102242]
When attempting to run codesign verification on a linux machine, the following error message is received:

`Exception: Error! Expected operating system "macos", actual operating system is: "linux"`

cc @CaseyHillers @christopherfujino

**Comment by christopherfujino** [comment]
Verifying the code signatures (AFAIK) requires Xcode, thus this check.

**Comment by christopherfujino** [comment]
Looks technically possible, this open source app will even let you sign: https://github.com/sauce-archives/isign. IDK if we should rely on it, though, as Apple frequently has breaking changes to these processes without any advance warning.

**Comment by CaseyHillers** [comment]
\cc @XilaiZhang this is an example of something we'd want to put in infra, that way the conductor isn't required to run on macos.

**Comment by christopherfujino** [comment]
note, the way the code is written now, we'd also have to trick the tool into thinking it was on a mac, in order to download the right archives

**Comment by christopherfujino** [comment]
Closing this as not practical
