### ISSUE TITLE
Implement federated plugin implementation selection for native plugins

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#102245]
The federated plugin spec describes plugin clients being able to depend directly on an alternate implementation package to override an endorsed `default_package` implementation. We've implemented this for Dart implementations, but not for the native implementations, which means that currently, using an alternate implementation requires forking the app-facing package.

We should refactor and extend the implementation selection logic that currently exists for the Dart plugin to apply to the native implementations as well, so that we never add the overridden default to the native build step.

**Comment by Gustl22** [comment]
Just wondering, isn't this the same as #80374?

**Comment by stuartmorgan** [comment]
Yes, apparently I forgot we had an issue taking this.
