### ISSUE TITLE
Reducing the cost of ImageFilter

### ISSUE THREAD

**Issue by nikitadol** [flutter/flutter#102211]
## Use case

Some `ImageFilter` is resource intensive and looks different than on native development

## Proposal

As it turned out, some filters on iOS have `_requestedScaleHint`, which specifies the value at which the image falls into the filter

You can see in the screenshot:
![Screenshot 2021-03-27 at 12 57 45](https://user-images.githubusercontent.com/16593680/164220064-d284c88f-9f64-489c-bba7-d975d2852fee.png)

Perhaps it would be convenient to be able to adjust this parameter in Flutter:
- filters would be able to work faster
- filters can consume fewer resources (CPU/GPU)

**Comment by chinmaygarde** [comment]
Do you have a more detailed proposal for a specific Flutter API. The issue as titled is extremely vague.

**Comment by nikitadol** [comment]
I have two options:
- Add a parameter that will reduce the size of the input picture
- Make a filter that will reduce the size of the input image

**Comment by jonahwilliams** [comment]
We did not accept this proposal.
