### ISSUE TITLE
Add self-contained SafeArea to NavigationRail

### ISSUE THREAD

**Issue by Piinks** [flutter/flutter#102263]
The NavigationRail does not respect SafeAreas by default. This requires wrapping a SafeArea to ensure it is available, for example, when using an iPhone with a notch:

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const Material3Demo());
}

class Material3Demo extends StatelessWidget {
  const Material3Demo({Key? key}) : super(key: key);
  @override
  Widget build(BuildContext context) {
    return MainScreen();
  }
}

class MainScreen extends StatefulWidget {
  const MainScreen({Key? key}) : super(key: key);

  @override
  State<MainScreen> createState() => _MainScreenState();
}

class _MainScreenState extends State<MainScreen> {
  int _selectedIndex = 0;

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Demo'),
        ),
        backgroundColor: Colors.amberAccent[100],
        body: SafeArea(
            bottom: false,
            top: false,
            child: Row(
              children: [NavigationRail(
                minWidth: 50,
                destinations: const <NavigationRailDestination>[
                  NavigationRailDestination(
                    icon: Icon(Icons.widgets_outlined),
                    label: Text('Demo 1'),
                  ),
                  NavigationRailDestination(
                    icon: Icon(Icons.format_paint_outlined),
                    label: Text('Demo 2'),
                  ),
                ],
                selectedIndex: _selectedIndex,
                useIndicator: true,
                onDestinationSelected: (index) {
                  setState(() {
                    _selectedIndex = index;
                  });
                },
              ),
              Expanded(child: Container(color: Colors.blueAccent[100])),
              ]
            )),
      ),
    );
  }
}

```

This looks somewhat as expected:

![Screen Shot 2022-04-20 at 6 18 40 PM](https://user-images.githubusercontent.com/16964204/164340221-e8f15b52-7aa6-4e12-b67a-55e0a09df5ee.png)

But when flipped it definitely looks off:

![Screen Shot 2022-04-20 at 6 16 07 PM](https://user-images.githubusercontent.com/16964204/164340261-dbe8e486-b244-453a-8c0b-4e365295ca09.png)

When consulting the guidelines for SafeArea on iOS, the margins the SafeArea is applying are correct in landscape mode:
https://github.com/flutter/flutter/issues/28956#issuecomment-472188242

But it makes me wonder if the NavigationRail should function more like the AppBar. This widget has a self-contained SafeArea, and is how
- **the background of the AppBar extends up through the status bar area** while 
- **the content of the AppBar is inset below the status bar**.

Seen here:
![Screen Shot 2022-04-20 at 6 16 27 PM](https://user-images.githubusercontent.com/16964204/164340470-e4445b54-b81f-4d96-b8e7-72190ca9ee86.png)

And implemented here:
https://github.com/flutter/flutter/blob/9313fb8e287b63b5c3b740156cc7cf4a86f722d1/packages/flutter/lib/src/material/app_bar.dart#L1011

The Material Design spec does not provide a recommendation for NavigationRail as it relates to notches, likely because the NavigationRail is recommended for larger screens, we may want to reach out to the design team.

https://material.io/components/navigation-rail#behavior

I think the AppBar behavior that contains its own SafeArea makes sense, especially since the current NavigationRail can end up in the middle of a notch. It would be nice if we could handle this cleanly for our users, no one will ever want a rail in a cutout.

Widgets that contain their own safe area as a pattern seems to allude folks as well, I found these while looking into this:
- https://stackoverflow.com/questions/67542879/flutter-safearea-avoid-notches-but-ignore-rounded-corners
- https://stackoverflow.com/questions/64464468/flutter-whitespaces-displaying-for-image-in-portrait-and-landscape

Interested parties may be...
@darrenaustin
@QuncCccccc (Thanks for finding this!)
@craiglabenz

**Comment by Piinks** [comment]
Oh sweet, sounds like the research has already been done here. This should be an easy fix.

**Comment by Piinks** [comment]
I am going to close this to defer to #101605, @QuncCccccc I see you already assigned there, let me know if I can assist.

**Comment by QuncCccccc** [comment]
@Piinks Thanks a lot for all the explanation! I'll take a look for both problems.
