### ISSUE TITLE
Drawer drops frames before JIT warms up

### ISSUE THREAD

**Issue by tain335** [flutter/flutter#1022]
when I package a apk, how to make ahead-of-time work?

**Comment by abarth** [comment]
We haven't wired up ahead-of-time compilation on Android.  We just use that on iOS.  We've talked about doing it, but I think we want to do something slightly different than what we do on iOS.  Specifically, I think we want to AOT compile the code by leave the ability to recompile it dynamically latter using the JIT.  That way you get all the benefits of AOT compilation and all the benefits of JIT compilation.

**Comment by tain335** [comment]
When I open a flutter app (eg. stocks) on  my android phone, the drawer animation is not smooth enough, but after try several times (open and close drawer) ,  the app can improve its animation. And I am not sure the reason (dart vm JIT or flutter framework ?). So I want to know  if use AOT , could it run   smoother, when user first time open app.

**Comment by abarth** [comment]
Yes, we've seen the same thing and the VM team is working on the issue.  If you use AOT, then it will run smooth the first time.  However, the plan is to do better by improving the VM in the following ways:

1. Teach the JIT how to optimize code on a background thread.
2. Teach the AOT compiler how to generate code that the JIT can later optimize by recompiling.

We've talked about wiring up AOT compilation on Android while the VM folks are working on those features, but our current plan is invest in making other parts of the system better while we wait for (1) and (2).

**Comment by spierce7** [comment]
So I had a similar concern about the dropped frames with the JIT running. The proposed solution though sounds like the best of both worlds. I hope that comes to fruition.

**Comment by abarth** [comment]
(1) is done.  Still working on (2).

**Comment by eseidelGoogle** [comment]
We no longer use the JIT in --release builds.  I think we can close this?

**Comment by ScottPierce** [comment]
>1. Teach the JIT how to optimize code on a background thread.
2. Teach the AOT compiler how to generate code that the JIT can later optimize by recompiling.

@eseidel Does that mean that the above mentioned plans for JIT are no longer used, as in the the JIT doesn't run at all in release builds, even in a background thread?

**Comment by eseidelGoogle** [comment]
So 1. and 2. both exist.  But we are not using the JIT at all in Release mode anymore, correct.  Both iOS and Android builds use AOT builds.  There exists an AOT + update-with-JIT-on-device technology in the DartVM which we could use, we investigated it briefly, but since it would be Android-only we decided it was simpler to just use plain-old AOT for both iOS and Android for now.
