### ISSUE TITLE
[google_sign_in_android] Migrate from Google Sign-In to Google Identity Services

### ISSUE THREAD

**Issue by camsim99** [flutter/flutter#102243]
The [`google_sign_android` plugin](https://github.com/flutter/plugins/blob/main/packages/google_sign_in/google_sign_in_android/android/src/main/java/io/flutter/plugins/googlesignin/GoogleSignInPlugin.java) currently uses the [gms.auth.api.signin](https://developers.google.com/android/reference/com/google/android/gms/auth/api/signin/package-summary) package. While this package is not being deprecated yet, Google suggests migrating to [gms.auth.api.identity](https://developers.google.com/android/reference/com/google/android/gms/auth/api/identity/package-summary) (see note at the top of [this page](https://developers.google.com/identity/sign-in/web/sign-in).) to enable One Tap sign-in and sign-up.

Original issue: #101004

**Comment by diver2** [comment]
Hi people. Thanks for all the work you do.
I'd like to point that new firebase projects starting today cannot use the old google sign in code that's right now in pub dev. New client IDs are forced to use the identity services way of signing in. Old client Ids can use it until march 2023.

See this:
https://developers.google.com/identity/sign-in/web/reference#error_codes
<img width="947" alt="image" src="https://user-images.githubusercontent.com/30389474/181477584-1ab2f3a4-76b9-4f9e-9159-39a8b861d1d3.png">

**Comment by arualana** [comment]
I am using [package google_sign_in](https://pub.dev/packages/google_sign_in) and [package google_sign_in_web](https://pub.dev/packages/google_sign_in_web).

I am following the exact example [here](https://github.com/flutter/plugins/blob/main/packages/google_sign_in/google_sign_in/example/lib/main.dart) and getting
`gapi.auth2.ExternallyVisibleError: gapi.auth2 has been initialized with different options. Consider calling gapi.auth2.getAuthInstance() instead of gapi.auth2.init().`

Is this error related to this issue?

Thank you

**Comment by jpiabrantes** [comment]
While this issue is not solved, how is everyone implementing signing in with google?

**Comment by PT10** [comment]
Isn't it a blocker now?

**Comment by diver2** [comment]
it is a blocker for new users to use google sign in for a long time, since July 29th.
I don't understand the google team not updating google sign in... I think I will remove this feature from my app, as it seems flutter is not supporting it anymore

**Comment by camsim99** [comment]
My understanding is that these are blockers for web and this has been addressed, as per https://github.com/flutter/flutter/issues/101004.

**Comment by BlueDev5** [comment]
I was looking for a plugin that uses the new GIS SDK. I found the `google_one_tap_sign_in` plugin, which seems to be using GIS, but I couldn't get it to work. So, if you can get it to work, we would have an alternative for implementing Google Sign-In.

**Comment by stuartmorgan** [comment]
Closing in favor of https://github.com/flutter/flutter/issues/154205 as Credential Manager is now the recommended replacement.
