### ISSUE TITLE
[impeller] impeller::DeviceBuffer::CopyHostBuffer must take fml::Mappings instead of raw pointers.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#102262]
This will allow the OpenGL ES backend to elide a copy. These APIs were devised in the early prototyping stage before the FML dependency was taken.

**Comment by chinmaygarde** [comment]
This is fixed for textures in https://github.com/flutter/engine/pull/33441. The same pattern needs to be applied to device buffers as well. This is lower priority since these are usually extremely small.

**Comment by jonahwilliams** [comment]
Based on how we use device buffers with the new host buffer arena, changing to use fml types would be counter productive.
