### ISSUE TITLE
m3 material not being elevated

### ISSUE THREAD

**Issue by cedvdb** [flutter/flutter#102296]
repro: https://github.com/cedvdb/flutter_repros/tree/m3_material_elevation 

The repro has to be run on a big screen because it has the same app running 12 times side by side with different Theme constructors. In the repro the elevated material at the bottom should be elevated but it is not in m3.

![Recording 2022-04-21 at 13 29 50](https://user-images.githubusercontent.com/22280985/164448874-7f7bfa8c-9429-4442-bae9-f685097820b1.gif)

**Comment by maheshmnj** [comment]
Hi @cedvdb, Thanks for filing the issue. I am not sure I understood the issue, Can you please clarify what exactly the issue is?

**Comment by cedvdb** [comment]
In the repro the elevated material at the bottom should be elevated but it is not on the apps running on the right. The shadows are not seen.

**Comment by maheshmnj** [comment]
I am sorry, I am still little confused, By `elevated material` are you referring to the `OverlayButton`? 

*Overlay Button without shadow Circled with red*

![image](https://user-images.githubusercontent.com/31410839/164473304-e7e77d41-b173-48ff-b7ea-9996ff0c124d.png)

**Comment by cedvdb** [comment]
Yes what is in the red circle is not elevated on the right (look at the shadows)

**Comment by TahaTesser** [comment]
Hi @cedvdb 

This is intended behavior when enabling `useMaterial3`


https://github.com/flutter/flutter/blob/0cbd6231e4e5411ac7c021cf685a1025ec507a17/packages/flutter/lib/src/material/material.dart#L255-L269

You can provide shadow color from the theme, Card widget now does the same thing https://github.com/flutter/flutter/blob/0cbd6231e4e5411ac7c021cf685a1025ec507a17/packages/flutter/lib/src/material/card.dart#L230 and it draws shadow when enabling `useMaterial3`


<details> 
<summary>minimal code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key, this.dark = false});

  final bool dark;

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Row(
        children: [
          Expanded(
            child: MaterialApp(
              debugShowCheckedModeBanner: false,
              themeMode: dark ? ThemeMode.dark : ThemeMode.light,
              theme: ThemeData(
                useMaterial3: false,
                brightness: Brightness.light,
                colorSchemeSeed: const Color(0xff6750a4),
              ),
              darkTheme: ThemeData(
                useMaterial3: false,
                brightness: Brightness.dark,
                colorSchemeSeed: const Color(0xff6750a4),
              ),
              home: Example(title: 'Material 2'),
            ),
          ),
          Expanded(
            child: MaterialApp(
              debugShowCheckedModeBanner: false,
              themeMode: dark ? ThemeMode.dark : ThemeMode.light,
              theme: ThemeData(
                useMaterial3: true,
                brightness: Brightness.light,
                colorSchemeSeed: const Color(0xff6750a4),
              ),
              darkTheme: ThemeData(
                useMaterial3: true,
                brightness: Brightness.dark,
                colorSchemeSeed: const Color(0xff6750a4),
              ),
              home: Example(title: 'Material 3'),
            ),
          ),
        ],
      ),
    );
  }
}

class Example extends StatelessWidget {
  Example({super.key, required this.title});

  String title;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.spaceEvenly,
          children: [
            const Card(
              child: Padding(
                padding: EdgeInsets.all(8.0),
                child: Text('Card'),
              ),
            ),
            OverlayButton(
              onTap: () {},
              child: const Text('Material'),
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () {},
        child: const Icon(Icons.add),
      ),
    );
  }
}

class OverlayButton extends StatelessWidget {
  final Function() onTap;
  final Widget child;

  const OverlayButton({
    Key? key,
    required this.onTap,
    required this.child,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Material(
      type: MaterialType.card,
      color: Theme.of(context).colorScheme.surface,
      elevation: 3,
      borderRadius: BorderRadius.circular(20),
      shadowColor: Theme.of(context).colorScheme.shadow,
      surfaceTintColor: Theme.of(context).colorScheme.surfaceTint,
      child: InkWell(
        onTap: onTap,
        borderRadius: BorderRadius.circular(20),
        child: Padding(
          padding: const EdgeInsets.symmetric(
            horizontal: 12,
            vertical: 8,
          ),
          child: DefaultTextStyle(
            style: TextStyle(color: Theme.of(context).colorScheme.onSurface),
            child: child,
          ),
        ),
      ),
    );
  }
}

``` 
	
</details>

**Comment by cedvdb** [comment]
Hey @TahaTesser Thanks for the detailed answer. As I understand it has to be done on a case by case basis now, instead of being done for you automatically.  I was under the wrong impression that when turning useM3 flag to true I'd have the same app with all the bells and whistles from m3. I was a bit taken aback by how our app looked like when I turned on this flag as I had high hopes. Now I understand that it needs some migration.

**Comment by TahaTesser** [comment]
@cedvdb 
Actually, M3 migration is also fixing  minor issues and some clean up, it is not just changing theme and colors.

- Here shadow color is transparent by default after migrating to M3.
- `ListTile` won't use [hard-coded color](https://github.com/flutter/flutter/blob/fde7622f7e0ab915ce19bd49a8ead5707141df6a/packages/flutter/lib/src/material/list_tile.dart#L628-L635) in the light mode for disabled icons after migrating to M3. 
See https://github.com/flutter/flutter/pull/102078


> The transition to M3 will introduce many small color changes; seems OK to include this one too. 
https://github.com/flutter/flutter/issues/99400#issuecomment-1075580629

cc: @HansMuller 
Perhaps there should be a migration guide for Material 3?

**Comment by cedvdb** [comment]
@TahaTesser FYI the context menu do not have shadows, in the Figma file furnished by material there are shadows for the menu. Maybe that's a mistake.
