### ISSUE TITLE
flutter pub get always exclude .dart_tool folder

### ISSUE THREAD

**Issue by EArminjon** [flutter/flutter#102246]
## Steps to Reproduce

When using flutter_localizations, dart_tool contain all translate variable, by exclude automatically this folder the benefice is f**k. Please do something.

1. Intelij / android studio
2. flutter pub get

## Logs

<details>
<summary>Logs</summary>

```
```

```
```

</details>

![image](https://user-images.githubusercontent.com/37028599/164292414-3f75cc4c-5538-447e-9f15-909fbf2ae8e8.png)

Console got no error, only in IDE
```
flutter analyze
Analyzing project...                                               
No issues found! (ran in 1.8s)
```

**Comment by stuartmorgan** [comment]
Please file issues related to `pub get` against `pub`; `flutter pub` is just a passthrough.

In the future, please include all requested information when filing issues. You haven't provided any actual steps, or a clear description of the problem.
