### ISSUE TITLE
[CP] Fix the CanvasPath::CreateNew signature to avoid unnecessary Dart API::NewError calls

### ISSUE THREAD

**Issue by jason-simmons** [flutter/flutter#102247]
### issue_link

https://github.com/flutter/engine/pull/32791

### Commit Hash

a9dafdb97913924acd421a7ef73f90c62a7499c6

### Target

beta

### Impacted Users

All Flutter apps

### Impact Description

The Flutter engine is doing unnecessary work every time a Flutter app constructs a Path object.  This is a regression affecting a frequently used operation (for example, in the default template counter app this happens 38 times each time you press the button)

### Workaround

No workaround

### Risk

low

### Test Coverage

yes

**Comment by zanderso** [comment]
@jason-simmons did SkiaPerf notice any benchmark improvements for this change?

**Comment by jason-simmons** [comment]
No - this is a low risk fix to a regression, but any performance impact on benchmarks is small and lost in the noise.
