### ISSUE TITLE
[Feature Request] Provide enabled to CheckboxListTile

### ISSUE THREAD

**Issue by mtc-jed** [flutter/flutter#102219]
## Use case
I want to disable a `CheckboxListTile`, like you'd do a `ListTile`.

## Proposal
Add an argument `CheckboxListTile.enabled`, which would be transmitted to `ListTile.enabled`.

**Comment by maheshmnj** [comment]
Hi @mtc-jed, Thanks for filing the issue. If you leave `CheckboxListTile.onChanged` as null, You should be able to disable the `CheckboxListTile` wouldn't that work? 

Consider the below code sample, if counter is even `CheckboxListTile` is disabled

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);
  final String title;
  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;
  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            CheckboxListTile(
              value: true,
              onChanged: _counter.isEven ? null : (x) {},
            ),
            ListTile(
              enabled: _counter.isEven,
              title: Text('Listtile test'),
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}

```
</details>

**Comment by mtc-jed** [comment]
@maheshmnj Yep that works, but the splash animation is still there, contrary to the behaviour on a ListTile. That's what I'd like to disable properly, so there is no confusion for the user.

**Comment by maheshmnj** [comment]
> but the splash animation is still there, contrary to the behaviour on a ListTile. That's what I'd like to disable properl

I don't see any splash animation when `CheckboxListTile.onChanged`.

However, this looks like a fair proposal.

**Comment by mtc-jed** [comment]
Ah, my bad, I saw that `CheckboxListTile.onChanged` has the `required` keyword, and I didn't see that it could actually be null.
This proposal should therefore be "Remove the `required` keyword from `CheckboxListTile.onChanged`", for clarity's sake. Or we try to stick to how `ListTile` works (where you can specify both a callback and `enabled`, which makes for cleaner code).
The two approches are commonly used in Flutter, so it's up to the team (I prefer having `enabled`, personally).
