### ISSUE TITLE
Allow hot reload to be triggered from Xcode console without "flutter attach"

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#102260]
This would be particularly useful for add-to-app.  

Maybe we could teach the engine to interpret `SIGUSR1` or `SIGUSR2` signals as hot reload, and document how to send that signal with lldb via `process signal SIGUSR1`?

**Comment by jonahwilliams** [comment]
How do you run the compiler without a flutter tool instance running somewhere?

**Comment by jmagman** [comment]
> How do you run the compiler without a flutter tool instance running somewhere?

You're right the sources to reload need to get there somehow.  This feature request doesn't make sense. 😛
