### ISSUE TITLE
[linux] Support Linux arm64

### ISSUE THREAD

**Issue by ydddx** [flutter/flutter#102271]
How to cross compile linux arm64 on linux 64?

**Comment by bernaferrari** [comment]
https://github.com/flutter/flutter/issues/60678#issuecomment-1021631389

**Comment by ydddx** [comment]
Hi @bernaferrari .
How to install flutter sdk on linux arm64?I want to compile linux arm64 app

**Comment by ydddx** [comment]
https://github.com/flutter/flutter/issues/102271#issuecomment-1104746509
I found that just replacing the dart sdk works

**Comment by bernaferrari** [comment]
You can install flutter on arm64, you just can't cross compile from x64 to arm64.

**Comment by ydddx** [comment]
not be sorry,i did want to cross compile at first

**Comment by bernaferrari** [comment]
I never tried, if it is fast, go for it..
