### ISSUE TITLE
Instructions for running on simulator/device is a bit hidden now

### ISSUE THREAD

**Issue by xster** [flutter/flutter#10224]
On the website, the instructions for running apps on simulator/devices are no longer trivially discoverable vs before. 

It's now inside the 'install' top level nav link and then behind one of the install steps. But looking for specific answers on deploying, I won't think of looking inside 'install' but I'm scanning for something like 'run' or some similarly named link. There is a 'Test your app' which is a bit confusing since that's talking about writing automated tests rather than put in on a phone and see how it runs. 

Can we expose them better somehow?

**Comment by Sfshaza** [comment]
As of beta 3, we now have a "Test drive" page. The section at the end says to select a device, but it doesn't specifically mention the simulator/emulator. The last sentence infers it.

Do you feel this is sufficient, @xster ?

**Comment by xster** [comment]
Is the test drive page meant for Android only? The terminal + editor tab just says 'Check that an Android device is running' which may be confusing.

**Comment by zoechi** [comment]
Issue moved to [flutter/website #2001](https://github.com/flutter/website/issues/2001) via [**ZenHub**](https://www.zenhub.com/)
