### ISSUE TITLE
Website layout on smaller screens

### ISSUE THREAD

**Issue by ThomasOrlita** [flutter/flutter#10229]
On smaller screens, the footer overflows:
![flutteriobug1](https://cloud.githubusercontent.com/assets/17808846/26274702/2cc13200-3d50-11e7-9763-6ba7e1f1d4a8.png)

And if there's some longer text in `<code>`, the page won't display correctly on smaller screens (because of `white-space: nowrap` in `<code>`).
For example [https://flutter.io/android-release/](https://flutter.io/android-release/)

**Comment by sethladd** [comment]
Merged in the fix :)

Thanks!
