### ISSUE TITLE
One widget covering the full screen (only on Android)

### ISSUE THREAD

**Issue by SwiftyFlow** [flutter/flutter#102201]
I have a screen with a map from mapbox_gl (the issue has been reported there too: https://github.com/flutter-mapbox-gl/maps/issues/1008#issue-1208406765)

In short the Scaffold appBar & FAB are recovered by the map if I put it in... Please follow https://github.com/flutter-mapbox-gl/maps/issues/1008#issue-1208406765 for screenshots.

Is it a Flutter bug or mapbox_gl?

Otherwise can send a widget back? Like I would on iOS with a view...

Happy to share more if need be.

**Comment by danagbemava-nc** [comment]
Hi @SwiftyFlow, based on your comment in https://github.com/flutter-mapbox-gl/maps/issues/1008#issuecomment-1103758417, it appears that this is an issue with `mapbox_gl` as such, I am going to close this issue. 

If it does turn out to be an issue with flutter kindly leave a comment with your `flutter doctor -v` and a complete minimal reproducible code sample. 

Closing this for now. 

Thank you

**Comment by SwiftyFlow** [comment]
Yep all good I actually found out that it was requiring .textureMode(true) in

```
private final MapboxMapOptions options = new MapboxMapOptions().textureMode(true).attributionEnabled(true);
```

This fixed it if it ever helps anyone...
