### ISSUE TITLE
EXC_BAD_ACCESS (code=1, address=0x7f944304fdb0) when launching screen with map on iOS

### ISSUE THREAD

**Issue by JulianGerman** [flutter/flutter#102356]
**Expected results:** 
Properly launched screen with map.

**Actual results:** 
App crashed (not always) when user want to launch page with google_maps. White screen instead of screen with map. 

Google_maps_flutter 2.1.3

Also in terminal there is an information : 
**New version of Google Maps SDK for iOS available: 6.1.1.0**

<details>
  <summary>Logs</summary>

EXC_BAD_ACCESS (code=1, address=0x7f944304fdb0)

```
```

```
```

```
[✓] Flutter (Channel stable, 2.10.5, on macOS 12.3.1 21E258 darwin-arm, locale pl-PL)
    • Flutter version 2.10.5 at /Users/julian/Dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (4 days ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/julian/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] VS Code (version 1.66.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.38.1

[✓] Connected device (3 available)
    • iPhone12 (mobile) • F7AD8B74-AD79-489C-87DD-977C0B16167C • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-15-4 (simulator)
    • macOS (desktop)   • macos                                • darwin-arm64   • macOS 12.3.1
      21E258 darwin-arm
    • Chrome (web)      • chrome                               • web-javascript • Google Chrome
      100.0.4896.127
    ! Error: iPhone (Julian) is not connected. Xcode will continue when iPhone (Julian) is
      connected. (code -13)

[✓] HTTP Host Availability
    • All required HTTP hosts are available

```

</details>

**Comment by danagbemava-nc** [comment]
Hi @JulianGerman, please provide a complete minimal reproducible code sample that we can use to verify this. 

Is this crash in debug/release mode?
What devices are experiencing the crash?
Please also provide the full crash log. 

Thank you

**Comment by JulianGerman** [comment]
Hi @danagbemava-nc , thank you for response. 
Crash is happening in both of modes. Lot's of iOS devices are experiencing the crash. I've tested on iPhone 12 simulator and it happened, also we've got some crashes on firebase crashlytics related probably for that one. Unfortunately I can't provide the full crash log, I've got only this : 
**EXC_BAD_ACCESS (code=1, address=0x7f944304fdb0)**.
I am trying to reproduce it now but unfortunately everything is working good :).
Also can you answer me what about this update of google SDK for flutter? Is it possible to do it manually without waiting for next google_maps_flutter update?

**Comment by JulianGerman** [comment]
I've changed the simulator and got this crash again. Maybe it's related to first opening of the map? 
`2022-04-22 11:18:52.667731+0200 Runner[50065:2614251] Google Maps SDK for iOS version: 5.2.0.0
2022-04-22 11:18:52.667855+0200 Runner[50065:2614251] New version of Google Maps SDK for iOS available: 6.1.1.0
2022-04-22 11:18:52.668232+0200 Runner[50065:2618240] [Client] Synchronous remote object proxy returned error: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated: failed at lookup with error 3 - No such process." UserInfo={NSDebugDescription=The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated: failed at lookup with error 3 - No such process.}
2022-04-22 11:18:52.668269+0200 Runner[50065:2618239] [Client] Updating selectors failed with: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated: failed at lookup with error 3 - No such process." UserInfo={NSDebugDescription=The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated: failed at lookup with error 3 - No such process.}
2022-04-22 11:18:53.144848+0200 Runner[50065:2618982] [boringssl] boringssl_metrics_log_metric_block_invoke(153) Failed to log metrics
2022-04-22 11:18:53.798984+0200 Runner[50065:2618240] [boringssl] boringssl_metrics_log_metric_block_invoke(153) Failed to log metrics
(lldb) `

Got here the latest console output.

**Comment by danagbemava-nc** [comment]
> Also can you answer me what about this update of google SDK for flutter? Is it possible to do it manually without waiting for next google_maps_flutter update?

You can do it yourself by forking the repo and make the changes there

Hi @JulianGerman, can you provide the output of `flutter doctor -v` that shows the full error that you're experiencing? Also, please provide a complete minimal reproducible code sample so that we may verify this. 

Thank you

**Comment by JulianGerman** [comment]
> > Also can you answer me what about this update of google SDK for flutter? Is it possible to do it manually without waiting for next google_maps_flutter update?
> 
> You can do it yourself by forking the repo and make the changes there
> 
Can you explain me in details how can i do it? Tried lots of things, and still got the warning.
![Zrzut ekranu 2022-04-25 o 13 30 19](https://user-images.githubusercontent.com/44871866/165080580-14e79468-030c-42a5-9861-8e5710c8c2e3.png)

**Comment by danagbemava-nc** [comment]
Hi @JulianGerman, rather than you manually messing with the plugin code, I would prefer you leave it to the plugin team to work on this if you don't have much experience with it yourself. The code should work just fine with or without the update. 

Please provide the code sample that you are experiencing this issue with so that we can investigate this. Please also provide the content of your `Info.plist` file. 

Thank you

**Comment by danagbemava-nc** [comment]
Hi @vicleonov, could you please file a new issue and provide all the relevant information necessary to reproduce it? All setups are different so similar issues may not be similar upon further investigation

**Comment by ggirotto** [comment]
Very frustrating to face the exactly same issue but not being able to create a reproducible sample. It seems to be happening randomly in iOS simulator. Sometimes it happens, sometime it doesn't.
