### ISSUE TITLE
Flutter Windows - TextField inside of ListTile

### ISSUE THREAD

**Issue by bar4488** [flutter/flutter#102391]
while placing a `TextField` as the title of  `ListTile`, and trying to type in the `TextField` `enter` and `space` key events are forwarded into `ListTile` as a tap instead of the `TextField`.

undesired behavior:
1. `on*` event on the `TextField` are not called, the onTap of the `ListTile` is called
2. the ListTile is in focused. 
3. even when ListTile onTap is null, or it is disabled, pressing enter and space will trigger a material splash

the desired effect is that the text field will behave as usual and the ListTile will not be focused.
in addition, it would be nice if the user will be in control of what keys are navigated where, and will be able to act accordingly.

![image](https://user-images.githubusercontent.com/36762719/164770341-04bd8153-a0c9-443f-b9c1-4d468be0b1a0.png)

**Comment by darshankawar** [comment]
> trying to type in the `TextField` `enter` and `space` key events are forwarded into `ListTile` as a tap instead of the `TextField`.

Does that mean, you are unable to input anything in the textifled which is inside ListTile ? What behavior are you seeing after inputing a text and then pressing `enter` or `space` ?

@bar4488 
I tried below code sample based on your description and tried it on macOS desktop and observed that pressing `return` or `enter` moves the focus away from TextField, but was able to press space in the textfield properly as below:

<img width="386" alt="Screenshot 2022-04-25 at 11 58 08 AM" src="https://user-images.githubusercontent.com/67046386/165032538-dfa6dc3e-d656-4090-a1ef-867e2ffacd8c.png">


<details>
<summary> runnable code sample </summary>

```

import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}


class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);
  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {


  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: const Center(
        child: ListTile(
          title: TextField(

          ),
        ),
      ),
    );
  }
}

```

</details>

Can you try using above code sample and see if you get same behavior as reported ? If not, can you provide updated code sample that shows the issue ?

**Comment by bar4488** [comment]
> Can you try using above code sample and see if you get same behavior as reported ? If not, can you provide updated code sample that shows the issue ?

running the above code sample on windows 10, typing space makes a splash effect on the list tile as if the list tile was tappable and I've pressed it, and does not input space into the TextField, but the focus stays on the TextField. the exact same behavior when pressing enter:
![image](https://user-images.githubusercontent.com/36762719/165037153-b47b66b1-cb86-48cc-b6de-c3472650f5a1.png)

copying in text with spaces works properly.

**Comment by darshankawar** [comment]
@bar4488 
A similar issue was recently fixed and should be available on latest master https://github.com/flutter/flutter/pull/98469
Can you switch to latest master and try again to see if issue still persists or not ?

`flutter channel master`
`flutter upgrade`
