### ISSUE TITLE
How to prevent  some dart class name  from  obfuscating when i use flutter build apk --obfuscate?

### ISSUE THREAD

**Issue by cj3479** [flutter/flutter#102302]

**Comment by FusoraTech** [comment]
Marking a Class or Member as an entry point should make it to survive stripping/obfuscation.
https://github.com/dart-lang/sdk/blob/master/runtime/docs/compiler/aot/entry_point_pragma.md

**Comment by maheshmnj** [comment]
Hi @cj3479, Thanks for filing the issue. Can you please check if the above link helps prevent obfuscating a particular dart class?

**Comment by cj3479** [comment]
> Hi @cj3479, Thanks for filing the issue. Can you please check if the above link helps prevent obfuscating a particular dart class?

Yes it works fine

**Comment by maheshmnj** [comment]
Thanks for the confirmation, 

> Yes it works fine

Closing based on the above response.
