### ISSUE TITLE
Recipes roll is failing with `automated roll attempt is stale`

### ISSUE THREAD

**Issue by akbiggs** [flutter/flutter#102383]
Console: https://ci.chromium.org/p/flutter/g/recipes/console
Sample failure: https://ci.chromium.org/ui/p/flutter/builders/prod/recipe-deps-roller/b8816235419177526897/overview

**Comment by keyonghan** [comment]
Last auto roll was stuck on tests timing out. 
Manual roll: https://flutter-review.googlesource.com/c/recipes/+/29283

**Comment by keyonghan** [comment]
Manual roll merged.

**Comment by akbiggs** [comment]
@keyonghan It looks like the recipes roll is still red: https://ci.chromium.org/p/flutter/g/recipes/console is this expected?

**Comment by keyonghan** [comment]
Blocker: https://flutter-review.googlesource.com/c/recipes/+/29461

**Comment by keyonghan** [comment]
@yusuf-goog Do you mind take a look at the blocker CL above? https://flutter-review.googlesource.com/c/recipes/+/29461

**Comment by yusuf-goog** [comment]
Fixing downstream issue with luci-config builder in: https://flutter-review.googlesource.com/c/infra/+/29540

**Comment by yusuf-goog** [comment]
@keyonghan do we need a different manual roll after the applied fixes?

I tried this roll https://flutter-review.googlesource.com/c/recipes/+/29560

**Comment by keyonghan** [comment]
See go/flutter-luci-recipes#manual-roll. Please try finding an available auto roll, or kick off a manual roll by updating the deps to the latest.

**Comment by yusuf-goog** [comment]
Created roll: https://flutter-review.googlesource.com/c/recipes/+/29600

**Comment by yusuf-goog** [comment]
@keyonghan its still failing: https://ci.chromium.org/p/flutter/g/recipes/console after the roll: https://flutter-review.googlesource.com/c/recipes/+/29600 any ideas?

**Comment by keyonghan** [comment]
The error message shows `manual intervention needed: automated roll attempt is stale`. Could you help take a look at https://source.chromium.org/chromium/infra/infra/+/main:recipes/recipe_modules/recipe_autoroller/api.py;l=215?q=roll_projects to see if any findings?

**Comment by keyonghan** [comment]
Seems we need to abandon earlier failed non-trivial roll CL to unblock.
@godofredoc could you help abandon: https://flutter-review.googlesource.com/c/recipes/+/28982?

**Comment by godofredoc** [comment]
Done!

**Comment by yusuf-goog** [comment]
This is back to green: https://ci.chromium.org/p/flutter/g/recipes/console
