### ISSUE TITLE
Can't reach out https://docs.flutter.dev/

### ISSUE THREAD

**Issue by EvaNizhni** [flutter/flutter#102373]
Good day, 

When I trying to reach out https://docs.flutter.dev/ I have got err_connection_refused
![telegram-cloud-photo-size-2-5406861954896739235-y](https://user-images.githubusercontent.com/48185933/164713381-04c43c9a-2d91-4cda-b7c5-ac8857ff2dd1.jpg)
In the same time I am able to open https://flutter.dev/
Chrome version: Version 100.0.4896.75 (Official Build) (x86_64). MacOS

**Comment by darshankawar** [comment]
@EvaNizhni 
I am on similar chrome version `Google Chrome 100.0.4896.127` but don't see the issue as I am able to see the link properly. 

<img width="646" alt="Screenshot 2022-04-22 at 6 28 03 PM" src="https://user-images.githubusercontent.com/67046386/164718872-48bf65d9-caa6-41e5-815d-4fb195b95905.png">

Check if any of the solutions mentioned [here](https://stackoverflow.com/questions/55375467/cant-access-flutter-dev-mac-os) helps to resolve.

**Comment by EvaNizhni** [comment]
I discussed also with my internet provider this problem. It seems, that there are few providers in my city, which can't reach this link.

**Comment by darshankawar** [comment]
Closing this as network related issue and not Flutter.
