### ISSUE TITLE
Event unfocus doesn’t appear on FocusNode

### ISSUE THREAD

**Issue by kwiatek91** [flutter/flutter#102367]
Condition:
Focus is in the FocusNode widget, and we've added a listener to FocusNode:

Test on Desktop device
When we use mouse to click on switch button there will be called event unfocus 
 
Test on mobile device (touch screen)
When we touch switch button there is no event unfocus

We test latest Flutter version.

**Comment by darshankawar** [comment]
@kwiatek91 
Can you provide `flutter doctor -v` and a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that shows the behavior ?
Also when you say mobile device, does it occur on Android or iOS ?

**Comment by hikachi** [comment]
<details>
<summary> flutter doctor -v </summary>


[√] Flutter (Channel master, 2.13.0-0.0.pre.712, on Microsoft Windows [Version 10.0.19043.1586], locale pl-PL)
    • Flutter version 2.13.0-0.0.pre.712 at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 8c22f5648a (35 minutes ago), 2022-04-25 05:34:07 -0400
    • Engine revision 10efa195bf
    • Dart version 2.18.0 (build 2.18.0-44.0.dev)
    • DevTools version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at C:\Users\mucin\AppData\Local\Android\sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.10)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.32126.315
    • Windows 10 SDK version 10.0.22000.0

[√] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] IntelliJ IDEA Community Edition (version 2021.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.3.2
    • Flutter plugin version 66.0.3
    • Dart plugin version 213.7306

[√] VS Code, 64-bit edition (version 1.64.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (5 available)
    • sdk gphone x86 (mobile) • emulator-5556 • android-x86     • Android 11 (API 30) (emulator)
    • Windows (desktop)       • windows       • windows-x64     • Microsoft Windows [Version 10.0.19043.1586]
    • Windows (UWP) (desktop) • winuwp        • windows-uwp-x64 • 
    • Chrome (web)            • chrome        • web-javascript  • Google Chrome 100.0.4896.127
    • Edge (web)              • edge          • web-javascript  • Microsoft Edge 99.0.1150.55

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!


</details>

<details>
  <summary>Minimal code</summary>

```
import 'package:flutter/material.dart';
void main() {
  runApp(const MyApp());
}
class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        title: 'Flutter Demo',
        theme: ThemeData(
          primarySwatch: Colors.blue,
        ),
        home: MyHomePage());
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {

  @override
  Widget build(BuildContext context) {
    return Material(
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: <Widget>[TextFormField(), Checkbox(value: false, onChanged: (_) {})],
      ),
    );
  }
}
```


</details>

![windows](https://user-images.githubusercontent.com/36861253/165068730-1892988a-c118-446d-a504-7f1070ad3ac8.gif)
mouse click on checkbox -windows - textfield is unfocused

![android](https://user-images.githubusercontent.com/36861253/165068733-649f6920-c7e6-45a1-aa18-8081a18240b6.gif)

tap on checkbox -android - textfield is still remaining focused

**Comment by kwiatek91** [comment]
> @kwiatek91 Can you provide `flutter doctor -v` and a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that shows the behavior ? Also when you say mobile device, does it occur on Android or iOS ?

Here is an answer from my coworker for your question
https://github.com/flutter/flutter/issues/102367#issuecomment-1108379911

**Comment by darshankawar** [comment]
I believe this is similar to https://github.com/flutter/flutter/issues/98199, so please follow-up in it for further updates.
Closing this as duplicate.
