### ISSUE TITLE
move icon(custom icon font) in Buttons flutter when on pressed

### ISSUE THREAD

**Issue by conall1995** [flutter/flutter#102381]
i have problem with only custom font icon in flutter (font icon created by https://www.fluttericon.com/)

so when i used icon in buttons and press button (in android) and hover (in web(desktop)) my icon moved to top !

![Screen Shot 2022-04-22 at 7 46 25 PM](https://user-images.githubusercontent.com/28934905/164749678-67caf058-c1bd-43fe-974e-ecb1d9083a4b.png)

right button>> button on pressed left button >> normal

when change icon to standard flutter icons like Icons.calendar_today its fixed !

code:
` ElevatedButton(
                                  onPressed: () => null,
                                  child: Row(
                                    children: const [
                                      Text("example"),
                                      SizedBox(
                                        width: 8,
                                      ),
                                      Icon(MyIcon.calendar_1)
                                    ],
                                  ))`
                                  
                                  
font icon file :

[MyFlutterApp.ttf.zip](https://github.com/flutter/flutter/files/8542309/MyFlutterApp.ttf.zip)

dart file icons :

[my_flutter_app_icons.dart.zip](https://github.com/flutter/flutter/files/8542316/my_flutter_app_icons.dart.zip)

video:

https://user-images.githubusercontent.com/28934905/164750815-7e28c586-1dfc-4646-8937-87e353dbf28d.mov

--------------------------
flutter doctor -v :
`[✓] Flutter (Channel stable, 2.10.3, on Mac OS X 10.15.7 19H1715 darwin-x64, locale en-IR)
    • Flutter version 2.10.3 at /Volumes/HDD/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (7 weeks ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/conall/Library/Android/sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code (version 1.64.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] VS Code (version 1.63.2)
    • VS Code at /Volumes/HDD/Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 100.0.4896.127

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
`

**Comment by darshankawar** [comment]
@conall1995 
Since the framework icons don't show the behavior as you reported, I think this could be related to the way custom icon are generated from the link you shared which is not directly related to the framework and is third party. 

If you want to use icons, try this link : https://fonts.google.com/icons and see using from there still gives you same behavior or not.
Closing for now, as this doesn't seem to be framework issue.
