### ISSUE TITLE
`flutter test` can take more than a minute to execute a single test

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#102393]
## reproduction steps
```
cd $FLUTTER/packages/flutter
flutter test --name "Floating action button directionality"
```

## expected result
The test should take less than a minute to execute one test.

## seen results
The test takes well over a minute and appears to be spending a lot of time "loading" tests that I'm not executing.

`dart:frontend_server.dart.snapshot` and `dart:flutter_tools.snapshot` are taking up a large portion of my CPU.

## example output
```
aaclarke-macbookpro2:flutter aaclarke$ flutter test --name "Floating action button directionality"
01:09 +0: loading /Users/aaclarke/dev/flutter/packages/flutter/test/material/button_bar_theme_test.dart                       
```

## doctor
```
[✓] Flutter (Channel unknown, 2.13.0-0.0.pre.537, on macOS 12.3.1 21E258 darwin-x64, locale en-US)
    • Flutter version 2.13.0-0.0.pre.537 at /Users/aaclarke/dev/flutter
    • Upstream repository unknown
    • Framework revision fd5356ff60 (9 days ago), 2022-04-13 12:09:11 -0700
    • Engine revision f6e7fd521c
    • Dart version 2.18.0 (build 2.18.0-18.0.dev)
    • DevTools version 2.12.2
```

**Comment by jonahwilliams** [comment]
Running by name has the unfortunate side effect that all tests must be invoked (which of course means they must be compiled) so that the test file containing said test can be located. if you narrow it down by giving it a single test file it should be much faster. i.e. flutter test -name foo path/to/test.dart

**Comment by darshankawar** [comment]
@gaaclarke Hi, Please try by passing single test file as suggested to see tests running faster.

**Comment by gaaclarke** [comment]
@darshankawar, supplying the test file cuts down execution time.  I consider that a workaround and the bug is still a bug, albeit a lower priority bug since there is a workaround.

**Comment by darshankawar** [comment]
@gaaclarke Thanks for the feedback. Labeling it for further tracking.

**Comment by christopherfujino** [comment]
> @darshankawar, supplying the test file cuts down execution time. I consider that a workaround and the bug is still a bug, albeit a lower priority bug since there is a workaround.

@gaaclarke Note, you have to actually execute a file to resolve the full test name (which concatenates any surrounding group names with the final `test()` invocation).

I suppose you could try to compile them one by one and stop once you found it, which on average would mean compiling half of them; though I'm not sure if this method would take half the time.

**Comment by jonahwilliams** [comment]
> I suppose you could try to compile them one by one and stop once you found it, which on average would mean compiling half of them; though I'm not sure if this method would take half the time.

Actually, you can have multiple tests with the same name, so you'd still need to compile all files

**Comment by christopherfujino** [comment]
> > I suppose you could try to compile them one by one and stop once you found it, which on average would mean compiling half of them; though I'm not sure if this method would take half the time.
> 
> Actually, you can have multiple tests with the same name, so you'd still need to compile all files

Ohh yeah, I got bit by this!

**Comment by christopherfujino** [comment]
I'm closing this as this behavior is implemented upstream in package:test https://github.com/dart-lang/test/issues
