### ISSUE TITLE
Add typed_data flavors of drawAtlas and drawVertices

### ISSUE THREAD

**Issue by jhirth** [flutter/flutter#10233]
Currently, these methods take things like lists of offsets, colors, or integers. However, these values aren't used as is; they are converted to Float32Lists etc before they are handed to Skia.

Recreating those lists and refilling them with each call adds some overhead which you might want to avoid in some scenarios like games.

#10087 is same thing for drawPoints.

**Comment by sethladd** [comment]
Thanks for the suggestion!
