### ISSUE TITLE
CodeLabs Write your first Flutter App part 4

### ISSUE THREAD

**Issue by AngeMauriciolAntolin** [flutter/flutter#102324]
## Steps to Reproduce

```dart
import 'package:flutter/material.dart';
import 'package:english_words/english_words.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    final wordPair = WordPair.random(); 
    return MaterialApp(
      title: 'Welcome to Flutter',
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Welcome to Flutter'),
        ),
        body: const Center(
			child: Text(wordPair.asPascalCase),
        ),
      ),
    );
  }
}
```

**Expected results:** 
    in Chrome browser an English Word
```
$ flutter run -d chrome
Launching lib\main.dart on Chrome in debug mode...
Waiting for connection from debug service on Chrome...
lib/main.dart:21:16: Error: Not a constant expression.
                        child: Text(wordPair.asPascalCase),
                                    ^^^^^^^^
Waiting for connection from debug service on Chrome...             26,1s
Failed to compile application.
```

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by maheshmnj** [comment]
Hi @AngeMauriciolAntolin, Thanks for filing the issue. The issue in your code is you are using `const` for `Center` removing that should help fix the issue. However, looking at the code lab https://codelabs.developers.google.com/codelabs/first-flutter-app-pt1#4 The code seems correct to me.

**Comment by gregtzar** [comment]
I was getting the same error during [Part 3](https://codelabs.developers.google.com/codelabs/first-flutter-app-pt1#3), and it looked to me like a problem with `wordPair`, because after removing `const` from the `Body` declaration I was still getting a (more verbose) error about `wordPair`:

```
lib/main.dart:20:23: Error: The getter 'wordPair' isn't defined for the class 'MyApp'.
 - 'MyApp' is from 'package:startup_namer/main.dart' ('lib/main.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'wordPair'.
          child: Text(wordPair.asPascalCase),
```

The real issue was that I was missing this line: `final wordPair = WordPair.random();`. Revisiting this now I simiply didn't pick up on the use of the pink comment lines which denoted each change.
