### ISSUE TITLE
flutter ios error after adding shared_preferences

### ISSUE THREAD

**Issue by devnoaman** [flutter/flutter#102398]
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. ...  i've added shared_preferences
4. ...  pod install

**Expected results:** 
app running on ios

**Actual results:** 

                              Showing Recent Messages
                              ../../.pub-cache/hosted/pub.dartlang.org/path_provider_windows-2.0.5/lib/src/folders.dart:122:32: Error: Undefined name 'FOLDERID_logHood'.
                              
                                static String get logHood => FOLDERID_logHood;

                               ^^^^^^^^^^^^^^^^
                              
                              ../../.pub-cache/hosted/pub.dartlang.org/path_provider_windows-2.0.5/lib/src/folders.dart:125:37: Error: Undefined name 'FOLDERID_logersFolder'.
                              
                                static String get logersFolder => FOLDERID_logersFolder;
                              
                                                                  ^^^^^^^^^^^^^^^^^^^^^

                          Failed to package /Users/noamanmonther/MyDevProjects/csuot.

**Comment by devnoaman** [comment]
i've tried to add local_store and get the same error , i think the error comes from path provider

**Comment by devnoaman** [comment]
`
 Error: Undefined name 'FOLDERID_logHood'.
../…/src/folders.dart:122
  static String get logHood => FOLDERID_logHood;
                               ^^^^^^^^^^^^^^^^
: Error: Undefined name 'FOLDERID_logersFolder'.
../…/src/folders.dart:125
  static String get logersFolder => FOLDERID_logersFolder;
                                    ^^^^^^^^^^^^^^^^^^^^^
: Error: Undefined name 'FOLDERID_logHood'.
../…/src/folders.dart:122
  static String get logHood => FOLDERID_logHood;
                               ^^^^^^^^^^^^^^^^
: Error: Undefined name 'FOLDERID_logersFolder'.
../…/src/folders.dart:125
  static String get logersFolder => FOLDERID_logersFolder;
`

**Comment by stuartmorgan** [comment]
There are no such lines in `path_provider`:

https://github.com/flutter/plugins/blob/main/packages/path_provider/path_provider_windows/lib/src/folders.dart#L119-L125

You appear to have run a find/replace over your pub cache changing `Print` to `log`.

Changing files directly in your pub cache is, in general, a very bad idea. If you choose to do it, it's up to you to ensure that the result compiles.

**Comment by devnoaman** [comment]
@stuartmorgan how do i solve this
