### ISSUE TITLE
[Test] find.byType cannot find super type

### ISSUE THREAD

**Issue by cedvdb** [flutter/flutter#102335]
repro: 

https://github.com/cedvdb/flutter_repros/tree/finder_super_type

run flutter test

Use case:

In responsive design it's not always the same widget that is shown and you don't always know the key in advance easily especially in integration tests.

This is the widget finder:

```dart
class _WidgetTypeFinder extends MatchFinder {
  _WidgetTypeFinder(this.widgetType, { super.skipOffstage });

  final Type widgetType;

  @override
  String get description => 'type "$widgetType"';

  @override
  bool matches(Element candidate) {
    return candidate.widget.runtimeType == widgetType;
  }
}
```

currently the runtime type is checked, instead `is` should be used. 

I know there is find  by predicate.

**Comment by darshankawar** [comment]
> ```dart
> return candidate.widget.runtimeType == widgetType;
> ```

Are you saying that instead `return candidate.widget is widgetType;` should be used ? If so, we cannot use a Type object like this in an `is` expression.

May be you can try something like below and see if it suits your need:

`Type typeOf<T>() => T;` and then `find.byType(typeOf<WidgetName<t>>());`

**Comment by cedvdb** [comment]
I'm saying it would be more correct to have `find.byType<T>()`. I'm using `find.byPredicate is X`.

**Comment by darshankawar** [comment]
Thanks for the update. I am treating this as a proposal.

**Comment by goderbauer** [comment]
I believe this is already implemented: https://master-api.flutter.dev/flutter/flutter_test/CommonFinders/bySubtype.html?

**Comment by cedvdb** [comment]
Looks like it. I find the finder name `byType` a bit misleading but I guess this is a story for another day
