### ISSUE TITLE
Compile ‘samples/tree/master/add_to_app/multiple_flutters’ multi engine demo in release mode of IOS device error

### ISSUE THREAD

**Issue by yanwei49** [flutter/flutter#102474]
I downloaded this demo in https://github.com/flutter/samples/tree/master/add_to_app/multiple_flutters, and compiled it in the release mode of IOS real machine, and the result reported an error: nosuchmethoderror: no top-level getter 'bottommain' declared

Receiver: top-level，Tried calling: bottomMain, stack trace: #0 NoSuchMethodError._ Thrownew (dart:core-patch/errors_patch.dart:222) multiplefluttersios[4219:2013305] [verbose-2:dart_isolate.cc (681)] could not resolve main entry point function Could not run the run main Dart entrypoint. Could not create root isolate. Could not launch engine with configuration.

It is normal in debug mode.
My fluent -- version:
Flutter 2.10.6-0.0.pre.9 • channel stable • https://github.com/flutter/flutter.git
Framework • revision db1bda399e (83 minutes ago) • 2022-04-24 19:24:50 +0800
Engine • revision 57d3bac3dd
Tools • Dart 2.16.2 • DevTools 2.9.2

My iphone info: iPhone 7 , systom: iOS14.0

**Comment by yanwei49** [comment]
Flutter 2.13.0-0.0.pre.708 • channel master •
https://github.com/flutter/flutter.git
Framework • revision 2a9aa79843 (5 hours ago) • 2022-04-24 16:29:06 -0400
Engine • revision e31251e55f
Tools • Dart 2.18.0 (build 2.18.0-44.0.dev) • DevTools 2.12.2

In the official demo, I upgrade to the master branch, which is normal in the release mode

**Comment by SamTienz** [comment]
same issue with Flutter (Channel stable, 2.10.5, on macOS 12.3 21E230 darwin-arm, locale zh-Hant-TW)

plz help.

**Comment by darshankawar** [comment]
@yanwei49 
I tried the same sample add_to_app example using latest master version and ran it on iOS device (iPhone 6s, OS 15.3.1) which compiled and built properly without any issues.


Did you try following:

```
add_to_app % cd multiple_flutters
cd multiple_flutters_module
flutter pub get
cd multiple_flutters_ios
pod install
open MultipleFluttersIos.xcworkspace
```


How are you running the app in release mode ? Through Xcode ?

**Comment by yanwei49** [comment]
Yes, I did the above
Set release mode: Edit Scheme --> Run --> Info --> Build Configuration --> Select Release

**Comment by yanwei49** [comment]
> @yanwei49 我使用最新的主版本尝试了相同的示例 add_to_app 示例，并在 iOS 设备（iPhone 6s、OS 15.3.1）上运行，该设备正确编译和构建，没有任何问题。
> 
> 您是否尝试过以下操作：
> 
> ```
> add_to_app % cd multiple_flutters
> cd multiple_flutters_module
> flutter pub get
> cd multiple_flutters_ios
> pod install
> open MultipleFluttersIos.xcworkspace
> ```
> 
> 你是如何在发布模式下运行应用程序的？通过 Xcode ？

Xcode defaults to debug mode, debug mode is normal

**Comment by darshankawar** [comment]
@yanwei49 
Yes, I tried that and it is giving me below error which isn't the same as the one you reported:

`ld: '/Users/dhs/Library/Developer/Xcode/DerivedData/MultipleFluttersIos-araagjsfcmtuunbnysnsrxoupaov/Build/Products/Release-iphoneos/App.framework/App' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file '/Users/dhs/Library/Developer/Xcode/DerivedData/MultipleFluttersIos-araagjsfcmtuunbnysnsrxoupaov/Build/Products/Release-iphoneos/App.framework/App' for architecture arm64`

for which the original issue for tracking is: https://github.com/flutter/flutter/issues/29546

> Receiver: top-level，Tried calling: bottomMain, stack trace: #0 NoSuchMethodError._ Thrownew (dart:core-patch/errors_patch.dart:222) multiplefluttersios[4219:2013305] [verbose-2:dart_isolate.cc (681)] could not resolve main entry point function Could not run the run main Dart entrypoint. Could not create root isolate. Could not launch engine with configuration.

This looks similar to https://github.com/flutter/flutter/issues/91841 which should be fixed on latest master and doesn't seem to be available on stable yet.



> n the official demo, I upgrade to the master branch, which is normal in the release mode

Does that mean this is no longer an issue at your end and can be close ?

**Comment by yanwei49** [comment]
Yes, it can be closed

**Comment by yanwei49** [comment]
> @yanwei49 Yes, I tried that and it is giving me below error which isn't the same as the one you reported:
> 
> `ld: '/Users/dhs/Library/Developer/Xcode/DerivedData/MultipleFluttersIos-araagjsfcmtuunbnysnsrxoupaov/Build/Products/Release-iphoneos/App.framework/App' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file '/Users/dhs/Library/Developer/Xcode/DerivedData/MultipleFluttersIos-araagjsfcmtuunbnysnsrxoupaov/Build/Products/Release-iphoneos/App.framework/App' for architecture arm64`
> 
> for which the original issue for tracking is: #29546
> 
> > Receiver: top-level，Tried calling: bottomMain, stack trace: #0 NoSuchMethodError._ Thrownew (dart:core-patch/errors_patch.dart:222) multiplefluttersios[4219:2013305] [verbose-2:dart_isolate.cc (681)] could not resolve main entry point function Could not run the run main Dart entrypoint. Could not create root isolate. Could not launch engine with configuration.
> 
> This looks similar to #91841 which should be fixed on latest master and doesn't seem to be available on stable yet.
> 
> > n the official demo, I upgrade to the master branch, which is normal in the release mode
> 
> Does that mean this is no longer an issue at your end and can be close ?

Yes, it can be closed

**Comment by darshankawar** [comment]
Closing based on above comment.
