### ISSUE TITLE
Questions about web fonts

### ISSUE THREAD

**Issue by longgong** [flutter/flutter#102464]
![image](https://user-images.githubusercontent.com/5051456/164976069-5738eea2-d95f-40ae-9bb1-98ca367079a3.png)
Can this URL(https://fonts.gstatic.com/s/roboto/v20/KFOmCnqEu92Fr1Me5WZLCzYlKw.ttf) be loaded from a local service when build web?

**Comment by darshankawar** [comment]
@longgong 
If you are looking to load fonts, can you try using https://api.flutter.dev/flutter/services/FontLoader-class.html and see if it serves your purpose ?

**Comment by mrbech** [comment]
@longgong 
If you want to use a local version of the font my comment https://github.com/flutter/flutter/issues/77580#issuecomment-1112333700 might help.
