### ISSUE TITLE
Large icon buttons shift positions for no reason

### ISSUE THREAD

**Issue by bramvbilsen** [flutter/flutter#10240]
I'm trying to make a large icon button (size 60.0) centered on the screen. My code looks like this
![capture](https://cloud.githubusercontent.com/assets/16825392/26285911/1daf8956-3e59-11e7-82cb-07e75485962e.PNG)
For some reason, the position of the icon gets shifted a bit with large sizes while the material animation remains in the correct position. Take a look here:
![hjny1l7nos](https://cloud.githubusercontent.com/assets/16825392/26285916/3b6c7864-3e59-11e7-9aba-fd76d76a308c.gif)
Anyone with the same problem or even better, with a solution? 😄

**Comment by Hixie** [comment]
See the final paragraph of the documentation for Icon.size:
https://docs.flutter.io/flutter/material/Icon/size.html
