### ISSUE TITLE
Is there any other way to fix Flutter web can't login to Google and log out?

### ISSUE THREAD

**Issue by mycar98765** [flutter/flutter#102454]
I have the same problem as [Dinesh2703](https://github.com/Dinesh2703). I refer to [this answer](https://github.com/flutter/flutter/issues/48392#issuecomment-572824148). I tried [this](https://github.com/flutter/plugins/blob/master/packages/google_sign_in/google_sign_in_web/README.md#web-integration) 
 way and it worked. But when I change the code, Flutter web doesn't change. I have to quit Flutter web and run it again. Is there any other way to fix Flutter web can't login to Google and log out? I would appreciate any help.

**Comment by maheshmnj** [comment]
Hi @mycar98765, Thanks for filing the issue. Please update the issue description which clearly describes the problem that you are facing along with the output of `flutter doctor -v`. This will help us to triage the issue better.

**Comment by mycar98765** [comment]
Here is the output of `flutter doctor -v`:
```
[✓] Flutter (Channel stable, 2.10.1, on macOS 12.3.1 21E258 darwin-x64, locale en-MY)
    • Flutter version 2.10.1 at /Users/lee/development/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db747aa133 (3 months ago), 2022-02-09 13:57:35 -0600
    • Engine revision ab46186b24
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/lee/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.66.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.38.1

[✓] Connected device (2 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 100.0.4896.127

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

**Comment by mycar98765** [comment]
> Hi @mycar98765, Thanks for filing the issue. Please update the issue description with a clear description of the problem, along with the output of `flutter doctor -v`. This will help us to triage the issue better.

@maheshmnj I commented the output of `flutter doctor -v`.

**Comment by maheshmnj** [comment]
Thanks for the info @mycar98765, However, I am not sure what this issue is reporting. You did mention the solutions you have tried, But not the issues that you are facing.  Could you please clarify the issue?

**Comment by mycar98765** [comment]
@maheshmnj, Flutter web doesn't change when I change the code. I have to quit Flutter web and run it again.

**Comment by maheshmnj** [comment]
Thanks for the clarification, If I understand it right hot restart is not working for you on the web. Can you please confirm if this is happening in a specific project or a newly created project too? if the former please share the exact step to reproduce the issue (Indicating the code sample you had and the changes you made, where the app was not rebuilt)

**Comment by mycar98765** [comment]
@maheshmnj, when I need to login to Google on Flutter web, I have to run `flutter run -d chrome --web-hostname localhost --web-port 7357` in terminal to run Flutter web. When I run it, hot restart doesn't work for me on Flutter web.

**Comment by maheshmnj** [comment]
Thanks for the info @mycar98765, When you run the app using the above command, Does pressing "r" or "R" in the terminal restart the app? if it doesn't then can you share what logs you see in the terminal when the restart fails?

**Comment by mycar98765** [comment]
Thanks @maheshmnj, when I press "r" it will hot restart the Flutter web.

**Comment by maheshmnj** [comment]
@mycar98765  Can you clarify why was this reopened? The issue you linked seems different from this issue, if its a different Issue I would recommend filing a new issue. 
I am going to close this issue for now.

**Comment by mycar98765** [comment]
@maheshmnj, can you fix the issue in the Github issue below?

#103169
