### ISSUE TITLE
[iOS] Archive didn't use CFBundleShortVersionString and CFBundleVersion

### ISSUE THREAD

**Issue by treacks5** [flutter/flutter#102485]
**Expected results:** 
An archive with the version 1.5.84 (489)

**Actual results:** 
An archive with the version 0.7.2 (76)

When I want to generate my archive in Xcode. The version in the 'pubspec.yaml' is not the same as the archive version.

pubspec.yaml version :
<img width="201" alt="Screenshot 2022-04-25 at 09 43 44" src="https://user-images.githubusercontent.com/53431511/165043057-d4e69561-2808-446f-9503-5e346e8c80b2.png">

Info.plist : 
<img width="382" alt="Screenshot 2022-04-25 at 09 44 40" src="https://user-images.githubusercontent.com/53431511/165043222-24b8517d-6233-4fb1-9dc2-992e07f191d6.png">

I also tried to use these values. But same issue happen.
<img width="395" alt="Screenshot 2022-04-25 at 09 45 51" src="https://user-images.githubusercontent.com/53431511/165043448-af111b84-e029-4e15-bf8d-d0363c915c3a.png">

Xcode build version still blocked with the old values
<img width="146" alt="Screenshot 2022-04-25 at 09 48 05" src="https://user-images.githubusercontent.com/53431511/165043813-99f3fbae-ab36-4736-a8fc-687d101a8e7d.png">
Same for the User-Defined values : 
<img width="370" alt="Screenshot 2022-04-25 at 10 04 33" src="https://user-images.githubusercontent.com/53431511/165046467-5abffa4e-11f4-4ea3-a65f-ebdf7468f418.png">
Product > Archive, produce an archive with the wrong version : 
<img width="294" alt="Screenshot 2022-04-25 at 09 54 47" src="https://user-images.githubusercontent.com/53431511/165044909-1cb966c8-0fb9-4569-88c8-cde439ac59ff.png">

Before generated the archive I tried all this steps together : 
1. Xcode clean
2. Xcode remove derived data
3. Delete Runner.xcworkspace / Pods folder / Podfile.lock
4. Android Studio > Invalidate caches + Clear file and history
5. cd ios & pod install

The result is that the build version / number is never updated.
The only way to update the archive version is to directly update the build version / number inside Xcode > General.

```
[✓] Flutter (Channel stable, 2.10.4, on macOS 12.3.1 21E258 darwin-arm, locale en-GB)
    • Flutter version 2.10.4 at /Users/damienlemenager/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (4 weeks ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/damienlemenager/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] Connected device (2 available)
    • Mobile’s iPhone (mobile) • 00008101-00067150227A001E • ios            • iOS 15.4.1 19E258
    • Chrome (web)             • chrome                    • web-javascript • Google Chrome 100.0.4896.127

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

**Comment by maheshmnj** [comment]
Hi @treacks5, I tried to build the newly created ios app and I do see the same version as in `pubspec.yaml`. When you do the following 
- change the version in `pubspec.yaml`  
-  Build the app
- open in  xcode `open ios/Runner.xcworkspace `
Do you see the same version in xcode as in `pubspec.yaml`?

<img width="593" alt="image" src="https://user-images.githubusercontent.com/31410839/165107715-ca80c2a9-e063-4c51-9472-00a5e0ec6dcd.png">
