### ISSUE TITLE
[camera] Make it possible to simultaneously access to front and rear cameras.

### ISSUE THREAD

**Issue by ykaito21** [flutter/flutter#102427]
I want to access both front and rear cameras at the same time and use both previews on the same view to take a picture or record a video like [BeReal App](https://bere.al/en).

<img src="https://user-images.githubusercontent.com/35805590/164868601-aff1c69a-b9b4-4817-8e97-399f21822cb4.jpg" width="200">

**Comment by danagbemava-nc** [comment]
Hi @ykaito21, I see a similar issue requesting this feature in #51928. 

Kindly follow up there for updates. 

Closing from here as duplicate. 

Thank you
