### ISSUE TITLE
[MacOS Desktop]Ability to replace the system about dialog with a Custom Dialog

### ISSUE THREAD

**Issue by mgenware** [flutter/flutter#102440]
## Use case

In order to have a consistent UI across different platforms, I have my own about dialog implemented inside my app. Flutter macOS projects also have a builtin system about dialog. Is there a way to keep the about menu item but allow the user to customize the handler to display an in-app dialog?

**Comment by maheshmnj** [comment]
Hi @mgenware, Thanks for filing the issue. I am quite not sure if the system Dialog can be replaced with a Custom Dialog labeling this issue for further insights from the team.

**Comment by gspencergoog** [comment]
I think that the long term answer to this is [`PlatformMenuBar`](https://master-api.flutter.dev/flutter/widgets/PlatformMenuBar-class.html), which allows customization of the macOS system menu bar to do whatever you want.  It's currently only available in the master branch, but should be in stable soon.
