### ISSUE TITLE
Should flutter doctor support newer versions of ios-deploy?

### ISSUE THREAD

**Issue by mattsarett** [flutter/flutter#10245]
Output from flutter doctor:

[-] iOS toolchain - develop for iOS devices (Xcode 8.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.2.1, Build version 8C1002
    • ios-deploy 1.9.1
    ✗ ios-deploy out of date (1.9.0 is required). To upgrade:
        brew update
        brew upgrade ios-deploy
    • CocoaPods version 1.2.1

I think this might be preventing me from running flutter on a connected device.  I'm currently trying to figure out how to downgrade to 1.9.0.

Should 1.9.1 be supported?

**Comment by eseidelGoogle** [comment]
Thanks for the report!  @cbracken

**Comment by cbracken** [comment]
Wow - that's definitely a bug. Thanks for reporting! 

Interestingly, I'm also using `ios-deploy` 1.9.1 and not seeing that error message so I suspect a bug in the reporting. It's possible we're reporting an ios-deploy issue when we should be reporting something else instead. Could you run `flutter doctor -v` and add the log to this bug report?

**Comment by mattsarett** [comment]
I'm digging now, but I actually think this is user error.  I didn't I set up the symlink to libimobiledevice properly.  idevice_id was failing to run, which was what caused the error to be printed.

**Comment by cbracken** [comment]
Thanks that's useful info! I'll see if I can repro and we'll get a patch put together to get the right diagnostic message displayed.

**Comment by mattsarett** [comment]
Sure!  I think a more informative error message would be helpful.

Also feel free to close this.  It was caused by a bad install of libimobiledevice on my end.  I think this is essentially a documentation/messaging nit.

**Comment by cbracken** [comment]
Fixed by #10254.
