### ISSUE TITLE
Support for native application on linux just like windows

### ISSUE THREAD

**Issue by satviksinha12** [flutter/flutter#102468]
Hi flutter dev team,I request you to bring support for flutter native applications on Linux. I feel like flutter has very high scopes on Linux just like other platform and will make it easier for Linux developers to build native application on Linux.
Thanking you
Your's sincerely
Satvik

**Comment by danagbemava-nc** [comment]
Hi @satviksinha12, I'm not entirely sure what it is you are requesting here. 

Are you asking for a UI library for linux or are you requesting that flutter be built for linux?

**Comment by satviksinha12** [comment]
Hi ,I was asking for just like you brought native windows support to flutter ,where we can build our flutter UI apps in .exe format for windows ,I was requesting the same for Linux also where we can build apps to run in Linux operating system ,natively.

**Comment by stuartmorgan** [comment]
That has existed for several years, see https://docs.flutter.dev/desktop for details.
