### ISSUE TITLE
flutter run fails on Windows when project path contains space character

### ISSUE THREAD

**Issue by mravn-google** [flutter/flutter#10244]
## Steps to Reproduce

Not entirely sure, beyond having a flutter project in a folder containing a space character on a Windows dev machine, and executing `flutter run`.

The error below has been seen in a particular scenario and went away after moving the project to a different folder without the space character. We are trying to collect some more context.

cc @Gustash

## Logs

```
%1 is not a valid win32 app
```

## Flutter Doctor

TBD

**Comment by eseidelGoogle** [comment]
@goderbauer fixed some flavors of these.  We used to have this bug on mac too, but then @cbracken added a space to the path on our mac bot and it hasn't come back since to my knowledge. :)

**Comment by cbracken** [comment]
FYI I haven't actually added it yet; I've got the patch ready to go, but it uncovered a `flutter_tester` engine-side bug that needs fixing re: URL-encoding. I'll try to get back to that now that I've got a little more time.

**Comment by goderbauer** [comment]
@mravn-google The log output right before the `%1 is not a valid win32 app` line would be of interest to know which command produced that error. Do you happen to have that one? There have been user reports of `pub` throwing that exception, see https://github.com/dart-lang/pub/issues/1591.

**Comment by mravn-google** [comment]
No, sorry. The issue was reported on gitter by @Gustash.

**Comment by goderbauer** [comment]
From Gitter: @Gustash thinks it was during the `running assembleDebug` step. So, that's most likely not pub then.

I cannot reproduce this on my system. Running `flutter run` in `C:\Users\goderbauer\foo bar\hello_there` works just fine.

**Comment by mravn-google** [comment]
Also from gitter, earlier: the flutter project was reported to work fine for some time before the error occurred

**Comment by goderbauer** [comment]
On a fresh windows machine, I just created a user named `Name with a space` and installed all flutter dependencies for that user. Flutter runs just fine in that setup. I am very doubtful that the space in the path is actually the problem here.

**Comment by Gustash** [comment]
I had the same problem yesterday. Before that the project was always in the same directory, which was `C:\Users\Gustavo Pereira\IdeaProjects\gps_coordinates\example`. I did solve it by moving it to a new directory without any spaces, but I'm doubtful that would be the issue when everything worked before that. Here's my `flutter doctor`.

```
C:\Users\Gustavo Pereira>flutter doctor
[√] Flutter (on Microsoft Windows [Version 6.1.7601], channel alpha)
    • Flutter at C:\Flutter
    • Framework revision 973304d5fb (4 days ago), 2017-05-18 17:31:57 -0700
    • Engine revision f99d3ef108
    • Tools Dart version 1.23.0-dev.11.11

[√] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at C:\Android\sdk
    • Platform android-25, build-tools 25.0.3
    • ANDROID_HOME = C:\Android\sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[√] Android Studio (version 2.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Gradle version 3.2
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[√] IntelliJ IDEA Ultimate Edition (version 2017.1)
    • Dart plugin version 171.4424
    • Flutter plugin version 13.1

[-] WebStorm (version 2017.1)
    • Flutter plugin not installed; this adds Flutter specific functionality.
    • For information about managing plugins, see
      https://www.jetbrains.com/help/idea/managing-plugins.html

[√] Connected devices
    • None
```

**Comment by hassanalinali** [comment]
I have the same issue with the latest alpha when trying to run 'flutter doctor' and update the dependencies

**Comment by tvolkert** [comment]
@mravn-google is this fixed nowadays?

**Comment by mravn-google** [comment]
The root cause does not appear to be spaces in the path name. Closing this issue.
