### ISSUE TITLE
Camera plugin: android: problems with flash and exposure

### ISSUE THREAD

**Issue by avmax** [flutter/flutter#102471]
Hello!

I want my app to take photos with flash. And there is a problem with exposure on Android.

To do this im using package:camera/camera.dart.
Here are the methods I am using to take a photo:
`await _controller.setFlashMode(FlashMode.always);
var photo = await _controller.takePicture()`

At iOS everything works fine. But on Android I get the following:
https://i.stack.imgur.com/nnx5T.jpg

On the left - image that I receive in my app.
On the right - image of the same object from the same angle made by native android camera app. with flash

The question is - how can I fix this and get the same photo image in my app as I receive in native camera app?

Thanks for help in advance!

**Comment by darshankawar** [comment]
@avmax 
Probably your use case is similar to https://github.com/flutter/flutter/issues/83549, so please check the same.
If not, provide your `flutter doctor -v`, a complete minimal code sample and the device on which you are seeing the reported behavior.

**Comment by avmax** [comment]
@darshankawar my case is similar to [#83549](https://github.com/flutter/flutter/issues/83549), but not the same(
My problem depends on a flash and ```_controller.setFlashMode``` method.

Android device: POCO X3 Pro
MIUI version: 13.0.3 Stable
Android version: 12

However this problem appeared on every android device I checked on.

Below is the code sample.

Code sample where I create camera controller:
`
  @override
  void initState() {
    super.initState();
    initCamera();
  }

  void initCamera() async {
    final cameras = await availableCameras();
    final firstCamera = cameras.first;
    // To display the current output from the Camera,
    // create a CameraController.
    _controller = CameraController(
      // Get a specific camera from the list of available cameras.
      firstCamera,
      // Define the resolution to use.
      ResolutionPreset.max,
      // Disable audio recording and microphone usage
      enableAudio: false,
    );

    await _controller.initialize();
  }
`


And here I take photo:
`
  Future<XFile> _takePhotoWithFlash() async {
    await _controller.setFlashMode(FlashMode.torch);
    await Future.delayed(const Duration(seconds: 1), () {});
    final XFile photoWithFlash = await _controller.takePicture();
    await _controller.setFlashMode(FlashMode.off);
    return photoWithFlash;
  }
`

And finally, output of `flutter doctor-v`

`
[✓] Flutter (Channel stable, 2.10.5, on macOS 12.2.1 21D62 darwin-x64, locale ru-RU)
    • Flutter version 2.10.5 at /Users/igloo/Code/flutter_sandbox/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (8 days ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/igloo/Library/Android/sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code (version 1.66.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.38.1

[✓] Connected device (2 available)
    • M2102J20SG (mobile) • f4e7ec23 • android-arm64  • Android 12 (API 31)
    • Chrome (web)        • chrome   • web-javascript • Google Chrome 100.0.4896.127

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
`

**Comment by darshankawar** [comment]
Thanks for the update. Can you provide more details on where are you calling `_takePhotoWithFlash` method ?
Good to get a complete minimal code sample that we can directly use to run and verify.

Also, please check the behavior using plugin's [example](https://github.com/flutter/plugins/tree/main/packages/camera/camera/example) as well and see if you still get same issue using it or not.

**Comment by avmax** [comment]
@darshankawar yo!
Here is the minimal code sample:

`import 'package:flutter/material.dart';

import 'dart:io';

import 'package:camera/camera.dart';
import 'package:loading_animation_widget/loading_animation_widget.dart';

void main() async {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'VetX',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      routes: {
        '/photo/take': (_) => const TakePhotoPage(),
        '/photo/confirm': (_) => const ConfirmTestPhotoPage(),
      },
      initialRoute: '/photo/take',
    );
  }
}

class TakePhotoPage extends StatefulWidget {
  const TakePhotoPage({Key? key}) : super(key: key);

  @override
  TakePhotoPageState createState() => TakePhotoPageState();
}

class TakePhotoPageState extends State<TakePhotoPage> {
  late CameraController _controller;
  bool isCameraReady = false;
  bool isPhotoInProgress = false;

  @override
  void initState() {
    super.initState();
    initCamera();
  }

  void initCamera() async {
    final cameras = await availableCameras();
    final firstCamera = cameras.first;
    // To display the current output from the Camera,
    // create a CameraController.
    _controller = CameraController(
      // Get a specific camera from the list of available cameras.
      firstCamera,
      // Define the resolution to use.
      ResolutionPreset.max,
      // Disable audio recording and microphone usage
      enableAudio: false,
    );

    await _controller.initialize();
    setState(() {
      isCameraReady = true;
    });
  }

  @override
  void dispose() {
    // Dispose of the controller when the widget is disposed.
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Take a picture')),
      // You must wait until the controller is initialized before displaying the
      // camera preview. Use a FutureBuilder to display a loading spinner until the
      // controller has finished initializing.
      body: Center(
        child: isCameraReady
            ? Column(mainAxisAlignment: MainAxisAlignment.start, children: [
                Container(
                  padding: const EdgeInsets.only(top: 20),
                  width: MediaQuery.of(context).size.width * 0.9,
                  height: MediaQuery.of(context).size.height * 0.75,
                  child: Stack(
                    alignment: AlignmentDirectional.center,
                    children: [
                      CameraPreview(_controller),
                    ],
                  ),
                ),
              ])
            :
            // Otherwise, display a loading indicator.
            Column(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [LoadingAnimationWidget.fourRotatingDots(color: Theme.of(context).primaryColor, size: 200)],
              ),
      ),
      floatingActionButton: SizedBox(
        width: 80,
        height: 80,
        child: FittedBox(
          child: FloatingActionButton(
            // Provide an onPressed callback.
            onPressed: _takePhoto,
            child: const Icon(Icons.camera_alt),
          ),
        ),
      ),
      floatingActionButtonLocation: FloatingActionButtonLocation.centerFloat,
    );
  }

  void _takePhoto() async {
    if (isPhotoInProgress) return;
    isPhotoInProgress = true;

    try {
      final File photoWithoutFlash = await _takePhotoWithoutFlash();
      final File photoWithFlash = await _takePhotoWithFlash();

      Navigator.pushNamed(
        context,
        '/photo/confirm',
        arguments: {
          'photoWithFlash': photoWithFlash,
          'photoWithoutFlash': photoWithoutFlash,
        },
      );
    } catch (e) {
      print(e);
    }

    isPhotoInProgress = false;
  }

  Future<File> _takePhotoWithoutFlash() async {
    await _controller.setFlashMode(FlashMode.off);
    final File photoWithoutFlash = File((await _controller.takePicture()).path);
    return photoWithoutFlash;
  }

  Future<File> _takePhotoWithFlash() async {
    await _controller.setFlashMode(FlashMode.torch);
    await Future.delayed(const Duration(seconds: 1), () {});
    final File photoWithFlash = File((await _controller.takePicture()).path);
    await _controller.setFlashMode(FlashMode.off);
    return photoWithFlash;
  }
}

class ConfirmTestPhotoPage extends StatelessWidget {
  const ConfirmTestPhotoPage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    final File photoWithFlash = (ModalRoute.of(context)!.settings.arguments as dynamic)['photoWithFlash'] as File;
    final File photoWithoutFlash = (ModalRoute.of(context)!.settings.arguments as dynamic)['photoWithoutFlash'] as File;

    return Scaffold(
      appBar: AppBar(
        title: const Text('Confirm photo'),
      ),
      body: Center(
          child: SingleChildScrollView(
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            const SizedBox(height: 20),
            const Text('Flash: disabled', style: TextStyle(fontSize: 22)),
            const SizedBox(height: 10),
            SizedBox(
              width: MediaQuery.of(context).size.width * 0.9,
              height: MediaQuery.of(context).size.height * 0.75,
              child: Stack(
                alignment: AlignmentDirectional.center,
                children: [
                  Image.file(photoWithoutFlash, fit: BoxFit.fitWidth),
                ],
              ),
            ),
            const SizedBox(height: 20),
            const Text('Flash: enabled', style: TextStyle(fontSize: 22)),
            const SizedBox(height: 10),
            SizedBox(
              width: MediaQuery.of(context).size.width * 0.9,
              height: MediaQuery.of(context).size.height * 0.75,
              child: Stack(
                alignment: AlignmentDirectional.center,
                children: [
                  Image.file(photoWithFlash, fit: BoxFit.fitWidth),
                ],
              ),
            ),
            const SizedBox(height: 80),
          ],
        ),
      )),
      floatingActionButton: Row(
        mainAxisAlignment: MainAxisAlignment.spaceBetween,
        children: [
          const SizedBox(width: 10),
          SizedBox(
            width: 80,
            height: 80,
            child: FittedBox(
              child: FloatingActionButton(
                heroTag: 'refresh',
                onPressed: () => retakePhote(context),
                child: const Icon(Icons.refresh),
              ),
            ),
          ),
          const SizedBox(width: 10),
        ],
      ),
      floatingActionButtonLocation: FloatingActionButtonLocation.centerFloat,
    );
  }

  void retakePhote(BuildContext context) async {
    Navigator.pushReplacementNamed(
      context,
      '/photo/take',
    );
  }
}
`

**Comment by darshankawar** [comment]
@avmax 
Thanks for the runnable code. I used it and ran it on Android A2Core device running API 27 and observed below:


https://user-images.githubusercontent.com/67046386/166189160-60906657-5e73-44d1-9b66-c8bd25680c81.MOV



Indicating, the takePicture worked properly.  Is there anything else apart from the video that you are facing at your end ?
