### ISSUE TITLE
CocoaPods not installed

### ISSUE THREAD

**Issue by kingkongsama** [flutter/flutter#102478]
HI, I have update Flutter 2.10.5 from 2.10.1. 
When update completed, I run "Flutter doctor",   there is error said "CocoaPods not installed", even I have installed cocoaPods

So far, I have tried

1. remove all cocoapods file by 
"rm -rf ~/.cocoapods"

2. reinstall cocoaPods by
"sudo gem uninstall cocoapods"
"sudo gem install cocoapods"
or
"brew install cocoapods"
"brew uninstall cocoapods"

3. "Flutter clean" and Android Studio->"Invalidate and Restart"

4. "pod setup" and "pod install"

But the Flutter Doctor still said "CocoaPods not installed",  

Here is my gem list and `flutter doctor -v`

*** LOCAL GEMS ***
cocoapods (1.11.3)
cocoapods-core (1.11.3)
cocoapods-deintegrate (1.0.4)
cocoapods-downloader (1.6.3)
cocoapods-plugins (1.0.0)
cocoapods-search (1.0.0)
cocoapods-trunk (1.5.0)
cocoapods-try (1.2.0)

[✓] Flutter (Channel stable, 2.10.4, on macOS 12.3.1 21E258 darwin-x64, locale zh-Hans-CN)
    • Flutter version 2.10.4 at /Users/ezio/Desktop/flutter_macos/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (4 weeks ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/ezio/Library/Android/sdk
    • Platform android-31, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 13.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Connected device (2 available)
    • iPhone6s (mobile) • 3c0a3fce33569132e2b082ab3b486542d2f9abad • ios            • iOS 13.5.1 17F80
    • Chrome (web)      • chrome                                   • web-javascript • Google Chrome 100.0.4896.127

Is there someone has same problem?

**Comment by Yukams** [comment]
Hi,

If I'm remembering well, I had a lot of issues to install cocoapods too. I searched on my browser history and this is the last link I seem to have for any cocoapods installation related problem. So I guess it's what solved it for me :

[https://developer.apple.com/forums/thread/668456](https://developer.apple.com/forums/thread/668456)

Though I can't guarantee it's still a good fix, neither if it's still working. But try it out maybe ?

**Comment by kingkongsama** [comment]
> Hi,
> 
> If I'm remembering well, I had a lot of issues installing cocoapods too. I searched on my browser history and this is the last link I seem to have for any cocoapods' installation related issue. So I guess it's what solved it for me :
> 
> https://developer.apple.com/forums/thread/668456
> 
> Though I can't guarantee it's still a good fix, neither if it's still working. But try it out maybe ?

Thanks [Yukams](https://github.com/Yukams).
I have find the reason: My Android Studio verion is too low (4.1.3), so when I update it to latest verion , the problem has been sloved
https://developer.android.com/r/studio-ui/download-stable.html
