### ISSUE TITLE
[autosubmit] Duplicate messages are saved to pub/sub queue for a single PR

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#102418]
Take https://github.com/flutter/cocoon/pull/1779 for example. 
When this PR was first submitted and marked `autosubmit` label, here is a screenshot from pubsub queue, where four messaged are pushed.
![Screen Shot 2022-04-22 at 5 33 00 PM](https://user-images.githubusercontent.com/54558023/164838494-51f81f6a-fa18-4e59-b520-98d8ce3815e0.png)

This causes the bot to repeatedly check PR merge status, though the label was removed the first time.

**Comment by keyonghan** [comment]
@godofredoc could you help check if the app sends multiple webhook events to the API? I am wondering if adding other labels triggers the event after `autosubmit` label was added.

**Comment by godofredoc** [comment]
A mitigation for this has been landed, there will still be some duplicated messages as when adding new labels we don't know if the auto-submit label was there previously and a new message is created.
