### ISSUE TITLE
[camera_web][android] App throws `The Camera is not supported on this device` error 

### ISSUE THREAD

**Issue by P-B1101** [flutter/flutter#102436]
First of all, thank you guys for your awesome work. Well, my problem is when I use the camera plugin for my web application I got this error
Error code: 

> cameraNotSupported

Error description: 

> The camera is not supported on this device

I already found #90881 and #90040 but not helping.

for the record, my device has a camera, and I test [Photobooth](https://github.com/flutter/photobooth) codes that directly use platform camera API, and it works fine. 

- Android Device Tested: Galaxy S8+
- Camera plugin version used: 0.9.4+20
- Environment: Debug mode

**Comment by aloysiousBenoy** [comment]
Please follow the format provided for reporting bugs. I don't think you have provided  enough information to diagnose the issue.

**Comment by P-B1101** [comment]
Where can I find provided format?
none of formated at the beginning of the opening issue was for reporting bugs for the camera package.

**Comment by navaronbracke** [comment]
When you create a new issue and pick the option `I have a problem with my Flutter application`, the issue description starts with a prefilled template. Fill out each section of that template.

**Comment by danagbemava-nc** [comment]
Hi @P-B1101, please provide a complete minimal reproducible code sample so that we can verify this issue. Please also provide the output of `flutter doctor -v`.

Thank you

**Comment by P-B1101** [comment]
Hi, I believe that the example app in the package has the same issue.  the problem will show in a specific target device  (like my galaxy S8+).

**Comment by danagbemava-nc** [comment]
Hi, @P-B1101, I tested the example in the camera package on a `POCO X3 NFC` and I could not reproduce the issue. Is the s8+ the only device that you're experiencing this issue on? 

> Please also provide the output of flutter doctor -v.

This info will be appreciated

**Comment by P-B1101** [comment]
Hi, @danagbemava-nc, I just tested it on my `Galaxy S8+` and this is the screenshot of it. :(

![photo_2022-04-27_00-25-29](https://user-images.githubusercontent.com/22874550/165381525-c9f952a6-59ee-40e0-99be-33324e35f6c3.jpg)

**Comment by danagbemava-nc** [comment]
Hi @P-B1101, can you check if you have allowed your browser access to your `Camera`?

I tested in `Chrome` and I was able to open the cameras just fine. The only time I got this message was when I disabled the camera permission for `Chrome`. See screenshots below

<details>
<summary>screenshots</summary>

| permission denied | permission granted | 
| -- | -- |
| ![photo_2022-04-27 07 30 02](https://user-images.githubusercontent.com/88313112/165465206-bf1b3a23-fa8d-494c-9786-508bbcdae96f.jpeg) | ![photo_2022-04-27 07 30 06](https://user-images.githubusercontent.com/88313112/165465189-eebe1ccc-7af6-4904-aa09-be8d9b93db06.jpeg) |

**Comment by P-B1101** [comment]
Yes, The permission pop-up will show and I give access to the browser.

**Comment by danagbemava-nc** [comment]
Hmmm, just to confirm, you tested it with the `chrome` mobile browser, is that correct? 

Do you also have this issue when you run a release version of the app?

**Comment by P-B1101** [comment]
Yes, tested in chrome mobile browser. and no just tested on debug mode.

**Comment by danagbemava-nc** [comment]
Hmm, one final thing, can you try this url https://test-2f735.web.app to see if it works? It's the camera example deployed to firebase hosting. 

Please also make sure that chrome has the right permissions as shown below. 

<img src="https://user-images.githubusercontent.com/88313112/165696085-73e94fbb-36a1-4be3-a934-168b8bd5b3b8.jpeg"  width="250"/>

Thank you

**Comment by P-B1101** [comment]
That works!! it only works if I deploy it?

**Comment by P-B1101** [comment]
I test it again in incognito and I did not get a permission popup. I check browser settings and didn't find anything.
I test it on the Samsung browser too and the result was the same.
check the chrome settings for camera permission and it was allowed. check the chrome app settings and it has allowed permission for the camera. I don't know what to do next!! :((

**Comment by danagbemava-nc** [comment]
I'm going to have to label this for further investigation as I cannot reproduce this locally. 

@P-B1101, just to confirm, you're experiencing this on both your Samsung S+ and Xiaomi Mi 11X, is that correct?

**Comment by P-B1101** [comment]
Yes, I do.

**Comment by danagbemava-nc** [comment]
I got a bunch of browsers and tested all of them with the deployed version of the app and some of them worked, others didn't. 

<details>
<summary>screenshots</summary>

### Browsers that worked

| chrome | brave | opera mini |
| -- | -- | -- |
| ![photo_2022-05-02 12 35 13](https://user-images.githubusercontent.com/88313112/166234662-1f66cd08-ac56-419f-b369-5ca43c1dabda.jpeg)| ![photo_2022-05-02 12 35 21](https://user-images.githubusercontent.com/88313112/166234648-f0ea8801-65c5-4bde-8a4d-730ed526dac3.jpeg) | ![photo_2022-05-02 12 35 19](https://user-images.githubusercontent.com/88313112/166234657-1713e9f8-b8f4-46dc-96ab-facc63aac1c7.jpeg) |

### Browsers that didn't work

| firefox | firefox focus | via browser | 
| -- | -- | -- |
| ![photo_2022-05-02 12 35 16](https://user-images.githubusercontent.com/88313112/166234659-e5f45c77-b3a2-4b58-b322-3a522c7722c3.jpeg) | ![photo_2022-05-02 12 35 10](https://user-images.githubusercontent.com/88313112/166234663-ca4d2f6b-cf9f-4e8d-afd2-a985ae080449.jpeg) | ![photo_2022-05-02 12 35 07](https://user-images.githubusercontent.com/88313112/166234665-b4242cc9-d54c-47f4-88af-89f2e8468fea.jpeg) |

</details>

All browsers had the camera permission enabled in settings. 

For `firefox focus` and `via browser` I never got the prompt to enable camera permission and  I also noticed that the apps do not have microphone permission in the list of permissions, so I could not enable it either way. 

For `firefox`, I got the prompt to enable both the camera and microphone, but even after enabling the permissions, I got the `No camera found` error.

In `firefox`, the error message I get is 

```
Error: cameraAbort
Error Message: Some problem occurred that prevented the camera from being used.
```

In `firefox focus` and `via browser`, the error message I get is

```
Error: cameraPermission
Error Message: The camera cannot be used or the permission to access the camera is not granted.
```

I tried a facetime link with `firefox focus` but I just got a `Not found` error in the browser. 
`firefox` is not supported for the facetime feature yet. 
`Via browser` worked just fine. 

I haven't been able to reproduce the `camera is not supported on this device` error in all the various tests I run. 

Leaving this for further investigation from the team. The code sample in the [package example](https://github.com/flutter/plugins/blob/main/packages/camera/camera/example/lib/main.dart) should be enough to repro this as it did in https://github.com/flutter/flutter/issues/102436#issuecomment-1110192404.

**Comment by blasten** [comment]
cc @ditman

**Comment by ditman** [comment]
I think this is the problem:

```
run -d web-server --web-port 8282 --web-hostname 0.0.0.0 --release
```

@P-B1101 **Can you try to *not* use `0.0.0.0` as hostname, and use `localhost` instead?** I think your browser thinks 0.0.0.0 is an "insecure origin". (You should also check in the Developer Console of Chrome to see if there are any errors thrown from Javascript.)

See this article, for example: https://medium.com/@Carmichaelize/enabling-the-microphone-camera-in-chrome-for-local-unsecure-origins-9c90c3149339

**Comment by P-B1101** [comment]
@ditman Thanks, I did test what you said and it fix the issue.  however, when I click the camera (front and rear) it takes a lot of time to change. and after two or three times of changing it got stuck.

**Comment by yjbanov** [comment]
@P-B1101 can you please file a new issue about it getting stuck?
