### ISSUE TITLE
 Can UI Task Runner execute on Android main thread?

### ISSUE THREAD

**Issue by loongchow** [flutter/flutter#102466]
## Use case

My project uses MVVM as the development framework, but our view model is implemented in C++, the view model layer is executed on the Android main thread, and it is a single-threaded model. We need frequent thread switching when communicating with the view model through the dart ffi.
So we hope there is a way that UI Task Runner can be executed on the Android main thread, so that we don't need frequent thread switching

## Proposal

May be We can add a meta-data for Flutter Activity in AndroidManifest.xml
 <meta-data android:name="io.flutter.app.android.FlutterUITaskRunnerExecuteOnPlatformThread"
                android:value="ture"/>

**Comment by darshankawar** [comment]
@loongchow 
Can you take a look at this document and see if it helps further ? https://github.com/flutter/flutter/wiki/The-Engine-architecture#ui-task-runner
