### ISSUE TITLE
Is it posible to run dart code in platform-specific Android Service with Flutter?

### ISSUE THREAD

**Issue by cj3479** [flutter/flutter#102507]
I have a Flutter library that work well in Flutter main.dart but I need to use it in Android services to run in background.

Since Flutter hasn't support Services yet (as I know), so I create a native Android Service using Java and start it using MethodChannel. But I don't know how to use the Flutter library inside my Service.

So is it possible to use the Flutter library inside Android Service or I need to convert the library to Java code?

**Comment by maheshmnj** [comment]
Hi @cj3479, Thanks for filing the issue. If I understand it right you want to use dart code from the platform side is that correct? if so please see the StackOverflow answer https://stackoverflow.com/a/63926566/8253662  and see if it helps.

If you need further help I would suggest you to look for solutions on StackOverflow.

Closing as this is neither a bug nor a feature request.
