### ISSUE TITLE
to make `DraggableScrollableSheet` dismissible

### ISSUE THREAD

**Issue by takassh** [flutter/flutter#102571]
## Use case
we want to dismiss `DraggableScrollableSheet` when we tap the background area (the background area is the red area. please see the attached video below).
and I think there is no workaround.
I found https://stackoverflow.com/questions/64781862/flutter-draggablescrollable-layout-inside-modalbottomsheet-does-not-dismiss, but it needs `expand = false`. if we set it false, we can't drag down the red area.

## Proposal
changing some codes about `DraggableScrollableSheet` or `showModalBottomSheet`

I'm imaging it like this video.
in this video, we can dismiss it tapping the red area, and we can drag down.

https://user-images.githubusercontent.com/52235899/165307817-c4ebf6bf-449a-4195-8f09-0b5c6f1886c0.mov

but now, we can't do anything.
this is related to the issue https://github.com/flutter/flutter/issues/102432
according to it, It works as design, but we can't dismiss it...

<details>
<summary>Code sample</summary>

```dart

import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const HomePage(),
    );
  }
}

class HomePage extends StatelessWidget {
  const HomePage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('title'),
      ),
      body: Center(
        child: ElevatedButton(
          onPressed: () => showModalBottomSheet(
            barrierColor: Colors.yellow.withOpacity(0.5),
            backgroundColor: Colors.red.withOpacity(0.5),
            useRootNavigator: true,
            context: context,
            isDismissible: true,
            builder: (context) => DraggableScrollableSheet(
              builder: (_, controller) => Container(
                color: Colors.white,
                child: ListView.builder(
                  controller: controller,
                  itemBuilder: (_, index) => ListTile(
                    title: Text(index.toString()),
                  ),
                ),
              ),
            ),
          ),
          child: const Text('open modal'),
        ),
      ),
    );
  }
}


```

</details>

**Comment by darshankawar** [comment]
@takassh 
Looking at the use case / behavior you described or looking for, I think your case is same as mentioned in this open issue: https://github.com/flutter/flutter/issues/36283 . Please follow-up in it for further updates or you can share your findings in it.
Closing this as a duplicate. If you disagree, write in comments and I'll reopen it.

**Comment by takassh** [comment]
@darshankawar 
thank you for kind.

certainly, this issue is related to the issue. I will comment on the issue. thanks!
