### ISSUE TITLE
Flutter plugin development error

### ISSUE THREAD

**Issue by 1663049254** [flutter/flutter#102563]
When I developed the flutter IOS plug-in and tried to introduce a third-party library, I made a mistake

## Steps to Reproduce
1.flutter create test1    
  cd test1 
2.flutter create --org com.tencent.map --template=plugin --platforms=android,ios -a java -i objc map
3.cd test1/map/ios     
   The podspec file is added as follows：
   s.dependency 'Tencent-MapSDK'
4.cd test1/map/example/ios  
   pod install
5.cd test1   
   flutter run
6.Errors are reported as follows：
   building for iOS Simulator, but linking in object file built for iOS, for architecture arm64

How can I solve this error？

## Logs

<details>
<summary>Logs</summary>

```
```

```
```

</details>

**Comment by darshankawar** [comment]
> 6.Errors are reported as follows：
> building for iOS Simulator, but linking in object file built for iOS, for architecture arm64

Can you provide the entire error log by running `flutter run -v` in properly formatted text ?
