### ISSUE TITLE
Cannot assign color from theme.

### ISSUE THREAD

**Issue by infacto** [flutter/flutter#102517]
https://docs.flutter.dev/cookbook/design/themes#using-a-theme

![image](https://user-images.githubusercontent.com/60390085/165136746-bbd65e00-e446-4945-bc57-242c8d516a06.png)

Nope ...

Flutter 2.10.5

**Comment by danagbemava-nc** [comment]
Hi @infacto, this is an issue with your code. 
You need to remove the `const` from `DrawerHeader`. 

The value you have provided for the color is not a `const` value, that is why you're getting this error. 

Closing this as this is an implementation issue. 

Thank you
