### ISSUE TITLE
[Discussion] Is `Widget Test` redundant?

### ISSUE THREAD

**Issue by YowFung** [flutter/flutter#102548]
As far as I know, the Widget Test basically simulates events such as clicking or scrolling and then detects whether the target widget contains the expected text, child, and so on.

But I think that when you code a UI widget, shouldn't the first and most important thing be to verify that it displays and interacts as expected? For example, whether its color, size, position, or animation matches the desired effect, or whether the corresponding callback function is executed after clicking it. Of course, most of these can be verified by the Widget Test. However, some visual effects need to be perceived by eye observation, and it is difficult to describe with abstract data. 

For example, you code a widget and set its text color to 0xFFF2F2F2. I know this color is white, but how white is it? How does it look when combined with the surrounding background? In another sample, you put widget A to the right of widget B. But where exactly on the right, and how far apart does it look good? None of this can be verified by Widget Test. 

So most of the time, when we create a new widget, we have to write a demo for it. Then run the demo, observe it and operate it to verify its actual effect. Now that you've done this prosecution, and you've verified that your widget is ok, do you still need the Widget Test? 

Or, consider adding the ability to preview the target widget in real-time during Widget Test?

The above are some of my personal views, and may not be comprehensive cognition. Welcome to share your opinion.

**Comment by jonahwilliams** [comment]
No, its not redundant. This is a bit more philosophical of question than can be answered in the issue tracker. the best way for you to understand the value of these unit tests is to work on a project for an extended period of time without writing a single one. like you said, as long as you verify the demo works it should be fine, right ....?

> Or, consider adding the ability to preview the target widget in real-time during Widget Test?

You can `flutter run` a widget test and execute them, debug them, step through them just like regular code.
