### ISSUE TITLE
image_picker does not throw error when recording video with no microphone permissions (iOS)

### ISSUE THREAD

**Issue by chagaj** [flutter/flutter#102549]
Hello,

I have noticed an issue when recording video on an iOS device using `image_picker` (by calling `imagePicker.pickVideo(source: ImageSource.camera);`. 

In general, the user is requested both camera and microphone permissions **the first time** they attempt recording a video. However, if microphone and camera permissions are revoked thereafter, the image_picker library only throws an exception for the missing camera permissions and not for the missing microphone permissions (on iOS). 

This means I am only able to catch the exception caused by the missing camera permissions and subsequently request camera permissions from the user. I am unable to request microphone permissions from the user because there is no exception thrown.

In fact, when camera permissions are missing, the following is logged to the console but the exception is not exposed:
`[Camera] Creating an AVCaptureDeviceInput for the audio device (<AVCaptureFigAudioDevice: 0x28046ae60 [iPhone Microphone][com.apple.avfoundation.avcapturedevice.built-in_audio:0]>) failed. (Error Domain=AVFoundationErrorDomain Code=-11852 "Cannot use iPhone Microphone" UserInfo={NSLocalizedFailureReason=This app is not authorized to use iPhone Microphone., AVErrorDeviceKey=<AVCaptureFigAudioDevice: 0x28046ae60 [iPhone Microphone][com.apple.avfoundation.avcapturedevice.built-in_audio:0]>, NSLocalizedDescription=Cannot use iPhone Microphone})` 

Is there a way I could expose this exception so that my app could always ask the user for microphone permissions whenever it is missing when recording a video? 

Is there another workaround for this?

Thank you very much in advance.

**Comment by darshankawar** [comment]
@chagaj 
Thanks for the report. 

> However, if microphone and camera permissions are revoked thereafter, the image_picker library only throws an exception for the missing camera permissions and not for the missing microphone permissions (on iOS).

Can you elaborate on this as how are you revoking the permissions after granting them ?

From the plugin example I tried, if we are recording video for the first time, it asks for camera and microphone permissions. If we deny `microphone permission`, then I get below log in the console which I think is expected:
```

VERBOSE-2:FlutterObservatoryPublisher.mm(143)] Could not register as server for FlutterObservatoryPublisher. Check your network settings and relaunch the application.
[Snapshotting] Snapshotting a view (0x123d656a0, CAMPreviewView) that has not been rendered at least once requires afterScreenUpdates:YES.
[Camera] Creating an AVCaptureDeviceInput for the audio device (<AVCaptureFigAudioDevice: 0x2800691f0 [iPhone Microphone][com.apple.avfoundation.avcapturedevice.built-in_audio:0]>) failed. (Error Domain=AVFoundationErrorDomain Code=-11852 "Cannot use iPhone Microphone" UserInfo={NSLocalizedFailureReason=This app is not authorized to use iPhone Microphone., AVErrorDeviceKey=<AVCaptureFigAudioDevice: 0x2800691f0 [iPhone Microphone][com.apple.avfoundation.avcapturedevice.built-in_audio:0]>, NSLocalizedDescription=Cannot use iPhone Microphone})
[Snapshotting] Snapshotting a view (0x123eb0410, CAMPreviewView) that has not been rendered at least once requires afterScreenUpdates:YES.
[Camera] Creating an AVCaptureDeviceInput for the audio device (<AVCaptureFigAudioDevice: 0x2800691f0 [iPhone Microphone][com.apple.avfoundation.avcapturedevice.built-in_audio:0]>) failed. (Error Domain=AVFoundationErrorDomain Code=-11852 "Cannot use iPhone Microphone" UserInfo={NSLocalizedFailureReason=This app is not authorized to use iPhone Microphone., AVErrorDeviceKey=<AVCaptureFigAudioDevice: 0x2800691f0 [iPhone Microphone][com.apple.avfoundation.avcapturedevice.built-in_audio:0]>, NSLocalizedDescription=Cannot use iPhone Microphone})
```

Are you trying the same use case / scenario that I described ? If not, can you provide exact steps to replicate too ?

**Comment by chagaj** [comment]
@darshankawar thanks for your quick response.

After granting permissions the first time, I revoke them manually by open iOS settings > app name > disable microphone permissions. 

If i then try recording a video, I am no longer asked microphone permissions again, and neither is an error thrown. As such I am unable to detect that microphone permissions are missing and request said permissions from the user again.

What results in this case is a video recorded with no audio.

To reiterate, I am looking for a way to detect that microphone permissions are missing (or have been revoked).

**Comment by darshankawar** [comment]
Thanks for the update. I now see what you are saying. Revoking the microphone permission from app settings and then recording the video, records it without audio and console shows below log:

```
[Camera] Creating an AVCaptureDeviceInput for the audio device (<AVCaptureFigAudioDevice: 0x2804c8bd0 [iPhone Microphone][com.apple.avfoundation.avcapturedevice.built-in_audio:0]>) failed. (Error Domain=AVFoundationErrorDomain Code=-11852 "Cannot use iPhone Microphone" UserInfo={NSLocalizedFailureReason=This app is not authorized to use iPhone Microphone., AVErrorDeviceKey=<AVCaptureFigAudioDevice: 0x2804c8bd0 [iPhone Microphone][com.apple.avfoundation.avcapturedevice.built-in_audio:0]>, NSLocalizedDescription=Cannot use iPhone Microphone})
[Snapshotting] Snapshotting a view (0x149d0d120, CAMPreviewView) that has not been rendered at least once requires afterScreenUpdates:YES.
[Camera] Creating an AVCaptureDeviceInput for the audio device (<AVCaptureFigAudioDevice: 0x2804c8bd0 [iPhone Microphone][com.apple.avfoundation.avcapturedevice.built-in_audio:0]>) failed. (Error Domain=AVFoundationErrorDomain Code=-11852 "Cannot use iPhone Microphone" UserInfo={NSLocalizedFailureReason=This app is not authorized to use iPhone Microphone., AVErrorDeviceKey=<AVCaptureFigAudioDevice: 0x2804c8bd0 [iPhone Microphone][com.apple.avfoundation.avcapturedevice.built-in_audio:0]>, NSLocalizedDescription=Cannot use iPhone Microphone})

```

I think the log seems to be expected since it is recognizing that there's no microphone permission and hence when we try to record a video, it records without audio.


> I am looking for a way to detect that microphone permissions are missing (or have been revoked).

I am not too sure, but it may not be Flutter plugin specific. Do you know how it works with native iOS camera ?
