### ISSUE TITLE
[CP] Avoid scheduling a first frame too early

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#102583]
### issue_link

b/230429702

### Commit Hash

34d8420

### Target

beta

### Impacted Users

All end-customers

### Impact Description

App may take down splash screen too early on Android and iOS.

The device may report metric related information multiple times during startup. For larger apps that do not immediately call `runApp` in `main`, this may result in the framework forcing a frame to be scheduled, which will incorrectly indicate to the engine that Flutter has started rendering UI before it is actually ready.

### Workaround

An application could do some complicated work around involving overriding their bindings and refusing to let the superclass do what it should. It is not viable.

### Risk

low

### Test Coverage

yes

### Validation Steps

Internal customer tests accurately show whether the callback is firing too early.

**Comment by dnfield** [comment]
https://github.com/flutter/flutter/pull/102556

**Comment by itsjustkevin** [comment]
@HansMuller

**Comment by CaseyHillers** [comment]
Landed in last week's hotfix in https://github.com/flutter/flutter/pull/103101
