### ISSUE TITLE
Flutter debug or release apk sizes increase after making new build

### ISSUE THREAD

**Issue by Hannan404** [flutter/flutter#102500]
Hi team, i just noticed that whenever i try to make a debug apk it's size increasing as compare to previous debug apk. e.g first when i try to generate debug apk it's size was 28.5 mb but when i tried to again debug without adding single line of code, it's size increase to 40.3 mp. it's too much strange.

**Comment by maheshmnj** [comment]
Hi @Hannan404, Thanks for filing the issue. Have you tried `flutter clean`  before building the debug apk? Additionally when you see a increasing size with a consecutive build you can use the [app size tool](https://docs.flutter.dev/development/tools/devtools/app-size#:~:text=Generating%20size%20files-,What%20is%20it%3F,information%E2%80%9D%20using%20the%20Diff%20tab.) from the devtools to understand the increase in size. Please share the output of `flutter doctor -v`.

**Comment by Hannan404** [comment]
Hello @maheshmnj, Thanks for reply, 
Sure i am sharing sample project with you please look into this, this bug taking a lot of time. I noticed yesterday that when even i try to generate signed apk for google play, it's behaving same. Size was increasing with every try!

**Comment by Hannan404** [comment]
@maheshmnj  below is my flutter doctor -v details

[✓] Flutter (Channel stable, 2.10.2, on macOS 12.2 21D49 darwin-x64, locale
    en-GB)
    • Flutter version 2.10.2 at /Users/pro/Documents/Work/SDKs/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 097d3313d8 (9 weeks ago), 2022-02-18 19:33:08 -0600
    • Engine revision a83ed0e5e3
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/pro/Library/Android/sdk
    • Platform android-32, build-tools 32.0.0
    • ANDROID_HOME = “/Users/pro/Library/Android/sdk”
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] Connected device (2 available)
    • SM A307FN (mobile) • RF8MA2NHHPX • android-arm64  • Android 11 (API 30)
    • Chrome (web)       • chrome      • web-javascript • Google Chrome
      100.0.4896.127

[✓] HTTP Host Availability
    • All required HTTP hosts are available

**Comment by maheshmnj** [comment]
>Sure i am sharing sample project with you please look into this, 

@Hannan404 Please do attach the sample project

**Comment by Hannan404** [comment]
@maheshmnj you can create a new project. Because this bug is causing in every project.

Make new Flutter project and then generate debug apk. After generating once, when you try to regenerate the debug apk it's size will be increased. Same this issue is generating while we are making signed apk for google play store.

**Comment by maheshmnj** [comment]
@Hannan404,  I tried building a debug apk and then rebuilding it however I see the same size for both the apks, Please see the below size on disk

Build 1            |  Build 2
:-------------------------:|:-------------------------:
<img width="267" alt="image" src="https://user-images.githubusercontent.com/31410839/165317129-5ec8c25e-7b28-4076-a410-e863e197e0d5.png"> |  <img width="269" alt="image" src="https://user-images.githubusercontent.com/31410839/165317456-47dad255-4d6d-41dd-b58b-4b2643035235.png">

I would suggest you to please share the apk code size analysis json file for both the consecutive build where you see different app size to investigate this issue further.

You can download  the json files from the [appsize tool](https://docs.flutter.dev/development/tools/devtools/app-size#:~:text=Generating%20size%20files-,What%20is%20it%3F,information%E2%80%9D%20using%20the%20Diff%20tab.)

<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel stable, 2.10.5, on macOS 12.3 21E230 darwin-arm, locale en-IN)
    • Flutter version 2.10.5 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (12 hours ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.65.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.39.20220405

[✓] Connected device (4 available)
    • Redmi K20 Pro (mobile) • 192.168.1.2:55555                    • android-arm64  • Android 11 (API 30)
    • iPhone 12 Pro (mobile) • 535317A4-921C-488F-B234-C2CC6D4AE5A1 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.3 21E230 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 100.0.4896.88

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by Hannan404** [comment]
@maheshmnj i got it, if we delete the build folder before regenerating the new build then the apk sizes is not increasing. 

Thanks for reply

**Comment by maheshmnj** [comment]
>i got it, if we delete the build folder before regenerating the new build then the apk sizes is not increasing.

That is what I suggested in the [initial comment](https://github.com/flutter/flutter/issues/102500#issuecomment-1109396706)  😀, Glad its resolved.
