### ISSUE TITLE
Widget assets are not loaded on aws ec2 server

### ISSUE THREAD

**Issue by Sasikumar3595** [flutter/flutter#102506]
We are creating a new widget with the timezone package(https://pub.dev/packages/timezone), and the time zone package asset is not loaded on aws ec2 server and it was working correctly on other servers.

## Steps to Reproduce

1. Configure and run the sample on aws ec2 server
2. It makes an error while loading the timezone package asset 

**Expected results:** 

- Package asset will load correctly on aws ec2 server

**Actual results:** 

- Package asset not loaded correctly on aws ec2 server

<details>
<summary>Code sample</summary>

```dart

@override
  void initState() {
    _loadDataBase();
    super.initState();
  }

  Future<bool> _loadDataBase() async {
    final ByteData byteData =
    await rootBundle.load('packages/timezone/data/2020a.tzf');
    initializeDatabase(byteData.buffer.asUint8List());
    return true;
  }

  void _refresh() {
    DateTime date = DateTime.now();
    Location location = getLocation('Australia/Darwin');
    DateTime convertedDate = TZDateTime.from(date, location);
    print(convertedDate);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Container(

        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _refresh,
        tooltip: 'Convert Date',
        child: const Icon(Icons.refresh),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }

```

</details>

<details>
  <summary>Logs</summary>

```

Uncaught Unable to load asset: packages/timezone/data/2020a.tzf

```

</details>

**Screenshot:** 

![Screen Shot 2022-04-22 at 4 47 38 PM](https://user-images.githubusercontent.com/44917578/165103340-d3bf4317-b2bb-4d0e-980b-43fcef0fa436.png)

**Sample:** 
[flutter_timezone.zip](https://github.com/flutter/flutter/files/8555136/flutter_timezone.zip)

**Comment by darshankawar** [comment]
@Sasikumar3595 
As the error message says `Failed to load resource: the server responded with a status of 404`, it indicates the request is not even reaching Flutter and has been timing out with 404 error, so I think this is an issue from the server side and not from Flutter, so I suggest you to reach out to the said server for further resolution.
Closing from here.
