### ISSUE TITLE
[google_sign_in] NSInvalidArgumentException', reason: 'One of IDToken, accessToken, pendingToken, or requestURI must be supplied.'

### ISSUE THREAD

**Issue by dvird** [flutter/flutter#102590]
google_sign_in: ^5.3.0

when click on login in google it open the dialog, if you cancel this dialog this issue pop.
```
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'One of IDToken, accessToken, pendingToken, or requestURI must be supplied.'
terminating with uncaught exception of type NSException

```

**Comment by darshankawar** [comment]
@dvird 
Can you provide a minimal code sample that shows this error ?
There's a similar open issue that talks about platformException being thrown after canceling the sign-in https://github.com/flutter/flutter/issues/85785, maybe you are hitting same issue, but the error you shared seems to be different, so please provide a code sample that we can use along with `flutter doctor -v`.
