### ISSUE TITLE
Enable RasterCache for clipper layers using saveLayer

### ISSUE THREAD

**Issue by wangying3426** [flutter/flutter#102512]
As we all know, saveLayer has a bad impact on performance, related ​discussions include: https://github.com/flutter/flutter/issues/92874#issuecomment-958205328

Now that, ClipPathLayer/ClipRectLayer/ClipRRectLayer/PhysicalShapeLayer will use saveLayer when clipBehavior is set to Clip::antiAliasWithSaveLayer. Although [Clip::antiAliasWithSaveLayer](https://docs.flutter.dev/release/breaking-changes/clip-behavior) is not recommended and should be less needed, in fact, we found that some of our developers still use it in daily development. 

Therefore, it will help to optimize performance if the raster cache can be used to reduce the use of saveLayer in those cases.

**Comment by ColdPaleLight** [comment]
Closing by linked PR
