### ISSUE TITLE
`flutter ios --init` does not work for iPhone 5

### ISSUE THREAD

**Issue by eseidel** [flutter/flutter#1025]
```% flutter --version
Flutter
Repository: git@github.com:flutter/flutter.git
Branch: master
Revision: 4f672dc04923b474b11c86e9b8cb1a96f5254ac7 (29 hours ago)```

`flutter init -o my_app`
`flutter ios --init`
Select "iPhone5" from the targets list.
Click Run.

Dialog pops up: "FlutterRunner does not have an architecture that iPhone 5 can execute."

@chinmaygarde presumably we're 64-bit only?

**Comment by chinmaygarde** [comment]
The runner meant for the device is 64 bit only. I can add another snapshotter/runner variant for older devices. `ninja` is already configured for this.

**Comment by eseidel** [comment]
Is the list of possible iphone types displayed in that run menu controlled by the runner?  (i.e. should we hide the 32bit ones in that runner?)  Can we have one runner that knows how to build for both? (presumably not due to our current ninja setup?)

![image](https://cloud.githubusercontent.com/assets/478541/12007389/71a1dca2-abb7-11e5-9d97-d750e6010ac8.png)

**Comment by eseidelGoogle** [comment]
I will at least partially fix this as part of moving us to our new infrastructure.

**Comment by chinmaygarde** [comment]
Should I close this as a Wont-Fix? We already hide the 32-Bit variants now and the complexity of adding support for older variant via tooling is non-trivial. If absolutely necessary, we can add this (or make users prepare engine builds.)

**Comment by eseidelGoogle** [comment]
Assuming we hide these, that seems OK.  Does `flutter devices` need to be updated to list iPhone 5 simulators, etc as "incompatible"?  @devoncarew

**Comment by devoncarew** [comment]
Yeah, we would need to black-list the iphone 4s and 5 simulator devices.

**Comment by eseidelGoogle** [comment]
We had another report of this just now in #flutter.  Its easy to end up with a simulator running iPhone 5 and then `flutter start` just crashes.

**Comment by jumpkick** [comment]
I'm the one who reported the crash, it was because I tried to use "iPhone 5" as indicated @ https://flutter.io/getting-started/#running-your-app-in-the-ios-simulator.  

iPhone 5s worked as expected.   Looks like the docs need 64-bit only (iPhone 5s+) rather then just "5"

**Comment by devoncarew** [comment]
We update the docs here: https://github.com/flutter/website/pull/165

**Comment by eseidelGoogle** [comment]
Lets close this and I'll file a separate bug about blacklisting devices.

**Comment by eseidelGoogle** [comment]
Filed https://github.com/flutter/flutter/issues/1929 about handling unsupported devices better.
