### ISSUE TITLE
Video file has multiple audio tracks so how I can select any one audio track?

### ISSUE THREAD

**Issue by NayakBoy** [flutter/flutter#102567]
In Video_player package have no option to select an audio track if a video file has multiple audio tracks. so please add the method so we can select any one audio track.

**Comment by maheshmnj** [comment]
Hi @NayakBoy, Thanks for filing the issue. 

There is a similar issue describing this case https://github.com/flutter/flutter/issues/59437, Please follow up there for further updates, Closing this issue as a duplicate. If you disagree feel free to write in the comments and we will reopen it.

Thank you.
