### ISSUE TITLE
Theme/IconTheme regression

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#10250]
https://github.com/flutter/flutter/pull/10179 caused a regression to our build times

![regression1](https://cloud.githubusercontent.com/assets/551196/26318575/72797506-3ed0-11e7-9ea7-5d43a1df251b.png)

**Comment by Hixie** [comment]
Any update on this? Having the regression makes it very difficult for us to tell if we have more regressions so this is a high priority. (It's fine if you just want to revert the patches that led to the regression in the meantime so that you can lower the priority of this; I would have done it but there were multiple PRs involved so it wasn't trivial.)

**Comment by xster** [comment]
looking at this today

**Comment by xster** [comment]
Definitely reproducible locally. 
Taking median speeds on Samsung S8

Before: (48237d54)
I/flutter (19186): Stock build: 1223.7 µs per iteration

After: (95e9e7e9)
I/flutter (22090): Stock build: 2530.0 µs per iteration

I messed it up pretty bad... 
Will dig more

**Comment by xster** [comment]
Thought firehose:
The StocksAppState's build() function went from 27µs to 38µs per iteration. 
There's definitely other stuff going on here.

**Comment by xster** [comment]
Semi-scientifically breaking up each average frame time:
Animate: 0.68ms before, 0.54ms after. Noise.
Layout: 3.78ms before, 5.34ms after. Messed up.
⤷ Build: 1.6ms before, 1.43ms after. 
Paint: 0.79ms before, 0.81ms after. Not impactful.

So if I can make a leap here, the problem is probably not the various new calls to .of statics. But something else is going on during layout than the build() changes.

**Comment by xster** [comment]
May have found some stuff. The previous post's data is actually a bit flawed. Forgot to run --profile and I was just manually scrolling around the app so it might not reflect the exact same behaviour. 

Running the same microbenchmark on --profile. 

Before:
Per frame: 1449µs
Build: 1050µs
Compositing: 236µs

After:
Per frame: 2951µs
Build: 1686µs
Compositing: 254µs
Semantics: 692µs

The increase in build and semantics mostly account for the per frame cost difference. 

Though the new Theme StatelessWidget's build() cost is mostly negligible at 5µs per frame. 

IconTheme.merge being called ~15 times per frame in the stocks app is maybe improvable but also not that big at 60µs per frame. 

Still more going on.

**Comment by xster** [comment]
oh I'm dumb. Found it.

Theme the InheritedWidget used to compare ThemeData for updateShouldNotify. 
_InheritedTheme the new InheritedWidget is comparing Theme the StatelessWidget which is always different. 

![screen shot 2017-05-25 at 1 37 40 am](https://cloud.githubusercontent.com/assets/156888/26442795/ce11cbcc-40ea-11e7-8e12-5347e99007e9.png)

The new block is new and always there, triggered by _InheritedTheme causing a dispatchDidChangeDependencies.

**Comment by xster** [comment]
Woohoo, I think it worked
![screen shot 2017-05-31 at 12 32 54 pm](https://cloud.githubusercontent.com/assets/156888/26650130/4db5fa26-45fd-11e7-9b79-569402b2f114.png)
