### ISSUE TITLE
Espresso plugin error

### ISSUE THREAD

**Issue by j20mc** [flutter/flutter#102514]
Hello, I have a problem with the espresso plugin. https://github.com/flutter/plugins/tree/main/packages/espresso

- when I run the command line ./gradlew app:connectedAndroidTest I have this error:

```
Starting 1 tests on ONEPLUS A6003 - 11

*************.MainActivityTest > checkButton[ONEPLUS A6003 - 11] FAILED 
        java.lang.RuntimeException: java.util.concurrent.ExecutionException: androidx.test.espresso.flutter.internal.protocol.impl.FlutterProtocolException: Flutter testing APIs not registered with Dart isolate isolates/534430309763143.
        at androidx.test.espresso.flutter.EspressoFlutter$WidgetInteraction$ExceptionPropagator.<init>(EspressoFlutter.java:179)

> Task :app:connectedDebugAndroidTest FAILED
```

```
import static androidx.test.espresso.flutter.EspressoFlutter.onFlutterWidget;
import static androidx.test.espresso.flutter.action.FlutterActions.click;
import static androidx.test.espresso.flutter.action.FlutterActions.syntheticClick;
import static androidx.test.espresso.flutter.assertion.FlutterAssertions.matches;
import static androidx.test.espresso.flutter.matcher.FlutterMatchers.isDescendantOf;
import static androidx.test.espresso.flutter.matcher.FlutterMatchers.withText;
import static androidx.test.espresso.flutter.matcher.FlutterMatchers.withTooltip;
import static androidx.test.espresso.flutter.matcher.FlutterMatchers.withType;
import static androidx.test.espresso.flutter.matcher.FlutterMatchers.withValueKey;
import static com.google.common.truth.Truth.assertThat;
import static org.junit.Assert.fail;

import androidx.test.core.app.ActivityScenario;
import androidx.test.espresso.flutter.EspressoFlutter.WidgetInteraction;
import androidx.test.espresso.flutter.assertion.FlutterAssertions;
import androidx.test.espresso.flutter.matcher.FlutterMatchers;
import androidx.test.ext.junit.runners.AndroidJUnit4;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;

/** Unit tests for {@link EspressoFlutter}. */
@RunWith(AndroidJUnit4.class)
public class MainActivityTest {

    @Before
    public void setUp() throws Exception {
        ActivityScenario.launch(MainActivity.class);
    }

    @Test
    public void checkButton() {
        onFlutterWidget(FlutterMatchers.withValueKey("btnConnection"))
        .check(FlutterAssertions.matches(FlutterMatchers.isExisting()));
    }
}
```

- and if i use this line ./gradlew app:connectedAndroidTest -Ptarget=`pwd`/../test_driver/example2.dart 

`* What went wrong:
Task '*********/android/../test_driver/example2.dart' not found in root project 'android'.`

```
// Copyright 2013 The Flutter Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

import 'package:******/main.dart' as app;
import 'package:flutter_driver/driver_extension.dart';

void main() {
  enableFlutterDriverExtension();
  app.main();
}
```

![Capture d’écran 2022-04-25 à 17 44 27](https://user-images.githubusercontent.com/61017929/165125096-a176548d-ea58-44d7-b047-edf387f60f00.png)

This is an application that is in production. I would like to run automated tests but I don't see any documentation.

```
dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation platform('com.google.firebase:firebase-bom:26.5.0')
    implementation 'com.google.firebase:firebase-analytics:17.2.2'
    implementation 'com.google.firebase:firebase-messaging'
    testImplementation 'junit:junit:4.12'
    testImplementation "com.google.truth:truth:1.0"
    androidTestImplementation 'androidx.test:runner:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.1'
    api 'androidx.test:core:1.2.0'
}
```

**Comment by darshankawar** [comment]
@j20mc 
Thanks for the report. I tried the plugin [example](https://github.com/flutter/plugins/tree/main/packages/espresso/example) and ran it using below command:

`dhs@Dhss-MacBook-Pro android % ./gradlew app:connectedAndroidTest -Ptarget=`pwd`/../test_driver/example.dart`

Which ran properly without any issues. Can you try the same by running the same example ?

As the error you are getting says `Flutter testing APIs not registered with Dart isolate` indicating You need to enable the test extensions from Dart as described in the section starting "You'll need to create a test app that enables the Flutter driver extension."

And other error `What went wrong: Task '*********/android/../test_driver/example2.dart' not found in root project 'android'.` seems to be related to folder structure of hierarchy. Please check the plugin example structure and see if you are missing anything from it.

**Comment by j20mc** [comment]
Hello, I understood what was wrong with the integration of this plugin with my project.

- First the command line alone: ​​`./gradlew app:connectedAndroidTest`

always returns the same error even with the example project of the plugin, so you have to delete this message in this page:

https://github.com/flutter/plugins/tree/main/packages/espresso/example

- For the second it works perfectly in the example of the plugin. So I compared and everything was the same except that my project was not in a parent android project like this:
<img width="776" alt="Capture d’écran 2022-04-26 à 13 46 24" src="https://user-images.githubusercontent.com/61017929/165301074-7e155c90-3fc5-4da7-8634-7ee74ac1f3e6.png">

`not found in root project 'android'`

But more like this

<img width="776" alt="Capture d’écran 2022-04-26 à 14 35 17" src="https://user-images.githubusercontent.com/61017929/165300990-543c94b6-fbb3-4d0c-9bc6-bf2acdac6342.png">

- Last question, do we have documentation for the different test functions. because I can't find how to fill a textField (typically enter a login & password)

```
 @Before
    public void setUp() throws Exception {
        ActivityScenario.launch(MainActivity.class);
    }

    @Test
    public void checkButton() {
        onFlutterWidget(FlutterMatchers.withValueKey("btnConnection"))
        .check(FlutterAssertions.matches(FlutterMatchers.isExisting()));
    }

    @Test
    public void performSyntheticClick() {
         onFlutterWidget(withValueKey("textFieldEmail")).perform(click());
         onFlutterWidget(withValueKey("textFieldPassword")).perform(click());
        WidgetInteraction interaction =
            onFlutterWidget(withValueKey("btnConnection")).perform(syntheticClick());
        assertThat(interaction).isNotNull();
    }
```

I manage to make clicks but when I test with replaceText or typeText, I have a java error

**Comment by darshankawar** [comment]
Good to know you were able to resolve the errors.
For the issues you pointed out related to documentation, I suggest you to open a new issue by providing what all things you would to include in the plugin documentation, so that we can track it properly.

Closing this, since your original issues have been resolved.
