### ISSUE TITLE
Scribble (handwriting) input not working on iPad

### ISSUE THREAD

**Issue by mattrussell-sonocent** [flutter/flutter#102561]
## Steps to Reproduce

1. Execute `flutter run` on the code sample, running on a connected iPad.
2. Ensure iPad has Scribble enabled.
3. Attempt to write with an Apple Pencil in the text field.

**Expected results:** Handwriting to appear above field, then be converted into text. Flutter has added support for this feature in https://github.com/flutter/flutter/pull/97437.

**Actual results:** No handwriting shown. 

Scribble input does work on other applications.

I've tested this in a couple of iPads with a couple of Apple Pencils (1st and 2nd generation) with the same results.
iOS: 15.4.1
iPad: 6th generation

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: Scaffold(
        body: TextField(),
      ),
    );
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```
Launching lib/main.dart on Matthew’s iPad in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: QV24J58JX6
Running Xcode build...
Xcode build done.                                            6.7s
Installing and launching...
Debug service listening on ws://127.0.0.1:50386/d0bqGPAtTn4=/ws
Syncing files to device Matthew’s iPad...
iomfb_match_callback: primary
API error: <_UIKBCompatInputView: 0x102b5e280; frame = (0 0; 0 0); layer = <CALayer: 0x280d33140>> returned 0 width, assuming UIViewNoIntrinsicMetric
API error: <_UIKBCompatInputView: 0x102b5e280; frame = (0 0; 0 0); layer = <CALayer: 0x280d33140>> returned 0 width, assuming UIViewNoIntrinsicMetric
```

```
[✓] Flutter (Channel stable, 2.10.5, on macOS 12.2.1 21D62 darwin-arm, locale en-GB)
    • Flutter version 2.10.5 at /Users/matt/fvm/versions/2.10.5
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (8 days ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/matt/Library/Android/sdk
    • Platform android-32, build-tools 32.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.66.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • Matthew’s iPad (mobile) • 064430975331d329deb3b08ecc5699b823bc98a7 • ios            • iOS 15.4.1 19E258
    • Chrome (web)            • chrome                                   • web-javascript • Google Chrome 100.0.4896.127

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @mattrussell-sonocent, the tag for the linked PR shows that it's available in `2.12.0-4.0.pre` and above, which is likely why it isn't working on stable. Can you switch to the `master` or `beta` branch to see if this works for you? 

To switch branches, run the following commands

```
flutter channel master/beta
flutter upgrade
```

Thank you

**Comment by mattrussell-sonocent** [comment]
> Hi @mattrussell-sonocent, the tag for the linked PR shows that it's available in `2.12.0-4.0.pre` and above, which is likely why it isn't working on stable. Can you switch to the `master` or `beta` branch to see if this works for you?

Thanks - I'll try it on a later version.

I had assumed it was present in 2.10 based off this page: https://docs.flutter.dev/release/breaking-changes/scribble-text-input-client

![image](https://user-images.githubusercontent.com/45822724/165284858-dc43b81c-3b94-4933-8cf5-7c6791124f19.png)

**Comment by mattrussell-sonocent** [comment]
I can confirm this works in the latest beta version (`2.13.0-0.2.pre`).

**Comment by mattrussell-sonocent** [comment]
> the tag for the linked PR shows that it's available in `2.12.0-4.0.pre` and above,

@danagbemava-nc Just to help me in future to understand which things have landed in which versions, is there a place I can see that information in the Pull Request?

**Comment by danagbemava-nc** [comment]
> @danagbemava-nc Just to help me in future to understand which things have landed in which versions, is there a place I can see that information in the Pull Request?

Hi @mattrussell-sonocent, see https://github.com/flutter/flutter/wiki/Where%27s-my-Commit%3F for information on that. 

Given that this is working in the beta version, it's likely that this should roll out to stable some time in the future. 

Closing as fixed. 

Thank you

**Comment by mattrussell-sonocent** [comment]
Thanks - oddly I don't see the version tags when I look at the PR in Github:

![image](https://user-images.githubusercontent.com/45822724/165291958-d0c72a89-c12d-4a50-a2ae-9b60d4de3232.png)

Is there some kind of permissions restriction in place for who can view them?

**Comment by danagbemava-nc** [comment]
It looks like only members can see it. However, you can still view it by following the video below

https://user-images.githubusercontent.com/88313112/165292888-a199f5d6-29f5-411e-b9b2-d30da090f170.mov

**Comment by mattrussell-sonocent** [comment]
> It looks like only members can see it. However, you can still view it by following the video below

Thanks, ace.
