### ISSUE TITLE
Would like support for dependent plugins

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#10252]
Unclear if this works today.

@lukef is attempting to write a permission-helper plugin so he can handle the dance of getting permissions on iOS and Android.

He'd like to then be able to use this plugin from another plugin (as it would make writing an image-capture plugin trivial, since you'd use this other plugin to handle the ask-for-the-camera-permission dance).

If this is possible, would be nice to have an example.

**Comment by mit-mit** [comment]
This did indeed work, and @mravn-google updated docs in https://github.com/flutter/website/pull/660. Closing.
