### ISSUE TITLE
[Flutter Web] flavor option not found

### ISSUE THREAD

**Issue by AbhishekDoshi26** [flutter/flutter#102587]
## Summary
Why do we don't have flavor option when we build for web? When I run the following:
```
flutter build web --target=lib/main_development.dart --flavor=development
```
It throws error:
```
Could not find an option named "flavor".


Run 'flutter -h' (or 'flutter <command> -h') for available flutter commands and options.
```

Ofcourse this works when I replace `web` with `apk`.
## Steps to Reproduce

1. Create a new flutter project and add flavours to it (Even if you don't add it's not an issue as the param `flavor` is not recognised).
2. Run `flutter build web --target=lib/main.dart --flavor=development `
3. Woila! Get an error.

**Expected results:** The `flavor` option should be available for web.

**Actual results:** `flavor` option is not available.

<details>
  <summary>Logs</summary>

```
Analyzing test_project...                                               
No issues found! (ran in 1.7s)
```

```
abhishekdoshi@Abhisheks-MacBook-Pro test_project % flutter doctor -v
[✓] Flutter (Channel stable, 2.10.5, on macOS 12.3.1 21E258 darwin-arm, locale en-GB)
    • Flutter version 2.10.5 at /Users/abhishekdoshi/Desktop/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (8 days ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/abhishekdoshi/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.66.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.39.20220405

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 100.0.4896.127

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
@AbhishekDoshi26 
Flutter web doesn't support `flavor` feature yet and there doesn't seem to be any plan to do so in near future. Please see [this](https://github.com/flutter/flutter/issues/59388#issuecomment-644202660) issue comment and [this](https://github.com/flutter/flutter/issues/59388#issuecomment-796060509) alternate solution and see if it works for your case. 

Having said that, the `Could not find an option named "flavor".` message while trying to add `flavor` for building web could be misleading. 

Closing this issue as this is WAI and web platform doesn't support that feature.

**Comment by AbhishekDoshi26** [comment]
I agree @darshankawar but now if we don’t have flavors in web (which I already supposed because we don’t add any configuration for web the way we add in Manifest :)) then how does it run in debug mode with flavors?

Just curious.
