### ISSUE TITLE
[url_launcher] Direct Phone Call ?

### ISSUE THREAD

**Issue by imeDevelopers** [flutter/flutter#102524]
Can you please & why don't you add [This Feature](https://pub.dev/packages/flutter_phone_direct_caller) !?

Thanks.

**Comment by stuartmorgan** [comment]
`url_launcher` is a plugin for launching URLs; any other functionality is out of scope. If you are looking for functionality that involves performing actions within your application instead of handing off to other applications via URLs, we encourage you to find plugins that address your use case.
