### ISSUE TITLE
Handle Expiration of auto renewable subscription

### ISSUE THREAD

**Issue by harikrishnanvr1511** [flutter/flutter#102645]
I am not able to handle the expiration of auto renewable subscription in flutter application.
I am not able to find any functions to get the purchase details of the user when ever i need.

**Comment by harikrishnanvr1511** [comment]
I am not able to handle the expiration of auto renewable subscription in flutter application.

**Comment by darshankawar** [comment]
@harikrishnanvr1511 
What platform are you seeing this on ? Are you experiencing this using sandbox account ?
Are auto-renewable subscriptions not expiring or are they ?




> I am not able to find any functions to get the purchase details of the user when ever i need.

This seems to be another question separate from expiration of auto renewables.

Also, can you provide `flutter doctor -v`, plugin version along minimal code sample that shows both the behaviors you reported ?

**Comment by harikrishnanvr1511** [comment]
> @harikrishnanvr1511 What platform are you seeing this on ? Are you experiencing this using sandbox account ? Are auto-renewable subscriptions not expiring or are they ?
> 
> > I am not able to find any functions to get the purchase details of the user when ever i need.
> 
> This seems to be another question separate from expiration of auto renewables.
> 
> Also, can you provide `flutter doctor -v`, plugin version along minimal code sample that shows both the behaviors you reported ?
I am solving this using google play api in android and apple store api in ios, flutter doesn't provide any functions to handle these situations

**Comment by darshankawar** [comment]
> Are auto-renewable subscriptions not expiring or are they ?



> not able to find any functions to get the purchase details of the user when ever i need.

Can you provide a sample use case / code sample that shows the current limitation you are reporting ?

**Comment by harikrishnanvr1511** [comment]
after subscription, if i close the app and opens the app, there are no api s for me to get the current status of the purchase,
For example I subscribed for an auto-renewable subscription from my app and after one month i want to check whether its status is okay?
What should I do in such cases?

**Comment by darshankawar** [comment]
Check [this](https://stackoverflow.com/questions/54911966/flutter-how-to-check-that-autorenewal-subscription-is-still-valid) SO link and see if it helps to answer your question.
