### ISSUE TITLE
[Pub] Host packages on Gitea and Gitlab

### ISSUE THREAD

**Issue by trymeouteh** [flutter/flutter#102671]
The ability for a developer to host the source code of their package on a gitea instance or a gitlab instance and not be restricted to github.

**Comment by stuartmorgan** [comment]
Issues related to pub need to be filed against [the pub project](https://github.com/dart-lang/pub), as it in not part of Flutter itself.

(When filing there, you should provide more details; it's not clear what restriction you are referring to here; pub.dev doesn't enforce a hosting requirement, and there are published packages whose source is in GitLab, for instance.)
