### ISSUE TITLE
[CP] M3 AppBar support

### ISSUE THREAD

**Issue by darrenaustin** [flutter/flutter#102697]
### issue_link

https://github.com/flutter/flutter/issues/92093

### Commit Hash

14a9b4a7512c9bc40d0417672a87276bd48df2ad

### Target

beta

### Impacted Users

Apps that are opting into Material 3.

### Impact Description

This change should have no impact on existing apps, but provides opt-in support for the Material 3 design of App Bars.

### Workaround

There is nothing really to work around, but if apps wanted to support the M3 look for AppBars they would have to do a lot of work to the existing AppBar to make it happen.

### Risk

low

### Test Coverage

yes

### Validation Steps

This should already be covered by the automated tests (and I ran this against all the internal tests as well). To manually check this, if you just bring up the counter example the app bar should look like a normal Material 2 app bar (i.e. blue background with white text). If you add `useMaterial3: true` to the `ThemeData` used by the counter app it should switch to a white background with black text.

**Comment by itsjustkevin** [comment]
@HansMuller

**Comment by CaseyHillers** [comment]
Landed in last weeks hotfix https://github.com/flutter/flutter/pull/103101
