### ISSUE TITLE
[url_launcher] [web] Does not properly handle "lightning:" scheme

### ISSUE THREAD

**Issue by jtmuller5** [flutter/flutter#102608]
The url_launcher package says that it supports several different URL schemes depending on the platform and installed apps (mailto:<email>, tel:<phone number>, sms:<phone number>). 

I am building an app that should be able to open apps that support bitcoin lightning transactions. The scheme for these is lighting:<encoded invoice>.

Here is an example of a [website](https://www.plebpay.com/) that lets users click on a QR code and open a lighting wallet chrome extension ([code](https://github.com/SamSamskies/PlebPay)). The chrome extension is called [Strike](https://chrome.google.com/webstore/detail/strike-bitcoin-payments/ddlakobiikmpnaeakgbdeodclnmiablf).

When I Iaunch lighting:#### from the above website, the Strike chrome extension opens with the invoice.

When I try to use url_launcher to launch lightning:#### in my Flutter web app (with the Strike chrome extension installed), a new blank tab is opened and I get the following error in my console:

`Failed to launch 'lightning:lnbc78490n1p3xs7p9pp5gvjlywtlc4ergxefka5makye9u......4sp5mj8emnaeghuqaszqqns9evlzhnpxgk05yadrxd6j4kajz2sthtqq9qyyssqxjdd7e9lh8524schanjqctg52v6plrqejgh40xllzr8526gtyprq4f24mk5atkuvl20y786wzh6efutgnx5h5rsjkqp76zk3593u0fcqm9qmsy' because the scheme does not have a registered handler.`

If I run the same app on a mobile device (Android or iOS) and I have the strike app installed, the Strike app opens properly when I launch lighting:####. So the scheme seems correct but for some reason Flutter web doesn't know how to handle it.

## Steps to Reproduce

Reproducing this might be a lengthy process since you need:
- A Flutter web app that can access chrome extensions
- An [API key from Strike](https://developer.strike.me/en/)
- My [Strike](https://pub.dev/packages/strike) package 
- The Strike chrome extension

You can find an example app in the example folder [here](https://github.com/jtmuller5/strike)

1. Run the app in a browser with the Strike chrome extension installed
2. Create a new invoice
3. Click on the new invoice
4. Click "Create Quote"
5. Click "Open Strike"

**Expected results:** 
The Strike chrome extension should open in a little popup window (see how this works on [plebpay](https://www.plebpay.com/))

**Actual results:** 
A blank screen opens and the console says "the scheme does not have a registered handler."

<details>
<summary>Code sample</summary>

You can find an example app in the example folder [here](https://github.com/jtmuller5/strike)

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

[√] Flutter (Channel stable, 2.10.3, on Microsoft Windows [Version 10.0.22543.1000], locale en-US)
    • Flutter version 2.10.3 at H:\Mullr\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (8 weeks ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at D:\Android
    • Platform android-32, build-tools 32.1.0-rc1
    • ANDROID_HOME = D:\Android
    • ANDROID_SDK_ROOT = D:\Android
    • Java binary at: H:\Downloads\android-studio-2021.1.1.11-windows\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Build Tools 2019 16.8.5)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
    • Visual Studio Build Tools 2019 version 16.8.31005.135
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 2021.1)
    • Android Studio at D:\Android 2021.1.1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] Android Studio (version 2021.1)
    • Android Studio at H:\Downloads\android-studio-2021.1.1.11-windows\android-studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] Connected device (4 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Windows (desktop)                  • windows       • windows-x64    • Microsoft Windows [Version 10.0.22543.1000]
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 100.0.4896.127
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 100.0.1185.50

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```
```

</details>

**Comment by maheshmnj** [comment]
Hi @jtmuller5, Thanks for filing the issue. In order to launch the lightning URL successfully, The device need to have a lightning scheme handler ( The app that can handle that URL)  as mentioned in the docs

> URL schemes are only supported if there are apps installed on the device that can support them.

Also, try adding queries (I haven't tried this)

```
<intent>
      <action android:name="android.intent.action.VIEW" />
      <data android:scheme="lightning" />
    </intent>
```

However, the scheme you are referring to seems uncommon, so I am quite not sure if this is currently possible. Labeling this issue for further insights from the team.

**Comment by jtmuller5** [comment]
Thanks, @maheshmnj.

I'd like to point out a few things:
- This seems to work fine on a mobile device with apps that can handle lighting schemes. For example, if I launch('lightning:###') on my Android, it takes me directly to the payment screen in the Strike app
- If I add 'lightning:####' to an href in a regular old web page and click on it, that also works. The Strike chrome extension opens in a pop up

It seems like Flutter Web is having a hard time passing the scheme to the browser.

Do Flutter Web apps need special permission to launch/open browser extensions?

**Comment by jtmuller5** [comment]
The interesting thing is that when I create an HtmlElementView with the AnchorElement, the link opens correctly (ie. the Strike browser extension opens).

For reference:
```dart
Widget build(BuildContext context, HomeViewModel model) {
    if (model.genQuote != null) {
      String intent = 'lightning:${model.genQuote!.quoteId}';

      final NodeValidatorBuilder _htmlValidator = NodeValidatorBuilder.common()..allowElement('button', attributes: ['style']);

      // ignore: undefined_prefixed_name
      ui.platformViewRegistry.registerViewFactory(
        intent,
        (int viewId) => AnchorElement(href: intent)
          ..setInnerHtml(
              '<button style="border-radius: 25px; '
              'height: 50px; '
              'width: 200px; '
              'background-color: #EEFF41; '
              'font-size: 24px; cursor:pointer;" >Send</button>',
              validator: _htmlValidator),
      );

      return SizedBox(width: 200, height: 50, child: HtmlElementView(viewType: intent));
    } else {
      return const SizedBox.shrink();
    }
  }
```

**Comment by maheshmnj** [comment]
> This seems to work fine on a mobile device with apps that can handle lighting schemes

Thanks for the clarification

> It seems like Flutter Web is having a hard time passing the scheme to the browser.

> Do Flutter Web apps need special permission to launch/open browser extensions?

I am quite not sure about this or if it is possible as of today, Lets wait for the secondary triage's input on this.

**Comment by stuartmorgan** [comment]
> Here is an example of a [website](https://www.plebpay.com/) that lets users click on a QR code [...] When I Iaunch lighting:#### from the above website, the Strike chrome extension opens with the invoice.
> 
> When I try to use url_launcher to launch lightning:#### in my Flutter web app (with the Strike chrome extension installed), a new blank tab is opened and I get the following error in my console:

It seems like you're comparing two very different things here; you're describing this as a link in the case that works, whereas your Flutter test case is using `launchUrl`, which tried to directly navigate the browser. Does using a `Link` widget work?

If so, this sounds like a limitation in the extension, not `url_launcher` or Flutter.

**Comment by stuartmorgan** [comment]
It sounds like this is a limitation with the Chrome extension you mentioned then, rather than a Flutter issue, so closing.
