### ISSUE TITLE
SliverAppBar shadow is not transparent when background color is

### ISSUE THREAD

**Issue by Solido** [flutter/flutter#10267]
## Steps to Reproduce

Create a CustomScrollView with 
```dart 
new SliverAppBar(
                  title: new Text('Bar'),
                  pinned: true,
                  snap: false,
                  floating: false,
                  backgroundColor: new Color.fromRGBO(0, 0, 0, 0.0),
```

<img width="319" alt="screen shot 2017-05-23 at 13 15 22" src="https://cloud.githubusercontent.com/assets/1295961/26352059/601d719c-3fba-11e7-9473-053b16502cbb.png">

Thanks.

**Comment by eseidelGoogle** [comment]
Looks like that's the shadow behind the AppBar.  You might try changing the elevation parameter?
https://docs.flutter.io/flutter/material/SliverAppBar-class.html

**Comment by Solido** [comment]
It worked ! a posteriori the link between shadow and elevation is now clear to me.
Maybe put a note on the documentation of elevation property ? 
Thx.

**Comment by Hixie** [comment]
I'll totally add

**Comment by Hixie** [comment]
I'll totally add some documentation for this. I'm confused about two things that I'm helping you can explain to me to help me write the docs:

1. What did you think `elevation` was for, before you understood it was about shadows? (Knowing this will help me write the text in a way that avoids this confusion in the future.)

2. What is it you think is explained in SliverAppBar that is missing in AppBar, which would apply to the AppBar version of `elevation`?

**Comment by Solido** [comment]
1. To better understand elevation one must understand the Material Design philosophy. 
Coming from a Java/Javascript world when you paint on a canvas you decide to add a filter to work with shadow and it has nothing to do with the Z index. 
In Material design elevation is not a Z index, it's truly like the name stand the elevation/altitude of one block of matter that drop a shadow.

Because sometimes ago I was on this page https://material.io/guidelines/material-design/elevation-shadows.html#elevation-shadows-elevation-android 
I can now have a mental schema.

2. If you dig on SliverAppBar you'll find 

`
forceElevated → bool
Whether to show the shadow appropriate for the elevation even if the content is not scrolled under the AppBar.
`
which make the link evident.

But on AppBar you can only find
`elevation → double
The z-coordinate at which to place this app bar.
`
At best using the browser search in page you will find kElevationToShadow which is a hint of a potential link

**Comment by Solido** [comment]
Know it's clear that this is not a bug at all even if I would stand that if we respect the Material Design philosophy and behavior of matter a transparent matter cannot cast shadow. So maybe shadow opacity should have some link with color opacity. In this case having a background color with zero opacity will lead to invisible shadow because changing elevation to correct the shadow cast is just a trick. My bar contains a block of matter that is truly over the block scrolled under not same elevation.

**Comment by Solido** [comment]
Best demonstration of this case is Google Allo AppBar.
I've no idea if the AppBar shadow is animated or only the background color.

**Comment by Hixie** [comment]
I've got a patch which mentions that 'elevation' is about 'shadows'.

I don't think we will make the shadows aware of the background color in the near future, though that is something we definitely think would be cool in principle.

I'm going to close this bug once I land the shadow/elevation clarification. We'll track the more realistic shadow processing as a separate work item.

**Comment by yy1300326388** [comment]
```
appBar: new AppBar(
  backgroundColor: Colors.transparent,
  elevation: 0.0,
)
```
