### ISSUE TITLE
[flutter_markdown] Flutter markdown does not handle multiple new lines

### ISSUE THREAD

**Issue by jpiabrantes** [flutter/flutter#102668]
```dart
const data = '''**Presenting my issue**



This text should be rendered after multiple line breaks.
''';
```
`Markdown(data: data)` renders the following:

**Presenting my issue**
This text should be rendered after multiple line breaks.

**Comment by maheshmnj** [comment]
Hi @jpiabrantes, Thanks for filing the issue. Wouldn't adding <br> for line breaks help you achieve the desired result?

**Comment by nosmirck** [comment]
> 

Html tags are not supported on flutter_markdown, `<br/>` won't work.

**Comment by maheshmnj** [comment]
Thanks for the clarification @nosmirck, 

I tried the below code sample `<br/>` or `<br />` isn't working for markown plugun. But `<br />` works 
fine here https://dart-lang.github.io/markdown/.

Labeling this issue as a valid feature request.

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter_markdown/flutter_markdown.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);
  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    const data = '''**Presenting my issue**
<br/>
<br/>
<br/>
This text should be rendered after multiple line breaks.
''';
    return Scaffold(
        appBar: AppBar(
          title: Text(widget.title),
        ),
        body: const Markdown(data: data));
  }
}

```
</details>

**Comment by nosmirck** [comment]
That sucks! but, I found a workaround that works.

@jpiabrantes try this:

```dart
Markdown(data:
'''
text
ㅤ
ㅤ
separated
''');
```

The blank space you see there is actually an invisible character!, you can copy it from here: https://invisibletext.com/

**Comment by jpiabrantes** [comment]
thank you @nosmirck that works!

@stuartmorgan flutter's position is that adding newlines is not an important feature and if we want to do it we should come up with hacks?

**Comment by stuartmorgan** [comment]
> @stuartmorgan flutter's position is that adding newlines is not an important feature

The Flutter team doesn't control the markdown spec.
