### ISSUE TITLE
[Pub] Self Host & Add/Import 3rd Party Repositories

### ISSUE THREAD

**Issue by trymeouteh** [flutter/flutter#102670]
The ability to for an individual, company, group or organisation to self host their own pub package repository and the ability to add/import repositories into the pub package manager.

- Fully open sourcing the pub package server (If it is not yet open source)
- Instructions on how to self host a pub package server
- Adding the ability in the pub package manager client to add/import other repositories
- Making it distinct on what packages in the pub package manager client are from

**Comment by stuartmorgan** [comment]
Issues related to pub need to be filed against [the pub project](https://github.com/dart-lang/pub), as it in not part of Flutter itself.
