### ISSUE TITLE
[path_provider] VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method getApplicationDocumentsDirectory on channel plugins.flutter.io/path_provider_ios) 

### ISSUE THREAD

**Issue by chitgyi** [flutter/flutter#102624]
`
VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method getApplicationDocumentsDirectory on channel plugins.flutter.io/path_provider_ios)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:175:7)
<asynchronous suspension>
#1      getApplicationDocumentsDirectory (package:path_provider/path_provider.dart:115:24)
<asynchronous suspension>
`

## Step Procedure
- Setup Flutter Moudule
- Integrate with iOS Native App
- Crash Error when navigate to flutter app from iOS

> There is no error when running standalone flutter module

**Comment by danagbemava-nc** [comment]
Hi @chitgyi, please provide a complete minimal reproducible code sample as well as the output of `flutter doctor -v`. 

Can you also take a look at https://github.com/flutter/samples/tree/master/add_to_app/plugin to see if you have implemented the module correctly?

Thank you

**Comment by chitgyi** [comment]
Thank you @danagbemava-nc I got it.
