### ISSUE TITLE
Emit warning when `flutter` CLI is invoked on Windows 7/8.x hosts

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#102607]
We only officially support Windows 10 hosts.  Let's emit a warning to that effect when developers invoke the Flutter CLI on older Windows hosts.

**Comment by FusoraTech** [comment]
> We only officially support Windows 10 hosts.

Also update the docs as in https://docs.flutter.dev/desktop#additional-windows-requirements

**Comment by christopherfujino** [comment]
> > We only officially support Windows 10 hosts.
> 
> Also update the docs as in https://docs.flutter.dev/desktop#additional-windows-requirements

I believe that is for desktop *target* device, whereas this issue is tracking desktop host device. Confusingly, we support building for older windows targets than we support development on.

**Comment by christopherfujino** [comment]
cc @eliasyishak

**Comment by christopherfujino** [comment]
per offline discussion, I think the best solution here would be to hard-code a minimum supported Windows OS version, and have the doctor error when the current version is lower.

**Comment by eliasyishak** [comment]
Identified a command that can be run in windows to determine OS Version for windows
`systeminfo | findstr /C:"OS Version:" /B` 

`/C`: look for entire string between quotes
`/B`: look for matches from the beginning of the line

Using the `systeminfo` and `findstr` (filtering) built in tools to get information about the host system returned.

Snippet shown below running on CloudTop windows VM.
<img width="497" alt="Screen Shot 2022-08-05 at 4 20 38 PM" src="https://user-images.githubusercontent.com/42216813/183156967-1684e6f1-e48d-43a2-b07d-0f302327de4b.png">

Will need to test across different versions of windows to determine if output follows the same return schema.

**Comment by christopherfujino** [comment]
> Identified a command that can be run in windows to determine OS Version for windows `systeminfo | findstr /C:"OS Version:" /B`

Will this pattern matching work across different locales?

**Comment by christopherfujino** [comment]
We actually already have logic for this https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/base/os.dart#L118 (that particular method does not check the version, but it looks like it gets overridden in the platform-specific sub-classes that do query the OS for exact version)

**Comment by eliasyishak** [comment]
Ah of course, should’ve taken a look at what was available within the OS code. Well then I can pivot to using existing code already to add this validator assuming that version number exists.

**Comment by christopherfujino** [comment]
> Ah of course, should’ve taken a look at what was available within the OS code. Well then I can pivot to using existing code already to add this validator assuming that version number exists.

You probably still want to investigate whether that produces consistent output on Windows 7/8.
