### ISSUE TITLE
Mac/android arm64 builders complain no android `mac-arm64@version:31v8`

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#102605]
https://github.com/flutter/flutter/pull/102589 enabled `mac/android` arm64 tests in post-submit as `bringup: true`.

These tests have been passing in staging with android_sdk `version:31v1`, and are complaining no `version:31v8`:
https://ci.chromium.org/ui/p/flutter/builders/staging/Mac_arm64_android%20integration_test_test/1/overview

@GaryQian Could you help push a new `version:31v8` for mac-arm64?

**Comment by GaryQian** [comment]
Yeah, I can push a 31v8 for arm64. The current situation is that mac-arm64 is the same package as mac-amd64, so ill re-upload it with a different tag.

I should modify the script to do this as well.

**Comment by GaryQian** [comment]
https://chrome-infra-packages.appspot.com/p/flutter/android/sdk/all/mac-arm64/+/version:31v8

**Comment by keyonghan** [comment]
Validated this works. Thanks @GaryQian !
