### ISSUE TITLE
[flutter_markdown] bold is not working for questions

### ISSUE THREAD

**Issue by jpiabrantes** [flutter/flutter#102669]
```
data = '**This is not a question**';

Markdown(data:data);
```

This outputs the sentence in bold: **This is not a question**

```
data = '**This is a question?**';

Markdown(data:data);
```

This outputs the following \*\*This is a question?\*\*

**Comment by darshankawar** [comment]
@jpiabrantes 

Using `data = '**This is not a question**';`, it shows:

<img width="320" alt="Screenshot 2022-04-28 at 12 31 17 PM" src="https://user-images.githubusercontent.com/67046386/165695844-c907bba5-b8d1-481c-a919-93b221c386ab.png">


Using `data = '**This is a question?**';`, it shows:

<img width="291" alt="Screenshot 2022-04-28 at 12 32 21 PM" src="https://user-images.githubusercontent.com/67046386/165695892-8319cf74-c552-4451-8c9a-5e9d3f85d506.png">

What's the expected output you are looking for for latter scenario ?

<details>
<summary> runnable code sample </summary>

```

import 'package:flutter/material.dart';
import 'package:flutter_markdown/flutter_markdown.dart';

const String _markdownData = '**This is a question?**';

void main() {
   runApp(
     MaterialApp(
       title: "Markdown Demo",
       home: Scaffold(
         appBar: AppBar(
           title: const Text('Simple Markdown Demo'),
         ),
         body: SafeArea(
           child: Markdown(
             data: _markdownData,
           ),
         ),
       ),
     ),
   );
 }

```

</details>

**Comment by jpiabrantes** [comment]
Ah yes, I can't also reproduce the issue when using single quotes. This is what happens when I use triple quotes:

```dart
const rules = """**This is a question?**

**This is a question?**

**This is a question**
""";
```

<img width="173" alt="Screenshot 2022-04-28 at 09 39 43" src="https://user-images.githubusercontent.com/2369107/165713154-fa5d301a-553d-4523-a7e1-02d7d5ce89c1.png">
