### ISSUE TITLE
Add support for TextInputType.email

### ISSUE THREAD

**Issue by markmooibroek** [flutter/flutter#10268]
It would be nice if you were to add a TextInputType dedicated for email text input.
Now supported: text, phone, number, datetime

**Comment by cbracken** [comment]
Fixed in flutter/engine#3729 and flutter/flutter#10471. Also added support for URL input.

**Comment by cbracken** [comment]
Also disabled auto-capitalisation for `emailAddress` and `url` in flutter/engine#3735.
