### ISSUE TITLE
UPDATE PageController with PhotoViewGallery.builder

### ISSUE THREAD

**Issue by LlMrc** [flutter/flutter#102602]
I'm creating an app gallery. and can not update the images, I am always coming across the first image although the pagecontroller is correct, please help me to solve this issu.

         `class ViewerPage extends StatefulWidget {
              final Medium medium;
                ViewerPage({
                  Key? key,
             required this.medium,
                required this.media,
                    }) : super(key: key);
                List<Medium> media;

                   @override
                     State<ViewerPage> createState() => _ViewerPageState();
              }

                 class _ViewerPageState extends State<ViewerPage> {
                    List<String> img = [];
                  int idx = 0;

                  late PageController pageController;

                 @override
                     void initState() {
                      super.initState();
                    pageController = PageController(initialPage: idx);
                          img = widget.media.map((e) => e.id).toList();
                        }

               @override
                     Widget build(BuildContext context) {
                          return Scaffold(
     
                          body: Container(
                               alignment: Alignment.center,
                           child: widget.medium.mediumType == MediumType.image
                      ? PhotoViewGallery.builder(
                         pageController: pageController,
                      builder: (BuildContext context, int index) {
                       return PhotoViewGalleryPageOptions(
                          heroAttributes: PhotoViewHeroAttributes(
                          tag: Text(widget.medium.filename.toString())),
                      imageProvider: PhotoProvider(mediumId: img[index]));
                },
                itemCount: img.length,
                onPageChanged: onPageChanged,
              )
            : VideoProvider(
                mediumId: widget.medium.id,
              ),
              ),
           );
           }

               void onPageChanged(int index) {
                   setState(() {
                    idx = index;
                  });
                  }
              }`

I also have this error when I press the return button after displaying the photos

'' Looking up a deactivated widget's ancestor is unsafe.

At this point the state of the widget's element tree is no longer stable.

To safely refer to a widget's ancestor in its dispose() method, save a reference to the ancestor by calling dependOnInheritedWidgetOfExactType() in the widget's didChangeDependencies() method.

**Comment by darshankawar** [comment]
@LlMrc 
Your question is better suited for support channels like StackOverflow, so please ask the same there.
Closing from here as it seems to be a code implementation and code assistance issue rather than a bug in framework.
