### ISSUE TITLE
KeyUpEvent is dispatched

### ISSUE THREAD

**Issue by Nayemuzzaman** [flutter/flutter#102707]
When taking input data using TextField, sometimes the input is turned off. Does not take input and application is not worked. I gave below my textfield code and console error. If anyone encounters such a problem, please let us know how you solved it. 

Here is my code: 

```
 
Widget _entryPasswordField(String title, {bool isPassword = false}) {
    return Container(
      margin: EdgeInsets.symmetric(vertical: 20),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: <Widget>[
          Text(
            title,
            style: TextStyle(fontWeight: FontWeight.bold, fontSize: 15),
          ),
          SizedBox(
            height: 10,
          ),
          //name textfield
          Container(
            child: TextField(
              controller: passController,
              obscureText: isPassword,
              decoration: InputDecoration(
                  border: InputBorder.none,
                  fillColor: Color(0xfff3f3f4),
                  filled: true),
            ),
          ),
        ],
      ),
    );
  }

```

```
A KeyUpEvent is dispatched, but the state shows that the physical key is not pressed. If this occurs in real application, please report this bug to Flutter. If this occurs in unit tests, please ensure that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This was the event: KeyUpEvent#a1bfb(physicalKey: PhysicalKeyboardKey#70025(usbHidUsage: "0x00070025", debugName: "Digit 8"), logicalKey: LogicalKeyboardKey#00038(keyId: "0x00000038", keyLabel: "8", debugName: "Digit 8"), character: null, timeStamp: -2562047788:00:54.775808)
'package:flutter/src/services/hardware_keyboard.dart':
package:flutter/…/services/hardware_keyboard.dart:1
Failed assertion: line 441 pos 16: '_pressedKeys.containsKey(event.physicalKey)'
```
<img width="868" alt="Screen Shot 2022-04-28 at 7 54 20 AM" src="https://user-images.githubusercontent.com/12158468/165660732-a5554bfa-5b67-4786-9719-ed48d432dbdd.png">

flutter doctor -v report
<img width="896" alt="flutter doc 1" src="https://user-images.githubusercontent.com/12158468/167233768-d74c8a4b-ecae-4b29-83f8-9a99d0f8dfd8.png">
<img width="883" alt="flutter doc 2" src="https://user-images.githubusercontent.com/12158468/167233780-5ff5c3a8-5d88-4795-9bf6-83a6622b6955.png">

**Comment by darshankawar** [comment]
@Nayemuzzaman 
When you open an issue, please use new issue template and fill out requested details so that we'll have enough details to work with. Only providing error log won't help unless you provide us other details such as platform you are seeing this error on, a complete minimal code sample along with steps to replicate and `flutter doctor -v`, so please provide these details.

**Comment by Nayemuzzaman** [comment]
@darshankawar fix now

**Comment by darshankawar** [comment]
Thanks for the update, but it is missing `flutter doctor -v` so we are not sure on which version are you seeing this error. A similar error has been fixed recently. So if you are not on latest master or latest stable, please upgrade to either latest versions and try again to see if same error still persists or not.

**Comment by darshankawar** [comment]
@Nayemuzzaman 
Can you upgrade to latest stable or master and check if you still get same behavior ?
Also can you provide platform (windows, desktop) where you get this error ?
