### ISSUE TITLE
The framework should have good text overflow effects

### ISSUE THREAD

**Issue by tain335** [flutter/flutter#1027]
![screenshot_2015-12-24-21-29-42](https://cloud.githubusercontent.com/assets/5304597/12006811/43606060-ac21-11e5-8abf-d77c4f849458.png)
If text content overflow, the Text widget should cut  the content. More, the Text widget should have a property(singleLine or  multiLine) for configuration.

**Comment by abarth** [comment]
Yeah, there's already a bug on file for text-overflow ellipsis.  Let's keep this issue open for more general thinking about text overflow effects.

**Comment by abarth** [comment]
https://github.com/flutter/flutter/issues/417 is the issue about ellipsis

**Comment by abarth** [comment]
https://github.com/flutter/flutter/pull/3818 has `isSingleLine` and a couple overflow effects.  We can add more if there's something specific you want to do.

**Comment by abarth** [comment]
We now support a couple different TextOverflow treatments.  https://github.com/flutter/flutter/issues/4202 is a specific bug about multiline overflow effects.  Hopefully what we have now is sufficient for your purposes.  If not, please open more specific bugs about what you'd like to see.
