### ISSUE TITLE
[go_router] `barrierDismissible` of `CustomTransitionPage` isn't used from anywhere and does not work

### ISSUE THREAD

**Issue by mono0926** [flutter/flutter#102714]
`barrierDismissible` of `CustomTransitionPage` isn't used from anywhere and does not work.
https://github.com/flutter/packages/blob/42f874a8076b2e0620a55d6eec149cc24aaa363c/packages/go_router/lib/src/custom_transition_page.dart#L71

Other fields are used here, but the`barrierDismissible` is missing.
https://github.com/flutter/packages/blob/42f874a8076b2e0620a55d6eec149cc24aaa363c/packages/go_router/lib/src/custom_transition_page.dart#L114-L130

**Expected results:** 

`barrierDismissible` of `CustomTransitionPage` is used and works as described here:
https://github.com/flutter/packages/blob/42f874a8076b2e0620a55d6eec149cc24aaa363c/packages/go_router/lib/src/custom_transition_page.dart#L70

```dart
  @override
  bool get barrierDismissible => _page.barrierDismissible;
```

**Actual results:** 

`barrierDismissible` of `CustomTransitionPage` isn't used from anywhere and does not work.

```dart
class SomePage extends CustomTransitionPage<void> {
  SomePage({
    required LocalKey key,
    required Widget child,
    required bool barrierDismissible, // not work
  }) : super(
          key: key,
          transitionsBuilder: (c, a1, a2, child) => FadeTransition(
            opacity: a1.drive(_curveTween),
            child: child,
          ),
          barrierDismissible: barrierDismissible,
          child: child,
        );

  static final _curveTween = CurveTween(curve: Curves.easeIn);
}
```

**Comment by darshankawar** [comment]
@mono0926 Hi,
There's already similar open issue describing your case, https://github.com/flutter/flutter/issues/102289
Please follow-up in it for further updates.
Closing this as a duplicate.
