### ISSUE TITLE
[go_router_builder] should integration tests run in CI?

### ISSUE THREAD

**Issue by ditman** [flutter/flutter#102799]
After some comments in an unrelated PR, I've been trying to find where [these tests](https://github.com/flutter/packages/tree/main/packages/go_router_builder/example/test) are running in our testing infrastructure, but couldn't find anything after peeking at a bunch of logs:

* ios-build+platform-test skipped ([1](https://cirrus-ci.com/task/5702073722339328?logs=build#L20), [2](https://cirrus-ci.com/task/5139123768918016?logs=build#L20))
* ios-custom_package_tests skipped ([1](https://cirrus-ci.com/task/5139123768918016?logs=build#L20), [2](https://cirrus-ci.com/task/4857648792207360?logs=local_tests#L21))
* test only runs [these](https://github.com/flutter/packages/tree/main/packages/go_router_builder/test), as expected ([1](https://cirrus-ci.com/task/5772442466516992?logs=main#L104))

I didn't look much further, so I might have missed the exact log where those tests are running; but it seems to me that the integration tests present in go_router_builder example aren't running in CI. **Should they?**

(This is maybe because of the odd directory structure of the example app that is different from what is expected by the tooling?)

**Comment by chunhtai** [comment]
The integration test failed when running locally, will need to fix that first

**Comment by ditman** [comment]
I'm going to deduplicate this in favor of: https://github.com/flutter/flutter/issues/102845
