### ISSUE TITLE
New entrypoint for Flutter beginners new to Dart

### ISSUE THREAD

**Issue by Sfshaza** [flutter/flutter#10274]
Just an FYI. I've created a new codelabs page for www.dartlang:
https://www.dartlang.org/codelabs

Also, when writing the tutorials, the only entrypoint I could provide for folks who didn't know Dart was DartPad (which has no guided instruction), Dart Tour (which is a huge, overwhelming doc), or the samples. But you can now also point people to the [Intro to Dart for Java Developers codelab](https://codelabs.developers.google.com/codelabs/from-java-to-dart).

**Comment by sethladd** [comment]
Thanks! I think we're going to add your Dart/Java codelab to our "Bootstrap to Dart" page.

**Comment by sethladd** [comment]
All set. Thanks for the feedback!
