### ISSUE TITLE
[Impeller] Enable impeller on macOS

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#102793]
I would like this for testing. I find it easier to test on desktop than mobile in general.

Current challenges are:

- [ ] (easy): make GPUSurfaceMetalImpeller able to take a MTLTexture (along side of existing methods to take a CAMetalLayer).
- [ ] (easy): update embedder_surface_metal to have an impeller variant
- [ ] (harder): split EmbedderExternalView into a Skia/Impeller variant.
- [ ] (harder): split EmbedderExternalViewEmbedder into Skia/Impeller variant

**Comment by chinmaygarde** [comment]
Blocked on https://github.com/flutter/flutter/issues/102793

**Comment by gaaclarke** [comment]
Another thing we'll have to do is make sure that we are using `kDevicePrivate` on x86_64 macOS devices.  We ran into this problem in https://github.com/flutter/engine/pull/40998 where the assumption of `kHostVisible` is baked into MTLTexture::OnSetContents.

**Comment by jonahwilliams** [comment]
We don't actually use that many host visible textures though, its only the glyph atlas where we'd have to add a blit. The tests, on the other hand, make heavy use of them (apparently). We should just fix it.

**Comment by jonahwilliams** [comment]
Oh and gifs

**Comment by bdero** [comment]
Oh hey, didn't see this bug. This was solved as part of https://github.com/flutter/flutter/issues/112230. :)
