### ISSUE TITLE
Upgrade subscriptions on Android

### ISSUE THREAD

**Issue by Ducius6** [flutter/flutter#102733]
Hi, 

I want to upgrade/downgrade subscriptions for android. To do that I need to provide ChangeSubscriptionParam with the field oldPurchaseDetails. How is my app supposed to get the oldPurchaseDetails object?

Thanks!

**Comment by darshankawar** [comment]
@Ducius6 
I am assuming this is for `in_app_purchase` plugin. If so, check this issue and see if it helps.  https://github.com/flutter/flutter/issues/32395

**Comment by Ducius6** [comment]
Yes, that is for in_app_purchase plugin. But it's the [#32395](https://github.com/flutter/flutter/issues/32395) that I don't understand. For an android upgrade/downgrade subscription you should have the old purchase details object, but there is no proper way of getting your old purchase details.

**Comment by darshankawar** [comment]
> but there is no proper way of getting your old purchase details.

That is correct. The plugin currently doesn't yet have an api to fetch you existing / old purchase details. There's an open issue for it which you can track: https://github.com/flutter/flutter/issues/90707.
Closing this as a duplicate.
