### ISSUE TITLE
dependabot pub updates conflict with dart version in docker file. 

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#102702]
This is one of the examples:

```
The current Dart SDK version is 2.15.1.

Because shelf 1.3.0 requires SDK version >=2.16.0 <3.0.0 and no versions of shelf match >1.3.0 <2.0.0, shelf ^1.3.0 is forbidden.
So, because auto_submit depends on shelf ^1.3.0, version solving failed.
The command '/bin/sh -c pub get' returned a non-zero code: 1
ERROR
ERROR: build step 0 "gcr.io/cloud-builders/docker" failed: step exited with non-zero status: 1
```

**Comment by godofredoc** [comment]
\cc @keyonghan

**Comment by jonasfj** [comment]
@jonasfj, @sigurdm we should look at this :)

Probably we should make dependabot upgrade as part of the release proces.. or we should make it upgrade automatically on demand.

**Comment by jonasfj** [comment]
Sorry, I read the issue wrong. The problem here is that you're using a Dart version older than the current stable.

And dependabot runs with latest stable. We could consider making some configuration options for this.

**Comment by godofredoc** [comment]
Would it be possible to use beta? we just moved to use dart docker official images https://hub.docker.com/_/dart

**Comment by godofredoc** [comment]
Seems like this is not happening anymore after we move to use the dart official docker images.
