### ISSUE TITLE
Disabled mouse cursor when hovering ExpansionPanel icon on flutter web

### ISSUE THREAD

**Issue by Pierre-Monier** [flutter/flutter#102737]
When we set the `canTapOnHeader` parameter to `true` on an ExpansionPanel, we have a disabled mouse cursor on the expand icon. I'm pretty sure that it's not what we want, because if I allow all the header to be clicked, that also include the icon.
Note that when I click on the icon, the expension callback is still called.

![demo bug](https://user-images.githubusercontent.com/65488471/165712811-a144e20d-b87d-45ae-bcd9-b44aa26f1fc1.gif)

```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.3, on macOS 12.2.1 21D62 darwin-arm, locale fr-FR)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.66.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability
```

The code use for the demo: 

```dart
ExpansionPanelList(
              children: [
                ExpansionPanel(
                    canTapOnHeader: true,
                    headerBuilder: (_, __) => const Text("titi"),
                    body: const Text("toto"))
              ],
            )
```

**Comment by danagbemava-nc** [comment]
Hi @Pierre-Monier, kindly see the comment in https://github.com/flutter/flutter/issues/102303#issuecomment-1105239701. 

Closing this as it has already been fixed on `beta` and `master`. 

Thank you

**Comment by Pierre-Monier** [comment]
perfect
