### ISSUE TITLE
SkParagraph performance regression

### ISSUE THREAD

**Issue by bdero** [flutter/flutter#102711]
https://flutter-engine-perf.skia.org/e/?begin=1651076344&end=1651100254&keys=X133b7f3845e030cd1dca69e879839d6a&num_commits=50&request_type=1&xbaroffset=27427

* SkParagraphFixture_ManyStylesLayout.cpu_time: 4x increase
* SkParagraphFixture_StylesBigO_[8|16|64|256|1024|4096].cpu_time: 2x increase

Skia roll here: https://github.com/flutter/engine/pull/32974
Not seeing anything relevant in surrounding commits.

**Comment by bdero** [comment]
Speculative revert: https://github.com/flutter/engine/pull/32978

**Comment by zanderso** [comment]
@jason-simmons

https://skia.googlesource.com/skia.git/+/c35e492a19b047618dcea58043ba915ece6fc99d looks related?

**Comment by jason-simmons** [comment]
https://skia.googlesource.com/skia.git/+/c35e492a19b047618dcea58043ba915ece6fc99d is intended to improve performance in typical use cases by replacing the text style stack/deque with an SkSTArray that preallocates enough space for most paragraphs.

The ManyStylesLayout benchmark is pushing 1000 styles, which is not how apps commonly use this API.
