### ISSUE TITLE
[android] [opengl] Queueing and Dequeueing buffers on Android can take a significant amount of time on some devices

### ISSUE THREAD

**Issue by iskakaushik** [flutter/flutter#102765]
When partial repaint is enabled, we need to know what the age of a buffer is, to do this we call:

```
eglQuerySurface(display, surface, EGL_BUFFER_AGE_EXT, &age);
```

On some devices, this call isn't cheap and can wait for a buffer to be dequeued, resulting in long times. See https://groups.google.com/g/angleproject-review/c/DRdEzerEGro?pli=1 for (similar) context on why it could be long.

This could also be unavoidable as we need to queue and dequeue buffers for a frame anyways.

`dequeue` trace (~3 seconds):

<img width="2747" alt="image" src="https://user-images.githubusercontent.com/1006071/165793342-2a1548ab-9426-4002-bf06-80ff0dac5bd5.png">

`queue` trace:

<img width="1553" alt="image" src="https://user-images.githubusercontent.com/1006071/165794920-eec28835-2d8e-455a-8515-aa555c4118b7.png">

Seems like we are taking ~4.5 seconds total out of ~14 second raster time.

**Comment by jonahwilliams** [comment]
This is likely due to GPU backpressure. We have pretty good techniques to measure GPU execution time now.
