### ISSUE TITLE
prevent multiple approvals from fluttergithubbot

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#102712]
We need to validate if a given PR is already approved by fluttergithub bot before triggering the approval. This is to prevent multiple approvals as new labels are being added to the PR.

**Comment by keyonghan** [comment]
This is still happening: https://github.com/flutter/cocoon/pull/1822

**Comment by codebird** [comment]
if we look here: https://api.github.com/repos/flutter/cocoon/pulls/1822/reviews you will see that the submitted_at of both approvals is exactly the same, which is weird, something is being triggered twice.

**Comment by keyonghan** [comment]
Yeah, this is caused by duplicated webhook events. https://github.com/flutter/cocoon/pull/1811 was implemented to check if an earlier `approval` has been applied. Sounds some race condition when approving the second webhook PR before the first approved review is posted.

**Comment by codebird** [comment]
It is interesting. I'll take a look again tomorrow

**Comment by codebird** [comment]
@keyonghan what if we add some delay above @godofredoc's logic

```
    final GitHub botClient = await config.createFlutterGitHubBotClient(slug);
    Random random = Random();
    int randomNumber = random.nextInt(500);
    sleep(Duration(milliseconds: randomNumber));
    Stream<PullRequestReview> reviews = botClient.pullRequests.listReviews(slug, pullRequest.number!);
    await for (PullRequestReview review in reviews) {
      if (review.user.login == 'fluttergithubbot' && review.state == 'APPROVED') {
        // Already approved.
        return;
      }
    }
```

**Comment by godofredoc** [comment]
> ed way to control th
If this is not happening very frequently maybe we want to keep the duplicated approval rather than always adding a random delay.

**Comment by keyonghan** [comment]
This is happening 4 out of recent 5 deps bump PRs. We can use a small random delay like (<10s), considering the auto-approval API runs every 2 mins.

**Comment by godofredoc** [comment]
Random delays introduce unexpected behavior, I'd encourage you to look for a different alternative.

**Comment by codebird** [comment]
@godofredoc I don't think we have an alternative, this is the only thing we control, that's why I thought about it. It is half a second delay, which will decrease the probability of getting same number twice and at the same time we won't feel it. I don't know we can give it a try and revert it maximum.

**Comment by godofredoc** [comment]
As this is executing sequentially and assuming not overlapping cron executions we can keep a map of approved PRs to avoid calling the approvals API twice.

Something like:

if (!approvedPRs.contains(pr.number)) {
   # approve pr
   # add pr to the map    
}

If the problem is overlapping cron executions we may be able to tweak it on the cron.yaml configuration.

**Comment by codebird** [comment]
It is not overlapping cron. It is overlapping github Webhooks. The webhook is being triggered twice exactly the same time. Your logic alone was great, but whatever you do nothing will change. If we do what you are proposing,  approvedPrs.contains will return false for both... So same issue as your current logic

**Comment by godofredoc** [comment]
One potential solution is to move these two lines: https://cs.opensource.google/flutter/cocoon/+/main:auto_submit/lib/requests/github_webhook.dart;l=61-62 somewhere here https://cs.opensource.google/flutter/cocoon/+/main:auto_submit/lib/requests/check_pull_request.dart;l=68

**Comment by codebird** [comment]
great find @godofredoc. Needs line 57 and 59 with it.
