### ISSUE TITLE
[url_launcher] Opening up a Play Store link via Google Play brings up a dialog box asking to Install a Web Browser.

### ISSUE THREAD

**Issue by patrick-enzo** [flutter/flutter#102769]
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. Tap on a link that leads to the play store app with the correct path.

**Expected results:** The app corresponding to the play store link displays.

**Actual results:** A dialog appears saying "To view this content, install and set up a web browsing app".

<details>
<summary>Code sample</summary>

    return ul.launchUrl(
      Uri(
        scheme: scheme,  // <-- https
        host: host,   // <-- play.google.com
        path: path, // <--- store/apps/details?id=com.abc.yxz
      ),
      mode:ul.LaunchMode.externalApplication,
    );

```dart
```

</details>

Before upgrading to version 6.1.0, this problem didn't exist.
I've also tried LaunchMode.externalNonBrowserApplication which lead to the same result. LaunchMode.inAppWebView also doesn't work because the path can't be found because it's private. I've tried manually inputting the link into the chrome web page and it works properly so I'm sure that the path I'm passing in works. I do have Chrome installed and it's set as my default on my device. I'm on Flutter version 2.10.3.

Thank you.

**Comment by darshankawar** [comment]
@patrick-enzo 
Looking at the error it shows `To view this content, install and set up a web browsing app`, this doesn't seem to be specific to Flutter and may be coming from Google play itself. 
See this related link which hopefully should answer your question: https://www.reddit.com/r/Android/comments/7lv04m/google_play_now_intercepts_all_links_to_the/

Closing this as not a Flutter specific issue. If you disagree, write in comments and I'll reopen it.

**Comment by patrick-enzo** [comment]
@darshankawar 

Thank you for replying. 
I was also reluctant on posting this issue since it seemed more like a Google Play issue.

I only had the courage to submit this as a problem because it worked properly using the old deprecated method.

I've attached a video showing the difference between using the deprecated `launch` method and the new `launchUrl` method.


https://user-images.githubusercontent.com/88462493/165950523-a0b37533-464a-4a5e-bbdd-526132fae806.mov

<details>
<summary>Code sample (Also visible in the video)</summary>

            TextButton(
              child: const Text('Deprecated launch method'),
              onPressed: () {
                launch('https://play.google.com/store/apps/details?id=com.shikudo.focus.google&hl=en_US&gl=US');
              },
            ),
            const SizedBox(height: 20),
            TextButton(
              child: const Text('New launchUrl method'),
              onPressed: () {
                launchUrl(
                    Uri(
                        scheme: 'https',
                        host: 'play.google.com',
                        path: 'store/apps/details?id=com.shikudo.focus.google&hl=en_US&gl=US'),
                    mode: LaunchMode.externalApplication);
              },
            ),

```dart
```

</details>

Thank you.

**Comment by andreyjr08** [comment]
Greetings.
I have the same problem, I am upgrading the url_launcher library from ^6.0.12 to ^6.1.0.
When I try to open the social networks of facebook, instagram or twitter in specific links it opens the browser and not the native applications, in the version I had previously this only happened when the applications of these social networks were not installed.
I need to open these networks in a specific profile, there is a possibility that you share an example of how I can do this in the new version.
Thank you.
