### ISSUE TITLE
dartanalyzer and flutter analyze don't do the same thing on a newly created flutter project

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#10278]
I created a new project, added the following line:

```dart
Row r = new Row();
r.mainAxisAlignment;
```

to the `main()` function.

I then ran `dartanalyzer` and it failed with an warning. I ran `flutter analyze` and it succeeded!

This is pretty confusing behavior for a new user. Can we make the tools do the same thing?

```
sethladd@sethladd-macbookpro ~/tmp/myapp $ dartanalyzer lib/main.dart 
Analyzing lib/main.dart...
  warning • The getter 'mainAxisAlignment' isn't defined for the class 'Row' at lib/main.dart:6:5 • undefined_getter
1 warning found.
sethladd@sethladd-macbookpro ~/tmp/myapp $ flutter analyze lib/main.dart
Analyzing /Users/sethladd/tmp/myapp/lib/main.dart...
No issues found!
Ran in 4.7s
```

Code:

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(new MyApp());
  Row r = new Row();
  r.mainAxisAlignment;
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: 'Flutter Demo',
      theme: new ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see
        // the application has a blue toolbar. Then, without quitting
        // the app, try changing the primarySwatch below to Colors.green
        // and then invoke "hot reload" (press "r" in the console where
        // you ran "flutter run", or press Run > Hot Reload App in IntelliJ).
        // Notice that the counter didn't reset back to zero -- the application
        // is not restarted.
        primarySwatch: Colors.blue,
      ),
      home: new MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  // This widget is the home page of your application. It is stateful,
  // meaning that it has a State object (defined below) that contains
  // fields that affect how it looks.

  // This class is the configuration for the state. It holds the
  // values (in this case the title) provided by the parent (in this
  // case the App widget) and used by the build method of the State.
  // Fields in a Widget subclass are always marked "final".

  final String title;

  @override
  _MyHomePageState createState() => new _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      // This call to setState tells the Flutter framework that
      // something has changed in this State, which causes it to rerun
      // the build method below so that the display can reflect the
      // updated values. If we changed _counter without calling
      // setState(), then the build method would not be called again,
      // and so nothing would appear to happen.
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance
    // as done by the _incrementCounter method above.
    // The Flutter framework has been optimized to make rerunning
    // build methods fast, so that you can just rebuild anything that
    // needs updating rather than having to individually change
    // instances of widgets.
    return new Scaffold(
      appBar: new AppBar(
        // Here we take the value from the MyHomePage object that
        // was created by the App.build method, and use it to set
        // our appbar title.
        title: new Text(widget.title),
      ),
      body: new Center(
        child: new Text(
          'Button tapped $_counter time${ _counter == 1 ? '' : 's' }.',
        ),
      ),
      floatingActionButton: new FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: new Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
```

**Comment by sethladd** [comment]
cc @devoncarew we took a look at this a while ago. Can you help see what it would take to resolve these differences? I don't think it should matter which tool I use, but I could be wrong. Thanks! 

(this also makes me wonder if our IDEs are doing the same or different things?)

**Comment by eseidelGoogle** [comment]
How does a Flutter user have `dartanalyze` in the first place?  All Dart SDK binaries are an implementation detail of Flutter.

**Comment by sethladd** [comment]
I agree in principle, but people will google around and find that command, unfortunately. The error here isn't useful, it doesn't say "oh, hey, you're in a flutter project! I don't work in that. please use flutter analyze", instead it just fails for a weird reason :/

I can't think of a reason why `dartanalyze` wouldn't work, in principle. What's wrong with our setup such that dartanalyze can't handle our project?

Any of these are sufficient:

A) error out with a respectful error message if dartanalyze encounters a flutter project
B) teach dartanalyze about a flutter project
C) make a flutter project "just work" with dartanalyze

**Comment by devoncarew** [comment]
Yeah, likely `dartanalyzer` shouldn't be used for flutter projects, but I am surprised by the difference.

If you run `which dartanalyzer`, does it point to the same sdk as that from `which flutter`?

There was some work in progress to unify the various analysis options files (by @danrubel), but I don't think that that would be a cause here.

**Comment by sethladd** [comment]
```
sethladd@sethladd-macbookpro ~/tmp/myapp $ which dartanalyzer
/Users/sethladd/homebrew/bin/dartanalyzer
sethladd@sethladd-macbookpro ~/tmp/myapp $ dartanalyzer --version
dartanalyzer version 1.23.0
```

dartanalyzer is NOT the same as the analyzer that ships with Flutter.

**Comment by eseidelGoogle** [comment]
Yeah.  So you have two copies of the Dart SDK installed.  I would suspect that most Flutter users won't?  Since they'll be new to Dart and will only have installed Flutter?  But yes, there also seems like little reason why `dartanalyzer` couldn't work for Flutter projects, but it's also not clear to me that it needs to?

**Comment by devoncarew** [comment]
For posterity, your flutter analyzer is likely at version `1.24.0-dev.3.0`.

**Comment by sethladd** [comment]
Thanks, I understand I have two darts installed and that's weird. :/  FWIW most people doing Dart for mobile and web will run into this.

I'd like to understand why dartanalyzer can't analyze a Flutter project. That may teach us about decisions we made, and if we made them for a good reason. If there's no reason to be different, maybe we can fix that. Or, maybe this shows a bug in how dartanalyzer approaches a project?

**Comment by devoncarew** [comment]
I don't see the issue locally w/ a `dartanalyzer` from `1.24.0-dev.5.0`, but am downloading a 1.23.0 sdk to check that...

**Comment by devoncarew** [comment]
Hmm, I don't see it w/ 1.23.0 dartanalyzer either, so something else is going on.

**Comment by Hixie** [comment]
IMHO running "dartanalyzer" directly is a bit like running "pub" directly. "pub" gives you a semi-useful message complaining about flutter if you do this now (mostly as a side-effect, I think).

**Comment by devoncarew** [comment]
OK, I can repro now - dartanalyzer 1.23.0 shows the issue, 1.24.0 does not. `dartanalyzer` isn't using the analysis options file used by flutter analyze (contributed here: https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/commands/analyze_once.dart#L200). We're seeing this issue w/ 1.23.0 as that sdk didn't have some language flags set by default.

**Comment by sethladd** [comment]
> IMHO running "dartanalyzer" directly is a bit like running "pub" directly

Kind of. pub requires a magic env variable to exist to be able to acknowledge Flutter exists. From my understanding, dartanalyzer should "just work". All the metadata should be in a Flutter project.

> 1.23.0 shows the issue, 1.24.0 does not

Ah, thanks for tracking that down. Curious, what's in the analysis_options_repo file that allows the analyzer to find `r.mainAxisAlignment` ? I previously thought the analysis_options were to turn on and off language features and lints.

**Comment by zoechi** [comment]
Is there still something to do?
`dartanalyzer` doesn't even show an error if `dart:ui` is used.

**Comment by zoechi** [comment]
I believe this is fixed.
