### ISSUE TITLE
Linux_android fast_scroll_heavy_gridview__memory failing repeatedly on metrics upload

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#102760]
https://ci.chromium.org/p/flutter/builders/prod/Linux_android%20fast_scroll_heavy_gridview__memory

e.g.

https://ci.chromium.org/ui/p/flutter/builders/prod/Linux_android%20fast_scroll_heavy_gridview__memory/2611/overview

```
The lock is waiting for a long time: 1:27:22.880000. If the lock file flutter-flutter/2022/04/28/08/f9f4915e5efb5e917b6d3a45751ff927028a29e3/fast_scroll_heavy_gridview__memory_intel_linux_MotoG4_values.json.lock in bucket flutter-skia-perf-prod seems to be stuck (i.e., it was created a long time ago and no one seems to be owning it currently), delete it manually to unblock this.
```

P0 because this is closing the tree.

**Comment by godofredoc** [comment]
Lock file was deleted, the builder retried and the the tree is now open.

**Comment by godofredoc** [comment]
@keyonghan does the upload to metrics happen in the context?

\cc @yusuf-goog

**Comment by godofredoc** [comment]
For context this happened twice last week.

**Comment by keyonghan** [comment]
The build first hit `DetailedApiRequestError(status: 503, message: We encountered an internal error. Please try again.)` in build [2609](https://ci.chromium.org/ui/p/flutter/builders/prod/Linux_android%20fast_scroll_heavy_gridview__memory/2609/overview)

The following retries kept hitting `lock issue`:
```
The lock is waiting for a long time: 1:27:22.880000. If the lock file flutter-flutter/2022/04/28/08/f9f4915e5efb5e917b6d3a45751ff927028a29e3/fast_scroll_heavy_gridview__memory_intel_linux_MotoG4_values.json.lock in bucket flutter-skia-perf-prod seems to be stuck (i.e., it was created a long time ago and no one seems to be owning it currently), delete it manually to unblock this.
Access was denied (www-authenticate header was: Bearer realm="https://accounts.google.com//", error=invalid_token).
```
![Screen Shot 2022-05-02 at 11 41 18 AM](https://user-images.githubusercontent.com/54558023/166306670-e4733c31-8b5e-4d37-b1db-dcd9c1d2bb11.png)

We should call the `unlock` before throwing the exception: https://github.com/flutter/packages/blob/main/packages/metrics_center/lib/src/gcs_lock.dart#L75

**Comment by keyonghan** [comment]
> @keyonghan does the upload to metrics happen in the context?

I don't think metrics would be uploaded. From the bucket, only the metrics from the success build are there.

**Comment by godofredoc** [comment]
> > @keyonghan does the upload to metrics happen in the context?
> 
> I don't think metrics would be uploaded. From the bucket, only the metrics from the success build are there.

The metrics step was the problem here. The lock file was not deleted in a previous attempt to upload metrics making all the next runs fail until the lock file was manually deleted. 

The question is whether the lock file is created/deleted from a context to ensure the lock is deleted no matter if the upload was successful or not.

**Comment by keyonghan** [comment]
That't correct. See my last [comment](https://github.com/flutter/flutter/issues/102760#issuecomment-1115241536), we need to call the unlock before throwing the exception: https://github.com/flutter/packages/blob/main/packages/metrics_center/lib/src/gcs_lock.dart#L75

**Comment by zanderso** [comment]
@drewroengoogle is this the same lockfile issue that was closing the tree the week before last? I'm going to re-open this so that it can be properly de-duped against the more recent issue.

**Comment by drewroengoogle** [comment]
Yep, it is the same issue, so I'll close it but reference https://github.com/flutter/flutter/issues/120440. Thanks!
