### ISSUE TITLE
`flutter upgrade` fails on Windows with `pshot` error

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#10273]
## Steps to Reproduce

`flutter upgrade`:

```
Upgrading Flutter from c:\Users\mit\dev\github\flutter-alpha...
...
Running flutter doctor...
...

'pshot' is not recognized as an internal or external command,
operable program or batch file.
Error: Unable to create dart snapshot for flutter tool. Retrying...
```

Running it again and it completes with no error.

**Comment by mit-mit** [comment]
cc @goderbauer

**Comment by goderbauer** [comment]
This is unfortunately a known issue when the upgrade causes the content of the batch script (or of the shell script on Linux) to change, see https://github.com/flutter/flutter/issues/8813.
