### ISSUE TITLE
Add umbrella/meta issue tag

### ISSUE THREAD

**Issue by eliabieri** [flutter/flutter#102783]
I suggest adding a tag for all umbrella/meta issues.

### Context  
Currently I find it quite hard to track upcoming features/changes.
If all meta/umbrella issues were tagged, they could be filtered and once could see all big upcoming changes at one glance.

**Comment by stuartmorgan** [comment]
> If all meta/umbrella issues were tagged, they could be filtered and once could see all big upcoming changes at one glance.

The premise here is not actually true; there's no required way to track a feature within Flutter. Some people use umbrella bugs, some people use GitHub projects, some people use specialized labels. There are likely other ways as well.

Can you elaborate more on the use case here? There's [the roadmap](https://github.com/flutter/flutter/wiki/Roadmap) for a high-level overview; do you have examples of things you want to know about that aren't covered there?

**Comment by stuartmorgan** [comment]
> I would like to stay informed about new concrete changes and features, before I read about them in the stable change log.

Does watching commits address this use case?

> Umbrella issues were the closest thing I could get to actually knowing what the people are working on for the upcoming release.

Even when they exist, umbrella issues aren't necessarily associated with any specific release; they often track working spanning multiple release cycles.

If the goal is to see actual concrete changes that will be in the next release, actual commits are going to be the only reliable and complete source of information.

**Comment by eliabieri** [comment]
Agree.

Having an overview over currently worked on features would nevertheless be something of big use to me (and possibly others), even though I can't be sure, in which release they land.
Having to look through all issues and commits would take too much time for me (as I'm not that involved) so I though having an overview over the umbrella issues would serve my need.

Maybe I'm also alone with this need, so feel free to close this issue.

**Comment by darshankawar** [comment]
Closing per above comment.
