### ISSUE TITLE
[flutter_tools] flutter update-packages downgrades package:coverage

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#102781]
See: https://github.com/flutter/flutter/pull/102780/files

package:coverage is being downgraded from 1.2.0 -> 1.0.3.

This is also leading to compilation failures on the PR:
```
packages/flutter_tools/lib/src/test/coverage_collector.dart:26:15: Error: Type 'coverage.HitMap' not found.
  Map<String, coverage.HitMap> _globalHitmap;
              ^^^^^^^^^^^^^^^
```

**Comment by christopherfujino** [comment]
Test was bumped from 1.20.2 -> 1.21.1, which now constrains package:coverage: 1.0.1.

**Comment by christopherfujino** [comment]
Looks like also package:vm_service was downgraded from `8.2.2` -> `7.5.0`

**Comment by christopherfujino** [comment]
Added a new flag to `flutter update-packages` to diagnose:

Run with packages from master:

```
~/git/flutter$ flutter update-packages --describe-package=coverage
Running "flutter pub get" in flutter_update_packages.OBZACI...         6.6s
Package coverage is resolved as 1.2.0
Found 2 packages depending on coverage:
        test constrains coverage with ^1.0.1
        test_core constrains coverage with ^1.0.0
```

After a --force-upgrade:

```
Package coverage is resolved as 1.0.3
Found 2 packages depending on coverage:
        test constrains coverage with ^1.0.1
        test_core constrains coverage with ^1.0.0
```

Hmm...

**Comment by christopherfujino** [comment]
Now with package:vm_service on master:

```
Package vm_service is resolved as 8.2.2
Found 6 packages depending on vm_service:
        coverage-1.2.0 constrains vm_service with >=8.2.0 <9.0.0
        dds-2.2.0 constrains vm_service with ^8.1.0
        dds_service_extensions-1.3.0 constrains vm_service with ^8.1.0
        devtools_shared-2.12.1 constrains vm_service with ^8.1.0
        dwds-13.1.0 constrains vm_service with ^8.2.0
        test_core-0.4.11 constrains vm_service with >=6.0.0 <9.0.0
```

And after a force-upgrade:

```
Package vm_service is resolved as 7.5.0
Found 5 packages depending on vm_service:
        coverage-1.0.3 constrains vm_service with >=6.1.0 <8.0.0
        dds-2.1.6+3 constrains vm_service with ^7.2.0
        devtools_shared-2.8.0 constrains vm_service with ^7.1.0
        dwds-11.5.2 constrains vm_service with ^7.4.0
        test_core-0.4.13 constrains vm_service with >=6.0.0 <9.0.0
```

**Comment by christopherfujino** [comment]
More verbose comparison

[diff.txt](https://github.com/flutter/flutter/files/8592818/diff.txt)

**Comment by christopherfujino** [comment]
The set of all packages that were downgraded:

- `coverage`: not constrained by other packages
- `dds` - constrained by `dwds`
- `devtools_shared` - constrained by `dds`
- `dwds` - not constrained by other packages
- `vm_service`: constrained by `coverage`, `dds`, `devtools_shared`, and `dwds`

**Comment by christopherfujino** [comment]
In summary:

```
package:coverage was downgraded from 1.2.0 -> 1.0.3
Package coverage is resolved as 1.0.3
        test-1.21.1 constrains coverage with ^1.0.1
        test_core-0.4.13 constrains coverage with ^1.0.0

package:vm_service was downgraded from 8.2.2 -> 7.5.0
Package vm_service is resolved as 7.5.0
        coverage-1.0.3 constrains vm_service with >=6.1.0 <8.0.0
        dds-2.1.6+3 constrains vm_service with ^7.2.0
        dwds-11.5.2 constrains vm_service with ^7.4.0
        test_core-0.4.13 constrains vm_service with >=6.0.0 <9.0.0
        devtools_shared-2.8.0 constrains vm_service with ^7.1.0

package:dds was downgraded from 2.2.0 -> 2.1.6+3
Package dds is resolved as 2.1.6+3
        dwds-11.5.2 constrains dds with ^2.1.1

package:dwds was downgraded from 13.1.0 -> 11.5.2
Package dwds is resolved as 11.5.2

package:devtools_shared was downgraded from 2.12.1 -> 2.8.0
Package devtools_shared is resolved as 2.8.0
        dds-2.1.6+3 constrains devtools_shared with ^2.3.0
```

**Comment by christopherfujino** [comment]
I finally narrowed this down to our direct dev_dependency on `file_testing: 3.0.0` (the newest) conflicting with `dwds`. In a dart package with just the two, and `file_testing` pinned to 3.0.0, `dwds` is downgraded to 11.5.2.

**Comment by christopherfujino** [comment]
Ahh, so I think the real reason is that `file_testing: 3.0.0` constrains `lints: ^1.0.1` https://github.com/google/file.dart/blob/master/packages/file_testing/pubspec.yaml, while `analyzer: 4.0.0` contrains it `lints: ^2.0.0` https://github.com/dart-lang/sdk/commit/3514a3ed930f3dd51c3953d51db406db6b3f7c81#diff-a8403f1fc69a35a5ee70b920d57c1d402b06e5d10929ec8daedfebbf8c34c42f

**Comment by jonasfj** [comment]
> I think this is a bug in pub?

From what you describe pub successfully solves the dependency constraints in all scenarios.

From what I understand there are multiple solutions. Any solution to the constraints provided is a correct solution. So there is no bug, hehe :rofl: 

The limitation is that pub doesn't have any definition of one solution being better than another solution. When the solution space is explored, the local decisions made by the solver aims to explore newer versions first. But this is a heuristic, and indeed it's a local heuristic, it doesn't even try to get as many newest versions as possible.

It just picks the package with fewerst versions and tries the newest version of that package before trying other dependencies.
So it does a _depth-first exploration_ and uses a heuristic to pick which branches to explore first, but the depth-first exploration nature means that this heuristic isn't very powerful.

----------------------------------------

What you can do is to use `>=` to force the solver to pick newer versions. If you use `>= [currently pinned version]` in the synthetic `pubspec.yaml` then you would prevent downgrades. This is also what `dart pub upgrade --major-versions` will do.

Downgrading any pinned dependency is probably is a breaking change. But there are so many ways in which pinning dependencies causes problems.
