### ISSUE TITLE
flutter: [ERROR:flutter/shell/common/shell.cc(94)] Dart Unhandled Exception: NoSuchMethodError: No top-level getter 'showCell' declared

### ISSUE THREAD

**Issue by cj3479** [flutter/flutter#102727]
When I use these  code below to start up dart

Android code
<img width="821" alt="image" src="https://user-images.githubusercontent.com/9412601/165702871-996cdd1a-7adf-4a40-a32b-f6c2ac5d6403.png">

dart code 
<img width="562" alt="image" src="https://user-images.githubusercontent.com/9412601/165702988-6eb61715-a597-4003-b7b8-49a38290b723.png">

It works fine in debug mode, **but it failed in release mode**
this is error log
<img width="1952" alt="image" src="https://user-images.githubusercontent.com/9412601/165703179-93aa2bda-adb8-4683-83c9-bdfdb692f86d.png">

<img width="1037" alt="image" src="https://user-images.githubusercontent.com/9412601/165702673-d0c0c2a1-b5f4-4225-a88b-14e8006adcf9.png">

**Comment by danagbemava-nc** [comment]
Hi @cj3479, you appear to be on an older version of `stable`. Kindly upgrade to the latest version of `stable(2.10.5)` to see if you still experience this issue. 

If you do, kindly provide a complete minimal reproducible code sample, preferably in a repo that we can run without minimal changes so we can verify this. Please provide the updated `flutter doctor -v` as well. 

Thank you

**Comment by cj3479** [comment]
> Hi @cj3479, you appear to be on an older version of `stable`. Kindly upgrade to the latest version of `stable(2.10.5)` to see if you still experience this issue.
> 
> If you do, kindly provide a complete minimal reproducible code sample, preferably in a repo that we can run without minimal changes so we can verify this. Please provide the updated `flutter doctor -v` as well.
> 
> Thank you

Hi @danagbemava-nc ,I upgrade to the latest version of stable(2.10.5), it still has above  error

this code path is 
add_to_app/android_view of https://github.com/flutter/samples.git 

by the way ，When I remove url_launcher  dependencies, It works fine,  It seems that packages with the ability to interact with native platform may encounter this problem.

<img width="354" alt="image" src="https://user-images.githubusercontent.com/9412601/167304676-fd7c9adc-d871-4dcc-863e-fd3cd8b7db0c.png">

**Comment by danagbemava-nc** [comment]
Hi @cj3479, can you check https://github.com/flutter/samples/tree/master/add_to_app/plugin for an example on how to integrate plugins into an add-to-app app? My guess is that the `android_view` example isn't set up to work with plugins.

**Comment by cj3479** [comment]
> https://github.com/flutter/samples/tree/master/add_to_app/plugin

The path is https://github.com/flutter/samples/tree/master/add_to_app/android_view

**Comment by cj3479** [comment]
> Hi @cj3479, can you check https://github.com/flutter/samples/tree/master/add_to_app/plugin for an example on how to integrate plugins into an add-to-app app? My guess is that the `android_view` example isn't set up to work with plugins.

The code path is https://github.com/flutter/samples/tree/master/add_to_app/android_view

**Comment by danagbemava-nc** [comment]
> Sorry,I don't understand what your meaning. The code path you mentioned is wrong

Hi @cj3479, that was my bad. I didn't realize that the `android_view` example was based on the `plugins` example. 

The error you're getting seems similar to https://github.com/flutter/flutter/issues/91841, which has been fixed on `master`. Can you upgrade to the `master` channel to see whether or not you still experience this issue?

If you do, please provide the output of `flutter doctor -v` that shows the version of the `master` channel you used. Thank you
