### ISSUE TITLE
Left-side Scrollbar of a big thickness has unexpected behavior (draws on top of content, shows additional scrollbar on the right).

### ISSUE THREAD

**Issue by whitemagehealing** [flutter/flutter#102775]
## Steps to Reproduce

1. Run the following code sample on DartPad and/or a Desktop build (Windows).

**Expected results:** 
1. Track thickness would change to match the bar thickness.
   * I expected setting `thickness` to PUSH my list (to the right) to make space for its thickness so it wouldn't overlap with content. I can see why it might be expected to overlap for some developers; however, it does not work for those having the bar visibility always on, because it will obscure content. I can see this being an "overlap" parameter, but the workaround is to manually push the content yourself.
3. Be able to make my scrollbar FLUSH with the edges of the parent widget or have **controllable padding**. 
    * It looks like it is misaligned, because I'm thinking there is inherent padding. I manually padded the contents to make a fake track; however, without knowing the inherent padding, I cannot properly compensate and the contents look misaligned like this. Of course, I could guess and test, but I'm just mentioning the weakness here.
![image](https://user-images.githubusercontent.com/98419352/165814544-10ad748c-d0a4-4ee6-9e14-5f5ac7559696.png)
4. **ONE** scrollbar on the **LEFT**.
    * This might be a problem caused by the newer default implementation of the ScrollbarController. It seems like we don't need to use Scrollbar() at all anymore (https://api.flutter.dev/flutter/material/Scrollbar-class.html) and just pass in a controller; however, I see no means of making a left-side Scrollbar with this method.

**Actual results:** 
1. Two scrollbars, even when orientation is set to `ScrollbarOrientation.left` (visible when actively scrolling).
   * Even when set to `ScrollbarOrientation.right`, one scrollbar is drawn overlapping the other.
3. Scrollbar overlapping content.
4. Scrollbar misaligned with forced hard-coded track thickness.

## Code Sample

```dart
import 'package:flutter/material.dart';

const Color darkBlue = Color.fromARGB(255, 18, 32, 47);

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: darkBlue,
      ),
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: Center(
          child: MyWidget(),
        ),
      ),
    );
  }
}

class MyWidget extends StatelessWidget {
   final List<String> entries = <String>[
    'A',
    'B',
    'C',
    ...List.generate(100, (index) => index.toString())
  ];
  final List<int> colorCodes = <int>[600, 500, 100];
  
  @override
  Widget build(BuildContext context) {
    return Scrollbar(
        isAlwaysShown: true,
        thickness: 30,
        radius: Radius.zero,
        scrollbarOrientation: ScrollbarOrientation.left,
        child: ListView.builder(        padding: EdgeInsets.all(8),
            itemCount: entries!.length,
            itemBuilder: (BuildContext context, int index) {
              return Container(
                height: 50,
                color: Colors.amber[colorCodes[index % colorCodes.length]],
                child: Center(
                    child: Text('Entry ${entries![index]}')),
              );
            }));
  }
}

```

**Comment by maheshmnj** [comment]
Hi @whitemagehealing, Thanks for filing the issue. I believe this is working as intended, Scrollbars are intended to show on top of the content. And regarding the additional scrollbar on the right you can disable it by using [ScrollConfiguration](https://api.flutter.dev/flutter/widgets/ScrollConfiguration-class.html). Please see the below code sample

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

const Color darkBlue = Color.fromARGB(255, 18, 32, 47);

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: darkBlue,
      ),
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: Center(
          child: MyWidget(),
        ),
      ),
    );
  }
}

class MyWidget extends StatelessWidget {
  final List<String> entries = <String>[
    'A',
    'B',
    'C',
    ...List.generate(100, (index) => index.toString())
  ];
  final List<int> colorCodes = <int>[600, 500, 100];

  @override
  Widget build(BuildContext context) {
    return Scrollbar(
        thumbVisibility: true,
        thickness: 30,
        radius: Radius.zero,
        scrollbarOrientation: ScrollbarOrientation.left,
        child: ScrollConfiguration(
          behavior: ScrollConfiguration.of(context).copyWith(scrollbars: false),
          child: ListView.builder(
              padding: EdgeInsets.all(8),
              itemCount: entries!.length,
              itemBuilder: (BuildContext context, int index) {
                return Container(
                  height: 50,
                  color: Colors.amber[colorCodes[index % colorCodes.length]],
                  child: Center(child: Text('Entry ${entries[index]}')),
                );
              }),
        ));
  }
}
```
</details>   

<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel stable, 2.10.5, on macOS 12.3 21E230 darwin-arm, locale en-IN)
    • Flutter version 2.10.5 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (12 hours ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.65.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.39.20220405

[✓] Connected device (4 available)
    • Redmi K20 Pro (mobile) • 192.168.1.2:55555                    • android-arm64  • Android 11 (API 30)
    • iPhone 12 Pro (mobile) • 535317A4-921C-488F-B234-C2CC6D4AE5A1 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.3 21E230 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 100.0.4896.88

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by whitemagehealing** [comment]
Thank you! That worked! Hopefully, more documentation can be added (with an example) to the  link I was referencing [https://api.flutter.dev/flutter/material/Scrollbar-class.html](https://api.flutter.dev/flutter/material/Scrollbar-class.html). 

The following LIVE example at the link (doesn't have double scrollbars) does not have a ScrollConfiguration.
![image](https://user-images.githubusercontent.com/98419352/165987165-32a7cec4-4f86-4bfa-b181-779ef429349e.png)

However, the following LIVE example at the link (has/"**HAD**" one scrollbar on top of the other) does not have a ScrollConfiguration. I wrote **HAD**, because the double scrollbar was occurring when I originally posted this issue, but as I'm checking it now to get a picture for this response, the second scrollbar is not appearing. It is strange. Maybe it's a browser thing; I am currently and was using Edge. I just tried Chrome right now, and the LIVE example just shows an error saying:
> Missing browser features
> DartPad requires localStorage to be enabled. For more information, visit  [dart.dev/tools/dartpad/troubleshoot](https://dart.dev/tools/dartpad/troubleshoot)."*.

![image](https://user-images.githubusercontent.com/98419352/165987869-08dff56f-0e34-431b-a1ea-bea966f61f70.png)

In any case, thank you very much for your response to clear up that misunderstanding! Since it is working as intended, I'll close this issue.
