### ISSUE TITLE
[video_player]version 2.2.18 "Moves Android and iOS implementations to federated packages." causes compileSdkVersion issues in APK builds

### ISSUE THREAD

**Issue by haamaanaa** [flutter/flutter#102772]
## Steps to Reproduce

using pub.dev plugins that depend on https://pub.dev/packages/video_player/changelog 2.2.18+ causes android APK to depend on compileSdkVersion 31

version numbering should have reflected that with major update (like 2.3.0) as using dependency markup like

```
video_player: ^2.2.7
```

causes 2.2.18 to be taken into use automatically

## Logs

<details>
<summary>Logs</summary>

```
FAILURE: Build failed with an exception.

* What went wrong:

Execution failed for task ':app:checkDebugAarMetadata'. > A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction > The minCompileSdk (31) specified in a

dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties) is greater than this module's compileSdkVersion (android-30). Dependency: androidx.core:core:1.7.0.

AAR metadata file: /Users/.gradle/caches/transforms-2/files-2.1/1978c8540575e4da29114a40e6bf1a1a/core-1.7.0/META-INF/com/android/build/gradle/aar-metadata.properties.
```

</details>

**Comment by maheshmnj** [comment]
Hi @haamaanaa, I am quite not sure what this issue is proposing,  

> version numbering should have reflected that with major update (like 2.3.0) as using dependency markup like

Do you mean that the version 2.2.18+ requires to depend on compile Sdk 31 so the version should have been 2.3.0 ?

**Comment by haamaanaa** [comment]
> Hi @haamaanaa, I am quite not sure what this issue is proposing,
> 
> > version numbering should have reflected that with major update (like 2.3.0) as using dependency markup like
> 
> Do you mean that the version 2.2.18+ requires to depend on compile Sdk 31 so the version should have been 2.3.0 ?

yeah, exactly. Seems to me having been API level breaking change and as such could have been a major(er?) version update.

**Comment by maheshmnj** [comment]
Thanks for the clarification @haamaanaa, Considering the current version is `2.4.0`, I am quite not sure if it makes sense to update the older version, Perhaps updating the changelog to indicate that the app must use minSdk 31  in `2.2.18` release might help. I will leave this issue open for the team to decide.

cc: @stuartmorgan

**Comment by haamaanaa** [comment]
yeah, wasn't expecting to change happen in history of time :)

Just that maybe next time API breaking changes happen, this would be notified with major version change.

If there is possibilities to add info into to changeLog, that would probably be enough
