### ISSUE TITLE
[tool_crash] FileSystemException: Cannot create file, OS Error: Input/output error, errno = 5

### ISSUE THREAD

**Issue by danthienphuc** [flutter/flutter#102776]
## Command
```
flutter pub get
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Cannot create file, OS Error: Input/output error, errno = 5
```
#0      _File.throwIfError (dart:io/file_impl.dart:635:7)
#1      _File.createSync (dart:io/file_impl.dart:273:5)
#2

**Comment by codebird** [comment]
This could be many things, but I don't think it is Flutter related.

Check this:

https://github.com/flutter/flutter/issues/15711

**Comment by darshankawar** [comment]
@danthienphuc 
Is that the complete log you get ? If not, can you provide the entire error log ?
Do you get this error everytime you run `flutter pub get` ? Can you also provide `flutter doctor -v` ?

**Comment by Mrfaann** [comment]
Check again!
