### ISSUE TITLE
[packages][ci] Tests running both on `main` and `master` for the same hash

### ISSUE THREAD

**Issue by ditman** [flutter/flutter#102801]
It seems that we're running tests both in `main` and `master`, and the Github UI is getting updated TWICE (once with the successful run, then with the results of the run in the second branch. The first run logs **are lost**!).

Some "proof" here:

* https://cirrus-ci.com/task/6591136247578624 (master)
* https://cirrus-ci.com/task/6243828481916928 (main)

I only managed to get those two links because I saw the test restart in real-time, and I had already gotten the first link to complain in discord about being throttled. **THE GITHUB UI GETS COMPLETELY REWRITTEN** in `main`, and it seems that tests begin again.

| 🚨 Crazy status right now!
|---
| <img width="782" alt="Screen Shot 2022-04-28 at 7 34 39 PM" src="https://user-images.githubusercontent.com/1255594/165877382-00319eb0-e367-45d9-969f-9f888d7c8d9e.png">
| (Note: `release` having completed before `android-blah`, CaseyHillers' commit being merged without the previous tests are 🟢)

Some speculation:

May this be the root cause of the "release" action some times running without waiting for all tests to complete? (because they completed the first time, but not the second time!), also (maybe) why we were being throttled today?

* Possibly caused by this: https://github.com/flutter/flutter/issues/100557

Should we exclude the flutter/plugins:master branch from the `.cirrus.yml` file, somehow?

**Comment by ditman** [comment]
(I'd maybe P2 this thing 😱)

**Comment by ditman** [comment]
There's some environment variables set by Cirrus that can be used to skip/noop `flutter/packages|plugins:master`:

`$CIRRUS_REPO_OWNER` (in our case would be `flutter`)
`$CIRRUS_BRANCH`

And this: https://cirrus-ci.org/guide/writing-tasks/#conditional-task-execution (`only_if`?)

(This is a band-aid, ideally Cirrus shouldn't look at `master` at all!)

**Comment by stuartmorgan** [comment]
> (This is a band-aid, ideally Cirrus shouldn't look at `master` at all!)

I believe the expected behavior is that it runs on all branches by default. Otherwise things like release branches, PRs, etc. wouldn't get tests. I just forget that when it comes to things like having two identical branches...

**Comment by ditman** [comment]
@stuartmorgan I've just marked the `flutter/packages` as waiting for tree to go green, it should land shortly. Very cool link: https://cirrus-ci.com/github/flutter/packages ! Cirrus remembers! :P

**Comment by ditman** [comment]
flutter/packages and flutter/plugins seem to have recovered. Their `release` action seems to work too. Thanks for the super quick fix @stuartmorgan!!!

**Comment by stuartmorgan** [comment]
Fixing it was easy once we knew what was going on; you get all the credit here for figuring out why our test results have been acting strange. And halving the number of CI resources we are spending!

**Comment by ditman** [comment]
Tests are still being run multiple times, but now it's a little bit more rare than before. They're correctly *not* running for `master`, but they run for `main`, AND then **again** for the `tag` that gets pushed by the `release` action (if any).

See the following screenshot:

<img width="1196" alt="Screen Shot 2022-04-29 at 6 23 45 PM" src="https://user-images.githubusercontent.com/1255594/166085306-3bdf089a-1c31-4ad1-b499-5fc45b53ec46.png">

More info: https://cirrus-ci.com/github/flutter/packages

**Comment by stuartmorgan** [comment]
I'll send you a PR in a second; we already filter that in flutter/plugins.

**Comment by ditman** [comment]
@stuartmorgan beat me to it haha
