### ISSUE TITLE
📚 `cupertino` library tracker

### ISSUE THREAD

**Issue by guidezpl** [flutter/flutter#102812]
## `cupertino` component tracker

TODO: audit
TODO: add missing components, e.g. iOS Modal Sheets, Menus, different styles of pickers, etc. See links with `[-]` in this issue's source

HIG¹                       | `cupertino` component²               | Audit                                     | [`.adaptive`] constructor                         | API doc HIG link | API doc dartpad | Gallery demo
---                        | ---                                  | ---                                       | ---                                               | ---              | ---             | ---
[Action Sheets]            | [`CupertinoActionSheet`]             |                                           |                                                   | ✅                | ✅              | [✅][gallery-alerts]
[Alerts]                   | [`CupertinoAlertDialog`]             |                                           |  #102811                                          | ✅                | ✅              | [✅][gallery-alerts]
[Buttons]                  | [`CupertinoButton`]                  |                                           |                                                   | ✅                | ✅              | [✅][gallery-buttons]
[Context Menus]            | [`CupertinoContextMenu`]             |                                           |                                                   | ✅                | ✅              | [✅][gallery-context-menu]
[Navigation Bars]          | [`CupertinoNavigationBar`]           |                                           |                                                   | ✅                | ✅              | [❌][gallery-missing-issue]
[Navigation Bars]          | [`CupertinoSliverNavigationBar`]     |                                           |                                                   | ✅                | ✅              | [✅][gallery-navigation-bar]
[Pickers]                  | [`CupertinoDatePicker`]              |                                           |                                                   | ✅                | ✅              | [✅][gallery-picker]
[Pickers]                  | [`CupertinoPicker`]                  |                                           |                                                   | ✅                | ✅              | [❌][gallery-missing-issue]
[Pickers]                  | [`CupertinoTimerPicker`]             | Missing [Full-size `CupertinoDatePicker`] |                                                   | ✅                | ✅              | [✅][gallery-picker]
[Refresh Content Controls] | [`CupertinoActivityIndicator`]       |                                           | [`CircularProgressIndicator.adaptive`]            | ✅                | ✅              | [✅][gallery-activity-indicator]
N/A                        | [`CupertinoScrollbar`]               |                                           |                                                   | ✅                | ✅              | [❌][gallery-missing-issue]
[Search Bars]              | [`CupertinoSearchTextField`]         |                                           |                                                   | ✅                | ✅              | [❌][gallery-missing-issue]
[Segmented Controls]       | [`CupertinoSegmentedControl`]        |                                           |                                                   | ✅                | ✅              | [✅][gallery-segmented-control]
[Segmented Controls]       | [`CupertinoSlidingSegmentedControl`] |                                           |                                                   | ✅                | ✅              | [✅][gallery-segmented-control]
[Sliders]                  | [`CupertinoSlider`]                  |                                           | [`Slider.adaptive`]                               | ✅                | ✅              | [✅][gallery-slider]
[Switches]                 | [`CupertinoSwitch`]                  |                                           | [`Switch.adaptive`] & [`SwitchListTile.adaptive`] | ✅                | ✅              | [✅][gallery-switch]
[Tab Bars]                 | [`CupertinoTabBar`]                  |                                           |                                                   | ✅                | ✅              | [✅][gallery-tab-bar]
[Text Fields]              | [`CupertinoTextField`]               |                                           |                                                   | ✅                | ✅              | [✅][gallery-text-field]
*Proposed new components*  |               
N/A                        | #102813                              |                                           | #102809                                           |                   |                 |
N/A                        | #61789                               |                                           | #102810                                           |                   |                 |
[Tables]                   | [`CupertinoListSection`]             |                                           |                                                   |                   |                 |
[Tables]                   | [`CupertinoListTile`]                |                                           |                                                   |                   |                 |

¹: HIG guidelines link out to `UIKit` and `SwiftUI` developer docs. Look for "For developer guidance, see...".
²: This table includes a subset of [all `cupertino` widgets](https://master-api.flutter.dev/flutter/cupertino/cupertino-library.html). It does not include:
- building-block widgets e.g. [`CupertinoDialogAction`](https://api.flutter.dev/flutter/cupertino/CupertinoDialogAction-class.html), used to build these components
- non-component widgets e.g. [`CupertinoPageTransition`](https://api.flutter.dev/flutter/cupertino/CupertinoPageTransition-class.html) and [`CupertinoPageScaffold`](https://api.flutter.dev/flutter/cupertino/CupertinoPageScaffold-class.html). 

[gallery]: https://gallery.flutter.dev
[`.adaptive`]: https://github.com/flutter/flutter/issues/33830

[gallery-missing-issue]: https://github.com/flutter/gallery/issues/668
[gallery-activity-indicator]: https://gallery.flutter.dev/#/demo/cupertino-activity-indicator
[gallery-alerts]: https://gallery.flutter.dev/#/demo/cupertino-alerts
[gallery-buttons]: https://gallery.flutter.dev/#/demo/cupertino-buttons
[gallery-context-menu]: https://gallery.flutter.dev/#/demo/cupertino-context-menu
[gallery-navigation-bar]: https://gallery.flutter.dev/#/demo/cupertino-navigation-bar
[gallery-picker]: https://gallery.flutter.dev/#/demo/cupertino-picker
[gallery-segmented-control]: https://gallery.flutter.dev/#/demo/cupertino-segmented-control
[gallery-slider]: https://gallery.flutter.dev/#/demo/cupertino-slider
[gallery-switch]: https://gallery.flutter.dev/#/demo/cupertino-switch
[gallery-tab-bar]: https://gallery.flutter.dev/#/demo/cupertino-tab-bar
[gallery-text-field]: https://gallery.flutter.dev/#/demo/cupertino-text-field

[`Slider.adaptive`]: https://master-api.flutter.dev/flutter/material/Slider/Slider.adaptive.html
[`Switch.adaptive`]: https://master-api.flutter.dev/flutter/material/Switch/Switch.adaptive.html
[`SwitchListTile.adaptive`]: https://master-api.flutter.dev/flutter/material/SwitchListTile/SwitchListTile.adaptive.html
[`CircularProgressIndicator.adaptive`]: https://master-api.flutter.dev/flutter/material/CircularProgressIndicator/CircularProgressIndicator.adaptive.html
[`CupertinoActionSheet`]: https://master-api.flutter.dev/flutter/cupertino/CupertinoActionSheet-class.html
[`CupertinoActivityIndicator`]: https://master-api.flutter.dev/flutter/cupertino/CupertinoActivityIndicator-class.html
[`CupertinoAlertDialog`]: https://master-api.flutter.dev/flutter/cupertino/CupertinoAlertDialog-class.html
[`CupertinoButton`]: https://master-api.flutter.dev/flutter/cupertino/CupertinoButton-class.html
[`CupertinoContextMenu`]: https://master-api.flutter.dev/flutter/cupertino/CupertinoContextMenu-class.html
[`CupertinoDatePicker`]: https://master-api.flutter.dev/flutter/cupertino/CupertinoDatePicker-class.html
[`CupertinoNavigationBar`]: https://master-api.flutter.dev/flutter/cupertino/CupertinoNavigationBar-class.html
[`CupertinoSliverNavigationBar`]: https://master-api.flutter.dev/flutter/cupertino/CupertinoSliverNavigationBar-class.html
[`CupertinoPicker`]: https://master-api.flutter.dev/flutter/cupertino/CupertinoPicker-class.html
[`CupertinoScrollbar`]: https://api.flutter.dev/flutter/cupertino/CupertinoScrollbar-class.html
[`CupertinoSearchTextField`]: https://master-api.flutter.dev/flutter/cupertino/CupertinoSearchTextField-class.html
[`CupertinoSegmentedControl`]: https://master-api.flutter.dev/flutter/cupertino/CupertinoSegmentedControl-class.html
[`CupertinoSlider`]: https://master-api.flutter.dev/flutter/cupertino/CupertinoSlider-class.html
[`CupertinoSlidingSegmentedControl`]: https://master-api.flutter.dev/flutter/cupertino/CupertinoSlidingSegmentedControl-class.html
[`CupertinoSwitch`]: https://master-api.flutter.dev/flutter/cupertino/CupertinoSwitch-class.html
[`CupertinoTabBar`]: https://master-api.flutter.dev/flutter/cupertino/CupertinoTabBar-class.html
[`CupertinoTextField`]: https://master-api.flutter.dev/flutter/cupertino/CupertinoTextField-class.html
[`CupertinoTimerPicker`]: https://master-api.flutter.dev/flutter/cupertino/CupertinoTimerPicker-class.html

[`CupertinoListSection`]: https://github.com/flutter/flutter/pull/78732
[`CupertinoListTile`]: https://github.com/flutter/flutter/pull/78732
[Full-size `CupertinoDatePicker`]: https://github.com/flutter/flutter/pull/93130

[Navigation Bars]: https://developer.apple.com/design/human-interface-guidelines/ios/bars/navigation-bars/
[Search Bars]: https://developer.apple.com/design/human-interface-guidelines/ios/bars/search-bars/
[-]: https://developer.apple.com/design/human-interface-guidelines/ios/bars/sidebars/
[Tab Bars]: https://developer.apple.com/design/human-interface-guidelines/ios/bars/tab-bars/

[Action Sheets]: https://developer.apple.com/design/human-interface-guidelines/ios/views/action-sheets/
[-]: https://developer.apple.com/design/human-interface-guidelines/ios/views/activity-views/
[Alerts]: https://developer.apple.com/design/human-interface-guidelines/ios/views/alerts/
[-]: https://developer.apple.com/design/human-interface-guidelines/ios/views/collections/
[-]: https://developer.apple.com/design/human-interface-guidelines/ios/views/image-views/
[-]: https://developer.apple.com/design/human-interface-guidelines/ios/views/pages/
[-]: https://developer.apple.com/design/human-interface-guidelines/ios/views/popovers/
[-]: https://developer.apple.com/design/human-interface-guidelines/ios/views/scroll-views/
[-]: https://developer.apple.com/design/human-interface-guidelines/ios/views/sheets/
[-]: https://developer.apple.com/design/human-interface-guidelines/ios/views/split-views/
[Tables]: https://developer.apple.com/design/human-interface-guidelines/ios/views/tables/
[-]: https://developer.apple.com/design/human-interface-guidelines/ios/views/text-views/
[-]: https://developer.apple.com/design/human-interface-guidelines/ios/views/web-views/

[Buttons]: https://developer.apple.com/design/human-interface-guidelines/ios/controls/buttons/
[-]: https://developer.apple.com/design/human-interface-guidelines/ios/controls/color-wells/
[Context Menus]: https://developer.apple.com/design/human-interface-guidelines/ios/controls/context-menus/
[-]: https://developer.apple.com/design/human-interface-guidelines/ios/controls/edit-menus/
[-]: https://developer.apple.com/design/human-interface-guidelines/ios/controls/page-controls/
[Pickers]: https://developer.apple.com/design/human-interface-guidelines/ios/controls/pickers/
[-]: https://developer.apple.com/design/human-interface-guidelines/ios/controls/progress-indicators/
[Refresh Content Controls]: https://developer.apple.com/design/human-interface-guidelines/ios/controls/refresh-content-controls/
[Segmented Controls]: https://developer.apple.com/design/human-interface-guidelines/ios/controls/segmented-controls/
[Sliders]: https://developer.apple.com/design/human-interface-guidelines/ios/controls/sliders/
[-]: https://developer.apple.com/design/human-interface-guidelines/ios/controls/steppers/
[Switches]: https://developer.apple.com/design/human-interface-guidelines/ios/controls/switches/
[Text Fields]: https://developer.apple.com/design/human-interface-guidelines/ios/controls/text-fields/

### See also
- [Flutter-SwiftUI widget catalog](https://github.com/flutter/platform_tests/tree/master/ios_widget_catalog_compare), for audit and testing purposes
- [`flutter_platform_widgets`](https://pub.dev/packages/flutter_platform_widgets), a  package which has implemented 24 platform adaptive widgets
- https://docs.flutter.dev/development/ui/widgets/cupertino, a mostly complete view of all `cupertino` widgets
- https://github.com/flutter/flutter/projects/124, "iOS Platform - Cupertino widget review"
- https://github.com/flutter/flutter/issues/94821

cc @jmagman

**Comment by Piinks** [comment]
This issue has some super helpful resources and links.

We're now tracking issues for updating the library in the [Cupertino Refresh project](https://github.com/orgs/flutter/projects/155/views/6?groupedBy%5BcolumnId%5D=123151514).

I've added this umbrella issue to the project to preserve it as a reference, and will close this since we are not tracking the work in this location anymore.
