### ISSUE TITLE
onDragDown, onDragDownMove, on DragCancel

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#1028]
Dismissable, Drawer, and Switch need a way to start with a drag but end with a tap.

**Comment by abarth** [comment]
onDragDownMove is kind of subtle.  For the first onDragUpdate, we give you all the delta we've accumulated up until that point, which might be redundant with the delta you get in onDragDownMove.

**Comment by abarth** [comment]
Fixed with gesture arena teams.
