### ISSUE TITLE
Flutter camera widget - Image totaly/partly white(even exposure time is set to min) on Pixel 4

### ISSUE THREAD

**Issue by NotThatFunny** [flutter/flutter#102817]
Hello everyone!

currently wrote an flutter app which uses the camera package and the code of the link below to take a picture.
https://docs.flutter.dev/cookbook/plugins/picture-using-camera#complete-example

The problem is when I use it on a pixel 4 I get a total white image(exposure time to high?) Even if I set the exposure time to min while it is working on my OnePlus6 fine.

Is this a known issue or is the example outdatet?

Thank you already  very much an have a nice weekend!

**Comment by darshankawar** [comment]
@NotThatFunny 
Can you try the plugin [example](https://github.com/flutter/plugins/tree/main/packages/camera/camera/example) as well and see if you still get same behavior ?

**Comment by NotThatFunny** [comment]
So I tried now the example you send me as well and still the same issue. The exposure is just way to high for the pixel and when I set it to min it does look okay(not even good) on the pixel but really bad on all the other phones.

**Comment by darshankawar** [comment]
@NotThatFunny 
There's similar open issue describing your case related to Pixel phones, https://github.com/flutter/flutter/issues/76481, so please follow-up in it for further updates. Closing this as a duplicate. If you disagree, write in comments and I'll reopen it.
