### ISSUE TITLE
It appears that the downloaded file is corrupt; please try again.

### ISSUE THREAD

**Issue by nazilaeshghi** [flutter/flutter#102894]
git clone -b master https://github.com/flutter/flutter.git
./flutter/bin/flutter --version

"It appears that the downloaded file is corrupt; please try again."

## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

<details>
<summary>Logs</summary>

```
```

```
```

</details>

**Comment by darshankawar** [comment]
@nazilaeshghi 
Can you provide the entire error log ? Which file is it pointing to, that throws this error ?

Also, you can work around this by deleting your cache, via:

```
rm -rf /home/ryan/programming/flutter/bin/cache
/home/ryan/programming/flutter/bin/flutter --version
```

And try again to see if it works for you.
