### ISSUE TITLE
IAP - How to catch billing's reponseCode

### ISSUE THREAD

**Issue by giovanni256** [flutter/flutter#102874]
Hi there.

I'm writing a subscription method using the [official package](https://pub.dev/packages/in_app_purchase).
Everything seems to work fine on Android but I can't catch the Billing's ResponseCode.

When the user wants to but the subscription, I launch this code:
`_inAppPurchase.buyNonConsumable(purchaseParam: purchaseParam);`

So the Play Store modal is shown and it works.
If an error occurs, this will be thrown in the console.
Now I want to catch the error in order to work on it.
Actually I only get this exceptions in the console:

```
W/ProxyBillingActivity( 5851): Activity finished with resultCode 0 and billing's responseCode: 1
W/BillingHelper( 5851): Couldn't find purchase lists, trying to find single data.
W/BillingHelper( 5851): Received a bad purchase data.
W/BillingHelper( 5851): Couldn't find single purchase data as well.
```

Flutter doctor:
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.10.5, on Microsoft Windows [Versione 10.0.19042.1526], locale it-IT)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2021.1)
[√] Connected device (4 available)
[√] HTTP Host Availability

! Doctor found issues in 1 category.
```

**Comment by darshankawar** [comment]
@giovanni256 
There's similar open issue describing your case, https://github.com/flutter/flutter/issues/32512, so please follow-up in it for further updates.
Closing this as a duplicate.
