### ISSUE TITLE
[auto flake bot] Link to detailed flake log instead of a success build

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#102848]
There are two types of flake that we have been collecting: flake from multiple builds and flake from multiple test step within a single build(https://github.com/flutter/flutter/wiki/Reducing-Test-Flakiness).

The flake bot collects flaky builds of both and creates bugs by listing recent ones. No issue with the first case, as it links to the failed build. But for the second case, the bot current links to the single (finally green) build though it flakes on the test step (e.g. https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_ios%20ios_picture_cache_complexity_scoring_perf__timeline_summary/129).

This is confusing for people not familiar with the logics, and we should update the bot to point to the detailed flake log instead.

Issue: https://github.com/flutter/flutter/issues/102236

**Comment by Nike682631** [comment]
@keyonghan  is this issue available to work on?

**Comment by keyonghan** [comment]
@Nike682631 Yeah, this is still available. But I believe this involves internal bigquery tables.. I am removing the good first contribution label. Thanks for your interest! Please feel free to pick up other bugs.

**Comment by keyonghan** [comment]
Instead, https://flutter-review.googlesource.com/c/recipes/+/46720 to flag the flake test step.
