### ISSUE TITLE
Update SceneBuilder.pushOpacity and PaintingContext.pushOpacity

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#102888]
The Flutter framework and dart:ui has methods called `PaintingContext.pushOpacity` and `SceneBuilder.pushOpacity`  (respectively) used to create opacity layers today. Unfortunately, these methods actually take an alpha. In order to support wider opacity values, we'd like to instead have methods which accept a float/double and avoid int truncation. We have a few advantages, namely that in the corpus of g3 code I've looked at, no one seems to use these methods directly.

* We could roll a hard breaking change where we change the type of the engine APIs to accept a double, then do a similar change in the framework. This would be disruptive during the landing, but would lead us quickly to an ideal state. Code not in g3 or the SDK would not be migrated, though this could potentially be `dart fix`'d since the conversion from alpha to opacity is trivial.

* Alternatively, we could introduce new APIs that do the right thing, and make the old APIs delegate to these new ones along with a deprecation period. Unfortunately its hard to get a better name than `pushOpacity`. We'd basically need to introduce `pushOpacity2`. I'm calling it `pushOpacityValue` right now which is just redundant.

This came up in https://github.com/flutter/flutter/pull/102687 

Engine change would be: https://github.com/flutter/engine/pull/33035

(We should consider similar changes for color to support wider gamuts )

**Comment by jonahwilliams** [comment]
Also important to note that both Skia and Impeller (I think) are using a float for opacity, and today the engine converts the framework provided alpha value to a float:

https://github.com/flutter/engine/blob/main/flow/layers/opacity_layer.cc#L95-L105

**Comment by flar** [comment]
For a method argument you could take both double? and int? and assert that one and only one is specified, but I think just doing the breaking change is better, especially if we want to add a compositing argument like the other "pushModifier" methods.

**Comment by jonahwilliams** [comment]
We're not planning to do this in the near term, as the engine APIs still treat colors as a 32 bit value and a migration to four floats would be a larger effort.
