### ISSUE TITLE
WebSocket Connection with some delay after build for web

### ISSUE THREAD

**Issue by rrrovalle** [flutter/flutter#102840]
Hi guys,

anyone knows about what can make this delay happen? When running it locally it runs fast but when I build for web and run it using a python server (python -m http.server 8000) it's really slow.

For better undestanding I'm using a webapp to connect with another and send data (json) through wss connection..

**Comment by darshankawar** [comment]
@rrrovalle 
Assuming you are using `web_socket_channel` package for websocket connection, I suggest you to ask this question in dedicated repo: https://github.com/dart-lang/web_socket_channel/issues

Closing from here. If you get re-directed here, write in comments and I'll reopen it.
