### ISSUE TITLE
[Impeller] Implement the FragmentProgram API.

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#102853]
- [x] https://github.com/flutter/flutter/pull/102674
- [x] When Impeller is enabled with the tool flag `--enable-impeller`, the `impellerc` invocation should pass the correct backend-specific flags
- [x] When Impeller is enabled in the Engine, the Engine should assume that byte buffers passed to the FragmentProgram API are shaders that are appropriate for the current backend rather than spir-v bytecode that has to be transpiled.
- [x] https://github.com/flutter/flutter/issues/104750
- [x] https://github.com/flutter/flutter/issues/104776
- [ ] https://github.com/flutter/flutter/issues/105538
- [x] https://github.com/flutter/flutter/issues/113714
- [ ] https://github.com/flutter/flutter/issues/113715
- [ ] https://github.com/flutter/flutter/issues/113719
- [ ] https://github.com/flutter/flutter/issues/115794

**Comment by zanderso** [comment]
Assigning to myself initially to finish the first tickybox.

**Comment by bdero** [comment]
I'm _very_ excited about this feature.

**Comment by chinmaygarde** [comment]
Closing this as done for Metal and we have separate issues for other backends as we attempt them.
