### ISSUE TITLE
Cupertino style radio button (single-selection)

### ISSUE THREAD

**Issue by guidezpl** [flutter/flutter#102813]
![image](https://user-images.githubusercontent.com/6655696/165897419-aa97457b-4c2a-42b8-b557-e86c91256b88.png)

See #61789 for multi-selection

**Comment by guidezpl** [comment]
@MitchellGoodwin Thanks for your work! I'm going to reopen to keep track of the iOS-specific uncircle checkbox style (see issue description). Do you think it would make sense as an additional parameter on `CupertinoRadio`?

**Comment by MitchellGoodwin** [comment]
> @MitchellGoodwin Thanks for your work! I'm going to reopen to keep track of the iOS-specific checkbox style (see issue description). Do you think it would make sense as an additional parameter on `CupertinoRadio`?

@guidezpl I made it look like the radio button described in the HIGs, but if making it look like a checkbox is needed, I don't see the harm in adding it as a parameter.

**Comment by guidezpl** [comment]
Yeah, the HIG don't have a specific page for this checkbox style, they're strewn about other pages (e.g. the tables page). Sg
