### ISSUE TITLE
BackdropFilter discrepancy between simulator and physical device

### ISSUE THREAD

**Issue by xster** [flutter/flutter#10284]
Given

```dart
import 'dart:ui';
import 'package:flutter/material.dart';

void main() {
  runApp(new MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: 'Flutter Demo',
      theme: new ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: new Scaffold(
        body: new Stack(
          children: <Widget>[
            new ListView(children: new List<Widget>.filled(
              10,
              new Padding(
                padding: const EdgeInsets.symmetric(horizontal: 16.0, vertical: 2.0),
                child: new Card(
                  child: new SizedBox(
                    height: 160.0,
                    child: const Center(child: const Text('blah')),
                  )
                ),
              )
            )),
            new ClipRect(
              child: new BackdropFilter(
                filter: new ImageFilter.blur(sigmaX: 5.0, sigmaY: 5.0),
                child:
                  new Container(
                    height: 60.0,
                    padding: const EdgeInsets.only(top: 16.0),
                    decoration: const BoxDecoration(
                      color: const Color(0xAAF7F7F7),
                      border: const Border(
                        bottom: const BorderSide(color: const Color(0xAAEEEEEE)),
                      ),
                    ),
                    child: const Center(child: const Text('Title')),
                  ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}
```

Outcome is different between simulator and device (both on 10.3.1)
Simulator blurs:
![flutter_02](https://cloud.githubusercontent.com/assets/156888/26382307/444f97da-3fe0-11e7-9367-8aae65b26ccf.png)

Blur effect doesn't seem to work on real device:
![flutter_01](https://cloud.githubusercontent.com/assets/156888/26382319/54419f4e-3fe0-11e7-8d40-ee34e2a6008f.png)

Curiously works on physical Android devices

**Comment by eseidelGoogle** [comment]
Simulator uses Skia's software backend.  All our other configurations use GPU (OpenGL) backends.  Strange that blurring is different between iOS hardware and Android Hardware.  I would expect those to use very similar Skia code.

**Comment by eseidelGoogle** [comment]
I've added dependency: skia and @chinmaygarde will track with Skia in his regular meetings.

**Comment by chinmaygarde** [comment]
> Strange that blurring is different between iOS hardware and Android Hardware. I would expect those to use very similar Skia code.

Perhaps Skia uses an extension. I am not sure. Will bring this up.

**Comment by xster** [comment]
Tested on some more Android including some crummy old ones. Seems consistent so far.

**Comment by eseidelGoogle** [comment]
Sounds like we should escalate to a skia bug?

**Comment by sethladd** [comment]
Is this the related Skia bug? https://bugs.chromium.org/p/skia/issues/detail?id=6753

Just ran into this when prepping a demo. The blur effect doesn't work on iOS hardware, ironically.

**Comment by markmclaren2** [comment]
Any chance of some feedback on this issue?  Is it a Skia bug?

**Comment by eseidelGoogle** [comment]
Is this what's causing the background blur on Nav Bars in the cupertino demo not to show up blurred on physical iOS devices?  @cbracken.

**Comment by cbracken** [comment]
@eseidel yep. I've just cross-linked that bug to this one.

**Comment by xster** [comment]
Split the iOS specific bug to https://bugs.chromium.org/p/skia/issues/detail?id=7412. Since  https://bugs.chromium.org/p/skia/issues/detail?id=6753 had multiple nuanced cross-platform issues.

**Comment by eseidelGoogle** [comment]
@sethladd was just asking me if we have any updates on this bug? :)  This is very visible in our iOS/Cupertino-themed demos.

**Comment by Hixie** [comment]
@brianosman increased its priority last week, see https://bugs.chromium.org/p/skia/issues/detail?id=7412.

**Comment by brianosman** [comment]
Yes, we've identified the problem, just trying to figure out a good solution. (And snow/ice kept me out of the office the last two days, so I didn't have access to an iOS device for testing). The quick workaround is to always start drawing offscreen (even just throwing an extra saveLayer()/restore() pair in). Because of how the initial FBO is being created and passed to Skia in the iOS GL code, Skia thinks it can't make a copy, so anything drawn to that first layer becomes unreadable when we try to do the blur.

**Comment by xster** [comment]
Super awesome. Thanks @brianosman!

**Comment by xster** [comment]
Tested. Confirm this works!

**Comment by sethladd** [comment]
Awesome!
