### ISSUE TITLE
[flutter_plugin_tools] Support example/test/ in `test` command

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#102845]
Currently we're only running for `<package>/test/`; we should include all the examples as well so that examples can have their tests run. This is needed for some packages in flutter/packages, we actually have a couple in flutter/plugins that we aren't running, and as we adopt code-excerpt more we'll likely have more small tests of example code.

**Comment by chunhtai** [comment]
Is the tool currently run flutter drive? if not we should probably add it too, the pointer_interceptor/example tests are driver tests

**Comment by stuartmorgan** [comment]
A different command (`drive-examples`) runs flutter driver tests. `test` should really be called something like `dart-unit-test` since it's specific to that.

**Comment by stuartmorgan** [comment]
I filed https://github.com/flutter/flutter/issues/102851. The lack of dinner tests is just a CI config issue.
