### ISSUE TITLE
Benchmarks failing to run on lower-end devices

### ISSUE THREAD

**Issue by iskakaushik** [flutter/flutter#102939]
@keyonghan : @godofredoc  mentioned that we had some issues running benchmarks on lower-end devices. Let us use this issue to track getting them running successfully. Could you please paste any logs from the failing runs for me to investigate?

**Comment by keyonghan** [comment]
Could you provide some more context? Is this related to mac/ios arm64 ones? If yes, here are the current blocking test: https://github.com/flutter/flutter/issues/87508#issuecomment-1101764380

**Comment by keyonghan** [comment]
@iskakaushik Is the lower-end device here limited to Samsung A02? Or does MotoG4 work? One blocker on Samsung A02 is the capacity (current only one bot in staging, and is quarantined now: https://github.com/flutter/flutter/issues/103668).

**Comment by iskakaushik** [comment]
Moto G4 is also currently considered mid-tier per Android's classification standard. Per my conversation with @godofredoc we have many more A02 devices, and the main blocker is failures because of OOMs. Is that right?

**Comment by keyonghan** [comment]
> Moto G4 is also currently considered mid-tier per Android's classification standard. Per my conversation with @godofredoc we have many more A02 devices, and the main blocker is failures because of OOMs. Is that right?

We have many in the lab, but not set up yet in the CI. Currently we have only on in the staging pool.
Could you suggest some tests from our CI (which are close to what you plan to enable) that we can enable to validate they pass?

**Comment by keyonghan** [comment]
Another issue with A02 deices is that they need to be connected with some samsung account, which makes the setup non-trivial.

**Comment by iskakaushik** [comment]
The test `Linux_android_flutter_gallery__transition_perf` is similar to the ones that I plan on enabling. For example [see this](https://flutter-flutter-perf.skia.org/e/?queries=sub_result%3D90th_percentile_frame_rasterizer_time_millis%26test%3DLinux_android_flutter_gallery__transition_perf).

> Another issue with A02 deices is that they need to be connected with some samsung account, which makes the setup non-trivial.

Ah, I did not realize this. I do not have an opinion on what low-tier device we have tests running on, just that we run them on at lease one low-tier device. Godofredo mentioned that we already have the A02 devices and that these may be the easiest to get started with.

**Comment by yusuf-goog** [comment]
If we are planning on needed any new device, especially the A02 or other, please allow for generous lead time. As @keyonghan  mentioned, setup and install is not always simple.

**Comment by keyonghan** [comment]
Validated `Linux_android_flutter_gallery__transition_perf` runs successfully in a [Samsung A02 testbed](https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-linux-26):
https://luci-milo.appspot.com/raw/build/logs.chromium.org/flutter/led/keyonghan_google.com/1ae754fca914df13c11cfad3232487027a4dc011c57ccf57dbaf13363340f591/+/build.proto

**Comment by keyonghan** [comment]
I am working to suppress logs, and we can try enabling after that.

In addition to `Linux_android_flutter_gallery__transition_perf`, any other benchmark you want to enable in A02?

**Comment by keyonghan** [comment]
@iskakaushik Does this build look good to you regarding log suppress? https://ci.chromium.org/raw/build/logs.chromium.org/flutter/led/keyonghan_google.com/1ce781d6397e955508e42f71600fc3d17b61e56aa68fc40598b0d6e16afc6074/+/build.proto?server=chromium-swarm.appspot.com

**Comment by iskakaushik** [comment]
@keyonghan  this looks perfect. Couple of follow-up questions:

1. I want to make sure that this is not the default for all the benchmarks. Will there be a flag that I have to use in `ci.yaml`?
2. For any test that has this, can we ensure that they can not be run in pre-submits? These should only be run in post-submits. Even if someone were to change the `ci.yaml`.

Thanks

**Comment by iskakaushik** [comment]
> This can be controlled by adding `presubmit: false` in the ci.yaml target.

If a user were to change this to `presubmit: true` as a part of their PR, they would still not be able to see the logs, right?

**Comment by keyonghan** [comment]
> > This can be controlled by adding `presubmit: false` in the ci.yaml target.
> 
> If a user were to change this to `presubmit: true` as a part of their PR, they would still not be able to see the logs, right?

No. Both pre-submit and post-submit shares the same recipe which suppress logs whenever it is defined in the `SUPPRESS_LOG_BUILDER_LIST`

**Comment by flar** [comment]
> Could we have the following benchmarks also run please:
> 
> ```
> Linux_android new_gallery__crane_perf
> Linux_android new_gallery__transition_perf
> ```
> 
> I was asking around and looks like @flar might also have some thoughts on good candidate benchmarks for lower-end devices.

Potentially one of the complex scrolling perf benchmarks and the opacity performance benchmark.

**Comment by keyonghan** [comment]
https://flutter-review.googlesource.com/c/infra/+/30445 to enable below five benchmarks in staging.
```
flutter_gallery__transition_perf
new_gallery__crane_perf
new_gallery__transition_perf
complex_layout_scroll_perf__timeline_summary
opacity_peephole_one_rect_perf__e2e_summary
```

**Comment by zanderso** [comment]
Closing as stale.
