### ISSUE TITLE
[Flutter Doctor] Mac M1 CocoaPods installed but not working.

### ISSUE THREAD

**Issue by SportApps** [flutter/flutter#102911]
I am not able to run a flutter app that has CocoaPods on my Mac M1 computer.

Flutter run:

   Warning: CocoaPods is installed but broken. Skipping pod install.
  You appear to have CocoaPods installed but it is not working.
  This can happen if the version of Ruby that CocoaPods was installed with is different from the one being used to invoke it.
  This can usually be fixed by re-installing CocoaPods.
To re-install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.
ruby -v

ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.arm64e-darwin20]

**UPDATE: I updated the ruby version with home-brew but it still gives the same error:**

`ruby -v ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-darwin20]`

**Update 2.0 I tried installing CocoaPods with homebrew**

`brew install cocoapods --build-from-source`
`then: brew link --overwrite cocoapods`

`flutter clean...`
Restarting Android Studio ...

And same error!

**Update 3.0 Combination of new Ruby 3.1.2p20 with ffi**

`brew unlink cocoapods`

`brew uninstall cocoapods`

Try_ing this: https://medium.com/p-society/cocoapods-on-apple-silicon-m1-computers-86e05aa10d3e_

Opening terminal using Rosetta

`sudo arch -x86_64 gem install ffi`

`sudo gem install CocoaPods`

--> Says that CocoaPods are not installed

So I try this approach:

https://stackoverflow.com/a/66842555/18936943

`1- arch -x86_64 sudo gem install cocoapods -n /usr/local/bin`

`2- arch -x86_64 sudo gem install ffi`

`3- pod install`

```
/usr/local/lib/ruby/gems/3.1.0/gems/cocoapods-1.11.3/lib/cocoapods/command.rb:128:in `git_version': Failed to extract git version from `git --version` ("") (RuntimeError)
        from /usr/local/lib/ruby/gems/3.1.0/gems/cocoapods-1.11.3/lib/cocoapods/command.rb:140:in `verify_minimum_git_version!'
        from /usr/local/lib/ruby/gems/3.1.0/gems/cocoapods-1.11.3/lib/cocoapods/command.rb:49:in `run'
        from /usr/local/lib/ruby/gems/3.1.0/gems/cocoapods-1.11.3/bin/pod:55:in `<top (required)>'
        from /usr/local/bin/pod:25:in `load'
        from /usr/local/bin/pod:25:in `<main>'
```
STILL NO SOLUTION...

Most recent flutter doctor: 

```
timknogel@Tims-MacBook-Pro multiculturalapp % flutter doctor -v
[✓] Flutter (Channel stable, 2.10.5, on macOS 11.5.1 20G80 darwin-arm, locale en-ES)
    • Flutter version 2.10.5 at /Users/timknogel/FlutterDev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (13 days ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/timknogel/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ✗ CocoaPods installed but not working.
        You appear to have CocoaPods installed but it is not working.
        This can happen if the version of Ruby that CocoaPods was installed with is different from the one being used to invoke it.
        This can usually be fixed by re-installing CocoaPods.
      To re-install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] VS Code (version 1.66.2)
    • VS Code at /Users/timknogel/Desktop/Visual Studio Code.app/Contents
    • Flutter extension version 3.38.1

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 100.0.4896.127

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```
`which ruby`

/usr/bin/ruby
My machine: MacBook Pro (13-inch, M1, 2020) Mac OS big sur

**Update 4.0 I updated Mac to Mac OS Monterey to install Roseta 2.0** https://github.com/flutter/flutter/wiki/Developing-with-Flutter-on-Apple-Silicon

`sudo softwareupdate --install-rosetta --agree-to-license`
Then I tried again:

`sudo gem uninstall CocoaPods`

`brew install cocoapods
`
`brew link --overwrite cocoapods`
Still same error.
`
brew unlink cocoapods`

```
brew uninstall cocoapods`
```
sudo gem install CocoaPods`
Restarting IDE...

Same error.

Then I tried again with the standard ruby version and that failed again.

Flutter doctor

```
[✓] Flutter (Channel stable, 2.10.5, on macOS 11.5.1 20G80 darwin-arm, locale en-ES)
• Flutter version 2.10.5 at /Users/timknogel/FlutterDev/flutter
• Upstream repository https://github.com/flutter/flutter.git
• Framework revision 5464c5bac7 (11 days ago), 2022-04-18 09:55:37 -0700
• Engine revision 57d3bac3dd
• Dart version 2.16.2
• DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/timknogel/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] VS Code (version 1.66.2)
    • VS Code at /Users/timknogel/Desktop/Visual Studio Code.app/Contents
    • Flutter extension version 3.38.1

[✓] Connected device (2 available)
    • iPhone 13 (mobile) • 3253AB15-FB90-45F5-93CD-5A95FC029075 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-2
      (simulator)
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 100.0.4896.127
    ! Error: Failed to prepare device for development. This operation can fail if the version of the OS on the device is incompatible
      with the installed version of Xcode. You may also need to restart your mac and device in order to correctly detect compatibility.
      (code 806)

[✓] HTTP Host Availability
    • All required HTTP hosts are available

```

Flutter run -v result:

[flutter run v.txt](https://github.com/flutter/flutter/files/8602974/flutter.run.v.txt)

**Update 6.0 Git related?**

Referring to this post:
https://github.com/CocoaPods/CocoaPods/issues/8661

I installed git with homebrew just in case CocoaPods don't work because of the git version.

Before:

```
git --version
git version 2.32.0 (Apple Git-132)
```

1.) Install git by home-brew

After:

```
brew install git

git --version

git version 2.36.0
```

2.) change Path variables to:

zshrc File:

export PATH=$PATH:/Users/timknogel/FlutterDev/flutter/bin

export JAVA_HOME=$(/usr/libexec/java_home)

export PATHTWO="/usr/local/opt/ruby/bin:$PATH"

export PATHTHREE=/usr/local/bin

The last one is supposed to point to the git version, but I am unsure if I did it the right way... I have no idea about this path variables...

when I write 
```
git --version I get back:
git version 2.36.0
```

So the terminal can consult the gitversion. Why can flutter not? I don't understand much about the PATH (es). But I am not sure if it's really related anyways, because I don't have the GIT name issue that is mentioned in the post.

3.) I tried to downgrade Cocapods to 1.10.2 but it still doesn't work.

Can somebody please help me out?

**Comment by maheshmnj** [comment]
Hi @SportApps, Thanks for filing the issue. Provided that you have tried all the things mentioned in the post I am quite not sure what could potentially be wrong on your machine. Please try running the flutter counter app on an IOS device and share the complete logs by running `flutter run -v` (Share these logs in a text file as the output will be long)

**Comment by SportApps** [comment]
Hey 

> Hi @SportApps, Thanks for filing the issue. Provided that you have tried all the things mentioned in the post I am quite not sure what could potentially be wrong on your machine. Please try running the flutter counter app on an IOS device and share the complete logs by running `flutter run -v` (Share these logs in a text file as the output will be long)

Hey! I just updated the post and attached the requested file. Thank you so much for your help!

**Comment by maheshmnj** [comment]
Thanks for the info @SportApps Looks like the build is failing while checking git version 

> /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/command.rb:128:in `git_version': Failed to
extract git version from `git --version` ("") (RuntimeError)

Can you please try running `git --version` and see if the command succeeds?

**Comment by SportApps** [comment]
> Thanks for the info @SportApps Looks like the build is failing while checking git version
> 
> > /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/command.rb:128:in `git_version': Failed to extract git version from `git --version` ("") (RuntimeError)
> 
> Can you please try running `git --version` and see if returns a valid git version? if it doesn't try running `brew install git` This seems to be a known issue in cocoapods [CocoaPods/CocoaPods#8661](https://github.com/CocoaPods/CocoaPods/issues/8661)

Hi ! Before installing with home-brew:
`git --version`
git version 2.32.0 (Apple Git-132)

After:
`brew install git`

` git --version`

git version 2.36.0

Then I uninstalled CocoaPods, reinstalled, tired with both the new and old ruby version and it gives me still the same error.


When I use Ruby/Gems/2.6.0/ it gives me this error:

 ```
+609 ms] /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/command.rb:128:in `git_version': Failed to
extract git version from `git --version` ("") (RuntimeError)
                        from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/command.rb:140:in
                        `verify_minimum_git_version!'
                        from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/command.rb:49:in `run'
                        from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/bin/pod:55:in `<top (required)>'
                        from /usr/local/bin/pod:23:in `load'
                        from /usr/local/bin/pod:23:in `<main>'
[   +2 ms] Warning: CocoaPods is installed but broken. Skipping pod install.
             You appear to have CocoaPods installed but it is not working.
             This can happen if the version of Ruby that CocoaPods was installed with is different from the one being
used to
             invoke it.
             This can usually be fixed by re-installing CocoaPods.
           To re-install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.
           
[  +10 ms] CocoaPods not installed or not in valid state.
[   +1 ms] Error launching application on iPhone SE (3rd generation).
[+5899 ms] "flutter run" took 14,808ms.
[  +30 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:687:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command.dart:1161:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:94:3)
           <asynchronous suspension>
           
           
[ +309 ms] ensureAnalyticsSent: 71ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1
```

And with the home-brew ruby :
`ruby -v`
ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-darwin20]

```
[ +735 ms] /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/command.rb:128:in `git_version': Failed to
extract git version from `git --version` ("") (RuntimeError)
                        from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/command.rb:140:in
                        `verify_minimum_git_version!'
                        from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/command.rb:49:in `run'
                        from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/bin/pod:55:in `<top (required)>'
                        from /usr/local/bin/pod:23:in `load'
                        from /usr/local/bin/pod:23:in `<main>'
[   +2 ms] Warning: CocoaPods is installed but broken. Skipping pod install.
             You appear to have CocoaPods installed but it is not working.
             This can happen if the version of Ruby that CocoaPods was installed with is different from the one being
used to
             invoke it.
             This can usually be fixed by re-installing CocoaPods.
           To re-install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.
           
[   +9 ms] CocoaPods not installed or not in valid state.
[   +1 ms] Error launching application on iPhone SE (3rd generation).
[+6728 ms] "flutter run" took 17,627ms.
[  +36 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:687:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command.dart:1161:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:94:3)
           <asynchronous suspension>
           
           
[ +276 ms] ensureAnalyticsSent: 145ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1

```


Unfortunately its still not working.

**Comment by maheshmnj** [comment]
Thanks for the update @SportApps, I would suggest following up on the [cocoapods issue](https://github.com/CocoaPods/CocoaPods/issues/8661) as this isn't related to flutter. Also to unblock yourself probably downgrading cocoapods might help. I am using ` CocoaPods version 1.10.2` on M1 mac as can be seen from my flutter doctor.

<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel stable, 2.10.5, on macOS 12.3 21E230 darwin-arm, locale en-IN)
    • Flutter version 2.10.5 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (12 hours ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.65.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.39.20220405

[✓] Connected device (4 available)
    • Redmi K20 Pro (mobile) • 192.168.1.2:55555                    • android-arm64  • Android 11 (API 30)
    • iPhone 12 Pro (mobile) • 535317A4-921C-488F-B234-C2CC6D4AE5A1 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.3 21E230 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 100.0.4896.88

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

I am going to close this issue as this is not related to flutter, In case you disagree feel free to write in the comments and we will reopen it.

Thank you.

**Comment by SportApps** [comment]
Hey ! Thanks for the answer. I would really appreciate if you don't close the topic because we still don't know why Flutter can't launch the program. I tried to implement everything mentioned in the link but it still doesn´t work:

1.) Install git by home-brew
2.) change Path variables to:

zshrc File: 

export PATH=$PATH:/Users/timknogel/FlutterDev/flutter/bin

export JAVA_HOME=$(/usr/libexec/java_home)

export PATHTWO="/usr/local/opt/ruby/bin:$PATH"

export PATHTHREE=/usr/local/bin

when I write git --version I get back:
git version 2.36.0

So the terminal can consult the gitversion. Why can flutter not? I don't understand much about the PATH (es). Sorry.

3.) I tried to downgrade Cocapods to 1.10.2 but it still doesn't work.

**Comment by SportApps** [comment]
> Thanks for the update @SportApps, I would suggest following up on the [cocoapods issue](https://github.com/CocoaPods/CocoaPods/issues/8661) as this isn't related to flutter. Also to unblock yourself probably downgrading cocoapods might help. I am using ` CocoaPods version 1.10.2` on M1 mac as can be seen from my flutter doctor.
> 
> flutter doctor -v (mac)
> I am going to close this issue as this is not related to flutter, In case you disagree feel free to write in the comments and we will reopen it.
> 
> Thank you.

The Cocoapods section of Github furthermore doesn't allow me to post this cause it says its flutter related.

**Comment by maheshmnj** [comment]
> . I would really appreciate if you don't close the topic because we still don't know why Flutter can't launch the program. I tried to implement everything mentioned in the link but it still doesn´t work:

@SportApps As per my understanding flutter tool queries the cocoapods version, and cocoapods internally queries the git version where it seems to be failing, so it makes me think that this is cocoapods related.

 However, I will leave this issue open for a second opinion from the secondary triage team.
 

cc: @jmagman

**Comment by christopherfujino** [comment]
@SportApps 

> `3- pod install`
> 
> ```
> /usr/local/lib/ruby/gems/3.1.0/gems/cocoapods-1.11.3/lib/cocoapods/command.rb:128:in `git_version': Failed to extract git version from `git --version` ("") (RuntimeError)
>         from /usr/local/lib/ruby/gems/3.1.0/gems/cocoapods-1.11.3/lib/cocoapods/command.rb:140:in `verify_minimum_git_version!'
>         from /usr/local/lib/ruby/gems/3.1.0/gems/cocoapods-1.11.3/lib/cocoapods/command.rb:49:in `run'
>         from /usr/local/lib/ruby/gems/3.1.0/gems/cocoapods-1.11.3/bin/pod:55:in `<top (required)>'
>         from /usr/local/bin/pod:25:in `load'
>         from /usr/local/bin/pod:25:in `<main>'
> ```

I don't believe this is a Flutter issue; if you cannot run `pod` by itself, I'm not sure how Flutter could repair this?

The doctor check is only calling `pod --version`, and if cocoapods returns a non-zero exit, then we assume cocoapods is broken. The first step you need to do is get your cocoapods install in a good state, where the Flutter CLI can successfully call `pod --version`.

**Comment by jmagman** [comment]
I've never seen this one, and @christopherfujino's analysis is correct--Flutter can't really do anything about this, CocoaPods (and something with git) isn't working.  It would be like if Xcode wasn't installed correctly, getting that working is a dependency on using Flutter.  

CocoaPods doesn't seem to be doing anything special here, just running the version of git on your `PATH`:
https://github.com/CocoaPods/CocoaPods/blob/123f2d02f42075fa9f3b1bc729b342bd844efb44/lib/cocoapods/command.rb#L126-L127

Whatever your `PATH` is in the session where you're running `pod install`, it seems to be using some version of git that returns an empty string for its version.  Any chance you are running `pod` and `git` in different sessions, like you're running `pod` in your IDE and `git` in terminal?  We've seen that before where one is using bash, so wouldn't pick up your `zshrc` `PATH`.

In a single terminal session, can you give us the output of:
```
$ cd path/to/project/ios
$ pod install
$ git --version
$ echo $PATH
$ which -a git
```

**Comment by SportApps** [comment]
> I've never seen this one, and @christopherfujino's analysis is correct--Flutter can't really do anything about this, CocoaPods (and something with git) isn't working. It would be like if Xcode wasn't installed correctly, getting that working is a dependency on using Flutter.
> 
> CocoaPods doesn't seem to be doing anything special here, just running the version of git on your `PATH`: https://github.com/CocoaPods/CocoaPods/blob/123f2d02f42075fa9f3b1bc729b342bd844efb44/lib/cocoapods/command.rb#L126-L127
> 
> Whatever your `PATH` is in the session where you're running `pod install`, it seems to be using some version of git that returns an empty string for its version. Any chance you are running `pod` and `git` in different sessions, like you're running `pod` in your IDE and `git` in terminal? We've seen that before where one is using bash, so wouldn't pick up your `zshrc` `PATH`.
> 
> In a single terminal session, can you give us the output of:
> 
> ```
> $ cd path/to/project/ios
> $ pod install
> $ git --version
> $ echo $PATH
> $ which -a git
> ```

Hey ! Thanks for this detailed reply! 

```
Out of Android Studio Terminal

```
timknogel@Tims-MacBook-Pro multiculturalapp % cd ios
timknogel@Tims-MacBook-Pro ios % pod install
zsh: command not found: pod
```

`timknogel@Tims-MacBook-Pro ios % git --version
git version 2.36.0
`

`timknogel@Tims-MacBook-Pro ios % echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/timknogel/FlutterDev/flutter/bin
`

```
timknogel@Tims-MacBook-Pro ios % which -a git
/usr/local/bin/git
/usr/bin/git
```


"Any chance you are running `pod` and `git` in different sessions, like you're running `pod` in your IDE and `git` in terminal? "

Ehm, sorry I am really not 100% sure how to answer this, I understand when I run flutter debug out of the IDE - it automatically runs Pod (as far as I understand) and git.... I don't know cause I don't use it right now....

**Comment by jmagman** [comment]
> Ehm, sorry I am really not 100% sure how to answer this, I understand when I run flutter debug out of the IDE - it automatically runs Pod (as far as I understand) and git.... I don't know cause I don't use it right now....

I was referencing your own comment that you ran `git`
> when I write git --version I get back:

Meaning: every time you're running `git` and sending out output in this issue, are you doing it from terminal?  And when you're manually running `pod`, is that also from terminal.  The part that's confusing is that `pod` is just running `git --version` resolving from your `PATH` which is incorrectly returning an empty string,  and you're saying that `git --version` is returning a non-empty string.  So that doesn't make sense.  

I'm going to close this and refer you to https://github.com/CocoaPods/CocoaPods/issues/8661.  I don't know why `git` and CocoaPods aren't playing well together, but once you get that fixed, Flutter should work.

**Comment by SportApps** [comment]
Hey ! As I said, I tried everything out from:

https://github.com/CocoaPods/CocoaPods/issues/8661.

but it still doesn't work. 

As you recommended, I opened an issue at the Cocoapods section, and they immediately closed 

https://github.com/CocoaPods/CocoaPods/issues/11351

**Comment by jmagman** [comment]
> As you recommended, I opened an issue at the Cocoapods section, and they immediately closed

I agree with them, you should be able to isolate this from Flutter by running `pod install` directly in the same place Flutter is, in the same session.  Looks like you already did that 

> `3- pod install`
> 
> ```
> /usr/local/lib/ruby/gems/3.1.0/gems/cocoapods-1.11.3/lib/cocoapods/command.rb:128:in `git_version': Failed to extract git version from `git --version` ("") (RuntimeError)
>         from /usr/local/lib/ruby/gems/3.1.0/gems/cocoapods-1.11.3/lib/cocoapods/command.rb:140:in `verify_minimum_git_version!'
>         from /usr/local/lib/ruby/gems/3.1.0/gems/cocoapods-1.11.3/lib/cocoapods/command.rb:49:in `run'
>         from /usr/local/lib/ruby/gems/3.1.0/gems/cocoapods-1.11.3/bin/pod:55:in `<top (required)>'
>        from /usr/local/bin/pod:25:in `load'
>         from /usr/local/bin/pod:25:in `<main>'
> ```

Flutter requires CocoaPods to be working, just as it requires Xcode and git to be installed correctly.  I'm not sure why git isn't returning a version, but that seems to be the source of the issue.  Once you figure that out, CocoaPods and therefore Flutter should work.

**Comment by gramster** [comment]
Having the same issue. It seems that on M1 Macs the Ruby installation needs to use Rosetta. That means `pod --version` fails; you have to use `arch -x86_64 pod --version`. And in general that prefix is needed when using CocoaPods. Unless Apple fixes this or Flutter changes what it is doing, it seems to be basically impossible to do iOS development with Flutter on M1 Macs right now.
