### ISSUE TITLE
Flutter: How to remove the hover area of the Switch widget?

### ISSUE THREAD

**Issue by SittiphanSittisak** [flutter/flutter#102957]
I want to remove the padding of the Switch.
The padding is caused by the hover area of the button.
How to remove the hover area/padding of the button?
<img width="50" alt="switch" src="https://user-images.githubusercontent.com/59549741/166408213-ce47f305-a180-4fbf-b399-95e133af19dc.png">

basic code:
```
Container(
            color: Colors.yellow,
            child: Switch(
              value: false,
              onChanged:  (value){},
              materialTapTargetSize: MaterialTapTargetSize.shrinkWrap,
              activeColor: ColorStyle().accent,
              hoverColor: Colors.green,
            ),
          ),
```

**Comment by darshankawar** [comment]
@SittiphanSittisak 
Your question is better suited for support channels like StackOverflow where you can get solutions on how to do that, so please ask the same there.
Closing from here, as this is more of a `how to` question, rather than a bug or a feature request.
