### ISSUE TITLE
[google_sign_in_web] Document How to pass Google Sign-In OAuth client ID on README

### ISSUE THREAD

**Issue by gimKondo** [flutter/flutter#102977]
## Use case

When we want to use [google_sign_in_web plugin](https://github.com/flutter/plugins/tree/main/packages/google_sign_in/google_sign_in_web), we need to set Google Sign-In OAuth client ID.
Now, there is a note the way to pass that to meta tag on web/index.html.
But usually, we want to pass that one from dart code to switch target environment easily.

## Proposal

Actually, there is the way to set ClientID on dart code, but that's not written on document.
I guess showing that on README is helpful for developers.

Please refer following this pull request.
https://github.com/flutter/plugins/pull/5450

**Comment by piedcipher** [comment]
Instruction requested by Author is present on https://pub.dev/packages/google_sign_in.

Hence closing this issue!

![Screenshot_20240808-011523](https://github.com/user-attachments/assets/fa6fe5e5-e96b-444c-a991-0c52c12bd44d)
