### ISSUE TITLE
First-party plugins have org ID inconsistencies

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#10291]
Several if our first-party plugins still have `com.yourcompany` in code, manifests, etc.:
https://github.com/flutter/plugins/search?utf8=%E2%9C%93&q=com.yourcompany&type=

(side-note: glad we fixed https://github.com/flutter/flutter/issues/9994 so that we will see this less in the future!)

**Comment by mit-mit** [comment]
cc @mravn-google, didn't you fix this?

**Comment by mravn-google** [comment]
I fixed the Android parts (apparently missed one Gradle group declaration).

To be done:
* Update iOS product bundle IDs.
* Regenerate Google service json/plist files from Firebase console. This requires access to the Firebase projects, so it is probably more expedient to set up my own project and use that instead.
