### ISSUE TITLE
[Fonts] Icon request: social_media

### ISSUE THREAD

**Issue by mycar98765** [flutter/flutter#102964]
I want to display social media on my Flutter app and need a social media icon. However, I can't find the social media icon. I hope Flutter would add a social media icon.

**Comment by danagbemava-nc** [comment]
Hi @mycar98765, is there a specific `social media` icon that you need? 
I can't seem to find a reference to an icon called `social media` on the google icons site.

<img src="https://user-images.githubusercontent.com/88313112/166429156-f961c778-1aa8-4271-aa9b-4d0acef827ba.png" width="300" />

**Comment by mycar98765** [comment]
@danagbemava-nc, yes I need a specific social media icon like this:

<img width="52" alt="Screenshot 2022-05-03 at 7 06 28 PM" src="https://user-images.githubusercontent.com/85623500/166442797-8b3abec8-fc04-41eb-b2ee-b0793426d6c3.png">

**Comment by guidezpl** [comment]
Hi, we generally offer icons found on the Google Fonts website. If not available, there are many packages which include social icons, such as https://pub.dev/packages/font_awesome_flutter

**Comment by mycar98765** [comment]
@guidezpl, I want this social media icon with many small icons from social media companies. I think that means social media.

**Comment by danagbemava-nc** [comment]
Hi @mycar98765, as @guidezpl stated, the icons added are generally the ones that are available on the Google Fonts site. 

Given that your specific icon doesn't yet exist on the Google Fonts site, it can't be added yet. 

You can try requesting such an icon on the [material icons github](https://github.com/google/material-design-icons) or you can create a custom SVG and use https://www.fluttericon.com/ to generate an icon suitable for your project. 

I'm going to have to close this issue as unactionable for now. 

Thank you

**Comment by mycar98765** [comment]
I solved my problem. I solved this problem by the way of [this article](https://www.freecodecamp.org/news/how-to-add-custom-icons-to-your-flutter-application/). Hope this post will also help someone with the same problem as me.
