### ISSUE TITLE
Flutter - Google Sign In - Android - Access Token always returns invalid credential

### ISSUE THREAD

**Issue by arianlopezc** [flutter/flutter#102906]
I'm implementing the Google Sign In option on a Flutter app, it works fine with iOS (emulator) but in Android (emulator) the credentials that I get are always marked invalid when I check them with Google.
```
    Future<GoogleSignInAuthentication?> _validateGoogleToken(
      GoogleSignInAccount? googleSignInAccount) async {
    try {
      if (googleSignInAccount?.authentication != null) {
        final credentials = await googleSignInAccount?.authentication;
        if (credentials != null && credentials.idToken != null) {
          final urlRequest = Uri.parse(https://www.googleapis.com/oauth2/v3/userinfo);
          final response = await http.get(urlRequest, headers: {
            'Authorization': 'Bearer ${credentials.accessToken}',
          });
          final responseData = json.decode(response.body);
          if (responseData['error'] == null &&
              responseData['email_verified'] == true) {
            this._profile = Profile.fromJson(json.decode(response.body));
            _authenticationToken = credentials.idToken!;
            return Future.value(credentials);
          }
        }
      }
      return Future.value(null);
    } catch (error) {
      return Future.value(null);
    }
  }
```

The Google OAuth always returns me that the credentials are invalid. However, in the case of iOS, the credential that my app receives always gets validated with no issues.

I noticed that for some reason the credential in Android, is always the same and it seems to be shorter/truncated than the one from iOS.

Any recommendations?

```
[✓] Flutter (Channel stable, 2.10.5, on macOS 12.3.1 21E258 darwin-arm, locale en-US)
    • Flutter version 2.10.5 at /Library/Flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (13 days ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/arianlc/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] VS Code (version 1.66.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.38.1

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554                        • android-arm64  • Android 12 (API 32)
      (emulator)
    • iPhone 13 (mobile)          • 18DE5604-4254-4F6B-A118-A21471B40473 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-15-4 (simulator)
    • Chrome (web)                • chrome                               • web-javascript • Google Chrome
      100.0.4896.127

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

**Comment by darshankawar** [comment]
> but in Android (emulator) the credentials that I get are always marked invalid when I check them with Google.

@arianlopezc Do you see any error while this happens ? If so, can you provide the complete error log ?

Also, does it only happens with Android emulators ? or with Android device too ?
Does the emulator have Google play services ?

**Comment by arianlopezc** [comment]
@darshankawar in order to validate that the token I'm receiving is a valid one, I'm performing a call to the `https://www.googleapis.com/oauth2/v3/userinfo` using the token as a Bearer token. The response to the request is always 401 with body:
```
{
    "error": "invalid_request",
    "error_description": "Invalid Credentials"
}
```

This happens in the emulator and also if I try to perform the call directly to the endpoint using Postman.
The emulator has Google Play but as I mentioned, the returned token is always marked invalid even if I use it to make the call directly with Postman.

**Comment by darshankawar** [comment]
> "error": "invalid_request",

This means the request probably isn't getting validated properly at the server. Can you try the plugin example on same emulator and see what you get ?

**Comment by arianlopezc** [comment]
@darshankawar my mind has been blown to pieces.

Before trying to run the example as you asked me, I decided to check on the request again, just to give it another try, and suddenly the token started coming back with no issues (not truncated) and properly validated with Google's endpoint...

I don't know specifically what happened that it just "fixed itself".

I'm thinking that maybe some cache was getting in the way and sending me the wrong token every time... I tried it last night before going to bed and it was borked and now about 10 hours later it just works fine...? Makes no sense

**Comment by darshankawar** [comment]
Thanks for the update @arianlopezc.
Based on your findings, I don't think this would be specific to the plugin, but probably coming from Google itself due to a glitch or any internal error from their end.  Error 401 although indicates that the client request couldn't be validated at server end, but also indicates that atleast the request has been initiated from client but somehow not being able to validate by Google. So I also suggest you to raise this issue in Google support for further resolution.
