### ISSUE TITLE
flutter-devicelab-mac-12 doctor failing 

### ISSUE THREAD

**Issue by Jasguerrero** [flutter/flutter#102986]
After bringing the bot out of quarantined the doctor is failing to find the getMacBinaryPath while it was quarantined I tried to install xcode tools via ssh with brew after failing to do that I deleted brew

https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-12

**Comment by yusuf-goog** [comment]
@Jasguerrero FYI, we maintain the devicelab bots via salt states. If there are failures that need actions not covered in the states they should be updated.

**Comment by yusuf-goog** [comment]
homebrew was missing/removed from the bot.
*  installed it.
* Fixed brew links: `brew list | xargs -I % sh -c 'brew unlink %; brew link %'` . 

applied salt states.

manually fixed some idevice* package installation that was corrupted.

bot is up and running.
