### ISSUE TITLE
iOS FlutterTextureRegistry should be a proxy, not the engine itself

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#102990]
The general model on iOS (I believe; it's possible the internals have changed here enough since I last looked that this is no longer true and there is enough indirection that I can't quickly tell from the source) is that the engine indirectly owns plugin instances via `addMethodCallDelegate:` (which despite the name, creates a strong reference to the delegate, which is the plugin itself).

This makes having the `FlutterTextureRegistry` returned by `[registrar textures]` be the engine itself problematic, because if the plugin retains the texture registrar there's a cycle. It's easy for developers to do this, and it's not even clear from the API that they shouldn't.

See https://github.com/flutter/flutter/issues/102966 for an example.

We should have a proxy object with a weak reference back to the engine serve as the texture registry object that is returned instead.

/cc @gaaclarke; IIRC you fixed this same problem with the binary messenger a while ago.

**Comment by endless7** [comment]
Hi - @stuartmorgan. Is the realization of this proxy will be similar to the binary messenger? 
see https://github.com/flutter/engine/pull/9419/files#diff-5adc15a968e598149c4528e88353dc7a325f7bc287c23dc74a002d2def03bcd0

**Comment by stuartmorgan** [comment]
Yes, that PR was fixing essentially the same problem for the binary messenger.

**Comment by jmagman** [comment]
@stuartmorgan this should have been closed by https://github.com/flutter/engine/pull/37666, right?

**Comment by stuartmorgan** [comment]
Yep, thanks.
