### ISSUE TITLE
[url_launcher] The new launchUrl method doesn't work as well as the deprecated launch method for Play Store Links.

### ISSUE THREAD

**Issue by patrick-enzo** [flutter/flutter#102918]
## Steps to Reproduce

1. Use the new launchUrl method to open up a play store link.

**Expected results:** The corresponding app on the playstore displays properly.

**Actual results:** A dialog box asking to install a web browser even though it's already installed and set as the default browser. The old deprecated `launch `method works without any problems.

<details>
<summary>Code sample</summary>

            TextButton(
              child: const Text('Deprecated launch method'),
              onPressed: () {
                launch('https://play.google.com/store/apps/details?id=com.shikudo.focus.google&hl=en_US&gl=US');
              },
            ),
            const SizedBox(height: 20),
            TextButton(
              child: const Text('New launchUrl method'),
              onPressed: () {
                launchUrl(
                    Uri(
                        scheme: 'https',
                        host: 'play.google.com',
                        path: 'store/apps/details?id=com.shikudo.focus.google&hl=en_US&gl=US'),
                    mode: LaunchMode.externalApplication);
              },
            ),

```dart
```
</details>
For transparency, I've already opened an issue here https://github.com/flutter/flutter/issues/102769 that got closed but I feel like I didn't properly explain the problem. If this gets closed again, I'll officially give up on this.

Here is a video displaying the different results between using the new `launchUrl `method and the deprecated `launch `method trying to go to the same exact play store page.

https://user-images.githubusercontent.com/88462493/166229787-d7a4446b-9776-4127-9a16-cd636244ac3b.mov

I'm on Flutter version 2.10.3 and I'm using the new url_launcher version 6.1.0 which is what's causing my problem.

Thank you.

**Comment by maheshmnj** [comment]
Hi @patrick-enzo, launchUrl method works fine. Looks like the Uri parsing is incorrect Please try this 

```dart
 launchUrl(
      Uri.parse(
          'https://play.google.com/store/apps/details?id=com.shikudo.focus.google&hl=en_US&gl=US'),
      mode: LaunchMode.externalApplication,
 );
```

**Comment by patrick-enzo** [comment]
@maheshmnj 

Thank you so much for the clarification. The solution that you provided is perfect for my use case.
