### ISSUE TITLE
Codelab: In_app_purchases needs updating

### ISSUE THREAD

**Issue by jbryanh** [flutter/flutter#102923]
Just a request for an update on the codelab in_app_purchases.  Issues I've found:

1. Server Side verification is insufficient for subscription changes in app with ios. When a user changes their subscription within same group, update to firebase server does not fire and sub not changed.  I think this is because apple doesn't provide a the new product_id, they provide the new id as auto_renew_product_id

2. handleServerEvent does not function properly for subscription changes outside of app, as you would need/expect.

3. The recommendation to provide "environment: 'sandbox', is counter to apple recommendation, I think you should be suggesting, environment: ["production", "sandbox"],

Thanks

**Comment by darshankawar** [comment]
@jbryanh 
Can you check if your case is same as described in here ? https://github.com/flutter/flutter/issues/102881

**Comment by jbryanh** [comment]
@darshankawar 
As it relates to handleServerEvent, absolutely, yes.  I'm still reconciling handleValidation to Apple's subscription flow, so I haven't fully debugged what's happening in handleServerEvent beyond knowing it's not working for out of app subscription changes.

I need to refine my notes above.  As I'm upgrading logic in the functions, I'm discovering a few more things that might/should be addressed.

**Comment by darshankawar** [comment]
Thanks for the update. Closing this as a duplicate. Please follow-up in it for further updates.
