### ISSUE TITLE
Padding in header doesn't match sidebar

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#10292]
![screen shot 2017-05-24 at 8 48 30 am](https://cloud.githubusercontent.com/assets/5479/26412508/d9f56f94-405d-11e7-993d-d062fa4c2104.png)

Notice how the logo has more left padding that the side bar.

**Comment by zoechi** [comment]
The site had a complete overhaul anyway but this looks fixed.

![image](https://user-images.githubusercontent.com/405837/49237328-41717f00-f3fe-11e8-96ac-62deb233fe1c.png)
