### ISSUE TITLE
Flutter Firebase Codelab: google-services plugin could not detect any version for com.google.android.gms

### ISSUE THREAD

**Issue by darioielardi** [flutter/flutter#10295]
Hi guys,
I'm trying the new [flutter-firebase codelab](https://codelabs.developers.google.com/codelabs/flutter-firebase/index.html?index=..%2F..%2Findex#5) but when I run my app with propers plugin imported ( step 6 ) here's what happen ( `flutter run -v` ):

```
[+5658 ms] google-services plugin could not detect any version for com.google.android.gms or com.google.firebase, default version: 9.0.0 will be used.
[        ] please apply google-services plugin at the bottom of the build file.
[  +68 ms] FAILURE: Build failed with an exception.
[   +1 ms] * Where:
[   +2 ms] Build file 'C:\Users\dario\Repos\friendlychat\android\build.gradle' line: 22
[   +1 ms] * What went wrong:
[   +1 ms] A problem occurred evaluating root project 'android'.
[   +1 ms] > A problem occurred configuring project ':app'.
[   +4 ms]    > Failed to notify project evaluation listener.
[   +1 ms]       > Could not resolve all dependencies for configuration ':app:_debugApk'.
[   +1 ms]          > A problem occurred configuring project ':firebase_analytics'.
[   +1 ms]             > Could not resolve all dependencies for configuration ':firebase_analytics:_debugPublishCopy'.
[   +1 ms]                > Could not find com.google.firebase:firebase-auth:10.2.1.
[   +1 ms]                  Required by:
[   +4 ms]                      io.flutter.firebase_analytics:firebase_analytics:1.0-SNAPSHOT
[   +2 ms]                > Could not find com.google.firebase:firebase-analytics:10.2.1.
[   +1 ms]                  Required by:
[   +2 ms]                      io.flutter.firebase_analytics:firebase_analytics:1.0-SNAPSHOT
[   +4 ms]       > Could not get unknown property 'compileDebugJavaWithJavac' for project ':app' of type org.gradle.api.Project.

```
Notice that " apply plugin: 'com.google.gms.google-services' " definitely is at the bottom of my android/app/gradle

`flutter analyze`: No issues

`flutter doctor`:

[√] Flutter (on Microsoft Windows [Version 10.0.15063], channel alpha)
    • Flutter at C:\Users\dario\Repos\flutter
    • Framework revision dc4ca8db83 (13 days ago), 2017-05-11 15:33:29 -0700
    • Engine revision f99d3ef108
    • Tools Dart version 1.23.0-dev.11.11

[√] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at C:\Users\dario\AppData\Local\Android\sdk
    • Platform android-25, build-tools 25.0.3
    • ANDROID_HOME = C:\Users\dario\AppData\Local\Android\sdk
    • Java binary at: C:\Program Files\Android\Android Studio1\jre\bin\java
    • Java version: OpenJDK Runtime Environment (build 1.8.0_76-release-b03)

[√] Android Studio (version 2.2)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Gradle version 2.14.1
    • Java version: OpenJDK Runtime Environment (build 1.8.0_76-release-b03)

[-] IntelliJ IDEA Community Edition (version 2016.3)
    • Dart plugin not installed; this adds Dart specific functionality.
    • Flutter plugin not installed; this adds Flutter specific functionality.
    • For information about managing plugins, see
      https://www.jetbrains.com/help/idea/managing-plugins.html

[√] IntelliJ IDEA Ultimate Edition (version 2017.1)
    • Dart plugin version 171.4424.63
    • Flutter plugin version 13.1

[√] WebStorm (version 2017.1)
    • Flutter plugin version 13.1

[√] Connected devices
    • Moto G4 • ZY2239WT6B • android-arm • Android 7.1.2 (API 25)

**Comment by Skylled** [comment]
Does your `android/build.gradle` contain the following snippet?
```
allprojects {
    repositories {
        jcenter()
        maven { url "https://jitpack.io" }
    }
}
```

**Comment by darioielardi** [comment]
@Skylled 
yeah sure, I added all code suggested by the codelab

**Comment by mkhennoussi** [comment]
@darioielardi 
Make sure all your Android dependencies are up to date (Android Support Repository, etc.). 
The easiest way is to open Android Studio and let it check everything for you (This is what I've done). Then you should be able to follow the codelab.

**Comment by branflake2267** [comment]
The GMS classpath has to be added to projectRoot/build.gradle and apply plugin [GMS] to the bottom of projectRooot/app/build.gradle. This will fix that. 

This video covers wiring it up: https://www.youtube.com/watch?v=t_SgDznY99k

**Comment by konifar** [comment]
@darioielardi
I guess you have to install or update `Google Repository` and `Google Play Services` in SDK tools
This link might help you. 
https://developers.google.com/android/guides/setup

I updated them from `Android Studio > Preferences > Appearance & Behavior > System Settings > Android SDK`.

<img width="900" alt="default_preferences" src="https://cloud.githubusercontent.com/assets/1269214/26555276/4cd084fc-44cf-11e7-96ae-ead2f960aee0.png">

**Comment by LarkAscending** [comment]
The codelab has been updated with the Google Repository requirement. Please ping if you're still seeing this issue.

**Comment by branflake2267** [comment]
I'm just adding to the heap. But when you see gms errors, it could be that the gradle instructions have been missed. 

* https://github.com/flutter/plugins/tree/master/packages/firebase_auth

Enable the Google services by configuring the Gradle scripts as such.

1. Add the classpath to the `[project]/android/build.gradle` file.
```
dependencies {
  // Example existing classpath
  classpath 'com.android.tools.build:gradle:2.2.3'
  // Add the google services classpath
  classpath 'com.google.gms:google-services:3.1.0'
}
```

2. Add the apply plugin to the `[project]/android/app/build.gradle` file.
```
// ADD THIS AT THE BOTTOM
apply plugin: 'com.google.gms.google-services'
```

**Comment by LarkAscending** [comment]
Closing because we are not seeing this during verification this week. Feel free to re-open if it's still an issue.

**Comment by erluxman** [comment]
Did you forget to add  google repository In project build folder?

```
buildscript {
    repositories {
        jcenter()
        maven {
            url "https://maven.google.com"
        }
    }
```

**Comment by singlakaran** [comment]
i did all these but issue still not gone for analytics

**Comment by singlakaran** [comment]
i got the solution of this we have to use androidx instead of android and we dont need to add this

maven{
            url "https://maven.google.com"
        }
