### ISSUE TITLE
[go_router] Navigate to the default page when rebuilding MaterialApp [document]

### ISSUE THREAD

**Issue by XuanTung95** [flutter/flutter#102952]
## Steps to Reproduce

Many people use `go_router` like this:

```
class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    // watch some state management
    final provider = context.watch<MyProvider>();
    //

    final _router = GoRouter(
      redirect: (state) {
        // use state management
        provider.doStuff();
        return null;
      },
      routes: [
        GoRoute(
          path: '/',
          builder: (context, state) => const MyPage(title: 'Home Page'),
        ),
        GoRoute(
          path: '/page2',
          builder: (context, state) => const MyPage(title: 'Page 2'),
        ),
      ],
    );

    return MaterialApp.router(
      routerDelegate: _router.routerDelegate,
      routeInformationParser: _router.routeInformationParser,
    );
  }
}
```
It works fine until MyApp is rebuilt, then it will navigate to the default page because a new instance of `routerDelegate` is passed to `MaterialApp`.
The route is changed without using `context.go()` or `context.goNamed()` but there is no verbose warning in the document.
It's hard to detect in early development because `MaterialApp` is not rebuilt frequently.

**Expected results:** 

Could you add a warning in the document about this case? Especially this part https://gorouter.dev/declarative-routing
If it is already documented, please let me know, I will close this ticket.

**Comment by chunhtai** [comment]
The documentation will be added as part of https://github.com/flutter/flutter/issues/99121
