### ISSUE TITLE
Allow scrollPadding to be defined in InputDecorationTheme

### ISSUE THREAD

**Issue by MilesAdamson** [flutter/flutter#103066]
## Use case

I would like 40 padding on text field scrolling (opposed to the default 20) on every text field in my app.

Currently you must supply this to every text field individually.

```
          const TextField(
            scrollPadding: EdgeInsets.all(40),
          ),
          const TextField(
            scrollPadding: EdgeInsets.all(40),
            decoration: InputDecoration(
              labelText: "This is a label",
            ),
          ),
          const TextField(
            scrollPadding: EdgeInsets.all(40),
            decoration: InputDecoration(
              hintText: "This is a hint",
            ),
          ),
          const TextField(
            scrollPadding: EdgeInsets.all(40),
            decoration: InputDecoration(
              helperText: "This is helper text",
            ),
          ),
```

## Proposal

```
InputDecorationTheme(
    contentPadding: const EdgeInsets.all(16.0),
    // add this just like contentPadding
    scrollPadding: const EdgeInsets.all(40.0),
  );
```

**Comment by justinmc** [comment]
@MilesAdamson scrollPadding is a [parameter in EditableText](https://github.com/flutter/flutter/blob/e4ce47f3485ffe30842dce4bfa35feef79cc4816/packages/flutter/lib/src/widgets/editable_text.dart#L856), it's not related to InputDecorator. Currently with no theming support in the widgets library (where EditableText resides), there might not be a straightforward way to solve your problem of needing to repeat this for every TextField.

I'm going to close this, but if you think of another way to solve the problem let me know and I'll be happy to reopen.

Also, there's a chance that this sort of thing could be made easier when Dart's macros feature is released...
