### ISSUE TITLE
The dashboard menu to select 'stages' is broken

### ISSUE THREAD

**Issue by yusuf-goog** [flutter/flutter#103082]
On https://flutter-dashboard.appspot.com/#/build

* Click the gear icon and uncheck the `Stages`, and click apply.
* You see all results disappear as expected.
* Click the gear icon and check the `Stages`, and click apply.
* While your selecting the checkbox you see the results appear, but when you click the apply button, they don't appear.

Note that the query parameters remain as false for the settings in the URL.

**Comment by yusuf-goog** [comment]
\cc @CaseyHillers @XilaiZhang

possibly related to https://github.com/flutter/cocoon/pull/1744

**Comment by yusuf-goog** [comment]
\cc @codebird

**Comment by yusuf-goog** [comment]
If you manually remove the url query parameter, it works as expected, so that part of the plumbing seems to be good.

**Comment by codebird** [comment]
I'll check it out
