### ISSUE TITLE
`flutter run` is keep downloading gradle constantly, why is that?

### ISSUE THREAD

**Issue by http600** [flutter/flutter#103039]
```bash
flutter run -v
...
[ +322 ms] Downloading https://services.gradle.org/distributions/gradle-7.4.2-all.zip
...
```

How can I tell flutter to take existing gradle at `~/Download/gradle`, do not download automatically.

**Comment by Kemorave** [comment]
I too suffer from this and have no idea why is it happening but i found a workaround.
  
You can download the file `gradle-7.4.2-alll.zip` once on your drive then in your project navigate to file
`\android\gradle\wrapper\gradle-wrapper.properties`
and change the `distributionUrl` to the file path like this
`distributionUrl=file:///e:/gradle-7.4.2-all.zip`

**Comment by darshankawar** [comment]
@http600 
See [this](https://stackoverflow.com/a/62589571) SO link which should hopefully answer your question.
Bottom line is gradle will reuse the artifacts and will download required files if there's any plugin added or upgrade made to the version which is expecte.

Also take a look at this link for further reference: https://stackoverflow.com/questions/62589406/way-to-stop-android-studio-gradle-build-from-using-internet-data/62589571#62589571.

Closing from here.
