### ISSUE TITLE
cocoon is using libs that are being deprecated soon

### ISSUE THREAD

**Issue by yusuf-goog** [flutter/flutter#103071]
When running the dashboard locally with `dashboard$ flutter run -d chrome --web-port=8080` we see the message:

Your client application uses libraries for user authentication or authorization that will soon be deprecated. See the [Migration Guide](https://developers.google.com/identity/gsi/web/guides/gis-migration) for more information.

**Comment by yusuf-goog** [comment]
\cc @godofredoc @keyonghan  no idea what the timeline is, but something we should look at.

**Comment by codebird** [comment]
isn't this coming from google_sign_in package? Guess it is more about the package being updated than cocoon itself no?

**Comment by ditman** [comment]
Just found this issue. Please follow:

* https://github.com/flutter/flutter/issues/88084

**Comment by keyonghan** [comment]
> isn't this coming from google_sign_in package? Guess it is more about the package being updated than cocoon itself no?

After the google sign in plugin support, we also need to update cocoon to migrate js library follow: https://developers.google.com/identity/gsi/web/guides/migration#html_and_javascript

**Comment by ditman** [comment]
@keyonghan do you have any JS code that uses the JS library directly? If **not**, I think that the update to `package:google_sign_in_web` should suffice for Cocoon?

**Comment by keyonghan** [comment]
Yeah. Here it is: https://github.com/flutter/cocoon/blob/main/dashboard/web/index.html#L35

**Comment by codebird** [comment]
@keyonghan I don't think it is related. This is for analytics... It has to stay the same.

**Comment by ditman** [comment]
Aha, I see. AFAIK the only thing that is being deprecated from that file is the `gapi.auth2` library, but other `gapi` libraries will continue working as normal. See this example where one of the new authentication flows is being used in conjunction with `gapi.client.calendar`: [Working with the Google APIs JavaScript library](https://developers.google.com/identity/oauth2/web/guides/use-token-model#working_with_the_google_apis_javascript_library).

One thing you can do in cocoon is follow this procedure to **[Identify affected code and testing](https://developers.google.com/identity/gsi/web/guides/migration#identifying_affected_code_and_testing)** (using the `G_AUTH2_MIGRATION` cookie), but I'm 99% sure the only offender is going to be the `google_sign_in_web` plugin.

**Comment by keyonghan** [comment]
Thanks all for the explanations! We will track https://github.com/flutter/flutter/issues/88084 and follow up from there.
