### ISSUE TITLE
[go_router_builder] add `push` method to generated `GoRouteData` extension

### ISSUE THREAD

**Issue by Ayman-Barghout** [flutter/flutter#103025]
According to `go_router_builder`'s documentation, we should be able to navigate using our defined typed route's `go` or `push` methods.

<img width="1014" alt="Screen Shot 2022-05-04 at 9 33 32 AM" src="https://user-images.githubusercontent.com/44665622/166641258-61c0249b-3a07-49e7-ab09-66515519f870.png">

But when generating our routes only the `go` method is added to the extension:
```dart
extension $HomeRouteExtension on HomeRoute {
  static HomeRoute _fromState(GoRouterState state) => const HomeRoute();

  String get location => GoRouteData.$location(
        '/',
      );

  void go(BuildContext buildContext) => buildContext.go(location, extra: this);
}
```
the above code is fetched directly from [the package's example.](https://github.com/flutter/packages/blob/ec0aed4f559d03e792064ddf9b929c3e606524c2/packages/go_router_builder/example/lib/main.g.dart#L46)

It'd be great if we can also have the `push` method as the documentation states as it has its own cases 🙏

**Comment by darshankawar** [comment]
Thanks for the report. Labeling this as a proposal to add `push` method as suggested.

/cc @kevmoo

**Comment by cuong0993** [comment]
Can we add the feature please :(. It strange that at v1.0.3 the lib doesn't have this feature.

**Comment by kevmoo** [comment]
Someone needs to implement it, @cuong0993 – PRs welcome!
