### ISSUE TITLE
[autosubmit] Neutral statuses block PRs from landing

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#103099]
See https://github.com/flutter/cocoon/pull/1818 where the scorecards status was neutral (a black box).

These statuses shouldn't block PRs from landing

**Comment by CaseyHillers** [comment]
\cc @keyonghan @godofredoc

**Comment by codebird** [comment]
I can work on this starting Monday.

**Comment by codebird** [comment]
This needs closing guys
