### ISSUE TITLE
Filter out staging builds from the cocoon dashboard

### ISSUE THREAD

**Issue by yusuf-goog** [flutter/flutter#103081]
To allow us to use the current build definition mechanism (.ci.yaml) for staging builds, we need a way to add the builds without polluting the flutter dashboard with staging task results.

Where staging tasks are task marked with `bringup:true`, and the results show up as flakey runs on the dashboard currently.

**Comment by keyonghan** [comment]
Do we not want to show those `bringup: true` builders in the dashboard? I believe team has been monitoring these flaky tests using the dashboard.

The key issue here is how we distinguish `bringup: true` builders and those we want to enable in staging (not flaky) for validation.

**Comment by yusuf-goog** [comment]
@keyonghan you are correct, we do want to differentiate between flakey and staging tests, since they are used by the teams in different manners.

I have a proposal PR: https://github.com/flutter/cocoon/pull/1817 that implements this differentiation by filtering on task name prefix ('staging_build_').

**Comment by keyonghan** [comment]
> I have a proposal PR: https://github.com/flutter/cocoon/pull/1817 that implements this differentiation by filtering on task name prefix ('staging_build_').

That should help with the UI side.

But some potential side effect of the proposed change to consider:
1) Flake bot relies on .ci.yaml targets to iterate to check flaky stats for any target. And we should exclude these builder from the flake bot. Related issue: https://github.com/flutter/flutter/issues/91913
2) This will adds burden to existing `refresh-chrome-bot-status` api further if we enable ~100 builders at one time.
3) We need to update corresponding docs

**Comment by yusuf-goog** [comment]
@CaseyHillers do you know what the impact is going to be on `refresh-chrome-bot-status` api further if we enable ~100 builders at one time? Does your work on pubsub mitigate the extra load?

**Comment by CaseyHillers** [comment]
> @CaseyHillers do you know what the impact is going to be on refresh-chrome-bot-status api further if we enable ~100 builders at one time? Does your work on pubsub mitigate the extra load?

I would avoid that, or if you do, have them all be on the Cocoon scheduler. last time I checked it was taking 2.5 minutes for flutter. I'm not sure what the exact request timeout is, but that's awfully close.

**Comment by yusuf-goog** [comment]
FYI: currently all VM builds are on the cocoon scheduler so should not affect `refresh-chrome-bot-status`.

**Comment by yusuf-goog** [comment]
Closing this, since the filtering changes are all checked in and working.
