### ISSUE TITLE
new_gallery_ios__transition_perf missing past 2 days of data in SkiaPerf

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#103053]
Looking at the chart here https://flutter-flutter-perf.skia.org/e/?begin=1649264769&end=1651540151&queries=sub_result%3D90th_percentile_frame_rasterizer_time_millis%26sub_result%3D99th_percentile_frame_rasterizer_time_millis%26sub_result%3Daverage_frame_rasterizer_time_millis%26sub_result%3Dworst_frame_rasterizer_time_millis%26test%3Dnew_gallery_ios__transition_perf&requestType=0&xbaroffset=28367

SkiaPerf hasn't recorded data about new_gallery_ios__transition_perf in about two days. However it looks like this benchmark is running successfully:

https://ci.chromium.org/p/flutter/builders/staging/Mac_ios%20new_gallery_ios__transition_perf

I suspect other benchmarks are impacted as well since we have not been getting many SkiaPerf alerts since last week. Not sure whether this is related to the cocoon scheduling change, or the issues with upload we were seeing last week.

/cc @keyonghan @CaseyHillers

**Comment by yusuf-goog** [comment]
@keyonghan do the skiaperf results run on staging builders only?

**Comment by yusuf-goog** [comment]
@zanderso I'm trying to see if there are any other builds that are uploading correctly for the last couple day:

https://flutter-flutter-perf.skia.org/e/?begin=1649264769&end=1651540151&queries=sub_result%3D90th_percentile_frame_rasterizer_time_millis%26sub_result%3D99th_percentile_frame_rasterizer_time_millis%26sub_result%3Daverage_frame_rasterizer_time_millis%26sub_result%3Dworst_frame_rasterizer_time_millis%26test%3DMac_ios_large_image_changer_perf_ios%26test%3DMac_ios_microbenchmarks_ios%26test%3DMac_ios_platform_channels_benchmarks_ios%26test%3Dnew_gallery_impeller_ios__transition_perf%26test%3Dnew_gallery_ios__transition_perf&requestType=0&xbaroffset=28367

 Do you have an example of any that are working?

**Comment by zanderso** [comment]
This was user error. Sorry for the disruption. The SkiaPerf UI doesn't scroll the date window all the way to the most recent values in an intuitive way.
