### ISSUE TITLE
Cocoon scheduled builders keep failing with `fatal: reference is not a tree`

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#103087]
One example: https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20analyze/7056/overview

<img width="1232" alt="Screen Shot 2022-05-04 at 1 46 40 PM" src="https://user-images.githubusercontent.com/54558023/166823196-52b10749-fce8-4600-9bc2-02ec26527224.png">

**Comment by yusuf-goog** [comment]
I believe this is due to the gob mirror not being caught up to github. We can see the retries kicked in, but the delay was probably not enough in this case.

**Comment by yusuf-goog** [comment]
Currently in retry(), max_attempts = 2. That includes the initial attempt, which doesn't give us the expected delay of > 60s. Sending a fix to increase attempts by 1.

**Comment by yusuf-goog** [comment]
Fix in: https://flutter-review.googlesource.com/c/recipes/+/29602

**Comment by yusuf-goog** [comment]
fixed merged
