### ISSUE TITLE
[web] Flutter_service_worker.js still reports an error of Mixed Content when the browser allows it

### ISSUE THREAD

**Issue by AoEiuV020** [flutter/flutter#103054]
I'm trying to access the network on the web platform like other native platforms,

![image](https://user-images.githubusercontent.com/11682198/166713246-16cd58ae-6618-4ef1-b972-7a79260c1982.png)

I know that browsers will not allow https sites to request http resources by default.
The picture above is after I manually select Allow Insecure content in chrome site settings,
The browser itself has not blocked access to http resources, it will only prompt a warning,
However, the flutter service worker reported an error and could not access http resources.
In fact, http resources can only be accessed when the website is accessed for the first time, after which this error will occur,

![image](https://user-images.githubusercontent.com/11682198/166712412-3a77c1ce-642c-4e9b-8a61-f0c203836a22.png)

I know this problem can be solved by disabling flutter service worker with parameter --pwa-strategy=none,
But I'm not sure if disabling flutter service worker has other effects,
I think there should be other ways to prevent the flutter service worker from reporting redundant errors.

my demo, 
https://github.com/AoEiuV020/FlutterDemo/blob/a8d8577369b194f835a007ac8b745559b012d818/lib/mixed.dart#L15

flutter version: 2.10.5+1
http version: ^0.13.4
Dart SDK version: 2.16.2 (stable)

**Comment by darshankawar** [comment]
@AoEiuV020 
Looking at the error you shared, take a look at this open issue which probably describes the same case, https://github.com/flutter/flutter/issues/43595. You may follow-up in it for further reference.

Also, check out this SO link for a workaround / solution, https://stackoverflow.com/questions/66796932/is-it-possible-to-allow-mixed-content-in-flutter-webview

Closing this as duplicate.

**Comment by AoEiuV020** [comment]
@darshankawar It's different, it's completely different, I'm not talking about android or webview, but a web platform, flutter build web

**Comment by darshankawar** [comment]
Thanks for the feedback. Reopening.

**Comment by darshankawar** [comment]
@AoEiuV020 
After running `flutter build web -t lib/main.dart --pwa-strategy=none`, the file will be created but there won't be any content in it. Is this an acceptable solution for you ?

**Comment by AoEiuV020** [comment]
<img width="791" alt="image" src="https://user-images.githubusercontent.com/11682198/166924796-754932c3-ed05-4aef-9057-92581212fbf9.png">
As I mentioned above, pwa-strategy=none is ok to disable flutter service worker,
But I think the flutter service worker should not report an error here, instead of disabling the flutter service worker for this,

**Comment by AoEiuV020** [comment]
Since pwa-strategy=none is not the default option, there should not be such a troubling problem that the first operation works normally and the second operation reports an error.

**Comment by darshankawar** [comment]
Thanks for the update. I am keeping this issue open for further insights from the team on expected behavior.

**Comment by ditman** [comment]
This is [standard Worker behavior](https://github.com/w3c/ServiceWorker/issues/813#issuecomment-366941915), so there isn't much that flutter can do to work around it.

It seems that the recommendation to [handle this](https://github.com/w3c/ServiceWorker/issues/813#issuecomment-1047552606) is to set the `upgrade-insecure-requests` CSP header value (or meta element) in the response that is serving your flutter app (or your index.html, if you're using the meta). This will instruct the browser to perform requests over `https` even if the URL says `http` (from what I could understand, this is only intended when you're migrating an http site to https).

Here's some more information:

* [MDN - CSP: upgrade-insecure-requests](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/upgrade-insecure-requests)

I'm closing this, since this is Web Standard behavior. I hope the workaround helps @AoEiuV020!

**Comment by AoEiuV020** [comment]
![image](https://user-images.githubusercontent.com/11682198/167058198-41a70223-9ead-40ec-be35-dfff6a6c4187.png)
Oh, I understand this,
But I think, at least the requests of other websites should not report errors, because they should not be handed over to the serviceWorker cache,
When I checked flutter_service_worker.js, I found a problem, even if I requested other sites, still not reutrn at RESOURCES check,
As shown in the figure above, the key requested by other websites is empty, resulting in (|| key == '') being true, resulting in the key being set to /, resulting in no reutrn at the RESOURCES check,
I think flutter should at least fix this and can also be used to solve my problem,
@ditman

**Comment by AoEiuV020** [comment]
In the picture above, my demo page address is,
https://flutter.aoeiuv020.com/#/
The requested address is,
http://main.aoeiuv020.com/
I think this case should be returned here, right?
   if (!RESOURCES[key]) {
     return;
   }

**Comment by ditman** [comment]
@AoEiuV020 I understand the problem now, you're right, the flutter service worker should only attempt to handle flutter resources, not the whole internet. I'll try to land a fix on `master` asap.
