### ISSUE TITLE
recipes: api.python(...)` is deprecated in favor of `api.step

### ISSUE THREAD

**Issue by yusuf-goog** [flutter/flutter#103091]
When running `./recipes.py test train` ...

**********************************************************************
            WARNING: recipe_engine/PYTHON_CALL_DEPRECATED             
                Found 8 call sites and 0 import sites                 
**********************************************************************
Description:
  `api.python(...)` is deprecated in favor of `api.step`.
  
  Please update your api.python(name, ...) calls to one of:
    api.step(name, ['vpython3', ...])
    api.step(name, ['python3', ...])
    api.step(name, ['vpython', ...])
    api.step(name, ['python', ...])

Bug Link: https://bugs.chromium.org/p/chromium/issues/detail?id=1271425
Call Sites:
  /Users/mohsinally/src/recipes/recipe_modules/android_virtual_device/api.py:64 (and 68)
  /Users/mohsinally/src/recipes/recipe_modules/yaml/api.py:30
  /Users/mohsinally/src/recipes/recipe_modules/zip/api.py:65 (and 122)
  /Users/mohsinally/src/recipes/recipes/engine/engine.py:134 (and 559)
  /Users/mohsinally/src/recipes/recipes/engine/engine_unopt.py:70

**Comment by godofredoc** [comment]
@drewroengoogle I saw one pr from you addressing this, can we close this issue?
