### ISSUE TITLE
The method '[]' can't be unconditionally invoked because the receiver can be 'null' | Firebase Database | Flutter

### ISSUE THREAD

**Issue by khaledbadr97** [flutter/flutter#103153]
`import 'package:firebase_database/firebase_database.dart';

class Drivers
{
  String? name;
  String? phone;
  String? email;
  String? id;
  String? car_color;
  String? car_model;
  String? car_number;

  Drivers({this.name, this.phone, this.email, this.car_color, this.car_model, this.car_number});

  Drivers.fromSnapshot(DataSnapshot dataSnapshot)
  {
    id = dataSnapshot.key;
    name = dataSnapshot.value["name"];
    phone = dataSnapshot.value["phone"];
    email = dataSnapshot.value["email"];
    car_color = dataSnapshot.value["car_color"];
    car_model = dataSnapshot.value["car_model"];
    car_number = dataSnapshot.value["car_number"];
  }
}`

What is the problem in my code??

**Comment by stuartmorgan** [comment]
For help with your own code, try one of the resources listed at https://flutter.dev/community#community-grid

Closing as this is not an issue in Flutter itself, which is what we track here.
