### ISSUE TITLE
[go_router] Deep linking

### ISSUE THREAD

**Issue by AkzhanArdaki** [flutter/flutter#103109]
I'm trying to implement deep linking in my test app. I already tried out go_router. So, in documentation there is not much about deep linking. First I created page and added it to router like this:
```
GoRoute(
 name: 'deepLink',
 path: '/deepLink',
 builder: (context, state) => const DeepLinkPage(),
),
```
after I added intent filter to my AndroidManifest file as written <a href="https://docs.flutter.dev/development/ui/navigation/deep-linking">here</a>:
```
<!-- Deep linking -->
<meta-data android:name="flutter_deeplinking_enabled" android:value="true" />
<intent-filter android:autoVerify="true">
 <action android:name="android.intent.action.VIEW" />
 <category android:name="android.intent.category.DEFAULT" />
 <category android:name="android.intent.category.BROWSABLE" />
 <data android:scheme="http" android:host="akzdeeplink" />
 <data android:scheme="https" android:host="akzdeeplink" />
</intent-filter>
```
And what do i do from here? What I want achieve is when user presses URL it opens app at deepLink page

**Comment by maheshmnj** [comment]
Hi @AkzhanArdaki, Thanks for filing the issue. Please see the next section 
> Test on Android emulator
Running the specified command from the console should launch the app with the deeplink URL which must be handled within the app, probably in `navigatorBuilder`. If you need further help with handling deeplinks inside the app I would suggest asking a question on StackOverflow with a proper explanation and a minimal code sample.

Closing as this is neither a bug nor a feature request, In case you disagree feel free to write in the comments and we will reopen it.

Thank you.
