### ISSUE TITLE
Bug: Codelabs: FriendlyChat: Step 7: Focus does not go back to TextField on Enter in browser

### ISSUE THREAD

**Issue by DarkTrick** [flutter/flutter#103179]
Tutorial in question: https://codelabs.developers.google.com/codelabs/flutter/#6
Code in question: https://github.com/flutter/codelabs/blob/master/friendly_chat/step_07/lib/main.dart

Problem:
When the code is run in browser (dartpad.dev, Firefox / Safari), after submitting a message by hitting enter the focus is supposed to go back to the TextField for the user to type another message. While the focus seemingly goes back (caret blinks), keyboard input is disregarded.

**Steps to reproduce**

- open dartpad.dev  and switch to flutter.
- paste [the code](https://github.com/flutter/codelabs/blob/master/friendly_chat/step_07/lib/main.dart) and code.
- write a message in the bottom.
- press enter to submit the message (*do not use the send button*)
- EXPECTED: 
  - Focus is in text field.
  - user can write text.
- ACTUAL:
  - Caret blinks in text field.
  - Keyboard input is disregarded.

**Comment by danagbemava-nc** [comment]
Hi @DarkTrick, this is not an issue with the code but a bug in flutter itself. See #95553

Closing from here as duplicate. 

Thank you
