### ISSUE TITLE
Missing CircularProgressIndicator in Widget Catalog

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#10319]
Tracking issue.

cc @InMatrix should we just add this next to LinearProgressIndicator?

We can then add the words "spin" and "busy" to make the Control-F case easier.

See https://github.com/flutter/flutter/issues/10317

**Comment by InMatrix** [comment]
Sure, adding it next to LinearProgressIndicator sounds good to me. Adding "spin" and "busy" sounds good as well. The first sentence of its API doc already includes "spin": "A material design circular progress indicator, which spins to indicate that the application is busy."

**Comment by Hixie** [comment]
That's because I added those words to fix https://github.com/flutter/flutter/issues/10317. :-)

**Comment by zoechi** [comment]
Still not listed and only text (no link) on [LinearProgressIndicator](https://flutter.io/docs/development/ui/widgets/material#Information%20displays)

![image](https://user-images.githubusercontent.com/405837/49279734-8e019c80-f488-11e8-9e10-a68f1f5adee4.png)

**Comment by zoechi** [comment]
Issue moved to [flutter/website #2036](https://github.com/flutter/website/issues/2036) via [**ZenHub**](https://www.zenhub.com/)
