### ISSUE TITLE
[CP] Do not create incomplete DlColorSource objects from Skia gradients

### ISSUE THREAD

**Issue by flar** [flutter/flutter#103173]
### issue_link

https://github.com/flutter/flutter/issues/102947

### Commit Hash

b1b0a5a

### Target

stable

### Impacted Users

any Flutter dev using a matrix in a text gradient in 2.13(-pre)

### Impact Description

Gradients have an optional matrix that controls how their stop locations appear in the frame. If a Gradient is used to render text then we will fumble that matrix and render the gradient incorrectly.

### Workaround

In some cases, the matrix can be directly applied to, for example, the end points of a linear gradient, but that isn't true for all gradient types or all matrix types. A skewing gradient affects the perpendicular vectors of a gradient which can distort it in ways that applying the matrix to the geometry cannot achieve.

### Risk

low

### Test Coverage

yes

### Validation Steps

The original commit above had API tests to verify that we were implementing the API that was causing the problem correctly, but it did not contain a golden test to verify that we were rendering the correct output.

A golden test was merged immediately after the fix and can be found in https://github.com/flutter/engine/pull/33153

Running that golden test, or the test case in the original issue (both are basically the same code), will demonstrate the fix.

**Comment by CaseyHillers** [comment]
Landed in last week's hotfix in https://github.com/flutter/flutter/pull/103101

**Comment by CaseyHillers** [comment]
PR is in https://github.com/flutter/engine/pull/33131

**Comment by itsjustkevin** [comment]
@zanderso

**Comment by zanderso** [comment]
Cherry-picking into the first hotfix lgtm.

**Comment by XilaiZhang** [comment]
@flar Hello sir! there is a merge conflict when cherry picking this commit into the release branch flutter-2.13-candidate.0, could you help take a look at https://github.com/flutter/flutter/wiki/Flutter-Cherrypick-Process, and open a pr against the release branch to resolve the merge conflict? Thank you so much!

**Comment by itsjustkevin** [comment]
Cherry-picked into Flutter 3.0.1.
