### ISSUE TITLE
pubsub message count alert triggering

### ISSUE THREAD

**Issue by yusuf-goog** [flutter/flutter#103139]
https://pantheon.corp.google.com/monitoring/alerting/incidents/0.mhlvq8sxehac?project=flutter-dashboard&pageState=(%22interval%22:(%22i%22:(%22s%22:%222022-05-05T15:37:05.000Z%22,%22e%22:%222022-05-05T16:29:26.979Z%22)))

**Comment by yusuf-goog** [comment]
@CaseyHillers can you please take a look

**Comment by CaseyHillers** [comment]
I rolled back Cocoon to 701db1e. go/engine-build isn't getting it's results updated, and it's likely caused by https://github.com/flutter/cocoon/pull/1816.

I can revisit the PR and try to fix the bug in the logic. I didn't realize the hotfix was still being relied on.

**Comment by yusuf-goog** [comment]
FYI, alert has recovered: https://pantheon.corp.google.com/monitoring/alerting/incidents/0.mhlvq8sxehac?project=flutter-dashboard&pageState=(%22interval%22:(%22d%22:%22P42D%22,%22i%22:(%22s%22:%222022-05-05T15:37:05.000Z%22,%22e%22:%222022-05-05T16:59:04.000Z%22)))

**Comment by CaseyHillers** [comment]
De-duping with https://github.com/flutter/flutter/issues/102998 for the fix. I think we want to explicitly fail on builds that don't have a commit_key
