### ISSUE TITLE
LocalizationsDelegate: call load before isSupported

### ISSUE THREAD

**Issue by erf** [flutter/flutter#103151]
## Use case

I've made a custom Localization package called [csv_localizations](https://pub.dev/packages/csv_localizations)

Now `LocalizationsDelegate.isSupported` is call before `LocalizationsDelegate.load` method - if this was the other way around i could return the supported locales based on the languages listed in the CSV file.

## Proposal

Could the `load` method be called before `isSupported` ?

Could `isSupported` return a `FutureOr` in case we'd need to figure this out asynchronous?

**Comment by darshankawar** [comment]
@erf
I think your case is similar to https://github.com/flutter/flutter/issues/93865, so please follow-up in it for further updates.
Closing this as a duplicate. If you disagree, write in comments and I'll reopen it.

**Comment by erf** [comment]
@darshankawar I think that issue is different, my concern is with `isSupported` is called before `load`, the other issue is about loading time and splash screens.

**Comment by darshankawar** [comment]
Thanks for the feedback. Reopening.

**Comment by goderbauer** [comment]
That wouldn't make much sense. `LocalizationsDelegate.isSupported` is used to determine whether `LocalizationsDelegate.load` is supposed to be called or not. If the delegate doesn't support the requested locale, there's no point in loading it.

**Comment by erf** [comment]
> That wouldn't make much sense. `LocalizationsDelegate.isSupported` is used to determine whether `LocalizationsDelegate.load` is supposed to be called or not. If the delegate doesn't support the requested locale, there's no point in loading it.

Ok. My idea was that i could check if the language was supported dynamically based on the content of the file, but i guess i have to hard code this.
