### ISSUE TITLE
setState inside navigationDelegate doesn't work on android?

### ISSUE THREAD

**Issue by aikonics** [flutter/flutter#103129]
Hello, I hope you're doing well. I am having an issue with adding setState(() {}); inside the navigationDelegate method on Android, It doesn't work. It's working properly on iOS but It's not working on Android. I want to add a loading indicator when the URL contains "checkout?identifier". Any thoughts?

     bool showSpinner = true;     
     return ModalProgressHUD(
                opacity: 1,
                inAsyncCall: showSpinner,
                color: Colors.white,
                progressIndicator: CircularProgressIndicator(
                  color: primaryColor,
                ),
                child: WebView(
                  onWebViewCreated: (controller) {
                    _webViewController = controller;
                  },
                  onWebResourceError: (e) {
                    singleBookingBloc.add(FailedOperation());
                  },
                  onPageFinished: (e) async {
                    setState(() {
                      showSpinner = false;
                    });
                  },
                  navigationDelegate: (NavigationRequest request) {
   
                    if (request.url.contains('checkout?identifier')) {
                      setState(() {
                        showSpinner = true;
                      });
                    }

                    return NavigationDecision.navigate;
                  },
                  javascriptMode: JavascriptMode.unrestricted,
                  initialUrl: 'https://infavr.com/product/' +
                      widget.bookingSlug +
                      '?' +
                      widget.parameter,
                ),
              );

Flutter doctor -v

[✓] Flutter (Channel dev, 2.10.0-0.3.pre, on macOS 11.1 20C69 darwin-arm, locale en-PH)
    • Flutter version 2.10.0-0.3.pre at /Applications/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fdd0af78bb (3 months ago), 2022-01-25 22:01:33 -0600
    • Engine revision 5ac30ef0c7
    • Dart version 2.16.0 (build 2.16.0-134.5.beta)
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/aikbusmeon/Library/Android/sdk
    • Platform android-31, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 12.5.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] VS Code (version 1.66.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Connected device (2 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 12 (API 32) (emulator)
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 101.0.4951.54

[✓] HTTP Host Availability

**Comment by maheshmnj** [comment]
Hi @aikonics, Thanks for filing the issue. Please share a [minimal and complete reproducible code](https://stackoverflow.com/help/minimal-reproducible-example) without any third party packages to investigate this issue further.
