### ISSUE TITLE
API docs search box autocomplete fails

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#10314]
The autocomplete string overwrites the input string at a different offset...

![screenshot](https://cloud.githubusercontent.com/assets/1377460/26461596/858e3e38-4132-11e7-9f06-7dd6fca1aa08.png)

**Comment by sethladd** [comment]
cc @jcollins-g   Is this specific to docs.flutter.io or is it a generic dartdoc issue?

**Comment by jcollins-g** [comment]
This appears to be specific to flutter.io, probably something conflicting in the new style.  @devoncarew  ?

**Comment by devoncarew** [comment]
Yup, looks like the type ahead text is at a different offset and 1px off on font size.
