### ISSUE TITLE
Make "spin" and "busy" keywords you can use to find progress indicator.

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#10317]
From someone trying Flutter for the second time:
> found progress indicators in the gallery. A search for "spin" or "busy" on the dartdocs didn't help me.

**Comment by sethladd** [comment]
Does gallery mean "flutter gallery" or "widget gallery aka catalog" ?

**Comment by Hixie** [comment]
not clear

**Comment by floitschG** [comment]
I used the gallery app.
