### ISSUE TITLE
Android ListView bounces a little when scrolled quickly to the bottom

### ISSUE THREAD

**Issue by KevinTheGray** [flutter/flutter#10318]
If you build a simple ListView, put a lot of elements into it such that it can scroll, and then scroll it quickly to the bottom, it will bounce a little on Android.  

Here's a video of it: https://www.youtube.com/watch?v=GZK3esOBUEw

## Steps to Reproduce
Construct a widget with a ListView as the root element. Populate it so it can scroll, and scroll quickly to the bottom and it should bounce.

## Flutter Doctor
```
[✓] Flutter (on Mac OS X 10.12.4 16E195, locale en-US, channel master)
    • Flutter at /Users/KG/Developer/Flutter/flutter
    • Framework revision 4a9205572b (3 days ago), 2017-05-22 17:12:02 -0700
    • Engine revision 8b09c7231e
    • Tools Dart version 1.24.0-dev.3.0

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at /Users/KG/Library/Android/sdk
    • Platform android-25, build-tools 25.0.3
    • ANDROID_HOME = /Users/KG/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.3.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3.2, Build version 8E2002
    • ios-deploy 1.9.1
    • CocoaPods version 1.2.1

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Gradle version 3.2
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.1.3)
    • Dart plugin version 171.4424.63
    • Flutter plugin version 14.0

[✓] Connected devices
    • SM G930V • a674c503 • android-arm • Android 6.0.1 (API 23)
```

**Comment by Hixie** [comment]
This is more or less by design. If you're scrolling so fast that we don't yet have the last widget reified when you get to the end of the list, then we won't know to clamp when we start rendering, and then when we find we are too far, we apply the correction logic which bounces. You should be able to fix it by providing an explicit itemExtent to the ListView, if all your children are the same size.

**Comment by eseidelGoogle** [comment]
Does anyone know how Android avoids doing this?   Do we just need to be more aggressive about creating items ahead of the scroll?

**Comment by ds84182** [comment]
Android does have a slight bounce when scrolling really fast, so I wouldn't say this is really a bug. It also doesn't smoothly readjust in this case though, I think it shows blank space for a frame or two.

To reproduce, take any app that uses ListView (I dunno if RecyclerView will have the same behavior) and scroll really fast. Be careful though, some versions of Android have an integer overflow bug with fast scrolls (Lollipop I think, a fast scroll sometimes causes an unintended bounce).

**Comment by Hixie** [comment]
We should probably push the clamp logic all the way down to the layout objects and use our layout-time correction logic to avoid this.

**Comment by sumujain1995** [comment]
is this issue resolved?

**Comment by LouisParkin** [comment]
Hi @Hixie I am busy rewriting an old android app of mine in flutter, and, as far as I can see, only on my iPhone 6S, when I scroll to the very bottom of one of my lists, it reaches the point where it cuts the topmost item in half to display the last item in the list, and like a half a second later, it jumps up slightly to display the one that was cut fully, which then cuts the last item in the list in half.  Scroll down, it jumps back up, half a list item.  If I slowly scroll down as to not actually hit the bottom of the scroll area, the bottom item can be brought, and kept, into view.  It doesn't do this on iOS 13m (iPhone 11 simulator), nor does it happen on the Android emulator (pixel2 running Oreo 8.1).  Any thoughts?

**Comment by LucasAschenbach** [comment]
Is this also what's causing the following issue: https://github.com/flutter/flutter/issues/42540

**Comment by darshankawar** [comment]
The listview doesn't seem to bounce when it reaches bottom. Verified in latest stable (1.20.3).

[10318.mp4.zip](https://github.com/flutter/flutter/files/5173754/10318.mp4.zip)

<details>
<summary>flutter doctor -v</summary>

```
Flutter 1.20.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 216dee60c0 (2 days ago) • 2020-09-01 12:24:47 -0700
Engine • revision d1bc06f032
Tools • Dart 2.9.2

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.20.3, on Mac OS X 10.15.2 19C57, locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions.
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[✓] Android Studio (version 3.6)
[✓] Connected device (1 available)
```

</details>

**Comment by Piinks** [comment]
It has been a few years since the initial report, does Android still do this natively? I have tried it on the latest version of Android and not observed this subtle bounce. If someone else does, would you please leave a comment and possibly a video clip of the behavior? Thanks!
