### ISSUE TITLE
flutter url_launcher plugin integration_test "only web" gives ios device error on Arm64

### ISSUE THREAD

**Issue by JCzz** [flutter/flutter#103180]
I am trying to run integration test on url_loader from flutter [plugins][1]

I have in installed ChromeDriver for Apple silicon Arm64 from [here][2]

Running the driver on port 44:

    Run ./chromedriver — port=4444

Opened/run the url_launcher in Android Studio. Now running the integration test:

    integration_test/url_launcher_web_test.dart

I get the following in Android Studio test results:

    NoSuchMethodError: The getter 'simulatorBundlePath' was called on null.
    Receiver: null
    Tried calling: simulatorBundlePath
    
    dart:core-patch/object_patch.dart 38:5                             Object.noSuchMethod
    package:flutter_tools/src/ios/simulators.dart 385:44               IOSSimulator.installApp
    package:flutter_tools/src/ios/simulators.dart 454:18               IOSSimulator.startApp
    package:flutter_tools/src/test/integration_test_device.dart 53:52  IntegrationTestTestDevice.start

  [1]: https://github.com/flutter/plugins
  [2]: https://chromedriver.chromium.org/downloads

**Comment by darshankawar** [comment]
@JCzz 
I ran the `url_launcher` plugin's example that contains `integration_test` which ran properly without any issues.

1. cd `/Users/dhs/Documents/NCFlutter/plugins/packages/url_launcher/url_launcher/example`
2. Started chromedriver --port on 4444
3. Ran `flutter test integration_test/url_launcher_test.dart` which completed properly as below:

```
dhs@Dhss-MacBook-Pro example % flutter test integration_test/url_launcher_test.dart
Downloading Web SDK...                                              3.9s
Downloading CanvasKit...                                         1,331ms
Downloading darwin-x64/FlutterMacOS.framework tools...           2,785ms
Downloading darwin-x64-profile/FlutterMacOS.framework tools...        852ms
Downloading darwin-x64-profile tools...                            300ms
Downloading darwin-x64-release/FlutterMacOS.framework tools...        688ms
Downloading darwin-x64-release tools...                            267ms
00:04 +0: loading /Users/dhs/Documents/NCFlutter/plugins/packages/url_launcher/url_launcher/example/integration_test/url_launcher_test.dart                                                      Warning: Missing build name (CFBundleShortVersionString).
Warning: Missing build number (CFBundleVersion).
Action Required: You must set a build name and number in the pubspec.yaml file version field before submitting to the App Store.
00:09 +0: loading /Users/dhs/Documents/NCFlutter/plugins/packages/url_launcher/url_launcher/example/integration_test/url_launcher_test.dart                                                       R00:11 +0: loading /Users/dhs/Documents/NCFlutter/plugins/packages/url_launcher/url_launcher/example/integration_test/url_launcher_test.dart                                                1,565ms
00:39 +0: loading /Users/dhs/Documents/NCFlutter/plugins/packages/url_launcher/url_launcher/example/integration_test/url_launcher_test.dart                                                       
00:48 +0: loading /Users/dhs/Documents/NCFlutter/plugins/packages/url_launcher/url_launcher/example/integration_test/url_launcher_test.dart                                                   9.5s
Xcode build done.                                           37.6s
00:53 +1: All tests passed!  
```

Is this a correct interpretation / replication of the issue you reported ?

**Comment by JCzz** [comment]
Thanks @darshankawar

I am running on Apple Silicon arm64, in case it make any different?

**Comment by JCzz** [comment]
Thanks, yes correct, these are the steps.

**Comment by JCzz** [comment]
Sorry, no it is in url_launcher_web and running these tests from the terminal gives:

```
flutter test integration_test/url_launcher_test.dart
Web devices are not supported for integration tests yet.
```

and from within Android studio is gives(same as above in the issue description):

```
NoSuchMethodError: The getter 'simulatorBundlePath' was called on null.
Receiver: null
Tried calling: simulatorBundlePath

dart:core-patch/object_patch.dart 38:5                             Object.noSuchMethod
package:flutter_tools/src/ios/simulators.dart 385:44               IOSSimulator.installApp
package:flutter_tools/src/ios/simulators.dart 454:18               IOSSimulator.startApp
package:flutter_tools/src/test/integration_test_device.dart 53:52  IntegrationTestTestDevice.start
```

Running this in the terminal, I guess it is not supported for web - sorry I did not see that in Android Studio.

**Comment by darshankawar** [comment]
> Running this in the terminal, I guess it is not supported for web - sorry I did not see that in Android Studio

I tried the same running from Android studio and received expected result as below:

<img width="621" alt="Screenshot 2022-05-09 at 11 31 56 AM" src="https://user-images.githubusercontent.com/67046386/167349549-024d1574-9484-4514-b76d-ebc838b29195.png">

Can you provide `flutter doctor -v` ?

**Comment by darshankawar** [comment]
> "yet", do you know if it is in progress and how do you test you ui then?

I don't have details around it. The message means url_launcher related integration tests doesn't seem to support web for now.

Closing as this is not an issue.
