### ISSUE TITLE
Make "scrollable list" something you can find when searching widgets-library

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#10316]
From someone trying Flutter for the second time:
> Lots of "List" on the API page, but found "ListView" relatively fast. In the gallery they are called "scrollable" list, but searching for "scrollable list" on the widgets-library page doesn't trigger, because it is described as "A scrollable, linear list of widgets".

**Comment by sethladd** [comment]
When you say "gallery", do you mean gallery app or widget gallery?

**Comment by Hixie** [comment]
i assume widget gallery.

**Comment by floitschG** [comment]
The gallery app.
I used the gallery app to find the widgets I need.

**Comment by sethladd** [comment]
It's going to be difficult to write synonyms for every literal search query. I'm happy to try to make overall searching better, though. Our search box should answer customer question s:)

I used flutter.io search box for "scrollable list" and the second response was https://flutter.io/widgets/scrolling/

@floitschG have you seen our widget catalog? Wondering if that's useful... ?
