### ISSUE TITLE
typo in the Flutter Codelab

### ISSUE THREAD

**Issue by knutvalen** [flutter/flutter#10312]
There is a minor typo in the Flutter Codelab. "property" is typed twice, see the screenshot. 
![screen shot 2017-05-25 at 14 18 18](https://cloud.githubusercontent.com/assets/2733083/26449960/65df70c0-4155-11e7-8d17-54bbef501c54.png)

**Comment by LarkAscending** [comment]
Thank you!

Fixed:
https://codelabs.developers.google.com/codelabs/flutter/#4
