### ISSUE TITLE
Scheduling logic causing too many duplicate builds

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#103168]
There are a few problems causing the duplicate builds:

## Release branches build configurations

The release branches  sometimes have build configurations for builders that do not exist anymore. This causes the grpc to fail with 500 status code:

![image](https://user-images.githubusercontent.com/54371434/167052253-241c383e-5cff-4c46-b939-d69f39ab0a51.png)

This causes the handler to fail without acking the pubsub message.

## Pubsub delivery retry

The current subscription configuration will try to deliver the failed message starting from 1m with an exp backoff of 10 seconds up to  10m. The message retention is 2 days. 

![image](https://user-images.githubusercontent.com/54371434/167052745-917abf12-ffa6-4953-92f6-e6fa7695a736.png)
 
These two problems combined can easily scale up to consume all the available capacity.

**Comment by godofredoc** [comment]
Mitigations:

* Unacked messages were purged
* All the pending builds have been cancelled

**Comment by yusuf-goog** [comment]
\cc @CaseyHillers

**Comment by keyonghan** [comment]
Issue mitigated. Adjusting the priority to P3.

**Comment by godofredoc** [comment]
I don't think this is a P3. I've been purging the pubsub queue manually after every release candidate branches PR

**Comment by keyonghan** [comment]
> I don't think this is a P3. I've been purging the pubsub queue manually after every release candidate branches PR

Didn't know that. Adjusting back.

Every time when you cleaned up, did you see specific builders pending, or it happened across all builders? Last time, from internal chat, seems it happened only on `Mac Web Engine`.

**Comment by godofredoc** [comment]
This happens every time a release candidate branch PR tries to run a build that does not exist anymore.

**Comment by keyonghan** [comment]
This is caused by deleted `Windows UWP Engine` builder in luci config, which causes exception in batch scheduling. The result is pub/sub message not acked and it keeps retrying/rescheduling.

https://github.com/flutter/cocoon/pull/1834 to fix.
