### ISSUE TITLE
Is there any way to validate that the entered text is the price?

### ISSUE THREAD

**Issue by mycar98765** [flutter/flutter#103169]
I want to validate that the entered text is the price. I want it to validate that the user entered a number and "." only. My Flutter app automatically enters "," and currency symbols. How can I verify it?

**Comment by maheshmnj** [comment]
Hi @mycar98765, 
The flutter Framework does not provide any such solution out of the box, You will need to implement that yourself by restricting the Textfield with inputFormatters to allow only the desired numbers and characters. In case you need further help I would suggest asking this question on StackOverflow with a clear explanation along with a minimal code sample.
You may also leave the question link here and I can take a look.

Closing as this is neither a bug nor a feature request.
