### ISSUE TITLE
Consider disabling repaint boundaries (at the render object level) if a scrollable cannot actually scroll

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#103162]
Internal: b/292548462

The function of a repaint boundary in a scrollable is primarily that it allows the scrolling to change the offset of the child picture without repainting the picture. This works in conjunction with the engine's raster cache, which is most effective when pictures are moderately complex and stable. For the sake of memory/performance limits, we typically try to limit the number of entries cached per frame.

Because this is generally usefull, and because we don't want users to have to think too hard about this, all scrollables automatically insert repaint boundaries around their children via `addRepaintBoundaries: true`.

However with nested list views, we still wrap all children in repaint boundaries. But this can end up dividing the screen into dozens and dozens of tiny pictures. Individually caching each individual picture is much less likely than caching the overall picture (were it in a wrap, column, row). Even if each picture is complex enough, we will quickly hit the limits of the number of pictures cached per frame, and caching these individual pictures is also less efficient.

While this situation is common with nested shrink-wrapped lists, it can also happen with cross-axis lists. It may be the case that another scrollable is used because the container _may_ have enough items that it would overflow, so the application accounts for this by using a cross axis scrollable. 

But If the nested scrollable can't actually scroll (because it doesn't have enough items), then we get all the downsides listed above of the additional repaint boundaries with no benefit.

If we could conditinally disable these repaint boundaries when the scrollable can't actually scroll, there shouldn't be any downside and the pictures won't be reduced in size too much.  We should also address this with more documentation on the addRepaintBoundary member.

**Comment by jonahwilliams** [comment]
This was observed via customer:money application but could apply to a much wider set of circumstances. I'll plan on adding a microbenchmark example to demonstrate here

**Comment by ColdPaleLight** [comment]
I'm a little concerned that this proposal will have side effects in some scenarios. Imagine a non-scrollable list with multiple items, one of which is animating. In the current implementation, the animation will only repaint that item, while the proposed solution will repaint the entire list. Please let me know if I missed something.

**Comment by jonahwilliams** [comment]
If that list is inside another list it already has a repaint boundary though. If its not in another list, perhaps we shouldn't do that.

**Comment by jonahwilliams** [comment]
though generally I think the "single animating widget on simple UI" example is a bit contrived. If you don't have a list and instead just have a spinning widget in the default scaffold you'll repaint the whole screen. If the screen isn't complex, its not really that bad in either case

**Comment by jonahwilliams** [comment]
Anyway, we could restrict this to non-primary scrollables

**Comment by ColdPaleLight** [comment]
> Anyway, we could restrict this to non-primary scrollables

I got it. If so, I think another scene could consider disabling repaint boundaries as well. Imagine a scenario where there are multiple items in a vertically scrolling list, and each item has a horizontally scrollable list in it. In this case, I guess we can consider disabling the repaint boundaries in the horizontal list.

**Comment by jonahwilliams** [comment]
yeah that one is tricky. if the horizontal scrollable is a small gridview or something the repaint boundaries aren't worth it, but if it is a fairly complex list in its own right then they may still help - especially if the crossaxis size is significant.

**Comment by jonahwilliams** [comment]
I've decided this doesn't matter, as long term we'd like to remove the raster cache.
