### ISSUE TITLE
[local_auth] Add possibility to use error_codes to catch specific exceptions 

### ISSUE THREAD

**Issue by RuslanSk1p** [flutter/flutter#103125]
In version 1.1.11 it was possible to import error_codes as : import 'package:local_auth/local_auth.dart/error_codes.dart' as auth_error;

In version 2.0.0 as package started using strict exports there is no way to access error codes.
Consider adding :

```
export ‘package:local_auth/src/types/error_codes.dart’ as ErrorCodes 

```
to packages/local_auth/local_auth/lib/local_auth.dart

**Comment by maheshmnj** [comment]
Hi @RuslanSk1p, Thanks for filing the issue.  I do see that `errorCodes` is not being exported

Could you please specify what exactly are you trying to use from error_codes.dart or why is the export necessary?

**Comment by stuartmorgan** [comment]
This was a mistake during federation; it should not be in `src`.
