### ISSUE TITLE
IOS build crashed :  'Flutter/Flutter.h' file not found

### ISSUE THREAD

**Issue by chenshaxuanjing** [flutter/flutter#103241]
flutter run -v :

[flutter_run_v.txt](https://github.com/flutter/flutter/files/8644183/flutter_run_v.txt)

iOS/podfile  : 
[podfile.txt](https://github.com/flutter/flutter/files/8644184/podfile.txt)

iOS/podfile.lock :
[podfile_lock.txt](https://github.com/flutter/flutter/files/8644185/podfile_lock.txt)

pubspec.yaml :
[pubspec_yaml.txt](https://github.com/flutter/flutter/files/8644186/pubspec_yaml.txt)

pubspec.lock :
[pubspec_lock.txt](https://github.com/flutter/flutter/files/8644187/pubspec_lock.txt)

iOS/runner.xcodeproj/project.pbxproj :
[project_pbxproj.txt](https://github.com/flutter/flutter/files/8644189/project_pbxproj.txt)

**Comment by darshankawar** [comment]
Looking at the error log, it it throwing `ios/Runner/GeneratedPluginRegistrant.h:10:9: error: 'Flutter/Flutter.h' file not found
               #import <Flutter/Flutter.h>` for which there's similar open issue : https://github.com/flutter/flutter/issues/99387 so please follow-up in it for further updates.

Closing this as a duplicate.
