### ISSUE TITLE
How to fix bug in listview getx flutter

### ISSUE THREAD

**Issue by majidpourdavood** [flutter/flutter#103297]
The following assertion was thrown while dispatching notifications for ScrollController:
ScrollController attached to multiple scroll views.
'package:flutter/src/widgets/scroll_controller.dart':
Failed assertion: line 108 pos 12: '_positions.length == 1'

**Comment by XuanTung95** [comment]
Don't put ScrollController inside a controller and make sure there is no chance a ScrollController can be used by multiple scroll views at the same time.

**Comment by 350887156** [comment]
Add different tags when creating GetXController

example
```
return GetX<ExampleController>(
      init: ExampleController(),
      tag: example.id,//Add it
...
);

```

```
return GetBuilder<ExampleController>(
      init: ExampleController(),
      tag: example.id,//Add it
...
);
```


```
Get.put<ExampleController>(ExampleController(),tag:example.id);
```

**Comment by darshankawar** [comment]
Please ask support questions on StackOverflow. Closing from here.
