### ISSUE TITLE
Mac43 is failing tests consistently

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#103237]
Ever since a failed [release build](https://luci-milo.appspot.com/ui/p/flutter/builders/prod/Mac_ios%20beta%20complex_layout_scroll_perf_ios__timeline_summary/154/overview), the bot started failing with
```
Testing failed:
	infra-dialogUITests:
		infra-dialogUITests-Runner encountered an error (Failed to install or launch the test runner. If you believe this error represents a bug, please attach the result bundle at /Users/swarming/Library/Developer/Xcode/DerivedData/infra-dialog-ayzxmkyimrprakexnyiavfekoqad/Logs/Test/Test-infra-dialog-2022.05.06_16-10-11--0700.xcresult. (Underlying Error: Unable to launch dev.flutter.infra-dialogUITests.xctrunner. (Underlying Error: Request to launch dev.flutter.infra-dialogUITests.xctrunner failed. The operation couldn’t be completed. Unable to launch dev.flutter.infra-dialogUITests.xctrunner because it has an invalid code signature, inadequate entitlements or its profile has not been explicitly trusted by the user. : Failed to launch process with bundle identifier 'dev.flutter.infra-dialogUITests.xctrunner'. (Underlying Error: The operation couldn’t be completed. Unable to launch dev.flutter.infra-dialogUITests.xctrunner because it has an invalid code signature, inadequate entitlements or its profile has not been explicitly trusted by the user.))))
```

<img width="1294" alt="Screen Shot 2022-05-06 at 4 19 58 PM" src="https://user-images.githubusercontent.com/54558023/167227154-d183794d-4a44-4737-bab5-8be8428dee4f.png">

<img width="433" alt="Screen Shot 2022-05-06 at 4 19 29 PM" src="https://user-images.githubusercontent.com/54558023/167227137-1a2545c1-c31e-420e-87e6-0362a681745c.png">

A couple of issues:
1) The bot is expected to auto quarantine with https://chrome-internal-review.googlesource.com/c/infradata/config/+/4732106, but it is not.
2) The device doctor clean up seems not running after test failure.

**Comment by keyonghan** [comment]
Manually quarantined the bot.

**Comment by keyonghan** [comment]
`idevicediagnostics` is not found on M1 bots. https://github.com/flutter/cocoon/pull/1856 to add support.

**Comment by keyonghan** [comment]
The bot is ready to bring back. Before that, shall we enforce release builders to `cpu: x86`? /cc @CaseyHillers

**Comment by CaseyHillers** [comment]
flutter and engine had this change CP'd a few weeks back (and the packaging builders got it added manually)

**Comment by keyonghan** [comment]
Bot is back online passing tests consistently. Auto quarantine bot is tracked https://github.com/flutter/flutter/issues/96616
