### ISSUE TITLE
Project template use existing organization or default to com.example

### ISSUE THREAD

**Issue by mravn-google** [flutter/flutter#10329]
Currently `flutter create` uses `com.yourcompany` which is up for sale and may at some point be in real use.

The change should be accompanied by functionality to detect existing organization when running `flutter create` on an existing (perhaps partial) project so that we e.g. avoid creating `android/app/src/main/java/com/example/` when `android/app/src/main/java/com/yourcompany/` already exists.

**Comment by Hixie** [comment]
This is a new user experience blocker, since we don't control that domain (and other people could). We should either buy the domain or (preferred) use `example.com`. Leaving in current milestone.

**Comment by mit-mit** [comment]
@mravn-google are you likely to work on this, or should we remove you as the assignee?

**Comment by mravn-google** [comment]
It's on my list.
