### ISSUE TITLE
Map function doesn't seem to work on firebase database stream

### ISSUE THREAD

**Issue by ajonp** [flutter/flutter#10321]
map is never called, listen still prints the original DataSnapshot

```
//Merge two streams
      var _fireFollower = FirebaseDatabase.instance.reference().child('followers/' + auth.currentUser.uid);
      _fireFollower.onValue.map((Event e){
        print('not working');
        return FirebaseDatabase.instance.reference().child('users/' + e.snapshot.key);
      });
      _fireFollower.onValue.listen((e){
        print(e.snapshot.value);
      });
```

I should add that when I tried this with a basic example it fails:
```
  Stream<int> timedCounter(Duration interval, [int maxCount]) {
    StreamController<int> controller;
    Timer timer;
    int counter = 0;

    void tick(_) {
      counter++;
      controller.add(counter); // Ask stream to send counter values as event.
      if (maxCount != null && counter >= maxCount) {
        timer.cancel();
        controller.close();    // Ask stream to shut down and tell listeners.
      }
    }

    void startTimer() {
      timer = new Timer.periodic(interval, tick);
    }

    void stopTimer() {
      if (timer != null) {
        timer.cancel();
        timer = null;
      }
    }

    controller = new StreamController<int>(
        onListen: startTimer,
        onPause: stopTimer,
        onResume: startTimer,
        onCancel: stopTimer);

    return controller.stream;
  }

  Stream<int> get onValue => timedCounter(const Duration(seconds: 1), 15);
```

Fails:
```
main() {
   this.onValue.map((int x){
        print('timed counter:');
        return x * 2;
    });
    this.onValue.listen(print);
}
```

This works:
```
Stream<int> counterStream2 =
    timedCounter(const Duration(seconds: 1), 15).map((int x){
        print('timed counter:');
        return x * 2;
    });
    counterStream2.listen(print);

```

**Comment by sethladd** [comment]
cc @collinjackson

**Comment by collinjackson** [comment]
I think there's are a few confusing issues here:

- [`Stream.map`](https://api.dartlang.org/stable/1.23.0/dart-async/Stream/map.html) returns a `Stream` object. Until a client starts listening to the mapped stream, Dart has no reason to fire the callback, so it doesn't bother.
- Dart's [package:async](https://pub.dartlang.org/packages/async) provides a way to combine multiple streams in Dart.
- `Query.onValue` will normally fire only once for a query that has children. It won't fire again until the data changes. The `value` of the `DataSnapshot` could be a `Map` if `followers` nodes are created using `push()`, or a `List` if the followers are defined using `set` with a `List`.
- Probably you should be creating your follower nodes using `push()` to prevent race conditions. So I'm going to assume you're doing that.

So I think you're trying to do something like this:

    var root = FirebaseDatabase.instance.reference();
    Stream _fireFollower = StreamGroup.merge(
      root.child('followers/' + auth.currentUser.uid).onValue.map((Event e) {
        return e.snapshot.value.values.map((uid) => root.child('users/$uid').onValue);
      }),
    );

This approach is fine for small numbers of followers. If you expect to have a lot, consider using `FirebaseAnimatedList` to only query the followers that are visible. `FutureBuilder` and `StreamBuilder` are very useful for working with Firebase as well.

Also, remember you can call `once()` to get a Future if you just want a one-time snapshot and don't need to be notified about changes.

**Comment by collinjackson** [comment]
It is my understanding that this is working as intended, but let me know if I'm mistaken.

**Comment by kroikie** [comment]
@ajonp

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1007. Any further collaboration will be done there.
