### ISSUE TITLE
MaterialBanner is not updating when calling ScaffoldMessenger.of(context).setState(() {});

### ISSUE THREAD

**Issue by large** [flutter/flutter#103277]
## Use case

MaterialBanner() is a StatefulWidget and are created in `ScaffoldMessenger.of(context).showMaterialBanner(....);`
Since it is Stateful, shouldn't it be possible to add a for instance a LinearProgressIndicator() and set new value through setState()?

![image](https://user-images.githubusercontent.com/535446/167270681-096d921b-4710-4eb3-8172-7964496537b7.png)

Example of implementation
```Dart
            ScaffoldMessenger.of(context).showMaterialBanner(MaterialBanner(
                content: LinearProgressIndicator(
                  value:
                      getIt<LongBackgroundProcessingQueue>()
                          .current()
                          .toDouble()
                      /
                      getIt<LongBackgroundProcessingQueue>()
                          .totals()
                          .toDouble(),
                ),
                actions: const [Text("Hide")]));
```

## Proposal
The MaterialBanner() should be updated with something simple as this
```Dart
ScaffoldMessenger.of(contextSomewhereInTheApp).setState(() {});
```

With such implementation you'll show progress for a task/queue all over your app where Scaffolding is included.

**Comment by darshankawar** [comment]
@large 
I think this proposal can be a part of this open issue https://github.com/flutter/flutter/issues/60024, so please share your use case in it for better tracking.
Closing this as a duplicate.
