### ISSUE TITLE
[infra] Deprecate branches version field

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#103213]
Recipes are no longer branched manually, but instead via git branches.

We no longer need to update the recipe names based on this field, and it can be removed.

https://cs.opensource.google/flutter/infra/+/main:config/lib/release_branches/branches.proto;l=8 can be marked as reserved, and the codebase can be cleaned up of all the references.

**Comment by Hirdey-1999** [comment]
I Can Go With This Issue But Can You Explain With The Issue

**Comment by Dev-Akash** [comment]
Hi, so is this issue still open for contribution.
As I'm new here, and looking to contribute to the repo.

**Comment by keyonghan** [comment]
Cache uses the version to distinguish named caches between release and main/master branches. Closing as this is still needed. Please reopen if I missed anything.
