### ISSUE TITLE
starting a Flutter app from an IDE on a VR headset causes the app on the device to hang

### ISSUE THREAD

**Issue by csells** [flutter/flutter#103234]
## Steps to Reproduce

1. Attach a Quest 2 VR headset to your computer and [enable developer mode](https://developer.oculus.com/documentation/unity/unity-enable-device/) such that it shows up in `adb devices` and `flutter devices`
1. Create a new Flutter project from the CLI or your IDE of choice (I've tried both AS and VSC)
1. Deploy and execute the Flutter app from Android Studio or VS Code using either Run or Debug, targeting the Quest 2 device

**Expected results:** I see the Flutter counter app running on my Quest 2 and am able to use the Quest controllers to interact with it. If I'm debugging, I can set breakpoints and they'll be hit, etc.

**Actual results:** I see three pulsing white dots on a black background, mocking me in their eternal progress indication.

If I perform the equivalent steps for a native Android app, i.e. create a new Android project and deploy the app from Android Studio to my Quest 2, it runs and I'm able to debug it as expected.

If I manually deploy the Flutter app's apk, then I can see the Flutter app run on my Quest 2 and interact with it using the controllers:

```sh
$ flutter build apk
$ adb install path/to/flutter_app_name.apk
$ adb shell monkey -p com.domain.flutter_app_name 1
```

It's only when deploying my Flutter app from AS or VSC to enable debugging that there is trouble. I've tried it on both the latest beta and the latest stable, getting the same results. I'm trying this from my Apple M1 Max although it's my understanding that the same thing happens using 64-bit Intel processors running Windows as well.

<details>
  <summary>Logs</summary>

```
# `flutter run --verbose` output flagged by GitHub as too long; `flutter run` output follows:
➜ flutter run
Launching lib/main.dart on Quest 2 in debug mode...
Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
Running Gradle task 'assembleDebug'...                           2,432ms
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
Syncing files to device Quest 2...                                  51ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

💪 Running with sound null safety 💪

An Observatory debugger and profiler on Quest 2 is available at:
http://127.0.0.1:58140/FtQBh0Rz4-M=/
The Flutter DevTools debugger and profiler on Quest 2 is available at:
http://127.0.0.1:9103?uri=http://127.0.0.1:58140/FtQBh0Rz4-M=/
```

```
➜ flutter analyze
Analyzing flutter_application_7...                                      
No issues found! (ran in 1.6s)
```

```
➜ flutter doctor -v
[✓] Flutter (Channel stable, 2.10.5, on macOS 12.3.1 21E258 darwin-arm, locale
    en-US)
    • Flutter version 2.10.5 at /Users/csells/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (3 weeks ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/csells/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] VS Code (version 1.67.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Connected device (3 available)
    • Quest 2 (mobile) • 1WMHH824UW0353 • android-arm64  • Android 10 (API 29)
    • macOS (desktop)  • macos          • darwin-arm64   • macOS 12.3.1 21E258
      darwin-arm
    • Chrome (web)     • chrome         • web-javascript • Google Chrome
      101.0.4951.54

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
Thanks for the report @csells. I'll directly label this issue for further analysis and insights from the team, since we don't have VR headset to verify this issue on.

**Comment by Hixie** [comment]
From the logs it looks like it does launch on the device, so the issue is presumably just that we're launching incorrectly in some way that doesn't end up showing in the headset?

**Comment by csells** [comment]
Correct, @Hixie. A native Android app starts and displays correctly. However, a Flutter app only shows a black background and a pulsing ellipses. I assume some part of the initial communication between the debugger and the app is failing.

**Comment by Hixie** [comment]
Can you attach the `flutter run -v` logs?

If you have any way to debug where the problem might be happening that would definitely help, I don't think we have anyone with the device available.

**Comment by csells** [comment]
Further investigation shows that a difference between the way that AS starts native Android app debugging and the way that AS/VSC starts Flutter app debugging may account for the difference in behavior. Specifically, AS starting a native Android app via `adb start am` may include the action and category flags explicitly: `-a android.intent.action.MAIN -c android.intent.category.LAUNCHER1` whereas AS/VSC starting a Flutter app may not include these flags. Presumably the Android team explicitly includes the additional flags to enable a larger set of Android devices.

I don't know where to look in the logs to verify this or whether the Flutter tooling allows for these flags to be manually added, however. Perhaps @jonahwilliams @christopherfujino @devoncarew @DanTup would know?

**Comment by DanTup** [comment]
@csells I'm not very familiar with this code, but I suspect the relevant part for these flags is here:

https://github.com/flutter/flutter/blob/61cbe6ea8a13bffc5d33e1257ee75b3b418fbe0e/packages/flutter_tools/lib/src/android/android_device.dart#L626-L628

It seems to always pass `'-a', 'android.intent.action.RUN',` and it doesn't seem like `-c` is ever set (or can be set from flags).

To test whether that's the issue, you could try modifying the flags there (then deleting `flutter/bin/cache/flutter_tools.stamp` so the `flutter` is rebuilt on net run) and then run from `flutter run` / VSC.

**Comment by csells** [comment]
I submitted a PR: https://github.com/flutter/flutter/pull/104135

**Comment by csells** [comment]
Interestingly, even the default `AndroidManifest.xml` we generate from `flutter create` produces an intent with the action as MAIN and the category as LAUNCHER:

```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.foo7">
   <application
        android:label="foo7"
        android:name="${applicationName}"
        android:icon="@mipmap/ic_launcher">
        <activity
            android:name=".MainActivity"
            android:exported="true"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            <!-- Specifies an Android theme to apply to this Activity as soon as
                 the Android process has started. This theme is visible to the user
                 while the Flutter UI initializes. After that, this theme continues
                 to determine the Window background behind the Flutter UI. -->
            <meta-data
              android:name="io.flutter.embedding.android.NormalTheme"
              android:resource="@style/NormalTheme"
              />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
        <!-- Don't delete the meta-data below.
             This is used by the Flutter tool to generate GeneratedPluginRegistrant.java -->
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
    </application>
</manifest>
```

It seems like the use of MAIN + LAUNCHER is more correct in this case.

**Comment by DanTup** [comment]
Nice! That seems reasonable to me, though I'm not very familiar with Android so would seek a more informed opinion. I think you'll need to update some tests though:

https://github.com/flutter/flutter/blob/2ad7ced9162be02bcdd7d4ea270f7ee5546e67a9/packages/flutter_tools/test/general.shard/android/android_device_start_test.dart#L94-L109

**Comment by csells** [comment]
> I think you'll need to update some tests though:

Correct. Fixed!

**Comment by blasten** [comment]
Thanks, @csells!  You are right, it looks like we were doing it wrong. https://cs.android.com/android-studio/platform/tools/adt/idea/+/mirror-goog-studio-main:android/src/com/android/tools/idea/run/activity/AndroidActivityLauncher.java;l=22-28?q=android.intent.category.LAUNCHER%20-f:.xml&ss=android-studio&start=11

**Comment by csells** [comment]
Well everyone gets lucky sometimes : )

**Comment by nilsreichardt** [comment]
We can close this ticket because https://github.com/flutter/flutter/pull/104135 got merged, right?

**Comment by csells** [comment]
we can indeed. I've tested the merged bits and they work great.
