### ISSUE TITLE
Flutter how to bind and call function dynamically

### ISSUE THREAD

**Issue by abdulrehmananwar** [flutter/flutter#103247]
i want to bind functions as describe in code please resolve the issue
import 'package:flutter/material.dart';

class WindowListener{
  final Function()? Add;
  final Function()? Delete;
  WindowListener({this.Add, this.Delete,});
}

class Buttons extends StatelessWidget {
  const Buttons({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Row(children: [
      // here want to bind windows listner add function
      IconButton(onPressed: (){}, icon: Icon(Icons.add)),
      // here want to bind windows listner add function
      IconButton(onPressed: (){}, icon: Icon(Icons.delete)),
    ],);
  }
}

class MainPage extends StatefulWidget {
  const MainPage({Key? key}) : super(key: key);
  @override
  State<MainPage> createState() => _MainPageState();
}

class _MainPageState extends State<MainPage> {
  @override
  Widget build(BuildContext context) {
    return
      Scaffold(body:

      Column(children: [
      Buttons(),
      ChildPage()

    ],),);
  }
}

class ChildPage extends StatefulWidget {
  const ChildPage({Key? key}) : super(key: key);

  @override
  State<ChildPage> createState() => _ChildPageState();
}

class _ChildPageState extends State<ChildPage> {
  // here if add function call then do this
  void AddFunction()
  {
    print('Add button clicked');
  }
  
// here if Delete function call then do this
  void DeleteFunction()
  {
    print('delete button clicked');
  }

  @override
  Widget build(BuildContext context) {
    return Column(children: [
      Text('This is child page')
    ],);
  }
}

## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by stuartmorgan** [comment]
For help with your own code, try one of the resources listed at https://flutter.dev/community#community-grid

Closing as this is not an issue in Flutter itself, which is what we track here.
