### ISSUE TITLE
Mirror the following repos to flutter.googlesource

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#103223]
The following repositories are used for building mac tools:

* ~cocoapods~
* homebrew-flutter
* ideviceinstaller
* ios-deploy
* libimobiledevice
* libplist
* libtasn1
* ~libtasn1-flutter~
* libusb
* libusbmuxd
* libzip
* openssl

**Comment by godofredoc** [comment]
@christopherfujino do we need to keep the ones with -flutter?

**Comment by christopherfujino** [comment]
i think one of the libtasn1 repos is redundant. as for homebrew-flutter, we can deprecate that once we stop using homebrew to compile libimobiledevice.

**Comment by yusuf-goog** [comment]
@godofredoc is this a ticket queue bug?

**Comment by godofredoc** [comment]
`cocoapods` does not need a third party fork

**Comment by godofredoc** [comment]
https://flutter.googlesource.com/third_party/ideviceinstaller is ready with 1h updates.

**Comment by godofredoc** [comment]
https://flutter.googlesource.com/third_party/libimobiledevice is ready with 1h updates.

**Comment by godofredoc** [comment]
https://flutter.googlesource.com/third_party/ios-deploy is ready with 1h updates.

**Comment by godofredoc** [comment]
https://flutter.googlesource.com/third_party/libtasn1 is ready with 1h updates.

**Comment by godofredoc** [comment]
https://flutter.googlesource.com/third_party/libusb/ is ready with 1h updates.

**Comment by godofredoc** [comment]
https://flutter.googlesource.com/third_party/libzip/ is ready with 1h updates.

**Comment by godofredoc** [comment]
https://flutter.googlesource.com/third_party/openssl/ is ready with 1h updates.

**Comment by godofredoc** [comment]
We are missing homebrew-flutter

**Comment by keyonghan** [comment]
> https://flutter.googlesource.com/third_party/libimobiledevice is ready with 1h updates.

Seems something is misconfigured. I am not able to checkout. For example:
https://flutter.googlesource.com/third_party/libimobiledevice/+/refs/heads/master
```
git clone https://flutter.googlesource.com/third_party/libimobiledevice
Cloning into 'libimobiledevice'...
remote: Total 9777 (delta 7591), reused 9777 (delta 7591)
Receiving objects: 100% (9777/9777), 2.71 MiB | 677.00 KiB/s, done.
Resolving deltas: 100% (7591/7591), done.
warning: remote HEAD refers to nonexistent ref, unable to checkout.
```

Also the repo is not being updated (latest change is on 05/10/2022)

**Comment by yusuf-goog** [comment]
@keyonghan I don't think these are setup to be mirrored? Atleast not through copybara.

**Comment by godofredoc** [comment]
There was a typo on the mirror link, it was updated and now things are working properly.

**Comment by keyonghan** [comment]
Reopening this issue as other repos need a gob config fix as well (now only `libimobiledevice` works).

I tried updating the default branch from `main` to `master`, but hit permission issues:
```
gob-ctl repos update-ref flutter/third_party/libplist --ref=HEAD --old-ref-target=refs/heads/main --new-ref-target=refs/heads/master
E0721 10:35:43.904463  135768 errorlogger.go:93] gob-ctl GGoB::PERMISSION_DENIED_BY_REPOSITORY_ACL (canonical: PERMISSION_DENIED, elapsed: 0.1998s, deadline: none, caller: unknown, backend: unknown, traced: false, trace_id: 0x0000000000000000) 
[type.googleapis.com/google.rpc.RequestInfo]
request_id:  "60f0d4f1dff042b98dcab520738e90d7"
```

Here are the list that needs a fix:
- [ ] https://flutter.googlesource.com/third_party/ideviceinstaller
- [ ] https://flutter.googlesource.com/third_party/ios-deploy
- [ ] https://flutter.googlesource.com/third_party/libplist
- [ ] https://flutter.googlesource.com/third_party/libtasn1
- [ ] https://flutter.googlesource.com/third_party/libusbmuxd
- [ ] https://flutter.googlesource.com/third_party/libusb/
- [ ] https://flutter.googlesource.com/third_party/libzip/ 
- [ ] https://flutter.googlesource.com/third_party/openssl/

**Comment by keyonghan** [comment]
All work now. Thanks!
