### ISSUE TITLE
Merge KeyboardServiceState into KeyboardServiceImpl

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#1032]
It's not clear why we need both of these classes.

**Comment by abarth** [comment]
KeyboardServiceState is one-to-one with the android.view.View that hosts the keyboard.  KeyboardServiceImpl is one-to-one with Mojo message pipes.  There's a many-to-one relationship between Mojo message pipes and android.view.Views.  The KeyboardServiceImpl-to-KeyboardServiceState relationship is there the many-to-one relationship is held.

**Comment by Hixie** [comment]
So two parts of the system could ask for a KeyboardService and independently set the text and the selection, with no way for them to know when the second has clobbered the first's?

**Comment by eseidel** [comment]
We have these two classes for object lifetime separation.  You can create multiple pipes and they should all back in the same state as is unique to the view.  In the case of the keyboard, yes two views on android can request the keyboard and fight about it.  We're just exposing that reality through to dart.

**Comment by abarth** [comment]
I'm going to close this issue as wont-fix.  These objects are separate because they have different lifetimes.  We might want to change how we deal with multiple people trying to talk to the keyboard at once, but that's a different issue.
