### ISSUE TITLE
I want to only face unlock feature.

### ISSUE THREAD

**Issue by nbpatel94** [flutter/flutter#103252]
Hello,
hey, devs.!

In my application, I just want to add a face unlock feature to unlock my application. but as I used this package it will take both figure and face.

Like, If the user sets both Fingures and Face in security. it will automatically use Figure to unlock the device. But I want to use only face unlock functionality in my application. I tried my level best to set this. But couldn't find a solution for this.

**Comment by Chinmay-KB** [comment]
Which package are you using?

**Comment by darshankawar** [comment]
@nbpatel94 
Assuming you are talking about `local_auth`, your case seem to be similar to https://github.com/flutter/flutter/issues/45775, so please follow-up in it for further updates. 
Also, as a workaroud, you may ask this question on support channels like StackOverflow.
Closing this as a duplicate.
