### ISSUE TITLE
Firebase + Flutter codelab needs updated naming for FireStore Database

### ISSUE THREAD

**Issue by mnilsson23** [flutter/flutter#103315]
[In this codelab](https://firebase.google.com/codelabs/firebase-get-to-know-flutter?hl=en#2) it says to click on "Cloud Firestore" + shows a picture of that option.  However it looks like in the left nav bar of a Firebase project it's since been renamed to "Firestore Database".
![image](https://user-images.githubusercontent.com/16671874/167337445-0b14e8ca-c5b9-42f3-9a4c-f46529d891ec.png)

**Comment by domesticmouse** [comment]
This codelab has been updated. I believe this issue has been fixed in the update.
