### ISSUE TITLE
devicelab pre-submit test failed without link to logs

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#103369]
My PR is failing the pre-submit `Mac_ios hot_mode_dev_cycle_macos_target__benchmark`: https://github.com/flutter/flutter/pull/103220

However, it doesn't have a link to a build, and I couldn't find the right builder in the luci dashboard. I checked in both Flutter try builders and devicelab_staging, but couldn't find it.

How can I diagnose this failure, ideally with a link to the actual LUCI build.

**Comment by CaseyHillers** [comment]
I also saw this in https://github.com/flutter/flutter/pull/103374

**Comment by christopherfujino** [comment]
Got it twice in a row. Currently re-running again in https://github.com/flutter/flutter/pull/103220

**Comment by keyonghan** [comment]
The bot is offline: 

<img width="664" alt="Screen Shot 2022-05-09 at 4 09 10 PM" src="https://user-images.githubusercontent.com/54558023/167512957-09d11d92-6576-4867-bf68-692bd39ca8a8.png">

**Comment by keyonghan** [comment]
Bot is back.

**Comment by christopherfujino** [comment]
> Bot is back.

Thanks!
