### ISSUE TITLE
Flutter build dashboard filtering setting not working correctly

### ISSUE THREAD

**Issue by yusuf-goog** [flutter/flutter#103372]
On https://flutter-dashboard.appspot.com/#/build the filtering setting dialog doesn't seem to be working correctly. Especially with the "Staging" checkbox, whose default value is false (other options are true).

See the attached video for the disabled "Apply" button on the dialog when unselecting the "Staging" checkbox.

https://user-images.githubusercontent.com/91688203/167512268-6a08844a-8dc9-4046-99ef-5d422d997175.mp4

**Comment by yusuf-goog** [comment]
cc @codebird

**Comment by codebird** [comment]
Will look

**Comment by codebird** [comment]
@yusuf-goog this can be closed.

**Comment by yusuf-goog** [comment]
Looks like this is working as expected now. Thanks @codebird !
