### ISSUE TITLE
[ci.yaml] Add official dimension support

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#103361]
Currently, we hard code a list of properties that are intended as dimensions, such as `cpu`.

Instead, we should update ci.yaml to allow targets to explicitly pass `dimensions` and `platform_properties` to support it as well.

Most cases, platforms want to pass dimensions and not properties.

This would prevent the need to hard code the list in flutter/infra and flutter/cocoon, saving time when adding new dimensions.

**Comment by keyonghan** [comment]
This is fixed.

**Comment by CaseyHillers** [comment]
This was added, but none of the ci.yamls were migrated nor any of the functionality. @XilaiZhang @keyonghan are there any plans to use this?

**Comment by keyonghan** [comment]
> This was added, but none of the ci.yamls were migrated nor any of the functionality. @XilaiZhang @keyonghan are there any plans to use this?

Oh, I see. Not a high priority though.

**Comment by godofredoc** [comment]
Closing as duplicate of https://github.com/flutter/flutter/issues/113732
