### ISSUE TITLE
[flutter_tools] package:material_color_utilities pinned at 0.1.4 because of breaking changes

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#103357]
There were test failures on the pub roll in https://github.com/flutter/flutter/pull/103220.

```
00:36 +634 -1: /b/s/w/ir/x/w/flutter/packages/flutter/test/material/theme_data_test.dart: ThemeData can generate a dark colorScheme from colorSchemeSeed [E]                                           
  Expected: Color:<Color(0xff9ccaff)>
    Actual: Color:<Color(0xff9ecaff)>
  
  package:test_api                                    expect
  package:flutter_test/src/widget_tester.dart 455:16  expect
  test/material/theme_data_test.dart 249:5            main.<fn>
```

https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8814886108995385025/+/u/run_test.dart_for_framework_tests_shard_and_subshard_libraries/test_stdout

**Comment by christopherfujino** [comment]
Pinned this in 0.1.4 to unblock pub roll in https://github.com/flutter/flutter/pull/103220

cc @guidezpl & @pennzht

If we don't control when this will break upstream, we can always leave this package pinned in https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/commands/update_packages.dart#L29 and merely periodically update the pin

**Comment by christopherfujino** [comment]
Also cc @darrenaustin about pinning this in https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/commands/update_packages.dart#L29

**Comment by christopherfujino** [comment]
Also cc @HansMuller, do you know if this will affect goldens for the internal roll?

**Comment by HansMuller** [comment]
@darrenaustin should be able to answer

**Comment by darrenaustin** [comment]
As I mentioned in chat, keeping it at 0.1.4 shouldn't break any goldens, as they were originally taken with that dependency (and are probably not effected one way or the other because they are not using the color scheme generation feature).

I would prefer to have this a pinned dependency that we manually manage so that we can handle any breaking change from it.

**Comment by pennzht** [comment]
@christopherfujino 

Hi Christopher,

This is expected and normal.

A recent change to `material_color_utilities` (https://github.com/material-foundation/material-color-utilities/commit/b9033934ea64b2fabfb7f08eab6452ee291e6ddf) updated the solver to the HCT equation, causing many tests to break, as the old and new solvers generate slightly different (often negligible) colors.

My suggestion is to use the newest `material_color_utilities` and update the tests accordingly.

**Comment by darrenaustin** [comment]
We will leave this dependency pinned so as not to have breakage with automatic updates. When we need to update this dependency we will do so manually as we did with #104771.

**Comment by christopherfujino** [comment]
> We will leave this dependency pinned so as not to have breakage with automatic updates. When we need to update this dependency we will do so manually as we did with #104771.

SGTM, thanks!
