### ISSUE TITLE
[Web] flutter web "Row"  

### ISSUE THREAD

**Issue by LailaiMaster** [flutter/flutter#103398]
[✓] Flutter (Channel stable, 2.2.3, on macOS 12.1 21C52 darwin-arm, locale
    zh-Hans-CN)
    • Flutter version 2.2.3 at /Users/lijian/work/flutter2.3/flutter
    • Framework revision f4abaa0735 (10 months ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/lijian/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • ANDROID_HOME = /Users/lijian/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.1, Build version 13A1030d
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.67.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • iPhone 13 (mobile) • 2ABEE3D3-15D8-4BAC-AE42-0BCB2F59B815 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • Chrome (web)       • chrome                               • web-javascript
      • Google Chrome 101.0.4951.54
<img width="68" alt="image" src="https://user-images.githubusercontent.com/19606597/167591137-25dc0643-da02-48d3-bd3e-058c0996b3ce.png">
<img width="587" alt="image" src="https://user-images.githubusercontent.com/19606597/167591183-4d461d77-5ffe-4096-914d-3c0b932d9642.png">

**Comment by LailaiMaster** [comment]
How to align img and text in Row?

**Comment by LailaiMaster** [comment]
Text add this  strutStyle: StrutStyle(height: 1) is right

**Comment by darshankawar** [comment]
Please ask support questions on StackOverflow.
Closing from here.
