### ISSUE TITLE
Add Multiple Info Window

### ISSUE THREAD

**Issue by shivamagarwal2097** [flutter/flutter#103319]
Can you add feature to show multiple info window on google map

**Comment by darshankawar** [comment]
@shivamagarwal2097 
Adding multiple info window to maps is against the best practices. See below:

<img width="938" alt="Screenshot 2022-05-09 at 3 41 04 PM" src="https://user-images.githubusercontent.com/67046386/167389291-453e50ee-c3fa-49a5-a999-a3bfcfaa9804.png">

You can read more about it here https://developers.google.com/maps/documentation/javascript/infowindows?hl=pt-br#add

Closing this issue, as the proposal isn't a valid one.
