### ISSUE TITLE
[plugins] `dart analyze` fails in `local_auth`

### ISSUE THREAD

**Issue by asashour** [flutter/flutter#103389]
As shown [here](https://github.com/flutter/plugins/runs/6357861403), it seems that `local_auth/local_auth` has analyzer issues.

Running locally gives the below error.

A PR was raised.

```
Analyzing local_auth...

   info • example\lib\readme_excerpts.dart:30:7 • Use key in widget
          constructors. • use_key_in_widget_constructors           
                                                                   
1 issue found.
```

**Comment by ditman** [comment]
The problematic code was reverted (https://github.com/flutter/plugins/pull/5691) and then relanded (https://github.com/flutter/plugins/pull/5692). `flutter/main` has recovered and is accepting changes normally.

Thanks for the report!
