### ISSUE TITLE
Default icons on Mac do not follow Apple HIG

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#103371]
It's not a big deal, but our defaults are wrong.

<img width="226" alt="image" src="https://user-images.githubusercontent.com/11857803/167508920-7d946b84-4dab-4d7c-a4ed-699fc5fb7656.png">

Icons:
https://github.com/flutter/flutter/tree/master/packages/flutter_tools/templates/app_shared/macos.tmpl/Runner/Assets.xcassets/AppIcon.appiconset

Should be smaller with rounded corners:
https://developer.apple.com/design/human-interface-guidelines/macos/icons-and-images/app-icon/

**Comment by darshankawar** [comment]
Thanks for the report @eseidelGoogle . It does look a bit bigger than other icons:

<img width="309" alt="Screenshot 2022-05-10 at 1 24 43 PM" src="https://user-images.githubusercontent.com/67046386/167578059-5c6a86c6-6569-4508-b65c-d430e53e117d.png">

<details>
<summary> stable, master flutter doctor -v </summary>

```

[✓] Flutter (Channel stable, 2.10.5, on macOS 12.2.1 21D62 darwin-x64, locale
    en-GB)
    • Flutter version 2.10.5 at /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (12 hours ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

[✓] Flutter (Channel master, 2.13.0-0.0.pre.1006, on macOS 12.2.1 21D62
    darwin-x64, locale en-GB)
    • Flutter version 2.13.0-0.0.pre.1006 at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f86dfdd2b7 (69 minutes ago), 2022-05-10 10:24:08 +0530
    • Engine revision 8774c24f65
    • Dart version 2.18.0 (build 2.18.0-99.0.dev)
    • DevTools version 2.13.1
    
[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.




```

</details>

**Comment by cbracken** [comment]
@HansMuller do we have a set of master icons we can regenerate the new ones from? I recall these existed at one point (when I did the iOS icons years ago) but haven't touched them in a while.

**Comment by HansMuller** [comment]
@cbracken - I'm afraid I'm not an icon master. We should definitely generate icons that match the conventional sizes per platform.

**Comment by cbracken** [comment]
Ah sorry to be clear @HansMuller I mean large-sized master assets of the Flutter logo that I can use to generate the macOS icons,

**Comment by cbracken** [comment]
When you bank on a quick, lazy patch to finish off the week on a Friday afternoon, sometimes it pays to check the date on your calendar. Fully embracing the spirit of Friday the 13th, the following have landed and/or been filed:
* https://github.com/flutter/packages/pull/1930
* Wrote [Managing template image assets](https://github.com/flutter/flutter/wiki/Managing-template-image-assets) wiki so the next person doesn't hit all the snags I hit
* https://github.com/flutter/flutter/pull/103787
* https://github.com/flutter/flutter/pull/103771
* https://github.com/flutter/flutter/pull/103739

And in the spirit of embracing the yak shave:
* Filed https://github.com/flutter/flutter/issues/103830 I attempted to fix this, but eventually had to work around this since it requires a roll of package:coverage to Google
  * Which was due to https://github.com/dart-lang/coverage/pull/370
    * Which was due to https://github.com/dart-lang/sdk/issues/48272
* https://github.com/flutter/flutter/pull/103785
* https://github.com/flutter/flutter/pull/103776

All that said... we now have shiny new icons!
