### ISSUE TITLE
The argument type 'List<dynamic>' can't be assigned to the parameter type 'Iterable<AuthMessages>'.

### ISSUE THREAD

**Issue by EliasFazel10296** [flutter/flutter#103346]
The argument type 'List<dynamic>' can't be assigned to the parameter type 'Iterable<AuthMessages>'.

On Version 2.0.1

**Comment by stuartmorgan** [comment]
For help with your own code, try one of the resources listed at https://flutter.dev/community#community-grid

Closing as this is not an issue in Flutter itself, which is what we track here.
