### ISSUE TITLE
invokeMethod arguments confusing (needs better documentation)

### ISSUE THREAD

**Issue by FaisalAbid** [flutter/flutter#10336]
Currently invokeMethod has the signature
```Future<dynamic> invokeMethod(String method, [dynamic arguments]) async {```

Which is great, however on Android its not clear how to fetch the arguments. You can either call getArguments() on MethodCall (in Android) which I assume returns the array of arguments, or there is also a method called getArgument(key). Investigation into the java source for getArguments(key) reveals that it does something like
```java
   public <T> T argument(String key) {
        if(this.arguments == null) {
            return null;
        } else if(this.arguments instanceof Map) {
            return ((Map)this.arguments).get(key);
        } else if(this.arguments instanceof JSONObject) {
            return ((JSONObject)this.arguments).opt(key);
        } else {
            throw new ClassCastException();
        }
    }
```

This basically means if I pass in a Map into invokeMethod I can fetch the key and values.

This is great but it's not documented anywhere as far as I can tell.

**Comment by Hixie** [comment]
cc @mravn-google

**Comment by mravn-google** [comment]
The Android side is documented [here](https://docs.flutter.io/javadoc/). The `MethodChannel` can be used with any `MethodCodec`, which is really the right place for documenting which argument values are accepted, or what they translate into on the target platform. I'll add a link to the standard codec.
