### ISSUE TITLE
image_picker Error (Xcode): Framework not found image_picker

### ISSUE THREAD

**Issue by mehdidavar** [flutter/flutter#103340]
i have error in build ipa in xcode 
i remove all pods and install but have problem
flutter doctor
[✓] Flutter (Channel stable, 2.10.5, on macOS 12.3.1 21E258 darwin-x64, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google
    Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Android Studio (version 2021.1)
[!] Connected device
    ! No devices available
[✓] HTTP Host Availability

**Comment by darshankawar** [comment]
@mehdidavar 
Can you provide `flutter run -v` and `ios/podfile` ?
The verbose log will be huge so you can put that in a text file and share it here.
