### ISSUE TITLE
master branch for windows system clip board unavailable，Affect the clip board of the system

### ISSUE THREAD

**Issue by albertPu** [flutter/flutter#103337]

**Comment by albertPu** [comment]
![image](https://user-images.githubusercontent.com/42194697/167401130-b77e6136-8b07-4a5d-806b-32428a92690e.png)

**Comment by stuartmorgan** [comment]
Duplicate of https://github.com/flutter/flutter/issues/103205

In the future, please poste text instead of taking pictures of it.
