### ISSUE TITLE
No devices found with name or id matching 'B6018B57-5091-434D-976A-C63D816E10E3'

### ISSUE THREAD

**Issue by kavyabhargava** [flutter/flutter#103309]
I am not able to run my flutter app on any of my emulators or iOS simulators. I am getting this error when I ran my project. The emulators are working fine and are opening and I am able to see them.
My device is M1pro MacBook

**The same app is running fine on my old windows laptop and giving no errors at all.**

```
Flutter doctor -v:
[✓] Flutter (Channel stable, 2.10.5, on macOS 12.2.1 21D62 darwin-arm, locale en-IN)
    • Flutter version 2.10.5 at /Users/kavyabhargava/FlutterDev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (3 weeks ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/kavyabhargava/Library/Android/sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] VS Code (version 1.67.0)
    • VS Code at /Users/kavyabhargava/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Connected device (2 available)
    • iPhone 12 mini (mobile) • B6018B57-5091-434D-976A-C63D816E10E3 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-4 (simulator)
    • Chrome (web)            • chrome                               • web-javascript • Google Chrome 101.0.4951.54

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

**Comment by darshankawar** [comment]
@kavyabhargava 
If you run `flutter devices`, do they show up ? Also, if you run `adb devices` do they show up ?
When you run `flutter run`, does the tool show those devices you can select from ?
Do these devices show up in the IDE to select from ?

If not, can you run `flutter devices -v` and see if it shows any error or unusual log ?

It seems to me that there's some config changes occured with your setup that might have led to this behavior ? Did you by any chance delete any exe or any related file recently ?

**Comment by kavyabhargava** [comment]
Answered your questions, please see the text in **bold**


If you run flutter devices, do they show up ?  **Yes they show up**


 Also, if you run adb devices do they show up ? **Yes they show up too**

When you run flutter run, does the tool show those devices you can select from ? **Yes using visual studio code, in the bottom right it is showing the device name**

Do these devices show up in the IDE to select from ? **yes same answer as above**

If not, can you run flutter devices -v and see if it shows any error or unusual log ? **I am not able to find the android devices in the list. No mention of them, list contains various IOS devices.(Maybe because I am using Mac)**

It seems to me that there's some config changes occured with your setup that might have led to this behavior ? Did you by any chance delete any exe or any related file recently ? **No, I did not. I just cloned the exact repository from GitHub**

**Comment by darshankawar** [comment]
Check below similar SO links and solutions and see if they help your case.

https://stackoverflow.com/questions/67936372/flutter-doctor-is-ok-but-this-no-devices-found-with-name-or-id-matching-emula

https://stackoverflow.com/questions/67043693/no-devices-found-with-name-or-id-matching-emulator-5554

**Comment by kavyabhargava** [comment]
Thanks, This has solved the android one but still getting issue for the iOS emulators. I app is not running on it. **The screen is completely white** 

None of the my app screen or anything is opening on iOS simulator.

**Comment by darshankawar** [comment]
Can you run `flutter run -v` on same simulator and check if you get any errors in the console when white screen shows up ?

**Comment by kavyabhargava** [comment]
I am not seeing any issue.It is stopping after "The Flutter DevTools debugger and profiler on iPhone 13 is available at: Link"
I clicked the link, that is also blank. That run has just stopped and I have tried different emulators and waited but it is not proceeding

**Comment by darshankawar** [comment]
Please share the console log.
