### ISSUE TITLE
Mac iOS Engine Release fails to be scheduled on release branches

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#103365]
This isn't urgent as I can rerun the build, and it will run as normal.

See https://flutter-dashboard.appspot.com/#/build?repo=engine&branch=flutter-2.13-candidate.0

Failing: https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20iOS%20Engine%20Release/13829/overview

Normal: https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20iOS%20Engine%20Release/13830/overview

The issue seems to be that it's trying to use the staging account against prod. There might be a ci.yaml mismatch between these two builders (where possibly the release has this builder set to bringup: true).

**Comment by keyonghan** [comment]
The builder in the PR was with `bringup: false` (see [properties](https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20iOS%20Engine%20Release/13829/overview)).
Is this still happening?

**Comment by CaseyHillers** [comment]
This happened again. https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20iOS%20Engine%20Release/14290/overview was used but it wasn't the correct commit (expected https://github.com/flutter/engine/commit/f15f824b57476e369b5e656f53d4c431c5b04b9a)

**Comment by keyonghan** [comment]
This is same as https://github.com/flutter/flutter/issues/102998
```
2022-06-02 15:37:15.526 PDT
{"commit_key":"flutter/engine/flutter-2.13-candidate.0/f15f824b57476e369b5e656f53d4c431c5b04b9a","task_key":"5502721571291136"}
2022-06-02 15:37:15.526 PDT
Updating buildId=8812429606148369057 for result=null
```
Task key (`Mac iOS Engine Release`) was linked to buildId (`8812429606148369057`, which is `Mac iOS Engine Profile`.

**Comment by CaseyHillers** [comment]
I'm not sure this is the same. The issue is Mac iOS Engine Release was never scheduled in the first place. I'm not sure if that's because it was skipped in scheduling due to this though.

**Comment by keyonghan** [comment]
> I'm not sure this is the same. The issue is Mac iOS Engine Release was never scheduled in the first place. I'm not sure if that's because it was skipped in scheduling due to this though.

If you take a look at other builders (green ones), they are not pointing to the correct builds either.
