### ISSUE TITLE
is there is a way to connect python decision tree model with flutter !?

### ISSUE THREAD

**Issue by MFrankestien** [flutter/flutter#103310]
Hello everyone my graduation project based on flutter app that suppose to connect with python decision tree 
i created each part alone but i don't understand how to migrate them ?

Can anyone help me how can connect decision tree model that created by python to flutter app !?

**Comment by stuartmorgan** [comment]
For help with your own code, try one of the resources listed at https://flutter.dev/community#community-grid

Closing as this is not an issue in Flutter itself, which is what we track here.
