### ISSUE TITLE
Flutter web - wrong icon rendering

### ISSUE THREAD

**Issue by payam-zahedi** [flutter/flutter#103302]
We have custom icon font in our app. We will use `[fontify](https://pub.dev/packages/fontify)` to generate `otf` file base on our SVG image files. The problem is when we add new SVG icons and generate new `otf` file, the web version of our app shows unrelated icons.

**Note:** when we are changing the icon items during the running app on the mobile platforms, We see the same problem in android and IOS. Hot reload and hot restart won't fix the problem.
But when we stop the program and run it again, the problem will be solved.

**Current Solution:** clearing cache of the browser would fix the problem, but this is not a proper way for end users. 

## Steps to Reproduce

1.  Run the project
2.  add new SVG file
3.  generate font icon

**Expected results:** 
![Screenshot_1652021025](https://user-images.githubusercontent.com/47558577/167302013-4290b0f0-5a03-4dbf-9f77-e717893d2a62.png)

**Actual results:** 
![Screenshot_1652021559](https://user-images.githubusercontent.com/47558577/167302016-6ecc1c84-5719-4873-8784-0fb15ad8cfb6.png)

<details>
  <summary>Flutter Doctor</summary>

```
 flutter doctor -v
[√] Flutter (Channel stable, 2.10.4, on Microsoft Windows [Version 10.0.18363.1977], locale en-US)
    • Flutter version 2.10.4 at D:\dev\sdk\flutter-sdk\fvm\default
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (6 weeks ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2   
    • DevTools version 2.9.2

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at D:\dev\sdk\android-sdk-essential
    • Platform android-31, build-tools 30.0.2
    • Java binary at: D:\dev\ide\androidstudio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Chrome - develop for the web
    • CHROME_EXECUTABLE = C:\excutable\CHROME_EXECUTABLE.bat

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2020.3)
    • Android Studio at D:\dev\ide\androidstudio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.66.2)
    • VS Code at C:\Users\Payam\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.40.0

[√] Connected device (4 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 7.1.1 (API 25) (emulator)
    • Windows (desktop)                  • windows       • windows-x64    • Microsoft Windows [Version 10.0.18363.1977]
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 100.0.4896.127
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 96.0.1054.57

[√] HTTP Host Availability
    • All required HTTP hosts are available

```

</details>

**Comment by payam-zahedi** [comment]
@guidezpl can you help me in this?

**Comment by guidezpl** [comment]
Can you provide more info about the caching? What does Chrome devtools say, how is the icon font included in the web build, etc.?

There are probably multiple solutions to this which are essentially to disable caching at some level. I think the easiest workaround might be to change the name of the file when it changes.

**Comment by payam-zahedi** [comment]
`Can you provide more info about the caching? `
I don't have any info about cache mechanism of the flutter in web platform. 
`how is the icon font included in the web build, etc.?`
we're using the font.otf file, and we will add it to pubspec.yaml. like below:
```

flutter:
  uses-material-design: true

  fonts:
    - family: IconsFont
      fonts: 
        - asset: lib/src/assets/fonts/icons_font.otf     
...
```

`I think the easiest workaround might be to change the name of the file when it changes.`
I did not understand which file you are referring to? But if you mean is the `icons_font.otf` file, I must mention that we can not change the file name and also update the `pubspec.yaml` file every time that we have a release.

**Comment by payam-zahedi** [comment]
I think we can fix this issue with removing the related cache in the browser every time that we have an update.
But I do not know exactly which cookie or cache should be deleted.

**Comment by guidezpl** [comment]
I'm wondering what it looks like on the client side. Devtools has answers about things like TTL
<img width="994" alt="Screen Shot 2022-05-16 at 13 35 35" src="https://user-images.githubusercontent.com/6655696/168584188-0a4847cc-758c-4bf2-87a0-7a5a5e2c5668.png">

<img width="509" alt="Screen Shot 2022-05-16 at 13 38 14" src="https://user-images.githubusercontent.com/6655696/168584597-51c5cb20-8f82-4d64-91e4-209b698302c4.png">


> we're using the font.otf file, and we will add it to pubspec.yaml. like below:

If you updated the font file every release, it would prevent it from being cache, which would workaround this issue. 
 
> I think we can fix this issue with removing the related cache in the browser every time that we have an update. But I do not know exactly which cookie or cache should be deleted.

This is where having more info about client-side caching would be helpful
