### ISSUE TITLE
Fix doctor message about missing lib32stdc++6

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#10335]
## Steps to Reproduce

On a clean Ubuntu 16.04 install follow Flutter setup guide then run `flutter doctor`. Observe message:

```
Downloaded executables cannot execute on host (see https://github.com/flutter/flutter/issues/6207 for more information)
```

This message is not useful. #6207 is closed by #8798, which in turn simply points back to the closed issue. The issue thread does not give you a straight solution, but rather to a stream of comments one of which happens to be a solution. There does not seem to be an open issue to fix this permanently any time soon. We should either include the `lib32stdc++6` setup step in the setup guide, or have the error message point to a special page that offers a solution more directly.

This is happening as of https://github.com/flutter/flutter/commit/f68c6fb814bd93e2061fb7ad595e275490fb999e

**Comment by iapicca** [comment]
Hi @yjbanov  is this issue still relevant?

**Comment by yjbanov** [comment]
Nope. Thanks for catching! Closing.
