### ISSUE TITLE
[Web][Documentation]: update index.html file to dynamically change the Favicon based on current system theme mode.

### ISSUE THREAD

**Issue by amorenew** [flutter/flutter#103322]
## Use case

I want to change the favicon according to system dark mode on Flutter web

## Proposal

When creating a new Flutter web project I suggest adding the following the index.html file to dynamiclly  change the Favicon based on current system theme mode:
```
    <!-- Favicon -->
    <link href="favicon-light.png" rel="shortcut icon" type="image/png" media="(prefers-color-scheme: light)" />
    <link href="favicon-dark.png" rel="shortcut icon" type="image/png" media="(prefers-color-scheme: dark)" />

```
Script in the body tag

```
    <script>
        // select the favicon 👉
        const faviconEl = document.querySelector('link[rel="shortcut icon"]')

        // watch for changes 🕵️
        const mediaQuery = window.matchMedia('(prefers-color-scheme: dark)')
        mediaQuery.addEventListener('change', themeChange)

        // listener 👂
        function themeChange(event) {
            if (event.matches) {
                faviconEl.setAttribute('href', 'favicon-dark.png')
            } else {
                faviconEl.setAttribute('href', 'favicon-light.png')
            }
        }

    </script>

```

Github icon sample:

<img width="244" alt="Screen Shot 2022-05-09 at 7 28 10 AM" src="https://user-images.githubusercontent.com/2842459/167346016-848beed3-abdb-42cc-a2e8-e447c8f043f9.png">
<img width="244" alt="Screen Shot 2022-05-09 at 7 28 22 AM" src="https://user-images.githubusercontent.com/2842459/167346040-0e980e77-0512-4a14-968e-63a238443371.png">

I think it is a simple change so new users doesn't have to search for that trick as dark mode theme is a required UX

**Comment by navaronbracke** [comment]
It would be sufficient to add this to the documentation for Flutter Web? Not every web app uses a dark mode, so including it in the template adds extra boilerplate that users might need to remove if they don't support dark mode. Not to mention the extra asset that is required to be included in the template.

**Comment by amorenew** [comment]
@navaronbracke good suggesstion, adding it to documentation makes sense

**Comment by darshankawar** [comment]
Considering this as a documentation request and updating title accordingly.

**Comment by yjbanov** [comment]
I think the best way to document this is to file a question on StackOverflow and answer it. Developers are used to finding answers like this by searching, and SO is frequently easily found.

**Comment by ditman** [comment]
This seems to be fairly well documented here (same code as OP's, unattributed?): https://joyofcode.xyz/dark-mode-favicon

Also, I don't think you need *both* the `media` and the JavaScript in your index, do you?

**Comment by amorenew** [comment]
Most Flutter web developers are from mobile development background that's why they wouldn't know that feature is even exist so they wouldn't ask on stackoverflow.
