### ISSUE TITLE
Error being displayed on flutter build dashboard

### ISSUE THREAD

**Issue by yusuf-goog** [flutter/flutter#103367]
On https://flutter-dashboard.appspot.com/#/build see the error in the bottom of the pic:

![image](https://user-images.githubusercontent.com/91688203/167505542-b3bdef1a-1c92-43c7-8048-78d0e9665723.png)

It disappears after a few seconds.

**Comment by keyonghan** [comment]
Dup of [flutter-devicelab-mac-1.mtv.corp.google.co](https://github.com/flutter/flutter/issues/103362)
