### ISSUE TITLE
Bump targetSdkVersion to 33 (Android T)

### ISSUE THREAD

**Issue by blasten** [flutter/flutter#103356]
With Android T coming up https://developer.android.com/about/versions/13,
Flutter tool should bump the `targetSdkVersion` to `33`, which can be done by changing a single value in the Flutter SDK:
https://github.com/flutter/flutter/blob/4c573207acc373fbb88cc98feb15678d0acdabcb/packages/flutter_tools/gradle/flutter.gradle#L39

https://developer.android.com/reference/android/os/Build.VERSION_CODES#TIRAMISU

**Comment by bernaferrari** [comment]
Can you do this now? In the previous years I think you needed to wait for platform stability before being able to submit apps to play store with the new targetSDK

**Comment by bartekpacia** [comment]
I'm pretty sure that you can't reference Android 13 Tiramisu with just `33` in `targetSdkVersion/compileSdkVersion`. 

[You have to use `Tiramisu` or `android-Tiramisu`, depending on your AGP version](https://developer.android.com/about/versions/13/setup-sdk#build-config-new-agp).

**Comment by GaryQian** [comment]
cc @GaryQian (for personal reference)

**Comment by SynSzakala** [comment]
@bartekpacia Since Android 13 reached platform stability, it seems that bumping to API level 33 should be now possible.

**Comment by marcellocamara** [comment]
I think there's something wrong, because when I updated the compileSdkVersion and the targetSdkVersion into 33 - of an existing functional app, the app does not launch into the emulator. An a curious fact is that the app launches correctly if I build it in the native code (android folder).

There's some warnings/errors that I saw on the logs after `flutter run -v`:

```dart
[+17196 ms] WARNING:We recommend using a newer Android Gradle plugin to use compileSdk = 33
[        ] This Android Gradle plugin (7.1.2) was tested up to compileSdk = 32
[        ] This warning can be suppressed by adding
[        ]     android.suppressUnsupportedCompileSdk=33
[        ] to this project's gradle.properties
[        ] The build will continue, but you are strongly encouraged to update your project to
[        ] use a newer Android Gradle Plugin that has been tested with compileSdk = 33
```


Error that does not open the app:
Note that I can open the app - manually - my self, and the logs continues. But, why it does not opening alone ?

```kotlin
[  +81 ms] --------- beginning of system
           07-16 12:48:55.979 D/CompatibilityChangeReporter(  589): Compat change id reported: 168419799; UID 10065; state: DISABLED
[  +12 ms] executing: /Users/cello/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell am start -a android.intent.action.RUN -f 0x20000000 --ez enable-dart-profiling
true --ez enable-checked-mode true --ez verify-entry-points true marcello.dev.my_app/marcello.dev.my_app.MainActivity
[ +264 ms] Starting: Intent { act=android.intent.action.RUN flg=0x20000000 cmp=marcello.dev.my_app/.MainActivity (has extras) }

                    Error type 3
                    Error: Activity class {marcello.dev.my_app/marcello.dev.my_app.MainActivity} does not exist.
[        ] Waiting for observatory port to be available...
```

**Comment by marcellocamara** [comment]
This problem, related above by me, is also present in `Flutter 3.0.5,` with `Dart 2.17.6`.

And, the good news, is that it's **not reproducible** on the flutter beta version 3.3.0, with dart 2.18.

It works pretty well on this environment:
```
environment:
  sdk: ">=2.18.0-271.2.beta <3.0.0"
  flutter: "3.3.0-0.0.pre"
```

**Comment by christopherfujino** [comment]
> This problem, related above by me, is also present in `Flutter 3.0.5`, with `Dart 2.17.6`.
> 
> And, the good news, is that it's **not reproducible** on the flutter beta version 3.3.0, with dart 2.18.
> 
> It works pretty well on this environment:
> 
> ```
> environment:
>   sdk: ">=2.18.0-271.2.beta <3.0.0"
>   flutter: "3.3.0-0.0.pre"
> ```
> 
> works = starts the app correctly, by itself, in the emulator

@GaryQian given this, is this fixed upstream?

**Comment by GaryQian** [comment]
Ill have to try it to see if it fixed. If so, we can bump the target version.

**Comment by Jasguerrero** [comment]
@GaryQian Was this fixed upstream?

**Comment by christopherfujino** [comment]
@GaryQian do we need to act on this?

**Comment by christopherfujino** [comment]
@stuartmorgan do you know if we need to act on this? It seems like this isn't high priority (given that Android T has been out for months).

**Comment by bernaferrari** [comment]
This will only be *necessary* when play store forces apps to have this (will take 12 months).

Until then, there is no difference if you do this today or next week, unless packages start using the newer sdk.

**Comment by GaryQian** [comment]
https://github.com/flutter/flutter/pull/112936 updates the target and compileSdkVersion to 33.

**Comment by christopherfujino** [comment]
Re-opening as https://github.com/flutter/flutter/pull/112936 was reverted in https://github.com/flutter/flutter/pull/113064

**Comment by christopherfujino** [comment]
@GaryQian can you take a look at relanding https://github.com/flutter/flutter/pull/112936 ?

**Comment by christopherfujino** [comment]
FYI @reidbaker

**Comment by JimmyTai** [comment]
@christopherfujino 
@GaryQian 
Google play required targetSdkVersion 33 now. Should Flutter also need to upgrade to 33 also compileSdkVersion?

**Comment by GaryQian** [comment]
https://github.com/flutter/flutter/pull/116146 Relands https://github.com/flutter/flutter/pull/112936 after a needed gradle bump

**Comment by christopherfujino** [comment]
@GaryQian is this now resolved after merging https://github.com/flutter/flutter/pull/116146?

**Comment by GaryQian** [comment]
Yes! This is resolved now.
