### ISSUE TITLE
[cocoon] Branch logic is including forks

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#103363]
https://pantheon.corp.google.com/datastore/entities;kind=Branch;ns=__$DEFAULT$__/edit;key=0%2F%257C6%2FBranch%257C35%2Fname%253Agodofredoc%2Fcocoon%2Ffilter_forks?project=flutter-dashboard

You can see here it's pulling forks, which isn't expected. It should only pull the supported list.

As a side note, I see this is only from godofredoc's repo, so they might have flutter-dashboard installed against their fork.

**Comment by amanv8060** [comment]
@CaseyHillers this should be closed?

**Comment by CaseyHillers** [comment]
@XilaiZhang is this fixed?

**Comment by XilaiZhang** [comment]
Oh forks have been fixed long long time ago :)
