### ISSUE TITLE
Cupertino needs an icon font solution too

### ISSUE THREAD

**Issue by xster** [flutter/flutter#10334]
We'd want to have batteries included for Cupertino. Especially for default widgets that will have icons in it like back button chevrons in #7508. 

There's a bunch of decent MIT fonts out there already like http://ionicons.com. The .ttf is <200kB. 

Might be worth having an official bundling

**Comment by xster** [comment]
@Hixie any concerns on licensing related stuff?

**Comment by Hixie** [comment]
Always. :-) Remind me tomorrow and we'll look at it together.

**Comment by xster** [comment]
We'll create a separate package that only has the icon assets. Let the default create template include the package.

**Comment by Hixie** [comment]
We should probably refactor how we do the material font to match at the same time.

cc @abarth who may have opinions on making every flutter app by default depend on two additional packages.

**Comment by xster** [comment]
Font's at https://pub.dartlang.org/packages/cupertino_icons but I still need #12160 to aggregate dependent packages' fonts into the app

**Comment by abarth** [comment]
95.4 KB and a leaf package.  Seems like the right trade-off.
