### ISSUE TITLE
Debugger just does not work

### ISSUE THREAD

**Issue by Wissperwind** [flutter/flutter#103397]
Hi,

I try to debug my code. But the execution just does not stop.
This happens only in complex real world applications. Please excuse that I can not send a 100 line code example because it just does not occour in tiny examples.
The red break points were changed to gray stop signs when the executions runs over them.

![Unbenannt](https://user-images.githubusercontent.com/20759873/167584035-c5c2912f-b532-4763-b74d-8e3f91e97064.PNG)

```
PS C:\...> flutter doctor -v
[√] Flutter (Channel master, 2.13.0-0.0.pre.1008, on Microsoft Windows [Version 10.0.19043.1645], locale de-DE)
    • Flutter version 2.13.0-0.0.pre.1008 at C:\Users\akilian\Flutter SDK\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6428624c10 (38 minutes ago), 2022-05-10 03:49:05 -0400
    • Engine revision fcf0e806b3
    • Dart version 2.18.0 (build 2.18.0-99.0.dev)
    • DevTools version 2.13.1

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\akilian\AppData\Local\Android\sdk
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] VS Code (version 1.52.1)
    • VS Code at C:\Users\akilian\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19043.1645]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 101.0.4951.54
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 101.0.1210.32

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.
```

**Comment by Wissperwind** [comment]
I am using chrome (flutter web) to run the application.

**Comment by darshankawar** [comment]
@Wissperwind 
Does this only happen on web platform or on other platforms too ? (ex: mobile, desktop)
What IDE are you using ?
Does it give you any unusual log or any errors while you are debugging `complex` app ?

**Comment by Wissperwind** [comment]
Hi,
I'm using Android studio.
Mobile and desktop is not configured in this project. I tried Chorme and Edge, and got a similar behaivour.
I do not get errors anymore. In the past therer were some:
https://github.com/flutter/flutter/issues/94549
But those does not appear anymore.

**Comment by Wissperwind** [comment]
![Unbenannt](https://user-images.githubusercontent.com/20759873/167616359-6eefdec0-4c93-4c56-9575-8ac7b39d59d4.PNG)
Same code in the first line. In the small example the debugger can stop at the first line, in the complex full app example the debugger refuses to stop at any line.

**Comment by Wissperwind** [comment]
I'll check my imports in the complex app if there is an import that makes a difference...

**Comment by Wissperwind** [comment]
Well I understood the difference between the example above:
The IDE ran the left example es dart application -> and the breakpoint worked.
But the right application was executed with a flutter run configuration and the debugger does nor work.
So even If I run the simple example on the left as flutter appliction, I can not stop at a breakpoint.

So in conclusion: I can not stop at the simples application with flutter runconfig:
// import 'package:http/http.dart';
// import 'package:http/http.dart' as http;

```
void main() {
  print("test");

}
```
My breakpoint at the print is just rolled over.
I have Android studio 2021.2.1 with Dart Plugin 212.5744 and Flutter plugin 67.1.2

**Comment by Wissperwind** [comment]
If I run the same code just as Dart the debugger works.

**Comment by darshankawar** [comment]
Thanks for all updates. I tried above code snippet in AS running on latest master, added breakpoint at `print` statement, selected chrome as device and then started debugging. Selected `step into` from console log which printed the statement properly as below:

<img width="726" alt="Screenshot 2022-05-11 at 10 52 44 AM" src="https://user-images.githubusercontent.com/67046386/167775020-acdbdd3e-4770-4ebe-bdf3-97ab2a3e25ae.png">

Is that a correct interpretation of the issue or did I miss anything to replicate properly ?

**Comment by Wissperwind** [comment]
Yes, thats an example for my issue. In my case my debugger does not stop at the breakpoint at print. The red point turns into a grey stop sign. Does it work in your case?

**Comment by Wissperwind** [comment]
Ok, I tried something different. I created a new project and it works. The last tests were in my big project. In a test file or the standard file. The big project is without nullk safety and two years old.
What infomation is now interesting to solve the issue?

**Comment by Wissperwind** [comment]
The "old project" is
environment:
  sdk: ">=2.11.0 <3.0.0"

**Comment by darshankawar** [comment]
> Does it work in your case?

Yes, it doesn't turn grey for me. I think this issue should be reported in https://github.com/flutter/flutter-intellij/issues because I don't think this is related to framework. Please try that and if you get redirected here, we can take it forward from there.

**Comment by hootyjeremy** [comment]
![image](https://user-images.githubusercontent.com/68588318/170546701-3134c6a5-d02e-46dc-a00b-bcd95ab92405.png)

The same thing is happening with my breakpoints in Android Studio when I even create the default flutter counter app. When I debug flutter with emulator or physical device, the breakpoints turn into the gray "nope scope" and code does not stop. But when I open Flutter DevTools and set breakpoints there, they will stop and you can see stack info in AS and DevTools. Breakpoints also work when I run from VScode, if that is relevant at all.

Flutter doctor shows a perfect score. Just let me know if you need any other data from me.

**Comment by hootyjeremy** [comment]
> The "old project" is environment: sdk: ">=2.11.0 <3.0.0"

I don't know if you are still experiencing this problem but this solution in another issue solved my problem. My breakpoints were not hitting if the project's folder path had spaces in it somewhere. I had a folder called "Flutter Projects" that I changed to "Flutter_Projects" and the breakpoints started working in Android Studio and Intellij IDEA.

https://github.com/flutter/flutter-intellij/issues/6159#issuecomment-1132226934

**Comment by Bes79** [comment]
Same issue

**Comment by Bes79** [comment]
and in the Android Emulator

**Comment by darshankawar** [comment]
Please take a look at original issue tracker here: https://github.com/flutter/flutter-intellij/issues/6159 and follow-up in it for further updates.
