### ISSUE TITLE
[webview_flutter] the iOS keyboard disappear animation is strange (incorrect)

### ISSUE THREAD

**Issue by zengsq** [flutter/flutter#103400]
## Steps to Reproduce

1、checkout the source code of flutter plugins
https://github.com/flutter/plugins

2、open webview_flutter example in Android Studio
directory:  packages/webview_flutter/webview_flutter

3、modify the below line source, change the intialUrl parameter to "https://www.baidu.com"
        initialUrl: 'https://www.baidu.com',

4、run app in iOS simulator or real device (iOS 15.4)

the background of the iOS soft-keyboard is incorrect .

this issue also exist in google.com、bing.com or other websites, but the problem happens in baidu.com is easy to observe. 

[
<img width="462" alt="issue" src="https://user-images.githubusercontent.com/10862173/167595827-5682bc3b-fa20-4e22-9a30-f1d3a5d699af.png">
](url)

[

https://user-images.githubusercontent.com/10862173/167595889-b947b010-5d07-4734-832a-437361af2ef5.mp4

](url)

1. Execute `flutter run` on the code sample 
2. ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
 % flutter analyze
Analyzing example...                                                    
No issues found! (ran in 3.8s)

```

```
 % flutter doctor -v
[✓] Flutter (Channel beta, 2.13.0-0.4.pre, on macOS 12.3.1 21E258 darwin-x64, locale zh-Hans-CN)
    • Flutter version 2.13.0-0.4.pre at /Users/zsq89464/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 25caf1461b (5 days ago), 2022-05-05 14:23:09 -0700
    • Engine revision c5caf749fe
    • Dart version 2.17.0 (build 2.17.0-266.8.beta)
    • DevTools version 2.12.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/zsq89464/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/zsq89464/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.66.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.38.1

[✓] Connected device (2 available)
    • iPhone 11 Pro Max (mobile) • 8F0CECD2-B269-434C-90A7-07F0AF1478A9 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-4 (simulator)
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 101.0.4951.54

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
@zengsq 
Thanks for the report. I can't open baidu.com from here as it just doesn't load, so I tried with default url and didn't see the behavior you reported with it.


https://user-images.githubusercontent.com/67046386/167625095-a2a2f814-4407-4e80-8a3d-334a59a18cf4.mov


I verified this on latest stable (2.10.5).


Can you show a short video if it replicates using google.com at your end ?

**Comment by zengsq** [comment]
> @zengsq Thanks for the report. I can't open baidu.com from here as it just doesn't load, so I tried with default url and didn't see the behavior you reported with it.
> 
>  103400.mov 
> I verified this on latest stable (2.10.5).
> 
> Can you show a short video if it replicates using google.com at your end ?

I figure out the root cause, this is because when the keyboard appear, the Scraffold  widget will auto resize the size of the webview widget, and some web sites do not handle this scenario correctly (HTML&JS code), for example, the baidu.com.

I set the resizeToAvoidBottomInset parameter to false , and this issue is fix. 

Widget build(BuildContext context) {
    return Scaffold(
      resizeToAvoidBottomInset: false,
      backgroundColor: Colors.green,
      appBar: AppBar(
        title: const Text('Flutter WebView example'),
        // This drop down menu demonstrates that Flutter widgets can be shown over the web view.
        actions: <Widget>[
          NavigationControls(_controller.future),
          SampleMenu(_controller.future, widget.cookieManager),
        ],
      ),
      body: WebView(
        initialUrl: 'https://www.bing.com/',
        javascriptMode: JavascriptMode.unrestricted,`
`

**Comment by bigslider** [comment]
@darshankawar  i hav

https://user-images.githubusercontent.com/99177073/168414082-98d7988b-36ad-4c11-9887-d721ea48145d.mov

e the same error .  i write some code in flutter web.  here is my video .
note: my height size of my page is more than device height.

**Comment by bigslider** [comment]
i don't think so that  'resizeToAvoidBottomInset' value is false. I hope the user can have a friendly interaction when clicking on the input box.

**Comment by GJYGitHub** [comment]
我也遇见了同样的问题，我发现只用在页面高度尺寸大于设备高度并且resizeToAvoidBottomInset=true时，运行在ios上面会出现这种问题
