### ISSUE TITLE
Everything drawn in qemu is too big

### ISSUE THREAD

**Issue by jimbeveridge** [flutter/flutter#10342]
## Steps to Reproduce

Flutter apps running under Fuchsia under qemu appear with everything too big. The image below has been resized, but its original size was approximately 1024x800. The buttons are enormous. This is making development more difficult because qemu shows a very different result than the hardware.

![image](https://cloud.githubusercontent.com/assets/7953123/26499790/ae0d8772-41e8-11e7-947b-8ab40d2b83f2.png)

**Comment by eseidelGoogle** [comment]
This is presumably the bug:
https://github.com/flutter/engine/blob/master/content_handler/runtime_holder.cc#L555

**Comment by eseidelGoogle** [comment]
@abarth would know.

**Comment by jimbeveridge** [comment]
Thank you Eric. I updated that constant, recompiled, and it did exactly what I needed.

**Comment by tvolkert** [comment]
@jimbeveridge can this be closed now?

**Comment by abarth** [comment]
Yes, we can't draw in QEMU at all now.  :)
