### ISSUE TITLE
TextFormField (password/obscureText:true) shows suggestions on keyboard

### ISSUE THREAD

**Issue by slyon** [flutter/flutter#10341]
The keyboard on Samsung devices does not recognize flutter's password (obscureText: true) TextFields. The problem seems to be related to the samsung-keyboard, as it is working as expected on a Motorola device with google-keyboard/GBoard.

### How to reproduce:
* Open Flutter Gallery -> Text fields (on a Samsung device)
* Enter a password in one of the password fields at the bottom
* see the suggestions in the samsung-keyboard

```
$ flutter doctor
[✓] Flutter (on Linux, channel master)
    • Flutter at /home/lukas/emvolution/dev/flutter
    • Framework revision 40b67bb187 (vor 5 Tagen), 2017-05-21 16:57:31 -0700
    • Engine revision 5a7e862cbe
    • Tools Dart version 1.23.0-dev.11.11

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at /media/Daten/Android/Sdk
    • Platform android-25, build-tools 25.0.3
    • ANDROID_HOME = /media/Daten/Android/Sdk
    • Java binary at: /media/Daten/Android/android-studio/jre/bin/java
    • Java version: OpenJDK Runtime Environment (build 1.8.0_76-release-b03)

[✓] Android Studio (version 2.2)
    • Android Studio at /media/Daten/Android/android-studio
    • Gradle version 2.14.1
    • Java version: OpenJDK Runtime Environment (build 1.8.0_76-release-b03)

[✓] Android Studio (version unknown)
    • Android Studio at /home/lukas/android-studio
    • Gradle version 2.14.1
    • Java version: OpenJDK Runtime Environment (build 1.8.0_76-release-b03)

[✓] Connected devices
    • SM G900F • 118f97ca • android-arm • Android 6.0.1 (API 23)

```

**Comment by eseidelGoogle** [comment]
IIRC @abarth or @jason-simmons mentioned that we had a very incomplete implementation of Android's IME APIs.  Presumably that's what's missing here?

**Comment by eseidelGoogle** [comment]
Looks like this is the phone in question: https://www.amazon.com/Samsung-Galaxy-S5-Cellphone-International/dp/B00JFNDLRC

**Comment by jason-simmons** [comment]
obscureText currently maps to (InputType.TYPE_CLASS_TEXT | InputType.TYPE_TEXT_FLAG_NO_SUGGESTIONS)

We'd have to test this with the Samsung IME.  But possibly we need additional flags like TYPE_TEXT_VARIATION_PASSWORD?

**Comment by cbracken** [comment]
Fixed by flutter/engine#3731, rolled into the framework in #10467

**Comment by slyon** [comment]
I can confirm that it is fixed in my context, too!

Thanks @cbracken

**Comment by brilliant-ember** [comment]
I am using flutter 0.7.3, emulating with android Oreo API 28 and obscure text is not working

**Comment by brilliant-ember** [comment]
Correction, it didn't work because I had  this property: keyboardType:TextInputType.text 
once I removed it, the obstruction worked just fine.

**Comment by patelkrunal78** [comment]
First declare a bool variable passwordVisible.

Initiate passwordVisible to false in initState()

@override
  void initState() {
    passwordVisible = false;
  }
Following is the TextFormField widget :

TextFormField(
   keyboardType: TextInputType.text,
   controller: _userPasswordController,
   obscureText: passwordVisible,//This will obscure text dynamically
   decoration: InputDecoration(
       labelText: 'Password',
       hintText: 'Enter your password',
       // Here is key idea
       suffixIcon: IconButton(
            icon: Icon(
              // Based on passwordVisible state choose the icon
               passwordVisible
               ? Icons.visibility
               : Icons.visibility_off,
               color: Theme.of(context).primaryColorDark,
               ),
            onPressed: () {
               // Update the state i.e. toogle the state of passwordVisible variable
               setState(() {
                   passwordVisible = !passwordVisible;
               });
             },
            ),
          ),
        );
Hope this help someone!!!

https://icetutor.com/question/how-to-show-hide-password-in-textformfield

**Comment by milanpatel18** [comment]
First declare a bool variable passwordVisible.

Initiate passwordVisible to false in initState()

Find full code at https://icetutor.com/question/how-to-show-hide-password-in-textformfield/
