### ISSUE TITLE
Safe area not working in Android 9 and 10 when app is in full screen mode

### ISSUE THREAD

**Issue by venkatjg** [flutter/flutter#103418]
## Steps to Reproduce

1. create flutter counter app
2. open `android/app/src/main/res/values/style.xml `  and add  below piece of code under `NormalTheme` section
    
    `<item name="android:windowLayoutInDisplayCutoutMode">shortEdges</item>`

3. open main.dart and add below piece of code
           
```dart
void main() {
  WidgetsFlutterBinding.ensureInitialized(); 
  SystemChrome.setEnabledSystemUIMode(SystemUiMode.immersiveSticky);
  runApp(const MyApp());
}
```
4. create android 9,10,11 emulators and set display cutout option as Tall cutout in all emulators 

![Screenshot 2022-05-10 at 7 16 12 PM](https://user-images.githubusercontent.com/100214707/167643736-fe7d3a20-16d3-4d49-9214-45d199367f22.png)

5. Run app in all devices and see safe area values in android 9,10 and 11 emulators 

**Expected results:** 

Safe area values should not be zero in  android 9 and 10  if device have display cutout .  

**Actual results:** 
Safe area values always coming as  zero in  android 9 and 10 .  

 Android 9
------------
![Screenshot 2022-05-10 at 6 55 11 PM](https://user-images.githubusercontent.com/100214707/167644895-cef081aa-a208-4ff1-ab24-93314c69a743.png)

 Android 10
------------
![Screenshot 2022-05-10 at 6 55 29 PM](https://user-images.githubusercontent.com/100214707/167644994-b2a9c0d1-06bc-425d-962b-77ec2b00299a.png)

 Android 11
-------------
![Screenshot 2022-05-10 at 6 55 51 PM](https://user-images.githubusercontent.com/100214707/167645043-cef172c5-c1c6-40ed-b99f-a4c47eee1770.png)

**NOTE: i am facing this issue in flutter version 2.8.x and 2.10.x and  2.13.0-0.4.pre ( literally i am facing this issue in most of all versions )**
 
If there is any alternate solution please provide.
i have seen similer issues  #64274 , #56362 , #46486 .

<details>
<summary>Code sample</summary>

sample code [Github Repo](https://github.com/venkatjg/qwe)

</details>

<details>
  <summary>Logs</summary>

```
boyavenkatareddy@Mac-Eng-BoyaR qwe % fvm flutter doctor -v
[✓] Flutter (Channel beta, 2.13.0-0.4.pre, on macOS 12.1 21C52 darwin-arm, locale en-IN)
    • Flutter version 2.13.0-0.4.pre at /Users/boyavenkatareddy/fvm/versions/2.13.0-0.4.pre
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 25caf1461b (5 days ago), 2022-05-05 14:23:09 -0700
    • Engine revision c5caf749fe
    • Dart version 2.17.0 (build 2.17.0-266.8.beta)
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/boyavenkatareddy/Library/Android/sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /Library/Java/JavaVirtualMachines/zulu-8.jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (Zulu 8.60.0.21-CA-macos-aarch64) (build 1.8.0_322-b06)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 13.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[!] Android Studio
    • Android Studio at /Users/boyavenkatareddy/Library/Android/sdk/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Android Studio not found at /Users/boyavenkatareddy/Library/Android/sdk/Contents
    • Try updating or re-installing Android Studio.

[✓] Connected device (4 available)
    • Android SDK built for arm64 (mobile) • emulator-5554 • android-arm64  • Android 10 (API 29) (emulator)
    • Android SDK built for arm64 (mobile) • emulator-5556 • android-arm64  • Android 9 (API 28) (emulator)
    • sdk gphone arm64 (mobile)            • emulator-5558 • android-arm64  • Android 11 (API 30) (emulator)
    • Chrome (web)                         • chrome        • web-javascript • Google Chrome 101.0.4951.54

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.

```

</details>

**Comment by darshankawar** [comment]
@venkatjg 
Thanks for the detailed report with screenshots and code sample. I believe you are hitting same issue as https://github.com/flutter/flutter/issues/64274, so I suggest you to follow-up in it for further updates.
Closing this as a duplicate.
