### ISSUE TITLE
Android HttpClient not complete request on app closing 

### ISSUE THREAD

**Issue by ruscoff** [flutter/flutter#103415]
Hi,
  i'm trying to do POST call during app closing or sending in background with Android real phone.
If i try to send app in background it works always correctly but if i close the app pushing back physical button, that POST call will not executed. Debug show to reach this function and after return back without any feedback, seems like flutter engine stop to works before complete call.

`void didChangeAppLifecycleState(AppLifecycleState state) async {
    if (   state == AppLifecycleState.inactive) {
            final request = await client.postUrl(Uri.parse("https://www.xxxxx.xx/xxxx/xxxx.php/xxxx"))
}
`

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.10.5, on Microsoft Windows [Versione 10.0.19043.1645], locale it-IT)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc3)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.0.4)
[√] Android Studio (version 2021.1)
[√] VS Code, 64-bit edition (version 1.65.2)
[√] Connected device (4 available)
[√] HTTP Host Availability

Best Regards

**Comment by darshankawar** [comment]
@ruscoff 
Thanks for the report. Can you please provide [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that shows this behavior ?
