### ISSUE TITLE
url_launcher 6.1.0 android 

### ISSUE THREAD

**Issue by sweetwolf** [flutter/flutter#103458]
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':url_launcher_android'.
> Could not resolve all artifacts for configuration ':url_launcher_android:classpath'.
   > Could not resolve org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.3.31.
     Required by:
         project :url_launcher_android > com.android.tools.build:gradle:3.4.2
         project :url_launcher_android > com.android.tools.build:gradle:3.4.2 > com.android.tools.build:builder:3.4.2
         project :url_launcher_android > com.android.tools.build:gradle:3.4.2 > com.android.tools.analytics-library:shared:26.4.2
         project :url_launcher_android > com.android.tools.build:gradle:3.4.2 > com.android.tools.lint:lint-gradle-api:26.4.2
         project :url_launcher_android > com.android.tools.build:gradle:3.4.2 > com.android.tools.build:gradle-api:3.4.2
         project :url_launcher_android > com.android.tools.build:gradle:3.4.2 > androidx.databinding:databinding-compiler-common:3.4.2
         project :url_launcher_android > com.android.tools.build:gradle:3.4.2 > com.android.tools.build:builder:3.4.2 > com.android.tools:sdk-common:26.4.2
         project :url_launcher_android > com.android.tools.build:gradle:3.4.2 > com.android.tools.build:builder:3.4.2 > com.android.tools:common:26.4.2
         project :url_launcher_android > com.android.tools.build:gradle:3.4.2 > com.android.tools.build:builder:3.4.2 > com.android.tools.build:manifest-merger:26.4.2
         project :url_launcher_android > com.android.tools.build:gradle:3.4.2 > com.android.tools.build:builder:3.4.2 > com.android.tools.analytics-library:tracker:26.4.2
         project :url_launcher_android > com.android.tools.build:gradle:3.4.2 > com.android.tools.build:builder:3.4.2 > com.android.tools:sdklib:26.4.2 > com.android.tools:repository:26.4.2
      > Could not resolve org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.3.31.
         > Could not get resource 'https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-stdlib-jdk8/1.3.31/kotlin-stdlib-jdk8-1.3.31.pom'.
            > Could not HEAD 'https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-stdlib-jdk8/1.3.31/kotlin-stdlib-jdk8-1.3.31.pom'.
               > Connect to repo.maven.apache.org:443 [repo.maven.apache.org/127.0.0.1] failed: Connection refused: connect

**Comment by darshankawar** [comment]
@sweetwolf 
Can you try solutions mentioned in [this](https://stackoverflow.com/questions/59482329/flutter-problems-could-not-resolve-all-artifacts-for-configuration-classpath) SO link and see if they help ?
