### ISSUE TITLE
Flutter windows - weird behaviour when app is half on and half off screen

### ISSUE THREAD

**Issue by gregor20021** [flutter/flutter#103482]
## Steps to Reproduce

- first, run your flutter app in windows mode
- move your app window so it will be half off and half on screen
- refresh state so something will change (in my case setState changes the entire screen so the result is pretty obvious, don't know if this happens with navigator also or not)
- move the changed window back on the screen and you should get a similar result I got below on the screenshot

<details>
This is happening while debugging, haven't tried the release version
</details>

![Screenshot 2022-05-11 131058](https://user-images.githubusercontent.com/33237691/167837092-4a598632-524e-4850-8ee7-15cdca35fbe0.png)

**Comment by gregor20021** [comment]
> @gregor20021 
> Thanks for the report. Can you check if this issue is similar to your case ? https://github.com/flutter/flutter/issues/102390
> If not, can you provide `flutter doctor -v` and a minimal code sample that shows this behavior ?
> 

Yes it is preatty simular, the only difference is that i wrote my own navigator using set state so it changes the entire screen, otherwise these two issues are the same

Good luck solving this🙂

**Comment by darshankawar** [comment]
Thanks for confirming. Please follow-up in it for further updates as I am closing this in favor of the linked one.
