### ISSUE TITLE
Regression in Android app build time

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#103421]
Edit: See comment below, this appears to be due to a change in infra.

On the Engine roll here https://github.com/flutter/flutter/pull/103154

SkiaPerf is reporting regressions in several compilation time benchmarks:

https://flutter-flutter-perf.skia.org/e/?begin=1650572647&end=1652191748&keys=X5b4f91962bfaaeb05668b3d0bf7ca87e&requestType=0&xbaroffset=28748

The Engine roll contains the Dart roll https://github.com/flutter/engine/pull/33132, with commits https://dart.googlesource.com/sdk.git/+log/2783b4384e56..ec71f6e0cb08, but nothing is jumping out at me as a likely cause.

Sample logs from CI are here https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8814545042243623665/+/u/run_flutter_gallery_android__compile/test_stdout, and contain the command to run the benchmark at the top.

cc'ing some folks who might be interested:
@a-siva @alexmarkov (for compile time)
@gaaclarke (for one of the other changes in the engine roll)
@keyonghan (to ask if there have been any changes to the device lab machines that this benchmark runs on)

**Comment by zanderso** [comment]
Flagged on the next commit, but probably related: https://flutter-flutter-perf.skia.org/e/?begin=1651779549&end=1651819151&keys=X180a70940030bd997655141f6575027f&num_commits=50&request_type=1&xbaroffset=28749

**Comment by gaaclarke** [comment]
What about https://github.com/flutter/engine/pull/33135? "Roll vulkan-deps from 40f4358a2a69 to 7727106601af" sounds like it could cause a change in compilation time.  The increase in build time wasn't reported by skiaperf until the next datapoint though.

It could also be a change in infra, did you check with the infra team to see if some change has been made to the bots?

**Comment by gaaclarke** [comment]
The change to memozing `Locale.hashCode` is unlikely to be the cause.  I don't believe compilation will call `Locale.hashCode` often.

**Comment by keyonghan** [comment]
> @keyonghan (to ask if there have been any changes to the device lab machines that this benchmark runs on)

To confirm: no changes from hardware side, and the test has been running evenly on different linux/android testbeds.

**Comment by zanderso** [comment]
> What about [flutter/engine#33135](https://github.com/flutter/engine/pull/33135)? "Roll vulkan-deps from 40f4358a2a69 to 7727106601af" sounds like it could cause a change in compilation time.

Clarified in the issue title that this was a regression in Dart code compilation time, that is the time to compile a Flutter app.

**Comment by jason-simmons** [comment]
So far I've been unable to reproduce this locally.

The iOS compile time benchmarks have not changed during this interval:

https://flutter-flutter-perf.skia.org/e/?begin=1651480147&end=1652203614&queries=sub_result%3Ddebug_full_compile_millis%26sub_result%3Drelease_full_compile_millis%26test%3Dflutter_gallery_ios__compile%26test%3Dbasic_material_app_ios__compile&requestType=0

**Comment by zanderso** [comment]
In the fast runs I am see logs like the following from e.g. https://ci.chromium.org/ui/p/flutter/builders/prod/Linux_android%20complex_layout_android__compile/2737/overview
```
[complex_layout_android__compile] [STDOUT] stdout: Running Gradle task 'assembleRelease'...                        
[complex_layout_android__compile] [STDOUT] stdout: Checking the license for package Android SDK Build-Tools 30.0.2 in /opt/s/w/ir/cache/android/sdk/licenses
[complex_layout_android__compile] [STDOUT] stdout: License for package Android SDK Build-Tools 30.0.2 accepted.
[complex_layout_android__compile] [STDOUT] stdout: Preparing "Install Android SDK Build-Tools 30.0.2 (revision: 30.0.2)".
[complex_layout_android__compile] [STDOUT] stdout: "Install Android SDK Build-Tools 30.0.2 (revision: 30.0.2)" ready.
[complex_layout_android__compile] [STDOUT] stdout: Installing Android SDK Build-Tools 30.0.2 in /opt/s/w/ir/cache/android/sdk/build-tools/30.0.2
[complex_layout_android__compile] [STDOUT] stdout: "Install Android SDK Build-Tools 30.0.2 (revision: 30.0.2)" complete.
[complex_layout_android__compile] [STDOUT] stdout: "Install Android SDK Build-Tools 30.0.2 (revision: 30.0.2)" finished.
[complex_layout_android__compile] [STDOUT] stderr: No issues found.
[complex_layout_android__compile] [STDOUT] stdout: Running Gradle task 'assembleRelease'...                           95.3s
```

In the slow runs, the lines about installing the SDK build tools are missing, e.g.:
```
[complex_layout_android__compile] [STDOUT] stdout: Running Gradle task 'assembleRelease'...                        
[complex_layout_android__compile] [STDOUT] stderr: No issues found.
[complex_layout_android__compile] [STDOUT] stdout: Running Gradle task 'assembleRelease'...                          181.9s
```

This also happens if I trigger a new build on an old commit:

https://ci.chromium.org/ui/p/flutter/builders/prod/Linux_android%20complex_layout_android__compile/3003/overview

So, I'm inclined to believe that this is an infrastructure/caching issue that has affected our build benchmarks. Given that, I am routing this issue to the infra queue. /cc @blasten

**Comment by godofredoc** [comment]
Linux_android test beds have not changed in a while, I could not find anything that could impact compilation time.

**Comment by zanderso** [comment]
@godofredoc the logs indicate that there is a difference between the runs in what the cache on the bots is populated with:
```
[complex_layout_android__compile] [STDOUT] stdout: Installing Android SDK Build-Tools 30.0.2 in /opt/s/w/ir/cache/android/sdk/build-tools/30.0.2
```
appears when the run is faster. The runs are slower when that line is not present in the logs. New runs on old commits are now slower than surrounding commits, indicating that this regression is not due to a change to the code under test. Could you help theorize what could have led to this?

**Comment by keyonghan** [comment]
One observation: there doesn't seem to be a clear mapping between `build execution time` and the `Android SDK Build-Tools`. The builds with `Android SDK Build-Tools` happened 5 times consecutively around 2022-05-05 10:17 AM:

Builds with `Android SDK Build-Tools`:
[2737](https://ci.chromium.org/p/flutter/builders/prod/Linux_android%20complex_layout_android__compile/2737) - 5min 29s
[2738](https://ci.chromium.org/p/flutter/builders/prod/Linux_android%20complex_layout_android__compile/2738) - 0min 42s
[2739](https://ci.chromium.org/p/flutter/builders/prod/Linux_android%20complex_layout_android__compile/2739) - 11min 58s
[2740](https://ci.chromium.org/p/flutter/builders/prod/Linux_android%20complex_layout_android__compile/2740) - 5min 24s
[2741](https://ci.chromium.org/p/flutter/builders/prod/Linux_android%20complex_layout_android__compile/2741) - 10min 9s

Checked 10 builds before and after these 5 builds, and none of them were with `Android SDK Build-Tools`. The `Android SDK Build-Tools` somehow seems a temporary change.

**Comment by zanderso** [comment]
@keyonghan the overall build execution time is not what is being measured by the benchmark. The variation in that number is dominated by the time to fetch dependencies. The wide variation in that number is likely an issue that should be addressed separately. Rather, the benchmark numbers that this issue is about are the `assembleRelease` and `assembleDebug` times reported in the logs.

**Comment by keyonghan** [comment]
Dig into the builds further, seems still not clear mapping between `assembleDebug` time and `Android SDK Build-Tools`. Please see below:

- builds without `Android SDK Build-Tool` before regression: (build v.s. debug_full_compile_millis)
  - [build 2734](https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8815013092965922305/+/u/run_complex_layout_android__compile/test_stdout): 52515 ms
  - [build 2733](https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8815019420745564049/+/u/run_complex_layout_android__compile/test_stdout): 51588 ms
- builds with `Android SDK Build-Tool` after regression: (build number v.s. debug_full_compile_millis)
  - [build 2745](https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8814958665657865649/+/u/run_complex_layout_android__compile/test_stdout): 70713 ms

**Comment by godofredoc** [comment]
After more investigation we can not find anything from the infra side that would impact the metric. @blasten is there anything in the gradle logic that could be causing this?

**Comment by blasten** [comment]
Also, cc @GaryQian.

This benchmark seems to be measuring the time it takes to run the build command, so if a dependency is being installed, the time increases.
https://github.com/flutter/flutter/blob/be7a4227c72715df0b5f6b07da4b1d63785c30f4/dev/devicelab/lib/tasks/perf_tests.dart#L1445-L1447

I don't see anything tracked in the Flutter repo that could have caused this issue.  @GaryQian what build tool version do we have installed in these bots?

**Comment by zanderso** [comment]
Assigning to @GaryQian to answer the question from @blasten

**Comment by godofredoc** [comment]
@GaryQian any ideas on what may be causing this?

**Comment by GaryQian** [comment]
No, unclear what is causing this.

The bots bow use the unified android sdk package on cipd, for most bots, they are using buildtools version 31.0.0

I recently added 33.0.0-rc4 but have not updated any shards to use it yet.

**Comment by GaryQian** [comment]
https://github.com/flutter/flutter/pull/105259 does not seem to have resolved the build time. Further investigation required.

**Comment by GaryQian** [comment]
https://github.com/flutter/flutter/pull/109177 to separate network steps was landed but reverted.

**Comment by GaryQian** [comment]
https://github.com/flutter/flutter/pull/109177 was Relanded as https://github.com/flutter/flutter/pull/111562

**Comment by GaryQian** [comment]
Since https://github.com/flutter/flutter/pull/109177 was relanded, we can see that the high variance with compile time metrics was largely caused by the network steps. In the following metrics, the top two are the initial compile (includes network downloads) and the bottom two are the full compile which does not include network. The bottom two are clearly more stable and a much better indicator of true compile time.
https://flutter-flutter-perf.skia.org/e/?queries=sub_result%3Drelease_full_compile_millis%26sub_result%3Drelease_initial_compile_millis%26test%3Dhello_world_android__compile&selected=commit%3D31363%26name%3D%252Carch%253Dintel%252Cbranch%253Dmaster%252Cconfig%253Ddefault%252Cdevice_type%253DMoto_G__4_%252Cdevice_version%253Dandroid-24%252Chost_type%253Dmac%252Csub_result%253Drelease_initial_compile_millis%252Ctest%253Dhello_world_android__compile%252C

**Comment by GaryQian** [comment]
We also see here that the benchmark also spikes corresponding to the gradle bump to AGP/Gradle 7.2/7.5. the outlier earlier on was also the gradle bump landing and shortly being reverted.
![image](https://user-images.githubusercontent.com/1887398/193070120-961f8574-1b26-4121-979b-cb55967170b6.png)

**Comment by zanderso** [comment]
@GaryQian is it possible to profile where the time is going and report a bug to the Gradle team?

**Comment by GaryQian** [comment]
I am working on profiling the build with the gradle profiler. Though it seems the profiler isnt a clean plug-and-play to integrate into our rather convoluted build system

**Comment by GaryQian** [comment]
After additional investigation, It is still not clear what is causing the increased build time on gradle upgrades. However, since it is not healthy to remain on antiquated versions of gradle, we will keep gradle upgraded and work with the gradle team to further explore what can cause build time increases. Since our version jumps are large, there are potentially new features/checks that could be behind the increase and this may be an acceptable tradeoff.

**Comment by zanderso** [comment]
As far as I can tell, the regression noted in the original report has recovered in the meantime. I'll close this.
