### ISSUE TITLE
Widget catalog doesn't link to sample code in widget API docs

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#10343]
It would be really cool if our widget catalog could link over to the emerging set of sample code in API docs.

See https://github.com/flutter/flutter/issues/9407#issuecomment-304144634 for examples

**Comment by Hixie** [comment]
Presumably if they like to the API docs at all, they link to the samples already?

**Comment by sethladd** [comment]
Yup, but I think we can do better. We can provide a link directly to the sample. :) It's nice to know when there is a sample for a widget, too.

**Comment by Hixie** [comment]
The sample is normally above the fold. I'd also be concerned about people not seeing the full context. I think it's fine to just link to the API page.

**Comment by sethladd** [comment]
Closing for now, after discussion with @Hixie
