### ISSUE TITLE
Command PhaseScriptExecution failed with a nonzero exit code  [MacOS M1 Chip] 

### ISSUE THREAD

**Issue by Gadagoju007** [flutter/flutter#103461]
I am trying to run Flutter app on iOS device but its throwing an exception

 **Command PhaseScriptExecution failed with a nonzero exit code** 

I have tried few things which could not solve my problem 

`/bin/sh -c /Users/ram/Library/Developer/Xcode/DerivedData/Runner-etlsxgkgvoffgrdfjoyxpeuknpec/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Script-9740EEB61CF901F6004384FC.sh

/bin/sh: /Users/ram/Development/flutter/bin/flutter/packages/flutter_tools/bin/xcode_backend.sh: Not a directory
Command PhaseScriptExecution failed with a nonzero exit code `

Please help

**Comment by darshankawar** [comment]
From the log you shared, the error seems to be below:

`Development/flutter/bin/flutter/packages/flutter_tools/bin/xcode_backend.sh: Not a directory`

Does this path exist ?  Is your Flutter SDK at //Users/ram/Flutter/flutter?

It seems the flutter path is mis-configured or not correctly set. You can run `which flutter` and see what path is it pointing to and confirm if in your PATH, does `FLUTTER_ROOT` point to same path or not.

**Comment by Gadagoju007** [comment]
@darshankawar  when I run 
which flutter then the path is this one 
/Users/ram/Development/flutter/bin/flutter

**Comment by darshankawar** [comment]
Ok, so that seems to be the same path as shown in the log you shared correct ?
Can you provide `flutter doctor -v`, `ios/podfile` and `flutter run -v` ? The verbose log will be huge so you can put that in a text file and share it here.

**Comment by Gadagoju007** [comment]
[Flutter_logs_Terminal.pdf](https://github.com/flutter/flutter/files/8670369/Flutter_logs_Terminal.pdf)

**Comment by darshankawar** [comment]
@Gadagoju007 
You didn't provide `flutter doctor -v`, podfile so don't really know which version you are on.
Also the verbose log in red lines seems to be pointing to third party plugins, so try to upgrade those to latest ones and try again.

Also, since these seems to be pointing to third party plugin code / usage, I am going ahead and closing it as not a flutter issue. If you think the same error occurs in brand new project without any third party plugins, write in comments and I'll reopen it.

**Comment by LeGoffMael** [comment]
Just in case someone arrive on this issue like i did.
Double check there is not an unwanted `import 'dart:html';` in your code.

if so, just remove it.

I imported it by mistake and lost time trying to figuring what was happening 🥲.
