### ISSUE TITLE
[iOS][XCode]: "Error Analyzing App Version" while validating archive with no error details.

### ISSUE THREAD

**Issue by denghejun** [flutter/flutter#103402]
Most of people get this error(with no error detail, I checked the log file) when validating archive in Xcode, any help?
![Screen Shot 2022-05-10 at 17 29 38](https://user-images.githubusercontent.com/8454695/167598779-4abeb86e-011f-4f1f-ad6f-06fcea59c1ec.png)

**Comment by denghejun** [comment]
I got it, try to remove the Xcode account (AppID), then add it back, it works.

**Comment by nur001** [comment]
I have the same problem. Have you solved it

**Comment by denghejun** [comment]
> I have the same problem. Have you solved it

I thought I fixed it, but not yet actually, I got this error again.

**Comment by darshankawar** [comment]
@denghejun 
Please check below links and see if they help.


https://stackoverflow.com/questions/69548498/xcode-error-analyzing-app-version-when-validating-app-in-archive-organizer
https://stackoverflow.com/questions/69433432/what-is-an-error-analyzing-app-version-when-distributing-from-xcode
https://developer.apple.com/forums/thread/693335

Also, these kind of issues are better to be asked on support channels like StackOverflow, so please ask the same there.

Closing from here.

**Comment by lukepighetti** [comment]
I'm also having this issue on an app that was successfully build/archive in the last few weeks. I think this should be left open until someone reports success. cc @darshankawar 

<img width="756" alt="Screen Shot 2022-05-10 at 8 58 55 AM" src="https://user-images.githubusercontent.com/666539/167635359-ac8ce32b-2033-4c0f-bc86-7ef7f4b05604.png">

**Comment by darshankawar** [comment]
Thanks for the feedback. Reopening and labeling based on the reports.

**Comment by darshankawar** [comment]
/cc @jmagman.

There doesn't seem to be any error log that usually indicates what the error could be.

**Comment by lukepighetti** [comment]
Attaching logs here (PII removed):
[Runner_2022-05-10_09-22-34.504.xcdistributionlogs.zip](https://github.com/flutter/flutter/files/8661897/Runner_2022-05-10_09-22-34.504.xcdistributionlogs.zip)

**Comment by lukepighetti** [comment]
Looks like this is upstream https://developer.apple.com/forums/thread/705599

**Comment by jmagman** [comment]
Thanks for finding that @lukepighetti, looks like it's unrelated to Flutter.  The system status cited https://developer.apple.com/system-status/ looks all green, can you keep trying and let us know when it is resolved?

**Comment by jmagman** [comment]
There was a post in https://developer.apple.com/forums/thread/705599?page=16 from 45 minutes ago that says it was fixed for someone.

**Comment by lukepighetti** [comment]
> Thanks for finding that @lukepighetti, looks like it's unrelated to Flutter. The system status cited https://developer.apple.com/system-status/ looks all green, can you keep trying and let us know when it is resolved?

I'll be trying here again in a minute. As a note, during this whole thing, status stayed all green for some reason.

**Comment by lukepighetti** [comment]
It's working now. I think it's OK to close this issue.

**Comment by jmagman** [comment]
Thanks for the update, @lukepighetti! Closing.
