### ISSUE TITLE
[plugins] enable some Flutter lints

### ISSUE THREAD

**Issue by asashour** [flutter/flutter#103403]
We should have the below enabled, since they are part of Flutter lints (some are recommended).

- [avoid_unnecessary_containers](https://dart-lang.github.io/linter/lints/avoid_unnecessary_containers.html), existing code passes.
- [file_names](https://dart-lang.github.io/linter/lints/file_names.html), existing code passes.
- [prefer_function_declarations_over_variables](https://dart-lang.github.io/linter/lints/prefer_function_declarations_over_variables.html).
- [prefer_interpolation_to_compose_strings](https://dart-lang.github.io/linter/lints/prefer_interpolation_to_compose_strings.html).
- [prefer_null_aware_operators](https://dart-lang.github.io/linter/lints/prefer_null_aware_operators.html), existing code passes.
- [sized_box_for_whitespace](https://dart-lang.github.io/linter/lints/sized_box_for_whitespace.html).

**Comment by stuartmorgan** [comment]
Adding lints from flutter/flutter is covered by https://github.com/flutter/flutter/issues/76229
