### ISSUE TITLE
Keyboard is not appearing on Safari iOS when browsing from one page to another

### ISSUE THREAD

**Issue by denddyprod** [flutter/flutter#103410]
## Steps to Reproduce

1. I used this example [form_app](https://github.com/flutter/samples/tree/master/form_app) from Flutter samples
2. To demonstrate bug I visited [Sample Flutter form](https://flutter.github.io/samples/web/form_app/#/)

**Steps that I made:**

1. Enter the page and press the button to "Sign in with HTTP" page.
2. My keyboard appears and focuses on input.
3. Click on the button that leads to the back page.
4. Press again the button leading to the "Sign in with HTTPS" page

**Expected results:**

My expectation is that every time I enter the page my keyboard and focus will appear on the input. 

**Actual results:** 

After a few repetitions of the steps mentioned above, the focus remains on the input but the keyboard no longer appears. 

This only happens on Safari on iOS, I also tested it on Chrome ( on iOS ) and Android phones as a result it worked. A strange fact is that the keyboard does not appear even though the focus is visible on the given input.  When I refresh the page everything starts to work and then again it doesn't work properly

**Code sample:**
[Here](https://github.com/flutter/samples/tree/master/form_app/lib)

**Attached video to demonstrate bug:**

Safari, iOS 15.4.1 (19E258)

https://youtube.com/shorts/NKtDUnWV16I?feature=share

Chrome, iOS 15.4.1 (19E258)

https://user-images.githubusercontent.com/16977962/167635617-459a6fa6-e251-4f18-8cf7-91cb7b8d8a7c.mov

**Comment by darshankawar** [comment]
@denddyprod 
Thanks for the report. From the code you shared, I observed that it uses `autofocus: true` which could be reason why keyboard doesn't show up. Here's an original issue for it: https://github.com/flutter/flutter/issues/58498

Can you try without `autofocus: true` and see if it works as expected then ?

**Comment by denddyprod** [comment]
> @denddyprod Thanks for the report. From the code you shared, I observed that it uses `autofocus: true` which could be reason why keyboard doesn't show up. Here's an original issue for it: #58498
> 
> Can you try without `autofocus: true` and see if it works as expected then ?

I set `autofocus: false` and focused manually on initState:

```
late FocusNode firstFocus;

  @override
  void initState() {
    firstFocus = FocusNode();
    firstFocus.requestFocus();
    super.initState();
  }

```
...

` 
TextFormField(
                    focusNode: firstFocus,
                    autofocus: false,
`

Unfortunately, the result is same as case with `autofocus: true` and problem still persists.

**Comment by darshankawar** [comment]
I think your issue is same as the linked one, so I suggest you share your findings in that issue for better tracking. Closing this as a duplicate.
