### ISSUE TITLE
Problem after upgrade  flutter 3 

### ISSUE THREAD

**Issue by samithe7** [flutter/flutter#103547]
## Logs

< /C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_riverpod-1.0.3/lib/src/framework.dart:275:26: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
- 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/C:/src/flutter/packages/flutter/lib/src/scheduler/binding.dart').
package:flutter/…/scheduler/binding.dart:1
    if (SchedulerBinding.instance!.schedulerPhase ==>
<summary>Logs</summary>

**Comment by stuartmorgan** [comment]
Compatibility issues with third-party packages need to be reported to the developers of those packages, so they can update them.
