### ISSUE TITLE
Allow TextPainter access from higher-level widgets

### ISSUE THREAD

**Issue by Dall127** [flutter/flutter#103524]
## Use case
The application that I am using requires knowing precise locations of where text is getting painted on the screen, and I also need the ability to select text.

 I rebuilt the page using a custom painter to get precise locations, but I lost the ability to use SelectableText. To recreate the same functionality, I would then have to rebuild the SelectableText Widget from scratch, as I can't inherit from its private state class, or access the TextPainter. 
## Proposal

I have two ideas in mind how this could be accomplished. There could be an abstract selectable text state that allows you to inherit, thus gaining access to the associated text painter, or;

Creating a chain of methods that allow access to the text painter from the SelectableText class to be able to call TextPainter functions while also allowing text to be selectable. 

## Side Notes

This is a mission mission critical feature required for my company's app to release, so I am willing to assist in any way possible.

**Comment by chunhtai** [comment]
There is a global selection project on going, which makes Text selectable by default, you can also implement the general selection api to make any widget selectable once it landed.

also you can access the layout information from render paragraph or renderEditable if you use SelectableText, will this work for your use case?

**Comment by Dall127** [comment]
@chunhtai If I am able to access the layout information from renderParagraph in SelectableText, that should work. Here is the line of code that I am needing the lower level access for. 

```
final List<TextBox> boxes = textPainter
        .getBoxesForSelection(calculateTextSelection(sentence, pageOffset));
```

So as long as I can call `getBoxesForSelection` and use `SelectableText`, then I should be fine. @chunhtai, do you have any suggestions on how to do this?

**Comment by chunhtai** [comment]
you should be able to do the following, closing this issue


```dart
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';
import 'package:flutter/services.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
           home: MyAppBody(),
      );
  }
}

class MyAppBody extends StatefulWidget {
  @override
  State<StatefulWidget> createState() => MyAppBodyState();

}

class MyAppBodyState extends State<MyAppBody> {
  final GlobalKey key = GlobalKey();
  RenderEditable? _getRenderEditable(RenderObject object) {
    if (object is RenderEditable) {
      return object;
    }
    RenderEditable? editable;
    object.visitChildren((child) {
      if (editable != null)
        return;
      editable = _getRenderEditable(child);
    });
    return editable;
  }
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: SelectableText('My selectable text',key:key),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          final RenderObject object = key.currentContext!.findRenderObject()!;
          final RenderEditable editable = _getRenderEditable(object)!;
          print(' boxes in local coordinate: ${editable.getBoxesForSelection(TextSelection(baseOffset: 0, extentOffset: 2))}');
        },
        child: const Icon(Icons.add),
      ),
    );
  }
}
```
