### ISSUE TITLE
Flutter commands give output of / not root-owned 1000:0

### ISSUE THREAD

**Issue by MartinDeBeer** [flutter/flutter#103592]
## Steps to Reproduce

I ran the installation of flutter as shown on the website 
https://docs.flutter.dev/get-started/install
When I went onto visual studio code to use it it said that it can't find the SDK so I tried running some commands and it just gives the output shown in the title. What am I doing wrong?? I tried to chown it and that doesn't work and neither does chmod.

I am running Linux Mint 20.3

![image](https://user-images.githubusercontent.com/79763595/168026603-0084b793-e6f2-42d0-98f7-ca728d8f3c19.png)

**Comment by darshankawar** [comment]
@MartinDeBeer 
It could be related to the setup / configuration / path. Please double check or ask support questions on stackoverflow.
Closing from here.
