### ISSUE TITLE
out of memory issue in my flutter application which is causing the application to crash. The widget causing it is video player

### ISSUE THREAD

**Issue by kavyabhargava** [flutter/flutter#103538]
My android emulators are crashing all of them. I am trying to run preloaded video in my application.

I have tried to dispose the video player controllers but It is not working, but still giving the error somehow(which does not makes sense ).

I am able to scroll through some of the videos and then the application crashes. Throws Out of memory error. 

My screen where the error persists:

```
class _PageViewBuilderState extends State<PageViewBuilder> {
  VideoPlayerController? INvideoPlayerController;
  @override
  void initState() {
    super.initState();
    INvideoPlayerController = VideoPlayerController.network('')
      ..addListener(() {})
      ..setLooping(true)
      ..initialize().then((value) => INvideoPlayerController!.play());
  }



  int _currentPage = 0;
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: StreamBuilder<QuerySnapshot<Map<String, dynamic>>>(
          stream:
              FirebaseFirestore.instance.collection('Videourls').snapshots(),
          builder: (ctx, snapshot) {
            if (snapshot.hasError) {
              const Center(
                child: Text('Unknown Error'),
              );
            }

            return !snapshot.hasData
                ? const Center(
                    child: CircularProgressIndicator(),
                  )
                : PageView.builder(
                    scrollDirection: Axis.vertical,
                    itemCount: snapshot.data!.docs.length,
                    onPageChanged: (int page) {
                      setState(() {
                        _currentPage = page;
                      });
                    },
                    itemBuilder: (BuildContext context, int index) {
                      INvideoPlayerController = VideoPlayerController.network(
                        snapshot.data!.docs[index].get('url'),
                      )
                        ..setLooping(true)
                        ..initialize()
                            .then((value) => INvideoPlayerController!.play());
  @override
  void dispose() {
    INvideoPlayerController?.dispose();
    super.dispose();
  }
                      return Stack(alignment: Alignment.center, children: [
                        AspectRatio(
                          aspectRatio: MediaQuery.of(context).size.width /
                              MediaQuery.of(context).size.height,
                          //  INvideoPlayerController!.value.aspectRatio,
                          child: VideoPlayer(INvideoPlayerController!),
                        ),
                        Container(),
                          ]),
                        ])
                      ]);
                    },
                  );
          }),
    );
  }
}

```

Flutter doctor -v:
```
[✓] Flutter (Channel stable, 2.10.5, on macOS 12.2.1 21D62 darwin-arm, locale en-IN)
    • Flutter version 2.10.5 at /Users/kavyabhargava/FlutterDev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (3 weeks ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/kavyabhargava/Library/Android/sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] VS Code (version 1.67.0)
    • VS Code at /Users/kavyabhargava/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Connected device (2 available)
    • iPhone 12 mini (mobile) • B6018B57-5091-434D-976A-C63D816E10E3 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-4 (simulator)
    • Chrome (web)            • chrome                               • web-javascript • Google Chrome 101.0.4951.54

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

**Comment by darshankawar** [comment]
@kavyabhargava 
Can you provide entire error log that shows OOM ? 

Also I think you are hitting same issue as https://github.com/flutter/flutter/issues/64897

**Comment by kavyabhargava** [comment]
So my issue is different than that because he is trying to run two video simultaneously. In my case, I don't care about running videos simultaneously. I am trying to load videos in the page view builder one after the other through stream builder.(In my case controller can get disposed one the other video starts playing)

Error log:

`E/flutter ( 4675): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(NullPointerException, java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference, null, null)
W/.news_app_admi( 4675): Throwing OutOfMemoryError "Failed to allocate a 65548 byte allocation with 529040 free bytes and 516KB until OOM, target footprint 201326592, growth limit 201326592" (VmSize 24655016 kB)
W/.news_app_admi( 4675): Throwing OutOfMemoryError "Failed to allocate a 65548 byte allocation with 140296 free bytes and 137KB until OOM, target footprint 201326592, growth limit 201326592" (VmSize 24672508 kB)
W/.news_app_admi( 4675): Throwing OutOfMemoryError "Failed to allocate a 65548 byte allocation with 88 free bytes and 88B until OOM, target footprint 201326592, growth limit 201326592" (VmSize 24747536 kB)
W/.news_app_admi( 4675): Throwing OutOfMemoryError "Failed to allocate a 65548 byte allocation with 52512 free bytes and 51KB until OOM, target footprint 201326592, growth limit 201326592" (VmSize 24747536 kB)
W/.news_app_admi( 4675): Throwing OutOfMemoryError "Failed to allocate a 65548 byte allocation with 52464 free bytes and 51KB until OOM, target footprint 201326592, growth limit 201326592" (VmSize 24747536 kB)
W/.news_app_admi( 4675): Throwing OutOfMemoryError "Failed to allocate a 65548 byte allocation with 51008 free bytes and 49KB until OOM, target footprint 201326592, growth limit 201326592" (VmSize 24747536 kB)
W/.news_app_admi( 4675): Throwing OutOfMemoryError "Failed to allocate a 65548 byte allocation with 51472 free bytes and 50KB until OOM, target footprint 201326592, growth limit 201326592" (VmSize 24747536 kB)
W/.news_app_admi( 4675): Throwing OutOfMemoryError "Failed to allocate a 65548 byte allocation with 51936 free bytes and 50KB until OOM, target footprint 201326592, growth limit 201326592" (VmSize 24747536 kB)
W/.news_app_admi( 4675): Throwing OutOfMemoryError "Failed to allocate a 65552 byte allocation with 51936 free bytes and 50KB until OOM, target footprint 201326592, growth limit 201326592" (VmSize 24747536 kB)
W/.news_app_admi( 4675): Throwing OutOfMemoryError "Failed to allocate a 65548 byte allocation with 43592 free bytes and 42KB until OOM, target footprint 201326592, growth limit 201326592" (VmSize 24747536 kB)
W/.news_app_admi( 4675): Throwing OutOfMemoryError "Failed to allocate a 65548 byte allocation with 10928 free bytes and 10KB until OOM, target footprint 201326592, growth limit 201326592" (VmSize 24765028 kB)
W/.news_app_admi( 4675): Throwing OutOfMemoryError "Failed to allocate a 65552 byte allocation with 45280 free bytes and 44KB until OOM, target footprint 201326592, growth limit 201326592" (VmSize 24765028 kB)
W/.news_app_admi( 4675): Throwing OutOfMemoryError "Failed to allocate a 65548 byte allocation with 2944 free bytes and 2944B until OOM, target footprint 201326592, growth limit 201326592" (VmSize 24765028 kB)
W/.news_app_admi( 4675): Throwing OutOfMemoryError "Failed to allocate a 65552 byte allocation with 42760 free bytes and 41KB until OOM, target footprint 201326592, growth limit 201326592" (VmSize 24765028 kB)
W/.news_app_admi( 4675): Throwing OutOfMemoryError "Failed to allocate a 65552 byte allocation with 128 free bytes and 128B until OOM, target footprint 201326592, growth limit 201326592" (VmSize 24765028 kB)
W/.news_app_admi( 4675): Throwing OutOfMemoryError "Failed to allocate a 65552 byte allocation with 42192 free bytes and 41KB until OOM, target footprint 201326592, growth limit 201326592" (VmSize 24765028 kB)
W/.news_app_admi( 4675): Throwing OutOfMemoryError "Failed to allocate a 65552 byte allocation with 7832 free bytes and 7832B until OOM, target footprint 201326592, growth limit 201326592" (VmSize 24765028 kB)
W/.news_app_admi( 4675): Throwing OutOfMemoryError "Failed to allocate a 8208 byte allocation with 39464 free bytes and 38KB until OOM, target footprint 201326592, growth limit 201326592; giving up on allocation because <1% of heap free after GC." (VmSize 24765028 kB)
W/.news_app_admi( 4675): Throwing OutOfMemoryError "Failed to allocate a 65552 byte allocation with 33928 free bytes and 33KB until OOM, target footprint 201326592, growth limit 201326592" (VmSize 24765028 kB)
W/.news_app_admi( 4675): Throwing OutOfMemoryError "Failed to allocate a 65552 byte allocation with 16 free bytes and 16B until OOM, target footprint 201326592, growth limit 201326592" (VmSize 24765028 kB)
W/.news_app_admi( 4675): Throwing OutOfMemoryError "Failed to allocate a 24 byte allocation with 24640 free bytes and 24KB until OOM, target footprint 201326592, growth limit 201326592; giving up on allocation because <1% of heap free after GC." (VmSize 24765028 kB)
W/.news_app_admi( 4675): Throwing OutOfMemoryError "Failed to allocate a 65552 byte allocation with 13512 free bytes and 13KB until OOM, target footprint 201326592, growth limit 201326592" (VmSize 24765028 kB)
W/.news_app_admi( 4675): Throwing OutOfMemoryError "Failed to allocate a 65548 byte allocation with 8424 free bytes and 8424B until OOM, target footprint 201326592, growth limit 201326592" (VmSize 24765028 kB)
W/.news_app_admi( 4675): Throwing OutOfMemoryError "Failed to allocate a 65548 byte allocation with 7440 free bytes and 7440B until OOM, target footprint 201326592, growth limit 201326592" (VmSize 24765028 kB)
W/.news_app_admi( 4675): Throwing OutOfMemoryError "Failed to allocate a 8208 byte allocation with 7944 free bytes and 7944B until OOM, target footprint 201326592, growth limit 201326592" (VmSize 24765636 kB)
W/.news_app_admi( 4675): Throwing OutOfMemoryError "Failed to allocate a 32 byte allocation with 11080 free bytes and 10KB until OOM, target footprint 201326592, growth limit 201326592; giving up on allocation because <1% of heap free after GC." (VmSize 24766244 kB)
W/.news_app_admi( 4675): Throwing OutOfMemoryError "Failed to allocate a 8208 byte allocation with 9016 free bytes and 9016B until OOM, target footprint 201326592, growth limit 201326592; giving up on allocation because <1% of heap free after GC." (VmSize 24766244 kB)
W/.news_app_admi( 4675): Throwing OutOfMemoryError "Failed to allocate a 65552 byte allocation with 28512 free bytes and 27KB until OOM, target footprint 201326592, growth limit 201326592" (VmSize 24776836 kB)
W/.news_app_admi( 4675): Throwing OutOfMemoryError "Failed to allocate a 32 byte allocation with 21328 free bytes and 20KB until OOM, target footprint 201326592, growth limit 201326592; giving up on allocation because <1% of heap free after GC." (VmSize 24776836 kB)
W/.news_app_admi( 4675): Throwing OutOfMemoryError "Failed to allocate a 65552 byte allocation with 29488 free bytes and 28KB until OOM, target footprint 201326592, growth limit 201326592" (VmSize 24780484 kB)
W/.news_app_admi( 4675): Throwing OutOfMemoryError "Failed to allocate a 8208 byte allocation with 5896 free bytes and 5896B until OOM, target footprint 201326592, growth limit 201326592" (VmSize 24781092 kB)
W/.news_app_admi( 4675): Throwing OutOfMemoryError "Failed to allocate a 65552 byte allocation with 27128 free bytes and 26KB until OOM, target footprint 201326592, growth limit 201326592" (VmSize 24782916 kB)
W/.news_app_admi( 4675): Throwing OutOfMemoryError "Failed to allocate a 65552 byte allocation with 128 free bytes and 128B until OOM, target footprint 201326592, growth limit 201326592" (VmSize 24782916 kB)
W/.news_app_admi( 4675): Throwing OutOfMemoryError "Failed to allocate a 65552 byte allocation with 25240 free bytes and 24KB until OOM, target footprint 201326592, growth limit 201326592" (VmSize 24782916 kB)
W/.news_app_admi( 4675): Throwing OutOfMemoryError "Failed to allocate a 256 byte allocation with 16 free bytes and 16B until OOM, target footprint 201326592, growth limit 201326592" (VmSize 24796516 kB)
W/.news_app_admi( 4675): Throwing OutOfMemoryError "Failed to allocate a 64 byte allocation with 24 free bytes and 24B until OOM, target footprint 201326592, growth limit 201326592" (VmSize 24796516 kB)`

**Comment by darshankawar** [comment]
@kavyabhargava 
There's similar open issue describing your case, https://github.com/flutter/flutter/issues/62118, please follow-up in it for further updates. Closing this as a duplicate.

**Comment by kavyabhargava** [comment]
Hey no-one has responded to that thread and I saw a lot of people facing the same issue in other forums too. Is there a fix for it ?? What can I do ??
