### ISSUE TITLE
It takes about 500 milliseconds on the linux touch screen to trigger the sliding event, which feels like the UI is stuck

### ISSUE THREAD

**Issue by heheyajie** [flutter/flutter#103564]
Situation Analysis
Using GestureDetector to monitor events, the click event can be triggered immediately, and the sliding event will be triggered about 500 milliseconds after the click event is triggered, causing the UI to freeze.
# this is the code

         GestureDetector( 
            child: Container(
              width: 500,
              height: 500,
              color: Colors.red,
            ),
            onPanStart:(e){
              print("onPanStart");
            },
            onPanUpdate: (e) {
              print("onPanUpdate");
            },
            onPanDown: (e){
              print("onPanDown");
            }, 
          ),

**Comment by darshankawar** [comment]
@heyajieGitHub 
For better reading, please file issue written in English, so we don't need to translate it later.
For your issue, please provide `flutter doctor -v`, a complete minimal reproducible code sample, along with actual vs expected result to get an idea of the issue you are reporting.

Also, provide what platform are you running this on in Linux (ex: mobile, web or desktop).

**Comment by heyajieGitHub** [comment]
Hi @darshankawar 

[✓] Flutter (Channel stable, 2.10.1, on Kylin V10 SP1 5.4.18-35-generic, locale zh_CN.UTF-8)
    • Flutter version 2.10.1 at /home/em/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db747aa133 (3 个月前), 2022-02-09 13:57:35 -0600
    • Engine revision ab46186b24
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4kylin1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] VS Code (version 1.66.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.40.0

[✓] Connected device (1 available)
    • Linux (desktop) • linux • linux-arm64 • Kylin V10 SP1 5.4.18-35-generic

[!] HTTP Host Availability
    ✗ HTTP host https://maven.google.com/ is not reachable. Reason: An error occurred while checking the HTTP host: Connection timed out
    ✗ HTTP host https://cloud.google.com/ is not reachable. Reason: An error occurred while checking the HTTP host: Connection timed out

! Doctor found issues in 2 categories.


This is run on the Linux desktop and used by the touch screen

Now, after touching the screen with your finger, trigger OnTap first. Press and hold for about 500 milliseconds, and then trigger onpanstart / onpanupdate

It is expected that onpanstart / onpanupdate can be triggered when the finger touches the screen

**Comment by darshankawar** [comment]
@heheyajie 
Please upgrade to latest stable if possible and try again to see if behavior still persists. If so, provide complete minimal reproducible code sample.
