### ISSUE TITLE
chrome-infra-packages.appspot.com is not accessible behind some corporate proxy

### ISSUE THREAD

**Issue by evenremy** [flutter/flutter#103591]
I am behind a corporate proxy and chrome-infra-packages.appspot.com is blacklisted for unknown reasons... I am able to fetch it manually (other network) but I don't how to put it working.

## Steps to Reproduce

1. use 'flutter run' or 'flutter precache'

## Logs

<details>
<summary>Logs</summary>

#> flutter run
Downloading Web SDK...                                              4,2s
Downloading CanvasKit...                                           224ms
Downloading CanvasKit...                                           219ms
Failed to download
https://chrome-infra-packages.appspot.com/dl/flutter/web/canvaskit_bundle/+/8MSYGWVWzrTJIoVL00ZquruZs-weuwLBy1kt1AawJiIC
. Ensure you have network connectivity and then try again.
Exception: 403

```
```

flutter doctor -v
[✓] Flutter (Channel stable, 2.10.5, on Microsoft Windows [version 10.0.19042.1645], locale fr-FR)
    • Flutter version 2.10.5 at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (3 weeks ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\remy.even\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at:
      C:\Users\remy.even\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\203.7784292\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Build Tools 2019 16.10.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
    • Visual Studio Build Tools 2019 version 16.10.31515.178
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2020.3)
    • Android Studio at C:\Users\remy.even\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\203.7784292
    • Flutter plugin version 64.1.1
    • Dart plugin version 203.8452
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2021.3
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code, 64-bit edition (version 1.66.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Proxy Configuration
    • HTTP_PROXY is set
    • NO_PROXY is localhost,127.0.0.1,::1
    • NO_PROXY contains localhost
    • NO_PROXY contains ::1
    • NO_PROXY contains 127.0.0.1

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [version 10.0.19042.1645]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 94.0.4606.71
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 100.0.1185.29

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

</details>

**Comment by darshankawar** [comment]
@evenremy 
Since it seems to be related to proxy, you'll need to reach out to your company security team for it. Don't think Flutter can do anything for this case.
Closing from here.

**Comment by evenremy** [comment]
I am looking for a solution to manage canvasKit manually to avoid
proxy/firewall problems.

I can't ask to unblock without a very good reason (it's blacklisted).

Is there any workaround to manage that or I have stop trying to use Flutter
?

Le jeu. 12 mai 2022, 11:57, darshankawar ***@***.***> a
écrit :

**Comment by evenremy** [comment]
Is it possible to reopen this issue ? 
For now Flutter is the only Framework that I am unable to use, there is always a workaround to avoid remote dependency...

Thanks
