### ISSUE TITLE
iOS simulator is (still) VERY jerky and slow

### ISSUE THREAD

**Issue by deborah-ufw** [flutter/flutter#10359]
Related to #6135, which is closed.

I just followed all of the steps to install and open a flutter example app on my Mac OSX Sierra (up to date as of two hours ago).  Flutter doctor confirms all dependencies are installed and up to date (except for iOS deploy but this is because of a flutter doctor bug - see issue #8676, this also should be re-opened).

flutter_gallery opens but the animation looks like about 1/10 of the fps it should be. It's hideous.

**Comment by eseidelGoogle** [comment]
Probably https://github.com/flutter/flutter/issues/9366.  The iOS simulator runs a different configuration of Flutter (since it doesn't have a GPU) and there are still some bugs in that configuration.

**Comment by sethladd** [comment]
Thanks for the feedback and for opening this issue!

**Comment by deborah-ufw** [comment]
thank you Flutter team :)

**Comment by tvolkert** [comment]
Closing this as a dup of https://github.com/flutter/flutter/issues/6135 (which has been re-opened and has more recent discussion).
