### ISSUE TITLE
Flutter SDK doesn't include or precache the darwin-arm64 engine

### ISSUE THREAD

**Issue by 0xchase** [flutter/flutter#103563]
Hello,

I'm attempting to build on apple silicon with 3.0.0 (using a custom embedder). When building I get the following error.

```
Flutter artifact location path at "/Users/chasekanipe/Software/flutter/bin/cache/artifacts/engine/darwin-arm64-release" does not exist! Try running 'flutter precache'
```

Looking in the artifacts/engine directory confirms that it contains the `darwin-x64` folders but not the `darwin-arm64` folders after running `flutter precache -a`. 

My apologies if I'm doing something incorrectly.

**Comment by darshankawar** [comment]
> I'm attempting to build on apple silicon with 3.0.0 (using a custom embedder). When building I get the following error.

Can you provide `flutter doctor -v` and a reproducible code sample along with steps to replicate that shows this log ?

**Comment by 0xchase** [comment]
Further evidence: if I diff the x86_64 and arm versions of the macOS SDK artifacts, there is no difference.

```
$ diff --brief --recursive flutter_x86/bin/cache/artifacts/ flutter_arm/bin/cache/artifacts/
$
```

Unless I'm missing something, I'm astounded this hasn't gotten a bunch of reports. The `3.0.0` SDK seems to not include an engine for Apple Silicon.

**Comment by 0xchase** [comment]
Ah, I see. The engine is built into a universal binary. In that case, the issue appears to be in NativeShell. Closing this issue.
