### ISSUE TITLE
Roll zlib so that -Wno-deprecated-non-prototype isn't needed

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#103568]
With newer clang versions, compiling the current version of zlib results in errors like:
```
../../third_party/zlib/contrib/optimizations/inflate.c:145:13: error: a function declaration without a prototype is deprecated in all versions of C and is not supported in C2x [-Werror,-Wdeprecated-non-prototype]
int ZEXPORT inflateReset(strm)
```

Presumably, in future versions of clang, it won't be possible to disable this warning, and support will actually be removed. We should roll to a zlib version where this is not a problem if one exists.

/cc @aam who I think recently rolled our zlib forward.

**Comment by aam** [comment]
Can you please provide some more details on what newer clang version you used, where did you get it from, how did you get the errors.

I see some changes landing to zlib related to that (https://chromium.googlesource.com/chromium/src/third_party/zlib/+/b55552138c566f8f861eadb0b6cb44deea5d24fe), nothing that touches this function though in recent history.

**Comment by zanderso** [comment]
I'm working on a toolchain roll here https://github.com/flutter/engine/pull/33284.

**Comment by aam** [comment]
Rolling zlib in dart sdk a little further https://dart.googlesource.com/sdk/+/862a2c6caf86ae18e1adca956fce23ca2d65214a

**Comment by zanderso** [comment]
We've rolled zlib, and I can't find any instances of the warning flag in the issue title in the tree, so I'll close this.
