### ISSUE TITLE
Update segmented buttons to support Material 3

### ISSUE THREAD

**Issue by darrenaustin** [flutter/flutter#103529]
As part of the [Material 3 specification](https://m3.material.io/components/segmented-buttons/overview) there are updates to the Segmented Button visuals:

<img width="373" alt="Screen Shot 2022-05-11 at 1 09 18 PM" src="https://user-images.githubusercontent.com/19588/167938461-c6ca8fc9-b014-4ea0-939b-b25cd0445432.png">

The Flutter Material library currently has a `ToggleButtons` class that we should either update to support Material 3 or build a new widget if they are not close enough in functionality.

**Comment by bernaferrari** [comment]
It would be nice if the API aligned with the Cupertino segmented control, it looks probably more similar than `ToggleButtons`.

**Comment by rydmike** [comment]
Probably better to build a new widget, can then also improve its API and features, plus name align it with the M3 name too.

ToggleButtons have some limitations, like does not implement `VisualDensity` and it is based on `RawMaterialButton`. Then add oddities like the border is drawn outside its content height/width constraints. It can be themed fairly close the `SegmentedButtons` look, but not quite.

**Comment by TahaTesser** [comment]
cc: @rydmike 

Thanks for the feedback!

> ToggleButtons have some limitations, like does not implement VisualDensity

This looks to be true.

> and it is based on RawMaterialButton.

 `ToggleButtons` no longer contain `RawMaterialButton`. (I've replaced it in https://github.com/flutter/flutter/pull/101760)

> Then add oddities like the border is drawn outside its content height/width constraints. It can be themed fairly close the SegmentedButtons look, but not quite.

Investigating into this.

**Comment by TahaTesser** [comment]
cc: @rydmike @darrenaustin @HansMuller 

After reading [Segmented buttons sepcs](https://m3.material.io/components/segmented-buttons/overview) and some native Android testing.

- In terms of functionality, there is no change. The single and multi-select functionality exist in both M2 and M3 versions
(there is a check to toggle between single and multi-select on Android, we can easily introduce this toggle if needed)
- There is a new optional check icon to indicate the selected state.
- Layout height is a little taller.
- Slight default Shape change and minor typography changes. 

Aside from minor improvements stated in https://github.com/flutter/flutter/issues/103529#issuecomment-1151700201 which are already required addressing in M2 ToggleButtons, there is no significant difference. 

I will defer to other team members for the widget name update. (In my testing I noticed even Android API doesn't have an updated name for SegementedButtons, it simply refers to `MaterialButtonToggleGroup` with different style attributes for M2 and M3).

We also didn't introduce newly named widgets for regular buttons, for instance `Filled` or `Filled Tonal`, see [Material 3 button types
](https://master-api.flutter.dev/flutter/material/ButtonStyle-class.html)

**Comment by bernaferrari** [comment]
Yes, there is FilledButton now. https://github.com/flutter/flutter/pull/107382

**Comment by darrenaustin** [comment]
After looking more closely at this, I think we should create a new `SegmentedButton` API that combines the best of the `ToggleButton` and `CupertinoSegmentedControl` APIs. It would of course be driven by M3 tokens by default, but would hopefully be configurable enough to be able to pull off Cupertino styles with just theme data. I have already started work on this, so if you don't mind @TahaTesser, I will assign this to myself.

**Comment by rydmike** [comment]
Thanks @darrenaustin, I also think that is a good call. Looking forward to seeing the results! 👍🏻

**Comment by TahaTesser** [comment]
It sounds. Definitely a bigger project, thanks for taking this.
