### ISSUE TITLE
Flutter doctor suggests Android Studio is required

### ISSUE THREAD

**Issue by DanTup** [flutter/flutter#10352]
It seems that Android Studio is not required to do flutter dev (I'm trying to add support for [Dart Code](https://marketplace.visualstudio.com/items?itemName=DanTup.dart-code)) but the output of `flutter doctor` makes it seem like it is:

```text
[X] Android Studio (not installed)
    • Android Studio not found. Download from https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).
```

I think it'd be better to tweak this to make it clearer that it's optional. I was hoping to use `flutter doctor` in my IDE integration to help the user get set up, but it doesn't seem right to fail the check and ask them to install another IDE when they've specifically chosen to use Code for development.

**Comment by sethladd** [comment]
Thanks for the feedback! It looks like we're likely to change this, tracking over here: https://github.com/flutter/flutter/issues/9747

The reason you see that output: right now, Android Studio is how Flutter expects you to get the Android SDK. However, after further investigation, we believe we can provide a path that doesn't _require_ Android Studio.

I agree that we shouldn't make Android Studio appear strictly _required_. All that is required is the Android SDK and Gradle.

**Comment by jjgh** [comment]
But... system requirements at flutter.io say that:

> Note: Flutter relies on a full installation of Android Studio to supply its Android platform dependencies. However, you can write your Flutter apps in a number of editors; a later step will discuss that.

https://flutter.io/setup-windows/#system-requirements

So did this end up in a direction where we are again required to install Android Studio? 
Or is the setup guide in need of an update?

**Comment by zoechi** [comment]
Duplicate of #25719

**Comment by zoechi** [comment]
I see. This is why #9747 is mentioned above.

**Comment by iapicca** [comment]
Hi @DanTup  is this issue still meant to be open?

**Comment by DanTup** [comment]
I think this was dealt with by #25269. The output is now only "partial" instead of "missing":

```
[!] Android Studio (not installed)
```

I think this is reasonable for now. Users are generally expected to have Android Studio to get the SDK (it's not required, but it's certainly easiest - I think it's the only way to get a GUI for updating SDK bits, for example) and there's an issue open about getting the SDK separately, so I don't think there's anything to do for this one.
