### ISSUE TITLE
Update `Switch` to support Material 3

### ISSUE THREAD

**Issue by darrenaustin** [flutter/flutter#103536]
As part of the [Material 3 specification](https://m3.material.io/components/switch/overview) there are updates to the Switch's visuals:

<img width="253" alt="Screen Shot 2022-05-11 at 1 53 27 PM" src="https://user-images.githubusercontent.com/19588/167945751-775e7e62-d412-4ee4-aafc-89fbfe73d912.png">

We need to update the existing `Switch` class in the Flutter Material library to support this.

**Comment by guidezpl** [comment]
This should require #81564

**Comment by tmaihoff** [comment]
Is there an update on this? A timeplan?

**Comment by QuncCccccc** [comment]
> Is there an update on this? A timeplan?

Hi! I'm working on it and will create a pr once it's ready. Thanks for asking!

**Comment by mavyfaby** [comment]
> > Is there an update on this? A timeplan?
> 
> Hi! I'm working on it and will create a pr once it's ready. Thanks for asking!

Is there any way that I can help with this?

**Comment by guidezpl** [comment]
Great work @QuncCccccc! However, I noticed the layout (thumb size)  and motion isn't quite to spec

Expected | Actual |
--- | --- | 
![image](https://user-images.githubusercontent.com/6655696/189622674-1ec7cbda-1603-4fd1-a87c-db56c1f14dca.png) | ![image](https://user-images.githubusercontent.com/6655696/189622937-771a1078-9870-45be-841d-f1660f299cef.png)

Do you plan on addressing this in a separate PR?

**Comment by MaxYablochkin** [comment]
@guidezpl 
Will Flutter exactly repeat this behavior of the switch?
![unnamed (1)](https://user-images.githubusercontent.com/102767277/191384842-bb77750f-239a-4bc7-8274-6ffc2f312bd0.png)

**Comment by QuncCccccc** [comment]
> @guidezpl
> 
> 1. Will Flutter exactly repeat this behavior of the switch?
>    ![unnamed (1)](https://user-images.githubusercontent.com/102767277/191384842-bb77750f-239a-4bc7-8274-6ffc2f312bd0.png)
> 2. If we talk about this switch in Flutter, then when it reaches the middle, the circle begins to decrease in radius, and then returns to the radius, depending on where the switch goes.
>    What about the difference regarding specification?
>    Is Flutter trying to be different?
>    ![image](https://user-images.githubusercontent.com/102767277/191387896-b0f43364-6c7e-4f66-9c58-62707131b589.png)
>    https://firebasestorage.googleapis.com/v0/b/design-spec/o/projects%2Fm3%2Fimages%2Fl1xillgu-00_Deck_Tap_Drag.mp4?alt=media&token=c7599d2c-0cbc-47b7-b58a-2a3f95e51c8c

Thanks for catching this! The decreasing radius in the middle comes from the implementation of Material 2, just raised an issue for this and will fix it soon. https://github.com/flutter/flutter/issues/112026

**Comment by MaxYablochkin** [comment]
Flutter
![IMG_20220921_060215.jpg](https://user-images.githubusercontent.com/102767277/191405316-78d9c1cd-d83b-4363-923b-e0d228bd2746.jpg)
![IMG_20220921_060138.jpg](https://user-images.githubusercontent.com/102767277/191405344-5e3dfbe0-0658-45eb-8597-2b0fd2d67e25.jpg)

Native Android
![IMG_20220921_060402.jpg](https://user-images.githubusercontent.com/102767277/191405411-a8c00c17-82d8-4af9-8a43-fff5a59e23bd.jpg)
![IMG_20220921_060302.jpg](https://user-images.githubusercontent.com/102767277/191405429-a0bc8b15-5213-4b43-9fbb-0317061be6b3.jpg)

There are also a few visual inconsistencies, for example, when the switch is off and pressed at the same time, the switch does not repaint in dark gray, and the same applies to the on, pressed state, it does not repaint in the color of the shade, but remains just white.  The switch does not animate smoothly when raised when held, and also, in my opinion, there is no accompanying InkRipple animation behind the switch.

**Comment by MaxYablochkin** [comment]
There is a difference between web on android and web on windows, and it is a little surprising where the second one shows the correct display of colors that I described above.

**Comment by mavyfaby** [comment]
Is there a separate pull request for the additional changes?

**Comment by QuncCccccc** [comment]
> Is there a separate pull request for the additional changes?

Yes, I will raise a pr for these changes soon.

**Comment by huage2580** [comment]
great work!  

Will it be released in version 3.5.0？

**Comment by bernaferrari** [comment]
You need to check the beta that includes this commit, so I don't know. But it's very recent, so I would wait for an additional 2-4 months.

**Comment by ArishSultan** [comment]
There is a sligh inconsistency in animation, if you drag the thumb halfway and then release the "pan" then instead of continuing  animation from that drag position there is slight glitch which feels like the thumb starts animation from the start instead of the position where drag was release.
