### ISSUE TITLE
.pub-cache/hosted/pub.flutter-io.cn/win32-2.3.6/lib/src/structs.g.dart:664:29: Error: Member not found: 'AsciiChar'.       int get AsciiChar => Char.AsciiChar;

### ISSUE THREAD

**Issue by yanwei49** [flutter/flutter#103565]
i upgraded flutter3.0, create a empty project, flutter run
```
error:
    ../../../.pub-cache/hosted/pub.flutter-io.cn/win32-2.3.6/lib/src/structs.g.dart:661:31: Error: Member not found: 'UnicodeChar'.
      int get UnicodeChar => Char.UnicodeChar;
                                  ^^^^^^^^^^^
    ../../../.pub-cache/hosted/pub.flutter-io.cn/win32-2.3.6/lib/src/structs.g.dart:662:38: Error: Setter not found: 'UnicodeChar'.
      set UnicodeChar(int value) => Char.UnicodeChar = value;
                                         ^^^^^^^^^^^
    ../../../.pub-cache/hosted/pub.flutter-io.cn/win32-2.3.6/lib/src/structs.g.dart:664:29: Error: Member not found: 'AsciiChar'.
      int get AsciiChar => Char.AsciiChar;
                                ^^^^^^^^^
    ../../../.pub-cache/hosted/pub.flutter-io.cn/win32-2.3.6/lib/src/structs.g.dart:665:36: Error: Setter not found: 'AsciiChar'.
      set AsciiChar(int value) => Char.AsciiChar = value;
                                       ^^^^^^^^^
```

flutter doctor:
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.1-0.0.pre.20, on macOS 12.0.1 21A559 darwin-arm, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc3)
[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.67.1)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

flutter --version:
Flutter 3.0.1-0.0.pre.20 • channel stable •
https://github.com/flutter/flutter.git
Framework • revision 9740e41036 (75 minutes ago) • 2022-05-12 09:02:05 +0800
Engine • revision d1b9a6938a
Tools • Dart 2.17.0 • DevTools 2.12.2

**Comment by GitHelge** [comment]
Same for me:

Xcode's output:
↳
    Writing result bundle at path:
    	/var/folders/b3/.../temporary_xcresult_bundle
: Error: Member not found: 'UnicodeChar'.
../…/src/structs.g.dart:554
      int get UnicodeChar => Char.UnicodeChar;
                                  ^^^^^^^^^^^
: Error: Setter not found: 'UnicodeChar'.
../…/src/structs.g.dart:555
      set UnicodeChar(int value) => Char.UnicodeChar = value;
                                         ^^^^^^^^^^^
: Error: Member not found: 'AsciiChar'.
../…/src/structs.g.dart:557
      int get AsciiChar => Char.AsciiChar;
                                ^^^^^^^^^
: Error: Setter not found: 'AsciiChar'.
../…/src/structs.g.dart:558
      set AsciiChar(int value) => Char.AsciiChar = value;
                                       ^^^^^^^^^

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.0, on macOS 12.1 21C52 darwin-x64, locale de-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.67.1)
[✓] Connected device (4 available)
[✓] HTTP Host Availability

**Comment by jccy2106** [comment]
I am encountering the same problem.

**Comment by darshankawar** [comment]
Since the version is upgraded, there might be some changes that packages may not be compatible with and same could be case with `win32-2.3.6`. So running `flutter pub upgrade` or `pod update` so that all packages are using latest versions could be a solution as mentioned above. Try the same and let us know if it fixes these errors or not.

**Comment by yanwei49** [comment]
> Since the version is upgraded, there might be some changes that packages may not be compatible with and same could be case with `win32-2.3.6`. So running `flutter pub upgrade` or `pod update` so that all packages are using latest versions could be a solution as mentioned above. Try the same and let us know if it fixes these errors or not.

I use the fluent SDK managed by sourcetree

**Comment by jccy2106** [comment]
> Since the version is upgraded, there might be some changes that packages may not be compatible with and same could be case with `win32-2.3.6`. So running `flutter pub upgrade` or `pod update` so that all packages are using latest versions could be a solution as mentioned above. Try the same and let us know if it fixes these errors or not.

Running `flutter pub upgrade` worked for me. Thanks.

**Comment by morrowyn** [comment]
Can you try to remove your `.pub-cache` inside your flutter sdk folder and then rerun the `flutter pub upgrade` ?

**Comment by zubisofts** [comment]
Running flutter upgrade solved the issue for me, you can ignore warnings that won't affect your project.

**Comment by yanwei49** [comment]
> Running `flutter pub upgrade` worked for me. Thanks

Running flutter pub upgrade worked for me. Thanks

**Comment by yanwei49** [comment]
> Running`flutter upgrade`solved the issue for me, you can ignore warnings that won't affect your project.

Running flutter pub upgrade worked for me. Thanks

**Comment by yanwei49** [comment]
> > Since the version is upgraded, there might be some changes that packages may not be compatible with and same could be case with `win32-2.3.6`. So running `flutter pub upgrade` or `pod update` so that all packages are using latest versions could be a solution as mentioned above. Try the same and let us know if it fixes these errors or not.
> 
> Running `flutter pub upgrade` worked for me. Thanks.

Running flutter pub upgrade worked for me. Thanks

**Comment by darshankawar** [comment]
Closing this as above seems to resolve the issue.
