### ISSUE TITLE
can't find cocoapods 

### ISSUE THREAD

**Issue by Tonigt** [flutter/flutter#103590]
flutter doctor --verbose

[✓] Flutter (Channel stable, 3.0.0, on macOS 12.3.1 21E258 darwin-x64, locale
    zh-Hans-CN)
    • Flutter version 3.0.0 at /Users/tonight/flutter_master/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ee4e09cce0 (2 days ago), 2022-05-09 16:45:18 -0700
    • Engine revision d1b9a6938a
    • Dart version 2.17.0
    • DevTools version 2.12.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version
    30.0.0-rc4)
    • Android SDK at /Users/tonight/Library/Android/sdk
    • Platform android-31, build-tools 30.0.0-rc4
    • ANDROID_HOME = /Users/tonight/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.66.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Connected device (2 available)
    • iPhone (mobile) • 82701af5539171b5da4b6da05c38f53597c13703 • ios        •
      iOS 14.5.1 18E212
    • macOS (desktop) • macos                                    • darwin-x64 •
      macOS 12.3.1 21E258 darwin-x64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

git --version

git version 2.33.0

flutter run -v 

[+12131 ms] Exception: CocoaPods not installed or not in valid state.
[  +10 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:601:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1183:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:94:3)
           <asynchronous suspension>

so why can't find cocoapods but flutter doctor --verbose has no problem

**Comment by darshankawar** [comment]
@Tonigt 
Check if [this](https://github.com/flutter/flutter/issues/93475#issuecomment-966851919) solution works for you.

**Comment by Tonigt** [comment]
in cmd flutter run -v, it's working,  but in Android Studio can't throw cocoapods not install

**Comment by Tonigt** [comment]
gem list cocoapods

*** LOCAL GEMS ***

cocoapods (1.11.3)
cocoapods-core (1.11.3)
cocoapods-deintegrate (1.0.5)
cocoapods-downloader (1.6.3)
cocoapods-plugins (1.0.0)
cocoapods-search (1.0.1)
cocoapods-trunk (1.6.0)
cocoapods-try (1.2.0)

**Comment by darshankawar** [comment]
This doesn't seem to be Flutter issue. Please reach out to cocoapods repo for further resolution.
Closing from here.
