### ISSUE TITLE
Can not build the android application after upgrading to flutter 3.0

### ISSUE THREAD

**Issue by petodavid** [flutter/flutter#103578]
flutter run --flavor dev --no-sound-null-safety

FAILURE: Build failed with an exception.

* Where:
Script '/Users/petodavid/Developer/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 1156

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDevDebug'.
> Process 'command '/Users/petodavid/Developer/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 12s
Exception: Gradle task assembleDevDebug failed with exit code 1

**Comment by darshankawar** [comment]
@petodavid 
Can you provide `flutter doctor -v` and `flutter run --flavor dev --no-sound-null-safety -v` ?
The log will be huge so you can put that in a text file and share it here.

**Comment by petodavid** [comment]
Here is the result of Flutter doctor -v ->
[FluttreRunResult.txt](https://github.com/flutter/flutter/files/8676919/FluttreRunResult.txt)

Here is the result of  flutter run --flavor dev --no-sound-null-safety -v  ->  
[FlutterDoctorResult.txt](https://github.com/flutter/flutter/files/8676885/FlutterDoctorResult.txt)

**Comment by UCetinkaya94** [comment]
I'm having the same issue. I deleted and regenerated the Android folder, reinstalled Flutter, nothing works. Had to downgrade back to 2.10.5

**Comment by petodavid** [comment]
I had to downgrade also, pls let me know if u find a solution

**Comment by BautizarCodigo** [comment]
I had a simpler  issue when I upgraded to 3.0, upgraded via the terminal on windows and Mac for the same project, broke both projects after a lot of troubleshooting I just downloaded 2.10 and replaced my flutter folder and I could compile again.

**Comment by darshankawar** [comment]
@petodavid 
from the verbose log you shared, all the errors are pointing to third party plugins:

flutter_awesome_select
percent_indicator-4.0.1
macos_ui-1.3.0
infinite_scroll_pagination-3.1.0
another_flushbar-1.10.28

which probably may not be compatible with latest stable 3.0 changes, so you'll probably need to reach out to plugin owners for further resolution.

**Comment by tomk9** [comment]
@petodavid your error comes from `appspector-0.8.1`.
