### ISSUE TITLE
Linux installation instructions talk about Xcode and brew

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#10354]
https://flutter.io/setup-linux/ shows the following example output from `flutter doctor`:

```
✗ Xcode end user license agreement not signed; open Xcode or run the command 'sudo xcodebuild -license'.

✗ Brew not installed; use this to install tools for iOS device development.

  Download brew at http://brew.sh/.
```

Instead, we should show a sample Linux output.

/cc @sethladd

**Comment by LarkAscending** [comment]
We USED to have only the Linux content! Somehow it got clobbered in the effort to split everything and make it platform-specific. Because most folks around us have every single dependency in place on Linux, it's difficult to source this info! Hang tight...

**Comment by LarkAscending** [comment]
Closed with https://github.com/flutter/website/pull/581
