### ISSUE TITLE
【share_preference】 Multiple .plist in Library/Preferences of my app?

### ISSUE THREAD

**Issue by OHeroJ** [flutter/flutter#103588]
iOS sandbox Library/Preferences

The name that assign to the file is "bundleId".plist.XXXXXX  

same problem: [https://developer.apple.com/forums/thread/116611](https://developer.apple.com/forums/thread/116611)

![image](https://user-images.githubusercontent.com/12316547/168023255-2e81e826-8545-458a-873f-4aae026fc69c.png)

**Comment by darshankawar** [comment]
@OHeroJ 
Does the apple forum thread help to debug further ?
Is there a way to replicate this locally and provide code sample for same ?
