### ISSUE TITLE
Update `BottomAppBar` to support Material 3

### ISSUE THREAD

**Issue by darrenaustin** [flutter/flutter#103530]
As part of the [Material 3 specification](https://m3.material.io/components/bottom-app-bar/overview) there are updates to the Bottom app bar's visuals:

<img width="465" alt="Screen Shot 2022-05-11 at 1 22 28 PM" src="https://user-images.githubusercontent.com/19588/167941127-4d481d06-3f41-42cc-988a-5fc90fb0f0bf.png">

We should update the `BottomAppBar` classes to support this Material 3 look.

**Comment by elbeicktalat** [comment]
#106525 result

<img src="https://user-images.githubusercontent.com/59793332/175773827-e95432f3-b3e8-414f-8524-3238183e73a2.png" width="400"/>

https://user-images.githubusercontent.com/59793332/175774401-54c9d362-e48c-4bf9-beb8-48a7800975b8.mp4

<details>
<summary>Get code example</summary>
Requires #106525 
<br>

```dart
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';

void main() {
  runApp(const BottomAppBarDemo());
}

class BottomAppBarDemo extends StatefulWidget {
  const BottomAppBarDemo({super.key});

  @override
  State createState() => _BottomAppBarDemoState();
}

class _BottomAppBarDemoState extends State<BottomAppBarDemo> {
  late ScrollController _controller;
  bool _showFab = true;
  bool _isElevated = true;
  bool _isVisible = true;

  FloatingActionButtonLocation get _fabLocation => _isVisible
      ? FloatingActionButtonLocation.endContained
      : FloatingActionButtonLocation.endFloat;

  void _onShowFabChanged(bool value) {
    setState(() {
      _showFab = value;
    });
  }

  void _onElevatedChanged(bool value) {
    setState(() {
      _isElevated = value;
    });
  }

  static const List<Color> colors = <Color>[
    Colors.yellow,
    Colors.orange,
    Colors.pink,
    Colors.purple,
    Colors.cyan,
  ];

  static final List<Widget> items = List<Widget>.generate(
    colors.length,
    (int index) => Container(color: colors[index], height: 150.0),
  ).reversed.toList();

  void _listen() {
    final ScrollDirection direction = _controller.position.userScrollDirection;
    if (direction == ScrollDirection.forward) {
      _show();
    } else if (direction == ScrollDirection.reverse) {
      _hide();
    }
  }

  void _show() {
    if (!_isVisible) {
      setState(() => _isVisible = true);
    }
  }

  void _hide() {
    if (_isVisible) {
      setState(() => _isVisible = false);
    }
  }

  void _addNewItem() {
    setState(() {
      items.insert(
        0,
        Container(
          height: 150.0,
          color: colors[items.length % 5],
        ),
      );
    });
  }

  @override
  void initState() {
    super.initState();
    _controller = ScrollController();
    _controller.addListener(_listen);
  }

  @override
  void dispose() {
    _controller.removeListener(_listen);
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(
        useMaterial3: true,
        colorScheme: const ColorScheme.light(
          primary: Color(0xffffdad9),
          onPrimary: Color(0xff2c1515),
          surface: Color(0xfff4eaeb),
          onSurface: Color(0xff544343),
        ),
      ),
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Bottom App Bar Demo'),
        ),
        body: ListView(
          controller: _controller,
          children: <Widget>[
            SwitchListTile(
              title: const Text('Floating Action Button'),
              value: _showFab,
              onChanged: _onShowFabChanged,
            ),
            SwitchListTile(
              title: const Text('Bottom App Bar Elevation'),
              value: _isElevated,
              onChanged: _onElevatedChanged,
            ),
            ...items,
          ],
        ),
        floatingActionButton: _showFab
            ? FloatingActionButton(
                onPressed: () => _addNewItem(),
                tooltip: 'Add New Item',
                child: const Icon(Icons.add),
              )
            : null,
        floatingActionButtonLocation: _fabLocation,
        bottomNavigationBar: _DemoBottomAppBar(_isElevated, _isVisible),
      ),
    );
  }
}

class _DemoBottomAppBar extends StatelessWidget {
  const _DemoBottomAppBar(this.isElevated, this.isVisible);

  final bool isElevated;
  final bool isVisible;

  @override
  Widget build(BuildContext context) {
    return AnimatedContainer(
      duration: const Duration(milliseconds: 200),
      height: isVisible ? 80.0 : 0,
      child: BottomAppBar(
        elevation: isElevated ? null : 0.0,
        child: Row(
          children: <Widget>[
            IconButton(
              tooltip: 'Open navigation menu',
              icon: const Icon(Icons.more_vert),
              onPressed: () {
                final SnackBar snackBar = SnackBar(
                  content: const Text('Yay! A SnackBar!'),
                  action: SnackBarAction(
                    label: 'Undo',
                    onPressed: () {},
                  ),
                );

                // Find the ScaffoldMessenger in the widget tree
                // and use it to show a SnackBar.
                ScaffoldMessenger.of(context).showSnackBar(snackBar);
              },
            ),
            IconButton(
              tooltip: 'Search',
              icon: const Icon(Icons.search),
              onPressed: () {},
            ),
            IconButton(
              tooltip: 'Favorite',
              icon: const Icon(Icons.favorite),
              onPressed: () {},
            ),
          ],
        ),
      ),
    );
  }
}
```
</details>

**Comment by youngdonkim** [comment]
Thank @elbeicktalat !!!
I will use your code to make my app, and then ask you your code if I would have  questions.

>

**Comment by jibbers42** [comment]
Tagging on a support request for a notch for the new `FloatinActionButton` shape.
![image](https://user-images.githubusercontent.com/797824/193435102-df712573-9491-4d1e-922a-4ae9d0f4ee1b.png)

Would it possible to adapt `CircularNotchedRectangle` to make the correct shape, or maybe a new `FloatingActionButtonNotchedRectangle` that automatically makes the correct shape?

**Comment by angel333** [comment]
> Would it possible to adapt `CircularNotchedRectangle` to make the correct shape, or maybe a new `FloatingActionButtonNotchedRectangle` that automatically makes the correct shape?

Note that "inset" FABs seem to be a Material 2 thing (see [specs](https://material.io/components/app-bars-bottom)). They aren't mentioned in the [Material 3 spec](https://m3.material.io/components/floating-action-button/specs). That being said, I don't know if the Flutter team implements them or not, but I don't expect them to.

**Comment by jibbers42** [comment]
> Note that "inset" FABs seem to be a Material 2 thing (see [specs](https://material.io/components/app-bars-bottom)). They aren't mentioned in the [Material 3 spec](https://m3.material.io/components/floating-action-button/specs). That being said, I don't know if the Flutter team implements them or not, but I don't expect them to.

Ahh, I didn't notice that. It seems the options are either floating or completely contained in the bar.
It's interesting to note that halfway down this page they say don't place a FAB outside of a bottom app bar (floating) https://m3.material.io/components/bottom-app-bar/guidelines
but then on this page every single example is floating https://m3.material.io/components/floating-action-button/guidelines
Or maybe I've missed their point... dunno.

**Comment by angel333** [comment]
> they say don't place a FAB outside of a bottom app bar (floating)

I think they basically wanted to say "if there is a bottom app bar, put FABs there; if there isn't a bottom app bar, put FABs anywhere." But it's worded weirdly and it took me a while to figure out! :-) ... Notice that on the other page, there are no bottom app bars, only navigation bars (which look alike but are different and have different purpose).

**Comment by elbeicktalat** [comment]
> It's interesting to note that halfway down this page they say don't place a FAB outside of a bottom app bar (floating) https://m3.material.io/components/bottom-app-bar/guidelines
but then on this page every single example is floating https://m3.material.io/components/floating-action-button/guidelines

@jibbers42 you are right,
but we haven't made this forced, because we'll increase the complexity of the Scaffold, since we set/get that position info from it. We also allows freedom in the choose.  Thanks for your comment and sorry for the delay in responding.  Nice coding!

**Comment by florian-obernberger** [comment]
> It's interesting to note that halfway down this page they say don't place a FAB outside of a bottom app bar (floating) https://m3.material.io/components/bottom-app-bar/guidelines
but then on this page every single example is floating https://m3.material.io/components/floating-action-button/guidelines
Or maybe I've missed their point... 

I just quickly want to add to this. They are in fact not conflicting themselves. What you see in the second page you mentioned is a BottomNavigationBar, not a BottomAppBar. They are different as in a BottomNavigationBar provides you with destinations of the App whereas a BottomAppBar features actions that can be performed on this page. (This could be to manage selected items or to create a new blog post).

I hope this helps with the confusion, @jibbers42!

**Comment by jibbers42** [comment]
Yeah, I didn't realize it was a different bar when writing that.

However, there does seem to be a conflict, or at least confusion, between https://m3.material.io/components/floating-action-button/guidelines#c45eaa7c-9d41-461f-8894-f8e222795bdd and https://m3.material.io/components/navigation-bar/guidelines#c5a1eb4e-7837-4063-8e11-9b3ce1879d6a. The first indicates that an indented FAB isn't used anymore (by omission), but the second suggests it can be indented as long as it's centered between 2 or 4 navigation items (mentioned in the "Don't" text).

... but I guess I'm off topic for this issue though.

**Comment by cbracken** [comment]
Re-opening since #106525 was reverted due to breakages.
