### ISSUE TITLE
camera_platform_interface-2.1.6 PlatformInterface.verify

### ISSUE THREAD

**Issue by faisalmushtaq007** [flutter/flutter#103576]
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/camera_platform_interface-2.1.6/lib/src/platform_interface/camera_platform.dart:42:23: Error: Member not found: 'PlatformInterface.verify'.
    PlatformInterface.verify(instance, _token);
                      ^^^^^^

**Comment by darshankawar** [comment]
@faisalmushtaq007 
When do you get this error ?. Can you provide `flutter doctor -v`, plugin version you are using, platform on which it gives this error ?

**Comment by faisalmushtaq007** [comment]
Actually i opened one of my old projects on a new system.
[√] Flutter (Channel stable, 2.10.5, on Microsoft Windows [Version 10.0.19044.1645], locale en-IN)
    • Flutter version 2.10.5 at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (3 weeks ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\User\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.67.1)
    • VS Code at C:\Users\User\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.40.0

[√] Connected device (4 available)
    • POCO F1 (mobile)  • 3964932c • android-arm64  • Android 10 (API 29)
    • Windows (desktop) • windows  • windows-x64    • Microsoft Windows [Version 10.0.19044.1645]
    • Chrome (web)      • chrome   • web-javascript • Google Chrome 101.0.4951.64
    • Edge (web)        • edge     • web-javascript • Microsoft Edge 101.0.1210.32

[√] HTTP Host Availability

**Comment by faisalmushtaq007** [comment]
@darshankawar any solution for this please???

**Comment by darshankawar** [comment]
check [this](https://stackoverflow.com/questions/70765865/error-member-not-found-platforminterface-verify-flutter-after-using-my-old) solution and see if it helps.

**Comment by faisalmushtaq007** [comment]
@darshankawar i have already  used this but still nothing

**Comment by faisalmushtaq007** [comment]
@darshankawar found the solution:
just had to add camera_platform_interface: ^2.1.0 to the dependencies
