### ISSUE TITLE
Update `IconButton` to support Material 3

### ISSUE THREAD

**Issue by darrenaustin** [flutter/flutter#103528]
As part of the [Material 3 specification](https://m3.material.io/components/icon-buttons/overview) there are updates to the Icon button's visuals as well as optional support for toggle states:

<img width="388" alt="Screen Shot 2022-05-11 at 12 54 48 PM" src="https://user-images.githubusercontent.com/19588/167934659-d9eb5276-b4b9-44a5-a34e-90709da2b0be.png">

If possible we should investigate adding these to the existing `IconButton` class to support these.

**Comment by bernaferrari** [comment]
I'm curious if there are the guidelines for the 'hovered'/'selected' state. I imagine the heart would have the 'large ripple effect' flutter current has, but the tri-state wouldn't and would work like a simple button.

**Comment by QuncCccccc** [comment]
> I guess, from looking at the guidelines, that's the end of the the 'huge ripple effect' the IconButton has when you hover/click?

Yes, the updated IconButton will look like the other common buttons(TextButton, OutlinedButton and etc) without text.
