### ISSUE TITLE
The shrine details view introduces a picture layer at the root.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#10355]
This causes the entire scene to be rasterized leading to a waste of memory for no performance gains. The root picture layer must be removed.
![screen shot 2017-05-26 at 2 10 15 pm](https://cloud.githubusercontent.com/assets/44085/26512823/3ecbdbd6-421d-11e7-9893-68d2828a8193.png)

**Comment by Hixie** [comment]
Any idea where it's coming from?

**Comment by zoechi** [comment]
Is this still relevant?
