### ISSUE TITLE
Low level swarming error doesn't notify

### ISSUE THREAD

**Issue by yusuf-goog** [flutter/flutter#103657]
Adding a bunch of new staging builders hit:

```
Swarming task creation API responded with HTTP 403: {"error": {"message": "user \"flutter-prod-builder@chops-service-accounts.iam.gserviceaccount.com\" does not have permission \"swarming.tasks.actAs\""}}
```
https://ci.chromium.org/p/flutter/builders/staging/Staging_build_linux%20test_ownership

But we didn't get notified that these errors were happening.

**Comment by yusuf-goog** [comment]
cc @CaseyHillers

**Comment by keyonghan** [comment]
Closing as WAI.
