### ISSUE TITLE
Widget to image(screenshot) not working properly on Flutter Web CanvasKit version with Flutter 3.

### ISSUE THREAD

**Issue by shofizone** [flutter/flutter#103612]
##Issue 
Widget to image not working properly on Flutter Web CanvasKit version with Flutter 3. Basically, the Image widget became invisible from the screenshot/generated image. While other widgets are captured properly.

## Steps to Reproduce
Run `flutter run -d Chrome  --web-renderer canvaskit` using the following code.
Try to capture an image with save FAB.

**Expected results:** Expected result Image should be captured as it looks on the UI. It should available on the bottom of the red container.

**Actual results:**  Image gets captured properly but the image widget is missing in the captured image.

<details>
<summary>Code sample</summary>

```dart

import 'dart:typed_data';

import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';
import 'dart:ui' as ui;

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Image Capture Bug',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final key = GlobalKey();
  Uint8List? imageBytes;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Flutter Image Capture Bug'),
      ),
      floatingActionButton: FloatingActionButton(
        child: const Icon(Icons.save),
        onPressed: () async {
          imageBytes = await captureImage();
       setState((){

       });
        },
      ),
      body: ListView(
        children: [
          Center(
            child: RepaintBoundary(
              key: key,
              child: Row(
                mainAxisSize: MainAxisSize.min,
                children: [
                  Container(
                    height: 300,
                    width: 200,
                    color: Colors.red,
                  ),
                  Image.network(
                    "https://picsum.photos/200/300",
                    height: 300,
                    width: 200,
                  ),
                ],
              ),
            ),
          ),
          if(imageBytes != null)
          Center(
            child: Card(
              child: Column(
                mainAxisSize: MainAxisSize.min,
                children: [
                  const Text("Capture Image"),
                  Padding(
                    padding: const EdgeInsets.all(8.0),
                    child: Image.memory(imageBytes!),
                  ),
                ],
              ),
            ),
          )
        ],
      ),
    );
  }

  Future<Uint8List?> captureImage() async {
    double pixelRatio = 5;
    try {
      RenderRepaintBoundary? boundary =
          key.currentContext?.findRenderObject() as RenderRepaintBoundary?;
      ui.Image? image = await boundary?.toImage(pixelRatio: pixelRatio);
      ByteData? byteData =
          await image?.toByteData(format: ui.ImageByteFormat.png);
      Uint8List? pngBytes = byteData?.buffer.asUint8List();
      return pngBytes;
    } catch (e) {
      debugPrint("$e");
      return null;
    }
  }
}

```

</details>

<details>
  <summary>Logs</summary>

```
Analyzing test_image_capture_web...                                     
No issues found! (ran in 1.4s)

```

```
[✓] Flutter (Channel stable, 3.0.0, on macOS 12.3.1 21E258 darwin-arm, locale en-US)
    • Flutter version 3.0.0 at /Users/shofiul/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ee4e09cce0 (3 days ago), 2022-05-09 16:45:18 -0700
    • Engine revision d1b9a6938a
    • Dart version 2.17.0
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/shofiul/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Library/Java/JavaVirtualMachines/zulu-8.jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (Zulu 8.60.0.21-CA-macos-aarch64) (build 1.8.0_322-b06)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] Android Studio (version 2021.2)
    • Android Studio at /Users/shofiul/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-2/212.5712.43.2112.8403254/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[!] Android Studio
    • Android Studio at /Users/shofiul/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-2/212.5712.43.2112.8233820/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] IntelliJ IDEA Community Edition (version 2022.1)
    • IntelliJ at /Users/shofiul/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5080.210/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Community Edition (version 2021.3.3)
    • IntelliJ at /Users/shofiul/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/213.7172.25/IntelliJ IDEA CE.app
    • Flutter plugin version 64.0.4
    • Dart plugin version 213.5744.122

[✓] VS Code (version 1.67.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.3.1 21E258 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 101.0.4951.64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```

</details>

<img width="496" alt="Screen Shot 2022-05-12 at 5 20 02 PM" src="https://user-images.githubusercontent.com/24232207/168066270-431ad7ea-de0f-47c9-99ec-644459e5ba97.png">
This image shows the captured image has a missing image widget.

**Comment by borjandev** [comment]
This is a very annoying issue!

It's quite challenging to to fully isolate it, and it's affecting a production app, thus any help from the Flutter team would be greatly appreciated!

Reproduction details: 

✅ : No Issue
❌ : Issue reproduced

Safari browsers ✅ 

Chrome browsers, both on Desktop and on Mobile (Pixel 3 Chrome) 
flutter run -d web-server --web-renderer canvaskit --release --web-hostname=0.0.0.0 --web-port=4242 ✅
flutter run -d web-server --web-renderer canvaskit --debug --web-hostname=0.0.0.0 --web-port=4242  ✅
This is odd because on local web-server release / debug mode it's working well..

Chrome browsers, both on Desktop and on Mobile (Pixel 3 Chrome) - Remote Release mode / PWA ❌
Things are getting weird here because if you release the same code on Firebase Hosting suddenly it stops working..
The only intuitive thing that comes to mind is that "https" makes some kind of a difference? 
As the local modes are not secure, thus maybe something about the "https" breaks it?

Chrome browsers, both on Desktop and on Mobile (Pixel 3 Chrome) - Local VS-Code Debug Chrome ❌
But if that was the case why is it broken again on the Local VS-Code Debug Chrome instance?

3.0.0  | x64 | ee4e09c | 11/05/2022 | 2.17.0 ❌ 
-- | -- | -- | -- | --
2.10.5 | x64 | 5464c5b | 18/04/2022 | 2.16.2 ✅ <-- Last Stable version where it works properly
-- | -- | -- | -- | --
2.11.0-0.1.pre | x64 | b101bfe | 16/02/2022 | 2.17.0 ❌ 
-- | -- | -- | -- | --
2.10.0-0.3.pre | x64 | fdd0af7 | 27/01/2022 | 2.16.0 ✅ <-- Last beta version where it works properly

**Comment by harithay** [comment]
I am facing the same issue as [shofizone](https://github.com/shofizone). 

`
 collage-maker  master  flutter doctor -v                                                                                                                               ✔ 
[✓] Flutter (Channel stable, 3.0.1, on Ubuntu 20.04.4 LTS 5.13.0-41-generic, locale en_CA.UTF-8)
    • Flutter version 3.0.1 at /home/user/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (4 days ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc1)
    • Android SDK at /home/user/Android/Sdk
    • Platform android-31, build-tools 31.0.0-rc1
    • ANDROID_SDK_ROOT = /home/user/Android/Sdk
    • Java binary at: /snap/android-studio/current/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[✓] Android Studio (version 2021.1)
    • Android Studio at /snap/android-studio/119/android-studio
    • Flutter plugin version 65.2.2
    • Dart plugin version 211.7808
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] Android Studio (version 2021.2)
    • Android Studio at /snap/android-studio/121/android-studio
    • Flutter plugin version 67.1.2
    • Dart plugin version 212.5744
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] Android Studio
    • Android Studio at /snap/android-studio/current/android-studio/
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /snap/android-studio/current/android-studio/
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code
    • VS Code at /snap/code/current
    • Flutter extension version 3.40.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 20.04.4 LTS 5.13.0-41-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 101.0.4951.64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
`

**Comment by borjandev** [comment]
As painstaking as it was to trace it,

This issue is caused by https://github.com/flutter/engine/pull/30681 included in https://github.com/flutter/flutter/pull/96239

/cc @yjbanov @huycozy 

✅ : No Issue
❌ : Issue reproduced

`flutter run -d chrome --dart-define=BROWSER_IMAGE_DECODING_ENABLED=true --release` ❌
`flutter run -d chrome --dart-define=BROWSER_IMAGE_DECODING_ENABLED=false --release` ✅

Opting-out from the `BROWSER_IMAGE_DECODING_ENABLED` flag fixes this particular issue, however would that cause any negative side-effects @yjbanov ?

**Comment by huycozy** [comment]
Similar to a little bit of #99945

**Comment by huycozy** [comment]
I tried to reproduce this issue on Flutter stable `2.10.5`. It works properly on Flutter Web CanvasKit.

<details>
<summary>Demo</summary>

![Screen Shot 2022-05-24 at 15 16 59](https://user-images.githubusercontent.com/104349824/169983746-edbd605b-31ed-4b57-972a-38152d5e5afa.png)
</details>

<details>

<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 2.10.5, on macOS 12.2.1 21D62 darwin-x64, locale en-VN)
    • Flutter version 2.10.5 at /Users/huynq/Documents/GitHub/flutter2.10.5
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (5 weeks ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.7042882/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Android Studio
    • Android Studio at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-1/203.7185775/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[✓] IntelliJ IDEA Community Edition (version 2020.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.67.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Connected device (3 available)
    • iPhone 13 (mobile) • 2526BC1A-435D-4B08-B99C-44B928F2517B • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-4 (simulator)
    • macOS (desktop)    • macos                                • darwin-x64     • macOS 12.2.1 21D62 darwin-x64
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 101.0.4951.64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!


```
</details>

**Comment by yjbanov** [comment]
The upstream Skia issue is https://bugs.chromium.org/p/skia/issues/detail?id=12721

**Comment by hterkelsen** [comment]
Same issue as https://github.com/flutter/flutter/issues/94895
