### ISSUE TITLE
Socket error: FileSystemException

### ISSUE THREAD

**Issue by Rodrigossff91** [flutter/flutter#103651]
Socket error: FileSystemException: Directory watcher closed unexpectedly, path = 'c:\Users\Tree Inova\Desktop\ProjetosTreeInova\doggi_app\doggi'

**Comment by darshankawar** [comment]
@Rodrigossff91 
Can you provide `flutter doctor -v` along with details around when do you see this error ? 
Please provide complete verbose log that shows more details around this error.

**Comment by aalpersen** [comment]
Hello, This happens to me as well

Error:

Socket error: FileSystemException: Directory watcher closed unexpectedly, path = 'd:\Programlama\flutter\konvert'

Here is "flutter doctor -v":

>[√] Flutter (Channel stable, 3.0.0, on Microsoft Windows [Version 10.0.19044.1706], locale tr-TR)
    • Flutter version 3.0.0 at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ee4e09cce0 (6 days ago), 2022-05-09 16:45:18 -0700
    • Engine revision d1b9a6938a
    • Dart version 2.17.0
    • DevTools version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\Alper\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.67.1)
    • VS Code at C:\Users\Alper\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.40.0

[!] Connected device
    ! No devices available

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

**Comment by trungdn0401** [comment]
Hi, This happens to me as well after upgrading Flutter to 3.0.0. Any news on this, please?

**Comment by kumangho** [comment]
same here. after upgrade flutter 3.0

**Comment by GaoWhitebird** [comment]
I have the same issue.
flutter doctor -v shows "No issue found!"
