### ISSUE TITLE
☂️ flutter/lifecycle channel support for desktop platforms

### ISSUE THREAD

**Issue by moko256** [flutter/flutter#103637]
The flutter/lifecycle channel is available in Android, iOS, web, but isn't implemented in desktop platforms. This issue tracks PR for each desktop platforms.
With this channel, framework can know whether an app window is visibled or focused.

This feature will unblock #87061.
Related: #30735

SystemChannels.lifecycle docs: https://api.flutter.dev/flutter/services/SystemChannels/lifecycle-constant.html
WidgetsBindingObserver.didChangeAppLifecycleState docs: https://api.flutter.dev/flutter/widgets/WidgetsBindingObserver/didChangeAppLifecycleState.html

- [ ] Add common StringMessage and StringMessageCodec: flutter/engine#29288
- [ ] Implement for Windows: flutter/engine#29288
- [ ] Implement for macOS:
- [ ] Implement for Linux:

**Comment by firashamila33** [comment]
any plans for Macos Desktop ?

**Comment by litgh** [comment]
There is a package named 'desktop_lifecycle' is working for macos desktop application.

**Comment by darshankawar** [comment]
Redirecting to `team-engine`. A community package seems to offer the feature : https://pub.dev/packages/desktop_lifecycle/example

**Comment by gspencergoog** [comment]
This is implemented in Flutter by the [`AppLifecycleListener`](https://api.flutter.dev/flutter/widgets/AppLifecycleListener-class.html) widget, even for desktop platforms and the web.
