### ISSUE TITLE
task':google_api_headers:compileDebugKotlin'.

### ISSUE THREAD

**Issue by Rodrigossff91** [flutter/flutter#103618]
AppData\Local\Pub\Cache\hosted\pub.dartlang.org\google_api_headers-1.2.0+1\android\src\main\kotlin\io\github\zeshuaro\google_api_headers\GoogleApiHeadersPlugin.kt: (58, 68): Type mismatch: inferred type is String? but String was expected

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':google_api_headers:compileDebugKotlin'.
> Compilation error. See log for more details

**Comment by bhanuka96** [comment]
same issue

**Comment by marchukav** [comment]
same issue as well

**Comment by ebcode008** [comment]
same issue

**Comment by gustavorozolin** [comment]
me too

**Comment by ebcode008** [comment]
Yo encontre este articulo que dice como solucionar pero aun siguiendo los pasos no me funciona
https://serveanswer.com/questions/after-upgrade-flutter-to-version-3-my-exist-project-is-not-building

**Comment by marchukav** [comment]
as a temporarily solution
you open this file producing error GoogleApiHeadersPlugin.kt (cmd + click on it in console for macOS)
and cut all the try catch part

```
    try {
                val info: PackageInfo
                if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.P) {
                    info = context!!.packageManager.getPackageInfo(call.arguments<String>(), PackageManager.GET_SIGNING_CERTIFICATES)
                    for (signature in info.signingInfo.apkContentsSigners) {
                        parseSignature(signature, result)
                    }
                } else {
                    @Suppress("DEPRECATION")
                    info = context!!.packageManager.getPackageInfo(call.arguments<String>(), PackageManager.GET_SIGNATURES)
                    @Suppress("DEPRECATION")
                    for (signature in info.signatures) {
                        parseSignature(signature, result)
                    }
                }

            } catch (e: Exception) {
                result.error("ERROR", e.toString(), null)
            }
```

so  if method is empty and doing nothing

`if (call.method == "getSigningCertSha1") {}`

I don't have enough knowledge to say what are the consequences of this but my app is working and all the google APIs are working too (google maps, google sign in, Firebase)

I suggest you save the code you cut somewhere.

**Comment by ebcode008** [comment]
it worked for me

**Comment by darshankawar** [comment]
Please avoid commenting `me too` or `same issue` and instead please upvote original issue for better visibility.

@gustavorozolin 
Is this happening after you upgraded to 3.0 ?  Do you get this error while trying to compile your app ? Can you provide `flutter doctor -v` and complete error log in verbose mode ?

**Comment by bhanuka96** [comment]
@darshankawar Yes, it happened after the upgrade to `3.0`. I downgrade flutter immediately without changing anything now it's working.

**Comment by gustavorozolin** [comment]
In my project I use `flutter_google_places` so I needed add 
```
dependency_overrides:
  google_api_headers: ^1.3.0-dev.0
```

**Comment by bhanuka96** [comment]
> @darshankawar Yes, it happened after the upgrade to `3.0`. I downgrade flutter immediately without changing anything now it's working.

I upgrade flutter 3.0 again and upgrade all **firebase** plugins, now it's working.

```
cloud_firestore to 3.1.15   
firebase_auth to 3.3.18   
firebase_core to 1.17.0   
firebase_crashlytics to 2.8.0    
firebase_messaging to 11.4.0   
firebase_remote_config to 2.0.7    
firebase_storage to 10.2.16 
```

**Comment by marchukav** [comment]
> > @darshankawar Yes, it happened after the upgrade to `3.0`. I downgrade flutter immediately without changing anything now it's working.
> 
> @darshankawar I upgraded flutter 3.0 again and upgrade all **firebase** plugins, now it's working.
> 
> ```
> cloud_firestore to 3.1.15   
> firebase_auth to 3.3.18   
> firebase_core to 1.17.0   
> firebase_crashlytics to 2.8.0    
> firebase_messaging to 11.4.0   
> firebase_remote_config to 2.0.7    
> firebase_storage to 10.2.16 
> ```

works for me
