### ISSUE TITLE
[Web] IME-based text input incorrectly fails to capture first character in composing region

### ISSUE THREAD

**Issue by cbracken** [flutter/flutter#103645]
[Reported](https://news.ycombinator.com/item?id=31349548) on Hacker News.

When inputting Japanese text in a Flutter Web app, we appear to be failing to capture the first character input in the composing region. See attached video for the (incorrect behaviour). I was able to repro on both macOS and Windows. Presumably this affects Linux as well.

https://user-images.githubusercontent.com/351029/168138099-796c31e0-ce25-4f72-b745-a4abd05d510f.mov

## Repro steps
1. Launch a Flutter Web app that includes a text field.
2. Switch to Japanese input hiragana mode (you should see an あ in the menu bar)
3. Type n-i-h-o-n-n.

**Expected behaviour:**
After each keypress you should see:
* n: n
* ni: に
* nih: にh
* niho: にほ
* nihon: にほn
* nihonn: にほん　(at this point you may get an auto-conversion to 日本, 2本, or other similar kanji conversion for 'nihon')

**Actual behaviour:**
* n: n
* ni: nい
* nih: nいh
* niho: nいほ
* nihon: nいほn
* nihonn: nいほん　(at this point you may get an auto-conversion to 伊ほん, 伊本 or other similar kanji conversion for 'ihon')

## Notes
Verified on Windows, macOS, and Linux and this issue does not affect the desktop embedders, so appears to likely to be an issue in the web engine.

**Comment by justinmc** [comment]
Related? https://github.com/flutter/flutter/issues/65357

**Comment by Renzo-Olivares** [comment]
Can confirm that #33590 fixes this issue.
