### ISSUE TITLE
Path Provider In Background

### ISSUE THREAD

**Issue by mhdkadi** [flutter/flutter#103652]
I am trying to use path provider in `FirebaseMessaging.onBackgroundMessage(firebaseMessagingBackgroundHandler)`, it always gives me 

> Unhandled Exception: MissingPluginException(No implementation found
> for method getApplicationDocumentsDirectory on channel
> plugins.flutter.io/path_provider)

    Future<void> firebaseMessagingBackgroundHandler(RemoteMessage message) async {
      try {
        final Directory appDocumentsDirector =
            await getApplicationDocumentsDirectory();
      } catch (e) {
        print(e.toString());
      }
    }

**MainActivity.java**

    package com.example.test_path_provider;
    import android.os.Bundle;
    import io.flutter.plugins.GeneratedPluginRegistrant;
    import io.flutter.embedding.android.FlutterActivity;
    public class MainActivity extends FlutterActivity {
        @Override
        protected void onCreate(Bundle savedInstanceState) {
            super.onCreate(savedInstanceState);
            GeneratedPluginRegistrant.registerWith(this.getFlutterEngine());
        }
    }

**Application.java**

    package com.example.test_path_provider;
    import io.flutter.app.FlutterApplication;
    import io.flutter.plugin.common.PluginRegistry;
    import io.flutter.plugin.common.PluginRegistry.PluginRegistrantCallback;
    import io.flutter.plugins.GeneratedPluginRegistrant;
    import io.flutter.plugins.pathprovider.PathProviderPlugin;
    
    public class Application extends FlutterApplication implements PluginRegistrantCallback {
      @Override
      public void registerWith(PluginRegistry registry) {
        PathProviderPlugin.registerWith(registry.registrarFor("io.flutter.plugins.pathprovider.PathProviderPlugin"));
      }
    }
**AndroidManifest.xml**

    <manifest xmlns:android="http://schemas.android.com/apk/res/android"
        package="com.example.test_path_provider">
       <application
            android:label="test_path_provider"
            android:name=".Application"
            android:icon="@mipmap/ic_launcher">
            <activity
                android:name=".MainActivity"
                android:exported="true"
                android:launchMode="singleTop"
                android:theme="@style/LaunchTheme"
                android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
                android:hardwareAccelerated="true"
                android:windowSoftInputMode="adjustResize">
                <meta-data
                  android:name="io.flutter.embedding.android.NormalTheme"
                  android:resource="@style/NormalTheme"
                  />
                <intent-filter>
                    <action android:name="android.intent.action.MAIN"/>
                    <category android:name="android.intent.category.LAUNCHER"/>
                </intent-filter>
            </activity>
            <meta-data
                android:name="flutterEmbedding"
                android:value="2" />
        </application>
    </manifest>

**flutter doctor -v**

> [√] Flutter (Channel stable, 2.10.5, on Microsoft Windows [Version
> 10.0.18362.30], locale en-US)
>     • Flutter version 2.10.5 at C:\src\flutter
>     • Upstream repository https://github.com/flutter/flutter.git
>     • Framework revision 5464c5bac7 (3 weeks ago), 2022-04-18 09:55:37 -0700
>     • Engine revision 57d3bac3dd
>     • Dart version 2.16.2
>     • DevTools version 2.9.2
> 
> [√] Android toolchain - develop for Android devices (Android SDK
> version 31.0.0)
>     • Android SDK at C:\Users\HP\AppData\Local\Android\sdk
>     • Platform android-31, build-tools 31.0.0
>     • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
>     • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
>     • All Android licenses accepted.
> 
> [√] Chrome - develop for the web
>     • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
> 
> [√] Visual Studio - develop for Windows (Visual Studio Community 2019
> 16.11.7)
>     • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
>     • Visual Studio Community 2019 version 16.11.31911.196
>     • Windows 10 SDK version 10.0.19041.0
> 
> [√] Android Studio (version 2020.3)
>     • Android Studio at C:\Program Files\Android\Android Studio
>     • Flutter plugin can be installed from:
>        https://plugins.jetbrains.com/plugin/9212-flutter
>     • Dart plugin can be installed from:
>        https://plugins.jetbrains.com/plugin/6351-dart
>     • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
> 
> [√] VS Code
>     • VS Code at C:\Users\HP\AppData\Local\Programs\Microsoft VS Code
>     • Flutter extension version 3.29.0
> 
> [√] Connected device (3 available)
>     • SM A205F (mobile) • R58M361JGKH • android-arm64  • Android 11 (API 30)
>     • Windows (desktop) • windows     • windows-x64    • Microsoft Windows [Version 10.0.18362.30]
>     • Chrome (web)      • chrome      • web-javascript • Google Chrome 101.0.4951.64
> 
> [√] HTTP Host Availability
>     • All required HTTP hosts are available
> 
> • No issues found!

**Comment by stuartmorgan** [comment]
See https://github.com/flutter/flutter/issues/99155#issuecomment-1060956399

Closing as a duplicate.

**Comment by mhdkadi** [comment]
I have tried https://github.com/flutter/flutter/issues/99155#issuecomment-1060956399 and it did not work 
```
Future<void> firebaseMessagingBackgroundHandler(RemoteMessage message) async {
  try {
    WidgetsFlutterBinding.ensureInitialized();
    DartPluginRegistrant.ensureInitialized();
    PathProviderAndroid.registerWith();
    final Directory appDocumentsDirector =
        await getApplicationDocumentsDirectory();
  } catch (e) {
    print(e.toString());
  }
}
```
**Platform:**

> flutter 3.0.0
> dart 2.17.0
> path_provider: ^2.0.10
> path_provider_android: ^2.0.14

**Comment by mhdkadi** [comment]
> See [#99155 (comment)](https://github.com/flutter/flutter/issues/99155#issuecomment-1060956399)
> 
> Closing as a duplicate.


I have tried https://github.com/flutter/flutter/issues/99155#issuecomment-1060956399 and it did not work 
```
Future<void> firebaseMessagingBackgroundHandler(RemoteMessage message) async {
  try {
    WidgetsFlutterBinding.ensureInitialized();
    DartPluginRegistrant.ensureInitialized();
    PathProviderAndroid.registerWith();
    final Directory appDocumentsDirector =
        await getApplicationDocumentsDirectory();
  } catch (e) {
    print(e.toString());
  }
}
```
**Platform:**

> Android
> flutter 3.0.0
> dart 2.17.0
> path_provider: ^2.0.10
> path_provider_android: ^2.0.14

**Comment by stuartmorgan** [comment]
What does "not work" mean, specifically? The error message in your initial report can't come from that version of `path_provider_android`.

**Comment by mhdkadi** [comment]
> What does "not work" mean, specifically? The error message in your initial report can't come from that version of `path_provider_android`.

**the Exception is** 

> MissingPluginException(No implementation found for method getApplicationDocumentsDirectory on channel plugins.flutter.io/path_provider_android)

**Comment by stuartmorgan** [comment]
That's a different exception (note the channel name change) demonstrating that `DartPluginRegistrant.ensureInitialized();` did fix the issue you reported. (You don't need to call both `DartPluginRegistrant.ensureInitialized()` and `PathProviderAndroid.registerWith()` by the way. If you are doing the former, there's no reason for the latter.)

The exception you have now means that the engine instance that is running `firebaseMessagingBackgroundHandler` doesn't have plugins registered on the native side. You'll need to contact the Firebase messaging plugin developers about that, because it's up to the creators of custom engine instances to decide what plugins to register.

**Comment by mhdkadi** [comment]
> That's a different exception (note the channel name change) demonstrating that `DartPluginRegistrant.ensureInitialized();` did fix the issue you reported. (You don't need to call both `DartPluginRegistrant.ensureInitialized()` and `PathProviderAndroid.registerWith()` by the way. If you are doing the former, there's no reason for the latter.)
> 
> The exception you have now means that the engine instance that is running `firebaseMessagingBackgroundHandler` doesn't have plugins registered on the native side. You'll need to contact the Firebase messaging plugin developers about that, because it's up to the creators of custom engine instances to decide what plugins to register.

thanks for your support,i appreciate that i will contact the Firebase messaging plugin developers about this Exception
