### ISSUE TITLE
Scaffold-->PageView-->Scaffold,GestureDetector onTap can't effect normal

### ISSUE THREAD

**Issue by Liberations** [flutter/flutter#103601]
## Steps to Reproduce

1. Scaffold-->PageView-->Scaffold,GestureDetector onTap can't effect normal

Here my code

```
import 'package:flutter/material.dart';

class TestClick extends StatefulWidget {
  const TestClick({Key? key}) : super(key: key);

  @override
  State<TestClick> createState() => _TestClickState();
}

class _TestClickState extends State<TestClick> {
  var count = 0;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.red,
      body: Column(
        children: [
          const SafeArea(child: Center(child: Text('Test Scaffold'))),
          Expanded(
              child: PageView(
            children: [
              _buildPage(),
              _buildPage(),
              _buildPage(),
            ],
          )),
        ],
      ),
    );
  }

  Widget _buildPage() {
    return Scaffold(
      backgroundColor: Colors.green,

      ///onTap not effect at blue Container top range
      body: GestureDetector(
        behavior: HitTestBehavior.opaque,
        onTap: () {
          setState(() {
            count++;
          });
        },
        child: Container(height: 100, color: Colors.blue, child: Center(child: Text('Click $count'))),
      ),
    );
  }
}

```

at top off green container,onTap(){} never effect. i don't know why. is it a bug of Scaffold??

```

<!-- Finally, paste the output of running `flutter doctor -v` here. -->

```
Flutter assets will be downloaded from https://mirrors.tuna.tsinghua.edu.cn/flutter. Make sure you trust this source!
[√] Flutter (Channel stable, 2.10.3, on Microsoft Windows [Version 10.0.22000.556], locale zh-CN)
    • Flutter version 2.10.3 at D:\fluttersdk\flutter
    • Upstream repository https://mirrors.tuna.tsinghua.edu.cn/git/flutter-sdk.git
    • Framework revision 7e9793dee1 (2 months ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2
    • Pub download mirror https://mirrors.tuna.tsinghua.edu.cn/dart-pub
    • Flutter download mirror https://mirrors.tuna.tsinghua.edu.cn/flutter

[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at D:\Android\sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • ANDROID_HOME = D:\Android\sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] VS Code (version 1.65.2)
    • VS Code at C:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.36.0

[√] Connected device (5 available)
    • SM N976N (mobile) • 127.0.0.1:62001      • android-x64    • Android 7.1.2 (API 25)
    • MYMEI (mobile)    • 192.168.110.222:5555 • android-arm    • Android 6.0.1 (API 23)
    • Windows (desktop) • windows              • windows-x64    • Microsoft Windows [Version 10.0.22000.556]
    • Chrome (web)      • chrome               • web-javascript • Google Chrome 101.0.4951.54
    • Edge (web)        • edge                 • web-javascript • Microsoft Edge 100.0.1185.44

[!] HTTP Host Availability
    X HTTP host https://maven.google.com/ is not reachable. Reason: An error occurred while checking the HTTP host:
      信号灯超时时间已到
```




<!--
   
![image](https://user-images.githubusercontent.com/16395007/168040345-4ae2411e-c2fa-4e63-81d1-1d9dd921e2fb.png)


-->

**Comment by Liberations** [comment]
Container==>PageView==>Scaffold same problem.

when i add padding onTap work normal
```
import 'package:flutter/material.dart';

class TestClick extends StatefulWidget {
  const TestClick({Key? key}) : super(key: key);

  @override
  State<TestClick> createState() => _TestClickState();
}

class _TestClickState extends State<TestClick> {
  var count = 0;

  @override
  Widget build(BuildContext context) {
    return Container(
      color: Colors.red,
      child: PageView(
        children: [
          _buildPage(),
          _buildPage(),
          _buildPage(),
        ],
      ),
    );
  }

  Widget _buildPage() {
    return Scaffold(
      backgroundColor: Colors.green,
      ///onTap not effect at blue Container top range
      body: Container(
        //add padding onTap work normal
        padding: const EdgeInsets.only(top: 60),
        child: GestureDetector(
          behavior: HitTestBehavior.opaque,
          onTap: () {
            setState(() {
              count++;
            });
          },
          child: Container(height: 100, color: Colors.blue, child: Center(child: Text('Click $count'))),
        ),
      ),
    );
  }
}

```
 
pageview cant perform well with Scaffold?

**Comment by darshankawar** [comment]
@Liberations 
Check below similar issues and see if they are same as your case.

https://github.com/flutter/flutter/issues/50946
https://github.com/flutter/flutter/issues/67461
https://github.com/flutter/flutter/issues/68960
https://github.com/flutter/flutter/issues/47119

**Comment by Liberations** [comment]
> @Liberations Check below similar issues and see if they are same as your case.
> 
> #50946 #67461 #68960 #47119

here my new found

```
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        platform: TargetPlatform.iOS,
        primarySwatch: Colors.blue,
      ),
      home: const TestClick(),
    );
  }
}

class TestClick extends StatefulWidget {
  const TestClick({Key? key}) : super(key: key);

  @override
  State<TestClick> createState() => _TestClickState();
}

class _TestClickState extends State<TestClick> {
  var count = 0;

  @override
  Widget build(BuildContext context) {
    return Container(
      padding: const EdgeInsets.only(top: 60),
      color: Colors.red,
      child: PageView(
        children: [
          _buildPage(),
        ],
      ),
    );
  }

  Scaffold _buildPage() {
    return Scaffold(
      backgroundColor: Colors.green,
      body: GestureDetector(
        behavior: HitTestBehavior.opaque,
        onTap: () {
          setState(() {
            count++;
          });
        },
        child: Container(height: 100, color: Colors.blue, child: Center(child: Text('Click $count'))),
      ),
    );
  }
}

```

This problem only occurs when I specify that the platform is IOS

`
platform: TargetPlatform.iOS,
`

I found code blow in Scaffold may be it is case this bug...

_handleStatusBarTap

```
switch (themeData.platform) {
      case TargetPlatform.iOS:
        _addIfNonNull(
          children,
          GestureDetector(
            behavior: HitTestBehavior.opaque,
            onTap: _handleStatusBarTap,
            // iOS accessibility automatically adds scroll-to-top to the clock in the status bar
            excludeFromSemantics: true,
          ),
          _ScaffoldSlot.statusBar,
          removeLeftPadding: false,
          removeTopPadding: true,
          removeRightPadding: false,
          removeBottomPadding: true,
        );
        break;
      case TargetPlatform.android:
      case TargetPlatform.fuchsia:
        break;
    }

 // iOS FEATURES - status bar tap, back gesture

  // On iOS, tapping the status bar scrolls the app's primary scrollable to the
  // top. We implement this by looking up the  primary scroll controller and
  // scrolling it to the top when tapped.
  void _handleStatusBarTap() {
    final ScrollController? _primaryScrollController = PrimaryScrollController.of(context);
    if (_primaryScrollController != null && _primaryScrollController.hasClients) {
      _primaryScrollController.animateTo(
        0.0,
        duration: const Duration(milliseconds: 300),
        curve: Curves.linear, // TODO(ianh): Use a more appropriate curve.
      );
    }
  }
```
I need all platforms to be able to slide elastically before adding this property。。。is there any way to remove this feture?

**Comment by Liberations** [comment]
@darshankawar

**Comment by darshankawar** [comment]
Please upgrade to latest stable and provide complete reproducible code sample (in a single file) that shows the current behavior and what's the expected result are you looking for .

**Comment by Liberations** [comment]
#15569 same problem.

**Comment by Liberations** [comment]
here my code   [https://github.com/Liberations/testClick](https://github.com/Liberations/testClick)
i want red Container ragne also effect onTap。Instead of tapping the status bar to return to the gesture, because there is no status bar here @darshankawar 

i hava update flutter Channel stable, 3.0.0,same issue.

```
C:\Users\Administrator>flutter doctor
Flutter assets will be downloaded from https://mirrors.tuna.tsinghua.edu.cn/flutter. Make sure you trust this source!
Running "flutter pub get" in flutter_tools...                      16.7s
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.0.0, on Microsoft Windows [版本 10.0.22000.556], locale zh-CN)
[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[√] Chrome - develop for the web
[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2021.1)
[√] VS Code (version 1.65.2)
[√] Connected device (3 available)
[√] HTTP Host Availability

! Doctor found issues in 1 category.
```

**Comment by darshankawar** [comment]
Thanks for the update. It's probably happening due to / or is similar to https://github.com/flutter/flutter/issues/54875 so please check this and https://docs.flutter.dev/development/ui/advanced/gestures#gesture-disambiguation for further reference.
