### ISSUE TITLE
iOS build stuck

### ISSUE THREAD

**Issue by VanshikaBagrodia** [flutter/flutter#103608]
## Steps to Reproduce

1. Execute `flutter build ipa` 

**Expected results:** 
Successful build of archive file

**Actual results:** 
Build stuck in 'Compiling, linking and signing...'

Screenshot for flutter run --verbose
![image](https://user-images.githubusercontent.com/39987545/168052395-5ae621ed-5fdf-41b3-bed1-842b178f4a3e.png)

**Comment by darshankawar** [comment]
@VanshikaBagrodia 
Can you provide `flutter doctor -v`, `flutter build ipa -v` ?  The verbose log will be huge so you can put that in a text file and share it here.

If you create a new flutter project and run same command on it, does it also behave similar ?

**Comment by VanshikaBagrodia** [comment]
@darshankawar 
I was able to fix the error
The GoogleService-Info.plist file was missing in my Runner folder
Closing the issue with this comment
Thanks!
