### ISSUE TITLE
How to convert webcam blob url to base64 string

### ISSUE THREAD

**Issue by Ashutosh0Sharma** [flutter/flutter#103690]
Hi,

I am trying to implement a capture image functionality on the website and store it in the database in base64 format. I have successfully implemented the capture image functionality using the camera package(^0.9.4+21) but I am facing an issue while converting it in the base64 because the camera web gives a blob URL (blob:http://url:/). 

Is there any way I can convert blob URL to base 64 string?

> Dart SDK version: 2.16.2 (stable) (Tue Mar 22 13:15:13 2022 +0100) on "windows_x64"

> Flutter 2.10.5 • channel stable • https://github.com/flutter/flutter.git
> Framework • revision 5464c5bac7 (4 weeks ago) • 2022-04-18 09:55:37 -0700
> Engine • revision 57d3bac3dd
> Tools • Dart 2.16.2 • DevTools 2.9.2

> Doctor summary (to see all details, run flutter doctor -v):
> [√] Flutter (Channel stable, 2.10.5, on Microsoft Windows [Version 10.0.22000.675], locale en-US)
> [!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
>     X cmdline-tools component is missing
>       Run `path/to/sdkmanager --install "cmdline-tools;latest"`
>       See https://developer.android.com/studio/command-line for more details.
>     X Android license status unknown.
>       Run `flutter doctor --android-licenses` to accept the SDK licenses.
>       See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
> [√] Chrome - develop for the web
> [√] Visual Studio - develop for Windows (Visual Studio Build Tools 2019 16.9.4)
> [√] Android Studio (version 2021.1)
> [!] Android Studio (version 4.2)
>     X Unable to determine bundled Java version.
> [√] VS Code (version 1.67.1)
> [√] Connected device (3 available)
> [√] HTTP Host Availability
> 
> ! Doctor found issues in 2 categories.

**Comment by darshankawar** [comment]
@Ashutosh0Sharma 
Your question is best suited for support channels like StackOverflow where you can get existing solutions if anybody has, so please ask the same there. Also take a look at this link : https://stackoverflow.com/questions/60565465/fetch-image-from-url-and-convert-it-to-base64-string-flutter

Closing from here.
