### ISSUE TITLE
Blanking occurs when using certain keyboard apps

### ISSUE THREAD

**Issue by intelryzen** [flutter/flutter#103611]
Failed OS: iOS
Flutter version: 2.10.5 (estimate occurrence if upgraded to 2.10.0 or higher)

If I use a certain keyboard app (in my case, Slyder app) in iOS, the screen will be blank as much as the keyboard height when I close the keyboard, as shown in the attached video. This problem disappears when I switch to a default keyboard or third party keyboard in iOS. Occurred when updating to the flutter 2.10.0 or higher.

https://user-images.githubusercontent.com/66426612/168063903-ef60ba0d-9292-4776-bc47-5acea3f51365.mp4

**Comment by mtrfnvwork** [comment]
+1

**Comment by darshankawar** [comment]
@intelryzen 
Can you provide `flutter doctor -v` and a complete minimal reproducible code sample that shows the behavior you are reporting ?

**Comment by darshankawar** [comment]
@intelryzen 
Per your original comment, the behavior seems to work correctly using default keyboard but not with third party keyboard you mentioned. Can you please confirm if using same keyboard (slyder) works properly with native iOS app ?

**Comment by intelryzen** [comment]
> @intelryzen Per your original comment, the behavior seems to work correctly using default keyboard but not with third party keyboard you mentioned. Can you please confirm if using same keyboard (slyder) works properly with native iOS app ?

It works well with other native iOS apps. The keyboard app has not been updated recently. However, when I updated to Flutter 2.10.0 and released my app, an abnormal phenomenon occurred. The app in the video was a flutter app produced by another person, and the same symptoms were found.

**Comment by coragx** [comment]
> It works well with other native iOS apps. The keyboard app has not been updated recently. However, when I updated to Flutter 2.10.0 and released my app, an abnormal phenomenon occurred. The app in the video (first app is native, second app is Flutter) was a flutter app produced by another person, and the same symptoms were found.

Same problem as yours in Flutter 2.10.3. This occurs with `resizeToAvoidBottomInset: true` in Scaffold Widget, when a  TextField is tapped to invoke a third-party keyboard app.

**Comment by coragx** [comment]
> > @intelryzen Per your original comment, the behavior seems to work correctly using default keyboard but not with third party keyboard you mentioned. Can you please confirm if using same keyboard (slyder) works properly with native iOS app ?
> 
> It works well with other native iOS apps. The keyboard app has not been updated recently. However, when I updated to Flutter 2.10.0 and released my app, an abnormal phenomenon occurred. The app in the video (first app is native, second app is Flutter) was a flutter app produced by another person, and the same symptoms were found.
> 
>  RPReplay_Final1652427930.MP4.1.mp4

Same problem as yours in Flutter 2.10.3. This occurs with resizeToAvoidBottomInset: true in Scaffold Widget, when a TextField is tapped to invoke a third-party keyboard app.

**Comment by coragx** [comment]
> > @intelryzen Per your original comment, the behavior seems to work correctly using default keyboard but not with third party keyboard you mentioned. Can you please confirm if using same keyboard (slyder) works properly with native iOS app ?
> 
> It works well with other native iOS apps. The keyboard app has not been updated recently. However, when I updated to Flutter 2.10.0 and released my app, an abnormal phenomenon occurred. The app in the video (first app is native, second app is Flutter) was a flutter app produced by another person, and the same symptoms were found.
> 
>  RPReplay_Final1652427930.MP4.1.mp4

Same problem as yours in Flutter 2.10.3. This occurs with resizeToAvoidBottomInset: true in Scaffold Widget, when a TextField is tapped to invoke a third-party keyboard app. Did your solved this problem and how?
