### ISSUE TITLE
Failed tests are not appearing in the result summary on Test Lab

### ISSUE THREAD

**Issue by umangdivyanshu** [flutter/flutter#103603]
When I am executing integration tests on Test Lab for android, failed tests are not appearing under the result summary. Only passed test cases are appearing and Instrumentation Test status is Passed. Whereas in the test execution video, I can clearly see that two of my test cases are failing but they do not appear in the result summary.

However, on executing the tests on my local on an AVD, failed tests are being reported as expected.

I have also tried running the tests using orchestrator but still the same issue replicates.

I had raised this Firebase support and after multiple emails, they have asked me to raise this to Flutter's GitHub.

<img width="899" alt="image" src="https://user-images.githubusercontent.com/77405518/168042416-b3a757f2-2ba6-49cb-ac17-cd5b9dac8f04.png">

**Comment by darshankawar** [comment]
@umangdivyanshu 
Thanks for the report. Can you provide `flutter doctor -v` and screenshots from FTL that only shows pass results and failed tests shown in it ?

**Comment by umangdivyanshu** [comment]
<details><summary> > flutter doctor -v</summary>
<p>

```terminal
umang@Apples-MacBook-Pro ~ % flutter doctor -v
[✓] Flutter (Channel stable, 2.10.5, on macOS 12.3 21E230 darwin-x64, locale en-GB)
    • Flutter version 2.10.5 at /Users/umang/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (4 weeks ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/umang/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.67.1)
    • VS Code at /Users/umang/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Connected device (3 available)
    • iPhone 12 Pro Max (mobile) • AC0DD1D7-222C-44E5-810A-790021907AEA • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-2
      (simulator)
    • macOS (desktop)            • macos                                • darwin-x64     • macOS 12.3 21E230 darwin-x64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 101.0.4951.64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</p>
</details>

<img width="1359" alt="image" src="https://user-images.githubusercontent.com/77405518/168965683-449b27a0-f3a9-4593-8aaf-4a0a2ffea5b7.png">

When I see the logs on FTL, it clearly shows that 4 scenarios were executed. Three scenarios passed and one failed. Even the video of the test execution shows the same.

<img width="1343" alt="image" src="https://user-images.githubusercontent.com/77405518/168966365-4af7eaed-498e-4d0c-9252-3eefc60d7e65.png">

**Comment by darshankawar** [comment]
@umangdivyanshu 
This was fixed for iOS as part of this https://github.com/flutter/flutter/issues/95648 and the fix is available on latest stable 3.0, so can you upgrade to latest stable or latest master and try again to see if it now captures failed tests too ?

`flutter channel master` 
`flutter upgrade`

or if you are on stable then `flutter upgrade`

**Comment by umangdivyanshu** [comment]
@darshankawar 
This is a different issue and not related to #95648.

This is happening for android where only failed test cases are not being reported on FTL. Please see the mail summary from my previous comment

> When I am executing integration tests on Test Lab for android, failed tests are not appearing under the result summary. Only passed test cases are appearing and Instrumentation Test status is Passed. Whereas in the test execution video, I can clearly see that two of my test cases are failing but they do not appear in the result summary.
> 
> However, on executing the tests on my local on an AVD, failed tests are being reported as expected.
> 
> I have also tried running the tests using orchestrator but still the same issue replicates.
> 
> I had raised this Firebase support and after multiple emails, they have asked me to raise this to Flutter's GitHub.
> 
> <img alt="image" width="899" src="https://user-images.githubusercontent.com/77405518/168042416-b3a757f2-2ba6-49cb-ac17-cd5b9dac8f04.png">

**Comment by darshankawar** [comment]
@umangdivyanshu 
Thanks for the update. Can you provide a minimal reproducible code sample that we can use to verify this further ?
