### ISSUE TITLE
[CP] SliverReorderableList can not reorder on Android platform

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#103663]
### issue_link

https://github.com/flutter/flutter/issues/103404

### Commit Hash

d29ccad

### Target

stable

### Impacted Users

Flutter Developers that ship on android using SliverReorderableList

### Impact Description

SliverReorderableList does not drag on certain android physical devices that have a platform touch slop less than the framework default of 16.

### Workaround

The workaround is to wrap the application in a MediaQuery that overrides that touchSlop to framework default value of 16:

```
MaterialApp(
 home: MediaQuery(
   data: MediaQueryData.fromWindow(window).copyWith(gestureSettings: DeviceGestureSettings(touchSlop: kTouchSlop)))
   child: ...
 )
 ```

### Risk

low

### Test Coverage

yes

### Validation Steps

https://github.com/flutter/flutter/issues/103404 contains a sample that when run on a physical android device will not allow dragging. The added unit test can also be run

**Comment by blasten** [comment]
I'm not familiar with this issue, but based on the description, it sounds like the fix should be cherry-picked

**Comment by itsjustkevin** [comment]
Flutter 3.0.2
