### ISSUE TITLE
[path_provider]: syncrhonus command

### ISSUE THREAD

**Issue by godalming123** [flutter/flutter#103646]
## Use case

When your app will be better when running synchronously

## Proposal

Synchronus commands for example
```dart
Directory = getApplicationDocumentsDirectorySync()
```

**Comment by darshankawar** [comment]
This should answer your question https://stackoverflow.com/questions/56192733/why-is-path-provider-in-dart-awaited

Closing as this isn't a valid proposal.

**Comment by godalming123** [comment]
Ok
