### ISSUE TITLE
Samsung S10 in staging pool is not detectable on linux-18

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#103668]
https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-linux-18

<img width="669" alt="Screen Shot 2022-05-12 at 5 06 42 PM" src="https://user-images.githubusercontent.com/54558023/168186485-ce46c4b3-1276-4b17-8d26-816e156787cf.png">

**Comment by yusuf-goog** [comment]
Will take a look when i go to the lab.

**Comment by keyonghan** [comment]
This seems blocking the newly enabled `Linux_samsung_s10 new_gallery_impeller__transition_perf` validation. /cc @zanderso 

<img width="407" alt="Screen Shot 2022-05-19 at 10 16 26 AM" src="https://user-images.githubusercontent.com/54558023/169359290-94a7ef0f-2f9b-4db1-a665-e15118c4f9ab.png">

**Comment by yusuf-goog** [comment]
I am planning on being in the lab tomorrow to check on the devices.

**Comment by godofredoc** [comment]
This is fixed now!
