### ISSUE TITLE
Does flutters framework use any encryption which are not general encryptions like https?

### ISSUE THREAD

**Issue by schwjo** [flutter/flutter#103625]
Hi,

we want to upload a flutter app to the apple appstore and it should be downloaded from other countries than usa.

Just a simple question: Does flutter use any encryption algorithms which need to be reported to the us government? 

I'm not talking about the annual self-classification report which has to be send to the nsa/bis every year when some kind of encryption is used (like https). I'm just talking about the kind of encryptions which are needing a CCATS (Commodity Classification Automated Tracking System) code before they are allowed to be published to the App Store.

I'm asking here because I think this is the "most official" place to ask a technical question like that.

Regards

**Comment by darshankawar** [comment]
I am not much aware about this, I'll keep this issue open for further insights from the team, although you may also try to ask this question on flutter discord server for faster response.

**Comment by schwjo** [comment]
Thanks, I already asked my questions on the flutter discord server, unfortunately it seems like no one knows how to deal with this situation.

**Comment by Hixie** [comment]
The encryptions that are used depends on which APIs you use, but in general the only encryption that Flutter apps will use are those for HTTPS, WebSocket, or secure sockets, as implemented by [boringssl](https://boringssl.googlesource.com/boringssl/), which is the same library used by Android and Chrome.

If you have a specific encryption algorithm in mind please don't hesitate to reach out. I'm not sure we can help much more beyond that.
