### ISSUE TITLE
[Windows] Newly created Windows project fails to run in Visual Studio 2022 

### ISSUE THREAD

**Issue by sebastianhaberey** [flutter/flutter#103731]
## Steps to Reproduce

1. `flutter create --platforms=windows foo`
2. `cd foo`
3. `flutter build windows`
4. MS Visual Studio 2022 > Open a Project or Solution > foo/build/windows/foo.sln
5. Right-click foo > Set as Startup Project
6. Menu > Project > Start Debugging (F5)

**Expected results:**

Application starts

**Actual results:** 

A window pops up: "flutter_windows.dll not found" (loosely translated from German)

**Comment**

Am I doing this wrong? It's been a while since I worked with VS.

<details>
  <summary>Logs</summary>

  ```
  λ flutter doctor -v
  [√] Flutter (Channel stable, 3.0.0, on Microsoft Windows [Version 10.0.19044.1645], locale de-DE)
      • Flutter version 3.0.0 at C:\Tools\flutter
      • Upstream repository https://github.com/flutter/flutter.git
      • Framework revision ee4e09cce0 (4 days ago), 2022-05-09 16:45:18 -0700
      • Engine revision d1b9a6938a
      • Dart version 2.17.0
      • DevTools version 2.12.2
  
  [√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
      • Android SDK at C:\Users\User\AppData\Local\Android\sdk
      • Platform android-32, build-tools 32.1.0-rc1
      • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
      • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
      • All Android licenses accepted.
  
  [√] Chrome - develop for the web
      • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe
  
  [√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.2.0)
      • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
      • Visual Studio Community 2022 version 17.2.32505.173
      • Windows 10 SDK version 10.0.19041.0
  
  [√] Android Studio (version 2021.2)
      • Android Studio at C:\Program Files\Android\Android Studio
      • Flutter plugin can be installed from:
         https://plugins.jetbrains.com/plugin/9212-flutter
      • Dart plugin can be installed from:
         https://plugins.jetbrains.com/plugin/6351-dart
      • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
  
  [√] VS Code (version 1.67.1)
      • VS Code at C:\Users\User\AppData\Local\Programs\Microsoft VS Code
      • Flutter extension can be installed from:
         https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
  
  [√] Connected device (3 available)
      • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19044.1645]
      • Chrome (web)      • chrome  • web-javascript • Google Chrome 101.0.4951.64
      • Edge (web)        • edge    • web-javascript • Microsoft Edge 101.0.1210.39
  
  [√] HTTP Host Availability
      • All required HTTP hosts are available
  
  • No issues found!
  ```

</details>

**Comment by timsneath** [comment]
You were very close!

I think the only thing you did wrong was creating a release build with `flutter build windows`. If for step 3, you instead do `flutter build windows --debug`, I think you'll be successful. 

![image](https://user-images.githubusercontent.com/2319867/168515087-a3668782-ba53-419e-955e-04dd1a3b72bd.png)

I'll file an issue to improve the documentation here.

**Comment by timsneath** [comment]
Sorry - accidentally closed the issue. Please try this out, and close it if you're successful.

**Comment by sebastianhaberey** [comment]
Indeed, it works! Thank you so much, that really improves my workflow!

**Comment by stuartmorgan** [comment]
Note that you also could have done a debug "build all" from within VS, and then run successfully

Unfortunately it was impossible to get the dependencies to work out right such that the build target and run target were there same.

**Comment by stuartmorgan** [comment]
Yes, that's the necessary build target. In practice because it's the to of the dependency tree, build all should do the same thing, and had the andante if having a keyboard shortcut.
