### ISSUE TITLE
Flutter downloads in vain

### ISSUE THREAD

**Issue by hosseinkhojany** [flutter/flutter#103723]
When I switch from one project to another or create a new project, when I press the run button to build for Android, it takes about 300 MB each time it downloads. This problem has been with me for the past two years.

**Comment by hosseinkhojany** [comment]
This only happens for Android when I press the run button

**Comment by manuelduarte077** [comment]
ok, sorry if I don't understand you, you say that when you do the build, to see your app in the emulator it takes up that amount of space, if that's it, that's fine, all that stays in the build folder, how everything is saved build them more if you test on desktop, web, mobile, that data is stored there, sometimes it reaches 1gb or more, of course it depends on the size of the app

but if it happens when you generate the apk, there if it would be another case, it would be to see how you do to generate the apk

**Comment by hosseinkhojany** [comment]
It downloads 300 mg and adds it to the .gradle folder

**Comment by Suman2023** [comment]
Hey try out this

flutter run --verbose  

u can see whats happening and avoid next time.. most probably its downloading a gradle .zip file it happened to me as well earlier.. checkout this and see if it helps

**Comment by hosseinkhojany** [comment]
flutter always deletes .gradle folder, you should save it and use it again. This is really funny. I lose more than 10 GB of bandwidth per day.

**Comment by hosseinkhojany** [comment]
Of course, when the build gets in error, this problem happining

**Comment by hosseinkhojany** [comment]
Honestly, I'm an Android developer and so far my .gradle has not been deleted due to a build error.

**Comment by hosseinkhojany** [comment]
Launching lib/main.dart on SM A307FN in debug mode...
Running Gradle task 'assembleDebug'...
../../Documents/flutter/3.0.0/flutter/.pub-cache/hosted/pub.dartlang.org/responsive_framework-0.1.7/lib/responsive_wrapper.dart:622:20: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../Documents/flutter/3.0.0/flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance!.addObserver(this);
                   ^
../../Documents/flutter/3.0.0/flutter/.pub-cache/hosted/pub.dartlang.org/responsive_framework-0.1.7/lib/responsive_wrapper.dart:623:20: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../Documents/flutter/3.0.0/flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance!.addPostFrameCallback((_) {
                   ^
../../Documents/flutter/3.0.0/flutter/.pub-cache/hosted/pub.dartlang.org/responsive_framework-0.1.7/lib/responsive_wrapper.dart:635:20: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../Documents/flutter/3.0.0/flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance!.removeObserver(this);
                   ^
../../Documents/flutter/3.0.0/flutter/.pub-cache/hosted/pub.dartlang.org/responsive_framework-0.1.7/lib/responsive_wrapper.dart:645:20: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../Documents/flutter/3.0.0/flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance!.addPostFrameCallback((_) {
                   ^
../../Documents/flutter/3.0.0/flutter/.pub-cache/hosted/pub.dartlang.org/dropdown_button2-1.4.0/lib/dropdown_button2.dart:1351:20: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../Documents/flutter/3.0.0/flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance!.removeObserver(this);
                   ^
../../Documents/flutter/3.0.0/flutter/.pub-cache/hosted/pub.dartlang.org/animations-2.0.2/lib/src/open_container.dart:631:24: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../Documents/flutter/3.0.0/flutter/packages/flutter/lib/src/scheduler/binding.dart').
      SchedulerBinding.instance!
                       ^
../../Documents/flutter/3.0.0/flutter/.pub-cache/hosted/pub.dartlang.org/animations-2.0.2/lib/src/open_container.dart:665:24: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../Documents/flutter/3.0.0/flutter/packages/flutter/lib/src/scheduler/binding.dart').
      SchedulerBinding.instance!
                       ^

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve io.flutter:x86_debug:1.0.0-d1b9a6938ad77326ac3a94d92bbc77933ed829ed.
     Required by:
         project :app
      > Could not resolve io.flutter:x86_debug:1.0.0-d1b9a6938ad77326ac3a94d92bbc77933ed829ed.
         > Could not get resource 'https://jcenter.bintray.com/io/flutter/x86_debug/1.0.0-d1b9a6938ad77326ac3a94d92bbc77933ed829ed/x86_debug-1.0.0-d1b9a6938ad77326ac3a94d92bbc77933ed829ed.pom'.
            > Could not GET 'https://jcenter.bintray.com/io/flutter/x86_debug/1.0.0-d1b9a6938ad77326ac3a94d92bbc77933ed829ed/x86_debug-1.0.0-d1b9a6938ad77326ac3a94d92bbc77933ed829ed.pom'. Received status code 403 from server: Forbidden
      > Could not resolve io.flutter:x86_debug:1.0.0-d1b9a6938ad77326ac3a94d92bbc77933ed829ed.
         > Could not get resource 'https://storage.googleapis.com/download.flutter.io/io/flutter/x86_debug/1.0.0-d1b9a6938ad77326ac3a94d92bbc77933ed829ed/x86_debug-1.0.0-d1b9a6938ad77326ac3a94d92bbc77933ed829ed.pom'.
            > Could not GET 'https://storage.googleapis.com/download.flutter.io/io/flutter/x86_debug/1.0.0-d1b9a6938ad77326ac3a94d92bbc77933ed829ed/x86_debug-1.0.0-d1b9a6938ad77326ac3a94d92bbc77933ed829ed.pom'. Received status code 403 from server: Forbidden
   > Could not resolve io.flutter:x86_64_debug:1.0.0-d1b9a6938ad77326ac3a94d92bbc77933ed829ed.
     Required by:
         project :app
      > Could not resolve io.flutter:x86_64_debug:1.0.0-d1b9a6938ad77326ac3a94d92bbc77933ed829ed.
         > Could not get resource 'https://jcenter.bintray.com/io/flutter/x86_64_debug/1.0.0-d1b9a6938ad77326ac3a94d92bbc77933ed829ed/x86_64_debug-1.0.0-d1b9a6938ad77326ac3a94d92bbc77933ed829ed.pom'.
            > Could not GET 'https://jcenter.bintray.com/io/flutter/x86_64_debug/1.0.0-d1b9a6938ad77326ac3a94d92bbc77933ed829ed/x86_64_debug-1.0.0-d1b9a6938ad77326ac3a94d92bbc77933ed829ed.pom'. Received status code 403 from server: Forbidden
      > Could not resolve io.flutter:x86_64_debug:1.0.0-d1b9a6938ad77326ac3a94d92bbc77933ed829ed.
         > Could not get resource 'https://storage.googleapis.com/download.flutter.io/io/flutter/x86_64_debug/1.0.0-d1b9a6938ad77326ac3a94d92bbc77933ed829ed/x86_64_debug-1.0.0-d1b9a6938ad77326ac3a94d92bbc77933ed829ed.pom'.
            > Could not GET 'https://storage.googleapis.com/download.flutter.io/io/flutter/x86_64_debug/1.0.0-d1b9a6938ad77326ac3a94d92bbc77933ed829ed/x86_64_debug-1.0.0-d1b9a6938ad77326ac3a94d92bbc77933ed829ed.pom'. Received status code 403 from server: Forbidden
   > Could not resolve io.flutter:flutter_embedding_debug:1.0.0-d1b9a6938ad77326ac3a94d92bbc77933ed829ed.
     Required by:
         project :app > project :shared_preferences_android
         project :app > project :sqlite3_flutter_libs
         project :app > project :url_launcher_android
         project :app > project :path_provider_android
      > Could not resolve io.flutter:flutter_embedding_debug:1.0.0-d1b9a6938ad77326ac3a94d92bbc77933ed829ed.
         > Could not get resource 'https://jcenter.bintray.com/io/flutter/flutter_embedding_debug/1.0.0-d1b9a6938ad77326ac3a94d92bbc77933ed829ed/flutter_embedding_debug-1.0.0-d1b9a6938ad77326ac3a94d92bbc77933ed829ed.pom'.
            > Could not GET 'https://jcenter.bintray.com/io/flutter/flutter_embedding_debug/1.0.0-d1b9a6938ad77326ac3a94d92bbc77933ed829ed/flutter_embedding_debug-1.0.0-d1b9a6938ad77326ac3a94d92bbc77933ed829ed.pom'. Received status code 403 from server: Forbidden
      > Could not resolve io.flutter:flutter_embedding_debug:1.0.0-d1b9a6938ad77326ac3a94d92bbc77933ed829ed.
         > Could not get resource 'https://storage.googleapis.com/download.flutter.io/io/flutter/flutter_embedding_debug/1.0.0-d1b9a6938ad77326ac3a94d92bbc77933ed829ed/flutter_embedding_debug-1.0.0-d1b9a6938ad77326ac3a94d92bbc77933ed829ed.pom'.
            > Could not GET 'https://storage.googleapis.com/download.flutter.io/io/flutter/flutter_embedding_debug/1.0.0-d1b9a6938ad77326ac3a94d92bbc77933ed829ed/flutter_embedding_debug-1.0.0-d1b9a6938ad77326ac3a94d92bbc77933ed829ed.pom'. Received status code 403 from server: Forbidden

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 19s
[!] Gradle threw an error while downloading artifacts from the network.
Retrying Gradle Build: #1, wait time: 100ms
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not find com.android.tools.build:gradle:7.0.1.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/7.0.1/gradle-7.0.1.pom
       - https://repo.maven.apache.org/maven2/com/android/tools/build/gradle/7.0.1/gradle-7.0.1.pom
     Required by:
         project :

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 49s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by hosseinkhojany** [comment]
When I saw this error, my .gradle folder, which was 3 GB in size, was deleted, WHY?

**Comment by hosseinkhojany** [comment]
Right now I'm very unlucky because I made a backup of my .gradle. When flutter deletes the .gradle, I replace it manually but flutter still downloads 200 MB. but is better than 1 GB ):

**Comment by hosseinkhojany** [comment]
In Android, when the prerequisites are being downloaded, we can see it in the console, but it does not show anything in the flutter.

**Comment by darshankawar** [comment]
@hosseinkhojany 
Check [this](https://stackoverflow.com/questions/62589406/way-to-stop-android-studio-gradle-build-from-using-internet-data/62589571#62589571) similar SO link for solution. Also, closing from hee as this isn't an issue. If you disagree, write in comments and I'll reopen it.
