### ISSUE TITLE
Update iOS version on devicelab iphones

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#103733]
This will hopefully resolve the "iPhone is busy: Fetching debug symbols for iPhone" issue in https://github.com/flutter/flutter/issues/103511

**Comment by yusuf-goog** [comment]
@christopherfujino  any specific version we need to go to, or the latest?

**Comment by yusuf-goog** [comment]
@christopherfujino decided that he doesn't need these to be upgraded, so closing.
