### ISSUE TITLE
flutter doctor / help

### ISSUE THREAD

**Issue by HelloWordSurely** [flutter/flutter#103791]
[☠]Visual Studio - develop for Windows (the doctor check crashed)
    X Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know
      about this issue at https://github.com/flutter/flutter/issues.
    X Exception: Bad UTF-8 encoding (U+FFFD; REPLACEMENT CHARACTER) found while decoding string: [
        {

**Comment by wzslr321** [comment]
Please, don't delete the PR template and share more information according to the instruction in the template.

**Comment by HelloWordSurely** [comment]
> Lütfen PR şablonunu silmeyin ve şablondaki talimata göre daha fazla bilgi paylaşın.

Okey bro thanks

**Comment by stuartmorgan** [comment]
Duplicate of https://github.com/flutter/flutter/issues/102451
