### ISSUE TITLE
Avoid using private types in public APIs trigger on Stful in flutter

### ISSUE THREAD

**Issue by nikhilbadyal** [flutter/flutter#103773]
**Describe the issue**
[Closed issue](https://github.com/Dart-Code/Dart-Code/issues/3827)

`Avoid using private types in public APIs`
Above lint should not trigger on stful in flutter.

**Example**
[See this Github Run in Flutter Analyzer step](https://github.com/nikhilbadyal/keepnotes/runs/6431420644?check_suite_focus=true)

Picking up the first location in code. Linter is issuing warning on stful  [See here](https://github.com/nikhilbadyal/keepnotes/blob/8cd8cbf9c14d61aee73bbc2d6b9e5a1006752294/lib/screen/edit/components/bottom_bar_options.dart#L16).

This is back in 
*flutter 3.0,flutter_lint 2.1* and it used `lints: ^2.0.0` version.

Please fix this as soon as possible. It is causing builds to fail. I have git-hook on Flutter analyzer so I'm not even able to commit my code.

**Comment by darshankawar** [comment]
@nikhilbadyal 
Can you provide a code sample that shows this lint message if we run it ?

**Comment by nikhilbadyal** [comment]
There is a link to the GitHub repo with the commit which have this issue.

**Comment by roslamir** [comment]
In our code, we can avoid the Lint message by changing the declaration from:
    `_ExampleState createState() => _ExampleState();`
to:
    `State<Example> createState() => _ExampleState();`

**Comment by darshankawar** [comment]
Thanks for the update. Keeping it open and labeling based on the original description and logs.

**Comment by mraleph** [comment]
There is no problem with Flutter here. It's your code @nikhilbadyal that now violates the lint, so you need to either update your code to fix the lint violation or disable this lint using analysis options. 

@roslamir gives a good example above on how you can update your code, e.g. 

```dart
  _BottomBarOptionsState createState() => _BottomBarOptionsState();
```

should become

```dart
  State<BottomBarOptions> createState() => _BottomBarOptionsState();
```

Note that there is no problem with `stful` snippet anymore - it now generates correct Dart code, which does not use any private types in the API.

**Comment by nikhilbadyalanchanto** [comment]
@mraleph Can you refer me to the changelog where these new changes are documented and mentioned that the old format is deprecated or something like that? I would like to read those.

**Comment by mraleph** [comment]
Well, nothing is really deprecated here. You are choosing to use `flutter_lints` package, which simply constantly gets new lints to enforce better code style. The changelog for that package is here: https://github.com/flutter/packages/blob/main/packages/flutter_lints/CHANGELOG.md. 

Lints are not fatal errors - you can choose to suppress or ignore individual lints. You code will run just fine even if it has linter violations.  The key here is to understand why each individual lint is flagging a particular piece of code and what are the consequences of violating a lint.
