### ISSUE TITLE
flutter still uses Android SDK version 31 instead of most recent 32

### ISSUE THREAD

**Issue by repentsinner** [flutter/flutter#103713]
Hi team-

Per [Google best practice](https://medium.com/androiddevelopers/picking-your-compilesdkversion-minsdkversion-targetsdkversion-a098a0341ebd), it is recommended to use the [latest released SDK](https://developer.android.com/studio/releases/platforms), which is 32 as of Dec 2021. How come flutter 3.0.0 (and 2.10.5) are still using a compileSdkVersion of 31?

https://github.com/flutter/flutter/blob/ee4e09cce01d6f2d7f4baebd247fde02e5008851/packages/flutter_tools/gradle/flutter.gradle#L32-L33

Thanks for considering!

**Comment by darshankawar** [comment]
Thanks for the report. Keeping it open and labeling for further insights on this from the team.

**Comment by blasten** [comment]
This makes sense. It should be pretty straightforward to update.

**Comment by GaryQian** [comment]
For archaeological reasons: The steps to the android SDK bump are at https://github.com/flutter/flutter/wiki/Upgrading-Engine's-Android-API-version

**Comment by repentsinner** [comment]
thanks all!
