### ISSUE TITLE
TextField is not displayed correctly on iOS after using microphone to speak input

### ISSUE THREAD

**Issue by peaklev** [flutter/flutter#10371]
## Steps to Reproduce

1. Run the Flutter Gallery application on an iPhone 6.
2. Select the "Text field" demo.
3. Click on the "Name" field.
4. Click on the microphone icon on the iOS keyboard and say something.
5. The text displays in the text field.
6. Click "Done" in the keyboard area to dismiss the keyboard.
7. Only the last character of the spoken text is displayed in the text field. All other characters disappear.

## Logs

N/A

## Flutter Doctor

[✓] Flutter (on Mac OS X 10.12.4 16E195, locale en-US, channel master)
    • Flutter at /Users/?/Development/flutter
    • Framework revision 767ab66c25 (32 hours ago), 2017-05-27 00:45:25 -0700
    • Engine revision 75c74dc463
    • Tools Dart version 1.24.0-dev.3.0

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at /Users/?/Library/Android/sdk
    • Platform android-25, build-tools 25.0.3
    • ANDROID_HOME = /Users/?/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.3.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3.2, Build version 8E2002
    • ios-deploy 1.9.1
    • CocoaPods version 1.2.1

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Gradle version 3.2
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.1.3)
    • Dart plugin version 171.4424.63
    • Flutter plugin version 13.1

**Comment by eseidelGoogle** [comment]
@cbracken would know.

**Comment by cbracken** [comment]
Thanks for reporting! Definitely a bug. I'll take a look!

**Comment by matthewtsmith** [comment]
Found a duplicate: https://github.com/flutter/flutter/issues/13771

**Comment by zoechi** [comment]
@matthewtsmith thanks!
Closing as dup of #13771
