### ISSUE TITLE
[go_router] Allow to redirect in builder / errorBuilder

### ISSUE THREAD

**Issue by DamienMrtl** [flutter/flutter#103710]
## Use case

When checking if the route parameters are valid values, I would like to redirect to another route if the parameters are not valid.

## Proposal

In the error builder allow access to the router to redirect to a custom location and not always show the error page.

**Comment by chunhtai** [comment]
redirect in builder: You should be able to achieve the same behavior using GoRoute.redirect
redirect in errorBuilder: We should come up with a wild card match all pattern, so that you can handle it in there.

**Comment by DamienMrtl** [comment]
@chunhtai  The problem is if I check the parameters in the redirect function, I will load 2 times the data as my parameter validation has to do a network request to check if the resource exists. The second time is in the builder function to then pass the data to the route. So it would be nice feature to have but I guess there are maybe limitation on the Navigator 2.0 level ?

**Comment by Skogsfrae** [comment]
This can be resolved with the introduction of https://github.com/flutter/flutter/issues/108144

**Comment by amin79** [comment]
Hi, any update?

**Comment by chunhtai** [comment]
added onException https://github.com/flutter/packages/pull/4216
