### ISSUE TITLE
Rename `XTypeGroup`'s `macUTIs`

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#103743]
We have a field called `macUTIs`, but it will be used for iOS too. We should rename it, with aliases (using `get` and `set`) to preserve backward compatibility.

**Comment by juandausa** [comment]
Hi @stuartmorgan, I was looking into starting contributing a bit to the project.
We looked into the code and discovered that both the Mac and iOS implementation use the property `macUTIs`. We modified the main example to include this field, and it's currently working on the different platforms.

Furthermore, we believe that changing `macUTIs` to `cupertinoUTIs` would be a good replacement but, it will generate a breaking change. Can you elaborate on the way you proposed to preserve backward compatibility?

Thanks,

**Comment by stuartmorgan** [comment]
> Furthermore, we believe that changing `macUTIs` to `cupertinoUTIs` would be a good replacement

`cupertino` is a confusing term in many contexts, and in the framework it explicitly means "iOS" not "iOS and macOS", so I definitely don't want to use it here. We should just call it `uniformTypeIdentifiers`, since that's an unambiguous term.

> Can you elaborate on the way you proposed to preserve backward compatibility?

`macUTIs` can be left as a synthetic property that forwards to the new name. I.e., a construction like:

```
class Foo {
  bool foo = false;
  bool get bar => foo;
  set bar(bool value) { foo = value;}
}
```

Once that's published and `file_selector` has been updated to use the new names, the old name can be `@Deprecated`.

**Comment by juandausa** [comment]
Hi @stuartmorgan we appreciate your prompt response and clarification, we'll take this approach.
