### ISSUE TITLE
Upgrade to Flutter 3.0 on ChromeBook error finding pkg-config 

### ISSUE THREAD

**Issue by bsanderson1981** [flutter/flutter#103744]
bill@penguin:/$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.0, on Debian GNU/Linux 11 (bullseye)
    5.10.106-15290-g6e9d70c8a9b4, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version
    32.1.0-rc1)
[✓] Chrome - develop for the web
[☠] Linux toolchain - develop for Linux desktop (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message
      below is not helpful, please let us know about this issue at
      https://github.com/flutter/flutter/issues.
    ✗ ProcessException: Failed to find "pkg-config" in the search path.
        Command: pkg-config 
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.67.1)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

my chromebook running debian 11.3

**Comment by stuartmorgan** [comment]
/cc @christopherfujino 

I would have thought that the fix for https://github.com/flutter/flutter/issues/99944 would have prevented this from throwing an exception.

**Comment by christopherfujino** [comment]
Looks like we need to add another catch: https://github.com/flutter/flutter/blob/flutter-2.13-candidate.0/packages/flutter_tools/lib/src/linux/linux_doctor.dart#L191

**Comment by christopherfujino** [comment]
@bsanderson1981 thank you for filing this, it's definitely a bug that we're showing the exception in the doctor.

However, to unblock yourself, you will need to install pkg-config to do linux desktop builds.

**Comment by bsanderson1981** [comment]
@christopherfujino   i did install pkg-config 
sudo apt install pkg-config

which fixed it.  i just wanted to report error so future installs check for pkg-config dependence.  

thanks

**Comment by christopherfujino** [comment]
> 



> @christopherfujino i did install pkg-config sudo apt install pkg-config
> 
> which fixed it. i just wanted to report error so future installs check for pkg-config dependence.

Thanks, I appreciate it!

**Comment by bsanderson1981** [comment]
@christopherfujino   just fyi.  looks like chromebook stock debian need more dev packages installed for flutter 3.0  after installing pkg-config.

these flutter doctor error come up.   after rerunning flutter doctor after install of pkg-config.


Linux toolchain - develop for Linux desktop
    ✗ clang++ is required for Linux development.
      It is likely available from your distribution (e.g.: apt install clang), or
      can be downloaded from https://releases.llvm.org/
    ✗ CMake is required for Linux development.
      It is likely available from your distribution (e.g.: apt install cmake), or
      can be downloaded from https://cmake.org/download/
    ✗ ninja is required for Linux development.
      It is likely available from your distribution (e.g.: apt install
      ninja-build), or can be downloaded from
      https://github.com/ninja-build/ninja/releases
    ✗ GTK 3.0 development libraries are required for Linux development.
      They are likely available from your distribution (e.g.: apt install
      libgtk-3-dev)
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.67.1)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

! Doctor found issues in 1 category.

**Comment by stuartmorgan** [comment]
> Looks like we need to add another catch: https://github.com/flutter/flutter/blob/flutter-2.13-candidate.0/packages/flutter_tools/lib/src/linux/linux_doctor.dart#L191

Ah right, I forgot there were two codepaths.

**Comment by stuartmorgan** [comment]
> looks like chromebook stock debian need more dev packages installed for flutter 3.0 after installing pkg-config.

Stock machines general don't have developer tools installed. If you are doing Linux development you should follow [these instructions](https://docs.flutter.dev/desktop#additional-linux-requirements).

**Comment by christopherfujino** [comment]
> > Looks like we need to add another catch: https://github.com/flutter/flutter/blob/flutter-2.13-candidate.0/packages/flutter_tools/lib/src/linux/linux_doctor.dart#L191
> 
> Ah right, I forgot there were two codepaths.

Actually it's more subtle than that

> > looks like chromebook stock debian need more dev packages installed for flutter 3.0 after installing pkg-config.
> 
> Stock machines general don't have developer tools installed. If you are doing Linux development you should follow [these instructions](https://docs.flutter.dev/desktop#additional-linux-requirements).

Yeah, this is working as intended.
