### ISSUE TITLE
Inject initialization code to Android application onCreate from Flutter package

### ISSUE THREAD

**Issue by deepak786** [flutter/flutter#103709]
I'm the maintainer of the flutter package [intercom_flutter](https://pub.dev/packages/intercom_flutter).
This package Integrates [Intercom](https://www.intercom.com/) for Flutter apps.
For the Android side, Intercom requires initializing the SDK at the onCreate of the Application class. But in the package, we are initializing it on demand in the main method. This is working fine.
But end-users have the following exception:
![Screen Shot 2022-05-13 at 8 31 16 PM](https://user-images.githubusercontent.com/14223997/168311759-a2f50133-2592-4e7d-8100-3c2254527177.png)

If we ask the users to Initialize it on the Android side, instead of in the Flutter main method then they have to add the Intercom dependency in Android build.gradle as well.

So I would like to know if there is any way to pass the code from the Flutter side to the Android application onCreate.

I don't know any other package that has a similar requirement.

**Comment by darshankawar** [comment]
Can you take a look at [this](https://stackoverflow.com/questions/57283923/run-flutter-code-when-android-application-class-starts) link and see if it helps ?

**Comment by deepak786** [comment]
@darshankawar Thanks. I will check and study this on weekend.
