### ISSUE TITLE
[Flutter 3] setState not workin in google_maps_flutter

### ISSUE THREAD

**Issue by Cryward** [flutter/flutter#103722]
I have an application with google_maps_flutter, when updating to Flutter 3 setState I stop updating markers that I add on the map, for the markers to be displayed on the map I have to zoom or move the map, so they are shown in the version of Flutter 2.10 .5 works fine.

Any solution for this?

**Comment by manuelduarte077** [comment]
what warnings do you get in the console, it may be that the package has not yet been updated to version 3

**Comment by Cryward** [comment]
> what warnings do you get in the console, it may be that the package has not yet been updated to version 3

Absolutely nothing appears in the console, there are no warning or error messages.

**Comment by manuelduarte077** [comment]
If it happened to you after migrating, it may be that the package is missing an update, with version 3 there may be some change that affects it, you can check the google_maps_flutter repo to see if another has the same problem

**Comment by manuelduarte077** [comment]
https://github.com/flutter/flutter/issues/101119  
something related to what happens to you

**Comment by Cryward** [comment]
> If it happened to you after migrating, it may be that the package is missing an update, with version 3 there may be some change that affects it, you can check the google_maps_flutter repo to see if another has the same problem

Update all libraries including google maps, I'm using the

`google_maps_flutter: ^2.1.5`

If you are using google maps, you should not update yet, I tried all possible ways, even creating the marker from a button even so I was not successful, just moving or zooming it managed to solve the problem although it is not the solution I was looking for.

**Comment by Cryward** [comment]
> #101119 something related to what happens to you

It is not the same, my case is that setState does not execute the action, as it did with the previous version of flutter.

**Comment by huycozy** [comment]
Hi @Cryward. Thanks for filing the issue. Please share a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) along with the output of `flutter doctor -v` to investigate this issue further.

**Comment by Cryward** [comment]
The example is simple when clicking on the map a marker is added and if I click on another place the marker is updated in the new position, but in flutter 3 it is necessary to move the map so that the marker is refreshed, this happens in Windows and MacOS .

`import 'dart:async';

import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

void main() {
  if (defaultTargetPlatform == TargetPlatform.android) {
    AndroidGoogleMapsFlutter.useAndroidViewSurface = true;
  }
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Flutter Demo',
      theme: ThemeData(
        colorSchemeSeed: Colors.blue,
        useMaterial3: true,
        brightness: Brightness.light,
        //appBarTheme: const AppBarTheme(backgroundColor: Colors.blue)
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final Completer<GoogleMapController> _controller = Completer();
  final List<Marker> _markers = [];
  final CameraPosition _kGooglePlex = const CameraPosition(
    target: LatLng(37.42796133580664, -122.085749655962),
    zoom: 14.4746,
  );

  final CameraPosition _kLake = const CameraPosition(
      bearing: 192.8334901395799,
      target: LatLng(37.43296265331129, -122.08832357078792),
      tilt: 59.440717697143555,
      zoom: 19.151926040649414);

  void _incrementCounter() {
    setState(() {

    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: GoogleMap(
        mapType: MapType.hybrid,
        initialCameraPosition: _kGooglePlex,
        onMapCreated: (GoogleMapController controller) {
          _controller.complete(controller);
        },
        markers: Set<Marker>.of(_markers),
        onTap: (position) {
          //if (newPolyAvance) {
          setState(() {
            _markers.add(Marker(
              infoWindow: const InfoWindow(title: 'Prueba'),
              //icon: iconMk,
              markerId: const MarkerId('test'),
              position: position,
              )
            );
          });
        },
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
`
`[√] Flutter (Channel stable, 3.0.0, on Microsoft Windows [Versi¢n 10.0.22000.675], locale es-CL)
    • Flutter version 3.0.0 at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ee4e09cce0 (7 days ago), 2022-05-09 16:45:18 -0700
    • Engine revision d1b9a6938a
    • Dart version 2.17.0
    • DevTools version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at C:\Users\HP\AppData\Local\Android\sdk
    • Platform android-32, build-tools 32.0.0
    • Java binary at: C:\Users\HP\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\211.7628.21.2111.8193401\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Build Tools 2019 16.11.9)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
    • Visual Studio Build Tools 2019 version 16.11.32106.194
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] Android Studio (version 2021.1)
    • Android Studio at C:\Users\HP\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\211.7628.21.2111.8193401
    • Flutter plugin version 67.1.1
    • Dart plugin version 211.7817
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] VS Code (version 1.67.1)
    • VS Code at C:\Users\HP\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.40.0

[√] Connected device (4 available)
    • SM G973F (mobile) • R28M21MZ6XR • android-arm64  • Android 12 (API 31)
    • Windows (desktop) • windows     • windows-x64    • Microsoft Windows [Versi¢n 10.0.22000.675]
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 101.0.4951.67
    • Edge (web)        • edge        • web-javascript • Microsoft Edge 101.0.1210.39

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!`

> Hi @Cryward. Thanks for filing the issue. Please share a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) along with the output of `flutter doctor -v` to investigate this issue further.

**Comment by huycozy** [comment]
> The example is simple when clicking on the map a marker is added and if I click on another place the marker is updated in the new position, but in flutter 3 it is necessary to move the map so that the marker is refreshed, this happens in Windows and MacOS .

Hi @Cryward, thank for your response. But the [google_maps_flutter](https://pub.dev/packages/google_maps_flutter) has not supported for Desktop yet. Can you tell me what your target environments so that I can try to verify this issue?

**Comment by Cryward** [comment]
> > The example is simple when clicking on the map a marker is added and if I click on another place the marker is updated in the new position, but in flutter 3 it is necessary to move the map so that the marker is refreshed, this happens in Windows and MacOS .
> 
> Hi @Cryward, thank for your response. But the [google_maps_flutter](https://pub.dev/packages/google_maps_flutter) has not supported for Desktop yet. Can you tell me what your target environments so that I can try to verify this issue?

Hello, I'm sorry I don't program on the desktop, in the previous answer I meant that in the installation of flutter 3 in windows and in macos the same thing happens when compiling the example for android, I develop for android and ios, the problem appears in android, in ios I have not tried it yet, greetings
