### ISSUE TITLE
Support flutter create --package

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#10377]
We currently support:

1. `flutter create` for creating an 'application', and
2. `flutter create --plugin` for creating a 'plugin' (i.e., a 'package' with native code)

To facilitate creating pure-dart 'package', would be good to support:

3. `flutter create --package`

## Template content:

1. `pubspec.yaml` (similar to plugin)
1. `CHANGELOG.md` (similar to plugin)
1. `README.md` (similar to plugin)
1. `.gitignore` (similar to plugin but without platform ones)
1. `lib/<name>.dart`: contains a single class with some simple sample API and some instructional comments
1. `test/<name>_test.dart`: contains a simple test class (see [stagehand templates](https://github.com/google/stagehand/tree/master/templates/package-simple/test)).

**Comment by sethladd** [comment]
Would `flutter create --plugin` add plugin files to an existing package? Would it "upgrade" it?

**Comment by mit-mit** [comment]
That command would not, but another set of commands being discussed would. Those ability are definitely needed.

**Comment by sethladd** [comment]
This feature greatly helps https://github.com/flutter/flutter/issues/10070

**Comment by Hixie** [comment]
It's not clear that this is a priority right now; should we move to a future milestone?

**Comment by sethladd** [comment]
We can document a work-around, so it's technically not blocking.

**Comment by mit-mit** [comment]
No, not blocking, but it's hurting our end to end plugin devexp story, which is suffering a bit from 'death by a thousand paper cuts', so I want to keep this in milestone 3.

**Comment by mit-mit** [comment]
cc @szakarias

**Comment by mit-mit** [comment]
@jakobr-google tried to specify contents of this templates up-top, does that look resonable?

**Comment by mit-mit** [comment]
Thanks @jakobr-google!

Documentation was updated in https://github.com/flutter/website/pull/656.
