### ISSUE TITLE
Stop releasing stable versions without releasing on beta channel

### ISSUE THREAD

**Issue by martin-braun** [flutter/flutter#103795]
EDIT: Nvm, apparently 3.0.0 is the result of 2.13.0-0.4.pre, so it was on the beta channel as different name. Still I'd suggest to release a 3.0.0-0.1.pre next time.

**Comment by maheshmnj** [comment]
Hi @martin-braun, Thanks for filing the issue. I am quite not sure I understood the reasoning for your proposal. However, the new stable release is branched out from the beta channel as mentioned in this wiki https://github.com/flutter/flutter/wiki/Flutter-build-release-channels
