### ISSUE TITLE
CircleCI fails after "Finding the correct isolate with the integration test service extension"

### ISSUE THREAD

**Issue by andrewboissonnault** [flutter/flutter#103759]
## Steps to Reproduce

1. Setup integration tests using CircleCI
2. Run `flutter test integration_test --verbose` command
3. Integration tests hang for 12 minutes after isolate message and then timesout.

"Finding the correct isolate with the integration test service extension"

## Logs

<details>
<summary>Logs</summary>

[flutter test.log](https://github.com/flutter/flutter/files/8691466/flutter.test.log)

[flutter_doctor.log](https://github.com/flutter/flutter/files/8691492/flutter_doctor.log)

</details>

**Comment by darshankawar** [comment]
@andrewboissonnault 
Does the integration tests run properly without the said behavior when you run it locally ?
If so, then you might need to reach out to CI provider for further resolution.
