### ISSUE TITLE
Flutter 3.0.0: Imports can't be found inside of a bazel workspace

### ISSUE THREAD

**Issue by daniel-possienke** [flutter/flutter#103706]
## Steps to Reproduce

1. Create a new flutter project
2. Setup a bazel project one directory above the flutter directory (should include a `WORKSPACE` file)

**Expected results:** 

The imports of the project should be found.

**Actual results:** 

Not a single import can be found anymore (e.g. the import flutter/material.dart)

<details>
  <summary>Logs</summary>
Flutter doctor:

[✓] Flutter (Channel stable, 3.0.0, on macOS 12.3.1 21E258 darwin-arm, locale de-DE)
    • Flutter version 3.0.0 at /Users/daniel/Library/Flutter/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ee4e09cce0 (4 days ago), 2022-05-09 16:45:18 -0700
    • Engine revision d1b9a6938a
    • Dart version 2.17.0
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/daniel/Library/Android/sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (4 available)
    • SM G991B (mobile)      • R3CR60KHBME                          • android-arm64  • Android 12 (API 31)
    • iPhone 13 Pro (mobile) • 7FC86B9B-3CE3-4981-A9B3-D372B8F18FC8 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-4 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.3.1 21E258 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 101.0.4951.64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

bazel --version:

bazel 5.1.1-homebrew

Android Studio version:

212.5712.43.2112.8512546

</details>

**Comment by darshankawar** [comment]
@daniel-possienke 
Please check [this](https://github.com/flutter/flutter/issues/19680#issuecomment-460797316) comment from Flutter team member.
You may also follow-up in this related issue: https://github.com/flutter/flutter/issues/25377
Based on that, I am going ahead and closing this as WAI. If you disagree, write in comments and I'll reopen it.

**Comment by daniel-possienke** [comment]
@darshankawar Thank you for your answer. I think you misunderstand me. We don't want to use bazel in our flutter project. We are using bazel for other projects and the folder of our flutter project is lying inside that bazel workspace. This wasn't a problem until flutter version 3.0 was released but with this version no import is found anymore. 
Please let me know if you need some more information about this issue.

**Comment by darshankawar** [comment]
Thanks for the feedback @daniel-possienke . Reopening.

**Comment by darshankawar** [comment]
> This wasn't a problem until flutter version 3.0 was released but with this version no import is found anymore.
> Please let me know if you need some more information about this issue.

Please provide more details and steps to replicate so that we can take a look.

**Comment by scheglov** [comment]
Ah, if we have nested `.dart_tool/package_config.json` inside a Bazel workspace, it looks that this will cause an issue. We will [try to find](https://github.com/dart-lang/sdk/blob/28e8202c1408c3dc066cc5c93b10026b17b75095/pkg/analyzer/lib/src/dart/analysis/context_locator.dart#L367) `BazelWorkspace` first, and will find it. But this is not the closest, let's say "workspace defining signal". Instead we should walk the file system up, and at each level look for a signal that we identified the workspace.

**Comment by daniel-possienke** [comment]
@darshankawar Thank you for reopening this issue. The problem is well described [here](https://github.com/Dart-Code/Dart-Code/issues/3976).

**Comment by darshankawar** [comment]
Thanks for the update. Keeping it open and labeling for further investigation from the team.

**Comment by daniel-possienke** [comment]
Are there any news regarding this issue?

**Comment by christopherfujino** [comment]
there was a duplicate bug with some other context that I just closed in https://github.com/flutter/flutter/issues/103895.

Also, the fix for this landed in https://dart-review.googlesource.com/c/sdk/+/248020, but later reverted because it broke internal google tests.

**Comment by christopherfujino** [comment]
The revert: https://dart-review.googlesource.com/c/sdk/+/250946

**Comment by christopherfujino** [comment]
A WIP re-land CL: https://dart-review.googlesource.com/c/sdk/+/251481. This CL is pending an internal fix for the reason the last CL was reverted.

**Comment by christopherfujino** [comment]
> Thanks @christopherfujino for following up! As I understand the revert cl can be submitted as it is. Is it possible to cp the cl to stable once the internal fix landed? We have been blocked by this bug for quite a while and it's getting harder to maintain our app and pull new deps without updating to 3.0+

What version are you on?

**Comment by christopherfujino** [comment]
> > What version are you on?
> 
> We are on Flutter 2.10.5 (Dart SDK 2.16.2).

Unfortunately, per our [cherrypick process](https://github.com/flutter/flutter/wiki/Flutter-Cherrypick-Process), the oldest release that is eligible to receive cherrypicks is the current stable. Thus, even when this gets fixed on master, flutter 2.10 will not receive a cherrypick. Your options from there are either upgrading Flutter or building the Dart SDK from source with the fix and pointing your Flutter SDK at it.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/251481 landed.

**Comment by christopherfujino** [comment]
> > Unfortunately, per our [cherrypick process](https://github.com/flutter/flutter/wiki/Flutter-Cherrypick-Process), the oldest release that is eligible to receive cherrypicks is the current stable. Thus, even when this gets fixed on master, flutter 2.10 will not receive a cherrypick.
> 
> Sorry I meant to cp into the current stable Flutter 3.0.x version (Dart 2.17.x). We do want to upgrade to Flutter 3.0 but without cp, we will have to wait for 3.1 (or even 3.3 in current beta?). @christopherfujino do you think this makes sense?

This makes sense.

So I checked to see if this would merge cleanly to 3.0, but it doesn't. However it does merge cleanly to the 3.3 beta, so I will request a cherrypick for that branch.

**Comment by christopherfujino** [comment]
Here's the tracking issue for cherrypicking to beta (Flutter 3.3.0-0.0.pre) https://github.com/dart-lang/sdk/issues/49544
