### ISSUE TITLE
flutter/packages presubmits are failing in Pigeon test

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#103715]
Example failed run:
https://cirrus-ci.com/task/6322322683461632

This has been blocking the roller for the last 16 hours, and I'm seeing it in one of my own PRs as well. It seems like it's an out-of-band failure, but I'm not sure where from.

**Comment by gaaclarke** [comment]
@stuartmorgan where is the failure happening?  The packages tree has been green (https://github.com/flutter/packages/commits/main) and the submit queue was just green on my PR too I noticed.  Is this flakey?

**Comment by stuartmorgan** [comment]
In presubmits; as I said, it seems to be out-of-band in some way I don't understand.

The last 10 roller attempts all failed on this, for instance.

**Comment by gaaclarke** [comment]
@stuartmorgan it looks like the last roll failure was from `ios-custom_package_tests CHANNEL:master` being cancelled https://github.com/flutter/packages/runs/6424340874 https://github.com/flutter/packages/pull/1927, no?

**Comment by gaaclarke** [comment]
I guess the comment in roll PR says what the description of this PR says, but it doesn't match the status of the last commit which is weird.

**Comment by gaaclarke** [comment]
All of the post commit tests passed after https://github.com/flutter/packages/commit/73a7b6aab2a8e51757b62c424bde62766e8b1cd0  We can try turning the autoroller back on.

**Comment by gaaclarke** [comment]
Rolls have landed, looks good now.
