### ISSUE TITLE
Eliminate CoverageCollector dependency on .package files

### ISSUE THREAD

**Issue by cbracken** [flutter/flutter#103775]
https://github.com/dart-lang/sdk/issues/48272 describes a proposal to eliminate the legacy `.packages` file that was replaced by `package_config.json` in the Dart SDK. In Flutter, we depend on this file in [`CoverageCollector`](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/test/coverage_collector.dart) via the `packagesPath` parameter.

[package:coverage](https://github.com/dart-lang/coverage) deprecated this parameter in https://github.com/dart-lang/coverage/pull/370 (related issue https://github.com/dart-lang/coverage/issues/369) and replaced it with a dependency on the path to the package for which coverage should be computed. See this [dependencies roll](https://github.com/flutter/flutter/pull/103771).

We should remove our dependency on this file in CoverageCollector and file bugs for any other uses of this file we discover.

**Comment by mit-mit** [comment]
Hi @cbracken how is this progressing? We're about to make the change to the Dart SDK to no longer read `.packages`...

**Comment by cbracken** [comment]
I have a patch ready to do but couldn't land it because package:coverage was never rolled to google3, which prevents us from landing it because it would break our roll to google3. See my comment on the package:coverage patch:
https://github.com/dart-lang/coverage/pull/370#issuecomment-1126811828

**Comment by liamappelbe** [comment]
I'm OOO, but I think the roll CL was sent to @grouma

**Comment by cbracken** [comment]
Oddly, I seem to have filed this issue twice on two subsequent days. Probably a product of looking at issues on a weekend as, I suppose, I'm doing right now :/

Closing this one and leaving https://github.com/flutter/flutter/issues/103830 open, since it's got more detail in the issue.

**Comment by cbracken** [comment]
Patch is out in https://github.com/flutter/flutter/pull/104997.
