### ISSUE TITLE
Upgrade Flutter 3.0 from 2.8.1: Warning: Operand of null-aware operation '?.' has type 'PaintingBinding' which excludes null error

### ISSUE THREAD

**Issue by kaanaytemir** [flutter/flutter#103793]
Upgraded to Flutter 3.0 from 2.8.1 and getting the following error:

`Warning: Operand of null-aware operation '?.' has type 'PaintingBinding' which excludes null error`

It's on binding.dart - a file I normally don't touch at all.

`() => PaintingBinding.instance?.imageCache?.evict(key),`
                            ^
Don't know if related, but also seeing this a lot:

`Class 'kotlin.Unit' was compiled with an incompatible version`

**Comment by ferhat097** [comment]
i faced this problem too.

**Comment by deakjahn** [comment]
_Warning_, not error. Expect a _lot_ of plugins to show this until all developers fix their code. If it's in your own code, just remove the question mark everywhere.

**Comment by darshankawar** [comment]
@kaanaytemir 
For the warnings, check out [this](https://docs.flutter.dev/development/tools/sdk/release-notes/release-notes-3.0.0#if-you-see-warnings-about-bindings) link for various solutions and follow-up in https://github.com/flutter/flutter/issues/103561 issue for further updates.

Closing this as a duplicate.

**Comment by kaanaytemir** [comment]
Fixed it myself. Changed my Kotlin version in build.gradle (manually).

buildscript {
    ext.kotlin_version = '1.6.21'
    repositories {
        google()
        jcenter()
    }

**Comment by deakjahn** [comment]
@kaanaytemir Which is a very good thing in itself, it's nice to keep your version up-to-date but it has no influence on this warning, sadly. :-)
