### ISSUE TITLE
Tooltip widget should provide a callback argument

### ISSUE THREAD

**Issue by doppio** [flutter/flutter#103780]
## Use case

I'm interested in sending analytics events when a user triggers a tooltip, but it looks like this isn't possible without a somewhat hacky workaround, like:

- Essentially reimplementing `Tooltip` with the callback functionality
- Using a `Stack` to overlay a `GestureDetector` on top of the tooltip widget
- Adding a new `GestureDetector` as the immediate child of the `Tooltip` -- this seems like a hacky solution

## Proposal

It seems `Tooltip` should offer an `onTriggered` void callback that gets invoked when the user activates it.

**Comment by guidezpl** [comment]
Thanks for filing, this seems reasonable. I'd be happy to review a PR adding this functionality.
