### ISSUE TITLE
How to use our exiting android library in flutter framework?

### ISSUE THREAD

**Issue by dilip90** [flutter/flutter#10379]
How to use our exiting android library in flutter framework?

**Comment by eseidelGoogle** [comment]
@mit-mit this is a documentation question?  Or just pointing to
https://github.com/flutter/flutter/tree/master/examples/flutter_view
or https://flutter.io/platform-channels/ ?

This is a common question.  We clearly have lots of answers.  Just not maybe one in the right place that folks are looking?

**Comment by mit-mit** [comment]
@dilip90 can you elaborate on whether the https://flutter.io/platform-channels/ documentation answers this for you?

**Comment by dilip90** [comment]
I just read that document. Thanks but before starting a new things I want to clear my vision  by looking prons and cons. I just heard this new framework few day ago from my friend I shocked seriously and started questioning myself. There are more doubt but want to go though all the docs by indexing.  
Thanks Google

**Comment by hamedrajabpour** [comment]
hey guys in't there any man in flutter team to answer to this question ?
in web and youtube i found just two tutorial to create plugin

please help 
best regards
