### ISSUE TITLE
Open app with dynamic arguments

### ISSUE THREAD

**Issue by Gustash** [flutter/flutter#10370]
I have been looking into sending arguments to the app when first opening, to open app shortcuts in this instance. But I can't seem to find documentation telling me if this is even possible or not. Is there a way to go about it in Flutter?

**Comment by branflake2267** [comment]
This is probably not what you're looking for, but I think of Firebase dynamic links and/or invites to take you directly into the application. https://firebase.google.com/docs/dynamic-links/

**Comment by Gustash** [comment]
I'll do some testing. It's possible this might work, but this requires platform specific code. I would think that a native Dart implementation would be better. So I guess that if there isn't one right now you can tag this as "New feature"

**Comment by jhirth** [comment]
If you want to differentiate between the first run and subsequent runs, you can simply set a boolean flag with this plugin:

https://pub.dartlang.org/packages/shared_preferences

**Comment by sethladd** [comment]
Thanks for the feedback! What's the use case? When do you want this to happen?

**Comment by mit-mit** [comment]
@szakarias this sounds similar to https://github.com/flutter/flutter/issues/10452 ?

**Comment by cbracken** [comment]
@xster would you mind adding the specific action items here, or closing if none remain?
