### ISSUE TITLE
Add spashColor and highlightColor to IconButton

### ISSUE THREAD

**Issue by arcas0803** [flutter/flutter#10383]
Why icon button does not have the same parameters as flat button in terms of background color, highlightColor, splashColor to control the theme properties?

**Comment by eseidelGoogle** [comment]
@Hixie would know.

**Comment by Hixie** [comment]
No reason really, except that the person who contributed the parameters for flat buttons didn't add them to icon buttons. We'd welcome patches to add highlightColor and splashColor (backgroundColor wouldn't make sense for an icon button).

**Comment by Hixie** [comment]
I think this is done now.
