### ISSUE TITLE
[webview_flutter] getUserMedia does not work

### ISSUE THREAD

**Issue by yaetiya** [flutter/flutter#103851]
## Steps to Reproduce

1. Create app with webview
2. Choose any URL with getUsermedia access (example [Yllo Room] or [Whereby room])
3. The resources will not be able to get the micro connection

[Yllo Room]: https://lllweb.yllo.co/haARM6hZhioP13Ql90zNDWBneRR6tZZj?v=0.22
[Whereby Room]: https://whereby.com/

**Comment by darshankawar** [comment]
This probably looks like similar to https://github.com/flutter/flutter/issues/40791 so please follow-up in it for further updates.
Closing this as a duplicate. If you disagree, write in comments and I'll reopen it.
