### ISSUE TITLE
canvas.drawPoints crashes on the release version of Flutter Web.

### ISSUE THREAD

**Issue by hackware1993** [flutter/flutter#103842]
canvas.drawPoints crashes on the release version of Flutter Web. Windows and Android are no problem. debug version is no problem.

[√] Flutter (Channel stable, 2.10.5, on Microsoft Windows [Version 10.0.19044.1706], locale zh-CN)
    • Flutter version 2.10.5 at D:\Android\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (4 weeks ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at D:\Android\Sdk
    • Platform android-32, build-tools 32.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.2.0)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.2.32505.173
    • Windows 10 SDK version 10.0.20348.0

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] Connected device (3 available)
    • DT1901A (mobile)  • 192.168.0.195:5555 • android-arm64  • Android 10 (API 29)
    • Windows (desktop) • windows            • windows-x64    • Microsoft Windows [Version 10.0.19044.1706]
    • Chrome (web)      • chrome             • web-javascript • Google Chrome 101.0.4951.67

**Comment by hackware1993** [comment]
class TrackPainter extends CustomPainter {
  Queue<Offset> points = Queue();
  Paint painter = Paint();

  TrackPainter(this.points);

  @override
  void paint(Canvas canvas, Size size) {
    /// canvas.drawPoints crashes on the release version of Flutter Web.
    /// Windows and Android are no problem.
    /// debug version is no problem.

    // canvas.drawPoints(PointMode.polygon,points.toList(), painter);

    for (final element in points) {
      canvas.drawCircle(element, 1 / window.devicePixelRatio, painter);
    }
  }

  @override
  bool shouldRepaint(CustomPainter oldDelegate) => true;
}

**Comment by hackware1993** [comment]
https://github.com/hackware1993/Flutter_ConstraintLayout
checkout this project and build release flutter web version. the entry-point is example/main.dart. see example/translate.dart

**Comment by hackware1993** [comment]
![translate.gif](https://github.com/hackware1993/flutter-constraintlayout/blob/master/translate.gif?raw=true)

**Comment by darshankawar** [comment]
@hackware1993 
Thanks for the report. Can you upgrade to latest stable or master and try again to see if you still get same behavior ?
When it crashes according to your findings, does it throw any error / exception log ? If so, can you provide the same here ?

Also, I looked at the github repo you shared which seems to have lot of code under example folder. Is there a way to provide a minimal but sufficient enough code that replicates the crash ? 

Thanks.

**Comment by hackware1993** [comment]
> > @hackware1993 Thanks for the report. Can you upgrade to latest stable or master and try again to see if you still get same behavior ? When it crashes according to your findings, does it throw any error / exception log ? If so, can you provide the same here ?
> > Also, I looked at the github repo you shared which seems to have lot of code under example folder. Is there a way to provide a minimal but sufficient enough code that replicates the crash ?
> > Thanks.
> 
> a minimal but sufficient enough code that replicates the crash, see example/translate.dart。restore my commented out code



> @hackware1993 Thanks for the report. Can you upgrade to latest stable or master and try again to see if you still get same behavior ? When it crashes according to your findings, does it throw any error / exception log ? If so, can you provide the same here ?
> 
> Also, I looked at the github repo you shared which seems to have lot of code under example folder. Is there a way to provide a minimal but sufficient enough code that replicates the crash ?
> 
> Thanks.

I'll try it later with version 3.0

**Comment by hackware1993** [comment]
The last bug about baseline alignment that was raised has not been fixed in 3.0, more than a month has passed.

**Comment by hackware1993** [comment]
3.0 is ok
