### ISSUE TITLE
[web]Disable automatic device rotation on the web

### ISSUE THREAD

**Issue by OnesWYong** [flutter/flutter#103890]
I think on the browser, the page is not automatically rotated according to the device, what should be done to achieve this function.

Specifically, some pages are vertical and some are horizontal. I used SystemChrome.setPreferredOrientations() but that didn't work

**Comment by maheshmnj** [comment]
Hi @OnesWYong, Thanks for filing the issue. When you use `SystemChrome.setPreferredOrientations()` You will basically restrict the orientation. Without any such restriction the flutter web app should respect the device orientation. Here's a sample flutter app to verify https://textfield.netlify.app/#/ Which doesn't use any specific orientation and rotates as per device rotation.

Closing as this doesn't seem like a bug, In case you have a concrete reproducible case to report an issue feel free to write in the comments and we will reopen it.
