### ISSUE TITLE
flutter downgrade bug

### ISSUE THREAD

**Issue by AhmadFalahian** [flutter/flutter#103840]
## Steps to Reproduce

1. When I run flutter downgrade 2.10.5 command it downgrade to version 2.10.2 without considering the version while I want to degrade to version 2.10.5

**Comment by quaaantumdev** [comment]
you can help yourself by checking using git to checkout the tag you'd like. Enter the flutter installation directory and type the following in your command line:

```bash
git checkout tags/2.10.5
flutter --version
```

Stumbled over the same thing, hope that helps for now :)

**Comment by AhmadFalahian** [comment]
> 

Thank you for your guidance
