### ISSUE TITLE
SharedPreferences plugin warns about unsafe/unchecked operations on Android

### ISSUE THREAD

**Issue by lukef** [flutter/flutter#10380]
When compiling a Flutter app using the SharedPreferences plugin on Android you get the following warning/issue:

```
Note: /<user dir>/.pub-cache/hosted/pub.dartlang.org/shared_preferences-0.2.0+1/android/src/main/java/io/flutter/plugins/shared_preferences/SharedPreferencesPlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
```

**Comment by eseidelGoogle** [comment]
@mehmetf did you mean to assign this to yourself?  Do you plan to fix this in Github?

**Comment by mehmetf** [comment]
@eseidelGoogle Yup.

**Comment by mehmetf** [comment]
This should already be fixed actually https://github.com/flutter/plugins/pull/67 which was merged 12 days ago. It did not rev the version though.

@collinjackson I am not sure how plugins are versioned externally. Something looks fishy. Pub repo still shows 0.2.0 as the version of shared perfs plugin so I presume update won't fetch the latest code. Is there anything else that needs to be done here?

**Comment by collinjackson** [comment]
Someone needs to rev the version and publish to pub. We haven't been publishing every time a PR is merged, but perhaps we should? 

Created https://github.com/flutter/plugins/pull/95 to rev the version so we can publish it

**Comment by lukef** [comment]
We can also link to master. Whatever works for you guys.

**Comment by collinjackson** [comment]
I merged https://github.com/flutter/plugins/pull/95 and [published](https://pub.dartlang.org/packages/shared_preferences) it.
