### ISSUE TITLE
[WEB] - Navigator 2.0 - URL #fragment is removed when page is reloaded

### ISSUE THREAD

**Issue by stenlee** [flutter/flutter#103807]
In the web app with Navigator 2.0 and **PathUrlStrategy** the `#fragment` part of the URL/URI is removed when the page is reloaded.
URL Fragments should be preserved as they can be used to navigate inside the page, or invoke an action (show Alert dialog, etc).

Query params are preserved as expected.

**Comment by darshankawar** [comment]
@stenlee 
Please provide `flutter doctor -v` and a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) along with actual vs expected behavior.
Thanks.
