### ISSUE TITLE
Exception caught by widgets library

### ISSUE THREAD

**Issue by palguy** [flutter/flutter#103848]
**### The error:**
type '_InternalLinkedHashMap<String, String?>' is not a subtype of type 'Map<String, String>' in type cast

**### The code**

 ```
`import 'package:flutter/material.dart';

class CategoryTripsScreen extends StatelessWidget {
  const CategoryTripsScreen({
    Key? key,
  }) : super(key: key);

  
@override
  Widget build(BuildContext context) {
    final routeArgument =
        ModalRoute.of(context)!.settings.arguments as Map<String, String>;

    final categoryID = routeArgument['id'];
    final categoryTilte = routeArgument['tilte'];
    return Scaffold(
      appBar: AppBar(
        title: Text(categoryTilte!),
      ),
      body: Center(child: Text('Trip Lists')),
    );
  }
}`
```

**Comment by darshankawar** [comment]
@palguy 
Can you provide `flutter doctor -v` ? Running your code sample on latest stable gives me below:

`type 'Null' is not a subtype of type 'Map<String, String>' in type cast`

Regarding the error you are getting, I think you are hitting same as https://github.com/flutter/flutter/issues/102579, please check that and confirm.

**Comment by palguy** [comment]
[√] Flutter (Channel stable, 3.0.0, on Microsoft Windows [Version 10.0.19044.1706], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.1.5)       
[√] Android Studio (version 2021.1)
[√] VS Code (version 1.67.0)
[√] Connected device (4 available)
[√] HTTP Host Availability

• No issues found!

**Comment by palguy** [comment]
This is the example repositories I am trying to learn -- >
the error line [29]

https://github.com/ammaralkhatib/traveling_app_final/blob/master/lib/screens/category_trips_screen.dart

**Comment by palguy** [comment]
I found out that if I comment on the line -->    title: Text(categoryTilte!),
the screen navigates but without passing the category title to the appBar

**Comment by palguy** [comment]
I SOLVE IT
it's my stupid mistake 
I miss Spelling the (title) instead of  -->routeArgument['tilte'];
this mistake cost me 8 days what a lost 
I am so sorry for wasting your time 
thanks, a lot
