### ISSUE TITLE
[camera][Android] Cannot build app when upgrade flutter to 3.0

### ISSUE THREAD

**Issue by trungtinh961** [flutter/flutter#103886]
## Steps to Reproduce

1. Execute `flutter run` and get error below

<details>
  <summary>Logs</summary>

```
FAILURE: Build failed with an exception.
Execution failed for task ':camera:parseDebugLocalResources'.
  > Could not resolve all files for configuration ':camera:androidApis'.
    > Failed to transform android.jar to match attributes {artifactType=android-platform-attr, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
      > Execution failed for PlatformAttrTransform: ~/Library/Android/sdk/platforms/android-31/android.jar.
        > ~/Library/Android/sdk/platforms/android-31/android.jar
```

</details>

<details>
  <summary>Flutter doctor</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.0, on macOS 12.3.1 21E258 darwin-arm, locale en-VN)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.67.1)
[✓] Connected device (4 available)
[✓] HTTP Host Availability

```

</details>

**Comment by phamquocdai123** [comment]
I got the same issue!

**Comment by LeNguyen0608** [comment]
I got the same issue!

**Comment by maheshmnj** [comment]
Hi @trungtinh961, Thanks for filing the issue. Please share the complete output of `flutter run -v` in a text file along with the output of `flutter doctor -v`.

Thanks

**Comment by trungtinh961** [comment]
@maheshmnj
[run.txt](https://github.com/flutter/flutter/files/8705819/run.txt)
[flutter doctor.txt](https://github.com/flutter/flutter/files/8705825/flutter.doctor.txt)

**Comment by maheshmnj** [comment]
Thanks for the details @trungtinh961, from the logs it looks like Android api 31 is missing.
> [        ]    > Failed to transform android.jar to match attributes {artifactType=android-platform-attr, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
[        ]       > Execution failed for PlatformAttrTransform: /Users/tinhnguyen/Library/Android/sdk/platforms/android-31/android.jar.
[        ]          > /Users/tinhnguyen/Library/Android/sdk/platforms/android-31/android.jar

  Can you please try the solution mentioned here https://stackoverflow.com/a/54248935/8253662

**Comment by trungtinh961** [comment]
@maheshmnj I have tried this solution, I have all `platform-tools` and `platforms;android-31`

**Comment by maheshmnj** [comment]
Thanks for the update @trungtinh961, Can you please share the `app/build.gradle` file to and ensure that the compiledSdk version is set to 31? Also does a newly created flutter app build fine?

**Comment by trungtinh961** [comment]
Thank @maheshmnj for response. I ensure that I had set compiledSdk to 31. I created new project, and also build failed with error above:
`FAILURE: Build failed with an exception.
* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Failed to find target with hash string 'android-31' in: /Users/tinhnguyen/Library/Android/sdk
* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
* Get more help at https://help.gradle.org
BUILD FAILED in 2m 23s
Exception: Gradle task assembleDebug failed with exit code 1`

**Comment by maheshmnj** [comment]
Thanks for the info @trungtinh961,
Can you please share the SDK platforms screenshot in Android Studio and also try to delete(uncheck=> apply) and then recheck Android SDK 31?

![image](https://user-images.githubusercontent.com/31410839/169031835-2e6e0e2e-a076-4fa6-b4df-2c66869c53f8.png)
