### ISSUE TITLE
[google_sign_in] How to pass in Nonce on iOS?

### ISSUE THREAD

**Issue by DanMossa** [flutter/flutter#103867]
Context:
You can **not** pass a rawNonce to `signInWithGoogle`.

When using signInWithGoogle on Android, the returned idToken does not return a nonce. This makes sense because a rawNonce is not passed in.

The same exact code when run on iOS, returns a hashed nonce in the idToken. This does not make sense since we can not pass in a nonce. Where is the nonce coming from?

**Comment by stuartmorgan** [comment]
Issues with the behavior of the sign-in library on iOS would need to be filed [in the SDK's issue tracker](https://github.com/google/GoogleSignIn-iOS/issues). The plugin is just a wrapper around that SDK, which does not support passing a nonce.
