### ISSUE TITLE
Document the flutter equivalents of the lifecycle methods that Android and iOS provide

### ISSUE THREAD

**Issue by FaisalAbid** [flutter/flutter#10388]
There are times where it would be important to know when the Flutter app comes back from the background or goes into the background. I.e Doing some work in the app, phone call comes, the app should have a onPause method and when you are back an onResume.

I found some sample code in this repo (i think) that I think is suppose to do this

```dart
  ByteData message = const StringCodec().encodeMessage('AppLifecycleState.paused');
    BinaryMessages.handlePlatformMessage('flutter/lifecycle', message, (_) {
      print('on pause');
    });
```

Running this however doesn't seem to work as on Pause is logged right away and never again.

The ask here is "What are the flutter equivalents of the lifecycle methods that Android and iOS provide and how can I hook into them?"

**Comment by Hixie** [comment]
https://docs.flutter.io/flutter/widgets/WidgetsBindingObserver/didChangeAppLifecycleState.html

**Comment by Hixie** [comment]
I should add some sample code for these, this is a common question.

**Comment by FaisalAbid** [comment]
Thanks @Hixie , an example of this would be great!

**Comment by sethladd** [comment]
@FaisalAbid , did https://docs.flutter.io/flutter/widgets/WidgetsBindingObserver/didChangeAppLifecycleState.html answer your question?

**Comment by FaisalAbid** [comment]
@sethladd - yea totally did! works great now

**Comment by sethladd** [comment]
Nice! So, we should re-title this issue to be about creating examples, or, close. I'll let @Hixie choose what to do here :)

**Comment by sethladd** [comment]
Does this issue dupe https://github.com/flutter/flutter/issues/7394 ?

**Comment by Hixie** [comment]
Yup.
