### ISSUE TITLE
The extremely bad design of the rotation angle in Flutter is completely confusing!

### ISSUE THREAD

**Issue by hackware1993** [flutter/flutter#103882]
I vomited by Flutter's drawing angle

I encapsulated the angle uniformly into a range of [0.0,360.0]

result :
Transform.rotate is calculated like this: pi + pi * (angle / 180)
canvas.rotate has to be calculated like this: angle * pi / 180
drawArc is calculated like this: -pi / 2, angle * pi / 180

Every one is different.

Why is it so badly designed? ? ?

**Comment by maheshmnj** [comment]
Hi @hackware1993, Thanks for filing the issue. If you think any part of the code could be improved or requires refactoring you are welcome to submit the PR's with a valid rationale for the proposal. Closing as this issue doesn't seem to describe a bug or a feature request. Incase you disagree feel free to write in the comments and we will reopen it. 

Thank you.

**Comment by hackware1993** [comment]
Sorry for my rudeness because I'm just so pissed off. I will try to improve the api and make a pull request.
like this:

degree is between 0.0 - 360.0
Transform.rotateDegree(degree)
canvas.rotateDegree(degree)
drawArc(startDegree, endDegree)
