### ISSUE TITLE
[iOS][Font Bug]flutter 3.0 Chinese font FontWeight.w500 not work

### ISSUE THREAD

**Issue by hhgz9527** [flutter/flutter#103854]
Code:

```dart
TextSpan(
    text: name,
    style: TextStyle(color: Theme.of(context).textTheme.bodyText2!.color, fontSize: 16, fontWeight: FontWeight.w500, height: 1.0),
)
```

before 3.0 version, like this:

<img width="269" alt="image" src="https://user-images.githubusercontent.com/7303158/168475679-e36574c2-3939-4949-be62-1d4317441c87.png">

upgrade to 3.0 version, like this:

<img width="241" alt="image" src="https://user-images.githubusercontent.com/7303158/168475619-32edc90b-3f45-494a-98d3-cc0e5ec49a6b.png">

--------

English keep medium font weight, but Chinese changed regular.

**Comment by darshankawar** [comment]
This probably is similar to https://github.com/flutter/flutter/issues/70164, so please follow-up in it for further updates.
Closing this as a duplicate. If you disagree, write in comments and I'll reopen it.
