### ISSUE TITLE
[Proposal] make _CalendarDateRangePicker part of the public API

### ISSUE THREAD

**Issue by cedvdb** [flutter/flutter#103885]
To show a date range picker, you currently have to call `showDateRangePicker` as per material guidelines.

There are however, lots of use case where showing the range picker fits better if it is not shown inside a dialog. The first example that comes to my head is a booking app where not showing the calendar on the main page would be an UX issue, especially on bigger screen sizes. This is our use case too.

# Proposed

 - Export _CalendarDateRangePicker 
 - Allow customization such that it can work as an effective widget:  
     -  enabled / disabled

**Comment by darshankawar** [comment]
Can you check if [this](https://github.com/flutter/flutter/issues/65108) issue is similar to your case and implementing it would also resolve yours ?

Thanks.

**Comment by cedvdb** [comment]
yes
