### ISSUE TITLE
How to find root cause of incomplete stack trace?

### ISSUE THREAD

**Issue by http600** [flutter/flutter#103898]
It's not unique to see
```
══╡ EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE ╞════════════════════════════════════════════════════
The following _Exception was thrown resolving an image codec:
Exception: Invalid image data

When the exception was thrown, this was the stack:
#0      _futurize (dart:ui/painting.dart:5564:5)
#1      ImageDescriptor.encoded (dart:ui/painting.dart:5432:12)
#2      instantiateImageCodec (dart:ui/painting.dart:2052:60)
<asynchronous suspension>
════════════════════════════════════════════════════════════════════════════════════════════════════
```
the stack backtrace is not complete, How to find where or which image caused the issue?
If I need to give code example, I have to upload all my codes

**Comment by darshankawar** [comment]
@http600 
Can you provide `flutter doctor -v` where it shows incomplete stacktrace ?
There was a similar issue which was resolved indicating it now shows complete verbose stacktrace on latest versions. https://github.com/flutter/flutter/issues/81464
