### ISSUE TITLE
Modifying a flutter app and running it goes back to the old state

### ISSUE THREAD

**Issue by toufikzitouni** [flutter/flutter#10381]
## Steps to Reproduce

- Create a Flutter app on Webstorm
- Make some modifications to main.dart.
- Run the app.
Expected: new changes take effect
Actual: The app goes back to the sample template that was provided on creation

I've attached a video showcasing the bug
[bug.mp4.zip](https://github.com/flutter/flutter/files/1036402/bug.mp4.zip)

**Comment by eseidelGoogle** [comment]
Video as YouTube: https://youtu.be/JrEIbwRKNNk

**Comment by sethladd** [comment]
Let's see if this is something with the IDE or in-general.

Please try this:

* open a terminal
* cd into your project
* type `flutter run`
* make a change to main.dart
* type `r` in the terminal

What happens?

**Comment by a-siva** [comment]
Is this in some sense a dup of #10684

**Comment by a-siva** [comment]
marking this as a duplicate of #12300
