### ISSUE TITLE
[Windows] Remove comments that reference to UWP's issues in BUILD.gn

### ISSUE THREAD

**Issue by moko256** [flutter/flutter#103873]
In the shell/platform/windows/BUILD.gn in engine, this two lines is commented-out, but same contents are already included after the line, and these are referencing closed UWP's issues. We can remove this two lines.

https://github.com/flutter/engine/blob/bd11e1bb701d2ddcc2207adcb685705a1a12c315/shell/platform/windows/BUILD.gn#L172-L173

**Comment by dkwingsmt** [comment]
Nice find! Can you make a PR for it?

**Comment by moko256** [comment]
Yes, I'll send PR in a few hours.

**Comment by moko256** [comment]
I published flutter/engine#33387!
