### ISSUE TITLE
I am not being able to use Flutter on my M1 Mac. 

### ISSUE THREAD

**Issue by saurabhdhingra** [flutter/flutter#103862]
Until last night Flutter was working well on my computer (M1 MacBook Air 2020). Then all of a sudden an error popped up on an open VS Code window saying : "Failed to initialize Flutter: Process exited with code 1." along with a separate pop up saying "Could not find Dart in your Flutter SDK. Please run 'flutter doctor' in the terminal then reload the project once all issues are resolved."

Here's the log of `flutter doctor` :-

```
saurabhdhingra@Saurabhs-Mac trackrecord % flutter doctor
Downloading Darwin arm64 Dart SDK from Flutter engine <<<<<<< HEAD
57d3bac3dd5cb5b0e464ab70e7bc8a0d8cf083ab
=======
d1b9a6938ad77326ac3a94d92bbc77933ed829ed
>>>>>>> ee4e09cce01d6f2d7f4baebd247fde02e5008851...
curl: (3) URL using bad/illegal format or missing URL
/usr/local/Caskroom/flutter/2.2.3/flutter/bin/internal/update_dart_sdk.sh: line 156: return: can only `return' from a function or sourced script
curl: (3) URL using bad/illegal format or missing URL

Failed to retrieve the Dart SDK from: https://storage.googleapis.com/flutter_infra_release/flutter/<<<<<<< HEAD
57d3bac3dd5cb5b0e464ab70e7bc8a0d8cf083ab
=======
d1b9a6938ad77326ac3a94d92bbc77933ed829ed
>>>>>>> ee4e09cce01d6f2d7f4baebd247fde02e5008851/dart-sdk-darwin-arm64.zip
If you're located in China, please see this page:
  https://flutter.dev/community/china
```

I am not living in China.

I tried reinstalling flutter by deleting the flutter folder inside my usr/Developer folder replacing it a fresh folder from [Flutter's official website](https://docs.flutter.dev/get-started/install/macos). I checked my path in the .zshrc file. Please help I need to continue my work urgently.

**Comment by maverick-ai** [comment]
Download the zip and extract the folder. Then set the path to flutter. Flutter will not download from the web. You have missed some steps. I also have an m1 and I installed flutter 3.0  on my new machine by following the steps. There was no error like this. You might have missed some steps in between.

**Comment by darshankawar** [comment]
Try [this](https://github.com/flutter/flutter/issues/91153#issuecomment-933238712) solution which should fix the issue.
Closing from here.

**Comment by saurabhdhingra** [comment]
So should I just replace the flutter folder and replace it with a freshly downloaded one from the Flutter website ?

I did this and restarted my system as well but it didn't help.

**Comment by saurabhdhingra** [comment]
Here are some new logs : 

`git status` inside the flutter folder
```
[Saurabhs-Mac:flutter saurabhdhingra$ git status
On branch stable
Your branch is up to date with 'origin/stable'.

nothing to commit, working tree clean
```

Then I did `git reset --hard`

```
[Saurabhs-Mac:flutter saurabhdhingra$ git reset --hard
HEAD is now at ee4e09cce0 [flutter_releases] Flutter stable 2.13.0 Framework Cherrypicks (#103375)

```

Now here's `flutter doctor -v`

```
[Saurabhs-Mac:flutter saurabhdhingra$ flutter doctor -v
Downloading Darwin arm64 Dart SDK from Flutter engine <<<<<<< HEAD
57d3bac3dd5cb5b0e464ab70e7bc8a0d8cf083ab
=======
d1b9a6938ad77326ac3a94d92bbc77933ed829ed
>>>>>>> ee4e09cce01d6f2d7f4baebd247fde02e5008851...
curl: (3) URL using bad/illegal format or missing URL
/usr/local/Caskroom/flutter/2.2.3/flutter/bin/internal/update_dart_sdk.sh: line 156: return: can only `return' from a function or sourced script
curl: (3) URL using bad/illegal format or missing URL

Failed to retrieve the Dart SDK from: https://storage.googleapis.com/flutter_infra_release/flutter/<<<<<<< HEAD
57d3bac3dd5cb5b0e464ab70e7bc8a0d8cf083ab
=======
d1b9a6938ad77326ac3a94d92bbc77933ed829ed
>>>>>>> ee4e09cce01d6f2d7f4baebd247fde02e5008851/dart-sdk-darwin-arm64.zip
If you're located in China, please see this page:
  https://flutter.dev/community/china


```

Checked my path as well. 

```
Saurabhs-Mac:flutter saurabhdhingra$ which flutter
/usr/local/bin/flutter
```

**Comment by darshankawar** [comment]
@saurabhdhingra 
How are you downloading / installing the sdk ? Are you using any other tool to extract it ?  Can you try to manually extract it instead of any other tool you are using and check ?

Also check this related link for your reference: https://stackoverflow.com/questions/70281885/why-is-this-illegal-url-error-appearing-when-running-flutter-doctor

**Comment by saurabhdhingra** [comment]
I downloaded the flutter zip folder for apple Silicon on Flutter’s offiicial website. I manually extracted the folder into the path I have specified. 

Believe me I didn’t do anything to cause it. I didn’t even `flutter upgrade`. It started happening out of nowhere on Saturday night.

**Comment by saurabhdhingra** [comment]
I have solved this issue now. 

Here's what I did. I downloaded a fresh flutter SDK and replaced the existing one in my `$PATH`.

Checked my path variable in `.zshrc` file. (since my `$SHELL` was set to `zsh`. It will be different for you if your shell is different. For example: for `bash` it will be `.bashrc` )

For Apple Silicon we need to install flutter with HomeBrew. So I went to my `usr/local/Caskroom` and deleted the flutter folder there and ran `brew install --cask flutter`. 

After this the flutter doctor was running well but my Dart SDK wasn't configured well and I couldn't run my projects. I was getting [this](https://stackoverflow.com/questions/67268972/get-an-unexpected-kernel-sdk-version-error-when-running-flutter-project-in-and) error. 

The first answer helped. You need to delete your Cache in the $HOME/'pwd'/flutter/bin and run `flutter doctor`. 

Thank you everyone for trying to help me.
