### ISSUE TITLE
[tool_crash] FormatException

### ISSUE THREAD

**Issue by askmegit** [flutter/flutter#103880]
## Command
```
flutter build ios --release --no-codesign --no-tree-shake-icons
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FormatException
```
#0      _Utf8Decoder.convertChunked (dart:convert-patch/convert_patch.dart:1892:7)
#1      _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:314:28)
#2      _Utf8ConversionSink.add (dart:convert/string_conversion.dart:310:5)
#3      _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:72:18)
#4      _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:111:24)
#5      _rootRunUnary (dart:async/zone.dart:1362:47)
#6      _CustomZone.runUnary (dart:async/zone.dart:1265:19)
#7      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
#8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#9      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#10     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
#11     _StreamController._add (dart:async/stream_controller.dart:607:7)
#12     _StreamController.add (dart:async/stream_controller.dart:554:5)
#13     _Socket._onData (dart:io-patch/socket_patch.dart:2160:41)
#14     _rootRunUnary (dart:async/zone.dart:1370:13)
#15     _CustomZone.runUnary (dart:async/zone.dart:1265:19)
#16     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
#17     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#18     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#19     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
#20     _StreamController._add (dart:async/stream_controller.dart:607:7)
#21     _StreamController.add (dart:async/stream_controller.dart:554:5)
#22     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1696:33)
#23     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1208:14)
#24     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
```
```
[✓] Flutter (Channel dev, 2.3.0-0.1.pre, on macOS 11.2.3 20D91 darwin-arm, locale zh-Hans-CN)
    • Flutter version 2.3.0-0.1.pre at /Users/hellotalk/Applications/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d72bfb8d07 (1 year, 1 month ago), 2021-04-26 06:05:55 -0700
    • Engine revision de6e1adf97
    • Dart version 2.14.0 (build 2.14.0-18.0.dev)

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 101.0.4951.64
    ! Error: Jersey 11 is not connected. Xcode will continue when Jersey 11 is connected. (code -13)

! Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Type**: null
**Version**: 1.0.0+1
**Material**: true
**Android X**: true
**Module**: true
**Plugin**: false
**Android package**: com.hellotalk
**iOS bundle identifier**: com.helloTalk.helloTalk
**Creation channel**: null
**Creation framework version**: null
### Plugins
audio_session-0.1.6+1
audioplayers-0.19.1
connectivity-0.4.6+2
device_info-0.4.2+6
device_info_plus-3.2.3
device_info_plus_linux-2.1.1
device_info_plus_macos-2.2.3
device_info_plus_web-2.1.0
device_info_plus_windows-2.1.1
flutter_boost-4e3790e50531af786d86d0c9b0f502ee4865a460
flutter_current_locale-3eb501f2df34cbda861baf62dfa76ca8084b814b
flutter_handle_url-db909737236c89791b4cd927f87568a164119e53
flutter_secure_storage-3.3.5
flutter_sound-9.2.12
flutter_sound_web-9.2.12
flutter_webview_plugin-0.4.0
flutter_break_iterator-032a4e22664c4c198a9b59a0e4dffeb9e1ba7fc7
fluttertoast-8.0.9
get_ip-0.4.0
ht_audioplayer-6c3a32f94f65b1aece53c33491917fa56ee3e30f
ht_flutter_plugin_deviceid-f360f2dbc4e654712cc07d96d5e2505a68875ec4
just_audio-0.9.21
just_audio_web-0.4.7
launch_review-2.0.0
orientation-1.3.0
package_info-0.4.3+4
package_info_plus-1.4.2
package_info_plus_linux-1.0.5
package_info_plus_macos-1.3.0
package_info_plus_web-1.0.5
package_info_plus_windows-1.0.5
path_provider-2.0.2
path_provider_linux-2.1.5
path_provider_macos-2.0.5
path_provider_windows-2.0.5
permission_handler-6.1.3
sensors-2.0.3
share-0.6.5+4
shared_preferences-2.0.7
shared_preferences_linux-2.0.4
shared_preferences_macos-2.0.2
shared_preferences_web-2.0.3
shared_preferences_windows-2.0.4
sqflite-2.0.2
system_proxy-0.1.0
tingyun_flutter_plugin-1.0.2
unique_ids-1.1.1
url_launcher-6.0.10
url_launcher_linux-2.0.3
url_launcher_macos-2.0.3
url_launcher_web-2.0.7
url_launcher_windows-2.0.2
vibration-1.7.3
vibration_web-1.6.2
video_player-2.2.3
video_player_web-2.0.8
wakelock
wakelock_macos-0.4.0
wakelock_web-0.4.0
webview_flutter-2.0.13

**Comment by maheshmnj** [comment]
Hi @askmegit, Thanks for filing the issue. 

There is a similar issue describing this case  https://github.com/flutter/flutter/issues/81666, Please follow up there for further updates, Closing this issue as a duplicate. If you disagree feel free to write in the comments and we will reopen it.

Thank you.
