### ISSUE TITLE
Kurdish is currently available in Google Translate, but has not yet been added to the flutter_localization

### ISSUE THREAD

**Issue by aminsamad** [flutter/flutter#103826]
Hello, 

Kurdish is currently available in [**Google Translate** ](https://translate.google.com/?sl=ckb&tl=en&op=translate), but has not yet been added to the flutter_localization package! Do you plan to add Kurdish to this package? Because we really need to have Kurdish language officially in our apps. Kurdistan country code is "**ckb**" I hope you add it soon.

Thanks.

**Comment by darshankawar** [comment]
Closing this as duplicate of https://github.com/flutter/flutter/issues/57216
