### ISSUE TITLE
Flutter web  TextOverflow.ellipsis 

### ISSUE THREAD

**Issue by Jovines** [flutter/flutter#103815]
Chinese
<img width="407" alt="image" src="https://user-images.githubusercontent.com/44845663/168440385-46d360f2-541a-4149-af91-b4d67902a681.png">
<img width="1186" alt="image" src="https://user-images.githubusercontent.com/44845663/168440392-b2342716-9647-44b5-816d-c969bf788d6c.png">

Character
<img width="455" alt="image" src="https://user-images.githubusercontent.com/44845663/168440409-53b204f2-d19a-4df2-81fa-2c3f8ae2d823.png">
<img width="1190" alt="image" src="https://user-images.githubusercontent.com/44845663/168440419-6df010b0-b3e7-468d-81ea-6c9035c664b8.png">

Japanese
<img width="485" alt="image" src="https://user-images.githubusercontent.com/44845663/168440457-ac347e93-7a64-4c34-a909-441a06ef63f5.png">
<img width="1189" alt="image" src="https://user-images.githubusercontent.com/44845663/168440466-1511117b-d093-4032-bdb6-47acf1563064.png">

<img width="1105" alt="image" src="https://user-images.githubusercontent.com/44845663/168440508-77280d65-e5af-4dbf-8901-da50b0a30cff.png">
I tried the stable, beta and master.

**Comment by darshankawar** [comment]
This seems to be similar to https://github.com/flutter/flutter/issues/90135, so please follow-up in it for further updates.
Closing this as a duplicate.
