### ISSUE TITLE
Listen to Listview/GridView scroll events

### ISSUE THREAD

**Issue by FaisalAbid** [flutter/flutter#10393]
I'm trying to build an infinite scrolling grid/listview but trying to understand how I can listen to the scroll events to detect when my listview/gridview has reached the end

```
  return new GridView.extent(
        maxCrossAxisExtent: 200.0,
        padding: const EdgeInsets.all(4.0),
        mainAxisSpacing: 4.0,
        crossAxisSpacing: 4.0,
        children: girlsList);
```

**Comment by FaisalAbid** [comment]
Ah its ScrollController I belive! Closing this off till I run into issues again

**Comment by long1eu** [comment]
Hi! Do you have a working example of this?
