### ISSUE TITLE
Flutter assembleDebug freeze my pc

### ISSUE THREAD

**Issue by Asmitta-01** [flutter/flutter#103900]
hello
When i press F5 or when i run `flutter doctor -v`, the execution (assembleDebug) goes normally but after a moment my pc freeze. 
I usually shut it down, by plugging it out. Even after one hour it stays frozen. How can i solve this please ? 
My question : https://superuser.com/q/1721272/1263237

**Comment by darshankawar** [comment]
@Asmitta-01 
When you open an issue, please use new issue template and fill out requested details so that we'll have enough details to work with. 
For now, in order to address your issue properly, provide `flutter doctor -v`, steps to replicate that shows current behavior and any error log that shows up indicating a freeze.

**Comment by Asmitta-01** [comment]
Thanks for the reply
I ran `flutter run -v | tee ./logs.txt` and here is this log file: https://paste-bin.xyz/58417
My pc stucked two times and this time i didn't shut it down but left it and but it stopped my emulator(i just remark it at the end, since it was frozen).
The two times were:

1. After Line 152, so i think it is this task that consume too much resources : `[+170964 ms] > Task :app:mergeDexDebug`
2. At line 225 `[+171719 ms] executing: /home/asmitta/Android/Sdk/platform-tools/adb -s emulator-5554 shell pm list packages com.example.sensor_app` this instruction also.

So what do you think about it please.

**Comment by darshankawar** [comment]
From the verbose log you shared, I don't see any obvious errors in it. Also, the apk seems to be have been built properly and installed on the device successfully according to the logs.

Are you making use of heavy network calls, images or doing heavy processing on main thread ? A code sample would be helpful to understand this issue better.

**Comment by Asmitta-01** [comment]
My .apk file is running normally when launching on the emulator directly (installing it normally, no 'debug'). My code is following this example: https://pub.dev/packages/flutter_sensors/example , i just added few lines for others sensors. 
I pressed now on F5 on vscode and the `Running assembleDebug task` ends wth this output: 
```
Launching lib/main.dart on Android SDK built for x86 in debug mode...
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
adb: device 'emulator-5554' not found
Error: ADB exited with exit code 255
Performing Push Install
adb: error: failed to get feature set: device 'emulator-5554' not found
Error launching application on Android SDK built for x86.
Exited (sigterm)
```
The apk is again successfully created but it is not 'automatically' launched in the emulator, i have to do it 'manually'. And when the task is running, my pc is frozen. Now it takes less time but it is still frozen at that moment.

**Comment by Asmitta-01** [comment]
My .apk file is running normally when launching on the emulator directly (installing it normally, no 'debug'). My code is following this example: https://pub.dev/packages/flutter_sensors/example , i just added few lines for others sensors. 
I pressed now on F5 on vscode and the `Running assembleDebug task` ends wth this output: 
```
Launching lib/main.dart on Android SDK built for x86 in debug mode...
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
adb: device 'emulator-5554' not found
Error: ADB exited with exit code 255
Performing Push Install
adb: error: failed to get feature set: device 'emulator-5554' not found
Error launching application on Android SDK built for x86.
Exited (sigterm)
```
The apk is again successfully created but it is not 'automatically' launched in the emulator, i have to do it 'manually'. And when the task is running, my pc is frozen. Now it takes less time but it is still frozen at that moment. After the 'freeze time;, the android emulator was again closed.

**Comment by Asmitta-01** [comment]
Please i precise that the android where i install apk file and successfully run it is on another pc. The one linked with vscode was installed by android studio and i didn't know how to install an apk manually, but after researchs i found and i get this on it while trying to install : `'pm install-create -r -t --user current --full -S 56798401' returns error 'Unknown failure: Error: java.lang.NumberFormatException: Invalid int: "current"'`

**Comment by darshankawar** [comment]
@Asmitta-01 
Maybe it has to do with your code and apk installation on emulator and its cpu architecture which may not be supporting the apk you are trying to build. 
Probably your app is making use of native libs that are not compatible with emulator you are trying to build. Also the fact that you are using flutter_sensors which is third party plugin. 
You may try to create a new Flutter project without any third party plugins and try the same steps and see if you still get the freeze or not. If not, then it may be related to the plugin code and you'll need to reach out to dedicated plugin's repo.

Closing from here for now.

**Comment by Asmitta-01** [comment]
Thanks for your support @darshankawar 
I tried to run `flutter run` many times and now my pc doesn't freeze again during the process, after many light freezes. I have my apk file and i do `flutter install` to push it on my android device. All works well now. Thanks again for your availability
