### ISSUE TITLE
[google_maps_flutter_web] update google_maps dependency to latest release

### ISSUE THREAD

**Issue by hmbenhaim** [flutter/flutter#103987]
## [google_maps_flutter_web] update google_maps dependency to latest release

i'm using google_maps_flutter_web which is using google_maps: 5.2.0, the latest release is 6.1.0
I have tested google_maps_flutter_web with google_maps: 6.1.0 and it works just fine
I would like to propose  if you can update google_maps dependency to the latest release which is 6.1.0,
it causess that I can't install other packages that use google_maps: 6.1.0
thank you

**Comment by maheshmnj** [comment]
Hi @hmbenhaim, Thanks for filing the issue. Labeling this issue as a valid proposal to update the google maps dependency in the google_maps_web plugin.

**Comment by ditman** [comment]
Coincidentally, I'm currently working on this right now. I'll link this issue in the appropriate PR!

**Comment by ditman** [comment]
This has been published as `package:google_maps_flutter_web: ^0.3.3`.
