### ISSUE TITLE
Flutter 3.0 causes issues with Android Platform views

### ISSUE THREAD

**Issue by felix-ht** [flutter/flutter#103907]
Upgrading to flutter 3.0 breaks apps using https://github.com/flutter-mapbox-gl/maps

- Views render in the wrong position/scale
- Views disregard stacking
- Page transitions cause issues
- The app crashes after navigation
- Effects both with Hybrid and normal composition

See https://github.com/flutter-mapbox-gl/maps/issues/1041 for more details

## Steps to Reproduce
Install the example app from 

1. checkout https://github.com/flutter-mapbox-gl/maps and run the the example app (docs for this are in the readme)
2. go to `Place symbol`

**Expected results:** 

App renders fine

**Actual results:** 
It does not

**Comment by maheshmnj** [comment]
Hi @felix-ht, thanks for reporting the issue.

I see there is a similar issue, describing this case https://github.com/flutter/flutter/issues/103630, Please follow up there for further updates, Closing this issue as a duplicate. If you disagree feel free to write in the comments and we will reopen it.

Thank you.

**Comment by felix-ht** [comment]
No it is indeed a duplicate!
