### ISSUE TITLE
Fix Typo the Compiling the engine wiki

### ISSUE THREAD

**Issue by daisuke0715** [flutter/flutter#103901]
## Corresponding section
Hello.

I found what appears to be a typo when building the FlutterEngine environment.

There is a typo in the file path for the command option in the section corresponding to Compiling for iOS (from macOS) in step 5 of Compiling the engine.

```
# incorrect description
out/out/ios_debug_unopt_arm

# correct description
out/ios_debug_unopt_arm
```

<img width="1068" alt="スクリーンショット 2022-05-16 22 59 00" src="https://user-images.githubusercontent.com/38068379/168611051-2eafde0a-f1ac-403c-a6a7-750c33d4d6bd.png">

**Comment by timsneath** [comment]
iPhone 4s is no longer supported in current builds of Flutter (Flutter 3 was the last release to support it). Should we simply remove these instructions now, @jmagman?

**Comment by jmagman** [comment]
Great idea, done: https://github.com/flutter/flutter/wiki/Compiling-the-engine/_compare/9310fa56017b04c87fa0728af53a71d7baa63f17...b6e2df5d0afa2f70b439c82182701abd7834e1c3
