### ISSUE TITLE
Dropdown button crash

### ISSUE THREAD

**Issue by emshack** [flutter/flutter#10390]
## Steps to Reproduce

I ran `flutter create` and replaced the body of `main.dart` with the following code building a basic dropdown button:

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(new MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: 'Flutter Demo',
      theme: new ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see
        // the application has a blue toolbar. Then, without quitting
        // the app, try changing the primarySwatch below to Colors.green
        // and then invoke "hot reload" (press "r" in the console where
        // you ran "flutter run", or press Run > Hot Reload App in IntelliJ).
        // Notice that the counter didn't reset back to zero -- the application
        // is not restarted.
        primarySwatch: Colors.blue,
      ),
      home: new MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  // This widget is the home page of your application. It is stateful,
  // meaning that it has a State object (defined below) that contains
  // fields that affect how it looks.

  // This class is the configuration for the state. It holds the
  // values (in this case the title) provided by the parent (in this
  // case the App widget) and used by the build method of the State.
  // Fields in a Widget subclass are always marked "final".

  final String title;

  @override
  _MyHomePageState createState() => new _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  String dropdown1Value = 'One';

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance
    // as done by the _incrementCounter method above.
    // The Flutter framework has been optimized to make rerunning
    // build methods fast, so that you can just rebuild anything that
    // needs updating rather than having to individually change
    // instances of widgets.
    return new Scaffold(
        appBar: new AppBar(
        // Here we take the value from the MyHomePage object that
        // was created by the App.build method, and use it to set
        // our appbar title.
          title: new Text(widget.title),
        ),
        body: new DropdownButton<String>(
            value: dropdown1Value,
            onChanged: (String newValue) {
              setState(() {
                dropdown1Value = newValue;
              });
            },
            items: <String>['One', 'Two', 'Free', 'Four'].map((String value) {
              return new DropdownMenuItem<String>(
                value: value,
                child: new Text(value),
              );
            }).toList(),
          ),

    );
  }
}
```

I'm seeing strange behavior from the dropdown button when trying to run this. On 
the iOS Simulator, when I select any option in the dropdown button other than 'One', and then reopen the button, all text inside briefly loads, then goes blank and reloads. I don't see any console messages when this happens. When I run the same code on Mac with SkyShell and perform the same interaction, it completely crashes rather than going blank and reloading. Here, I do see an error message:

```
../../third_party/skia/include/core/SkRRect.h:144: fatal error: "assert(this->isValid())"
Abort trap: 6
```

## Flutter Doctor

[✓] Flutter (on Mac OS X 10.12.4 16E195, channel alpha)
    • Flutter at /Users/emshack/flutter
    • Framework revision 973304d5fb (12 days ago), 2017-05-18 17:31:57 -0700
    • Engine revision f99d3ef108
    • Tools Dart version 1.23.0-dev.11.11

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at /Users/emshack/Library/Android/sdk
    • Platform android-25, build-tools 25.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3.1, Build version 8E1000a
    • ios-deploy 1.9.1
    • CocoaPods version 1.2.0

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Gradle version 3.2
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2016.3.4)
    • Dart plugin version 163.13137
    • Flutter plugin version 12.1

[✓] Connected devices
    • iPhone 7 Plus • 09A7F58D-C832-4D91-B681-F67134E64361 • ios • iOS 10.3 (simulator)

**Comment by chinmaygarde** [comment]
I am not able to reproduce the crash or the text going blank and reloading on ToT.

**Comment by emshack** [comment]
Interesting... I switched my copy of flutter from alpha to master and am not seeing the bug. Still seeing it on alpha though. Can you reproduce it on alpha?

**Comment by Hixie** [comment]
@HansMuller fixed this on master. It'll be resolved on alpha when we next roll.
