### ISSUE TITLE
An issue about native view in Flutter stack parent layout

### ISSUE THREAD

**Issue by wxkly8888** [flutter/flutter#103953]
I am using native view embed in flutter view. it works great before flutter 3.0, after I upgraded the flutter SDK to 3.0, some strange behavior happened.

Here is my flutter view:

```dart
 Stack(
children: <Widget>[
   Container(
     width: 300,
     height: 200,
     decoration: BoxDecoration(
       color: Colors.red,
     ),
  ),
    SizedBox(
      width: 100,
      height:400,
     child: AndroidView(
      viewType: "video_player",
      creationParamsCodec: const StandardMessageCodec(),
    ),)
  ,
  Container(
    width: 300,
    height: 300,
    decoration: BoxDecoration(
      color: Colors.green,
    ),
  ),
],
)
```

`AndroidView` is android `SurfaceView` view. here is my android view code:

```
import android.content.Context
import android.graphics.*
import android.view.SurfaceHolder
import android.view.SurfaceView

class MysurfaceView(context: Context?) : SurfaceView(context), SurfaceHolder.Callback {


    //线程
    internal inner class MyThread : Runnable {
        override fun run() {
            val canvas: Canvas = holder.lockCanvas(null) //获取画布
            val mPaint = Paint()
            mPaint.setColor(Color.BLACK)
            canvas.drawRect(Rect(100,100,100,100), mPaint)
            holder.unlockCanvasAndPost(canvas);
        }
    }

    init {
        val holder = this.getHolder() //获取holder
        holder.addCallback(this)
        setBackgroundColor(Color.BLACK)
        //setFocusable(true);
    }

    override fun surfaceCreated(holder: SurfaceHolder) {
        Thread(MyThread()).start()
    }

    override fun surfaceChanged(holder: SurfaceHolder, format: Int, width: Int, height: Int) {

    }

    override fun surfaceDestroyed(holder: SurfaceHolder) {

    }
}
```

the AndroidView is supposed to covered by the green flutter view. like bellow:

![image-20220517113639188](https://github.com/wxkly8888/flutter3.0_bugdemo/blob/master/screenshot/361652758568.jpg)

  But actually with flutter 3.0,  the `Androidview` is on the top of flutter view, here is the screenshot:

![image-20220517113900531](https://github.com/wxkly8888/flutter3.0_bugdemo/blob/master/screenshot/371652758727.jpg)

​     this demo is here https://github.com/wxkly8888/flutter3.0_bugdemo

**Comment by maheshmnj** [comment]
Hi @wxkly8888,

There is a similar issue describing this case https://github.com/flutter/flutter/issues/103630, Please follow up there for further updates, Closing this issue as a duplicate. If you disagree feel free to write in the comments and we will reopen it.

Thank you.
