### ISSUE TITLE
[cross_file] Wrong unimplemented error message

### ISSUE THREAD

**Issue by NazarenoCavazzon** [flutter/flutter#103930]
## Use case

Let's say that you didn't implement lastModified() on a class, the error that it will throw you is "lastModified() has not been implemented." instead of "openRead() has not been implemented.".

## Proposal

Modify XFileBase unimplemented error message on the lastModified function.

![image](https://user-images.githubusercontent.com/49735945/168682229-5856068e-eb90-4e00-98ca-fdfa5cf58b70.png)

**Comment by huycozy** [comment]
Hi @NazarenoCavazzon, 
Thanks for filing the issue. As my understanding, the issue should be described as:
> "Let's say that you didn't implement lastModified() on a class, the error that it will throw you is "openRead() has not been implemented." instead of "lastModified() has not been implemented."

Refer to source code: https://github.com/flutter/packages/blob/main/packages/cross_file/lib/src/types/base.dart#L85

Please update the issue and also share the output of `flutter doctor -v` in the issue.
