### ISSUE TITLE
Remove iOS OpenGL backend

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#103929]
Remove the fallback for older iOS versions and hardware, and only use the engine Metal backend on iOS.
This will reduce app binary size, team maintenance burden, and testing matrix.

**Comment by jmagman** [comment]
Note: make sure this doesn't wind up breaking OpenGL on macOS.  macOS 10.11 is the minimum supported version, which can run on some hardware that doesn't support Metal.
/cc @zanderso @stuartmorgan

**Comment by jmagman** [comment]
macOS 10.13 is no the minimum, which can still run on some hardware that doesn't support Metal per https://support.apple.com/en-us/HT205073 and  https://support.apple.com/kb/sp765?locale=en_US

**Comment by jmagman** [comment]
cc @cbracken

**Comment by cbracken** [comment]
Related macOS issue: https://github.com/flutter/flutter/issues/108304

**Comment by zanderso** [comment]
First part here https://github.com/flutter/engine/pull/34913. That saved ~100KB compressed. Second part is here https://github.com/flutter/engine/pull/34924 from @chinmaygarde

**Comment by zanderso** [comment]
I think this is done. I didn't notice any additional binary savings after the second part landed, so presumably our LTO is doing its job

**Comment by chinmaygarde** [comment]
Seems so. I did verify that the additional TUs weren't being compiled after the second part landed.

**Comment by jmagman** [comment]
@zanderso did this pass on a TAP run?

**Comment by zanderso** [comment]
Yes, the internal roll is caught up nearly to tip-of-tree. It is amazing.

**Comment by jmagman** [comment]
Thanks @zanderso and @chinmaygarde!
