### ISSUE TITLE
[go_router_builder] pageBuilder missing GoRouterState

### ISSUE THREAD

**Issue by leoshusar** [flutter/flutter#103985]
The `go_router_builder` [documentation](https://pub.dev/packages/go_router_builder#transitions) says you can access the `GoRouterState` object in `pageBuilder` and even shows an example:

...
If you'd like to change how the page is created, e.g. to use a different page
type, pass non-default parameters when creating the page (like a custom key) **or
access the `GoRouteState` object**, you can override the `buildPage` method of the
base class instead of the `build` method:
...
### Custom transitions

Overriding the `buildPage` method is also useful for custom transitions:

```dart
class FancyRoute extends GoRouteData {
  @override
  MaterialPage<void> buildPage(BuildContext context, GoRouterState state) =>
    CustomTransitionPage<void>(
      key: state.pageKey,
      child: FancyPage(),
      transitionsBuilder: (context, animation, animation2, child) =>
          RotationTransition(turns: animation, child: child),
    ),
}
```
...

but in reality the `pageBuilder` method is defined like this:

```dart
Page<void> buildPage(BuildContext context) => const NoOpPage();
```

so either the documentation is wrong or the `pageBuilder` method signature.

**Comment by huycozy** [comment]
Hi. I've seen this issue mentioned [here](https://github.com/flutter/flutter/issues/102713) but it doesn't seem to have been resolved through the comments. I will keep this issue open for further investigation. 
Also refer to [source](https://github.com/flutter/packages/blob/9440d04d527781e0023fcbdb1eda3cd55efc203c/packages/go_router/lib/src/route_data.dart#L41) for this.

**Comment by chunhtai** [comment]
this also applies to GoRouteData.build

**Comment by chunhtai** [comment]
You can use GoRouteState.of() of context to get the goRouteState, we should make sure the documentation is clear

**Comment by leoshusar** [comment]
Looks like [`GoRouterState`](https://github.com/flutter/packages/blob/main/packages/go_router/lib/src/go_router_state.dart) doesn't have `of(context)`
![image](https://user-images.githubusercontent.com/13891066/169436599-907f1c39-5370-4a2a-97ff-c0394eb753df.png)

**Comment by chunhtai** [comment]
For some reason i kept thinking GoRouterState is part of context, and it apparently is not. I think we should make it part of the context so that we don't need to keep passing goRouterState around different build method

**Comment by danielmahon** [comment]
this is currently a blocking issue for me to move to the typed builder, especially for route level redirects. There is currently no other good way to implement redirect guards, etc. I think it should be as simple as just passing the state through each method call. They are still being cached unless I'm missing a reason why this won't work.

```dart
    Widget builder(BuildContext context, GoRouterState state) =>
        factoryImpl(state).build(context, state);

    Page<void> pageBuilder(BuildContext context, GoRouterState state) =>
        factoryImpl(state).buildPage(context, state);

    String? redirect(GoRouterState state) {
      return factoryImpl(state).redirect(state);
    }
```
