### ISSUE TITLE
[fuchsia_ctl] Remove `pubspec.lock` from git

### ISSUE THREAD

**Issue by nilsreichardt** [flutter/flutter#103970]
Regarding the Dart guidelines, we should not commit the `pubspec.lock` for library packages: https://dart.dev/guides/libraries/private-files#pubspeclock.

Therefore, we should remove the `pubspec.lock` for the [fuchsia_ctl](https://github.com/flutter/packages/tree/main/packages/fuchsia_ctl) package

**Comment by stuartmorgan** [comment]
`fuchsia_ctl` is intended as a tool, not a library. That file is there deliberately.

**Comment by nilsreichardt** [comment]
Ah, makes sense
