### ISSUE TITLE
Infra failing frequently on Mac_arm64_ios build_ios_framework_module_test

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#103990]
I triggered a re-run, but this has been failing a lot, so I'm not hopeful:

https://ci.chromium.org/p/flutter/builders/prod/Mac_arm64_ios%20build_ios_framework_module_test?limit=100

**Comment by keyonghan** [comment]
This is being tracked in https://github.com/flutter/flutter/issues/103910
