### ISSUE TITLE
Xcode <Flutter/Flutter.h> file not found, after adding Share Extension to project

### ISSUE THREAD

**Issue by mobikats** [flutter/flutter#103977]
I am stuck with this build issue, which looks similar to others reported eg   #94265, #101025

```
ios/Runner/GeneratedPluginRegistrant.h:10:9: error: 'Flutter/Flutter.h' file not found
#import <Flutter/Flutter.h>
        ^
1 error generated.
<unknown>:0: error: failed to emit precompiled header 

```
It occurs after carefully adding a Share Extension to the Xcode workspace and configuring it according to this article:
https://medium.com/flutter-community/receive-sharing-files-to-flutter-app-from-another-app-7a84c0c0cd88

The "solutions" appear to be limited to deleting the iOS folder, and then recreating it. 
I have done that, however as soon as I then add back in the share extension, I am left with the same problem.

I have so far tried the following, as well as many others since forgotten, and in many different combinations:
- flutter clean
- delete DerivedData folder
- rm Podfile.lock and rm -rf Pods, follow by arch -x86_64 pod install --repo-update
- Cocoapods updated

I am running on an M1 Macbook Pro

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.0, on macOS 12.2 21D49 darwin-arm, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
[✓] Chrome - develop for the web
[!] Android Studio
    ✗ Unable to find bundled Java version.
[✓] Android Studio (version 4.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.3)
[✓] VS Code (version 1.67.1)
[✓] Connected device (5 available)
[✓] HTTP Host Availability
```

I have seen the project build and run for the Simulator, but I cannot reliably say what changed or why, and right now it is back to not even building for simulator after I attempted a device build (which failed as above).

Additional notes
- My targets (Runner, ShareExtension, Pods) are all set to build for iOS14
- ShareExtension has the same bundle id as the Runner project with "Share-Extension" appended.
- Bitcode not enabled

Thanks in advance for any help

**Comment by darshankawar** [comment]
@mobikats 
Please provide complete `flutter run -v` log. It'll be huge so you can put that in a text file and share it here.

Also, in XCode flutter specific build settings for your base configuration, do you have the share extension also configured for `debug` mode ?

If so, it should be set to `None` like for your profile and release build.

**Comment by mobikats** [comment]
Thanks for your quick response @darshankawar 
I will attach that log output shortly, but I am not sure exactly what you mean by "configured for debug mode" - sorry!

Information format? Optimization level? And I don't think Xcode has any build settings that are flutter specific, although it uses flutter-set-environment variables?

Here's a filtered screenshot incase useful:
![Screenshot 2022-05-17 at 17 43 41](https://user-images.githubusercontent.com/5747434/168852893-8b0cd90e-dbbb-4d32-b37e-ecd1caffcc8e.png)

**Comment by darshankawar** [comment]
@mobikats 
Like shown in below screenshot.

<img width="754" alt="test" src="https://user-images.githubusercontent.com/67046386/168962392-39d47f68-0b82-4983-8bc8-4bbb97bcd8b4.png">

**Comment by mobikats** [comment]
Thanks - funnily enough it took me awhile to find that section, and I don't recall ever changing it, but actually it is already set to None :/

Maybe something else there should be changed?

![Screenshot 2022-05-18 at 11 28 01](https://user-images.githubusercontent.com/5747434/169006995-4dc21486-a0a5-4e8c-9251-8bed51e48408.png)

**Comment by darshankawar** [comment]
Thanks for the update @mobikats . Good that it is set to `none` so my doubt has been cleared.
Next step would be to provide complete `flutter run -v` log.

**Comment by mobikats** [comment]
Thanks for your attention @darshankawar, and I now have it running via flutter run -v on a device and on simulator!

But what is very odd is that:
- Xcode build still fails
- VSCode build fails in the same way
- Script using xcodebuild fails

However, given that flutter run -v succeeds, I should be able to inspect that and determine what it is, and by the sounds of it, it will come down to a scheme or build argument somewhere set incorrectly.

`flutter run -v`

- Picks the default scheme "Runner", whereas I am using my "dev" scheme - so the problem must be in there somewhere, as a result of perhaps an outdated run of the "flutter_flavorizr" package.

Thanks for your help @darshankawar ! I had just about run out of morale for trying to solve this, your attention has pushed me if not to the top of the hill then to a position where I can at least see it and know that it exists! :)

**Comment by darshankawar** [comment]
Glad to know I was of help to diagnose the issue further. I'll keep this issue open until you are able to resolve this issue. If not, we can take it further.

**Comment by mobikats** [comment]
Thanks @darshankawar, I've given up with the flavor schemes for now, but this problem is solved - I don't know what the actual specific problem was, but it happens in the flavor schemes created by flutter_flavorizer. I've deleted them and will live without them for now.

**Comment by darshankawar** [comment]
`flutter_flavorizer` seems to be third party plugin, so you may reach out to plugin owner on potential fix in it if applicable.

**Comment by Klabauterman** [comment]
@mobikats I had the same issue and solved it.

I created new configurations using flutter_flavorizer for my app that has two targets: the main app and a share extension. The newly created schemas for the share extension had a bridging header ("Objective-C Bridging Header") set that referenced to flutter stuff that was not build for the app extension. The solution was to remove them. So you just need to compare the old configurations of your extension target with the newly created ones and you might find it.
