### ISSUE TITLE
[fuchsia_ctl] unit tests failed on windows platform

### ISSUE THREAD

**Issue by chunhtai** [flutter/flutter#103991]
failed instance

https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8814226430734410449/+/u/Run_package_tests/custom_package_tests/stdout

```
00:00 +8 -1: test\emulator_test.dart: Emulator prepare environment runs as expected [E]
  Expected: true
    Actual: <false>
  
  package:test_api              expect
  test\emulator_test.dart 56:7  main.<fn>.<fn>
  
00:00 +9 -1: test\image_paver_test.dart: Tar fails
```

Fuchsia_ctl is currently skipped, we should figure out whether this can be fix or not

**Comment by stuartmorgan** [comment]
This package was removed.
