### ISSUE TITLE
 [iOS] Integration Flutter Module | Swift - List widgets won't scroll on iOS

### ISSUE THREAD

**Issue by romaCaldeira** [flutter/flutter#103997]
1- Create a simple Flutter app (module) with a single page including ListView or SingleChildScrollView. Append as many children as possible to make it scrollable.
2- Create a simple iOS native app, which has two controllers. Controller A has a button which initializes controller B. Controller B initializes and adds FlutterViewController into itself.
3- Run the app on the simulator using Xcode 13, IOS version 10 or later, Flutter 2.10.5

**Comment by danagbemava-nc** [comment]
Hi @romaCaldeira, thanks for filing the issue. 

Please provide a complete runnable minimal code sample, preferably in a repo, that we can run and investigate further.

Can you also check if you still experience this issue on flutter 3? If you do, please provide the updated `flutter doctor -v` as well.

Thank you

**Comment by see** [comment]
my app crashes

<img width="1484" alt="截屏2022-06-02 19 15 57" src="https://user-images.githubusercontent.com/19725091/171617697-b7a0b8c9-9a4c-4a04-918a-1b95c0dcc42b.png">

**Comment by danagbemava-nc** [comment]
Hi @see, kindly file a new issue and provide the relevant information required to investigate this issue. 

Your issue seems unrelated to this.
