### ISSUE TITLE
Enable SUPPORT_FRACTIONAL_TRANSLATION for desktop (and mobile if benchmarks permit)

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#103909]
See https://github.com/flutter/engine/search?q=SUPPORT_FRACTIONAL_TRANSLATION

Enabling SUPPORT_FRACTIONAL_TRANSLATION removes the physical pixel snap from engine layers. It is off by default due to mobile performance issues, specifically on iOS32 bit but potentially on newer devices as well. See also https://github.com/flutter/flutter/issues/56722

Unfortunately there are two major drawbacks of having this disabled, namely:

* The physical pixel snap is much more noticeable on platforms that have lower DPRs. On desktop, close to 1.0 is common and that causes issues such as https://github.com/flutter/flutter/issues/71008.

* The physical pixel snap causes flutter_tester to render nearly identical UI differently based on whether or not an engine composited layer is updated. This causes problems rolling into google3 due to the large number of golden tests, for example https://github.com/flutter/flutter/pull/102274

We should opt desktop into this define. This will require us to separately roll an engine variant with this enabled that would allow us to gradually opt-in google3.

Migration process:

* Build a new engine host variant (linux is the only variant used for golden testing in g3) and roll that into google3. This variant will have SUPPORT_FRACTIONAL_TRANSLATION enabled and no raster cache in the tester.

* Run a global presubmit in g3 to determine the impact of switching to the new tester. If the number of diffs is small, do this as an atomic change. If the number of diffs is large, then we'll perform a project by project opt-in, and finally switch the default to the new tester.

* Once this has landed, we update the engine build rules so that all host variants are build with SUPPORT_FRACTIONAL_TRANSLATION. After this rolls into g3, we can switch the build rules back to the previous tester variant in a non-breaking way - since it should have the same rendering output as the new tester.

* Finally, we delete the new engine variant.

**Comment by jonahwilliams** [comment]
FYI @goderbauer , once we update g3 to this I think we could probably back out the opacity changes with no change to scuba diffs

**Comment by jonahwilliams** [comment]
Alternatively, we may need to keep a variant without fractional translation enabled since we may not run all of the same tests on the platform variants

**Comment by Hixie** [comment]
Another option would be to make this runtime configurable, with a flag on the layers themselves, and slowly opt more and more layers into it (maybe conditionally opting out on certain platforms and/or dpr situations).

**Comment by jonahwilliams** [comment]
we couldn't opt even a single layer in without a repeat of the physical model layer roll unfortunately - removing pixel snapping from one layer would cascade down to each picture. We'd have to do project by project code changes, which unlike changes just to the tester/goldens we couldn't approve without OWNERS verification

**Comment by jonahwilliams** [comment]
From b/233382771 , all internal clients have been migrated

**Comment by jonahwilliams** [comment]
I've opted desktop/tester in by default.

Waiting for that to roll to google3 so we can delete fractional tester. Similarly waiting https://github.com/flutter/engine/pull/34141 to evaluate performance

**Comment by jonahwilliams** [comment]
Last remaining task is to wait for another google3 roll and remove the fractional tester infra

**Comment by jonahwilliams** [comment]
This is now fixed
