### ISSUE TITLE
[flutter_releases] Cocoon failing to add branches on GitHub branch create event

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#103996]
This is prevent rollers from being able to easily locate the results for their branches. It seems the cron job logic is working as expected.

**Comment by XilaiZhang** [comment]
yep this is weird. I created test cases with the exact json input as shown in the log, and the test passes. I tried many variation of test cases and they show up successfully in data base. Also checked log and there was no exception raised. everything seems to have worked except the entity was not added to database. Would be great if Casey could offer some idea on possible causes, thank you!

**Comment by XilaiZhang** [comment]
Yep, the json file shown in the appengine log looks legit. I copied the exact json and pass it to cocoon test and it works well. Not sure why it was not added to database.

**Comment by XilaiZhang** [comment]
I also created a test branch called 'test-branch-xilaizhang' on flutter/flutter, it showed up both in database and on dashboard. I could not reproduce the loss of data problem

**Comment by CaseyHillers** [comment]
What if a branch is pushed instead of being created through the UI

**Comment by XilaiZhang** [comment]
the two requests, processed after yesterday's fix was deployed, look good. I will check back when we have more data points

**Comment by XilaiZhang** [comment]
@itsjustkevin feel free to post your observations here if you see anything
