### ISSUE TITLE
75% of windows android capacity is down

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#103942]
* Flutter-win-1 is quarantined with >1024 files in temp
* flutter-win-2 and flutter-win-3 are dead

**Comment by godofredoc** [comment]
Flutter-win-1/2 were recovered. Flutter-win-3 is not reachable over ssh.

**Comment by zanderso** [comment]
flutter-win-2 has been down for >1 day it says? I am bumping this back up to P0 since a failing Windows test means that it takes many hours for the tree to re-open.

**Comment by godofredoc** [comment]
flutter-win-2 is not running the machine tokend as a service.

flutter-win-3, and flutter-win-4 do not have a dns entry.

flutter-win-5 registered mac address is incorrect.

**Comment by CaseyHillers** [comment]
As an update, this seems to be blocking the tree from being able to reopen right now due to the long queue time

**Comment by godofredoc** [comment]
Are the test-beds down again? at least two of them should be up and running.

@yusuf-goog did you get any updates about the dns configs?

**Comment by yusuf-goog** [comment]
win-1,3 are up. I will follow up on the others.

**Comment by godofredoc** [comment]
win-2 is not refreshing the token even though the command is running. The phone connected to win-4 is auto disabling the developer options.

**Comment by godofredoc** [comment]
win-2 has been fixed. It required an update to the to the scheduled task after updating the swarming password.

**Comment by yusuf-goog** [comment]
Note: if you happen to change the password, you need to also change the autologin password entry.

**Comment by godofredoc** [comment]
Closing as the only remaining issue is related to a phone.
