### ISSUE TITLE
Flutter in a Fragment, when showing keyboard, does not update insets/metrics

### ISSUE THREAD

**Issue by monkeyswarm** [flutter/flutter#103921]
Our Flutter Android app must embed Flutter within a Fragment (not an Activity). We have some layout issues when showing the keyboard.

When Flutter is in a Fragment, and the keyboard is shown, the Flutter `widgetsBinding.window.viewInsets.bottom` is always zero, and `didChangeMetrics()` is never called. This yields bad layout while the keyboard is shown (e.g. dialogs are centered 'underneath' the keyboard, cannot autoscroll to focus nodes, etc).

Note we prefer to use `android:windowSoftInputMode="adjustNothing"` instead of `adjustResize`, since there is a one-frame jank when resizing the Flutter window between full-screen and above the keyboard. (Android stretches the fragment, then Flutter catches up and rebuilds). When previously using `adjustResize`, `didChangeMetrics()` was called, but the insets were still unchanged.

## Steps to Reproduce

1. Embed Flutter in an Android fragment (with `android:windowSoftInputMode="adjustNothing"`, to keep the window size constant)
2. Use SafeArea and Scaffold (with resizeToAvoidBottomInset left unset, defaulting to true)
3. Tap a TextField to show keyboard

**Expected results:** 
- Update window insets, which will rebuild the content to within the new bounds (allowing scroll-to-focus, recentering of dialogs, etc)
- `didChangeMetrics()` is called

**Actual results:** 
- window Insets never change (bottom inset is always at zero), layout is unchanged
- `didChangeMetrics()` is never called

**Comment by felix-mittermeier** [comment]
Probably related to https://github.com/flutter/flutter/issues/103630

**Comment by blasten** [comment]
those two issues aren't related

**Comment by dowski** [comment]
Further update: setting `resizeToAvoidBottomInset` on `Scaffold` fixes the issue for Android API 29+ as far as I can tell. However for lower API levels, `didChangeMetrics` isn't called because `FlutterView.onApplyWindowInsets` isn't getting called.

**Comment by dowski** [comment]
This is starting to look like a bug on our side - we're hosting a FlutterFragment and we weren't properly piping through various lifecycle calls, most critically `onPostResume`.

**Comment by chinmaygarde** [comment]
@blasten Are you still working on this? If not, can you update the assignee and reprioritize? @dowski Any updates on if this is an Add2App bug?

**Comment by blasten** [comment]
This is a documentation issue. I filed https://github.com/flutter/flutter/issues/104297.  This issue can be closed.
