### ISSUE TITLE
Math and a Matrix4 is required to rotate something 15 degrees

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#10398]
This is a feature request :)

Looks like Flutter has a `Transform` class that takes low-level arguments like alignment and a Matrix4. Developers familiar with the web might be looking for higher-level convenience transform abilities, without having to bust out math or a Matrix4.

For example, it would be cool if there was an easy way to: translate, scale, rotate, and skew. Maybe there is, and I didn't find it?

Strawman idea:

`new Translate.rotate(degrees: 15.0, child: ...)`

`new Translate.skew(x: 5, y: 5, child: ...)`

etc...

(inspired by https://flutter.io/web-analogs/#rotating-components)

**Comment by Hixie** [comment]
`new Translate(transform: new Matrix4.rotationZ(math.PI / 12.0))`

(where `math.PI / 12.0` is 15 degrees in radians)

But I can add examples to Transform, for sure.

**Comment by Hixie** [comment]
We can also totally add constructors to Transfrom

**Comment by Hixie** [comment]
(Though it's not clear exactly what point you'd want to rotate around? Or whether you want this to affect the layout... There's RotatedBox if you want to do a 90 degree turn.)

**Comment by sethladd** [comment]
> We can also totally add constructors to Transfrom like Transform.rotation or some such.

Yes, please!! :)

**Comment by sethladd** [comment]
Cool! Can you link the PR to this issue, for posterity?

**Comment by Hixie** [comment]
https://github.com/flutter/flutter/pull/10519

(I've been doing documentation as big patches to make it more efficient on my side.)

**Comment by sethladd** [comment]
Very cool! Thank you.
