### ISSUE TITLE
Error when run app with debugger (VS Code) and run copy via terminal

### ISSUE THREAD

**Issue by alex9153** [flutter/flutter#104060]
<details>
<summary>logs</summary>

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:cleanMergeDebugAssets'.
> java.io.IOException: Unable to delete directory '/Users/aleks/Projects/WORK/homm3_web/build/app/intermediates/assets/debug/mergeDebugAssets'
    Failed to delete some children. This might happen because a process has files open or has its working directory set in the target directory.
    - /Users/aleks/Projects/WORK/homm3_web/build/app/intermediates/assets/debug/mergeDebugAssets/flutter_assets/resources/images/magic/ls_lightning_strike
    - /Users/aleks/Projects/WORK/homm3_web/build/app/intermediates/assets/debug/mergeDebugAssets/flutter_assets/resources/images/magic/ls_force_field
    - /Users/aleks/Projects/WORK/homm3_web/build/app/intermediates/assets/debug/mergeDebugAssets/flutter_assets/resources/images/magic/ls_minefield
    - /Users/aleks/Projects/WORK/homm3_web/build/app/intermediates/assets/debug/mergeDebugAssets/flutter_assets/resources/images/magic/ls_healing
    - /Users/aleks/Projects/WORK/homm3_web/build/app/intermediates/assets/debug/mergeDebugAssets/flutter_assets/resources/images/magic/ls_stone_skin
    - /Users/aleks/Projects/WORK/homm3_web/build/app/intermediates/assets/debug/mergeDebugAssets/flutter_assets/resources/images/magic/ls_resurrection
    - /Users/aleks/Projects/WORK/homm3_web/build/app/intermediates/assets/debug/mergeDebugAssets/flutter_assets/resources/images/magic/ls_anti_magic
    - /Users/aleks/Projects/WORK/homm3_web/build/app/intermediates/assets/debug/mergeDebugAssets/flutter_assets/resources/images/magic/ls_implosion
    - /Users/aleks/Projects/WORK/homm3_web/build/app/intermediates/assets/debug/mergeDebugAssets/flutter_assets/resources/images/magic/ls_blindness
    - /Users/aleks/Projects/WORK/homm3_web/build/app/intermediates/assets/debug/mergeDebugAssets/flutter_assets/resources/images/magic/ls_fire_wall
    - /Users/aleks/Projects/WORK/homm3_web/build/app/intermediates/assets/debug/mergeDebugAssets/flutter_assets/resources/images/magic/ls_water_defense
    - /Users/aleks/Projects/WORK/homm3_web/build/app/intermediates/assets/debug/mergeDebugAssets/flutter_assets/resources/images/magic/ls_forgetfulness
    - /Users/aleks/Projects/WORK/homm3_web/build/app/intermediates/assets/debug/mergeDebugAssets/flutter_assets/resources/images/magic/ls_air_defense
    - /Users/aleks/Projects/WORK/homm3_web/build/app/intermediates/assets/debug/mergeDebugAssets/flutter_assets/resources/images/magic/ls_sadness
    - /Users/aleks/Projects/WORK/homm3_web/build/app/intermediates/assets/debug/mergeDebugAssets/flutter_assets/resources/images/magic/ls_mirth
    - /Users/aleks/Projects/WORK/homm3_web/build/app/intermediates/assets/debug/mergeDebugAssets/flutter_assets/resources/images/magic/ls_counter_attack
    - and more ...
    New files were found. This might happen because a process is still writing to the target directory.
    - /Users/aleks/Projects/WORK/homm3_web/build/app/intermediates/assets/debug/mergeDebugAssets/flutter_assets
    - /Users/aleks/Projects/WORK/homm3_web/build/app/intermediates/assets/debug/mergeDebugAssets/flutter_assets/resources
    - /Users/aleks/Projects/WORK/homm3_web/build/app/intermediates/assets/debug/mergeDebugAssets/flutter_assets/resources/images
    - /Users/aleks/Projects/WORK/homm3_web/build/app/intermediates/assets/debug/mergeDebugAssets/flutter_assets/resources/images/units/battle/stronghold
    - /Users/aleks/Projects/WORK/homm3_web/build/app/intermediates/assets/debug/mergeDebugAssets/flutter_assets/resources/images/units/battle/stronghold/roc

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 49s
Running Gradle task 'assembleDebug'...                             49,9s
Exception: Gradle task assembleDebug failed with exit code 1
```
</details>

**Comment by danagbemava-nc** [comment]
Hi @alex9153, please provide the output of `flutter doctor -v` as well as the full verbose logs of the command you ran when you faced this issue. 

Do you have this issue with the default flutter app?

**Comment by alex9153** [comment]
the issue with the default flutter app. Concurrent build not working.



iMac-Aleksey:homm3_web aleks$ flutter doctor -v
[✓] Flutter (Channel stable, 3.0.0, on macOS 12.2 21D49 darwin-x64, locale ru-RU)
    • Flutter version 3.0.0 at /Users/aleks/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ee4e09cce0 (9 days ago), 2022-05-09 16:45:18 -0700
    • Engine revision d1b9a6938a
    • Dart version 2.17.0
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/aleks/Library/Android/sdk
    • Platform android-32, build-tools 32.0.0
    • ANDROID_HOME = /Users/aleks/Library/Android/sdk
    • Java binary at: /Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_321-b07)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code (version 1.66.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Connected device (4 available)
    • ZB602KL (mobile) • J6AXB7654974VZ8 • android-arm64  • Android 9 (API 28)
    • SM T970 (mobile) • R52N71EFXPN     • android-arm64  • Android 12 (API 31)
    • macOS (desktop)  • macos           • darwin-x64     • macOS 12.2 21D49 darwin-x64
    • Chrome (web)     • chrome          • web-javascript • Google Chrome 101.0.4951.64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Comment by danagbemava-nc** [comment]
Hi @alex9153, please provide the steps to reproduce as well as the full verbose logs of `flutter run -v`. The output of this might be too huge for github, so kindly put it into a .txt file and attach it here.

Thank you
