### ISSUE TITLE
[Impeller] Add a RenderTargetBuilder with common presets

### ISSUE THREAD

**Issue by bdero** [flutter/flutter#104006]
Make RenderTarget setup more convenient and readable. As per: https://github.com/flutter/engine/pull/33413#discussion_r874376631

**Comment by ColdPaleLight** [comment]
Closing it via linked PR.

**Comment by dnfield** [comment]
The patch is getting reverted again.

There's a non-trivial inter-relationship between render targets and their properties - if we do in fact agree on a builder API, it's going to have to either have more guards around it or more methods that take multiple parameters and make it clear when certain parameter types are incompatible. The patch has landed twice now in ways that broke existing usage of the API.

**Comment by chinmaygarde** [comment]
This would have been nice to have but we haven't run into the need for this recently. Closing this as won't fix.
