### ISSUE TITLE
WebView blocked after open bottom sheet or alert dialog(these issues happen just on iOS devices, in android working fine).

### ISSUE THREAD

**Issue by emanuelzallikodelabs** [flutter/flutter#104059]
The first time the URL is loaded web view is working fine, but if I want to open an alert dialog or bottom sheet after those if I want to zoom or whatever, the web view is totally blocked!

**Comment by danagbemava-nc** [comment]
Hi @emanuelzallikodelabs, please provide a complete minimal reproducible code sample that we can use to verify this. Please also provide the output of `flutter doctor -v` and the version of `webview_flutter` you're experiencing this issue with. 

Thank you
