### ISSUE TITLE
Firebase Phone Number Authentication

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#10404]
There was a request to the firebase-talk@ list about using Firebase Phone Number Authentication with Flutter.

Docs:

* https://firebase.google.com/docs/auth/ios/phone-auth
* https://firebase.google.com/docs/auth/android/phone-auth

**Comment by driftavalli** [comment]
Having this available will be great for emerging markets as Android is the more dominant OS and phone numbers have more penetration when compared with emails.

**Comment by Solido** [comment]
Our roadmap is build around this feature. A lot of mobile application now rely on this.

**Comment by eseidelGoogle** [comment]
Flutter's firebase_auth is just a wrapper around the Firebase SDKs themselves:
https://github.com/flutter/plugins/tree/master/packages/firebase_auth
patches are certainly welcome.  @collinjackson wrote the existing wrappers.  I don't know how much work it would be to add these additional apis.

**Comment by collinjackson** [comment]
I think this would be straightforward to add, and I'd be happy to do it. But I'm doing a lot of things, so pull requests are welcome if anyone feels blocked on this.

**Comment by PrimeNexes** [comment]
Any Updates on this ?

**Comment by eliezedeck** [comment]
+1

**Comment by CrazyStaff** [comment]
I would like to use this feature too. Is there a progress ?

**Comment by fjbatresv** [comment]
I am needing this for a new app... Some progress?

**Comment by FakhruddinAbdi** [comment]
+1

**Comment by long1eu** [comment]
I want to build this. Is anyone available to help?

**Comment by alibitek** [comment]
This is my attempt to add support for Firebase phone number authentication on the Android platform: https://github.com/flutter/plugins/pull/329

Feel free to provide any feedback regarding the design and implementation.

**Comment by alibitek** [comment]
Besides adding some UX improvements as mentioned in https://github.com/flutter/plugins/pull/329#issuecomment-355340771 by:
- trying to autocomplete the user's phone number using the Smart Lock API  
- auto validating the verification code via SMS Retriever API  
the Android implementation is ready for review.

I can't help with the iOS implementation so it would be really awesome if someone can contribute this part.
Is an implementation on both platforms mandatory before this feature is added to the firebase_auth plugin?

**Comment by PrimeNexes** [comment]
Has anyone tried [flutter/plugins#329 (comment)](https://github.com/flutter/plugins/pull/329#issuecomment-355340771)
?

**Comment by alibitek** [comment]
@PrimeNexes I've implemented SmartLock support in the [firebase_auth_android_smartlock branch](https://github.com/alibitek/plugins/commit/0b00311ceb1435241bb47ca1033259df4e846a7e) , however I couldn't test it as the hint is not coming back for the Google account I tested with.
As the [Firebase UI docs](https://github.com/firebase/FirebaseUI-Android/blob/master/auth/README.md#smart-lock) mentions, I think I need to store the user's credentials in SmartLock after a successful authentication and then it'll work, as the phone number cannot be retrieved automatically by other means.

**Comment by PrimeNexes** [comment]
@alibitek I just want to implement phone auth it's basic feature. The current google sign in is not something that I can build upon for my app, phone auth will help me to at least have a base to built my app on. 
You think this will at least give me something to work with ? Or I have to work more when the official build comes by  ?

**Comment by pauldemarco** [comment]
Friendly ping :smile:

**Comment by vikas10foodvite** [comment]
Is there any update on this?

**Comment by mohith7548** [comment]
How to do Phone authentication in Flutter using Firebase? Can anyone tell me? I need the code snippet very badly. I'm doing an App for my college. It needs the user to be verified using the phone number.

**Comment by zoechi** [comment]
Work in progress

- flutter/plugins#329
- flutter/plugins#484

**Comment by Peet-A** [comment]
need it asap for more than project ,

**Comment by d7h** [comment]
+1

**Comment by teamrdy** [comment]
+1

**Comment by adityasodhani** [comment]
Friendly ping.

**Comment by mohith7548** [comment]
Is phone Authentication can now be done in flutter ?? Is PR submitted? I want to use it

**Comment by zoechi** [comment]
https://github.com/flutter/plugins/pull/606 is the current work and it's still work-in-progress.

**Comment by saltpetreca** [comment]
Any update on Firebase Phone Auth using flutter? Is there any ETA on the horizon?

**Comment by mmcc007** [comment]
@saltpetreca flutter/plugins#606 PR is currently in review. The phone auth feature in the example provided works for me. If interested, u can test the PR by adding the following to your `pubspec.yaml`:
```
  firebase_auth:
    git:
      url: git@github.com:flutter/plugins.git
      path: packages/firebase_auth
      ref: 075897e
```

**Comment by saltpetreca** [comment]
Thanks will take a look. 

On Jul 3, 2018, at 11:42 AM, Maurice McCabe <notifications@github.com> wrote:

@saltpetreca flutter/plugins#606 PR is currently in review. The phone auth feature in the example provided works for me. If interested, u can test the PR by adding the following to your pubspec.yaml:

  firebase_auth:
    git:
      url: git@github.com:flutter/plugins.git
      path: packages/firebase_auth
      ref: 075897e

**Comment by singlakaran** [comment]
go to this link
https://stackoverflow.com/questions/50181000/how-to-do-phone-authentication-in-flutter-using-firebase/56823147#56823147

**Comment by kroikie** [comment]
@sethladd

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1006. Any further collaboration will be done there.

**Comment by rahmanrezaee** [comment]
how send code in PhoneVerificationCompleted method 
cuase varify the phone again
