### ISSUE TITLE
Tree redness caused by `BOT_DIED` on flutter-devicelab-linux-12 

### ISSUE THREAD

**Issue by LongCatIsLooong** [flutter/flutter#104098]
https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-linux-12#

Example failures:
https://ci.chromium.org/p/flutter/builders/prod/Linux_android%20flutter_test_performance

**Comment by keyonghan** [comment]
Manually quarantine the bot /cc @godofredoc 

@LongCatIsLooong Could you help rerun the failed builds to bring the tree back?

**Comment by godofredoc** [comment]
None of the devicelab bots are able to reach the salt masters.

**Comment by godofredoc** [comment]
Test bed has been recovered and passing the tests successfully.
