### ISSUE TITLE
RenderSliverGrid lies about having visual overflow

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#104046]
There's a comment saying `// Conservative to avoid complexity`.

I'd like to make this more accurate, since having visual overflow here will trigger additional clipping that may not be necessary _and_ will make some debug checking I'm interested in adding for https://github.com/flutter/flutter/issues/103068 harder.

/cc @Piinks @goderbauer fyi

**Comment by dnfield** [comment]
Looks like `RenderSliverScrollingPersistentHeader` does the same with the same comment.

**Comment by Piinks** [comment]
I checked the git history on this, it's from 2017. 😄 

While the comment in RenderSliverGrid does not provide much explanation, I did find similar patterns elsewhere that were a bit more informative:

From `RenderSliverFixedExtentBoxAdaptor`
` // Conservative to avoid flickering away the clip during scroll.`

https://github.com/flutter/flutter/blob/1ecb52e2f8978b1de65f0300a6f6ae90fa28bc6b/packages/flutter/lib/src/rendering/sliver_fixed_extent_list.dart#L306

From `RenderSliverList`
`// Conservative to avoid flickering away the clip during scroll.`

https://github.com/flutter/flutter/blob/6eb65b376d822b7aa87372b7a001d839836eeb23/packages/flutter/lib/src/rendering/sliver_list.dart#L331


I wasn't able to find a test related to these classes covering overflow or flickering, but we should make sure we aren't introducing a flicker in the RenderSliverGrid change.
