### ISSUE TITLE
Support mac_arm64 host only test configuration

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#104034]
Create `mac_arm64` configuration for host-only tests to be run on arm Macs, similar to:
https://github.com/flutter/flutter/blob/4b1ff134596196d31d5b324ecb997ac0340187db/.ci.yaml#L49-L56

For example, `Mac_arm64_ios macos_chrome_dev_mode` does not need a tethered iOS device to pass.

cc @keyonghan

**Comment by a-wallen** [comment]
Desktop team has macos compile and start up devicelab tests on our OKRs. For the time being, it looks like we will have to use `Mac_ios_arm64` devices instead of `Mac_arm64` so that we are not blocked.

**Comment by keyonghan** [comment]
> Desktop team has macos compile and start up devicelab tests on our OKRs. For the time being, it looks like we will have to use Mac_ios_arm64 devices instead of Mac_arm64 so that we are not blocked.

Unblock: https://github.com/flutter/flutter/pull/110050.
Let's use host only bots if they do not need a device.

**Comment by keyonghan** [comment]
@jmagman is this implemented?

**Comment by keyonghan** [comment]
Yeah, it's there: https://github.com/flutter/flutter/blob/master/.ci.yaml#L130. Closing.

**Comment by jmagman** [comment]
https://github.com/flutter/flutter/blob/78390a086dccdc2a29118570da9addc9b6fb6b35/.ci.yaml#L81

I can't actually use it anywhere because of https://github.com/flutter/flutter/pull/109889 though. But yes it's technically present...
