### ISSUE TITLE
Initial scroll is off when using scroll with tabs

### ISSUE THREAD

**Issue by vlidholt** [flutter/flutter#10405]
## Steps to Reproduce

When placing scroll views inside tabs the initial scroll is off on tabs. The offset grows by the tab number. See video:

https://www.youtube.com/watch?v=w2rQfbFdWAo

```
[✓] Flutter (on Mac OS X 10.12.4 16E195, locale en-US, channel master)
    • Flutter at /Users/vik/Projects/flutter
    • Framework revision 87c5b24e87 (16 hours ago), 2017-05-30 16:45:54 -0700
    • Engine revision 75c74dc463
    • Tools Dart version 1.24.0-dev.3.0

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.2)
    • Android SDK at /Users/vik/Library/Android/sdk
    • Platform android-25, build-tools 25.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.3.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3.2, Build version 8E2002
    • ios-deploy 1.9.1
    • CocoaPods version 1.2.0

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Gradle version 3.2
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2016.3.4)
    • Dart plugin version 163.13137
    • Flutter plugin version 0.1.11.1

[✓] Connected devices
    • iPhone SE • B19052F4-91FF-48C7-85B4-26C1D2D1A148 • ios • iOS 10.3 (simulator)
```

**Comment by eseidelGoogle** [comment]
Specifically @vlidholt means the scroll-offset changes.  All of the tabs are expected to be scrolled to the top (grey bar), but notice that they each are scrolled progressively more as he tabs through.

@HansMuller would know.

**Comment by vlidholt** [comment]
Thanks for the clarification, was a bit in a rush. :)

**Comment by HansMuller** [comment]
I wasn't able to reproduce the problem with the current version of  NewsVoice or with the tabs demo from Flutter Gallery (Android).  It's possible for NestedScrollViews to affect the scroll offset of their siblings, but you're not using NestedScrollView.

Does the bug manifest itself the same way on a device as the emulator?

**Comment by vlidholt** [comment]
It's the same on device and simulator. I can try to make a reduced test case.

**Comment by vlidholt** [comment]
I made a reduced test case here: https://github.com/vlidholt/flutter_bug_scroll

The bug happens when the tab bar is scrolled. Looks like the tab bar offset is used as an offset in the scroll list.

**Comment by vlidholt** [comment]
@HansMuller

**Comment by vlidholt** [comment]
Video of the issue
https://www.youtube.com/watch?v=qgqRbMi3IVo

Also, possibly related, the scroll offset of the tab you are going to is affected by the offset in the current tab. But it behaves differently if you are pressing the tabs at the top or if you are swiping. It's also different if the scrollview is animating while switching tabs. Preferably, the Scrollview should always respect the offset as passed by the ScrollController.

**Comment by Hixie** [comment]
My guess is that each list is trying to save its position, but because they don't have distinct keys, they all end up using the same slot in the page storage. Does it resolve itself if you put a `GlobalObjectKey(widget.pageNum)` on the CustomScrollView?

**Comment by vlidholt** [comment]
@Hixie I tried to add the global key, but it makes no difference.

**Comment by HansMuller** [comment]
Thanks for the small test case; trying to get to the bottom of the problem now.

**Comment by HansMuller** [comment]
There seem to be two problems here. Not only does the tab bar end up storing its scrollOffset in the same PageStorage location as each view's CustomScrollView, but all of the CustomScrollView's end up hitting the exact same location. So in addition to the problem you reported, all of the CustomScrollView's end up scrolled to the same offset. 

So to workaround the problem create the CustomScrollView's with their own key:
```
 new CustomScrollView(
        key: new ValueKey<int>(widget.pageNum),
        controller: scrollController,
        slivers ...
  )
```
To really fix the problem we'll ensure that TabBarView pages automatically end up with a unique key.

**Comment by HansMuller** [comment]
The root of this problem is the way we generate PageStorage identifiers, the per-route map keys used to store scroll offsets.

PageStorage is read and written as follows. The storage identifiers are based on the context value.
```
PageStorage.of(context).writeState(context, value);
var value = PageStorage.of(context).readState(context);
```

If the context's widget has a Global key, then that defines the storage identifier. Otherwise we use all of the ancestor's keys, up to - but not including - the next GlobalKey. Which is what happens in all cases in this example. All of the CustomScrollViews end up finding the RefreshIndicator's GlobalKey (I don't know why it has one), and since there are no intervening keys, they all end up with the same bucket. The TabBar's scrollable has also ends up with no identifier; it bumps into the Material's _InkFeatures global key. Not to put too fine a point on it, by the result is that all of the scroll offsets are saved and restored from the same map entry.

For ground truth see PageStorageBucket._computeStorageIdentifier(context).

Adding a ValueKey to to each CustomScrollView remedies the problem because the storage identifier algorithm finds it. Unfortunately this approach doesn't generalize, since adding value keys to farther up the tree, like above the RefreshIndicator, don't have any effect. In other words, the remedy only works if you happen to be creating the scroll view directly.

**Comment by Hixie** [comment]
I liked your offline suggestion of having PageStorage only use `PageStorageKey<T>`s (extends `ValueKey<T>`) to determine the storage identifier. Presumably the chain of such keys from the widget to the PageStorage itself, ignoring all other keys (and removing the GlobalKey stuff from the equation).

**Comment by HansMuller** [comment]
Here's a proposal for fixing the page storage identifier problem.

Widgets can save and restore state that outlives the widget itself using:

```
PageStorage.of(context).writeState(context, value);
var value = PageStorage.of(context).readState(context);
```

Scrollables (their ScrollPositions really) use this mechanism to save and restore their scroll offset.

Page storage is just a per ModalRoute Map. The read and write state methods create a "storage identifier" (a key for the PageStorage Map) based on the context parameter. This is where things get tricky.

The storage identifier needs to be stable across widget lifetimes. For example, for a PageView with three children, each of which contains a ListView, the storage identifiers for the ListViews must remain the same, as they're lazily created and recreated by the PageView. Currently the storage identifiers often are not stable and so scroll offsets are not restored correctly. 

To remedy the problem we could introduce a kind of ValueKey - PageStorageKey - which would be used to create storage identifiers. A storage identifier would be the concatentation of all of the ancestor PageStorageKeys, from the context's widget to the application's root. To be useful the PageStorageKey's value would have to stable and unique. For example:
```
new TabBarView(
  children: myTabs.map((MyTab tab) {
    new MyScrollableTabView(
      key: new PageStorageKey<MyTab>(tab),
      tab: tab
    ),
  }),
)
```

On the down side, this approach leaves the problem of identifying widgets to the app developer. On the up side it makes it possible for developers to give widgets stable identities.

**Comment by Hixie** [comment]
https://github.com/flutter/flutter/pull/10575 will revert this fix due to the performance impact.

**Comment by HansMuller** [comment]
https://github.com/flutter/flutter/pull/10590 restored the fix
