### ISSUE TITLE
Flutter's support for iOS flick/fling gesture on iOS is wrong

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#10401]
We have heard this brought up a few times. Most recently came up [in this post](https://sethlopez.me/article/exploring-flutter-for-cross-platform-mobile-development/
): _"On iOS, the biggest thing that stuck out to me was the scrolling. It didn’t quite feel right because of the physics..."_

**Comment by eseidelGoogle** [comment]
@HansMuller looked at this some months ago.  When doing so we used https://github.com/flutter/scroll_overlay as well as a combination of instrumenting & logging to collect scroll offsets from both Flutter UIScrollView and build graphs of the scroll curve.

**Comment by HansMuller** [comment]
We've tried pretty hard to precisely mimic iOS fling-scroll deceleration.  If we're still not getting some aspect of iOS scrolling right, it would help to find out what specifically doesn't feel native.

**Comment by mit-mit** [comment]
For me personally, the 'flick' gesture seems different. In native apps, you can flick scroll with a very minimal of 'dragging' up or down on the screen. In Flutter, you seem to need to move the finger further. I tried to illustrate in this video: https://goo.gl/photos/QaY2dwuJygeUsMHi9

**Comment by eseidelGoogle** [comment]
That's definitely actionable.  Lets rename this bug to cover that specific aspect and file more if we have more issues.

**Comment by xster** [comment]
It's the same task. Duping into #10977
