### ISSUE TITLE
Image is null after its saved on local memory..

### ISSUE THREAD

**Issue by halhwadi** [flutter/flutter#104066]
Hello

**Description:**
I'm using (image_picker: ^0.8.5+3) package to pick the images from gallery and camera and then upload them on backend server (django by using django rest framework)

**Issue:**
Image is getting null outside picker function, even though state has been set by using setSatet(() {}) method

**Failed Solutions:**
I tried to save the image locally before uploading the image on the backend, But image still shown null once its used or referenced outside picker function

**Note: backend API's works fine and i can upload images by using postman**

picker function:
```

  // Get image from gallery and store it locally
  Future<File?> _getFromGallery() async {
    PickedFile? image = await ImagePicker.platform.pickImage(source: ImageSource.gallery);
    if (image == null) {
      return null;
    }

    final File file = File(image.path);
    final Directory directory = await getApplicationDocumentsDirectory();
    final imagepath = directory.path;
    final String fileName = path.basename(image.path);

    File newImage = await file.copy('$imagepath/$fileName');
    setState(() {
      _imagelocal = newImage;
      print('image.path1');
      print(_imagelocal!.path);
    });
  }
```
Uploading image function:

```
_uploadimage() async {
      Map<String,String> header = {
        "Content-Type":"application/octet-stream)"
      };
      print("uploaded image invoked");
      var request = http.MultipartRequest('POST', Uri.parse('http://192.168.1.15:8000/api/uploadimage'));
      
      // request.files.add(await http.MultipartFile('image',http.ByteStream(image.openRead()).cast(),await image.length(),filename:image.name, contentType: MediaType('image', 'jpg')));
      request.files.add(await http.MultipartFile('LoadModelImage',http.ByteStream(_imagelocal!.openRead()).cast(),await _imagelocal!.length(),));
      request.headers.addAll(header);
      //for completeing the request
      var response =await request.send();

      //for getting and decoding the response into json format
      var responsed = await http.Response.fromStream(response);
      final responseData = json.decode(responsed.body);


      if (response.statusCode==201) {
        print("SUCCESS");
        print(responseData);
      }
      else {
        print("ERROR");
      }

    }

```

**Comment by danagbemava-nc** [comment]
Hi @halhwadi, please provide the version of `path_provider` you're using as well as the output of `flutter doctor -v`. 

Also, what platform(s) are you experiencing this issue on?

**Comment by halhwadi** [comment]
Hello
thanks for your quick response, please fnd the details below:

path_provider version is 2.0.10

pubspec.yaml:
```
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # localization
    sdk: flutter
  intl: ^0.17.0
  http: ^0.13.4
  shared_preferences: ^2.0.13
  loading_animations: ^2.2.0
  connectivity_plus: ^2.3.0
  permission_handler: ^9.2.0
  flutter_map: ^0.14.0
  maps_launcher: ^2.0.1
  image_picker: ^0.8.5+3
  path_provider: ^2.0.10
```

Flutter Doctor:**(Note: No need for Visual Studio as I'm developing mobile app)**
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.0.0, on Microsoft Windows [Version 10.0.19044.1706], locale en-AE)
    • Flutter version 3.0.0 at C:\Users\Husam.Alhwadi\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ee4e09cce0 (9 days ago), 2022-05-09 16:45:18 -0700
    • Engine revision d1b9a6938a
    • Dart version 2.17.0
    • DevTools version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc2)
    • Android SDK at C:\Users\Husam.Alhwadi\AppData\Local\Android\Sdk
    • Platform android-32, build-tools 33.0.0-rc2
    • ANDROID_HOME = C:\Users\Husam.Alhwadi\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] VS Code (version 1.67.1)
    • VS Code at C:\Users\Husam.Alhwadi\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (4 available)
    • SM A125F (mobile) • R58R1008B2E • android-arm64  • Android 10 (API 29)
    • Windows (desktop) • windows     • windows-x64    • Microsoft Windows [Version 10.0.19044.1706]
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 101.0.4951.67
    • Edge (web)        • edge        • web-javascript • Microsoft Edge 101.0.1210.39

[√] HTTP Host Availability
    • All required HTTP hosts are available

**Comment by halhwadi** [comment]
Issue has been solved, I was calling both function sequentially inside elevatedbutton, hence uploadimage function executed  completely before getting the image from picker function (though Picker function is quick) and that's why image was null, recommended solution is either to merge both functions in one function or call uploadimage function inside setState((){}) method in getimagegallery function
