### ISSUE TITLE
[fuchsia_ctl] Remove `@visibleForTesting` in `bin/main.dart`

### ISSUE THREAD

**Issue by nilsreichardt** [flutter/flutter#104001]
## Description
It looks like that the methods of the annotation `@visibleForTesting` are not used in tests. As mentioned in https://github.com/flutter/packages/pull/1770#issuecomment-1129151900 can give this a false safety.

Removing `@visibleForTesting` and running `dart analyze` does not print any issues.

Therefore, would be my proposal to remove the `@visibleForTesting` annotations in the [`bin/main.dart`](https://github.com/flutter/packages/blob/main/packages/fuchsia_ctl/bin/main.dart)

**Comment by ditman** [comment]
@ramanjitsingh-hub no need to be assigned, prepare a PR following the contribution rules of the repo, and fix it!

Than you for your help!

**Comment by ramanjitsingh-hub** [comment]
I have prepared the [PR ](https://github.com/flutter/packages/pull/1970)  Can you please review it
