### ISSUE TITLE
Encouraging contributions to our site and API docs

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#10416]
We'd like to do more to encourage our developers and community to contribute to our website and API docs. We believe that by making the call a bit more explicit, with very clear quality guidelines, we can increase the breath and community in our documentation.

We believe we can start in two ways:

* Each website page can have a more clear call to action to fix bugs and clarify content.
* Select API docs (those we feel are incomplete) can display a call to contribute.

In both cases, we believe that by linking to our guidelines and linking directly to the source file in GitHub, we can lower the bar to contributions.

Often time, it just takes a few small contributions to get involved in an open source community. Let's make contributing to Flutter's doc a bit easier and more welcoming. :)

**Comment by sethladd** [comment]
cc @InMatrix

**Comment by LarkAscending** [comment]
It's trivial to add Edit Source and File Issue buttons just below the header of every page. In _layouts/page.html, add something like:

```
  <header class="post-header">
    <h1 class="post-title">{{ page.title }} </h1>
      <div class="btn-group" role="group">
         <a href="https://github.com/flutter/website/blob/master/{{page.path}}" class="btn btn-default">
            <i class="glyphicon glyphicon-pencil"></i> Edit Source
         </a>
         <a href="https://github.com/flutter/flutter/issues/new/" class="btn btn-default">
            <i class="glyphicon glyphicon-paperclip"></i> File Issue
        </a>
     </div>

  </header>
```
This uses the lavish-bootstrap classes for buttons and icons, which IMO is not a problem but others may differ. Feel free to suggest alternatives...

**Comment by InMatrix** [comment]
Adding Edit Source and File Issue probably is a useful first step. It would be interesting to see if people do anything with them. What we'd really like to do is to ask the community to help something more specific, so we get what we're looking for and the community member feels accomplished by adding small but clearly valued content to our docs.

**Comment by InMatrix** [comment]
Maybe the next step is to get user feedback on those recently improved docs and work towards a API doc pattern for Flutter. cc @Hixie

**Comment by sethladd** [comment]
We can also try this "edit, file issue" feature on the website.

Can we add data to the "new issue" link, such that it says which file was the source of the issue?

**Comment by LarkAscending** [comment]
...and it might be good to break the goal into steps:
1. Make it clear and convenient to access source for the documentation in GitHub.
1. Publish contribution guidelines that are just restrictive enough. 
1. Maintain a wish list, via issues w/a specific label, the README, or other means.

**Comment by LarkAscending** [comment]
@sethladd it's possible to pass the path or url of the file where the button is clicked. We construct the URL so it could be a parameter there, or it could be the value of an `id` attribute in the HTML element. That kind of thing?

A little tooling would need to happen on the GitHub issue side to use this info - to pre-populate an issue, for example.

**Comment by sethladd** [comment]
Even knowing which page the user is filing an issue for should be a big help.

Ah, looks like we can! Here's a format for a URL that pre-populates the title and body of an issue: `https://github.com/isaacs/github/issues/new?title=foo&body=bar`

So perhaps we can do something like this on the website:

`https://github.com/flutter/flutter/issues/new?title=Issue from [insert page title]&body=From URL: [insert url]`

**Comment by LarkAscending** [comment]
Wow, the perfect example! This made it easy to create #https://github.com/flutter/website/pull/592

Feedback welcome...

**Comment by LarkAscending** [comment]
@jcollins-g FYI, this began with a request for dartdocs, to invite people to contribute to docs.flutter.io.
1. Is it possible to mark or highlight pages we want help on?
1. Is is possible to add Edit Source and File Issue buttons to dartdocs pages?

**Comment by jcollins-g** [comment]
For number one, it is possible to mark or highlight pages, assuming we can define which ones.  We could provide something a template could check on as part of dartdoc (might be useful for symbols without any documentation at all), or someone could write some javascript to check an external source for whether or not the page needs to be marked.

Adding the File Issue button doesn't seem that hard in theory and I'm willing to help with that.  If possible please file a dart-lang/dartdoc issue describing where you want the button to appear and what you want it to link to.  We'll have to design something that can work for Flutter without negatively impacting Dart's other customers but that's really the only serious complication.

I'm curious about Edit Source in this instance -- for dartdoc, this literally means "edit the source code".   Dartdoc currently knows nothing about where source code it is generating docs for lives on github or elsewhere making it somewhat difficult to construct links to that.  In addition, individual elements on a page can come from wildly different locations.  But I welcome a bug and we can brainstorm the best way to make this happen if we think it is a big win.

**Comment by InMatrix** [comment]
There is already a dartdoc issue filed by @eseidelGoogle about linking from doc to source: https://github.com/dart-lang/dartdoc/issues/1454 Thanks for taking a look!

**Comment by filiph** [comment]
@InMatrix and I just talked about this. I think there are some relatively easy things we can do:

1. Find the worst offenders (high-traffic Widget dartdoc pages with no sample/image).
2. Find out if anyone from the community ever contributed to the docs. If so, make a list.
3. Publish the following (in one Medium / flutter-dev@ post):
  * List of the pages (worst offenders)
  * Call to action - "Please contribute samples and screenshots here"
  * Reassurance that PRs don't need to nail it at first go. Contributing to a project with this high quality of code can be scary. I think we can hand-hold a bit at the beginning. ("It's okay if your first PR is a bit of a mess. We'll work with you.")
  * Huge thanks to all existing contributors, and links to their github profiles.

**Comment by sethladd** [comment]
Great to see discussions!

**Comment by filiph** [comment]
Would you like me to go forward with the 1-3 steps above?

**Comment by sethladd** [comment]
sgtm , maybe also email and tweet the medium doc?

Do we have a wiki page for "so you want to contribute to the API docs?"

**Comment by Hixie** [comment]
The documents are:
* https://github.com/flutter/flutter/blob/master/CONTRIBUTING.md
* https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
* https://flutter.io/design-principles/

...with particular emphasis on the documentation sections of the style guide and design principles docs.

**Comment by InMatrix** [comment]
Thanks, @filiph! Let me know if there is anything I can help. I'd like to make sure we have a way to measure the outcome of any method we try to engage contributors. There can be useful lessons to be learned for OSS projects in general.
