### ISSUE TITLE
card example image is blurry

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#10412]
https://docs.flutter.io/flutter/material/Card-class.html

<img width="316" alt="screen shot 2017-05-31 at 1 14 42 pm" src="https://cloud.githubusercontent.com/assets/11857803/26651961/31b6f090-4603-11e7-8e61-c53d8ca03999.png">

@Hixie

**Comment by Hixie** [comment]
We can regenerate it to be bigger. It's just that it's being scaled down when generated.

**Comment by sethladd** [comment]
Good catch. +1 for a bigger image. Could easily go up to 700px wide if we want.

**Comment by Hixie** [comment]
When I asked you said 200px! :-P

**Comment by sethladd** [comment]
Hm, if I did, I apologize about that. Maybe I was commenting on the size of the images in our Widget Catalog ? For the API docs, we're much more flexible.

**Comment by Hixie** [comment]
I've put up a PR that doubles the image size, see 
https://github.com/flutter/assets-for-api-docs/issues/9.
