### ISSUE TITLE
[in_app_purchase: 3.0.4] Subscription details are not shown

### ISSUE THREAD

**Issue by genabotpub** [flutter/flutter#104123]
Hello,

After recent change [introduced ](https://support.google.com/googleplay/android-developer/answer/140504?hl=en#zippy=%2Cedit-an-existing-subscription)by Google how Subscriptions are defined, I cannot retrieve their details using  `InAppPurchasePlatform.instance.queryProductDetails(identifiers)`.

The code worked prior to the recent Google change.

Any insight would be appreciated.
gen

**Comment by darshankawar** [comment]
@genabotpub 
From the google link you shared, can you point to exact section from it which shows the change introduced ?
Also, currently if you run `InAppPurchasePlatform.instance.queryProductDetails(identifiers)` what does it return with ?

Can you provide the before and after results based on the change you linked above ?

**Comment by genabotpub** [comment]
@darshankawar 
Thank you for the prompt response. I figured out the problem, there was an issue with my configuration. Please close this question.
