### ISSUE TITLE
[Flutter_Module] XCode 13.3 Pod Install Removes Path To Flutter Module

### ISSUE THREAD

**Issue by grisvladko** [flutter/flutter#104178]
Hello

I Have opened this SO : https://stackoverflow.com/questions/72302377/xcode-13-3-pod-install-removes-path-to-flutter-module 

As described there, we have the following problem:
pod install removes all of the flutter module paths from our iOS App. 
everything was working fine until at some point it wasn't and pod install started removing those lines, then we get a crash:

dyld: Library not loaded: @rpath/App.framework/App Referenced from: /private/var/containers/Bundle/Application/SomeRandomGeneratedNumber/MyApp.app/MyApp Reason: image not found

when running the app on a real device, while on simulator it works fine.

XCode13.4 fails too.
flutter version : 2.10.3
cocoapods: 1.11.2

will gladly provide more information if needed, Thank you!

**Comment by darshankawar** [comment]
@grisvladko 
This looks similar to https://github.com/flutter/flutter/issues/49504. Can you go through it and see if it helps ?

Also, what's the iOS version you are running on ? I also suggest you to upgrade flutter version.

Moreover, please provide complete `flutter run -v` log. It'll be huge so you can put that in a text file and share it here.

**Comment by grisvladko** [comment]
Thank you for the reply,
at first i thought that thread was helpfull but my issue is a different one although the crashes being decribed are similar.
our project is working perfectly when i am not doing pod install, but when i do this somehow removes the paths to my flutter module inside the iOS project. see this image as an example of how the code in the source control looks like after pod install:

![WhatsApp Image 2022-05-19 at 12 03 23 PM](https://user-images.githubusercontent.com/59421266/169663551-e831ca29-d7a0-4a72-8bfc-96ec34fe4c10.jpeg)

currently running iOS 15.4.1 device, but this is regardless of the iOS version i am using.
also we are not using flutter run very often because it is the architecture where flutter is embedded as a module in iOS and aOS projects, but if needed i can provide the text file.

the question here is : is it a known issues that pod install removes flutter module from iOS project when flutter is embedded as a module ? why does this happen and how can i fix it ?

NOTE: when i revert the changes being made by the pod install command e.g the removed paths are back into place the project runs and everything is fine.

**Comment by darshankawar** [comment]
Thanks for the update. Based on your findings that using cocoapods, you are seeing this behavior, I suggest you to ask this question in dedicated repo and see if you get any leads from there. There seems to be similar issues raised in that repo as I see: https://github.com/CocoaPods/CocoaPods/issues?q=dyld%3A+Library+not+loaded

**Comment by grisvladko** [comment]
I have opened an issue over there, it seems that flutter team is not connected to this one, if some one runs into that problem see the issue that i've opened here : https://github.com/CocoaPods/CocoaPods/issues/11378
