### ISSUE TITLE
[macOS][Desktop]: UI is broken on latest master

### ISSUE THREAD

**Issue by darshankawar** [flutter/flutter#104154]
UI seems to be broken and not rendering on macOS desktop using latest master (`Channel master, 3.1.0-0.0.pre.799`, at the time of writing this).

Steps to replicate:

1. Create a new Flutter app (`flutter create macos_issue`)
2. cd `macos_issue`
3. `flutter run -d macos` and observe that UI is not rendered and shows a blank screen. If we try to resize the app window, then it shows flashes of the UI as we move the window size:

https://user-images.githubusercontent.com/67046386/169229045-92d96ffc-1ce2-45ee-bda8-0e5d26e5f375.mov

The same works properly on latest stable (3.0) and beta (2.13.0-0.4.pre) as shown below:

https://user-images.githubusercontent.com/67046386/169229109-1ce83263-9ee2-4d1f-a49e-4d407467396f.mov

Moreover, this seems to be only happening on macOS desktop, whereas, macOS + web, macOS + android and Linux desktop seems to be working as expected.

<details>
<summary> master flutter doctor -v </summary>

```

[✓] Flutter (Channel master, 3.1.0-0.0.pre.799, on macOS 12.2.1 21D62
    darwin-x64, locale en-GB)
    • Flutter version 3.1.0-0.0.pre.799 at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 348a2b4f2f (29 minutes ago), 2022-05-19 00:33:08 -0400
    • Engine revision 1965c92ea4
    • Dart version 2.18.0 (build 2.18.0-130.0.dev)
    • DevTools version 2.13.1
    
[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.



```

</details>

**Comment by dkwingsmt** [comment]
I bisected it to be 348a2b4f2ff57770a40da3b3b1b7df2e8183128a.

**Comment by jmagman** [comment]
@cbracken mentioned writing more macOS tests...

**Comment by cbracken** [comment]
Indeed. There are many many many tests we need. :)

I just bisected this again without knowing it had already been bisected.
