### ISSUE TITLE
Linux machines failing salt states

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#104138]
----------
          ID: psutil3
    Function: cmd.run
        Name: /opt/swarming-support/bin/python3 /opt/swarming-support/bin/pip3 install psutil
      Result: False
     Comment: The following requisites were not found:
                                 require:
                                     cipd: python3
     Started: 20:48:48.685378
    Duration: 0.01 ms
     Changes:   
----------

**Comment by yusuf-goog** [comment]
flutter@flutter-devicelab-linux-12:~$ sudo salt-call state.apply
local:
    Data failed to compile:
----------
    Pillar failed to render with the following messages:
----------
    Specified SLS 'users.foundation' in environment 'base' is not available on the salt master
----------
    Specified SLS 'users.labs' in environment 'base' is not available on the salt master

**Comment by yusuf-goog** [comment]
The infra team is currently working on the pillar issues.

**Comment by yusuf-goog** [comment]
Fix in http://go/tircl/536891

**Comment by yusuf-goog** [comment]
This has been deployed on dev salt master and is working on minions connected to it (e.g. linux-18). It shoudl be deployed to prod salt master shortly.
