### ISSUE TITLE
Update "child" docs

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#10414]
We should use a macro for all the "child" properties to have the same docs, something like:

> The widget below this widget in the tree.
>
> This widget can only have one child. To lay out multiple children, use a widget such as [Row], [Column], or [Stack], which have a `children` property.

**Comment by shamrin** [comment]
I think this issue should be closed, because PR #13718 was merged.

**Comment by Hixie** [comment]
Good catch, thanks!
