### ISSUE TITLE
Camera image rotated 90 degrees when taken in landscape mode.

### ISSUE THREAD

**Issue by mikeb1986** [flutter/flutter#104134]
I have recently upgraded to flutter 2.10.5 and the camera plugin to 0.9.5.
After this upgrade, taking a picture in landscape mode displays it 90 degrees rotated.
Any ideas if this is a common issue now?
I can reproduce on my Galaxy S10 and also on the android emulator in Android Studio.
The FlutterExifRotation plugin doesn't correct the orientation (but it does on iOS).

**Comment by darshankawar** [comment]
@mikeb1986 
Can you provide a minimal code sample and current behavior ?
Also please check if the same behavior occurs using camera plugin [example](https://github.com/flutter/plugins/tree/main/packages/camera/camera/example) too.

**Comment by mikeb1986** [comment]
Hi @darshankawar 
I noticed actually this issue started with the camera plugin version 0.9.0 and onwards.
Previously we used 0.8.1+3.

What I noticed now is if the app is fixed in portrait mode via setPreferredOrientations(...)
then rotating the phone 90 degrees to take a picture will just save it sideways as portrait.

Is there a way to not have a fixed orientation on the camera even though the app itself is always portrait mode?

I was able to reproduce the issue using the camera example from the official flutter plugin page - though I had to add logic to call setPreferredOrientations(...) to keep the app in portraitUp mode.

https://github.com/flutter/plugins/blob/main/packages/camera/camera/example/lib/main.dart

**Comment by darshankawar** [comment]
Thanks for the update. I think you are hitting https://github.com/flutter/flutter/issues/25232, specifically https://github.com/flutter/flutter/issues/25232#issuecomment-600208893, so please follow-up in it for further updates.

Closing this as a duplicate.

**Comment by mikeb1986** [comment]
Thanks @darshankawar I have added a comment on the other ticket, even though it is closed.

**Comment by darshankawar** [comment]
The other issue is still open.
