### ISSUE TITLE
Remove unnecessary code when ShortcutManager.of and Shortcuts manager are finally removed.

### ISSUE THREAD

**Issue by gspencergoog** [flutter/flutter#104129]
In change https://github.com/flutter/flutter/pull/104115, the `ShortcutManager.of`, `ShortcutManager.maybeOf` and `Shortcuts` constructor parameter for `manager` were deprecated.

Once they are actually removed, then some things can be simplified:

1) The `_ShortcutsMarker` class can go away, and we don't need to add one with every `Shortcuts` widget.
2) The `Shortcuts._forceShortcutsOnManager` boolean can go away, and the value of `widget.manager` can be used to decide this state instead (if it is null, force the shortcuts, if it isn't, let the manager decide).
3) The deprecation comment in the `Shortcuts` constructor can be removed/reworded.
4) The `Shortcuts.shortcuts` accessor can be simplified.

**Comment by goderbauer** [comment]
This was completed in https://github.com/flutter/flutter/pull/104215
