### ISSUE TITLE
flutter-devicelab-mac-9 not available over ssh

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#104142]
flutter-devicelab-mac-9 bot is dead and not accessible over ssh

**Comment by jmagman** [comment]
I had filed https://github.com/flutter/flutter/issues/104671 yesterday and it was closed as a dupe, but I'm not sure where the dead bots are being tracked.

**Comment by godofredoc** [comment]
We have been opening one bug per bot, most of them are down for different issues that require to track them separately.

**Comment by godofredoc** [comment]
You can find the dead bots from the swarming UI: https://chromium-swarm.appspot.com/botlist?c=id&c=task&c=os&c=status&d=asc&f=pool%3Aluci.flutter.prod&k=pool&s=id

**Comment by yusuf-goog** [comment]
mac-9 was hung, possibly because of upgrade. rebooted, and system is back up.
