### ISSUE TITLE
Website HTML/CSS style guide

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#10417]
For contributors from our community, we'd like to point them to an HTML/CSS authoring style guide.

This could be a Wiki on the flutter/website, if that's easy enough.

**Comment by eseidelGoogle** [comment]
Perhaps https://google.github.io/styleguide/htmlcssguide.html?

**Comment by zoechi** [comment]
Issue moved to [flutter/website #1842](https://github.com/flutter/website/issues/1842) via [**ZenHub**](https://www.zenhub.com/)
