### ISSUE TITLE
Flutter 3 Regression: ReorderableDragStartListener is ignored on mobile

### ISSUE THREAD

**Issue by 12people** [flutter/flutter#104130]
## Steps to Reproduce

1. Execute `flutter run` on the code sample on an Android device 
2. Drag an item's drag handle up or down.

**Expected results:** 
The item should have moved up or down, just as it does in the web version or desktop version.

The solution in the code is also described in the [documentation](https://api.flutter.dev/flutter/material/ReorderableListView/buildDefaultDragHandles.html):

> To change the appearance or the layout of the drag handles, make this parameter false and wrap each list item, or a widget within each list item, with [ReorderableDragStartListener](https://api.flutter.dev/flutter/widgets/ReorderableDragStartListener-class.html) or [ReorderableDelayedDragStartListener](https://api.flutter.dev/flutter/widgets/ReorderableDelayedDragStartListener-class.html), or a custom subclass of [ReorderableDragStartListener](https://api.flutter.dev/flutter/widgets/ReorderableDragStartListener-class.html).

**Actual results:** 
No items change.

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  static const String _title = 'Flutter Code Sample';

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: _title,
      home: Scaffold(
        appBar: AppBar(title: const Text(_title)),
        body: const MyStatefulWidget(),
      ),
    );
  }
}

class MyStatefulWidget extends StatefulWidget {
  const MyStatefulWidget({Key? key}) : super(key: key);

  @override
  State<MyStatefulWidget> createState() => _MyStatefulWidgetState();
}

class _MyStatefulWidgetState extends State<MyStatefulWidget> {
  final List<int> _items = List<int>.generate(50, (int index) => index);

  @override
  Widget build(BuildContext context) {
    return ReorderableListView(
      buildDefaultDragHandles: false,
      padding: const EdgeInsets.symmetric(horizontal: 40),
      children: <Widget>[
        for (int index = 0; index < _items.length; index += 1)
          ListTile(
            key: Key('$index'),
            title: Text('Item ${_items[index]}'),
            trailing: ReorderableDragStartListener(
                            index: index, child: const Icon(Icons.drag_handle))
          ),
      ],
      onReorder: (int oldIndex, int newIndex) {
        setState(() {
          if (oldIndex < newIndex) {
            newIndex -= 1;
          }
          final int item = _items.removeAt(oldIndex);
          _items.insert(newIndex, item);
        });
      },
    );
  }
}
```

</details>

**Comment by 12people** [comment]
It's worth noting that this used to work in a previous version of Flutter. Upgrading to 3.0 seems to have broken this functionality.

**Comment by dapperappdeveloper** [comment]
Yep can confirm functionality is broken on mobile only. However it seems to work if the listview is **not** scrollable.
ReorderableDelayedDragStartListener does work however (long press to reorder)

**Comment by darshankawar** [comment]
This probably is similar to https://github.com/flutter/flutter/issues/103404 which has been fixed as part of this PR https://github.com/flutter/flutter/pull/103406 and cherry-pick request has been made to fix in stable https://github.com/flutter/flutter/issues/103663

@12people Can you verify the same on latest master and see if the behavior is fixed ?

`flutter channel master`
`flutter upgrade`

**Comment by dapperappdeveloper** [comment]
Thank you! You're right, it has been already fixed

**Comment by darshankawar** [comment]
Thanks for confirming. Closing this as already fixed and available on latest master.
