### ISSUE TITLE
[image_picker: ^0.8.5+3][Android][Camera] -> request to open with default front camera but it open camera with default rear camera option.

### ISSUE THREAD

**Issue by brand2021** [flutter/flutter#104162]
final pickedFile = await _picker.pickImage(
          source: source,
          preferredCameraDevice: CameraDevice.front,
          maxWidth: maxWidth,
          maxHeight: maxHeight,
          imageQuality: imageQuality,
        );
        _imageFile = pickedFile;

**Comment by darshankawar** [comment]
@brand2021 
Check [this](https://github.com/flutter/flutter/issues/55644#issuecomment-691079453) issue comment for current limitation and reason why it comes default rear camera.
Flutter team added documentation for same as part of this PR that you can take a look: https://github.com/flutter/plugins/pull/3037

Closing, as this is WAI and dependent on how Android makes use of intents.
