### ISSUE TITLE
Cannot run Project.afterEvaluate(Closure) when the project is already evaluated.

### ISSUE THREAD

**Issue by RodolfoBonis** [flutter/flutter#104187]
My flutter application it's giving this error when i compile for android.

I already updated flutter to version 3.0 and update the packages, sdk, ndk.

![image](https://user-images.githubusercontent.com/28612995/169314982-3abb2c85-3466-47dc-a374-b406a8f053bc.png)

Flutter doctor:

![image](https://user-images.githubusercontent.com/28612995/169529274-0eb8f183-ad5f-4bb2-b61e-33c73d130f2c.png)

**Comment by huycozy** [comment]
Hi @RodolfoBonis, please share a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) along with the output of `flutter doctor -v` to investigate this issue further.
