### ISSUE TITLE
Tree is closed on repeated infra failures on Mac_arm64_ios build_ios_framework_module_test

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#104195]
It looks like various steps are timing out e.g. https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_arm64_ios%20build_ios_framework_module_test/452/overview

**Comment by keyonghan** [comment]
This is the same as https://github.com/flutter/flutter/issues/103910.
Did the same on mac42 as mac41 and mac43 by disabling the extra service.

**Comment by godofredoc** [comment]
There was a race condition running multiple bots per machine. This has been fixed now.
