### ISSUE TITLE
InkWell widget when placed in a tree that contains a BackdropFilter gets blurred

### ISSUE THREAD

**Issue by Kirchesch** [flutter/flutter#104167]
## Steps to Reproduce

1. Create a new Flutter app
2. In the MaterialApp home paste:

```dart
class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        brightness: Brightness.dark,
      ),
      home: Scaffold(
        body: Center(
          child: BackdropFilter(
            filter: ImageFilter.blur(sigmaX: 12, sigmaY: 12),
            child: InkWell(
              onTap: () {},
              child: const Text(
                  "Ink Well Text, as you can see, the text doesn't get blurry, just the splash effect"),
            ),
          ),
        ),
      ),
    );
  }
}
```
3. Run the app and see that the inkwell is blurry

**Expected results:** Anything bellow the BackdropFilter should not be filtered, and nothing is, except for the InkWell ofcourse

**Actual results:** InkWell splash effect gets blurry

**Comment by Kirchesch** [comment]
Another InkWell problem, the fact that it doesn't respect parent's border corners
Sometimes we use InkWells inside dynamic containers, like a dynamic drawer that the content have no access on the drawer border radius, we have to hard code the same border radius on both, its another hacky thing

**Comment by maheshmnj** [comment]
Hi @Kirchesch, I believe this is working as intended the ink is not blurred basically The ink is applied on a widget with a transparent background hence the output.


> Another InkWell problem,

I would suggest filing that as a separate issue.

**Comment by Kirchesch** [comment]
Hey @maheshmnj alright, so the ink splash is not its own thing, it paints the background behind it? thanks for letting me know
