### ISSUE TITLE
With Flutter 3.0, code suggestion for initState/dispose/setState no longer works. It worked for Flutter 2.10. This issue was found in both Windows(10) and Mac(12.3.1).  Steps to Reproduce Start typing in ini. Hit control-space for auto suggestions Nothing comes up yet.

### ISSUE THREAD

**Issue by ir185005** [flutter/flutter#104247]
With Flutter 3.0, code suggestion for initState/dispose/setState no longer works. It worked for Flutter 2.10.
This issue was found in both Windows(10) and Mac(12.3.1).

Steps to Reproduce
Start typing in ini.
Hit control-space for auto suggestions
Nothing comes up yet.

**Comment by maheshmnj** [comment]
Hi @ir185005, Thanks for filing the issue. 
This is an issue with dart analyzer which is being tracked here see https://github.com/dart-lang/sdk/issues/49054

Closing as this is not an issue with flutter.
