### ISSUE TITLE
[image_picker] Add support for Android 13's photo picker

### ISSUE THREAD

**Issue by alex-sandri** [flutter/flutter#104250]
Currently the system file picker is opened.

See https://developer.android.com/about/versions/13/features/photopicker.

**Comment by darshankawar** [comment]
Android 13 is still in beta and is yet to be available officially and Flutter is no exception as it doesn't yet support new OS.
Keeping it open and labeling as proposal.

**Comment by blasten** [comment]
cc @GaryQian

**Comment by armandojimenez** [comment]
Any updates with this?

**Comment by debojyoti452** [comment]
I want to add a fix for this task. Is anyone already doing this task? 
cc: @GaryQian @blasten

**Comment by rmasarovic** [comment]
any news? maybe change priority?

**Comment by FXschwartz** [comment]
@blasten @darshankawar I've submitted a PR implementing this. Can you assign this to me when you get time, please?

**Comment by darshankawar** [comment]
@FXschwartz Done :)
