### ISSUE TITLE
Colors do not auto-complete after upgrade to 3.0.0

### ISSUE THREAD

**Issue by mark8044** [flutter/flutter#104224]
When typing in Android Studio Chipmunk, previous to upgrade to 3.0.0, when typing color names, for example 'whi' the color `Colors.white` would auto-complete.  Now none of the colors will auto-complete, and one must type `Colors` and then the various color choices will come in a popup to chose from.  

It was more efficient when the specific colors could be typed `white`, `grey`, `red` etc

**Comment by maheshmnj** [comment]
Hi @mark8044, Thanks for filing the issue. Could you please check if this is the same issue you are referring to https://github.com/flutter/flutter/issues/104149?

**Comment by maheshmnj** [comment]
This is being tracked here https://github.com/flutter/flutter-intellij/issues/6177.
Closing as tihs is not an issue with flutter.
