### ISSUE TITLE
Text is not painted to the Canvas at the correct position on Flutter 3.0.0

### ISSUE THREAD

**Issue by bdlukaa** [flutter/flutter#104275]
## Steps to Reproduce

Execute `flutter run` on the [package example app](https://github.com/bdlukaa/rounded_background_text/tree/master/example) with two different flutter versions:
1. Flutter 2.10.0
2. Flutter 3.0.0

**Expected results:** 

![example 20_05_2022 14_53_13](https://user-images.githubusercontent.com/45696119/169585262-0d858855-b842-4a57-9d85-7323d587dd3e.png)

**Actual results:** 

![example 20_05_2022 14_55_43](https://user-images.githubusercontent.com/45696119/169585381-a6acfa40-0b6c-4adb-abaa-4722484f4102.png)

For some reason, the text is not painted ([painting operation occurs here](https://github.com/bdlukaa/rounded_background_text/blob/master/lib/src/rounded_background_text.dart#L344-L351)) at the same position on these two different versions. To paint the background, I use the `LineMetric`s generated by `TextPainter.generateLineMetrics` positions. They are the same for both versions (you can run the tests and see), so something may be wrong on paiting the text into the `Canvas`.

<details>
<summary>Code sample</summary>

https://github.com/bdlukaa/rounded_background_text/blob/master/example/lib/main.dart#L142-L159

</details>

<details>
  <summary>Logs</summary>

```
```

```
Analyzing example...                                                    
No issues found! (ran in 41.3s)
```

```
[√] Flutter (Channel stable, 3.0.0, on Microsoft Windows [versÆo 10.0.22000.675], locale pt-BR)
    • Flutter version 3.0.0 at C:\Users\bruno\Documents\flutter\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ee4e09cce0 (11 days ago), 2022-05-09 16:45:18 -0700
    • Engine revision d1b9a6938a
    • Dart version 2.17.0
    • DevTools version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\bruno\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.7)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31911.196
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.67.2)
    • VS Code at C:\Users\bruno\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.40.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [versÆo 10.0.22000.675]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 101.0.4951.67
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 101.0.1210.47

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by jason-simmons** [comment]
This is caused by https://github.com/flutter/flutter/issues/104153

**Comment by bdlukaa** [comment]
Marking as duplicate then.
