### ISSUE TITLE
Pencil and square icon isn't right

### ISSUE THREAD

**Issue by rafaelovandov** [flutter/flutter#104248]

**Comment by darshankawar** [comment]
@rafaelovandov 
Are you referring to CupertinoIcons square and pencil ? If so, they seem to be working properly:

<img width="67" alt="Screenshot 2022-05-20 at 6 02 20 PM" src="https://user-images.githubusercontent.com/67046386/169528845-b980e871-fd7a-4e1c-83d7-84b7cc7eeca2.png">


```
Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              Icon(
                  CupertinoIcons.square
              ),
              Icon(
                CupertinoIcons.pencil
              )
            ],
          )
```

**Comment by rafaelovandov** [comment]
You are using two icons, i was saying about the icon that has pencil inside the square

**Comment by darshankawar** [comment]
I see.  It shows up as below:

<img width="66" alt="Screenshot 2022-05-20 at 6 23 55 PM" src="https://user-images.githubusercontent.com/67046386/169532171-b8253f82-bd6f-48c7-82cc-d3c55e7b2daa.png">

And it seems to have been tracked already as part of this umbrella issue: https://github.com/flutter/flutter/issues/82634 so I suggest you to follow-up in it for further updates.
Closing this as duplicate.
