### ISSUE TITLE
ShaderMask is broken by the shifting done by Align

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#10424]
This works:
```
import 'package:flutter/material.dart';

void main() {
  runApp(
    new Align(
      alignment: FractionalOffset.topLeft,
      child: new SizedBox(
        width: 400.0,
        height: 400.0,
        child: new FittedBox(
          child: new ShaderMask(
            shaderCallback: (Rect bounds) {
              return new RadialGradient(
                center: FractionalOffset.topLeft,
                radius: 1.0,
                colors: <Color>[Colors.yellow, Colors.deepOrange.shade900],
                tileMode: TileMode.repeated,
              ).createShader(bounds);
            },
            blendMode: BlendMode.modulate,
            child: const Text('I’m burning the memories'),
          ),
        ),
      ),
    ),
  );
}
```

If you change `alignment: FractionalOffset.topLeft` to `alignment: FractionalOffset.center` then it stops working.

cc @jason-simmons @abarth

**Comment by Hixie** [comment]
"Working" means the text looks like it's on fire, "stops working" means the text is white.

**Comment by jason-simmons** [comment]
This is related to the calculation of the shader's bounds rectangle.

The example works if I change RenderShaderMask.paint() to apply the offset to the bounds rect:
    `final Rect rect = offset & size;`

However, I'm not sure if this is the right fix.  PaintingContext.pushShaderMask docs say that the shader "operates in the coordinate system of the caller".  Does that mean that the coordinates should have the painting offset applied?

@abarth any advice?

**Comment by Hixie** [comment]
That seems like a legit fix. The caller in this case is the render object which is operating in the coordinate space where it's top left is at `offset`, rather that at the origin.

**Comment by efortuna** [comment]
Reopening. This seems to still not be working based on the example provided in ShaderMask:
https://docs.flutter.io/flutter/widgets/ShaderMask-class.html
I'm currently running 

Flutter 0.7.6-pre.27 • channel master • https://github.com/flutter/flutter.git
Framework • revision 2369087668 (5 hours ago) • 2018-09-03 11:39:32 -0400
Engine • revision de4c7a53f2
Tools • Dart 2.1.0-dev.3.0.flutter-760a9690c2

**Comment by Hixie** [comment]
There was a related fix we did just a few days ago (cc @GaryQian @jason-simmons), can you confirm if it is still broken?

**Comment by Hixie** [comment]
(might be best to file a new bug with a new reduced testcase if it still happens)

**Comment by GaryQian** [comment]
I just ran this with the fix in https://github.com/flutter/engine/commit/ba7752917f3081fd6b4e10d8ef6cecbdfe59a985
and it seems to be working properly.
