### ISSUE TITLE
Our first-party Firebase plugins should link to each other

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#10427]
Currently Firebase plugin discovery for Flutter is quite poor (this is mostly an artifact of poor ranking on Pub; hopefully that will be resolved later):
https://pub.dartlang.org/search?q=firebase

For now, let's cross-link them so that if a developer finds one of them, finding the others is easy.

**Comment by mit-mit** [comment]
Concrete suggestion: In each plugin's readme.md, add a second line below the current `A Flutter plugin to use Firebase xxx` with the following contents: `For Flutter plugins for other Firebase products, see [FlutterFire](https://github.com/flutter/plugins/blob/master/FlutterFire.md).`

Or maybe @sethladd can word-smith a better sentence?

**Comment by branflake2267** [comment]
I would suggest moving the FlutterFire.md contents to the root README.md as a subsection with `##FlutterFire` as the header. FlutterFire.md feels like an orphan deeply connected in this location. I would then suggest separating the two pages on flutter.io `Plugins & platform-specific code` and create something like `[Native] Platform Plugins` and `Designing [Native] Platform Plugins`. Something to tell the story, here's what we have and if don't see what you need, here's how to do it. Or if you like less main index chatter, I would simply put, `Platform [Native] Plugins` and deep link `Designing Native Platform Plugins`. Using my descriptive words don't matter, just that the story could be more concise regarding those two items on the site.

**Comment by mit-mit** [comment]
Thanks for the feedback @branflake2267, I believe that has been addressed with the overview tables you helped us get in the main README.md.

**Comment by kroikie** [comment]
@mit-mit

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1003. Any further collaboration will be done there.
