### ISSUE TITLE
Article request: Migrating to Flutter

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#10422]
We'd love a canonical source for our opinions, perspectives, and suggestions for migrating an existing mobile app investment to Flutter.

Not every prospective Flutter developer understands that Flutter doesn't have to drive every screen in your app. Once we have an article that explains the techniques for migration, the tooling integrations, and best practices, we can share the article and link to it from our homepage.

This will be a key article when talking to potential customers, many of whom have existing mobile investments.

**Comment by roughike** [comment]
I have played around with this a little bit. Would be cool to take a shot at an article.

Just to be sure, to migrate an Android project, we:

1. have an existing Android project, let's say in a folder called `MyAndroidProject`
2. create a new Flutter project
3. delete the `<flutter project root>/android` folder
4. drop the `MyAndroidProject` to the `<flutter project root>` folder
5. rename the `MyAndroidProject` folder to `android`
6. run `flutter create .` in the flutter project root
7. edit the `build.gradle` files a little bit
8. add `android:name="io.flutter.app.FlutterApplication"` to the `<application>` tag in the AndroidManifest file
9. call the `FlutterMain.ensureInitializationComplete(getApplicationContext(), args);` method with the args that get passed to the `Intent` that the Activity receives.
10. now we can run the existing native Android Studio with Flutter tools.

Is that correct or did I miss something?

Not sure about iOS steps, but pretty sure I can figure them out as well.

**Comment by sethladd** [comment]
Yup! And @lukef did some work here. Would love to see an article!

**Comment by lukef** [comment]
I have insights!

**Comment by roughike** [comment]
@lukef Sharing is caring! :)

**Comment by lukef** [comment]
I have a meeting with the Flutter team on Tuesday to discuss so let me regroup after that

**Comment by zoechi** [comment]
Is this covered by 
https://flutter.io/docs/get-started/flutter-for/android-devs
...
https://flutter.io/docs/get-started/flutter-for/xamarin-forms-devs
?

**Comment by lukef** [comment]
Yeah. It's not perfect but I'd guess anyone not on dart 2 is about 0% now so it's irrelevant.

**Comment by zoechi** [comment]
@lukef not sure why you mention Dart 2.
I assume this is for onboarding developers from other platforms like Android native, iOS native, Xamarin, React Native, ...

**Comment by lukef** [comment]
Before the beta there wasn't access to some of the later Dart 2 additions (optional `new`, etc). This is what if consider more in the vein of "legacy". My point is that most people starting today don't need to migrate from the "older" syntax. In theory it's not an issue unless Dart decides to deprecate.

**Comment by lukef** [comment]
The Hamilton app (I worked on) will probably still have code like that (for example). I haven't looked in a while 😀

**Comment by lukef** [comment]
@zoechi - despite the above comments I still recommend closing this for the reasons I mentioned
