### ISSUE TITLE
fml::WriteAtomically  is  thread safe or process safe?

### ISSUE THREAD

**Issue by hangning** [flutter/flutter#104246]
In Posix,  fml::WriteAtomically  write data to a temp file, and  finally rename this temp file to destination file.
```c++
 ...
  std::stringstream stream;
  stream << file_name << ".temp";
  const auto temp_file_name = stream.str();

  auto temp_file = OpenFile(base_directory, temp_file_name.c_str(), true,
                            FilePermission::kReadWrite);
   ...
  if (::fsync(temp_file.get()) != 0) {
    return false;
  }

  return ::renameat(base_directory.get(), temp_file_name.c_str(),
                    base_directory.get(), file_name) == 0;
}
```

However, when two threads or processes write to same file like "test", they will handle the same temp file "test.temp". So this function seems to unsafe in multi-thread. 
Rename operation can  guarante that other thread will not read  dirty data.

I don't know if I understand correctly？Or we can add pid and tid to temp file's extension ?

**Comment by darshankawar** [comment]
Keeping it open and labeling for further insights from the team.

**Comment by chinmaygarde** [comment]
Neither. It only means that either all the contents will be written out or none (barring platform specific construction issues). We added it originally to make sure we weren't writing incomplete shader binary blobs to the cache.

Is there a specific issue with how this is being used today?

**Comment by hangning** [comment]
> Neither. It only means that either all the contents will be written out or none (barring platform specific construction issues). We added it originally to make sure we weren't writing incomplete shader binary blobs to the cache.
> 
> Is there a specific issue with how this is being used today?

Fine, I think I got it now.

**Comment by darshankawar** [comment]
Closing this as resolved per above comment.
