### ISSUE TITLE
Proposal to customize overflow for hintText in TextField

### ISSUE THREAD

**Issue by devibrahimkarahan** [flutter/flutter#104243]
Hi,

As you can see in the below link, `input_decorator.dart` doesnt use textstyle's overflow for hint, why we have to use ellipsis overflow, is there any special bug or something ? (I wanna use it for single line)

[https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/input_decorator.dart#L2119](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/input_decorator.dart#L2119)

One issue is already opened and closed about this, and yeah now textstyle has a overflow property but we cant use it for hint style.
* [https://github.com/flutter/flutter/issues/20569](https://github.com/flutter/flutter/issues/20569)

Flutter doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.4, on macOS 12.2 21D49 darwin-arm, locale tr)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
[✓] VS Code (version 1.67.0)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

• No issues found!

```

**Comment by darshankawar** [comment]
@devibrahimkarahan 
I see different overflow values to choose from as shown below:

<img width="649" alt="Screenshot 2022-05-20 at 5 41 14 PM" src="https://user-images.githubusercontent.com/67046386/169525735-155f4c2f-c462-4032-b4ec-0657140b3aae.png">

Or this isn't the correct interpretation ?

Can you provide a code sample or current limitation you are facing and what are you trying to achieve ?

**Comment by devibrahimkarahan** [comment]
Yeah you can pick one of them, its ok. But its not changing hint overflow, because its written hardcoded.

![image](https://user-images.githubusercontent.com/7039967/169529295-8c245d18-ec34-4c24-9c1f-18b36711836c.png)

I wanna use fade overflow or clip overflow, but i can't because of this hardcoded ellipsis line. Its always ellipsis (...), even if you gave any other overflow in hintStyle

**Comment by darshankawar** [comment]
It seems to have been fixed for `Text` widget as below:

https://github.com/flutter/flutter/blob/afdfc56bbb635350a18b90e5487c2dcc852f42be/packages/flutter/lib/src/painting/text_painter.dart#L24

Usage:

```
Center(
          child: Text(
            'This is sample text to check overflow implementation and whether ', style: TextStyle(
            overflow: TextOverflow.clip
          ),
          )
```

<img width="319" alt="Screenshot 2022-05-20 at 6 34 36 PM" src="https://user-images.githubusercontent.com/67046386/169535042-fe6a6e4b-f3a9-4e8f-9f91-229a91f0135b.png">


While, `overflow: TextOverflow.ellipsis` shows as expected:

<img width="324" alt="Screenshot 2022-05-20 at 6 34 22 PM" src="https://user-images.githubusercontent.com/67046386/169535226-21e6c8ca-a282-4175-8a75-9afe2bc99538.png">


But for `input_decorator.dart`, ,ie, essentially for `TextField` widget, it still seems to be hardcoded:

https://github.com/flutter/flutter/blob/afdfc56bbb635350a18b90e5487c2dcc852f42be/packages/flutter/lib/src/material/input_decorator.dart#L2119

So, the following implementation with different overflow options don't take effect and it still shows text in ellipsis mode:

```
TextField(
            decoration: InputDecoration(
              hintText: 'This is a sample text to check  overflow implementation and whether',
              hintStyle: TextStyle(
                overflow: TextOverflow.clip
              )
            )
          )
```

<img width="321" alt="Screenshot 2022-05-20 at 6 45 40 PM" src="https://user-images.githubusercontent.com/67046386/169535871-5d3b3b44-db5e-406f-b1b3-8a1b9a58359d.png">

**Comment by HansMuller** [comment]
As noted above, TextStyles can specify TextOverflow (https://github.com/flutter/flutter/pull/78927), but InputDecorator currently wires the hint's TextStyle.overflow to TextOverflow.ellipsis. What we should do instead is to use `hintStyle?.overflow ?? TextOverflow.ellipsis`. This will cause problems for existing apps that provide a hintStyle with a non-null overflow property but want depend on the existing behavior. Maybe this is rare; hard to know.

**Comment by devibrahimkarahan** [comment]
> As noted above, TextStyles can specify TextOverflow (#78927), but InputDecorator currently wires the hint's TextStyle.overflow to TextOverflow.ellipsis. What we should do instead is to use `hintStyle?.overflow ?? TextOverflow.ellipsis`. This will cause problems for existing apps that provide a hintStyle with a non-null overflow property but want depend on the existing behavior. Maybe this is rare; hard to know.

In my opinion, its not a problem. Because its not textStyle's overflow, its already hintStyle's overflow. If developer gave fade overflow to hintStyle, this means developer wants hint with fade overflow.

**Comment by huycozy** [comment]
@devibrahimkarahan This issue seems to be fixed by PR https://github.com/flutter/flutter/pull/114378. You can also check the current implementation at:

https://github.com/flutter/flutter/blob/6c2041e1e9e699cdf25bb23a01b01a4cdd722e72/packages/flutter/lib/src/material/input_decorator.dart#L2191

Also, there is a new issue with multiple lines at https://github.com/flutter/flutter/issues/127477. You can check it if necessary. 

So I will close this issue from here. If you disagree, please write in the comments and I will reopen it. Thanks!
