### ISSUE TITLE
TextField - IME position issue

### ISSUE THREAD

**Issue by littlecatheart** [flutter/flutter#104261]
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. Add a textfield widget with multiline enabled.
3. the position of IME is not correct for the first char.

**Expected results:**
![image](https://user-images.githubusercontent.com/43427550/169551631-be4076bb-7aa9-47f2-9d35-9e6062648668.png)

**Actual results:**
![image](https://user-images.githubusercontent.com/43427550/169551565-2b7cc37b-1bb3-491a-a173-f2587be649b5.png)

**Comment by maheshmnj** [comment]
Similar to https://github.com/flutter/flutter/issues/101642
https://github.com/flutter/flutter/issues/101222
