### ISSUE TITLE
Icons.table_restaurant_outlined

### ISSUE THREAD

**Issue by Samuelbrandani** [flutter/flutter#104200]
I has user a icon Icons.table_restaurant_outlined in my flutter project and when i put this, show me a middle finger emogi 
![Captura de Tela 2022-05-19 às 14 27 16](https://user-images.githubusercontent.com/36521572/169361087-868bfe2f-f968-4015-9613-df8690c07eae.png)

**Comment by gabrielscr** [comment]
no way! LOL

**Comment by lucavenir** [comment]
Is this serious? I guess not. This isn't happening to me

**Comment by Samuelbrandani** [comment]
i'm not kidding, it's real. i'm using nexus 5 emulator and 31 api android

**Comment by Samuelbrandani** [comment]
![Captura de Tela 2022-05-19 às 16 40 02](https://user-images.githubusercontent.com/36521572/169389029-7ba2898f-2eb9-48b3-bc28-dfac830d898a.png)
it's same if put in another place

**Comment by guidezpl** [comment]
This is going straight into my folder of original bugs 😄. Can you please provide the output of `flutter doctor -v`? I can't repo on Dartpad with 3.0.0

**Comment by Samuelbrandani** [comment]
flutter doctor -v                       
[✓] Flutter (Channel stable, 2.10.1, on macOS 12.1 21C52 darwin-arm, locale pt-BR)
    • Flutter version 2.10.1 at /Users/samuelbrandani/fvm/versions/2.10.1
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db747aa133 (3 months ago), 2022-02-09 13:57:35 -0600
    • Engine revision ab46186b24
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/samuelbrandani/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] VS Code (version 1.67.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 101.0.4951.64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Comment by guidezpl** [comment]
Ah, please upgrade (e.g. `flutter upgrade`), that version had issues with all icons pointing to other icons.

**Comment by Samuelbrandani** [comment]
tks!
