### ISSUE TITLE
Add an example for `AppBar.notificationPredicate`

### ISSUE THREAD

**Issue by TahaTesser** [flutter/flutter#104252]
https://github.com/flutter/flutter/pull/103899 added `notificationPredicate` property to support scroll under elevation for complex layouts similar to `RefreshIndicator. notificationPredicate` 

Add an example for `AppBar.notificationPredicate` to make easier to understand its usage for Material 3
(similar to https://github.com/flutter/flutter/pull/103894)

(Example will be added later since this change is not yet available on the `stable` channel,  adding this example now will show a broken example on api.flutter.dev)

**Comment by guidezpl** [comment]
The API docs use stable, no? with https://master-api.flutter.dev/ for HEAD

**Comment by TahaTesser** [comment]
> The API docs use stable, no? with https://master-api.flutter.dev/ for HEAD


Hey @guidezpl 

I mean dartpad on both api.flutter.dev and master-api.flutterdev runs the stable channel, If this example is added, it will immediately be a broken dartpad example.

We need a channel switcher for dartpad in API docs  just like dartpad.dev

Check out this recent of this problem -> https://github.com/flutter/flutter/issues/101779 (where I've updated TooltipState class and example was broken)

**Comment by guidezpl** [comment]
Ah gotcha, we should fix that, definitely

**Comment by TahaTesser** [comment]
`api.flutter.dev` is indeed using the `stable` channel and I'm adding the example, example should not show up in this page until the code sample is in the `stable` branch.

 Most people use this page so I think for it's safe to push the example since it will show up only in `master-api.flutter.dev` in the meantime.  I read somewhere on Discord that this page is not supposed to be consumed by regular users.

**Comment by TahaTesser** [comment]
part of https://github.com/flutter/flutter/issues/101048

**Comment by TahaTesser** [comment]
fixed https://github.com/flutter/flutter/pull/106018
