### ISSUE TITLE
[pigeon] C++ generator should make convenience constructors

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#104286]
It would be convenient for creating generated data class instances to have constructors with all fields (e.g., so they could be created inline as arguments in simple cases) instead of having to create them and then call each setter.

**Comment by azchohfi** [comment]
Is there anything we can do aside from a ctor? I'm wondering what undesired side effects this can stimulate since we can't force named parameters.

**Comment by stuartmorgan** [comment]
What do you mean by side effects?

It could make constructors that aren't all that readable at the call site (e.g., multiple `bool` fields), but that can be mitigated with inline comments on calls. (If it becomes a significant issue in practice, we could even generate a bunch of one-field structs called something like `<ClassName>Arg<FieldName>` and make those the constructor arguments.)

**Comment by azchohfi** [comment]
What I was thinking was that a breaking change with the generated constructor could be very hard to notice, since named parameters are not mandatory.
Imagine you have a class with 1 parameter, and you want to deprecate it in favor of another one, of same type, and this old one is not mandatory anymore. Still, you've added another field for something else. Since ctor parameters are not named, one could be confused by the other one, since it would not break the calls to it.
I like your suggestion, but maybe we are just over complicating things, and this is not an issue.

**Comment by stuartmorgan** [comment]
Oh, interesting! I hadn't considered that aspect. I can see a few options:
1. Ignore the problem as essentially inherent to C++
    * \+ Easy to generate, and less boilerplate code.
    * \+ Idiomatic at the call sites (arguably; good practice would generally be to do things like use enum args instead of bools, for instance, in hand-authored code).
    * \- A foot gun, as you describe. And unlike changing method arguments directly in C++, where hopefully people know to check all the call sites, the degree of separation between the Dart change (which doesn't have this problem) and the generated C++ code makes it much harder to realize that you need to.
2. Do the named-struct-arg trick
    * \+ Generated code should be small, with minimal perf impact.
    * \+ Prevents the foot-gun.
    * \+ Very self-documenting at the call sites.
    * \- Very non-idiomatic, and verbose. (Although it would kind of match the really verbose `EncodableValue` code that method channels already use...)
3. Pretend we're Java: make the constructor private, and create a builder with chainable setters.
    * \+ Prevents the foot-gun.
    * \+ Very self-documenting at the call sites.
    * \- Very non-idiomatic, and verbose.
    * \- Generated code is more complicated.
    * \- Doesn't allow requiring all fields to be initialized in the constructor, so we'll need default values to solve #104653

So maybe we should go ahead and do the struct trick. It shouldn't be hard, and we can see how we like it in practice, and re-evaluate if necessary.

**Comment by stuartmorgan** [comment]
I played with the struct approach a little bit, and it felt pretty clunky. I'm going to implement (1) for now, and we'll see if this ends up being a significant pain point in practice.

One argument against engineering either 2 or 3 is that either could be built as add-on layers in their own code by clients who find (1) problematic, without forcing people to adopt one or the other (or either). We can see if either one (or some other solution?) becomes a popular enough community solution to warrant adopting in Pigeon.
