### ISSUE TITLE
Laggy Janky scrolling on iOS 15.5 and stable 3.0.1

### ISSUE THREAD

**Issue by privateRepoF** [flutter/flutter#104376]
## Details

**Target Platform: iOS**
**Target OS version/browser: 15.5**
**Devices: iPhone 11 standard 60hz not promotion**

Scrolling is janky and laggy on stable 3.0.1 and iOS 15.5 and goes away when screen recording is turned on or landscape mode. It feels like it is running on debug mode or half the frames. Below is a video that shows the issue. If you exit to home screen and open app up again the scrolling also returns to smooth for a while. But exiting app completely and restarting has low framerate all throughout. App in video is on release mode. 

On Android release the app is smooth as butter so this is an iOS issue and goes away with screen recording or landscape. 

https://drive.google.com/file/d/1VLq-4vqUpaPDxRBgGPJMAZRCUw50YIUF/view?usp=sharing

The app is rather complex but nothing out of the ordinary so I cannot list a reproducible file. However this issue seems to be the same one as noted by people in these issue threads:

https://github.com/flutter/flutter/issues/31086

## Logs
Flutter doctor shows no issues
<details>
<summary>Logs</summary>

```
<!-- Finally, paste the output of running `flutter doctor -v` here, with your device plugged in. -->
Running "flutter pub get" in flutter_tools...                       4.5s
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.1, on macOS 12.3.1 21E258 darwin-x64, locale
    en-ZM)
[✓] Android toolchain - develop for Android devices (Android SDK version
    32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] Connected device (2 available)

• No issues found!
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @privateRepoF, would it be possible to capture some timeline traces using the devtools or some metrics in `Instruments` that capture the behavior you're seeing and share them with us? 

Can you also look at https://github.com/flutter/flutter/issues/96381 to see if it is similar to your issue? 

I did attempt to repro with the sample in https://github.com/flutter/flutter/issues/31086 but I didn't notice anything out of the ordinary. The frame time in instruments was steady across my testing. 

Can you also see if you can reproduce it with the sample in https://github.com/flutter/flutter/issues/31086 and share the metrics for that as well? You can take a look at the trace file below in `Instruments`. 

Thank you

[104376.trace.zip](https://github.com/flutter/flutter/files/8754528/104376.trace.zip)

**Comment by danagbemava-nc** [comment]
Hi @privateRepoF, thanks for taking a look at that issue. 

It will be best for you to share your findings and any other information that you have in that issue so that the team can take a look. 

Closing from here as duplicate. 

Thank you
