### ISSUE TITLE
An annotation error in /cupertino/refresh.dart

### ISSUE THREAD

**Issue by toly1994328** [flutter/flutter#104339]
location : [cupertino/refresh.dart](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/cupertino/refresh.dart#L387) line 387  

Stack's overflow was removed，but the documentation wasn't updated to reflect this

<img width="879" alt="image" src="https://user-images.githubusercontent.com/26687012/169675007-f81dd0b8-ca39-4eef-92c0-a5441184d97a.png">

**Comment by GautamSharma05** [comment]
I want to work on this please assign this issue to me

**Comment by GautamSharma05** [comment]
#104475 Review This

**Comment by piedcipher** [comment]
I can verify that Overflow.visible is not there and doc is updated to Clip.none. Hence closing this one.

![Screenshot_20240806-012211](https://github.com/user-attachments/assets/97002b30-3b35-4892-a613-179ac03679e6)
