### ISSUE TITLE
[WEB] Flutter tries to load a cryptic font in offline mode which slows down initial loading by 10s

### ISSUE THREAD

**Issue by Wissperwind** [flutter/flutter#104399]
Hi,

We use flutter websites in an intranet environment whith no internet access. We bundle canvaskit already. The build command already downloads canvaskit in the build folder and you can set the canvaskit location to this local location in the build command. So flutter can be used offline.
But at the moment a font is loaded: https://fonts.gstatic.com/s/roboto/v20/KFOmCnqEu92Fr1Me5WZLCzYlKw.ttf
I don't know what this font is for. But if we are offline the browser tries for 10s to reach this server and than continues displaying the website. This happens only on the first load because after that the browser chaches that the file is not reachable.
But this is really annoying to wait that long on first loade.

Could you pleas stop fetching resources from internet servers and package everything? Especially this font file if really needed should be packaged so that flutter websites can be use better without internet access.

**Comment by Wissperwind** [comment]
![Unbenannt](https://user-images.githubusercontent.com/20759873/169783439-22377160-a66c-4b9c-a187-c49059c118d7.PNG)

Here you can see the loading gap.

**Comment by Wissperwind** [comment]
```
[√] Flutter (Channel master, 3.1.0-0.0.pre.854, on Microsoft Windows [Version 10.0.19043.1645], locale de-DE)
    • Flutter version 3.1.0-0.0.pre.854 at C:\Users\akilian\Flutter SDK\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ec20ea80ad (2 days ago), 2022-05-21 16:28:06 -0400
    • Engine revision 1bfe551d6b
    • Dart version 2.18.0 (build 2.18.0-142.0.dev)
    • DevTools version 2.13.1

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\akilian\AppData\Local\Android\sdk
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] VS Code (version 1.52.1)
    • VS Code at C:\Users\akilian\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19043.1645]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 101.0.4951.67
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 101.0.1210.39

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.
```

**Comment by maheshmnj** [comment]
Hi @Wissperwind, Thanks for filing the issue. Did you create flutter project using `--offline` flag (e.g `flutter create myapp--offline` ). 
However looks like some font assets are still loaded from google fonts, Please see this https://github.com/flutter/flutter/issues/94264#issuecomment-994106628

**Comment by Wissperwind** [comment]
I build the project with flutter build web. And deployd it to our webserver.
This is a screenshot from a clients / users browser.

**Comment by maheshmnj** [comment]
> No, never heard about --offline. What does it do?

`--offline` flag will fetch all the dependencies required to build the app locally, from the flutter cli help

>   When "flutter pub get" is run by the create command, this indicates whether to run it in
    offline mode or not. In offline mode, it will need to have all dependencies already available in the pub cache to succeed.


Although, I feel the offline support is not completely working as per https://github.com/flutter/flutter/issues/94264#issuecomment-994106628, However can you please try creating a flutter project with `flutter create . --offline` and build in offline mode?

**Comment by maheshmnj** [comment]
> what do you mean with "build in offline mode"?

Sorry I meant build the app without the internet as per your usecase

>We use flutter websites in an intranet environment whith no internet access.

**Comment by Wissperwind** [comment]
Ok, I tried. I

- created a project with --offline
- navigated to the project folder
- executed flutter build web
- deployed the result to intranet server

But nothing has changed. It still tried to load erxternal resources like canvaskt and the KFOmCnqEu92Fr1Me5WZLCzYlKw.ttf font.

**Comment by maheshmnj** [comment]
> canvaskit is already a solved problem. I now how to set it to an offline location. This issue is about loading the font what slows down the initial load when offline.

Thanks for the confirmation @Wissperwind, But I wonder if the app loads in offline mode, it doesn't on my side in offline mode. 


<img width="823" alt="image" src="https://user-images.githubusercontent.com/31410839/169991436-232eea5d-aec6-4b40-8407-5409641ec72e.png">

<img width="830" alt="image" src="https://user-images.githubusercontent.com/31410839/169991483-b1081d64-c67d-4dfe-bde2-980a6d2df08f.png">


I believe this will be solved by https://github.com/flutter/flutter/issues/60069 as mention in linked comment above

cc ing @yjbanov for further insights on this issue.

**Comment by Wissperwind** [comment]
The first step to an offline working website is to build with 
`--dart-define=FLUTTER_WEB_CANVASKIT_URL=/canvaskit/`
That makes it use the bundeled canvaskit.
Of course there is room for improovements. That it does this by default if the project was created with --offline or that it automatically falls back to that if the online resource is not accessible.

As said early, I would like to focus on the font in this issue.

**Comment by yjbanov** [comment]
Offline mode with CanvasKit doesn't work due to the need for fallback fonts, which currently come from fonts.google.com. It should work in HTML mode, although I don't think we have tests for it, so there may be quirks that we're not aware of.

Let's continue tracking offline support in https://github.com/flutter/flutter/issues/60069
