### ISSUE TITLE
Beginners won't necessarily notice plugin examples

### ISSUE THREAD

**Issue by franklinharper** [flutter/flutter#10433]
## Steps to Reproduce
1. Imagine you're new to Flutter, and you want to learn how to use shared_preferences to update the UI of your app.
2. Go to https://pub.dartlang.org/packages/shared_preferences
3. Read the simplistic example code given on that page
4. Try to figure out how this can be used in a real world app.
5. Beginner tries to come up with a hacky solution that doesn't match Flutter best practices!

## Suggestion to fix

Add a link to the shared_preferences/example app, which does show a good pattern for using shared_preferences.

https://github.com/flutter/plugins/blob/master/packages/shared_preferences/example/lib/main.dart

**Comment by sethladd** [comment]
Thanks for the feedback!

**Comment by mit-mit** [comment]
Great feedback, we are already looking at how to best showcase this on pub!

**Comment by mit-mit** [comment]
Tracking pub site issue in https://github.com/dart-lang/pub-dartlang-dart/issues/186.

**Comment by mit-mit** [comment]
This has been resolved; we now highlight `/example/lib/main.dart` in a top-level tab on the package page, for example:
https://pub.dartlang.org/packages/shared_preferences#pub-pkg-tab-example
