### ISSUE TITLE
Flutter: Is it will be better if List[Index out of range] give null?

### ISSUE THREAD

**Issue by SittiphanSittisak** [flutter/flutter#104319]
the example:
```
main() {
  String msg = '*** empty ***';

  String? c = null;
  print("\nString? c;");

  print("\n0. print(c?.length ?? msg);");
  try {
    print(c?.length ?? msg);
  } catch (e) {
    print("----- ERROR -----");
  }

  print("\n--------------------------------------------------");

  List<String> a = [];
  print('\nList<String> a = [];');

  print("\n1. print(a[0]?.length ?? msg);");
  try {
    print(a[0]?.length ?? msg);
  } catch (e) {
    print("----- ERROR -----");
  }

  print("\n2. print(a.first?.length ?? msg);");
  try {
    print(a.first?.length ?? msg);
  } catch (e) {
    print("----- ERROR -----");
  }

  print("\n3. print(a.length > 0 ? a[0].length : msg);");
  try {
    print(a.length > 0 ? a[0].length : msg);
  } catch (e) {
    print("----- ERROR -----");
  }

  print("\n4.  print(a.asMap()[0]?.length ?? msg);");
  try {
    print(a.asMap()[0]?.length ?? msg);
  } catch (e) {
    print("----- ERROR -----");
  }
}
```
the result:
![image](https://user-images.githubusercontent.com/59549741/169647193-c48e9457-51d5-4e2c-a4bf-6337b5e3d4c9.png)

The basic null safety looks like solution 0.
But when I use List instead String type, the null safety doesn't work(solutions 1 and 2), and get the error is `RangeError (index): Index out of range: no indices are valid: 0`.
So I use the If statement to check that List doesn't empty before using it(solution 3).
Or change the List to the Map(solution 4).

When I use the List looks like
`String? data = emptyList[0];` or
`if(data == emptyList[0]) {}` or ...
It will be error.

Is it will be better if this returns null when the index out of range of the List like the Map?

**Comment by stuartmorgan** [comment]
Requests for changes in code Dart libraries need to be filled against Dart: https://github.com/dart-lang/sdk

Note that nothing is preventing you from making your own list implementation that has this behavior, and using that instead.
