### ISSUE TITLE
Map values displaying with brackets, 

### ISSUE THREAD

**Issue by Phero49** [flutter/flutter#104372]
i just upgraded to flutter 3 and i was trying to print out a value from a map for example `{'greet':'hello world'}` if i try to print out greet i get` (hello world)` instead of just `hello world` the same with keys

**Comment by danagbemava-nc** [comment]
Hi @Phero49, can you provide a complete minimal sample that shows the error you're getting? I tried with the code sample below and no brackets were displayed when I tried to access the map value. 

<img width="300" alt="Screenshot 2022-05-23 at 10 45 10" src="https://user-images.githubusercontent.com/88313112/169802799-3ee04b7c-5a68-4a33-8ebb-278f2793294b.png">

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        useMaterial3: true,
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {

  final Map<String, String> mapVal = {'greet':'hello world'};

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("${widget.title}"),
      ),
      body: Center(
        child: Text(mapVal['greet']!),
      ),
    );
  }
}
```
<details>
