### ISSUE TITLE
Error: Method 'addPostFrameCallback' cannot be called on 'SchedulerBinding?

### ISSUE THREAD

**Issue by gitHubAdminUser** [flutter/flutter#104342]
Can we remove the warning from the package?

../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/animations-2.0.2/lib/src/open_container.dart:631:24: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../Developer/flutter/packages/flutter/lib/src/scheduler/binding.dart').
      SchedulerBinding.instance!
                       ^
../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/animations-2.0.2/lib/src/open_container.dart:665:24: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../Developer/flutter/packages/flutter/lib/src/scheduler/binding.dart').
      SchedulerBinding.instance!

**Comment by ddxl123** [comment]
me too

**Comment by nehal076** [comment]
Agreed. Please remove warnings from flutter packages.

**Comment by darshankawar** [comment]
@gitHubAdminUser 
This is similar to https://github.com/flutter/flutter/issues/103561. Check [this](https://github.com/flutter/flutter/issues/103561#issuecomment-1129356149) issue comment for your reference and [this](https://docs.flutter.dev/development/tools/sdk/release-notes/release-notes-3.0.0#if-you-see-warnings-about-bindings) document to try various solutions.

Closing as duplicate.
