### ISSUE TITLE
Image.toByteData() becames super SLOW after Flutter 3

### ISSUE THREAD

**Issue by fullflash** [flutter/flutter#104300]
before flutter 3 it was working super fast 

```
ByteData b =
        await image.toByteData(format: ui.ImageByteFormat.png) as ByteData;
```

**Comment by doppio** [comment]
What platform are you on? It's completely broken on web: https://github.com/flutter/flutter/issues/104197

**Comment by fullflash** [comment]
Ios
Before flutter 3 it fast blazing fast.

**Comment by huycozy** [comment]
Hi @fullflash,
Please try to provide all or some of the information indicated in the [Performance Issue Template](https://github.com/flutter/flutter/issues/new?assignees=&labels=created+via+performance+template&template=5_performance_speed.md&title=) to investigate this issue further.

Thank you.

**Comment by fullflash** [comment]
i will try to provide more details but this is just one flutter internal sdk toByteData method.
just generate png data from bytes with flutter sdk 3 and previous version and you will see the difference with just simple stopwatch.

**Comment by huycozy** [comment]
Hi, please try to provide all or some of the information indicated in the [Performance Issue Template](https://github.com/flutter/flutter/issues/new?assignees=&labels=created+via+performance+template&template=5_performance_speed.md&title=) so that we'll have enough details to conclude on the issue. 
By the way, there is an issue #104197 with the `Image.toByteData` on Flutter 3.0, and it is being processed on #103803.

**Comment by spydon** [comment]
> By the way, there is an issue #104197 with the `Image.toByteData` on Flutter 3.0, and it is being processed on #103803.

That's for web though, this isssue is for ios?

**Comment by ninoid** [comment]
> before flutter 3 it was working super fast
> 
> ```
> ByteData b =
>         await image.toByteData(format: ui.ImageByteFormat.png) as ByteData;
> ```

VERY SLOW :( I also have same issue on iOS with flutter 3 (3.0.2).

**Comment by ssyzh** [comment]
this mush be an issues, I also have same issue on iOS with flutter 3 (3.0.2).
