### ISSUE TITLE
Jank after upgrade to flutter 3 with the video_player plugin

### ISSUE THREAD

**Issue by SarcasticNoodle** [flutter/flutter#104334]
## Details

Im am using the video_player plugin to play a normal mpeg4 video, so i can design the controls myself.
Everything works fine while playing the video without skipping / seeking to positions.
But after seeking to different positions the ui becomes unresponsive until i dispose the video player

#### Before Upgrading to flutter 3 (v2.10.4) everything runs fine and seeking has no impact on performance
![image](https://user-images.githubusercontent.com/28826881/169667375-def7cc01-44ff-4a4e-82ba-2d672ea445d6.png)

#### After upgrading to flutter 3 seeking causes huge jank spikes with frames taking over 120ms per frame
![image](https://user-images.githubusercontent.com/28826881/169667469-6893f655-06f0-44e3-a3cf-bb2395a699bd.png)

### Observatory Trace:
[dart-timeline-2022-5-21.zip](https://github.com/flutter/flutter/files/8748296/dart-timeline-2022-5-21.zip)

### Before upgrade to v3:

https://user-images.githubusercontent.com/28826881/169668493-243f98f0-d996-4b53-8c13-a27d884043f0.mp4

### After upgrade to v3:
https://user-images.githubusercontent.com/28826881/169668403-8f772e3d-cca2-466a-b4e8-0a7060b2aaa9.mp4

**Target Platform:** Android
**Target OS version/browser:** Android 10 & 12
**Devices:** OnePlus Nord, Google Pixel 6

## Logs

<details>
<summary>Flutter Doctor</summary>
[✓] Flutter (Channel stable, 3.0.0, on EndeavourOS 5.17.8-arch1-1, locale en_US.UTF-8)
    • Flutter version 3.0.0 at /home/thedome6/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ee4e09cce0 (12 days ago), 2022-05-09 16:45:18 -0700
    • Engine revision d1b9a6938a
    • Dart version 2.17.0
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /home/thedome6/Android/Sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+10)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = google-chrome-stable

[✓] Linux toolchain - develop for Linux desktop
    • clang version 13.0.1
    • cmake version 3.23.1
    • ninja version 1.10.2
    • pkg-config version 1.8.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] IntelliJ IDEA Ultimate Edition (version 2022.1)
    • IntelliJ at /home/thedome6/.local/share/JetBrains/Toolbox/apps/IDEA-U/ch-0/221.5591.52
    • Flutter plugin version 67.1.4
    • Dart plugin version 221.5591.58

[✓] Connected device (3 available)
    • OnePlus Nord (mobile) • 617fd1c7 • android-arm64  • Android 10 (API 29)
    • Linux (desktop)       • linux    • linux-x64      • EndeavourOS 5.17.8-arch1-1
    • Chrome (web)          • chrome   • web-javascript • Google Chrome 101.0.4951.64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
</details>

**Comment by exaby73** [comment]
Hi @SarcasticNoodle. Can you provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)?
