### ISSUE TITLE
getTemporaryDirectory call in PathProvider returns 'Library/Caches' directory on iOS

### ISSUE THREAD

**Issue by alardizabal** [flutter/flutter#10431]
When I call `getTemporaryDirectory` on iOS it points to the `Library/Caches` directory. The source comments for `getTemporaryDirectory` reads that it uses the `NSTemporaryDirectory` API (`tmp` directory). `Library/Caches` corresponds to `NSCachesDirectory`. `NSCachesDirectory` seems closer to the `getCacheDir` API on Android as far as behavior. This may just require an update to the source documentation.

**`getTemporaryDirectory` returns:**
```
/var/mobile/Containers/Data/Application/A6DB6EC4-CA05-4FBE-A8BF-E3FE7F5607F8/Library/Caches/myitems/test0001.jpg
```
**`NSTemporaryDirectory` returns:**
```
/var/mobile/Containers/Data/Application/A6DB6EC4-CA05-4FBE-A8BF-E3FE7F5607F8/tmp/myitems/test0001.jpg
```
**from Path Provider source:**
```
  /// On iOS, this uses the `NSTemporaryDirectory` API.
  ///
  /// On Android, this uses the `getCacheDir` API on the context.
  Future<Directory> getTemporaryDirectory() async {
    final String path = await _channel.invokeMethod('getTemporaryDirectory');
    if (path == null)
      return null;
    return new Directory(path);
  }
```

**flutter doctor output:**
```
[✓] Flutter (on Mac OS X 10.12.5 16F73, locale en-US, channel master)
    • Flutter at /Users/albertlardizabal/dev/flutter
    • Framework revision 0809a4fcdc (25 hours ago), 2017-05-31 09:00:04 -0700
    • Engine revision 75c74dc463
    • Tools Dart version 1.24.0-dev.3.0

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at /Users/albertlardizabal/Library/Android/sdk
    • Platform android-25, build-tools 25.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.3.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3.2, Build version 8E2002
    • ios-deploy 1.9.0
    • CocoaPods version 1.2.1

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Gradle version 3.2
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2016.3.7)
    • Dart plugin version 163.13137
    • Flutter plugin version 12.1
```

**Comment by eseidelGoogle** [comment]
Here is the code:
https://github.com/flutter/plugins/blob/master/packages/path_provider/ios/Classes/PathProviderPlugin.m

FYI @szakarias.  @cbracken or @xster might have opinions as to if this is the "correct" behavior on iOS or not.  In any case, very easy to change!

**Comment by Hixie** [comment]
Marking as milestone 3 since this will be a breaking API change.

**Comment by mit-mit** [comment]
cc @cbracken can you help us determine what the "correct" behavoir is?

**Comment by collinjackson** [comment]
path_provider seems to be using NSCachesDirectory, I think this was just a documentation issue.

https://github.com/flutter/plugins/commit/79037146b0a70384a9a24c4bec076e0c4551113c#diff-6f3de9136bfae65f73ed7b70915c2c1e

**Comment by uiboy** [comment]
@collinjackson so how do I access the `NSTemporaryDirectory` API , there are certain ios plugins which create temporary files there and we want to be able to clear them as part of cleanup.

**Comment by josencv** [comment]
> @collinjackson so how do I access the `NSTemporaryDirectory` API , there are certain ios plugins which create temporary files there and we want to be able to clear them as part of cleanup.

I'm curious on how to achieve this as well.

**Comment by jpgpuyo** [comment]
> > @collinjackson so how do I access the `NSTemporaryDirectory` API , there are certain ios plugins which create temporary files there and we want to be able to clear them as part of cleanup.
> 
> I'm curious on how to achieve this as well.


This works for me in iOS 14. Not sure if it works in all devices:

```
final Directory directory = await getApplicationDocumentsDirectory();
String nsTemporaryPath = "${directory.parent.path}/tmp/";
```
