### ISSUE TITLE
Apple Store updates with Flutter 3.0 result in Apple removing all applications

### ISSUE THREAD

**Issue by justrach** [flutter/flutter#104323]
I had a few Flutter applications under my App Store line up and they all were working fine until I started uploading the iPAS made with Flutter 3.0 using the Transporter tool

I had over 30 builds for one of my enterprise applications however, for some reason after build all of them get uploaded to the App Store the error that pops up would be

"The requested app doesn't exist"

There have been similar discussions elsewhere, is there any way to resolve this?

**Comment by ueman** [comment]
Desktop application may not have such a lifecycle. If there's no such lifecycle, it can't be called.

**Comment by huycozy** [comment]
Hi @justrach. This issue might be an issue on Apple’s end. And your question is best suited for support channels like StackOverflow or Apple forums, so please ask the same there for solutions if any.
Btw, I've just seen there are some fixes that may help you: 
- https://stackoverflow.com/a/66580295/5921933
- https://developer.apple.com/forums/thread/673860

I'm closing this issue as above explanation. If you disagree about this, please drop a comment and I will reopen it.
