### ISSUE TITLE
Android Release page looks funny on iOS mobile Safari

### ISSUE THREAD

**Issue by efortuna** [flutter/flutter#10432]
## Steps to Reproduce

Visit this page in Safari with an iOS device: https://flutter.io/android-release/
My current setup: I'm running iOS version 10.3.2 (latest version as of this writing) on an iPhone SE
I attached a screenshot of what I see -- basically the left part of the text is cut off, and I can't seem to scroll sideways to see that portion of the text.  

![img_5613](https://cloud.githubusercontent.com/assets/2112792/26693511/4780e924-46b9-11e7-88d3-387130255c5a.PNG)

**Comment by sethladd** [comment]
Thanks! we're working on a fix :)

**Comment by sethladd** [comment]
I'm going to close this in favor of https://github.com/flutter/flutter/issues/10120#issuecomment-305360720
