### ISSUE TITLE
[Flutter 3] Debugger for web is not working with Chrome 100+

### ISSUE THREAD

**Issue by ryuujo1573** [flutter/flutter#104382]
## Steps to Reproduce

I ran into #101224 when using 2.13-pre from beta branch, but after I upgraded flutter to `3.0.1` on stable branch, the same problem happens.
1. Create new Flutter project.
2. Debug with `Chrome (Web)`

## Logs

<details>
<summary>Logs</summary>

```
Launching lib/main.dart on Chrome in debug mode...
Waiting for connection from debug service on Chrome...
This app is linked to the debug service: ws://127.0.0.1:59785/jel3oK0Fw60=/ws
Debug service listening on ws://127.0.0.1:59785/jel3oK0Fw60=/ws

💪 Running with sound null safety 💪
Debug service listening on ws://127.0.0.1:59785/jel3oK0Fw60=/ws
Flutter Web Bootstrap: Auto
ChromeProxyService: Failed to evaluate expression 'ChewieController': InternalError: No frame with index 48.
```

```
[✓] Flutter (Channel stable, 3.0.1, on macOS 12.0.1 21A559 darwin-arm, locale
    en-CN)
    • Flutter version 3.0.1 at /Users/ryuujo/env/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (3 days ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2
    • Pub download mirror https://mirrors.sjtug.sjtu.edu.cn/dart-pub
    • Flutter download mirror https://mirrors.sjtug.sjtu.edu.cn

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/ryuujo/Library/Android/sdk
    • Platform android-31, build-tools 30.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses

[!] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS
      development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] VS Code (version 1.67.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.0.1 21A559 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 101.0.4951.64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.
```

</details>

## Thank you.

**Comment by annagrin** [comment]
@darshankawar I see some strange behavior with a new project (but not the example/hello_world) in VSCode - some breakpoints are not set and a new "main.dart" file is opened for the ones that are hit. I'll look into it.

/cc @DanTup for any insights.

**Comment by annagrin** [comment]
Update - I had a pubspec.yaml in a wrong place (inside a lib directory) - after I removed it everything seems to work fine. So still no repro.  I am running on an Intel macos laptop though, will try to find a way to test on an arm machine.

@ryuujo1573 how do you create your project?
@darshankawar do breakpoints work when you try?

**Comment by annagrin** [comment]
@helin24 I can set breakpoints in VSCode but not in IntelliJ apparently. I don't see any failed `addBreakpointsWithScriptUri` calls in the verbose logs. This happens on `flutter/examples/hello_world` as well. Appreciate any insights!

**Comment by DanTup** [comment]
If the issue occurs in VS Code, capturing the DAP/VM Service traffic may be helpful:

- Run the [**Dart: Capture Debugging Logs** command](https://dartcode.org/docs/logging/#capture-debugging-logs)
- Reproduce the issue
- Click **Cancel** on the logging notification to stop logging and open the log

If the log is started before the debug session, it will run `flutter run` with `-v` so it may produce a large file. If the Flutter build output is likely not relevant, starting logging after starting to launch the debug session will be the non-verbose output.

(@elliette fyi)

**Comment by annagrin** [comment]
> If the issue occurs in VS Code, capturing the DAP/VM Service traffic may be helpful:

Thank you Danny! Apparently the VSCode problem was in between the chair and the keyboard (me:). IntelliJ does seem to repro the real issue.

**Comment by annagrin** [comment]
Update: my mistake, IntelliJ works fine. Still no repro.

**Comment by ryuujo1573** [comment]
> Update - I had a pubspec.yaml in a wrong place (inside a lib directory) - after I removed it everything seems to work fine. So still no repro. I am running on an Intel macos laptop though, will try to find a way to test on an arm machine.
> 
> @ryuujo1573 how do you create your project? Did you set a breakpoint and try to evaluate something in your repro? @darshankawar do breakpoints work when you try?

I created it using Flutter 2 beta branch, now I'm trying `Flutter 3` with new project.
Thank you!

**Comment by ryuujo1573** [comment]
Hi, I ran into the same problem :-o
```
Chrome is up to date
Version 101.0.4951.64 (Official Build) (arm64)
```
### Runtime Log
```
Flutter assets will be downloaded from https://mirrors.sjtug.sjtu.edu.cn. Make sure you trust this source!
Downloading Web SDK...
Downloading CanvasKit...
Running "flutter pub get" in video_gallery_sdu...
Launching lib/main.dart on Chrome in debug mode...
Waiting for connection from debug service on Chrome...
This app is linked to the debug service: ws://127.0.0.1:49435/m-X0I2oSAiU=/ws
Debug service listening on ws://127.0.0.1:49435/m-X0I2oSAiU=/ws

💪 Running with sound null safety 💪
Debug service listening on ws://127.0.0.1:49435/m-X0I2oSAiU=/ws
Flutter Web Bootstrap: Programmatic
ChromeProxyService: Failed to evaluate expression 'chewieController': InternalError: Expression evaluation in async frames is not supported. No frame with index 48..
```

This seems the debugger has caught an exception, and break at where it occurs
<div style="display: flex; flex-direction: row;">
<img width="400" alt="image" src="https://user-images.githubusercontent.com/16525512/169928787-b78bbc39-9aaa-4ca3-b657-156f78b17bad.png">
<img width="130" alt="image" src="https://user-images.githubusercontent.com/16525512/169928833-d9e3aed9-3056-42be-9c63-97c9b2afe254.png">
</div>

<img width="765" alt="image" src="https://user-images.githubusercontent.com/16525512/169929082-5f14d965-ab8d-435c-99fa-873fb81157a9.png">

Is this ok?

**Comment by ryuujo1573** [comment]
The same with `Chrome 99.0.4844.51`, is my AS not working properly or something missing?

**Comment by darshankawar** [comment]
> @darshankawar do breakpoints work when you try?

Thanks for your insights @annagrin . I tried with breakpoints but strangely they don't work, as they turn like below although I still don't see the `ChromeProxyService` log as reported by OP.

<img width="423" alt="Screenshot 2022-05-24 at 11 12 42 AM" src="https://user-images.githubusercontent.com/67046386/169957775-044e65d0-9efb-46c4-aafa-ca80fd940204.png">

which lead me to this open issue which talks about same case https://github.com/flutter/flutter/issues/103397

@ryuujo1573 From your latest screenshot, I still see the `ChromeProxyService` logs, so we probably need to keep it open until we have a final verdict from concerned team.

**Comment by annagrin** [comment]
@darshankawar The project mentioned in the issue https://github.com/flutter/flutter/issues/103397 has a base change in index.html, which is currently failing on windows. So I don't think this is the same issue.

Could you please provide the `flutter doctor -v` output? I wonder if this is related to arm...

**Comment by darshankawar** [comment]
> Could you please provide the `flutter doctor -v` output? I wonder if this is related to arm...

<details>
<summary> stable flutter doctor -v </summary>

```

[✓] Flutter (Channel unknown, 3.0.1, on macOS 12.2.1 21D62 darwin-x64, locale
    en-GB)
    • Flutter version 3.0.1 at /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository unknown
    • Framework revision fb57da5f94 (5 days ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 65.1.4
    • Dart plugin version 213.7228

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.2.1 21D62 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 101.0.4951.64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

</details>
