### ISSUE TITLE
[Flutter_Build_iOS] success on 2.10.3 and fail on 3.0.1

### ISSUE THREAD

**Issue by grisvladko** [flutter/flutter#104353]
Hello
we are trying to update our flutter env , currently using 2.5.3.
we have successfully ran flutter 2.10.3 but we fail on 3.0.1 with this exception:

```
2022-05-22 14:49:59.472 xcodebuild[64808:11482349] Requested but did not find extension point with identifier
    Xcode.IDEKit.ExtensionSentinelHostApplications for extension Xcode.DebuggerFoundation.AppExtensionHosts.watchOS of plug-in
    com.apple.dt.IDEWatchSupportCore
    2022-05-22 14:49:59.472 xcodebuild[64808:11482349] Requested but did not find extension point with identifier
    Xcode.IDEKit.ExtensionPointIdentifierToBundleIdentifier for extension Xcode.DebuggerFoundation.AppExtensionToBundleIdentifierMap.watchOS of plug-in
    com.apple.dt.IDEWatchSupportCore
```
 
there might be problems with compatability to watchos 8.5? 

using : 
xcode 13.4
flutter 3.0.1
pods 1.11.3

can you please provide some insight on that? Thank you!

**Comment by julienlebren** [comment]
Same issue for me.

**Comment by blue492** [comment]
Same here, the app works 2.10.5 but not in 3.0.1

**Comment by julienlebren** [comment]
To bring some precision: in my case, it has been working with Flutter 3 during a few days, I think it stopped working when Xcode updated to 13.4.

**Comment by darshankawar** [comment]
@grisvladko 
The log you provided earlier doesn't seem to be complete. Please provide entire verbose log in properly formatted text so that we can take a look at what's going on.

**Comment by grisvladko** [comment]
Failed to build iOS app
Error output from Xcode build:
↳
    2022-05-23 11:21:29.078 xcodebuild[96515:11740175] Requested but did not find extension point with identifier
    Xcode.IDEKit.ExtensionSentinelHostApplications for extension Xcode.DebuggerFoundation.AppExtensionHosts.watchOS of plug-in
    com.apple.dt.IDEWatchSupportCore
    2022-05-23 11:21:29.079 xcodebuild[96515:11740175] Requested but did not find extension point with identifier
    Xcode.IDEKit.ExtensionPointIdentifierToBundleIdentifier for extension Xcode.DebuggerFoundation.AppExtensionToBundleIdentifierMap.watchOS of plug-in
    com.apple.dt.IDEWatchSupportCore
    ** BUILD FAILED **


Xcode's output:
↳
    Writing result bundle at path:
        /var/folders/rp/fcvyjnf158l6ncn927tfbr4m0000gn/T/flutter_tools.vjkhgV/flutter_ios_build_temp_dirq7ZYhb/temporary_xcresult_bundle

    lib/widgets/ez_count/ez_count_product_page/product_page_content.dart:59:22: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which
    excludes null.
     - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../development/flutter/packages/flutter/lib/src/widgets/binding.dart').
          WidgetsBinding.instance!
                         ^
    lib/widgets/currency/currency_transfers/transfer_summary.dart:249:23: Warning: Operand of null-aware operation '!' has type 'String' which excludes null.
                    if (!(toolTipTxt!.contains("null")))
                          ^
    lib/common_widgets/ToolTipWidget.dart:1025:20: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
     - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../development/flutter/packages/flutter/lib/src/widgets/binding.dart').
        WidgetsBinding.instance!.addPostFrameCallback((_) {
                       ^
    lib/widgets/currency/currency_amount_selection/currency_amount_selection_content.dart:260:60: Warning: Operand of null-aware operation '??' has type
    'String' which excludes null.
                                  GeneralErrorPopUpWidget(msg: error ?? "", img: "assets/declined_icon.png"));
                                                               ^
    libraries/searchable_dropdown/lib/dropdown_search.dart:546:26: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
     - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../development/flutter/packages/flutter/lib/src/widgets/binding.dart').
              WidgetsBinding.instance!.addPostFrameCallback((_) {
                             ^
    libraries/searchable_dropdown/lib/dropdown_search.dart:578:26: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
     - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../development/flutter/packages/flutter/lib/src/widgets/binding.dart').
              WidgetsBinding.instance!.addPostFrameCallback((_) {
                             ^
    ../../development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_math_fork-0.5.0/lib/src/widgets/selectable.dart:459:24: Warning: Operand of
    null-aware operation '!' has type 'SchedulerBinding' which excludes null.
     - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../development/flutter/packages/flutter/lib/src/scheduler/binding.dart').
          SchedulerBinding.instance!.addPostFrameCallback((_) {
                           ^
    ../../development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_math_fork-0.5.0/lib/src/widgets/selection/overlay_manager.dart:138:28: Warning:
    Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
     - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../development/flutter/packages/flutter/lib/src/scheduler/binding.dart').
          if (SchedulerBinding.instance!.schedulerPhase ==
                               ^
    ../../development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_math_fork-0.5.0/lib/src/widgets/selection/overlay_manager.dart:140:26: Warning:
    Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
     - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../development/flutter/packages/flutter/lib/src/scheduler/binding.dart').
            SchedulerBinding.instance!
                             ^
    ../../development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_math_fork-0.5.0/lib/src/widgets/selection/web_selection_manager.dart:119:24: Warning:
    Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
     - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../development/flutter/packages/flutter/lib/src/scheduler/binding.dart').
          SchedulerBinding.instance!
                           ^
    ../../development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_math_fork-0.5.0/lib/src/widgets/selection/overlay.dart:141:26: Warning: Operand of
    null-aware operation '!' has type 'SchedulerBinding' which excludes null.
     - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../development/flutter/packages/flutter/lib/src/scheduler/binding.dart').
        if (SchedulerBinding.instance!.schedulerPhase ==
                             ^
    ../../development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_math_fork-0.5.0/lib/src/widgets/selection/overlay.dart:143:24: Warning: Operand of
    null-aware operation '!' has type 'SchedulerBinding' which excludes null.
     - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../development/flutter/packages/flutter/lib/src/scheduler/binding.dart').
          SchedulerBinding.instance!.addPostFrameCallback(_markNeedsBuild);
                           ^
    ../../development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_math_fork-0.5.0/lib/src/widgets/selection/overlay.dart:193:26: Warning: Operand of
    null-aware operation '!' has type 'SchedulerBinding' which excludes null.
     - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../development/flutter/packages/flutter/lib/src/scheduler/binding.dart').
        if (SchedulerBinding.instance!.schedulerPhase ==
                             ^
    ../../development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_math_fork-0.5.0/lib/src/widgets/selection/overlay.dart:195:24: Warning: Operand of
    null-aware operation '!' has type 'SchedulerBinding' which excludes null.
     - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../development/flutter/packages/flutter/lib/src/scheduler/binding.dart').
          SchedulerBinding.instance!.addPostFrameCallback(_markNeedsBuild);
                           ^
    ../../development/flutter/.pub-cache/hosted/pub.dartlang.org/win32-2.3.1/lib/src/structs.g.dart:554:31: Error: Member not found: 'UnicodeChar'.
      int get UnicodeChar => Char.UnicodeChar;
                                  ^^^^^^^^^^^
    ../../development/flutter/.pub-cache/hosted/pub.dartlang.org/win32-2.3.1/lib/src/structs.g.dart:555:38: Error: Setter not found: 'UnicodeChar'.
      set UnicodeChar(int value) => Char.UnicodeChar = value;
                                         ^^^^^^^^^^^
    ../../development/flutter/.pub-cache/hosted/pub.dartlang.org/win32-2.3.1/lib/src/structs.g.dart:557:29: Error: Member not found: 'AsciiChar'.
      int get AsciiChar => Char.AsciiChar;
                                ^^^^^^^^^
    ../../development/flutter/.pub-cache/hosted/pub.dartlang.org/win32-2.3.1/lib/src/structs.g.dart:558:36: Error: Setter not found: 'AsciiChar'.
      set AsciiChar(int value) => Char.AsciiChar = value;
                                       ^^^^^^^^^
    Failed to package /MYPACKAGEPATH.
    Command PhaseScriptExecution failed with a nonzero exit code
    note: Using new build system
    note: Planning
    note: Build preparation complete
    note: Building targets in dependency order

    Result bundle written to path:
        /var/folders/rp/fcvyjnf158l6ncn927tfbr4m0000gn/T/flutter_tools.vjkhgV/flutter_ios_build_temp_dirq7ZYhb/temporary_xcresult_bundle


Encountered error while building for device.

**Comment by Faisalkc4u** [comment]
Same issue

**Comment by darshankawar** [comment]
@grisvladko 
Thanks for the log. From it, it seems you and others in this thread are hitting https://github.com/flutter/flutter/issues/103561. Some of the warnings are coming from community packages for which take a look at https://docs.flutter.dev/development/tools/sdk/release-notes/release-notes-3.0.0#if-you-see-warnings-about-bindings and https://docs.flutter.dev/development/tools/sdk/release-notes/release-notes-3.0.0#dependencies for various solutions.

Closing this per issue linked above.

**Comment by blue492** [comment]
@darshankawar  I did `dart fix --apply`  and I don't have any "SchedulerBinding" functions in my app. 
 I tested both 3.0.0 and 3.0.1, the app doesn't works in them.  The app still can't build in iOS or Android.

My app works well in 2.10.5

**Comment by grisvladko** [comment]
@darshankawar Thank for the references, though it is not necesserely a duplicate, because i report a build failure while the issues address warnings. wernings don't prevent you from flutter build ios to succeed, but i can't build my app for ios.
you suggest that this is a problem in our bindings which are coused by the change of : 

[COPIED FROM FLUTTER WEBSITE : https://docs.flutter.dev/development/tools/sdk/release-notes/release-notes-3.0.0#if-you-see-warnings-about-bindings] 

These are caused by a simplification of the API (the instance property on bindings is now non-nullable), combined with an eager compiler that wants to report any case where redundant null-aware operators (such as ! and ?.) that are used when they’re not necessary

**Comment by darshankawar** [comment]
Thanks for the feedback. Reopening.

**Comment by darshankawar** [comment]
> ../../development/flutter/.pub-cache/hosted/pub.dartlang.org/win32-2.3.1/lib/src/structs.g.dart:554:31: Error: Member not found: 'UnicodeChar'.
>       int get UnicodeChar => Char.UnicodeChar;
>                                   ^^^^^^^^^^^
>     ../../development/flutter/.pub-cache/hosted/pub.dartlang.org/win32-2.3.1/lib/src/structs.g.dart:555:38: Error: Setter not found: 'UnicodeChar'.
>       set UnicodeChar(int value) => Char.UnicodeChar = value;
>                                          ^^^^^^^^^^^
>     ../../development/flutter/.pub-cache/hosted/pub.dartlang.org/win32-2.3.1/lib/src/structs.g.dart:557:29: Error: Member not found: 'AsciiChar'.
>       int get AsciiChar => Char.AsciiChar;
>                                 ^^^^^^^^^
>     ../../development/flutter/.pub-cache/hosted/pub.dartlang.org/win32-2.3.1/lib/src/structs.g.dart:558:36: Error: Setter not found: 'AsciiChar'.
>       set AsciiChar(int value) => Char.AsciiChar = value;

These seem to be the errors from the log which are affecting your build. Again, these seem to be coming from third party package `win32-2.3.1` for which there was a similar [issue](https://github.com/flutter/flutter/issues/103674) and flutter team member closed it per [this](https://github.com/flutter/flutter/issues/103674#issuecomment-1125969994) comment.

You may try [this](https://github.com/flutter/flutter/issues/103674#issuecomment-1125898276) solution and [this](https://github.com/flutter/flutter/issues/103674#issuecomment-1126083869) explaination as why it need to be reported in dedicated repo. 

Check if that helps.

**Comment by grisvladko** [comment]
we will check out the dependencies and see how upgrading them slowly will effect the project, for now we are staying on 2.10.5 so thank you for the help. if this keeps happening without any solution i will file another issue or ask to reopen this one. Thank you for the provided help.

**Comment by darshankawar** [comment]
Thanks for update. Based on your comment and the one I shared earlier for reasoning, I'll close it for now.
