### ISSUE TITLE
Tree red on gerrit post failure

### ISSUE THREAD

**Issue by GaryQian** [flutter/flutter#104308]
https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20ci_yaml%20flutter%20roller/3003/overview

The relevant commit is just a comment change (https://github.com/flutter/flutter/commit/1e1f4bcfb56105912a90ffa1a3a317dfb724612b)

```gerrit: failed to post to "https://flutter-review.googlesource.com/a/changes/infra~main~I87368bbe5eb6038efa2fda0ed52dfcec5bb8d6c6/revisions/current/review" with &{  map[]   [{flutter-infra@grotations.appspotmail.com CC false }] false false}, status code 400```

**Comment by GaryQian** [comment]
cc @godofredoc @keyonghan

**Comment by godofredoc** [comment]
Fixed!

**Comment by christopherfujino** [comment]
Happened again https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20ci_yaml%20flutter%20roller/3602/overview

**Comment by yusuf-goog** [comment]
@godofredoc what was the fix that you originally applied for this issue?

**Comment by christopherfujino** [comment]
> @christopherfujino this seems to not be immediately happening anymore, can we reduce priority to p2?

SGTM

**Comment by keyonghan** [comment]
Lowering priority as this is not happening in weeks. Also moved to technical debts.

**Comment by yusuf-goog** [comment]
obsolete.
