### ISSUE TITLE
plugin(google_sign_in): use Object type for GoogleSignInAccount operator

### ISSUE THREAD

**Issue by evan361425** [flutter/flutter#104378]
When using [mockito](https://pub.dev/packages/mockito) for GoogleSignInAccount, the static analyzer starts complaint:

    'Mock.==' ('bool Function(Object)') isn't a valid concrete implementation of 'GoogleSignInAccount.==' ('bool Function(dynamic)').

Which means it should be Object in the `operator ==`'s argument.

**Comment by evan361425** [comment]
I think using [firebase_auth_mocks](https://pub.dev/packages/firebase_auth_mocks) can fix this issue.

**Comment by danagbemava-nc** [comment]
Hi @evan361425, this is a duplicate of https://github.com/flutter/flutter/issues/101895, which has just been fixed. 

Closing from here as duplicate thank you.
