### ISSUE TITLE
[go_router] remove `debugLogDiagnostics` from `GoRouterDelegate`

### ISSUE THREAD

**Issue by Anas35** [flutter/flutter#104470]
Consider deprecating and removing `debugLogDiagnostics` from `GoRouterDelegate`. 

It was added in `GoRouterDelegate` to turn on and off the logging. After migrating to `Logging` packages, It is now managed in 'GoRouter'.

As of now, `debugLogDiagnostics` acts as an instance variable that does nothing in `GoRouterDelegate`.

**Comment by maheshmnj** [comment]
cc: @chunhtai

**Comment by bambinoua** [comment]
Maybe my questin is for this subject. I set `debugLogDiagnostics` to `false` and debug information disappeared but it looks like `go_router` "attaches" to my `Logger` and prints its messages to log. How can I disable this?

**Comment by Anas35** [comment]
@bambinoua it's a known issue. see ->  https://github.com/flutter/flutter/issues/99115

**Comment by chunhtai** [comment]
close as a duplicate

**Comment by Anas35** [comment]
It is a different issue than #99115. This issue proposes to remove `debugLogDiagnostics` from `GoRouterDelegate` which does nothing as of now.
cc @chunhtai

**Comment by chunhtai** [comment]
Wouldnt it be better if we fix debugLogDiagnostics and people can decide whether they want to keep it or disable?

**Comment by Anas35** [comment]
Ah! I might not have written it clearly. Right now, `debugLogDiagnostics` is defined in two classes - `GoRouter` and `GoRouterDelegate`. 
one in `GoRouter` is newly one which was declared while migrating `Logging` packages.
`GoRouterDelegate`'s `debugLogDiagnostics` was used to enable or disable debug print which we no longer use now. as of now  `debugLogDiagnostics` in `GoRouterDelegate` does nothing.

**Comment by chunhtai** [comment]
yes makes sense

**Comment by chunhtai** [comment]
will be fixed as part of the https://github.com/flutter/packages/pull/1653

**Comment by johnpryan** [comment]
Fixed in flutter/packages#2189
