### ISSUE TITLE
[SnackBar] SnackBarBehavior.floating not working Flutter 2.10.5 & 3.0.1

### ISSUE THREAD

**Issue by Cryward** [flutter/flutter#104455]
I am using a SnackBar in my project and I noticed that when I want to use `behavior: SnackBarBehavior.floating` it does not work, it just does not run, there is no error message in the console, I am trying the example of api.flutter.dev, testing on android 12.

The code is as follows, I execute this from a button

```dart
ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(
              action: SnackBarAction(
                label: 'Action',
                onPressed: () {
                  // Code to execute.
                },
              ),
              content: const Text('Awesome SnackBar!'),
              duration: const Duration(milliseconds: 1500),
              width: 280.0, // Width of the SnackBar.
              padding: const EdgeInsets.symmetric(
                horizontal: 8.0, // Inner padding for SnackBar content.
              ),
              behavior: SnackBarBehavior.floating,
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.circular(10.0),
              ),
            ),
          );
```

```flutter doctor -v
[√] Flutter (Channel stable, 2.10.5, on Microsoft Windows [VersiÃ³n 10.0.22000.675], locale es-CL)
    • Flutter version 2.10.5 at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (5 weeks ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at C:\Users\HP\AppData\Local\Android\sdk
    • Platform android-32, build-tools 32.0.0
    • Java binary at: C:\Users\HP\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\211.7628.21.2111.8193401\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Build Tools 2019 16.11.9)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
    • Visual Studio Build Tools 2019 version 16.11.32106.194
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] Android Studio (version 2021.1)
    • Android Studio at C:\Users\HP\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\211.7628.21.2111.8193401
    • Flutter plugin version 67.1.1
    • Dart plugin version 211.7817
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] VS Code (version 1.67.2)
    • VS Code at C:\Users\HP\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.40.0

[√] Connected device (4 available)
    • SM G973F (mobile) • R28M21MZ6XR • android-arm64  • Android 12 (API 31)
    • Windows (desktop) • windows     • windows-x64    • Microsoft Windows [VersiÃ³n 10.0.22000.675]
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 101.0.4951.67
    • Edge (web)        • edge        • web-javascript • Microsoft Edge 101.0.1210.53

[√] HTTP Host Availability
    • All required HTTP hosts are available
```

**Comment by danagbemava-nc** [comment]
Hi @Cryward, I just tested this on both flutter 2.10.5 and flutter 3.0.1 and in both cases, the snackbar shows up as expected. 
See the recording below. I tested on a Pixel 4a Emulator running android 12. 

<details>
<summary>recording</summary>

https://user-images.githubusercontent.com/88313112/169974209-63bc1907-c8c7-4d90-bbf0-ad740578d749.mov
</details>


<details>
<summary>code sample used</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        appBarTheme: AppBarTheme(
          systemOverlayStyle: SystemUiOverlayStyle.light.copyWith(
            systemNavigationBarColor: Colors.green,
          ),
        ),
      ),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: Container(),
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(
              action: SnackBarAction(
                label: 'Action',
                onPressed: () {
                  // Code to execute.
                },
              ),
              content: const Text('Awesome SnackBar!'),
              duration: const Duration(milliseconds: 1500),
              width: 280.0, // Width of the SnackBar.
              padding: const EdgeInsets.symmetric(
                horizontal: 8.0, // Inner padding for SnackBar content.
              ),
              behavior: SnackBarBehavior.floating,
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.circular(10.0),
              ),
            ),
          );
        },
      ),
    );
  }
}

```
</details>


It would help if you could provide a complete runnable sample so that we can verify this issue. 

Thank you

**Comment by Cryward** [comment]
I made a new project and it works correctly as you indicate, but when I want to use floating snackbar in my project it doesn't work, I don't know why, the project I have uses several libraries, so I don't know what can prove this, I will close the query, since it is a problem of my project, thanks.

> Hi @Cryward, I just tested this on both flutter 2.10.5 and flutter 3.0.1 and in both cases, the snackbar shows up as expected. See the recording below. I tested on a Pixel 4a Emulator running android 12.
> 
> recording
>  Screen.Recording.2022-05-24.at.07.28.59.mov 
> code sample used
> ```dart
> import 'package:flutter/material.dart';
> import 'package:flutter/services.dart';
> 
> void main() {
>   runApp(const MyApp());
> }
> 
> class MyApp extends StatelessWidget {
>   const MyApp({Key? key}) : super(key: key);
> 
>   @override
>   Widget build(BuildContext context) {
>     return MaterialApp(
>       title: 'Flutter Demo',
>       theme: ThemeData(
>         primarySwatch: Colors.blue,
>         appBarTheme: AppBarTheme(
>           systemOverlayStyle: SystemUiOverlayStyle.light.copyWith(
>             systemNavigationBarColor: Colors.green,
>           ),
>         ),
>       ),
>       home: const MyHomePage(),
>     );
>   }
> }
> 
> class MyHomePage extends StatelessWidget {
>   const MyHomePage({Key? key}) : super(key: key);
> 
>   @override
>   Widget build(BuildContext context) {
>     return Scaffold(
>       appBar: AppBar(),
>       body: Container(),
>       floatingActionButton: FloatingActionButton(
>         onPressed: () {
>           ScaffoldMessenger.of(context).showSnackBar(
>             SnackBar(
>               action: SnackBarAction(
>                 label: 'Action',
>                 onPressed: () {
>                   // Code to execute.
>                 },
>               ),
>               content: const Text('Awesome SnackBar!'),
>               duration: const Duration(milliseconds: 1500),
>               width: 280.0, // Width of the SnackBar.
>               padding: const EdgeInsets.symmetric(
>                 horizontal: 8.0, // Inner padding for SnackBar content.
>               ),
>               behavior: SnackBarBehavior.floating,
>               shape: RoundedRectangleBorder(
>                 borderRadius: BorderRadius.circular(10.0),
>               ),
>             ),
>           );
>         },
>       ),
>     );
>   }
> }
> ```
> 
> It would help if you could provide a complete runnable sample so that we can verify this issue.
> 
> Thank you

**Comment by bleroux** [comment]
@Cryward
Maybe the `SnackBar` in your app is off screen.
There is a pending PR for this : https://github.com/flutter/flutter/pull/102073
It might get merged in master soon.
