### ISSUE TITLE
AndroidContextGl_MSAAx4 test is flaky 

### ISSUE THREAD

**Issue by blasten** [flutter/flutter#104463]
This test was added in https://github.com/flutter/engine/commit/7b38d4594587b0e529594de1b9a313c5006fc136, but it doesn't seem to be currently running.

I seem to be getting different values for `sample_count` every time this test is run. 

Example log:
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8813332198409600145/+/u/Android_Unit_Tests/stdout?format=raw

cc @dnfield

**Comment by dnfield** [comment]
Is this flaky or did it just never work on CI?

This seems to pass locally pretty consistently. It's possible that on CI, MSAA isn't available for the emulator.

**Comment by blasten** [comment]
did you test on an emulator or physical device? I used emulators in both.

**Comment by dnfield** [comment]
Emulator.

**Comment by GaryQian** [comment]
@dnfield Do we still want to re-enable the test?

**Comment by dnfield** [comment]
No one is actually using this flag, and we'd likely need a physical device that we know supports MSAA to get this test re-enabled. I think this can be treated with low priority.

**Comment by chinmaygarde** [comment]
Obsoleted by https://github.com/flutter/flutter/issues/148257
