### ISSUE TITLE
PictureRecorder->Picture->toImage doesn't work with Images on Web

### ISSUE THREAD

**Issue by luigi-rosso** [flutter/flutter#104445]
The combination of PictureRecorder, Picture, and toImage doesn't work with drawImage or drawVertices on Web.

Repro here: https://github.com/luigi-rosso/flutter-picture-recorder-image-bug

This example draws a circle and then two image over it. The image on the left is drawn with [canvas.drawImageRect](https://github.com/luigi-rosso/flutter-picture-recorder-image-bug/blob/25651e25bf5f2cee04a3d2b0a704c735b81c03b7/lib/main.dart#L9). The one on the right is drawn with [canvas.drawVertices](https://github.com/luigi-rosso/flutter-picture-recorder-image-bug/blob/25651e25bf5f2cee04a3d2b0a704c735b81c03b7/lib/main.dart#L49). The canvas is created with a [PictureRecorder](https://github.com/luigi-rosso/flutter-picture-recorder-image-bug/blob/25651e25bf5f2cee04a3d2b0a704c735b81c03b7/lib/main.dart#L65). 

Note how it works in the Mac app but not on the Web. 

I ran the web build with:
```
flutter run --release --dart-define=FLUTTER_WEB_USE_SKIA=true -d chrome
```
I ran the mac build with:
```
flutter run -dmacos
```

<img width="821" alt="repro" src="https://user-images.githubusercontent.com/454182/169895127-69bef8a7-e16c-4da6-bdf9-c9a87e92746c.png">

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, 3.0.0, on macOS 12.3.1 21E258 darwin-arm, locale en-US)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed
      instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4)
[✓] Chrome - develop for the web
[!] Android Studio (not installed)
[✓] VS Code (version 1.67.1)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

! Doctor found issues in 2 categories.
```

**Comment by maheshmnj** [comment]
Hi @luigi-rosso, Thanks for filing the issue. 

There is a similar issue describing this case https://github.com/flutter/flutter/issues/103803, Please follow up there for further updates, Closing this issue as a duplicate. If you disagree feel free to write in the comments and we will reopen it.

Also please see https://github.com/flutter/flutter/issues/103803#issuecomment-1133520718

Thank you.
