### ISSUE TITLE
Mac customer_testing is trying to build the flutter tool from a different commit?

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#104433]
See https://github.com/flutter/flutter/pull/104431#issuecomment-1135001826

This is the CI build: https://ci.chromium.org/ui/p/flutter/builders/try/Mac%20customer_testing/31608/overview

Here are the relevant logs:

```
From https://github.com/flutter/flutter
 * [new branch]            master     -> master
 * [new branch]            master     -> origin/master
Warning: you are leaving 1 commit behind, not connected to
any of your branches:

  19204c238e Roll engine to d882b2d12375a4ae54baeccd2f7b0aafef422831

Switched to branch 'master'
+ dart __deprecated_pub get
Downloading Darwin x64 Dart SDK from Flutter engine 1bfe551d6b5adec64bb677cbb31ffd56c5acff49...
Building flutter tool...
Exhausted heap space, trying to allocate 32 bytes.
```

Note the engine version is from upstream HEAD, not the PR

This means that if upstream master Flutter SDK is broken, this CI test will have to be broken, even if run on a PR that would have fixed it

**Comment by keyonghan** [comment]
Based on https://flutter-review.googlesource.com/c/recipes/+/25820/2/recipe_modules/adhoc_validation/resources/customer_testing.sh#11, @godofredoc is this intended to run against HEAD?

**Comment by christopherfujino** [comment]
oh, this looks like on line 18 it re-checks out the original branch?

**Comment by keyonghan** [comment]
> oh, this looks like on line 18 it re-checks out the original branch?

Yeah, it intended to checkout the original branch, but all presubmit builds are with `GIT_BRANCH: master`, so it always checks out the HEAD. Looking to see if we can check out the commit instead.

**Comment by keyonghan** [comment]
https://flutter-review.googlesource.com/c/recipes/+/30840 to check out the commit.

**Comment by keyonghan** [comment]
Builders are not checking out correct commit to cover changes. Closing.
