### ISSUE TITLE
PopupMenuButton is not triggering onSelected callback when PopupMenuItem value is null

### ISSUE THREAD

**Issue by Fraa-124** [flutter/flutter#104404]
A minimal bug reproduction is here.

Open the console to see a print trace when an option is selected. In case of null, none is printed

https://dartpad.dev/?id=10b110c96c63a9059bbd72fafcf241d0

**Comment by danagbemava-nc** [comment]
Hi @Fraa-124, it would appear that this is working as intended.  According to the docs

```dart
  /// Called when the user selects a value from the popup menu created by this button.
  ///
  /// If the popup menu is dismissed without selecting a value, [onCanceled] is
  /// called instead.
  final PopupMenuItemSelected<T>? onSelected;

  /// Called when the user dismisses the popup menu without selecting an item.
  ///
  /// If the user selects a value, [onSelected] is called instead.
  final PopupMenuCanceled? onCanceled;
```

See also https://github.com/flutter/flutter/blob/ec20ea80ad98007bd022648168e7b3cc38b2e665/packages/flutter/lib/src/material/popup_menu.dart#L1190-L1197.

Is there something that you're trying to achieve with the null value?

**Comment by Fraa-124** [comment]
Ohh I didn't see the onCanceled callback! Perfect then, sorry for the inconveniences!
