### ISSUE TITLE
[Material 3] Using NestedScrollView with SliverAppBar makes content go behind it, even though it fits on the screen.

### ISSUE THREAD

**Issue by iamcosmin** [flutter/flutter#104440]
Part of #104363.

When using the new variants SliverAppBar.medium and SliverAppBar.large in a NestedScrollView without using SliverOverlapAbsorber and SliverOverlapInjector, content goes behind the SliverAppBar even though it fits on the screen. This behavior does not occur when using SliverAppBar in a CustomScrollView.

**Expected result:**
- The SliverList children should not go under the SliverAppBar when they all fit on the screen (when scrolling, only the expanded title should collapse, the SliverList children should not go under the collapsed SliverAppBar).

**Actual result:**
- The SliverList children go under the SliverAppBar when collapsing instead of remaining on the screen, though they fit the current layout.

https://user-images.githubusercontent.com/47219753/169709890-513bd44e-0c53-4953-8c3f-40f0142857c2.mp4

<details>
<summary>Code sample:</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const TestApp());
}

class TestApp extends StatelessWidget {
  const TestApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.from(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.blue),
        useMaterial3: true,
      ),
      home: Scaffold(
        body: NestedScrollView(
          headerSliverBuilder: (context, innerBoxIsScrolled) => [
            SliverAppBar.large(
              title: const Text('Example App'),
              forceElevated: innerBoxIsScrolled,
            ),
          ],
          body: CustomScrollView(
            slivers: [
              SliverList(
                delegate: SliverChildBuilderDelegate(
                  (context, index) {
                    return ListTile(
                      title: Text('Item ${index.toString()}'),
                    );
                  },
                  childCount: 5,
                ),
              )
            ],
          ),
        ),
      ),
    );
  }
}
```
</details>

**Comment by Piinks** [comment]
It looks like you are missing the SliverOverlap* widgets. These are essential when using the NestedScrollView with a header that overlaps like the SliverAppBar above. There are several examples in the api docs:

- https://api.flutter.dev/flutter/widgets/NestedScrollView-class.html
- https://api.flutter.dev/flutter/widgets/SliverOverlapAbsorber-class.html
- https://api.flutter.dev/flutter/widgets/SliverOverlapInjector-class.html

FYI @darrenaustin

**Comment by iamcosmin** [comment]
With trial and error, I discovered myself that I was doing things incorrectly. 
I posted this issue to make it clear to myself, as well as for others.
Thank you, I will close this.
