### ISSUE TITLE
Flutter needs to integrate with Mozart Views to handle hit testing properly

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#10443]
@abarth 
@Hixie

**Comment by Hixie** [comment]
cc @chinmaygarde @abarth @jason-simmons Any of you able to look at this in the near future?

**Comment by chinmaygarde** [comment]
Aye. I am working on hit testing in the composer. Will follow up with @apwilson in person regarding the specifics.

**Comment by eseidelGoogle** [comment]
@apwilson was asking about this bug today.  I assume @chinmaygarde is still on this?

**Comment by eseidelGoogle** [comment]
I'm going to assume @chinmaygarde is on this for now, please un-assign if not.

**Comment by Hixie** [comment]
cc @alanlgardner 

I assume this is requesting that we provide a way to take an Offset in global coordinates from the top-left of our view, and return a list and a boolean, the list being the child views that we would consider hit at that point before us, and the boolean being whether we would consider ourselves to be hit at that point if none of those child views consider themselves to be hit.

Is that accurate?

**Comment by Hixie** [comment]
@chinmaygarde, let me know if you'd any help with this one, especially on the framework side (I am less sure what needs doing on the engine side).

**Comment by Hixie** [comment]
@chinmaygarde Is this what your big patch is doing?

**Comment by chinmaygarde** [comment]
This should be done already.

**Comment by Hixie** [comment]
Cool, ok. Closing for now, please re-open if we haven't addressed the problem to your satisfaction!
