### ISSUE TITLE
Warning in run project

### ISSUE THREAD

**Issue by msnmuhsinpt** [flutter/flutter#104481]
/C:/flutterSDK/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_easyloading-3.0.3/lib/src/widgets/container.dart:64:24: Warning: Operand of null-aware operation '?.' has type 'Schedu
lerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/C:/flutterSDK/flutter/packages/flutter/lib/src/scheduler/binding.dart').
      SchedulerBinding.instance?.schedulerPhase ==
                       ^
/C:/flutterSDK/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_easyloading-3.0.3/lib/src/widgets/container.dart:101:24: Warning: Operand of null-aware operation '?.' has type 'Sched
ulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/C:/flutterSDK/flutter/packages/flutter/lib/src/scheduler/binding.dart').
      SchedulerBinding.instance?.addPostFrameCallback((_) => completer
                       ^
/C:/flutterSDK/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_easyloading-3.0.3/lib/src/widgets/container.dart:112:24: Warning: Operand of null-aware operation '?.' has type 'Sched
ulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/C:/flutterSDK/flutter/packages/flutter/lib/src/scheduler/binding.dart').
      SchedulerBinding.instance?.addPostFrameCallback((_) => completer
                       ^
/C:/flutterSDK/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_easyloading-3.0.3/lib/src/widgets/overlay_entry.dart:35:26: Warning: Operand of null-aware operation '?.' has type 'Sc
hedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/C:/flutterSDK/flutter/packages/flutter/lib/src/scheduler/binding.dart').
    if (SchedulerBinding.instance?.schedulerPhase ==
                         ^
/C:/flutterSDK/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_easyloading-3.0.3/lib/src/widgets/overlay_entry.dart:37:24: Warning: Operand of null-aware operation '?.' has type 'Sc
hedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/C:/flutterSDK/flutter/packages/flutter/lib/src/scheduler/binding.dart').
      SchedulerBinding.instance?.addPostFrameCallback((_) {
                       ^
/C:/flutterSDK/flutter/.pub-cache/hosted/pub.dartlang.org/cached_network_image-3.2.0/lib/src/image_provider/cached_network_image_provider.dart:109:29: Warning: Operand of null-aware op
eration '?.' has type 'PaintingBinding' which excludes null.
 - 'PaintingBinding' is from 'package:flutter/src/painting/binding.dart' ('/C:/flutterSDK/flutter/packages/flutter/lib/src/painting/binding.dart').
      () => PaintingBinding.instance?.imageCache?.evict(key),
                            ^
/C:/flutterSDK/flutter/.pub-cache/hosted/pub.dartlang.org/cached_network_image-3.2.0/lib/src/image_provider/multi_image_stream_completer.dart:152:22: Warning: Operand of null-aware ope
ration '?.' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/C:/flutterSDK/flutter/packages/flutter/lib/src/scheduler/binding.dart').
    SchedulerBinding.instance?.scheduleFrameCallback(_handleAppFrame);
                     ^

**Comment by danagbemava-nc** [comment]
@msnmuhsinpt
This is similar to https://github.com/flutter/flutter/issues/103561. Check [this](https://github.com/flutter/flutter/issues/103561#issuecomment-1129356149) issue comment for your reference and [this](https://docs.flutter.dev/development/tools/sdk/release-notes/release-notes-3.0.0#if-you-see-warnings-about-bindings) document to try various solutions.

Closing as duplicate.
