### ISSUE TITLE
The following assertion was thrown during performLayout(): 'package:flutter/src/rendering/object.dart': Failed assertion: line 1840 pos 12: '!_debugDoingThisLayout': is not true.

### ISSUE THREAD

**Issue by goodavid** [flutter/flutter#104427]
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by exaby73** [comment]
Hello @goodavid. Looks like your issue report isn't complete. Please edit your original comment to include the following:

- [Minimal reproducible code sample][1]
- Logs showing the error
- `flutter doctor -v` output

[1]: https://stackoverflow.com/help/minimal-reproducible-example
