### ISSUE TITLE
Android Release doc doesn't mention --release

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#10440]
For https://flutter.io/android-release/

It doesn't mention `--release` in the "Building a release APK" section.

However, https://flutter.io/ios-release/ says to use `--release`

Is --release the default? We might want to unify how these two docs talk about building for release.

**Comment by sethladd** [comment]
cc @mit-mit

**Comment by mit-mit** [comment]
Yes, `--release` is the default for `flutter build`:

```
mit-macbookpro2:app01 mit$ flutter build apk
Running 'gradle assembleRelease'...                  28.9s
Built build/app/outputs/apk/app-release.apk (7.1MB).
mit-macbookpro2:app01 mit$ flutter build ios
Building com.yourcompany.app01 for device (ios-release)...
Running Xcode build...                                1.9s
```
