### ISSUE TITLE
IOS build Error: "Encountered error while archiving for device."

### ISSUE THREAD

**Issue by bharawdwajrahul** [flutter/flutter#104497]
Unable to build flutter IOS app with flutter version 3.0.1 and 3.0.0

NOTE: The build was and is working perfectly for version 2.10.5 and below.

**Comment by bharawdwajrahul** [comment]
[building_ios (1).log](https://github.com/flutter/flutter/files/8763117/building_ios.1.log)
[flutte_doctor_v.txt](https://github.com/flutter/flutter/files/8763119/flutte_doctor_v.txt)
[Podfile.txt](https://github.com/flutter/flutter/files/8763141/Podfile.txt)
[Pubspec.txt](https://github.com/flutter/flutter/files/8763150/Pubspec.txt)
[pubspec_lock.txt](https://github.com/flutter/flutter/files/8763153/pubspec_lock.txt)

**Comment by bharawdwajrahul** [comment]
I am building the application on Codemagic, I don't have a log with verbose, I've attached all the other things you have asked for, please take a look.

**Comment by danagbemava-nc** [comment]
Hi @bharawdwajrahul, on your local machine are you able to build the android apk successfully?

I'm asking this because buried somewhere in the logs you shared, there's an error in one of your files
`lib/screens/maps/locationPicker.dart:93:7: Error: Expected ',' before this.`

**Comment by danagbemava-nc** [comment]
Hi @bharawdwajrahul, are you running the same versions of flutter locally and on Codemagic? 

Can you also make sure that your dependencies are up to date and try building again to see if you experience the error?
