### ISSUE TITLE
`SelectionArea` should support selecting text with arrow keys

### ISSUE THREAD

**Issue by nilsreichardt** [flutter/flutter#104556]
## Description
This is an extracted feature request of @justinmc comment:
> Should the arrow keys work in this PR? They aren't working for me.

https://github.com/flutter/flutter/pull/95226#pullrequestreview-976138900

On HTML pages you can select text with your arrow keys after starting a selection (e. g. selecting with the mouse).

https://user-images.githubusercontent.com/24459435/170143980-39ba3dfe-5b74-4250-812b-23b35b4421d7.mov

**Comment by maheshmnj** [comment]
Hi @nilsreichardt, Thanks for filing the issue. That looks like a valid feature request.

**Comment by nilsreichardt** [comment]
I see this is a duplicate of https://github.com/flutter/flutter/issues/104541

**Comment by nilsreichardt** [comment]
@maheshmnj There is also a new label called `f: selection` for ticket related to the `SelectionArea` widget
