### ISSUE TITLE
Could not extend class _CupertinoDesktopTextSelectionControls

### ISSUE THREAD

**Issue by kugoo109** [flutter/flutter#104511]
Flutter version: 3.0.1
Dart version: 2.17.1

I'm trying to handlePaste event from TextField and I have found one solution to create a custom TextSelectionControls and extend from the _CupertinoDesktopTextSelectionControls class.

However, I could not extend the _CupertinoDesktopTextSelectionControls class. VSCode keep showing this error.
```
Classes can only extend other classes.
Try specifying a different superclass, or removing the extends clause.
```

Here is my custom class:
```
class AppCupertinoDesktopTextSelectionControls extends _CupertinoDesktopTextSelectionControls {
  AppCupertinoDesktopTextSelectionControls({
    required this.onPaste,
  });
  ValueChanged<TextSelectionDelegate> onPaste;
  @override
  Future<void> handlePaste(final TextSelectionDelegate delegate) {
    onPaste(delegate);
    return super.handlePaste(delegate);
  }
}
```

What should I do to extend class _CupertinoDesktopTextSelectionControls?
I did the same to extend CupertinoTextSelectionControls and it's looking fine.

**Comment by maheshmnj** [comment]
Hi @kugoo109, Thanks for filing the issue. Looks like `_CupertinoDesktopTextSelectionControls` is not publicly accessible, But [TextSelectionControls](https://api.flutter.dev/flutter/widgets/TextSelectionControls-class.html) is, would that help to achieve your usecase?
