### ISSUE TITLE
_translateCanvas() isn't called after zooming in browser

### ISSUE THREAD

**Issue by fatduckling** [flutter/flutter#104573]
This is a continuation of issue #77084 as the fix done there is only a partial fix.

A comment by @HeinrichJanzing said:

> Interestingly, as @linxuebin1990 noticed, size.width and size.height often suffer from precision issues, making them subtly different, causing this path to not be taken as often as expected. When it is taken, the devicePixelRatio change is detected, the logical size of the canvas is updated to match, but the canvas' translation, intended to compensate for the canvas being oversized, isn't updated. This translation is expressed in logical pixels and thus should also be updated.

> If this doesn't happen, it causes the Flutter UI to appear shifted vertically in the browser's viewport. This can be reproduced in any Flutter web app by using Ctrl+mousewheel to change the zoom level. Sooner or later it pops up. Luckily, changing the zoom level again or resizing the window does trigger the call to _translateCanvas() and fixes things.

This ticket aims to fix this issue.

**Comment by huycozy** [comment]
@johnsonmh: Since there are many people had this issue. Should we reopen #77084 or label this new issue?

**Comment by linxuebin1990** [comment]
> @johnsonmh: Since there are many people had this issue. Should we reopen #77084 or label this new issue?

Yeah， There are still some scenarios where this problem occurs. I think I can reopen it. The remaining issues can be fixed 编by https://github.com/flutter/engine/pull/33604, but need to wait @fatduckling to configure CLA.

**Comment by huycozy** [comment]
Hey @fatduckling, so I will close this issue as duplication, please follow up on #77084 for further updates.
