### ISSUE TITLE
[Android] Can we get better performance in platformView if we don't use `convertToImageView()` and still use SurfaceView in Hybrid Composition?

### ISSUE THREAD

**Issue by eggfly** [flutter/flutter#104574]
I modified the java code in engine as below and it let the lowest layer still use SurfaceView (not converted to FlutterView):
```diff
diff --git a/shell/platform/android/io/flutter/plugin/platform/PlatformViewsController.java b/shell/platform/android/io/flutter/plugin/platform/PlatformViewsController.java
index 08c8138655..9999555437 100644
--- a/shell/platform/android/io/flutter/plugin/platform/PlatformViewsController.java
+++ b/shell/platform/android/io/flutter/plugin/platform/PlatformViewsController.java
@@ -718,7 +718,7 @@ public class PlatformViewsController implements PlatformViewsAccessibilityDelega
 
   private void initializeRootImageViewIfNeeded() {
     if (synchronizeToNativeViewHierarchy && !flutterViewConvertedToImageView) {
-      flutterView.convertToImageView();
+      // flutterView.convertToImageView();
       flutterViewConvertedToImageView = true;
     }
   }
@@ -856,11 +856,12 @@ public class PlatformViewsController implements PlatformViewsAccessibilityDelega
     // Otherwise, acquire the latest image.
     if (flutterViewConvertedToImageView && currentFrameUsedPlatformViewIds.isEmpty()) {
       flutterViewConvertedToImageView = false;
-      flutterView.revertImageView(
-          () -> {
-            // Destroy overlay surfaces once the surface reversion is completed.
-            finishFrame(false);
-          });
+      finishFrame(false);
+//      flutterView.revertImageView(
+//          () -> {
+//            // Destroy overlay surfaces once the surface reversion is completed.
+//            finishFrame(false);
+//          });
       return;
     }
     // Whether the current frame was rendered using ImageReaders.
```

This lowest layer always be a full screen size! I think if we use SurfaceView instead of ImageView, it can avoid a "copy buffer" call in java code, and avoid the "if" case to check whether it's Android 10 or above to use hardware accelaration version of bitmap got from ImageReader.

I only change the "background layer" and let it not use `convertToImageView`, but still use ImageView for the overlay layers.

The result of the engine change in Android Hierarchy Viewer:
<img width="1392" alt="any screen" src="https://user-images.githubusercontent.com/922837/170172145-7ab60e46-b802-486b-9d61-12f2abbee6ed.png">

Is there any historical reason to use `convertToImageView` for the background layer? Can you foresee any problems if we don't use `ImageView` for the lowest layer?

cc @blasten 😄

----- 

Oh I found the `synchronizeToNativeViewHierarchy(false)` to disable this conversion, but why this API is deprecated?

https://github.com/flutter/flutter/blob/f85209272dca619d15cb3cbc59fc6681319f7da7/packages/flutter/lib/src/services/platform_views.dart#L187-L191

**Comment by blasten** [comment]
That won't work because if you add the platform view to a scrollable list, then you will see that the Flutter  UI gets momentarily out of sync causing a lag.

**Comment by blasten** [comment]
Why do you still need to use this code path? If possible, we would like everyone to use the new texture mode.

**Comment by chinmaygarde** [comment]
Closing this as answered.
