### ISSUE TITLE
Should `SelectionArea` cursor lose to click cursor?

### ISSUE THREAD

**Issue by guidezpl** [flutter/flutter#104595]
When wrapping something selectable like `Text` in an `InkWell` with `onTap`, the cursor changes unexpectedly.

Should the `SelectionArea` cursor be made to "lose" to the click cursor?

```
import 'package:flutter/material.dart';

class SelectionAreaCursorRepro extends StatelessWidget {
  const SelectionAreaCursorRepro({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: SelectionArea(
        child: Scaffold(
          body: InkWell(
            onTap: () => {},
            child: const Padding(
              padding: EdgeInsets.all(32.0),
              child: Text('Hello'),
            ),
          ),
        ),
      ),
    );
  }
}
```

https://user-images.githubusercontent.com/6655696/170219503-68196aea-c1b0-429a-8b10-f316fcde3fdf.mp4

**Comment by nilsreichardt** [comment]
Looking at HTML behavior there is this not the case. Cursor is still set the click.

https://user-images.githubusercontent.com/24459435/170221783-01777dde-7101-4eea-a9b0-dc982bed72eb.mov

(I use the [flutter.dev](https://flutter.dev) website).

**Comment by chunhtai** [comment]
I did a few experiments, it looks like native web button can not be selected if the selection starts from inside, it can only be selected if the selection starts outside, so it makes sense to not override the cursor. For flutter it can still be selected if the selection starts inside.

If the web behavior is something we want, we need to have a machoism to let the button subtree to know the selection can't start inside and therefore do not override the cursor.

**Comment by dkwingsmt** [comment]
To complement chunhtai's explanation: The mouse cursor should reflect the action at the mouse position. If it's drag-selecting the texts, then it should be a text cursor. If it's pressing the button, then it should be the default/hand cursor.

That makes this scenario a weird design: You can drag-select the text _and_ you can click the button. But is it really a correct design? When you are dragging the text, the button shows an inkwell splash first, indicating that the button _might_ be pressed, making the text selection action feel insecure and flaky.

Unsurprisingly, dragging through the text starting from inside the button is _not_ possible on Web either. If you check out GitHub's buttons, such as [the current issue page](https://github.com/flutter/flutter/issues/104595), find the "Comment" buttons, you can not even select them from outside: GitHub labeled them with `user-select: none;`.

As a conclusion, I believe texts within a button should not be selectable, including from the outside. Cursors should be the default/hand cursor throughout the button.

**Comment by guidezpl** [comment]
Had a quick look at code to try and fix this but I don't understand how the cursor is being set, can you point me in the right direction?

**Comment by dkwingsmt** [comment]
Hi! Thanks for investing. The cursor is usually set via the MouseRegion widget. Internally it is discovered by MouseTracker in a hit test, which notifies the engine via a metho channel.

**Comment by guidezpl** [comment]
A naive solution might be to have `MouseRegion` wrap its child in `SelectionContainer.disabled` when the cursor is set to anything but `SystemMouseCursors.text`.

I also tried `InkResponse`, which works well for Material, but not much else.

**Comment by dkwingsmt** [comment]
I would say this works as intended and there's nothing to "fix". At best this would make a new feature, some "IgnoreCursor" widget that adds an exception to the cursor algorithm. But you'll want to explain why that exception should be considered worthwhile.

**Comment by guidezpl** [comment]
I believe this is still a valid issue. To illustrate, please see the following:


https://user-images.githubusercontent.com/6655696/178814844-88ad79a6-b824-4aea-84ae-bebc2d119976.mp4


https://user-images.githubusercontent.com/6655696/178814867-0826e0c4-348c-49ec-bf57-65472797dea5.mp4

The cursor is a click cursor over selectable elements on web.

**Comment by nimr77** [comment]
now we are with flutter 3.3 with SelectionArea feature, yet this is an issue with the widget, this is also on the desktop

**Comment by Vluf** [comment]
I noticed the users of my website to be confused by not seeing the hand cursor. It makes the buttons look like they don't do anything at all if it shows the text cursor.

**Comment by davidmigloz** [comment]
> A naive solution might be to have MouseRegion wrap its child in SelectionContainer.disabled when the cursor is set to anything but SystemMouseCursors.text.

Even if I do that, I still get the `SystemMouseCursors.text` cursor.

```dart
MouseRegion(
  cursor: SystemMouseCursors.click,
  child: SelectionContainer.disabled(
    child: child,
  ),
)
```

**Comment by kar1981** [comment]
Honestly there are many instances where the text in the button needs to be selectable so that users can copy that text but as well having the text clickable, it's basically the behaviour of a standard "html link". I'm building a metadata tool where multiple database column names needs to be selectable as text (dragging from the outside in) for the copy/paste scenario but each "column name" text button should also be clickable to trigger navigation or other functionality.

**Comment by eggzotic** [comment]
I don't think the debate is over having text both selectable and clickable - it's that in such a case, the mouse-pointer should take on the pointy (i.e. `SystemMouseCursors.click`) appearance, rather than the text-cursor thing (`SystemMouseCursors.text`). Selecting text with a pointy-one is still acceptable, but "clicking" (with the intent of it triggering some action) something with the text-cursor is not a familiar pattern...

And, as @davidmigloz mentioned above, the "workaround" using SystemMouseCursors.click does not work - the text in the button still changes the pointer into the text-cursor when the mouse is over it :-(

**Comment by eggzotic** [comment]
I have come up with a workaround for my own projects - demonstrated at https://github.com/eggzotic/web_text_select with the help of the `custom_text` package. The use of a custom `TextMatcher` subclass and the use of the `mousecursor` parameter to `TextDefinition` shows how it "wins" over the surrounding `SelectionArea` - even in the last `ElevatedButton` in the demo. Hope that helps anyone in the short-term - although would really love to see this behaviour builtin to `SelectionArea`...

**Comment by bleroux** [comment]
The _SystemMouseCursors.text_ cursor is set directly by the `Text` widget, see:
https://github.com/flutter/flutter/blob/3476b966524ff313baf3e31d1818cde33d6fa37f/packages/flutter/lib/src/widgets/text.dart#L617-L621

I filed a PR to propose one possible solution to make this cursor configurable, see https://github.com/flutter/flutter/pull/125133.
