### ISSUE TITLE
Engine roller "fails to create a CL" and then creates duplicate PRs/commits

### ISSUE THREAD

**Issue by flar** [flutter/flutter#104572]
We are seeing intermittent failures on the engine rolls with no real logs to look at. The sheriff was sent 2 messages early this morning about failing to create a CL and no pointer to a task log in it. I go and look at the PRs and commits for the engine rolls and find that it created 3 dups of that roll, and eventually it landed all 3 (the first commit has the roll, the other 2 are "0 changes/0 files".

Here are the 3 links to the duplicate PRs the roller created:
1. https://github.com/flutter/flutter/pull/104524
2. https://github.com/flutter/flutter/pull/104525
3. https://github.com/flutter/flutter/pull/104526

And these led to 3 commits:
1. https://github.com/flutter/flutter/commit/ca1767408636dffa288c062c1f3b268d00eac2bb
2. https://github.com/flutter/flutter/commit/e4c7f6e1b0277ff49da48de1d3628e14c9a6e84f
3. https://github.com/flutter/flutter/commit/ac29c11aecb866d2265314e012d8d3e872cb7640

Example of one of the messages sent to the sheriff:
```
The roller failed to create a CL with:
Failed doing repos.get: GET https://api.github.com/repos/flutter/flutter/commits/776c23716650034f5d75c14da2d9bb1d06c4f8ec/check-runs: 500 []

The AutoRoll server is located here: https://autoroll.skia.org/r/flutter-engine-flutter-autoroll
```

**Comment by zanderso** [comment]
cc @rmistry

**Comment by flar** [comment]
I guess there are 2 questions here:

1. Why did those gets fail? Is this intermittent network issues or something else?
2. Why were the PRs created and tested and merged in duplicates as a result?

**Comment by jmagman** [comment]
More duplicates rolls seen in packages:
https://github.com/flutter/packages/pull/2064
https://github.com/flutter/packages/pull/2065

**Comment by flar** [comment]
I only got 4 of these messages today, all for the engine roller. The emails for the packages must have gone to someone else.

**Comment by zanderso** [comment]
From @rmistry over chat:
> Chromium CQ has a check that fails when there are no changes with ToT (eg: https://ci.chromium.org/raw/build/logs.chromium.org/skia/5b108a539f798211/+/annotations). Might be useful to make a check like that for Flutter as well.

**Comment by zanderso** [comment]
Is this still happening? Should we bump the priority?

**Comment by rmistry** [comment]
> Is this still happening? Should we bump the priority?

If that question was for me- I am not sure, but I have not seen any recent errors.
I am also not sure how to handle this on the roller side because if the Github API returns 500 then the roller assumes that a PR was not uploaded

My recommendation is to add a new check in flutter that makes sure that a no-change patch is not submitted (see this [comment](https://github.com/flutter/flutter/issues/104572#issuecomment-1137232150)).

**Comment by zanderso** [comment]
@rmistry Sorry about that. The question was for @flar as the Engine sheriff this week. If this is still happening frequently, we'd increase the priority of the issue on the Flutter infra ticket queue.

**Comment by flar** [comment]
I've seen 4 Skia->Engine failures to create a CL over the past day and just recently another Engine->Flutter failure. It's still happening on various rollers.

**Comment by flar** [comment]
2 of those were from this morning.

**Comment by flar** [comment]
> > Is this still happening? Should we bump the priority?
> 
> If that question was for me- I am not sure, but I have not seen any recent errors. I am also not sure how to handle this on the roller side because if the Github API returns 500 then the roller assumes that a PR was not uploaded
> 
> My recommendation is to add a new check in flutter that makes sure that a no-change patch is not submitted (see this [comment](https://github.com/flutter/flutter/issues/104572#issuecomment-1137232150)).

This won't help.

The multiple PRs are simultaneous which means all 3 of them have "changes wrt ToT". They then spend an hour or two running tests on the exact same change. It's only when they finish their tests (usually close to each other in time) and we start marking them to be merged. Even still, at that point each of them thinks they have some non-empty changes to commit.

Only when we finally merge the first of those PRs into the tree do the others discover that they are essentially empty now. But, all of the work has already done. If we checked if there were no changes to ToT then all we'd save is the milliseconds to process the "Squash and Merge" which we don't really care about other than theoretically.

We're trying to stop them from being created in the first place, or to abort them when they are "same non-empty changes as another PR", not when they are "no-changes". The "no-changes" is too late in the game to really save any processing time.

**Comment by rmistry** [comment]
> I've seen 4 Skia->Engine failures to create a CL over the past day and just recently another Engine->Flutter failure. It's still happening on various rollers.

Looks like the CL failed to create errors are still happening. More github API flakes:
`E0526 18:28:19.425756      15 autoroller.go:344] Failed to run autoroll: Failed state transition sequence: Failed to transition from "idle" to "active": Failed to get pull request for 104737: Failed doing pullrequests.get: GET https://api.github.com/repos/flutter/flutter/pulls/104737: 500  []. At autoroller.go:792 autoroller.go:336 util.go:391 cleanup.go:57 asm_amd64.s:1571`

But out of curiousity are the duplicate PRs/commits still happening?

**Comment by flar** [comment]
Given the small amount of "content" in these roller PRs, how hard would it be to query if there is an existing PR that matches the intended content.

Actually, if there is any outstanding PR then we should probably wait for that to close anyway, even if our new PR is using a different target commit hash.

Basically instead of waiting to create a new PR until "the one that we remember creating" finishes, it should be until either "the one we recorded creating" or "one that is in the open PR list even if we don't remember creating it"...?

**Comment by rmistry** [comment]
> Given the small amount of "content" in these roller PRs, how hard would it be to query if there is an existing PR that matches the intended content.
> 
> Actually, if there is any outstanding PR then we should probably wait for that to close anyway, even if our new PR is using a different target commit hash.
> 
> Basically instead of waiting to create a new PR until "the one that we remember creating" finishes, it should be until either "the one we recorded creating" or "one that is in the open PR list even if we don't remember creating it"...?

Unfortunately, adding something like that to the roller framework is difficult with the current design.
I think the best solution is to add exponential retries for calls to Github API. Especially if these occasional server errors from Github are going to start being the norm.

**Comment by rmistry** [comment]
I have not seen Github API related `The roller failed to create a CL with`  messages in the engine->flutter roller in the last 5 days. Added exponential backoff has seemed to help.
Did a new push to all flutter Github rollers this morning.

We can probably mark this as fixed and reopen if the problem happens again.
