### ISSUE TITLE
[Flutter 3.0 Android] Crash signal 6 (SIGABRT), code -1 (SI_QUEUE)

### ISSUE THREAD

**Issue by chartreux** [flutter/flutter#104599]
### Issue
After changing from Flutter 2.x to 3.0, I received multiple inquiries from users of the app that it would crash.
When I asked the user in detail, it crashed when I returned to the app after selecting an image from the gallery.
Image_picker is used to get the image.

### Steps to Reproduce
Unfortunately, I couldn't reproduce it on my smartphone.

**Expected results**: The app should not crash

**Actual results**: App is getting crashed
When I investigated the log, it seems that it is occurring on a specific smartphone of Android 11 (SDK 30).
Example) Vivo vivo 1906, Coolpad 1904, Infinix HOT 10 Play, Motorola moto ...

I downgraded the version of Flutter and asked users to try it, but it didn't seem to occur in version 2.10.5.

<details>
<summary>Log</summary>
Google Play Console

```
backtrace:
  #00  pc 000000000008cd50  /apex/com.android.runtime/lib64/bionic/libc.so (abort+164)
  #00  pc 0000000000532740  /apex/com.android.art/lib64/libart.so (art::Runtime::Abort(char const*)+2340)
  #00  pc 000000000001394c  /system/lib64/libbase.so (android::base::SetAborter(std::__1::function<void (char const*)>&&)::$_3::__invoke(char const*)+76)
  #00  pc 0000000000006d10  /system/lib64/liblog.so (__android_log_assert+336)
  #00  pc 0000000000219704  /system/lib64/libhwui.so (android::uirenderer::skiapipeline::SkiaOpenGLPipeline::getFrame()+52)
  #00  pc 0000000000222070  /system/lib64/libhwui.so (android::uirenderer::renderthread::CanvasContext::draw()+404)
  #00  pc 0000000000224490  /system/lib64/libhwui.so (_ZNSt3__110__function6__funcIZN7android10uirenderer12renderthread13DrawFrameTask11postAndWaitEvE3$_0NS_9allocatorIS6_EEFvvEEclEv$c303f2d2360db58ed70a2d0ac7ed911b+524)
  #00  pc 0000000000212c4c  /system/lib64/libhwui.so (android::uirenderer::WorkQueue::process()+208)
  #00  pc 0000000000234b24  /system/lib64/libhwui.so (android::uirenderer::renderthread::RenderThread::threadLoop()+88)
  #00  pc 0000000000015540  /system/lib64/libutils.so (android::Thread::_threadLoop(void*)+320)
  #00  pc 0000000000014db4  /system/lib64/libutils.so (thread_data_t::trampoline(thread_data_t const*)+408)
  #00  pc 00000000000f4510  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+64)
  #00  pc 000000000008ef34  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64)
```

flutter doctor
```
[✓] Flutter (Channel stable, 3.0.1, on macOS 12.3.1 21E258 darwin-x64, locale ja-JP)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] IntelliJ IDEA Community Edition (version 2021.1)
[✓] VS Code (version 1.66.2)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

• No issues found!
```

</details>

<details>
<summary>image_picker</summary>

```
    final picker = ImagePicker();
    final pickedFile = await picker.pickImage(source: ImageSource.gallery);
    if (pickedFile == null) return null;
```
</details>

**Comment by Tom3652** [comment]
Hi @chartreux  i have made the same issue #104514.

**Comment by angelbuzon** [comment]
+1 here.  Just after upgrade Flutter to 3.01

*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
pid: 0, tid: 0 >>> com.Adanel.QC <<<

backtrace:
  #00  pc 0000000000062b60  /apex/com.android.runtime/lib/bionic/libc.so (abort+172)
  #00  pc 00000000003fee8d  /apex/com.android.art/lib/libart.so (art::Runtime::Abort(char const*)+1768)
  #00  pc 000000000000d97f  /system/lib/libbase.so (android::base::SetAborter(std::__1::function<void (char const*)>&&)::$_3::__invoke(char const*)+46)
  #00  pc 00000000000052eb  /system/lib/liblog.so (__android_log_assert+174)
  #00  pc 0000000000145f0b  /system/lib/libhwui.so (android::uirenderer::skiapipeline::SkiaOpenGLPipeline::getFrame()+26)
  #00  pc 000000000014c767  /system/lib/libhwui.so (android::uirenderer::renderthread::CanvasContext::draw()+246)
  #00  pc 000000000014e327  /system/lib/libhwui.so (_ZNSt3__110__function6__funcIZN7android10uirenderer12renderthread13DrawFrameTask11postAndWaitEvE3$_0NS_9allocatorIS6_EEFvvEEclEv$c303f2d2360db58ed70a2d0ac7ed911b+474)
  #00  pc 000000000014111f  /system/lib/libhwui.so (android::uirenderer::WorkQueue::process()+162)
  #00  pc 0000000000158221  /system/lib/libhwui.so (android::uirenderer::renderthread::RenderThread::threadLoop()+72)
  #00  pc 000000000000ee95  /system/lib/libutils.so (android::Thread::_threadLoop(void*)+168)
  #00  pc 000000000000e9dd  /system/lib/libutils.so (thread_data_t::trampoline(thread_data_t const*)+256)
  #00  pc 00000000000aacf3  /apex/com.android.runtime/lib/bionic/libc.so (__pthread_start(void*)+40)
  #00  pc 0000000000064063  /apex/com.android.runtime/lib/bionic/libc.so (__start_thread+30)
