### ISSUE TITLE
[Windows] Make Flutter development without Developer Mode

### ISSUE THREAD

**Issue by gdf8gdn8** [flutter/flutter#104529]
## Use case
I want to start flutter development on Windows without enabling "Developer Mode".
This is a security risk and companies IT will not support or allow this. 

## Proposal
Make it possible to run flutter without enabling Developer mode.

**Comment by timsneath** [comment]
To the best of our knowledge, this requirement was added in error. We're reverting it now. https://github.com/flutter/website/pull/7185
