### ISSUE TITLE
[impeller] OpenGL ES linker failures must dump program info log.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#104585]
Right now, the only error returned to the caller is a generic "link failed" message. The program info log (obtained via `glProgramInfoLog`) must be obtained as well.

**Comment by chinmaygarde** [comment]
@bdero I used this to figure out why the Impeller program wasn't linking and now I have nightmares :(
<img width="1440" alt="Screen Shot 2022-05-25 at 12 17 48 AM" src="https://user-images.githubusercontent.com/44085/170204451-86c3348c-eada-4e42-8a51-56319d3520f1.png">

**Comment by bdero** [comment]
Haha, love it! At a glance, the surface albedo/shadow contribution and noise sampling all look correct. Just the cubemap contribution seems to be broken. Amusingly, the sampled color appears to be largely tied to the underlying fragment block as opposed to the sample direction. Pretty sure I forget something silly when adding the cubemap support blind.
