### ISSUE TITLE
Tree red on "Mac tool_cross_arch_tests" even though test passed

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#104518]
The build dashboard reports the tree is red on "Mac tool_cross_arch_tests". When I click on the build log, I get a "resource not found" error https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20tool_host_cross_arch_tests/856/overview

However, from the milo dashboard, I can see two builds ran successfully for the tip of tree commit: https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20tool_host_cross_arch_tests/504/overview

Note, the build number is different; the dashboard seems to be waiting for a non-existent (too big) build number.

**Comment by keyonghan** [comment]
This sounds https://github.com/flutter/flutter/issues/102998.
Manually updated the task entry to green the tree.  Use the above bug to track.
