### ISSUE TITLE
`SelectionArea` does not show a magnifying glass when selecting text

### ISSUE THREAD

**Issue by nilsreichardt** [flutter/flutter#104555]
When I select text on my Android, Android shows a magnifying glass when selecting text. Flutter does't do it.

https://user-images.githubusercontent.com/24459435/170141105-11719308-51fa-4c91-aa2d-5977852ec803.MOV

I would expect the behavior for the `SelectionArea` in my Flutter App.

I used Pixel 4a with Android 12.

iOS has a similar feature:

https://user-images.githubusercontent.com/24459435/170143559-172acb80-1aae-44d5-b4e6-0fe70a37eb43.MP4

<details>
<summary>My app</summary>

```dart
// Copyright 2014 The Flutter Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This example shows how to make a screen selectable..

import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      // You need to add the "SelectionArea" to make the text selectable.
      home: SelectionArea(
        child: Scaffold(
          body: Padding(
            padding: const EdgeInsets.all(16),
            child: Center(
              child: Column(
                mainAxisSize: MainAxisSize.min,
                children: <Widget>[
                  Text(
                    'Fast',
                    style: Theme.of(context).textTheme.titleLarge,
                  ),
                  const Text(
                    'Flutter code compiles to ARM or Intel machine code as well as JavaScript, for fast performance on any device.',
                  ),
                  ElevatedButton(
                    onPressed: () {},
                    child: const Text('Try it in DartPad'),
                  )
                ],
              ),
            ),
          ),
        ),
      ),
    );
  }
}
```

</details>

cc: @chunhtai 

Extracted this issue from https://github.com/flutter/flutter/issues/104551#issuecomment-1136489191.

**Comment by nilsreichardt** [comment]
Shouldn't get this also the `platform-ios` label?

**Comment by nilsreichardt** [comment]
When I'm seeing this correct is https://github.com/flutter/flutter/issues/17617 only for `TextField`.

**Comment by justinmc** [comment]
CC @antholeole who will be working on this feature.

So we have 3 issues for the magnifying glass, which I think is ok:

This one for SelectionArea.
https://github.com/flutter/flutter/issues/9507 for text fields on iOS.
https://github.com/flutter/flutter/issues/17617 for text fields on Android.
