### ISSUE TITLE
App restarting when choosing gallery

### ISSUE THREAD

**Issue by georges-ph** [flutter/flutter#104538]
I have a profile screen where the user can click a button to change the profile image by picking one from the gallery using the image_picker package. When the button is pressed, the picker opens and the file manager shows up. If I choose something that's outside that file manager like the gallery app of google drive or photos... and select an image, the app stops running and starts again. But nothing happens when I choose an image from that file manager. It works normally.

## Steps to Reproduce

1. Add the code sample below to any button and click it. The picker shows up
2. Choose Gallery on the left pane
3. Select an image

**Expected results:** the selected image should be shown if logic is handled. Otherwise the app shouldn't restart.

**Actual results:** the app restarts and VS Code shows `Lost connection to device.`
Precisely the connection is lost when the Gallery option is selected and the Gallery opens.

Btw why isn't `ImageSource.gallery` opening gallery directly?

<details>
<summary>Code sample</summary>

```dart
final image = await ImagePicker().pickImage(source: ImageSource.gallery);
if (image == null) return;
final tempImage = File(image.path);
```

</details>

<details>
  <summary>Logs</summary>

```
D/ZrHung.AppEyeUiProbe(17087): Current Activity:false
D/ZrHung.AppEyeUiProbe(17087): not watching, wait.
W/libEGL  (17087): EGLNativeWindowType 0x6f2bd69010 disconnect failed
I/SurfaceView(17087): delay destroy surface control
W/libEGL  (17087): EGLNativeWindowType 0x6f2c4f0010 disconnect failed
I/SurfaceView(17087): need destroy surface control
D/ViewRootImpl[MainActivity](17087): surface should not be released
E/        (17087): [ZeroHung]zrhung_get_config: Get config failed for wp[0x0008]
Lost connection to device.
Exited (sigterm)
```

```yaml
image_picker: ^0.8.5+3
```

```
[√] Flutter (Channel stable, 3.0.0, on Microsoft Windows [Version 10.0.19043.1645], locale en-US)
    • Flutter version 3.0.0 at C:\Users\Geo\AppData\Local\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ee4e09cce0 (2 weeks ago), 2022-05-09 16:45:18 -0700
    • Engine revision d1b9a6938a
    • Dart version 2.17.0
    • DevTools version 2.12.2

Checking Android licenses is taking an unexpectedly long time...[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at C:\Users\Geo\AppData\Local\Android\sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] IntelliJ IDEA Ultimate Edition (version 2021.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2021.3.1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code (version 1.67.2)
    • VS Code at C:\Users\Geo\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.40.0

[√] Connected device (4 available)
    • INE LX1 (mobile)  • GVV7N18A12000260 • android-arm64  • Android 9 (API 28)
    • Windows (desktop) • windows          • windows-x64    • Microsoft Windows [Version 10.0.19043.1645]
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 101.0.4951.67
    • Edge (web)        • edge             • web-javascript • Microsoft Edge 100.0.1185.44

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

</details>

**Comment by huycozy** [comment]
Hi @georges-ph,
Thanks for filing the issue. I attempted to run [example](https://github.com/flutter/plugins/tree/main/packages/image_picker/image_picker/example) on my Samsung phone (Tab A7 Lite, Android 11) but it worked fine. 

<details>
<summary>Demo</summary>

https://user-images.githubusercontent.com/104349824/170204638-3f782898-2def-4e21-9345-de7ccd9b682a.mp4

</details>

I guess this issue only affects some specific devices. There are similar issues here: #104168 that occurred when picking multiple images from gallery, and a longstanding issue: #66322

> Btw why isn't ImageSource.gallery opening gallery directly?

Duplicated of: #75020

Please follow up on it for further updates. I'm closing this issue as above explanation.
If you disagree about this, please drop a comment and I will reopen it.
