### ISSUE TITLE
On iOS when switching between apps only half the Flutter app is shown

### ISSUE THREAD

**Issue by vlidholt** [flutter/flutter#10460]
## Steps to Reproduce

Double tap the home button to switch between running apps on iOS. Only half of the flutter app is shown. See screenshot:

![img_0670](https://cloud.githubusercontent.com/assets/1539812/26742204/0e33eb9c-47dd-11e7-9a8d-4c55ef45c2a4.PNG)

## Flutter Doctor
```
[✓] Flutter (on Mac OS X 10.12.4 16E195, locale en-US, channel master)
    • Flutter at /Users/vik/Projects/flutter
    • Framework revision 7397bb9071 (2 days ago), 2017-05-31 12:43:18 -0700
    • Engine revision 75c74dc463
    • Tools Dart version 1.24.0-dev.3.0

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.2)
    • Android SDK at /Users/vik/Library/Android/sdk
    • Platform android-25, build-tools 25.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.3.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3.2, Build version 8E2002
    • ios-deploy 1.9.1
    • CocoaPods version 1.2.0

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Gradle version 3.2
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2016.3.4)
    • Dart plugin version 163.13137
    • Flutter plugin version 0.1.11.1

[✓] Connected devices
    • iPhone SE • B19052F4-91FF-48C7-85B4-26C1D2D1A148 • ios • iOS 10.3 (simulator)
```

**Comment by eseidelGoogle** [comment]
Also interesting that there is a shadow below the bottom bar.  I suspect we're doing unnecessary work to draw that.

**Comment by vlidholt** [comment]
I may be responsible for that shadow :P

**Comment by eseidelGoogle** [comment]
@cbracken is the right person to know.  Unclear if this is a regression.

**Comment by cbracken** [comment]
Do you have more specific repro instructions? The height of the gap at the bottom looks suspiciously like the keyboard region height, but I'm unable to repro on my end either with keyboard open (I see the keyboard in the keyboard frame) or closed (behaves as expected).

Looks like you're using gBoard? I'll give it a go with gBoard as well and see if that changes things.

**Comment by vlidholt** [comment]
I haven't seen this lately, even with the exact same build. Before it was reproducible every single time. Will update this issue if I can find out what the trigger is.

**Comment by Hixie** [comment]
Please do reopen the bug if you see this again. We can't repro.
