### ISSUE TITLE
Instructions for generating ffi bindings incorrect in ffi plugin template

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#104681]
## Seen behavior
Following the instructions in the `foo_generated_bindings.dart` ("Regenerate bindings with `dart run ffigen --config ffigen.yaml`.") causes the following error: 
```
Resolving dependencies... 
Because signposts requires the Flutter SDK, version solving failed.

Flutter users should run `flutter pub get` instead of `dart pub get`.
```

## Expected behavior
I expect the documentation in the template to tell how to regenerate the bindings correctly.

## steps to reproduce
1) `flutter create -t plugin_ffi --platforms ios signposts`
1) `cd signposts`
1) `dart run ffigen --config ffigen.yaml`

cc @stuartmorgan

**Comment by gaaclarke** [comment]
Running it through flutter also doesn't work out of the box:
```
$ flutter pub run ffigen --config ffigen.yaml
Running in Directory: '/Users/aaclarke/dev/signposts'
[SEVERE] : Couldn't find dynamic library in default locations.
[SEVERE] : Please supply one or more path/to/llvm in ffigen's config under the key 'llvm-path'.
Unhandled exception:
Exception: Couldn't find dynamic library in default locations.
#0      findDylibAtDefaultLocations (package:ffigen/src/config_provider/spec_utils.dart:330:3)
#1      Config._getSpecs.<anonymous closure> (package:ffigen/src/config_provider/config.dart:203:29)
#2      Config._extract (package:ffigen/src/config_provider/config.dart:189:50)
#3      new Config.fromYaml (package:ffigen/src/config_provider/config.dart:139:17)
#4      getConfigFromCustomYaml (package:ffigen/src/executables/ffigen.dart:120:17)
#5      getConfig (package:ffigen/src/executables/ffigen.dart:69:14)
#6      main (package:ffigen/src/executables/ffigen.dart:47:14)
#7      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:32)
#8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
pub finished with exit code 255
```

What is `ffigen's config`?

**Comment by gaaclarke** [comment]
The fix for running on macOS was to add the following line to ffigen.yaml: `llvm-path: [/Library/Developer/CommandLineTools/usr/]`

**Comment by dcharkes** [comment]
@gaaclarke we can replace `dart run` with `flutter pub run` in the template. I'll make a PR for that.

I've added the path to the default paths. Do you prefer updating the template to use ffigen 5.0.1 and minimum Flutter version 3.0.1? Or do you prefer adding the path to the config, and keeping the current Flutter and ffigen versions?

**Comment by gaaclarke** [comment]
> @gaaclarke we can replace `dart run` with `flutter pub run` in the template. I'll make a PR for that.

sounds good!

> I've added the path to the default paths. Do you prefer updating the template to use ffigen 5.0.1 and minimum Flutter version 3.0.1? Or do you prefer adding the path to the config, and keeping the current Flutter and ffigen versions?

Well since the template ships with flutter it isn't a big deal requiring 3.0.1, since they are guaranteed to have it.  There's probably some other advancements you've made too that you want.  Probably better just to upgrade it.
