### ISSUE TITLE
Consider running Clang format over Java sources in the engine.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#10465]
Currently, the Java source files in the engine are not passed over a formatter. Apparently, Clang format can handle these files just fine. We should adopt a style and run a formatting pass over all files.

**Comment by chinmaygarde** [comment]
cc @jason-simmons

**Comment by eseidelGoogle** [comment]
Presumably Google has a java styleguide and clang format rule? :)
https://google.github.io/styleguide/javaguide.html
https://github.com/google/google-java-format

**Comment by iapicca** [comment]
Hi @chinmaygarde is this issue still meant to be open?

**Comment by chinmaygarde** [comment]
Yes

**Comment by jonahwilliams** [comment]
We format java now with google3-java-format
