### ISSUE TITLE
Layout times differ between DevTools and Instruments

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#104656]
## Description
The timeline events for `LAYOUT` differ from the time spent in `PipelineOwner.flushLayout`.  In the case of the default flutter project, for the first frame, the timeline event says LAYOUT takes 78.9ms, but when running the same app through Instruments, `PipelineOwner.flushLayout` is reported to be 13ms.   The LAYOUT event is [generated inside of `PipelineOwner.flushLayout`](https://github.com/flutter/flutter/blob/2e7cea6dfed6dedaae5a2f378a0f9dee91e9578f/packages/flutter/lib/src/rendering/object.dart#L960:L960) so they should be equivalent.  I suspect this may be a difference between cpu time and clock time?  When the difference is so dramatic it seems like that distinction should be visible in DevTools somehow.  It also seems to be a problem that the cpu time and the clock time are so dramatically different, that indicates the UI thread is being preempted a lot at startup.

**LAYOUT:**
<img width="849" alt="Screen Shot 2022-05-25 at 2 16 02 PM" src="https://user-images.githubusercontent.com/30870216/170368851-f137ae7c-741c-4f6e-aeff-a3e94b2ddafb.png">

**Instruments:**
<img width="812" alt="Screen Shot 2022-05-25 at 2 18 24 PM" src="https://user-images.githubusercontent.com/30870216/170368997-a844d4cf-5df5-498b-b689-e0c250b5ffa2.png">

## Steps to reproduce
1) `flutter create counter`
1) `cd counter`
1) `flutter run --profile`
1) connect to DevTools and look at the LAYOUT event
1) `open ios/Runner.xcworkspace`
1) 'Product -> Profile`
1) Use the CPU profiler in Instruments
1) Run the app
1) Search in Instruments for the flushLayout symbol.

cc @kenzieschmoll for DevTools visibility cc @dnfield for performance consideration

**Comment by dnfield** [comment]
Can you share the JSON timeline file?

If you open that file in `chrome://tracing` does it give you any insight about CPU time vs wall time?

If you trace this using systrace are we just getting descheduled and devtools is showing wall time whereas profiling is showing CPU time?

**Comment by jonahwilliams** [comment]
does devtools turn on additional layout tracing flags that slow down the application?

**Comment by gaaclarke** [comment]
> Can you share the JSON timeline file?

Remind me how to do that, please.

**Comment by dnfield** [comment]
If you open the "old" observatory page under timeline it'll be there - or if you click `export data` in devtools

<img width="303" alt="image" src="https://user-images.githubusercontent.com/8620741/170378537-cae1bc0f-408f-4478-bdc4-e56fb0f82e0d.png">

**Comment by kenzieschmoll** [comment]
> does devtools turn on additional layout tracing flags that slow down the application?

We don't turn anything on by default - a user would have to explicitly enable Track Layouts.

Here are the things we do when initializing the Performance page
- set the profilePeriod flag to '250' (default is 1000, I'm pretty sure). 
- set the Dart, Embedder, and GC vm timeline flags
- set the 'ext.dart.io.httpEnableTimelineLogging' extension value to true

See 
https://github.com/flutter/devtools/blob/0e66703555909eaf4246a225ab44ae2001f84a1e/packages/devtools_app/lib/src/screens/performance/performance_controller.dart#L191-L198.

One way you could verify that DevTools is not enabling anything that could be causing the slowdown is to open the DevTools performance page first connected to your app, and then open the Instruments profiler. That way, any setup that devtools has initiated will have already been completed by the time you record a profile in instruments.

**Comment by gaaclarke** [comment]
I checked out startup with the system trace to see if there is something weird with the threading.  Here is the first 100ms of the ui thread (BUILD happens at around 594ms):
<img width="1759" alt="Screen Shot 2022-05-25 at 3 36 30 PM" src="https://user-images.githubusercontent.com/30870216/170380910-d99372d0-a723-47d5-842d-b11455c5ccca.png">

My conclusions from that are that we aren't getting preempted.  It seems like the ui thread is running as much as it wants.

**Comment by gaaclarke** [comment]
> Can you share the JSON timeline file?

Here you go: [dart_devtools_2022_5_25-1653518478558000.json.zip](https://github.com/flutter/flutter/files/8774968/dart_devtools_2022_5_25-1653518478558000.json.zip)

**Comment by gaaclarke** [comment]
>  does devtools turn on additional layout tracing flags that slow down the application?

I don't think it's a slowdown from DevTools because by the time I open DevTools the event already happened, so it should essentially be run the same way as when I launch it in the profiler.

**Comment by gaaclarke** [comment]
I think this is the event in the json file:
```json
{"name":"LAYOUT","cat":"Dart","tid":42755,"pid":49434,"ts":3421444921381,"tts":17836,"ph":"B","args":{"isolateId":"isolates/3608599239366331","isolateGroupId":"isolateGroups/4729915749442431256"}}
```

It was reported as 78.4 ms, but I'm not sure how that is calculated.  `ts` seems to be time the event started in microseconds, i guess since the device rebooted?  Since 3421444921381 µs ago was april 15th.

**Comment by kenzieschmoll** [comment]
> @kenzieschmoll can we surface this in devtools as well?

Yes, we'd like to, but this is not a feature our trace viewer supports. I'm trying to push for embedding the Perfetto UI in DevTools, in which case we'll get this and many other nice features for free.

**Comment by Hixie** [comment]
We have Perfetto now so this should be resolved right? Closing but feel free to reopen if I misunderstood.
