### ISSUE TITLE
Cross Compiling Linux Apps

### ISSUE THREAD

**Issue by jwinarske** [flutter/flutter#104679]
CMake cross-compiling for Linux Apps is not currently supported.  It's an easy change.

CMake supports the idea of a toolchain file passed via the CMake variable [CMAKE_TOOLCHAIN_FILE](https://cmake.org/cmake/help/latest/variable/CMAKE_TOOLCHAIN_FILE.html).
This file contains all the toolchain specific settings for project to properly cross compile.  

My proposal is a minor change in `build_linux.dart`.  Add checking of an environmental variable named `FLUTTER_PLUGIN_CMAKE_TOOLCHAIN_FILE`, if set pass it to _runCmake.  It would be passed something like `-DCMAKE_TOOLCHAIN_FILE=flutter_plugin_toolchain_file`.  This approach would enable cross compiling plugin for any toolchain.

One additional variable would be used to pass externally built `libflutter_linux_gtk.so`.  Using the same pattern only using name`FLUTTER_PLUGIN_LIBS`.

A minor change to CMake template file would be to add ${FLUTTER_PLUGIN_LIBS} to target library list.

With this proposed change one could cross compile a Linux Plugin with any toolchain using this pattern:
```
export FLUTTER_PLUGIN_CMAKE_TOOLCHAIN_FILE=/my/path/to/special_toolchain.cmake
export FLUTTER_PLUGIN_LIBS="/my/external/engine/build/libflutter_linux_gtk.so;/another/lib/if/needed/libfwdprogress.so"
flutter build linux -vv
```

If `FLUTTER_PLUGIN_CMAKE_TOOLCHAIN_FILE` was unset, then it would behave as it does today.

This approach can be applied to any plugin built with CMake.

If this sounds reasonable I'll put together a PR for `build_linux.dart`.

Some CMake toolchain examples:
https://github.com/ckormanyos/real-time-cpp/blob/master/ref_app/cmake/gcc-toolchain.cmake
https://github.com/Bill-Gray/PDCursesMod/blob/master/cmake/watcom_open_os2v2_toolchain.cmake
https://github.com/jwinarske/clang_toolchain/blob/master/cmake/clang.toolchain.cmake.in

Yocto/OE dynamically generates a CMake toolchain file.

@stuartmorgan

**Comment by stuartmorgan** [comment]
I'm not clear on what is being requested here; this is being described as being about plugins but `flutter` doesn't have a mode where it compiles plugins specifically. All build are of apps, and plugin build are built as part of that app build.

Given that, how is this different from https://github.com/flutter/flutter/issues/74929?

**Comment by jwinarske** [comment]
It's different in that:
* The interface for the toolchain is agnostic
* It enables tuning the native code build for optimal perf
* It's a simple solution

**Comment by jwinarske** [comment]
Also changed text to refer to Apps instead of plugins, as plugins/FFI are implicit with an app build.

**Comment by stuartmorgan** [comment]
> * The interface for the toolchain is agnostic

It's not clear to me what the use case for this is.

> * It enables tuning the native code build for optimal perf

I'm not sure what this means; build flags can already be changed.

> * It's a simple solution

It adds a second, completely different way of finding some of the dependencies, an well as a second way of doing cross-compilation that's completely different from the current design proposals for cross compilation. Having to support multiple ways of doing the same thing forever isn't necessarily simpler. And it's not at all clear to me how the Dart portion of this build would work since you don't seem to have any way of changing `gen_snapshot` here, or of controlling the flags to the call back into the Flutter tool portion of the build in general.

Given that there are a number of significant questions about the goals and the implementation details, the place to start here would be a full design document.

**Comment by jwinarske** [comment]
>> *It enables tuning the native code build for optimal perf

> I'm not sure what this means; build flags can already be changed.

The preferred pattern with CMake is to factor out toolchain specifics into the actual toolchain file.  Compiler flags specific to the platform and compiler/linker get implemented in the toolchain file.  It helps to create portable solutions.

In IOT and Automotive there are many unique SoCs and platforms, unlike the desktop world.  The desktop world is largely around generic builds that run on any hardware.  On lower end hardware you want to enable all the hardware features you can to get the best performance out of the hardware as possible.  Compiler tuning is an important area for lower end hardware.

In the case of a closed system that is under the control of team, the right way would be to install a single `libflutter_linux_gtk.so` and install with a package config file.  Then one just needs to set the toolchain file.  In the case where different versioned apps may exist on the same system (desktop), you need an explicit path to the cross compiled engine artifacts.  I package these bits in meta-flutter as the "engine sdk".  The "engine sdk" represents the required dependencies to create AOT and App.

I may have left out minor implementation details, but those details would clearly show up in the PR.

**Comment by stuartmorgan** [comment]
> In IOT and Automotive there are many unique SoCs and platforms, unlike the desktop world. The desktop world is largely around generic builds that run on any hardware.

But you are proposing changes to the desktop build.

> I may have left out minor implementation details, but those details would clearly show up in the PR.

They should be discussed in a design document, along with goals, tradeoffs, alternatives considered, etc. of the entire proposal before reaching the PR stage. (Also, where critical tooling comes from and how target details are tracked through the build are not minor details of cross compilation in the Flutter build.)

**Comment by jwinarske** [comment]
Of the panacea of platforms variations, **_desktop_** is just one.

> They should be discussed in a design document, along with goals, tradeoffs, alternatives considered, etc. of the entire proposal before reaching the PR stage. (Also, where critical tooling comes from and how target details are tracked through the build are not minor details of cross compilation in the Flutter build.)

Fair enough I will create a design doc.

**Comment by stuartmorgan** [comment]
> Of the panacea of platforms variations, **_desktop_** is just one.

Sorry, I'm really not following the argument here. I understand that desktop is only one variant, but as I said above it is the variant whose build process and build file template you are proposing changing. And when I asked for details about your comment about tuning build performance, you said "In IOT and Automotive there are many unique SoCs and platforms, unlike the desktop world." I don't understand how needs specific to **non-desktop** use cases are relevant to a proposal to change Flutter's **desktop Linux** build.

I would encourage you to make clear in the design doc what the motivation for this change is as it related specifically to desktop, as that is the configuration your are proposing modifications to.

**Comment by jwinarske** [comment]
Desktop is one of many platforms, where-in lies an implicit goal of grooming the current desktop approach to support many platforms.

Nothing in my proposal changes the existing behavior, it just adds the ability to cross compile.

Happy to setup a call to discuss; it might be more productive.

**Comment by stuartmorgan** [comment]
> Desktop is one of many platforms, where-in lies an implicit goal of grooming the current desktop approach to support many platforms.

Supporting non-desktop environments is not a goal, implicit or otherwise, of our desktop embedding, nor has it ever been.

>

**Comment by stuartmorgan** [comment]
[Accidentally submitted the comment above before I was finished]

I think the right order here is a design document with all the elements I mentioned above to make sure there's clarity about the details of what's being proposed and how it interacts with the existing cross-compilation proposal, and then potentially a live discussion of that proposal. That's the standard process for Flutter proposals.

**Comment by jwinarske** [comment]
Where can I find the design document for https://github.com/flutter/flutter/pull/61221?  The referenced link shows it no longer exists.

**Comment by stuartmorgan** [comment]
Apparently it no longer exists, which is unfortunate: https://github.com/flutter/flutter/issues/74929#issuecomment-1128487946

**Comment by maheshmnj** [comment]
@jwinarske Once you have the design doc ready please leave them here in the comments for further review.

**Comment by jwinarske** [comment]
@maheshmnj Hi Mahesh, yes I've written two already using this template: Vulkan embedder and Dynamic plugins.  I'll look into this next week.
