### ISSUE TITLE
Dialog dismisser is crashing

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#104672]
All tests run of flutter-devicelab-mac-10 are failing because the dialog dismiss test is failing.

The latest to run:

- https://luci-milo.appspot.com/ui/p/flutter/builders/staging/Mac_ios_staging%20large_image_changer_perf_ios/2362/overview
- https://luci-milo.appspot.com/ui/p/flutter/builders/staging/Mac_ios%20large_image_changer_perf_ios/597/overview
- https://luci-milo.appspot.com/ui/p/flutter/builders/staging/Mac_ios%20cubic_bezier_perf_ios_sksl_warmup__timeline_summary/828/overview

It's unclear to me from reading the logs the cause of these failures; however, per Godofredo, the phones do have dialogs showing.

**Comment by christopherfujino** [comment]
The source for this code lives in https://github.com/flutter/cocoon/tree/main/device_doctor/tool/infra-dialog

**Comment by jmagman** [comment]
You shouldn't need to go into the lab to see this, you can vnc to the host and see the screen from QuickTime.

**Comment by christopherfujino** [comment]
So this actually was unrelated to the dialog, but the issue was that the application was signed with a different certificate. Godofredo manually recovered mac-10 (it has since not failed with this error). For posterity, instructions for recovering this are at go/flutter-devicelab-playbook#error-task-failing-to-dismiss-dialogs

**Comment by jmagman** [comment]
It didn't uninstall the bad app when the test ran? Or you mean the dialog dismisser wasn't signed correctly?

**Comment by christopherfujino** [comment]
> It didn't uninstall the bad app when the test ran? Or you mean the dialog dismisser wasn't signed correctly?

The latter. I mostly copy and pasted Godofredo's comments though, I'm not sure when or where the dialog dismisser gets built.

**Comment by godofredoc** [comment]
The problem was that uninstalling the app was not enough. We had to uninstall the app and then reboot the phone for the new version of the dismiss dialogs app to install cleanly.
