### ISSUE TITLE
No visible @interface for 'UIAlertView' declares the selector 'addAction:' or No known class method for selector 'alertControllerWithTitle:message:preferredStyle:'

### ISSUE THREAD

**Issue by kenaitian** [flutter/flutter#104696]
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. ... 
3. ... 

```
Could not build the precompiled application for the device.
Uncategorized (Xcode): Command CompileSwiftSources failed with a nonzero exit code

ARC Semantic Issue (Xcode): No known class method for selector 'alertControllerWithTitle:message:preferredStyle:'
/Users/ken/.pub-cache/hosted/pub.dartlang.org/image_picker_ios-0.8.5+5/ios/Classes/FLTImagePickerPlugin.m:280:8

ARC Semantic Issue (Xcode): No visible @interface for 'UIAlertView' declares the selector 'addAction:'
/Users/ken/.pub-cache/hosted/pub.dartlang.org/image_picker_ios-0.8.5+5/ios/Classes/FLTImagePickerPlugin.m:285:8

Error launching application on iPhone (2).
```

**Expected results:** 
running application like in Android but but bug output above from Android Studio Terminal

**Actual results:** 
Xcode output:
![Screen Shot 2022-05-26 at 4 33 52 AM](https://user-images.githubusercontent.com/63857624/170452284-c003223c-55ed-41ee-81d3-c98caee17b38.png)

<details>
<summary>Code sample</summary>

```
Launching lib/main.dart on iPhone (2) in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: SJAV7HZQZ6
Running Xcode build...
Xcode build done.                                           96.7s
Failed to build iOS app
Error output from Xcode build:
↳
    2022-05-26 04:29:39.816 xcodebuild[6820:61727] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionSentinelHostApplications for extension Xcode.DebuggerFoundation.AppExtensionHosts.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
    2022-05-26 04:29:39.816 xcodebuild[6820:61727] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionPointIdentifierToBundleIdentifier for extension Xcode.DebuggerFoundation.AppExtensionToBundleIdentifierMap.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
    2022-05-26 04:29:41.173 xcodebuild[6820:61733]  DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/DVTiOSFrameworks/DVTiOSFrameworks-20038/DTDeviceKitBase/DTDKRemoteDeviceData.m:373
    Details:  (null) deviceType from 00008030-0004551014E8802E was NULL when -platform called.
    Object:   <DTDKMobileDeviceToken: 0x7fc23cc51000>
    Method:   -platform
    Thread:   <NSThread: 0x60000018de80>{number = 2, name = (null)}
    Please file a bug at https://feedbackassistant.apple.com with this warning message and any useful information you can provide.
    2022-05-26 04:29:41.537 xcodebuild[6820:61734]  DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/DVTiOSFrameworks/DVTiOSFrameworks-20038/DTDeviceKitBase/DTDKRemoteDeviceData.m:373
    Details:  (null) deviceType from 00008030-0004551014E8802E was NULL when -platform called.
    Object:   <DTDKMobileDeviceToken: 0x7fc23cc51000>
    Method:   -platform
    Thread:   <NSThread: 0x600000ed42c0>{number = 9, name = (null)}
    Please file a bug at https://feedbackassistant.apple.com with this warning message and any useful information you can provide.
    2022-05-26 04:29:41.655 xcodebuild[6820:61734]  DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/DVTiOSFrameworks/DVTiOSFrameworks-20038/DTDeviceKitBase/DTDKRemoteDeviceData.m:373
    Details:  (null) deviceType from 00008030-0004551014E8802E was NULL when -platform called.
    Object:   <DTDKMobileDeviceToken: 0x7fc23cc51000>
    Method:   -platform
    Thread:   <NSThread: 0x600000ed42c0>{number = 9, name = (null)}
    Please file a bug at https://feedbackassistant.apple.com with this warning message and any useful information you can provide.
    ** BUILD FAILED **


Xcode's output:
↳
    Writing result bundle at path:
    	/var/folders/6w/jwfs2zcj4nv1wgyzxc9ps5rw0000gn/T/flutter_tools.AkzLbz/flutter_ios_build_temp_diroCiTeq/temporary_xcresult_bundle

    Command CompileSwiftSources failed with a nonzero exit code
    /Users/ken/.pub-cache/hosted/pub.dartlang.org/location-4.4.0/ios/Classes/LocationPlugin.m:176:13: warning: 'UIAlertView' is deprecated: first deprecated in iOS 9.0 - UIAlertView is deprecated. Use UIAlertController with a preferredStyle of UIAlertControllerStyleAlert instead [-Wdeprecated-declarations]
                UIAlertView *alert = [[UIAlertView alloc] initWithTitle:@"Location is Disabled"
                ^
    In module 'UIKit' imported from /Users/ken/StudioProjects/lessimp/ios/Pods/Target Support Files/location/location-prefix.pch:2:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.5.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIAlertView.h:27:12: note: 'UIAlertView' has been explicitly marked deprecated here
    @interface UIAlertView : UIView
               ^
    /Users/ken/.pub-cache/hosted/pub.dartlang.org/location-4.4.0/ios/Classes/LocationPlugin.m:176:48: warning: 'UIAlertView' is deprecated: first deprecated in iOS 9.0 - UIAlertView is deprecated. Use UIAlertController with a preferredStyle of UIAlertControllerStyleAlert instead [-Wdeprecated-declarations]
                UIAlertView *alert = [[UIAlertView alloc] initWithTitle:@"Location is Disabled"
                                                   ^
    In module 'UIKit' imported from /Users/ken/StudioProjects/lessimp/ios/Pods/Target Support Files/location/location-prefix.pch:2:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.5.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIAlertView.h:27:12: note: 'UIAlertView' has been explicitly marked deprecated here
    @interface UIAlertView : UIView
               ^
    2 warnings generated.
    /Users/ken/.pub-cache/hosted/pub.dartlang.org/image_picker_ios-0.8.5+5/ios/Classes/FLTImagePickerPlugin.m:280:5: warning: 'UIAlertView' is deprecated: first deprecated in iOS 9.0 - UIAlertView is deprecated. Use UIAlertController with a preferredStyle of UIAlertControllerStyleAlert instead [-Wdeprecated-declarations]
        UIAlertView *cameraErrorAlert = [UIAlertView
        ^
    In module 'UIKit' imported from /Users/ken/StudioProjects/lessimp/ios/Pods/Target Support Files/image_picker_ios/image_picker_ios-prefix.pch:2:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.5.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIAlertView.h:27:12: note: 'UIAlertView' has been explicitly marked deprecated here
    @interface UIAlertView : UIView
               ^
    /Users/ken/.pub-cache/hosted/pub.dartlang.org/image_picker_ios-0.8.5+5/ios/Classes/FLTImagePickerPlugin.m:281:9: error: no known class method for selector 'alertControllerWithTitle:message:preferredStyle:'
            alertControllerWithTitle:NSLocalizedString(@"Error", @"Alert title when camera unavailable")
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Users/ken/.pub-cache/hosted/pub.dartlang.org/image_picker_ios-0.8.5+5/ios/Classes/FLTImagePickerPlugin.m:281:9: warning: 'UIAlertView' is deprecated: first deprecated in iOS 9.0 - UIAlertView is deprecated. Use UIAlertController with a preferredStyle of UIAlertControllerStyleAlert instead [-Wdeprecated-declarations]
    In module 'UIKit' imported from /Users/ken/StudioProjects/lessimp/ios/Pods/Target Support Files/image_picker_ios/image_picker_ios-prefix.pch:2:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.5.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIAlertView.h:27:12: note: 'UIAlertView' has been explicitly marked deprecated here
    @interface UIAlertView : UIView
               ^
    /Users/ken/.pub-cache/hosted/pub.dartlang.org/image_picker_ios-0.8.5+5/ios/Classes/FLTImagePickerPlugin.m:286:9: error: no visible @interface for 'UIAlertView' declares the selector 'addAction:'
            addAction:[UIAlertAction actionWithTitle:NSLocalizedString(
            ^~~~~~~~~
    /Users/ken/.pub-cache/hosted/pub.dartlang.org/image_picker_ios-0.8.5+5/ios/Classes/FLTImagePickerPlugin.m:291:64: warning: incompatible pointer types sending 'UIAlertView *' to parameter of type 'UIViewController * _Nonnull' [-Wincompatible-pointer-types]
        [[self viewControllerWithWindow:nil] presentViewController:cameraErrorAlert
                                                                   ^~~~~~~~~~~~~~~~
    In module 'UIKit' imported from /Users/ken/StudioProjects/lessimp/ios/Pods/Target Support Files/image_picker_ios/image_picker_ios-prefix.pch:2:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.5.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIViewController.h:223:51: note: passing argument to parameter 'viewControllerToPresent' here
    - (void)presentViewController:(UIViewController *)viewControllerToPresent animated: (BOOL)flag completion:(void (^ __nullable)(void))completion NS_SWIFT_DISABLE_ASYNC API_AVAILABLE(ios(5.0));
                                                      ^
    3 warnings and 2 errors generated.
    note: Using new build system
    note: Planning
    note: Build preparation complete
    note: Building targets in dependency order

    Result bundle written to path:
    	/var/folders/6w/jwfs2zcj4nv1wgyzxc9ps5rw0000gn/T/flutter_tools.AkzLbz/flutter_ios_build_temp_diroCiTeq/temporary_xcresult_bundle


Could not build the precompiled application for the device.
Uncategorized (Xcode): Command CompileSwiftSources failed with a nonzero exit code

ARC Semantic Issue (Xcode): No known class method for selector 'alertControllerWithTitle:message:preferredStyle:'
/Users/ken/.pub-cache/hosted/pub.dartlang.org/image_picker_ios-0.8.5+5/ios/Classes/FLTImagePickerPlugin.m:280:8

ARC Semantic Issue (Xcode): No visible @interface for 'UIAlertView' declares the selector 'addAction:'
/Users/ken/.pub-cache/hosted/pub.dartlang.org/image_picker_ios-0.8.5+5/ios/Classes/FLTImagePickerPlugin.m:285:8

Error launching application on iPhone (2).
```

</details>

<details>
  <summary>Logs</summary>

Log output from Read.md via Github - https://github.com/lessimp/lessimp_logs.git

```
```

ken@Kens-MBP ios % flutter analyze
Analyzing ios...                                                        
No issues found! (ran in 3.3s)
```
```

ken@Kens-MBP ios % flutter doctor -v
[✓] Flutter (Channel stable, 3.0.1, on macOS 12.4 21F79 darwin-x64, locale
    en-US)
    • Flutter version 3.0.1 at /Users/Ken/Development/flutter
    • Upstream repository git@github.com:flutter/flutter.git
    • Framework revision fb57da5f94 (6 days ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version
    32.1.0-rc1)
    • Android SDK at /Users/ken/Library/Android/sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)

[✓] Connected device (4 available)
    • LM Q610 FGN (mobile) • LMQ610TA3526ef8           • android-arm    •
      Android 9 (API 28)
    • iPhone (2) (mobile)  • 00008030-0004551014E8802E • ios            • iOS
      15.4.1 19E258
    • macOS (desktop)      • macos                     • darwin-x64     • macOS
      12.4 21F79 darwin-x64
    • Chrome (web)         • chrome                    • web-javascript • Google
      Chrome 102.0.5005.61

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
```

**Comment by maheshmnj** [comment]
Hi @kenaitian, Thanks for filing the issue. Those errors seem to be coming from the image_picker_ios plugin, Please share the complete output of `flutter run -v` in a text file (as the output will be long) along with a minimal code sample

**Comment by kenaitian** [comment]
> Hi @kenaitian, Thanks for filing the issue. Those errors seem to be coming from the image_picker_ios plugin, Please share the complete output of `flutter run -v` in a text file (as the output will be long) along with a minimal and complete code sample

You’ll see the log output under dropdown “log” in the original post. I wish I could share sample code with you but the code is long and subject to PII.

**Comment by maheshmnj** [comment]
@kenaitian Your logs seem to show the build failed when choosing one of the multiple target device, And you pressed `q` instead of selecting the device, basically the tool seem to have crashed when quitting the build process

> [ +122 ms] Multiple devices found:
[   +4 ms] ro.hardware = cv5a
[        ] ro.build.characteristics = default
[   +9 ms] LM Q610 FGN (mobile) • LMQ610TA3526ef8           • android-arm • Android 9 (API 28)
[   +1 ms] iPhone (2) (mobile)  • 00008030-0004551014E8802E • ios         • iOS 15.4.1 19E258
[   +1 ms] [1]: LM Q610 FGN (LMQ610TA3526ef8)
[        ] [2]: iPhone (2) (00008030-0004551014E8802E)
[   +3 ms] Please choose one (To quit, press "q/Q")
[        ] : 
[  +11 ms] q
[  +36 ms] "flutter run" took 4,363ms.
[  +80 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      DeviceManager._chooseOneOfAvailableDevices (package:flutter_tools/src/device.dart:314:7)

Can you please try running `flutter run -v` and choose a device and then share the complete logs(in a text file as the output will be long)?

**Comment by kenaitian** [comment]
@maheshmnj I've updated the log per flutter run -v and you can access the code here: https://drive.google.com/file/d/1oryxOztgmaFARLpASvW8bDJPT8g09cI3/view?usp=sharing

**Comment by maheshmnj** [comment]
Updated logs [shared by author](https://github.com/lessimp/lessimp_logs)

[logs.txt](https://github.com/flutter/flutter/files/8802704/logs.txt)

**Comment by maheshmnj** [comment]
@kenaitian I looked at the logs, the build seems to be failing because of the pay_ios plugin.

> [+1499 ms] Could not build the precompiled application for the device. [ +37 ms] Swift Compiler Error (Xcode): Editor placeholder in source file /Users/ken/.pub-cache/hosted/pub.dartlang.org/pay_ios-1.0.6/ios/Classes/PaymentExtensions.swift:66:36

> [ ] Swift Compiler Error (Xcode): Editor placeholder in source file /Users/ken/.pub-cache/hosted/pub.dartlang.org/pay_ios-1.0.6/ios/Classes/PaymentExtensions.swift:67:34

I would suggest filing this issue in the respective repository https://github.com/google-pay/flutter-plugin  with a clear description and  proper logs. Closing as this is not an issue with flutter

**Comment by kenaitian** [comment]
> Hi @kenaitian. It seems that Xcode is misinterpreting the existence of placeholders in the code.
> Cleaning the build folder or re-pasting pieces of the code seems to help. Take a look at [this post](https://stackoverflow.com/questions/35167123/swift-error-editor-placeholder-in-source-file) in StackOverflow.



> Hi @kenaitian. It seems that Xcode is misinterpreting the existence of placeholders in the code.
> Cleaning the build folder or re-pasting pieces of the code seems to help. Take a look at [this post](https://stackoverflow.com/questions/35167123/swift-error-editor-placeholder-in-source-file) in StackOverflow.

I did change things around per this blog and that Swift error with placeholders seemed to have gone away but this led to “Flutter/flutter.h” file cannot be found:

https://www.hackingwithswift.com/articles/136/the-complete-guide-to-optionals-in-swift
