### ISSUE TITLE
[Windows] My flutter app is not running on Windows 7

### ISSUE THREAD

**Issue by BerkSpar** [flutter/flutter#104614]
## Steps to Reproduce

Just install the Flutter exe and wait to open.

**Expected results:** 

Open correctly.

**Actual results:** 

Open, show a white window and close.

Is flutter running on Windows 7?

**Comment by BerkSpar** [comment]
> #104644

It's not the same error.

**Comment by stuartmorgan** [comment]
@BerkSpar Please provide a native crash log; without that there's no way for us to know why your application is crashing (especially since you haven't provided a minimal test case, so we have no idea what code is running).

**Comment by imeDevelopers** [comment]
> > #104644
> 
> It's not the same error.

this is the main error, which causes many errors !

**Comment by stuartmorgan** [comment]
@imeDevelopers This issue is about running an application built with Flutter on Windows 7. Your issue is about trying to run the Flutter tooling on Windows 7. They are entirely unrelated.
