### ISSUE TITLE
flutter-devicelab-mac-9 and flutter-devicelab-mac-29 are dead

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#104671]
https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-9 (dead 4 weeks)
https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-29 (dead 3 days)

Two more Mac devicelab machines would help with framework testing capacity.

**Comment by jmagman** [comment]
@yusuf-goog

**Comment by yusuf-goog** [comment]
Dupes
