### ISSUE TITLE
Consider checking default ANDROID_HOME locations

### ISSUE THREAD

**Issue by eseidel** [flutter/flutter#1046]
e.g. on Mac, if you have the default Android Tools installed (Android Studio) your sdk is:
ANDROID_HOME=~/Library/Android/sdk/

http://stackoverflow.com/questions/26739114/android-studio-sdk-location

Even if we don't default to this (which I think we should consider) we could make the flutter tool offer this.

**Comment by Hixie** [comment]
There's a school of thought that suggests we should rather automatically download and install the SDK ourselves, so that we have a known compatible version.

**Comment by abarth** [comment]
We do this now.
