### ISSUE TITLE
Flutter >= 3.0.0 & Windows 7

### ISSUE THREAD

**Issue by imeDevelopers** [flutter/flutter#104644]
## Steps to Reproduce

1. Install flutter on External hard driver
2. Open project in Visual Studio Code (portable on the external driver)
3. Build the project using `flutter build --release --shrink`

## Problems
1. PC Completely Hangs
2. Avast antivirus catches flutter/cache/bin/dart.exe as virus

![Capture](https://user-images.githubusercontent.com/63128477/170354805-f1f5d0d1-2ae6-47c6-b613-4ea625f9bbc4.PNG)

## fixes
1. Shutdown PC
2. Remove External driver
3. Turn PC on
4. Tell Avast to ignore file in the future (which already deleted and i have to re-download flutter and reinstall it)
5. Plug in the Driver (requires format !)
6. Run chkdsk in CMD to fix the driver (without format), look at the logs:

```
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\any>chkdsk F: /f /r
The type of the file system is NTFS.

Chkdsk cannot run because the volume is in use by another
process.  Chkdsk may run if this volume is dismounted first.
ALL OPENED HANDLES TO THIS VOLUME WOULD THEN BE INVALID.
Would you like to force a dismount on this volume? (Y/N) Y
Volume dismounted.  All opened handles to this volume are now invalid.
Volume label is TOSHIBA EXT.

CHKDSK is verifying files (stage 1 of 5)...
  1523968 file records processed.
File verification completed.
  1094 large file records processed.
  0 bad file records processed.
  0 EA records processed.
  14 reparse records processed.
CHKDSK is verifying indexes (stage 2 of 5)...
  2146416 index entries processed.
Index verification completed.
  0 unindexed files scanned.
  0 unindexed files recovered.
CHKDSK is verifying security descriptors (stage 3 of 5)...
  1523968 file SDs/SIDs processed.
Security descriptor verification completed.
  311225 data files processed.
CHKDSK is verifying Usn Journal...
  163717544 USN bytes processed.
Usn Journal verification completed.
CHKDSK is verifying file data (stage 4 of 5)...
10 percent complete. (75651 of 1523952 files processed)
Windows replaced bad clusters in file 75670
of name \Lap\E\Flutters\FLUTTE~1\bin\cache\FLUTTE~1\kernel\LEGACY~4\dart_sdk.js.

10 percent complete. (101542 of 1523952 files processed)

```

## results
fixed the driver, dart.exe removed again, i can't run or build my projects ..

**Comment by stuartmorgan** [comment]
Windows 7 is not a supported host environment for Flutter; see https://docs.flutter.dev/get-started/install/windows#system-requirements

**Comment by imeDevelopers** [comment]
@stuartmorgan 
it works normally on windows 7, however i am upgrading to windows 10 now, if the same issue occurred again i will reopen this case , because this means that flutter has a problem not the OS here ..
