### ISSUE TITLE
Tree was temporarily red because builds could failed to check out the latest framework commit from the mirror

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#104645]
For commit: https://github.com/flutter/flutter/commit/7a2b187c7bc47de1578992a225e64bbc6ad1eb4a there was at least 5 shards that failed, some multiple times, to check out the commit.

For example: https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20web_long_running_tests_5_5/4469/overview

With `fatal: reference is not a tree: 7a2b187c7bc47de1578992a225e64bbc6ad1eb4a`

The first re-run likewise failed to check it out: https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20web_long_running_tests_5_5/4470/overview

And it is only on the second re-run (third overall) that it succeeded: https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20web_long_running_tests_5_5/4471/overview

This third run started at 11:29:27 Wed, May 25 2022 PDT, ~6 minutes after the commit was merged. I suspect the cause was latency in the mirroring.

**Comment by keyonghan** [comment]
@yusuf-goog Do you see any copybara issue around this time?

**Comment by yusuf-goog** [comment]
Nothing seems to have failed for the [flutter mirror job](https://copybara.corp.google.com/list-jobs?piperConfigPath=%2F%2Fdepot%2Fgoogle3%2Fturquoise%2Fflutter%2Finfra%2Fcopybara%2Fcopy.bara.sky&workflowName=flutter_github_to_gob)

**Comment by christopherfujino** [comment]
This is still affecting the tree, marking this a p0

**Comment by yusuf-goog** [comment]
Looks like its a delay about 3-4mins for the mirror.

**Comment by yusuf-goog** [comment]
Real fix is to get builds to trigger off the mirror. But until that can go into place, I can increase the exponential backoff to be longer...

**Comment by yusuf-goog** [comment]
Contacted copybara team for recommendations as well.

**Comment by yusuf-goog** [comment]
The 230sec mirror definitely seems to be an outlier. Most mirrors take about 35-40secs.

**Comment by yusuf-goog** [comment]
Retry backoff increase in https://flutter-review.googlesource.com/c/recipes/+/30625

**Comment by yusuf-goog** [comment]
Fix has landed. Closing this bug since the immediate issue should be mitigated. We will be looking at the longer term fix separately.
