### ISSUE TITLE
[CP] Pass the --enable-skparagraph=false flag if the EnableSkParagraph manifest metadata value is false

### ISSUE THREAD

**Issue by jason-simmons** [flutter/flutter#104641]
### issue_link

https://github.com/flutter/flutter/issues/103846#issuecomment-1136334771

### Commit Hash

1e28cfafa05fd3ea01e3b1d72b6eacf95b537d95

### Target

stable

### Impacted Users

Users affected by regressions in SkParagraph

### Impact Description

Flutter 3 was the first stable release that used SkParagraph to render text.

Some users are affected by issues in SkParagraph that were not present in the old Libtxt text renderer.  For these cases Flutter 3 provides a flag that reenables Libtxt.

This PR makes it easier to use that flag on Android.  With this PR, Android users can opt into Libtxt by setting a metadata attribute in the app manifest and removes the requirement to also pass a flag in the app's FlutterActivity subclass.

### Workaround

Override getFlutterShellArgs in the app's FlutterActivity subclass

### Risk

low

### Test Coverage

yes

### Validation Steps

Run an app like the one in https://github.com/flutter/flutter/issues/103846 that is affected by an SkParagraph regression.

Verify that the text renders as expected when this tag is added to the app's `AndroidManifest.xml`:

```
<meta-data
    android:name="io.flutter.embedding.android.EnableSkParagraph"
    android:value="false" />
```

**Comment by zanderso** [comment]
cherry-pick lgtm

**Comment by itsjustkevin** [comment]
Flutter 3.0.2
