### ISSUE TITLE
Upgrade flutter-devicelab-mac-2 and flutter-devicelab-mac-3 to macOS 12

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#104664]
These were left on macOS 10.15 to support releasing pre-Flutter 3.0, and have not run any jobs since March.  We should now be able to migrate to macOS 12 to increase Mac capacity in the framework.

https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-2
https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-3

@yusuf-goog @CaseyHillers

**Comment by yusuf-goog** [comment]
I'll update the machines

**Comment by CaseyHillers** [comment]
SGTM.

I confirmed that we only need to keep mac vms on Mac 10. The devicelab fleet can be upgraded

**Comment by yusuf-goog** [comment]
these have been upgraded to macos 12
