### ISSUE TITLE
Determine a fix for the zoom page transition performance

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#104680]
The zoom page transition is the default page transition for Android, and used heavily by google customers and customer: money. Unfortunately, the raster performance of this transitions leaves a lot to be desired. Currently, the transition uses a FadeTransition and ScaleTransition. The changing scale factor essentially disables raster caching of child pictures, and apparently causes increases in native memory compared to the baseline transition: https://github.com/flutter/flutter/issues/100972

To solve this, we originally investigated switching from a ScaleTransition using a transform layer, to a ScaleTransition using an ImageFilterLayer with a ImageFilter.matrix. In theory, this should be faster than a transform layer for this case, since the pages aren't animated at all while the transition occurs and this allows a single raster cache entry to be used for the entire page (which can also absorb the opacity from the FadeTransition). While switching did improve memory consumption, it regressed worst frame raster performance by about 1.5x on our gallery benchmark (https://flutter-flutter-perf.skia.org/e/?begin=1650989645&end=1651012744&keys=X809a5f88fb68c1b259242471f65ee081&num_commits=50&request_type=1&xbaroffset=28565) . This is likely due to either the performance of Skia's ImageFilter, or perhaps specific to shader compilation for the first use of this filter.

Interestingly enough though, we accidentally rolled a version of flutter into google3 that used a ImageFilterLayer  🙃 and it significantly improved the performance of a number of customer money benchmarks. A "worst raster frame" benchmark improved from 104.7 ms to 41.75 ms.  A follow-up roll reverted the change and the benchmark regressed again. b/232993351

Its quite difficult to identify performance improvements that are as good as the above change, so I attempted a fix in the engine/raster cache to special case a scale transform matrix filter: https://github.com/flutter/engine/pull/33562 , but that stalled out since it conflicted with another refactor PR.
 
@xster @zanderso can you help determine how we should prioritize this?

**Comment by jonahwilliams** [comment]
(As to why things regressed on the gallery and improved on customer: money, I suspect that is due to the gallery being fairly trivial while money's application is not)

**Comment by flar** [comment]
I think the problem was entirely due to ImageFilter.Matrix not resulting in a simple matrix blit as we had originally thought. Moving away from using ImageFilterLayer to accomplish this  and instead using a layer that is aware that it is just trying to apply a transform and doing it directly in the cache Draw method should provide a lot of improvement. Has that avenue been investigated here?

**Comment by jonahwilliams** [comment]
No, you're right - its not that changing the scale invaldiates it - its that the child animation, intentional or accidental invalidates it.

**Comment by jonahwilliams** [comment]
https://flutter-flutter-perf.skia.org/e/?queries=sub_result%3D90th_percentile_frame_rasterizer_time_millis%26sub_result%3D99th_percentile_frame_rasterizer_time_millis%26sub_result%3Daverage_frame_rasterizer_time_millis%26sub_result%3Dworst_frame_rasterizer_time_millis%26test%3Dold_gallery__transition_perf

![image](https://user-images.githubusercontent.com/8975114/180517708-20ccdd62-3c52-42f0-8ddd-4373fc9047d2.png)

About a 50% reduction in 99%, 90%, and average frame raster time. Worst frame time might have gone down a bit too, though its harder to tell since it is much less stable

**Comment by jonahwilliams** [comment]
A reported performance issue with the old implementation for reference: https://github.com/flutter/flutter/issues/108246
