### ISSUE TITLE
[CP] Fix Flutter doctor crash on Windows caused by bad UTF8 from vswhere.exe

### ISSUE THREAD

**Issue by loic-sharma** [flutter/flutter#104654]
### issue_link

https://github.com/flutter/flutter/issues/102451

### Commit Hash

928bb12, c29a7a2

### Target

stable

### Impacted Users

Windows developers using the latest version of Visual Studio

### Impact Description

Flutter doctor crashes on Windows on the latest version of Visual Studio for certain locales. See: https://github.com/flutter/flutter/issues/102451

### Workaround

Yes, workarounds include

1. Downgrade Visual Studio to an unaffected version
2. Switch your locale to English
3. Patch your Visual Studio installation and replace `vswhere.exe` with a pre-release build: https://github.com/microsoft/vswhere/releases

### Risk

low

### Test Coverage

yes

### Validation Steps

There are three commits to cherry pick:

* https://github.com/flutter/flutter/commit/928bb1229ba050990597a17d1bc5b6cf4cf63e54 from PR https://github.com/flutter/flutter/pull/103947 - This commit made it possible to unit test the fix
* https://github.com/flutter/flutter/commit/52e19ef7ec31652840cc01026358e2a678e73504 from PR https://github.com/flutter/flutter/pull/104133 - This commit refactors vswhere.exe integration
* https://github.com/flutter/flutter/commit/c29a7a2d22e6a685fc06c6685bb4dc72b021d05d from PR https://github.com/flutter/flutter/pull/104284 - This commit ignores replacement characters from vswhere.exe output

All of these commits contain unit tests. Manual testing that can be ensuring `flutter doctor` does not crash on Windows with the latest Visual Studio installation.

**Comment by itsjustkevin** [comment]
@christopherfujino request your review on this CP

**Comment by christopherfujino** [comment]
> @christopherfujino request your review on this CP

LGTM

**Comment by loic-sharma** [comment]
I added one more commit to the cherrypick: https://github.com/flutter/flutter/commit/52e19ef7ec31652840cc01026358e2a678e73504 from https://github.com/flutter/flutter/pull/104133
