### ISSUE TITLE
Upgrade flutter-devicelab-mac-7 to macOS 12

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#104774]
I missed this staging machine when I filed https://github.com/flutter/flutter/issues/104664, it's running macOS 10.15.7.

@yusuf-goog

**Comment by yusuf-goog** [comment]
If someone can confirm when its ok to no longer have mac-10 capacity I can go ahead and upgrade them all.

**Comment by jmagman** [comment]
All the `flutter-devicelab` machines should be on macOS 12 since Flutter 3 has shipped.  We still need some macOS 10.15s for the engine until Mac Web Engine is migrated https://github.com/flutter/flutter/issues/99885.

**Comment by yusuf-goog** [comment]
@CaseyHillers can you please confirm when engine (or anything else) does not need macOS 10 anymore.

**Comment by CaseyHillers** [comment]
I'm not the right owner for this. Mac Web Engine is blocking this on ToT still.

**Comment by yusuf-goog** [comment]
@CaseyHillers  who would be the person to make the call?

**Comment by jmagman** [comment]
@yusuf-goog isn't it you and me? 🙂  go/flutter-mac-builder-upgrade-plan

For flutter/flutter repo, where `flutter-devicelab-mac-*` are being used, all tests are on `Mac-12`
on master:
https://github.com/flutter/flutter/blob/1d47a1b3b2862708ee260a9a1bfc568be85459a7/.ci.yaml#L54
and stable:
https://github.com/flutter/flutter/blob/fb57da5f945d02ef4f98dfd9409a72b7cce74268/.ci.yaml#L86

So any further cherry-picks onto stable will need to be packaged on `Mac-12`.  We shouldn't need any macOS 10.15* machines for flutter/flutter.

However, due to https://github.com/flutter/flutter/issues/99885 we do need a few machines to continue running `Mac-10.15`
https://github.com/flutter/engine/blob/2321e302428ffc0904e5f0050910511438e11de2/.ci.yaml#L325

So these bots should **NOT** be upgraded:
https://chromium-swarm.appspot.com/botlist?f=pool%3Aluci.flutter.prod&f=os%3AMac-10.15&f=cpu%3Ax86&f=device_type%3Anone

build812-m9
build813-m9
build814-m9
build815-m9
build816-m9
build817-m9
build818-m9
build819-m9

But `flutter-devicelab-mac-7` should be upgraded.

**Comment by CaseyHillers** [comment]
I'm referring to https://github.com/flutter/flutter/issues/99885 is the blocker for capacity right now. \cc @eyebrowsoffire

**Comment by godofredoc** [comment]
This is already done: 
![image](https://user-images.githubusercontent.com/54371434/186299012-16af1d81-5fee-49cb-b001-77c871e0f795.png)
