### ISSUE TITLE
IntelliJ Autocomplete broken for StatefulWidget setState() and initState() (and potentially more)

### ISSUE THREAD

**Issue by diegoescudero** [flutter/flutter#104714]
## Steps to Reproduce

1. Load sample project in IntelliJ 2022.1.1 with Flutter 3.0.1 installed
2. Create or use an existing Material StatefulWidget
3. In a code block of the state class, begin typing 'setSta'
4. With Flutter 2.10.5 installed, it will autocomplete to the setState() method, but flutter 3 does not suggest this method for autocomplete, unless you type 'this.setSta'.
5. In a blank area of the the state class, begin typing 'ini' and notice IntelliJ does not suggest and fill out the 'initState()` method. IntelliJ will suggest the method override with flutter 2.10.5, but not 3.0.1.
6. Lastly, when using the IntelliJ overrides menu (ctrl-enter on mac) when choosing to override 'initState()' it does not fill the method with the super.initState() call and instead shows a warning squiggle that the super must be called.
7. Side Note: This autocomplete seems to be working with Flutter 3+ when using VSCode

**Expected results:** 

IntelliJ provides the autocomplete functionality with Flutter 3+ as it did with Flutter 2.10.5

**Actual results:** 

IntelliJ is missing autocomplete functionality with Flutter 3+

<details>
<summary>Code sample</summary>

```
[bug.zip](https://github.com/flutter/flutter/files/8779793/bug.zip)
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
[✓] Flutter (Channel stable, 3.0.1, on macOS 12.4 21F79 darwin-x64, locale en-US)
    • Flutter version 3.0.1 at /Users/diegoescudero/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (7 days ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/diegoescudero/Library/Android/sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 67.1.4
    • Dart plugin version 221.5591.58

[✓] VS Code (version 1.67.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.4 21F79 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 101.0.4951.64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

</details>

<img width="322" alt="Screen Shot 2022-05-26 at 10 30 07 AM" src="https://user-images.githubusercontent.com/3713775/170512826-888abde7-2af3-4e2c-ab66-7f41fb94af19.png">

<img width="359" alt="Screen Shot 2022-05-26 at 10 29 58 AM" src="https://user-images.githubusercontent.com/3713775/170512996-5060fbbd-7c82-49c2-b9f0-2e6b36cf2997.png">
<img width="204" alt="Screen Shot 2022-05-26 at 10 30 22 AM" src="https://user-images.githubusercontent.com/3713775/170513071-e992a862-7d6b-4686-a03f-f8714e395bd0.png">
<img width="289" alt="Screen Shot 2022-05-26 at 10 30 51 AM" src="https://user-images.githubusercontent.com/3713775/170513101-ba40bd1b-a31f-443f-ace5-c5afbb71815d.png">

**Comment by huycozy** [comment]
Hi @diegoescudero, thanks for filing the issue.
This is an issue with Dart analyzer which is being tracked here: https://github.com/dart-lang/sdk/issues/49054 and will be released soon: https://github.com/flutter/flutter-intellij/issues/6176#issuecomment-1134959662

Closing as this is not an issue with flutter.
