### ISSUE TITLE
iOS Flutter 2.8 got crash because of EXC_BAD_ACCESS KERN_INVALID_ADDRESS

### ISSUE THREAD

**Issue by zjrwdl** [flutter/flutter#104795]
Should be fixed in https://github.com/flutter/engine/pull/28495 which should be in 2.10.1

_Originally posted by @chunhtai in https://github.com/flutter/flutter/issues/96850#issuecomment-1020389065_

**Comment by zjrwdl** [comment]
[https://github.com/flutter/engine/pull/28495/files/549d44100ca393cf434831c1d23b84f874ca7955]these commits have been merged in flutter 2.8 
<img width="999" alt="image" src="https://user-images.githubusercontent.com/6874049/170629635-22bee0b5-029f-4118-9506-71c671e00569.png">


but this crash[https://github.com/flutter/flutter/issues/96850] is also exist.
stack belows:

flutter::AccessibilityBridge::GetOrCreateObject(int, std::__1::unordered_map<int, flutter::SemanticsNode, std::__1::hash, std::__1::equal_to, std::__1::allocator<std::__1::pair<int const, flutter::SemanticsNode> > >&) (in Flutter) (accessibility_bridge.mm:303)
flutter::PlatformViewIOS::UpdateSemantics(std::__1::unordered_map<int, flutter::SemanticsNode, std::__1::hash, std::__1::equal_to, std::__1::allocator<std::__1::pair<int const, flutter::SemanticsNode> > >, std::__1::unordered_map<int, flutter::CustomAccessibilityAction, std::__1::hash, std::__1::equal_to, std::__1::allocator<std::__1::pair<int const, flutter::CustomAccessibilityAction> > >) (in Flutter) (platform_view_ios.mm:191)
std::__1::__function::__func<flutter::Shell::OnEngineUpdateSemantics(std::__1::unordered_map<int, flutter::SemanticsNode, std::__1::hash, std::__1::equal_to, std::__1::allocator<std::__1::pair<int const, flutter::SemanticsNode> > >, std::__1::unordered_map<int, flutter::CustomAccessibilityAction, std::__1::hash, std::__1::equal_to, std::__1::allocator<std::__1::pair<int const, flutter::CustomAccessibilityAction> > >)::$_38, std::__1::allocator<flutter::Shell::OnEngineUpdateSemantics(std::__1::unordered_map<int, flutter::SemanticsNode, std::__1::hash, std::__1::equal_to, std::__1::allocator<std::__1::pair<int const, flutter::SemanticsNode> > >, std::__1::unordered_map<int, flutter::CustomAccessibilityAction, std::__1::hash, std::__1::equal_to, std::__1::allocator<std::__1::pair<int const, flutter::CustomAccessibilityAction> > >)::$_38>, void ()>::operator()() (in Flutter) (functional:1720)
fml::MessageLoopImpl::FlushTasks(fml::FlushType) (in Flutter) (message_loop_impl.cc:132)
fml::MessageLoopDarwin::OnTimerFire(__CFRunLoopTimer*, fml::MessageLoopDarwin*) (in Flutter) (message_loop_darwin.mm:81)

**Comment by darshankawar** [comment]
Looking at stacktrace, it looks similar to https://github.com/flutter/flutter/issues/101488, and based on [this](https://github.com/flutter/flutter/issues/101488#issuecomment-1095383409) issue comment, I'll close this as duplicate.
Please follow-up in it for further updates. If you disagree, write in comments and I'll reopen it.

**Comment by zjrwdl** [comment]
> Looking at stacktrace, it looks similar to #101488, and based on [this](https://github.com/flutter/flutter/issues/101488#issuecomment-1095383409) issue comment, I'll close this as duplicate. Please follow-up in it for further updates. If you disagree, write in comments and I'll reopen it.

ok
we will track the case  https://github.com/flutter/flutter/issues/101488,
