### ISSUE TITLE
[Impeller] Implement shadows

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#104715]
See https://github.com/flutter/engine/blob/4a519a80e13d74e1df9a7d5606162cbd2433c351/impeller/display_list/display_list_dispatcher.cc#L735

**Comment by bdero** [comment]
This is blocked on https://bugs.chromium.org/p/skia/issues/detail?id=12125, which makes the `DisplayListCanvasRecorder` unable to record shadows.

**Comment by bdero** [comment]
In-progress implementation of the box shadow case here: https://github.com/flutter/engine/compare/main...bdero:bdero/is-rectangle

Still need to wire it up in the DrawShadows path and test against gallery.
