### ISSUE TITLE
[Impeller] Bring OpenGL backend on par with Metal

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#104712]
This is a tracking issue that we'll close when Impeller's OpenGL backend matches the fidelity of the Metal backend in the apps that we're currently targeting (flutter/gallery, etc.).

Pending Items:
- [x] https://github.com/flutter/flutter/issues/104754
- [x] https://github.com/flutter/flutter/issues/104756

**Comment by chinmaygarde** [comment]
The items in the umbrella bug are done. I am counting this as done. There may be remaining construction issues that we can track separately as we find this.
