### ISSUE TITLE
flutter GenerateMocks is not generated mock class

### ISSUE THREAD

**Issue by tazik561** [flutter/flutter#104700]
I am trying to use `@GenerateMocks` on my test method, This is my dev dependancies:

    dev_dependencies:
      test: any
      flutter_test:
        sdk: flutter
      flutter_driver:
        sdk: flutter
      integration_test:
        sdk: flutter
      flutter_lints: ^1.0.4
      build_runner: ^2.1.4
      mockito: ^5.0.0
      mocktail: ^0.2.0

and I am using like this: 

    @GenerateMocks([CustomerPOAutocompleteState])
    void main() {
      TestWidgetsFlutterBinding.ensureInitialized();

But after running `flutter pub run build_runner build` nothing is generated? 

```
alt@Alis-MacBook-Pro rr-portal-front % flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.5, on macOS 12.3.1 21E258 darwin-arm, locale en-AM)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2022.1)
[✓] VS Code (version 1.67.2)
[✓] Connected device (1 available)
[✓] HTTP Host Availability

• No issues found!
alt@Alis-MacBook-Pro rr-portal-front % 
```

**Comment by maheshmnj** [comment]
Hi @tazik561, Looks this is an issue related to mockito, Please file this issue in its dedicated repository https://github.com/dart-lang/mockito.

Closing as this is not related to flutter sdk
