### ISSUE TITLE
[Impeller] Improve the performance of text rendering

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#104713]
Explore performance improvements so that text rendering in Impeller matches the performance of Skia. The techniques used by Skia are likely to translate well over to Impeller.

**Comment by chinmaygarde** [comment]
All the work items for the meta-bug have been filed and tracked in their own milestone for iOS. Closing this one. For reference, the bugs are listed below. They were discussed during the weekly sync.

* https://github.com/flutter/flutter/issues/112213
* https://github.com/flutter/flutter/issues/116815
* https://github.com/flutter/flutter/issues/116818
* https://github.com/flutter/flutter/issues/116819
* https://github.com/flutter/flutter/issues/116820
