### ISSUE TITLE
First run hurdle: put the mac into developer mode in flutter tool

### ISSUE THREAD

**Issue by xster** [flutter/flutter#10478]
Users running anything in xcode for the first time need to put their mac into developer mode. 

Otherwise, our flutter tool will always give a non-explicit error 
```
flutter run
Launching lib/main.dart on Xiao Yu’s iPhone in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: J23Z8ZF55Q
Running Xcode build...                               14.0s
Could not install build/ios/Release-iphoneos/Runner.app on ff369dfd5f4a80545a431441c1e3066f8cb8d759.
Try launching Xcode and selecting "Product > Run" to fix the problem:
  open ios/Runner.xcworkspace

Error launching application on Xiao Yu’s iPhone.
```

It seems like it's possible to do it in the command line by sudo'ing `DevToolsSecurity -enable`. We should save the user the round trip into Xcode

**Comment by eseidelGoogle** [comment]
Can we check for this in `flutter doctor` or should we just always unconditionally enable?

**Comment by xster** [comment]
We should check with DevToolsSecurity -status
Enabling requires sudo so we should just do it once per user's machine

**Comment by xster** [comment]
@LarkAscending did you run into this as well when you were testing https://github.com/flutter/website/pull/596?

**Comment by LarkAscending** [comment]
Don't believe so...

OTOH it's been almost 3 weeks and eyewitness testimony is notoriously unreliable.
;-)
