### ISSUE TITLE
[Impeller] Implement Picture.toImage().

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#104718]

**Comment by chinmaygarde** [comment]
This needs blit pass support and affects both Metal and OpenGL.

**Comment by jonahwilliams** [comment]
This is about the implementation of Scene/Picture.toImage

https://api.flutter.dev/flutter/dart-ui/Scene/toImage.html
https://api.flutter.dev/flutter/dart-ui/Picture/toImage.html

Which can be used by the framework to create a texture from a Scene/Picture object (Both will flatten down to a display list)

I believe most of the logic for this lives in https://github.com/flutter/engine/blob/main/shell/common/rasterizer.h#L46
