### ISSUE TITLE
[CP] [web] Fix flutter.js for Safari 13

### ISSUE THREAD

**Issue by ditman** [flutter/flutter#104785]
### issue_link

https://github.com/flutter/flutter/issues/104646

### Commit Hash

b7eaad8

### Target

stable

### Impacted Users

Flutter Web app users on Safari 13

### Impact Description

The flutter.js file utilizes JS syntax slightly newer than what Safari 13 is able to understand, so:

* Users on Safari 13 (both on iDevices and MacOSX)
* Visiting a Flutter Web app that uses the new initialization

Will see a blank screen (and a few errors in the console, see above).

The impact should be rather low. According to caniuse.com, Safari 13 on iOS accounts for 0.21% of all users globally, and Safari 13 for MacOS: 0.4%. [Data](https://caniuse.com/usage-table).

### Workaround

Since the flutter.js is statically generated, users may be able to start any new flutter project for web, generate the `flutter.js` file there, and bring it to their "broken" projects before uploading. It's cumbersome (flutter.js gets re-generated after every flutter clean) but doable.

### Risk

low

### Test Coverage

no

### Validation Steps

Having an iOS Simulator running iOS 13.X, deploy any flutter web app with the new index.html (that uses flutter.js), and it should work. Currently it doesn't.

Sanity check:

* Gallery (broken): https://gallery.flutter.dev (the "F" from the loader never finishes loading, errors in the JS console)
* Example (fixed): https://dit-bootstrap-tests.web.app (the counter app starts normally, no errors on the JS console)

**Comment by ditman** [comment]
> ### Test Coverage
> 
> no

Unfortunately, I couldn't find any reliable way of installing Safari 13 desktop on a computer to run automated tests on this (or manual tests, for that matter).

With iOS this could be tested maybe by automating web tests running on iphone simulators, but it seems that flutter/engine is phasing out those tests due to flakiness.

There are some alternatives (discussed in the PR of the change), [here](https://github.com/flutter/flutter/pull/104761#issuecomment-1139180473), but any of those go way beyond the scope of any hotfix.

**Comment by itsjustkevin** [comment]
@yjbanov could you give this cp a look?

**Comment by ditman** [comment]
(@itsjustkevin thanks for the super-fast response! @yjbanov is OOO until Tuesday, I'll ping him then!)

**Comment by itsjustkevin** [comment]
@ditman thank you for the heads up!

**Comment by ditman** [comment]
This landed here:

https://github.com/flutter/flutter/commit/4115b80986135e51e232eb2c3fabdfb141009e4a

But isn't available on stable yet.

**Comment by itsjustkevin** [comment]
Flutter 3.0.2

**Comment by ditman** [comment]
Amazing! Thanks @itsjustkevin!
