### ISSUE TITLE
[Impeller] Make PlatformViews support the generation of DisplayLists when they split the tree into layers

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#104723]
Currently PlatformViews will use SkPictureRecorder objects to record multiple layers of the layer tree that are split by the embedded platform views. We end up with multiple recordings, one for each part of the tree that appears above, below, or between the views.

Unfortunately, Impeller cannot interpret SkPicture objects so the PlatformViews will need to record the intervening layers in DisplayList objects using a DisplayListBuilder in order for impeller to be able to render them.

**Comment by flar** [comment]
Duplicates https://github.com/flutter/flutter/issues/104025
