### ISSUE TITLE
Can I build a production app with impeller?

### ISSUE THREAD

**Issue by mark8044** [flutter/flutter#104735]
I've been using impeller on my test devices with the `--enable-impeller` flag, and it seems to be working very well.  No complaints.  I want to use it on my production app and see how it performs out there in the real world.

Is it possible to build the app for distrubtion with impeller?   `flutter build apk --enable-impeller` ?  or does simply adding it to the `Info.plist` and `AndroidManifest.xml` put it into use for a production app?

Thanks!
@Hixie

**Comment by jonahwilliams** [comment]
@zanderso

**Comment by zanderso** [comment]
Overall, Impeller does not yet implement all of Flutter, and it lacks the testing coverage that we would need before calling it production ready. A partial catalog of known issues is [here](https://github.com/flutter/flutter/projects/229). So, while it is technically possible to enable Impeller in a release-mode app, I don't recommend it. Thanks for trying it out, though! If you're interested, I'd ask that you pound on your app a little harder to see what rendering and performance issues you can shake out.

However, to answer your second question, adding the entries described [here](https://github.com/flutter/engine/tree/main/impeller#try-impeller-in-flutter) to your `Info.plist` and/or `AndroidManifest.xml` would be sufficient.

**Comment by zanderso** [comment]
Since I don't think there's any actionable follow-up from this issue, I'm going to go ahead and close this, but please feel free to ask questions or discuss further on Discord.

**Comment by mark8044** [comment]
@zanderso Thanks for the answers, I've been playing with it and I like it alot so far.  

For the most part my problems were with initial startup jank which seems to be totally gone.  But I'm an n=1 and I cant tell if the improvements are in my head.  So I want to float the app out there and just see what happens.  Worst case scenario is I release an update with it disabled again.

Just to summarize, it sounds like adding https://github.com/flutter/engine/tree/main/impeller#try-impeller-in-flutter will put Impeller into production

Thank you!

**Comment by mark8044** [comment]
> Since I don't think there's any actionable follow-up from this issue, I'm going to go ahead and close this, but please feel free to ask questions or discuss further on Discord.

Hi,  as a follow-up I pushed my iOS app out to TestFlight with the info.plist edited, and the app is super crashy, with many of my graphic elements not rendering.  You are correct, this is not production ready :)

But it begs the question, when I was running it with the `--enable-impeller` flag, it seems I was not actually using Impeller

**Comment by zanderso** [comment]
Do you see the same crashes locally when setting the flag in the `Info.plist` file? You can also help us by letting us know the version of Flutter and the crashes that you're seeing (in a new issue). I also filed https://github.com/flutter/flutter/issues/104746 to make it easier to see whether Impeller is running.

**Comment by mark8044** [comment]
> Do you see the same crashes locally when setting the flag in the `Info.plist` file? You can also help us by letting us know the version of Flutter and the crashes that you're seeing (in a new issue). I also filed #104746 to make it easier to see whether Impeller is running.

Yup, the crashes only seem to happen with the Info.plist file change

#104746 would be awesome

In the meantime, I filed https://github.com/flutter/flutter/issues/104743 I'm not sure how informative it is, but its all I have to work with
