### ISSUE TITLE
dio post multiplepart file request

### ISSUE THREAD

**Issue by abdelghanimeliani** [flutter/flutter#104741]
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by stuartmorgan** [comment]
Feature requests for third -party packages need to be filled against the package, not the Flutter project.

**Comment by abdelghanimeliani** [comment]
@stuartmorgan i think this is related to the flutter project beceause i faced the same problem even with http package
