### ISSUE TITLE
Standardize issue priority across Flutter & Dart

### ISSUE THREAD

**Issue by nuritzi** [flutter/flutter#104728]
## WHAT PROBLEM IS THIS SOLVING?
As Dart & Flutter contributors work on bugs that cross issue databases, having different prioritization semantics yields confusion and things getting dropped.

As we move towards more automation, having separate issue prioritization schemes means that unique automation code has to be written for Flutter & Dart. Standardizing will help us make automation more efficient.

### BACKGROUND
Dart and Flutter are two separate open source projects, yet they work very closely together. Since Flutter is built on Dart and most of Dart’s users are Flutter developers, many processes are being standardized across the two projects in order for them to work better together. 

Issue priority is one of the things that will allow more cross-collaboration between Flutter & Dart developers. 

## NEXT STEPS
The current proposals to evaluate are in [flutter.dev/go/issue-priority-standards](http://flutter.dev/go/issue-priority-standards) (For Google employees: [go/issue-priority-standards](http://go/issue-priority-standards)). 

This issue is meant to be a place where we discuss options and come to a decision about which path to follow.

**Comment by Hixie** [comment]
done as part of [flutter.dev/go/triage-2023-rfc](https://flutter.dev/go/triage-2023-rfc)
