### ISSUE TITLE
[local_auth] Flutter package

### ISSUE THREAD

**Issue by desmondlee95700** [flutter/flutter#104792]
Hi all the newest package of local_auth Flutter package only include BiometricType.strong or BiometricType.weak.
Is there anyway to detect BiometricType.Face and BiometricType.Fingerpint ? 
Both BiometricType.Face and BiometricType.Fingerpint are not accessible in the new package

**Comment by huycozy** [comment]
Hi @desmondlee95700,

> BREAKING CHANGE: Enum BiometricType has been expanded with options for strong and weak, and applications should be updated to handle these accordingly.

There is a Breaking Change since [2.0.0](https://pub.dev/packages/local_auth/changelog#200) and it seems it is missing the relevant documents for that change, see https://github.com/flutter/flutter/issues/102164#issuecomment-1119308677

**Comment by stuartmorgan** [comment]
> and it seems it is missing the relevant documents for that change

That comment is outdated; see https://pub.dev/packages/local_auth#enrolled-biometrics (and the section just above that).

> the newest package of local_auth Flutter package only include BiometricType.strong or BiometricType.weak.

This is not accurate; the other types still exist, and are returned on iOS.

> Is there anyway to detect BiometricType.Face and BiometricType.Fingerpint

The package no longer exposes deprecated APIs on Android. You could certainly use platform channels to query the deprecated APIs in your own application if you want to continue using an approach that the platform explicitly discourages, and anyone in the community could release a plugin to do so.

**Comment by desmondlee95700** [comment]
Thanks for all the replies. Let's say android have fingerprint id and face id enabled. How do the biometric.strong detect fingerprint id and face id?

**Comment by stuartmorgan** [comment]
I'm not sure what the question is exactly. If you're asking how Android classifies authentication mechanisms into classes you'd need to consult Android documentation.
