### ISSUE TITLE
Deflake flutter_desktop_darwin_unittests

### ISSUE THREAD

**Issue by cyanglaz** [flutter/flutter#104789]
Some tests in `flutter_desktop_darwin_unittests` uses global states, results them not suitable for running parallelly.

See: https://github.com/flutter/flutter/issues/104748

Using global states for tests are usually not a good idea as it makes tests hard to maintain.
Maybe we can update the how the tests are set up to make them self contained?

**Comment by cbracken** [comment]
Renamed to capture the broader issue of deflaking the macOS desktop tests, and as part of that work, eliminate the use of OCMock.

**Comment by cbracken** [comment]
I'm going to close this since we've made a ton of progress on this and I don't think we're seeing a significant number of flakes on the bots anymore.
