### ISSUE TITLE
libtxt: Switch to rendering text with libtxt

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#10476]
cc @chinmaygarde, @jamesr, @abarth

**Comment by GaryQian** [comment]
Tracker for remaining things to do:
https://github.com/flutter/flutter/issues/11092

**Comment by chinmaygarde** [comment]
This has landed in the engine behind a flag. Will close this issue when it becomes the default.

**Comment by Hixie** [comment]
IT IS DONE

**Comment by abarth** [comment]
![Mission accomplished](http://childr...

**Comment by abarth** [comment]
![MicDrop2](https://flavorwire.files.wordpress.com/2016/05/obama.png?w=1199)
