### ISSUE TITLE
[Impeller] Refactor Contents to separate geometry and color source concerns

### ISSUE THREAD

**Issue by bdero** [flutter/flutter#104757]
Make DrawPath/DrawPaint/DrawVertices work for solid color/texture/gradients.

Update 10/2022: [Design doc](https://docs.google.com/document/d/1t-dzzi04nCdkIReoJp8ZyGNskqIip1TG3WhGEz7Osd8)

**Comment by chinmaygarde** [comment]
@bdero Are you still working on this line of investigation? Perhaps we can move off-of the in-progress section.

**Comment by bdero** [comment]
Yeah feel free to move it. Sorry this turned into a bit of a Project Jabberwocky. I have a half baked solution I've been sitting on for a while and I'll probably start trying to land changes for it next week

**Comment by bdero** [comment]
Design doc: flutter.dev/go/impeller-geometry

**Comment by bdero** [comment]
Linked to a doc with my latest ideas for this in the description.

**Comment by chinmaygarde** [comment]
@bdero I am closing this as done with go/impeller-geometry.
