### ISSUE TITLE
Adding Kotlin as another programming language for flutter 

### ISSUE THREAD

**Issue by josephkabba** [flutter/flutter#104722]
Can Kotlin be added as another programming language for flutter development alongside dart. Like Kotlin compiling to dart code. I don't know something along those lines. Because kotlin is feature rich and code footprint is low making codebase more manageable and easy to work with. Just a suggestion. Thanks

**Comment by iapicca** [comment]
> since Kotlin is a much superior language and much easier language to learn compared to Dart

give that anyone is entitled to have it's opinion, what makes you think that?

**Comment by stuartmorgan** [comment]
Closing as a duplicate of https://github.com/flutter/flutter/issues/18422 (and others).
