### ISSUE TITLE
E/flutter: [ERROR:flutter/fml/platform/android/jni_util.cc(204)] java.lang.IllegalStateException: Platform view hasn't been initialized from the platform view channel.

### ISSUE THREAD

**Issue by kimriri** [flutter/flutter#104797]
We have the exact same problem as this.

It happens unconditionally when using automatic rotation on Android devices.

E/flutter: [ERROR:flutter/fml/platform/android/jni_util.cc(204)] java.lang.IllegalStateException: Platform view hasn't been initialized from the platform view channel.
        at io.flutter.plugin.platform.PlatformViewsController.u(SourceFile:13)
        at io.flutter.plugin.platform.PlatformViewsController.onDisplayPlatformView(SourceFile:2)
        at io.flutter.embedding.engine.FlutterJNI.onDisplayPlatformView(SourceFile:3)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:335)
        at android.os.Looper.loopOnce(Looper.java:186)
        at android.os.Looper.loop(Looper.java:313)
        at android.app.ActivityThread.main(ActivityThread.java:8663)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
2022-05-27 13:55:22.846 21430-21430/? A/flutter: [FATAL:flutter/shell/platform/android/platform_view_android_jni_impl.cc(1469)] Check failed: fml::jni::CheckException(env).

**Comment by kimriri** [comment]
Did you figure it out?

**Comment by maheshmnj** [comment]
Hi @kimriri, Thanks for filing the issue, Could you please the output of `flutter doctor -v` and `flutter run -v` in a text file, along with a [minimal and complete reproducible code](https://stackoverflow.com/help/minimal-reproducible-example) to better address the issue

**Comment by kimriri** [comment]
Hi! 
I'm sorry to leave you with a duplicate question.
I thought you asked him a question because there was someone who had the same problem as me!

Flutter doctor -v 

[✓] Flutter (Channel stable, 3.0.1, on macOS 11.6 20G165 darwin-x64, locale ko-KR)
    • Flutter version 3.0.1 at /Users/user/Flutter/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (10일 전), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/user/Library/Android/sdk
    • Platform android-32, build-tools 32.0.0
    • Java binary at: /Users/user/Desktop/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 12.5.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ✗ Flutter requires Xcode 13 or higher.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] Android Studio (version 2021.2)
    • Android Studio at /Users/user/Desktop/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.67.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • SM G977N (mobile) • R3CM302C73E • android-arm64  • Android 12 (API 31)
    • macOS (desktop)   • macos       • darwin-x64     • macOS 11.6 20G165 darwin-x64
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 102.0.5005.61

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

 flutter run -v

[        ] I/flutter (20759): only implement point type
[ +993 ms] I/flutter (20759): only implement point type
[        ] I/flutter (20759): only implement point type
[        ] I/flutter (20759): only implement point type
[        ] I/flutter (20759): only implement point type
[+1039 ms] E/flutter (20759): [ERROR:flutter/fml/platform/android/jni_util.cc(204)] java.lang.IllegalStateException: Platform view hasn't been initialized from the platform view channel.
[        ] E/flutter (20759):   at io.flutter.plugin.platform.PlatformViewsController.u(SourceFile:13)
[        ] E/flutter (20759):   at io.flutter.plugin.platform.PlatformViewsController.onDisplayPlatformView(SourceFile:2)
[        ] E/flutter (20759):   at io.flutter.embedding.engine.FlutterJNI.onDisplayPlatformView(SourceFile:3)
[        ] E/flutter (20759):   at android.os.MessageQueue.nativePollOnce(Native Method)
[        ] E/flutter (20759):   at android.os.MessageQueue.next(MessageQueue.java:335)
[        ] E/flutter (20759):   at android.os.Looper.loopOnce(Looper.java:186)
[        ] E/flutter (20759):   at android.os.Looper.loop(Looper.java:313)
[        ] E/flutter (20759):   at android.app.ActivityThread.main(ActivityThread.java:8663)
[        ] E/flutter (20759):   at java.lang.reflect.Method.invoke(Native Method)
[        ] E/flutter (20759):   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
[        ] E/flutter (20759):   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
[        ] E/flutter (20759): 
[        ] F/flutter (20759): [FATAL:flutter/shell/platform/android/platform_view_android_jni_impl.cc(1469)] Check failed: fml::jni::CheckException(env). 

Is this information okay?
Thank you !

**Comment by maheshmnj** [comment]
Thanks for the info @kimriri, The logs you shared aren't complete Can you please share the complete output of `flutter run -v` in a text file? Also What target platform is this issue on? It would be great if you can share a [minimal and complete reproducible code](https://stackoverflow.com/help/minimal-reproducible-example) sample

**Comment by ccchp** [comment]
@kimriri I also have this problem. Have you found the reason

**Comment by FlutterSu** [comment]
I have this problem too.

You need to test in the release build. It doesn't crash in the debug build.

I'm trying to rewrite the video player by replacing Texture with SurfaceView for Android.

Everything works, but when I start to quickly change the PlatformViewLink or switch to PIP, the application crashes:

**Log:** 
```
E/flutter (14136): [ERROR:flutter/fml/platform/android/jni_util.cc(204)] java.lang.IllegalStateException: Platform view hasn't been initialized from the platform view channel.
E/flutter (14136): 	at h9.m.I(Unknown Source:100)
E/flutter (14136): 	at h9.m.Q(Unknown Source:3)
E/flutter (14136): 	at io.flutter.embedding.engine.FlutterJNI.onDisplayPlatformView(Unknown Source:19)
E/flutter (14136): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (14136): 	at android.os.MessageQueue.next(MessageQueue.java:337)
E/flutter (14136): 	at android.os.Looper.loopOnce(Looper.java:168)
E/flutter (14136): 	at android.os.Looper.loop(Looper.java:299)
E/flutter (14136): 	at android.app.ActivityThread.main(ActivityThread.java:8103)
E/flutter (14136): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (14136): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
E/flutter (14136): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
```

**Flutter doctor -v**
```
[✓] Flutter (Channel stable, 3.0.3, on macOS 12.2.1 21D62 darwin-x64)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
[✓] Chrome - develop for the web
[!] Android Studio
    ✗ Unable to find bundled Java version.
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.68.1)
[✓] Connected device (3 available)
[✓] HTTP Host Availability
```

**Dart code**
```Dart
return PlatformViewLink(
          viewType: 'my_view_type',
          surfaceFactory: (BuildContext context, PlatformViewController controller) {
            return AndroidViewSurface(
              controller: controller as AndroidViewController,
              gestureRecognizers: const <Factory<OneSequenceGestureRecognizer>>{},
              hitTestBehavior: PlatformViewHitTestBehavior.transparent,
            );
          },
          onCreatePlatformView: (PlatformViewCreationParams params) {
            final ExpensiveAndroidViewController controller = PlatformViewsService.initExpensiveAndroidView(
              id: params.id,
              viewType: params.viewType,
              layoutDirection: TextDirection.ltr,
              creationParams: {'textureId': textureId},
              creationParamsCodec: const StandardMessageCodec(),
            );
            controller
              ..addOnPlatformViewCreatedListener(params.onPlatformViewCreated)
              ..create();

            return controller;
          },
        );
```

**Kotlin code**
```Kotlin
internal class PlayerViewFactory(private val videoPlayers: LongSparseArray<Player>) :
    PlatformViewFactory(StandardMessageCodec.INSTANCE) {
    override fun create(context: Context?, viewId: Int, args: Any?): PlatformView {
        val layout = LinearLayout(context)
        
        val creationParams = args as Map<String?, Any?>?
        val textureId = (creationParams!!["textureId"] as Int).toLong()
        val player = videoPlayers[textureId]

        val surfaceView = player.surfaceView()

        if (surfaceView.parent != null) {
            (surfaceView.parent as ViewGroup).removeView(surfaceView)
        }

        layout.addView(surfaceView)

        return NativeView(layout)
    }
}

internal class NativeView(private val view: View) :
    PlatformView {
    override fun getView(): View {
        return view
    }

    override fun dispose() {
    }
}
```

**You can test code**
```Kotlin
internal class PlayerViewFactory(private val videoPlayers: LongSparseArray<Player>) :
    PlatformViewFactory(StandardMessageCodec.INSTANCE) {
    override fun create(context: Context?, viewId: Int, args: Any?): PlatformView {
        val layout = LinearLayout(context)
        
        val view = View(context)
        view.setBackgroundColor(Color.GREEN)
        layout.addView(view)

        return NativeView(layout)
    }
}

internal class NativeView(private val view: View) :
    PlatformView {
    override fun getView(): View {
        return view
    }

    override fun dispose() {
    }
}
```
