### ISSUE TITLE
A problem occurred configuring project ':webview_flutter_android'.

### ISSUE THREAD

**Issue by Es-Rell** [flutter/flutter#104838]
## Steps to Reproduce

1. Flutter 3.0.1 • channel stable, create a new project and import `webview_flutter ^3.0.4`
2. `flutter run` with Android Simulator (Nexus device 5x API 28 Android 9.0)

**Error:** 

```dart
> Could not resolve all files for configuration ':webview_flutter_android:classpath'.
   > Could not resolve org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.5.31.
     Required by:
         project :webview_flutter_android > com.android.tools.build:gradle:7.2.1
         project :webview_flutter_android > com.android.tools.build:gradle:7.2.1 > com.android.tools:sdk-common:30.2.1
         project :webview_flutter_android > com.android.tools.build:gradle:7.2.1 > com.android.tools:repository:30.2.1
         project :webview_flutter_android > com.android.tools.build:gradle:7.2.1 > com.android.tools.ddms:ddmlib:30.2.1
         project :webview_flutter_android > com.android.tools.build:gradle:7.2.1 > com.android.tools.build:aaptcompiler:7.2.1
         project :webview_flutter_android > com.android.tools.build:gradle:7.2.1 > com.android.tools.analytics-library:shared:30.2.1
         project :webview_flutter_android > com.android.tools.build:gradle:7.2.1 > com.android.tools.lint:lint-model:30.2.1
         project :webview_flutter_android > com.android.tools.build:gradle:7.2.1 > androidx.databinding:databinding-compiler-common:7.2.1
         project :webview_flutter_android > com.android.tools.build:gradle:7.2.1 > com.android.tools.utp:android-test-plugin-host-retention-proto:30.2.1
         project :webview_flutter_android > com.android.tools.build:gradle:7.2.1 > com.android.tools.build:builder:7.2.1
         project :webview_flutter_android > com.android.tools.build:gradle:7.2.1 > com.android.tools.build:builder-model:7.2.1
         project :webview_flutter_android > com.android.tools.build:gradle:7.2.1 > com.android.tools.build:gradle-api:7.2.1
         project :webview_flutter_android > com.android.tools.build:gradle:7.2.1 > com.android.tools:sdk-common:30.2.1 > com.android.tools:common:30.2.1
         project :webview_flutter_android > com.android.tools.build:gradle:7.2.1 > com.android.tools.build:builder:7.2.1 > com.android.tools.analytics-library:tracker:30.2.1
         project :webview_flutter_android > com.android.tools.build:gradle:7.2.1 > com.android.tools.build:builder:7.2.1 > com.android.tools.build:manifest-merger:30.2.1
      > Could not resolve org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.5.31.
         > Could not get resource 'https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-stdlib-jdk8/1.5.31/kotlin-stdlib-jdk8-1.5.31.pom'.
            > Could not GET 'https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-stdlib-jdk8/1.5.31/kotlin-stdlib-jdk8-1.5.31.pom'.
               > The server may not support the client's requested TLS protocol versions: (TLSv1.2, TLSv1.3). You may need to configure the client to allow other protocols to be used. See: https://docs.gradle.org/7.4/userguide/build_environment.html#gradle_system_properties
                  > Remote host terminated the handshake
   > Could not resolve org.apache.httpcomponents:httpmime:4.5.6.
```

But on iOS, everything is all right. 

### My environment:
```dart
[✓] Flutter (Channel stable, 3.0.1, on macOS 12.3.1 21E258 darwin-arm, locale en-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.67.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability


java version "18.0.1.1" 2022-04-22
Java(TM) SE Runtime Environment (build 18.0.1.1+2-6)
Java HotSpot(TM) 64-Bit Server VM (build 18.0.1.1+2-6, mixed mode, sharing)
```

**Comment by huycozy** [comment]
Hi, thanks for filing the issue. 

> Could not resolve org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.5.31.
         > Could not get resource 'https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-stdlib-jdk8/1.5.31/kotlin-stdlib-jdk8-1.5.31.pom'.
            > Could not GET 'https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-stdlib-jdk8/1.5.31/kotlin-stdlib-jdk8-1.5.31.pom'.
               > The server may not support the client's requested TLS protocol versions: (TLSv1.2, TLSv1.3). You may need to configure the client to allow other protocols to be used. See: https://docs.gradle.org/7.4/userguide/build_environment.html#gradle_system_properties
                  > Remote host terminated the handshake

This issue seems related to your network, please ensure you have a working internet connection.
There is a checklist you can use for this:

- [ ] Is the network stable and fast?
- [ ] Do you use any proxy server?
- [ ] Are you using https://flutter.dev/community/china#configuring-flutter-to-use-a-mirror-site?
- [ ] It may be useful for troubleshooting the issue: https://dart.dev/tools/pub/troubleshoot#pub-get-fails-from-behind-a-corporate-firewall

If these solutions are not working for you, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that we can directly copy paste and run to verify this issue.

**Comment by Es-Rell** [comment]
> Hi, thanks for filing the issue.
> 
> > Could not resolve org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.5.31.
> > > Could not get resource 'https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-stdlib-jdk8/1.5.31/kotlin-stdlib-jdk8-1.5.31.pom'.
> > > Could not GET 'https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-stdlib-jdk8/1.5.31/kotlin-stdlib-jdk8-1.5.31.pom'.
> > > The server may not support the client's requested TLS protocol versions: (TLSv1.2, TLSv1.3). You may need to configure the client to allow other protocols to be used. See: https://docs.gradle.org/7.4/userguide/build_environment.html#gradle_system_properties
> > > Remote host terminated the handshake
> 
> This issue seems related to your network, please ensure you have a working internet connection. There is a checklist you can use for this:
> 
> * [ ]  Is the network stable and fast?
> * [ ]  Do you use any proxy server?
> * [ ]  Are you using https://flutter.dev/community/china#configuring-flutter-to-use-a-mirror-site?
> * [ ]  It may be useful for troubleshooting the issue: https://dart.dev/tools/pub/troubleshoot#pub-get-fails-from-behind-a-corporate-firewall
> 
> If these solutions are not working for you, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that we can directly copy paste and run to verify this issue.

Thank You!
It's my Internet
And now I've solved it
