### ISSUE TITLE
Upgrade devicelab ios phone to latest 15.5

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#104862]
Existing DeviceLab iOS phones are with different lower versions spanning across 15.1 to 15.5.  However from .ci.yaml builder config side, targets are tied to only one specific version ([current 15.1](https://github.com/flutter/flutter/blob/master/.ci.yaml#L89)). This caused bot resources not fully used.

This bug tracks the progress to upgrade existing iOS phones to latest 15.5, and should be unblocked when xcode version is bumped up: https://github.com/flutter/flutter/pull/104857.

Actions (ETA week of 05/30):
- [x] Wait @jmagman  to land https://github.com/flutter/flutter/pull/104857
- [x] @yusuf-goog  to reland https://github.com/flutter/flutter/pull/104835 to allow mac/ios tasks to run on any iOS testbed
- [x]  @yusuf-goog to upgrade 11 mac/ios testbeds to iOS 15.5 for bots between mac1 to mac24
- [x] @yusuf-goog to ensure these phones are with auto upgrade off
- [x] @keyonghan to upgrade remainning 13 mac/ios testbeds to iOS 15.5 for bots between mac25 to mac46.
- [x] @keyonghan to ensure all devices are with auto upgrade off
- [x] @keyonghan  to update devicelab_staging_config.star to loose iOS 15.1 to iOS15 + xcode to latest version as well

/cc @godofredoc @jmagman @yusuf-goog

**Comment by keyonghan** [comment]
All mac/ios between mac25 and mac46 are with 15.5, and auto upgrade off.

**Comment by yusuf-goog** [comment]
mac-23 is having an issue, where its failing to get the update.

**Comment by yusuf-goog** [comment]
All devicelab ios devices have been upgraded to 15.5: https://chromium-swarm.appspot.com/botlist?c=id&c=task&c=device_os&c=os&c=status&d=asc&f=device_os%3AiOS-15&k=device_os&s=device_os
