### ISSUE TITLE
[pigeon] pubspec has dependency on flutter

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#104861]
Pigeon doesn't depend on Flutter but it is listed as a dependency in the pubspec.yaml.  This causes 2 problems:
1) On new versions of flutter it causes `run_tests.sh` to fail since it uses `dart` to run tests, but the tests will error out saying you need to run `flutter` instead
1) The pub.dev page says it is "unidentified" since it doesn't list any platforms

Our options are to:
1) Fully embrace the dependency on flutter despite the fact there is no actual runtime dependency on flutter
1) Rip out the dependency on flutter

Ripping it out is technically correct but if we do that it will confuse different ci steps that rely on that dependency to be there.  Maybe it is a good idea to fully embrace the dependency on flutter in order to control access to new flutter features.  In the past we've just always conformed to the platform channel API which is pretty stable so no version check of flutter was necessary.

cc @stuartmorgan

**Comment by stuartmorgan** [comment]
> 2\. The pub.dev page says it is "unidentified" since it doesn't list any platforms

Most Flutter packages don't list platforms. I think pub.dev may just be behind on processing recent updates to packages. It's normal for that to show for a short time after publishing.

> Maybe it is a good idea to fully embrace the dependency on flutter in order to control access to new flutter features. In the past we've just always conformed to the platform channel API which is pretty stable so no version check of flutter was necessary.

The generation-time version dependency is separate from the runtime dependency of the generated code though.

**Comment by stuartmorgan** [comment]
> Ripping it out is technically correct but if we do that it will confuse different ci steps that rely on that dependency to be there.

These CI steps have been improved, and this issue was fixed in https://github.com/flutter/packages/pull/3397
