### ISSUE TITLE
add description to devicelab .manual_quarantine_file

### ISSUE THREAD

**Issue by yusuf-goog** [flutter/flutter#104851]
We can manually quarantine a devicelab bot by add a `.manual_quarantine_file` to the homedir.

It would be nice to be able to specify some text in the file which shows up on the swarming bot webpage, to see why the host was quarantined.

\cc @keyonghan

**Comment by keyonghan** [comment]
https://chrome-internal-review.googlesource.com/c/infradata/config/+/6113870 to support.
http://cl/544718451 to update doc.
