### ISSUE TITLE
[pigeon] Nullable nested type causes crash in ObjC

### ISSUE THREAD

**Issue by dnys1** [flutter/flutter#104871]
Similar to: https://github.com/flutter/flutter/issues/99150

The following pigeon type generates code which can crash iOS.

```dart
class MyType {
  NestedType? nestedType;
}

class NestedType {
  late bool myValue;
}
```

```objc
@implementation MyType
+ (MyType *)fromMap:(NSDictionary *)dict {
  MyType *pigeonResult = [[MyType alloc] init];
  pigeonResult.nestedType = [NestedType fromMap:GetNullableObject(dict, @"nestedType")];
  return pigeonResult;
}
}
@end

@implementation NestedType
+ (NestedType *)fromMap:(NSDictionary *)dict {
  NestedType *pigeonResult = [[NestedType alloc] init];
  pigeonResult.myValue = GetNullableObject(dict, @"myValue");
  NSAssert(pigeonResult.myValue != nil, @"");
  return pigeonResult;
}
@end
```

Calling a host API with `MyType()` (no value for `nestedType`) in Dart will cause the `NSAssert` to fail. I would potentially expect `fromMap` to return `nil` in the case that `dict == nil`, or for `MyType.fromMap` to not try to set `nestedType` if its dict entry is `nil`.

**Comment by darshankawar** [comment]
Thanks for the report. Currently, `NSAssert` checks for `myValue` to be not `nil` , but the pigeon generated code doesn't pass any value for `nestedType`:

`NestedType? nestedType;`
