### ISSUE TITLE
Add blur effect for container background.

### ISSUE THREAD

**Issue by Mhamad-Rzgar** [flutter/flutter#104833]
I believe the flutter framework should include an integrated container with a blur effect property. I know we have a backdrop filter, but it's not efficient or clean code for glassmorphism style apps, which are becoming increasingly popular. I believe it should be integrated rather than achieved through a plugin or package.

**Comment by huycozy** [comment]
Hi @Mhamad-Rzgar,
I agree that this may help the code cleaner. But I'm not sure what's not efficient.
And also, I'm not sure what package/plugin you're using. I can achieve this with the code sample below:

<details>
<summary>Sample code</summary>

```dart
Container(
  decoration: const BoxDecoration(
    image: DecorationImage(
      image: ExactAssetImage('assets/abc.jpeg'),
      fit: BoxFit.cover,
    ),
  ),
  child: BackdropFilter(
    filter: ImageFilter.blur(sigmaX: 10.0, sigmaY: 10.0),
    child: Container(
      decoration: BoxDecoration(color: Colors.white.withOpacity(0.0)),
    ),
  ),
)
```
</details>

This issue can consider as a `new feature` issue. Please try to provide all or some of the information indicated in the [feature request template](https://github.com/flutter/flutter/issues/new?assignees=&labels=&template=3_feature_request.md&title=).
