### ISSUE TITLE
android flutter webview navigationDelegate Don't take effect

### ISSUE THREAD

**Issue by xiaocode337317439** [flutter/flutter#104804]
```dart
WebView(
                        initialUrl: "url",
                        gestureNavigationEnabled: true,
                        navigationDelegate: (NavigationRequest request) {
                        // ios ok
                        // android not ok
                          return NavigationDecision.navigate;
                        },
                      )
```

For SPA single page H5 apps, Android listens for URL changes without calling back, iOS is OK

**Comment by danagbemava-nc** [comment]
Hi @xiaocode337317439, there's an existing issue describing what you're experiencing in https://github.com/flutter/flutter/issues/39441.

Kindly follow up there for updates. 

Closing from here as duplicate. 

Thank you
