### ISSUE TITLE
Update DeviceLab linux/android testbeds to use ubuntu image

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#104864]
To make all Linux bots consistent, this bug tracks updating DeviceLab Linux/Android testbeds to ubuntu from debian, in addition to [VM ones]([go/flutter-vm-ubuntu](http://go/flutter-vm-ubuntu)).

This bug tracks the progress (ETA week of 05/30):

- [x] @yusuf-goog to track/valid/doc update process on one bot
- [x] @yusuf-goog to update 13 Linux/android testbeds in prod pool (from linux1 to linux19)
- [x] @keyonghan to update remaining 13 Linux/android testbeds
  - [x] 6 remaining ones in prod (from linux20 to linux25)
  - [x] 6 testbeds in staging
  - [x] 1 testbed in try

/cc @godofredoc

**Comment by yusuf-goog** [comment]
staging pool devicelab linux bots updated to ubuntu.

**Comment by yusuf-goog** [comment]
Instructions on updating are at: go/flutter-ubuntu-update

**Comment by yusuf-goog** [comment]
linux-1 from the prod pool has been updated. Once runs on it validates, we should continue with the prod pool updates.

@keyonghan can you please update linux-2..12. And I can complete the remaining ones next week.

**Comment by keyonghan** [comment]
linux2-linux12 are all with ubuntu and running.

**Comment by yusuf-goog** [comment]
all devicelab linux bots upgraded to ubuntu.
