### ISSUE TITLE
[webview_flutter] using proxy

### ISSUE THREAD

**Issue by subzero911** [flutter/flutter#104826]
How can I set proxy for a WebView widget?
I don't have any "findProxy" property or direct access to the underlying http client.

**Comment by darshankawar** [comment]
@subzero911 

Please check below links for a possible solution you can try : 
https://stackoverflow.com/a/58972125

And reasonings for closing this issue.

https://github.com/flutter/flutter/issues/34778#issuecomment-570414418

https://github.com/flutter/flutter/issues/32869#issuecomment-813610327

**Comment by subzero911** [comment]
I saw this SO answer.
Global override is not a solution. It affects not only the WebView but the whole app and all HTTP clients. That's not what I want.

**Comment by subzero911** [comment]
Okay, i have read the second comment and see your point now.
