### ISSUE TITLE
Not able to fetch data from php api.have tried with Uri and parse methode

### ISSUE THREAD

**Issue by somfinso** [flutter/flutter#104808]
I had been trying to fetch data from php api in which i had tried using Uri and parse method but i am not able to fecth tried.I tried alll the method which was available in internet but luck havent favored me.This is my code ..correct me if i am wrong .
 Future<List<Data>> getData() async {
    var response = await http.get(Uri.parse("http://10.10.3.89/moea/list.php"),
        headers: {"Access-Control-Allow-Origin": "*"});
 
    //await http.get(Uri.http(Env.URL_PREFIX,"/moea/list.php"),);

    var jsonData = jsonDecode(response.body);
    List<Data> dataList = [];
    for (var u in jsonData) {
      Data data = Data(u["id"], u["name"], u["age"]);
      dataList.add(data);
    }
    print(dataList.length);
    return dataList;
  }

I would grateful if someone could suggest me what could the reason for the following error .

Error: XMLHttpRequest error.
    C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/core_patch.dart 963:28                get current
packages/http/src/browser_client.dart 69:22                                                                                    <fn>
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/zone.dart 1685:54                                              runUnary
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 147:18                                        handleValue
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 766:44                                        handleValueCallback
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 795:13                                        _propagateToListeners
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 557:7                                         [_complete]
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/stream_pipe.dart 61:11                                         _cancelAndValue
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/stream.dart 1530:7                                             <fn>
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 334:14  _checkAndCall
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 339:39  dcall
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/html/dart2js/html_dart2js.dart 37309:58                              <fn>

    at Object.createErrorWithStack (http://localhost:60875/dart_sdk.js:5093:12)
    at Function._throw (http://localhost:60875/dart_sdk.js:20399:18)
    at Function.throwWithStackTrace (http://localhost:60875/dart_sdk.js:20396:18)
    at async._AsyncCallbackEntry.new.callback (http://localhost:60875/dart_sdk.js:40921:18)
    at Object._microtaskLoop (http://localhost:60875/dart_sdk.js:40778:13)
    at _startMicrotaskLoop (http://localhost:60875/dart_sdk.js:40784:13)
    at http://localhost:60875/dart_sdk.js:36261:9

**Comment by darshankawar** [comment]
@somfinso 
This issue probably need to be asked in dedicated repo: https://github.com/dart-lang/sdk/issues

Closing from here.
