### ISSUE TITLE
[go_router] Impossible to specify custom format for debug logs

### ISSUE THREAD

**Issue by s0nerik** [flutter/flutter#104822]
Since go_router writes debug logs using `developer.log` (https://github.com/flutter/packages/blob/main/packages/go_router/lib/src/logging.dart#L37), it's impossible to override the logged message formatting, which may lead to ugly console log messages whenever go_router writes its logs.

For example, we have debug logging set up in a way, that each log message will be prepended with a constant-width section. Enabling the `debugLogDiagnostics` on go_router, though, breaks all our formatting, like here:

<img width="310" alt="зображення" src="https://user-images.githubusercontent.com/5076429/170690535-dd3bf20d-6e24-41a8-a6ca-5f9cef9cc0a1.png">

It would've been great if there was an option to override the format of messages written to the debug console by go_router.

**Comment by darshankawar** [comment]
Thanks for the report. Treating this as a proposal to provide an option to override format of messges.

/cc @chunhtai @johnpryan

**Comment by cedvdb** [comment]
In general I prefer the event emitter pattern instead of directly logging, letting the user choose however he was to print event.

**Comment by chunhtai** [comment]
superseded https://github.com/flutter/flutter/issues/109263
