### ISSUE TITLE
[Impeller] Support inverse winding methods in Path

### ISSUE THREAD

**Issue by bdero** [flutter/flutter#104848]
In the dispatcher, we're able to interpret `SkPathFillType::kWinding` and `SkPathFillType::kEvenOdd`, but don't have a way to interpret `SkPathFillType::kInverseWinding` or `SkPathFillType::kInverseEvenOdd`.

The trouble with these is that they involve expanding a path with a contour that covers the render target, which is not necessarily known by the time it's converted to raw geometry.

**Comment by dnfield** [comment]
Mentioned this in the PR, but Flutter doesn't expose these.

That said, I suppose some other internal engine component could still use them (e.g. SkParagraph)

**Comment by chinmaygarde** [comment]
I am closing this as wont-fix. I couldn't find any internal users of these methods either.
