### ISSUE TITLE
Proposal: add name parameter to ThemeData

### ISSUE THREAD

**Issue by sivaprasadnk** [flutter/flutter#104929]
## Proposal

Adding a name parameter to the ThemeData can help display names of corresponding themes in a theme-switch screen without any extra function or extension codes.

**Comment by darshankawar** [comment]
@sivaprasadnk 
Thanks for the report. Can you provide us an example or code sample wherein the `name` parameter will be useful and would be effective ?

**Comment by sivaprasadnk** [comment]
class ThemeGrid extends StatelessWidget {
  const ThemeGrid({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Consumer<ThemeNotifier>(
      builder: (_, provider, __) {
        return Padding(
          padding: const EdgeInsets.only(left: 0, top: 0),
          child: GridView.builder(
            physics: const NeverScrollableScrollPhysics(),
            shrinkWrap: true,
            itemCount: AppTheme.values.length,
            gridDelegate: const SliverGridDelegateWithFixedCrossAxisCount(
              crossAxisCount: 2,
              mainAxisExtent: 120,
              crossAxisSpacing: 20,
              mainAxisSpacing: 10,
            ),
            itemBuilder: (ctx, index) {
              final ThemeData? theme = appThemeData[AppTheme.values[index]];
              String title = AppTheme.values[index].name.toString().initCap
();
              return GestureDetector(
                onTap: () {
                  provider.setTheme(AppTheme.values[index], index, context);
                },
                child: Stack(
                  children: [
                    Container(
                      height: 120,
                      padding: const EdgeInsets.all(5),
                      decoration: BoxDecoration(
                          color: Colors.blueGrey,
                          borderRadius: BorderRadius.circular(5)),
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        mainAxisSize: MainAxisSize.min,
                        children: [
                          const SizedBox(
                            height: 10,
                          ),
                          Padding(
                            padding: const EdgeInsets.only(left: 8),
                            child: Text(
                              title,
                              style: const TextStyle(
                                color: Colors.black,
                                fontSize: 25,
                                fontFamily: 'Rajdhani',
                              ),
                            ),
                          ),
                          const SizedBox(
                            height: 10,
                          ),
                          Row(
                            children: [
                              const SizedBox(
                                width: 5,
                              ),
                              CircleAvatar(
                                backgroundColor: theme!
.scaffoldBackgroundColor,
                              ),
                              const SizedBox(
                                width: 5,
                              ),
                              CircleAvatar(
                                backgroundColor: theme.primaryColor,
                              ),
                            ],
                          ),
                        ],
                      ),
                    ),
                    if (provider.themeIndex == index)
                      const Positioned.fill(
                        right: 8,
                        top: 8,
                        child: Align(
                          alignment: Alignment.topRight,
                          child: Icon(
                            Icons.check,
                            size: 30,
                            color: Colors.black,
                          ),
                        ),
                      )
                  ],
                ),
              );
            },
          ),
        );
      },
    );
  }
}

**Comment by darshankawar** [comment]
Thanks for the update. Labeling this as a proposal.

Note: Please don't post a comment as a reply because that way we won't be able to properly format the text. Always post as a separate comment.

**Comment by guidezpl** [comment]
Thank you for your suggestion. This should be easily achievable without additions to `ThemeData`, which we tend to avoid given its size. I would look at extended enums or extensions to get exactly the String you want per theme. As such I'm closing this issue.
