### ISSUE TITLE
Flutter Release Build for MacOS doesn't start after a while, but code runs without exceptions in the debugger.

### ISSUE THREAD

**Issue by mikexkllr** [flutter/flutter#104946]
I tried to compile a Flutter app that I wrote for work for MacOS because my work colleagues want to use it on their desktop devices as well. I have a valid Apple developer certificate. The app can be started initially after compiling and runs as desired. However, after about 2 weeks, a message appears that the application can no longer be started. Then it has to be recompiled and rolled out on all devices. Tested it on a MBP 16 from 2019 (intel x86) and on a MBP 14 from 2021 (arm64) running Flutter SDK 3. The code runs without any exceptions or problems in the MacOS debugger and on other plattforms (like windows) aswell. Thanks for help!

<img width="437" alt="Bildschirmfoto 2022-05-30 um 08 27 05" src="https://user-images.githubusercontent.com/95420747/170931621-bcb94a36-ed7f-41dd-9695-3388eaabc1fa.png">

<img width="1290" alt="Bildschirmfoto 2022-05-30 um 08 38 51" src="https://user-images.githubusercontent.com/95420747/170931855-69103cad-0eab-41b0-a55d-87b5362866c1.png">

**Comment by maheshmnj** [comment]
Hi @mikexkllr, Thanks for filing the issue. Could you please paste those crash logs in the comments along with the output of `flutter doctor -v` which shows the details of the environment using which the app was builtt.

**Comment by mikexkllr** [comment]
Here is my doctor's output. Thx!

```
[✓] Flutter (Channel stable, 3.0.0, on macOS 12.4 21F79 darwin-x64, locale de-DE)
    • Flutter version 3.0.0 at /usr/local/Caskroom/flutter/2.5.3/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ee4e09cce0 (vor 3 Wochen), 2022-05-09 16:45:18 -0700
    • Engine revision d1b9a6938a
    • Dart version 2.17.0
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mikekeller/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 63.0.3
    • Dart plugin version 212.5632

[✓] VS Code (version 1.67.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.4 21F79 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 102.0.5005.61
    ! Error: iPhone is not connected. Xcode will continue when iPhone is connected. (code -13)

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

**Comment by maheshmnj** [comment]
Thanks for the logs @mikexkllr, Probably those logs cannot be symbolized, labeling this issue for further insights from the team 

cc: @cbracken
