### ISSUE TITLE
material 3 alert dialog's scrollbar goes out of the container when scrolling to the end

### ISSUE THREAD

**Issue by werainkhatri** [flutter/flutter#104917]
Not sure what's expected, but this seems incorrect.

| Platform | Image |
| --- | --- |
| MacOS | <img width="384" alt="Screenshot 2022-05-29 at 2 23 29 PM" src="https://user-images.githubusercontent.com/44755140/170860166-1f43e85c-d191-4b0a-8bc9-08ea4e07ae81.png"> |
| Web | <img width="497" alt="Screenshot 2022-05-29 at 2 28 46 PM" src="https://user-images.githubusercontent.com/44755140/170860344-ec8f2373-1386-4b28-802f-23bb03a79df2.png"> |

<details>
<summary>sample code</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const M3DialogApp());

class M3DialogApp extends StatelessWidget {
  const M3DialogApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(useMaterial3: true),
      home: Scaffold(
        body: Builder(builder: (context) {
          return Center(
            child: IconButton(
                onPressed: () {
                  showDialog<void>(
                    context: context,
                    builder: (context) => AlertDialog(
                      scrollable: true,
                      icon: const Icon(Icons.phonelink_erase),
                      iconColor: Colors.red,
                      title: const Text('Basic dialog title'),
                      content: const Text(
                          'A dialog is a type of modal window that appears in '
                          'front of app content to provide critical '
                          'front of app content to provide critical '
                          'front of app content to provide critical '
                          'front of app content to provide critical '
                          'front of app content to provide critical '
                          'front of app content to provide critical '
                          'front of app content to provide critical '
                          'front of app content to provide critical '
                          'front of app content to provide critical '
                          'front of app content to provide critical '
                          'front of app content to provide critical '
                          'front of app content to provide critical '
                          'information, or ask for a decision.'),
                      actions: <Widget>[
                        TextButton(
                          style: TextButton.styleFrom(
                            textStyle: Theme.of(context).textTheme.labelLarge,
                          ),
                          child: const Text('Enabled'),
                          onPressed: () {
                            Navigator.of(context).pop();
                          },
                        ),
                        TextButton(
                          style: TextButton.styleFrom(
                            textStyle: Theme.of(context).textTheme.labelLarge,
                          ),
                          child: const Text('Enabled'),
                          onPressed: () {
                            Navigator.of(context).pop();
                          },
                        ),
                      ],
                    ),
                  );
                },
                icon: const Icon(Icons.open_in_browser)),
          );
        }),
      ),
    );
  }
}
```
</details>

**Comment by werainkhatri** [comment]
> You need to set the [AlertDialog.clipBehavior](https://master-api.flutter.dev/flutter/material/AlertDialog/clipBehavior.html).

but shouldn't it start from where the curve ends instead of getting clipped? similar to if you remove actions and try to scroll to the end.

**Comment by TahaTesser** [comment]
> but shouldn't it start from where the curve ends instead of getting clipped? similar to if you remove actions and try to scroll to the end.


Not sure what you mean but regardless of actions and content, clipping is applied to Dialog itself with a shape. 
When clipping has been applied, everything inside the dialog is clipped including the scrollbar. 
This is similar to the dropdown clip https://github.com/flutter/flutter/issues/102914, which I fixed recently

**Comment by TahaTesser** [comment]
> shouldn't the track of the scrollback shrink enough to fit in the dialog correctly instead of being clipped? 

The scrollbar is attached to the list and it takes the height of the dialog. The entire content is scrollable and the dialog has a rounder corner so clipping the content to match the dialog's shape is the current solution.


If the padding is applied outside the content list it could shrink the scrollbar but it could break existing behavior. 
I can see you're adding an icon and the scrollbar is flowing above "content", in such case instead of modifying content list or shrinking the scroll bar (would  be breaking change), it would be better to place the icon out the content list view and make it always visible regardless of the dialog size if it matches material specs
