### ISSUE TITLE
Remove hard destination count requirement for NavigationRail 

### ISSUE THREAD

**Issue by BLumia** [flutter/flutter#104913]
I'm not sure if it's the right place to send this feedback, please let me know if I come to the wrong place.

Currently the NavigationRail material widget requires user provide 2 or more destinations to work. I suggest remove this limitation so NavigationRail can be more generic use cases.

## Use case

Image when developing an app similar to Discord, when user doesn't join any Discord server, the navigation rail on the left side doesn't contain any entry except the "Add server" entry. As suggested by the Material guideline, the Add Server button should be put in the [container](https://m3.material.io/components/navigation-rail/specs) (or the FAB in Material 2). If user joined a server, there will be a server entry / navigation destination available, and more destinations will be there when user adds them.

Other use cases are similar to this one, when we build an app that is designed to let user add entries by themself and the app doesn't provide or only provide one default entry, the NavigationRail should still fit this requirement and developer should be able to use it.

## Proposal

Remove the destinations.length assert or change it to  `>= 0` in the NavigationRail widget:

https://github.com/flutter/flutter/blob/64b08f3c5658b66d7a19b71bea0aa18bc30a3d01/packages/flutter/lib/src/material/navigation_rail.dart#L108

## Additional Information

Navigation Rail in Jetpack Compose doesn't have such limitation.

**Comment by darshankawar** [comment]
@BLumia 
This looks like similar case with https://github.com/flutter/flutter/issues/58367. You may follow-up in that issue and raise or link the PR you created to the original one. Closing from here.
