### ISSUE TITLE
flutter web output does not run on older android devices

### ISSUE THREAD

**Issue by moodstubos** [flutter/flutter#104984]
second try. Please do not close without testing it yourself. 

## Steps to Reproduce

1. flutter channel master
2. flutter create .
3. flutter build web
4. Upload build/ to webserver
5. Start android emulator with older api level. E.g. Android 6.0 Google APIs | x86
6. launch website

**Actual results:**

empty index.html file without web app loaded. 

See example of official gallery app:

![image](https://user-images.githubusercontent.com/5072232/171047073-40cd6de7-1acc-48d9-81a3-ccb78e9b884d.png)

![image](https://user-images.githubusercontent.com/5072232/171047102-acc96a0a-6509-40f9-8ec8-f1ebc4a79f98.png)

### flutter doctor

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.0.1, on Microsoft Windows [Version 10.0.22000.675], locale de-DE)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.5)
[√] Android Studio (version 2021.2)
[√] VS Code (version 1.67.2)
[√] Connected device (5 available)
[√] HTTP Host Availability

• No issues found!

```

tried some older flutter version. This issue seems to have existed for a long time. First working flutter release: 2.0.5

**Comment by maheshmnj** [comment]
Hi @moodstubos,

Please do not file duplicates, Let us continue the discussion in the original issue https://github.com/flutter/flutter/issues/104960
