### ISSUE TITLE
Drawing bug with soft wrapped Text

### ISSUE THREAD

**Issue by markentingh** [flutter/flutter#10496]
When using Row > Container > Text, the text doesn't want to soft wrap, and a red box appears on the right-hand side of the text as it bleeds off the page.

```
new Row(mainAxisAlignment:MainAxisAlignment.center, children:[
    new Container(padding:const EdgeInsets.only(top:50.0, left:30.0, right:30.0),
        child: new Text("You haven't specified any custom inputs for this task", softWrap:true,
            style: new TextStyle(color:widget.theme.fadedText)
        )
    )
])
```

When I use an Align widget instead of a Row widget, everything works as expected.

```
new Align(child:
    new Container(padding:const EdgeInsets.only(top:50.0, left:30.0, right:30.0),
        child: new Text("You haven't specified any custom inputs for this task", softWrap:true,
            style: new TextStyle(color:widget.theme.fadedText)
         )
     )
)
```

**Comment by Hixie** [comment]
Does this answer your question?:
https://docs.flutter.io/flutter/widgets/Row-class.html

**Comment by markentingh** [comment]
absolutely, thank you for the insight.

**Comment by Hixie** [comment]
@markentingh Is there anywhere we could have put that documentation that you would have run into before filing the bug? I'm trying to figure out how we could have helped you better here.

**Comment by markentingh** [comment]
It's kind of my own fault since I assumed a Row widget would be able to work like an HTML div. I wasn't reading the documentation completely. Instead I was using intellisense in Visual Studio Code in this case.

**Comment by Hixie** [comment]
Interesting. I'll close this bug since I don't know that there's anything we can do about this right now but I'll keep thinking about what we could do to make it more obvious! Let me know if you have any ideas.
Cheers!
