### ISSUE TITLE
We should have a simple LRU cache

### ISSUE THREAD

**Issue by abarth** [flutter/flutter#1049]
I wanted to have a memory cache of network responses.  I used a map with the URL as the key and a Future to the parsed response as the value.  That's fine, but it grows unbounded.  We should provide a collection that manages the cache using LRU.  We also need this internally for the image cache.

**Comment by eseidel** [comment]
Quiver has one:
https://www.dartdocs.org/documentation/quiver/0.21.4/quiver.collection/LruMap-class.html

Supposedly there is one built deep in the bowels of Dart too?
https://github.com/dart-lang/sdk/issues/18445

**Comment by abarth** [comment]
https://github.com/flutter/flutter/pull/1118 claims we should the one from quiver.

**Comment by abarth** [comment]
#1118 landed, so we have this now.
