### ISSUE TITLE
[tool_crash] RPCError

### ISSUE THREAD

**Issue by maple52046** [flutter/flutter#104932]
## Command
```
flutter run
```

## Steps to Reproduce

I just run the flutter app in debug mode on my iphone (iOS 14.8), and the app crashed and terminated without any operation.

## Logs
RPCError
```
#0      new _OutstandingRequest (package:vm_service/src/vm_service.dart:1734:45)
#1      VmService._call (package:vm_service/src/vm_service.dart:2245:21)
#2      VmService.callServiceExtension (package:vm_service/src/vm_service.dart:2216:14)
#3      FlutterVmService.createDevFS (package:flutter_tools/src/vmservice.dart:918:20)
#4      DevFS.create (package:flutter_tools/src/devfs.dart:508:61)
#5      FlutterDevice.setupDevFS (package:flutter_tools/src/resident_runner.dart:361:18)
#6      HotRunner._initDevFS (package:flutter_tools/src/run_hot.dart:447:22)
#7      HotRunner.attach (package:flutter_tools/src/run_hot.dart:263:40)
<asynchronous suspension>
#8      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:692:26)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1183:27)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#11     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
<asynchronous suspension>
#15     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 3.0.1, on macOS 11.3.1 20E241 darwin-x64, locale zh-Hant-TW)
    • Flutter version 3.0.1 at /Users/maple/opt/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (10 days ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/maple/Library/Android/sdk
    • Platform android-30, build-tools 31.0.0
    • ANDROID_HOME = /Users/maple/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.0

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /Applications/Chromium.app/Contents/MacOS/Chromium

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.67.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Proxy Configuration
    • HTTP_PROXY is set
    • NO_PROXY is localhost,127.0.0.1,10.99.0.0/24,127.94.0.1,::1
    • NO_PROXY contains localhost
    • NO_PROXY contains 127.0.0.1
    • NO_PROXY contains ::1
    • NO_PROXY contains 127.94.0.1

[✓] Connected device (3 available)
    • iPhone (mobile) • 00008020-000E610C263A002E • ios            • iOS 14.8 18H17
    • macOS (desktop) • macos                     • darwin-x64     • macOS 11.3.1 20E241 darwin-x64
    • Chrome (web)    • chrome                    • web-javascript • Chromium 97.0.4669.0

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 77d935af4db863f6abd0b9c31c7e6df2a13de57b
### Plugins
better_player-0.0.82
camera-0.9.7+1
camera_web-0.2.1+6
device_info_plus-3.2.3
device_info_plus_linux-2.1.1
device_info_plus_macos-2.2.3
device_info_plus_web-2.1.0
device_info_plus_windows-2.1.1
flutter_inappwebview-5.4.3+7
flutter_keyboard_visibility-5.2.0
flutter_keyboard_visibility_web-2.0.0
flutter_native_splash-2.2.0+1
flutter_openim_sdk-2.0.9
flutter_plugin_android_lifecycle-2.0.6
gallery_saver-2.3.2
image_picker-0.8.5+3
image_picker_android-0.8.4+13
image_picker_for_web-2.1.8
image_picker_ios-0.8.5+5
package_info_plus-1.4.2
package_info_plus_linux-1.0.5
package_info_plus_macos-1.3.0
package_info_plus_web-1.0.5
package_info_plus_windows-1.0.5
path_provider-2.0.10
path_provider_android-2.0.14
path_provider_ios-2.0.9
path_provider_linux-2.1.7
path_provider_macos-2.0.6
path_provider_windows-2.0.7
permission_handler-9.2.0
permission_handler_android-9.0.2+1
permission_handler_apple-9.0.4
permission_handler_windows-0.1.0
photo_manager-2.1.1
sqflite-2.0.2+1
url_launcher-6.1.2
url_launcher_android-6.0.17
url_launcher_ios-6.0.17
url_launcher_linux-3.0.1
url_launcher_macos-3.0.1
url_launcher_web-2.0.11
url_launcher_windows-3.0.1
video_player-2.4.2
video_player_android-2.3.4
video_player_avfoundation-2.3.4
video_player_web-2.0.10
wakelock-0.6.1+2
wakelock_macos-0.4.0
wakelock_web-0.4.0

**Comment by maple52046** [comment]
> Hi @maple52046, does this reproduce consistently for you? Or did it occur only once? And what other devices did you experience this on?

Hi @danagbemava-nc, thanks for your reply.

I guess this problem occurred might because I deleted /tmp directory when the app is started.

My flutter app takes more than 10GB of disk space, but the actual data is only 50MB. I found the same issue on stackoverflow, and the solution is to remove this directory.

Currently, this issue doesn't happen when the app is in release mode, just only debug mode (maybe include profile mode). Perhaps the flutter toolchain is stored in /tmp?

I'll do more tests on these days.

**Comment by danagbemava-nc** [comment]
Hi @maple52046, thanks for the info. 

> My flutter app takes more than 10GB of disk space, but the actual data is only 50MB.

That seems like a lot of storage for just one app. Do you have some large assets or is it just the files generated by flutter that use that much storage on your device?
