### ISSUE TITLE
iOS Not launching after plug-in changes

### ISSUE THREAD

**Issue by jtrunick** [flutter/flutter#10499]
## Steps to Reproduce

Tried to upgrade to new plug-in support as documented here: https://groups.google.com/forum/#!searchin/flutter-dev/path_provider%7Csort:relevance/flutter-dev/J3ujgdOuG98/H90pdpM8BgAJ

Android upgraded OK, for iOS there is an error.

I added from example projects, a Podfile, the .h/.m of GeneratedPluginRegistrant. I also specified FlutterStreamHandler:
@interface AppDelegate : FlutterAppDelegate<FlutterStreamHandler>
[GeneratedPluginRegistrant registerWithRegistry:self];

I deleted the build/ directory, and ran.

## Logs

CoreSimulatorBridge: Launch successful for 'com.harpsoft.bendometer'
Unknown class ViewController in Interface Builder file.
You've implemented -[<UIApplicationDelegate> application:didReceiveRemoteNotification:fetchCompletionHandler:], but you still need to add "remote-notification" to the list of your supported UIBackgroundModes in your Info.plist.
-[UIViewController setMessageHandlerOnChannel:binaryMessageHandler:]: unrecognized selector sent to instance 0x7fbc0a7064e0
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[UIViewController setMessageHandlerOnChannel:binaryMessageHandler:]: unrecognized selector sent to instance 0x7fbc0a7064e0'
	*** First throw call stack:
	(
		0   CoreFoundation                      0x0000000104d7ed4b __exceptionPreprocess + 171
		1   libobjc.A.dylib                     0x000000010473521e objc_exception_throw + 48
		2   CoreFoundation                      0x0000000104deef04 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
		3   CoreFoundation                      0x0000000104d04005 ___forwarding___ + 1013
		4   CoreFoundation                      0x0000000104d03b88 _CF_forwarding_prep_0 + 120
		5   Flutter                             0x0000000101ad57d4 -[FlutterMethodChannel setMethodCallHandler:] + 104
		6   path_provider                       0x0000000103380915 +[PathProviderPlugin registerWithRegistrar:] + 173
		7   Runner                              0x0000000101a4dfae +[GeneratedPluginRegistrant registerWithRegistry:] + 94
		8   Runner                              0x0000000101a48900 -[AppDelegate application:didFinishLaunchingWithOptions:] + 64
		9   UIKit                               0x00000001051993c2 -[UIApplication _handleDelegateCallbacksWithOptions:isSuspended:restoreState:] + 290
		10  UIKit                               0x000000010519ad47 -[UIApplication _callInitializationDelegatesForMainScene:transitionContext:] + 4236
		11  UIKit                               0x00000001051a10ed -[UIApplication _runWithMainScene:transitionContext:completion:] + 1731
		12  UIKit                               0x000000010519e26d -[UIApplication workspaceDidEndTransaction:] + 188
		13  FrontBoardServices                  0x000000010815c6cb __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ + 24
		14  FrontBoardServices                  0x000000010815c544 -[FBSSerialQueue _performNext] + 189
		15  FrontBoardServices                  0x000000010815c8cd -[FBSSerialQueue _performNextFromRunLoopSource] + 45
		16  CoreFoundation                      0x0000000104d23761 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
		17  CoreFoundation                      0x0000000104d0898c __CFRunLoopDoSources0 + 556
		18  CoreFoundation                      0x0000000104d07e76 __CFRunLoopRun + 918
		19  CoreFoundation                      0x0000000104d07884 CFRunLoopRunSpecific + 420
		20  UIKit                               0x000000010519caea -[UIApplication _run] + 434
		21  UIKit                               0x00000001051a2c68 UIApplicationMain + 159
		22  Runner                              0x0000000101a48e92 main + 80
		23  libdyld.dylib                       0x000000010ba5468d start + 1

## Flutter Doctor

Paste the output of running `flutter doctor` here.

[✓] Flutter (on Mac OS X 10.11.6 15G1510, locale en, channel alpha)
    • Flutter at /Users/joelt/dev/3rd_party/flutter
    • Framework revision e2f54df5ab (2 days ago), 2017-06-02 10:43:54 -0700
    • Engine revision 1f2aa07571
    • Tools Dart version 1.24.0-dev.3.0

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at /Users/joelt/Library/Android/sdk
    • Platform android-25, build-tools 25.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.2.1, Build version 8C1002
    • ios-deploy 1.9.1
    • CocoaPods version 1.2.1

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Gradle version 3.2
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.1.3)
    • Dart plugin version 171.4424.63
    • Flutter plugin version 14.0

[✓] Connected devices
    • iPhone SE • 062AC068-13CE-4F74-A927-C0DA2CE48106 • ios • iOS 10.2 (simulator)

**Comment by eseidelGoogle** [comment]
I believe this is https://github.com/flutter/flutter/issues/9984 ?

**Comment by jtrunick** [comment]
I changed the .storyboard file to use the newer FlutterViewController as the custom class, now I get this:

*** Assertion failure in -[UIApplication _runWithMainScene:transitionContext:completion:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKit_Sim/UIKit-3600.6.21/UIApplication.m:3680
2017-06-05 00:42:15.510 Runner[22799:457874] *** Assertion failure in -[UIApplication _runWithMainScene:transitionContext:completion:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKit_Sim/UIKit-3600.6.21/UIApplication.m:3680
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Application windows are expected to have a root view controller at the end of application launch'
	*** First throw call stack:
	(
		0   CoreFoundation                      0x00000001061c7d4b __exceptionPreprocess + 171
		1   libobjc.A.dylib                     0x0000000105b7e21e objc_exception_throw + 48
		2   CoreFoundation                      0x00000001061cbe42 +[NSException raise:format:arguments:] + 98
		3   Foundation                          0x000000010571366d -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 195
		4   UIKit                               0x00000001065ea91d -[UIApplication _runWithMainScene:transitionContext:completion:] + 3827
		5   UIKit                               0x00000001065e726d -[UIApplication workspaceDidEndTransaction:] + 188
		6   FrontBoardServices                  0x00000001095a56cb __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ + 24
		7   FrontBoardServices                  0x00000001095a5544 -[FBSSerialQueue _performNext] + 189
		8   FrontBoardServices                  0x00000001095a58cd -[FBSSerialQueue _performNextFromRunLoopSource] + 45
		9   CoreFoundation                      0x000000010616c761 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
		10  CoreFoundation                      0x000000010615198c __CFRunLoopDoSources0 + 556
		11  CoreFoundation                      0x0000000106150e76 __CFRunLoopRun + 918
		12  CoreFoundation                      0x0000000106150884 CFRunLoopRunSpecific + 420
		13  UIKit                               0x00000001065e5aea -[UIApplication _run] + 434
		14  UIKit                               0x00000001065ebc68 UIApplicationMain + 159
		15  Runner                              0x0000000102e91ec9 main + 80
		16  libdyld.dylib                       0x000000010ce9d68d start + 1

**Comment by jtrunick** [comment]
Turns out I had some calls that were problematic that needed to be removed as found in didFinishLaunchingWithOptions:

    FlutterDartProject* project = [[FlutterDartProject alloc] initFromDefaultSourceForConfiguration];
    self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
