### ISSUE TITLE
[iOS]In some cases, some font sytle are different from others in Chinese

### ISSUE THREAD

**Issue by xiaoxiaowesley** [flutter/flutter#104996]
My users in my app report some strange cases within some unknown situations some font styles of some Chinese characters are different from others. Unfortunately, I haven't reproduced step.

Here are some features I have found so far.

- Only a few Chinese characters have problems in sentences.
- Restart  cellphone **maybe** recover (not 100% recover).
- Use the ios system keyboard.

![IMG_0257_1](https://user-images.githubusercontent.com/44207000/171087452-a43bb32a-6ac6-4c24-8389-bafb8cda8a9e.jpg)

the font of characters '来'  is different from others.

![IMG_02572](https://user-images.githubusercontent.com/44207000/171087458-9f70e59a-0358-4ff7-8d8c-2d47ced22386.jpg)

the font of characters '歉'  is different from others.

But when the user restarted the phone or a few days later problem recovered automatically.
![IMG_02582](https://user-images.githubusercontent.com/44207000/171087963-9b9632b3-1950-4fb2-856f-6185aa1111e0.jpg)

**Comment by exaby73** [comment]
Hello @xiaoxiaowesley. Can you provide a [minimal, reproducible example][1] and the output of `flutter doctor -v`?

[1]: https://stackoverflow.com/help/minimal-reproducible-example

**Comment by xiaoxiaowesley** [comment]
> `flutter doctor -v`?

 flutter doctor -v 
[✓] Flutter (Channel unknown, 2.5.4-0.0.pre.52, on macOS 12.3.1 21E258
    darwin-x64, locale zh-Hans-CN)
    • Flutter version 2.5.4-0.0.pre.52 at
      /Users/xiaoxiang/Documents/code/flutter/flutter253
    • Upstream repository unknown
    • Framework revision fb193e8f35 (2 个月前), 2022-03-23 14:24:20 +0800
    • Engine revision d175d70d28
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/xiaoxiang/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/xiaoxiang/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.3.1, Build version 13E500a
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.67.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Connected device (3 available)
    • RoyChan 的 iPhone (mobile) • 9f4880651c05ea08146eeb2d66408def76cdceee • ios
      • iOS 14.3 18C66
    • iPhone (mobile)           • 00008020-000954E136A1002E                • ios
      • iOS 14.6 18F72
    • Chrome (web)              • chrome                                   •
      web-javascript • Google Chrome 102.0.5005.61
    ! Error: RoyChan 的 iPhone is busy: Fetching debug symbols for RoyChan 的
      iPhone. Xcode will continue when RoyChan 的 iPhone is finished. (code -10)

**Comment by xiaoxiaowesley** [comment]
> Hello @xiaoxiaowesley. Can you provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) and the output of `flutter doctor -v`?

Sorry for that I can't reproduce it because It's reported from my user. I was wondering if anyone in the community had a similar problem.

**Comment by exaby73** [comment]
Hello @xiaoxiaowesley. I've noticed that you're running an older version of Flutter `Channel unknown, 2.5.4-0.0.pre.52`. Please upgrade to the latest version and confirm if the behavior persists. 

If it does, we would need a reproducible sample, without which we cannot really proceed. It could be specific to exact text or a device and without a reproducible example, we won't be able to understand the issue.
