### ISSUE TITLE
Unable to find a specification for `Google/SignIn (~> 3.0)`

### ISSUE THREAD

**Issue by Solido** [flutter/flutter#10494]
## Steps to Reproduce

Open google sign_in_example from firebase plugins repo, 
`flutter run`
## Logs

```  +2 ms] Running pod install...
[            ] [ios/] pod install
[     +620 ms] Analyzing dependencies
                       Fetching podspec for `Flutter` from `/Users/dev7/Install/flutter/bin/cache/artifacts/engine/ios-release`
                       Fetching podspec for `google_sign_in` from `/Users/dev7/Documents/PRJCTS/plugins/packages/google_sign_in/ios`
                       [!] Unable to find a specification for `Google/SignIn (~> 3.0)` depended upon by `google_sign_in`
                       
                       
                       [!] Automatically assigning platform ios with version 8.0 on target Runner because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.
[      +23 ms] "flutter ios" took 3,739ms.
Error running pod install: Exit code 1 from: pod install
```

## Flutter Doctor

```
[✓] Flutter (on Mac OS X 10.12.4 16E195, locale en-FR, channel master)
    • Flutter at /Users/dev7/Install/flutter
    • Framework revision c55097da7d (31 hours ago), 2017-06-03 06:05:09 +0200
    • Engine revision bd09286e4a
    • Tools Dart version 1.24.0-dev.3.0

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.2)
    • Android SDK at /Users/dev7/Library/Android/sdk
    • Platform android-25, build-tools 25.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.3.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3.2, Build version 8E2002
    • ios-deploy 1.9.1
    • CocoaPods version 1.2.1

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Gradle version 3.2
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] Connected devices
    • iPhone SE • B84FB97F-1BAE-48EF-9313-99BE7E7F92D2 • ios • iOS 10.3 (simulator)
```

**Comment by mit-mit** [comment]
Hi, can you clarify which exact example from which repo you are using?

The following steps seem to work for me:

1. `git clone https://github.com/flutter/plugins`
1. `cd plugins/packages/google_sign_in/`
1. `cd example/`
1. `flutter run`

**Comment by Solido** [comment]
I've been stuck with plugins installation on Ios for weeks now.
Sure that this case only happen on my setup.

Question should rather be what's the meaning of this error, what cause it, how to correct it or prevent it.

It happened on all my projects so I decided to move on official project to see if it works.
Since it's still fail my setup is faulty but doctor said all is OK.
I'm asking for clue.

Thanks.

**Comment by mit-mit** [comment]
Does `pod setup` in a terminal complete with no errors?

Do the exact steps I listed above fail with the error you posted at the top of this bug?

**Comment by Solido** [comment]
Your command found it :

first I get 
```
Please set FLUTTER_FRAMEWORK_DIR to the directory containing Flutter.framework

[!] Invalid `Podfile` file: Please set FLUTTER_FRAMEWORK_DIR to the directory containing Flutter.framework.
```
then by setting it 
```
Fetching podspec for `Flutter` from `/Users/username/Install/flutter`
[!] No podspec found for `Flutter` in `/Users/username/Install/flutter`
```

**Comment by jakobr-google** [comment]
Try running `pod repo update` to make sure you have the latest CocoaPods specs.

The error you're getting in the issue description means that it can't find the `Google/SignIn` pod of version 3.0 (or compatible). The pod does exist, but you might not have the spec in your local pods repository.

If you want to run `pod install` manually (like in your latest comment), you'll need to set FLUTTER_FRAMEWORK_DIR to point to the Flutter iOS framework, which would be something like `/Users/username/Install/flutter/bin/cache/artifacts/engine/ios`.

**Comment by Solido** [comment]
Using the commands you provided I was able to find that something was corrupted in CocoaPod.
On the official CocoaPod thread they provided the following advice
`rm -rf ~/.cocoapods/repos`

I'm really happy that this is solved.
Thank you !

**Comment by mit-mit** [comment]
Great to hear! Can we close this, or are you seeing other issues?

**Comment by Solido** [comment]
My project is some weeks old now I get 
`MissingPluginException(No implementation found for method init on channel plugins.flutter.io/google_sign_in)`

I guess I should start a new project from scratch then add plugins then copy paste my sources ?
If you can point me to some docs I guess this one is closed.
Thank you very much.

**Comment by mit-mit** [comment]
Yes, for projects older than ~3-4 weeks there were some breaking changes, incl:
https://groups.google.com/forum/#!searchin/flutter-dev/breaking%7Csort:relevance/flutter-dev/zba1Ynf2OKM/6m__2uCbAgAJ

My recommendation would be to `flutter create` a new application, then move over the contents of `pubspec.yaml` and `lib/*.dart`. This is assuming you have not written any native code yourself; in that case additional code from the ios/ and android/ dirs would also need to be moved.
