### ISSUE TITLE
Add support for full screen dialogs 

### ISSUE THREAD

**Issue by guidezpl** [flutter/flutter#104961]
[Spec](https://m3.material.io/components/dialogs/specs#bbf1acde-f8d2-4ae1-9d51-343e96c4ac20)

![image](https://user-images.githubusercontent.com/6655696/170970763-56cd8e01-c475-4010-b29f-52d8b033daa7.png)

**Comment by HansMuller** [comment]
Part of https://github.com/flutter/flutter/issues/91605

**Comment by TahaTesser** [comment]
This is required for https://github.com/flutter/flutter/issues/106101, looking at what is needed to make this feature possible.

**Comment by TahaTesser** [comment]
cc: @guidezpl @darrenaustin 

Do you think creating a new `FullscreenDialog` widget is the way to go to make it work out of the box? or perhaps adding something like `Dialog.fullscreen()`. 

We can create a fullscreen dialog using [Dialog](https://master-api.flutter.dev/flutter/material/Dialog-class.html) widget with some zero `insetPadding` and a Scaffold. If this is sufficient, we can close this issue. 


<details> 
<summary>Code Sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key, this.dark = true, this.useMaterial3 = true});

  final bool dark;
  final bool useMaterial3;

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      themeMode: dark ? ThemeMode.dark : ThemeMode.light,
      theme: ThemeData(
        useMaterial3: useMaterial3,
        brightness: Brightness.light,
        colorSchemeSeed: const Color(0xff6750a4),
      ),
      darkTheme: ThemeData(
        useMaterial3: useMaterial3,
        brightness: Brightness.dark,
        colorSchemeSeed: const Color(0xff6750a4),
      ),
      home: const DialogExample(),
    );
  }
}

class DialogExample extends StatelessWidget {
  const DialogExample({super.key});

  Future<void> _dialog(BuildContext context) async {
    return showDialog(
      context: context,
      builder: (BuildContext context) {
        return Dialog(
          insetPadding: EdgeInsets.zero,
          child: Scaffold(
            appBar: AppBar(
              title: const Text('Full-screen dialog title'),
              centerTitle: false,
              automaticallyImplyLeading: false,
              leading: IconButton(
                onPressed: () => Navigator.of(context).pop(),
                icon: const Icon(Icons.close),
              ),
              actions: <Widget>[
                TextButton(
                  onPressed: () => Navigator.of(context).pop(),
                  child: const Text('Save'),
                ),
              ],
            ),
          ),
        );
      },
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Dialog'),
      ),
      body: Center(
        child: ElevatedButton(
          onPressed: () => _dialog(context),
          child: const Text('Open Full-screen Dialog'),
        ),
      ),
    );
  }
}

``` 
	
</details>


https://user-images.githubusercontent.com/48603081/178717142-9b489f94-5391-4de7-bf33-4a1ca7b5e16d.mov

**Comment by guidezpl** [comment]
It does look very close, but not quite up to spec (save button padding). I do like `Dialog.fullscreen()` for this kind of case.

Can you add some content to the example? I'd like to see how close to spec we are by default.

**Comment by TahaTesser** [comment]
[Dialog](https://master-api.flutter.dev/flutter/material/Dialog-class.html) is an actually unopinionated dialog. 

In the Flutter context, [AlertDialog](https://master-api.flutter.dev/flutter/material/AlertDialog-class.html) is the dialog that provides the ability title, message, and actions buttons and the M3 Fullscreen dialog is just that but of course screen. In those cases, creating `AlertDialog.fullscreen` makes more sense (Dialog being unopinionated means it has none of the features to support M3 tokens) 

![Screenshot 2022-07-14 at 16 11 28](https://user-images.githubusercontent.com/48603081/178990748-c8de9d74-8205-4894-8d64-a44c3e0ba4fe.png)

**Comment by guidezpl** [comment]
Agreed that AlertDialog isn't the way to go for this. Since Dialog  

> In this case, creating a new FullscreenDialog makes more sense to me (Dialog being unopinionated means it has none of the features to support M3 tokens)
I'm not sure I understand this. Since `Dialog` is so close, wouldn't it make more sense to migrate it? We could have `Dialog.fullscreen` which sets `insetPadding` and a new `padding` or `contentPadding` to match spec, leaving the rest up to users.

Also, if you overlay the sample with the spec, is the padding around the button the only padding difference?

**Comment by TahaTesser** [comment]
> I'm not sure I understand this. Since Dialog is so close, wouldn't it make more sense to migrate it? We could have Dialog.fullscreen which sets insetPadding and a new padding or contentPadding to match spec, leaving the rest up to users.

That's what I thought at first, given Android too doesn't provide the concrete fullscreen implementation.

According to [Dialogs - Full-screen dialogs](https://m3.material.io/components/dialogs/specs#bbf1acde-f8d2-4ae1-9d51-343e96c4ac20) and [tokens](https://github.com/flutter/flutter/blob/master/dev/tools/gen_defaults/data/dialog_fullscreen.json), there needs to be a header with the title with app bar like height, the closing icon, and action text button and it should should also elevate on the scroll and a divider. 


`AlertDialog` follows its specs so should fullscreen dialog given the similar tokens and specs above?

Could we leave all this full-screen dialog design for the users to match the specs? 

I think the new `FullscreenDialog` that matches specs and uses the tokens to style header, icon, action buttin, and the divider is probably good?

**Comment by guidezpl** [comment]
Both options are valid, but I suspect the customizeability of full screen dialogs is more important than providing an exact match to spec. I'd lean towards the `Dialog.fullscreen` approach.

**Comment by TahaTesser** [comment]
@guidezpl 

Thanks so much!

**Comment by pedromassango** [comment]
I was about to file a new issue for this :) Is someone working on this up?

**Comment by TahaTesser** [comment]
@pedromassango 
I have the code ready to be filed. (I was on vacation and working on higher priority issues).

**Comment by TahaTesser** [comment]
I have implemented `Dialog.fullscreen` based on the discussion. I will PR soon and would like it if you take a look.

**Comment by pedromassango** [comment]
That is great 🏅

**Comment by TahaTesser** [comment]
Update: 
Didn't forget about this. I was focused on getting some existing PRs merged. 
Filing this dialog tomorrow.
