### ISSUE TITLE
How to write image to photos?

### ISSUE THREAD

**Issue by pedia** [flutter/flutter#10495]
It's very important feature to me.

Thanks

**Comment by eseidelGoogle** [comment]
I believe https://github.com/flutter/plugins/tree/master/packages/image_picker was written by @collinjackson

**Comment by collinjackson** [comment]
/cc @goderbauer who was also involved

Can you describe your use case? Do you have a jpeg file downloaded to a temporary folder? Or is it a ui.Image that you've built up using the Canvas APIs?

**Comment by pedia** [comment]
We modify some images in photo and save back to photos. Support in jpeg format.

**Comment by Hixie** [comment]
Questions:
 - Do we think this is in scope for the image picker plugin?
 - Is it something we want to provide as a first-party plugin?

**Comment by Hixie** [comment]
Seth will investigate these questions.

**Comment by sethladd** [comment]
We believe this is best done in a new plugin, not the "image picker" plugin.

We also believe that the necessary plugin/interop APIs are available and thus anyone could build this "image saver" plugin. For docs: https://flutter.io/developing-packages/

We don't have plans to make this a first-party plugin. However, we want our plugin infra to support this use case, so if you try to make this plugin and are blocked by the plugin API, please let us know.

**Comment by sethladd** [comment]
We're going to close this, as we think that this plugin can be "self service". If the plugin/interop API isn't sufficient for this requirement, please let us know.

**Comment by jinfagang** [comment]
How to this exactly?

**Comment by NTMS2017** [comment]
I know this is old and close but still want to add some detail so I can overcome the difficulties that I am facing. There is a image plugin (https://pub.dartlang.org/packages/image) and it says (Published Jun 14, 2018 FLUTTER WEB OTHER). Meaning is that works on Flutter. I try to use it in Flutter and got an error as shown below. Its working in dart console app but couldn't make it to run in Flutter.

-------
I am trying to load image using rootBundle in flutter and I get this below error. Any help please.

**E/flutter (24839): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter (24839): Unable to load asset: packages/myAppName/assets/images/ReceiptRaw_1.jpg**

```
Future<bool> makeReceiptImage() async {
  // load the receipt jpeg
  String mImagePath = await rootBundle.loadString('packages/myAppName/assets/images/ReceiptRaw_1.jpg');
  print("mImagePath: $mImagePath");
  Image _receiptImage = await decodeImage(new File(mImagePath).readAsBytesSync());

  drawString(_receiptImage, arial_48, 440, 30, “Customer Name”, color: 0xFF000000);

  // Write it to disk as a different jpeg
  var new_jpeg = await encodeJpg(_receiptImage);
  String newImagePath = await rootBundle.loadString('packages/myAppName/assets/images/ReceiptRaw_2.jpg');
  await new File(‘$newImagePath’).writeAsBytesSync(new_jpeg);
}
```


**The Dart Console App is working with similar code**

**import 'dart:io';
import 'dart:convert';
import 'dart:async';
import 'package:image/image.dart';

void main() async {

  // load the receipt jpeg
  String mImagePath = 'images/ReceiptRaw_1.jpg';
  Image _receiptImage = decodeImage(new File(mImagePath).readAsBytesSync());
  drawString(_receiptImage, arial_48, 440, 30, “Customer Name”, color: 0xFF000000);


  // Write it to disk as a different jpeg
  var new_jpeg = encodeJpg(_receiptImage);
  new File('images/ReceiptRaw_1.jpg').writeAsBytesSync(new_jpeg);
}**

**Comment by zoechi** [comment]
@NTMS2017 this looks unrelated to the issue or the `image` package.
This kind of how-to question is better asked on StackOverflow

**Comment by NTMS2017** [comment]
Thanks @zoechi
