### ISSUE TITLE
[url_launcher_web] Incorrect comparison causing incorrect behaviour 

### ISSUE THREAD

**Issue by fatadel** [flutter/flutter#104909]
This comparision is useless because `openNewWindow` returns non-nullable `html.WindowBase`, which means any URL is assumed to be launchable on web (which is not true at all, try with custom application schemes for example).

https://github.com/flutter/plugins/blob/b0bfab678f83bebd49e9f9d0a83fe9b40774e853/packages/url_launcher/url_launcher_web/lib/url_launcher_web.dart#L88

**Comment by darshankawar** [comment]
@fatadel 
Can you provide us a code sample that shows this behavior with current result ?
