### ISSUE TITLE
TextField in ListView hides keyboard instantly on tap

### ISSUE THREAD

**Issue by markentingh** [flutter/flutter#10498]
I have a form within a scrollable ListView where I can generate new TextFields by clicking a button. After generating a few TextFields, I try to tap on one of them located about halfway down the screen. The Android keyboard appears and instantly disappears after tapping the TextField because the TextField is located behind the keyboard. Shouldn't the ListView auto-scroll the focused TextField into view instead, so that the keyboard doesn't disappear?

**Comment by AlexiCoard** [comment]
Maybe related to this : #10363

**Comment by markentingh** [comment]
I forgot to mention, I am also using persistentFooterButtons, which is also blocking the view after the keyboard appears. Either way, the TextField does not scroll into view like I am use to seeing in other native apps for Android.

**Comment by Hixie** [comment]
This is basically the same bug as #105, #170, #172, #188.

**Comment by avmanpuria** [comment]
I too have faced the same issue wherein the keyboard disappears for textfields which are towards the bottom end of the screen. I changed the order of the fields and found that if the textfield is above the keyboard, the keyboard does not disappear.

Is there any fix or workaround available for this issue?

**Comment by szastavnyy** [comment]
hi. still an issue ? any planned fix ? thank you

**Comment by goderbauer** [comment]
I believe this has been fixed a while ago. Please re-open with more details if you still see this.

**Comment by laszlo-galosi** [comment]
Hi this is happened to me int ListView and also SingleChildScrollView with Column for the last TextField. However if I supplied a key
for the last field, the issue is not happening. Maybe it's related to [#15719](https://github.com/flutter/flutter/issues/15719)
