### ISSUE TITLE
Italic formatting is not applied when at least one of the boundary is inside a word

### ISSUE THREAD

**Issue by harkairt** [flutter/flutter#104928]
Package I am referring to: [flutter_markdown](https://pub.dev/packages/flutter_markdown)

While this renders properly
`i**talic bol**d` as i**talic bol**d

Italic style is not rendered well
`i_talic bol_d` is still `i_talic bol_d` when rendered

When the underscores are placed next to spaces/word bounds then the formatting is applied well.
eg:
`_italic _bold`
`_italic_ bold`

**Comment by darshankawar** [comment]
@harkairt 
Can you provide a minimal code sample that shows actual vs expected result you are looking for ?

**Comment by harkairt** [comment]
dart```
import 'package:flutter/material.dart';
import 'package:flutter_markdown/flutter_markdown.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: const [
              MarkdownBody(data: 'i**talic bol**d'),
              MarkdownBody(data: 'i_talic bol_d'),
              MarkdownBody(data: 'i*talic bol*d'),
              MarkdownBody(data: '_italic_ bold'),
            ],
          ),
        ),
      ),
    );
  }
}
```

☑️ Upon further testing now I found out `*` should be used for italic
What mislead me is `_` is still partly supported.

<img width="211" alt="image" src="https://user-images.githubusercontent.com/32367206/171104333-6894a584-e754-472a-b2f4-da77b24cb4fb.png">

As you see the 2nd item tries to achieve the same way to make part of the text italic, as the way it works with bold, but that does not work (although 4th example works with `_` as italic.)
But the 3rd line is formatting well.

Issue can be closed, I assume this behavior (`_` formats text as italic, but not as good as `*`) is somehow a remainder from previous markdown?!
