### ISSUE TITLE
Branch '3.0.1' prevents cloning the tag with the same name

### ISSUE THREAD

**Issue by lexxxel** [flutter/flutter#104901]
The issue is that there is a branch with the same name as a tag: `3.0.1`  
previously, branches did have a different name then release tags, resulting in `git clone` using the 'wrong' `--branch` and flutter to present the wrong version during builds (`0.0.0-unknown`).

## Steps to Reproduce

In my docker file I clone flutter with
1. `git clone --depth 1 --branch $FLUTTER_VERSION https://github.com/flutter/flutter.git && \`

## Logs

<details>
<summary>
[✓] Flutter (Channel 3.0.1, 0.0.0-unknown, on Ubuntu 20.04.4 LTS 5.18.0-gentoo, locale en_US)
</summary>

```
$ flutter pub get
Running "flutter pub get" in production...                      
The current Flutter SDK version is 0.0.0-unknown.
Because mobile_scanner 1.1.1 requires Flutter SDK version >=1.10.0 and no versions of mobile_scanner match >1.1.1 <2.0.0, mobile_scanner ^1.1.1 is forbidden.
So, because sleepjournal depends on mobile_scanner ^1.1.1, version solving failed.
pub get failed (1; So, because sleepjournal depends on mobile_scanner ^1.1.1, version solving failed.)
```

```
dev@03f12627b2cf:~$ flutter doctor -v
[✓] Flutter (Channel 3.0.1, 0.0.0-unknown, on Ubuntu 20.04.4 LTS 5.18.0-gentoo, locale en_US)
    • Flutter version 0.0.0-unknown at /home/dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9cfac48e2e (4 days ago), 2022-05-24 08:58:08 -0700
    • Engine revision 07f0224e5b
    • Dart version 2.18.0 (build 2.18.0-147.0.dev)
    • DevTools version 2.13.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/dev/Android/sdk
    • Platform android-31, build-tools 30.0.3
    • ANDROID_SDK_ROOT = /home/dev/Android/sdk
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+10-Ubuntu-0ubuntu0.20.04.1)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✗] Linux toolchain - develop for Linux desktop
    ✗ clang++ is required for Linux development.
      It is likely available from your distribution (e.g.: apt install clang), or can be downloaded from https://releases.llvm.org/
    ✗ CMake is required for Linux development.
      It is likely available from your distribution (e.g.: apt install cmake), or can be downloaded from https://cmake.org/download/
    ✗ ninja is required for Linux development.
      It is likely available from your distribution (e.g.: apt install ninja-build), or can be downloaded from https://github.com/ninja-build/ninja/releases
    ✗ pkg-config is required for Linux development.
      It is likely available from your distribution (e.g.: apt install pkg-config), or can be downloaded from https://www.freedesktop.org/wiki/Software/pkg-config/

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (1 available)
    • Linux (desktop) • linux • linux-x64 • Ubuntu 20.04.4 LTS 5.18.0-gentoo

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 3 categories.
```

</details>

**Comment by lexxxel** [comment]
@godofredoc can you help?

**Comment by maheshmnj** [comment]
Hi @lexxxel, Thanks for filing the issue. Labeling this issue for further insights from the team.

cc: @christopherfujino

**Comment by Mike278** [comment]
I ran into this too when trying to upgrade from Flutter 1.20.4 to 3.0.1, although in my case it presented itself slightly differently. 

After fixing analyzer errors and ignoring deprecation warnings for `FlatButton`, my project's tests were passing when flutter was installed via https://github.com/flutter/flutter/releases/tag/3.0.1 (zip) or via `cd ~/flutter && git checkout 3.0.1 && flutter --version`.

But when running tests in CI - where Flutter is installed with `git clone --branch $FLUTTER_VERSION https://github.com/flutter/flutter.git` - tests failed because `FlatButton` didn't exist anymore. 

IOW, [this exists](https://github.com/flutter/flutter/blob/refs/tags/3.0.1/packages/flutter/lib/src/material/flat_button.dart) and [this doesn't](https://github.com/flutter/flutter/blob/3.0.1/packages/flutter/lib/src/material/flat_button.dart).

**Comment by CaseyHillers** [comment]
\cc @christopherfujino @itsjustkevin

**Comment by godofredoc** [comment]
@christopherfujino @itsjustkevin have you looked at this issue?

**Comment by christopherfujino** [comment]
> @christopherfujino @itsjustkevin have you looked at this issue?

I have no idea how this happened. I doubt it was via the conductor, as we validate that branches we push to upstream (https://github.com/flutter/flutter/blob/master/dev/conductor/core/lib/src/start.dart#L52) are either stable or beta (https://github.com/flutter/flutter/blob/master/dev/conductor/core/lib/src/globals.dart#L15).

**Comment by christopherfujino** [comment]
@godofredoc does this work for you? https://docs.github.com/en/github-ae@latest/admin/monitoring-activity-in-your-enterprise/exploring-user-activity/viewing-push-logs

**Comment by Mike278** [comment]
Just FYI this method is used in a fairly popular dockerfile: https://github.com/cirruslabs/docker-images-flutter/blob/4b904a42e86f312184b006437e4ead6c3537b3f2/sdk/Dockerfile#L13

**Comment by godofredoc** [comment]
@christopherfujino should we just go ahead and delete 3.0.1 branch. I'm not sure how it was created maybe from the branch list in the github UI?

**Comment by christopherfujino** [comment]
> @christopherfujino should we just go ahead and delete 3.0.1 branch. I'm not sure how it was created maybe from the branch list in the github UI?

SGTM, that will fix fresh CI builds.

**Comment by godofredoc** [comment]
Done, @lexxxel can you please try cloning again?

**Comment by lexxxel** [comment]
Looks good now!
I remove the .git folder to slim down the image, resulting in an unknown channel (so that is not an error).

```
dev@01028fe9869a:~$ flutter doctor -v
[✓] Flutter (Channel unknown, 3.0.1, on Ubuntu 20.04.4 LTS 5.15.32-gentoo-r1, locale en_US)
    • Flutter version 3.0.1 at /home/dev/flutter
    • Upstream repository unknown
    • Framework revision fb57da5f94 (2 weeks ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/dev/Android/sdk
    • Platform android-31, build-tools 30.0.3
    • ANDROID_SDK_ROOT = /home/dev/Android/sdk
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+10-Ubuntu-0ubuntu0.20.04.1)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (1 available)
    • Linux (desktop) • linux • linux-x64 • Ubuntu 20.04.4 LTS 5.15.32-gentoo-r1

[✓] HTTP Host Availability
    • All required HTTP hosts are available

```

**Comment by godofredoc** [comment]
Thanks for the confirmation that cloning is working properly now.

**Comment by CaseyHillers** [comment]
When 3.0.2 is released, the unknown channel will get fixed.

**Comment by christopherfujino** [comment]
> Looks good now! I remove the .git folder to slim down the image, resulting in an unknown channel (so that is not an error).

Please don't delete the .git folder, the Flutter CLI tool depends on the SDK being a git repo for various operations.

**Comment by CaseyHillers** [comment]
I'm not sure what your dockerfile looks like, but if the last step is to delete the .git folder to trim the size down, that sounds good to me. 

If you're running `flutter upgrade` in CI, you'll no longer be able to get updates.
