### ISSUE TITLE
Splashes are lost if you scroll their row off the screen

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#105]
<a href="https://github.com/Hixie"><img src="https://avatars.githubusercontent.com/u/551196?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Hixie](https://github.com/Hixie)**
_Monday Jul 20, 2015 at 20:33 GMT_
_Originally opened as https://github.com/flutter/engine/issues/149_

---

_From @Hixie on April 20, 2015 20:26_

If you start a splash animation on a row in a scroll list and then scroll that row off the screen then back again, the animation is nowhere to be seen.

_Copied from original issue: domokit/mojo#103_

**Comment by Hixie** [comment]
One way to fix this would be for the splash to trigger a Notification that bubbles up the widget tree up to the list, and causes the list to keep this row alive even if it goes out of view, until it receives a matching "release" notification.

**Comment by eseidelGoogle** [comment]
Is this still an issue @Hixie?

**Comment by Hixie** [comment]
Yes.

**Comment by sethladd** [comment]
Is this issue still valid?

**Comment by Hixie** [comment]
Yes.

**Comment by Hixie** [comment]
This is basically the same bug as #170, #172, #188 .

**Comment by baileyfriend** [comment]
Still having this issue.

**Comment by Hixie** [comment]
Sorry to hear that. Please file a new bug, with a small program showing the problem, and include information such as that printed by `flutter doctor -v`. Thanks!
