### ISSUE TITLE
Support sync style GPU resident Picture.toImage in ImageShaders

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#105085]
It should be possible to add support for this, but in my initial stab at resolving https://github.com/flutter/flutter/issues/77289 and https://github.com/flutter/flutter/issues/13498 it's making the patch a bit more complicated. For now it's going to throw an exception if you try to use `Picture.toGpuImage` in an ImageShader, but can be fixed in a follow up with ImageShader code that respects the owning context of the supplied image.

**Comment by cmkweber** [comment]
No rush but I have a demo ready that utilizes the `Picture.toGpuImage` use case I described awhile back. The final piece relies on the ability to create an `ImageShader` (from a GPU image) to pass as an argument for painting with `drawVertices`. I'll finish out my demo once this is addressed.

**Comment by zanderso** [comment]
This would make some very interesting page transition animations possible since the `ImageShader`s could then be passed as sampler uniforms to a custom shader.

**Comment by tgucio** [comment]
We have a case for this one too for fancy widget animations w/ distort effects. With https://github.com/flutter/flutter/pull/106621 + https://github.com/flutter/flutter/pull/108280 widgets will be able to rasterise themselves quickly and the missing bit is being able to create an ImageShader to use with canvas.drawVertices(). Currently this is done via .toImage() and FutureBuilder so neither elegant nor fast.

**Comment by dnfield** [comment]
The only spot that will be hard to deal with right now is image shaders used on text. That will depend on getting API from SkParagraph that doesn't directly require SkPaint.

AFAIK, @jason-simmons is working on this but I can't find a more specific bug than https://github.com/flutter/flutter/issues/95434.

also /cc @c-h-i-a-m-a-k-a-2 FYI

**Comment by cmkweber** [comment]
I was able to run my demo and everything works as expected! Excellent work @dnfield!
There weren't any noticeable performance drawbacks and I didn't experience aggressive collections, but I didn't test on mobile, only desktop. Sample gist is here for reference: [https://gist.github.com/cmkweber/053396d89aec995e4a88ec97c9208147](GPU Image Shader)
