### ISSUE TITLE
Add support for vertical layout of sliders

### ISSUE THREAD

**Issue by raju-bitter** [flutter/flutter#10500]
Someone on Stackoverflow asked if Flutter sliders can be arranged vertically, which is not possible with the current code base:
https://stackoverflow.com/questions/44341650/

Quoting the [answer on Stackoverflow](https://stackoverflow.com/questions/44341650/vertical-sliders-in-flutter-aligned-side-by-side?answertab=active#tab-top):
The slider component does not support switching the axis from horizontal to vertical. While you could technically rotate the sliders using a RotatedBox or the Transform class, that messes up the position calculation for the sliders. The slider class uses a HorizontalDragGestureRecognizer, so the thumb position change will be adjusted based on horizontal instead of vertical drags.

## Steps to Reproduce
Run the example code from the Stackoverflow answer and try to move the scrollthumb. Vertical scrollthumb position is triggered by moving finger from left to right.

## Flutter Doctor
Flutter • channel alpha • https://github.com/flutter/flutter.git
Framework • revision e2f54df5ab (3 days ago) • 2017-06-02 10:43:54 -0700
Engine • revision 1f2aa07571
Tools • Dart 1.24.0-dev.3.0

**Comment by eseidelGoogle** [comment]
Material Design doesn't seem to discuss vertical sliders:
https://material.io/guidelines/components/sliders.html#
so it would be useful to have examples of ones you're looking for if these belong in the Material library itself.  Alternatively maybe this should just be a separate package?

**Comment by raju-bitter** [comment]
Angular Material Design components have an example of vertical sliders, see https://material.angularjs.org/latest/demo/slider
![image](https://cloud.githubusercontent.com/assets/296926/26826331/fbdf54b6-4ab8-11e7-8d2d-49b435ae3566.png)
Regarding the separate package: Maybe, but having an axis='x' | 'y' setting would probably not require large code changes.

**Comment by TibbleForkDave** [comment]
Any update on this? We're building a app that requires vertical sliders.

**Comment by angel1st** [comment]
Any updates on this one?

**Comment by Ali-Azmoud** [comment]
You can use this package, (flutter_xlider)[https://pub.dartlang.org/packages/flutter_xlider/versions/2.1.0)

**Comment by adamnoor** [comment]
@Ali-Azmoud - The vertical slider looks awesome!   Want to add a comment about usage- to make it not crash when changing the axis to vertical it needs to be wrapped in a parent widget like a container and the height must be set.  

Again thanks for putting this together- it looks great and I'm excited to use it!

**Comment by GokhanArik** [comment]
@benoitjadinon Sorry, I moved to another country and haven't been online for long time, didn't mean to ignore. Seems like Ali already created a better one!

**Comment by jamesncl** [comment]
It seems you can now simply wrap a Slider in a RotatedBox and it works fine. There are no problems with positionining or gesture detection - it all just works, I've just tried it. I would suggest that this issue could be closed?

```
RotatedBox(
     quarterTurns: 1,
     child: Slider( ... )
)
```

**Comment by zoeyfan** [comment]
Given solution has been provided above. I am closing this issue now.

**Comment by AlexHartford** [comment]
> It seems you can now simply wrap a Slider in a RotatedBox and it works fine. There are no problems with positionining or gesture detection - it all just works, I've just tried it. I would suggest that this issue could be closed?
> 
> ```
> RotatedBox(
>      quarterTurns: 1,
>      child: Slider( ... )
> )
> ```

ValueIndicator text is sideways if you do this.  No way I can see to rotate that as RangeSlider's RangeLabels accepts Strings, not Widgets.  Has anyone found a workaround for this? Example below:

![slider](https://user-images.githubusercontent.com/28658524/88598783-e5219100-d01e-11ea-8f8f-5689d4bccc4f.gif)

**Comment by ddevoss** [comment]
> > It seems you can now simply wrap a Slider in a RotatedBox and it works fine. There are no problems with positionining or gesture detection - it all just works, I've just tried it. I would suggest that this issue could be closed?
> > ```
> > RotatedBox(
> >      quarterTurns: 1,
> >      child: Slider( ... )
> > )
> > ```
> 
> ValueIndicator text is sideways if you do this. No way I can see to rotate that as RangeSlider's RangeLabels accepts Strings, not Widgets. Has anyone found a workaround for this? Example below:
> 
> ![slider](https://user-images.githubusercontent.com/28658524/88598783-e5219100-d01e-11ea-8f8f-5689d4bccc4f.gif)

I was able to get around this by using a custom thumb shape that I rotated the canvas on.

For the slider:

```
RotatedBox(
        quarterTurns: -1,
        child: SliderTheme(
          data: SliderThemeData(
            activeTrackColor: color,
            inactiveTrackColor: Colors.black,
            thumbShape: CustomSliderThumbRectangle(color: color),
            trackHeight: 70,
          ),
          child: Slider(
            min: 0,
            max: 255,
            value: widget.value,
            onChanged: widget.onChanged
          ),
        ),
      ),

```
and then my thumb class:

```
class CustomSliderThumbRectangle extends SliderComponentShape {
  final Color color;
  final int min;
  final int max;

  const CustomSliderThumbRectangle({
    @required this.color,
    this.min = 0,
    this.max = 255
  });

  @override
  Size getPreferredSize(bool isEnabled, bool isDiscrete) {
    return Size.fromRadius(40);
  }

  @override
  void paint(
      PaintingContext context,
      Offset center, {
        Animation<double> activationAnimation,
        Animation<double> enableAnimation,
        bool isDiscrete,
        TextPainter labelPainter,
        RenderBox parentBox,
        SliderThemeData sliderTheme,
        TextDirection textDirection,
        double value,
        double textScaleFactor,
        Size sizeWithOverflow,
      }) {
    final Canvas canvas = context.canvas;

    TextSpan span = new TextSpan(
      style: AFTextStyles.timeline,
      text: (min + (max - min) * value).round().toString(),
    );

    TextPainter tp = new TextPainter(
        text: span,
        textAlign: TextAlign.center,
        textDirection: TextDirection.ltr
    );
    tp.layout();
    Offset textCenter = Offset(center.dy - (tp.height / 2), - center.dx - (tp.width / 2));


    Paint paintRB;
    final RRect borderRectB = BorderRadius.circular(8).resolve(textDirection).toRRect(Rect.fromCenter(center: center, width: 30, height: 70));
    paintRB = new Paint()
      ..color = Colors.black
      ..style = PaintingStyle.fill;

    Paint paintR;
    final RRect borderRect = BorderRadius.circular(8).resolve(textDirection).toRRect(Rect.fromCenter(center: center, width: 30, height: 70));
    paintR = new Paint()
      ..color = color
      ..style = PaintingStyle.stroke
      ..strokeWidth = 5;

    canvas.drawRRect(borderRectB, paintRB);
    canvas.drawRRect(borderRect, paintR);

    canvas.rotate(1.5708);
    tp.paint(canvas, textCenter);
  }
}

```
lotta bad hard code in there I know, but I just thought I'd share anyway.
