### ISSUE TITLE
Gradle version mistmatch in Flutter Gradle plugin

### ISSUE THREAD

**Issue by blasten** [flutter/flutter#105040]
flutter.gradle sets the AGP version to 4.1.0 in https://github.com/flutter/flutter/blob/16b7348155c327a87d36570b2a1532c7b3ecfd70/packages/flutter_tools/gradle/flutter.gradle#L64 whereas the app projects use AGP version 7.1.2 in https://github.com/flutter/flutter/blob/606e91ad63d95f881be0c8035d6e3a8e4c66987e/packages/flutter_tools/lib/src/android/gradle_utils.dart#L31

It's also worth investigating why this AGP version needs to be set in flutter.gradle.

**Comment by christopherfujino** [comment]
@GaryQian will https://github.com/flutter/flutter/pull/108355 fix this?

**Comment by GaryQian** [comment]
It does not directly address this. Ill have to investigate what flutter.gradle is doing specifically

**Comment by GaryQian** [comment]
The flutter.gradle AGP has been updated and seems stable. Closing.
