### ISSUE TITLE
Keep log of all manual testing of codesign scripts

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#105045]
This would have helped recover from https://github.com/flutter/flutter/issues/104387

**Comment by XilaiZhang** [comment]
sounds good! Should i keep the log in a google doc such as go/code-signing-bot?

**Comment by godofredoc** [comment]
Let's close after signing implementation is ready

**Comment by ricardoamador** [comment]
@XilaiZhang Any progress?

**Comment by XilaiZhang** [comment]
Thanks for the reminder! yep I need to finish up my codesign project

**Comment by godofredoc** [comment]
Obsolete, automated code signing prevents this.
