### ISSUE TITLE
Boring to Beautiful codelab is broken.

### ISSUE THREAD

**Issue by domesticmouse** [flutter/flutter#105017]
Well, this broke task 6 of boring to beautiful because the pageTransitionsTheme is already set.

https://codelabs.developers.google.com/codelabs/flutter-boring-to-beautiful#6

https://github.com/flutter/codelabs/blob/fb972dd17a7b79b5f0501535b89148d2cc315127/boring_to_beautiful/step_05/lib/src/shared/providers/theme.dart
ln 171

vs.

https://github.com/flutter/codelabs/blob/f072bbe9ac2db929603ac305d19b2fe144206174/boring_to_beautiful/step_05/lib/src/shared/providers/theme.dart
ln 171

also the padding code in the example in task 5 (lab) seems not to be quite as expected (code).

Maybe you want to take a look at this lab (and all other labs as far as I know).
Have a great week.

p.s.:
(sorry for the bug report style, I did not want to open a propper Flutter ticket because of a small Lab issue,
that is why I am posting this as a comment.)

p.p.s.:
Also, the Lab 'boring to beautiful', and maybe Flutter itself seems to have a issue, when you size down the window witdh to small on desktop (winx64), because it throws in a 'flutter base class', maybe you want to investigate that one.
Just pull task 1 code, build on a win x64 (with vscode if that matters) and resize the windo verry 'thin'.
I think that should not happen in a beginners tutorial, maybe a min-width would be a easy 'fix'

Edit:
Yeah, the 'hoover' task
https://codelabs.developers.google.com/codelabs/flutter-boring-to-beautiful#6
should not work neighter, because of the flutter 2 syntax in the Lab code 
'const OutlinedCard({    Key? key, '

__Originally posted by @derKosi in https://github.com/flutter/codelabs/pull/816#issuecomment-1141915639__

**Comment by domesticmouse** [comment]
@khanhnwin do you want to mark this as fixed now?

**Comment by khanhnwin** [comment]
Once https://github.com/flutter/codelabs/pull/1037 gets merged, I think we're set to mark this issue as fixed!

**Comment by domesticmouse** [comment]
Marking as fixed as flutter/codelabs#1037 has landed
