### ISSUE TITLE
ACLs for GCS bucket for engine artifacts should be further restricted

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#105041]
We should restrict the ACLs to only automated bots.

Would have prevented https://github.com/flutter/flutter/issues/104387.

See internal go/flutter-dart-oom-retro for more context.

**Comment by godofredoc** [comment]
Blocked on codesigning implementation.

**Comment by ricardoamador** [comment]
@godofredoc @XilaiZhang any update?

**Comment by godofredoc** [comment]
The ACLs for individuals will be removed after the Aug 2023 release.

@itsjustkevin FYI

**Comment by godofredoc** [comment]
This is now complete.
