### ISSUE TITLE
print doesn't work in flutter apps on fuchsia

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#10509]

**Comment by Hixie** [comment]
A bisect letting us know when exactly this failed would be extremely helpful here.

**Comment by dabhaid** [comment]
Working at 09de6f79d
Not working at dcfcc9259

**Comment by eseidelGoogle** [comment]
@cbracken is looking.

**Comment by cbracken** [comment]
Should be fixed in c3721a589b50e3d2c2e56befbfd6f860d0de12a1
