### ISSUE TITLE
PageView not working properly with Stack

### ISSUE THREAD

**Issue by Nuke-101** [flutter/flutter#105092]
I am using a pageview widget inside stack and want to have 2nd page in pageview to be displayed first.

This is the hierarchy-

Stack
-Pageview
--Page1
--Page2
--Page3

I want Page2 to be on display when the app starts, but Page1 is on top.

I have a navigation bar which displays the correct page highlighted (Page2) but the pageview shows Page1. I have also specified initial index to 1 which is Page2 but the issue seems to arise.
Can anyone please help out with this....It worked previously but since i upgraded flutter 1 week earlier, it stopped working.
Should I downgrade or does this have any solution?

EDIT: I tried downgrading the version of flutter sdk and dart sdk as well, still the issue is persistent

**Comment by danagbemava-nc** [comment]
Hi @Nuke-101, thanks for filing the issue. 

Please provide a complete minimal reproducible code sample and the output of `flutter doctor -v`. 

Also, which version of flutter were you using where this was working for you?

**Comment by Nitingadhiya** [comment]
@Nuke-101 

As I understand your issue, I created something for you and maybe it's helpful for you. 
so Please check  below link. I've verified with stable Flutter version(3.0.1) / Dark SDK (2.17.1) and also with old Stable version (2.10.0).

https://gist.github.com/Nitingadhiya/697599cf2d7dc6f49ce5477604618a15

**Comment by Nuke-101** [comment]
> Hi @Nuke-101, thanks for filing the issue.
> 
> Please provide a complete minimal reproducible code sample and the output of `flutter doctor -v`.
> 
> Also, which version of flutter were you using where this was working for you?

HI @danagbemava-nc,
I was using flutter 2.10.5 when this was working and after i upgraded to flutter 3.0.0 this stopped working.
I reverted to flutter version 2.10.5 and it works again

This is the code-

import 'package:flutter/material.dart';

class StackPageView extends StatefulWidget {
  const StackPageView({Key? key}) : super(key: key);

  @override
  State<StackPageView> createState() => _StackPageViewState();
}

class _StackPageViewState extends State<StackPageView> {
  late PageController pageController;
  @override
  void initState() {
    pageController = PageController(initialPage: 1);
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      resizeToAvoidBottomInset: false,
      body: Stack(
        alignment: Alignment.bottomCenter,
        children: [
          PageView(
            physics: const BouncingScrollPhysics(),
            controller: pageController,
            scrollDirection: Axis.horizontal,
            children: [
              // ignore: avoid_unnecessary_containers
              Container(
                child: const Center(
                  child: Text("Page1"),
                ),
              ),
              // ignore: avoid_unnecessary_containers
              Container(
                child: const Center(
                  child: Text("Page2"),
                ),
              ),
              // ignore: avoid_unnecessary_containers
              Container(
                child: const Center(
                  child: Text("Page3"),
                ),
              ),
            ],
          ),
        ],
      ),
    );
  }

This is the current flutter doctor (where the code is working fine) just downgraded the flutter version from 3.0.0 to 2.10.5 no other changes made.

![Screenshot (34)](https://user-images.githubusercontent.com/61948729/171565112-20db55a9-f463-45ba-9716-dc1c4d282dc3.png)

**Comment by Nuke-101** [comment]
> @Nuke-101
> 
> As I understand your issue, I created something for you and maybe it's helpful for you. so Please check below link. I've verified with stable Flutter version(3.0.1) / Dark SDK (2.17.1) and also with old Stable version (2.10.0).
> 
> https://gist.github.com/Nitingadhiya/697599cf2d7dc6f49ce5477604618a15

Thankyou for this, i'll try it out and see if its working.

**Comment by danagbemava-nc** [comment]
Hi @Nitingadhiya, I run your sample on `flutter 3.0.1` and the first page is always Page 2 as expected. I tested on android, ios, web, and macOS and the results were the same in all cases.  

Is there any more information you can provide?

<details>
<summary>video</summary>

https://user-images.githubusercontent.com/88313112/171569129-0d0c3460-88d8-478f-b1b7-335a7e6f708c.mp4


</details>

<details>
<summary>complete sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const StackPageView(),
    );
  }
}


class StackPageView extends StatefulWidget {
  const StackPageView({Key? key}) : super(key: key);

  @override
  State<StackPageView> createState() => _StackPageViewState();
}

class _StackPageViewState extends State<StackPageView> {
  late PageController pageController;
  @override
  void initState() {
    pageController = PageController(initialPage: 1);
    super.initState();
  }


  @override
  Widget build(BuildContext context) {
    return Scaffold(
      resizeToAvoidBottomInset: false,
      body: Stack(
        alignment: Alignment.bottomCenter,
        children: [
          PageView(
            physics: const BouncingScrollPhysics(),
            controller: pageController,
            scrollDirection: Axis.horizontal,
            children: [
              // ignore: avoid_unnecessary_containers
              Container(
                child: const Center(
                  child: Text("Page1"),
                ),
              ),
              // ignore: avoid_unnecessary_containers
              Container(
                child: const Center(
                  child: Text("Page2"),
                ),
              ),
              // ignore: avoid_unnecessary_containers
              Container(
                child: const Center(
                  child: Text("Page3"),
                ),
              ),
            ],
          ),
        ],
      ),
    );
  }
}
```

</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.0.1, on macOS 12.3.1 21E258 darwin-arm, locale en-GB)
    • Flutter version 3.0.1 at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (13 days ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.67.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Connected device (3 available)
    • iPhone 13 (mobile) • DBB48503-41CE-4969-9043-3261726E438A • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-4 (simulator)
    • macOS (desktop)    • macos                                • darwin-arm64   • macOS 12.3.1 21E258 darwin-arm
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 102.0.5005.61

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>
