### ISSUE TITLE
`SkiaGpuObjectTest.UnrefResourceContextInTaskRunnerThread` failing

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#105066]
`SkiaGpuObjectTest.UnrefResourceContextInTaskRunnerThread` is failing after skia roll: https://github.com/flutter/engine/commit/1171115b664155d5c908f765a50d554f7926fc42

This has closed down the engine tree.

example failure:
https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20Unopt/5792/overview

error:
```
[1/562] SkiaGpuObjectTest.UnrefResourceContextInTaskRunnerThread (43 ms)
[0;33mNote: Google Test filter = SkiaGpuObjectTest.UnrefResourceContextInTaskRunnerThread
[m[0;32m[==========] [mRunning 1 test from 1 test suite.
[0;32m[----------] [mGlobal test environment set-up.
[0;32m[----------] [m1 test from SkiaGpuObjectTest
[0;32m[ RUN      ] [mSkiaGpuObjectTest.UnrefResourceContextInTaskRunnerThread
../../flutter/flow/skia_gpu_object_unittests.cc:158: Failure
Expected equality of these values:
  dtor_task_queue_id
    Which is: 0
  unref_task_runner()->GetTaskQueueId()
    Which is: 1
[0;31m[  FAILED  ] [mSkiaGpuObjectTest.UnrefResourceContextInTaskRunnerThread (1 ms)
```

**Comment by gaaclarke** [comment]
This test was introduced in https://github.com/flutter/engine/pull/32106 2 months ago (cc author @ColdPaleLight and reviewers @jason-simmons @dnfield)

**Comment by gaaclarke** [comment]
Tree is open again because it has been deflaked, dropping priority

**Comment by gaaclarke** [comment]
With a debug build the test doesn't flake in 1000 runs (example `for run in {1..1000}; do out/host_debug_unopt/flow_unittests --gtest_filter="*UnrefResourceContextInTaskRunnerThread*"; done`)

**Comment by dnfield** [comment]
How about if you use `cpulimit`? CI machines are a lot slower than ours.

**Comment by gaaclarke** [comment]
I think I found the problem, posting pr now.

**Comment by chinmaygarde** [comment]
The linked PR is closed. Can we disable or remove the test if we can't figure out what it does or fix it?

**Comment by gaaclarke** [comment]
I was able to assert that the order is happening the way we expected it.  It appears `fml::MessageLoop::GetCurrentTaskQueueId()` is not returning the value we expect.  Wether it's erroneous or not I haven't been able to establish yet.  (I hope it's an error in reporting the thread id and not an error in dispatching to the correct thread)

```diff
--- a/flow/skia_gpu_object_unittests.cc
+++ b/flow/skia_gpu_object_unittests.cc
@@ -25,7 +25,9 @@ class TestSkObject : public SkRefCnt {
   virtual ~TestSkObject() {
     if (dtor_task_queue_id_) {
       *dtor_task_queue_id_ = fml::MessageLoop::GetCurrentTaskQueueId();
+      printf("didit\n");
     }
+    printf("%zu\n", static_cast<size_t>(*dtor_task_queue_id_));
     latch_->Signal();
   }
 
@@ -154,6 +156,8 @@ TEST_F(SkiaGpuObjectTest, UnrefResourceContextInTaskRunnerThread) {
   // context in the task runner's thread.
   unref_queue = nullptr;
   latch->Wait();
+
+  printf("assert\n");
   // Verify that the resource context was destroyed in the task runner's thread.
   ASSERT_EQ(dtor_task_queue_id, unref_task_runner()->GetTaskQueueId());
 }
```

yields
```
didit
0
assert
```

**Comment by zanderso** [comment]
From triage. Closing as presumed fixed by the linked PR.
