### ISSUE TITLE
Have iOS SDK 10.3 available on the Chromium buildbots.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#10510]
The color correctness patches require migration to iOS SDK 10.3. We can still keep the iOS deployment target as 8.0 as the added code has version checks. The buildroot changes introduced in https://github.com/flutter/buildroot/pull/67 make our preference for 10.3 explicit. If 10.3 is not available on the bots (which it currently is not), the GN step on the bots will fail.

**Comment by cbracken** [comment]
To do:
1. Migrate to the non-deprecated version of `find_xcode.py` from the Chromium infra
1. Switch framework builds over to Xcode 8.3.x with SDK 10.3, deployment target iOS 8.
1. Ensure engine build specifies deployment target iOS 8.
1. Add `xcode-select` logic to engine build, using Xcode 8.3.x with SDK 10.3, deployment target iOS 8.

**Comment by cbracken** [comment]
Patch 1: Migrate to non-deprecated `find_xcode.py`: 
https://chromium-review.googlesource.com/c/525074/

**Comment by cbracken** [comment]
Filed a ticket to request installation of Xcode 8.3.3 on our bots:
https://bugs.chromium.org/p/chromium/issues/detail?id=730089

**Comment by cbracken** [comment]
Patch 2: Add `xcode-select` logic to engine build:
https://chromium-review.googlesource.com/526310

**Comment by cbracken** [comment]
Patch 3: Migrate framework builds to Xcode 8 build
https://chromium-review.googlesource.com/c/528364/

**Comment by cbracken** [comment]
Patch 4: Migrate engine builds to Xcode 8 build:
https://chromium-review.googlesource.com/c/527579/

**Comment by cbracken** [comment]
All builds updated to Xcode 8. Both engine and framework builds look happy.

**Comment by cbracken** [comment]
iOS CocoaPods-dependent tests disabled in:
https://chromium-review.googlesource.com/c/527819/

Re-enabled in:
https://chromium-review.googlesource.com/c/528648/

**Comment by cbracken** [comment]
The bots are now fully upgraded to macOS 10.12 and Xcode 8. Engine & Framework are using it, deployment target iOS 8 hasn't changed. As of #10591, the framework is using an Xcode 8-built engine and everything looks green. 

Calling this closed :)
