### ISSUE TITLE
Upgrading flutter on windows 7

### ISSUE THREAD

**Issue by PixelToast** [flutter/flutter#10516]
## Steps to Reproduce

1. Install git ( https://git-scm.com/download/win )
2. Set up Dart SDK using 3rd part installer, pub and dart appears to be working
3. Set up Android Studio
4. Clone flutter
5. Add flutter to path
6. Run `flutter`

## Logs

```C:\Users\Yaw\flutter\bin>flutter
Checking Dart SDK version...
Downloading Dart SDK 1.24.0-dev.3.0...
Unzipping Dart SDK...
Updating flutter tool...
The system cannot find the path specified.
Error: Unable to 'pub upgrade' flutter tool. Retrying...

Waiting for 0 seconds, press CTRL+C to quit ...
The system cannot find the path specified.
Error: Unable to 'pub upgrade' flutter tool. Retrying...

Waiting for 2 seconds, press CTRL+C to quit ...
Terminate batch job (Y/N)? Y

C:\Users\Yaw\flutter\bin>flutter -v
Updating flutter tool...
The system cannot find the path specified.
Error: Unable to 'pub upgrade' flutter tool. Retrying...

Waiting for 3 seconds, press CTRL+C to quit ...
Terminate batch job (Y/N)? Y
```

This appears to be caused by a bad variable substitution, a directory `bin/$cachePath` is created which contains the `dart-sdk` folder that should be in `bin/cache`

Moving `bin/$cachePath/dart-sdk` over to `bin/cache/dart-sdk` fixes the issue and flutter now works normally

**Comment by eseidelGoogle** [comment]
@goderbauer I wonder if the variable substitution inside quotes fails somehow on win7 powershell?  https://github.com/flutter/flutter/blob/master/bin/internal/update_dart_sdk.ps1#L49

**Comment by goderbauer** [comment]
@PixelToast What version of PowerShell do you have on your system? If you open PowerShell and execute `$PSVersionTable.PSVersion` it should tell you.

**Comment by goderbauer** [comment]
Closed due to no response.
