### ISSUE TITLE
How to download Dark SDK without powershell?

### ISSUE THREAD

**Issue by rabichawila** [flutter/flutter#105115]
Powershell is blocked by network admin, Therefore i'm getting this error when trying to run any flutter command ( `flutter doctor`  , `flutter pub upgrade` etc)

![image](https://user-images.githubusercontent.com/37574136/171391827-33c42caf-f3e0-47e1-98a2-7bc48a1a748a.png)

My question is: Is there any workaround this? without violating the policies :) 

NB: requesting network admin to change the permission is not an option.

**Comment by danagbemava-nc** [comment]
Hi @rabichawila, can you share the full verbose logs of the error you're receiving? 

As for workarounds, I'm not sure there are any.  Powershell is listed as a minimum requirement for the setup of flutter. Per the documentation in https://docs.flutter.dev/get-started/install/windows#system-requirements
