### ISSUE TITLE
Ensure that the raster cache rasterizes at the correct scale when the model plane intersects with the viewing plane in the presence of a perspective transform.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#10513]
Test bench described [in this comment](https://github.com/flutter/engine/pull/3717#issuecomment-305937491). Concerns [described here](https://github.com/flutter/engine/pull/3717#issuecomment-306108948).

**Comment by chinmaygarde** [comment]
cc @abarth

**Comment by zoechi** [comment]
Is this still relevant?

**Comment by chinmaygarde** [comment]
Yes.

**Comment by Hixie** [comment]
The raster cache is a legacy feature at this point (no plans on adding it to impeller) so I'm going to close this.
