### ISSUE TITLE
Does the Clipboard only support text type?

### ISSUE THREAD

**Issue by liuweibing7** [flutter/flutter#105197]
I need to watch the system clipboard on Windows and process the content, but I found it only supports `text/plain` type. Is there any plans to add other formats?

**Comment by huycozy** [comment]
Hi @liuweibing7, thanks for filing the issue. 
I see there's an open issue addressing the case you described.
Closing as duplicate of #23603, so please follow up on it for further updates.

**Comment by liuweibing7** [comment]
> Hi @liuweibing7, thanks for filing the issue. I see there's an open issue addressing the case you described. Closing as duplicate of #23603, so please follow up on it for further updates.

OK. Thanks
