### ISSUE TITLE
[macOS][Desktop]: App name does not change

### ISSUE THREAD

**Issue by XRayAdamo** [flutter/flutter#105157]
## Steps to Reproduce
I am trying to add macOs support to one of my projects. I have managed to complete everything, but one problem still exists. Application name remains as a project name. 

**Expected results:** 
App name should be Bundle Display Name
**Actual results:** 
Instead project name was used
<details>
I have created new empty project to show behavior.
This is info.plist
![image](https://user-images.githubusercontent.com/4430621/171471681-2a1703b7-4cba-46cf-941f-07bd0edd3e68.png)

As you can see I have changed Bundle name and display name, but here is what I am getting.
This is good

![image](https://user-images.githubusercontent.com/4430621/171471870-b7c6725a-41ed-4c82-9c5b-dae1e1e01f55.png)

But this is not

![image](https://user-images.githubusercontent.com/4430621/171471923-30221b0a-33c6-41f9-88ce-b0231782bc05.png)
Same in task list when you press Cmd+Tab

If I try to edit AppInfo file

![image](https://user-images.githubusercontent.com/4430621/171472276-f69d607a-0985-446a-a5c3-60a004d9bd34.png)

build will fail
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.1, on macOS 12.4 21F79 darwin-arm, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.67.2)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

• No issues found!
</details>

**Comment by darshankawar** [comment]
Thanks for the report. I verified this on latest stable (3.0.1) and confirmed the behavior. I looked for similar issues already filed and came across https://github.com/flutter/flutter/issues/41793 which was fixed and working for iOS.

According to that fix and [comment](https://github.com/flutter/flutter/issues/41793#issuecomment-624894279), `set the display name in General > Identity > Display Name` which seem to be available only for iOS as below:

<img width="615" alt="Screenshot 2022-06-02 at 11 14 05 AM" src="https://user-images.githubusercontent.com/67046386/171562943-7f95eebe-7f66-4432-b983-16e0f4fdb1a5.png">


But not for macOS:

<img width="583" alt="Screenshot 2022-06-02 at 11 26 38 AM" src="https://user-images.githubusercontent.com/67046386/171562995-a932816e-0b00-415e-b6fb-1bfea6fa801b.png">


Alternatively, changing the `Bundle Name` value as below changes the macOS app name, but doesn't update in the task bar as shown below:

<img width="778" alt="Screenshot 2022-06-02 at 11 31 16 AM" src="https://user-images.githubusercontent.com/67046386/171563246-867bda45-f694-4751-9e3c-ad923208f4c3.png">


<img width="243" alt="Screenshot 2022-06-02 at 11 12 23 AM" src="https://user-images.githubusercontent.com/67046386/171563270-2723a4db-edba-4421-8e11-2906af77ccce.png">


<img width="126" alt="Screenshot 2022-06-02 at 11 12 30 AM" src="https://user-images.githubusercontent.com/67046386/171563290-b051f1f2-c7a9-44cd-9a9d-25f0b0b5d285.png">


I also tried to change the `ProductName` as below, but it resulted in compile error:

<img width="812" alt="Screenshot 2022-06-02 at 11 37 04 AM" src="https://user-images.githubusercontent.com/67046386/171564539-62c882ab-2953-4c5a-be52-9659f028a52a.png">

<img width="596" alt="Screenshot 2022-06-02 at 11 37 58 AM" src="https://user-images.githubusercontent.com/67046386/171564576-006b119a-ef9c-4b30-bfb2-03441ea66263.png">


<details>
<summary> stable, master flutter doctor -v </summary>

```

[✓] Flutter (Channel unknown, 3.0.1, on macOS 12.2.1 21D62 darwin-x64, locale
    en-GB)
    • Flutter version 3.0.1 at /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository unknown
    • Framework revision fb57da5f94 (3 days ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.




```

</details>

**Comment by jmagman** [comment]
@cbracken

**Comment by jmagman** [comment]
`PRODUCT_NAME` gets set in AppInfo.xcconfig and is populated from the pubpsec.yaml. You should be able to manually override `PRODUCT_NAME` in build settings:
<img width="714" alt="Screen Shot 2022-06-02 at 9 56 44 AM" src="https://user-images.githubusercontent.com/682784/171683756-c4e5c662-ed0b-40e4-b1ff-d311246a2c78.png">

Or you can follow the instructions [in the docs](https://docs.flutter.dev/deployment/macos#configuring-the-apps-name-bundle-identifier-and-copyright) which says to edit AppInfo.xcconfig:

> The configuration for the product identifiers are centralized in macos/Runner/Configs/AppInfo.xcconfig. For the app’s name, set PRODUCT_NAME, for the copyright set PRODUCT_COPYRIGHT, and finally set PRODUCT_BUNDLE_IDENTIFIER for the app’s bundle identifier.



But `BUNDLE_NAME` is set to `PRODUCT_NAME` which gets used by Xcode to name the bridging header. And if you've already built with the old name, you get an error like:
```
Xcode/DerivedData/Runner-ctretxpfaeypegasfqwbmrjkizyw/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/Objects-normal/x86_64/This_Gallery-Swift.h: No such file or directory
```
I cleaned `Product > Clean Build Folder` which deleted the generated header, then built again so it generated the new one.  Then it ran with the new name:
<img width="148" alt="Screen Shot 2022-06-02 at 9 58 06 AM" src="https://user-images.githubusercontent.com/682784/171683957-0e5207d8-81f7-4526-88ec-b0d7012ac4e8.png">

There might be a real fix, but maybe the clean at least should be called out in the docs?

**Comment by jmagman** [comment]
@XRayAdamo can you confirm that editing `PRODUCT_NAME` in `AppInfo.xcconfig` then cleaning works? If you're building in Xcode it's `Product > Clean Build Folder`, if you're `flutter run`ing in the command line then it's `flutter clean`.

**Comment by XRayAdamo** [comment]
It does not work for me.
Steps:
1. Changed AppInfo
2. Clean build folder
3. Build and run
4. No errors but no change
5. Clean in Android Studio (flutter clean)
6. Build and run
7. Same result

![image](https://user-images.githubusercontent.com/4430621/171686937-7a675157-92ef-4d3e-8c1f-ff05b962c107.png)

**Comment by jmagman** [comment]
```
$ flutter create test_name
...
Your application code is in test_name/lib/main.dart.

Projects$ cd test_name
test_name$ flutter build macos

💪 Building with sound null safety 💪

Building macOS application...
$ open macos/Runner.xcworkspace
```
Edit `PRODUCT_NAME`
<img width="1239" alt="Screen Shot 2022-06-02 at 10 40 42 AM" src="https://user-images.githubusercontent.com/682784/171692341-1b2262e4-2574-49af-b457-8956498021b2.png">

Run in Xcode, and I see the updated name:
<img width="322" alt="Screen Shot 2022-06-02 at 10 41 24 AM" src="https://user-images.githubusercontent.com/682784/171692546-3196f37c-4168-4f02-82b5-b360f3372f70.png">
<img width="166" alt="Screen Shot 2022-06-02 at 10 41 19 AM" src="https://user-images.githubusercontent.com/682784/171692626-767d1c98-b5b7-417d-9f6a-2d4c5e3400b3.png">

What reproduction step am I missing?

**Comment by XRayAdamo** [comment]
I don't know. May be with new project it will work, but I have project created already and only recently added macos - so it does not work for me.

**Comment by XRayAdamo** [comment]
So, I have created test app and it does work for new app. Not working for old app, have no idea what is wrong :(

**Comment by jmagman** [comment]
> Changed AppInfo
> Clean build folder
> Build and run
> No errors but no change

After this step an you run `flutter clean` and then attach the results of `flutter build macos -v`? It will be large so you'll need to attach it. That will let me see all your build settings.

**Comment by XRayAdamo** [comment]
Also found this
![image](https://user-images.githubusercontent.com/4430621/171744331-e9e344ab-787b-4398-a55a-8ab9f6618c59.png)

**Comment by XRayAdamo** [comment]
Addition:
If I change product copyright it does applied properly
![image](https://user-images.githubusercontent.com/4430621/171749061-7c4fd07d-890c-420f-acb5-567139b470fe.png)

**Comment by XRayAdamo** [comment]
Long story short.
I have deleted macos folder and re-created macos 
Now everything is working properly. I will have to re-create all code in macos, but I have it saved.

**Comment by jmagman** [comment]
From those logs the product name was set to `export PRODUCT_NAME\=text_split_android` so that's what would be used by the app in the dock.  I'm not sure how you hard-coded that, it didn't come from Flutter...

**Comment by XRayAdamo** [comment]
I did not set it. It was probably from previous flutter version.

**Comment by jmagman** [comment]
Filed https://github.com/flutter/flutter/issues/105317 to track that the app won't build until a clean when the name changes.
