### ISSUE TITLE
mac-23 ios device is dead

### ISSUE THREAD

**Issue by yusuf-goog** [flutter/flutter#105172]
The device cannot be activated. Needs to be activated manually or replaced.

**Comment by yusuf-goog** [comment]
The ios device is unable to activate. Need to find a replacement device.

**Comment by yusuf-goog** [comment]
device replaced. it needs a new provisioning profile. @keyonghan can you fix the profile.

**Comment by keyonghan** [comment]
Profile updated, and the bot is back.
