### ISSUE TITLE
Wanting to downgrade to flutter 2

### ISSUE THREAD

**Issue by vandit2209** [flutter/flutter#105130]
Device: Macbook 
I want to downgrade to flutter 2 because I am trying to develop an app using agora and
> it is giving me a lot of errors while working with agora.
# My first try, downloaded the arm version 2.13 pre from flutter website and tried changing my path
my zshrc file `updated`
`export PATH="$PATH:/Users/USERNAME/development/flutter2/bin"`

results:
```
> which flutter
/Users/USERNAME/development/flutter/bin/flutter
```
`Notice there is not /flutter2`

# my second thought

uninstall flutter. But there is no guide to it.

Kindly help I am stuck.

**Comment by darshankawar** [comment]
@vandit2209 
Your question is better suited for support channels like Stackoverflow so please ask the same there.
See below similar SO links for your reference and check if they help.

https://stackoverflow.com/questions/59760735/how-do-you-uninstall-flutter-completely-and-properly-from-a-mac
https://stackoverflow.com/questions/64763870/how-to-uninstall-flutter-in-mac

Closing as this isn't a bug or feature request.
