### ISSUE TITLE
Android Studio flutter inspection not displaying fix suggestion

### ISSUE THREAD

**Issue by fuadreza** [flutter/flutter#105199]
Flutter Plugins version: 68.0.2
Android Studio version: 
```
Android Studio Chipmunk | 2021.2.1
Build #AI-212.5712.43.2112.8512546, built on April 28, 2022
Runtime version: 11.0.12+0-b1504.28-7817840 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.3.1
GC: G1 Young Generation, G1 Old Generation
Memory: 1280M
Cores: 8
Registry: external.system.auto.import.disabled=true
Non-Bundled Plugins: com.vermouthx.idea (1.13.1), manjaro.ptpb (1.6), Dart (212.5744), GrepConsole (12.12.211.6693.0), org.jetbrains.kotlin (212-1.6.21-release-334-AS5457.46), com.developerphil.adbidea (1.6.6), io.flutter (68.0.2)
```

## Steps to Reproduce

1. Create some state less class
<img width="442" alt="image" src="https://user-images.githubusercontent.com/25898509/171576420-a6823138-8d7c-4999-abc0-2b6eb8843f4e.png">

2. Move cursor to Error word (example: Key)
3. Open up suggestion by pressing (Option+return) on Mac

**Expected results:** 

Expected to see suggestion to import package

<img width="577" alt="image" src="https://user-images.githubusercontent.com/25898509/171577087-9d47eb12-6ec9-45a1-9122-5236c36e1406.png">

**Actual results:** 

<img width="487" alt="image" src="https://user-images.githubusercontent.com/25898509/171576970-5371c347-0674-49e0-9108-8acbdca80d71.png">

But, somehow it will fix itself if I wait for some times. I have not encountered this before I updated the flutter plugins.

Thanks in advance.

**Comment by danagbemava-nc** [comment]
Hi @fuadreza, issues with the flutter intellij plugin should be reported on their dedicated repo over on https://github.com/flutter/flutter-intellij. 

Closing from here as the intellij plugin has its own repo. 

Thank you
