### ISSUE TITLE
flutter/flutter main and master branches are out of sync, pointed to different commits

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#105159]
https://github.com/flutter/flutter/tree/master points to 38a2359, https://github.com/flutter/flutter/tree/main points to 3d62732 which is 11 commits and 14 hours behind.

**Comment by jmagman** [comment]
@keyonghan on-call

**Comment by godofredoc** [comment]
Updated the token and ran the failing workflows. Now main and master point to the same commit.
