### ISSUE TITLE
The plugin named Flutter_markdown has overlapping blockquotes in certain mobile browsers, such as Safari and Quark.

### ISSUE THREAD

**Issue by 2372281891** [flutter/flutter#105179]
The plugin named **Flutter_markdown** has overlapping blockquotes in certain mobile browsers, such as **Safari** and **Quark**.

[image](https://imgtu.com/i/XYcs0K)

**Comment by maheshmnj** [comment]
Hi @2372281891, Thanks for filing the issue. Please share a minimal and complete code sample along with the output of `flutter doctor -v` to investigate further.
