### ISSUE TITLE
Hot reload rejects deferred imports

### ISSUE THREAD

**Issue by dwelch91** [flutter/flutter#10515]
## Steps to Reproduce

Unsure how to independently reproduce this. I've been working part time on a small flutter app over the last couple of weeks and hot reloading was working well. Sometime in the past few days, hot reload stopped working with this error message (IDE console):

`Hot reload was rejected:
Reloading support for deferred loading has not yet been implemented: library 'package:flutter/src/widgets/placeholder.dart' has deferred import 'es'`

This occurs for any size code change - even a one word change that just changes the color of a widget.  

This occurs both in the IDE and command line:

```To hot reload your app on the fly, press "r". To restart the app entirely, press "R".
An Observatory debugger and profiler on Google Pixel, 7 1 0, API 25, 1080x1920 is available at: http://127.0.0.1:8100/
An Observatory debugger and profiler on iPhone 7 Plus is available at: http://127.0.0.1:8138/
For a more detailed help message, press "h". To quit, press "q".
Initializing hot reload...
Hot reload was rejected:
Reloading support for deferred loading has not yet been implemented: library 'package:flutter/src/widgets/placeholder.dart' has deferred import 'es'
Try again after fixing the above error(s).
```

I've checked the `placeholder.dart` file - there is no deferred import and no mention of `es` anywhere in the code. 

## Flutter Doctor

```
[✓] Flutter (on Mac OS X 10.11.6 15G1421, channel alpha)
    • Flutter at /Users/dwelch/git/flutter
    • Framework revision 973304d5fb (3 weeks ago), 2017-05-18 17:31:57 -0700
    • Engine revision f99d3ef108
    • Tools Dart version 1.23.0-dev.11.11

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at /Users/dwelch/android-sdk-macosx
    • Platform android-25, build-tools 25.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.2.1, Build version 8C1002
    • ios-deploy 1.9.1
    • CocoaPods version 1.2.1

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Gradle version 3.2
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.1.3)
    • Dart plugin version 171.4424.63
    • Flutter plugin version 13.1

[-] WebStorm (version 11.0.4)
    • Flutter plugin not installed; this adds Flutter specific functionality.
    • For information about managing plugins, see
      https://www.jetbrains.com/help/idea/managing-plugins.html

[✓] Connected devices
    • Google Pixel, 7 1 0, API 25, 1080x1920 • 192.168.59.101:5555                  • android-x86 • Android 7.1.1 (API 25)
    • iPhone 7 Plus                          • 7CACD369-1464-4CD1-9535-A6248DEF5E30 • ios         • iOS 10.2 (simulator)
```

**Comment by eseidelGoogle** [comment]
@a-siva or @tvolkert  may have theories.

**Comment by tvolkert** [comment]
> `library 'package:flutter/src/widgets/placeholder.dart' has deferred import 'es'`

... and yet it doesn't :-)

Out of curiosity, are there any deferred imports used in your app?

@Hixie

**Comment by dwelch91** [comment]
No, didn't even know what a deferred import was until I hit this error and starting Googling. :-)  My app is a pretty basic extension of the infinite scrolling demo on YouTube:  https://www.youtube.com/watch?v=F26pbGaSzfM&t=473s
I've added `http`, `sqflite`, `path_provider` and `timeago` libraries as dependencies - is it possible one of those is not behaving?

**Comment by eseidelGoogle** [comment]
I suspect it's coming from:
https://github.com/andresaraujo/timeago.dart/blob/master/lib/src/i18/messages_all.dart#L9

I don't know why the runtime is reporting the wrong file/line.  @a-siva might have theories.

**Comment by megamattron** [comment]
This is affecting me as well. Happy to provide any additional info to help track down the problem.

**Comment by Hixie** [comment]
We believe the problem is caused by using the "timeago" library (which uses deferred imports, which we don't support in Flutter), but the bug is in the VM (it should just ignore the deferrals and certainly shouldn't point to the wrong file). We should file a Dart SDK bug to track this.

**Comment by megamattron** [comment]
Ah, I am indeed using the timeago library. I wonder if I forked it and removed the deferred imports if that would fix the problem?

**Comment by Hixie** [comment]
Almost certainly.

**Comment by ride4sun** [comment]
have the same problem an I also use the timeago lib

**Comment by megamattron** [comment]
@ride4sun I made a fork of the timeago library that removes deferred library loading, you can use that to avoid this problem: https://github.com/larvalabs/timeago.dart

Here's how you reference it in pubspec.yaml:

```
  timeago:
    git: git://github.com/larvalabs/timeago.dart.git
```

**Comment by ride4sun** [comment]
Works , thx a lot.

**Comment by zoechi** [comment]
The Dart VM issue dart-lang/sdk#26878

**Comment by mraleph** [comment]
I think this is outdated and should work now because deferred libraries are no longer supported by VM - so hot reload does not need any special support for them.
