### ISSUE TITLE
Remove handling of the Flutter splash screen

### ISSUE THREAD

**Issue by blasten** [flutter/flutter#105173]
Flutter splash screen are deprecated: https://docs.flutter.dev/development/ui/advanced/splash-screen#migrating-from-manifest--activity-defined-custom-splash-screens

There are a number of apps that add the metadata `io.flutter.embedding.android.SplashScreenDrawable` to AndroidManifest.xml in g3.

Recently, the logic that lookups the drawable in the embedding is causing some issues on Android T beta. 
See http://b/234598486, and http://b/231425885

This code can be removed from the engine assuming all 1P clients can be migrated.

**Comment by blasten** [comment]
cc @GaryQian

**Comment by Taym95** [comment]
Hi @blasten, I don't know if it is related to this issue, but adding custom splash screen to an activity(`LaunchTheme`) is not working anymore after removing `io.flutter.embedding.android.SplashScreenDrawable `, can you please point me to code responsible for that and I will try to help, thanks!

**Comment by khyati82** [comment]
@camsim99 - Has this been fixed and can this issue be closed?

**Comment by camsim99** [comment]
@khyati82 No, I am working on migrating people internal usages of it. After that, I'll discuss with my team a timeline for deleting it.

**Comment by camsim99** [comment]
Working on migrating internal usages which is blocking this, so lowering in priority for now.

**Comment by camsim99** [comment]
Un-assigning me for now as I am not actively working on this.
