### ISSUE TITLE
Enable `os_signpost` events for `Timeline` events

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#105253]
## description

iOS has support for `os_signpost`s which gives allows you to identify certain regions of activity inside of Instruments.  Dart appears to have [support for emitting os_signpost events](https://github.com/dart-lang/sdk/blob/main/runtime/vm/timeline_macos.cc), but there is no way I can determine to enable it for Flutter projects.

It is my understanding that `--trace-systrace` is supposed to turn them on, but they don't.

Ideally there should be a way to make sure they are enabled when launching from Instruments as well.  Typically this is done on iOS by caching the last arguments for launching the app from the command line.

## steps to reproduce
1) `flutter run --profile --trace-systrace`
1) attach Instruments to the running process
1) tap around the app to make it update

Notice that no "Points of interest" are generated.

## doctor
```
[✓] Flutter (Channel unknown, 3.1.0-0.0.pre.1072, on macOS 12.4 21F79
    darwin-x64, locale en-US)
    • Flutter version 3.1.0-0.0.pre.1072 at /Users/aaclarke/dev/flutter
    • Upstream repository unknown
    • Framework revision ff110fb958 (48 minutes ago), 2022-06-02 13:11:28 -0700
    • Engine revision 00a64bf4f2
    • Dart version 2.18.0 (build 2.18.0-163.0.dev)
    • DevTools version 2.13.1
```

## fixes
- [x] tool: https://github.com/flutter/flutter/pull/105321
- [x] engine: https://github.com/flutter/engine/pull/33889
- [ ] dart: https://github.com/dart-lang/sdk/issues/49178

**Comment by gaaclarke** [comment]
# Debug log

With the following patch there is a compilation error when compiling for ios.  So even though it seems like it might be only for macos, it does appear to be compiled.  It might however be that building the iOS engine is also building the macos engine.  That was the case in the past:
```diff
--- a/runtime/vm/timeline_macos.cc
+++ b/runtime/vm/timeline_macos.cc
@@ -5,6 +5,8 @@
 #include "vm/globals.h"
 #if defined(DART_HOST_OS_MACOS) && defined(SUPPORT_TIMELINE)
 
+#error hello!
+
```

I also ran an app with the following breakpoints on but they aren't hit (even with the --trace-systrace flag:
1) `dart::TimelineEventMacosRecorder::OnEvent`
1) `dart::TimelineEventMacosRecorder::TimelineEventMacosRecorder`

The symbols definitely exist in the iOS build:
```
aaclarke-macbookpro2:src aaclarke$ nm out/ios_debug_unopt/libFlutter.dylib | grep TimelineEventMacosRecorder
000000000217b5ec t __ZN4dart26TimelineEventMacosRecorder4SizeEv
000000000217b418 t __ZN4dart26TimelineEventMacosRecorder7OnEventEPNS_13TimelineEventE
000000000217b3cc t __ZN4dart26TimelineEventMacosRecorderC1Ev
000000000217b39c t __ZN4dart26TimelineEventMacosRecorderC2Ev
000000000217b404 t __ZN4dart26TimelineEventMacosRecorderD0Ev
000000000217b400 t __ZN4dart26TimelineEventMacosRecorderD1Ev
000000000217b3fc t __ZN4dart26TimelineEventMacosRecorderD2Ev
000000000217b5e0 t __ZNK4dart26TimelineEventMacosRecorder4nameEv
0000000003ce2d78 s __ZTVN4dart26TimelineEventMacosRecorderE
```

The timeline recorder is getting created [here](https://github.com/dart-lang/sdk/blob/3d1c991fcf7cc6ec0817fd040ffc045da5142571/runtime/vm/timeline.cc#L97), it looks like it's creating a `TimelineEventRingRecorder`.  It seems like `trace-systrace` should be turning on the `TimelineEventMacosRecorder`.

I put a print statement next to the creation of each recorder to see if the ring recorder was getting created when launching from the command line, or just xcode.  It is also creating the ring recorder which matches what we saw previously.

Looks like we need to run dart with either `--systrace_timeline` or `--timeline_recorder=systrace`.

It looks like the engine is referencing `--systrace_timeline` here: https://github.com/flutter/engine/blob/81e4b133ac07cc05ae32a7ccbce52f6e6ce0d449/runtime/dart_vm.cc#L104:L104.  It gets used later down in DartVM::DartVM, but `settings_.trace_systrace` is evaluating to false despite having used the `--trace-systrace` flag (launched from xcode or from the command-line).

---
With the following patch:
```diff
--- a/runtime/dart_vm.cc
+++ b/runtime/dart_vm.cc
@@ -393,6 +393,7 @@ DartVM::DartVM(std::shared_ptr<const DartVMData> vm_data,
                 fml::size(kDartEndlessTraceBufferArgs));
   }
 
+  printf("hey: %d\n", settings_.trace_systrace);
   if (settings_.trace_systrace) {
     PushBackAll(&args, kDartSystraceTraceBufferArgs,
                 fml::size(kDartSystraceTraceBufferArgs));
diff --git a/shell/common/switches.cc b/shell/common/switches.cc
index ebfcc08330..464734f768 100644
--- a/shell/common/switches.cc
+++ b/shell/common/switches.cc
@@ -334,6 +334,7 @@ Settings SettingsFromCommandLine(const fml::CommandLine& command_line) {
 
   settings.trace_systrace =
       command_line.HasOption(FlagForSwitch(Switch::TraceSystrace));
+  printf("ho %d\n", settings.trace_systrace);
 
   settings.skia_deterministic_rendering_on_cpu =
       command_line.HasOption(FlagForSwitch(Switch::SkiaDeterministicRendering));
```

Invoking with `run --trace-systrace`.

The following is printed:
```
ho 0
hey: 0
```

It seems like the flag is not working its way down from the tool to the engine.  The [documentation](https://github.com/gaaclarke/engine/blob/9f99d99628ee4a658f4fff206f588592278ed6b0/shell/common/switches.h#L162) for the `trace-systrace` flag claims it is only for android and fuchsia, so that might be why it is not being sent down.

Aha, [in android](https://github.com/flutter/flutter/blob/dc55ca640cbf70a970ca8d065cdd0a5845beaf8f/packages/flutter_tools/lib/src/android/android_device.dart#L646) we have a place where it is set as a flag, but it is missing for ios in https://github.com/flutter/flutter/blob/dc55ca640cbf70a970ca8d065cdd0a5845beaf8f/packages/flutter_tools/lib/src/ios/devices.dart#L352.  We should just have to add it there.

**Comment by jmagman** [comment]
@gaaclarke do we also need this for simulators?

**Comment by jmagman** [comment]
> I have a patch for this which I'm wrapping up. 

I didn't know you were already working on this, I put out https://github.com/flutter/flutter/pull/105321.
Want me to close it?

**Comment by gaaclarke** [comment]
I've tested it and it doesn't work yet.  I think that this is just the first step in the journey.  I'm not sure if the next blocker is in the framework repo or the engine repo.  It's probably easier just to let me drive the PR in case I need to add more changes to the framework.  I'll send the PR your way once I have everything working.

**Comment by gaaclarke** [comment]
I was able to test the PRs that pass down the flags, the value is getting sent down to the engine and that Dart is creating a `TimelineEventMacosRecorder`, yet the events are not showing up in Instruments.

When then launching the app from xcode, the `--trace-systrace` flag is not being saved and used when xcode is launched, since the `TimelineEventRingRecorder` is being created in that case.  It's hard to debug why the events aren't showing up until I get that working so I can launch with the debugger attached.

@jmagman I wondered if saving the flag was going to be an issue.  If you have a sec can you show me the mechanism in the tool that is saving parameters, like the local engine, that are then read when launching from xcode?

**Comment by gaaclarke** [comment]
Nevermind, i see it.  We are using environment variables: https://github.com/flutter/flutter/blob/889a15eb9df6961b9a4dc3bf751ff67cb54a2065/packages/flutter_tools/bin/xcode_backend.dart#L352

**Comment by gaaclarke** [comment]
Passing in `--trace-systrace` into the command line args of the xcode scheme will recreate the `--trace-systrace` flag's behavior.  There doesn't appear to be prior art for saving flags from the command line and using them in xcode like I had thought.  The local engine effects the build process and doesn't work through command-line flags like I had always thought.  I'm not sure how to best surface this to users.  The template xcode project could have the flag saved in it, but turned off.  An environment variable would be more idiomatic for xcode users probably...

**Comment by gaaclarke** [comment]
Okay so here is a list of all the outstanding problems:
1) The `--trace-systrace` flag isn't being passed down from the tool to the engine (jenn's PR addressed this)
1) There is no good way to specify `--trace-systrace` when launching the app from xcode.  You can specify launch arguments for your configuration.
1) There is no way to specify `--trace-systrace` when profiling the app from xcode.  This is important since attaching instruments after the fact can miss information about the start of the app.  If you use the workaround from the previous step, it messes up the splash screen that blocks the app if you try to launch a debug build from outside of xcode.
1) The documentation in the engine says ios doesn't support `--trace-systrace`
1) Even when you do pass the flag down to the engine and dart starts calling the os_signpost API, the signposts are not actually showing up in Instruments.  When I made the signposts plugin I ran into this where the events have to be the correct category for them to show up in instruments.  This will require a fix to dart.

**Comment by gaaclarke** [comment]
I filed an issue against dart that lists the problems on dart's side: https://github.com/dart-lang/sdk/issues/49178

**Comment by jmagman** [comment]
> 1) There is no good way to specify `--trace-systrace` when launching the app from xcode.  You can specify launch arguments for your configuration. This probably isn't that big of a deal.
> 1) There is no way to specify `--trace-systrace` when profiling the app from xcode.  This is important since attaching instruments after the fact can miss information about the start of the app.  If you use the workaround from the previous step, it messes up the splash screen that blocks the app if you try to launch a debug build from outside of xcode.

You can specify launch arguments for Profile specifically in the scheme if you uncheck `Use the Run action's arguments and environment variables`, then `Product > Profile` to launch from Instruments. 
<img width="927" alt="Screen Shot 2022-06-03 at 3 06 00 PM" src="https://user-images.githubusercontent.com/682784/171960403-5ddd5659-c11b-4848-b294-6862bc933b17.png">

You can swap the build configuration too if you want to use Instruments for debug or release mode.
<img width="937" alt="Screen Shot 2022-06-03 at 3 11 02 PM" src="https://user-images.githubusercontent.com/682784/171960935-ec1cc580-2ec9-4560-9ff4-944b461ace4f.png">

Does that work?

**Comment by gaaclarke** [comment]
> Does that work?

Yep, that works for getting it working with Debug builds.  It would be nice to have something a big more usable, but it's not the end of the world.  The problem I had with that though is that it was messing up with the jit gate for some reason when I went to try to profile the app.  I had that "Use the Run action's arguments..." thing selected so that might have got me in a weird state.  I didn't have a chance to debug it yet.

**Comment by gaaclarke** [comment]
closed since https://github.com/flutter/packages/pull/2157 landed and seems sufficient
