### ISSUE TITLE
Let a user skip the root warning in bin/flutter

### ISSUE THREAD

**Issue by kevmoo** [flutter/flutter#10529]
I'm trying to run some tools in Docker – having to handle the warning about running as `root` is a bit annoying.

Could I have an ENV variable that can silence this? (See my horrible bash script edit below)

```bash
# Test if running as superuser
if [[ "$EUID" == "0" && !dont_annoy_kevin ]]; then
  echo "   Woah! You appear to be trying to run flutter as root."
  echo "   We strongly recommend running the flutter tool without superuser privileges."
  echo "  /"
  echo "📎"
fi
```

**Comment by eseidelGoogle** [comment]
See also https://github.com/flutter/flutter/issues/9634.

**Comment by eseidelGoogle** [comment]
We've now spent way more time creating/maintaining this warning than I suspect it's saved us. :/

**Comment by Hixie** [comment]
Why are you running it as root?

**Comment by kevmoo** [comment]
I'm not. Docker is. By default.

...unless there is a way to run it as non-root that I'm not aware of...

**Comment by Hixie** [comment]
Well that's terrifying.

**Comment by kevmoo** [comment]
> Well that's terrifying.

ish...it is running in a container. 🤷‍♂️

**Comment by Hixie** [comment]
If you can reliably detect that you're in a docker instance, feel free to submit a PR that silences the warning in that case.

**Comment by kevmoo** [comment]
I was more interesting in just having an ENV variable – detecting that we're in docker may be more harry

**Comment by kevmoo** [comment]
> We've now spent way more time creating/maintaining this warning than I suspect it's saved us. :/

☝️

**Comment by Anyoks** [comment]
How do I not  run flutter as root? I simply do `flutter run` and i get the warning `We strongly recommend running the flutter tool without superuser privileges`. I don't know how to run flutter as a normal user but I want to. I get errors like:

 ` FileSystemException: FileSystemException: Cannot copy file /build/app/outputs/apk/app.apk' to app/outputs/apk/release/app-release.apk'  (OS Error: Permission denied, errno = 13)`

All my flutter files are owned by the normal user. My flutter is installed in `/home/orinamokaya/flutter/bin
`

How do I do it?(get flutter to run as a normal user?)

**Comment by zoechi** [comment]
@Anyoks you get this warning when you are logged in as root when you execute Flutter commands.

**Comment by Anyoks** [comment]
@zoechi  Logged in as root on the terminal? Hmm... when I run `whoami` i don't get the root user.

**Comment by Anyoks** [comment]
How then would I ensure that I am running it as a normal user in any case?

**Comment by zoechi** [comment]
> running the flutter tool without superuser privileges

I don't know the implementation or what it checks. 
If the user account you are using actually doesn't have superuser privileges, please create a new issue. This one is long closed.

> How then would I ensure that I am running it as a normal user in any case?

I don't even know what OS you're using, so hard to make suggestions. 
Basically don't log in as admin/root when you work with Flutter (or generally don't login as as admin/root at all)

**Comment by Anyoks** [comment]
@zoechi Sorry for the vague details. 
`Ubuntu 16.04`
So you suggest that I create a new non-admin user for flutter building... Let me try that

**Comment by zoechi** [comment]
It's generally adviced to not work as admin and use `su`/`sudo` or similar for commands/actions that need elevated permissions. Always working as root undermines Linux's and other OS's security.
