### ISSUE TITLE
SliverAnimatedList doc example bug

### ISSUE THREAD

**Issue by misterfourtytwo** [flutter/flutter#105251]
[SliverAnimatedList code example](https://api.flutter.dev/flutter/widgets/SliverAnimatedList-class.html) has a bug, where on removal, CardWidget is built with index of an item instead of actual removed object. Though AnimatedList example doesn't contain one.
![image](https://user-images.githubusercontent.com/17276509/171735219-bb607f89-f582-467a-8be7-9db86a2d4798.png)
![image](https://user-images.githubusercontent.com/17276509/171735257-2285405e-1106-40e5-9d6a-8c8738125878.png)

**Comment by danagbemava-nc** [comment]
Hi @misterfourtytwo, thanks for catching that. 

I can confirm that there is a bug in the example.

<details>
<summary>videos</summary>

| current example | fix proposed(from PR) | 
| -- | -- |
| <video src="https://user-images.githubusercontent.com/88313112/171808013-2995da0b-635c-4fb3-a96a-e14ea34297eb.mov" /> | <video src="https://user-images.githubusercontent.com/88313112/171808002-396e58e5-8d36-4289-ae66-06a008a3e7b4.mov" /> |

</details>

**Comment by misterfourtytwo** [comment]
https://github.com/flutter/flutter/pull/105252
i forgot to link PR from here. I'll write some simple tests later and then will wait for approval
