### ISSUE TITLE
flutter tool is turning echo off in the terminal in regular usage

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#105255]
After running `flutter run` and the app is quitting normally I'm not getting local echo on my terminal (I can't see what I'm typing).

`reset` will fix the issue.

Output before the echo is turned off:
```
Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

💪 Running with sound null safety 💪

An Observatory debugger and profiler on Aaron’s iPhone is available at: http://127.0.0.1:58590/KS8qMQD_RrI=/
The Flutter DevTools debugger and profiler on Aaron’s iPhone is available at:
http://127.0.0.1:9102?uri=http://127.0.0.1:58590/KS8qMQD_RrI=/

Application finished.
aaclarke-macbookpro2:counter aaclarke$ 
```

I'm not sure if it happens 100% of the time but it is happening at least most of the time for me.

doctor:
```
[✓] Flutter (Channel unknown, 3.1.0-0.0.pre.1072, on macOS 12.4 21F79 darwin-x64, locale en-US)
    • Flutter version 3.1.0-0.0.pre.1072 at /Users/aaclarke/dev/flutter
    • Upstream repository unknown
    • Framework revision ff110fb958 (2 hours ago), 2022-06-02 13:11:28 -0700
    • Engine revision 00a64bf4f2
    • Dart version 2.18.0 (build 2.18.0-163.0.dev)
    • DevTools version 2.13.1
```

cc @christopherfujino

**Comment by christopherfujino** [comment]
from discord chat, he was using the default macOS terminal

**Comment by ditman** [comment]
This is happening to me as well (GNOME Terminal 3.44.0 for GNOME 42): https://github.com/flutter/flutter/issues/105273

**Comment by christopherfujino** [comment]
Ohh, I can reproduce this if i hit `q`, but not with ctrl-c

**Comment by ditman** [comment]
It's very easy to reproduce with a web project: Close the Chrome window that opens with `flutter run -d chrome`. It doesn't happen with Ctrl+C.

**Comment by christopherfujino** [comment]
ok, this is definitely a regression, i'm bisecting now...

**Comment by christopherfujino** [comment]
git bisect says [86ab6d2bac78f32e23ae19619cf09484ecb4e14e](https://github.com/flutter/flutter/pull/105070)

**Comment by christopherfujino** [comment]
> git bisect says [86ab6d2bac78f32e23ae19619cf09484ecb4e14e](https://github.com/flutter/flutter/pull/105070)

out of those engine commits, I suspect the Dart roll: https://github.com/flutter/engine/pull/33722

Here's the dart git log: https://dart.googlesource.com/sdk.git/+log/d1ddf6fca6fe..b7b20478af70

Of which the obvious standout seems to be: https://dart.googlesource.com/sdk.git/+/83850ac5fa8cfd58a0dcbfe7103b6455a2a1d523

**Comment by christopherfujino** [comment]
It looks like the problem is that we handled setting this in the signal handler, but not when `q` is entered, and we relied on the fallback dart vm default restoration logic. now we need to explicitly set this all code paths.

**Comment by ditman** [comment]
Yikes! good find @christopherfujino! Thanks for getting a fix out for this so quickly!

**Comment by christopherfujino** [comment]
@ditman & @gaaclarke I merged a change that fixes this for me, would appreciate if you pull upstream and verify.

Notably, I couldn't reproduce this by sending ctrl-c, so if there's some race condition there my change won't have fixed that.

**Comment by ditman** [comment]
In my case, Ctrl+C was never a problem, only closing the browser manually. It now works as expected, thanks @christopherfujino!!
