### ISSUE TITLE
ListItem should have a background color

### ISSUE THREAD

**Issue by eseidel** [flutter/flutter#1052]
To make alternating lists easy.

It looks like the MD colors for backgrounds are defined in the themes:
https://www.google.com/design/spec/style/color.html#color-ui-color-application

The list spec itself doesn't seem to mention background colors, but it definitely uses them:
https://www.google.com/design/spec/components/lists.html#lists-specs

**Comment by abarth** [comment]
Why not just wrap the `ListItem` in a `Container` with the background color?

> but it definitely uses them

I think those images with alternating backgrounds are just to illustrate where the boundaries are between the list items so they can draw the metric lines.

**Comment by abarth** [comment]
I'm going to close this in favor just just using a container to add the background.
