### ISSUE TITLE
[flutter_tools] boolArg() should be non-nullable, and throw if the flag doesn't exist

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#105263]
https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/runner/flutter_command.dart#L1526

Discussion: https://github.com/flutter/flutter/pull/105242#discussion_r888395925

**Comment by christopherfujino** [comment]
WDYT @Jasguerrero ?

**Comment by Jasguerrero** [comment]
SGTM

**Comment by jmagman** [comment]
My comment from the discussion was:
> @Jasguerrero I keep running into this pattern. Can we make `boolArg` return a nonnull bool to simplify the code, and have it throw an exception (not `toolExit` since it's a developer error) if the flag doesn't exist?

Actually, I guess I'm essentially proposing going back to the old behavior from before https://github.com/flutter/flutter/issues/101595

> They make an assumption that the argument passed to them is valid therefore if the key is not found this methods raise an ArgumentError

That seems like the correct behavior in most cases?  The key isn't there, so it should throw.  There's no paper trail from https://github.com/flutter/flutter/issues/101595 to see what issue the proposed pattern was solving when the key wasn't present.

**Comment by christopherfujino** [comment]
From a discussion in discord:

- intArg is already deleted
- for stringArg we should throw an ArgumentError if it wasn't parsed
- for boolArg we should throw if it wasn't parsed and update the return type to bool
- for stringsArg we should throw if it wasn't parsed

**Comment by christopherfujino** [comment]
cc @bartekpacia
