### ISSUE TITLE
android_lifecycles_test has been failing for quite a while

### ISSUE THREAD

**Issue by yusuf-goog** [flutter/flutter#105237]
https://luci-milo.appspot.com/p/flutter/builders/staging/Linux_android%20android_lifecycles_test has been failing for a while: https://chromium-swarm.appspot.com/task?id=5b3d8f1ca0bdc710

**Comment by keyonghan** [comment]
This has caused staging bot to quarantine, and caused capacity issue: https://github.com/flutter/flutter/issues/108054
We will remove this test from CI.

**Comment by keyonghan** [comment]
Closing as obsolete.
