### ISSUE TITLE
[Windows build] Building the engine results in a flutter_windows.dll with missing entrypoint FlutterDesktopEngineReloadPlatformBrightness

### ISSUE THREAD

**Issue by 0xNF** [flutter/flutter#105297]
Having followed the build instructions located at  https://github.com/flutter/flutter/wiki/Compiling-the-engine I get what looks like a successful build of the engine, but the resulting `flutter_windows.dll` does not include `FlutterDesktopEngineReloadPlatformBrightness`, while the same, pre-built dll from official sources works fine.

**Comment by maheshmnj** [comment]
Hi @0xNF,  Can you please help me with the steps to reproduce the issue along with the output of `flutter doctor -v`?

**Comment by 0xNF** [comment]
Upon further inspection it seems that the `FlutterDesktopEngineReloadPlatformBrightness` set of APIs were removed recently with commit c4f583d1baaadaa3a65502382c4e3745d5e937d4. I guess this means I can't use the patched dlls as a drop-in replacement for a flutter app right now.
