### ISSUE TITLE
flutter doctor on german Windows cmd shows broken glyphs after upgrade

### ISSUE THREAD

**Issue by b-strauss** [flutter/flutter#10527]
![flutter_doctor](https://cloud.githubusercontent.com/assets/6588177/26832779/d00227d4-4ad0-11e7-9114-68e79a1acb60.png)

@goderbauer 

**update**:
this does not occur with powershell

**Comment by goderbauer** [comment]
@zanderso Were there any chances to the Dart VM between 1.24.0-dev.3.0 and 1.23.0-dev.11.11 that could have caused this regression?

I'll see if I can reproduce it on my System.

**Comment by goderbauer** [comment]
It still seems to work as expected on my system in CMD as well as PowerShell with the latest Flutter version. However, I am one Windows version behind yours (Version 10.0.14393) as cooperate IT doesn't allow me to install the Windows 10 Creator Update yet...

**Comment by b-strauss** [comment]
It works on my private machine. Maybe something went wrong during the upgrade process? I'll try it with a clean installation tomorrow.

**Comment by goderbauer** [comment]
Did you try restarting the CMD or Windows? I highly suspect that something just messed up the codepage configuration of your CMD session...

**Comment by b-strauss** [comment]
I think I tried restarting the CMD but I'm not sure. I'll check it tomorrow before I reinstall it.

**Comment by b-strauss** [comment]
This is still happening, even after I restarted Windows and CMD. I'll reinstall the sdk now.

**Comment by b-strauss** [comment]
Hmm, problem still persists:
```
[ÔêÜ] Flutter (on Microsoft Windows [Version 10.0.15063], locale de-DE, channel master)
    ÔÇó Flutter at D:\sdks\flutter
    ÔÇó Framework revision 1b56cb790c (8 hours ago), 2017-06-06 18:40:32 -0700
    ÔÇó Engine revision 8686a45810
    ÔÇó Tools Dart version 1.24.0-dev.3.0

[ÔêÜ] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    ÔÇó Android SDK at C:\Users\nbuser\AppData\Local\Android\sdk
    ÔÇó Platform android-25, build-tools 25.0.3
    ÔÇó ANDROID_HOME = C:\Users\nbuser\AppData\Local\Android\sdk
    ÔÇó Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    ÔÇó Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[ÔêÜ] Android Studio (version 2.3)
    ÔÇó Android Studio at C:\Program Files\Android\Android Studio
    ÔÇó Gradle version 3.2
    ÔÇó Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[ÔêÜ] IntelliJ IDEA Ultimate Edition (version 2017.1)
    ÔÇó Flutter plugin version 14.0
    ÔÇó Dart plugin version 171.4424.63

[ÔêÜ] Connected devices
    ÔÇó None
```

I don't know what the difference is to my private machine. Both are on the same Windows version.

**Comment by zanderso** [comment]
It looks like the Dart VM might be sending the right UTF-8 sequences to the console, but the console is not interpreting them correctly. What is the output of `chcp`?

**Comment by b-strauss** [comment]
```
chcp
Aktive Codepage: 850.
```

**Comment by b-strauss** [comment]
PowerShell also has `Aktive Codepage: 850.`, it's working there.

**Comment by goderbauer** [comment]
I am not seeing this on my system. @b-strauss Is this still an issue for you?

**Comment by b-strauss** [comment]
Yes this still happens, but I only have this problem on my work pc, not at home. Same Windows version.

**Comment by b-strauss** [comment]
I was able to solve this. There is an option in the console properties called "Use legacy console" which was checked for whatever reason. I unchecked it and it works now.

It looks like this:

![Windows console properties](https://www.top-password.com/blog/wp-content/uploads/2016/03/legacy-cmd-console.png)

**Comment by goderbauer** [comment]
Good to know! Thanks for posting back.
