### ISSUE TITLE
Exception: Release mode is not supported for ASUS Z00XS.

### ISSUE THREAD

**Issue by anderson155081** [flutter/flutter#105224]
It shows "Exception: Release mode is not supported for ASUS Z00XS." only when I run on this phone with release mode.
(ASUS Z00XS is running Android 5.0.)
It works fine on --debug mode and --verbose but can't run on release mode.
Is there any way I can fix it? or there's nothing I can do. 

## Steps to Reproduce
1. create new flutter project.
1. Execute `flutter run --release` on the code sample with ASUS Z00XS connect to computer.

**Expected results:** 
Run successfully.

**Actual results:** 
Exception: Release mode is not supported for ASUS Z00XS.

<details>
  <summary> Here are the Logs</summary>

[        ] Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
[        ] Use '--warning-mode all' to show the individual deprecation warnings.
[        ] See https://docs.gradle.org/6.7/userguide/command_line_interface.html#sec:command_line_warnings
[        ] BUILD SUCCESSFUL in 28s
[        ] 58 actionable tasks: 54 executed, 4 up-to-date
[ +397 ms] Running Gradle task 'assembleDebug'... (completed in 29.9s)
[  +58 ms] calculateSha: LocalDirectory: '/Users/chi-an/AndroidStudioProjects/nfd_case/build/app/outputs/flutter-apk'/app.apk
[ +614 ms] ✓  Built build/app/outputs/flutter-apk/app-debug.apk.
[   +3 ms] executing: /Users/chi-an/Library/Android/sdk/build-tools/30.0.3/aapt dump xmltree /Users/chi-an/AndroidStudioProjects/nfd_case/build/app/outputs/flutter-apk/app.apk AndroidManifest.xml
[  +83 ms] Exit code 0 from: /Users/chi-an/Library/Android/sdk/build-tools/30.0.3/aapt dump xmltree /Users/chi-an/AndroidStudioProjects/nfd_case/build/app/outputs/flutter-apk/app.apk AndroidManifest.xml
[        ] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1f
               A: android:compileSdkVersionCodename(0x01010573)="12" (Raw: "12")
               A: package="nfd.com.tw.nfd_case" (Raw: "nfd.com.tw.nfd_case")
               A: platformBuildVersionCode=(type 0x10)0x1f
               A: platformBuildVersionName=(type 0x10)0xc
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1f
               E: uses-permission (line=14)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: uses-permission (line=15)
                 A: android:name(0x01010003)="android.permission.WRITE_EXTERNAL_STORAGE" (Raw: "android.permission.WRITE_EXTERNAL_STORAGE")
               E: uses-permission (line=16)
                 A: android:name(0x01010003)="android.permission.READ_EXTERNAL_STORAGE" (Raw: "android.permission.READ_EXTERNAL_STORAGE")
               E: application (line=18)
                 A: android:label(0x01010001)="Lottery Number" (Raw: "Lottery Number")
                 A: android:icon(0x01010002)=@0x7f080001
                 A: android:name(0x01010003)="android.app.Application" (Raw: "android.app.Application")
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw: "androidx.core.app.CoreComponentFactory")
                 A: android:requestLegacyExternalStorage(0x01010603)=(type 0x12)0xffffffff
                 E: activity (line=25)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A: android:name(0x01010003)="nfd.com.tw.nfd_case.MainActivity" (Raw: "nfd.com.tw.nfd_case.MainActivity")
                   A: android:exported(0x01010010)=(type 0x12)0xffffffff
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x40003fb4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: meta-data (line=40)
                     A: android:name(0x01010003)="io.flutter.embedding.android.NormalTheme" (Raw: "io.flutter.embedding.android.NormalTheme")
                     A: android:resource(0x01010025)=@0x7f0a0001
                   E: intent-filter (line=44)
                     E: action (line=45)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=47)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw: "android.intent.category.LAUNCHER")
                 E: meta-data (line=54)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw: "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
                 E: uses-library (line=58)
                   A: android:name(0x01010003)="androidx.window.extensions" (Raw: "androidx.window.extensions")
                   A: android:required(0x0101028e)=(type 0x12)0x0
                 E: uses-library (line=61)
                   A: android:name(0x01010003)="androidx.window.sidecar" (Raw: "androidx.window.sidecar")
                   A: android:required(0x0101028e)=(type 0x12)0x0
[   +7 ms] Stopping app 'app.apk' on ASUS Z00XS.
[        ] executing: /Users/chi-an/Library/Android/sdk/platform-tools/adb -s FCAZFG00E135MRB shell am force-stop nfd.com.tw.nfd_case
[ +595 ms] executing: /Users/chi-an/Library/Android/sdk/platform-tools/adb -s FCAZFG00E135MRB shell pm list packages nfd.com.tw.nfd_case
[ +507 ms] Installing APK.
[   +4 ms] Installing build/app/outputs/flutter-apk/app.apk...
[        ] executing: /Users/chi-an/Library/Android/sdk/platform-tools/adb -s FCAZFG00E135MRB install -t -r /Users/chi-an/AndroidStudioProjects/nfd_case/build/app/outputs/flutter-apk/app.apk
[+22950 ms] Performing Push Install
                     /Users/chi-an/AndroidStudioProjects/nfd_case/build/app/outputs/flutter-apk/app.apk: 1 file pushed, 0 skipped. 4.1 MB/s (53710173 bytes in 12.408s)
                        pkg: /data/local/tmp/app.apk
                     Success
[   +1 ms] Installing build/app/outputs/flutter-apk/app.apk... (completed in 23.0s)
[   +3 ms] executing: /Users/chi-an/Library/Android/sdk/platform-tools/adb -s FCAZFG00E135MRB shell echo -n 3a6d7e61f0869170e768d532f54747b4b94026e1 > /data/local/tmp/sky.nfd.com.tw.nfd_case.sha1
[  +37 ms] executing: /Users/chi-an/Library/Android/sdk/platform-tools/adb -s FCAZFG00E135MRB shell -x logcat -v time -t 1
[  +35 ms] --------- beginning of main
           06-02 21:30:00.360 D/[UpdateService]( 1376): [isParsingDisabled] Retry interval is too short, parsing disabled: nfd.com.tw.nfd_case
[  +11 ms] executing: /Users/chi-an/Library/Android/sdk/platform-tools/adb -s FCAZFG00E135MRB shell am start -a android.intent.action.RUN -f 0x20000000 --ez enable-dart-profiling true --ez
enable-checked-mode true --ez verify-entry-points true nfd.com.tw.nfd_case/nfd.com.tw.nfd_case.MainActivity
[ +461 ms] Starting: Intent { act=android.intent.action.RUN flg=0x20000000 cmp=nfd.com.tw.nfd_case/.MainActivity (has extras) }
[   +1 ms] Waiting for observatory port to be available...
[+1508 ms] Observatory URL on device: http://127.0.0.1:48078/vqgnh3iKn9M=/
[   +1 ms] executing: /Users/chi-an/Library/Android/sdk/platform-tools/adb -s FCAZFG00E135MRB forward tcp:0 tcp:48078
[  +24 ms] 54254
[        ] Forwarded host port 54254 to device port 48078 for Observatory
[   +5 ms] Caching compiled dill
[  +45 ms] Connecting to service protocol: http://127.0.0.1:54254/vqgnh3iKn9M=/
[ +568 ms] Launching a Dart Developer Service (DDS) instance at http://127.0.0.1:0, connecting to VM service at http://127.0.0.1:54254/vqgnh3iKn9M=/.
[ +263 ms] DDS is listening at http://127.0.0.1:54259/HLl-cBiF00o=/.
[  +66 ms] Successfully connected to service protocol: http://127.0.0.1:54254/vqgnh3iKn9M=/
[ +108 ms] DevFS: Creating new filesystem on the device (null)
[  +60 ms] DevFS: Created new filesystem on the device (file:///data/data/nfd.com.tw.nfd_case/code_cache/nfd_casePVUKZE/nfd_case/)
[   +2 ms] Updating assets
[  +98 ms] Syncing files to device ASUS Z00XS...
[   +1 ms] <- reset
[        ] Compiling dart to kernel with 0 updated files
[        ] Processing bundle.
[        ] <- recompile package:nfd_case/main.dart 583d372b-c62d-44d8-9442-3a19258751d3
[        ] <- 583d372b-c62d-44d8-9442-3a19258751d3
[   +1 ms] Bundle processing done.
[ +150 ms] Updating files.
[        ] DevFS: Sync finished
[   +1 ms] Syncing files to device ASUS Z00XS... (completed in 155ms)
[        ] Synced 0.0MB.
[   +1 ms] <- accept
[   +9 ms] Connected to _flutterView/0xea723310.
[   +3 ms] Flutter run key commands.
[   +1 ms] r Hot reload. 🔥🔥🔥
[        ] R Hot restart.
[        ] h List all available interactive commands.
[        ] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[        ] q Quit (terminate the application on the device).
[        ] 💪 Running with sound null safety 💪
[        ] An Observatory debugger and profiler on ASUS Z00XS is available at: http://127.0.0.1:54259/HLl-cBiF00o=/
[+2069 ms] The Flutter DevTools debugger and profiler on ASUS Z00XS is available at: http://127.0.0.1:9100?uri=http://127.0.0.1:54259/HLl-cBiF00o=/

```
```

```
```

[✓] Flutter (Channel stable, 3.0.1, on macOS 12.3.1 21E258 darwin-x64, locale zh-Hant-TW)
    • Flutter version 3.0.1 at /Users/chi-an/Desktop/code/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (2 weeks ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/chi-an/Library/Android/sdk
    • Platform android-31, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] IntelliJ IDEA Community Edition (version 2021.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • ASUS Z00XS (mobile) • FCAZFG00E135MRB • android-x86    • Android 5.0 (API 21)
    • macOS (desktop)     • macos           • darwin-x64     • macOS 12.3.1 21E258 darwin-x64
    • Chrome (web)        • chrome          • web-javascript • Google Chrome 102.0.5005.61

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```
```

</details>

**Comment by jonahwilliams** [comment]
ASUS Z00XS is a 32bit x86 device, flutter only supports 64-bit x86 devices in release mode, as well as 32 and 64bit arm
