### ISSUE TITLE
Links with fragment identifiers are slightly out of view

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#10525]
Links on flutter.io with fragment are shown with the linked fragment scrolled slightly too far.

Repro:

1. Visit https://www.w3.org/TR/html4/intro/intro.html#fragment-uri. Notice that the page is scrolled so that '2.1.2 Fragment identifiers' is at the top of the page
1. Visit https://flutter.io/getting-started/#running-your-flutter-app. Notice that the top of the page has no title; if you scroll a bit op, 'Running your Flutter app' appears

![image](https://cloud.githubusercontent.com/assets/13644170/26829016/28bfa94e-4ac4-11e7-9b7d-84b837365642.png)

**Comment by mit-mit** [comment]
Would love help on this; tagging 'easy fix' (for someone with better html skills then myself)

**Comment by mit-mit** [comment]
I think maybe our "hovering" top banner is the cause of this; it looks like the heading might actually be at the top but just under the banner.

**Comment by sethladd** [comment]
Thanks for filing!

**Comment by gspencergoog** [comment]
Looks like this [stackoverflow answer](https://stackoverflow.com/questions/10732690/offsetting-an-html-anchor-to-adjust-for-fixed-header) might help with the solution, but I have no idea how to apply a class to all the headers with ids in markdown code: they don't currently have one, AFAICT.
