### ISSUE TITLE
[Desktop] didChangeAppLifecycleState does not reflect focus change

### ISSUE THREAD

**Issue by ltOgt** [flutter/flutter#105226]
I would expect to be able to use `didChangeAppLifecycleState` from `WidgetsBindingObserver` to detect focus change for flutter applications on Desktop platforms:

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
// This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: '', // TODO add title
      home: Scaffold(
        body: FocusObserver(),
      ),
    );
  }
}

class FocusObserver extends StatefulWidget {
  FocusObserver({Key? key}) : super(key: key);

  @override
  State<FocusObserver> createState() => _FocusObserverState();
}

class _FocusObserverState extends State<FocusObserver> with WidgetsBindingObserver {
  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    switch (state) {
      case AppLifecycleState.resumed:
        print("resume");
        break;
      case AppLifecycleState.inactive:
        print("inactive");
        break;
      case AppLifecycleState.paused:
        print("paused");
        break;
      case AppLifecycleState.detached:
        print("detached");
        break;
    }
  }

  @override
  Widget build(BuildContext context) {
    return Container();
  }
}

```

`didChangeAppLifecycleState` is never called on focus change / minimizing / ...

The documentation for [AppLifecycleState](https://api.flutter.dev/flutter/dart-ui/AppLifecycleState.html) only mentions `iOS` and `Android`.

Related to https://github.com/flutter/flutter/issues/103446#issuecomment-1125476654

**Comment by maheshmnj** [comment]
Hi @ltOgt, Flutter currently doesn't support LifeCycle events on the desktop, But there is an existing issue which is being tracked here https://github.com/flutter/flutter/issues/30735. 
Please follow up on that issue for further updates closing this issue as a duplicate.
