### ISSUE TITLE
Feature Request: Flutter should expose API to configure default windows size (Height, Width) cross platform

### ISSUE THREAD

**Issue by cnmade** [flutter/flutter#105286]
For cross platform app, we may want to set a different window size, with height and width for all platform(Windows, Linux, MacOS)
![Snipaste_2022-06-03_11-27-52](https://user-images.githubusercontent.com/278153/171781407-c492fdb6-6153-49a1-a4a0-10e5ff5b55e2.png)

I guess there should be a api expose for us to call when 
```dart
  runApp(MyApp());
```

**Comment by huycozy** [comment]
Hi, thanks for filing the issue. 
I see there are some issues that addressing the case you described, see #30736, #67708.
Closing as duplication, so please follow up on it for further updates.
