### ISSUE TITLE
No tests match regular expression "        test & exit /B 0".

### ISSUE THREAD

**Issue by DarkHeros09** [flutter/flutter#105365]
Hi 

vscode is having a problem running tests with a multi-line string description.

How to reproduce:

This will pass:
```dart
import 'package:flutter_test/flutter_test.dart';

void main() {
  testWidgets('''test''', (tester) async {});
}
```
This will not pass:
```dart
import 'package:flutter_test/flutter_test.dart';

void main() {

    testWidgets('''
        test
        ''', (tester) async {});

}
```

keep in mind that the later test will pass if run through void main.

```
[√] VS Code (version 1.67.2)
    • VS Code at C:\Users\m_ben\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.42.0
```

**Comment by darshankawar** [comment]
I verified this by running in Android Studio and it passes as below:

<img width="841" alt="Screenshot 2022-06-06 at 11 26 04 AM" src="https://user-images.githubusercontent.com/67046386/172103573-067b51c4-d511-4102-b42a-ce17f58917a5.png">


If this is specific to VSCode, please report it in dedicated repo: https://github.com/Dart-Code/Dart-Code/issues

Closing from here.
