### ISSUE TITLE
path_provider completely broken. Deprecates depending libraaries too. error GC9768DF9: Undefined name 'FOLDERID_printHood'.

### ISSUE THREAD

**Issue by AirAdmirer** [flutter/flutter#105377]
I've been trying to work with ```path_provider``` for a week now. I initially came to know of it through the ```hive_flutter``` package, which gave me constant errors while runtime, such as-

```
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_windows-2.1.0/lib/src/folders.dart:122:34: Error: Undefined name 'FOLDERID_printHood'.
  static String get printHood => FOLDERID_printHood;
                                 ^^^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_windows-2.1.0/lib/src/folders.dart:125:39: Error: Undefined name 'FOLDERID_printersFolder'.
  static String get printersFolder => FOLDERID_printersFolder;
                                      ^^^^^^^^^^^^^^^^^^^^^^^
```

I narrowed down this bug to one of the dependencies of ```hive_flutter```; ```path_provider```, and specifically ```path_provider_windows```. I tried countless methods to fix this like-

* Delete and redownload flutter sdk
* Run my project in another directory
* Running ```flutter clean ; flutter pub get``` everytime before running my app
* Changing my ```minskdversion``` to 21
etc.

Please help me through this. I don't see any reason for this specific error to be occuring. My flutter doctor is-

```
[√] Flutter (Channel stable, 3.0.1, on Microsoft Windows [Version 10.0.22000.675], locale en-IN)
[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.1.0)
[!] Android Studio (not installed)
[√] VS Code (version 1.67.2)
[√] Connected device (3 available)
[√] HTTP Host Availability
```

**Comment by stuartmorgan** [comment]
You are using old, incompatible versions of `path_provider_windows` and `win32`. You just need to `flutter pub upgrade` to update your transitive dependencies.

**Comment by AirAdmirer** [comment]
> You are using old, incompatible versions of `path_provider_windows` and `win32`. You just need to `flutter pub upgrade` to update your transitive dependencies.

I did, but it still gives me the same errors :/

**Comment by stuartmorgan** [comment]
Ah, I missed that the case is wrong on those constants. That's not what is [actually in the package](https://github.com/flutter/plugins/blob/main/packages/path_provider/path_provider_windows/lib/src/folders.dart#L122-L125).

So the actual issue here is that you edited files in your pub cache and now they are wrong. You need to fix them, or delete your pub cache to get fresh copies.

You should never, ever edit files in your pub cache.

**Comment by AirAdmirer** [comment]
Oh! Must have happened when I was refactoring some functions. My bad.
Thanks!
