### ISSUE TITLE
flutter_tools: src/base/version.dart – explain why not pkg/pub_semver

### ISSUE THREAD

**Issue by kevmoo** [flutter/flutter#10536]
Not clear here why this is duplicated – although it seems copied.

At a minimum, it'd be nice if this file explained why it's not pub_semver.

**Comment by Hixie** [comment]
Can you elaborate?

cc @devoncarew @tvolkert

**Comment by tvolkert** [comment]
You're saying https://pub.dartlang.org/packages/pub_semver provides the same functionality and would allow us to not reinvent it?  If that's true, SGTM, modulo the fact that we're trying to decrease our external dependencies, not increase them.  I assume `pub_semver` is a lightweight package?  (side-note: why is "pub" in the package name?)

**Comment by kevmoo** [comment]
semver is totally ordered – there is some vagueness when you add plusses – `pub_semver` establishes rules there which are not to spec (but provide unambiguous results)

...otherwise, what @tvolkert said. Less duplication is good. Fewer dependencies is also good.

I figured (at a minimum) it might be useful to tell folks, etc etc

**Comment by devoncarew** [comment]
I _believe_ we can use it for parsing this that are not well formed semver versions. So, some versions from the android sdk? From the unit tests, we can parse things like `1`, `1.0`, ..., which I think the semver parsers would throw on?

**Comment by kevmoo** [comment]
Crash? I believe so, yes.

I was wondering why the "standard" dart semver package wasn't being used. Others might as well.

Not a biggy.
