### ISSUE TITLE
navigation pop while zooming on a marker 

### ISSUE THREAD

**Issue by guns28** [flutter/flutter#105301]
i have a google maps when i zoom out and click on a pin i have a view showing with navigation button but if i click on a button while the map is still zooming i navigate and go back to the map again. 

is anyone have an idea of what could be happening ? 

thx.

**Comment by exaby73** [comment]
Hi @guns28, please provide a [minimal, reproducible example][1] and the output of `flutter doctor -v`.

[1]: https://stackoverflow.com/help/minimal-reproducible-example
