### ISSUE TITLE
[tool_crash] String: <57 characters>

### ISSUE THREAD

**Issue by original-one** [flutter/flutter#105300]
## Command
```
flutter run --profile
```

## Steps to Reproduce
1. flutter run --profile on android 5.1 API 22
2. Oops; flutter has exited unexpectedly: "failed to connect to http://127.0.0.1:56101/NFZt9u9joGE=/".

## Logs
String: <57 characters>
```

```
```
[✓] Flutter (Channel stable, 3.0.0, on Microsoft Windows [Version 10.0.19044.1706], locale en-US)
    • Flutter version 3.0.0 at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ee4e09cce0 (3 weeks ago), 2022-05-09 16:45:18 -0700
    • Engine revision d1b9a6938a
    • Dart version 2.17.0
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at C:\Users\ammar\AppData\Local\Android\Sdk
    • Platform android-32, build-tools 32.0.0
    • ANDROID_HOME = C:\Users\ammar\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✗] Visual Studio - develop for Windows
    ✗ Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[✓] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[✓] Connected device (4 available)
    • SM N900 (mobile)  • 340424e4705831e9 • android-arm    • Android 5.0 (API 21)
    • Windows (desktop) • windows          • windows-x64    • Microsoft Windows [Version 10.0.19044.1706]
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 102.0.5005.63
    • Edge (web)        • edge             • web-javascript • Microsoft Edge 102.0.1245.30

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 0.1.1+3
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 1d9032c7e1d867f071f2277eb1673e8f9b0274e3
### Plugins
cloud_firestore-3.1.17
cloud_firestore_web-2.6.16
connectivity_plus-2.3.2
connectivity_plus_linux-1.3.1
connectivity_plus_macos-1.2.2
connectivity_plus_web-1.2.1
connectivity_plus_windows-1.2.2
firebase_auth-3.3.19
firebase_auth_web-3.3.16
firebase_core-1.17.1
firebase_core_web-1.6.4
firebase_crashlytics-2.8.1
firebase_dynamic_links-4.2.5
firebase_messaging-11.4.1
firebase_messaging_web-2.4.1
flutter_facebook_auth-4.3.4
flutter_facebook_auth_web-3.1.2
flutter_local_notifications-9.5.3+1
flutter_plugin_android_lifecycle-2.0.6
flutter_sound_lite-8.5.0
flutter_sound_web-8.5.0
fluttertoast-8.0.9
google_sign_in-5.3.2
google_sign_in_android-5.2.8
google_sign_in_ios-5.3.1
google_sign_in_web-0.10.1+2
image_picker-0.8.5+3
image_picker_android-0.8.4+13
image_picker_for_web-2.1.8
image_picker_ios-0.8.5+5
package_info_plus-1.4.2
package_info_plus_linux-1.0.5
package_info_plus_macos-1.3.0
package_info_plus_web-1.0.5
package_info_plus_windows-1.0.5
path_provider-2.0.10
path_provider_android-2.0.14
path_provider_ios-2.0.9
path_provider_linux-2.1.7
path_provider_macos-2.0.6
path_provider_windows-2.0.7
permission_handler-9.2.0
permission_handler_android-9.0.2+1
permission_handler_apple-9.0.4
permission_handler_windows-0.1.0
share_plus-4.0.6
share_plus_linux-3.0.0
share_plus_macos-3.0.1
share_plus_web-3.0.0
share_plus_windows-3.0.0
sign_in_with_apple-4.0.0
sign_in_with_apple_web-1.0.1
sqflite-2.0.2+1
url_launcher-6.0.20
url_launcher_android-6.0.17
url_launcher_ios-6.0.17
url_launcher_linux-3.0.1
url_launcher_macos-3.0.1
url_launcher_web-2.0.11
url_launcher_windows-3.0.1

**Comment by exaby73** [comment]
Hello @original-one. I see you're using an older version of Flutter `3.0.0`. Please upgrade to the latest version `3.0.1` and confirm if this issue persists there as well.

**Comment by original-one** [comment]
> Hello @original-one. Can you please provide the logs of `flutter run --profile -v`?

Thank you, the issue is resolved

**Comment by exaby73** [comment]
@original-one Could you provide information on how you resolved the issue so that anyone else having this issue would also be able to find a solution?

**Comment by original-one** [comment]
> @original-one Could you provide information on how you resolved the issue so that anyone else having this issue would also be able to find a solution?

I just upgraded Flutter to latest version and then restarted Android Studio.
