### ISSUE TITLE
[flutter_image] avoid using deprecated APIs in image_provider.

### ISSUE THREAD

**Issue by cyanglaz** [flutter/flutter#105336]
Several methods in image_provider has been deprecated in https://github.com/flutter/flutter/commit/8d2978af642176f1e292edacc19d1a134fa3669f
These methods were used in flutter_image.

To make CI happy, we temporarily ignored the deprecation warning in `flutter_image`. We should migrate `flutter_image` to the new APIs after the [commit](https://github.com/flutter/flutter/commit/8d2978af642176f1e292edacc19d1a134fa3669f) lands on flutter/stable.

**Comment by cyanglaz** [comment]
cc @jonahwilliams

**Comment by jonahwilliams** [comment]
> the new APIs as early as possible.

You should probably not migrate _as early_ as possible, in the event we end up reverting in google3. I would wait at least another week.

**Comment by cyanglaz** [comment]
> > the new APIs as early as possible.
> 
> You should probably not migrate _as early_ as possible, in the event we end up reverting in google3. I would wait at least another week.

Yeah I meant migrate as early as possible after this commit lands in stable. Let me update the description to make it more clear.
