### ISSUE TITLE
Plugins that only support one Platform currently need dummy boilerplate for the other platform

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#10530]
It is totally possible to have plugins that only make sense on one of the supported platforms (e.g. a Plugin that launches an Android Intent doesn't make sense on iOS). Users might want to still use these plugins in their cross-platform app (and guard calls to them with `platform.isAndroid`). Currently, the only way to make this work is to include a lot of boilerplate dummy code in your plugin for the platform your plugin is not supporting to make the Flutter build system happy. It would be better if Flutter could detect that a plugin dependency is e.g. Android only (for example by realizing that the plugin is missing an iOS subdirectory) and if that's the case Flutter should stop including that plugin in the generated platform registry for the unsupported platforms.

/cc @mehmetf who ran into this with the Android-only android_intent plugin
/cc @mit-mit and @mravn-google for opinions

**Comment by mit-mit** [comment]
Agree we should fix this; see also https://github.com/flutter/flutter/issues/10288 which should enable this

**Comment by mit-mit** [comment]
We need to fix this prior to 4; we are already seeing plugins published that look like they support both platforms but really only support one. We have to fix that or we get a polluted ecosystem.

**Comment by Hixie** [comment]
Leaving this in the current milestone because this is important plugins framework maintenance work.

**Comment by mit-mit** [comment]
Postponing to milestone 4.

**Comment by stuartmorgan** [comment]
This was resolved a while ago; plugins can have arbitrary subsets of platforms now.
