### ISSUE TITLE
How to run flutter app on start of the phone?

### ISSUE THREAD

**Issue by richard457** [flutter/flutter#105385]
I checked this https://stackoverflow.com/questions/6391902/how-do-i-start-my-app-when-the-phone-starts-on-android but I wanted a flutter native way to achieve this.

**Comment by darshankawar** [comment]
@richard457 
Your question or use case isn't clear and there's no supporting information provided. I suggest you to use flutter new issue template and fill out requested details so that we'll have enough details to work with.

Closing for now.
