### ISSUE TITLE
Datetimepicker Needed

### ISSUE THREAD

**Issue by KunjKanani** [flutter/flutter#105356]
### It will help in many use cases like meeting timing

I show this type of widget for datetimepicker. Is there any way to achieve this using flutter?

![unnamed](https://user-images.githubusercontent.com/64889177/171995762-4a159d0c-5005-41c6-9b5f-20a5c9822701.jpg)

**Comment by darshankawar** [comment]
@KunjKanani 
You can search for community plugins on `pub.dev` to check if there are any plugins already which offers this feature. See https://pub.dev/packages/flutter_datetime_picker as one such example.

Closing from here. You may ask the same question on support channels like StackOverflow for existing solutions too.
