### ISSUE TITLE
Honor orientation EXIF flag for images on Android

### ISSUE THREAD

**Issue by pcomans** [flutter/flutter#10533]
## Steps to Reproduce

Create an Image widget with a source image that has the orientation flag in its EXIF parameters set.
Example:
```
new Image.network(
              "https://www.dropbox.com/s/owrunurvdq20r25/20170606_111821_HDR.jpg?dl=1",
              fit: BoxFit.scaleDown
          )
```
What should happen: The image should appear in portrait, since the orientation is Orientation: 6 (Rotated 90° CCW).
What happens instead: The image appears in landscape, as if there was no orientation flag.
## Logs
None

## Flutter Doctor
[✓] Flutter (on Mac OS X 10.12.5 16F73, channel alpha)
    • Flutter at /Users/philipp/code/flutter
    • Framework revision 973304d5fb (3 weeks ago), 2017-05-18 17:31:57 -0700
    • Engine revision f99d3ef108
    • Tools Dart version 1.23.0-dev.11.11

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at /Users/philipp/Library/Android/sdk
    • Platform android-25, build-tools 25.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[-] iOS toolchain - develop for iOS devices (Xcode 8.3.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3.3, Build version 8E3004b
    • ios-deploy 1.9.1
    ✗ CocoaPods installed but not initialized.
        CocoaPods is used to retrieve the iOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work on iOS.
        For more info, see https://flutter.io/platform-plugins
      To initialize CocoaPods, run:
        pod setup
      once to finalize CocoaPods' installation.

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Gradle version 3.2
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.1.3)
    • Dart plugin version 171.4424.63
    • Flutter plugin version 14.0

[✓] Connected devices
    • LGUS991   • LGUS99168d23625                      • android-arm • Android 6.0 (API 23)
    • iPhone SE • B42ADC67-E52E-43A9-A3B1-B5AC81D7E2F9 • ios         • iOS 10.3 (simulator)

**Comment by eseidelGoogle** [comment]
Unclear if we need to do this by exposing APIs to dart:ui or if we can do this from dart alone.

**Comment by Hixie** [comment]
We should definitely make sure this is consistent across platforms, and we should probably honour the flag everywhere.

**Comment by jason-simmons** [comment]
The Skia JPEG codec has an EXIF parser that reads the orientation tag.  But it doesn't apply the orientation to the image:
    https://bugs.chromium.org/p/skia/issues/detail?id=3834
    https://bugs.chromium.org/p/skia/issues/detail?id=1592

**Comment by Hixie** [comment]
If we don't do this in the new few months, we'll never be able to do it, because it's a breaking change.

**Comment by zoechi** [comment]
Seems to be working.
I investigate this issue because thumbnails (created using Firebase could functions) were shown with wrong orientation while the original image was shown correctly. It turned out that the thumbnails are created without exif information.

**Comment by mit-mit** [comment]
I cannot repro this in beta either. @Hixie shall we close this out?

**Comment by Hixie** [comment]
Sure!

**Comment by MichaelSowah** [comment]
I am using the camera plugin and after taking the picture, I convert to base64 and send to my servers but when previewed on my server the image on the server comes 90 degrees clockwise rotated, so instead of portrait image of my face I get landscape image of my face. how do I fix this? 

I just noticed the exif data is lost before getting to the server which is causing me problems now and it has practically become a block for my project. is there any workaround to fixing this.

this is what I do before sending the image to my server

`imageFile = new File(widget.previewImagePath);
    imageBytes = imageFile.readAsBytesSync();
    visitorImage = base64.encode(imageBytes);`

**Comment by jonasbark** [comment]
This actually still seems to happen on one of our test device, namely:

- Huawei P8 Lite (Model number hi6210sft): Android 5.0
- Huawei P8 Lite (Model number ALE-L21): Android 6.0

The failing image: https://uffldatar853t51.azureedge.net/uploads/279fd9e290ed3d8dc9c42cf1414fb266d3b05a4664b2c9b64e0ae05c9ca6d3b0.jpg

This is rotated correctly on all (about 20) of our phones, including iOS devices. The image is loaded via Image.network with BoxFit.cover inside a Container with a fixed height of 200.

Correct: 
![ok2](https://user-images.githubusercontent.com/1151304/41419311-fed9892a-6ff1-11e8-939f-b182601f6408.png)

Incorrect:
![ok](https://user-images.githubusercontent.com/1151304/41419324-06157f14-6ff2-11e8-8d67-2eb58339c159.png)

So not only the orientation is wrong - the placement inside the Container is as well.

`[✓] Flutter (Channel master, v0.5.2-pre.42, on Mac OS X 10.13.5 17F77, locale de-DE)
    • Flutter version 0.5.2-pre.42 at /Users/boni/Documents/Programmieren/Dart/flutter
    • Framework revision 4cd5870ece (13 days ago), 2018-06-01 15:57:01 -0700
    • Engine revision 6cef519598
    • Dart version 2.0.0-dev.59.0.flutter-1a185867a9
`

**Comment by zoechi** [comment]
@jonasbark probably better to create a new issue

**Comment by rcagantas** [comment]
Was there a new ticket for this?

**Comment by eseidelGoogle** [comment]
There are several exif related bugs on file:
https://github.com/flutter/flutter/issues/20431
https://github.com/flutter/flutter/issues/24575
https://github.com/flutter/flutter/issues/12921
https://github.com/flutter/flutter/issues/24574
https://github.com/flutter/flutter/issues/18391
https://github.com/flutter/flutter/issues/19458

**Comment by eseidelGoogle** [comment]
https://stackoverflow.com/questions/47528440/invalid-image-metadata-when-try-to-display-a-livephoto-with-phlivephotoview-obje might be related?

**Comment by eseidelGoogle** [comment]
Here is some related code copying over exif: https://github.com/piemonte/PBJVision/blob/master/Source/PBJVision.m#L1595

**Comment by eseidelGoogle** [comment]
https://developer.android.com/reference/android/hardware/camera2/CameraCaptureSession.CaptureCallback.html#onCaptureCompleted(android.hardware.camera2.CameraCaptureSession,%20android.hardware.camera2.CaptureRequest,%20android.hardware.camera2.TotalCaptureResult) looks like possibly the right hook on Android to grab (and copy over) the image meta data into the preview image captured.
