### ISSUE TITLE
Allow `FlutterViewController` to be initialized with a `FlutterEngine` to support add-to-app host injecting running engine

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#105347]
For iOS the `FlutterViewController` is presented with a running `flutterEngine` in the host app:
```objc
    FlutterEngine *flutterEngine =
        ((AppDelegate *)UIApplication.sharedApplication.delegate).flutterEngine;
    FlutterViewController *flutterViewController =
        [[FlutterViewController alloc] initWithEngine:flutterEngine nibName:nil bundle:nil];
    [self presentViewController:flutterViewController animated:YES completion:nil];
````
https://docs.flutter.dev/development/add-to-app/ios/add-flutter-screen?tab=engine-swift-tab#show-a-flutterviewcontroller-with-your-flutterengine

See also sample https://github.com/flutter/samples/blob/e3b51bb17f887ee97c0b10ead68f9d3fef063da0/add_to_app/prebuilt_module/ios_using_prebuilt_module/IOSUsingPrebuiltModule/ViewController.swift#L46

Expose `-[FlutterViewController initWithEngine::]` for macOS:
https://github.com/flutter/engine/blob/bbc9bd899d704c8f27225010973f8c246d3a523e/shell/platform/darwin/macos/framework/Source/FlutterViewController_Internal.h#L35-L37

Make this code work:
```swift
  func openFlutterApp() {
    guard
      let contentViewController = NSApplication.shared.keyWindow?.contentViewController
    else { return }

    let flutterViewController = FlutterViewController(
      engine: flutterDependencies.flutterEngine, // THIS DOESN'T EXIST
      nibName: nil,
      bundle: nil)
    flutterViewController.view.setFrameSize(NSMakeSize(500, 500))
    contentViewController.presentAsModalWindow(flutterViewController)
  }
```

**Comment by dubik** [comment]
Please make it possible to keep the engine running regardless of whether the view is displayed.

**Comment by jmagman** [comment]
Closing in favor of https://github.com/flutter/flutter/issues/74735
