### ISSUE TITLE
How to integrate go_router with seo_renderer?

### ISSUE THREAD

**Issue by o7planning** [flutter/flutter#105360]
I am using go_router for my project. Recently I wanted to integrate seo_renderer into my project.
   https://pub.dev/packages/seo_renderer
However, the examples show that these 2 libraries are not compatible with each other.

```
// seo_renderer:
runApp(
  RobotDetector(
    debug: true, // you can set true to enable robot mode
    child: MaterialApp(
      home: MyApp(),
      navigatorObservers: [seoRouteObserver],
    ),
  ),
);

// go_router
final _router = GoRouter(
  observers: [seoRouteObserver],  // NOT WORK!!
  routes: [ ...]
);
 
MaterialApp.router(
   routeInformationParser: _router.routeInformationParser,
   routerDelegate: _router.routerDelegate,
  title: 'GoRouter Example',
);
```
Can you help me with such an example?

**Comment by darshankawar** [comment]
Please ask support questions on stackoverflow or flutter's reddit help page.
You may also reach out to `seo_renderer` plugin owner for solution.
Closing from here.

**Comment by o7planning** [comment]
Thanks, luckily I solved the problem.
