### ISSUE TITLE
Scrolling on macOS disables gesture interaction

### ISSUE THREAD

**Issue by guidezpl** [flutter/flutter#105308]
It's possible this affects other platforms.

On web, one can scroll and interact with elements below
- cursor is correct
- interactions (e.g. clicks) are registered

e.g. https://api.flutter.dev/flutter/widgets/ListView-class.html

On macOS, when scrolling:
- cursor is incorrect
- disables interactions

e.g. below, I am scrolling and clicking

 https://user-images.githubusercontent.com/6655696/171866063-a235c20b-1faa-4316-a739-f01dfccc32c2.mp4

**Comment by HansMuller** [comment]
Test case?

**Comment by guidezpl** [comment]
Not sure if there is one, but I confirmed this was working with `2.13.0-0.4.pre` and `flutter run -d macos lib/widgets/scroll_view/listview_select.1.dart`

**Comment by jason-simmons** [comment]
This behavior change is related to a series of patches that added trackpad gesture support to the engine and framework
(see https://github.com/flutter/engine/commit/e470a96d58ca109c5c8af667b3566861d9288691 and https://github.com/flutter/flutter/commit/30a501801af7b4aa8d12eb5fd5a71d0cd88f8d2c)

**Comment by Piinks** [comment]
(Triage) FYI @dkwingsmt

**Comment by guidezpl** [comment]
>  Probably the scroll content shouldn't be locked-out if the scroll originated from a trackpad (ScrollActivity.shouldIgnorePointer).

+1. Scrolling with a trackpad feels broken at the moment, because the page now needs to be at a complete standstill for other gestures to be recognized

**Comment by knopp** [comment]
Even on mobile it doesn't feel right. Native apps (at least on iOS) don't disable interaction completely during scrolling. When shipping mobile app I always used something like [this](https://github.com/knopp/flutter/commit/826304ec531530837174c581d167dde04d9b349c) to reenable interaction at the end of scrolling.
