### ISSUE TITLE
Confusing error message when using tryParse with onChanged in a TextFormField

### ISSUE THREAD

**Issue by Strain-solutions** [flutter/flutter#105366]
Hi, I think this is pretty minor, but it threw me for an hour or so.  There are a few things interacting so I will try to explain each step.

I have a TextFormField with a number type keyboard.  

In the onChanged callback, I use tryParse to convert the text to an int.  Because text can be null, tryParse requires the ! operator

Now if the user types in some numbers and then deletes all to them tryParse throws a null check error.  Now this seems fair enough since the text in the onChanged call back is empty.  However, it is not null it is ""  

However, if you try to put a null check into the logic, the compiler knows that the text in onChanged can't be null and so will flag it as not necessary and ignore it (which is technically correct.... I think).

```dart
   onChanged: (text){`
        if(text !=null){          // <= (1)`
            int.tryParse(text)!
    }
```

The check in (1) is ignored as it is deemed necessary, but the resulting error is that a null check operator was used on a null value.  This leaves the dev is left in a weird position that the error reported is that a null value has been passed, but the fix for it is invalid.   Eventually, I worked out that it works if you check that text is not ""
``` dart
onChanged: (text){`
          if(text !=""){          // <= This fixes the null check error`
     int.tryParse(text)!
    }
```

As i say, I don't think this is a bug per se, but the error reported doesn't help fix the issue.

**Comment by maheshmnj** [comment]
Hi @Strain-solutions, Thanks for filing the issue. Please share the output of `flutter doctor -v` along with the minimal and complete code sample and the error logs.
