### ISSUE TITLE
HttpClient sends invalid extension during TLS Client Hello causing failed connection to server

### ISSUE THREAD

**Issue by Programatic** [flutter/flutter#105381]
## Steps to Reproduce

1. Execute `dart run example.dart` on the code sample 
2. Press Button
3. See error in debug output

**Expected results:**
Request successfully goes through

**Actual results:**
Error fails with error 
```
I/flutter (29677): Error HandshakeException: Handshake error in client (OS Error:
I/flutter (29677): 	TLSV1_ALERT_DECODE_ERROR(tls_record.cc:594))
```

<details>
<summary>Code sample</summary>

```dart
import 'dart:io';

void main() async {
  HttpClient client = HttpClient();
  Uri url = Uri.parse("https://10.0.0.224:8888/");
  try {
    await client.postUrl(url);
  } catch (error) {
    print("Error $error");
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```
Error HandshakeException: Handshake error in client (OS Error:
	TLSV1_ALERT_DECODE_ERROR(tls_record.cc:594))
```

```
[✓] Flutter (Channel master, 3.1.0-0.0.pre.1099, on Arch Linux
    5.18.1-arch1-1, locale en_US.UTF-8)
    • Flutter version 3.1.0-0.0.pre.1099 at /opt/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 0895130e51 (28 hours ago), 2022-06-03
      16:43:11 -0700
    • Engine revision 76a1567841
    • Dart version 2.18.0 (build 2.18.0-165.0.dev)
    • DevTools version 2.14.0

[✓] Android toolchain - develop for Android devices (Android SDK
    version 32.1.0-rc1)
    • Android SDK at /home/ford/Android/Sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.3+7)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at
    google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome
      executable.

[✓] Linux toolchain - develop for Linux desktop
    • clang version 13.0.1
    • cmake version 3.23.2
    • ninja version 1.11.0
    • pkg-config version 1.8.0

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit
      https://flutter.dev/docs/get-started/install/linux#android-setu
      p for detailed instructions).

[✓] Connected device (2 available)
    • SM G975U (mobile) • R38M30FGMGE • android-arm64 • Android 12
      (API 31)
    • Linux (desktop)   • linux       • linux-x64     • Arch Linux
      5.18.1-arch1-1

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.
```

</details>

Currently, my server is using axum-server with rustls in order to create a backend for my application. In doing so, I only have an ip to connect with. However, using wireshark we can decode the TLSv1.2 Client Hello packet that the flutter application is sending.
![image](https://user-images.githubusercontent.com/41210901/172034650-79078c85-fd00-48a3-83cd-ce93426d7b60.png)
Specifically what we see here is that the HttpClient is sending a server_name extension. While this traditionally would serve to increase security, the way it is represented with the uri is a bug. 10.0.0.224 is clearly not a hostname, but instead an ip. Furthermore, according [to the ietf rfc, an ip is a distinct thing from a hostname and "Literal IPv4 and IPv6 addresses are not permitted in 'HostName'."](https://datatracker.ietf.org/doc/html/rfc6066). As a result, [when the server goes to decode the host name](https://github.com/rustls/rustls/blob/main/rustls/src/msgs/handshake.rs#L268), it fails to get a DnsNameRef. If we reply this packet with only the hostname changed to the hext of a string, such as 'google.com', then the connection succeeds. 

EDIT: Changed quote from RFC to more proper RFC as well as simplifying code. Thanks simolus3!

**Comment by darshankawar** [comment]
@Programatic 
Looking at the error `TLSV1_ALERT_DECODE_ERROR`, it could be related to your server using the latest TLSV version which Flutter may not be supporting.

Also, I suggest you to file this issue in dedicated repo : https://github.com/dart-lang/io/issues

Closing from here. If you get redirected here mentioning this could be specific to flutter itself, write in comments and I'll reopen it.
