### ISSUE TITLE
[path_provider] A way to get the current user's cache directory on desktop

### ISSUE THREAD

**Issue by cachapa** [flutter/flutter#105386]
## Use case

Out app can potentially download a lot of media to show locally. We cache this data locally to avoid unnecessary round-trips.
We try to store the data in a platform-standard cache directory so that it can be cleared by the system e.g. when the system is running out of space.

On Linux the proper place to store the data would be in the user's `~/.cache` directory, but there's currently no way to retrieve it from `path_provider`.
I believe there are equivalent directories on macOS (`~/Library/Caches`?) and Windows (`%LOCALAPPDATA%`?).

The closest candidate is `getTemporaryDirectory()` which (on my Linux system) returns `/tmp`, potentially exposing the user's data in multiuser systems.

## Proposal

A new method called `getApplicationCacheDirectory()` analogous to the Android-only `getExternalCacheDirectories()`.
That method could also return the first result of `getExternalCacheDirectories()` on Android, since it seems to always point to the current user's `/sdcard/android/data/$app_id/cache`.

Note: I'm willing to do this work for Linux and Android but I wanted to discuss it before starting the effort.

**Comment by tomekit** [comment]
`/tmp` is isolated per application for quite a while at least on Debian/Ubuntu. 
I believe it would be still way better practice to use: `~/.cache` instead.

On my side on Ubuntu 22.10 it isn't even possible to use the: `getTemporaryDirectory()` as it fails with:
`Directory listing failed, path = '/tmp/systemd-private-c7768a176cd6400eade59b377bdff460-fwupd.service-jTW0hW' (OS Error: Permission denied, errno = 13)`

**Comment by jpnurmi** [comment]
To highlight the problem on Linux, run the [cached_network_image](https://pub.dev/packages/cached_network_image) example first as user A and then as user B:
```
PathAccessException: Cannot open file, path = '/tmp/libCachedImageData/dc555ac0-23b8-11ee-8203-690c79df21e0.jpg' (OS Error: Permission denied, errno = 13)
Another exception was thrown: PathAccessException: Cannot open file, path =
'/tmp/libCachedImageData/dc555ac0-23b8-11ee-8203-690c79df21e0.jpg' (OS Error: Permission denied, errno = 13)
flutter: CacheManager: Failed to download file from https://notAvalid.uri with error:
ClientException with SocketException: Failed host lookup: 'notavalid.uri' (OS Error: No address associated with hostname, errno = -5), uri=https://notavalid.uri
flutter: CacheManager: Failed to download file from https://via.placeholder.com/300x150 with error:
PathAccessException: Cannot open file, path = '/tmp/libCachedImageData/dc854460-23b8-11ee-8203-690c79df21e0.png' (OS Error: Permission denied, errno = 13)
flutter: CacheManager: Failed to download file from https://via.placeholder.com/200x150 with error:
PathAccessException: Cannot open file, path = '/tmp/libCachedImageData/dc854461-23b8-11ee-8203-690c79df21e0.png' (OS Error: Permission denied, errno = 13)
flutter: CacheManager: Failed to download file from https://via.placeholder.com/350x200 with error:
PathAccessException: Cannot open file, path = '/tmp/libCachedImageData/dc854462-23b8-11ee-8203-690c79df21e0.png' (OS Error: Permission denied, errno = 13)
Another exception was thrown: PathAccessException: Cannot open file, path =
'/tmp/libCachedImageData/dc854461-23b8-11ee-8203-690c79df21e0.png' (OS Error: Permission denied, errno = 13)
flutter: CacheManager: Failed to download file from https://via.placeholder.com/350x150 with error:
PathAccessException: Cannot open file, path = '/tmp/libCachedImageData/dc856b70-23b8-11ee-8203-690c79df21e0.png' (OS Error: Permission denied, errno = 13)
flutter: CacheManager: Failed to download file from https://via.placeholder.com/300x300 with error:
PathAccessException: Cannot open file, path = '/tmp/libCachedImageData/dc856b71-23b8-11ee-8203-690c79df21e0.png' (OS Error: Permission denied, errno = 13)
Another exception was thrown: PathAccessException: Cannot open file, path =
'/tmp/libCachedImageData/dc856b70-23b8-11ee-8203-690c79df21e0.png' (OS Error: Permission denied, errno = 13)
Another exception was thrown: PathAccessException: Cannot open file, path =
'/tmp/libCachedImageData/dc856b71-23b8-11ee-8203-690c79df21e0.png' (OS Error: Permission denied, errno = 13)
```
