### ISSUE TITLE
windows dart-only plugin doesn't work correctly (possibly due to web plugin?)

### ISSUE THREAD

**Issue by matanshukry** [flutter/flutter#105367]
## Steps to Reproduce

1. Clone the repo: https://github.com/matanshukry/flutter_google_places_sdk ( https://github.com/matanshukry/flutter_google_places_sdk/tree/windows branch )
2. Switch to `windows` branch
3. Go to the front-facing/example directory: `cd flutter_google_places_sdk/example/`
4. Run the app in windows: `flutter run -d windows`

**Expected results:**
App should run using the web implementation.

**Actual results:**
App starts and immediately throws this exception:
```
flutter: FlutterGooglePlacesSdk::_ensureInitialized error: MissingPluginException(No implementation found for method initialize on channel plugins.msh.com/flutter_google_places_sdk)
flutter: FlutterGooglePlacesSdk::call error: MissingPluginException(No implementation found for method initialize on channel plugins.msh.com/flutter_google_places_sdk)
```

# Reason ?
Tried to look a bit more into it, and I see the web code calls `RegisterPlugins`, but the generated file and method only calls the web plugin:

```
import 'package:flutter_google_places_sdk_web/flutter_google_places_sdk_web.dart';

import 'package:flutter_web_plugins/flutter_web_plugins.dart';

// ignore: public_member_api_docs
void registerPlugins(Registrar registrar) {
  FlutterGooglePlacesSdkWebPlugin.registerWith(registrar);
  registrar.registerMessageHandler();
}
```

Note: to clarify, the web implementation is a dart-only implementation.

**Comment by stuartmorgan** [comment]
Your Windows implementation is missing the `implements` entry (see https://docs.flutter.dev/development/packages-and-plugins/developing-packages#federated-platform-packages); if you're missing that Dart plugin registration isn't enabled for desktop platforms (unless the plugin requires Flutter 3.0 or later).

**Comment by matanshukry** [comment]
@stuartmorgan perhaps I'm missing something on my side again, but that doesn't seem to work either.

The doc says implements should be for the front-facing package (`flutter_google_places_sdk` in my case), so I tried that and pushed - still the same.

The word `implements` makes me think it should be the platform interface package though, so I tried that too - still nothing.
