### ISSUE TITLE
Beta Test Xcode released June 2022

### ISSUE THREAD

**Issue by nuritzi** [flutter/flutter#105337]
There are issues we will need to work through once the Xcode beta is out, but we may not know what that will be until it's out. 

As a first step, we should run the beta somewhere to see what tests break.

Should this be in a staging pool?

**Comment by nuritzi** [comment]
@godofredoc @zanderso what's the best way to proceed with testing the beta once it's out? 

cc/ @jmagman

**Comment by ppunj25** [comment]
- [ ] 1. > _**NEED TO HIRE FOR 5 CORPORATE COMPANIES, THEY PAY $400,000/annum.
- [ ] 2. > contact:- +91 8076511364
- [ ] 3. > **ppunj25@gmail.com****_

**Comment by jmagman** [comment]
I'll make the cipd package once I verify it's mostly working locally.  Xcode is usually a crashy mess for a few betas so it may be a month or so after it's released before it makes sense to put it in infra to run tests against.

**Comment by ppunj25** [comment]
I HAVE ALL THE NAMES AND PICTURES OF MEDICINES IN MY EXCEL SHEET MOSTLY
SOLD IN SOUTH DELHI.

FROM NOW WHAT OTHER REQUIREMENTS I NEED TO PROVIDE YOU TO BUILD 1 APP?
I WANT SUBSCRIPTION SERVICE TOO IN MY APP.

WISHING YOU TO GET BACK SOON I WANT TO START ASAP.
I HAVE A CAPITAL BUDGET OF $4000

THANKS
PRANAV PUNJ
+91 8076511364

**Comment by nuritzi** [comment]
> There are issues we will need to work through once the Xcode beta is out, but we may not know what that will be until it's out.
> 
> As a first step, we should run the beta somewhere to see what tests break.
> 
> Should this be in a staging pool?

FYI -- per Godofredo: we'll prepare capacity to run both engine and flutter tests on staging

**Comment by jmagman** [comment]
I'm going to wait until beta 2 is out to make the cipd package.
