### ISSUE TITLE
[webview_flutter] getting webview_flutter_wkwebview error when uploading the application to the appstoreconnect

### ISSUE THREAD

**Issue by husbycodereis** [flutter/flutter#105499]
The flutter app successfully gets archived for a new release but at the last step of the upload process in xcode, the error message below shows up.

The app references non-public selectors in Payload/Runner.app/Frameworks/webview_flutter_wkwebview.framework/webview_flutter_wkwebview: estimatedProgress, initWithFrame:configuration:, isMainFrame, setNavigationDelegate:, userContentController, websiteDataStore With error code STATE_ERROR.VALIDATION_ERROR.50 for id a440e713-5fb0-40a0-a323-dbd12001884a

![Screen Shot 2022-06-07 at 08 35 01](https://user-images.githubusercontent.com/63356401/172303614-402eed2d-91db-4ea7-af84-798f2af434aa.png)

webview_flutter version:  
 webview_flutter: ^3.0.4

pubspec.lock:
 webview_flutter:
    dependency: "direct main"
    description:
      name: webview_flutter
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.0.2"
  webview_flutter_android:
    dependency: transitive
    description:
      name: webview_flutter_android
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.8.10"
  webview_flutter_platform_interface:
    dependency: transitive
    description:
      name: webview_flutter_platform_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.9.1"
  webview_flutter_wkwebview:
    dependency: transitive
    description:
      name: webview_flutter_wkwebview
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.8.0"

Podfile.lock: 
- webview_flutter_wkwebview (0.0.1):
    - Flutter

**Comment by paulocoutinhox** [comment]
Hi,

Message from Apple: "The issue has been resolved on the app validation backend. Please try resubmitting. Sorry for the trouble."

Thanks.

**Comment by husbycodereis** [comment]
thank you so much! 

it is fixed indeed. Now the app has successfully been uploaded to appstoreconnect.

Closing the issue

**Comment by maheshmnj** [comment]
Hi @paulocoutinhox, Thanks for filing the issue and for the update probably that was an issue on the end of the apple's end. Glad its resolved. 

Closing based on the above response.
