### ISSUE TITLE
Transition after the back button tap is not done with the current StatefulComponent

### ISSUE THREAD

**Issue by a14n** [flutter/flutter#1054]
The following code show the issue. Basically there are 2 widgets:
- `App`: the landing page where you can click a button to navigate to the second page
- `Action`: a StatefulComponent where you can tap on the text "tap here" to change its state

After tapping on "tap here" to change the initial state you go back. during the transition you should see that the state is not the modified one but a state that suggests that a new `Action` is used as initial display for the transition (actually `config` has changed).

I'm not sure if this is an expected behaviour but it looks strange. Could you confirm this is a bug or not ?

```dart
import 'package:flutter/material.dart';

class App extends StatelessComponent {
  App();

  Widget build(BuildContext context) {
    return new Scaffold(
        toolBar: new ToolBar(center: new Text('Title')),
        body: new Container(),
        floatingActionButton: new FloatingActionButton(onPressed: () {
          Navigator.pushNamed(context, '/action');
        }, child: new Icon(icon: 'content/add')));
  }
}

class Action extends StatefulComponent {
  bool flag = false;
  Action();
  _ActionState createState() => new _ActionState();
}

class _ActionState extends State<Action> {
  void initState() {
    super.initState();
    print('initState');
  }

  Widget build(BuildContext context) {
    print('flag:${config.flag}');
    if (config.flag) {
      return new Scaffold(
          toolBar: new ToolBar(center: new Text('Action ${config.flag}')),
          body: new Container());
    } else {
      return new Scaffold(
          toolBar: new ToolBar(center: new Text('Action ${config.flag}')),
          body: new GestureDetector(onTap: () {
            setState(() {
              config.flag = true;
            });
          }, child: new Text('tap here')));
    }
  }
}

void main() {
  runApp(new MaterialApp(
      title: 'Test back button',
      routes: {
        '/': (RouteArguments args) => new App(),
        '/action': (RouteArguments args) => new Action(),
      }));
}
```

**Comment by a14n** [comment]
PS: I'm on alpha branch (commit 9487197502b5fcbe14a6b2de91ed51b95f5297d5)

**Comment by abarth** [comment]
> Could you confirm this is a bug or not ?

This behavior is expected.

Subclasses of `Widget`, including subclasses of `StatefulComponent`, are intended to be immutable objects.  When you write `config.flag = true;`, you're mutating a `Widget`, which can cause surprising behavior.  Instead, you should store state on subclasses of `State`.  In your specific case, you should store `flag` on `_ActionState`.

During the transition back from `/action` to `/`, the `Navigator` is free to build new `Action` widgets as often as it likes.  However, the `_ActionState` instance will be maintained.  That's why you want to store state on the `State` subclass and not the `Widget` subclass.  (After the back transition is complete, of course, the `/action` route will be garbage collected and the state will be lost unless you persist it somewhere.)

**Comment by a14n** [comment]
Thanks for the explanation.

This behaviour is really surprising for me and even more with the following code where I use immutable `StatefulComponent`. The difference is that the `flag` is flipped every time the `Action` is created in the `routes` section (in my real app, I start a new game on `/game` route). So the rule seems to be that a given route should always return the same `Widget` ? 

Moreover I don't understand what `config` getter is used for if you get a `Widget` that hasn't been used to create the `State`.

```
import 'package:flutter/material.dart';

class App extends StatelessComponent {
  App();

  Widget build(BuildContext context) {
    return new Scaffold(
        toolBar: new ToolBar(center: new Text('Title')),
        body: new Container(),
        floatingActionButton: new FloatingActionButton(onPressed: () {
          Navigator.pushNamed(context, '/action');
        }, child: new Icon(icon: 'content/add')));
  }
}

class Action extends StatefulComponent {
  Action(this.flag);
  final bool flag;
  _ActionState createState() => new _ActionState();
}

class _ActionState extends State<Action> {
  Widget build(BuildContext context) {
    return new Scaffold(
        toolBar: new ToolBar(center: new Text('Action ${config.flag}')),
        body: new Container());
  }
}

void main() {
  bool flag = true;
  runApp(new MaterialApp(
      title: 'Test back button',
      routes: {
        '/': (RouteArguments args) => new App(),
        '/action': (RouteArguments args) => new Action(flag = !flag),
      }));
}
```

**Comment by abarth** [comment]
> '/action': (RouteArguments args) => new Action(flag = !flag),

This is the line of code that's causing the surprising behavior.  These functions are called repeatedly whenever the `Navigator` wishes to rebuild.  In particular, they happen to be called when the navigator starts a transition.  This line of code has a side-effect of changing the value of `flag`, which means the flag will flip back and forth at arbitrary times.

> So the rule seems to be that a given route should always return the same `Widget`?

It doesn't have to be the same widget.  You're welcome to return a different widget each time.  The rule is that these functions shouldn't have side-effects.  In your particular case, it's the fact that you're mutating `flag` during the function call that's causing the surprising behavior.  It's fine to read `flag` in that function and to modify it elsewhere (e.g., in the `onPressed` callback).

> Moreover I don't understand what `config` getter is used for if you get a `Widget` that hasn't been used to create the `State`.

The `config` getter returns the current `Widget` associated with the `State`.  When your parent widget rebuilds, it might create a new widget with different parameters.  If the `runtimeType` and the `key` remain the same, you'll keep the same `State` object but update the widget it uses as its `config`.

**Comment by a14n** [comment]
sorry for the delay and thanks for the infos.

The example with `flag=!flag` was just to illustrate my point. If the widget returned is not the same, the back transition will be done as if the new widget was the old one from which I go back.

Here's another try to explain it :)

1. I'm on my app's home with a white background
1. I navigate to the route `/action` and when I accessed it, it displays a widget with a red background
1. at one point the route `/action` no longer return a widget with a red background but a widget with a blue background.
1. after this change, on my page with red background, I press the back button and instead of a transition from red to white I see a transition from blue to white.

IIRC I tried with a Key but without success. I'll make another try when I'll have free cycles.

**Comment by Hixie** [comment]
The problem is that you're changing what you're returning from the routes callback, but not telling anyone about it. `void main()` is essentially a stateless component, so it shouldn't change its state.

You can work around this by having a stateful component that returns the MaterialApp(), and put the flag argument there. When you change it, change it from inside a setState() call in that stateful component. The runApp() call in `void main()` would then only be a simple call to create this stateful component.

Does that make sense?

**Comment by a14n** [comment]
Thanks for your time and explanations. I better understand now (although my brain is still not full react-oriented).
