### ISSUE TITLE
Long press blank and drag it to move cursor. The cursor shouldn't blink.

### ISSUE THREAD

**Issue by talisk** [flutter/flutter#105454]
## Steps to Reproduce

The blinking animation of Flutter app looks different with iOS native app when I move the cursor.

There're screen records of Flutter app and iOS native app.

### Flutter

https://user-images.githubusercontent.com/7621572/172211845-a89a9dda-f60a-4c9a-aec3-9e96c1a53409.mov

### iOS Native
https://user-images.githubusercontent.com/7621572/172211895-da8897f1-66b3-4109-b296-e0b709f07a65.mov

### Steps

1. Long press and drag the blank bar.
2. Look at the cursor. The cursor will keep blinking while dragging. But iOS won't.

**flutter doctor**
<details>
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, 3.0.1, on macOS 12.4 21F79 darwin-x64, locale
    zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4)
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.67.2)
[✓] Connected device (1 available)
[✓] HTTP Host Availability

• No issues found!
```
</details>

**Comment by HansMuller** [comment]
CC @justinmc
