### ISSUE TITLE
[webview] Problem publishing app to TestFlight ITMS-90338: Non-public API usage

### ISSUE THREAD

**Issue by rologr35** [flutter/flutter#105495]
The app references non-public selectors in Frameworks/webview_flutter_wkwebview.framework/webview_flutter_wkwebview: estimatedProgress, isMainFrame, setNavigationDelegate:, targetFrame, userContentController, websiteDataStore. If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed. For further information, visit the Technical Support Information at http://developer.apple.com/support/technical/

**Comment by khang-dev** [comment]
Same for me

**Comment by thanhphu** [comment]
I guess Apple added those after WWDC, and now flutter have to bend backwards to rename those variables

**Comment by daksh-pokar-shipsy** [comment]
Facing similar issue, I had uploaded a build to TestFlight 2 days back, which seemed to be working fine.

**Comment by daksh-pokar-shipsy** [comment]
<img width="1165" alt="image" src="https://user-images.githubusercontent.com/91050674/172304121-ba3974f8-7d0f-4b45-b125-bdf1254f16b8.png">

**Comment by paulocoutinhox** [comment]
Hi,

Message from Apple: "The issue has been resolved on the app validation backend. Please try resubmitting. Sorry for the trouble."

Thanks.

**Comment by darshankawar** [comment]
Based on above comment, it seemed to be an issue upstream and not specific to Flutter.
Closing, as the issue seems to have been resolved per above.
