### ISSUE TITLE
Plugin references UrlLauncher which doesn't exist

### ISSUE THREAD

**Issue by filiph** [flutter/flutter#10545]
## Steps to Reproduce

1. Go to https://github.com/flutter/plugins/tree/master/packages/android_intent
2. Locate the text "Note that a similar method does not currently exist for iOS. Instead, the system plugin (UrlLauncher) can be used for deep linking."
3. Click on UrlLauncher.

This is a 404 error. In fact, `UrlLauncher` doesn't seem to exist in all of Flutter SDK, at least not on https://docs.flutter.io/index.html.

**Comment by eseidelGoogle** [comment]
It got moved into a plugin: https://pub.dartlang.org/packages/url_launcher
