### ISSUE TITLE
devicelab_benchmark Android benchmarks purple for last Friday 6/3

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#105464]
<img width="1674" alt="Screen Shot 2022-06-06 at 1 21 59 PM" src="https://user-images.githubusercontent.com/6343103/172242363-0dd72a97-8b41-43dd-a74c-7852cfdc1baf.png">

**Comment by zanderso** [comment]
The builds have no logs

**Comment by zanderso** [comment]
@gaaclarke Could you check whether you received emails for these failures?

**Comment by gaaclarke** [comment]
> @gaaclarke Could you check whether you received emails for these failures?

I didn't receive emails and it's not on my radar as something to manually check either.

**Comment by keyonghan** [comment]
Tests are being picked up and running through: https://ci.chromium.org/p/flutter/g/devicelab_benchmark/console.
Leaving https://github.com/flutter/flutter/issues/105468 to track the migration to prod.
