### ISSUE TITLE
Uri.parse is not able to parse the string url with a parameter '###'

### ISSUE THREAD

**Issue by vilashraj** [flutter/flutter#105424]
String urlStr = 'https://abc.com/pqr?pageSize=20&searchQuery=###';

print(Uri.parse(urlStr)); // Result:  https://abc.com/pqr?pageSize=20&searchQuery=#%23%23

The first '#' is still not converted to %23.

For hands on please try the below link:
https://dartpad.dev/?id=b8cdade1c849680082b49132e5c91b72

**Comment by darshankawar** [comment]
@vilashraj 
This should be reported in dedicated repo: https://github.com/dart-lang/sdk/issues

Closing, as this isn't a Flutter issue.
