### ISSUE TITLE
Webview_flutter App Store Connect Operation Error

### ISSUE THREAD

**Issue by lauralarez** [flutter/flutter#105472]
Hello, I am having trouble uploading the app to the App Store. I have uploaded the same app several times before but today its showing this error:

> The app references non-public selectors in Payload/Runner.app/Frameworks/webview_flutter.framework/webview_flutter: initWithFrame:configuration:, isMainFrame, setNavigationDelegate:, targetFrame, userContentController With error code STATE_ERROR.VALIDATION_ERROR.50 for id 4e50137e-2378-492a-83f7-08cc856c7520

<img width="732" alt="Screen Shot 2022-06-06 at 16 54 32" src="https://user-images.githubusercontent.com/35902996/172258179-b6330021-c382-43f3-85ce-77485a2b0bb1.png">

The thing is I have not changed anything that has to do with the webview (dependency version or implementation) since last upload. I don't know if it is something with apple or this dependency, it works perfect with Android

I am using:
webview_flutter: ^1.0.7
Flutter 1.22.5 • channel stable
Tools • Dart 2.10.4

Flutter doctor:
[✓] Flutter (Channel stable, 1.22.5, on macOS 12.1 21C52 darwin-arm, locale en-VE)

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
[!] Android Studio (version 4.2)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] VS Code (version 1.63.2)
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[✓] Connected device (1 available)

**Comment by stuartmorgan** [comment]
You will need to contact Apple, as this is definitely a bug at their end. Everything on that list is a public, documented selector.

**Comment by paulocoutinhox** [comment]
I have the same error here:
https://github.com/swordray/JXWebViewController/issues/1

Apple forum post:
https://developer.apple.com/forums/thread/707350?page=1#715882022

**Comment by WONDERJEWEL** [comment]
I have the same error

**Comment by jmagman** [comment]
This isn't just Flutter:
https://twitter.com/ThomasVidas/status/1533936319596007425
https://news.ycombinator.com/item?id=31648690
https://github.com/ionic-team/capacitor/issues/5661
https://github.com/facebook/react-native/issues/31507#issuecomment-1147885603 and later comments

We will report this to Apple, but likely they are already aware and working on a fix.

**Comment by chailirTokoplas** [comment]
after update to webview_flutter 3.0.4 and uploaded. than i got email:

ITMS-90338: Non-public API usage - The app references non-public selectors in Frameworks/webview_flutter_wkwebview.framework/webview_flutter_wkwebview: estimatedProgress, initWithFrame:configuration:, isMainFrame, setNavigationDelegate:, userContentController, websiteDataStore. If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed. For further information, visit the Technical Support Information at http://developer.apple.com/support/technical/

in testFlight i have Invalid Binary Status
what is the solution?

**Comment by abreudiego94** [comment]
me too

**Comment by talhakosen** [comment]
same here

**Comment by preteambuy** [comment]
i used an older version of xcode 13.2.1 and was able to submit to the app store successfully

**Comment by paulocoutinhox** [comment]
Hi,

Message from Apple: "The issue has been resolved on the app validation backend. Please try resubmitting. Sorry for the trouble."

Thanks.
