### ISSUE TITLE
Chainable animations doc typo

### ISSUE THREAD

**Issue by pauldemarco** [flutter/flutter#10544]
## Steps to Reproduce

On the [Animations page](https://flutter.io/animations/#animation-controllers):

> The ReverseAnimation subclass takes an Animation<double> class as its parent and reverses all the values of the animation. It assumes the parent is using a value nominally in the range 0.0-1.0 and returns a value in the range 1.0-0.0. The status and direction of the parent animation are also reversed. **CurvedAnimation** is immutable and stateless.

CurvedAnimation should probably be ReverseAnimation?

**Comment by Hixie** [comment]
Thanks for bringing this to our attention, will fix.

**Comment by Hixie** [comment]
@sethladd I misunderstood, this is actually a Web site bug.

**Comment by sethladd** [comment]
@Hixie can you confirm the fix is just s/CurvedAnimation/ReverseAnimation ? We can make that change easily.

**Comment by Hixie** [comment]
yes
