### ISSUE TITLE
Move devicelab benchmark builders from staging to prod

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#105468]
Devicelab benchmark builders are https://ci.chromium.org/p/flutter/g/devicelab_benchmark/console.

These builders were moved to staging due to their high flaky rate. As of today, linux/android ones have been pretty stable without a single flak in recent 500 runs, and we should move them to prod. This can help monitor the tests more closely (avoiding issues like https://github.com/flutter/flutter/issues/105464).

Linux/android ones are ready to move, whereas the mac/ios ones are still flaky and we can monitor and move later if flake is clear.

**Comment by ricardoamador** [comment]
Yes sir. I'll take a look.

**Comment by keyonghan** [comment]
Action items:

- [ ] Add targets in .ci.yaml (flutter/flutter)
- [ ] remove configs from devicelab_staging_config.star (flutter/infra)

**Comment by zanderso** [comment]
> /cc @zanderso These linux builders have been enabled in flutter dashboard, and will be removed from devicelab_benchmark console via https://flutter-review.googlesource.com/c/infra/+/31020.

Thanks!

**Comment by ricardoamador** [comment]
I have moved flutter-linux-14 and flutter-linux-15 from staging to prod.

**Comment by ricardoamador** [comment]
Reopening to track the move of the IOS bots.

**Comment by keyonghan** [comment]
F.Y.I: https://github.com/flutter/flutter/issues/110037. This should be ready to go without any blockers. /cc @ricardoamador

**Comment by ricardoamador** [comment]
@keyonghan on it.

**Comment by ricardoamador** [comment]
IOS Benchmark tests have been moved to prod.

**Comment by zanderso** [comment]
Thanks!
