### ISSUE TITLE
Cannot stat gn file on infra

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#105476]
See e.g. https://ci.chromium.org/ui/p/flutter/builders/try/Mac%20Android%20AOT%20Engine/32081/overview

Iv'e seen this in several try jobs on the PR for that bad build.

**Comment by sealesj** [comment]
Hey Dan, I've been looking into this. Talking with Casey, it sounds like this could be due to `gn` being assumed to be downloaded from source code cache, but this failure seems to be on a fresh cache.

**Comment by sealesj** [comment]
But also he mentioned the previous two tasks are from the framework and not the engine. Do you know why this could be?

**Comment by dnfield** [comment]
FWIW, I'm seeing this happen pretty frequently on try jobs in engine PRs.

**Comment by sealesj** [comment]
It looks like the call to gclient `revinfo` has the wrong git directory somehow and it is failing with `fatal: not a git repository: '/opt/s/w/ir/cache/builder/src/flutter/.git' but I haven't been able to figure out what the difference in input to that is causing the error

**Comment by keyonghan** [comment]
Some findings:
1) this happens only in presubmit builds
2) this happened only on builder `Mac Android AOT Engine`
3) From the failed builds, I can alway spot below fatal message, which should cause the gn file not available.
```
src (Elapsed: 0:00:00)
----------------------------------------
[0:00:00] Started.
_____ src at 8ce3dadcb6bb3e05570e1b5748fbc2716d264bb0
[0:00:00] Finished running: git remote set-url --push origin https://github.com/flutter/buildroot.git
running "git cat-file -e 8ce3dadcb6bb3e05570e1b5748fbc2716d264bb0^{commit}" in "/opt/s/w/ir/cache/git/github.com-flutter-buildroot"
skipping mirror update, it has rev=8ce3dadcb6bb3e05570e1b5748fbc2716d264bb0 already
[0:00:00] Finished running: git config remote.origin.url
[0:00:00] _____ switching src from /opt/s/w/ir/cache/git/github.com-chinmaygarde-flutter_buildroot to new upstream /opt/s/w/ir/cache/git/github.com-flutter-buildroot
[0:00:00] Likely due to DEPS change with git cache_dir, the current commit points to no longer existing object.
Command 'git rev-list -n 1 HEAD' returned non-zero exit status 128 in /opt/s/w/ir/cache/builder/src
fatal: bad object HEAD
```
All failed builds either hit `github.com-chinmaygarde-flutter_buildroot` or `github.com-dnfield-flutter_buildroot`, and then complains bad HEAD. /cc @dnfield @chinmaygarde Do you recognize these messages or anything special in your PRs/branches, etc?

I am enabling `clobber: true` for this builder in https://github.com/flutter/engine/pull/33916, which adds 3+ min to the execution time.

**Comment by dnfield** [comment]
I think something is wrong with the cache that bot is pulling. Can we kill the cache without clobbering every build?

It looks like it's somehow getting chinmay's fork of buildroot sometimes?

**Comment by godofredoc** [comment]
Fix is being tracked here: https://crbug.com/1334889

**Comment by godofredoc** [comment]
depot_tools rolled to recipes in https://flutter-review.googlesource.com/c/recipes/+/31082

**Comment by aam** [comment]
How long does the roll out take?
I still see it happening on Mac Host engine build as part of dart->engine sdk roll https://github.com/flutter/engine/pull/33961
`gn --runtime-mode debug --unoptimized --prebuilt-dart-sdk --no-lto` fails with
```
/opt/s/w/ir/cipd_bin_packages/python: could not resolve options: failed to resolve Python script: stat /opt/s/w/ir/cache/builder/src/flutter/tools/gn: no such file or directory
```

**Comment by godofredoc** [comment]
The change to depot_tools is fully propagated. For reference this is the failing build: https://ci.chromium.org/p/flutter/builders/try/Mac%20Host%20Engine/38526?

**Comment by godofredoc** [comment]
Reverting last change:

* https://ci.chromium.org/p/flutter/builders/try/Windows%20Host%20Engine/38519?
* https://ci.chromium.org/p/flutter/builders/try/Windows%20Android%20AOT%20Engine/38550?
* https://ci.chromium.org/p/flutter/builders/try/Linux%20Host%20Engine/37184?

**Comment by aam** [comment]
Any updates on this?
This is still consistently failing on dart->engine roller bots preventing successful dart sdk rolls.

**Comment by keyonghan** [comment]
Fix is in. Will keep monitoring how things go.

**Comment by keyonghan** [comment]
Haven't seen the problem in recent 100 builds for above mentioned four builders:
https://ci.chromium.org/p/flutter/builders/try/Linux%20Host%20Engine?limit=100
https://ci.chromium.org/p/flutter/builders/try/Windows%20Android%20AOT%20Engine?limit=100
https://ci.chromium.org/p/flutter/builders/try/Windows%20Host%20Engine?limit=100
https://ci.chromium.org/p/flutter/builders/try/Mac%20Android%20AOT%20Engine?limit=100

Marking as resolved. Please reopen if you see this again.
