### ISSUE TITLE
October does not have 31 days in datepicker on iOS

### ISSUE THREAD

**Issue by otaviojr** [flutter/flutter#10541]
Why flutter datepicker does not show 31 days in october on iOS? 

The same app on Android shows 31 days.

Maybe an iOS problem?

<img width="353" alt="screen shot 2017-06-06 at 17 54 47" src="https://user-images.githubusercontent.com/2933837/26851481-582c5124-4ae1-11e7-9912-8e58d164245a.png">

<img width="340" alt="screen shot 2017-06-06 at 17 54 57" src="https://user-images.githubusercontent.com/2933837/26851482-5831a7dc-4ae1-11e7-8d1b-cf3e14354195.png">

**Comment by eseidelGoogle** [comment]
That seems bad. :/  FYI @hansmuller

**Comment by otaviojr** [comment]
Is there something to do with DST? On Dart documentation they say that the difference between two dates could be not multiple of 24h if a DST happens between those dates.

date_picker.dart uses difference and inDays to compute the maximum allowed day for that month.

I know that US DST is near october/november. 

To make a test I changed the line 130 of date_picker.dart from:

final int daysInMonth = new DateTime(year, month + 1).difference(new DateTime(year, month)).inDays;

to:

final int daysInMonth = ((new DateTime(year, month + 1).millisecondsSinceEpoch - new DateTime(year, month).millisecondsSinceEpoch)/1000/3600/24).round();

and it worked in both platforms. This is not a solution, just a test to understand better the problem.

regards

**Comment by eseidelGoogle** [comment]
I don't know.  @alan-knight probably would.
https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/date_picker.dart is the relevant file.

**Comment by jason-simmons** [comment]
The "Using DateTime with Duration" section of the Dart DateTime class docs explains this:
    https://api.dartlang.org/stable/1.23.0/dart-core/DateTime-class.html

Duration.inDays returns the number of whole days calculated from the delta in nanoseconds between the two DateTimes.  A daylight savings adjustment can result in a partial day.

We probably should be using DateTime.utc()

**Comment by otaviojr** [comment]
I made a test here with the line below.

final int daysInMonth = new DateTime.utc(year, month + 1).difference(new DateTime.utc(year, month)).inDays;

It worked on both platforms.

regards

**Comment by eseidelGoogle** [comment]
FYI @floitschG

**Comment by floitschG** [comment]
That doesn't make sense to me: iOs and Android should behave the same, and UTC datetimes should definitely give you 30 days in April.

I looked through the code, and afaics UTC doesn't even ask the system for zone-related information. It's a fully deterministic computation on its inputs.

Could you please rerun the program and get the `millisecondsSinceEpoch` values for the two datetimes?
(More correct would be `microSecondsSinceEpoch`, but the higher precision shouldn't matter).

Wrt using `DateTime`s for dates: be *very* careful when doing this. Always stay in UTC `DateTime`s. Even simple things like `new DateTime(year, month, day)` could go wrong, otherwise. For example, Brazil changes timezone at midnight leading to weird bugs: https://github.com/dart-lang/sdk/issues/7079

**Comment by Hixie** [comment]
It seems to me that we should just hard-code the number of days in a month for the widget, rather than depending on DateTime...

**Comment by floitschG** [comment]
That should be ok. You would just need to reimplement the `isLeapYear` functionality of the `DateTime` class (which is pretty simple).

**Comment by floitschG** [comment]
I would still like to know what's going wrong here, though!
If you could provide the microseconds/milliseconds I would still be interested (even if you decide to implement it differently).

**Comment by floitschG** [comment]
This has been closed, but just in case you can easily reproduce: the micro/milliseconds for the failing UTC code would still be interesting to me.
It's not a big deal, though. (Just would like to make sure there isn't a bug elsewhere).

**Comment by otaviojr** [comment]
@floitschG I tried to reproduce it and it is working now... with the same UTC code. When I updated flutter dart gets a new version too. I do not change my simulator neither changed anything on xcode. I don't know what have changed, but, april gets 30 days now with UTC code and october gets 31. Maybe the simulator gets new DST info? I really don't know. I think that freeing this from any datetime dependencies will solve this for good.

regards

**Comment by floitschG** [comment]
Maybe it was a hot-reload issue?
In any case, I think the UTC approach should work, but having a table seems like a good solution anyway.

**Comment by patelkrunal78** [comment]
You can use the difference method provide by DateTime class

 //the birthday's date
 final birthday = DateTime(1967, 10, 12);
 final date2 = DateTime.now();
 final difference = date2.difference(birthday).inDays;

https://icetutor.com/question/flutter-finding-difference-between-two-dates
