### ISSUE TITLE
[iOS] Remove bitcode support

### ISSUE THREAD

**Issue by Sunbreak** [flutter/flutter#105501]
https://developer.apple.com/documentation/xcode-release-notes/xcode-14-release-notes

> Starting with Xcode 14, bitcode is no longer required for watchOS and tvOS applications, and the App Store no longer accepts bitcode submissions from Xcode 14.

Related: https://github.com/flutter/flutter/issues/15288

**Comment by jmagman** [comment]
https://github.com/flutter/flutter/issues/46707#issuecomment-1147962206

We should probably wait until the tool enforces Xcode 14 as the minimum to do this.  If we need to do it sooner we would break add-to-app/watchOS companion app developers.

**Comment by jmagman** [comment]
Closing in favor of the more detailed https://github.com/flutter/flutter/issues/107887
