### ISSUE TITLE
Flutter Test package using outdated dependencies

### ISSUE THREAD

**Issue by doublej74** [flutter/flutter#105509]
Collection library has a new version. not sure about other dependencies, but some of the new versions of my project's dependencies are using the latest version of Collection library, therewith rendering my unit tests unusable at the moment. please update.

**Comment by doublej74** [comment]
looks like the correct version. This made me realize, that I'm still on flutter 2.5.10. Sorry for the inconvenience. please close

**Comment by exaby73** [comment]
@doublej74 No problem :) Just a side note, you can also close issues that you have opened :)
