### ISSUE TITLE
Update `MaterialBanner` to support  Material 3

### ISSUE THREAD

**Issue by TahaTesser** [flutter/flutter#105594]
### Description

[MaterialBanner](https://master-api.flutter.dev/flutter/material/MaterialBanner-class.html) could be updated to support Material 3 using the [tokens](https://github.com/flutter/flutter/blob/master/dev/tools/gen_defaults/data/banner.json).

**Comment by HansMuller** [comment]
@darrenaustin - please add this to the Material3 umbrella issue.
