### ISSUE TITLE
`flutter run` with multiple devices should ask me which device to use

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#10557]
I have multiple devices connected to my system. When I just do a `flutter run` and forget to specify which device to run flutter just exits after printing the list of available devices. Instead of doing that, it would be nice if it asked me which device to use (e.g. press 1 for iPod Touch, press 2 for Nexus 6P, etc.)

**Comment by clemkofi** [comment]
Please this should at least be added in the production version ..... It will be extremely useful!

**Comment by Atralb** [comment]
Yup, seems to me like a basic feature that should be implemented

**Comment by jonahwilliams** [comment]
Completed in #57349, thanks @natanportilho !
