### ISSUE TITLE
Android Signin Plugin does not handle UserRecoverableAuthException

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#10550]
When a UserRecoverableAuthException happens on Android, it comes with an Intent that the app is supposed to invoke to recover from the error. Common reasons could be giving consent to the API or device management being turned off (or invalid). These are user fixable problems and the actions to fix them usually accompanies the exception. Sending this error back to the Dart app code is not good because the Intent does not go through and the app can do nothing but close.

https://developers.google.com/android/reference/com/google/android/gms/auth/UserRecoverableAuthException

**Comment by mit-mit** [comment]
cc @collinjackson

**Comment by goderbauer** [comment]
@mehmetf I am re-working the google_sign_in plugin a bit to fix https://github.com/flutter/flutter/issues/10688.

Do you have ab example of how I can trigger an UserRecoverableAuthException and see it getting resolved? I want to make sure that the re-work doesn't re-surface this bug (I wish we had better testing for the plugins... https://github.com/flutter/flutter/issues/10824).

**Comment by mehmetf** [comment]
Externally, this happens when you need to give consent prior to login (for instance an app is asking for Drive API scope; you need to give consent before they can access).

Internally, you can reproduce this by going to your Device Policy settings and turning it off. you won't be able to use your corp account and it will forward you to the policy page via a recoverable exception.

**Comment by mehmetf** [comment]
@goderbauer The current plugin doesn't handle this, right? That's why we have this issue open. So your re-work is not going to regress anything AFAIK.

**Comment by goderbauer** [comment]
Todd's https://github.com/flutter/plugins/issues/114 claims to have fixes this (and probably forgot to close the issue @tvolkert). However, the fix relies on auto-managing the connection, which I intent to replace by a manual managed connection to fix other issues. In doing though, I wanted to make sure we don't break this again.

**Comment by mehmetf** [comment]
You are right. This is one of the things automanage manages for you. You would need to do it manually now.

**Comment by goderbauer** [comment]
Fixed by flutter/plugins#148.
