### ISSUE TITLE
[Windows only] Horizontal scrolling not working with mouse wheel inside a column

### ISSUE THREAD

**Issue by mgenware** [flutter/flutter#105522]
## Steps to Reproduce

1. Create an app from official template `flutter create myapp`
2. Replace the `return Scaffold` code with the following:

```dart
return Scaffold(
      appBar: AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: Column(
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: [
          SingleChildScrollView(
            scrollDirection: Axis.horizontal,
            child: Row(children: [
              Text(
                  'Long text Long text Long text Long text Long text Long text Long text Long text Long text Long text Long text Long text '),
              ElevatedButton(
                  onPressed: () {},
                  child: Text(
                      'Long text Long text Long text Long text Long text ')),
              Text(
                  'Long text Long text Long text Long text Long text Long text Long text Long text Long text ')
            ]),
          )
        ],
      ),
    );
```

**Expected results:**

![image](https://user-images.githubusercontent.com/11565096/172409817-0ed3df85-fb22-40bd-9567-dd57659aa6a2.png)

Horizontal scrolling works on the row.

**Actual results:**

Works on Android by swiping and macOS by swiping on touchpad. 

Doesn't work Windows with mouse wheel. I don't have a touchpad for Windows to test. 

<details>
<summary>Flutter doctor</summary>

[✓] Flutter (Channel stable, 3.0.1, on Microsoft Windows [Version 10.0.22000.675], locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Chrome - develop for the web
[✓] Visual Studio - develop for Windows (Visual Studio Enterprise 2022 17.2.3)
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.67.2)
[✓] Connected device (4 available)
[✓] HTTP Host Availability

• No issues found!

</details>

**Comment by huycozy** [comment]
Hi @mgenware, thanks for filing the issue. 
I see there are open issues addressing the case you described 
- #75180
- #105095
Closing as a duplication, so please follow up on them for further updates.
