### ISSUE TITLE
Engine's `gn` script failing to run in CI.

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#105565]
The Engine's `gn` script is failing in CI, occasionally with:

```
/opt/s/w/ir/cipd_bin_packages/python: could not resolve options: failed to resolve Python script: stat /opt/s/w/ir/cache/builder/src/flutter/tools/gn: no such file or directory
```

https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8811967282878277121/+/u/gn_--runtime-mode_profile_--android_--no-lto/stdout

Previously: https://github.com/flutter/flutter/issues/88298

**Comment by zanderso** [comment]
Bumping priority as this is failing repeatedly in presubmit.

**Comment by sealesj** [comment]
Looks like the same issue as https://github.com/flutter/flutter/issues/105476
