### ISSUE TITLE
Terminating `flutter run --machine` process does not always close app on device/emulator

### ISSUE THREAD

**Issue by DanTup** [flutter/flutter#10556]
If I launch Flutter's Hello World with a breakpoint on the main method and then terminate the process while sat at that breakpoint, the app does not close correctly (it remains as a black screen).

![Emulator](https://user-images.githubusercontent.com/1078012/26895042-23c8168e-4bb8-11e7-99f9-e48ffdf48df8.png)

**Comment by DanTup** [comment]
Actually, doesn't even need the debugging... I launched without debugger (nor did I pass `--start-paused`) and then terminated, and it left the app open (though this time Hello World is visible, since it didn't stop at a breakpoint).

![Emulator](https://user-images.githubusercontent.com/1078012/26895163-98b52e96-4bb8-11e7-8835-9db092b50a59.png)

**Comment by Hixie** [comment]
This is expected, the Hello World app does not implement the debugging APIs.

**Comment by DanTup** [comment]
@Hixie This doesn't seem to match what @devoncarew said [here](https://github.com/flutter/flutter/issues/10546#issuecomment-306876635), he thinks this is a bug?

I'm also slightly confused; this does seem to work sometimes and should an individual app really need to implement APIs so that it terminates correctly; why wouldn't this be done by the framework?

**Comment by Hixie** [comment]
Normal apps should close fine. It's just specifically the Hello World app (or any app that doesn't actually use the Flutter framework) that is affected.

**Comment by DanTup** [comment]
@Hixie Do you know why it would intermittently work?

> specifically the Hello World app (or any app that doesn't actually use the Flutter framework)

I'm a bit of a flutter noob, it looked to me like Hello World used the flutter framework; what is it that's missing? (I presume I can just switch to one of the other example apps for testing, I'm just curious about this!)

**Comment by Hixie** [comment]
Ah, I may have been confused about which app you meant.

These should terminate fine, because they use the Flutter framework:
https://github.com/flutter/flutter/blob/master/examples/hello_world/lib/main.dart
https://github.com/flutter/flutter/blob/master/examples/layers/widgets/hello_world.dart
https://github.com/flutter/flutter/blob/master/examples/layers/rendering/hello_world.dart

This one should not terminate, because it does not use the Flutter framework:
https://github.com/flutter/flutter/blob/master/examples/layers/raw/hello_world.dart

None of them should only work intermittently, that's weird.

**Comment by DanTup** [comment]
Ah, ok. It is [this one](https://github.com/flutter/flutter/blob/master/examples/hello_world/lib/main.dart) I'm testing with.

Terminating from the command line seems to always work, though I think pressing Ctrl+C sends a different signal than just calling `.kill()` in node (which is basically what I'm doing). As I understood it, `.kill()` will just terminate the process in a way that it has no way of dealing with it, so I'm actually more surprised it ever works than that it sometimes doesn't!

That said, I guess it should work reliably if it's being terminated by something running on the device that has noticed the flutter process has gone away?

When I get time, I'll try and do a little bit more investigation and see whether I can find a pattern for when it does/doesn't work.

**Comment by devoncarew** [comment]
@DanTup, you could also kill the app with the app.stop() daemon command, instead of node process kill function.

**Comment by DanTup** [comment]
@devoncarew Tried that, but then either the debugger process gets immediately terminated (which I don't know if may result in unreliable termination; eg. if the command was still in a buffer) or I delay telling Code I've finished (and that's where https://github.com/Microsoft/vscode/issues/28192 came from!).

If killing the process _should_ work, then I think fixing this bug is the simplest way (for me). If it's unlikely it can be made reliable, I can try and see if that Code issue can be investigated/resolved.

**Comment by DanTup** [comment]
FWIW, I made [a change](https://github.com/Dart-Code/Dart-Code/commit/d01965f318802607380677925c5a71043ada817a) to send the request before immediately terminating and it seems to have been reliable (I don't know if would be the case on bigger apps or under load though).

I think there's still value in fixing this if you can, but it might not be as bad as I thought. I'll post back if it does seem to become unreliable though.

**Comment by DanTup** [comment]
I think https://github.com/Dart-Code/Dart-Code/issues/771 may be related to this. I'm currently sending `app.stop` and then `.kill()`, but Flutter seems to continue running afterwards.

I could send a SIGKILL but I don't know if that's even more likely to leave things around. How fast shout Flutter stop when send app.stop/SIGTERM during a build?

**Comment by DanTup** [comment]
I'm not sure why I commented on this and raised https://github.com/flutter/flutter/issues/16183 on the same day. Closing this as a dupe of https://github.com/flutter/flutter/issues/16183 since they seem to describe the same problem - telling Flutter to stop/quit during a build.
