### ISSUE TITLE
[in_app_purchase 3.0.5] Not getting subscription products from console for android

### ISSUE THREAD

**Issue by nidhi-concetto** [flutter/flutter#105593]
Steps I have followed

## Steps to Reproduce

Set up merchant account in PDC
Uploaded signed apk on Close track ( It is active and used by one tester)
Now if checking with same keystore and app id in getting 0 products with same ids created in console

Here is the details

> in_app_purchase: ^3.0.5

`await _inAppPurchase.isAvailable();` getting true for this but not getting anything in this `await _inAppPurchase.queryProductDetails(_kProductIds.toSet());`

I have verified appId and product id
Included this in `build.gradle`:

```
def billing_version = "5.0.0"
implementation "com.android.billingclient:billing:billing_version"
```

**Expected results:** 

**Actual results:** 
Here _kProductIds= my subscription product ids

<details>
<summary>Sample code</summary>

```dart

 await _inAppPurchase.isAvailable();
 await _inAppPurchase.queryProductDetails(_kProductIds.toSet());

```
</details>

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 2.10.4, on macOS 12.1 21C52 darwin-x64, locale en-GB)
    • Flutter version 2.10.4 at /Users/admin/Nidhi/FlutterSDK/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (3 months ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/admin/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code (version 1.66.2)
    • VS Code at /Users/admin/Downloads/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • RMX1921 (mobile)             • 192.168.20.124:5555 • android-arm64  • Android 11 (API 30)
    • sdk gphone64 x86 64 (mobile) • emulator-5554       • android-x64    • Android 12 (API 31) (emulator)
    • Chrome (web)                 • chrome              • web-javascript • Google Chrome 102.0.5005.61

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```
</details>

 
Please let me know If I am missing something.

**Comment by huycozy** [comment]
Hi @nidhi-concetto,
From your `flutter doctor -v`, I can see you're using old Flutter SDK, please upgrade it to the latest version. 
Then provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this.
Thank you!

**Comment by huycozy** [comment]
For your information,
> def billing_version = "5.0.0"

You're using a new `billing_version` that isn't supported yet. See https://github.com/flutter/plugins/pull/5405
So I recommend you using the same version as the example [here](https://github.com/flutter/plugins/blob/7723022cdc6dfb4d5e502ec07ae8444bc9305c90/packages/in_app_purchase/in_app_purchase/example/android/app/build.gradle#L109)

```
implementation 'com.android.billingclient:billing:3.0.2'
```

> but not getting anything in this await _inAppPurchase.queryProductDetails(_kProductIds.toSet());

From `queryProductDetails` API document, this function will return a `ProductDetailsResponse` object, is it null in your case?

**Comment by nidhi-concetto** [comment]
Thanks for the reply @huycozy  this is working now with implementation 'com.android.billingclient:billing:3.0.2' and one more things I have done , I have created new subscriptions after alpha release then I got all new subscriptions somehow old subscriptions which were created before release and payment account integration was not working.
