### ISSUE TITLE
`Icons.add` icon is displaying a beer emoji 🍺 instead of a plus on iOS 16 beta 1

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#105536]
On a new `flutter create`d app, the counter `Icon(Icons.add)` icon is showing as a beer emoji instead of a plus on Xcode 14 beta 1 (14A5228q) on macOS 12.4 (non-beta). Reproduced on simulator and physical phone.  Does not reproduce on macOS desktop app.

<img width="410" alt="beer" src="https://user-images.githubusercontent.com/682784/172454387-71eefa63-8cb2-466d-8c2e-551a8bd82358.png">

```
[✓] Flutter (Channel main, 3.1.0-0.0.pre.1095, on macOS 12.4 21F79 darwin-x64, locale en-US)
    • Flutter version 3.1.0-0.0.pre.1095 at /Users/m/Projects/flutter
    • Upstream repository git@github.com:jmagman/flutter.git
    • Framework revision 3f1f0a8170 (4 days ago), 2022-06-03 10:13:08 -0700
    • Engine revision 76a1567841
    • Dart version 2.18.0 (build 2.18.0-165.0.dev)
    • DevTools version 2.14.0

[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
    • Xcode at /Users/m/Applications/Xcode-14_beta1.app/Contents/Developer
    • CocoaPods version 1.11.3
```

Weirdly it does not reproduce on the simulator OR physical device when run from macOS 13 beta 1 (22A5266r) running the same Xcode build (14A5228q).

**Comment by jmagman** [comment]
Since it doesn't reproduce from macOS 13 beta, suspect this will be resolved in a subsequent beta.  Will keep an eye on it.

**Comment by jmagman** [comment]
Well after a few reruns it doesn't reproduce at all, even after uninstalling the app and deleting DerivedData... 🤔

**Comment by hellohuanlin** [comment]
easter egg maybe

**Comment by jmagman** [comment]
I haven't seen this again in latest betas, let's close for now and see if it gets re-reported.

**Comment by jmagman** [comment]
This happened again on Xcode 16 beta 2. I'm not going to bother reopening this unless I see it again in a later beta.
![Screenshot 2024-06-28 at 4 24 43 PM](https://github.com/flutter/flutter/assets/682784/72006ef0-aaef-45eb-a5e1-4e0645e4a114)
