### ISSUE TITLE
[flutter_markdown] Cannot Copy & Paste content inside markdown

### ISSUE THREAD

**Issue by parkershamblin** [flutter/flutter#105557]
I'm using flutter_markdown for my app and I can't seem to copy & paste from the markdown content. Is this feature not available at the moment? And if so, is there a known work-around?

**Comment by exaby73** [comment]
Hi @parkershamblin, please provide a [minimal, reproducible example][1] and the output of `flutter doctor -v`.

[1]: https://stackoverflow.com/help/minimal-reproducible-example
