### ISSUE TITLE
Implement Dart/platform resync protocol in relevant examples and plugins

### ISSUE THREAD

**Issue by mravn-google** [flutter/flutter#10554]
Plugins and apps using platform messages to relay events from the platform to the Dart side face two problems:
1. early events may be lost because Dart message handlers are not set up immediately on app launch
1. hot restart implies that the Dart isolate is recreated, and knowledge of any state about which the events communicate delta changes is lost

One solution to both problems is to establish a custom "resync" protocol by which the Dart side of the plugin or app sends a platform message once it is ready for business. The platform may then respond by emitting collected events or sending/returning current state to the Dart side.

While resync could be implemented as part of the Flutter framework and platform, it is unlikely that a generic solution can provide the needed flexibility (e.g. catering to Dart message handlers that are set up asynchronously) and still be as simple to use as a custom resync protocol. **That said, provided plugins and examples should implement the resync protocol as applicable in a consistent, recognizable way to be emulated by plugin/app authors.**

See also:
- #8711 about adding a message queue to avoid losing early platform messages (dropped).
- #10452 about adding support for deep linking / initial routing. Using platform messages here is insufficient even with a resync protocol as they are delivered asynchronously.

**Comment by eseidelGoogle** [comment]
Does this block @lukef's deep linking application?  If so we should mark this as customer: posse and customer blocker.

**Comment by mravn-google** [comment]
This issue is not a blocker. It's about providing examples to be emulated.

**Comment by Hixie** [comment]
@mravn-google @mit-mit  Is this something that you plan to do in the coming months? If not, please update the milestone accordingly. (It's plugin framework maintenance so it could be on our list.)

**Comment by mit-mit** [comment]
We are yet to actually have a plugin that has a strong need for this, so closing this bug for now. We'll open a new one should the need arise.
