### ISSUE TITLE
FieldValue.serverTimestamp() Is returning FieldValue(Instance of 'MethodChannelFieldValue')

### ISSUE THREAD

**Issue by saiyajindont** [flutter/flutter#105527]
Hello everyone, I'm trying to use timestamp from firebase but when I set the value FieldValue.serverTimestamp().toString(); on database it returns FieldValue(Instance of 'MethodChannelFieldValue'). What can i do to return a timestamp?

**Comment by darshankawar** [comment]
@saiyajindont 
Your question is better suited for support channels like StackOverflow, so please ask the same there.
If you think, this is a bug in plugin, please report it in dedicated repo using issue template : https://github.com/firebase/flutterfire/issues
