### ISSUE TITLE
redirect to application fail

### ISSUE THREAD

**Issue by kashan1122** [flutter/flutter#105592]
when I try to connect metamask wallet it launch the uri but not redirect to my app from uri (in the debugger mode its fine but release mode raising issue)
I tried this:
onDisplayUri: (uri) async => {print(uri.runtimeType), _launchUrl(uri)});

and this also:
          onDisplayUri: (uri) async => {print(uri.runtimeType), await launchUrl(Uri.parse(uri), mode: LaunchMode.platformDefault)});

          onDisplayUri: (uri) async => {print(uri.runtimeType), await launchUrl(Uri.parse(uri), mode: LaunchMode.externalApplication)});

**Comment by danagbemava-nc** [comment]
Hi @kashan1122, thanks for filing the issue. 

Please provide a complete minimal reproducible code sample as well as the output of `flutter doctor -v` and the version of `url_launcher` you're using. 

Please also provide the relevant steps to reproduce and any errors that you may be experiencing.

Thank you

**Comment by 1972chris** [comment]
>Hi @kashan1122, thanks for filing the issue.  ...

@danagbemava-nc thankyou I’ve been trying so hard too read research on how to follow but it’s so difficult too find the correct way of going about it 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by kashan1122** [comment]
`C:\Users\Toshiba\AndroidStudioProjects\flutterprojects\mobile-application>flutter doctor -v
[√] Flutter (Channel stable, 2.8.1, on Microsoft Windows [Version 10.0.19044.1706], locale en-US)
    • Flutter version 2.8.1 at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (6 months ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at C:\Users\Toshiba\AppData\Local\Android\sdk
    • Platform android-32, build-tools 32.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[!] Android Studio
    • Android Studio at C:\Users\Toshiba\AppData\Local\Android\Sdk\tools\bin
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    X android-studio-dir = C:\Users\Toshiba\AppData\Local\Android\Sdk\tools\bin
    X Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.
    • Consider removing your android-studio-dir setting by running:
      flutter config --android-studio-dir=

[√] Connected device (3 available)
    • Infinix X6810 (mobile) • 07263251B5002661 • android-arm64  • Android 11 (API 30)
    • Chrome (web)           • chrome           • web-javascript • Google Chrome 102.0.5005.63
    • Edge (web)             • edge             • web-javascript • Microsoft Edge 102.0.1245.33

! Doctor found issues in 1 category.
`



`
  url_launcher: ^6.1.3
`






    connector = WalletConnect(
      bridge: 'https://bridge.walletconnect.org',
      clientMeta: const PeerMeta(
        name: 'WalletConnect',
        description: 'WalletConnect Developer App',
        url: 'https://walletconnect.org',
        icons: [
          'https://gblobscdn.gitbook.com/spaces%2F-LJJeCjcLrr53DcT1Ml7%2Favatar.png?alt=media'
        ],
      ),
    );
    print("connector: $connector");
    connector.on('connect', (session) => print("connector.on session: $session"));
    connector.on('session_update', (payload) => print("connector.on session_update payload: $payload"));
    connector.on('disconnect', (session) => print("connector.on session disconnect: $session"));
    // Create a new session
    print("connector.connected>>>>>>>>>>>>>>>>>>>>>>>>>${connector.connected}");
    if (!connector.connected) {
      session = await connector.createSession(
          chainId: 97,
          onDisplayUri: (uri) async => {print(uri.runtimeType), await launchUrl(Uri.parse(uri))});

      print("session,:${session.runtimeType}");
      print("my session: $session");
      // setSession(session);

    }

**Comment by kashan1122** [comment]
@danagbemava-nc 

> `C:\Users\Toshiba\AndroidStudioProjects\flutterprojects\mobile-application>flutter doctor -v [√] Flutter (Channel stable, 2.8.1, on Microsoft Windows [Version 10.0.19044.1706], locale en-US) • Flutter version 2.8.1 at C:\src\flutter • Upstream repository https://github.com/flutter/flutter.git • Framework revision [77d935a](https://github.com/flutter/flutter/commit/77d935af4db863f6abd0b9c31c7e6df2a13de57b) (6 months ago), 2021-12-16 08:37:33 -0800 • Engine revision 890a5fca2e • Dart version 2.15.1
> 
> [√] Android toolchain - develop for Android devices (Android SDK version 32.0.0) • Android SDK at C:\Users\Toshiba\AppData\Local\Android\sdk • Platform android-32, build-tools 32.0.0 • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189) • All Android licenses accepted.
> 
> [√] Chrome - develop for the web • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe
> 
> [√] Android Studio (version 2020.3) • Android Studio at C:\Program Files\Android\Android Studio • Flutter plugin can be installed from: https://plugins.jetbrains.com/plugin/9212-flutter • Dart plugin can be installed from: https://plugins.jetbrains.com/plugin/6351-dart • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
> 
> [!] Android Studio • Android Studio at C:\Users\Toshiba\AppData\Local\Android\Sdk\tools\bin • Flutter plugin can be installed from: https://plugins.jetbrains.com/plugin/9212-flutter • Dart plugin can be installed from: https://plugins.jetbrains.com/plugin/6351-dart X android-studio-dir = C:\Users\Toshiba\AppData\Local\Android\Sdk\tools\bin X Unable to find bundled Java version. • Try updating or re-installing Android Studio. • Consider removing your android-studio-dir setting by running: flutter config --android-studio-dir=
> 
> [√] Connected device (3 available) • Infinix X6810 (mobile) • 07263251B5002661 • android-arm64 • Android 11 (API 30) • Chrome (web) • chrome • web-javascript • Google Chrome 102.0.5005.63 • Edge (web) • edge • web-javascript • Microsoft Edge 102.0.1245.33
> 
> ! Doctor found issues in 1 category. `
> 
> `url_launcher: ^6.1.3`
> 
> ```
> connector = WalletConnect(
>   bridge: 'https://bridge.walletconnect.org',
>   clientMeta: const PeerMeta(
>     name: 'WalletConnect',
>     description: 'WalletConnect Developer App',
>     url: 'https://walletconnect.org',
>     icons: [
>       'https://gblobscdn.gitbook.com/spaces%2F-LJJeCjcLrr53DcT1Ml7%2Favatar.png?alt=media'
>     ],
>   ),
> );
> print("connector: $connector");
> connector.on('connect', (session) => print("connector.on session: $session"));
> connector.on('session_update', (payload) => print("connector.on session_update payload: $payload"));
> connector.on('disconnect', (session) => print("connector.on session disconnect: $session"));
> // Create a new session
> print("connector.connected>>>>>>>>>>>>>>>>>>>>>>>>>${connector.connected}");
> if (!connector.connected) {
>   session = await connector.createSession(
>       chainId: 97,
>       onDisplayUri: (uri) async => {print(uri.runtimeType), await launchUrl(Uri.parse(uri))});
> 
>   print("session,:${session.runtimeType}");
>   print("my session: $session");
>   // setSession(session);
> 
> }
> ```

@danagbemava-nc

**Comment by danagbemava-nc** [comment]
Hi @kashan1122, the sample you have provided is not complete. 

Please provide a complete minimal sample, preferably just a `main.dart` file that will demonstrate the issue that you're facing. 

You also appear to be on an older version of flutter. Kindly upgrade to the latest version of flutter to see if you still experience this issue. If you do, please provide the updated `flutter doctor -v` along with the complete sample so that we can investigate this. 

Thank you

**Comment by kashan1122** [comment]
> flutter doctor -v
> `url_launcher: ^6.1.3`
> 
> ```dart
>     connector = WalletConnect(
>       bridge: 'https://bridge.walletconnect.org',
>       clientMeta: const PeerMeta(
>         name: 'WalletConnect',
>         description: 'WalletConnect Developer App',
>         url: 'https://walletconnect.org',
>         icons: [
>           'https://gblobscdn.gitbook.com/spaces%2F-LJJeCjcLrr53DcT1Ml7%2Favatar.png?alt=media'
>         ],
>       ),
>     );
>     print("connector: $connector");
>     connector.on('connect', (session) => print("connector.on session: $session"));
>     connector.on('session_update', (payload) => print("connector.on session_update payload: $payload"));
>     connector.on('disconnect', (session) => print("connector.on session disconnect: $session"));
>     // Create a new session
>     print("connector.connected>>>>>>>>>>>>>>>>>>>>>>>>>${connector.connected}");
>     if (!connector.connected) {
>       session = await connector.createSession(
>           chainId: 97,
>           onDisplayUri: (uri) async => {print(uri.runtimeType), await launchUrl(Uri.parse(uri))});
> 
>       print("session,:${session.runtimeType}");
>       print("my session: $session");
>       // setSession(session);
> 
>     }
> ```


main.dart

`import 'dart:io';
import 'package:flutter/material.dart';
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:wallet_connect/wallet_connect.dart';
import 'package:zerohex_app/Screens/Login/login_page.dart';
import 'package:zerohex_app/Screens/ProjectDetail/project_details.dart';
import 'package:zerohex_app/Screens/SplashScreen/SplashScreen.dart';
import 'Screens/Discussion/discussion.dart';
import 'package:web3dart/web3dart.dart';
import 'package:http/http.dart' as http;
import 'package:socket_io_client/socket_io_client.dart' as IO;

int notificationCounter;
setNotification(notification)async{
  SharedPreferences pref = await SharedPreferences.getInstance();
  pref.setInt('notification', notification);
  print("SetEmail: $notification");
}
Future<void> main() async {
  await dotenv.load(fileName: ".env");
  runApp(MyApp());
  IO.Socket socket= IO.io("https://stg-api.zerohex.market", <String, dynamic>{
    "transports": ["websocket"],
    "autoConnect": false,
  });
  socket.connect();
  socket.onConnect((data)=> {
    print("socketId: ${socket.id}"),
    print(socket.connected),
    print("connected: $data"),
    socket.emitWithAck(
        'join-room', 'notify2',
        ack: (data) {
          print("connect with join room");
        }),

    socket.on('receive-notifications', (notificationsCount) {
    }),

  });



  // httpClient = Client();
  // ethClient = Web3Client(
  //     "https://rinkeby.infura.io/v3/50c651d850cb4308900bef8b27269851",
  //     httpClient);
  // getBalance(myAddress);
  // loadData();
}

class MyApp extends StatelessWidget {

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'App',
      theme: ThemeData(primarySwatch: Colors.grey, fontFamily: "Poppin-Light"),
      home: SplashScreen(),
      debugShowCheckedModeBanner: false,
    );
  }
}

`
@danagbemava-nc I have provided you complete steps and library version I am using updated version of it 

![image](https://user-images.githubusercontent.com/20478939/172798324-ff3164dd-c1f8-4139-9cda-9b36a62437a9.png)

**Comment by kashan1122** [comment]
@danagbemava-nc Still issue here Kindly help me to reduce it 
here is the code from where url launcher is apply
basically I am opening an uri which direct to uri but not redirect to flutter application




`// ignore_for_file: avoid_init_to_null, avoid_print, prefer_typing_uninitialized_variables, unused_field, missing_return
import 'package:dart_web3/dart_web3.dart';
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:flutter_spinkit/flutter_spinkit.dart';
import 'package:url_launcher/url_launcher.dart';
import 'package:zerohex_app/Screens/Login/wallet_connect_ethereum.dart';

import '../../CommonWidgets/eth_utils.dart';
import 'package:wallet_connect/wallet_connect.dart';
import 'package:walletconnect_dart/walletconnect_dart.dart';
import 'dart:convert';
import 'dart:math';
import 'dart:typed_data';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:http/http.dart' as http;
import 'package:shared_preferences/shared_preferences.dart';


// import 'package:web3dart/web3dart.dart';
import 'package:zerohex_app/Auth/auth.dart';
import 'package:zerohex_app/Screens/HomePage/HomePage.dart';
import 'package:zerohex_app/Screens/SignUp/register_page.dart';
import 'package:http/http.dart';




class LoginPage extends StatefulWidget {
  @override
  _LoginPageState createState() => _LoginPageState();
}

const maticRpcUri =
    'https://data-seed-prebsc-1-s1.binance.org:8545/';
// enum TransactionState {
//   disconnected,
//   connecting,
//   connected,
//   connectionFailed,
//   transferring,
//   success,
//   failed,
// }
// enum NetworkType {
//   ethereum,
//   algorand,
// }
class _LoginPageState extends State<LoginPage> {
  // controllers
  final emailController = TextEditingController();
  final passwordController = TextEditingController();

  final formKey = GlobalKey<FormState>();
  bool isPasswordNotVisible = true;
  var errorMsg, jsonResponse;
  bool boolean = true;
  var token;
  var accountFlag;
  var sessionRoute;
  final url =
  Uri.parse("https://stg-api.zerohex.market/api/users/login_signupByEmail");
  final _web3client = Web3Client(
    maticRpcUri,
    http.Client(),
  );
  WCClient _wcClient;
  SharedPreferences _prefs;
  setEmail(email)async{
    SharedPreferences pref = await SharedPreferences.getInstance();
    pref.setString('email', email);
    print("SetEmail: $email");
  }

  @override
  void initState() {
    super.initState();
  }
  var session;
  var yourContract;
  var rpcUrl = 'https://data-seed-prebsc-1-s1.binance.org:8545/';
  String account = "";
  final contractAddress = dotenv.env['TOKEN_CONTRACT_ADDRESS'];
  var _myData;
  // final contractAddress = "0xaBE2ec3a68A15a382BcDC93499Ab751D3d954BB2";
  EthereumUtils ethUtils = EthereumUtils();
  bool isLoading = true;
  bool checkBool;
  booleanValue(value) async {
    SharedPreferences prefs = await SharedPreferences.getInstance();
    prefs.setBool('bool', value);
  }

  @override
  Widget build(BuildContext context) {
    return WillPopScope(
        onWillPop: () async => false,
        // =>
        // SystemChannels.platform.invokeMethod('SystemNavigator.pop'),
      child:   Scaffold(
        appBar: AppBar(
          backgroundColor: Colors.white38,
          elevation: 0,
          leading: BackButton(color: Color(0xff324259),),
        ),
        body: isLoading==true?Form(
          key: formKey,
          child: ListView(
            padding: const EdgeInsets.all(20.0),
            children: [
              const SizedBox(height: 30),
              Container(
                child: Text("Login", style: TextStyle(fontWeight: FontWeight.bold,
                  fontSize: 40,),),
              ),
              Container(
                child: Text("Login with your ZeroHex Account",
                  style: TextStyle(fontWeight: FontWeight.bold,
                      fontSize: 20),),
              ),
              Center(
                child: Column(
                  children: [

                    const SizedBox(height: 70),
                    buildEmail(),
                    const SizedBox(height: 20),
                    buildPassword(),
                    const SizedBox(height: 20),
                    buildLoginButton(context),
                  ],
                ),
              )
            ],
          ),
        ):SpinKitThreeBounce(
          color: Color(0xff324259),
      size: 50.0,
    ),
      ),
    );

  }

  TextButton buildCreateAccount(BuildContext context) {
    return TextButton(
      onPressed: () =>
          Navigator.push(
              context, MaterialPageRoute(builder: (context) => RegisterPage())),
      child: const Text('Not Registered ? Create an account'),
    );
  }

  Widget buildLoginButton(context) {
    return Column(
      children: [
        ElevatedButton(
          style: ElevatedButton.styleFrom(
              fixedSize: const Size(240, 50), primary: Color(0xff324259)),
          onPressed: () {
            final isValid = formKey.currentState.validate();
            setEmail(emailController.text);
            if (isValid) {
              print("Login pressed");
              Login()
                  .LoginAuth(emailController.text, passwordController.text)
                  .then((value) async {
                print("value: $value");
                token = value["token"];
                setFlag(true);
                // accountFlag = true;
                SharedPreferences prefs = await SharedPreferences.getInstance();
                prefs.setString('token', token);
                booleanValue(true);

                print(">>>>>:$token");

                Navigator.push(
                  context,
                  MaterialPageRoute(
                    builder: (context) => HomePage(accountFlag, '',''),
                  ),
                );
              });
            }
          },
          child: const Text('Login', style: TextStyle(
              color: Colors.white, fontWeight: FontWeight.bold, fontSize: 20),),
        ),
        buildCreateAccount(context),
        SizedBox(
          height: 10,
        ),
        Container(
          child: Text("OR", style: TextStyle(
              color: Colors.black, fontWeight: FontWeight.bold, fontSize: 20),),
        ),
        SizedBox(
          height: 30,
        ),
        ElevatedButton(
          style: ElevatedButton.styleFrom(
              fixedSize: const Size(240, 50), primary: Color(0xff324259)),
          onPressed: () {
            _walletConnect();

            ethUtils.initialSetup();
          },
          child: const Text('Connect your wallet', style: TextStyle(
              color: Colors.white, fontWeight: FontWeight.bold, fontSize: 20),),
        )
      ],
    );
  }

  TextFormField buildPassword() {
    return TextFormField(
      controller: passwordController,
      validator: (value) {
        if (value.isEmpty) {
          return 'enter password';
        }
      },
      obscureText: isPasswordNotVisible,
      decoration: InputDecoration(
        border: OutlineInputBorder(
          // borderSide: BorderSide(
          //   color: Colors.grey,
          // ),
          // borderRadius: BorderRadius.circular(30.0),
          borderSide: BorderSide.none,
          borderRadius: BorderRadius.circular(30),
        ),
        prefixIcon: const Icon(Icons.lock_outline),
        suffixIcon: IconButton(
          onPressed: () {
            setState(() {
              isPasswordNotVisible = !isPasswordNotVisible;
            });
          },
          icon: isPasswordNotVisible
              ? const Icon(Icons.visibility)
              : const Icon(Icons.visibility_off),
        ),
        hintText: 'Password',
      ),
    );
  }

  TextFormField buildEmail() {
    return TextFormField(
      keyboardType: TextInputType.emailAddress,
      controller: emailController,
      validator: (value) {
        const pattern = r'(^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$)';
        final regExp = RegExp(pattern); // uni code form mai reg exp dedi hai

        if (value.isEmpty) {
          return 'enter an email';
        } else if (!regExp.hasMatch(value)) {
          return 'enter valid email';
        }
      },
      decoration: InputDecoration(
        border: OutlineInputBorder(
          borderSide: BorderSide.none,
          borderRadius: BorderRadius.circular(30),
        ),
        prefixIcon: Icon(Icons.email_outlined),
        label: Text('Email'),
        hintText: 'xyz@email.com',
      ),
    );
  }
  setBalance(balance)async{
    SharedPreferences pref = await SharedPreferences.getInstance();
    setState(() {
      pref.setDouble("balance", balance);
      print("setWalletAddress/////////////////////////data: $balance");
    });
  }

  setWalletAddress(account)async{
    SharedPreferences pref = await SharedPreferences.getInstance();
    // pref.setDouble('walletAddress', balance);
    pref.setString('account', account);
    print("setWalletAddress////////////////////account: $account");
  }
  setToken(token)async{
    SharedPreferences prefs = await SharedPreferences.getInstance();
    prefs.setString('token', token);
    print("On boarding screen: $token");
  }
  setFlag(flag)async{
    SharedPreferences prefs = await SharedPreferences.getInstance();
    accountFlag= prefs.setBool('flag', flag);
    print("On boarding screen: $flag");
  }
  // setSession(session)async{
  //   SharedPreferences prefs = await SharedPreferences.getInstance();
  //   prefs.setString('session', session.toString());
  //   print("setSession from login: $session");
  //   // prefs.setString(session, session);
  // }
  var connector;
  _walletConnect() async {
    isLoading=false;
    connector = WalletConnect(
      bridge: 'https://bridge.walletconnect.org',
      clientMeta: const PeerMeta(
        name: 'WalletConnect',
        description: 'WalletConnect Developer App',
        url: 'https://walletconnect.org',
        icons: [
          'https://gblobscdn.gitbook.com/spaces%2F-LJJeCjcLrr53DcT1Ml7%2Favatar.png?alt=media'
        ],
      ),
    );
    print("connector: $connector");
    // setSession(connector);
    // Subscribe to events
    connector.on('connect', (session) => print("connector.on session: $session"));
    connector.on('session_update', (payload) => print("connector.on session_update payload: $payload"));
    connector.on('disconnect', (session) => print("connector.on session disconnect: $session"));
    // Create a new session
    print("connector.connected>>>>>>>>>>>>>>>>>>>>>>>>>${connector.connected}");
    if (!connector.connected) {
      session = await connector.createSession(
          chainId: 97,
          onDisplayUri: (uri) async => {print(uri), await launchUrl(Uri.parse(uri))});

      print("session,:${session.runtimeType}");
      print("my session: $session");
      // setSession(session);

    }
    account = session.accounts[0];
    setWalletAddress(account);
    ethUtils.getBalance(account).then((balance) {
      setState(() {
        _myData = balance;
        print("BALANCE DATATYPE: ${balance.runtimeType}");
        print("_myData DATATYPE: ${_myData.runtimeType}");
        setBalance(balance);
        print("!!!!!!!!!!!!!!!....!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!: $_myData");
        print("_myData: $session");
        MetamaskSignUp().SignUpAuth(account).then((value){
          setState(() {
            var token = value['token'];
            print("metamask sigup response1: $value");
            setFlag(false);
            booleanValue(true);
            // accountFlag = false;
            setToken(token);
            Navigator.push(
              context,
              MaterialPageRoute(
                builder: (context) => HomePage(accountFlag, connector, session),
              ),
            );
          });
        });
        // setState(() {});
      });
    });

    if (account != null) {
      print('account != null $rpcUrl');
      final client = Web3Client(rpcUrl, Client());
      print("client:$client");
      EthereumWalletConnectProvider provider =
      EthereumWalletConnectProvider(connector);
      ethUtils.getDeployedContract(contractAddress, client);
    }

    print("////////////////////////////////////a,$account");
  }
}
`
