### ISSUE TITLE
[in_app_purchase] Subscription error in production for Android

### ISSUE THREAD

**Issue by viktor-morin** [flutter/flutter#105548]
Hi eveyone,
I tested my app in development for both iOS and Android and it worked fine.
But for production, Android dosnt work.
I use subscriptions (monthly payment) and for Android it simple says:
"Something went wrong on our end. Please try again later".

As long as i pass in my testaccount for applicationUserName I get into the test enviroment and all works fine.
But not for production. Does anyone have a clue whats wrong? 

My sign config looks as following:
```
signingConfigs {
    release {
        keyAlias keystoreProperties['keyAlias']
        keyPassword keystoreProperties['keyPassword']
        storeFile file(keystoreProperties['storeFile'])
        storePassword keystoreProperties['storePassword']
    }

}
buildTypes {
        release {
            signingConfig signingConfigs.release
            ndk {
                abiFilters 'arm64-v8a', 'armeabi-v7a', 'x86_64'
            }
        }
        debug {
            signingConfig signingConfigs.release
        }
    }
```

Same issue people where talking about 1 year ago here:
https://github.com/flutter/flutter/issues/35741

The output is following:

```
Couldn't find purchase lists, trying to find single data.
Received a bad purchase data.
Couldn't find single purchase data as well.
```

**Comment by viktor-morin** [comment]
After more debugging I found that _listenToPurchaseUpdate returned an object with following error message:
```
Invalid obfuscated account id
```

Following code seems to fix the issue:
```dart
  if (Platform.isAndroid) {
    var purchaseParam = PurchaseParam(productDetails: productDetails);
    return InAppPurchase.instance.buyNonConsumable(purchaseParam: purchaseParam);
  } else {
    var purchaseParam = PurchaseParam(productDetails: productDetails, applicationUserName: userName);
    return InAppPurchase.instance.buyNonConsumable(purchaseParam: purchaseParam);
  }
```

**Comment by viktor-morin** [comment]
The app is published, but when I signup for a subscription is shows me the "test-card-payment".
This Google account has no connection to my organization?

**Comment by darshankawar** [comment]
> shows me the "test-card-payment".
> This Google account has no connection to my organization?

This is probably happening because you passed the `applicationUserName`  that seems to be your test account per your earlier comment and may not be recognized in production.



> Invalid obfuscated account id

This could probably be an indication as why the error in production could be occuring. It seems the account id being obfuscated by Google play is invalid somehow. Can you try by using `obfuscatedProfileId` instead and see if it helps ?

See [this](https://github.com/flutter/flutter/issues/83651#issuecomment-855684530) for reference.

**Comment by viktor-morin** [comment]
Problem is solved, you can close this ticket.

Removing `applicationUserName ` for Android solved the issue, and after doing a `factory reset` on my test phone and use a new Google account not connected to my organization, I was prompt to use a real credit card.

**Note:**
The error message for sending in a "bad" `applicationUserName ` should be better, or atleast at that to the documentation.
