### ISSUE TITLE
Turndown unused flutter chromium.googlesource.com repos

### ISSUE THREAD

**Issue by yusuf-goog** [flutter/flutter#105556]
The flutter related mirrors have moved over to their own host, and the older ones should be turned down. E.g.:

https://chromium.googlesource.com/external/github.com/flutter/engine

Note to check if googlesource search is based on these older ones.

**Comment by keyonghan** [comment]
This needs a gob-ctl command to cleanup.

**Comment by yusuf-goog** [comment]
These repos have been moved over for a while to https://flutter.googlesource.com/

**Comment by yusuf-goog** [comment]
Checked with codesearch config and could not find any lingering references to chromium host.

**Comment by yusuf-goog** [comment]
confirmed the mirrors are running and up to date for the following repos:

  repo: "chromium/external/github.com/flutter/cocoon"
  repo: "chromium/external/github.com/flutter/engine"
  repo: "chromium/external/github.com/flutter/flutter"
  repo: "chromium/external/github.com/flutter/plugins"
  repo: "chromium/external/github.com/flutter/packages"

and these seem obsolete:

  repo: "chromium/external/github.com/flutter/flutter_gcm"
  repo: "chromium/external/github.com/flutter/infra"

**Comment by yusuf-goog** [comment]
Opened bug against chromium team to archive these repos: https://bugs.chromium.org/p/chromium/issues/detail?id=1474113

**Comment by yusuf-goog** [comment]
According to their response, the repos will not be archived/deleted per existing strict policy requires are filled.

**Comment by yusuf-goog** [comment]
FYI: Descriptions of the old projects have been updated to reflect their deprecation.
