### ISSUE TITLE
Add prefix/suffix support to TextField

### ISSUE THREAD

**Issue by paolosoares** [flutter/flutter#10559]
Per the Material design spec:

https://material.io/guidelines/components/text-fields.html#text-fields-input-types

**Comment by eseidelGoogle** [comment]
Let us know what the priority on this is for you.  Presumably possible to do yourself?  Or we certainly could augment TextInput to make it possible to do things like this yourself.

**Comment by paolosoares** [comment]
Low priority. It's just something I notice we deviate from the spec and that we might want change in the future.

**Comment by gspencergoog** [comment]
FYI, I have something for this already coded.  Just writing some tests.
