### ISSUE TITLE
[Impeller] Wire-up EGL presentation time.

### ISSUE THREAD

**Issue by iskakaushik** [flutter/flutter#105597]

**Comment by jonahwilliams** [comment]
The usage of this API caused several regressions in the last stable:

* https://github.com/flutter/flutter/issues/112603
* https://github.com/flutter/flutter/issues/110885

We should exercise _extreme_ caution if we try and use this API at all

**Comment by jonahwilliams** [comment]
First link should be: https://github.com/flutter/flutter/issues/111376

**Comment by chinmaygarde** [comment]
The linked patch was reverted and I am not sure we have decided if we should attempt this. Closing this for now.
