### ISSUE TITLE
Codelabs "Firebase for Flutter" - Firebase Database security rules typo

### ISSUE THREAD

**Issue by DrPhil** [flutter/flutter#10551]
The security rules for the Firebase database at https://codelabs.developers.google.com/codelabs/flutter-firebase/#8 has an error.
It is:
```
{
  "rules": {
    "messages": {
      ".read": true,
      ".write": "auth != null && auth.provider == 'google'"
    }
}
```
but should be
```
{
  "rules": {
    "messages": {
      ".read": true,
      ".write": "auth != null && auth.provider == 'google'"
    }
  }
}
```
(Note the missing **}** in the existing code.)

**Comment by eseidelGoogle** [comment]
FYI @LarkAscending

**Comment by LarkAscending** [comment]
Thanks! Updated..
The publication request for the codelab has completed: 
kiosk: https://kiosk-dot-codelabs-site.appspot.com/codelabs/flutter-firebase 
web: https://codelabs.developers.google.com/codelabs/flutter-firebase
