### ISSUE TITLE
How can I get older flutter version source code ?

### ISSUE THREAD

**Issue by xiaoxiaowesley** [flutter/flutter#105568]
I want to get the v1.9.1 version flutter source.

Here is my .gclient
```
solutions = [
  {
    "managed": False,
    "name": "src/flutter",
    "url": "https://github.com/flutter/engine.git@v1.9.1",
    "deps_file": "DEPS",
    "safesync_url": "",
  },
]
target_os = ['ios','android']
```

But when I `gclient sync`. I always suck in sync project tonic. It seem non-googler can access [https://fuchsia.googlesource.com/tonic](https://fuchsia.googlesource.com/tonic ) anymore. 

How I can get the source code v1.9.1?

**Comment by maheshmnj** [comment]
Hi @xiaoxiaowesley, Thanks for filing the issue. This doesn't seem like a valid URL `https://github.com/flutter/engine.git@v1.9.1`  Can you please take a look at this wiki https://github.com/sony/flutter-embedded-linux/wiki/Building-Flutter-Engine-from-source and see if it helps answer your question?

**Comment by xiaoxiaowesley** [comment]
> Hi @xiaoxiaowesley, Thanks for filing the issue. This doesn't seem like a valid URL `https://github.com/flutter/engine.git@v1.9.1` Can you please take a look at this wiki https://github.com/sony/flutter-embedded-linux/wiki/Building-Flutter-Engine-from-source and see if it helps answer your question?

I follow the wiki you offered.
And I change another URL with commitId [https://github.com/flutter/engine/commit/cc88fa45dbf4c55bc23cecea17fb90f43bccf588](https://github.com/flutter/engine/commit/cc88fa45dbf4c55bc23cecea17fb90f43bccf588)

```
solutions = [
  {
    "managed": False,
    "name": "src/flutter",
    "url": "https://github.com/flutter/engine.git@cc88fa45dbf4c55bc23cecea17fb90f43bccf588",
    "deps_file": "DEPS",
    "safesync_url": "",
  },
]
target_os = ['ios','android']
```

But don't work which always shows me an alert to enter the user name and password to access project in fuchsia.googlesource.com

![image](https://user-images.githubusercontent.com/44207000/172754785-12c5ac52-0dcd-46f0-a5c9-23a78e841341.png)

**Comment by maheshmnj** [comment]
Thank for the update @xiaoxiaowesley, I will leave this issue open for further insights from the team

cc: @Chinmay-KB

**Comment by chinmaygarde** [comment]
The repo for Tonic (which is an obsolete dependency) is no longer present. I has asked on internal channels about what the recourse ought to be. cc @Hixie for followup.

**Comment by jonahwilliams** [comment]
Unfortunately a bunch of dependencies got delisted. While you can grab the flutter/engine source from github, gclient may not work anymore
