### ISSUE TITLE
Device emulator-5554 is not authorized, and I am not able to get any authorization dialog in my emulator 

### ISSUE THREAD

**Issue by CM-Sharan** [flutter/flutter#105507]
1. When I run flutter doctor in cmd I get a warning saying,
      [√] Connected device (3 available)
               
              ! Device emulator-5554 is not authorized.
                         You might need to check your device for an authorization dialog.

2. Later when I run flutter devices I get the following,
      [1] connected devices:

         Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22000.708]
         Chrome (web)      • chrome  • web-javascript • Google Chrome 102.0.5005.63
         Edge (web)        • edge    • web-javascript • Microsoft Edge 102.0.1245.30

        • Device emulator-5554 is not authorized.
        You might need to check your device for an authorization dialog.
3. I am not getting any authorization dialog in my emulator, my emulator is in developer mode, the USB debugging is ON and default 
    USB configuration is set to File Transfer
4. My emulator is not being detected and I am not able to run my flutter app in the emulator.

**Comment by exaby73** [comment]
Hello @CM-Sharan. Have you tried re-creating the emulator by deleting it and creating it again or testing with another emulator?

**Comment by CM-Sharan** [comment]
I have tried re-creating the emulator but the same issue keeps coming up.

**Comment by exaby73** [comment]
Can you check if [this][1] helps you?

[1]: https://stackoverflow.com/questions/26079838/android-studio-adb-error-device-unauthorized-please-check-the-confirmat

**Comment by CM-Sharan** [comment]
Thank you @exaby73
