### ISSUE TITLE
【windows】flutter run not work

### ISSUE THREAD

**Issue by guoqiang9160** [flutter/flutter#105506]
Launching lib\main.dart on Windows in debug mode...
Building Windows application...
CMake Error at CMakeLists.txt:3 (project):
  Failed to run MSBuild command:

    d:/Program Files/Microsoft Visual Studio/2022/Community/MSBuild/Current/Bin/amd64/MSBuild.exe

  to get the value of VCTargetsPath:

**Comment by guoqiang9160** [comment]
When developing a medical project, I tried to use Flutter Based on windows, but there was an error when running.

**Comment by huycozy** [comment]
Hi @guoqiang9160, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this. Please provide the output of `flutter doctor -v` as well.

Thank you!

**Comment by guoqiang9160** [comment]
I used idea before, and it was normal when I changed it to vscode last night. There is no problem at present.
