### ISSUE TITLE
Add @Generated annotation in Pigeon-generated java classes

### ISSUE THREAD

**Issue by romkal** [flutter/flutter#105653]
The standard `javax.annotation.Generated` annotation can be used by tooling to distinguish generated from non-generated classes.

It can be used to exempt those from some lint checks etc..

For reference a draft PR https://github.com/flutter/packages/pull/2225/commits/f2d77c5b657ba3aeebb1deb0776a4bd34d113078

**Comment by maheshmnj** [comment]
Hi @romkal, Thanks for filing the issue. Labeling this issue as a proposal and for further insights from the team.


cc: @gaaclarke

**Comment by gaaclarke** [comment]
Unfortunately we can't add this unconditionally since the "@Generated" annotation isn't available to the plugin template.  I've added a PR that will add it conditionally, PTAL.
