### ISSUE TITLE
I found that the Podfile file was missing when I created a new flutter project, I have a few questions.

### ISSUE THREAD

**Issue by see** [flutter/flutter#105602]
I found that the Podfile file was missing when I created a new flutter project, I have a few questions
1. How the flutter framework integrates with iOS projects
2. How to upgrade old projects to new integration methods

## Details

**Target Platform:**
**Target OS version/browser:**
**Devices:**

## Logs

<details>
<summary>Logs</summary>

```
```

```
```

</details>

**Comment by cedvdb** [comment]
i think it's generated once you run the project on ios

**Comment by maheshmnj** [comment]
Hi @see, Thanks for filing the issue.   

> I found that the Podfile file was missing when I created a new flutter project

I would say this is normal, if your `pubspec.yaml` contains any dependencies then on running `flutter pub get` the Podfile is generated.

For your rest of the "How to" questions I would suggest to please ask them on some other channels by clearly explaining your question with supporting examples and code samples (if required).
