### ISSUE TITLE
Flutter version upgrade

### ISSUE THREAD

**Issue by 132056135** [flutter/flutter#105676]
我的旧项目是1.22.3版本的 ，现在我想升级到3.0.0 或者 2.8.1版本的，会出现很多很多错误。我需要怎么做，才能更好的把我的原来的版本升级成功

_Translated using Google Translate_

My old project is version 1.22.3, and now I want to upgrade to version 3.0.0 or 2.8.1, there will be many, many errors. What do I need to do to better upgrade my original version successfully

**Comment by exaby73** [comment]
Hello @132056135. You can read the [migration guide](https://dart.cn/null-safety/migration-guide) to understand how to go about upgrading your project.
