### ISSUE TITLE
75% of windows/android testbeds in prod pool are dead

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#105628]
<img width="1103" alt="Screen Shot 2022-06-08 at 9 35 19 AM" src="https://user-images.githubusercontent.com/54558023/172670195-c4503003-d8e7-4836-ae54-bdd64a78dd13.png">

**Comment by yusuf-goog** [comment]
These went through a windows update and needed the dialogs to be manually accepted. Could do with via VNC into the machines. Bots are back up.
