### ISSUE TITLE
PageView sample not working

### ISSUE THREAD

**Issue by TheCarpetMerchant** [flutter/flutter#105692]
[This PageView sample code](https://api.flutter.dev/flutter/widgets/PageView-class.html) on flutter.dev isn't working.

**Comment by maheshmnj** [comment]
Hi @TheCarpetMerchant, It seems to work fine, if the issue persists please verify incognito  mode or by switching your network

<img width="987" alt="image" src="https://user-images.githubusercontent.com/31410839/172844011-89177268-5086-45d0-b2d6-2e3953dc58d7.png">

**Comment by TheCarpetMerchant** [comment]
It isn't scrollable. Might be something on my end with my Chrome browser, but it should be investigated even if that's the case, I can provide the necessary debug info.
Also, incognito mode doesn't work for that.

**Comment by maheshmnj** [comment]
> It isn't scrollable

Ah, I see, Are you trying to drag and scroll? if so note that drag and scroll is disabled by default on the web starting stable 2.5 to mimic the native web platforms.This applies to all the scrolling widgets. However, this behavior can be restored to the old behavior.
 
see https://docs.flutter.dev/release/breaking-changes/default-scroll-behavior-drag

**Comment by TheCarpetMerchant** [comment]
Seems weird to me for a widget such as PageView to _not_ be scrollable by default, but ok.
