### ISSUE TITLE
Consider migrating to Vulkan on Android.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#105644]
Modern Android devices may not ship with a native OpenGL ES driver all. Instead, they may depend on Angle to perform translation of OpenGL ES to Vulkan.

Initial observations from source like this [Dolphin Emulator Progress Report (February, March, April 2022)](https://dolphin-emu.org/blog/2022/05/17/dolphin-progress-report-february-march-and-april-2022/#50-16174-fix-opengl-label-identifiers-for-angle-by-iwubcode) indicate that the Angle translation layer halves performance. From that article, performance on the Exynos 2200:
<img width="930" alt="Screen Shot 2022-06-08 at 12 36 20 PM" src="https://user-images.githubusercontent.com/44085/172706436-581ce9f6-7d69-4d54-9cd0-cbc562bfa0fd.png">

The trend of new devices not shipping with a native Open GL ES driver is likely to spread to lower end devices where Flutter may not have any headroom to spare for the translation layer.

The translation layer may also do additional shader compilation that will exacerbate issues related to shader compilation that affect jank instead of per frame performance.

Also, frame debuggers like [Android GPU Inspector](https://developer.android.com/agi) do not support capturing OpenGL ES frames natively. Instead, resorting to the same Angle translation layer. This is already causing a poor debugging and instrumentation experience when analyzing GPU workloads and slowing down the team.

Flutter should ideally use all the capabilities of the users device and only using OpenGL ES is not achieving that goal.

**Comment by chinmaygarde** [comment]
Some context and history about Vulkan on Android with Flutter:
* There was a Flutter Vulkan Android backend basically since forever. Vulkan support was prototyped in Android before shipping with Fuchsia.
* There was never enough of an impetus to ship Vulkan on Android for the following reasons:
  * An additional backend would mean a larger Flutter engine. This was a hard sell in an environment where the size of the Flutter engine was already a concern. Per the [Android distribution dashboard](https://developer.android.com/about/dashboards), there is no Vulkan on about 26% of Android devices. So a Vulkan only engine would leave a lot of users behind.
  * Unlike in the Metal backend where inline texture composition went through the CoreVideo API where OpenGL ES textures could be transmuted to a Metal texture, no such abstraction exists in the Android embedder. Raw OpenGL handles are shared from plugins to the renderer. This substantially complicates porting plugins that provide textures for inline composition by the engine. Essentially, these plugins will have to operate in a mode where they are capable of both OpenGL and Vulkan (if the want to have the same reach as Flutter itself). Using extensions, Vulkan on Android has some of the same capabilities as iOS where OpenGL ES textures can be transmuted to Vulkan textures. But these extensions aren't available everywhere and also probably require some configuration on part of plugin.
  * Switching from OpenGL to Metal on iOS was relatively painful (as of this writing, it is only just completing). There was effectively no scenario in which we could fully move to a world where Flutter was Vulkan only on Android. So signing up to an ongoing maintenance burden was something the team wasn't eager to do. The priorities in recent quarters has also been towards improving performance on certain lower end device and this took up its bandwidth (and will probably continue to do so for some time).
* For this reason, the prototype Vulkan backend (which was bit-rotting) was removed in https://github.com/flutter/engine/pull/28239
<img width="405" alt="Screen Shot 2022-06-08 at 1 15 52 PM" src="https://user-images.githubusercontent.com/44085/172708963-927d7ac7-bc2f-4b0a-a3e1-386823ce15c1.png">
<img width="462" alt="Screen Shot 2022-06-08 at 1 15 05 PM" src="https://user-images.githubusercontent.com/44085/172708726-648364a8-f1a6-4720-8c64-3898e0dce4a3.png">

**Comment by chinmaygarde** [comment]
The latest bulletin on the Android Distribution Dashboard shows a stark increase in availability of Vulkan on Android.

Devices with no Vulkan availability dropped from 26% to 11% and Vulkan 1.1 availability went from 58% to 77%.

![Numbers](https://user-images.githubusercontent.com/44085/236959892-b1e0b8e6-bf0a-4a25-9fd6-a33c2eda3ef3.png)

**Comment by followthemoney1** [comment]
Is this only Android improvement? Such as I know the IOS, MacOS, and Windows can also work on Vulkan so maybe only the Web cannot.

**Comment by lisovyk** [comment]
Might be there are some updates on Vulkan after a few months? Reviewing my app's performance I see shader compilation jank – and the proposed solution in docs seems to be to use Impeller / Vulkan. Is it possible to distribute a Vulkan-version to the supported devices and a default one for those who don't support it yet?

**Comment by jonahwilliams** [comment]
The new Impeller renderer for Android is using a Vulkan backend, release progress can be tracked in https://github.com/flutter/flutter/issues/144398
