### ISSUE TITLE
Master Bug: Make all widgets accessible

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#10562]
We need to go through all the widgets in our library and insure that they are accessible.

**Comment by oscarcpozas** [comment]
How check if a widget is accessible?

**Comment by goderbauer** [comment]
Right now its a manual process: Turn on TalkBack on Android or VoiceOver on iOS and see if the widget can be used in a reasonable way with those techniques.

**Comment by jonahwilliams** [comment]
Lets close this along with the other "master" a11y bugs. It is too broad to be individually actionable and better suited to a milestone.

**Comment by jonahwilliams** [comment]
The work done here was tracked in individual bugs. Closing for now, reopen if you disagree.
