### ISSUE TITLE
Consult  the branch management issues

### ISSUE THREAD

**Issue by wangying3426** [flutter/flutter#105698]
Hi, consult some problems, I found that the stable and beta branches have some commits that are not in the master branch, for example, the stable branch is [11 commits ahead](https://github.com/flutter/flutter/compare/master...stable) master.
<img width="990" alt="Screen Shot 2022-06-09 at 9 19 30 PM" src="https://user-images.githubusercontent.com/4476512/172856833-10e13fc3-f6d5-4209-9493-053a88bd4699.png">

Should the ahead commits of stable and beta be merged to the master in the future? If so, when are these commits merged to the master?

Also, Could you explain the detail workflow of Master, Beta and Stable, please？

Thanks.

**Comment by maheshmnj** [comment]
Hi @wangying3426, those commits could be hotfixes or cherry-picks from the master. 
see: https://github.com/flutter/flutter/wiki/Flutter-build-release-channels to understand the flutter release channels.
Closing as this is neither a bug nor a feature request.

**Comment by wangying3426** [comment]
@maheshmnj I'd like to ask about the details of how beta  branch becomes stable branch. After beta tested, will we rename beta to stable and then create the beta branch from master again?
