### ISSUE TITLE
Requesting TextFormField documentation updates

### ISSUE THREAD

**Issue by EnduringBeta** [flutter/flutter#105603]
I've already made the code changes on my fork, but the guidance says to have an issue, so here it is!

Multiple times I have tried to use `TextFormField` without a form but while keeping validation. [The docs](https://api.flutter.dev/flutter/material/TextFormField-class.html) say this is possible, but one key piece of information isn't there that I'm probably not the only one to miss repeatedly.

> To use without a [Form](https://api.flutter.dev/flutter/widgets/Form-class.html), pass a [GlobalKey](https://api.flutter.dev/flutter/widgets/GlobalKey-class.html) to the constructor and use [GlobalKey.currentState](https://api.flutter.dev/flutter/widgets/GlobalKey/currentState.html) to save or reset the form field.

Namely, the `GlobalKey` used for the widget seems to need to be of type `<FormFieldState>`. Otherwise you don't have access to `validate()`, `save()`, `reset()`, etc.

I also noticed the use of "we" in there, which doesn't follow [passive voice guidance](https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#use-the-passive-voice-recommend-do-not-require).

**Comment by HansMuller** [comment]
Fixed in https://github.com/flutter/flutter/pull/105605
