### ISSUE TITLE
ImageFiltered Render Issue

### ISSUE THREAD

**Issue by JsouLiang** [flutter/flutter#105674]
The scenario is like this:
```
@override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.lightBlue,
      body: ListView(
        controller: _controller,
        children: <Widget>[
          ImageFiltered(
            imageFilter: ImageFilter.blur(
              sigmaX: 4,
              sigmaY: 4,
            ),
            child: Container(
              width: 50,
              height: 50,
              color: Colors.red,
            ),
          ),
          Container(
            height: 800,
          ),
        ],
      ),
    );
  }
```
this is the behavior:

https://user-images.githubusercontent.com/10297030/172775380-9c4757a6-9275-45d8-b256-60271605743e.mov

The engine is the latest version.
And I found this issue may be because of `Partial repaint` 

The second scenario is like this:
```dart
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.lightBlue,
      body: SingleChildScrollView(
        child: Row(
          children: [ImageFiltered(
            imageFilter: ImageFilter.blur(
              sigmaX: 4,
              sigmaY: 4,
            ),
            child: Container(
              width: 50,
              height: 50,
              color: Colors.red,
            ),
          ),
            Container(
              height: 800,
            ),],
        ),
      ),
    );
  }
```

https://user-images.githubusercontent.com/10297030/172793263-9e6678c4-9787-45eb-b779-351599b2455c.mov

The second  scenario and the first scenario may not be the same problem.
Because the second scenario I set the RasterCahe is nullptr, and don't use the partial repaint
```C++
// set the clip_rect is nullptr when Raster
CompositorContext::ScopedFrame::Raster() {
  std::optional<SkRect> clip_rect = std::nullopt;
  bool root_needs_readback = layer_tree.Preroll(
      *this, ignore_raster_cache, clip_rect ? *clip_rect : kGiantRect);
....
}

// set this when preoll and paint:
PrerollContext.raster_cache = nullptr;
PaintContext.raster_cache = nullptr;

```

**Comment by JsouLiang** [comment]
It is the ImageFilter diff rect  is calculated as an error value.
https://github.com/flutter/engine/blob/main/flow/layers/image_filter_layer.cc#L29

**Comment by rivella50** [comment]
Is this effect happen all the time?
Perhaps it has something to do with the flickering issue no one could reproduce so far:
https://github.com/flutter/flutter/issues/100522

**Comment by danagbemava-nc** [comment]
Issue is reproducible on `stable` and `master`. 

In my testing, I was only able to reproduce this on iOS. 


<details>
<summary>recordings</summary>

| iOS | macOS | 
| -- | -- |
| <video src="https://user-images.githubusercontent.com/88313112/172809466-1246b4c3-b816-4b4a-90dc-eb8a291fd61d.mp4" /> | <video src="https://user-images.githubusercontent.com/88313112/172809518-53ac9b8c-9b7c-475d-9f43-a50302edf180.mov" /> |

</details>


<details>
<summary>code sample</summary>

```dart
import 'dart:ui';

import 'package:flutter/material.dart';

class MyCustomScrollBehavior extends MaterialScrollBehavior {
  // Override behavior methods and getters like dragDevices
  @override
  Set<PointerDeviceKind> get dragDevices => {
    PointerDeviceKind.touch,
    PointerDeviceKind.mouse,
    // etc.
  };
}

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      scrollBehavior: MyCustomScrollBehavior(),
      home: const Scaffold(
        backgroundColor: Colors.black,
        body: BugTest(),
      ),
    );
  }
}

class BugTest extends StatefulWidget {
  const BugTest({Key? key}) : super(key: key);

  @override
  State<BugTest> createState() => _BugTestState();
}

class _BugTestState extends State<BugTest> {
  final ScrollController _controller = ScrollController();

  @override
  Widget build(BuildContext context) {

    return Scaffold(
      backgroundColor: Colors.lightBlue,
      body: ListView(
        physics: AlwaysScrollableScrollPhysics(),
        controller: _controller,
        children: <Widget>[
          ImageFiltered(
            imageFilter: ImageFilter.blur(
              sigmaX: 4,
              sigmaY: 4,
            ),
            child: Container(
              width: 50,
              height: 50,
              color: Colors.red,
            ),
          ),
          Container(
            height: 800,
          ),
        ],
      ),
    );
  }
}

```
</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.0.1, on macOS 12.3.1 21E258 darwin-arm, locale en-GB)
    • Flutter version 3.0.1 at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (3 weeks ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.67.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.42.0

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 12 (API 31) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64   • macOS 12.3.1 21E258 darwin-arm
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 102.0.5005.61
    ! Error: Nexus is not connected. Xcode will continue when Nexus is connected. (code -13)

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

```
[✓] Flutter (Channel master, 3.1.0-0.0.pre.1187, on macOS 12.3.1 21E258 darwin-arm, locale en-GB)
    • Flutter version 3.1.0-0.0.pre.1187 at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c951d2d7a0 (2 hours ago), 2022-06-09 07:38:08 +0200
    • Engine revision d5eff9c6a6
    • Dart version 2.18.0 (build 2.18.0-170.0.dev)
    • DevTools version 2.14.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.67.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.42.0

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 12 (API 31) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64   • macOS 12.3.1 21E258 darwin-arm
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 102.0.5005.61
    ! Error: Nexus is not connected. Xcode will continue when Nexus is connected. (code -13)

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by JsouLiang** [comment]
I may know why.
The reasons may be the ImageFilterLayer `AutoSaveLayer` bounds problem:
```

void ImageFilterLayer::Paint(PaintContext& context) const {
  ....
 // This change `child_paint_bounds` to `paint_bounds`
  Layer::AutoSaveLayer save_layer =
      Layer::AutoSaveLayer::Create(context, paint_bounds(), &paint);
  PaintChildren(context);
}
```
This is behavior:
https://user-images.githubusercontent.com/10297030/172814015-45bc17af-2acb-419d-ab14-0a0b440ac764.mov

Hello Jim, do you the why use child_paint_bounds?
cc @flar

**Comment by flar** [comment]
> I may know why. The reasons may be the ImageFilterLayer `AutoSaveLayer` bounds problem:
> 
> ```c++
> void ImageFilterLayer::Paint(PaintContext& context) const {
>   ....
>  // This change `child_paint_bounds` to `paint_bounds`
>   Layer::AutoSaveLayer save_layer =
>       Layer::AutoSaveLayer::Create(context, paint_bounds(), &paint);
>   PaintChildren(context);
> }
> ```
> 
> This is behavior:
> 
>  2022-06-09.17.24.55.mov 
> Hello Jim, do you the why use child_paint_bounds? cc @flar

The filter is applied to the contents of the save layer, so it needs an input with those dimensions. paint_bounds is the expanded dimensions that include all of the output of the filter so it is usually too large.

This isn't just an optimization, consider applying a blur filter to a content that is filled with a rectangle. The edge conditions of the blur need to be applied to the edge of that rectangle so the filter input needs to be the size of that rectangle. If we used paint_bounds then the input would have transparent pixel padding around that rectangle and thus the edge conditions would apply to the transparent pixels rather than the rectangle background.

**Comment by flar** [comment]
Is there an older version that doesn't have this issue? It could be something we've done with Diff bounds or various caching changes, but it could also be a Skia boundary condition issue.

If there is an older version that doesn't have the problem, bisecting might help pin down when it was added. Maybe try a version 4-6 months ago before we made a lot of recent changes to bounds code.

**Comment by JsouLiang** [comment]
> > I may know why. The reasons may be the ImageFilterLayer `AutoSaveLayer` bounds problem:
> > ```c++
> > void ImageFilterLayer::Paint(PaintContext& context) const {
> >   ....
> >  // This change `child_paint_bounds` to `paint_bounds`
> >   Layer::AutoSaveLayer save_layer =
> >       Layer::AutoSaveLayer::Create(context, paint_bounds(), &paint);
> >   PaintChildren(context);
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This is behavior:
> > 2022-06-09.17.24.55.mov
> > Hello Jim, do you the why use child_paint_bounds? cc @flar
> 
> The filter is applied to the contents of the save layer, so it needs an input with those dimensions. paint_bounds is the expanded dimensions that include all of the output of the filter so it is usually too large.
> 
> This isn't just an optimization, consider applying a blur filter to a content that is filled with a rectangle. The edge conditions of the blur need to be applied to the edge of that rectangle so the filter input needs to be the size of that rectangle. If we used paint_bounds then the input would have transparent pixel padding around that rectangle and thus the edge conditions would apply to the transparent pixels rather than the rectangle background.

@flar hi, a question that if I use the `ImageFilterLayer` to `Blur` the `red rect` which picture behaves normally
<img src="https://user-images.githubusercontent.com/10297030/172979247-aac5355f-cf69-402f-9bb1-e37722ae692c.png" width=200px/>   <img src="https://user-images.githubusercontent.com/10297030/172979262-621e6bf0-d940-4717-8868-bdd7b4465290.png" width=200px/>

**Comment by JsouLiang** [comment]
> Shouldn't the diff method of ImageFilterLayer (and ColorFilterLayer for that matter) update the transform of the diff context to the pixel snapped version?
> 
> OpacityLayer:
> 
> https://github.com/flutter/engine/blob/main/flow/layers/opacity_layer.cc#L25-L28
> 
> ImageFilterLayer:
> 
> https://github.com/flutter/engine/blob/main/flow/layers/image_filter_layer.cc#L14

@jonahwilliams do you mean this:
```

void ImageFilterLayer::Diff(DiffContext* context, const Layer* old_layer) {
  ...
  #ifndef SUPPORT_FRACTIONAL_TRANSLATION
  context->SetTransform(
        RasterCache::GetIntegralTransCTM(context->GetTransform()));
  #endif
  DiffChildren(context, prev);
  ....
}
```

**Comment by flar** [comment]
> @flar hi, a question that if I use the `ImageFilterLayer` to `Blur` the `red rect` which picture behaves normally? <img alt="" width="200px/" src="https://user-images.githubusercontent.com/10297030/172979247-aac5355f-cf69-402f-9bb1-e37722ae692c.png"> <img alt="" width="200px/" src="https://user-images.githubusercontent.com/10297030/172979262-621e6bf0-d940-4717-8868-bdd7b4465290.png">

If this is the code in the original description then it should be just a large red rectangle because the default tile mode for the blur is clamp. The one on the right looks like it was rendered with a decal tile mode.

Skia attempts to ensure proper edge conditions for blur filters, but they still have some bugs that sometimes crop up.

**Comment by flar** [comment]
> Shouldn't the diff method of ImageFilterLayer (and ColorFilterLayer for that matter) update the transform of the diff context to the pixel snapped version?
> 
> OpacityLayer:
> 
> https://github.com/flutter/engine/blob/main/flow/layers/opacity_layer.cc#L25-L28
> 
> ImageFilterLayer:
> 
> https://github.com/flutter/engine/blob/main/flow/layers/image_filter_layer.cc#L14

That sounds like an issue. Paging @knopp

**Comment by JsouLiang** [comment]
@flar These pictures are the demo code behaves. So you mean the display on the right is right? But you can see the left edge on the right picture that has some difference with other edges.

**Comment by knopp** [comment]
There seem to be few a issues causing this:
- `ImageFilterLayer::Preroll` doesn't apply `GetIntegralTransCTM` before calling `TryToPrepareRasterCache` (see `OpacityLayer`).
- `ImageFilterLayer::Paint`  doesn't apply `GetIntegralTransCTM` before painting cached layer (also see `OpacityLayer`)
- `ImageFilterLayer::paint_bounds` in `Preroll` is calculated subtly wrong (filter should be applied in device coordinates so that it is identical with filter bounds adjustment in `::Diff`. But I think this one shouldn't cause rendering artifacts.
-  `GetIntegralTransCTM` seem to be missing in other layers that cache things (i.e. `ColorFilterLayer`, `ShaderMaskLayer` and `TryToPrepareRasterCache`).

**Comment by knopp** [comment]
> > Shouldn't the diff method of ImageFilterLayer (and ColorFilterLayer for that matter) update the transform of the diff context to the pixel snapped version?
> > OpacityLayer:
> > https://github.com/flutter/engine/blob/main/flow/layers/opacity_layer.cc#L25-L28
> > ImageFilterLayer:
> > https://github.com/flutter/engine/blob/main/flow/layers/image_filter_layer.cc#L14
> 
> That sounds like an issue. Paging @knopp

Not in `::Diff` (`ImageFilterLayer` doesn't have any offset like `OpacityLayer`), but everywhere else (before `TryToPrepareRasterCache` and painting) the matrix needs to be adjusted to pixel snapped version.

**Comment by flar** [comment]
I think the Integral CTM probably matters more in cases where there might be a 1:1 pixel blit (opacity, dl_picture, sk_picture) but ImageFilter won't be blitting the children, it will be using them as an input. If a layer is caching itself it probably matters more as that cache draw won't apply any filters (potentially just an alpha in the case of OpacityLayer).

**Comment by knopp** [comment]
> I think the Integral CTM probably matters more in cases where there might be a 1:1 pixel blit (opacity, dl_picture, sk_picture) but ImageFilter won't be blitting the children, it will be using them as an input. If a layer is caching itself it probably matters more as that cache draw won't apply any filters (potentially just an alpha in the case of OpacityLayer).

The issue is that `DiffContext` uses takes integral CTM into account when computing bounds of each layer.  The coordinates calculated in Diff must match exactly coordinates where layer will be painted. That means using integral CTM in `TryToPrepareRasterCache` and Integral CTM before painting cached layer. If we don't do this the layer will be painted on slightly different location when using raster cache as it would be without, which causes these artefacts.

You can verify this by 
-  Disabling raster cache 
-  Snapping the matrix to integer in `Preroll` and `Paint` like in OpacityLater

Any of these will fix the issue. I'll work on a PR.

**Comment by flar** [comment]
> > I think the Integral CTM probably matters more in cases where there might be a 1:1 pixel blit (opacity, dl_picture, sk_picture) but ImageFilter won't be blitting the children, it will be using them as an input. If a layer is caching itself it probably matters more as that cache draw won't apply any filters (potentially just an alpha in the case of OpacityLayer).
> 
> The issue is that `DiffContext` takes integral CTM into account when computing bounds of each layer. The coordinates calculated in Diff must match exactly coordinates where layer will be painted. That means using integral CTM in `TryToPrepareRasterCache` and Integral CTM before painting cached layer. If we don't do this the layer will be painted on slightly different position when using raster cache as it would be without, which causes these artefacts.
> 
> You can verify this by
> 
> * Disabling raster cache
> * Snapping the matrix to integer in `Preroll` and `Paint` like in `OpacityLayer`
> 
> Any of these will fix the issue. I'll work on a PR.

My point was not about bounds agreement between the passes, I was saying that we care about exact pixel alignment in cache::draw otherwise we can leave a fair bit of performance on the table on lower end devices.

Integer CTM was created to help with that performance consideration. The headaches about how to get all of the bounds in all of the passes to agree are just side effects of having to use this performance trick.

Having said that, I'm not sure anyone has verified if the performance still matters (and there are potentially other ways to achieve the "pixel for pixel blit" without having to slam all of the CTMs.

OpacityLayer ends up with a cache entry that can match pixels corner-by-corner center-by-center exactly and so it needs the Integer CTM to ensure performance.

Layers that mostly are used for blur operations only use the cache entry as an input to a filter and so they never measure the pixels of the cache entry against the pixels on the destination because there is a complicated filtering system that is in the way which will dice and slice the pixels anyway.

Thus, Integer CTM mangling matters to OpacityLayer in terms of performance. But it doesn't so much matter to the other layers.

Having said that, once we've chosen that a particular layer cares about Integer CTM, then we need to make sure it matches across the various passes and methods on the layer.

**Comment by flar** [comment]
I just noticed that Dl_layer and SkP_layer also use it just for rendering. I think that was a boon for trying to avoid AA rectangles all over the place, but I'm not sure again how much that matters. So, DL/SkP layers also inherit that practice for their cached blits should they be cached.

**Comment by JsouLiang** [comment]
> > I think the Integral CTM probably matters more in cases where there might be a 1:1 pixel blit (opacity, dl_picture, sk_picture) but ImageFilter won't be blitting the children, it will be using them as an input. If a layer is caching itself it probably matters more as that cache draw won't apply any filters (potentially just an alpha in the case of OpacityLayer).
> 
> The issue is that `DiffContext` takes integral CTM into account when computing bounds of each layer. The coordinates calculated in Diff must match exactly coordinates where layer will be painted. That means using integral CTM in `TryToPrepareRasterCache` and Integral CTM before painting cached layer. If we don't do this the layer will be painted on slightly different position when using raster cache as it would be without, which causes these artefacts.
> 
> You can verify this by
> 
> * Disabling raster cache
> * Snapping the matrix to integer in `Preroll` and `Paint` like in `OpacityLayer`
> 
> Any of these will fix the issue. I'll work on a PR.

I try to use the Integer CTM to fix the issue. And then this scenario is normal.

https://user-images.githubusercontent.com/10297030/173186148-08e8e350-deae-421f-aebc-0cad65ce7c6c.mov

**Comment by flar** [comment]
I disagree with the solution. Whereas caching can vary the result subtly from uncached rendering, that can be fixed in ways other than slamming all CTMs to integer translations.

**Comment by knopp** [comment]
But raster cache already does that. Every time you paint raster cached layer the translation is already slammed to integer. The only difference being is that when painting raster cached layer the integer coordinates are determined through `SkRect::roundOut` (`RasterCache::GetDeviceBounds`), whether as `RasterCache::GetIntegralTransCTM` uses `SkScalarRoundToScalar`.

**Comment by knopp** [comment]
Also if you don't raster snap before rasterizing layer you'll get subtly different cached layer depending on current scroll offset for example.

Don't get me wrong, I'm all for removing the `GetIntegralTransCTM` altogether, it just may need some rethinking of how raster cache paints.

**Comment by flar** [comment]
(Conversation was continued on https://github.com/flutter/engine/pull/33981)
