### ISSUE TITLE
Google Map Loading issue on iphone

### ISSUE THREAD

**Issue by parasvaid31** [flutter/flutter#105711]
We are using this plugin for loading google map with two marker only. 

It will more time while it is loading. 

Map view can show Google Text at bottom quickly but map loading will take more time.

**Comment by huycozy** [comment]
Hi @parasvaid31, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this. Please provide the output of `flutter doctor -v` as well.
Thank you!
