### ISSUE TITLE
[Web] Copying Image to Clipboard working on MacOS and Linux but Black screen on Windows

### ISSUE THREAD

**Issue by zambetpentru** [flutter/flutter#105790]
Hi,

I figured out how to get Images to copy successfully to the Clipboard from Flutter Web using some starting code I found in the rich_clipboard package (this package does not support images and the code below doesn't use that package). It turns out for some reason though the code below works in MacOS and Linux but in Windows Chrome / Edge / Opera it comes out as a black screen for some reason. 

Have you any insight why there is a difference between the client platforms and is it a Flutter framework bug?

*The pngBytes appears to be the same on all platforms so it appears to be on the transform / write where things are going wrong.

<details>
<summary>Flutter Doctor</summary>

[√] Flutter (Channel stable, 3.0.1, on Microsoft Windows [Version 10.0.22598.1], locale en-IE)
    • Flutter version 3.0.1 at c:\code\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (3 weeks ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[X] Android toolchain - develop for Android devices
    X Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[√] Chrome - develop for the web
    • CHROME_EXECUTABLE = c:\code\rocketx\chromecorsarm.bat

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] VS Code (version 1.68.0)
    • VS Code at C:\Users\Rober\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.42.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22598.1]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 102.0.5005.63
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 102.0.1245.33

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 3 categories.

</details>

<details>
<summary>Sample code</summary>

```dart
import 'dart:html';
import 'package:js/js.dart';
import 'package:js/js_util.dart';
import 'package:flutter/material.dart';
import 'package:qr_flutter/qr_flutter.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(home: const MyHomePage());
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  var image;

  void _createandcopyQRCode() async {
    final image = await QrPainter(
      data: "https://www.slashdot.org",
      version: QrVersions.auto,
      errorCorrectionLevel: QrErrorCorrectLevel.H,
    ).toImageData(400);

    var pngBytes = image!.buffer.asUint8List();

    final clipboard = window.navigator.clipboard as _Clipboard?;
    if (clipboard == null) {
      return;
    }

//DOES not work on Firefox due to limitations in Clipboard API

    final dataMap = <dynamic, dynamic>{
      'image/png': Blob([pngBytes], 'image/png')
    };

    var out = jsify(dataMap);
    final item = _ClipboardItem(out);
    await clipboard.write([item]);

    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text('You have copied the QR Code this many times:'),
            Text('$_counter', style: Theme.of(context).textTheme.headline4),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _createandcopyQRCode,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}

@JS('ClipboardItem')
@staticInterop
class _ClipboardItem {
  external _ClipboardItem(dynamic args);
}

@JS('Clipboard')
@staticInterop
class _Clipboard {}

extension _ClipboardImpl on _Clipboard {
  @JS('write')
  external dynamic _write(List<_ClipboardItem> items);
  Future<void> write(List<_ClipboardItem> items) => promiseToFuture(_write(items));
}

```
</details>

**Comment by huycozy** [comment]
Hi @zambetpentru
It looks like you are approaching `Copying Image to Clipboard` functionality using 3rd party plugins rather than to Flutter itself.  For example, `js` dependency issue should be opened in the dedicated [dart-lang/sdk repository](https://github.com/dart-lang/sdk/) and the same to `qr_flutter`.

FYI: There is in-progressing issue #32045 related to this issue (official supporting image for clipboard in Flutter).

So, if you still want to handle the issue by yourself approach, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that represents the problem (without 3rd party plugins). Otherwise, I will close this issue as a duplicate of #32045.

Thanks!

**Comment by zambetpentru** [comment]
Hi @huycozy, okay cheers let me come back to you with an example without the external packages.

**Comment by zambetpentru** [comment]
Hi @huycozy, I couldn't easily extract the js package pieces as it depends on internal dart packages so I took your advice and have raised it in the dart-lang/sdk repo here: https://github.com/dart-lang/sdk/issues/49299
