### ISSUE TITLE
Selectable Text should select the related characters on double tap

### ISSUE THREAD

**Issue by Dall127** [flutter/flutter#105723]
## Use case
When using selectable text, the ability to double tap to retrieve entire concept using a pictograms (as shown below) would be super helpful, as selecting one of the many pictograms does not give entire concept. I query a dictionary based off of a user's selection, but the behavior does not translate well to languages with pictograms as the double tap behavior only selects a single pictogram. This behavior is shown on google when a language with pictograms is selected (screen recording below).

## Proposal

Support double tap for languages with Pictograms

https://user-images.githubusercontent.com/31700756/172924994-0d8de2a3-d286-45fc-9943-5cc097269f18.mp4

(Side-note: I apologize if I am using the wrong terminology, I'm not super familiar with non-latin based languages)

**Comment by maheshmnj** [comment]
Hi @Dall127, Thanks for filing the issue. Do you mean double-tap on non-English characters should select only that character as it happens with English Characters?  Please share reproducible steps along with a minimal sample code to address the issue better.

**Comment by Dall127** [comment]
@maheshmnj, actually the opposite; I will work on producing a minimum viable code sample today, but in the mean time, here's maybe a slightly better explanation. 

When double tapping on characters that are a part of a non-english language, it will only select a single pictogram (or symbol, I apologize for my lack of expertise here). But, as in my video demonstration, on google (the webpage) when you double tap a pictogram, they highlight the entire "word concept". In English, this is easy since a space determines what a word concept is. However,  in languages such as Chinese, a word concept might be 1, 2, 3+ symbols. If there is a way to have SelectableText support languages intuitive double tap (like the google webpage will do) that is the desired behavior I am inquiring about.

**Comment by Dall127** [comment]
## Example Code

Below is a Minimum Viable Sample code demonstrating the current behavior. The desired behavior is that of the screen-recording on my original post. 
<details code>

```
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
          appBar: AppBar(
            title: const Text("Minimal"),
          ),
          body: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              crossAxisAlignment: CrossAxisAlignment.stretch,
              children: const [
                SelectableText.rich(
                  TextSpan(
                    children: [
                      TextSpan(text: "This is test Text\n"),
                      TextSpan(text: "他の人はこちらも質問")
                    ],
                  ),
                  textAlign: TextAlign.center,
                )
              ])),
    );
  }
}

```
</details>

## Reproduce Screen-Recording-Behavior Steps: 

1.  Change language settings on google to Chinese
2. perform a google search 
3. find a non-url text (such as "google answers") 
4. double click throughout a string of text and notice that sometimes, more than one character is selected. This is the desired behavior in SelectableText.

**Comment by maheshmnj** [comment]
Thanks for the clarification @Dall127, I am labeling this issue as a valid feature request to match the native platforms 

### Flutter
https://user-images.githubusercontent.com/31410839/173289402-57686dd5-83e1-4f3a-aeb3-79671ca66510.mov


### Native

https://user-images.githubusercontent.com/31410839/173289651-2d1ac035-68af-4113-9f25-e645789c4a7e.mov


<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel stable, 3.0.2, on macOS 12.4 21F79 darwin-arm, locale en-IN)
    • Flutter version 3.0.2 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cd41fdd495 (5 days ago), 2022-06-08 09:52:13 -0700
    • Engine revision f15f824b57
    • Dart version 2.17.3
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-32, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.67.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.42.0

[✓] Connected device (3 available)
    • sdk gphone arm64 (mobile) • emulator-5554 • android-arm64  • Android 11 (API 30) (emulator)
    • macOS (desktop)           • macos         • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)              • chrome        • web-javascript • Google Chrome 102.0.5005.61

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

```
[✓] Flutter (Channel master, 3.1.0-0.0.pre.1237, on macOS 12.4 21F79 darwin-arm, locale en-IN)
    • Flutter version 3.1.0-0.0.pre.1237 at /Users/mahesh/Documents/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6062e40510 (64 minutes ago), 2022-06-12 23:53:08 -0400
    • Engine revision f80294b57e
    • Dart version 2.18.0 (build 2.18.0-180.0.dev)
    • DevTools version 2.14.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-32, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.67.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.42.0

[✓] Connected device (3 available)
    • sdk gphone arm64 (mobile) • emulator-5554 • android-arm64  • Android 11 (API 30) (emulator)
    • macOS (desktop)           • macos         • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)              • chrome        • web-javascript • Google Chrome 102.0.5005.61

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by maheshmnj** [comment]
cc: @chunhtai

**Comment by Dall127** [comment]
@maheshmnj @Piinks,  Do y'all know what the timeline might look for something of this nature? And, tangential, is there any way that I can assist? The project that I have been working on for almost a year and a half is getting close to release an alpha version, with this being an important feature.

**Comment by maheshmnj** [comment]
@Dall127 Unfortunately we cannot give you any timeline of when a particular bug will be fixed. Please see https://github.com/flutter/flutter/wiki/Issue-hygiene#priorities to understand how issues are prioritized.

**Comment by chunhtai** [comment]
remove selection label as this is for SelectableText not SelectionArea

**Comment by Renzo-Olivares** [comment]
This looks fixed on stable. I tried it on dartpad. Are you still experiencing this issue?

https://github.com/flutter/flutter/assets/948037/ca449aeb-d377-41a0-81f7-7dfeba45b44b

**Comment by Piinks** [comment]
Thanks for the update! We can close this issue then. :)
