### ISSUE TITLE
[path_provider] Convert to Pigeon

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#105735]
Part of https://github.com/flutter/flutter/issues/117844

- [x] `path_provider_android`
- [x] `path_provider_ios`
- [x] `path_provider_linux` - N/A, Dart-only.
- [x] `path_provider_macos`
- [x] `path_provider_windows` - N/A, Dart-only.

**Comment by stuartmorgan** [comment]
The main forcing function I had picked `path_provider` to cover was making sure that in a really simple use case where it's easy to evaluate, Pigeon wasn't generating a lot of duplicate code that would bloat the plugin. It doesn't look like duplicate code generation was improved yet (via helper method extraction); we should make sure that's done in a follow-up as part of this issue.

**Comment by stuartmorgan** [comment]
> It doesn't look like duplicate code generation was improved yet (via helper method extraction); we should make sure that's done in a follow-up as part of this issue.

I'll file a new set of separate issues about auditing each generator for duplicate output for clarity, rather than trying to track the tangential work here.
