### ISSUE TITLE
Suddenly cannot build flutter application

### ISSUE THREAD

**Issue by sirwes** [flutter/flutter#105727]
Hi,
I am building a flutter application and it was working just fine until I tried doing a debug build again and now I get this error on every physical device and emulator I have. I am using VSCode to do my development and it has an auto-fetch enabled to the flutter stable release.

This is what is in the debug console

Launching lib\main.dart on sdk gphone x86 in debug mode...
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/http-0.13.4/lib/src/base_request.dart:144:7: Error: The getter 'ponrethrow' isn't defined for the class 'BaseRequest'.
- 'BaseRequest' is from 'package:http/src/base_request.dart' ('/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/http-0.13.4/lib/src/base_request.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'ponrethrow'.
      ponrethrow;
      ^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/http-0.13.4/lib/src/base_request.dart:129:28: Error: A non-null value must be returned since the return type 'StreamedResponse' doesn't allow null.
- 'StreamedResponse' is from 'package:http/src/streamed_response.dart' ('/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/http-0.13.4/lib/src/streamed_response.dart').
  Future<StreamedResponse> send() async {
                           ^

FAILURE: Build failed with an exception.

* Where:
Script 'C:\src\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1156

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\src\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
BUILD FAILED in 15s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

**Comment by sirwes** [comment]
This problem popped up about 5 minutes ago. flutter doctor says everything is okay

**Comment by stuartmorgan** [comment]
You have edited the file that is failing to compile:
https://github.com/dart-lang/http/blob/0.13.4/lib/src/base_request.dart#L144

You should not edit files in your pub cache; you will need to restore the original version of the file.

Closing as this is not a Flutter bug.

**Comment by sirwes** [comment]
Hi, I didn't edit it, but deleting flutter and reinstalling it fixed the problem
