### ISSUE TITLE
dart.exe got flagged as virus by apex one/trend micro

### ISSUE THREAD

**Issue by Chris1234567899** [flutter/flutter#105704]
Similar to this issue (https://github.com/flutter/flutter/issues/58302) I ran into the problem, that dart.exe got flagged by anti malware software.
Anti malware software: Apex One security agent by trend micro.

![image](https://user-images.githubusercontent.com/12623865/172876393-ddc6926d-8027-463e-9895-ab2505a4cd27.png)

## Logs

<details>
<summary>Logs</summary>

```
```

flutter doctor -v
[√] Flutter (Channel master, 3.1.0-0.0.pre.1191, on Microsoft Windows [Version 10.0.19043.1320], locale en-US)
    • Flutter version 3.1.0-0.0.pre.1191 at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fc1710b41c (2 hours ago), 2022-06-09 09:08:09 -0400
    • Engine revision 47e374f632
    • Dart version 2.18.0 (build 2.18.0-170.0.dev)
    • DevTools version 2.14.0

[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at C:\Users\cm\AppData\Local\Android\sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[√] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] VS Code (version 1.67.2)
    • VS Code at C:\Users\cm\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.42.0

[√] Connected device (1 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86 • Android 11 (API 30) (emulator)

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
</details>

**Comment by huycozy** [comment]
Hi @Chris1234567899, thanks for filing the issue. 
I see there's an open issue addressing the case you described #46696.
Please drop a comment or add a reaction to the original comment on that issue.
Closing as a duplication, so please follow up on it for further updates.
