### ISSUE TITLE
Is it possible to downgrade compileSdkVersion to 30 at flutter module?

### ISSUE THREAD

**Issue by wangmir** [flutter/flutter#105752]
## Steps to Reproduce

I'm trying to produce my flutter application as aar to the customer, and customer requires to set compileSdkVersion to 30 because of there own application issue.

But, when I tried to downgrade compileSdkVersion to 30, it fails.

First, since flutter android module cannot customize build.gradle because all the `.android/` directory will be autogenerated, so I temporally fix flutter sdk itself. At `pacages/flutter_tools/templates/module/android/host_app_common/app.tmpl/build.gradle.tmpl`, I changed ths gradle template into, like below,

<details>
<summary>Gradle template fix</summary>

```gradle
def flutterPluginVersion = 'managed'

apply plugin: 'com.android.application'

android {
    compileSdkVersion 30

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    defaultConfig {
        applicationId "{{androidIdentifier}}.host"
        minSdkVersion 16
        targetSdkVersion 30
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        profile {
            initWith debug
        }
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
    }

}
buildDir = new File(rootProject.projectDir, "../build/host")
dependencies {
    implementation project(':flutter')
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'androidx.appcompat:appcompat:1.0.2'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
}

```
</details>

So, in that case, autogenerated gradle file also can be set to compileSdkVersion 30.

But, after that, when building sample application which uses our aar with compileSdkVersion 30, the error shows like,

```
Dependency 'androidx.window:window-java:1.0.0-beta04' requires 'compileSdkVersion' to be set to 31 or higher.
Compilation target for module ':app' is 'android-30'
```

But in case of this `androidx.window:window-java:1.0.0-beta04`, i cannot find any references at flutter sdk too.

## Questions

1. Are there any way to properly downgrade compileSdkVersion into 30?
2. If not, are there any temporal way to fix flutter sdk to downgrade compileSdkVersion at least..?

**Comment by stuartmorgan** [comment]
Flutter 3.0 has dependencies that require 31 (as you have discovered). If you want to remove that dependency you would need to build a custom Flutter engine, removing both that dependency any anything using it.

If you don't want to build a custom engine, you would need to use an earlier version of Flutter.

**Comment by wangmir** [comment]
@stuartmorgan Yes, I also think for custom engine as temporal solution (because eventually, we need to update to SDK 31). Can u give a hint to remove window-java:1.0.0-beta04 dependency from custom engine..?

**Comment by stuartmorgan** [comment]
https://github.com/flutter/flutter/wiki/Compiling-the-engine explains how to build the engine.
