### ISSUE TITLE
Unhandled exception: ProcessException: No such file or directory. then: Command PhaseScriptExecution failed with a nonzero exit code

### ISSUE THREAD

**Issue by gikwegbu** [flutter/flutter#105762]
Hello,
So I cloned a project which is running well on my colleagues mac to my own mac. Downloaded the flutter version and xcode that is being used for the project. I can build for android, but can't build for iOS.

I cloned another repository that I had created with my windows months back just for testing purpose, and I was able to build for both android and iOS.

I even created a dummy flutter project, just the usual boilerplate just to confirm, it still worked, but  I just can't get the work project to build for iOS.

Have followed the steps I saw on Stackoverflow and some githhub issues, didn't work. Now i'm confused.

OK, I saw a regex command  `grep -riL "<path to my flutter sdk>" "<path to my project directory>", ` I used this code on the dummy flutter project and the window's created flutter project, and I was able to see results, but when I ran it on the work's project, it was returning 'no such directory exist'.

My `flutter doctor` does not have any errors.

<details>
<summary>The error message</summary>

```bash
Unhandled exception:
ProcessException: No such file or directory
  Command: /Users/mac/Documents/flutter/bin/flutter assemble --no-version-check --output=/Users/mac/Library/Developer/Xcode/DerivedData/Runner-fperlolhnuairoccpmjpzyfkmzqr/Build/Products/Debug-iphonesimulator/ -dTargetPlatform=ios -dTargetFile=/Users/mac/Documents/GitHub/AmazeMobile /lib/main.dart -dBuildMode=debug -dIosArchs=x86_64 -dSdkRoot=/Applications/Xcode13.3.1.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator15.4.sdk -dSplitDebugInfo= -dTreeShakeIcons=false -dTrackWidgetCreation=true -dDartObfuscation=false -dEnableBitcode= --ExtraGenSnapshotOptions= --DartDefines=RkxVVFRFUl9XRUJfQVVUT19ERVRFQ1Q9dHJ1ZQ== --ExtraFrontEndOptions= -dCodesignIdentity=- debug_ios_bundle_flutter_assets
#0      _ProcessImpl._runAndWait (dart:io-patch/process_patch.dart:487:7)
#1      _runNonInteractiveProcessSync (dart:io-patch/process_patch.dart:632:18)
#2      Process.runSync (dart:io-patch/process_patch.dart:68:12)
#3      Context.runSync (file:///Users/mac/Documents/flutter/packages/flutter_tools/bin/xcode_backend.dart:92:42)
#4      Context.buildApp (file:///Users/mac/Documents/flutter/packages/flutter_tools/bin/xcode_backend.dart:448:34)
#5      Context.run (file:///Users/mac/Documents/flutter/packages/flutter_tools/bin/xcode_backend.dart:51:9)
#6      main (file:///Users/mac/Documents/flutter/packages/flutter_tools/bin/xcode_backend.dart:17:5)
#7      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:32)
#8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
Command PhaseScriptExecution failed with a nonzero exit code
```
</details>

<details>
<summary>flutter doctor</summary>

```bash
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.4, on macOS 12.4 21F79 darwin-x64, locale
    en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version
    32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.67.2)
[✓] Connected device (1 available)
[✓] HTTP Host Availability

• No issues found!
```
</details>

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 2.10.4, on macOS 12.4 21F79 darwin-x64, locale
    en-GB)
    • Flutter version 2.10.4 at /Users/mac/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (3 months ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version
    32.1.0-rc1)
    • Android SDK at /Users/mac/Library/Android/sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode13.2.1.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.67.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.42.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 102.0.5005.61

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

 Please, I can provide more details, if need be, I really need to get this application to run so I can continue my job.
 
 NB: The flutter version and that of xcode is what works on the project, upgrading the versions breaks the project, as the dependencies would have to be upgraded as well, that caused errors at first on my colleague's side

**Comment by huycozy** [comment]
@gikwegbu,
It seems I see the cause of this issue.
Look at this:

>   Command: /Users/mac/Documents/flutter/bin/flutter assemble --no-version-check --output=/Users/mac/Library/Developer/Xcode/DerivedData/Runner-fperlolhnuairoccpmjpzyfkmzqr/Build/Products/Debug-iphonesimulator/ -dTargetPlatform=ios -dTargetFile=/Users/mac/Documents/GitHub/AmazeMobile /lib/main.dart -dBuildMode=debug -dIosArchs=x86_64 -dSdkRoot=/Applications/Xcode13.3.1.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator15.4.sdk -dSplitDebugInfo= -dTreeShakeIcons=false -dTrackWidgetCreation=true -dDartObfuscation=false -dEnableBitcode= --ExtraGenSnapshotOptions= --DartDefines=RkxVVFRFUl9XRUJfQVVUT19ERVRFQ1Q9dHJ1ZQ== --ExtraFrontEndOptions= -dCodesignIdentity=- debug_ios_bundle_flutter_assets

and pay attention to `-dTargetFile=/Users/mac/Documents/GitHub/AmazeMobile /lib/main.dart`.
There is a redundant space on project name `AmazeMobile `.
Try to remove it and retry build/run project.

If the above finding is not helpful, try to follow these questions:
- Are you getting this error while archiving or while running `flutter run` command?
- Can you provide a complete `flutter run -v` output? It'll be huge so you can put that in a text file and share it here.

**Comment by gikwegbu** [comment]
ok, Thanks @huycozy , will try this out now

**Comment by gikwegbu** [comment]
OooooooooMG!!!!!!!!!!


Whaaaaaaaaaaat!!!!!!!!!!!!!!!!!!!!!!



I'll surely tell this story to my kids!!!!!


Just a Space almost ruined my tech career?

**Comment by gikwegbu** [comment]
Thank you sooooo much, I just removed the redundant space in the project name and it worked!!!!!!
