### ISSUE TITLE
https://pub.dev/packages/flutter_screen_recording

### ISSUE THREAD

**Issue by hemandroid** [flutter/flutter#105768]
https://pub.dev/packages/flutter_screen_recording

_Originally posted by @salime45 in https://github.com/flutter/flutter/issues/26805#issuecomment-544860871_

This plugin is completely outdated and it's not supporting Android version 10 or 11 and not even working for iOS

**Comment by stuartmorgan** [comment]
Issues with third-party packages need to be reported to their developers. Closing as this is not a Flutter issue.
