### ISSUE TITLE
Update web_engine Flutter Recipe to not rely on Xcode/iOS Simulator

### ISSUE THREAD

**Issue by eyebrowsoffire** [flutter/flutter#105721]
As part of https://github.com/flutter/flutter/issues/99885, the LUCI recipes for flutter must be updated to only run tests for Safari Desktop instead of iOS Safari. Since https://github.com/flutter/engine/pull/33757 has merged, we can now validate golden testing with Webkit via Desktop Safari instead of iOS, which removes the dependency on the iOS Simulator and Safari, which has been a source of flakiness on newer builds of macOS.

Looking through the recipe, a few things that might need updating:

1. The recipe actually installs Xcode twice per run. I believe that is just an error in the recipe itself, but after this change I think we should be able to get away with not installing Xcode at all for the web_engine tests, since we only installed Xcode for the iOS simulator previously.
2. macOS has some special logic to compile the tests in a separate test, so that the same compiled tests can be used for iOS and macOS Safari. This is no longer necessary since we will be running on only one browser
3. There is an `additionalArgs` variable in the recipe that is only updated in the macOS branch, but only used in a non-macOS path. As a result I think this variable is actually unnecessary and can just be removed.

Once the recipe is updated, we can make a small change to the .ci.yaml in the engine repo to remove the dependency on old Xcode/macOS. Once that lands, the build bots running older macOS versions can be upgraded.

**Comment by keyonghan** [comment]
Validated 3) works by removing the `additioinal_args`.
As for 1) removing [Xcode context](https://flutter.googlesource.com/recipes/+/refs/heads/main/recipes/engine/web_engine.py#167) fails the [build](https://ci.chromium.org/raw/build/logs.chromium.org/flutter/led/keyonghan_google.com/17a31e1f826dd10c5624fdfe100fb5d43b5eaf20dc2f7269bf20f1d22f7b2f98/+/build.proto?server=chromium-swarm.appspot.com): 
```
ERROR at //build/config/ios/ios_sdk.gni:45:9: Script returned non-zero exit code.
        exec_script("ios_sdk.py", ios_sdk_args, "list lines")
        ^----------
Current dir: /opt/s/w/ir/cache/builder/src/out/host_debug_unopt/
Command: python3 /opt/s/w/ir/cache/builder/src/build/config/ios/ios_sdk.py --sdk iphoneos
Returned 1.
stderr:

xcode-select: note: no developer tools were found at '/Applications/Xcode.app', requesting install. Choose an option in the dialog to download the command line developer tools.
```

**Comment by eyebrowsoffire** [comment]
I went ahead and filed https://github.com/flutter/flutter/issues/105805 as a follow-on task. For now, let's change the recipe so that Xcode is installed if a specific version is specified as a dependency in .ci.yaml, which it currently is. Once we clean up our build such that we don't need Xcode at all to perform the web build and run web tests, we will remove the dependency from .ci.yaml and the recipe should just skip the Xcode install.

**Comment by keyonghan** [comment]
After removing [line 192-209](https://flutter.googlesource.com/recipes/+/refs/heads/main/recipes/engine/web_engine.py#192), the [xcode context](https://flutter.googlesource.com/recipes/+/refs/heads/main/recipes/engine/web_engine.py#227), and updated `felt_test.append('run_tests_ios-safari')` to `felt_test.append('run_tests_safari')`, both old xcode and new xcode builds hit timeout issue on `paragraph_builder_test`:

xcode: 12c33: https://ci.chromium.org/raw/build/logs.chromium.org/flutter/led/keyonghan_google.com/dab788f47578dd54e0c98c0df321df945e14b835c69493bd5885babea4b2783a/+/build.proto?server=chromium-swarm.appspot.com
xcode: 13a233: https://ci.chromium.org/raw/build/logs.chromium.org/flutter/led/keyonghan_google.com/3e2e4d2dffb92f9bca5aa8a98fc36295b867606abd7b4a9ca0b4e7bf62be6ad1/+/build.proto?server=chromium-swarm.appspot.com

@eyebrowsoffire could you help take a look?

**Comment by eyebrowsoffire** [comment]
Can we try replacing lines 229-233 with:
```
            felt_test = copy.deepcopy(felt_cmd)
            felt_test.append('test')
            felt_test.append('--require-skia-gold')
            felt_test.append('--browser=safari')
            api.step(
                api.test_utils.test_step_name('Run tests on macOS Safari'), felt_test
            )
```

**Comment by keyonghan** [comment]
Both succeeded! ([old xcode](https://ci.chromium.org/raw/build/logs.chromium.org/flutter/led/keyonghan_google.com/d0904cd01476a1665ae40e99400a9113e5722f6acb41ac6de4f044cd58c5660f/+/build.proto?server=chromium-swarm.appspot.com) v.s.[ latest one](https://ci.chromium.org/raw/build/logs.chromium.org/flutter/led/keyonghan_google.com/608e071fe0e3f71c614fda82da5e51004eb39c32903e9b455593623737dc44de/+/build.proto?server=chromium-swarm.appspot.com))

Let me finishup the recipes cl.

**Comment by keyonghan** [comment]
Recipes landed. Closing assuming fixed.
