### ISSUE TITLE
FirebaseFirestore orderBy function not works with when function

### ISSUE THREAD

**Issue by devnoaman** [flutter/flutter#105703]
i have implemented this code for retrieving the messages of this room.

final messagesProvider = StreamProvider((ref) {
  FirebaseFirestore db = FirebaseFirestore.instance;
var room = ref.watch(roomIdProvider);
  print('room updated');
  print('room is '+room);
  final docRef = db
.collection("messages")

.where("chat_room_id",isEqualTo: room)
    // .orderBy('created_at')
    // .orderBy('created_at',descending: true)

;
print(docRef.orderBy("created_at").snapshots());

  return docRef.snapshots();
});
i want to sort the data and have tried these two lines separately but not worked for me

     .orderBy('created_at')
     .orderBy('created_at',descending: true)

where created at is a timestamp field.

**Comment by iapicca** [comment]
@devnoaman looks like a [firebase issue](https://github.com/firebase/flutterfire/issues)

**Comment by maheshmnj** [comment]
Hi @devnoaman, This issue doesn't seem to describe bug in flutter, Please report the issue in the flutterfire repo https://github.com/firebase/flutterfire/issues
