### ISSUE TITLE
`Scroll behavior: smooth` option for flutter web, such as in HTML/CSS

### ISSUE THREAD

**Issue by opxdelwin** [flutter/flutter#105722]
## Use case
For smoother scrolling in flutter web projects

## Proposal
Smooth scrolling while using trackpad in laptops but the issue/use case comes for desktop users. While scrolling on a mouse, the page feels janky/not-so-smooth. In HTML and CSS there's the option to add
```
html {
  scroll-behavior: smooth;
}
```

Moreover, you could see this suggestion in Lighthouse performance test.
![image](https://user-images.githubusercontent.com/84124091/172916617-8ea56868-4987-4a74-be86-da1c32013f3f.png)

Sample project here
Flutter: http://flutter-scrolling-cats.web.app/

HTML: https://flutter-scrolling-cats.web.app/plainhtml.html

Thanks to - https://www.reddit.com/r/FlutterDev/comments/lxw0ec/flutter_2_web_scrolling_performance/

Let it take time to implement, but this is an essential feature that flutter could benefit. This doesn't seem a major issue in moile devices

**Comment by maheshmnj** [comment]
Hi @opxdelwin,

There is a similar issue describing this case https://github.com/flutter/flutter/issues/56257, Please follow up there for further updates, Closing this issue as a duplicate. If you disagree feel free to write in the comments and we will reopen it.

Thank you.

**Comment by opxdelwin** [comment]
@maheshmnj I don't think it's a duplicate. My issue is that it only happens when a mouse is used. Let me attach videos.

Flutter WebApp using mouse scroll.

https://user-images.githubusercontent.com/84124091/173048514-2727c921-4e5f-4726-a6c4-6f69222fa067.mp4

Html page using mouse scroll.

https://user-images.githubusercontent.com/84124091/173048947-bf1926e0-cf5b-47bb-9d3c-e949c78f5d5b.mp4

If I'm using a trackpad on a laptop/desktop and/or on mobile its works absolutely fine with no issues. It's not about the frame drop, its about the sudden scroll

**Comment by opxdelwin** [comment]
Is there any way this case could be reopened?  @maheshmnj

**Comment by maheshmnj** [comment]
@opxdelwin I tried scrolling your app and it seems to scroll smoothly, I don't see abrupt scrolling as in your video


https://user-images.githubusercontent.com/31410839/173506056-d019a99f-bb65-44bb-a4fb-6b06c4a0b3a7.mov

**Comment by opxdelwin** [comment]
@maheshmnj did you use a mouse (not apple magic mouse as it uses touch). Use a mouse with physical scroll wheel.
![1655188104005753080347814795412](https://user-images.githubusercontent.com/84124091/173508375-24775360-010b-471f-a098-449cb8871a66.jpg)

**Comment by maheshmnj** [comment]
@opxdelwin  I did verify with an external mouse and scrolled with the wheel, But I do see smooth scrolling, Can you please share the output of `flutter doctor -v`? Also Can you check if this issue is in other browsers too e.g chrome?

**Comment by maheshmnj** [comment]
Thanks for the info @opxdelwin, I see a similar issue describing your case see https://github.com/flutter/flutter/issues/32120, Could you please confirm if that is the same issue?

**Comment by opxdelwin** [comment]
Yes, it's the same issue as that of #32120 , closing this thread.
