### ISSUE TITLE
Evaluate raster-caching while `dequeueBuffer` wait happens

### ISSUE THREAD

**Issue by iskakaushik** [flutter/flutter#105719]
Currently RasterCache is taking ~8% of the time on the raster thread for customer:money and most of it is CPU work. A lot of paths that get cached end up getting rasterized on the CPU, due to them having complex (or sometimes concave) paths, and falling back to software rasterization.

This creates the following scenario:

1. dequeueBuffer [blocking on GPU]
2. CPU-work
    a. RasterCache [causes a render target switch to render to texture]
    b. Paint [needs to happen on the on_screen surface]
3. queueBuffer [blocking on GPU]

Consider doing **2.a** while **1** happens, maybe on the IO thread pool to front-load some of the work.

**Comment by jonahwilliams** [comment]
We're going to remove the raster cache!
