### ISSUE TITLE
Some Future.catchError onError callbacks are missing returns

### ISSUE THREAD

**Issue by srawlins** [flutter/flutter#105750]
See this code:

```dart
void main() async {
  await Future<int>.error('error').catchError((e) {});
}
```

This code is guaranteed to throw a runtime error. However, there is currently no static error reported. As part of https://github.com/dart-lang/sdk/issues/49215, the dart analyzer will start to report static errors for code like this. Before analyzer can start reporting these static errors by default, the Flutter codebases must be cleaned of them.

**Comment by srawlins** [comment]
I plan on adding `// ignore:` directives to Flutter files to mitigate this.


Any code which is currently missing a return statement may require business logic knowledge to implement the correct fix.

**Comment by christopherfujino** [comment]
This is hurting my brain. So if you try to use the value wrapped by a future (say an `int` like in your example) but it was actually an implicitly returned `null`, would that be a runtime error? Is this a loophole in Dart's sound type system?

**Comment by srawlins** [comment]
> So if you try to use the value wrapped by a future (say an int like in your example) but it was actually an implicitly returned null, would that be a runtime error?

That's right.

> Is this a loophole in Dart's sound type system?

Insofar as `dynamic` is a loop hole. For example, you can write this code:

```dart
int f(Function x) => x();

void main() {
  int i = f(() => 'hello');
}
```

which is statically legal but guaranteed to fail at runtime.

**Comment by christopherfujino** [comment]
Fixed by https://github.com/flutter/flutter/pull/115184
