### ISSUE TITLE
Remove FlutterActivity#onFlutterReady()

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#10571]
As of https://github.com/flutter/engine/pull/3748, [`FlutterActivity#onFlutterReady()`](https://github.com/flutter/engine/blob/1f765cdba7aee9d0a953043209b05d2c59270391/shell/platform/android/io/flutter/app/FlutterActivity.java#L45) is no longer needed and has been deprecated
 — subclasses should just put their "on Flutter ready" logic on `#onCreate(Bundle)` after calling `super.onCreate()`

After sufficient time has passed to allow callers to stop using the method, we should remove it.

Unless anyone objects by commenting on this issue, the API removal is targeted for Wednesday, June 21 (two weeks from today).

**Comment by tvolkert** [comment]
Announcement: https://groups.google.com/forum/#!topic/flutter-dev/PfdpgLZ8hVI

**Comment by FaisalAbid** [comment]
This is such a great change, thanks @tvolkert
