### ISSUE TITLE
Typo in Codelabs "Firebase for Flutter" comment

### ISSUE THREAD

**Issue by DrPhil** [flutter/flutter#10578]
At https://codelabs.developers.google.com/codelabs/flutter-firebase/#9 there is a typo at:
```
// Add the following to the _buildTextCompose() method in ChatScreenState.
```
it should be
```
// Add the following to the _buildTextComposer() method in ChatScreenState.
```
where the typo is in the name `_buildTextComposer()`.

**Comment by DrPhil** [comment]
FYI @LarkAscending
(Sorry if this is the wrong person to notify, but you were notified last time...)

**Comment by LarkAscending** [comment]
Thank you! Fixed!
