### ISSUE TITLE
[Proposal] Add keyboard type namePhonePad

### ISSUE THREAD

**Issue by hemal-moradiya** [flutter/flutter#105816]
## Use case

I am trying to convert the native iOS application to the Flutter application. 

In iOS, there is a keyboard type **namePhonePad**. When the user switch to a numeric keyboard user only will see a numeric keyboard rather than showing a keyboard that has numbers and all punctuation sign

With the help of the [keyboard_actions](https://pub.dev/packages/keyboard_actions) dependency, I have created one custom keyboard and when the user switches keyboard alphabet to numeric, I am only showing the numeric keyboard without punctuation sign (just like keyboard type **TextInputType.number**)

## Proposal

It would be great If we have a keyboard type namePhonePad same as we have in iOS. Please take a look at the attached snapshots. This is what I am expecting.

When the user pressed button '123' as shown in the attached snapshot,
![Image 2022-06-11 at 10 37 27 AM](https://user-images.githubusercontent.com/68743842/173173680-e66d617f-61c7-41ff-be8d-8e321cbd6eb3.jpeg)

The keyboard type should be only numeric, as shown in below-attached picture

![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/68743842/173173714-d1e953b0-c67c-4e5f-9e87-9a6085ee0ae2.png)

It would be great If flutter has this type of keyboard type instead of using a custom keyboard feature from other dependencies.

**Comment by jmagman** [comment]
It looks like `TextInputType.name` maps to `UIKeyboardTypeNamePhonePad` should work as of flutter/engine#18202.

https://api.flutter.dev/flutter/services/TextInputType/name-constant.html

Does that work the way you expect?

**Comment by hemal-moradiya** [comment]
@jmagman  Yes, you're right. `TextInputType.name` maps to `UIKeyboardTypeNamePhonePad`. Thank you for pointing this out. Although, I have one question, What If first I want to open the numeric keyboard of `TextInputType.name`. Right now it opens an alphabetical keyboard and when I press `123` then after it's switched to the numeric keyboard. What If I want the numeric keyboard initially open? Is there any workaround for this?
