### ISSUE TITLE
unnecessary dependency of Firebase

### ISSUE THREAD

**Issue by samnaseri** [flutter/flutter#105867]
I need to sign in with Google. But I don't find a good solution to implement Sign In with Google button in my app. The main problem is that native android doesn't force me to use Firebase. But the official flutter plugin for Flutter requires me to use Firebase.

**Comment by asashour** [comment]
Firebase is not needed for using Google sign in, please see

- https://medium.com/flutter-community/flutter-sign-in-with-google-in-android-without-firebase-a91b977d166f
- https://morioh.com/p/52f8595e5915
- https://www.youtube.com/watch?v=E5WgU6ERZzA

**Comment by huycozy** [comment]
Hi @samnaseri 
Use above @asashour's tutorials or ask this in support channels like StackOverflow.

If you are proposing a change, please use the appropriate new issue template and fill out the requested details so that we can address this issue properly.

Closing for now.
