### ISSUE TITLE
We'd like to know what host OS version our users are using

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#10582]
We had a question about when/how to upgrade a dependency, which has a restriction on the host OS version. We went into analytics, and saw OS type but didn't see OS version. Specifically, we wanted to know what version of Mac OS our users are using.

cc @cbracken

**Comment by eseidelGoogle** [comment]
This may need support in package:usage?

**Comment by sethladd** [comment]
So, apparently we are attempting this info, line 30 of usage.dart: `   _analytics.setSessionValue('dimension1', os.name);`

Will continue to dig.

**Comment by sethladd** [comment]
This is what we're sending: `{utv: run, utt: 1253, utl: fail, utc: flutter, an: flutter, av: dev/ab30432fe4, ul: en-us, dimension1: Mac OS X 10.12.5 16F73, dimension2: dev, v: 1, tid: UA-67589403-6, cid: a652d13a-48c4-44e4-8c77-bc7574f4c062, t: timing}`

Note that `dimension1` is being set to a nice and verbose OS version and name.

**Comment by sethladd** [comment]
Ah, looks like custom dimensions should be set with `cd<index>` : https://developers.google.com/analytics/devguides/collection/protocol/v1/parameters#cd_

**Comment by devoncarew** [comment]
Ah, good catch :)
