### ISSUE TITLE
Set a threshold for passing or failing a golden test

### ISSUE THREAD

**Issue by yshean** [flutter/flutter#105870]
## Use case

Related to https://github.com/flutter/flutter/issues/36667, https://github.com/flutter/flutter/issues/100896, and https://github.com/flutter/flutter/issues/94729, we have faced issues needing to disable certain golden tests especially when running the tests on different platforms than when it was created. We would like to have an option to set a threshold in which to consider a golden test to pass or fail, so that we don't have to attend to our CI failures every time a failure happens because of a very small difference (e.g. 2.0% pixel difference). 

## Proposal

Can we pass an additional argument to the `flutter test` command, something like `--threshold 2.00` to consider a test (or a set of tests) to pass when the pixel difference is below 2.00%?

**Comment by danagbemava-nc** [comment]
Hi @yshean, can you take a look at [this comment](https://github.com/flutter/flutter/pull/77014#issuecomment-1048896776)  to see if it helps you achieve what you want to do?

**Comment by yshean** [comment]
Oh, I didn't know we could do it this way, thanks @danagbemava-nc! Let me give it a try:)

**Comment by danagbemava-nc** [comment]
Kindly update when you do.

Thanks
