### ISSUE TITLE
[go_router_builder] Support Enhanced enums

### ISSUE THREAD

**Issue by Riscait** [flutter/flutter#105876]
## Steps to Reproduce

1. Defines the Enhanced-enum that is now available in Dart 2.17.

```dart
enum Fruit {
  apple(themeColor: Colors.red),
  banana(themeColor: Colors.yellow),
  orange(themeColor: Colors.orange),
  ;

  const Fruit({required this.themeColor});

  final Color themeColor;
}
```

2. Define a TypedGoRoute that takes Fruit as an argument.

```dart
@TypedGoRoute<FruitRoute>(
  path: '/:fruit',
)
class FruitRoute extends GoRouteData {
  const FruitRoute({required this.fruit});

  final Fruit fruit;

  @override
  Widget build(BuildContext context) => const FruitPage();
}
```

3. Perform code generation. `flutter pub run build_runner build`
4. Build the application.
5. An error is displayed in the console and the build fails.
```shell
: Error: Member not found: 'themeColor'.
lib/…/router/app_routes.g.dart:204
  Fruit.themeColor: 'theme-color',
        ^^^^^^^^^^
```

It seems that go_router_builder also recognizes Enhanced-enum fields (themeColor in the example) as an value of Enum.

Both `go_router_builder` and `Enhanced-enum` are great features and should be used together.

I will add any missing information.

Thank you!

**Comment by danagbemava-nc** [comment]
I see some errors when I generate the code with the enhanced enums. 
Leaving this for further input from the team. 

<details>
<summary>flutter analyze</summary>

```
  error • The method '_$fromName' isn't defined for the type 'Map' • lib/fruit_route.g.dart:20:31 • undefined_method
  error • Const variables must be initialized with a constant value • lib/fruit_route.g.dart:36:3 •
         const_initialized_with_non_constant_value
  error • The keys in a const map literal must be constant • lib/fruit_route.g.dart:36:3 • non_constant_map_key
  error • Instance member 'themeColor' can't be accessed using static access • lib/fruit_route.g.dart:36:9 •
         static_access_to_instance_member
   info • The declaration '_$fromName' isn't referenced • lib/fruit_route.g.dart:40:5 • unused_element
```
</details>

Labeling as a proposal as this doesn't seem to be currently supported.

Project for easy repro

[egrb.zip](https://github.com/flutter/flutter/files/8890870/egrb.zip)
