### ISSUE TITLE
[TimePicker] Material 3 tokens have some issues

### ISSUE THREAD

**Issue by TahaTesser** [flutter/flutter#105899]
I want to update https://github.com/flutter/flutter/pull/99931 however there seem to be some token mishaps.

### There is no color token for the dial container (There should be a `surfaceVariant` token for this, onSurfaceVariant is the wrong color and it has `.ignore` for some reason) 

https://github.com/flutter/flutter/blob/712860d33b00bf3acf02118512901a6261ad5219/dev/tools/gen_defaults/data/time_picker.json#L4-L5

| Expected dial container color | There is no correct token, if `clock-dial.color.ignore` is used we get |
| --------------- | --------------- |
| <img src="https://user-images.githubusercontent.com/48603081/173376278-0b7f5067-d4e2-4bab-b69c-d73f7258cbb0.png" height="450" /> | <img src="https://user-images.githubusercontent.com/48603081/173377658-869bbdf7-c66d-4338-95ec-24d146ded374.png" height="450" /> |

#### Selected dial text color (`onSurface` is provided here to be on `primary` color)
https://github.com/flutter/flutter/blob/712860d33b00bf3acf02118512901a6261ad5219/dev/tools/gen_defaults/data/time_picker.json#L7

#### Unselected dial text color (`onPrimary` is provided here to be on `surfaceVariant ` color)

https://github.com/flutter/flutter/blob/712860d33b00bf3acf02118512901a6261ad5219/dev/tools/gen_defaults/data/time_picker.json#L17 

If we apply these color tokens, dial colors are not as expected.

| Preview | 
| --------------- | 
| <img src="https://user-images.githubusercontent.com/48603081/173377658-869bbdf7-c66d-4338-95ec-24d146ded374.png" height="450" />	|

![]()

**Comment by TahaTesser** [comment]
cc: @darrenaustin

**Comment by HansMuller** [comment]
CC @guidezpl

**Comment by guidezpl** [comment]
The tokens are final, but I'm seeing `md.sys.color.on-primary-container` for `md.comp.time-picker.time-selector.selected.label-text.color` so it's possible there's a data error?

**Comment by darrenaustin** [comment]
> The tokens are final, but I'm seeing `md.sys.color.on-primary-container` for `md.comp.time-picker.time-selector.selected.label-text.color` so it's possible there's a data error?

That is what is in the token json file: 

https://github.com/flutter/flutter/blob/712860d33b00bf3acf02118512901a6261ad5219/dev/tools/gen_defaults/data/time_picker.json#L58

It is not clear to me looking at the token file what the background color for the dial is meant to be. As Taha pointed out the only dial color in the file is marked with `.ignore` and is `onSurfaceVariant`

Is the 'time-selector' meant to represent the dial? If so, what are the dial properties for?

Again, perhaps we should wait until we have a full spec for this before attempting to decipher this.

**Comment by TahaTesser** [comment]
https://m3.material.io/components/time-pickers/overview is available.
I will match the specs with the tokens we have for time picker today.
