### ISSUE TITLE
Image.network's loadingProgress shouldn't be null while waiting for response from a server

### ISSUE THREAD

**Issue by DmitrySikorsky** [flutter/flutter#105823]
Hi guys, thank you for your work.

I have a little suggestion related to the `Image.network's loadingBuilder`.

`loadingProgress` is null before any response is received from a server (it took some time for me to realize that). And if you have a server-side image processing (cropping for example) it can take time for the server to download an image, crop, and return it. And before `Image` widget is waiting for response `loadingProgress` is null. After that, image might be downloaded immediately and `loadingProgress` becomes null again. So it makes it useless without simple additional logic for handling such delays.

While `ImageChunkEvent.expectedTotalBytes` is already nullable it could be an indicator that widget is not aware of the image size yet.

Thank you.

**Comment by DmitrySikorsky** [comment]
For those who has the same problem. It can be solved this way so far:

```
frameBuilder: (context, child, frame, wasSynchronouslyLoaded) {
  _isLoaded = frame != null;
  return child;
},
loadingBuilder: (context, child, loadingProgress) {
  if (_isLoaded && loadingProgress == null) {
    return child;
  }

  return _createPlaceholder();
},
```

**Comment by huycozy** [comment]
Hi @DmitrySikorsky,
I don't really understand your suggestion here. The above description has been here inside API:
https://github.com/flutter/flutter/blob/712860d33b00bf3acf02118512901a6261ad5219/packages/flutter/lib/src/widgets/image.dart#L197
https://github.com/flutter/flutter/blob/712860d33b00bf3acf02118512901a6261ad5219/packages/flutter/lib/src/painting/image_stream.dart#L274

I'm assuming [this your comment](https://github.com/flutter/flutter/issues/105823#issuecomment-1152895191) helps to solve the issue you're wondering here, right?
> So it makes it useless without simple additional logic for handling such delays.

It has been handled similarly in [loadingBuilder](https://api.flutter.dev/flutter/widgets/Image/loadingBuilder.html)'s sample

I'd love to hear your feedback.

**Comment by DmitrySikorsky** [comment]
Hi @huycozy, thank you for your reply.

I mean, that the time before widget gets any response from the server (request processing time) should be considered as loading progress too. Example from real life: normally when you open your browser, enter some website's URL and press Enter, you can see progress indicator. It is not important which part is in progress now: DNS lookup, request handling by the server, or response downloading. It is loading for you.

The same in our case. When you put some image URL into the widget, you consider that loadingProgress is not null until image is ready for display. But in current implementation loadingProgress will be **also** null while server handling the request. And in many cases it can take even much more time than image downloading itself. My case: server-side cropping of large images.

My idea is that loadingProgress shouldn't be null from the beginning of the HTTP request and until the last bytes of the image are received. It **doesn't** work this way now. Checked on version 3.0.1.

**Comment by DmitrySikorsky** [comment]
> I'm assuming https://github.com/flutter/flutter/issues/105823#issuecomment-1152895191 helps to solve the issue you're wondering here, right?

Yes, but it requires to manage state for each image. And it doesn't look nice.

**Comment by huycozy** [comment]
Hi @DmitrySikorsky 
I see there's an open issue addressing the case you described #85966 (Proposal)
Closing as a duplication, so please follow up on it for further updates. If you disagree, please write in the comments and I will reopen it.
Thank you
