### ISSUE TITLE
Problem with running Flutter desktop app.

### ISSUE THREAD

**Issue by Adam-Mazur** [flutter/flutter#105832]
## Steps to Reproduce

1. I downloaded Visual Studio with desktop development in C++ enabled
2. I created a new project with flutter create running it without any issues on android VM or web.
3. I tried to run it on windows and i got those errors:

## Logs

<details>
<summary>Logs</summary>

Launching lib\main.dart on Windows in debug mode...
lib\main.dart:1
CMake Error at CMakeLists.txt:3 (project):
  No CMAKE_CXX_COMPILER could be found.

Exception: Unable to generate build files
Exited (sigterm)

[flutter] flutter doctor -v
[√] Flutter (Channel stable, 3.0.1, on Microsoft Windows [Version 10.0.22000.675], locale pl-PL)
    • Flutter version 3.0.1 at C:\Users\adamm\OneDrive\Dokumenty\Flutter\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (3 weeks ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at C:\Users\adamm\AppData\Local\Android\sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.2.3)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.2.32526.322
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22000.675]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 102.0.5005.63
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 102.0.1245.39

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
exit code 0

</details>

**Comment by Abdelmenam-Tarek-Abdelmenam** [comment]
i have the same problem did you find a solution

**Comment by maheshmnj** [comment]
Hi @Adam-Mazur, Thanks for filing the issue. There's already a open issue https://github.com/flutter/flutter/issues/105844 please follow up there for further updates. Closing this issue as a duplicate.
