### ISSUE TITLE
in app purchase current plan status

### ISSUE THREAD

**Issue by ahmedfayed29** [flutter/flutter#105893]
hello devs.
i used in app purchase and want to know if user canceled subscription or ended.
i can't find any way to know the status of current subscription .
or any way to get grand transaction id or way to connect my server to google to know the updates 

any one can help me please .

**Comment by huycozy** [comment]
Hi @ahmedfayed29, thanks for filing the issue. 
I see there's an open issue addressing the case you described #52522.
Also, you can find there a referenced issue #49110 that its OP provided implementation for Android: https://github.com/flutter/flutter/issues/49110#issue-551774799 

Closing as a duplication, so please follow up on it for further updates.
