### ISSUE TITLE
Linux with WSL, with embedded jvm loaded isn't rendering text with standard java.awt ui/ux on the Desktop

### ISSUE THREAD

**Issue by phr34k** [flutter/flutter#105824]
I have a java library that I'm trying to interface with from flutter on a Linux desktop. I using a native plugin to host the jvm. When doing some test cases with user-interfaces using the java.awt libraries I noticed the java based ui/ux aren't rendering any text (everything else seemingly works though).

## Steps to Reproduce

This problem is reproducible.  I can reproduce this problem consistently. Here's minimum example: https://github.com/phr34k/flutter_jvm_interop - This is just a very basic quick example, it has a couple of (hard coded-) paths in `linux/CMakeLists.txt` and `windows/CMakeLists.txt` to resolve and link against the openjdk.

```
# The following line is optional due personal development environment - (redirect the display to xserver on windows)
export DISPLAY=$(grep nameserver /etc/resolv.conf | awk '{print $2}'):0.0
sudo apt install openjdk-16-jdk
git clone https://github.com/phr34k/flutter_jvm_interop
cd flutter_jvm_interop/example
export LD_LIBRARY_PATH=/usr/lib/jvm/java-1.16.0-openjdk-amd64/lib/server:/usr/lib/jvm/java-1.16.0-openjdk-amd64/lib
/:$LD_LIBRARY_PATH
flutter -v run -d linux
```

I'm running this under wsl/2 with ubuntu. On Windows I setup an xserver on windows using vcxsrv, hence the display environment variable. This behavior is also there when I activate software rendering e.g. `LIBGL_ALWAYS_SOFTWARE=1 flutter -v run -d linux`

**Expected results:**

![afbeelding](https://user-images.githubusercontent.com/1190003/173227058-93b8d78a-4734-4a2b-a3b4-5a2759f073f5.png)

Screenshot from Linux - using the java code directly

**Actual results:** 

To clarify the flutter side draws correctly, as expected. It's the java.awt test widgets aren't displaying/rendering fonts, like in the image below, the buttons and text-edit box aren't displaying their respective labels/placeholders.

![afbeelding](https://user-images.githubusercontent.com/1190003/173282935-2e796966-6e58-4d62-9b61-3340b7056a05.png)

Screenshot from Linux - using the java code indirectly from flutter

**Environment:**

```
$ flutter --version
Flutter 3.0.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision fb57da5f94 (3 weeks ago) • 2022-05-19 15:50:29 -0700
Engine • revision caaafc5604
Tools • Dart 2.17.1 • DevTools 2.12.2

$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.1, on Ubuntu 20.04.3 LTS 5.10.102.1-microsoft-standard-WSL2, locale C.UTF-8)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Linux toolchain - develop for Linux desktop
[!] Android Studio (not installed)
[✓] Connected device (1 available)
[✓] HTTP Host Availability

! Doctor found issues in 3 categories.
```

**Personal attempts:** 

- Verified that the user-interface in renders as expected outside of a flutter application host e.g. when the java code is run directly outside of flutter everything works as intended
- Verified that system font's are available from the java side when embedded in flutter
- Verified that manually loading font also doesn't render/display
- Verified that other aspects of the user-interface are working as intended e.g. event handlers, button presses, typing (just the text isn't displayed/measured).
- Attached loggers to that are outlined in this document https://docs.oracle.com/javase/8/docs/technotes/guides/troubleshoot/awt001.html but I didn't see anything of warning/error.

**Additional:** 

To me it looks like it's some kind of presentation issue. It looks like java's font/text -rendering somehow is (silently) being affected by flutter. To my understanding the desktop version of flutter are using glfw for window handling and opengl context initialization. I have a hunch it could be related to this. As flutter initializes before java side.

I'm familiar with opengl but not experienced enough with java (awt) or the internals of flutter to fully comprehend what is causing this issue. I could understand that maybe there's some kind internal device/context conflict e.g. different versions or even abi changes- but I would have expected this to trigger errors/warnings/exceptions.

I'd love to get some pointers in general.  I have been stuck on this a couple of weeks without progress and haven't been able to find a solution in the respective dedicated communities. Is there somebody of the flutter team who could give me some additional insights in this problem?

**Comment by maheshmnj** [comment]
Hi @phr34k, thanks for filing the issue. I tried to run the example and it seems to fail with below error. Let me know if I am missing anything. I am using flutter `stable 3.0.2`

```
mahesh@mahesh:~/Desktop/flutter_jvm_interop/example$ flutter run -d linux
Running "flutter pub get" in example...                             6.3s
Launching lib/main.dart on Linux in debug mode...
JVM_LIB-NOTFOUND
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
/home/mahesh/Desktop/flutter_jvm_interop/example/linux/flutter/ephemeral/.plugin_symlinks/native_jvm/linux/JNI_INCLUDE_PATH
   used as include directory in directory /home/mahesh/Desktop/flutter_jvm_interop/example/linux/flutter/ephemeral/.plugin_symlinks/native_jvm/linux

Building Linux application...                                           
Exception: Unable to generate build files
```

**Comment by phr34k** [comment]
@maheshmnj judging by your console output it has some trouble finding your java installation https://github.com/phr34k/flutter_jvm_interop/blob/master/linux/CMakeLists.txt - like your paths are different from mine, easiest way would be changes the paths there.

**Comment by maheshmnj** [comment]
Thanks for the info @phr34k, I am having trouble understanding where exactly `JNI_INCLUDE_PATH ` is pointing, I guessed it $JAVA_HOME does have lib/server, I tried  replacing 

```
JNI_INCLUDE_PATH}/../lib/server
``` 

with 

```
JAVA_HOME/lib/server
```

But looks like I am wrong considering `JNI_INCLUDE_PATH` is also being used further  here

https://github.com/phr34k/flutter_jvm_interop/blob/8c45b0d2633152f9e6edd348c15a3c4047675e8a/linux/CMakeLists.txt#L47

**Comment by phr34k** [comment]
@maheshmnj so `JNI_INCLUDE_PATH` is pointing to the include directory in your java system where it can find `jni.h`, and `JVM_LIB` is pointing to directory where it can resolve the `libjvm.so` files. See below for shell output.

The folder that contains `jni.h` should have a platform specific folder called `linux` that's why both the include and linux folders are included.

```
# This is the root installation of java for me
$ ls /usr/lib/jvm/java-1.16.0-openjdk-amd64/
bin  conf  docs  include  jmods  legal  lib  man  release

# this is what JNI_INCLUDE_PATH  should resolve to (the folder with jni.h)
$ ls /usr/lib/jvm/java-1.16.0-openjdk-amd64/include/
classfile_constants.h  jawt.h  jdwpTransport.h  jni.h  jvmti.h  jvmticmlr.h  linux

# this is what JVM_LIB should resolve to (the folder with libjvm.so)
$ ls /usr/lib/jvm/java-1.16.0-openjdk-amd64/lib/server
classes.jsa  classes_nocoops.jsa  libjsig.so  libjvm.so


# this is the secondary path derived from JNI_INCLUDE_PATH  
$ ls /usr/lib/jvm/java-1.16.0-openjdk-amd64/include/linux/
jawt_md.h  jni_md.h

# this is the secondary path derived from JVM_LIB 
$ ls /usr/lib/jvm/java-1.16.0-openjdk-amd64/lib/
classlist   jfr           jvm.cfg-default    libawt_headless.so  libfontmanager.so  libj2pkcs11.so  libjawt.so    libjsig.so        libmanagement_agent.so  libnio.so     libsctp.so          modules               server
ct.sym      jrt-fs.jar    libatk-wrapper.so  libawt_xawt.so      libinstrument.so   libjaas.so      libjdwp.so    libjsound.so      libmanagement_ext.so    libprefs.so   libsplashscreen.so  psfont.properties.ja  src.zip
jar.binfmt  jspawnhelper  libattach.so       libdt_socket.so     libj2gss.so        libjava.so      libjimage.so  liblcms.so        libmlib_image.so        librmi.so     libverify.so        psfontj2d.properties  tzdb.dat
jexec       jvm.cfg       libawt.so          libextnet.so        libj2pcsc.so       libjavajpeg.so  libjli.so     libmanagement.so  libnet.so               libsaproc.so  libzip.so           security
```

Taking my local paths as a reference what you want cmake to do, is basically this: 

```
target_include_directories(${PLUGIN_NAME} PRIVATE "/usr/lib/jvm/java-1.16.0-openjdk-amd64/include/;/usr/lib/jvm/java-1.16.0-openjdk-amd64/include/linux")
target_link_directories(${PLUGIN_NAME} PRIVATE "/usr/lib/jvm/java-1.16.0-openjdk-amd64/lib/server;/usr/lib/jvm/java-1.16.0-openjdk-amd64/lib")
```

**Comment by maheshmnj** [comment]
Thanks for the info @phr34k,I finally managed to run the app, the include folder was missing, reinstalling the jdk fixed it.
Coming back to the original issue, I ran the app and I see the interop fetched the device info, Was this supposed to launch a native linux window?

![image](https://user-images.githubusercontent.com/31410839/173794997-30081392-9149-4409-b62a-d5531712d6ca.png)


I see some failure logs in the cosole.

```
mahesh@mahesh:~/Desktop/flutter_jvm_interop/example$ flutter run -d linux
Launching lib/main.dart on Linux in debug mode...
/usr/lib/jvm/java-1.11.0-openjdk-amd64/lib/server
Building Linux application...                                           
started
Syncing files to device Linux...                                   113ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

Running with unsound null safety
For more information see https://dart.dev/null-safety/unsound-null-safety

An Observatory debugger and profiler on Linux is available at: http://127.0.0.1:41987/PlQhTeikfcU=/
start
The Flutter DevTools debugger and profiler on Linux is available at: http://127.0.0.1:9100?uri=http://127.0.0.1:41987/PlQhTeikfcU=/
loading -Djava.class.path=/home/mahesh/Desktop/flutter_jvm_interop/example/../java
Failed to find class
getPlatformVersion

```
<details>
<summary>flutter doctor -v (Linux)</summary>

```
[✓] Flutter (Channel stable, 3.0.1, on Ubuntu 20.04.4 LTS 5.13.0-30-generic, locale en_GB.UTF-8)
    • Flutter version 3.0.1 at /home/mahesh/Development/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (5 days ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /home/mahesh/Android/Sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /home/mahesh/Downloads/android-studio-2020.3.1.25-linux/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 2020.3)
    • Android Studio at /home/mahesh/Downloads/android-studio-2020.3.1.25-linux/android-studio
    • Flutter plugin version 67.1.2
    • Dart plugin version 212.5744
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.66.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.40.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 20.04.4 LTS 5.13.0-30-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 100.0.4896.75

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by maheshmnj** [comment]
Thanks for the info @phr34k, Upon running the app I received the same error, so I compiled and ran the native app using `javac` and I could see the native window running. 

![image](https://user-images.githubusercontent.com/31410839/174098038-e31f415b-a798-45a8-967b-13f32c132f4d.png)


Then I rebuilt the flutter app using `flutter run -d linux` and I see the text getting rendered

![image](https://user-images.githubusercontent.com/31410839/174098230-23fa1dda-9038-4b0b-8690-53b635151f43.png)



<details>
<summary>flutter doctor -v (Linux)</summary>

```
[✓] Flutter (Channel stable, 3.0.1, on Ubuntu 20.04.4 LTS 5.13.0-30-generic, locale en_GB.UTF-8)
    • Flutter version 3.0.1 at /home/mahesh/Development/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (5 days ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /home/mahesh/Android/Sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /home/mahesh/Downloads/android-studio-2020.3.1.25-linux/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 2020.3)
    • Android Studio at /home/mahesh/Downloads/android-studio-2020.3.1.25-linux/android-studio
    • Flutter plugin version 67.1.2
    • Dart plugin version 212.5744
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.66.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.40.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 20.04.4 LTS 5.13.0-30-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 100.0.4896.75

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by phr34k** [comment]
@maheshmnj I think the only significant difference between our environments is that you run this on Ubuntu directly. I'm running `flutter run -d linux` on a wsl installation (ubuntu 20.04) and use x11 forwarding to display the ui on windows as I don't have a dedicated linux system.

![afbeelding](https://user-images.githubusercontent.com/1190003/174122132-3f452c45-35d1-4023-993c-e178a7dd79f4.png)
Here's it side by side: left is `java` invoked directly and on the right with `flutter run -d linux`.

Both instances are using x11 forwarding. I repeated my tests against openjdk-11 (same version as you) to rule out it's due to different versions, and I used both VcXserv and xming to rule out an individual bad implementation of an x11-server. I'd try to see if you can recreate the issue in a similar setup, maybe try using an x11 forward to another machine. 

What really stood out to me is that running under flutter somehow causes stringWidth to compute as 0. The focus rectangle (see highlights) is made me realize it can't measure the text for a reason. I don't really understand what measurement code does to get affected, most of the time they measure a string based on glyph/character information i.e. glyph advance, kerning.

What I could trace in java source code is that first time a user interface is initialized is that it tries to synchronize to some current state, and derive certain factors including scaling factors, and an affine transform. Some of the state looked to be local to java, but the some of the factors looked derived from the x11 context.

```
      JLabel j = new JLabel();
      java.awt.Font f = j.getFont();
      java.awt.FontMetrics m = j.getFontMetrics(f);
      System.out.println("font is " + f.toString());
      System.out.println("stringWidth of \"hello world\" " + String.valueOf(m.stringWidth("hello world")));
```

This is the code I used to measure the string with, but also individual character advances are all computed as zero.

**Comment by maheshmnj** [comment]
Thanks for the info @phr34k, Unfortunately, I do not have another machine with wsl setup to investigate further. I am going to label this issue for further insights from the team.

**Comment by phr34k** [comment]
@maheshmnj  Sure, thanks for all the help so far!  

Just a thought. Trying out x11 forwarding though docker container might be worth a shot i.e. spin up a Ubuntu docker container to compile and run the code example and use x11 forwarding (e.g. `export DISPLAY`) to forward the ui over one of the internal eth interfaces to your desktop.

It's the closest analogy I can think of my wsl setup e.g. both are headless, both use x11 forwarding.  With some luck it might be similar enough to repro it that way.

**Comment by gspencergoog** [comment]
@phr34k Thanks for letting us know that this might be an issue. Unfortunately, unless it's clear that Flutter is the cause, we really can't do much to fix this issue without a lot more information. (Desktop Triage)

**Comment by phr34k** [comment]
@gspencergoog what type of additional information do you need/want for a triage? With the example I've provided I can reproduce this error on multiple machines e.g. both my desktop machine and laptop. I think there's enough context to establish flutter is the directly (or indirectly) the cause of the behavior. 

Before I decided to report this, I've eliminated pretty much everything except for flutter. The clearest example is that `m.stringWidth("hello world")` from flutter or from java directly yield different results.  The java code embedded in flutter reports this always as 0, and doesn't actually give the correct results (pixels).

Were you able to establish a reproduction case using wsl or docker as an alternative? If not can you let me know if you need me to provide you more information?
