### ISSUE TITLE
Support opening drawers with a drag on the desktop

### ISSUE THREAD

**Issue by au-top** [flutter/flutter#105835]
Start the drag and drop drawer on the desktop

I understand the changes made to adapt to the platform, but we have changed the available `true`/`false` control to completely disable it, which is a step backwards!

https://github.com/flutter/flutter/issues/100321

**Comment by maheshmnj** [comment]
Hi @au-top, Thanks for filing the issue. I am labeling this issue as a new feature request for further consideration from the team.

**Comment by maheshmnj** [comment]
cc: @justinmc

**Comment by HansMuller** [comment]
CC @guidezpl - is a drag gesture the right way to open a drawer on desktop?

**Comment by guidezpl** [comment]
No, this isn't supported and not really something we want to allow.

**Comment by au-top** [comment]
How can I use the mouse to control the drawer on win?
