### ISSUE TITLE
Engine Android Emulator Tests Failing

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#105937]
After fixing the emulator flakines we have identified a single test is failing consistently on the android emulator tests.

https://ci.chromium.org/p/flutter/builders/staging/Linux%20Android%20Emulator%20Tests

**Comment by godofredoc** [comment]
@GaryQian @blasten is this something you can help us fix?

**Comment by godofredoc** [comment]
\cc @ricardoamador

**Comment by blasten** [comment]
yes, this test should be disabled.  I did this in https://github.com/flutter/engine/pull/33574/files#diff-7948658b934f17fd28e6542e3c34afa2789e8b8d1c6455703aa3ba90d68de3ceR168, but the PR got reverted

**Comment by godofredoc** [comment]
@ricardoamador is this fixed? can we close this issue?

**Comment by ricardoamador** [comment]
No I don't believe so. I have not been able to look at this yet. The test was last run on July 12. I think it needs to be disabled again.

**Comment by ricardoamador** [comment]
Yeah looks like the test still runs. I can revert the revert and can open a tracking issue for the flutter android team.

**Comment by ricardoamador** [comment]
This is not an emulator issue. It is a unit test issue and the test has been disabled.
https://github.com/flutter/engine/blob/main/shell/platform/android/android_context_gl_unittests.cc#L167
Closing this issue.
