### ISSUE TITLE
Hide `debug` banner from Dartpad examples 

### ISSUE THREAD

**Issue by TahaTesser** [flutter/flutter#105959]
When running examples in [AppBar](https://api.flutter.dev/flutter/material/AppBar-class.html) docs in the Dartpad window, the ` AppBar` action is covered by debug banner making the examples less clear.

### Before
![Screenshot 2022-06-14 at 17 09 42](https://user-images.githubusercontent.com/48603081/173598865-c67eb69c-3871-4ba6-a31c-dc75a38ef767.png)

### After
![Screenshot 2022-06-14 at 17 09 57](https://user-images.githubusercontent.com/48603081/173598941-734abc6c-39d4-4639-99a8-f4baf22c9eca.png)

Similarly 

![Screenshot 2022-06-14 at 17 11 44](https://user-images.githubusercontent.com/48603081/173599114-d06f0f55-1a01-46d5-a6de-ddcf44cd9205.png)

and maybe more examples have this problem when `AppBar`  has action buttons.

**Comment by TahaTesser** [comment]
cc: @guidezpl @gspencergoog 

Is there any reason to keep debug banners in the example at all? If not, could we hide it in all the examples?

**Comment by gspencergoog** [comment]
Hmm. No, no reason. That's a good idea, I'm just not sure I want to add it to all of the examples, since typically we don't want users to turn that off (it's a good indicator for them, especially when starting out learning).

Maybe there's a flag we can give Dartpad or something...

**Comment by TahaTesser** [comment]
> Hmm. No, no reason. That's a good idea, I'm just not sure I want to add it to all of the examples, since typically we don't want users to turn that off (it's a good indicator for them, especially when starting out learning).
> 
> Maybe there's a flag we can give Dartpad or something...

That makes sense, I propose a button in the Dartpad that disables the banner by default. When checking this menu option, the banner will be visible.


Something like this

![Screenshot 2022-06-22 at 13 14 04](https://user-images.githubusercontent.com/48603081/175005805-cb3f750b-674f-43bd-8c5e-69a29eb2c882.png)

**Comment by gspencergoog** [comment]
Sure.  @RedBrogdon is that a possibility?  Or maybe there's already a flag for that?

**Comment by gspencergoog** [comment]
Yeah, good point.  I don't see any need for the banner at all in Dartpad.

**Comment by RedBrogdon** [comment]
I always thought the banner was there to make sure people knew what kind of performance characteristics to expect when using the running application. DartPad has to use dartdevc in order to make the download size of the compiled code manageable (the Dart and Flutter SDKs can be precached that way), which means it's only capable of produced non-optimized, "debug" code.

**Comment by TahaTesser** [comment]
Closing this for https://github.com/dart-lang/dart-pad/issues/1391
