### ISSUE TITLE
[flutter_webview] SystemChannels.textInput.invokeMethod('TextInput.hide') is not working in flutter_webview for ios

### ISSUE THREAD

**Issue by ichengao** [flutter/flutter#105951]
in my case, i want to hide keyboard and stay focus，on android is ok, but on ios is not working

**Comment by huycozy** [comment]
Hi @ichengao, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this. Please provide the output of `flutter doctor -v` as well.
Thank you!
