### ISSUE TITLE
Firestore Performance Android only, when deployed to Google Playstore

### ISSUE THREAD

**Issue by zthrive** [flutter/flutter#105990]
My app is fully operational on Android, iOS and Web.
It is using Firestore to access its data (transaction, batch, 'plain')

When used on the Web (deployed or local browser) everything works great
When used on the iOS device (downloaded from the App Store or installed directly) it works great
When used on Android emulator, it works great
When signed release_app.apk is downloaded to the physical Android device it works great.
If I share the signed release_app.apk file over email, installed app works great

When uploaded to the Android device (connected over USB), running 'flutter run --release' - dramatic performance issues  (access to firestore is timed out)
When appbundle is uploaded to Google Playstore and the app downloaded to the device - same issues as above.
When release_apk.app is uploaded to Google Playstore and then app downloaded to the device - same issues as above

The timeout error is attached.

If you need any other information from me please let me know.

<img src="https://user-images.githubusercontent.com/13058185/173731581-4e597c35-6e89-4ae8-92b8-1dd42be72600.jpg" width ="300"> 

**Target Platform:**
**Target OS version/browser:**
**Devices:**

## Logs

<details>
<summary>Logs</summary>

```
```

```
```

</details>

**Comment by maheshmnj** [comment]
Hi @zthrive, Thanks for filing the issue.  Looks like this issue is occurring in release mode on Android, Are you making lot of read/writes in a short amount of time which is why you are running out of limits on firebase?

Since this error is coming from firestore I would suggest filing this issue in the dedicated [flutterfire repository ](https://github.com/firebase/flutterfire/issues) and I would love to take a look.

Closing as this is not related to flutter.

**Comment by zthrive** [comment]
Hi  @maheshmnj, 
Let me respectfully disagree with the rationale provided to close this issue. Since the app operates without problems in all but one specific circumstance, I don't think that this is a firestore issue. If it was, the app would fail everywhere, which is not the case at all. Please re-read my description of the issue. 
(Perhaps the screenshot I provided was misleading and I should not  have included it  when filling the issue)

I believe that the issue has to do with compression and packaging, since the problem appears only when the app is packaged for deployment  and downloaded from the Google Playstore.

**Comment by maheshmnj** [comment]
Thanks for the update @zthrive, reopening based on the above comment.

**Comment by maheshmnj** [comment]
@zthrive  Can you share a minimal and complete sample project for us to investigate the issue? Also, Please share the output of `flutter doctor -v`?

**Comment by maheshmnj** [comment]
> The output of 'flutter doctor -v' is included, However, providing a minimal and complete example is not that trivial since it involves a complete project setup.

@zthrive Without any sample code, this will be pretty difficult to investigate, I would suggest making a copy of your sample project and try removing the code sample which doesn't help in reproducing the issue, Doing so will leave you with a minimal and complete sample project which you can share with us to investigate.

Thanks

**Comment by iapicca** [comment]
>  Since the app operates without problems in all but one specific circumstance, I don't think that this is a firestore issue.

assuming, but not given, that the issue is not caused by the implementation
I'd argue that it most likely depend from [firestore package](https://pub.dev/packages/cloud_firestore) and should be addressed [here](https://github.com/firebase/flutterfire/issues)

**Comment by zthrive** [comment]
I'll do my best to provide a code sample but disagree with the argument that this is a firestore related issue. 

Once again, I used the same Android device to test the app with a direct installation of the apk file and the same apk file uploaded to the Google Playstore and then download to the device. There are performance issues only in the latter case.
(Also, the app works well in all iOS cases as well as the web app - if there was a firestore issue, it would show here too.)

Additionally, none of  the 'number of factors' stated above is applicable.  

I will be happy to provide more information.

**Comment by zthrive** [comment]
Please find the code bellow.

To reproduce the problem please do the following:

1. Create a firebase project to run the code provided
2. Run the code from the android emulator (press Run button) - confirm no latency ('Waiting ..' text shows only briefly)
3.  install the code to an Android device - 'flutter run --release' - there are latency issues present ('Waiting ...' text duration is several seconds)
4.  Generate signed apk, install it on the Android device - there are no latency issues (the very first run only will be slower)

If you need any other information from me, please let me know.

========================================================

import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';

FirebaseFirestore gFirestoreDb = FirebaseFirestore.instance;

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: const Home(),
    );
  }
}

class Home extends StatefulWidget {
  const Home({Key? key}) : super(key: key);

  @override
  State<Home> createState() => _HomeState();
}

class _HomeState extends State<Home> {
  bool _busy = false;

  Future<String?> _runTransaction() async {
    print('about to add booking to the calendar');

    final Map<String, dynamic> newBooking = {
      'fbDocId': 'abc',
      'appEnv': 'test',
      'city': 'Berlin',
      'owner': "booking.owner",
      'timestamp': Timestamp.fromDate(DateTime.now()).millisecondsSinceEpoch,
    };
    try {
      print('About to start transaction to store booking');
      await gFirestoreDb.runTransaction((transaction) async {
        // your transaction

        final String queryString = 'cities';

        transaction.set(gFirestoreDb.collection(queryString).doc(), newBooking);
        // add booking for efective search purposes, each user will have separate collection
        final String queryString2 = queryString + '/other/' + 'all-bookings';
        DocumentReference dr = gFirestoreDb
            .collection(queryString2)
            .doc("booking.owner")
            .collection('bookings')
            .doc();
        transaction.set(dr, newBooking);

        dr = gFirestoreDb
            .collection(queryString2)
            .doc('manage-bookings')
            .collection('bookings')
            .doc();
        transaction.set(dr, newBooking);

        return {
          // any data related to transaction success
        };
      }, timeout: Duration(seconds: 5));

      print(
          'Bookig was successful for  booking.owner'); // handle your app state here,outside the transaction handler

    } catch (e) {
      print('There was a problem ${e.toString()}');
      return e.toString();
    }

    return null;
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: Column(
      mainAxisAlignment: MainAxisAlignment.center,
      children: [
        Row(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Visibility(visible: _busy, child: Text('Waiting ....')),
          ],
        ),
        Row(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            TextButton(
              child: Text('Run'),
              onPressed: () async {
                setState(() {
                  _busy = true;
                });
                await _runTransaction();
                setState(() {
                  _busy = false;
                });
              },
            ),
          ],
        ),
      ],
    ));
  }
}
========================================================

**Comment by zthrive** [comment]
Just following up on my previous post. 

Could you please confirm that you have enough information to start with investigating the issue. If this is not the case, please let me know what else you require.

Regards

**Comment by maheshmnj** [comment]
Thanks for the info @zthrive.  I tried your reproducible steps and I see  a slight delay in release mode as compared to debug mode, Is this the issue you are referring to? If so I believe this is an issue in the plugin which must be filed in the flutterfire repo  as mentioned above.



*Physical device: Xiaomi k20 Pro (Android 11)*

Physical device (Release) | Physical device (Debug)  | Emulator (Debug)
:-: | :-: | :-:
<video src='https://user-images.githubusercontent.com/31410839/175873903-fcf6f09c-0c45-4d38-a6a5-cf77cd88652f.mov' width=180/> | <video src='https://user-images.githubusercontent.com/31410839/175873955-3f77e0a1-52e5-4d15-aa27-979e94a0b1d5.mov' width=180/> | <video src='https://user-images.githubusercontent.com/31410839/175873920-ab675a64-966b-46ac-a44c-78a255f04d8e.mov' width=180/>



<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel stable, 3.0.2, on macOS 12.4 21F79 darwin-arm, locale en-IN)
    • Flutter version 3.0.2 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cd41fdd495 (5 days ago), 2022-06-08 09:52:13 -0700
    • Engine revision f15f824b57
    • Dart version 2.17.3
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-32, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.67.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.42.0

[✓] Connected device (3 available)
    • sdk gphone arm64 (mobile) • emulator-5554 • android-arm64  • Android 11 (API 30) (emulator)
    • macOS (desktop)           • macos         • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)              • chrome        • web-javascript • Google Chrome 102.0.5005.61

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

```
[✓] Flutter (Channel master, 3.1.0-0.0.pre.1237, on macOS 12.4 21F79 darwin-arm, locale en-IN)
    • Flutter version 3.1.0-0.0.pre.1237 at /Users/mahesh/Documents/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6062e40510 (64 minutes ago), 2022-06-12 23:53:08 -0400
    • Engine revision f80294b57e
    • Dart version 2.18.0 (build 2.18.0-180.0.dev)
    • DevTools version 2.14.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-32, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.67.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.42.0

[✓] Connected device (3 available)
    • sdk gphone arm64 (mobile) • emulator-5554 • android-arm64  • Android 11 (API 30) (emulator)
    • macOS (desktop)           • macos         • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)              • chrome        • web-javascript • Google Chrome 102.0.5005.61

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by maheshmnj** [comment]
Update: I just saw [your comment ](https://github.com/firebase/flutterfire/issues/8623#issuecomment-1147362397)in flutterfire repo, And based on your research this could potentially be an issue in the flutter tool. I am leaving this issue open for further investigation from the team.

flutterfire issue being tracked here: https://github.com/firebase/flutterfire/issues/8623

**Comment by zthrive** [comment]
Thank you @maheshmnj , I appreciate your assistance.  
I would be happy to provide further information to the team if/when necessary

Just to summarise:
- an app using firestore  - iOS  => no issues
- an app using firestore - webApp => no issues
- an app using firestore  in debug  whether on physical Android device or emulator  => no issues
- an app using firestore (signed app-release.apk)  deployed on the Android physical device (cable/WIFI)  => no issues
- 
- an app  using firestore  deployed in the Goolge Play and then downloaded to Android device => performance issues
-  an app  using firestore  deployed to the physical Android device (cable/WiFi) using command 'flutter run --release' => performance issues

**Comment by stuartmorgan** [comment]
> (Also, the app works well in all iOS cases as well as the web app - if there was a firestore issue, it would show here too.)

There's no reason this should necessarily be true; the plugin implementation is completely different on each platform. Given that this seems to be specific to Firestore internals, and there's no clear avenue to investigate this as a Flutter issue, I think the next step would be to file this as a Firestore issue. If they find that it's Flutter-specific, they can provide more details about what is different about the Flutter-built app vs a non-Flutter app. (It's not clear to me how Flutter would be causing an issue that is specific to how you *deployed*, not built, the app.)

**Comment by zthrive** [comment]
@stuartmorgan  I respectfully disagree with your assertion, and request this issue reopened. Please read carefully all bullet points above I stated.  
The issue has to do with packaging for deployment to Google Playstore and nothing else. 

Once again, please read all bullet points but in particular bullet point 4.

Please respond.

**Comment by stuartmorgan** [comment]
I have read your comments. In particular https://github.com/firebase/flutterfire/issues/8623#issuecomment-1149176723 where you say that the exact same build product

**Comment by stuartmorgan** [comment]
(Re-opening was an accidental mis-click.)

**Comment by zthrive** [comment]
@stuartmorgan  Thank you for reading my comments on the issue.  And yes, the comment you pointed at should be a bit more elaborated on.  

Google recommends uploading a bundle rather than an apk to the Playstore, but they do not stop you from uploading an apk. It is not known how they manipulate the apk during the upload but it is a fact that if I load the same apk directly to the physical device there are no performance issues. However, if I download it from the Google Playstore, performance issues are present (same as with a bundle). 
And in my mind this tells that there are  no issues with firestore but somewhere else, 'upstream'.  Firestore interface is there as a pure coincidence, but it is important piece of information that could help. Chances are that there are many other cases where this same issue would surface.

Below is my updated bullet point list. 

Also,  I would appreciate if you could reopen this issue so that someone can look at it. Please let me know

1. an app using firestore - iOS => no issues
2. an app using firestore - webApp => no issues
3. an app using firestore in debug whether on physical Android device or emulator => no issues
4. an app using firestore (signed app-release.apk) deployed on the Android physical device (cable/WIFI) => no issues
5. an app using firestore deployed in the Goolge Play and then downloaded to Android device => performance issues
6. an app using firestore deployed to the physical Android device (cable/WiFi) using command 'flutter run --release' => performance issues

**Comment by stuartmorgan** [comment]
> it is a fact that if I load the same apk directly to the physical device there are no performance issues. However, if I download it from the Google Playstore, performance issues are present (same as with a bundle).

And as I said above: Flutter is not involved in this step. It's not at all clear to me how you are concluding that this means both that it isn't a Firestore bug and that it is a Flutter bug. Flutter is no more or less involved in that deployment step than Firestore.

> Also, I would appreciate if you could reopen this issue so that someone can look at it.

Please see my comment above for what we would need in order to re-open this. If you have determined that the issue is specific to something the Play Store is doing, you should file a bug against the Play Store.

**Comment by zthrive** [comment]
It might well be that it is a Play Store issue and I would be prepared to raise it with them.  

However,  before proceeding to raise the issue with Play Store, there is another thing, listed in my bullet points that needs to be looked at  - item #6. In this instance, Play Store is not involved.  So, if I do item #4 no issue, if I then do item #6 there is issue. 

I still think that firestore is just an accidental 'actor' that highlights the issue on the Android side, only production code. All is good if a debug version of the code is used, check the bullet point #3. 

Once again, to the defence of firestore, the same app works just fine with iOS and Web. As such, my conclusion that firestore is working properly and should not be blamed for the performance issue still stands.    

Therefore, I still believe that this issue needs to be reopened.

**Comment by zthrive** [comment]
@stuartmorgan I haven't heard back from you. 
Could you please let me know whether you intend to reopen this issue or not. If not, I would like to know the rationale.

**Comment by stuartmorgan** [comment]
I can re-open this for the purposes of looking specifically at the case you've labelled 6. However:
- [that was not reproducible](https://github.com/flutter/flutter/issues/105990#issuecomment-1166938048) so far, which is going to be very problematic for investigating, and
- the fact that you can get *exactly the same issue* two different ways, and one of those ways doesn't involve Flutter at all, still strongly suggest that this isn't a Flutter issue.

**Comment by zthrive** [comment]
@stuartmorgan  Thank you for reopening the issue.

I shared the code earlier that can be used to reproduce the issue.  (I responded to @maheshmnj message, please read my response.)

What is important here is that Firestore should not be engaged in the wasteful investigation of the non-existing problem. That would unnecessarily further delay the resolution of the real issue.

Having said above, I acknowledge that it is not 100% conclusive where the issue lies - could be more than one place, Play Store inclusive, I don't know that. However, there is enough information for Flutter people to have a look at this and make their own decision about how to proceed. I would be happy to help further if this is required.

Additionally, as per your comment above, I know that there is some kind of 'code shrinking' done during the 'packaging for deployment' step and I suspect that this is where the issue could be investigated by Flutter. But I do not want to speculate further on that, it is not my call.

If you need anything else from me at this stage, please let me know.

**Comment by zthrive** [comment]
@stuartmorgan I deployed the app (apk) to the Galaxy Store and then downloaded it to the physical device - there are no performance issues. As a result of this, I raised a bug report with Google Play. I'll see how they respond.

However, the performance issue still remains very much valid with app bundle, and flutter team will need to investigate this issue further.

**Comment by zthrive** [comment]
@stuartmorgan - there is some major development that I would like to advise about. 
After upgrading to the latest Android Studio, and associated development environment I was able to deploy the app to the Google Play Store and performance issues have disappeared. Therefore, I think that this issue can be closed now.
