### ISSUE TITLE
我的项目从1.22.3升到2.8.1时，编译出现以下错误，请问怎么修改呢？

### ISSUE THREAD

**Issue by 132056135** [flutter/flutter#105999]
/D:/devflutter/flutter/.pub-cache/hosted/pub.flutter-io.cn/video_player_platform_interface-2.2.0/lib/messages.dart:432:15: Error: The method 'setMockMessageHandler' isn't defined for the class 'BasicMessageChannel<dynamic>'.
 - 'BasicMessageChannel' is from 'package:flutter/src/services/platform_channel.dart' ('/D:/devflutter/flutter/packages/flutter/lib/src/services/platform_channel.dart').
Try correcting the name to the name of an existing method, or defining a method named 'setMockMessageHandler'.
      channel.setMockMessageHandler((dynamic message) async {
              ^^^^^^^^^^^^^^^^^^^^^
/D:/devflutter/flutter/.pub-cache/hosted/pub.flutter-io.cn/video_player_platform_interface-2.2.0/lib/messages.dart:440:15: Error: The method 'setMockMessageHandler' isn't defined for the class 'BasicMessageChannel<dynamic>'.
 - 'BasicMessageChannel' is from 'package:flutter/src/services/platform_channel.dart' ('/D:/devflutter/flutter/packages/flutter/lib/src/services/platform_channel.dart').
Try correcting the name to the name of an existing method, or defining a method named 'setMockMessageHandler'.
      channel.setMockMessageHandler((dynamic message) async {
              ^^^^^^^^^^^^^^^^^^^^^
/D:/devflutter/flutter/.pub-cache/hosted/pub.flutter-io.cn/video_player_platform_interface-2.2.0/lib/messages.dart:451:15: Error: The method 'setMockMessageHandler' isn't defined for the class 'BasicMessageChannel<dynamic>'.
 - 'BasicMessageChannel' is from 'package:flutter/src/services/platform_channel.dart' ('/D:/devflutter/flutter/packages/flutter/lib/src/services/platform_channel.dart').
Try correcting the name to the name of an existing method, or defining a method named 'setMockMessageHandler'.
      channel.setMockMessageHandler((dynamic message) async {
              ^^^^^^^^^^^^^^^^^^^^^
/D:/devflutter/flutter/.pub-cache/hosted/pub.flutter-io.cn/video_player_platform_interface-2.2.0/lib/messages.dart:463:15: Error: The method 'setMockMessageHandler' isn't defined for the class 'BasicMessageChannel<dynamic>'.
 - 'BasicMessageChannel' is from 'package:flutter/src/services/platform_channel.dart' ('/D:/devflutter/flutter/packages/flutter/lib/src/services/platform_channel.dart').
Try correcting the name to the name of an existing method, or defining a method named 'setMockMessageHandler'.
      channel.setMockMessageHandler((dynamic message) async {
              ^^^^^^^^^^^^^^^^^^^^^
/D:/devflutter/flutter/.pub-cache/hosted/pub.flutter-io.cn/video_player_platform_interface-2.2.0/lib/messages.dart:475:15: Error: The method 'setMockMessageHandler' isn't defined for the class 'BasicMessageChannel<dynamic>'.
 - 'BasicMessageChannel' is from 'package:flutter/src/services/platform_channel.dart' ('/D:/devflutter/flutter/packages/flutter/lib/src/services/platform_channel.dart').
Try correcting the name to the name of an existing method, or defining a method named 'setMockMessageHandler'.
      channel.setMockMessageHandler((dynamic message) async {
              ^^^^^^^^^^^^^^^^^^^^^
/D:/devflutter/flutter/.pub-cache/hosted/pub.flutter-io.cn/video_player_platform_interface-2.2.0/lib/messages.dart:487:15: Error: The method 'setMockMessageHandler' isn't defined for the class 'BasicMessageChannel<dynamic>'.
 - 'BasicMessageChannel' is from 'package:flutter/src/services/platform_channel.dart' ('/D:/devflutter/flutter/packages/flutter/lib/src/services/platform_channel.dart').
Try correcting the name to the name of an existing method, or defining a method named 'setMockMessageHandler'.
      channel.setMockMessageHandler((dynamic message) async {
              ^^^^^^^^^^^^^^^^^^^^^
/D:/devflutter/flutter/.pub-cache/hosted/pub.flutter-io.cn/video_player_platform_interface-2.2.0/lib/messages.dart:499:15: Error: The method 'setMockMessageHandler' isn't defined for the class 'BasicMessageChannel<dynamic>'.
 - 'BasicMessageChannel' is from 'package:flutter/src/services/platform_channel.dart' ('/D:/devflutter/flutter/packages/flutter/lib/src/services/platform_channel.dart').
Try correcting the name to the name of an existing method, or defining a method named 'setMockMessageHandler'.
      channel.setMockMessageHandler((dynamic message) async {
              ^^^^^^^^^^^^^^^^^^^^^
/D:/devflutter/flutter/.pub-cache/hosted/pub.flutter-io.cn/video_player_platform_interface-2.2.0/lib/messages.dart:510:15: Error: The method 'setMockMessageHandler' isn't defined for the class 'BasicMessageChannel<dynamic>'.
 - 'BasicMessageChannel' is from 'package:flutter/src/services/platform_channel.dart' ('/D:/devflutter/flutter/packages/flutter/lib/src/services/platform_channel.dart').
Try correcting the name to the name of an existing method, or defining a method named 'setMockMessageHandler'.
      channel.setMockMessageHandler((dynamic message) async {
              ^^^^^^^^^^^^^^^^^^^^^
/D:/devflutter/flutter/.pub-cache/hosted/pub.flutter-io.cn/video_player_platform_interface-2.2.0/lib/messages.dart:521:15: Error: The method 'setMockMessageHandler' isn't defined for the class 'BasicMessageChannel<dynamic>'.
 - 'BasicMessageChannel' is from 'package:flutter/src/services/platform_channel.dart' ('/D:/devflutter/flutter/packages/flutter/lib/src/services/platform_channel.dart').
Try correcting the name to the name of an existing method, or defining a method named 'setMockMessageHandler'.
      channel.setMockMessageHandler((dynamic message) async {
              ^^^^^^^^^^^^^^^^^^^^^
/D:/devflutter/flutter/.pub-cache/hosted/pub.flutter-io.cn/video_player_platform_interface-2.2.0/lib/messages.dart:532:15: Error: The method 'setMockMessageHandler' isn't defined for the class 'BasicMessageChannel<dynamic>'.
 - 'BasicMessageChannel' is from 'package:flutter/src/services/platform_channel.dart' ('/D:/devflutter/flutter/packages/flutter/lib/src/services/platform_channel.dart').
Try correcting the name to the name of an existing method, or defining a method named 'setMockMessageHandler'.
      channel.setMockMessageHandler((dynamic message) async {
              ^^^^^^^^^^^^^^^^^^^^^
/D:/devflutter/flutter/.pub-cache/hosted/pub.flutter-io.cn/video_player_platform_interface-2.2.0/lib/messages.dart:544:15: Error: The method 'setMockMessageHandler' isn't defined for the class 'BasicMessageChannel<dynamic>'.
 - 'BasicMessageChannel' is from 'package:flutter/src/services/platform_channel.dart' ('/D:/devflutter/flutter/packages/flutter/lib/src/services/platform_channel.dart').
Try correcting the name to the name of an existing method, or defining a method named 'setMockMessageHandler'.
      channel.setMockMessageHandler((dynamic message) async {
              ^^^^^^^^^^^^^^^^^^^^^
/D:/devflutter/flutter/.pub-cache/hosted/pub.flutter-io.cn/wakelock_platform_interface-0.1.0+1/lib/messages.dart:96:17: Error: The method 'setMockMessageHandler' isn't defined for the class 'BasicMessageChannel<dynamic>'.
 - 'BasicMessageChannel' is from 'package:flutter/src/services/platform_channel.dart' ('/D:/devflutter/flutter/packages/flutter/lib/src/services/platform_channel.dart').
Try correcting the name to the name of an existing method, or defining a method named 'setMockMessageHandler'.
        channel.setMockMessageHandler(null);
                ^^^^^^^^^^^^^^^^^^^^^
/D:/devflutter/flutter/.pub-cache/hosted/pub.flutter-io.cn/wakelock_platform_interface-0.1.0+1/lib/messages.dart:98:17: Error: The method 'setMockMessageHandler' isn't defined for the class 'BasicMessageChannel<dynamic>'.
 - 'BasicMessageChannel' is from 'package:flutter/src/services/platform_channel.dart' ('/D:/devflutter/flutter/packages/flutter/lib/src/services/platform_channel.dart').
Try correcting the name to the name of an existing method, or defining a method named 'setMockMessageHandler'.
        channel.setMockMessageHandler((dynamic message) async {
                ^^^^^^^^^^^^^^^^^^^^^
/D:/devflutter/flutter/.pub-cache/hosted/pub.flutter-io.cn/wakelock_platform_interface-0.1.0+1/lib/messages.dart:111:17: Error: The method 'setMockMessageHandler' isn't defined for the class 'BasicMessageChannel<dynamic>'.
 - 'BasicMessageChannel' is from 'package:flutter/src/services/platform_channel.dart' ('/D:/devflutter/flutter/packages/flutter/lib/src/services/platform_channel.dart').
Try correcting the name to the name of an existing method, or defining a method named 'setMockMessageHandler'.
        channel.setMockMessageHandler(null);
                ^^^^^^^^^^^^^^^^^^^^^
/D:/devflutter/flutter/.pub-cache/hosted/pub.flutter-io.cn/wakelock_platform_interface-0.1.0+1/lib/messages.dart:113:17: Error: The method 'setMockMessageHandler' isn't defined for the class 'BasicMessageChannel<dynamic>'.
 - 'BasicMessageChannel' is from 'package:flutter/src/services/platform_channel.dart' ('/D:/devflutter/flutter/packages/flutter/lib/src/services/platform_channel.dart').
Try correcting the name to the name of an existing method, or defining a method named 'setMockMessageHandler'.
        channel.setMockMessageHandler((dynamic message) async {

**Comment by 132056135** [comment]
我的项目也没有引用video_player_platform_interface 下面是我的pub.yaml
provider: ^4.1.3
  dio: ^3.0.10
  dio_cookie_manager: ^1.0.0
  package_info: ^2.0.2
  path_provider: ^1.6.11
  connectivity: ^3.0.6
  flutter_spinkit: ^4.1.2+1
#  flutter_animation_set: ^0.0.4
  flutter_swiper_null_safety: ^1.0.2
  flutter_slidable: ^0.5.7
  photo_view: ^0.14.0
  webview_flutter: 1.0.7
  extended_text: ^8.0.2
  extended_text_field: ^9.0.3
  flutter_keyboard_visibility: ^4.0.0
  flutter_datetime_picker: 1.5.0
  fluttertoast: 6.0.1
  common_utils: ^1.0.9
#  aes_crypt: ^0.1.1
  flutter_app_badger: ^1.1.2
  flutter_local_notifications: ^1.4.4+2
  #  loading_dialog: ^0.0.1+1 #latest version
  permission_handler: ^4.3.0
  flutter_html: ^1.1.0
  shared_preferences: ^0.5.7
  flutter_inappwebview: ^4.0.0+4
  flutter_webview_plugin: ^0.4.0
  jwt_decoder: ^1.0.4
  flutter_echarts: 1.5.0
  sticky_headers: ^0.1.8+1
  charts_flutter: ^0.9.0
  fl_chart: ^0.20.0
  flutter_tree: ^2.0.3

**Comment by wuweijian1997** [comment]
`flutter pub deps`能看到你的插件依赖，可以看一下是哪个插件依赖了`video_player_platform_interface`

**Comment by 132056135** [comment]
> 
是这个flutter_html

**Comment by wuweijian1997** [comment]
可以升级这个库的版本试试，要是没问题就把issues关掉吧，下次尽量用英文，方便大家解决问题。
