### ISSUE TITLE
The directory of *.so on flutter linux app

### ISSUE THREAD

**Issue by fayfive** [flutter/flutter#105961]
I have done ```flutter create test1```
I create a app of Linux. I have a library ```liba.so``` ```liba.dart```
I want to add the liba.so to the linux app. The directory of  liba.so is ```linux/lib/liba.so```
When I ```flutter run```, I find that the *so can not be move to the ```budle/lib```
I want to know How can I layout the *.so in a flutter of linux or I should add some command in ```linux/CMakeLists.txt```？
Thanks！

**Comment by stuartmorgan** [comment]
> or I should add some command in `linux/CMakeLists.txt`

If you are adding your own library, it is up to you to bundle it, yes.

Closing as this is not a Flutter issue.
