### ISSUE TITLE
.print() as Extension method on String etc..

### ISSUE THREAD

**Issue by hardiklakhalani** [flutter/flutter#105973]
We code & use `print()` function all the time. Atleast we beginners do coz breakpoints are not our thing _yet._

## Use case

So my feature request is,
Addition of an extension method callable on every console printable Objects such as String, List, Map etc..

If you are not getting the idea then for example There is already `.toString()` method which can be called upon certain objects.

Benefit of this feature is eliminating cut/copy/paste process in separate print() and we can just print existing data by appending the method.

There's not any package providing this feature unless we create for ourselves personally.

It would be good if flutter gets this feature implemented by default. 

## Proposal

Final output code would be like:
```
"This is a String".print();
[This,is,a, list].print();
var someVariable = data;
someVariable.print();
```

**Comment by stuartmorgan** [comment]
If for some reason you prefer `foo.print()` to the existing `print(foo)`, you can trivially create an extension method for it. This isn't something we would add in Flutter, as extension methods violate our style guide
