### ISSUE TITLE
TabBar indicator color is not displaying one particular color

### ISSUE THREAD

**Issue by bujdy** [flutter/flutter#105904]
## Steps to Reproduce

After giving TabBar `indicatorColor: Color(0xffCF2C29)`, color wont show. But if i change at least one character (lets say number 9 to 8) suddenly i can see the color. 

**Expected results:** Red indicator color under tabbar

**Actual results:** ![image](https://user-images.githubusercontent.com/62099703/173404934-3523a432-a4fa-4cba-a00d-604f5bd50fcc.png)

**Comment by Mamun361054** [comment]
could provide some more code

**Comment by Mamun361054** [comment]
## Maybe help you

TabBar(
                      indicatorColor: Colors.white,
                      labelColor: Colors.white,
                      labelStyle: Get.textTheme.subtitle2,
                      indicatorSize: TabBarIndicatorSize.label,
                      tabs: [
                        Tab(child: Text('Home Page'),),
                        Tab(child: Text('View All'),),
                      ],
                    ),
