### ISSUE TITLE
Wrong auto wrap

### ISSUE THREAD

**Issue by gxl2024595** [flutter/flutter#105998]
## Use case

when i using widget Text,and allow auto wrap,fill the text 'scasdd-sadqwer-iip9-5fftq-ghkjhjhh'.
For currently,Text widget will wrap the content like this:

scasdd-sadqwer-
iip9-5fftq-ghk

Autually,the Text has enough speace to layout text like this:
scasdd-sadqwer-iip9-
5fftq-ghk

So,why auto wrapping the line at 'iip9-5fftq' for current  Text widget. Maybe it should wrap like this below when it has enough speace.
scasdd-sadqwer-iip9-
5fftq-ghk

**Comment by exaby73** [comment]
Hi @gxl2024595, please provide a [minimal, reproducible example][1] and the output of `flutter doctor -v`.

[1]: https://stackoverflow.com/help/minimal-reproducible-example
