### ISSUE TITLE
'image_picker/FLTImagePickerPlugin.h' file not found .  Please help me!   

### ISSUE THREAD

**Issue by 312236232** [flutter/flutter#105946]
/Volumes/DATA/flutter/.pub-cache/hosted/pub.dartlang.org/image_picker-0.8.4+11/ios/Classes/FLTImagePickerPlugin_Test.h:7:9: 'image_picker/FLTImagePickerPlugin.h' file not found

**Comment by huycozy** [comment]
Hi @312236232 
Please try deleting `podfile.lock`, `ios/Pods/` and run:
```
flutter clean
flutter pub get
cd ios
pod install
```
The detailed steps in https://github.com/flutter/flutter/issues/16036#issuecomment-380712094 may help you.

If the above solution isn't helpful, try to provide more information to investigate this issue further.
- Share the output of `flutter doctor -v`
- Share `Podfile` content

I'd love to hear your feedback.

**Comment by 312236232** [comment]
Thinks very much!!!!!!
