### ISSUE TITLE
Plugin tree closed on "Scorecards supply-chain security" failure

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#105912]
https://github.com/flutter/plugins/runs/6867166655?check_suite_focus=true

```
Failed to get repository information from GitHub, response 401: Bad credentials
{
  "message": "Bad credentials",
  "documentation_url": "https://docs.github.com/rest"
}
```

**Comment by drewroengoogle** [comment]
Taking a look!

**Comment by drewroengoogle** [comment]
It looks like the global token used by scorecards has expired, as this is affecting all flutter repositories. I'm taking a look at how to recreate the token.

**Comment by drewroengoogle** [comment]
Reran the plugins scorecard job. Success!

https://github.com/flutter/plugins/actions/runs/2490205462

Closing, feel free to reopen if necessary.

**Comment by stuartmorgan** [comment]
Is there a strategy in place to prevent this from closing the trees again in 3 months?

**Comment by drewroengoogle** [comment]
I think Godofredo misspoke, as the expiration has been set to 1 year!

With that in mind, we have created a bug card and are set to be notified a week in advance of the expiration to replace the token again. I'm currently creating documentation on how to create the token for whoever replaces the token.

**Comment by stuartmorgan** [comment]
This just regressed again

https://github.com/flutter/packages/runs/6887964948?check_suite_focus=true

**Comment by godofredoc** [comment]
I believe it was not fixed for this repo, there were per repo secrets overriding the global ones. Please give it another try.

**Comment by godofredoc** [comment]
This is fixed now
