### ISSUE TITLE
Expose idToken in Firebase Auth

### ISSUE THREAD

**Issue by Solido** [flutter/flutter#10594]
Currently when you authenticate with Google to Firebase you receive a **FirebaseUser.UID** that is the _definitive_ ID.

Our Flutter application is calling our Rest API and sending this UID is not secure because if stolen there's nothing we can do.

When working with android or Angular2 client you'll get a **Firebase Token** instead that you can pass to your server as JWT Authorization header and by calling Firebase SDK the backend can get the real **FirebaseUser.UID**

[https://firebase.google.com/docs/auth/admin/verify-id-tokens](https://firebase.google.com/docs/auth/admin/verify-id-tokens)

How can we accomplish that with Flutter to secure our application ?

This is the call that you made from java. I guess it can be called by FirebaseUser.dart in the future ?

```java
FirebaseUser mUser = FirebaseAuth.getInstance().getCurrentUser();
mUser.getToken(true)
```

Thank you !

**Comment by eseidelGoogle** [comment]
@collinjackson would know.

**Comment by collinjackson** [comment]
You're right that this is needed if you're talking to a custom backend. I'll add a method to `FirebaseUser` to retrieve `idToken`. Thanks for the feedback!

**Comment by collinjackson** [comment]
This is fixed in [firebase_auth](https://pub.dartlang.org/packages/firebase_auth) 0.0.4, please give this a try and let me know if it works for you.

**Comment by Solido** [comment]
You can see the decoded JWT token using jwt.io and my Firebase sdk was also successful.
💯

**Comment by ericel** [comment]
**firebase_auth: ^0.11.0**
What is the method to get the token?
I tried with the latest version but can't find any method  for that.

 ```
FirebaseUser mUser = FirebaseAuth.instance.currentUser();
     mUser.getToken(true)
```
The above won't work, neither is this:
```
FirebaseUser mUser = FirebaseAuth.getInstance().getCurrentUser();
mUser.getToken(true)
```

@Solido how did you get the token?

**Comment by premtemp1** [comment]
@collinjackson  I also need the refresh token . How do we get this value.. We need it to authenticate against our backend

It should similar to the restful call --https://identitytoolkit.googleapis.com/v1/accounts:signUp?key=[API_KEY]

**Comment by kroikie** [comment]
@Solido

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1000. Any further collaboration will be done there.
