### ISSUE TITLE
Dragging the list off the screen fires an exception

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#106]
<a href="https://github.com/Hixie"><img src="https://avatars.githubusercontent.com/u/551196?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Hixie](https://github.com/Hixie)**
_Monday Jul 20, 2015 at 20:33 GMT_
_Originally opened as https://github.com/flutter/engine/issues/150_

----

_From @Hixie on April 20, 2015 16:21_

If you drag a fixed height scrollable list's contents off screen, once it goes entirely off-screen it throws an exception because it is trying to render item -1.

_Copied from original issue: domokit/mojo#102_

**Comment by abarth** [comment]
This issue is fixed.
