### ISSUE TITLE
[tool]: How to calculate the Dart SDK snapshot download URL

### ISSUE THREAD

**Issue by TheOneWithTheBraid** [flutter/flutter#106099]
When downloading and installing the Flutter too, it first downloads the Dart SDK snapshot, having the URL:

```
DART_SDK_BASE_URL="${FLUTTER_STORAGE_BASE_URL:-https://storage.googleapis.com}"
DART_SDK_URL="$DART_SDK_BASE_URL/flutter_infra_release/flutter/$ENGINE_VERSION/$DART_ZIP_NAME"
```

E.g. for current stable Flutter, this results in: https://storage.googleapis.com/flutter_infra_release/flutter/caaafc5604ee9172293eb84a381be6aadd660317/dart-sdk-linux-x64.zip

I was wondering what SHA256 (is it?) the `ENGINE_VERSION` is computed with? In `$FLUTTER_ROOT/bin/flutter/internal/update_dart_sdk.sh`, it is simply read out from `$FLUTTER_ROOT/bin/internal/engine.version`

In environments Flutter is installed in without any network access, this might be useful to know. Especially e.g. for distributors of Linux distributions willing to package Flutter.

**Comment by rzr** [comment]
May this help:

https://github.com/meta-flutter/meta-flutter/blob/kirkstone/conf/include/flutter-version.inc
