### ISSUE TITLE
iOS 11 SmartInvert is not smart for Flutter apps

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#10603]
A Flutter app is completely inverted when using SmartInvert. It seems to behave exactly like the old (now called "clasic") invert. One difference between classic and smart invert is that smart invert should not invert pictures. There might be more differences...

**Comment by jonahwilliams** [comment]
Investigating using the a11y trait for images, found that this does not effect smart invert

**Comment by jonahwilliams** [comment]
Idea: invert the pixels of images ourselves, so that when smart invert inverts them...they are back to normal.   cc @chinmaygarde @liyuqian , is this something we can do through skia?

**Comment by liyuqian** [comment]
@jonahwilliams : do you mean to invert an RGB pixel from (r, g, b) to (255-r, 255-g, 255-b)? Would SkColorFilter or SkColorSpaceXform be useful? I think Flutter already uses SkColorSpaceXformCanvas so we probably could just add a little more tweak to that.

**Comment by jonahwilliams** [comment]
Thanks! Yes, I believe smart invert does something similar, so as long as it is an invertable it should work. Looks like Paint does expose a `colorFilter` option, I can look into how to wire this up on the framework side.

**Comment by jonahwilliams** [comment]
actually ... hm I am not sure if this can be expressed as a color filter, but we could probably do it as some sort of color space transform

**Comment by jonahwilliams** [comment]
FYI to future, there is a property on UIView to disable this, not applicable to our semantic hierarchy.
https://developer.apple.com/documentation/uikit/uiview/2865843-accessibilityignoresinvertcolors?language=objc
