### ISSUE TITLE
[Impeller] OpenGL ES: Reduce API traffic by maintaining a pass bindings cache.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#106056]
Similar to the [Metal PassBindingsCache](https://github.com/flutter/engine/blob/fb80e863edfd1ef9610db791b47989c17eb467ff/impeller/renderer/backend/metal/render_pass_mtl.mm#L188), a mechanism must be present in OpenGL to reduce redundant API calls. This is relevant with some drivers for performance. Also, this greatly improves the readability of GPU trace captures.

**Comment by ColdPaleLight** [comment]
@guoguo338 would like to file a PR to fix it.

**Comment by chinmaygarde** [comment]
@ColdPaleLight For this and the other issues marked as in-progress, if no progress is being made, can you please un-assign yourself so other takers can work on it? No hurry of course :)

**Comment by jonahwilliams** [comment]
I think we should probably not do this, unless we have benchmarks show it is faster. Tentatively closing for now, but we can re-open based on benchmarks
