### ISSUE TITLE
[url_launcher] Link widget is missing corresponding InlineSpan implementation

### ISSUE THREAD

**Issue by TheOneWithTheBraid** [flutter/flutter#106012]
While Flutter features the `Link` Widget creating semantically correct links for a while, it is not possible to make use of this advantage when using `Text.rich()` and corresponding `InlineSpan` elements.

I would fence propose to include a corresponding `LinkSpan` element into the library `package:url_launcher/link.dart` providing an `InlineSpan` implementation representing an `anchor` tag on the web.

Current workarounds are either using a `WidgetSpan` containing a `Link` widget. This causes trouble in case the Link's text is too long for a line (and is garbage in regard of code hierarchy). Another workaround is simply using a `GestureDetector` on a `TextSpan` which simply doesn't provide a link.

**Comment by TheOneWithTheBraid** [comment]
Yes, thanks for the clarification. Of course, we workaround it that way as of now. Anyway, this workaround simply does not create a link as in an `anchor` tag in HTML (like the `Link()` widget does it) but simply adds an event listener on a single action (e.g. tap). This os a very bad practice in regard of handling links.

For web users and visually limited users using screen readers and semantic aid, this is a huge regression, as the browser does not handle the link as link. E.g. context menu actions like copying or opening in new tab won't work hence.

**Comment by gnprice** [comment]
I believe this is the same issue as #91600, so I'm closing this one to consolidate the discussion into that thread.

If there's information you feel is missing in that thread, please add it there.
