### ISSUE TITLE
AnimatedOpacity tells me its expensive, but not why?

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#10601]
Would be nice to have a second sentence there which gave some minimal explanation of why or if there are cases which are more expensive vs others?

**Comment by Solido** [comment]
Same goes for https://docs.flutter.io/flutter/widgets/IntrinsicWidth-class.html ?

**Comment by Hixie** [comment]
Fixed it for Canvas, IntrinsicWidth, and IntrinsicHeight. Please open new bugs if there's more cases where this should be clarified.
