### ISSUE TITLE
[Impeller] Embedded shader sources don't show up in the Metal frame debugger.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#106066]
This used to work. Thats how I wrote the Wiki entry for debugging shaders https://github.com/flutter/engine/blob/main/impeller/docs/read_frame_captures.md#debugging-a-shader

**Comment by chinmaygarde** [comment]
cc @iskakaushik

**Comment by iskakaushik** [comment]
This seems to be working as of revision: 2612e88bfe659105d4a3692b97c83c49a50de60b

I ran with `--gtest_filter=*CanRenderRoundedRectWithNonUniformRadi*` and captured the frame as documented in the impeller wiki, which is awesome, btw.

<img width="512" alt="image" src="https://user-images.githubusercontent.com/1006071/174888290-468af80f-8a66-4d40-bc17-4bba70b32851.png">

@chinmaygarde  feel free to re-open if this is still failing for you.

**Comment by chinmaygarde** [comment]
This always works on MacOS. It was an iOS device (where we can gather shader instrumentation) where it doesn't show up.

**Comment by iskakaushik** [comment]
@chinmaygarde I'm able to see it on iOS as well:

<img width="512" alt="image" src="https://user-images.githubusercontent.com/1006071/175098097-8e9daf70-e249-40ed-bfe1-b2619f00c77b.png">

This was running a simple flutter application on xcode: 13.4.

**Comment by chinmaygarde** [comment]
Good to know. Thanks for verifying. Dang. It may be my local setup in that case. Can you also dump the version of your device as well as the mac host version? I'll do some debugging on my end too.

**Comment by iskakaushik** [comment]
Ok, so this works with

```
  elif args.platform == 'ios':
    command += [
        '--std=ios-metal2.1',
        '-mios-version-min=15.0',
    ]
```

to `build_metal_library.py`, will attempt to isolate the cause an go from there.
