### ISSUE TITLE
Request: Update cmake version bundled with Flutter snap from 3.10

### ISSUE THREAD

**Issue by chirag729** [flutter/flutter#106005]
Would it be possible to update the cmake version bundled with the Flutter snap? The current version 3.10 is several years old. 

I'm running into an issue building an app with the latest version of the [audioplayers ](https://pub.dev/packages/audioplayers) package which requires a cmake version of 3.11 

Installing Flutter manually is an acceptable workaround for local development but for CI environments and others like snapcraft it is not.

**Comment by danagbemava-nc** [comment]
Hi @chirag729, the snap package has its own dedicated repo over on https://github.com/canonical/flutter-snap. 

Kindly report this issue over there so that it can be properly addressed.

Thank you
