### ISSUE TITLE
git-source flutter pub get not sustainable for large repos

### ISSUE THREAD

**Issue by mralbertchen** [flutter/flutter#106010]
Currently under the hood `flutter pub get` uses `git clone --mirror` to get git-sourced packages, even if a tag/branch is specified. At my company we have a really large repo with orphaned branches for each release but as the repo grows the time it takes for `flutter pub get` grows to an unsustainable time (currently 30 min+). To fix this we have to periodically purge the entire package repo.

Suggestion: Use `git clone --branch <tag-here> --depth 1` for `flutter pub get` so it's a shallow clone.

**Comment by christopherfujino** [comment]
> Currently under the hood `flutter pub get` uses `git clone --mirror` to get git-sourced packages, even if a tag/branch is specified. At my company we have a really large repo with orphaned branches for each release but as the repo grows the time it takes for `flutter pub get` grows to an unsustainable time (currently 30 min+). To fix this we have to periodically purge the entire package repo.
> 
> Suggestion: Use `git clone --branch <tag-here> --depth 1` for `flutter pub get` so it's a shallow clone.

Can you provide some more details? As far as I know, the flutter CLI tool is not directly fetching any pub dependencies, but delegating that work the to the pub binary from the Dart SDK.

If you use a published package, I believe that `pub get` will download a snapshot of that version. I'm guessing that you are depending on these via git in your pubspec.yaml? If so, there is an upstream bug tracking that already: https://github.com/dart-lang/pub/issues/2686

**Comment by mralbertchen** [comment]
> > Currently under the hood `flutter pub get` uses `git clone --mirror` to get git-sourced packages, even if a tag/branch is specified. At my company we have a really large repo with orphaned branches for each release but as the repo grows the time it takes for `flutter pub get` grows to an unsustainable time (currently 30 min+). To fix this we have to periodically purge the entire package repo.
> > Suggestion: Use `git clone --branch <tag-here> --depth 1` for `flutter pub get` so it's a shallow clone.
> 
> Can you provide some more details? As far as I know, the flutter CLI tool is not directly fetching any pub dependencies, but delegating that work the to the pub binary from the Dart SDK.
> 
> If you use a published package, I believe that `pub get` will download a snapshot of that version. I'm guessing that you are depending on these via git in your pubspec.yaml? If so, there is an upstream bug tracking that already: [dart-lang/pub#2686](https://github.com/dart-lang/pub/issues/2686)

Thank you. I was having a hard time finding if someone had mentioned a similar issue. This is exactly it. I will track through that issue instead.
