### ISSUE TITLE
(willing to pr) How to mutate `ui.Image` in Flutter, or draw frequently mutated image?

### ISSUE THREAD

**Issue by fzyzcjy** [flutter/flutter#106021]
## Use case

I have a roughly 1000x1000 image, which will be mutated at 60fps, each time changing color of only dozens of pixels.

Then, I need to display this image in Flutter. Of course I can use `Image.memory(the_uint8list_data)`, but it will be extremely costly since it will create 60 new big images in one second. I have also checked `ui.Image`, but it is opaque and I do not see any handles to change pixel data. I originally used `Path`-based solutions, but that was also too slow because the mutation can happen for a long time and the Path will be very huge.

The question is, how can I display this image with high performance?

I am willing to make a PR, for example, modifying ui.Image etc.

**Comment by jonahwilliams** [comment]
Making ui.Image mutable would break caching assumptions across the engine, framework, and ecosystem and is not something that would ever be supported.

Anything that goes through an image decoding path, such as Image.memory or fromPixels will likely be several orders of magnitude slower than what you need. 


What im imaging you'd like is something like the abiility to create/upload a texture from a typed data array, something like using texImage2D in WebGL:

```
gl.texImage2D(gl.TEXTURE_2D, 0, gl.RGBA, 1, 1, 0, gl.RGBA, gl.UNSIGNED_BYTE,
              new Uint8Array([ /* data goes here */]));
 ```
 
 Of course ui.Image is the closest thing we have to a texture handle on the framework side. Whether or not it would be feasible to support an API like above I don't know.
 
 @chinmaygarde @dnfield

**Comment by fzyzcjy** [comment]
Totally agree! So what should I do? I am willing to PR.

Btw one more reason for this feature: For advanced usages, people may want to directly control some bitmaps in Flutter, since one major advantage of Flutter is its flexibility and the ability to access low-level things when really needed.

**Comment by dnfield** [comment]
It might work to use vertices for this.

We can't have a mutable image. It's not supported anywhere up or down the stack (framework, dart:ui, Skia).

I strongly doubt that re-uploading a 1000x1000 texture every frame will be performant enough either - are the pixels you're changing clustered together or far apart?

**Comment by fzyzcjy** [comment]
@dnfield Thanks for the reply! This is my real use case:

I have a core component, which is like a ["painter"](https://pub.dev/packages/painter) (but with quite complex blending, saveLayer, etc). So, the original implementation is, I have `List<Path>` that represents each stroke of the user on the painter. Then I have a `CustomPainter` which draws each `Path` in each render, like `void paint() { for(var path in paths) canvas.drawPath(path); }`.

However, there are really a lot of strikes when the user is painting. There can be >10000 points totally in all paths. Thus, we see that, the UI becomes more and more laggy and non-responsive as the user draws more strokes.

That is really unacceptable. Imagine when you draw an image on the painter - the first few minutes UI is very smooth, and after a while when there are tons of strokes, UI is extremely slow :( In other words, UI performance is O(N) where N is the number of strikes.

If we can directly control a 1000x1000 texture, we will only change a dozen of pixels every frame (since every frame only a little bit of new stroke) so not slow. The "re-uploading a 1000x1000 texture every frame" may be slow - that is why I want to PR and avoid too slow - but it is O(1) instead of O(N).

I would appreciate it if some hints could be given about the problem above. Maybe I am going in the wrong direction? Thank you!

**Comment by dnfield** [comment]
How will you handle the complex blending and save layer logic if you directly control the pixels? 

Can your application just use fewer paths and append to them as needed? Or, can it use some intermediate data structure representing the drawn path and appropriately smooth it out for a given scale to draw some more reasonable path than one with lots of extra/unnecessary commands?

Can you use the drawPoints API instead? drawVertices could work too if you just think about your rectangles as two triangles - but neither of these APIs will give you AA, which I imagine you want.

Part of what I'm having trouble with on this issue is that it's suggesting a solution for a problem that I'm not sure I fully understand.

**Comment by fzyzcjy** [comment]
@dnfield Thank you very much for your reply!

> How will you handle the complex blending and save layer logic if you directly control the pixels?

Luckily it is a layered structure and complex things happen between different layers. So I plan to have a bitmap for each layer. Just imagine a layer as a PhotoShop layer.

> Can your application just use fewer paths and append to them as needed? Or, can it use some intermediate data structure representing the drawn path and appropriately smooth it out for a given scale to draw some more reasonable path than one with lots of extra/unnecessary commands?

I guess no... Users can write handwritten texts on this "painter" component, so you know, it must be of high resolution. Btw I do have intermediate data structure.

> Part of what I'm having trouble with on this issue is that it's suggesting a solution for a problem that I'm not sure I fully understand.

Feel free to ask anything! 

For a mental model, just think of it like a "painter". Or a "photoshop" where you can draw things.

**Comment by fzyzcjy** [comment]
P.S. A normal app user will paint on the painter. Thus, the `Path`s will accumulate in normal cases, e.g. each second some new points in Paths are added. This is one important property of the use case: The data is *appended*, not modified arbitrarily. Users may do things like "undo" which is surely not appending, but those operations are sparse and can tolerate some slowness.

**Comment by dnfield** [comment]
I think it would help to have a realistic test case that is currently too slow.  However, I also think that you'll end up getting responses like "optimize it this way" and maybe that won't work for your particular application.

**Comment by fzyzcjy** [comment]
> I think it would help to have a realistic test case that is currently too slow.

I have it and use Flutter's benchmarking tools to even reliable reproduce it.

If you want it, I can make one with minimal dependency that mimics the real case (you know - the real case is tons of engineering code so quite big).

**Comment by huycozy** [comment]
> I have it and use Flutter's benchmarking tools to even reliable reproduce it.
> 
> If you want it, I can make one with minimal dependency that mimics the real case (you know - the real case is tons of engineering code so quite big).

@fzyzcjy 
Based on your comments, I will leave this issue as `waiting` for the minimal reproducible real case in order to the team analyzes the issue in more detail.

**Comment by fzyzcjy** [comment]
@huycozy I have done a minimal reproducible sample just now, but then realized that publicly sharing it leaks too much secret implementation details, and it is very non-intuitive to merely looking at that sample without knowing the feature - just a few strange overlapping strokes etc.

So I would appreciate it if I could just provide replies (texts) to describe what is happening. 

Also looking forward to contribute PR.

**Comment by huycozy** [comment]
@fzyzcjy 
It'll be great if you could provide a completed and minimal reproducible code so that we can verify this issue.
You may find out something when minimizing/reinterpreting the issue (from a personal point of view)
