### ISSUE TITLE
Mappings for 'Esc' KeyboardEvent key values are missing.

### ISSUE THREAD

**Issue by egramond** [flutter/flutter#106062]
KeyboardEvent key values in keyboard_maps.dart have mappings for 'Escape' but not for the older 'Esc' key values.

These values were used by older IE and Firefox browsers, and are still being generated by the Cobalt browser. 

(Specifically, this is causing problems when running a Flutter-Web app on Cobalt and using the back button on the TV remote.  The KeyboardEvent generated by Cobalt has an 'Esc' key value, which then does not get interpreted by Flutter as an LocalKeyboardKey.escape event.)

See the note on the 'Escape' value here:
https://developer.mozilla.org/en-US/docs/Web/API/UI_Events/Keyboard_event_key_values#ui_keys

**Comment by egramond** [comment]
cc @dkwingsmt

**Comment by maheshmnj** [comment]
Hi @egramond, Thanks for filing the issue. Can you please share the steps to verify the issue along with the output of `flutter doctor -v`?

Thanks

**Comment by egramond** [comment]
This is a bit tricky to reproduce, as it requires running Flutter-Web on a Cobalt browser (or some really old Firefox browser).

There is more details on our internal bug at: b/236048950

I made an attempt at fixing the issue that was wrong because I was editing a generated file, but it did have a unit test that catches the issue. You can see it here:
https://github.com/flutter/flutter/pull/106059/commits/58fa5754dc31dab90f0068615654a409f9be8fe2#diff-ac9c378fae8af8f4ffb68fad0b56e14f9f15ab797a0e7271a3690317a4df9c59

**Comment by maheshmnj** [comment]
Thanks for the info @egramond, Looks like the bug is identified and a related PR is ready to be merged. Labeling it as a valid bug.
