### ISSUE TITLE
[Proposal]Allow users to force a layer to be raster cached

### ISSUE THREAD

**Issue by fzyzcjy** [flutter/flutter#106006]
## Use case

Currently https://github.com/flutter/flutter/issues/88832 says "Raster cache heuristics are bad". However, in some cases, raster caches are very much needed. For example, some complex Path + drawImage + ... in my app. Thus, I would appreciate it if I could forcefully tell Flutter to enable raster cache for a specific portion of my app.

I am willing to contribute.

## Proposal

Add an API to force a portion to be raster cached. For example, maybe a widget, or a renderobject, or maybe need to dig into flutter/engine code.

**Comment by maheshmnj** [comment]
Hi @fzyzcjy, Thanks for filing the issue and for your interest to contribute. I am quite not sure about the feasibility of this proposal, I will leave this for the team to decide.

cc: @chinmaygarde

**Comment by fzyzcjy** [comment]
Hi thanks, and looking forward to further replies!

**Comment by fzyzcjy** [comment]
Thank you!

**Comment by dnfield** [comment]
We are not going to open up ways for users to control what goes into the raster cache.

That said, I'm working on a series of issues that would allow users to effectively create and manage their own raster cache entry-like objects. This would involve converting a Picture (or, eventually, a Layer) to a GPU resident image that the user can hold and dispose when needed. 

Once https://github.com/flutter/flutter/issues/106381, it should be trivial to add a `toGpuImage` method on `Layer` in the framework.

**Comment by fzyzcjy** [comment]
@bleroux 

Hi, I wonder whether the `Transform(filterQuality: FilterQuality.none)` hack will work on *all machines*, or *some of the machines*?

I have tested 4 devices and they all work. But not sure whether there exist some machines that will not have a raster cache even if this is enabled?

**Comment by dnfield** [comment]
The raster cache is normally never disabled - I'm pretty sure you'd need a custom build of the engine to disable it.

**Comment by fzyzcjy** [comment]
Well my question is whether the ` Transform(filterQuality: FilterQuality.none)` hack will enforce an (extra) raster cache on the subtree below Transform?

**Comment by fzyzcjy** [comment]
Today I see the `Transform(filterQuality: FilterQuality.none)` hack does not work sometimes even on the same machine... More specifically, sometimes, even if the subtree content does not change and no repaint happens, the raster cache is rebuilt...

**Comment by dnfield** [comment]
Layers and scenes now have a way to call toImageSync - marking this as fixed.

**Comment by fzyzcjy** [comment]
🎉 Looking forward to the next stable release!
