### ISSUE TITLE
Windows tests failing when downloading canvaskit zip file

### ISSUE THREAD

**Issue by iskakaushik** [flutter/flutter#106151]
See: https://ci.chromium.org/ui/p/flutter/builders/try/Windows%20build_tests_2_3/22426/overview

per @jason-simmons a dart archive package upgrade should fix this.

**Comment by iskakaushik** [comment]
cc: @jonahwilliams

**Comment by jonahwilliams** [comment]
Fixed via https://github.com/flutter/flutter/pull/106157
