### ISSUE TITLE
[shared_preferences] Use path_provider directly in windows/linux

### ISSUE THREAD

**Issue by wangbax** [flutter/flutter#106194]
## Steps to Reproduce

1. `PathProviderPlatform.instance = MyFakePathProviderPlatform` in app `main.dart`
2. `MyFakePathProviderPlatform` override all directory function

**Expected results:** 
`shared_preferences` file location follow where i `override`
**Actual results:** 
`shared_preferences` file location not changed
<details>
<summary>Code sample</summary>
main.dart

```dart
PathProviderPlatform.instance = FakePathProviderWindows();
```
fake.dart

```
class FakePathProviderWindows extends PathProviderPlatform {

  @override
  Future<String?> getApplicationSupportPath() async => r'C:\appsupport';

  @override
  Future<String?> getTemporaryPath() async => null;

  @override
  Future<String?> getLibraryPath() async => null;

  @override
  Future<String?> getApplicationDocumentsPath() async => null;

  @override
  Future<String?> getDownloadsPath() async => null;

}
```

**Comment by stuartmorgan** [comment]
Using `path_provider_<platform>` is an implementation detail of `shared_preferences`; you should not be trying to change `shared_preferences` behaviors by changing internal implementation details of `shared_preferences`. If you want `shared_preferences` to have fake behavior, you need to create a fake `SharedPreferencesPlatform` implementation.

(We use the platform implementations directly on purpose; it prevents the native code for all other `path_provider` platforms from being pointlessly built into an application that's only using `shared_preferences`.)
