### ISSUE TITLE
Layout with multiple MaterialButtons: Animation framerate drops considerably on Nexus 6P

### ISSUE THREAD

**Issue by hugovangalen** [flutter/flutter#10614]
**Issue description**
I am observing a considerable animation lag on the Nexus 6P on the ripples of the MaterialButton if there are a couple of them on the scene. 

I do not know if other devices are affected, but I am not observing this in the emulator: no matter how much buttons I add to the scene, the emulator appears to keeps animating all the ripples smoothly without any noticeable performance difference.

I initially thought this was due to the complexity of the layout (nested rows/columns with buttons) but, in an attempt to narrow down the issue, after extracting the relevant code into a separate project and simplifying the layout, I noticed that it is still not animating as smooth as it ought to. 

**Steps to reproduce**
I have added code below that demonstrates the matter. It initially shows a single button: holding your finger will animate the ripple smoothly, as expected. 

After tapping, there will be 18 buttons on the scene (I added more so the issue is significantly observable). 

Touch and holding any button will show a ripple that seems to skip a few frames and the animation feels choppy.

**Code**
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(new FramerateDroppingApp());
}

class FramerateDroppingApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: 'Testing',
      theme: new ThemeData(
        primarySwatch: Colors.green,
      ),
      home: new FramerateDropping(),
    );
  }
}

class _FramerateDroppingState extends State<FramerateDropping> {
  bool _showMore = false;

  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(
        title: new Text("TEST"),
      ),
      body: _showMore ? _createNineChildren() : _createOneChild(),
    );
  }

  void _flickAll() {
    setState( () {
      _showMore = !_showMore;
    } );
  }

  Widget _createChild() {
    return new MaterialButton(
        color: Colors.green,
        elevation: 4.0,
        minWidth: 32.0,
        height: 32.0,
        onPressed: _flickAll,
        child: new Text( 'Foo' ),
    );
  }

  List<Widget> _createMore() {
    return [
      _createChild(),
      _createChild(),
      _createChild(),

      _createChild(),
      _createChild(),
      _createChild(),

      _createChild(),
      _createChild(),
      _createChild(),
      
      _createChild(),
      _createChild(),
      _createChild(),

      _createChild(),
      _createChild(),
      _createChild(),

      _createChild(),
      _createChild(),
      _createChild(),
    ];
  }

  Widget _createOneChild() {
    return _createChild();
  }

  Widget _createNineChildren() {
    return new Column( children: _createMore() );
  }
}


class FramerateDropping extends StatefulWidget {
  @override
  State<StatefulWidget> createState() => new _FramerateDroppingState();
}
```

**Comment by Hixie** [comment]
Can you confirm if you are using debug mode or release mode?

**Comment by hugovangalen** [comment]
I can confirm this happens in both modes.

**Comment by eseidelGoogle** [comment]
If someone is interested in debugging, the first step is probably to turn on showPerformanceOverlay to get a sense as to if this is time spent on the Dart thread or the Rasterizer/GPU thread. I strongly suspect it's the latter.  MaterialApp has several first-line-of-defense perf debugging flags:
https://docs.flutter.io/flutter/material/MaterialApp-class.html

After that we'll escalate to taking a trace from observatory or using `flutter trace` which can tell us how the time is being spent on those threads.

**Comment by hugovangalen** [comment]
I tested this today on the master branch, and it animates much smoother on the Nexus 6P now.
