### ISSUE TITLE
Missing Android permissions

### ISSUE THREAD

**Issue by FrancisShanahan** [flutter/flutter#10618]
## Steps to Reproduce

When adding image support to the Chat tutorial app,  the Android Camera and Media permissions are missing. On a Nexus 6P running Android O my screen was blank when clicking the camera icon until adding the permissions to the Android Manifest. 

Suggested fix: Add the following to AndroidManifest.xml
 &lt;uses-permission android:name="android.permission.CAMERA"/&gt;
 &lt;uses-permission android:name="android.permission.MEDIA_CONTENT_CONTROL"/&gt;

**Comment by mit-mit** [comment]
Hi, just confirming, is this in this codelab? https://codelabs.developers.google.com/codelabs/flutter-firebase/

**Comment by FrancisShanahan** [comment]
Yep, sorry if that wasn't clear. It's the last step "Add Image Support".  

    On Monday, June 12, 2017 9:46 AM, Michael Thomsen <notifications@github.com> wrote:
 

 Hi, just confirming, is this in this codelab? https://codelabs.developers.google.com/codelabs/flutter-firebase/—

**Comment by mit-mit** [comment]
cc @LarkAscending

**Comment by LarkAscending** [comment]
Added new section "Enable camera and media content access on Android" to Step 10. PTAL:
https://codelabs.developers.google.com/codelabs/flutter-firebase/#9
Will verify shortly - feel free to beat me to it!

**Comment by LarkAscending** [comment]
As part of a larger update cycle for plugin upgrades, I tested the codelab on a 5x without these permissions and could not repro. For me there was no issue with accessing the camera and images on the device without these permissions. 

Access also works with them (of course). So I left them in the codelab, assuming they will help other users out there.

Thanks for this issue!
