### ISSUE TITLE
Devicelab tests are timing out occasionally on Windows-4

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#106132]
This caused test flakes and tree red.
https://chromium-swarm.appspot.com/bot?id=flutter-win-4

<img width="1289" alt="Screen Shot 2022-06-16 at 2 08 03 PM" src="https://user-images.githubusercontent.com/54558023/174163918-3691fbc9-3ae0-4168-94b9-4a208276b656.png">

**Comment by yusuf-goog** [comment]
These failures look legitimate? Is there something that needs to be done here?

**Comment by keyonghan** [comment]
This testbed has been passing consistently, maybe the newly added device recovery logic helps. Closing.
