### ISSUE TITLE
Observe 60+ ms raster times occassionally on customer:money demo app when attached with devtools

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#106125]
To reproduce, open customer moneys demo app on a mid range (Pixel 4 in my case) android app. After the first couple frames have stabilized, scroll up and down. Every so often, I'll see a massive raster time show up in devtools UI

![image](https://user-images.githubusercontent.com/8975114/174142763-6ccf0607-4db4-4888-accc-5afcf60c151c.png)
![image](https://user-images.githubusercontent.com/8975114/174142784-7cce696a-8135-45f4-984d-6dec487a9085.png)

I can't really tell what is going on. Is the app getting throttled? Is a major GC happening? Is something in DisplayListLayer::Preroll or RasterCache taking forever?

Needs investigation.

@iskakaushik @dnfield @gaaclarke

**Comment by dnfield** [comment]
I don't know how actionable it is for non-enginr developers

**Comment by jonahwilliams** [comment]
I don't see anything obvious with trace-skia:

![image](https://user-images.githubusercontent.com/8975114/174862176-bf5d8f2a-77fd-4f6e-9141-3df9fd18f90d.png)


What is Scene display lag?

**Comment by gaaclarke** [comment]
FWIW I was unable to reproduce it on iOS.  62k instances of "DisplayListLayer::RasterCache" and the longest one was 523µs.

<img width="1146" alt="Screen Shot 2022-06-21 at 10 34 21 AM" src="https://user-images.githubusercontent.com/30870216/174862280-1b857898-0007-4061-bd16-51aa270e2f3d.png">

**Comment by jonahwilliams** [comment]
Might be android specific then?

**Comment by dnfield** [comment]
Looks like a scheduling issue....

https://github.com/flutter/flutter/issues/106125#issuecomment-1162067019 is showing very high wall times and very low CPU times.

**Comment by jonahwilliams** [comment]
Do we already have a FR for devtools to include self/wall time in timeline?

**Comment by dnfield** [comment]
https://github.com/flutter/devtools/issues/3454

**Comment by jonahwilliams** [comment]
I'm decreasing the priority as I am increasingly convinced that this is actually due to continually pushing timeline traces
