### ISSUE TITLE
[engine] 3.x x86_64 embedder segfaults

### ISSUE THREAD

**Issue by jwinarske** [flutter/flutter#106118]
Segfault is happening in 3.x x86_64 builds on Ubuntu 20.04. aarch64 builds do not exhibit this problem.  Ubuntu22 via WSL does not segfault.  We are standardized on Ubuntu 20.04 internally.  So this is a high priority issue for us (Toyota).

Build flags:
--unoptimized --runtime-mode debug --no-goma --lto --clang --embedder-for-target --full-dart-sdk --target-os linux --linux-cpu x64 --target-triple x86_64-linux-gnu

Repro happens with or without --unoptimized.

Seg fault happens with: https://github.com/freetype/freetype/blob/3f83daeecb1a78d851b660eed025eeba362c0e4a/src/base/ftobjs.c#L5656

The function that calls it has this note:
https://github.com/freetype/freetype/blob/3f83daeecb1a78d851b660eed025eeba362c0e4a/include/freetype/ftcolor.h#L1620

    @SInCE: * 2.11 -- currently experimental only! There might be changes without retaining backward compatibility of both the API and ABI.

It looks like it happens when it is trying to display the hello world text: "Futter Demo Home Page"
https://github.com/google/skia/blob/main/modules/skparagraph/src/OneLineShaper.cpp#L705

Full stack trace is documented here:
https://github.com/meta-flutter/flutter_embedded/issues/46

@aikalant

**Comment by jason-simmons** [comment]
I've been unable to reproduce this locally.

I tried building a `linux_debug_unopt_x64` embedder library using the configuration above and then successfully ran the `examples/glfw` sample app.  Rendering color bitmap emoji with the "Noto Color Emoji" font also worked as expected.

Is there a specific text string and/or font that reproduces this in your setup?

If it's crashing consistently in `FT_Get_Color_Glyph_Paint`, then try changing FreeType's configuration to disable related features
(e.g. comment out `#define TT_CONFIG_OPTION_COLOR_LAYERS` in `include/freetype-flutter-config/ftoption.h`)

**Comment by jwinarske** [comment]
@jason-simmons

* What machine and graphics card did you attempt to repro on?
* What version of GLFW and what EGL config is it using?  This is ours:
https://github.com/toyota-connected/ivi-homescreen/blob/main/shell/constants.h#L61

I'm finding some interesting interaction with our ThinkPads running NVidia graphics cards.  I found a combination that does work:
* Hybrid graphics (Intel and NVidia GPU) - segfaults when running Discrete NVidia GPU.
* https://storage.googleapis.com/flutter_infra_release/flutter/f15f824b57476e369b5e656f53d4c431c5b04b9a/linux-x64/linux-x64-embedder
* 2.10.5 icudtl.dat.  If I move this file forward to artifact from 3.0.2 it segfaults.  This is an odd one.

**Comment by jwinarske** [comment]
@jason-simmons Attempting to run GLFW example on Ubuntu 20.04 we see:
```
aik@thickpad:~/repos/flutter_embedded/third_party/engine/src/flutter/examples/glfw/build$ ./flutter_glfw ~/repos/hello/ /home/aik/repos/flutter_embedded/third_party/engine/src/out/linux_debug_unopt_x64/icudtl.dat
[ERROR:flutter/shell/platform/embedder/embedder_surface_gl.cc(103)] Could not create a resource context for async texture uploads. Expect degraded performance. Set a valid make_resource_current callback on FlutterOpenGLRendererConfig.
[ERROR:flutter/shell/gpu/gpu_surface_gl.cc(53)] Failed to set up Skia Gr context.
[ERROR:flutter/shell/common/platform_view.cc(76)] Failed to create platform view rendering surface
```

**Comment by cmc5788** [comment]
@chinmaygarde @jason-simmons -- to clarify, we're trying to run the GLFW example associated with the 3.0.2 engine to give you an easy reproduction example (https://github.com/flutter/engine/tree/f15f824b57476e369b5e656f53d4c431c5b04b9a/examples/glfw) but the error Joel mentioned above stops us. GLFW embedder example doesn't seem to run at all under Ubuntu 20.04, before even getting to the point of the segfault earlier in the thread.

**Comment by jwinarske** [comment]
@jason-simmons We have confirmed the Brandon's PR works on both Wayland (setting GLFW build flags) and X11.  The default for GLFW is OpenGL.

We are now focusing on sorting out how to get GLFW to setup EGL attributes and context to be the same as what we are using.

**Comment by jwinarske** [comment]
Also note I'm loading libflutter_engine.so via dlopen.  If gstreamer loads freetype2 before hand the same way to the same space, perhaps this is the reason.

https://github.com/toyota-connected/ivi-homescreen/blob/main/shell/engine.cc#L141

**Comment by jwinarske** [comment]
This fixes the issue:
```
 m_engine_so_handle = dlopen("libflutter_engine.so", RTLD_LAZY|RTLD_DEEPBIND);
```

**Comment by cmc5788** [comment]
Thanks for your help, all. Definitely a strange issue.

**Comment by chinmaygarde** [comment]
> `nm --dynamic libflutter_engine.so | grep FT_` shows the FreeType APIs as global text symbols.

Ok that looks like a Flutter issue and explains what @jwinarske ran into. We have tests for the iOS and Android dylibs to ensure that we don't leak internal symbols. Can we do the same for the embedder API please (lets file an issue)? I didn't even know `RTLD_DEEPBIND` was a thing TBH. So glad there is a workaround at least.

**Comment by chinmaygarde** [comment]
Filed https://github.com/flutter/flutter/issues/106453 with a mini-post mortem and followup steps. Thanks for the working through this tricky issue.

**Comment by 0xchase** [comment]
FYI, I have also run into this issue
