### ISSUE TITLE
[iOS] Flutter crashes with `libsystem_kernel.dylib __pthread_kill`

### ISSUE THREAD

**Issue by kutian** [flutter/flutter#106188]
We found https://github.com/flutter/flutter/issues/103477 occurs on flutter 3.0.0 as well, but with a lower probability of around 1/1000.
[62aab82ec6fbf1f681e7cb4b-1655355438256016000_type[1]_677045256.txt](https://github.com/flutter/flutter/files/8926859/62aab82ec6fbf1f681e7cb4b-1655355438256016000_type.1._677045256.txt)

**Comment by exaby73** [comment]
Hello @kutian. Please post your logs, `flutter doctor -v` and `flutter run -v` logs here so that it's easier to follow the issue and investigate it. Thanks

**Comment by kutian** [comment]
···
Incident Identifier: C3786E04-15CE-4075-ABDA-3EFF35CAC4B7
Hardware Model:      iPhone13,3
Process:         Lanxin [18893]
Path:            /private/var/containers/Bundle/Application/BB6C2DF8-A5A0-449F-8A33-419281422211/Lanxin.app/Lanxin
Identifier:      com.comisys.lanxinPlus
Version:         8.3.3 (3555)
Code Type:       ARM-64
Parent Process:   [1]

Date/Time:       2022-06-16 03:52:04 +0000
OS Version:      iPhone OS 15.3.1 (19D52)
Report Version:  104

Exception Type:  SIGABRT
Exception Codes: #0 at 0x1b7f0f964
Crashed Thread:  22


Thread 22 Crashed:
0   libsystem_kernel.dylib              0x00000001b7f0f964 __pthread_kill + 8
1   libsystem_c.dylib                   0x000000018b718f50 abort + 164
2   libc++abi.dylib                     0x00000001991a5bc4 <redacted> + 0
3   libc++abi.dylib                     0x0000000199196fc0 <redacted> + 308
4   libobjc.A.dylib                     0x00000001990a3e44 <redacted> + 160
5   libc++abi.dylib                     0x00000001991a4f58 <redacted> + 20
6   libc++abi.dylib                     0x00000001991a7efc __cxa_rethrow + 148
7   libobjc.A.dylib                     0x000000019909fcac objc_exception_rethrow + 44
8   CoreFoundation                      0x00000001807d3554 CFRunLoopRunSpecific + 836
9   Flutter                             0x00000001138f7f88 0x1135ec000 + 3194760
10  Flutter                             0x00000001138f796c 0x1135ec000 + 3193196
11  libsystem_pthread.dylib             0x00000001f1bc79a4 _pthread_start + 148
12  libsystem_pthread.dylib             0x00000001f1bc6ea0 thread_start + 8
···
flutter doctor -v
···
[✓] Flutter (Channel stable, 3.0.0, on macOS 12.3.1 21E258 darwin-x64, locale
    zh-Hans-CN)
    • Flutter version 3.0.0 at /Users/mahao/flutter
    • Upstream repository https://gitee.com/mirrors/Flutter.git
    • Framework revision ee4e09cce0 (5 周前), 2022-05-09 16:45:18 -0700
    • Engine revision d1b9a6938a
    • Dart version 2.17.0
    • DevTools version 2.12.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/mahao/Library/Android/sdk
    • Platform android-31, build-tools 30.0.3
    • ANDROID_HOME = /Users/mahao/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/XCode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] Connected device (3 available)
    • Mahao test (mobile) • 518fff1769e8d6cc3b01b0d795ef9bf12d950cb4 • ios
      • iOS 15.4.1 19E258
    • macOS (desktop)     • macos                                    •
      darwin-x64     • macOS 12.3.1 21E258 darwin-x64
    • Chrome (web)        • chrome                                   •
      web-javascript • Google Chrome 96.0.4664.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
···

**Comment by exaby73** [comment]
@flutter-symbolizer-bot flutter#v3.0.0 release arm64 https://github.com/flutter/flutter/issues/106188#issuecomment-1158758833
