### ISSUE TITLE
When using flutter_tree controls, I need When clicking on the title, select the title and hide the selection box. What should I do

### ISSUE THREAD

**Issue by 132056135** [flutter/flutter#106174]
![1655450324846](https://user-images.githubusercontent.com/89127976/174250976-f1accc92-ebec-41e4-948d-dd8f069bda62.png)
TreeView(
          data: treeData,
          lazy: false,
          //load: _load,
          showActions: false,
          showCheckBox: false,
          showFilter: false,
          append: (parent) {
            print(parent.extra);
            return TreeNodeData(
              title: 'Appended',
              expaned: true,
              checked: true,
              children: [],
            );
          },
          onLoad: (node) {
            print('onLoad');
            print(node);
          },
          onAppend: (node, parent) {
            print('onAppend');
            print(node);
          },
          onCheck: (checked, node) {
            print('checked');
            print('onCheck');
            print(node.extra);
          },
          onCollapse: (node) {
            print('onCollapse');
            print(node);
          },
          onExpand: (node) {
            print('onExpand');
            print(node);
          },
          onRemove: (node, parent) {
            print('onRemove');
            print(node);
          },
          onTap: (node) {
            print('onTap');
            print(node);
          },
        ),
![1655450324846](https://user-images.githubusercontent.com/89127976/174250976-f1accc92-ebec-41e4-948d-dd8f069bda62.png)

**Comment by danagbemava-nc** [comment]
Hi @132056135, `flutter_tree` is a third-party package. Any issues related to said package should be reported on their repo. 

Closing this as this issue is not related to the flutter repo. 

Thank you
