### ISSUE TITLE
Flutter web app initial load time takes about 3 minutes. 

### ISSUE THREAD

**Issue by zamargab** [flutter/flutter#106109]
I have a problem with a website I created with Flutter web, it worked fine when I was building and testing on Chrome but after uploading to the internet, for the first time I try to open it up, it takes takes about 3 minutes to load and then subsequent visits takes about 8 secs, I don't  have an issue with the 8 secs delay, its the 3 minutes initial load that bothers me.

**Comment by zamargab** [comment]
[✓] Flutter (Channel stable, 2.10.4, on macOS 12.4 21F79 darwin-x64, locale en-GB)
    • Flutter version 2.10.4 at /Users/user/FlutterSDK/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (3 months ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[!] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/user/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.68.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.42.0

[✓] Connected device (2 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 102.0.5005.115

[✓] HTTP Host Availability
    • All required HTTP hosts are available

**Comment by zamargab** [comment]
https://drive.google.com/file/d/1RlB8unaBp1OUGzdYui0SHYsnws_WlAEM/view?usp=sharing

link to timeline traces

**Comment by exaby73** [comment]
Hi @zamargab. Can you please upgrade to the latest release `3.0` and confirm if you are still experiencing this issue?
