### ISSUE TITLE
Taking Pictures Every 200 ms (10 pictures in 2 seconds) on iOS

### ISSUE THREAD

**Issue by Jayvd** [flutter/flutter#106193]
I tried using the Camera Plugin to perform Burst mode. But it seems quite impossible to take pictures every 0.2 seconds. Because it takes almost 1 second for 1 picture

Could anyone please guide on how to efficiently take multiple photos in the shortest time possible?

**Comment by darshankawar** [comment]
@Jayvd 
Thanks for the report. Can you provide `flutter doctor -v`, camera plugin version ?
Also check [this](https://github.com/flutter/flutter/issues/73250) issue and the properties added as part of its fix and see if it helps in your case.
