### ISSUE TITLE
Mac host engine failing on recipes-with-led

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#106128]
I suspect this is an infra issue.

On the CL: https://flutter-review.googlesource.com/c/recipes/+/31281
Recipes with led run: https://ci.chromium.org/ui/p/flutter/builders/try/recipes-with-led/b8811240244551560209/overview
Mac host engine build: https://luci-milo.appspot.com/raw/build/logs.chromium.org/flutter/led/flutter-try-builder_chops-service-accounts.iam.gserviceaccount.com/d77824f4dea92300f98fdc8b87c914eb368aa12f095ce34f58e5a96179be6c70/+/build.proto?server=chromium-swarm.appspot.com

I am seeing the error:

```
/opt/s/w/ir/cipd_bin_packages/python: could not resolve options: failed to resolve Python script: stat /opt/s/w/ir/cache/builder/src/flutter/tools/gn: no such file or directory
```

Which I believe is unrelated to my change.

**Comment by drewroengoogle** [comment]
I believe this is a similar issue as #105476
