### ISSUE TITLE
PR stuck on ci.yaml validation

### ISSUE THREAD

**Issue by flar** [flutter/flutter#106181]
https://github.com/flutter/engine/pull/34024 has been stuck waiting on the ci.yaml validation step for several hours.

**Comment by drewroengoogle** [comment]
Hello! I've restarted the build, so we'll see if that resolves the issue

**Comment by drewroengoogle** [comment]
The try builds have passed! Closing this.

We have a bug for resolving the root issue of ci.yaml validation getting stuck here: https://github.com/flutter/flutter/issues/106203
