### ISSUE TITLE
Update test_api to 0.4.10

### ISSUE THREAD

**Issue by brianquinlan** [flutter/flutter#106143]
## Use case

Flutter currently pins `test_api: 0.4.9`

`package:test` version `1.21.2` pins `test_api: 0.4.10`

And `package:http_client_conformance_tests` requires `test: ^1.21.2`

So `package:http_client_conformance_tests` 

## Proposal

Update the pinned `test_api: 0.4.10`

**Comment by danagbemava-nc** [comment]
This is currently blocked due to https://github.com/flutter/flutter/issues/106158.

**Comment by brianquinlan** [comment]
I have a PR to fix this here: https://github.com/flutter/flutter/pull/106148

https://github.com/flutter/flutter/issues/106158 is fixed by https://github.com/flutter/packages/pull/2249 is someone would like to do a code review.

**Comment by brianquinlan** [comment]
Fixed in https://github.com/flutter/flutter/pull/107185
