### ISSUE TITLE
[VERBOSE-2:ui_dart_state.cc(198)] Unhandled Exception: PlatformException(multiple_request, Cancelled by a second request, null, null)

### ISSUE THREAD

**Issue by s2yed** [flutter/flutter#106103]
final ImagePicker _picker = ImagePicker();
    final XFile? image = await _picker.pickImage(source: ImageSource.gallery,
        imageQuality: 100
    );

[VERBOSE-2:ui_dart_state.cc(198)] Unhandled Exception: PlatformException(multiple_request, Cancelled by a second request, null, null)
#0      ImagePickerApi.pickImage (package:image_picker_ios/src/messages.g.dart:133:7)
<asynchronous suspension>
#1      ImagePickerIOS.getImage (package:image_picker_ios/image_picker_ios.dart:168:26)
<asynchronous suspension>
#2      _WidgetEcommerceImgItemState.imageGallery (package:ezee_click_report/screen/ecommerce/widget/eccom/wd_dialog_image_ecomm_items.dart:500:26)

**Comment by s2yed** [comment]
[✓] Flutter (Channel stable, 3.0.1, on macOS 12.2 21D49 darwin-arm (Rosetta), locale en-EG)
    • Flutter version 3.0.1 at /Users/tebalink/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (4 weeks ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/tebalink/Library/Android/sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] Connected device (2 available)
    • iPhone 11 Pro (mobile) • 6B213EEA-4794-4EF4-A07A-122E03C7F736 • ios          • com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64 • macOS 12.2 21D49 darwin-arm (Rosetta)

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
Process finished with exit code 0

**Comment by maheshmnj** [comment]
Hi @s2yed,

There is a similar issue describing this case https://github.com/flutter/flutter/issues/82602, Please follow up there for further updates, Closing this issue as a duplicate. If you disagree feel free to write in the comments and we will reopen it.

Thank you.
