### ISSUE TITLE
How to use flutter driver in add-to-app.

### ISSUE THREAD

**Issue by Super-Crab** [flutter/flutter#106165]
As the question mentioned in the title, I have an app that **uses add-to-app**, the native code and the dart code are separated, and now I want to perform the driver test, but I don't know how to perform the performance test. **I want to get the performance data of the first rendering through driver test for use sksl warmup** 。
I want to get the following data ,but **flutter drive --target=XXX --profile** is not available for me.

ex:  {average_frame_build_time_millis: 1.2139090909090908, 90th_percentile_frame_build_time_millis: 1.847, 99th_percentile_frame_build_time_millis: 2.348, worst_frame_build_time_millis: 2.348, missed_frame_build_budget_count: 0, average_frame_rasterizer_time_millis: 8.13509090909091, 90th_percentile_frame_rasterizer_time_millis: 19.456, 99th_percentile_frame_rasterizer_time_millis: 31.914, worst_frame_rasterizer_time_millis: 31.914, missed_frame_rasterizer_budget_count: 2, frame_count: 11, frame_rasterizer_count: 11, frame_build_times: [2348, 1109, 574, 545, 680, 1599, 1250, 1847, 1081, 1078, 1242], frame_rasterizer_times: [3635, 31914, 12595, 1118, 19456, 3524, 4655, 2302, 2932, 3398, 3957], frame_begin_times: [0, 20320, 40483, 59851, 79985, 100183, 120154, 140608, 160738, 181010, 201040], frame_rasterizer_begin_times: [0, 19364, 51335, 63970, 78578, 99687, 119190, 140364, 159680, 179967, 200346], average_vsync_transitions_missed: 1.0, 90th_percentile_vsync_transitions_missed: 1.0, 99th_percentile_vsync_transitions_missed: 1.0}

**Comment by huycozy** [comment]
@Super-Crab 

- `integration_test` package is now preferred over `flutter_driver`. See [this](https://docs.flutter.dev/testing/integration-tests/migration) for reference and [this](https://docs.flutter.dev/cookbook/testing/integration/introduction) as a guideline.

- With `method channel`, you can find these StackOverflow topics for more details:
https://stackoverflow.com/questions/63353885/how-to-test-method-channel-that-call-from-native-to-flutter
https://stackoverflow.com/questions/52028969/testing-flutter-code-that-uses-a-plugin-and-platform-channel

- Also, check these duplicated issues #63465, #34345, #36259

So, I close this issue as a duplicate, please follow up on above issues for further updates.

**Comment by huycozy** [comment]
@Super-Crab 

> I want to get the following data ,but flutter drive --target=XXX --profile is not available for me.

Could you describe what did you try? Why is it not available?

Also, there is a guideline here that introduces [Performance profiling] that may help you.

For `add-to-app` testing, find there opening issues for further updates: 
https://github.com/flutter/flutter/issues/63465, 
https://github.com/flutter/flutter/issues/34345, 
https://github.com/flutter/flutter/issues/36259

**Comment by Super-Crab** [comment]
@huycozy flutter drive --target=XXX --profile need build android apk,but in my programs,the native code and the dart code are separated

**Comment by Super-Crab** [comment]
@huycozy i have some other questions about  [shader compilation jank](https://docs.flutter.dev/perf/shader)，Does this only work for animations?

**Comment by huycozy** [comment]
@Super-Crab 
I found some answers that you can try:

- https://github.com/flutter/flutter/issues/67192#issuecomment-710700465
- https://docs.flutter.dev/perf/shader#how-to-use-sksl-warmup
    ```
    flutter drive --profile --cache-sksl --write-sksl-on-exit flutter_01.sksl.json -t test_driver/app.dart
    ```

Also, I see there are some open issues addressing the case you described #81919, #88874
Please read them and confirm that those are the similar issues you are looking for?
