### ISSUE TITLE
iOS Release Build Crashes Upon Startup - Error while initializing the Dart VM: Flag dedup_instructions is false in snapshot, but dedup_instructions is always true in product mode

### ISSUE THREAD

**Issue by Aaron-Cohen** [flutter/flutter#106112]
I am not totally sure how to reproduce this issue as I do not know what causes this issue. I currently have an app that is working in debug mode and profile mode, but I am unable to build it for release mode. I am installing it directly via cable to a physical iPhone (not an emulator) that is running iOS 14.8. I do not own an Android device, so I am unsure if this issue happens for Android builds too.

My flutter doctor output:
[doctor-out.txt](https://github.com/flutter/flutter/files/8919446/doctor-out.txt)

After removing the iOS Pods folder, the podfile.lock, running `flutter clean` and trying a fresh rebuild, this is my output for `flutter run --release --verbose`
[release-log.txt](https://github.com/flutter/flutter/files/8919455/release-log.txt)

If you navigate to the end, you can see that it successfully deploys to my device. What is not reflected in the logs is that upon launching there is a brief white screen and the app crashes. At this point, I hit 'q' to end the terminal session and 'Application finished' Is logged. No errors or exceptions are logged when the app crashes, which makes me clueless on how to pinpoint the issue. Just to reiterate, the app can be installed and used without issue in debug mode and profile mode. It is only in release mode where this happens.

I wish I could provide more information, but I do not know where to begin fixing this.

**Comment by Aaron-Cohen** [comment]
I created a new flutter project that has the default code of the button counter. The same behavior is present there- I can load the debug and profile versions to my device, but when I try to do the same for release mode, it builds successfully and then crashes without outputting any error.

**Comment by Aaron-Cohen** [comment]
I noticed this in Xcode which I hadn't noticed before.

```
2022-06-16 15:32:44.889467-0500 Runner[68916:5583414] Metal API Validation Enabled
2022-06-16 15:32:45.053915-0500 Runner[68916:5583414] [VERBOSE-3:dart_vm_initializer.cc(22)] Error while initializing the Dart VM: Flag dedup_instructions is false in snapshot, but dedup_instructions is always true in product mode
```

Running a profile or debug build in Xcode works without this error. Perhaps this is the root cause in release mode. Still seeking answers on how to resolve this.

**Comment by huycozy** [comment]
@Aaron-Cohen 
I'm not sure I can reproduce this issue with just one clue from your log in https://github.com/flutter/flutter/issues/106112#issuecomment-1158113476 and you also confirmed that you got the same error with `a new flutter project that has the default code of the button counter.`

I will leave this issue open for further investigation from the team.

And I repost your flutter doctor output here for better readability. 

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 3.0.2, on macOS 11.4 20F71 darwin-x64, locale en-US)
    • Flutter version 3.0.2 at /Users/aaron/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cd41fdd495 (8 days ago), 2022-06-08 09:52:13 -0700
    • Engine revision f15f824b57
    • Dart version 2.17.3
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/aaron/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Library/Java/JavaVirtualMachines/jdk-18.0.1.1.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 18.0.1.1+2-6)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Users/aaron/Downloads/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] Connected device (3 available)
    • אהרן iPhone (mobile) • 00008020-001A74AA01F9002E            • ios        • iOS 14.8 18H17
    • iPhone 13 (mobile)   • DBEAE20E-D3D1-43B5-BC15-CC8D20753EEB • ios        • com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • macOS (desktop)      • macos                                • darwin-x64 • macOS 11.4 20F71 darwin-x64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.

```
</details>

**Comment by huycozy** [comment]
@Aaron-Cohen 
I'm not sure I can reproduce this issue with just one clue from your log in https://github.com/flutter/flutter/issues/106112#issuecomment-1158113476 and you also confirmed that you got the same error with `a new flutter project that has the default code of the button counter.`

The issue #90422 may be related but they may not similar. So I will leave this issue open for further investigation from the team.

And I repost your flutter doctor output here for better readability. 

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 3.0.2, on macOS 11.4 20F71 darwin-x64, locale en-US)
    • Flutter version 3.0.2 at /Users/aaron/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cd41fdd495 (8 days ago), 2022-06-08 09:52:13 -0700
    • Engine revision f15f824b57
    • Dart version 2.17.3
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/aaron/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Library/Java/JavaVirtualMachines/jdk-18.0.1.1.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 18.0.1.1+2-6)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Users/aaron/Downloads/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] Connected device (3 available)
    • אהרן iPhone (mobile) • 00008020-001A74AA01F9002E            • ios        • iOS 14.8 18H17
    • iPhone 13 (mobile)   • DBEAE20E-D3D1-43B5-BC15-CC8D20753EEB • ios        • com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • macOS (desktop)      • macos                                • darwin-x64 • macOS 11.4 20F71 darwin-x64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.

```
</details>

**Comment by cyanglaz** [comment]
@jmagman Do you know anything about this? I couldn't find anything related to `Flag dedup_instructions is false in snapshot, but dedup_instructions is always true in product mode` anywhere.

**Comment by jmagman** [comment]
When you reproduce this are you sure there are no crash logs in **Xcode > Window > Devices and Simulators > View Device Logs**?  The timestamp should match the crash you're seeing.
<img width="1242" alt="Screen Shot 2022-07-14 at 2 19 04 PM" src="https://user-images.githubusercontent.com/682784/179088012-5e02eb56-db5d-440d-9a23-a6b9ca0cdf87.png">

If you don't see it there, could you try reproducing the crash from Xcode while attached to the debugger?  You'll have to change the scheme build configuration to release mode. Open `ios/Runner.xcworkspace` then **Product > Scheme > Edit Scheme**.  Under **Run** switch the **Build Configuration** to "Release".
<img width="979" alt="Screen Shot 2022-07-14 at 2 21 29 PM" src="https://user-images.githubusercontent.com/682784/179088282-867fdd2b-0d1e-4212-b59b-b908be742663.png">

Then choose your physical device 
<img width="740" alt="Screen Shot 2022-07-14 at 2 22 57 PM" src="https://user-images.githubusercontent.com/682784/179088481-35460059-e55e-413a-8213-c1ae4d857866.png">
and **Product > Run**.

Reproduce the crash and copy the stack of where it crashes and anything else interesting that happens, like console logs.

Thanks for your help tracking this down!

**Comment by stuartmorgan** [comment]
Is this still an issue? If so, could you provide the crash logs requested above?
