### ISSUE TITLE
TimePicker/DatePicker localization

### ISSUE THREAD

**Issue by Tobiaswk** [flutter/flutter#10616]
The `showDatePicker()` and `showTimePicker()` should allow localization. Right now it is not possible to specify labels for the "cancel" and "ok" buttons. Either it should be possible to specify labels for these buttons or localization should be done automatically. I prefer the latter.

**Comment by Hixie** [comment]
Why do you prefer the former?

Also, it needs a lot more localisation than that. For example, it needs to handle 12h/24h clocks, and Norwegian 00/24 styles, etc.

**Comment by Tobiaswk** [comment]
Sorry. I actually meant the latter. Edited my comment.
I've always renamed this issue to also cover the `showTimePicker` and `showDatePicker`.

**Comment by Hixie** [comment]
When we localize DatePicker, we should make sure that as a side-effect all the `intl` dependencies end up indirected through MaterialLocalizations, to enable https://github.com/flutter/flutter/issues/12050.

**Comment by yjbanov** [comment]
Update: time picker i18n is done. I filed https://github.com/flutter/flutter/issues/12185 specifically for the date picker.
