### ISSUE TITLE
[path_provider_linux] example folder got download as a dependency

### ISSUE THREAD

**Issue by guyluz11** [flutter/flutter#106292]
I have found that the example folder of `path_provider_linux` got downloaded as well into my app dependencies.

I think that it shouldn't happen as it is redundant code.

![image](https://user-images.githubusercontent.com/9304740/174579604-d8b07bc1-4bc2-4746-abfc-7f4180fe5911.png)

**Comment by stuartmorgan** [comment]
This is how `pub` works; of you'd like it to remove example code from what is downloaded, you'd need to file [a pub feature request](https://github.com/dart-lang/pub-dev/issues).
