### ISSUE TITLE
MaterialIcons library does not respect the Flutter version or is broken

### ISSUE THREAD

**Issue by pavel604** [flutter/flutter#106217]
In our dev team and in our CI/CD pipeline, we've locked our Flutter version, and all dependency versions are also locked for security and predictability reasons. In our project we've used Material Icons library to display icons in our views, in particular:

Icons.balance ([IconData](https://api.flutter.dev/flutter/widgets/IconData/IconData.html)(0xf04c6, fontFamily: 'MaterialIcons')),
Icons.edit_note ([IconData](https://api.flutter.dev/flutter/widgets/IconData/IconData.html)(0xf04f6, fontFamily: 'MaterialIcons'))

The problem we are having is that the above mentioned icons work fine locally, but when we install _**the same**_ Flutter version in our pipeline and run a pipeline build, the icon data fails to resolve and our xCode build fails with the following message:

```
    Codepoint 984262 not found in font, aborting.
    Failed to package /Users/runner/work/1/s/src.
    Command PhaseScriptExecution failed with a nonzero exit code
```
This tell me that the Material Icon library installed in the pipeline is somehow different than the one we use locally.

## Steps to Reproduce

1.  Use the above mentioned icons in your app
2. Run CICD pipeline build with Flutter V2.10.1

**Expected results:** Build completes, producing .ipa artefact

**Actual results:** Build fails with the error message as above

**Comment by darshankawar** [comment]
@pavel604 
Thanks for the report. Can you provide complete verbose log that shows the detailed error ?
