### ISSUE TITLE
[webview_flutter] Android 33 Build Issue

### ISSUE THREAD

**Issue by parmarravi** [flutter/flutter#106257]
webview_flutter: ^3.0.4 is failing to build for android SDK Targeting 33 

Gradle

>
>     compileSdkVersion 33
> 
>     compileOptions {
>         sourceCompatibility JavaVersion.VERSION_1_8
>         targetCompatibility JavaVersion.VERSION_1_8
>     }
> 
>     defaultConfig {
>         applicationId "com.company.sample"
>         minSdkVersion 21
>         targetSdkVersion 33
>         versionCode flutterVersionCode.toInteger()
>         versionName flutterVersionName
>     }
> 

>
>Task :flutter_inappwebview:compileDebugJavaWithJavac FAILED 
> /.pub-cache/hosted/pub.dartlang.org/flutter_inappwebview-5.4.3+7/android/src/main/java/com/pichillilorenzo/flutter_inappwebview/in_app_webview/InAppWebView.java:280: 
> error: cannot find symbol
>       settings.setAppCachePath(options.appCachePath);
>               ^
>   symbol:   method setAppCachePath(String)
>   location: variable settings of type WebSettings

**Comment by stuartmorgan** [comment]
That error is coming from `flutter_inappwebview`, not `webview_flutter`. Errors in third-party packages need to be reported to their developers.
