### ISSUE TITLE
autosubmit bot not working in flutter/plugins

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#106209]
It successfully landed at least one PR earlier in the week, but it doesn't seem to be working at all now.

There are currently [two PRs that have had the label for several days](https://github.com/flutter/plugins/pulls?q=is%3Apr+is%3Aopen+label%3Aautosubmit), but the tree is green and nothing is happening. The last PR that landed (which I did manually because the bot wasn't working) landed 14 hours ago, so it's not a throttling issue; the tree is completely idle.

**Comment by stuartmorgan** [comment]
Looking back at the PRs it landed, it looks like they are before I switched to skipping `stable` tests in presubmit. Maybe the bot doesn't like tests that are in the `skip` state so it thinks they aren't ready to land?

**Comment by keyonghan** [comment]
> Looking back at the PRs it landed, it looks like they are before I switched to skipping stable tests in presubmit. Maybe the bot doesn't like tests that are in the skip state so it thinks they aren't ready to land?

You are right. We saw exception in the backend.
```
Exception: This level of check run conclusion is unimplemented: skipped.
```

This is due to upstream github packages is not supporting [`"conclusion": "skipped",`](https://github.com/SpinlockLabs/github.dart/blob/master/lib/src/common/model/checks.dart#L57) yet.
We should send an upstream support and also update our logic to handle this case.

**Comment by ditman** [comment]
This is also happening with the `waiting for tree to go green` bot, for example:

* https://github.com/flutter/plugins/pull/5988

**Comment by ricardoamador** [comment]
Ah okay. I already started.

**Comment by ricardoamador** [comment]
Can someone provide some context as to how the tests are being marked skipped? The link to the original PRs in description are not showing. Thank you.

**Comment by stuartmorgan** [comment]
They are skipped using the Cirrus `skip:` directive, which allows us to skip tests by default but a) see that they aren't run in presubmit as a reminder, and b) run them on demand.

**Comment by ricardoamador** [comment]
Perfect. Thanks @stuartmorgan

**Comment by ricardoamador** [comment]
I have found the issue and working on getting the change tested. Should be done by eod today or very early tomorrow at the latest.

**Comment by ditman** [comment]
I just saw it working today! Thank you very much!!
