### ISSUE TITLE
 when run test driver on android simulator  , can not access internet connection 

### ISSUE THREAD

**Issue by AhkamKhalaaf** [flutter/flutter#106290]
i used test driver to automate location permission  with android  simulator 
, but when i run test driver , application can not access   internet connection, 
، 
this is the error after run 
VMServiceFlutterDriver: Flutter Driver extension is taking a long time to become available. Ensure your test app (often "lib/main.dart") imports "package:flutter_driver/driver_extension.dart" and calls enableFlutterDriverExtension() as the first call in main().

and there is a  warning 
 Warning: At least one test in this suite creates an HttpClient. When
I/flutter ( 5447): running a test suite that uses TestWidgetsFlutterBinding, all HTTP
I/flutter ( 5447): requests will return status code 400, and no network request will
I/flutter ( 5447): actually be made. Any test expecting a real network connection and
I/flutter ( 5447): status code will fail.
I/flutter ( 5447): To test code that needs an HttpClient, provide your own HttpClient
I/flutter ( 5447): implementation to the code under test, so that your test can
I/flutter ( 5447): consistently provide a testable response to the code under test.

this is my test driver code 
flutter drive \
  --driver=test_driver/main_test.dart \
  --target=integration_test/unify_test.dart \
  -d emulator-5554

@darshankawar

**Comment by exaby73** [comment]
Hi @AhkamKhalaaf, please provide a [minimal, reproducible example][1] and the output of `flutter doctor -v`.

[1]: https://stackoverflow.com/help/minimal-reproducible-example

**Comment by exaby73** [comment]
Can you provide the code samples you are using? Check [this link](https://stackoverflow.com/help/minimal-reproducible-example) on how to provide a reproducible sample so that we can investigate
