### ISSUE TITLE
Why you are use Tencecnt TBS SDK?

### ISSUE THREAD

**Issue by ABmamunHoneybee** [flutter/flutter#106238]
As your google play store team reject my apps several times for TBS SDK.
I research it and, I got you ar using this package "com.tencent.smtt.export.external.DexClassLoaderProviderService". For this i' rejected.

Please help me. It's urgeent to go live.

**Comment by darshankawar** [comment]
@ABmamunHoneybee 
Your issue isn't clear when you point to the package. It could be a part of an error in which the log points to the package you are referring. We would need complete verbose error log to properly analyze the issue.

Closing for now, as the issue doesn't have any details as requested in new issue template. Please use the template and provide requested details in it.
