### ISSUE TITLE
[local_auth] USE_FINGERPRINT android permission is deprecated

### ISSUE THREAD

**Issue by labaxter** [flutter/flutter#106298]
The application will compile and run with the `USE_FINGERPRINT` permission (it's crossed out in Android Studio.)  This has been replaced with `USE_BIOMETRIC`.

The android section of the Readme should state that if one is using flutter ^3.0, the line to insert in AndroidManifest.kt is:

```
     <uses-permission android:name="android.permission.USE_BIOMETRIC"/>
```
Flutter Doctor -v output:
```

[✓] Flutter (Channel stable, 3.0.2, on Debian GNU/Linux 11 (bullseye)
    5.10.0-11-amd64, locale en_US.UTF-8)
    • Flutter version 3.0.2 at /home/lab/devel/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cd41fdd495 (12 days ago), 2022-06-08 09:52:13 -0700
    • Engine revision f15f824b57
    • Dart version 2.17.3
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /home/lab/Android/Sdk
    • Platform android-32, build-tools 32.0.0
    • Java binary at: /home/lab/devel/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Debian clang version 11.0.1-2
    • cmake version 3.18.4
    • ninja version 1.10.1
    • pkg-config version 0.29.2

[✓] Android Studio (version 2021.2)
    • Android Studio at /home/lab/devel/android-studio
    • Flutter plugin version 67.1.2
    • Dart plugin version 212.5744
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.67.1)
    • VS Code at /usr/share/code
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    •
      Android 11 (API 30) (emulator)
    • Linux (desktop)                    • linux         • linux-x64      •
      Debian GNU/Linux 11 (bullseye) 5.10.0-11-amd64
    • Chrome (web)                       • chrome        • web-javascript •
      Google Chrome 101.0.4951.64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!


```

**Comment by huycozy** [comment]
@labaxter, thanks for filing the issue. 

Provide additional information:

- https://developer.android.com/reference/android/Manifest.permission#USE_FINGERPRINT
- https://github.com/flutter/plugins/blob/main/packages/local_auth/local_auth/README.md#permissions

Solving this issue may help to solve the issue #78137 as the comment https://github.com/flutter/flutter/issues/78137#issuecomment-970387592

**Comment by stuartmorgan** [comment]
> The android section of the Readme should state that if one is using flutter ^3.0, the line to insert in AndroidManifest.kt is

Android deprecations are unrelated to Flutter versions. But either way, this is incorrect; the plugin still has a codepath that uses `FingerprintManager` so needs this permission for now. This isn't a documentation issue, but something that requires code changes in the plugin.

**Comment by labaxter** [comment]
Fair enough. I realized after I submitted this that this is related to the android version not the flutter version.  That said, I'm using android version 29, and `USES_FINGERPRINT` is deprecated on this version.  The application works with `USES_BIOMETRIC`  So the documentation should make that clear, which would have avoided this issue submission. Perhaps identifying the version at which `USES_FINGERPRINT` is deprecated and replaced with `USES_BIOMETRIC`.  Perhaps it is and I missed it.

**Comment by stuartmorgan** [comment]
> I'm using android version 29 [...]The application works with `USES_BIOMETRIC`

When *running* on API level 29 it works, yes.

> So the documentation should make that clear, which would have avoided this issue submission. Perhaps identifying the version at which `USES_FINGERPRINT` is deprecated and replaced with `USES_BIOMETRIC`.

The small benefit of doing so--eliminating a harmless warning for the subset of developers only supporting 28+--is far outweighed by the likely harm--people misunderstanding the docs telling apps that work in their testing on a recent device, but fail at runtime for anyone running older versions of Android.

We will update the docs when the plugin is updated to no longer use the legacy codepath that makes it required on older devices.

**Comment by stuartmorgan** [comment]
This is mostly fixed by https://github.com/flutter/plugins/pull/6059, but we still need to do an update to the app-facing package to update the README.
