### ISSUE TITLE
Provide feedback when hot reload fails (eg. due to main method change)

### ISSUE THREAD

**Issue by DanTup** [flutter/flutter#10620]
I'm wiring up "hot reload" in Dart Code. I was caught out while testing it because I didn't realise changes to the `main` method didn't work ([this is documented](https://flutter.io/faq/#hot-reload)). The output from flutter was still `1 of x libraries reloaded` so it's not obvious to the user (if they didn't read the docs - which I didn't ;-)) why things didn't update.

I'm guessing that Flutter can tell when a change like this has been made that will result in hot reload not working, so I think there are two improvements that could be made:

1. Output to the user that hot reload didn't not work correctly because of (`main` method change/etc.)

2. For `flutter run --machine` provide this feedback via the JSON API so that an IDE can initiate a full restart

I'd really like to make hot reload the default behaviour when clicking the `Restart` button on the debugger toolbar, but I'm not comfortable doing it without feedback to the user when it fails (otherwise it just looks kinda buggy). I can move it to another command/toolbar button (but sadly not one on the debugger toolbar) but the experience would not be as good.

**Comment by DanTup** [comment]
Possibly this is just a dupe of #10486?

**Comment by mit-mit** [comment]
cc @a-siva

**Comment by a-siva** [comment]
marking as a dupicate of #12300
