### ISSUE TITLE
`setup` step in `flutter/tests`

### ISSUE THREAD

**Issue by spydon** [flutter/flutter#106259]
# Feature request `flutter/tests`

## What is the problem?

If there are any preparation steps needed before the `test` steps they can't be done in `fetch`, since `fetch` runs from outside of the `tests` directory. This could be for example `melos bootstrap` (initialized a monorepo).

## Suggested solution

Add a `setup` step after `fetch`, but before `test`, which runs from within the `tests` directory.

## Example

In this example `dart pub global activate melos` could be run from the `fetch` step, but not `melos bootstrap`.

```yaml
fetch=git clone https://github.com/flame-engine/flame.git tests
fetch=git -C tests checkout 1dc313f3016c21f188375b134dd65346c0373856
update=.
setup=dart pub global activate melos
setup=melos bootstrap 
test=melos test
```

**Comment by spydon** [comment]
CC: @Hixie

**Comment by Hixie** [comment]
If the steps are expensive (take more than a second) then we probably wouldn't want to add those tests because we have to run many of these. If they are not expensive (and ideally if they are idempotent) then it should work to just put them as another `test=` line.

**Comment by spydon** [comment]
I'm not sure how it is currently handled with `pub get`, but I assume that the dependencies are cached between test runs? This would be the same thing, it would run setup once and then it can run the test steps many times.

**Comment by Hixie** [comment]
`pub get` is idempotent, so we can run it every time (well `flutter test` does it, but same idea). It's not so much "cached" as the tests are just run back to back multiple times on the same VM. So so long as the setup is idempotent, it's fine to call it many times.

That said if the script is downloading resources beyond `pub` and GitHub then we probably wouldn't want to run those tests via this system anyway, because we want to minimize our third-party dependencies for reliability reasons (if pub or github are down everything is broken anyway so they don't matter so much).

**Comment by spydon** [comment]
> `pub get` is idempotent, so we can run it every time (well `flutter test` does it, but same idea). It's not so much "cached" as the tests are just run back to back multiple times on the same VM. So so long as the setup is idempotent, it's fine to call it many times.

`pub get` is only fully idempotent if the versions are pinned in the pubspec, which several of the repos in the registery doesn't have. But that isn't relevant to this issue. 

> That said if the script is downloading resources beyond `pub` and GitHub then we probably wouldn't want to run those tests via this system anyway, because we want to minimize our third-party dependencies for reliability reasons (if pub or github are down everything is broken anyway so they don't matter so much).

It just feels strange to do setup in the `test` step (especially here when it would only need to be run once), but we can go with that too, since `melos bootstrap` should be as idempotent as `pub get` is.
