### ISSUE TITLE
Flutter DropdownButton fails to render long lists

### ISSUE THREAD

**Issue by pouyarahmti** [flutter/flutter#106245]
I am trying to create a date selection widget using dropDownButton in Flutter, but it seems that flutter DropDownDownButton cannot render long list items like 30 items and closes immediately. I was wondering if there is any solution to that or not?
the list that I forward to DropDownButton and it fails to render it properly is days list, which has 30 or 31 items but the list cannot renders all of them.

Here I'm forwarding my dropdown items and selected based on the onChanged function. Thanks in advance for your great help.
`
        String? dropdownValue;
      
        @override
        void initState() {
          dropdownValue = widget.initialValue;
          super.initState();
        }
      
        @override
        Widget build(BuildContext context) {
          return Container(
            padding: EdgeInsets.all(1.5.h),
            decoration: BoxDecoration(
              borderRadius: BorderRadius.circular(
                10,
              ),
              color: const Color.fromRGBO(244, 244, 244, 1),
            ),
            child: DropdownButtonHideUnderline(
              child: DropdownButton<String>(
                dropdownColor: Colors.white,
                icon: const Icon(
                  Icons.expand_more,
                  size: 20,
                  color: Colors.black,
                ),
                value: dropdownValue,
                isExpanded: true,
                isDense: false,
                selectedItemBuilder: (BuildContext context) {
                  return widget.items.map<Widget>((String item) {
                    return DropdownMenuItem(
                      value: item,
                      child: Text(
                        item.toPersianDigit(),
                        style: normalTextStyle.copyWith(
                          fontSize: 8.sp,
                          color: Colors.black,
                        ),
                      ),
                    );
                  }).toList();
                },
                items: widget.items.map<DropdownMenuItem<String>>(
                  (String value) {
                    if (value == dropdownValue) {
                      return DropdownMenuItem<String>(
                        value: value,
                        child: Container(
                          padding: const EdgeInsets.all(8),
                          decoration: BoxDecoration(
                            borderRadius: BorderRadius.circular(8),
                            color: Theme.of(context).colorScheme.primary,
                          ),
                          width: double.infinity,
                          child: Text(
                            value.toPersianDigit(),
                            style: normalTextStyle.copyWith(
                              fontSize: 8.sp,
                              color: Colors.white,
                            ),
                          ),
                        ),
                      );
                    } else {
                      return DropdownMenuItem<String>(
                        value: value,
                        child: Text(
                          value.toPersianDigit(),
                          style: normalTextStyle.copyWith(
                            fontSize: 8.sp,
                            color: Colors.black,
                          ),
                        ),
                      );
                    }
                  },
                ).toList(),
                onChanged: (selectedValue) {
                  setState(
                    () {
                      dropdownValue = selectedValue;
                    },
                  );
                  widget.onTap(selectedValue);
                },
              ),
            ),
          );
        }
`

**Comment by superciccio** [comment]
not sure what problem you're facing.

see this code and see the number in bold. is it screen space or what ?

```import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  static const String _title = 'Flutter Code Sample';

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: _title,
      home: Scaffold(
        appBar: AppBar(title: const Text(_title)),
        body: const Center(
          child: MyStatefulWidget(),
        ),
      ),
    );
  }
}

class MyStatefulWidget extends StatefulWidget {
  const MyStatefulWidget({Key? key}) : super(key: key);

  @override
  State<MyStatefulWidget> createState() => _MyStatefulWidgetState();
}

class _MyStatefulWidgetState extends State<MyStatefulWidget> {
  int dropdownValue = 1;

  @override
  Widget build(BuildContext context) {
    return DropdownButton<int>(
      value: dropdownValue,
      icon: const Icon(Icons.arrow_downward),
      elevation: 16,
      style: const TextStyle(color: Colors.deepPurple),
      underline: Container(
        height: 2,
        color: Colors.deepPurpleAccent,
      ),
      onChanged: (int? newValue) {
        setState(() {
          dropdownValue = newValue!;
        });
      },
      items: Iterable<int>.generate(**150**)
          .map<DropdownMenuItem<int>>((int value) {
        return DropdownMenuItem<int>(
          value: value,
          child: Text(value.toString()),
        );
      }).toList(),
    );
  }
}```

**Comment by pouyarahmti** [comment]
My problem is that I can not see all the items when scrolling for long lists, and dropDownButton immediately closes

**Comment by superciccio** [comment]
> @SuperPenguin My problem is that I can not see all the items when scrolling for long lists, and dropDownButton immediately closes. Frame time is 0.13927 ms in the future! Check that graphics HAL is generating vsync timestamps using the correct timebase. this text is also printing in terminal.

Compare your code with mine. You must have something different.. not at home I cannot try yours

**Comment by maheshmnj** [comment]
Hi @pouyarahmti, Your code sample is not complete enough to investigate the actual Cause, Have you tried using `menuMaxHeight`? 
This property was requested here which seems similar to your issue  https://github.com/flutter/flutter/issues/23865 

If you need further help with your code, I would suggest moving the discussion to one of these platforms https://flutter.dev/community#community-grid 

Closing as this is not really a bug nor a feature request.
