### ISSUE TITLE
CMake Error at CMakeLists.txt:19 (apply_standard_settings): Unknown CMake command "apply_standard_settings".

### ISSUE THREAD

**Issue by ctmobiledev** [flutter/flutter#106234]
Greetings, Flutterati. :-)

I just started using Flutter not quite two weeks ago and just LOVE it. Version 3.0.1 is the one I have.

I am also using Realm Database by MongoDB in the project.

When compiling for Windows desktop, I get this error:

`CMake Error at CMakeLists.txt:19 (apply_standard_settings): Unknown CMake command "apply_standard_settings".`

The analyzer flags, in red, the "windows" folder, the "runner" folder under that, and the "CMakeLists.txt" file under that. And the offending line in question in the CMakeLists.txt file is this one, with the red squiggle under it:

`apply_standard_settings(${BINARY_NAME})`

And the Output window shows all of the following:

```
[main] Configuring folder: crud_application_1 
[proc] Executing command: "C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" --no-warn-unused-cli -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -Sc:/Users/charl/Documents/FlutterProjects/Flutter-CRUD1/crud_application_1/windows/runner -Bc:/Users/charl/Documents/FlutterProjects/Flutter-CRUD1/crud_application_1/build -G "Visual Studio 17 2022" -T host=x64 -A x64
[cmake] Not searching for unused variables given on the command line.
[cmake] -- Selecting Windows SDK version 10.0.22621.0 to target Windows 10.0.22000.
[cmake] CMake Error at CMakeLists.txt:19 (apply_standard_settings):
[cmake]   Unknown CMake command "apply_standard_settings".
[cmake] 
[cmake] 
[cmake] -- Configuring incomplete, errors occurred!
[cmake] See also "C:/Users/charl/Documents/FlutterProjects/Flutter-CRUD1/crud_application_1/build/CMakeFiles/CMakeOutput.log".
[visual-studio] Patch Windows SDK bin path from C:\Program Files (x86)\Windows Kits\10\bin\x64 to C:\Program Files (x86)\Windows Kits\10\bin\10.0.22621.0\x64 for C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvarsall.bat

```

Here's what's in the CMakeLists.txt file:

```
cmake_minimum_required(VERSION 3.14)
project(runner LANGUAGES CXX)

# Define the application target. To change its name, change BINARY_NAME in the
# top-level CMakeLists.txt, not the value here, or `flutter run` will no longer
# work.
#
# Any new source files that you add to the application should be added here.
add_executable(${BINARY_NAME} WIN32
  "flutter_window.cpp"
  "main.cpp"
  "utils.cpp"
  "win32_window.cpp"
  "${FLUTTER_MANAGED_DIR}/generated_plugin_registrant.cc"
  "Runner.rc"
  "runner.exe.manifest"
)

apply_standard_settings(${BINARY_NAME})

# Disable Windows macros that collide with C++ standard library functions.
target_compile_definitions(${BINARY_NAME} PRIVATE "NOMINMAX")

# Add dependency libraries and include directories. Add any application-specific
# dependencies here.
target_link_libraries(${BINARY_NAME} PRIVATE flutter flutter_wrapper_app)
target_include_directories(${BINARY_NAME} PRIVATE "${CMAKE_SOURCE_DIR}")

# Run the Flutter tool portions of the build. This must not be removed.
add_dependencies(${BINARY_NAME} flutter_assemble)

```

The interesting thing is, even with this error, the Windows desktop application runs just fine.  

I don't know how the addition of Realm could have seemingly fouled up the compilation process. Is this a known issue with Flutter, Realm and Windows? Whaddya think? 

Thanks!

**Comment by maheshmnj** [comment]
Hi @ctmobiledev, Do you get this error with a newly created flutter project too ?

```
flutter create hello
cd hello
flutter run -d windows
```  

If the issue is only with this application Can you please ensure that your are running the application and not a plugin project as mentioned here https://stackoverflow.com/a/64536462/8253662

**Comment by ctmobiledev** [comment]
Hello, @maheshmnj. No, with the example you gave, there were no issues with CMakeLists.txt. Here's the log:

```
Microsoft Windows [Version 10.0.22000.739]
(c) Microsoft Corporation. All rights reserved.

C:\Users\charl>cd "C:\Users\charl\Documents\FlutterProjects"

C:\Users\charl\Documents\FlutterProjects>flutter create hello

┌─────────────────────────────────────────────────────────┐
│ A new version of Flutter is available!                  │
│                                                         │
│ To update to the latest version, run "flutter upgrade". │
└─────────────────────────────────────────────────────────┘
Creating project hello...
Running "flutter pub get" in hello...                            1,858ms
Wrote 127 files.

All done!
In order to run your application, type:

  $ cd hello
  $ flutter run

Your application code is in hello\lib\main.dart.


C:\Users\charl\Documents\FlutterProjects>cd hello

C:\Users\charl\Documents\FlutterProjects\hello>flutter run -d windows
Launching lib\main.dart on Windows in debug mode...
Building Windows application...
Syncing files to device Windows...                                 149ms

Flutter run key commands.
r Hot reload.
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

 Running with sound null safety

An Observatory debugger and profiler on Windows is available at: http://127.0.0.1:53851/sBaHPEUzKW0=/
The Flutter DevTools debugger and profiler on Windows is available at:
http://127.0.0.1:9100?uri=http://127.0.0.1:53851/sBaHPEUzKW0=/

Application finished.

C:\Users\charl\Documents\FlutterProjects\hello>
```

I only noticed this issue after installing Realm (the MongoDB ORM system that's an alternative to SQLite).  But I do notice, sometimes, getting a prompt from Visual Studio Code saying it couldn't find CMakeLists.txt, and then offers the options to "Create" it, "Locate" it, or to not be cautioned about this issue again. I usually select the last option, to ignore it, and it hasn't stopped me from generating Windows code (see second attachment). 

I've also attached a screen shot of VS Code with the Hello project opened (first attachment).

Finally, to clarify, I am not running a plugin, unless you're referring to Realm, which I'm assuming is not. My installation of Realm database was put into effect with the command:

`flutter pub add realm`

and then generation of any database objects with the command

`flutter pub run realm generate`

The details on Realm installation under Flutter can be found at these URLs:

[https://www.mongodb.com/docs/realm/sdk/flutter/install](https://www.mongodb.com/docs/realm/sdk/flutter/install)
[https://www.mongodb.com/docs/realm/sdk/flutter/quick-start](https://www.mongodb.com/docs/realm/sdk/flutter/quick-start)

Thanks for your assistance.

![No red error condition in Windows tree folder structure Image_20220622_123115](https://user-images.githubusercontent.com/26987447/175101859-7632c9ed-aa4a-4b63-9191-1350d484358a.png)

![CMakeLists option from VSCode Image_20220622_123713](https://user-images.githubusercontent.com/26987447/175101877-b99113cd-ecb3-4a3a-8f4a-3f0a31bec67c.png)

**Comment by stuartmorgan** [comment]
> When compiling for Windows desktop, I get this error:
> 
> `CMake Error at CMakeLists.txt:19 (apply_standard_settings): Unknown CMake command "apply_standard_settings".`

What command exactly are you running when you get that error?

It sounds like an error that would happen if you tried to directly build one of the subcomponent CMake files instead of the root file, which the tooling should never do.

**Comment by maheshmnj** [comment]
Thanks for the info @ctmobiledev, Please provide the info as [requested above](https://github.com/flutter/flutter/issues/106234#issuecomment-1163450922)
