### ISSUE TITLE
[flutter/engine] PlatformViewIOS::attachVIew() is called multiple times during flutter engine startup on iOS

### ISSUE THREAD

**Issue by gordon-ljl** [flutter/flutter#106283]
```
void PlatformViewIOS::attachView() {

  auto flutter_view = static_cast<FlutterView*>(owner_controller_.get().view);
  auto ca_layer = fml::scoped_nsobject<CALayer>{[[flutter_view layer] retain]};
  ios_surface_ = IOSSurface::Create(ios_context_, ca_layer);
  FML_DCHECK(ios_surface_ != nullptr);
 ...
}
 ```

During the startup process of the flutter engine, this function(PlatformViewIOS::attachView()) will be called multiple times, which will result in unnecessary creation and deletion of ios_surface_ (ios_surface_ = IOSSurface::Create(ios_context_, ca_layer))many times.

First time:  shell/platform/darwin/ios/platform_view_ios.mm
 ```
void PlatformViewIOS::SetOwnerViewController(fml::WeakPtr<FlutterViewController> owner_controller) {

  // line 101-103
  if (owner_controller_ && [owner_controller_.get() isViewLoaded]) {
    this->attachView();
  }
  ...
}
```
second time:  /shell/platform/darwin/ios/framework/Source/FlutterEngine.mm
// line 391-394
```
- (void)attachView {
  self.iosPlatformView->attachView();
  [_textInputPlugin.get() setupIndirectScribbleInteraction:self.viewController];
}
```

**Comment by maheshmnj** [comment]
Hi @gordon-ljl, Thanks for filing the issue. Can you please share a minimal and complete sample project along with the steps to reproduce the issue? Please do also share the output of `flutter doctor -v`.

Thanks

**Comment by gordon-ljl** [comment]
I simply created a flutter project with Android studio, and then switched to xcode through "Open iOS module in Xcode" to debug the source code of the flutter engine, and found this little problem,  you can refer to the following two screenshots to understand this issue
<img width="1200" alt="issue" src="https://user-images.githubusercontent.com/37619354/174707422-87842730-78ee-43b2-bb93-9f85b3587f4c.png">
<img width="1051" alt="issue2" src="https://user-images.githubusercontent.com/37619354/174707483-eb020fdc-03e1-4225-90da-8440b22c1d4f.png">

The code at the two red arrows in the first screenshot will call PlatformViewIOS::attachView() respectively, which will cause "ios_surface_" to be created twice, and the second call is unnecessary


void PlatformViewIOS::attachView() {
...
  auto flutter_view = static_cast<FlutterView*>(owner_controller_.get().view);
  auto ca_layer = fml::scoped_nsobject<CALayer>{[[flutter_view layer] retain]};
  **_ios_surface_ = IOSSurface::Create(ios_context_, ca_layer);_**
  FML_DCHECK(ios_surface_ != nullptr);
...
}

--------------------------------------------------
execute doctor -v

┌─────────────────────────────────────────────────────────┐
│ A new version of Flutter is available!                  │
│                                                         │
│ To update to the latest version, run "flutter upgrade". │
└─────────────────────────────────────────────────────────┘
[✓] Flutter (Channel master, 3.1.0-0.0.pre.1251, on macOS 12.4 21F79 darwin-x64, locale zh-Hans-CN)
    • Flutter version 3.1.0-0.0.pre.1251 at /Users/gordonliang/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 0c0087f805 (6 days ago), 2022-06-14 21:48:06 -0400
    • Engine revision f8c0dc87bc
    • Dart version 2.18.0 (build 2.18.0-189.0.dev)
    • DevTools version 2.14.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/gordonliang/Documents/Android/sdk/
    • Platform android-32, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2022.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 67.0.4
    • Dart plugin version 221.5588

[✓] VS Code (version 1.44.2)
    • VS Code at /Users/gordonliang/Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[!] Proxy Configuration
    • HTTP_PROXY is set
    • NO_PROXY is localhost,127.0.0.1
    • NO_PROXY contains localhost
    • NO_PROXY contains 127.0.0.1
    ! NO_PROXY does not contain ::1

[✓] Connected device (3 available)
    • iPhone 13 Pro Max (mobile) • 7E68EAE4-411E-4703-B331-92AF0FE00A8A • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-15-5 (simulator)
    • macOS (desktop)            • macos                                • darwin-x64     • macOS 12.4
      21F79 darwin-x64
    • Chrome (web)               • chrome                               • web-javascript • Google
      Chrome 102.0.5005.115

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

**Comment by maheshmnj** [comment]
Thanks for the update @gordon-ljl, Labeling this issue for further investigation from the team.

cc: @cbracken

**Comment by jmagman** [comment]
Introduced in https://github.com/flutter/engine/pull/16672, let's make sure we don't regress add-to-app https://github.com/flutter/flutter/issues/50949
/cc @cyanglaz
