### ISSUE TITLE
After upgrading to flutter 3.0 AndroidView is always on top of other widgets on Android

### ISSUE THREAD

**Issue by usamashafiqs** [flutter/flutter#106246]
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. After upgrading to flutter 3.0 android view is always on top of other widgets on Android
3. Work fine with flutter v2.10.5

**Expected results:** 
![Screenshot_20220618-162519](https://user-images.githubusercontent.com/18592683/174435551-a456389b-5057-4515-ac2b-c8d7b2093013.png)

**Actual results:** 
![Screenshot_20220618-162556](https://user-images.githubusercontent.com/18592683/174435562-41c7b406-c837-4316-867f-eafd50709b8b.png)

<details>
<summary>Code sample</summary>

``` 
Scaffold(
      body: Stack(
        children: <Widget>[
         AndroidView(),
         const Container(
            height: 200.0,
            width: 200.0,
            color: Colors.red,
          ),
        ],
      ),
    );
```

</details>

**Comment by darshankawar** [comment]
I believe you are hitting https://github.com/flutter/flutter/issues/103630 so please follow-up in it for further updates.
Closing this as a duplicate.
