### ISSUE TITLE
Uncategorized (Xcode): Command CompileSwiftSources failed with a nonzero exit code

### ISSUE THREAD

**Issue by kenaitian** [flutter/flutter#106247]
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. ... 
3. ... 

**Expected results:** 
For application to properly run on iPhone

**Actual results:** 
```
Launching lib/main.dart on iPhone (2) in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: SJAV7HZQZ6
Running Xcode build...
Xcode build done.                                           27.8s
Failed to build iOS app
Error output from Xcode build:
↳
    2022-06-18 09:04:51.504 xcodebuild[77577:6648066] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionSentinelHostApplications for extension Xcode.DebuggerFoundation.AppExtensionHosts.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
    2022-06-18 09:04:51.504 xcodebuild[77577:6648066] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionPointIdentifierToBundleIdentifier for extension Xcode.DebuggerFoundation.AppExtensionToBundleIdentifierMap.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
    2022-06-18 09:04:53.769 xcodebuild[77577:6648074]  DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/DVTiOSFrameworks/DVTiOSFrameworks-20038/DTDeviceKitBase/DTDKRemoteDeviceData.m:373
    Details:  (null) deviceType from 00008030-0004551014E8802E was NULL when -platform called.
    Object:   <DTDKMobileDeviceToken: 0x7f8318bd5ff0>
    Method:   -platform
    Thread:   <NSThread: 0x60000237f900>{number = 2, name = (null)}
    Please file a bug at https://feedbackassistant.apple.com with this warning message and any useful information you can provide.
    2022-06-18 09:04:54.061 xcodebuild[77577:6648079]  DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/DVTiOSFrameworks/DVTiOSFrameworks-20038/DTDeviceKitBase/DTDKRemoteDeviceData.m:373
    Details:  (null) deviceType from 00008030-0004551014E8802E was NULL when -platform called.
    Object:   <DTDKMobileDeviceToken: 0x7f8318bd5ff0>
    Method:   -platform
    Thread:   <NSThread: 0x600002c6ebc0>{number = 3, name = (null)}
    Please file a bug at https://feedbackassistant.apple.com with this warning message and any useful information you can provide.
    2022-06-18 09:04:54.169 xcodebuild[77577:6648079]  DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/DVTiOSFrameworks/DVTiOSFrameworks-20038/DTDeviceKitBase/DTDKRemoteDeviceData.m:373
    Details:  (null) deviceType from 00008030-0004551014E8802E was NULL when -platform called.
    Object:   <DTDKMobileDeviceToken: 0x7f8318bd5ff0>
    Method:   -platform
    Thread:   <NSThread: 0x600002c6ebc0>{number = 3, name = (null)}
    Please file a bug at https://feedbackassistant.apple.com with this warning message and any useful information you can provide.
    ** BUILD FAILED **


Xcode's output:
↳
    Writing result bundle at path:
    	/var/folders/kk/myzww_6s6vnd669d4x9yr_nw0000gn/T/flutter_tools.RG12RK/flutter_ios_build_temp_dire3ie33/temporary_xcresult_bundle

    Command CompileSwiftSources failed with a nonzero exit code
    /Users/ken/.pub-cache/hosted/pub.dartlang.org/path_provider_ios-2.0.10/ios/Classes/messages.g.m:7:9: fatal error: 'Flutter/Flutter.h' file not found
    #import <Flutter/Flutter.h>
            ^~~~~~~~~~~~~~~~~~~
    1 error generated.
    note: Using new build system
    note: Planning
    note: Build preparation complete
    note: Building targets in dependency order

    Result bundle written to path:
    	/var/folders/kk/myzww_6s6vnd669d4x9yr_nw0000gn/T/flutter_tools.RG12RK/flutter_ios_build_temp_dire3ie33/temporary_xcresult_bundle


Could not build the precompiled application for the device.
Uncategorized (Xcode): Command CompileSwiftSources failed with a nonzero exit code

Lexical or Preprocessor Issue (Xcode): 'Flutter/Flutter.h' file not found
/Users/ken/.pub-cache/hosted/pub.dartlang.org/path_provider_ios-2.0.10/ios/Classes/messages.g.m:6:8

Lexical or Preprocessor Issue (Xcode): 'Flutter/Flutter.h' file not found
/Users/ken/.pub-cache/hosted/pub.dartlang.org/path_provider_ios-2.0.10/ios/Classes/FLTPathProviderPlugin.h:4:8


Error launching application on iPhone (2).

```
<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
[iOS_logs](https://github.com/lessimp/lessimp_logs.git)
```

```
[iOS_logs (flutter analyze)](https://github.com/lessimp/lessimp_logs.git)
```

```
[iOS_logs (flutter doctor -v)](https://github.com/lessimp/lessimp_logs.git)
```

</details>

![Screen Shot 2022-06-18 at 9 21 13 AM](https://user-images.githubusercontent.com/63857624/174439762-092128f9-dd84-46f6-8f76-1f090288ca5b.png)

**Comment by kenaitian** [comment]
For some reason, build keeps failing and ultimately leads to "Lexical or Preprocessor Issue (Xcode): 'Flutter/Flutter.h' file not found"
ios/podfile:

# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

# post_install do |installer|
#   installer.pods_project.targets.each do |target|
#     flutter_additional_ios_build_settings(target)
#   end
# end

post_install do |installer|
 installer.pods_project.targets.each do |target|
  target.build_configurations.each do |config|
   config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.3'
#   config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.5'
  end
 end
end

**Comment by darshankawar** [comment]
@kenaitian 
Inside `post_install` section, you need to have below entry which is required to process the plugins:

`flutter_additional_ios_build_settings(target)`

Add above and try again to see if it helps to resolve the issue.

example:

```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
```

**Comment by kenaitian** [comment]
I added "flutter_additional_ios_build_settings(target)" per your advice under post_install of the Podfile and no longer have that "flutter/flutter.h" problem leading to another issue via [error_after_Podfile_settings](https://github.com/lessimp/lessimp_logs/blob/main/error_after_Podfile_settings):
post_install do |installer|
 installer.pods_project.targets.each do |target|
**flutter_additional_ios_build_settings(target)**
target.build_configuration.each do |config|
config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
end
end
end

**Comment by kenaitian** [comment]
Following https://github.com/react-native-community/upgrade-support/issues/99 does not seem to help this issue:

![Screen Shot 2022-06-24 at 1 14 22 AM](https://user-images.githubusercontent.com/63857624/175467109-6b7a2fe6-74d1-403e-ad29-33048996bf21.png)

**Comment by kenaitian** [comment]
This iOS Launch Files guide seems promising for the "error: Build input file cannot be found: '/Users/ken/Documents/Projects/lessimp/ios/Runner/Base.lproj/Main.storyboard'":

 [https://titaniumsdk.com/guide/Titanium_SDK/Titanium_SDK_How-tos/User_Interface_Fundamentals/Icons_and_Splash_Screens/iOS_Launch_Files.html](https://www.google.com/url?q=https://titaniumsdk.com/guide/Titanium_SDK/Titanium_SDK_How-tos/User_Interface_Fundamentals/Icons_and_Splash_Screens/iOS_Launch_Files.html&sa=D&source=buganizer&usg=AOvVaw064-WERPg70Sh98zPs4Jmc)

**Comment by darshankawar** [comment]
From the error log, XCode isn't able to find `launch.storyboard` file:

```
Could not build the precompiled application for the device.
Error (Xcode): Build input file cannot be found: '/Users/ken/Documents/Projects/lessimp/ios/Runner/Base.lproj/LaunchScreen.storyboard'

Error (Xcode): Build input file cannot be found: '/Users/ken/Documents/Projects/lessimp/ios/Runner/Base.lproj/Main.storyboard'
```

Can you confirm if the said file exists in your project ?  `ios/Runner/Base.lproj/LaunchScreen.storyboard` ?

See below links for your further reference:

https://developer.apple.com/forums/thread/670162
https://developer.apple.com/forums/thread/116142

**Comment by kenaitian** [comment]
@darshankawar Why close ticket when I had already mentioned that the file in question does exist via path?

**Comment by darshankawar** [comment]
@kenaitian did you try above as mentioned https://github.com/flutter/flutter/issues/106247#issuecomment-1166891216 ?

**Comment by kenaitian** [comment]
> @kenaitian did you try above as mentioned [#106247 (comment)](https://github.com/flutter/flutter/issues/106247#issuecomment-1166891216) ?

I tried a series of steps and got this error about "Xcode 11 Command PhaseScriptExecution failed with a nonzero exit code"
https://developer.apple.com/forums/thread/123790
and now dealing with https://github.com/lessimp/lessimp_logs/blob/main/AppDelegate_swift_log

**Comment by darshankawar** [comment]
It seems your project is messed up. 

For `duplicate symbols for architecture arm64`, try if [this](https://github.com/flutter/flutter/issues/44305#issuecomment-567788768) helps. 

For `error: Build input file cannot be found: ios/Runner/AppDelegate.swift`, does the said file exist at given path ? Can you provide screenshot from your project folder that shows this file ?

Same for 

```
`Error (Xcode): Build input file cannot be found: '/Users/ken/Documents/Projects/lessimp/ios/Runner/Base.lproj/LaunchScreen.storyboard'

Error (Xcode): Build input file cannot be found: '/Users/ken/Documents/Projects/lessimp/ios/Runner/Base.lproj/Main.storyboard'`
```

**Comment by kenaitian** [comment]
I didn't even bother with any other links providing instructions, except to create a simple flutter app and adding all copying code from other the same project and it now works. Thanks for your assistance. Note that "flutter_additional_ios_build_settings(target)" would be added on the simple flutter app and I also added Firebase SDK via Xcode: File > Add Packages when prompted after entering the URL - https://github.com/firebase/firebase-ios-sdk
