### ISSUE TITLE
[go_router] navigation in responsive layout (please see description)

### ISSUE THREAD

**Issue by Pr47h4m** [flutter/flutter#106288]
Hello
I'm working on UI project (please see image) 
in wide screen: 3 (or in general n) pages are shown in single screen
in small screen: those 3 (or in general n) pages are shown individually

I have used same family and person example in the UI

challenges I'm facing are:
* unable to map routes with UI
**section 1** (in wide screen image) is families section where list of families is displayed
^ i need to map `/families` displaying only list of family in first column rest 2 column will be blank
**section 2** (in wide screen) are family members
^ i need to map` /families/:fId` when any family is selected and in second column persons list will be displayed and third column remains empty
**section 3** (in wide screen) is profile screen
^ i need to map `/families/:fId/persons/:personId` when person is selected and showing profile in third column

please note: I'm not requesting solution for my problem i wanted to know how the following work can be done using go_router either its possible or not and is there any way to satisfy all 3 (web layout, mobile layout, url routing) requirements?

<img width="1440" alt="Screenshot 2022-06-20 at 11 48 42 AM" src="https://user-images.githubusercontent.com/56750378/174562249-f7af758e-6c12-4c0f-a4fb-c230c53647ca.png">

**Comment by exaby73** [comment]
@Pr47h4m I don't see why this would not be possible with a combination of using a state management solution to handle the data changes when a family is clicked along with [nest navigation](https://gorouter.dev/nested-navigation)

**Comment by Pr47h4m** [comment]
when i write code for router it is like
/families
              /:fId
                     /persons
                                    /:pId

so for ever next segment new page gets pushed on top
but my wide screen UI has all 3 screens inside single screen
and mobile app size screen have all 3 screens separate (one on top of other)

**Comment by iapicca** [comment]
@Pr47h4m 

does [this code](https://gist.github.com/iapicca/3ca67a732b00f383161d96dbe878891b) represent your case?

**Comment by Pr47h4m** [comment]
```
import 'package:go_router/go_router.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatefulWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
      routerDelegate: _router.routerDelegate,
      routeInformationParser: _router.routeInformationParser,
      debugShowCheckedModeBanner: false,
    );
  }

  GoRouter get _router {
    return GoRouter(
      initialLocation: '/families', // '/wide-screen-layout',
      routes: [
        GoRoute(
          path: '/families',
          builder: (context, state) {
            return Families(key: state.pageKey);
          },
          routes: [
            GoRoute(
              path: ':fId/persons',
              builder: (context, state) {
                return Persons(key: state.pageKey);
              },
              routes: [
                GoRoute(
                  path: ':pId',
                  builder: (context, state) {
                    return PersonDetails(key: state.pageKey);
                  },
                ),
              ],
            ),
          ],
        ),
        GoRoute(
          path: '/wide-screen-layout',
          builder: (context, state) {
            return WideScreenLayout(key: state.pageKey);
          },
        )
      ],
      navigatorBuilder: (context, state, widget) {
        return Material(
          child: Column(
            children: [
              Expanded(child: widget),
              Text(state.location),
            ],
          ),
        );
      },
    );
  }
}

class Families extends StatefulWidget {
  const Families({Key? key}) : super(key: key);

  @override
  _FamiliesState createState() => _FamiliesState();
}

class _FamiliesState extends State<Families> {
  @override
  Widget build(BuildContext context) {
    final screenWidth = MediaQuery.of(context).size.width;
    return Scaffold(
      appBar: screenWidth < 600
          ? AppBar(
              title: const Text('families'),
            )
          : null,
      body: Center(
        child: TextButton(
          child: const Text('Go => /families/f1/persons'),
          onPressed: () {
            context.go('/families/f1/persons');
          },
        ),
      ),
    );
  }
}

class Persons extends StatefulWidget {
  const Persons({Key? key}) : super(key: key);

  @override
  _PersonsState createState() => _PersonsState();
}

class _PersonsState extends State<Persons> {
  @override
  Widget build(BuildContext context) {
    final screenWidth = MediaQuery.of(context).size.width;
    return Scaffold(
      appBar: screenWidth < 600
          ? AppBar(
              title: const Text('Persons'),
            )
          : null,
      body: Center(
        child: TextButton(
          child: const Text('Go => /families/fId/persons/p1'),
          onPressed: () {
            context.go('/families/f1/persons/p1');
          },
        ),
      ),
    );
  }
}

class PersonDetails extends StatefulWidget {
  const PersonDetails({Key? key}) : super(key: key);

  @override
  _PersonDetailsState createState() => _PersonDetailsState();
}

class _PersonDetailsState extends State<PersonDetails> {
  @override
  Widget build(BuildContext context) {
    final screenWidth = MediaQuery.of(context).size.width;
    return Scaffold(
      appBar: screenWidth < 600
          ? AppBar(
              title: const Text('Person Details'),
            )
          : null,
      body: const Center(
        child: Text('Person details'),
      ),
    );
  }
}

class WideScreenLayout extends StatefulWidget {
  const WideScreenLayout({Key? key}) : super(key: key);

  @override
  _WideScreenLayoutState createState() => _WideScreenLayoutState();
}

class _WideScreenLayoutState extends State<WideScreenLayout> {
  @override
  Widget build(BuildContext context) {
    final screenWidth = MediaQuery.of(context).size.width;
    return Scaffold(
      appBar: AppBar(
        title: const Text('Families'),
      ),
      body: Row(
        children: [
          Expanded(
            flex: 1,
            child: Families(),
          ),
          VerticalDivider(),
          Expanded(
            flex: 1,
            child: Persons(),
          ),
          VerticalDivider(),
          Expanded(
            flex: 2,
            child: PersonDetails(),
          ),
        ],
      ),
    );
  }
}
```

this is simple runnable example of navigation using go_router
you can change `initialLocation` to '/wide-screen-layout' to see how it should look in wide screen
(also shown in example image)
so here how to sync screen with url?
so suppose if there are 5 families and 1 is selected then url should change 
suppose i have selected 1 family then persons list will be displayed and then 
when i select 1 person out of 5 person again url should change and show person details screen 

when nothing is selected only families list is shown and column2 and column3 is empty

**Comment by exaby73** [comment]
I think your query can be solved by using [nested navigation](https://gorouter.dev/nested-navigation). This issue does not seem to describe a bug here. For more help on this issue, I do suggest asking this on StackOverflow. Since this is not, a bug or feature request, I'm closing this issue. If you disagree, please comment and we can reopen it.
