### ISSUE TITLE
`test_root` parameter in `flutter/tests`

### ISSUE THREAD

**Issue by spydon** [flutter/flutter#106258]
# Feature request `flutter/tests`

## What is the problem?

If the `pubspec.yaml` file isn't in the root of the repository that is to be used for the tests, it can't be used since `cd` can't be used in the context. Which makes it hard to add tests for only one package from a monorepo like [Flame](https://github.com/flame-engine/flame/) for example.

## Suggested solution

Add a `test_root` step after `fetch`, but before `test`, where you can declare from which directory the `test` steps should be run from.

## Example

```yaml
fetch=git clone https://github.com/flame-engine/flame.git tests
fetch=git -C tests checkout 1dc313f3016c21f188375b134dd65346c0373856
test_root=packages/flame
update=packages/flame
test=flutter test
test=flutter analyze --no-fatal-infos
```

**Comment by spydon** [comment]
CC: @Hixie

**Comment by Hixie** [comment]
Normally what we do for this kind of thing is create a script. For example, this is how we handle it for `flutter_packages`: https://github.com/flutter/tests/blob/master/registry/flutter_packages.test

**Comment by spydon** [comment]
I'm thinking that it would be easier to read and review these files if as much as possible is stated within them, compared to having to checkout a specific script from another repo to check what it does, which in most monorepo cases would only be `cd` to the correct directory and then run the tests.

**Comment by Hixie** [comment]
To the extent that we have to check what the script does, we'd have to check what every test does anyway.

**Comment by spydon** [comment]
Alright, you can close this then.
To me it feels like something is missing when you have to glue it together with a shell script for a quite basic use case, but if this is how you want it we'll just do this for `flame` too. :)

**Comment by Hixie** [comment]
At the end of the day, this is just a little Dart script that runs the tests, so the simpler we keep it, the less there is for us to maintain. We might look at it differently if it was a CI system that we were planning on selling to the world. :-)
