### ISSUE TITLE
Feature Request: Inner Box Shadow for Containers

### ISSUE THREAD

**Issue by ManoVikram** [flutter/flutter#106295]
# Inner Shadow for Containers in Flutter

Flutter is really good in a lot of aspects and I'm aware that it is getting better every single day. On the path to becoming a better framework to build cross-platform apps, we users would love it if we could have an explicit feature to add an inner shadow to boxes/containers!

It would be really helpful in building a better UI and experience for the users. I request the Flutter team to consider adding the inner box-shadow feature in the upcoming Flutter versions.

**Comment by danagbemava-nc** [comment]
Hi @ManoVikram, there's an existing issue requesting this feature in https://github.com/flutter/flutter/issues/18636. 

Kindly follow up in the linked issue for updates. 

Closing from here as duplicate. 

Thank you
