### ISSUE TITLE
Getting error at build apk release - Execution failed for task ':app:compileFlutterBuildRelease'

### ISSUE THREAD

**Issue by ask9027** [flutter/flutter#106230]
Hi,
I am using flutter at Termux ubuntu arm64(Device : Android 12),
It is working for build apk --debug but when i want to build --release apk getting error at flutter 1156,

Flutter Version : 3.0.2 stable

<details>
<summary>Logs</summary>

```bash
> Task :app:compileFlutterBuildRelease FAILED
[ +494 ms] FAILURE: Build failed with an exception.
[   +9 ms] * Where:
[   +2 ms] Script
'/home/ask2784/Android/src/flutter/packages/flutter_tools/gradle/flutter.gradle' line:
1156
[   +7 ms] * What went wrong:
[   +5 ms] Execution failed for task ':app:compileFlutterBuildRelease'.
[   +1 ms] > Process 'command '/home/ask2784/Android/src/flutter/bin/flutter'' finished
with non-zero exit value 1
[   +3 ms] * Try:
[        ] > Run with --stacktrace option to get the stack trace.
[   +1 ms] > Run with --info or --debug option to get more log output.
[   +3 ms] > Run with --scan to get full insights.
[   +1 ms] * Get more help at https://help.gradle.org
[   +3 ms] BUILD FAILED in 1m 13s
[   +4 ms] Deprecated Gradle features were used in this build, making it incompatible
with Gradle 8.0.
[   +2 ms] You can use '--warning-mode all' to show the individual deprecation warnings
and determine if they come from your own scripts or plugins.
[   +5 ms] See
https://docs.gradle.org/7.4.2/userguide/command_line_interface.html#sec:command_line_war
nings
[   +1 ms] 45 actionable tasks: 1 executed, 44 up-to-date
[+1138 ms] Running Gradle task 'assembleRelease'... (completed in 75.6s)
[  +14 ms] "flutter apk" took 78,072ms.
[  +12 ms] Gradle task assembleRelease failed with exit code 1
[   +5 ms]
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      AndroidGradleBuilder.buildGradleApp
           (package:flutter_tools/src/android/gradle.dart:406:9)
           <asynchronous suspension>
           #2      AndroidGradleBuilder.buildApk
           (package:flutter_tools/src/android/gradle.dart:184:5)
           <asynchronous suspension>
           #3      BuildApkCommand.runCommand
           (package:flutter_tools/src/commands/build_apk.dart:109:5)
           <asynchronous suspension>
           #4      FlutterCommand.run.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command.dart:1183:27)
           <asynchronous suspension>
           #5      AppContext.run.<anonymous closure>
           (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #6      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure>
           (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #9      FlutterCommandRunner.runCommand
           (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #10     run.<anonymous closure>.<anonymous closure>
           (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #11     AppContext.run.<anonymous closure>
           (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #12     main (package:flutter_tools/executable.dart:94:3)
           <asynchronous suspension>
```
</details>

<img width="400" src="https://user-images.githubusercontent.com/61283438/174421413-ff793421-e0a9-4c66-9c9f-dc0d256b8629.jpg">

Please help me for this problem

**Comment by huycozy** [comment]
@ask9027 
Can you try re-running the command on the master channel with the `--verbose` flag?

FYI, this log is quite similar to issue #97764 log even though your command ran without `--analyze-size` flag

**Comment by heybeachboy** [comment]
[        ] > Task :app:compileFlutterBuildRelease FAILED
[        ] FAILURE: Build failed with an exception.
[        ] * Where:
[        ] Script 'D:\Program Files\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1156
[        ] * What went wrong:
[        ] Execution failed for task ':app:compileFlutterBuildRelease'.
[        ] > Process 'command 'D:\Program Files\flutter\bin\flutter.bat'' finished with non-zero exit value 1
[        ] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[        ] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 17s
[        ] Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
[        ] Use '--warning-mode all' to show the individual deprecation warnings.
[        ] See https://docs.gradle.org/6.8.3/userguide/command_line_interface.html#sec:command_line_warnings
[        ] 1 actionable task: 1 executed
[ +938 ms] Running Gradle task 'assembleRelease'... (completed in 19.1s)
[   +2 ms] "flutter apk" took 19,744ms.
[   +3 ms] Gradle task assembleRelease failed with exit code 1
[        ]
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      AndroidGradleBuilder.buildGradleApp (package:flutter_tools/src/android/gradle.dart:406:9)
           <asynchronous suspension>
           #2      AndroidGradleBuilder.buildApk (package:flutter_tools/src/android/gradle.dart:184:5)
           <asynchronous suspension>
           #3      BuildApkCommand.runCommand (package:flutter_tools/src/commands/build_apk.dart:109:5)
           <asynchronous suspension>
           #4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1183:27)
           <asynchronous suspension>
           #5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #6      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #9      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #10     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #12     main (package:flutter_tools/executable.dart:94:3)
           <asynchronous suspension>


[ +206 ms] ensureAnalyticsSent: 206ms
[        ] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1

**Comment by ask9027** [comment]
same problem while using flutter from master branch

**Comment by huycozy** [comment]
@ask9027 
Could you check if you have the same issue with the default flutter create project?
Also, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this and the output of `flutter doctor -v` as well.
Thank you!

**Comment by FireAndIceFrog** [comment]
I have the same problem for flutter 3.0.2 - this occurs from the template `flutter create xxx`

$ flutter build apk --verbose
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
[ +100 ms] executing: [A:\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +593 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] 676cefaaff197f27424942307668886253e1ec35
[   +1 ms] executing: [A:\flutter/] git tag --points-at 676cefaaff197f27424942307668886253e1ec35
[  +72 ms] Exit code 0 from: git tag --points-at 676cefaaff197f27424942307668886253e1ec35
[        ] 3.0.3
[  +10 ms] executing: [A:\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +67 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [A:\flutter/] git ls-remote --get-url origin
[  +57 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +155 ms] executing: [A:\flutter/] git rev-parse --abbrev-ref HEAD
[  +72 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[ +114 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +6 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +72 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[   +4 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[ +135 ms] Skipping pub get: version match.
[ +157 ms] Generating A:\Github\chat_bot\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +94 ms]  Building with sound null safety 
[  +24 ms] Running Gradle task 'assembleRelease'...
[   +6 ms] Using gradle from A:\Github\chat_bot\android\gradlew.bat.
[  +19 ms] executing: A:\Android Studio\jre\bin\java -version
[ +197 ms] Exit code 0 from: A:\Android Studio\jre\bin\java -version
[        ] openjdk version "11.0.12" 2021-07-20
           OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
           OpenJDK 64-Bit Server VM (build 11.0.12+7-b1504.28-7817840, mixed mode)
[   +2 ms] executing: A:\Android Studio\jre\bin\java -version
[ +212 ms] Exit code 0 from: A:\Android Studio\jre\bin\java -version
[   +1 ms] openjdk version "11.0.12" 2021-07-20
           OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
           OpenJDK 64-Bit Server VM (build 11.0.12+7-b1504.28-7817840, mixed mode)
[   +3 ms] executing: [A:\Github\chat_bot\android/] A:\Github\chat_bot\android\gradlew.bat -Pverbose=true -Ptarget-platform=android-arm,android-arm64,android-x64     
-Ptarget=lib\main.dart -Pbase-application-name=android.app.Application -Pdart-obfuscation=false -Ptrack-widget-creation=true -Ptree-shake-icons=true assembleRelease  
[ +123 ms] The system cannot find the path specified.
[+2258 ms] > Task :app:buildKotlinToolingMetadata UP-TO-DATE
[+1996 ms] > Task :app:compileFlutterBuildRelease
[   +2 ms] The system cannot find the path specified.
[   +6 ms] The system cannot find the path specified.
[   +8 ms] The system cannot find the path specified.
[+1985 ms] > Task :app:compileFlutterBuildRelease FAILED
[   +5 ms] FAILURE: Build failed with an exception.
[        ] * Where:
[        ] Script 'A:\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1156
[        ] * What went wrong:
[   +1 ms] Execution failed for task ':app:compileFlutterBuildRelease'.
[        ] > Process 'command 'A:\flutter\bin\flutter.bat'' finished with non-zero exit value 1
[        ] * Try:
[        ] > Run with --stacktrace option to get the stack trace.
[        ] > Run with --info or --debug option to get more log output.
[        ] > Run with --scan to get full insights.
[   +4 ms] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 6s
[        ] Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
[        ] You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
[  +11 ms] See https://docs.gradle.org/7.4/userguide/command_line_interface.html#sec:command_line_warnings
[   +1 ms] 2 actionable tasks: 1 executed, 1 up-to-date
[ +538 ms] Running Gradle task 'assembleRelease'... (completed in 7.4s)
[   +6 ms] "flutter apk" took 7,942ms.
[   +6 ms] Gradle task assembleRelease failed with exit code 1
[   +1 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      AndroidGradleBuilder.buildGradleApp (package:flutter_tools/src/android/gradle.dart:406:9)
           <asynchronous suspension>
           #2      AndroidGradleBuilder.buildApk (package:flutter_tools/src/android/gradle.dart:184:5)
           <asynchronous suspension>
           #3      BuildApkCommand.runCommand (package:flutter_tools/src/commands/build_apk.dart:109:5)
           <asynchronous suspension>
           #4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1183:27)
           <asynchronous suspension>
           #5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #6      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #9      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #10     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #12     main (package:flutter_tools/executable.dart:94:3)
           <asynchronous suspension>


[ +169 ms] ensureAnalyticsSent: 159ms
[   +2 ms] Running shutdown hooks
[   +1 ms] Shutdown hooks complete
[   +1 ms] exiting with code 1
