### ISSUE TITLE
Re-running a task for the GitHub UI does not set the cipd_version tag

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#106203]
If for some reason we need to retry a failing build twice the check will be in the scheduled state forever. There are two different issues here:

* Retrying a task is not setting the cipd_version tag which makes the next retry failed in the backend.
* The task failing in the backend is not setting the correct check state leaving the task pending forever.

Some details in this PR: https://github.com/flutter/engine/pull/33746#issuecomment-1158152086

**Comment by ricardoamador** [comment]
How was the retry done here? Was it via the checks page and a rerun link? Or did we run the full suite of failed checks? I ran a check from a failed pull request and it did not have an issue with hanging or not updating the github page.

**Comment by godofredoc** [comment]
It was retried using the re-run link from the checks tab. Retrying for the first time works because it is copying the data from the original run but not passing cipd_version as a tag. The second retry gets the build metadata from the first retry which does not include cipd_version and assumes it needs to run from main.
