### ISSUE TITLE
Git and gn errors on Dart SDK -> engine auto-roller PRs

### ISSUE THREAD

**Issue by alexmarkov** [flutter/flutter#106208]
For example see https://github.com/flutter/engine/pull/34136.

```
fatal: unable to access 'https://dart.googlesource.com/a/mime.git/': The requested URL returned error: 500
```
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8811111485758340577/+/u/Checkout_source_code/bot_update/stdout
```
Command '['git', 'remote', 'show', 'https://dart.googlesource.com/web_socket_channel.git']' returned non-zero exit status 128.
```
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8811111485758340513/+/u/Checkout_source_code/bot_update/stdout
```
Command: python3 /opt/s/w/ir/cache/builder/src/third_party/dart/tools/copy_tree.py --gn /opt/s/w/ir/cache/builder/src/flutter/prebuilts/macos-x64/dart-sdk {}
Returned 1.
```
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8811111485567401073/+/u/gn_--runtime-mode_debug_--unoptimized_--prebuilt-dart-sdk_--no-lto/stdout
```
ERROR at //third_party/dart/build/dart/copy_tree.gni:20:3: Action has no outputs.
```
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8811111485807430721/+/u/gn_--runtime-mode_debug_--unoptimized_--no-lto_--prebuilt-dart-sdk/stdout

@iskakaushik

**Comment by iskakaushik** [comment]
seems like the bots are unable to reach the host:

```
git remote show https://dart.googlesource.com/web_socket_channel.git
```

Running that command locally seems to run fine.

**Comment by keyonghan** [comment]
This is not happening.

But there is an infra issue when retrying cache clobber. Fix is in https://flutter-review.googlesource.com/c/recipes/+/31540

**Comment by keyonghan** [comment]
Fix is in.
