### ISSUE TITLE
GLFW example fails to run in Linux

### ISSUE THREAD

**Issue by betrevisan** [flutter/flutter#106221]
While attempting to run the GLFW example on Linux, I keep getting an error that Skia is not being successfully set up. The script works fine in other platforms (e.g. MacOS), which makes me wonder if there is a bug within the Linux specific code.

## Steps to Reproduce

1. In a Linux machine, execute ./run.sh from the  GLFW example folder.

## Logs

<details>
Below is the error that I get back after running ./run.sh in the GLFW example folder.

<summary>Logs</summary>

[ERROR:flutter/shell/platform/embedder/embedder_surface_gl.cc(103)] Could not create a resource context for async texture uploads. Expect degraded performance. Set a valid make_resource_current callback on FlutterOpenGLRendererConfig.
../../third_party/skia/src/gpu/ganesh/gl/GrGLInterfaceAutogen.cpp:264 GrGLInterface::validate() failed.
[ERROR:flutter/shell/gpu/gpu_surface_gl_skia.cc(54)] Failed to set up Skia Gr context.
[ERROR:flutter/shell/common/platform_view.cc(76)] Failed to create platform view rendering surface
flutter: The Dart VM service is listening on http://127.0.0.1:34203/aTHAhw8rAxE=/

</details>

**Comment by bdero** [comment]
This may or may not be partially solved by https://github.com/flutter/engine/compare/main...bdero:bdero/glfw-example-fixes.

**Comment by stuartmorgan** [comment]
(`e: glfw` is https://github.com/flutter/engine/tree/main/shell/platform/glfw)
