### ISSUE TITLE
iOS auto-provisioning code doesn't play nice with `flutter run --machine`

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#10626]
```
$ flutter run --machine
[{"event":"app.start","params":{"appId":"95ec9ce1-98b0-4440-a8b3-d73e36fa8d39","deviceId":"b851637e924ad4a23cb62691cfab9a1251fa7aef","directory":"/Users/tvolkert/project/flutter/flutter/examples/hello_world","supportsRestart":true}}]
Launching lib/main.dart on Boq in debug mode...
Multiple valid development certificates available:
  1) iPhone Developer: Google Development (3F4Y5873JF)
  2) iPhone Developer: Todd Volkert (VEM2GJ2RW9)
  a) Abort
Please select a certificate for code signing [1|2|a]: [{"event":"app.stop","params":{"appId":"95ec9ce1-98b0-4440-a8b3-d73e36fa8d39","error":"Bad state: Stream has already been listened to."}}]
```

**Comment by tvolkert** [comment]
@xster

**Comment by xster** [comment]
I guess conceptually since we're asking for user input, we're gonna need to translate that feature to support the JSON APIs too? 

The simplest solution is probably to just pick the first one, or is there an existing documentation for the JSON APIs for would be --machine developers that I can look at and extend?

**Comment by tvolkert** [comment]
@devoncarew

**Comment by devoncarew** [comment]
Yeah, we shouldn't be asking for user input in `--machine` mode, or at least not via stdin.

I possible solution here is to auto-select a certificate, print a message saying what we did, and have some instructions in there telling the user how to select an explicit one going forward. This may even be a good solution for the regular `flutter run` case - which, even for that, we may not want to interrupt a run by asking for user input. 

```
Multiple valid iOS development certificates available (3F4Y5873JF: Google Development, Todd VolkertVEM2GJ2RW9); autoselecting '3F4Y5873JF: Google Development'. In order to specify a default certificate, running `flutter config mac-certificate=xxx`.
```

**Comment by tvolkert** [comment]
Can we use `flutter config` to store the default choice going forward?

**Comment by devoncarew** [comment]
Yeah, it's just a key value store, and work probably work well for something like this. And just to re-cap my thoughts from above, instead of asking the user for the choice, I think we should:

- guess
- warn that we guessed
- provide a way to configure the choice (in a stateful way on disk)

**Comment by xster** [comment]
Great idea. I was thinking about where to save it but there's already prior art. Will use the config store. 

+1 on the other points. We already output the chosen one.

**Comment by xster** [comment]
Saving choice in #10181.
I was reading the --machine code but it wasn't very clear how it worked. Is there a global state I can read to know that it was from --machine? Doesn't seem passed down to the downstream commands.

**Comment by devoncarew** [comment]
Do you mean as an intermediate step towards not asking for user input, or as the solution for this issue? I definitely think we're better off now asking.

If this is just an intermediate step, you'd probably need to record that we're in a non-interactive mode in some global state, perhaps in a context variable (like in `globals.dart`).

**Comment by tvolkert** [comment]
+1 for not asking and just informing the user that we're choosing one and how they can update the config of which choice we'll make.

**Comment by xster** [comment]
#10181 is somewhat tangential. Trying to figure out how to know we're in --machine mode in the deeper build commands so we can guess. @devoncarew you answered my question. I'll save that state somewhere.

**Comment by xster** [comment]
Oops, pasted the wrong PR for saving before. Fixed
