### ISSUE TITLE
Cannot call showDialog if using MaterialApp.router

### ISSUE THREAD

**Issue by zcourts** [flutter/flutter#106241]
## Steps to Reproduce

1. Create a Material app using the `MaterialApp.router` constructor
2. Try to call `showDialog` anywhere in the app

**Expected results:** 
I expect the showDialog to be shown.

**Actual results:** 

An error is thrown because `showDialog` is entirely based on having a `Navigator` but by using `MaterialApp.router` you're inevitably not going to have a `Navigator.

`showMaterialBanner` is not a suitable alternative, nor is `showSnackBar`

I attempted to emulate this with `showBodyScrim` but it didn't work in the end and also requires a Scaffold in the tree which isn't always the case for us.

```shell
[   +3 ms] flutter: ----------------------
[        ] flutter: Error :  Navigator operation requested with a context that does not include a Navigator.
[        ] The context used to push or pop routes from the Navigator must be that of a widget that is a descendant of a Navigator widget.
[        ] flutter: StackTrace :  #0      Navigator.of.<anonymous closure> (package:flutter/src/widgets/navigator.dart:2553:9)
[        ] #1      Navigator.of (package:flutter/src/widgets/navigator.dart:2560:6)
[        ] #2      showDialog (package:flutter/src/material/dialog.dart:1036:19)
[        ] #3      ScreenInstance._confirmUserAction.<anonymous closure> (package:hypi_tink_widgets/models/ui/screen_instance.dart:307:7)
[        ] #4      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
[        ] #5      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1089:9)
[        ] #6      SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:995:5)
[        ] #7      _rootRun (dart:async/zone.dart:1426:13)
[        ] #8      _CustomZone.run (dart:async/zone.dart:1328:19)
[        ] #9      _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
[        ] #10     _invoke (dart:ui/hooks.dart:151:10)
[        ] #11     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308:5)
[        ] #12     _drawFrame (dart:ui/hooks.dart:115:31)
```

```
➜  flutter doctor -v
[✓] Flutter (Channel stable, 2.10.3, on macOS 12.3 21E230 darwin-arm, locale en-GB)
    • Flutter version 2.10.3 at /usr/local/flutter-2.10.3
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (4 months ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2
```

**Comment by danagbemava-nc** [comment]
Hi @zcourts, you appear to be on an older version of flutter. Kindly upgrade to the latest version of stable(3.0.2)) to see whether or not you still experience this issue.

If you do, please provide the updated `flutter doctor -v` as well as a complete minimal reproducible code sample so that we can further investigate this. 

Thank you

**Comment by zcourts** [comment]
@danagbemava-nc we're not in a position to upgrade to 3.x right now. It's a large project and each upgrade requires a sizable effort especially for QA 2.10.3 is only 3 months old (March I think) and we upgraded from 2.5 only a month ago and we're still finding issues off the back of that so to do another one is quite painful. We're spending more time upgrading and debugging upgrade issues than working on the product.

**Comment by danagbemava-nc** [comment]
Sorry about that. 

Can you provide a minimal example so that we can check whether this issue is on newer versions?

Thank you
