### ISSUE TITLE
Engine Tree red due to change in API while PR was in-progress

### ISSUE THREAD

**Issue by iskakaushik** [flutter/flutter#106218]
PR: https://github.com/flutter/engine/pull/34024

```
../../flutter/impeller/display_list/display_list_unittests.cc:326:13: error: no matching member function for call to 'drawImage'
    builder.drawImage(DlImageImpeller::Make(texture), SkPoint::Make(200, 200),
    ~~~~~~~~^~~~~~~~~
../../flutter/display_list/display_list_builder.h:274:8: note: candidate function not viable: no known conversion from 'SkSamplingOptions' to 'flutter::DlImageSampling' for 3rd argument
  void drawImage(const sk_sp<DlImage> image,
       ^
../../flutter/display_list/display_list_builder.h:278:8: note: candidate function not viable: no known conversion from 'SkSamplingOptions' to 'flutter::DlImageSampling' for 3rd argument
  void drawImage(const sk_sp<DlImage> image,
```

https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8811082473885209041/+/u/build_host_release/stdout

@JsouLiang  could you please rebase and create a new PR? I'm going to revert the old one.

cc: @flar

**Comment by flar** [comment]
(Fixed formatting in the Description that prevented me and JsouLiang from getting tagged.)

Also, @JsouLiang it looks like we don't need a "rebase and re-submit" on the PR if https://github.com/flutter/engine/pull/34143 succeeds...

**Comment by godofredoc** [comment]
Not sure what "in progress" means here? the PR was approved and tests were passing before the autosubmit landed it.

![image](https://user-images.githubusercontent.com/54371434/174396812-c09b0f44-cdd2-4ff1-b20f-7e6e82f7295e.png)

**Comment by flar** [comment]
> Not sure what "in progress" means here? the PR was approved and tests were passing before the autosubmit landed it.

This PR changed a method interface.
The other PR introduced a new use of the modified method interface that wasn't present when the first PR was created and tested.

Until both landed in the Engine tree (nearly at the same time), there was no way for the first PR to know that a new call site had to be updated and there was no way for the second PR to know that it was using a method call that was about to be modified.

Their incompatible changes crossed in the ether between their test runs and their merging.

**Comment by godofredoc** [comment]
Thanks for the explanation, I thought the bot landed it while the PR was marked as draft.
