### ISSUE TITLE
Regression in list text layout rasterization time on Android

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#106307]
On the engine roll here: https://github.com/flutter/flutter/pull/106162

SkiaPerf is reporting a 2x regression in average rasterization time in the list_text_layout_perf__e2e_summary benchmark:

https://flutter-flutter-perf.skia.org/e/?begin=1655418366&end=1655487127&keys=Xa5c2bc86cf2856a5f23b951b71eea68e&xbaroffset=29495

@dnfield

**Comment by jason-simmons** [comment]
Bisected this to https://github.com/flutter/engine/commit/1edc3502f21134cabbc3d6a5861489968dfbcd1b

@bdero

**Comment by dnfield** [comment]
How would an impeller change have affected the non-impeller version of the benchmark?

**Comment by jason-simmons** [comment]
This benchmark is run with the `enableImpeller: true` flag (see https://github.com/flutter/flutter/blob/master/dev/devicelab/bin/tasks/list_text_layout_perf__e2e_summary.dart#L11)

Is that not working as intended?

**Comment by bdero** [comment]
It appears to be intentional: https://github.com/flutter/flutter/pull/104736/files#r882955959

**Comment by dnfield** [comment]
Given that this is an impeller only regression I think we should lower priority but not sure how we're handling these.

**Comment by chinmaygarde** [comment]
Closing these as stale.
