### ISSUE TITLE
Exception caught by rendering library

### ISSUE THREAD

**Issue by kenaitian** [flutter/flutter#106345]
After having removed debugCheckElevationsEnabled per https://github.com/Dart-Code/Dart-Code/issues/4025 and following the rendering libary  -  https://api.flutter.dev/flutter/rendering/rendering-library.html, I get these errors via this [rendering_library](https://github.com/lessimp/lessimp_logs.git) log file

Question: I know the purpose of using the debug flag and some of its functions per this [YouTube video](https://www.youtube.com/watch?v=b4dCHbINmyk). Why should anyone implement code if above errors show that it gets buggy on Android Studio for the effect from the YouTube video following this flutter guide via https://docs.flutter.dev/development/tools/devtools/android-studio or https://docs.flutter.dev/development/tools/android-studio?

**Comment by maheshmnj** [comment]
Hi @kenaitian, I am quite not sure what this issue is proposing/reporting  Can you please share a minimal and complete code sample along with the output of `flutter doctor -v`?

Thanks

**Comment by kenaitian** [comment]
Please consider this issue with the rendering library resolved as I added "flutter_additional_ios_build_settings(target)" as indicated under post_install of the Podfile and no longer have that "flutter/flutter.h" problem leading to another issue via [error_after_Podfile_settings](https://github.com/lessimp/lessimp_logs/blob/main/error_after_Podfile_settings):

post_install do |installer|
 installer.pods_project.targets.each do |target|
**flutter_additional_ios_build_settings(target)**
target.build_configuration.each do |config|
config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
end
end
end

**Comment by kenaitian** [comment]
["flutter run -v" ](https://github.com/lessimp/lessimp_logs/blob/c56a508bfb688523f4b1ecf6c1a77c4a34f4978f/iOS_logs%20(flutter%20doctor%20-v))

**Comment by kenaitian** [comment]
This iOS Launch Files guide seems promising for the "error: Build input file cannot be found: '/Users/ken/Documents/Projects/lessimp/ios/Runner/Base.lproj/Main.storyboard'":

 [https://titaniumsdk.com/guide/Titanium_SDK/Titanium_SDK_How-tos/User_Interface_Fundamentals/Icons_and_Splash_Screens/iOS_Launch_Files.html](https://www.google.com/url?q=https://titaniumsdk.com/guide/Titanium_SDK/Titanium_SDK_How-tos/User_Interface_Fundamentals/Icons_and_Splash_Screens/iOS_Launch_Files.html&sa=D&source=buganizer&usg=AOvVaw064-WERPg70Sh98zPs4Jmc)

**Comment by kenaitian** [comment]
This iOS Launch Files guide seems promising for the "error: Build input file cannot be found: '/Users/ken/Documents/Projects/lessimp/ios/Runner/Base.lproj/Main.storyboard'" but no where to an end:

[https://titaniumsdk.com/guide/Titanium_SDK/Titanium_SDK_How-tos/User_Interface_Fundamentals/Icons_and_Splash_Screens/iOS_Launch_Files.html](https://www.google.com/url?q=https://titaniumsdk.com/guide/Titanium_SDK/Titanium_SDK_How-tos/User_Interface_Fundamentals/Icons_and_Splash_Screens/iOS_Launch_Files.html&sa=D&source=buganizer&usg=AOvVaw064-WERPg70Sh98zPs4Jmc)
