### ISSUE TITLE
[Impeller] Regression in impeller rasterization time on Android

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#106308]
On the engine roll here https://github.com/flutter/flutter/pull/106162

SkiaPerf is reporting a regression in average and 90th %-ile rasterization time in new_gallery_impeller__transition_perf on Android:

https://flutter-flutter-perf.skia.org/e/?begin=1655418366&end=1655487127&keys=Xdd2fea0dbd9ba3ff872c3bfa3a5aaf71&xbaroffset=29495

**Comment by chinmaygarde** [comment]
The only item that looks relevant could be the backdrop filter implementation. We haven't started any performance profiling on Android/OpenGLES right now though. Stashing for later investigation.

**Comment by chinmaygarde** [comment]
![Image](https://user-images.githubusercontent.com/44085/206796581-76866d88-ac29-4a12-9ef9-c8158aaa2e87.png)

The trend line is back and I suspect we will be making many more improvements in the future as we take on the Android effort in earnest.
