### ISSUE TITLE
Make a page start popping when swiping right anywhere on the screen.

### ISSUE THREAD

**Issue by pavittarsingh315** [flutter/flutter#106320]
## Use case
Adding the ability to pop a page when the user swipes anywhere on the screen adds lots of convenience for the user and their overall experience.

Having to reach all the way across the device(for right-handed people) to navigate back is pretty annoying especially for users on larger devices such as iPads, other tablets, and really any modern phone. Apps such as Twitter and Instagram have this feature and its very convenient.

## Proposal
Add a ```PageRoute``` which makes it possible to start navigating back when swiping right anywhere on the screen.

[Swipeable_Page_Route](https://pub.dev/packages/swipeable_page_route) already has such functionality however it has a few drawbacks:

1. You always have to explicitly push the SwipeablePageRoute everytime like so: 
   ` Navigator.of(context).push(SwipeablePageRoute(builder: (context) => myPage()));` 
2. When a widget on the page is horizontally scrollable like a horizontal ```ListView``` or a ```TabBarView```, rather than the widget scrolling when the user swipes right, the page starts to pop.

SwipeablePageRoute is a "specialized CupertinoPageRoute" so I suppose that's the best place to start. I have tried to such behavior but I wasn't too successful with it.

**Comment by wuweijian1997** [comment]
You can use [get](https://pub.dev/packages/get),It encapsulates this function. You can see how it is implemented.

**Comment by exaby73** [comment]
Hello @pavittarsingh315. Flutter follows Google's Material and Apple's Cupertino guidelines to design components. These include navigation. Apps like Twitter have this feature, yes, but it's most likely implemented by the developer or by some third party library. I don't think this proposal makes sense for Flutter. 

Some possible solutions are to build your own transition or, as @wuweijian1997 said, use GetX or copy their implementation in your own codebase. I'm closing this issue as this is not a valid feature request. You're welcome to comment if you disagree.

[Google Material guidelines](https://material.io/design/navigation/understanding-navigation.html#reverse-navigation)
[Apple Cupertino guidelines](https://developer.apple.com/design/human-interface-guidelines/inputs/touchscreen-gestures#standard-gestures)
