### ISSUE TITLE
Remove rethrow from Dart plugin registration handler

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#106322]
Currently the (non-web) Dart plugin registration catches exceptions and logs, but then re-throws. This means that if there's an exception in one plugin, all plugins that come after it alphabetically won't have their Dart registration run. This is a Dart version of the issue we already had and fixed with Java registration, which caused a lot of confusion before we changed it to catch exceptions.

We should keep the logging and remove the `rethrow`, so that only the problematic plugin will be broken, not other plugins.

**Comment by christopherfujino** [comment]
@stuartmorgan is this still a p3?
