### ISSUE TITLE
Several regressions in build time across two engine rolls

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#106305]
On the Engine roll at https://github.com/flutter/flutter/pull/105934

SkiaPerf is reporting a 2x regression in 99th %-ile frame build time on Android Moto G4

https://flutter-flutter-perf.skia.org/e/?begin=1655161949&end=1655308987&keys=X1571d863df8769d2863268cae0fc8dda&num_commits=50&request_type=1&xbaroffset=29455

The issue might actually be on the next commit, which is another large engine roll: https://github.com/flutter/flutter/pull/105978

See:

https://flutter-flutter-perf.skia.org/e/?begin=1655163791&end=1655316859&keys=X62c90029030d87852a0e7f8873983cbc&xbaroffset=29457

and

https://flutter-flutter-perf.skia.org/e/?begin=1655163791&end=1655316859&keys=X62c90029030d87852a0e7f8873983cbc&num_commits=50&request_type=1&xbaroffset=29457

**Comment by zanderso** [comment]
Also

https://flutter-flutter-perf.skia.org/e/?begin=1655164089&end=1655323328&keys=X6796800fe0e12c5f5a32958a66a19661&num_commits=50&request_type=1&xbaroffset=29458

https://flutter-flutter-perf.skia.org/e/?begin=1655164089&end=1655323328&keys=X6796800fe0e12c5f5a32958a66a19661&num_commits=50&request_type=1&xbaroffset=29458

**Comment by zanderso** [comment]
Possibly related b/236163770 /cc @rmacnak-google

**Comment by chinmaygarde** [comment]
@rmacnak-google Believes this will be resolved by https://dart-review.googlesource.com/c/sdk/+/249403. This was submitted this morning.

**Comment by zanderso** [comment]
Benchmarks have recovered. Closing.
