### ISSUE TITLE
Hot reload was rejected:

### ISSUE THREAD

**Issue by H3mnz** [flutter/flutter#106311]
When i use Wireless debugging in flutter 3.0.2
hot reload not work
and this error happen multiple time in console.

ERROR - 2022-06-20 21:07:27.133543
PUT /yYbzxB3hXcs=/
Error thrown by handler.
Bad state: Can't finalize a finalized Request.
BaseRequest.finalize
package:http/src/base_request.dart:118
StreamedRequest.finalize
package:http/src/streamed_request.dart:43
IOClient.send
package:http/src/io_client.dart:32
package:shelf_proxy/shelf_proxy.dart 59:48    proxyHandler.<fn>
package:shelf_proxy/shelf_proxy.dart 37:10    proxyHandler.<fn>

Hot reload was rejected:
Error while starting Kernel isolate task.
Try performing a hot restart instead.

**Comment by exaby73** [comment]
Hi @H3mnz, please provide a [minimal, reproducible example][1] and the output of `flutter doctor -v` as well as `flutter run -v`.

[1]: https://stackoverflow.com/help/minimal-reproducible-example

**Comment by H3mnz** [comment]
[✓] Flutter (Channel stable, 3.0.2, on Microsoft Windows [Version 10.0.22000.613], locale en-AU)
    • Flutter version 3.0.2 at E:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cd41fdd495 (13 days ago), 2022-06-08 09:52:13 -0700
    • Engine revision f15f824b57
    • Dart version 2.17.3
    • DevTools version 2.12.2

Checking Android licenses is taking an unexpectedly long time...[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at E:\android-sdk
    • Platform android-32, build-tools 31.0.0
    • ANDROID_HOME = E:\android-sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.5)
    • Visual Studio at E:\Program\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31729.503
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.68.1)
    • VS Code at C:\Users\H3mnz\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.42.0

[✓] Connected device (2 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22000.613]
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 97.0.1072.55
    ! Device 192.168.1.35:5555 is offline.

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
