### ISSUE TITLE
Navigator.pushAndRemoveUntil  throws assertion error : Failed assertion: line 5128 pos 12: '_history.isNotEmpty': is not true.

### ISSUE THREAD

**Issue by ramazan351** [flutter/flutter#106353]
its my code: 

```dart
Navigator.pushAndRemoveUntil(
          context,
          MaterialPageRoute(builder: (context) => const HomeScreen()),
          (route) => false);
```
Exception :
The following assertion was thrown building Navigator-[GlobalObjectKey<NavigatorState> _WidgetsAppState#8b03d](dirty, dependencies: [HeroControllerScope, UnmanagedRestorationScope], state: NavigatorState#59190(tickers: tracking 3 tickers)):
'package:flutter/src/widgets/navigator.dart': Failed assertion: line 5128 pos 12: '_history.isNotEmpty': is not true.
```

Flutter version 2.10.4

**Comment by maheshmnj** [comment]
Hi @ramazan351, Thanks for filing the issue. You seem to be using an older version of flutter, Please upgrade to the latest stable release 3.0.2. If the issue persists Please share a minimal and complete code sample along with the output of `flutter doctor -v ` and the complete exception logs .
