### ISSUE TITLE
[Proposal] Add Tooltip to helperError of InputDecoration

### ISSUE THREAD

**Issue by BananaMasterz** [flutter/flutter#106333]
## Proposal
I would like to have the option to show a tooltip for the `helperError` of a `TextField`

## Use case
I'm working with data tables and sometimes I have to put TextFields in cells and some times the fields cannot be wide enough for the helper error message. I would like for the user to be able to mouse over to see rest of the error. I know this isn't the best UI and ideally you want your error message to fit under the field, but sometimes it's above the developers say what ends up in the final product.

## Workaround
The way I'm currently dealing with this is by changing the `helperError` in `input_decoration.dart` from this:

```dart
final Widget helperError = _HelperError(
  textAlign: textAlign,
  helperText: decoration!.helperText,
  helperStyle: _getHelperStyle(themeData),
  helperMaxLines: decoration!.helperMaxLines,
  errorText: decoration!.errorText,
  errorStyle: _getErrorStyle(themeData),
  errorMaxLines: decoration!.errorMaxLines,
);
```

to this: 

```dart
import 'package:flutter/material.dart';
.
.
.
final Widget helperError = Tooltip(
  message: decoration!.errorText ?? '',
  child: _HelperError(
    textAlign: textAlign,
    helperText: decoration!.helperText,
    helperStyle: _getHelperStyle(themeData),
    helperMaxLines: decoration!.helperMaxLines,
    errorText: decoration!.errorText,
    errorStyle: _getErrorStyle(themeData),
    errorMaxLines: decoration!.errorMaxLines,
  ),
);
```

I'm sure there's a better way to implement it ofc but haven't gotten to it.

**Comment by bleroux** [comment]
Closing as fixed by https://github.com/flutter/flutter/pull/145157 which introduced `InputDecoration.helper`.
`InputDecoration.helper` accepts any widget so it gives the Flexibility to add a Tooltip if wanted.
