### ISSUE TITLE
art_sigsegv_fault or abort error

### ISSUE THREAD

**Issue by pickupsb** [flutter/flutter#106392]
first of all sorry for my English, English is not my first language, i hope you are able to understand it.
when i constantly send message from java to flutter and update a progressbar with provider some err like art_sigsegv_fault or abort occurs!
its an ndk app, at first i thought it was c code , but i didn't solve it until i delete the codes that update ui like "provider.of…". 
is there any solution?
i use c code both with jni and ffi.

**Comment by exaby73** [comment]
Hi @pickupsb, please provide a [minimal, reproducible example][1] and the output of `flutter doctor -v` as well as `flutter run -v`.

[1]: https://stackoverflow.com/help/minimal-reproducible-example

**Comment by mraleph** [comment]
Given the description you most likely have some sort of bug in your code (some form of JNI misuse or memory corruption) which causes ART to crash.
