### ISSUE TITLE
ImageCache.clear should maybe be called when views are detached from the engine

### ISSUE THREAD

**Issue by xster** [flutter/flutter#106394]
Currently, when a view is detached from the FlutterEngine, the rasterizer is torn down, and after https://github.com/flutter/engine/pull/33890, the skia resource cache is cleared as well. However, the image cache isn't currently and it's not as clear what the correct behavior should be.

When the engine is retained but the view is no longer attached (such as in hybrid use cases), it's unclear what the user's intentions are. 

1- the application may be weaving in and out of Flutter views, in which case it may be more beneficial to keep the image cache
2- the application may not show a Flutter UI for a long time or when it does show a Flutter UI again, it would be for a different screen with minimal re-use of the previous screen's cache

For case 2, it would be great to have this as a global configurable (perhaps as an option in the embedding) such that it would require no additional wiring to not leave resident memory in the process when no Flutter screens are shown.

For case 1, the solution could be as simple as letting the user decide whether to listen to listen to https://api.flutter.dev/flutter/widgets/WidgetsBindingObserver-class.html and call ImageCache.clear when `detached`. But we should definitely have clear docs for this since it would otherwise be very difficult to discover. 

@dnfield @zanderso

**Comment by dnfield** [comment]
I think what's probably more important here is making it easier for users to discover what images (and perhaps pictures) are resident in memory, particularly those in the image cache, and how much memory they're taking. I vaguely remember devtools making this somewhat possible, but I haven't looked at that recently.

@jacob314 might remember, or @polina-c

**Comment by dnfield** [comment]
I'm hesitant to change or add behaviore related to clearing the image cache though, since I think application developers are in a better position to know whether/when they need to do that - and they have no good way to recover from an incorrectly cleared memory cache, whereas in low memory situations the image cache will get cleared anyway (except, currently, in the FlutterFragment case because of #105346)

**Comment by chinmaygarde** [comment]
Per Dans comment: The cache is purged in low memory situations and developers have signals already to affect clearing the cache themselves. Closing this as WAI.
