### ISSUE TITLE
Add support for prereleases in flutter/packages and flutter/plugins

### ISSUE THREAD

**Issue by johnpryan** [flutter/flutter#106363]
Allow packages in [flutter/packages](https://github.com/flutter/packages) and [flutter/plugins](https://github.com/flutter/plugins) to specify a [prerelease](https://dart.dev/tools/pub/publishing#publishing-prereleases) version in their pubspec, such as `2.0.0-dev.1`.

**Comment by stuartmorgan** [comment]
The tools update is published, so you'll just need to update flutter/packages to flutter_plugin_tools 0.8.8 when (or before) you want to do a prerelease.
