### ISSUE TITLE
Problem with camera permission

### ISSUE THREAD

**Issue by aytoku** [flutter/flutter#106401]
Hello. I have some problems with camera permission. On ios and android doesn't show permission after app installing and may be cause of I can't agree camera permission "await availableCameras()" calls crash like "Unhandled Exception: Unhandled error MissingPluginException(No implementation found for method availableCameras on channel plugins.flutter.io/camera) occurred in Instance of". Specified permissions in info.plist and androidManifetst.xml. If you had problem like that can you give some advices how can I fix this. Thank you.

**Comment by exaby73** [comment]
@aytoku Can you check #106236 and try the fixes mentioned there?
