### ISSUE TITLE
Support creation of dart-sdk archive in builds without a prebuilt Dart SDK

### ISSUE THREAD

**Issue by whesse** [flutter/flutter#106494]
Builds of Flutter engine with a tip-of-tree Dart SDK build the Dart SDK as part of the build, so there is no prebuilt SDK to be copied
to the right place and uploaded to GCS.

We need this support to be able to build tip-of-tree engine and Dart together, upload them, and test the Flutter framework using Flutter tools to download the artifacts from cloud storage.

The fix for this is to add code to https://github.com/flutter/engine/blob/main/build/archives/BUILD.gn#L108
that zips the built dart-sdk from the build directory, and puts it in the proper place.

Assigning myself to implement this support.

@godofredoc @keyonghan @athomas

**Comment by chinmaygarde** [comment]
@whesse Can we close this issue now that the linked patch has landed?

**Comment by keyonghan** [comment]
Friendly ping @whesse

**Comment by whesse** [comment]
This is now working, using the engine_v2 recipes to build and upload engine and Dart SDK artifacts.
