### ISSUE TITLE
[video_player]Remove listener problem? 

### ISSUE THREAD

**Issue by Moyout** [flutter/flutter#106474]
After adding a listener using the _addListener ()_ method. I try to use the playercontroller _.removeListener()_ removes the listener manually, but it seems that there is no response. It continues to listen.

**Comment by huycozy** [comment]
Hi @Moyout, 
Which `video_player` version are you using?
Please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this. Also, please provide the output of `flutter doctor -v` as well.
Thank you!

**Comment by Moyout** [comment]
> 你好@Moyout,你用的是 哪个版本？ 请提供[完整且可重现的最小代码示例](https://stackoverflow.com/help/minimal-reproducible-example)，以便我们验证这一点。另外，请提供输出。 谢谢！`video_player`[](https://stackoverflow.com/help/minimal-reproducible-example)`flutter doctor -v`



_Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.10.3, on Microsoft Windows [Version 10.0.22000.739], locale zh-CN)
[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.3)
[√] Android Studio (version 2021.2)
[√] IntelliJ IDEA Ultimate Edition (version 2020.3)
[√] Connected device (5 available)
[!] HTTP Host Availability
    X HTTP host https://maven.google.com/ is not reachable. Reason: An error occurred while checking the HTTP
      host: 信号灯超时时间已到


! Doctor found issues in 2 categories._

**Comment by Moyout** [comment]
> 

`video_player: ^2.4.5`
### This is my main code
`import 'package:pet_community/util/tools.dart';
import 'package:pet_community/view_models/home/video_viewmodel.dart';

class VideoWidget extends StatefulWidget {
  final String videoUrl;
  final String picUrl;
  final int index;

  const VideoWidget({
    Key? key,
    required this.videoUrl,
    required this.picUrl,
    required this.index,
  }) : super(key: key);

  @override
  State<VideoWidget> createState() => _VideoWidgetState();
}

class _VideoWidgetState extends State<VideoWidget> {
  @override
  void initState() {
    super.initState();
    context.read<VideoViewModel>().initViewModel(widget.videoUrl, context);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.black,
      body: AnnotatedRegion<SystemUiOverlayStyle>(
        value: const SystemUiOverlayStyle(
          statusBarBrightness: Brightness.dark,
          statusBarIconBrightness: Brightness.light,
          statusBarColor: Colors.transparent,
        ),
        child: Stack(
          children: [
            GestureDetector(
              onTap: () {
                if (context.read<VideoViewModel>().playerController?.value.isPlaying ?? false) {
                  context.read<VideoViewModel>().playerController?.pause();
                } else {
                  context.read<VideoViewModel>().playerController?.play();
                }
              },
              child: Container(
                alignment: Alignment.center,
                // color: Colors.black,
                child: AspectRatio(
                  aspectRatio: context.watch<VideoViewModel>().playerController?.value.aspectRatio ?? 1 / 2,
                  child: !context.watch<VideoViewModel>().playerController!.value.isInitialized
                      ? Hero(
                          tag: widget.picUrl + widget.index.toString(),
                          child: CachedNetworkImage(
                            cacheKey: widget.picUrl,
                            imageUrl: widget.picUrl,
                            fit: BoxFit.cover,
                          ),
                        )
                      : Hero(
                          tag: widget.picUrl + widget.index.toString(),
                          child: VideoPlayer(context.watch<VideoViewModel>().playerController!),
                        ),
                ),
              ),
            ),
            Positioned(
              left: 0,
              right: 0,
              bottom: 0,
              child: buildProgress(),
            ),
          ],
        ),
      ),
    );
  }

  Widget buildProgress() {
    return SafeArea(
      child: context.watch<VideoViewModel>().position.isNaN ||
              context.watch<VideoViewModel>().playerController!.value.isBuffering
          ? Container(
              height: 22.w,
              width: MediaQuery.of(context).size.width,
              alignment: Alignment.center,
              child: SizedBox(
                height: 2.w,
                child: const LinearProgressIndicator(color: Colors.white),
              ),
            )
          : Container(
              height: 22.w,
              width: MediaQuery.of(context).size.width,
              // color: Colors.grey.withOpacity(0.2),
              alignment: Alignment.center,
              child: GestureDetector(
                behavior: HitTestBehavior.opaque,
                onPanDown: (DragDownDetails e) {
                  context.read<VideoViewModel>().dragState = DragState.dragStateBegin;
                  context.read<VideoViewModel>().playerController?.pause();
                  context.read<VideoViewModel>().notifyListeners();
                },
                onHorizontalDragUpdate: (DragUpdateDetails v) {
                  // debugPrint("v--------->${v.globalPosition.dx}");
                  // context.read<VideoViewModel>().position = v.globalPosition.dx;
                  // context.read<VideoViewModel>().dragState = DragState.dragStateBegin;
                  //
                  // context.read<VideoViewModel>().notifyListeners();
                  context.read<VideoViewModel>().onHorizontalDragUpdate(context, v.globalPosition.dx);
                },
                onHorizontalDragEnd: (DragEndDetails v) {
                  context.read<VideoViewModel>().onHorizontalDragEnd(context);
                },
                onTapUp: (v) {
                  context.read<VideoViewModel>().dragState = DragState.dragStateEnd;
                  context.read<VideoViewModel>().playerController?.play();
                  context.read<VideoViewModel>().notifyListeners();
                },
                onVerticalDragEnd: (v) {
                  context.read<VideoViewModel>().dragState = DragState.dragStateEnd;
                  context.read<VideoViewModel>().notifyListeners();
                },
                child: Stack(
                  alignment: Alignment.center,
                  children: [
                    Positioned(
                      top: 10.w,
                      left: 0,
                      bottom: 10.w,
                      child: Container(
                        height: 2.w,
                        color: Colors.grey.withOpacity(0.5),
                        width: context.watch<VideoViewModel>().cacheWidth,
                      ),
                    ),
                    Positioned(
                      left: 0,
                      right: 0,
                      child: Row(
                        mainAxisSize: MainAxisSize.min,
                        children: [
                          AnimatedContainer(
                            constraints: BoxConstraints(
                              minWidth: 0,
                              maxWidth: MediaQuery.of(context).size.width - 8.w,
                            ),
                            duration: const Duration(milliseconds: 200),
                            width: context.watch<VideoViewModel>().position,
                            color: Colors.white,
                            height: context.watch<VideoViewModel>().dragState == DragState.dragStateBegin ? 12.w : 3.w,
                          ),
                          AnimatedContainer(
                            duration: const Duration(milliseconds: 200),
                            height: context.watch<VideoViewModel>().dragState == DragState.dragStateBegin ? 18.w : 5.w,
                            width: context.watch<VideoViewModel>().dragState == DragState.dragStateBegin ? 8.w : 5.w,
                            decoration: BoxDecoration(
                              color: Colors.blue,
                              borderRadius: BorderRadius.circular(22.w),
                            ),
                          ),
                        ],
                      ),
                    )
                  ],
                ),
              ),
            ),
    );
  }

  @override
  void dispose() {
    AppUtils.getContext().read<VideoViewModel>().disposeController();
    super.dispose();
  }
}
`

`
import 'package:pet_community/util/tools.dart';

class VideoViewModel extends ChangeNotifier {
  VideoPlayerController? playerController;
  double position = 0;
  double cacheWidth = 0;
  DragState dragState = DragState.dragStateIdle;

  void initViewModel(String videoUrl, BuildContext context) {
    initController(videoUrl, context);
  }

 
  Future<void> initController(String videoUrl, BuildContext context) async {
    position = 0;
    playerController = VideoPlayerController.network(videoUrl)
      ..initialize()
      ..setLooping(true)
      ..play()
      ..addListener(() {
        position = (MediaQuery.of(context).size.width) *
            ((playerController?.value.position.inMilliseconds ?? 0) /
                (playerController?.value.duration.inMilliseconds ?? 1));
        if (playerController!.value.buffered.isNotEmpty) {
          cacheWidth = MediaQuery.of(context).size.width *
              ((playerController?.value.buffered.first.end.inMilliseconds ?? 0) /
                  (playerController?.value.duration.inMilliseconds ?? 1));
        }
        notifyListeners();
      });
  }

  void onHorizontalDragUpdate(BuildContext context, double width) {
    dragState = DragState.dragStateBegin;
    position = width;
    debugPrint("Percent--------->${width / MediaQuery.of(context).size.width}");

    notifyListeners();
  }

  void onHorizontalDragEnd(BuildContext context) {
    dragState = DragState.dragStateEnd;

    double percent = position / MediaQuery.of(context).size.width;
    int inMilliseconds = (playerController!.value.duration.inMilliseconds * percent).toInt();
    playerController?.seekTo(Duration(milliseconds: inMilliseconds));
    playerController?.play();
    notifyListeners();
  }

 
  void disposeController() {
    playerController?.dispose();
  }
}

`

**Comment by huycozy** [comment]
@Moyout 
For the issue to be workable, it needs to be reproducible with a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code so that we can directly copy paste and run to verify this issue. Please provide such a sample.
Thank you!
