### ISSUE TITLE
Remove reflection from platform view implementation on Android

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#106449]
See https://github.com/flutter/engine/pull/33599#discussion_r903373898 for context.

That code was written at a point in time where we were very behind on the Android SDK, We have since rolled the SDK forward several times and should be good to kill at least some of the reflection now.

**Comment by reidbaker** [comment]
This is both technical debt and an reasonable bug to build expertise working in the engine since the level of functionality should stay the same.

**Comment by gmackall** [comment]
For anyone searching issues in the future that notices, that the original fix was reverted, it was relanded in https://github.com/flutter/engine/pull/50890.
