### ISSUE TITLE
ci.yaml validation is hanging for too long.

### ISSUE THREAD

**Issue by aam** [flutter/flutter#106429]
flutter engine PRs are only run through handful of checks now - only one build_and_test_linux_unopt_debug is run versus over 20 build runs just a few days ago. 

See https://github.com/flutter/engine/pull/34226 for example.

**Comment by zanderso** [comment]
I am seeing this issue on many framework and engine PRs, so bumping this to P0 since everything is blocked.

**Comment by keyonghan** [comment]
Cocoon has been switched to an earlier version. An empty commit push should unblock the PRs.

**Comment by keyonghan** [comment]
The culprit is https://github.com/flutter/cocoon/pull/1917, which incorrectly used default `builder` url instead of `build` url for `builds` related RPCs. 
```
BuildBucketException: [501]: Not Implemented

#0      BuildBucketClient._postRequest (package:cocoon_service/src/service/buildbucket.dart:80:5)
<asynchronous suspension>
#1      BuildBucketClient.batch (package:cocoon_service/src/service/buildbucket.dart:118:36)
<asynchronous suspension>
#2      LuciService.getBuilds (package:cocoon_service/src/service/luci.dart:190:41)
<asynchronous suspension>
#3      LuciService.getBuildsForBuilderList.<anonymous closure> (package:cocoon_service/src/service/luci.dart:121:49)
<asynchronous suspension>
#4      RetryOptions.retry (package:retry/retry.dart:131:16)
<asynchronous suspension>
```

**Comment by keyonghan** [comment]
Earlier version is in use, and forward fix is in: https://github.com/flutter/cocoon/pull/1927
