### ISSUE TITLE
Hot Update Support

### ISSUE THREAD

**Issue by Mrjordon88** [flutter/flutter#106465]
Does flutter now have hot update support, especially for IOS projects
The development project team needs to hot update the IOS project of flutter 😂

**Comment by ervindobri** [comment]
https://github.com/flutter/flutter/issues/14330

**Comment by Mrjordon88** [comment]
> 

thank you for your prompt reply.

**Comment by huycozy** [comment]
Closing as duplicate of #14330, so please follow up on it for further updates.
