### ISSUE TITLE
getExternalStorageDirectories( ) returns empty string

### ISSUE THREAD

**Issue by aenckli** [flutter/flutter#106498]
Previously, getExternalStorageDirectories returns list of directories with empty (or null) parameter, and the first element is same as getExternalStorageDirectory. Now, getExternalStorageDirectories() returns empty string.

I found changes ([#5959](https://github.com/flutter/plugins/pull/5959)) recently in path_provider_android.dart as below,

```
  @override
  Future<List<String>?> getExternalStoragePaths({
    StorageDirectory? type,
  }) async {

//////////// removed below return statement ////////////////
    return methodChannel.invokeListMethod<String>(
      'getExternalStorageDirectories',
      <String, dynamic>{'type': type?.index},
    );

//////////// added below return statement ////////////////
    return type == null
        ? <String>[]
        : (await _api.getExternalStoragePaths(_convertStorageDirectory(type)))
            .cast<String>();
  }

```

is this the cause of the issue ? Is there any workaround to get the list of directories as before?

**Comment by stuartmorgan** [comment]
@gaaclarke Looks like there was an unintentional behavioral change in the conversion.

**Comment by gaaclarke** [comment]
Yep, I see the problem.  The annotations in the android code were incorrect.  They stated the parameter should not be null, but it looks like being null was actually meaningful: https://github.com/flutter/plugins/pull/5959/files#diff-e9ca51e6137a39808bc271bc8eaa220104e7069020bcdc59e9df2717531eedbfL58  We should make sure to query the API with null.
