### ISSUE TITLE
autosubmit bot doesn't remove label when conditions aren't satisfied

### ISSUE THREAD

**Issue by guidezpl** [flutter/flutter#106487]
It ends up spamming the PR e.g. https://github.com/flutter/flutter/pull/99644

**Comment by guidezpl** [comment]
Looks like it also ends up commenting [after the label is removed](https://github.com/flutter/flutter/pull/99644#issuecomment-1164388841).

**Comment by guidezpl** [comment]
Bumping up priority since the bot is effectively spamming certain PRs.

**Comment by keyonghan** [comment]
Fix is in.
