### ISSUE TITLE
Issue while building Flutter APK with obfuscate flag. 

### ISSUE THREAD

**Issue by vishesh005** [flutter/flutter#106408]
Hi ,

I'm facing issue while building flutter apk with --obfuscate command.

Steps to replicate :

1.  Add any large json file (> 17Mb) in asset folder. 
2. Build apk using  command flutter build apk --obfuscate --split-debug-info=<folder>.
3. You will get si_signo=Segmentation fault(11), si_code=128, si_addr=(nil) error.

For your reference, please check attached screenshot.

<img width="994" alt="Screenshot 2022-06-22 at 7 10 40 PM" src="https://user-images.githubusercontent.com/29999171/175045281-e162fadf-8d43-4587-ad2e-1dc788c839c1.png">

**Comment by huycozy** [comment]
Hi @vishesh005, 
I was trying to build APK with obfuscate flag in a sample project contains [26MB JSON file](https://github.com/json-iterator/test-data/blob/master/large-file.json) but it was successful:

```bash
➜  reproduce_issues flutter build apk --obfuscate --split-debug-info=build/app/outputs/symbols

💪 Building with sound null safety 💪

Running Gradle task 'assembleRelease'...                           54.4s
✓  Built build/app/outputs/flutter-apk/app-release.apk (21.6MB).
```

Which Flutter version are you using now?
And please provide the output of `flutter doctor -v`.
Thank you!

**Comment by vishesh005** [comment]
Hi @huycozy ,

I'm using version 2.0.0.

**Comment by huycozy** [comment]
You are using the old Flutter version, the latest Flutter stable is `3.0.3` and the master is `3.1.0-0.0.pre.1359`. Please try upgrading them and retry to see if this issue still reproduces?

**Comment by vishesh005** [comment]
Thanks, we are planning to migrate our current project to flutter 3.0. I'll give it a try once our migration is done and then update you.
