### ISSUE TITLE
Proposal to configure hintText to be always visible even when inputting

### ISSUE THREAD

**Issue by IlyaMax** [flutter/flutter#106478]
## Use case

I'd like to add a hint which is visible always, even when I type a text

## Proposal

Add HintTextBehavior enum with values default value(not sure how to name but with current behavior) and always

**Comment by huycozy** [comment]
@IlyaMax okay, thank you. Labeling the issue as a proposal.

**Comment by guidezpl** [comment]
Hi, as this is the role of the `label` (see https://material.io/components/text-fields/flutter#using-text-fields), closing this issue as not planned.

**Comment by IlyaMax** [comment]
@guidezpl so maybe rename this issue to "configure labelText"? I can't achieve desired behavior anyway with current `TextField` interface.

**Comment by IlyaMax** [comment]
with `labelText` and `FloatingLabelBehavior.never` I can achieve keeping visible text until field is focused. with `hintText` I can achieve keeping visible text until I type. but I still can't achieve keeping visible text always, even when I type.

**Comment by guidezpl** [comment]
I'm not sure I understand, you can totally have the label text visible at all times, see https://gallery.flutter.dev/#/demo/text-field for an example.
