### ISSUE TITLE
[flutter_releases] 3.0.3 stable packaging builds used an old recipe with a bug

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#106446]
Failed builds:
- https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20Flutter%20Stable%20Packaging/67/overview
- https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20Flutter%20Stable%20Packaging/58/overview

Things that went wrong:

1. Packaging builds used tagged/branched recipes (https://flutter.googlesource.com/infra/+/refs/heads/main/config/packaging_config.star#54), when they should use the latest
2. The tagged version of the recipes, had a bug where they were supposed to check out the framework from master HEAD to use the latest version of prepare_package.dart, however it actually cloned the engine at master HEAD, thus the framework version was the initial checkout, from the release branch: https://flutter.googlesource.com/recipes/+/refs/heads/flutter-2.13-candidate.2/recipes/packaging/packaging.py#52
  a. This had been fixed upstream in https://flutter.googlesource.com/recipes/+/df2294643e381c854b901642da6d5dc3a2e42a7b and https://flutter.googlesource.com/recipes/+/4fb75da437d14a111a27327d69aabaae69d97a20
3. The branched version of prepare_package.dart from flutter/flutter did not have an upstream fix: https://github.com/flutter/flutter/pull/104222

**Comment by CaseyHillers** [comment]
Fix is in https://flutter-review.googlesource.com/c/infra/+/31460

**Comment by christopherfujino** [comment]
Fixed https://flutter-review.googlesource.com/c/infra/+/31460
