### ISSUE TITLE
Customize size of TabPageSelector

### ISSUE THREAD

**Issue by alardizabal** [flutter/flutter#10642]
I'd like the ability to customize the size of the dots in a TabPageSelector. This was mentioned in https://github.com/flutter/flutter/issues/10475. That issue was closed but the dot size is a separate issue to the tab bar indicator. @gavindoughtie had an outstanding PR that hadn't been merged (https://github.com/flutter/flutter/pull/7553/files).

**Comment by HansMuller** [comment]
I'll add the indicatorSize, selectedColor, and (not selected) color parameters. Although in this case it might be more flexible to just allow you to provide a callback that generates a widget.
