### ISSUE TITLE
 Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause. In either case, please report this assertion by filing a bug on GitHub:

### ISSUE THREAD

**Issue by manal2015hassan** [flutter/flutter#106501]

**Comment by abhineetchandan** [comment]
@manal2015hassan  You should provide at least the code sample and the logs by running
```flutter run -v``` and attach the outputs of the flutter doctor

**Comment by manal2015hassan** [comment]
> 

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
          fontFamily: 'BigVesta-Arabic'),
      home: const SplashScreen(
      ),
    );
  }
}

**Comment by abhineetchandan** [comment]
@manal2015hassan Just to be sure have you added the fontFamily to your assets & referenced it in your pubspec.yaml file?

**Comment by manal2015hassan** [comment]
> @manal2015hassan Just to be sure have you added the fontFamily to your assets & referenced it in your pubspec.yaml file?

 fonts:
    - family: BigVesta-Arabic
      fonts:
        - asset: fonts/BigVesta-Arabic-Regular.ttf 
        -

**Comment by manal2015hassan** [comment]
When i use it in textstyle is work 
But when i use it in them it will happen like this
