### ISSUE TITLE
Failed to build iOS app: Lexical or Preprocessor Issue (Xcode): 'Flutter/Flutter.h' file not found

### ISSUE THREAD

**Issue by kenaitian** [flutter/flutter#106566]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce
flutter run

_Please tell us what you were doing and what went wrong_

Please click here for error via [iOS_logs](https://github.com/lessimp/lessimp_logs/blob/main/iOS_logs)

## Version info

Please paste the output of running `flutter doctor -v` here (available from the command
line or from `Tools > Flutter > Flutter Doctor`). It will provide the version of the
Flutter framework as well as of the IntelliJ plugin.

Please click here for "flutter run -v" via [iOS_logs (flutter doctor -v)](https://github.com/lessimp/lessimp_logs/blob/main/iOS_logs%20(flutter%20doctor%20-v))

**Comment by darshankawar** [comment]
This seems to be same as you mentioned in earlier issue: https://github.com/flutter/flutter/issues/106247#issuecomment-1165040625

Please don't open multiple issues for same reason. Closing as duplicate. Please follow-up in linked issue.
