### ISSUE TITLE
[web]: <describe issue here>

### ISSUE THREAD

**Issue by telefiless** [flutter/flutter#106593]
Launch a web server (for example, python -m http.server 8000, or by using the [dhttpd](https://pub.flutter-io.cn/packages/dhttpd) package), and open the /build/web directory. Navigate to localhost:8000 in your browser (given the python SimpleHTTPServer example) to view the release version of your app.

Start the web server (for example, python -m **SimpleHTTPServer** 8000, or use the [dhttpd](https://pub.flutter-io.cn/packages/dhttpd) package), then open the /build/web directory. Visit localhost:8000 (the server started with Python earlier) in a browser to see the release version of the application.
the "python -m SimpleHTTPServer 8000" is for python2,   it doesn`t work for python3

**Comment by darshankawar** [comment]
@telefiless 
I am not sure what exactly is the issue you are reporting. I tried below and it works with python3:

```
Compiling lib/main.dart for the Web...                             19.2s
dhs@Dhss-MacBook-Pro testdemo % python -m http.server 8000
dhs@Dhss-MacBook-Pro testdemo % python2 -m http.server 8000
dhs@Dhss-MacBook-Pro testdemo % python3 -m http.server 8000
Serving HTTP on :: port 8000 (http://[::]:8000/) ...

```

See https://stackoverflow.com/a/60306277 for your reference.

Closing, as this seems to be non-issue / unrelated to Flutter. You may ask the same on support channels like StackOverflow. If you disagree, write in comments and I'll reopen it.
