### ISSUE TITLE
java uses or overrides a deprecated API

### ISSUE THREAD

**Issue by alhamri** [flutter/flutter#106537]
My app works fine, but I get some notes when the compilation process:

Note: C:\Flutter_SDK\flutter\.pub-cache\hosted\pub.dartlang.org\google_maps_flutter-2.1.8\android\src\main\java\io\flutter\plugins\googlemaps\Convert.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Flutter_SDK\flutter\.pub-cache\hosted\pub.dartlang.org\location-4.4.0\android\src\main\java\com\lyokone\location\FlutterLocation.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

I installed the latest versions of google_maps_flutter and location packages.

run flutter doctor:
`Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, 2.10.0-0.3.pre, on Microsoft Windows [Version 10.0.19043.1766],
    locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[√] Chrome - develop for the web
[!] Visual Studio - develop for Windows (Visual Studio Enterprise 2019 16.11.1)
    X Visual Studio is missing necessary components. Please re-run the Visual Studio
      installer for the "Desktop development with C++" workload, and include these
      components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK
[√] Android Studio (version 2021.1)
[√] Android Studio (version 4.1)
[√] Android Studio (version 4.2)
[√] VS Code (version 1.68.1)
[√] Connected device (4 available)
[√] HTTP Host Availability

! Doctor found issues in 1 category.
`

**Comment by abinvs-2019** [comment]
It is not an error actually. Its just a warning.

**Comment by huycozy** [comment]
Hi @alhamri 

The warnings are coming from `android` itself. It shouldn't break your app, at least until those methods that are being called are removed from android itself.
Keep in mind that just because the packages are the latest versions doesn't mean that they are up to date on the native side.
For the foreseeable future, this shouldn't affect your app, but if it bothers you, file issues with the appropriate repo. Although, I imagine the plugin authors should be aware of this and will most likely be working on it.
As this isn't actually an issue with `flutter`, I'll be closing.

Thank you!

**Comment by alhamri** [comment]
> Hi @alhamri
> 
> The warnings are coming from `android` itself. It shouldn't break your app, at least until those methods that are being called are removed from android itself. Keep in mind that just because the packages are the latest versions doesn't mean that they are up to date on the native side. For the foreseeable future, this shouldn't affect your app, but if it bothers you, file issues with the appropriate repo. Although, I imagine the plugin authors should be aware of this and will most likely be working on it. As this isn't actually an issue with `flutter`, I'll be closing.
> 
> Thank you!

Ok noticed, thank you
