### ISSUE TITLE
Make `flutter test` verify that target package depends on `flutter_test`

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#10656]
Example test failures visible at https://travis-ci.org/flutter/plugins/jobs/242412801

```
RUNNING battery tests...
Running "flutter packages get" in battery...          4.5s
00:01 +0 -1: loading /home/travis/build/flutter/plugins/packages/battery/test/battery_test.dart [E]
  Failed to load "/home/travis/build/flutter/plugins/packages/battery/test/battery_test.dart": Failed assertion: boolean expression must not be null
  package:test            test
  battery_test.dart 24:3  main
  ===== asynchronous gap ===========================
  package:test            serializeSuite
  listener.dart 17:27     main
  
00:01 +0 -1: Some tests failed.    
```

**Comment by jason-simmons** [comment]
The version of the test package used by the plugin tests needs to match the version used by flutter_tools.

flutter_tools is currently pinned to 0.12.21, so pinning the tests to 0.12.21 fixes this.  Both sides will need to be upgraded simultaneously when we move to a new version of the test package.

**Comment by tvolkert** [comment]
This is potentially a big deal for any Flutter customers - it means that:

* They'll in turn need to pin to the version of `package:test` that we use in flutter_tools -- if they use an open-ended dependency (as we did in the plugins repo), they can break whenever a new version of `test` is released on pub.
* More seriously, it means that whenever we bump our pinned version of `package:test` in flutter_tools, we're likely to break the tests of all our customers, since they'll be pinned to the version we used previously.

**Comment by tvolkert** [comment]
One solution is to extricate `flutter test` from `package:test` altogether...  @Hixie, thoughts?

**Comment by Hixie** [comment]
If they depend on us and on `test`, won't they be forced to the same version of `test` as we have?

**Comment by jason-simmons** [comment]
The tests need to use the same version of `test` as `flutter_tools` (the Flutter framework doesn't bring in a dependency on `test`)

**Comment by Hixie** [comment]
Sorry, by "us" I meant flutter_test.

**Comment by tvolkert** [comment]
> If they depend on us and on test...

There's no `pub` dependency on `test` - they're simply using the `flutter` binary that comes with the Flutter SDK (and has a hidden dependency on a specific version of `test`)

**Comment by Hixie** [comment]
If they use "flutter test" they presumably either depend on "test" or on "flutter_test" which depends on "test", no?

**Comment by tvolkert** [comment]
Good point.  Though in today's failure, it was a case of [a test that didn't use flutter_test](https://github.com/flutter/plugins/blob/7149e1753cd92b0d2a8c2e1c8cbed0afc9a2aba5/packages/battery/test/battery_test.dart), yet still [depended on the Flutter SDK](https://github.com/flutter/plugins/blob/7149e1753cd92b0d2a8c2e1c8cbed0afc9a2aba5/packages/battery/pubspec.yaml#L15) (and so was running tests via `flutter test` rather than `pub test`).

**Comment by Hixie** [comment]
Ok. I guess then we should say that this:
  https://github.com/flutter/plugins/blob/master/packages/battery/pubspec.yaml
...should have depended on `flutter_test`, which would have caught this problem when `pub get` failed to find a reasonable `test` that matched all the criteria.

We can make "flutter test" verify that the target package depends on the right `test` or that it depends on `flutter_test`.

**Comment by tvolkert** [comment]
Just verifying that it depends on `flutter_test` is probably sufficient.

**Comment by jonahwilliams** [comment]
This has since been fixed: https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/test/flutter_platform.dart#L1019
