### ISSUE TITLE
flutter command should have analytics

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#1065]
We should have analytics reporting of common usage from the flutter command to we can make sure it's correctly serving users.

@sethladd has experience doing this in the past.

**Comment by sethladd** [comment]
Yup! We even have a nice package that makes this easy: https://pub.dartlang.org/packages/usage

And, we did it with the stagehand tool. Here's the code: https://github.com/google/stagehand/blob/master/lib/src/cli_app.dart#L25

Here's example text:

```
~/tmp/test $ flutter init MyApp
Do you want to help us improve Flutter by automatically sending anonymous usage statistics? We will not use this information to identify or contact you. You can read our official Privacy Policy at _link_ (Y/n) 
```

@devoncarew is the expert here.

**Comment by sethladd** [comment]
Candidate measurements:

* Number of installs (which can lead to active users)
* How the command is run (Atom, or CLI)
* Developer's operating system
* Version of flutter used
* Crashes (of the flutter tool itself)
* Number of times each command is issued (create, run, etc)
* Timings for each command
  * Perhaps command arguments, modulo not capturing user’s paths
* Knowing which command args are never used would be valuable

**Comment by sethladd** [comment]
Work here will also help with https://github.com/flutter/flutter/issues/2416

**Comment by sethladd** [comment]
Behold! Our newly minted UA code: UA-67589403-5

**Comment by sethladd** [comment]
Thanks!
