### ISSUE TITLE
Some tests in `flutter_desktop_darwin_unittests` leak into other tests

### ISSUE THREAD

**Issue by LongCatIsLooong** [flutter/flutter#106509]
Running the main runloop in `kCFRunLoopDefaultMode` in a test causes the test to crash.

See https://github.com/flutter/engine/pull/33838#discussion_r904498285.

This prevents us from using [async expectations](https://developer.apple.com/documentation/xctest/asynchronous_tests_and_expectations) in `flutter_desktop_darwin_unittests`.

**Comment by cbracken** [comment]
Deduping into #104789.
