### ISSUE TITLE
Mac Host Engine is 24% flaky on step `test: Host Tests for host_release`

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#106589]
There are [24 post-submit flakes](https://data.corp.google.com/sites/dash_infra_metrics_datasite/flutter_check_test_flakiness_status_dashboard/?p=BUILDER_NAME:%22Mac%20Host%20Engine%22&p=LIMIT:100) in recent 100 runs.

Example flaky builds:
https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20Host%20Engine/16571/overview
https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20Host%20Engine/16570/overview
https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20Host%20Engine/16567/overview

Error logs:
```
[223/224] EmbedderTest.CanInvokeCustomEntrypoint (142 ms)
[224/224] EmbedderA11yTest.A11yTreeIsConsistent (120170 ms)
[INFO:test_timeout_listener.cc(76)] Test timeout of 120 seconds per test case will be enforced.
[0;33mNote: Google Test filter = EmbedderA11yTest.A11yTreeIsConsistent
[m[0;32m[==========] [mRunning 1 test from 1 test suite.
[0;32m[----------] [mGlobal test environment set-up.
[0;32m[----------] [m1 test from EmbedderA11yTest
[0;32m[ RUN      ] [mEmbedderA11yTest.A11yTreeIsConsistent
[FATAL:flutter/testing/test_timeout_listener.cc(45)] Check failed: delay < timeout_. Test EmbedderA11yTest.A11yTreeIsConsistent did not complete in 120 seconds and is assumed to be hung. Killing the test harness.
[ERROR:flutter/fml/backtrace.cc(116)] Caught signal SIGABRT during program execution.
Frame 0: 0x7ff81e629d10 abort
Frame 1: 0x107a5e169 fml::KillProcess()
Frame 2: 0x107a5e14c fml::LogMessage::~LogMessage()
Frame 3: 0x10781d244 flutter::testing::PendingTests::CheckTimedOutTests()
Frame 4: 0x10781d0c0 std::__1::__function::__func<>::operator()()
Frame 5: 0x107a5febe fml::MessageLoopImpl::FlushTasks()
Frame 6: 0x107a68b9c fml::MessageLoopDarwin::OnTimerFire()
Frame 7: 0x7ff81e7bd84f __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__
Frame 8: 0x7ff81e7bd33e __CFRunLoopDoTimer
Frame 9: 0x7ff81e7bce9d __CFRunLoopDoTimers
Frame 10: 0x7ff81e7a345f __CFRunLoopRun
Frame 11: 0x7ff81e7a25dd CFRunLoopRunSpecific
Frame 12: 0x107a68e0e fml::MessageLoopDarwin::Run()
Frame 13: 0x107a5fcd4 fml::MessageLoopImpl::DoRun()
Frame 14: 0x107a67272 std::__1::__thread_proxy<>()
Frame 15: 0x7ff81e6dd4f4 _pthread_start
Frame 16: 0x7ff81e6d900f thread_start

[224/224] EmbedderA11yTest.A11yTreeIsConsistent returned/aborted with exit code -6 (120170 ms)
FAILED TESTS (1/224):
  120170 ms: /opt/s/w/ir/cache/builder/src/out/host_release/embedder_unittests EmbedderA11yTest.A11yTreeIsConsistent (try #2)
SUMMARY:
  /opt/s/w/ir/cache/builder/src/out/host_release/embedder_unittests EmbedderA11yTest.A11yTreeIsConsistent passed 1 / 2 times.


!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!


Failed Command:

python3 /opt/s/w/ir/cache/builder/src/third_party/gtest-parallel/gtest-parallel /opt/s/w/ir/cache/builder/src/out/host_release/embedder_unittests --repeat=2

Exit Code: 250



!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!


Traceback (most recent call last):
  File "/opt/s/w/ir/cache/builder/src/flutter/testing/run_tests.py", line 1071, in <module>
    sys.exit(main())
  File "/opt/s/w/ir/cache/builder/src/flutter/testing/run_tests.py", line 1021, in main
    build_dir, engine_filter, args.coverage, args.engine_capture_core_dump
  File "/opt/s/w/ir/cache/builder/src/flutter/testing/run_tests.py", line 397, in RunCCTests
    gtest=True
  File "/opt/s/w/ir/cache/builder/src/flutter/testing/run_tests.py", line 225, in RunEngineExecutable
    env=env
  File "/opt/s/w/ir/cache/builder/src/flutter/testing/run_tests.py", line 80, in RunCmd
    (command_string, process.returncode)
Exception: Command "python3 /opt/s/w/ir/cache/builder/src/third_party/gtest-parallel/gtest-parallel /opt/s/w/ir/cache/builder/src/out/host_release/embedder_unittests --repeat=2" exited with code 250.
```

**Comment by zanderso** [comment]
@keyonghan teat failures should be sending emails to the engine sheriff. Is that happening?

Also, do you know the rough commit where these failures started?

Assigning back to you to answer these questions.

**Comment by keyonghan** [comment]
> @keyonghan test failures should be sending emails to the engine sheriff. Is that happening?

Since this flake (test step flake) doesn't cause the build to fail, it doesn't trigger the alerts. I will take a look to see how to combine failures alerts on `build`+`test` step with `success` alerts on such flakes.

> Also, do you know the rough commit where these failures started?

Flake started happening on https://github.com/flutter/engine/commit/9830def3a494ec0ecf4e0da5cbb8801ff6929400, with build: https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20Host%20Engine/12378/overview, and it flaked several times a day consistently since then.

**Comment by keyonghan** [comment]
Created https://github.com/flutter/flutter/issues/106747 to track the alert support.
Re-assigning back to engine for flake triage/fix.

**Comment by zanderso** [comment]
https://github.com/flutter/engine/commit/9830def3a494ec0ecf4e0da5cbb8801ff6929400 is too long ago to be related to any recent increase in flakiness.

Most of the recent ones seem to be `EmbedderA11yTest.A11yTreeIsConsistent`, whose timeout @dnfield bumped up in https://github.com/flutter/engine/pull/29367. I suspect that this test started to blow through the bigger timeout when we started to run tests in parallel. @dnfield should we increase the timeout again, or reconsider/disable this test?

**Comment by dnfield** [comment]
We could bump the timeout again, but maybe this test should just get moved to its own target with a higher timeout. I don't think we want individual tests taking >2 minutes generally speaking.

This test doesn't seem to be doing anything super crazy - maybe the call to `RunExpiredTasksNow`? It's mostly just a series of calls and waits, but I haven't traced through all the callbacks to understand how much work they do underneath.

**Comment by zanderso** [comment]
@keyonghan Can you tell if flakiness has gone down at all since https://github.com/flutter/engine/pull/34377 landed?

**Comment by keyonghan** [comment]
It hit three more after that landed:
https://ci.chromium.org/p/flutter/builders/prod/Mac%20Host%20Engine/16640
https://ci.chromium.org/p/flutter/builders/prod/Mac%20Host%20Engine/16641
https://ci.chromium.org/p/flutter/builders/prod/Mac%20Host%20Engine/16647

But it has been 17 runs since last flake.

**Comment by dnfield** [comment]
At least the first of those looks like a different exception...

**Comment by zanderso** [comment]
The TestSetMenu flake is closing the tree every now and then. Here is a PR to disable it https://github.com/flutter/engine/pull/34429 cc @gspencergoog

**Comment by zanderso** [comment]
@keyonghan This should be less flaky now. Could you check and close if so?

**Comment by zanderso** [comment]
I checked the dashboard, and this shard still seems a bit flaky. Unfortunately, other than digging through the links on LUCI, there's no good way to identify which runs flaked. On https://github.com/flutter/flutter/issues/106588, which is likely related, there's a question for @keyonghan about sending notifications to the sheriff on flakes.

**Comment by keyonghan** [comment]
For debug purpose, here is the recent list of flaky builds (7 out of recent 100 commits):
[16751](https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20Host%20Engine/16751/overview)
[16752](https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20Host%20Engine/16752/overview)
[16763](https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20Host%20Engine/16763/overview)
[16808](https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20Host%20Engine/16808/overview)
[16813](https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20Host%20Engine/16813/overview)
[16821](https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20Host%20Engine/16821/overview)
[16833](https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20Host%20Engine/16833/overview)

**Comment by zanderso** [comment]
1 of those 7 is the menu item test that has already been disabled.

Of the remaining 6, 3 of them are flakes of `EmbedderTest.CompositorRenderTargetsNotRecycledWhenAvoidsCacheSet`, as in https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20Host%20Engine/16813/overview. Since that seems to be the only one that's flaked more than once in the last 100 runs, let's focus on it. It looks like the author of that test was @iskakaushik. @iskakaushik Any ideas why this test might be flaking?

**Comment by chinmaygarde** [comment]
Ping @iskakaushik

**Comment by chinmaygarde** [comment]
@iskakaushik Do you have the cycles answer Zachs query about `EmbedderTest.CompositorRenderTargetsNotRecycledWhenAvoidsCacheSet` this week? If not, feel free to un-assign yourself.

**Comment by chinmaygarde** [comment]
Taking a look at the dashboard again, there flakiness in the past 100 commits is due to the five following tests. We should either follow up on these separately or track them here.

- EmbedderTest.PushingMutlipleFramesSetsUpNewRecordingCanvasWithoutCustomCompositor
- ShellTest.SecondaryVsyncCallbackShouldBeCalledAfterVsyncCallback
- EmbedderTest.PushingMutlipleFramesSetsUpNewRecordingCanvasWithCustomCompositor
- EmbedderA11yTest.A11yTreeIsConsistent
- EmbedderTest.CompositorRenderTargetsNotRecycledWhenAvoidsCacheSet

**Comment by zanderso** [comment]
Except for:
- `ShellTest.SecondaryVsyncCallbackShouldBeCalledAfterVsyncCallback` and
- `EmbedderA11yTest.A11yTreeIsConsistent`

the flaky tests are unit tests of OpenGL on macOS. (They come from `embedder_unittests_gl.cc`.) Given that, should we focus on the non-gl-backend tests first?

**Comment by dnfield** [comment]
The GL tests are using SwAngle fwiw.

**Comment by keyonghan** [comment]
F.Y.I. current flakes in [recent 100 commits](https://data.corp.google.com/sites/dash_infra_metrics_datasite/flutter_check_test_flakiness_status_dashboard/?p=BUILDER_NAME:%22Mac%20Host%20Engine%22&p=LIMIT:100):
[17257](https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20Host%20Engine/17257/overview)
[17251](https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20Host%20Engine/17251/overview)
[17249](https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20Host%20Engine/17249/overview)
[17244](https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20Host%20Engine/17244/overview)
[17221](https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20Host%20Engine/17221/overview)
[17212](https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20Host%20Engine/17212/overview)
[17197](https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20Host%20Engine/17197/overview)
[17196](https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20Host%20Engine/17196/overview)
[17195](https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20Host%20Engine/17195/overview)

**Comment by keyonghan** [comment]
@zanderso Who is the appropriate asignee?

**Comment by zanderso** [comment]
There is no one appropriate assignee because this issue covers several flaking tests. We need to make separate issues for each test that is flaking.

**Comment by keyonghan** [comment]
Based on recent 100 commits, created https://github.com/flutter/flutter/issues/109332 and https://github.com/flutter/flutter/issues/109333 to track separately.

**Comment by chinmaygarde** [comment]
The other issues are being tracked and we are investigating the flakes. Does this one still need to be open?

**Comment by keyonghan** [comment]
Closing as tracked https://github.com/flutter/flutter/issues/109332 and https://github.com/flutter/flutter/issues/109333
