### ISSUE TITLE
Scroll positions not preserved when switching tabs

### ISSUE THREAD

**Issue by KevinTheGray** [flutter/flutter#10657]
If you build a widget with tabs and scroll views, the scroll position is not maintained.   

## Steps to Reproduce
- Build and install latest Flutter Gallery from the repo, enter "Tabs" section, 
- scroll "Left" section to the bottom, 
- select to "Right" tab, 
- go back to "Left", notice it is scrolled back to the top.

## Flutter Doctor
```
[✓] Flutter (on Mac OS X 10.12.4 16E195, locale en-US, channel master)
    • Flutter at /Users/KG/Developer/Flutter/flutter
    • Framework revision 37e32d5aee (21 hours ago), 2017-06-12 12:23:13 -0700
    • Engine revision ffe8181ffe
    • Tools Dart version 1.24.0-dev.6.7

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at /Users/KG/Library/Android/sdk
    • Platform android-25, build-tools 25.0.3
    • ANDROID_HOME = /Users/KG/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.3.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3.3, Build version 8E3004b
    • ios-deploy 1.9.1
    • CocoaPods version 1.2.1

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Gradle version 3.2
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.1.4)
    • Flutter plugin version 14.0
    • Dart plugin version 171.4694.29
```

**Comment by eseidelGoogle** [comment]
@HansMuller did some work here recently, not sure what the current status is.

**Comment by HansMuller** [comment]
This looks like a consequence of https://github.com/flutter/flutter/pull/10612. We no longer save and restore scroll offsets unless a PageStorageKey can be found.

**Comment by lukef** [comment]
Is there anything that we should do specifically in our code/implementation to address it?

**Comment by HansMuller** [comment]
If you give each TabBarView a PageStorageKey, the scroll offset will be saved and restored modulo nested scroll view behavior.  Details can be found here: https://github.com/flutter/flutter/pull/10517

I'd also sent a note to flutter-dev about this change:

Widgets can save and restore state that outlives the widget itself using:
```
  PageStorage.of(context).writeState(context, value);
  var value = PageStorage.of(context).readState(context);
```
- Scrollables (their ScrollPositions really) use this mechanism to save and restore their scroll offset.
- ExpansionTiles use PageStorage to record their (boolean) expanded/collpased state.

PageStorage is a per-Route Map whose key is based on the type of the context's widget as well as the PageStorageKeys that belong to the widget's ancestors. The previous scheme was a little different and sometimes used the same PageStorage location for different contexts. More details about this can be found in the PR: https://github.com/flutter/flutter/pull/10517.

Apps that put more than one scrollable or expansion tile on the screen at the same time should use PageStorageKeys to ensure that state is saved in distinct locations. In some cases this may just involve replacing ValueKeys (which sometimes served the same purpose with the previous page storage indexing scheme) with PageStorageKeys.

A PageStorgeKey can be specified for a widget whose descendant is a scrollable (or an expansion tile) or by inserting a KeyedSubtree widget above the subtree.

Scrollables can opt out of saving and restoring their scroll offsets with a ScrollController that specifies keepScrollOffset: false. In that case the PageStorageKeys aren't needed.

If you need help with updating your app per these changes feel free to contact me directly, I'll be glad to help.
```

**Comment by Hixie** [comment]
@lukef Is the solution above sufficient or do you think we should find a way to do this automatically?

**Comment by lukef** [comment]
I think that there may be a longer term issue, but its up to you if you want to fix it.

We can definitely define keys for each widget but I feel like the expectation is that scroll offsets and tab positions should not be shared across widgets of different kinds (which is happening now).

Speaking with @collinjackson and @eseidelGoogle it might be that the autogenerated keys are not taking into account the class type (??). The widgets that are affected are all at the same level in the hierarchy but are each a different widget `class`.

**Comment by collinjackson** [comment]
On our call the morning (and in your comment just now) it sounds like you're having an issue with scroll positions being shared when they shouldn't be.

However the description of the bug indicates that scroll positions are not being shared when they should be.

This makes me think that we may be talking about two separate bugs.

A reduced test case of the unexpected behavior might help clarify things.

**Comment by lukef** [comment]
Yes. Sorry, I added my comment but it was describing a different issue. I'll remove it and add it elsewhere for clarity.

**Comment by collinjackson** [comment]
Thanks @lukef. Can this issue be resolved using the approach Hans recommended above?

**Comment by lukef** [comment]
This issue can be closed. If we have another issue we will open another issue
