### ISSUE TITLE
Mac Unopt is 6% flaky on step `test: Host Tests for host_debug_unopt`

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#106588]
There are [6 post-submit flakes](https://data.corp.google.com/sites/dash_infra_metrics_datasite/flutter_check_test_flakiness_status_dashboard/?p=BUILDER_NAME:%22Mac%20Unopt%22&p=LIMIT:100) in recent 100 runs.

Example flaky builds:
https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20Unopt/6173/overview
https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20Unopt/6165/overview
https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20Unopt/6161/overview

Error logs:
```
[356/360] HashCombineTest.CanHash (41 ms)
[357/360] StringRangeSanitizationTest.HandlesInvalidRanges (43 ms)
[358/360] StringRangeSanitizationTest.HandlesInvalidRanges (38 ms)
[359/360] AutoResetWaitableEventTest.MultipleWaiters (4233 ms)
[360/360] AutoResetWaitableEventTest.MultipleWaiters (4400 ms)
FAILED TESTS (1/360):
     100 ms: /opt/s/w/ir/cache/builder/src/out/host_debug_unopt/fml_unittests TaskRunnerCheckerTests.FailsTheCheckIfOnDifferentTaskRunner (try #1)
SUMMARY:
  /opt/s/w/ir/cache/builder/src/out/host_debug_unopt/fml_unittests TaskRunnerCheckerTests.FailsTheCheckIfOnDifferentTaskRunner passed 1 / 2 times.


!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!


Failed Command:

python3 /opt/s/w/ir/cache/builder/src/third_party/gtest-parallel/gtest-parallel /opt/s/w/ir/cache/builder/src/out/host_debug_unopt/fml_unittests --gtest_filter=-*TimeSensitiveTest* --repeat=2

Exit Code: 245



!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!


Traceback (most recent call last):
  File "/opt/s/w/ir/cache/builder/src/flutter/testing/run_tests.py", line 1071, in <module>
    sys.exit(main())
  File "/opt/s/w/ir/cache/builder/src/flutter/testing/run_tests.py", line 1021, in main
    build_dir, engine_filter, args.coverage, args.engine_capture_core_dump
  File "/opt/s/w/ir/cache/builder/src/flutter/testing/run_tests.py", line 397, in RunCCTests
    gtest=True
  File "/opt/s/w/ir/cache/builder/src/flutter/testing/run_tests.py", line 225, in RunEngineExecutable
    env=env
  File "/opt/s/w/ir/cache/builder/src/flutter/testing/run_tests.py", line 80, in RunCmd
    (command_string, process.returncode)
Exception: Command "python3 /opt/s/w/ir/cache/builder/src/third_party/gtest-parallel/gtest-parallel /opt/s/w/ir/cache/builder/src/out/host_debug_unopt/fml_unittests --gtest_filter=-*TimeSensitiveTest* --repeat=2" exited with code 245.
```

**Comment by chinmaygarde** [comment]
The three linked flakes are not the same. The second one is `FlutterMenuPluginTest.TestSetMenu` which is a known bad test. The first one, we will need to investigate. It is in the Darwin message loop termination. The test has also been stable forever. So not sure if this could be because of platform specific issues.

@keyonghan How are these failures aggregated? We may need to go chase down the other other unrelated failure in `FlutterMenuPluginTest.TestSetMenu`.

**Comment by Hixie** [comment]
Do we have separate issues for the separate flakes listed above? Which one is this issue specifically about?

**Comment by keyonghan** [comment]
Here is the bug: https://github.com/flutter/flutter/issues/106747. I will try cycling back on this issue.

**Comment by keyonghan** [comment]
For flaky builds, here are the list for recent 100 commits (since 07/07/2022)
[6394](https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20Unopt/6394/overview)
[6408](https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20Unopt/6408/overview)
[6428](https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20Unopt/6428/overview)
[6432](https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20Unopt/6432/overview)

**Comment by zanderso** [comment]
Two of these are SIGSEGV crashers in `TaskRunnerCheckerTests.FailsTheCheckIfOnDifferentTaskRunner` in the call to `MessageLoopDarwin::Terminate()` from here:

https://github.com/flutter/engine/blob/2962099077b36704071802ea5595f4a016a1c214/fml/memory/task_runner_checker_unittest.cc#L40

Looking at the git blame, it looks like @cyanglaz may be familiar with this area. Any idea why this test might be crashing?

**Comment by chinmaygarde** [comment]
For the one issue where we have a backtrace, we can try to scribble to TLS slot on terminate to see if the look is getting terminated by someone else. But other than that, the test is extremely simple so I am not able to tell how this could fail. We will need to reproduce the error locally.

**Comment by chinmaygarde** [comment]
The linked PR should fix this.
