### ISSUE TITLE
locale error

### ISSUE THREAD

**Issue by YongjunChoi** [flutter/flutter#10650]
## Steps to Reproduce
I added two dependencies and run package get..

dependencies:
  flutter:
    sdk: flutter
  **google_sign_in: "^0.0.2"
  firebase_auth: "^0.0.2+1"**

## Logs
/Users/yongjun/dev_sdk/flutter/bin/flutter --no-color packages get
Running "flutter packages get" in sotong...

Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Crash report sent (report ID: f21d61ac58000000)
Crash report written to /Users/yongjun/git/flutter/sotong/flutter_04.log;
please let us know at https://github.com/flutter/flutter/issues.
Process finished with exit code 1

## Flutter Doctor

[✓] Flutter (on Mac OS X 10.12.5 16F73, locale ko-KR, channel alpha)
    • Flutter at /Users/yongjun/dev_sdk/flutter
    • Framework revision e2f54df5ab (10 days ago), 2017-06-02 10:43:54 -0700
    • Engine revision 1f2aa07571
    • Tools Dart version 1.24.0-dev.3.0

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.0)
    • Android SDK at /Users/yongjun/Library/Android/sdk
    • Platform android-26, build-tools 26.0.0
    • ANDROID_HOME = /Users/yongjun/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.3.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3.3, Build version 8E3004b
    • ios-deploy 1.9.1
    • CocoaPods version 1.0.1

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Gradle version 3.2
    • Java version: OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.1.4)
    • Dart plugin version 171.4694.29
    • Flutter plugin version 14.0

[✓] Connected devices
    • Nexus 6P • ENU7N15B12009629 • android-arm • Android 7.1.2 (API 25)

**Comment by eseidelGoogle** [comment]
Crash log:
```
	at Intl._throwLocaleError	(package:intl/intl.dart:229 )
at Intl.verifiedLocale	(package:intl/intl.dart:223 )
at Intl.verifiedLocale	(package:intl/intl.dart:208 )
at kMillisecondsFormat	(package:flutter_tools/src/base/utils.dart:92 )
at kMillisecondsFormat	(package:flutter_tools/src/base/utils.dart:92 )
at getElapsedAsMilliseconds	(package:flutter_tools/src/base/utils.dart:100 )
at FlutterCommand.run	(package:flutter_tools/src/runner/flutter_command.dart:162 )
at <asynchronous gap>	(async )
at CommandRunner.runCommand	(package:args/command_runner.dart:194 )
at <asynchronous gap>	(async )
at FlutterCommandRunner.runCommand	(package:flutter_tools/src/runner/flutter_command_runner.dart:262 )
at <asynchronous gap>	(async )
at CommandRunner.run.<fn>	(package:args/command_runner.dart:109 )
at CommandRunner.run	(package:args/command_runner.dart:109 )
at FlutterCommandRunner.run	(package:flutter_tools/src/runner/flutter_command_runner.dart:157 )
at run.<fn>	(package:flutter_tools/executable.dart:142 )
at <asynchronous gap>	(async )
at AppContext._run	(package:flutter_tools/src/base/context.dart:76 )
at <asynchronous gap>	(async )
at AppContext.runInZone.<fn>	(package:flutter_tools/src/base/context.dart:66 )
at runZoned	(dart:async )
at AppContext.runInZone	(package:flutter_tools/src/base/context.dart:65 )
at run	(package:flutter_tools/executable.dart:114 )
at <asynchronous gap>	(async )
at main	(package:flutter_tools/executable.dart:67 )
at <asynchronous gap>	(async )
at main	(../../../dev_sdk/flutter/packages/flutter_tools/bin/flutter_tools.dart:16 )
```

**Comment by eseidelGoogle** [comment]
It seems we crash when locale is ko-KR ?  FYI @tvolkert @alan-knight

**Comment by alan-knight** [comment]
It would be particularly useful to know what locale is actually being requested. Unless something in flutter explicitly sets it, the system locale isn't actually set automatically.

**Comment by YongjunChoi** [comment]
Hi..
Yes. ko_KR is right locale ..
But I guess when after I open or create project With androidStudio .. then
my project has locale error..
I don't know where It set..

2017. 6. 13. 오후 4:08에 "Eric Seidel" <notifications@github.com>님이 작성:

It seems we crash when locale is ko-KR ? FYI @tvolkert
<https://github.com/tvolkert> @alan-knight <https://github.com/alan-knight>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/flutter/flutter/issues/10650#issuecomment-308019202>,
or mute the thread

**Comment by eseidelGoogle** [comment]
This appears to be the line of code:
https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/base/utils.dart#L99

**Comment by alan-knight** [comment]
Yes, the line of code is clear. But a trivial example that sets Intl.defaultLocale and then creates a NumberFormat and formats something works fine for me. But I'm not doing it in a Flutter context, and it's not clear what the rest of the environment is, or even what the actual error message is. Did it fail to find ko-KR? Or is it looking for something different? Is number_symbols_data_local.dart not visible for some reason?

**Comment by eseidelGoogle** [comment]
I changed my mac to korean and restarted Terminal (which then showed up in korean), but was not able to get `flutter doctor` to detect the language as korean.  I didn't try restarting, but may need to.

@YongjunChoi could you look at the output of `env` and see if you have anything set in your environment which seems specific to korean?  LC_ALL, LANG, etc.

env | grep ko-KR
might show if you do?

**Comment by YongjunChoi** [comment]
below is my mac locale.. 
choeyongjun-ui-MacBook-Pro:sotong yongjun$ env|grep -e ko_KR
LANG=ko_KR.UTF-8
I don't know where this comes..
[ArgumentError: Invalid argument(s): Invalid locale **'re_KR'**]

**Comment by eseidelGoogle** [comment]
It looks like this is the code which package:intl uses to read the locale:
https://github.com/dart-lang/intl/blob/master/lib/intl_standalone.dart#L31

It looks like flutter_tools prints out a different local in the doctor output:
https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/doctor.dart#L233

**Comment by eseidelGoogle** [comment]
It looks like this is the implementation for platform.localeName on Mac:
https://github.com/dart-lang/sdk/blob/bc923bed16fb87c44cdea43c9b90b8d1266ff29f/runtime/bin/platform_macos.cc#L148 Very recent code.

**Comment by YongjunChoi** [comment]
I found that
on mac console I's ok..
but Indellij IEDA it has problem [Package get..]
I guess maybe it is ieda issue...

/Users/yongjun/dev_sdk/flutter/bin/flutter --no-color packages get
Running "flutter packages get" in sotong...
===========================================================
Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Crash report sent (report ID: 5b0d916e40000000)
Crash report written to /Users/yongjun/git/flutter/sotong/flutter_01.log;
please let us know at https://github.com/flutter/flutter/issues.
Process finished with exit code 1

**Comment by alan-knight** [comment]
I have a number of interesting theories about what might be going wrong (e.g. I'm going to take a wild guess that the peculiar language code "re" is due to incorrectly parsing "Korean" somewhere) but I think the correct thing to do now that 1.24 is stable is to land the CL to make Intl rely on the platform.localeName API and publish a version.

**Comment by alan-knight** [comment]
I have published a 0.15.1 Intl which uses the platform.locale API.

**Comment by tvolkert** [comment]
@alan-knight if I create a blank project with the following `pubspec.yaml`:

```
name: foo
version: 0.0.1

dependencies:
  intl: 0.15.1

environment:
  sdk: '>=1.19.0 <2.0.0'
```

... I get the following error:

```
$ pub upgrade
Resolving dependencies... 
Package intl has no versions that match 0.15.1 derived from:
- foo depends on version 0.15.1
```

**Comment by devoncarew** [comment]
Looks like 0.15.1 requires at least a 1.24.0 dart sdk (https://github.com/dart-lang/intl/blob/master/pubspec.yaml#L7), but flutter is still on a dev version of 1.24.0. Possibly time to rev flutter to the latest dart sdk?

**Comment by tvolkert** [comment]
Current plan is to bump Flutter Dart SDK version to 1.24.0, then bump `package:intl` to 0.15.1

**Comment by tvolkert** [comment]
@YongjunChoi can you try again against the master branch, which uses the most recent version of `package:intl`?

**Comment by Hixie** [comment]
We're going to close this since we believe we fixed it. Please open a new bug if you still see this. Thanks.
