### ISSUE TITLE
Failing to archive the app with xCode: path_provider/PathProviderPlugin.h file not found

### ISSUE THREAD

**Issue by lasiboy** [flutter/flutter#10654]
## Steps to Reproduce
add plugin path_provider in pubspec.yaml:
path_provider: "^0.2.1+1" 

build with Flutter:
$ flutter build ios

Open xCode and try to archive the app.

--> the following error occurs in the GeneratedPluginRegistrant.m file (in build/ios) : 
'path_provider/PathProviderPlugin.h' file not found.

Note:
I am able to install the app on my iPhone using 
$flutter install

Did I miss something before the step "Archive"?
Thanks!

**Comment by eseidelGoogle** [comment]
Have we tested making releases with plugins @mit-mit, @cbracken?

**Comment by mit-mit** [comment]
@jakobr-google can you take a quick look at this, please?

**Comment by mit-mit** [comment]
I speculate that the following is related:

```
flutter create test1
cd test1
nano pubspec.yaml + add path_provider: "^0.2.1+1"
flutter build ios
open ios/Runner.xcodeproj/
```

Hit build button =>

```
ld: warning: directory not found for option '-L/Users/mit/tmp/iostest/build/ios/Debug-iphoneos/path_provider'
```

**Comment by jakobr-google** [comment]
Always open `ios/Runner.xcworkspace`, otherwise Xcode won't be able to see the plugins (or other pods).

I haven't been able to reproduce the original issue yet. Archiving works fine for me on a new project with path_provider added.

**Comment by mit-mit** [comment]
Ops, sorry, user error 42 :-|. (I really look forward to https://github.com/flutter/flutter-intellij/issues/880 shipping).

@lasiboy the following steps now succeed for both @jakobr-google and myself:

```
flutter create test1
cd test1
nano pubspec.yaml + add path_provider: "^0.2.1+1"
flutter build ios
open ios/Runner. xcworkspace/
```

Once Xcode opens, hit Product > Archive.

Do those not work for you? What are the exact steps that fail for you?

**Comment by lasiboy** [comment]
I was doing the same mistake, opening Runner.xcodeproj and not Runner.xcworkspace...
Everything works opening the correct file. 

Thanks a lot, you saved my week!

**Comment by jakobr-google** [comment]
I was able to reproduce the original issue, by adding `use_frameworks!` to `ios/Podfile`. If I then open `ios/Runner.xcodeproj` and try to archive, I get the include error (instead of the linker error we get without use_frameworks).

Archiving works fine if I open `ios/Runner.xcworkspace`.

**Comment by mit-mit** [comment]
Great to hear @lasiboy !

**Comment by tendant** [comment]
Having similar error. 

Failed on step: "flutter build ios"

$ flutter build ios

Running "flutter packages get" in test1...
Building com.yourcompany.test1 for device (ios-release)...
Found saved certificate choice "iPhone Developer: lei@wishlife.com (4F44X3KPL2)". To clear, use "flutter config".
Signing iOS app for device deployment using developer identity: "iPhone Developer: lei@wishlife.com (4F44X3KPL2)"
Running pod install...
CocoaPods' output:
↳
      Preparing

    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (`arm64`)

    Fetching external sources
    -> Fetching podspec for `Flutter` from `/Users/l/workspace/flutter/flutter/bin/cache/artifacts/engine/ios-release`
    -> Fetching podspec for `path_provider` from `/Users/l/.pub-cache/hosted/pub.dartlang.org/path_provider-0.2.1+1/ios`

    Resolving dependencies of `Podfile`

    Comparing resolved specification to the sandbox manifest
      A Flutter
      A path_provider

    Downloading dependencies

    -> Installing Flutter (1.0.0)

    -> Installing path_provider (0.0.1)
      - Running pre install hooks

    Generating Pods project
      - Creating Pods project
      - Adding source files to Pods project
      - Adding frameworks to Pods project
      - Adding libraries to Pods project
      - Adding resources to Pods project
      - Linking headers
      - Installing targets
        - Installing target `path_provider` iOS 8.0
        - Installing target `Pods-Runner` iOS 8.0
Error running pod install

**Comment by tendant** [comment]
I am testing this with Xcode Version 9.0 (9A235).

**Comment by tendant** [comment]
Figured out the issue, the cocoapods version is too old 1.0.1. For some reason, even when I installed latest version 1.3.1, the default pod still linked to old version. 

Once I update the pod link to latest version, this problem is gone now.

**Comment by suesitran** [comment]
I'm still seeing this issue with i try to include path_provider.

My pm is at version 1.4.0

**Comment by thphuc** [comment]
I am getting the same issue with cocoapods 1.3.0

**Comment by zinwalin** [comment]
After update Podfile in ios folder with following content, it works well.


# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

def parse_KV_file(file, separator='=')
  file_abs_path = File.expand_path(file)
  if !File.exists? file_abs_path
    return [];
  end
  pods_ary = []
  skip_line_start_symbols = ["#", "/"]
  File.foreach(file_abs_path) { |line|
      next if skip_line_start_symbols.any? { |symbol| line =~ /^\s*#{symbol}/ }
      plugin = line.split(pattern=separator)
      if plugin.length == 2
        podname = plugin[0].strip()
        path = plugin[1].strip()
        podpath = File.expand_path("#{path}", file_abs_path)
        pods_ary.push({:name => podname, :path => podpath});
      else
        puts "Invalid plugin specification: #{line}"
      end
  }
  return pods_ary
end

target 'Runner' do
  # Prepare symlinks folder. We use symlinks to avoid having Podfile.lock
  # referring to absolute paths on developers' machines.
  system('rm -rf Pods/.symlinks')
  system('mkdir -p Pods/.symlinks/plugins')

  # Flutter Pods
  generated_xcode_build_settings = parse_KV_file('./Flutter/Generated.xcconfig')
  if generated_xcode_build_settings.empty?
    puts "Generated.xcconfig must exist. If you're running pod install manually, make sure flutter packages get is executed first."
  end
  generated_xcode_build_settings.map { |p|
    if p[:name] == 'FLUTTER_FRAMEWORK_DIR'
      symlink = File.join('Pods', '.symlinks', 'flutter')
      File.symlink(File.dirname(p[:path]), symlink)
      pod 'Flutter', :path => File.join(symlink, File.basename(p[:path]))
    end
  }

  # Plugin Pods
  plugin_pods = parse_KV_file('../.flutter-plugins')
  plugin_pods.map { |p|
    symlink = File.join('Pods', '.symlinks', 'plugins', p[:name])
    File.symlink(p[:path], symlink)
    pod p[:name], :path => File.join(symlink, 'ios')
  }
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end

**Comment by kavinda1995** [comment]
@zinwalin thanks man. This solution fixed my problem. Furthermore i have switched the xcode's build system to legacy.

**Comment by braysonjohn148** [comment]
Am also getting the same error while running my app on IOS...help please
![Screenshot 2020-03-10 at 11 17 25](https://user-images.githubusercontent.com/41685357/76292775-df6e1d80-62c0-11ea-9bcd-15b5714cfe47.png)

**Comment by kavinda1995** [comment]
I fixed this by running

1) flutter clean
2) run pod install inside ios folder

**Comment by junkai-li** [comment]
![0F4BD4B7-65F4-438A-8A4F-501ABE9B37FC](https://user-images.githubusercontent.com/57887866/76719153-dd4e0800-6773-11ea-9ec8-40054f287121.png)

**Comment by junkai-li** [comment]
我也遇到这个问题 打包和调试都没有问题 唯独使用xcode存档出现这个问题
