### ISSUE TITLE
_ErrorDiagnostic.toString() prints "Instance of"

### ISSUE THREAD

**Issue by mockturtl** [flutter/flutter#106504]
A helper method in the Crashlytics plugin [`recordFlutterError(FlutterErrorDetails)`](https://github.com/firebase/flutterfire/blob/master/packages/firebase_crashlytics/firebase_crashlytics/lib/src/firebase_crashlytics.dart#L134) passes the `context` of its argument as `dynamic reason`, where `toString` is called ([#L125](https://github.com/firebase/flutterfire/blob/master/packages/firebase_crashlytics/firebase_crashlytics/lib/src/firebase_crashlytics.dart#L125)).

I believe the bug is in [`assertions.dart`](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/foundation/assertions.dart#L470), where the various `_ErrorDiagnostic` subclasses spend some effort at nice formatting.

In the screenshot below (Firebase Crashlytics dashboard), I expect to see the message value, instead of _Instance of 'ErrorDescription'._

![Screenshot from 2022-06-13 18-46-36](https://user-images.githubusercontent.com/705804/175350652-20de283b-eee6-47ea-b628-c3d3bddd34a4.jpg)

Flutter version: 3.0.2 stable

**Comment by mockturtl** [comment]
Related: #105712

**Comment by goderbauer** [comment]
My understanding is that the framework's `_ErrorDiagnostic` class needs a proper `toString` method.

**Comment by MattyBoy4444** [comment]
Any progress on this? It sure we be nice to get more information.

**Comment by Danau5tin** [comment]
I have raised a simple PR here: https://github.com/flutter/flutter/pull/118263
This is my first time contributing, so if there is something which I have not done quite right then please let me know 😊
If my solution is too simple and I am missing something, I'd appreciate some small guidance along the correct path!
