### ISSUE TITLE
Very slow keyboard on iOS

### ISSUE THREAD

**Issue by vixez** [flutter/flutter#106550]
## Details

Hello,

We have an app on the store, currently on Flutter 3.0.0, which seems to have severe keyboard lag on iOS.
I'm not sure if it is an iOS issue, or an app issue. Sometimes restarting the app solves the issue temporarily.
I have attached videos showing the issue.

Does anyone else have this issue, or knows what could cause it?

Thanks

**Target Platform:** iOS
**Target OS version/browser:** 15
**Devices:** iPhone 13

<details>
<summary>Videos</summary>

https://user-images.githubusercontent.com/3032294/175525574-ce657962-5c8c-41cb-81a6-74a3f61433fc.mp4

https://user-images.githubusercontent.com/3032294/175525586-4f840d80-18a3-4ca1-b589-67e44b3bc1b9.MP4

</details>

**Comment by Marcelo-Petrucelli** [comment]
That's odd. I've just published an iOS app on 3.0.0 and was not facing such issue.

I'm kindda new on Flutter, but my application extensivelly uses the keyboard... Have you tried it on another iOS device? Heve you tried it on MacOS? Are you doing something that forces the layout to be rebuild every frame/time?

I had similar problems with other widgets when I accidentally managed to force redraws/rebuilds every frame, or even setStates that I didn't manage correctly. Could this also be your issue?

**Comment by exaby73** [comment]
Hello @vixez. Are you running code in `onChange` that might be blocking the thread? Also, please provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) so that we can verify this issue.
