### ISSUE TITLE
video_player package on IOS exeption src whit spaces

### ISSUE THREAD

**Issue by lcyper** [flutter/flutter#106506]
video_player package on IOS platafor if you are traying to reproduce a video that have spaces on is name the app trow an exeption

## Steps to Reproduce

```
      // mediaItem.src = "my file with spaces on the name.mp4"
     
      // fix for ios when the file have spaces
     // if (defaultTargetPlatform == TargetPlatform.iOS && mediaItem.src.contains(' ')) {
     // mediaItem.src = mediaItem.src.replaceAll(' ', '%20'));
    //  }

      final _videoPlayerController = VideoPlayerController.file(mediaItem.src);
```

**Expected results:** 
- play the video

**Actual results:** 
- trow an error

**Comment by stuartmorgan** [comment]
Duplicate of https://github.com/flutter/flutter/issues/105950

**Comment by stuartmorgan** [comment]
The specific cases where invalid URLs fail differ by platform, but the root cause is that the URL isn't being constructed correctly.
