### ISSUE TITLE
Weird scroll behavior in Tabs section of gallery (NestedScrollView)

### ISSUE THREAD

**Issue by KevinTheGray** [flutter/flutter#10658]
In the tabs section of the gallery, the beach ball can get in a state where it sits slightly under the header.  The resting state should be sitting fully underneath the header.

Steps to Reproduce

- Build and install latest Flutter Gallery from the repo, enter "Tabs" section,
- scroll "Left" section to the bottom,
- select to "Right" tab,
- Notice that the beach ball is scrolled under the header a little bit, and will sit there.

<img width="369" alt="screen shot 2017-06-13 at 12 02 53 pm" src="https://user-images.githubusercontent.com/9346834/27092131-5d79b4c4-5030-11e7-9305-0bf7f51e7f98.png">

Flutter Doctor

[✓] Flutter (on Mac OS X 10.12.4 16E195, locale en-US, channel master)
    • Flutter at /Users/KG/Developer/Flutter/flutter
    • Framework revision 37e32d5aee (21 hours ago), 2017-06-12 12:23:13 -0700
    • Engine revision ffe8181ffe
    • Tools Dart version 1.24.0-dev.6.7

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at /Users/KG/Library/Android/sdk
    • Platform android-25, build-tools 25.0.3
    • ANDROID_HOME = /Users/KG/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.3.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3.3, Build version 8E3004b
    • ios-deploy 1.9.1
    • CocoaPods version 1.2.1

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Gradle version 3.2
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.1.4)
    • Flutter plugin version 14.0
    • Dart plugin version 171.4694.29

**Comment by HansMuller** [comment]
This is likely due to NestedScollViews were not being updated in https://github.com/flutter/flutter/pull/10590

**Comment by Hixie** [comment]
This is as designed, though I forget exactly why.

**Comment by HansMuller** [comment]
> This is likely due to NestedScollViews were not being updated in https://github.com/flutter/flutter/pull/10590

This particular behavior is not due to the new scheme for managing page storage ids. It is, as Ian pointed out, a feature of the way nested scroll views work.

**Comment by lukef** [comment]
This might be a feature of the nested scrollview but it leaves the application broken. what would be the workaround here?

**Comment by Hixie** [comment]
It's not clear to me that this is "broken" (the user did scroll to that position), but yeah, we should improve it. Is this blocking you?

**Comment by KevinTheGray** [comment]
In my opinion, it's broken for three reasons.  

1. In my reproduction steps, I never scrolled that right list.  Why would scrolling this left list move the right one?  If that's the intended behavior for the gallery app, fine, but it's odd and should be easily configurable.

2. Why can this cell rest slightly under the header?  Normal behavior would be that the cell would rest completely visible and under the header.  Yes you can push it up and hide it, but ultimately it should rest there.  

3. The cell shouldn't be scrollable at all.  There isn't enough content to justify it scrolling.  You should be able to push/pull it around on iOS, but eventually it always goes back to its position.

It's only blocking if there isn't a work around that will allow the behavior I expect.

**Comment by Hixie** [comment]
If you scroll the page half-way so that you can see both lists, and then scroll it, you'll see why the behaviour is as it is. The appbar itself is scrollable, and it covers both sublists, so when you scroll it, they both scroll.

If you want the second side to not scroll at all you can build it without a listview (NestedScrollView gives you independent control of each tab). You can also duplicate NestedScrollView's behaviour to do whatever precise logic you want.

If you want the tabs to be entirely independent, and for scrolling the appbar to not scroll the sublists, then it's much easier -- just use a regular AppBar with a TabBar/TabBarView and don't use NestedScrollView at all.

**Comment by lukef** [comment]
I'm not sure that this is being communicated properly. I'm happy to jump on a VC if this doesn't make sense. In the attached screenshot, the list has 1 item. There is no acceptable use case where that list will "settle" in that position because you cannot scroll to that position. You could definitely see this state on iOS because of the "overscroll" but it should never "rest" in this position. 

What @KevinTheGray is seeing is that Flutter is setting the scroll position to a positive scroll position incorrectly when it should be at 0,0 because the list doesn't scroll.

**Comment by Hixie** [comment]
It does scroll. Try it. :-) The AppBar in that example is an expanding AppBar. It's the same AppBar as when the Left tab is shown. If you scroll sideways such that you can simultaneously see both lists, it becomes obvious why you need to be able to shrink and expand that AppBar -- it's what happens when you scroll the left list, which has enough content to scroll.

If you don't want the AppBar to scroll, then it's trivial to avoid this issue, just don't use a NestedScrollView. Being able to do this is basically the only reason NestedScrollView exists. :-)

**Comment by KevinTheGray** [comment]
The AppBar scrolling is fine, it is abundantly clear why each list would scroll the same AppBar, because they share the same same AppBar.  What isn't ok is to have a a tabbed list of items, and for them to behave like this:

https://www.youtube.com/watch?v=7zgjGppzsQE

The right content becomes hidden under the header, because it is resting there.  If a user saw this, they would assume that the right side had no content.

**Comment by Hixie** [comment]
I totally agree that it's suboptimal and that we should improve it. Is it blocking you? (i.e. do you intend to ship an app with a NestedScrollView where one of the lists may be short but will not always be short such that you require it to be a ListView?)

**Comment by KevinTheGray** [comment]
It's not blocking, we should be ok with the current functionality

**Comment by nonameden** [comment]
It is the same what I faced, issue is NestedScrollView does not respect minIntend for all headers from `headerSliverBuilder` and scroll inner scroll under headers.

**Comment by collinjackson** [comment]
Here's another [test case](https://gist.github.com/collinjackson/2bc6697d31e6b94ada330ef5e818a36f) that triggers the issue.

![untitled2](https://user-images.githubusercontent.com/394889/33858228-b8930e5a-de83-11e7-9ded-bd96261608ec.gif)

**Comment by Hixie** [comment]
I'm looking at this one now.

**Comment by Hixie** [comment]
My current plan is to look at creating a sliver that goes in the outer viewport before the final sliver, which has zero scroll extent and zero layout extent but remembers the overlap extent, and another sliver that goes in the inner viewport, before the listview's contents, which has a scroll extent equal to the remembered overlap extent. Or something. What I described here doesn't quite make sense.

**Comment by Hixie** [comment]
idea: Nested Scroll View Overlay Absorber, with sliver child, passes geometry through but converts all layout extent into overlap, passes the difference to a Value Notifier. Nested Scroll View Overlay Injector injects layout extent equal to a Value Notifier.

**Comment by Hixie** [comment]
I'm on a path which I think will lead to a solution, though at the moment I've actually just made item 0 _always_ be under the tabs, so we're not quite done yet.

**Comment by Hixie** [comment]
I have a solution, just need to write tests and docs.

**Comment by Ali-Azmoud** [comment]
after about 1.5 year this is not fixed yet
I have exactly the same behavior ( [this comment](https://github.com/flutter/flutter/issues/10658#issue-235606235)


and this is my `Flutter Doctor` information

```
[√] Flutter (Channel stable, v1.0.0, on Microsoft Windows [Version 10.0.17763.194], locale en-US)
    • Flutter version 1.0.0 at C:\flutter
    • Framework revision 5391447fae (6 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[!] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:\Users\Ali\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Android Studio (version 3.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[√] VS Code (version 1.30.1)
    • VS Code at C:\Users\Ali\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 2.21.1

[!] Connected device
    ! No devices available
```

**Comment by bnamora** [comment]
@Ali-Azmoud It is fixed. Use SliverOverlap widget. See the [tab demo](https://github.com/flutter/flutter/blob/master/examples/flutter_gallery/lib/demo/material/tabs_demo.dart)

**Comment by louisdeb** [comment]
I must say it's slightly odd that not returning to a no overlap rest position isn't the default behaviour. This fix makes life harder, as, say, a `ListView` has to converted to a lower level `Sliver` implementation before the fix can be employed.

**Comment by 0biWanKenobi** [comment]
> @Ali-Azmoud It is fixed. Use SliverOverlap widget. See the [tab demo](https://github.com/flutter/flutter/blob/master/examples/flutter_gallery/lib/demo/material/tabs_demo.dart)

404 not found
