### ISSUE TITLE
Make DateTime parameters named & optional 

### ISSUE THREAD

**Issue by M97Chahboun** [flutter/flutter#106575]
## Proposal
I suggest to make DateTime parameters named & optional and set now as default for use it easy
## Use case
I want use it for convert seconds to seconds, minutes and hours
**Actual**
```
DateTime now = DateTime.now();
DateTime currentDuration = DateTime(now.year, now.month, now.day, 0, 0, secondsForConvertToUnites);
seconds = currentDuration.second;
minutes = currentDuration.minute;
hours = currentDuration.hour;
```
**Excpect**
```
DateTime currentDuration = DateTime(seconds: secondsForConvertToUnites);
seconds = currentDuration.second;
minutes = currentDuration.minute;
hours = currentDuration.hour;
```

I will implement it if you accept this proposal.
Thank you/

**Comment by danagbemava-nc** [comment]
Hi @M97Chahboun, the `DateTime` class is from `dart` itself and not from flutter. You'll need to file this issue on their repo over on https://github.com/dart-lang/sdk/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc. 

Closing from here as this proposal would be better suited in the dart repo. 

Thank you
