### ISSUE TITLE
Engine CI should build every commit

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#106503]
It looks like a couple of commits got skipped:
<img width="1241" alt="Screen Shot 2022-06-23 at 9 59 41 AM" src="https://user-images.githubusercontent.com/6343103/175354356-30bb98b5-dc74-49b8-84ed-3bd8fe23016f.png">

**Comment by keyonghan** [comment]
This is due to API failures (https://github.com/flutter/flutter/issues/106429).
Have manually triggered builds on those missing two commits.
