### ISSUE TITLE
CIPD access for builders

### ISSUE THREAD

**Issue by drewroengoogle** [flutter/flutter#106577]
While creating a recipe for automatically uploading cosign/sget to CIPD, I am running into a CIPD access issue with the builder accounts:
```
CIPD('register flutter/tools/cosign/${platform}') failed with:
"user:flutter-try-builder@chops-service-accounts.iam.gserviceaccount.com" has no required WRITER role in
prefix "flutter/tools/cosign/linux-amd64", run cipd auth-login to login or relogin
```

I believe the builder accounts need access to the WRITER role for `flutter/tools/cosign` and `flutter/tools/sget` in order to be able to automatically upload these packages. Currently I am only using the try builders but eventually we will need them in prod as well. Let me know if there is any more information I need to provide!

**Comment by godofredoc** [comment]
@keyonghan which service account are we using for cocoon device doctor cipd packages?

@drewroengoogle can you please share a link to the failure?

**Comment by drewroengoogle** [comment]
Here is a build that I ran from a local configuration: https://ci.chromium.org/raw/build/logs.chromium.org/flutter/led/drewroen_google.com/201dde8e7676d49fe9da0719b6e023df1ef238ef0a89be2afabc9a8c916c1cc9/+/build.proto?server=chromium-swarm.appspot.com

**Comment by keyonghan** [comment]
Device doctor is using `flutter-try-builder@chops-service-accounts.iam.gserviceaccount.com` as well.
I can see `flutter-try-builder@chops-service-accounts.iam.gserviceaccount.com` is in `project-flutter-cipd-writers`.
I also see 
```
Writer | flutter-try-builder@chops-service-accounts.iam.gserviceaccount.com via flutter/tools/cosign
```
There is a package uploaded 1 min ago. Is it a success from try builder account?

**Comment by drewroengoogle** [comment]
Godofredo just added write permissions a couple of minutes ago, and after doing that it was successful
