### ISSUE TITLE
When setting the color of ProgressBar, the animation of ProgressBar will not work properly.

### ISSUE THREAD

**Issue by Waylon-Firework** [flutter/flutter#106644]
Wrap the native android code with Fultter. When we set the inderterminateTint in the progressbar component, android:indeterminateTint="#F84D5F", the animation will not work properly.

```
    <ProgressBar
        android:layout_width="32dp"
        android:layout_height="32dp"
        app:layout_constraintTop_toTopOf="parent"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        android:indeterminate="true"
        android:indeterminateTint="#F84D5F"
        android:id="@+id/progress_bar"
        android:visibility="visible"
        />
```

**Comment by Waylon-Firework** [comment]
<img width="454" alt="image" src="https://user-images.githubusercontent.com/95599645/175859606-e60a93c7-03c5-4862-8adb-f75cf5e45e0f.png">

**Comment by AscEmon** [comment]
You will globally set the progress bar in theme data.  Please checkout this code.
```
 theme: ThemeData(
        progressIndicatorTheme: ProgressIndicatorThemeData(color: Colors.green),)
```

**Comment by exaby73** [comment]
Hi @Waylon-Firework, please provide a [minimal, reproducible example][1] and the output of `flutter doctor -v` as well as `flutter run -v`.

[1]: https://stackoverflow.com/help/minimal-reproducible-example
