### ISSUE TITLE
[Documentation] Typo in the documentation for `MenuItem.onClose`

### ISSUE THREAD

**Issue by navaronbracke** [flutter/flutter#106617]
The docs for `MenuItem.onClose` have a typo where the wrong value is mentioned.

`Returns a callback, if any, to be invoked if the platform menu receives a "Menu.opened" method call from the platform for this item.`

It should be `Menu.closed` per the docs in SystemChannels.
`Menu.closed: Called when a submenu is closed, along with the unique ID of the submenu.`

https://api.flutter.dev/flutter/widgets/MenuItem/onClose.html
https://api.flutter.dev/flutter/services/SystemChannels/menu-constant.html

**Comment by goderbauer** [comment]
Thanks for the report. Looks like this is already fixed on master: https://master-api.flutter.dev/flutter/widgets/MenuItem/onClose.html
