### ISSUE TITLE
Make Widgets automatically select Cupertino or MTV style

### ISSUE THREAD

**Issue by vlidholt** [flutter/flutter#10666]
Everywhere in my code where I need to use a `Switch` I currently need to check if I'm on iOS and in that case use a `CupertinoSwitch`.

It would be pretty sweet if I could just use a `Switch` and it would automatically use a `CupertinoSwitch` or a `MountainviewSwitch` depending on the platform. Basically the `Switch` class would in this case be a wrapper for the platform dependent switches. In the case that I want the component to look the same on both platforms I could just choose to use the platform dependent version.

It would be great if this worked across all widgets, including page routes, etc. Right now, some widgets and behaviors are different across platforms and some are not. I would love to be able to easily choose if I want a specific widget to be the same on both platforms or use the platform specific ones.

**Comment by Hixie** [comment]
This is the plan, yes.

cc @xster

**Comment by sethladd** [comment]
I wonder if this would be a package, in order to experiment first? Or, we want to go straight to the core framework?

**Comment by xster** [comment]
Duping into #8410
