### ISSUE TITLE
`PopupRoute`: Document dismiss action behavior and add an example

### ISSUE THREAD

**Issue by TahaTesser** [flutter/flutter#106650]
Dismiss action behavior added in https://github.com/flutter/flutter/pull/59310  is not documented. 

When `PopupRoute` is on the screen, pressing the `ESC` key dismisses the popup route. This is not mentioned in the docs, only testing the code reveals this behavior.

related https://github.com/flutter/flutter/pull/106186

**Comment by gspencergoog** [comment]
@TahaTesser is this issue closed now that the PR landed?

**Comment by TahaTesser** [comment]
@gspencergoog 

This is not fixed, while fixing the Drawer dismiss action and updating its doc, I realized `PopupRoute` need similar documentation and more.

**Comment by TahaTesser** [comment]
https://github.com/flutter/flutter/pull/106948 landed
