### ISSUE TITLE
Autosubmit bot is repeatedly pinging PR labeled as autosubmit

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#106684]
See https://github.com/flutter/flutter/pull/106624

A previous version of the bot managed the state around this by removing the label once it added a message, so that it would not re-consider PRs until the label had been added back. It seems like that logic has either regressed or been removed.

/cc @godofredoc 

I'm giving this a relatively high priority since it's spamming new contributors and may discourage them from contributing.

**Comment by keyonghan** [comment]
This is https://github.com/flutter/flutter/issues/106487.
An attempt fix is in today's version.
In addition to removing label when validation fails, there are two more issues:
1) Validation may return `empty` comment message, which is not allowed when posting github comment
2) Messaged are being handled in async manner in a Future list, seems some interaction between different messages. Maybe some `await` keyword missing.

**Comment by keyonghan** [comment]
Removing label with correct message is validated: https://github.com/flutter/cocoon/pull/1911#issuecomment-1167851954

**Comment by keyonghan** [comment]
Fix is in, and the issue is fixed. See https://github.com/flutter/engine/pull/34335, where correct comment was posted and label was removed. Also validated message from pub-sub was acked as well.

Please reopen if you see the issue again.
