### ISSUE TITLE
Using Scene.toGpuImage seems to aggressively trigger GC during frame workload

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#106698]
When running through some benchmarks with the timeline enabled, I've noticed that pretty much every call to Scene.toGpuImage results in a GC:

![Flutter DevTools - Google Chrome 6_27_2022 1_25_58 PM](https://user-images.githubusercontent.com/8975114/176034995-b9c5b451-fb3e-4198-9a36-aa291e88b7a2.png)

![Flutter DevTools - Google Chrome 6_27_2022 1_34_24 PM](https://user-images.githubusercontent.com/8975114/176035001-2c609ed8-1093-4325-b089-f313735d691b.png)

According to @dnfield this is expected, because Dart may need to reduce PSS size before allocating the large texture. 

(The ui.Image created by Scene.toGpuImage and Picture.toImage reports an estimation of its external size as `4 * width * height` to Dart: https://github.com/flutter/engine/pull/33736/files#diff-44a029b47e68b6b14a22356aef963e5f11bbd67e906c4d38fdef67153ba211a2R46-R52)

Generally triggering a GC during a frame workload is bad.

**Comment by jonahwilliams** [comment]
The first one takes 2-3 ms. But then we run another one in the same frame, which is another 1ms. These are probably a bit slower than they would otherwise be due to profile mode, but its also running on a pixel 6 which is a fairly high end Android hpone.

**Comment by fzyzcjy** [comment]
So, if I understand correctly, `toGpuImage` will contribute `width * height * 4` bytes to *the GPU memory* instead of *the CPU memory* as the name suggests? On the other hand, GC is managing the heap on *CPU*, so the memory pressure from toGpuImage is only a fake signal to GC that makes it confused.

And what about manual memory management? Like (manual) reference counting, and only delete the data after last `dispose()` is called. Just like what we do with `Layer` - we do reference counting via `LayerHandle`.

**Comment by dnfield** [comment]
> So, if I understand correctly, `toGpuImage` will contribute `width * height * 4` bytes to _the GPU memory_ instead of _the CPU memory_ as the name suggests?

Yes, but there is no guarantee that GPU and CPU memory are actually physically separated.

> On the other hand, GC is managing the heap on _CPU_, so the memory pressure from toGpuImage is only a fake signal to GC that makes it confused.

Not quite. In the end, all of this is shared as part of the PSS accounted against your process, and if you're on an OS that kills you for using too much memory it may well kill you regardless of whether that memory is being used for graphics or "native heap."  More specifically: Android and iOS will definitely kill you for using too much of this, mobile devices in general don't have dedicated graphics memory banks.

> And what about manual memory management? Like (manual) reference counting, and only delete the data after last `dispose()` is called. Just like what we do with `Layer` - we do reference counting via `LayerHandle`.

This is already how `image.dispose` works, but if someone forgets to call dispose you end up relying on the GC to clean things up. And at any rate, the GC should be informed about this allocation so it can properly plan and stay within the limits it was told to for its own heap size.

**Comment by jonahwilliams** [comment]
"aggressively", as a comment that we trigger two GCs in the same frame. Only the first collects anything.

**Comment by dnfield** [comment]
@rmacnak-google @a-siva FYI

**Comment by a-siva** [comment]
Can you post instructions to run the benchmark, would like to get a timeline locally.

**Comment by jonahwilliams** [comment]
The devicelab benchmark in this PR should demonstrate the issue: https://github.com/flutter/flutter/pull/106621

**Comment by zanderso** [comment]
@jonahwilliams Does this repro at tip-of-tree?

**Comment by jonahwilliams** [comment]
No, you need to use the PR above which actually adds a usage toGpuImage in the framework

**Comment by zanderso** [comment]
Sorry, I meant does this repro when that PR is rebased onto tip-of-tree flutter/flutter. I think a fix from @rmacnak-google may have rolled in within the past day or so.

**Comment by jonahwilliams** [comment]
Oh, I will check that out today. What was the dart commit?

**Comment by jonahwilliams** [comment]
https://github.com/dart-lang/sdk/commit/2e4107c8aee8da6bd4c8173e0c130d873cc3b6cc this one?

**Comment by zanderso** [comment]
Yes, that's the one.

**Comment by jonahwilliams** [comment]
I think that commit is at ToT, but I can still repro

**Comment by rmacnak-google** [comment]
I do not observe GC following `toGpuImage` when I run the benchmark locally. @jonahwilliams, can you provide the trace file where this does occur? It needs to recorded by the VM instead of Android systrace so the attributes on the GC events are retained.

**Comment by jonahwilliams** [comment]
[page_transition_perf.timeline.zip](https://github.com/flutter/flutter/files/9067473/page_transition_perf.timeline.zip)

@rmacnak-google Is the timeline recorder by our integration tests what you are looking for?

**Comment by rmacnak-google** [comment]
Yep, that's it.

**Comment by zanderso** [comment]
@a-siva @rmacnak-google Is there an issue we can x-ref here for the work to grow aggressively during frame workloads?

**Comment by a-siva** [comment]
https://github.com/dart-lang/sdk/issues/47574

**Comment by a-siva** [comment]
Any updates on whether the new API introduced here https://dart-review.googlesource.com/c/sdk/+/252462 helps in this case ?

**Comment by jonahwilliams** [comment]
We're working on using this API during page transitions, for this particular case we've decided to disable reporting of image size to the Dart GC. Since correct usage of images is to dispose them and we had previously done significant work in ensuring that framework images are disposed instead of collected by the GC.
