### ISSUE TITLE
DropdownButtonFormField InkWell spreads to error message

### ISSUE THREAD

**Issue by BananaMasterz** [flutter/flutter#106659]
## Steps to Reproduce

1. Execute `flutter run` on the code sample
2. Tap on the drop down field to trigger the validation and notice that the inkwell spreads to the "Required" error message.

**Expected results:**
The inkwell should be contained within the border of the text field as in the normal text fields when you mouse over.

**Actual results:** 
As seen in the screenshots, the inkwell spreads to the error message

![image](https://user-images.githubusercontent.com/45745548/175932672-eeeba678-c9e1-41c3-9eec-5d465a74a1db.png)

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  MyApp({Key? key}) : super(key: key);

  static const String _title = 'Flutter Code Sample';
  final _formKey = GlobalKey<FormState>();

  @override
  Widget build(BuildContext context) {
    var items = [
      'Ayo',
      'This',
      'Don',
      'Look',
      'Right',
    ].map((String val) {
      return DropdownMenuItem(
        value: val,
        child: Text(
          val,
        ),
      );
    }).toList();

    return MaterialApp(
      title: _title,
      theme: ThemeData(
        inputDecorationTheme: const InputDecorationTheme(
          border: OutlineInputBorder(
            borderRadius: BorderRadius.all(Radius.circular(32)),
            borderSide: BorderSide(color: Colors.blue, width: 2),
          ),
        ),
      ),
      home: Scaffold(
        body: Center(
          child: SizedBox(
            width: 500,
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                Form(
                  key: _formKey,
                  child: DropdownButtonFormField(
                    onTap: () {
                      _formKey.currentState!.validate();
                    },
                    validator: (String? v) => 'Required',
                    onChanged: (String? value) {},
                    items: items,
                  ),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}

```
</details>

**Comment by BananaMasterz** [comment]
> The splash also spills over the border on the corners when you have rounded corners

Yesh I have opened another issue but I was prompted to open a different one for the error text here:

https://github.com/flutter/flutter/issues/106560

**Comment by exaby73** [comment]
Okay thanks. It's good practice to mention linked issues so that it's easier the track everything :)

**Comment by BananaMasterz** [comment]
My bad, will keep it in mind next time. Thanks

**Comment by BananaMasterz** [comment]
The same issue is present in `PopupMenuButton`'s `PopupMenuItem` as seen in the screenshot. I'm not sure if it inherits from the dropdown (I can't see it anywhere but im not sure) so if someone can confirm that fixing the dropdown won't fix the popupmenu item I'll open a new issue for it

![image](https://user-images.githubusercontent.com/45745548/177713975-2a89b9fa-30cf-4351-a3c1-33b023f368da.png)
