### ISSUE TITLE
Delete obsolete dartdocs for Flutter

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#10661]
We should delete the following docs:
- https://www.dartdocs.org/documentation/flutter/0.0.17/index.html
- http://domokit.github.io/docs/sky/

**Comment by Hixie** [comment]
cc @abarth @sethladd

**Comment by sethladd** [comment]
cc @mit-mit do we have the ability to nuke docs from dartdocs.org ?

**Comment by abarth** [comment]
Please send a pull request with the changes you want to https://github.com/domokit/domokit.github.io .  Probably just delete the whole thing and change the README to point to flutter.io ?

**Comment by mit-mit** [comment]
For dartdocs, I believe the only way is to open a bug here https://github.com/astashov/dartdocs.org/issues and ask for them to be removed.

**Comment by zoechi** [comment]
Looks like this is fixed.
