### ISSUE TITLE
Re-enable ExternalTextureTests

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#106673]
For example on https://github.com/flutter/engine/pull/34289, the bot asked for approval for diffs on a Dart SDK -> Engine roll, but that should not be happening.

Edit: In investigating these roll blockages, we determined that the real problem was that the ExternalTextureTests that were recently enabled by https://github.com/flutter/engine/pull/34118 are flaky. One issue is that the wrong value is being used for the image size. This should be addressed by https://github.com/flutter/engine/pull/34431. However, the images that the test produces are still toggling back and forth between 2 or more variants, which causes skia diffs on PRs in a flaky way. The tests were disabled by https://github.com/flutter/engine/pull/34433, but should be re-enabled as a P0 since they are one of the only places we have test coverage of platform views.

**Comment by aam** [comment]
another instance of dart->engine roll being held due to flaky gold tests https://github.com/flutter/engine/pull/34364

**Comment by a-siva** [comment]
bumping priority as we seem to see this happen often

**Comment by a-siva** [comment]
Here is another instance of dart -> engine roll being held up due to a flaky gold test https://github.com/flutter/engine/pull/34388

**Comment by keyonghan** [comment]
@Piinks Could you please help take a look?

**Comment by Piinks** [comment]
I am not familiar with the engine implementation, @mdebbar implemented it. Can you take a look?

**Comment by zanderso** [comment]
@keyonghan This request might be unrelated to the specifics of the check itself. Rather, this is a request that the skia gold diffs should not stop an autoroll from landing.

**Comment by keyonghan** [comment]
I will take a look.

**Comment by keyonghan** [comment]
https://github.com/flutter/cocoon/pull/1953 is being discussed how to move forward.
Un-assigning myself as I will not be able to work on this in the next week.

**Comment by zanderso** [comment]
It looks like these are coming from https://github.com/flutter/engine/pull/34118. @ds84182 Can you suggest how to make these less flaky?

**Comment by zanderso** [comment]
@ds84182

> screenshotSize: fileContent.lengthInBytes

This looks wrong. I think this is supposed to be the number of pixels, not the file size.

https://github.com/flutter/engine/blob/main/testing/scenario_app/bin/android_integration_tests.dart#L79

**Comment by ds84182** [comment]
Will look into a solution after the holidays. I suspect the flakiness comes from different data being decoded from the source image due to timing.

**Comment by ds84182** [comment]
Found a super simple fix. Looks like the source image (which is encoded as a video, intentionally, to test video rotations) has multiple frames. Need to rerun ffmpeg with a framerate specified so there's only a single video frame present in the file.

**Comment by chinmaygarde** [comment]
Ping @ds84182. Are you making progress on https://github.com/flutter/engine/pull/34479?

I am not sure if this is a P0 either. I am moving this to P2 since this was originally elevated to P0 as it was the only test for this scheme.

**Comment by ds84182** [comment]
Yes, it should actually be ready for review. Will update the PR
