### ISSUE TITLE
XCode Error building - camera: ^0.9.8+1 - Module 'camera_avfoundation' not found

### ISSUE THREAD

**Issue by robertjones1** [flutter/flutter#106696]

**Comment by maheshmnj** [comment]
Hi @robertjones1, Thanks for filing the issue. Are you by any chance directly depending on  `camera_avfoundation`? please share the dependencies you are using in `pubspec.yaml`. A minimal and complete code sample along with the output of `flutter doctor -v ` and `flutter run -v` in a text file.
