### ISSUE TITLE
flutter driver _flutter.screenshot: (-32000) Could not capture image screenshot

### ISSUE THREAD

**Issue by Nasrallahelfarra** [flutter/flutter#106631]
Sometimes an error occurs when taking a screenshot of a screen in test driver flutter

E/flutter (20595): [ERROR:flutter/shell/common/rasterizer.cc(717)] Last layer tree was null when screenshotting.
_flutter.screenshot: (-32000) Could not capture image screenshot

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.0.1, on Microsoft Windows [Version 10.0.19044.1706], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2021.1)
[√] Connected device (4 available)
[√] HTTP Host Availability

! Doctor found issues in 1 category.
```

flutter doctor

code screenshot
```
`extension on FlutterDriver {
  Future<void>takeScreenshot(String screenName)async{
    final File file =  File('screenshot/$screenName.png');
    if(file.existsSync()){
      await file.delete(recursive: true);
    }
       await file.create(recursive: true);
      final png=await screenshot();
      file.writeAsBytesSync(png);
      stderr.writeln("screen shot pass");


  }
}`
```

**Comment by Nasrallahelfarra** [comment]
؟؟؟

**Comment by darshankawar** [comment]
@Nasrallahelfarra 
Can you provide complete minimal reproducible code sample that shows this error ?
Can you also try using integration_test package which is now preferred over flutter_driver and see if you still get same error using it ?

https://docs.flutter.dev/testing/integration-tests
https://github.com/flutter/flutter/tree/main/packages/integration_test#usage
https://github.com/flutter/flutter/tree/main/packages/integration_test#screenshots
