### ISSUE TITLE
[image_picker] installing package on Apple M1 raises a 'Could not initialize class java.net.IDN'

### ISSUE THREAD

**Issue by gerasimos** [flutter/flutter#106614]
Hello,

Just by adding the following dependency on an Apple M1, 

```yaml
dependencies:
  image_picker: ^0.8.5+3
```

I am getting:

```
Launching lib/main.dart on sdk gphone64 arm64 in debug mode...
lib/main.dart:1

FAILURE: Build failed with an exception.

* What went wrong:
Could not initialize class java.net.IDN
```

**Comment by exaby73** [comment]
Hi @gerasimos, please provide a [minimal, reproducible example][1] and the output of `flutter doctor -v` as well as `flutter run -v`.

[1]: https://stackoverflow.com/help/minimal-reproducible-example
