### ISSUE TITLE
Kotlin problem

### ISSUE THREAD

**Issue by Herlarney** [flutter/flutter#106633]
I'm a junior mobile app dev working on Vs code, i upgraded to version 3.0.2. Ever since then, i've been on the below error

Launching lib\main.dart on TECNO CD6 in debug mode...
lib\main.dart:1
[Fatal Error] kotlin-script-runtime-1.6.10.pom:2:1: Content is not allowed in prolog.
[Fatal Error] kotlin-reflect-1.6.10.pom:2:1: Content is not allowed in prolog.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugKotlin'.
> Could not resolve all files for configuration ':app:kotlinCompilerClasspath'.
   > Could not resolve org.jetbrains.kotlin:kotlin-script-runtime:1.6.10.
     Required by:
         project :app > org.jetbrains.kotlin:kotlin-compiler-embeddable:1.6.10
      > Could not resolve org.jetbrains.kotlin:kotlin-script-runtime:1.6.10.
> Could not parse POM https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-script-runtime/1.6.10/kotlin-script-runtime-1.6.10.pom
            > Content is not allowed in prolog.
   > Could not resolve org.jetbrains.kotlin:kotlin-reflect:1.6.10.
     Required by:
         project :app > org.jetbrains.kotlin:kotlin-compiler-embeddable:1.6.10
      > Could not resolve org.jetbrains.kotlin:kotlin-reflect:1.6.10.
         > Could not parse POM https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-reflect/1.6.10/kotlin-reflect-1.6.10.pom
            > Content is not allowed in prolog.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

I dont even know where to start looking for the problem. if can take time to help me out, i will be grateful

**Comment by huycozy** [comment]
@Herlarney 
This is likely an issue with that particular version of Gradle. Upgrading/downgrading like in https://github.com/flutter/flutter/issues/51690#issuecomment-603988891 is likely the only solution.
Also, this isn't a Flutter issue, so you need to ask this in support channels like StackOverflow.
Closing from here.
