### ISSUE TITLE
[Documentation] Error in documentation for NavigationRail constructor

### ISSUE THREAD

**Issue by LamaMen** [flutter/flutter#106685]
The docs for the [NavigationRail](https://api.flutter.dev/flutter/material/NavigationRail/NavigationRail.html) constructor state that assignments must be larger than one element:

>The value of [destinations] must be a list of one or more [NavigationRailDestination] values.

But, based on the code and description of the destinations field, we can conclude that there must be more than two elements:

```dart
assert(destinations != null && destinations.length >= 2)
```

```dart
/// Defines the appearance of the button items that are arrayed within the
/// navigation rail.
///
/// The value must be a list of two or more [NavigationRailDestination]
/// values.
final List<NavigationRailDestination> destinations;
```

**Comment by danagbemava-nc** [comment]
Hi @LamaMen, this has been fixed on the master channel. See the screenshot below taken from https://master-api.flutter.dev/flutter/material/NavigationRail/NavigationRail.html

![Screenshot 2022-06-28 at 06 37 52](https://user-images.githubusercontent.com/88313112/176110231-c3bb345d-a8b8-4e5b-98e0-3606f2bb7217.png) 

and this one below taken from the source code.

<img width="748" alt="Screenshot 2022-06-28 at 06 38 58" src="https://user-images.githubusercontent.com/88313112/176110365-e4f03800-b761-4302-9f51-3184801c86a0.png">
 

Closing this as it has already been fixed on the master channel. 

Thank you
