### ISSUE TITLE
CupertinoPicker stuck after scrolling for few minute

### ISSUE THREAD

**Issue by harsh-savvient** [flutter/flutter#106667]
## Details
1. If we scroll the picker continuously more than 2 minute, then it's starting to stuck. That issue is reproducing each time with release build.
2. https://gist.github.com/harsh-savvient/03c9e245dc38b810a2522982e7db697f

**Target Platform:**Android and iOS both
**Target OS version/browser:**11 (api level 30)
**Devices:**Redmi Note 7 pro, iPhone 12 Pro Max

## Logs

<details>

```
```

```
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @harsh-savvient, please provide the output of `flutter doctor -v`. 

Thank you

**Comment by harsh-savvient** [comment]
> Hi @harsh-savvient, please provide the output of `flutter doctor -v`.
> 
> Thank you

Flutter (Channel stable, 3.0.1, on Ubuntu 18.04.5 LTS 5.4.0-120-generic, locale en_IN)
    • Flutter version 3.0.1 at /home/harsh/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (5 weeks ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2
[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /home/harsh/Android/Sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/linux#android-setup for more details.
[✓] Chrome - develop for the web
    • Chrome at google-chrome
[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1
[✓] Android Studio (version 2020.3)
    • Android Studio at /home/harsh/Documents/android-studio-2020.3.1.24/android-studio
    • Flutter plugin version 65.2.1
    • Dart plugin version 203.8452
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
[✓] Android Studio (version 2021.1)
    • Android Studio at /home/harsh/Documents/Software/android-studio-2021.1.1.22-linux_new/android-studio-2021.1.1.22-linux/android-studio
    • Flutter plugin version 68.1.1
    • Dart plugin version 211.7817
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
[✓] Connected device (3 available)
    • Redmi Note 7 Pro (mobile) • 94566c09 • android-arm64  • Android 9 (API 28)
    • Linux (desktop)           • linux    • linux-x64      • Ubuntu 18.04.5 LTS 5.4.0-120-generic
    • Chrome (web)              • chrome   • web-javascript • Google Chrome 93.0.4577.63
[✓] HTTP Host Availability
    • All required HTTP hosts are available

**Comment by danagbemava-nc** [comment]
Hi @harsh-savvient, can you check on the `master` channel to see if you still experience this issue?  You can switch to the master channel by running the following commands

```
flutter channel master
flutter upgrade
```

**Comment by yangyxd** [comment]
I have the same problem. Multiple cupertinopickers will get stuck after rolling for a time.  I have used `flutter stable 3.0.3`.

```dart
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

class RawPickerTest extends StatefulWidget {
  const RawPickerTest({Key? key}) : super(key: key);

  @override
  State<RawPickerTest> createState() => _RawPickerTestState();
}

class _RawPickerTestState extends State<RawPickerTest> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('Test Raw Picker')),
      body: Column(
        mainAxisSize: MainAxisSize.min,
        children: [
          SizedBox(height: 50),
          SizedBox(
            height: 320,
            child: Row(
              children: [
                Expanded(child: _buildCupertinoPicker(context, 0, 20, ValueKey(0))),
                Expanded(child: _buildCupertinoPicker(context, 1, 120, ValueKey(1))),
                Expanded(child: _buildCupertinoPicker(context, 2, 50, ValueKey(2))),
              ],
            ),
          )
        ],
      ),
    );
  }

  Widget _buildCupertinoPicker(BuildContext context,
      int i, int _length, Key? key) {
    return CupertinoPicker.builder(
      key: key,
      scrollController: FixedExtentScrollController(),
      itemExtent: 42,
      selectionOverlay: const CupertinoPickerDefaultSelectionOverlay(),
      childCount: _length,
      itemBuilder: (context, index) {
        return Text("$i.$index");
      },
      onSelectedItemChanged: (int _index) {
        if (_length <= 0) return;
        var index = _index % _length;
        print("onSelectedItemChanged. col: $i, row: $index");
      },
    );
  }
}

```

![001](https://user-images.githubusercontent.com/14143779/176370729-c315f711-209b-4cbc-b476-5ac4423f7b57.gif)

**Comment by harsh-savvient** [comment]
> Hi @harsh-savvient, can you check on the `master` channel to see if you still experience this issue? You can switch to the master channel by running the following commands
> 
> ```
> flutter channel master
> flutter upgrade
> ```

@danagbemava-nc I'll review with master channel. But, We need fixes with stable branch as well.
