### ISSUE TITLE
Bot not landing reverts

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#106668]
I have two reverts on the engine tree that are needed to reopen the tree: https://github.com/flutter/engine/pull/34320 and https://github.com/flutter/engine/pull/34319. Each revert has issues that are not solved by the other, so both reverts are needed to turn the tree back to green. I have added the labels 'autosubmit' and 'warning: land on red to fix tree breakage', but the bot isn't landing the changes.

The expected behavior is for the bot to land reverts.

**Comment by keyonghan** [comment]
This is not tied to `autosubmit` bot, but also the `waiting for tree to go green`.
We have an OKR to implement this in Q3. /cc @ricardoamador 
Moving to technical debt.

**Comment by ricardoamador** [comment]
Reverts have been implemented.
