### ISSUE TITLE
go_router namedLocation() does not function as shown in documentation

### ISSUE THREAD

**Issue by Cyamanide** [flutter/flutter#106605]
Documentation: https://gorouter.dev/named-routes#redirecting-to-named-routes

When calling `state.namedLocation()` in the redirect handler a question mark `?` is appended to the location, this means that when comparing a named location to a subLoc it is impossible to find a match and ends in a redirection loop occurring:

Emulator Screenshot:
![image](https://user-images.githubusercontent.com/4545960/175772617-d7674fa1-371a-46f1-95f6-37e9c2f7ef93.png)

Debugging session screenshot highlighting the issue:

![image](https://user-images.githubusercontent.com/4545960/175772722-9e1e2355-0e1a-45bf-b8aa-519cb3e02489.png)

Following are the names for each location:
![image](https://user-images.githubusercontent.com/4545960/175772775-d7fde797-4e09-4c80-9a21-5f507dfd0c46.png)

**Comment by Cyamanide** [comment]
Sample app:

[cosapp.zip](https://github.com/flutter/flutter/files/8984680/cosapp.zip)

**Comment by darshankawar** [comment]
Thanks for the report @Cyamanide. From the code sample you shared above, I see that you are using provider which is third party plugin. Does the same behavior occur without using it ? If so, can you provide minimal but sufficient code sample (ex: main.dart) that'll be enough to replicate the behavior ?

**Comment by Cyamanide** [comment]
Hi @darshankawar, for sure. 

Please see screenshot and sample app attached. 

The screenshot shows a breakpoint on app startup - the app is not functional, but you are able to see that a `?` mark is appended when retrieving a named location.

![image](https://user-images.githubusercontent.com/4545960/176052703-6f927b8a-8368-4f02-a3e0-0858f77f4d53.png)

The sample app was a copy of https://github.com/csells/go_router/blob/main/go_router/example/lib/redirection.dart that I puller `provider` out of (The sample app also has the same issue)

[test_go.zip](https://github.com/flutter/flutter/files/8996218/test_go.zip)

**Comment by darshankawar** [comment]
Thanks for the update. Using above code sample, I see that the route link has appended `?` in it:

```
Syncing files to device iPhone 13...
flutter: /?
```

<details>
<summary> stable, master flutter doctor -v </summary>

```

[✓] Flutter (Channel stable, 3.0.3, on macOS 12.2.1 21D62 darwin-x64, locale
    en-GB)
    • Flutter version 3.0.3 at /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 676cefaaff (4 days ago), 2022-06-22 11:34:49 -0700
    • Engine revision ffe7b86a1e
    • Dart version 2.17.5
    • DevTools version 2.12.2

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

[✓] Flutter (Channel master, 3.1.0-0.0.pre.1396, on macOS 12.2.1 21D62
    darwin-x64, locale en-GB)
    • Flutter version 3.1.0-0.0.pre.1396 on channel master at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 23437d93ca (73 minutes ago), 2022-06-27 23:39:08 -0400
    • Engine revision 6301c5cb30
    • Dart version 2.18.0 (build 2.18.0-232.0.dev)
    • DevTools version 2.14.1
    
[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.



```

</details>

`go_router: ^4.1.0`

**Comment by techouse** [comment]
I've just observed the same issue.

**Comment by sedumapps** [comment]
Same issue of the routes being suffixed with a ? in  go_router: ^4.2.2

**Comment by absar** [comment]
@johnpryan @chunhtai this is a braking change for named routing with redirection, `state.namedLocation` is now appending unnecessary `?` which is braking redirection logic

**Comment by csells** [comment]
I believe this is a breaking change introduced by the Flutter team as part of their continuing work on go_router. @johnpryan @chunhtai thoughts?
