### ISSUE TITLE
Add Xcode Projects and iOS icons for all flutter/examples

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#1066]
@collinjackson said he'd take a stab at least at the iOS projects.

We no longer should be using Ninja to build any apps, ever.  If there are bugs, please file so we can fix.

There are Android icons for most of our examples.  For the ones that have them, we should port those to iOS.

@chinmaygarde

**Comment by chinmaygarde** [comment]
Now that iOS engines are upgradable, this should be good to go.

**Comment by eseidelGoogle** [comment]
So we can remove `ios` from the .gitignore now?  If you or @tvolkert could show me what to do, I'm happy to start on this.

**Comment by eseidelGoogle** [comment]
I just tried this and got confused.  The XCode project is still in ios/generated.  Does that mean I can edit it?  The default app name is "Flutter" (which I obviously want to change) and I'm not sure if it's safe to rename my XCode project.

**Comment by tvolkert** [comment]
https://github.com/flutter/flutter/pull/1801, and now we can check icons into ios/

**Comment by chinmaygarde** [comment]
@eseidelGoogle the Xcode project is still in the generated folder but the Info.plist, SplashScreen and user assets are not. If you modify those, your changes will stick around across engine upgrades. Modifying these from Xcode should be fine too. If it's too confusing to have a generated Xcode project at all, we can move this out of the iOS directory

**Comment by chinmaygarde** [comment]
Fixed in https://github.com/flutter/flutter/pull/1936

**Comment by eseidelGoogle** [comment]
Still no icons. :(

**Comment by eseidelGoogle** [comment]
We have icons!  https://github.com/flutter/flutter/pull/2175  They're not exactly the right icons, but they're better than nothing.
