### ISSUE TITLE
App is crashing while loading an images

### ISSUE THREAD

**Issue by venkateshavenki** [flutter/flutter#106734]
I am using cache network image for displaying images but it is crashing every time while loading images and it is showing errors like the below.

1. * thread #11, name = 'io.flutter.1.io', stop reason = EXC_RESOURCE RESOURCE_TYPE_MEMORY (limit=2098 MB, unused=0x0)
    frame #0: 0x00000001084d0e68 Flutter`void downsample_2_2<ColorTypeFilter_8888>(void*, void const*, unsigned long, int) + 84
Flutter`downsample_2_2<ColorTypeFilter_8888>:
->  0x1084d0e68 <+84>: st1.s  { v0 }[0], [x0], #4
    0x1084d0e6c <+88>: subs   x8, x8, #0x1
    0x1084d0e70 <+92>: b.ne   0x1084d0e24               ; <+16>
    0x1084d0e74 <+96>: ret    
Target 0: (Runner) stopped.

2. * thread #11, name = 'io.flutter.1.io', stop reason = EXC_RESOURCE RESOURCE_TYPE_MEMORY (limit=2098 MB, unused=0x0)
    frame #0: 0x00000002232e1aa8 libsystem_platform.dylib`_platform_memmove + 88
libsystem_platform.dylib`_platform_memmove:
->  0x2232e1aa8 <+88>:  stnp   q0, q1, [x3]
    0x2232e1aac <+92>:  add    x3, x3, #0x20
    0x2232e1ab0 <+96>:  ldnp   q0, q1, [x1]
    0x2232e1ab4 <+100>: add    x1, x1, #0x20

**Comment by danagbemava-nc** [comment]
Hi @venkateshavenki, thanks for filing the issue. 

- Does this crash occur when you use only the `Image` widget or does it only crash when you use `CachedNetworkImage`?
- Does this crash occur in release/profile/debug mode?

Please provide a complete minimal reproducible code sample if this issue occurs without the use of `CachedNetworkImage` and the output of `flutter doctor -v` as well as the complete logs of the running app that captures the bug if possible. 

Thank you

**Comment by danagbemava-nc** [comment]
Hi @venkateshavenki, if the app only crashes when you use the `cached_network_image` plugin then you need to report this on their dedicated repo over [here](https://github.com/Baseflow/flutter_cached_network_image/issues) so that they can investigate this. 

I'll be closing this as this issue appears to be from a third-party dependency. 

If the crash does occur with the `Image` widget in flutter, kindly provide a complete minimal reproducible code sample and I will reopen this issue. 

Thank you

**Comment by venkateshavenki** [comment]
> Hi @venkateshavenki, if the app only crashes when you use the `cached_network_image` plugin then you need to report this on their dedicated repo over [here](https://github.com/Baseflow/flutter_cached_network_image/issues) so that they can investigate this.
> 
> I'll be closing this as this issue appears to be from a third-party dependency.
> 
> If the crash does occur with the `Image` widget in flutter, kindly provide a complete minimal reproducible code sample and I will reopen this issue.
> 
> Thank you

Okay, Thank you @danagbemava-nc, I will add this issue in the flutter cached network image.
