### ISSUE TITLE
[Impeller] New gallery transition perf worst and 99th %-ile raster time regression on Android

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#106774]
On the change to render BackdropFilter layers directly to DisplayListBuilder https://github.com/flutter/engine/pull/34337, worst and 99th %-ile frame rasterization times regressed on Moto G4:

https://flutter-flutter-perf.skia.org/e/?begin=1654156387&end=1656469887&keys=X5f6e343cfb7467cdc34ede6764f63458&requestType=0&xbaroffset=29603

@chinmaygarde @bdero @flar

**Comment by flar** [comment]
Closing as this increase in time was expected now that we are actually filtering the backdrop...
