### ISSUE TITLE
CupertinoDatePicker very lag when scroll up and down several times

### ISSUE THREAD

**Issue by dankocher** [flutter/flutter#106737]
> Hi @genevaspur @adham-ashraf77, could either of you provide a complete minimal sample that we can use to verify this behaviour? I ran the sample found in https://api.flutter.dev/flutter/cupertino/CupertinoDatePicker-class.html and I didn't notice any lag. The frame rate was around 56fps in `debug` mode and around 60fps in `profile` mode.
> 
> What platforms are you experiencing this issue on?
> 
> Please provide the output of `flutter doctor -v` as well.
> 
> video

@danagbemava-nc  I copy https://api.flutter.dev/flutter/cupertino/CupertinoDatePicker-class.html code, run on Flutter 3.0.1 Android 10 can reproduce this issue, you need scroll up and down several times, it suddenly become very lag.
It seems change to `DateTime dateTime = DateTime.now();` will Increase the probability of occurrence

_Originally posted by @taosimple in https://github.com/flutter/flutter/issues/104049#issuecomment-1139561773_

I have the same issue on iOS when scroll up and down several times, it suddenly become very lag. Any solution?

**Comment by moffatman** [comment]
It's probably the same issue: https://github.com/flutter/flutter/issues/98275. The fix isn't yet in `stable` channel, it's present in `master` channel only so far.

**Comment by danagbemava-nc** [comment]
Hi @dankocher, can you check on the `master` channel to see if you still experience this issue?  You can switch to the master channel by running the following commands

```
flutter channel master
flutter upgrade
```

**Comment by dankocher** [comment]
> Hi @dankocher, can you check on the `master` channel to see if you still experience this issue? You can switch to the master channel by running the following commands
> 
> ```
> flutter channel master
> flutter upgrade
> ```

Thanks a lot. This solved the problem.
