### ISSUE TITLE
Copybara mirror fails when private keys are touched

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#106755]
For the commit: https://github.com/flutter/flutter/commit/bbdf617034171ab1128a594fb24e1c72a09e072e

all post-submit builds are failing because the commit does not yet exist on https://flutter.googlesource.com/mirrors/flutter

Example failures: https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20build_tests_2_2/5515/overview
https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20docs_publish/5268/overview
https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20packages_autoroller/4/overview

**Comment by keyonghan** [comment]
I manually run the copybara (which failed due to config issue). @christopherfujino could you help push an empty commit to green the tree?

**Comment by christopherfujino** [comment]
gonna manually merge: https://github.com/flutter/flutter/pull/106706

**Comment by godofredoc** [comment]
@keyonghan Do we need to update configs?

**Comment by christopherfujino** [comment]
are post-submit builds triggered by cocoon? it seems to me like a bug that we even scheduled the builds before the commit mirrored.

**Comment by christopherfujino** [comment]
oh actually, by merging a new commit, will this fail again until THAT commit gets mirrored?

**Comment by christopherfujino** [comment]
> oh actually, by merging a new commit, will this fail again until THAT commit gets mirrored?

never mind, we already have a green build

**Comment by keyonghan** [comment]
> @keyonghan Do we need to update configs?

Copybara complains about rejection due to `private key`:
```
remote: The push has been rejected because we detect that it contains a private        
remote: key. There might be false positives if the local repo is behind. You        
remote: may sync by using git fetch or repo sync before push again to avoid        
remote: this. If the warning persists, please check the following commands and        
remote: confirm that it's intentional:        
remote: 
remote:     git describe --always 6f5c76d9e713c5de2a2085d985e03fd86b4665cf        
remote: 
remote: (To Googlers) Please check if this is OK with a privacy review. In        
remote: general, we recommend using go/keystore to store secret keys.        
remote: 
remote: If you are certain this is a false positive, or that it is safe to store        
remote: this key, then please run `git push -o nokeycheck`.        
remote: (repo users can run `repo upload -o nokeycheck`).        
remote: 
To rpc://flutter.googlesource.com/_direct/mirrors/flutter
 ! [remote rejected]       main -> main (found a private key)
 ! [remote rejected]       master -> master (found a private key)
error: failed to push some refs to 'rpc://flutter.googlesource.com/_direct/mirrors/flutter'
```

After a manual trigger, the following commit was mirrored correctly.
Do you have any insight if any easy config is feasible here?

**Comment by christopherfujino** [comment]
> > @keyonghan Do we need to update configs?
> 
> Copybara complains about rejection due to `private key`:
> 
> ```
> remote: The push has been rejected because we detect that it contains a private        
> remote: key. There might be false positives if the local repo is behind. You        
> remote: may sync by using git fetch or repo sync before push again to avoid        
> remote: this. If the warning persists, please check the following commands and        
> remote: confirm that it's intentional:        
> remote: 
> remote:     git describe --always 6f5c76d9e713c5de2a2085d985e03fd86b4665cf        
> remote: 
> remote: (To Googlers) Please check if this is OK with a privacy review. In        
> remote: general, we recommend using go/keystore to store secret keys.        
> remote: 
> remote: If you are certain this is a false positive, or that it is safe to store        
> remote: this key, then please run `git push -o nokeycheck`.        
> remote: (repo users can run `repo upload -o nokeycheck`).        
> remote: 
> To rpc://flutter.googlesource.com/_direct/mirrors/flutter
>  ! [remote rejected]       main -> main (found a private key)
>  ! [remote rejected]       master -> master (found a private key)
> error: failed to push some refs to 'rpc://flutter.googlesource.com/_direct/mirrors/flutter'
> ```
> 
> After a manual trigger, the following commit was mirrored correctly. Do you have any insight if any easy config is feasible here?

I think @CaseyHillers and I had discussed skipping these checks...

**Comment by CaseyHillers** [comment]
https://g3doc.corp.google.com/company/teams/flutter/infrastructure/copybara.md?cl=head#bypassing-a-private-key-check-error

**Comment by CaseyHillers** [comment]
I thought cl/439367716 would've skipped the security check, but maybe there is another flag we need to flip?

**Comment by keyonghan** [comment]
Reopen b/204369275 to track from GOB team.

**Comment by christopherfujino** [comment]
Lowering priority as this is not currently blocking the tree

**Comment by yusuf-goog** [comment]
Pinged the b/204369275 to see what more we need to add to cl/439367716 to get the check bypassed.

**Comment by keyonghan** [comment]
This is not happening in weeks. Moving to technical debt.

**Comment by keyonghan** [comment]
cl/553819522 to fix the bug
