### ISSUE TITLE
terminal.onCharInput can crash if dart.io.stdin is already listened to

### ISSUE THREAD

**Issue by xster** [flutter/flutter#10677]
dart.io.stdin itself isn't a broadcast stream. 

IDEs subscribed to stdin can cause the tool to crash in terminal.onCharInput

**Comment by eseidelGoogle** [comment]
Does the IDE need to run `flutter` with --non-interactive?  Or do we need to wrap stdin in a broadcast stream?  Or something else?  @tvolkert @devoncarew

**Comment by xster** [comment]
Letting dart.io.stdin be exposed as a broadcast stream seems like a generally safe thing to do unless I'm missing some context. Though it seems like that file was last touched 5 years ago anyway.

**Comment by eseidelGoogle** [comment]
I presume there is a memory cost?  @zanderso might know.

**Comment by zanderso** [comment]
If there is an additional memory cost, I would guess that it is pretty small. I would guess that `dart:io` `stdin` is not a broadcast stream by default because broadcast streams silently drop events when there are no listeners, which would be bad if you really want all the bits that are sent your way. Also, if what you really want is a broadcast stream you can always say `stdin.asBroadcastStream()`.

**Comment by floitschG** [comment]
The problem with a broadcast stream is, that it justs dumps events into the void when nobody is listening. For `stdin` that would probably be worse that not being able to have multiple listeners on stdin.

In general, we think that stdin is a resource that can't just be used independently by different parts of a program. That is, there should be some part of the program that is responsible for managing access to `stdin`. That part can then also deal with multiple listeners by using the [StreamQueue](https://www.dartdocs.org/documentation/async/1.13.3/async/StreamQueue-class.html) class from package async (for example).

Related issues:
https://github.com/dart-lang/sdk/issues/24881
https://github.com/dart-lang/sdk/issues/24464

**Comment by devoncarew** [comment]
> IDEs subscribed to stdin can cause the tool to crash in terminal.onCharInput

This is an external process subscribed to stdin, or flutter_tools listening to stdin in more than one place?

We should likely be able to infer a non-interactive global flag from running in `flutter daemon` or `flutter run --machine`. Though, I'd want to look at places where we're asking for user input and see if those can't be eliminated (https://github.com/flutter/flutter/issues/10626).

**Comment by jonahwilliams** [comment]
I don't think there is anything actionable here for us. Closing for now
