### ISSUE TITLE
Debug Console: Error: ADB exited with exit code 1 Performing Streamed Install... 

### ISSUE THREAD

**Issue by BegicHarun** [flutter/flutter#106742]
## Problem
I am trying to run app on Android Emulator and it's saying that **[INSTALL_FAILED_INSUFFICIENT_STORAGE]** but when I wipe data from AVD and restart VS Code and try again, sam error.. Sometimes I go _flutter clean_ and _flutter pub_ get and sometimes work but sometimes don't. I tried to do every solution that people posted previously in their similar problems but solutions don't work. When I use Windows10 on my PC I am not having this problem but on my Mackbook Air 2020 I am facing this on all projects. P.S This is new project(blank template).

## Logs

> flutter run
Using hardware rendering with device sdk gphone64 arm64. If you
notice graphics artifacts, consider enabling software rendering
with "--enable-software-rendering".
Launching lib/main.dart on sdk gphone64 arm64 in debug mode...
Running Gradle task 'assembleDebug'...                             12.9s
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
Installing build/app/outputs/flutter-apk/app.apk...                689ms
Error: ADB exited with exit code 1
Performing Streamed Install
adb: failed to install
/Users/harunbegic/Desktop/dev/flutter/login_authh/build/app/outp
uts/flutter-apk/app.apk: Failure
[INSTALL_FAILED_INSUFFICIENT_STORAGE]
Error launching application on sdk gphone64 arm64. ```

**Comment by huycozy** [comment]
Hi @BegicHarun 
Try to clean up the device to free some space and then run again which should resolve this issue.
Also, you can try creating/modify Android emulator with higher storage.
![Screen Shot 2022-06-29 at 11 06 36](https://user-images.githubusercontent.com/104349824/176349304-75509557-92b4-4c82-a261-a62726a365c5.png)
And you can see this StackOverflow answers for more details: https://stackoverflow.com/questions/4709137/solution-to-install-failed-insufficient-storage-error-on-android

Closing from here as this isn't a Flutter issue.
