### ISSUE TITLE
Autosubmit bot failing to land rolls into engine following cirrus removal

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#106712]
After https://github.com/flutter/engine/pull/34335, the autosubmit bot is sad that the Cirrus checks are gone, and is failing to land PRs from autorollers: https://github.com/flutter/engine/pull/34339

cc @dnfield @keyonghan

**Comment by zanderso** [comment]
If it will take some time to land a fix to the autosubmit bot, we should revert the cirrus yaml removal until that can happen first.

**Comment by dnfield** [comment]
We could also just add back some trivial task that quickly completes with success for now

**Comment by dnfield** [comment]
Lowering priority since work around landed. If infra wants to drop cirrus more eagerly might be worth raising the priority.
