### ISSUE TITLE
[Question] Compilation problem with generated C++ code with pigeon.

### ISSUE THREAD

**Issue by HakkyuKim** [flutter/flutter#106720]
Hi, I'm a developer working on integrating flutter framework into a custom OS at my company.

I see that many plugins are migrating to pigeon and I would like to apply this change to our plugin implementations as well.

The target platform uses the Linux kernel and has it's own application framework written in C. Plugin code is written in C++, the build tool for our platform internally uses Make and Clang tools for compilation. 

Pigeon recently added (experimental) support for C++ on Windows and I was hoping to use this new feature to generate code for our platform as well. Our current build system has access to code in [engine/shell/platform/common/client_wrapper](https://github.com/flutter/engine/tree/main/shell/platform/common/client_wrapper), so my expectation was that generated code will compile without any issue.

However, compiler generates the following error message:
```sh
src/messages.g.cc:55:18: error: no viable conversion from 'flutter::EncodableMap' (aka 'map<flutter::EncodableValue,
flutter::EncodableValue>') to 'const flutter::EncodableValue'
      WriteValue(std::any_cast<Message>(*custom_value).ToEncodableMap(), stream);
```

I understand that the code compiles fine on Windows, but I'm not sure why that is. I know two platforms use different compilers (and probably different compiler options).

Could anyone provide hints or provide some keywords to search?

**Comment by stuartmorgan** [comment]
We cannot provide support for third-party embedding build systems (particularly when we've never even seen them).

> I understand that the code compiles fine on Windows

If you haven't already, you should verify that this is actually true; a number of features that were added to Pigeon while the C++ PR was evolving don't currently work, and in some cases currently generate code that doesn't compile.

(Since you haven't provided any context on what the source API is, I have no way of knowing if this is one of those cases.)

**Comment by HakkyuKim** [comment]
I wasn't implying any support but wondering if someone might know about the issue because the error message looks more like a language misuse rather than difference in build system. 

Thanks for the reply and I'll check again on Windows.

**Comment by stuartmorgan** [comment]
> I wasn't implying any support but wondering if someone might know about the issue

The Flutter issue tracker is for bug reports and feature requests though, not questions/discussion.

> the error message looks more like a language misuse

If you find bugs in Pigeon-generated code, please file them as issue reports, with all the usual necessary elements like a minimal reproducible test case.

**Comment by HakkyuKim** [comment]
> The Flutter issue tracker is for bug reports and feature requests though, not questions/discussion.

Ah okay, should have found a more appropriate channel for the issue :)
