### ISSUE TITLE
DropdownButton's hint alignment is affected by selectedItemBuilder

### ISSUE THREAD

**Issue by zopagaduanjr** [flutter/flutter#106717]
## issue

The hint widget isn't wrapped with _DropdownMenuItemContainer when selectedItemBuilder is set.

https://github.com/flutter/flutter/blob/8c67684fce26f3ec74b598ac957e1d874913c563/packages/flutter/lib/src/material/dropdown.dart#L1399-L1404

this causes the hint widget to have a float effect.

![image](https://user-images.githubusercontent.com/38291023/176080477-3bfa9a1d-912b-406b-a6e4-649b5b1dab30.png)
dartpad demo: https://dartpad.dev/?id=f31fae9f27d88f616522d15ef71777bc

I believe selectedItemBuilder should only affect the selected menu item. Since hint can't be selected, it should still be wrapped to the default DropdownMenuItemContainer.

## proposal
displayedHint to be always wrapped with DropdownMenuItemContainer

**Comment by TahaTesser** [comment]
fixed in https://github.com/flutter/flutter/pull/106731
