### ISSUE TITLE
Want webview_flutter can accept permisson[camera etc]

### ISSUE THREAD

**Issue by niumj** [flutter/flutter#106772]
Thank you for your contributions.

## Use case
     Smart app can use website's scan function by the webvie_flutter。 Like the below issue
     https://github.com/flutter/flutter/issues/92414

## Proposal

    Want scan barcode etc by smart App through the webview_flutter。

**Comment by manuelduarte077** [comment]
you can read this, it may help you

https://stackoverflow.com/questions/66743004/android-crashes-when-i-try-to-use-qr-scanning-with-a-web-view

**Comment by maheshmnj** [comment]
Hi @niumj, I see there is a similar issue describing your case Please see https://github.com/flutter/flutter/issues/78147. Please follow up there on that issue for further updates, Closing this issue as a duplicate.
