### ISSUE TITLE
How flutter implements the hot update solution for Android and IOS

### ISSUE THREAD

**Issue by HG9558** [flutter/flutter#106718]
Hi, I'm currently using flutter for app product development, and since I'm experiencing version iteration problems with my app product development, I'd like to ask if there is a hot update solution available in flutter for IOS and Android, thanks.

**Comment by danagbemava-nc** [comment]
Hi @HG9558, this feature is currently not supported in flutter, but there is a proposal requesting this feature in https://github.com/flutter/flutter/issues/14330. Kindly follow up in the linked issue for updates. 

Closing from here as duplicate. 

Thank you
