### ISSUE TITLE
'flx' is reported as the top most-used command, but it's not a top-level command for flutter_tool

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#10670]
We might be confusing our analytics data.

We wanted to know how often the 'test' command is used with the flutter tool. When we look at analytics, we see the 'flx' is the top command. However, 'flx' is not an "available command":

```
Available commands:
  analyze          Analyze the project's Dart code.
  build            Flutter build commands.
  channel          List or switch flutter channels.
  config           Configure Flutter settings.
  create           Create a new Flutter project.
  devices          List all connected devices.
  doctor           Show information about the installed tooling.
  drive            Runs Flutter Driver tests for the current project.
  format           Format one or more dart files.
  fuchsia_reload   Hot reload on Fuchsia.
  help             Display help information for flutter.
  install          Install a Flutter app on an attached device.
  logs             Show log output for running Flutter apps.
  packages         Commands for managing Flutter packages.
  precache         Populates the Flutter tool's cache of binary artifacts.
  run              Run your Flutter app on an attached device.
  screenshot       Take a screenshot from a connected device.
  stop             Stop your Flutter app on an attached device.
  test             Run Flutter unit tests for the current project.
  trace            Start and stop tracing for a running Flutter app.
  upgrade          Upgrade your copy of Flutter.
```

I don't think we want to track 'flx' as a command/screen, for the purposes of analytics. 'flx' is an internal task, which fires in response to 'hotrun'.

We're basically double-counting the amount of user actions (once for "hotrun", once for "flx").

Suggestion:

* Fire _one_ analytics screen, for the actual command the the user initiated (analyze, test, drive, run, etc).

* Make "hotrun" _only_ an event, not an event _and_ a screen.

* Don't report secondary analytics screens (such as flx) if you've already reported the primary screen (build).

**Comment by Hixie** [comment]
@sethladd This doesn't fall into any of our current high-priority buckets, but if you want this dealt with sooner rather than later let's talk about who should look at it.

**Comment by sethladd** [comment]
Agreed, this isn't a blocker for our customers. This is a near-blocker for our understanding of our customers :) But yeah, happy to discuss ways to slice/dice the data to get the answers we seek.

**Comment by sethladd** [comment]
Should be fixed by https://github.com/flutter/flutter/issues/10789
