### ISSUE TITLE
'flutter pub get' Command run error when ios directory exists in root directory

### ISSUE THREAD

**Issue by dujj** [flutter/flutter#106846]
## Steps to Reproduce

1. https://docs.flutter.dev/development/add-to-app/ios/project-setup use Option A - Embed with CocoaPods and the Flutter SDK
2. flutter create -t module hello in a ios project
3. cd hello
4. fultter pub clean
5. fultter pub get
6. view .ios directory is right
7. fultter pub clean
8. mkdir ios
9. fultter pub get
10. view .ios directory is not right
11. pod install failed

## Logs

<details>
<summary>Logs</summary>

```
```

```
```

</details>

**Comment by exaby73** [comment]
Hi @dujj, please provide a [minimal, reproducible example][1] and the output of `flutter doctor -v`.

[1]: https://stackoverflow.com/help/minimal-reproducible-example

**Comment by dujj** [comment]
@exaby73
[hello.zip](https://github.com/flutter/flutter/files/9017640/hello.zip)
cd why
flutter pub get
cd ..
pod install

result:
Analyzing dependencies
[!] No podspec found for `Flutter` in `why/.ios/Flutter/engine` 

flutter doctor -v
[✓] Flutter (Channel stable, 3.0.3, on macOS 12.4 21F79 darwin-arm, locale
    zh-Hans-CN)
    • Flutter version 3.0.3 at /opt/homebrew/Caskroom/flutter/3.0.3/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 676cefaaff (8 days ago), 2022-06-22 11:34:49 -0700
    • Engine revision ffe7b86a1e
    • Dart version 2.17.5
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version
    32.1.0-rc1)
    • Android SDK at /Users/dujianjie/Library/Android/sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.68.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.42.0

[✓] Connected device (3 available)
    • iPhone 7 Plus (mobile) • 6c5b20c0164d794f0e3ad79f52b9ce59d4540689 • ios
      • iOS 15.5 19F77
    • macOS (desktop)        • macos                                    •
      darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)           • chrome                                   •
      web-javascript • Google Chrome 103.0.5060.53

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Comment by exaby73** [comment]
@dujj By deleting the `why` folder and re-creating the module using `flutter create -t module why`, I was able to get it working

**Comment by dujj** [comment]
@exaby73 
The key is whether there is an ios directory in the why directory.
Of course, you can also delete the ios directory, or rename it to another name.
The crux of the problem is that whether the execution of the command is successful or not cannot depend on whether there is an ios directory in the why directory.

**Comment by exaby73** [comment]
I created an `ios` directory in `why` and ran `flutter pub get` in `why` and `pod install` in root. I didn't get any errors

**Comment by dujj** [comment]
@exaby73 
Did you run flutter clean before running flutter pub get?

**Comment by exaby73** [comment]
I am unable to reproduce this with master. In stable, I can. Please confirm if that's the case for you as well

**Comment by dujj** [comment]
Hope the next stable can solve this problem

**Comment by dujj** [comment]
@exaby73 
yes, success in master, and failed in stable
