### ISSUE TITLE
[go_router] Exposing some of the classes

### ISSUE THREAD

**Issue by atoka93** [flutter/flutter#106863]
## Use case

When assigning some of the members of the GoRouter class to variables:
```dart
  final GoRouter goRouter = GoRouter(...);
  final GoRouteInformationProvider routeInformationProvider =  goRouter.routeInformationProvider;
  final GoRouterDelegate routeInformationParser =  goRouter.routeInformationParser;
  final GoRouterDelegate routerDelegate =  goRouter.routerDelegate;
``` 
I need to import the following implementation imports to make it work:
```dart
import 'package:go_router/src/go_route_information_parser.dart';
import 'package:go_router/src/go_route_information_provider.dart';
import 'package:go_router/src/go_router_delegate.dart';
```

## Proposal

Would be nice if these could be exposed through the public API to avoid this.

I am using the `implementation_imports` lint and it is throwing a warning, that's how I noticed it to begin with.

Thank you for the great work!

**Comment by exaby73** [comment]
Hello @atoka93. Thank you for filing this proposal. This looks like a valid feature request

**Comment by atoka93** [comment]
I just noticed I wrote `private API`, I meant public API, exposed through the public API; sorry for the confusion.

**Comment by atoka93** [comment]
so basically I would like to have:
```dart
export 'src/go_route_information_parser.dart';
export 'src/go_route_information_provider.dart';
export 'src/go_router_delegate.dart';
```
in `go_router.dart` or something similar.

**Comment by exaby73** [comment]
Thanks for the clarification. I edited your comment to fix the typo. Hope you don't mind.

I'm a bit unsure, but does this mean that the current imports would break? Or would this work side-by-side with the way it's currently working?

**Comment by atoka93** [comment]
Sure, thanks for fixing.
Both would work side by side

**Comment by johnpryan** [comment]
Why do you need to assign these to variables? You shouldn't need to import these libraries if you aren't using them directly:

```dart
import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';

class App extends StatelessWidget {
  App({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) => MaterialApp.router(
        routeInformationProvider: _router.routeInformationProvider,
        routeInformationParser: _router.routeInformationParser,
        routerDelegate: _router.routerDelegate,
      );

  final GoRouter _router = GoRouter(
    // ...
  );
}
```

**Comment by johnpryan** [comment]
What's the reason you would prefer to use variables rather than getters as is currently written?

**Comment by atoka93** [comment]
Oh, I see, because if I specify: `<List<GoRouteMatch>>` `GoRouteMatch` is not exposed.
Not ideal, I would then have a

**Comment by atoka93** [comment]
closed it accidentally

**Comment by johnpryan** [comment]
@atoka93 Thanks for filing this issue, I'm going to move the conversation over to https://github.com/flutter/flutter/issues/107757, which will make these types abstract, and  change the return type of `GoRouter.of()`.
