### ISSUE TITLE
bot_update consistently taking 10 minutes longer than last week

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#106805]
Compared with last week, regardless of configuration, the bot_update step is taking about 10 extra minutes on a large proportion of builds.

<img width="1451" alt="Screen Shot 2022-06-29 at 8 54 06 AM" src="https://user-images.githubusercontent.com/6343103/176481467-0b27cefc-1a3c-4205-a56c-967b59549ad1.png">

Compare e.g.:
fast: https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20Web%20Engine/11406/timeline
slow: https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20Web%20Engine/11523/timeline

Slowing down a larger proportion of builds by 10 minutes takes us out of our 30-40 minute cycle time goal for Engine CI.

**Comment by zanderso** [comment]
Might go beyond Linux. Bot update took 49 minutes on this mac presubmit run https://ci.chromium.org/ui/p/flutter/builders/try/Mac%20iOS%20Engine/33238/overview

**Comment by keyonghan** [comment]
> Might go beyond Linux. Bot update took 49 minutes on this mac presubmit run https://ci.chromium.org/ui/p/flutter/builders/try/Mac%20iOS%20Engine/33238/overview

`Mac iOS Engine` is with a different issue where it took ~50 mins to communicate with `src/third_party/angle` and hit error in the end.
```
[0:47:14]   src/third_party/angle
[0:47:24] Stil
l working on:
[0:47:24]   src/third_party/angle
13>WARNING: subprocess '"git" "-c" "core.deltaBaseCacheLimit=2g" "fetch" "origin" "--prune" "--verbose" "--no-tags"' in /opt/s/w/ir/cache/builder/src/third_party/angle failed; will retry after a short nap...
[0:47:34] Still working on:
[0:47:34]   src/third_party/angle

src/third_party/angle
```

**Comment by keyonghan** [comment]
I created crbug.com/1340718 to see if any issue with our GCEs.

**Comment by keyonghan** [comment]
Adding for context: both the [fast](https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20Web%20Engine/11406/overview) and [slow](https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20Web%20Engine/11523/overview) builds are with bots from same region: `central1-b`. /cc @godofredoc

**Comment by keyonghan** [comment]
Network issue seems resolved since 2022-07-08. /cc @zanderso 
<img width="1103" alt="Screen Shot 2022-07-11 at 10 56 20 AM" src="https://user-images.githubusercontent.com/54558023/178327471-630be2bf-85cf-4de2-968e-877904e04e53.png">

**Comment by zanderso** [comment]
It looks like this has recovered. What was the root cause? Is there anything we should do to avoid this in the future?

**Comment by keyonghan** [comment]
This is due to GFE config: b/235486845, which has been rolled back.
Marking this as resolved.
