### ISSUE TITLE
Dev docs point to master instead of alpha

### ISSUE THREAD

**Issue by maryx** [flutter/flutter#10685]
It seems like we should be developing using the alpha branch, but the docs point to the master branch, so there are some inconsistencies. E.g. the alpha branch of DragTarget's `LongPressDraggable` doesn't have a `onDragCompleted` callback (https://github.com/flutter/flutter/blob/alpha/packages/flutter/lib/src/widgets/drag_target.dart#L219) whereas the docs say that it is a constructor property (https://docs.flutter.io/flutter/widgets/LongPressDraggable-class.html).

**Comment by sethladd** [comment]
Agreed. I think docs.flutter.io should point to the latest version from the _recommended_ branch/channel.

**Comment by sethladd** [comment]
I can take a crack at this.

**Comment by sethladd** [comment]
docs.flutter.io should now point to alpha
