### ISSUE TITLE
Custom tooltip message in apbar back button

### ISSUE THREAD

**Issue by sikandernoori** [flutter/flutter#106814]
There should be an option to customize back button tooltip message in AppBar.
By default the tooltip message is fixed and being provided by `MaterialLocalizations.backButtonTooltip`

**Comment by maheshmnj** [comment]
Hey @sikandernoori, that is when the Back button is shown by default on the appBar. However, the appbar does allow you to show your custom widget using the `leading`  parameter.
Closing as this can be achieved by specifying your custom widget to `leading` parameter.

**Comment by sikandernoori** [comment]
Hello @maheshmnj I know the leading widget workaround to customize tooltip.
But why do workaround ? when we can do it in a proper way.
