### ISSUE TITLE
[tool]Pressing R Hot reload not responding

### ISSUE THREAD

**Issue by xiaoka1233333** [flutter/flutter#106868]
![截屏2022-06-30 19 04 44](https://user-images.githubusercontent.com/108468277/176672844-64c24b70-56b8-4a13-a5d7-c8e334365a99.png)

After I start the project with fvm flutter run on VScode, the R key hot update on the terminal does not respond

**Comment by maheshmnj** [comment]
Hi @xiaoka1233333, Thanks for filing the issue. to invoke hot reload from the terminal you need to run the flutter app from your terminal by running `flutter run`. If you are  still facing the issue can you please share the complete output of `flutter run -v` in a text file (as the output will be long)? along with the output of `flutter doctor -v`.

Thanks
