### ISSUE TITLE
[Impeller] Update impellerc to allow compiling to SkSL shader format

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#106823]
Given a particular target platform + architecture, though not much more info than that.

From discussion on shader hot reload support. @zanderso @chinmaygarde

**Comment by chinmaygarde** [comment]
From meeting notes: This is fairly low priority as this isn't a blocker for either shader hot-reload or Impeller. The implementation will likely be similar to the the [SPIRV to C++ transpiler in SPIRV-Cross](https://github.com/KhronosGroup/SPIRV-Cross/blob/e6925974d1ff5cb6b6472b20eed380889cde2ae8/spirv_cpp.cpp). SKSL uniforms will be of `UniformConstant` type with only fragment shaders processed.
