### ISSUE TITLE
[flutter_tools] the tool manually pinning test_api is blocking rolling the latest dwds

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#106886]
To diagnose why dwds is did not get bumped by the auto-roll: https://github.com/flutter/flutter/pull/106837, I temporarily added `'dwds': '15.0.0',` to the manual pin map: https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/commands/update_packages.dart#L29, and ran `flutter update-packages --force-upgrade` and got this error from pub:

```
Because test_core >=0.4.14 <0.4.15 depends on test_api 0.4.10 and test_core >=0.4.11 <0.4.14 depends on vm_service >=6.0.0 <9.0.0, test_core >=0.4.11 <0.4.15 requires test_api 0.4.10 or vm_service >=6.0.0 <9.0.0.
And because dwds >=15.0.0 depends on vm_service ^9.0.0, if dwds >=15.0.0 and test_core >=0.4.11 <0.4.15 then test_api 0.4.10.
And because test_core >=0.4.15 depends on test_api 0.4.11 and flutter_update_packages depends on test_api 0.4.9, dwds >=15.0.0 is incompatible with test_core >=0.4.11.
So, because flutter_update_packages depends on both dwds 15.0.0 and test_core >=0.4.13, version solving failed.
```

Because we're also manually pinning `test_api`.

**Comment by jonahwilliams** [comment]
https://github.com/flutter/flutter/issues/106158

**Comment by christopherfujino** [comment]
unpinned in https://github.com/flutter/flutter/pull/106887
