### ISSUE TITLE
Dragging while the text selection toolbar is up should close it

### ISSUE THREAD

**Issue by justinmc** [flutter/flutter#106820]
On Flutter desktop, it's currently possible to keep the text selection toolbar open and updating while you drag some selection around:

![out](https://user-images.githubusercontent.com/389558/176510941-a4129d88-6c8e-4c8c-98b7-8cb6e9bfefa6.gif)

### Steps to reproduce

  1. Run an app with a text input, such as the example below, on desktop.
  2. Right click somewhere on the text to open the text selection toolbar.
  3. Left click and drag somewhere else on the text.

Expected: The menu closes and selection does not change (tested on Linux).
Actual: The menu stays open and selection begins.

<details>

<summary>Code</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(title),
      ),
      body: const Center(
        child: TextField(),
      ),
    );
  }
}
```

</details>

**Comment by TahaTesser** [comment]
investigated this, looks like an easy fix, need to write test tho.
