### ISSUE TITLE
Unable to load local json file from "assets" folder in Flutter Package project.

### ISSUE THREAD

**Issue by hemandroid** [flutter/flutter#106847]
Hello everyone, 

I have created a flutter package project, and I've been using a local json config file and it was not loading. I have tried multiple ways to load it. Please check the below log and do the needful.

```
E/flutter (17332): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: Unable to load asset: assets/JsonConfig/test.json
E/flutter (17332): #0      PlatformAssetBundle.load (package:flutter/src/services/asset_bundle.dart:237:7)
E/flutter (17332): <asynchronous suspension>
E/flutter (17332): #1      AssetBundle.loadString (package:flutter/src/services/asset_bundle.dart:72:27)
E/flutter (17332): <asynchronous suspension>
E/flutter (17332): #2      _CustomDropDownState.readJson (package:uitoolkit/src/dropDown/custom_dropdown.dart:34:29)
E/flutter (17332): <asynchronous suspension>
E/flutter (17332): 
```

**Comment by rish07** [comment]
Hey @hemandroid,

Can you please attach the following:

1. Output of `flutter doctor -v`
2. pubspec.yaml

Also please confirm you have hot restarted your project and are still facing the issue.

**Comment by exaby73** [comment]
Along with @rish07's suggestion, could you also produce a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)?

**Comment by hemandroid** [comment]
Hi @rish07 Please check the below answers for your questions.

<img width="678" alt="Screenshot 2022-06-30 at 11 05 50 AM" src="https://user-images.githubusercontent.com/12004982/176695493-64274343-177a-4147-bfc1-32133adaa460.png">

Json files have been added in both 
assets/
assets/mocks/
assets/JsonConfig/test.json as well

flutter doctor -v

``` 
hemandroid@macbook ~ % flutter doctor -v
[✓] Flutter (Channel stable, 3.0.1, on macOS 12.3 21E230 darwin-x64, locale
    en-GB)
    • Flutter version 3.0.1 at /Users/hemandroid/flutter_sdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (6 weeks ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version
    32.1.0-rc1)
    • Android SDK at /Users/hemandroid/Library/Android/sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code (version 1.66.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.38.1

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.3 21E230 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 103.0.5060.53

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!```

**Comment by exaby73** [comment]
Thank you. Can you also share a code sample?

**Comment by hemandroid** [comment]
``@exaby73 It's an in-house flutter package we are building for our company's projects. So I can't share the code sample. The problem is easy to understand, I'm unable to load the assets from the **Flutter Package Project**, and when searched in StackOverflow, many people mentioned using this

**WidgetsFlutterBinding.ensureInitialized()** inside main() method.

But here my case is different, I don't have any main() method in my package lib folder. I'm having only these

```
library uitoolkit;

export 'src/assets/assets.dart';
export 'src/buttons/buttons.dart';
export 'src/core/enum/toolkit_assets.dart';
export 'src/core/constants/shared_strings.dart';
export 'src/core/theme/colors.dart';
export 'src/core/theme/theme.dart';
export 'src/core/utils.dart';
export 'src/list_tiles/list_info_tile.dart';
export 'src/scaffold/common_scaffold.dart';
export 'src/generic_page/base_generic_icon_page.dart';
export 'src/form_fields/text_field.dart';
export 'src/expandable_fab/expandable_fab.dart';
export 'src/uitoolkit.dart';
export 'src/typography.dart';
```

So I'm trying to load the JSON file in one of the above-mentioned export dart files and I'm accessing that dart file in the example application demo. But it's not working

The error was pointed to here

```
/// An [AssetBundle] that loads resources using platform messages.
class PlatformAssetBundle extends CachingAssetBundle {
  @override
  Future<ByteData> load(String key) async {
    final Uint8List encoded = utf8.encoder.convert(Uri(path: Uri.encodeFull(key)).path);
    final ByteData? asset =
        await ServicesBinding.instance.defaultBinaryMessenger.send('flutter/assets', encoded.buffer.asByteData());
    if (asset == null)
      throw FlutterError('Unable to load asset: $key');
    return asset;
  }
}
```
the asset is getting null for the package-level project. But the same way of loading the asset is working for a normal Flutter Project, as we can able to initialize the **WidgetsFlutterBinding.ensureInitialized()**  under the main() method.

@RedBrogdon @filiph @timsneath

**Comment by exaby73** [comment]
In the application you are using this package in, you can call `WidgetsFlutterBinding.ensureInitialized()` in `main()`. Have you tried that?

**Comment by huanghui1998hhh** [comment]
I'm facing the same problem. But only on platform Windows. Other platforms are OK.

**Comment by huanghui1998hhh** [comment]
> I'm facing the same problem. But only on platform Windows. Other platforms are OK.

Sorry, in my case, i miss the assets folder in front, but some platform don't need it also OK. Have someone can help me about this?

**Comment by exaby73** [comment]
@huanghui1998hhh Can you post a code sample and reproducible steps?

**Comment by abdulrojakdev** [comment]
> @huanghui1998hhh Can you post a code sample and reproducible steps?

same error as this

final data = json.decode(await readPermissionResourceData());

  Future<String> readPermissionResourceData() async {
    final jsonText = await rootBundle.loadString(pathJson);
    return jsonText;
  }

**Comment by exaby73** [comment]
@abdulrojakdev Can you providea [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)?

**Comment by abdulrojakdev** [comment]
> Hi @rish07 Please check the below answers for your questions.
> 
> <img alt="Screenshot 2022-06-30 at 11 05 50 AM" width="678" src="https://user-images.githubusercontent.com/12004982/176695493-64274343-177a-4147-bfc1-32133adaa460.png">
> 
> Json files have been added in both assets/ assets/mocks/ assets/JsonConfig/test.json as well
> 
> flutter doctor -v
> 
> ```
> hemandroid@macbook ~ % flutter doctor -v
> [✓] Flutter (Channel stable, 3.0.1, on macOS 12.3 21E230 darwin-x64, locale
>     en-GB)
>     • Flutter version 3.0.1 at /Users/hemandroid/flutter_sdk/flutter
>     • Upstream repository https://github.com/flutter/flutter.git
>     • Framework revision fb57da5f94 (6 weeks ago), 2022-05-19 15:50:29 -0700
>     • Engine revision caaafc5604
>     • Dart version 2.17.1
>     • DevTools version 2.12.2
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version
>     32.1.0-rc1)
>     • Android SDK at /Users/hemandroid/Library/Android/sdk
>     • Platform android-32, build-tools 32.1.0-rc1
>     • Java binary at: /Applications/Android
>       Studio.app/Contents/jre/Contents/Home/bin/java
>     • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
>     • All Android licenses accepted.
> 
> [✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • CocoaPods version 1.11.2
> 
> [✓] Chrome - develop for the web
>     • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
> 
> [✓] Android Studio (version 2021.1)
>     • Android Studio at /Applications/Android Studio.app/Contents
>     • Flutter plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/9212-flutter
>     • Dart plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/6351-dart
>     • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
> 
> [✓] VS Code (version 1.66.2)
>     • VS Code at /Applications/Visual Studio Code.app/Contents
>     • Flutter extension version 3.38.1
> 
> [✓] Connected device (2 available)
>     • macOS (desktop) • macos  • darwin-x64     • macOS 12.3 21E230 darwin-x64
>     • Chrome (web)    • chrome • web-javascript • Google Chrome 103.0.5060.53
> 
> [✓] HTTP Host Availability
>     • All required HTTP hosts are available
> 
> • No issues found!```
> ```

hello sir, have you found a solution?

**Comment by hemandroid** [comment]
Hi @abdulrojakdev I haven't found any solution yet and no one haven't suggested anything yet.

**Comment by exaby73** [comment]
@abdulrojakdev @hemandroid Lot's of packages ask the user of the package they are using to call `WidgetsFlutterBinding.ensureInitialized()` in their `main()`. Example [camera](https://pub.dev/packages/camera), [flutter_stripe](https://pub.dev/packages/flutter_stripe).

**Comment by abdulrojakdev** [comment]
> @abdulrojakdev @hemandroid Lot's of packages ask the user of the package they are using to call `WidgetsFlutterBinding.ensureInitialized()` in their `main()`. Example [camera](https://pub.dev/packages/camera), [flutter_stripe](https://pub.dev/packages/flutter_stripe).

I've been doing that from the start

**Comment by exaby73** [comment]
@abdulrojakdev Can you provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) so that we can investigate it further?

**Comment by alamsz** [comment]
Hi @hemandroid , try to load it like this

`String jsonString =
        await rootBundle.loadString('packages/yourpackagename/assets/yourfile.json');`

**Comment by abdulrojakdev** [comment]
> Hi @hemandroid , try to load it like this
> 
> `String jsonString = await rootBundle.loadString('packages/yourpackagename/assets/yourfile.json');`

I succeeded this way. Thank you
