### ISSUE TITLE
Plugin-architecture for services

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#1068]
Some way to build and distribute flutter services on iOS and Android.

One could imagine a model for simple apps that could involve adding an entry to `flutter.yaml` e.g.:

```
- services:
  - keyboard
  - my_custom: my/custom/service
```

But with our current iOS build system that can't work.  Presumably we need a way (a framework? and iOS template?) to generate Frameworks that iOS can include?

Maybe `ninja` needs to be required for redistributable service building in the short-term?  Would services be packaged as pub packages?  I suspect this needs to start as a design proposal before this bug can be actionable.  Writing this down here and assigning to myself for now.

**Comment by eseidelGoogle** [comment]
@mpcomplete is looking at similar.

**Comment by abarth** [comment]
We have this now.
