### ISSUE TITLE
[go_router] document the route matching behavior when there are multiple matches

### ISSUE THREAD

**Issue by ValentinVignal** [flutter/flutter#106851]
## Use case

Right now, the `GoRouter` and `GoRoute` classes have a parameter `List<GoRoute> routes`. The order of the routes in the list doesn't matter :

[From the doc](https://gorouter.dev/declarative-routing)
>Only a single route can be matched, specifically the one whose path matches the entire location (and so it doesn't matter in which order you list your routes).

So it would make more sense to use a `Set<GoRoute>` in my opinion. We could still support the `List<GoRoute>` by only requesting an `Iterable<GoRoute>`

## Proposal

The `routes` parameter could be an `Iterable<GoRoute>` instead of `List<GoRoute>`.

**Comment by exaby73** [comment]
Hello @ValentinVignal. Your proposal is that it would make sense for `routes` to be a `Set` since only one location would match. But to be backward-compatible, you're suggesting to use an `Iterable`. But using an `Interable` wouldn't convey the information that a `Set` would and, I think most, users would still opt for a `List`.

**Comment by ValentinVignal** [comment]
>  But using an Interable wouldn't convey the information that a Set would and

I'm not sure what you mean by that. Do you mean that users won't be able to know they can use a `Set`? 

>  I think most, users would still opt for a List.

I don't know about that, maybe you are right. But with `Iterable`, at least the few users that want to use a `Set` will be able to do so.

**Comment by exaby73** [comment]
> Do you mean that users won't be able to know they can use a Set?
No I meant the semantics of having a `Set`. With a `Set`, it's clear that this parameter's order doesn't matter and that duplicates aren't allowed. While `Iterable` doesn't have the same semantics.

Anyways, I will keep this feature request open for the team to bring some insights to. Thanks for filing it :)

**Comment by bambinoua** [comment]
I think using of `Iterable` is useless because it brings nothing except disadvantages. For example if someone need to do some `List` related actions he will need to convert the `Iterable` to the `List` (why if we have this already?). Using `Set` make sense because this defends progremmer from route duplicates.

**Comment by ValentinVignal** [comment]
> For example if someone need to do some `List` related actions he will need to convert the `Iterable` to the `List`

If the order of the routes doesn't matter, why would someone need to do some `List` related actions?

> Using Set make sense because this defends progremmer from route duplicates.

The issue I have with using a `Set` is that it is a breaking change.

**Comment by chunhtai** [comment]
The order does matter if you have multiple matches, it will always return the first match.

**Comment by ValentinVignal** [comment]
> The order does matter if you have multiple matches, it will always return the first match.

Then, shouldn't the doc be updated  Because _"Only a single route can be matched, specifically the one whose path matches the entire location (and so it doesn't matter in which order you list your routes)."_ says the opposite

**Comment by chunhtai** [comment]
It appears we forgot to update the doc

**Comment by chunhtai** [comment]
closing this as the documentation update will be part of the gorouter.dev migration
