### ISSUE TITLE
IOS build only replaces in the build method variable names that start with underscores

### ISSUE THREAD

**Issue by arualana** [flutter/flutter#106855]
Flutter version 3.0.3

This did not happen before 3 version. I think it should either happen on every build, including development mode or it should not happen ever.

Example:

```
@override
  Widget build(BuildContext context) {
    final String? someVar = widget.someVar;
    final String _someVar = "bbb";
    return Container(
      child: Text(_someVar);
    );
  }
```
In this example, on the ios release build, you will get errors that Can't declare 'someVar' because it was already used in this scope. And that The argument type 'String?' can't be assigned to the parameter type 'String'

If this happened in every build it would be alright, but it only happens in iOS which is very confusing.

Thank you

**Comment by danagbemava-nc** [comment]
Hi @arualana, thanks for filing the issue. 

Please provide a complete minimal reproducible code sample along with steps to reproduce as well as any logs that may be relevant and screen recordings if applicable. 

Thank you

**Comment by arualana** [comment]
Thank you for your response. The reproducible example is the one I posted in the issue, then you need to build that code for an ios release version.

Then the errors specific to this example are also posted in the issue, I copy and paste them again, being variable names and data types different in each use case



`Can't declare 'someVar' because it was already used in this scope. `

`The argument type 'String?' can't be assigned to the parameter type 'String'`

_someVar and someVar are different variables, in Android every build type, but not on ios, which compiles as if they were the same

I hope it clear, else you can ask me

**Comment by danagbemava-nc** [comment]
Hi @arualana, at what point do you get the errors you're pointing out? 

I used the code sample below and I was able to run the iOS build without any issues. 

I also run it in release mode on my device and there was no issue.

[log.txt](https://github.com/flutter/flutter/files/9019900/log.txt)

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  static const String _title = 'Flutter Code Sample';

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: _title,
      home: Scaffold(
        appBar: AppBar(title: const Text(_title)),
        body: const MyTextEditor(),
      ),
    );
  }
}

class MyTextEditor extends StatefulWidget {

  const MyTextEditor({
    Key? key,
    this.someVar,
  }) : super(key: key);

  final String? someVar;

  @override
  State<MyTextEditor> createState() => _MyTextEditorState();
}

class _MyTextEditorState extends State<MyTextEditor> {

  @override
  Widget build(BuildContext context) {
    final String? someVar = widget.someVar;
    final String _someVar = "bbb";
    return Container(child: Text(_someVar));
  }
}

```
</details>

Kindly share the exact conditions required to reproduce the bug. 

Thank you
