### ISSUE TITLE
[TextField]The text cursor can be dragged in windows, which is inconsistent with the native behavior

### ISSUE THREAD

**Issue by yixiaco** [flutter/flutter#106843]
## Video
https://user-images.githubusercontent.com/30982989/176576206-7bf0a739-0a78-431a-a232-2fb30144835a.mp4

**Comment by maheshmnj** [comment]
Hi @yixiaco, Thanks for filing the issue. This is fixed on beta, You can expect the fix in the upcoming stable release.

closing as duplicate of https://github.com/flutter/flutter/issues/106676
