### ISSUE TITLE
Document how to create xcconfig file for running devicelab tests locally on iOS

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#10697]
When I run an iOS devicelab test locally, it tells me to specify a xcconfig. We should document on https://github.com/flutter/flutter/tree/master/dev/devicelab how to create that file and where the required information can be found.

/cc @yjbanov

**Comment by yjbanov** [comment]
Do you have a preference for where to put such a document? I've used Wiki in the past, e.g.: https://github.com/flutter/flutter/wiki/Flutter-CLI-crash-reporting

**Comment by yjbanov** [comment]
The error message would provide a link to the wiki page.

**Comment by goderbauer** [comment]
I would have expected to find the information in the readme for device lab: https://github.com/flutter/flutter/blob/master/dev/devicelab/README.md

That one also tells me everything else I need to know about running a task.

**Comment by goderbauer** [comment]
We should also re-evaluate if we still need the xcconfig. Now that @xster added support for automatically selecting the correct certificates for signing it might no longer be needed...
