### ISSUE TITLE
WebView packages causing flutter embedding error while build my flutter apk. but it runs fine on debug mode

### ISSUE THREAD

**Issue by sublime247** [flutter/flutter#106995]
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by sublime247** [comment]
Gradle task assembleRelease failed with exit code 1
PS C:\Users\BASHIR\Documents\Flutter-Apps\MyFirstApp\cashbuddy> flutter run
Launching lib\main.dart on vivo 2015 in debug mode...
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Running Gradle task 'assembleDebug'...                            182.3s
√  Built build\app\outputs\flutter-apk\app-debug.apk.
Installing build\app\outputs\flutter-apk\app.apk...                30.1s
W/FlutterActivityAndFragmentDelegate(13016): A splash screen was provided to Flutter, but this is deprecated. See flutter.dev/go/android-splas
migration steps.
Syncing files to device vivo 2015...                               554ms

Flutter run key commands.
r Hot reload. 
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

 Running with sound null safety 

An Observatory debugger and profiler on vivo 2015 is available at: http://127.0.0.1:65105/EPZFrDCNDIY=/
The Flutter DevTools debugger and profiler on vivo 2015 is available at: http://127.0.0.1:9101?uri=http://127.0.0.1:65105/EPZFrDCNDIY=/
I/WebViewFactory(13016): Loading com.google.android.webview version 102.0.5005.125 (code 500512533)
W/ample.cashbudd(13016): Accessing hidden method Landroid/os/Trace;->isTagEnabled(J)Z (greylist, reflection, allowed)
W/ample.cashbudd(13016): Accessing hidden method Landroid/os/Trace;->traceBegin(JLjava/lang/String;)V (greylist, reflection, allowed)
W/ample.cashbudd(13016): Accessing hidden method Landroid/os/Trace;->traceEnd(J)V (greylist, reflection, allowed)
W/ample.cashbudd(13016): Accessing hidden method Landroid/os/Trace;->asyncTraceBegin(JLjava/lang/String;I)V (greylist, reflection, allowed)
W/ample.cashbudd(13016): Accessing hidden method Landroid/os/Trace;->asyncTraceEnd(JLjava/lang/String;I)V (greylist, reflection, allowed)
I/cr_WVCFactoryProvider(13016): Loaded version=102.0.5005.125 minSdkVersion=29 isBundle=true multiprocess=true packageId=2
I/cr_LibraryLoader(13016): Successfully loaded native library
I/cr_CachingUmaRecorder(13016): Flushed 9 samples from 9 histograms.
W/ample.cashbudd(13016): Accessing hidden method Landroid/media/AudioManager;->getOutputLatency(I)I (greylist, reflection, allowed)
W/cr_media(13016): Requires BLUETOOTH permission
I/BufferQueue(13016): [unnamed-13016-0](this:0x772acaa000,id:0,api:0,p:-1,c:-1) BufferQueue core=(13016:com.example.cashbuddy)
W/ample.cashbuddy(13016): type=1400 audit(0.0:78322): avc: denied { read } for name="u:object_r:debug_bq_dump_prop:s0" dev="tmpfs" ino=186 scoted_app:s0:c54,c257,c512,c768 tcontext=u:object_r:debug_bq_dump_prop:s0 tclass=file permissive=0
E/libc    (13016): Access denied finding property "vendor.debug.bq.dump"
I/BufferQueueConsumer(13016): [unnamed-13016-0](this:0x772acaa000,id:0,api:0,p:-1,c:13016) connect(C): consumer=(13016:com.example.cashbuddy) true
E/libc    (13016): Access denied finding property "vendor.debug.bq.dump"
I/BufferQueueConsumer(13016): [unnamed-13016-0](this:0x772acaa000,id:0,api:0,p:-1,c:13016) setConsumerName: unnamed-13016-0
W/ample.cashbuddy(13016): type=1400 audit(0.0:78323): avc: denied { read } for name="u:object_r:debug_bq_dump_prop:s0" dev="tmpfs" ino=186 scoted_app:s0:c54,c257,c512,c768 tcontext=u:object_r:debug_bq_dump_prop:s0 tclass=file permissive=0
E/libc    (13016): Access denied finding property "vendor.debug.bq.dump"
I/BufferQueueConsumer(13016): [SurfaceTexture-0-13016-0](this:0x772acaa000,id:0,api:0,p:-1,c:13016) setConsumerName: SurfaceTexture-0-13016-0
E/NetdClient(13016): querySockNetidForUid nid:0, uid:10310, command.cmdId:11, id:0
W/IMGSRV  (13016): glGetString:4370: Override GL_RENDERER PowerVR SGX Doma
I/chatty  (13016): uid=10310(com.example.cashbuddy) Chrome_InProcGp identical 1 line
W/IMGSRV  (13016): glGetString:4370: Override GL_RENDERER PowerVR SGX Doma 
W/IMGSRV  (13016): glGetString:4370: Override GL_RENDERER PowerVR SGX Doma
W/IMGSRV  (13016): glGetString:4370: Override GL_RENDERER PowerVR SGX Doma
D/Surface (13016): Surface::connect(this=0x772abf4000,api=1)
I/BufferQueueProducer(13016): [SurfaceTexture-0-13016-0](this:0x772acaa000,id:0,api:1,p:13016,c:13016) connect(P): api=1 producer=(13016:com.e) producerControlledByApp=true
D/Surface (13016): Surface::setBufferCount(this=0x772abf4000,bufferCount=3)
W/Gralloc3(13016): allocator 3.x is not supported
E/ion     (13016): ioctl c0044901 failed with code -1: Invalid argument
I/BufferQueueConsumer(13016): [SurfaceTexture-0-13016-0](this:0x772acaa000,id:0,api:1,p:13016,c:13016) setDefaultBufferSize: width=720 height=
E/NetdClient(13016): querySockNetidForUid nid:0, uid:10310, command.cmdId:11, id:0
W/IMGSRV  (13016): glGetString:4370: Override GL_RENDERER PowerVR SGX Doma 
W/IMGSRV  (13016): glGetString:4370: Override GL_RENDERER PowerVR SGX Doma 
W/IMGSRV  (13016): glGetString:4370: Override GL_RENDERER PowerVR SGX Doma
W/IMGSRV  (13016): glGetString:4370: Override GL_RENDERER PowerVR SGX Doma 
W/IMGSRV  (13016): glGetString:4370: Override GL_RENDERER PowerVR SGX Doma
W/IMGSRV  (13016): glGetString:4370: Override GL_RENDERER PowerVR SGX Doma 
W/IMGSRV  (13016): glGetString:4370: Override GL_RENDERER PowerVR SGX Doma
E/NetdClient(13016): querySockNetidForUid nid:0, uid:10310, command.cmdId:11, id:0
W/IMGSRV  (13016): glGetString:4370: Override GL_RENDERER PowerVR SGX Doma 
I/chatty  (13016): uid=10310(com.example.cashbuddy) Chrome_InProcGp identical 27 lines
W/IMGSRV  (13016): glGetString:4370: Override GL_RENDERER PowerVR SGX Doma 
W/ample.cashbudd(13016): Accessing hidden method Llibcore/io/Memory;->peekLong(JZ)J (greylist, reflection, allowed)
W/ample.cashbudd(13016): Accessing hidden method Llibcore/io/Memory;->pokeLong(JJZ)V (greylist, reflection, allowed)
W/ample.cashbudd(13016): Accessing hidden method Llibcore/io/Memory;->pokeInt(JIZ)V (greylist, reflection, allowed)
W/ample.cashbudd(13016): Accessing hidden method Llibcore/io/Memory;->peekInt(JZ)I (greylist, reflection, allowed)
W/ample.cashbudd(13016): Accessing hidden method Llibcore/io/Memory;->pokeByte(JB)V (greylist, reflection, allowed)
W/ample.cashbudd(13016): Accessing hidden method Llibcore/io/Memory;->peekByte(J)B (greylist, reflection, allowed)
W/ample.cashbudd(13016): Accessing hidden method Llibcore/io/Memory;->pokeByteArray(J[BII)V (greylist, reflection, allowed)
W/ample.cashbudd(13016): Accessing hidden method Llibcore/io/Memory;->peekByteArray(J[BII)V (greylist, reflection, allowed)
W/ample.cashbudd(13016): Accessing hidden method Lsun/misc/Unsafe;->objectFieldOffset(Ljava/lang/reflect/Field;)J (greylist,core-platform-api,owed)
W/ample.cashbudd(13016): Accessing hidden method Lsun/misc/Unsafe;->getLong(Ljava/lang/Object;J)J (greylist,core-platform-api, reflection, all
W/ample.cashbudd(13016): Accessing hidden field Ljava/nio/Buffer;->address:J (greylist, reflection, allowed)
W/ample.cashbudd(13016): Accessing hidden method Lsun/misc/Unsafe;->arrayBaseOffset(Ljava/lang/Class;)I (greylist,core-platform-api, reflectio
W/ample.cashbudd(13016): Accessing hidden method Lsun/misc/Unsafe;->arrayIndexScale(Ljava/lang/Class;)I (greylist, reflection, allowed)
W/ample.cashbudd(13016): Accessing hidden method Lsun/misc/Unsafe;->getInt(Ljava/lang/Object;J)I (greylist, reflection, allowed)
W/ample.cashbudd(13016): Accessing hidden method Lsun/misc/Unsafe;->putInt(Ljava/lang/Object;JI)V (greylist, reflection, allowed)
W/ample.cashbudd(13016): Accessing hidden method Lsun/misc/Unsafe;->getLong(Ljava/lang/Object;J)J (greylist,core-platform-api, reflection, all
W/ample.cashbudd(13016): Accessing hidden method Lsun/misc/Unsafe;->putLong(Ljava/lang/Object;JJ)V (greylist, reflection, allowed)
W/ample.cashbudd(13016): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, reflection, al
W/ample.cashbudd(13016): Accessing hidden method Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, reflection, a
W/ample.cashbudd(13016): Accessing hidden method Lsun/misc/Unsafe;->putInt(Ljava/lang/Object;JI)V (greylist, linking, allowed)
W/ample.cashbudd(13016): Accessing hidden method Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, linking, allo
E/IMGSRV  (13016): :0: IsTextureConsistent: IMGEGLImage is not consistent
E/IMGSRV  (13016): :0: IsTextureConsistent: IMGEGLImage is not consistent
D/NetworkSecurityConfig(13016): No Network Security Config specified, using platform default
W/IMGSRV  (13016): glGetString:4370: Override GL_RENDERER PowerVR SGX Doma 
W/IMGSRV  (13016): glGetString:4370: Override GL_RENDERER PowerVR SGX Doma 
E/NetdClient(13016): querySockNetidForUid nid:0, uid:10310, command.cmdId:11, id:0
I/BufferQueueProducer(13016): [SurfaceTexture-0-13016-0](this:0x772acaa000,id:0,api:1,p:13016,c:13016) queueBuffer: fps=2.12 dur=1415.66 max=9
E/NetdClient(13016): querySockNetidForUid nid:0, uid:10310, command.cmdId:11, id:0
E/NetdClient(13016): querySockNetidForUid nid:0, uid:10310, command.cmdId:11, id:0
E/NetdClient(13016): querySockNetidForUid nid:0, uid:10310, command.cmdId:11, id:0
I/BufferQueueProducer(13016): [SurfaceTexture-0-13016-0](this:0x772acaa000,id:0,api:1,p:13016,c:13016) queueBuffer: fps=3.20 dur=2816.47 max=2E/NetdClient(13016): querySockNetidForUid nid:0, uid:10310, command.cmdId:11, id:0
I/Choreographer(13016): Skipped 84 frames!  The application may be doing too much work on its main thread.
I/OpenGLRenderer(13016): Davey! duration=1427ms; Flags=0, IntendedVsync=28749750152760, Vsync=28751145501540, OldestInputEvent=922337203685477tEvent=0, HandleInputStart=28751159557944, AnimationStart=28751162104559, PerformTraversalsStart=28751169221251, DrawStart=28751172693867, Syn505174, SyncStart=28751174264790, IssueDrawCommandsStart=28751174585944, SwapBuffers=28751176445251, FrameCompleted=28751178749251, DequeueBuf00, QueueBufferDuration=1160000,
I/BufferQueueProducer(13016): [SurfaceTexture-0-13016-0](this:0x772acaa000,id:0,api:1,p:13016,c:13016) queueBuffer: fps=0.47 dur=8424.92 max=7W/cr_AwContents(13016): WebView.destroy() called while WebView is still attached to window.
I/GED     (13016): ged_boost_gpu_freq, level 100, eOrigin 2, final_idx 2, oppidx_max 2, oppidx_min 0
I/Choreographer(13016): Skipped 34 frames!  The application may be doing too much work on its main thread.
D/Surface (13016): Surface::disconnect(this=0x777b90e000,api=1)
D/Surface (13016): Surface::disconnect(this=0x777b90e000,api=-1)
D/Surface (13016): Surface::disconnect(this=0x7781333000,api=1)
Lost connection to device.



it run fine with flutter run

**Comment by sublime247** [comment]
PS C:\Users\BASHIR\Documents\Flutter-Apps\MyFirstApp\cashbuddy> flutter build apk

 Building with sound null safety 

[Fatal Error] flutter_embedding_release-1.0.0-6ba2af10bb05c88a2731482cedf2cfd11cf5af0b.pom:11:14: Element type "dependenci" must be followed by either attribute specifications, ">" or "/>".

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeReleaseAssets'.
> Could not resolve all files for configuration ':app:releaseRuntimeClasspath'.
   > Could not resolve io.flutter:flutter_embedding_release:1.0.0-6ba2af10bb05c88a2731482cedf2cfd11cf5af0b.
     Required by:
         project :app > project :webview_flutter_android
      > Could not resolve io.flutter:flutter_embedding_release:1.0.0-6ba2af10bb05c88a2731482cedf2cfd11cf5af0b.
         > Could not parse POM https://storage.googleapis.com/download.flutter.io/io/flutter/flutter_embedding_release/1.0.0-6ba2af10bb05c88a2731482cedf2cfd11cf5af0b/flutter_embedding_release-1.0.0-6ba2af10bb05c88a2731482cedf2cfd11cf5af0b.pom
            > Element type "dependenci" must be followed by either attribute specifications, ">" or "/>".

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 38s
Running Gradle task 'assembleRelease'...                           40.4s
Gradle task assembleRelease failed with exit code 1

this is what it logs if i try to build the apk

**Comment by maheshmnj** [comment]
Hi @sublime247, Thanks for filing the issue. I tried building the release version of the app and it seems to build fine.
Can you please share the output of `flutter doctor -v` && `flutter build apk -v` in a text file?

<details>
<summary>flutter build apk</summary>

```
mahesh@Maheshs-MacBook-Air-M1 sample % flutter build apk

💪 Building with sound null safety 💪

w: Runtime JAR files in the classpath should have the same version. These files were found in the classpath:
    /Users/mahesh/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk8/1.5.30/5fd47535cc85f9e24996f939c2de6583991481b0/kotlin-stdlib-jdk8-1.5.30.jar (version 1.5)
    /Users/mahesh/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk7/1.6.10/e1c380673654a089c4f0c9f83d0ddfdc1efdb498/kotlin-stdlib-jdk7-1.6.10.jar (version 1.6)
    /Users/mahesh/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.6.21/11ef67f1900634fd951bad28c53ec957fabbe5b8/kotlin-stdlib-1.6.21.jar (version 1.6)
    /Users/mahesh/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-common/1.6.21/5e5b55c26dbc80372a920aef60eb774b714559b8/kotlin-stdlib-common-1.6.21.jar (version 1.6)
w: Some runtime JAR files in the classpath have an incompatible version. Consider removing them from the classpath
w: Runtime JAR files in the classpath should have the same version. These files were found in the classpath:
    /Users/mahesh/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk8/1.5.30/5fd47535cc85f9e24996f939c2de6583991481b0/kotlin-stdlib-jdk8-1.5.30.jar (version 1.5)
    /Users/mahesh/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk7/1.6.10/e1c380673654a089c4f0c9f83d0ddfdc1efdb498/kotlin-stdlib-jdk7-1.6.10.jar (version 1.6)
    /Users/mahesh/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.6.21/11ef67f1900634fd951bad28c53ec957fabbe5b8/kotlin-stdlib-1.6.21.jar (version 1.6)
    /Users/mahesh/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-common/1.6.21/5e5b55c26dbc80372a920aef60eb774b714559b8/kotlin-stdlib-common-1.6.21.jar (version 1.6)
w: Some runtime JAR files in the classpath have an incompatible version. Consider removing them from the classpath
Running Gradle task 'assembleRelease'...                           35.4s
✓  Built build/app/outputs/flutter-apk/app-release.apk (18.2MB).
mahesh@Maheshs-MacBook-Air-M1 sample % 
```
</details>

<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel stable, 3.0.3, on macOS 12.4 21F79 darwin-arm, locale en-IN)
    • Flutter version 3.0.3 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 676cefaaff (5 days ago), 2022-06-22 11:34:49 -0700
    • Engine revision ffe7b86a1e
    • Dart version 2.17.5
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-32, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.67.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.43.20220621

[✓] Connected device (3 available)
    • sdk gphone arm64 (mobile) • emulator-5554 • android-arm64  • Android 11 (API 30) (emulator)
    • macOS (desktop)           • macos         • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)              • chrome        • web-javascript • Google Chrome 103.0.5060.53

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>
