### ISSUE TITLE
Flutter app doesn't resume from background [Android]

### ISSUE THREAD

**Issue by sede10** [flutter/flutter#106912]
## Steps to Reproduce

Create new flutter project in Android Studio. 
Run app.
Force device to go low on memory (clean/optimize memory in device settings, or open other apps)
Go back to app.

App is stuck at splash screen. I checked that Android activity lifecycle callbacks are being called, but no Dart code is being executed and there are no log messages from Flutter.

This happens randomly 20%-50% of time depending on device.

```
    • Flutter version 3.0.2 at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cd41fdd495 (3 weeks ago), 2022-06-08 09:52:13 -0700
    • Engine revision f15f824b57
    • Dart version 2.17.3
    • DevTools version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at C:\Users\A\AppData\Local\Android\sdk
    • Platform android-32, build-tools 32.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.
[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

```

**Comment by exaby73** [comment]
Hello @sede10. I am unable to reproduce this issue. I have open many applications causing the Flutter one to be killed by the OS. Upon opening the app, I see the default Flutter splash screen for about 2 seconds before the app starts up again. Can you provide me with which device you're testing on? Can you also provide some sample code you're using to verify that Dart code isn't being called? A sample repo would be ideal

**Comment by exaby73** [comment]
I am still not able to reproduce this issue. There's a similar issue https://github.com/flutter/flutter/issues/96875. I think this is happening due to low memory. Are you able to get any traces using [this method](https://medium.com/flutter/profiling-flutter-applications-using-the-timeline-a1a434964af3#a499)?
