### ISSUE TITLE
[autosubmit] Bot is evaluating tree status incorrectly

### ISSUE THREAD

**Issue by Piinks** [flutter/flutter#106916]
https://github.com/flutter/flutter/pull/106795#issuecomment-1171780210

The bot removed the autosubmit label because the tree is red. This should not happen, the label should be able to stay so that when the tree turns green is can be merged.

Also saw this happen on another PR today: https://github.com/flutter/flutter/pull/105549#issuecomment-1171460318

**Comment by ricardoamador** [comment]
I have verified this bug. Working on a fix now.
