### ISSUE TITLE
Windows LUCI postsubmit tests failing on stable

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#106900]
Now that go/flutter-build works for flutter/plugins and flutter/packages has support for flutter/plugins and flutter/packages, I noticed that our Windows post-submit tests for `stable` are all failing, and apparently have been for a long time (forever?). We didn't notice because of LUCI tests not reporting post-submit results to GitHub (I'm not sure why, but that's always been true).

Example:
https://ci.chromium.org/ui/p/flutter/builders/prod/Windows%20win32-platform_tests%20stable/1669/overview

Every failure is:
```
fatal: reference is not a tree: <some hash>
```

I'm not sure why this only affecting stable checkout. Perhaps a recipe error, or a problem with the mirror?

**Comment by keyonghan** [comment]
This is a different issue.

The flutter/packages is checking out the repo correctly (with mirrored commit ready), but as for `refs/heads/stable` ref, it is using the same packages commit for the flutter/flutter checkout: https://cs.opensource.google/flutter/recipes/+/main:recipe_modules/repo_util/api.py;l=208

@stuartmorgan What version of flutter is expected to use for this builder 1Windows win32-platform_tests stable`?

**Comment by stuartmorgan** [comment]
It should be the latest `stable` of flutter/flutter.

(At some point I'd like to switch to a pin+roller for stable, like we already did for master, but it hasn't been a priority since out-of-band failures on stable are much rarer.)

**Comment by keyonghan** [comment]
> (At some point I'd like to switch to a pin+roller for stable, like we already did for master, but it hasn't been a priority since out-of-band failures on stable are much rarer.)

Considering we want to switch to pin+roller anyway, does it make sense we land this change now? It should fix the issue naturally, but not sure how complex the change would be.
If not, we can try landing a fix to the recipes, which would be a specific corner patch for this issue.

**Comment by stuartmorgan** [comment]
It's not very complicated; I should be able to get it set up next week.

**Comment by keyonghan** [comment]
Thanks @stuartmorgan !

**Comment by keyonghan** [comment]
Tree is green for both repos. Thanks for the quick fix @stuartmorgan .
