### ISSUE TITLE
Manual steps required when plugin depends on FlutterFragmentActivity

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#10690]
Some plugins (right now, `google_sign_in`) require that your main app activity be an instance of `android.support.v4.app.FragmentActivity`.  Right now, Flutter makes this possible, but not as easy as it could be.  The current state is:

1. Flutter provides `io.flutter.app.FlutterFragmentActivity` out of the box, but it doesn't bundle the `android-support-v4` library, upon which that activity depends at runtime (it omits this library on purpose to avoid bloating application binaries that don't need to use `FlutterFragmentActivity`).
2. The plugin's Gradle dependency pulls in the requisite `android-support-v4` library so that the necessary classes *are* available at runtime.
3. The plugin throws a runtime exception if it detects that your app's activity isn't an instance of `FragmentActivity`.  The exception message directs the user towards `FlutterFragmentActivity`.
4. The developer has to manually edit their `MainActivity` to extend from `FlutterFragmentActivity` rather than from `FlutterActivity` in order to get back up and running.

While the good news is that we support the use case of plugins that require `FragmentActivity`, the developer experience leaves something to be desired.  Notably, the developer under normal circumstances doesn't need to hand edit anything in `MainActivity` - the auto-plugin-registration takes care of any would-be edits.  So telling them to go hand-edit the activity is a break from the developer experience they've come to expect.

**Comment by tvolkert** [comment]
@mit-mit @mravn-google

**Comment by mit-mit** [comment]
Thanks Todd, yes we should get this fixed so no manual edits are needed.

**Comment by collinjackson** [comment]
It sounds like the agreed on plan is to switch the google_sign_in plugin to doing manual connection management if the provided activity isn't a FlutterFragmentActivity. This will fix #10688 as well. I am waiting for @tvolkert to finish doing the unification of internal and external google_sign_in plugins and then I will handle this.

**Comment by mit-mit** [comment]
Sounds good

**Comment by mehmetf** [comment]
@goderbauer just looped me in on this.

Automanage (unfortunately) does not fit to plugin use case for another reason: There can only be one auto-managed GoogleApiClient in the entire activity. If multiple plugins will need to use this, we will quickly run into a problem (e.g. Google Drive plugin would need it).

How hard is it to introduce a shared library for plugins? For now, it does not keep state across different plugins such as providing the same GoogleApiClient to multiple plugins. We can put GoogleApiClientProvider there which can manage all this logic (our own automanage). Wdyt?

If this is too costly to figure out now (rolls into Google?) and we would rather wait for another plugin to need it; I would at least structure the PR in a way that makes this transition easier.

**Comment by goderbauer** [comment]
I read through the docs yesterday and it sounds like a properly manual managed connection is undistinguishable from an auto-managed connection. So, my plan for this was to just replace the auto-managed connection altogether. That should fix the issue for now.

**Comment by tvolkert** [comment]
Thanks everyone - it sounds like manual management is definitely the way to go.

**Comment by tvolkert** [comment]
> How hard is it to introduce a shared library for plugins?

@mehmetf is this still needed in a manually-managed environment?

**Comment by mehmetf** [comment]
@tvolkert Needed? No. However, manually managing a connection is not that trivial. There are a lot of corner cases and boilerplate code. If we can do that centrally for all plugins that need a GoogleApiClient, that would be nice. Since GoogleSignIn is the only plugin that needs this at the moment, there is no _need_.

**Comment by tvolkert** [comment]
Let's wait until we have two plugins that need to share code in that way to avoid over-designing it.
