### ISSUE TITLE
Investigate cause of basic_material_app_ios__size regression

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#10698]
This bug is to track the results of the investigation into the basic_material_app_ios__size release_size_in_bytes 4% regression (8589140b->8954839b) that happened after https://github.com/flutter/flutter/pull/10591.

**Comment by Hixie** [comment]
@cbracken Any luck?

**Comment by Hixie** [comment]
@cbracken We need to resolve this (either decide it's a real problem or not) soon. Because this was not rebaselined, more recent regressions (#10996) didn't turn it red, since it was already red.

**Comment by cbracken** [comment]
It's a real issue. TL;DR it looks like it was the Dart SDK roll in flutter/engine#3755.

## Download links to iOS engine builds:
[1f765cd: Baseline](https://storage.cloud.google.com/flutter_infra/flutter/1f765cdba7aee9d0a953043209b05d2c59270391/ios-release/artifacts.zip)
[f298557: Dart SDK roll](https://storage.cloud.google.com/flutter_infra/flutter/f2985577392aac89fb4ee957677042d43dcdc5ce/ios-release/artifacts.zip)
[4d423b6: First Xcode 8 build](https://storage.cloud.google.com/flutter_infra/flutter/4d423b62b99b9d943a26fad776769cfe2c7f016d/ios-release/artifacts.zip)

## Sizes (bytes)

| Release         | Xcode 7 Size | Xcode 8 Size |
|--------------|--------------|--------------|
| Baseline         | 13,410,720   | 13,410,724    |
| Dart SDK roll | 14,316,544   | 14,316,548   |
| Xcode 7->8   | 14,316,544   | 14,316,548   |

**Comment by Hixie** [comment]
cc @rmacnak-google @a-siva

**Comment by Hixie** [comment]
cc @aam

**Comment by cbracken** [comment]
The Dart roll in question was from 64ce51c to d86cb76

Commit logs for the runtime dir in this commit range:
```
git log 64ce51c..d86cb76
```

There don't appear to be any changes to the Dart SDK's `DEPS` file in this range.

**Comment by cbracken** [comment]
Bisected to a change to use BoringSSL for [SecureSocket](https://github.com/dart-lang/sdk/commit/644862bf966e6c079460258807ab3364b7e3759a) on iOS + macOS.

@bkonyi

**Comment by cbracken** [comment]
Closing since we've now got an explanation and this seems working as you'd expect given the change.
