### ISSUE TITLE
Package do not work on web platform. 

### ISSUE THREAD

**Issue by gauria24** [flutter/flutter#106931]
I am using this package to show webview in app. I also need to show the webview on web platform but it fails there.

**Comment by exaby73** [comment]
Hello @gauria24. Can you please provide which package you're using, as well as your `flutter doctor -v` output and a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)?

**Comment by gauria24** [comment]
I am using webview_flutter package to show webview on web. 
![flutter_doctor](https://user-images.githubusercontent.com/97582254/176847672-05f5e42a-8204-422d-a7bd-2191c974dca8.PNG)

**Comment by gauria24** [comment]
WebView(
              //initialUrl: 'https://providersearch.progyny.com/',
              initialUrl: 'https://micktestunilinks.herokuapp.com',
              onWebViewCreated: (WebViewController webViewController) {
                _controller = webViewController;
              },
              javascriptMode: JavascriptMode.unrestricted,
              onPageStarted: (String url) {
                appLogger.i('Page started loading: $url');
              },
              onPageFinished: (String url) {
                appLogger.i('Page finished loading: $url');
                var uri = Uri.dataFromString(url);
                Map<String, String> params = uri.queryParameters;
                String? param1;
                String? param2;
                if (params['clinic'] != null && params['dr'] != null) {
                  param1 = params['clinic']!.replaceAll(RegExp(r'%20'), ' ');
                  param2 = params['dr']!.replaceAll(RegExp(r'%20'), ' ');
                }
                if (param1 != null && param2 != null) {
                  widget.callback!(param1, param2);
                }

**Comment by demoslotid** [comment]
> I am using this package to show webview in app. I also need to show the webview on web platform but it fails there.

having the same issues here

**Comment by stuartmorgan** [comment]
`webview_flutter` doesn't support web, as it says in the platform list on https://pub.dev/packages/webview_flutter and in the package's README.

See https://pub.dev/packages/webview_flutter_web for adding preliminary web support.
