### ISSUE TITLE
Crash when running a newly created Flutter app via Xcode on an iOS device.

### ISSUE THREAD

**Issue by szakarias** [flutter/flutter#10693]
## Steps to Reproduce

`Flutter create` a new project. Set the `Team` in Xcode and run the project from Xcode on a connected device. This results in : `Thread 1: signal SIGPIPE` . It is possible to make the app run by pressing the `Continue program execution` button in the debug area about 3 times.

**Comment by mit-mit** [comment]
This repros for me on alpha:

1. `flutter create iostest`
1. `cd iostest`
1. `open ios/Runner.xcodeproj/`
1. Select Runner and set signing
1. Plug in a physical iOS device
1. Hit run

```
libsystem_kernel.dylib`writev:
    0x187a809f8 <+0>:  mov    x16, #0x79
    0x187a809fc <+4>:  svc    #0x80
->  0x187a80a00 <+8>:  b.lo   0x187a80a18               ; <+32>
    0x187a80a04 <+12>: stp    x29, x30, [sp, #-0x10]!
    0x187a80a08 <+16>: mov    x29, sp
    0x187a80a0c <+20>: bl     0x187a80f3c               ; cerror
    0x187a80a10 <+24>: mov    sp, x29
    0x187a80a14 <+28>: ldp    x29, x30, [sp], #0x10
    0x187a80a18 <+32>: ret 
```

**Comment by mit-mit** [comment]
cc @cbracken @chinmaygarde

**Comment by eseidelGoogle** [comment]
Is this a crash or just a sigpipe in debugger?  Sigpipe in debugger is tracked by https://github.com/flutter/flutter/issues/10358.

**Comment by szakarias** [comment]
Yes, looks like a duplicate.
