### ISSUE TITLE
[shared_preferences] Request for documentation about memory write process to understand at what level (dart, native, elsewhere) we need to be aware of memory wear.

### ISSUE THREAD

**Issue by whitemagehealing** [flutter/flutter#106954]
Sorry, I have a limited experience in Android and Flutter, and only have a general understanding that [Flash memory](https://en.wikipedia.org/wiki/Flash_memory#Memory_wear) can only withstand about 100,000 write cycles before it fails. It must expand small writes into large blocks so it wears down "unused" cells.

I noticed that the code in Android has the ability to only call `apply()` (async) or `commit()` (sync) as necessary after several `put`s.

```java
SharedPreferences sharedPref = getActivity().getPreferences(Context.MODE_PRIVATE);
SharedPreferences.Editor editor = sharedPref.edit();
editor.putInt(getString(R.string.saved_high_score_key), newHighScore);
editor.putInt(getString(R.string.saved_high_score_key2), newHighScore);
editor.apply();
```

However, in [shared_preferences.dart](https://github.com/flutter/plugins/blob/b5e4ad208a0651cd19e5162619a3f958ddf18cff/packages/shared_preferences/shared_preferences/lib/shared_preferences.dart), there seems to be a comment about the Flutter package `commit()` being deprecated and that a `commit()` is called with "every set".

So, if every set is a write, and if I have say 100 `set`s per save, at 5 saves a day, for 1 year, I would have:
 
     100 * 5 * 365 = 182,500 writes, which already exceeds the write cycles for a block of memory.

Using that same idea, but if I can block `put` 100 items per write, I would have:

     1 * 5 * 365 = 1,825 writes 
     100,000 / 1,852 = about 54.7 years (significantly different than 1 year)

I understand that maybe this is avoided somewhere else in this package or the OS, so there might be a link in Android documentation that I do not know about addressing this already. If you know of such a link, it would be great if you could share it with me. The closest I could find is [this](https://developer.android.com/topic/performance/memory-management).

Below the line below is a quote I read from another post talking about caching. I vaguely understand about caching itself and that the Android system cache is why we might get out of sync with long-term non-volatile memory, but it's not clear about if this caching is in RAM, Flash, or elsewhere. Granted, this question might be decoupled from software and impossible to answer, because the hardware manufacturer might take the write command to place data in whatever memory type it wants. 

### What I seek is to know if it is possible to stock up my writes to minimize wear to Flash or, if this behavior is already done by some other process, which process that is.

Or course, this question would also be applicable to the new [secured storage](https://github.com/flutter/flutter/issues/58470) as well.

Thank you for your patience in my lack of understanding.

===============================================
I'm not quite sure what you think `reload` does; the way you are using it there still doesn't actually make sense.

The first time you call `SharedPreferences.getInstance()` in any given isolate, you get an instance that has a cache of what was in the native preferences at the time you called it. Normally the native prefs are never queried again, and the cache is just kept updated by all of the `set*` calls. `reload` discards the cache and re-creates it from the native prefs again.

The point where you would want to call `reload` is *before reading*, in any scenario where prefs may have been changed in a way that bypassed the cache (either via the plugin from another isolate, or directly with native code). Calling reload after calling `set*` makes no sense, nor does calling it in the same synchronous block where you are calling `SharedPreferences.getInstance()` the first time. So as with your earlier code, your `reload` call there is doing nothing but making the code less efficient. It will not changed the observed behavior.

_Originally posted by @stuartmorgan in https://github.com/flutter/flutter/issues/101691#issuecomment-1096899038_

**Comment by stuartmorgan** [comment]
Questions about how the Android `SharedPreferences` system deals with hardware limitations of flash storage would need to be addressed to the Android team; it's beyond the scope or control of the plugin. Closing as this is not a Flutter-level issue.

> and if I have say 100 `set`s per save,

`shared_preferences` is intended for small amounts of simple data, such as user preferences. If you are setting 100 values every time you are interacting with it, you are probably using the wrong plugin, and should investigate other plugins designed for data storage.

> Below the line below is a quote I read from another post talking about caching.

The comment you've quoted (and the issue it's from) are unrelated to your question.

**Comment by whitemagehealing** [comment]
For further clarification, by "small", what exactly is the expect amount of
data and at what save rate does this package target?

I considered 100 small items as "small" and 5 accesses a day was being
really conservative.

Does this mean that the answer to my question about being able to `put` to
a single `commit/apply` will never be possible with this package and, thus,
this package is planned to always do one `put` and one `commit\apply` each
time a `set` is used?

**Comment by stuartmorgan** [comment]
> For further clarification, by "small", what exactly is the expect amount of data

There is no specific threshold.

> and at what save rate does this package target?

It doesn't; it is intended to provide access to specific platform APIs (as documented in the README). The plugin makes no guarantees about the performance of those APIs.

> I considered 100 small items (example one int) as "small" and 5 accesses a day was being really conservative.

The wrapped APIs, as their (and the plugin's) names suggest, are primarily intended for user preferences. Updating 100 preferences at a time, five times a day, every day, is not a normal use case.

> I merely mentioned the quote to explain caching

The cache being discussed there is a *read* cache, and thus entirely unrelated to your question.
