### ISSUE TITLE
In release mode crashed widgets should not show stacktrace and red background

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#10695]
Users do not understand what stacktraces mean and red color is too scary for them. It would be great to replace this (only in release mode) with a "broken widget" (may be something like aw, snap! page on Chrome?).

**Comment by Hixie** [comment]
Seems reasonable.

**Comment by gspencergoog** [comment]
It would probably be even more acceptable if users could perform an action, like submit feedback, from the "broken widget" screen.

**Comment by mehmetf** [comment]
@gspencergoog that might not be possible. The broken widget might manifest as a very small area on screen or not be visible at all. 

I think the best way is for the app to install an error handler and do something from there. File feedback, show dialog, etc.

**Comment by tvolkert** [comment]
See also: https://github.com/flutter/flutter/issues/11206

**Comment by emesx** [comment]
Having control over what happens is necessary - I'd like my app to simply close (or do whatever native apps do).

**Comment by tvolkert** [comment]
@emesx that's #11206

**Comment by eseidelGoogle** [comment]
customer: six is reporting that even though they are handling errors in FlutterError and crashing they still see a red screen of death for a second before crashing.  They would like to be able to display something other than the red screen of death during that time.

**Comment by eseidelGoogle** [comment]
Customer six believes this could block their app, so marking as customer critical.

**Comment by Hixie** [comment]
What would they like to show instead?

**Comment by harveynick** [comment]
I think whatever the widget was showing before, possibly with a scrim overlaid would be ideal.

**Comment by Hixie** [comment]
The widget that was showing before is gone, it crashed.

**Comment by harveynick** [comment]
Yes, but we would like for the frame it was displaying before it crashed to remain visible.

**Comment by Hixie** [comment]
Ah, you can probably do that today. Just unhook onDrawFrame when the FlutterError.onError callback is invoked, then replace the FlutterError.onError callback with one that just rethrows, and then rethrow the exception. That should cause the framework to abort and never update the frame this time, and should prevent it from ever trying to update the frame in the future.

**Comment by mehmetf** [comment]
It might be useful to understand Customer six's entire approach. Do you expect users to be forwarded to feedback page? or do you simply want to retain the existing rendered view with a warning of some sort and let the user decide if they want to file feedback?

FWIW, this is not what Leafy wants to do. For us, if a widget crashes, it typically does so when loading new data so we would rather show consistent view (crashed widget with rest of the page showing current data) than inconsistent view (crashed widget with old data mixed with loaded widgets with new data).

**Comment by emesx** [comment]
@Hixie

Right now I have something like this:

```
void handle(FlutterErrorDetails error) {
  ui.window.onDrawFrame = null;
  // .. take screenshot and report 
}
```

And, unfortunately, this doesn't help. The red widget is still rendered. The method is assigned to FlutterError.onError

**Comment by Hixie** [comment]
@emesx Yes you also need the rethrowing thing I mentioned in my earlier comment (otherwise the exception is caught and the framework still gets around to rendering the frame in which the error occurred).

**Comment by emesx** [comment]
@Hixie

Thanks! Where exactly should I rethrown the exception if I run some async code in the error handler? Chained to the end of the last future? Or immediately?

**Comment by Hixie** [comment]
What matters is that FlutterError.onError must not return cleanly. (There's nothing asynchronous in the drawing of the frame, anything you kick off that is asynchronous will happen after the frame has reached the GPU.) So, you must throw synchronously before the method returns.

**Comment by Hixie** [comment]
@mehmetf Is the workaround above sufficient for customer:six? (We want to make the widget prettier but that doesn't seem as high a priority unless that is in fact what you would prefer.)

**Comment by mehmetf** [comment]
@emesx would be the best person to answer that. If it works as you say, then it should be enough.

For Leafy, as I mentioned, this is not enough. The best way would be to allow apps to override the crash widget.

**Comment by Hixie** [comment]
@mehmetf so to clarify, for leafy they do want the app to continue working as best it can, just with a less scary rendering than the red box?

**Comment by Hixie** [comment]
(Overriding the crash widget is something we can investigate but it's non-trivial because at the time where we need the widget the system can be in a _really_ bad state.)

**Comment by mehmetf** [comment]
@Hixie Yes.

Just allowing apps to change the background color and the textual content would be enough if a crash widget override is tricky.

**Comment by Hixie** [comment]
Ok, we will look into this.

**Comment by Hixie** [comment]
Current plan is for me to work on this after RTL, which will be in a few weeks.

**Comment by Hixie** [comment]
I'm looking at this now.

**Comment by Hixie** [comment]
-> https://github.com/flutter/flutter/issues/16774

**Comment by specneeo** [comment]
I see all answers above,  in order to catch exceptions、errors must need `try...catch...`?
How to catch unknown dart exception? for example:
```
new Image.asert("images/back.png")
```
actually, image `back.png` does not exist, it will throw exception like:
```
 ══╡ EXCEPTION CAUGHT BY SERVICES ╞══════════════════════════════════════════════════════════════════
The following assertion was thrown resolving an image codec:
    Unable to load asset: lib/images/backs.png
When the exception was thrown, this was the stack:
#0      PlatformAssetBundle.load (package:flutter/src/services/asset_bundle.dart:221:7)
    <asynchronous suspension>
#1      AssetBundleImageProvider._loadAsync (package:flutter/src/painting/image_provider.dart:427:44)
    <asynchronous suspension>
    #2      AssetBundleImageProvider.load (package:flutter/src/painting/image_provider.dart:412:14)
    #3      ImageProvider.resolve.<anonymous closure>.<anonymous closure> (package:flutter/src/painting/image_provider.dart:266:86)
    #4      ImageCache.putIfAbsent (package:flutter/src/painting/image_cache.dart:143:20)
    #5      ImageProvider.resolve.<anonymous closure> (package:flutter/src/painting/image_provider.dart:266:63)
    (elided 8 frames from package dart:async)
Image provider: AssetImage(bundle: null, name: "lib/images/backs.png")
    Image key: AssetBundleImageKey(bundle: PlatformAssetBundle#2707c(), name: "lib/images/backs.png",
    scale: 1.0)
════════════════════════════════════════════════════════════════════════════════════════════════════
```
How to catch these unknown error in run time?
