### ISSUE TITLE
Triage SkiaPerf flags on raster cache refactoring change

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#106987]
At https://flutter-flutter-perf.skia.org/t/, I have left untriaged the benchmark changes that SkiaPerf has flagged on the engine roll https://github.com/flutter/flutter/pull/106848, which contains only https://github.com/flutter/engine/pull/31892.

It looks like cache usage has generally gone up, some raster times have gone up, and some raster times have gone down. Unfortunately, I don't have enough context to know whether these trade-offs are expected or reasonable.

Since we are going to cut a beta branch soon, I'm filing this issue to prioritize triaging these flags after the holiday weekend.

@flar @JsouLiang

**Comment by JsouLiang** [comment]
@zanderso how to see the cases detail , I want to know which ones are grown up. cause I added a benchmark case show the cache usage is grow down https://github.com/flutter/flutter/pull/103338

**Comment by zanderso** [comment]
Click on https://flutter-flutter-perf.skia.org/t/. Then click on the question marks in the SkiaPerf UI. Then click on the button that says "View on dashboard".

<img width="1490" alt="Screen Shot 2022-07-02 at 7 13 37 AM" src="https://user-images.githubusercontent.com/6343103/177004426-f68dbf47-dab3-4c13-9897-d4759421e7ad.png">

**Comment by JsouLiang** [comment]
This is I revert #31892 change and run the `backdrop_filter_perf__timeline_summary` benchmark.
`-t backdrop_filter_perf__timeline_summary --ab 4`
```
═════════════════════════╡ ••• Final A/B results ••• ╞══════════════════════════

Score	Average A (noise)	Average B (noise)	Speed-up
average_frame_build_time_millis	0.58 (0.63%)	0.52 (2.71%)	1.11x	
worst_frame_build_time_millis	2.23 (66.22%)	2.70 (71.16%)	0.83x	
90th_percentile_frame_build_time_millis	0.69 (3.98%)	0.76 (3.96%)	0.90x	
99th_percentile_frame_build_time_millis	0.93 (14.39%)	1.25 (14.78%)	0.74x	
average_frame_rasterizer_time_millis	4.94 (4.22%)	7.52 (3.27%)	0.66x	
worst_frame_rasterizer_time_millis	8.69 (11.04%)	204.98 (1.06%)	0.04x	
90th_percentile_frame_rasterizer_time_millis	5.63 (0.55%)	7.22 (2.24%)	0.78x	
99th_percentile_frame_rasterizer_time_millis	6.99 (4.68%)	8.99 (1.98%)	0.78x	
average_layer_cache_count	0.00 (0.00%)	0.00 (0.00%)	NaNx	
90th_percentile_layer_cache_count	0.00 (0.00%)	0.00 (0.00%)	NaNx	
99th_percentile_layer_cache_count	0.00 (0.00%)	0.00 (0.00%)	NaNx	
worst_layer_cache_count	0.00 (0.00%)	0.00 (0.00%)	NaNx	
average_layer_cache_memory	0.00 (0.00%)	0.00 (0.00%)	NaNx	
90th_percentile_layer_cache_memory	0.00 (0.00%)	0.00 (0.00%)	NaNx	
99th_percentile_layer_cache_memory	0.00 (0.00%)	0.00 (0.00%)	NaNx	
worst_layer_cache_memory	0.00 (0.00%)	0.00 (0.00%)	NaNx	
average_picture_cache_count	2.00 (0.00%)	1.99 (0.05%)	1.00x	
90th_percentile_picture_cache_count	2.00 (0.00%)	2.00 (0.00%)	1.00x	
99th_percentile_picture_cache_count	2.00 (0.00%)	2.00 (0.00%)	1.00x	
worst_picture_cache_count	2.00 (0.00%)	2.00 (0.00%)	1.00x	
average_picture_cache_memory	10.24 (0.00%)	10.21 (0.05%)	1.00x	
90th_percentile_picture_cache_memory	10.24 (0.00%)	10.24 (0.00%)	1.00x	
99th_percentile_picture_cache_memory	10.24 (0.00%)	10.24 (0.00%)	1.00x	
worst_picture_cache_memory	10.24 (0.00%)	10.24 (0.00%)	1.00x	
new_gen_gc_count	6.00 (0.00%)	4.50 (19.25%)	1.33x	
old_gen_gc_count	0.00 (0.00%)	0.00 (0.00%)	NaNx	
average_vsync_transitions_missed	0.25 (173.21%)	12.75 (10.93%)	0.02x	
90th_percentile_vsync_transitions_missed	0.25 (173.21%)	19.75 (2.19%)	0.01x	
99th_percentile_vsync_transitions_missed	0.25 (173.21%)	20.50 (2.44%)	0.01x	
30hz_frame_percentage	0.00 (0.00%)	0.00 (0.00%)	NaNx	
60hz_frame_percentage	0.00 (0.00%)	0.78 (83.72%)	0.00x	
80hz_frame_percentage	0.00 (0.00%)	0.00 (0.00%)	NaNx	
90hz_frame_percentage	100.00 (0.00%)	99.22 (0.65%)	1.01x	
120hz_frame_percentage	0.00 (0.00%)	0.00 (0.00%)	NaNx	
illegal_refresh_rate_frame_count	0.00 (0.00%)	0.00 (0.00%)	NaNx	
```
You can see the `90th_percentile_picture_cache_memory` and `99th_percentile_picture_cache_memory` are `1.0x`
and if I revert my change the 99th_percentile_frame_rasterizer_time_millis is gone down.

**Comment by JsouLiang** [comment]
https://github.com/flutter/engine/pull/34455
Try to fix this problem . cc @zanderso @flar

**Comment by chinmaygarde** [comment]
The fix landed by @flar this morning and we are waiting on results from Skia perf to come it to check again.

**Comment by zanderso** [comment]
I verified on SkiaPerf that the regressions have recovered, and that the improvements have stuck (or gotten even better) following https://github.com/flutter/engine/pull/34562.
