### ISSUE TITLE
Crash with an Input widget that has an initial value

### ISSUE THREAD

**Issue by mishadynin** [flutter/flutter#1069]
It's triggered in the Create app when an Input widget is instantiated with an initial value and an attempt is made to edit it.

The log file is attached.

May be related to https://github.com/flutter/flutter/issues/964

[alog.txt](https://github.com/flutter/flutter/files/77719/alog.txt)

**Comment by mishadynin** [comment]
Looking into a simple way to reproduce...

**Comment by mishadynin** [comment]
Reproducible in card_collection.dart when you enable 'Make card labels editable' and try to edit a card label.

**Comment by Hixie** [comment]
Cool, thanks. I'll look into it.

**Comment by mishadynin** [comment]
Fixed when engine was upgraded.  Closing.
