### ISSUE TITLE
Web : Special characters (ex: Chinese) not rendering on latest master using flutter run -d chrome，referring to #73628

### ISSUE THREAD

**Issue by lyf571321556** [flutter/flutter#106949]
![image](https://user-images.githubusercontent.com/2295872/176887361-257057da-8420-4683-9c1f-fd61e65942a4.png)

**Comment by danagbemava-nc** [comment]
Hi @lyf571321556, I tried some of the code samples in https://github.com/flutter/flutter/issues/73628 but I was not able to reproduce the issue. 

Please provide a complete minimal reproducible code sample as well as the output of `flutter doctor -v` so that we can investigate this. 

Thank you
