### ISSUE TITLE
Regression in traverseIterableSyncStar_iteration

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#106986]
SkiaPerf has flagged a large regression in the traverseIterableSyncStar_iteration benchmark:

https://flutter-flutter-perf.skia.org/e/?begin=1654721590&end=1656728348&keys=X5511fb24a8d597199a36b42f0e277609&requestType=0&xbaroffset=29630

The regression is on the Dart roll here https://github.com/flutter/engine/pull/34362

That contains https://dart.googlesource.com/sdk.git/+/77ea9820aaa440be32313c257b2e08f41aaf13d8

@alexmarkov @a-siva

**Comment by chinmaygarde** [comment]
@alexmarkov is taking a look at this but this failure in a microbenchmark is expected to be working as intended.

**Comment by alexmarkov** [comment]
https://dart-review.googlesource.com/c/sdk/+/250420 improved other Dart sync* micro-benchmarks, but unfortunately had a very little effect on the Flutter `traverseIterableSyncStar_iteration` micro-benchmark.

I noticed that `traverseIterableSyncStar_iteration` micro-benchmark has a very small measurement interval: only 3-6 milliseconds. The reported results had a very high variability in the past (jumping up to 1.5x), then became stable for a while and started to vary again after the regression. I suspect the score of this benchmark might be highly affected by GC pauses happening or not happening during the measurement interval.

I can suggest to increase number of iterations in this benchmark to measure an execution for at least a couple of seconds. That would make it less affected by GC pauses and less noisy. Also, measuring performance of calculating a sum of integers from 1 to 100 doesn't look like a representative workload from Flutter.

**Comment by zanderso** [comment]
The benchmark recovered. Closing this as done.
