### ISSUE TITLE
Allow suspending scheduling of engine CI jobs during repo merges with history.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#106907]
The team would like to merge the [buildroot](https://github.com/flutter/buildroot) repository into the [engine](https://github.com/flutter/engine) and archive the former. The rationale for doing so is documented in https://github.com/flutter/flutter/issues/67373. A previous (aborted) attempt at doing so is at https://github.com/flutter/engine/pull/27376 and the mechanism should look extremely similar in any new attempts.

The buildroot repo has 546 commits as of today and we would like to Git history to maintain provenance of all patches.

From previous experiences [merging](https://github.com/flutter/engine/pull/32934) [Impeller](https://github.com/flutter/impeller) into the [engine](https://github.com/flutter/engine), it was found that adding that many patches at once overwhelms CI with manual intervention necessary.

This issue tracks overriding scheduling of jobs for a set period of time so that the merge (with history) may with minimal disruption.

**Comment by keyonghan** [comment]
One way to workaround this is skip saving all commits in the PR from go/flutter-build?repo=engine and skip all builds/tasks against them.

Question to confirm: is it okay to skip these commits from go/flutter-build?repo=engine? /cc @chinmaygarde  This way, TOT commit from the merge PR will also be skipped from running tests, and we may need a follow PR/commit to validate tasks/builds to keep tree status up-to-date. Note: this skips commit history only from go/flutter-build?repo=engine, and the list will be kept in https://github.com/flutter/engine/commits.

If this is okay, please let me know the attempt PR to land the merge and I will add an exception for it when scheduling.

**Comment by chinmaygarde** [comment]
> One way to workaround this is skip saving all commits in the PR from go/flutter-build?repo=engine and skip all builds/tasks against them.

How would I do that? Or is this something you will control?

> is it okay to skip these commits from go/flutter-build?repo=engine

Yes.

> This way, TOT commit from the merge PR will also be skipped from running tests, and we may need a follow PR/commit to validate tasks/builds to keep tree status up-to-date.

Roger. I will prep a doc update or or some such PR to land immediately afterwards.

> this skips commit history only from go/flutter-build?repo=engine, and the list will be kept in https://github.com/flutter/engine/commits.

Right. That's what we want.

**Comment by keyonghan** [comment]
> How would I do that? Or is this something you will control?

Yeah, I will land a change from cocoon side for the exception. Please let me know the PR when it's ready (before land).

**Comment by chinmaygarde** [comment]
> Please let me know the PR when it's ready (before land).

Wilco.

**Comment by keyonghan** [comment]
Moving it out of ticket queue. Just let me know when infra is needed.

**Comment by chinmaygarde** [comment]
This is obsolete. We are no longer going to attempt to merge repos by preserving history. Instead, the plan is to squash all old commits for easier merges.
