### ISSUE TITLE
[autosubmit] Bot assessed for submission before checks completed

### ISSUE THREAD

**Issue by Piinks** [flutter/flutter#106914]
https://github.com/flutter/flutter/pull/106795

Before the checks finished, the bot left a comment saying the PR was not able to be merged due to tree status (https://github.com/flutter/flutter/issues/106916). It was not ready to be considered for merging at all since tests were not completed.

**Comment by keyonghan** [comment]
Seems some race condition here: auto submit bot scan through the status and checks before the status is ready. Then hit https://github.com/flutter/cocoon/blob/main/auto_submit/lib/validations/ci_successful.dart#L97.

@godofredoc @ricardoamador can any of you help take a further look?

F.Y.I this is the same issue @dnfield hit earlier

**Comment by ricardoamador** [comment]
I can take a look.

**Comment by ricardoamador** [comment]
This is indeed a bug in our code. We are indeed incorrectly removing the autosubmit label. I have located the issue and am working on a fix.

**Comment by keyonghan** [comment]
Is this fixed by the https://github.com/flutter/cocoon/pull/1961?

**Comment by ricardoamador** [comment]
Yes sir.

**Comment by ricardoamador** [comment]
Although there does seem to be some misunderstanding between how we have
coded the autosubmit label and what developers expect the behavior to be.
It seems like the consensus is that you should be able to apply the label
and leave it there until all conditions are met and the tree is green even
before you have gotten a review. However it only functions to merge the PR
after all the conditions have been met and a review has been given. I
wonder how well this has been communicated.
