### ISSUE TITLE
plugin/package autopublish script doesn't wait for LUCI results

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#106903]
Our auto-publish GitHub action [waits for all post-submit tests to pass](https://github.com/flutter/plugins/blob/main/.github/workflows/release.yml#L37-L47) before publishing. However, because of https://github.com/flutter/flutter/issues/106902 it doesn't know about LUCI tests, and isn't gating release on them.

Currently that means that we're not waiting for Windows post-submit tests, which is a problem, but a minor one since we still have presubmit coverage, and we rarely change Windows plugins compared to other plugins right now. However, having a solution to this is a hard blocker for moving any other tests to LUCI. Possible solutions I can see:
- Fix https://github.com/flutter/flutter/issues/106902
- Replace lewagon/wait-on-check-action with a new action of our own creation that does the same thing plus also waiting for LUCI results

/cc @keyonghan

**Comment by keyonghan** [comment]
With https://github.com/flutter/flutter/issues/106902 being fixed to populate LUCI status to post-submit commits, could you help check if this bug is fixed correspondingly @stuartmorgan ?

**Comment by stuartmorgan** [comment]
i'm seeing LUCI tests in the "wait on all tests" task, so it looks like this should be fixed.
