### ISSUE TITLE
In_app_purchase: Purchase Stream returns expired purchases with PurchaseStatus.restored on IOS

### ISSUE THREAD

**Issue by isiyemijoe** [flutter/flutter#106930]
Using a sandbox account monthly renewable subscriptions purchases are expected to last for 5 mins and will auto-renew a number of times, except it's canceled. 

However I experienced a strange behavior from the data I get from the purchase stream on iOS,  **The Purchase stream returns expired subscriptions with a PurchaseStatus of Restored even when the subscription is no longer active**

This only happens on iOS android works perfectly 

**Steps to reproduce**
I tested this on an iPhone 11 (iOS 15.5)

I used  **in_app_purchase: ^3.0.4** 

1)  On the test device, sign in with the Sandbox Apple ID 
2)  In the example app on this [link](https://dartlang-pub.appspot.com/packages/in_app_purchase/example), 
3)  Select  Subscribe to make a subscription purchase (in my case, the product was a renewable subscription)
4)  A payment sheet shows up; go ahead and finish the purchase.

5) Head over to your sandbox subscriptions and cancel it, wait for about 5+ minutes for it to expire.

6) Go back and restart the app, you'll notice the purchase stream returns the just expired subscription with the status of Restored, 

This is unlike android which only returns active purchases through the stream.

Expected result
After step 6, I would have expected that no purchase will be returned through the stream as I do not have an active purchase.

Actual result
After step 6, the just expired transaction  is returned within the stream with purchase status of Restored

Furthermore, making multiple purchases and cancelling them will also have the same effect, they will all be returned like a transaction history thing.

And this only occurs in iOS

**Comment by bgoncharuck** [comment]
Same issue

**Comment by danagbemava-nc** [comment]
Hi @isiyemijoe, I followed the steps you outlined, but when I restart the app, the purchase stream is empty. 

Can you upgrade to the latest version of the in_app_purchase package 3.0.6 to see if this issue persists? 

If it does, can you provide some logs or any information that captures the states of the stream at each point? 

Please also provide the output of `flutter doctor -v`.

Thank you

**Comment by isiyemijoe** [comment]
> Hi @isiyemijoe, I followed the steps you outlined, but when I restart the app, the purchase stream is empty.
> 
> Can you upgrade to the latest version of the in_app_purchase package 3.0.6 to see if this issue persists?
> 
> If it does, can you provide some logs or any information that captures the states of the stream at each point?
> 
> Please also provide the output of `flutter doctor -v`.
> 
> Thank you

I've tried the latest version and this is still the case.

to be sure you test correctly,

1) Make a purchase on iOS, 
2) Cancel the purchase 
3) Even after canceling the iOS subscription, you will still get the canceled transaction in the logs, with the transaction status of restored. 

Output of flutter doctor -v

`! Doctor found issues in 1 category.
joseph.isiyemi@JosephIsiyemis-MacBook-Pro ~ % flutter doctor -v
[✓] Flutter (Channel stable, 3.0.4, on macOS 12.3.1 21E258 darwin-arm, locale en-NG)
    • Flutter version 3.0.4 at /Users/joseph.isiyemi/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 85684f9300 (12 days ago), 2022-06-30 13:22:47 -0700
    • Engine revision 6ba2af10bb
    • Dart version 2.17.5
    • DevTools version 2.12.2

Checking Android licenses is taking an unexpectedly long time...[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/joseph.isiyemi/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] VS Code (version 1.68.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.44.0

[✓] Connected device (2 available)
    • iPhone 11 (mobile) • 31C73233-3F82-425B-A5DB-E9C4B708D966 • ios          • com.apple.CoreSimulator.SimRuntime.iOS-15-4 (simulator)
    • macOS (desktop)    • macos                                • darwin-arm64 • macOS 12.3.1 21E258 darwin-arm

[☠] HTTP Host Availability (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at
      https://github.com/flutter/flutter/issues.
    ✗ HandshakeException: Connection terminated during handshake`

**Comment by danagbemava-nc** [comment]
Hi @isiyemijoe, are you using the IAP sample as is, or have you made some modifications? 

On my end, after canceling the subscription for the sandbox account, when I go back to the app, I do not receive any activity in the iap stream. 
Also, when I hot restart the app, I do not receive any events in the stream, unless I perform some sort of action related to purchasing.

**Comment by hpsolver** [comment]
Same issue
