### ISSUE TITLE
Input component should support selection

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#107]
<a href="https://github.com/Hixie"><img src="https://avatars.githubusercontent.com/u/551196?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Hixie](https://github.com/Hixie)**
_Monday Jul 20, 2015 at 20:33 GMT_
_Originally opened as https://github.com/flutter/engine/issues/151_

----

_From @Hixie on April 17, 2015 21:31_

_Copied from original issue: domokit/mojo#101_

**Comment by abarth** [comment]
We can paint selections now.  Still missing:

- [ ] Long-press to create a selection.
- [ ] Selection handles for manipulating the selection.

**Comment by eseidelGoogle** [comment]
@mpcomplete landed this recently, no?

**Comment by mpcomplete** [comment]
Yep.

**Comment by sethladd** [comment]
Did we test on iOS?

**Comment by mpcomplete** [comment]
Yes. It's material-style, so it looks/feels the same on both platforms.

**Comment by sethladd** [comment]
Nice!
