### ISSUE TITLE
"flutter build apk" doesn't implicitly run pub get 

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#10700]
If the first thing you do in a flutter project directory is "flutter build", you get all kinds of weird messages because we don't imply a "pub get" for you like we do for "flutter run".

**Comment by Hixie** [comment]
cc @HansMuller

**Comment by mit-mit** [comment]
Yes, we should fix this!. @Hixie why the gradle label?

**Comment by Hixie** [comment]
Sorry, overzealous labeling there!

**Comment by Hixie** [comment]
Moving out of bucket5 since there is no committed assignee; please don't hesitate to move these to a specific milestone if there is someone who is committed to working on it by that milestone.

**Comment by gspencergoog** [comment]
I think this is fixed already: I tried creating a new flutter project (`flutter create hello`), and running `flutter build apk` from there had no errors.  Similarly, if I delete that project and creat a new project, and even if the first thing I do is edit the `pubspec.yaml`, it produces the following output:
```
(home/gspencer:master) -- hello > vi pubspec.yaml
# add a dependency
(home/gspencer:master) -- hello > flutter build apk
Running "flutter packages get" in hello...                   0.7s
Initializing gradle...                                       0.9s
Resolving dependencies...                                    1.0s
Running 'gradlew assembleRelease'...                        25.4s
Built build/app/outputs/apk/release/app-release.apk (7.3MB).
```
Please reopen with your repro if you disagree.
