### ISSUE TITLE
[go_router_builder] Generate a method that returns the route from the location

### ISSUE THREAD

**Issue by ValentinVignal** [flutter/flutter#107053]
## Use case

Using `go_router_builder` allows to created typed routes: 

```dart
@TypedGoRoute<RouteA>(path: '/a')
class RouteA extends GoRouteData {
  const RouteA();

  Widget build(BuildContext context) => const ScreenA();
}

@TypedGoRoute<RouteB>(path: '/b')
class RouteB extends GoRouteData {
  const RouteB();

  @override
  Widget build(BuildContext context) => const ScreenB();
}
```

But, in the `redirect` parameter of the `GoRouter`, we are limited to the state which only offers `String`s (`state.location`, `state.name`, `state.path`, `state.fullpath`) or `Map`s (`state.params`, `state.queryParams`) or `Object`s (`state.extra`):

```dart
final router = GoRouter(
  redirect: (state) {},
  routes: $appRoutes,
);
```

Doing logic around those types (`String`, `Map`, `Object`) is not safe. 

## Proposal

It would be useful if a method

```dart
GoRouteData? routeDataFromState(GoRouterState state);
```

and/or

```dart
GoRouteData? routeDataFromLocation(String location);
```

were generated.

**Comment by chunhtai** [comment]
Is this the same as https://github.com/flutter/flutter/issues/107993 ?

**Comment by ValentinVignal** [comment]
Oops yes I guess I ran into this issue 2 times and I didn't manage to find back this issue when I created the other one. 
We can close one of the 2 (whichever you want and it is less clearer than the other)

**Comment by chunhtai** [comment]
closed as duplicates
