### ISSUE TITLE
Camera position is not getting new latitude and longitude on camera move

### ISSUE THREAD

**Issue by AliPunjabi** [flutter/flutter#107061]
I am trying to drag the map and get the longlat of center of map. With this I am using an icon which is placed at center for better ux. but when I move camera, it is not getting new longlat abd the value of latlaong remains same as initial value. I want to store my latlong in **strLongitude** and **strLatitude** but they are getting the same value of **_initialCameraPosition**. ss is also attached for better understanding.
here is my google map code:
```
GoogleMap(
                    initialCameraPosition: CameraPosition(
                        target: _initialCameraPosition, zoom: 25),
                    mapType: MapType.normal,
                    onMapCreated: _onMapCreated,
                    myLocationEnabled: true,
                    //  markers: _createMarker(),
                    onCameraMove: (CameraPosition cameraPosition) {
                      strLongitude = cameraPosition.target.longitude
                          .toString(); //gets the center longitude
                      strLatitude = cameraPosition.target.latitude.toString();
                      setState(() {}); //gets the center lattitude
                    },
                  ),
```
this is my on map controller method:

```
void _onMapCreated(GoogleMapController controller) {
    _mapsController = controller;
  }
```

and this is my icon which is place in center of map using stack:
```
Align(
                      alignment: Alignment.center,
                      child: IconButton(
                        iconSize: 30,
                        icon: Icon(
                          Icons.place,
                          color: Colors.red,
                        ),
                        onPressed: () {},
                      )),
```
![simulator_screenshot_F3DAE28E-5222-407F-9FB4-277D3A67AD41](https://user-images.githubusercontent.com/90439428/177135426-03628bc1-8161-4f0c-ac42-615f35e313d7.png)

**Comment by exaby73** [comment]
Hi @..., please provide a [minimal, reproducible example][1] (i.e. a single `main.dart` file) and the output of `flutter doctor -v`.

[1]: https://stackoverflow.com/help/minimal-reproducible-example

**Comment by exaby73** [comment]
No problem @AliPunjabi :)
