### ISSUE TITLE
flutter pwa not work offline

### ISSUE THREAD

**Issue by mzelecom** [flutter/flutter#107088]
Hi
I just create a flutter web project and compile it.flutter version 3.0.4
I upload to my host .
first it doesnt work so i change `<base href="/">` to `<base href="">`
after that i check application and it say page does not work offline.and install app not show.
I test this page [https://gallery.flutter.dev/](url).it work correct.
can anyone help me?example?
thanks

**Comment by maheshmnj** [comment]
Hi @mzelecom, running PWA offline is not fully supported as of today. Please see this issue for more details https://github.com/flutter/flutter/issues/60069.

Closing this issue as a duplicate.
