### ISSUE TITLE
[PROPOSAL] Expose  Autocomplete widget's TextEditingController / OnChanged action

### ISSUE THREAD

**Issue by BananaMasterz** [flutter/flutter#107078]
## Proposal
I would like to have access to `Autocomplete` widget's `TextEditingController` or `OnChanged` action.

## Use case
When only the autocomplete `options` are legal, I want to be able to know if the user selected an option and then manually edited the text, in order to disable/enable a button. The current implementation **only** gives feedback when `onSelected` is triggered.

**Comment by maheshmnj** [comment]
Hi @BananaMasterz, Thanks for filing the issue.

There is a similar issue describing this case https://github.com/flutter/flutter/issues/78181, Please follow up there for further updates, Closing this issue as a duplicate. If you disagree feel free to write in the comments and we will reopen it.

Thank you.
