### ISSUE TITLE
Remove workaround for duplicate analyzer output

### ISSUE THREAD

**Issue by kevmoo** [flutter/flutter#10705]
See https://github.com/flutter/flutter/blob/befe01989610e4e231ca1c9095fcdb7a027ede84/packages/flutter_tools/lib/src/commands/analyze_once.dart#L93

https://github.com/dart-lang/sdk/issues/25697 was fixed at https://github.com/dart-lang/sdk/commit/eae2bf27470ff5c52c52647b27db224feb4f68d5

Now you can replace `issues` with an `int`. Nice!

**Comment by kevmoo** [comment]
CC @danrubel

**Comment by zoechi** [comment]
This was done in #16979
