### ISSUE TITLE
[video_player]Uncaught RangeError: Maximum call stack size exceeded while playing m3u8 video in Flutter Web Release

### ISSUE THREAD

**Issue by ArpanaSwarnkar** [flutter/flutter#107098]
Hi, I am facing one issue with your video player in Flutter web release only.

Here is the link of web https://sample-f55e4.web.app/#/.

Uncaught RangeError: Maximum call stack size exceeded
    at Object.b (hls.js@latest:1:3489)
    at l.trigger (hls.js@latest:1:316427)
    at l.trigger (hls.js@latest:1:316554)
    at l.trigger (hls.js@latest:1:316554)
    at l.trigger (hls.js@latest:1:316554)
    at l.trigger (hls.js@latest:1:316554)
    at l.trigger (hls.js@latest:1:316554)
    at l.trigger (hls.js@latest:1:316554)
    at l.trigger (hls.js@latest:1:316554)
    at l.trigger (hls.js@latest:1:316554)

This RangeError exception comes when i play video after few mins spent on that screen. And after that video stuck at one position.
![image](https://user-images.githubusercontent.com/17845189/177301008-ca6bc9a0-2d92-4041-b80c-715b43466be9.png)

And Same occur when i use chewie with video player. You can navigate on chewie screen by clicking on action item chewie.

![image](https://user-images.githubusercontent.com/17845189/177301616-51618591-2d5a-48bc-ab1f-e44a4dc55c75.png)

So please look into this issue as it is happening randomly. Also these are m3u8 video only.

chewie: ^1.3.4
video_player: ^2.4.5
video_player_web_hls: ^0.1.11+4

flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.10.0, on Microsoft Windows [Version 10.0.19044.1766], locale en-IN)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[!] Visual Studio - develop for Windows (Visual Studio Community 2019 16.10.4)
    X Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop development with C++" workload, and include these
      components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK
[√] Android Studio (version 2020.3)
[√] Connected device (3 available)
[√] HTTP Host Availability

! Doctor found issues in 1 category.

**Comment by exaby73** [comment]
Hi @..., please provide a [minimal, reproducible example][1] and the output of `flutter doctor -v`. Also try to upgrade to the latest stable version of Flutter, `3.0.4` and confirm if it still occurs.

[1]: https://stackoverflow.com/help/minimal-reproducible-example

**Comment by ArpanaSwarnkar** [comment]
already give flutter doctor -v output above.

see the example below but it is happening only with released web which you check on https://sample-f55e4.web.app/#/.

void main() {
  runApp(const MyApp()/*VideoApp()*/);
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Video_Player'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  late VideoPlayerController _controller;

  @override
  void initState() {
    super.initState();
    try {
      _controller = VideoPlayerController.network(
          'https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8'
   )
        ..initialize().then((_) {
          // Ensure the first frame is shown after the video is initialized, even before the play button has been pressed.
          setState(() {});
        });
      //_controller.setVolume(0.0);

    }catch(e)
    {
      print(e);
      print("here in catch");

    }
  }
  
  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
        actions: <Widget>[
          TextButton(
            onPressed: () {
              Navigator.of(context).push(MaterialPageRoute(
                builder: (context) {
                  return ChewieSample();
                },
              ));
            },
            child: const Text(
              'Chewie',
                style: TextStyle(
                  color: Colors.white,
                )
            ),
          ),
        ],
      ),
      body: Center(
        child: _controller.value.isInitialized
            ? AspectRatio(
          aspectRatio: _controller.value.aspectRatio,
          child: VideoPlayer(_controller),
        )
            : Container(),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          setState(() {
            _controller.value.isPlaying
                ? _controller.pause()
                : _controller.play();
          });
        },
        child: Icon(
          _controller.value.isPlaying ? Icons.pause : Icons.play_arrow,
        ),
      ),
    );
  }

  @override
  void dispose() {
    super.dispose();
    _controller.dispose();
  }
}

class VideoWidget extends StatefulWidget {

  @override
  _VideoWidgetState createState() => _VideoWidgetState();
}

class _VideoWidgetState extends State<VideoWidget> {
  late VideoPlayerController _controller;

  late ChewieController chewieController;
  late Future<void> _initializeVideoPlayerFuture;

  @override
  void initState() {
    super.initState();
    loadVideoPlayer();
  }

  @override
  void dispose() {
    // Ensure disposing of the VideoPlayerController to free up resources.
    _controller.dispose();
    chewieController.dispose();

    super.dispose();
  }

  void loadVideoPlayer() {
    try {
      _controller = VideoPlayerController.network(
        'https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8');

      // Initialize the controller and store the Future for later use.
      _initializeVideoPlayerFuture = _controller.initialize();
    }catch(e)
    {
      print(e);
    }
  }

  @override
  Widget build(BuildContext context) {
    return Dialog(
      elevation: 0,
      backgroundColor: Colors.transparent,
      child: contentBox(context),
    );
  }

  contentBox(context){
    return Container(
      child:
      Center(
        child:
        FutureBuilder(
          future: _initializeVideoPlayerFuture,
          builder: (context, snapshot) {
            if (snapshot.connectionState == ConnectionState.done) {
              chewieController = ChewieController(
                videoPlayerController: _controller,
                autoPlay: true,
                autoInitialize: true,
                showControlsOnInitialize: true,
                allowedScreenSleep: false,
                materialProgressColors: ChewieProgressColors(
                  playedColor: Colors.red,
                  handleColor: Colors.blue,
                  backgroundColor: Colors.grey,
                  bufferedColor: Colors.yellowAccent,
                ),
                looping: false,
                allowFullScreen: false,
                allowMuting: true,
                showControls: true,
              );

              // If the VideoPlayerController has finished initialization, use
              // the data it provides to limit the aspect ratio of the video.
              return AspectRatio(
                aspectRatio: _controller.value.aspectRatio,
                // Use the VideoPlayer widget to display the video.
                child: Chewie(
                  controller: chewieController,
                ),
              );
            } else {
              // If the VideoPlayerController is still initializing, show a
              // loading spinner.
              return CircularProgressIndicator();
            }
          },
        ),
      ),
    );
  }
}

class ChewieSample extends StatelessWidget{

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text("Chewie"),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          showDialog(
              barrierDismissible: true,
              context: context,
              builder: (context) {
                return VideoWidget();
              });
        },
        child: Icon(Icons.play_arrow,),
      ),
    );
  }

}

**Comment by exaby73** [comment]
Hello @ArpanaSwarnkar. Doesn't look like [`video_player`](https://pub.dev/packages/video_player_web) supports `m3u8` video format. You would need to convert it to a supported format to play it. Closing this issue as this is not a but. If you disagree, please comment and I can reopen it.

**Comment by ArpanaSwarnkar** [comment]
video_player definitely supports m3u8 video format same with chewie.

**Comment by exaby73** [comment]
`video_player` might, but `video_player_web` might not. See the README file on pub.dev for [`video_player_web`](https://pub.dev/packages/video_player_web) which explains supported formats
