### ISSUE TITLE
Provide a --machine flag for `flutter analyze`

### ISSUE THREAD

**Issue by kevmoo** [flutter/flutter#10704]
Just like `--version --machine` we need to process the output of `flutter analyzer` in a mache-friendly way.

Thankfully, we already do this with the regular dart analyzer with the `--format machine` flag. https://github.com/dart-lang/pana/blob/2e30307bd6babc07a8b133b3dd927d7f65ebc3e9/lib/src/sdk_env.dart#L44

We just need `flutter analyzer` to

* Add a `--machine` flag
* Pass it on as `--format machine` to `dartanalyzer`
* Either don't print other output, or make it trivial to exclude from reliably by a line-by-line parser. (Put in a big `*FLUTTER*:` prefix, encode the values in single-line JSON, open for discussion)

This is blocking https://github.com/dart-lang/pana/issues/32
Which is blocking https://github.com/dart-lang/pub-dartlang-dart/issues/170

**Comment by kevmoo** [comment]
CC @mit-mit

**Comment by mit-mit** [comment]
@danrubel is this something you can help with? We need this to get proper analysis of flutter packages & plugins on pub, which is needed to properly calculate package health.

**Comment by kevmoo** [comment]
QQ after looking at the source, it seems this not anything special beyond
setting the packet directory. Right?

No special lint or anything. Am I missing something?

From mobile. Sorry for brevity and/or spelling.

**Comment by danrubel** [comment]
I'm updating `flutter analyze` to use the analysis server in the same way and using the same code as `flutter analyze --watch`. While I'm there I need to make sure that all the current `flutter analyze` options are supported. I can add this to the list.

**Comment by kevmoo** [comment]
> QQ after looking at the source, it seems this not anything special beyond
> setting the packet directory. Right?
> No special lint or anything. Am I missing something?

@mit-mit @danrubel – thoughts here?

**Comment by danrubel** [comment]
Not sure I understand your QQ, but ....
`flutter analyze` will be using analysis server rather than `dartanalyzer` to perform analysis, so unfortunately supporting a machine format will not be as easy as just adding a flutter analyze flag and forwarding that to the analysis engine.

**Comment by kevmoo** [comment]
> Not sure I understand your QQ, but ....

Does (or will) `flutter analyze` do anything "special" beyond just running `dartanalyzer`? Special lints/flags/options/etc?

> will be using analysis server...

That will make things more difficult.

I'm guessing it will dump a nice, complete list of errors/warnings/hints/lints to stdout, right?

Could we have an option to format them exactly like `dartanalyzer --machine` ?

**Comment by danrubel** [comment]
> I'm guessing it will dump a nice, complete list of errors/warnings/hints/lints to stdout, right?

Correct.

> Could we have an option to format them exactly like dartanalyzer --machine ?

Definitely. That's the goal.

**Comment by kevmoo** [comment]
@danrubel what about

> Does (or will) flutter analyze do anything "special" beyond just running dartanalyzer? Special lints/flags/options/etc?

**Comment by danrubel** [comment]
It won't be running `dartanalyzer`. It will be running analysis server instead. Whatever lints/analysis/options are provided by analysis server will be available in `flutter analyze` as well.

**Comment by Hixie** [comment]
https://github.com/dart-lang/pana/issues/32 was closed as not needed, so since this was filed because of that bug, I will close this one also. Please reopen the bug if it's still needed after all.
