### ISSUE TITLE
Cannot display chinese characters (tofu) with canvas-kit renderer on mobile web browser

### ISSUE THREAD

**Issue by dokinkon** [flutter/flutter#107021]
Launch gallery web app or our in-house dev app with local web-server `flutter run -d web-server --web-renderer canvaskit --web-hostname 0.0.0.0 --web-port 8080`

Then I use Chrome app on iPhone SE to open web app and found chinese characters are all tofu.
![IMG_955A1BB9C18B-1](https://user-images.githubusercontent.com/524313/177022898-a131685d-870c-40b5-a5fa-32f2d4763728.jpeg)

Is it possible to solve this issue with canvas-kit web-renderer? Our dev team found there are so many issues with html-renderer, and it cannot be a production-level.

Thank you.

**Comment by maheshmnj** [comment]
Hi @dokinkon, Thanks for filing the issue. What version of flutter are you using? Please share the output of `flutter doctor -v` . Is this issue only on safari or other browsers too?

>Then I use Chrome app on iPhone SE to open web app and found chinese characters are all tofu.

  Could you also give examples of tofu characters?
