### ISSUE TITLE
Page https://flutter.io/debugging/ implies no Observatory for ios devices.

### ISSUE THREAD

**Issue by RandalSchwartz** [flutter/flutter#10708]
## Steps to Reproduce

Go to [the debugging page](https://flutter.io/debugging/), and read the paragraph under Observatory that mentions only Android, without mentioning iOS.  I understand that it works only in the ios simulator, but that's still more than nothing. :)

**Comment by sethladd** [comment]
thanks for the feedback!

**Comment by mit-mit** [comment]
Fixed in https://github.com/flutter/website/pull/602
