### ISSUE TITLE
[tool]Disable update check via environment variable

### ISSUE THREAD

**Issue by TheOneWithTheBraid** [flutter/flutter#107046]
## Use case

As discussed in #59533 (locked), there are some few use cases in which auto update should be switched off. Aside of by the `--no-version-check`, this should also be possible by environment variable.

## Proposal

I'd like to propose to make Flutter listening on certain environment variables, e.g. `FLUTTER_VERSION_CHECK` set to `false` in order to archive the behavior as `--no-version-check`.

As a future prospect, this might be extended to other flags of the Flutter tool, such as `--color` (`FLUTTER_COLOR`), `--machine` (`FLUTTER_MACHINE`), `--suppress-analytics` (`FLUTTER_ANALYTICS`) etc.

**Comment by maheshmnj** [comment]
Hi @TheOneWithTheBraid, Thanks for filing the issue. I was just wondering How is the environment variable better than the existing flag `--no-version-check`?

**Comment by TheOneWithTheBraid** [comment]
An environment variable could be created by a system-wide configuration, e.g. in `/etc/profile.d/`.

**Comment by maheshmnj** [comment]
Thanks for the info leaving this issue open for the team to decide.

**Comment by maheshmnj** [comment]
cc: @christopherfujino

**Comment by TheOneWithTheBraid** [comment]
> whats the benefit of this proposal over `--no-version-check`?

The advantage is that an environment variable can be *once* enrolled system-wide for *every* user, e.g. by a package manager.

A flag to the tool must be passed *every* single time *any* user uses the Flutter tool.

---

It's somehow related to #105087, both issues of packaging Flutter via a package manager.

**Comment by christopherfujino** [comment]
This sounds reasonable to me, as long as we implement it at the same place we check `--no-version-check`

**Comment by andrewkolos** [comment]
Closing this issue since it has gone stale and has a working alternative in the form of `--no-version-check`. Feel free to open a new request issue this feature if it is still desired.
