### ISSUE TITLE
Failed to generate GN files with target windows x86

### ISSUE THREAD

**Issue by Ronbb** [flutter/flutter#107085]
I tried to build engine by https://github.com/flutter/engine/pull/30417 but got an error: 

```
D:\Project\tools\engine\src>python .\flutter\tools\gn --no-goma --no-prebuilt-dart-sdk --windows  --windows-cpu x86
Generating GN files in: out\win_debug_x86
ERROR at //third_party/angle/src/tests/BUILD.gn:5:1: Can't load input file.
import("//build/config/chromecast_build.gni")
^-------------------------------------------
Unable to load:
  D:/Project/tools/engine/src/build/config/chromecast_build.gni
I also checked in the secondary tree for:
  D:/Project/tools/engine/src/build/secondary/build/config/chromecast_build.gni
See //third_party/angle/BUILD.gn:74:7: which caused the file to be included.
      "$angle_root/src/tests:angle_tests",
      ^----------------------------------
```

The error also occurs in https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8810166468039705489/+/u/gn_--runtime-mode_profile_--android_--no-lto/stdout.

Maybe https://github.com/flutter/engine/commit/6301c5cb306e1845ebf3dd446392e2df4573579d causes the problem.

**Comment by stuartmorgan** [comment]
This is not a supported configuration; see https://github.com/flutter/engine/pull/30417#pullrequestreview-908043085 and https://github.com/flutter/flutter/issues/37777#issuecomment-1068402216

You're welcome to send PRs that fix problems, but we don't track x86-specific issues.
