### ISSUE TITLE
Need a way to set the language keyboard layout  for text fields

### ISSUE THREAD

**Issue by holeg** [flutter/flutter#107080]
I am writing a vocabulary app where user can enter their own vocabularies. So I have a dialog with 2 text fields. Eg the first text field is for german and the 2nd text field for english. The keyboard has by default the language of the device. But I want to have the german keyboard layout when the german text field get focus and the english keyboard layout when the english text field get focus. Under iOS it is possible to do it with overriding textInputMode property of the text field. There you can iterate through UITextInputMode.activeInputModes and when the wanted language is within UITextInputMode.activeInputModes you just need to return it.

I want something similar in Flutter too. Would be great If it could be implemented some how. I know there is the property locale in EditableText widget. But this only controls the text output. Would be great if it could also control the keyboard layout (of course if it is available)

**Comment by maheshmnj** [comment]
Hi @holeg, Thanks for filing the issue.  

There is a similar issue describing this case https://github.com/flutter/flutter/issues/99606, Please follow up there for further updates, Closing this issue as a duplicate. If you disagree feel free to write in the comments and we will reopen it.

Thank you.
