### ISSUE TITLE
in_app_purchase codelabs demo test does not populate firestore

### ISSUE THREAD

**Issue by LordWilliamsr** [flutter/flutter#107057]
I am following the in_app_purchase package from flutter and building on android/playstore. When testing the subscription which renews every 5 min, the backend functions log looks fine. However, I do not see the test subscription purchases in the firestore. Since this is happening I cannot implement a hasActiveSubscription to manage the user access. Am I doing something wrong here or this is how the package behaves in test? It would be great to actually have documentation on this part of the package where it matters the most. My assumption here is that, I have to handle where in the app the user has access based on hasActiveSubscription.

**Comment by danagbemava-nc** [comment]
Hi @LordWilliamsr, thanks for reporting this. 

- Are you testing this for iOS/android?
- Do the item updates reflect in the underlying store that you're using? 

Can you also provide the output of `flutter doctor -v` as well as the version of `in_app_purchase` you're using? 

Thank you

**Comment by LordWilliamsr** [comment]
Hi @danagbemava-nc 
Thank you for taking the time.

I am testing for android.
Yes the items in the play store reflect in the app and I can also initiate a buy on the subscription. which updates every 5 min
I can see the purchases reflect in the log in the firebase functions log

in_app_purchase : version - 3.0.6

Flutter doctor -v output
PS C:\Users\User\Documents\Android\Flutter\pasco wassce> flutter doctor -v
[√] Flutter (Channel stable, 3.0.4, on Microsoft Windows [Version 10.0.19044.1766], locale nb-NO)
    • Flutter version 3.0.4 at C:\Users\User\Documents\Flutter\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 85684f9300 (5 days ago), 2022-06-30 13:22:47 -0700
    • Engine revision 6ba2af10bb
    • Dart version 2.17.5
    • DevTools version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\User\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio1\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.1.6)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.1.32421.90
    • Windows 10 SDK version 10.0.22000.0

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] IntelliJ IDEA Community Edition (version 2022.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2022.1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin version 221.5588

[√] VS Code (version 1.68.1)
    • VS Code at C:\Users\User\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.42.0

[√] Connected device (4 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)                  • windows       • windows-x64    • Microsoft Windows [Version 10.0.19044.1766]
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 103.0.5060.66
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 102.0.1245.39
    ! Device emulator-5580 is offline.

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Comment by danagbemava-nc** [comment]
Hi @LordWilliamsr, one more thing, have you completed all the stages of the codelab?

**Comment by LordWilliamsr** [comment]
> Hi @LordWilliamsr, one more thing, have you completed all the stages of the codelab?

Yes I have. I have been going over all the steps over and over again the past days.
I thought it was the firestore rules so I update the firestore rules like so:
rules_version = '2';
service cloud.firestore {
  match /databases/{database}/documents {
    match /{document=**} {
      allow read, write: if request.auth.uid != null;
    }
  }
}

the only part I am struggling with is getting the purchases to populate in firestore and also showing past purchases in the app

**Comment by danagbemava-nc** [comment]
Thanks for the feedback, perhaps that wasn't covered in the codelab. 

Labeling for further insight from the team. 

/cc @domesticmouse

**Comment by LordWilliamsr** [comment]
> Thanks for the feedback, perhaps that wasn't covered in the codelab.
> 
> Labeling for further insight from the team.
> 
> /cc @domesticmouse

That would be great, Thanks for taking the time

**Comment by domesticmouse** [comment]
PTAL @miquelbeltran

**Comment by miquelbeltran** [comment]
I will check that the instructions are correct when I re-write the codelab. In the current implementation, there are firestore rules defined in a file that should be applied, those seem to work for me, but I'll make sure the codelab works as expected.
