### ISSUE TITLE
`flutter doctor --android-licenses` attempts to install java

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#10703]
Was trying to get past https://github.com/flutter/flutter/issues/10702 with `flutter doctor --android-licenses`:

```
%flutter doctor --android-licenses
No Java runtime present, requesting install.
```

Pops up a dialog.  Could it use the Java installed inside Android studio instead?

**Comment by eseidelGoogle** [comment]
If I try to run `~/Library/Android/sdk/tools/bin/sdkmanager` I also get the java install prompt.  I guess I need to install java to accept the licenses for gradle?  FYI @mit-mit

**Comment by Hixie** [comment]
Don't you need java to _run_ gradle?

**Comment by mit-mit** [comment]
One of the key reasons for having `flutter doctor --android-licenses` was for it to be able to auto-locate the JRE. @jason-simmons didn't we get that in?

**Comment by mit-mit** [comment]
@eseidelGoogle does `flutter doctor` defect java?

**Comment by eseidelGoogle** [comment]
I'm attempting to install java now.

**Comment by mit-mit** [comment]
You shoudldn't have to -- not sure why this is failing: https://github.com/flutter/flutter/pull/9892/files

**Comment by eseidelGoogle** [comment]
I installed Java just now and `flutter doctor --accept-licenses` worked.

**Comment by mit-mit** [comment]
Did doctor detect java prior to that?

**Comment by mit-mit** [comment]
Hmm, not working on my personal mac either:

```
Running flutter doctor...
[✓] Flutter (on Mac OS X 10.12.5 16F73, locale en-DK, channel master)
    • Flutter at /Users/mit/github/flutter
    • Framework revision c55097da7d (11 days ago), 2017-06-13 10:51:17 -0700
    • Engine revision 4f5d6fab11
    • Tools Dart version 1.24.0-dev.3.0

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at /Users/mit/Library/Android/sdk
    • Platform android-26, build-tools 25.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.3.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3.2, Build version 8E2002
    • ios-deploy 1.9.1
    • CocoaPods version 1.2.1

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Gradle version 3.2
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[-] IntelliJ IDEA Community Edition (version 2017.1.3)
    ✗ Flutter plugin version 13.1 - the recommended minimum version is 14.0.0
    • Dart plugin version 171.4424.63
    • For information about managing plugins, see
      https://www.jetbrains.com/help/idea/managing-plugins.html

[✓] Connected devices
    • Android SDK built for x86 • emulator-5554                        • android-x86 • Android 7.1.1 (API 25) (emulator)
    • iPhone SE                 • 11BAA4F0-3169-4DCE-A48A-A5E329C8238A • ios         • iOS 10.3 (simulator)

Michaels-MacBook:app mit$ flutter doctor --android-licenses
No Java runtime present, requesting install.
Michaels-MacBook:app mit$
```

**Comment by jason-simmons** [comment]
flutter_tools adds the detected Java directory to the end of the PATH variable when running the Android sdkmanager tool.  So Mac OS' Java placeholder will be ahead of it in the path, and that generates the "No Java runtime present, requesting install".

I can change it to put the Java installation at the front of the PATH.

**Comment by mit-mit** [comment]
Yes, putting the detected Java in the beginning of path when we call out to sdkmanager sounds good!

**Comment by mit-mit** [comment]
Thanks @jason-simmons !
