### ISSUE TITLE
 SingleChildScrollView makes flutter web on mobile browsers laggy,  instead use Listview

### ISSUE THREAD

**Issue by stvhrs** [flutter/flutter#107011]
iv just discovered that SingleChildScrollView(child: Colum[] ) makes flutter web on mobile browsers laggy, instead use Listview(children:[Column([])), and also
don't depend too much on packages try to make your own.
try on a mobile browser
Before: https://stvhrs.github.io/laggyPortfolio/#/
After(Smoother): https://stvhrs.github.io/#/

**Comment by darshankawar** [comment]
This looks similar to https://github.com/flutter/flutter/issues/56257, so please follow-up in it for further updates.
Closing this as a duplicate.
