### ISSUE TITLE
didChangeAppLifecycleState always called even not visible/active

### ISSUE THREAD

**Issue by josefwilfinger** [flutter/flutter#107074]
Hi guys, 

i have the problem that for a widget which is not visible (not active StatelessWidget) the function
didChangeAppLifecycleState is always called. This is a performance issue. 
In this case because it is a Camera widget, the camera gets always active if the app resumes.
This widget is not mine, i can not change the code it is a package from flutter.dev.
A possibility to disable this call would be great.

greets and thx for your work

**Comment by maheshmnj** [comment]
Hi @josefwilfinger, Thanks for filing the issue. Please share a [minimal and complete reproducible code](https://stackoverflow.com/help/minimal-reproducible-example) along with the output of `flutter doctor -v` with expected vs actual results.
