### ISSUE TITLE
How can I transparent gesture navigation in Android

### ISSUE THREAD

**Issue by liasica** [flutter/flutter#107020]
Please help me, I need transparent gesture navigation bar background.
![691656816699_ pic](https://user-images.githubusercontent.com/671431/177022572-ca57846d-43c6-45ca-bbb2-c7ac9e4d0804.jpg)

**Comment by Hari-07** [comment]
https://stackoverflow.com/a/69721972/6787582

**Comment by jakeump** [comment]
Put this above MaterialApp

```
    SystemChrome.setSystemUIOverlayStyle(const SystemUiOverlayStyle(
      statusBarColor: Colors.transparent,
      systemNavigationBarColor: Colors.transparent,
    ));
```

**Comment by liasica** [comment]
@jakeump @Hari-07 

Thanks, I have tried this options, but when I swipe screen from bottom, the black gesture navigation line appeared again.

Phone is XiaoMi 11 Ultra

**Comment by jakeump** [comment]
> @jakeump @Hari-07 
> 
> Thanks, I have tried this options, but when I swipe screen from bottom, the black gesture navigation line appeared again.
> 
> Phone is XiaoMi 11 Ultra

The Xiaomi is the issue. It runs a different version of Android, so that code won't work. I don't have experience with Xiaomi, so I cannot help further.

**Comment by liasica** [comment]
> > @jakeump @Hari-07
> > Thanks, I have tried this options, but when I swipe screen from bottom, the black gesture navigation line appeared again.
> > Phone is XiaoMi 11 Ultra
> 
> The Xiaomi is the issue. It runs a different version of Android, so that code won't work. I don't have experience with Xiaomi, so I cannot help further.

I got it, thanks for help.

**Comment by darshankawar** [comment]
Please ask support questions on stackoverflow. Closing from here.
