### ISSUE TITLE
go_router unknown route name, seems to be case sensitive

### ISSUE THREAD

**Issue by AgiMaulana** [flutter/flutter#107142]
Despite the declared route is registered internally in lowercase, the named route should be case insensitive as mentioned here https://github.com/csells/go_router/issues/132#issuecomment-962065418 and[ in the docs](https://gorouter.dev/named-routes)

> The namedLocation method will look up the route by name in a <b>case-insensitive</b> way, construct the URI for you and fill in the params as appropriate.

![image](https://user-images.githubusercontent.com/88304902/177527760-ab42c7af-aa49-4f42-a635-44aea3c5e590.png)

## Steps to Reproduce

1. Declare a named route with enum such as `AppRoute.myHome.name`
```
enum AppRoute {
    myHome
}

GoRoute(
    path: 'myHome/:someId',
    name: AppRoute.myHome.name,
    pageBuilder: (context, state) {
        final id = state.params['someId'] ?? '';
        return MaterialPage(
            key: state.pageKey,
            child: MyHomeScreeen(id: id)
        );
    }
)
```
2. Open the desired route with its name using `AppRoute.myHome.name`
```
ElevatedButton(
      child: const Text('Go to My Home'),
      onPressed: () {
        context.goNamed(AppRoute.myHome.name, params: {
          'someId': 'someMyHomeId',
        });
      },
    )
```

**Expected results:** 
Open the desired route/page, which is `MyHomeScreeen` in this case

**Actual results:** 
The current page still remains and does not go to the desired route

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>
  
```
unknown route name: myHome
'package:go_router/src/go_route_information_parser.dart':
Failed assertion: line 97 pos 12: '_nameToPath.containsKey(name)'
```

```
```

```
```

```
```

</details>

**Comment by AgiMaulana** [comment]
Wrong repository, this issue should be opened in the [`flutter/packages`](https://github.com/flutter/packages/pulls?q=is%3Apr+is%3Aopen+go_router) instead.

**Comment by AgiMaulana** [comment]
already there is an active issue https://github.com/flutter/packages/pull/2302

**Comment by chunhtai** [comment]
nvm duplicates of https://github.com/flutter/flutter/issues/106163
