### ISSUE TITLE
Cocoon should test some emulator configurations

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#10718]
We should at a minimum have some testing that would have caught yesterday's regression.

Something which fails with https://github.com/flutter/flutter/commit/1a1bbacf0d16c1780377ea77580ec3b05c387f88 and passes with https://github.com/flutter/flutter/commit/6f77b4a9a76e57c4e6d23e61ba59a0cdd80d22b7.

cc @yjbanov

**Comment by godofredoc** [comment]
Obsolete, cocoon agent is being deprecated.
