### ISSUE TITLE
[go_router] Opening app with universal/app link not working

### ISSUE THREAD

**Issue by traed** [flutter/flutter#107108]
I have an NFC tag with a URL that opens my app when scanned. The URL is registered as an associated domain in xcode and equivalent for android. The link points to https://<my domain>/app/test. I've registered a GoRoute like so:

```
class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    final router = GoRouter(
      redirect: (state) {
        // Some redirect logic in case authentication is needed

        return null;
      },
      routes: [
        GoRoute(
          path: '/',
          builder: (context, state) => const HomeScreen(),
        ),
        GoRoute(
          path: '/app/test',
          builder: (context, state) => const TestScreen(),
        ),
      ],
    );

    return CupertinoApp.router(
        routerDelegate: router.routerDelegate,
        routeInformationParser: router.routeInformationParser,
        routeInformationProvider: router.routeInformationProvider,
      );
  }
}
```

However, when the app opens no navigation is triggered. The redirect function never runs and the app opens on the last opened screen, not TestPage. The docs don't really give any hints as to how this is supposed to work... Am I doing something wrong or is universal links not supported?

I can't provide a working example app since universal/app links require you to put a file on a web server to verify your domain.

**Comment by traed** [comment]
$ flutter doctor -v
[✓] Flutter (Channel stable, 3.0.4, on macOS 12.1 21C52 darwin-x64, locale en-SE)
    • Flutter version 3.0.4 at /usr/local/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 85684f9300 (5 days ago), 2022-06-30 13:22:47 -0700
    • Engine revision 6ba2af10bb
    • Dart version 2.17.5
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/mattias/Library/Android/sdk
    • Platform android-32, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.68.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.42.0

[✓] Connected device (3 available)
    • MiPhone (mobile) • 00008030-001149D00C46802E • ios            • iOS 15.5 19F77
    • macOS (desktop)  • macos                     • darwin-x64     • macOS 12.1 21C52 darwin-x64
    • Chrome (web)     • chrome                    • web-javascript • Google Chrome 103.0.5060.114

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Comment by huycozy** [comment]
Hi @traed
Did you follow this [guideline](https://docs.flutter.dev/development/ui/navigation/deep-linking) that was referenced from [declarative-routing#deep-linking](https://gorouter.dev/declarative-routing#deep-linking)?

It'll be great if you could provide us a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we can verify this issue. It should be a Github repository in this case because there are some dependencies configuration files such as: `AndroidManifest.xml`, `Info.plist`.

Thanks!

**Comment by traed** [comment]
Never mind, had a typo in my Info.plist 🙄
