### ISSUE TITLE
Clean up pubRootDirectory tests

### ISSUE THREAD

**Issue by CoderDake** [flutter/flutter#107186]
The `ext.flutter.inspector.addPubRootDirectories` and `addPubRootDirectories` and `ext.flutter.inspector.addPubRootDirectories extra args regression test` specs will be mostly redundant after https://github.com/flutter/flutter/pull/106567 .
As a clean up those tests can be consolidated into the `createdByLocalProject`, `ext.flutter.inspector createdByLocalProject` and `ext.flutter.inspector createdByLocalProject extra args regression test` tests.

**Comment by goderbauer** [comment]
Looks like this was supposed to be closed with the merging of https://github.com/flutter/flutter/pull/106567.
