### ISSUE TITLE
_uriBaseClosure: FileSystemException: Getting current working directory failed, path = ''

### ISSUE THREAD

**Issue by jsantell** [flutter/flutter#107114]
Not sure if this is a Flutter issue or Dart, but when running in a VM on MacOS (macos and ios simulator builds), but running into issues where the current working directory is not defined, surfacing in various ways. There are handful of other similar reported issues, notably for Big Sur, but don't seem directly related.

* flutter: `2.10.3` and `3.0.4`
* dart: `2.16.1` and `2.17.5`
* MacOS `11.6.5`, occurs on other Big Sur machines.

## Spawning Isolate Failure

When running an app `flutter run` (macos or ios simulator), [spawning an isolate](https://github.com/dart-lang/sdk/blob/85700570f64d56fcaff3c9a6cae8f38c62184e90/sdk/lib/_internal/vm/lib/isolate_patch.dart#L362), [VMLibraryHooks.platformScript](https://github.com/dart-lang/sdk/blob/8bd60f41449d26fc06e14705db47ad7e5f4350d7/sdk/lib/_internal/vm/lib/internal_patch.dart#L99) attempts to [resolve a URI](https://github.com/dart-lang/sdk/blob/8bd60f41449d26fc06e14705db47ad7e5f4350d7/sdk/lib/_internal/vm/bin/platform_patch.dart#L65) when `_nativeScript` [is set](https://github.com/dart-lang/sdk/blob/4c0387461c41cb66d26a43e3104879f7a83922a5/runtime/bin/dartutils.cc#L621) to [isolate_group_data->script_url](https://github.com/dart-lang/sdk/blob/4308eb39cfee07052dc4695b2d7d5f68573c068e/runtime/bin/main.cc#L155).

```
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: FileSystemException: Getting current working directory failed, path = '' (OS Error: No such file or directory, errno = 2)
#0      _uriBaseClosure (dart:io-patch/directory_patch.dart:71:5)
#1      Uri.base (dart:core-patch/uri_patch.dart:21:41)
#2      _Platform._nativeScript=.<anonymous closure> (dart:io-patch/platform_patch.dart:65:20)
#3      VMLibraryHooks.platformScript (dart:_internal-patch/internal_patch.dart:99:40)
#4      Isolate.spawn (dart:isolate-patch/isolate_patch.dart:362:33)
```

Setting `Directory.current = Platform.pathSeparator` before `runApp()` fixes this **only for subsequent runs of hot restarting**. Without this, it always fails. This isn't a CLI app, and `Directory.current` isn't used directly, but the isolate resolves a URI value based on this. This functionality was previously working with Flutter Isolates, and migrating to dart isolates (to support additional platforms, we do not currently use flutter plugins in the isolate thread), so maybe there's some conflict here.

## Uri.base 

Digging into why `Uri.base` is throwing, logging `Uri.base` before app startup works for the first run (`file:///`), but subsequent runs (after hot restarting) has a similar error when accessing `Uri.base` at startup:

```
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: FileSystemException: Getting current working directory failed, path = '' (OS Error: No such file or directory, errno = 2)
#0      _uriBaseClosure (dart:io-patch/directory_patch.dart:71:5)
#1      Uri.base (dart:core-patch/uri_patch.dart:21:41)
#2      main (package:<APP>/main.dart:13:13)
#3      main (file:///<APP>/.dart_tool/fluter_build/generated_main.dart:91:42)
#4      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:128:38)
#5      _rootRun (dart:async/zone.dart:1426:13)
#6      _CustomZone.run (dart:async/zone.dart:1328:19)
#7      _runZoned (dart:async/zone.dart:1861:10)
#8      runZonedGuarded (dart:async/zone.dart:1849:12)
#9      _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:126:5)
#10     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:19)
#11     _RawReceivePortImpl._handleMessage (dart:isolate-p<…>
```

Looks like `Uri.base` isn't set on hot restarting runs. Logging `Directory.current` on startup has a similar error:

```
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: FileSystemException: Getting current working directory failed, path = '' (OS Error: No such file or directory, errno = 2)
#0      _Directory.current (dart:io/directory_impl.dart:42:7)
#1      Directory.current (dart:io/directory.dart:136:25)
#2      main (package:<APP>/main.dart:15:19)
#3      main (file:///<APP>/.dart_tool/flutter_build/generated_main.dart:91:42)
#4      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:128:38)
#5      _rootRun (dart:async/zone.dart:1426:13)
#6      _CustomZone.run (dart:async/zone.dart:1328:19)
#7      _runZoned (dart:async/zone.dart:1861:10)
#8      runZonedGuarded (dart:async/zone.dart:1849:12)
#9      _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:126:5)
#10     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:19)
#11     _RawReceivePortImpl._handleMessage (dart:isolate-pat<…>
```

## Doctor

```
[✓] Flutter (Channel stable, 2.10.3, on macOS 11.6.5 20G527 darwin-x64, locale en-US)
    • Flutter version 2.10.3 at /Users/---/.flutter-sdk-2.10.3
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (4 months ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed
      instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.68.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.42.0

[✓] Connected device (3 available)
    • iPhone 13 (mobile) • 6F0C0E30-476F-4AD7-85EE-148A17941816 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • macOS (desktop)    • macos                                • darwin-x64     • macOS 11.6.5
      20G527 darwin-x64
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome
      103.0.5060.114

[✓] HTTP Host Availability
    • All required HTTP hosts are available
```

## Summary

Why does `Uri.base` (or `Directory.current`) throw on hot restarting runs, and not the first run? Why do isolates require `Directory.current` to be set (and only applied on subsequent hot restarting runs)? There's definitely room for misunderstanding usage, but seems like there's some race condition related to `_uriBaseClosure`.

**Comment by jsantell** [comment]
Related issues:

* Similar issues appear when running antivirus with tests on Big Sur; notably, we aren't running antivirus or running tests: https://github.com/dart-lang/sdk/issues/44509, https://github.com/flutter/flutter/issues/70940
* Similar issue with analysis tools: https://github.com/dart-lang/sdk/issues/39465
* Possibly similar issue as https://github.com/flutter/flutter/issues/66235, though from Flutter 1.20.4
* There's a possible work around with `IOOverrides` stubbing out the current directory, though `Uri.base` [doesn’t use Directory.current overrides](https://github.com/dart-lang/sdk/issues/39796)

I'm interested in investigating further, but this appears to have affected several components over time -- any guidance on `Uri.base` expectations (noted that this can change if CWD changes, how does that affect non CLI apps if at all?) or ideas on the culprit that could cause differences between first and subsequent runs?

**Comment by maheshmnj** [comment]
Hi @jsantell, Thanks for filing the issue. Can you please share the minimal reproducible sample code that fails in your VM?
  Also can you please attach the output of `flutter run -v ` in a text file?

Thanks

**Comment by jsantell** [comment]
Exploring if MacOS 12+ fixes the issue and also trying to break this down into a minimal test case -- will report back when successful, thanks @maheshmnj!
