### ISSUE TITLE
macOS uses unmanaged color profile, should use sRGB instead

### ISSUE THREAD

**Issue by knopp** [flutter/flutter#107103]
It looks like the image's color profile is ignored and colours are assumed to be in the target color space, which appears to be sRGB on iOS and Display P3 on macOS. Similarly, painting done by Flutter also occur in sRGB for iOS and Display P3 for macOS.

These two images of both filled with `RGB(255, 0, 0)`  but on having the sRGB color profile and the other Display P3 (the color in the image on the right should look more intense on monitors supporting Display P3):

| sRGB | Display P3 |
| --- | --- |
| <img alt="sRGB" width=100 src="https://user-images.githubusercontent.com/4456832/164975962-8295ec04-297a-4620-8ca7-5f5c40aed46d.png" /> | <img alt="Display P3" width=100 src="https://user-images.githubusercontent.com/4456832/164975961-b9c74bff-9a0f-44b5-b1da-3007d369ffc9.png" /> |

| iOS | macOS |
| --- | --- |
| <img alt="iOS" width=200 src="https://user-images.githubusercontent.com/4456832/164975950-79a4313c-14d8-41e0-99d0-56d5f4b4a625.jpeg" /> | <img alt="macOS" width=200 src="https://user-images.githubusercontent.com/4456832/164975951-af690d5a-78fa-44f9-987f-c64b8447bfd5.png" /> |

_Originally posted by @spkersten in https://github.com/flutter/flutter/issues/96733#issuecomment-1107830072_

**Comment by knopp** [comment]
> Hey @knopp. On iOS, using a program called ColorSlurp, I get the hex code `FE0100` while on Mac it's `FF0000`. Is that expected?

ColorSlurp seems pretty useless because it doesn't show the color profile. Use the "Digital Colour Meter" app that comes installed with macOS. If you then run a Flutter application with full red in it (1,0,0), the color meter should read the red as 255,0,0 in sRGB and 234,51,35 in P3. Instead it displays it as 255,0,0 **(clipped)** in sRGB and 255,255,0 in P3.

Note that this only works if you have a display that supports P3.

**Comment by exaby73** [comment]
Thanks for the info. Yes, I can see that. I'm not very informed in how colors work with different color profiles so that was very helpful
