### ISSUE TITLE
Android, on-screen keyboard is hidden after minimising and resuming to the app

### ISSUE THREAD

**Issue by maxim-saplin** [flutter/flutter#107153]
# Summary

Unlike other Android apps (Chrome, YouTube) soft keyboard visibility is not preserved when minimising/resuming Flutter Android apps.

https://user-images.githubusercontent.com/7947027/177575348-d203d4aa-653d-4fa1-9788-545f7b8fb666.mov

## Steps to Reproduce

1.  Run any flutter app that has text inputs (tried on my apps, Flutter Gallery, Google Ads) -> attached is a counter app with a TextField which demonstrates the issue
2. Select the input field so that soft keyboard is displayed
3. Minimize app
4. Resume the app
5. See that the keyboard is hidden though the input field is in focus and cursor is blinking

**Expected results:**
Keyboard is not hidden

**Actual results:**
It is hidden

<details>
<summary>Code sample</summary>
[bug.zip](https://github.com/flutter/flutter/files/9055639/bug.zip)
</details>

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel stable, 3.0.4, on macOS 12.4 21F79 darwin-arm, locale en-BY)
    • Flutter version 3.0.4 at /private/var/user/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 85684f9300 (6 days ago), 2022-06-30 13:22:47 -0700
    • Engine revision 6ba2af10bb
    • Dart version 2.17.5
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /private/var/user/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.68.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.44.0
```

</details>

**Comment by huycozy** [comment]
Hi @maxim-saplin, thanks for filing the issue. 
I see there's an open issue addressing the case you described #52599
Closing as a duplication, so please follow up on it for further updates.
