### ISSUE TITLE
[CanvasKit] Load many images (cors)

### ISSUE THREAD

**Issue by Sesa1988** [flutter/flutter#107187]
Hi, there is no real solution for loading many images from another domain if you use canvas-kit.
I would switch to html-renderer but there issues with Path calculations so I can't.

## Steps to Reproduce

1. Create a list (builder) with platform views for images
2. Scroll through the list

**Expected results:** All images are loaded

**Actual results:** Only the first images are loaded

**Comment by exaby73** [comment]
Hi @Sesa1988, please provide a [minimal, reproducible example][1] and the output of `flutter doctor -v` as well as `flutter run -v`.

[1]: https://stackoverflow.com/help/minimal-reproducible-example

**Comment by Sesa1988** [comment]
> Hi @Sesa1988, please provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) and the output of `flutter doctor -v` as well as `flutter run -v`.

Hi, @exaby73 , I will provide an example next week.

**Comment by exaby73** [comment]
Sure thanks :)

**Comment by Sesa1988** [comment]
> Sure thanks :)

Hi @exaby73 

I stripped down my app. Originally I have multiple bottom navigation tabs with each containing multiple lists with images.
In this example I just put multiple lists in one view and its kinda shows one of the issues.

https://github.com/Sesa1988/flutter-web-platform-image-issue

**Comment by maheshmnj** [comment]
Thanks for the [sample project](https://github.com/Sesa1988/flutter-web-platform-image-issue) @Sesa1988, I can reproduce the issue. Some of the images fail to render in canvaskit while it works fine with HTML renderer.


### HTML
https://user-images.githubusercontent.com/31410839/181445149-0a4dc25a-ba82-4ab1-88e7-8a7bf516e23c.mov

### Canvaskit

https://user-images.githubusercontent.com/31410839/181445478-995a6366-2d98-4f1f-b566-3f8f3c287c95.mov



<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.4 21F79 darwin-arm, locale en-IN)
    • Flutter version 3.0.5 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (5 days ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-32, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.67.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.44.0

[✓] Connected device (3 available)
    • sdk gphone arm64 (mobile) • emulator-5554 • android-arm64  • Android 11 (API 30) (emulator)
    • macOS (desktop)           • macos         • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)              • chrome        • web-javascript • Google Chrome 103.0.5060.114

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

```
[✓] Flutter (Channel master, 3.1.0-0.0.pre.1868, on macOS 12.4 21F79 darwin-arm, locale en-IN)
    • Flutter version 3.1.0-0.0.pre.1868 on channel master at /Users/mahesh/Documents/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 925bee92e7 (2 days ago), 2022-07-26 04:49:06 -0400
    • Engine revision 5dcaeae656
    • Dart version 2.19.0 (build 2.19.0-34.0.dev)
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-32, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13C100
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.69.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.44.0

[✓] Connected device (3 available)
    • sdk gphone arm64 (mobile) • emulator-5554 • android-arm64  • Android 11 (API 30) (emulator)
    • macOS (desktop)           • macos         • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)              • chrome        • web-javascript • Google Chrome 103.0.5060.134

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by maheshmnj** [comment]
Could be related to https://github.com/flutter/flutter/issues/106433

cc: @yjbanov

**Comment by yjbanov** [comment]
CanvasKit cannot render cross-domain images without a CORS handshake. This is an intentional limitation of WebGL (unfortunately, WebGPU will continue having this limitation).

A few options available today:

* See if you can get a CORS handshake with the server your app is fetching images from.
* Use platform views. For efficiency you'd want to minimize the number of platform views. Otherwise, Flutter may end up creating a lot of WebGL canvases. If possible, one platform view should display many images.

In Flutter itself, one solution could be to allow choosing a renderer on a per-layer basis. Then the layer containing many CORS images can use the HTML renderer, while the rest of the app can continue using WebGL/WebGPU. I am going to accept this as a feature request, but it's unlikely that we'll be able to fix it soon.

**Comment by slavap** [comment]
In some cases, the possible solution could be using a simple server side proxy to pretend that images are in your domain.

**Comment by yjbanov** [comment]
I have a proposal that fixes this issue using a more general approach: https://github.com/flutter/flutter/issues/145360.
