### ISSUE TITLE
[github-admin] Lock down flutter/engine fuchsia_r49

### ISSUE THREAD

**Issue by akbiggs** [flutter/flutter#107198]
New Fuchsia release branch in flutter/engine that needs to be write-protected.

**Comment by akbiggs** [comment]
Alternatively if there's a way to write-protect all branches matching the regex [`fuchsia_r\d+`](https://github.com/flutter/engine/blob/main/.ci.yaml#L11) that works too. This might already be done, I'm not sure.

**Comment by godofredoc** [comment]
Used `fuchsia_r*` the branch rules only support fnmatch syntax.
