### ISSUE TITLE
[plugins] Obscure failure when using `update-excerpts` while IDE is open

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#107180]
If a plugin is open in VS Code with default settings while running `update-excerpts`, it will often failure with an unhelpful error message like:

```
Cannot rename file to '[...]/example/.dart_tool/pub/bin/build_runner/build_runner.dart-2.18.0-216.0.dev.snapshot', path = '[...]/example/.dart_tool/pub/incremental/build_runner/tmpOZSDBC/build_runner.dart.incremental.dill.incremental.dill' (OS Error: No such file or directory, errno = 2)
```

It seems to be a race with the setting to run `pub get` when the pubspec.yaml changes, which we change on the fly as part of that command. We should see if we can find a way to avoid the race, since having to close the project is kind of annoying. For now I'll document it in the wiki.

**Comment by freshteapot** [comment]
I can confirm this also happens if you have editor open and run a script doing things like

```sh
dart pub get
dart run build_runner build
dart format lib
dart fix --apply lib
```

**Comment by Hixie** [comment]
I suspect this would be fixed by https://github.com/flutter/packages/pull/4417 (but haven't tested).
