### ISSUE TITLE
Please add documentation on how to use MemoryImage

### ISSUE THREAD

**Issue by pcomans** [flutter/flutter#10716]
Hi there,

I'm trying to write a widget that displays an animated GIF.
I am decoding the GIF using https://pub.dartlang.org/packages/image and trying to write the bytes to a MemoryImage.
I find, however, that MemoryImage never redraws, even when setting a new state.
Is there something I'm doing wrong?

```dart
    String url =
        "https://upload.wikimedia.org/wikipedia/commons/2/2c/Rotating_earth_%28large%29.gif";
    var httpClient = createHttpClient();
    var response = await httpClient.readBytes(url);

// DartImage is an alias for package:image/image.dart
    DartImage.Animation decodedGif = DartImage.decodeGifAnimation(response);
    DartImage.Image firstImage = decodedGif.toList().first;

    setState(() {
      print("Should draw image");
      _imageData = firstImage.getBytes();
    });
```

My code is here: https://github.com/pcomans/flutter_gif_test/blob/master/lib/main.dart

Any help is appreciated!

**Comment by eseidelGoogle** [comment]
We could also probably do some engine work to help you with https://github.com/flutter/flutter/issues/204 :)

**Comment by pcomans** [comment]
@eseidelGoogle That would be fantastic!
Whats the best way to reach out? We'd love to share what we are building with Flutter.

**Comment by sethladd** [comment]
@pcomans we'd love to see what you're building :) you can email me at `sethladd@google.com`. thanks!

**Comment by eseidelGoogle** [comment]
@pcomans @sethladd above is the right person to start with. :) Thanks!

**Comment by Hixie** [comment]
To answer the original question, MemoryImage doesn't expect you to change the bytes after it's created. I'll add a paragraph (see https://github.com/flutter/flutter/pull/10815) that talks about how you would generate an ImageStream whose image changes over time.

**Comment by Hixie** [comment]
I added to the documentation (see the PR).
