### ISSUE TITLE
Support Android APK splits to target multiple abi

### ISSUE THREAD

**Issue by kamathln** [flutter/flutter#10728]
Currenlt Flutter only packages the armeabi-v7a library in the release APK and none other. So my suggestion is to use the feature explained at

https://developer.android.com/studio/build/configure-apk-splits.html 

.. so that flutter can generate different apks for different abis (x86, x86_64, etc).

For more details see #10717

**Comment by gedw99** [comment]
+1
I use golang with flutter mobile and flutter desktop.
Getting this working for mobile would make things much easier at least

**Comment by JarvanMo** [comment]
We need this in a hurry because we want to support both *armeabi-v7a* and *arm64-v8a* because our app stores don't support uploading apps by different abis. And we want arm64. I think  flutter should split *.so* by *abiFilters*,not flutter.gradle.

**Comment by kamathln** [comment]
Hello, I have switched jobs, thus not using Flutter anymore. And am no longer pursuing this bug (trying out patches and the like). Whoever needs this fixed please take charge of this , and when developers do respond with patches, commits, etc.. do make sure they are tested.

**Comment by JarvanMo** [comment]
Sounds good @kamathln . I have to abandon *arm64*. I tried to move *libflutter.so* in *android-arm64-release* in to *src/main/jniLibs/arm64-v8a*, it crashed.So I gave up.

**Comment by rostopira** [comment]
For those interested in this feature, I use an workaround to build release apk for different platforms
```groovy
    buildTypes {
        debug {
            minifyEnabled true
            useProguard true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            ndk {
                abiFilters 'arm64-v8a', 'armeabi-v7a'
            }
        }
        release {
            minifyEnabled true
            useProguard true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules-release.pro'
            signingConfig signingConfigs.release
            ndk {
                if (!project.hasProperty('target-platform'))
                    abiFilters 'arm64-v8a', 'armeabi-v7a'
                else {
                    switch (project.property('target-platform')) {
                        case 'android-arm64': abiFilters 'arm64-v8a'; break
                        case 'android-arm': abiFilters 'armeabi-v7a'; break
                        case 'android-x86': abiFilters 'x86'; break
                        case 'android-x64': abiFilters 'x86_64'; break
                        default:
                            throw new GradleException("Unrecognized target-platform: " + project.property('target-platform'))
                    }
                    print(project.property('target-platform'))
                }
            }
        }
    }
```
Sync gradle and build arm64 for example
```bash
flutter build apk --target-platform=android-arm64
```

**Comment by Kiruel** [comment]
@rostopira Can't use `flutter run` anymore with your solution. And crash my application.
```
E/flutter ( 2633): [ERROR:flutter/shell/platform/android/platform_view_android_jni.cc(722)] Could not locate FlutterCallbackInformation class
F/flutter ( 2633): [FATAL:flutter/shell/platform/android/library_loader.cc(24)] Check failed: result.
```

**Comment by rostopira** [comment]
@Kiruel I dunno, I don't have any issues, even on master channel ¯\_(ツ)_/¯

**Comment by blasten** [comment]
this is already implemented as `flutter build apk --split-per-abi`.
