### ISSUE TITLE
flutter create

### ISSUE THREAD

**Issue by MansiPatel15** [flutter/flutter#107294]
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by darshankawar** [comment]
Same as https://github.com/flutter/flutter/issues/107293#issuecomment-1178923455
Please don't spam the repo by creating empty issues or multiple issues for same reason.
