### ISSUE TITLE
Script src assignment for Google Sign in Flutter web plugin should be via trusted type

### ISSUE THREAD

**Issue by rockaustin2k6** [flutter/flutter#107212]
Line of code with the [injection sink](https://developer.mozilla.org/en-US/docs/Web/API/Trusted_Types_API#injection_sinks): [packages/google_sign_in/google_sign_in_web/lib/src/utils.dart](https://github.com/flutter/plugins/blob/main/packages/google_sign_in/google_sign_in_web/lib/src/utils.dart#L33)

When a flutter web app uses the plugin, that line sets HTMLScriptElement.src to the string: 'https://apis.google.com/js/platform.js?o..' . To make it more secure (i.e. avoid DOM XSS risks), we need to make use of [Trusted Type APIs](https://developer.mozilla.org/en-US/docs/Web/API/Trusted_Types_API) rather than simply setting string.

**Comment by stuartmorgan** [comment]
This is tracked by https://github.com/flutter/flutter/issues/103448

**Comment by ditman** [comment]
> We need to make use of Trusted Type APIs...

As of now, Trusted Types are only supported in Chromium browsers. Neither Firefox nor Safari support the Trusted Types API *today* (July 8th, 2022), so we can't *really* use them (without splitting the code in two)

[![Trusted Types for DOM manipulation support chart as of July 8th, 2022, from caniuse.com](https://caniuse.bitsofco.de/static/v1/trusted-types-1657308969287.jpg)](https://caniuse.com/trusted-types)
