### ISSUE TITLE
"invisible characters" added when switch to "Symbol Keyboard" in a TextFormField ( Android 4.4.4 )

### ISSUE THREAD

**Issue by rxlabz** [flutter/flutter#10723]
we have a very strange bug with a textFormField on two samsung devices ( samsung tab 9 SM T 560 => Android 4.4.4, samsung tab 3 SM T 113 => Android 4.4.4)  : when we use an "@" , the resulting string contains 2 spaces around the " @ ". It's not visible, but the login fails, and when we copy / paste in other app, it appears. We did some tests : if we paste the mail in the field : it works, if we type in the field : spaces appears. 
I can't reproduce this bug on my Acer Android 6.0 device.

Here a screenshot showing the text in the field, ( I log the controller.text.length )
![field_space_bug](https://user-images.githubusercontent.com/1397248/27186574-13d8a3e2-51e9-11e7-9398-c03f4a76c472.png)

**Update :**

the bug seems to be caused by the use of the "sym" key to switch to "symbol keyboard",

![sym key](https://user-images.githubusercontent.com/25841448/27187016-55847838-51ea-11e7-9241-76446e18d9ed.png)

there is no invisible char when we use the [2/@] "shortcut" key

![short key](https://user-images.githubusercontent.com/25841448/27186975-438cde22-51ea-11e7-9813-9ca20b133c94.png)

## Flutter Doctor

here the flutter doctor for the computer building the apk
```
[✓] Flutter (on Mac OS X 10.12.5 16F73, locale fr-FR, channel master)
    • Flutter at /Users/rxlabz/dev/tools/flutter
    • Framework revision 36c3a962c5 (8 hours ago), 2017-06-14 23:33:14 -0700
    • Engine revision 18fdfb86bb
    • Tools Dart version 1.24.0-dev.6.7

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at /Users/rxlabz/Library/Android/sdk
    • Platform android-25, build-tools 25.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.3.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3.3, Build version 8E3004b
    • ios-deploy 1.9.1
    • CocoaPods version 1.2.0

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Gradle version 3.2
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Ultimate Edition (version 2017.1.4 EAP)
    • Flutter plugin version 14.0
    • Dart plugin version 171.4694.29

[✓] Connected devices
    • A3 A40   • 622004271815                         • android-arm • Android 6.0 (API 23)
    • iPhone 5 • DFE2B96E-4F8A-4FA2-80B7-06C0F74B270F • ios         • iOS 10.3 (unsupported) (simulator)
```

**Comment by rxlabz** [comment]
I have the confirmation that this problem appears only with my last update of the app, not in the initial release in April (same devices were used).

**Comment by eseidelGoogle** [comment]
@jason-simmons recently re-wrote our Android IME integration, and it's possible this occurred from that?

**Comment by alardizabal** [comment]
```
I've run into this same problem on a Samsung S7. Tapping the Sym key will clear out the previously typed word. The "invisible characters" seem to be the issue as I get a bad text formatting error instead of an empty field error when i run a supposedly blank field through our validation. This is a pretty big issue for our app since we have several sign up/login forms and if you use aliases in Gmail, it's difficult to add a '+'. 
```

**Comment by collinjackson** [comment]
I was able to repro in a Samsung device. Here is some [test code](https://gist.github.com/collinjackson/f004c316cca2f6c6bee70ed491b85f2a) that reproduces the issue.
