### ISSUE TITLE
Dart2js - Compile single function instead of program

### ISSUE THREAD

**Issue by duck-dev-go** [flutter/flutter#107267]
## Use case

I am currently using the following [package](https://pub.dev/packages/isolated_worker). This package takes a javascript file imports the scripts in a webworker. Then it executes a function in that scope.

For the webworker I am compiling my dart code to js with `dart compile js -O0 -o test.js test.dart`

this is my dart file

void main(List<String> args) {
  doComputation('');
}
            
String doComputation(String input) {
  return 'output';
}

But I want to be able to just compile

String doComputation(String input) {
  return 'output';
}

Without the main function. So just compile a javascript function with the dependencies instead of a program. This is because the program should not run automatically but instead a functions needs to be called.

## Proposal

Preferably a flag to the dart compile js command to get the function output in a javascript file.

**Comment by exaby73** [comment]
Hello @duck-dev-go. This issue does not seem to describe a bug or proposal in Flutter. I think this issue would be better suited in https://github.com/dart-lang/sdk. Please raise this proposal there. Closing this issue since it's not related to Flutter itself.
