### ISSUE TITLE
Duplacate class using integration test

### ISSUE THREAD

**Issue by luciano-cervantes** [flutter/flutter#107235]
Hello, I have a doubt. I have a problem in my app, I want to add an android sdk to my app, however, when I add this sdk I'm getting this error: 
>  Execution failed for task ':app:checkDebugDuplicateClasses'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
   > Duplicate class org.xmlpull.v1.XmlPullParser found in modules jetified-kxml2-2.3.0 (net.sf.kxml:kxml2:2.3.0) and jetified-xpp3_min-1.1.4c (xpp3:xpp3_min:1.1.4c)
     Duplicate class org.xmlpull.v1.XmlPullParserException found in modules jetified-kxml2-2.3.0 (net.sf.kxml:kxml2:2.3.0) and jetified-xpp3_min-1.1.4c (xpp3:xpp3_min:1.1.4c)

     Go to the documentation to learn how to <a href="d.android.com/r/tools/classpath-sync-errors">Fix dependency resolution errors</a>.`

When removing Integration test from my Pubspack the error disappears. Does anyone know how to solve this problem?

![image](https://user-images.githubusercontent.com/72446530/177792283-4b380e64-d699-4c61-ae50-2349a65923fe.png)

![image](https://user-images.githubusercontent.com/72446530/177792376-f68c760b-fecb-49c2-b711-2b4035c281cb.png)

**Comment by maheshmnj** [comment]
Hi @luciano-cervantes, Thanks for filing the issue. Looks like your dependencies have duplicate classes Please see this SO answer  https://stackoverflow.com/a/56029604/8253662 on how to fix it.

**Comment by luciano-cervantes** [comment]
I've tried this way and several others didn't work. 
I know this is not a Flutter issue 🤷‍♂️.
