### ISSUE TITLE
flutter create

### ISSUE THREAD

**Issue by MansiPatel15** [flutter/flutter#107295]
[manifest-merger-debug-report.txt](https://github.com/flutter/flutter/files/9071711/manifest-merger-debug-report.txt)
[README.md](https://github.com/flutter/flutter/files/9071767/README.md)
[manifest-merger-debug-report.txt](https://github.com/flutter/flutter/files/9071775/manifest-merger-debug-report.txt)

## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by darshankawar** [comment]
Same as https://github.com/flutter/flutter/issues/107294#issuecomment-1178924589
