### ISSUE TITLE
[MacOS] Font in Text widget partially pixelated

### ISSUE THREAD

**Issue by gkovac42** [flutter/flutter#107218]
I'm using a simple Text widget with the default font, fixed font size. Some parts of the text, or some characters appear pixelated / blurry while others do not. It's weird and hard to explain in words so I'm attaching a screenshot.

Running Flutter 3.0.4 on MacOS 11.6, MacBook Air M1 (2021)

<img width="568" alt="Screenshot 2022-07-07 at 10 05 38" src="https://user-images.githubusercontent.com/23480045/177725322-a6cf452e-6229-4738-b54d-1bf983e9c252.png">

**Comment by huycozy** [comment]
Hi @gkovac42, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this. Also, please provide the output of `flutter doctor -v` as well.
Thank you!

**Comment by gkovac42** [comment]
Found the culprit: it was a Container with a transparent foregroundDecoration color in the builder of the MaterialApp widget. Not sure if it's a Flutter issue or I was just using it wrong, but the blurred text in Text widgets is present only on MacOS, the implementation works fine on all other supported platforms I've tried (iOS, Android, Windows). Here is the code:

```
return MaterialApp(
          builder: (context, widget) {
            return Container(
              foregroundDecoration: BoxDecoration(
                color: Values.theme == 1 
                    ? Colors.grey.withOpacity(0.67)
                    : Colors.transparent,
                backgroundBlendMode: BlendMode.saturation,
              ),
              child: widget
            );
          },
          ...
```

**Comment by huycozy** [comment]
Hi @gkovac42, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this on platforms or find relevant/existed issues.
Thank you!
