### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by MansiPatel15** [flutter/flutter#107296]
[source-classes-mapping.txt](https://github.com/flutter/flutter/files/9071785/source-classes-mapping.txt)

## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by MansiPatel15** [comment]
ok

**Comment by MansiPatel15** [comment]
ok

**Comment by MansiPatel15** [comment]
flutter run

**Comment by MansiPatel15** [comment]
[README.md](https://github.com/flutter/flutter/files/9071828/README.md)

**Comment by MansiPatel15** [comment]
[manifest-merger-debug-report.txt](https://github.com/flutter/flutter/files/9071833/manifest-merger-debug-report.txt)

**Comment by darshankawar** [comment]
Same as https://github.com/flutter/flutter/issues/107294#issuecomment-1178924589
