### ISSUE TITLE
docs.flutter.io doesn't easily link back to flutter.io

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#10726]
Oddly enough, the upper-left "Flutter" word isn't linked to flutter.io. This makes docs.flutter.io a bit of an island.

**Comment by zoechi** [comment]
This seems to be fixed.

![image](https://user-images.githubusercontent.com/405837/49340976-3e1d0400-f647-11e8-9f95-53417f04c473.png)

(see status bar when mouse hovers over "Flutter SDK"
