### ISSUE TITLE
[Android] Deferred Components with video mp4 files not work properly

### ISSUE THREAD

**Issue by enricoi** [flutter/flutter#107222]
I am using the deferred components in one of my application. The configuration and settings for making up the deferred components went successfully. I followed the [Flutter Documentation](https://docs.flutter.dev/perf/deferred-components) to implement it.

When I build app-release bundle, upload it on play store for internal test and install it into my device for testing purpose the deferred component loads successfully as the doc provided for images and mp3 but not for video(mp4).  Images and sounds are ready and available as soon the download component finished. Video files take at least few hours before be available even if component is downloaded successfully.

[✓] Flutter (Channel stable, 2.10.5, on macOS 12.4 21F79 darwin-arm, locale it-IT)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.63.2)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

**Comment by maheshmnj** [comment]
Hi @enricoi, Thanks for filing the issue. You seem to be using an older version of flutter. Could you please try updating to the latest stable release? if the issue persists please share a minimal and complete sample project.
