### ISSUE TITLE
ERROR:flutter/flow/layers/transform_layer.cc(24) TransformLayer is constructed with an invalid matrix

### ISSUE THREAD

**Issue by cengizhanas** [flutter/flutter#107214]
flutter doctor -v no isue everything looking fine

**Comment by danagbemava-nc** [comment]
Hi @cengizhanas,

Can you please provide your `flutter doctor -v` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?

Thank you

**Comment by cengizhanas** [comment]
Hi @danagbemava-nc  I find problem ,problem is about my Dimensions and Stack widget and i solved it thank u for try to help 👍

**Comment by danagbemava-nc** [comment]
Closing this based on https://github.com/flutter/flutter/issues/107214#issuecomment-1178649489
