### ISSUE TITLE
[TextField] When hintText is Chinese, content offset down.When hintText is English or no hintText, no problem

### ISSUE THREAD

**Issue by NRMrYang** [flutter/flutter#107232]
## Steps to Reproduce
1. When hintText is "please", it shows
![hintText-please](https://user-images.githubusercontent.com/29404224/177770834-93b9ffb2-1108-443e-80e1-d5f3141b760c.jpg)
2. When hintText is "请", it shows
![hintText-请](https://user-images.githubusercontent.com/29404224/177770844-0c1afe9f-7eb4-4ef8-abbd-2fb77225a476.jpg)
3. Content offset down when hintText is Chinese. It is very obvious when hot reload
4. I already try:  
> TextField > style > textBaseline: TextBaseline.alphabetic  
> contentPadding: const EdgeInsets.symmetric(vertical: 0.0),  
> no inputBorder or transparent InputBorder  
5. Please tell me how to fix it! Extremely grateful!  
6. Flutter: Channel stable, 2.0.2. Code sample can review this problem.

<details>
<summary>Code sample</summary>

```dart
        Container(
          margin: EdgeInsets.fromLTRB(10, 10, 10, 10),
          decoration: BoxDecoration(
            border: Border.all(color: Colors.black, width: 1),
          ),
          child: TextField(
            keyboardType: TextInputType.multiline,
            maxLines: 5,
            minLines: 1,
            decoration: InputDecoration(
              // hintText: "please",
              hintText: "请",
            ),
          ),
        ),
```

</details>

<details>
  <summary>Flutter doctor</summary>

[√] Flutter (Channel stable, 2.0.2, on Microsoft Windows [Version 10.0.19044.1766], locale zh-CN)
    • Flutter version 2.0.2 at C:\flutter
    • Framework revision 8962f6dc68 (1 year, 4 months ago), 2021-03-11 13:22:20 -0800
    • Engine revision 5d8bf811b3
    • Dart version 2.12.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\20025\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] IntelliJ IDEA Ultimate Edition (version 2020.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2020.1.2
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code (version 1.67.2)
    • VS Code at C:\Users\20025\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (3 available)
    • MI 8 (mobile) • d4f88d6c • android-arm64  • Android 10 (API 29)
    • Chrome (web)  • chrome   • web-javascript • Google Chrome 102.0.5005.115
    • Edge (web)    • edge     • web-javascript • Microsoft Edge 101.0.1210.47

• No issues found!

</details>

**Comment by maheshmnj** [comment]
@NRMrYang,  I verified this on the latest stable channel and I don't see any difference when the `hintText` is english/chinese Please check the below output and the code sample.

English hintText             |  Chinese hintText
:-------------------------:|:-------------------------:
<img width="507" alt="image" src="https://user-images.githubusercontent.com/31410839/177923823-1f6ab412-92fb-4232-bb49-b88dee7e4d80.png"> | <img width="509" alt="image" src="https://user-images.githubusercontent.com/31410839/177923859-a2cd0def-1827-48f2-b2e0-e5b79a6bf772.png">

You can also  verify this on dartpad (btw dartpad shouldn't be considered as a standard to judge how flutter works on different platforms)

*Output from dartpad*
![image](https://user-images.githubusercontent.com/31410839/177925125-121bd49c-47cf-47df-9a74-60409f51dbf1.png)


<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);
  final String title;
  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Container(
              margin: EdgeInsets.fromLTRB(10, 10, 10, 10),
              decoration: BoxDecoration(
                border: Border.all(color: Colors.black, width: 1),
              ),
              child: TextField(
                keyboardType: TextInputType.multiline,
                maxLines: 5,
                minLines: 1,
                decoration: InputDecoration(
                  // hintText: "please",
                  hintText: "请",
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}

```
</details>

**Comment by NRMrYang** [comment]
@maheshmnj 
Flutter version 3.0.4 on [dartpad](https://dartpad.dev/?) , still has this problem. I add a line to show the difference more obviously.
| English hintText | Chinese hintText |
| :----: | :----: |
| ![English](https://user-images.githubusercontent.com/29404224/177930042-d752647b-df0d-4d9d-8a85-ca24499463ca.png) | ![Chinese](https://user-images.githubusercontent.com/29404224/177930033-70d6ae57-b163-4632-9fe6-000e751b3c54.png) |

please try code sample and enter "测试一下".

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);
  final String title;
  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Stack(
              children: [
                Container(
                  margin: EdgeInsets.fromLTRB(10, 10, 10, 10),
                  decoration: BoxDecoration(
                    border: Border.all(color: Colors.black, width: 1),
                  ),
                  child: TextField(
                    keyboardType: TextInputType.multiline,
                    maxLines: 5,
                    minLines: 1,
                    decoration: InputDecoration(
//                       hintText: "please",
                      hintText: "请",
                    ),
                  ),
                ),
                Positioned.fill(
                    child: Divider(
                  height: 1,
                  color: Colors.red,
                )),
              ],
            )
          ],
        ),
      ),
    );
  }
}

```
</details>

**Comment by NRMrYang** [comment]
already try:
> TextField > style > textBaseline: TextBaseline.alphabetic  
> contentPadding: const EdgeInsets.symmetric(vertical: 0.0),  
> no inputBorder or transparent InputBorder  
> isDense: true

**Comment by maheshmnj** [comment]
Thanks for the update @NRMrYang I do see very slight offset but perhaps I believe this is already being tracked here for Chinese text https://github.com/flutter/flutter/issues/96713 Do you think this will solve the issue?

**Comment by maheshmnj** [comment]
Thanks for the update @NRMrYang, I do see the text is slightly offset. With Chinese text.

 English hint             |  Chinese hint
:-------------------------:|:-------------------------:
<img width="235" alt="image" src="https://user-images.githubusercontent.com/31410839/178198950-8da05bca-d281-4f60-be84-beb906e38f3d.png"> | <img width="220" alt="image" src="https://user-images.githubusercontent.com/31410839/178199064-875fa232-90c8-4ee3-9e4e-85c2db4aa0d3.png">

Perhaps #96713 will help solve this issue. 

cc: @LongCatIsLooong  for confirmation.

<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel stable, 3.0.4, on macOS 12.4 21F79 darwin-arm, locale en-IN)
    • Flutter version 3.0.4 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 85684f9300 (4 days ago), 2022-06-30 13:22:47 -0700
    • Engine revision 6ba2af10bb
    • Dart version 2.17.5
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-32, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.67.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.44.0

[✓] Connected device (3 available)
    • sdk gphone arm64 (mobile) • emulator-5554 • android-arm64  • Android 11 (API 30) (emulator)
    • macOS (desktop)           • macos         • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)              • chrome        • web-javascript • Google Chrome 103.0.5060.53

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

```
[✓] Flutter (Channel master, 3.1.0-0.0.pre.1494, on macOS 12.4 21F79 darwin-arm, locale en-IN)
    • Flutter version 3.1.0-0.0.pre.1494 on channel master at /Users/mahesh/Documents/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 829bddf616 (3 hours ago), 2022-07-04 03:49:08 -0400
    • Engine revision e78ed7f1c9
    • Dart version 2.18.0 (build 2.18.0-251.0.dev)
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-32, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13C100
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.67.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.44.0

[✓] Connected device (3 available)
    • sdk gphone arm64 (mobile) • emulator-5554 • android-arm64  • Android 11 (API 30) (emulator)
    • macOS (desktop)           • macos         • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)              • chrome        • web-javascript • Google Chrome 103.0.5060.53

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by chinmaygarde** [comment]
Moving this to the framework. It is likely that the metrics of the typeface of the hint text are bring used to size and position the actual text.

**Comment by LongCatIsLooong** [comment]
It's a font issue. The font family in use doesn't have the glyph for "请" so it had to use the glyph from a different font. If you use a font family such as this one: https://fonts.google.com/noto/specimen/Noto+Sans+SC then you'll get consistent font metrics.

That said this isn't the first time people having issues with glyphs that don't exist in the default font family, and I found it very difficult to debug these issues. Let me see if I can find an existing issue for debugging font family fallback.

**Comment by NRMrYang** [comment]
Thanks for the response.  @LongCatIsLooong That means I have to change the default font family? I already try to avoid using hintText to catch development progress.I will try [this](https://fonts.google.com/noto/specimen/Noto+Sans+SC) when i'm not very busy.Thanks again!

**Comment by LongCatIsLooong** [comment]
Closing this for now. Feel free to reopen if the problem remains.
