### ISSUE TITLE
🐛 Android SDK version bug

### ISSUE THREAD

**Issue by zs-dima** [flutter/flutter#107209]
local.properties has minSdkVersion set
     `flutter.minSdkVersion=21`

\android\app\build.gradle has minSdkVersion set
     `minSdkVersion flutter.minSdkVersion`

But build error appear
│ The plugin firebase_dynamic_links requires a higher Android SDK version.
│ Fix this issue by adding the following to the file
│ \android\app\build.gradle:
│ android {
│   defaultConfig {
│     minSdkVersion 19

Yes, manual edit build.gradle to minSdkVersion 19 - is not acceptable solution.

**Comment by danagbemava-nc** [comment]
Hi @zs-dima, see https://github.com/flutter/flutter/issues/95533#issuecomment-1051489232 and https://github.com/flutter/flutter/issues/95533#issuecomment-1054513327. 

Closing this based on the linked comments. 

Thank you
