### ISSUE TITLE
[Web engine] Unexported files and external libraries are not accessible

### ISSUE THREAD

**Issue by dkwingsmt** [flutter/flutter#107271]
## Problem 1: Unexported files are not accessible

The way `sdk_rewriter.dart` is written currently requires that every file under `web_ui/lib/src/engine` is exported by `engine.dart`, even if it's not used externally. Otherwise it is not accessible by other files in the same folder even with `import`.

I'm working on a new class, `KeyboardLayoutDetector`, that is defined in a new file `web_ui/lib/src/engine/keyboard_layout_detector.dart`, and this class is used privately by `web_ui/lib/src/engine/keyboard_binding.dart`. I imported it, compiled, and got the following errors:

```
org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/keyboard_binding.dart:102:9: Error: Type 'KeyboardLayoutDetector' not found.
  final KeyboardLayoutDetector layoutDetector = KeyboardLayoutDetector();
        ^^^^^^^^^^^^^^^^^^^^^^
org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/keyboard_binding.dart:102:9: Error: 'KeyboardLayoutDetector' isn't a type.
  final KeyboardLayoutDetector layoutDetector = KeyboardLayoutDetector();
        ^^^^^^^^^^^^^^^^^^^^^^
org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/keyboard_binding.dart:102:49: Error: Method not found: 'KeyboardLayoutDetector'.
  final KeyboardLayoutDetector layoutDetector = KeyboardLayoutDetector();
```

After investigation, I found out that it's because I didn't export `keyboard_layout_detector.dart` in `engine.dart`. I shouldn't: it's a private class. However, `sdk_writer.dart` converts Web engine into Dart "parts", and, although it converts all files into with a `part of` header, it only converts `export`s in `engine.dart` into a `part` directive. Since this private file is not declared as a `part` despite it declares itself as a `part of`, it is not accessible by anyone.

If I understand correctly, each `part of` should have a corresponding `part`. Either we add `part` to every file we converted into `part of`, or warn these inaccessible files and do not include them at all.

## Problem 2: External libraries are not accessible

The same file, `keyboard_layout_detector.dart`, will need to import an external library:
```dart
import 'package:web_keyboard_layouts/web_keyboard_layouts.dart';
```
This part of code needs to be an external library because it uses a different license. ~~Currently `sdk_rewriter.dart` seems to strip off all import directives except for a hard-coded set.~~

**Edit:** Ok, it seems that there are much more things to do in order to add an external library. What do I need to do?

**Comment by dkwingsmt** [comment]
cc @yjbanov

**Comment by dkwingsmt** [comment]
Ok, it seems that there are more things to do in order to add an external library, namely `libraries.yaml`.

**Comment by eyebrowsoffire** [comment]
To the second issue, we cannot rely on packages in dart:ui as it is part of the Dart SDK. This is a general limitation of writing code that goes into the Dart SDK.

**Comment by eyebrowsoffire** [comment]
As for the first issue, @mdebbar might have some more insight. Is the behavior correct here around `sdk_rewriter.dart`'s treatment of the `part` and `part of` directives.

**Comment by dkwingsmt** [comment]
> To the second issue, we cannot rely on packages in dart:ui as it is part of the Dart SDK. This is a general limitation of writing code that goes into the Dart SDK.

Yes, I've talked with @/yjbanov and understood the limitation, and with @/Hixie for the intended solution.

**Comment by dkwingsmt** [comment]
> As for the first issue, @mdebbar might have some more insight. Is the behavior correct here around `sdk_rewriter.dart`'s treatment of the `part` and `part of` directives?

On second thought, if all files are marked as `part`, there will be no private files or symbols, and it is equivalent to exporting all files. Maybe what we should do is to warn against not exporting a file.

**Comment by yjbanov** [comment]
The `engine.dart` library is private. It's rewritten into `dart:_engine` (note the `_` in the library name). This makes anything exported from it invisible externally. It's OK to export anything and everything from it. As for the problem 2, as @eyebrowsoffire in https://github.com/flutter/flutter/issues/107271#issuecomment-1184753284 explains, as of today, this is by design. We cannot use pub packages in the engine.
