### ISSUE TITLE
windows keyboard issue

### ISSUE THREAD

**Issue by razzaqosama** [flutter/flutter#107204]
when i use flutter windows app
when use textfield
steps
1)click on textfield keyboard is appear need close manually
2) cannot dismiss keyboard  
3)when is use route to Navigate to next screen  keyboard is popup 
4) after close keyboard  then touch any where screen keyboard again is popup
5)focus and unfocused also dosent work

**Comment by razzaqosama** [comment]
https://user-images.githubusercontent.com/105033735/177737379-1e463df8-5031-4e10-9ddb-262fb212e1ec.mp4

import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);
  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  TextEditingController controller = TextEditingController();
  FocusNode focusNode = FocusNode();
  bool isFocused = false;

  @override
  void initState() {
    super.initState();
    focusNode.addListener(() {
      setState(() {
        isFocused = focusNode.hasFocus;
      });
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text('focusNode.hasFocus: $isFocused'),
            TextField(
              controller: controller,
              focusNode: focusNode,
            ),
            const SizedBox(height: 20),
            Row(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                ElevatedButton(
                  onPressed: () {
                    FocusScope.of(context).requestFocus(FocusNode());
                  },
                  child: const Text('unfocus'),
                ),
                const SizedBox(width: 20),
                ElevatedButton(
                  onPressed: () {
                    Navigator.of(context)
                        .push(MaterialPageRoute(builder: (context) {
                      return const NewsPage();
                    }));
                  },
                  child: const Text('go to news page'),
                ),
              ],
            )
          ],
        ),
      ),
    );
  }
}

class NewsPage extends StatefulWidget {
  const NewsPage({Key? key}) : super(key: key);

  @override
  _NewsPageState createState() => _NewsPageState();
}

class _NewsPageState extends State<NewsPage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('new pages'),
      ),
      body: const Center(
        child: Text('new pages'),
      ),
    );
  }
}

**Comment by huycozy** [comment]
@razzaqosama, thank you for providing the details.
I see there's an open issue addressing the case you described #99050
Closing as a duplication, so please follow up on it for further updates.
