### ISSUE TITLE
Unhandled Exception: RangeError (index): Invalid value: Valid value range is empty: 0

### ISSUE THREAD

**Issue by naseerz** [flutter/flutter#107206]
**_FLUTTER DOCTOR_**
![Capture](https://user-images.githubusercontent.com/92418626/177688770-f1e72feb-2f13-4366-a7a3-91dde0f56216.PNG)
)

I am facing the issue while using tabbar in flutter.
I have three tabs in my screen and i am posting different API on every single tab.

I am saving the index number of a tabbar in a variable **selectIndex** while tapping on tabbar
`   onTap: (index) {
                          setState(() {
                            selectIndex = index;
                          });
                        },`

Then i am using switch statement to post API as shown as below.

`switch (selectIndex) {
                case 0:
                  posShareApi();
                  break;
                case 1:
                  postFindApi();
                  break;
                case 2:
                  postQueryApi();
                  break;
              }`

Thats all the info about my problem 
thank you

**Comment by danagbemava-nc** [comment]
Hi @naseerz, the code sample you have provided is not enough to make this issue actionable on our part. 

Please provide a complete minimal reproducible code sample, preferably without any third-party packages, so that we can investigate further. 

Thank you

**Comment by naseerz** [comment]
i have no soluion

**Comment by danagbemava-nc** [comment]
Without a minimal sample that reproduces the issue, we cannot investigate this issue
