### ISSUE TITLE
[Impeller] Implement a Vulkan backend.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#107357]
A prototype for this backend is currently in the icebox at https://github.com/flutter/engine/pull/34212. We can either revive that or start from scratch.

**Comment by chinmaygarde** [comment]
cc @iskakaushik who is thinking of direction of the Impeller backend to use on Android. The choice for a modern backend will either be OpenGL ES 3.2 with ES 2 fallback or Vulkan with ES 2 fallback.

**Comment by gustav3d** [comment]
A "modern" backend is per definition not based on something stagnated like OpenGL ES which is stuck on 3.2 , where only extensions is the development.

**Comment by chinmaygarde** [comment]
Thats totally fair. The stuff Impeller needs from a "modern" backend are compute and/or tessellation shaders. But I agree I'd prefer to use Vulkan with ES 2 fallback. The [arguments for a single ES backend](https://github.com/flutter/flutter/issues/105644#issuecomment-1150380115) are mostly around compatibility and binary size at this point.

**Comment by whiskeyPeak** [comment]
I would also second a Vulkan backend.

Along with much better multi-threaded support, in the future there might be a use in implementing a Vulkan backend for Linux and Windows too.

**Comment by chinmaygarde** [comment]
@iskakaushik Since we are now committed to writing the backend and the pieces are landing along with the smaller work items having issues of their own, can we close this umbrella bug and focus on items [on the dashboard instead](https://github.com/orgs/flutter/projects/21).

**Comment by iskakaushik** [comment]
sounds good!
