### ISSUE TITLE
[Documentation] Boring to Beautiful codelab hasn't been updated for go_router 4

### ISSUE THREAD

**Issue by sammic297** [flutter/flutter#107354]
I am having difficulty running step_01 in boring_to_beautiful.
When I run the app, I get an error:

```
 This GoRouteInformationParser needs to be used with GoRouteInformationProvider, did you forget to pass in GoRouter.routeInformationProvider to the Router constructor?
'package:go_router/src/go_route_information_parser.dart':
Failed assertion: line 148 pos 13: 'routeInformation is DebugGoRouteInformation'
```

**Comment by Pr47h4m** [comment]
if you see go router object you will have 1 property called `routeInformationProvider`
you need to pass that property in `MaterialApp.router()`

example: 
```
MaterialApp.router(
        routeInformationParser: router(context).routeInformationParser,
        routeInformationProvider: router(context).routeInformationProvider,
        routerDelegate: router(context).routerDelegate,
        title: 'My App',
)
```
Please note in my case i have created function called router in another file 
function signature 
`GoRouter router(BuildContext);`

**Comment by danagbemava-nc** [comment]
Hi @sammic297, thanks for catching that. 

The bot updated the go_router dependency to 4.0.0 in https://github.com/flutter/codelabs/commit/5a584831fe8e15922e37067610b23a912c8a8cb0 but it looks like the code wasn't updated for go_router 4. There's a PR in progress to address this issue in https://github.com/flutter/codelabs/pull/1004

/cc @domesticmouse

**Comment by khanhnwin** [comment]
Thanks @sammic297! Just merged flutter/codelabs#1004 which should resolve this issue. Please let me know if you're still running into issues!

**Comment by danagbemava-nc** [comment]
Per our triage policy, I'll be closing this issue since the linked PR has been merged. 

@sammic297, if you do run into this issue after checking out the latest source, kindly leave a comment below and this issue will be reopened. 

Thank you

**Comment by sammic297** [comment]
Thanks, everyone.
I will update the clone shortly. 
Namaste 🙏🏾🙏🏾🙏🏾
