### ISSUE TITLE
[RepaintBoundary] Cannot take screenshot with platform views

### ISSUE THREAD

**Issue by AlexV525** [flutter/flutter#107308]
## Steps to Reproduce

1. Clone the edited example of the `camera` plugin: https://github.com/AlexV525/flutter-plugins/tree/take-screenshot
2. Select an available camera and wait until it initialized.
3. Tap the "Screenshot" button, then the screenshot will be displayed in a new dialog.

| Displays | Screenshot |
|:-------:|:-------:|
| ![image](https://user-images.githubusercontent.com/15884415/178009368-0223cad2-1678-4c62-a7b3-75ffbc7ba20d.png) | ![image](https://user-images.githubusercontent.com/15884415/178009456-4249c86b-6d35-44be-9157-aff3e0c6d32c.png) |

**Expected results:** The platform view got captured in the screenshot.

**Actual results:** The platform view is black(blank) in the screenshot.

</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.0.4, on macOS 12.4 21F79 darwin-x64, locale zh-Hans-CN)
    • Flutter version 3.0.4 at /Users/alex/Documents/flutter-stable
    • Upstream repository https://github.com/flutter/flutter
    • Framework revision 85684f9300 (8 days ago), 2022-06-30 13:22:47 -0700
    • Engine revision 6ba2af10bb
    • Dart version 2.17.5
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Volumes/T5/android-sdk
    • Platform android-33, build-tools 32.0.0
    • ANDROID_HOME = /Volumes/T5/android-sdk
    • ANDROID_SDK_ROOT = /Volumes/T5/android-sdk
    • Java binary at: /Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)
    • All Android licenses accepted.

[✓] Android Studio (version 2021.2)
    • Android Studio at /Users/alex/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/212.5712.43.2112.8609683/Android Studio.app/Contents

[✓] Connected device (3 available)
    • ONEPLUS A6010 (mobile) • f8e67ce3 • android-arm64  • Android 11 (API 30)
```

</details>

**Comment by AlexV525** [comment]
This is the same issue as #25306, but it's not solved. Instead, #83856 turn this into a test issue, then #97853 turn this into a test coverage issue.

**Comment by huycozy** [comment]
Hi @AlexV525, thanks for filing the issue. 
I see there's an open issue addressing the case you described #102866. This issue is opened recently.
Closing as a duplication, so please follow up on it for further updates.
