### ISSUE TITLE
Android+iOS usage of User Certificate Authorities with dart.io

### ISSUE THREAD

**Issue by ImdShatz** [flutter/flutter#107373]
Hi,

Our application which is a mobile application written in flutter targets both Android and iOS, and is deployed On-Premise (The Backend API is installed on premise, and isn't public to the internet)

As part of our solution, the customer often has their own Certificate Authority for their internal network, and does not have access to public certificates.

We planned to deploy that private CA certificates to the mobile devices, as a trusted root certificate (also known as a user-ca), and planned for flutter to trust the API server certificate issued from that CA.

However, it seems that flutter isn't using the User CA in any of its internal operations, and always returns this error:
Unhandled Exception: HandshakeException: Handshake error in client (OS Error: E/flutter ( 7370): CERTIFICATE_VERIFY_FAILED: self signed certificate(handshake.cc:354))

At first we thought it is because we are missing some manifest as described [here](https://developer.android.com/training/articles/security-config) (in case of android), however it seems that flutter completely ignores it (dart.io), and and uses only its internal logic (non-platform) to approve/reject the certificate.

The only thing that worked is specifying the certificate as a [Trusted Certificate](https://api.dart.dev/stable/2.17.5/dart-io/SecurityContext/setTrustedCertificatesBytes.html) as part of the SecurityContext of dart.

This however does not allow us to specify a trusted root certificate, but rather a 'self-signed' certificate type of approach.
Further more, even if it did, we would still need to find a secure way to load the trusted user certificate from android/iOS and give it to flutter as input, as it is different per-customer/deployment.

Can you advise on a possible solution, or better yet, add support within flutter for this scenario?

**Comment by exaby73** [comment]
Hi @ImdShatz, please provide a [minimal, reproducible example][1] and the output of `flutter doctor -v` as well as `flutter run -v` so that we can investigate the issue. Would be ideal if you could also include the steps you are taking to produce the self-signed user ca and how you're installing it on the app/device.

[1]: https://stackoverflow.com/help/minimal-reproducible-example
