### ISSUE TITLE
If you reset iOS simulator with IntelliJ open, it forgets the simulator

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#10734]
The only recourse appears to be to restart IntelliJ.

@lukef just ran into this while showing me another issue.

This is not blocking Posse, but was annoying.

FYI @devoncarew

**Comment by eseidelGoogle** [comment]
Maybe we need some way to force the `flutter daemon` to rescan?

**Comment by mit-mit** [comment]
I can't repro this. I tried:

1. Start IntelliJ
1. Create a Flutter project
1. Start the iOS Simulator
1. Confirm the IJ device picker shows the simulated device
1. In the iOS Simulator, invoke Simulator > Reset Settings and Content
1. Wait for Simulator to boot
1. Confirm the IJ device picker shows the simulated device

**Comment by eseidelGoogle** [comment]
Maybe @lukef reset simulator hadn't booted yet.  I was watching him over VC.

**Comment by devoncarew** [comment]
I'm going to close this as can't repro; we can re-open if we see more cases of it.
