### ISSUE TITLE
Building Beautiful UIs Tutorial - Silly Link Display

### ISSUE THREAD

**Issue by rachelward9** [flutter/flutter#10731]
## Steps to Reproduce

On [step six](https://codelabs.developers.google.com/codelabs/flutter/index.html#5) under _Place the message list_, there is a chopped up link on, "Naming the argument..."
<img width="551" alt="capture" src="https://user-images.githubusercontent.com/4926352/27195476-260ab37c-51c4-11e7-91d8-6c030b86be46.PNG">

**Comment by eseidelGoogle** [comment]
That's amazing. :D  I didn't even know CSS could do that.

**Comment by Hixie** [comment]
That's not CSS, every other letter is hyperlinked somehow.

**Comment by LarkAscending** [comment]
It's a Google Docs/codelab bug - the empty space before the "N" character erroneously was linked in Google Docs, and this was the result (visible only in the codelab UI).

Fixed:
https://codelabs.developers.google.com/codelabs/flutter/#5
