### ISSUE TITLE
Building Beautiful UIs with Flutter - `@override` placement error

### ISSUE THREAD

**Issue by rachelward9** [flutter/flutter#10739]
## Steps to Reproduce

Follow the tutorial through step 6, and see that `@override` is on `Widget build(BuildContext context)`.

<img width="966" alt="step6" src="https://user-images.githubusercontent.com/4926352/27198584-07cbe10e-51d0-11e7-9e6b-42f883b3a221.PNG">

Proceed to step 7, and see that the `@override` has been moved from there to above the class `ChatMessage`.

<img width="790" alt="step7" src="https://user-images.githubusercontent.com/4926352/27198589-0ce96922-51d0-11e7-934c-d96d4a6c9098.PNG">

**Comment by eseidelGoogle** [comment]
@LarkAscending or possibly @collinjackson can fix.

**Comment by LarkAscending** [comment]
Thanks for the detailed description! This was a sync issue with an older vs. newer version of the sample code. Updated:
https://codelabs.developers.google.com/codelabs/flutter/#5
