### ISSUE TITLE
flutter version constraints in `pubspec.yaml` allows versions newer than the specified range

### ISSUE THREAD

**Issue by DetachHead** [flutter/flutter#107364]
## Steps to Reproduce

1. add a flutter version constraint like this to `pubspec.yaml`:
   ```yaml
    environment:
      sdk: ">=2.16.1 <3.0.0"
      flutter: "<=2.10.5"
   ```
2. upgrade to the latest flutter version (`flutter upgrade`)
3. run `flutter pub get`

**Expected results:** 
error because the installed flutter version doesn't match the constraint

**Actual results:** 
no error
```
>flutter pub get
Running "flutter pub get" in project...                           6.0s

>
```

## `flutter doctor`
```
>flutter doctor   
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.0.4, on Microsoft Windows [Version 10.0.19044.1766], locale en-AU)
[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Build Tools 2019 16.8.3)
[!] Android Studio (not installed)
[√] IntelliJ IDEA Community Edition (version 2019.2)
[√] IntelliJ IDEA Ultimate Edition (version 2022.1)
[√] VS Code, 64-bit edition (version 1.65.2)
[√] Connected device (4 available)
[√] HTTP Host Availability

! Doctor found issues in 1 category.
```

**Comment by maheshmnj** [comment]
Hi @DetachHead, Thanks for filing the issue.

There is a similar issue describing this case https://github.com/flutter/flutter/issues/95472, Please follow up there for further updates, Closing this issue as a duplicate. If you disagree feel free to write in the comments and we will reopen it.

Thank you.
