### ISSUE TITLE
when the app hasn't fully started yet the play button should be dimmed

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#10735]
@lukef was showing me him hitting https://github.com/flutter/flutter/issues/10228 and not being able to run on an iOS simulator.

simctl was constantly retrying, he would hit the "play" button in IntelliJ (and you would expect that to do something, e.g. a hot restart) but it didn't, since the app hadn't actually fully started yet.  It seems in this state either the Play button should be dimmed or it should do a full cold restart?

@devoncarew @mit-mit

**Comment by mit-mit** [comment]
I think the button should be dimmed; that would be consistent with Android Studio, which dims until the app is actually running and then transitions to the 'play with green dot' state.

**Comment by FlutterIssues** [comment]
This issue was moved to flutter/flutter-intellij#2120
