### ISSUE TITLE
Report custom stack trace for `PlatformException` on Android

### ISSUE THREAD

**Issue by ueman** [flutter/flutter#107392]
## Use case

On Android, a native stacktrace can be reported if something happens on the native side, see https://master-api.flutter.dev/flutter/services/PlatformException/stacktrace.html. 
However, all of these cases are just from within the Flutter framework. 
I would like to have the ability to report my own exception stacktraces for error cases.

This enables us to better report exceptions to monitoring tools, like Sentry, DataDog etc., because until now, these exceptions had to be caught and reported in one of the other fields of the `PlatformException`. This makes automated parsing of PlatformExceptions nearly impossible because it's unstructured.

(Also relates to this comment https://github.com/flutter/flutter/issues/97698#issuecomment-1092714020) 

## Proposal

Add a `void errorWithStackTrace(@NonNull String errorCode, @Nullable String errorMessage, @Nullable Object errorDetails, @NonNull StackTrace stackTrace);` method to the `Result` class here
https://github.com/flutter/engine/blob/b0c129db124d19e4c55d242701e5792be9d304a8/shell/platform/android/io/flutter/plugin/common/MethodChannel.java#L198-L222

**Comment by noinskit** [comment]
I'd love to use this feature as well! What's the status? Has the proposal/merge request been rejected?

**Comment by ueman** [comment]
You can already do this as explained on https://api.flutter.dev/flutter/services/PlatformException/stacktrace.html
