### ISSUE TITLE
Flutter 3.0.4 - display bug on text widget with Thai Character

### ISSUE THREAD

**Issue by naijab** [flutter/flutter#107390]
## Flutter for android

Widget Structure:

```dart
InkWell
- Container
--- Text("ใช้")
```

Actual:

```
-----
| ใ |
| ช้ |
-----
```

Expect (Before upgrade to flutter 3.0):

```
-----
| ใช้ |
-----
```

Temp solution for now is add space to after word `“ใช้<space>“`

## Flutter Doctor
```
[✓] Flutter (Channel stable, 3.0.4, on macOS 12.4 21F79 darwin-arm, locale en-TH)
    • Flutter version 3.0.4 at /Users/naijab/SDK/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 85684f9300 (11 days ago), 2022-06-30 13:22:47 -0700
    • Engine revision 6ba2af10bb
    • Dart version 2.17.5
    • DevTools version 2.12.2
```

**Comment by exaby73** [comment]
Hello @naijab. Looks like this issue is fixed in master. Please confirm it on your end

**Comment by naijab** [comment]
> Hello @naijab. Looks like this issue is fixed in master. Please confirm it on your end

Thanks I will try

**Comment by naijab** [comment]
> Hello @naijab. Looks like this issue is fixed in master. Please confirm it on your end

which commit : I need to learn how to fix it?

**Comment by exaby73** [comment]
@naijab You can run `flutter channel master` and `flutter upgrade` then run your app

**Comment by arnirichard** [comment]
I am having similar problems, not sure if that is the same problem
https://github.com/flutter/flutter/issues/108778

**Comment by arnirichard** [comment]
Works for me after `flutter channel master`

**Comment by exaby73** [comment]
Since this issue is fixed on master, I am closing it. If you disagree, please comment and we can reopen it
