### ISSUE TITLE
Provide detailed timezone information

### ISSUE THREAD

**Issue by tjarvstrand** [flutter/flutter#107309]
## Use case
I want to send push notifications containing accurate timestamps in payload. To enable this I would like to be able to get access to detailed timezone information from the platform so that I can pass it to my backend. 

`DateTime.timeZoneName` returns abbreviated names and is not reliable as it produces ambiguous values (see eg. https://stackoverflow.com/questions/64467722/timezones-abbreviations). On my current device calling this method returns `CEST` which is not even parseable to a `ZoneId` in Java.

Previously, there has been the [flutter_native_timezone](https://pub.dev/packages/flutter_native_timezone) package to alleviate this shortcoming but that now seems more or less dead as a project and reportedly does not even install with recent versions of Flutter.

## Proposal
I would like to request a method to access the platform's actual [IANA timezone name](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones).

**Comment by iamsahilsonawane** [comment]
This is an already known issue on Dart SDK https://github.com/dart-lang/sdk/issues/21758

**Comment by iapicca** [comment]
> This is an already known issue on Dart SDK [dart-lang/sdk#21758](https://github.com/dart-lang/sdk/issues/21758)

an issue dated Dec 1, 2014 and last interaction more than a year old,
maybe flutter could address it separately

**Comment by iamsahilsonawane** [comment]
> 

Agreed

**Comment by iamsahilsonawane** [comment]
> > This is an already known issue on Dart SDK [dart-lang/sdk#21758](https://github.com/dart-lang/sdk/issues/21758)
> 
> an issue dated Dec 1, 2014 and last interaction more than a year old, maybe flutter could address it separately

Agreed!

**Comment by maheshmnj** [comment]
Hi @tjarvstrand, Thanks for filing the issue, Since the DateTime class is from the `dart:core` library, I would suggest filing this issue in the [dartlang SDK](https://github.com/dart-lang/sdk) repo and more specifically following up on the open issue https://github.com/dart-lang/sdk/issues/21758 rather than filing a new one.

Closing as this is not an issue with flutter.

**Comment by iapicca** [comment]
> Hi @tjarvstrand, Thanks for filing the issue, Since the DateTime class is from the `dart:core` library, I would suggest filing this issue in the [dartlang SDK](https://github.com/dart-lang/sdk) repo and more specifically following up on the open issue [dart-lang/sdk#21758](https://github.com/dart-lang/sdk/issues/21758) rather than filing a new one.
> 
> Closing as this is not an issue with flutter.

@maheshmnj 
I think this [comment](https://github.com/dart-lang/sdk/issues/21758#issuecomment-681139483) makes a good case on why this should be treated as a flutter issue

> Considering this needs an implementation on the platform level (ios, android, web, ...), is the dart SDK the correct place to make this ask?
