### ISSUE TITLE
I have an issue with flutter doctor 

### ISSUE THREAD

**Issue by Steven20201** [flutter/flutter#107310]
[!] HTTP Host Availability
    X HTTP host "https://pub.dev/" is not reachable. Reason: An error occurred while checking the HTTP host: The semaphore timeout period has expired.

**Comment by iamsahilsonawane** [comment]
@Steven20201 A semaphore timeout indicates that your operating system failed to connect to a network or retrying to connect. That's the reason you're not able to reach the https://pub.dev host

You can try some options from [this](https://www.stellarinfo.co.in/blog/how-to-fix-the-semaphore-timeout-period-has-expired-0x80070079/) link.

**Comment by christopherfujino** [comment]
@Steven20201 it appears like this is an issue with your local setup, and not with the Flutter SDK.

If you believe your computer is able to reach pub.dev and the problem is with the Flutter SDK, please provide reproduction instructions and the full output of `flutter doctor -v`.
