### ISSUE TITLE
[quick_actions] - Not redirecting on iOS

### ISSUE THREAD

**Issue by giovanni256** [flutter/flutter#107398]
Hi there.
I'm testing my app on iOS and I found that Quick Actions are not working on iOS.

They appears in the app menu, but quick actions are not working as well as Android.

main.dart

```
String redirect = "default";

 void initState() {
quickActions.initialize((String shortcutType) {
      switch (shortcutType) {
        case 'map':
          return setState(() {
            redirect = "map";
          });
        case 'files':
          return setState(() {
            redirect = "files";
          });
        default:
          return setState(() {
            redirect = "map";
          });
      }
    });
    quickActions.setShortcutItems([
      ShortcutItem(
          type: 'map',
          localizedTitle: "Map",
          icon: Platform.isAndroid ? 'short_map' : 'map'),
      ShortcutItem(
          type: 'file',
          localizedTitle: "Files",
          icon: Platform.isAndroid ? 'short_files' : 'files'),
    ]);

    if (redirect == "map") {
            debugPrint(">> SHORTCUT > MAP");
            Navigator.pushAndRemoveUntil(
              context,
              MaterialPageRoute(builder: (context) => MapPage()),
              (Route<dynamic> route) => false,
            );
            Navigator.of(context).push(_map());
          }
 if (redirect == "files") {
            debugPrint(">> SHORTCUT > FILES");
            Navigator.pushAndRemoveUntil(
              context,
              MaterialPageRoute(builder: (context) => FilesPage()),
              (Route<dynamic> route) => false,
            );
            Navigator.of(context).push(_files());
          }
  }
```

It is working on Android but on iOS I only get icons.
If I tap on a quick action, it just opens the app but not at the desired page.

flutter doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.5, on macOS 12.4 21F79 darwin-x64, locale it-IT)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google
    Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.68.1)
[✓] Connected device (1 available)
    ! Device f2c44a6d is not authorized.
      You might need to check your device for an authorization dialog.
[✓] HTTP Host Availability

! Doctor found issues in 1 category.
```

I'm using the latest version of quick_actions (0.6.0+11)

**Comment by danagbemava-nc** [comment]
Hi @giovanni256, you appear to be on an older version of flutter. Kindly upgrade to the latest version of flutter to see if you still experience this issue. 

If you do, please provide the updated output of `flutter doctor -v` as well as a complete minimal reproducible code sample so that we can investigate this. 

Thank you

**Comment by giovanni256** [comment]
> Hi @giovanni256, you appear to be on an older version of flutter. Kindly upgrade to the latest version of flutter to see if you still experience this issue.
> 
> If you do, please provide the updated output of `flutter doctor -v` as well as a complete minimal reproducible code sample so that we can investigate this.
> 
> Thank you

Hi there, thanks for your time.
I want to use this Flutter versione because I don't want to use the non-nullable language since I'm still learning Flutter.

Can I do something to avoid that?

**Comment by danagbemava-nc** [comment]
Hi @giovanni256, I'm not sure I fully understand your question. 

Can you provide a bit more detail?

**Comment by giovanni256** [comment]
> 

Yes, sure.
I want to keep the actual 2.10.5 Flutter version because if I upgrade to 3.0.4 I will have to fix a loro of bugs because of the null safety.

In addition I don't understand why the 2.10.5 version should cause this issue since in the changelog Quick Actions supports versions > 2.8

**Comment by danagbemava-nc** [comment]
Hi @giovanni256, 

> I want to keep the actual 2.10.5 Flutter version because if I upgrade to 3.0.4 I will have to fix a lot of bugs because of the null safety.

You will eventually have to upgrade. My recommendation is to do it as early as you can so you don't have more to fix later on. The transition from 2.10 to 3.0 was quite painless, in my experience. 

> In addition, I don't understand why the 2.10.5 version should cause this issue since in the changelog Quick Actions supports versions > 2.8

There have been instances where the are some improvements in the engine/framework that have fixed issues we weren't aware of (this goes in the other direction too), that is why we usually request that people upgrade to the latest version of flutter so that if it works, you can just continue with your project and not wait for a fix/workaround. 

That being said, please provide a *complete minimal reproducible code sample* so that we can investigate this. 

Thank you
