### ISSUE TITLE
 [tool] Android embedding v2 migration warning points to a dead link

### ISSUE THREAD

**Issue by stereotype441** [flutter/flutter#107437]
I'm trying to help someone fix a broken flutter project, and they're seeing the following error message:

```
This app is using a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to migrate this app to the V2 embedding.
Take a look at the docs for migrating an app: https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects
The plugin `wakelock` requires your app to be migrated to the Android embedding v2. Follow the steps on https://flutter.dev/go/android-project-migration and re-run this command.
```

I still haven't gotten to the bottom of what's going wrong with my friend's flutter project, but what's particularly troublesome to me is that if I click on the second of these two links (https://flutter.dev/go/android-project-migration), I get a 404 error.  It seems to me that regardless of what's wrong with any given flutter project, Flutter should not be issuing an error message containing a broken link.

Is it possible that a "go" link on the Flutter website got inadvertently deleted?  If so, is it possible to restore it?

**Comment by maheshmnj** [comment]
Hi @stereotype441, Thanks for filing the issue. Perhaps the second link is no longer in use. To fix the warning you need to migrate your project to android embedding v2 using the first link https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects.
Can you please share the output of `flutter doctor -v`? My guess is the broken link won't be suggested on the newer releases of flutter.

**Comment by christopherfujino** [comment]
Fixed in https://github.com/flutter/flutter/pull/107456
