### ISSUE TITLE
Add more platform specific logging

### ISSUE THREAD

**Issue by mattsarett** [flutter/flutter#10745]
Flutter has a wide variety of backends for different platforms, simulators, and emulators.  And in many of the GPU backends, there are variety of fallback paths, ex: first try sRGB 8888, then 8888, then 4444, etc.

It would be really helpful for debugging and general issue diagnosis to log what backend Flutter is running on, on start-up.

Let's add those logs.

@eseidelGoogle

**Comment by tvolkert** [comment]
Whatever we add to the logging could also be added to our bug reports -- https://github.com/flutter/flutter/issues/10746

**Comment by eseidelGoogle** [comment]
This should be a relatively easy fix to the c++ code, if we know where it is.  @chinmaygarde would know the links to the source or @GaryQian might.

**Comment by Hixie** [comment]
Please only actually log the information on request (e.g. in response to a crash or exposed through an API that is used by the debugDump* methods). The log should be completely silent in normal operation.

**Comment by Hixie** [comment]
I think it's fine to add more logging in certain cases (e.g. if there's a flag set, or when we have an error), but as a general rule we shouldn't have chatty logs. So I'm going to close this. But please don't hesitate to submit PRs to add more debugging information within those guidelines.
