### ISSUE TITLE
Provide support for all return types when running JavaScript in the webview plugin

### ISSUE THREAD

**Issue by bparrishMines** [flutter/flutter#107491]
In pre 4.0, the webview plugin only provides support for [returning strings](https://pub.dev/documentation/webview_flutter_platform_interface/latest/webview_flutter_platform_interface/WebViewPlatformController/runJavascriptReturningResult.html) when running JavaScript.

However, iOS supports multiple return types: https://developer.apple.com/documentation/webkit/wkwebview/1415017-evaluatejavascript?language=objc

For iOS, the return object is converted to a String on the Objective-C side. This causes an incorrect representation of some objects when they are returned to Dart. For example, booleans are represented as an `NSNumber` in  Objective-C, but are converted to a `0` or `1` when converted to a string. (`true`/`false` are the expected results).

For `webview_flutter` version 4.0+, `runJavascriptReturningResult` should return a `Future<Object?>`.

**Comment by stuartmorgan** [comment]
This was fixed in v4.
