### ISSUE TITLE
Platform-View List / Grid scrolling is janky on IOS / Android

### ISSUE THREAD

**Issue by Nico3652** [flutter/flutter#107486]
My team and I are facing troubles for a while trying to implements native views inside scrollable content in our App. 

The real problem here is that the Platform View rendering is very heavy and as a consequence the scrolling animation make it visible on screen by lag / freezing the UI. 
So when native views are placed into ListView / GridView, the entire screen start to freeze because of performance.

Here are 2 videos to illustrate my words. A simple ListView with widgets inside.
The first contain Flutter widgets and the second Native views.

FLUTTER : 

Flutter | NATIVE (IOS)
:-: | :-:
<video src='https://user-images.githubusercontent.com/50270977/178569163-1717bfac-d02d-4605-becb-3f543aff3e73.mp4' width=180/> | <video src='https://user-images.githubusercontent.com/50270977/178569310-860ef9fc-60d4-4bf5-b44c-75b52dcd8d2a.mp4' width=180/> 

This is a completely empty App so the freezing could may be not very pronounced here but a simple app with common content (ex: users/photos) is much more impacting. 

It was record on IOS but clearly tested on Android too and the problem still persist. 

Our App is a full social media (photo / video / story) and when we are trying to add native view inside lists, this app quickly become unusable. 

Here are linked issues #96679  (which should not be closed)

------------------------------------------------------

GOOGLE ADS SDK

Also currently trying to provide Ads into our Social Media app between photo and videos lists, the performance issue is even worse than the recorded example here while scrolling or animating other components. 

ADS are provided with Platform View so the problem is remaining once again here, and this is very restrictive for us because we can not go in production version without ADS and native view because of business model. 

Linked issues :

https://github.com/googleads/googleads-mobile-flutter/issues/269
https://github.com/googleads/googleads-mobile-flutter/issues/313

------------------------------------------------------

This issue should have a high priority level taking into account the huge impact for company or developers teams into their app. 

Thank you.   

-- FULL CODE --

https://github.com/Nico3652/native_view_project

-- FLUTTER DOCTOR -- 

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.4, on macOS 12.4 21F79 darwin-x64, locale
    fr-FR)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.65.2)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

• No issues found!
```

**Comment by b3nni97** [comment]
I have the same problem #103014

**Comment by euphio** [comment]
+1 Also experiencing this issue and require the exact same use case as described above.

**Comment by maheshmnj** [comment]
Hi @Nico3652, Thanks for filing the issue. Could you please share a minimal and complete sample project so that we could directly run the sample app?   Also there have been recent updates to platform views, So I would suggest checking the performance on the latest master channel by running 

```
flutter channel master
flutter upgrade
```

**Comment by Nico3652** [comment]
Hello @maheshmnj  and thanks for reply. I've updated my issue with the link of the sample app containing the full code which you can clone. 

I tried the channel master but the problem is still present unfortunately.

**Comment by Nico3652** [comment]
This issue is focused on the platform view performance impact in its generality and not only for the Native ads SDK. 

Solve the platform view issue will certainly also solve the ads performance but I'm not sure the opposite.
If the google_ads_sdk is improved or workarounded one way or another without fix the platform view render, then this issue should remain.

**Comment by euphio** [comment]
Agreed, the Native ad issue appears to be a symptom of this more general performance problem, not the other way around.

**Comment by jmagman** [comment]
@cyanglaz do we have any benchmarks for this?

**Comment by cyanglaz** [comment]
> @cyanglaz do we have any benchmarks for this?

I think we do: https://github.com/flutter/flutter/tree/master/dev/benchmarks/platform_views_layout

**Comment by Tom3652** [comment]
This issue is preventing me from going in production unfortunately

**Comment by cyanglaz** [comment]
@Tom3652 iOS PlatformView requires all flutter compositing happen on the main thread, which slows down the performances, especially when there are many platform views in a scroll view.
See: https://docs.flutter.dev/development/platform-integration/ios/platform-views?tab=ios-platform-views-objective-c-tab#performance

May I ask what content are you trying to display as PlatformViews? Is there a way to make them non-platformView flutter widgets?

**Comment by b3nni97** [comment]
@cyanglaz One use case that concerns me is the display of ads that run entirely through Platform Views and not through Flutter Widgets.

**Comment by cyanglaz** [comment]
iOS doesn't have a native support for displaying content in UIView in a texture, so a similar approach like Android is impossible on iOS.

We should revisit the iOS PlatformView's performance at some point to see if we can increase the performance within the current threading model for PlatformVIews.

**Comment by Tom3652** [comment]
Hey @cyanglaz thank you for asking actually.

My use case is the same as described above : displaying native ads in scrollable content.
My app is also a social media app, i am gonna say like instagram so everyone has the example in mind.

Instagram has a lot of success so people pay to promote their content and Instagram display it (like ads) through URLs as their own `Post` object so they can't have unexpected UI behavior. 

But as a start, i can't do like them because users will not think it's worth it yet, so i want to display Google Native ads in the same way inside `ListView.builder` or `GridView.builder`. 

I have also upvoted a feature request that ask to make Google native ads implemented in dart code only and not using `PlatformViews`.

I really wish i could not be using `PlatformViews` but i don't think i can do something myself here unfortunately :/ 
If there is anything i can do to help i am available of course let me  know 🙏🏻

**Comment by euphio** [comment]
My use case is essentially identical to that of @Tom3652 - Native Google Ads in a steam of content, although I can imagine there would be requirements for other native views in such a feed.

**Comment by naamapps** [comment]
Hey guys,
Adding to all of the previous comments,
The ideal solution will be not using PlatformViews at all when possible, however, the implementations of all the critical packages (ads in particular) are using platform views.

The Android platform views are fixed to a degree.
In iOS the situation is far worse.

I think the Flutter teams should really prioritize these issues. Most of the attention now are given to expanding flutter to more platforms (web, desktop), even when the initial platforms (iOS, Android) are not perfectly executed unfortunately.

Hope we can see a solution in the near future.
Thank you.

**Comment by iosephmagno** [comment]
Yes guys please put web/desktop on hold a bit. We jumped on flutter due to its native-like performance promise and we got stuck in a nightmare. Lags, janky animations, flickering, emojis wrong rendering, text input issues and keyboard weird animation, lacks of platform fidelity for text input and no deadlines for fixes.

We had to postpone our launch waiting for improvements. But these severe issues are mostly assigned a p4 and no one’s really on them with a sense of gravity and urgency.

**Comment by euphio** [comment]
> Yes guys please put web/desktop on hold a bit. We jumped on flutter due to its native-like performance promise and we got stuck in a nightmare. Lags, janky animations, flickering, emojis wrong rendering, text input issues and keyboard weird animation, lacks of platform fidelity for text input and no deadlines for fixes.
> 
> We had to postpone our launch waiting for improvements. But these severe issues are mostly assigned a p4 and no one’s really on them with a sense of gravity and urgency.

Agreed on this unfortunately. We have had to launch our maiden Flutter app with ads turned off (meaning no revenue stream). 

It pains me to have to pull the plug but we are now having to rewrite the application in Native code as we can’t afford to not earn revenue from Ads.

Its a shame as our technology cycle has now been:

Swift -> Flutter -> Swift & Kotlin.

**Comment by iosephmagno** [comment]
Can we also agree on the fact that senior people **with a product-man’s mind** should review task priority? Because several p1-p3 issues have been assigned a p4. If that mistake is made, we need to undo it.

Also, can we agree that “lack of platform fidelity for texts and text input” is always p1 for a mobile framework and that “performance issue” is always p1-p3, given the native-like performance promise of flutter?

**Comment by iosephmagno** [comment]
@euphio I know it is sad but you can temporarily pay double fee https://qonversion.io/

At Presence we would take a party if that were our issue with flutter. We are building the first flutter “premium” messaging app and that is almost impossible

**Comment by jmagman** [comment]
> iOS doesn't have a native support for displaying content in UIView in a texture, so a similar approach like Android is impossible on iOS.
> 
> We should revisit the iOS PlatformView's performance at some point to see if we can increase the performance within the current threading model for PlatformVIews.

Let's keep conversation focused on the performance issues related to platform view threading model on iOS.  Please avoid adding noise to GitHub issues.

**Comment by iosephmagno** [comment]
@jmagman @chinmaygarde can we know why this is p4? That part was on topic.

![20C162A3-E9B9-42E1-A169-DBE316B2E8A3](https://user-images.githubusercontent.com/83366073/188112747-db0aac1c-2347-47a8-85c7-26b275d19a46.jpeg)

**Comment by Hixie** [comment]
If anyone wants to have a conversation about our processes you are welcome to do so but please do so either on our Discord (ping me @Hixie and I'll be happy to engage with you), or e-mail me directly (ian@hixie.ch). As @jmagman says, the bug database is not the right venue for such conversations.

**Comment by 0xZOne** [comment]
I have a similar problem too. https://github.com/flutter/flutter/issues/114010

The difference is that on non-ProMotion devices (e.g., iphone8) it's smooth with barely perceptible jitter. However, there is noticeable jitter on the ProMotion device (e.g., iPhone13 Pro Max).

@cyanglaz Here it seems to be more than just platform view performance issues.

**Comment by 0xZOne** [comment]
> I have a similar problem too. #114010
> 
> The difference is that on non-ProMotion devices (e.g., iphone8) it's smooth with barely perceptible jitter. However, there is noticeable jitter on the ProMotion device (e.g., iPhone13 Pro Max).
> 
> @cyanglaz Here it seems to be more than just platform view performance issues.

## iPhone 8
<img width="1918" alt="iphone13_pro_max_2022-10-27 10 56 00" src="https://user-images.githubusercontent.com/26625149/198183114-c7334eda-3b38-4682-9234-fa79b59340ad.png">

## iPhone 13 Pro Max
<img width="1917" alt="iphone8_2022-10-27 11 12 13" src="https://user-images.githubusercontent.com/26625149/198183137-6a1dee08-f434-49bf-a8b8-f1274fff34e7.png">

In fact, non-ProMotion devices will also experience jitter, but not as visible to the naked eye as ProMotion devices.

**Comment by stuartmorgan** [comment]
Capturing from offline discussion: the two main potential sources of perf issues here are:
- thread merging, as discussed above, and
- frequent creation and destruction of platform views as they scroll through.

As a next step here, we should compare perf of the scroll-lots-of-native-views test in the original report to scrolling the same list with just widgets, but with a platform view persistently on the screen, to isolate just the thread-merging part, to see to what extent each contributes to the issue.

**Comment by cyanglaz** [comment]
Performance comparison between multiple scenarios with iPhone 13 pro, with Flutter dev tools:

1. **No PlatformView while scrolling:**

![no platform view dart](https://user-images.githubusercontent.com/3756895/200051152-1a5eccc1-fa7a-40c9-a91f-9250d12b8c9f.png)

2. **One PlatformView, with the PlatformView stationary and non-flutter widgets scrolling. (Thread merging)**

![one platform view](https://user-images.githubusercontent.com/3756895/200051434-a2885a48-c2f8-470a-92d4-8addd51e0739.png)

2* 5 PlatformViews, with the PlatformViews stationary

![5 PlatformView not scrolling](https://user-images.githubusercontent.com/3756895/200060004-c2577bd2-f832-4b4c-b3d1-cc6274f8edb7.png)

3. **One PlatformView, with the PlatformView constantly animating. **

![one platform view scrolling half out of the screen](https://user-images.githubusercontent.com/3756895/200051668-7e88ae14-2ea8-4bf7-abf7-06d0fed03c59.png)

4. **5 PlatformViews in the list, no creation destruction during scrolling (This also matches the max number of PlatformView on the screen in the next scenario**

![5 platform view , no alloc deallc](https://user-images.githubusercontent.com/3756895/200054151-adb3d844-8ec1-4efb-959f-5b9f927ecb1f.png)

4*. **30 PlatformViews in the list, no creation destruction during scrolling.**

![30 PlatformView animating](https://user-images.githubusercontent.com/3756895/200056936-3d823590-0f6d-467f-a32c-5d6a3c5b3adf.png)


5. **Multiple PlatformView scrolling (the scenario in this issue)**

![all platform view dart](https://user-images.githubusercontent.com/3756895/200051755-36e14347-4815-425d-8b5f-c8e4327c60da.png)

My observations: 
1. Thread merging does reduce the performance but not too much, about 2ms per frame. (comparing scenario 1 and 2) This is expected.
2. One PlatformView animating its position reduces performance further more, but insignificantly. (comparing scenario 2 and 3) This is expected too.
3. Animating the position of multiple PlatformViews with no creations and destructions reduces performance. (comparing scenario 3 and 4)
4. PlatformView creation and destruction doesn't seem to contribute to the performance reduction much. (comparing scenario 4 and 5)
5. The more the PlatformView animating, the worse the performance. (comparing 4 and 4*)
6. Number of the stationary PlatformView on the screen doesn't seem to affect performance (comparing 2 and 2*)

In summary, 2 things are happening that contributes the performance reduction.
1. **Thread merging.** This is expected and I'm not sure what we can do about it unless completely changing the threading model. The reduction is not much tho. I could not observe any janks when only 1 platform view is on the screen.
2. **Numbers of the PlatformView constantly animating.** It looks like the more PlatformView that are animating, the worse the screen jank is. There might be something we can do here.

The next step would be to find where in PlatformView's code takes long time during animation. My gut says it is either [ApplyMutator](https://github.com/flutter/engine/blob/main/shell/platform/darwin/ios/framework/Source/FlutterPlatformViews.mm#L406) is slow, or unnecessary overlays are created in [SubmitFrame](https://github.com/flutter/engine/blob/main/shell/platform/darwin/ios/framework/Source/FlutterPlatformViews.mm#L613-L676)

**Comment by cyanglaz** [comment]
I found that setting the maskView is one of the bottlenecks that lowering down the performance, [here](https://github.com/flutter/engine/blob/main/shell/platform/darwin/ios/framework/Source/FlutterPlatformViews.mm#L502)

I have tried removing all the clipping logic and just setting the maskView, the performance is still as bad.

**Plain mask view no clipping**
<img width="736" alt="Just mask view, no clip" src="https://user-images.githubusercontent.com/3756895/200394080-3bf360cb-6087-49c7-ba6f-a214f4f05156.png">

**No mask view**
<img width="759" alt="no mask view" src="https://user-images.githubusercontent.com/3756895/200394086-7e8130ac-7409-4ccc-acdf-8d3cde953669.png">

_Masking is the probably the best way that I could find to clip a UIView. I'm not sure if we can avoid masking if we want to support clipping._

One thing that we might be able to optimize is to pre-calculate the final clip path for the PlatformView, check if the PlatformView's frame is completely inside the final clip path, and do not set the mask view if that is the case.
I think this is the case for the example app, the clip rect in the example is basically the entire section below the navigation bar and all the PlatformViews never really need to be clipped. 

I will start prototype this and see if it increases performance. I believe (and hopefully) it will enhance performance for regular scrolling scenarios. Although it won't help if the App wants to do fancy clippings while scrolling. (For example, adding a clipRRect for each PlatformView in the ListView)

**Comment by cyanglaz** [comment]
The draft is ready at https://github.com/flutter/engine/pull/37434. I have tested the performance with flutter dev tools it seems to have a significant performance increase while using the example app.

It would be great If anyone else can verify if it fixes the visual janks for their app.

**Comment by 0xZOne** [comment]
@cyanglaz 

Frame stuttering in PlatformView is far less noticeable on non-ProMotion devices than on ProMotion devices.

It might be a not-bad optimization option if we could lower the refresh rate to 60Hz for pages containing PlatformView. :)

**Comment by 0xZOne** [comment]
> @cyanglaz
> 
> Frame stuttering in PlatformView is far less noticeable on non-ProMotion devices than on ProMotion devices.
> 
> It might be a not-bad optimization option if we could lower the refresh rate to 60Hz for pages containing PlatformView. :)

I mean rendering at a refresh rate depending on the context of what is being rendered. See https://github.com/flutter/flutter/issues/90675#issuecomment-971863161 for more details. 

@cyanglaz @iskakaushik  Do you guys have further plans? :)
