### ISSUE TITLE
NestedScroll in flutter view for add to app

### ISSUE THREAD

**Issue by reytum** [flutter/flutter#107418]
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. ... 
3. ... 

**Expected results:** While sliding the carousel slider wrapped in a flutter view within android recycler view, the recycler view should not scroll

<details>
I am using the carousel slider in my FlutterView in Android. In Android Native, I have a recycler view with vertical scrolling and different types of views. One of the view type is Banner for which I am using the FlutterView. Inside this flutter view I am rendering a Carousel slider from dart. Everything works fine except when I am scrolling through the carousel sliders images. When Sliding the images, the recycler view also scrolls unlike the native ViewPager which works well with nested scrolling. Is there a way to keep the scrolls in sync of both the native and flutter views?

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by maheshmnj** [comment]
Hi @reytum, Thanks for filing the issue. Please share a minimal and complete sample project along with the output of `flutter doctor -v`.

Thanks

**Comment by maheshmnj** [comment]
@reytum, could you please recheck the sample code? When I run the flutter app I see a circular progressindicator with a error in the console

```
: Warning: Operand of null-aware operation '??' has type 'String' which excludes null.
              Text("Profile Page : ${widget.usertype ?? ""}"),
                                            ^
Error running hot-restart: NoSuchMethodError: The getter 'assetPathsToEvict' was called on null.
Receiver: null
Tried calling: assetPathsToEvict
Exited

```

**Comment by ashish-bb-16** [comment]
Hi @maheshmnj, 
Kindly follow the below steps:

1) In the android project , open the settings.gradle file and replace [this](https://github.com/ashish-bb-16/FlutterTest/blob/040281457acf8efe75b22bb44b2852192edc807b/settings.gradle#L20) path with the path to bb_flutter project. In this case the bb_flutter project is present in the root of the repo.
2) Open bb_flutter from terminal and run `flutter pub get`
3) Run the command: `flutter create .`
4) Open the Android project in Android studio and you can run it from there.

**Comment by ashish-bb-16** [comment]
@maheshmnj Any update on this?

**Comment by maheshmnj** [comment]
Thanks for the reproducible steps @ashish-bb-16, I ran your code sample and it seems to work fine, When I scroll the carousel the vertical listview (Recycler view does not scroll). Let me know if I am missing anyything. 

https://user-images.githubusercontent.com/31410839/182211178-6810812b-ebc4-43fe-9aea-ccb481f03991.mov

<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.4 21F79 darwin-arm, locale en-IN)
    • Flutter version 3.0.5 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (5 days ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-32, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.67.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.44.0

[✓] Connected device (3 available)
    • sdk gphone arm64 (mobile) • emulator-5554 • android-arm64  • Android 11 (API 30) (emulator)
    • macOS (desktop)           • macos         • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)              • chrome        • web-javascript • Google Chrome 103.0.5060.114

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>
