### ISSUE TITLE
[proposed Label] go_router package -  The equivalent of pushAndRemoveUntil of navigator 1.0 in go_router?

### ISSUE THREAD

**Issue by abdimussa87** [flutter/flutter#107447]
What is the equivalent of pushAndRemoveUntil of navigator 1.0 in go_router?

**Comment by danagbemava-nc** [comment]
Hi @abdimussa87, there's no equivalent of this in go_router yet, but there's an issue tracking this feature request in https://github.com/flutter/flutter/issues/99112. 

Kindly follow up in the linked issue for updates. 

Closing from here as duplicate. 

Thank you

**Comment by abdimussa87** [comment]
Any alternative way of accomplishing this, as this seems like a fundamental use case
