### ISSUE TITLE
Flutter app works cant make network request while using wifi but works when on mobile data

### ISSUE THREAD

**Issue by haddiebakrie** [flutter/flutter#107405]
My app cant access internet on wifi network, I have added the internet permission & network state permission to the androidmanifest.xml file

**Comment by maheshmnj** [comment]
Hi @haddiebakrie, do other apps work on the same wifi network if yes then, Please share the error that you are receiving along with the output of `flutter doctor -v`.

**Comment by haddiebakrie** [comment]
Hello @maheshmnj, other apps works fine 

`[√] Flutter (Channel unknown, 2.10.5, on Microsoft Windows [Version 10.0.18363.1316], locale en-NG)
    • Flutter version 2.10.5 at C:\Users\Haddy\flutter
    • Upstream repository unknown
    • Framework revision 5464c5bac7 (3 months ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at C:\Users\Haddy\AppData\Local\Android\sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop for Windows (Visual Studio Build Tools 2019 16.11.10)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
    • Visual Studio Build Tools 2019 version 16.11.32126.315
    X Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop
      development with C++" workload, and include these components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK

[√] Android Studio (version 4.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.68.1)
    • VS Code at C:\Users\Haddy\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.34.0

[√] Connected device (4 available)
    • TECNO KG5k (mobile) • 07819371CH008109 • android-arm64  • Android 11 (API 30)
    • Windows (desktop)   • windows          • windows-x64    • Microsoft Windows [Version 10.0.18363.1316]
    • Chrome (web)        • chrome           • web-javascript • Google Chrome 103.0.5060.114
    • Edge (web)          • edge             • web-javascript • Microsoft Edge 103.0.1264.49

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.`

The error message i get is >>
Socket exception: OS error: No route to host, address api.braket.com, port 480

The address opens when using chrome on the same device

**Comment by maheshmnj** [comment]
thanks for the info @haddiebakrie, Can you also share the error you are receiving when making the network request? Additionally please try upgrading to the latest stable release `3.0.5` by running `flutter upgrade`
