### ISSUE TITLE
Runner quit unexpectedly when attempting to open Google Maps on iOS emulator in my app.

### ISSUE THREAD

**Issue by tlutgen** [flutter/flutter#107408]
I am running into issues when I try to open a specific screen on my app I am developing. When I open a screen with a Google Map plugin installed, my flutter inspector crashes and app crashes on my Simulator iOS 15.5. 

Here is my flutter doctor -v:
[✓] Flutter (Channel stable, 2.10.5, on macOS 12.4 21F79 darwin-arm, locale en-US)
    • Flutter version 2.10.5 at /Users/tristanlutgen/Developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (3 months ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/tristanlutgen/Library/Android/sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.66.2)
    • VS Code at /Users/tristanlutgen/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Connected device (3 available)
    • C302U (mobile)             • C032UQ91720231                       • android-arm64  • Android 10 (API 29)
    • iPhone 13 Pro Max (mobile) • 1247A984-18CC-49B2-8EB3-3D2AA01E31F8 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-5 (simulator)
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 100.0.4896.127

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

I have attached the error report log in text file:
[running_error_log.txt](https://github.com/flutter/flutter/files/9084837/running_error_log.txt)

**Comment by maheshmnj** [comment]
Hi @tlutgen, Thanks for filing the issue. Does the issue occur everytime when opening maps? Can you share the steps to reproduce the issue along with a minimal and complete sample code. Additionally please try upgrading to latest stable 3.0.4.
