### ISSUE TITLE
[Request] Scallop / Sunflower / Star Material 3 Shape

### ISSUE THREAD

**Issue by bernaferrari** [flutter/flutter#107442]
I think it would be nice for Flutter to adopt the Clover / Scallop / Sunflower shape from Android 12 / M3.

It could be a custom OutlinedBorder with custom math like this: https://stackoverflow.com/a/25840319
You probably have access to the Android 12 source code, so that could also be helpful.

Figma uses three pieces of information:

- pointCount (number of spikes, 5 for a star)
- innerRadius (%, if it should grow inside or outside)
- cornerRadius

This is a widget that feels heavy to use, but when you need it is really nice to have. I would love to see in the framework.

<img width="617" alt="image" src="https://user-images.githubusercontent.com/351125/178392619-c9eae4a7-a928-486f-88c6-0a548b5bb0b9.png">

![Frame 4](https://user-images.githubusercontent.com/351125/178391903-3795f3ca-7527-4099-8c3a-437b84079243.png)

**Comment by gspencergoog** [comment]
I'm not sure how to calculate an exact radius with the spline, though. I'd have to try it and see how it looks.

**Comment by gspencergoog** [comment]
The hardest part to implement here will be the lerp functions from the other border types.

**Comment by bernaferrari** [comment]
You wouldn't. BeveledRectangleBorder doesn't lerp.

**Comment by gspencergoog** [comment]
Well, it seems like I could figure out a lerp, but it would be weird: It could lerp to a circle (just increase the inner radius to 100%, and up the number of points), and from there to whatever shape we're lerping to. But I don't think we support multi-stage lerps, so I'd have to make one that did that.

**Comment by gspencergoog** [comment]
Here's a demo of what I have so far.  There are two constructors, one that makes polygons, and one that makes stars.

https://user-images.githubusercontent.com/8867023/179088336-0626f5e6-5211-4209-9e90-eb0bd7fd0935.mp4

**Comment by bernaferrari** [comment]
Well, you got surprisingly far already!

**Comment by bernaferrari** [comment]
When you add cornerRadius in Figma, the 'spike points' changes to be less, I just don't know how.

**Comment by gspencergoog** [comment]
No, I'm not really doing any kind of specific "radius", I'm just using the tension on the spline to curve it.  It does round the outer ones, just at a different curvature than the inner one.

What they're probably doing is moving back from the ends of the segments by the size of the radius, and then putting a circular arc on it.  They have to figure out the start and end angles for the circle, but that's not too hard.

I can see if I can find the source in Android code, but I can't do that until it's pushed to their open source site after release (I don't have access to it internally).

**Comment by bernaferrari** [comment]
> I can see if I can find the source in Android code, but I can't do that until it's pushed to their open source site after release (I don't have access to it internally).

I looked into the easter egg and... if I looked it right, surprisingly, it is an image. I don't know where else it is used in Android, since I use Samsung. But you can try your best here: https://cs.android.com/
