### ISSUE TITLE
BuildContext is meant to be used synchronously

### ISSUE THREAD

**Issue by ricnaaru** [flutter/flutter#107474]
In my opinon, this linter ([use_build_context_synchronously](https://dart-lang.github.io/linter/lints/use_build_context_synchronously.html)) is well intended but sometimes not practical. Consider the case below

```
class Foo {
  static Future<void> initialize(BuildContext context) async {
    await Foo1.initialize(context);
    await Foo2.initialize(context);
  }
}
class Foo1 {
  static Future<void> initialize(BuildContext context) async {
    //initialization stuffs
  }
}
class Foo2 {
  static Future<void> initialize(BuildContext context) async {
    //initialization stuffs that depend on Foo1 result
  }
}
```

How should I initialize those classes at startup for performance optimization? This linter pushes us to initialize all the classes inside the Stateful's State with the checking. So..

```
class SomeView extends StatefulWidget {
  const SomeView({Key? key}) : super(key: key);

  @override
  State<SomeView> createState() => _SomeViewState();
}

class _SomeViewState extends State<SomeView> {
  @override
  void initState() {
    super.initState();
    doInitialization();
  }

  Future<void> doInitialization() async {
    await Foo1.initialize(context);
    
    if (mounted) {
      await Foo2.initialize(context);
    }
  }

  @override
  Widget build(BuildContext context) {
    return Container();
  }
}
```

Personally, I think if BuildContext is meant to be used synchronously, it's better to have a `isMounted` method inside the BuildContext, so..

```
class Foo {
  static Future<void> initialize(BuildContext context) async {
    await Foo1.initialize(context);
    await Foo2.initialize(context);
  }
}
class Foo1 {
  static Future<void> initialize(BuildContext context) async {
    if (!context.isMounted) return;
    //initialization stuffs
  }
}
class Foo2 {
  static Future<void> initialize(BuildContext context) async {
    if (!context.isMounted) return;
    //initialization stuffs that depend on Foo1 result
  }
}
```

**Comment by Kavantix** [comment]
You can get the dependencies before the first await and then pass those into the initialize methods.

**Comment by iapicca** [comment]
@ricnaaru 
I think is very dangerous to use `context` asynchronously

```dart 
class Foo {
  static Future<void> initialize(BuildContext context) async {
    await Foo1.initialize(context); /// <= [YOU DON'T KNOW IF THIS `context` STILL EXIST!]
  }
}
```

**Comment by ricnaaru** [comment]
@Kavantix what if the first initialization is asynchronous and needs context, as well as the second initialization?

@iapicca yes, I am well aware of that, that's why my suggestion is to add a method check inside the BuildContext, whether the context is valid

**Comment by iapicca** [comment]
>  my suggestion is to add a method check inside the BuildContext, whether the context is valid
this would make the `context` *stateful*... please don't!

**Comment by danagbemava-nc** [comment]
Hi @ricnaaru, the devrel team released a video yesterday on this lint. See https://www.youtube.com/watch?v=bzWaMpD1LHY

Does it give you any hints as to how to go about your initialization?

**Comment by ricnaaru** [comment]
Yes, I noticed the video.. My intention is to create an API client base that requires context.. Why is that? so then I can handle the error handling internally in the API client base.. so if there is a connectivity error, without the caller wrapping it in a try catch, it will be handled internally (by API client base) by opening a dialog with a retry button on it.. more or less like this

```
class ApiClientBase {
  Future post(BuildContext context) async {
    try {
      final result = http.post(...);

      if (result.statusCode == 401) {
        /// handling refresh token
        if (token.isExpired) {
          /// show popup to say that the session is expired and please log in again
        } else {
          /// handle refresh token internally
        }
      } else if (result.statusCode == 200) {
        return result;
      }
    } on TimeoutException catch (e) {
      /// open dialog with a retry button
    } on SocketException catch (e) {
      /// open dialog with a retry button
    } catch (e) {
      /// on other error, display a toast message
      /// not to mention that there could be a localization needed here, which will also require BuildContext
    }
  }
}
```

so every method that calls this post request, will not be bothered to handle all the negative cases on http call..

**Comment by iapicca** [comment]
@ricnaaru 
paying attention to this part [3:37](https://youtu.be/bzWaMpD1LHY?t=217)
it's quite clear that the intended use is 
```dart
if(!mounted) return
```
#

```dart
class ApiClientBase {
  Future post(BuildContext context) async {
  // ...
       } catch (e) {
      /// on other error, display a toast message
      /// not to mention that there could be a localization needed here, which will also require BuildContext
    }
```

displaying a toast from an api client is wrong in so many ways (e.g.: [Separation of concerns](https://en.wikipedia.org/wiki/Separation_of_concerns))
this should be handled via state management

**Comment by ricnaaru** [comment]
I see, thanks for the discussion guys.. I will close it for now..
