### ISSUE TITLE
video refusing to play

### ISSUE THREAD

**Issue by wanoghoco** [flutter/flutter#107468]
when initialising about 20 videocontroller at a time to pre download or buffer the video to reduce latency on client Side while scrolling, some videos does not download or buffer. sometimes it download but does not show on the devices screen but it plays the sound

**Comment by iapicca** [comment]
> when initialising about 20 videocontroller at a time to pre download 

in my humble opinion this is a very questionable strategy
#
maybe the error [description](https://exoplayer.dev/debug-logging.html#media-tracks) in exoplayer page shed some light

> In this example, the player has selected four of the five available video tracks. The fifth video track is not selected because it exceeds the capabilities of the device, as indicated by supported=NO_EXCEEDS_CAPABILITIES. The player will adapt between the selected video tracks during playback. When the player adapts from one track to another, it’s logged in a line like the one below [...]

**Comment by ajosecueto** [comment]
@iapicca It is not about how many controllers you initialized... For example i preload the videos using cache + (previous - actual - next) and the video player throws the same exception... Some devices doesnt play andin other it crash.
