### ISSUE TITLE
Firebase plugins should be updated to Play Services 11.0.x

### ISSUE THREAD

**Issue by lukef** [flutter/flutter#10749]
Version 11 of play services introduce new features (generally) and the Firebase plugins should be updated so apps can take advantage.

**Comment by eseidelGoogle** [comment]
Per or conversation earlier in the week, @collinjackson can you take this on?  @lukef is making manual modifications for now.

**Comment by goderbauer** [comment]
I am working on this one now.

**Comment by kroikie** [comment]
@lukef

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/996. Any further collaboration will be done there.
