### ISSUE TITLE
InkSparkle effect color has wrong blue and green values

### ISSUE THREAD

**Issue by ko16a46** [flutter/flutter#107438]
Hello, 

I noticed an issue with the InkSparkle effect: it seems the green and blue values of the splash color are switched. This makes blue splash colors appear more green and green splash colors appear more blue. The red value of the color is unaffected.

I think the issue is caused by this [_colorToVector4() function](https://github.com/flutter/flutter/blob/15aa3bfda3658d1094ae50cc4c608fc94642405a/packages/flutter/lib/src/material/ink_sparkle.dart#L362) which is only used for the splash color. I notice that the values returned are in the order `red`, `blue`, `green`, `alpha`, but the ink sparkle shader uses `rgb`.

## Steps to Reproduce

1. Create an app with the following:
    - A theme with `useMaterial3` set to `true` and a splash color with either a high blue or a high green value (e.g. `Color(0xff0000ff)`) 
    - A widget that uses the sparkle effect (such as `IconButton()`)
2. Run the app on a platform that supports the sparkle effect (e.g. Android). This bug doesn't exist on the web for example.
3. Tap the `IconButton`

**Expected results:** A sparkle effect that matches the splash color

**Actual results:** A sparkle effect that has a splash color with the blue and green values switched

See screenshots attached at the bottom of the issue for further reference

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.from(
        colorScheme: const ColorScheme.light(),
        useMaterial3: true,
      ).copyWith(
        splashColor: const Color(0xff0000ff),
      ),
      home: const MyHome(),
    );
  }
}

class MyHome extends StatelessWidget {
  const MyHome({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            IconButton(
              onPressed: () {},
              icon: const Icon(Icons.home),
            ),
            const Padding(
              padding: EdgeInsets.only(top: 16.0, bottom: 8.0),
              child: Text('Splash Color:'),
            ),
            Container(
              width: 48.0,
              height: 16.0,
              color: Theme.of(context).splashColor,
            )
          ],
        ),
      ),
    );
  }
}
```

</details>

<details>
<summary>Screenshots of result (with different splash colors)</summary>

![Screenshot_20220711-174635](https://user-images.githubusercontent.com/100613422/178385614-1b865d7b-2bb5-4c2d-9850-9ee585232e4a.png)
![Screenshot_20220711-174654](https://user-images.githubusercontent.com/100613422/178385623-a69f4c98-9329-4a51-92d3-33df295da65b.png)
![Screenshot_20220711-174706](https://user-images.githubusercontent.com/100613422/178385635-da8e57a3-09e0-49e1-b1e4-abb18fed87f4.png)
![Screenshot_20220711-174724](https://user-images.githubusercontent.com/100613422/178385639-f705ed5a-59ec-4b92-8ce2-2ad406c0645d.png)

</details>

<details>
<summary>Flutter doctor logs</summary>

```
C:\Users\KO16A46\Projects\Scratch\sparkle_test> flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.0.4, on Microsoft Windows [Version 10.0.19042.1766], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.2.5)
[√] Android Studio (version 2021.1)
[√] VS Code (version 1.69.0)
[√] Connected device (4 available)
[√] HTTP Host Availability

• No issues found!
```

</details>

**Comment by timsneath** [comment]
Adding @clocksmith...

**Comment by danagbemava-nc** [comment]
Hi @ko16a46, there's an existing issue describing this bug in https://github.com/flutter/flutter/issues/104312. 

Kindly follow up in the linked issue for updates. 

Closing from here as duplicate. 

Thank you
