### ISSUE TITLE
Another exception was thrown: type 'String' is not a subtype of type 'int' of 'index'

### ISSUE THREAD

**Issue by shubhamdtalekar** [flutter/flutter#107460]
![image](https://user-images.githubusercontent.com/102503285/178476036-a4bdc77e-5251-4e55-97b8-221de21cda8d.png)

**Comment by shubhamdtalekar** [comment]
![image](https://user-images.githubusercontent.com/102503285/178475901-438f54df-615d-4a60-80a0-7f8300f2f7fa.png)

**Comment by shubhamdtalekar** [comment]
![image](https://user-images.githubusercontent.com/102503285/178475957-33a7b3f2-96f8-414d-b8a5-b86b2b3bd893.png)

**Comment by MohamedMubarak123** [comment]
Index should be only Integer value

**Comment by exaby73** [comment]
Hi @shubhamdtalekar, please provide a [minimal, reproducible example][1] and the output of `flutter doctor -v` as well as `flutter run -v`.

[1]: https://stackoverflow.com/help/minimal-reproducible-example
