### ISSUE TITLE
Copy/Cut/Paste icons greyed out on iPad keyboard

### ISSUE THREAD

**Issue by JagandeepBrar** [flutter/flutter#107443]
This issue is the exact same as https://github.com/flutter/flutter/issues/68514 which seems to have reappeared (Stable/3.0.4).

- If there is content in the clipboard, the paste icon is greyed out
- If content is currently highlighted in a TextField, the cut/copy icons are greyed out
- You can still long press the TextField to bring up the in-line contextual menu to cut/copy/paste successfully

```
[✓] Flutter (Channel stable, 3.0.4, on macOS 13.0 22A5295i darwin-x64, locale en-US)
    • Flutter version 3.0.4 at /Users/jagandeepbrar/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 85684f9300 (11 days ago), 2022-06-30 13:22:47 -0700
    • Engine revision 6ba2af10bb
    • Dart version 2.17.5
    • DevTools version 2.12.2
```

**Comment by danagbemava-nc** [comment]
Hi @JagandeepBrar, there's an existing issue that seeks to address this in https://github.com/flutter/flutter/issues/102940. 

Kindly follow up in the linked issue for updates. 

Closing from here as duplicate. 

Thank you
