### ISSUE TITLE
Implement SliverDecoration

### ISSUE THREAD

**Issue by Kavantix** [flutter/flutter#107498]
The SliverDecoration widget introduced in PR #107269 is not finished and has at least the following issues:

1. It doesnt work in horizontal scrollviews
2. It uses the paintExtent of the child which isn't always the correct value to use, take for instance this example when applying a rounde corner. The bottom two corners shouldn't be rounded yet. 
<img width="704" alt="image" src="https://user-images.githubusercontent.com/6243755/178582200-17b77dfd-e002-49d7-85eb-af47b3e39538.png">

3. Overlap and other advanced properties of slivers aren't accounted for.
4. The name is inconsistent with the box counterpart `DecoratedBox`, this should be called `DecoratedSliver`. The current name suggests its the configuration just like `BoxDecoration`

The correct behaviour should be the same as using a `SliverStack` from sliver_tools with a `SliverPositioned.fill` behind the second child sliver.

Minimal repro example I can add later if needed (dont have time right now).

### Proposed resolution steps

1. Revert #107269 ✅
2. Discuss here what sliver features the finished implementation should and shouldnt support
3. Create extensive widget tests for those cases and reimplement

@Piinks @jonahwilliams FYI

**Comment by jonahwilliams** [comment]
I think its likely that using the existing Decoration/BoxDecoration API won't work - in this case we'd need a new decoration class that would allow us to communicate the different sliver-y parts of the paint extent so that we could determine correctly where to use rounded corners

**Comment by Kavantix** [comment]
The way I’ve dealt with it so far in [SliverStack](https://github.com/Kavantix/sliver_tools/blob/86bbbaff58748f030d27c0d111aa8782ea778ef0/lib/src/rendering/sliver_stack.dart#L254) is to base the size on the `maxPaintExtent`. This however might cause painting far outside the visible region.
