### ISSUE TITLE
Dump debugging info into Android bug-reports

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#10746]
[https://developer.android.com/reference/android/app/Activity.html#dump(java.lang.String,%20java.io.FileDescriptor,%20java.io.PrintWriter,%20java.lang.String%5B%5D)](https://developer.android.com/reference/android/app/Activity.html#dump(java.lang.String,%20java.io.FileDescriptor,%20java.io.PrintWriter,%20java.lang.String%5B%5D))

This method gets automatically called by the Android framework for all started activities when `adb bugreport` is called.  It gives us a chance to dump any useful Flutter info (render tree, semantic tree, etc.) into the bug report.

**Comment by matthew-carroll** [comment]
Hi @tvolkert, did you have any thoughts on what we'd like to report here, or just something that might be useful?

**Comment by tvolkert** [comment]
It was just something that might be useful - such info would automatically be included in Android crash reports.

**Comment by matthew-carroll** [comment]
FYI @xster @GaryQian @jason-simmons for visibility

**Comment by tvolkert** [comment]
Dumping the current widget tree and/or render tree and/or semantic tree would be something I could see being of value.  Along with the Flutter version if possible.

**Comment by tvolkert** [comment]
Closing this since it's going to run into the same problem that saving instance state did - namely, that it's a synchronous API but would need to call into a platform channel (async API) to get the info it needs.  The instance state saving went through a ton of hoops to get around this, but that wouldn't be worth it here.
