### ISSUE TITLE
Uncaught ReferenceError: _flutter is not defined

### ISSUE THREAD

**Issue by mamaly12** [flutter/flutter#107448]
Hi everyone,

First, thank you for your efforts in producing this excellent framework. I have a problem with building and serving the Flutter demo app. with clicking the run button on Android Studio everything works fine and the app will run correctly:

![first ](https://user-images.githubusercontent.com/7683251/178432290-d80fb8ce-03b4-4eb5-9ec4-ea233a7a89bb.png)

but after I installed webdev:

![webdev](https://user-images.githubusercontent.com/7683251/178433031-2584065b-1937-4d70-8871-0f225bcc963b.png)

and added Cache/bin to my environment system:

![path](https://user-images.githubusercontent.com/7683251/178433780-08f35ecd-b502-46d8-8fcf-15840520d882.png)

I added build_runner, build_test and build_web_compilers to my pubspec.yml project:

![image](https://user-images.githubusercontent.com/7683251/178434530-83ab747b-e98b-4896-8ed7-a6fa382562f3.png)

I run the command webdev serve in the terminal and everything seems to be fine:

![terminal](https://user-images.githubusercontent.com/7683251/178434626-cc23d0d0-d04a-4849-aeb2-fbb62428ad97.png)

but when I open my browser I face this error that Flutter resources seem not loaded (flutter.js):

![error](https://user-images.githubusercontent.com/7683251/178434730-fe0c9cab-a96a-4beb-8883-284ab1dc9ef5.png)

I would be more than happy if you could help me how to resolve this problem

**Comment by exaby73** [comment]
Hello @mamaly12. Looks like the browser cannot find `flutter.js` which is what includes `_flutter`. Can you provide the following information:

- A [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)
- Output of `flutter doctor -v`

Thank you

**Comment by mamaly12** [comment]
Thank you @exaby73 for your reply.

1. Download the latest version of the Flutter SDK , unzip it, and add the "bin" folder to the user's path environment variable (Flutter 3.0.4)
2. Add Flutter plugin to Android Studio and restart it
3. In Android Studio: click on File -> New -> New Flutter Project 
   3.1. Set Flutter SDK path to the folder that is extracted from step 1
   3.2. Select "Application" for the project, Kotlin for android, swift for iOS, and also select "Web" for platforms
   
  ![image](https://user-images.githubusercontent.com/7683251/178462781-4fa6db21-e35e-4d2f-870f-5642f5b39b1d.png)
  
   3.3. Press finish button
4. Use "dart pub global activate webdev" command to install webdev  (2.7.10)
5. Add "C:\Users\Lenovo\AppData\Local\Pub\Cache" to the system's path environment variables
6. Add the following codes to pubspec.yml under the dev_dependencies

```
dev_dependencies:
    # ···
    build_runner: ^2.1.0
    build_test: ^2.1.0
    build_web_compilers: ^3.0.0
```
as mentioned here:
[https://dart.dev/tools/webdev](https://dart.dev/tools/webdev)

7. Run "dart pub get" in the terminal to get packages added from step 6

8. Run "webdev serve"

9. Follow the serving web link (http://127.0.0.1:8080/)

![image](https://user-images.githubusercontent.com/7683251/178465473-2a2f2f64-d4f0-403e-9f14-217a0b732550.png)

It will rise an error and show a blank page:
![image](https://user-images.githubusercontent.com/7683251/178465830-0fe76b82-bbcb-41ec-9f8f-d6317bf473a4.png)

I run "flutter doctor -v" and attached the result:

![flutter doctor v1](https://user-images.githubusercontent.com/7683251/178465104-f3e955bb-6e70-4902-8900-e4125afa293c.png)

![flutter doctor v2](https://user-images.githubusercontent.com/7683251/178465138-9f03b91b-f514-435c-8199-d37384e02221.png)


Please let me know if you have any questions or need any further information.

Thank you again for your attention

**Comment by exaby73** [comment]
Ahh I see the issue here. You need to run `flutter build web`, which is what generates the `flutter.js` file. You can serve the files located in `build/web` and you shouldn't get this problem

**Comment by exaby73** [comment]
You need serve the `build/web` folder and not the `web` folder at the root. Then it should work

**Comment by mamaly12** [comment]
Thank you so much @exaby73  for all your help, You're totally right. 
It does work for me with python.  I think "flutter run -d chrome" will also be useful if anyone wants to check the project with the Flutter command.

**Comment by exaby73** [comment]
Glad I was able to help. Though for future reference, if you need help with code, or issues that aren't a bug or feature request, please post on dedicated sites like StackOverflow as you'll be able to get better help there

**Comment by samuelnihoul** [comment]
I have the same error but `flutter build web` does not create the flutter.js for me. This happened it 2 apps of mine (all of mine I think)  :( Only one of the 2 apps is giving the error though, the other one works fine.

**Comment by samuelnihoul** [comment]
https://stackoverflow.com/questions/73058016/flutter-is-not-defined-error-in-index-js-firebase-deploy

https://stackoverflow.com/questions/73070958/is-flutter-build-web-supposed-to-output-a-file-called-flutter-js-because-it-d

Here are the two SO questions I asked that contain debug info.

**Comment by samuelnihoul** [comment]
OK nvm I understood my error!

**Comment by samuelnihoul** [comment]
I mixed up web and build/web.
