### ISSUE TITLE
[in-app-purchase][iOS] Promotional Offers in iOS not working 

### ISSUE THREAD

**Issue by crystalstorm** [flutter/flutter#107533]
There's an issue  ["Implementation of iOS Promotional Offers #92231"](https://github.com/flutter/flutter/issues/92231)
which is closed by a [pull request in plugins in-app-purchase](https://github.com/flutter/plugins/pull/4458)
but the implementation is not 100% complete and there is no way to get the promotional offer to work.

I've searched the net for example of using the newly added `SKPaymentDiscountWrapper` class (introduced in the above mentioned pull request) , but did not found anything. After trying to make it work on my own, I noticed several missing pieces which I will add in a new pull request.

**Comment by danagbemava-nc** [comment]
Hi @crystalstorm, for the sake of completeness, can you point out some of the missing pieces with the current implementation?

**Comment by crystalstorm** [comment]
Hi @danagbemava-nc , the current implementation lacks this:

1. In order to apply a promotional offer to a payment, one should pass `paymentDiscount` parameter (an object of class `SKPaymentDiscountWrapper`) in the constructor of `SKPaymentWrapper` object. In the comments of the `SKPaymentWrapper` it's said that a developer should not create instance of this object explicitly but rather use
`SKPaymentQueueWrapper.addPayment` method. The SKPaymentQueueWrapper's `addPayment` method though is not direcly exposed, but reachable only trough `InAppPurchaseStoreKitPlatform`'s overriden method of `buyNonConsumable` :

```
@override
  Future<bool> buyNonConsumable({required PurchaseParam purchaseParam}) async {
    await _skPaymentQueueWrapper.addPayment(SKPaymentWrapper(
        productIdentifier: purchaseParam.productDetails.id,
        quantity: purchaseParam is AppStorePurchaseParam ? purchaseParam.quantity : 1,
        applicationUsername: purchaseParam.applicationUserName,
        simulatesAskToBuyInSandbox: purchaseParam is AppStorePurchaseParam && purchaseParam.simulatesAskToBuyInSandbox,
        requestData: null));

    return true; // There's no error feedback from iOS here to return.
  }
```
But as visible in the current implementation, there is no `paymentDiscount` parameter in the constructor of `SKPaymentWrapper`.

My solution was to introduce second method `buyNonConsumableWithDiscount` whith a discount parameter:

```
static Future<bool> buyNonConsumableWithDiscount(
      {required PurchaseParam purchaseParam, SKPaymentDiscountWrapper? discount}) async {
    await _skPaymentQueueWrapper.addPayment(SKPaymentWrapper(
      productIdentifier: purchaseParam.productDetails.id,
      quantity: purchaseParam is AppStorePurchaseParam ? purchaseParam.quantity : 1,
      applicationUsername: purchaseParam.applicationUserName,
      simulatesAskToBuyInSandbox: purchaseParam is AppStorePurchaseParam && purchaseParam.simulatesAskToBuyInSandbox,
      requestData: null,
      paymentDiscount: discount,
    ));

    return true; // There's no error feedback from iOS here to return.
  }
```
 and put set it as static so it can be used like:
`InAppPurchaseStoreKitPlatform.buyNonConsumableWithDiscount(purchaseParam: purchaseParam, discount: discount);`

2. The `SKPaymentWrapper` class has `toMap()` method which is used to transfer it trough the method channel into the ObjectiveC side. But it does not export the `paymentDiscount` property. So even if you add it, on the ObjectiveC side of the plugin you will not see it.
Current implementation:
```
Map<String, dynamic> toMap() {
    return <String, dynamic>{
      'productIdentifier': productIdentifier,
      'applicationUsername': applicationUsername,
      'requestData': requestData,
      'quantity': quantity,
      'simulatesAskToBuyInSandbox': simulatesAskToBuyInSandbox
    };
  }
```
What I did is to add it to the exported map:
```
      'paymentDiscount': paymentDiscount?.toMap(),
```

3. When both above pieces are added the Promotional offers start to work. But then it will be an issue when the payment is not having a discount.
In the ObjectiveC side of the plugin in `FIAObjectTranslator.m` there is `getSKPaymentDiscountFromMap` method with check in the very first lines like this:
```
  if (!map || map.count <= 0) {
```
The received `map` argument though, is not nil, but an object of class NSNull, which is not having `.count` property and an unhandled exception will be thrown, crashing the app.
What I did is to add one more check there:
```
  if (!map || [map isKindOfClass:[NSNull class]] || map.count <= 0) {
```

That's it :)

**Comment by danagbemava-nc** [comment]
Hi @crystalstorm, thanks for the info. 

/cc @mvanbeusekom

**Comment by jmagman** [comment]
@crystalstorm you did a lot of research to track this down.  We do take pull requests 🙂

**Comment by crystalstorm** [comment]
@jmagman thanks :) I did a pull request too! :) it should be noted above! It is still missing tests and I wait for reviewers to reply on my comments... 
here it is [a link to it](https://github.com/flutter/plugins/pull/6099)
