### ISSUE TITLE
[Documentation] Typo in "Write your first flutter app" codelab

### ISSUE THREAD

**Issue by kcs-govindtank** [flutter/flutter#107535]
in the description text : 
"Create boilerplate code for a stateful widget.

It can go anywhere in the file outside of MyApp, but the solution places it at the bottom of the file. In lib/main.dart, position your cursor after all of the code, enter Return a couple times to start on a fresh line. In your IDE, start typing stful. The editor asks if you want to create a Stateful widget. Press Return to accept. The boilerplate code for two classes appears, and the cursor is positioned for you to enter the name of your stateless widget."

Problem : the last line suggesting that using 'stful' command, the cursor is positioned to enter "STATELESS WIDGET"
Solution : It should be "STATEFUL WIDGET" in the text, if we are using 'stful' command.

**Comment by danagbemava-nc** [comment]
Hi @kcs-govindtank, where is this text copied from?

**Comment by erdzan12** [comment]
https://github.com/flutter/flutter/issues/69504

**Comment by cofirazak** [comment]
This issue should be closed, as it was fixed here: https://github.com/flutter/flutter/issues/69504#issuecomment-801608551

**Comment by domesticmouse** [comment]
Googlers: fix for reals this time in cl/463548410

**Comment by cofirazak** [comment]
Went to this [codelab](https://codelabs.developers.google.com/codelabs/first-flutter-app-pt1#4), see the typo still there:

<img width="747" alt="image" src="https://user-images.githubusercontent.com/2613578/182030375-4c04fe8f-42f4-4c31-96c3-63d7d2873024.png">

**Comment by codewithkushagra** [comment]
Is this issue still open, I check the site it still shows stateless widget, If it's open can I work on it?

**Comment by domesticmouse** [comment]
@codewithkushagra and @cofirazak the fix for this issue is waitiing on @craiglabenz to land an inflight CL. This is Google internal, not open source.

**Comment by domesticmouse** [comment]
This should now be fixed. Sorry for the delay!

**Comment by kcs-govindtank** [comment]
@domesticmouse thanks man, I see the correct word now.
