### ISSUE TITLE
PhaseScriptExecution failed with a nonzero exit code 

### ISSUE THREAD

**Issue by NatrajOptisol** [flutter/flutter#107516]
Hello,

Im Running flutter build iOS and flutter run on Xcode, android studio and terminal and Im getting this error not sure why, we have been weeks trying different things and nothing is working.

I was expecting that it runs but its doesn't.

MacBook Pro (14-inch, M1, 2022)
Xcode version 13.3

Xcode:
Command PhaseScriptExecution failed with a nonzero exit code.
I have added the attachment for relating this issue. 

Thanks in advance!

<details>
<summary>flutter doctor</summary>

```
[✓] Flutter (Channel stable, 2.10.5, on macOS 12.1 21C52 darwin-arm, locale en-IN)
    • Flutter version 2.10.5 at /Users/mac-obs-51/flutter2.10.5
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (3 months ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/mac-obs-51/Library/Android/sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] IntelliJ IDEA Community Edition (version 2021.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 66.0.3
    • Dart plugin version 213.7306

[✓] VS Code (version 1.69.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.44.0

[✓] Connected device (3 available)
    • Android SDK built for arm64 (mobile) • emulator-5554 • android-arm64  • Android 8.0.0 (API 26) (emulator)
    • macOS (desktop)                      • macos         • darwin-arm64   • macOS 12.1 21C52 darwin-arm
    • Chrome (web)                         • chrome        • web-javascript • Google Chrome 103.0.5060.114

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

<details>
<summary>screenshots</summary>

<img width="1396" alt="attachment-1" src="https://user-images.githubusercontent.com/91648574/178663049-f7647829-2693-4a94-8061-8d1efcc3b268.png">
<img width="1396" alt="attachment-2" src="https://user-images.githubusercontent.com/91648574/178663115-f4a0e0c6-46cf-494c-a6c1-ae6967341ae4.png">
0

</details>

**Comment by danagbemava-nc** [comment]
Hi @NatrajOptisol, I have a couple of questions

- Do you experience this issue when running the default counter app?
- Are you running on a physical ios device or on the ios simulator?
- Can you try upgrading to the latest version of stable to see if you still experience this issue?

**Comment by NatrajOptisol** [comment]
Hi @danagbemava-nc 
* Counter app is working 
* Checked with real time device
* Latest version also have same issue

**Comment by danagbemava-nc** [comment]
Hi @NatrajOptisol, please provide the full output of `flutter run -v`. The output may be huge so kindly put it into a .txt file and attach it here. 

Please also provide the following 
- Your pubspec.yaml & pubspec.lock
- Your podfile & podfile.lock 

Thank you
