### ISSUE TITLE
DisplayList should omit any NOP rendering operations

### ISSUE THREAD

**Issue by flar** [flutter/flutter#107580]
A simple example would be any rendering operation that has a blend mode of SrcOver and an alpha of 0 would not be rendered. Another simple example is any rendering that happens under a singular matrix (though we might want to consider whether "hairline" strokes which are supposed to never disappear regardless of scale should be rendered).

**Comment by JsouLiang** [comment]
> A simple example would be any rendering operation that has a blend mode of SrcOver and an alpha of 0 would not be rendered.

I found If I set create a Opacity Widget and set the alpha == 0, the framework doesn't create any layer.

**Comment by flar** [comment]
> > A simple example would be any rendering operation that has a blend mode of SrcOver and an alpha of 0 would not be rendered.
> 
> I found If I set create a Opacity Widget and set the alpha == 0, the framework doesn't create any layer.

Correct, but that is controversial because if it is animating then it disrupted the tree and the cache by doing so. There was a PR somewhere to only do that if the animation had ended, but I forget what happened to it.

DisplayList has no such optimization, though.

**Comment by ColdPaleLight** [comment]
@flar 

It looks like we have two optional timings to do this:

1. When the DisplayListBuilder records the Op, if we find that the Op does not have any operation, then we push a NoDrawOp into the stream (Push a NoDrawOp instead of directly ignoring it is to align with the SkPicture in the number of Ops)

2. Do it when the content is actually drawn, if we're using the Skia backend, it looks like Skia already does this. But Impeller doesn't, so we can add this capability to Impeller's backend.

Please let me know which of these two options do you prefer?

**Comment by flar** [comment]
The problem with overwriting the stream with a "NoDraw" op is that some of the ops have data that needs to be disposed during the destructor so the "NoDraw" overwrite would not be aware of that situation. These records aren't necessarily tagged in the "ops.h" file, but rather discovered dyamically at runtime using a test for a trivial destructor in the DisposeOps switch statement: https://github.com/flutter/engine/blob/9f35eb10b558bd2d58cdaa83fa68a1313966d3fc/display_list/display_list.cc#L108

**Comment by flar** [comment]
Why can't we just omit the op if we can statically determine that it is a NOP?

One thing that might temper our prediction of a NOP rendering operation is if we dispatch these records with an inherited values due to peephole optimization. Consider an op that has an opaque color and a blend mode where opaque colors are NOP. Normally that op would NOP, but if the DL is being dispatched with an inherited opacity, then the opaque color would be modulated to non-opaque and no longer be a NOP.

Currently we only manage inherited opacity in the CanvasDispatcher, but we should be handling it for cases like Impeller as well eventually. Also, we should be expanding the inherited attributes to more than just opacity. Will the op be a NOP if there is an inherited ColorFilter not currently in evidence?

Perhaps most decisions about NOP really should be left to dispatch time for this reason.

Some things that might make it statically always a NOP would be if the transform is singular or the clip is an empty rectangle, though. I don't think there can be any inherited state that would "contradict" that NOP assessment.

**Comment by ColdPaleLight** [comment]
@flar 
So to sum up, we have the following conclusions: (please correct me if something wrong)

1. If we can statically determine that the op is a NOP (for example:  transform is singular or the clip is an empty rectangle), we can just omit it. (But looks like we should push a NOP to stream to fix the unittests? )

3. For other NOPs that cannot be determined directly in DisplayListBuilder, we can omit it in the dispatch phase. I personally think we can create a subclass of `flutter::Dispatcher`, for example named `flutter::OptimizeDispatcher`, and do NOP optimization in it. In the end, we can let the necessary dispatchers such as `impeller::DisplayListDispatcher` inherit this subclass.

**Comment by ColdPaleLight** [comment]
@flar 
If the PR https://github.com/flutter/engine/pull/34365 landed, we could do some better optimizations, as you mentioned in the issue https://github.com/flutter/flutter/issues/100172:
> eventually we will want to take advantage of information uncovered in the bounds computations to make the DisplayLists more efficient - for instance, detecting non-trivially empty operations

**Comment by flar** [comment]
> @flar So to sum up, we have the following conclusions: (please correct me if something wrong)
> 
> 1. If we can statically determine that the op is a NOP (for example:  transform is singular or the clip is an empty rectangle), we can just omit it. (But looks like we should push a NOP to stream to fix the unittests? )

No, do not push a NOP to the stream. No test should force you to push a NOP. If the test was expecting an op in the count, then the test was wrong. Please identify which tests were causing this op count discrepancy.

**Comment by flar** [comment]
Fixed by https://github.com/flutter/engine/pull/43698
