### ISSUE TITLE
Whenever I try to run the application I get this Error !

### ISSUE THREAD

**Issue by omarakl** [flutter/flutter#107523]
FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\hp\AndroidStudioProjects\megabee\android\app\build.gradle' line: 26

* What went wrong:
A problem occurred evaluating project ':app'.
> Could not load compiled classes for script 'C:\flutter2\flutter\packages\flutter_tools\gradle\flutter.gradle' from cache.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 11s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by omarakl** [comment]
output of  "flutter doctor -v" :


[√] Flutter (Channel stable, 3.0.4, on Microsoft Windows [Version 10.0.19043.1766], locale en-US)
    • Flutter version 3.0.4 at C:\flutter2\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 85684f9300 (13 days ago), 2022-06-30 13:22:47 -0700
    • Engine revision 6ba2af10bb
    • Dart version 2.17.5
    • DevTools version 2.12.2

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\hp\.android
    • Platform android-33, build-tools 33.0.0
    X Android SDK file not found: C:\Users\hp\.android\platforms\android-33\android.jar.
    • Try re-installing or updating your Android SDK,
      visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] VS Code
    • VS Code at C:\Users\hp\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19043.1766]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 103.0.5060.114
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 103.0.1264.49

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.




------------------------------------------------------



output of "flutter run -v" :

[ +433 ms] executing: [C:\flutter2\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[+2814 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +4 ms] 85684f9300908116a78138ea4c6036c35c9a1236
[   +4 ms] executing: [C:\flutter2\flutter/] git tag --points-at 85684f9300908116a78138ea4c6036c35c9a1236
[ +246 ms] Exit code 0 from: git tag --points-at 85684f9300908116a78138ea4c6036c35c9a1236
[   +3 ms] 3.0.4
[  +46 ms] executing: [C:\flutter2\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[ +232 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +3 ms] origin/stable
[   +2 ms] executing: [C:\flutter2\flutter/] git ls-remote --get-url origin
[ +205 ms] Exit code 0 from: git ls-remote --get-url origin
[   +3 ms] https://github.com/flutter/flutter.git
[+1911 ms] executing: [C:\flutter2\flutter/] git rev-parse --abbrev-ref HEAD
[ +219 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +3 ms] stable
[ +376 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +4 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +20 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +317 ms] executing: C:\Users\hp\.android\platform-tools\adb.exe devices -l
[ +303 ms] List of devices attached
[  +36 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[  +88 ms] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +406 ms] No supported devices connected.
[ +162 ms] The following devices were found, but are not supported by this project:
                    Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19043.1766]
                    Chrome (web)      • chrome  • web-javascript • Google Chrome 103.0.5060.114
                    Edge (web)        • edge    • web-javascript • Microsoft Edge 103.0.1264.49
                    If you would like your app to run on web or windows, consider running `flutter create .` to generate projects for these platforms.
                    
[  +78 ms] "flutter run" took 1,544ms.
[ +133 ms] 
                    #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
                    #1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:484:7)
                    <asynchronous suspension>
                    #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1298:5)
                    <asynchronous suspension>
                    #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1183:27)
                    <asynchronous suspension>
                    #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
                    <asynchronous suspension>
                    #5      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
                    <asynchronous suspension>
                    #6      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
                    <asynchronous suspension>
                    #7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
                    <asynchronous suspension>
                    #8      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
                    <asynchronous suspension>
                    #9      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
                    <asynchronous suspension>
                    #10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
                    <asynchronous suspension>
                    #11     main (package:flutter_tools/executable.dart:94:3)
                    <asynchronous suspension>
                    
                    
[ +589 ms] ensureAnalyticsSent: 568ms
[   +8 ms] Running shutdown hooks
[   +2 ms] Shutdown hooks complete
[  +16 ms] exiting with code 1

**Comment by exaby73** [comment]
Could you share the output of running `flutter run -v`?

**Comment by omarakl** [comment]
output of "flutter run -v" :


[ +455 ms] executing: [C:\flutter2\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[+3074 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +3 ms] 85684f9300908116a78138ea4c6036c35c9a1236
[   +4 ms] executing: [C:\flutter2\flutter/] git tag --points-at 85684f9300908116a78138ea4c6036c35c9a1236
[ +272 ms] Exit code 0 from: git tag --points-at 85684f9300908116a78138ea4c6036c35c9a1236
[   +2 ms] 3.0.4
[  +49 ms] executing: [C:\flutter2\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[ +237 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +2 ms] origin/stable
[   +1 ms] executing: [C:\flutter2\flutter/] git ls-remote --get-url origin
[ +206 ms] Exit code 0 from: git ls-remote --get-url origin
[   +2 ms] https://github.com/flutter/flutter.git
[+1899 ms] executing: [C:\flutter2\flutter/] git rev-parse --abbrev-ref HEAD
[ +208 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +2 ms] stable
[ +423 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +20 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +333 ms] executing: C:\Users\hp\.android\platform-tools\adb.exe devices -l
[ +293 ms] List of devices attached
                    9EHNW19C17001880       device product:JAT-L29HW model:JAT_L29 device:HWJAT-M transport_id:1
[  +45 ms] C:\Users\hp\.android\platform-tools\adb.exe -s 9EHNW19C17001880 shell getprop
[ +424 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[  +51 ms] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[   +8 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +785 ms] Skipping pub get: version match.
[ +228 ms] Found plugin file_picker at C:\flutter2\flutter\.pub-cache\hosted\pub.dartlang.org\file_picker-1.10.0\
[  +42 ms] Found plugin flutter_inappwebview at C:\flutter2\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_inappwebview-5.4.3+7\
[ +137 ms] Found plugin flutter_plugin_android_lifecycle at C:\flutter2\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_plugin_android_lifecycle-1.0.11\
[  +75 ms] Found plugin path_provider at C:\flutter2\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-2.0.11\
[  +12 ms] Found plugin path_provider_android at C:\flutter2\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_android-2.0.16\
[  +14 ms] Found plugin path_provider_ios at C:\flutter2\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_ios-2.0.10\
[  +26 ms] Found plugin path_provider_linux at C:\flutter2\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_linux-2.1.7\
[  +16 ms] Found plugin path_provider_macos at C:\flutter2\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_macos-2.0.6\
[  +28 ms] Found plugin path_provider_windows at C:\flutter2\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_windows-2.1.0\
[  +51 ms] Found plugin share at C:\flutter2\flutter\.pub-cache\hosted\pub.dartlang.org\share-0.6.4+5\
[  +12 ms] Found plugin share_plus at C:\flutter2\flutter\.pub-cache\hosted\pub.dartlang.org\share_plus-4.0.10\
[  +23 ms] Found plugin share_plus_linux at C:\flutter2\flutter\.pub-cache\hosted\pub.dartlang.org\share_plus_linux-3.0.0\
[  +10 ms] Found plugin share_plus_macos at C:\flutter2\flutter\.pub-cache\hosted\pub.dartlang.org\share_plus_macos-3.0.1\
[  +19 ms] Found plugin share_plus_web at C:\flutter2\flutter\.pub-cache\hosted\pub.dartlang.org\share_plus_web-3.0.1\
[  +13 ms] Found plugin share_plus_windows at C:\flutter2\flutter\.pub-cache\hosted\pub.dartlang.org\share_plus_windows-3.0.1\
[  +25 ms] Found plugin sqflite at C:\flutter2\flutter\.pub-cache\hosted\pub.dartlang.org\sqflite-2.0.3\
[  +75 ms] Found plugin url_launcher at C:\flutter2\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher-6.1.4\
[  +20 ms] Found plugin url_launcher_android at C:\flutter2\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_android-6.0.17\
[  +10 ms] Found plugin url_launcher_ios at C:\flutter2\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_ios-6.0.17\
[   +9 ms] Found plugin url_launcher_linux at C:\flutter2\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_linux-3.0.1\
[  +20 ms] Found plugin url_launcher_macos at C:\flutter2\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_macos-3.0.1\
[  +16 ms] Found plugin url_launcher_web at C:\flutter2\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_web-2.0.12\
[  +12 ms] Found plugin url_launcher_windows at C:\flutter2\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_windows-3.0.1\
[  +23 ms] Found plugin webview_flutter at C:\flutter2\flutter\.pub-cache\hosted\pub.dartlang.org\webview_flutter-3.0.4\
[   +9 ms] Found plugin webview_flutter_android at C:\flutter2\flutter\.pub-cache\hosted\pub.dartlang.org\webview_flutter_android-2.8.14\
[  +11 ms] Found plugin webview_flutter_wkwebview at C:\flutter2\flutter\.pub-cache\hosted\pub.dartlang.org\webview_flutter_wkwebview-2.8.1\
[ +281 ms] Found plugin file_picker at C:\flutter2\flutter\.pub-cache\hosted\pub.dartlang.org\file_picker-1.10.0\
[  +15 ms] Found plugin flutter_inappwebview at C:\flutter2\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_inappwebview-5.4.3+7\
[   +9 ms] Found plugin flutter_plugin_android_lifecycle at C:\flutter2\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_plugin_android_lifecycle-1.0.11\
[  +59 ms] Found plugin path_provider at C:\flutter2\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-2.0.11\
[   +9 ms] Found plugin path_provider_android at C:\flutter2\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_android-2.0.16\
[   +6 ms] Found plugin path_provider_ios at C:\flutter2\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_ios-2.0.10\
[   +6 ms] Found plugin path_provider_linux at C:\flutter2\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_linux-2.1.7\
[   +7 ms] Found plugin path_provider_macos at C:\flutter2\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_macos-2.0.6\
[   +9 ms] Found plugin path_provider_windows at C:\flutter2\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_windows-2.1.0\
[  +20 ms] Found plugin share at C:\flutter2\flutter\.pub-cache\hosted\pub.dartlang.org\share-0.6.4+5\
[   +7 ms] Found plugin share_plus at C:\flutter2\flutter\.pub-cache\hosted\pub.dartlang.org\share_plus-4.0.10\
[   +7 ms] Found plugin share_plus_linux at C:\flutter2\flutter\.pub-cache\hosted\pub.dartlang.org\share_plus_linux-3.0.0\
[   +6 ms] Found plugin share_plus_macos at C:\flutter2\flutter\.pub-cache\hosted\pub.dartlang.org\share_plus_macos-3.0.1\
[  +11 ms] Found plugin share_plus_web at C:\flutter2\flutter\.pub-cache\hosted\pub.dartlang.org\share_plus_web-3.0.1\
[   +8 ms] Found plugin share_plus_windows at C:\flutter2\flutter\.pub-cache\hosted\pub.dartlang.org\share_plus_windows-3.0.1\
[  +11 ms] Found plugin sqflite at C:\flutter2\flutter\.pub-cache\hosted\pub.dartlang.org\sqflite-2.0.3\
[  +32 ms] Found plugin url_launcher at C:\flutter2\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher-6.1.4\
[   +8 ms] Found plugin url_launcher_android at C:\flutter2\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_android-6.0.17\
[   +6 ms] Found plugin url_launcher_ios at C:\flutter2\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_ios-6.0.17\
[   +8 ms] Found plugin url_launcher_linux at C:\flutter2\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_linux-3.0.1\
[   +8 ms] Found plugin url_launcher_macos at C:\flutter2\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_macos-3.0.1\
[   +8 ms] Found plugin url_launcher_web at C:\flutter2\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_web-2.0.12\
[   +6 ms] Found plugin url_launcher_windows at C:\flutter2\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_windows-3.0.1\
[  +11 ms] Found plugin webview_flutter at C:\flutter2\flutter\.pub-cache\hosted\pub.dartlang.org\webview_flutter-3.0.4\
[   +7 ms] Found plugin webview_flutter_android at C:\flutter2\flutter\.pub-cache\hosted\pub.dartlang.org\webview_flutter_android-2.8.14\
[   +8 ms] Found plugin webview_flutter_wkwebview at C:\flutter2\flutter\.pub-cache\hosted\pub.dartlang.org\webview_flutter_wkwebview-2.8.1\
[ +143 ms] Generating C:\Users\hp\AndroidStudioProjects\megabee\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[ +348 ms] ro.hardware = mt6765
[   +3 ms] ro.build.characteristics = default
[ +235 ms] Initializing file store
[  +66 ms] Skipping target: gen_localizations
[  +28 ms] gen_dart_plugin_registrant: Starting due to {InvalidatedReasonKind.inputChanged: The following inputs have updated contents:
C:\Users\hp\AndroidStudioProjects\megabee\.dart_tool\package_config_subset,C:\Users\hp\AndroidStudioProjects\megabee\.dart_tool\flutter_build\dart_plugin_registran
t.dart}
[ +102 ms] Found plugin file_picker at C:\flutter2\flutter\.pub-cache\hosted\pub.dartlang.org\file_picker-1.10.0\
[  +12 ms] Found plugin flutter_inappwebview at C:\flutter2\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_inappwebview-5.4.3+7\
[   +9 ms] Found plugin flutter_plugin_android_lifecycle at C:\flutter2\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_plugin_android_lifecycle-1.0.11\
[  +32 ms] Found plugin path_provider at C:\flutter2\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-2.0.11\
[   +6 ms] Found plugin path_provider_android at C:\flutter2\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_android-2.0.16\
[   +5 ms] Found plugin path_provider_ios at C:\flutter2\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_ios-2.0.10\
[   +5 ms] Found plugin path_provider_linux at C:\flutter2\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_linux-2.1.7\
[   +4 ms] Found plugin path_provider_macos at C:\flutter2\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_macos-2.0.6\
[   +7 ms] Found plugin path_provider_windows at C:\flutter2\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_windows-2.1.0\
[  +14 ms] Found plugin share at C:\flutter2\flutter\.pub-cache\hosted\pub.dartlang.org\share-0.6.4+5\
[   +5 ms] Found plugin share_plus at C:\flutter2\flutter\.pub-cache\hosted\pub.dartlang.org\share_plus-4.0.10\
[   +5 ms] Found plugin share_plus_linux at C:\flutter2\flutter\.pub-cache\hosted\pub.dartlang.org\share_plus_linux-3.0.0\
[   +5 ms] Found plugin share_plus_macos at C:\flutter2\flutter\.pub-cache\hosted\pub.dartlang.org\share_plus_macos-3.0.1\
[   +7 ms] Found plugin share_plus_web at C:\flutter2\flutter\.pub-cache\hosted\pub.dartlang.org\share_plus_web-3.0.1\
[   +4 ms] Found plugin share_plus_windows at C:\flutter2\flutter\.pub-cache\hosted\pub.dartlang.org\share_plus_windows-3.0.1\
[   +9 ms] Found plugin sqflite at C:\flutter2\flutter\.pub-cache\hosted\pub.dartlang.org\sqflite-2.0.3\
[  +21 ms] Found plugin url_launcher at C:\flutter2\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher-6.1.4\
[   +8 ms] Found plugin url_launcher_android at C:\flutter2\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_android-6.0.17\
[   +5 ms] Found plugin url_launcher_ios at C:\flutter2\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_ios-6.0.17\
[   +6 ms] Found plugin url_launcher_linux at C:\flutter2\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_linux-3.0.1\
[   +8 ms] Found plugin url_launcher_macos at C:\flutter2\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_macos-3.0.1\
[   +6 ms] Found plugin url_launcher_web at C:\flutter2\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_web-2.0.12\
[   +5 ms] Found plugin url_launcher_windows at C:\flutter2\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_windows-3.0.1\
[   +9 ms] Found plugin webview_flutter at C:\flutter2\flutter\.pub-cache\hosted\pub.dartlang.org\webview_flutter-3.0.4\
[   +6 ms] Found plugin webview_flutter_android at C:\flutter2\flutter\.pub-cache\hosted\pub.dartlang.org\webview_flutter_android-2.8.14\
[   +7 ms] Found plugin webview_flutter_wkwebview at C:\flutter2\flutter\.pub-cache\hosted\pub.dartlang.org\webview_flutter_wkwebview-2.8.1\
[  +43 ms] gen_dart_plugin_registrant: Complete
[  +10 ms] Skipping target: _composite
[  +12 ms] complete
[  +33 ms] Launching lib\main.dart on JAT L29 in debug mode...
[  +32 ms] C:\flutter2\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev
C:\flutter2\flutter\bin\cache\dart-sdk\bin\snapshots\frontend_server.dart.snapshot --sdk-root
C:\flutter2\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names
--experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true --output-dill
C:\Users\hp\AppData\Local\Temp\flutter_tools.a0744bb3\flutter_tool.910889bb\app.dill --packages
C:\Users\hp\AndroidStudioProjects\megabee\.dart_tool\package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation
--filesystem-scheme org-dartlang-root --initialize-from-dill build\c075001b96339384a97db4862b8ab8db.cache.dill.track.dill --source
C:\Users\hp\AndroidStudioProjects\megabee\.dart_tool\flutter_build\dart_plugin_registrant.dart --source package:flutter/src/dart_plugin_registrant.dart
-Dflutter.dart_plugin_registrant=file:///C:/Users/hp/AndroidStudioProjects/megabee/.dart_tool/flutter_build/dart_plugin_registrant.dart
--enable-experiment=alternative-invalidation-strategy
[  +82 ms] executing: C:\Users\hp\.android\platform-tools\adb.exe -s 9EHNW19C17001880 shell -x logcat -v time -t 1
[  +80 ms] <- compile package:megabee/main.dart
[ +426 ms] --------- beginning of main
                    07-14 00:13:35.234 I/HwMobileSignalController(0)( 1665): subId:0 phoneType:1 networktype:15 targetClass:2 masterLevel:5 slaveLevel:-1
[  +52 ms] executing: C:\Users\hp\.android\platform-tools\adb.exe version
[ +333 ms] Android Debug Bridge version 1.0.41
                    Version 33.0.2-8557947
                    Installed as C:\Users\hp\.android\platform-tools\adb.exe
[  +10 ms] executing: C:\Users\hp\.android\platform-tools\adb.exe start-server
[ +175 ms] Building APK
[ +128 ms] Running Gradle task 'assembleDebug'...
[  +25 ms] Using gradle from C:\Users\hp\AndroidStudioProjects\megabee\android\gradlew.bat.
[  +60 ms] executing: [C:\Users\hp\AndroidStudioProjects\megabee\android/] C:\Users\hp\AndroidStudioProjects\megabee\android\gradlew.bat -Pverbose=true
-Ptarget-platform=android-arm -Ptarget=C:\Users\hp\AndroidStudioProjects\megabee\lib\main.dart -Pbase-application-name=android.app.Application
-Pdart-defines=RkxVVFRFUl9XRUJfQVVUT19ERVRFQ1Q9dHJ1ZQ== -Pdart-obfuscation=false -Ptrack-widget-creation=true -Ptree-shake-icons=false
-Pfilesystem-scheme=org-dartlang-root assembleDebug
[+3310 ms] Welcome to Gradle 7.4!
[   +5 ms] Here are the highlights of this release:
[   +2 ms]  - Aggregated test and JaCoCo reports
[   +1 ms]  - Marking additional test source directories as tests in IntelliJ
[   +1 ms]  - Support for Adoptium JDKs in Java toolchains
[   +1 ms] For more details see https://docs.gradle.org/7.4/release-notes.html
[+3461 ms] Starting a Gradle Daemon, 1 incompatible and 1 stopped Daemons could not be reused, use --status for details
[+38401 ms] FAILURE: Build failed with an exception.
[  +21 ms] * Where:
[   +2 ms] Build file 'C:\Users\hp\AndroidStudioProjects\megabee\android\app\build.gradle' line: 24
[   +2 ms] * What went wrong:
[   +2 ms] A problem occurred evaluating project ':app'.
[   +5 ms] > Failed to apply plugin 'com.android.internal.application'.
[   +2 ms]    > Android Gradle plugin requires Java 11 to run. You are currently using Java 1.8.
[   +2 ms]      You can try some of the following options:
[   +2 ms]        - changing the IDE settings.
[   +2 ms]        - changing the JAVA_HOME environment variable.
[   +2 ms]        - changing `org.gradle.java.home` in `gradle.properties`.
[   +8 ms] * Try:
[   +2 ms] > Run with --stacktrace option to get the stack trace.
[   +9 ms] > Run with --info or --debug option to get more log output.
[   +4 ms] > Run with --scan to get full insights.
[   +2 ms] * Get more help at https://help.gradle.org
[   +2 ms] BUILD FAILED in 44s
[+1272 ms] Running Gradle task 'assembleDebug'... (completed in 46.6s)
[  +24 ms]
           ┌─ Flutter Fix ───────────────────────────────────────────────────────────────────────────────────────────────────┐
           │ [!] You need Java 11 or higher to build your app with this version of Gradle.                                   │
           │                                                                                                                 │
           │ To get Java 11, update to the latest version of Android Studio on https://developer.android.com/studio/install. │
           │                                                                                                                 │
           │ To check the Java version used by Flutter, run `flutter doctor -v`.                                             │
           └─────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
           
[+20645 ms] Exception: Gradle task assembleDebug failed with exit code 1
[  +14 ms] "flutter run" took 73,573ms.
[  +21 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:699:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1183:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:94:3)
           <asynchronous suspension>
           
           
[ +270 ms] ensureAnalyticsSent: 256ms
[   +7 ms] Running shutdown hooks
[   +3 ms] Shutdown hooks complete
[   +5 ms] exiting with code 1
