### ISSUE TITLE
google map's getScreenCoordinate method

### ISSUE THREAD

**Issue by wahyuanas** [flutter/flutter#107524]
Description:

I use google map's getScreenCoordinate method, for example
final myLatLng = LatLng(38.9647, 35.2233)
final myScreenCoord = await _controller.getScreenCoordinate(myLatLng );

Problem:

Then on the map I zoom out to the lowest level, after that I call the getLatLng method as follows
LatLng myLatLngAfterZoom =
        await _controller.getLatLng(ScreenCoordinate(x: myScreenCoord .x, y: myScreenCoord .y));
But the LatLng coordinates I get (myLatLngAfterZoom) are different from the previous coordinates (myLatLng). 

Question:
is it supposed to be like that, or is it because I misunderstood the use of the getScreenCoordinate method?

 Thank you

**Comment by exaby73** [comment]
The [`getScreenCooridinate`](https://pub.dev/documentation/google_maps_flutter/latest/google_maps_flutter/GoogleMapController/getScreenCoordinate.html) method is used to get the position on screen (from the top left of the map) where this `LatLng` is. Zooming in would change where this point lies and therefore give you a different result to where this point is.

I'm closing this issue as this is working as expected. If you disagree, please provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) along with your `flutter doctor -v` output and `pubspec.yaml`. Thank you
