### ISSUE TITLE
Expand flaky bugs description to make it clear

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#107570]
Flaky bugs are filed for two types:
1) multiple builds
2) multiple test runs in a single build.

It is confusing to understand the 2) where the whole build reads as a pass/success, but with an extra flaky step and logs hidden in the test step.

We should expand the description to make it clear where to find the logs/failures/flakes.

Context: https://github.com/flutter/flutter/issues/107543

**Comment by christopherfujino** [comment]
Would it be possible to have red steps that later get re-run and don't fail the overall build? I feel like this would be more intuitive.

I imagine this would mean moving the re-run logic from the devicelab runner to the recipe...

**Comment by keyonghan** [comment]
Based on offline discussions with @christopherfujino and @godofredoc , we would like to move the retry logic from test runner to recipes. Similar to what Engine is following:
https://ci.chromium.org/ui/p/flutter/builders/staging/Mac%20Staging%20Engine%20Drone/74177/overview
Recipes: https://flutter.googlesource.com/recipes/+/refs/heads/main/recipes/engine_v2/builder.py#122

**Comment by keyonghan** [comment]
Instead marking the step as `Failure` but not throwing exception when a flake happens:
https://flutter-review.googlesource.com/c/recipes/+/46720

**Comment by keyonghan** [comment]
Recipes CL landed, closing here presumably the issue is fixed.
