### ISSUE TITLE
Requesting a custom dimension for "run target" so we know where people are developing (emulator, simulator, device)

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#10751]
I can't seem to identify the "run target" for flutter tool. We'd like to know "how many people are running on emulators, simulators, or hardware" ?

I can see the "screens" for Run and HotRun, but not _where_ the app is run.

**Comment by eseidelGoogle** [comment]
@xster and @devoncarew have both done some analytics work.  This may be straightforward to wire up, I don't know.

It's also possible we should just record the CPU type, GPU and device model number.

**Comment by xster** [comment]
I won't paste the link here but it's in analytics -> behavior -> app speed -> flutter -> run.

A bit unfortunate that the data for screens, events and timings are stored in different 'tables' instead of being just different metrics for the same dimensions.

**Comment by sethladd** [comment]
Thanks!

I also noticed that we report target platform in the "screen" for run, when it's a hot reload run.

This line from run.dart in tools:

`return '$command/${getNameForTargetPlatform(await devices[0].targetPlatform)}';`

We don't clearly mark "emulator/simulator or real device", but we have this:

```
    case TargetPlatform.android_arm:
      return 'android-arm';
    case TargetPlatform.android_x64:
      return 'android-x64';
    case TargetPlatform.android_x86:
      return 'android-x86';
    case TargetPlatform.ios:
      return 'ios';
    case TargetPlatform.darwin_x64:
      return 'darwin-x64';
    case TargetPlatform.linux_x64:
      return 'linux-x64';
    case TargetPlatform.windows_x64:
      return 'windows-x64';
    case TargetPlatform.fuchsia:
      return 'fuchsia';
```

Are any of these the Simulator?

**Comment by xster** [comment]
Looking at the 'app speed' section is probably more accurate than the 'screen' section. 

Arm android can still be an emulator and x86 can be a physical device as well. The 'app speed' section will point them out specifically.

**Comment by sethladd** [comment]
Ah, I see you have "-emulator" in there. Perfect, that means we know if we're targeting emulator. I'll like to peel that out and make it a custom dimension.

**Comment by sethladd** [comment]
Chatted with @xster , reopening so we can send a custom dimension for run target.

**Comment by sethladd** [comment]
I'll take a crack at this.

**Comment by xster** [comment]
Thanks Seth!
