### ISSUE TITLE
Does TextureLayer actually need compositing?

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#107504]
Today the [TextureLayer](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/rendering/layer.dart#L860) forces compositing, even though it is itself always a LeafLayer. Since this ultimately bottoms out in a call to Texture::Paint (https://github.com/flutter/engine/blob/main/flow/layers/texture_layer.cc#L63), it seems like we could instead add this to the display list and expose via `Canvas.drawTexture` and remove the layer.

@flar @dnfield

**Comment by flar** [comment]
It would need access to the current texture registry for the frame, something that generally is not part of the environment of the DL. The DL doesn't currently have any notion of a "rendering context", it is its own collection of information that currently has no dependencies, but we could create one - it would have to be supplied at dispatch time.

This also complicates Diff testing of a DisplayList that has an embedded TextureID. How can 2 DLs compare to each other given that they are at the mercy of such an external factor.

If the texture ID mapping was known at the time that the DisplayList was being built then we could incorporate it by value, but then we'd have to rebuild the DL (i.e. ui.Picture) object on every frame. A tradeoff of compositing vs repainting.
