### ISSUE TITLE
image_picker crashes on iPad

### ISSUE THREAD

**Issue by pcomans** [flutter/flutter#10752]
## Steps to Reproduce
Opening an image picker reproducibly fails on iPad.
(tested on iOS 10.3.1 and 11.0 15A5278f)

The code is very simple:
```dart
            new RaisedButton(
                child: new Text("Upload Image"),
                onPressed: () {
                  Future<File> imageFile = ImagePicker.pickImage();
                }),
```
Tapping this button works as intended on Android and iPhone. On iPad, the error posted below is thrown.

The version of image picker is: image_picker: ^0.0.2

## Logs
*** Terminating app due to uncaught exception 'NSGenericException', reason: 'Your application has presented a UIAlertController (<UIAlertController: 0x101b377e0>) of style UIAlertControllerStyleActionSheet. The modalPresentationStyle of a UIAlertController with this style is UIModalPresentationPopover. You must provide location information for this popover through the alert controller's popoverPresentationController. You must provide either a sourceView and sourceRect or a barButtonItem.  If this information is not known when you present the alert controller, you may provide it in the UIPopoverPresentationControllerDelegate method -prepareForPopoverPresentation.'
Lost connection to device.

## Flutter Doctor

[✓] Flutter (on Mac OS X 10.12.5 16F73, locale en-US, channel alpha)
    • Flutter at /Users/philipp/code/flutter
    • Framework revision 6f77b4a9a7 (22 hours ago), 2017-06-14 17:27:08 -0700
    • Engine revision 18fdfb86bb
    • Tools Dart version 1.24.0-dev.6.7

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at /Users/philipp/Library/Android/sdk
    • Platform android-25, build-tools 25.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.3.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3.3, Build version 8E3004b
    • ios-deploy 1.9.1
    • CocoaPods version 1.3.0.beta.1

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Gradle version 3.2
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Ultimate Edition (version 2017.1.4)
    • Flutter plugin version 14.0
    • Dart plugin version 171.4694.29

[✓] Connected devices
    • Cracked Black iPad • f37dbd25e8d0d5b97962cc240c518388b9141fd8 • ios • iOS 10.3.1 (14E304)

**Comment by eseidelGoogle** [comment]
@collinjackson would know.

**Comment by collinjackson** [comment]
I think @goderbauer wrote the UI that is throwing this exception, do you want this one?

If not I'm happy to take it -- looks like a straightforward fix that can be tested in the simulator, no physical iPad is required.

**Comment by goderbauer** [comment]
The updated version of the iamge_picker plugin is live on pub: https://pub.dartlang.org/packages/image_picker

**Comment by pcomans** [comment]
@goderbauer That fixed it. Thank you so much!
