### ISSUE TITLE
Hosting native window views in Flutter app with Platform Views?

### ISSUE THREAD

**Issue by tashi146** [flutter/flutter#107518]
I am working on plugin which require native view. I have done the changes for android and ios with help of [platform integration](https://docs.flutter.dev/development/platform-integration/ios/platform-views). Now I am trying same with window support and could't find any official support. Is there any third party library or any plan on window support?

**Comment by maheshmnj** [comment]
Hi @tashi146, Thanks for filing the issue. Unfortunately, this is not supported as of today, But this seems to be on the todo list and is being tracked here https://github.com/flutter/flutter/issues/31713. Please follow up there for further updates, Closing this issue as a duplicate.
