### ISSUE TITLE
`autosubmit` merged PR after it removed `autosubmit` label

### ISSUE THREAD

**Issue by TahaTesser** [flutter/flutter#107521]
See https://github.com/flutter/flutter/pull/106955

![Screenshot 2022-07-13 at 11 21 07](https://user-images.githubusercontent.com/48603081/178687306-c3bbc160-3bb1-4018-9af1-cbf4900fe982.png)

When `autosubmit` label was first applied in [here](https://github.com/flutter/flutter/pull/106955#pullrequestreview-1036273562) 
then when rebasing the PR to fix `Google Testing` , `autosubmit` is [removed](https://github.com/flutter/flutter/pull/106955#issuecomment-1182828770) by the bot and then PR is merged anyways without re-adding `autosubmit` label. 

I think it shouldn't merge the PR without re-adding `autosubmit` label

**Comment by keyonghan** [comment]
There have been several fixes regarding tree status check in the past days.
This issue should have been resolved. Please reopen if you still see the issues.
