### ISSUE TITLE
Build fault tolerance into jobs that use `pub`

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#10764]
`pub` times out just enough to produce flakiness in our various automated tests:

- [ ] Travis
- [ ] Chromium bots
- [ ] Device lab

We should build in basic fault tolerance, where we retry N times with an exponential backoff before giving up.

**Comment by Hixie** [comment]
See also https://github.com/flutter/flutter/issues/9898 which is about the `flutter` tool itself.

**Comment by Hixie** [comment]
I'm going to close this in favour of https://github.com/dart-lang/pub/issues/2242.
