### ISSUE TITLE
[firebase_dynamic_links] [iOS] Deeplinks do not work if they are clicked while the app is killed

### ISSUE THREAD

**Issue by tudor07** [flutter/flutter#107643]
I have a deeplink that when clicked is supposed to open a specific screen.

**On Android all scenarios work perfectly.**

On iOS I see the following behaviours:

**Working scenario:**
If the app was already opened, but was put in background, if I click the deeplink, it works fine, the app is put to foreground and shows my custom screen for the opened deeplink path. These are the steps:
1. Open my app normally (tap app icon)
2. Put the app to background (I just dissmiss my app to go to iOS main menu, note: I do not kill my app from memory)
3. I go and open another app where I have my deeplink (eg. Messages or Mail)
4. Tap the deeplink
5. My app is brought to foreground and the correct screen is shown according to the tapped deeplink path

**Broken scenario:**
1. Kill my app from memory (from app switcher, swipe up on my app so it's killed)
2. I go and open another app where I have my deeplink (eg. Messages or Mail)
3. Tap the deeplink
4. My app opens on the first default screen, the custom screen for the deeplink is not shown (other way to put it: my handler for the deeplink is **not** called, `onLink`/`getInitialLink` **not** called)

Minimal code to reproduce:
<details>
  <summary>main.dart</summary>
  
  ```
  import 'dart:async';
  
  import 'package:flutter/material.dart';
  import 'package:firebase_core/firebase_core.dart';
  
  void main() async {
    WidgetsFlutterBinding.ensureInitialized();
  
      await Firebase.initializeApp(
        options: FirebaseOptions(
          apiKey: 'apiKey',
          appId: 'appId',
          messagingSenderId: 'messagingSenderId',
          projectId: 'projectId',
          authDomain: 'authDomain',
          databaseURL: 'databaseURL',
          storageBucket: 'storageBucket',
          measurementId: 'measurementId',
          androidClientId: 'androidClientId',
          iosClientId: 'iosClientId',
          iosBundleId: 'iosBundleId',
        ),
    );
  
  
    runApp(MyApp());
  }
  ```
</details>

<details>
  <summary>my_app.dart</summary>
  
  ```
  import 'package:firebase_dynamic_links/firebase_dynamic_links.dart';
  import 'package:flutter/material.dart';
  import 'package:flutter/services.dart';
  
  class MyApp extends StatefulWidget {
    MyApp({
      Key key,
    }) : super(key: key);
  
    @override
    _MyAppState createState() => _MyAppState();
  }
  
  class _MyAppState extends State<MyApp> {
    @override
    void initState() {
      super.initState();
  
      FirebaseDynamicLinks.instance.onLink.listen(_handleDeepLink);
      _getInitialLink();
    }
  
    Future<void> _getInitialLink() async {
      final PendingDynamicLinkData data =
          await FirebaseDynamicLinks.instance.getInitialLink();
      _handleDeepLink(data);
    }
  
    @override
    Widget build(BuildContext context) {
      // return app widgets...
    }
  
    Future<dynamic> _handleDeepLink(PendingDynamicLinkData linkData) async {
      final Uri deepLink = linkData?.link;
      if (deepLink == null) {
        return;
      }
  
      if (deepLink.path == '/my/custom/path') {
        Navigator.of(context).pushNamed(MyCustomScreen.routeName);
      }
    }
  }
  ```
</details>

<details>
  <summary>flutter doctor</summary>
  
  ```
  Doctor summary (to see all details, run flutter doctor -v):
  [✓] Flutter (Channel stable, 2.10.3, on macOS 12.4 21F79 darwin-arm, locale en-RO)
  [✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
  [✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
  [✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
      ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
  [✓] Android Studio (version 2021.2)
  [✓] Android Studio (version 2021.2)
  [✓] IntelliJ IDEA Community Edition (version 2022.1.3)
  [✓] IntelliJ IDEA Community Edition (version 2022.1.2)
  [✓] IntelliJ IDEA Ultimate Edition (version EAP IC-222.3244.4)
  [✓] IntelliJ IDEA Ultimate Edition (version EAP IC-222.3048.13)
  [✓] VS Code (version 1.69.0)
  [✓] Connected device (1 available)
  [✓] HTTP Host Availability
  ```
</details>

Firebase libs:
```
firebase_core: 1.19.2
firebase_dynamic_links: 4.3.2
```

**Comment by danagbemava-nc** [comment]
Hi @tudor07, issues with the `firebase` related products should be reported on their own repo over on https://github.com/firebase/flutterfire/issues. 

Kindly file this issue over there. 

If you are redirected back here, kindly leave a comment below and I will reopen this. 

I'll be closing this for now, as it seems like an issue with a third party plugin. 

Thank you

**Comment by tudor07** [comment]
For people arriving here in the future, I moved this ticket to `flutterfire` repo here: https://github.com/firebase/flutterfire/issues/9110
