### ISSUE TITLE
swiper error

### ISSUE THREAD

**Issue by Dragon-168** [flutter/flutter#107633]
'package:flutter/src/animation/animation_controller.dart': Failed assertion: line 822 pos 12: 'elapsedInSeconds >= 0.0': is not true.
package:flutter/…/animation/animation_controller.dart:822

**Comment by exaby73** [comment]
Hi @Dragon-168, please provide a [minimal, reproducible example][1] and the output of `flutter doctor -v` as well as `flutter run -v`.

[1]: https://stackoverflow.com/help/minimal-reproducible-example

**Comment by darshankawar** [comment]
Closing this as duplicate of https://github.com/flutter/flutter/issues/106277
