### ISSUE TITLE
Ink Spashes on emulator are very slow, miss most frames

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#10767]
I have a simple app, just playing around with Ink Splashes. I'm using the emulator on Windows. However, the splashes are so slow, it's almost hard to tell there is a splash. I see maybe 2-3 frames?

Here's the code:

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(
    new Material(
      child: new InkResponse(
        splashColor: Colors.red,
        onTap: () => print('tapped'),
      ),
    ),
  );
}
```

Using this version:

```
C:\Users\sethladd\Documents\Code\circles>flutter --version
Flutter • channel alpha • https://github.com/flutter/flutter.git
Framework • revision e2f54df5ab (13 days ago) • 2017-06-02 10:43:54 -0700
Engine • revision 1f2aa07571
Tools • Dart 1.24.0-dev.3.0
```

Is there a special flag I can set to make emulator + flutter run in "accelerated graphics" mode?

Thanks!

**Comment by sethladd** [comment]
I made a video: https://www.youtube.com/watch?v=ZmAElHGHUZY

**Comment by eseidelGoogle** [comment]
The video has some strange flashing pause button.  Have you tried the performanceOverlay?
https://docs.flutter.io/flutter/widgets/PerformanceOverlay-class.html

**Comment by sethladd** [comment]
Sorry, what do you mean "strange flashing pause button" ?

Related question: what kind of performance should I expect when using the emulator?

**Comment by eseidelGoogle** [comment]
The pause button was just my youtube player freaking out.  It was on my side, not your video, sorry.

**Comment by eseidelGoogle** [comment]
I would expect something close to 30fps on the iOS Simulator or x86 Android emulator (which always run --debug builds and are thus slower).  We aren't optimizing for simulators so I would not expect perfect performance, but it should be useable for doing work in.

**Comment by sethladd** [comment]
OK, good to know. Then, I can say that emulator + InkResponse is too slow to do work in. :/

**Comment by eseidelGoogle** [comment]
Can you please add more information about your hardware as well as the emulator in question so we can understand if this setup is reasonable to expect to be able to do work in? :D

**Comment by Hixie** [comment]
Also if you could get a timeline and zoom in on a couple of frames then take a screenshot of that, that would be great. Also if the timeline has any samples, see what those say the code is doing.

**Comment by sethladd** [comment]
No problem. Working on Windows 10. What kind of info would you like from the emulator? (Not sure what to dump out for you, but happy to try to get anything that's useful.)

**Comment by sethladd** [comment]
Here's a zip of the timeline , which should show three taps on my emulator.

[dart-timeline-2017-5-20.zip](https://github.com/flutter/flutter/files/1090117/dart-timeline-2017-5-20.zip)

@eseidelGoogle what kind of hardware info would be useful from my emulator? Happy to grab it.

**Comment by Hixie** [comment]
Wow, ok. This is all GPU and, to a lesser extent, compiling.
cc @chinmaygarde (GPU), @goderbauer (Windows), @jason-simmons (Android)

**Comment by sethladd** [comment]
Thanks for taking a look!

I may or may not have my emulator setup correctly (??) ... happy to provide more data here.

**Comment by liyuqian** [comment]
From the Q3 2019 Survey, we've known that many developers care about the debug and simulator performance. While they're not as critical as the release performance on actual devices, I wonder if we can add some benchmarks for either debug or simulator performance, so we'll at least know when we regress. @digiter @dnfield @collinjackson : is there any known difficulty of doing so on either the device lab, or the Fire lab?

**Comment by markusaksli-nc** [comment]
This seems to be working identically on Android 11 emulator and my SM G950F physical on the latest master `1.22.0-10.0.pre.403`.
<details>
 <summary>flutter doctor -v</summary>

```
[√] Flutter (Channel master, 1.22.0-10.0.pre.403, on Microsoft Windows [Version 10.0.19041.508], locale en-US)
    • Flutter version 1.22.0-10.0.pre.403 at C:\Development\flutter_master
    • Framework revision 975cf9af59 (9 hours ago), 2020-09-28 23:42:03 -0400
    • Engine revision 438685dad0
    • Dart version 2.11.0 (build 2.11.0-174.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\marku\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.6.5)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.6.30320.27
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.0)
    • Android Studio at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (5 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)           • windows       • windows-x64    • Microsoft Windows [Version 10.0.19041.508]
    • Web Server (web)            • web-server    • web-javascript • Flutter Tools
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 85.0.4183.121
    • Edge (web)                  • edge          • web-javascript • Microsoft Edge 85.0.564.51

• No issues found!
```
</details>

@liyuqian Should this still be open? https://github.com/flutter/flutter/issues/10767#issuecomment-539230210 sounds like a separate issue.

**Comment by liyuqian** [comment]
It's nice to hear that it performs well on Android 11 emulator. I think we can close this issue.
