### ISSUE TITLE
🐛 BUG [video_player] Some HLS Video doesn't load on few Android Devices.

### ISSUE THREAD

**Issue by tsvillain** [flutter/flutter#107696]
**Issue:** 

- I am not able to stream a few HLS Vimeo links. (https://player.vimeo.com/external/729923557.m3u8?s=8519f298bfb98bd703a2f23814ddac330a3c1e66)

**Steps to Reproduce:**

- Clone `video_player` example
- Replace the existing video link with the HLS link mentioned in the Issue.
- Run the app on Android Emulator (Pixel 3 API 31, Android 12.0 Google Playe | arm64)

**Fix:** 

- We need to Bump the ExoPlayer dependencies version to the following: 
     ```
        implementation 'com.google.android.exoplayer:exoplayer-core:2.18.0'
        implementation 'com.google.android.exoplayer:exoplayer-hls:2.18.0'
        implementation 'com.google.android.exoplayer:exoplayer-dash:2.18.0'
        implementation 'com.google.android.exoplayer:exoplayer-smoothstreaming:2.18.0'
     ```
Currently, `video_player` is using 2.17.1

I tried updating code in the `video_player` plugin repo but it's not reflecting.

**Temporary Solution (Till this is fixed and released on pub.dev):**

- Add the following dependencies in your `app/build.gradle`
    ```
        implementation 'com.google.android.exoplayer:exoplayer-core:2.18.0'
        implementation 'com.google.android.exoplayer:exoplayer-hls:2.18.0'
        implementation 'com.google.android.exoplayer:exoplayer-dash:2.18.0'
        implementation 'com.google.android.exoplayer:exoplayer-smoothstreaming:2.18.0' 
    ```

**Comment by tsvillain** [comment]
@stuartmorgan @a14n

**Comment by exaby73** [comment]
Hello @tsvillain. Looks like a valid request. Thank you for filing it :)

**Comment by stuartmorgan** [comment]
@tsvillain Please do not ping random people when filing issues.

**Comment by tsvillain** [comment]
> @tsvillain Please do not ping random people when filing issues.

Extremely sorry about that.

**Comment by stuartmorgan** [comment]
Exoplayer was rolled in https://github.com/flutter/plugins/pull/6123, so this should be resolved.
