### ISSUE TITLE
Verify wifi debugging works with Xcode 9

### ISSUE THREAD

**Issue by cbracken** [flutter/flutter#10762]
Once #10602 is fixed, ensure Flutter works with wifi debugging.

**Comment by jmagman** [comment]
@christopherfujino I know this bug is old, but can this be closed with https://github.com/flutter/flutter/issues/37699?

**Comment by christopherfujino** [comment]
I'd have to verify. Probably?

**Comment by jmagman** [comment]
Closing in favor of https://github.com/flutter/flutter/issues/15072 which has more details.
