### ISSUE TITLE
[engine v2 + artifacts] can't locate Mac_android_aot_engine.json

### ISSUE THREAD

**Issue by XilaiZhang** [flutter/flutter#107674]
Looks like there is no corresponding entries in https://github.com/flutter/engine/blob/main/ci/builders, to produce mac andriod artifacts (android-arm-profile/darwin-x64.zip etc.). Therefore I can't test the changes I made to mac andriod / third party build gn. This would be solved after sir Godofredo is back.

**Comment by XilaiZhang** [comment]
cc @godofredoc @CaseyHillers

**Comment by XilaiZhang** [comment]
A quick recap from 1:1 with sir Godofredo today:
1. mac-andriod targets and ios-targets (e.g. ios/artifacts.zip) have been configured, and will be uploaded to [json files](https://github.com/flutter/engine/blob/main/ci/builders) soon.
2. flutterMacOS_framework.zip dropping symlinks is a known issue and has been fixed on Linux. It will be fixed in the mac BUILD.gn soon.
3. We are advocating separation of zip files into different output folders, but might receive oppositions. Christopher and Jenn will help verify the changes needed on the tools side, to see if additional files need to be included.
4. current zip on GCS might include historical leftover files that shouldn't be there. Build.gn output targets will differ with GCS targets in certain aspects, and those differences are acceptable as long as they pass [tests](https://github.com/flutter/flutter/pull/105938/files#diff-a722a1dc6b49475ae13775e5c74f26bcdc63a5ed720d0c9767920fdddd202d22).

**Comment by keyonghan** [comment]
This has been resolved.

**Comment by XilaiZhang** [comment]
Umm after revisiting (https://github.com/flutter/engine/pull/35707), I realized that the macOS symlinks are still dropped

**Comment by godofredoc** [comment]
Can you please add more details? e.g. link to the artifact with the missing symlinks, was it generated from v2 recipes, etc

**Comment by XilaiZhang** [comment]
For sure, yeah i might have done it wrong, I built the macOS.framework in the following way:

1. first build `host_release` and the target `flutter/shell/platform/darwin/macos:zip_macos_flutter_framework`
2. then build `mac_release_arm64` and the target `flutter/shell/platform/darwin/macos:zip_macos_flutter_framework`
3. finally run `flutter/sky/tools/create_macos_framework.py` with all the args.
the above would produce a `out/release/framework/FlutterMacOS.framework.zip` file. but compared with the framework.zip downloaded from google cloud (https://pantheon.corp.google.com/storage/browser/_details/flutter_infra_release/flutter/a5967ed309ef2beb9625f128571f7060597b5eda/darwin-x64-release/FlutterMacOS.framework.zip;tab=live_object?authuser=0), there seems to be a few differences:

1. files as the first level child files of the extracted zip aren't symlinks, `flutterMacOs`, `Headers`, ` Modules`, `Resources`.
2. the folder in Versions/Current isn't a symlink of the folder Versions/A

Like sir Godofredo pointed out the symlinks might have been added through some steps in the recipe but I might be unaware of it. so i could be wrong in the process of producing the artifact.

**Comment by godofredoc** [comment]
Rather than building the file yourself you can use one of the files generated by https://ci.chromium.org/p/flutter/builders/prod/Mac%20mac_host_engine

**Comment by XilaiZhang** [comment]
Oh this is cool! yeah engine v2 is already in prod now. 

umm my understanding is that I need to build the artifact locally to test the changes i made to the generator script. Yeah i think the existing builders might have added the symlinks to the files in recipe, is there a way I can reproduce this step of adding symlinks locally? (my understanding is that the existing builders won't use the changes i made to the generator script, because it checks out the engine repo from web?)

**Comment by godofredoc** [comment]
Is that a different CL from the one in recipes?

**Comment by XilaiZhang** [comment]
umm my understanding might not be correct. so I think the recipe checks out the engine repository (from tip of tree), and uses the sky/tools/macos script from tip of tree (a generator script without my local changes), and so I think this way it would not embed the metadata files.

When i build my files locally, I can run my local version of generator script to embed the metadata. I could be wrong, but yeah my understanding is that the generator scripts are different for existing build and local build.

**Comment by godofredoc** [comment]
@XilaiZhang can we close this bug?

**Comment by XilaiZhang** [comment]
Sure, thank you sir!
