### ISSUE TITLE
Adding Custom channel

### ISSUE THREAD

**Issue by sikandernoori** [flutter/flutter#107691]
Hello,

By default flutter flutter has 3 channels.

```
Flutter channels:
  master
  beta
* stable
```

Is there an option of making your own custom channel ?

For example I am working on a project which is running on old version of flutter, so to switch to that project I always have to downgrade flutter version.

It would be convenient if there is an option of creating a custom channel which I can lock to older version of flutter and use it when needed.

**Comment by huycozy** [comment]
Hi @sikandernoori 
I assume that you have already had 3 Flutter channels in 3 separate directories as below tutorials. 
- https://medium.com/@sarbagyastha/using-two-or-more-different-versions-of-flutter-in-single-machine-484293c2a7ff
- https://stackoverflow.com/a/68047743/5921933

You can do the same with older Flutter versions by downloading the versions here: https://docs.flutter.dev/development/tools/sdk/releases?tab=windows (please select the corresponding environment)
and follow the same steps in the instructions above.

Closing as this is neither a bug nor a feature request.

**Comment by sikandernoori** [comment]
Hello @huycozy 

I am familiar with the multi SDK approach like you shared in the links. But that's just wrong in a sense when you only want to use a different version only.

This is not a bug rather a good feature to have in flutter.

there is an organization FVM who helps achieve the same goal what you mentioned in Links in a way better approach here is the [link](https://fvm.app/)

But still if this feature is available in flutter itself people won't have look for bulky way arounds.

**Comment by huycozy** [comment]
@sikandernoori  I re-open the issue for further discussion. 

> For example I am working on a project which is running on old version of flutter, so to switch to that project I always have to downgrade flutter version.

I have three Flutter versions on my machine: master, beta, stable and 2.10.5:
![Screen Shot 2022-07-18 at 11 38 38](https://user-images.githubusercontent.com/104349824/179446161-cf9de382-96b3-4f09-b631-b94a06ab7e17.png)

And it's so easy when you want to use a specific Flutter version by setting up alias for them without downgrade Flutter version:

```bash
alias flutterd='/Users/huynq/Documents/GitHub/flutter_dev/bin/flutter'
alias flutterm='/Users/huynq/Documents/GitHub/flutter_master/bin/flutter'
alias flutterb='/Users/huynq/Documents/GitHub/flutter_beta/bin/flutter'
alias flutter2105='/Users/huynq/Documents/GitHub/flutter2.10.5/bin/flutter'
```

For example:
```
flutter run
flutterm run
flutter2105 run
```

If you still believe this should be a Feature request. Please help to update the issue's description as [template here](https://github.com/flutter/flutter/issues/new?assignees=&labels=&template=3_feature_request.md&title=) for further opinions from the team.
Thank you!
