### ISSUE TITLE
[web] Pinch zoom via touchpad does not work as expected. 

### ISSUE THREAD

**Issue by Jonas-Schnee** [flutter/flutter#107624]
## Steps to Reproduce

Checked only on Windows with Chrome (Version 102.0.5005.63) and Firefox (102.0.1).

1. Open any Flutter application (for example https://gallery.flutter.dev/#/)
2. pinch-zoom via touchpad (on laptop)

**Expected results:** 
Doing this on a html website behaves like a magnifying glass, meaning it zooms in without page reflow. Afterwards, I am able to perform 2-finger-scroll to move the pinch-zoomed area (see  [visual viewport api](https://wicg.github.io/visual-viewport/#definition-of-the-visual-viewport))

Example using flutter.io:
![pinch_as_should_be](https://user-images.githubusercontent.com/73643512/178926666-2690d69c-8506-422a-8c14-e11d6730cc1e.gif)

So I would expect the app to be zoomed without re-layout and possible 2-finger-scroll afterwards.

**Actual results:** 
The app is not properly zoomed and wrongly aligned. There is a re-layout happening during the zoom. It is not possible to perform 2-finger-scroll afterwards
![pinch_as_it_is](https://user-images.githubusercontent.com/73643512/178925785-2d8fe246-8f68-41f7-9c0e-a74ef47d28ea.gif)

I think this is a serious issue as pinch-zoom is a standard way of users to zoom in web apps when using a laptop. 

Is this a known issue? I could not find a similar bug report. It seems to me that the way flutter uses visual viewport for its size calculation is wrong. 

I am not providing a code sample, logs or flutter doctor results as this happens on all apps including flutter gallery.

**Comment by huycozy** [comment]
Hi @Jonas-Schnee, thanks for filing the issue. 
I see there's an open issue addressing the case you described #97305. That issue is considered as a `new feature` on the web.
Closing as a duplication, so please follow up on it for further updates.

**Comment by Jonas-Schnee** [comment]
Thanks @huycozy,
I don't understand how this is considered a `new feature` (with prio P5) as it is a default web/browser functionality that breaks any flutter app.

**Comment by huycozy** [comment]
@Jonas-Schnee  please give your thoughts in comments on that issue. Thanks!

**Comment by Jonas-Schnee** [comment]
Sure will do - thank you!
