### ISSUE TITLE
[go_router] Prevent access to internal classes

### ISSUE THREAD

**Issue by johnpryan** [flutter/flutter#107757]
The following fields on GoRouter should be private:

- `routerDelegate`
- `routeInformationProvider`
- `routeInformationParser`
- `routeConfiguration`

They are currently are exposed for testing reasons and for the `.router()` constructor:

```dart
final GoRouter _router = GoRouter(
  // ...
);

@override
Widget build(BuildContext context) => MaterialApp.router(
  routeInformationProvider: _router.routeInformationProvider,
  routeInformationParser: _router.routeInformationParser,
  routerDelegate: _router.routerDelegate,
);
```

We should make these return types abstract (for example, `GoRouteInformationParser` would become `RouteInformationParser`).

We should also be providing a different class for navigation, otherwise users can do things like this:

```dart
// GoRouter publicly exposes RouterDelegate, RouteInformationParser, etc
GoRouter.of(context).routerDelegate.matches.matches.removeLast();
```

The `InheritedGoRouter` class should be provide a new object, `RouteState` that supports relative routes (See the [prototype](https://pub.dev/packages/go_router_prototype)) and exposes specific methods  like `pop()`:

```dart
// old way
GoRouter.of(context).go();
// new way
RouteState.of(context).go(/*...*/)
```

**Comment by johnpryan** [comment]
We don't necessarily need to break the API by changing `GoRouter.of()` to `RouteState.of()`, but we should change the return type to be more precise about what methods we expose

**Comment by chunhtai** [comment]
It will be a hard breaking change though. I was wondering whether we may actually need to open up these classes if we allow developer to swap out their own delegate to use along with the go_router delegates
