### ISSUE TITLE
[go_router] Remove namedLocation API

### ISSUE THREAD

**Issue by johnpryan** [flutter/flutter#107729]
The current implementation of `namedLocation` uses asserts and isn't tested. We should simplify or deprecate this API. It's not doing anything related to routing, and users can implement their own map from named locations to paths on their own using a Map.  Another option is to use typed routes with go_router_builder instead of this API. 

Context: https://github.com/flutter/packages/pull/2317#discussion_r921572424

**Comment by johnpryan** [comment]
That's a good point, it's clunky without `goNamed()`...

```dart
final uri = Uri.parse('/user/${42}').replace(
    queryParameters: {
      'filter': 'abc'
    });
context.go(uri.toString());
```

In the long run, it would be better to have one method instead of two. I propose that we deprecate `goNamed`, and add `pathParameters` and `queryParameters`  parameters to `go()`, like this:

```dart
context.go('/user/:id',
    pathParameters: {'id': '123'},
    queryParameters: {'filter': 'abc'});
```

Users will still be able to call `context.go('/user/123?filter=abc')` if they want.

There's also [go_router_builder](https://pub.dev/packages/go_router_builder), which can make this even easier: https://pub.dev/packages/go_router_builder#navigation

**Comment by TatsuUkraine** [comment]
Me personally like ability to navigate using Name instead of full path. Also it's a common practice in a lot of different routers (not only flutter)

Also, need to take into account that big app with quite complex navigation without Named routes may become quite dirty.

My personal thought that `namedLocation` helps to keep route generation consistent between app and go_router when it comes to route generation rules and validation

**Comment by johnpryan** [comment]
To avoid confusion for new users, I'd like to have a single way to navigate (`go()`)

There's no reason this API couldn't be implemented as a separate class, since there's nothing related to routing involved with mapping names to route templates.  For example:

```dart
// Replacement for goNamed() API:
class GoRouteLookup {
    Map<String, String> _routesByName = {};

    GoRouteLookup();

    void add(String name, String routeTemplate) {
        _routesByName.add(name, routeTemplate);
    }

    String lookup(String name, {
            Map<String, String> pathParameters,
            Map<String, String> queryParameters}) {
        // ...
    }
}


// How to use:
final lookup = GoRouteLookup();
lookup.add('user', '/users/:userId');
GoRouter.of(context).go(lookup('user', pathParameters: {'userId': '123'}));
```

**Comment by TatsuUkraine** [comment]
> There's no reason this API couldn't be implemented as a separate class

It seems the same point was used during making Navigator 2.0, which end up bunch of third-party libraries, long UXR of solutions for navigator to reduce boilerplate and adopting go_router))))

**Comment by johnpryan** [comment]
I think it would be better if there was _one_ way to navigate, not two. The original pitch for go_router is that it simplifies Navigator 2.0 by providing one way to navigate , `go()`.

As a compromise, we could consider making this a separate library `package:go_router/named.dart` that adds goNamed to GoRouter via extension methods. That way, we don't break current users and we don't confuse new users either.

**Comment by chunhtai** [comment]
> As a compromise, we could consider making this a separate library `package:go_router/named.dart` that adds goNamed to GoRouter via extension methods. That way, we don't break current users and we don't confuse new users either.

I still vote for deprecating it, the go_router_builder provide a better API. The only downside is it use code gen.

**Comment by andyduke** [comment]
Codegen is a significant downside. When it will be possible to implement this without Codegen (for example, using Static Metaprogramming) - then you can deprecate it, but now it will force developers to create new wrappers around GoRouter (although GoRouter is a wrapper over Navigator 2.0) or force them to use Codegen - this is not a good idea.

**Comment by chunhtai** [comment]
We can do this step by step, but we should at least deprecate GoRouteState.namedLocation as it will clear out a lot of mess internally. We should wait we support build context in redirect, otherwise customer won't be able to use namedLocation in redirect

**Comment by rayk** [comment]
Hey @chunhtai  and @johnpryan 

Totally on board that routing can be made simpler, that is ```go()``` and if there means a lookup for the route, so be it. But one thing I would not like to lose in terms of behaviour is being able to easily get ```RouteConfiguration``` from the GoRouterState that is commonly passed into the page.

Current, I noticed:
```dart
 // TODO(johnpryan): remove once namedLocation is removed from go_router.
  // See https://github.com/flutter/flutter/issues/107729
  final RouteConfiguration _configuration;
```

Which I am leveraging as a snapshot of the router configuration at the point when the navigation is done.

So if could come up with a way to do the following:

1. Simply routing ```go()``` for newbie users, Implies an easy way to find, select or build the route to the desired destination.
2. Preservation of an immutable/snapshot of ```RouteConfiguration``` when the navigation was made that can be passed into the page.

This would be a real plus.

**Comment by ahmednfwela** [comment]
why not remove `goNamed` and introduce a new parameter to `go()`, e.g. `lookupRouteName` and change `go()` to be like this:

- case 1: using absolute path

```dart
context.go(
    path: '/user/:id',
    pathParameters: {'id': '123'},
    queryParameters: {'filter': 'abc'}
);
```

- case 2: using named path

```dart
context.go(
    lookupRouteName: 'userDetails',
    pathParameters: {'id': '123'},
    queryParameters: {'filter': 'abc'}
);
```

only downside is that `path` and `lookupRouteName` will both have to be non-required and nullable, so a user can just call 
```dart
context.go();
``` 
which is going to throw at run time and not compile time

**Comment by johnpryan** [comment]
I also think we could come up with a better name here. Searching for "named routes Flutter" still brings the [old named routes API](https://docs.flutter.dev/cookbook/navigation/named-routes), which isn't going away any time soon.

**Comment by johnpryan** [comment]
In AngularDart, routes are defined as RoutePath objects, and can be used for navigation by assigning them to static variables, like this:

```
class RoutePaths {
  static final home = RoutePath(path: 'home');
  static final settings = RoutePath(path: 'settings');
}
```

Child routes can be defined in the same way:

```
class RoutePaths {
  static final articles = RoutePath(
      path: 'articles', parent: app.RoutePaths.home, useAsDefault: true);
  static final users = RoutePath(path: 'users', parent: app.RoutePaths.home);
}
```

Then they can be referenced for navigation, for example using a link:

```
<nav>
    <a [routerLink]="RoutePaths.articles.toUrl()"
       [routerLinkActive]="'active'">Articles</a>
    <a [routerLink]="RoutePaths.users.toUrl()"
       [routerLinkActive]="'active'">Users</a>
</nav>
```

This gives you the type checking you are looking for without requiring you give a unique name to each route. But this would be a drastic change to how go_router was originally designed and it's probably not something we can improve at this point.
