### ISSUE TITLE
Difficulty when integrating Flutter with an iOS cocos2d-x based app

### ISSUE THREAD

**Issue by deadlocklogic** [flutter/flutter#107764]
Hi,

## Steps to Reproduce

1. create a cocos2d-x project for ios
2. generate Xcode project with CMake
3. add Flutter to the existing app as per the docs (init pod, modify then install)
4. build

## Logs

<details>
<summary>Logs</summary>

```
/Users/user/Library/Developer/Xcode/DerivedData/CocosGame-cmpatcfndynytsfurfklqcdsitnh/Build/Intermediates.noindex/CocosGame.build/Debug-iphoneos/CocosGame.build/Script-59C6F09F151681E75D29DB9D.sh: line 4: /Users/user/Desktop/user/cocostest/CocosGame/../my_flutter/.ios/Flutter/flutter_export_environment.sh: No such file or directory
```

```
```

</details>

Then offending file contains:
```
#!/bin/sh
set -e
set -u
source "${SRCROOT}/../my_flutter/.ios/Flutter/flutter_export_environment.sh"
export VERBOSE_SCRIPT_LOGGING=1 && "$FLUTTER_ROOT"/packages/flutter_tools/bin/xcode_backend.sh build
```

It is likely a problem with `${SRCROOT}`, but I am not so sure, and what to do about it anyway.
Any help/suggestions would be greatly appreciated.
Thanks!

**Comment by deadlocklogic** [comment]
I can upload a minimal repro if someone is interested. But I really hope someone could help me with some hints.

**Comment by danagbemava-nc** [comment]
Hi @deadlocklogic, please provide the following 

- the output of flutter doctor -v
- the complete minimal reproducible code sample 
- the full logs when you try to either build/run the app

Thank you

**Comment by deadlocklogic** [comment]
Hi, after some investigations I found a solution to my problem.
Apparently Flutter complains when the `Game.xcodeproj` isn't a direct child of the project folder, so generating then Xcode project in the root directory fixes the problem.
