### ISSUE TITLE
Let me use the version from the Flutter snap so I don't have to download twice. 

### ISSUE THREAD

**Issue by jo-erlend** [flutter/flutter#107728]
I have a mobile internet connection that is metered and slow when I'm out of the plan. So I did a snap download flutter to download the futter snap package to local storage so I could go out to the park and have some fun with Flutter. But then I came to the park and just do a local snap install flutter.snap". Great. I was then told to run "fflutter config --android-studio-dir /snap/android-studio/current/android-studio", but then it suddenly starts downloading Flutter, which is going to take a long time and I'm guessing that if I abort, it'll start again. 

Why does Flutter not simply rely on the Flutter snap package I have, instead of manually downloading it outside the packaging system? It is so damaging to the user experience to suddenly and without warning have to wait for over an hour on first run after installing a package and have to pay for the privilege to boot. 

Please fix this. Also; am I running the risk every time I run Flutter that it may suddenly require hundreds of megabytes in downloads without warning?

**Comment by stuartmorgan** [comment]
Please file issues with the snap installation at https://github.com/canonical/flutter-snap/issues

> Also; am I running the risk every time I run Flutter that it may suddenly require hundreds of megabytes in downloads without warning?

Flutter downloads binaries on demand to avoid downloading a lot of large files people may never need (e.g., the Flutter engines for all the target platforms they never target). The `flutter precache` command will let you get the parts you want in advance, and is designed for use cases like yours.

**Comment by jo-erlend** [comment]
I don't understand. I do not. For me, three hours of waiting while I'm eager to do something, does not equal three hours of my computer doing downloads while I'm asleep. It took me two weeks to download Ubuntu 22.04, but now I have it on a 100Gbps connection, so when I did upgrade, I did not have to wait. I have every Ubuntu going back to 2006 stored, because disks are cheap, but time is not. 

Is there a way for me to download the Flutter ecosystem that way, or some other way that I can install it on demand on different systems? This sense of not being in control is not appetizing at all. Do you remember when Bill Gates demonstrated Windows 98? I don't like that experience. 

If this is open source, why can't I just download it in advance?

**Comment by jo-erlend** [comment]
Oh, you just closed it. I see. It's just not for me then. Nothing wrong with that. It's the way of the MAGA I guess.

**Comment by stuartmorgan** [comment]
> Is there a way for me to download the Flutter ecosystem that way

Please see my comment above: `flutter precache` is there for the exact purpose of pre-downloading everything you need so that you won't need to do on-demand downloads later.
