### ISSUE TITLE
The buttons in the text selection toolbar bounce on desktop

### ISSUE THREAD

**Issue by justinmc** [flutter/flutter#107733]
On desktop, the buttons in the text selection toolbar have some small vertical movement after they appear.  Notice the downward movement of the buttons in the gif below as I move my mouse.

<img src="https://user-images.githubusercontent.com/389558/179282176-46065db4-c332-4ee0-91ed-5b3c7b602eae.gif" />

### Steps to reproduce

  1. Run any app with text that can be selected, such as the one given below with a TextField, on desktop.
  2. Right click to show the toolbar.
  3. Wait a bit, maybe move the mouse.
 
Expected: The toolbar buttons stay in place and don't move.
Actual: The toolbar buttons move vertically by a pixel or two.

<details>

<summary>Example app</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}
class MyHomePage extends StatelessWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            TextField(),
          ],
        ),
      ),
    );
  }
}
```

</details>

**Comment by gspencergoog** [comment]
Justin, where did you reproduce this?  It looks like it's drawing a different menu from the one that Taha shows. (Desktop Triage)

**Comment by justinmc** [comment]
Sorry, this was on Linux!  I just tried it again and I still see it on Linux, using a physical mouse.  I tried on Mac and did not see it, using a trackpad.  Not sure if that has anything to do with it.

**Comment by jpnurmi** [comment]
This is caused by [fractional translation](https://github.com/flutter/engine/pull/34115). It's not 100% deterministic but relatively easy to reproduce with popups and dialogs and device pixel ratio 1.

https://user-images.githubusercontent.com/140617/185578566-78475c9e-8caa-4926-811d-b896aa692c90.mp4

**Comment by tgucio** [comment]
Likely same as https://github.com/flutter/flutter/issues/107921 (seen on Windows, also with dialogs, Chips etc.)

**Comment by justinmc** [comment]
@jpnurmi Thanks for the insight!

@jonahwilliams Could you help me understand how https://github.com/flutter/flutter/issues/103909 affects this bug?  I'm wondering if it will be fixed by that or if there's anything else we need to do in the framework.

**Comment by jonahwilliams** [comment]
I have not debugged the issue, though @jpnurmi is looking at it. https://github.com/flutter/flutter/issues/103909 landed a long time ago - essentially it removed forced pixel snapping from composited layers. That fixed some instances of the above, where an animated transition would appear to "snap" into place as it concluded. According to some other filled issues, that makes some previous rendering that would have been pixel aligned non-pixel aligned, and so on low DPR there can be apparent snapping as something animates across pixels.

Its possible there is another issue mixed in, where we might still be rounding out in places - which would actually be a bug and not just an artifact of rendering at low DPR

**Comment by justinmc** [comment]
Thanks I appreciate the explanation!  I'll keep an eye out for an update from @jpnurmi.

A large monitor like where I saw this bug would be a low DPR compared to a late model smartphone if I'm not mistaken, so maybe that's evidence in favor of this being due to the snapping thing.

**Comment by jonahwilliams** [comment]
Right, so if you're on a low DPR device like a desktop monitor (probably 1.0 or 1.25), then drawing something like text at fractional pixel boundaries may be a noticable shift from pixel aligned  (depending on a lot of other things like how AA is working).

The pixel snapping I removed worked at the level of the composited layer, so if you painted text at 0,0 or at some other position that when multiplied by dpr landed at round number, your text was guaranteed to be pixel aligned. But as far as I know, you could still draw your text at something like 0.33, 0.33 and end up non-pixel aligned.

In general, this is the same sort of problem as the hairline appearing between solid color containers.

**Comment by jpnurmi** [comment]
With `checkerboardRasterCacheImages` turned on, it's easy to see how they are incorrectly drawn:

https://user-images.githubusercontent.com/140617/185736996-e1ebde52-1c4e-4fea-8a65-b1d4e59c1b68.mp4

**Comment by jpnurmi** [comment]
Sometimes even lines are not straight:
![Screenshot from 2022-08-20 11-17-33](https://user-images.githubusercontent.com/140617/185738554-ab9bd222-4e39-489d-9e27-027c17049c8f.png)

The respective raster cache image looks fine, though:
![rasterize_931_457_2](https://user-images.githubusercontent.com/140617/185738526-ef64d9b7-5c3d-4a28-9847-3467eeaaba65.png)

**Comment by Hixie** [comment]
FWIW, I'm not able to reproduce this. I tried today's tip of tree (roughly 3.22.0-22.0.pre.13, 21da3a8063) and a version from when the issue was filed (3.1.0-0.0.pre.1695, 4f9528293f). Linux desktop. 96 dpi, 1.0 dpr.

**Comment by justinmc** [comment]
I just tried the same and I was able to reproduce it on [4f95282](https://github.com/flutter/flutter/commit/4f9528293f54037993a6b2eb8f1df5604a3da954) but not on tip of tree. It seems like it's been fixed, so I will close this, but if anyone else reproduces it on master let me know.
