### ISSUE TITLE
bump `meta` version

### ISSUE THREAD

**Issue by iapicca** [flutter/flutter#107717]
## Steps to Reproduce

- add to pubspec any package that depend from 
```yaml
  meta: ^1.8.0
```
- run `flutter pub get`

**Expected results:**

`flutter_test` dependencies should be up-to-date

**Actual results:**

```console
Running "flutter pub get" in <APP>...                       
Because every version of flutter_test from sdk depends on meta 1.7.0 and <PACKAGE> >=0.1.0+4 depends on meta ^1.8.0, flutter_test from sdk is incompatible with <PACKAGE> >=0.1.0+4.
So, because <APP> depends on both <PACKAGE> ^1.0.0 and flutter_test from sdk, version solving failed.
pub get failed (1; So, because <APP> depends on both <PACKAGE> ^1.0.0 and flutter_test from sdk, version solving failed.)
exit code 1
```

## workaround

```yaml
 dependency_overrides:
   meta: ^<some version>
```

note that [does not work with packages](https://github.com/dart-lang/pub/issues/3493) published on `pub.dev`

```console
Package validation found the following error:
* Your pubspec.yaml must not override non-dev dependencies.
  This ensures you test your package against the same versions of its dependencies
  that users will have when they use it.
Sorry, your package is missing a requirement and can't be published yet.
For more information, see: https://dart.dev/tools/pub/cmd/pub-lish.
```

### doctor

```bash
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.4 21F79 darwin-arm, locale en-EE)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.69.1)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

• No issues found!
```

**Comment by iapicca** [comment]
removing `flutter_test` dependency (for science)
reveals 
```console
Resolving dependencies in ... (1.7s)
Because <PACKAGE> >=0.1.0+4 depends on meta ^1.8.0 and every version of flutter from sdk depends on meta 1.7.0, <PACKAGE> >=0.1.0+4 is incompatible with flutter from sdk.
So, because yak_tween depends on both flutter from sdk and <PACKAGE> ^1.0.0, version solving failed.
```

retitlying the issue

#

please consider the **misleading** error message part of the issue

**Comment by stuartmorgan** [comment]
It [already has been](https://github.com/flutter/flutter/blob/master/packages/flutter/pubspec.yaml#L13). It's best to test version conflicts against the latest master, not stable, as dependencies are rolled often. (Almost every issue that I've seen requesting a dependency update was already obsolete when it was filed.)

> please consider the **misleading** error message part of the issue

Requests for changes to pub resolver output (such as showing all sources of a conflict instead of just one, which I assume is what you are looking for here) would need to be filed against pub, not Flutter.
