### ISSUE TITLE
External texture for Windows (Win32 and UWP)

### ISSUE THREAD

**Issue by lattice0** [flutter/flutter#107797]
Since https://github.com/flutter/flutter/issues/38601 is closed and has no PRs linked, I wonder what is the status of this. 

Is there support for Flutter external textures on Windows? If so, is it a real GPU external texture or does it copy to CPU and then to GPU back again? Is it OpenGL? Is it for Win32 or UWP?

**Comment by stuartmorgan** [comment]
> Since #38601 is closed and has no PRs linked

There are links to several PRs in that issue, most notably https://github.com/flutter/engine/pull/19405.

> Is there support for Flutter external textures on Windows? If so, is it a real GPU external texture or does it copy to CPU and then to GPU back again? Is it OpenGL?

If you have questions about the APIs in `flutter_texture_registrar.h` try one of the resources listed at https://flutter.dev/community#community-grid for help.

Closing as the issue tracker is specifically for issue reports and feature requests.
