### ISSUE TITLE
Mutator stack should store a shared reference to the backdrop filter

### ISSUE THREAD

**Issue by flar** [flutter/flutter#107763]
I missed this in the initial reviews of https://github.com/flutter/engine/pull/34408 but storing a raw pointer to a Dl<Attribute> object is not a good practice. The stored value should be a shared ptr. See comment https://github.com/flutter/engine/pull/34408#discussion_r922586961

**Comment by flar** [comment]
Additionally, with regard to the Skpath copy constructor efficiency, here is the Skia documentation for the copy constructor:

https://api.skia.org/classSkPath.html#aa30a9363d49c092958d48e30608df367

**Comment by cyanglaz** [comment]
Fixed in https://github.com/flutter/engine/pull/34944
