### ISSUE TITLE
Failed assertion: line 243 pos 14: 'notification.metrics.axis == widget.axis': is not true.

### ISSUE THREAD

**Issue by rahulsharmadev-community** [flutter/flutter#107772]
Performing hot restart...
Syncing files to device sdk gphone64 x86 64...

======== Exception caught by animation library =====================================================
The following assertion was thrown while notifying listeners for AnimationController:
'package:flutter/src/widgets/overscroll_indicator.dart': Failed assertion: line 243 pos 14: 'notification.metrics.axis == widget.axis': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      _GlowingOverscrollIndicatorState._handleScrollNotification (package:flutter/src/widgets/overscroll_indicator.dart:243:14)
#3      _NotificationElement.onNotification (package:flutter/src/widgets/notification_listener.dart:130:38)
#4      _NotificationNode.dispatchNotification (package:flutter/src/widgets/framework.dart:3078:18)
#5      _NotificationNode.dispatchNotification (package:flutter/src/widgets/framework.dart:3081:13)
#6      _NotificationNode.dispatchNotification (package:flutter/src/widgets/framework.dart:3081:13)
#7      _NotificationNode.dispatchNotification (package:flutter/src/widgets/framework.dart:3081:13)
#8      _NotificationNode.dispatchNotification (package:flutter/src/widgets/framework.dart:3081:13)
#9      Element.dispatchNotification (package:flutter/src/widgets/framework.dart:4375:24)
#10     Notification.dispatch (package:flutter/src/widgets/notification_listener.dart:60:13)
#11     BallisticScrollActivity.dispatchOverscrollNotification (package:flutter/src/widgets/scroll_activity.dart:575:108)
#12     ScrollPosition.didOverscrollBy (package:flutter/src/widgets/scroll_position.dart:918:15)
#13     ScrollPosition.setPixels (package:flutter/src/widgets/scroll_position.dart:282:9)
#14     ScrollPositionWithSingleContext.setPixels (package:flutter/src/widgets/scroll_position_with_single_context.dart:82:18)
#15     BallisticScrollActivity.applyMoveTo (package:flutter/src/widgets/scroll_activity.dart:566:21)
#16     BallisticScrollActivity._tick (package:flutter/src/widgets/scroll_activity.dart:553:10)
#17     AnimationLocalListenersMixin.notifyListeners (package:flutter/src/animation/listener_helpers.dart:155:19)
#18     AnimationController._tick (package:flutter/src/animation/animation_controller.dart:830:5)
#19     Ticker._tick (package:flutter/src/scheduler/ticker.dart:238:12)
#20     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1146:15)
#21     SchedulerBinding.handleBeginFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:1059:11)
#22     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:614:13)
#23     SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:1057:17)
#24     SchedulerBinding._handleBeginFrame (package:flutter/src/scheduler/binding.dart:976:5)
#28     _invoke1 (dart:ui/hooks.dart:170:10)
#29     PlatformDispatcher._beginFrame (dart:ui/platform_dispatcher.dart:286:5)
#30     _beginFrame (dart:ui/hooks.dart:104:31)
(elided 5 frames from class _AssertionError and dart:async)
The AnimationController notifying listeners was: AnimationController#749de(▶ 702.127; for BallisticScrollActivity)

**Comment by huycozy** [comment]
Hi @rahulsharmadev-community, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this. Also, please provide the output of `flutter doctor -v` as well.
Thank you!

**Comment by MatteoAntolini** [comment]
The problem is an overscroll of a horizontal `ListView` inside another `ListView`

To replicate: 
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Builder(builder: (context) {
          return ListView(
            shrinkWrap: true,
            children: [
              Container(
                height: 50,
                child: ListView(
                  scrollDirection: Axis.horizontal,
                  children: List.generate(
                      20,
                      (index) => Container(
                            padding: EdgeInsets.all(8),
                            height: 50,
                            width: 50,
                            child: Text(index.toString()),
                          )),
                ),
              ),
            ],
          );
        }),
      ),
    );
  }
}
```

The workaround is to set `shrinkWrap` to `false`

**Comment by ThomasKozsir** [comment]
I had the same problem and found the solution from here solving the problem:
https://www.flutterforum.org/d/1296-notification-metrics-axis-widget-axis-is-not-true

In short:
Add a physics: BouncingScrollPhysics to your scrollable widget, in your case the ListView.

**Comment by iliyami** [comment]
@ThomasKozsir Why will this fix the issue? Do you have any idea? Thanks for your time.

**Comment by pritimoyp** [comment]
If you need another physic like PageScrollPhysics() then just put BouncingScrollPhysice as a parent.
Ex:  physics: const PageScrollPhysics(
                                  parent: BouncingScrollPhysics()),
