### ISSUE TITLE
Possibility of automatically parallelizing Dart code to speed up by 31-44% using the approach described in OSDI'21 paper?

### ISSUE THREAD

**Issue by fzyzcjy** [flutter/flutter#107794]
## Use case

When reading OSDI'21 papers (https://www.usenix.org/system/files/osdi21_full_proceedings_interior.pdf), there is a paper named *Horcrux: Automatic JavaScript Parallelism for Resource-Efficient Web Computation* (paper pdf download: https://www.usenix.org/system/files/osdi21-mardani.pdf), talking about how they *parallelize* the JavaScript code execution and speed up.

If I understand correctly, they find out an approach to knowing the dependency of js functions, and then run some functions in web-worker (i.e. extra threads) by passing data needed to the new thread, computing them, and passing back.

I know Dart uses isolate, meaning that no two threads share any data. However, IMHO the paper discusses how they does with JavaScript - js also only has one main thread, and have to use message-passing to transfer data from/to a web-worker (i.e. another thread). So Dart can mimic the JS case.

If working on Dart, IMHO it will be much easier to implement and even gain more performance boost. It is because Dart is a statically strongly typed language, while JavaScript is so dynamic - they even have to use concolic execution to know what state a function needs, while with Dart it is so trivial. And we can do whatever change we want to the Dart compiler etc, while the paper focuses on not changing the browser (and surely cannot change the browser).

I am willing to contribute and discuss :)

## Proposal

See above.

**Comment by danagbemava-nc** [comment]
Hi @fzyzcjy, this seems like a discussion for [the dart repo](https://github.com/dart-lang/sdk/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc). 

Kindly file this issue over there. 

I'll be closing this issue for now since this discussion seems better suited to the dart repo. 

Thank you

**Comment by fzyzcjy** [comment]
Thank you. I post it again here: https://github.com/dart-lang/sdk/issues/49468
