### ISSUE TITLE
Real time function(class) editor.

### ISSUE THREAD

**Issue by flavio7co** [flutter/flutter#107778]
I would like to use a textField to edit an imported dart file (function or class) on real time in an application (would be a didatic application). Is this possible? 

Thank you very much!!

**Comment by maheshmnj** [comment]
Hi @flavio7co, I am not sure what your use case is, But perhaps you can definitely edit code in flutter's textfield, See https://pub.dev/packages/code_text_field for inspiration.

Closing as this is not really a bug nor a feature request.

**Comment by flavio7co** [comment]
Thank's a lot. ^^
