### ISSUE TITLE
SliverPersistentHeader overlaps content

### ISSUE THREAD

**Issue by git-xiaocao** [flutter/flutter#107714]
```dart
Scaffold
  appbar: AppBar(...)
  body: NestedScrollView
      headerSliverBuilder => [
           SliverToBoxAdapter(...),
           SliverToBoxAdapter(...),
           SliverPersistentHeader(pinned: true, ... TabBar)
       ]
    body: Column(...)
```

I need the content in `Column` not to overlap with `TabBar`

https://user-images.githubusercontent.com/76673990/179213536-9dce49ad-cc3f-4aef-be41-1b087c3916c9.mp4

**Comment by huycozy** [comment]
Hi @git-xiaocao, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this. Also, please provide the output of `flutter doctor -v` as well.
Thank you!
