### ISSUE TITLE
Provision two linux testbeds with samsung a02

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#107758]
This is to support benchmark tests on low end devices for regression check.

/cc @iskakaushik

**Comment by keyonghan** [comment]
Progress:

- [x] Provision a new intel nuc with ubuntu image, and get salt setup
- [ ] setup dns for remote connection
- [ ] setup samsung a02 device (blocked on Verizon account setup)

**Comment by yusuf-goog** [comment]
Two A02s devices have been setup. One connected to linux-27, and processing jobs.

**Comment by godofredoc** [comment]
This is complete.
