### ISSUE TITLE
How to force update PlatformView?

### ISSUE THREAD

**Issue by JarvanMo** [flutter/flutter#107781]
Currently, I'm working on integrating ArcGIS Map view with PlatformView. In some cases, I need send commands to native code by method channel on Android side. When the native code receive these commands，mapview will add some markers and lines. The problem is even I've already add markers correctly on Android side, flutter still doesn't display those ui updates until I scroll the PlatformView. Is there anything I can do to let PlatformView force update the UI?

**Comment by maheshmnj** [comment]
Hi @JarvanMo, Thanks for filing the issue. Perhaps your code is right and it is an issue with Platform view, I think the issue you are referring to is the same as  https://github.com/flutter/flutter/issues/103686, I would suggest following up on that issue for further updates and Closing this issue as a duplicate.

If you disagree feel free to write in the comments and we will reopen it.

Thank you.
