### ISSUE TITLE
Android system font style changes

### ISSUE THREAD

**Issue by kutian** [flutter/flutter#107719]
Our online application is going to follow the Android system font style changes. Is there any way for flutter to respond?

**Comment by maheshmnj** [comment]
Hi @kutian, If I understand it right you want to use the system fonts in your flutter app is that correct? If so this is currently not possible, But one possible solution is to use [platform views ](https://docs.flutter.dev/development/platform-integration/android/platform-views) and use them as a widget.

Closing as this is not really a bug nor a feature request.
