### ISSUE TITLE
Consider avoiding padding the size of the raster cache image if they are just slightly larger than a pixel

### ISSUE THREAD

**Issue by ColdPaleLight** [flutter/flutter#107895]
Consider avoiding padding the size of the cache image when the actual floating point size is not enough larger than an integer to actually capture any rendering past the pixel boundary.

Currently we use the following code to calculate the size of the cache image. But due to the round-off error, the calculated size may be one pixel larger than we expected.
``` c++
  SkRect dest_rect =
      RasterCacheUtil::GetDeviceBounds(context.logical_rect, context.matrix);
  // we always round out here so that the texture is integer sized.
  int width = SkScalarCeilToInt(dest_rect.width());
  int height = SkScalarCeilToInt(dest_rect.height());

  const SkImageInfo image_info = SkImageInfo::MakeN32Premul(
      width, height, sk_ref_sp(context.dst_color_space));
```
c.f. 
https://github.com/flutter/engine/blob/0f83a6fbc4436a0ff7a57de5454ff8229eeb9c1e/flow/raster_cache.cc#L71-L72

here is an example:
the `height` of `dest_rect` is `1890`, but its hex value is `0x1.d88002p+10`, so the `height` of the` image` calculated by `SkScalarCeilToInt(dest_rect.height())` is `1891`
c.f.
https://github.com/flutter/engine/pull/34660#issuecomment-1185270432

## potential solution
Something like "ceil(width - epsilon)" would solve this issue
origin comment
https://github.com/flutter/engine/pull/34660#issuecomment-1185768166

**Comment by Hixie** [comment]
The raster cache is a legacy feature at this point (no plans on adding it to impeller) so I'm going to close this.
