### ISSUE TITLE
Flutter version on Flutter Doctor

### ISSUE THREAD

**Issue by Solido** [flutter/flutter#10788]
When using Flutter Doctor command I've the precise revision but there's no human readable informations. 

[✓] Flutter (on Mac OS X 10.12.5 16F73, locale en-FR, channel master)
Flutter at /Users/robbie/Install/flutter
Framework revision 3db402ec98 (11 hours ago), 2017-06-15 23:01:25 -0700
Engine revision f741647d49
Tools Dart version 1.24.0-dev.6.7

@sethladd follow-up of the discussion

**Comment by eseidelGoogle** [comment]
I believe this flutter doctor stuff was written before we had the concept of a flutter version number.  We do now, and could show that.

**Comment by sethladd** [comment]
Thanks for the report!

**Comment by Hixie** [comment]
Fixed.
