### ISSUE TITLE
Regression in hotReloadDevFSSyncMilliseconds

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#107845]
On the change here https://github.com/flutter/flutter/pull/107617, SkiaPerf is reporting a regression in hotReloadDevFSSyncMilliseconds: https://flutter-flutter-perf.skia.org/e/?begin=1657909086&end=1657930327&keys=Xcafc8d4bc6b7c42aa4e266575cbf4916&num_commits=50&request_type=1&xbaroffset=29895

@chingjun @christopherfujino

**Comment by christopherfujino** [comment]
The change was reverted and it looks like the benchmark has returned: https://flutter-flutter-perf.skia.org/e/?begin=1657909086&keys=Xcafc8d4bc6b7c42aa4e266575cbf4916&num_commits=50&request_type=1&xbaroffset=29895
