### ISSUE TITLE
[webview_flutter_web] NavigationDelegate Support

### ISSUE THREAD

**Issue by chillbrodev** [flutter/flutter#107877]
## Use case
Hello Flutter Devs, I am asking for NavigationDelegate support to the new webview_flutter_web package. It is great that this package exists but it is lacking a crucial feature. I need to be able to use WebViews on Flutter Web. Currently I am investigating other packages but none have NavigationDelegate support

## Proposal
Include support for NavigationDelegate to webview_flutter_web similar to webview_flutter.

**Comment by stuartmorgan** [comment]
Full NavigationDelegate support is impossible to implement via `iframe`. Could you elaborate on the specific use case, so we can determine whether it's something that could be supported?

**Comment by chillbrodev** [comment]
I have additional information to provide. These URLs are triggered via protocols such as `protocol://load?...` I basically need a way to register a function to intercept these protocols. I've come across errors such as:
```
Not allowed to launch 'protocol://load?metadata=...' because a user gesture is required.
```
or 
```
Not allowed to launch 'protocol://connect/loaded?metadata=...' because a user gesture is required.
```

**Comment by stuartmorgan** [comment]
> If you know of another way to "intercept" messages or urls via `iframe`

Do you control the source being loaded into the iframe? If not, this isn't going to be possible.

**Comment by chillbrodev** [comment]
> > If you know of another way to "intercept" messages or urls via `iframe`
> 
> Do you control the source being loaded into the iframe? If not, this isn't going to be possible.

@stuartmorgan When you mention `source`, are you talking about the URL or JS content being loaded into the `iframe`? If so, then I do control the URL/JS Script being loaded into the `iframe`. Otherwise if you are talking about the source that the URL points to then no I do not control that.

**Comment by stuartmorgan** [comment]
The latter. Because the implementation of `webview_flutter_web` is based on an iframe, anything being done with that content is subject to the same-origin policy, which severely limits what is possible unless you control the content that is being displayed.

**Comment by chillbrodev** [comment]
@stuartmorgan Through a combination of reviewing my 3rd party partners docs and use of the [WebViewX](https://pub.dev/packages/webviewx) Package, I was able to load my own html + iframe and use injected JS with DartCallbacks to get a solution that works. Essentially my 3rd party partner uses `postMessage` so I added an event listener which calls back to my Dart code with the events and I can process them as needed. I also use the `callJSMethod` from WebviewX to call JS functions that I loaded. 

It would be great to see Flutter add support to the new package similar to WebviewX to allow JS injection and DartCallbacks injection.  

I will work on producing a sample repo for you and others to review. 

Thanks for your time and for being responsive to this issue thread. I'll go ahead and close it now. I'll re-open it once I get a sample repo together.

**Comment by odunboye** [comment]
> @stuartmorgan Through a combination of reviewing my 3rd party partners docs and use of the [WebViewX](https://pub.dev/packages/webviewx) Package, I was able to load my own html + iframe and use injected JS with DartCallbacks to get a solution that works. Essentially my 3rd party partner uses `postMessage` so I added an event listener which calls back to my Dart code with the events and I can process them as needed. I also use the `callJSMethod` from WebviewX to call JS functions that I loaded.
> 
> It would be great to see Flutter add support to the new package similar to WebviewX to allow JS injection and DartCallbacks injection.
> 
> I will work on producing a sample repo for you and others to review.
> 
> Thanks for your time and for being responsive to this issue thread. I'll go ahead and close it now. I'll re-open it once I get a sample repo together.

@chillbrodev could you share a working example, thanks

**Comment by jeremiahlukus** [comment]
Yes please share an example i am trying to do the same exact thing.
