### ISSUE TITLE
Not clear how to "clean" my flutter project, and remove all generated/built artifacts

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#10783]
I tried to run `flutter clean` but that didn't work. I looked at `flutter --help` and I didn't see anything with the semantics of "clean up all the generated/built artifacts". Maybe I missed it?

**Comment by sethladd** [comment]
For now, the workaround seems to be `rm -rf build` in your Flutter project.

**Comment by goderbauer** [comment]
There is `flutter build clean` -- not very discoverable, though.

**Comment by sethladd** [comment]
Ah, thanks!

Consider this a request for "flutter clean" :)

**Comment by sethladd** [comment]
Just ran into this again. `flutter -h` doesn't tell me an obvious answer for how to clean out my project.

**Comment by sethladd** [comment]
cc @mit-mit

**Comment by mit-mit** [comment]
Thanks @goderbauer & @sethladd, always good when we can make things more discoverable!

**Comment by deepak-gehlot** [comment]
When i run flutter clean command, i face this issue.

Deleting 'build\'.
FileSystemException: Deletion failed, path = 'build' (OS Error: The system cannot find the path specified.
, errno = 3)

**Comment by mit-mit** [comment]
@deepak-gehlot, can you open a new bug please for that issue? And please include the output of `flutter doctor` in the bug.

**Comment by deepak-gehlot** [comment]
#14067

**Comment by Allan-Nava** [comment]
> There is `flutter build clean` -- not very discoverable, though.

It works for this error: 
```
ion -Xlinker -dependency_info -Xlinker /Users/ies/Library/Developer/Xcode/DerivedData/Runner-apffkuoylfsqdqazxdmhgktnzyay/Build/Intermediates.noindex/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/Runner.build/Release-iphoneos/OneSignalNotificationServiceExtension.build/Objects-normal/armv7/OneSignalNotificationServiceExtension_dependency_info.dat -o /Users/ies/Library/Developer/Xcode/DerivedData/Runner-apffkuoylfsqdqazxdmhgktnzyay/Build/Intermediates.noindex/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/Runner.build/Release-iphoneos/OneSignalNotificationServiceExtension.build/Objects-normal/armv7/OneSignalNotificationServiceExtension

ld: library not found for -lvideo_player
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
?

**Comment by aeonoftime** [comment]
Had the same issue on windows using VS Code. Once I closed the IDE and ran the clean from the command line it clean and I was able to relaunch the ide to get a successful build.

**Comment by luckymehndiratta** [comment]
Run Flutter Clean but same issue still there 
every time get the same data even I change the sign in ID
