### ISSUE TITLE
[go_router] Observe the path change for the analytics

### ISSUE THREAD

**Issue by rulim34** [flutter/flutter#107879]
My app is using GoRouter with [nested navigation on the NavigationBar](https://github.com/KweeksNews/kweeksnews_app/blob/develop/lib/core/widgets/navbar.dart).

To avoid jarring transition, I'm using the [same ValueKey for all of the NavigationBar's MaterialPage](https://github.com/KweeksNews/kweeksnews_app/blob/develop/lib/core/router/root_router.dart).

Now when I'm trying to implement firebase analytics using NavigatorObserver, none of the didPush, didReplace, or didPop method is called when I switched from one NavigationBar destination to other (eg. from Home to Search). I guess this is because the MaterialPage is using a same ValueKey.

So how can I observe the path change for the analytics?

[This is the current implementation (WIP)](https://github.com/KweeksNews/kweeksnews_app/commit/36cee7e7975604ba7872044e0d4b333675dca660).

**Comment by maheshmnj** [comment]
@rulim34  You can extending from Navigatorobserver and listen the route changes in the overridden methods, complete code sample here https://github.com/csells/go_router/blob/main/go_router/example/lib/nav_observer.dart 

<details>
<summary>code sample</summary>

```dart
 final router = GoRouter(
    observers: [MyNavObserver()],
    routes: [
     ...
   ]
)
...
...

class MyNavObserver extends NavigatorObserver {
  MyNavObserver() {}

  @override
  void didPush(Route<dynamic> route, Route<dynamic>? previousRoute) =>
      print('didPush: ${route.str}, previousRoute= ${previousRoute?.str}');

  @override
  void didPop(Route<dynamic> route, Route<dynamic>? previousRoute) =>
      print('didPop: ${route.str}, previousRoute= ${previousRoute?.str}');

  @override
  void didRemove(Route<dynamic> route, Route<dynamic>? previousRoute) =>
      print('didRemove: ${route.str}, previousRoute= ${previousRoute?.str}');

  @override
  void didReplace({Route<dynamic>? newRoute, Route<dynamic>? oldRoute}) =>
      print('didReplace: new= ${newRoute?.str}, old= ${oldRoute?.str}');

  @override
  void didStartUserGesture(
    Route<dynamic> route,
    Route<dynamic>? previousRoute,
  ) =>
      print('didStartUserGesture: ${route.str}, '
          'previousRoute= ${previousRoute?.str}');

  @override
  void didStopUserGesture() => print('didStopUserGesture');
}

extension on Route<dynamic> {
  String get str => 'route(${settings.name}: ${settings.arguments})';
}


```
</detals>

Cloasing as this is neither a bug nor a feature request.

**Comment by thorgexyz** [comment]
Would be good if settings.name returns the name property of a go_route? @maheshmnj

**Comment by zmoshansky** [comment]
I can confirm this suggestion is working for me. But also, if you're looking for FirebaseAnalytics logging, they have an Observer...

```
import 'package:go_router/go_router.dart';
import 'package:firebase_analytics/firebase_analytics.dart';
...

observers: [
  FirebaseAnalyticsObserver(analytics: FirebaseAnalytics.instance)
],
```
