### ISSUE TITLE
Flutter web app not working after deploy release

### ISSUE THREAD

**Issue by alex9153** [flutter/flutter#107803]
"Uncaught Bad state: Cannot add new events after calling close"

This error happens repetitively after submitting files to hosting.
At localhost all works fine. 
How to debug and catch this error?

**Comment by alex9153** [comment]
Uncaught SyntaxError: Unexpected token '<'
(index):54 Uncaught ReferenceError: _flutter is not defined
    at (index):54:7
manifest.json:1 Manifest: Line: 1, column: 1, Syntax error.

**Comment by huycozy** [comment]
Hi @alex9153, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this. Also, please provide the output of `flutter doctor -v` as well.
Thank you!

**Comment by renittobb** [comment]
Hi Getting the Same for me during release only. 

1. working fine while running locally
2. working fine while running on a local server (on python / Nginx server etc).
3. working fine even on firebase hosting.

When trying to deploy it as a containerized application on AWS and getting the following response

`GET https://qas1.bigbasket.com/flutter.js net::ERR_ABORTED 404
(index):46 Uncaught ReferenceError: _flutter is not defined
    at (index):46:7
(anonymous) @ (index):46
load (async)
(anonymous) @ (index):44
manifest.json:1          GET https://qas1.bigbasket.com/manifest.json 404
manifest.json:2 Manifest: Line: 2, column: 1, Syntax error.`
