### ISSUE TITLE
Make a benchmark to look at  how much time we spend creating raster cache IDs/items/entries

### ISSUE THREAD

**Issue by ColdPaleLight** [flutter/flutter#107811]
We should have a benchmark that looks at how much time we spend creating the raster cache IDs, raster cache items, raster cache entries, etc. so that as we make raster cache mechanism more complicated we don't start adding visible overhead?

origin comment
https://github.com/flutter/engine/pull/32676#issuecomment-1186045553

**Comment by jonahwilliams** [comment]
We're removing the raster cache long term, closing as obsolete
