### ISSUE TITLE
UnsupportedError RenderSliverFixedExtentBoxAdaptor.getMinChildIndexForScrollOffset

### ISSUE THREAD

**Issue by zjrwdl** [flutter/flutter#107893]
<img width="1233" alt="image" src="https://user-images.githubusercontent.com/6874049/179657637-0c62f015-d1d3-4265-99ba-128c165e89c5.png">

<img width="822" alt="image" src="https://user-images.githubusercontent.com/6874049/179657853-b4db2228-1178-408c-8c44-b6594609a40a.png">

from this stack we can not detect which app page encounters the error. so we guess may be there is any issue with framework?

flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.8.0, on macOS 11.6 20G165 darwin-x64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] Connected device (3 available)

**Comment by danagbemava-nc** [comment]
Hi @zjrwdl, what devices are you experienced this issue on?

**Comment by zjrwdl** [comment]
> Hi @zjrwdl, what devices are you experienced this issue on?

<img width="186" alt="image" src="https://user-images.githubusercontent.com/6874049/180146701-11d7648c-7cba-48ea-985c-632e9786229c.png">
<img width="171" alt="image" src="https://user-images.githubusercontent.com/6874049/180146783-0ed182bc-5686-4a8e-aeac-dc4f97773189.png">

**Comment by danagbemava-nc** [comment]
H @zjrwdl, seeing as you're on an older version of flutter, there's a chance this issue has already been fixed in the newer versions. 

Can you upgrade to the latest version of flutter to see if you still experience this issue?

Thank you

**Comment by zjrwdl** [comment]
> H @zjrwdl, seeing as you're on an older version of flutter, there's a chance this issue has already been fixed in the newer versions.
> 
> Can you upgrade to the latest version of flutter to see if you still experience this issue?
> 
> Thank you

which version? is this issule fixed in flutter 3.0.1?

**Comment by danagbemava-nc** [comment]
Hi @zjrwdl, the latest version of stable is 3.0.5. 

Given that there is no reproducible sample and steps to reproduce, it'll be difficult to say if it has been fixed or not. 

Kindly upgrade and let us know whether or not it still reproduces for you. 

Thank you

**Comment by zjrwdl** [comment]
> Hi @zjrwdl, the latest version of stable is 3.0.5.
> 
> Given that there is no reproducible sample and steps to reproduce, it'll be difficult to say if it has been fixed or not.
> 
> Kindly upgrade and let us know whether or not it still reproduces for you.
> 
> Thank you

after we upgrade 3.0.5 and get conclusion ,i will response to you.
thanks

**Comment by danagbemava-nc** [comment]
Thanks, will be awaiting your response
