### ISSUE TITLE
_CastError ScrollPosition.didUpdateScrollPositionBy

### ISSUE THREAD

**Issue by zjrwdl** [flutter/flutter#107890]
<img width="957" alt="image" src="https://user-images.githubusercontent.com/6874049/179655203-7514b535-9734-4ab4-a3d6-02ce7617a01d.png">
<img width="1063" alt="image" src="https://user-images.githubusercontent.com/6874049/179655235-1c097783-9cd8-4c71-ae2b-2148481cc45f.png">

from this stack we can not detect which app page encount error. so we guess may be there is any issue with framework?

flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.8.0, on macOS 11.6 20G165 darwin-x64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] Connected device (3 available)

**Comment by huycozy** [comment]
Hi @zjrwdl
Is this issue reproducible locally? If so, can you please share the output of `flutter run -v` and a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?

As far as I can see, you are using the old Flutter version `2.8.0`, the latest Flutter stable is `3.0.5` and the master is `3.1.0`. Please also try upgrading them and retry to see if this issue still reproduces.

**Comment by zjrwdl** [comment]
> Hi @zjrwdl Is this issue reproducible locally? If so, can you please share the output of `flutter run -v` and a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
> 
> As far as I can see, you are using the old Flutter version `2.8.0`, the latest Flutter stable is `3.0.5` and the master is `3.1.0`. Please also try upgrading them and retry to see if this issue still reproduces.

sorry, we can not reproduce this issule locally.
we have upgrade flutter engine to 3.0.1 for our app which will be published in nex month until which  time we may confirm if this issule has been fixed.
thanks

**Comment by huycozy** [comment]
Hey @zjrwdl, could you provide full crash log (see hint `flutter_error_details` from your screenshot) and list of affected devices? 
(The log should be in the text format instead of a screenshot for better investigation)

**Comment by huycozy** [comment]
Hi @zjrwdl
The information from the log above is not enough to investigate the issue. Do you see this issue when try running the project with `release` mode?
