### ISSUE TITLE
Flutter version on docs.flutter.io

### ISSUE THREAD

**Issue by Solido** [flutter/flutter#10787]
Here is the documentation footer on docs.flutter.io 
It is the most recent but there's no human readable version to follow-up. 

`Flutter •  Dart • cc license • 2017-06-15 01:01 • 6f77b4a9a76e57c4e6d23e61ba59a0cdd80d22b7`

@sethladd Edit if required

**Comment by sethladd** [comment]
Thanks for the report!

@jcollins-g do we need to do something special, or should dartdoc pick up the version as reported from the package ?

**Comment by jcollins-g** [comment]
@sethladd If the version field is defined in pubspec.yaml, dartdoc should do the right thing.
I'm noticing right now the generated pubspec.yaml from [here](https://github.com/flutter/flutter/blob/master/dev/tools/dartdoc.dart#L32) doesn't do that.

**Comment by sethladd** [comment]
Ah, thanks! Really appreciate it.
