### ISSUE TITLE
When developing on the flutter tool, no apparent way to ask gradle "don't rebuild the snapshot", to avoid the multi-second snapshot rebuild

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#10785]
When running the flutter tool, it calls to gradle, which then takes a snapshot of the flutter tool (a multi-second operation).

When developing on the flutter tool, that snapshot generation is unnecessary.

It would be really cool if there was a way to say/configure "don't generate a snapshot, just run the source", to speed up development of the flutter tool.

Meanwhile, the workaround is: `rm $FLUTTER_HOME/bin/cache/flutter_tools.stamp` before you re-run your flutter tool during development of the flutter tool itself.

**Comment by Hixie** [comment]
I don't understand what you mean about gradle. We build the tool once, when you run the tool. Then if gradle shells out to us again it should just be using the prebuilt version, unless you're starting it in a weird way.

**Comment by Hixie** [comment]
The rest of what you describe is working as intended. If you are developing on the tool, you must either delete the pre-built version, delete the stamp for the prebuilt version -- that's what you describe above -- or change the hash of the latest commit, by committing your code (or amending your existing commit).

**Comment by sethladd** [comment]
No worries, I suspect that most people aren't hacking on the flutter tools at a furious pace. :) With the workaround listed in this issue, I can close this. Thanks for taking a look.
