### ISSUE TITLE
Latest `markdown` breaks `flutter_markdown` tests

### ISSUE THREAD

**Issue by domesticmouse** [flutter/flutter#107871]
https://github.com/dart-lang/markdown/pull/428 breaks `flutter_markdown` tests in interesting ways. It looks like the non breaking spaces are bleeding through and breaking tests. However, when I add a filter to ignore said non breaking spaces to the test harness, it looks like the task list parsing is still broken.

Steps to reproduce:
1. Change `markdown` dependency to be latest `git` version
2. Run `flutter test`

Results:

```console
$ flutter test
00:03 +16: /Users/brettmorgan/Documents/GitHub/packages/packages/flutter_markdown/test/list_test.dart: Task List simple 2 item task list                                                
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure was thrown running a test:
Expected: 'Item 1'
  Actual: '​​Item 1'
   Which: is different.
          Expected: Item 1
            Actual: ​​Item 1
                    ^
           Differ at offset 0

When the exception was thrown, this was the stack:
#4      expectTextStrings (file:///Users/brettmorgan/Documents/GitHub/packages/packages/flutter_markdown/test/utils.dart:29:7)
#5      defineTests.<anonymous closure>.<anonymous closure> (file:///Users/brettmorgan/Documents/GitHub/packages/packages/flutter_markdown/test/list_test.dart:130:9)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)

This was caught by the test expectation on the following line:
  file:///Users/brettmorgan/Documents/GitHub/packages/packages/flutter_markdown/test/utils.dart line 29
The test description was:
  simple 2 item task list
════════════════════════════════════════════════════════════════════════════════════════════════════
00:03 +17 -1: /Users/brettmorgan/Documents/GitHub/packages/packages/flutter_markdown/test/list_test.dart: Task List simple 2 item task list [E]                                         
  Test failed. See exception logs above.
  The test description was: simple 2 item task list
  
00:03 +28 -1: /Users/brettmorgan/Documents/GitHub/packages/packages/flutter_markdown/test/list_test.dart: Task List custom checkbox builder                                             
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure was thrown running a test:
Expected: 'Item 1'
  Actual: '​​Item 1'
   Which: is different.
          Expected: Item 1
            Actual: ​​Item 1
                    ^
           Differ at offset 0

When the exception was thrown, this was the stack:
#4      expectTextStrings (file:///Users/brettmorgan/Documents/GitHub/packages/packages/flutter_markdown/test/utils.dart:29:7)
#5      defineTests.<anonymous closure>.<anonymous closure> (file:///Users/brettmorgan/Documents/GitHub/packages/packages/flutter_markdown/test/list_test.dart:178:9)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)

This was caught by the test expectation on the following line:
  file:///Users/brettmorgan/Documents/GitHub/packages/packages/flutter_markdown/test/utils.dart line 29
The test description was:
  custom checkbox builder
════════════════════════════════════════════════════════════════════════════════════════════════════
00:03 +28 -2: /Users/brettmorgan/Documents/GitHub/packages/packages/flutter_markdown/test/list_test.dart: Task List custom checkbox builder [E]                                         
  Test failed. See exception logs above.
  The test description was: custom checkbox builder
  
00:07 +314 ~5 -2: Some tests failed.                                                                                                                                                    
```

**Comment by srawlins** [comment]
Can you elaborate on what you mean by "add a filter to ignore said non breaking spaces to the test harness"?

**Comment by srawlins** [comment]
flutter_markdown has its own [TaskListSyntax](https://github.com/flutter/packages/blob/main/packages/flutter_markdown/lib/src/widget.dart#L548) which conflicts with (or perhaps... is straight up overridden by) makdown's new OrderedListWithCheckBoxSyntax and UnorderedListWithCheckBoxSyntax, which are part of `ExtensionSet.gitHubFlavored`. The easiest change we can make to flutter_markdown is probably to change the extension set used by flutter_markdown. Something like:

```dart
extensionSet: widget.extensionSet ?? ExtensionSet(
    List<BlockSyntax>.unmodifiable(
      <BlockSyntax>[
        const FencedCodeBlockSyntax(),
        const TableSyntax(),
        // Do not include `UnorderedListWithCheckBoxSyntax` or `OrderedListWithCheckBoxSyntax`,
        // as they conflict with `TaskListSyntax`.
      ],
    ),
    List<InlineSyntax>.unmodifiable(
      <InlineSyntax>[
        InlineHtmlSyntax(),
        StrikethroughSyntax(),
        AutolinkExtensionSyntax(),
      ],
    ),
  ),
```

It's not a great long-term fix, since this will not keep up with additions to `ExtensionSet.gitHubFlavored`. The better long-term fix is probably to:
* remove `TaskListSyntax` (as indicated by it's FIXME comment),
* use markdown's `UnorderedListWithCheckBoxSyntax` and `OrderedListWithCheckBoxSyntax`,
* check for those `indicatorForUncheckedCheckBox` and `indicatorForCheckedCheckBox` characters, and
* render to `Icons.check_box.codePoint` and `Icons.check_box_outline_blank.codePoint` like `TaskListSyntax` does today.

**Comment by domesticmouse** [comment]
> Can you elaborate on what you mean by "add a filter to ignore said non breaking spaces to the test harness"?

It was an exploration, but your comment is a better starting point.

**Comment by timmaffett** [comment]
I will take a stab at @srawlins 's suggested long term fix if no one has any objections/has already started on it.
I was unaware of the flutter_markdown alternate handling of checkboxes and I probably should have addressed this when i created https://github.com/dart-lang/markdown/pull/428

**Comment by domesticmouse** [comment]
> I will take a stab at @srawlins 's suggested long term fix if no one has any objections/has already started on it.
> 
> I was unaware of the flutter_markdown alternate handling of checkboxes and I probably should have addressed this when i created https://github.com/dart-lang/markdown/pull/428

Go for it. I'm happy to review.

**Comment by timmaffett** [comment]
I have submitted https://github.com/flutter/packages/pull/2338 which fixes this issue.   It ended up being a little simpler than @srawlins imagined.
