### ISSUE TITLE
☂️ Remove bitcode support on iOS

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#107887]
Apple is dropping support for bitcode submissions in Xcode 14/iOS 16. Remove it from Flutter.

- [x] https://github.com/flutter/flutter/issues/111776
- [x] https://github.com/flutter/flutter/issues/107883
- [x] https://github.com/flutter/flutter/pull/112900
- [x] https://github.com/flutter/flutter/issues/107884
- [x] https://github.com/flutter/flutter/issues/112896
- [x] https://github.com/flutter/flutter/issues/107886
- [x] https://github.com/flutter/flutter/issues/107885
- [x] https://github.com/flutter/flutter/issues/107888
- [x] https://github.com/flutter/flutter/issues/112994
- [ ] Archive https://github.com/flutter/flutter/wiki/Creating-an-iOS-Bitcode-enabled-app
- [x] Turn off bitcode in g3 apps - roller team says this is already off in g3, no bitcode usage
- [x] Add note to [add-to-app documentation](https://docs.flutter.dev/development/add-to-app/ios/project-setup) that Flutter no longer supports bitcode, and they need to turn it off in the host app. Scrub website for bitcode references https://github.com/flutter/website/pull/7623
- [x] Announce deprecation will happen in release blog post - https://medium.com/flutter/whats-new-in-flutter-3-3-893c7b9af1ff#04f3
- [ ] Announce deprecation has happened in release blog post when complete
- [ ] Tell fuschia team they can archive their bitcode-marker-aware toolchain linker.  It should not be removed until stable+1 so hotfixes will still build
- [x] Stop using the libcxx fork in the engine - https://github.com/flutter/engine/pull/36634

> Starting with Xcode 14, bitcode is no longer required for watchOS and tvOS applications, and the App Store no longer accepts bitcode submissions from Xcode 14.
> 
> Xcode no longer builds bitcode by default and generates a warning message if a project explicitly enables bitcode: “Building with bitcode is deprecated. Please update your project and/or target settings to disable bitcode.” The capability to build with bitcode will be removed in a future Xcode release. IPAs that contain bitcode will have the bitcode stripped before being submitted to the App Store. Debug symbols for past bitcode submissions remain available for download. (86118779)

https://developer.apple.com/documentation/xcode-release-notes/xcode-14-release-notes

Note Apple never used bitcode on macOS so this only impacts iOS.
See https://github.com/flutter/flutter/issues/15288 for breadcrumbs of what needs to be removed.

**Comment by jmagman** [comment]
@dnfield am I missing anything? Can any LTO logic also be removed?

**Comment by jmagman** [comment]
cc @mraleph

**Comment by dnfield** [comment]
This looks good to me

**Comment by jmagman** [comment]
The user-facing parts of this are done.  Flutter projects with bitcode on should now be off.  Flutter frameworks are no longer built with bitcode.  Some documentation has been updated to note that bitcode is no longer supported.

Goma has been turned on in the iOS framework engine builders and are now significantly faster.

Still need to move the roll scriptoff the `ios-release-nobitcode`, and announce this in the next release blog post.

**Comment by jmagman** [comment]
The code part of this is complete and will be available in the next stable, the rest is housekeeping.  Closing.
