### ISSUE TITLE
Stuck  when running on Android  devices 

### ISSUE THREAD

**Issue by abdalazeez1** [flutter/flutter#107896]
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
Installing build/app/outputs/flutter-apk/app.apk...
D/FlutterLocationService(12143): Creating service.
D/FlutterLocationService(12143): Binding to location service.
i used A50 samsung  Android 11

**Comment by huycozy** [comment]
Hi @abdalazeez1 , please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this. Also, please provide the output of `flutter doctor -v` as well.
Thank you!
