### ISSUE TITLE
Get device screen's corner radius

### ISSUE THREAD

**Issue by ercantomac** [flutter/flutter#107849]
## Use case

Some UI elements that are close to edges of the screen look ugly when element's border radius doesn't match device screen's corner radius. With Android 12, it's possible to get the corner radius of the device screen [with this API.](https://developer.android.com/guide/topics/ui/look-and-feel/rounded-corners)

## Proposal

We should be able to get this information. For example: by using something like `MediaQuery.of(context).screenCornerRadius`.

**Comment by danagbemava-nc** [comment]
Hi @ercantomac, there's an existing requesting this feature in https://github.com/flutter/flutter/issues/97349. 

Kindly follow up there for updates. 

Closing from here as duplicate. 

Thank you
