### ISSUE TITLE
[Impeller] Big regression in raster times

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#107846]
On both iOS and Android, raster times regressed for Impeller on a Skia roll: https://flutter-flutter-perf.skia.org/e/?begin=1657658524&end=1658159168&keys=Xedd663ae4d828fa68977161d36fcd4c5&requestType=0&xbaroffset=29897

**Comment by zanderso** [comment]
https://github.com/flutter/flutter/pull/107748 with Skia roll https://github.com/flutter/engine/pull/34695

**Comment by chinmaygarde** [comment]
This is a bit of a head scratcher. They only thing that Impeller uses Skia for is text layout and shaping. I'll bisect.

**Comment by zanderso** [comment]
Maybe https://skia.googlesource.com/skia.git/+/7d1636010a55664f54165fc6213a37e77609774f ?

**Comment by zanderso** [comment]
Looks like changes from https://github.com/flutter/flutter/pull/107894 recovered some of the performance:

https://flutter-flutter-perf.skia.org/e/?begin=1658181964&end=1658237168&keys=X2f010df8159ca4ec7c5bfd148c745223&num_commits=50&request_type=1&xbaroffset=29927

**Comment by jason-simmons** [comment]
Also confirmed that the recent decrease in rasterization time started with https://github.com/flutter/engine/commit/81e8abef5e7cbf51dcd6c05d2367aba5ce2b605f

**Comment by zanderso** [comment]
The benchmarks have recovered following the revert.
