### ISSUE TITLE
Make laying out screens sane

### ISSUE THREAD

**Issue by jjonte-vutrans** [flutter/flutter#107891]
## Use case

I want to put text boxes on the screen to gather user input.

The following code produces several layout exceptions.

```
return Scaffold(
        body:  Column(children: [
                Row(children: const [TextField()])
         ])
);
```

## Proposal

I think the Flutter team needs to try again on layouts. They're insane and holding the framework back. Try looking into "web development" and "HTML" - they're pretty great and have already solved this problem in a well-known way.

**Comment by Hixie** [comment]
@jjonte-vutrans Thanks for your contribution. Unfortunately this bug report is not actionable as written (and calling our work "insane" is rather insulting and a violation of our code of conduct) so I'm afraid I'm going to have to close it.

For what it's worth you may be interested in some of these resources:

* https://docs.flutter.dev/development/ui/layout
* https://docs.flutter.dev/development/ui/layout/box-constraints
* https://docs.flutter.dev/development/ui/layout/tutorial
* https://api.flutter.dev/flutter/widgets/Row-class.html
* https://api.flutter.dev/flutter/widgets/Column-class.html

In general, Flutter's layout system is entirely extensible so I would recommend creating a package with your own custom layout primitives if you don't like the defaulto nes -- unlike with HTML, there's not a fixed set of layout systems, it's just code, and you can create your own just like Row and Column and so forth. For example, here is the code that implements Row and Column:

   https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/rendering/flex.dart
   https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/basic.dart#L4318 

Good luck!
