### ISSUE TITLE
Error in CustomPainter docs: 'CustomPaint' instead of 'CustomPainter'

### ISSUE THREAD

**Issue by 0xba1** [flutter/flutter#107837]
Hi, while going through the code documentation of `CustomPainter`, I found an error in which `CustomPaint` was used instead of `CustomPainter` https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/rendering/custom_paint.dart#L29

Error: line 29, lib/src/rendering/custom_paint.dart

```
/// To implement a custom painter, either subclass or implement this interface
/// to define your custom paint delegate. [CustomPaint] subclasses must
/// implement the [paint] and [shouldRepaint] methods, and may optionally also...
```
Should be:
```
/// To implement a custom painter, either subclass or implement this interface
/// to define your custom paint delegate. [CustomPainter] subclasses must
/// implement the [paint] and [shouldRepaint] methods, and may optionally also...
```

**Comment by 0xba1** [comment]
Pull request: https://github.com/flutter/flutter/pull/107836

**Comment by danagbemava-nc** [comment]
#107836 has been merged. 

Closing as fixed.
