### ISSUE TITLE
flutter run builds the FLX twice

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#10781]
I'm starting to enhance our analytics, and I noticed that we're generating two 'flx' screens.

My debug output:

```
Running "flutter packages get" in myapp...
XXXX flx
XXXX flx
```

(The XXXX is my debug output)

Conclusion: we're building the FLX twice, when a user types `flutter run`, at least for Android.

**Comment by sethladd** [comment]
Confirmed, `flutter run` builds the FLX twice. Output from my local testing:

```
XXX Inside and running flx
Built /Users/sethladd/tmp/myapp/build/app/intermediates/flutter/debug/app.flx
XXX Inside and running flx
Built /Users/sethladd/tmp/myapp/build/app/intermediates/flutter/debug/app.flx
```

As reported from flx.dart's assemble().

**Comment by eseidelGoogle** [comment]
FYI @mravn-google @tvolkert

**Comment by tvolkert** [comment]
@jason-simmons discovered that it looks like the double build is intentional in order to speed up Gradle builds.  @mravn-google or @jakobr-google may know more.

**Comment by mravn-google** [comment]
This behavior is intentional:
https://github.com/flutter/flutter/issues/9717
https://github.com/flutter/flutter/pull/9801

I'll discuss with @jakobr-google if there is anything better we can do.

**Comment by mit-mit** [comment]
Closing as by-design. The customer observable thing we should be focused on is generally making the build faster, and that is tracked in https://github.com/flutter/flutter/issues/9897.
