### ISSUE TITLE
some devicelab win machines offline

### ISSUE THREAD

**Issue by yusuf-goog** [flutter/flutter#107872]

**Comment by yusuf-goog** [comment]
win-3 had windows update which needed the dialogs to be accepted.

win-3,4,6 had password for swarming account got changed to the alternate one. Changed it back to our flutter password and it works.

**Comment by keyonghan** [comment]
Seems win 3, 4, 6 are offline again.

**Comment by yusuf-goog** [comment]
possibly the password is being overwritten by the password stored in the salt state, which is different from our standard password thats been added to the local machine, causing it to not login automatically. 

Will try to remotely fix, or will look at it when I go into the lab tomorrow.

**Comment by yusuf-goog** [comment]
can ssh and vnc into win-3. 

Everything seems to be looking fine. Command prompt is showing swarming bot is started.

Swarming bot log extract here: https://paste.googleplex.com/6031265670103040

Seems to indicate it had issues contacting auth server?

**Comment by keyonghan** [comment]
@yusuf-goog what would be the next step here? Now 3 out of 4 are down in prod, and 1 out of 2 is down in staging.

**Comment by keyonghan** [comment]
Restart win3 and win4, and they are back.
win2 is not sshable though.

**Comment by yusuf-goog** [comment]
Maybe it needed some time. Win-2 is sshable now.

Logs from win-2 show problem renewing certs: https://paste.googleplex.com/5164869304188928

Reaching out to LUCI team for guidance.

**Comment by yusuf-goog** [comment]
Win-3 hit windows task scheduler error 2147943726, which is caused by a password change. Reset the password in task scheduler job properties and bot is back up.

**Comment by yusuf-goog** [comment]
win-4 and win-6, windows "require username/password option" under command `netplwiz` was reset and so needed login when the host was rebooted. Unchecked the box, entered password and bot is now up.

**Comment by yusuf-goog** [comment]
all windows hosts are back up.
