### ISSUE TITLE
Unable to archive my flutter app: Command PhaseScriptExecution failed with a nonzero exit code

### ISSUE THREAD

**Issue by MGTKenYCS** [flutter/flutter#107897]
Here is my `flutter doctor -v`
```
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.4 21F79 darwin-arm, locale zh-HK)
    • Flutter version 3.0.5 at /Users/user/flutter_2_3_05
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (5 days ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
    • Xcode at /Users/user/Desktop/Xcode/13/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] VS Code (version 1.69.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.44.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 103.0.5060.114

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.
```

I had tried a lot of different method from similar issues but none of them works for me, this makes me really confused, when I tried to use `flutter build ipa --verbose`
It comes with an error of
`Command PhaseScriptExecution failed with a nonzero exit code`
and I think it might be caused by this:
`Target release_unpack_ios failed: Exception: Binary`
But I'm not able to find any solution of this.

I've also tried downgrade my flutter version from 3.0.5 to 2.10 and flutter master and Xcode 13 or upgrade to Xcode 14, all those are able to run `flutter run` to build on simulator but none of them are able to run `flutter build ipa`

I've also tried to archive it using Xcode but it shows the same issue of `Command PhaseScriptExecution failed with a nonzero exit code`

Here is my Podfile:
[Podfile.txt](https://github.com/flutter/flutter/files/9137206/Podfile.txt)

Podfile.lock
[Podfile.lock.txt](https://github.com/flutter/flutter/files/9137211/Podfile.lock.txt)

Generated.xcconfig
[Generated.xcconfig.txt](https://github.com/flutter/flutter/files/9137226/Generated.xcconfig.txt)

Release.xcconfig
[Release.xcconfig.txt](https://github.com/flutter/flutter/files/9137228/Release.xcconfig.txt)

project.pbxproj
[project.pbxproj.txt](https://github.com/flutter/flutter/files/9137232/project.pbxproj.txt)

`flutter build ipa --verbose`
https://drive.google.com/file/d/1eS4uP5qpwWPSPM8gfMfacJ2qabvuZh4t/view?usp=sharing

Error from archive in Xcode
[xcode_archive.txt](https://github.com/flutter/flutter/files/9137347/xcode_archive.txt)

any suggestion?
Please help, and Thank you for spending time to understand my issue.

**Comment by exaby73** [comment]
Hello @MGTKenYCS. Have you tried the solution [here](https://stackoverflow.com/questions/49612211/codesign-error-with-flutter-on-ios)?

**Comment by MGTKenYCS** [comment]
@exaby73 Thank you for your help.

Yes, I tried, the error appear before the build folder appeared again, which mean the build folder did not show up but the error occurred.
the error is the same `Target release_unpack_ios failed: Exception: Binary`

when I run `flutter build ios`, the error switched to 
```
2022-07-20 09:44:46.711 xcodebuild[7073:25081] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionSentinelHostApplications for extension
    Xcode.DebuggerFoundation.AppExtensionHosts.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
    2022-07-20 09:44:46.711 xcodebuild[7073:25081] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionPointIdentifierToBundleIdentifier for extension
    Xcode.DebuggerFoundation.AppExtensionToBundleIdentifierMap.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
```

**Comment by exaby73** [comment]
Can you check this issue (https://github.com/flutter/flutter/issues/97659) as well. Seems to be very similar to yours. I believe you need to add the arm64 architecture in your xcode project

**Comment by MGTKenYCS** [comment]
Thank You!, I solved the problem by deleting code below inside `ios/Runner.xcodeproj/project.pbxproj`
```
EXCLUDED_ARCHS = arm64;
"EXCLUDED_ARCHS[sdk=iphonesimulator*]" = arm64;
```
and it works! 
Thank you very much!
