### ISSUE TITLE
tool thinks pub packages without a lib directory are always out of date

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#107957]
This logic is checking if `package.packageUriRoot` directory exists, so the `lib` directory.  

https://github.com/flutter/flutter/blob/ed3c32c9d2c27b6259b7226063317d07b85f2134/packages/flutter_tools/lib/src/flutter_cache.dart#L101

https://github.com/flutter/packages/pull/1951 removed this directory `flutter_template_images`

> Removes the empty Dart file, which used to be required by pub.dev checks but no longer is.

But because the `lib` doesn't exist, on every run it thinks the pub dependencies are out of date, and `pub get` needs to be run.

Either that directory is needed, or the tool needs to be updated.

See https://github.com/flutter/flutter/issues/107873#issuecomment-1189507243

**Comment by jmagman** [comment]
This is blocking https://github.com/flutter/flutter/issues/106110.

@stuartmorgan can you give some clarification about what the right way to fix this is?

**Comment by christopherfujino** [comment]
@Jasguerrero can you take a look at if there's a quick tool fix to this class we can make that will detect whether flutter_template_images is present locally without checking `package.packageUriRoot`?

If there isn't a quick tool fix, it sounds like we should re-add the dummy file and then track actually fixing this in the tool.

**Comment by jmagman** [comment]
> It's definitely out of sync with pub, which no longer requires a lib folder. 

@stuartmorgan do you have a link to when this change was done on the `pub` side, for reference?

Copied from https://github.com/flutter/flutter/pull/107873#issuecomment-1189515611

>> I'm not sure what that tool logic does exactly, but it shouldn't be assuming that _all_ packages have `lib` directories.
>
>This is the logic:
https://github.com/flutter/flutter/blob/ed3c32c9d2c27b6259b7226063317d07b85f2134/packages/flutter_tools/lib/src/flutter_cache.dart#L100-L104
>
>`package.packageUriRoot` is `lib` in this case.
><img width="786" alt="Screen Shot 2022-07-19 at 1 21 03 PM" src="https://user-images.githubusercontent.com/682784/179841103-77cb1168-dec5-456d-9089-e8ce762f7f33.png">
>
> Need some better way to check this then, I don't see anything else interesting in that package object.

**Comment by jmagman** [comment]
> goal of that check is just to answer the question "has something that looks like a package been copied to this location?", then checking for a `pubspec.yaml` file rather than a `lib/` directory seems like it would be more robust.

Agreed, I was just just looking at this but the `Package` API doesn't actually expose the pubspec `Uri`. A fallback to hardcode that as a fallback would probably always work in the tool, but it seems like `package_config` should handle this case, or expose more.  @Jasguerrero  If that's what we need, we should file an issue over there and either get the right people involved and/or send over a PR.

https://github.com/dart-lang/package_config/blob/cff98c90acc457a3b0750f0a7da0e351a35e5d0c/lib/src/package_config_impl.dart#L250-L252

**Comment by Jasguerrero** [comment]
> > @stuartmorgan do you have a link to when this change was done on the `pub` side, for reference?
> 
> I can't find the publish-side change, but it looks like it's been allowed for consuming since 2015: [dart-lang/pub#844](https://github.com/dart-lang/pub/issues/844) (I know the publish side was later than that).
> 
> If (and I want to stress that I **don't** know that this is the case, which is why I don't want to change this myself) the goal of that check is just to answer the question "has something that looks like a package been copied to this location?", then checking for a `pubspec.yaml` file rather than a `lib/` directory seems like it would be more robust.

According to the dart issue, the package could also be an asset (which I assume flutter_template_images is) we can fallback to either check for the lib/ or "see if it is an asset" which I am not familiar on what constitutes as an asset

**Comment by christopherfujino** [comment]
> > > @stuartmorgan do you have a link to when this change was done on the `pub` side, for reference?
> > 
> > 
> > I can't find the publish-side change, but it looks like it's been allowed for consuming since 2015: [dart-lang/pub#844](https://github.com/dart-lang/pub/issues/844) (I know the publish side was later than that).
> > If (and I want to stress that I **don't** know that this is the case, which is why I don't want to change this myself) the goal of that check is just to answer the question "has something that looks like a package been copied to this location?", then checking for a `pubspec.yaml` file rather than a `lib/` directory seems like it would be more robust.
> 
> According to the dart issue, the package could also be an asset (which I assume flutter_template_images is) we can fallback to either check for the lib/ or "see if it is an asset" which I am not familiar on what constitutes as an asset

Since we control our dependencies, I'm not so much concerned about supporting every possible valid package. I think checking for pubspec.yaml is a reasonable solution. The long-term fix should be deprecating this entire `PubDependencies` artifact.

**Comment by jmagman** [comment]
> Since we control our dependencies, I'm not so much concerned about supporting every possible valid package.

Good point. And our integration tests failed and caught this.

**Comment by Jasguerrero** [comment]
> I think checking for pubspec.yaml is a reasonable solution. The long-term fix should be deprecating this entire PubDependencies artifact.

Sounds good.

**Comment by Jasguerrero** [comment]
After just checking for the pubspec.yaml I am getting this error on the bots https://cirrus-ci.com/task/5298139090386944. @christopherfujino Do you think is related on skipping a flutter pub get (or even related to my change, here is the [PR](https://github.com/flutter/flutter/pull/107968))?

**Comment by christopherfujino** [comment]
> After just checking for the pubspec.yaml I am getting this error on the bots https://cirrus-ci.com/task/5298139090386944. @christopherfujino Do you think is related on skipping a flutter pub get (or even related to my change, here is the [PR](https://github.com/flutter/flutter/pull/107968))?

I'll comment on the PR

**Comment by jmagman** [comment]
Fixed by https://github.com/flutter/flutter/pull/107968.
