### ISSUE TITLE
[Proposal] Ability to have the system keyboard stripped to bare bones - no utility bar on top, no emoji keyboard 

### ISSUE THREAD

**Issue by johnnypcc** [flutter/flutter#107970]
![ipad keyboard](https://user-images.githubusercontent.com/69480535/179857777-8aa5b129-5639-4121-965a-81657857ee81.png)
![ios keyboard](https://user-images.githubusercontent.com/69480535/179857783-d5ee51b2-0ead-4162-9aad-b6afbbd74173.png)
![samsung keyboard](https://user-images.githubusercontent.com/69480535/179857790-21f9c4c4-e090-41aa-b3f4-18e972f7cfa8.jpeg)

**Comment by maheshmnj** [comment]
Hi @johnnypcc, Thanks for filing the issue. I am quite not sure if the native platforms expose any api for such customizations. I am labeling this issue for further insights from the team.

**Comment by hellohuanlin** [comment]
> I am quite not sure if the native platforms expose any api for such customizations. 

iOS keyboard should support hiding the emoji button by setting the [UIKeyboardType](https://developer.apple.com/documentation/uikit/uikeyboardtype) to `UIKeyboardTypeASCIICapable`

**Comment by huycozy** [comment]
As mentioned above, there is a new issue that proposes adding `UIKeyboardTypeASCIICapable` for text input on iOS: https://github.com/flutter/flutter/issues/127831

**Comment by hellohuanlin** [comment]
I think we can close it as duplicate now. The `UIKeyboardTypeASCIICapable` should remove things like emoji for you.
