### ISSUE TITLE
[Impeller] Don't use Skia's rect packer in Impeller for font-atlas generation in the SkParagraph backend.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#107959]
This is not in a public header and it's [performance characteristics](https://github.com/flutter/flutter/issues/107846) as well as API may change.

**Comment by jonahwilliams** [comment]
This was removed in https://github.com/flutter/engine/commit/b9860dcc8dddad71f2f2f60e93ea8ea56e48b3e2
