### ISSUE TITLE
[scheduler] Unacked messages and 500 errors on cocoon

### ISSUE THREAD

**Issue by yusuf-goog** [flutter/flutter#107961]
Project
[flutter-dashboard](https://console.cloud.google.com/?project=flutter-dashboard)

Policy
[[scheduler] Unacked requests](https://console.cloud.google.com/monitoring/alerting/policies/5806421347978844758?project=flutter-dashboard)

Condition
[scheduler] Unacked messages

Metric
pubsub.googleapis.com/subscription/num_undelivered_messages

**Comment by yusuf-goog** [comment]
A custom version of cocoon was deployed at 12pm, which coincides with the pubsub backlog event starting ~12:30pm. 

@keyonghan rolled back that version, which seems to have started the recovery on the `luci-postsubmit` and `scheduler-requests-sub` queues. 

The `luci-postsubmit` queue looks to have started growing again at ~1:05pm. And the `github-updater` queue kept growing till around 1:30pm, where it looks to have started a downward trend.

See: https://pantheon.corp.google.com/monitoring/alerting/policies/5806421347978844758?project=flutter-dashboard

https://screenshot.googleplex.com/3mrenyRap7feCUd.png

**Comment by yusuf-goog** [comment]
At about 1:35pm, the `github-updater` queue has started growing again.

**Comment by yusuf-goog** [comment]
Looks like the data being accessed (for the messages in the 500 error logs) needs to be base64 decoded: 

https://github.com/flutter/cocoon/blob/main/app_dart/lib/src/request_handlers/postsubmit_luci_subscription.dart#L69

@keyonghan did the change that got pushed out at 12pm start base 64 encoding the `user_data`?

**Comment by yusuf-goog** [comment]
500 error graph: https://screenshot.googleplex.com/3a39QJJiGpW7Kam.png

**Comment by keyonghan** [comment]
Most of 500 errors are related to closed PRs, like https://github.com/flutter/flutter/pull/107953.
I believe the issue is mitigated after we switched back the version.

**Comment by keyonghan** [comment]
A quick wrap up.

The issue is with an inconsistent `base64` encoded message: some are with encoded message, while others are strings without encoding.

Error messages:
```
FormatException: Unexpected character (at character 1)
eyJjb21taXRfa2V5IjoiZmx1dHRlci9mbHV0dGVyL21hc3Rlci9lZDNjMzJjOWQyYzI3YjYyNTl...
^

#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1383:5)
#1      _ChunkedJsonParser.parseNumber (dart:convert-patch/convert_patch.dart:1250:9)
#2      _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:915:22)
#3      _parseJson (dart:convert-patch/convert_patch.dart:35:10)
```

The issue has caused failures in three APIs affecting both presubmit and postsubmit scheduling:
- scheduling is broken
- post-submit task status update is broken
- pre-submit (github task) status update) is broken

**Fix**: 
- https://github.com/flutter/cocoon/pull/1992 (WIP)
- At the same time, we deployed a test version with the fixes, and it is working through.
- Now the dashboard is catching up with miss-scheduled builds

The root cause of the inconsistency needs a further investigation.

**Comment by yusuf-goog** [comment]
These alerts are now green, and the immediate issues have been mitigated. 

I'll open a bug to track:

* Investigation of the root cause of the different encoding schemes
* Mitigation of future instances where messages can be differently formatted.
