### ISSUE TITLE
RawAutocomplete with TextFormField does not allow user to enter text from soft keyboard on Android

### ISSUE THREAD

**Issue by BellRampion** [flutter/flutter#107969]
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. Click on the textfield
3. Try to enter text using the soft keyboard
4. Click on the "AAAAAAAAAAAAAAAA" suggestion
5. Delete all the characters
6. Attempt to type more characters

**Expected results:** 
Expected to be able to type characters without first selecting a suggestion.

**Actual results:** 
Cannot enter characters without first selecting a suggestion. Deleting all the characters after selecting a suggestion also prevents entering more characters until a new suggestion is selected. 

The Debug Console shows this error every time a key is pressed: 
I/TextInputPlugin(15340): Composing region changed by the framework. Restarting the input method.

<details>
<summary>Code sample</summary>

https://github.com/BellRampion/TextField-RawAutocomplete-issue/blob/main/lib/error_page.dart

</details>

<details>
  <summary>Logs</summary>

```
```

```
Analyzing sample_project...                                             
No issues found! (ran in 2.3s)
```

```
[√] Flutter (Channel stable, 3.0.3, on Microsoft Windows [Version 10.0.19044.1766], locale en-US)
    • Flutter version 3.0.3 at C:\Users\blivingston\Documents\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 676cefaaff (4 weeks ago), 2022-06-22 11:34:49 -0700
    • Engine revision ffe7b86a1e
    • Dart version 2.17.5
    • DevTools version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\blivingston\AppData\Local\Android\sdk
    • Platform android-33, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

    • VS Code at C:\Users\blivingston\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.44.0

[√] Connected device (3 available)
    • moto x4 (mobile)  • ZY224MXXH9 • android-arm64  • Android 9 (API 28)
    • Windows (desktop) • windows    • windows-x64    • Microsoft Windows [Version 10.0.19044.1766]

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @BellRampion, the issue you're facing is due to you calling `onFieldSubmitted` in the `onChanged` property of your `TextField`. 

If you remove that method call from `onChanged`, this works as expected. 

See https://api.flutter.dev/flutter/widgets/RawAutocomplete-class.html for an example of how to use the `RawAutoComplete`. 

I'll be closing this as it is an implementation issue. 

Thank you

**Comment by BellRampion** [comment]
Thank you! I misread the docs and thought it was called in onChanged instead of onFieldSubmitted.
