### ISSUE TITLE
Allow adb to interact with the app during flutter integration tests

### ISSUE THREAD

**Issue by HelioStrike** [flutter/flutter#107934]
## Use case

We want to test platform views (including webviews) in our flutter integrations tests. Flutter integration tests currently don't support this. To workaround this, we'd like to use adb to interact with the app. For adb to be able to interact with the app during the test, we need to set [`pointerEventSource`](https://github.com/flutter/flutter/blob/d8b9d5d1c784bc8fc7b1d21c66b3447a2ec76d12/packages/flutter_test/lib/src/binding.dart#L498) to `TestBindingEventSource.test`.

Unfortunately, flutter_test doesn't seem to support setting `pointerEventSource` yet... I think we can create a setter for it, or make `withPointerEventSource`. Thanks!

**Comment by maheshmnj** [comment]
Hi @HelioStrike, Thanks for filing the issue. If I understand it right this is an android only feature?

**Comment by HelioStrike** [comment]
@maheshmnj Hey Mahesh! Yup, our usecase is android only for now.
