### ISSUE TITLE
Too many commits batched on framework CI

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#107989]
<img width="1671" alt="Screen Shot 2022-07-19 at 9 54 18 PM" src="https://user-images.githubusercontent.com/6343103/179900046-979839cf-be1b-4424-924d-15ce2129b7f7.png">

When too many commits are batched like this, we have a big gap in our benchmarking data, and regressions require a lot more manual effort to pin down.

**Comment by zanderso** [comment]
@keyonghan @CaseyHillers

**Comment by CaseyHillers** [comment]
This seems to be related to https://github.com/flutter/flutter/issues/107961 (\cc @yusuf-goog ). There was an outage causing the build updates to fail to process, and commits kept getting landed by the autosubmit bot.

> When too many commits are batched like this, we have a big gap in our benchmarking data, and regressions require a lot more manual effort to pin down.

The good news is the framework is mostly migrated to the Cocoon scheduler thanks to Keyong. Overnight, Cocoon backfilled all the missing data

A feature request I could see here is that the tree should close itself if there's 10 commits with gray rows.

**Comment by CaseyHillers** [comment]
All tasks get backfilled, unfortunately, staging doesn't have the capacity to backfill. At the minimum every 3 commits gets run, and if there's no yellow tasks, Cocoon will run backfilling.

@keyonghan is there a tracking bug for the mac ios staging capacity? 2 out of the 4 bots are down - https://chromium-swarm.appspot.com/botlist?f=device_os%3AiOS-15&f=os%3AMac-12&f=cpu%3Ax86&f=pool%3Aluci.flutter.staging

**Comment by keyonghan** [comment]
> We do not currently have an alert setup for the staging pool. I can add
this if we need it.

That would be great, as we are relying on staging pool to validate flake fix. Thanks!

**Comment by ricardoamador** [comment]
Sure no problem. I can add those alerts for staging.

**Comment by keyonghan** [comment]
Staging alerts were created: cl/463888722
Closing.
