### ISSUE TITLE
[google_sign_in] Can't scroll down to sign-in with my mail

### ISSUE THREAD

**Issue by water-user** [flutter/flutter#107922]
Can't scroll down to sign-in with my mail

<img src="https://user-images.githubusercontent.com/95235346/179745366-e816d63e-6dac-46c9-a9ef-3ceb691bd0c2.jpeg" width ="300">

**Comment by maheshmnj** [comment]
Hi @water-user, Thanks for filing the issue. What target platform is this issue on?   Please share a minimal and complete sample code along with the output of `flutter doctor -v`.


Thanks

**Comment by water-user** [comment]
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.2.1 21D62 darwin-arm, locale en-IL)
    • Flutter version 2.8.1 at /Users/amitwater/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (7 months ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

**Comment by maheshmnj** [comment]
@water-user We would need a code sample describing your case, I am unable to reproduce the issue with the [official example app](https://github.com/flutter/plugins/tree/main/packages/google_sign_in/google_sign_in/example)

> What target platform is this issue on? Please share a minimal and complete sample code 


<img src="https://user-images.githubusercontent.com/31410839/180136680-6827822b-c99c-4519-b46f-6d1bd63d744c.png" width ="300"> 

<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.4 21F79 darwin-arm, locale en-IN)
    • Flutter version 3.0.5 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (5 days ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-32, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.67.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.44.0

[✓] Connected device (3 available)
    • sdk gphone arm64 (mobile) • emulator-5554 • android-arm64  • Android 11 (API 30) (emulator)
    • macOS (desktop)           • macos         • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)              • chrome        • web-javascript • Google Chrome 103.0.5060.114

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by water-user** [comment]
Just change your phone resolution like my and you get the result:
![WhatsApp Image 2022-07-21 at 09 57 19 (1)](https://user-images.githubusercontent.com/95235346/180149951-903deeb1-5908-41e7-abbd-dfdd7290ae5a.jpeg)
![WhatsApp Image 2022-07-21 at 09 57 19](https://user-images.githubusercontent.com/95235346/180149961-6d188ea6-dff0-4196-8a43-82bc08605e1d.jpeg)

**Comment by maheshmnj** [comment]
@water-user ensure I have maxed out displays and font size and  I am still unable to reproduce the issue. What device is this issue on?

https://user-images.githubusercontent.com/31410839/180225800-e3ad08e4-7287-4a5c-847f-2c0daefd8094.mov


<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.4 21F79 darwin-arm, locale en-IN)
    • Flutter version 3.0.5 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (5 days ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-32, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.67.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.44.0

[✓] Connected device (3 available)
    • sdk gphone arm64 (mobile) • emulator-5554 • android-arm64  • Android 11 (API 30) (emulator)
    • macOS (desktop)           • macos         • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)              • chrome        • web-javascript • Google Chrome 103.0.5060.114

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by water-user** [comment]
I'm using Galaxy S21 (SM-G991)
Using google_sign_in: ^5.4.0
I have another screen, not like you attached in the recorder screenshot.
I have a screen like your screenshot you uploaded in your second answer, and it's not scrollable (except the mails area, which i can't get when the font is big)

**Comment by maheshmnj** [comment]
@water-user Can you please share a minimal and complete code sample? I still can't reproduce it, Verified on two different devices so far Xiaomi  k20 pro and pixel 3 emulator.

**Comment by water-user** [comment]
It's build in dialog that open from **signIn()** build-in function from **google_sign_in** package
My code:

  ```
Future<User?> _googleSignIn() async {
    if (await GoogleSignIn().isSignedIn()) {
      await GoogleSignIn().signOut();
    }
    GoogleSignIn _googleSignIn = GoogleSignIn(
      scopes: [
        'email',
      ],
    );
    try {
      final GoogleSignInAccount? result = await _googleSignIn.signIn();
      if (result == null) {
        return null;
      }
      // some code...
      return user;
    } catch (error) {
      print(error);
      return null;
    }
  }
```

**Comment by huycozy** [comment]
@water-user 
> It's build in dialog that open from signIn() build-in function from google_sign_in package (https://pub.dev/documentation/google_sign_in/latest/google_sign_in/GoogleSignIn/signIn.html)

Do you embed the login screen inside a dialog? 
Please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this. Thanks!

**Comment by maheshmnj** [comment]
Thanks for the sample code @water-user, This doesn't reproduce on our end.  

> I checked it in Mi 9 Pro and it's ok, I encountered this problem in only in my Galaxy S21

Perhaps this could be device-specific labeling for further investigation from the team. Triage details here https://github.com/flutter/flutter/issues/107922#issuecomment-1191491230

**Comment by stuartmorgan** [comment]
We don't control this UI; it's system-provided. You'd need to report this issue to Android.
