### ISSUE TITLE
Unexpected behavior of FractionalOffset types

### ISSUE THREAD

**Issue by manyopensource** [flutter/flutter#107930]
I get an error:
`A value of type 'Alignment' can't be assigned to a variable of type 'FractionalOffset'.`

when trying this:
```dart
import 'package:flutter/material.dart';

const Color darkBlue = Color.fromARGB(255, 18, 32, 47);

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: darkBlue,
      ),
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: Center(
          child: MyWidget(),
        ),
      ),
    );
  }
}

class MyWidget extends StatelessWidget {
  FractionalOffset n = const FractionalOffset(0.2, 0.4);
  FractionalOffset m = const FractionalOffset(0.1, 0.5);
  FractionalOffset s = n + m;
  
  @override
  Widget build(BuildContext context) {
    return Text(
      'Hello, World!',
      style: Theme.of(context).textTheme.headline4,
    );
  }
}
```

**Comment by huycozy** [comment]
Hi @manyopensource 

```
A value of type 'Alignment' can't be assigned to a variable of type 'FractionalOffset'.
Try changing the type of the variable, or casting the right-hand type to 'FractionalOffset'.dart[invalid_assignment](https://dart.dev/diagnostics/invalid_assignment)
```

Below is a workaround that you can try:

<details>
<summary>Sample code</summary>

```dart
import 'package:flutter/material.dart';

const Color darkBlue = Color.fromARGB(255, 18, 32, 47);

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: darkBlue,
      ),
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: Center(
          child: MyWidget(),
        ),
      ),
    );
  }
}

class MyWidget extends StatelessWidget {
  FractionalOffset n = const FractionalOffset(0.2, 0.4);
  FractionalOffset m = const FractionalOffset(0.1, 0.5);
  late FractionalOffset s;

  @override
  Widget build(BuildContext context) {
    s = (n + m) as FractionalOffset;
    return Container(
      alignment: s,
      child: Text(
        'Hello, World!',
        style: Theme.of(context).textTheme.headline4,
      ),
    );
  }
}

```
</details>

<details>
<summary>Demo</summary>

<img width="776" alt="Screen Shot 2022-07-20 at 14 01 53" src="https://user-images.githubusercontent.com/104349824/179917901-d9e39456-043a-449d-936f-314319210066.png">

</details>

**Comment by manyopensource** [comment]
> Hi @manyopensource 
> 
> ```
> A value of type 'Alignment' can't be assigned to a variable of type 'FractionalOffset'.
> Try changing the type of the variable, or casting the right-hand type to 'FractionalOffset'.dart[invalid_assignment](https://dart.dev/diagnostics/invalid_assignment)
> ```
> 
> Below is a workaround that you can try:
> 
> <details>
> <summary>Sample code</summary>
> 
> ```dart
> import 'package:flutter/material.dart';
> 
> const Color darkBlue = Color.fromARGB(255, 18, 32, 47);
> 
> void main() {
>   runApp(MyApp());
> }
> 
> class MyApp extends StatelessWidget {
>   @override
>   Widget build(BuildContext context) {
>     return MaterialApp(
>       theme: ThemeData.dark().copyWith(
>         scaffoldBackgroundColor: darkBlue,
>       ),
>       debugShowCheckedModeBanner: false,
>       home: Scaffold(
>         body: Center(
>           child: MyWidget(),
>         ),
>       ),
>     );
>   }
> }
> 
> class MyWidget extends StatelessWidget {
>   FractionalOffset n = const FractionalOffset(0.2, 0.4);
>   FractionalOffset m = const FractionalOffset(0.1, 0.5);
>   late FractionalOffset s;
> 
>   @override
>   Widget build(BuildContext context) {
>     s = (n + m) as FractionalOffset;
>     return Container(
>       alignment: s,
>       child: Text(
>         'Hello, World!',
>         style: Theme.of(context).textTheme.headline4,
>       ),
>     );
>   }
> }
> 
> ```
> </details>
> 
> <details>
> <summary>Demo</summary>
> 
> <img width="776" alt="Screen Shot 2022-07-20 at 14 01 53" src="https://user-images.githubusercontent.com/104349824/179917901-d9e39456-043a-449d-936f-314319210066.png">
> 
> </details>

Thank you, nice and simple workaround!
