### ISSUE TITLE
Document writing custom shaders on the website

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#107929]
When the APIs are stable, we should add documentation or a tutorial to the website on writing custom shaders.

In particular:
- What input formats are supported
- How to add one to an app
- How to obtain a [FragmentProgram](https://github.com/flutter/engine/blob/5c60785b802ad2c8b8899608d949342d5c624952/lib/ui/painting.dart#L4036)
- How to use a FragmentProgram to obtain a `Shader`
- How to use that shader in a scene/widget
- Best practices for structuring this code efficiently

**Comment by jonahwilliams** [comment]
From https://github.com/flutter/flutter/issues/108307 : also include information on premultiplied outputs, conversion helpers, et cetera

**Comment by jonahwilliams** [comment]
We also need to update https://master-api.flutter.dev/flutter/dart-ui/FragmentProgram-class.html to point to this documentation. Since its not updated yet this is a likely CP candidate to update the link
