### ISSUE TITLE
Google SignIn is not working with firebase_auth 3.4.2 

### ISSUE THREAD

**Issue by PranayDosii** [flutter/flutter#107914]
It was working fine with the older version of firebase auth but when I updated to the latest version of firebase auth. It is throwing me the error `argument-error`.  This is my sample code and I have added all the credentials but it is not working 

```
 final _firebaseAuth = FirebaseAuth.instance;
  Future<void> _handleSignIn() async {
    final authProvider = GoogleAuthProvider();
    try {

      await _firebaseAuth.signInWithPopup(authProvider);

      Navigator.pushAndRemoveUntil(
          context,
          MaterialPageRoute(builder: (context) => const Profile()),
          (route) => false);
    
     
    } on FirebaseException catch (e) {
      print(e.code);
      rethrow;
    }
   
  }
```

`+12168 ms] argument-error
[   +6 ms] Error: [firebase_auth/argument-error] Error
               at Object.throw_ [as throw] (http://localhost:63167/dart_sdk.js:5080:11)
               at firebase_auth_web.FirebaseAuthWeb.new.signInWithPopup

(http://localhost:63167/packages/firebase_auth_web/firebase_auth_web.dart.lib.js:358:23)
               at signInWithPopup.throw (<anonymous>)
               at http://localhost:63167/dart_sdk.js:40646:38
               at _RootZone.runBinary (http://localhost:63167/dart_sdk.js:40515:59)
               at _FutureListener.thenAwait.handleError
(http://localhost:63167/dart_sdk.js:35449:33)
               at handleError (http://localhost:63167/dart_sdk.js:36015:51)
               at _Future._propagateToListeners
(http://localhost:63167/dart_sdk.js:36041:17)
               at [_completeError] (http://localhost:63167/dart_sdk.js:35878:23)
               at async._AsyncCallbackEntry.new.callback
(http://localhost:63167/dart_sdk.js:35927:31)
               at Object._microtaskLoop (http://localhost:63167/dart_sdk.js:40778:13)
               at _startMicrotaskLoop (http://localhost:63167/dart_sdk.js:40784:13)
               at http://localhost:63167/dart_sdk.js:36261:9
`

**Comment by maheshmnj** [comment]
Hi @PranayDosii, this looks like an issue in the `firebaseAuth` library  I would suggest filing that issue in the [flutterfire repo](https://github.com/firebase/flutterfire) Closing as this is not an issue with flutter's `google_sign_in`plugin. In case you disagree feel free to write in the comments and we will reopen it.
