### ISSUE TITLE
[iOS] More information is needed about screen lock when building iPhone devices.

### ISSUE THREAD

**Issue by ybin0823** [flutter/flutter#107983]
Hello, 
Recently, while building on a new device, I found something. 

## Use case

- iPhone had a screen lock.
- run `flutter build ios`

![스크린샷 2022-07-20 오전 11 54 38](https://user-images.githubusercontent.com/7553607/179888188-5a699862-272e-42ce-8420-e3ffe0ec8c6f.png)
- I was able to guess by building it with xcode to find the cause.

## Proposal
- It seems that flutter can get the error code from Xcode.
![스크린샷 2022-07-20 오후 12 04 40](https://user-images.githubusercontent.com/7553607/179888417-8a42345c-b198-4459-9d63-f7478132a82b.png)
- Is it possible to log a little more detailed than "Try launching Xcode"? (ex. device is locked)

**Comment by jmagman** [comment]
I wasn't able to reproduce this with `flutter build ios` since that doesn't target a particular device, but I did from `flutter run`.
This looks like new behavior from the phone,`xcrun xcdevice` used to tell us when it was locked (-13 error if I recall), but now there's no error reported:
```
  {
    "simulator" : false,
    "operatingSystemVersion" : "15.4.1 (19E258)",
    "interface" : "usb",
    "available" : true,
    "platform" : "com.apple.platform.iphoneos",
    "modelCode" : "iPhone13,3",
    "identifier" : "00008101-001E69261695003A",
    "architecture" : "arm64e",
    "modelUTI" : "com.apple.iphone-12-pro-9",
    "modelName" : "iPhone 12 Pro",
    "name" : "iPhone 12 Pro"
  },
```
That means we won't be able to tell you up front that the device is locked and to unlock it.  I wonder if any of the `libimobiledevice` tools could be used to report it.

In verbose mode I see:
```
[  +95 ms] error: The operation couldn’t be completed. Unable to launch io.flutter.examples.gallery because the device was not, or could not be, unlocked.
```
so we could at least tell once it failed that it was locked...
so we can at least

**Comment by jmagman** [comment]
> I wonder if any of the `libimobiledevice` tools could be used to report it.

I couldn't find a lock state from those tools either.

**Comment by jmagman** [comment]
> That means we won't be able to tell you up front that the device is locked and to unlock it.

Actually, this matches Xcode behavior, it lets me target a locked device, it builds the app, and I only get the pop up when it's ready to install it.
<img width="550" alt="Screen Shot 2022-07-20 at 2 13 51 PM" src="https://user-images.githubusercontent.com/682784/180083343-cc6c6789-09ad-4a69-afe6-86de3ae223f7.png">

**Comment by jmagman** [comment]
Should consider changing from string matching to parsing the JSON events
https://github.com/ios-control/ios-deploy/blob/24c9efbd43f2acd25c0f3e85137e29ec3c1654cf/src/ios-deploy/ios-deploy.m#L779-L781
