### ISSUE TITLE
Can't find assets with foreign characters

### ISSUE THREAD

**Issue by arnirichard** [flutter/flutter#107911]
I can't load assets with special characters.
I can't find any rules on assets naming.
If working as expected, what is the best workaround?

## Steps to Reproduce

1. Add asset กิน.wav to assets folder, also to pubspec.yaml (- assets/กิน.wav)
2. Add `WidgetsFlutterBinding.ensureInitialized();` to main.dart
3. Try to load the asset using
`ByteData bytes = await rootBundle.load('กิน.wav'); //load sound from assets`

**Expected results:** 
Asset is loaded
**Actual results:**
Unable to load asset: กิน.wav

## Flutter Doctor

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.10.5, on Microsoft Windows [Version 10.0.22000.795], locale en-GB)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Professional 2022 17.2.4)
[√] Android Studio (version 2020.3)
[√] Android Studio (version 2021.2)
[√] VS Code (version 1.68.1)
[√] Connected device (4 available)
[√] HTTP Host Availability

• No issues found!

**Comment by exaby73** [comment]
Hello @arnirichard. Can you confirm if this issue persists on the current stable version of Flutter? You can use `flutter upgrade` to upgrade your copy of Flutter to V3.0.5

**Comment by arnirichard** [comment]
Sorry, I forgot that I was on old version.
I upgraded and the issue persists.

## Flutter Doctor

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.0.5, on Microsoft Windows [Version 10.0.22000.795], locale en-GB)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Professional 2022 17.2.4)
[√] Android Studio (version 2020.3)
[√] Android Studio (version 2021.2)
[√] VS Code (version 1.68.1)
[√] Connected device (4 available)
[√] HTTP Host Availability

• No issues found!

## pubspec.yaml

name: app
description: desc

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  dotted_border: ^2.0.0+2
  flutter_svg: ^1.0.3
  audioplayers: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  fonts:
    - family: Sarabun
      fonts:
        - asset: fonts/Sarabun-Regular.ttf
    - family: Kanit
      fonts:
        - asset: fonts/Kanit-Regular.ttf
    - family: Mitr
      fonts:
        - asset: fonts/Mitr-Regular.ttf
    - family: Prompt
      fonts:
          - asset: fonts/Prompt-Regular.ttf

  assets:
    - assets/
    - assets/icons/book.svg
    - assets/icons/checklist.svg
    - assets/กิน.wav

**Comment by exaby73** [comment]
I believe you need to do `ByteData bytes = await rootBundle.load('assets/กิน.wav');`. Can you please try that and confirm?

**Comment by arnirichard** [comment]
@exaby73 yes, it works. I thought I tried all versions of this. Thank you.
