### ISSUE TITLE
[video_player][iOS]Video file is not playing in IOS device , same video is playing in android device

### ISSUE THREAD

**Issue by expertdev-designer** [flutter/flutter#108009]
I have a video player in our project where we play camera-recorded videos and gallery video . But there is a one file which is not playing in IOS device only.

Here is the video file download link : https://drive.google.com/file/d/19q0QNWvCclfCa_NniAubTMf1hhbrV6tV/view?usp=sharing

Here is my code 

<details>
<summary>code sample</summary>

```dart
VideoPlayerController _videoController;

  @override
  void initState() {
    super.initState();
    _videoController = VideoPlayerController.file(widget.file)
     ..initialize().then((_) {
    
        setState(() {});
      });
  }
  
  
  Scaffold(
  //     body: AspectRatio(
  //         aspectRatio: _videoController!
  //             .value.aspectRatio,
  //         child: VideoPlayer(
  //           _videoController!,
  //         )),
  //   );
```
</details>

Please help guys . I need to fix this issue asap

Thanks

**Comment by danagbemava-nc** [comment]
Hi @expertdev-designer, your code sample is not complete. Please provide a complete minimal reproducible code sample. 

Also, what version of `video_player` are you using? 

Please also provide the output of `flutter doctor -v` as well.

Thank you

**Comment by expertdev-designer** [comment]
@danagbemava-nc  
flutter doctor -v 
[✓] Flutter (Channel stable, 2.10.5, on macOS 11.6.6 20G624 darwin-x64, locale en-IN)
    • Flutter version 2.10.5 at /Users/mac/Documents/Flutter/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (3 months ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mac/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] Connected device (2 available)
    • iPhone 13 (mobile) • 3D03FB0A-5521-4CDA-BE47-209408C6E642 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 103.0.5060.134

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

video_player version  ^2.2.10

**Comment by danagbemava-nc** [comment]
Hi @expertdev-designer, can you upgrade to the latest version of the video_player plugin (2.4.5) to see if you still experience this issue?

**Comment by danagbemava-nc** [comment]
Hi @expertdev-designer, one more thing, when I downloaded the file, the name was `10. Overwhelm have a plan - Micro.MP4`. Is that the correct name for the file you're trying to load?

**Comment by expertdev-designer** [comment]
Hello, @danagbemava-nc  
We updated the latest version but stile the issue,
The code sample :
else if (mimeType!.startsWith('video/')) {
            print(pickedGallaryFile.path);
            Navigator.of(context)
                .push(MaterialPageRoute(builder: (context) => SeedVideoPlayer(file: pickedGallaryFile)));
          }


import 'dart:io';

import 'package:flutter/material.dart';
import 'package:video_player/video_player.dart';

class SeedVideoPlayer extends StatefulWidget {
  final File file;

  SeedVideoPlayer({required this.file});

  @override
  SeedVideoPlayerState createState() => SeedVideoPlayerState();
}

class _SeedVideoPlayerState extends State<SeedVideoPlayer> {
  late VideoPlayerController _controller;

  @override
  void initState() {
    super.initState();
    _controller = VideoPlayerController.file(widget.file)
      ..initialize().then((_) {
        setState(() {});
      });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text("My Video"),),
      body: Center(
        child: _controller.value.isInitialized
            ? AspectRatio(
                aspectRatio: _controller.value.aspectRatio,
                child: VideoPlayer(_controller),
              )
            : Container(),
      ),
    );
  }

  @override
  void dispose() {
    super.dispose();
    _controller.dispose();
  }
}
The file name is correct it only in iOS file is not loading

**Comment by danagbemava-nc** [comment]
Hi @expertdev-designer, this is a known issue and is being tracked in https://github.com/flutter/flutter/issues/51031. 

As a workaround, you can try removing the whitespace in your file names before you upload/save them so that the files do not have the whitespace in them. 

Kindly follow up in the linked issue for updates. 

Closing from here as duplicate. 

Thank you
