### ISSUE TITLE
linux17 is quarantined due to 6 consecutive failed tasks

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#108054]
<img width="1561" alt="Screen Shot 2022-07-20 at 2 06 11 PM" src="https://user-images.githubusercontent.com/54558023/180082213-858238c4-2827-4b56-97cf-a050dd0ec089.png">

This is due to failed task: Linux_android android_lifecycles_test (https://github.com/flutter/flutter/issues/105237)

<img width="1226" alt="Screen Shot 2022-07-20 at 2 06 30 PM" src="https://user-images.githubusercontent.com/54558023/180082220-b1775d49-2246-4e18-abea-4c1f5184be32.png">

We should remove the test from CI before the issue is addressed: https://cs.opensource.google/flutter/flutter/+/master:.ci.yaml;l=2245.

**Comment by yusuf-goog** [comment]
@keyonghan is this test required, should we fix the test?

**Comment by keyonghan** [comment]
> @keyonghan is this test required, should we fix the test?

Yes. Please see the fix suggested in the description.

**Comment by keyonghan** [comment]
Now both 16 and 17 are down due to this issue:
<img width="1313" alt="Screen Shot 2022-07-26 at 9 37 31 AM" src="https://user-images.githubusercontent.com/54558023/181062063-38fbc6fb-df3b-4fd8-9f3c-1e8361b4fedd.png">

**Comment by yusuf-goog** [comment]
Test has been removed, deleting  `.task_failure_count` file.

**Comment by yusuf-goog** [comment]
bot is back up.
