### ISSUE TITLE
Support for producing an RTree from a DisplayList

### ISSUE THREAD

**Issue by flar** [flutter/flutter#108083]
Note that this is a subset of https://github.com/flutter/flutter/issues/92740 in that it doesn't require using the RTree for active culling during rendering, but is merely a support task for enabling PlatformView embedders to embrace the DisplayListBuilder as their primary layer separation mechanism in lieu of their existing use of SkPictureRecorder. This will help Impeller produce more accurate rendering in the presence of these embedded views.

**Comment by ColdPaleLight** [comment]
fixed by linked PR
