### ISSUE TITLE
Issue from website page Using Custom Fonts, display an example use

### ISSUE THREAD

**Issue by branflake2267** [flutter/flutter#10809]
From URL: https://flutter.io/custom-fonts.md

Docs suggestion. On the custom fonts page,  it doesn't show how to use the declared fonts pubsec.yaml, so it's only half of the story. 

I'd suggest adding an example of how to use the same declared fonts.

**Comment by Hixie** [comment]
https://flutter.io/cookbook/design/fonts/ does this now.
