### ISSUE TITLE
flutter 3.0.1 crash (ios) GrMtlGpu::onWritePixels

### ISSUE THREAD

**Issue by zjrwdl** [flutter/flutter#108096]
<img width="1311" alt="image" src="https://user-images.githubusercontent.com/6874049/180186560-02543d61-f111-4bc3-9cab-bb123a0045ec.png">

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.1, on macOS 11.6 20G165 darwin-x64, locale
zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!

15.5 (19F77)
iPhone 8 Plus

**Comment by huycozy** [comment]
Hi @zjrwdl, thanks for filing the issue.
Could you please provide full crash log and affected devices as well?
(If the log is too long, please save it to a file and attach it here)

**Comment by zjrwdl** [comment]
> Hi @zjrwdl, thanks for filing the issue. Could you please provide full crash log and affected devices as well? (If the log is too long, please save it to a file and attach it here)

AGXMetalA11
0x00000001ddd44000 + 108840
2
AGXMetalA11
0x00000001ddd44000 + 88548
3
Flutter
GrMtlGpu::onWritePixels(GrSurface*, SkIRect, GrColorType, GrColorType, GrMipLevel const*, int, bool) (GrMtlGpu.mm:391)
4
Flutter
GrGpu::writePixels(GrSurface*, SkIRect, GrColorType, GrColorType, GrMipLevel const*, int, bool) (GrGpu.cpp:478)
5
Flutter
GrResourceProvider::createTexture(SkISize, GrBackendFormat const&, GrTextureType, GrColorType, GrRenderable, int, SkBudgeted, GrMipmapped, GrProtected, GrMipLevel const*) (GrGpu.cpp:229)
6
Flutter
_ZNSt3__110__function6__funcIZN15GrProxyProvider27createMippedProxyFromBitmapERK8SkBitmap10SkBudgetedE3$_1NS_9allocatorIS7_EEFN14GrSurfaceProxy18LazyCallbackResultEP18GrResourceProviderRKNSA_15LazySurfaceDescEEEclEOSD_SG_ (SkRefCnt.h:320)
7
Flutter
GrSurfaceProxyPriv::doLazyInstantiation(GrResourceProvider*) (SkRefCnt.h:320)
8
Flutter
make_bmp_proxy (GrProxyProvider.cpp:320)
9
Flutter
GrMakeUncachedBitmapProxyView (SkRefCnt.h:298)
10
Flutter
SkImage::MakeCrossContextFromPixmap(GrDirectContext*, SkPixmap const&, bool, bool) (SkRefCnt.h:298)
11
Flutter
_ZNSt3__110__function6__funcIZN7flutter15MultiFrameCodec5State17GetNextFrameImageEN3fml7WeakPtrI15GrDirectContextEERKNS_10shared_ptrIKNS5_10SyncSwitchEEEE3$_4NS_9allocatorISF_EEFvvEEclEv (multi_frame_codec.cc:140)
12
Flutter
fml::SyncSwitch::Execute(fml::SyncSwitch::Handlers const&) const (mutex:501)
13
Flutter
_ZNSt3__110__function6__funcIN3fml8internal14CopyableLambdaIZN7flutter15MultiFrameCodec12getNextFrameEP12_Dart_HandleE3$_2EENS_9allocatorISA_EEFvvEEclEv (functional:1838)
14
Flutter
fml::MessageLoopImpl::FlushTasks(fml::FlushType) (ref_ptr.h:124)
15
Flutter
fml::MessageLoopDarwin::OnTimerFire(__CFRunLoopTimer*, fml::MessageLoopDarwin*) (message_loop_darwin.mm:81)
16
CoreFoundation
___CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 28
20
CoreFoundation
_CFRunLoopRunSpecific + 572
21
Flutter
fml::MessageLoopDarwin::Run() (message_loop_darwin.mm:52)
22
Flutter
__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, (lambda at ../../flutter/fml/thread.cc:79:7)> > (message_loop_impl.cc:0)
23
libsystem_pthread.dylib
__pthread_start + 116

**Comment by zjrwdl** [comment]
similar with this issue  [ https://github.com/flutter/flutter/issues/105036]

**Comment by huycozy** [comment]
Hi @zjrwdl 
As you mentioned above, the issue #105036 has the similar log and has been answered [here](https://github.com/flutter/flutter/issues/105036#issuecomment-1143959860).
Closing this issue based on that explanation!

**Comment by zjrwdl** [comment]
> Hi @zjrwdl As you mentioned above, the issue #105036 has the similar log and has been answered [here](https://github.com/flutter/flutter/issues/105036#issuecomment-1143959860). Closing this issue based on that explanation!

@[chinmaygarde](https://github.com/chinmaygarde)
@huycozy 
the issue above is not fixed  but it has been closed.
