### ISSUE TITLE
java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dlopen failed: library "libflutter.so" not found

### ISSUE THREAD

**Issue by ahmedkeewan** [flutter/flutter#108079]
<p> Hey team <br>
I have a problem with my Flutter project related to  "libflutter.so" not found, the issue was reported using firebase Crashlytics and I tried reproducing the problem locally, but I couldn't, I have checked a lot of articles and open issues here, but none of the solutions was helpful, even after analyzing my apk I can see the libflutter.so for the cpu architectures supported by Flutter.

<details>
  <summary>Logs</summary>

xxxxx@bayts-MacBook-Pro flutter-bayt-js % flutter doctor -v
[✓] Flutter (Channel stable, 3.0.3, on macOS 12.1 21C52 darwin-arm, locale en-JO)
    • Flutter version 3.0.3 at /Users/xxxxx/Desktop/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 676cefaaff (4 weeks ago), 2022-06-22 11:34:49 -0700
    • Engine revision ffe7b86a1e
    • Dart version 2.17.5
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/xxxxx/Library/Android/sdk
    • Platform android-32, build-tools 32.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.69.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.44.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.1 21C52 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 103.0.5060.114

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

</details>

**Comment by huycozy** [comment]
Hi @ahmedkeewan, thanks for filing the issue
Could you please provide full crash log from Firebase Crashlytics? And the affected device information as well.
Also, is this issue reproducible when you run the project locally with [release](https://docs.flutter.dev/testing/build-modes#release) mode?
Thanks!

**Comment by ahmedkeewan** [comment]
Hi @huycozy ,

Thanks for the fast reply, 

the affected device information:
<img width="421" alt="Screen Shot 2022-07-21 at 2 13 36 PM" src="https://user-images.githubusercontent.com/42587111/180206698-6f744a28-2037-42af-bd08-99ec80e02cf6.png">
<img width="421" alt="Screen Shot 2022-07-21 at 2 48 21 PM" src="https://user-images.githubusercontent.com/42587111/180206706-e01b7284-e7e9-45c6-af31-5e55884d3d95.png">
<img width="421" alt="Screen Shot 2022-07-21 at 2 48 26 PM" src="https://user-images.githubusercontent.com/42587111/180206714-f720322e-fcc1-43f1-ad6f-54605c846476.png">
<img width="421" alt="Screen Shot 2022-07-21 at 2 48 31 PM" src="https://user-images.githubusercontent.com/42587111/180206719-80ce0fcd-30f1-4f9c-9013-533cd2323956.png">
<img width="421" alt="Screen Shot 2022-07-21 at 2 48 38 PM" src="https://user-images.githubusercontent.com/42587111/180206723-43da6c2f-5b82-408b-9660-4e692d91cf8b.png">
<img width="421" alt="Screen Shot 2022-07-21 at 2 48 44 PM" src="https://user-images.githubusercontent.com/42587111/180206728-40085799-0415-4548-90df-79d180b23754.png">


is this issue reproducible when you run the project locally with [release](https://docs.flutter.dev/testing/build-modes#release) mode?
: only if add the following code snippet to the build grade, and i don't have it in my production app, i just added it to reproduce
```
ndk {
            abiFilters 'armeabi-v7a'
        }
```

full crash log from Firebase Crashlytics:

E/FlutterLoader( 5411): java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dlopen failed: library "libflutter.so" not found
E/FlutterLoader( 5411): 	at java.util.concurrent.FutureTask.report(FutureTask.java:123)
E/FlutterLoader( 5411): 	at java.util.concurrent.FutureTask.get(FutureTask.java:193)
E/FlutterLoader( 5411): 	at io.flutter.embedding.engine.loader.FlutterLoader.ensureInitializationComplete(FlutterLoader.java:236)
E/FlutterLoader( 5411): 	at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:327)
E/FlutterLoader( 5411): 	at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:207)
E/FlutterLoader( 5411): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.setupFlutterEngine(FlutterActivityAndFragmentDelegate.java:266)
E/FlutterLoader( 5411): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:175)
E/FlutterLoader( 5411): 	at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:498)
E/FlutterLoader( 5411): 	at com.baytjs.MainActivity.onCreate(MainActivity.kt:27)
E/FlutterLoader( 5411): 	at android.app.Activity.performCreate(Activity.java:7994)
E/FlutterLoader( 5411): 	at android.app.Activity.performCreate(Activity.java:7978)
E/FlutterLoader( 5411): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
E/FlutterLoader( 5411): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422)
E/FlutterLoader( 5411): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
E/FlutterLoader( 5411): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
E/FlutterLoader( 5411): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/FlutterLoader( 5411): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/FlutterLoader( 5411): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
E/FlutterLoader( 5411): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/FlutterLoader( 5411): 	at android.os.Looper.loop(Looper.java:223)
E/FlutterLoader( 5411): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/FlutterLoader( 5411): 	at java.lang.reflect.Method.invoke(Native Method)
E/FlutterLoader( 5411): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/FlutterLoader( 5411): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/FlutterLoader( 5411): Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: library "libflutter.so" not found
E/FlutterLoader( 5411): 	at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
E/FlutterLoader( 5411): 	at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
E/FlutterLoader( 5411): 	at java.lang.System.loadLibrary(System.java:1664)
E/FlutterLoader( 5411): 	at io.flutter.embedding.engine.FlutterJNI.loadLibrary(FlutterJNI.java:141)
E/FlutterLoader( 5411): 	at io.flutter.embedding.engine.loader.FlutterLoader$1.call(FlutterLoader.java:186)
E/FlutterLoader( 5411): 	at io.flutter.embedding.engine.loader.FlutterLoader$1.call(FlutterLoader.java:179)
E/FlutterLoader( 5411): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/FlutterLoader( 5411): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/FlutterLoader( 5411): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/FlutterLoader( 5411): 	at java.lang.Thread.run(Thread.java:923)

**Comment by huycozy** [comment]
Hi @ahmedkeewan, thanks for providing the detail.
I see there's an open issue addressing the case you described #57237
Closing as a duplication, so please follow up on it for further updates.
