### ISSUE TITLE
Staging Mac bots are Dead for days

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#108055]
<img width="1166" alt="Screen Shot 2022-07-20 at 2 12 59 PM" src="https://user-images.githubusercontent.com/54558023/180083224-73ea2f1a-4ada-4bc1-bdfb-ffac04584626.png">

**Comment by yusuf-goog** [comment]
mac-10 is ssh'able.

**Comment by godofredoc** [comment]
Bots have been recovered. They required reboots or manually starting the swarming service.
