### ISSUE TITLE
Mac 5 and mac39 are quarantined due to 6 consecutive failed tasks

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#108053]
<img width="1559" alt="Screen Shot 2022-07-20 at 1 59 51 PM" src="https://user-images.githubusercontent.com/54558023/180081185-1d404425-23eb-4f68-a185-71372b02e718.png">

**Comment by keyonghan** [comment]
The failures are with `Mac_arm64_staging native_ui_tests_macos`, which is not needed anymore (https://github.com/flutter/flutter/issues/101721)
<img width="1222" alt="Screen Shot 2022-07-20 at 2 00 29 PM" src="https://user-images.githubusercontent.com/54558023/180081325-4fb670d0-06c1-4e5d-a08c-8e94aac2437f.png">

We should remove the test https://cs.opensource.google/flutter/infra/+/main:config/devicelab_staging_config.star;l=349

**Comment by keyonghan** [comment]
> @keyonghan is this a test issue? Should we be trying to make the test pass?

Yes. Please see the fix suggested in the description.

**Comment by yusuf-goog** [comment]
Fix: https://flutter-review.googlesource.com/c/infra/+/32080

**Comment by yusuf-goog** [comment]
removed .task_failure_count from mac-5,39. Both machines are recovered.
