### ISSUE TITLE
[android] Declare usage of `REQUEST_INSTALL_PACKAGES`

### ISSUE THREAD

**Issue by Zazo032** [flutter/flutter#108011]
Today I received a new message regarding a Flutter app published in Play Store, with the following information:

> You'll need to complete a declaration soon for apps using REQUEST_INSTALL_PACKAGES

> We found that your manifest file contains the REQUEST_INSTALL_PACKAGES permission.
> Starting September 29, 2022, apps that use this permission will not be able to submit updates for review until they have completed a new sensitive permission declaration.
> This declaration will be available in Play Console on August 31, 2022. You'll need to declare which permitted functionality your app provides, tell us about a core feature in your app that uses the permission, and provide a video showing its use.
> You must remove this sensitive permission from your manifest if your app does not use the permitted functionalities, or if you no longer use this permission. To learn more, watch this [PolicyBytes video](https://www.youtube.com/watch?v=O0UwUF2DgQc&t=139s).
> [Learn more](https://support.google.com/googleplay/android-developer/answer/9888170#install_package)

I'm not directly using the mentioned permission, so I'm not sure if any of the plugins I'm using has that permission set on its manifest file.

We should somehow be able to know if a plugin is adding a specific permission, or if this comes directly from the Flutter framework.

**Comment by danagbemava-nc** [comment]
Hi @Zazo032, can you open the `android` project of your app in android studio and check the `Merged Manifests` portion of the `AndroidManifest.xml` to see if you find that permission being used in your app?

**Comment by Zazo032** [comment]
Found the culprit: [open_file](https://pub.dev/packages/open_file)

I'll open an issue in that repository, thanks!

**Comment by danagbemava-nc** [comment]
I'll be closing this as solved. 

Thank you
