### ISSUE TITLE
By using SingleChildScrollView, some text widget gets blurred in Flutter web

### ISSUE THREAD

**Issue by Adeel-Sultan** [flutter/flutter#108002]
I used widgets inside column children's and when I wrap SingleChildScrollView and some text widget get blurred.
I am facing this issue only in Flutter Web, even in flutter mobile this is working fine.
Below I've attached Screenshot you can see last two lines get blurred.

![image](https://user-images.githubusercontent.com/50919582/179960611-48a89bb2-1901-4c94-93b5-92c98abe834d.png)

**Comment by exaby73** [comment]
Hi @Adeel-Sultan, please provide a [minimal, reproducible example][1] and the output of `flutter doctor -v` as well as `flutter run -v`.

[1]: https://stackoverflow.com/help/minimal-reproducible-example

**Comment by Adeel-Sultan** [comment]
[√] Flutter (Channel stable, 3.0.1, on Microsoft Windows [Version 10.0.19044.1766], locale en-PK)
    • Flutter version 3.0.1 at C:\flutterSdk
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (9 weeks ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0-rc1)
    • Android SDK at C:\Users\asultanvm\AppData\Local\Android\sdk
    • Platform android-32, build-tools 32.0.0-rc1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19044.1766]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 103.0.5060.66
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 103.0.1264.44

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

**Comment by Adeel-Sultan** [comment]
flutter run -v :- 
[  +84 ms] executing: [C:\flutterSdk/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +88 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] fb57da5f945d02ef4f98dfd9409a72b7cce74268
[   +1 ms] executing: [C:\flutterSdk/] git tag --points-at fb57da5f945d02ef4f98dfd9409a72b7cce74268
[  +71 ms] Exit code 0 from: git tag --points-at fb57da5f945d02ef4f98dfd9409a72b7cce74268
[        ] 3.0.1
[   +9 ms] executing: [C:\flutterSdk/] git rev-parse --abbrev-ref --symbolic @{u}
[  +55 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\flutterSdk/] git ls-remote --get-url origin
[  +53 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +138 ms] executing: [C:\flutterSdk/] git rev-parse --abbrev-ref HEAD
[  +56 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +96 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +66 ms] executing: C:\Users\asultanvm\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +68 ms] List of devices attached
[   +8 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +7 ms] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +102 ms] Multiple devices found:
[  +36 ms] Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19044.1766]
[   +1 ms] Chrome (web)      • chrome  • web-javascript • Google Chrome 103.0.5060.66
[        ] Edge (web)        • edge    • web-javascript • Microsoft Edge 103.0.1264.44
[   +1 ms] [1]: Windows (windows)
[        ] [2]: Chrome (chrome)
[        ] [3]: Edge (edge)
[   +1 ms] Please choose one (To quit, press "q/Q")
[        ] :

**Comment by Adeel-Sultan** [comment]
@exaby73 do you understand this query?

**Comment by exaby73** [comment]
@Adeel-Sultan You have not provided the entire logs of `flutter run -v`. Please do paste the entire logs and provide a code sample as described [here](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by Adeel-Sultan** [comment]
SingleChildScrollView(
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          SizedBox(height: Get.height * .02),
          heading(),
          visitor.inOutStatus.isEmpty || !isToday
              ? expectedDetails()
              : activityDetails(),
          SizedBox(height: verticalPadding * 2),
          Row(
            children: [
              //some widgets
            ],
          ),
          Row(
            children: [
              //some widgets
            ],
          ),
          passPropertyDetails(),
          Row(
            children: [
              //some widgets
            ],
          ),
          passActionsButtons(),
          hostDetails(),
        ],
      ),
    ),
    
    
    @exaby73 please have a look on code,
    the screenshot which I shared with you is hostDetails() widget.

**Comment by exaby73** [comment]
@Adeel-Sultan I cannot use the code sample you provided since there are missing methods. Can you make a `main.dart` file that as all the code needed and share the entire contents of the `main.dart` file, please?
