### ISSUE TITLE
Not able to compile flutter app in iOS because of image_picker

### ISSUE THREAD

**Issue by vkmittal** [flutter/flutter#108084]
I am compiling my application in iOS and am getting the following error
```
Could not build the precompiled application for the device. Semantic Issue (Xcode): Unknown type name 'FLTMaxSize' /Users/vikkasmiittal/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/image_picker_ios-0.8.5/ios/Classes/FLTImagePickerPlugin_Te st.h:36:39

Semantic Issue (Xcode): Property with 'retain (or strong)' attribute must be of object type /Users/vikkasmiittal/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/image_picker_ios-0.8.5/ios/Classes/FLTImagePickerPlugin_Te st.h:36:0

Semantic Issue (Xcode): Cannot find protocol declaration for 'FLTImagePickerApi' /Users/vikkasmiittal/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/image_picker_ios-0.8.5/ios/Classes/FLTImagePickerPlugin_Te st.h:53:36

Parse Issue (Xcode): Could not build module 'image_picker_ios' /Users/vikkasmiittal/Developer/flutterProj/sportsgiri/ios/Runner/GeneratedPluginRegistrant.m:39:8
```
a) This plugin works absolutely fine in Android
b) Flutter doctor does not show any error 
c) Image picker version that I am using is 0.8.5+3 (the latest one)

Can any one please help me resolving this issue!!

**Comment by maheshmnj** [comment]
Hi @vkmittal, Thanks for filing the issue. Please share the output of `flutter doctor -v` along with the output of `flutter run -v` in a textfile.

**Comment by Sridhar1213** [comment]
i am also getting these errors. Unable to run and archive the application. Unable to upload to testflight. Please help me

**Comment by guisua** [comment]
> You're not running the latest version of `image_picker_ios`; does running `flutter pub upgrade` (or if you don't want to update anything else, `flutter pub upgrade image_picker_ios`) fix this?

After having tried many combinations, `flutter pub upgrade` is the one that did it for me! Thanks @stuartmorgan

**Comment by vkmittal** [comment]
Well - when nothing worked for me - I created a new project, included all the plugins again and compiled - it worked for me!!

**Comment by huycozy** [comment]
> Well - when nothing worked for me - I created a new project, included all the plugins again and compiled - it worked for me!!

@vkmittal Based on the comment, I would like to close this issue as solved. Thank you!
