### ISSUE TITLE
Tree closed on infra failures

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#108050]
For example https://ci.chromium.org/ui/p/flutter/builders/prod/Linux_android%20complex_layout_scroll_perf__memory/2514/overview

This is across many jobs.

**Comment by yusuf-goog** [comment]
looking

**Comment by yusuf-goog** [comment]
Looks like this is due to package install issues:

https://chromium-swarm.appspot.com/task?id=5c3601ea5a2cc210

```23051 2022-07-20 19:59:43.510 E: internal failure: Could not install packages; exit code 2```

@keyonghan potentially similar to the recent issue you had encountered? I believe that was due to an upstream outage?

**Comment by keyonghan** [comment]
Seems similar, both happened on linux12 only. This is not due to upstream, but local corrupted cache/packages.
We should quarantine the bot and move it to staging.

**Comment by yusuf-goog** [comment]
linux-12 has been manually quarantined.

**Comment by zanderso** [comment]
Has this been resolved. It looks like the tree is green again.

**Comment by yusuf-goog** [comment]
We quarantined linux-12 which seemed to be the host that was having issues, so things should be good now.

Please reopen if this happens agains.

**Comment by keyonghan** [comment]
> We quarantined linux-12 which seemed to be the host that was having issues, so things should be good now.

Do we have a bug to track the linux-12? The issue is still there with the bot, and we need to recover and validate the testbed.
