### ISSUE TITLE
Canvas.concat() is poorly named

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#1080]
"skew", "scale", "translate", "setMatrix", etc, have names that sound like they're affecting the canvas' matrix. "concat" sounds like it's concatenating canvases or something. It doesn't spring to mind when scanning the list of methods as being a method that applies the transform.

We should consider maybe renaming it "transform".

**Comment by abarth** [comment]
Let's do this in two steps:

 - [ ] Add the new call.
 - [ ] Remove the old call.

**Comment by Hixie** [comment]
Three steps... the following has to go between the other two:
- [ ] Transition the callers.
