### ISSUE TITLE
flutter 3.0.1 crash dart::SimpleHashMap::Lookup

### ISSUE THREAD

**Issue by zjrwdl** [flutter/flutter#108094]
<img width="1303" alt="image" src="https://user-images.githubusercontent.com/6874049/180185850-7961d5b6-b744-4874-9eca-79e22bc35ce5.png">

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.1, on macOS 11.6 20G165 darwin-x64, locale
zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!

iPhone 8 Plus
15.5 (19F77)

**Comment by zjrwdl** [comment]
@[chinmaygarde](https://github.com/chinmaygarde)
https://github.com/flutter/flutter/issues/106159

**Comment by zjrwdl** [comment]
#22 io.flutter.7.ui

SIGABRT

解析原始
0
libsystem_kernel.dylib
___pthread_kill + 8
2
libsystem_c.dylib
_abort + 124
3
Flutter
dart::SimpleHashMap::Lookup(void*, unsigned int, bool) (hashmap.cc:22)
4
Flutter
dart::ThreadPool::RunImpl(std::__1::unique_ptr<dart::ThreadPool::Task, std::__1::default_delete<dart::ThreadPool::Task> >) (os_thread_macos.cc:0)
5
Flutter
dart::MessageHandler::PostMessage(std::__1::unique_ptr<dart::Message, std::__1::default_delete<dart::Message> >, bool) (memory:2519)
6
Flutter
dart::PortMap::PostMessage(std::__1::unique_ptr<dart::Message, std::__1::default_delete<dart::Message> >, bool) (memory:2519)
7
Flutter
dart::BootstrapNatives::DN_SendPortImpl_sendInternal_(dart::Thread*, dart::Zone*, dart::NativeArguments*) (memory:2519)
8
Flutter
dart::NativeEntry::BootstrapNativeCallWrapper(_Dart_NativeArguments*, void (*)(_Dart_NativeArguments*)) (object.h:477)
9
App
kDartVmSnapshotInstructions + 9760
10
App
kDartIsolateSnapshotInstructions + 375236
11
App
kDartIsolateSnapshotInstructions + 374996
12
App
kDartIsolateSnapshotInstructions + 478436
13
App
kDartIsolateSnapshotInstructions + 419256
14
App
kDartIsolateSnapshotInstructions + 418508
15
App
kDartIsolateSnapshotInstructions + 436976
16
App
kDartIsolateSnapshotInstructions + 232756
17
App
kDartIsolateSnapshotInstructions + 180684
18
App
kDartIsolateSnapshotInstructions + 180556
19
App
kDartIsolateSnapshotInstructions + 9366416
20
App
kDartIsolateSnapshotInstructions + 58276
21
App
kDartIsolateSnapshotInstructions + 6236032
22
App
kDartIsolateSnapshotInstructions + 3336
23
App
kDartIsolateSnapshotInstructions + 59588
24
App
kDartIsolateSnapshotInstructions + 310064
25
App
kDartIsolateSnapshotInstructions + 422472
26
App
kDartIsolateSnapshotInstructions + 232756
27
App
kDartIsolateSnapshotInstructions + 180684
28
App
kDartIsolateSnapshotInstructions + 180556
29
App
kDartIsolateSnapshotInstructions + 9366416
30
App
kDartIsolateSnapshotInstructions + 58276
31
App
kDartIsolateSnapshotInstructions + 6236032
32
App
kDartIsolateSnapshotInstructions + 3336
33
App
kDartIsolateSnapshotInstructions + 59588
34
App
kDartIsolateSnapshotInstructions + 60380
35
App
kDartIsolateSnapshotInstructions + 181284
36
App
kDartIsolateSnapshotInstructions + 181052
37
App
kDartIsolateSnapshotInstructions + 9361328
38
App
kDartIsolateSnapshotInstructions + 9376264
39
App
kDartIsolateSnapshotInstructions + 9362924
40
App
kDartIsolateSnapshotInstructions + 182588
41
App
kDartIsolateSnapshotInstructions + 182288
42
App
kDartIsolateSnapshotInstructions + 182228
43
App
kDartVmSnapshotInstructions + 8984
44
Flutter
dart::DartEntry::InvokeFunction(dart::Function const&, dart::Array const&, dart::Array const&, unsigned long) (dart_entry.cc:0)
45
Flutter
Dart_InvokeClosure (dart_api_impl.cc:4712)
46
Flutter
tonic::DartMicrotaskQueue::RunMicrotasks() (dart_microtask_queue.cc:77)
47
Flutter
fml::MessageLoopImpl::FlushTasks(fml::FlushType) (iterator:1479)
48
Flutter
fml::MessageLoopDarwin::OnTimerFire(__CFRunLoopTimer*, fml::MessageLoopDarwin*) (message_loop_darwin.mm:81)
49
CoreFoundation
___CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 28
53
CoreFoundation
_CFRunLoopRunSpecific + 572
54
Flutter
fml::MessageLoopDarwin::Run() (message_loop_darwin.mm:52)
55
Flutter
__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, (lambda at ../../flutter/fml/thread.cc:79:7)> > (message_loop_impl.cc:0)
56
libsystem_pthread.dylib
__pthread_start + 116

**Comment by maheshmnj** [comment]
Hi @zjrwdl, Are these crashes happening in production? Are there any known reproducible steps to reproduce the crash?

Thanks
