### ISSUE TITLE
flutter engine crash (3.0.1) dart::ScavengerVisitorBase<true>::VisitCompressedPointers

### ISSUE THREAD

**Issue by zjrwdl** [flutter/flutter#108082]
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.1, on macOS 11.6 20G165 darwin-x64, locale
    zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!

<img width="1295" alt="image" src="https://user-images.githubusercontent.com/6874049/180148613-f1802346-4782-4ea7-acab-d5ae6a2982aa.png">

**Comment by huycozy** [comment]
Hi @zjrwdl, thanks for filing the issue.
Could you please provide full crash log and affected devices as well? 
(If the log is too long, please save it to a file and attach it here)

**Comment by zjrwdl** [comment]
#19 io.flutter.5.ui

SIGBUS

BUS_ADRALN

0
Flutter
dart::ScavengerVisitorBase<true>::VisitCompressedPointers(unsigned long, dart::CompressedObjectPtr*, dart::CompressedObjectPtr*) (atomic:998)
1
Flutter
dart::ScavengerVisitorBase<true>::VisitCompressedPointers(unsigned long, dart::CompressedObjectPtr*, dart::CompressedObjectPtr*) (scavenger.cc:506)
2
Flutter
dart::ScavengerVisitorBase<true>::ProcessSurvivors() (scavenger.cc:1335)
3
Flutter
dart::ParallelScavengerTask::RunEnteredIsolateGroup() (scavenger.cc:624)
4
Flutter
dart::Scavenger::Scavenge(dart::GCReason) (os_thread_macos.cc:380)
5
Flutter
dart::Heap::CollectNewSpaceGarbage(dart::Thread*, dart::GCReason) (heap.cc:475)
6
Flutter
dart::Heap::NotifyIdle(long long) (atomic:998)
7
Flutter
flutter::RuntimeController::NotifyIdle(fml::TimePoint) (os_thread_macos.cc:290)
8
Flutter
flutter::Shell::OnAnimatorNotifyIdle(fml::TimePoint) (string:1423)
9
Flutter
fml::MessageLoopImpl::FlushTasks(fml::FlushType) (ref_ptr.h:124)
10
Flutter
fml::MessageLoopDarwin::OnTimerFire(__CFRunLoopTimer*, fml::MessageLoopDarwin*) (message_loop_darwin.mm:81)
11
CoreFoundation
___CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 28
15
CoreFoundation
_CFRunLoopRunSpecific + 572
16
Flutter
fml::MessageLoopDarwin::Run() (message_loop_darwin.mm:52)
17
Flutter
__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, (lambda at ../../flutter/fml/thread.cc:79:7)> > (message_loop_impl.cc:0)
18
libsystem_pthread.dylib
__pthread_start + 116

**Comment by zjrwdl** [comment]
i just met this crash , stack belows :

Flutter
dart::ForwardPointersVisitor::VisitCompressedPointers(unsigned long, dart::CompressedObjectPtr*, dart::CompressedObjectPtr*) (atomic:998)
1
Flutter
dart::ForwardPointersVisitor::VisitCompressedPointers(unsigned long, dart::CompressedObjectPtr*, dart::CompressedObjectPtr*) (become.cc:0)
2
Flutter
dart::UntaggedObject::VisitPointers(dart::ObjectPointerVisitor*) (raw_object.h:434)
3
Flutter
dart::Scavenger::Scavenge(dart::GCReason) (atomic:998)
4
Flutter
dart::Heap::CollectNewSpaceGarbage(dart::Thread*, dart::GCReason) (heap.cc:475)
5
Flutter
dart::Heap::AllocateOld(long, dart::OldPage::PageType) (heap.cc:572)
6
Flutter
dart::Object::Allocate(long, long, dart::Heap::Space, bool) (object.cc:2670)
7
Flutter
dart::Closure::New(dart::TypeArguments const&, dart::TypeArguments const&, dart::TypeArguments const&, dart::Function const&, dart::Context const&, dart::Heap::Space) (object.h:11592)
8
Flutter
DRT_AllocateClosure (runtime_entry.cc:681)

**Comment by huycozy** [comment]
@flutter-symbolizer-bot https://github.com/flutter/flutter/issues/108082#issuecomment-1191411022 flutter#v3.0.1 ios release force x64

**Comment by huycozy** [comment]
@flutter-symbolizer-bot this force ios flutter#v3.0.1 release x64

```
0
Flutter
dart::ScavengerVisitorBase::VisitCompressedPointers(unsigned long, dart::CompressedObjectPtr*, dart::CompressedObjectPtr*) (atomic:998)
1
Flutter
dart::ScavengerVisitorBase::VisitCompressedPointers(unsigned long, dart::CompressedObjectPtr*, dart::CompressedObjectPtr*) (scavenger.cc:506)
2
Flutter
dart::ScavengerVisitorBase::ProcessSurvivors() (scavenger.cc:1335)
3
Flutter
dart::ParallelScavengerTask::RunEnteredIsolateGroup() (scavenger.cc:624)
4
Flutter
dart::Scavenger::Scavenge(dart::GCReason) (os_thread_macos.cc:380)
5
Flutter
dart::Heap::CollectNewSpaceGarbage(dart::Thread*, dart::GCReason) (heap.cc:475)
6
Flutter
dart::Heap::NotifyIdle(long long) (atomic:998)
7
Flutter
flutter::RuntimeController::NotifyIdle(fml::TimePoint) (os_thread_macos.cc:290)
8
Flutter
flutter::Shell::OnAnimatorNotifyIdle(fml::TimePoint) (string:1423)
9
Flutter
fml::MessageLoopImpl::FlushTasks(fml::FlushType) (ref_ptr.h:124)
10
Flutter
fml::MessageLoopDarwin::OnTimerFire(__CFRunLoopTimer*, fml::MessageLoopDarwin*) (message_loop_darwin.mm:81)
11
CoreFoundation
_CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION + 28
15
CoreFoundation
_CFRunLoopRunSpecific + 572
16
Flutter
fml::MessageLoopDarwin::Run() (message_loop_darwin.mm:52)
17
Flutter
__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_deletestd::__1::__thread_struct >, (lambda at ../../flutter/fml/thread.cc:79:7)> > (message_loop_impl.cc:0)
18
libsystem_pthread.dylib
__pthread_start + 116
```

**Comment by huycozy** [comment]
Hi @zjrwdl 
The information from the log above is not enough to investigate the problem. Could you try to get full log from craslytic tool (try finding functionality to export the log to file there)?
