### ISSUE TITLE
Huawei HarmonyOS Black Screen after being in background

### ISSUE THREAD

**Issue by huntrist** [flutter/flutter#108005]
Symptom is similar to https://github.com/flutter/flutter/issues/93276
When app is brought to foreground from background after a while, the APP will stuck in a black screen.
Only after exited (put into background), and reopened (bring back to foreground), the app will function normally.

I have tried all fixes mentioned in https://github.com/flutter/flutter/issues/93276, and the problem persists.
This is seen in Flutter 3.0.5.
The exact trigging condition of the problem is unclear, and it is NOT guaranteed to show on every instance, but can be reproduced fairly often.

I am unable to provide a minimum reproducible example due to the uncertainty of the triggering condition.

flutter doctor -v

```
Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
[√] Flutter (Channel stable, 3.0.5, on Microsoft Windows [Version 10.0.19044.1826], locale zh-CN)
    • Flutter version 3.0.5 at D:\Env\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (7 days ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at D:\Env\Android\SDK
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2021.2)
    • Android Studio at D:\Executable\Android\AndroidStudio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version openjdk version "11.0.12" 2021-07-20

[√] Connected device (4 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)       • windows       • windows-x64    • Microsoft Windows [Version 10.0.19044.1826]
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 103.0.5060.114
    • Edge (web)              • edge          • web-javascript • Microsoft Edge 103.0.1264.62

[√] HTTP Host Availability
    • All required HTTP hosts are available

```

**Comment by danagbemava-nc** [comment]
Hi @huntrist, without a minimal sample, it will be difficult for us to investigate and fully resolve the issue.  That aside, can you provide a couple of extra details?

- How long have you put the app in the background?
- Is this an issue with all Huawei devices or a select few?
- Can you please also check if this happens with a specific flutter project or a newly created flutter project too?

**Comment by huntrist** [comment]
> Hi @huntrist, without a minimal sample, it will be difficult for us to investigate and fully resolve the issue. That aside, can you provide a couple of extra details?
> 
> * How long have you put the app in the background?
> * Is this an issue with all Huawei devices or a select few?
> * Can you please also check if this happens with a specific flutter project or a newly created flutter project too?

1. In my experience, the APP has to be put into background for at least a few mins before the bug shows. The bug almost never shows when reopened immediately.
2. I do not have the resource to test on ALL huawei devices. But I can confirm the bug shows on Mate30 (HarmonyOS), and P50Pro (HarmonyOS). I suspect it is related to the HarmonyOS system, not a device model.
3. I am sure it is NOT related to a specific project. I was able to reproduce the error with the Flutter Gallery APK (v2.9.2). I haven't got the chance to try with a newly created project. Will report back later.

**Comment by danagbemava-nc** [comment]
Hi @huntrist, thanks for the info, if you're able to repro with the sample app, can you share the logs so that we can see if anything goes wrong at the time?

**Comment by huntrist** [comment]
> Hi @huntrist, thanks for the info, if you're able to repro with the sample app, can you share the logs so that we can see if anything goes wrong at the time?

I am not sure how to get the log for the Flutter Gallery APP.
Can you instruct me? I can try to reproduce and share the logs.

**Comment by danagbemava-nc** [comment]
Hi @huntrist, you shouldn't need to use the flutter gallery app if you can repro with the flutter counter app. 

Flutter gallery is a bit too complex for us to narrow down the cause of the issue immediately, but the source code for flutter gallery is open source and you can clone it to attempt to repro. https://github.com/flutter/gallery

**Comment by Lilee902** [comment]
I also encountered the same problem on realme Q3 pro 768G。

my flutter doctor
`
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.5, on macOS 11.6 20G165 darwin-arm, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.69.1)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!
`

**Comment by danagbemava-nc** [comment]
Hi @Lilee902, does it occur for you with the counter app?

**Comment by yk3372** [comment]
I have the same problem. I try dump the layout，it looks like normally. The node is exist.
And I checked the flutter view's visibility in OnResume, it's VISIBLE.
The mini layout dump is :

```xml
<?xml version='1.0' encoding='UTF-8' standalone='yes' ?>
<hierarchy rotation="0">
    <node index="0" text="" resource-id="" class="android.widget.FrameLayout" package="com.test.flutter" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[0,0][1080,2265]">
        <node index="0" text="" resource-id="" class="android.widget.LinearLayout" package="com.test.flutter" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[0,0][1080,2265]">
            <node index="0" text="" resource-id="android:id/content" class="android.widget.FrameLayout" package="com.test.flutter" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[0,0][1080,2265]">
                <node index="0" text="" resource-id="" class="android.widget.FrameLayout" package="com.test.flutter" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="true" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[0,0][1080,2265]">
                    <node index="0" text="" resource-id="" class="android.view.View" package="com.test.flutter" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[0,0][1080,2265]">
                        <node index="0" text="" resource-id="" class="android.view.View" package="com.test.flutter" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[0,0][1080,2265]">
                            <node index="0" text="" resource-id="" class="android.view.View" package="com.test.flutter" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[0,0][1080,2265]">
                                <node index="1" text="" resource-id="" class="android.view.View" package="com.test.flutter" content-desc="作品" checkable="false" checked="false" clickable="true" enabled="true" focusable="true" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[359,105][539,180]" />
                            </node>
                        </node>
                    </node>
                </node>
            </node>
        </node>
    </node>
</hierarchy>
```

And the flutter logs is below:
```log
V/FlutterActivityAndFragmentDelegate( 6493): Forwarding onUserLeaveHint() to FlutterEngine.
V/FlutterActivityAndFragmentDelegate( 6493): onPause()
V/FlutterSurfaceView( 6493): SurfaceHolder.Callback.stopRenderingToSurface()
V/FlutterActivityAndFragmentDelegate( 6493): onStop()
V/FlutterActivityAndFragmentDelegate( 6493): onSaveInstanceState. Giving framework and plugins an opportunity to save state.

// after a few minutes, come back the App.

V/FlutterActivityAndFragmentDelegate( 6493): onStart()
V/FlutterActivityAndFragmentDelegate( 6493): Forwarding onNewIntent() to FlutterEngine and sending pushRoute message.
V/FlutterActivityAndFragmentDelegate( 6493): onResume()
V/FlutterActivityAndFragmentDelegate( 6493): onPostResume()
V/FlutterSurfaceView( 6493): SurfaceHolder.Callback.startRenderingToSurface()
V/FlutterSurfaceView( 6493): SurfaceHolder.Callback.surfaceChanged()
V/FlutterSurfaceView( 6493): Notifying FlutterRenderer that Android surface size has changed to 1080 x 2340
```

All the log looks like normally, but the screen is black. Even the debug label are also not visible...

The screenshot:
![image](https://user-images.githubusercontent.com/1514899/185731351-550ac007-10e4-452f-b3c0-a405df4c598a.png)

flutter doctor: 
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.5 21G72 darwin-arm, locale en-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] Android Studio (version 2021.2)
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.70.2)
[✓] Connected device (3 available)

device: Huawei p30 pro
