### ISSUE TITLE
Feature request - Helper Text in TextField/InputDecoration

### ISSUE THREAD

**Issue by alardizabal** [flutter/flutter#10807]
I'd like to add helper text to a text field. Currently, it's possible to override the error text property to achieve a similar effect. However, when the error text (and the desired error text style) is set, the divider changes color to the theme's error color. The material spec for helper text would meet my requirements.

https://material.io/guidelines/components/text-fields.html#text-fields-layout

<img width="1209" alt="screen shot 2017-06-16 at 11 20 27 pm" src="https://user-images.githubusercontent.com/3614291/27249742-6f2066ac-52ea-11e7-9d63-66a4edcdee9b.png">

**Comment by eseidelGoogle** [comment]
@HansMuller how difficult would this be to add?  Is this something you could look into doing?

**Comment by HansMuller** [comment]
I'm looking into this feature now.
