### ISSUE TITLE
Create a mirror of abseil-cpp on flutter.googlesource.com

### ISSUE THREAD

**Issue by jason-simmons** [flutter/flutter#108189]
The engine's `third_party/abseil-cpp` dependency is currently pulled from a repository owned by Chromium.  The build scripts in the current head of that repository are not fully compatible with the engine source tree.

I'd like to create a mirror of `third_party/abseil-cpp` on https://flutter.googlesource.com/

The mirror should start at the current `main` branch of https://chromium.googlesource.com/chromium/src/third_party/abseil-cpp.git

This is required to unblock the latest roll of Clang into the engine (see https://github.com/flutter/engine/pull/34847)

**Comment by zanderso** [comment]
Marking as P2 because this is blocking a toolchain roll.

**Comment by yusuf-goog** [comment]
Created `third_party/abseil-cpp` repo based on instructions at: https://g3doc.corp.google.com/company/teams/flutter/infrastructure/thirdparty_projects.md?cl=head

**Comment by yusuf-goog** [comment]
Permissions changes: https://flutter-review.googlesource.com/c/third_party/abseil-cpp/+/32101

**Comment by yusuf-goog** [comment]
Cloned at [321355c47e71ce52282100cc0283334a855da544](https://flutter.googlesource.com/third_party/abseil-cpp/+/refs/heads/main/)

**Comment by godofredoc** [comment]
@yusuf-goog can we close this bug?

**Comment by yusuf-goog** [comment]
Only gob commands need to be run, waiting on doc update for setting the default branch for gob.

**Comment by yusuf-goog** [comment]
@godofredoc has the permissions needed and ran the necessary got-ctl command. Everything should be setup now.
