### ISSUE TITLE
TimeOfDay format localization issue in language Persian

### ISSUE THREAD

**Issue by jacobsimionato** [flutter/flutter#108165]
Crossposted from internal issue 239856858

We use flutter library TimeOfDay.format() to construct time like 8:00 AM, 6:00 PM etc. But the localization doesn't work well in certain language.

Locale(s): fa

Issue: With language Persian, linguist reported that number 7 is translated incorrectly to non-Persian(guessing Urdu) character. But number 2 is translated correctly to Persian. See attached screenshot.

Source in EN: 10 PM - 7 AM Current: 22 - """the Urdu character""" Expected: 22 - 7

Code sample & repro steps: Set language to fa and do TimeOfDay(hour: 7).format(context).

Flutter team, can you take a look this issue? Please also check if other numbers translated correctly to Persian(refer like https://images.app.goo.gl/a1SchM5HNzuXyhoL6) The LQA issue is a launch blocking for internal team in September 2022. In order to meet this deadline, we'd need to fix merged on Github by early August in order to leave time to roll to Google.

**Comment by jacobsimionato** [comment]
Hans, would you be able to triage and find an owner for this? It probably makes sense to look at it in tandem with https://github.com/flutter/flutter/issues/108125

**Comment by HansMuller** [comment]
@jacobsimionato - looks like you have the correct owner. We will make sure the translations are updated.

**Comment by thkim1011** [comment]
Quick updates: First of all, this seems to be a font issue as changing the font to a different one with Persian glyphs fixes the issue. Also the issue only happens on web and not on mobile or desktop. Most likely, skia is using an incorrect font to draw the text, and I'm working on figuring out which font is causing the issue.

**Comment by chinmaygarde** [comment]
Triage: From the internal issue, this is an issue in the fallback font that whole fix is being implemented in https://github.com/notofonts/arabic/tree/fix-27.

**Comment by thkim1011** [comment]
I think this is resolved now, so will close.
