### ISSUE TITLE
Dart docs, add AlertDialog example

### ISSUE THREAD

**Issue by branflake2267** [flutter/flutter#10811]
I'd like to suggest adding an AlertDialog example. This way a developer doesn't have to hunt for the wiring procedure. 

https://docs.flutter.io/flutter/material/AlertDialog-class.html
```
  void onSignedInError() {
    var alert = new AlertDialog(
      title: new Text("Sign in Error"),
      content: new Text("There was an error signing in. Please try again."),
    );
    showDialog(context: context, child: alert);
  }
```

**Comment by sethladd** [comment]
Is there a PR for this? (just want to link for those that like to follow along :)

**Comment by Hixie** [comment]
https://github.com/flutter/flutter/pull/10812
