### ISSUE TITLE
I'm having difficult with installing old version of Flutter on M1 macbook air 

### ISSUE THREAD

**Issue by Lazizbek97** [flutter/flutter#108104]
I have tried to install rosetta, but get :
`lazizbekfayziev@Lazizbeks-MacBook-Air bin % sudo softwareupdate --install-rosetta --agree-to-license      
Password:
Installing Rosetta 2 on this system is not supported.
lazizbekfayziev@Lazizbeks-MacBook-Air bin % softwareup`
I have downloaded flutter added its path to .zshrc  and run: 
`zsh: permission denied: flutter`

It's already working fine for flutter 3.0.5 version. But I need to install 2.5.3 version. 
Looking forward,

flutter doctor -v:
lazizbekfayziev@Lazizbeks-MacBook-Air bin % flutter doctor -v
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.4 21F79 darwin-arm (Rosetta), locale en-UZ)
    • Flutter version 3.0.5 at /usr/local/Caskroom/flutter/3.0.5/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (8 days ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/lazizbekfayziev/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.69.2)
    • VS Code at /Users/lazizbekfayziev/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.44.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.4 21F79 darwin-arm (Rosetta)
    • Chrome (web)    • chrome • web-javascript • Google Chrome 103.0.5060.134

[✓] HTTP Host Availability
    • All required HTTP hosts are available

**Comment by stuartmorgan** [comment]
For general support questions, try one of the resources at https://flutter.dev/community#community-grid.

Closing as the issue tracker is specifically for bug reports and feature requests, and neither is applicable to version 2.5 at this point.
