### ISSUE TITLE
Autosubmit should merge older PRs first.

### ISSUE THREAD

**Issue by ditman** [flutter/flutter#108179]
I have observed that when Autosubmit has a list of PRs to pick from, like here:

* https://github.com/flutter/plugins/pulls?q=is%3Apr+is%3Aopen+label%3Aautosubmit

It seems to prefer merging the topmost item from the list.

I don't know if this is a coincidence (I've noticed this a couple of times in the last few days), or that `autosubmit` is actually merging PRs in "Newest" sort.

I think PRs should be merged in "Least Recently Updated" order (`updated-asc`), so things land in the repo more or less in the same order that they were worked on.

**Comment by ditman** [comment]
Maybe it's doing it already, but some of our older PRs never got the "submit-queue" re-checked after a while? :/

**Comment by keyonghan** [comment]
The autosubmit bot is currently querying all queued PRs and process in a random order.

**Comment by ricardoamador** [comment]
Closing as not needed.
