### ISSUE TITLE
Document the correct solution to avoid duplicate `Scrollbar`'s on desktop

### ISSUE THREAD

**Issue by TahaTesser** [flutter/flutter#108159]
I just noticed behavior when testing https://github.com/flutter/flutter/issues/107765.

### Steps to reproduce
1. Copy the sample from https://master-api.flutter.dev/flutter/material/Scrollbar-class.html. 
2. Choose either of the `Scrollbar` and add a custom `thickness: 20.0`.

![Screenshot 2022-07-22 at 11 27 51](https://user-images.githubusercontent.com/48603081/180397835-aac69a0a-975d-43f3-b1af-580bafffc6a7.png)

One of the solutions suggested  in https://github.com/flutter/flutter/issues/102775#issuecomment-1113149073 is to add the following lines
```dart
ScrollConfiguration(
          behavior: ScrollConfiguration.of(context).copyWith(scrollbars: false),
          child: ListView.builder(
              ...
              ...
```

I'm not entirely sure this is the exact solution to this issue. IMO, it should show a single scrollbar when I wrap `ListView` with the `Scrollbar` widget. 

If using `ScrollConfiguration`  to `scrollbars: false` is the correct way, this should be documented in https://master-api.flutter.dev/flutter/material/Scrollbar-class.html with an example. 

cc: @Piinks

**Comment by Piinks** [comment]
> using ScrollConfiguration to scrollbars: false is the correct way

Your expectation is correct! This is because if there are two scrollbars, there is no way for them to know about each other. Covered in this guide: https://docs.flutter.dev/release/breaking-changes/default-desktop-scrollbars

**Comment by TahaTesser** [comment]
@Piinks 
Do you think documenting this in API doc is required? if I missed it there.

**Comment by Piinks** [comment]
There is mention of it here: https://github.com/flutter/flutter/blob/72163a89191f3893515aee23b613f7c96e3ea86d/packages/flutter/lib/src/widgets/scrollbar.dart#L872 Perhaps it just needs an example of overriding it?
