### ISSUE TITLE
is TextSelectionControls not supported on web and desktops?

### ISSUE THREAD

**Issue by guchengxi1994** [flutter/flutter#108156]
Here are some example repos https://github.com/moneyeSir/flutter_text_selection_controls , https://github.com/vilashraj/selectable_text_highlighter using `TextSelectionControls`, but ToolbarItems are  only  displayed on mobiles, is TextSelectionControls not supported on web and desktops?

**Comment by huycozy** [comment]
Hi @guchengxi1994 
I see there's an open issue addressing the case you described #74255 and look at the https://github.com/flutter/flutter/issues/74255#issuecomment-790810610 that explained about TextSelectionControls.
You can leave there your comment and react an upvote to the original comment will help to raise the issue.
Closing as a duplication, so please follow up on it for further updates.
