### ISSUE TITLE
Focused TextField in readOnly state emits continuous Frame Events

### ISSUE THREAD

**Issue by mack-at-pieces** [flutter/flutter#108187]
Hey Flutter Team -

I have identified what seems to be an issue related to a _focused_ `readOnly: true` TextField.

What's happening is the TextField in this state emits a continuous stream of Frame Events reflecting similar behavior to that of a `readOnly: false` TextField where the cursor animates in and out.

Your help would be very much appreciated.

Thanks!

### Steps to reproduce

1. Clone the demo repository here: https://github.com/mack-at-pieces/flutter_text_field
2. Run the demo app in profile mode using the command `flutter run -d macos --profile`.
3. Open the Flutter DevTools debugger and profiler at the link provided by the command output
4. Navigate to the running demo app and tap to bring into focus.
5. At this point, the Frame Chart is idle and no events are occurring.
6. Next, tap the TextField to bring focus as if you are going to input a value.
7. Observe the Frame Chart and you will now see a continuous stream of events being emitted. This represents that of a `readOnly: false` TextField where the cursor animates in and out.

### Demo
https://github.com/mack-at-pieces/flutter_text_field

### Target Platform
macOS

_I did not attempt to reproduce this on Windows, Linux, iOS, or Android, however I believe this problem may still be present on those platforms as well_

### Target OS version/browser
macOS Monterey Version 12.0.1

### Devices
MacBook Pro (16-inch, 2021)
Chip: Apple M1 Max
Memory: 64 GB

## Logs

<details>
<summary>Logs</summary>

```
mackmyers@Macks-MacBook-Pro flutter_text_field % flutter analyze
Analyzing flutter_text_field...                                         
No issues found! (ran in 0.9s)
```

```
mackmyers@Macks-MacBook-Pro flutter_text_field % flutter doctor -v
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.0.1 21A559 darwin-arm (Rosetta), locale en-US)
    • Flutter version 3.0.5 at /Users/mackmyers/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (9 days ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mackmyers/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 67.1.3
    • Dart plugin version 213.7371

[✓] VS Code (version 1.69.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.0.1 21A559 darwin-arm (Rosetta)
    • Chrome (web)    • chrome • web-javascript • Google Chrome 103.0.5060.134

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by darren-pieces** [comment]
# I am also encountering the same bug mentioned above

## Demo (Still happening with flutter 3.0.4)
- Reference this video for context: https://vimeo.com/manage/videos/733077757

## Device info
- Macbook Pro (16 inch 2021)
- Chip M1 max
- Memory 64 gb

**Comment by darshankawar** [comment]
Thanks for the detailed report and steps to replicate @mack-at-pieces 
I tried your code sample on macOS desktop, web (chrome) and on mobile (ios simulator) and noticed same observation, ie, when we tap in the textfield, the `Logging` section in devtools shows continuously emits frame events as below:

1. macOS desktop:


https://user-images.githubusercontent.com/67046386/180724557-02405e49-e7a8-4b45-b844-5badfba03348.mov


2. web (chrome):

<img width="1083" alt="Screenshot 2022-07-25 at 1 07 08 PM" src="https://user-images.githubusercontent.com/67046386/180724749-713842e6-e1bb-4ce6-9d8d-2407fe2296dd.png">


3. mobile (iOS), wherein, the emit is fast as compared to other platforms:

<img width="883" alt="Screenshot 2022-07-25 at 1 10 37 PM" src="https://user-images.githubusercontent.com/67046386/180724797-9e3090e7-0e09-4e95-8dcf-46b64b6bc561.png">

All these observations are similar to when we use `readOnly: false`. Is the expected result here, not to emit the frames when `readOnly: true` ?

**Comment by mack-at-pieces** [comment]
Hey @darshankawar - Thanks for getting back to me. That is exactly correct. 

The reason is because when the TextField is `readOnly: true`, there is no visible widget in the UI that would indicate continuous rebuilds & events (like an animation), and therefore as a developer, you don't know this is the case until opening devtools. Once you open devtools, you wonder why your app is emitting continuous events while the UI is completely idle and in my case, this was the cause.

There may also be unintended side effects of this that I am unaware of.

**Comment by darshankawar** [comment]
Thanks for the update.
Based on my findings [earlier](https://github.com/flutter/flutter/issues/108187#issuecomment-1193706714), adding labels as applicable.

<details>
<summary> stable, master flutter doctor -v </summary>

```

[✓] Flutter (Channel stable, 3.0.5, on macOS 12.2.1 21D62 darwin-x64, locale
    en-GB)
    • Flutter version 3.0.5 at /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (2 days ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

[✓] Flutter (Channel master, 3.1.0-0.0.pre.1861, on macOS 12.2.1 21D62
    darwin-x64, locale en-GB)
    • Flutter version 3.1.0-0.0.pre.1861 on channel master at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ca6cecf034 (7 hours ago), 2022-07-25 15:23:08 -0700
    • Engine revision 7f8925b1f6
    • Dart version 2.19.0 (build 2.19.0-33.0.dev)
    • DevTools version 2.15.0
    
[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.



```

</details>

**Comment by LongCatIsLooong** [comment]
It looks like we do (after https://github.com/flutter/flutter/pull/106893 on macOS the caret no longer uses animation controllers but still the timer is not disabled when it's readonly)

**Comment by mack-at-pieces** [comment]
Hi @darshankawar & team - Is there a timeframe or future Flutter release we could expect this to be addressed?

**Comment by mack-at-pieces** [comment]
@darshankawar @LongCatIsLooong @goderbauer @justinmc just want to say thanks 🤝 looking forward to this being live. going to make some [Pieces](https://pieces.app) users and team members very happy 😄
