### ISSUE TITLE
[go_router] Remove urlPathStrategy

### ISSUE THREAD

**Issue by johnpryan** [flutter/flutter#108132]
The `urlPathStrategy` API is a convenience based on [documentation on URL strategies](https://docs.flutter.dev/development/ui/navigation/url-strategies) for Flutter apps that target the web. We should remove this API and recommend using `flutter_web_plugins` instead:

```dart
import 'package:flutter/material.dart';
import 'package:flutter_web_plugins/url_strategy.dart';

void main() {
  usePathUrlStrategy();
  runApp(ExampleApp());
}
```

**Comment by ahmednfwela** [comment]
is this really necessary ? I think having it there is nice

**Comment by salihgueler** [comment]
Can't we depend on the package in the go_router instead and fix it in the package?

**Comment by chunhtai** [comment]
merged into feature branch. check https://github.com/flutter/flutter/issues/108044 for progress
