### ISSUE TITLE
[in-app-purchase][iOS] Offer Codes implementation

### ISSUE THREAD

**Issue by panhna** [flutter/flutter#108170]
How can we implement Offer Codes on IOS?

I have try it by using presentCodeRedeptionSheet with [in_app_purchase]. But after successfully redeem there is no way to get the transaction back when open the app. So I cannot get the receipt for verification with backend + apple server.

There is no transactions store on SKPaymentQueue.

```
List<SKPaymentTransactionWrapper> transactions = await SKPaymentQueueWrapper().transactions();
```

Thanks in advance

**Comment by darshankawar** [comment]
@panhna 
The plugin `ReadMe` has the section about implementing offer codes using `presentCodeRedemptionSheet` as below:

https://developer.apple.com/documentation/storekit/in-app_purchase/original_api_for_in-app_purchase/subscriptions_and_offers/implementing_offer_codes_in_your_app

And further documentation on how to implement offer codes: https://developer.apple.com/documentation/storekit/in-app_purchase/original_api_for_in-app_purchase/subscriptions_and_offers/implementing_offer_codes_in_your_app

Can you take a look at these and see if it helps ?

**Comment by panhna** [comment]
Thanks @darshankawar for the suggestion.
I will try the native implementation to see if I can receive any transactions on  payment queue.

Because what I have try recently is to check after redeem successfully and user click continue to open the app. So after user open the app, I try to send all transactions using Sentry Log with SKPaymentQueueWrapper to see if we can receive any transaction for verification receipt flow with backend.

```
List<SKPaymentTransactionWrapper> transactions = await SKPaymentQueueWrapper().transactions();
```

But it's not success I got nothing on Sentry. it mean no transactions on PaymentQueue after redeem code successfully. I will try the native one to see if it's difference from in_app_purchase (fluter).

I will explore more and share here.

**Comment by panhna** [comment]
Hi @darshankawar, Hope you a great day.

FYI, I have try PaymentQueue with the native one and it also didn't work as well. Only 1 option left and it success. Probably not a good solution but it work 😁

I'm using `SwiftyStoreKit` to retrieve latest receipt and send back to flutter using `MethodChannel`. This way we able to get receipt and also know who send this receipt to backend. So we able to give user a membership.

```
  SwiftyStoreKit.fetchReceipt(forceRefresh: true) { result in
      switch result {
      case .success(let receiptData):
          let encryptedReceipt = receiptData.base64EncodedString(options: [])
          resultFlutter(encryptedReceipt)
      case .error(_):
          resultFlutter("")
      }
  }
```

> How it work

1. User click on redeem (custom button) and redeem popup `presentCodeRedemptionSheet` appear.
2. User redeem the code and successfully. Apple will send a success transaction to our server (Server-to-server) with some important info ex: TransactionID, offer_code_ref_name, ... etc
3. After User click continue or even close the native popup (redeem popup). I'm using `didChangeAppLifecycleState` to detect assuming user success or failed with redeem code.
4. With `AppLifecycleState.resumed` I have call a native func using MethodChannel to retrieve `Receipt`.
5. After receive receipt from native I have submit it to our backend to extract and check if TransactionID in receipt the same as TransactionID in step #2 and give the user a membership.

_Sentry also a big part to solve this issue since we're not able to make it with with debug. It only work with **App Download From App Store**. So we logged receipt on sentry and debug._

**Comment by darshankawar** [comment]
Thanks for coming back and providing the updates @panhna .
Does that mean the issue is resolved and can be closed ?
