### ISSUE TITLE
Update 1P plugin platform view selection

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#108106]
Currently both `webview_flutter` and `google_maps_flutter` have APIs and README documentation about selecting the Android platform view mode, but as of Flutter 3.0 those options don't actually do anything, so the docs are wrong. We should update them:
- [x] Maps:
  - Fix it so that it switches between HC and TLHC
  - Update the default to HC for now, to work around https://github.com/flutter/flutter/issues/103686
  - Update the README to describe the Flutter 3.0+ behavior
- [ ] Webview:
  - Either:
    - Add a new way to select HC (we don't want to just "fix" the old selection because we want anyone opting out of TLHC for webview to be making a new explicit decision to do it, rather than downgrade what would have been a common option for people to want pre-3.0), or
    - Fully deprecate the switch, and document that it's a no-op. (We don't currently have a compelling case for people to use HC for webview that I know of other than the fallback issue described in https://github.com/flutter/flutter/issues/107313, which we should just fix.)
  - Update the README to describe the Flutter 3.0+ behavior

**Comment by bparrishMines** [comment]
The switch in WebView should be fixed once https://github.com/flutter/engine/pull/34800 makes it to stable.

**Comment by xster** [comment]
For archival purposes, can you just describe what the behavior is at this moment?

**Comment by stuartmorgan** [comment]
> For archival purposes, can you just describe what the behavior is at this moment?

Currently, for Flutter 3.0+:
- Maps has received no changes yet, so no matter which mode you think you are selecting, you actually get TLHC (or, for Android versions below SDK 23, the automatic fallback to VD)
- The same is mostly true of webview; the exception is [the very recent fix for transparency](https://github.com/flutter/plugins/pull/6063), which will cause webview to use HC if the background is transparent (and the pre-2.0 mode the client had selected was HC, but that's the default for webview 4.x).

**Comment by xster** [comment]
Understood, thank you

**Comment by stuartmorgan** [comment]
Per https://github.com/flutter/flutter/issues/104889#issuecomment-1348653282 we should keep (and fix) a Hybrid Composition mode option.

**Comment by stuartmorgan** [comment]
That's https://github.com/flutter/flutter/issues/112208
