### ISSUE TITLE
[CP] Use PorterDuff blend mode when below Android 29

### ISSUE THREAD

**Issue by bparrishMines** [flutter/flutter#108136]
### issue_link

https://github.com/flutter/flutter/issues/104686

### Commit Hash

092481d

### Target

beta

### pr_link

https://github.com/flutter/flutter/pull/108135

### Impacted Users

Customers and plugins using Android Platform Views

### Impact Description

On Android versions below 29, platform views struggle to render when the background is transparent:
<img width="569" alt="something" src="https://user-images.githubusercontent.com/10687576/180320083-f6249494-3123-4534-a048-23436e10e8af.png">
 

### Workaround

Any plugin or app that uses platform views could switch to Hybrid Composition when the background is made transparent. 

### Risk

low

### Test Coverage

yes

### Validation Steps

1. Build a custom engine that changes:

https://github.com/flutter/engine/blob/main/shell/platform/android/io/flutter/plugin/platform/PlatformViewWrapper.java#L172
```
canvas.drawColor(Color.TRANSPARENT, PorterDuff.Mode.CLEAR);
```

to

```
canvas.drawColor(Color.TRANSPARENT);
```

2. Create a Flutter app with webview_flutter. The example app from the plugin also works: [webview_flutter example app](https://github.com/flutter/plugins/tree/main/packages/webview_flutter/webview_flutter_android/example)

3. Set the background to transparent: https://github.com/flutter/plugins/blob/main/packages/webview_flutter/webview_flutter_android/example/lib/main.dart#L137

4. Create and start an Android emulator as Nexus 4 API 28.

5. Run the app and navigate through any webpage.

6. Compare the result to adding the `PorterDuff.Mode.CLEAR` parameter in step 1.

**Comment by bparrishMines** [comment]
cc @stuartmorgan

**Comment by itsjustkevin** [comment]
Thanks @bparrishMines!  As soon as approval from @stuartmorgan comes in, I will push this to the release queue for the next beta hotfix.

**Comment by stuartmorgan** [comment]
I approve https://github.com/flutter/engine/pull/34800 for cherry picking to the beta branch!

I'm assuming we do that by cherry-picking that PR's engine commit and then rolling the beta branch's engine to that new engine commit though. The links above are to the master engine roll, which would give us not the specific engine PR, but everything that's landed in the engine's `main` since the branch point.

**Comment by itsjustkevin** [comment]
Correct @stuartmorgan, I think the commit @bparrishMines was looking for is [7025645](https://github.com/flutter/engine/commit/7025645c52bfaeb1cc67be5ca842b65772c89c8e) at https://github.com/flutter/engine/pull/34800.

Is this the correct commit you'd like to cherry-pick into the next beta hotfix?

**Comment by bparrishMines** [comment]
@itsjustkevin Yes, that's the commit. I created: https://github.com/flutter/flutter/pull/108338. Let me know if this is what you were looking for.

**Comment by itsjustkevin** [comment]
Thanks @bparrishMines, monitoring the cherry-pick.

**Comment by godofredoc** [comment]
CP has landed in the release candidate branch.
