### ISSUE TITLE
[go_router] Remove GoRouterRefreshStream

### ISSUE THREAD

**Issue by johnpryan** [flutter/flutter#108128]
The GoRouterRefreshStream class converts a [Stream](https://api.dart.dev/stable/2.17.6/dart-async/Stream-class.html) into a [Listenable](https://api.flutter.dev/flutter/foundation/Listenable-class.html):

```dart
/// Converts a [Stream] into a [Listenable]
///
/// {@tool snippet}
/// Typical usage is as follows:
///
/// ```dart
/// GoRouter(
///  refreshListenable: GoRouterRefreshStream(stream),
/// );
/// ```
/// {@end-tool}
class GoRouterRefreshStream extends ChangeNotifier {
  /// Creates a [GoRouterRefreshStream].
  ///
  /// Every time the [stream] receives an event the [GoRouter] will refresh its
  /// current route.
  GoRouterRefreshStream(Stream<dynamic> stream) {
    notifyListeners();
    _subscription = stream.asBroadcastStream().listen(
          (dynamic _) => notifyListeners(),
        );
  }

  late final StreamSubscription<dynamic> _subscription;

  @override
  void dispose() {
    _subscription.cancel();
    super.dispose();
  }
}
```

This class should probably be moved to another package and renamed to something that describes its behavior better, like `StreamListenable`.  The Flutter framework could provide a `Listenable.fromStream` constructor, for example.

**Comment by cgutierr-zgz** [comment]
Is there any news on where this StreamListenable will be implemented?
Thanks 👍

**Comment by johnpryan** [comment]
I think we should probably add it to the Flutter SDK itself.

**Comment by chunhtai** [comment]
merged into feature branch. check https://github.com/flutter/flutter/issues/108044 for progress
