### ISSUE TITLE
[go_router] Add support for relative routes

### ISSUE THREAD

**Issue by johnpryan** [flutter/flutter#108177]
In order to support multiple navigation stacks (https://github.com/flutter/flutter/issues/99126), a `RouteState` object should be placed in the widget tree above each route builder to provide a `go()` API that interprets the route path as a relative path to the parent route. The [go_router_prototype](https://pub.dev/packages/go_router_prototype) implements this behavior using the `RouteState` inherited widget.

See also: 
- [go_router_prototype](https://pub.dev/packages/go_router_prototype)
- [flutter.dev/go/go-router-improvements](https://goto.google.com/go-router-improvements)

**Comment by chunhtai** [comment]
copied from
https://github.com/flutter/flutter/issues/99112#issuecomment-1197095743

cc [Skogsfrae](https://github.com/Skogsfrae)

This suggestion only supports relative path in go_router_builder, I think we need a solution too for naive go_router

**Comment by johnpryan** [comment]
Adding a note that we should ensure that all GoRouter builders have a the appropriate BuildContext. See [this comment](https://github.com/flutter/packages/pull/2453#issuecomment-1251239543) for details.

**Comment by predatorx7** [comment]
I use the below code for going to a relative route

```dart
  void goRelative(
    String location, {
    Map<String, String> params = const <String, String>{},
    Map<String, dynamic> queryParams = const <String, dynamic>{},
    Object? extra,
  }) {
    assert(
      !location.startsWith('/'),
      "Relative locations must not start with a '/'.",
    );

    final state = GoRouterState.of(this);
    final currentUrl = Uri.parse(state.location);
    String newPath = '${currentUrl.path}/$location';
    for (final entry in params.entries) {
      newPath.replaceAll(':${entry.key}', entry.value);
    }
    final newUrl = currentUrl.replace(path: newPath, queryParameters: {
      ...currentUrl.queryParameters,
      ...queryParams,
    });

    go(newUrl.toString(), extra: extra);
  }
```

**Comment by rahulraj-idt** [comment]
This is very important feature to reuse navigation paths for app having complex routing logic. Any plan to do this @johnpryan  @chunhtai

**Comment by ThangVuNguyenViet** [comment]
any plan on implement this feature? or is there an alternative way to do this?

**Comment by MartinDawson** [comment]
I'm sorry but how does a major routing library for a major language not have relative paths. This is so unbelievably basic it frustrates me, claude, chatgpt all hallucinate and think this library should have it!

**Comment by ThangVuNguyenViet** [comment]
Well I'm working on it. You can check out my PR if your project needs it now
