### ISSUE TITLE
[go_router] Improve error API

### ISSUE THREAD

**Issue by johnpryan** [flutter/flutter#108144]
Right now there's two parameters for handling errors, `errorPageBuilder` and `errorBuilder`. Users might prefer to handle the exception programmatically and navigate to an app location rather than by building a widget for the error screen. For example, we could provide an API that takes a callback:

```dart
GoRouter(
  onError: (Exception e) {
    // Handle the error...
    return '/home?dialogMessage="Page not found."';
  }
```

**Comment by omar-hanafy** [comment]
@johnpryan 
any updates?
