### ISSUE TITLE
make NavigationDestination integratable with others Navigation widget.

### ISSUE THREAD

**Issue by elbeicktalat** [flutter/flutter#108162]
## Problem

The `NavigationDestination` widget was introduced with the new `NavigationBar` and actually it's coupled with it. This make it hard to reuse.

## Proposal

The proposal in simple words is to make `NavigationDestination` widget usable with other navigation like: `Drawer`.

## Solution
Extract `NavigationDestination` widget and its utils from `NavigationBar` file to remove the coupling with it.

**Comment by exaby73** [comment]
Hello @elbeicktalat. Looks like there is already a proposal for this exact issue https://github.com/flutter/flutter/issues/104813. Closing this one as a duplicate. Please upvote the original issue. Thank you

**Comment by elbeicktalat** [comment]
Hi @exaby73, To me it's different since the #104813 ask to make a common interface for `NavigationDestination` and `NavigationRailDestination` which is not what I'm trying to do here.

If we follow the #104813 approche then we'll end with a few widgets who does the same job like: `NavigationDestination`, `NavigationRailDestination`, `DrawerNavigationDestination` ect.

Feel free to ask any clarification about My proposal, thank you and best regards!

**Comment by TahaTesser** [comment]
@elbeicktalat 
https://github.com/flutter/flutter/issues/104813 is a similar proposal, both proposals suggest decoupling `NavigationDestination` to be usable in other widgets.  Either by extracting the code as you suggest or by creating a base class.


We can extract  `NavigationDestination` and make it usable with `Drawer` and `NavigationRail` and or create a common base class but it's not possible to do both or worth doing so.

I will update the title for https://github.com/flutter/flutter/issues/104813 to make it more flexible to decide which approach is best, come to a single solution.

**Comment by elbeicktalat** [comment]
@TahaTesser Fine! Thanks
