### ISSUE TITLE
Issue from website page Using Custom Fonts, include material design fonts

### ISSUE THREAD

**Issue by branflake2267** [flutter/flutter#10810]
From URL: https://flutter.io/custom-fonts.md

I would suggest showing how to turn on the material design fonts and a list of the fonts supplied with material design. Either link to a page that has them, or show that option here.

**Comment by sethladd** [comment]
Thanks for the suggestion! PR's most welcome.

**Comment by branflake2267** [comment]
https://github.com/flutter/website/pull/606 - hows this? :)

**Comment by zoechi** [comment]
flutter/website#606 was merged so I assume this is fixed.
