### ISSUE TITLE
Route jump

### ISSUE THREAD

**Issue by lhc0229** [flutter/flutter#108148]
Why does the push of the route not destroy the current component？What should I do when I want to push the route and destroy the current component？

**Comment by maheshmnj** [comment]
Hey, you can use [pushReplacement](https://api.flutter.dev/flutter/widgets/Navigator/pushReplacement.html) method like this 

```
Navigator.pushReplacement(context, MaterialPageRoute(builder: (context)=>MyNewPage()));
```

Closing as this is neither a bug nor a feature request.
