### ISSUE TITLE
TimeOfDay.format() localization issue in language 'ta'

### ISSUE THREAD

**Issue by jacobsimionato** [flutter/flutter#108125]
Crossposting from internal issue 238922926 - see that for more context. This issue is blocking a Google app release with a deadline in August. The fix would need to be merged in Github by early September to give it time to roll.

We use flutter library `TimeOfDay.format()` to construct time like 8:00 AM, 6:00 PM etc. But the localization doesn't work well in certain language.

Locale(s) affected: ta

Issue: Linguist reported that the AM mentioned before the numeral value.

Source: 3:00 AM - 9:00 AM
Current: AM 3:00 - AM 9:00
Expected: 3:00 AM - 9:00 AM

Minimal repro steps:
Sample code: `TimeOfDay(hour: 9).format(context)`

Steps:
1. Go to language settings and select language tamil(Locale: ta)
1. Do TimeOfDay(hour: 9).format(context).
1. It will display time as screenshot

**Comment by jacobsimionato** [comment]
It looks like the ICU 'a h:mm' is being used for some locales e.g. `TimeOfDayFormat.a_space_h_colon_mm`. See `MaterialLocalizationTa.timeOfDayFormatRaw`.

**Comment by jacobsimionato** [comment]
Hans, would you be able to triage this?

**Comment by xster** [comment]
Based on https://github.com/flutter/flutter/wiki/Triage#priority-labels and original customer bug b/238115277, I'm setting this to P2
