### ISSUE TITLE
Out of memory exception thrown when passing larger file bytes through method channel in Android platform

### ISSUE THREAD

**Issue by deepika134** [flutter/flutter#108109]
**Description:**  In the Android platform, we have created an application with custom platform specific code to get the images of PDF document pages. So, we have converted the PDF file as Uint8List in the client side and passed those bytes to host side through the method channel. On doing this so, it throws out of memory exception. This happened when a PDF document with the size of 500 MB is converted and passed as bytes through the method channel.

**Code snippet:**

**main.dart**

```
import 'dart:async';
import 'dart:typed_data';

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

class PlatformChannel extends StatefulWidget {
  const PlatformChannel({super.key});

  @override
  State<PlatformChannel> createState() => _PlatformChannelState();
}

class _PlatformChannelState extends State<PlatformChannel> {
  final MethodChannel _channel = MethodChannel('samples.flutter.io/pdf');
  int _pageCount = 0;
  ByteData? bytes;
  Uint8List? _documentBytes;

  Future<Uint8List> _readDocumentData() async {
    bytes = await DefaultAssetBundle.of(context)
        .load('assets/sample.pdf');
    return _documentBytes = bytes!.buffer.asUint8List();
  }

  Future<String?> initializePdfRenderer(Uint8List getBytes) async {
    return _channel.invokeMethod('initializePdfRenderer', <String, dynamic>{
      'documentBytes': getBytes,
    });
  }

  Future<void> result() async {
    Uint8List loadBytes = await _readDocumentData();
    final String? pageCount = await initializePdfRenderer(loadBytes);
    _pageCount = int.parse(pageCount!);
    print(_pageCount);
  }

  @override
  Widget build(BuildContext context) {
    return Material(
      child: Column(
        mainAxisAlignment: MainAxisAlignment.spaceEvenly,
        children: <Widget>[
          Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              Padding(
                padding: const EdgeInsets.all(16.0),
                child: ElevatedButton(
                  onPressed: () async {
                    await result();
                  },
                  child: const Text('Get'),
                ),
              ),
            ],
          ),
        ],
      ),
    );
  }
}

void main() {
  runApp(const MaterialApp(home: PlatformChannel()));
}
```
**MainActivity.java**

```
public class MainActivity extends FlutterActivity {
    private static final String METHOD_CHANNEL = "samples.flutter.io/pdf";
    @Override
    public void configureFlutterEngine(@NonNull FlutterEngine flutterEngine) {

        new MethodChannel(flutterEngine.getDartExecutor(), METHOD_CHANNEL).setMethodCallHandler(
                new MethodCallHandler() {
                    @Override
                    public void onMethodCall(MethodCall call, Result result) {
                         if(call.method.equals("initializePdfRenderer")){
                            result.success(initializePdfRenderer((byte[]) call.argument("documentBytes")));
                        }
                        else {
                            result.notImplemented();
                        }
                    }
                }
        );
    }

    String initializePdfRenderer(byte[] path) {
        try {
            File file = File.createTempFile(
                    ".viewer", ".pdf"
            );
            OutputStream stream = new FileOutputStream(file);
            stream.write(path);
            stream.close();
            return String.valueOf(1);
        } catch (Exception e) {
            return e.toString();
        }
    }
}
```

**Stack trace detail:**

E/AndroidRuntime(25582): java.lang.OutOfMemoryError: Failed to allocate a 542281144 byte allocation with 12582912 free bytes and 253MB until OOM, target footprint 15013128, growth limit 268435456
E/AndroidRuntime(25582):     at io.flutter.plugin.common.StandardMessageCodec.readBytes(StandardMessageCodec.java:320)
E/AndroidRuntime(25582):     at io.flutter.plugin.common.StandardMessageCodec.readValueOfType(StandardMessageCodec.java:386)
E/AndroidRuntime(25582):     at io.flutter.plugin.common.StandardMessageCodec.readValue(StandardMessageCodec.java:340)
E/AndroidRuntime(25582):     at io.flutter.plugin.common.StandardMessageCodec.readValueOfType(StandardMessageCodec.java:434)
E/AndroidRuntime(25582):     at io.flutter.plugin.common.StandardMessageCodec.readValue(StandardMessageCodec.java:340)
E/AndroidRuntime(25582):     at io.flutter.plugin.common.StandardMethodCodec.decodeMethodCall(StandardMethodCodec.java:51)
E/AndroidRuntime(25582):     at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:260)
E/AndroidRuntime(25582):     at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/AndroidRuntime(25582):     at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/AndroidRuntime(25582):     at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/AndroidRuntime(25582):     at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime(25582):     at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(25582):     at android.os.Looper.loop(Looper.java:257)
E/AndroidRuntime(25582):     at android.app.ActivityThread.main(ActivityThread.java:8246)
E/AndroidRuntime(25582):     at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(25582):     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:626)
E/AndroidRuntime(25582):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1016)

**Flutter Doctor log:**

[√] Flutter (Channel stable, 3.0.4, on Microsoft Windows [Version 10.0.19042.1706], locale en-US)
    • Flutter version 3.0.4 at C:\Flutter new SDk 2.5\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 85684f9300 (3 weeks ago), 2022-06-30 13:22:47 -0700
    • Engine revision 6ba2af10bb
    • Dart version 2.17.5
    • DevTools version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\DeepikaRavi\AppData\Local\Android\sdk
    • Platform android-31, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Users\DeepikaRavi\AppData\Local\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.2.5)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.2.32616.157
    • Windows 10 SDK version 10.0.20348.0

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] VS Code (version 1.66.2)
    • VS Code at C:\Users\DeepikaRavi\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19042.1706]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 103.0.5060.114
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 92.0.902.78

[√] HTTP Host Availability
    • All required HTTP hosts are available

**Comment by stuartmorgan** [comment]
> E/AndroidRuntime(25582): java.lang.OutOfMemoryError: Failed to allocate a 542281144 byte allocation with 12582912 free bytes and 253MB until OOM, target footprint 15013128, growth limit 268435456

Can you elaborate on what you believe the Flutter bug here is? Passing data via method channels involves copying data, so best-case scenario this is going to use 1GB of memory; according to the logs you just don't have enough memory available on the device to copy it.

Is there a reason that you are copying the data rather than using a `Texture`? If you have to copy it, do you have to pass all 500MB at once?

**Comment by deepika134** [comment]
Hi stuartmorgan,

Can you elaborate on what you believe the Flutter bug here is?
We only pass the converted PDF file as Uint8List from the client side to the host side through the method Chanel and we did not perform any conversion in custom specific code, but we are getting the out-of-memory exception.

```
Future<Uint8List> _readDocumentData() async {
    bytes = await DefaultAssetBundle.of(context)
        .load('assets/sample.pdf');
    return _documentBytes = bytes!.buffer.asUint8List();
  }
```

We used the Android Samsung m31s device for testing and the device specifications:
Memory: 128GB 6GB RAM
Android version: 12
Display: 1080 x 2400 pixels

Regards,
Deepika

**Comment by huycozy** [comment]
Hi @deepika134 

> E/AndroidRuntime(25582): java.lang.OutOfMemoryError: Failed to allocate a 542281144 byte allocation with 12582912 free bytes and 253MB until OOM, target footprint 15013128, growth limit 268435456

Based on above log, could you try this workaround to see if the issue still reproduces?
https://stackoverflow.com/a/32245018/5921933
