### ISSUE TITLE
Engine builds for Android on Mac always look for gen_snapshot in the default clang_x64 directory

### ISSUE THREAD

**Issue by flar** [flutter/flutter#108238]
The paths for `gen_snapshot` are hard-coded in `src/flutter/sky/tools/create_macos_gen_snapshots.py` to be expected in the `clang_x64` subdirectory, but will be found in the `clang_arm64` directory on builds on Apple Silicon machines.

**Comment by rmacnak-google** [comment]
Duplicate of https://github.com/flutter/flutter/issues/105651
