### ISSUE TITLE
Increase the minimum version of iOS in a Flutter Module from 9.0 to 10.0

### ISSUE THREAD

**Issue by ParasGarg7** [flutter/flutter#108282]
Is there a way to increase the minimum version of iOS in a Flutter Module from 9.0 to 10.0?
The problem is that some of the dependencies which I am using requires iOS 10.0 as the minimum version. So to do so, after every flutter clean, I need to open Podfile and update it every time.
This is not a problem in a flutter project since the Podfile there is not deleted upon flutter clean.

## Steps to Reproduce

1. Add Firebase_core to pubspec.yaml with version `firebase_core: 1.3.0`
2. Run `flutter pub get`.
3. `cd .ios`
4. `pod install`

## Logs

<details>
<summary>Logs</summary>
[!] CocoaPods could not find compatible versions for pod "firebase_core":
  In Podfile:
    FlutterPluginRegistrant (from `Flutter/FlutterPluginRegistrant`) was resolved to 0.0.1, which depends on
      firebase_core

    firebase_core (from `.symlinks/plugins/firebase_core/ios`)

Specs satisfying the `firebase_core (from `.symlinks/plugins/firebase_core/ios`), firebase_core` dependency were found, but they required a higher minimum deployment target.

</details>

**Comment by huycozy** [comment]
Hi @ParasGarg7 
Which configuration do you need to change in `Podfile`?
From my side, after adding `firebase_core` plugin, the log is different than yours as below (The Podfile is not changed from default Flutter project)

<details>
<summary>Logs (pod install)</summary>

```bash
➜  ios pod install
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/universal-darwin21/rbconfig.rb:230: warning: Insecure world writable dir /Users/huynq/Documents/GitHub/flutter/bin in PATH, mode 040777
Analyzing dependencies
firebase_core: Using Firebase SDK version '8.0.0' defined in 'firebase_core'
Downloading dependencies
Installing Firebase (8.0.0)
Installing FirebaseCore (8.0.0)
Installing FirebaseCoreDiagnostics (8.15.0)
Installing Flutter (1.0.0)
Installing Google-Mobile-Ads-SDK (8.13.0)
Installing GoogleAppMeasurement (8.15.0)
Installing GoogleDataTransport (9.1.4)
Installing GoogleUserMessagingPlatform (2.0.0)
Installing GoogleUtilities (7.7.0)
Installing PromisesObjC (2.1.1)
Installing firebase_core (1.3.0)
Installing google_mobile_ads (0.0.1)
Installing nanopb (2.30908.0)
Generating Pods project
Integrating client project
Pod installation complete! There are 3 dependencies from the Podfile and 13 total pods installed.

[!] Automatically assigning platform `iOS` with version `11.0` on target `Runner` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

[!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target `Runner` to `Target Support Files/Pods-Runner/Pods-Runner.profile.xcconfig` or include the `Target Support Files/Pods-Runner/Pods-Runner.profile.xcconfig` in your build configuration (`Flutter/Release.xcconfig`).
```
</details>

**Comment by ParasGarg7** [comment]
Hi @huycozy,
Is this logs for a Flutter Project or a Flutter Module?

**Comment by huycozy** [comment]
@ParasGarg7 Sorry, I tested on Flutter Project. 
I see there's an open issue addressing the case you described #78862
You can leave there your comment and react an upvote to the original comment will help to raise the issue.
Closing as a duplication, so please follow up on it for further updates.  If you disagree, please write in the comments and I will reopen it.
Thank you!
