### ISSUE TITLE
firebase database plugin keepSynced function doesn't work, throws error

### ISSUE THREAD

**Issue by KevinTheGray** [flutter/flutter#10822]
## Steps to Reproduce
- Use an android device
- Use `firebase_database: "^0.0.7"`
- Call keepSynced, see error

## Logs
```
E/flutter (30887): [ERROR:../../lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter (30887): MissingPluginException(No implementation found for method Query#keepSynced on channel plugins.flutter.io/firebase_database)
E/flutter (30887): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:153:7)
E/flutter (30887): <asynchronous suspension>
E/flutter (30887): #1      Query.keepSynced (package:firebase_database/src/query.dart:170:31)
E/flutter (30887): #2      new NewsFeedManager._internal (package:kingkong/managers/news_feed_manager.dart:52:25)
E/flutter (30887): #3      NewsFeedManager._newsFeedManager (package:kingkong/managers/news_feed_manager.dart:45:11)
E/flutter (30887): #4      NewsFeedManager._newsFeedManager (package:kingkong/managers/news_feed_manager.dart:44:32)
E/flutter (30887): #5      new NewsFeedManager (package:kingkong/managers/news_feed_manager.dart:48:12)
E/flutter (30887): #6      new _NewsFeedComponentState (package:kingkong/components/newsfeed/news_feed_component.dart:29:41)
E/flutter (30887): #7      new NewsFeedComponent (package:kingkong/components/newsfeed/news_feed_component.dart:19:46)
E/flutter (30887): #8      new _MainComponentState (package:kingkong/components/main/main_component.dart:38:31)
E/flutter (30887): #9      new MainComponent (package:kingkonf/components/main/main_component.dart:20:42)
E/flutter (30887): #10     new AppState (package:kingkong/components/app/app_state.dart:22:44)
E/flutter (30887): #11     App.createState (package:kingkong/components/app/app.dart:15:16)
E/flutter (30887): #12     new StatefulElement (package:flutter/src/widgets/framework.dart:3461:23)
E/flutter (30887): #13     StatefulWidget.createElement (package:flutter/src/widgets/framework.dart:734:42)
E/flutter (30887): #14     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2748:40)
E/flutter (30887): #15     Element.updateChild (package:flutter/src/widgets/framework.dart:2553:12)
E/flutter (30887): #16     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:732:16)
E/flutter (30887): #17     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:703:5)
E/flutter (30887): #18     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:649:17)
E/flutter (30887): #19     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2122:19)
E/flutter (30887): #20     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:648:13)
E/flutter (30887): #21     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding&WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:543:7)
E/flutter (30887): #22     runApp (package:flutter/src/widgets/binding.dart:581:7)
E/flutter (30887): #23     main (/data/user/0/com.kingkong.app/cache/kingkong-flutterV2MhKb/kingkong-flutter/lib/main.dart:11:3)
E/flutter (30887): #24     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:265)
E/flutter (30887): #25     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

## Flutter Doctor
[✓] Flutter (on Mac OS X 10.12.4 16E195, locale en-US, channel master)
    • Flutter at /Users/KG/Developer/Flutter/flutter
    • Framework revision 6965312822 (2 days ago), 2017-06-16 10:05:18 -0700
    • Engine revision 784e975672
    • Tools Dart version 1.24.0-dev.6.7

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.0)
    • Android SDK at /Users/KG/Library/Android/sdk
    • Platform android-26, build-tools 26.0.0
    • ANDROID_HOME = /Users/KG/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.3.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3.3, Build version 8E3004b
    • ios-deploy 1.9.1
    • CocoaPods version 1.2.1

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Gradle version 3.2
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.1.4)
    • Flutter plugin version 14.0
    • Dart plugin version 171.4694.29

[✓] Connected devices
    • Android SDK built for x86 • emulator-5554                            • android-x86 • Android 7.0 (API 24) (emulator)
    • Nexus 5X                  • 0106bcc49c8ca3eb                         • android-arm • Android 7.1.2 (API 25)
    • Kevin's iPhone            • c95c86bdc3aac565adb373de3dc2dbedcdecc900 • ios         • iOS 10.3.1 (14E304)
    • iPhone 5s                 • AB2FA880-541C-49D7-BDB2-9720261982A3     • ios         • iOS 10.3 (simulator)

**Comment by eseidelGoogle** [comment]
Looks like the Android implementation of this feature is missing?  @collinjackson

**Comment by collinjackson** [comment]
Fixed in flutter/plugins#144 (version 0.0.8)

**Comment by CharlesCleveJr** [comment]
What's the proper way to implement the keepSync property on a Flutter Firebase query or reference?

**Comment by collinjackson** [comment]
@CharlesCleveJr documentation for `keepSynced `is here:

https://www.dartdocs.org/documentation/firebase_database/0.1.0/firebase_database/Query/keepSynced.html

Please open a new issue if it isn't working for you.

**Comment by kroikie** [comment]
@KevinTheGray

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/994. Any further collaboration will be done there.
