### ISSUE TITLE
Figure out how to test plugins (on OEM side)

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#10824]
Currently our plugin template and plugin docs have no recommendation for how to test a plugin. We should probably figure out what to do here.

**Comment by goderbauer** [comment]
We also need a story for testing the native side of a plugin. Looking at flutter/plugins most (all?) of our first-party plugins only test the dart side of things.

**Comment by mit-mit** [comment]
Yes, definitely, I consider that part of the scope of this bug!

**Comment by Hixie** [comment]
This seems like something that could be classified as plugin framework maintenance, so I'm leaving this in the current milestone. Please move it out of this milestone if it is not on your near-term radar. Thanks.

**Comment by mit-mit** [comment]
Punting to M4

**Comment by roughike** [comment]
I'm interested in working on this issue. The Android implementation of image_picker currently has a pretty good test coverage and [the tests can be found here](https://github.com/flutter/plugins/tree/master/packages/image_picker/example/android/app/src/test). I've started to investigate on bringing the iOS implementation under tests as well.

@mit-mit Just to be clear, what is required to consider this issue resolved?

Is it:
* modifying the plugin templates to include necessary setup and sample tests for Android and iOS implementations of the plugin
* creating a "Testing plugins" article (or section in the Plugins documentation) on the flutter.io website
* both
* something else?

**Comment by mit-mit** [comment]
_cc @mravn-google for his thoughts also_

Fantastic to hear that you are looking into this! I think the ideal solution would indeed include considering templates and documentation. But I also wonder if an ideal solution would need to include a test framework capable of spanning both Flutter and native? For example, write a test that triggers an action in the Flutter UI, and then tests for a reaction in the native UI. How are you handling that type of use case (e.g. click a button in Flutter that opens the Gallery in native)?

**Comment by fmatosqg** [comment]
@roughike I see you mention tests for image_picker, but they're implemented in the example app inside that project.

I think we should have unit tests that don't involve apps, but I don't know what's the official way around it. People have been manually adding `compile ... flutter.jar` to their plugin gradles, but that's a hack at best. If there is an alternative way of doing it I'd love to learn about it. So far there's no mention of flutter except it's either a full fledged app or a plugin example app.

**Comment by roughike** [comment]
> But I also wonder if an ideal solution would need to include a test framework capable of spanning both Flutter and native?

More like integration or end-to-end tests? That would be awesome, but I have no idea currently how to do those.

My current idea, that has worked pretty well, has been this:
* extract the heavy plugin logic into a `delegate` class; see [ImagePickerDelegate.java](https://github.com/flutter/plugins/blob/master/packages/image_picker/android/src/main/java/io/flutter/plugins/imagepicker/ImagePickerDelegate.java)
* the plugin class that handles the `MethodChannel` registration should now be really lean. It should only determine what method we want to do and then rely on the `delegate` class to do the actual work; see [ImagePickerPlugin.java](https://github.com/flutter/plugins/blob/master/packages/image_picker/android/src/main/java/io/flutter/plugins/imagepicker/ImagePickerPlugin.java)

With this setup, we can:
* test the plugin contract on the implementation side by mocking the `delegate` class; see [ImagePickerPluginTest.java](https://github.com/flutter/plugins/blob/master/packages/image_picker/example/android/app/src/test/java/io/flutter/plugins/imagepicker/ImagePickerPluginTest.java)
* if needed, test that the `delegate` class does the things we want. Relying heavily on mocking every dependency; see [ImagePickerDelegateTest.java](https://github.com/flutter/plugins/blob/master/packages/image_picker/example/android/app/src/test/java/io/flutter/plugins/imagepicker/ImagePickerDelegateTest.java)

I expect we can use a similar approach for iOS as well. Of course, this doesn't test the Dart -> MethodChannel -> native implementation end-to-end, but I feel this is still a reasonable way.

**Comment by roughike** [comment]
> I see you mention tests for image_picker, but they're implemented in the example app inside that project.

@fmatosqg The tests test only the plugin and don't really depend on the example app. The tests can be moved from `example/android` to `android` directory, but last time I did it, I had problems with the imports regarding the `MethodChannel` apis; moving the tests under the `example/android` directory solved those problems.

So the tests actually test the `image_picker` plugin and nothing else, but they just live inside `example/android` directory because otherwise they wouldn't compile.

**Comment by yjbanov** [comment]
@roughike, your suggestion makes sense. `flutter_driver` may not be required for some tests. We have [LiveTestWidgetsFlutterBinding](https://docs.flutter.io/flutter/flutter_test/LiveTestWidgetsFlutterBinding-class.html) that you can `flutter run`. `flutter_driver` is useful when you are testing performance, or need to script things like saving screenshots and/or call `adb` commands from within the test.

That said, neither `LiveTestWidgetsFlutterBinding` nor `flutter_driver` give you a way to choose between real and mock plugin implementations, so something like what you are suggesting is needed for completeness.

**Comment by jules15** [comment]
On a superficial reading, I see that Dart's canonical testing framework has "plugins" for running Dart unit tests 1. In a VM, and 2. In a browser. The documentation implies that their plugin approach should allow for other implementations, perhaps a Flutter/iOS/Android plugin??

I will like to be able to run Dart unit tests on-device, so that my tests can use the plugins on which my classes depend. This is currently a real omission. Currently this is not possible without rigging up my own testing framework for invocation using the flutter "driver". An alternative is to do regular testing and mock-out the plugins, but this gives me less confidence.

**Comment by jaumard** [comment]
I agree that we should be able to unit test inside the plugin and not under the example app. For now putting manually the flutter.jar inside the gradle file look good enough for but it should be at least mention somewhere in the doc. 

Here is what I put in my gradle to make test ok
```
dependencies {
    ...
    testImplementation files(getFlutterDependencyPath())
}

String getFlutterDependencyPath() {
    def localProperties = new Properties()
    def localPropertiesFile = rootProject.file('local.properties')
    if (localPropertiesFile.exists()) {
        localPropertiesFile.withReader('UTF-8') { reader ->
            localProperties.load(reader)
        }
    }

    def flutterRoot = localProperties.getProperty('flutter.sdk')
    if (flutterRoot == null) {
        throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
    }

    java.nio.file.Path baseEnginePath = Paths.get(flutterRoot, "bin", "cache", "artifacts", "engine")
    String targetArch = 'arm'
    if (project.hasProperty('target-platform') &&
            project.property('target-platform') == 'android-arm64') {
        targetArch = 'arm64'
    }
    return "$baseEnginePath/android-$targetArch/flutter.jar"
}
```

Your idea to be able to test end to end from dart to native is really good too ! Would be awesome to be able to test this (without a device)

**Comment by bizz84** [comment]
I can add one more use case here for context.

I opened a PR in [flutter/plugins/#1159](https://github.com/flutter/plugins/pull/1159) to add support for passwordless sign in in Firebase Auth.

This requires some plugin code to call native APIs, and some platform code to handle incoming dynamic links.

Perhaps moving towards a full end-to-end test would be valuable here, as the entire flow for passwordless sign in requires that:

1. clients can use the plugin to call into the native APIs
2. clients can register to receive dynamic links via an `EventChannel` that is created by the host app.
3. project-level configuration is done correctly.

Some level of testing could probably be done for points 1 and 2. However tests that cover point 1 would belong to `firebase_auth`, and tests that cover point 2 would belong to `firebase_dynamic_links`, which are two separate packages.

So how should we test for use cases that require two (or more) separate firebase packages to work correctly (plus some configuration that is external to both)?

**Comment by Ehesp** [comment]
Has there been any progress on this front @mit-mit?

I'm playing around with a Flutter Plugin (pure Android/iOS integration calling an underlying API), so no views/widgets involved.  Obviously mocking the service will only catch so much.

Having to write both Dart / Java tests is a bit overkill for my use-case, as ideally it makes more sense to do a full end-to-end testing what's been sent over the Channel and returned is handled correctly on both Dart & Native. I

I'm also having to do:

```kt
override fun onMethodCall(call: MethodCall, result: Result) {
    @Suppress("UNCHECKED_CAST") val arguments = call.arguments as Map<String, Any>
```
Therefore I kind of need to ensure what I'm passing to native from Dart is correctly cast, something which doing Dart / Java tests separately won't catch.

**Comment by mit-mit** [comment]
cc @csells for an update

**Comment by collinjackson** [comment]
We are currently integration testing many of the first-party flutter plugins with package:test tests that run on-device in the same isolate as the example app of the plugin being tested. You can find instructions for how to run these tests here:

https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md#running-the-tests

Here are some examples:

https://github.com/flutter/plugins/blob/master/packages/cloud_firestore/example/test_driver/cloud_firestore.dart

https://github.com/flutter/plugins/blob/master/packages/cloud_functions/example/test/cloud_functions.dart

https://github.com/flutter/plugins/blob/master/packages/webview_flutter/example/test_driver/webview.dart

Documentation of plugin integration testing is currently pretty limited; I'm making some some improvements to how plugins are tested and will document that more fully once we've had a chance to try it out on some of our plugins.

**Comment by Ehesp** [comment]
Thanks Collin @collinjackson.

I got it working from those examples 👍 To be honest, that's not too different from the docs on the Flutter website currently. The only thing which it doesn't explain is:

```dart
void main() async {
  final FlutterDriver driver = await FlutterDriver.connect();
  await driver.requestData(null, timeout: const Duration(minutes: 1));
  driver.close();
}
```

**Comment by c1avie** [comment]
@collinjackson 
Is there any new progress in this issue? The links above are 404。

**Comment by izio38** [comment]
In my opinion, it would be awesome to have a complete guide/example on how to test plugin in flutter. Specifically, testing the Flutter -> Native platforms contract, and vice-versa.

**Comment by nightscape** [comment]
This page looks relevant: https://github.com/flutter/flutter/wiki/Plugin-Tests

**Comment by jvretamero** [comment]
Complementing what @nightscape shared, there is also an official page in the docs: https://docs.flutter.dev/development/packages-and-plugins/plugins-in-tests

**Comment by stuartmorgan** [comment]
That's not about testing plugins themselves, it's about testing code that uses plugins when the host side of the plugin isn't present.

**Comment by stuartmorgan** [comment]
The plugin template now contains scaffolding/examples for:
- Flutter integration tests
- native unit tests in every supported language

That's the vast majority of the coverage that we are using in our 1P plugins, so I think that's sufficient for the template. (The only thing that's not covered is native integration tests, such as XCUITest and Robolectric; those are more complex and generally only needed when the plugin requires interacting directly with native UI; we may eventually document them, but aren't something we need in the template).

https://github.com/flutter/flutter/issues/96421 covers documenting this once it reaches `stable`; given that the remaining work is tracked there, I'm going to go ahead and close this.
