### ISSUE TITLE
Spawn's engine throws a MissingPluginException

### ISSUE THREAD

**Issue by Nayuta403** [flutter/flutter#108272]
The Spawn engine calls EntryPoint directly on the UI thread and plugin registration on the Platform thread. If the plugin is called with `await` in EntryPoint (in real scenarios such as waiting for some data to be initialized), At this point, an exception may occur if the plugin is not registered.

source code：

Spawn Engine run EntryPoint：

https://github.com/flutter/engine/blob/d8c49e185e88bd218c62308eacb9490a39f488da/shell/common/shell.cc#L549

The plugin registry：

https://github.com/flutter/engine/blob/d8c49e185e88bd218c62308eacb9490a39f488da/shell/platform/android/io/flutter/embedding/engine/FlutterEngine.java#L356-L358

The engine for `spawn` means that construction and execution of EntryPoint occur simultaneously. But for `new` engine, the two are separate, so I can register the plugin ahead of time to make sure EntryPoint executes properly.

So my question is, can we not `runEngine` directly in shell::spawn? If so, Spawn engine will look the same as new if don't do this. And then  embedded layer without having to deal with their differences, they won't have this problem like: https://github.com/flutter/flutter/issues/78931

Some issues related to this issue are as follows:
https://github.com/flutter/flutter/issues/97424
https://github.com/flutter/flutter/issues/99504
https://github.com/flutter/flutter/issues/103483
https://github.com/flutter/flutter/issues/59951

## Steps to Reproduce
This [example](https://github.com/Nayuta403/multiple_flutters/tree/channel) is based on the [multiple_flutters](https://github.com/flutter/samples/tree/master/add_to_app/multiple_flutters/multiple_flutters_android) modification

The main modifications are as follows:
1. await plugin in main, this plugin is a custom I made on the Java side
```dart
void main() async{
  // ADD START
  WidgetsFlutterBinding.ensureInitialized();
  print('Nayuta main invoker wait for multiple-flutters response');
  MethodChannel channel = const MethodChannel("multiple-flutters");
  await channel.invokeMethod("test");
  print('Nayuta multiple-flutters test invoked');
  // ADD END
  runApp(MyApp(color: convertNumberToColor(count)));
}
```
2. In Java, the plugin is registered with a delay of 100 milliseconds (simulating a more time-consuming case)
```java
EngineBindings.kt:
    init {
        val app = activity.applicationContext as App
        // This has to be lazy to avoid creation before the FlutterEngineGroup.
        val dartEntrypoint =
            DartExecutor.DartEntrypoint(
                FlutterInjector.instance().flutterLoader().findAppBundlePath(), entrypoint
            )
        engine = app.engines.createAndRunEngine(activity, dartEntrypoint, initialRoute);
        this.delegate = delegate
        Handler(Looper.getMainLooper()).postDelayed({
            Log.i("Nayuta", " multiple-flutters channel register ")
            channel = MethodChannel(engine.dartExecutor.binaryMessenger, "multiple-flutters")
            attach()
        }, 100)

    }
```

3. Execute `flutter run` on the code sample 
4. Keep clicking on the `next` button, and you may get ANR(on start SingleFlutterActivity) or a white screen FlutterView(on start DoubleFlutterActivity)... Sometimes it's ANR and sometimes it's a white screen 

**Expected results:** 
SingleFlutterActivity started successfully, DoubleFlutterActivity displays two FlutterView

**Actual results:** 
ANR(on start SingleFlutterActivity)

https://user-images.githubusercontent.com/40540394/180709303-f027d352-46b1-426c-99e2-088fcefefa77.mp4

white screen FlutterView(on start DoubleFlutterActivity)

https://user-images.githubusercontent.com/40540394/180709739-51ad7686-70c9-49c1-af29-c3833c434e81.mp4

<details>
<summary>Code sample</summary>

https://github.com/Nayuta403/multiple_flutters/tree/channel

</details>

<details>
  <summary>Logs</summary>

You can search for `Nayuta` in the log to find out when the plugin was called and registered

```
15:09:47.737 22799-22799 V/FlutterActivity: Using the launch theme as normal theme.
15:09:47.737 22799-22799 V/FlutterActivityAndFragmentDelegate: Setting up FlutterEngine.
15:09:47.739 22799-22799 V/DartMessenger: Setting handler for channel 'flutter/isolate'
15:09:47.739 22799-22799 V/DartExecutor: Attached to JNI. Registering the platform message handler for this Dart execution context.
15:09:47.739 22799-22799 V/DartMessenger: Setting handler for channel 'flutter/accessibility'
15:09:47.739 22799-22799 V/DartMessenger: Setting handler for channel 'flutter/deferredcomponent'
15:09:47.739 22799-22799 V/DartMessenger: Setting handler for channel 'flutter/localization'
15:09:47.739 22799-22799 V/DartMessenger: Setting handler for channel 'flutter/mousecursor'
15:09:47.739 22799-22799 V/DartMessenger: Setting handler for channel 'flutter/navigation'
15:09:47.739 22799-22799 V/DartMessenger: Setting handler for channel 'flutter/platform'
15:09:47.739 22799-22799 V/DartMessenger: Setting handler for channel 'flutter/restoration'
15:09:47.739 22799-22799 V/DartMessenger: Setting handler for channel 'flutter/textinput'
15:09:47.740 22799-22799 V/FlutterActivityAndFragmentDelegate: Attaching FlutterEngine to the Activity that owns this delegate.
15:09:47.740 22799-22799 V/DartMessenger: Setting handler for channel 'flutter/platform_views'
15:09:47.740 22799-22799 V/FlutterActivityAndFragmentDelegate: onRestoreInstanceState. Giving framework and plugins an opportunity to restore state.
15:09:47.740 22799-22799 V/FlutterActivityAndFragmentDelegate: Creating FlutterView.
15:09:47.741 22799-22799 V/FlutterView: Initializing FlutterView
15:09:47.741 22799-22799 V/FlutterView: Internally using a FlutterSurfaceView.
15:09:47.741 22799-22799 V/FlutterActivityAndFragmentDelegate: Attaching FlutterEngine to FlutterView.
15:09:47.741 22799-22799 V/FlutterView: Attaching to a FlutterEngine: io.flutter.embedding.engine.FlutterEngine@de5556d
15:09:47.741 22799-22799 V/FlutterSurfaceView: Attaching to FlutterRenderer.
15:09:47.742 22799-22799 V/DartMessenger: Sending message with callback over channel 'flutter/textinput'
15:09:47.744 22799-22799 V/SettingsChannel: Sending message: 
    textScaleFactor: 1.0
    alwaysUse24HourFormat: false
    platformBrightness: light
15:09:47.744 22799-22799 V/DartMessenger: Sending message with callback over channel 'flutter/settings'
15:09:47.746 22799-22799 V/LocalizationChannel: Sending Locales to Flutter.
15:09:47.746 22799-22799 V/LocalizationChannel: Locale (Language: zh, Country: CN, Variant: )
15:09:47.746 22799-22799 V/LocalizationChannel: Locale (Language: en, Country: US, Variant: )
15:09:47.746 22799-22799 V/DartMessenger: Sending message with callback over channel 'flutter/localization'
15:09:47.754 22799-22799 V/FlutterActivityAndFragmentDelegate: onStart()
15:09:47.755 22799-22799 V/FlutterActivityAndFragmentDelegate: onResume()
15:09:47.755 22799-22799 V/LifecycleChannel: Sending AppLifecycleState.resumed message.
15:09:47.755 22799-22799 V/DartMessenger: Sending message with callback over channel 'flutter/lifecycle'
15:09:47.755 22799-22799 V/FlutterActivityAndFragmentDelegate: onPostResume()
15:09:47.760 22799-22799 D/ViewRootImpl: support adaptive color gamut feature!
15:09:47.765 22799-22799 D/ViewRootImpl[MainActivity]: windowFocusChanged hasFocus=false inTouchMode=true
15:09:47.768 22799-22799 D/OpScreenModeManager: setRefreshRate parent io.flutter.embedding.android.FlutterView{f4d8ea1 VFE...... ......I. 0,0-0,0 #1} parent width 0 parent height 0 mRatio 1.2
15:09:47.768 22799-22799 D/OpScreenModeManager: setRefreshRate view io.flutter.embedding.android.FlutterSurfaceView{857b708 V.E...... ......I. 0,0-0,0} viewRate 0 width 0 height 0
15:09:47.769 22799-22799 V/FlutterView: Updating window insets (onApplyWindowInsets()):
    Status bar insets: Top: 137, Left: 0, Right: 0
    Keyboard insets: Bottom: 0, Left: 0, Right: 0System Gesture Insets - Left: 0, Top: 137, Right: 0, Bottom: 0
15:09:47.777 22799-22799 V/FlutterView: Updating window insets (onApplyWindowInsets()):
    Status bar insets: Top: 137, Left: 0, Right: 0
    Keyboard insets: Bottom: 0, Left: 0, Right: 0System Gesture Insets - Left: 0, Top: 137, Right: 0, Bottom: 0
15:09:47.778 22799-22799 V/FlutterView: Size changed. Sending Flutter new viewport metrics. FlutterView was 0 x 0, it is now 1440 x 2910
15:09:47.778 22799-22799 V/FlutterRenderer: Setting viewport metrics
    Size: 1440 x 2910
    Padding - L: 0, T: 137, R: 0, B: 0
    Insets - L: 0, T: 0, R: 0, B: 0
    System Gesture Insets - L: 0, T: 137, R: 0, B: 0
    Display Features: 0
15:09:47.784 22799-22799 V/FlutterSurfaceView: SurfaceHolder.Callback.startRenderingToSurface()
15:09:47.785 22799-22799 V/FlutterSurfaceView: SurfaceHolder.Callback.surfaceChanged()
15:09:47.785 22799-22799 V/FlutterSurfaceView: Notifying FlutterRenderer that Android surface size has changed to 1440 x 2910
15:09:47.786 22799-22799 D/OpScreenModeManager: setRefreshRate parent io.flutter.embedding.android.FlutterView{f4d8ea1 VFE...... ......ID 0,0-1440,2910 #1} parent width 1440 parent height 2910 mRatio 1.2
15:09:47.786 22799-22799 D/OpScreenModeManager: setRefreshRate view io.flutter.embedding.android.FlutterSurfaceView{857b708 V.E...... ......ID 0,0-1440,2910} viewRate 1 width 1440 height 2910
15:09:47.786 22799-22799 D/OpScreenModeManager: setRefreshRate token android.os.BinderProxy@b76de16 rate 1 mCurrentRate 0 tmpRate:1
15:09:47.787 22799-22799 D/OpScreenModeManager: updateScenario fullScreen 1
15:09:47.790 22799-22799 V/FlutterRenderer: Setting viewport metrics
    Size: 1440 x 2910
    Padding - L: 0, T: 137, R: 0, B: 0
    Insets - L: 0, T: 0, R: 0, B: 0
    System Gesture Insets - L: 0, T: 137, R: 0, B: 0
    Display Features: 0
15:09:47.836 22799-1105 V/DartMessenger: Received message from Dart over channel 'flutter/isolate'
15:09:47.837 22799-1105 I/flutter: Nayuta main invoker wait for multiple-flutters response
15:09:47.837 22799-1105 V/DartMessenger: Received message from Dart over channel 'multiple-flutters'
15:09:47.837 22799-22799 V/DartMessenger: Received message reply from Dart.
15:09:47.845 22799-22799 V/DartMessenger: Deferring to registered handler to process message.
15:09:47.845 22799-22799 V/DartMessenger: No registered handler for message. Responding to Dart with empty reply message.
15:09:47.845 22799-22799 I/Nayuta:  multiple-flutters channel register 
15:09:47.846 22799-22799 V/DartMessenger: Sending message with callback over channel 'multiple-flutters'
15:09:47.846 22799-1105 E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: MissingPluginException(No implementation found for method test on channel multiple-flutters)
    #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:165:7)
    <asynchronous suspension>
    #1      main (package:multiple_flutters/main.dart:27:3)
    <asynchronous suspension>
15:09:47.846 22799-22799 V/DartMessenger: Setting handler for channel 'multiple-flutters'
```

flutter doctor：
```
➜  multiple_flutters git:(channel) flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.4 21F79 darwin-x64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2022.1)
[✓] VS Code (version 1.69.1)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!

```

</details>

**Comment by gaaclarke** [comment]
This appears to be working as intended.  Creating channels outside of the event that executes `createAndRunEngine` will create a race condition.  The solution is to make the channel in the same event.
```kt
EngineBindings.kt:
    init {
        val app = activity.applicationContext as App
        // This has to be lazy to avoid creation before the FlutterEngineGroup.
        val dartEntrypoint =
            DartExecutor.DartEntrypoint(
                FlutterInjector.instance().flutterLoader().findAppBundlePath(), entrypoint
            )
        engine = app.engines.createAndRunEngine(activity, dartEntrypoint, initialRoute);
        this.delegate = delegate
        channel = MethodChannel(engine.dartExecutor.binaryMessenger, "multiple-flutters")
        Handler(Looper.getMainLooper()).postDelayed({
            Log.i("Nayuta", " multiple-flutters channel register ")
            attach()
        }, 100)

    }
```

This works because all messages are forwarded to the platform thread's event loop until initialization is finished, so a message can't be received until the event calling `createAndRunEngine` is completed. (cc @jiahaog who was asking about this the other day).

**Comment by Nayuta403** [comment]
Thank you for reply @gaaclarke 
Yeah, the question is expected, but I don't think it makes sense. Since in FlutterActivity the plugin is registered in `onCreate`, the Dart code runs in `onStart`. Make sure the plugin is ready before run the dart code again, otherwise this race state may occur.

But for FlutterEngineGroup, it now seems to be mixed together, and dart is executed before the plugin is registered.The above problem may occur if the plugin is slow to register.

After discussed with @ColdPaleLight  offline. I'm thinking of two ways to solve this. 

1.  for spawn engine `flutterJNI.spawn` do not directly `runEngine`
2. or spawn engine, move `flutterJNI.spawn` after plugin registration

What do you think

**Comment by Nayuta403** [comment]
In particular, in our scenario, there is custom logic for plugin registration. So we don't register the plugin in the constructor of FlutterEngine, which makes this problem much easier. The problem is better reproduced after this https://github.com/flutter/engine/pull/34663 is merged,

**Comment by Nayuta403** [comment]
> This appears to be working as intended. Creating channels outside of the event that executes `createAndRunEngine` will create a race condition. The solution is to make the channel in the same event.
> 
> ```kotlin
> EngineBindings.kt:
>     init {
>         val app = activity.applicationContext as App
>         // This has to be lazy to avoid creation before the FlutterEngineGroup.
>         val dartEntrypoint =
>             DartExecutor.DartEntrypoint(
>                 FlutterInjector.instance().flutterLoader().findAppBundlePath(), entrypoint
>             )
>         engine = app.engines.createAndRunEngine(activity, dartEntrypoint, initialRoute);
>         this.delegate = delegate
>         channel = MethodChannel(engine.dartExecutor.binaryMessenger, "multiple-flutters")
>         Handler(Looper.getMainLooper()).postDelayed({
>             Log.i("Nayuta", " multiple-flutters channel register ")
>             attach()
>         }, 100)
> 
>     }
> ```
> 
> This works because all messages are forwarded to the platform thread's event loop until initialization is finished, so a message can't be received until the event calling `createAndRunEngine` is completed. (cc @jiahaog who was asking about this the other day).

Thanks for replying. As you said, the initialization is in the same eventLoop of the Platform thread. This should not be an issue if it is in the same event. I think I haven't found the root cause of this problem, so I will close this Issue first.
