### ISSUE TITLE
Is there any easy way to simulate the detach logic of the Flutter Plugin in test?

### ISSUE THREAD

**Issue by littleGnAl** [flutter/flutter#108293]
## Use case
I have run into this [issue](https://github.com/flutter/plugins/pull/2759) without cleanup the listeners when the engine is dead, so it causes the crash. As I single FlutterEngine APP, the `detachFromEngineForRegistrar ` is only called when the APP is exited. It's not easy to test this case in the integration test, although I can simulate the detached logic of the Flutter Plugin through the [Add2App](https://docs.flutter.dev/development/add-to-app/ios/project-setup) scenario, there's a lot of work to achieve this, and the Add2App feature is not support the desktop, and web yet.

So, is there any easy way to simulate the Plugin detach logic?

**Comment by maheshmnj** [comment]
Hi @littleGnAl, Thanks for filing the issue. I am labeling this issue for further insights from the team.

cc: @cbracken

**Comment by chinmaygarde** [comment]
> So, is there any easy way to simulate the Plugin detach logic?

Can you redirect questions to the Discord or StackOverflow channels please? Closing this as it isn't clear if there is an bug here.
