### ISSUE TITLE
[go_router]  go_router 4.2.1 breaks go_router_builder

### ISSUE THREAD

**Issue by cenumi** [flutter/flutter#108274]
From go_router_builder v1.0.7 https://github.com/flutter/packages/blob/main/packages/go_router_builder/lib/src/go_router_generator.dart

```dart
  @override
  TypeChecker get typeChecker => const TypeChecker.fromUrl(
        'package:go_router/src/route_data.dart#TypedGoRoute',
      );
```
In latest go_router v4.2.1
https://github.com/flutter/packages/tree/main/packages/go_router/lib/src

https://github.com/flutter/packages/pull/2317

TypedGoRoute was refactored to typed_routing.dart

No related .g.dart file will be generated, and no error message is reported.

**Comment by exaby73** [comment]
Hello @cenumi. Can you provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)?

**Comment by cenumi** [comment]
#108278 same sample here
Already pointed out the code caused this, go_router_builder uses `TypeChecker.fromUrl`, but the linked file is gone with https://github.com/flutter/packages/pull/2317, its name changed from [route_data.dart](https://github.com/flutter/packages/blob/199d8c9cd291406e54e51d49cd18c58ecb6c8dad/packages/go_router/lib/src/route_data.dart) to [typed_routing.dart](https://github.com/flutter/packages/blob/main/packages/go_router/lib/src/typed_routing.dart) which contains TypedGoRoute class that checker can't find

**Comment by cenumi** [comment]
example
4.2.1 https://github.com/cenumi/go_router_builder_failing_example/tree/master
4.2.0 https://github.com/cenumi/go_router_builder_failing_example/tree/4.2.0

**Comment by cenumi** [comment]
> @cenumi Since this has already been raised, I am marking this as a duplicate. You can share your findings on the original issue. If you disagree, please comment and we can re-open it. Thank you

Actually, this is the origin one, check the time...
and now they are all closed!!

**Comment by Skogsfrae** [comment]
> @cenumi Since this has already been raised, I am marking this as a duplicate. You can share your findings on the original issue. If you disagree, please comment and we can re-open it. Thank you

We opened our issues with a 15minutes difference, which may have caused some confusion about what's the original one.

I'll be happy to share my report here as well, but we need to know which issue will be used to track the problem.

**Comment by exaby73** [comment]
Ohh sorry about that. Let's keep this one for tracking this issue

**Comment by stuartmorgan** [comment]
/cc @johnpryan who made this change.

@johnpryan Do you want to withdraw 4.2.1 while addressing this? We still have a window of a couple of days to do so.

**Comment by stuartmorgan** [comment]
It looks like this is blocking the flutter->packages roller, so I've retracted 4.2.1 for now as a temporary solution.

**Comment by johnpryan** [comment]
Oops, I thought CI would catch this...
