### ISSUE TITLE
Flutter engine cannot locate ICU data file correctly in IosUnitTests

### ISSUE THREAD

**Issue by Yeatse** [flutter/flutter#108221]
In https://github.com/flutter/engine/pull/34508 I added a new test case for iOS which depends on the ICU library, but the test kept failing because it could not locate `icudtl.dat` file correctly, until I specified its location by hardcoding it in the command line argument. We should get rid of this hardcoding.

cc @jmagman

**Comment by dnfield** [comment]
Copying my comment here: I think this is fine. For other test harness we do the same thing. This does not end up impacting user facing apps.
