### ISSUE TITLE
Would like to cache HTTP responses on disk

### ISSUE THREAD

**Issue by passsy** [flutter/flutter#10820]
I couldn't find a simple way to cache http responses depending on `Cache-Control` headers. the [`http`](https://github.com/dart-lang/http) package doesn't support it and I haven't found other packages providing a cache implementation. Most likely because browsers automatically cache requests and there was no demand from web front end developers.

The only cache implementation in the flutter sdk is `ImageCache`. But it's only a in memory cache not a persistent disk cache.

There should be a [`DiskLruCache`](https://github.com/square/okhttp/blob/master/okhttp/src/main/java/okhttp3/internal/cache/DiskLruCache.java) implementation like in OkHttp.

It's pretty common on Android to simply rely on the http cache to build offline apps.

**Comment by sethladd** [comment]
Thanks for the feedback!

Does this have to be part of the core Flutter framework? I wonder if a package would suffice. Flutter can write files and directories (see https://flutter.io/reading-writing-files/)

Does the http package provide necessary hooks, or would someone need to write a full wrapper around http package?

**Comment by eseidelGoogle** [comment]
@donny-dont might know.

**Comment by donny-dont** [comment]
@sethladd @eseidel `http` is moving to a middleware based implementation in the same vein as `shelf`. If you wanted something like this you would end up writing a middleware that would make decisions based on the caching headers. Once the middleware bits are fully integrated into `http` then we can talk more about how one would do that.

**Comment by sethladd** [comment]
@donny-dont can you please link to an issue/PR that describes the new http middlewear?

In the meantime, we'll close this and defer to the http package to provide at least the hooks to make it possible for someone to write an additional package/extension for the http package.

We like the suggestion, we just think it doesn't need to happen in the core Flutter framework. Thanks for the feedback!

**Comment by donny-dont** [comment]
Sure @sethladd 

I would say https://github.com/dart-lang/http/issues/60 is the tracking bug. For middleware specifically there is https://github.com/dart-lang/http/pull/85. After that lands there will be a PR for `Pipeline` and `Cascade` which should look like their counterparts in `shelf`. Then its adding some tests and figuring out what to do with MIME types. Extension methods would be nice for that.

**Comment by eseidelGoogle** [comment]
@jonahwilliams also worked on caching for Flutter specifically.

I ran across this old bug today and unclear from the above how/if this actually got resolved in a way which developers can use.

**Comment by giaur500** [comment]
Please clarify, anybody? Is caching available currently or not? It seems not? Planned or not?

**Comment by MahdiPishguy** [comment]
+1
