### ISSUE TITLE
[Proposal]SliverPersistantHeader should support Sticky Headers

### ISSUE THREAD

**Issue by Areopagitics** [flutter/flutter#108289]
## Use case

Many other frameworks come with this feature out of the box. There are 5 packages that provide sticky headers, none of which work properly in a CustomScrollView with a center key on a Sliver (sticky_headers doesn't even work with CustomScrollView). Each tries to make up for the failings of the other.

https://pub.dev/packages/flutter_sticky_header
https://pub.dev/packages/sticky_headers
https://pub.dev/packages/sticky_and_expandable_list
https://pub.dev/packages/sticky_infinite_list
https://pub.dev/packages/sticky_and_expandable_list

## Proposal

SliverPersistantHeader really should have a property (sticky) that allows for sticky headers. 

![sticky_header_all](https://user-images.githubusercontent.com/24683841/180788743-349fd13f-5785-48eb-a618-03c9e08f4ef9.gif)

**Comment by maheshmnj** [comment]
Hi @Areopagitics, `SliverPersistentHeader` does have a pinned property https://api.flutter.dev/flutter/widgets/SliverPersistentHeader/pinned.html to stick the header to the start of the viewport, I believe this will help you achieve your use case?

**Comment by Areopagitics** [comment]
Unfortunately it does not have the same effect. It's a real misnomer in my opinion.

**Comment by maheshmnj** [comment]
Thanks for the update @Areopagitics 

There is a similar issue describing this case https://github.com/flutter/flutter/issues/51107, Please follow up there for further updates, Closing this issue as a duplicate. In case you have more info feel free to comment on that issue.


Thank you.

**Comment by Areopagitics** [comment]
@maheshmnj I really don't think it's a duplicate since `ListView` is not the same as `CustomScrollView`. I can also almost get the desired effect if I use `SliverPersistantHeader` pinned and floating, but the only problem is the first (or previous) `SliverPersistantHeader` will always be on top of the new one, whereas the new one should always go over the old one (higher one).

**Comment by Piinks** [comment]
I am going to reopen this, since it is not the same issue.

**Comment by Areopagitics** [comment]
much appreciated...looking forward to seeing this feature

**Comment by luanbatistadev** [comment]
same problems here with multiples slivers persistentheaders floatings

**Comment by Piinks** [comment]
I think @thkim1011's work on https://github.com/flutter/flutter/issues/33137 will make this possible by putting a pinned sliver persistent header in a SliverGroup (which is the feature they are working on).

**Comment by luanbatistadev** [comment]
will this solve the problem of overlapping multiples sliverpersistentheader floating?

**Comment by Piinks** [comment]
> will this solve the problem of overlapping multiples sliverpersistentheader floating?

I am not familiar with that issue @luanbatistadev. If an issue does not already exist, please file one.

**Comment by Piinks** [comment]
This has been resolved by https://github.com/flutter/flutter/pull/126596. Composing a SliverMainAxisGroup containing a pinned SliverPersistentHeader will now provide this sticky effect! cc @thkim1011
