### ISSUE TITLE
Flutter web requests an image every screen redraw when caching is disabled in the browser

### ISSUE THREAD

**Issue by app111** [flutter/flutter#108271]
[main.dart.zip](https://github.com/flutter/flutter/files/9187186/main.dart.zip)
![xxxx](https://user-images.githubusercontent.com/1449284/180942014-1e5c74c3-5271-4618-9820-6838cac14806.jpg)

➜  ffw_demo 2 flutter doctor -v                                                                   
[✓] Flutter (Channel mt-stable-web-2.10, 2.10.102-0.0.pre.46, on macOS 12.5 21G72 darwin-x64, locale zh-Hans-CN)
    • Flutter version 2.10.102-0.0.pre.46 at /Users/xxxx/.flutter_sdk
    • Framework revision 73a50d8331
    • Engine revision e94dbc36da
    • Dart version 2.16.1
    • DevTools version 2.9.2
    • Pub download mirror https://pub.com
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/xxx/Library/Android/sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_333-b02)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] VS Code (version 1.69.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.44.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 103.0.5060.134

[✓] HTTP Host Availability
    • All required HTTP hosts are available

**Comment by exaby73** [comment]
Hi @app111, please provide a [minimal, reproducible example][1] and the output of `flutter doctor -v` as well as `flutter run -v`. Also, can you highlight what the expected behavior is?

[1]: https://stackoverflow.com/help/minimal-reproducible-example

**Comment by app111** [comment]
> Hi @app111, please provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) and the output of `flutter doctor -v` as well as `flutter run -v`. Also, can you highlight what the expected behavior is?

**Comment by exaby73** [comment]
Hello @app111. I noticed you're not using the latest Flutter stable (`Flutter version 2.10.102-0.0.pre.46`). Can you test this on the latest stable?

**Comment by app111** [comment]
I still have problems with my test. It doesn't matter the Flutter version, thank you
[flutter] flutter doctor -v
[✓] Flutter (Channel stable, 3.0.5, on macOS 11.6.8 20G728 darwin-x64, locale zh-Hans-CN)
    • Flutter version 3.0.5 at /Users/kangzh/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (13 days ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

**Comment by app111** [comment]
/// BitmapCanvas.dart
.......
html.ImageElement _reuseOrCreateImage(HtmlImage htmlImage) {
    final String cacheKey = htmlImage.imgElement.src!;
    if (_elementCache != null) {
      final html.ImageElement? imageElement =
          _elementCache!.reuse(cacheKey) as html.ImageElement?;
      if (imageElement != null) {
        return imageElement;
      }
    }
    // Can't reuse, create new instance.
    final html.ImageElement newImageElement = htmlImage.cloneImageElement();
    if (_elementCache != null) {
      _elementCache!.cache(cacheKey, newImageElement, _onEvictElement);
    }
    return newImageElement;
  }

**Comment by maheshmnj** [comment]
Hi @app111, Can you please share a minimal and complete code sample that we can directly run with minimal or no code changes?

**Comment by app111** [comment]
[fff_demo.zip](https://github.com/flutter/flutter/files/9200943/fff_demo.zip)

**Comment by maheshmnj** [comment]
@app111 Perhaps this is working as intended when we disable the cache, The image is destroyed when out of the viewport and created when it comes into view?

<img width="1419" alt="image" src="https://user-images.githubusercontent.com/31410839/181449251-57230f5d-270d-4014-a096-671976a2a549.png">

**Comment by app111** [comment]
viewport->cacheExtent

**Comment by huycozy** [comment]
Hi @app111 
>viewport->cacheExtent

Please provide **reproduction steps**, **expected results** and **actual results** so that we can address this issue properly.
Also, please try using latest Flutter SDK (stable and master) and retry to see if this issue still reproduces.
