### ISSUE TITLE
Ability to use DatePicker without having to use material icons

### ISSUE THREAD

**Issue by alardizabal** [flutter/flutter#10827]
We are currently not using material icons and I'd like to be able to use the DatePicker without relying on the material icons. The only material icons on the picker are the back and forward icons (screenshot below). The ability to provide our own icons would be preferable.

![screenshot_20170619-121754](https://user-images.githubusercontent.com/3614291/27295541-49a0cdce-54eb-11e7-9b91-d34d0df2ae38.png)

**Comment by eseidelGoogle** [comment]
@xster this sounds like something you were working on?

**Comment by xster** [comment]
The material library generally assumes it can use material icons. The ask seems to be more about creating a general shimming mechanism to inject any icons internally referred to by the material library via Icons and still use the material library?

Are those new assets you want to use font icons or image assets?

**Comment by eseidelGoogle** [comment]
Curious: How much binary size does `use_material_design: true` add?

**Comment by alardizabal** [comment]
I've had a chat with the team and we're just going to turn material back on. It would be nice in the future to not have to depend on the material library to use some basic widgets like the date picker. For now we're fine with closing the issue.

**Comment by lukef** [comment]
@xster - we might want to have a warning or just remove the `uses-material-design` flag in pubspec if it is required. At the moment we have `uses-material-design: false`, but if it doesn't take up extra space in the app and its impossible to decouple material from flutter then it might just be redundant?

**Comment by collinjackson** [comment]
it's not clear that there's an action we can take here and @lukef said this can be closed. closing

**Comment by xster** [comment]
For a better understanding of your main motivations and to maybe derive some long term tasks on our end, were your first principles with this mainly to:

1- Not use material library and widgets at all? Somewhat hinted at it in https://github.com/flutter/flutter/issues/10827#issuecomment-309827835 but I wasn't quite sure
2- Not incur any app size costs associated with using material in the form of icon fonts
3- Use the material library but be able to customize some of the icons material is currently internally referring to or
4- Just make the pubspec's material asset reference clearer

It's definitely possible to decouple material from flutter. It's just not yet easy to decouple the icons material is using from material's included widgets. We just wanted to be sure if that was something you guys wanted. 

Feel free to ignore too if already addressed with Collin in person :)

**Comment by lukef** [comment]
So, the `uses-material-design` option is actually a little confusing. We were under the impression that it meant that it wouldn't load the icon font (essentially) and we were using it with the intention to save space because we weren't using the `Icon` class at all. We still wanted to use the other classes though. So, option number 2.

In hindsight, it makes perfect sense that other things in the material package depend on that font/flag being set to `true` and that setting the flag to false wont actually *stop* you from using material, but just disable the specifics of the platform if you *choose* not to use it.

I think that if there is/was documentation to that extent then it is fine :) Its totally acceptable that it is an all or nothing deal. I think we just were working of an incorrect assumption.

Hopefully this make sense.

**Comment by Hixie** [comment]
Where would you look for this documentation?

**Comment by lukef** [comment]
I would think probably a Getting Started guide. Either here: https://flutter.io/setup or something like https://firebase.google.com/docs/android/setup. Ideally that would explain that if you want to use the material package then you should set that value to `true`. If you don't want to use it, set it to `false`. I think we read too much into that flag ultimately. 

If that flag is meant to represent "use material, but not the icon font" then the package should work *without* the font in my opinion. If it is a flag that specifies the intent to *never* use material, then it works :)

**Comment by Hixie** [comment]
Cool, thanks. Filed https://github.com/flutter/flutter/issues/10878.
