### ISSUE TITLE
Prefix icon doesn't align properly with Input hint or text

### ISSUE THREAD

**Issue by AmitSonkhiya** [flutter/flutter#108243]
The `prefixIcon` property doesn't align the widget with the `hintText` or the input entered whereas `prefix` does.
It needs rectification since the `prefix` widget is shown only when the `TextField` has the focus.

## Steps to Reproduce

1. Execute the attached code on DartPad
2. You will see the country flag/code misaligned to `hintText`.
3. Change `prefixIcon` property name to `prefix`.
4. Run the code again and the flag/code will get aligned to `hintText` or any input when you would click the input.

**Expected results:** `prefixIcon` widget aligned with `hintText`.

**Actual results:** `prefixIcon` widget pushed a bit downward (or upward in other implementations) as compared to `hintText`.

![flutter](https://user-images.githubusercontent.com/32666864/180639576-eb5d9f78-c25e-401f-90ea-e2cd0c5853ac.png)

**Proposal Solution:** Either the `prefixIcon` position should be fixed or a property `alwaysShowPrefix` (false by default) could be added to `InputDecoration` and the `prefix` widget should be shown always when the property is set to true.

**Additional:** Similar issue [https://github.com/flutter/flutter/issues/91174](https://github.com/flutter/flutter/issues/91174)
The `icon` property displays the same behavior as `prefixIcon`.

<details>
<summary>Code sample</summary>

```
import 'package:flutter/material.dart';

const Color darkBlue = Color.fromARGB(255, 18, 32, 47);

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: darkBlue,
      ),
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: Center(
          child: Padding(
            padding: const EdgeInsets.all(8),
            child: TextFormField(
              decoration: InputDecoration(
                hintText: 'Your Phone number',
                prefixIcon: TextButton.icon(
                        onPressed: () {},
                        icon: ConstrainedBox(
                          constraints: const BoxConstraints(
                            maxWidth: 24.0,
                            maxHeight: 24.0,
                          ),
                          child: Image.Network('https://raw.githubusercontent.com/hampusborgos/country-flags/main/png100px/in.png'), // Flag network image
                        ),
                        label: const Text('+91'),
                      ),
              )
            ),
          ),
        ),
      ),
    );
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by AmitSonkhiya** [comment]
Closing as setting `textAlignVertical: TextAlignVertical.center` for the `TextField` fixes the concern.

**Comment by AmitSonkhiya** [comment]
I'm reopening the issue since setting `textAlignVertical: TextAlignVertical.center` seems to resolve the issue on DartPad only.
In a real device, `prefixIcon` and `hintText`/input are not perfectly aligned like `prefix` property does.

**Comment by huycozy** [comment]
Hi @AmitSonkhiya, as you mentioned above, I see #91174 addressing the case you described.

https://github.com/flutter/flutter/issues/91174#issue-1014212306
> Currently the prefix property of InputDecoration correctly aligns the prefix with the text while the prefixIcon property does not.

Closing as a duplication, so please follow up on it for further updates.
