### ISSUE TITLE
[tool][Proposal] Allow `split-per-abi` to use the same version codes for generated apks

### ISSUE THREAD

**Issue by git-xiaocao** [flutter/flutter#108220]
flutter build apk --split-per-abi will compile apk with different version code
[https://developer.android.com/studio/build/configure-apk-splits#configure-APK-versions](https://developer.android.com/studio/build/configure-apk-splits#configure-APK-versions)
I need the version code to be the same

**Comment by danagbemava-nc** [comment]
Hi @git-xiaocao, what is your case for this? According to the playstore guidelines, each apk uploaded needs to have a unique version code.
