### ISSUE TITLE
I can't make a bottom navigation bar

### ISSUE THREAD

**Issue by Mustafabsahi** [flutter/flutter#108217]
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by superciccio** [comment]
have you seen this ?
https://api.flutter.dev/flutter/material/BottomNavigationBar-class.html

**Comment by darshankawar** [comment]
Looking at issue title, it is better suited to be asked on support channels like StackOverflow.
Also, when you open an issue, please try to use new issue template and fill out requested details to properly address it.
Take a look at above link and see if it helps.
Closing for now.
