### ISSUE TITLE
Flutter http vs https loading delays

### ISSUE THREAD

**Issue by soloposmenu** [flutter/flutter#108206]
Hello,

I have a web app that on http runs very fast (less than a second), the same web app running on https takes between 7-12 seconds.

You can check the code here: https://gist.github.com/soloposmenu/780304f16267a2297c816a16eed86918

Same app on Android device or emulator runs at 1-2 seconds
To better see the difference, please see the attached video.
It happens in any browser.

You can view it live here:
http://soloposmenu.com/hardware/
and
https://soloposmenu.com/hardware

https://user-images.githubusercontent.com/83898133/180585364-90ca96e7-f916-4f91-8e4f-e1b6f8171c52.mp4

/

**Comment by exaby73** [comment]
Hello @soloposmenu. The sample code you provided doesn't include the following imports:

```dart
import 'package:json_listview/model/user.dart';
import 'package:json_listview/page/user_page.dart';
```

Can you please edit it to remove these dependencies so that I can test it? You can follow guidelines for creating a [minimal, reproducible example here](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by soloposmenu** [comment]
Here you go. user_page.dart has been removed for this sample.
See main.dart and user.dart in:
https://gist.github.com/soloposmenu/d8ebb6cd115a5b4aac13375af529813c

Also, the links to the web page have been updated with the new code.

**Comment by exaby73** [comment]
Could you also try uploading a build with master channel?

**Comment by soloposmenu** [comment]
Let me give a try. Will let you know in a bit

**Comment by soloposmenu** [comment]
> Could you also try uploading a build with master channel?

Excelent suggestion. https is now almost as fast as http was on the stable channel. 
Also regular http runs well, but not as fast as it was on the stable channel (my perception only, I don't have the data to back that up)

The flutter development team continues making improvements on this solution.
Thanks for you support exaby73.

**Comment by maheshmnj** [comment]
Thanks for the update @soloposmenu, provided that it works fine on the latest master channel, I am going to close this issue. The fix will land on the stable channel in future releases.
