### ISSUE TITLE
Need an Expansion Tile Builder 

### ISSUE THREAD

**Issue by abinvs-2019** [flutter/flutter#108283]
## Use case

I want to build a dynamic size expansion tile like listViewBuilder. But couldn't find one.

**Comment by maheshmnj** [comment]
Hi @abinvs-2019, I believe you can already achieve that with the existing APIs, Can you share a code sample that doesn't work? This will also help me understand your use case.

Thanks

**Comment by abinvs-2019** [comment]
Yes, I have achieve it. But the issue was there is a need of Expansion tile builder.

**Comment by maheshmnj** [comment]
@abinvs-2019 I do understand that you are proposing to add ExpansionTile builder, But What I don't understand is, if it can be achieved with the existing APIs then why would we need this?

**Comment by abinvs-2019** [comment]
@maheshmnj yes, I think this is effecting the perfomance. Any ways I think this is not needed. Closing the issue.
