### ISSUE TITLE
Re-evaluation of assertions removal for const widgets

### ISSUE THREAD

**Issue by albertodev01** [flutter/flutter#108248]
## Use case

Right now, for backwards compatibility with non-nullsafe code, there still are some assertions that make some code impossible to be marked as `const`. For example:

```dart
Row(
  children: const [
    Text('Hello'),
    Text('World'),
  ]
),
```

This is valid but only the `children` list is constant, not the whole widget. In other words, we can't do this:

```dart
const Row(
  children: [
    Text('Hello'),
    Text('World'),
  ]
),
```

There already was an issue (https://github.com/flutter/flutter/pull/88359) to address this but it was closed due to this reason:

> Is the reasoning here that we can remove the check because in an NNBD world List<Widget> children can never contain null? We've left these kind of null checks in the code base for now because not all apps have migrated to NNBD yet and they still need these asserts for proper error reporting.

That was a valid point but almost one year has passed since then and I think the team could re-evaluate investigating if it's worth removing those assertions. They would make `Row`, `Column`, `Stack` and much more `const`-able.

A `Container` for example could also be `const` if some assertions were removed on its constructors.

## Proposal

Remove the `assert` statement [here](https://github.com/spkersten/flutter/blob/master/packages/flutter/lib/src/widgets/framework.dart#L1803-L1816) for `MultiChildRenderObjectWidget`, which would make lots of widgets `const`.

**Comment by iapicca** [comment]
the ubiquitous presence of like **_unnecessary_** assertion like `: assert(children != null);` ([e.g.](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/list_wheel_scroll_view.dart#L84)) really baffles me.

It's clearly a **technical debt** and it does, albeit in limited fashion,
have consequences in terms of performance @albertodev01 just provided an example of it

**Comment by albertodev01** [comment]
The Dart team is also planning to remove support to non-null-safe code:

 - https://github.com/dart-lang/sdk/issues/49529
 - https://github.com/dart-lang/sdk/issues/49530

**Comment by goderbauer** [comment]
We plan to remove these asserts from the framework when dart discontinues non-null safety.

**Comment by albertodev01** [comment]
There is an interesting update: https://github.com/dart-lang/sdk/issues/49530

Looks like we should be able to remove those assertions somewhere around mid-2023 when Dart 3 will be out

**Comment by albertodev01** [comment]
Update: with the upcoming Dart 3 version, it may be a good time now to make this change.

@goderbauer will you create something under "Projects"? or just an umbrella issue (or anything else) to track this?

**Comment by gustav3d** [comment]
Dear god, finally :)

**Comment by goderbauer** [comment]
> It seems that this issue might be addressed here: https://github.com/flutter/flutter/issues/118837

Yeah, I am working on this as part of that issue.

**Comment by albertodev01** [comment]
We can close this as it's finally done 🎉
