### ISSUE TITLE
About the jump page of flutter3.0.5, there will be a problem of jamming.

### ISSUE THREAD

**Issue by bingxio** [flutter/flutter#108246]
Using the basic `MaterialPageRoute` will cause a jam problem, because the jump animation of the page is not smooth and black edges appear. This is something that didn't appear in the previous version.
```dart
ElevatedButton(
  onPressed: () => Navigator.push(
    context,
    MaterialPageRoute(builder: (_) {   
      return TestPage();
    },
  ),
  child: const Text("PRESS ME!"),
)
```
This problem will not appear on the iPhone virtual machine. **It appears when I use Android physical machine.**

However, I will return the version to 2.10.5 and test it here, and the problem does not appear.

```
[✓] Flutter (Channel stable, 2.10.5, on macOS 11.6.2 20G314 darwin-x64, locale
    zh-Hans-CN)
    • Flutter version 2.10.5 at /Users/bingxio/Downloads/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (3 months ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version
    32.1.0-rc1)
    • Android SDK at /Users/bingxio/Library/Android/sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✗] Chrome - develop for the web (Cannot find Chrome executable at
    /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code (version 1.69.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.44.0

[!] Proxy Configuration
    • HTTP_PROXY is set
    ! NO_PROXY is not set

[✓] Connected device (1 available)
    • Redmi Note 5 (mobile) • f31b6a38 • android-arm64 • Android 12 (API 32)

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.
```

**Comment by bingxio** [comment]
https://user-images.githubusercontent.com/31379103/180644079-31d708c2-d12d-4e5d-ab8b-22b5472d531e.mov

This is the version compiled with 2.10.5, which is very smooth.

**Comment by bingxio** [comment]
https://user-images.githubusercontent.com/31379103/180645427-465ec9d8-b9ea-4263-b618-96928019d106.mp4

**Comment by jonahwilliams** [comment]
While it was only merged two days ago, if you're feeling adventurous you could try `https://github.com/flutter/flutter/pull/106621` to see if it improves the performance for you. This is only available on flutter master/main.

Otherwise, you could opt back into the old transition using either `OpenUpwardsPageTransitionsBuilder ` or `FadeUpwardsPageTransitionsBuilder ` in your theme

**Comment by bingxio** [comment]
> While it was only merged two days ago, if you're feeling adventurous you could try #106621 to see if it improves the performance for you. This is only available on flutter master/main.
> 
> Otherwise, you could opt back into the old transition using either `OpenUpwardsPageTransitionsBuilder ` or `FadeUpwardsPageTransitionsBuilder ` in your theme

yes. I switched to the master channel, which solved my problem.
```dart
  bool preferRasterization = true;
```

**Comment by goderbauer** [comment]
Closing as per previous comment.
