### ISSUE TITLE
[SelectionArea] add the ability to get the currently selected text

### ISSUE THREAD

**Issue by CaptainDario** [flutter/flutter#108231]
I am currently using the new `SelectionArea`-widget and it is working great! However, it would be nice to be able to get the currently selected text which currently does not seem to be possible.
For example one could show a popup with word translations on selection.

**Comment by huycozy** [comment]
Hi @CaptainDario
From my understanding, are you suggesting a feature of SelectionArea that allows getting selected text value in SelectionArea, right?
Do you recommend any specific mechanism? For example `onSelectionChange`, `onSelectionFinished`, etc.

**Comment by CaptainDario** [comment]
@huycozy Yes, that is exactly what I meant.
To my mind a callback like, `onSelectionChange(String selection)` which passes the selected portion of the text would be perfect. There is not something like that implemented, right?

**Comment by huycozy** [comment]
@CaptainDario yes, as far as I can see, these callbacks haven't been implemented yet.
https://github.com/flutter/flutter/blob/15aa3bfda3658d1094ae50cc4c608fc94642405a/packages/flutter/lib/src/material/selection_area.dart#L33-L38
Labeling this issue as a new feature request. Thanks!

**Comment by CaptainDario** [comment]
@huycozy how likely is that something like that is going to be implemented sometime soon?

**Comment by huycozy** [comment]
> @huycozy how likely is that something like that is going to be implemented sometime soon?

@CaptainDario This is not known in advance. Please follow this issue for further updates.

**Comment by justinmc** [comment]
@chunhtai How do you get the current selection from SelectionArea?  I'm pretty sure I remember there being a way when you wrote global selection...

**Comment by chinmoy12c** [comment]
Hey, @justinmc @chunhtai I dropped a PR, please take a look :).

**Comment by kaboc** [comment]
The `onSelectionChanged` callback of `SelectionArea` is only given plain text, so it is not equivalent to SelectableText's `onSelectionChanged`, which receives detailed information regarding text selection. If `SelectionArea` replaces `SelectableText`, I think it should provide the same functionality at least.

e.g. An app that has the feature to highlight a selected piece of text.

When a user selects "pick" in "Peter Piper picked a peck of pickled peppers", there is no way to tell which one of the two "pick"s in the sentence should be highlighted, without necessary info on the selection, like selection offsets.

**Comment by chunhtai** [comment]
@kaboc I have not figured out a way to describe the selection across multiple text widgets.

**Comment by kaboc** [comment]
@chunhtai 
Shall I file it as a separate issue? But if it is improved not now but in the future, it will be a breaking change.

**Comment by chunhtai** [comment]
@kaboc yes can you create a separate issue. I think if we were to do that, we need to expose a lot other API too. It will be a big feature update anyway.

**Comment by kaboc** [comment]
@chunhtai 
Sounds like a lot of work to do... OK, I'll file a new issue anyway. Thanks.
