### ISSUE TITLE
Flutterweb:     Error during WebSocket handshake: Unexpected response code: 200 (when i proxy hostname and port)

### ISSUE THREAD

**Issue by LeeCareFree** [flutter/flutter#108359]
![image](https://user-images.githubusercontent.com/51224246/180981457-ca3b315d-a444-47ae-a3c2-52a2900999e8.png)

**Comment by exaby73** [comment]
Hi @LeeCareFree, please provide a [minimal, reproducible example][1] and the output of `flutter doctor -v` as well as `flutter run -v`.

[1]: https://stackoverflow.com/help/minimal-reproducible-example
