### ISSUE TITLE
[go_router] go router does not work

### ISSUE THREAD

**Issue by devnoaman** [flutter/flutter#108377]
## Steps to Reproduce
i had used go router and after that added geolocator inside pub but get this error: 
`Because health_app depends on go_router ^4.2.1 which doesn't match any versions, version solving failed.`

**Comment by stuartmorgan** [comment]
4.2.2 has been published, so this will now work.

The error was because 4.2.1 was retracted, so was no longer available to resolve to.

**Comment by devnoaman** [comment]
thanks @stuartmorgan
