### ISSUE TITLE
Xcode warning: Run script build phase 'Run Script' will be run during every build because it does not specify any outputs

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#108321]
New warnings in Xcode 14 beta 3 on a new `flutter create` project:

> Run script build phase 'Run Script' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase.
>
> Run script build phase 'Thin Binary' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase.
<img width="448" alt="Screen Shot 2022-07-25 at 2 31 00 PM" src="https://user-images.githubusercontent.com/682784/180877587-77e79c21-4ef4-4463-af0d-8fb5e72c81eb.png">

Unchecking adds:
```diff
		9740EEB61CF901F6004384FC /* Run Script */ = {
			isa = PBXShellScriptBuildPhase;
+			alwaysOutOfDate = 1;
			buildActionMask = 2147483647;
```

Xcode isn't handling input/output, `flutter` is, so it is correct to be unchecked.

This is happening on iOS (both script build phases) and macOS (only `Runner` target, not `Flutter Assemble`, which is using inputs/outputs so the option should be checked).

Update templates and add a migration.  Note this check box exists on Xcode 13 so we don't need to increase the minimum version to 14 before doing this.

**Comment by guidezpl** [comment]
This or a very similar issue cropped up again with Flutter `3.9.0-1.0.pre.123` and `darwin-arm64`

```
warning: Run script build phase 'Run Script' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'Flutter Assemble' from project 'Runner')
```

**Comment by jmagman** [comment]
@guidezpl what Xcode version are you on?  I've seen this too on Xcode 14.3 beta 1, but the macOS script phases _are_ set up with either dependency outputs (Flutter Assemble) or with "Based on dependency analysis" unchecked (Runner).  On Xcode 14.2 I don't see this warning on the same project, makes me think it's an Xcode bug?
