### ISSUE TITLE
Computed frame damage always set to the entire screen on partial repaint

### ISSUE THREAD

**Issue by betrevisan** [flutter/flutter#108306]
The frame damage that is computed by the `DiffContext::ComputeDamage` function is always set to the entire screen (even in cases in which only part of the screen is effectively changing). This damage seems to be computed by the `Diff` call within the `FrameDamage::ComputeClipRect` function, which calculates the difference between the current tree and the previous tree. What is interesting about this issue is that it only happens for certain types of trees. For example, when the only changes between frames is a tooltip, `DiffContext::ComputeDamage` returns the correct damage region. However, when there's a loading bar or a spinner on the screen, the damage region is set to the entire screen. This makes me think that there might be a difference in the `Diff`'ing of trees with different layers but I could not yet pinpoint the problem. While debugging, I also checked if the previous tree was being set as expected and it was. It seems like the inconsistency comes from the `Diff`'ing process.

Note: this issue was seen while using the GLFW example on a Linux machine.

**Comment by jonahwilliams** [comment]
> However, when there's a loading bar or a spinner on the screen, the damage region is set to the entire screen. 

If you put a spinner on a page in just a Scaffold or Centered widget, there will be no repaint boundarys that constraint the picture - so it will expand to cover the entire screen. Diff looks at picture identity and will probably compute most of the screen as changed.

To verify this is the case, you can enable debug repaint rainbows, which will show which parts of the screen are being repainted from the framework perspective.

**Comment by betrevisan** [comment]
> To verify this is the case, you can enable debug repaint rainbows, which will show which parts of the screen are being repainted from the framework perspective.

You're right! I didn't realize this was the behavior in the case of Scaffold and Centered widgets. So if one wanted to do partial repaint in case like this, would they need to explicitly define the repaint boundaries?

![Screen Shot 2022-07-25 at 11 11 00 AM](https://user-images.githubusercontent.com/43152751/180845466-a53105d7-69a4-4ff2-b250-252e33495142.png)

**Comment by jonahwilliams** [comment]
> You're right! I didn't realize this was the behavior in the case of Scaffold and Centered widgets. So if one wanted to do partial repaint in case like this, would they need to explicitly define the repaint boundaries?

Yes, either a repaint boundary around the animated widget, or if you have a less trivial app that has a list view or something that is handled automagically.

Alternatively, we should consider actually diffing pictures, but that is a much bigger problem.

**Comment by betrevisan** [comment]
That makes sense. After setting wrapping the widget in a boundary region the frame damage was computed as expected. Thank you!
