### ISSUE TITLE
Add test coverage for non-disposed and non-GCed memory leaks.

### ISSUE THREAD

**Issue by polina-c** [flutter/flutter#108322]
Leak-tracker productization should happen first: [leak-tracker](https://github.com/flutter/devtools/blob/master/packages/devtools_app/lib/src/screens/memory/panes/leaks/LEAK_TRACKING.md).

Examples of not disposed leaks: 
https://github.com/flutter/flutter/pull/108193
https://github.com/flutter/flutter/pull/108234
https://github.com/flutter/flutter/pull/108233
https://github.com/flutter/flutter/pull/108228
https://github.com/flutter/flutter/pull/108227

**Comment by goderbauer** [comment]
from triage: I see you removed the priority, which puts this issue back in our triaging queue. What additional triaging is needed here?

**Comment by polina-c** [comment]
Closing as duplicate: it is subtask in https://github.com/flutter/devtools/issues/3951
