### ISSUE TITLE
firebase_database fails if user's system has Gradle 4.0 installed

### ISSUE THREAD

**Issue by albertog** [flutter/flutter#10839]
## Steps to Reproduce

Firebase example with linux OS
https://github.com/flutter/plugins/tree/master/packages/firebase_database/example

## Logs
Run your application with `flutter run` and attach all the log output.
flutter run
Launching lib/main.dart on SM G930F in debug mode...
FAILURE: Build failed with an exception.

* Where:
Build file '/home/albertog/Downloads/plugins-master/packages/firebase_database/example/android/build.gradle' line: 21

* What went wrong:
A problem occurred evaluating root project 'android'.
> A problem occurred configuring project ':app'.
   > Failed to notify project evaluation listener.
      > Could not resolve all dependencies for configuration ':app:_debugApk'.
         > A problem occurred configuring project ':firebase_auth'.
            > Could not resolve all dependencies for configuration ':firebase_auth:_debugPublishCopy'.
               > Could not find com.google.firebase:firebase-core:10.2.1.
                 Required by:
                     project :firebase_auth
               > Could not find com.google.firebase:firebase-auth:10.2.1.
                 Required by:
                     project :firebase_auth
      > Could not get unknown property 'compileDebugJavaWithJavac' for project ':app' of type org.gradle.api.Project.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
Error running gradle: Exit code 1 from: /home/albertog/android-studio/gradle/gradle-3.2/bin/gradle app:properties
Running 'gradle assembleDebug'...                         

FAILURE: Build failed with an exception.

* Where:
Build file '/home/albertog/Downloads/plugins-master/packages/firebase_database/example/android/build.gradle' line: 21

* What went wrong:
A problem occurred evaluating root project 'android'.
> A problem occurred configuring project ':app'.
   > Failed to notify project evaluation listener.
      > Could not resolve all dependencies for configuration ':app:_debugApk'.
         > A problem occurred configuring project ':firebase_auth'.
            > Could not resolve all dependencies for configuration ':firebase_auth:_debugPublishCopy'.
               > Could not find com.google.firebase:firebase-core:10.2.1.
                 Required by:
                     project :firebase_auth
               > Could not find com.google.firebase:firebase-auth:10.2.1.
                 Required by:
                     project :firebase_auth
      > Could not get unknown property 'compileDebugJavaWithJavac' for project ':app' of type org.gradle.api.Project.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
Gradle build failed: 1

Run `flutter analyze` and attach any output of that command also.

Analyzing /home/albertog/Downloads/plugins-master/packages/firebase_database/example...
No issues found!
Ran in 7.8s

## Flutter Doctor

/home/albertog/flutter/bin/flutter --no-color doctor
[✓] Flutter (on Linux, locale en_US.UTF-8, channel master)
    • Flutter at /home/albertog/flutter
    • Framework revision 400a62d121 (20 minutes ago), 2017-06-19 13:36:05 -0700
    • Engine revision 105cc35af3
    • Tools Dart version 1.24.0-dev.6.7

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at /home/albertog/Android/Sdk
    • Platform android-25, build-tools 25.0.3
    • ANDROID_HOME = /home/albertog/Android/Sdk
    • Java binary at: /home/albertog/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] Android Studio (version 2.3)
    • Android Studio at /home/albertog/android-studio
    • Gradle version 3.2
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] WebStorm (version 2017.1)
    • Flutter plugin version 14.0

[✓] Connected devices
    • SM G930F • ad061603092a9939af • android-arm • Android 7.0 (API 24) (emulator)

Process finished with exit code 0

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by Hixie** [comment]
cc @mravn-google

**Comment by mravn-google** [comment]
@albertog You seem to have a version of Gradle installed on your system that is too new for the Gradle plugins used by the example. They make use of API elements that have been removed in Gradle 4.0. You can try to run:
```shell
gradle -v
```
My guess is that comes up with Gradle 4.0 or a variant thereof. The example works for me when built using Gradle 2.14.1 or Gradle 3.3. You can configure Flutter to use a specific Gradle installation by executing `gradle config --gradle-dir path/to/gradle`.

The underlying problem here is that Flutter tooling doesn't enforce use of the [Gradle Wrapper](https://docs.gradle.org/4.0/userguide/gradle_wrapper.html) to ensure repeatable builds. That has been addressed by #10928 (for new projects) and #10993 (for existing projects, still in review).

**Comment by mravn-google** [comment]
Fixed via #10993
