### ISSUE TITLE
Remove macOS OpenGL backend when we roll macOS 10.14 SDK

### ISSUE THREAD

**Issue by cbracken** [flutter/flutter#108304]
All hardware capable of running macOS 10.14 (Mojave) have a Metal-capable GPU since Mojave [requires a Metal-capable GPU](https://support.apple.com/en-us/HT208898). OpenGL support was officially deprecated in the 10.14 SDK.

When we roll our minimum macOS SDK to 10.14, we should remove the fallback for older macOS hardware and only use the Metal backend on macOS. This will reduce app binary size, team maintenance burden, and testing matrix.

Related iOS issue: https://github.com/flutter/flutter/issues/103929

**Comment by JacoFourie** [comment]
This has broken Flutter 3.7.0 on all VM based MacOS systems.

**Comment by giaur500** [comment]
I wouldn't expect Flutter will care MacOS running on VM. However, compatibility has been significally decreased. 99% apps from appstore don't have such requirement, I see no reason why Flutter does.
