### ISSUE TITLE
FfiNative `PictureRecorder::endRecording` wrong return type

### ISSUE THREAD

**Issue by dcharkes** [flutter/flutter#108309]
```dart
  @FfiNative<Handle Function(Pointer<Void>, Handle)>('PictureRecorder::endRecording')
  external void _endRecording(Picture outPicture);
```

https://github.com/flutter/engine/blob/main/lib/ui/painting.dart#L5664-L5665

Either the Dart return type should be `Object` or the native return type should be `Void`.

cc @dnfield, landing the static checks found another issue.

* https://github.com/dart-lang/sdk/issues/49471

I'll revert the added checks in Dart for now.

**Comment by dnfield** [comment]
The native return type shoul dbe `Void`.

**Comment by dnfield** [comment]
Can we just fix this forward and keep the checks?

**Comment by dcharkes** [comment]
It was breaking g3, I'll reland the checks once the Flutter fix has made it to g3.

Shall I make the PR for the fix here and sent it to you?

**Comment by dnfield** [comment]
(feel free to re-open if you need this to track the roll into g3)
