### ISSUE TITLE
Adding Math Equation Support in flutter_markdown package

### ISSUE THREAD

**Issue by codeilm** [flutter/flutter#108375]
## Use case
Writing Mathematical equations in `flutter_markdown` package
I should be able to write equations like  this
```
When $a \ne 0$, there are two solutions to $(ax^2 + bx + c = 0)$ and they are 
$$ x = {-b \pm \sqrt{b^2-4ac} \over 2a} $$
```
and output could be like this
![image](https://user-images.githubusercontent.com/84150407/181046153-59f9a116-2824-489e-a75d-cf62d41c5de1.png)

## Proposal
Add feature of writing mathematical equations in Flutter package : `flutter_markdown`

**Comment by danagbemava-nc** [comment]
Hi @codeilm, see https://github.com/flutter/flutter/issues/81785#issuecomment-934755253. 

There are packages on pub.dev that can help you with what you want to achieve. 

I'll be closing this based on the linked comment. 

Thank you
