### ISSUE TITLE
Deprecate the NotYetDeprecated things

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#108327]
...and make _DefaultBinaryMessenger indirect its channelBuffers usage through the binding.

**Comment by goderbauer** [comment]
Closing this as it was completed by https://github.com/flutter/flutter/pull/116793

**Comment by Hixie** [comment]
weird, i wonder why github didn't autoclose it.

**Comment by goderbauer** [comment]
Maybe because the command to close it was left in a comment (https://github.com/flutter/flutter/pull/116793#issuecomment-1492683174) and not part of the PR description?
