### ISSUE TITLE
[CP] null check error in flutter attach

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#108393]
### issue_link

https://github.com/flutter/flutter/issues/107709

### Commit Hash

1371b8dc3cf3448226c8d2ab0f097741e8364734

### Target

beta

### pr_link

https://github.com/flutter/flutter/pull/108394

### Impacted Users

Flutter developers using the command `flutter attach` for iOS targets

### Impact Description

if a flutter developer uses the command `flutter attach` without the optional `--app-id=$ID` option, they will hit a null check _CastError, because of a mistake when migrating the file to null-safety.

### Workaround

The workaround would be to manually provide the --app-id, would be the bundle identifier.

### Risk

low

### Test Coverage

yes

### Validation Steps

To test, you would need a macOS host device with a working Xcode setup and a physical iOS device.

1. Ensure the iOS device is attached to the macOS host and is detected via `flutter devices`
2. Launch any flutter app on the device in debug mode with `flutter run -d $phone`
3. Detach the CLI tool from the app by pressing `d`
4. Re-attach to the device with `flutter attach`
5. Ensure the tool does not crash with a `_CastError`.

**Comment by itsjustkevin** [comment]
@christopherfujino is this reproducible on stable also?

CC: @zanderso for review.

**Comment by zanderso** [comment]
CP lgtm, this is a fix for one of the null-safety migration mistakes that were anticipated.

**Comment by christopherfujino** [comment]
> @christopherfujino is this reproducible on stable also?
> 
> CC: @zanderso for review.

No, as the regression happened in between the two branch points. Also FYI I'm working on the PR now...

**Comment by itsjustkevin** [comment]
Thank you both for the info!
