### ISSUE TITLE
Fill out the java docs

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#10837]
Our documentation on the Java side is somewhat anemic.

https://docs.flutter.io/javadoc/

For example, FlutterView has many members with no documentation at all.

**Comment by eseidelGoogle** [comment]
Supposedly http://checkstyle.sourceforge.net/ can tell us javadoc coverage infos.

**Comment by matthew-carroll** [comment]
Closing this ticket in favor of numerous granular Javadoc tickets that can be found in the Platform Embedding project:
https://github.com/flutter/flutter/projects/27
