### ISSUE TITLE
linux-12 needs to be deprecated and replaced

### ISSUE THREAD

**Issue by yusuf-goog** [flutter/flutter#108397]
linux-12 is quarantined due to issues it was having, see: https://github.com/flutter/flutter/issues/108050

**Comment by keyonghan** [comment]
Following up in https://chat.google.com/room/AAAAXGgrwSo/oLDosPPLRx4 to see if any insight about the root cause.
Example failed task: https://chromium-swarm.appspot.com/task?id=5c3601e906735b10&o=true&w=true

**Comment by keyonghan** [comment]
It was mentioned that something from machine is corrupted, like faulty disk. Considering to reimage the bot. If still happening, it was suggested to retire the machine.

**Comment by keyonghan** [comment]
Moving to staging for validation.

**Comment by keyonghan** [comment]
The bot is indeed with faulty disk. Below is when re-installing ubuntu image. We should replace the testbed with a new bot (when we get those new NUC back).
![image0](https://user-images.githubusercontent.com/54558023/183131078-7961b4ad-d6df-420d-86c2-4e589a0dbe74.jpeg)
.

**Comment by yusuf-goog** [comment]
new machine provisioned: ip ...183 (till we get the DNS entry fixed)

**Comment by yusuf-goog** [comment]
DNS: t/213375732

**Comment by yusuf-goog** [comment]
linux-12 is up and running now.
