### ISSUE TITLE
Move to Gradle 4.0

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#10833]
Gradle 4.0 is now stable.  @lukef recommends we move our templates and plugins to use such.  @mit-mit @mravn-google

**Comment by mravn-google** [comment]
Dupe of https://github.com/flutter/flutter/issues/10236

**Comment by mravn-google** [comment]
We decided to be consistent with Android Studio here. Current stable version of Android Studio is 2.3.3, and it uses Gradle 3.3 in its project templates. So that's what we do too.

Once Android Studio 3.0.0 is out, we'll use whatever version of Gradle it uses for new projects.
