### ISSUE TITLE
Team members should be able to land reverts TBR

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#108374]
The autosubmit bot blocked a clean revert of the tip-of-tree commit here: https://github.com/flutter/flutter/pull/108349

@keyonghan @godofredoc

**Comment by keyonghan** [comment]
Ah, the logic was removed when refactoring the validations: https://github.com/flutter/cocoon/pull/1891/files

**Comment by keyonghan** [comment]
Assigning to @ricardoamador for a more general revert support.

**Comment by zanderso** [comment]
Another example here https://github.com/flutter/flutter/pull/108882

**Comment by zanderso** [comment]
https://github.com/flutter/cocoon/pull/2062 Does not appear to be working. See https://github.com/flutter/flutter/issues/110479. Bumping this to P2 since the tree is closed on this issue several times a week.

**Comment by keyonghan** [comment]
@ricardoamador is this fixed?

**Comment by ricardoamador** [comment]
Yes reverts can be landed. Unless this is somehow not working now?

**Comment by ricardoamador** [comment]
I am closing this as fixed. The mentioned issue has been resolved as well.
