### ISSUE TITLE
Path.combine doesn't work on web with the html renderer

### ISSUE THREAD

**Issue by justinmc** [flutter/flutter#108382]
Path.combine is unimplemented in the web engine for the html renderer.

[Full context](https://github.com/flutter/engine/blob/9a8686477a471a90e4c8c1c6c67c167a7f8ffc43/lib/web_ui/lib/path.dart#L72)
```dart
  static Path combine(PathOperation operation, Path path1, Path path2) {
    assert(path1 != null); // ignore: unnecessary_null_comparison
    assert(path2 != null); // ignore: unnecessary_null_comparison
    if (engine.useCanvasKit) {
      return engine.CkPath.combine(operation, path1, path2);
    }
    throw UnimplementedError();
  }
```

However, the framework uses it in two places:

https://github.com/flutter/flutter/blob/fe16c206ea19a9e8b9b5ff5ac7b73ea707f98e39/packages/flutter/lib/src/cupertino/text_selection_toolbar.dart#L282

https://github.com/flutter/flutter/blob/fe16c206ea19a9e8b9b5ff5ac7b73ea707f98e39/packages/flutter/lib/src/painting/notched_shapes.dart#L162

Is it intentional that Path.combine can't be used on web with the html renderer?  Should we be guarding against that in these two usages in the framework? CC @mdebbar

**Comment by yjbanov** [comment]
Deduplicating into https://github.com/flutter/flutter/issues/44572
