### ISSUE TITLE
Latest Android SDK (Command-Line Tools Only) cannot be found by Flutter

### ISSUE THREAD

**Issue by Francosf7** [flutter/flutter#108354]
Initially, when running either flutter doctor or flutter doctor --android-licenses, the only information I was getting about the Android Toolchain or Android SDK in my system was:

" Unable to locate Android SDK. "

Now, when running "flutter doctor" command without using options I'm getting: 

[✗] Android toolchain - develop for Android devices
    ✗ ANDROID_HOME = /Users/samuelfranco/android-sdk/cmdline-tools/latest
      but Android SDK not found at this location.

For context, I'm able to run the sdkmanager from within the Android SDK location, inside the "bin" folder in:

/Users/samuelfranco/android-sdk/cmdline-tools/latest/bin

So I think it's unlikely there are "installation" errors. But Flutter just won't recognize the SDK.

I implemented this file structure (<<home>>/android-sdk/cmdline-tools/latest ) strictly following the instructions given in the official Android Developers Download Page for the Android SDK (Command Line Tools Only):

https://developer.android.com/studio/command-line/sdkmanager

Of course I've tried several solutions from across the internet but the most recent ones I've found are from 2020, at which time, the file structure of the Android SDK was different (build-tools, tools and platform-tools were direct children of the sdk folder) as you can see in this old thread:

https://github.com/flutter/flutter/issues/15114

I've set the $ANDROID_HOME environment variable in my /etc/zshrc file as follows:

export ANDROID_HOME="/Users/samuelfranco/android-sdk/cmdline-tools/latest"

and also updated my PATH to include this variable:

export PATH=$PATH:$ANDROID_HOME

So now I get a little bit more information:

![Screen Shot 2022-07-26 at 2 09 33](https://user-images.githubusercontent.com/47958237/180945390-5b89e2db-4ba7-46cc-b306-1bdf70e8c2a0.png)

So, Flutter does read the ANDROID_HOME variable and looks for the Android SDK there... It just doesn't find it (????

**Comment by exaby73** [comment]
Hello @Francosf7. Thanks for filing this issue. Have you tried setting `ANDROID_HOME` to `/Users/samuelfranco/android-sdk` instead?

**Comment by s-ramosm** [comment]
I have the same issue

**Comment by IsaacGamboa00** [comment]
I have the same issue

**Comment by JoseDRamirezM** [comment]
Same here

**Comment by WallBlodige** [comment]
Me too, but I don't know if it's because of permissions on the computer that I don't have access to the folder

**Comment by JJaraSas** [comment]
I have the same issue

**Comment by ZetaMcCormick** [comment]
> Initially, when running either flutter doctor or flutter doctor --android-licenses, the only information I was getting about the Android Toolchain or Android SDK in my system was:
> 
> " Unable to locate Android SDK. "
> 
> Now, when running "flutter doctor" command without using options I'm getting:
> 
> [✗] Android toolchain - develop for Android devices ✗ ANDROID_HOME = /Users/samuelfranco/android-sdk/cmdline-tools/latest but Android SDK not found at this location.
> 
> For context, I'm able to run the sdkmanager from within the Android SDK location, inside the "bin" folder in:
> 
> /Users/samuelfranco/android-sdk/cmdline-tools/latest/bin
> 
> So I think it's unlikely there are "installation" errors. But Flutter just won't recognize the SDK.
> 
> I implemented this file structure (<>/android-sdk/cmdline-tools/latest ) strictly following the instructions given in the official Android Developers Download Page for the Android SDK (Command Line Tools Only):
> 
> https://developer.android.com/studio/command-line/sdkmanager
> 
> Of course I've tried several solutions from across the internet but the most recent ones I've found are from 2020, at which time, the file structure of the Android SDK was different (build-tools, tools and platform-tools were direct children of the sdk folder) as you can see in this old thread:
> 
> #15114
> 
> I've set the $ANDROID_HOME environment variable in my /etc/zshrc file as follows:
> 
> export ANDROID_HOME="/Users/samuelfranco/android-sdk/cmdline-tools/latest"
> 
> and also updated my PATH to include this variable:
> 
> export PATH=$PATH:$ANDROID_HOME
> 
> So now I get a little bit more information:
> 
> ![Screen Shot 2022-07-26 at 2 09 33](https://user-images.githubusercontent.com/47958237/180945390-5b89e2db-4ba7-46cc-b306-1bdf70e8c2a0.png)
> 
> So, Flutter does read the ANDROID_HOME variable and looks for the Android SDK there... It just doesn't find it (?
I've been through the same thing

**Comment by maheshmnj** [comment]
@Francosf7  Your `Android_HOME` should point to the root of the Android SDK folder  and this variable must be defined in rc file (.zshrc or .bashrc depending on your shell) and also ensure the `ANDROID_HOME` is under your `PATH` variable


```
export ANDROID_HOME="/Users/username/Library/Android/sdk"
export PATH="$ANDROID_HOME/tools:$ANDROID_HOME/tools/bin:$ANDROID_HOME/platform-tools:$PATH"
```

Additionally, install the command line tools from the Android studio refer  https://stackoverflow.com/a/67956603/8253662
If it's already installed try uncheck (delete) and reinstall.
