### ISSUE TITLE
flutter_tester must provide actionable information on engine crashes.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#10835]
Currently, the `flutter_tester` executable uploaded to the cloud is built with the debug configuration with symbols stripped. This was done so that none of the assertions in the engine would be stripped away on the desktop shells. This leads to no backtraces being available (since symbol files for the same are not preserved separately) on engine crashes. Also, the binary sizes are unnecessarily large (this has to be downloaded for each configuration, currently at ~45mb each while it should only be ~8mb).

The ideal configuration would be the following:

- [ ] Engine is built in a configuration similar to `release`.
- [ ] Symbol must be available for this engine. Either:
  - [ ] Leaving the executable unstripped. All downloads would be bloated.
  - [ ] Upload the symbols separately (for each platform) and add a symbolize step on engine crashes.
- [ ] Assertions (like `FTL_DLOG`) in the engine must remain enabled in this configuration.

This will give us more readily actionable information for crashes like https://github.com/flutter/flutter/issues/10834.

**Comment by eseidelGoogle** [comment]
FYI @abarth, see also our docs here: https://github.com/flutter/flutter/wiki/Flutter%27s-modes

**Comment by Hixie** [comment]
@chinmaygarde What's the status of this these days?

**Comment by chinmaygarde** [comment]
The `flutter_tester` is already in the `release` (optimized, not the Flutter runtime mode) configuration today. While having an opt-with-asserts build with separate symbols would be nice to have, this has not come up at all in the past year or so.  If there is an issue that requires debugging crashes of the engine in the tester, the local engine development workflow is the recommendation. Closing this issue as no additional progress is likely on this issue.
