### ISSUE TITLE
@ravidhu have you tried wrapping your `DraggableScrollableSheet` in a `PointerInterceptor` widget?

### ISSUE THREAD

**Issue by savdev-ua** [flutter/flutter#108368]
@ravidhu have you tried wrapping your `DraggableScrollableSheet` in a `PointerInterceptor` widget?

Hi. What can i do, if my widget isn't placed in one Stack with map. I mean if we talk about dialog or ModalBottomSheet which comes after the map. In this case your solution doesn't work
I'm using :
(Channel stable, 3.0.2, on macOS 12.1 21C52 darwin-arm, locale en-UA)
pointer_interceptor: ^0.9.3+2

_Originally posted by @ditman in https://github.com/flutter/flutter/issues/80655#issuecomment-871642086_

**Comment by darshankawar** [comment]
@savdev-ua 
Please don't file a new issue using comment from other issue. Use new issue template, fill out requested details so that we'll have enough details to work with.



> Hi. What can i do, if my widget isn't placed in one Stack with map. I mean if we talk about dialog or ModalBottomSheet which comes after the map. In this case your solution doesn't work

This question is better suited for support channels like StackOverflow.
Closing for now.
