### ISSUE TITLE
[CP] Remove Picture/Scene toImageSync from 3.3 beta

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#108471]
### issue_link

https://github.com/flutter/flutter/issues/108389

### Commit Hash

N/A

### Target

beta

### pr_link

https://github.com/flutter/engine/pull/34975

### Impacted Users

Flutter Developers

### Impact Description

Developers that attempt to use a new API that was not quite ready for 3.3 may experience native crashes.

### Workaround

Don't use the new API

### Risk

low

### Test Coverage

yes

### Validation Steps

This is a pure revert, so it is not really risky as long as existing tests pass

**Comment by jonahwilliams** [comment]
Diff is https://gist.github.com/jonahwilliams/dfb5ccc1d44affc0a013d879009fb849, but I guess rather than a CP this is really more of a PR against a release branch?

**Comment by itsjustkevin** [comment]
Looking at the conversation in https://github.com/flutter/flutter/issues/108389, I am going to go ahead and approve this revert.  

I think this would require a revert on master followed by a CP of that revert into the beta branch. 

CC: @CaseyHillers

**Comment by CaseyHillers** [comment]
From the release side, this sounds fine to me.

@jonahwilliams can you open a PR containing your proposed against the branch flutter-3.2-candidate.5?

**Comment by jonahwilliams** [comment]
https://github.com/flutter/engine/pull/34975

**Comment by godofredoc** [comment]
CP has landed in the candidate release branch.
