### ISSUE TITLE
Cache and Pre cache videos

### ISSUE THREAD

**Issue by saddem123** [flutter/flutter#108427]
## Use case
Adding the feature of caching video while playing

It will be nice to add preCaching function without having a controller for every cached video as in some cases we need to precache few seconds from a lot of videos ( that can be streamed later).

## Proposal
In android native there's  `CacheUtil` inside `exoplayer` like an example. It will be great if we have the some feature on flutter too

**Comment by huycozy** [comment]
Hi @saddem123 
I see there are opens issue addressing the case you described #28094 and #92597 (Web)
Closing as a duplication, so please follow up on them for further updates.
