### ISSUE TITLE
Linux android testbeds in staging are all quarantined

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#108461]
Two testbeds linux16 and linux17 in staging pool are all offline. 
<img width="1652" alt="Screen Shot 2022-07-27 at 9 52 30 AM" src="https://user-images.githubusercontent.com/54558023/181304902-00e40e09-c454-43b6-96d7-aa621c0bb19a.png">

This is blocking flakiness validation, and discouraging team to mark tests as flaky:
https://github.com/flutter/flutter/pull/108454#issuecomment-1196970674
https://github.com/flutter/flutter/pull/108449#issuecomment-1196960924

<img width="182" alt="Screen Shot 2022-07-27 at 9 53 08 AM" src="https://user-images.githubusercontent.com/54558023/181304988-dfecd174-238e-4ce7-b576-c6eb59e348db.png">

**Comment by keyonghan** [comment]
Related issue: https://github.com/flutter/flutter/issues/108054

**Comment by yusuf-goog** [comment]
both linux-16 and 17 are now back up.
