### ISSUE TITLE
[Linux] Building snap for linux getting error

### ISSUE THREAD

**Issue by alihassan143test** [flutter/flutter#108419]
<details>
<summary>Error</summary>

`
snapcraft
Launching a VM.
The flutter plugin is currently in beta, its API may break. Use at your own risk.
Skipping pull flutter-extension (already ran)
Skipping pull gnome-3-28-extension (already ran)
Skipping pull rewording (already ran)
Skipping build flutter-extension (already ran)
Skipping build gnome-3-28-extension (already ran)
Building rewording 
+ snapcraftctl build
flutter pub get
   Woah! You appear to be trying to run flutter as root.
   We strongly recommend running the flutter tool without superuser privileges.
  /
📎
Running "flutter pub get" in build...                               5.6s
flutter build linux --release -v -t lib/main.dart
   Woah! You appear to be trying to run flutter as root.
   We strongly recommend running the flutter tool without superuser privileges.
  /
📎
[  +57 ms] executing: uname -m
[  +38 ms] Exit code 0 from: uname -m
[        ] x86_64
[   +8 ms] executing: [/root/snap/flutter/common/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +8 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 9b5019437bcd43c60211a74c3ba0736a0edf957a
[   +1 ms] executing: [/root/snap/flutter/common/flutter/] git tag --points-at 9b5019437bcd43c60211a74c3ba0736a0edf957a
[  +21 ms] Exit code 0 from: git tag --points-at 9b5019437bcd43c60211a74c3ba0736a0edf957a
[   +1 ms] executing: [/root/snap/flutter/common/flutter/] git describe --match *.*.* --long --tags 9b5019437bcd43c60211a74c3ba0736a0edf957a
[  +75 ms] Exit code 0 from: git describe --match *.*.* --long --tags 9b5019437bcd43c60211a74c3ba0736a0edf957a
[        ] 3.0.0-0.0.pre-1899-g9b5019437b
[  +63 ms] executing: [/root/snap/flutter/common/flutter/] git rev-parse --abbrev-ref --symbolic @{upstream}
[   +5 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{upstream}
[        ] origin/master
[        ] executing: [/root/snap/flutter/common/flutter/] git ls-remote --get-url origin
[   +4 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +53 ms] Unable to locate an Android SDK.
[   +5 ms] executing: [/root/snap/flutter/common/flutter/] git rev-parse --abbrev-ref HEAD
[  +14 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[ +147 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +71 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[  +61 ms] Skipping pub get: version match.
[  +83 ms] Found plugin file_picker at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/file_picker-5.0.0/
[   +7 ms] Found plugin file_selector at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/file_selector-0.9.0/
[   +3 ms] Found plugin file_selector_macos at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/file_selector_macos-0.9.0/
[   +4 ms] Found plugin file_selector_web at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/file_selector_web-0.9.0/
[   +2 ms] Found plugin file_selector_windows at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/file_selector_windows-0.9.0/
[  +12 ms] Found plugin flutter_native_splash at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_native_splash-2.2.6/
[   +2 ms] Found plugin flutter_plugin_android_lifecycle at
/root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_plugin_android_lifecycle-2.0.7/
[  +27 ms] Found plugin msix at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/msix-3.6.2/
[   +7 ms] Found plugin path_provider at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider-2.0.11/
[   +2 ms] Found plugin path_provider_android at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_android-2.0.16/
[   +1 ms] Found plugin path_provider_ios at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_ios-2.0.10/
[   +4 ms] Found plugin path_provider_linux at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_linux-2.1.7/
[   +2 ms] Found plugin path_provider_macos at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_macos-2.0.6/
[   +2 ms] Found plugin path_provider_windows at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_windows-2.1.0/
[   +8 ms] Found plugin screen_retriever at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/screen_retriever-0.1.2/
[   +2 ms] Found plugin shared_preferences at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences-2.0.15/
[   +1 ms] Found plugin shared_preferences_android at
/root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_android-2.0.12/
[   +2 ms] Found plugin shared_preferences_ios at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_ios-2.1.1/
[   +1 ms] Found plugin shared_preferences_linux at
/root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_linux-2.1.1/
[   +1 ms] Found plugin shared_preferences_macos at
/root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_macos-2.0.4/
[   +3 ms] Found plugin shared_preferences_web at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_web-2.0.4/
[   +1 ms] Found plugin shared_preferences_windows at
/root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_windows-2.1.1/
[  +22 ms] Found plugin window_manager at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/window_manager-0.2.5/
[  +87 ms] Found plugin file_picker at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/file_picker-5.0.0/
[   +1 ms] Found plugin file_selector at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/file_selector-0.9.0/
[   +1 ms] Found plugin file_selector_macos at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/file_selector_macos-0.9.0/
[   +2 ms] Found plugin file_selector_web at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/file_selector_web-0.9.0/
[   +2 ms] Found plugin file_selector_windows at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/file_selector_windows-0.9.0/
[   +4 ms] Found plugin flutter_native_splash at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_native_splash-2.2.6/
[   +1 ms] Found plugin flutter_plugin_android_lifecycle at
/root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_plugin_android_lifecycle-2.0.7/
[  +17 ms] Found plugin msix at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/msix-3.6.2/
[   +4 ms] Found plugin path_provider at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider-2.0.11/
[   +1 ms] Found plugin path_provider_android at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_android-2.0.16/
[   +1 ms] Found plugin path_provider_ios at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_ios-2.0.10/
[   +1 ms] Found plugin path_provider_linux at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_linux-2.1.7/
[   +1 ms] Found plugin path_provider_macos at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_macos-2.0.6/
[   +1 ms] Found plugin path_provider_windows at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_windows-2.1.0/
[   +7 ms] Found plugin screen_retriever at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/screen_retriever-0.1.2/
[   +1 ms] Found plugin shared_preferences at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences-2.0.15/
[   +1 ms] Found plugin shared_preferences_android at
/root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_android-2.0.12/
[   +5 ms] Found plugin shared_preferences_ios at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_ios-2.1.1/
[   +1 ms] Found plugin shared_preferences_linux at
/root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_linux-2.1.1/
[   +1 ms] Found plugin shared_preferences_macos at
/root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_macos-2.0.4/
[   +2 ms] Found plugin shared_preferences_web at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_web-2.0.4/
[        ] Found plugin shared_preferences_windows at
/root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_windows-2.1.1/
[   +9 ms] Found plugin window_manager at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/window_manager-0.2.5/
[  +50 ms] Found plugin file_picker at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/file_picker-5.0.0/
[        ] Found plugin file_selector at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/file_selector-0.9.0/
[        ] Found plugin file_selector_macos at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/file_selector_macos-0.9.0/
[   +1 ms] Found plugin file_selector_web at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/file_selector_web-0.9.0/
[   +1 ms] Found plugin file_selector_windows at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/file_selector_windows-0.9.0/
[   +2 ms] Found plugin flutter_native_splash at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_native_splash-2.2.6/
[   +2 ms] Found plugin flutter_plugin_android_lifecycle at
/root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_plugin_android_lifecycle-2.0.7/
[   +8 ms] Found plugin msix at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/msix-3.6.2/
[   +1 ms] Found plugin path_provider at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider-2.0.11/
[   +1 ms] Found plugin path_provider_android at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_android-2.0.16/
[   +1 ms] Found plugin path_provider_ios at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_ios-2.0.10/
[        ] Found plugin path_provider_linux at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_linux-2.1.7/
[   +1 ms] Found plugin path_provider_macos at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_macos-2.0.6/
[   +1 ms] Found plugin path_provider_windows at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_windows-2.1.0/
[   +5 ms] Found plugin screen_retriever at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/screen_retriever-0.1.2/
[        ] Found plugin shared_preferences at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences-2.0.15/
[   +1 ms] Found plugin shared_preferences_android at
/root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_android-2.0.12/
[   +1 ms] Found plugin shared_preferences_ios at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_ios-2.1.1/
[   +1 ms] Found plugin shared_preferences_linux at
/root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_linux-2.1.1/
[   +2 ms] Found plugin shared_preferences_macos at
/root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_macos-2.0.4/
[   +1 ms] Found plugin shared_preferences_web at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_web-2.0.4/
[   +1 ms] Found plugin shared_preferences_windows at
/root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_windows-2.1.1/
[   +7 ms] Found plugin window_manager at /root/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/window_manager-0.2.5/
[  +74 ms] Generating /root/parts/rewording/build/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[ +103 ms] 💪 Building with sound null safety 💪
[  +15 ms] Building Linux application...
[  +45 ms] executing: [build/linux/x64/release/] cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DFLUTTER_TARGET_PLATFORM=linux-x64
/root/parts/rewording/build/linux
[  +35 ms] CMake Error: The current CMakeCache.txt directory /root/parts/rewording/build/build/linux/x64/release/CMakeCache.txt is different than the
directory /home/enzipe/Desktop/rewording/build/linux/x64/release where CMakeCache.txt was created. This may result in binaries being created in the
wrong place. If you are not sure, reedit the CMakeCache.txt
[   +3 ms] CMake Error: The source "/root/parts/rewording/build/linux/CMakeLists.txt" does not match the source
"/home/enzipe/Desktop/rewording/linux/CMakeLists.txt" used to generate cache.  Re-run cmake with a different source directory.
[  +21 ms] Building Linux application... (completed in 93ms)
[        ] "flutter linux" took 961ms.
[   +5 ms] Unable to generate build files
[   +4 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      _runCmake (package:flutter_tools/src/linux/build_linux.dart:155:5)
           <asynchronous suspension>
           #2      buildLinux (package:flutter_tools/src/linux/build_linux.dart:76:5)
           <asynchronous suspension>
           #3      BuildLinuxCommand.runCommand (package:flutter_tools/src/commands/build_linux.dart:85:5)
           <asynchronous suspension>
           #4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1209:27)
           <asynchronous suspension>
           #5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #6      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #9      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #10     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #12     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>
           
           
[ +281 ms] ensureAnalyticsSent: 277ms
[   +2 ms] Running shutdown hooks
[   +1 ms] Shutdown hooks complete
[   +8 ms] exiting with code 1
Failed to run 'flutter build linux --release -v -t lib/main.dart' for 'rewording': Exited with code 1.
Verify that the part is using the correct parameters and try again.
Run the same command again with --debug to shell into the environment if you wish to introspect this failure.
`

**Comment by huycozy** [comment]
Hi @alihassan143test, 
Based on the output log:
>[ +35 ms] CMake Error: The current CMakeCache.txt directory /root/parts/rewording/build/build/linux/x64/release/CMakeCache.txt is different than the
directory /home/enzipe/Desktop/rewording/build/linux/x64/release where CMakeCache.txt was created. This may result in binaries being created in the
wrong place. If you are not sure, reedit the CMakeCache.txt
[ +3 ms] CMake Error: The source "/root/parts/rewording/build/linux/CMakeLists.txt" does not match the source
"/home/enzipe/Desktop/rewording/linux/CMakeLists.txt" used to generate cache. Re-run cmake with a different source directory.

Please see this StackOverflow answer for more details https://stackoverflow.com/a/14459230/5921933

Closing as this is neither a bug nor a feature request. If you encounter behavior that you believe could be a bug, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that represents the problem so that we can verify it. Also, please provide the output of `flutter doctor -v` as well.

Thanks!
