### ISSUE TITLE
Flutter asset sync requires a hot restart on windows desktop

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#108492]
(Someone else should probably double check this too...)

Something I noticed when working on shader hot reload, I was not able to successfully sync an asset until I had done at least one full restart. To me, this sounds like an issue that might be caused by https://github.com/flutter/engine/pull/21436 - that is, we expect that we can sync an asset withotu creating a new asset bundle, but we might not be able to.

We should make sure this is wired up correctly for desktop, but as a work around we could change the tool that for desktop target platforms we always do an initial sync of assets

**Comment by jonahwilliams** [comment]
I've investigated more and this doesn't repro on linux and according to @zanderso it doesn't happen on macOS either. This may be windows specific

**Comment by AlexV525** [comment]
I ran into similar issues when running checks on Windows before, could it be improved as well?
- https://ci.chromium.org/ui/p/flutter/builders/try/Windows%20tool_tests_general/14448/overview
- [01:10 +1918 ~4](https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8807292358977506033/+/u/run_test.dart_for_tool_tests_shard_and_subshard_general/test_stdout#:~:text=files%20well%20formatted-,FileSystemException,-%3A%20Exists%20failed%2C%20path)

**Comment by jonahwilliams** [comment]
In general a windows file path with a leading `/` is invalid. I would make sure you are not setting `windows: false` in Uri.toFilePath
