### ISSUE TITLE
PathUrlStrategy rebuilds all parent routes when child is refreshed

### ISSUE THREAD

**Issue by hasanm08** [flutter/flutter#108420]
## Steps to Reproduce

1. Execute `flutter run -d chrome` 
2. remove # in web using PathUrlStartgy
3. refresh pages level 2 like `test.com/x/y`

**Expected results:** 
it should just rebuild route y
**Actual results:** 
it will rebuild both x and y route :)

*this issue does not exist on HashUrlStartegy*

**Comment by danagbemava-nc** [comment]
Hi @hasanm08,

Can you please provide your `flutter doctor -v` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?

Thank you
