### ISSUE TITLE
How to set cookie ?

### ISSUE THREAD

**Issue by ardipermana59** [flutter/flutter#108411]
I wrote as follows. then I tried to look on the web, a cookie with the name my_session_cookie was successful. but the value is always null. 
is there any writing wrong?
```

 var sessionCookie = WebViewCookie(
      name: 'my_session_cookie',
      value: 'cookie_value',
      domain: 'mydomain.com',
);
WebView(
          initialCookies: [sessionCookie],
 ),```

**Comment by maheshmnj** [comment]
Hi @ardipermana59, Please see the [Official sample code](
https://github.com/flutter/plugins/blob/278bc6668567adb5c20dc17a71f03ef404b0d8c8/packages/webview_flutter/webview_flutter/example/lib/main.dart#L379)

```dart
  Future<void> _onSetCookie(
      WebViewController controller, BuildContext context) async {
    await cookieManager.setCookie(
      const WebViewCookie(
          name: 'foo', value: 'bar', domain: 'httpbin.org', path: '/anything'),
    );
    await controller.loadUrl('https://httpbin.org/anything');
  }
```




Closing as this is neither a bug nor a feature request.
