### ISSUE TITLE
[Impeller] Implement path tessellation (fills and strokes) on the GPU

### ISSUE THREAD

**Issue by bdero** [flutter/flutter#108499]
Right now Impeller tessellates every path synchronously on the CPU, and then hauls all of the decompressed geometry to the GPU (the computer that actually needs to use it) via vertex buffers.

These jobs are small enough and plentiful enough to be a great match for homogeneous computing; by moving this work to the GPU, we can reduce PCI traffic (by just uploading smaller path descriptions) and let the GPU scheduler parallelize all of the jobs.

**Comment by bdero** [comment]
I did a bit of research around the possibility of using tessellation shaders to generate fills. My takeaway so far is that we probably can't use it as a standalone solution, but it's quite possible I'm missing some tricks we can do.

Skia has an implementation that [incorporates tessellation shaders](https://bugs.chromium.org/p/skia/issues/detail?id=10419) that I haven't looked at in detail yet. We should figure out what it's doing and figure out what techniques are applicable to us.

## How tessellation shaders work

My understanding is that raster pipeline tessellation works in 3 stages:
1. Control (programmable): Takes a set of "patches" (each of which is an arbitrarily sized polygon) and outputs an LOD value for each.
2. Generation (fixed): Takes the LOD value output by the control shader and subdivides the patch.
3. Evaluation (programmable): Takes the barycentric coordinates output by the generation stage and computes the vertex attributes for the new geometry (positions, etc).

Given this subdivision-centric workflow, I don't think a standalone solution for path fills using only tessellation shaders is broadly possible. However, there might be ways that tessellation shaders could be incorporated as part of the solution. Below is an exploration of some possibilities.

## Possible solution 1: Generate polyline in advance; use one patch.

One partial solution would be to generate the polyline (with all of the cubic curves already evaluated) in advance (on CPU or in a compute shader) and bind it to the pipeline as a single patch, and then have the control shader output an LOD value that's hopefully sufficient.

In this solution, we're just using the tessellation stage to fill in the center of an already completed polyline. The curves were fleshed out in advance when the polyline was generated.

Caveats:
1. This might not work well for concave paths. The generated geometry may end up being visible outside of the paths bounds.
2. The max patch size may be quite low on some devices. OpenGL's minimum patch size limit is only 32.
3. We don't get the benefit of any parallelization at the generation stage. This means execution time for the fixed generation stage scales linearly with the number of vertices.
4. Curve winding rules for overlapping paths need to be handled in advanced.

## Possible solution 2: Generate tessellated mesh in advance; evaluate cubic interpolation in TES.

Another partial solution is to generate a set of patches in advance (on CPU or in a compute shader) that follow along with each component of the path. Curved components have their cubic control points added to the outer facing edge of the patch. The control shader outputs an appropriate > 0 LOD for the patches marked as having an outer cubic edge, and a 0 LOD for everything else. The evaluation shader just maps the generated coordinates with cubic interpolation.

In this solution, we're using the tessellation stage to subdivide the curve edges. The center geometry was already blocked out in advance.

Caveats:
1. We have to solve the "hard" problem in advance of producing a regular mesh consisting of simple convex shapes. We just reserve the subdivision part for the tessellation shader (which is the part it's good at and can parallelize).
2. A good chunk of unnecessary geometry will be generated towards the center of the mesh for particularly curvy shapes.
3. Curve winding rules for overlapping paths need to be unfolded into disconnected patches in advance.

**Comment by dnfield** [comment]
Blocked by https://github.com/flutter/flutter/issues/109346
