### ISSUE TITLE
Trying to render a html in iFrame I am getting "This XML file does not appear to have any style information associated with it."

### ISSUE THREAD

**Issue by pogouveia** [flutter/flutter#108425]
```
Flutter 2.8.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 77d935af4d (7 months ago) • 2021-12-16 08:37:33 -0800
Engine • revision 890a5fca2e
Tools • Dart 2.15.1
```

Try to render a html from an API using different webview plugins I am always getting, after submit in the form inside of it:
"This XML file does not appear to have any style information associated with it. The document tree is shown below."

Tested in different webview plugins: InAppWebView, Webview, flutter_webview_plugin

Can you help us?

The html used in webview was:

<details>
<summary>HTML file</summary>

```html
<!DOCTYPE html SYSTEM "about:legacy-compat">
<html class="no-js" lang="en" xmlns="[http://www.w3.org/1999/xhtml">](http://www.w3.org/1999/xhtml%22%3E)
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <meta charset="utf-8" />
  <title>3D Secure Processing</title>
  <link href="[https://mpi.valitor.com/mdpaympi/static/mpi.css"](https://mpi.valitor.com/mdpaympi/static/mpi.css%22) rel="stylesheet" type="text/css" />
</head>
<body>
  <div id="main">
    <div id="content">
      <div id="order">
        <h2>3D Secure Processing</h2>
        <img src="[https://mpi.valitor.com/mdpaympi/static/preloader.gif"](https://mpi.valitor.com/mdpaympi/static/preloader.gif%22) alt="Please wait.." />
        <img src="[https://mpi.valitor.com/mdpaympi/static/mc_idcheck_hrz_ltd_pos_103px.png"](https://mpi.valitor.com/mdpaympi/static/mc_idcheck_hrz_ltd_pos_103px.png%22) alt="MasterCard ID Check" />
        <div id="formdiv">
          <script type="text/javascript">
            function hideAndSubmitTimed(formid) {
              var timer = setTimeout("hideAndSubmit('" + formid + "');", 999);
            }

            function hideAndSubmit(formid) {
              var formx = document.getElementById(formid);
              if (formx != null) {
                formx.style.visibility = "hidden";
                formx.submit();
              }
            }
          </script>
          <div>
            <form id="webform0" name="ddcoll" method="POST" action="[https://uat.valitorpay.com/ThreeDSecureModirumSimulator/CallbackV4/"](https://uat.valitorpay.com/ThreeDSecureModirumSimulator/CallbackV4/%22) accept_charset="UTF-8">
              <input type="hidden" name="_charset_" value="UTF-8" />
              <input type="hidden" name="txid" value="121028191" />
              <input type="hidden" name="TDS2_Navigator_language" value="" />
              <input type="hidden" name="TDS2_Navigator_javaEnabled" value="" />
              <input type="hidden" name="TDS2_Navigator_jsEnabled" value="" />
              <input type="hidden" name="TDS2_Screen_colorDepth" value="" />
              <input type="hidden" name="TDS2_Screen_height" value="" />
              <input type="hidden" name="TDS2_Screen_width" value="" />
              <input type="hidden" name="TDS2_Screen_PixelDepth" value="" />
              <input type="hidden" name="TDS2_TimezoneOffset" value="" />
              <input type="text" name="digest" value="dd783b0c-fc34-4a77-8af4-3a21eb38b7f3" readonly="true" style="display:none;" />
              <input type="hidden" name="transientData" value="AMmu2jGuNtftpWq7UeOdAoxjDKtIvuO76og/NlG3oe1BjXMUVXNc2hgfNEzM2EtNWYG8/LNXRsROx8780mFzUQega7iOL1g/9NUoVdiav6MAECMHrpFyzhXjGn3ccxveyUKGlQDDFlxgbe5Tw33zpQ/0t6iZz8ASAFlsiOM6sh+jOSxb86zU2PGQ1BuOGGUpGznNxGiASQB7CGKJzldZYyJk37KbnNNW3BWdIsMc2M8TNUjQB5DpRC6PNPLooy8m" />
              <input type="submit" name="submitBtn" value="Please click here to continue" />
            </form>
          </div>
        </div>
        <script type="text/javascript">
          hideAndSubmitTimed('webform0');
        </script>
        <noscript>
          <div align="center">
            <b>Javascript is turned off or not supported!</b>
            <br />
          </div>
        </noscript>
        <script type="text/javascript">
          function populateData() {
            var form = document.getElementById("webform0");
            if (form != null) {
              if (form["TDS2_Navigator_language"] != null) {
                form["TDS2_Navigator_language"].value = (navigator.language || '');
              }
              if (form["TDS2_Navigator_jsEnabled"] != null) {
                // if this scipt runs js is enabled
                form["TDS2_Navigator_jsEnabled"].value = "true";
              }
              if (form["TDS2_Navigator_javaEnabled"] != null) {
                form["TDS2_Navigator_javaEnabled"].value = navigator.javaEnabled();
              }
              if (form["TDS2_Screen_colorDepth"] != null) {
                form["TDS2_Screen_colorDepth"].value = screen.colorDepth;
              }
              if (form["TDS2_Screen_height"] != null) {
                form["TDS2_Screen_height"].value = screen.height;
              }
              if (form["TDS2_Screen_width"] != null) {
                form["TDS2_Screen_width"].value = screen.width;
              }
              if (form["TDS2_Screen_pixelDepth"] != null) {
                form["TDS2_Screen_pixelDepth"].value = screen.pixelDepth;
              }

              var timezoneOffsetField = form["TDS2_TimezoneOffset"];
              if (timezoneOffsetField != null) {
                timezoneOffsetField.value = new Date().getTimezoneOffset();
              }
            }
          }
          populateData();
        </script>
      </div>
      <div id="content-footer">
        <br />
        <img height="20" src="[https://mpi.valitor.com/mdpaympi/static/powered-by-modirum.svg"](https://mpi.valitor.com/mdpaympi/static/powered-by-modirum.svg%22) alt="Powered by Modirum" />
      </div>
    </div>
  </div>
</body>
</html>
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @pogouveia, what happens when you open the HTML in a web browser and submit the form?

**Comment by pogouveia** [comment]
Hi @danagbemava-nc we implemented similar iframe in portal and in the browser after submiting the iframe turns white

**Comment by danagbemava-nc** [comment]
Hi @pogouveia, please provide a complete minimal reproducible code sample along with the version of `webview_flutter` you used. 

However, considering this fails with three separate plugins, I'm not certain this is something we have to resolve on our end. 
You most likely might have to do it on your end.

**Comment by pogouveia** [comment]
flutter_inappwebview: ^5.3.2

Component to render iframe:
`import 'package:flutter/material.dart';
import 'package:flutter_inappwebview/flutter_inappwebview.dart';

class CardVerificationPage extends StatefulWidget {
  final String authenticationHtml;

  CardVerificationPage({Key key, this.authenticationHtml}) : super(key: key);

  @override
  _CardVerificationPage createState() => _CardVerificationPage();
}

class _CardVerificationPage extends State<CardVerificationPage> {
  InAppWebViewController webView;
  PullToRefreshController pullToRefreshController;
  String url;
  final urlController = TextEditingController();

  @override
  Widget build(BuildContext context) {

    return  Column(children: <Widget>[
      Container(height: 30),
      Container(
          height: 500,
          child: InAppWebView(
            initialOptions: InAppWebViewGroupOptions(
                android: AndroidInAppWebViewOptions(
                    useHybridComposition: true,
                    textZoom: 100 * 3,
                    initialScale: 2),
                ios: IOSInAppWebViewOptions(
                    pageZoom: 2.0 //check this zoom, might need to increase
                )),
            pullToRefreshController: pullToRefreshController,
            initialData: InAppWebViewInitialData(
              data: widget.authenticationHtml,
            ),
            onWebViewCreated: (InAppWebViewController controller) {
              webView = controller;
            },
            onLoadStart: (controller, url) {
              setState(() {
                this.url = url.toString();
                urlController.text = this.url;
              });
            },
            onLoadStop: (controller, url) async {
              pullToRefreshController.endRefreshing();
              setState(() {
                this.url = url.toString();
                urlController.text = this.url;
              });
            },
            onLoadError: (controller, url, code, message) {
              pullToRefreshController.endRefreshing();
            },
          ))
    ]);
  }
}

where authenticationHtml is the html that I anexed in the first message.`

**Comment by danagbemava-nc** [comment]
Hi @pogouveia, the sample you have provided uses `flutter_inappwebview`, a third-party plugin. We won't be able to do anything since we do not have ownership of that plugin. 

Please provide a sample that uses `webview_flutter`. 

Thank you
