### ISSUE TITLE
ArgumentError Invalid argument(s): 193.0   _Double.clamp (double.dart:236)

### ISSUE THREAD

**Issue by tomake** [flutter/flutter#108421]
<img width="1963" alt="image" src="https://user-images.githubusercontent.com/4862910/181186781-ea851f9e-a3ce-428f-ba7b-2039e77bdce4.png">

It seems to have appeared in  using NestedScrollView,  but with the stack above i can‘t  get useful information to resolve the crash.

The following devices were experiencing this issue
<img width="1112" alt="image" src="https://user-images.githubusercontent.com/4862910/181190292-002ce04c-04b1-4e1d-9030-c07400d5cc65.png">

<details>
<summary>flutter doctor</summary>

```
[✓] Flutter (Channel stable, 3.0.1, on macOS 12.0.1 21A559 darwin-arm, locale zh-Hans-CN)
[!] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[!] Xcode - develop for iOS and macOS (Xcode 12.4)
    ✗ Flutter requires Xcode 13 or higher.
      Download the latest version or update via the Mac App Store.
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.66.2)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

! Doctor found issues in 2 categories.
```
</details>

**Comment by danagbemava-nc** [comment]
Hi @tomake, please provide the stacktrace in text format. Screenshots aren't very helpful when it comes to logs/stacktraces. 

Thank you

**Comment by tomake** [comment]
hi @danagbemava-nc , the stacktrace is as  follows:

libapp +0x4421bc _Double.clamp (double.dart:236)
libapp +0xc75bb8 _NestedOuterBallisticScrollActivity.applyMoveTo (nested_scroll_view.dart:1510)
libapp +0x49664c BallisticScrollActivity._tick (scroll_activity.dart:553)
libapp +0x496488 BallisticScrollActivity._tick (scroll_activity.dart)
libapp +0x442028 AnimationLocalListenersMixin.notifyListeners (listener_helpers.dart:155)
libapp +0x441b14 AnimationController._tick (animation_controller.dart:830)
libapp +0x44190c AnimationController._tick (animation_controller.dart)
libapp +0x44324c Ticker._tick (ticker.dart:238)
libapp +0x443180 Ticker._tick (ticker.dart)
libapp +0x41ddf0 SchedulerBinding._invokeFrameCallback (binding.dart:1145)
libapp +0x41e338 SchedulerBinding.handleBeginFrame.<T> (binding.dart:1058)
libapp +0x6e7eb0 _LinkedHashMapMixin.forEach (compact_hash.dart:539)
libapp +0x41e0dc SchedulerBinding.handleBeginFrame (binding.dart:1056)
libapp +0x41df78 SchedulerBinding._handleBeginFrame (binding.dart:975)
libapp +0x41df18 SchedulerBinding._handleBeginFrame (binding.dart)
libapp +0x384768 _rootRunUnary (zone.dart:1444)
libapp +0x384870 _rootRunUnary (zone.dart)
libapp +0xbe2240 _CustomZone.runUnary (zone.dart:1335)
libapp +0xbe931c _CustomZone.runUnaryGuarded (zone.dart:1244)
libapp +0x3a4f08 _invoke1 (hooks.dart:169)
libapp +0x3e45c0 PlatformDispatcher._beginFrame (platform_dispatcher.dart:248)
libapp +0x3e4458 _beginFrame (hooks.dart:103)
libapp +0x3e4604 _beginFrame (hooks.dart)

**Comment by danagbemava-nc** [comment]
@tomake, thanks for the logs. 

Are you able to reproduce this locally?

**Comment by tomake** [comment]
@danagbemava-nc  the crash was reported during development,  but i can't reproduce it

**Comment by danagbemava-nc** [comment]
I'll label this for further investigation, but if you are able to reproduce it locally, kindly update the thread with a complete minimal reproducible code sample so that we can investigate this. 

Thank you
