### ISSUE TITLE
Text input cursor blinks even when the app loses Mozart input focus

### ISSUE THREAD

**Issue by yyoon** [flutter/flutter#10847]
We had multiple situations where a cursor was blinking in a text field but it did not actually have Mozart focus.

According to @poitch, the `FocusEvent` needs to be handled in `RuntimeHolder::OnEvent()` (in `runtime_holder.cc`) handler to remove the current focus from the text field when the Mozart focus is lost.

cc: @abarth, @Hixie

**Comment by Hixie** [comment]
cc @chinmaygarde 

We may want to expose this using the AppLifecycle stuff.

**Comment by jxson** [comment]
@eseidelGoogle could you add the customer:blocker label?

**Comment by Hixie** [comment]
I understand this is part of what @chinmaygarde is working on at the moment.

@chinmaygarde, let me know if you'd any help with this one, especially on the framework side (I am less sure what needs doing on the engine side).

**Comment by Hixie** [comment]
We are not actively working on this this week.

**Comment by Hixie** [comment]
Current status is that we believe Fuchsia exposes the necessary APIs for us now and so @chinmaygarde is going to look into what is needed to implement this on our end. My guess is that what we want to do is expose this using AppLifecycleState.inactive (unfocused) and AppLifecycleState.resumed (focused). Once that is done I can make the framework handle this correctly in terms of exposing the focus state to the UI.

**Comment by cbracken** [comment]
@chinmaygarde are we blocked on anything for this anymore?

**Comment by Hixie** [comment]
This is a top priority for our current milestone, since it is considered a blocker by fuchsia.

**Comment by abarth** [comment]
`AppLifecycleState.inactive` doesn't match this state according to https://docs.flutter.io/flutter/dart-ui/AppLifecycleState-class.html.  The app can still receive user input in the form of touch events.

If you want to plan for futures involving desktop operating systems (e.g., Mac OS X and Windows), you actually need two bools:

1. Focused
2. Activated

If a text input control has focus within the app, if the app itself is focused, then the cursor should be visible.  If the app is also activated, then the cursor should blink.  If the app is not active, then the should still be visible, not blink, and appear disabled (e.g., grayed out).  There are also some design languages that adjust the appearance of various other UI elements when the app is active versus inactive.

I'd recommend using `AppLifecycleState.inactive` for the activated boolean (which matches the description in the docs) and having a separate representation of the focused boolean.

You might want to send the focus/blur events through the `SystemChannels.keyEvent` channel.

**Comment by iapicca** [comment]
Hi @yyoon  is this issue still meant to be open?

**Comment by jxson** [comment]
This issue is obsolete, feel free to close.

**Comment by markusaksli-nc** [comment]
Closing as per the comments above
