### ISSUE TITLE
Past Purchases returning empty on Android after upgrade to version 3.0.6

### ISSUE THREAD

**Issue by danielefolatelli** [flutter/flutter#108468]
Past Purchases returning empty on Android after upgrade to version 3.0.6

**Comment by huycozy** [comment]
Hi @danielefolatelli 
According to the [plugin's changelog](https://pub.dev/packages/in_app_purchase/changelog#060):

`
The InAppPurchaseConnection.queryPastPurchases method has been removed. Instead, you should use InAppPurchase.restorePurchases. This method emits each restored purchase on the InAppPurchase.purchaseStream, the PurchaseDetails object will be marked with a status of PurchaseStatus.restored;
`

So you should use `InAppPurchase.restorePurchases` to receive past purchases.
Also, check [this](https://stackoverflow.com/questions/69125209/flutter-get-past-purchases-on-android?rq=1) SO link and see if it helps.

**Comment by danielefolatelli** [comment]
Hi, I am already using restorePurchases. I also checked that link , but I
am still with the same issue.
Also if I try to buy the in app purchase I get a message that I already own
it. I have done a refund so that is also strange.
Any ideas?

**Comment by huycozy** [comment]
Hi @danielefolatelli,
Looks like you are getting the same issue as described in #107454, do you find this similar?

**Comment by danielefolatelli** [comment]
Hi, yes its the same issue.

Daniele Folatelli
Creator and Developer Time To Count

**Comment by huycozy** [comment]
Closing as a duplicate, so please follow up on it for further updates.
