### ISSUE TITLE
Combine TextCapitalization.characters and TextInputType.visiblePassword

### ISSUE THREAD

**Issue by AugustoResende** [flutter/flutter#108443]
## Use case

Make a TextFormField that opens a keyboard with both uppercase letters and immediate number row access.

Currently, doing TextInputType.visiblePassword and TextCapitalization.characters together makes keyboard appear with immediate number row access but the letters turn lowercase.

With TextInputType.text and TextCapitalization.characters, letters are uppercase but can't make appear immedate number row access.

## Proposal

Make TextInputType.visiblePassword and TextCapitalization.characters work together

Ie TextCapitalization.characters work exactly the same with TextInputType.text and TextInputType.visiblePassword.

**Comment by huycozy** [comment]
Hi @AugustoResende, thanks for filing the issue. 

> With TextInputType.text and TextCapitalization.characters, letters are uppercase but can't make appear immedate number row access.

IMO, this works as intended, it requests the default platform keyboard. See https://github.com/flutter/flutter/blob/938ec1452dde11c3709ab17180fcc8254f1aa1fe/packages/flutter/lib/src/services/text_input.dart#L119-L120

With `TextInputType.visiblePassword`, the issue is reproducible. But it seems it is only reproducible on specific devices (verified on both latest `stable` and `master` channels). Please see demo below:

- Pixel 3a Android 12: ❌
- Samsung Galaxy Tab A7: ✅

✅: No Issue ❌: Issue reproduced

---------------------------
### Issue Demo:

```
keyboardType: TextInputType.visiblePassword,
textCapitalization: TextCapitalization.characters,
```

<details>
<summary>Demo 1 (visiblePassword)</summary>

| Pixel 3a | Samsung Galaxy Tab A7 |
| --------------- | --------------- |
<img width="270" src="https://user-images.githubusercontent.com/104349824/181428186-09a3f7e0-0388-42ee-9e37-8b6ff0ae3f04.png"> | <img width="400" src="https://user-images.githubusercontent.com/104349824/181428992-fd9efb1c-c888-4a7b-b27c-020d6416f8d8.png">

</details>


```
keyboardType: TextInputType.text,
textCapitalization: TextCapitalization.characters,
```
<details>
<summary>Demo 2 (text)</summary>

| Pixel 3a | Samsung Galaxy Tab A7 |
| --------------- | --------------- |
<img width="270" src="https://user-images.githubusercontent.com/104349824/181428106-119ce351-511f-468b-9a3c-3e91a62a02a0.png"> | <img width="400" src="https://user-images.githubusercontent.com/104349824/181428992-fd9efb1c-c888-4a7b-b27c-020d6416f8d8.png">

</details>



<details>
<summary>Sample code</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: GestureDetector(
        onTap: () => FocusScope.of(context).requestFocus(FocusNode()),
        child: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            mainAxisSize: MainAxisSize.min,
            children: <Widget>[
              const Text(
                'You have pushed the button this many times: ',
              ),
              Text(
                '$_counter',
                style: Theme.of(context).textTheme.headline4,
              ),
              TextFormField(
                keyboardType: TextInputType.visiblePassword,
                textCapitalization: TextCapitalization.characters,
                decoration: const InputDecoration(
                  labelText: 'Password',
                ),
              ),
            ],
          ),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}

```
</details>

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.2.1 21D62 darwin-x64, locale en-VN)
    • Flutter version 3.0.5 at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (9 hours ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2020.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.69.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.44.0

[✓] Connected device (3 available)
    • SM T225 (mobile) • R9JT3004VRJ • android-arm64  • Android 11 (API 30)
    • macOS (desktop)  • macos       • darwin-x64     • macOS 12.2.1 21D62 darwin-x64
    • Chrome (web)     • chrome      • web-javascript • Google Chrome 103.0.5060.114

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

```bash
[✓] Flutter (Channel master, 3.1.0-0.0.pre.1931, on macOS 12.5 21G72 darwin-x64, locale en-VN)
    • Flutter version 3.1.0-0.0.pre.1931 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 87d36c9abe (39 minutes ago), 2022-07-27 23:28:05 -0400
    • Engine revision 75d212ff08
    • Dart version 2.19.0 (build 2.19.0-42.0.dev)
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13E113
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2020.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.69.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.44.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.5 21G72 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 103.0.5060.134

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```
</details>

**Comment by AugustoResende** [comment]
> Hi @AugustoResende, thanks for filing the issue.
> 
> > With TextInputType.text and TextCapitalization.characters, letters are uppercase but can't make appear immedate number row access.
> 
> IMO, this works as intended, it requests the default platform keyboard. See
> 
> https://github.com/flutter/flutter/blob/938ec1452dde11c3709ab17180fcc8254f1aa1fe/packages/flutter/lib/src/services/text_input.dart#L119-L120
> 
> With `TextInputType.visiblePassword`, the issue is reproducible. But it seems it is only reproducible on specific devices (verified on both latest `stable` and `master` channels). Please see demo below:
> 
> * Pixel 3a Android 12: x
> * Samsung Galaxy Tab A7: white_check_mark
> 
> white_check_mark: No Issue x: Issue reproduced
> 
> ### Issue Demo:
> ```
> keyboardType: TextInputType.visiblePassword,
> textCapitalization: TextCapitalization.characters,
> ```
> 
> Demo 1 (visiblePassword)
> ```
> keyboardType: TextInputType.text,
> textCapitalization: TextCapitalization.characters,
> ```
> 
> Demo 2 (text)
> Sample code
> flutter doctor -v

It's related to Gboard?

**Comment by huycozy** [comment]
@AugustoResende 

> It's related to Gboard?

It seems so. I try using Gboard on Samsung Galaxy Tab A7 and see the same issue with the combination of `TextInputType.visiblePassword` & `TextCapitalization.characters`:

<img width="400" src="https://user-images.githubusercontent.com/104349824/181673969-91827f0e-2904-4068-9e73-b6a9dab474a9.png">

Thanks for spotting this.

**Comment by guillaume-salmon-LM** [comment]
I had the same issue on an Oppo A72 with gboard
`keyboardType: TextInputType.text,
textCapitalization: TextCapitalization.characters,`
Those two don't work together and the `keyboardType` seems to take precedence.

**Comment by justinmc** [comment]
TextInputType and TextCapitalization are used to set Android's [InputType](https://developer.android.com/reference/android/text/InputType) flags [here in the Android embedder](https://github.com/flutter/engine/blob/8f1b77b1ac693524435fe9199ce2e0cb43662bd3/shell/platform/android/io/flutter/plugin/editing/TextInputPlugin.java#L230).  It looks like they're independent.

Can anyone create a native Android app that gives the desired behavior on the affected devices?  If not then there might not be anything that Flutter can do about this.

**Comment by huycozy** [comment]
@justinmc I don't have my affected device anymore but I just created Android native sample code here: https://github.com/huycozy/Android-Native-Sample/tree/108443-caps-visiblepass

In the native sample code, I use these two attributes:

```xml
<EditText
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:inputType="textCapCharacters|textVisiblePassword" />
```

It displays as expected on my device `Realme 6, Android 11` with GBoard:

<details>
<summary>Demo (Android native - Realme 6, Android 11)</summary>

![Screenshot 2023-09-05 at 11 30 56](https://github.com/flutter/flutter/assets/104349824/a66dfd14-194a-42c4-89d1-7590c64216aa)

</details>


@AugustoResende Can you please help to verify this with native sample code on your device?
