### ISSUE TITLE
WidgetApp.onGenerateInitialRoutes and Navigator. defaultGenerateInitialRoutes should have the same types/parameters

### ISSUE THREAD

**Issue by RodXander** [flutter/flutter#108482]
## Use case

This change will be useful in situations where you want to override the `initialRoutes` for certain routes, but keep the usual behavior for the rest. For instance, like when you're initializing deep links vs the normal operation of the app.

Right now, `WidgetsApp.onGenerateInitialRoutes` takes an `InitialRouteListFactory` which returns a `List<Route>` and takes in a `String`. On the other hand, `Navigator. defaultGenerateInitialRoutes` and `Navigator.onGenerateInitialRoutes` take a `RouteListFactory` which returns a `List<Route>` as well, but takes in a `Navigator` and a `String`.

As such, implementations like the following are NOT possible right now, but still necessary:

```
MaterialApp(
    onGenerateInitialRoutes: (initialRoute) {
        if (initialRoute == '/deepLink') {
            return [MaterialPageRoute(builder: (context) => const DeepLinkScreen())]
        }
        else {
            // This is NOT possible
            return Navigator.defaultGenerateInitialRoutes(/*NEEDS a NavigatorState I don't have*/, initialRoute);
        }
    }
)
```

## Proposal

I recommend changing `WidgetsApp.onGenerateInitialRoutes` from an `InitialRouteListFactory` to a `RouteListFactory` like the `Navigator` methods. The previous code will then look like the following:

```
MaterialApp(
    onGenerateInitialRoutes: (navigatorState, initialRoute) {
        if (initialRoute == '/deepLink') {
            return [MaterialPageRoute(builder: (context) => const DeepLinkScreen())]
        }
        else {
            // This is NOW possible
            return Navigator.defaultGenerateInitialRoutes(navigatorState, initialRoute);
        }
    }
)
```

**Comment by maheshmnj** [comment]
cc: @chunhtai

**Comment by chunhtai** [comment]
I don't think this worth the breaking change, you can also use navkey to get the navigator stack
