### ISSUE TITLE
GN error when building macos engine

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#108485]
I'm on unable to build the mac engine at `56af76d122cc820f77a53211d0a08242147d94fe` from a gn error.

## error
```
$ flutter//tools/gn --runtime-mode debug --goma --mac --unoptimized
Using prebuilt Dart SDK binary. If you are editing Dart sources and wish to compile the Dart SDK, set `--no-prebuilt-dart-sdk`.
Generating GN files in: out/mac_debug_unopt
ERROR at //third_party/angle/BUILD.gn:499:7: Can't load input file.
      "$angle_vulkan_headers_dir:vulkan_headers",
      ^-----------------------------------------
Unable to load:
  /Users/aaclarke/dev/engine/src/third_party/angle/third_party/vulkan-deps/vulkan-headers/src/BUILD.gn
I also checked in the secondary tree for:
  /Users/aaclarke/dev/engine/src/build/secondary/third_party/angle/third_party/vulkan-deps/vulkan-headers/src/BUILD.gn
```

## steps to try to remedy the problem
1) `gclient sync` again
1) `gclient sync -D`
1) `gclient sync -D --force`
1) `rm -rf third_party; gclient sync; rm out/mac_debug_unopt`

**Comment by gaaclarke** [comment]
Sometimes the following error happens too, it might be a race which one gets hit first:
```
$ flutter//tools/gn --runtime-mode debug --goma --mac --unoptimized
Using prebuilt Dart SDK binary. If you are editing Dart sources and wish to compile the Dart SDK, set `--no-prebuilt-dart-sdk`.
Generating GN files in: out/mac_debug_unopt
ERROR at //third_party/angle/src/tests/BUILD.gn:5:1: Can't load input file.
import("//build/config/chromecast_build.gni")
^-------------------------------------------
Unable to load:
  /Users/aaclarke/dev/engine/src/build/config/chromecast_build.gni
I also checked in the secondary tree for:
  /Users/aaclarke/dev/engine/src/build/secondary/build/config/chromecast_build.gni
See //third_party/angle/BUILD.gn:74:7: which caused the file to be included.
      "$angle_root/src/tests:angle_tests",
      ^----------------------------------
```

**Comment by gaaclarke** [comment]
This seems to have been introduced in https://github.com/flutter/engine/pull/33814.  If I checkout the version before that (9c9ef561e869f77fc07c41b1bd49e5e5f88b4496) mac builds work.

@dnfield do you know what is going on here?

**Comment by chinmaygarde** [comment]
Were you able to stat either 
`/Users/aaclarke/dev/engine/src/third_party/angle/third_party/vulkan-deps/vulkan-headers/src/BUILD.gn` or 
`/Users/aaclarke/dev/engine/src/build/secondary/third_party/angle/third_party/vulkan-deps/vulkan-headers/src/BUILD.gn`.

Also, a dump of the `args.gn` file from the out directory would be useful.

From Triage: @dnfield wasn't able to reproduce this issue so we need more information about the local environment.

**Comment by gaaclarke** [comment]
> Were you able to stat either `/Users/aaclarke/dev/engine/src/third_party/angle/third_party/vulkan-deps/vulkan-headers/src/BUILD.gn` or `/Users/aaclarke/dev/engine/src/build/secondary/third_party/angle/third_party/vulkan-deps/vulkan-headers/src/BUILD.gn`.

```
aaclarke-macbookpro2:src aaclarke$ ls /Users/aaclarke/dev/engine/src/third_party/angle/third_party/vulkan-deps/vulkan-headers/src/BUILD.gn
ls: /Users/aaclarke/dev/engine/src/third_party/angle/third_party/vulkan-deps/vulkan-headers/src/BUILD.gn: No such file or directory
aaclarke-macbookpro2:src aaclarke$ ls /Users/aaclarke/dev/engine/src/build/secondary/third_party/angle/third_party/vulkan-deps/vulkan-headers/src/BUILD.gn
ls: /Users/aaclarke/dev/engine/src/build/secondary/third_party/angle/third_party/vulkan-deps/vulkan-headers/src/BUILD.gn: No such file or directory
```

> Also, a dump of the `args.gn` file from the out directory would be useful.

```
enable_bitcode = false
skia_enable_flutter_defines = true
skia_use_dng_sdk = false
skia_use_sfntly = false
skia_enable_pdf = false
skia_use_x11 = false
skia_use_wuffs = true
skia_use_expat = false
skia_use_fontconfig = false
skia_use_icu = true
flutter_always_use_skshaper = false
is_official_build = true
is_debug = true
android_full_debug = false
is_clang = true
skia_gl_standard = ""
use_clang_static_analyzer = false
enable_coverage = false
enable_lto = false
target_os = "mac"
target_cpu = "x64"
dart_target_arch = "x64"
host_cpu = "x64"
use_ios_simulator = false
flutter_use_fontconfig = false
flutter_enable_skshaper = true
dart_component_kind = "static_library"
embedder_for_target = false
dart_lib_export_symbols = false
flutter_runtime_mode = "debug"
full_dart_sdk = false
dart_version_git_info = true
dart_runtime_mode = "develop"
enable_desktop_embeddings = true
bssl_use_clang_integrated_as = true
use_goma = true
goma_dir = "/Users/aaclarke/dev/depot_tools/.cipd_bin"
create_xcode_symlinks = true
allow_deprecated_api_calls = true
skia_use_metal = true
shell_enable_metal = true
skia_use_vulkan = true
skia_vulkan_memory_allocator_dir = "//third_party/vulkan_memory_allocator"
shell_enable_vulkan = true
disable_hidden_visibility = false
flutter_prebuilt_dart_sdk = true
dart_sdk_output = "built-dart-sdk"
stripped_symbols = true
```

> From Triage: @dnfield wasn't able to reproduce this issue so we need more information about the local environment.

No one has been able to provide a workaround that gets me building, so I'm blocked here.  I'm not sure if there is something goofy about my setup or if this is a more common error.  No cleaning or deleting of directories has seemed to unblock it yet.

**Comment by chinmaygarde** [comment]
Ok, I can reproduce this. It is because of the specification of the `--mac` flag which should be redundant on the Mac host. Not specifying the flag and generating the `host_foo` (instead of `mac_foo` engine) works fine. Looking into why this flag was added and why its behavior is different.

**Comment by gaaclarke** [comment]
> Ok, I can reproduce this. It is because of the specification of the `--mac` flag which should be redundant on the Mac host. Not specifying the flag and generating the `host_foo` (instead of `mac_foo` engine) works fine. Looking into why this flag was added and why its behavior is different.

Oh interesting, thanks!  I didn't realize that `host` will build the engine for running apps on macOS.  I thought `host` only built the code required to run on the host platform and its tests, ie the binaries used for creating flutter artifacts and communicating with a Flutter process running on the target platform.

If that's not the case, its a bit asymmetrical between desktop and mobile development, no?

**Comment by chinmaygarde** [comment]
> its a bit asymmetrical between desktop and mobile development, no?

It is. We just didn't have the concept of a desktop target back then.
