### ISSUE TITLE
A keyUpEvent is dispatched, but the state shows that the physical key is pressed on a different logical key

### ISSUE THREAD

**Issue by kindkmj** [flutter/flutter#108408]
```dart
 assert(_pressedKeys[event.physicalKey] == event.logicalKey,
          'A ${event.runtimeType} is dispatched, but the state shows that the physical '
          'key is pressed on a different logical key. $common$event '
          'and the recorded logical key ${_pressedKeys[event.physicalKey]}');
```

Problematic code.
![스크린샷 2022-07-27 오전 11 08 27](https://user-images.githubusercontent.com/41276448/181145004-439b7570-3b76-42ad-899c-1ab386a4fb87.png)
![스크린샷 2022-07-27 오전 11 08 45](https://user-images.githubusercontent.com/41276448/181145032-8cc9ca3b-8e73-4772-9c2d-ac48c5aaef29.png)

I want to know why this is happening.

**Comment by maheshmnj** [comment]
Hi @kindkmj, Thanks for filing the issue. Can you please share the output of `flutter doctor -v` and the steps to reproduce the issue?

Thanks
