### ISSUE TITLE
API `/api/push-gold-status-to-github` is failing to update github gold status

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#108463]
Backend error:

```
2022-07-27 10:08:04.416 PDT
Bad state: GithubGoldStatusUpdate should have no more than one entry on repository flutter/flutter, pr 108460.
#0      DatastoreService.queryLastGoldUpdate (package:cocoon_service/src/service/datastore.dart:225:9)
<asynchronous suspension>
#1      PushGoldStatusToGithub._sendStatusUpdates (package:cocoon_service/src/request_handlers/push_gold_status_to_github.dart:65:49)
<asynchronous suspension>
#2      PushGoldStatusToGithub.get (package:cocoon_service/src/request_handlers/push_gold_status_to_github.dart:49:5)
<asynchronous suspension>
#3      RequestHandler.service.<anonymous closure> (package:cocoon_service/src/request_handling/request_handler.dart:49:22)
<asynchronous suspension>
#4      ApiRequestHandler.service.<anonymous closure> (package:cocoon_service/src/request_handling/api_request_handler.dart:151:7)
<asynchronous suspension>
#5      ApiRequestHandler.service (package:cocoon_service/src/request_handling/api_request_handler.dart:150:5)
<asynchronous suspension>
#6      main.<anonymous closure>.<anonymous closure> (file:///app/bin/server.dart:260:9)
<asynchronous suspension>
```

/cc @Piinks

**Comment by Piinks** [comment]
I am not sure why this would be happening, and unfortunately I do not have access to the infra back end dashboard to find out more info.

**Comment by keyonghan** [comment]
With https://github.com/flutter/flutter/pull/108460 submitted. The API is back to work through.

As for the backend log access, could you try: https://pantheon.corp.google.com/logs/query;query=resource.type%3D%22gae_app%22%0Aresource.labels.module_id%3D%22default%22%0Aresource.labels.version_id%3D%22version-6ec0130%22%0A%22%2Fapi%2Fpush-gold-status-to-github%22;cursorTimestamp=2022-07-27T20:33:17.846Z?serviceId=default&project=flutter-dashboard&pli=1

The flutter-team@ should have access.

**Comment by Piinks** [comment]
IT soudns like this is resolved now, should we close, or monitor for a time?

**Comment by keyonghan** [comment]
We can close, but I want to make sure the permission is correctly configured.
Do you have access to the above linked logs?

**Comment by Piinks** [comment]
I do! Thank you! 🎉
