### ISSUE TITLE
File Upload dose not work inside Webview, Flutter

### ISSUE THREAD

**Issue by Ishtiak-20** [flutter/flutter#108540]
I have a website and I converted that website into flutter android application using webview_flutter plugin, everything is working fine.

But there is an issue, there is a form on website in which there is a file input in the form. On website everything works fine but when I click on upload file from android application which I created using webview_flutter plugin, the file input dose not works.

When I click on upload file, it dose not open any popup or anything to allow me to select file from my phone and to upload into the form

**Comment by danagbemava-nc** [comment]
Hi @Ishtiak-20, this is a known limitation of the webview plugin and an issue has already been filed to track the implementation of that feature in https://github.com/flutter/flutter/issues/27924.

Kindly follow up in that issue for updates. 

Closing from here as duplicate. 

Thank you
