### ISSUE TITLE
flutter iOS app crashes when trying to upload image using camera inside Webview

### ISSUE THREAD

**Issue by Ishtiak-20** [flutter/flutter#108541]
I am creating a flutter app using webview_flutter plugin, everything is working fine. In the website, there is a form in which users can upload images(that asks to choose weather to use Camera or Album to choose image). When I tap on Camera the app crashes.

**Comment by huycozy** [comment]
Hi @Ishtiak-20, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this. Also, please provide the output of `flutter doctor -v` as well.
Thank you!
