### ISSUE TITLE
Optimize SaveLayer operation

### ISSUE THREAD

**Issue by JsouLiang** [flutter/flutter#108515]
In this [issue](https://github.com/flutter/flutter/issues/107579) we will know that our DLs have some unnecessary `save/restore` pairs, and we can find a mechanism to solve that, but as we know, the `save` method costs less than the `saveLayer`. So I'm looking for a mechanism to omit the unneeded saveLayer operation.
As this [issue](https://github.com/flutter/flutter/issues/106897) says, this may require starting with the preroll/paint direction of the Layer tree.
cc @flar

**Comment by JsouLiang** [comment]
https://github.com/flutter/engine/pull/35229

**Comment by flar** [comment]
Is this about omitting unused saveLayer operations (as the save elimination was doing), or about peephole optimization of distributing the attributes it applies to the individual content items?

**Comment by JsouLiang** [comment]
I think this could be like as the save elimination doning

**Comment by flar** [comment]
The linked PR seems to be checking for peephole optimization situations, though.

**Comment by jonahwilliams** [comment]
This is a pretty opened bug, i don't think its worth keeping around unless there are some specific peephole circumstances we're not hitting
