### ISSUE TITLE
NVDA screenreader in Windows reads 'back' button as 'button' only

### ISSUE THREAD

**Issue by jacobsimionato** [flutter/flutter#108537]
Reposted from internal bug 240543061, which also has a repro video

Minimal Repro:
```
Scaffold(
      appBar: AppBar(
        centerTitle: false,
        title: Text('Debug Menu'),
      ),
      body: ListView(
        padding: const EdgeInsets.only(top: 8.0),
        children: [
          ListTile(
            leading: _icon(GoogleMaterialIcons.feedback),
            title: Text('Clear Device Logs'),
            key: const Key(debug_menu_keys.clearLogs),
          ),
        ],
      ),
    );
```

To repro:
1. Try running NVDA on the windows machine. Hover over the back button in AppBar it does not respond.
2. Press tab to access all the options

Actual: Should say "Back button" when focusing the back button
Actual: It just says "button" when focusing the back button

**Comment by gspencergoog** [comment]
Assigning to @yaakovschectman for further analysis.

**Comment by yaakovschectman** [comment]
If this repro is run by itself, there is no back button in the app bar. Can you please expand your repro to include enough context for a back button to be presented?

**Comment by cbracken** [comment]
@jacobsimionato as requested by @yaakovschectman.

If this repro is run by itself, there is no back button in the app bar. Can you please expand your repro to include enough context for a back button to be presented?

(Desktop triage)
