### ISSUE TITLE
Linux flutter_plugins fails on release branches due to checking out old version of plugins repo

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#108584]
https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20flutter_plugins/30034/overview is an example failure.

Plugins should run from the tip of tree of that repo instead of at where the betas and stables were branched at.

For the time being, releases should ignore this check.

**Comment by stuartmorgan** [comment]
> Plugins should run from the tip of tree of that repo instead of at where the betas and stables were branched at.

That would make them even less hermetic, and create different kinds of out-of-band failures.

I think the best solution here is actually to just remove this test from the release branches. The purpose is to ensure that people don't change Flutter APIs without considering the effects on the plugins repo; nobody is going to make novel changes on a release branch.

I think the cost of maintaining this test on release branches isn't worth any tiny theoretical benefit we get from running it. Is there an easy way to configure it to be main-branch only?
