### ISSUE TITLE
The `ios-deploy` fails on step `ios-deploy-tests`

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#108560]
Builder `ios-deploy` hasn't been run over the past year. Now it complains:

```
*** If you believe this error represents a bug, please attach the result bundle at /Users/swarming/Library/Developer/Xcode/DerivedData/ios-deploy-ghmaxqjqzwrddrcdlyhaingvldnr/Logs/Test/Test-ios-deploy-tests-2022.07.28_10-37-23--0700.xcresult

2022-07-28 10:37:29.794 xcodebuild[40408:854322]  IDETestOperationsObserverDebug: Failure collecting logarchive: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service named com.apple.testmanagerd.control was invalidated: failed at lookup with error 3 - No such process." UserInfo={NSDebugDescription=The connection to service named com.apple.testmanagerd.control was invalidated: failed at lookup with error 3 - No such process.}
2022-07-28 10:37:29.795 xcodebuild[40408:854248] [MT] IDETestOperationsObserverDebug: 0.023 elapsed -- Testing started completed.
2022-07-28 10:37:29.795 xcodebuild[40408:854248] [MT] IDETestOperationsObserverDebug: 0.000 sec, +0.000 sec -- start
2022-07-28 10:37:29.795 xcodebuild[40408:854248] [MT] IDETestOperationsObserverDebug: 0.023 sec, +0.023 sec -- end

Test session results, code coverage, and logs:
	/Users/swarming/Library/Developer/Xcode/DerivedData/ios-deploy-ghmaxqjqzwrddrcdlyhaingvldnr/Logs/Test/Test-ios-deploy-tests-2022.07.28_10-37-23--0700.xcresult

Testing failed:
	ios-deploy-tests:
		The test runner encountered an error (Failed to establish communication with the test runner. If you believe this error represents a bug, please attach the result bundle at /Users/swarming/Library/Developer/Xcode/DerivedData/ios-deploy-ghmaxqjqzwrddrcdlyhaingvldnr/Logs/Test/Test-ios-deploy-tests-2022.07.28_10-37-23--0700.xcresult. (Underlying Error: Couldn’t communicate with a helper application. Try your operation again. If that fails, quit and relaunch the application and try again. The connection to service named com.apple.testmanagerd.control was invalidated: failed at lookup with error 3 - No such process.))

** TEST FAILED **
```
Example build: https://ci.chromium.org/raw/build/logs.chromium.org/flutter/led/keyonghan_google.com/ee6bd5e65a8f527ca2f91db97f223735186664dfa6e9513335cd66dd54dbb82e/+/build.proto?server=chromium-swarm.appspot.com

@christopherfujino could you help take a look?

Related: https://github.com/flutter/flutter/issues/36019

**Comment by christopherfujino** [comment]
looking

**Comment by christopherfujino** [comment]
Looks like it's the same error as https://github.com/flutter/flutter/issues/101721, so I don't think it's specifically related to this builder? Interestingly, on that issue it was believed to be arm related, however this build ran on intel. cc @jmagman

**Comment by jmagman** [comment]
I can't really pick out exactly what failed, there's
```
rsync: delete_file: rmdir "/opt/s/w/ir/x/w/src/_Frameworks/MobileDevice.framework" failed: Directory not empty (66)
rsync error: some files could not be transferred (code 23) at /System/Volumes/Data/SWE/macOS/BuildRoots/b8ff8433dc/Library/Caches/com.apple.xbs/Sources/rsync/rsync-55/rsync/main.c(996) [sender=2.6.9]
```
but that could be stray logging and not fatal.

@keyonghan  Can we get the `xcresult` directory it says has all the logging?
```
Test session results, code coverage, and logs:
	/Users/swarming/Library/Developer/Xcode/DerivedData/ios-deploy-ghmaxqjqzwrddrcdlyhaingvldnr/Logs/Test/Test-ios-deploy-tests-2022.07.28_10-37-23--0700.xcresult
```
Not sure it will have everything we need since it says `Failure collecting logarchive`.

**Comment by keyonghan** [comment]
A new example build: https://ci.chromium.org/swarming/task/5c74113ddfb78810?server=chromium-swarm.appspot.com, with logs appended.
[Test-ios-deploy-tests-2022.08.01_14-11-54--0700.xcresult.zip](https://github.com/flutter/flutter/files/9238047/Test-ios-deploy-tests-2022.08.01_14-11-54--0700.xcresult.zip)

**Comment by jmagman** [comment]
Unfortunately that xcresult bundle just says
> The test runner encountered an error (Failed to establish communication with the test runner. If you believe this error represents a bug, please attach the result bundle at /Users/swarming/Library/Developer/Xcode/DerivedData/ios-deploy-ghmaxqjqzwrddrcdlyhaingvldnr/Logs/Test/Test-ios-deploy-tests-2022.08.01_14-11-54--0700.xcresult. (Underlying Error: Couldn’t communicate with a helper application. Try your operation again. If that fails, quit and relaunch the application and try again. The connection to service named com.apple.testmanagerd.control was invalidated: failed at lookup with error 3 - No such process.))

We keep seeing versions of this https://github.com/flutter/flutter/issues/100639 https://github.com/flutter/flutter/issues/101721, it seems to be related to how we are running these tests.  

I see SO question https://stackoverflow.com/questions/67688130/run-macos-test-cases-on-the-jenkins-pipeline

We started digging into this in https://github.com/flutter/flutter/issues/101721#issuecomment-1117643193
> > Where are we running tests over SSH?
> 
> Maybe that wasn't the right way to put it, I thought these tests weren't running with the window server running (a user actually logged into the GUI)? It's one of the reasons we think the Safari tests won't launch on newer versions of Xcode.

**Comment by keyonghan** [comment]
Tried running the test locally on mac11:

- checkout `ios-deploy`
- `xcodebuild -configuration Release SYMROOT=build -arch x86_64`
  - Hit 
```
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance
```
And did `sudo xcode-select -s /opt/flutter/xcode/13f17a/XCode.app/Contents/Developer` to workaround
- `xcodebuild test -scheme ios-deploy-tests -configuration Release SYMROOT=build -arch x86_64`

I am hitting the same error: [test.log](https://github.com/flutter/flutter/files/9264073/test.log)

**Comment by jmagman** [comment]
I can't tell what failed, unfortunately, can you upload the bundle it logs like /Users/swarming/Library/Developer/Xcode/DerivedData/ios-deploy-gohpowxwnhiuvffwdnjfdhryzpde/Logs/Test/Test-ios-deploy-tests-2022.08.04_16-19-40--0700.xcresult

**Comment by keyonghan** [comment]
Here it is: [Test-ios-deploy-tests-2022.08.04_16-19-40--0700.xcresult.zip](https://github.com/flutter/flutter/files/9264257/Test-ios-deploy-tests-2022.08.04_16-19-40--0700.xcresult.zip)

**Comment by jmagman** [comment]
Grrr yeah same thing.
Are you seeing the same thing if you open the project in Xcode and run the tests there (**Product -> Test**).

**Comment by keyonghan** [comment]
> Grrr yeah same thing. Are you seeing the same thing if you open the project in Xcode and run the tests there (**Product -> Test**)?

Validated running from xcode succeeded.

**Comment by jmagman** [comment]
I'm not sure what's going on with Xcode here, but stepping back, do we need to run `ios-deploy-tests`?

**Comment by christopherfujino** [comment]
> I'm not sure what's going on with Xcode here, but stepping back, do we need to run `ios-deploy-tests`?

The ultimate test would be devicelab ios tests, I'm ok with skipping these XCtests.

**Comment by keyonghan** [comment]
Cool. I will skip ios-deploy-tests for now.
