### ISSUE TITLE
0-duration routes are not supported...

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#1085]
If you create a route with a transitionDuration of 0ms you'll get the following assert:

'packages/flutter/src/widgets/routes.dart': Failed assertion: line 453: 'performance.status != PerformanceStatus.dismissed' is not true.

**Comment by Hixie** [comment]
as a workaround you can do: 
```dart
List<WidgetBuilder> get builders => <WidgetBuilder>[super.builders[1]];
```
in your route

**Comment by apwilson** [comment]
I tried that workaround and it sometimes doesn't work right when popping and pushing.

**Comment by Hixie** [comment]
The problem might be that zero-duration performances don't actually play(). We should make sure if the duration is 0 than when the performance is started it goes to 1.0, and ends, on the very next frame.

**Comment by eseidelGoogle** [comment]
Pink has created their own routes as a workaround for this issue.  Not currently blocking them, but still probably a nice fix for the framework.

**Comment by chunhtai** [comment]
This seems to be fixed already, I can't reproduce it.
Feel free to reopen if this is still an issue
