### ISSUE TITLE
InputDecorator could animate error to helper text changes, divider color change

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#10858]
See https://github.com/flutter/flutter/pull/10852#discussion_r122886186

We could cross fade between the error and helper text, and animate the divider's color change. 

I don't believe this behavior is specified in (say) https://material.io/guidelines/components/text-fields.html#text-fields-states

**Comment by justinmc** [comment]
@HansMuller Do you know if this is part of the material spec? If not, should we close this issue?

**Comment by HansMuller** [comment]
Seven years later and the [M3 spec still doesn't appear to specify animated transitions](https://m3.material.io/components/text-fields/specs#dbc210fc-c916-4d28-8541-f3ecdb954a62) like this.  I think the time has (finally) come to close this issue :-).
