### ISSUE TITLE
[Codelab] Add better instructions in "Write a Flutter desktop application"

### ISSUE THREAD

**Issue by Umar-Waseem** [flutter/flutter#108533]
After writing the main.dart code and completing **_OAUTH2_** implementation, the app needs to be **stopped** and then be **_started again_** because a plugin is added and simply hot restarting wont work.

I was getting this error . This should be mentioned in the codelab.
~~~
Unhandled Exception: MissingPluginException(No implementation found for method canLaunch on channel plugins.flutter.io/url_launcher)
~~~

**Comment by maheshmnj** [comment]
Hi @Umar-Waseem, Thanks for filing the issue. Can you please point to the codelab you are referring to?

**Comment by Umar-Waseem** [comment]
> Hi @Umar-Waseem, Thanks for filing the issue. Can you please point to the codelab you are referring to?

https://codelabs.developers.google.com/codelabs/flutter-github-client#0

This is the codelab im reffering to.

**Comment by maheshmnj** [comment]
cc: @domesticmouse

**Comment by domesticmouse** [comment]
Fix is in flight.

Googlers: cl/513415878
