### ISSUE TITLE
adb: failed to install C:\Users\Kulka\StudioProjects\spotify\build\app\outputs\flutter-apk\app.apk: Failure [INSTALL_FAILED_UPDATE_INCOMPATIBLE: Package com.example.spotify signatures do not match previously installed version; ignoring!]

### ISSUE THREAD

**Issue by vinaykulk621** [flutter/flutter#108549]
This is the issue i'm facing.
I referred to [this](https://github.com/flutter/flutter/issues/48064) issue but it didn't help.
As much as i can understand, the error tells me to uninstall the app(i think so) or the app is not properly uninstalled.
in my case i am using physical device, and i don't have the app installed on my device.
i tried `flutter clean` did not work
i uninstalled android studio and installed it again but still same issue.
how do i delete an app that is not installed in my phone.

my `flutter run -v`
**### minimal version**

`C:\Users\Kulka\StudioProjects\spotify\build\app\outputs\flutter-apk\app.apk
[+24013 ms] Performing Streamed Install

                     adb: failed to install
                     C:\Users\Kulka\StudioProjects\spotify\build\app\outputs\flutter-apk\app.apk:
                     Failure [INSTALL_FAILED_UPDATE_INCOMPATIBLE: Package com.example.spotify
                     signatures do not match previously installed version; ignoring!]
[   +1 ms] Installing build\app\outputs\flutter-apk\app.apk... (completed in 24.0s)
[   +1 ms] Error: ADB exited with exit code 1
[   +2 ms] Performing Streamed Install
           
           adb: failed to install
C:\Users\Kulka\StudioProjects\spotify\build\app\outputs\flutter-apk\app.apk:
           Failure [INSTALL_FAILED_UPDATE_INCOMPATIBLE: Package com.example.spotify signatures do not
match
           previously installed version; ignoring!]
[   +2 ms] Warning: Failed to install APK.
[   +1 ms] Error launching application on RMX2151.
[   +4 ms] "flutter run" took 44,006ms.
[   +7 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:699:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command.dart:1183:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand
           (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure>
(package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:94:3)
           <asynchronous suspension>

[ +259 ms] ensureAnalyticsSent: 256ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1
`
![image](https://user-images.githubusercontent.com/94120295/181574805-9e447468-4876-4f44-861b-87338a500afd.png)

**### full vesrion**
`PS C:\Users\Kulka\StudioProjects\spotify> flutter run -v
[  +68 ms] executing: [C:\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +290 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +2 ms] f1875d570e39de09040c8f79aa13cc56baab8db1
[   +1 ms] executing: [C:\flutter/] git tag --points-at f1875d570e39de09040c8f79aa13cc56baab8db1
[  +44 ms] Exit code 0 from: git tag --points-at f1875d570e39de09040c8f79aa13cc56baab8db1
[   +1 ms] 3.0.5
[   +9 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +39 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] origin/stable
[        ] executing: [C:\flutter/] git ls-remote --get-url origin
[  +35 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +112 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref HEAD
[  +35 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +74 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +54 ms] executing: C:\Users\Kulka\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +87 ms] List of devices attached
           adb-SSOJXWGQW4S8LZQS-rHc0i0._adb-tls-connect._tcp device product:RMX2151 model:RMX2151 device:RMX2151L1 transport_id:1
[   +5 ms] C:\Users\Kulka\AppData\Local\Android\sdk\platform-tools\adb.exe -s adb-SSOJXWGQW4S8LZQS-rHc0i0._adb-tls-connect._tcp shell getprop
[ +348 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +5 ms] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +117 ms] Skipping pub get: version match.
[  +62 ms] Generating C:\Users\Kulka\StudioProjects\spotify\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +50 ms] ro.hardware = mt6785
[   +2 ms] ro.build.characteristics = default
[  +34 ms] Initializing file store
[  +14 ms] Skipping target: gen_localizations
[  +10 ms] gen_dart_plugin_registrant: Starting due to {InvalidatedReasonKind.inputChanged: The following inputs have updated contents: C:\Users\Kulka\StudioProjects\spotify\.dart_tool\package_config_subset}
[  +32 ms] gen_dart_plugin_registrant: Complete
[   +2 ms] Skipping target: _composite
[   +3 ms] complete
[   +8 ms] Launching lib\main.dart on RMX2151 in debug mode...
[   +7 ms] C:\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev C:\flutter\bin\cache\dart-sdk\bin\snapshots\frontend_server.dart.snapshot --sdk-root
C:\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names --experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true --output-dill
C:\Users\Kulka\AppData\Local\Temp\flutter_tools.3f63eb2e\flutter_tool.c0d5741f\app.dill --packages C:\Users\Kulka\StudioProjects\spotify\.dart_tool\package_config.json -Ddart.vm.profile=false
-Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill build\c075001b96339384a97db4862b8ab8db.cache.dill.track.dill
--enable-experiment=alternative-invalidation-strategy
[  +15 ms] executing: C:\Users\Kulka\AppData\Local\Android\sdk\build-tools\33.0.0\aapt dump xmltree C:\Users\Kulka\StudioProjects\spotify\build\app\outputs\flutter-apk\app.apk AndroidManifest.xml
[  +32 ms] Exit code 0 from: C:\Users\Kulka\AppData\Local\Android\sdk\build-tools\33.0.0\aapt dump xmltree C:\Users\Kulka\StudioProjects\spotify\build\app\outputs\flutter-apk\app.apk AndroidManifest.xml
[   +1 ms] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1f
               A: android:compileSdkVersionCodename(0x01010573)="12" (Raw: "12")
               A: package="com.example.spotify" (Raw: "com.example.spotify")
               A: platformBuildVersionCode=(type 0x10)0x1f
               A: platformBuildVersionName=(type 0x10)0xc
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1f
               E: uses-permission (line=15)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: application (line=17)
                 A: android:label(0x01010001)="spotify" (Raw: "spotify")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:name(0x01010003)="android.app.Application" (Raw: "android.app.Application")
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw: "androidx.core.app.CoreComponentFactory")
                 E: activity (line=23)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A: android:name(0x01010003)="com.example.spotify.MainActivity" (Raw: "com.example.spotify.MainActivity")
                   A: android:exported(0x01010010)=(type 0x12)0xffffffff
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x40003fb4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: meta-data (line=38)
                     A: android:name(0x01010003)="io.flutter.embedding.android.NormalTheme" (Raw: "io.flutter.embedding.android.NormalTheme")
                     A: android:resource(0x01010025)=@0x7f0a0001
                   E: intent-filter (line=42)
                     E: action (line=43)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=45)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw: "android.intent.category.LAUNCHER")
                 E: meta-data (line=52)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw: "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
                 E: uses-library (line=56)
                   A: android:name(0x01010003)="androidx.window.extensions" (Raw: "androidx.window.extensions")
                   A: android:required(0x0101028e)=(type 0x12)0x0
                 E: uses-library (line=59)
                   A: android:name(0x01010003)="androidx.window.sidecar" (Raw: "androidx.window.sidecar")
                   A: android:required(0x0101028e)=(type 0x12)0x0
[   +6 ms] executing: C:\Users\Kulka\AppData\Local\Android\sdk\platform-tools\adb.exe -s adb-SSOJXWGQW4S8LZQS-rHc0i0._adb-tls-connect._tcp shell -x logcat -v time -t 1
[  +18 ms] <- compile package:spotify/main.dart
[ +309 ms] --------- beginning of main
                    07-28 21:00:50.550 D/SwtpMonitorThread( 1510): read swtp_status_buf: 0
[  +10 ms] executing: C:\Users\Kulka\AppData\Local\Android\sdk\platform-tools\adb.exe version
[  +81 ms] Android Debug Bridge version 1.0.41
           Version 33.0.2-8557947
           Installed as C:\Users\Kulka\AppData\Local\Android\sdk\platform-tools\adb.exe
[   +3 ms] executing: C:\Users\Kulka\AppData\Local\Android\sdk\platform-tools\adb.exe start-server
[  +74 ms] Building APK
[  +14 ms] Running Gradle task 'assembleDebug'...
[   +4 ms] Using gradle from C:\Users\Kulka\StudioProjects\spotify\android\gradlew.bat.
[  +14 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
[ +130 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
[   +1 ms] openjdk version "11.0.12" 2021-07-20
           OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
           OpenJDK 64-Bit Server VM (build 11.0.12+7-b1504.28-7817840, mixed mode)
[   +2 ms] executing: [C:\Users\Kulka\StudioProjects\spotify\android/] C:\Users\Kulka\StudioProjects\spotify\android\gradlew.bat -Pverbose=true -Ptarget-platform=android-arm64
-Ptarget=C:\Users\Kulka\StudioProjects\spotify\lib\main.dart -Pbase-application-name=android.app.Application -Pdart-defines=RkxVVFRFUl9XRUJfQVVUT19ERVRFQ1Q9dHJ1ZQ== -Pdart-obfuscation=false
-Ptrack-widget-creation=true -Ptree-shake-icons=false -Pfilesystem-scheme=org-dartlang-root assembleDebug
[ +986 ms] Welcome to Gradle 7.4!
[        ] Here are the highlights of this release:
[        ]  - Aggregated test and JaCoCo reports
[        ]  - Marking additional test source directories as tests in IntelliJ
[        ]  - Support for Adoptium JDKs in Java toolchains
[        ] For more details see https://docs.gradle.org/7.4/release-notes.html
[+2494 ms] > Task :app:preBuild UP-TO-DATE
[   +1 ms] > Task :app:preDebugBuild UP-TO-DATE
[        ] > Task :app:mergeDebugNativeDebugMetadata NO-SOURCE
[+11107 ms] > Task :app:compileFlutterBuildDebug
[  +82 ms] > Task :app:packLibsflutterBuildDebug UP-TO-DATE
[        ] > Task :app:compileDebugAidl NO-SOURCE
[        ] > Task :app:compileDebugRenderscript NO-SOURCE
[        ] > Task :app:generateDebugBuildConfig UP-TO-DATE
[ +109 ms] > Task :app:checkDebugAarMetadata UP-TO-DATE
[        ] > Task :app:cleanMergeDebugAssets
[        ] > Task :app:mergeDebugShaders UP-TO-DATE
[        ] > Task :app:compileDebugShaders NO-SOURCE
[        ] > Task :app:generateDebugAssets UP-TO-DATE
[  +93 ms] > Task :app:mergeDebugAssets
[ +203 ms] > Task :app:copyFlutterAssetsDebug
[   +1 ms] > Task :app:generateDebugResValues UP-TO-DATE
[        ] > Task :app:generateDebugResources UP-TO-DATE
[        ] > Task :app:mergeDebugResources UP-TO-DATE
[        ] > Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
[        ] > Task :app:extractDeepLinksDebug UP-TO-DATE
[        ] > Task :app:processDebugMainManifest UP-TO-DATE
[        ] > Task :app:processDebugManifest UP-TO-DATE
[        ] > Task :app:processDebugManifestForPackage UP-TO-DATE
[ +100 ms] > Task :app:processDebugResources UP-TO-DATE
[        ] > Task :app:compileDebugKotlin UP-TO-DATE
[        ] > Task :app:javaPreCompileDebug UP-TO-DATE
[  +98 ms] > Task :app:compileDebugJavaWithJavac UP-TO-DATE
[ +102 ms] > Task :app:processDebugJavaRes NO-SOURCE
[ +100 ms] > Task :app:mergeDebugJavaResource UP-TO-DATE
[ +200 ms] > Task :app:checkDebugDuplicateClasses UP-TO-DATE
[        ] > Task :app:dexBuilderDebug UP-TO-DATE
[        ] > Task :app:desugarDebugFileDependencies UP-TO-DATE
[        ] > Task :app:mergeExtDexDebug UP-TO-DATE
[        ] > Task :app:mergeDexDebug UP-TO-DATE
[        ] > Task :app:mergeDebugJniLibFolders UP-TO-DATE
[        ] > Task :app:mergeDebugNativeLibs UP-TO-DATE
[        ] > Task :app:stripDebugDebugSymbols UP-TO-DATE
[  +82 ms] > Task :app:validateSigningDebug UP-TO-DATE
[        ] > Task :app:writeDebugAppMetadata UP-TO-DATE
[        ] > Task :app:writeDebugSigningConfigVersions UP-TO-DATE
[ +607 ms] > Task :app:compressDebugAssets
[        ] Execution optimizations have been disabled for task ':app:compressDebugAssets' to ensure correctness due to the following reasons:
[        ]   - Gradle detected a problem with the following location: 'C:\Users\Kulka\StudioProjects\spotify\build\app\intermediates\assets\debug\mergeDebugAssets'. Reason: Task ':app:compressDebugAssets' uses
this output of task ':app:copyFlutterAssetsDebug' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please
refer to https://docs.gradle.org/7.4/userguide/validation_problems.html#implicit_dependency for more details about this problem.
[ +104 ms] > Task :app:packageDebug UP-TO-DATE
[        ] > Task :app:createDebugApkListingFileRedirect UP-TO-DATE
[  +66 ms] > Task :app:assembleDebug
[   +1 ms] Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
[        ] You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
[        ] See https://docs.gradle.org/7.4/userguide/command_line_interface.html#sec:command_line_warnings
[   +1 ms] Execution optimizations have been disabled for 1 invalid unit(s) of work during this build to ensure correctness.
[        ] Please consult deprecation warnings for more details.
[        ] BUILD SUCCESSFUL in 16s
[        ] 35 actionable tasks: 6 executed, 29 up-to-date
[ +565 ms] Running Gradle task 'assembleDebug'... (completed in 17.3s)
[ +136 ms] calculateSha: LocalDirectory: 'C:\Users\Kulka\StudioProjects\spotify\build\app\outputs\flutter-apk'/app.apk
[ +540 ms] √  Built build\app\outputs\flutter-apk\app-debug.apk.
[   +4 ms] executing: C:\Users\Kulka\AppData\Local\Android\sdk\build-tools\33.0.0\aapt dump xmltree C:\Users\Kulka\StudioProjects\spotify\build\app\outputs\flutter-apk\app.apk AndroidManifest.xml
[  +35 ms] Exit code 0 from: C:\Users\Kulka\AppData\Local\Android\sdk\build-tools\33.0.0\aapt dump xmltree C:\Users\Kulka\StudioProjects\spotify\build\app\outputs\flutter-apk\app.apk AndroidManifest.xml
[   +1 ms] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1f
               A: android:compileSdkVersionCodename(0x01010573)="12" (Raw: "12")
               A: package="com.example.spotify" (Raw: "com.example.spotify")
               A: platformBuildVersionCode=(type 0x10)0x1f
               A: platformBuildVersionName=(type 0x10)0xc
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1f
               E: uses-permission (line=15)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: application (line=17)
                 A: android:label(0x01010001)="spotify" (Raw: "spotify")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:name(0x01010003)="android.app.Application" (Raw: "android.app.Application")
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw: "androidx.core.app.CoreComponentFactory")
                 E: activity (line=23)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A: android:name(0x01010003)="com.example.spotify.MainActivity" (Raw: "com.example.spotify.MainActivity")
                   A: android:exported(0x01010010)=(type 0x12)0xffffffff
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x40003fb4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: meta-data (line=38)
                     A: android:name(0x01010003)="io.flutter.embedding.android.NormalTheme" (Raw: "io.flutter.embedding.android.NormalTheme")
                     A: android:resource(0x01010025)=@0x7f0a0001
                   E: intent-filter (line=42)
                     E: action (line=43)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent
.action.MAIN")
                     E: category (line=45)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw: "android.
intent.category.LAUNCHER")
                 E: meta-data (line=52)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw: "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
                 E: uses-library (line=56)
                   A: android:name(0x01010003)="androidx.window.extensions" (Raw: "androidx.window.ex
tensions")
                   A: android:required(0x0101028e)=(type 0x12)0x0
                 E: uses-library (line=59)
                   A: android:name(0x01010003)="androidx.window.sidecar" (Raw: "androidx.window.sidec
ar")
                   A: android:required(0x0101028e)=(type 0x12)0x0
[   +2 ms] Stopping app 'app.apk' on RMX2151.
[   +1 ms] executing: C:\Users\Kulka\AppData\Local\Android\sdk\platform-tools\adb.exe -s adb-SSOJXWGQ
W4S8LZQS-rHc0i0._adb-tls-connect._tcp shell am force-stop com.example.spotify
[ +374 ms] executing: C:\Users\Kulka\AppData\Local\Android\sdk\platform-tools\adb.exe -s adb-SSOJXWGQ
W4S8LZQS-rHc0i0._adb-tls-connect._tcp shell pm list packages com.example.spotify
[ +155 ms] Installing APK.
[   +2 ms] Installing build\app\outputs\flutter-apk\app.apk...
[        ] executing: C:\Users\Kulka\AppData\Local\Android\sdk\platform-tools\adb.exe -s adb-SSOJXWGQ
W4S8LZQS-rHc0i0._adb-tls-connect._tcp install -t -r
C:\Users\Kulka\StudioProjects\spotify\build\app\outputs\flutter-apk\app.apk
[+24013 ms] Performing Streamed Install

                     adb: failed to install
                     C:\Users\Kulka\StudioProjects\spotify\build\app\outputs\flutter-apk\app.apk:
                     Failure [INSTALL_FAILED_UPDATE_INCOMPATIBLE: Package com.example.spotify
                     signatures do not match previously installed version; ignoring!]
[   +1 ms] Installing build\app\outputs\flutter-apk\app.apk... (completed in 24.0s)
[   +1 ms] Error: ADB exited with exit code 1
[   +2 ms] Performing Streamed Install
           
           adb: failed to install
C:\Users\Kulka\StudioProjects\spotify\build\app\outputs\flutter-apk\app.apk:
           Failure [INSTALL_FAILED_UPDATE_INCOMPATIBLE: Package com.example.spotify signatures do not
match
           previously installed version; ignoring!]
[   +2 ms] Warning: Failed to install APK.
[   +1 ms] Error launching application on RMX2151.
[   +4 ms] "flutter run" took 44,006ms.
[   +7 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:699:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command.dart:1183:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand
           (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure>
(package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:94:3)
           <asynchronous suspension>

[ +259 ms] ensureAnalyticsSent: 256ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1
`

**Comment by huycozy** [comment]
Hi @vinaykulk621 
It seems your question is best suited for support channels like StackOverflow, so please ask the same there for solutions if any. Please see this StackOverflow answer for more details: https://stackoverflow.com/a/53396378/5921933
Closing as this is neither a bug nor a feature request.
