### ISSUE TITLE
GoogleSignIn plugin should not throw if user cancels sign-in

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#10856]
It currently throws, causing app code to have to catch an error to handle the user cancelling the sign-in.

e.g. in the sign-in example app: https://github.com/flutter/plugins/blob/0909e96c366f2f06643dd8f3be779a84aec37750/packages/google_sign_in/example/lib/main.dart#L100

Instead, it should just return `null` -- https://github.com/flutter/plugins/blob/0909e96c366f2f06643dd8f3be779a84aec37750/packages/google_sign_in/lib/google_sign_in.dart#L192

**Comment by mehmetf** [comment]
@goderbauer wants to fix this in the current PR for manually managed connections

**Comment by mehmetf** [comment]
I have an open PR for it which can be merged to Michael's PR. https://github.com/flutter/plugins/pull/147

**Comment by goderbauer** [comment]
Fixed by https://github.com/flutter/plugins/pull/148.

**Comment by mit-mit** [comment]
@tvolkert @mehmetf @goderbauer are we will looking at this? Or was it fixed already?

**Comment by tvolkert** [comment]
This was fixed by https://github.com/flutter/plugins/pull/153
