### ISSUE TITLE
flutter app on Android 4.4 devices calls on Android Accessibility APIs that are not available

### ISSUE THREAD

**Issue by slowtick** [flutter/flutter#10855]
## Steps to Reproduce

Built a [flutter app](https://play.google.com/store/apps/details?id=com.slowtick.icer) and tested it on Android device with OS version 4.4.x and Android API level 19.
Firebase crash reporter caught NoClassDefFoundError.

## Logs

From Firebase crash report.

`
Exception java.lang.NoClassDefFoundError: android.view.accessibility.AccessibilityNodeInfo$AccessibilityAction
io.flutter.view.AccessibilityBridge.createAccessibilityNodeInfo (AccessibilityBridge.java:136)
android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchDescendantsOfVirtualNode (AccessibilityInteractionController.java:917)
android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchDescendantsOfRealNode (AccessibilityInteractionController.java:838)
android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchDescendantsOfRealNode (AccessibilityInteractionController.java:834)
android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchDescendantsOfRealNode (AccessibilityInteractionController.java:834)
android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchAccessibilityNodeInfos (AccessibilityInteractionController.java:720)
android.view.AccessibilityInteractionController.findAccessibilityNodeInfoByAccessibilityIdUiThread (AccessibilityInteractionController.java:147)
android.view.AccessibilityInteractionController.access$300 (AccessibilityInteractionController.java:49)
android.view.AccessibilityInteractionController$PrivateHandler.handleMessage (AccessibilityInteractionController.java:971)
android.os.Handler.dispatchMessage (Handler.java:102)
android.os.Looper.loop (Looper.java:157)
android.app.ActivityThread.main (ActivityThread.java:5633)
java.lang.reflect.Method.invokeNative (Method.java)
java.lang.reflect.Method.invoke (Method.java:515)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:896)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:712)
dalvik.system.NativeStart.main (NativeStart.java)`

## Flutter Doctor

Sorry, will add this later today

## Troubleshooting

Below seems to be triggering the crash

1. Android [AccessibilityNodeInfo.AccessibilityAction fields were available from Android API 21 onwards](https://developer.android.com/reference/android/view/accessibility/AccessibilityNodeInfo.AccessibilityAction.html#ACTION_ACCESSIBILITY_FOCUS)

2. [Flutter Engine calls on the AccessibilityNodeInfo Android API but misses error handling for Android API levels below 21](https://github.com/flutter/engine/blob/25c7a86a5343969c734adb788041d3976430f4ec/shell/platform/android/io/flutter/view/AccessibilityBridge.java#L134).

**Comment by eseidelGoogle** [comment]
FYI @goderbauer
