### ISSUE TITLE
[Image_Picker] retrieveLostData() should return an identifier

### ISSUE THREAD

**Issue by cedvdb** [flutter/flutter#108551]
When an application crashes when using image picker, as far as I understand there is no way to know which part of the app made the original call to pickImage.

Currently I'm storing a key with `pickFile(String lostDataKey)` and if the `retrieveLostData(String lostDataKey)` key is different than the one that is stored it return null, if it's the same `ImagePicker.retrieveLostData` is called.

# Proposal

Add key param to image picker `pickFile` and `retrieveLostData()`.

If that's not how this is supposed to be handled the doc should be clearer.

**Comment by stuartmorgan** [comment]
> as far as I understand there is no way to know which part of the app made the original call to pickImage

Restoring the overall state of your app is not in scope for `image_picker`; it's something that applications should be handling regardless of this plugin. `retrieveLostData` is a utility to get the plugin's data during that restoration process, not to get any other app state.
