### ISSUE TITLE
PluginRegistry: onRequestPermissionResult should be onRequestPermissionsResult

### ISSUE THREAD

**Issue by ianbarber** [flutter/flutter#10853]
Nit, but confused me for a minute. 

https://docs.flutter.io/javadoc/io/flutter/plugin/common/PluginRegistry.RequestPermissionResultListener.html

This offers onRequestPermissionResult, which I believe is supposed to wrap the system or compat method, which is https://developer.android.com/reference/android/support/v4/app/ActivityCompat.OnRequestPermissionsResultCallback.html#onRequestPermissionsResult(int, java.lang.String[], int[]) onRequestPermissionsResult - note Permissions is plural, not singular. Should probably be that way across the board.

**Comment by Hixie** [comment]
cc @mravn-google @mit-mit

**Comment by Hixie** [comment]
Since this is an API-breaking change, we should make it soon if we're going to do it at all.
