### ISSUE TITLE
Classes that depend on PageStorage need to explain PageStorageKeys

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#10867]
Currently the scrollable classes, ExpansionTile, and PaginatedDataTable rely on PageStorage to save and restore state across widget lifetimes. The corresponding API doc should explain the implications of PageStorageKeys, particularly the need to for multiple PageStorage clients to distinguish themselves.

**Comment by pedromassangocode** [comment]
Related to https://github.com/flutter/flutter/issues/10868

**Comment by pedromassangocode** [comment]
Found in `1.17.5`.

The current documentation of `PaginatedDataTable` and `ExpansionTile` does not explain the usage of `PageStorageKeys`.

https://api.flutter.dev/flutter/material/PaginatedDataTable-class.html
https://api.flutter.dev/flutter/material/ExpansionTile-class.html
