### ISSUE TITLE
Typo in documentation for SliverChildListDelegate

### ISSUE THREAD

**Issue by swch01** [flutter/flutter#108619]
There is a missing backtick before `children` in this doc comment.

```
  /// If the order of children` never changes, consider using the constant
  /// [SliverChildListDelegate.fixed] constructor.
```

**Comment by danagbemava-nc** [comment]
From triage: 

https://github.com/flutter/flutter/blob/a62ee852950a2f2b69c2ffe733eb82e56cc616b9/packages/flutter/lib/src/widgets/sliver.dart#L574

**Comment by cofirazak** [comment]
This issues is fixed and should be closed.
Now there is no backticks
<img width="559" alt="image" src="https://user-images.githubusercontent.com/2613578/182014686-7a0f4c09-0c16-447c-aa00-7a980936e844.png">
