### ISSUE TITLE
Default handling of back button is non-intuitive

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#1086]
Not a bug, but maybe an area for us to make things less surprising?

Looks like the default behavior (assuming you are not using MaterialApp) is to ignore the back button (on Android). A developer could use MaterialApp to get the back button behavior, but that might be overkill for super simple apps.

The default behavior of exiting the app if the back button is tapped is probably something non-material apps want to add easily, or simply assume.

Could the behavior of "if the user taps the back button, and the app is on the only screen and/or has no navigator, then the app exits" be the default?

Another idea that was proposed: extract simple rules of back button handling out of MaterialApp into something any app could easily use.

Thanks!

**Comment by Hixie** [comment]
Should the back button go back if your application is just:

```dart
void main() { }
```

...?

**Comment by abarth** [comment]
I think it would be fair for the FlutterWidgetBinding to introduce the default behavior.  It already knows whether any of the BindingObservers consumed the pop.
