### ISSUE TITLE
NavigatorObserver is not working when used with onGenerateRoute

### ISSUE THREAD

**Issue by subzero911** [flutter/flutter#108613]
I found the same issue https://github.com/flutter/flutter/issues/61341
But I'm not satisfied with the suggested solution.
@chunhtai advised to wrap every widget in onGenerateRoute into RouteAwareWidget, and do all the job in its didPush() / didPopNext() callbacks.
But it looks like a crutch, and not convenient. I have to write a custom RouteAwareWidget for it and to add the didPush() logic into it.
I already have a custom class extending NavigatorObserver and want to use it as a single entrypoint to handle the push / pop events. I don't want to handle it in multiple places.
It would be better to fix NavigatorObserver to watch not only `routes` but also `onGenerateRoute`. It was a bad surprise for me that it doesn't see onGenerateRoute, and it is a non-obvious behaviour.

![image](https://user-images.githubusercontent.com/12999702/181750049-13c39fe8-3911-4491-95ae-e51ab4b188a2.png)

**Comment by darshankawar** [comment]
@subzero911 
Can you provide what's the current behavior as compared to expected result are you looking for ?

**Comment by subzero911** [comment]
Example from the application I'm developing.

**Current behaviour:**

```dart
MaterialApp(
...
      navigatorObservers: [mainNavigatorObserver],
      initialRoute: Routes.splash,
      // I use onGenerateRoute to create a CupertinoPageRoute
      onGenerateRoute: (settings) {
        // mainNavigatorObserver does not see it
        if (settings.name == Routes.placeEventDetail) {
          final args = settings.arguments as Event;
          return CupertinoPageRoute(
            builder: (_) => PlaceEventDetailScreen(args),
            fullscreenDialog: true,
          );
        }
      },
     routes: {
        Routes.splash: (_) => SplashScreen(),
        Routes.pinHello: (_) => PinHelloScreen(),
        Routes.pinCode: (_) => PinCodeScreen(),
        Routes.issueBankCard: (_) => IssueBankCardScreen(),
        Routes.issueBankCardConfirmation: (_) => IssueBankCardConfirmationScreen(),
        Routes.developer: (_) => DeveloperScreen(),
        Routes.logDetails: (_) => ScreenLogDetails(),
        Routes.authEsia: (_) => AuthEsiaScreen(),
        Routes.authConsent: (context) {
          AuthConsentArguments arguments = ModalRoute.of(context)!.settings.arguments as AuthConsentArguments;
          return AuthConsentScreen(arguments);
        },
       ....
       }
...
)

class _MainNavigationObserver extends RouteObserver<PageRoute> {
  final TelemetryManager _telemetryManager = GetIt.I<TelemetryManager>();

  final routeToTelemetryIdMap = <String, TelemetryScreenId>{
    Routes.splash: TelemetryScreenId.Splash,
    Routes.authEsia: TelemetryScreenId.Auth,
    Routes.authConsent: TelemetryScreenId.AuthConsent,
    Routes.issueBankCard: TelemetryScreenId.AuthOnboard,
    Routes.home: TelemetryScreenId.Home,
    Routes.account: TelemetryScreenId.Account,
    Routes.issueBankCardOtp: TelemetryScreenId.RegisterOtp,
    Routes.map: TelemetryScreenId.Places,
    FaqScreen.route: TelemetryScreenId.Faq,
    .....
    Routes.needUpdatePassportData: TelemetryScreenId.NeedUpdatePassportData,    
    Routes.placeEventDetail: TelemetryScreenId.EventDetail,
  };

  @override
  void didPush(Route route, Route? previousRoute) {
    super.didPush(route, previousRoute);

    if (route.settings.name == null || route.settings.name == Routes.splash) {
      return;
    }

    final telemetryId = routeToTelemetryIdMap[route.settings.name!] ?? TelemetryScreenId.Unknown;

    _telemetryManager.trackEvent(EventScreenOpen(), telemetryId).ignore();
    log.d('[telemetry] didPush: $telemetryId');
  }
}
```

**Expected behaviour:** NavigatorObserver track routes which returned in onGenerateRoutes.
But it didn't, didPush() didn't execute, and no telemetry was sent!
Because NavigatorObserver currently can't track routes in onGenerateRoute, I also have to do additional work: to manually create a RouteAware State for PlaceEventDetailScreen widget, to handle the telemetry logic and to subscribe and unsubscribe to the main NavigatorObserver:

```dart
class _PlaceEventDetailScreenState extends State<PlaceEventDetailScreen> with RouteAware {
  late final TelemetryManager _telemetryManager;

  @override
  void didPush() {
    super.didPush();

    _telemetryManager.trackEvent(EventScreenOpen(), TelemetryScreenId.EventDetail).ignore();    
  }

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    mainNavigatorObserver.subscribe(this, ModalRoute.of(context) as PageRoute);
  }

  @override
  void dispose() {
    mainNavigatorObserver.unsubscribe(this);
    super.dispose();
  }
...
}
```

**Desired behaviour:**

NavigatorObserver should automatically watch the routes created in onGenerateRoute and apply the same logic to them, so I wouldn't have to create these RouteAware widgets.

**Comment by darshankawar** [comment]
Thanks for the update. Is there a way for you to take a look at [go_router](https://pub.dev/packages/go_router/install) package and see if it serves your need ?
Also, check this issue and see if it helps in your case: https://github.com/flutter/flutter/issues/101386

**Comment by subzero911** [comment]
No, `go_router` is not production-ready yet. It can't deal with nested navigation (there's a prototype https://github.com/flutter/flutter/issues/99126 , but no ETA when it will be released)

**Comment by darshankawar** [comment]
Thanks for the update. I tried the [code sample](https://github.com/flutter/flutter/issues/61341#issuecomment-659525080) mentioned in original issue, with which I get below output:

```
Syncing files to device iPhone 13...
Restarted application in 983ms.
flutter: didPush screen1
flutter: didPush screen2
flutter: didPush screen3
flutter: didPopNext screen2
flutter: didPush screen3
flutter: didPopNext screen2
flutter: didPush screen3
flutter: didPopNext screen2
flutter: didPush screen3
```
The code you shared seems to have third party plugin and custom code, so can't directly use it. Can you provide details based on the code sample shared in linked issue and what's the exact current behavior you are seeing as compared to expected result ?
