### ISSUE TITLE
flutter not updated properly

### ISSUE THREAD

**Issue by Sonubairwa2021** [flutter/flutter#108634]
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

<details>
<summary>Logs</summary>

```
```

```
```

</details>

**Comment by christopherfujino** [comment]
Thank you for filing an issue! However, unfortunately this issue is not currently actionable by our team. Feel free to open a new issue *filling out the template*, including steps to reproduce, relevant logs, and the output of `flutter doctor --verbose`.
