### ISSUE TITLE
[Suggestion / Engine] Improve `Rect` and `RRect` with simple methods

### ISSUE THREAD

**Issue by bernaferrari** [flutter/flutter#108689]
I'm doing many weird things and finding a few Rect / RRect limitations. I can contribute, but I don't know if you **want** them.

First one, I wish the following code were in the engine. `Rect.inflate`, `Rect.deflate`, `RRect.inflate`, `RRect.deflate` are great methods, but they are limited to a single double value applied to every field. I want greater customizability. I think being able to inflate by changing all four corners could be great. I also can't use `_.raw` there :(.

Furthermore, some operators could be nice. Like `rect + rect` and `rect / 2`. I'm not sure if they were ever considered and rejected for a good reason or if no one simply asked for them. I often miss these methods in debugging, even if they are not the most efficient thing ever (by dividing 10 times the same value, for example. Not perfect. But good for writing code, can optimize later).

RRect code:
```dart
  /// Similar to [RRect.inflate] but receives a [Rect].
  RRect inflateWithRect(Rect rect) {
    return RRect.fromLTRBAndCorners(
      left - rect.left,
      top - rect.top,
      right + rect.right,
      bottom + rect.bottom,
      topLeft: tlRadius + Radius.elliptical(rect.left, rect.top),
      topRight: trRadius + Radius.elliptical(rect.right, rect.top),
      bottomRight: brRadius + Radius.elliptical(rect.right, rect.bottom),
      bottomLeft: blRadius + Radius.elliptical(rect.left, rect.bottom),
    );
  }

  /// Similar to [RRect.deflate] but receives a [Rect].
  RRect deflateWithRect(Rect rect) {
    return RRect.fromLTRBAndCorners(
      left + rect.left,
      top + rect.top,
      right - rect.right,
      bottom - rect.bottom,
      topLeft: tlRadius - Radius.elliptical(rect.left, rect.top),
      topRight: trRadius - Radius.elliptical(rect.right, rect.top),
      bottomRight: brRadius - Radius.elliptical(rect.right, rect.bottom),
      bottomLeft: blRadius - Radius.elliptical(rect.left, rect.bottom),
    );
  }
```

Rect code:
```dart
  /// Similar to [Rect.inflate] but receives a [Rect].
  Rect inflateWithRect(Rect rect) {
    return Rect.fromLTRB(
      left - rect.left,
      top - rect.top,
      right + rect.right,
      bottom + rect.bottom,
    );
  }

  /// Similar to [Rect.deflate] but receives a [Rect].
  Rect deflateWithRect(Rect rect) {
    return Rect.fromLTRB(
      left + rect.left,
      top + rect.top,
      right - rect.right,
      bottom - rect.bottom,
    );
  }
```

**Comment by chinmaygarde** [comment]
I'd vote for these extension methods in a separate package.

**Comment by bernaferrari** [comment]
Flutter itself can't have extensions.

**Comment by Hixie** [comment]
inflateWithRect really wants to use EdgeInsets rather than Rect (from a semantic perspective)... and it turns out EdgeInsets already has inflateRect/deflateRect. I wouldn't mind adding inflateRRect et al to EdgeInsets.

Not sure what rect + rect means, or rect / num.

**Comment by bernaferrari** [comment]
Original idea was `Rect(1, 1, 1, 1) + Rect(1, 1, 1, 1) = Rect(2, 2, 2, 2)` or `Rect(2, 2, 2, 2) / 2 = Rect(1, 1, 1, 1)` (would apply a transformation to every value. But that's less necessary 😛. The EdgeInset is also a good idea, I was using Rect because it is simpler, but that would do fine.

**Comment by Hixie** [comment]
If there's specific use cases for `+` and `/` that would be good to study.

**Comment by bernaferrari** [comment]
Good news: EdgeInsets already has '+' operator. I was using Rect, which is barebones. Bad news, the '+ double' idea is also not possible right now because you can't overload an operator twice (yet?).

I made a PR for the RRect.

**Comment by bernaferrari** [comment]
This was never accepted and the code now lives on box_border.dart, where Border calls it.
