### ISSUE TITLE
Feature -> Add support for Live Activities for iOS

### ISSUE THREAD

**Issue by gdelataillade** [flutter/flutter#108609]
## Proposal

Apple recently announced that iOS 16 Live Activities API is now available in beta for developers.
_Source: https://developer.apple.com/news/?id=hi37aek8_

It would be awesome if Flutter could add support for this feature for iOS users.

**Comment by yelkamel** [comment]
That will be awesome ! :D

**Comment by Zazo032** [comment]
It might make more sense to add support for this in a third party library like [flutter_local_notifications](https://pub.dev/packages/flutter_local_notifications)

**Comment by gdelataillade** [comment]
Yea you're right

**Comment by jmagman** [comment]
If you didn't need Flutter in the extension it's pretty trivial to open `ios/Runner.xcworkspace and follow the instructions in https://developer.apple.com/documentation/activitykit/displaying-live-data-on-the-lock-screen-with-live-activities.  

If you do want to use Flutter in the extension embedding it would be similar to https://docs.flutter.dev/development/platform-integration/ios/ios-app-clip.  Not sure if the live activities bundle has a size restriction though.

**Comment by istornz** [comment]
Hello 👋 
I created a plugin to support iOS 16.1+ live activities & iPhone 14 Pro Dynamic Island feature 🙂

[https://pub.dev/packages/live_activities](https://pub.dev/packages/live_activities) 

Any suggestion are welcome to improve this package 📦 !

**Comment by xSILENCEx** [comment]
[live_activities](https://pub.dev/packages/live_activities) has not been updated for a long time
Inspired by @istornz ,I created a more complete plugin: [flutter_live_activities](https://pub.dev/packages/flutter_live_activities)
