### ISSUE TITLE
Why Shortcuts & Actions must need a Focus Widget?

### ISSUE THREAD

**Issue by huanghui1998hhh** [flutter/flutter#108605]
As the title say, **Shortcust** & **Actions** must need a Focus widget's context to work.
I'm facing a case, need a shortcut take effect globally(no widget be focused currently). 
Have there any way to do this?

**Comment by darshankawar** [comment]
Your question is better suited for support channels like StackOverflow, so please ask the same there.
Closing from here, as this is neither bug report or feature request.

**Comment by huanghui1998hhh** [comment]
**Shortcuts** & **Actions** can be used only when some widget be focused. And if i want a global shortcut, i must use platform channels from platform-specific code.
I think this is not reasonable.
So my question is more like a feature request.

**Comment by darshankawar** [comment]
Please check this which shows usage of Focus widget for Shortcuts and Actions: https://docs.flutter.dev/development/ui/advanced/actions_and_shortcuts#why-not-use-callbacks
