### ISSUE TITLE
BackButton and CloseButton with overrideable default icon values

### ISSUE THREAD

**Issue by williamhjcho** [flutter/flutter#108631]
## Use case

Hi, we have a custom set of icons that we would like to have inserted into the Back and Close navigation buttons.

Most of our screens already benefit from the automatically implied AppBar's leading button, instead of manually inserting them on every screen/page.

## Proposal

The simplest and most straightforward solution might just be an overrideable (static/global?) value somewhere that the buttons have access to. 
Still, since it might need to be able to cover more use cases (e.g. different icons per platform or other derived properties like theme/user values), a callback resolver somewhere might be more suitable. Maybe inside `ThemeData` (similar to what we already have for route anim builders)?

**Comment by favechua** [comment]
You can create a custom component extended from `AppBar` which defaulted to a custom icon. Then use it in every page.

**Comment by maheshmnj** [comment]
Hi @williamhjcho, Thanks for filing the issue. @favechua is right you can create your own AppBar  extending from Appbar as below and use it across your app.

```dart
import 'package:flutter/material.dart';

class CustomAppBar extends StatelessWidget with PreferredSizeWidget {
  final String _title;

  @override
  final Size preferredSize;

  CustomAppBar(this._title, { Key? key}) : preferredSize = Size.fromHeight(50.0),
        super(key: key);

  @override
  Widget build(BuildContext context) {
    return AppBar( // your customization here
      title: Text('$_title'),
      centerTitle: true,
      backgroundColor: Colors.black54,
    );
  }
}

// on the file using the appBar just: 

class NewScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: CustomAppBar('Your title here'),
    );
  }
}
```
Closing as it is neither a bug nor a new feature request

**Comment by williamhjcho** [comment]
Hi @maheshmnj , 

The main proposal of this issue was to just extend the existing functionality of `BackButton` and `CloseButton`.
As opposed to create an extra widget, which would require me to replace it everywhere on the app `AppBar/SliverAppBar -> MyCustomAppBar/MyCustomSliverAppBar`.
