### ISSUE TITLE
[go_router] Access to fragment(`/#access_token=bla_bla_bla`) in router `state`

### ISSUE THREAD

**Issue by vasilich6107** [flutter/flutter#108614]
## Use case

I'm using Amazon Cognito auth and it sends token in redirect URL as `/#access_token=bla_bla_bla`
On v4.1 it worked well for me and I was able to access to this fragment in `state.location`.

On v4.2 there is no more fragment in `state.location`.

## Proposal
Could you expose fragment(`#access_token=bla_bla_bla`) the same way as you do with `state.params`?

**Comment by chunhtai** [comment]
Is this a regression that it worked on 4.1?

also can you provide a minimum repro code?

**Comment by chunhtai** [comment]
It looks like the fragment is dropped somewhere in the parsing pipeline
`_addQueryParams` in match.dart should also append the fragment.

**Comment by SheriefAlaa** [comment]
I can reproduce on version 5.1.5. Flutter 3.3.5.

**Comment by rlee1990** [comment]
Any update on this?

**Comment by chunhtai** [comment]
yes this looks correct, although I am not the owner of that part of the code. feel free to open a pr and pin me on it, I can help redirect to the right person

**Comment by yjbanov** [comment]
Assigned to @vasilich6107 and @chunhtai who are actively working on the PR.

**Comment by chunhtai** [comment]
should be fixed by https://github.com/flutter/flutter/pull/131123
