### ISSUE TITLE
Cocoon is using TOT commit to trigger github presubmit targets from default branches

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#108645]
Cocoon is using TOT commit to trigger github presubmit targets from default branches. This caused inconsistent configs in pre-submit validation, compared to changes in the working PR.

Seems it was switched to use TOT commit for default branches in https://github.com/flutter/cocoon/commit/ac8236da60845e48791842a2997238cfc6e6a32c#diff-fd76e43f9b3d0214f9e948d7a30442aef85a728d31e65b696113d6270bb3d1b6.

/cc @XilaiZhang Do you have any context for such change?

/cc @hellohuanlin Related to why your PR didn't pick the newly enabled target.

**Comment by CaseyHillers** [comment]
@keyonghan can you give me the expected result? It's not clear to me what went wrong with https://github.com/flutter/flutter/pull/108642

I created https://github.com/flutter/cocoon/pull/2036/commits/1eb36af3d14135f347a23d2c462d3901141838d3

which triggered the expected presubmit build of https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20Cocoon/2414/overview with the property "hello": "world"

**Comment by keyonghan** [comment]
IIRC, the issue is when we toggle an existing target from `bringup: false` to `bringup: true`, the target was not triggered in pre-submit checks.

**Comment by CaseyHillers** [comment]
I created https://github.com/flutter/cocoon/pull/2036/commits/e0cb081bfd9f7c5411ad5125e793d152d7c28cf0 and didn't get a Linux Cocoon check due to it being marked bringup.

**Comment by keyonghan** [comment]
Ah, my bad, I guess the issue is when switching `presubmit: false` to `presubmit: true` where the target was not triggered.

**Comment by CaseyHillers** [comment]
In the case of https://github.com/flutter/flutter/pull/108642 - It also had bringup: true, which isn't expected to run in presubmit.

Or is the force push on that PR hiding the actual issue?

**Comment by keyonghan** [comment]
> In the case of https://github.com/flutter/flutter/pull/108642 - It also had bringup: true, which isn't expected to run in presubmit.

That makes sense then. I believe the target will be triggered when it is with `bringup: false` and newly switched to `presubmit: true` in the PR? If so, this is WAI and we can close the bug.
