### ISSUE TITLE
Option to have a tappable TextButton in a Tooltip

### ISSUE THREAD

**Issue by leocape** [flutter/flutter#108604]
## Use case

Often it is useful for the `Tooltip` to display a summary that includes a `TextButton` which links to an external article / webpage with more in depth information. Currently it does not appear possible for the `TextButton` to capture gestures, as any taps on the `Tooltip` itself (including tapping on the `TextButton`) will close the `Tooltip`, and not execute the `onPressed` of the `TextButton`.

(Attempting to manually capture the gestures by wrapping the `ToolTip` in a `GestureDetector` and using a `GlobalKey` also does not seem to capture the `TextButton` `onPressed`, and closes the `Tooltip`.)

Example of what is tried and expected:

```
Tooltip(
  preferBelow: false,
  padding: EdgeInsets.all(12.0),
  showDuration: Duration(
    seconds: 10,
  ),
  richMessage: TextSpan(
    text: "This is a summary.... ",
    children: <InlineSpan>[
      WidgetSpan(
          alignment: PlaceholderAlignment.baseline,
          baseline: TextBaseline.alphabetic,
          child: TextButton(
            child: Text(
              'LEARN MORE',
              style: TextStyle(color: Colors.blue),
            ),
            onPressed: (() {
              bloc.launchURL(
                LaunchLink.moreInfo,
              );
            },
          ),
        ),
      ),
    ],
  ),
  triggerMode: TooltipTriggerMode.onTap,
  child: Icon(
    Icons.info_rounded,
    color: Color(AppColors.blue),
    size: 18,
  ),
),

```
## Proposal

Prioritise the tap on the `TextButton` over the tap of the `Tooltip`, perhaps this would mean the introduction of a `Tooltip Controller` - although it seems like overkill for this use case.

**Comment by darshankawar** [comment]
@leocape 
Having a textbutton in a tooltip would go against the material design of Flutter. You may go through this document to know more about it from material design perspective: https://material.io/components/tooltips/flutter#using-tooltips

Also, you seem to have found a workaround already: https://stackoverflow.com/questions/73156129/add-text-button-to-tooltip-flutter

Closing from here, as the proposal doesn't seem to be feasible. If you disagree, write in comments and I'll reopen it.
