### ISSUE TITLE
Render Box Log requested bug report bc nto enough info given by flutter in log.

### ISSUE THREAD

**Issue by neiljaywarner** [flutter/flutter#108628]
RenderBox was not laid out: RenderRepaintBoundary#81ec0 relayoutBoundary=up21 NEEDS-PAINT
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1979 pos 12: 'hasSize'

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md
The relevant error-causing widget was: 
  Column Column:file:///Users/neil.warner/dev/ri_driver/lib/main.dart:57:14
When the exception was thrown, this was the stack: 
#2      RenderBox.size (package:flutter/src/rendering/box.dart:1979:12)
#3      ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:57:18)
#4      RenderFlex._computeSizes (package:flutter/src/rendering/flex.dart:829:43)
#5      RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:931:32)
#6      RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#7      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#8      RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#9      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#10     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#11     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#12     RenderCustomPaint.performLayout (package:flutter/src/rendering/custom_paint.dart:545:11)
#13     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#14     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#15     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1376:11)
#16     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#17     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:233:12)
#18     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#19     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#20     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#21     ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:56:11)
#22     RenderFlex._computeSizes (package:flutter/src/rendering/flex.dart:829:43)
#23     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:931:32)
#24     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#25     ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:56:11)
#26     RenderFlex._computeSizes (package:flutter/src/rendering/flex.dart:829:43)
#27     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:931:32)
#28     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#29     _RenderSingleChildViewport.performLayout (package:flutter/src/widgets/single_child_scroll_view.dart:513:14)
#30     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#31     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#32     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#33     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#34     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#35     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#36     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#37     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#38     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#39     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#40     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#41     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#42     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#43     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#44     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#45     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#46     RenderCustomPaint.performLayout (package:flutter/src/rendering/custom_paint.dart:545:11)
#47     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#48     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#49     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#50     RenderPositionedBox.performLayout (package:flutter/src/rendering/shifted_box.dart:437:14)
#51     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#52     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:171:12)
#53     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:1003:7)
#54     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:240:7)
#55     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:403:14)
#56     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1757:7)
#57     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:887:18)
#58     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:504:19)
#59     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:892:13)
#60     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:370:5)
#61     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1146:15)
#62     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1083:9)
#63     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:997:5)
#67     _invoke (dart:ui/hooks.dart:151:10)
#68     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308:5)
#69     _drawFrame (dart:ui/hooks.dart:115:31)

**Comment by huycozy** [comment]
Hi @neiljaywarner, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this. Also, please provide the output of `flutter doctor -v` as well.
Thank you!
