### ISSUE TITLE
Bottomnavigationbar height according to icon size

### ISSUE THREAD

**Issue by naveenpardeep** [flutter/flutter#108612]
I want to suggest new improvement in Flutter in bottomnavigationbar's height we can set according to icon height ..now its taking more space .

Thank You

**Comment by darshankawar** [comment]
@naveenpardeep 
You can customize height of it. See this SO link and underlying solutions for your reference and see if it works for you: https://stackoverflow.com/questions/53758698/flutter-dart-customize-bottom-navigation-bar-height

Also, setting the height according to icon seem to go against the material design. Check this document for your reference: https://stackoverflow.com/questions/53758698/flutter-dart-customize-bottom-navigation-bar-height

Closing.

**Comment by naveenpardeep** [comment]
yeah we can edit height using Sizedbox but i want according to icon's height which i did not find any where
