### ISSUE TITLE
flutter-dashboard datastore - cannot opened error

### ISSUE THREAD

**Issue by imhunterand** [flutter/flutter#108616]
The dashboard at google cloud its cannot opened, 
```
Project  flutter-dashboard
appengine.applications.get
```
I have see read **Adding a contributor to Flutter Dashboard**

can you please invite my github for contributor at @flutter repository
Im a security research (OSCP/OSEP)

[linked.com/in/andrimuda](https://www.linkedin.com/in/andrimuda/)
[hackerone/user/semprul_edan](https://hackerone.com/semprul_edan)

Regards,

**Comment by huycozy** [comment]
Hi @imhunterand, thanks for filing the issue
Could you please provide detailed reproduction steps?
And please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example), the output of `flutter doctor -v` so that we may verify this.
Thank you!

**Comment by imhunterand** [comment]
**Hi!** @huycozy 

There is result errors 👍 
![image](https://user-images.githubusercontent.com/109766416/182112492-25881c92-0a94-4c92-b692-f48d2e9da278.png)

```
There was an error while loading [/datastore/entities;kind=AllowedAccount;ns=__$DEFAULT$__/query/kind?project=flutter-dashboard](https://console.cloud.google.com/datastore/entities%3Bkind%3DAllowedAccount%3Bns%3D__$DEFAULT$__/query/kind%3Fproject%3Dflutter-dashboard).
```

**Comment by huycozy** [comment]
Hi @imhunterand 
This issue doesn't seem to describe a bug or a feature request. As this is mentioned in [Access rights to Flutter dashboard](https://github.com/flutter/flutter/wiki/Contributor-access#access-rights-to-flutter-dashboard):

>The [Flutter dashboard](https://flutter-dashboard.appspot.com/) shows what recently landed and what tests passed or failed with those commits. To see rerun tasks, you need to be added to an allowlist. Anyone with commit access is eligible to be added to that allowlist, but only certain team members have the permissions required to update the backend database where the permissions are stored. To get access, ask on #hackers-infra to be added to the allowlist.

Please [join Discord channel](https://github.com/flutter/flutter/wiki/Chat) to ask for this request. 

Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it. Thank you!
