### ISSUE TITLE
Remove goma dependency from secured builds recipe

### ISSUE THREAD

**Issue by yusuf-goog** [flutter/flutter#108760]
go/dircl/3260 is the original change to run recipes in secured build env.

A build from it is here: 

https://ci.chromium.org/ui/p/dart-internal/builders/flutter/Linux%20Framework%20Smoke%20Tests/1/overview

We need to remove the goma references from the recipe, since those are not allowed to be run in the secure env.

**Comment by yusuf-goog** [comment]
@godofredoc here are some details on the recipe that needs goma removed. Please let me know if you need anything else.

**Comment by godofredoc** [comment]
Landed on https://flutter-review.googlesource.com/c/recipes/+/32841
