### ISSUE TITLE
Scrollable.of returns null for a child of a ScrollableViewport

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#1087]

**Comment by Hixie** [comment]
The problem is that `Scrollable.of` does a `runtimeType` check for `ScrollableState` rather than an `is` check.

As a workaround for now, instead of doing `Scrollable.of(context)`, do `context.ancestorStateOfType(ScrollableViewportState)`.

**Comment by Hixie** [comment]
This also breaks `Scrollable.ensureVisible`; that one has no good workaround.
