### ISSUE TITLE
Type in API docs for ImageProvider

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#10876]
In ImageProvider: https://docs.flutter.io/flutter/services/ImageProvider-class.html docs we have this line:

"(It is essentially a bare-bones version of the Image widget.)"

The word "Image" is linked over to dart:ui's Image. I think we meant to link over to the widget library's Image?

**Comment by Hixie** [comment]
oops!

**Comment by Hixie** [comment]
https://github.com/flutter/flutter/pull/10904 tries to fix this. We won't know until we re-enable docs uploads.
