### ISSUE TITLE
Request for API docs for Image.asset constructor (what is asset name?)

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#10875]
When reading https://docs.flutter.io/flutter/widgets/Image/Image.asset.html I was left with the question "what does the `name` mean or expect to be" ?

Does the `name` argument intend to be the exact matching path as declared in the asset bundle, which is declared in the pubspec.yaml ?

Assume I have this in my pubspec.yaml:

```
  assets:
    - assets/kitten1.jpg
```

What do I pass to the `name` argument of `new Image.asset(_____)` ?

**Comment by Hixie** [comment]
https://github.com/flutter/flutter/pull/10904

**Comment by sethladd** [comment]
Thanks!
