### ISSUE TITLE
Regression: ListView.builder's itemBuilder can no-longer return null since NNBD migration

### ISSUE THREAD

**Issue by rrousselGit** [flutter/flutter#108705]
It's a bit late to the party, since NNBD migration was done a long time ago.

But it seems that the migration process broke  ListView.builder's itemBuilder ability to return null;

## Steps to Reproduce

We used to be able to write the following:

```dart
ListView.builder(
  // no item count
  itemBuilder: (context, index) {
    if (condition) return null;
    return Item();
  }
)
```

**Expected results:**

Before NNBD migration, this code would render `Item()` until `condition` is true, at which point the list ends (similar to as it we reached the end of `itemCount`)

**Actual results:**

The code doesn't compile as `itemBuilder` doesn't allow returning `null` anymore.

___

Browsing through the git blames, it seems that this was removed by mistake.   
It probably didn't have a test and slipped through the review process because of the NNBD migration of `IndexedItemBuilder`. 

This issue https://github.com/flutter/flutter/issues/58371#issuecomment-638493007 in particular shows that returning null was a supported behavior.

Similarly, `SliverChildBuilderDelegate.build` (the delegate that implements `ListView.builder`) still allows returning `null`.
So returning `null` is still technically supported, just not with the `.builder` constructor

**Comment by bernaferrari** [comment]
I usually do `if (condition) return SizedBox()` but I guess that's fine too.. lol

**Comment by rrousselGit** [comment]
> I usually do `if (condition) return SizedBox()` but I guess that's fine too. lol

A `SizedBox` doesn't stop the list.  
Returning `null` is meant to behave as if the user reached the end. So we have the bouncing physics & co

In that sense, `null` inside `ListView.children` doesn't make sense

**Comment by maheshmnj** [comment]
Hi @rrousselGit, Thanks for filing the issue. I did verify on the latest stable and the master channel the below code wouldn't compile when returning null, looks like, with the current implementation, itemBuilder cannot be null.  Looking at the comment https://github.com/flutter/flutter/issues/58371#issuecomment-638493007 it is evident that this was supported in the past.


<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Material(
        child: ListView.builder(
            // no item count
            itemBuilder: (context, index) {
          if (index == 5) return null;
          return ListTile(
            title: Text('Item $index'),
          );
        }),
      ),
    );
  }
}

```
</details> 

<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.4 21F79 darwin-arm, locale en-IN)
    • Flutter version 3.0.5 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (5 days ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-32, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.67.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.44.0

[✓] Connected device (3 available)
    • sdk gphone arm64 (mobile) • emulator-5554 • android-arm64  • Android 11 (API 30) (emulator)
    • macOS (desktop)           • macos         • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)              • chrome        • web-javascript • Google Chrome 103.0.5060.114

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

```
[✓] Flutter (Channel master, 3.1.0-0.0.pre.1868, on macOS 12.4 21F79 darwin-arm, locale en-IN)
    • Flutter version 3.1.0-0.0.pre.1868 on channel master at /Users/mahesh/Documents/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 925bee92e7 (6 days ago), 2022-07-26 04:49:06 -0400
    • Engine revision 5dcaeae656
    • Dart version 2.19.0 (build 2.19.0-34.0.dev)
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-32, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13C100
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.69.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.44.0

[✓] Connected device (3 available)
    • sdk gphone arm64 (mobile) • emulator-5554 • android-arm64  • Android 11 (API 30) (emulator)
    • macOS (desktop)           • macos         • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)              • chrome        • web-javascript • Google Chrome 103.0.5060.134

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

cc: @goderbauer 

ps: TIL ListView.builder could be stopped by returning null

**Comment by goderbauer** [comment]
Looks like this was an oversight during the null safety migration and the `itemBuilder` of `ListView.builder` should have been typed `NullableIndexedWidgetBuilder` instead of `IndexedWidgetBuilder`. The `IndexedWidgetBuilder` is also used for some other scrollables. We should audit those instances as well to see if they should be changed to a `NullableIndexedWidgetBuilder` as well.

/cc @Piinks

**Comment by Piinks** [comment]
I think I remember chatting with someone about this a while back. If you use the SliverChildBuilderDelegate directly, you can return null from the builder. I don't recall who I was chatting with, but they suggested it was intentional to not allow for returning null in the higher level class, while allowing it in the lower level class where folks have more control over the configuration of their list.

I do know that returning null can cause headaches or confusion for folks that rely on the scroll metrics to be accurate. In the case of returning null, the scroll metrics are only accurate when you have reached the end of the list and actually returned null to signal the end. Maybe that was part of the motivation...

**Comment by Piinks** [comment]
I am not sure I follow, returning null would indicate the end of the list. How would it affect infinite list views?

**Comment by rrousselGit** [comment]
The problem with scroll metrics applies to infinite lists too

Infinite lists could also have an item count: The number of items currently fetched.
This number will keep growing as the user scrolls down, but an itemCount could possibly obtained for infinite lists

**Comment by Piinks** [comment]
I am not sure I follow.

It looks like this is explicitly mentioned in the documentation, and the pattern is consistent, as GridView.builder also does not allow returning null.

**Comment by Piinks** [comment]
This was migrated to NNBD in https://github.com/flutter/flutter/pull/65528, looking at the diff it still looks very intentional.

**Comment by rrousselGit** [comment]
I would argue that GridView.builder has the same problem, and some more too, like ListView.separated.


I think the root of the potential migration issue stems from how the related doc issue (https://github.com/flutter/flutter/issues/58371) was resolved.

My understanding of https://github.com/flutter/flutter/issues/58371 is that the expected resolution was to instead say: "After a null item is returned, the list will stop, independently of itemCount".  Yet the doc change instead was updated to say "never return null".
This doc mistake likely triggered an incorrect NNBD migration, by following the doc.


The doc saying "never use null" does not make sense to me. @goderbauer 's comment in https://github.com/flutter/flutter/issues/58371 clearly refers to how returning `null` is an officially supported behavior.


I think the source code is a testimony of that. It is explicit in supporting null. I've mentioned `SliverChildBuilderDelegate.build` before, but I think `ListView.separated`  also has some good clues. If we look at its source, we have:

```dart
           Widget widget;
           if (index.isEven) {
             widget = itemBuilder(context, itemIndex);
           } else {
             widget = separatorBuilder(context, itemIndex);
             assert(() {
               if (widget == null) { // ignore: dead_code
                 throw FlutterError('separatorBuilder cannot return null.');
               }
               return true;
             }());
           }
           return widget;
```

This code purposefully asserts that separators must not be `null`. But it doesn't do that for `itemBuilder`.  
This implies that `separatorBuilder` is an `IndexedWidgetBuilder` but `itemBuilder` is a `NullableIndexedWidgetBuilder`.

____


Alternatively, if the decision is to ban `itemBuilder` from returning `null`, then I think an assert should be added, like with `separatorBuilder`.

Code that opts out of null-safety could still return `null`. And this fallbacks to the behavior of `SliverChildBuilderDelegate.build`, which officially supports `null`.

**Comment by Piinks** [comment]
> I would argue that GridView.builder has the same problem

Not looking to argue, merely looking to understand. Examining past changes and motivations is generally how we approach something that has been reported as a regression. I appreciate your patience and work looking into this. 

Regarding your PR, if we are to fix this, we would want to address all of the cases where this is incorrect, rather than one individual class. If there is an established pattern in the framework that is wrong, we should correct it fully to avoid it being in an inconsistent state.

**Comment by rrousselGit** [comment]
No problem! Should I update the PR to update GridView and possible other cases then?

In the end, I fully recognize that my interpretation could be wrong. You and goderbauer have directly interacted with the source issues, so I'll trust whatever you decide.

And since no one complained in that long, I guess officially removing the feature is an alternate solution.  
What triggered this issue is that I was about to promote this feature as I have a use case for it. But there's the workaround of `ListView.custom` as you mentioned. 

So I don't mind either way :smile:

**Comment by Piinks** [comment]
> Should I update the PR to update GridView and possible other cases then?

Sure! We. should check every case of `IndexedItemBuilder` to see if there are others that need to be fixed as well.

**Comment by rrousselGit** [comment]
I think there's PageView.builder.

From my search, there's also custom List types (AnimatedList, ReorderableListView + sliver variant).
But I'm not sure either of these supported it before

**Comment by Piinks** [comment]
> But I'm not sure either of these supported it before

They all did in a non-null-safe world. 😜  I guess the question would be - is being able to return null helpful or applicable in some use cases? Think of your own case that motivated this issue report. If it were an animated list, would you feel the same way?

**Comment by rrousselGit** [comment]
> They all did in a non-null-safe world.

ReorderableListView throws a null exception in a non-null-safe world 😛 

I'm not sure about AnimatedList. Returning null is supposed to signify the end of the list. But the way AnimatedList works, it injects widgets after `itemBuilder` executes.  
So if AnimatedList.itemBuilder returns null, this could cause a bug where items imperatively pushed in the list (through `AnimatedListState.insertItem`) would not be rendered

**Comment by rrousselGit** [comment]
AnimatedList also has a default itemCount (0). Not specifying initialItemCout doesn't render an infinite list. Instead, it renders an empty list.

**Comment by Piinks** [comment]
TIL! 😜
