### ISSUE TITLE
RFC 9266: Channel Bindings for TLS 1.3 support

### ISSUE THREAD

**Issue by Neustradamus** [flutter/flutter#108748]
Can you add the support of RFC 9266: Channel Bindings for TLS 1.3?
- https://datatracker.ietf.org/doc/html/rfc9266

Little details, to know easily:
- tls-unique for TLS =< 1.2
- tls-exporter for TLS = 1.3

Thanks in advance.

**Comment by maheshmnj** [comment]
Hi @Neustradamus, Thanks for filing the issue. Labeling for further insights from the team.

cc:   @chinmaygarde

**Comment by zanderso** [comment]
cc @brianquinlan @a-siva Should we move this to the dart-sdk issue tracker?

**Comment by a-siva** [comment]
Yes, we should move it. Looks like 'Transfer Issue' will not work in this case, we may have to add a new Dart issue anf close this.

**Comment by Neustradamus** [comment]
Hello @maheshmnj, @chinmaygarde, @zanderso, @brianquinlan, @a-siva,

Thanks for your comments, I have already published an issue here:
- https://github.com/dart-lang/sdk/issues/49581

**Comment by maheshmnj** [comment]
Closing since this is being tracked under dartlang/sdk https://github.com/dart-lang/sdk/issues/49581

**Comment by Neustradamus** [comment]
@PapaTutuWawa: I have done ticket here, do not hesitated to explain your problem.

Linked to:
- https://github.com/PapaTutuWawa/moxxyv2/issues/13
