### ISSUE TITLE
[image_picker][iOS] Exception is thrown when picking image on simulator

### ISSUE THREAD

**Issue by Kiruel** [flutter/flutter#108724]
This issue is still a problem => https://github.com/flutter/flutter/issues/70436 on Apple M1 Max.

flutter doctor:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 3.1.0-0.0.pre.1834, on macOS 12.4 21F79 darwin-arm, locale en-FR)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.69.2)
[✓] Connected device (5 available)
[✓] HTTP Host Availability

• No issues found!
```

**Comment by huycozy** [comment]
Hi @Kiruel, thanks for filing the issue.
Please provide the information indicated below:
- Which `image_picker` version are you using?
- Affected device information (iOS model, version)
- A [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
- Reproduction steps

**Comment by Matsuo32** [comment]
Hi @Kiruel   For developing on apple silicon (M1), you needed to remove the google_maps plugin. This plugin moves the simulator to Rosetta and this has some issues with image handling in the simulator.
