### ISSUE TITLE
Getting Started guide should explain pubspec.yaml uses-material-design option better

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#10878]
From https://github.com/flutter/flutter/issues/10827:
>We were under the impression that it meant that the uses-material-design option meant that it wouldn't load the icon font (and other dependent resources, essentially) and we were using it with the intention to save space because we weren't using the Icon class at all. We still wanted to use the other classes though. So, [we set "uses-material-design: false" because we wanted to not incur any app size costs associated with using material in the form of icon fonts].
>
> In hindsight, it makes perfect sense that other things in the material package depend on that font/flag being set to true and that setting the flag to false wont actually stop you from using material, but just disable the specifics of the platform if you choose not to use it.

> Ideally that would explain that if you want to use the material package then you should set that value to true. If you don't want to use it, set it to false. I think we read too much into that flag ultimately.
>
> If that flag is meant to represent "use material, but not the icon font" then the package should work without the font in my opinion. If it is a flag that specifies the intent to never use material, then it works :)

**Comment by sethladd** [comment]
Do we also need to update the comments in the pubspec.yaml template that is used to generate the starter template?

**Comment by willlarche** [comment]
So, does the Material package work without the font? I actually don't know.

**Comment by Hixie** [comment]
The icons will be broken, but it'll "work" other than that.

**Comment by Sfshaza** [comment]
@Hixie, say you set uses-material-deign to true, but don't use the icon font in your code. When you build a release version of the app, would tree shaking remove the icon font?

**Comment by Hixie** [comment]
No.

**Comment by Sfshaza** [comment]
It was worth a shot, @Hixie.  ;)

**Comment by zoechi** [comment]
Issue moved to [flutter/website #1984](https://github.com/flutter/website/issues/1984) via [**ZenHub**](https://www.zenhub.com/)
