### ISSUE TITLE
A error in the text of the last step of the "Write Your First Flutter App, part 2" collab

### ISSUE THREAD

**Issue by cverdes** [flutter/flutter#108709]
In [the page of the last step](https://codelabs.developers.google.com/codelabs/first-flutter-app-pt2#8) of the codelab "Write Your First Flutter App, part 2", with the title "Next steps", it says "Now that you've written your first app, dive deeper into Flutter by creating a simple chat application in our Building beautiful UIs with Flutter codelab", but the link doesn´t point to a chat application. It [links to a codelab](https://codelabs.developers.google.com/codelabs/flutter-boring-to-beautiful#0) that teach the main screen of an app called MyArtist, a music player where fans can keep up with their favorite artists.

**Comment by danagbemava-nc** [comment]
That codelab has been sunset, see https://github.com/flutter/website/issues/6783#issuecomment-1138853049. 

We should update the text to reflect the change. 

/cc @domesticmouse

**Comment by domesticmouse** [comment]
Googlers: cl/465740456

**Comment by domesticmouse** [comment]
Updated to "Now that you've written your first app, dive deeper into Flutter by creating a simple chat application in our [Take your Flutter app from boring to beautiful](https://codelabs.developers.google.com/codelabs/flutter-boring-to-beautiful) codelab."
