### ISSUE TITLE
[plugins][quick_actions] Swift migration for quick_actions plugin

### ISSUE THREAD

**Issue by hellohuanlin** [flutter/flutter#108750]
This is to track the work of Swift migration for quick_actions plugin. This plugin is chosen to be the first plugin for Swift migration, because: 
- It's relatively smaller, but not too small
- It has good UI test coverage. Good candidate to showcase ui test in swift. 
- It has 0% unit tests coverage. Good candidate to showcase how to backfill unit tests
- Needs to refactor a few internal states for unit tests. Good candidate to showcase pre-migration refactoring. 

## Proposal

https://docs.google.com/document/d/1XsaulkJA6_ZSpM7chkQLhQY25sQqhEMiqHMYzw8H85o/edit?resourcekey=0-_cUjF1c0iBvRLKfV-3gK5A#

**Comment by jmagman** [comment]
@hellohuanlin what is left to do here?

**Comment by hellohuanlin** [comment]
@jmagman I think it's all complete. I'm closing this issue. 

As a follow up I will (1) write up a short community contribution guide in the wiki (2) maybe work on adding swift formatter support on the CI. 

CC @stuartmorgan
