### ISSUE TITLE
flutter-win-6 bot dead possibly from wrong java version found during testing.

### ISSUE THREAD

**Issue by ricardoamador** [flutter/flutter#108775]
flutter-win-6 is showing as dead for the last two weeks.

**Comment by ricardoamador** [comment]
The last test that ran was looking for java version 11 but it only found java 1.8. 
https://luci-milo.appspot.com/ui/p/flutter/builders/staging/Windows_staging%20basic_material_app_win__compile/3069/overview
Looking into why this would have killed the bot.

**Comment by keyonghan** [comment]
Windows bots occasionally hit auth issues. Marking as dup of https://github.com/flutter/flutter/issues/107872.

**Comment by ricardoamador** [comment]
Are you sure? I only saw java related issues in the error output.

**Comment by keyonghan** [comment]
Marking as dup based on the title...
Let's rename the tile to reflect the issue then. Reopen.

**Comment by yusuf-goog** [comment]
win-6 was recovered last week, and is currently up.
