### ISSUE TITLE
[image_picker] Security Issue - release version microphone always listening in background

### ISSUE THREAD

**Issue by ollydixon** [flutter/flutter#108796]
Flutter 3.0.5
image_picker: ^0.8.5+3

When pushing the release version of the app a few of our clients noticed over the years that the microphone is 'always listening' on both Android and iOS.

This only seems to happen on the release version of the app and not the debug version. It made some of our clients highly suspicious of our Flutter apps.

You can tell if an app is listening in the background when it has a dot next to the name on the home screen.

<img width="689" alt="Screenshot 2022-08-02 at 11 25 00" src="https://user-images.githubusercontent.com/6940726/182341116-1f8419c4-d9a2-40fd-b44d-179a9113e151.png">

![dot](https://user-images.githubusercontent.com/6940726/182341314-cfe224a1-5632-4839-a753-5de48288ebe5.jpg)

This really isn't great for Flutter apps..

**Comment by julianbraasch** [comment]
A dot next to an app icon indicates that it has recently been installed through Testflight (orange/red) or that it has been recently updated (blue). The indictors for camera/microphone access appear in the status bar at the top, next to the cell reception state.

**Comment by huycozy** [comment]
Hi @ollydixon 
Please make sure that there is no other package using microphone than `image_picker` itself. And please provide the content of `pubspec.yaml`.

>When pushing the release version of the app a few of our clients noticed over the years that the microphone is 'always listening' on both Android and iOS.

What signs indicate this?

From my side, I tried running `image_picker` [sample code](https://github.com/flutter/plugins/tree/main/packages/image_picker/image_picker/example) (release mode) on Pixel 3a (Android 12) and iPhone 7 (iOS 15.5), but the camera/microphone indicator is only shown when recording the video. 

<details>
<summary>Demo</summary>

| Android | iOS |
| --------------- | --------------- |
<video src="https://user-images.githubusercontent.com/104349824/182532725-8b94879e-b858-4f49-ac6d-296de6ab8478.mp4"/> | <video src="https://user-images.githubusercontent.com/104349824/182532752-c33f1e34-daba-4a72-b0e1-339e6d078f77.mp4"/>


</details>

**Comment by ollydixon** [comment]
@huycozy there are no other packages

@julianbraasch do you have a link to the docs for this?

**Comment by julianbraasch** [comment]
@ollydixon [official docs regarding the status bar icons](https://support.apple.com/en-us/HT211876).
I could not find anything from Apple regarding the dots next to the app name, but FWIW [here's a discussion from StackOverflow](https://stackoverflow.com/questions/25843856/red-dot-circle-next-to-the-app-name-below-the-app-icon-on-the-iphone-home-scre)

**Comment by ollydixon** [comment]
@julianbraasch thanks for clearing this up, this looks like the issue. The docs on Apple are not clear on where the dot will be.

@huycozy thanks for trying to help :-)
