### ISSUE TITLE
Using additional information to have a better partial repaint performance.

### ISSUE THREAD

**Issue by endless7** [flutter/flutter#108715]
In the current pipeline, operations are saved in a linear way in the DisplayList. And when we diff the new DisplayList and the old one, we just did a linear comparison. 
Reorganize the operations into a tree. To make the linear comparison a tree-like structure comparison. When we get the diff result, we can compute the bounds of different operations. Finally we just repaint the bounds of the differentiation part.   
So I introduced a new concept in DisplayList/DisplayListLayer – “Virtual Layer”, a node in the tree is a virtual layer.

**Comment by endless7** [comment]
Here is a detailed doc. https://docs.google.com/document/d/11ayzXfN1gQgZPVJUNr8n9hqU_7GKA55dUhtF_cuiLUY/edit#

**Comment by ds84182** [comment]
If non-composited RenderObjects each had their own leaf Picture could that accomplish the same goal here? Then the leaf DisplayListLayer is composed of a bunch of (not nested) drawPicture calls, where some pictures are identical to the previous frame, and some pictures have been updated.

**Comment by endless7** [comment]
cc @knopp

**Comment by endless7** [comment]
> 

Sounds like every RenderObject will be given a repaintBoundary, or every RenderObject will correspond to a displayList ?

**Comment by endless7** [comment]
> If non-composited RenderObjects each had their own leaf Picture could that accomplish the same goal here? Then the leaf DisplayListLayer is composed of a bunch of (not nested) drawPicture calls, where some pictures are identical to the previous frame, and some pictures have been updated.

Sounds like every RenderObject will be given a repaintBoundary, or every RenderObject will correspond to a displayList ?

**Comment by ds84182** [comment]
@endless7 Every render object (that opts in) would have an independent display list. Kinda like a RepaintBoundary, but without using layers.  For render objects that opt in, maybe only layout related ones (so RenderFlex, RenderStack, etc).

Would be worth measuring the overhead of using drawPicture with a prerecorded display list.

**Comment by jonahwilliams** [comment]
We did not accept this proposal.
