### ISSUE TITLE
Unable to write files in local directory

### ISSUE THREAD

**Issue by k1ran-ak** [flutter/flutter#108733]
I'm trying to write a file in custom path like (Whatsapp has its own folder in android internal storage) 
## Steps to Reproduce

```
static Future<String> saveImageLocally(String imageUrl, String path) async {
    if (await requestPermission(Permission.storage)) {
      var response = await http.get(Uri.parse(imageUrl));
      String directory = (await getExternalStorageDirectory())!.path;
      String newPath = "";
      List<String> paths = directory.split("/");
      for (int x = 1; x < paths.length; x++) {
        String folder = paths[x];
        if (folder != "Android") {
          newPath += "/" + folder;
        } else {
          break;
        }
      }
      newPath = newPath + "/Tralien";
      if (await direc.exists() != true) {
        direc.createSync(recursive: true);
      }
      File filePath = File(
          "$direc/${DateTime.now().millisecondsSinceEpoch.toString()}.jpeg");
      filePath.writeAsBytes(response.bodyBytes, flush: true);
      print(filePath.path);
      return filePath.path;
    }
    return "";
  }
```
Error I got was  [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: FileSystemException: Creation failed, path = '/storage/emulated/0/Tralien' (OS Error: Operation not permitted, errno = 1)

flutter doctor -v
[flutter] flutter doctor -v
[✓] Flutter (Channel stable, 2.10.5, on macOS 12.4 21F79 darwin-x64, locale en-GB)
    • Flutter version 2.10.5 at /Users/mac/developement/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (4 months ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc1)
    • Android SDK at /Users/mac/Library/Android/sdk
    • Platform android-32, build-tools 33.0.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3
[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      :hammer: https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      :hammer: https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
[✓] VS Code (version 1.65.2)
    • VS Code at /Users/mac/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0
[✓] Connected device (3 available)
    • HD1901 (mobile)             • 14fb2e9e      • android-arm64  • Android 11 (API 30)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 101.0.4951.54
    ! Error: iPhone is not connected. Xcode will continue when iPhone is connected. (code -13)
[✓] HTTP Host Availability
    • All required HTTP hosts are available
• No issues found!
exit code 0

**Comment by augustt0** [comment]
Hi there! I'd recommend you to upgrade your flutter version as a first thing to do.
You can upgrade flutter by running `flutter upgrade`.

Also, to create a path when this does not exist you can use

```
import 'dart:io';
import 'package:path_provider/path_provider.dart';

void createFileRecursively(String folder, String imageUrl) async {
  var response = await http.get(Uri.parse(imageUrl)); // Get the image

  Directory? tempDir = await getExternalStorageDirectory();
  String extDir = tempDir!.path;

  // Where folder in this case will be Tralien
  Directory writeDir = Directory.fromUri(Uri(path: "$extDir/$folder")); // Join the folder and external storage
  writeDir.createSync(recursive: true); // We first create the folder and file if it does not exist.
  
  String filename = DateTime.now().millisecondsSinceEpoch.toString();

  File("$extDir/$folder/$filename.jpeg").writeAsBytes(response.bodyBytes, flush: true); // Finally, we write the bytes into the file we just created
}
```

this will create the folders (in this case only the Trailen folder) in the path if they don't exist and it will create the file which then will write the bytes in.

**Comment by k1ran-ak** [comment]
> 

Hi the above-mentioned code works fine but it the directory is inside the Android folder of the internal. Like this code saves in storage/emulated/0/android/data/bundle-id/ I want it in storage/emulated/0/myfolder . Similar to WhatsApp folder in the internal storage of android phone.phones

**Comment by huycozy** [comment]
Hi @k1ran-ak
I see there's an open issue addressing the case you described #40498
Also, there are some clues from related issues that you can try implementing firstly:
- With Android 10 and below:
    - https://github.com/flutter/flutter/issues/89581#issuecomment-914982992
    - https://github.com/flutter/flutter/issues/71355#issuecomment-736321687
- With Android 11 and above: see https://github.com/flutter/flutter/issues/40498#issuecomment-826331592 that explains detail about ScopedStorage and his [workaround](https://github.com/flutter/flutter/issues/40498#issuecomment-828581352) may work in this case.

You can also leave there your comment and react an upvote to the original comment will help to raise the issue.
Closing as a duplication, so please follow up on it for further updates.
