### ISSUE TITLE
GCP deprecating container registry

### ISSUE THREAD

**Issue by yusuf-goog** [flutter/flutter#108759]
We need to evaluate and act as necessary on this recommended migration from google container registry to google artifact registry:

https://cloud.google.com/artifact-registry/docs/transition/transition-from-gcr?_ga=2.215021396.-213196913.1651507600

since a number of our project use this, e.g.: flutter-cirrus

**Comment by yusuf-goog** [comment]
Adding to infra ticket queue for triage/classification, because this might have a specific deadline associated. Not necessarily a current infra ticket queue responsiblity.

**Comment by keyonghan** [comment]
F.Y.I. @drewroengoogle @sealesj @godofredoc this is related to cocoon deploys to registry container.

**Comment by keyonghan** [comment]
@drewroengoogle @sealesj Have we covered all the container cases when we enforce SALSA level1 for cocoon?

**Comment by drewroengoogle** [comment]
> @drewroengoogle @sealesj Have we covered all the container cases when we enforce SALSA level1 for cocoon?

Yes, `flutter-dashboard` has configured container registry to route to artifact registry!

**Comment by keyonghan** [comment]
> > @drewroengoogle @sealesj Have we covered all the container cases when we enforce SALSA level1 for cocoon?
> 
> Yes, `flutter-dashboard` has configured container registry to route to artifact registry!

Thanks for the confirmation. Closing here as completed.
