### ISSUE TITLE
Flutter run fails on connected iOS device

### ISSUE THREAD

**Issue by szakarias** [flutter/flutter#10887]
`flutter create my_app`
`cd my_app`
`flutter run`

produces:

```
 $ flutter run 
Launching lib/main.dart on Sarah's iPod touch in debug mode...
Signing iOS app for device deployment using developer identity: "iPhone Developer: zarah@google.com (996U78ZQLQ)"
Running Xcode build...                                0.9s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **
    
    
    The following build commands failed:
    	Check dependencies
    (1 failure)
Xcode's output:
↳
    Build settings from command line:
        ARCHS = arm64
        BUILD_DIR = /Users/zarah/flutterApps/june21c/build/ios
        DEVELOPMENT_TEAM = 787AJ2398N
        ONLY_ACTIVE_ARCH = YES
        SDKROOT = iphoneos10.3
    
    === CLEAN TARGET Runner OF PROJECT Runner WITH CONFIGURATION Release ===
    
    Check dependencies
    [BCEROR]No profiles for 'com.yourcompany.june21c' were found:  Xcode couldn't find a provisioning profile matching 'com.yourcompany.june21c'.
    [BCEROR]Code signing is required for product type 'Application' in SDK 'iOS 10.3'
    [BCEROR]Code signing is required for product type 'Application' in SDK 'iOS 10.3'
    [BCEROR]Code signing is required for product type 'Application' in SDK 'iOS 10.3'
    
    Create product structure
    /bin/mkdir -p /Users/zarah/flutterApps/june21c/build/ios/Release-iphoneos/Runner.app
    
    Clean.Remove clean /Users/zarah/flutterApps/june21c/build/ios/Release-iphoneos/Runner.app.dSYM
        builtin-rm -rf /Users/zarah/flutterApps/june21c/build/ios/Release-iphoneos/Runner.app.dSYM
    
    Clean.Remove clean /Users/zarah/flutterApps/june21c/build/ios/Release-iphoneos/Runner.app
        builtin-rm -rf /Users/zarah/flutterApps/june21c/build/ios/Release-iphoneos/Runner.app
    
    Clean.Remove clean /Users/zarah/Library/Developer/Xcode/DerivedData/Runner-glexhhtljymtqsgunduxmkvckpph/Build/Intermediates/Runner.build/Release-iphoneos/Runner.build
        builtin-rm -rf /Users/zarah/Library/Developer/Xcode/DerivedData/Runner-glexhhtljymtqsgunduxmkvckpph/Build/Intermediates/Runner.build/Release-iphoneos/Runner.build
    
    ** CLEAN SUCCEEDED **
    
    === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Release ===
    
    Check dependencies
    No profiles for 'com.yourcompany.june21c' were found:  Xcode couldn't find a provisioning profile matching 'com.yourcompany.june21c'.
    Code signing is required for product type 'Application' in SDK 'iOS 10.3'
    Code signing is required for product type 'Application' in SDK 'iOS 10.3'
    Code signing is required for product type 'Application' in SDK 'iOS 10.3'
    
Could not build the precompiled application for the device.
═══════════════════════════════════════════════════════════════════════════════════
No Provisioning Profile was found for your project's Bundle Identifier or your device.
You can create a new Provisioning Profile for your project in Xcode for your
team by:
  1- Open the Flutter project's Xcode target with
       open ios/Runner.xcworkspace
  2- Select the 'Runner' project in the navigator then the 'Runner' target
     in the project settings
  3- In the 'General' tab, make sure a 'Development Team' is selected. You may need to add
     your Apple ID first.
  4- Build or run your project again

For more information, please visit:
  https://flutter.io/setup/#deploy-to-ios-devices

Or run on an iOS simulator without code signing```
═══════════════════════════════════════════════════════════════════════════════════

Error launching application on Sarah's iPod touch.

**Comment by eseidelGoogle** [comment]
This seems expected.  The big block at the bottom attempts to explain how to resolve.  Apple has to generate a cert for your com.example.june21c application identifier, which is only possible from within Xcode to our knowledge.  @xster would know.

**Comment by mit-mit** [comment]
Could we configure projects to use some general 'development preview' team with a wild card profile?

**Comment by szakarias** [comment]
So the command line certificate selection is not possible with personal teams?

**Comment by eseidelGoogle** [comment]
Yeah, we'll have to ask @xster.  It used to be whenever certificates weren't perfectly configured in Xcode, `flutter run` would just fail.  @xster added some support for auto-config, but it only covers some scenarios is my understanding.  See https://github.com/flutter/flutter/issues/10195 and https://github.com/flutter/flutter/issues/10135

**Comment by xster** [comment]
Ya, this is expected.

We can automatically select a development certificate in every case, either with corp certificates or personal ones. 

But a provisioning profile needs to exist for every new application bundle ID you create. That can either be done automatically by opening Xcode (unfortunately not automatable in command line) or by going to the developer console website and adding a bundle ID wildcard for that certificate (which is done with the google corp account but not automatable either for personal accounts).

From what I derive from the comments, it sounds like you made a new app with a new bundle ID and the tool attempted to sign it with a personal certificate. 

1. This may be an actionable part of this bug. Did you have other certificates on the machine used or just 'zarah@google.com (996U78ZQLQ)'? It's a bit strange that it didn't prompt you with a choice. 
2. It does indeed mean that for the typical first time users just using their apple ID, they need to open Xcode once for each new Flutter project they create. Maybe another action item is to optionally suggest that they can skip this for subsequent projects created if they went on the website and registered a wildcard for a broader domain name. 
3. From WWDC, a number of this non-automatable things will become automatable with Xcode 9. Unfortunately, a number of these conveniences are not yet possible now.

**Comment by eseidelGoogle** [comment]
Re: profiles from command line -- Ran across https://github.com/nomad/cupertino just now.  Not sure it's supported.  Claims to help with provisioning profiles.

**Comment by xster** [comment]
I think that project is deprecated and https://github.com/fastlane/fastlane is the biggest toolchain for the code signing flow. But I think it's too heavy of a dependency to bring in and is a bit too unofficial (it actually logs onto the apple website and does scrapping etc). I think it'll also become deprecated with the new set of Xcode 9 command line tools coming out.

**Comment by szakarias** [comment]
I see, I only had  a personal one.  I'll close this bug then. :-) Thanks for the answers.

**Comment by jacobweber** [comment]
Could -allowProvisioningUpdates in Xcode 9 be used to fix this?

**Comment by xster** [comment]
Should be used since #14684 which will be brought in with v0.2.0

**Comment by Allan-Nava** [comment]
How can I fix this error?
=== BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Debug ===
    Code Signing Error: No profiles for 'com.roughike.inkino.ios' were found:  Xcode couldn't find
    any iOS App Development provisioning profiles matching 'com.roughike.inkino.ios'. Automatic
    signing is disabled and unable to generate a profile. To enable automatic signing, pass
    -allowProvisioningUpdates to xcodebuild.
    Code Signing Error: Code signing is required for product type 'Application' in SDK 'iOS 12.1'
    Code Signing Error: Code signing is required for product type 'Application' in SDK 'iOS 12.1'
    Code Signing Error: Code signing is required for product type 'Application' in SDK 'iOS 12.1'

**Comment by eseidelGoogle** [comment]
@Allan-Nava https://stackoverflow.com/questions/tagged/flutter is a better way to ask that kind of question (rather than asking on a closed bug).

I suspect the answer is you need to change the bundle id of the inkino example you're trying to build if you want to build it for release.

**Comment by Allan-Nava** [comment]
I fix with sign-in with xcode

Il giorno ven 4 gen 2019 alle ore 17:42 Eric Seidel <
notifications@github.com> ha scritto:

**Comment by ShirlyChenLaLaLa** [comment]
I fixed this problem.
Just go to the Settings app on the iOS device, select General > Device Management and trust your Certificate.
