### ISSUE TITLE
Flutter Doctor insists on having Android Studio when I already have IDEA

### ISSUE THREAD

**Issue by BoaNeo** [flutter/flutter#10882]
It's kind of annoying to have to install an additional 500MB of IDE that I'll never use and which is essentially a copy of what I already have (Intellij IDEA) - is there no way that Flutter could use IDEA instead if present?

**Comment by eseidelGoogle** [comment]
This is likely a dupe of https://github.com/flutter/flutter/issues/9747.

**Comment by Hixie** [comment]
Closing as dupe of #9747.
