### ISSUE TITLE
Exceptions in WebSocket or Socket,

### ISSUE THREAD

**Issue by york-chen** [flutter/flutter#108865]
## Steps to Reproduce

emm,my english is just soso,it is so hard for me to asking you questions

first,i have a socket address,and i want to connect to it,when i use WebSocket to connect,i get exception,like this
socket = await WebSocket.connect('ws://example.com:6310');

below is the exception:
WebSocketChannelException (WebSocketChannelException: HttpException: Invalid request method, uri = http://example.com:6310)

so i turned to Socket
_socket = await Socket.connect("example.com", 6310);
connect is successful,but the data retuned has some problems,like this 

~{ "tag": 10000, "data": { "vehicle_type": 10, "vehicle_id": "lenovo01", "head": 354.112500, "longitude": 106.819892, "latitude": 29.693025, "altitude": 0.000000, "speed": 0.000000, "accuracy": 0.000000, "plate_number": "lenovo01", "brake_flag": -1, "turn_light": -1 } }~{ "tag": 10001, "data": [ { "vehicle_type": 301, "vehicle_id": "9279595912160055", "head": 94.387500, "longitude": 106.818910, "latitude": 29.692314, "altitude": -4096.000000, "speed": 47.880000, "plate_number": "9279595912160055" }, { "vehicle_type": 301, "vehicle_id": "5771182512160055", "head": 266.175000, "longitude": 106.819411, "latitude": 29.692356, "altitude": -4096.000000, "speed": 26.424000, "plate_number": "5771182512160055" }, { "vehicle_type": 301, "vehicle_id": "9279598212160055", "head": 95.337500, "longitude": 106.818957, "latitude": 29.692273, "altitude": -4096.000000, "speed": 32.616000, "plate_number": "9279598212160055" } ] }

at the head of each message ,it has some Garbled code,i can not solve

but  in javascript and java code,use websocket can work well,only in flutter,can not get the right data. please help me, or i will send the  socket request in java .instead of flutter.

**Comment by exaby73** [comment]
Hi @york-chen, please provide a [minimal, reproducible example][1] and the output of `flutter doctor -v` as well as `flutter run -v`.

[1]: https://stackoverflow.com/help/minimal-reproducible-example
