### ISSUE TITLE
Unhandled Exception: MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/ (shared_preferences, package_info, downloader)

### ISSUE THREAD

**Issue by muhammad-asif-ahmed** [flutter/flutter#108807]
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. ... when execute plugin in our method get  MissingPluginException (MissingPluginException(No implementation found for method getAll on channel [plugins.flutter.io/package_info))](http://plugins.flutter.io/package_info)))

then I commit the package_info code then show another exception on shared_preferences plugin
Unhandled Exception: MissingPluginException(No implementation found for method getAll on channel [plugins.flutter.io/shared_preferences](http://plugins.flutter.io/shared_preferences))

3. anyone please help me. thank in advance .

**Expected results:** 

**Actual results:** 

<details>
<summary>Code sample</summary>

main.dart

```
Future<void> getInfo() async {
  DeviceInfoPlugin deviceInfo = DeviceInfoPlugin();
  AndroidDeviceInfo androidInfo = await deviceInfo.androidInfo;
  print('Running on ${androidInfo.model}');
}

void main() {
  WidgetsFlutterBinding.ensureInitialized();
  getInfo();
  runApp(MyApp());
}
```

I commit out other plugin code just simple is that.
my app stuck on   await deviceInfo.androidInfo and given blow exception :
Exception has occurred.
MissingPluginException (MissingPluginException(No implementation found for method getAndroidDeviceInfo on channel plugins.flutter.io/device_info))

and same exception on shared_preferences and flutter_downloader respectively. 

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

 

```
flutter doctor -v
[√] Flutter (Channel stable, 3.0.5, on Microsoft Windows [Version 10.0.19042.1706], locale en-PK)
    • Flutter version 3.0.5 at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (3 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\adkarachi3\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] VS Code (version 1.69.2)
    • VS Code at C:\Users\adkarachi3\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.44.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19042.1706]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 103.0.5060.134
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 103.0.1264.77

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

</details>

**Comment by exaby73** [comment]
Hello @muhammad-asif-ahmed. I cannot see the code sample attached to your comment. Can you please post that?

**Comment by muhammad-asif-ahmed** [comment]
Hello @exaby73. thank you update.
I have update the sample code, please check.

**Comment by stuartmorgan** [comment]
> `Unhandled Exception: MissingPluginException(No implementation found for method getAll on channel [plugins.flutter.io/shared_preferences](http://plugins.flutter.io/shared_preferences))`

The actual implementation that should have run doesn't use this channel, at least with current versions. Could you provide:
- the code to reproduce the `shared_preferences` version of this,
- the version of `shared_preferences` and `shared_preferences_android` listed in your `pubspec.lock` (assuming this is on Android, per your code above), and
- the contents of `.dart_tool/flutter_build/dart_plugin_registrant.dart`

**Comment by muhammad-asif-ahmed** [comment]
@stuartmorgan thanks in advance.

- shared_preferences: any => pubspec.yaml

-  shared_preferences "2.0.15" and shared_preferences_android: "2.0.12" => pubspec.lock

- for now I testing only android

`//
// Generated file. Do not edit.
// This file is generated from template in file `flutter_tools/lib/src/flutter_plugins.dart`.
//

// @dart = 2.7

import 'dart:io'; // flutter_ignore: dart_io_import.
import 'package:camera_android/camera_android.dart';
import 'package:google_sign_in_android/google_sign_in_android.dart';
import 'package:image_picker_android/image_picker_android.dart';
import 'package:path_provider_android/path_provider_android.dart';
import 'package:shared_preferences_android/shared_preferences_android.dart';
import 'package:url_launcher_android/url_launcher_android.dart';
import 'package:video_player_android/video_player_android.dart';
import 'package:camera_avfoundation/camera_avfoundation.dart';
import 'package:google_sign_in_ios/google_sign_in_ios.dart';
import 'package:image_picker_ios/image_picker_ios.dart';
import 'package:path_provider_ios/path_provider_ios.dart';
import 'package:shared_preferences_ios/shared_preferences_ios.dart';
import 'package:url_launcher_ios/url_launcher_ios.dart';
import 'package:video_player_avfoundation/video_player_avfoundation.dart';
import 'package:device_info_plus_linux/device_info_plus_linux.dart';
import 'package:path_provider_linux/path_provider_linux.dart';
import 'package:shared_preferences_linux/shared_preferences_linux.dart';
import 'package:url_launcher_linux/url_launcher_linux.dart';
import 'package:path_provider_macos/path_provider_macos.dart';
import 'package:shared_preferences_macos/shared_preferences_macos.dart';
import 'package:url_launcher_macos/url_launcher_macos.dart';
import 'package:device_info_plus_windows/device_info_plus_windows.dart';
import 'package:path_provider_windows/path_provider_windows.dart';
import 'package:shared_preferences_windows/shared_preferences_windows.dart';
import 'package:url_launcher_windows/url_launcher_windows.dart';

@pragma('vm:entry-point')
class _PluginRegistrant {

  @pragma('vm:entry-point')
  static void register() {
    if (Platform.isAndroid) {
      try {
        AndroidCamera.registerWith();
      } catch (err) {
        print(
          '`camera_android` threw an error: $err. '
          'The app may not function as expected until you remove this plugin from pubspec.yaml'
        );
        rethrow;
      }

      try {
        GoogleSignInAndroid.registerWith();
      } catch (err) {
        print(
          '`google_sign_in_android` threw an error: $err. '
          'The app may not function as expected until you remove this plugin from pubspec.yaml'
        );
        rethrow;
      }

      try {
        ImagePickerAndroid.registerWith();
      } catch (err) {
        print(
          '`image_picker_android` threw an error: $err. '
          'The app may not function as expected until you remove this plugin from pubspec.yaml'
        );
        rethrow;
      }

      try {
        PathProviderAndroid.registerWith();
      } catch (err) {
        print(
          '`path_provider_android` threw an error: $err. '
          'The app may not function as expected until you remove this plugin from pubspec.yaml'
        );
        rethrow;
      }

      try {
        SharedPreferencesAndroid.registerWith();
      } catch (err) {
        print(
          '`shared_preferences_android` threw an error: $err. '
          'The app may not function as expected until you remove this plugin from pubspec.yaml'
        );
        rethrow;
      }

      try {
        UrlLauncherAndroid.registerWith();
      } catch (err) {
        print(
          '`url_launcher_android` threw an error: $err. '
          'The app may not function as expected until you remove this plugin from pubspec.yaml'
        );
        rethrow;
      }

      try {
        AndroidVideoPlayer.registerWith();
      } catch (err) {
        print(
          '`video_player_android` threw an error: $err. '
          'The app may not function as expected until you remove this plugin from pubspec.yaml'
        );
        rethrow;
      }

    } else if (Platform.isIOS) {
      try {
        AVFoundationCamera.registerWith();
      } catch (err) {
        print(
          '`camera_avfoundation` threw an error: $err. '
          'The app may not function as expected until you remove this plugin from pubspec.yaml'
        );
        rethrow;
      }

      try {
        GoogleSignInIOS.registerWith();
      } catch (err) {
        print(
          '`google_sign_in_ios` threw an error: $err. '
          'The app may not function as expected until you remove this plugin from pubspec.yaml'
        );
        rethrow;
      }

      try {
        ImagePickerIOS.registerWith();
      } catch (err) {
        print(
          '`image_picker_ios` threw an error: $err. '
          'The app may not function as expected until you remove this plugin from pubspec.yaml'
        );
        rethrow;
      }

      try {
        PathProviderIOS.registerWith();
      } catch (err) {
        print(
          '`path_provider_ios` threw an error: $err. '
          'The app may not function as expected until you remove this plugin from pubspec.yaml'
        );
        rethrow;
      }

      try {
        SharedPreferencesIOS.registerWith();
      } catch (err) {
        print(
          '`shared_preferences_ios` threw an error: $err. '
          'The app may not function as expected until you remove this plugin from pubspec.yaml'
        );
        rethrow;
      }

      try {
        UrlLauncherIOS.registerWith();
      } catch (err) {
        print(
          '`url_launcher_ios` threw an error: $err. '
          'The app may not function as expected until you remove this plugin from pubspec.yaml'
        );
        rethrow;
      }

      try {
        AVFoundationVideoPlayer.registerWith();
      } catch (err) {
        print(
          '`video_player_avfoundation` threw an error: $err. '
          'The app may not function as expected until you remove this plugin from pubspec.yaml'
        );
        rethrow;
      }

    } else if (Platform.isLinux) {
      try {
        DeviceInfoLinux.registerWith();
      } catch (err) {
        print(
          '`device_info_plus_linux` threw an error: $err. '
          'The app may not function as expected until you remove this plugin from pubspec.yaml'
        );
        rethrow;
      }

      try {
        PathProviderLinux.registerWith();
      } catch (err) {
        print(
          '`path_provider_linux` threw an error: $err. '
          'The app may not function as expected until you remove this plugin from pubspec.yaml'
        );
        rethrow;
      }

      try {
        SharedPreferencesLinux.registerWith();
      } catch (err) {
        print(
          '`shared_preferences_linux` threw an error: $err. '
          'The app may not function as expected until you remove this plugin from pubspec.yaml'
        );
        rethrow;
      }

      try {
        UrlLauncherLinux.registerWith();
      } catch (err) {
        print(
          '`url_launcher_linux` threw an error: $err. '
          'The app may not function as expected until you remove this plugin from pubspec.yaml'
        );
        rethrow;
      }

    } else if (Platform.isMacOS) {
      try {
        PathProviderMacOS.registerWith();
      } catch (err) {
        print(
          '`path_provider_macos` threw an error: $err. '
          'The app may not function as expected until you remove this plugin from pubspec.yaml'
        );
        rethrow;
      }

      try {
        SharedPreferencesMacOS.registerWith();
      } catch (err) {
        print(
          '`shared_preferences_macos` threw an error: $err. '
          'The app may not function as expected until you remove this plugin from pubspec.yaml'
        );
        rethrow;
      }

      try {
        UrlLauncherMacOS.registerWith();
      } catch (err) {
        print(
          '`url_launcher_macos` threw an error: $err. '
          'The app may not function as expected until you remove this plugin from pubspec.yaml'
        );
        rethrow;
      }

    } else if (Platform.isWindows) {
      try {
        DeviceInfoWindows.registerWith();
      } catch (err) {
        print(
          '`device_info_plus_windows` threw an error: $err. '
          'The app may not function as expected until you remove this plugin from pubspec.yaml'
        );
        rethrow;
      }

      try {
        PathProviderWindows.registerWith();
      } catch (err) {
        print(
          '`path_provider_windows` threw an error: $err. '
          'The app may not function as expected until you remove this plugin from pubspec.yaml'
        );
        rethrow;
      }

      try {
        SharedPreferencesWindows.registerWith();
      } catch (err) {
        print(
          '`shared_preferences_windows` threw an error: $err. '
          'The app may not function as expected until you remove this plugin from pubspec.yaml'
        );
        rethrow;
      }

      try {
        UrlLauncherWindows.registerWith();
      } catch (err) {
        print(
          '`url_launcher_windows` threw an error: $err. '
          'The app may not function as expected until you remove this plugin from pubspec.yaml'
        );
        rethrow;
      }

    }
  }
}
`

**Comment by stuartmorgan** [comment]
Please provide the exact code that gave you the `shared_preferences` exception, and the full stack for it. You have the Dart registration there, so an error referencing the `plugins.flutter.io/shared_preferences` channel should not have happened.

**Comment by muhammad-asif-ahmed** [comment]
> Actual project's code **main.dart**

`library main;
import 'dart:convert';
import 'dart:isolate';
import 'dart:ui';
import 'package:android_path_provider/android_path_provider.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_downloader/flutter_downloader.dart';
import 'package:fluttertoast/fluttertoast.dart';
import 'package:stepchain/screens/auth/new_login_screen.dart';
import 'package:stepchain/utils/FitDataUpdate/FitDataUpdate.dart';
import 'package:stepchain/utils/FrenchLocalDelegate.dart';
import 'package:stepchain/utils/analytics.dart';
import 'package:stepchain/utils/config.dart';
import 'package:stepchain/utils/headers.dart';
import 'package:stepchain/utils/themes.dart';
import 'package:device_info/device_info.dart';
import 'package:store_redirect/store_redirect.dart';
import 'package:stepchain/stored/storedPreference.dart';
import 'package:stepchain/model/services/fcm_payload.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:stepchain/model/services/fcm_token_model.dart';
import 'package:stepchain/presentation/toast/toast_utils.dart';
import 'package:stepchain/presentation/toast/fullscreen_toast.dart';
import 'package:stepchain/presentation/toast/competition_toast.dart';
import 'package:stepchain/screens/Profile/notification_page.dart';
import 'package:stepchain/screens/chatscreen/chat.dart';
import 'package:stepchain/model/user/get_profile.dart' as profile;
import 'package:http/http.dart' as http;
import 'package:stepchain/screens/what_up_stack/whats_up_page.dart';
import 'package:stepchain/model/services/menu_modal.dart';
import 'package:stepchain/model/services/cofiguration_modal.dart';
import 'package:cached_network_image/cached_network_image.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:stepchain/screens/auth/signup_page.dart';
import 'package:stepchain/utils/ScreenUtils.dart';
import 'package:stepchain/screens/tour_layout.dart';
import 'package:stepchain/screens/auth/social_login.dart';
import 'package:stepchain/screens/wallet/wallet_main.dart';
import 'package:stepchain/screens/wallet/wallet_page.dart';
import 'package:stepchain/screens/profile/profile_page.dart';
import 'package:stepchain/screens/activity/my_activity_layout.dart';
import 'package:stepchain/utils/dynamic_asset_handler/download_app_settings.dart';
import 'package:stepchain/screens/auth/choose_lang_screen.dart';
import 'package:stepchain/screens/auth/choose_country_screen.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:stepchain/screens/chatscreen/chat_list_page.dart';
import 'package:stepchain/model/general/app_identifier.dart';
import 'package:stepchain/utils/restart.dart';
import 'package:stepchain/screens/wallet/workouts/workout_plan_page.dart';
import 'package:stepchain/screens/wallet/workouts/new_workout_plan_page.dart';
import 'package:flutter/cupertino.dart';
import 'package:stepchain/utils/extensions.dart';
import 'package:package_info/package_info.dart';
import 'package:path_provider/path_provider.dart';
import 'package:flutter/foundation.dart';
import 'package:in_app_purchase_android/in_app_purchase_android.dart';
import 'package:stepchain/utils/step_background/step_counter_service.dart';
part 'package:stepchain/screens/main/app.dart';
part 'package:stepchain/screens/main/dashboard.dart';
part 'package:stepchain/utils/fcm_handler/fcm_action_manager.dart';
part 'package:stepchain/screens/main/activity.dart';

Future<String> _findLocalPath() async {
  var externalStorageDirPath;
  if (Platform.isAndroid) {
    try {
      externalStorageDirPath = await AndroidPathProvider.downloadsPath;
    } catch (e) {
      final directory = await getExternalStorageDirectory();
      externalStorageDirPath = directory?.path;
    }
  } else if (Platform.isIOS) {
    externalStorageDirPath =
        (await getApplicationDocumentsDirectory()).absolute.path;
  }
  return externalStorageDirPath;
}

void main() {
  WidgetsFlutterBinding.ensureInitialized();
  SystemChrome.setPreferredOrientations(
          [DeviceOrientation.portraitUp, DeviceOrientation.portraitDown])
      .then((_) async {
    getIt.registerLazySingleton(() => Analytics());

    //SharedPreferences.setMockInitialValues({});
    var preferences = await SharedPreferences.getInstance();
    StoredPreference.shared.prefs = preferences;

    if (Platform.isIOS)
      StoredPreference().imageAssetPath = (await _findLocalPath());

    if (StoredPreference().appId == 0) {
      await AppIdentifier.getAppInfo().then((value) {
        try {
          StoredPreference().appId = value.id;
          StoredPreference().loadingScreenLogo = value.loadingScreen.logoImage;
          StoredPreference().langLoadingLogo =
              value.loadingScreen.langLoadingLogo != null
                  ? value.loadingScreen.langLoadingLogo
                  : "";
          StoredPreference().loadingScreenBackgroundColor =
              value.loadingScreen.backgroundColor;
          StoredPreference().loadingScreenBackground =
              value.loadingScreen.backgroundImage;
          StoredPreference().loadingScreenGradient1 =
              value.loadingScreen.gradientColorStart;
          StoredPreference().loadingScreenGradient2 =
              value.loadingScreen.gradientColorEnd;
          StoredPreference().commonShape =
              value.uiControl.shape.rounded.toDouble();
          StoredPreference().defaultLoginMethod = value.defaultLoginMethod;
          StoredPreference().loadingGif = value.loadingScreen.loadingGif;
          StoredPreference().showLanguage = value.showLanguage;
          StoredPreference().appName = value.displayName;
          StoredPreference().userLanguageSelected = value.defaultLanguage;
//        StoredPreference().ctaColor = value.fonts.langButtonCta.fontColor;
          StoredPreference().ctaNextIcon = 'value.loadingScreen.ctaNextIcon';
        } catch (e) {
          print(e);
        }
      });
    }

    SystemChrome.setSystemUIOverlayStyle(SystemUiOverlayStyle.light.copyWith(
        statusBarIconBrightness: Brightness.light,
        statusBarBrightness: Brightness.dark,
        systemNavigationBarColor: Colors.black,
        statusBarColor: Colors.transparent,
        systemNavigationBarIconBrightness: Brightness.light));

    await FlutterDownloader.initialize(
        debug: true // optional: set false to disable printing logs to console
        );

    runApp(MyApp());
  });
}
`

> pubspec.yaml

`name: xyz
description: A responsible fitness app

version: 1.2.3+21

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  easy_localization: ^3.0.0


  google_maps_flutter:
  cloud_firestore:
  flutter_facebook_auth:
  google_sign_in:
  sign_in_with_apple:
  cupertino_icons:
  fluttertoast:
  percent_indicator:
  page_indicator:
  flutter_animation_progress_bar:
  font_awesome_flutter:
  pagination:
  step_progress_indicator:
  auto_size_text:
  flutter_svg: ^0.22.0
  flutter_keyboard_visibility:
  story_view: ^0.13.1
  flutter_custom_clippers:
  flutter_swiper:
  simple_animations: ^2.4.2
  recase:
  shimmer:
  fl_chart: ^0.45.0
  flutter_spinkit:
  simple_tooltip:
  camera:
  vibration:
  location:
  video_player:
  shared_preferences: ^2.0.15
  device_info:
  device_apps:
  path_provider:
  contacts_service:
  permission_handler:
  store_redirect:
  share:
  connectivity:
  wakelock:
  image_picker:
  image_cropper:
  photo_manager:
  cached_network_image:
  http:
  flutter_widget_from_html_core:
  flutter_downloader:
  android_path_provider: ^0.3.0
  url_launcher:
  intl:
  provider:
  date_format:
  enum_to_string:
  after_layout:
  package_info:
  webview_flutter:
  flutter_local_notifications:
  photo_view:
  gallery_saver:
  flutter_linkify:
  carousel_slider:
  flutter_html: ^2.1.5
  syncfusion_flutter_pdfviewer:
  native_device_orientation:
  youtube_player_flutter:
  youtube_parser:
  battery:
  flutter_toastr:
  flutter_file_manager:
  searchfield: ^0.5.6
  in_app_purchase:
  firebase_analytics: ^8.0.1
  firebase_crashlytics:
  firebase_messaging:
  firebase_storage:
  firebase_dynamic_links:
  firebase_auth:
  cloud_functions:
  firebase:
  health: ^3.4.3
  get_it: ^7.2.0
  firebase_core:
  pedometer: ^3.0.0
  flutter_login_facebook: ^1.4.1


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:


  uses-material-design: true


  fonts:
    - family: Nexa
      fonts:
        - asset: fonts/NexaBold.otf
          weight: 700
        - asset: fonts/NexaXBold.otf
          weight: 900
        - asset: fonts/NexaRegular.otf
          weight: 400 #style: normal
        - asset: fonts/NexaThin.otf
          weight: 100 #style: italic
        - asset: fonts/NexaHeavy.otf
          weight: 500
    - family: CIconBottom
      fonts:
        - asset: fonts/CIconBottom.ttf
          weight: 400
    - family: CIconTop
      fonts:
        - asset: fonts/CIconTop.ttf
          weight: 400
    - family: GE_SS_Two
      fonts:
        - asset: fonts/GE_SS_Two_Medium.otf
          weight: 700
        - asset: fonts/GE_SS_Two_Bold.otf
          weight: 900
        - asset: fonts/GE_SS_Two_Light.otf
          weight: 400
    - family: PublicaSans
      fonts:
        - asset: fonts/PublicaSans-Bold.otf
          weight: 700
        - asset: fonts/PublicaSans-Bold.otf
          weight: 900
        - asset: fonts/PublicaSans-Light.otf
          weight: 400 #style: normal
        - asset: fonts/PublicaSans-Thin.otf
          weight: 100
        - asset: fonts/PublicaSans-Bold.otf
          weight: 500

  
  > MainActivity.kt
  
  `package com.vidadigitalmobile.gsbyorange

import android.os.Bundle
import io.flutter.embedding.android.FlutterActivity
import io.flutter.embedding.engine.FlutterEngine
import io.flutter.embedding.engine.plugins.util.GeneratedPluginRegister
import io.flutter.plugin.common.MethodChannel
import io.flutter.plugins.GeneratedPluginRegistrant;

class MainActivity : FlutterActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        GeneratedPluginRegister.registerGeneratedPlugins(FlutterEngine(this))
        super.onCreate(savedInstanceState)
        Notifications.createNotificationChannels(this)
//        GeneratedPluginRegistrant.registerWith(this);
    }

    override fun configureFlutterEngine(flutterEngine: FlutterEngine) {
        

        super.configureFlutterEngine(flutterEngine)

        val binaryMessenger = flutterEngine.dartExecutor.binaryMessenger

        MethodChannel(binaryMessenger, "com.step/background_service").apply {
            setMethodCallHandler { method, result ->
                if (method.method == "startService") {
                    val callbackRawHandle = method.arguments as Long
                    BackgroundService.startService(this@MainActivity, callbackRawHandle)
                    result.success(null)
                } else {
                    result.notImplemented()
                }
            }
        }

        MethodChannel(binaryMessenger, "com.example/app_retain").apply {
            setMethodCallHandler { method, result ->
                if (method.method == "sendToBackground") {
                    moveTaskToBack(true)
                    result.success(null)
                } else {
                    result.notImplemented()
                }
            }
        }
    }
}
`
![Screenshot 2022-08-04 133210](https://user-images.githubusercontent.com/110467738/182801864-3bfee46f-47cf-4146-b7b9-196598c52046.png)

**Comment by stuartmorgan** [comment]
Your screenshot shows a different error than what you quoted above; `plugins.flutter.io/shared_preferences_android` is the correct channel, which changes this significantly.

How exactly are you starting the engine on the native side? It sounds like you running this code in an engine without any native plugin registration run against it.

**Comment by muhammad-asif-ahmed** [comment]
I am totally new to this project and not much expertise on native side. I recently started working on the project. I can't run this project because of plugins exceptions. Can you help me .what's the main problem with it.
problem is not only this plugin shared_preferences_android. I face the exception other plugins as well.  
@stuartmorgan @exaby73

**Comment by stuartmorgan** [comment]
> what's the main problem with it.

The problem is that on the Java side, none of the plugin registration appears to have been run for this engine. We need to see the code in your project that starts the engine to know if that's expected or not.

**Comment by muhammad-asif-ahmed** [comment]
So what do we do now??
for the solution...

**Comment by stuartmorgan** [comment]
@muhammad-asif-ahmed We cannot debug this further until you provide the information requested above.

**Comment by Ulukbek-01** [comment]
I also encountered the same issue today. I solved it simply by stopping my app and rerunning it.
