### ISSUE TITLE
[Mac, iPad, iPhone] enumerateDevices does not load audio outputs

### ISSUE THREAD

**Issue by ollydixon** [flutter/flutter#108874]
```Flutter 3.0.5```

Calling this function
```await navigator.mediaDevices.enumerateDevices()```

Does not produce audio outputs

<img width="1454" alt="Screenshot 2022-08-03 at 13 25 33" src="https://user-images.githubusercontent.com/6940726/182596861-798ed604-951a-4d02-aa84-3b638ba88ebd.png">

We have no way to switch audio-outputs for multiple reasons
- Think apps that play media (very common)
- Apps that do WebRTC
- Apps that are music players
- Etc

!!! Have not tested on Windows/Android or Web

**Comment by maheshmnj** [comment]
@ollydixon, This issue doesn't seem related to flutter. Closing as invalid in case you disagree feel free to write in the comments ad new will reopen it.

**Comment by ollydixon** [comment]
@maheshmnj ah yes, I though navigator was native to Flutter SDK.

**Comment by maheshmnj** [comment]
I am thinking If I made a mistake looking at this https://api.flutter.dev/flutter/dart-html/MediaDevices/enumerateDevices.html
seems related to `dart:html`

**Comment by ollydixon** [comment]
@maheshmnj I think you might have made a mistake, it happens :-)

**Comment by maheshmnj** [comment]
Reopening considering https://api.flutter.dev/flutter/dart-html/MediaDeviceInfo-class.html is from `dart:html`.

**Comment by maheshmnj** [comment]
@ollydixon Sorry again I consulted internally you should file this at https://github.com/dart-lang/sdk/issues

Closing as this is not related to the flutter framework.

**Comment by ollydixon** [comment]
@maheshmnj I'm not sure how dart-lang would relate to this? Since that's just the language and not the framework (flutter)

**Comment by maheshmnj** [comment]
@ollydixon I also see a issue related to MediaDeviceInfo filed there in the past https://github.com/dart-lang/sdk/issues/32698, so I think that is intended a right repo. 
Please try filing there if the dart team thinks it's not related, Please leave a comment on this issue and we will reopen it.

**Comment by ollydixon** [comment]
@maheshmnj we also have a comment from CloudSDK saying there is a fix in https://github.com/flutter-webrtc/flutter-webrtc/issues/1037

**Comment by kevmoo** [comment]
It's possible that https://api.dart.dev/stable/2.17.6/dart-html/MediaDevices/enumerateDevices.html has a bug. We'd need to investigate.

What does this function return now? What is expected?

**Comment by ollydixon** [comment]
@kevmoo I've posted a screenshot with the debugger showing what it returns. It's missing the audio output devices.

**Comment by kevmoo** [comment]
We don't do much magic here. Just wrap the JS API

See https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/enumerateDevices

Is it possible the desired device is now authorized?
Have you tried to repeat using normal Javascript?

**Comment by ollydixon** [comment]
@kevmoo we are using flutter so we are testing on Mac/iOS

**Comment by kevmoo** [comment]
@ollydixon – but you're testing WEB on these devices, right?
