### ISSUE TITLE
Impeller rendering fidelity regressed on Android

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#108854]
After the commit here https://github.com/flutter/engine/pull/35052, rendering fidelity on Android has regressed significantly. Images and text are missing and are replaced with solid color boxes in flutter/gallery. I guess this is not unexpected since the Vulkan backend is in-progress, but filing this anyway for awareness.

![test](https://user-images.githubusercontent.com/6343103/182513938-a757c32a-6462-44c6-be60-d1b6d7b5c745.png)

cc @iskakaushik @chinmaygarde

**Comment by chinmaygarde** [comment]
@iskakaushik can we please revert the patch?

**Comment by zanderso** [comment]
The wrong patch was reverted =( The problematic one was https://github.com/flutter/engine/pull/35052 not the one reverted by https://github.com/flutter/engine/pull/35136.

**Comment by iskakaushik** [comment]
Reverting the right now here https://github.com/flutter/engine/pull/35167. Sorry for the confusion.
