### ISSUE TITLE
Red screen, no logs, when route callback returns a State

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#1088]
(this is definitely a user bug, but maybe we can provide the user with some feedback?)

The following code generates a red screen, and it's probably because I'm returning a State object from my route callback (and not returning a Component/Widget).

```
import 'package:flutter/material.dart';

void main() {
  runApp(new MaterialApp(
      title: "Flutter Demo",
      routes: {'/': (RouteArguments args) => new FlutterDemo()}));
}

class FlutterDemoComponent extends StatefulComponent {
  @override
  State createState() => new FlutterDemo();
}

class FlutterDemo extends State {
  String message = "Hello, world!";

  Widget build(BuildContext context) {
    return new Scaffold(
        toolBar: new ToolBar(center: new Text("Flutter Demo")),
        body: new Material(child: new Center(child: new Text(message))),
        floatingActionButton: new FloatingActionButton(
            child: new Icon(icon: 'content/add'), onPressed: () {
          setState(() {
            message = "tapped!";
          });
        }));
  }
}
```

This is what I saw in the logs:

![screen shot 2016-01-06 at 1 04 23 pm](https://cloud.githubusercontent.com/assets/5479/12154719/09e7d04a-b476-11e5-9b0a-aef5d1dd1de6.png)

And I didn't see any analyzer warnings/hints that something was wrong.

If we draw a complete red screen, should we spit something out to the logs?

Also, in this particular case, I'm curious why I didn't get a type warning. Maybe an analyzer bug?

**Comment by sethladd** [comment]
Possible analyzer bug: https://github.com/dart-lang/sdk/issues/25363

**Comment by Hixie** [comment]
You didn't get an analyzer warning because your map literal is defined as
Map<dynamic, dynamic>, and "(RouteArguments) => State" matches "dynamic".
This is why you should always put types on literals. :-)

You should have seen an exception on the logs, though. If you didn't,
please file a bug.

**Comment by sethladd** [comment]
> You didn't get an analyzer warning because your map literal is defined as

That's true, but I'm hoping the analyzer can infer this for me.

> You should have seen an exception on the logs, though. If you didn't,
please file a bug.

This is that bug :)

**Comment by Hixie** [comment]
Oh, duh. I thought this was a flutter-dev e-mail. Me so confoose.

**Comment by Hixie** [comment]
I get a ton of stuff in the logs:

```
01-07 21:59:42.875  3654  3673 I flutter : -- EXCEPTION CAUGHT BY WIDGETS LIBRARY ---------------------------------
01-07 21:59:42.876  3654  3673 I flutter : Exception caught while building _ModalScope-[GlobalKey 645646520]
01-07 21:59:42.877  3654  3673 I flutter : type 'FlutterDemo' is not a subtype of type 'Widget' of 'result'.
01-07 21:59:42.877  3654  3673 I flutter : Stack trace:
01-07 21:59:42.890  3654  3673 I flutter : #0      MaterialPageRoute.buildPage (packages/flutter/src/material/page.dart:60)
01-07 21:59:42.890  3654  3673 I flutter : #1      _ModalScopeState.build (packages/flutter/src/widgets/routes.dart:336)
01-07 21:59:42.890  3654  3673 I flutter : #2      ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1160)
01-07 21:59:42.890  3654  3673 I flutter : #3      BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:1101)
...
```

You don't get that?

**Comment by sethladd** [comment]
Looks like the logs are showing some good info. The analyzer can't help us here unless we're strong mode enabled, or we use a parameterized type on the map.
