### ISSUE TITLE
[google_sign_in] Pop up dialog is not scrollable on with a device large font

### ISSUE THREAD

**Issue by softkot** [flutter/flutter#108815]
On a certain devices when font size is set to the maximum, it is not possible ti choose an account and no scrolling is available.

See screencast

https://user-images.githubusercontent.com/5500358/182399620-3541686c-fdf3-491f-8e1b-f5030e7d5716.mp4

Steps to reproduce:
1. Set font-size to maximum on device.
1. Make sure device has logged in google accounts.
1. Open app supporting google sign-in.
1. Attempt sign-in with google.

Observe and issue.

**Comment by danagbemava-nc** [comment]
Kindly see https://github.com/flutter/flutter/issues/107922#issuecomment-1195749933. 

Closing this based on the linked comment. 

Thank you
