### ISSUE TITLE
Add libupower-glib-dev to Linux bot VM

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#108872]
We need the `libupower-glib-dev` package added to the Linux builders for bringing one of the flutter/flutter examples online for Linux. See https://github.com/flutter/flutter/pull/108068#issuecomment-1190977923 and subsequent discussion.

/cc @cbracken @robert-ancell

**Comment by cbracken** [comment]
From @godofredoc's comment in #108068:

> This type of dependencies need to be included at the OS level and baked into the VM image. You can create a bug requesting the dependency and I'll route it to the correct people. This process may take several days because after adding the dependency the new image needs to be tested in staging.

**Comment by godofredoc** [comment]
@yusuf-goog can you please follow up with @whesse  and @athomas to add this dependency?

**Comment by godofredoc** [comment]
In addition to that, it will be great if we document the process.

**Comment by yusuf-goog** [comment]
Proposed change in: http://go/cirgs/4918425

Once the change is merged, it will take ~1 week to rollout.

**Comment by yusuf-goog** [comment]
Change is merged, rollout should progress as expected ~1week. Closing this for now, since all actions needed have been completed, please reopen if any issues crop up.
