### ISSUE TITLE
Several driver-based tests failing on engine roll

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#108881]
The engine roll https://github.com/flutter/flutter/pull/108862 contains only a dart roll https://github.com/flutter/engine/pull/35118 with commits https://dart.googlesource.com/sdk.git/+log/a8d90480d8ff..ba75fe6598e3.

Some example failures:
https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_ios%20complex_layout_scroll_perf_ios__timeline_summary/5986/overview
https://ci.chromium.org/ui/p/flutter/builders/prod/Linux_android%20complex_layout_scroll_perf__devtools_memory/4124/overview
https://ci.chromium.org/ui/p/flutter/builders/prod/Linux_samsung_s10%20new_gallery_impeller__transition_perf/273/overview
https://ci.chromium.org/ui/p/flutter/builders/prod/Linux_samsung_s10%20complex_layout_scroll_perf__timeline_summary/2215/overview

**Comment by jason-simmons** [comment]
This started with https://github.com/dart-lang/sdk/commit/460bd7a03a2ef87663ad14a28db52d7ad93be8b5

@rmacnak-google

**Comment by rmacnak-google** [comment]
I do not see an original failure in these logs, only the harness timing out. Presumably there is an exception or crash in the target engine process.

**Comment by jason-simmons** [comment]
The target Flutter app process is not crashing.  But midway through the test script the app process fails to correctly execute a request issued by the harness.  The harness keeps polling the app waiting for the expected response, and eventually it times out.

The Dart SDK commit has been reverted:
https://github.com/dart-lang/sdk/commit/d94a1cd419d8d644516336f9bbeae2e751ecdbf1

**Comment by a-siva** [comment]
The Dart commit has been reverted, please consider lowering the priority to P2, we would still like to figure out the failure.

**Comment by zanderso** [comment]
Yeah, since the roller is moving again, this is no longer a P0.

**Comment by a-siva** [comment]
I think this can be closed.
