### ISSUE TITLE
linux 2 is causing tests flaky

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#108842]
This has caused several tests flaky
Linux_android flavors_test: [2809](https://ci.chromium.org/ui/p/flutter/builders/prod/Linux_android%20flavors_test/2809/overview)
Linux_android flutter_gallery__transition_perf_e2e: [1088](https://ci.chromium.org/ui/p/flutter/builders/prod/Linux_android%20flutter_gallery__transition_perf_e2e/1088/overview), [1080](https://ci.chromium.org/ui/p/flutter/builders/prod/Linux_android%20flutter_gallery__transition_perf_e2e/1080/overview)
Linux_android fullscreen_textfield_perf: [2289](https://ci.chromium.org/ui/p/flutter/builders/prod/Linux_android%20fullscreen_textfield_perf/2289/overview)
Linux_android flutter_gallery__transition_perf_hybrid: [1128](https://ci.chromium.org/ui/p/flutter/builders/prod/Linux_android%20flutter_gallery__transition_perf_hybrid/1128/overview)
...

Example build: 
https://ci.chromium.org/ui/p/flutter/builders/prod/Linux_android%20flutter_gallery__transition_perf_e2e/1088/overview

It complains `adb: device 'ZY223TDZ45' not found`.

```
[flutter_gallery__transition_perf_e2e] [STDOUT] Executing "/opt/s/w/ir/x/w/recipe_cleanup/tmpss3k4xa8/flutter sdk/bin/flutter drive --screenshot /opt/s/w/ir/x/w/recipe_cleanup/flutter_logs_dir --no-dds --profile --use-application-binary=build/app/outputs/flutter-apk/app-profile.apk --driver test_driver/transitions_perf_e2e_test.dart -d ZY223TDZ45" in "/opt/s/w/ir/x/w/recipe_cleanup/tmpss3k4xa8/flutter sdk/dev/integration_tests/flutter_gallery" with environment {BOT: true, LANG: en_US.UTF-8}
[flutter_gallery__transition_perf_e2e] [STDOUT] stdout: Running "flutter pub get" in flutter_gallery...                  2,257ms
[flutter_gallery__transition_perf_e2e] [STDOUT] stdout: Installing build/app/outputs/flutter-apk/app-profile.apk...      1,270ms
[flutter_gallery__transition_perf_e2e] [STDOUT] stderr: Error: ADB exited with exit code 1
[flutter_gallery__transition_perf_e2e] [STDOUT] stderr: Performing Streamed Install
[flutter_gallery__transition_perf_e2e] [STDOUT] stderr: 
[flutter_gallery__transition_perf_e2e] [STDOUT] stderr: adb: failed to install build/app/outputs/flutter-apk/app-profile.apk:
[flutter_gallery__transition_perf_e2e] [STDOUT] stdout: Uninstalling old version...
[flutter_gallery__transition_perf_e2e] [STDOUT] stdout: Installing build/app/outputs/flutter-apk/app-profile.apk...        750ms
[flutter_gallery__transition_perf_e2e] [STDOUT] stderr: Error: ADB exited with exit code 1
[flutter_gallery__transition_perf_e2e] [STDOUT] stderr: Performing Streamed Install
[flutter_gallery__transition_perf_e2e] [STDOUT] stderr: 
[flutter_gallery__transition_perf_e2e] [STDOUT] stderr: adb: failed to install build/app/outputs/flutter-apk/app-profile.apk:
[flutter_gallery__transition_perf_e2e] [STDOUT] stderr: Error: Failed to install APK again.
[flutter_gallery__transition_perf_e2e] [STDOUT] stderr: Application failed to start on attempt: 1
[flutter_gallery__transition_perf_e2e] [STDOUT] stderr: adb: device 'ZY223TDZ45' not found
[flutter_gallery__transition_perf_e2e] [STDOUT] stdout: Installing build/app/outputs/flutter-apk/app-profile.apk...          5ms
[flutter_gallery__transition_perf_e2e] [STDOUT] stderr: Error: ADB exited with exit code 255
[flutter_gallery__transition_perf_e2e] [STDOUT] stderr: Performing Push Install
```

/cc gardener @chunhtai

**Comment by keyonghan** [comment]
Manually quarantined for now.
SSHing to the bot didn't show me anything weird.
Screen capture of the device shows normal as on the home screen.

Anything else may cause device not found? /cc @zanderso @GaryQian @godofredoc  Maybe loose cable, etc? Which may need a lab visit.

**Comment by zanderso** [comment]
If the device is rebooting itself, that would look like disappearing and coming back, but I suspect that would also need a trip to the lab to resolve.

**Comment by keyonghan** [comment]
Reset the phone on linux2, and switched it with a mac/android testbed (mac33) in staging.
Moving linux2 to staging for validation.

**Comment by keyonghan** [comment]
The bot is running okay in staging. Closing.
