### ISSUE TITLE
[CP] Catch more general XmlException in tool

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#108840]
### issue_link

https://github.com/flutter/flutter/issues/106365

### Commit Hash

cadb264d2612a372652022caaf06ab8fee434e7c

### Target

beta

### pr_link

https://github.com/flutter/flutter/pull/108839

### Impacted Users

Flutter devs targeting android who have malformed XML config files, such as their manifest

### Impact Description

When the tool fails to parse a malformed XML config file, rather than showing a user friendly tool exit with the absolute path to the file that the user must fix, the exception will bubble up and the user will have to check the source code to determine what the tool was trying to parse.

### Workaround

The user would have to know to check their app's manifest file.

### Risk

low

### Test Coverage

yes

### Validation Steps

1. Create a new flutter app: `flutter create test_bad_xml`
2. edit the contents of `test_bad_xml/android/app/src/debug/AndroidManifest.xml` to have invalid XML, such as `<manifest></application>`
3. build the app in debug mode: `flutter build apk --debug`; verify that there is a tool exit with the path to the bad file.

**Comment by itsjustkevin** [comment]
@zanderso

**Comment by zanderso** [comment]
This is low-risk and fixes a top tool crasher in the beta, so lgtm for cherry-pick.

**Comment by itsjustkevin** [comment]
Labeling this as approved, @christopherfujino please hold off on merging this until the release is complete.

**Comment by christopherfujino** [comment]
> Labeling this as approved, @christopherfujino please hold off on merging this until the release is complete.

I will defer merging to the release team
