### ISSUE TITLE
Errors of launch_review-3.0.1 in xCode

### ISSUE THREAD

**Issue by mmoahrefs** [flutter/flutter#108870]
I'm new to xCode and iOS app. I build this flutter source code in xCode 13.2.1 and got some errors of LauchReviewPlugin (ver 3.0.1).

Can you help me to fix it? Thank you very much!!!

_Parse Issue (Xcode): Expected expression /Users/khoanguyen/Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/launch_revi ew-3.0.1/ios/Classes/LaunchReviewPlugin.m:42:91

Parse Issue (Xcode): Expected expression /Users/khoanguyen/Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/launch_revi ew-3.0.1/ios/Classes/LaunchReviewPlugin.m:50:85

Semantic Issue (Xcode): Use of undeclared identifier 'options' /Users/khoanguyen/Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/launch_review-3.0.1/ios/Classes/LaunchReviewPlugin.m:42:65

Semantic Issue (Xcode): Use of undeclared identifier 'completionHandler' /Users/khoanguyen/Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/launch_review-3.0.1/ios/Classes/LaunchReviewPlugin.m:42:73

Semantic Issue (Xcode): Use of undeclared identifier 'options' /Users/khoanguyen/Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/launch_review-3.0.1/ios/Classes/LaunchReviewPlugin.m:50:59

Semantic Issue (Xcode): Use of undeclared identifier 'completionHandler' /Users/khoanguyen/Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/launch_review-3.0.1/ios/Classes/LaunchReviewPlugin.m:50:67_

[image](https://i.stack.imgur.com/vjHPe.png)

**Comment by stuartmorgan** [comment]
Issues in third-party packages (in this case, `launch_review`) need to be reported to the package developer rather than the Flutter team.
