### ISSUE TITLE
Flutter github codelabs issue with getPlatformVersion and WindowToFront plugin

### ISSUE THREAD

**Issue by Seanmyr** [flutter/flutter#108896]
I'm trying to go through the google codelabs project for creating a Flutter github desktop app.  I'm on step 6 of that codelabs project which is detailing how to create the window_to_front plugin.  That plugin is supposed to make it so that after authentication the app comes back to the forefront and is active.

I'm the type that usually manually types out every bit of code in a tutorial as I tend to learn best that way.  However when I started having this current issue and I couldn't find the problem by comparing my code to what's in the codelabs project I decided to do a copy and paste sort of thing.  However I'm still getting the following issues.

The codelabs doesn't say to do any editing of the window_to_front plugin's main.dart file, yet I'm getting this issue in that file...
`[{
	"resource": "/c:/Projects/window_to_front/example/lib/main.dart",
	"owner": "_generated_diagnostic_collection_name_#0",
	"code": {
		"value": "undefined_method",
		"target": {
			"$mid": 1,
			"external": "https://dart.dev/diagnostics/undefined_method",
			"path": "/diagnostics/undefined_method",
			"scheme": "https",
			"authority": "dart.dev"
		}
	},
	"severity": 8,
	"message": "The method 'getPlatformVersion' isn't defined for the type 'WindowToFront'.\nTry correcting the name to the name of an existing method, or defining a method named 'getPlatformVersion'.",
	"source": "dart",
	"startLineNumber": 35,
	"startColumn": 38,
	"endLineNumber": 35,
	"endColumn": 56
}]`

For reference here's that main.dart file...
```
import 'package:flutter/material.dart';
import 'dart:async';

import 'package:flutter/services.dart';
import 'package:window_to_front/window_to_front.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatefulWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  String _platformVersion = 'Unknown';
  final _windowToFrontPlugin = WindowToFront();

  @override
  void initState() {
    super.initState();
    initPlatformState();
  }

  // Platform messages are asynchronous, so we initialize in an async method.
  Future<void> initPlatformState() async {
    String platformVersion;
    // Platform messages may fail, so we use a try/catch PlatformException.
    // We also handle the message potentially returning null.
    try {
      platformVersion =
          await _windowToFrontPlugin.getPlatformVersion() ?? 'Unknown platform version';
    } on PlatformException {
      platformVersion = 'Failed to get platform version.';
    }

    // If the widget was removed from the tree while the asynchronous platform
    // message was in flight, we want to discard the reply rather than calling
    // setState to update our non-existent appearance.
    if (!mounted) return;

    setState(() {
      _platformVersion = platformVersion;
    });
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Plugin example app'),
        ),
        body: Center(
          child: Text('Running on: $_platformVersion\n'),
        ),
      ),
    );
  }
}
```

Since I can't figure out what the problem is and googling the issue didn't seem to help me at all (maybe I wasn't googling correctly I don't know), I thought that maybe there's an issue with that codelabs project?  Some step that I should have done but am not seeing?  Any help would be greatly appreciated.

**Comment by stuartmorgan** [comment]
> The codelabs doesn't say to do any editing of the window_to_front plugin's main.dart file

The plugin itself doesn't have a `main.dart` file, only its nested example project does.

@domesticmouse Perhaps the codelab should include changing that file even though it's not used, just to avoid this potential confusion?

> I'm getting this issue in that file

What's the context where you are getting that error? You shouldn't ever need to build that file in the codelab.

**Comment by Seanmyr** [comment]
@stuartmorgan well I wasn't trying to build the plugin.  I had performed all the things in step 6 of that codelabs down to where I needed to rerun the main app that I making.  When I tried to run that app to test everything I've done so far I got the following error message...

`C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\include\memory(3423,35): error C2512: 'window_to_front::WindowToFrontPlugin::WindowToFrontPlugin': no appropriate default constructor available [C:\Projects\github_client\build\windows\plugins\window_to_front\window_to_front_plugin.vcxproj]
`
When I went back to the window_to_front plugin code I noticed eslint giving me the error about the getPlatformVersion method.  So I figured that because that eslint error was there the plugin didn't fully build correctly when I tried to build/run the main app.  However if that's not the case then can someone tell me what the problem is with error I posted above that came from trying to build/run the main flutter github app that I'm building in this codelab?

**Comment by stuartmorgan** [comment]
That's unrelated, but it looks like it's an actual bug in the codelab.

@domesticmouse This line looks like it should be passing the registrar, but isn't:
```
  auto plugin = std::make_unique<WindowToFrontPlugin>();
```

**Comment by Seanmyr** [comment]
@stuartmorgan thanks for the assist!  I passed the registrar in that line you mentioned and it seems to have worked.

**Comment by Seanmyr** [comment]
@stuartmorgan then again I may have spoke too soon.  I was able to run the main flutter github app but as soon as I clicked on the login to github button to test it all out I got an error.  At this time I can only assume the error still has to do with the window_to_front plugin code.  because before trying to implement that part I was able to login to github through the app.  Also, the error mentions the activate() method from that plugin...

`The following UnimplementedError was thrown building GithubLoginWidget(dirty, state: _GithubLoginState#20044):
activate() has not been implemented`

Any ideas on this one?

**Comment by Seanmyr** [comment]
Can anyone help me with the following error I'm getting, still on step 6 of the flutter github codelab.  I'm at the very end of that step where I try out the part of logging in to Github and then when it's done logging in the app window comes to the front again.  Even though the error happens it does appear to actually go through the logging in to Github.  So it does appear to have something to do with the window_to_front plugin...

`The following UnimplementedError was thrown building GithubLoginWidget(dirty, state: _GithubLoginState#20044): activate() has not been implemented`

**Comment by domesticmouse** [comment]
@Seanmyr please see https://github.com/domesticmouse/codelabs/tree/github-client-fix-windows-window_to_front for a fix to get `window_to_front` working on Windows.
