### ISSUE TITLE
Any plan for Windows UWP support in the future?

### ISSUE THREAD

**Issue by luksireiku** [flutter/flutter#10881]
I'm sorry if it's not the place for asking, I couldn't find anything about it anywhere.

**Comment by eseidelGoogle** [comment]
Currently our project is focused on Android and iOS deployment targets.
https://flutter.io/faq/#what-devices-and-os-versions-does-flutter-run-on

It's certainly possible to port Flutter's runtime to UWP: https://github.com/flutter/engine/wiki/Porting-Flutter's-Engine
however we've not had very many requests for that.  Someone could certainly fork flutter/engine and do so themselves if they desired.

**Comment by semiautomatix** [comment]
React Native provides this option. Best to stick with that platform until a definitive development path and platform is available.

**Comment by weitzhandler** [comment]
I'd immigrate using Flutter when it supports UWP/Windows, and WASM.

**Comment by WesleyKhoiVo** [comment]
#30726

**Comment by WesleyKhoiVo** [comment]
There is a new update about flutter UWP: https://github.com/flutter/flutter/wiki/Desktop-shells

**Comment by WesleyKhoiVo** [comment]
@eseidelGoogle Can you re-open this issue?

**Comment by eseidelGoogle** [comment]
I believe https://github.com/flutter/flutter/issues/14967 is currently tracking.

**Comment by fisforfaheem** [comment]
Yes they should...its almost 2 years now :(
