### ISSUE TITLE
[windows] Mactype causes Flutter Windows apps to appear blurry

### ISSUE THREAD

**Issue by iiijam** [flutter/flutter#108873]
As the title, my flutter application is blurry on first run, where first run means running again long after closing a flutter application (usually several hours) and behaves as blurry as the application in debug mode, but this is the release version built with flutter build windows

**Expected results:** 
<img width="332" alt="image" src="https://user-images.githubusercontent.com/16839488/182592155-c63834ee-20fe-4732-8b67-c5cfdd4b411d.png">

**Actual results:** 
<img width="366" alt="image" src="https://user-images.githubusercontent.com/16839488/182592197-99a5dd36-7b32-4067-919b-4c69582b1669.png">

<details>
<summary>Code sample</summary>

here is my app: https://github.com/iiijam/ice_live_viewer

</details>

<details>
  <summary>Logs</summary>

```
[√] Flutter (Channel stable, 3.0.5, on Microsoft Windows [Version 10.0.22000.795], locale zh-CN)
    • Flutter version 3.0.5 at C:\Users\
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (3 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    • VS Code at C:\Users\
    • Flutter extension version 3.46.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22000.795]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 103.0.5060.134
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 103.0.1264.77

[√] HTTP Host Availability
    • All required HTTP hosts are available

```

**Comment by maheshmnj** [comment]
Hi @iiijam, thanks for filing the issue. Is this issue in debug or release mode or both?
I verified in debug mode and it seems to render fine for me on the first run and the consecutive runs.
 
![image](https://user-images.githubusercontent.com/31410839/182607163-445d2b6f-95b3-475b-9b4e-59dfd8f06f7b.png)

<details>
<summary>flutter doctor -v (windows)</summary>

```
[√] Flutter (Channel stable, 3.0.5, on Microsoft Windows [Version 10.0.19044.1826], locale en-IN)
    • Flutter version 3.0.5 at C:\flutter_sdk\stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (6 days ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\mahesh\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31727.386
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] VS Code (version 1.69.0)
    • VS Code at C:\Users\mahesh\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.44.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19044.1826]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 103.0.5060.114
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 100.0.1185.50

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by iiijam** [comment]
thanks for the test, This exists in both debug and release mode, and occurs more frequently (almost every time) in debug mode.

To make sure it wasn't due to my code, I did the following:

1.Run `flutter create debug_example`

2.Use the generated code and run in debug mode:
<img width="1183" alt="image" src="https://user-images.githubusercontent.com/16839488/182755810-4139a76d-221d-41b7-b58a-9880332076e9.png">

3.Go to `"...\debug_example\build\windows\runner\Debug"` then run `debug_example.exe`:
<img width="1257" alt="image" src="https://user-images.githubusercontent.com/16839488/182755964-3fdf4c03-0b6b-48cc-9226-44fd8c8e8064.png">

4.Run `flutter build windows`, then go to`.\debug_example\build\windows\runner\Release` and run the app:
<img width="983" alt="image" src="https://user-images.githubusercontent.com/16839488/182756232-0c0c7efe-6583-4deb-be60-bf6f7fb1e378.png">

5.Run it again:
<img width="1233" alt="image" src="https://user-images.githubusercontent.com/16839488/182756902-fc7ccd02-33c6-4655-a3f7-684e47c20b13.png">

**Comment by maheshmnj** [comment]
Thanks for the clarification @iiijam, provided that this issue occurs when running [macType](https://github.com/snowie2000/mactype), Probably this is a bug in macType that flutter doesn't control. So I would suggest filing the issue in its dedicated repo. Closing as this is not related to flutter in case you disagree feel free to write in the comments and we will reopen it.

Thank you.
