### ISSUE TITLE
Issue from website page Search: documents about flutter_markdown are 404

### ISSUE THREAD

**Issue by filiph** [flutter/flutter#10898]
From URL: https://flutter.io/search.md

Repro:
* Try to search for `markdown` from anywhere on the flutter.io site
* Click at any of the provided links

Expected: land on documentation
Actual: 404 Page (e.g. https://docs.flutter.io/flutter/flutter_markdown/Markdown-class.html)

**Comment by eseidelGoogle** [comment]
@Hixie is flutter_markdown still a supported part of our offering?  Should we remove it from flutter/flutter_markdown as well as from our docs?

**Comment by Hixie** [comment]
Those documents are long gone, I don't know why Google Search hasn't removed them from its index yet.

Markdown is now a separate package: https://pub.dartlang.org/packages/flutter_markdown

**Comment by filiph** [comment]
Does anyone have Google [Search Console](https://www.google.com/webmasters/tools/home?hl=en) (aka Webmaster Tools) access for flutter.io? I think you can manually ask for de-indexing there.

`sitemap.xml` also works, but we'd have to make sure it's complete.

**Comment by filiph** [comment]
Also, if we know about swaths of stuff that recently moved, we should probably do 301 redirects. It's easy enough with firebase.

**Comment by Hixie** [comment]
cc @sethladd

**Comment by sethladd** [comment]
@filiph please stop by my desk and teach me the magic of de-indexing. :) I'll also share the access with you.

To setup the firebase redirects for API docs, please send over a PR for this file: https://github.com/flutter/flutter/blob/master/dev/docs/firebase.json

Regardless, I don't think dartdocs.org can build API docs for packages that rely on Flutter , so flutter_markdown API docs aren't generated or hosted anywhere yet. I think @mit-mit has a plan for that, though.

**Comment by mit-mit** [comment]
Yup, dartdocs issue is https://github.com/flutter/flutter/issues/9796 with the underlying issue being https://github.com/flutter/flutter/issues/10015. Note that is working in most cases now; above bugs will get it working for all Flutter packages.

**Comment by zoechi** [comment]
This issue looks stale.
