### ISSUE TITLE
Improve canFlex Error Message

### ISSUE THREAD

**Issue by afandria** [flutter/flutter#1089]
The current message is:

```
The following exception was raised during performLayout():
'packages/flutter/src/rendering/flex.dart': Failed assertion: line 355: 'canFlex && "See https://flutter.github.io/layout/#flex" is String' is not true.
```

The link goes into the background of flex and how it works, but it would be more helpful if we were informed of which Flex widget in our code had this problem.

**Comment by Hixie** [comment]
The ownership chain should be in the logs already. Can you paste more of the output? (From the "----" line to the third line of the stack trace?)

**Comment by afandria** [comment]
I see this, which is related to the Render Objects, not the Widget tree.

Longer stack trace
```
-- EXCEPTION --
The following exception was raised during performLayout():
'packages/flutter/src/rendering/flex.dart': Failed assertion: line 355: 'canFlex && "See https://flutter.github.io/layout/#flex" is String' is not true.
Stack trace:
#0      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:27)
#1      RenderFlex.performLayout (packages/flutter/src/rendering/flex.dart:355)
#2      RenderObject.layout (packages/flutter/src/rendering/object.dart:719)
#3      RenderFlex.performLayout (packages/flutter/src/rendering/flex.dart:380)
#4      RenderObject.layout (packages/flutter/src/rendering/object.dart:719)
#5      RenderFlex.performLayout (packages/flutter/src/rendering/flex.dart:430)
#6      RenderObject._layoutWithoutResize (packages/flutter/src/rendering/object.dart:626)
#7      RenderObject.flushLayout.<anonymous closure> (packages/flutter/src/rendering/object.dart:604)
#8      List.forEach (dart:core-patch/growable_array.dart:233)
#9      RenderObject.flushLayout (packages/flutter/src/rendering/object.dart:602)
#10     FlutterBinding.beginFrame (packages/flutter/src/rendering/binding.dart:265)
#11     WidgetFlutterBinding.beginFrame (packages/flutter/src/widgets/binding.dart:37)
#12     FlutterBinding._handlePersistentFrameCallback (packages/flutter/src/rendering/binding.dart:260)
#13     Scheduler.invokeFrameCallback (packages/flutter/src/scheduler/scheduler.dart:263)
#14     Scheduler.handleBeginFrame (packages/flutter/src/scheduler/scheduler.dart:240)
#15     _beginFrame (file:///home/travis/build/flutter/buildbot/src/out/android_Release/gen/sky/bindings/Customhooks.dart:48)
```

**Comment by Hixie** [comment]
Maybe it's below the stack trace? I could have sworn we put the ownership chain for the widget that spawned the render object somewhere in the logs.

**Comment by afandria** [comment]
This stack trace was generated about 3 weeks ago, so it is possible that things have changed in that time. I'll let you know how it looks once I get a fresh one. I'll update Flutter too.

**Comment by Hixie** [comment]
I just tried to reproduce this and just after the stack trace it says:

```
The following RenderObject was being processed when the exception was fired:
RenderFlex relayoutSubtreeRoot=up3 NEEDS-LAYOUT
That RenderObject had the following owner:
Row ← Row ← DefaultTextStyle ← Padding ← ⋯
```

The ownership chain was previously a bit short for this specific case (it gave no parent, so in this case it would just say `Row`), but I'll submit a patch to make it look like the above (with 3 ancestors listed).

I'm not sure what more information we can include. Any suggestions?

**Comment by afandria** [comment]
Showing a few ancestors like that would help a lot with debugging. Would it be difficult to show the full ancestor chain? While it might get cluttered, it should provide enough to completely identify the faulty component.

In terms of extra information, each component's key (if available) can also be printed with the owner chain.

**Comment by Hixie** [comment]
Keys, if available, are included already, I believe.

We can show an arbitrary number of ancestors N, but the way this is written now, we pay an O(N) cost for every render object every time the object is created or updated, which is quite often. We could certainly change how this is done so that we only pay the cost when we need it, though it would change the rendering/widget boundary a bit.

**Comment by afandria** [comment]
Oh, I see. Let's leave it at 3 and see how it goes.

**Comment by Hixie** [comment]
Ok. If you run into this and find that 4 elements in the chain isn't enough, please do not hesitate to file a new bug. I have an idea for how to refactor this so that it gives the complete chain each time.
