### ISSUE TITLE
Item separators for `PlatformMenuBar`

### ISSUE THREAD

**Issue by GroovinChip** [flutter/flutter#108988]
## Use case

Native macOS applications that utilize the menu bar generally group similar items in a menu with horizontal line separators. It would be quite useful to be able to do this in Flutter apps with `PlatformMenuBar`.

Example:
![image](https://user-images.githubusercontent.com/4250470/182914652-9e9d9907-0708-497a-9b4b-36cd7b3c71d4.png)

## Proposal

I propose adding a new `PlatformProvidedMenuItemType` called `PlatformProvidedMenuItemType.separator`, which would create the desired separator. This way, developers can make use of the `PlatformProvidedMenuItem.hasMenu` call.

**Comment by stuartmorgan** [comment]
Is there a limitation that prevents [PlatformMenuItemGroup](https://api.flutter.dev/flutter/widgets/PlatformMenuItemGroup-class.html) from addressing this use case?

**Comment by GroovinChip** [comment]
Actually that does the job perfectly. Thanks @stuartmorgan!
