### ISSUE TITLE
[tool_crash] ProcessException: Operation not permitted Command: /Users/mohameedalarade/Developer/src/flutter/fity-ios/android/gradlew, OS error code: 1

### ISSUE THREAD

**Issue by 9mtm** [flutter/flutter#108970]
## Command
```
flutter build apk --target-platform android-arm,android-arm64,android-x64 --split-per-abi
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ProcessException: Operation not permitted Command: /Users/mohameedalarade/Developer/src/flutter/fity-ios/android/gradlew, OS error code: 1
```

```
```
[✓] Flutter (Channel stable, 1.22.6, on macOS 12.5 21G72 darwin-x64, locale en-US)
    • Flutter version 1.22.6 at /Users/mohameedalarade/Developer/src/flutter
    • Framework revision 9b2d32b605 (1 year, 6 months ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/mohameedalarade/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.4.1, Build version 13F100
    • CocoaPods version 1.11.3

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Connected device (2 available)
    • Nokia 5 4 (mobile) • 192.168.0.17:5555                                  • android-arm64 • Android 11 (API 30)
    • Nokia 5 4 (mobile) • adb-G151768000001835-NsqV2t._adb-tls-connect._tcp. • android-arm64 • Android 11 (API 30)
    ! Error: MTM 11 Pro is not connected. Xcode will continue when MTM 11 Pro is connected. (code -13)

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: null
**Version**: 1.3.0
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: null
**Creation framework version**: null
### Plugins
android_intent-0.3.7+7
device_info-1.0.0
firebase_auth-0.18.1+2
firebase_auth_web-0.3.1+1
firebase_core-0.5.0+1
firebase_core_web-0.2.1
firebase_messaging-7.0.3
flutter_facebook_login-3.0.0
flutter_inappwebview-4.0.0+4
flutter_local_notifications-4.0.1+2
flutter_plugin_android_lifecycle-1.0.11
fluttertoast-7.1.8
geolocator-6.2.1
geolocator_web-1.0.1
google_map_location_picker-4.1.6
google_maps_flutter-1.2.0
google_sign_in-4.5.9
google_sign_in_web-0.9.2
health-3.0.3
location-3.0.2
location_web-1.0.1
package_info-0.4.3+4
path_provider-1.6.28
path_provider_linux-0.0.1+2
path_provider_macos-0.0.4+8
path_provider_windows-0.0.4+3
permission_handler-5.1.0+2
qr_code_scanner-0.3.5
screen-0.0.5
searchable_dropdown-1.1.3
shared_preferences-0.5.12+4
shared_preferences_linux-0.0.2+4
shared_preferences_macos-0.0.1+11
shared_preferences_web-0.1.2+7
shared_preferences_windows-0.0.2+3
sqflite-1.3.2+4
stripe_payment-1.0.11
url_launcher-5.7.7
url_launcher_linux-0.0.1+4
url_launcher_macos-0.0.1+9
url_launcher_web-0.1.5+3
url_launcher_windows-0.0.1+3
video_player-0.10.12+5
video_player_web-0.1.4+1
wakelock-0.1.4+2
webview_flutter-0.3.24

**Comment by danagbemava-nc** [comment]
Hi @9mtm, you are on an older version of flutter. Kindly upgrade to the latest version of flutter. This issue was reported in https://github.com/flutter/flutter/issues/50880 and has since been fixed. 

Closing this as it has already been fixed. 

If you still experience this issue after upgrading to the latest version of flutter, kindly leave a report below. 

Thank you

**Comment by 9mtm** [comment]
Hey thank you, I can't actually update my flutter cause my application Depends now on 1.22.0, I think I can upgrade it after one month , and also I have windows it's work on windows perfectly.. only on MacBook not.
