### ISSUE TITLE
[Impeller] Metal Tests on M1 Mac don't run as expected.

### ISSUE THREAD

**Issue by betrevisan** [flutter/flutter#108996]
I am trying to run the Impeller unittests using a Mac but the tests do not seem to behave as expected in Metal. After compiling the Impeller playground, all of the unittests show up as blank fuchsia screen. However. this is not the case when running the tests in OpenGL, which executes the tests normally. 

For example, below is what I get when trying to render a cube in Metal.
<img width="1023" alt="Screen Shot 2022-08-04 at 1 11 11 PM" src="https://user-images.githubusercontent.com/43152751/182955433-ffb5247d-86ac-4a79-930e-77129d878380.png">

Now, this is what I get when trying to render the same cube in OpenGL.
<img width="1019" alt="Screen Shot 2022-08-04 at 1 11 27 PM" src="https://user-images.githubusercontent.com/43152751/182955444-b87db358-f93a-47b2-a3bc-c4a3578df0db.png">

For additional context, here is a frame capture of the problem.
<img width="1399" alt="Screen Shot 2022-08-04 at 1 35 35 PM" src="https://user-images.githubusercontent.com/43152751/182955532-05e97732-26bd-4fe2-9059-c33b2fe8586d.png">

**Comment by jonahwilliams** [comment]
I can confirm this happens to me as well. Both @betrevisan and I are using M1 macs which is probably related

**Comment by chinmaygarde** [comment]
This is an M1 Mac issue. Impeller assumes A series GPUs on iOS only (ToMTLStorageMode and ToMTLResourceOptions in `allocator_mtl`). Its a quick fix.
