### ISSUE TITLE
Draggable scrollable controller is already attached to a sheet

### ISSUE THREAD

**Issue by devnoaman** [flutter/flutter#108955]
## error
i had added nested navigation and i get this error when i push the DragableScrolableSheet .

```
Exception has occurred.
_AssertionError ('package:flutter/src/widgets/draggable_scrollable_sheet.dart': Failed assertion: line 185 pos 12: '_attachedController == null': Draggable scrollable controller is already attached to a sheet.)
```

**Comment by huycozy** [comment]
Hi @devnoaman, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this. Also, please provide the output of `flutter doctor -v` as well.
Thank you!
