### ISSUE TITLE
Add support for something like testID /testKeyId for widgets

### ISSUE THREAD

**Issue by MisterLight** [flutter/flutter#108975]
In react application you can specify a data-testId attribute to identify a component when performing unit/component tests.

Just like that: 
"<MyComponent data-testId="myComponent" //>"

Then when I create a unit test in jest I can get the component directly from that data-testId and be happy.

Working with flutter when I want to find a element in a test the most used ways that I do is find it through the text (which is totally a bad practice because thats a thing that change a lot in the future) or the type of component, thats turn to be a mess in certain situations..

Why not create a key-id, a property linked to  the widget component that can be used by the test to identify a widget or multiples widget with same test-id. Just like that:
 
myComponent extends StatelessWidget {
  myComponent() : super (testId:'myComponent')
}

In test you could find it with something like that:

find.byTestId('myComponent');

**Comment by navaronbracke** [comment]
This is exactly what `Key` is for?

https://api.flutter.dev/flutter/foundation/Key-class.html
https://docs.flutter.dev/cookbook/testing/widget/finders#2-find-a-widget-with-a-specific-key

**Comment by MisterLight** [comment]
I always though that Key is internally used by flutter to check the state of a widget,  a testID should not have any purpose other than be used for locate a component in the render tree.

**Comment by huycozy** [comment]
Hi @MisterLight 
I have the same thought with @navaronbracke about this, you can use a Key to find a widget in unit tests.
If you still believe this issue is an appropriate feature request, please tell us the problem you are running into when using Key that led to you wanting a new feature. Thanks!
