### ISSUE TITLE
Linking .dll with flutter plugin - C++

### ISSUE THREAD

**Issue by gredajustyna** [flutter/flutter#108962]
Hello. I have some issue with linking an external library (specifically , libsodium) to flutter plugin. My plugin is a multiplatform one, using Method Channel to connect with native code. I managed to connect the libsodium to native code in Kotlin and Swift. However, I am struggling to do that in C++. My code has been tested as a solo project in VS code and  building it using `g++ .\sodtest.cpp -o sodtest -LC:\\path\\to\\folder -lsodium` worked like a charm. In Android Studio project I don't know how to set the library path or use the `-lsodium` function. Should it be done in `CMakeLists.txt`? I would appreciate some help. My project structure (only the windows part):

```
windows
│   project_name.cpp
│   project_name.h   
│   project_name_c_api.cpp
│   CMakeLists.txt
│   libsodium.dll
│   libsodium.lib
│   sodium.h
└───include
│   └───project_name
│       │    project_name_c_api.cpp
└───sodium
    │   *This folder contains all header files of sodium library*
```

The `sodium.h` file is the main header file of the library. I include the header files in my `.cpp` file using:
```
#include "sodium/crypto_sign.h"
#include "sodium.h"
```

I am aware this is not enough. My Android Studio error is `LNK2019: unresolved external symbol` when i try to use library functions. So, again, what is the proper way to link the `.dll` library with headers to a flutter plugin?

**Comment by stuartmorgan** [comment]
> Should it be done in `CMakeLists.txt`?

Yes, `CMakeLists.txt` is the build specification file for Windows plugins. Standard resources about using CMake (CMake docs, StackOverflow, etc.) would be the best place to learn how to add build rules such as linker commands there.
