### ISSUE TITLE
[image_picker][iOS] Occasional crash, maybe due to multiple modal viewControllers being presented

### ISSUE THREAD

**Issue by ChristianEdwardPadilla** [flutter/flutter#108900]
Occasionally (hundreds of crashes per month from userbase of millions) seeing the following error message:

```
Application tried to present modally a view controller <PHPickerViewController: 0x157b805f0> that is already being presented by <FlutterViewController: 0x111824c00>.
```

Stacktrace:

```
Stack Trace:
0x0000000180c7d0fc ( CoreFoundation + 0x000990fc ) __exceptionPreprocess
0x00000001994cdd60 ( libobjc.A.dylib + 0x00015d60 ) objc_exception_throw
0x0000000183561984 ( UIKitCore + 0x004d4984 ) -[UIViewController _presentViewController:withAnimationController:completion:]
0x000000018334c3f4 ( UIKitCore + 0x002bf3f4 ) __63-[UIViewController _presentViewController:animated:completion:]_block_invoke
0x00000001832fca34 ( UIKitCore + 0x0026fa34 ) -[_UIViewControllerTransitionCoordinator _applyBlocks:releaseBlocks:]
0x000000018353209c ( UIKitCore + 0x004a509c ) -[_UIViewControllerTransitionContext _runAlongsideCompletions]
0x00000001832cdf24 ( UIKitCore + 0x00240f24 ) -[_UIViewControllerTransitionContext completeTransition:]
0x00000001834e0994 ( UIKitCore + 0x00453994 ) -[UITransitionView notifyDidCompleteTransition:]
0x000000018333718c ( UIKitCore + 0x002aa18c ) -[UITransitionView _didCompleteTransition:]
0x0000000183351dcc ( UIKitCore + 0x002c4dcc ) -[UIViewAnimationBlockDelegate _didEndBlockAnimation:finished:context:]
0x000000018321d2e4 ( UIKitCore + 0x001902e4 ) -[UIViewAnimationState sendDelegateAnimationDidStop:finished:]
0x0000000183231a58 ( UIKitCore + 0x001a4a58 ) -[UIViewAnimationState animationDidStop:finished:]
0x0000000183231bc0 ( UIKitCore + 0x001a4bc0 ) -[UIViewAnimationState animationDidStop:finished:]
0x0000000184a06a04 ( QuartzCore + 0x000c8a04 ) CA::Layer::run_animation_callbacks(void*)
0x00000001808ef66c ( libdispatch.dylib + 0x0000466c ) _dispatch_client_callout
0x00000001808fdb6c ( libdispatch.dylib + 0x00012b6c ) _dispatch_main_queue_callback_4CF
0x0000000180c35d80 ( CoreFoundation + 0x00051d80 ) __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
0x0000000180beff58 ( CoreFoundation + 0x0000bf58 ) __CFRunLoopRun
0x0000000180c03464 ( CoreFoundation + 0x0001f464 ) CFRunLoopRunSpecific
0x000000019c7a7388 ( GraphicsServices + 0x00001388 ) GSEventRunModal
0x00000001835a65cc ( UIKitCore + 0x005195cc ) -[UIApplication _run]
0x0000000183324f70 ( UIKitCore + 0x00297f70 ) UIApplicationMain
0x00000001023ccbf0 ( ios_prod_global - ./nbu/paisa/gpay/ios/main.m:73 ) main
0x0000000108e25aa0 (  + 0x108e25aa0 )
```

We know image_picker is the culprit because it is the only use of `PHPickerViewController` in this app.

## Steps to Reproduce

Unknown exactly what causes this crash or how to reproduce.

**Expected results:** image_picker works as expected
**Actual results:** occasional crashes

## Suggested fix:

Based on https://stackoverflow.com/questions/7429014/application-tried-to-present-modally-an-active-controller, we might want to have `!viewController.presentingViewController` be true before calling `[[self viewControllerWithWindow:nil] presentViewController:pickerViewController];` here (and maybe elsewhere in the file): https://github.com/flutter/plugins/blob/main/packages/image_picker/image_picker_ios/ios/Classes/FLTImagePickerPlugin.m#L426

**Comment by huycozy** [comment]
Hi @ChristianEdwardPadilla 
Which `image_picker` version are you using? 
Please provide affected device information and the output of `flutter doctor -v`.
Thanks!

**Comment by ChristianEdwardPadilla** [comment]
Sorry for the late response. This is still occurring occasionally (1k/day) for us.

versions used:
`image_picker: 1.0.2`
`image_picker_ios: 0.8.8+1`

Seems we could add a check for an already presenting view controller here:
https://github.com/flutter/plugins/blob/557d3284ac9dda32a1106bb75be8a23bdccd2f96/packages/image_picker/image_picker_ios/ios/Classes/FLTImagePickerPlugin.m#L442

Seems a check like this could solve the issue:
`(!pickerViewController.presentingViewController)`

**Comment by huycozy** [comment]
As the reference source code, it looks like this is an OS-specific issue. 

```objective-c
- (void)showPhotoLibraryWithPHPicker:(PHPickerViewController *)pickerViewController
    API_AVAILABLE(ios(14)) {
  [[self viewControllerWithWindow:nil] presentViewController:pickerViewController
                                                    animated:YES
                                                  completion:nil];
}
```

Labeling the issue for more insights. Please also provide the list of affected device info and the percentage occurrence of the crash if any. Thanks!

**Comment by ChristianEdwardPadilla** [comment]
Looks like iOS-only, all devices, iOS 16.1+ are affected. I don't know the percentage occurrence but this is the largest crash cluster for this version of GPay (b/305620691).

**Comment by stuartmorgan** [comment]
I can reproduce this easily by double-calling a picker method when no permission selection has been made yet. There are two layers of bugs here:
- we should be cancelling when there's an in-progress call since we don't currently stack responses yet; currently one one of our entry points is doing that.
- we have a singleton picker, which is causing this to crash instead of have no return for one of the calls (which is normally what the above would do).
