### ISSUE TITLE
API to get licenses to show

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#109]
<a href="https://github.com/Hixie"><img src="https://avatars.githubusercontent.com/u/551196?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Hixie](https://github.com/Hixie)**
_Monday Jul 20, 2015 at 20:33 GMT_
_Originally opened as https://github.com/flutter/engine/issues/153_

----

_From @Hixie on March 2, 2015 21:23_

We should have an API that returns all the licenses we're supposed to show in an app's about screen, since the runtime uses some libraries that require notice.

_Copied from original issue: domokit/mojo#56_

**Comment by Hixie** [comment]
- [ ] engine should export a String that contains all the licenses that are relevant to the engine.
- [ ] each library in the framework should do something similar, maybe concatenating its list with the previous layer's list.
- [ ] stocks app should demonstrate how to use this resulting String to show the licenses.

**Comment by Hixie** [comment]
Maybe the engine should expose a list of licenses it needs to show, and some low level of the framework should have an API that you can add licenses to, and that layer automatically adds the engine's, and other layers can add whatever they need, and then at the widgets layer we can have a widget that shows the licenses along with a "Made with Flutter" stamp.

**Comment by Hixie** [comment]
Maybe use `gn desk` to figure out what files to examine in the first place.

**Comment by abarth** [comment]
`gn desc`

**Comment by eseidelGoogle** [comment]
@Hixie is this something we can easily get out of the way (or at least plumb basic support for?)  customer:fast would like to check off this checkbox for their launch.

**Comment by Hixie** [comment]
It's on my list after data tables.

**Comment by eseidelGoogle** [comment]
Curious if we have any news on this? I know some work has gone in.

**Comment by Hixie** [comment]
It's ongoing.

**Comment by Hixie** [comment]
The bulk of this is now done. Remaining issues are https://github.com/flutter/flutter/issues/5052 and https://github.com/flutter/flutter/issues/5031 but neither is a blocker to launch.
