### ISSUE TITLE
Task step is failing with no stdout link, but top of page shows end of stdout log

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#109000]
`Linux_samsung_a02 openpay_benchmarks__scroll_perf` is consistently failing.
https://ci.chromium.org/ui/p/flutter/builders/staging/Linux_samsung_a02%20openpay_benchmarks__scroll_perf/307/overview

The end of the log output is in the red box at the top, but the failing step only has execution details, not a link to stdout to see the full log.

![Screen Shot 2022-08-04 at 3 34 21 PM](https://user-images.githubusercontent.com/682784/182964101-027d5427-a46c-440d-ab69-9d39b74569c1.png)

**Comment by keyonghan** [comment]
This is WAI: b/231460791
