### ISSUE TITLE
Tabbar inside IndexedStack shows blankPage at first run

### ISSUE THREAD

**Issue by HekmatFavid** [flutter/flutter#109083]
I'm using bottomNavigationBar for main page bottom tabs and IndexedStack to show screens in body. In one of this screens there is a TabBar and in first tab there is a widget using GridView.builder. 
When I run app and change bottom tab, nested tab that contains GridView shows blank page, but after changing nested tab content's of previous tab appears and firstly doesn't show on selected tab.
When I changing TabBarView with IndexedStack, this problem appear in bottom tabs and default selected tabs shows blank page and after changing tabs, contents appeared. 
This works properly in web mode using chrome or in debug mode in simulator or phone but problem appears in released apk.

Bug Video: https://drive.google.com/file/d/1leo3JbZdlZG6sZT0b6Njp98rGnSVZKwL/view?usp=sharing

**Comment by exaby73** [comment]
Hi @HekmatFavid, please provide a [minimal, reproducible example][1] and the output of `flutter doctor -v` as well as `flutter run -v`.

[1]: https://stackoverflow.com/help/minimal-reproducible-example

**Comment by HekmatFavid** [comment]
I changed nested TabBarView to IndexedStack and this solves the problem. I think TabBarView has some problems in production mode. Thank you @exaby73 for your attention.
