### ISSUE TITLE
The plugin needs to update CamcorderProfile

### ISSUE THREAD

**Issue by KomengTech** [flutter/flutter#109019]
Instead of CamcorderProfile.get(int, int) to update to CamcorderProfile.getAll(String, int)

<img width="1209" alt="Screenshot 2022-08-05 at 12 41 14 PM" src="https://user-images.githubusercontent.com/26598827/183003165-9a9b9453-5df9-4c8f-aac7-173d033f519e.png">

**Comment by huycozy** [comment]
Hi @KomengTech
I see there's an open issue addressing the case you described #94999 and please also take a look at https://github.com/flutter/flutter/issues/94999#issuecomment-1168145391.
You can leave there your comment and react an upvote to the original comment will help to raise the issue.
Closing as a duplication, so please follow up on it for further updates.
