### ISSUE TITLE
autosubmit bot landed a PR after the label was removed

### ISSUE THREAD

**Issue by flar** [flutter/flutter#109004]
In https://github.com/flutter/engine/pull/35170 I added the autosubmit flag and then immediately removed it seconds later. The bot ended up submitting the PR anyway a couple of minutes after that exchange.

**Comment by keyonghan** [comment]
Seems the logic to validate existence of `autosubmit` label was removed accidentally when refactoring the validations (https://github.com/flutter/cocoon/pull/1891/files).

We need to add the validation back.

**Comment by flar** [comment]
Also of note, that PR is still marked as WIP. It was actually pretty much ready to submit anyway, but the autosubmit bot should probably not submit something with that label either?

**Comment by keyonghan** [comment]
> Also of note, that PR is still marked as WIP. It was actually pretty much ready to submit anyway, but the autosubmit bot should probably not submit something with that label either?

The bot recognize a draft PR, but does not check `WIP` label. I would suggest mark the PR as a draft PR is it is still WIP.
