### ISSUE TITLE
.ci.yaml has different Xcode versions in different properties

### ISSUE THREAD

**Issue by yusuf-goog** [flutter/flutter#109008]
he framework .ci.yaml has different Xcode versions in different properties
  mac_ios:
    properties:
      dependencies: >-
        [
          {"dependency": "xcode", "version": "13a233"},
...
        ]
...
      xcode: 13f17a

**Comment by yusuf-goog** [comment]
cc @jmagman

**Comment by jmagman** [comment]
Pulled my question from the PR: Is `version` in the dependency even being used?  All the tests were already using `13f17a`, I assume pulled from the `xcode` property.  Can we remove it?

**Comment by yusuf-goog** [comment]
cc @CaseyHillers

**Comment by ricardoamador** [comment]
Closing this as the versions have been pinned to the same version in the framework .ci.yaml.
