### ISSUE TITLE
Catalog SkSL loading benchmarks and determine how/when to turn down for impeller

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#109002]
Long term plans for the flutter engine involve removing the need to precompile shader warmup. This means that eventually we can fully turn down this functionality in the tooling and remove benchmarks from the devicelab. As a first step towards that, we should consider reducing the number of tests/shards devoted to SkSL benchmarking as impeller becomes more available.

**Comment by chinmaygarde** [comment]
xref https://github.com/flutter/flutter/issues/122207
