### ISSUE TITLE
[Impeller] Flickering at edges of embedded view while scrolling.

### ISSUE THREAD

**Issue by flar** [flutter/flutter#109007]
On a popular internal test app running under Impeller the edges of a Google Map platform view will cause flickering in the Flutter overlay while scrolling. The flickering lines always disappear when the scrolling stops even if the finger is still engaged on the screen so it likely is only happening during interpolated scroll positions (non-integer?). The flickering also only happens on the leading edge of the Map view so on the bottom edge while scrolling it down underneath the bottom nav bar and on the top edge when scrolling it up from underneath the same nav bar.

**Comment by jonahwilliams** [comment]
IIRC @cyanglaz had looked at something like this in that particular app a few months back, but we weren't able to repro it. I can definitely repro it easily though. I wonder if they had gotten the impeller flags mixed up?

**Comment by cyanglaz** [comment]
https://github.com/flutter/engine/pull/33262 was a potential fix for that issue with non-impeller.

With impeller, did you have to implement a new RTree to calculate the PlatformView Overlay rect? One of the reasons that such flickering can happen is that the PlatformView Overlay's rect is incorrect which causing the overlay not covering the entire rect that it suppose to cover, see: https://github.com/flutter/engine/blob/main/shell/platform/darwin/ios/framework/Source/FlutterPlatformViews.mm#L544

@flar If I want to reproduce this, do I just run the sample app with latest engine/main and impeller on?

**Comment by cyanglaz** [comment]
> scrolling in the example app near ToT with --enable impeller reproduces it for me, though it is much more obvious in debug/profile mode than in release mode

Just to clarify, this isn't the same issue (although maybe related) that we talked about on discord right? This is more about PlatformView flickering and the issue on discord was more about frame freeze/lag.

**Comment by jonahwilliams** [comment]
correct, this is not about the frame freeze/lag

**Comment by flar** [comment]
A single horizontal pixel line located right around the bottom of the embedded view flashes white, but only while a scroll is happening. If you pause your finger it goes away, or if you lift your finger it also goes away. I've never been able to get it to stay visible statically, it only happens during the movement of a scroll.

**Comment by flar** [comment]
Also, if I remove the clipRect(kDifference) it goes away. It would appear that Impeller and Skia have different concepts on how to apply that clip. I'm guessing the fact that it only happens during the movement of scrolling that it has to do with how they deal with sub-pixel accuracy on the differende-style-clip.

**Comment by flar** [comment]
The clipRect is a non-AA clip rect, but I don't know if Impeller implements non-AA rendering even for clips. @bdero?

**Comment by flar** [comment]
Another thought is that since the view looks correct when the motion stops, perhaps we are just seeing "screen tearing" as the multiple layers are submitted to the compositing engine and we exceed a frame interval with all of the work being done?

**Comment by chinmaygarde** [comment]
@cyanglaz Are you still making progress on this? Feel free to un-assign yourself if not.

**Comment by cyanglaz** [comment]
> @cyanglaz Are you still making progress on this? Feel free to un-assign yourself if not.

Got distracted to other things, un-assign myself.
