### ISSUE TITLE
typographic: requesting a solution for subscripts/superscripts in richtext

### ISSUE THREAD

**Issue by namiwang** [flutter/flutter#10906]
For a content-oriented app we're working on, we feel that flutter is lacking a solution for <sub>subscripts</sub> and <sup>superscripts</sup> in paragraphs. (besides many other typographic features it lacks :/)

I believe the coordinate elements in HTML are \<sub\> and \<sup\>.

Currently we're trying to implement those effects via `Wrap` and `Positioned`, which involved a number of hackings. It does not feel good.

(We've even considered crafting a special font which contains every character being smaller and positioned in left-top)

Feel free to close/move the issue if you guys think this is an engine-wise one.

**Comment by eseidelGoogle** [comment]
We're working on re-writing our text engine at the moment.  I suspect our current one may even support this and we just haven't exposed it.  @Hixie would know.  FYI @GaryQian

**Comment by nanowang** [comment]
Hooray! Mind to reveal some rough schedule?

**Comment by eseidelGoogle** [comment]
@nanowang we don't have any hard schedule.  https://github.com/flutter/flutter/issues/10476 is the bug to track if you'd like to follow along.

**Comment by namiwang** [comment]
@eseidelGoogle Hi! Since the new text renderer is already online, could you guys point out how could we implement subscripts/superscripts in richtext? Thanks!

**Comment by gorjan-mishevski** [comment]
Yeah, been trying to figure that myself. No luck so far. Some documentation would help a lot. 🍺

**Comment by JoernByteBau** [comment]
So, there is no way to type H2O or CO2 in a proper format right now?

**Comment by Hixie** [comment]
For those specific examples you can use the relevant Unicode characters.
For a generic solution, we don't currently have a way to control the vertical alignment of text spans; that's one of the bullet points in #224.

**Comment by marcmorente** [comment]
You can try with RichText widget and Transform.transalte widget:

    RichText(
      text: TextSpan(
        style: TextStyle(color: Colors.red, fontSize: 16),
        children: [
          TextSpan(
            text: 'Some text ',
          ),
          WidgetSpan(
            child: Transform.translate(
              offset: const Offset(0.0, 4.0),
              child: Text(
                'subscripts',
                style: TextStyle(fontSize: 11),
              ),
            ),
          ),
          WidgetSpan(
            child: Transform.translate(
              offset: const Offset(0.0, -7.0),
              child: Text(
                'supscripts',
                style: TextStyle(fontSize: 11),
              ),
            ),
          ),
          TextSpan(
            text: 'Some text ',
          ),
        ],
      ),
    );
`

**Comment by puntodamar** [comment]
>       WidgetSpan(
>         child: Transform.translate(
>           offset: const Offset(0.0, -7.0),
>           child: Text(
>             'supscripts',
>             style: TextStyle(fontSize: 11),
>           ),
>         ),
>       ),

this above solution doesnt work for a paragraph because it creates a small padding between the first and second line
![image](https://user-images.githubusercontent.com/10866321/97112291-070ddb00-1716-11eb-9ce5-bfe187179e37.png)

**Comment by AliYar-Khan** [comment]
> 
> 
> You can try with RichText widget and Transform.transalte widget:
> 
> ```
> RichText(
>   text: TextSpan(
>     style: TextStyle(color: Colors.red, fontSize: 16),
>     children: [
>       TextSpan(
>         text: 'Some text ',
>       ),
>       WidgetSpan(
>         child: Transform.translate(
>           offset: const Offset(0.0, 4.0),
>           child: Text(
>             'subscripts',
>             style: TextStyle(fontSize: 11),
>           ),
>         ),
>       ),
>       WidgetSpan(
>         child: Transform.translate(
>           offset: const Offset(0.0, -7.0),
>           child: Text(
>             'supscripts',
>             style: TextStyle(fontSize: 11),
>           ),
>         ),
>       ),
>       TextSpan(
>         text: 'Some text ',
>       ),
>     ],
>   ),
> );
> ```

The Best Solution I found. Thanks
