### ISSUE TITLE
In go_router package, CustomTransitionPage<T> should have have child field as optional

### ISSUE THREAD

**Issue by jascodes** [flutter/flutter#109084]
## Use case
In my screen pages where these is complicated enter and exit animations such as staggering etc, I sometime pass animation and secondaryAnimation. I understand passing child to transition builder is an optimisation but in the case stated above its should be nullable.
```
GoRoute(
  path: '/fade',
  pageBuilder: (context, state) => CustomTransitionPage<void>(
    key: state.pageKey,
    transitionsBuilder: (context, animation, secondaryAnimation, _) =>
        MyScreen(enterAnimation:animation, exitAnimation:secondaryAnimation);
  ),
),
```
#### Currrent Workaround
```
GoRoute(
  path: '/fade',
  child: Container(),
  pageBuilder: (context, state) => CustomTransitionPage<void>(
    key: state.pageKey,
    transitionsBuilder: (context, animation, secondaryAnimation, _) =>
        MyScreen(enterAnimation:animation, exitAnimation:secondaryAnimation);
  ),
),
```
## Proposal
CustomTransitionPage<T> should have have child field as optional.

**Comment by chunhtai** [comment]
The CustomTransitionPage matches the `PageRouteBuilder` API, if you want a more flexible Page class, you can write your own Page subclass. Closing as Won't fix.
