### ISSUE TITLE
Linux-15 has faulty disk and needs a replace

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#109055]
Linux-15 has been dead for >1 week: https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-linux-15, and is not sshable.

When manually rebooting from the lab, it shows
![image0 (1)](https://user-images.githubusercontent.com/54558023/183134723-6d222f28-3b17-40a3-b21c-720e9629b5eb.jpeg)

We need to replace this testbed when we have the new NUCs available.

**Comment by yusuf-goog** [comment]
ip of linux-15: ...161 (till DNS entry is updated, ticket created).

**Comment by yusuf-goog** [comment]
DNS: t/213375732

**Comment by yusuf-goog** [comment]
linux-15 is up and running.
