### ISSUE TITLE
Flutter Localization is not compatible with on-demand resources

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#10915]
I don't believe that iOS apps include all localizations by default, but maybe?  If they don't, we will want to be compatible with whatever on-demand system exists.
https://developer.apple.com/library/content/documentation/FileManagement/Conceptual/On_Demand_Resources_Guide/index.html#//apple_ref/doc/uid/TP40015083

FYI @cbracken

**Comment by HansMuller** [comment]
Localized Android apps are deployed from the play store bundled with the resources needed for all supported locales. See https://developer.android.com/distribute/best-practices/launch/localization-checklist.html

**Comment by cbracken** [comment]
As far as I'm aware iOS apps do include all locales by default. App Slicing is done by device architecture and resolution (for code/asset thinning), and based on docs and local testing (iOS 10.3.3) it doesn't appear they're using on-demand loading behind the scenes for locale data.

I can imagine for apps with heavy localized assets (e.g. maybe a localized PDF user guide, or a lot of graphics that include text) we'll definitely want to support on-demand loading, but it doesn't appear to be part of UIKit's i18n implementation.

**Comment by eseidelGoogle** [comment]
Sounds like we can close this. :)
