### ISSUE TITLE
Access disposed canvas in VM causes segfault

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#109180]
This code causes a segfault currently:

```dart
test('use canvas after endRecording', () {
  final PictureRecorder recorder = PictureRecorder();
  final Canvas canvas = Canvas(recorder);
  final Picture picture = recorder.endRecording();
  canvas.restore();
});
```

The final call to canvas.restore should be an error but not a crash.

@c-h-i-a-m-a-k-a-2 fyi

**Comment by dnfield** [comment]
I think this is a more general bug in the FFI dispatcher - we unconditionally call methods on receivers even if the receiver is nullptr.

**Comment by dnfield** [comment]
This happens for any object with a `dispose` method on it, for example if you call `dispose` twice, e.g.:

```dart
final SceneBuilder builder = SceneBuilder();
final Scene scene = builder.build();
scene.dispose();
scene.dispose(); // segfault
```

@dcharkes - I'm not quite sure how to fix this without help from the Dart team, I think we'd want this to throw a Dart exception (e..g `StateError('Object disposed')`).

**Comment by dcharkes** [comment]
Relevant code

```dart
@pragma('vm:entry-point')
class Scene extends NativeFieldWrapperClass1 {
  /// This class is created by the engine, and should not be instantiated
  /// or extended directly.
  ///
  /// To create a Scene object, use a [SceneBuilder].
  @pragma('vm:entry-point')
  Scene._();

  // ..

  /// Releases the resources used by this scene.
  ///
  /// After calling this function, the scene is cannot be used further.
  ///
  /// This can't be a leaf call because the native function calls Dart API
  /// (Dart_SetNativeInstanceField).
  @FfiNative<Void Function(Pointer<Void>)>('Scene::dispose')
  external void dispose();
}
```

```c++
void Scene::dispose() {
  layer_tree_.reset();
  ClearDartWrapper();
}
```

> calling a method on the receiver whether the receiver is nullptr or not

Easy fixes (that require fixes on every call site)

* Make a top level C function that takes the "receiver" as first argument for nullptr and then calls the method if not nullptr. If the method is supposed to be idempotent, we're done.
  * Return a boolean, and check the boolean in Dart to throw if it was called a second time.
* Check the native field in Dart for being a nullptr with `_getNativeField`.
* Add a boolean to the Dart class that keeps track of being disposed.

> If we have to guard all the callsites in Dart code that seems a bit error prone

I'll take a look at the design of the `NativeFieldWrapperClass`es and automatic unwrapping of native fields to `Pointer<Void>` if we can make a general solution. From a quick glance this stems from the fact that Dart is object oriented, C++ classes have a receiver as well, but that this automatic unwrapping is based on the C FFI which does not have a concept of receiver and null-pointer-exception. Having both Dart and C++ as OO languages and having the `@FfiNative`s on `NativeFieldWrapperClass1` be direct mappings between Dart methods and C++ methods gives the illusion this would cover object-oriented behavior, but instead we get simple C behavior: e.g. you pass a nullptr.

For reference, the pattern with C (not C++) code and disposing methods:

1. Dart class implements `Finalizable`, has a `Pointer<...> _nativeResource` and a boolean `_isDisposed`.
2. `dispose()` sets `_isDisposed` to true, and frees the resource
3. All dart methods manually check `_isDisposed` and throw a `StateError` before accessing the `_nativeResource`.

And this pattern can be extend with a `NativeFinalizer`, which is cancelled on `dispose()` and cleans up the `_nativeResource` if the users forget to call `dispose`.

This suffers from the same issue that all callsites need to implement this pattern. But the pattern is very explicit in Dart code, which it is not with `NativeFieldWrapperClass` and automatic receiver unwrapping.

**Comment by mkustermann** [comment]
It seems to me that the natural way of using `@FfiNative` instance methods is with a C++ peer pointer that is the receiver for the C++ method invocation. As such, it would make most sense that the desugaring of `@Ffinative` not only check that the native field (aka peer) was initialized but also check whether it has been cleared again, see [kernel_to_il.cc:kGetNativeField](https://github.com/dart-lang/sdk/blob/c34b72482e5a41c02eaf0760e41c960f6e0c46dd/runtime/vm/compiler/frontend/kernel_to_il.cc#L1606) which isn't checking that the loaded integer is non-0.

For parameters we may not necessarily do that, since the peer (even if 0) will be passed to C++ which will then use it (or not) and the error should happen when "dereferencing" it.

**Comment by dnfield** [comment]
I like @mkustermann's idea - I think if the VM threw a Dart exception of the native field is zero that would be fine.

**Comment by dcharkes** [comment]
@dnfield I landed a fix for https://github.com/dart-lang/sdk/issues/49620 last week. Could you double check this is the behavior you'd like?

**Comment by dnfield** [comment]
@dcharkes this is definitely an improvement - we now get output like this instead of a segfault:

```
00:02 +0 -1: loading /Users/dnfield/tmp/t/test/widget_test.dart [E]                                                                                                                                                                                                                                             
  Failed to load "/Users/dnfield/tmp/t/test/widget_test.dart": Bad state: Native field is nullptr.
  dart:ui                      Canvas.restore
  test/widget_test.dart 14:10  main
  

To run this test again: /Users/dnfield/src/flutter/flutter/bin/cache/dart-sdk/bin/dart test /Users/dnfield/tmp/t/test/widget_test.dart -p vm --plain-name 'loading /Users/dnfield/tmp/t/test/widget_test.dart'
00:02 +0 -1: Some tests failed.         
```

That said, I think this may still be confusing for users. Is there some way that dart:ui could override this message, or alternatively a longer more actionable message could be presented? 

For example, I think something like 

```
Bad state: A Dart object attempted to access a native peer, but the native peer has been collected.

This is usually the result of calling methods on a native-backed object when it is in a disposed state.
```

**Comment by mkustermann** [comment]
@dcharkes Could we update the error message to something like @dnfield suggested?

**Comment by dnfield** [comment]
Pre-emptively closing this as fixed by https://dart-review.googlesource.com/c/sdk/+/255680
