### ISSUE TITLE
Implement Mozart gesture arena on Fuchsia

### ISSUE THREAD

**Issue by alanlgardner** [flutter/flutter#10918]
Please.

**Comment by Hixie** [comment]
See https://github.com/flutter/flutter/issues/10443 for the cross-view hit-testing.

**Comment by alanlgardner** [comment]
Here is the API in Mozart:
https://fuchsia-review.googlesource.com/c/33525/

**Comment by Hixie** [comment]
I understand this is part of what @chinmaygarde is working on at the moment.

@chinmaygarde, let me know if you'd any help with this one, especially on the framework side (I am less sure what needs doing on the engine side).

**Comment by Hixie** [comment]
We are not actively working on this this week.

**Comment by Hixie** [comment]
My understanding is that we can't implement this yet because Mozart2 doesn't yet have the gesture arena backend we need. I am therefore removing the `customer: blocker` label. We will not be working on this until we hear that the ball is back in our court.

**Comment by Hixie** [comment]
cc @jaeheon

**Comment by jaeheon** [comment]
Funny timing. We do now have the gesture arena backend in Scenic, but we're not quite ready to integrate with Flutter's arena. A prereq is this PR:
https://github.com/flutter/engine/pull/28242

and once done, I'll cook up a design to have the flutter arena communicate with the PointerDelegate in PlatformView.

**Comment by Hixie** [comment]
@jaeheon Is this this still on the radar for Fuchsia?

**Comment by jaeheon** [comment]
With recent events, probably no longer.
