### ISSUE TITLE
[proposal] un-bundle material from flutter sdk an make it available as package

### ISSUE THREAD

**Issue by iapicca** [flutter/flutter#109145]
### Use case

- `material 3` and `material 2` coexistence through `opt-in` approach may be 
  - confusing  
  - have unwanted side effect (`material2` regressions and or technical debt)
  
  having 2 separate packages would solve that

```dart
 return MaterialApp(
    theme: ThemeData(useMaterial3: true),
    // ...
  );
```

-  `uses-material-design` seems a "non standard" approach compared to other packages 
(even bundled ones like `cupertino`)

```yaml
flutter:
  uses-material-design: true
```

- would make sense if [material.io](https://pub.dev/publishers/material.io) maintained it 
(possibly and eventually, but definitely not happening if it's just bundled in the sdk)

- a strength of `flutter` is the ease of implementation of "branding", but sometimes if hindered by over reliance on material widgets and it's limited extensibility of it, un-bundling it would/may "force" the package to be more interoperable with flutter's core widgets and their extensions

### Proposal

un-bundle (if that's even a word) `material` from flutter sdk an make it available as package

### Notes

I have the feeling that this has been briefly discussed between the lines of some tangentially related issue
(maybe[ this one](https://github.com/flutter/flutter/issues/91605)?), but I couldn't find a "start to end" discussion about it

**Comment by exaby73** [comment]
Hello @iapicca. Seems like a valid request. Keeping open for discussion. Thank you

**Comment by iapicca** [comment]
duplicate of https://github.com/flutter/flutter/issues/101479
