### ISSUE TITLE
[go_router] Support routerConfig

### ISSUE THREAD

**Issue by chunhtai** [flutter/flutter#109162]
go_router should implement the RouterConfig interface and be able to use it like:

```dart
MaterialApp.router(
  routerConfig: GoRouter(
    // …
  )
);
```

**Comment by iapicca** [comment]
I hope `RouterConfig` won't be locked in like using private interfaces or stuff like that, so that most navigation packages could leverage that

**Comment by chunhtai** [comment]
fix merged into feature branch v5, please use https://github.com/flutter/flutter/issues/108044 to track v5 release progress
