### ISSUE TITLE
Webview not loading

### ISSUE THREAD

**Issue by Pratiksha0796** [flutter/flutter#109141]
I/chromium(18253): [INFO:CONSOLE(1)] "Unrecognized feature: 'payment'.", source: https://js.stripe.com/v3 (1)

I'm getting this error for hotel booking , Used stripe as payment method.
for webview initialUrl is PaymentUrl + Payment token, while Payment url is different for Production and Stage environment.

Payment get failed on Stage environment, Its working fine on Production environment.

**Comment by exaby73** [comment]
Hello @Pratiksha0796. This looks like an error on your end with regards to Stripe. You can use online forums like StackOverflow or Stripe's own docs to get help on this. Since this is not an issue with Flutter itself, I am closing this issue. If you disagree, please comment and we can reopen it
