### ISSUE TITLE
Can have text selected in multiple text fields

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#10911]
On a screen with multiple text fields (e.g. the Text fields demo in the Flutter gallery), select text in the first text field and then select text in the second one. Text in the first text field stays selected. Native apps don't seem to behave that way and deselect the text in the first text field.

![image](https://user-images.githubusercontent.com/1227763/27452295-efa709ec-5746-11e7-872f-29aa0fb4bbd6.png)

**Comment by eseidelGoogle** [comment]
@Hixie or @abarth did some work to make Focus unique.  somehow that's being missed here I guess.
