### ISSUE TITLE
[proposal] conditional import for iOS and Android

### ISSUE THREAD

**Issue by MaximeEglem** [flutter/flutter#109154]
## Use case

Initialisation of the project with only the class necessary for iOS and Android.

For now, only possible to do it for IO and Web

```
import 'something_stub.dart'
if (dart.library.io) 'something_io.dart'
    if (dart.library.js) 'something_web.dart';
```

## Proposal

Distinct further library to add in the conditional import.
or
Manage conditional compilation based on environmental variable

**Comment by iapicca** [comment]
possibly related to https://github.com/flutter/flutter/issues/81650

**Comment by MaximeEglem** [comment]
> 

exactly
