### ISSUE TITLE
Enable latency sensitive GC mode for high-impact animations

### ISSUE THREAD

**Issue by iskakaushik** [flutter/flutter#109167]
Dart has added support for `Dart_SetPerformanceMode` to enable configuring the performance characteristics of GC. This issue tracks enabling this feature during high-impact animations.

Notes for the implementor:

1. https://github.com/flutter/engine/pull/34985 is an attempt at doing this, but doesn't take into account raster time.
2. One way to reproduce problems is to land https://github.com/flutter/engine/pull/35073 and revert https://github.com/flutter/flutter/pull/108565 and run `page_transitions_perf.dart`.

cc: @a-siva , @dnfield for awareness

**Comment by jonahwilliams** [comment]
This issue is long out of date. We did some expeirments with performance mode and it had a minor improvement, but no large impact on our benchmarks.
