### ISSUE TITLE
How to run a standalone app Linux ?

### ISSUE THREAD

**Issue by Tom3652** [flutter/flutter#109159]
This is not really an issue, but i could not find any documentation on how to run a linux standalone app, which is required on most cases for custom embedders i guess.  

I have built my app using `flutter build linux` on my Ubuntu VM, then i saw a `bundle` package inside the `/build/linux/release` folder. 
I also see a file with my app name along with a `lib` and a `data` folder. 
I need to execute my app by something like `./my_app_name` on a custom linux embedder (where i copy the content of `/bundle`). 

How can i do so please ? As it is not stated anywhere in the documentation... Is it even possible ? 

I have asked the same thing on [StackOverFlow](https://stackoverflow.com/questions/73278689/how-to-run-a-standalone-linux-app-built-with-flutter) but not sure contributors will go there, and they probably have this basic answer... 

Thanks in advance

**Comment by stuartmorgan** [comment]
See [the documentation about building Linux apps](https://docs.flutter.dev/development/platform-integration/linux/building#preparing-linux-apps-for-distribution) for information about what you need for distribution.

**Comment by stuartmorgan** [comment]
Note that if you are running `flutter build linux` you are using the Flutter-team-maintained Linux embedding, not a custom embedding. If you want to use a custom embedding you'll need to look at that project's documentation for build/install instructions.

**Comment by Tom3652** [comment]
So do you mean i can't execute the output of `flutter build linux` without `flutter run` ? And by extension, i need to have flutter installed on the linux devices i want to run the app on ?

**Comment by stuartmorgan** [comment]
> So do you mean i can't execute the output of `flutter build linux` without `flutter run` ?

No, that's not at all what the instructions I linked to say.

> I simply want to build my app under some linux distribution, and execute the compiled app on another device (that have the same linux distribution)

That's not a custom embedder, it's just distributing an application.

**Comment by Tom3652** [comment]
`
The executable binary can be found in your project under build/linux/<build mode>/bundle/. Alongside your executable binary in the bundle directory there are two directories
`

The only thing i wanted to know is how to execute this "executable" file that i have (assuming i have installed all the dependencies etc...)

**Comment by stuartmorgan** [comment]
It's a standard Linux executable. How to run programs on Linux isn't in scope for Flutter documentation; any number of general resources on using Linux should be able to provide that information.

**Comment by Tom3652** [comment]
I have tried to run it as a simple linux program but i have got `-bash: ./my_project_name: cannot execute binary file: Exec format error`
So i agree with you this is not flutter documentation scope, but if the file can't be executed it's an issue.. And there is no extension to the file.

I apreciate you take time to answer me.

**Comment by stuartmorgan** [comment]
> I have tried to run it as a simple linux program but i have got `-bash: ./my_project_name: cannot execute binary file: Exec format error`

It sounds like you are trying to run on a different configuration than you built for, such as a different architecture. Flutter-built Linux binaries are subject to all the standard constraints of Linux binaries.

**Comment by Tom3652** [comment]
Thank you very much, i have indeed tried to run this script on my "working" device (where i have built the app) and it's working just fine so the problem comes from my other device. 
So i will dig into what you told me and make the according changes, thanks again.
