### ISSUE TITLE
Lost connection to device

### ISSUE THREAD

**Issue by trajamohan** [flutter/flutter#109129]
I had installed flutter in windows 10, created a project (default), the project runs in chrome and edge but not as windows desktop application it starts with the windows frame (no content are displayed) after couple of seconds reports 

**"Lost connection to device."**

> [√] Flutter (Channel stable, 3.0.5, on Microsoft Windows [Version 10.0.19043.1865], locale en-IN)
    • Flutter version 3.0.5 at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (4 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

>[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\Rajamohan\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

>[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

>[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.2.6)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.2.32630.192
    • Windows 10 SDK version 10.0.19041.0

>[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

>[√] VS Code (version 1.70.0)
    • VS Code at C:\Users\Rajamohan\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.46.0

>[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19043.1865]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 103.0.5060.134
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 104.0.1293.47

>[√] HTTP Host Availability
    • All required HTTP hosts are available

>• No issues found!

> C:\flutter_apps\test1>flutter --version
Flutter 3.0.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f1875d570e (4 weeks ago) • 2022-07-13 11:24:16 -0700
Engine • revision e85ea0e79c
Tools • Dart 2.17.6 • DevTools 2.12.2

No error or logs are seen, attached the full log generated running the application in verbose mode.

Is there anything I am missing in the installation of flutter in windows 10?, the same setup is running as expected under Linux without any issue

[run_log.txt](https://github.com/flutter/flutter/files/9278773/run_log.txt)

**Comment by trajamohan** [comment]
In the above environment the windows 10 running as guest os in Linux Mint. Now I had tested the same application in a laptop with same flutter setup it works as expected.

Seems there is rendering issue with windows10 running in virtualbox

**Comment by huycozy** [comment]
Hi @trajamohan 
As my understanding, you are building a Flutter app on Windows (virtual machine) hosted by Linux Mint, right?
Can you run the default Flutter app (counter app) normally? And does the app crash when this happens?

**Comment by trajamohan** [comment]
Hi @huycozy, the crash happen for the default flutter app to the above test is based on that, had tested all channel stable, beta, master and dev all have the same result for the windows desktop.

The same application is running in chrome and edge in the same machine, my feel is it's something to do with the GPU not detected correctly so rendering is causing the issue, trying setting in virtualbox to directly access the host GPU

**Comment by trajamohan** [comment]
With flutter channel master build I am getting an error message now, will this give a direction to solution

> C:\flutter_apps\nx20_app>flutter doctor                  
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, 3.1.0-0.0.pre.2144, on Microsoft Windows [Version 10.0.19043.1865], locale en-IN)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.2.6)
[√] Android Studio (version 2021.2)
[√] VS Code (version 1.70.0)
[√] Connected device (3 available)
[√] HTTP Host Availability

• No issues found!

```
ERR: DisplayD3D.cpp:158 (CreateRendererD3D): Failed to create D3D renderer: Could not create D3D11 device.
ERR: Display.cpp:991 (initialize): ANGLE Display::initialize error 12289: No available renderers.
```

**Comment by trajamohan** [comment]
Ok, after lot of testing and reading found the limitation in 3D support virtualbox, migrated the windows guest to vmware player guest, now the flutter desktop application are normally build and displayed.

The problem still persist in the guest OS installed in virtualbox.

Since the issues is solved I am closing the issue

Thanks for the support
