### ISSUE TITLE
The YearPicker embedded in DatePicker is not very discoverable.

### ISSUE THREAD

**Issue by gspencergoog** [flutter/flutter#10917]
Summary: This is a feature request for the DatePicker to switch to the YearPicker when tapping on the year displayed, or maybe to scroll through years if scrolled vertically.

I was going to file a bug about there not *being* a year picker, but I found the documentation for YearPicker and saw that it is supposed to appear as part of the DatePicker, and tried the gallery. After about 5 minutes of playing with the widget, I finally found how to activate the year picker, mainly because I was assuming that the header was just an inactive header, not an active field, and because the year is small, even though I tapped near it a few times, it didn't activate the year picker.

That's too hard.  I think that if it would switch to the year picker when someone taps on the year at the top of the month display, or if you could scroll by one year at a time by scrolling the month display vertically, then that would make it more useful.  At the very least, it seems like the year in the header should be larger, and/or part of the rest of the date so that it looks like an interesting data field instead of a title (e.g. Display "Thu, Jun 22, 2017" all on one line, with the year or the date dimmed to show which is selected).

**Comment by Hixie** [comment]
cc @sethladd Can you see what the material team thinks?

**Comment by eseidelGoogle** [comment]
Does Android's Material library or Material iOS Components follow the Material Date picker spec in this way?

**Comment by sethladd** [comment]
I was just testing the date picker on the Google Calendar app. Our Gallery seems to be very very close to that.

Tap the year above the day, and the vertical list of years appears. In Google Calendar, the vertical year list fades in, but the Gallery's vertical year list "pops" in. (Flutter could fade in the year list for an even nicer experience.)

Here are two screenshots:
![screenshot_20170713-091347](https://user-images.githubusercontent.com/5479/28176341-da9c4646-67ab-11e7-9022-ff6768eda3e0.png)

![screenshot_20170713-091352](https://user-images.githubusercontent.com/5479/28176349-e06a852e-67ab-11e7-9156-3c47875dcb16.png)

**Comment by collinjackson** [comment]
Here's the date picker in the Google Trips app on iOS.

![image](https://user-images.githubusercontent.com/394889/28177135-b5794fc8-67ae-11e7-86d4-101689f2bcef.png)

**Comment by collinjackson** [comment]
Comparing the date picker in the Google Trips app with the Flutter one, there are appear to be some minor differences in padding, but the main difference is that in the Trips app there is an inkwell splash and the tap target is larger (it behaves like a `FlatButton`). On Flutter there is no ink splash and the tap target is constrained to just the text itself.

![image](https://user-images.githubusercontent.com/394889/28177663-602eb3bc-67b0-11e7-85a9-5cedd424f7ec.png)

So I think the action item here is to make it behave like Trips and use `FlatButton`.

**Comment by collinjackson** [comment]
Testing with the trips app, tapping July 2017 at the top of the month view also switches to the year view (without an ink splash, I think). We should do that as well.

**Comment by sethladd** [comment]
>  tapping July 2017 at the top of the month view also switches to the year view

Interesting, it doesn't do that in Google Calendar on Android.
