### ISSUE TITLE
[impeller] 99th percentile raster time regression on Android

### ISSUE THREAD

**Issue by iskakaushik** [flutter/flutter#109163]
https://flutter-flutter-perf.skia.org/e/?begin=1659737526&end=1659813851&keys=X3afeaad5edd93e30e365b8e7bab5c7c4&num_commits=50&request_type=1&xbaroffset=30329

Seems to point to: https://github.com/flutter/flutter/pull/109074

**Comment by jonahwilliams** [comment]
Looks like this was impeller only, probably my change to uniforms in https://github.com/flutter/engine/pull/35201 . Let me investigate and see if there is something obviously in the generated shaders

**Comment by jonahwilliams** [comment]
Generated shaders are https://gist.github.com/jonahwilliams/e2dbc01595eaa2ffecd03a787de9da5d , no obvious differences to me. Going to check the other commits too
