### ISSUE TITLE
Horizontal scrolling by mouse wheel is not working

### ISSUE THREAD

**Issue by mohammadtaherri** [flutter/flutter#109117]
- Create a horizontal `ScrollView` Like `ListView`

- Run your Flutter Web App with chrome

- Try to scroll horizontally by mouse wheel

-  Unfortunately, It will not work.

<details><summary>Flutter Doctor</summary>
<p>

```
  [✓] Flutter (Channel stable, 3.0.1, on Pop!_OS 20.04 LTS 5.11.0-7620-generic,
    locale en_US.UTF-8)
    Checking Android licenses is taking an unexpectedly long time...[✓] Android toolchain - develop for Android devices (Android SDK 
    version 31.0.0)
  [✓] Chrome - develop for the web
  [✓] Linux toolchain - develop for Linux desktop
  [✓] Android Studio (version 2021.2)
  [✓] VS Code (version 1.58.2)
  [✓] Connected device (2 available)
 [✓] HTTP Host Availability

 • No issues found!
```

</p>
</details>

**Comment by navaronbracke** [comment]
I ran this on Dartpad (with Flutter 3.0.5 Dart SDK 2.17.6) and once I set scrollDirection: Axis.horizontal I can't scroll with the mouse wheel (even when holding down shift) I don't see any scrollbars either. A vertical ListView works fine

```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(primarySwatch: Colors.blue),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage();

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Column(
        children: [
          Expanded(
            child: ListView.builder(
              scrollDirection: Axis.horizontal,
              itemBuilder: (context, index) {
                return Container(
                  width: 70,
                  height: 200,
                  color: index % 2 == 0 ? Colors.blue : Colors.green,
                  child: Center(child: Text('index: $index')),
                );
              },
              itemCount: 50,
            ),
          ),
        ],
      ),
    );
  }
}
```

**Comment by adilwahla** [comment]
Wrap your inner SingleChildScrollView with Listener and add onPointerSignal callback, and you can get a offset in y axis when use mouse wheel. Then, scroll inner SingleChildScrollView and forbid outer ListView from scrolling. Here is code and it works on dartpad.

`final outerController = ScrollController();
final innerController = ScrollController();

ListView(
      controller: outerController,
      children: [
        Container(
          width: 420.0,
          child: Row(
            children: [
              Expanded(
                child: Text(
                  'Popular Search',
                ),
              ),
              Expanded(
                  flex: 3,
                  child: Listener(
                    onPointerSignal: (event) {
                      if (event is PointerScrollEvent) {
                        final offset = event.scrollDelta.dy;
                        innerController.jumpTo(innerController.offset + offset);
                        outerController.jumpTo(outerController.offset - offset);
                      }
                    },
                    child: SingleChildScrollView(
                      controller: innerController,
                      scrollDirection: Axis.horizontal,
                      child: Row(
                        children: categoriesList.map((e) {
                          return Container(
                            decoration: BoxDecoration(
                              borderRadius:
                                  BorderRadius.all(Radius.circular(12.0)),
                              color: Colors.white,
                            ),
                            child: Text(
                              e,
                              style: TextStyle(
                                fontSize: 13.0,
                              ),
                            ),
                          );
                        }).toList(),
                      ),
                    ),
                  ))
            ],
          ),
        ),
      ],
    ),`

**Comment by Hari-07** [comment]
On a laptop touchpad it works, mouse wheels scroll vertically not horizontally

**Comment by exaby73** [comment]
Hi @mohammadtaherri
I see there's an open issue addressing the case you described https://github.com/flutter/flutter/issues/105095
Please follow up and upvote that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
