### ISSUE TITLE
Problem with go_router 3.1.1, custom transition and context.pop()

### ISSUE THREAD

**Issue by cedricmelfatum** [flutter/flutter#109288]
When using go_router 3.1.1 and trying to call context.pop() on a page that has a CustomTransition, it breaks.
See https://github.com/cedricpalo/custom_transition_pop to reproduce the problem.

P.S.: I did not try with latest version of go_router

**Comment by exaby73** [comment]
Hello @cedricmelfatum. Please try with `go_router: ^4.2.7`. This issue may be fixed already

**Comment by cedricmelfatum** [comment]
Well, unfortunately, not easy, because would require us to upgrade a lot of things :(

**Comment by cedricmelfatum** [comment]
If someone can try it with latest version, would be very nice! (I don't have the setup for it at all)

**Comment by exaby73** [comment]
Hi @cedricmelfatum. If you produce a [minimal, reproducible example][1] and the output of `flutter doctor -v` as well as `flutter run -v`, that would be enough to test it on the latest version.

[1]: https://stackoverflow.com/help/minimal-reproducible-example

**Comment by cedricmelfatum** [comment]
Hi! I did produce a minimal reproducible example in this repository (see my first message): https://github.com/cedricpalo/custom_transition_pop

**Comment by cedricmelfatum** [comment]
Here is my output for `flutter doctor -v` and `flutter run -v`
```$ flutter doctor -v
[√] Flutter (Channel stable, 2.5.3, on Microsoft Windows [Version 10.0.22622.450], locale en-GB)
    • Flutter version 2.5.3 at C:\Users\cedri\Development\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (10 months ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\cedri\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.70.0)
    • VS Code at C:\Users\cedri\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.46.0

[√] Connected device (3 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 104.0.5112.81
    • Edge (web)              • edge          • web-javascript • Microsoft Edge 104.0.1293.47

• No issues found!```

```
$ flutter run -v
[  +78 ms] executing: [C:\Users\cedri\Development\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +56 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] 18116933e77adc82f80866c928266a5b4f1ed645
[   +1 ms] executing: [C:\Users\cedri\Development\flutter/] git tag --points-at 18116933e77adc82f80866c928266a5b4f1ed645
[  +38 ms] Exit code 0 from: git tag --points-at 18116933e77adc82f80866c928266a5b4f1ed645
[        ] 2.5.3
[  +11 ms] executing: [C:\Users\cedri\Development\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +23 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] origin/stable
[        ] executing: [C:\Users\cedri\Development\flutter/] git ls-remote --get-url origin
[  +20 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +111 ms] executing: [C:\Users\cedri\Development\flutter/] git rev-parse --abbrev-ref HEAD
[  +25 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +86 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +8 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +84 ms] executing: C:\Users\cedri\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +61 ms] List of devices attached
           emulator-5554          device product:sdk_gphone_x86 model:sdk_gphone_x86 device:generic_x86_arm transport_id:2
[   +6 ms] C:\Users\cedri\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell getprop
[  +48 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +8 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +116 ms] Skipping pub get: version match.
[ +161 ms] Generating
C:\Users\cedri\Development\projects\custom_transition_pop\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +92 ms] ro.hardware = ranchu
[  +13 ms] Using hardware rendering with device sdk gphone x86. If you notice graphics artifacts, consider enabling software rendering with
           "--enable-software-rendering".
[  +28 ms] Initializing file store
[  +14 ms] Skipping target: gen_localizations
[   +7 ms] Skipping target: gen_dart_plugin_registrant
[   +1 ms] Skipping target: _composite
[   +2 ms] complete
[   +6 ms] Launching lib\main.dart on sdk gphone x86 in debug mode...
[   +6 ms] C:\Users\cedri\Development\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev
C:\Users\cedri\Development\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root
C:\Users\cedri\Development\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names
--experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true --output-dill
C:\Users\cedri\AppData\Local\Temp\flutter_tools.9f8a5794\flutter_tool.5f70f627\app.dill --packages
C:\Users\cedri\Development\projects\custom_transition_pop\.dart_tool\package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts
--track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill build\c075001b96339384a97db4862b8ab8db.cache.dill.track.dill        
--enable-experiment=alternative-invalidation-strategy
[  +27 ms] executing: C:\Users\cedri\AppData\Local\Android\sdk\build-tools\31.0.0\aapt dump xmltree
C:\Users\cedri\Development\projects\custom_transition_pop\build\app\outputs\flutter-apk\app.apk AndroidManifest.xml
[  +26 ms] Exit code 0 from: C:\Users\cedri\AppData\Local\Android\sdk\build-tools\31.0.0\aapt dump xmltree
C:\Users\cedri\Development\projects\custom_transition_pop\build\app\outputs\flutter-apk\app.apk AndroidManifest.xml
[   +1 ms] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1e
               A: android:compileSdkVersionCodename(0x01010573)="11" (Raw: "11")
               A: package="com.example.custom_transition_pop" (Raw: "com.example.custom_transition_pop")
               A: platformBuildVersionCode=(type 0x10)0x1e
               A: platformBuildVersionName=(type 0x10)0xb
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1e
               E: uses-permission (line=14)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: application (line=16)
                 A: android:label(0x01010001)="custom_transition_pop" (Raw: "custom_transition_pop")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw: "androidx.core.app.CoreComponentFactory")     
                 E: activity (line=21)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A: android:name(0x01010003)="com.example.custom_transition_pop.MainActivity" (Raw: "com.example.custom_transition_pop.MainActivity")  
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x40003fb4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: meta-data (line=35)
                     A: android:name(0x01010003)="io.flutter.embedding.android.NormalTheme" (Raw: "io.flutter.embedding.android.NormalTheme")
                     A: android:resource(0x01010025)=@0x7f0a0001
                   E: meta-data (line=45)
                     A: android:name(0x01010003)="io.flutter.embedding.android.SplashScreenDrawable" (Raw:
                     "io.flutter.embedding.android.SplashScreenDrawable")
                     A: android:resource(0x01010025)=@0x7f040000
                   E: intent-filter (line=49)
                     E: action (line=50)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=52)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw: "android.intent.category.LAUNCHER")
                 E: meta-data (line=59)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw: "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
[  +10 ms] executing: C:\Users\cedri\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell -x logcat -v time -t 1
[  +16 ms] <- compile package:custom_transition_pop/main.dart
[  +62 ms] --------- beginning of main
           08-11 16:04:51.939 E/wifi_forwarder(  485): RemoteConnection failed to initialize: RemoteConnection failed to open pipe
[  +14 ms] executing: C:\Users\cedri\AppData\Local\Android\sdk\platform-tools\adb.exe version
[  +35 ms] Android Debug Bridge version 1.0.41
           Version 31.0.3-7562133
           Installed as C:\Users\cedri\AppData\Local\Android\sdk\platform-tools\adb.exe
[   +2 ms] executing: C:\Users\cedri\AppData\Local\Android\sdk\platform-tools\adb.exe start-server
[  +26 ms] Building APK
[  +21 ms] Running Gradle task 'assembleDebug'...
[   +6 ms] Using gradle from C:\Users\cedri\Development\projects\custom_transition_pop\android\gradlew.bat.
[  +16 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
[ +167 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
[        ] openjdk version "11.0.10" 2021-01-19
           OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
           OpenJDK 64-Bit Server VM (build 11.0.10+0-b96-7249189, mixed mode)
[   +3 ms] executing: [C:\Users\cedri\Development\projects\custom_transition_pop\android/]
C:\Users\cedri\Development\projects\custom_transition_pop\android\gradlew.bat -Pverbose=true -Ptarget-platform=android-x86
-Ptarget=C:\Users\cedri\Development\projects\custom_transition_pop\lib\main.dart -Pdart-defines=RkxVVFRFUl9XRUJfQVVUT19ERVRFQ1Q9dHJ1ZQ==
-Pdart-obfuscation=false -Ptrack-widget-creation=true -Ptree-shake-icons=false -Pfilesystem-scheme=org-dartlang-root assembleDebug
[+1612 ms] Starting a Gradle Daemon, 2 busy Daemons could not be reused, use --status for details
[+9293 ms] > Task :app:compileFlutterBuildDebug UP-TO-DATE
[   +1 ms] > Task :app:packLibsflutterBuildDebug UP-TO-DATE
[   +1 ms] > Task :app:preBuild UP-TO-DATE
[        ] > Task :app:preDebugBuild UP-TO-DATE
[        ] > Task :app:compileDebugAidl NO-SOURCE
[        ] > Task :app:compileDebugRenderscript NO-SOURCE
[        ] > Task :app:generateDebugBuildConfig UP-TO-DATE
[ +301 ms] > Task :app:checkDebugAarMetadata UP-TO-DATE
[   +1 ms] > Task :app:cleanMergeDebugAssets
[        ] > Task :app:mergeDebugShaders UP-TO-DATE
[        ] > Task :app:compileDebugShaders NO-SOURCE
[        ] > Task :app:generateDebugAssets UP-TO-DATE
[  +91 ms] > Task :app:mergeDebugAssets
[ +405 ms] > Task :app:copyFlutterAssetsDebug
[   +1 ms] > Task :app:generateDebugResValues UP-TO-DATE
[   +1 ms] > Task :app:generateDebugResources UP-TO-DATE
[  +91 ms] > Task :app:mergeDebugResources UP-TO-DATE
[   +1 ms] > Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
[   +1 ms] > Task :app:extractDeepLinksDebug UP-TO-DATE
[   +1 ms] > Task :app:processDebugMainManifest UP-TO-DATE
[   +1 ms] > Task :app:processDebugManifest UP-TO-DATE
[   +1 ms] > Task :app:processDebugManifestForPackage UP-TO-DATE
[  +87 ms] > Task :app:processDebugResources UP-TO-DATE
[ +607 ms] > Task :app:compileDebugKotlin UP-TO-DATE
[   +1 ms] > Task :app:javaPreCompileDebug UP-TO-DATE
[   +1 ms] > Task :app:compileDebugJavaWithJavac UP-TO-DATE
[   +1 ms] > Task :app:compileDebugSources UP-TO-DATE
[        ] > Task :app:mergeDebugNativeDebugMetadata NO-SOURCE
[  +89 ms] > Task :app:compressDebugAssets UP-TO-DATE
[        ] > Task :app:processDebugJavaRes NO-SOURCE
[   +1 ms] > Task :app:mergeDebugJavaResource UP-TO-DATE
[        ] > Task :app:checkDebugDuplicateClasses UP-TO-DATE
[        ] > Task :app:dexBuilderDebug UP-TO-DATE
[ +105 ms] > Task :app:desugarDebugFileDependencies UP-TO-DATE
[   +1 ms] > Task :app:mergeExtDexDebug UP-TO-DATE
[        ] > Task :app:mergeDexDebug UP-TO-DATE
[        ] > Task :app:mergeDebugJniLibFolders UP-TO-DATE
[  +92 ms] > Task :app:mergeDebugNativeLibs UP-TO-DATE
[   +1 ms] > Task :app:stripDebugDebugSymbols UP-TO-DATE
[        ] > Task :app:validateSigningDebug UP-TO-DATE
[        ] > Task :app:packageDebug UP-TO-DATE
[ +293 ms] > Task :app:assembleDebug
[   +1 ms] Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
[        ] Use '--warning-mode all' to show the individual deprecation warnings.
[        ] See https://docs.gradle.org/6.7/userguide/command_line_interface.html#sec:command_line_warnings
[        ] BUILD SUCCESSFUL in 12s
[        ] 32 actionable tasks: 4 executed, 28 up-to-date
[ +644 ms] Running Gradle task 'assembleDebug'... (completed in 13.9s)
[  +64 ms] calculateSha: LocalDirectory: 'C:\Users\cedri\Development\projects\custom_transition_pop\build\app\outputs\flutter-apk'/app.apk
[ +548 ms] √  Built build\app\outputs\flutter-apk\app-debug.apk.
[   +4 ms] executing: C:\Users\cedri\AppData\Local\Android\sdk\build-tools\31.0.0\aapt dump xmltree
C:\Users\cedri\Development\projects\custom_transition_pop\build\app\outputs\flutter-apk\app.apk AndroidManifest.xml
[  +25 ms] Exit code 0 from: C:\Users\cedri\AppData\Local\Android\sdk\build-tools\31.0.0\aapt dump xmltree
C:\Users\cedri\Development\projects\custom_transition_pop\build\app\outputs\flutter-apk\app.apk AndroidManifest.xml
[   +1 ms] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1e
               A: android:compileSdkVersionCodename(0x01010573)="11" (Raw: "11")
               A: package="com.example.custom_transition_pop" (Raw: "com.example.custom_transition_pop")
               A: platformBuildVersionCode=(type 0x10)0x1e
               A: platformBuildVersionName=(type 0x10)0xb
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1e
               E: uses-permission (line=14)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: application (line=16)
                 A: android:label(0x01010001)="custom_transition_pop" (Raw: "custom_transition_pop")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw: "androidx.core.app.CoreComponentFactory")     
                 E: activity (line=21)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A: android:name(0x01010003)="com.example.custom_transition_pop.MainActivity" (Raw: "com.example.custom_transition_pop.MainActivity")  
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x40003fb4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: meta-data (line=35)
                     A: android:name(0x01010003)="io.flutter.embedding.android.NormalTheme" (Raw: "io.flutter.embedding.android.NormalTheme")
                     A: android:resource(0x01010025)=@0x7f0a0001
                   E: meta-data (line=45)
                     A: android:name(0x01010003)="io.flutter.embedding.android.SplashScreenDrawable" (Raw:
                     "io.flutter.embedding.android.SplashScreenDrawable")
                     A: android:resource(0x01010025)=@0x7f040000
                   E: intent-filter (line=49)
                     E: action (line=50)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=52)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw: "android.intent.category.LAUNCHER")
                 E: meta-data (line=59)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw: "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
[   +6 ms] Stopping app 'app.apk' on sdk gphone x86.
[   +1 ms] executing: C:\Users\cedri\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell am force-stop
com.example.custom_transition_pop
[  +64 ms] executing: C:\Users\cedri\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell pm list packages
com.example.custom_transition_pop
[  +53 ms] package:com.example.custom_transition_pop
           package:com.example.custom_transition_pop2
[   +2 ms] executing: C:\Users\cedri\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell cat
/data/local/tmp/sky.com.example.custom_transition_pop.sha1
[  +44 ms] bd36e9011cc40b25724416d71254461c71b607b4
[   +1 ms] Latest build already installed.
[        ] executing: C:\Users\cedri\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell -x logcat -v time -t 1
[  +40 ms] --------- beginning of main
           08-11 16:05:26.313 D/CarrierSvcBindHelper(  851): No carrier app for: 0
[   +7 ms] executing: C:\Users\cedri\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell am start -a android.intent.action.RUN -f    
0x20000000 --ez enable-background-compilation true --ez enable-dart-profiling true --ez enable-checked-mode true --ez verify-entry-points true
com.example.custom_transition_pop/com.example.custom_transition_pop.MainActivity
[  +70 ms] Starting: Intent { act=android.intent.action.RUN flg=0x20000000 cmp=com.example.custom_transition_pop/.MainActivity (has extras) }
[        ] Waiting for observatory port to be available...
[ +762 ms] W/FlutterActivityAndFragmentDelegate(19431): A splash screen was provided to Flutter, but this is deprecated. See
flutter.dev/go/android-splash-migration for migration steps.
[ +361 ms] Observatory URL on device: http://127.0.0.1:44533/xj3DSAyjQSE=/
[   +1 ms] executing: C:\Users\cedri\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 forward tcp:0 tcp:44533
[  +27 ms] 12962
[        ] Forwarded host port 12962 to device port 44533 for Observatory
[   +6 ms] Caching compiled dill
[  +38 ms] Connecting to service protocol: http://127.0.0.1:12962/xj3DSAyjQSE=/
[ +345 ms] Launching a Dart Developer Service (DDS) instance at http://127.0.0.1:0, connecting to VM service at http://127.0.0.1:12962/xj3DSAyjQSE=/.
[ +268 ms] DDS is listening at http://127.0.0.1:12965/pes3HJj4tIY=/.
[  +65 ms] Successfully connected to service protocol: http://127.0.0.1:12962/xj3DSAyjQSE=/
[ +232 ms] DevFS: Creating new filesystem on the device (null)
[  +58 ms] DevFS: Created new filesystem on the device
(file:///data/user/0/com.example.custom_transition_pop/code_cache/custom_transition_popIMVVOU/custom_transition_pop/)
[   +4 ms] Updating assets
[ +117 ms] Syncing files to device sdk gphone x86...
[   +3 ms] <- reset
[        ] Compiling dart to kernel with 0 updated files
[   +3 ms] <- recompile package:custom_transition_pop/main.dart 26bab0c8-5f26-4cdb-acef-e2b730440231
[        ] <- 26bab0c8-5f26-4cdb-acef-e2b730440231
[  +89 ms] Updating files.
[        ] DevFS: Sync finished
[   +1 ms] Syncing files to device sdk gphone x86... (completed in 97ms)
[   +1 ms] Synced 0.0MB.
[   +1 ms] <- accept
[   +7 ms] Connected to _flutterView/0xf09c8020.
[   +3 ms] Flutter run key commands.
[   +2 ms] r Hot reload. 
[   +1 ms] R Hot restart.
[        ] h List all available interactive commands.
[        ] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[        ] q Quit (terminate the application on the device).
[        ]  Running with sound null safety 
[   +1 ms] An Observatory debugger and profiler on sdk gphone x86 is available at: http://127.0.0.1:12965/pes3HJj4tIY=/
[ +461 ms] Activating Dart DevTools...
[+4823 ms] Activating Dart DevTools... (completed in 4.8s)
[ +648 ms] The Flutter DevTools debugger and profiler on sdk gphone x86 is available at: http://127.0.0.1:9101?uri=http://127.0.0.1:12965/pes3HJj4tIY=/
```

**Comment by exaby73** [comment]
Hello @cedricmelfatum. I can see from your doctor output that you are running `Flutter Channel stable, 2.5.3`. Please upgrade to the latest stable and confirm if this bug still exists

**Comment by cedricmelfatum** [comment]
Well, as I told you, that would be quite a big impact on the project to upgrade flutter version ... I would be happy to know at least first if it will solve the problem to consider this option... (especially as we have a work around using Navigator.pop(context).

**Comment by exaby73** [comment]
I cannot reproduce the issue with the latest version of `go_router`. Am I missing any steps?
