### ISSUE TITLE
Placeholder under GestureDetector

### ISSUE THREAD

**Issue by HasanElHefnawy** [flutter/flutter#109246]
Add the following code under the children of Column in Counter app.

            GestureDetector(
              onTap: _incrementCounter,
              child: const Placeholder(),
              // child: Container(width: 300, height: 300, color: Colors.blue),
            ),
_incrementCounter isn't called when using Placeholder(). The issue doesn't happen when using Container() instead of Placeholder().

**Comment by maheshmnj** [comment]
Hi @HasanElHefnawy, Thanks for filing the issue. This working as intended, if you want Placeholder to receive gestures try specifying `behavior` to GestureDetector  

```dart
  GestureDetector(
       behavior: HitTestBehavior.opaque,
       onTap: _incrementCounter,
  child: const Placeholder(),
```
