### ISSUE TITLE
Image colors are off on the web

### ISSUE THREAD

**Issue by arsen** [flutter/flutter#109249]
For some weird reason, flutter renders the same image with different colors on the web compared to other platforms (e.g. mac os)

Here is the screenshot on mac os:
<img width="1056" alt="mac-os" src="https://user-images.githubusercontent.com/3446647/183737485-ac341ada-b1ba-4d66-aa93-47803cc1909d.png">

And here is the screenshot on web platform:
<img width="1056" alt="web" src="https://user-images.githubusercontent.com/3446647/183737528-633f2cfc-72de-4a18-8cbc-3323eebf13d5.png">

It is a simple Image.asset widget
```
class FlutterImage extends StatelessWidget {
  const FlutterImage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Image.asset('assets/background.png'),
      ),
    );
  }
}
```

This is the test repo that I used as an example:
[https://github.com/arsen/flutter-image](https://github.com/arsen/flutter-image)

And this is the URL to the actual image:
[assets/background.png](https://github.com/arsen/flutter-image/blob/06b6c449431f359966ac43ec431ae238b8625e8d/assets/background.png)

FYI, the image was created in Figma app and exported out as PNG.

Another thing is the overall quality of the image on the web is much worse compared to mac os, if I add filterQuality to high on the widget then it is better.

Here is the output of my flutter doctor -v

```
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.4 21F79 darwin-x64, locale en-US)
    • Flutter version 3.0.5 at /Users/user/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (4 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/user/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/user/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.69.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.46.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.4 21F79 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 104.0.5112.79

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

**Comment by MatthewPatience** [comment]
This could possibly be related to the canvaskit bug here: https://github.com/flutter/flutter/issues/106433

It has been fixed and merged, but I believe it's only available in Flutter 3.3
