### ISSUE TITLE
[CP] Asset images with spaces cannot be loaded

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#109272]
### issue_link

https://github.com/flutter/flutter/issues/109195

### Commit Hash

e79d12a 

### Target

beta

### pr_link

?

### Impacted Users

all Flutter devs

### Impact Description

Applications that use asset images that contains spaces won't be able to load.

### Workaround

Assets can be renamed to excluse spaces.

### Risk

low

### Test Coverage

yes

### Validation Steps

Example app in attached issue can be run, in addition to unit tests in PR.

**Comment by itsjustkevin** [comment]
@zanderso I want to approve this for the next beta, do you have any other opinions?

**Comment by zanderso** [comment]
Lgtm

**Comment by muditatandon** [comment]
@jonahwilliams is there a CP PR for this? If not could you create one so that it can be approved and merged in the release branch for the beta release this week.

**Comment by jonahwilliams** [comment]
PR created, waiting on approval

**Comment by muditatandon** [comment]
Great, it looks like all tests pass and got 1 approval as well. Good to go. :)
