### ISSUE TITLE
My flutter app causes iPhones screen to dimmer at app start

### ISSUE THREAD

**Issue by Tom3652** [flutter/flutter#109258]
I am sorry that i make this issue like this, but i don't really know what else i can do... 

When i run my app in release mode (send it to my testers), everyone complained that the screen kept dimming until low level as if it was consuming high resources or something.  
 
I can confirm that i can't see it during the debug, but in release mode yes. 
I could reproduce it on many iPhones and the phone's were a bit hotter than usual while running my app.

The only thing i can share with you is my dev tool metrics : 

![Capture d’écran 2022-08-09 à 22 37 25](https://user-images.githubusercontent.com/32631467/183756016-e88a3199-72b5-47e9-83b0-fb5d7a4a245c.png)

![Capture d’écran 2022-08-09 à 22 38 08](https://user-images.githubusercontent.com/32631467/183756132-742bdac5-0a30-444b-a9d0-1ae44dfa1a52.png)

I am actually close to the 60 FPS except for some animations it's okay, but here are the metrics i have from my first app page and it's at this moment that it makes the screen dimmer. 

I would also add that the camera is running at app start and opened but it doesn't seem to be consuming too much.

Do you know what could be causing this from the code ? Too many streams opened ? Too many `static` instances ? 

I have already released an app on both Apple Store and Google play store using Flutter that doesn't do this but that has a much less complex UI and no camera. 

Thanks a lot in advance for any lead / feedback on this.  

## Details

**Target Platform:** iOS - Android
**Target OS version/browser:** iOS : 12 - Android 6
**Devices:** iPhone XS max, iPhone 12 pro Max, iPhone XR, iPhone 7 plus, iPhone 8, iPhone 11

## Logs

<details>
<summary>Logs</summary>

```
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.5 21G72 darwin-x64, locale fr-FR)
    • Flutter version 3.0.5 at /Users/foxtom/Desktop/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (4 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/foxtom/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.70.0)
    • VS Code at /Users/foxtom/Desktop/Visual Studio Code.app/Contents
    • Flutter extension version 3.46.0

[✓] Connected device (3 available)
    • Now You See Me (mobile) • 00008020-001204401E78002E • ios            • iOS 15.6 19G71
    • macOS (desktop)         • macos                     • darwin-x64     • macOS 12.5 21G72 darwin-x64
    • Chrome (web)            • chrome                    • web-javascript • Google Chrome 104.0.5112.79
    ! Error: Now You See Me is busy: Fetching debug symbols for Now You See Me. Xcode will continue when Now You See Me is finished. (code -10)

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @Tom3652, please provide the trace files from devtools. 

If you could also share a recording that captures the "dimming" effect you're experiencing, that would be appreciated. 

Also, what do you do on startup in your app?

**Comment by Tom3652** [comment]
I am sorry i am going to close this as it's not much something flutter can do about it, i will try to investigate better... Thanks
