### ISSUE TITLE
Is there is anyway I can use webview_flutter in web version?

### ISSUE THREAD

**Issue by Sunsiha** [flutter/flutter#109228]
Actually few scenarios I have implemented through webview_flutter version. It's working fine in Android and iOS. But is there is anyway I can do with  ```webview_flutter: ^3.0.4```?

Since am handling many things using JavascriptChannel. 

Is there is any plan for updating this plugin for web version?

**Comment by stuartmorgan** [comment]
See https://pub.dev/packages/webview_flutter_web for the current web support.

If you need JS communication though, that's not currently possible. You can vote for https://github.com/flutter/flutter/issues/101758, and subscribe to it for updates.
