### ISSUE TITLE
What happened to `--no-web-browser-launch` ?

### ISSUE THREAD

**Issue by softmarshmallow** [flutter/flutter#109268]
https://github.com/flutter/flutter/issues/43809

I'm using `flutter run -d web-server` as a daemon for my custom cli app, but i found out that this does not support devtools connection, getting back to `flutter run -d chrome`. 

The thing is I need to display the run result on embedded iframe, so I searched for how to run on chrome without launching new instance.

And I recall I used `flutter run -d chrome --no-web-browser-launch` just fine, yet it seems no longer supported.

What happened to `--no-web-browser-launch` flag?

And is there any possible way I can connect devtools with `-d web-server` ?

ref: https://github.com/flutter/flutter/blob/master/packages/flutter_tools/doc/daemon.md

**Comment by maheshmnj** [comment]
Hi @softmarshmallow, Thanks for filing the issue.

see https://github.com/flutter/flutter/issues/94831#issuecomment-996105262
>  -d web-server doesn't support the debug protocol, only -d BROWSER does, where BROWSER is chrome or edge.  

Closing as this is neither a bug nor a feature request.

**Comment by softmarshmallow** [comment]
Closing is fine. But still need a explanation :(

**Comment by rmschindler** [comment]
Has the `--no-web-browser-launch` flag on `flutter run -d chrome` been deprecated/removed? If so, what’s the alternative to this functionality?

**Comment by maheshmnj** [comment]
`--no-web-browser-launch` was removed in https://github.com/flutter/flutter/pull/44263 in favour of `web-server` 

see https://github.com/flutter/flutter/issues/48803#issuecomment-575553200

**Comment by rmschindler** [comment]
I see, thanks Mahesh! :)

I wonder: do we need to document the `-d web-server` option anywhere? And is it a disfluency for us users that `flutter devices` doesn’t list *all* the available devices, i.e. because `web-server` is another available device?

**Comment by maheshmnj** [comment]
@rmschindler  The documentation request is being tracked here https://github.com/flutter/flutter/issues/94831

**Comment by rmschindler** [comment]
Thanks, Mahesh :)
