### ISSUE TITLE
Support for Toasts

### ISSUE THREAD

**Issue by ArcticZeroo** [flutter/flutter#10924]
Flutter currently has support for SnackBars, but not Toasts. It would be nice to be able to send information as toasts rather than SnackBars.

Examples:
![toast1](https://user-images.githubusercontent.com/5075030/27465343-f648e112-57a0-11e7-8b85-fb3624221e91.png)
![toast2](https://user-images.githubusercontent.com/5075030/27465342-f409eeaa-57a0-11e7-8586-d310c8a60323.png)

**Comment by eseidelGoogle** [comment]
Toasts appear to be an Android-only entry in the Material Design spec, and have unfortunately very little detail to their spec:
https://material.io/guidelines/components/snackbars-toasts.html

**Comment by eseidelGoogle** [comment]
@lukef points out that Toasts on Android are also drawn by the system it seems, if you quit an app while a toast is on screen it can stay there. :p  Obviously if Flutter implemented Toasts they wouldn't have that behavior.

**Comment by ArcticZeroo** [comment]
Hmm, not sure if they're really worth having in that case... I think most devs use toasts because they persist through activities, not necessarily for toasts that stay when the app is quit (unless it's an app whose primary function is in the background, and I don't believe flutter supports that atm?)

**Comment by eseidelGoogle** [comment]
It sounds like the proper resolution for this is for someone to write a tiny plugin which wraps the Android toast APIs:
https://flutter.io/platform-plugins/
https://developer.android.com/reference/android/widget/Toast.html

**Comment by Hixie** [comment]
We don't think this should be part of Flutter proper; it's something a plugin should provide.
We are going to close this since we don't plan on writing this plugin for now.

**Comment by fluttercorner** [comment]
[How to create Toast in Flutter With Example](https://fluttercorner.com/how-to-create-toast-in-flutter-with-example/)
