### ISSUE TITLE
[CP] Fix incorrect impellerc output file permissions

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#109233]
### issue_link

https://github.com/flutter/flutter/issues/108737

### Commit Hash

f047672a8f483e20b4a523bd4f94fa9032b11423

### Target

beta

### pr_link

https://github.com/flutter/engine/pull/35186

### Impacted Users

All devs targeting macOS

### Impact Description

Incorrect file permissions cause failures on uploading macOS apps to Apple App Store. This will affect all app uploads since all apps bundle the ink_sparkle shader.

### Workaround

Yes users can run:
```
$ chmod 0644 build/macos/Build/Products/Release/AppName.app/Contents/Frameworks/App.framework/Versions/A/Resources/flutter_assets/shaders/ink_sparkle.frag
```
however, the thought that this is difficult to document and error prone.

### Risk

low

### Test Coverage

yes

### Validation Steps

Build an iOS app and check that access permissions on `build/macos/Build/Products/Release/AppName.app/Contents/Frameworks/App.framework/Versions/A/Resources/flutter_assets/shaders/ink_sparkle.frag` are 0644.

Tested in https://github.com/flutter/flutter/pull/109190.

**Comment by itsjustkevin** [comment]
Starting the build this morning, could you open up a cherry pick to the release branch @zanderso?  I will merge it once @christopherfujino give the thumbs up on this issue.

**Comment by itsjustkevin** [comment]
absolutely, the beta release branch is: [flutter-3.2-candidate.5](https://github.com/flutter/flutter/tree/flutter-3.2-candidate.5)

**Comment by christopherfujino** [comment]
This LGTM

**Comment by cbenhagen** [comment]
@zanderso this issue is still present in the current stable channel (3.3.2). Am I just impatient or was there some issue with the CP?

**Comment by zanderso** [comment]
The CP landed on the release branch here https://github.com/flutter/engine/pull/35269, and should have been present since 3.3.0. If you're still seeing this, could you file a new issue with full details, please?

**Comment by cbenhagen** [comment]
@zanderso I opened #111808 to track this.
