### ISSUE TITLE
Would like a Sentry.io plugin

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#10926]
For reporting errors, crashes and other logging.

See also: https://github.com/flutter/flutter/issues/9592 (Crashlytics)

**Comment by yjbanov** [comment]
Update: I created a pure Dart Sentry.io client ([pub](https://pub.dartlang.org/packages/sentry), [repo](https://github.com/yjbanov/sentry)). It works in Flutter and standalone VM. Planning to create a Flutter plugin that will pre-configure the `SentryClient` with mobile-related attributes (such as mobile OS/version, Flutter version, runtime mode, etc). This is only for convenience. The package should be usable already.

**Comment by eseidelGoogle** [comment]
I believe we can close this now, given the above. :)
