### ISSUE TITLE
[conductor] Ensure flutter/flutter has the latest engine sha from corresponding branch

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#109254]
To prevent shipping releases that do not contain the latest Dart and Engine CPs, add a validation check that verifies the HEAD for the branches match.

As we migrate the CPs outside the release process, this is necessary as CPs aren't being managed by the release engineers.

\cc @itsjustkevin

**Comment by itsjustkevin** [comment]
@christopherfujino does the conductor tool already check for this?  For example, when I rolled another commit on top of the generated release PR, conductor still grabbed from HEAD.  Maybe I am misunderstanding here.

**Comment by christopherfujino** [comment]
> @christopherfujino does the conductor tool already check for this? For example, when I rolled another commit on top of the generated release PR, conductor still grabbed from HEAD. Maybe I am misunderstanding here.

I believe the ask here is to verify that the contents of //flutter/bin/internal/engine.version on the framework release candidate branch matches the revision at the tip of the engine release candidate branch. I don't believe the conductor currently does this (as you point out, the conductor will *check out* the tip of the engine candidate branch, but that doesn't mean the framework is rolled to that point).

**Comment by itsjustkevin** [comment]
Ahhhh thank you for clarifying, I will self-assign this one for now.

**Comment by XilaiZhang** [comment]
this has been fixed by Jesse
