### ISSUE TITLE
Flutter video_player not playing or mpeg2 has no audio

### ISSUE THREAD

**Issue by tishriclarin** [flutter/flutter#109221]
I wonder when will flutter video_player support playing mpeg2 audio format?

**Comment by tishriclarin** [comment]
@exaby73 I disagree flutter needs compile exoplayer with ffmpeg transcoder to be able to properly render mpeg2 and other unsupported audio formats.

**Comment by exaby73** [comment]
@tishriclarin Thanks for the feedback. I'll reopen this request for further insights from the team

**Comment by tishriclarin** [comment]
@exaby73 thanks

**Comment by tishriclarin** [comment]
https://github.com/google/ExoPlayer/tree/release-v2/extensions/ffmpeg 

Follow that link to compile ffmpeg extension for exoplayer.
