### ISSUE TITLE
Enable skia autoroller on release branches

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#109255]
This will remove the toil of manually rolling the revisions for engine->flutter

**Comment by CaseyHillers** [comment]
I synced up with the skia team. While the auto-roller configs don't support wildcards in the refspec, they do have a special variant they created for Chromium's releases.

We'll need to create a `/api/public/get-release-branches` that returns a list of the latest google3 roll, beta, and stable branches. Then skia's configs can ping that for what auto-rollers should be enabled for us.

**Comment by CaseyHillers** [comment]
I tried https://flutter-dashboard.appspot.com/api/public/get-release-branches but it's returning a 500 error. @XilaiZhang can you take a look?

**Comment by XilaiZhang** [comment]
Sure, thanks for catching this! I will inspect
