### ISSUE TITLE
RenderEditable (TextField) ignores offset in painting, making text selections shifted when offset is nonzero

### ISSUE THREAD

**Issue by fzyzcjy** [flutter/flutter#109289]
Please see https://github.com/flutter/flutter/pull/109287 for a detailed description of the issue and the PR :)

## Steps to Reproduce

As mentioned in the PR description, it is a logical bug, so cannot provide reproducible code.

**Comment by exaby73** [comment]
Hello @fzyzcjy. Thank you for filing this issue. Looks like a valid request. Labelling as such

**Comment by fzyzcjy** [comment]
@exaby73 Hi thanks for the reply :)

**Comment by fzyzcjy** [comment]
@exaby73 Btw I see it labeled "new feature", but indeed it seems like a bug

**Comment by exaby73** [comment]
@fzyzcjy Sorry. My mistake. Thanks :)

**Comment by fzyzcjy** [comment]
It is ok :)
