### ISSUE TITLE
[Impeller] In Playground, implement a swap to Skia backend for comparison

### ISSUE THREAD

**Issue by flar** [flutter/flutter#109271]
Perhaps pressing 's' to quick swap to Skia while pressed and/or 'S' - one could swap while pressed, the other could toggle.

**Comment by chinmaygarde** [comment]
Good suggestion, we could parameterize the display list unittests harness to begin with.

**Comment by chinmaygarde** [comment]
Looking into this some more, I don't think this makes sense for any playground other than maybe the display list one because all other variants use Impeller specific APIs.
