### ISSUE TITLE
Experimenting with Flutter

### ISSUE THREAD

**Issue by afandria** [flutter/flutter#1092]
How do you try out new layouts in Flutter? Do you usually modify your app, or create a dummy app with the relevant layout?

In HTML/JS/CSS land, it was a lot easier. I could modify the DOM directly and see what happened in the browser. That would allow me to test many UI changes quickly. However, for Flutter, that is not possible.

Thus, I currently modify my app. This can be troublesome since it takes a while to get my app into the right state to see my changes. Creating a dummy app is hard too, since some layouts are quite complex.

I mainly am seeking advice on how to best experiment with my app's layout.

Related to this is the idea for a Flutter playground #327

**Comment by Hixie** [comment]
If your app has routes, you can use `flutter listen` and pass it the route name of the page whose layout you're testing. Assuming you have good startup performance, that gives you an edit-save-look cycle on the order of one second.

**Comment by sethladd** [comment]
Thanks for the feedback! We're taking a look at improving our edit/refresh times. I'm going to close this issue, and redirect over to https://github.com/flutter/flutter/issues/3377,  but definitely please continue sending us feedback.

cc @devoncarew
