### ISSUE TITLE
[CP] cherry pick https://github.com/flutter/flutter/pull/109185

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#109244]
### issue_link

https://github.com/flutter/flutter/issues/109241

### Commit Hash

https://github.com/flutter/flutter/commit/5805f4544534ccb3200e50625f1dd79cd9881b1f

### Target

beta

### pr_link

https://github.com/flutter/flutter/pull/109345

### Impacted Users

All desktop AOT and Web users

### Impact Description

Will impact every production desktop (AOT and Web) app that uses `RawAutocomplete` directly or transitively. The autocomplete menu will prevent the user from picking items from the suggested list.

### Workaround

Rewrite the app to not use the autocomplete functionality.

### Risk

low

### Test Coverage

yes

### Validation Steps

Use the examples in the API docs - https://api.flutter.dev/flutter/widgets/RawAutocomplete-class.html

**Comment by itsjustkevin** [comment]
@ditman could you take a look at this cherry-pick for stable?

**Comment by eyebrowsoffire** [comment]
Looks good to me!

**Comment by CaseyHillers** [comment]
@yjbanov for the PR link, it should be pointing to an open PR to the release branch.

**Comment by yjbanov** [comment]
> @yjbanov for the PR link, it should be pointing to an open PR to the release branch.

Done.

**Comment by yjbanov** [comment]
> > @yjbanov for the PR link, it should be pointing to an open PR to the release branch.
> 
> Done.

Done again. Looks like the stable branch doesn't have the bug yet. Or maybe I'm not cherry picking correctly.

**Comment by yjbanov** [comment]
Turns out the regression didn't make it into the beta
