### ISSUE TITLE
webview_flutter scroll feels sluggish on Android

### ISSUE THREAD

**Issue by LiangWGMillions** [flutter/flutter#109218]
Flutter Webview scrolling is leggy or not so smooth

webview_flutter plugin is lagging and keyboard problems

I tried to replicate the issue on latest dev channel but observed smooth scrolling. I tested on Android 8.1.0 and found issues of sluggishness.

flutter webview very slow than react native webview 

how to solve this problem

**Comment by exaby73** [comment]
Hello @LiangWGMillions. If you are experiencing smooth scrolling on the latest dev channel, then this issue seems to be fixed. It would land in a future stable release. I am therefore, closing this issue. If you disagree, then please comment and we can reopen it. Thank you

**Comment by LiangWGMillions** [comment]
when will update stable release？

**Comment by exaby73** [comment]
You can find more information on the release process [here](https://github.com/flutter/flutter/wiki/Flutter-build-release-channels#will-a-particular-bug-fix-be-provided-in-a-hotfix-release) and [here}(https://github.com/flutter/flutter/wiki/Release-process)
