### ISSUE TITLE
[Feature request] Improve of SEO using router

### ISSUE THREAD

**Issue by Pr47h4m** [flutter/flutter#109210]
## Use case
this idea covers enabling some good & easy SEO practices for web applications / websites built with flutter

## Proposal

1) [when the app is running] material page with meta tags
- adding meta tags property inside material app can changes/replaces website's meta tags when the new page opens
this can be useful for application which is using navigator 1.0 and named routes, onGenerateRoute etc. for navigating inside application

2) [when the app is running] async router
- there should be functionality in router to make it async 
that is when new route is requested, application can make api call can fetch some information about the page from the server which can be added into material page at the same time when the route is changed 
also, router can provide one method which allows user to get loading progress of the page (which can be shown in UI)

3) adding sitemap.xml (manual)
- sitemap.xml file can be manually added inside /web/ folder

4) [when url is entered inside browser or posted on social platforms] server side loading of the first page 
- https://medium.com/@tookunna/flutter-web-seo-rich-web-link-preview-5116670369d4
- this can be useful when sharing url on social medias
- is it possible to add --server-side or similar flag while building web application so the application can be hosted on server 
and as a developer we can configure how pages should fetch information

**Comment by iapicca** [comment]
possibly related to https://github.com/flutter/flutter/issues/46789

**Comment by exaby73** [comment]
Hello @Pr47h4m. This issue looks like it can be a good addition to https://github.com/flutter/flutter/issues/46789. Please post your suggestions and upvote it so SEO related issues can be tracked there. I am marking this issue as a duplicate, though if you disagree with my decision, please do comment and we can reopen it if valid. Thank you
