### ISSUE TITLE
TextField automatically obtains the clipboard

### ISSUE THREAD

**Issue by 309791679** [flutter/flutter#109214]
flutter doctor -v

> ```
> Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
> [√] Flutter (Channel stable, 3.0.5, on Microsoft Windows [版本 10.0.19043.1826], locale zh-CN)
>     • Flutter version 3.0.5 at D:\flutter_windows_3.0.5-stable\flutter
>     • Upstream repository https://github.com/flutter/flutter.git
>     • Framework revision f1875d570e (4 weeks ago), 2022-07-13 11:24:16 -0700
>     • Engine revision e85ea0e79c
>     • Dart version 2.17.6
>     • DevTools version 2.12.2
>     • Pub download mirror https://pub.flutter-io.cn
>     • Flutter download mirror https://storage.flutter-io.cn
> 
> [!] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
>     • Android SDK at C:\Users\z\AppData\Local\Android\sdk
>     • Platform android-33, build-tools 33.0.0
>     • Java binary at: D:\android studio\android-studio2021.2.1\jre\bin\java
>     • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
>     ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
> 
> [X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
>     ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
> 
> [X] Visual Studio - develop for Windows
>     X Visual Studio not installed; this is necessary for Windows development.
>       Download at https://visualstudio.microsoft.com/downloads/.
>       Please install the "Desktop development with C++" workload, including all of its default components
> 
> [√] Android Studio (version 2021.2)
>     • Android Studio at D:\android studio\android-studio2021.2.1
>     • Flutter plugin can be installed from:
>        https://plugins.jetbrains.com/plugin/9212-flutter
>     • Dart plugin can be installed from:
>        https://plugins.jetbrains.com/plugin/6351-dart
>     • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
> 
> [√] Connected device (3 available)
>     • M2012K11AC (mobile) • 22b38ce • android-arm64  • Android 12 (API 31)
>     • Windows (desktop)   • windows • windows-x64    • Microsoft Windows [版本 10.0.19043.1826]
>     • Edge (web)          • edge    • web-javascript • Microsoft Edge 103.0.1264.77
> 
> [√] HTTP Host Availability
>     • All required HTTP hosts are available
> ```
> 

When textfield has focus, the  will get the clipboard hundreds of times per minut
I used the Xiaomi application behavior record and found that it had an impact on my work
which leads to triggering compliance issues
---------------------------------------------------------------------------------------------------------------------------------------------------
Please give me a solution

**Comment by 309791679** [comment]
![image](https://user-images.githubusercontent.com/26238458/183619340-aeecb531-3697-4ce0-85f8-3918faf78fed.png)

**Comment by exaby73** [comment]
Hello @309791679. Is it possible for you to share a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)? Also, is this reproducible on other platforms like desktop, web or iOS, or can it be reproduced on an Android Emulator for example? Thank you

**Comment by 309791679** [comment]
> 你好@309791679。您是否有可能分享一个[最小的，可重复的示例](https://stackoverflow.com/help/minimal-reproducible-example)？此外，这是否可以在桌面，Web或iOS等其他平台上复制，或者是否可以在Android模拟器上复制？谢谢

In fact, I simply used textfield

```
    Container(
                          width: 220.r,
                          child: TextField(
                            style: TextStyle(
                              fontSize: 18.sp,
                              fontFamily: FontType.D_DINBold,
                              color: Color.fromRGBO(11, 15, 22, 1),
                              textBaseline: TextBaseline.alphabetic,
                            ),
                            //autofocus: true,
                            // showCursor: true,
                            // readOnly: true,
                            maxLines: 1,

                            cursorRadius: Radius.circular(18.r),
                            cursorWidth: 3.r,

                            // keyboardType: NumberKeyboar.inputType1,
                            maxLength: 11,
                            maxLengthEnforcement: MaxLengthEnforcement.enforced,
                            inputFormatters: [
                              FilteringTextInputFormatter.allow(
                                  RegExp("[a-z,A-Z,0-9]"))
                            ],

                            decoration: InputDecoration(
                              hintText: "password",
                              hintStyle: TextStyle(
                                  color: Color.fromRGBO(164, 167, 173, 1),
                                  fontFamily: FontType.Ali_Regular,
                                  fontSize: 16.sp),
                              counterText: "",
                              filled: true,
                              enabledBorder: OutlineInputBorder(
                                borderSide:
                                    BorderSide(color: Colors.transparent),
                                borderRadius: BorderRadius.all(
                                  Radius.circular(55.r),
                                ),
                              ),
                              focusedBorder: OutlineInputBorder(
                                borderSide:
                                    BorderSide(color: Colors.transparent),
                                borderRadius: BorderRadius.all(
                                  Radius.circular(55.r),
                                ),
                              ),
                              contentPadding: EdgeInsets.only(
                                  left: 8.r, right: 0.r, bottom: 0.r, top: 0.r),
                              fillColor: Color.fromRGBO(249, 250, 252, 1),
                            ),
                            onChanged: (value) {},

                            onSubmitted: (value) {},
                          ),
                        ),
```

**Comment by 309791679** [comment]
@exaby73, This is my source code

**Comment by exaby73** [comment]
@309791679 Can you provide a sample `main.dart` file that can be run with little to no changes?

**Comment by 309791679** [comment]
> @309791679您能否提供一个示例文件，该文件几乎不需要更改即可运行？`main.dart`
Well, this is a complete source code @exaby73
```
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Container(
          width: 220,
          child: TextField(
            style: TextStyle(
              fontSize: 18,
              color: Color.fromRGBO(11, 15, 22, 1),
              textBaseline: TextBaseline.alphabetic,
            ),
            maxLines: 1,
            cursorRadius: Radius.circular(18),
            cursorWidth: 3,
            maxLength: 11,
            maxLengthEnforcement: MaxLengthEnforcement.enforced,
            inputFormatters: [
              FilteringTextInputFormatter.allow(
                  RegExp("[a-z,A-Z,0-9]"))
            ],

            decoration: InputDecoration(
              hintText: "password",
              hintStyle: TextStyle(
                  color: Color.fromRGBO(164, 167, 173, 1),),
              counterText: "",
              filled: true,
              enabledBorder: OutlineInputBorder(
                borderSide:
                BorderSide(color: Colors.transparent),
                borderRadius: BorderRadius.all(
                  Radius.circular(55),
                ),
              ),
              focusedBorder: OutlineInputBorder(
                borderSide:
                BorderSide(color: Colors.transparent),
                borderRadius: BorderRadius.all(
                  Radius.circular(55),
                ),
              ),
              contentPadding: EdgeInsets.only(
                  left: 8, right: 0, bottom: 0, top: 0),
              fillColor: Color.fromRGBO(249, 250, 252, 1),
            ),
            onChanged: (value) {},

            onSubmitted: (value) {},
          ),
        ),
      ),

    );
  }
}
```

**Comment by exaby73** [comment]
Hello @309791679. Unfortunately, I cannot reproduce this issue. Is this issue possible to be reproduced on a Pixel device, like an emulator?
