### ISSUE TITLE
[Proposal] Add a new Target Platform to identify apple silicon macs

### ISSUE THREAD

**Issue by samithe7** [flutter/flutter#109235]
apple mSeries  macos support   ios app  . now TargetPlatform.macOS only support   defaultTargetPlatform   . need a new TargetPlatform.mSeries   in web  so we tell our user download our app .

```dart
 if (defaultTargetPlatform == TargetPlatform.iOS ||
        defaultTargetPlatform == TargetPlatform.android ||  defaultTargetPlatform == TargetPlatform.mSeries  ) {

      return DownloadAppPage();
        }else {
      return Webpage();       }

```

**Comment by maheshmnj** [comment]
Hi @samithe7, Thanks for filing the issue. If I understand it right you want to determine apple silicon macs 
to run [IOS app on a Mac](https://developer.apple.com/documentation/apple-silicon/running-your-ios-apps-in-macos) is that correct?

if so why not just use a boolean constant  `kIsWeb`

```dart
if(kIsWeb){
 return Webpage(); 
}else{
 return DownloadAppPage();
 }
```

**Comment by samithe7** [comment]
Thanks ,

But kIsWeb   A constant that is true if the application was compiled to run on the web.

i have  a same app both android  , ios  and web  .now i  want when a user use my web app  tell him  download  ios or android app  if  he use  web app   TargetPlatform.iOS or 
   TargetPlatform.android  or  TargetPlatform.appleSilicon .

**Comment by maheshmnj** [comment]
> i have a same app both android , ios and web .now i want when a user use my web app tell him download ios or android app

@samithe7  just wondering whats the issue with using 

```dart
if(TargetPlatform.android){
 return AndroidApp();
}else if(TargetPlatform.ios){
return IOSApp();
}
...
...
```

**Comment by maheshmnj** [comment]
Hi @samithe7,

There is a similar issue describing this case https://github.com/flutter/flutter/issues/78151, Please follow up there for further updates, Closing this issue as a duplicate. If you disagree feel free to write in the comments and we will reopen it.

Thank you.
