### ISSUE TITLE
Target file "android" not found & Target file "ios" not found

### ISSUE THREAD

**Issue by hrmiraj** [flutter/flutter#109243]
Have tried running via android studio and in flutter run android it throws Target file "android" not found. same error for ios simulator

flutter doctor -v
[✓] Flutter (Channel stable, 2.10.1, on Mac OS X 10.15.7 19H1824 darwin-x64, locale en-PK)
    • Flutter version 2.10.1 at /Users/ale/Developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db747aa133 (6 months ago), 2022-02-09 13:57:35 -0600
    • Engine revision ab46186b24
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/ale/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • ANDROID_HOME = /Users/ale/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.68.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.42.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 104.0.5112.79

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

**Comment by maheshmnj** [comment]
Hi @hrmiraj, Thanks for filing the issue. Please ensure your project contains android and ios folders, if they are not present then please try running `flutter create .`. If the issue persists I would suggest upgrading to the latest stable release.

**Comment by hrmiraj** [comment]
@maheshmnj Issue resolved by updating Flutter Version, Android, and SDK
