### ISSUE TITLE
Issue from website page 起步: 配置编辑器

### ISSUE THREAD

**Issue by Huangjialan** [flutter/flutter#109282]
From URL: https://www.flutterchina.club/get-started/editor.md，vs code的标签切换点击不了，控制台找不到jquery的插件，报错

**Comment by laiiihz** [comment]
编辑器相关请参考 https://flutter.cn/docs/get-started/editor

> From URL: [https://www.flutterchina.club/get-started/editor.md，vs](https://www.flutterchina.club/get-started/editor.md%EF%BC%8Cvs) code的标签切换点击不了，控制台找不到jquery的插件，报错

**Comment by wwwqyhme** [comment]
你这个是官方维护的吗？如果不是，不要发在这里

**Comment by danagbemava-nc** [comment]
Hi all, the flutterchina website is not maintained by the flutter team but rather by the community. 

Kindly report this issue on their issue tracker https://github.com/flutterchina/website/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc. 

Closing from here. 

Thank you
