### ISSUE TITLE
FlutterFire Query parameters

### ISSUE THREAD

**Issue by dac3971** [flutter/flutter#10923]
I'm new to FlutterFire so I'm sure it's something simple, but I'm having trouble with query parameters to limit the size of my snapshot.  For example, in flutter/plugins/blob/master/packages/firebase_database/example/lib/main.dart, I added a limitToLast(2) parameter but it still prints out the entire `messages` node:

```dart
final DatabaseReference _messagesRef =
FirebaseDatabase.instance.reference().child('messages');

final DataSnapshot snapshot = await _messagesRef.limitToLast(2).once();
print(snapshot.value);
```

Why isn't the limitToLast being recognized?

**Comment by eseidelGoogle** [comment]
@collinjackson would know.

**Comment by collinjackson** [comment]
which version of firebase database are you using?

**Comment by dac3971** [comment]
maybe that's it.  what's the latest version?  from my pubspec file : 
`firebase_database: ^0.0.4`

**Comment by collinjackson** [comment]
Try 0.0.11

**Comment by Hixie** [comment]
@dac3971 Any luck?

**Comment by dac3971** [comment]
@Hixie @collinjackson All good and thank you! Sorry for the late response!

**Comment by kroikie** [comment]
@dac3971

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/988. Any further collaboration will be done there.
