### ISSUE TITLE
> Run with --info or --debug option to get more log output. > Run with --scan to get full insights.  * Get more help at https://help.gradle.org  BUILD FAILED in 7m 6s Exception: Gradle task assembleDebug failed with exit code 1

### ISSUE THREAD

**Issue by salimnjopeka** [flutter/flutter#109305]
I have faced this issue after installing the cloud_firestore packages
Anyone can help me please

**Comment by danagbemava-nc** [comment]
Hi @salimnjopeka, please provide the following: 

- your flutter doctor - v
- the output of either `flutter run -v` or `flutter build apk -v` (depending on what command you're experiencing the issue with). The output may be huge, so kindly put it into a .txt file and attach it here. 
- your pubspec.yaml

Thank you
