### ISSUE TITLE
Renew cirrus key which expires on 08/15/2022

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#109367]
Documentation in:

[https://g3doc.corp.google.com/company/teams/flutter/security/cirrus/index.md?cl=head#create-a-new-key](https://www.google.com/url?q=https://g3doc.corp.google.com/company/teams/flutter/security/cirrus/index.md?cl%3Dhead%23create-a-new-key&sa=D&source=calendar&ust=1660584696661296&usg=AOvVaw2Ty82-H8xaGFN6aLI2pcIl)

These keys will expire on Aug 15, and should be updated 1 week in advance.

Also, need to renew plugins firebase account.

[https://pantheon.corp.google.com/iam-admin/serviceaccounts/details/107738294387118941537/keys?project=flutter-cirrus](https://www.google.com/url?q=https://pantheon.corp.google.com/iam-admin/serviceaccounts/details/107738294387118941537/keys?project%3Dflutter-cirrus&sa=D&source=calendar&ust=1660584696661296&usg=AOvVaw2vlo7gPTBDtEufKtgNzvel)

**Comment by yusuf-goog** [comment]
Created https://github.com/flutter/flutter/issues/109469 to track lint errors on existing code in assets-for-api-docs

**Comment by yusuf-goog** [comment]
waiting till end of week to delete the old key and close this.

**Comment by godofredoc** [comment]
@yusuf-goog can we close this one?

**Comment by godofredoc** [comment]
Actually deleted the old key as it was expired anyway.
