### ISSUE TITLE
If FAB and Snackbar are in 2 separate (nested) Scaffolds, the FAB is not pushed up

### ISSUE THREAD

**Issue by ArcticZeroo** [flutter/flutter#10930]
## Steps to Reproduce

This widget shows the issue:

```dart
class HelloWorldHome extends StatelessWidget {
  final String title;

  HelloWorldHome({Key key, this.title}) : super(key: key);

  Widget buildBody(BuildContext context) {
    return new Scaffold(
        body: new Center(
            child: new Text('Hello World!')
        ),
        floatingActionButton: new FloatingActionButton(child: new Icon(Icons.chat), onPressed: ()=> Scaffold.of(context).showSnackBar(new SnackBar(content: new Text('Hello World!'))))
    );
  }

  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(
          title: new Text(title)
      ),
      body: new Builder(builder: buildBody)
    );
  }
}
```
When the FAB is pressed, a snackbar shows up on top of the nested FAB, since the BuildContext is used from the parent widget, where there is no FAB. I'm not sure if this is technically intended behavior, but it seems a bit wonky.

**Comment by eseidelGoogle** [comment]
This may be expected behavior.  @Hixie would know.

Do you need two Scaffolds?  Is there something you're attempting to achieve with two we can help you achieve otherwise?

**Comment by ArcticZeroo** [comment]
I was looking for any way to make a FAB press open a snackbar, and I've got no clue how to get the current scaffold's build context aside from a builder and creating a new scaffold with a FAB in it. 
Thinking about it now, I could probably set the first scaffold to have a FAB in a class that extends FloatingActionButton and that builds with the correct context.

**Comment by Hixie** [comment]
`Scaffold.of(context)` will give you access to the "current" scaffold.

This is working as intended.

**Comment by Hixie** [comment]
That is, your code should work fine if you just remove the inner scaffold.

**Comment by Hixie** [comment]
Oh, wait, I see what you're saying. Just put the builder in the `floatingActionButton` slot on your outer scaffold.

**Comment by ArcticZeroo** [comment]
Perfect, it seems the only issue here is me not being familiar enough with flutter yet. Thanks for the help 😄
