### ISSUE TITLE
After sending hot reload with `pause: true` isolate unexpectedly resumes immediately after PausePostRequest

### ISSUE THREAD

**Issue by DanTup** [flutter/flutter#10934]
I'm using `flutter run --machine` and sending a hot reload with `pause: true` in order to allow me to resend breakpoints after the reload completes (by handling `PausePostRequest`). However it seems that the isolate is immediately unpausing after the `PausePostRequest`.

I've managed to reproduce this in a small script (attached). It runs the example stocks app and after 10secs issues a hot reload, logging flutter and observatory communications. It does not set any breakpoints and it does not `--start-paused`.

[restart_pause.ts (typescript)](https://github.com/flutter/flutter/files/1098588/restart_pause.ts.txt)
[restart_pause.txt (log)](https://github.com/flutter/flutter/files/1098589/restart_pause.txt)

The interesting part of the log is this:

```text
// Send hot reload
FLUTTER: ==> [{"id":1,"method":"app.restart","params":{"appId":"ea01d925-b17a-48bc-8f25-d8ef8e1043ac","fullRestart":false,"pause":true}}]

// Hot reload starts
FLUTTER: <== [{"event":"app.progress","params":{"appId":"ea01d925-b17a-48bc-8f25-d8ef8e1043ac","id":"2","progressId":"hot.reload","message":"Initializing hot reload..."}}]

// PausePostRequest comes in (this is when I plan to re-send breakpoints and then issue a resume)
<== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Debug","event":{"type":"Event","kind":"PausePostRequest","isolate":{"type":"@Isolate","...

// #################
// But wait..., why did this happen?!
// #################
<== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Debug","event":{"type":"Event","kind":"Resume","isolate":{"type":"@Isolate","fixedId":t...

// Hot reload completes
FLUTTER: <== [{"event":"app.progress","params":{"appId":"ea01d925-b17a-48bc-8f25-d8ef8e1043ac","id":"2","progressId":"hot.reload","finished":true}}]
```

**Comment by jason-simmons** [comment]
Debugger::Pause is calling the DebuggerEventHandler in debugger_api_impl.cc, which ignores PausePostRequest events.  After DebuggerEventHandler returns, Debugger::Pause proceeds to send the Resume event and continue.

What is DebuggerEventHandler supposed to do here?
The default Isolate::PauseEventHandler will process service messages until receiving a resume message.

**Comment by a-siva** [comment]
I would think we should process service messages in a loop until a resume is received. I was wondering how this is handled in IntelliJ, do we have a similar issue in IntelliJ?

**Comment by DanTup** [comment]
Should I re-raise this in the sdk project or will it progressed from here?

@devoncarew If you think IntelliJ doesn't have this issue, do you know why? Is it something I can copy in the meantime?

**Comment by devoncarew** [comment]
I don't see the auto-resume behavior. I did see a potential deadlock issue, after resuming, reloading, setting and unsetting breakpoints. I was running flutter run with -v to get a bit more debugging info. The message I saw was: `Refreshing active FlutterViews before reloading.`, and the VM didn't resume from there.

It looks like we attempt to list the flutter views here:
https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/run_hot.dart#L414, with a check to make sure the isolate we're calling isn't paused, but that could be a bit racy, in that we won't know that it's paused when we try and list the views.

**Comment by B3rn475** [comment]
https://github.com/flutter/engine/pull/3833

**Comment by devoncarew** [comment]
> I don't see the auto-resume behavior.

Strike that - I did some more investigation on my end, and do see an auto-resume when debugging with Intellij.

**Comment by DanTup** [comment]
@devoncarew Glad it's consistent and not just me! I don't suppose you also see https://github.com/flutter/flutter/issues/11040? It'd probably much easier to debug if you can repro internally; it might be a while before I can get any more useful info that is in the logs attached there.

**Comment by a-siva** [comment]
We seem to be criss crossing two issues here
- there is a general deadlock issues when flutter views are refreshed and this being tracked in #10615 for which @B3rn475 has a proposed fix at [](https://github.com/flutter/engine/pull/3833)
(Please post comments related to the deadlock issue on this other issue).

- the second issue is the 'pause:true' parameter in hot reload not having any effect. We will track this bug here.
