### ISSUE TITLE
`Mac Host Engine` flakes on `ShellTest`

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#109332]
- Example builds for `WaitForFirstFrame` flakes:
https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20Host%20Engine/17415/overview

- Example builds for `WaitForFirstFrameMultiple ` flakes:
https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20Host%20Engine/17343/overview

**Comment by chinmaygarde** [comment]
We'll have to take a look at this more closely. We did not verify the logic around the signaling of the waiting_for_first_frame_condition_ CV in the test fixture.

@keyonghan How often is this happening?

**Comment by keyonghan** [comment]
> We'll have to take a look at this more closely. We did not verify the logic around the signaling of the waiting_for_first_frame_condition_ CV in the test fixture.
> 
> @keyonghan How often is this happening?

By the time I filed this bug, it flakes twice (those two listed in the bug description) in the recent 100 commits.

**Comment by chinmaygarde** [comment]
I took a look at this the other day and the issue may be in latching around a utility in the fixture itself. So it should affect all tests that wait for frames. I haven't had a chance to take a closer look at fixing this. If this has no takers this week, I can spend some time getting to the bottom of it.

**Comment by zanderso** [comment]
Over the last ~100 builds `Mac Host Engine` has flaked only twice, so I am going to reduce the priority of this relative some work that's happening for the upcoming stable.

**Comment by zanderso** [comment]
Closing as presumed stale.
