### ISSUE TITLE
styles for lists inside dartdocs don't get wrapped to the same margin as paragraphs

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#10936]
Which makes things weird like this:
https://master-docs-flutter-io.firebaseapp.com/flutter/widgets/State-class.html

cc @sethladd @jcollins-g

**Comment by jcollins-g** [comment]
@devoncarew This seems likely to be a dartdoc-wide issue.

**Comment by devoncarew** [comment]
Changing styles.css, line 77, to `.main-content section` will wrap everything, `p`, `li`, and `dd`. I assume that's what we'd want? We don't want any content long? Or, just content in that initial user-written section? In which case we'd just want `.main-content section.markdown`.

**Comment by zoechi** [comment]
Not sure if I'm missing something but the list looks good to me.
