### ISSUE TITLE
Add a way to attach widgets to the top border of DraggableScrollableSheet

### ISSUE THREAD

**Issue by subzero911** [flutter/flutter#109307]
## Use case

That's what I want to achieve
![image](https://user-images.githubusercontent.com/12999702/183904915-417d9b60-3919-406c-bbac-ce54b027b205.png)
These choice chip buttons should move with panel sticking to its top.
The problem is I cannot just wrap a sheet into the Stack and use Positioned, because a panel crops everything that is out. If I set `clipBehaviour` to `None`, there's another problem - buttons outside the Stack are not clickable. They won't react to gestures. It's a known issue of the Stack which won't be fixed.
https://stackoverflow.com/questions/62258640/flutter-overflowed-positioned-button-is-not-clickable
https://github.com/flutter/flutter/issues/19445

I also tried a method of a widget position dynamic calculation in an onPanelSlide callback, as described in a video below (super inconvenient)
https://youtu.be/s9XHOQeIeZg?t=527
But it has a problem that attached buttons are wobbling when dragging the sheet up and down. See the video: https://disk.yandex.ru/i/0Z4Rn1UVcvM9Ew
It's because their positions are recalculated and redrawn in response to the panel dragging, and it slightly delays.

## Proposal

Consider adding the `attachedWidgets:` property. The List of widgets inside of this property will be attached to the DraggableScrollableSheet, and will move with it.

**Comment by maheshmnj** [comment]
Hi @subzero911, Thanks for filing the issue . Can you please share a  minimal and complete code sample that shows this issue?

> The problem is I cannot just wrap a sheet into the Stack and use Positioned, because a panel crops everything that is out
