### ISSUE TITLE
[flutter_markdown] Add support for rendering on canvas

### ISSUE THREAD

**Issue by CodeDoctorDE** [flutter/flutter#109373]
## Use case

I have a note taking app where I want to support adding markdown in the canvas.
Currently flutter_markdown has only a widget that I can't render on a canvas.

## Proposal

Add a MarkdownPainter (like the [TextPainter](https://api.flutter.dev/flutter/painting/TextPainter-class.html)) that supports rendering markdown on a canvas.

**Comment by stuartmorgan** [comment]
The package works by building a widget tree; it's not a leaf object that has custom render logic. Given that, rendering to another target is out of scope for the package.
