### ISSUE TITLE
toImageSync should use kPremul_SkAlphaType

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#109372]
Right now it's using kUnpremul_SkAlphaType, which is resulting in darker anti-aliasing around edges, e.g. compare the square on bottom to the one on top:

<img width="127" alt="image" src="https://user-images.githubusercontent.com/8620741/184067414-71c3a08d-865a-4723-8a40-3640886ec2f2.png">

They're made form the same picture drawn like this:

```dart
Future<List<ui.Image>> drawImage() async {
  var recorder = ui.PictureRecorder();
  var canvas = ui.Canvas(recorder);
  canvas.drawRect(ui.Rect.fromLTWH(20, 20, 100, 100),
      ui.Paint()..color = ui.Color(0xFFFF6D00));
  var picture = recorder.endRecording();
  var toImageImage = await picture.toImage(200, 200);
  var toImageSyncImage = picture.toImageSync(200, 200);
  return [toImageImage, toImageSyncImage];
}
```

The `toImage` image is on top, the `toImageSync` image is on bottom. Changing https://github.com/flutter/engine/blob/5f92d3668c7a172be23df13eebd24ab7e7df29ee/lib/ui/painting/picture.cc#L71 to `kPremul_SkAlphaType` seems to fix this, but probably deserves to be tested to make sure it works - Im' pretty sure I tried unpremul at one point to try to get Linux to be happy, before finally just putting Linux on the software path for now.

@jonahwilliams fyi. If you don't get to this first, I'll pick it up when I come back next week. We may want a golden test that asserts the bytes are the same between these calls.

**Comment by jonahwilliams** [comment]
Thank you Dan!
