### ISSUE TITLE
[docs] Docs seems to be incorrect for NetworkInterface->listSupported

### ISSUE THREAD

**Issue by larssn** [flutter/flutter#109310]
The docs claim that the `list` method is unsupported on Android, but I just tried it, and it worked without a hitch.

Source: https://api.dart.dev/stable/2.17.6/dart-io/NetworkInterface/listSupported.html

**Comment by darshankawar** [comment]
The link is now updated. https://api.flutter.dev/flutter/dart-io/NetworkInterface/listSupported.html
Closing as such.
