### ISSUE TITLE
Build Failed for flutter project in Xcode

### ISSUE THREAD

**Issue by akshay-kapase** [flutter/flutter#109343]
/Users/user/Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/webview_flutter_wkwebview-2.7.2/ios/Classes/webview-umbrella.h: No such file or directory (in target 'webview_flutter_wkwebview' from project 'Pods')

**Comment by maheshmnj** [comment]
Hi @akshay-kapase, Thanks for filing the issue. Can you please share steps to reproduce the issue?  Are you using   `webview_flutter_wkwebview` plugin directly or depending on `webview_flutter`? Also ensure you are using the latest version of the plugin.
