### ISSUE TITLE
FIrebaseAnimatedLists with reverted and inverseSorted asserts()

### ISSUE THREAD

**Issue by DarkZeros** [flutter/flutter#109302]
## Steps to Reproduce

Using "FirebaseAnimatedList" to update from a remote DB.
It will trigger item insertion/removal as the remote DB changes.

When the FirbaseAnimatedList is configured with:
`FirebaseAnimatedList (reverse: true, sort: (DataSnapshot a, Datasnapshot b) => b.key.compareTo(a.key))`

It will show the results in sorted in inverted order, and in reverse order.
Effectively pushing the list "down" rather than "up" (default).

However, inserting new elements will now occur on index -1 (before the first index).
And will trigger an exception in debug builds on:
https://github.com/flutter/flutter/blob/5c44057d853caab9ed372268e69e55f2a159a573/packages/flutter/lib/src/widgets/animated_list.dart#L533

However, this is not a real issue, and the
`final int itemIndex = _indexToItemIndex(index);`
corrects the index location later on.

**Expected results:**
It should not except on debug builds, relax the assert() constrain.

**Actual results:** 
Asserts on https://github.com/flutter/flutter/blob/5c44057d853caab9ed372268e69e55f2a159a573/packages/flutter/lib/src/widgets/animated_list.dart#L533
with index = -1, and the list ends up in a corrupted state (the last element is removed).

DRAFT SUBMISSION, I will update it later with more details 

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by exaby73** [comment]
Hello @DarkZeros. Can you please provide you `flutter doctor -v` and `flutter run -v` logs, as well as the contents of your `pubspec.yaml` file? Would be great if you can provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) as well. Thank you
