### ISSUE TITLE
`Mac Host Engine` flakes on `EmbedderTest`

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#109333]
- Example builds for `PushingMutlipleFramesSetsUpNewRecordingCanvasWithCustomCompositor` flakes:

https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20Host%20Engine/17401/overview
https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20Host%20Engine/17392/overview
https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20Host%20Engine/17370/overview
https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20Host%20Engine/17363/overview
https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20Host%20Engine/17328/overview

- Example builds for `PushingMutlipleFramesSetsUpNewRecordingCanvasWithoutCustomCompositor` flakes:

https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20Host%20Engine/17417/overview
https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20Host%20Engine/17384/overview

**Comment by chinmaygarde** [comment]
This test was added a couple of years ago. We should figure out the flake history and perhaps disable if necessary.

**Comment by chinmaygarde** [comment]
Looking at this test in detail, it is flaky/racy by design. There is no guard around the frame count being greater than zero. I also could not find any assertion that tests the setting up of a new recording canvas. We should delete the test.
