### ISSUE TITLE
`flutter run --web-launch-url` should allow URL to be https

### ISSUE THREAD

**Issue by nullrocket** [flutter/flutter#109369]
I have been working on getting `flutter run -d chrome` to sit behind a reverse proxy so I can debug with an environment more closely matching production such as  ssl, Secure headers, CSP, COOP and COEP.   One issue among many to making this work I discovered by accident.  

Once the `flutter run` command launches the browser and opens the default http://localhost:xxx  url any other browser tabs that attempt to connect via the reverse proxy are unable to fully load,  I don't pretend to understand why, some interaction with sse or wss.   Whatever it is I'm over trying to figure it out... maybe.   

What does work is never launching on the **http** url and instead opening the proxied **https** url. However the `--web-launch-url` flag doesn't allow an https url like `https://localhost:9921`

Looks like the problem is with the regex here not allowing https.

https://github.com/flutter/flutter/blob/47f54ace4568c079a2fdb66260d61a74ef5cca03/packages/flutter_tools/lib/src/web/web_device.dart#L134

**Comment by exaby73** [comment]
Hello @nullrocket. Thank you for filing this request. Looks like a valid one. Labelling for further insights from the team.

**Comment by yjbanov** [comment]
Deduplicating with https://github.com/flutter/flutter/issues/60704

**Comment by nullrocket** [comment]
If you read the other issue and this one carefully, while slightly related it is not a duplicate.  The other issue is about providing a way to actually handle ssl for localhost dev via flutter configuration.   

This is just about not restricting the web launch url to be http so that chrome will launch on whatever external proxy a developer provides as a launch url,  pretty much a 4 or 5 character change that doesn't involve any of the other issues around serving https talked about in the other issue.

I can provide a PR for this specific issue, and while the other things touched on in the referenced issue should be fixed, just getting this fixed would be a good first step.

Could we reopen this?
