### ISSUE TITLE
Flutter windows doesn't render UI when deployed on PC other than development PC. I used MSIX to compile the packages but It is White Screen

### ISSUE THREAD

**Issue by nattyalem** [flutter/flutter#109303]
Hello guys, I have been a flutter developer for about 2 years now and deployed many projects. Including 2 mobile apps and a desktop app im currently building. However, I have encountered a rather unsolvable problem, because it gives no error messages. After successfully testing the app on my pc I have compiled it in a MSIX package. Which installed successfully but couldnt display anything but the windows frame. Please help, Ive got a deadline. I have attached all the packages Ive used in my pubspec file. 
![Screenshot (4)](https://user-images.githubusercontent.com/51331781/183889109-24d2c40b-0f51-427d-abe3-4718ae6f7966.png)
![Uploading Screenshot (4).png…]()
everything is okay with flutter doctor and the packages. Please help!

**Comment by exaby73** [comment]
Hi @nattyalem, please provide a [minimal, reproducible example][1] and the output of `flutter doctor -v` as well as `flutter run -v` and steps you've taken to reproduce this issue. Thank you

[1]: https://stackoverflow.com/help/minimal-reproducible-example

**Comment by nattyalem** [comment]
I have attached the flutter doctor output with png and the flutter run -v output in a text file.
[flutter run -v.txt](https://github.com/flutter/flutter/files/9300167/flutter.run.-v.txt)
![Screenshot (5)](https://user-images.githubusercontent.com/51331781/183906274-f73ae6d1-ae18-4ecd-9c4c-f0b304511d25.png)

**Comment by exaby73** [comment]
From your doctor output, I see you are using Flutter 2.10.2. Please upgrade to stable and confirm if this is still an issue
