### ISSUE TITLE
Add NavigationKey in GoRouter

### ISSUE THREAD

**Issue by DieGlueckswurst** [flutter/flutter#109479]
## Steps to Reproduce

I am using the [go_router][1] in my app and also the [get][2] package. The problem is that since I implemented the `Go-Router` I can no longer show the `Get.snackbar`. It is failing and throwing a `null-error`. 

For the `GoRouter` to work I had to add the `.router` for my `GetMaterialApp`. And then `navigationKey` was no longer available:

This is my `GetMaterialApp`:

      child: GetMaterialApp.router(
        title: 'Wishlists',

        // navigationKey: Get.key, 
        // .router does not have a navigationKey so showSnackBar fails because the key is null

        routeInformationProvider: router.routeInformationProvider,
        routeInformationParser: router.routeInformationParser,
        routerDelegate: router.routerDelegate,
        translationsKeys: AppTranslation.translationsKeys,
        locale: locale,
        fallbackLocale: fallbackLocale,
    
      ),

This is the `error`:

> Error: Unexpected null value.
    at Object.throw_ [as throw] (http://localhost:51492/dart_sdk.js:5080:11)
    at Object.nullCheck (http://localhost:51492/dart_sdk.js:5399:30)
at [_configureOverlay] (http://localhost:51492/packages/get/get_navigation/src/snackbar/snackbar_controller.dart.lib.js:2970:53)
at [_show] (http://localhost:51492/packages/get/get_navigation/src/snackbar/snackbar_controller.dart.lib.js:3113:30)

I feel like it has something to do with the `key` inside the `GetMaterialApp`, but I have no idea how to solve this. 

Is this a known bug? What am I missing here?

  [1]: https://gorouter.dev/
  [2]: https://pub.dev/packages/get

**Comment by iapicca** [comment]
being able to customize [go_router](https://pub.dev/packages/go_router) is  generally good, so I'm supportive of the idea
especially when it seems to be an `easy fix`

```diff
  GoRouter({
    /// ...
+  GlobalKey<NavigatorState>? key,
  }) {
  /// ...
    _routerDelegate = GoRouterDelegate(
+     key: key,
    );
    /// ...
  }
```

```diff

  GoRouterDelegate({
     /// ...
+  GlobalKey<NavigatorState>? key,
  }) : builder = RouteBuilder(
        /// ...
-        );
+       ),
+     _key = key ??  GlobalKey<NavigatorState>();

   /// ...
+ final GlobalKey<NavigatorState> _key; 
-  final GlobalKey<NavigatorState> _key = GlobalKey<NavigatorState>();
```

Nonetheless this is yet another example of why devs should steer clear of [getX](https://pub.dev/packages/get)!
something as easy as [dysplay a snackbar ](https://docs.flutter.dev/cookbook/design/snackbars#2-display-a-snackbar)
```dart
ScaffoldMessenger.of(context).showSnackBar(snackBar);
```
being "vendor locked" is just **bad** (together with many other reasons, including[ fudged benchmarks](https://github.com/jonataslaw/getx/issues/789))

**Comment by exaby73** [comment]
Hello @DieGlueckswurst. Thanks for filing this request. Looks like a valid one. Labelling as such.

**Comment by chunhtai** [comment]
The pr https://github.com/flutter/packages/pull/2453#discussion_r949604346 adds the navigator key to gorouter

**Comment by rddewan** [comment]
Yes please we need this to be able to navigate with Firebase push notification click listener , with GoRouter we are not able to get the context to navigate

**Comment by DieGlueckswurst** [comment]
any updates on this? seems like a quick fix. would help me a lot :D

**Comment by iapicca** [comment]
> flutter/packages#2453 (comment)

you can find the updates here https://github.com/flutter/packages/pull/2453
