### ISSUE TITLE
iOS screenshot scaling is off

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#10942]
The screen rasterization code added in https://github.com/flutter/engine/pull/3281 returns the screen as zoomed in:

![1](https://user-images.githubusercontent.com/6687929/27499782-35b893b4-581a-11e7-9e13-b0ab844b57a5.png)

**Comment by eseidelGoogle** [comment]
What I hear you saying is that we're not handling the devicePixelRatio scaling correctly when capturing screenshots on iOS. Correct?

@cbracken @chinmaygarde :)

**Comment by mehmetf** [comment]
Yep.

**Comment by mehmetf** [comment]
This is starting to hurt Leafy in a significant way as our iOS user base expands. Any chance we can get a fix soon?

**Comment by Hixie** [comment]
cc @jason-simmons

**Comment by Hixie** [comment]
cc @cbracken

**Comment by Hixie** [comment]
@cbracken Are you still working on this? (If not, please unassign yourself. Thanks!)

**Comment by cbracken** [comment]
Yes - at the front of my queue as of this evening.

**Comment by cbracken** [comment]
This should be fixed. 

Verified on both a physical device and simulator with:
1. `s` in hot reload
2. `flutter screenshot` command
3. `driver.screenshot()` from a Flutter Driver test

One last place this needs to be tested will be in the feedback plugin screenshotter, once we've rolled internally.

**Comment by cbracken** [comment]
Re-opened as I've confirmed there's still an issue when picking up the screenshot via the feedback plugin screenshotting code.

**Comment by mehmetf** [comment]
Hmm, perhaps we should not be using any core utility functions. I am sending you an internal CL. Let me know what you think.

**Comment by mehmetf** [comment]
We fixed this internally.
