### ISSUE TITLE
Richtext used as 'header' in Expansion panel causes exception in app

### ISSUE THREAD

**Issue by simondhearn** [flutter/flutter#109477]
## Steps to Reproduce

 I've a screen, it has a expanndable panel and the 'header' or text of that expandable panel  is RichText and is touchable for using as button to move to another page.
Displaying this combo of RichText as header of expandable panel causes this exception

1. Execute `flutter run` on the code sample
[main.zip](https://github.com/flutter/flutter/files/9330157/main.zip)
 
2. ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @simondhearn, please provide the output of `flutter doctor -v` as well as the output of `flutter run -v` that captures the exception you're experiencing. 

Thank you

**Comment by simondhearn** [comment]
[flutter_doctor_verbose.txt](https://github.com/flutter/flutter/files/9336715/flutter_doctor_verbose.txt)
[flutter_run_v.txt](https://github.com/flutter/flutter/files/9336716/flutter_run_v.txt)

**Comment by danagbemava-nc** [comment]
Hi @simondhearn, your error seems to indicate that you need to wrap your ExpansionPanelList in a widget that can scroll. 

Can you try wrapping your `ExpandableLinkPageState()` with a `SingleChildScrollView` to see if the error disappears?

**Comment by simondhearn** [comment]
Thank you for your response. I placed a SingleChildScrollView as suggested.

This allowed the expandable panel to appear and be usable BUT an exception is raised below I'm also including a new flutter doctor and flutter run text file:

 ══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
            The following assertion was thrown during a scheduler callback:
            'package:flutter/src/semantics/semantics.dart': Failed assertion: line 3014 pos 16: 'node.parent ==
            null || !node.parent!.isPartOfNodeMerging || node.isMergedIntoParent': is not true.

            Eit
[flutter_doctor_verbose.txt](https://github.com/flutter/flutter/files/9349102/flutter_doctor_verbose.txt)
[flutter_run_v.txt](https://github.com/flutter/flutter/files/9349103/flutter_run_v.txt)
her the assertion indicates an error in the framework itself, or we should provide substantially
            more information in this error message to help you determine and fix the underlying cause.
            In either case, please report this assertion by filing a bug on GitHub:
              https://github.com/flutter/flutter/issues/new?template=2_bug.md

            When the exception was thrown, this was the stack:
            #2      SemanticsOwner.sendSemanticsUpdate (package:flutter/src/semantics/semantics.dart:3014:16)
            #3      PipelineOwner.flushSemantics (package:flutter/src/rendering/object.dart:1098:24)
            #4      RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:509:21)
            #5      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:892:13)
            #6      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:370:5)
            #7      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1146:15)
            #8      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1083:9)
            #9      SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:997:5)
            #13     _invoke (dart:ui/hooks.dart:151:10)
            #14     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308:5)
            #15     _drawFrame (dart:ui/hooks.dart:115:31)
            (elided 5 frames from class _AssertionError and dart:async)
            ════════════════════════════════════════════════════════════════════════════════════════════════════
[+2126 ms] 
           Another exception was thrown: 'package:flutter/src/semantics/semantics.dart': Failed assertion: line 3028 pos 14: 'node.parent?._dirty != true': is not true.

**Comment by danagbemava-nc** [comment]
Hi @simondhearn, you should be able to get rid of the exception by setting `canTapOnHeader` of the `ExpansionPanel` to `false`. I think this is happening because you have conflicting gestures with the `TapGestureRecognizer` and the gesture receiver on the ExpansionPanel header. 

I'll be closing this as an implementation issue. 

If you still experience this issue after setting `canTapOnHeader` to false, kindly leave a comment below and I will reopen this. 

Thank you
