### ISSUE TITLE
consecutive quarantine check safety valves

### ISSUE THREAD

**Issue by yusuf-goog** [flutter/flutter#109423]
@keyonghan we have had a couple of bad tests take down both our a02s test beds.

I don't believe the quarantine task has any context beyond the individual bot, i.e. it will keep on quarantining all bots that hit 6 fails, upto all the bots in the fleet.

Does it have a a way for us to stop quarantining bots after _n_ bots have been quarantined for a particular test? This will prevent a single bad test from taking out our fleet.

Ability to denylist particular tests so that they don't trigger the consecutive failure task (maybe from a .ci.yaml property like bringup:true).

**Comment by keyonghan** [comment]
It makes sense, but it's not an easy flag check favored from ci.yaml side as the config is controlled from chromium side.
What we can do is add some check from chromium config to ignore the task failure check if any condition meets, for example when a `.ignore_task_failure_check` file exists.

**Comment by yusuf-goog** [comment]
Can we use a similar mechanism to make sure not more than _n_ bots get quarantined?

Maybe we can have the task failure bot open tickets rather than quarantine the bots?

**Comment by keyonghan** [comment]
Obsolete as we have removed the logic to quarantine the bot.
