### ISSUE TITLE
Hide a bottom Nav bar && TabBar while scrolling 

### ISSUE THREAD

**Issue by AlaaBashar** [flutter/flutter#109499]
I encounter this trouble while I trying to hide the bottom Nav bar & TabBar together in same time by using "**NestedScrollView**" widget.<br><br> in addition, I link it between each other by controller with type "**ScrollController**" and here is the error, _how can I fix it_ ?<br>

```
 =========================== Exception caught by gesture ===========================
The following assertion was thrown while handling a gesture:<br>
'package:flutter/src/widgets/nested_scroll_view.dart': Failed assertion: line 774 pos 16: 'extra >= 0.0': is not true.<br>


when the exception was thrown, this was the stack: <br>

nestedScrollCoordinator._getMetrics (package:flutter/src/widgets/nested_scroll_view.dart:774:16)
nestedScrollCoordinator.createOuterBallisticScrollActivity (package:flutter/src/widgets/nested_scroll_view.dart:729:42)
nestedScrollCoordinator.goBallistic (package:flutter/src/widgets/nested_scroll_view.dart:679:7)
scrollDragController.end (package:flutter/src/widgets/scroll_activity.dart:412:14)
scrollableState._handleDragEnd (package:flutter/src/widgets/scrollable.dart:657:12)
dragGestureRecognizer._checkEnd.<anonymous closure> (package:flutter/src/gestures/monodrag.dart:485:47)
gestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:198:24)
dragGestureRecognizer._checkEnd (package:flutter/src/gestures/monodrag.dart:485:5)
DragGestureRecognizer.didStopTrackingLastPointer (package:flutter/src/gestures/monodrag.dart:393:9)
OneSequenceGestureRecognizer.stopTrackingPointer (package:flutter/src/gestures/recognizer.dart:392:9)
DragGestureRecognizer._giveUpPointer (package:flutter/src/gestures/monodrag.dart:402:5)
DragGestureRecognizer.handleEvent (package:flutter/src/gestures/monodrag.dart:321:7)
PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:94:12)
```

![WhatsApp Image 2022-08-13 at 6 36 31 PM](https://user-images.githubusercontent.com/70103176/184500967-c795c11e-6499-4482-95f5-6e584f37c16b.jpeg)

**Comment by exaby73** [comment]
Hi @AlaaBashar, please provide a [minimal, reproducible example][1] and the output of `flutter doctor -v` as well as `flutter run -v`.

[1]: https://stackoverflow.com/help/minimal-reproducible-example

**Comment by AlaaBashar** [comment]
Hi @exaby73 sorry for delaying <br>
here is a snapshot for flutter doctor && a little example<br>


![WhatsApp Image 2022-08-19 at 11 19 22 AM (1)](https://user-images.githubusercontent.com/70103176/185576475-c7dff483-4aee-4d48-8408-4206fdb85ce3.jpeg)
![WhatsApp Image 2022-08-19 at 11 19 22 AM](https://user-images.githubusercontent.com/70103176/185576481-e6126de3-efa4-4f6b-94a9-c6f94f97d2d2.jpeg)

**Comment by exaby73** [comment]
@AlaaBashar Can you please provide the code in text form? Create a new project, and write all the code needed to reproduce this issue in the `main.dart` file, and post the contents on said file so that I can verify the issue.
