### ISSUE TITLE
Add a widget that can expose an automatically disposed Text Edition Controller to it's children

### ISSUE THREAD

**Issue by Luckey-Elijah** [flutter/flutter#109410]
## Use case

- I'd like to have a widget that exposes a `TextEditingController` to it's child widget. 
- I do not want to have create a `StatefulWidget`/`State` to manage closing/disposing of the controller when I'm done using.

## Proposal

Create a widget that abstracts a `StatefulWidget` that is handles exposing `TextEditingController` to be used. Currently I have my own widget that achieves just this ([`TextControllerBuilder`](https://gist.github.com/Luckey-Elijah/b22ec214e6063b6c1df31abb4ac4f73b)):

I'd like to have some type of APl like:

```dart
class MyWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    // Using the new widget
    return TextControllerBuilder<TextEditingController>(
      builder: (context, controller) => TextField(controller: controller),
      create: () => TextEditingController(text: 'my initial text')..someOtherInitializerMethod(),
    );
  }
}

```

**Comment by iapicca** [comment]
you could use [flutter_hooks](https://pub.dev/packages/flutter_hooks), specifically [useTextEditingController](https://pub.dev/documentation/flutter_hooks/latest/flutter_hooks/useTextEditingController-constant.html) 
it's made by Remi, so basically first party quality

**Comment by maheshmnj** [comment]
Hi @Luckey-Elijah, Thanks for filing the issue. Provided that your use case can be achieved using a few lines of code or using some existing packages in the pub, I believe this is not required to be part of the framework. In case you disagree feel free to write in the comments and we will open it.

Thank you.
