### ISSUE TITLE
Textures created for decoded images must not exceed a certain threshold.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#10946]
Currently, we create textures for images at the same size as the size of the decompressed image. However, this texture size may be larger than necessary. For example, images larger than the native dimensions of the screen should probably only create textures that are clamped to the size of the screen. We should detect this and other such cases and create a downscaled texture version of the decompressed image data as appropriate. It is possible that the framework can provide hints about the intended rendering size of the image so that the image decoders can do a better job of determining the appropriate texture size.

Artifacts due to downscaling may be introduced. We may need to adopt techniques such as Lanczos resampling to adequately preserve fidelity.

**Comment by ened** [comment]
@chinmaygarde has this been worked on already or do you have suggestions on how to workaround with existing apps?

**Comment by jonahwilliams** [comment]
We currently clamp textures to the maximum texture size/scale down as needed. I don't think we could be any smarter here as we don't know how the decode image is going to be used. For example, it may be used as part of a giant atlas for a sprite based game.
