### ISSUE TITLE
flutter_tools report successful hot restart, while it failed

### ISSUE THREAD

**Issue by polina-c** [flutter/flutter#109486]
In VS Code:

1. Start debugging application
2. Modify the code, so that it does not compile
3. Click 'hot restart' 
4. Get message in debug console about successful restart

<img width="990" alt="Screen Shot 2022-08-12 at 2 12 33 PM" src="https://user-images.githubusercontent.com/12115586/184468045-ab15445f-d063-4fc2-bc88-12f7dc2f8304.png">

**Comment by jonahwilliams** [comment]
I think the file may not be saved - at least that is what it looks like in your screenshot. The little circle icon on instead of the `x` on the landing_screen.dart tab means the file has unsaved changes

**Comment by exaby73** [comment]
@polina-c As @jonahwilliams said, you haven't saved your file in Vscode. Therefore you are hot restarting your previous code. You can turn on auto-save in Vscode if you need it. Closing this issue as this is not an issue with Flutter.
