### ISSUE TITLE
l10n Multiple ICU pluralisation strings in arb files is not producing expected output 

### ISSUE THREAD

**Issue by Jack-Overflow** [flutter/flutter#109498]
I'm having issues with translation strings that have at least one or more ICU pluralisation strings. Where it is not adding any other placeholders into the translated string other than the single pluralisation string.

## Steps to Reproduce

1. Run flutter gen-l10n with this arb file:
```
{
  "asleepTime": "Asleep {hours, plural, =1{1 hour} other{{hours} hours}} {minutes, plural, =1{1 minute} other{{minutes} minutes}}",
  "@asleepTime": {
    "placeholders": {
      "hours": {
        "type": "num",
        "format": "decimalPattern"
      },
      "minutes": {
        "type": "num",
        "format": "decimalPattern"
      }
    }
  }
}
```
and this `l10n.yaml`
```
arb-dir: lang
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
```
2. Run Flutter accessing this translation in a Text() widget for example passing hours and minutes (example 14 hours 7 minutes).

**Expected results:** 
I expected to see a formatted string saying `Asleep 14 hours 7 minutes`;

**Actual results:** 
What actually shows is `Asleep 14 hours` shown below
<img width="142" alt="Screenshot 2022-08-13 at 15 21 59" src="https://user-images.githubusercontent.com/31845161/184498385-7c64f7fb-3936-4abf-a294-d133983cac28.png">

Why is it not possible to have any other placeholders in a translation string when there are one or more pluralisation strings?
This same issue happens when using the following configuration as well (minutes do not show):
```
{
  "asleepTime": "Asleep {minutes} {hours, plural, =1{1 hour} other{{hours} hours}}",
  "@asleepTime": {
    "placeholders": {
      "hours": {
        "type": "num",
        "format": "decimalPattern"
      },
      "minutes": {
        "type": "num",
        "format": "decimalPattern"
      }
    }
  }
}
```
I've tried so many different configurations of placeholders and still no luck, please help.

<details>
  <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.5 21G72 darwin-x64, locale en-GB)
    • Flutter version 3.0.5 at /usr/local/Caskroom/flutter/3.0.5/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (4 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/jack/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Users/jack/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/212.5712.43.2112.8815526/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Users/jack/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/212.5712.43.2112.8815526/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.70.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • iPhone 12 (mobile) • 3F1B4E9F-5722-4BAF-860B-A23BF4E9F2DA • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-5 (simulator)
    • macOS (desktop)    • macos                                • darwin-x64     • macOS 12.5 21G72 darwin-x64
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 104.0.5112.79

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by danagbemava-nc** [comment]
Hi @Jack-Overflow, I think this is not working because it hasn't been implemented yet. Can you take a look at https://github.com/flutter/flutter/issues/86906 to see if its similar to the issue you're experiencing?

**Comment by Jack-Overflow** [comment]
> Hi @Jack-Overflow, I think this is not working because it hasn't been implemented yet. Can you take a look at #86906 to see if it is similar to the issue you're experiencing?

Hi, yes that issue does seem to highlight the issue I am also experiencing. You say that it is not currently implemented, is there a suggested workaround currently?

**Comment by danagbemava-nc** [comment]
Hi @Jack-Overflow, I'm not aware of any workarounds at the moment. 

Kindly follow up in the linked issue for updates. Please upvote the issue as well. 

Closing from here as duplicate. 

Thank you
