### ISSUE TITLE
[google-map] Imprecise registration of Circle tap events

### ISSUE THREAD

**Issue by jaimin1531** [flutter/flutter#109446]
- Circle tap events are not working properly when i tap outside of the circle then also circle gets selected. and when we have a overlapping circles at that time we face issues while selecting a circle

**Comment by darshankawar** [comment]
@jaimin1531 
When opening an issue, please try to use new issue template and fill out requested details so that we'll have enough info to work with.
For now, please provide `flutter doctor -v`, plugin version, platform and minimal code sample along with actual vs expected results.
Thanks.

**Comment by jaimin1531** [comment]
@darshankawar 
sorry as i was unable to find any suitable template for my issue thats why i have created blank issue

here is my `flutter doctor -v` output
`[✓] Flutter (Channel stable, 3.0.5, on macOS 12.5 21G72 darwin-x64, locale en-GB)
    • Flutter version 3.0.5 at /Users/jaimin.galiya/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (4 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/jaimin.galiya/Library/Android/sdk/
    • Platform android-33, build-tools 32.0.0
    • ANDROID_HOME = /Users/jaimin.galiya/Library/Android/sdk/
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode_13.2.1.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.70.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.46.0

[✓] Connected device (4 available)
    • ONEPLUS A6010 (mobile) • c318f7d2                             • android-arm64  • Android 11 (API 30)
    • iPhone 11 (mobile)     • BED2A076-6E9A-4395-96BF-5A8CA10778F0 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-2
      (simulator)
    • macOS (desktop)        • macos                                • darwin-x64     • macOS 12.5 21G72 darwin-x64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 104.0.5112.79

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
`

This is how i generate my circles and then add them to the map
`Set<Circle> listOfCircles = <Circle>{};
for (var index = 0;
          index < locationList.length;
          index++) {
            var location = locationList[index];
listOfCircles.add(Circle(
              circleId: CircleId(location.myUniqueLocationId),
              consumeTapEvents: true,
              fillColor: Colors.grey.withOpacity(
                          0.5),
              strokeColor: Colors.grey,
              strokeWidth:1,
              center: LatLng(location.myLocationLatitude,
                  location.myLocationLongitude),
              onTap: () {
                print("location tapped ${location.myUniqueLocationId}");
              },
              radius: 250,
              zIndex: selectedLocation == location.myUniqueLocationId
                  ? locationList.length + 1
                  : index));
      }`

**Comment by darshankawar** [comment]
Can you try removing `consumeTapEvents` property and see if it makes any difference ?

**Comment by jaimin1531** [comment]
as per documentation if i make it false my onTap callback will not be triggered
<img width="478" alt="Screenshot 2022-08-12 at 6 53 52 PM" src="https://user-images.githubusercontent.com/85997845/184362854-9eb81280-e7d6-4078-986c-5fb1f863d8df.png">

**Comment by darshankawar** [comment]
Can you provide us complete minimal reproducible code sample (ex: main.dart) that we can directly run ?
Also, is this occuring only on Android or on iOS too ?
