### ISSUE TITLE
[go_router] Allow deep links to always push

### ISSUE THREAD

**Issue by johnpryan** [flutter/flutter#109400]
If a user is migrating from [named routes](https://docs.flutter.dev/cookbook/navigation/named-routes) to go_router, they might want to keep the same behavior where a deep link is always pushed no matter where the user is currently located (a new screen is always pushed onto the Navigator).

**Comment by johnpryan** [comment]
@chunhtai

**Comment by chunhtai** [comment]
relevant https://github.com/flutter/flutter/issues/103659

**Comment by chunhtai** [comment]
duplicates of https://github.com/flutter/flutter/issues/103659
