### ISSUE TITLE
[CP] Replace removed deprecated Ruby method in tool helper script

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#109476]
### issue_link

https://github.com/flutter/flutter/issues/109385

### Commit Hash

dce82f7

### Target

beta

### pr_link

https://github.com/flutter/flutter/pull/109475

### Impacted Users

Devs who upgrade to Ruby 3.2 and develop an iOS or macOS app with plugins (most apps)

### Impact Description

Ruby 3.2 is still in preview (beta), but has removed a deprecated method used in a Flutter script that runs when users build iOS or macOS apps that contain plugins.  When Ruby 3.2 is released (not sure the schedule, could be before the next Flutter stable) if users upgrade they will not be able to build or release their iOS or macOS apps.

Note for why test coverage confidence is low (no selected): I am confident we have good automated test coverage for the current stable version of Ruby where the deprecated and replacing method is present, so coverage that the method replacing the deprecation will work on stable Ruby.  However, we have no automated testing covering the preview version of Ruby.  However, I am confident via manual testing that the replacing method will work on both the current stable as well as the preview version.

### Workaround

Users can downgrade to current stable Ruby 3.1.2.  Users could also manually edit the Ruby script in the SDK.

### Risk

low

### Test Coverage

no

### Validation Steps

[Install](https://www.ruby-lang.org/en/documentation/installation) and use Ruby 3.2 (preview for now). RVM or other package manager is an install option.

On a Mac already set up for Flutter iOS development (Xcode, CocoaPods, etc):
```
$ cd /path/to/flutter-sdk/dev/integration_tests/flutter_gallery
$ flutter clean
$ flutter build ios
```
If build succeeds, fix is validated.

**Comment by itsjustkevin** [comment]
Marking this as approved.

CC: @CaseyHillers
