### ISSUE TITLE
[flutter_web] [useMaterial3] Letter spacing not rendered correctly in Hindi 

### ISSUE THREAD

**Issue by mrinaljain** [flutter/flutter#109449]
![WhatsApp Image 2022-08-12 at 17 59 17](https://user-images.githubusercontent.com/7473761/184354255-ceb6313f-5f47-4eac-a2ce-b0d8d29cd126.jpeg)

minimal code sample:

` ThemeData(
    useMaterial3: true,
    visualDensity: VisualDensity.adaptivePlatformDensity,
    brightness: Brightness.dark,
);`

It appears the error is only appearing when using the material theme styling. When I use custom style it works fine.

Flutter doctor output:

```
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.4 21F79 darwin-arm, locale en-IN)
    • Flutter version 3.0.5 at /Users/mrinal/FlutterDev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (4 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/mrinal/Library/Android/sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.70.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.46.0

[✓] Connected device (4 available)
    • ONEPLUS A6010 (mobile)   • cbb6df8d                                 • android-arm64  • Android 11 (API 30)
```
    • Mrinal’s iPhone (mobile) • 113dd7857af7a71e2032182c27cb198338540e0f • ios            • iOS 15.6 19G71
    • macOS (desktop)          • macos                                    • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)             • chrome                                   • web-javascript • Google Chrome 104.0.5112.79

[✓] HTTP Host Availability
    • All required HTTP hosts are available

**Comment by mrinaljain** [comment]
Hi @darshankawar   it somehow starts working if  I set the usematerial3 to false
`useMaterial3: false`

Rest it doesn't work even if I set the  letter spacing to 0

**Comment by darshankawar** [comment]
@mrinaljain 
Material 3 is not completely integrated in Flutter yet. See this open issue for your reference and tracking: https://github.com/flutter/flutter/issues/91605 and hence you might be seeing the issue. I suggest you to use `useMaterial3: false` for now until the linked issue is merged.

Also, read this on `useMaterial3` property usage / implementation, as this is temporarily an opt-in feature, until it lands in stable in future: https://api.flutter.dev/flutter/material/ThemeData/useMaterial3.html

Closing for now. If you disagree, write in comments and I'll reopen it.
