### ISSUE TITLE
[Conductor] Release branches should be inferred from the release type.

### ISSUE THREAD

**Issue by itsjustkevin** [flutter/flutter#109467]
We still require a `--candidate-branch` flag to start a release.

We maintain two branches:
- Stable: flutter-x.x-candidate.x
- Beta: flutter-x.x-candidate.x

We should be able to use the `--channel` flag to infer which candidate branch we want to use, eliminating another point of possible failure in starting a release.

**Comment by CaseyHillers** [comment]
Extending this further, we should migrate hash alignment into conductor. Then we could have automated systems generate the betas.

**Comment by XilaiZhang** [comment]
from triage: closing since conductor is now in maintenance mode
