### ISSUE TITLE
[Cocoon] Create PubSub topic for green commits

### ISSUE THREAD

**Issue by itsjustkevin** [flutter/flutter#109471]
Cocoon has the ability to track test statuses from LUCI.  

Cocoon exposing events such as: testsFailed(), testsComplete() etc, could be useful in sending signals to FRoB and other tools.

Example use cases:

Case 1: The conductor tool could use these signals to rerun steps or use a positive signal to auto-increment release steps.
Case 2: Rollers monitoring FRoB could get earlier signals on when engine binaries are complete.

CC: @CaseyHillers

**Comment by CaseyHillers** [comment]
To support release tools anywhere, this should be made into a pubsub topic. Cocoon can push when a commit has had all green builds (bringup: false).

Subscribers can determine their format (push vs pull)

**Comment by godofredoc** [comment]
Do we really need a new layer of complexity in cocoon for this use case?

If the purpose is to check pass/fail data this be obtained by subscribing directly to the swarming topic.

\cc @keyonghan

**Comment by keyonghan** [comment]
Just a context: we want to make sure all boxes (tasks) run with green on a single row.

**Comment by XilaiZhang** [comment]
This is no longer needed.

**Comment by ricardoamador** [comment]
Thanks Amigo!
