### ISSUE TITLE
GER Localization of AboutDialog fails on Unicode Characters.

### ISSUE THREAD

**Issue by Terranic** [flutter/flutter#109495]
## Steps to Reproduce

1. Set localization to German.
2. Call showAboutDialog with any content

**Expected results:** 
It should show:
LIZENZEN ANZEIGEN          SCHLIE**ß**EN

**Actual results:** 

![image](https://user-images.githubusercontent.com/59094334/184477380-9c534688-5cf5-4b6a-94ff-fbf03b6d3574.png)

**Comment by danagbemava-nc** [comment]
Hi @Terranic,

Can you please provide your `flutter doctor -v` and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?

Thank you

**Comment by Terranic** [comment]
Part 1;
PS C:\Users\Constantin\StudioProjects\sdg4_github> flutter doctor -v
[√] Flutter (Channel stable, 3.0.5, on Microsoft Windows [Version 10.0.22000.856], locale de-DE)
    • Flutter version 3.0.5 at C:\dev\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (5 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc1)
    • Android SDK at C:\Users\Constantin\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.0-rc1
    • Java binary at: C:\Program Files\Android\Android Studio1\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.0.0)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.0.31903.59
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 12 (API 31) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.22000.856]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 104.0.5112.81
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 104.0.1293.54

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Comment by Terranic** [comment]
Well, this is an example code - interestingly, it works as expectet...
Trying to find out what is the difference. It does not seem to be a font issue.... looking into it

```
import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:google_fonts/google_fonts.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  MyApp({super.key});

  final ThemeData lightmode =
      ThemeData(textTheme: GoogleFonts.aBeeZeeTextTheme());

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      supportedLocales: const [
        Locale('de'),
        Locale('en'),
      ],
      localizationsDelegates: const [
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
      ],
      locale: const Locale('de'),
      theme: lightmode,
      darkTheme: lightmode,
      title: "Hello",
      home: Builder(builder: (context) {
        return ElevatedButton(
            onPressed: () =>
                showAboutDialog(context: context, children: [Text("Hello")]),
            child: Text("Click"));
      }),
    );
  }
}
```
![image](https://user-images.githubusercontent.com/59094334/184726369-9d5a8fa1-9efe-4b9e-b8b6-15b1dece0b9b.png)

**Comment by danagbemava-nc** [comment]
Kindly provide the reproducible sample when you're able to. 

Thank you
