### ISSUE TITLE
Horizontal ListView shrinkwrapped with bouncing scroll physics only bounces on end and not start.

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#10949]
```dart
new ListView(
        scrollDirection: Axis.horizontal,
        physics: const BouncingScrollPhysics(),
        shrinkWrap: true,
        children: children,
      );
```

**Comment by tvolkert** [comment]
@apwilson still an issue?  Close if not needed anymore.

**Comment by knopp** [comment]
As far as I can tell this is still an issue. in `RenderShrinkWrappingViewport._attemptLayout` the `layoutOffset` is always `0.0`. Setting it to `-correctedOffset` enables bounce on both sides, but is probably not the correct solution.

**Comment by knopp** [comment]
Okay, that's definitely not a proper fix (it causes layout issues). Is there any chance this is going to get looked at in foreseeable future? Our app relies on shrinkwrapped scrollviews and this inconsistent behavior is an issue.

**Comment by knopp** [comment]
Actually, settings `layoutOffset` to `math.max(0.0, -correctedOffset)` seems to do the trick.

**Comment by joshkahane** [comment]
Can confirm I'm experiencing the same issue, only bounces at the end of the list of a shrink wrapped, horizontal ListView. I would add, it also occurs for shrink wrapped vertical ListView, however it is the end (bottom) at which it won't bounce.

**Comment by quetool** [comment]
This is still an issue even with a scrollDirection: Axis.vertical

**Comment by csshuai** [comment]
Same issue.

**Comment by DFreds** [comment]
Still an issue

**Comment by nohli** [comment]
Same issue here

**Comment by bernaferrari** [comment]
This also affects TabBarView in iOS. It doesn't not scroll beyond because of this issue.

**Comment by romanlytvyn** [comment]
Still the issue in `1.18.0-dev.5.0` for vertical scroll as well.
Would be nice if this got addressed to create a pleasant UI experience.

**Comment by henrikskul** [comment]
Still an issue for me as well.

**Comment by Gladkowski** [comment]
Still an issue for vertical scroll

**Comment by SedlarDavid** [comment]
Still an issue for ListView.builder, direction Axis.horizontal, shrinkWrap: true, bounce physics works only from end, not from start. Flutter version 1.17.5

**Comment by eli-front** [comment]
I have this issue too. A workaround I've been using is to wrap your ListView with Flexible, SizedBox, or Expanded. Hope this helps.

**Comment by darshankawar** [comment]
Issue replicable on latest stable (1.20.3).

[10949.mp4.zip](https://github.com/flutter/flutter/files/5174006/10949.mp4.zip)

<details>
<summary>flutter doctor -v</summary>

```
Flutter 1.20.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 216dee60c0 (2 days ago) • 2020-09-01 12:24:47 -0700
Engine • revision d1bc06f032
Tools • Dart 2.9.2

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.20.3, on Mac OS X 10.15.2 19C57, locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions.
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[✓] Android Studio (version 3.6)
[✓] Connected device (1 available)
```

</details>

**Comment by vixez** [comment]
Still an issue, also on beta

<details><summary>flutter doctor -v</summary>
<p>

```
[✓] Flutter (Channel beta, 1.22.0-12.3.pre, on Mac OS X 10.15.6 19G2021, locale
    en-GB)
    • Flutter version 1.22.0-12.3.pre at
      /Users/glennruysschaert/development/flutter
    • Framework revision d408d302e2 (2 days ago), 2020-09-29 11:49:17 -0700
    • Engine revision 5babba6c4d
    • Dart version 2.10.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/glennruysschaert/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • ANDROID_HOME = /Users/glennruysschaert/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.0

[✓] Connected device (3 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11
      (API 30) (emulator)
    • Web Server (web)            • web-server    • web-javascript • Flutter
      Tools
    • Chrome (web)                • chrome        • web-javascript • Google
      Chrome 85.0.4183.121

• No issues found!
```


</p>
</details>

**Comment by hashem78** [comment]
Issue still persists in Flutter 1.22.1

**Comment by YeungKC** [comment]
@knopp I can pass all the tests perfectly according to your program, do you have a PR plan?

**Comment by YeungKC** [comment]
https://discord.com/channels/608014603317936148/608018585025118217/779868516164567080
https://discord.com/channels/608014603317936148/608018585025118217/779869568611909652

https://github.com/flutter/flutter/issues/10949#issuecomment-440445025 
It is possible to fix this issue, but there may be potential implications according to the discord discussion.

More information is provided here to help anyone interested in this later.

cc @knopp

**Comment by BradenBagby** [comment]
Still an issue Flutter 2

**Comment by sooxt98** [comment]
Oh my, its three year old issue; Flutter please do something

**Comment by renatomotorline** [comment]
Solved it by change to:
```
Container(
  child: SingleChildScrollView(
    scrollDirection: Axis.horizontal,
    physics: BouncingScrollPhysics(parent: AlwaysScrollableScrollPhysics()),
    child: Row(
      children: children
    )
  )
)
```

**Comment by azharul-islam** [comment]
still an issue
