### ISSUE TITLE
[go_route] Include extra in Browser state if possible

### ISSUE THREAD

**Issue by chunhtai** [flutter/flutter#109404]
This https://github.com/flutter/packages/blob/main/packages/go_router/example/lib/others/extra_param.dart
does not work when pressing browser backward and forward button because the extra parameter is not stored into browser session.

We should try to store the extra parameter if possible (if it is json encodable).

**Comment by AceChen1** [comment]
@chunhtai  Hi, looks like i also found this issue on your example, may i know when will fixed this part ? or may i know this part is on the schedule to fix?

**Comment by chunhtai** [comment]
I put this aside for two main reasons.
1. the serializing and deserializing will change the data type which may confuse things. it will be hard to debug unless developer starts playing with browser backward and forward button.
2. go_router_builder uses extra to pass along complex data type, so this will benefit go_router_builder

I have not come up with a solution that can solve these two problem yet

**Comment by chunhtai** [comment]
close as done
