### ISSUE TITLE
Enable autosubmit bot on flutter/tests

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#109406]
I had https://github.com/flutter/tests/pull/142 but the bot never submitted. I assume this is because we haven't installed it on that org.

**Comment by yusuf-goog** [comment]
@keyonghan can you confirm, or is this a bug?

**Comment by keyonghan** [comment]
This needs @godofredoc to install the app in the repo.

**Comment by godofredoc** [comment]
Autosubmit app was installed in flutter/tests.
