### ISSUE TITLE
Travis hangs while downloading from dl.google.com

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#10940]
Travis builds are [broken](https://travis-ci.org/flutter/flutter/builds/246067983) due to the setup step failing [when we try to download the Google Cloud SDK](https://github.com/flutter/flutter/blob/be99a04dacc2ac77b445aff54df225c4cf951076/dev/bots/travis_setup.sh#L10).

**Comment by Hixie** [comment]
We must not roll alpha until this is resolved, one way or the other, since this is blocking docs upload.

**Comment by tvolkert** [comment]
Current status: we have a note out to the dl.google.com SRE team to see if they can identify why the downloads were hanging.

**Comment by tvolkert** [comment]
Was reverted in https://github.com/flutter/flutter/pull/10999

**Comment by tvolkert** [comment]
Current status: this is fixed.  I'm currently testing a patch to see if it was fixed either because...
* We used `filter_secrets: false` in our `.travis.yml` file as suggested by Travis support.  The theory is that their newly introduced privacy filtering algorithm was getting in the way of our cloud SDK download.
* It was a transient failure (that lasted more than a week) that has since gone away.

**Comment by tvolkert** [comment]
Sure enough, if I remove `filter_secrets: false`, the build [fails](https://travis-ci.org/flutter/flutter/builds/251344281) as expected.  So the theory that the failure is caused by Travis' newly introduced privacy filtering algorithm is correct.

I'm closing this as fixed and following up with the Travis support team on the cause and if they need to make any fixes on their end.

**Comment by batter** [comment]
Did you ever find out if you were able to drop `filter_secrets`? I don't see it documented anywhere on Travis's support docs...
