### ISSUE TITLE
[Web]Error: Member not found: 'FlutterError.wformParts'

### ISSUE THREAD

**Issue by yaw0rld** [flutter/flutter#109420]
Launching lib/main.dart on Chrome in debug mode...
/opt/src/flutter/packages/flutter/lib/src/rendering/box.dart:2446:28: Error: Member not found: 'FlutterError.wfromParts'.
      throw FlutterError.wfromParts(<DiagnosticsNode>[ ^^^^^^^^

I normally debug my Flutter web app as usual, and I got a rendering error because of the two TextFields inside a Row Widget. I wrapped each TextField in an Expanded Widget, therefore, this error appears after Accidentally, my PC goes of when debugging and I no longer can run a web app, even when created a new project. 

Flutter Linux 

Please, Don't tell me to reinstall Flutter, because I already did, but I wanna know if there's a solution. Thanks

**Comment by maheshmnj** [comment]
Hi @yaw0rld, Please share the output of `flutter doctor -v`. Additionally please  also share the output of 
```
flutter create hello
cd hello 
flutter run -d chrome
```

**Comment by yaw0rld** [comment]
Here we go Mr, @maheshmnj 
the issue is when running the application
❯ flutter doctor -v
[✓] Flutter (Channel stable, 3.0.5, on Kali GNU/Linux Rolling 5.10.46, locale C.UTF-8)
    • Flutter version 3.0.5 at /opt/src/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (4 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /usr/bin/chromium

[✓] Linux toolchain - develop for Linux desktop
    • Debian clang version 13.0.1-4
    • cmake version 3.23.1
    • ninja version 1.11.0
    • pkg-config version 0.29.2

[✓] VS Code (version 1.67.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.46.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-arm64    • Kali GNU/Linux Rolling 5.10.46
    • Chrome (web)    • chrome • web-javascript • Chromium 101.0.4951.64 built on Debian bookworm/sid, running on Debian
      kali-rolling

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

----------------

❯ flutter create hello
Creating project hello...
Running "flutter pub get" in hello...                               8.8s
Wrote 127 files.

All done!
In order to run your application, type:

  $ cd hello
  $ flutter run

Your application code is in hello/lib/main.dart.

 ~─────

❯ cd hello
❯ flutter run -d chrome

Launching lib/main.dart on Chrome in debug mode...
/opt/src/flutter/packages/flutter/lib/src/rendering/box.dart:2446:28: Error:
Member not found: 'FlutterError.wfromParts'.
        throw FlutterError.wfromParts(<DiagnosticsNode>[
                           ^^^^^^^^^^
Waiting for connection from debug service on Chrome...            _169.3s_
Failed to compile application.
❯ 


I also run the application using html renderer 
❯ flutter run -d chrome --web-renderer html 
 with same output.

**Comment by maheshmnj** [comment]
Thanks for the info @yaw0rld, Perhaps thats an issue on Kali Linux environment, I am able to run it fine though on Ubuntu. Can you please try switching to the latest master channel by running 
```
flutter channel master
flutter upgrade
```
Just to ensure if this is still a bug?

<details>
<summary>flutter doctor -v (Linux)</summary>

```
[✓] Flutter (Channel stable, 3.0.5, on Ubuntu 20.04.4 LTS 5.13.0-48-generic, locale en_GB.UTF-8)
    • Flutter version 3.0.5 at /home/mahesh/Development/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (5 days ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /home/mahesh/Android/Sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at:
      /home/mahesh/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/212.5712.43.2112.8609683/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 2021.2)
    • Android Studio at /home/mahesh/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/212.5712.43.2112.8609683
    • Flutter plugin version 67.1.2
    • Dart plugin version 212.5744
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.1)
    • IntelliJ at /home/mahesh/.local/share/JetBrains/Toolbox/apps/IDEA-U/ch-0/221.5921.22
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.68.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.44.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 20.04.4 LTS 5.13.0-48-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 102.0.5005.115

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>
