### ISSUE TITLE
Migrate flutter/tests from master->main

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#109417]
I can't find any references to master on flutter/tests, but generally all of the repos in the Flutter organization should be using main.

**Comment by CaseyHillers** [comment]
\cc @Hixie

**Comment by CaseyHillers** [comment]
I found one reference in https://flutter.googlesource.com/recipes/+/refs/heads/main/recipe_modules/adhoc_validation/resources/customer_testing.sh

**Comment by Hixie** [comment]
SGTM. We may also need to update some of the scripts in `dev/bots/customer_testing` in flutter/flutter.

**Comment by yusuf-goog** [comment]
@CaseyHillers not sure this is a ticket queue issue?

**Comment by CaseyHillers** [comment]
Can the oncall generate the token for mirroring master and main, and set up the github action?

**Comment by godofredoc** [comment]
Is this a nice to have or it is blocking something? it will help to prioritize

**Comment by godofredoc** [comment]
Repo has been migrated.
