### ISSUE TITLE
[iOS] The keyboard animation is not so smooth and has some junk and laggy on 120HZ promotion devices

### ISSUE THREAD

**Issue by luckysmg** [flutter/flutter#109435]
It is tested on iPhone 13 Pro(120HZ) and iPhone12(60HZ), release mode:
When the keyboard showup, the textfield will pushup normally but not so smooth when device is under 120HZ refresh rate.

**Also tested iPhone13Pro on low power mode(60HZ),or on iPhone12(60HZ), the animation is not that bad.**

Here is the code example

<details>

<summary>Code</summary>

```dart

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const TextFieldPage(),
    );
  }
}

class TextFieldPage extends StatefulWidget {
  const TextFieldPage({Key? key}) : super(key: key);

  @override
  State<TextFieldPage> createState() => _TextFieldPageState();
}

class _TextFieldPageState extends State<TextFieldPage> {

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Column(
        mainAxisAlignment: MainAxisAlignment.end,
        children: [
          const Spacer(),
          const Text('Keyboard animation', style: TextStyle(fontSize: 26)),
          const Spacer(),
          SizedBox(
              height: 60 + MediaQuery.of(context).padding.bottom,
              child: const CupertinoTextField(
                decoration: BoxDecoration(color: Colors.red),
              )),
        ],
      ),
    );
  }
}


```

</details>

<details>

<summary>Flutter doctor</summary>

```
[✓] Flutter (Channel master, 3.1.0-0.0.pre.2241, on macOS 12.5 21G72 darwin-arm
    (Rosetta), locale zh-Hans-CN)
[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.70.1)
Scanning for devices is taking a long time...[✓] Connected device (2 available)
[✓] HTTP Host Availability

```

</details>

**Comment by maticla** [comment]
Do you have the `CADisableMinimumFrameDurationOnPhone` property set to `1` in `Info.plist`? 

This enables the faster ProMotion refresh rates.

**Comment by luckysmg** [comment]
Yes, I set

**Comment by darshankawar** [comment]
@luckysmg 
Is this different from https://github.com/flutter/engine/pull/34871 ?

**Comment by luckysmg** [comment]
This is the issue I will linked to that PR

**Comment by luckysmg** [comment]
Could you reproduce it?

**Comment by luckysmg** [comment]
I can reproduce it but I don't sure others can or not

**Comment by darshankawar** [comment]
> Could you reproduce it?

Tried using latest master on iPhone 6s (OS 15.3.1), but didn't observe the same behavior, although, the first time it opens the keyboard, it probably shows a jank, not after subsequent attempts. Do you see the same behavior ? 


https://user-images.githubusercontent.com/67046386/184360047-33c48664-4eb9-489b-b83a-f750f91454df.MP4

**Comment by luckysmg** [comment]
@darshankawar  Yes.But this issue will come out in 120HZ devices like iPhone13Pro, Could you reproduce it😄

**Comment by darshankawar** [comment]
I don't have that device to verify on, so it would be good if you could share what you see on that device, so we can compare.

**Comment by luckysmg** [comment]
Ok,I will upload a video later

**Comment by luckysmg** [comment]
https://user-images.githubusercontent.com/49340347/184362113-d3579137-f379-4ed5-9cc3-6fdcc5293f5e.MP4

When I start record video, the junk will reduce....... But it still have some..

**Comment by luckysmg** [comment]
The last two time toggle,You can see that junk? When I doesn't record video, every time is like that.

**Comment by luckysmg** [comment]
Hi @sundayla I see the your comment in https://github.com/flutter/flutter/issues/101653#issuecomment-1169809142
Could you reproduce it with the code example in this issue?

**Comment by b3nni97** [comment]
@luckysmg I have the same problem, however it is noticeable even with a 60hz device. 
The problem is that these microlags are not shown in the performance overlay / profiler. You can also test if you are above 8ms or 16ms while the lags are noticeable. (For me it is always under 8 / 16ms).

The problem is not only when opening the keyboard, in my app almost every animation is affected, sometimes the animations run 100% smooth and then there are some microlags again.

**Comment by sundayla** [comment]
In conclusion, yes this issue still exist and able to reproduce.

**Comment by luckysmg** [comment]
> @luckysmg I have the same problem, however it is noticeable even with a 60hz device. The problem is that these microlags are not shown in the performance overlay / profiler. You can also test if you are above 8ms or 16ms while the lags are noticeable. (For me it is always under 8 / 16ms).
> 
> The problem is not only when opening the keyboard, in my app almost every animation is affected, sometimes the animations run 100% smooth and then there are some microlags again.

This maybe related with shader.......When you first run some animation, it is normal to have some laggy...
But..I mean the keyboard animation on Promotion devices, the laggy is more obvious and transparent to see...

**Comment by luckysmg** [comment]
@sundayla 
When you start record video, did the junk reduce a little?

**Comment by luckysmg** [comment]
Every time I want to record the junk to show, the junk will reduce and become not that transparent.....

**Comment by luckysmg** [comment]
@sundayla  Agree with you. 
You can see My PR https://github.com/flutter/engine/pull/34871
This is to make the keyboard animation's refresh rate to adjust with the refresh rate using for rendering. Hoping it can be landed....

**Comment by luckysmg** [comment]
And You can check out my engine branch to test whether the animation is smoother a lot than before.......
I think the comparsion is very transparent.

**Comment by b3nni97** [comment]
> This maybe related with shader.......When you first run some animation, it is normal to have some laggy... But..I mean the keyboard animation on Promotion devices, the laggy is more obvious than others and more transparent to be discovered...

No I don't mean the shader compilation jank, the lags also occur when the animation has been displayed 10 times before. Sure the 1st time there is usually a larger lag, the subsequent times it is always only micro stutter.

The last version which did not have these problems was 3.0.1, at least this was the case for me.

**Comment by darshankawar** [comment]
Thanks for the update. Based on the report and verification, keeping this issue open and labeling.
