### ISSUE TITLE
flutter run --route doesn't work on iOS

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#10947]
We should implement `--route` on iOS.

- [ ] `flutter run --route` isn't implemented for iOS devices in flutter tool.
- [ ] `flutter run --route` isn't implemented for iOS simulators in flutter tool.
- [ ] There's no equivalent of receiving a route intent from the OS in the iOS engine.
- [ ] The devicelab test at `dev/devicelab/bin/tasks/routing_test.dart` isn't run for iOS.

**Comment by Hixie** [comment]
cc @cbracken

**Comment by gspencergoog** [comment]
The relevant code location is [here](https://github.com/flutter/flutter/blob/70772ea5a00a9518bea3e611c5008181df3423fe/packages/flutter_tools/lib/src/ios/devices.dart#L163).

**Comment by xster** [comment]
Merging into #4703
