### ISSUE TITLE
Add invoke on-screen keyboard on desktop

### ISSUE THREAD

**Issue by omatt** [flutter/flutter#109546]
## Use case

There are use cases where Flutter apps are used in Kiosks running desktop platforms that needs a virtual keyboard for input. Currently, the on-screen keyboard needs to be [enabled in desktops](https://support.microsoft.com/en-us/windows/use-the-on-screen-keyboard-osk-to-type-ecbb5e08-5b4e-d8c8-f794-81dbf896267a) to appear. Another workaround on Windows platform is to switch the device into [tablet mode](https://support.microsoft.com/en-us/windows/turn-tablet-mode-on-or-off-add3fbce-5cb5-bf76-0f9c-8d7b30041f30) to automatically display the softkeyboard when a TextField is active. 

The current behavior is understandable since most desktop machines use a physical keyboard.

## Proposal

Add a function similar to `System.Diagnostics.Process.Start("osk.exe");` - where the on-screen keyboard can be invoked in Windows using C#. It'll be helpful if this can be also applied in macOS and Linux as well.

**Comment by maheshmnj** [comment]
HI @omatt, Thanks for filing the issue. That sounds like a valid proposal.

cc: @justinmc

**Comment by gspencergoog** [comment]
If you need to do this, you should be able to do it via the Dart FFI interface (if you want to make a call to a Windows API), or via Dart's Process API to launch `osk.exe` as you describe.

At this time, we're not planning on adding a separate API for this purpose.  (Desktop Triage).
