### ISSUE TITLE
Error (Xcode): Undefined symbol: _OBJC_CLASS_$_GeneratedPluginRegistrant

### ISSUE THREAD

**Issue by kavyabhargava** [flutter/flutter#109571]
I am getting this error when running my app for IOS. Previously it was working fine but then I had to change my appID "com.xx.xx" to something else "com.yy.yy". I changed it everywhere. I started getting this error after that. I tried these answers: 

1. Stackoverflow:
https://stackoverflow.com/questions/63861443/undefined-symbols-for-architecture-x86-64-objc-class-generatedpluginregistr

2.Github:
https://github.com/flutter/flutter/issues/51992

But these solutions did not work

Commands I tried:
```
flutter upgrade
rm -f ios/Runner.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings
rm -rf ios/Podfile ios/Podfile.lock ios/Pods ios/Runner.xcworkspace
```

`pod update`

But the error still persists

Is there any other solution 

I am using a M1Pro Mac

**Comment by maheshmnj** [comment]
Hi @kavyabhargava, Thanks for filing the issue. Please share the output of `flutter doctor -v` along with the complete output of `flutter run -v`  in a text file (as the output will be long).

**Comment by kavyabhargava** [comment]
Flutter doctor -v output:
```
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.5 21G72 darwin-arm, locale en-IN)
    • Flutter version 3.0.5 at /Users/kavyabhargava/FlutterDev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (5 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/kavyabhargava/Library/Android/sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] VS Code (version 1.67.0)
    • VS Code at /Users/kavyabhargava/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.46.0


[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.5 21G72 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 104.0.5112.79

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

Flutter run - v output
[error.docx](https://github.com/flutter/flutter/files/9351204/error.docx)

I am unable to see whole thing in the vs code for some reason

**Comment by maheshmnj** [comment]
Thanks for the info Can you please run the below command from the root of your project and attach the output?

```bash
cat ios/Runner.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings
```

**Comment by kavyabhargava** [comment]
Output: `cat: ios/Runner.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings: No such file or directory`

**Comment by maheshmnj** [comment]
Oh, I see thats because you deleted those files

> Commands I tried:

> flutter upgrade
rm -f ios/Runner.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings
rm -rf ios/Podfile ios/Podfile.lock ios/Pods ios/Runner.xcworkspace

We should not manually delete those files, I think `flutter clean` will do the required clean-up for you (It mainly removes files that can be regenerated either during `flutter pub get` or during the build phase).

 One quick way to get around this issue is to delete the ios folder and recreate it using `flutter create . --platforms ios`,

 **But note that doing so, you will lose any of the configurations that you might have done in the IOS folder.**

Is it possible for you to share a minimal sample project by redacting any of the sensitive information from your code?

**Comment by kavyabhargava** [comment]
What part of code you want?? Should I delete the iOS folder as I think have only added firebase which I can add again, will anything else get deleted?

**Comment by kavyabhargava** [comment]
I ran `cat ios/Runner.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings ` after running `flutter clean` and `flutter pub get` but still receiving `cat: ios/Runner.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings: No such file or directory`

**Comment by maheshmnj** [comment]
> What part of code you want?? Should I delete the iOS folder as I think have only added firebase which I can add again, will anything else get deleted?

We would need a complete sample project the issue seems mainly in the ios folder, I would suggest making a copy of the project and redact your code sample (under the lib folder) to include minimal code and you could zip and share the project here.

> I ran cat ios/Runner.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings after running flutter clean and flutter pub get but still receiving cat: ios/Runner.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings: No such file or directory

Yes, probably that's because those files won't be re-generated once they are deleted.

**Comment by kavyabhargava** [comment]
Hey how could I redact the folder I am unsure? Also I tried, doing the easier option that somewhat worked. I deleted the iOS folder and run the command flutter create . --platforms iOS and I added back the google service info plist

**Comment by maheshmnj** [comment]
> Hey how could I redact the folder I am unsure?

- make a copy of your original project 
- delete everything in lib except main.dart (you could replace that with a counter app) 
- remove folders from other platform (e.g Android/web etc) (To reduce the size of your project)
- zip and share it, in the comments



>  but my firebase is not displaying anything

Ensure that you are adding `info.plist` via xcode, Probably you should use [flutterfire cli](https://firebase.flutter.dev/docs/cli/), which will handle everything for you.
