### ISSUE TITLE
flutter/engine/contributing.md doesn't explain how to run the license script

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#10950]
I went looking for instructions on how to run the license script. I didn't find them in
https://github.com/flutter/engine/blob/master/CONTRIBUTING.md
and we surprised?

**Comment by Hixie** [comment]
The docs are in tools/licenses/README, and iirc Travis points to them when you need them.

**Comment by Hixie** [comment]
Closing per last comment.
