### ISSUE TITLE
[flutter_markdown] MarkdownBody p tag padding is affecting img tag padding 

### ISSUE THREAD

**Issue by Helocominc** [flutter/flutter#109514]
When adding padding to the p tag it also add to the img tag padding. The img tag uses p tag padding. Added a different padding to the img tag by extending the MarkdownPaddingBuilder but it still using the p tag padding. 
The img tag padding doesn't affect the p tag padding but the p tag padding affect the img tag padding.

**Comment by exaby73** [comment]
Hi @Helocominc  please provide a [minimal, reproducible example][1] and the output of `flutter doctor -v`.

[1]: https://stackoverflow.com/help/minimal-reproducible-example
