### ISSUE TITLE
[tool_crash] StateError: Bad state: No context with the running Dart application.

### ISSUE THREAD

**Issue by josephjackson0811** [flutter/flutter#109525]
## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=chrome --start-paused --dart-define=flutter.inspector.structuredErrors=true lib\main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
StateError: Bad state: No context with the running Dart application.
```
#0      RemoteDebuggerExecutionContext.id (package:dwds/src/debugging/execution_context.dart:55:7)
<asynchronous suspension>
#1      AppInspector._getExtensionRpcs (package:dwds/src/debugging/inspector.dart:538:20)
<asynchronous suspension>
#2      AppInspector._initialize (package:dwds/src/debugging/inspector.dart:97:34)
<asynchronous suspension>
#3      AppInspector.initialize (package:dwds/src/debugging/inspector.dart:160:5)
<asynchronous suspension>
#4      ChromeProxyService.createIsolate (package:dwds/src/services/chrome_proxy_service.dart:216:18)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 3.0.5, on Microsoft Windows [Version 10.0.18363.719], locale en-US)
    • Flutter version 3.0.5 at E:\Mobile\flutter_windows_3.0.5-stable\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (5 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\admin\AppData\Local\Android\sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✗] Visual Studio - develop for Windows
    ✗ Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[✓] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[✓] VS Code (version 1.70.1)
    • VS Code at C:\Users\admin\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 104.0.5112.81

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: beta
**Creation framework version**: 8f89f6505b941329a864fef1527243a72800bf4d
### Plugins
audio_session-0.1.6+1
better_player-0.0.82
connectivity_plus-2.3.0
connectivity_plus_linux-1.3.0
connectivity_plus_macos-1.2.2
connectivity_plus_web-1.2.0
connectivity_plus_windows-1.2.0
contacts_service-0.6.3
firebase_analytics-9.1.8
firebase_analytics_web-0.4.0+13
firebase_core-1.17.0
firebase_core_web-1.6.4
firebase_crashlytics-2.8.0
firebase_messaging-11.4.0
firebase_messaging_web-2.4.0
flutter_branch_sdk-5.0.0
flutter_keyboard_visibility-5.2.0
flutter_keyboard_visibility_web-2.0.0
flutter_local_notifications-9.5.3+1
flutter_plugin_android_lifecycle-2.0.6
geolocator-8.2.1
geolocator_android-3.1.8
geolocator_apple-2.1.3
geolocator_web-2.1.5
geolocator_windows-0.1.1
google_sign_in-5.3.1
google_sign_in_android-5.2.8
google_sign_in_ios-5.3.1
google_sign_in_web-0.10.1+2
image_picker-0.8.5+3
image_picker_android-0.8.4+13
image_picker_for_web-2.1.8
image_picker_ios-0.8.5+5
just_audio-0.9.21
just_audio_web-0.4.7
map_launcher-2.2.2
multi_image_picker-4.8.01
package_info-2.0.2
path_provider-2.0.10
path_provider_android-2.0.14
path_provider_ios-2.0.9
path_provider_linux-2.1.6
path_provider_macos-2.0.6
path_provider_windows-2.0.6
permission_handler-9.2.0
permission_handler_android-9.0.2+1
permission_handler_apple-9.0.4
permission_handler_windows-0.1.0
share-2.0.4
shared_preferences-2.0.15
shared_preferences_android-2.0.12
shared_preferences_ios-2.1.1
shared_preferences_linux-2.1.1
shared_preferences_macos-2.0.4
shared_preferences_web-2.0.4
shared_preferences_windows-2.1.1
sign_in_with_apple-3.3.0
sign_in_with_apple_web-1.0.1
social_share-2.2.1
sqflite-2.0.2+1
stripe_android-2.5.0
stripe_ios-2.5.0
toast-0.3.0
url_launcher-6.1.2
url_launcher_android-6.0.17
url_launcher_ios-6.0.17
url_launcher_linux-3.0.1
url_launcher_macos-3.0.1
url_launcher_web-2.0.11
url_launcher_windows-3.0.1
video_player-2.4.2
video_player_android-2.3.4
video_player_avfoundation-2.3.4
video_player_web-2.0.10
wakelock-0.6.1+2
wakelock_macos-0.4.0
wakelock_web-0.4.0
webview_flutter-3.0.4
webview_flutter_android-2.8.8
webview_flutter_wkwebview-2.7.5

**Comment by exaby73** [comment]
Hi @josephjackson0811, please provide a [minimal, reproducible example][1] as well as `flutter run -v`.

[1]: https://stackoverflow.com/help/minimal-reproducible-example
