### ISSUE TITLE
On Modroid: Scrolling a ScrollableViewPort often fails to fling when lifting a finger at speed.

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#1095]
Possibly related to an issue where on Linux if you click a button that triggers animations those animations don't trigger (nor does the pointer event I think) until the pointer is moved post-click.

**Comment by apwilson** [comment]
This seems to be related to the switch over to MojoShell.  I didn't see it as often in SkyShell.

**Comment by abarth** [comment]
Modroid isn't a thing anymore.
