### ISSUE TITLE
TextButton docs examples broken

### ISSUE THREAD

**Issue by justinmc** [flutter/flutter#109567]
The two code examples on the [TextButton master docs](https://master-api.flutter.dev/flutter/material/TextButton-class.html) have errors and don't run.  The [stable docs](https://api.flutter.dev/flutter/material/TextButton-class.html) don't have this problem.

CC @HansMuller

**Comment by HansMuller** [comment]
Odd: the master channel includes the property that's being complained about:
https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/text_button.dart#L147

**Comment by justinmc** [comment]
Oh you're right.  Maybe this is a problem with the docs site deployment that will fix itself?  It says those changes are 2 months old already though.

**Comment by HansMuller** [comment]
Checked with @gspencergoog about this. There's not much we can do; DartPad doesn't run against the master branch; we'll have to wait for the next beta or stable release.

**Comment by HansMuller** [comment]
Closing per triage team discussion.
