### ISSUE TITLE
Height for TextField and similar fields

### ISSUE THREAD

**Issue by glaceon2000** [flutter/flutter#109588]
## Use case

I cannot set height for text or drop down fields without wrapping it in a SizedBox or Container with a height set. This works fine unless when there is error text and whatnot involved. For example:
![image](https://user-images.githubusercontent.com/51567674/184799630-da6a2d49-cf43-447b-93aa-de2f34a64efa.png)

Manipulating the height through content padding isn't always successful and it's just counter-intuitive.

## Proposal

Add a height property for text fields

**Comment by exaby73** [comment]
Hello @glaceon2000. The height of a `TextField` is determined by the font size plus the `contentPadding`. You can use those 2 to control the height of the `TextField`. Using global theming, you can set a consistent height for all `TextField`s. Let me know if this is a viable solution for you. 

The issue with constant heights is that it may not support icons. When specifying a `prefixIcon` for example, the `TextField`'s height is increased to accommodate the icon. Here, `contentPadding` comes into play. With a fixed height, you may run into overflow issues if you add an icon

**Comment by glaceon2000** [comment]
So when you add an icon, how do you configure the size of the icon?
Also when you have all 3 isCollapsed, isDense and contentPadding set, which one will take priority?

**Comment by exaby73** [comment]
The docs explain it well [here](https://api.flutter.dev/flutter/material/InputDecorationTheme/contentPadding.html).

> By default the contentPadding reflects [isDense](https://api.flutter.dev/flutter/material/InputDecorationTheme/isDense.html) and the type of the [border](https://api.flutter.dev/flutter/material/InputDecorationTheme/border.html). If [isCollapsed](https://api.flutter.dev/flutter/material/InputDecorationTheme/isCollapsed.html) is true then contentPadding is [EdgeInsets.zero](https://api.flutter.dev/flutter/painting/EdgeInsets/zero-constant.html).

Since this is how it's expected, I'm closing this issue. If you disagree, please comment and we can reopen it
