### ISSUE TITLE
Docs: Inconsistency in Action Chip Docs

### ISSUE THREAD

**Issue by chinmoy12c** [flutter/flutter#109515]
The action chip docs state that:

``` They cannot be disabled; if the action is not applicable, the chip should not be included in the interface. ```
https://github.com/flutter/flutter/blob/4dd7065244d59e068e2bcb6d6191e45963067b28/packages/flutter/lib/src/material/action_chip.dart#L20

Although, in a recent [PR](https://github.com/flutter/flutter/pull/107166), the `onPressed` was made an optional parameter which enabled the chip to have a disabled state. I think an update in the docs is required to reflect the same.

**Comment by HansMuller** [comment]
Right, we should now say that it's preferable to not include disabled ActionChips, instead of just disabling them.
