### ISSUE TITLE
Why not consider another language outside of dart for Flutter like as NodeJS or Java?

### ISSUE THREAD

**Issue by yhojann-cl** [flutter/flutter#109522]
Why not consider another language outside of dart?, for example, like the development of software for android that allows java and kotlin, why don't they allow more languages for Flutter?, for example, one that is more intuitive, that does not require such a high learning curve and that is not so ugly like Dart, for example Java or NodeJs. I don't think that node or java is executed on the host system, but that it serves as a translator of instructions at the time of being compiled just like dart.

Currently there are many people who already know how to develop in nodejs or java, there are already repositories with very modern and old libraries that cover almost all kinds of needs, why reinvent everything by creating a new programming language causing problems for new application developers?

Something similar happens with Kotlin and Go, despite being good languages, they are not convincing or earn a place in the most used programming languages due to their unintuitive and complex learning when you already come from the world of structured development from java or javascript. Why every time Google creates a new technology ends up creating a new language complicating all things? Why doesn't it work on improving what already exists and what people already know instead of making a student who finished learning a language have to spend more years of your life just trying to understand more languages?

Definitely dart is a good language just like go or kotlin, but not giving the option to use a language that is already widely known is cruel for many people.

I open this ticket to propose the option of considering integrating Javascript language (nodejs), Java and/or rust. If you want to create new languages, do it, but give more alternatives please.

Flutter was a very good idea to replace Electron, now that microsoft is planning to kill the project after killing atom editor and integrate microsoft edge in their hybrid apps, but the dart language sucks and there are no better cross-platform alternatives to build native apps for windows, mac and linux since react native does not natively support the creation of applications for linux, although in design I am more convinced by flutter, but the language is a great wall to migrate projects.

**Comment by iapicca** [comment]
duplicate 
https://github.com/flutter/flutter/issues/15128
https://github.com/flutter/flutter/issues/15922
https://github.com/flutter/flutter/issues/14382

**Comment by maheshmnj** [comment]
Hi @yhojann-cl, Considering some of the responses from the flutter team, I believe you should have answers to your question.

https://github.com/flutter/flutter/issues/15128#issuecomment-370222976
https://github.com/flutter/flutter/issues/14382#issuecomment-370938183

Closing as duplicate, in favor of the linked issues

**Comment by yhojann-cl** [comment]
Thanks for the answers, anyway I want to argue why there should be more alternatives to Dart.


## Async and await legacy issues

A typical problem is that currently you cannot use await inside a function that is not asynchronous, this problem was fixed in the new version of the ecmascript standard, but dart inherited bad practices with design errors included:

> Error: 'await' can only be used in 'async' or 'async*' methods.


## Private methods are a patch

It is an object-oriented language but it was not designed to maintain a context between private and public data. For example, like some legacy Javascript problems it is necessary to use special characters to represent properties of class attributes instead of creating native annotations, for example, need use underscore for declare private fields instead of use a single `private` declaration, but for statics attributes use a `static` declaration instead of a another special char, like as `#_@.attribute`,  it's ridiculous and a poor solution inheriting from other standards instead of creating your own declarations like any other programming language does, like java.


## Using loose package import

Dart uses a manual package import system without any strict structure, which is why it falls into the same problems as old programming languages like ph where each developer created structures as they pleased, this was a problem that php knew how to solve from php7 copying part of php and other stricter languages like python, but dart has stayed in the past allowing messy developments with spaghetti code.


## Unintuitive and unsafe class constructors

The creators of Dart have designed a new way to create constructors by saving all the code of a constructor and passing its data, also avoiding the use of getters/setters through get and set properties like c#, but this causes serious problems like those that are reflected when using lombok in Java.

Why did java implement in its recommendations the use of manual getters/setters and constructors for data transfer objects or models like DTO and DAO?, probably this answer is unknown to the maintainers of Dart, since what is sought is to maintain the integrity of the transfer data, being able to apply filtering of input data in setters and output in getters, it also gives the opportunity to create annotation controls additional validation checks, concatenation of multiple streams into setters and the like, but all of this is lost with lombok's automatic getter/setter creation library, something similar to what dart does but in a more aggressive way. It saves a lot of time creating code but at the same time you lose a lot of control over the integrity and security of the data and when creating these controls in dart you end up creating more code than in java and in a more messy way, which is why it is more There are more likely to be security bugs in a development built on dart than on java.


## Is Dart the best language for Flutter?

Dart is a language that copied not only the syntax of other languages joining java with javascript, but also copied their problems and did not know how to solve them, instead they applied temporary and obsolete patches which are already being abandoned by their own programming languages. Dart is an unintuitive language with horrible and insecure class construction syntax. Dart may have a lot of performance but it is far from being a programming language on a par with others that already exist. Does anyone know why Go or Kotlin were not used for Flutter, being languages also developed by Google? Being Go the language with good performance and multiplatform? If Google had really considered Go or Kotlin to be good languages, they wouldn't have had to waste time building a new one. Most likely, in a few more years they will manufacture another programming language, forgetting Dart as they are used to doing with their technologies and products.

It's a pity, Flutter is a good project with a good layout, everything that is sought in a modern era, being able to build multiplatform applications natively without duplicating code as was done in the past, when you had to program for internet explorer 6, for firefox , opera and others, you ended up with many projects for a single web page, but the standards came to change that and now google floods us again with more languages that do not contribute anything new, Flutter would be the definitive project if they had used a programming language more common and robust, making use of current standards instead of imposing long learning curves, and then abandoning users to their fate, there is not even official Dart documentation in Spanish or other languages.


## The technology doesn't exist yet

I understand that this thread, like others, has been closed and will probably be silenced, I understand that this topic will not reach beyond the eyes of a couple of people, Google is not what it used to be, when it created good projects that benefited people , nowadays they do not feel remorse to unsubscribe services like Google Play Music no matter how many people use it, they do not care if there are still people who use their languages ​​or technologies, in order to advance they are leaving many people behind and many of us are looking for an alternative that thinks of us as people and allows us to develop and create without the fear of running out of support in such a short time, it has already happened with Electron and Dart is not a good option, there are very few options that exist, despite of living in the year 2022 there is still no technology that allows us to program in a calm and confident way in a good multiplatform language for desktop and mobile systems in a robust way ta, safe and with a good design, today we are almost forced to develop on multiple platforms with multiple frameworks to create a single solution and Flutter was a good idea but poorly executed. Now we have to wait for some other project to appear that can give us that environment.

While Microsoft is desperately fighting to sink cross-platform projects so that Windows sales do not decline, while Oracle continues to buy open source projects to destroy them so that they do not stop selling their products, we are waiting for a company that thinks in us as people and in the diversity of systems in a universal way, unfortunately that era has not yet arrived, but it will come.

**Comment by maheshmnj** [comment]
@yhojann-cl Closing an issue doesn't mean that your request is being ignored, it's just not practical to do something that you are proposing at this time, since flutter works with limited resources. That also doesn't mean Dart is a perfect language. No framework or SDK or language is perfect, We can only strive to make it better and it is a result of a consistent effort of hundreds of contributors who are helping the flutter ecosystem make better.
If you think Dart or flutter lacks some feature or is not built in a way it should have been you are welcome to file an issue in a dedicated repo, Make a proposal prepare a design doc (if required) and also we welcome pull requests. But if your proposals are way too off (which requires a built-up from the ground) like using a different language. Then I think you should consider this comment https://github.com/flutter/flutter/issues/14382#issuecomment-370938183
