### ISSUE TITLE
Error while loading shared libraries: libjsoncpp.so

### ISSUE THREAD

**Issue by rekire** [flutter/flutter#109594]
When I start my flutter application on a fresh Ubuntu install (ubuntu-22.04.1-desktop-amd64) I get the error:
> error while loading shared libraries: libjsoncpp.so.1: cannot open shared object file: No such file or directory

## Steps to Reproduce

0. Create a Flutter-App
1. Build your app with `flutter build linux`
2. Install Ubuntu e.g. in a VM
3. Execute your Flutter App

**Expected results:**
I want to see my Flutter App as on Windows and MacOS

**Actual results:** 

<details>
<summary>The app crashes</summary>

> error while loading shared libraries: libjsoncpp.so.1: cannot open shared object file: No such file or directory

</details>

I tried to add the same dependecy as on the CI with:

```bash
$ sudo apt-get install libjsoncpp-dev
```

However that does not work. I would guess that I need to add another dependency, but I don't know which one. I found from @stuartmorgan an [old reference](https://github.com/google/flutter-desktop-embedding/issues/227#issuecomment-453554570), but that link does not work anymore.

**Comment by stuartmorgan** [comment]
> I found from @stuartmorgan an [old reference](https://github.com/google/flutter-desktop-embedding/issues/227#issuecomment-453554570), but that link does not work anymore.

That issue, and those instructions, were for a very, very early desktop support library that has almost nothing in common with the version that's actually part of the Flutter project.

The current Linux embedding doesn't use libjsoncpp, so most likely you are using a plugin that requires it. You'd need to contact the developers of that plugin to ask for distribution suggestions.

**Comment by rekire** [comment]
Thank you, I missed that this comes from a dependency, in my case [flutter_secure_storage](https://github.com/mogol/flutter_secure_storage).
