### ISSUE TITLE
Unable to Extract Widget Android studio ? 

### ISSUE THREAD

**Issue by Wahab-Khan** [flutter/flutter#109528]
Build: AI-212.5712.43.2112.8609683, 202205181650,

AI-212.5712.43.2112.8609683, JRE 11.0.12+0-b1504.28-7817840x64 JetBrains s.r.o., OS Mac OS X(aarch64) v12.4, screens 3456.0x2234.0; Retina

AS: Chipmunk | 2021.2.1 Patch 1; Kotlin plugin: 212-1.7.10-release-333-AS5457.46; Android Gradle Plugin: (plugin information not found); Gradle: (gradle version information not found); Gradle JDK: version 11.0.12; NDK: from local.properties: (not specified), latest from SDK: (not found); LLDB: pinned revision 3.1 not found, latest from SDK: (package not found); CMake: from local.properties: (not specified), latest from SDK: (not found), from PATH: (not found)Source: send_feedback_icon

Unable to Extract Widget directly from Double click and Extract Widget (show popup but nothing happens after clicking on refactor)option and from Flutter Outline.  

All buttons are disabled in the Flutter outline except the extract method.  

![image](https://user-images.githubusercontent.com/20702445/184602799-a778b308-35f0-41c1-aea6-c9beddf5c541.png).

Unable to rename any variable. 
![image](https://user-images.githubusercontent.com/20702445/184603493-9c83925f-256c-4c40-a0b9-16d05d2ef085.png)

This happening only in one flutter project others are working fine.

**Comment by exaby73** [comment]
Hi @Wahab-Khan, please provide a [minimal, reproducible example][1] and the output of `flutter doctor -v`.

[1]: https://stackoverflow.com/help/minimal-reproducible-example

**Comment by Wahab-Khan** [comment]
`flutter doctor -v`
[✓] Flutter (Channel stable, 3.0.3, on macOS 12.5 21G72 darwin-arm, locale en-PK)
    • Flutter version 3.0.3 at /Users/macbookpro/Developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 676cefaaff (8 weeks ago), 2022-06-22 11:34:49 -0700
    • Engine revision ffe7b86a1e
    • Dart version 2.17.5
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/macbookpro/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.69.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.5 21G72 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 104.0.5112.79

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!



This happens only for one project every single time I try to export Widget, unable to make it right for this project. And also unable to reproduce this issue for other projects. Creating a new project or importing any project from Github works fine.

**Comment by exaby73** [comment]
Can you at least provide the code sample that this is not working on?

**Comment by Wahab-Khan** [comment]
That's not a single piece of code... it's not working in the whole project.

**Comment by exaby73** [comment]
Is this specific to _Extract Widget_ or are other refactorings like _Rename_ also not working?

**Comment by Wahab-Khan** [comment]
Yes rename not working, auto import is not working and all functions from the outline also not working except Extract Widget.

**Comment by exaby73** [comment]
I think this issue is best raised in [flutter/flutter-intellij](https://github.com/flutter/flutter-intellij). I do not see an issue with Flutter itself, therefore I am closing this issue. Comment if you disagree and we can reopen it. Thank you.
