### ISSUE TITLE
[go_router] Provide a better way to handle deep link routing

### ISSUE THREAD

**Issue by jefrrey017** [flutter/flutter#109550]
I use firebase_dynamic_links to create deep links on my app. When the app is brought to the foreground from the background through a deep link, go_router automatically navigates to the path thereby not letting me to add some custom logic. The reason for why I want to add custom logic is because the path associated with deep link is a protected path that can only be accessed if the user is authenticated. Since I can't do a check about the path originating from a deep link or within the app, there is no scope for me to save the deep link elsewhere so that it could be handled after the authentication. How can I manually include some logic before the go_router does its deep-link navigation?

Currently I have no code inside this callback, but I still get navigated to the deep link,

``` 
FirebaseDynamicLinks.instance.onLink.listen((dynamicLinkData) {    
  }).onError((error) {
    print(error.message);
  }); 
```

**Comment by huycozy** [comment]
Hi @jefrrey017, thanks for filing the issue. 
I see there's an open issue addressing the case you described #103659
You can leave there your comment and react an upvote to the original comment will help to raise the issue.
Closing as a duplication, so please follow up on it for further updates.
