### ISSUE TITLE
Build on Ios Crashes suddenly: fopen failed for data file: errno = 2 (No such file or directory)

### ISSUE THREAD

**Issue by RainPixels** [flutter/flutter#109517]
Hi friends, till now the building on iOS worked perfect, suddenly from today I get a strange error and the app crashes after building,  I get this error:

```
`Running pod install...                                              4.7s
Running Xcode build...                                                  
 └─Compiling, linking and signing...                        18.4s
Xcode build done.                                           73.0s
(lldb) 2022-08-14 22:52:33.397000+0100 Runner[14421:817725] fopen failed for data file: errno = 2 (No such file or directory)
Errors found! Invalidating cache...
libc++abi: terminating with uncaught exception of type std::__1::system_error: thread constructor failed: Resource temporarily unavailable
Installing and launching...                                        61.4s
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGABRT
    frame #0: 0x00000001d0788b38 libsystem_kernel.dylib`__pthread_kill + 8
libsystem_kernel.dylib`__pthread_kill:
->  0x1d0788b38 <+8>:  b.lo   0x1d0788b58               ; <+40>
    0x1d0788b3c <+12>: pacibsp 
    0x1d0788b40 <+16>: stp    x29, x30, [sp, #-0x10]!
    0x1d0788b44 <+20>: mov    x29, sp
Target 0: (Runner) stopped.
Error connecting to the service protocol: failed to connect to http://127.0.0.1:55591/`
```

My flutter doctor -v:

> [✓] Flutter (Channel stable, 3.0.5, on macOS 12.5 21G72 darwin-arm, locale en-GB)
>     • Flutter version 3.0.5 at /Users/razvanu/Documents/flutter
>     • Upstream repository https://github.com/flutter/flutter.git
>     • Framework revision f1875d570e (5 weeks ago), 2022-07-13 11:24:16 -0700
>     • Engine revision e85ea0e79c
>     • Dart version 2.17.6
>     • DevTools version 2.12.2
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
>     • Android SDK at /Users/razvanu/Library/Android/sdk
>     • Platform android-33, build-tools 32.0.0
>     • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
>     • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
>     • All Android licenses accepted.
> 
> [✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • CocoaPods version 1.11.3
> 
> [✓] Chrome - develop for the web
>     • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
> 
> [✓] Android Studio (version 2020.3)
>     • Android Studio at /Applications/Android Studio.app/Contents
>     • Flutter plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/9212-flutter
>     • Dart plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/6351-dart
>     • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
> 
> [✓] VS Code (version 1.70.1)
>     • VS Code at /Applications/Visual Studio Code.app/Contents
>     • Flutter extension version 3.46.0
> 
> [✓] Connected device (2 available)
>     • Buraca’s iPhone (mobile) • 00008110-001645D43C8A801E • ios            • iOS 15.6 19G71
>     • Chrome (web)             • chrome                    • web-javascript • Google Chrome 104.0.5112.79
> 
> [✓] HTTP Host Availability
>     • All required HTTP hosts are available
> 

Please help me with this issue asap, or guide me how to fix this, thanks in advance!

P.S: Also after running:   **arch -x86_64 pod install --repo-update**  I get this:

```
Pod installation complete! There are 48 dependencies from the Podfile and 90 total pods installed.

[!] Can't merge user_target_xcconfig for pod targets: ["FirebaseFirestore", "AutodetectLeveldb", "Base", "WithLeveldb", "fluttertoast"]. Singular build setting EXCLUDED_ARCHS[sdk=iphonesimulator*] has different values.

[!] Can't merge user_target_xcconfig for pod targets: ["FirebaseFirestore", "AutodetectLeveldb", "Base", "WithLeveldb", "fluttertoast"]. Singular build setting EXCLUDED_ARCHS[sdk=iphonesimulator*] has different values.

[!] Can't merge user_target_xcconfig for pod targets: ["FirebaseFirestore", "AutodetectLeveldb", "Base", "WithLeveldb", "fluttertoast"]. Singular build setting EXCLUDED_ARCHS[sdk=iphonesimulator*] has different values.

[!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target `Runner` to `Target Support Files/Pods-Runner/Pods-Runner.profile.xcconfig` or include the `Target Support Files/Pods-Runner/Pods-Runner.profile.xcconfig` in your build configuration (`Flutter/Release.xcconfig`).
```

**Comment by danagbemava-nc** [comment]
Hi @RainPixels, please provide the full output of `flutter run -v`. The output may be huge, so kindly put it into a .txt file and attach it here. 

Please also provide the following 
- your pubspec.yaml & pubspec.lock
- your Podfile and podfile.lock 

Thank you

**Comment by RainPixels** [comment]
Hi, @danagbemava-nc 

Here you go, all the files you request:

[output.txt](https://github.com/flutter/flutter/files/9337627/output.txt)
[podfile.lock.txt](https://github.com/flutter/flutter/files/9337630/podfile.lock.txt)
[pubspec.lock.txt](https://github.com/flutter/flutter/files/9337631/pubspec.lock.txt)

Thanks in advance for your help!

**Comment by RainPixels** [comment]
Fixed my issue by:

1A.Complete cleanup (pod reset)
rm -rf ~/Library/Caches/CocoaPods
rm -rf Pods
rm -rf ~/Library/Developer/Xcode/DerivedData/*
pod deintegrate
pod setup
pod install

1B. **cd ios** and run `arch -x86_64 pod install --repo-update`

2. I got from git pull: a little change in Xcode Settings but with and huge impact => crashing the entire app by changing without knowing the Lunch Screen File from: **LaunchScreen** to _Main_ , screenshots:
<img width="712" alt="Screenshot 2022-08-15 at 22 55 36" src="https://user-images.githubusercontent.com/103572833/184725808-741728f8-21fd-43f2-b78b-30af639284a4.png">
instead of
<img width="721" alt="Screenshot 2022-08-15 at 22 56 04" src="https://user-images.githubusercontent.com/103572833/184725832-8eea9973-4d90-4520-8aa1-b7020f85b3d5.png">

Hope will be usefull for someone ;) Good luck!
