### ISSUE TITLE
[CP] Fix Android platform view creation flow

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#109545]
### issue_link

https://github.com/flutter/flutter/issues/107297

### Commit Hash

ab23233

### Target

beta

### pr_link

https://github.com/flutter/flutter/pull/109544

### Impacted Users

All clients of Android plugins using Hybrid Composition (including the 1P google_maps_flutter)

### Impact Description

Assertion failures, performance issues, and possible crashes on platform view creation due to double-create.

### Workaround

Only to for plugin authors to stop using Hybrid Composition, which causes other potential issues.

### Risk

medium

### Test Coverage

yes

### Validation Steps

1. Check out the flutter/plugins repository.
2. Edit `packages/google_maps_flutter/google_maps_flutter_android/lib/src/google_maps_flutter_android.dart` to replace `PlatformViewsService.initSurfaceAndroidView` with `PlatformViewsService.initExpensiveAndroidView`. (This is a change we will make and publish to the plugin shortly to work around a regression in Flutter 3.0, but are holding off on until this is fixed on `beta`).
3. `cd packages/google_maps_flutter/google_maps_flutter_android/example`
4. Launch an Android device or simulator.
5. `flutter run` on that device/simulator.
6. Look for (lack of) assertion failures about futures that have already completed.

**Comment by stuartmorgan** [comment]
Because it changes some logic around the creation flow of Android platform views, it could potentially regress other aspects of Android platform view creation (including for non-hybrid-composition plugins). For instance, the first version of the PR broke display of the `google_mobile_ads` plugin, which was caught by google3 testing but not Flutter testing.

**Comment by itsjustkevin** [comment]
That is fair, thank you for clarifying.  If we get this into this weeks beta, I think we will have sufficient signal from google3 before landing.

**Comment by dnfield** [comment]
I approve
