### ISSUE TITLE
Dynamic change status bar color for web not working

### ISSUE THREAD

**Issue by inagornyi** [flutter/flutter#109559]
I want to change the color of the status bar for the web at runtime, but with no success.
I have tried different ways to change the color of the status bar.

**Comment by exaby73** [comment]
Hello @inagornyi. Not sure what you mean by changing the status bar color. The status bar exists on Android and iOS, but not on web and desktop. Could you provide some screenshots or video explaining the issue?

**Comment by inagornyi** [comment]
> Hello @inagornyi. Not sure what you mean by changing the status bar color. The status bar exists on Android and iOS, but not on web and desktop. Could you provide some screenshots or video explaining the issue?

Sorry,
I meant for browsers (ios / android).
I found how to solve this problem:
```
<script>
    function changeThemeColor(color) {
      var themeColor = document.querySelector("meta[name=theme-color]");
      themeColor.setAttribute("content", color);
    }
    
    function changeBackgroundColor(color) {
      document.body.style.backgroundColor = color;
    }
  </script>
```
but the standard flutter solutions did not work for me :(

**Comment by exaby73** [comment]
In [the docs](https://api.flutter.dev/flutter/services/SystemUiOverlayStyle/statusBarColor.html), it's mentioned that this only works on Android. This is working as expected, therefore, I will close this issue. Feel free to comment if you disagree and we can reopen the issue. Thank you.
