### ISSUE TITLE
Flutter tool malfunction after migrating the codebase from windows to mac environment

### ISSUE THREAD

**Issue by johnmelodyme** [flutter/flutter#109527]
The Exception I got: 
```
[   +4 ms] "flutter run" took 920,808ms.
[  +12 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:669:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1125:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:92:3)
           <asynchronous suspension>
   ```
           
      The Method I had tried:
      
      >flutter pub cache repair && flutter clean && flutter pub get 
      
      and deleted `pubspec.yml` , `.gradle`.
      
      And the error persists.
      
```
      My flutter doctor returns :

      
      [✓] Flutter (Channel stable, 2.5.1, on macOS 12.4 21F2081 darwin-arm, locale en-MY)
    • Flutter version 2.5.1 at /Users/johnmelodyme/fvm/versions/2.5.1
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffb2ecea52 (11 months ago), 2021-09-17 15:26:33 -0400
    • Engine revision b3af521a05
    • Dart version 2.14.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/johnmelodyme/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    • CocoaPods version 1.11.3

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.70.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.46.0

[✓] Connected device (1 available)
    • Redmi Note 9S (mobile) • 192.168.248.121:5555 • android-arm64 • Android 11 (API 30)

! Doctor found issues in 2 categories.
```

I do aware that the issues are related to Xcode, do I need Xcode installed for developing an android application in flutter? 

@ianloic @anaisbetts @sgraham @gmoothart @sethladd

**Comment by exaby73** [comment]
Hello @johnmelodyme. I see you're using `Flutter Channel stable, 2.5.1`. Can you upgrade to the latest Flutter stable and confirm if the issue persists?

**Comment by johnmelodyme** [comment]
> Hello @johnmelodyme. I see you're using `Flutter Channel stable, 2.5.1`. Can you upgrade to the latest Flutter stable and confirm if the issue persists?

My companies requirements are using 2.5.1, if this is a personal project I would consider to upgrade it.

**Comment by exaby73** [comment]
Can you provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) for this issue so that we can investigate it further?

**Comment by johnmelodyme** [comment]
> Can you provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) for this issue so that we can investigate it further?

Sure. In a minute. (Driving now)

**Comment by exaby73** [comment]
Sure no problem :)

**Comment by johnmelodyme** [comment]
> Sure no problem :)

In My company, I was instructed to use `fvm` which I had config the PATH and have the environment ready. Previously the source code was coded in a Windows environment and copied and pasted in a mac environment (current).

I tried solving it as suggested in https://github.com/flutter/flutter/issues/107798 and https://github.com/flutter/flutter/issues/60441#issuecomment-651240121 , but It didn't work.

**Comment by exaby73** [comment]
I use `fvm` as well. Great tool. Were you able to produce that code sample?

**Comment by johnmelodyme** [comment]
> I use `fvm` as well. Great tool. Were you able to produce that code sample?

I create a new project `fvm flutter create abc` and `fvm flutter run` it still returned the same error.

**Comment by exaby73** [comment]
Okay. I see you are running on arm (Apple Silicon). You may need to add arm64 to your xcode project. Can you provide the logs to `flutter run -v`?

**Comment by johnmelodyme** [comment]
> add arm64 to your xcode project

'add arm64 to your xcode project' What do you mean?

**Comment by johnmelodyme** [comment]
is this look right?

```
[   +7 ms] Running Gradle task 'assembleDebug'...
[   +1 ms] Using gradle from /Users/johnmelodyme/Downloads/a/lalala/android/gradlew.
[  +57 ms] Exception while looking for Android Studio: FileSystemException: Directory listing failed, path = '/Applications/XAMPP/xamppfiles/var/mysql/test/' (OS Error: Permission denied, errno = 13)
[        ] Exception while looking for Android Studio: FileSystemException: Directory listing failed, path = '/Applications/XAMPP/xamppfiles/var/mysql/phpmyadmin/' (OS Error: Permission denied, errno = 13)
[        ] Exception while looking for Android Studio: FileSystemException: Directory listing failed, path = '/Applications/XAMPP/xamppfiles/var/mysql/mysql/' (OS Error: Permission denied, errno = 13)
[        ] Exception while looking for Android Studio: FileSystemException: Directory listing failed, path = '/Applications/XAMPP/xamppfiles/var/mysql/performance_schema/' (OS Error: Permission denied, errno = 13)

```

**Comment by johnmelodyme** [comment]
> > add arm64 to your xcode project
> 
> 'add arm64 to your xcode project' What do you mean?

I downloaded this version 'https://storage.googleapis.com/flutter_infra_release/releases/stable/macos/flutter_macos_arm64_3.0.5-stable.zip'

**Comment by exaby73** [comment]
See https://github.com/flutter/flutter/issues/107897 for a possible solution to your issue

**Comment by johnmelodyme** [comment]
> See #107897 for a possible solution to your issue

But that's for IOS config innit?

**Comment by johnmelodyme** [comment]
I fixed it @exaby73, Thank you so much for your help!

I faced 4 problems and these were my solutions:

1.  It was caused by the missing `google-service.json` file and I fixed that. 
2. `Apple Silicon M2` required `rosetta` which I already installed but the problem persists strangely, I had `rosetta` reinstalled.
3. The Gradle conflicts and was unable to `download` and `unzip` it. Fixed by doing manually. (in `.gradle`)
4. Conflicts from `fvm` downloaded the wrong release of flutter in my case. `fvm` downloaded for [Intel](https://storage.googleapis.com/flutter_infra_release/releases/stable/macos/flutter_macos_3.0.5-stable.zip) by default, and I fixed it by downloading flutter for [Apple Silicon M2](https://storage.googleapis.com/flutter_infra_release/releases/stable/macos/flutter_macos_arm64_3.0.5-stable.zip) and replace it in`/Users/{username_pwd}/fvm/versions/`.

So in my case, the errors weren't from installing the wrong SDK versions, or not installing `xcode` the problems are as above.

**Comment by anonnothing** [comment]
> I fixed it @exaby73, Thank you so much for your help!
> 
> I faced 4 problems and these were my solutions:
> 
> 1.  It was caused by the missing `google-service.json` file and I fixed that. 
> 2. `Apple Silicon M2` required `rosetta` which I already installed but the problem persists strangely, I had `rosetta` reinstalled. Refer [here](https://github.com/flutter/website/pull/7119#issuecomment-1124537969)
> 3. The Gradle conflicts and was unable to `download` and `unzip` it. Fixed by doing manually. (in `.gradle`)
> 4. Conflicts from `fvm` downloaded the wrong release of flutter in my case. `fvm` downloaded for [Intel](https://storage.googleapis.com/flutter_infra_release/releases/stable/macos/flutter_macos_3.0.5-stable.zip) by default, and I fixed it by downloading flutter for [Apple Silicon M2](https://storage.googleapis.com/flutter_infra_release/releases/stable/macos/flutter_macos_arm64_3.0.5-stable.zip) and replace it in`/Users/{username_pwd}/fvm/versions/`.
> 
> So in my case, the errors weren't from installing the wrong SDK versions, or not installing `xcode` the problems are as above. 
> 

Not bad

**Comment by anaisbetts** [comment]
Why do people randomly CC me on bugs in the Flutter repo? It literally _only_ happens here, yet happens constantly. I am not currently nor have I ever been a Flutter team member

**Comment by johnmelodyme** [comment]
> Why do people randomly CC me on bugs in the Flutter repo? It literally _only_ happens to me here, yet happens constantly. I am not currently nor have I ever been a Flutter team member

Because when I `@` your name pop out the first.

**Comment by anaisbetts** [comment]
> Because when I @ your name pop out the first.

That at least makes some kind of sense!

**Comment by exaby73** [comment]
To avoid such situations in the future, please avoid pinging random people
