### ISSUE TITLE
Swift plugin support

### ISSUE THREAD

**Issue by collinjackson** [flutter/flutter#10968]
In #9694 we commented out `use_frameworks!` in the new project template.

I would like to bring it back so that Swift plugins will be supported.

The problem is CocoaPods/CocoaPods#3289 - plugins that have third-party dependencies (e.g. Google Sign In) don't work properly and get errors of this form:

    [!] The 'Pods' target has transitive dependencies that include static binaries

`use_frameworks!` will happily coexist with static transitive dependencies if you override the static framework verification:

    pre_install do |installer|
        # workaround for https://github.com/CocoaPods/CocoaPods/issues/3289
        def installer.verify_no_static_framework_transitive_dependencies; end
    end

However, the header files don't get copied into the right place.

I think we need to understand this further and see if we can get the header to be right.

**Comment by mit-mit** [comment]
Are you working on this @collinjackson ?

**Comment by collinjackson** [comment]
I am, though it's backed up behind a couple other higher priority tasks. Happy to brain dump here if there's anyone else who wants to take it on.

**Comment by mclark4386** [comment]
Really need this, so I would be happy to see a brain dump and give it my best shot^^

**Comment by mclark4386** [comment]
Not to rush you @collinjackson , but I just realized I didn't tag you so I thought would tag you just to make sure. I'm sure you get a bazillion notifications from github everyday like I do^^;

**Comment by mclark4386** [comment]
So I took the liberty of making a test case project: https://github.com/mclark4386/test_flutter_plugins so that when that will `flutter run` it should be good^^

**Comment by mclark4386** [comment]
So it looks like it's not setting up the includes properly...
```
/home/mclark4386/Projects/TESTS/dart/flutter/test_plugins/ios/Pods/Headers/Private/Firebase/Firebase.h:1:9: fatal error: 'FirebaseAnalytics/FirebaseAnalytics.h' file not found
    #import <FirebaseAnalytics/FirebaseAnalytics.h>
            ^
    1 error generated.
```

**Comment by eseidelGoogle** [comment]
@collinjackson looks like this got dropped.  Are you available for a brain dump?

**Comment by eseidelGoogle** [comment]
FYI @zanderso or @mit-mit who may also have knowledge or interest here.

**Comment by collinjackson** [comment]
I pinged @szakarias about this last week to gauge availability and she said she'd get back to me. I'll follow up again. Thanks!

**Comment by collinjackson** [comment]
I had a call today with @szakarias to talk about the plan for resolving this.

It seems like no matter what approach we take, we should probably change the template's Podfile to pull in some Ruby that lives in the flutter/flutter github repo so we can more change the behavior to be compatible with Future CocoaPods versions without forcing devs to edit their Podfiles.

These are the three potential options I see that could work, I leave it up to @szakarias to pick the best one:

1. Turn on `use_frameworks!`and override `verify_no_static_framework_transitive_dependencies` as described above. Search the CocoaPods code base for `requires_frameworks?` and decide which methods need to be overridden in order to get CocoaPods to copy the headers as if `use_frameworks!` were not being used. Use monkey patching or its [alternatives](https://stackoverflow.com/a/4471202/1463116) to accomplish this.
1. Have the Podfile check an environment variable to determine whether to set `use_frameworks!` or not. When the Flutter build system runs `pod install` it runs it first without `use_frameworks!`, copies the header directory and sets it aside, then re-runs with `use_frameworks!` and move the headers back into the correct location.
1. Submit a PR to the CocoaPods repo to copy the headers in `use_frameworks!` mode for development pods.

**Comment by sethladd** [comment]
Carnivore expressed interest in writing plugins with Swift.

**Comment by rxlabz** [comment]
Hi, any update on this ? @collinjackson @szakarias 
I have a plugin written in Swift, I don't know if I better try to rewrite it in ObjC ?

**Comment by sethladd** [comment]
cc @mit-mit

**Comment by collinjackson** [comment]
my understanding is that @szakarias is still owning this one, but I can take it back if need be

**Comment by szakarias** [comment]
Yes, I am, but at the moment I am working on another task with higher priority. This one is up next.

**Comment by albrecht87** [comment]
We created a flutter project with Swift support and ran in an issue while using firebase analytics. Removing use_frameworks! from the Podfile helped. Seems like this issue: https://github.com/flutter/flutter/pull/10205 Please consider to add a proper warning or a real fix.

**Comment by rmtmckenzie** [comment]
What is the progress on this? I'm in the process of porting over an existing project to flutter and have a bunch of swift dependencies that will frankly be too much work to port to objc.

**Comment by szakarias** [comment]
I am sorry, but there is unfortunately no news to report yet.

**Comment by animeshjain** [comment]
Hi, just wanted to bump this again. It'd be great to be able to write plugins in Swift. For eg. I was thinking about writing a plugin for in app purchases, but I'm really uncomfortable writing Objective C. Any chance someone might pick this up soon?

**Comment by rmtmckenzie** [comment]
FYI it is possible to work around this issue without modifying plugins (although a bit of a headache) by including swift plugin dependencies as git submodules in your app's repo & adding dependency_overrides in the pubspec for those submodules, making the podfile ignore any swift plugins, importing the swift files to xcode manually, and replacing the generated plugin registrant (i.e. not including the generated one in the project files) with a hand-written one in which you copy from the generated one but modify any swift plugins to be imported directly.

Definitely not ideal, but at least you could write the plugin in swift and once they do fix this you could just undo the changes in your app without having to modify the plugin.

**Comment by bramvbilsen** [comment]
I'm also still waiting for this :)

**Comment by jmnyv** [comment]
Yup, still an issue. :)

**Comment by szakarias** [comment]
This should now fixed by #14667 and https://github.com/flutter/plugins/pull/385

**Comment by itchyfingertips** [comment]
Not really. I am on beta channel and got this bug tonight. Tried to add Facebook SDK but it did not work until I commented out use_frameworks!.

**Comment by itchyfingertips** [comment]
Does not work even in master channel.

**Comment by szakarias** [comment]
@itchyfingertips could you please provide more details on your project and the errors you experience?

**Comment by itchyfingertips** [comment]
You can create new project with swift on iOS side:
1) flutter create -i swift demo

Add this package, which contains Facebook SDK pods.
2) flutter_facebook_login 1.1.0

build project 
3) flutter build ios

And you will get the error.

If you comment out use_frameworks! error will be gone, but thats not ok.

**Comment by yy1300326388** [comment]
+1

**Comment by zoechi** [comment]
@yy1300326388 please don't post +1 comments.

**Comment by Sh1d0w** [comment]
@escamoteur Open the project in Xcode, the select File -> New -> File and choose Swift File.

Xcode then automatically will add Swift bridging header and you should be all set.
