### ISSUE TITLE
[android] `hmssdk_flutter` has incorrect layering in Flutter 3.0+

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#109689]
This is split off from https://github.com/flutter/flutter/issues/103630 for detailed investigation.

According to https://github.com/flutter/flutter/issues/103630#issuecomment-1218077657, the fix for https://github.com/flutter/flutter/issues/103630 does not work for https://pub.dev/packages/hmssdk_flutter. The most likely explanation is that fallback to Virtual Display isn't triggering for the plugin, although it's possible that there's something else going on.

I tried to debug locally, but the example doesn't build out of the box; it has Firebase dependencies that appear to need server-side setup, and even then it's not clear how to get a valid test URL. Ideally we need a minimal repro example with no Firebase or other service dependencies, and a hard-coded test URL that we can use.

From source inspection, it's surprising that the fix wouldn't have worked, since it appears to be using a surface view for its rendering.

**Comment by Decoder07** [comment]
Hi @stuartmorgan we have created a minimal app for repro : 
https://github.com/Decoder07/100ms-flutter-test/tree/109689/repro-build

If you need anything more please let us know.
cc : @ygit

**Comment by stuartmorgan** [comment]
Thanks, I'm able to run that test.

@rlee1990 what exactly were you testing when you said "I switched to the beta channel and ran the latest beta but the issue was still there"? With `stable` I can reproduce the controls (e.g., toggle video and toggle audio) being hidden, but it works fine on both `beta` and `master` (and my debug logging on `master` shows that fallback due to `SurfaceView` is being triggered as expected).

**Comment by stuartmorgan** [comment]
@Decoder07 Are you able to reproduce issues on `beta`?

**Comment by rlee1990** [comment]
> due

Unless a change was made on their end anytime I would use a stack and have the video render view from 100ms and then add buttons the buttons would always be under the video. When using the same layout in 2.10.5 the buttons showed on top of the video.

**Comment by stuartmorgan** [comment]
@rlee1990 Does the test case above work for you on `beta`?

**Comment by rlee1990** [comment]
> @rlee1990 Does the test case above work for you on `beta`?

I will give it a try one moment

**Comment by rlee1990** [comment]
> @rlee1990 Does the test case above work for you on `beta`?

It does not work. The why they have it set up is the video view is cut short so the buttons show at the bottom. When adding the buttons to the same area as the video view they do not show.

**Comment by stuartmorgan** [comment]
> It does not work. The why they have it set up is the video view is cut short so the buttons show at the bottom.

Could you provide a screenshot of exactly what you are looking at in the repro case that doesn't work on `beta` (and the comparison in 2.10 where it does)? I see buttons over the video view when I run that test case.

**Comment by rlee1990** [comment]
> > It does not work. The why they have it set up is the video view is cut short so the buttons show at the bottom.
> 
> Could you provide a screenshot of exactly what you are looking at in the repro case that doesn't work on `beta` (and the comparison in 2.10 where it does)? I see buttons over the video view when I run that test case.

I just did a reboot and cleaned the project and it's showing on beta with the above repo.

**Comment by rlee1990** [comment]
> @rlee1990 I'm not sure what "it's showing" means.
> 
> To investigate further here (given that in all of my testing so far `beta` does fix the issue with this plugin) we will need:
> 
> * exact code for a layering issue that reproduces with this plugin on `beta`.
> * the output of `flutter --version`, to make sure we're testing the same thing.
> * a screenshot of the issue on `beta`, and a screenshot of the same thing on 2.10 to show how it is supposed to look.

It works after a ran a clean of the package in beta.

**Comment by stuartmorgan** [comment]
Okay, then I'm going to close this as a duplicate of https://github.com/flutter/flutter/issues/103630.
