### ISSUE TITLE
image picker not working in mac 

### ISSUE THREAD

**Issue by Div-47** [flutter/flutter#109684]
Hello there , the image picker never works on apple macbook m1 ios simulator with any ios version. in intel it was working but when i switched to macbook m1 ,it stopped working on ios simulator. please fix or help me to get out of this.

**Comment by danagbemava-nc** [comment]
Hi @Div-47, please provide a complete minimal reproducible code sample as well as the output of `flutter doctor -v`. 

Please also provide the version of `image_picker` you're using and the steps to reproduce this issue. 

Thank you
