### ISSUE TITLE
[Impeller] Metal validation failures on CanRenderTiledTexture/Metal.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#109648]
The following validation error is reported.

```
[ RUN      ] Play/AiksTest.CanRenderTiledTexture/Metal
-[MTLDebugBlitCommandEncoder generateMipmapsForTexture:]:1109:
  failed assertion
    `Generate Mipmaps For Texture Validation [tex mipmapLevelCount](1) must be > 1.'
```

The steps to enable Metal validation in command line apps (like the Google Test harness) [are here](https://github.com/flutter/engine/blob/main/impeller/docs/metal_validation.md).

**Comment by chinmaygarde** [comment]
cc @bdero

**Comment by bdero** [comment]
FYI @ColdPaleLight
