### ISSUE TITLE
[Impeller] Ensure that the Vulkan and OpenGLES backends build together by default.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#109645]
Today, there is a GN opt-in to using the Vulkan backend. This makes refactors that affect all backends a bit harder to affect as we need to manually enable the Vulkan backend. Vulkan and OpenGL can co-exist on the desktop targets. So there is no need to have a separate target for Vulkan. We should enable building the backend by default (and perhaps skip tests till the backend is functional).

This is also needed for https://github.com/flutter/flutter/issues/109636.

**Comment by chinmaygarde** [comment]
cc @iskakaushik

**Comment by Flutterdev55** [comment]
�
![StandingOvationGIF](https://user-images.githubusercontent.com/109794233/185098080-f5b914ac-ff8e-4023-a045-55d05d8455b0.gif)
�

**Comment by iskakaushik** [comment]
This is now complete
