### ISSUE TITLE
[gen-l10n] Unable to export generated files from another package

### ISSUE THREAD

**Issue by ferraridamiano** [flutter/flutter#109606]
I'm working on a flutter monorepo project and I faced many issues when I decided to put all the translation files in a separate package (I use `intl`). I tought I just need to export `package:flutter_gen/gen_l10n/app_localizations.dart` so that when I import the translation package I could just use all the translations. I tought it was a common use-case.
But that doesn't work! I think it is counter-intuitive. I would expect that if I export a genereated file and then I import it from another package it works (just like any other non generated file). To me it seems a major blocker for large projects. Are there any other ways to create a translation package?

## Steps to Reproduce
1. Clone the example repo: `git clone https://github.com/ferraridamiano/fluttergen_export_issue`
2. Take a look to the errors reported by the IDE

**Expected results:**
Same behaviour for generated and non-generated files

**Actual results:**
Different behaviour for generated and non-generated files

**Comment by huycozy** [comment]
Hi @ferraridamiano, thanks for filing the issue.
I see there's an open issue addressing the case you described #96839, but it's closed and referenced to issue #84979.
You can leave there your comment and react an upvote to the original comment will help to raise the issue.
Closing as a duplication, so please follow up on it for further updates.

**Comment by ferraridamiano** [comment]
Hi @huycozy and thank you for your answer. The first issue that you mentioned is absolutely related to this one. But they closed it since they found a workaround (and NOT a solution). I think that the issue still exists, even if a workaround exists as well. The second issue that you mentioned is related to the aforementioned workaround but not directly related to this problem.
I would like to upvote the first issue but it is closed 😞

**Comment by huycozy** [comment]
Hi @ferraridamiano 
I reopen the issue for further discussion. Please try the workaround as below steps to see if it helps to solve the issue:

Steps for the workaround:
1. Update translations/l10n.yaml: Add `synthetic-package: false`
```
arb-dir: lib/l10n
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
synthetic-package: false
```
2. Open the Terminal from root dir of repository
3. cd translations
4. flutter gen-l10n
5. Update main_app/lib/main.dart: import `AppLocalizations` class
```
import 'package:translations/l10n/app_localizations.dart';
```

**Comment by ferraridamiano** [comment]
Thank you very much for reopening this.
Of course the workaround works! But to me it's still just a workaround. To me the main problems of this are:
- Inconsistency when exporting non-generated code and generated code
- No code generation when running `flutter run`
- Forced to either running multiple command the first time to generate the code or including generated files in the repository (which is not elegant)

Tell me what do you think

**Comment by huycozy** [comment]
Hi @ferraridamiano, sorry for replying late. Labeling this issue for further options from the team.

**Comment by Jasguerrero** [comment]
cc @HansMuller

**Comment by thkim1011** [comment]
Hey @ferraridamiano, I talked to someone who originally designed how the synthetic packages work; the way that the synthetic package works is that the `generate: true` flag in `pubspec.yaml` adds the synthetic package into `.dart_tool/package_config.json`.

Unfortunately, this causes the `AppLocalizations` class to not be available when imported by a different package, but this was something that was considered an acceptable trade-off in the original design. If you need your localizations to be available to other packages, then the proper way to do this is by setting `synthetic-package: false`.

As to `flutter run` not regenerating `AppLocalizations`, there's an open issue for that and I can take a look soon: #84979.
