### ISSUE TITLE
How to set access_type - or how to get refresh_token

### ISSUE THREAD

**Issue by arualana** [flutter/flutter#109642]
From the google docs:
[Step 1: Set authorization parameters](https://developers.google.com/identity/protocols/oauth2/web-server#creatingclient)

> **access_type**

> Recommended
> Indicates whether your application can refresh access tokens when the user is not present at the browser. Valid parameter values are online, which is the default value, and offline.

> Set the value to offline if your application needs to refresh access tokens when the user is not present at the browser. This is the method of refreshing access tokens described later in this document. This value instructs the Google authorization server to return a refresh token and an access token the first time that your application exchanges an authorization code for tokens.

I don't find how to set this in the library. Thank you

What i need is to exchange the authorization code for an access_token, thank you

**Comment by stuartmorgan** [comment]
You've linked to documents for implementing OAuth authentication directly; the Flutter team doesn't maintain any libraries at that level.

If you are using a lower-level authentication library you'll need to direct this request to the authors of that library.

**Comment by arualana** [comment]
Ok, thank you
