### ISSUE TITLE
[macOS] Bring up more performance/benchmark tests x86

### ISSUE THREAD

**Issue by a-wallen** [flutter/flutter#109633]
This issue is a fork of [#70027](https://github.com/flutter/flutter/issues/70027) for `platform-mac`. [#70027](https://github.com/flutter/flutter/issues/70027). Build tests for `platform-mac` should mirror `platform-windows` as closely as possible.

- [x] https://github.com/flutter/flutter/issues/109799
- [ ] https://github.com/flutter/flutter/issues/109800

## Description 
> The initial desktop integration tests are running now, but they need to be expanded beyond the initial gallery build test; filing this to make sure that planned work is captured in the issue tracker. This should be much more straightforward that getting the first one running was, since the bot work is all complete.
> 
> In particular we should ensure we are testing building a freshly created project to catch errors in template changes. (I haven't checked where that test lives on existing platforms; it may be a device lab test, which still needs desktop bring-up).

**Comment by christopherfujino** [comment]
@a-wallen interesting! When I'm back in office (starting 8/24) we should touch base, I'd like to hear more about the desktop build testing strategy.
