### ISSUE TITLE
Android platform view fallback to Virtual Display doesn't trigger when `SurfaceView` is added dynamically

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#109690]
This is split off from https://github.com/flutter/flutter/issues/103630 for detailed investigation.

According to https://github.com/flutter/flutter/issues/103630#issuecomment-1218077657, the fix for https://github.com/flutter/flutter/issues/103630 does not work for https://pub.dev/packages/dyte_client. The most likely explanation is that fallback to Virtual Display isn't triggering for the plugin, although it's possible that there's something else going on.

I tried to debug locally, but the example doesn't build out of the box, and appears to require access to a non-public SDK. We'll need a minimal repro case to investigate further.

**Comment by stuartmorgan** [comment]
@rlee1990 you mentioned that you've already reached out to the developers; if you could ask them to follow up here that would be great.

**Comment by rlee1990** [comment]
@stuartmorgan Thank you and will do

**Comment by rlee1990** [comment]
@stuartmorgan It appears that this is now the only one having an issue from the image below in the video view there are buttons at the bottom of the video that do no show ![image](https://user-images.githubusercontent.com/21372502/185418253-23e1fe84-e1cc-4911-85a2-17de17f077a0.jpeg)

**Comment by stuartmorgan** [comment]
Thanks, I was able to reproduce with https://github.com/dyte-in/flutter-sample-app

The reason that https://github.com/flutter/flutter/issues/103630 didn't work for this plugin is that at view creation time, when the view hierarchy is scanned for `SurfaceView`s, there isn't one (it looks like it's just an empty container view: `com.facebook.react.ReactRootView`), so fallback to Virtual Display doesn't trigger. Then later, a SurfaceView is added, triggering the bug.

It might be possible to monitor the view hierarchy for changes and then dynamically trigger a switch from TLHC to VD if a SurfaceView is added. (cc @bparrishMines )

In the short term, affected plugins should be able to work around this issue (for Flutter 3.3, which is currently on `beta`, and later) by making the view returned from their view factory contains an initial dummy `SurfaceView` so that fallback mode triggers.

**Comment by rlee1990** [comment]
> Thanks, I was able to reproduce with https://github.com/dyte-in/flutter-sample-app
> 
> The reason that #103630 didn't work for this plugin is that at view creation time, when the view hierarchy is scanned for `SurfaceView`s, there isn't one (it looks like it's just an empty container view: `com.facebook.react.ReactRootView`), so fallback to Virtual Display doesn't trigger. Then later, a SurfaceView is added, triggering the bug.
> 
> It might be possible to monitor the view hierarchy for changes and then dynamically trigger a switch from TLHC to VD if a SurfaceView is added. (cc @bparrishMines )
> 
> In the short term, affected plugins should be able to work around this issue (for Flutter 3.3, which is currently on `beta`, and later) by making the view returned from their view factory contains an initial dummy `SurfaceView` so that fallback mode triggers.

Thanks, I will let the developers know.

**Comment by stuartmorgan** [comment]
https://github.com/flutter/flutter/issues/110816 is another duplicate of this (also starting as an empty `com.facebook.react.ReactRootView`).

@bparrishMines Do you have cycles to look into whether dynamic fallback is viable?

**Comment by stuartmorgan** [comment]
Oh, sorry, I'll pick that back up tomorrow. It mostly needs tests.

**Comment by geiszla** [comment]
Any news on this? This still prevents us to upgrade to Flutter v3.

I see that https://github.com/flutter/engine/pull/35233 has been merged, so is there anything blocking this issue?

**Comment by stuartmorgan** [comment]
> This still prevents us from upgrading to Flutter v3.

What plugin is preventing you from updating? As noted above, developers of plugins with this behavior can work around it with a minor change.

**Comment by geiszla** [comment]
> > This still prevents us from upgrading to Flutter v3.
> 
> What plugin is preventing you from updating? As noted above, developers of plugins with this behavior can work around it with a minor change.

It's a plugin that's not being maintained anymore, but we already created a fork, so we might be able to add this workaround. Thanks!

**Comment by dayron9110** [comment]
this issue is the same problem that I have?
https://github.com/HMS-Core/hms-flutter-plugin/issues/253

**Comment by dayron9110** [comment]
This workaround worked for me:

```
    override fun onCreate(savedInstanceState: Bundle?) {
        intent.putExtra("background_mode", "transparent");//TODO Huawei fix map
        super.onCreate(savedInstanceState);
        MapsInitializer.initialize(applicationContext, Renderer.LATEST, this)
    }

    //TODO Huawei fix map
    override fun onFlutterTextureViewCreated(flutterTextureView: FlutterTextureView) {
        // We do not actually need a transparent TextureView.
        flutterTextureView.isOpaque = true;
        super.onFlutterTextureViewCreated(flutterTextureView);
    }
```
Thanks to @ppiatkowski-here

**Comment by rameshkec85** [comment]
Patch released and fixed in the beta release. [dyte_client 0.9.0-beta.1  ](https://pub.dev/packages/dyte_client/versions/0.9.0-beta.1/example)

**Comment by johnmccutchan** [comment]
Note, it does not appear possible to dynamically switch from Android View Hierarchy to Virtual Display or vice-versa. 

If your Platform View uses a `SurfaceView` it must be present when the Platform View is first instantiated and then the correct behaviour will trigger.

NOTE: You should avoid using SurfaceViews if at all possible. TextureView does not suffer from this issue.
