### ISSUE TITLE
Flutter autofill input fields doesn't work on iOS, but it works on Android. 

### ISSUE THREAD

**Issue by Lazizbek97** [flutter/flutter#109663]
What I have done:
1. I have switched on AutoFill passwords in Simulator. iOS simulator version is 15.5(checked for 14.0 also).
2. The code here for auto-filling inputs:

```dart
 AutofillGroup(
          child: Column(
            children: <Widget>[
              TextField(
                controller: usernameController,
                autofillHints: const <String>[AutofillHints.username],
              ),
              TextField(
                controller: passordController,
                autofillHints: const <String>[
                  AutofillHints.password
                ],
              ),
            ],
          ),
        ),
  ```
 It's not showing any older(used for this app) passwords or usernames
     
 3. Flutter doctor -v:

```
lazizbekfayziev@Lazizbeks-MacBook-Air billz-mobile-1 % flutter doctor -v
[✓] Flutter (Channel stable, 2.5.3, on macOS 12.5 21G72 darwin-arm, locale en-UZ)
    • Flutter version 2.5.3 at /Users/lazizbekfayziev/dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (10 months ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/lazizbekfayziev/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.4.1, Build version 13F100
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.69.2)
    • VS Code at /Users/lazizbekfayziev/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.46.0

[✓] Connected device (2 available)
    • iPhone 11 Pro Max (mobile) • 1EFB7A68-D962-4EEC-BDCC-52172013E606 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-0
      (simulator)
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 104.0.5112.101

• No issues found!
```
Maybe, There are any specific things to do for IOS? I haven't found any solutions yet, please help as soon as possible.

**Comment by maheshmnj** [comment]
Hi @Lazizbek97, Thanks for filing the issue. You seem to be using an older version of flutter, I would suggest upgrading to the latest stable release which seems to have fixed the issue.
see: https://github.com/flutter/flutter/pull/97846

**Comment by Lazizbek97** [comment]
> r filing the issue. Yo

Hii, my already built with flutter 2.5.3 version. So should i have to migrate it to Flutter 3 to use Autofill?

**Comment by maheshmnj** [comment]
@Lazizbek97 Yes, In order to use the latest fix, You will need to upgrade.

**Comment by husnainasghar** [comment]
@maheshmnj I am using flutter 3.0.5, I am also facing this issue. Autofill is not working on IOS and also save password pop-up does not appear for IOS.
`Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.3.1 21E258 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] Connected device (4 available)
[✓] HTTP Host Availability

• No issues found!
`

**Comment by maheshmnj** [comment]
@husnainasghar Please try upgrading to the latest stable release of flutter by running `flutter upgrade`.
