### ISSUE TITLE
Audit TESTOWNERS for outdated owners

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#109630]
Prevent the bot from assigning flakes to members who are no longer contributors.
Example:
> /dev/devicelab/bin/tasks/android_choreographer_do_frame_test.dart `@blasten` @flutter/engine

**Comment by jmagman** [comment]
cc @zanderso @keyonghan

**Comment by keyonghan** [comment]
This needs a manual audit. Please suggest new owners of these tests, and I will send a PR to update.
```
/dev/integration_tests/abstract_method_smoke_test @blasten @flutter/android
/dev/integration_tests/android_embedding_v2_smoke_test @blasten @flutter/android
/dev/integration_tests/release_smoke_test @blasten @flutter/android
/dev/devicelab/bin/tasks/android_choreographer_do_frame_test.dart @blasten @flutter/engine
/dev/devicelab/bin/tasks/android_lifecycles_test.dart @blasten @flutter/engine
/dev/devicelab/bin/tasks/gradle_java8_compile_test.dart @blasten @flutter/tool
```

**Comment by jmagman** [comment]
@zanderso who is the best person to take over the android tests?

**Comment by zanderso** [comment]
My understanding is that @stuartmorgan is the right person to route these for now.
