### ISSUE TITLE
flutter compiler-precompiler

### ISSUE THREAD

**Issue by JonathanGit** [flutter/flutter#109677]
My flutter project currently wants to support web and windows, but part of the code cannot be compiled on the web, how can I use conditional compilation? Similar to #ifdef #endif

**Comment by maheshmnj** [comment]
@JonathanGit There is no way to conditionally compile see https://github.com/dart-lang/sdk/issues/34262#issuecomment-416129832  and also https://stackoverflow.com/a/64068904/8253662

Closing as this is neither a bug nor a feature request.
