### ISSUE TITLE
Linux font rendering issue in dialogues

### ISSUE THREAD

**Issue by Feichtmeier** [flutter/flutter#109608]
## issue description

The font/text in dialogues is rendered incorrectly or one could say "fuzzy". When the app is rebuild (for example by resizing the window) the next time the text is rendered correctly.

## recording

https://user-images.githubusercontent.com/15329494/184888627-816c0351-49b1-4df2-9b8a-6b67dd4d8f3d.mp4

## minimal code example

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: TextButton(
            onPressed: () => showDialog(
                  context: context,
                  builder: (context) => const AlertDialog(
                    title: Text('Title'),
                    content: Text(
                        'text text  text  text  text  text text  text  text  text  text  text  text'),
                  ),
                ),
            child: const Text('Open Dialog')),
      ),
    );
  }
}
```
### flutter
frederik@karbon:~$ flutter --version
Flutter 3.1.0-0.0.pre.2294 • channel master •
https://github.com/flutter/flutter.git
Framework • revision 370fc483e3 (vor 6 Stunden) • 2022-08-16 08:56:07 +0200
Engine • revision 280e9a7bec
Tools • Dart 2.19.0 (build 2.19.0-100.0.dev) • DevTools 2.16.0

### Hardware
Processor: 12th Gen Intel(R) Core(TM) i7-1260P x16
Memory: 31 Gb
Graphics: Intel Corporation
Disk Capacity: 954 GB

### System
OS: Ubuntu 22.04 (64-bit)
Kernel version: 5.15.0-46-generic
GNOME version: 42.2.0
Windowing System: wayland

**Comment by jpnurmi** [comment]
@jonahwilliams, the issue seems to be caused by https://github.com/flutter/engine/pull/34115 and is likely related to `RasterCache`. The following hack helps to avoid the rendering artifact:

```
diff --git a/flow/raster_cache.h b/flow/raster_cache.h
index f3dbac5b7e..ba91cac388 100644
--- a/flow/raster_cache.h
+++ b/flow/raster_cache.h
@@ -152,9 +152,9 @@ class RasterCache {
   static SkRect GetDeviceBounds(const SkRect& rect, const SkMatrix& ctm) {
     SkRect device_rect;
     ctm.mapRect(&device_rect, rect);
-#ifndef SUPPORT_FRACTIONAL_TRANSLATION
+// #ifndef SUPPORT_FRACTIONAL_TRANSLATION
     device_rect.roundOut(&device_rect);
-#endif
+// #endif
     return device_rect;
   }
```

**Comment by jpnurmi** [comment]
@jonahwilliams Correct in what sense? It's not a fix proposal but It was just a quick test to see which part of https://github.com/flutter/engine/pull/34115 may cause the rendering issue.

**Comment by jonahwilliams** [comment]
Oh I see, I'm sorry I thought that diff was meant to apply to ToT.

**Comment by jonahwilliams** [comment]
I'd be surprised if that dialog entry were in the raster cache, that said we might be using that method elsewhere.

**Comment by jpnurmi** [comment]
> Oh I see, I'm sorry I thought that diff was meant to apply to ToT.

My bad, I forgot to mention the little detail that I had [d30c460362](https://github.com/flutter/engine/commit/d30c46036257c52c9892295e4cfb08fd4d383b86) checked out after bisecting. Interestingly, `RasterCacheUtil::GetDeviceBounds()` does no longer have `SUPPORT_FRACTIONAL_TRANSLATION`.

**Comment by jonahwilliams** [comment]
So I suspect what is happening here, is that if you happen to draw at something like 0,0 or another pixel aligned boundary, and your DPR is a whole number (like 1.0), then the effect of pixel snapping the layers does what you'd expect and pixel aligns your text.

I believe if you draw your text at something that isn't pixel aligned already, you'll still look pixelated. Worse, with the pixel snapping the engine used to do, its not really possible to compute where you would be laid out so that you can pixel align yourself.

An approach to solve this problem could be something like a "smart" canvas that aligns certain drawning operations (like text) to physical pixel boundaries when painted. That would avoid the problems that the layer based pixel snapping caused like instability in animations and unpredicatable layout.

**Comment by jpnurmi** [comment]
Here's a couple of screencasts @Feichtmeier shared earlier where things shift around a bit when being hovered:

https://user-images.githubusercontent.com/140617/184940435-e6c76c01-dbed-4c6e-9dc1-2e95ec335354.mp4

https://user-images.githubusercontent.com/140617/184940390-d456e415-9d3e-43a5-9416-c9e3ff5577d9.mp4

**Comment by jonahwilliams** [comment]
hmm, that looks different

**Comment by maheshmnj** [comment]
Hi @Feichtmeier, thanks for filing the issue. Unfortunately, I am unable to reproduce that issue on the latest stable or the master channel.

  
https://user-images.githubusercontent.com/31410839/185326638-44c2b0d5-aa8e-4cfa-9001-0a77a5328f3a.mp4

Labeling it as a bug since the ubuntu team was able to reproduce it.

<details>
<summary>flutter doctor -v (Linux)</summary>

```
[✓] Flutter (Channel stable, 3.0.5, on Ubuntu 20.04.4 LTS 5.13.0-48-generic, locale en_GB.UTF-8)
    • Flutter version 3.0.5 at /home/mahesh/Development/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (5 days ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /home/mahesh/Android/Sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at:
      /home/mahesh/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/212.5712.43.2112.8609683/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 2021.2)
    • Android Studio at /home/mahesh/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/212.5712.43.2112.8609683
    • Flutter plugin version 67.1.2
    • Dart plugin version 212.5744
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.1)
    • IntelliJ at /home/mahesh/.local/share/JetBrains/Toolbox/apps/IDEA-U/ch-0/221.5921.22
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.68.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.44.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 20.04.4 LTS 5.13.0-48-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 102.0.5005.115

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
```
[✓] Flutter (Channel master, 3.1.0-0.0.pre.2346, on Ubuntu 20.04.4 LTS 5.15.0-41-generic, locale en_GB.UTF-8)
    • Flutter version 3.1.0-0.0.pre.2346 on channel master at /home/mahesh/Development/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision adda088bcc (4 hours ago), 2022-08-17 22:59:07 -0400
    • Engine revision a77ead45a8
    • Dart version 2.19.0 (build 2.19.0-108.0.dev)
    • DevTools version 2.16.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /home/mahesh/Android/Sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /home/mahesh/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/212.5712.43.2112.8609683/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 2021.2)
    • Android Studio at /home/mahesh/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/212.5712.43.2112.8609683
    • Flutter plugin version 67.1.2
    • Dart plugin version 212.5744
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.1)
    • IntelliJ at /home/mahesh/.local/share/JetBrains/Toolbox/apps/IDEA-U/ch-0/221.5921.22
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.69.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.46.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 20.04.4 LTS 5.15.0-41-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 103.0.5060.134

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by jpnurmi** [comment]
@maheshmnj Is it a VM?

I haven't been able to reproduce the issue in a VM but the issue does easily reproduce on two different laptops with native Ubuntu 22.04 and 22.10 installations. One of the laptops has a high DPI screen and the issue was at first only visible on an external display with 100% scale but not on the built-in display with 200% scale. Setting the built-in display scale to 100% to get DPR=1 made the issue visible on that display as well.

https://user-images.githubusercontent.com/140617/185346430-858105f1-42ba-4556-89f1-69a43c41aa33.mp4

<details><summary>main.dart</summary>
```dart
import 'package:flutter/material.dart';

void main() => runApp(const MaterialApp(home: MyHomePage()));

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addPostFrameCallback((_) => _showTestDialog());
  }

  Future<void> _showTestDialog() {
    return showDialog(
      context: context,
      builder: (context) => const AlertDialog(
        content: Text('Text', style: TextStyle(fontSize: 48)),
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: TextButton(
          onPressed: _showTestDialog,
          child: const Text('Open Dialog'),
        ),
      ),
    );
  }
}
```
</details>

**Comment by maheshmnj** [comment]
> @maheshmnj Is it a VM?

No, Ubuntu is installed on a physical machine. Could be an issue with device resolution, I will see if changing resolution makes a difference.

**Comment by jpnurmi** [comment]
Toggling overlay guidelines or baselines at runtime forces the content to get re-rendered correctly.

Set `debugPaintBaselinesEnabled = false` on app start-up and toggle _Show baselines_ on from DevTools:
| Start-up | Toggle |
|---|---|
| ![Screenshot from 2022-08-19 09-29-21](https://user-images.githubusercontent.com/140617/185567204-9518e0c3-d454-4c98-9619-fdd4b3540d4f.png) | ![Screenshot from 2022-08-19 09-29-31](https://user-images.githubusercontent.com/140617/185567222-cc33002d-b6ab-42c8-8fc4-f1e68f30fab5.png) |

Set `debugPaintBaselinesEnabled = true` on app start-up and toggle _Show baselines_ off from DevTools:
| Start-up | Toggle |
|---|---|
| ![Screenshot from 2022-08-19 09-25-04](https://user-images.githubusercontent.com/140617/185566714-4f8dff65-522d-4f64-9a20-8000050172d7.png) | ![Screenshot from 2022-08-19 09-25-15](https://user-images.githubusercontent.com/140617/185566739-4456d964-9ad5-4a60-8f71-a537ba69673a.png) |

**Comment by bleroux** [comment]
FYI, https://github.com/flutter/flutter/issues/107733 might be a duplicate.

**Comment by jpnurmi** [comment]
@jonahwilliams What about something like this? Before, `RasterCacheUtil::GetDeviceBounds()` would round out when fractional translation was disabled. That logic has been now removed which is presumably fine for all other uses of `RasterCacheUtil::GetDeviceBounds()`, but `RasterCache` probably should still round out so that an integer-sized texture covers full pixels on all edges, right?

```diff
diff --git a/flow/raster_cache.cc b/flow/raster_cache.cc
index 8a4e46d58d..69d2b62f15 100644
--- a/flow/raster_cache.cc
+++ b/flow/raster_cache.cc
@@ -34,6 +34,7 @@ void RasterCacheResult::draw(SkCanvas& canvas, const SkPaint* paint) const {
 
   SkRect bounds =
       RasterCacheUtil::GetDeviceBounds(logical_rect_, canvas.getTotalMatrix());
+  bounds.roundOut(&bounds);
 #ifndef NDEBUG
   // The image dimensions should always be larger than the device bounds and
   // smaller than the device bounds plus one pixel, at the same time, we must
@@ -68,6 +69,7 @@ std::unique_ptr<RasterCacheResult> RasterCache::Rasterize(
   SkRect dest_rect =
       RasterCacheUtil::GetDeviceBounds(context.logical_rect, context.matrix);
   // we always round out here so that the texture is integer sized.
+  dest_rect.roundOut(&dest_rect);
   int width = SkScalarCeilToInt(dest_rect.width());
   int height = SkScalarCeilToInt(dest_rect.height());
 
```

For example, for bounds like `[-52,011993,-19,500000, 930,687988x477,000000]` (XYWH), the rounded-up size is `931x477` but it needs the size rounded-out to `932x478` to cover all pixels.

**Comment by jpnurmi** [comment]
I pushed a fix proposal: https://github.com/flutter/engine/pull/35538

**Comment by Feichtmeier** [comment]
This is issue is not present in Flutter 3.13+, I am pretty sure in saying it is fixed :)
