### ISSUE TITLE
Flutter view is shown for a brief time before showing Android platform view

### ISSUE THREAD

**Issue by orestesgaolin** [flutter/flutter#109692]
## Steps to Reproduce

1. Run [this example application](https://github.com/orestesgaolin/spren-vision-ios/blob/reproduce-ghosting-issue/flutter/example/lib/main.dart) on Flutter beta 3.3.0-0.3.pre; it is using hybrid composition; I run this on Android 12, Samsung S21
2. Navigate to the measurement screen
3. Go back
4. Navigate again
5. Observe ghosting of the Flutter view, it repeats on every subsequent opening

**Expected results:** 

Subsequent openings should be exactly the same as the first one - no ghosting

**Actual results:** 

Please see video for reference

https://user-images.githubusercontent.com/16854239/185186553-e23b0e2f-2b9b-4189-8c88-1c7a76091c6d.mp4

<details>
  <summary>Logs</summary>

[download log.log](https://github.com/flutter/flutter/files/9364414/log.log)

```
[✓] Flutter (Channel beta, 3.3.0-0.3.pre, on macOS 12.4 21F79 darwin-arm, locale pl-PL)
    • Flutter version 3.3.0-0.3.pre on channel beta at /Users/dominik/fvm/versions/beta
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 8c1149878b (7 days ago), 2022-08-10 12:15:36 -0500
    • Engine revision f16e757d5d
    • Dart version 2.18.0 (build 2.18.0-271.4.beta)
    • DevTools version 2.15.0

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/dominik/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F100
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.70.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.46.0

[✓] Connected device (4 available)
    • SM G991B (mobile)       • R5CR617G51T               • android-arm64  • Android 12 (API 31)
    • iPhone 12 mini (mobile) • 00008101-0001510C3CF0001E • ios            • iOS 15.6 19G71
    • macOS (desktop)         • macos                     • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)            • chrome                    • web-javascript • Google Chrome 104.0.5112.79

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```

</details>

Related issue: #103630 #106543

**Comment by orestesgaolin** [comment]
Just to compare here's the example on `master`, where the ghosting issue is not present, but there seems to be some blinking, not sure if this is related to platform views or the spren SDK

```
[✓] Flutter (Channel master, 3.1.0-0.0.pre.2296, on macOS 12.4 21F79 darwin-arm, locale pl-PL)
    • Flutter version 3.1.0-0.0.pre.2296 on channel master at /Users/dominik/fvm/versions/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f4a64ef03d (29 hours ago), 2022-08-16 13:39:05 +0300
    • Engine revision 8a1ab4692a
    • Dart version 2.19.0 (build 2.19.0-100.0.dev)
    • DevTools version 2.16.0
```

https://user-images.githubusercontent.com/16854239/185188264-0a854a9b-f9d7-40c4-ae5f-352c766fa1d6.mp4

**Comment by stuartmorgan** [comment]
Does this work in ab23233fa8212b2813d92191e520d3cc88ffd362 and fail in b79c21684545c93250cb37575b57638361ef4794? If so, this was fixed by https://github.com/flutter/flutter/pull/109405

**Comment by exaby73** [comment]
Hello @orestesgaolin. Thank you for filing this issue. If you are still experiencing this issue in https://github.com/flutter/flutter/commit/ab23233fa8212b2813d92191e520d3cc88ffd362, could you also produce a sample without any third party libraries?

**Comment by stuartmorgan** [comment]
@exaby73 This is about behavioral differences in the plugin system affecting existing plugins, so it doesn't need a repro without third party libraries.

**Comment by exaby73** [comment]
@stuartmorgan Okay thanks for the insight :)

**Comment by orestesgaolin** [comment]
Hi folks, just to clarify - would you like me to prepare reproducible example with no 3rd party?

**Comment by exaby73** [comment]
@orestesgaolin I guess not. Though could you confirm if it works in https://github.com/flutter/flutter/commit/ab23233fa8212b2813d92191e520d3cc88ffd362 and fails in https://github.com/flutter/flutter/commit/b79c21684545c93250cb37575b57638361ef4794 or not?
