### ISSUE TITLE
MissingPluginException on url launcher package

### ISSUE THREAD

**Issue by PixelToast** [flutter/flutter#10967]
## Steps to Reproduce

Added url launcher package to my project, did full restart of app, called `canLaunch("url")` and I get a `MissingPluginException(No implementation found for method canLaunch on channel plugins.flutter.io/url_launcher)`

I've restarted IntelliJ, the Emulator, and my computer with no luck.
Same thing happens on a physical device.

My `android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java` contains `UrlLauncherPlugin.registerWith(registry.registrarFor("io.flutter.plugins.url_launcher.UrlLauncherPlugin"));`

My `android/app/src/main/java/com/yourcompany/vexdb/MainActivity.java` contains `pluginRegistry.registerAll(this);`

## Logs

`flutter run-v` logs: https://gist.githubusercontent.com/PixelToast/ef5a38dfa3a777a3e42bef5fd8255d9d/raw/1090a387b65d25343c516eccaca64ea613d89451/gistfile1.txt

pubspec.yaml: https://gist.githubusercontent.com/PixelToast/22351d0be73db2f40258a96939c245a9/raw/662288c2b8d04548fc2cd07677fb0803481ef3bc/gistfile1.txt

## Flutter Doctor

```
$ flutter doctor
[✓] Flutter (on Linux, locale en_US.UTF-8, channel master)
    • Flutter at /home/pixel/flutter
    • Framework revision f946171817 (4 hours ago), 2017-06-25 21:17:39 -0700
    • Engine revision 8a2d337446
    • Tools Dart version 1.24.0

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at /home/pixel/Android/Sdk
    • Platform android-25, build-tools 25.0.3
    • Java binary at: /home/pixel/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] Android Studio (version 2.3)
    • Android Studio at /home/pixel/android-studio
    • Gradle version 3.2
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.1)
    • Flutter plugin version 14.0
    • Dart plugin version 171.4424

[✓] Connected devices
    • Android SDK built for x86 64 • emulator-5554 • android-x64 • Android 6.0 (API 23) (emulator)
```

**Comment by mravn-google** [comment]
I don't know what `pluginRegistry.registerAll(this)` refers to? Your `MainActivity.java` file should contain the call `GeneratedPluginRegistrant.registerWith(this)` in `onCreate`, as in:
```java
  @Override
  protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    GeneratedPluginRegistrant.registerWith(this);
  }
```
For what it's worth, I just tried to include `url_launcher` in a newly created Flutter project based on the master channel. Launching URLs on Android works nicely.

**Comment by mravn-google** [comment]
Ah, now I see. The `PluginRegistry.java` file with the `registerAll` method is an old class that is no longer generated or updated by Flutter tooling. You should replace you call of `PluginRegistry.registerAll` with a call to `GeneratedPluginRegistrant.registerWith` as shown above.

The change was made on May 9th and is documented [here](https://groups.google.com/forum/#!topic/flutter-dev/zba1Ynf2OKM).

**Comment by PixelToast** [comment]
To anyone else having this issue TL;DR
If you modified your MainActivity apply the patch shown above ^^
```
rm android/app/src/main/java/com/yourcompany/appname/MainActivity.java
flutter create .
```
Works perfectly, I am now opening URLs :smiley:

**Comment by boldijar** [comment]
@PixelToast how to fix the issue on iOS?

**Comment by wilburt** [comment]
If you're still experiencing this issue, update Android Studio And Flutter plugin. This fixed it for me

**Comment by Winghin2517** [comment]
I also have the same issue just now. I managed to resolve it by clicking on the red square button in the tool bar and restart my app by clicking on the green triangle button. I'm using Android Studio.

**Comment by rasyidcode** [comment]
For those who still have this issue, just upgrade your flutter and you are good to go.

**Comment by tiagohm** [comment]
Thanks @Winghin2517 :+1:

**Comment by komputerboy** [comment]
For me..
I need to clean/rebuild again my flutter project
Tool > Flutter > Flutter Clean

**Comment by anybao** [comment]
For me, I am using VSCode and Terminal.

I press d to detach the device and run "flutter run" again.

It worked!

**Comment by FrancisDeh** [comment]
Flutter run after detaching the device worked on my end.

**Comment by urmilshroff** [comment]
I guess hot reload/restart wouldn't work for this, since it requires native Android code (in Java).

All you have to do is stop the app entirely and run it again.

**Comment by maskas** [comment]
Android studio and emulator restart fixed the issue for me.

**Comment by haroonkhan9426** [comment]
Actually you have to restart your app as the plugin added need to be compiled and added into the project.
So, just restart your app and it'll start working perfectly.

**Comment by rabihmb** [comment]
I'm having the same issue, I've restarted the app and the problem gone away.

**Comment by monkeyaccount** [comment]
啥时候修复。。。。

**Comment by vashisth00** [comment]
Mine was different had to reinstall the app

**Comment by PixelToast** [comment]
The original issue has been solved (and is quite old), If you are experiencing a similar error you may want to follow more up to date issue: #62006 #63577
