### ISSUE TITLE
The funcion LoadDartDeferredLibraryError & UpdateAssetResolverByType should run in UI thread

### ISSUE THREAD

**Issue by guoguo338** [flutter/flutter#109762]
As below code snippet shows， the two functions should be run in UI thread but not.

https://github.com/flutter/engine/blob/main/shell/common/shell.cc#L1371-L1383

**Comment by maheshmnj** [comment]
HI @guoguo338, Thanks for filing the issue. Do you have any reasoning for your claim? or What problem would it solve?

> the two functions should be run in UI thread

**Comment by dnfield** [comment]
This is fixed. There's good enough reason to do it from an API consistency perspective, although it'd be nice if @guoguo338 can share any details about how this ever got run on a non-UI thread.
