### ISSUE TITLE
missed_frame_build_budget_count is misleading on high frame rate devices

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#109745]
https://github.com/flutter/flutter/blob/f852c46c877bc321c1705403cfb2b94e5976de3f/packages/flutter_driver/lib/src/driver/timeline_summary.dart#L25

We should either query the device frame rate or remove this field in place of percentiles

**Comment by Hixie** [comment]
We can't do either reasonably due to the amount of code that uses these APIs. Instead I've documented the problem.
