### ISSUE TITLE
Android NDK 24+ does not support API 16-18

### ISSUE THREAD

**Issue by GaryQian** [flutter/flutter#109709]
From https://github.com/android/ndk/wiki/Changelog-r24

`Jelly Bean (APIs 16, 17, and 18) is no longer supported. The minimum OS supported by the NDK is KitKat (API level 19).`

As long as flutter continues to support these older API versions, we can no longer upgrade our NDK version beyond 23.

**Comment by GaryQian** [comment]
@Hixie This may become a forcing function that may require us to eventually drop APIs 16, 17, 18 as Android begins to sunset support for old APIs. The choice will eventually be: Remain on legacy dependencies or upgrade the min sdk version to 19.

**Comment by Hixie** [comment]
Yeah this seems like the final straw.

@khyati82 This is a good candidate to shepherd through a new process for determining support policy.

@timsneath We should begin messaging about how we're going to drop Android Jelly Bean support in a coming release.

**Comment by timsneath** [comment]
Version distribution per Android Studio: 
![image](https://user-images.githubusercontent.com/2319867/188756113-d6e4d075-4ff7-4101-9e2e-7a4184322b24.png)

This feels reasonable to me. Ideally we'd ship one more stable version with older versions formally deprecated, unless there's a compelling reason to do this earlier. Agree we should message this to flutter-announce@ when we have a timeline.

**Comment by khyati82** [comment]
@Hixie - Ack. I am on it

**Comment by Hixie** [comment]
@timsneath FWIW I don't think that graph makes it seem reasonable (0.3% of Android users is entire countries' worth of people). It's the fact that we literally cannot support Jellybean with the latest NDK that is IMHO what drives this.

**Comment by GaryQian** [comment]
For context, we currently use NDK 22. NDK 24 drops support for 16-18, and NDK 25 is the latest version. This puts us 3 versions behind as of now at roughly 1 version a year. Upgrading to 23 should be straightforwards though.

**Comment by camsim99** [comment]
When updating related documentation, we will need to fix https://github.com/flutter/website/issues/8531, as well.

**Comment by gmackall** [comment]
Yes, this should have been closed when https://github.com/flutter/flutter/issues/82000 was closed. Closing now!
