### ISSUE TITLE
[Impeller] ShaderMaskLayer shaders show up as unknown filter type.

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#109753]
Today ShaderMaskLayers are constructed with an SkShader.

https://github.com/flutter/engine/blob/main/lib/ui/compositing/scene_builder.cc#L191-L193

According to https://github.com/flutter/flutter/issues/103111 , we don't have enough information to figure out how to get the correct gradient type from an SkShader. We may need to De-skia-fy the ShaderMaskLayer to support this API.

**Comment by zanderso** [comment]
cc @flar

**Comment by jonahwilliams** [comment]
This was done with https://github.com/flutter/engine/pull/35622
