### ISSUE TITLE
gradlew/gradlew.bat should not be gitignored according to official doc

### ISSUE THREAD

**Issue by fzyzcjy** [flutter/flutter#109749]
## Steps to Reproduce

According to https://docs.gradle.org/current/userguide/gradle_wrapper.html

> To make the Wrapper files available to other developers and execution environments you’ll need to check them into version control. All Wrapper files including the JAR file are very small in size. Adding the JAR file to version control is expected. 

So the gitignore seems to need some modification.

1. Execute `flutter run` on the code sample 
2. ... 
3. ... 

**Expected results:** 
n/a

**Actual results:** 
n/a

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
latest version, no error
```

</details>

**Comment by maheshmnj** [comment]
Hi @fzyzcjy, Thanks for filing the issue. Is this still valid considering that the current behavior is intentional as per this response https://github.com/flutter/flutter/pull/109750#issuecomment-1218966258
