### ISSUE TITLE
【WEB】Web Release NoSuchMethodError : method not fount:'S'(a.S is not a function)

### ISSUE THREAD

**Issue by 15563988825** [flutter/flutter#109751]
Web relase report NoSuchMethodError，but it`s works well in debug mode.

![image](https://user-images.githubusercontent.com/4360198/185276344-0d36c955-f581-4e45-9f3d-7e6c396ded8a.png)

```
NoSuchMethodError: method not found: 'S' (a.S is not a function)
main.dart.js:35203     at aIK.as2 (http://--url--:8092/main.dart.js:106825:56)
main.dart.js:35203     at aIK.as_ (http://*****--url--***:8092/main.dart.js:106816:10)
main.dart.js:35203     at aIK.af8 (http://*****--url--***:8092/main.dart.js:106752:14)
main.dart.js:35203     at Object.b1f (http://**--url--******:8092/main.dart.js:27819:3)
main.dart.js:35203     at a3n.a1u (http://****--url--*****:8092/main.dart.js:107774:29)
main.dart.js:35203     at a3n.wg (http://*****--url--***:8092/main.dart.js:107748:37)
main.dart.js:35203     at aBI.$3 (http://****--url--*****:8092/main.dart.js:108552:103)
main.dart.js:35203     at rn.aIV (http://*****--url--****:8092/main.dart.js:108420:7)
main.dart.js:35203     at a2J.at0 (http://****--url--*****:8092/main.dart.js:108478:8)
main.dart.js:35203     at a2J.dE (http://*****--url--****:8092/main.dart.js:108502:22)
```

![image](https://user-images.githubusercontent.com/4360198/185276386-ab70c7a5-de50-4783-a54f-8a9001a79baa.png)

```
C:\>flutter doctor
Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, 3.1.0-0.0.pre.2318, on Microsoft Windows [版本 10.0.22000.856], locale zh-CN)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Professional 2019 16.11.5)
[√] Android Studio (version 2020.3)
[√] Android Studio (version 2021.2)
[√] IntelliJ IDEA Ultimate Edition (version 2021.1)
[√] Connected device (4 available)
[√] HTTP Host Availability

• No issues found!

```

**Comment by 15563988825** [comment]
flutter build web --profile --source-maps

![6c971fe2851c3547aa4bc4f6b96a949](https://user-images.githubusercontent.com/4360198/185283094-2ece7bd9-9cd4-41ee-92ec-adaef8872734.jpg)

**Comment by darshankawar** [comment]
@15563988825 
Can you provide minimal complete reproducible code sample without any third party plugin code along with steps to replicate that shows the error you are reporting ?

**Comment by 15563988825** [comment]
Sorry i cannot.

**Comment by darshankawar** [comment]
@15563988825 
You cannot replicate with minimal reproducible code sample or cannot provide it ?

**Comment by 15563988825** [comment]
It is works well while running directly in android stdio,but report above error after 'flutter build web' and published to server.

**Comment by darshankawar** [comment]
@15563988825 
We would require a minimal reproducible code sample along with steps to replicate in order to make this issue actionable.

**Comment by Kristijan505** [comment]
Hi,

I had the same issue when building the application from the master channel.

The solution is to build it from the stable channel.

The issue is not related to flutter but to the pdf package.

Related issue: https://github.com/DavBfr/dart_pdf/issues/1144

Hope this will help someone.

**Comment by 15563988825** [comment]
>Thanks，It`s useful
