### ISSUE TITLE
[Impeller] DrawPath and stroke rendering doesn't support hairlines.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#109726]
There is no floor on the size of a stroke in Impeller and a width of 0 is outright rejected by the rendering code when it should result in a hairline. We should implement a floor in the size of stroke sizes and stop rejecting 0 in favor of a minimum value (computed in device space).

**Comment by flar** [comment]
The basic problem was fixed in https://github.com/flutter/engine/pull/35576 but a more thorough solution is needed.

Since the "severe: rendering" part of this issue is fixed I'll close this issue as fixed and open a new issue to remind us to fix the remaining corner cases.
