### ISSUE TITLE
Exception: Gradle task assembleDebug failed with exit code 1

### ISSUE THREAD

**Issue by ARTEM10101010** [flutter/flutter#109759]
![image](https://user-images.githubusercontent.com/111486137/185308672-f44bc78b-1a25-472f-9db7-42e8b40bc079.png)
![image](https://user-images.githubusercontent.com/111486137/185308736-02274969-af5d-41eb-8dc8-49c84aece178.png)

**Comment by ARTEM10101010** [comment]
i need help)

**Comment by darshankawar** [comment]
@ARTEM10101010 
Please don't post screenshots of the error. Provide error log in properly formatted text format.
Looking at the error: `Exception in thread "main" java.net.ConnectException: Connection time out:`, it seems to be related to internet connection or you are probably behind proxy / firewall that is prohibiting to compile.
Please ask this question on support channels like StackOverflow.
Closing from here.
