### ISSUE TITLE
Dart to Engine roll failing

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#109778]
Starting with the roll here https://github.com/flutter/engine/pull/35479

cc @a-siva

**Comment by zanderso** [comment]
Framework smoke tests are not completing:
https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20Framework%20Smoke%20Tests/16972/overview
```
07:02 +8554 ~66: /b/s/w/ir/cache/flutter/packages/flutter/test/material/date_range_picker_test.dart: Can switch from calendar to input entry mode - did not complete [E]
```

**Comment by aam** [comment]
potential root cause was reverted in https://dart.googlesource.com/sdk/+/9299aa216ead9e594ac374ae7de7595e4bcdc8c7

**Comment by zanderso** [comment]
The roll is successful again. Thanks @aam!
