### ISSUE TITLE
`flutter create` should suggest replacing "-" with "_" if doing so would yield a valid Dart package name

### ISSUE THREAD

**Issue by bryanoltman** [flutter/flutter#109775]
## Use case

I often try to use `flutter create` to spin up a quick example. The number of times I use `-` instead of `_` is astounding, and the error text doesn't make it especially clear that this is why my package name is invalid (`"my-flutter-exampe" is not a valid Dart package name.`). 

## Proposal

It would be super helpful if the error message called this out, as I imagine 1) a lot of people make this mistake and 2) it's not immediately obvious to them that the `-` vs `_` distinction is the cause of the problem. The tool could also suggest a valid package name if swapping the separator character with `_` would yield a valid package name.

**Comment by maheshmnj** [comment]
Hi @bryanoltman, Thanks for filing the issue. This sounds like a great proposal.

**Comment by Jasguerrero** [comment]
The error message also prints out `See https://dart.dev/tools/pub/pubspec#name for more information.` which I think it's helpful

**Comment by AmanNegi** [comment]
Hey there can I help with this? In the case of the `-` or any other special character we can just replace it with `_` and suggest the name. 

Let's say the user enters: `flutter create todo-app#1`

We can suggest this: 

`The project name contains special characters which can not be used to create a project! Note that underscore( _ ) is the only valid special character allowed in a project name.`

`Try Using: flutter create todo_app_1`

**Comment by andrewkolos** [comment]
> Hey there can I help with this? In the case of the `-` or any other special character we can just replace it with `_` and suggest the name.
> 
> Let's say the user enters: `flutter create todo-app#1`
> 
> We can suggest this:
> 
> `The project name contains special characters which can not be used to create a project! Note that underscore( _ ) is the only valid special character allowed in a project name.`
> 
> `Try Using: flutter create todo_app_1`

Anyone is free to open a PR that closes this issue. Discussion on the details of implementation or user messaging can happen there.

For anyone interested in working on this issue, the relevant code is _probably_ in [create_base.dart](https://github.com/flutter/flutter/blob/9c7a9e779f0bc89fe43e7c9de692c88b881ef36e/packages/flutter_tools/lib/src/commands/create_base.dart) (contains validation code for `CreateCommand`) and [create_test.dart](https://github.com/flutter/flutter/blob/9c7a9e779f0bc89fe43e7c9de692c88b881ef36e/packages/flutter_tools/test/commands.shard/permeable/create_test.dart).
