### ISSUE TITLE
Confusing code in codelab

### ISSUE THREAD

**Issue by wmleler** [flutter/flutter#10974]
Not a major bug, but can be confusing.

## Steps to Reproduce
Open https://codelabs.developers.google.com/codelabs/flutter/#4
Scroll down until you see two code listings. The first one starts with the comment:
`// Modify the ChatScreen class definition to extend StatefulWidget.`
The second one starts with the comment:
`// Add the ChatScreenState class definition in main.dart.`

The confusing part is that, other than two comments, these code listings are exactly the same.

**Comment by LarkAscending** [comment]
This duplicate snippet is a throwback to a more complex version of that step. When we simplified this step late in the game, the snippets got updated and were correct, but the second one was extraneous.

Fixed, by removing the second snippet:
https://codelabs.developers.google.com/codelabs/flutter/#4
