### ISSUE TITLE
Introduce bitset to manage bool flags in mock_layer unit test.

### ISSUE THREAD

**Issue by guoguo338** [flutter/flutter#109768]
As the title said, there are some bool flags in mock_layer class which needs to be tidied up. Maybe bitset is needed. 
![image](https://user-images.githubusercontent.com/5646684/185356172-3bcb0cec-1335-44b7-92bd-22c2d3a260c5.png)

**Comment by danagbemava-nc** [comment]
Closing this since the linked PR has been merged.
