### ISSUE TITLE
[google_sign_in] Some Android clients receive 403: disallowed_useragent when signing in on mobile device

### ISSUE THREAD

**Issue by dzsonni** [flutter/flutter#109767]
## Steps to Reproduce
1. Sign in to app using google on a device 

This happens on some of the market user devices. I can't reproduce it on my own device. It seems instead of the account picker from the device it opens a webview for sign in.

[√] Flutter (Channel stable, 3.0.5, on Microsoft Windows [Version 10.0.22000.917], locale en-US)
    • Flutter version 3.0.5 at D:\Development\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (5 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc2)
    • Android SDK at D:\Development\AndroidSDK
    • Platform android-33, build-tools 33.0.0-rc2
    • Java binary at: D:\Development\AndroidStudioBumble2\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2020.3)
    • Android Studio at D:\Development\AndroidStudio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] Android Studio (version 2021.2)
    • Android Studio at D:\Development\AndroidStudioBumble2
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22000.917]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 104.0.5112.81
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 104.0.1293.54

[√] HTTP Host Availability
    • All required HTTP hosts are available
![photo_2022-08-18_11-41-36](https://user-images.githubusercontent.com/6988242/185351423-9ff41e64-9da3-4fcf-b38f-c84cf73630f7.jpg)
![photo_2022-08-18_11-41-40](https://user-images.githubusercontent.com/6988242/185351431-df901901-799e-4389-b294-05da6037db5b.jpg)
![photo_2022-08-18_11-41-31](https://user-images.githubusercontent.com/6988242/185351437-4dd48910-89d6-4f71-ab32-67f53c00d801.jpg)
e

**Comment by darshankawar** [comment]
@dzsonni 
This probably has to do with webview as you mentioned, as it opens a webview to sign-in. See this old issue which was fixed for the plugin to add user agent support: https://github.com/flutter/flutter/issues/28256#issuecomment-522177607.
For your reference, the same feature doesn't seem to be bet yet added in community webview plugin: https://github.com/pichillilorenzo/flutter_inappwebview/issues/1112

Based on above, can you try to add latest version of `webview_flutter` and see using it, resolve this error ?

**Comment by dzsonni** [comment]
I am using ` webview_flutter: ^3.0.4` and that seems to be the latest.

**Comment by darshankawar** [comment]
Looking at the error again, `403: disallowed_useragent` usually indicates that user is trying to use an application that fails to make a valid login request to Google and Google rejected it and the most common reason for this rejection is an unauthorized browser agent (the app is using a deprecated browser agent that Google no longer accepts).

Hence this doesn't seem to be specific to Flutter. I suggest you to reach out to Google support for further resolution or search on StackOverflow, for example: https://stackoverflow.com/questions/69370491/you-cant-sign-in-from-this-screen-because-this-app-doesnt-comply-with-googles

Closing from here.
