### ISSUE TITLE
[Impeller] InvertColors is unimplemented.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#109739]

**Comment by jonahwilliams** [comment]
This functionality is used by the framework to invert images. (It may be used for other things at this point, but that was the only goal)

We could deprecate this functionality and replace it with the framework adding a color inverting filter itself.

**Comment by jonahwilliams** [comment]
```
  if (uint_data[kInvertColorIndex]) {
    sk_sp<SkColorFilter> invert_filter = SkColorFilters::Matrix(kInvertColors);
    sk_sp<SkColorFilter> current_filter = paint.refColorFilter();
    if (current_filter) {
      invert_filter = invert_filter->makeComposed(current_filter);
    }
    paint.setColorFilter(invert_filter);
  }
  ```

To implement this in Dart or in the engine we'd need a makeComposed API for ColorFilter.

**Comment by ColdPaleLight** [comment]
I think now we have two ways to implement this feature:
1. Implement DlComposeImage.
If so, I think we should let this PR land.
https://github.com/flutter/engine/pull/35597

2. Direct implementation in Impeller
For example, it can be directly supported in `Paint::WithFilters`.

**Comment by luckysmg** [comment]
I tried to implement this using `Paint::WithFilters`. Any thought about this? 😄😄

https://github.com/flutter/engine/compare/main...luckysmg:invert_colors
