### ISSUE TITLE
Cirrus task failed: Error getting access token for service account, Invalid JWT Signature

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#109722]
https://cirrus-ci.com/task/6717969496539136
Do gcp credentials need to be updated?

cc @godofredoc @keyonghan

**Comment by godofredoc** [comment]
Is this coming from an old PR? if yes you'll need to rebase as the old key expired last week.

**Comment by keyonghan** [comment]
Yeah, it's still using the old credential: https://github.com/flutter/flutter/blob/5c03c0e6cda7f35329a43113159ccec93331cd5f/.cirrus.yml

Credential is updated: https://github.com/flutter/flutter/pull/109461/files

**Comment by jmagman** [comment]
Ugh yes, it's branched off 0a055faf31.  Sorry for the noise.
