### ISSUE TITLE
[web][iOS] Error: Web Service worked not supported (or configured) in Safari browser on Iphone SE

### ISSUE THREAD

**Issue by ljmatan** [flutter/flutter#109771]
Websites work fine on other browsers, in Safari I'm getting errors visible in screenshots attached below. 

Example website:
min-go.hr
tajnikupac.mingor.gov.hr

Device info: 
iPhone SE 2019
iOS 15.4.1

Flutter doctor:
[✓] Flutter (Channel master, 3.1.0-0.0.pre.2191, on macOS 12.0.1 21A559 darwin-arm, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.70.1)
[✓] VS Code (version 1.71.0-insider)
[✓] Connected device (4 available)
[✓] HTTP Host Availability

![Screenshot 2022-08-18 at 13 32 56](https://user-images.githubusercontent.com/73232684/185385279-5d797b8b-de4d-4701-9deb-ad1f32eb7215.png)
![Screenshot 2022-08-18 at 13 32 59](https://user-images.githubusercontent.com/73232684/185385293-6067193a-ceda-4fbd-b205-b4fe5824533a.png)

**Comment by maheshmnj** [comment]
Hi @ljmatan, Thanks for filing the issue. Is this issue only with the deployed app or also when running in debug mode with `-d web-server`?  Can you please share the command that you are running to build the app?

**Comment by ljmatan** [comment]
Hi @maheshmnj 

I've made a mistake when creating the title. The issue appears to happen with both Skia and HTML, in all release modes. 

I can't access the website from above URLs or with below commands via Safari: 

flutter run --profile --verbose -d web-server --web-hostname 0.0.0.0 --web-port 8080
flutter run -dart-define=FLUTTER_WEB_USE_SKIA=false -d web-server --web-hostname 0.0.0.0 --web-port 8080

**Comment by maheshmnj** [comment]
Thanks for the info @ljmatan, Can you please confirm your deployed app contains `flutter_service_worker.js` at the root?  I tried to run a flutter web app in the safari browser using the above commands specified and it seems to load fine.

<img width="742" alt="image" src="https://user-images.githubusercontent.com/31410839/185556471-0af28a8c-3357-4684-b8dd-dd25421b14df.png">

Also is it possible to share a minimal and complete sample project?

Additionally, have you tried creating a new project and see if it works fine?



<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.4 21F79 darwin-arm, locale en-IN)
    • Flutter version 3.0.5 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (5 days ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-32, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.67.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.44.0

[✓] Connected device (3 available)
    • sdk gphone arm64 (mobile) • emulator-5554 • android-arm64  • Android 11 (API 30) (emulator)
    • macOS (desktop)           • macos         • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)              • chrome        • web-javascript • Google Chrome 103.0.5060.114

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by ljmatan** [comment]
From cpanel dashboard I can see this file is present for the "tajnikupac" subdomain, it's also present for the other one. 

As for the reproduction, here's the complete code for "min-go" URL, would that work for you? https://github.com/ljmatan/mingo

![Screenshot 2022-08-19 at 09 17 43](https://user-images.githubusercontent.com/73232684/185565123-a5ace2aa-b173-4e65-b0f4-f97b48510917.png)

**Comment by ljmatan** [comment]
BTW it's all working fine for me on desktop as well, the issue appears on iPhone

**Comment by yjbanov** [comment]
Are you able to connect the iPhone to desktop Safari via USB to see what's going on in the console and in the network tab?

**Comment by ljmatan** [comment]
Yes, you also have a couple of screenshots in the first post, and I've attached one now. Can I help you find anything specific?

![Screenshot 2022-08-24 at 10 50 46](https://user-images.githubusercontent.com/73232684/186374624-602ead76-6096-4904-82ba-60a170f1685c.png)

**Comment by yjbanov** [comment]
cc @ditman

**Comment by ditman** [comment]
@ljmatan from your screenshots, it seems that you're attempting to load a serviceworker over `http` (not `https`)?

Workers **require** a Secure Context ([Documentation](https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts)). TL;DR: the worker will only be available in **`https://...` or `http://localhost`**. Setting the `--web-hostname=192.x.x.x` or `0.0.0.0` in the `flutter run` arguments _definitely_ will trip the browser in a non-secure context.

The error is thrown [here](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/web/file_generators/flutter_js.dart#L77) (because `window.serviceWorker` is probably `null`).

You can verify this is true by running in the JS console of the phone, something like:

* `window.isSecureContext` (should return `false`) or
* `navigator.serviceWorker` (should return `null`)

**Comment by ljmatan** [comment]
@ditman unfortunately, logs are otherwise obfuscated when trying to access https://min-go.hr or https://tajnikupac.mingor.gov.hr

BTW this one definitely is device-specific as websites work normally on iPhone 12, for example. 

Can I help you with anything in order to debug the issue or are you certain this is caused by a 3rd party (anything)? 

![Screenshot 2022-10-20 at 16 37 36](https://user-images.githubusercontent.com/73232684/196979648-57549dbd-fb39-4d5d-aca0-ff26d1550435.png)

**Comment by ditman** [comment]
@ljmatan is the case I described above the problem you're experiencing, or is it something else?
