### ISSUE TITLE
 get shader output without painting on a canvas

### ISSUE THREAD

**Issue by g-apparence** [flutter/flutter#109798]
## Use case
The new ability to create shaders is amazing. 
Sadly it's today impossible to get the result of a shader without drawing it to a canvas. 
I'm trying to implement a fluid shader [Using Jos Stam paper](https://www.dgp.toronto.edu/public_user/stam/reality/Research/pdf/GDC03.pdf).

Today I've used a canvas to make the 20 iterations of computation.
I do every calculations using a customPainter and paint it to a canvas. (That I never render onto the screen). 
```dart
CustomPainter currentPainter = ShaderPainter(shader: shader);
var previousFrame = await canvasToImage(currentPainter);
``` 

```dart
Future<ui.Image> canvasToImage(CustomPainter painter) {
    ui.PictureRecorder recorder = ui.PictureRecorder();
    Canvas canvas = Canvas(recorder);

    painter.paint(canvas, areaSize!);
    return recorder
        .endRecording()
        .toImage(areaSize!.width.floor(), areaSize!.height.floor());
  }
```

Once I have the ui.Image I can do a fragmentShader and pass it to my next shader
```dart
var currentFrameSampler2D = ImageShader(
    previousFrame,
    TileMode.repeated,
    TileMode.repeated,
    Matrix4.identity().storage,
  );
```
After the 20 iterations, I just have to render the last image. 
Problem is that painting the shader result and transforming it to an image is slow. 

## Proposal
Could we imagine a way to get an `ImageShader` directly from a Shader ?
```dart
class Shader {
   /// process the shader computation and return result without drawing 
   Future<ImageShader> process();
}
```

Thank you reading this. 
I'm beginning with shaders and maybe my idea is dumb or not the best.

**Comment by jonahwilliams** [comment]
If you're willing to work closer to tip of tree, we recently added toImageSync on Picture and Scene which does not require scheduling a task on a slow background thread. That said, you still need to wire up and paint each canvas run.

> Could we imagine a way to get an ImageShader directly from a Shader ?

I'm not really sure what this would mean, with that sort of API we'd still need to run the shader on something. While we could automatically wrap the resulting texture in an ImageShader that would seem like it would be less flexible than the current API. 

Perhaps what we'd need is someway to specify that Shader N runs on the output of Shader N -1, and so on - ideally allowing the engine to make more efficient use of textures?

**Comment by jonahwilliams** [comment]
We could also find someway to expose compute shaders, but support for those may not be widely available on mobile devices (and will definitely take a while on our end)

**Comment by g-apparence** [comment]
> If you're willing to work closer to tip of tree, we recently added toImageSync on Picture and Scene which does not require > scheduling a task on a slow background thread.

Oh great 👍

> Perhaps what we'd need is someway to specify that Shader N runs on the output of Shader N -1, and so on - ideally >allowing the engine to make more efficient use of textures?

That would be perfect for this kind of work. 
The ability to make a pipeline of shaders without losing performance (currently my implementation needs 150ms to 300ms for each frame) would open many cool effects.

**Comment by jonahwilliams** [comment]
> The ability to make a pipeline of shaders without losing performance (currently my implementation needs 150ms to 300ms for each frame) would open many cool effects.

I would temper your expectations about performance here

**Comment by zanderso** [comment]
Based on this discussion, closing as compelted.
