### ISSUE TITLE
Skipped XXX frames!  The application may be doing too much work on its main thread.

### ISSUE THREAD

**Issue by Shimingli** [flutter/flutter#109755]
## Steps to Reproduce

1. I have a page with animations on it, I exit and then enter and this page
2. The first time is very smooth, but I have entered too many times, and I will find that the page is abnormally stuck.
3. Then the page cannot be clicked, nor can any operations be performed 
my phone is  Galaxy A30s
![image](https://user-images.githubusercontent.com/20720544/185287171-7ef4b0cf-ce69-4af8-bb5b-53bc0b84681c.png)

**Expected results:** 
be smoother, or be smoother

**Actual results:** 

<details>
<summary>
I/Choreographer(22956): Skipped 66 frames!  The application may be doing too much work on its main thread.
D/ViewRootImpl@57c21[MainActivity](22956): ViewPostIme pointer 1
D/ViewRootImpl@57c21[MainActivity](22956): ViewPostIme pointer 0
D/ViewRootImpl@57c21[MainActivity](22956): ViewPostIme pointer 1
D/ViewRootImpl@57c21[MainActivity](22956): ViewPostIme pointer 0
D/ViewRootImpl@57c21[MainActivity](22956): ViewPostIme pointer 1
D/ViewRootImpl@57c21[MainActivity](22956): ViewPostIme pointer 0
D/ViewRootImpl@57c21[MainActivity](22956): ViewPostIme pointer 1
I/Choreographer(22956): Skipped 72 frames!  The application may be doing too much work on its main thread.</summary>

```
I/Choreographer(22956): Skipped 66 frames!  The application may be doing too much work on its main thread.
D/ViewRootImpl@57c21[MainActivity](22956): ViewPostIme pointer 1
D/ViewRootImpl@57c21[MainActivity](22956): ViewPostIme pointer 0
D/ViewRootImpl@57c21[MainActivity](22956): ViewPostIme pointer 1
D/ViewRootImpl@57c21[MainActivity](22956): ViewPostIme pointer 0
D/ViewRootImpl@57c21[MainActivity](22956): ViewPostIme pointer 1
D/ViewRootImpl@57c21[MainActivity](22956): ViewPostIme pointer 0
D/ViewRootImpl@57c21[MainActivity](22956): ViewPostIme pointer 1
I/Choreographer(22956): Skipped 72 frames!  The application may be doing too much work on its main thread.
```

</details>

<details>
  <summary>Logs</summary>

```

I/Choreographer(22956): Skipped 66 frames!  The application may be doing too much work on its main thread.
D/ViewRootImpl@57c21[MainActivity](22956): ViewPostIme pointer 1
D/ViewRootImpl@57c21[MainActivity](22956): ViewPostIme pointer 0
D/ViewRootImpl@57c21[MainActivity](22956): ViewPostIme pointer 1
D/ViewRootImpl@57c21[MainActivity](22956): ViewPostIme pointer 0
D/ViewRootImpl@57c21[MainActivity](22956): ViewPostIme pointer 1
D/ViewRootImpl@57c21[MainActivity](22956): ViewPostIme pointer 0
D/ViewRootImpl@57c21[MainActivity](22956): ViewPostIme pointer 1
I/Choreographer(22956): Skipped 72 frames!  The application may be doing too much work on its main thread.
```

```
```

```
```

</details>

**Comment by maheshmnj** [comment]
Hi @Shimingli, Thanks for filing the issue. Please share a minimal and complete code sample along with the output 
of `flutter doctor -v`.

Thanks

**Comment by Shimingli** [comment]
@maheshmnj   thank u for reply  
I am so sorry

In the past two days, I was checking the logic of my colleagues. I found that the task was not stopped at a certain step, which caused the task to be repeated many times on this page. When I changed it to the correct logic
, I found that the whole of the page is back to normal,



![image](https://user-images.githubusercontent.com/20720544/185725821-1f269adc-db83-4839-8025-9e77a1b896e5.png)


![image](https://user-images.githubusercontent.com/20720544/185725824-bfe8a1df-45f7-4448-93aa-1a21f2e4b5b0.png)



thank u  ，i love u， 
i think this  issue can close
