### ISSUE TITLE
Flutter Web Page blank white screen

### ISSUE THREAD

**Issue by AnonimTM1** [flutter/flutter#109789]
No project is working in Flutter, I installed the sdk and installed android studio, I am using vs code, my stable version, but I could not solve some kind of error

**Comment by MakufonSkifto** [comment]
Can you open the browsers console and see if there are any errors?

**Comment by maheshmnj** [comment]
Hi @AnonimTM1, Thanks for filing the issue. Please share the output of `flutter doctor -v` and also check if there is any error in the chrome console. Additionally please check if this issue occurs with a newly created project too.

**Comment by AnonimTM1** [comment]
Hi @MakufonSkifto the chrome console error     `unpkg.com/canvaskit-wasm@0.35.0/bin/canvaskit.js:1          Failed to load resource: net::ERR_CONNECTION_RESET`

**Comment by AnonimTM1** [comment]
Hi @maheshmnj the chrome console error `unpkg.com/canvaskit-wasm@0.35.0/bin/canvaskit.js:1 Failed to load resource: net::ERR_CONNECTION_RESET`

the flutter doctor -v command value :
`[√] Flutter (Channel dev, 3.3.0-0.3.pre, on Microsoft Windows [Version 10.0.18362.239], locale tr-TR)
    • Flutter version 3.3.0-0.3.pre on channel dev at C:\src\flutter\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 8c1149878b (9 days ago), 2022-08-10 12:15:36 -0500
    • Engine revision f16e757d5d
    • Dart version 2.18.0 (build 2.18.0-271.4.beta)
    • DevTools version 2.15.0

Checking Android licenses is taking an unexpectedly long time...[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at C:\Users\nomer\AppData\Local\Android\Sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • ANDROID_HOME = C:\Users\nomer\AppData\Local\Android\Sdk
    • ANDROID_SDK_ROOT = C:\Users\nomer\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] VS Code (version 1.70.2)
    • VS Code at C:\Users\nomer\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.46.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.18362.239]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 104.0.5112.81
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 103.0.1264.71

[!] HTTP Host Availability
    X HTTP host "https://cocoapods.org/" is not reachable. Reason: An error occurred while checking the HTTP host: Connection terminated during handshake

! Doctor found issues in 2 categories.`

**Comment by AnonimTM1** [comment]
@maheshmnj Same error in all projects

**Comment by AnonimTM1** [comment]
I switched to the dev channel today, I tried the beta and stable channels in the past, but the same result. i tried again now but same result please help solve this problem!

**Comment by maheshmnj** [comment]
Thanks for the update @AnonimTM1, This error mostly seems related to your internet, The browser was not able to download the entire file hence the white screen.
 
> unpkg.com/canvaskit-wasm@0.35.0/bin/canvaskit.js:1 Failed to load resource: net::ERR_CONNECTION_RESET

Can you check if using a VPN or some other network works?
Additionally please try with a newly created project by running 
```
flutter create hello
cd hello
flutter run -d chrome
```
