### ISSUE TITLE
[CP] Fix Windows 7 crash

### ISSUE THREAD

**Issue by loic-sharma** [flutter/flutter#109742]
### issue_link

https://github.com/flutter/flutter/issues/109412

### Commit Hash

[fbbd8c6](https://github.com/flutter/engine/commit/fbbd8c6bab64982f6fbce27eac0927e47b96771c)

### Target

beta

### pr_link

https://github.com/flutter/engine/pull/35513

### Impacted Users

All Windows 7 users

### Impact Description

A Flutter app built using the beta channel crashes immediately on Windows 7 with the following error:

![image](https://user-images.githubusercontent.com/737941/184231110-46718079-36ec-4664-bf7c-b19c36338914.png)

### Workaround

Kindly ask users to upgrade to Windows 8, 10, or 11.

### Risk

medium

### Test Coverage

yes

### Validation Steps

This fix is covered by unit tests. However, this issue can only be reproduced on Windows 7 machines and none our build agents use Windows 7. 

The fix will need to be validated manually on a Windows 7 machine.

**Comment by loic-sharma** [comment]
FYI I put risk as "medium" as the cherry pick PR will have non-trivial merge conflicts. The resulting cherry pick will be somewhat different than the original changes on the `main` branch.

/cc @itsjustkevin

**Comment by loic-sharma** [comment]
I've prepared the cherry pick here: https://github.com/flutter/engine/compare/flutter-3.2-candidate.5...loic-sharma:flutter-engine:flutter-3.2-candidate.5?expand=1

I will open a pull request for the cherry pick once this issue has been approved.

**Comment by itsjustkevin** [comment]
@cbracken could you take a look at this cherry-pick request?

**Comment by cbracken** [comment]
Just to update here -- lgtm'ed the other day and re-lgtm'ed the patch this morning.

**Comment by loic-sharma** [comment]
Closing this as the cherry pick was merged. @itsjustkevin feel free to re-open this if I'm misunderstanding the process.
