### ISSUE TITLE
Scroll behavior off in iOS for "quick flings"

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#10976]
The following video was recorded by running [the scroll overlay app](https://github.com/flutter/scroll_overlay) on iOS:

[![Click to play video](https://img.youtube.com/vi/62Z3uH9stMc/0.jpg)](https://youtu.be/62Z3uH9stMc)

It shows that Flutter's scroll physics contain too much resistance when the user performs a small but quick fling.

**Comment by tvolkert** [comment]
FYI @xster @cbracken

**Comment by Hixie** [comment]
Related: https://github.com/flutter/flutter/issues/10977 https://github.com/flutter/flutter/issues/10976 https://github.com/flutter/flutter/issues/10972

**Comment by xster** [comment]
It's kinda the same thing as #10977. I'll just merge them.
