### ISSUE TITLE
[tool] Upgrade the example when `flutter pub upgrade` for packages

### ISSUE THREAD

**Issue by AlexV525** [flutter/flutter#109840]
## Use case

https://github.com/flutter/flutter/blob/75ee440329f555cac3d636a24bdc5c16c8ef60ef/packages/flutter_tools/lib/src/commands/packages.dart#L178-L179

When running `flutter pub get` under packages, it'll detect whether the example exists, then run the same thing for it.
As we're developing packages, when we released a new version that packages depend on, then we may tell users to `upgrade` with pub. But those users often stay at the root `pubspec.yaml` of the package, which avoids the example's upgrade, and both authors and users will get lost in communications.

More specifically:
```
-- A ( depends on: [B] )
   |-- example ( depends on: [ A, B(tranparent) ] )
```

## Proposal

We might consider running `flutter pub upgrade` for the example as well, like what `flutter pub get` does.

**Comment by christopherfujino** [comment]
This seems reasonable, however assigning it p3 priority as it is not currently on the team roadmap.

**Comment by AlexV525** [comment]
Just took another look at the main branch, and it seems to be resolved.
https://github.com/flutter/flutter/blob/3e67e1998fa7110be3b8fd3c7071ca95f9afd92b/packages/flutter_tools/lib/src/commands/packages.dart#L314-L319

```console
$ flutter pub upgrade
Resolving dependencies...
  async 2.11.0
  boolean_selector 2.1.1
  characters 1.3.0
  clock 1.1.1
  collection 1.17.2
  fake_async 1.3.1
  flutter 0.0.0 from sdk flutter
  flutter_lints 2.0.2
  flutter_test 0.0.0 from sdk flutter
  lints 2.1.1
  matcher 0.12.16
  material_color_utilities 0.5.0 (0.8.0 available)
  meta 1.9.1
  path 1.8.3
  sky_engine 0.0.99 from sdk flutter
  source_span 1.10.0
  stack_trace 1.11.1
  stream_channel 2.1.2
  string_scanner 1.2.0
  term_glyph 1.2.1
  test_api 0.6.1
  vector_math 2.1.4
  web 0.1.4-beta
No dependencies changed.
1 package has newer versions incompatible with dependency constraints.
Try `flutter pub outdated` for more information.
Resolving dependencies in .\example...
Got dependencies in .\example.
Process finished with exit code 0
```
