### ISSUE TITLE
[iOS] [iPad] Bug in avoid bottom inset in split view mode

### ISSUE THREAD

**Issue by RichardFevrier** [flutter/flutter#109845]
### Actual behavior

https://user-images.githubusercontent.com/5154754/185595926-8b28dff6-e65e-49b2-bb52-c8fc1395547e.mov

You can see on the video above, at the end, the application UI on the left did not react on the keyboard dismissing.

### Expected behavior

https://user-images.githubusercontent.com/5154754/185595983-48aeb404-19d8-4226-9587-e90514ffd579.mov

Here is the behavior fixed in my branch.

### Steps to reproduce

Simply add a ```const TextField()``` in the body's demo app.

### Other info

```
Flutter 3.0.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f1875d570e (5 weeks ago) • 2022-07-13 11:24:16 -0700
Engine • revision e85ea0e79c
Tools • Dart 2.17.6 • DevTools 2.12.2
```

I will create a pull request in a few minutes

**Comment by darshankawar** [comment]
Thanks for the report and the fix. Labeling based on the report.
