### ISSUE TITLE
`impellerc` and `libtessellator` should run natively on Apple Silicon arm machines

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#109892]
The `bin/cache/artifacts/engine/darwin-x64/impellerc` artifact only contains a x64 slice, so runs with Rosetta on an arm64 Mac.  Ship a native arm64 variant to run on Apple Silicon host machines.

Saw this on a bad luci run that was missing Rosetta:
```
stderr: [   +2 ms] ProcessException: Bad CPU type in executable
stderr:              Command: /opt/s/w/ir/x/w/recipe_cleanup/tmpxs3pju7o/flutter sdk/bin/cache/artifacts/engine/darwin-x64/impellerc --sksl --iplr --sl=/opt/s/w/ir/x/t/flutter_module_test.T4OVDk/hello_module/flutter-frameworks/Debug/iphoneos/App.framework/flutter_assets/shaders/ink_sparkle.frag --spirv=/opt/s/w/ir/x/t/flutter_module_test.T4OVDk/hello_module/flutter-frameworks/Debug/iphoneos/App.framework/flutter_assets/shaders/ink_sparkle.frag.spirv --input=/opt/s/w/ir/x/w/recipe_cleanup/tmpxs3pju7o/flutter sdk/packages/flutter/lib/src/material/shaders/ink_sparkle.frag --input-type=frag --include=/opt/s/w/ir/x/w/recipe_cleanup/tmpxs3pju7o/flutter sdk/packages/flutter/lib/src/material/shaders
```
https://github.com/flutter/flutter/issues/60118
Related https://github.com/flutter/flutter/issues/101138

**Comment by chinmaygarde** [comment]
Speculatively adding an Impeller tag, but there shouldn't be any blockers to compiling ImpellerC for arm64. We should don't have host artifact builders in CI for arm64 targets. If thats the case, we can follow up separately.

@jmagman Were you running into issues building ImpellerC on Apple Silicon macs instead? If so, I need to followup on this. I am still waiting on my M1/2 boxes unfortunately :(

**Comment by jmagman** [comment]
> Were you running into issues building ImpellerC on Apple Silicon macs instead?

Yes, I saw this on a misconfigured luci bot that didn't have Rosetta installed in https://github.com/flutter/flutter/pull/109889.  Ideally we'd be able to build and run totally natively, without needing Rosetta https://docs.flutter.dev/get-started/install/macos#system-requirements

**Comment by jmagman** [comment]
Example: https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8805363977658226225/+/u/run_plugin_test_ios/test_stdout

**Comment by jmagman** [comment]
Also `libtessellator`.

**Comment by jmagman** [comment]
Fixed by https://github.com/flutter/flutter/pull/110291
