### ISSUE TITLE
Issue: Trying to debug an embedded web application at subpath

### ISSUE THREAD

**Issue by skyne98** [flutter/flutter#109851]
Hi there, everyone! I hope it's a correct place to file this issue, if not, it's not a problem for me to file it at a correct location.
The issue I have is from a very special use-case, involving embedding Flutter Web into an existing application using iframes and conditionally using a reverse proxy that points to `flutter run` at a non-root path like `/flutter/`.

When trying to debug, on either `master`, `beta` or `stable` debugging with breakpoints never works correctly. Tried using both VSCode and DevTools. It seems like there is an issue with source file name resolution, but I don't have a way to confirm it, except for DevTools throwing an issue with `_stripBasePath(...)`.

When just using a reverse proxy without a sub-path, breakpoints work on `master` and `beta`, but show an error in VSCode on trying to dig into variables and objects.

## Steps to Reproduce
1. Setup an **nginx** reverse proxy, where `/flutter` points to a pre-defined port running `flutter run`
2. Have an embedding web app at `/` in the reverse proxy
3. Try to debug using VSCode

**Expected results:**
Being able to continue developing the application normally, using breakpoints and hot-restart with the embedded (in the iframe) application behaving correctly.

**Actual results:**
1. At first, issue with the application connecting to the debugging system, which requires this workaround (port 42422 is proxy's endpoint, 42420 is `flutter run`) which goes into `index.html`
```dart
if (location.href.includes('42422')) {
  Object.defineProperty(window, "$dwdsDevHandlerPath", {
    value: 'ws://localhost:42420/$dwdsSseHandler',
    writable: false
  }); 
}
```
2. When trying to debug, breakpoints are marked as `unavailable`
3. Have other issues with debug socket disconnecting, restart hanging, breakpoints showing up in wrong locations

<details>
<summary>Code sample</summary>

NGINX configuration
```

#user  nobody;
worker_processes  1;

events {
    worker_connections  1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    keepalive_timeout  65;

    server {
        listen       42422;
        server_name  localhost;

        location /flutter/ {
            proxy_pass http://localhost:42420/flutter/;
            proxy_pass_header Content-Type;
            proxy_redirect   off;
            proxy_set_header Host            $host;
            proxy_set_header X-Real-IP       $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

            # kill cache
            add_header Last-Modified $date_gmt;
            add_header Cache-Control 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0';
            if_modified_since off;
            expires off;
            etag off;
        }

        location / {
            proxy_pass http://localhost:62768/;
            proxy_pass_header Content-Type;
            proxy_redirect   off;
            proxy_set_header Host            $host;
            proxy_set_header X-Real-IP       $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

            # kill cache
            add_header Last-Modified $date_gmt;
            add_header Cache-Control 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0';
            if_modified_since off;
            expires off;
            etag off;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }
    }
}

```

`flutter run` parameters
```json
"args": [
    "--web-port", "42420",
    "--web-launch-url", "http://localhost:42422/mvc/Flutter/Container/step-by-step",
]
```
</details>

<details>
  <summary>Logs</summary>
</details>

**Comment by exaby73** [comment]
Hello @skyne98. Thank you for filing this issue. Unfortunately, the information you provided is not enough for me to try to reproduce this issue. Could you provide the below information:

- A [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). For an issue this complex to reproduce, a repository that contains all the required files to verify the issue is ideal. If possible, could the sample be void of any third party SDKs or libraries? For example, replacing the nginx proxy with a Dart one.
- Detailed reproduction steps. Mainly, what's missing is the "parent" web app. Could you provide, in your code sample, a sample web app with the `iframe` as well?
- Is this issue reproducible in IntelliJ/Android Studio as well?
- Could you also provide the entire log of running `flutter doctor -v` as well as the crash logs, if any?

**Comment by skyne98** [comment]
@exaby73, sure thing, as soon as I have a moment I will make a repo.

Can you give an example of a reverse proxy in Dart I can use?

**Comment by exaby73** [comment]
You can look at how a proxy is implemented in [`webdev_proxy`](https://pub.dev/packages/webdev_proxy) for example :)
