### ISSUE TITLE
[Docs] OutlinedButton and textButton api docs are incorrect/ has duplication.

### ISSUE THREAD

**Issue by yasargil** [flutter/flutter#109834]
There's is an documentation error in Flutter Beta 3.3.0-0.3.pre. disabledForegroundColor is duplicated. It is not clear what the second property would be.

```     
    @Deprecated(
      'Use disabledForegroundColor and disabledForegroundColor instead. '
      'This feature was deprecated after v3.1.0.'
    )
    Color? onSurface,
```

**Comment by maheshmnj** [comment]
Hi @yasargil, Thanks for filing the issue. Can you please point to the documentation that you are referring to?
I checked here and it doesn't seem to specify the duplication.
> https://github.com/flutter/flutter/blob/8c1149878bbb8f062aecfab4d825e5b87bdb4487/packages/flutter/lib/src/material/color_scheme.dart#L698-L701

**Comment by yasargil** [comment]
Sure here
https://github.com/flutter/flutter/blob/7ded3d91daf9478126b902b9508f1aeb9fb91e3a/packages/flutter/lib/src/material/outlined_button.dart#L168

and
https://github.com/flutter/flutter/blob/7ded3d91daf9478126b902b9508f1aeb9fb91e3a/packages/flutter/lib/src/material/text_button.dart#L175

**Comment by maheshmnj** [comment]
Thanks for the link I can repro it on the latest master too

https://github.com/flutter/flutter/blob/75ee440329f555cac3d636a24bdc5c16c8ef60ef/packages/flutter/lib/src/material/text_button.dart#L175
