### ISSUE TITLE
TextField widget can't show mac keyboard

### ISSUE THREAD

**Issue by javalin-zz** [flutter/flutter#109823]
My Flutter app have a problem,textfield widget can't use mac system keyboard,only use iphone simulator。

**Comment by exaby73** [comment]
Hello @javalin-zz. Thank you for filing this issue. Can you provide the information below:

- Output of `flutter doctor -v`
- A video demonstrating the issue
- Does other apps work? For example, try launching Safari and test if the keyboard is working.

**Comment by javalin-zz** [comment]
> Hello @javalin-zz. Thank you for filing this issue. Can you provide the information below:
> 
> * Output of `flutter doctor -v`
<img width="950" alt="截屏2022-08-21 11 27 02" src="https://user-images.githubusercontent.com/7592105/185774083-d65c467f-2ba1-4382-b515-aad9819b603a.png">

> * A video demonstrating the issue
when click command+shift+k change keyboad,system board can't show textfile inside
> * Does other apps work? For example, try launching Safari and test if the keyboard is working.
yes other app work,

**Comment by exaby73** [comment]
@javalin-zz Could you provide the rest of the information as well, please?
