### ISSUE TITLE
Going back in the dartdocs loses your scroll position

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#10984]
This used to be fine. I think it broken when we added scrolling in the left and right columns.

Steps:
1. Go to https://master-docs-flutter-io.firebaseapp.com/flutter/rendering/ContainerRenderObjectMixin-class.html
2. Open "add".
3. Nope, that was the wrong one. Go back.
4. Open "addAll".
5. Nope, that was the wrong one. Go back.
6. Get frustrated that you had to scroll after step 3 and have to scroll again now.

cc @sethladd

**Comment by Sfshaza** [comment]
Still broken.

**Comment by zoechi** [comment]
Is this `d: website - infra` or is this something dartdoc needs to fix?

**Comment by zoechi** [comment]
@Hixie I don't know what to do with dartdoc infra issues. 
Should they be moved to dart-lang/dartdoc?

**Comment by Hixie** [comment]
@zoechi  yeah probably.
cc @jcollins-g

**Comment by jcollins-g** [comment]
@zoechi Yes, move to dart-lang/dartdoc and I will be more likely to see/address them.

**Comment by Hixie** [comment]
Since we have moved the bug I'll close this one. Thanks all!
