### ISSUE TITLE
[go_router] expose `navigatorObservers` on `MaterialApp.router`contructor

### ISSUE THREAD

**Issue by pedromassango** [flutter/flutter#109861]
I have a requirement to listen for navigation changes in the app-level and since I'm using `MaterialApp.router` to initialise the app, I'm not able to provide a `navigatorObservers`.

After some research, I found out that the `navigatorObservers` is set to null and for a good reason: `MaterialApp.router` already allow us to give a `RouterDelegate` that we're supposed to use to handle and/or listen for navigation changes in their methods. The problem arise when using a navigation package such as [AutoRoute](https://pub.dev/packages/auto_route), you lose the ability to provide a custom delegate as the package asks you to use the package's delegate implementation.

There are some ways to workaround this but it adds too much complexity in the code so I think it makes sense for the Framework to provide a way to segregate the place to handle navigation and the place to listen for navigation changes

## Proposal

```dart
   MaterialApp.router(
        title: 'my app',
        debugShowCheckedModeBanner: false,
        theme: getAppTheme(Brightness.light),
        darkTheme: getAppTheme(Brightness.dark),
        navigatorObservers:             -------------------------->>> I need this 
        routerDelegate: _autoRoute.delegate(),  // I'm using autoroute so can't provide a custom delegate here
        routeInformationParser: _autoRoute.defaultRouteParser(),  // I'm using autoroute so can't provide a custom delegate here
        // ... more stuff here
      )
```

**Comment by maheshmnj** [comment]
Hi @pedromassango, Thanks for filing the issue.

You can extend from Navigatorobserver and listen the route changes in the overridden methods as shown in this complete code sample here https://github.com/csells/go_router/blob/main/go_router/example/lib/nav_observer.dart. 

<details>
<summary>code sample</summary>

```dart
 final router = GoRouter(
    observers: [MyNavObserver()],
    routes: [
     ...
   ]
)
...
...

class MyNavObserver extends NavigatorObserver {
  MyNavObserver() {}

  @override
  void didPush(Route<dynamic> route, Route<dynamic>? previousRoute) =>
      print('didPush: ${route.str}, previousRoute= ${previousRoute?.str}');

  @override
  void didPop(Route<dynamic> route, Route<dynamic>? previousRoute) =>
      print('didPop: ${route.str}, previousRoute= ${previousRoute?.str}');

  @override
  void didRemove(Route<dynamic> route, Route<dynamic>? previousRoute) =>
      print('didRemove: ${route.str}, previousRoute= ${previousRoute?.str}');

  @override
  void didReplace({Route<dynamic>? newRoute, Route<dynamic>? oldRoute}) =>
      print('didReplace: new= ${newRoute?.str}, old= ${oldRoute?.str}');

  @override
  void didStartUserGesture(
    Route<dynamic> route,
    Route<dynamic>? previousRoute,
  ) =>
      print('didStartUserGesture: ${route.str}, '
          'previousRoute= ${previousRoute?.str}');

  @override
  void didStopUserGesture() => print('didStopUserGesture');
}

extension on Route<dynamic> {
  String get str => 'route(${settings.name}: ${settings.arguments})';
}


```
</detals>

Would this help achieve your use case?

**Comment by pedromassango** [comment]
> Would this help achieve your use case?

Hi, yes, that works. Thanks!
