### ISSUE TITLE
Reading bar code with sequences of ZEROS in the flutter WEB/DESKTOP application

### ISSUE THREAD

**Issue by GustavoTeng** [flutter/flutter#109877]
## Steps to Reproduce

First of all things you should know is that my team uses mobX to do state management. We developed an application that basically reads products bar codes and process informations with it. Some beep devices are old and uses Windows CE as OS, for this ones we use them with a RDP conection in a Windows Server 2012/Windows 7 and we build a C# WebViewer that runs the flutter web app. The thing it's it's not a device problem neither a C# webviewer problem. We thought that too but if we put the same RDP connection to beep in a notepad or inside a textfield in the webviewer it will beep the complete code always, it never cuts the zero like the in the flutter application. 
We also built a Desktop version to test and it happens the same way that the web one (Only the new beep devices that use ANDROID as OS with the .apk app works fine, but if we use the remote conection as the same way  ). Curiously it only occurs when the barcode has two or more "0"(ZERO) sequence.

So to resume:
- The device using the remote connection it's not the problem it works perfectly out of the flutter application(Using notepad or other app)
- The problem only happens with the barcode that has sequences of two or more ZEROS
- The problem happens randomly
- There is two videos attached that shows the problem
- It's only in the WEB/DESKTOP version of flutter

1. Import mobX to manage state.
2. Put the code sample  in a project to make a screen that reads/shows the barcode reader using the TextField in the WEB version 
2. Use a device that can reads bar code
3. Use a barcode generator to make any barcode that has two or more ZEROS in sequence. For example: 1234567890001
4. Beeps really fast the barcode( Because sometimes it's what happens in the working place that we use the application for )
5. Some times it will read it fine, sometimes it will cut the last 0 of the sequence. Or even worse like read only 7 digits

**Expected results:** 
Everytime the code is beeped it should be complete

**Actual results:** 
Sometimes randomly it "cuts" a ZERO of the bar code if it has two or more sequences of ZEROs

<details>
<summary>Code sample</summary>

```
TextField(
   focusNode: testeBipeController.focusEnderecoProduto,
  controller: testeBipeController.cdBarraController,
  cursorColor: TargetColors.grey[50],
  style: TextStyle(
    color: TargetColors.grey[50],fontSize: TargetTextStyle.fontSize4,),
    decoration: InputDecoration(
    enabledBorder: UnderlineInputBorder(borderSide: BorderSide(color: Colors.lime)),
         labelText:'Informe o código de barras.',
         labelStyle: TextStyle(
         color: TargetColors.grey[50],
         fontSize:TargetTextStyle.fontSize5,
       ),
    ),
onSubmitted: (cdBarras) => this.testeBipeController.confereCdBarraBipado(cdBarras),
)
```

</details>
<details>
  <summary>Logs</summary>

```
   NO EXCEPTIONS IN 'FLUTTER RUN --VERBOSE'
```

```
   NO ERRORS IN ' FLUTTER ANALYZE '
```

```
PS C:\Projetos\Mlog2\mlog_heart2> flutter doctor -v
[√] Flutter (Channel stable, 3.0.2, on Microsoft Windows [versÆo 10.0.19044.1889], locale pt-BR)
    • Flutter version 3.0.2 at C:\tools\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cd41fdd495 (2 months ago), 2022-06-08 09:52:13 -0700
    • Engine revision f15f824b57
    • Dart version 2.17.3
    • DevTools version 2.12.2



[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at C:\Users\User\AppData\Local\Android\sdk      
    • Platform android-32, build-tools 32.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java       
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.



[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe



[√] Visual Studio - develop for Windows (Visual Studio Professional 2022 17.0.5)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Professional
    • Visual Studio Professional 2022 version 17.0.32112.339
    • Windows 10 SDK version 10.0.19041.0



[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)



[√] VS Code (version 1.70.2)
    • VS Code at C:\Users\User\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.44.0



[√] Connected device (4 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 7.1.1 (API 25) (emulator)
    • Windows (desktop)                  • windows       • windows-x64    • Microsoft Windows [versÆo 10.0.19044.1889]
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 104.0.5112.81
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 104.0.1293.54



[√] HTTP Host Availability
    • All required HTTP hosts are available
```

</details>

**Comment by GustavoTeng** [comment]
The videos:

https://user-images.githubusercontent.com/43620053/185701895-69e3e774-c74e-4104-a312-52d7679a80fc.mp4


https://user-images.githubusercontent.com/43620053/185701915-4e5515a3-aa51-4f33-8461-f874dbc27fa1.mp4

**Comment by exaby73** [comment]
Hello @GustavoTeng. I found a similar issue (https://github.com/flutter/flutter/issues/109437). Does this solve your issue?

**Comment by GustavoTeng** [comment]
We did a similar solution to this problem and worked well. I created the issue to see with if had a native solution or understand why it only happens in the WEB/DESKTOP version. Thanks for the help :)

**Comment by exaby73** [comment]
Glad you found a solution to your problem. But this use case seems very specific and doesn't look like a valid use case to be added into the framework. Therefore, I will close this issue. If you disagree, please comment and we can reopen it. Thank you.
