### ISSUE TITLE
BackdropFilter performance degrades after first appearance of platform view

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#109831]
I'm not sure if performance overall degrades, but it is most noticeable with blurs. Before the first time the platform view is displayed, performance is as expected. After the first time it is displayed, performance is worse, and possibly continues to degrade further as time goes on.

/cc @bdero @chinmaygarde @jonahwilliams

**Comment by zanderso** [comment]
Also cc @flar since it looks related to the platform view, which was recently wired up.

**Comment by bdero** [comment]
I'm able to reproduce this. The degraded performance does not scale with sigma, which leads me to believe we're going to find an issue with something else being slow.

**Comment by bdero** [comment]
Took some debug build frame captures:
- Fast frame (~30fps) GPU capture with the full blur is 19.6 ms
- Slow frame (multiple seconds to render a frame) GPU capture is 24.7 ms

**Comment by zanderso** [comment]
The CPU time appears to be going into:
```
flutter::IOSExternalViewEmbedder::PushFilterToVisitedPlatformViews(std::__1::shared_ptr<flutter::DlImageFilter const>)
```

**Comment by zanderso** [comment]
This also appears to repro with the Skia backend. cc @cyanglaz

**Comment by zanderso** [comment]
The revert has landed.

**Comment by cyanglaz** [comment]
The performance issue is due to not clearing visited platform view list. The fix will be landed in https://github.com/flutter/engine/pull/34596.
Since the original PR are reverted, I will re-land https://github.com/flutter/engine/pull/34355 in https://github.com/flutter/engine/pull/34596
