### ISSUE TITLE
[vscode] Intellisense is not working in flutter 3

### ISSUE THREAD

**Issue by mugi-luffy** [flutter/flutter#109881]
since upgrading to flutter 3 intellisense and auto suggest stopped working for me in visual studio code.
Flutter 2.10.5 works as expected.
All version after that, did not work for me.
I already tried the following:
restart my pc, create a new empty project, reinstall flutter, 

## Steps to Reproduce
1. have a running 2.10.5 version
2. flutter upgrade
3. restart editor

## flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.0.5, on Microsoft Windows [Version 10.0.19043.1889], locale de-DE)    
[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.1.3)
[√] Android Studio (version 2021.1)
[√] IntelliJ IDEA Community Edition (version 2020.3)
[√] VS Code (version 1.70.2)
[√] Connected device (3 available)
[√] HTTP Host Availability

![image](https://user-images.githubusercontent.com/23312130/185708813-9f2e13af-db34-4eb4-b41a-3d6943d98a3a.png)

**Comment by maheshmnj** [comment]
Hi @mugi-luffy, thanks for filing the issue, I am unable to reproduce the issue on the latest stable release of flutter.


https://user-images.githubusercontent.com/31410839/185884117-b2db93a9-c068-41bc-a639-3151bba719f8.mp4 

![image](https://user-images.githubusercontent.com/31410839/185884930-0a255fa4-b895-423d-8a62-a3c18e0678fb.png)


Is this issue only in vscode or other IDE's like intellij or Android studio too? Can you check if this issue occurs with newly created flutter projec too?

#### vscode version.  
```
Version: 1.70.2 (user setup)
Commit: e4503b30fc78200f846c62cf8091b76ff5547662
Date: 2022-08-16T05:35:13.448Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 10.0.19044
```

<details>
<summary>flutter doctor -v (windows)</summary>

```
[√] Flutter (Channel stable, 3.0.5, on Microsoft Windows [Version 10.0.19044.1826], locale en-IN)
    • Flutter version 3.0.5 at C:\flutter_sdk\stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (6 days ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\mahesh\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31727.386
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] VS Code (version 1.69.0)
    • VS Code at C:\Users\mahesh\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.44.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19044.1826]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 103.0.5060.114
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 100.0.1185.50

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by mugi-luffy** [comment]
The issue persisted even after creating a new project, but what seemed to fix the problem for me was deleting the workspace and creating a new one and adding my project to it.  I guess the old workspace got corrupted somehow.
Now it is working again as expected. 
thnx for the help :).
