### ISSUE TITLE
Unable To Purchase

### ISSUE THREAD

**Issue by hpsolver** [flutter/flutter#109856]
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. Click on restore button it returns list of all last purchase (e.g 312 items)
3. And then i'm try to purchase new subscriptions then it produced exception

**Expected results:** Payment Popup should be open

**Actual results:** Occur Exception
<img width="1669" alt="Screenshot 2022-08-19 at 6 39 48 PM" src="https://user-images.githubusercontent.com/25339734/185625289-69014297-ada6-4c0c-a70c-dd5cde9ead4f.png">

**Comment by danagbemava-nc** [comment]
Hi @hpsolver, please provide a complete minimal reproducible code sample as well as the output of `flutter doctor -v`. 

Please also provide the version of `in_app_purchase` you're using. 

Thank you
