### ISSUE TITLE
flutter all pictures turn purple

### ISSUE THREAD

**Issue by WuKong94** [flutter/flutter#109827]
## Problem description

Occasionally, it will appear after entering the foreground from the background, and all the pictures will turn purple. After restarting the APP, the pictures will load normally

**Expected results:** 

The picture is displayed normally.
**Actual results:** 
![IMG_9277](https://user-images.githubusercontent.com/16898532/185533010-95797d75-1a24-45e2-981c-3b0c1698eaf8.PNG)

## Development environment

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.0, on macOS 12.3.1 21E258 darwin-x64, locale
    zh-Hans-CN)
Checking Android licenses is taking an unexpectedly long time...[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.69.2)
[✓] Connected device (3 available)
    ! Error: 孙武东 is not connected. Xcode will continue when 孙武东 is connected.
      (code -13)
[✓] HTTP Host Availability

• No issues found!

## code desc

I am sorry that I cannot provide the code because I do not know which part of the code is faulty

**Comment by exaby73** [comment]
Hello @WuKong94. Thank you for filing this issue. Can you provide the below information:

- Can you try to reproduce this issue in a new project? Basically, what we're looking for is a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) so that we can verify and investigate the issue.
- Does this occur on a Simulator, or physical device? Is it reproducible on any other platforms like Android or desktop?

**Comment by WuKong94** [comment]
> 

It is currently only available on real iOS devices.
In addition, it is difficult for me to provide a new project, because it is not easy to reproduce, and it takes several days to reproduce in the background.

**Comment by exaby73** [comment]
@WuKong94 Could you give a sample of the code that exists that's causing this? For example: Are you using `Image.network()` or a 3rd party library?

Also, if you have gotten any crash logs from your users via something like Firebase Crashlytics if you have set that up, could you share those as well?

**Comment by WuKong94** [comment]
> 


> @WuKong94 Could you give a sample of the code that exists that's causing this? For example: Are you using `Image.network()` or a 3rd party library?
> 
> Also, if you have gotten any crash logs from your users via something like Firebase Crashlytics if you have set that up, could you share those as well?

I used Image.asset and cached_network_image, So I don't think it's cached_network_image,  I accessed Bugly, similar to Firebase Crashlytics, but did not find any error messages

**Comment by exaby73** [comment]
Are the images rendered purple from `Image.asset()` or from `cached_network_image`?

**Comment by WuKong94** [comment]
> 

all

**Comment by exaby73** [comment]
Are you using any specific image format? Or are they all pngs and/or jpegs?

**Comment by WuKong94** [comment]
> 

png

**Comment by exaby73** [comment]
Since I cannot reproduce this issue, I am labelling this for further insights from the team.

**Comment by chinmaygarde** [comment]
Without a reproducible test case, we unable to make progress on this.
