### ISSUE TITLE
Click sounds are missing from onClick events on cells (Android)

### ISSUE THREAD

**Issue by lukef** [flutter/flutter#10989]
In the vein of https://github.com/flutter/flutter/issues/6574, click sounds are missing from list view cells when they are clicked. Android only.

cc @goderbauer

**Comment by goderbauer** [comment]
@lukef Can you add a little more details? From looking at it a [ListView](https://docs.flutter.io/flutter/widgets/ListView-class.html) doesn't have a `onTap` handler that could emit a click sound. Instead, it just takes a list of generic child widgets. Those child widgets might of course have an `onTap` handler that might be missing a click sound. So, what widget are you putting inside this ListView? And which one of them has an `onTap` handler that you think should "click"?

**Comment by KevinTheGray** [comment]
```
import 'package:flutter/material.dart';

void main() {
  runApp(new MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: 'Click Test',
      theme: new ThemeData(
        primarySwatch: Colors.red,
      ),
      home: new MyHomePage(title: 'Click Test'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => new _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int counter = 0;

  @override
  void initState() {
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(
        title: new Text(widget.title),
      ),
      body: new ListView.builder(
        itemCount: 100,
        itemBuilder: (context, index) {
          return new GestureDetector(
            onTap: () {
              print("tapped");
            },
            child: new Padding(
              padding: const EdgeInsets.all(8.0),
              child: new Container(
                color: Colors.redAccent,
                height: 100.0,
              ),
            ),
          );
        },
      ),
    );
  }
}
```
If you put this into main.dart, I don't hear the click sounds when these cells are tapped

**Comment by Hixie** [comment]
Replace the GestureDetector with an InkWell. The tap sounds are a material feature.
If you want to get the tap sounds without the ink effects, you can use the Feedback class directly.

**Comment by KevinTheGray** [comment]
I see, will do.  The cells should have an inkwell anyway

**Comment by lukef** [comment]
@Hixie  - To be clear, the tap sounds have existed on Android before Material and are available on custom views. They're not a material feature natively.

https://developer.android.com/reference/android/view/View.html#attr_android:soundEffectsEnabled

**Comment by Hixie** [comment]
I meant a Flutter Material feature, sorry. 🙂 We don't have a library for earlier Android design languages.

**Comment by goderbauer** [comment]
I am closing this as I think there is no action for us to take. Feel free to re-open or file a new issue if there are remaining problems.
