### ISSUE TITLE
Problems with step 8 of Flutter codelab

### ISSUE THREAD

**Issue by wmleler** [flutter/flutter#10987]
There are some nasty problems with step 8 of the Flutter codelab.
`https://codelabs.developers.google.com/codelabs/flutter/#7`

The first code listing begins with:
`// Add the following code in the ChatScreenState class definition.`
The first line of code is:
`class ChatScreenState extends State<ChatScreen> {`
It should be:
`class ChatScreenState extends State<ChatScreen> with TickerProviderStateMixin {`

The next-to-last code listing begins:
`// Add the following code to main.dart.`
There are lots of added lines that do not have a "`//new`" comment

The last code listing begins:
`// Modify the following lines in main.dart.`
The last line of actual code (starts with "`decoration:`") is really long. No line breaks.

When I finished this page and ran the app, the app started giving what looks like an error message:
`E/SpannableStringBuilder(18941): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length`
Two of these errors are generated every time you try to send a message.

When you run the app, at first it does not work.
I ran the app on an actual Android device (Nexus 6P).  The app started up, but typing on the keyboard would not enter text into the message field, and the send icon never enabled.
I had to close the keyboard, and then open it again. Then the app would work (until I ran it again).
This is really bad, and would probably make it impossible to finish the lab.

I thought maybe I made a typo in the code lab, so I copied the main.dart file from the codelab source  at https://github.com/flutter/friendlychat/blob/master/lib/main.dart
I still had the same problems.

And there are many cases of bad indentation throughout the codelab. I don't know if we care about this, but it does make it hard to read the program and figure out what is going on. 

Sorry these instructions are not clearer, but I'm trying to pack to leave town and have run out of time. Feel free to ask me questions.

**Comment by LarkAscending** [comment]
Codelab-specific issues are fixed:
https://codelabs.developers.google.com/codelabs/flutter/#7
Please verify!

The indentation anomalies are a known issue. A space is getting stripped out on pasting into Google Docs. There may also be inconsistencies in space/tab characters. We do care but are taking a conservative, incremental approach to fixing them, since many snippets are affected.

**Comment by LarkAscending** [comment]
bump

**Comment by wmleler** [comment]
LGTM!
