### ISSUE TITLE
[engine/embedder] Rendering software frames faster than 60fps

### ISSUE THREAD

**Issue by slightfoot** [flutter/flutter#109894]
I am working on a custom embedder implementation and it is unclear to me how I might go about getting say 120fps from the engine. I am using the [current Flutter windows](https://github.com/flutter/engine/blob/a47ddf985d5934c0a17767788a236fda9149bdbe/shell/platform/windows/flutter_windows_engine.cc) as my go to example of correct implementation.

## Steps:
1. [Initialise the engine with a `vsync_callback` handler](https://github.com/flutter/engine/blob/a47ddf985d5934c0a17767788a236fda9149bdbe/shell/platform/windows/flutter_windows_engine.cc#L296)
    I am doing this exactly the same.
2. [Implement the OnVsync Handler](https://github.com/flutter/engine/blob/a47ddf985d5934c0a17767788a236fda9149bdbe/shell/platform/windows/flutter_windows_engine.cc#L385)
   Same implementation but the `FrameInterval` reports as **8'300'000** nanoseconds aka **8.3ms** aka **120fps**.
3. [Pass over the renderer configuration set to software and the ensure the surface_present_callback is working.](https://github.com/flutter/engine/blob/a47ddf985d5934c0a17767788a236fda9149bdbe/shell/platform/windows/flutter_windows_engine.cc#L104)
4. [Start the engine with Run](https://github.com/flutter/engine/blob/a47ddf985d5934c0a17767788a236fda9149bdbe/shell/platform/windows/flutter_windows_engine.cc#L340)
5. [Report a display device of 120fps](https://github.com/flutter/engine/blob/a47ddf985d5934c0a17767788a236fda9149bdbe/shell/platform/windows/flutter_windows_engine.cc#L347)
6. Finally I call `SendWindowMetricsEvent` with the framebuffer dimensions.

I am seeing the `surface_present_callback` called back with the correct frame data and the engine works as expected in all other ways. 

## Issue
The `surface_present_callback` callbacks occur at a rate of 60fps always. No matter what I configure the timing of vsync callbacks and/or set the display refresh rate.

I do not have any task-runner configuration in my args. Is this a requirement for this to work?

## Versions
Flutter Embedder ABI version: `1`
Flutter engine revision: `e85ea0e79c6d894c120cda4ee8ee10fe6745e187`
Embedder release: https://storage.googleapis.com/flutter_infra_release/flutter/e85ea0e79c6d894c120cda4ee8ee10fe6745e187/windows-x64/windows-x64-embedder.zip

**Comment by matthew-carroll** [comment]
To clarify this ticket, we're building a Dart package that calls into the Flutter engine. The Dart package captures frames from the engine and renders them to video. The problem we're facing is that we can't seem to get Flutter to pass time any faster than real-time. If we want to render 5 seconds of video frames, it's taking 5 seconds in engine time. This issue is not the result of video encoding time, because that work has been moved onto another thread.

**Comment by chinmaygarde** [comment]
From Triage: Per @jonahwilliams, this was an issue in the embedder and no action is needed.
