### ISSUE TITLE
Roller PRs are not auto approved by `fluttergithubbot`

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#109867]
Maybe some race conditions when auto approving roller PRs in autosubmit bot.

Example:  https://github.com/flutter/engine/pull/35537, where the `autosubmit` label is added, but it's not auto approved.

**Comment by keyonghan** [comment]
Though the label was added in the PR, but there was no log message related to this PR. @godofredoc could you check if there is any failures from github webhook side?

**Comment by ricardoamador** [comment]
Closing as this does not appear to be an issue:
![image](https://user-images.githubusercontent.com/32242716/197307227-a4c318d1-bb99-4446-ac34-a76478edc0ec.png)

**Comment by ricardoamador** [comment]
https://github.com/flutter/flutter/pull/115658

**Comment by keyonghan** [comment]
Issue has been resolved.
