### ISSUE TITLE
[Windows] Support high-contrast a11y feature

### ISSUE THREAD

**Issue by cbracken** [flutter/flutter#109802]
Internal: b/241362224

The high contrast theme is not getting set automatically when OS high-contrast accessibility setting is enabled/disabled.

## Minimal Repro

```dart
class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',

      theme: /* ... */,
      darkTheme: /* ... */,
      highContrastTheme: /* ... */,
      highContrastDarkTheme: /* ... */,
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}
```
Steps to repro:
1. Open the App.
2. Turn on the Dark Mode settings.
3. Verify if App Colors scheme has changed.
4. Re-launch the app if required.
5. Open the App.
6. Turn on the High Contrast settings.
7. Verify if App Colors scheme has changed.
8. Re-launch the app if required.

**Actual:** Color scheme of app does not change.

**Expected:** Color scheme should change as per the user settings.

**Comment by chinmaygarde** [comment]
Verified priority is accurate given the status of the internal issue.

**Comment by cbracken** [comment]
This may be a good starting point for detecting high-contrast mode:
https://docs.microsoft.com/en-us/windows/win32/w8cookbook/high-contrast-mode

Looks like you can watch for a [`WM_THEMECHANGED`](https://docs.microsoft.com/en-us/windows/win32/winmsg/wm-themechanged) event then use [`SystemParametersInfo`](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-systemparametersinfow) with the `SPI_GETHIGHCONTRAST` flag to check for high-contrast mode.

**Comment by yaakovschectman** [comment]
Detection of high contrast mode is introduced for Windows by https://github.com/flutter/engine/pull/35682
Do we need to also include some functionality for dark mode (as `darkTheme` is in the repro), or should we resolve this issue?

**Comment by cbracken** [comment]
You can close this issue. Thanks for fixing!

I believe dark theme already works in Windows, but it's been a while since I looked at it, so I could be wrong.

@loic-sharma is tracking related work to make sure the window decorations also pick up Dart mode in https://github.com/flutter/flutter/issues/107926.

**Comment by cbracken** [comment]
Looking at that patch it looks like we wired it up on the old (now deleted) UWP embedder but not for Win32, unless it landed in a later patch. Looks like a bunch of the plumbing is there though so it might not be too tough to wire up if you can catch it off the `WM_THEMECHANGED` events.

**Comment by loic-sharma** [comment]
I opened https://github.com/flutter/flutter/issues/110700 to track reacting to Windows's system theme changes.
