### ISSUE TITLE
InputDecoration's focusColor is no longer used with TextFormField, but that is not mentioned in documentation

### ISSUE THREAD

**Issue by abigotado** [flutter/flutter#109847]
Hello!

According to the [current documentation](https://api.flutter.dev/flutter/material/InputDecoration/focusColor.html):
```
/// By default the [focusColor] is based on the current [Theme].
  ///
  /// The decoration's container is the area which is filled if [filled] is
  /// true and bordered per the [border]. It's the area adjacent to
  /// [icon] and above the widgets that contain [helperText],
  /// [errorText], and [counterText].
```

As I have found it was removed from from UI rendering of TextFormField/TextField and now it is not working with these widgets. It would be very nice to mention that in the documentation.

Now it's not obvious, that it's useless to assign focusColor for TextFormField/TextField and it takes time to find out why it doesn't work.

**Comment by exaby73** [comment]
Hello @abigotado. Thank you for filing this issue. Can you provide the following information:

- Can you provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) so that we can verify this issue?
- The output of `flutter doctor -v`
- The output of `flutter run -v`

**Comment by abigotado** [comment]
Hello @exaby73 !

Thank you for your answer!

I'm sorry, maybe my title is a not fully correct. The ploblem is concerning only documentation. The usage of `focusColor` for UI rendering was removed in [#33062](https://github.com/flutter/flutter/pull/33062). So `focusColor` now has no impact on TextField/TexFormField UI rendering. And it doesn't have to. But that is not mentioned in documentation, that's why at the moment the documentation for `focusColor` looks quite misleading.

**Comment by exaby73** [comment]
Ahh I see now. Thank you @abigotado. Yeah I see that. Labelling for further insights from the team.

**Comment by abigotado** [comment]
Thank you very much @exaby73 ! 🙂
