### ISSUE TITLE
The showDialog() call in stock_menu.dart does nothing

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#1099]
If you open the drop-down menu (top right) in the stocks app, then pick "Refresh", it should show a dialog. It does not. I've no idea why. I've tried tracing it in the debugger and the call definitely gets made.

**Comment by eseidelGoogle** [comment]
I recommend we resolve this by deleting the stocks demo: https://github.com/flutter/flutter/issues/8374

**Comment by goderbauer** [comment]
Closing as this seems to work now.
