### ISSUE TITLE
[Add to App]The Flutter Project can't deal the multiple dex problem

### ISSUE THREAD

**Issue by liuguicen** [flutter/flutter#109921]
My Project Structure as The bellow
My Flutter Project is create fallow the [Adding to an Android app](https://docs.flutter.dev/development/add-to-app/android) https://docs.flutter.dev/development/add-to-app/android/project-setup

My Project Structure as The bellow
![2022-08-20 20-20-46 的屏幕截图](https://user-images.githubusercontent.com/13100498/185746135-4bd4953a-01da-404b-82ee-39e1e2c17dd9.png)
I have set the multi DEX related options, the original android project is normal ，but the flitter project still reports an error。

**Comment by maheshmnj** [comment]
Hi @liuguicen, Thanks for filing the issue. I am quite not sure what this bug is reporting, Can you please update the issue description and clarify the issue? And also share a minimal and complete sample project along with the output of `flutter doctor -v`  

Thanks
