### ISSUE TITLE
Run memory benchmarks in release mode

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#10998]
We currently run memory benchmarks in `--profile` mode. This allows us to use the VM service to synchronize the framework with memory measurements, but it also adds overhead from the VM service and timeline skewing the results. We should be able to run these benchmarks in release mode. However, we'd need a replacement for the VM service. We perform the following operations via the VM service:

- wait for the first frame to render before measuring the initial memory usage (`start_total_kb`)
  * this can be replaced by a simple `print` statement and read out of the `logcat`
- run a driver test that exercises the app in order to get a "cruising" memory usage (`end_total_kb`)
  * this can be replaced by an ad hoc test that drives the app from within the app process

/cc @rmacnak-google @eseidelGoogle

**Comment by Hixie** [comment]
Well I have this done for the scroll benchmark, but the numbers aren't much less flaky. Here's the raw data from five back-to-back runs:

```
"start_total_kb": 57430,
"end_total_kb": 185386,
"diff_total_kb": 127956

"start_total_kb": 92919,
"end_total_kb": 181339,
"diff_total_kb": 88420
 
"start_total_kb": 93804,
"end_total_kb": 179534,
"diff_total_kb": 85730
 
"start_total_kb": 95652,
"end_total_kb": 181096,
"diff_total_kb": 85444
 
"start_total_kb": 75448,
"end_total_kb": 176476,
"diff_total_kb": 101028
```

**Comment by Hixie** [comment]
Two options I can think of:
- make the memory benchmark process much more long-lived (right now this test takes a few seconds at most)
- run the test multiple times and use the median each time, rather than running it just once

@rmacnak-google @a-siva Any advice as to what would be a good way to get less noisy and more useful data regarding memory usage of Flutter apps?

**Comment by a-siva** [comment]
I am wondering if the number you are getting depends on whether a GC happens or not before the memory usage is measured.

**Comment by Hixie** [comment]
Quite possibly. Is there some way I can force a GC in a release build?

**Comment by Hixie** [comment]
I've done what this bug wanted. It hasn't done all that much to get us less noisy data though. I'll keep an eye on the numbers and figure out what to do next.
