### ISSUE TITLE
Print stack-trace from ErrorWidget onTap

### ISSUE THREAD

**Issue by apps-transround** [flutter/flutter#109950]
ErrorWidget is a great tool for displaying the essence of errors during widget builds. But it has limited area to show the error information and sometimes it is challenging to find the error location in the source based on that. 

ErrorWidget is easy to customize and even 3rd party packages may evolve to improve it. But one feature proved to be so essential that I propose to add it to the default widget: 

**Print the stack-trace to the console when onTap on the ErrorWidget.**
It's easy to try the proposed feature via custom ErrorWidget.builder, for example

```dart
  ErrorWidget.builder = (FlutterErrorDetails details) {
    return GestureDetector(
        onTap: () {
          debugPrint('onErrorWidgetTap => ${details.exceptionAsString()}');
          debugPrint(details.stack.toString());
        },
        child: ErrorWidget(details.exception));
  };
```

I think this is the natural behavior and developers will get more information and easy navigation to the error location.

(The proposed feature will not influence the real user experience because those users who see error widgets and console logs at the same time are often called developers.)

**Comment by maheshmnj** [comment]
Hi @apps-transround, Thanks for filing the issue. Even though this might sound a reasonable proposal, But, I believe you can already do that with a few lines of code as you have proposed.

**Comment by apps-transround** [comment]
Hi @maheshmnj Yes, you can, if you already know what and how to do.

The reason why I proposed it is to improve the developer experience mainly at the beginning of the learning curve. 
Currently they see something important and have no idea what to do with it. "Tap it" is the natural gesture but nothing happens...

**Comment by maheshmnj** [comment]
@apps-transround  Tapping on error widget works normally. Please see the below code sample

```dart
import "package:flutter/material.dart";

void main() {
  ErrorWidget.builder = (FlutterErrorDetails details) {
    return GestureDetector(
        onTap: () {
          debugPrint('onErrorWidgetTap => ${details.exceptionAsString()}');
          debugPrint(details.stack.toString());
        },
        child: Container(color: Colors.green));
  };

  runApp(const MaterialApp(home: Scaffold(body: MyApp())));
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    throw "help!";
  }
}

```

<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.4 21F79 darwin-arm, locale en-IN)
    • Flutter version 3.0.5 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (5 days ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-32, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.67.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.44.0

[✓] Connected device (3 available)
    • sdk gphone arm64 (mobile) • emulator-5554 • android-arm64  • Android 11 (API 30) (emulator)
    • macOS (desktop)           • macos         • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)              • chrome        • web-javascript • Google Chrome 103.0.5060.114

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by apps-transround** [comment]
@maheshmnj misunderstanding my comment. This is a feature request, not a bug report.

**Currently:** 

- **with the default builder,** 
- **without the feature I propose**

nothing happens onTap.

**Comment by maheshmnj** [comment]
@apps-transround  I understand that you are proposing to have this behavior built into the framework, As per my last comment, I meant that you could achieve your desired behavior with just a few [lines of code](https://github.com/flutter/flutter/issues/109950#issuecomment-1223585775)

>Hi @apps-transround, Thanks for filing the issue. Even though this might sound a reasonable proposal, But, I believe you can already do that with a few lines of code as you have proposed.

However, I will leave this feature request for the flutter team to decide.

**Comment by goderbauer** [comment]
Whenever the error widget is inserted into the tree, we already dump the stack-trace to the console, if I remember correctly. Why do you need to print it again on tap?

In general, we try to keep the ErrorWidget as simple as possible because if there's an error building the ErrorWidget we are in trouble...
