### ISSUE TITLE
[Impeller] Reduce overhead in small draw calls

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#109949]
From investigating a very wonderful custom app, an expensive part of the UI contained a few hundred calls to drawRect in a custom painter. It was difficult to see the impact of this on the Skia backend due to raster caching, but on impeller all calls to drawRect bottom out in drawPath.

Rather than telling folks to replace these drawRect calls with a single drawVertices, It would be nice if we could at least combine them into a single drawPath to reduce the overhead a bit (I actually don't know much about metal, but webgl at least tells folks to minimize draw calls).

That would require compatible paints, probably the exact same paints in most cases.

------------------------------------

Update: there is a substantial amount of overhead that we can remove before we explore batching draw calls. Below I've started tracking efforts to remove extra copying and making engine uploads more efficient. Once we're tapped out there, we can go back and re-evaluate.

**Comment by chinmaygarde** [comment]
We can also implement this in Impeller by implementing a pass that analyzes a command stream to look for such optimizations.

**Comment by dnfield** [comment]
We'll need at least some of this in impeller, since some of it is coming from SkParagraph, e.g. on the fullscreen_textfield benchmark that's currently getting broken up into 508 individual calls to drawTextBlob, which we directly translate into TextContents, which directly lead to draw calls. Many of those are for individual emoji.

**Comment by dnfield** [comment]
@bdero suggested another approach would be to look at why the CPU side allocations are costing as much as they are and seeing if we can come up with a general fix for that.

**Comment by jonahwilliams** [comment]
I'm writing another Skia vs Impeller benchmark for this that we can run on CI. Might be a useful place to investigate as well

**Comment by jonahwilliams** [comment]
https://github.com/flutter/flutter/pull/112678

**Comment by jonahwilliams** [comment]
From running this app in instruments, I see a huge amount of time spent allocating/freeing data and in tesselation.

[QRTrace.trace.zip](https://github.com/flutter/flutter/files/9679619/QRTrace.trace.zip)

<img width="1279" alt="Screen Shot 2022-09-29 at 4 35 23 PM" src="https://user-images.githubusercontent.com/8975114/193160244-2a6b33a9-0f96-408d-8a91-556c42f65a25.png">

**Comment by jonahwilliams** [comment]
Upon further investigation, I think a great amount of this overhead is due to the fact that the libtess defaults we're using are not well configured for individually tessellating individual small geometry pieces. See the defaults in https://github.com/memononen/libtess2/blob/fc52516467dfa124bdd967c15c7cf9faf02a34ca/Include/tesselator.h#L157 , these are huge bucket sizes.

Reducing the bucket size had a large improvement on the benchmark, see below. That said, we can probably get the best of both worlds by using our own arena.

before:

![image](https://user-images.githubusercontent.com/8975114/193185114-db3fd4b1-68de-4008-b906-1b7701401d0d.png)

After:

![image](https://user-images.githubusercontent.com/8975114/193185229-5a53c2ea-89cd-4592-b51a-6cf27a73c0ba.png)

**Comment by jonahwilliams** [comment]
diff is:

```diff
diff --git a/impeller/tessellator/tessellator.cc b/impeller/tessellator/tessellator.cc
index 0b4176f930..404bea0be3 100644
--- a/impeller/tessellator/tessellator.cc
+++ b/impeller/tessellator/tessellator.cc
@@ -28,6 +28,22 @@ static int ToTessWindingRule(FillType fill_type) {
   return TESS_WINDING_ODD;
 }
 
+void* heapAlloc(void* userData, unsigned int size) {
+  return malloc(size);
+}
+
+void* heapRealloc(void* userData, void* ptr, unsigned int size) {
+  return realloc(ptr, size);
+}
+
+void heapFree(void* userData, void* ptr) {
+  free(ptr);
+}
+
+static TESSalloc defaulAlloc = {
+    heapAlloc, heapRealloc, heapFree, 0, 16, 16, 16, 16, 16, 16,
+};
+
 static void DestroyTessellator(TESStesselator* tessellator) {
   if (tessellator != nullptr) {
     ::tessDeleteTess(tessellator);
@@ -49,9 +65,7 @@ Tessellator::Result Tessellator::Tessellate(
   using CTessellator =
       std::unique_ptr<TESStesselator, decltype(&DestroyTessellator)>;
 
-  CTessellator tessellator(
-      ::tessNewTess(nullptr /* the default ::malloc based allocator */),
-      DestroyTessellator);
+  CTessellator tessellator(::tessNewTess(&defaulAlloc), DestroyTessellator);
```

**Comment by jonahwilliams** [comment]
This change has rolled into the framework. On the gallery transition perf, 90% rasterize time is down by about 1.5 ms: 

https://flutter-flutter-perf.skia.org/e/?queries=sub_result%3D90th_percentile_frame_rasterizer_time_millis%26sub_result%3D99th_percentile_frame_rasterizer_time_millis%26sub_result%3Daverage_frame_rasterizer_time_millis%26test%3Dcomplex_layout_scroll_perf_impeller_ios__timeline_summary%26test%3Dflutter_gallery__transition_perf_e2e_impeller_ios&selected=commit%3D31410%26name%3D%252Carch%253Dintel%252Cbranch%253Dmaster%252Cconfig%253Ddefault%252Cdevice_type%253DiPhone_6s%252Cdevice_version%253DiOS-15.5%252Chost_type%253Dmac%252Csub_result%253D90th_percentile_frame_rasterizer_time_millis%252Ctest%253Dflutter_gallery__transition_perf_e2e_impeller_ios%252C


![image](https://user-images.githubusercontent.com/8975114/193374068-fcf472e4-398e-4581-a2ab-968a370638e8.png)

**Comment by jonahwilliams** [comment]
https://github.com/flutter/engine/pull/36914 is the latest work on this. Since the original issue was about the performance of 100s of drawRect calls, I think this is the last piece to close it out (Otherwise this issue would stay open forever, as we can always make things faster).

If we hit new scenarios in the future where canvas operations are slower than expected we can file new issues
