### ISSUE TITLE
Year list in DatePicker should begin at the selected year

### ISSUE THREAD

**Issue by alardizabal** [flutter/flutter#10991]
When the initial year is set to a distant date in the past, it would be great to have the option for the year list to first display the currently selected year. Currently, the date picker resets to the initial year. When the picker is meant to be comprehensive in showing birthdays, the picker potentially starts at a year in the distant past which is inconvenient.

![screenshot_20170627-011516](https://user-images.githubusercontent.com/3614291/27571871-8893b60e-5ad6-11e7-9c38-9778cc16b7ed.png)

![screenshot_20170627-011521](https://user-images.githubusercontent.com/3614291/27571872-8ce3a69c-5ad6-11e7-93e5-add0c6c5b6de.png)

**Comment by eseidelGoogle** [comment]
Thank you for the report.  @HansMuller or @xster know this code.

**Comment by collinjackson** [comment]
Marked as customer blocker because posse needs this.
