### ISSUE TITLE
docs.flutter.io difficult to use on mobile

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#10990]
Just visited docs.flutter.io on my iPhone (Safari on iOS 10) to quickly look up an API. It is very difficult to use on mobile:
* there is no search field to quickly search for something (<--- main problem)
* the actual information is embedded in a strangely scrolling div
* vertical scrolling is enabled even though there is no need for it
* when scrolling through the hamburger menu, the page below it scrolls as well when the end of the hamburger menu is reached.

**Comment by Hixie** [comment]
cc @sethladd 

Some of these issues may be already filed (in particular I think the search field issue is filed).

**Comment by sethladd** [comment]
Thanks for the feedback! Moved to https://github.com/dart-lang/dartdoc/issues/1469
