### ISSUE TITLE
IOS cannot be build whether I create a new project or not 

### ISSUE THREAD

**Issue by sarashawky** [flutter/flutter#109960]
[Build target Runner_2022-08-21T22-15-52.txt](https://github.com/flutter/flutter/files/9389889/Build.target.Runner_2022-08-21T22-15-52.txt)

this is the logs when I try to build ios however project run through a simulator

Thanks in advance

**Comment by mohyghb** [comment]
Same problem here, using M1 mac (I assume it has to do something with the M1)

**Comment by EmreSURK** [comment]
Please add flutter doctor output.

**Comment by sarashawky** [comment]
/Users/cashcall/flutter/bin/flutter doctor --verbose
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.5.1 21G83 darwin-arm, locale en-EG)
    • Flutter version 3.0.5 at /Users/cashcall/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (6 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/cashcall/Library/Android/sdk
    • Platform android-32, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 59.0.3
    • Dart plugin version 211.7727

[✓] Connected device (3 available)
    • iPhone 11 Pro (mobile) • 87C26DD8-BD16-427A-99D2-7CFA9CF88F6E • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.5.1 21G83 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 104.0.5112.101

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
Process finished with exit code 0

**Comment by huycozy** [comment]
Hi @sarashawky 
Which command did you use to build iOS app? And could you try building app with XCode?

**Comment by huycozy** [comment]
Hi @sarashawky
Which command did you use to build iOS app? And could you try building app with XCode? 
Please also provide the output of `flutter run -v`.

**Comment by sarashawky** [comment]
Hi huycozy,
command of build ios app is: flutter build ios. 
Also I build with xcode and the same error is appeared.
below is the output of  flutter run -v
https://drive.google.com/file/d/1IFPoAbTH57W8wJDO9JP0GVt94ZfmvR-s/view?usp=sharing

**Comment by huycozy** [comment]
Hi @sarashawky 
Based on your `flutter run -v` output, it looks like your project contains some 3rd plugins. Could you please provide the `flutter run -v` output when running a new Flutter default project without 3rd plugins?

**Comment by sarashawky** [comment]
[flutter_run_output.txt](https://github.com/flutter/flutter/files/9400863/flutter_run_output.txt)
Hi Hycozy,
please find the` flutter run -v `output of a new project

**Comment by huycozy** [comment]
Hi @sarashawky 
```
[  +35 ms] No supported devices connected.
[  +26 ms] The following devices were found, but are not supported by this
project:
           macOS (desktop) • macos  • darwin-arm64   • macOS 12.5.1 21G83
darwin-arm
           Chrome (web)    • chrome • web-javascript • Google Chrome
104.0.5112.101
           If you would like your app to run on macos or web, consider running
`flutter
           create .` to generate projects for these platforms.
```

It looks like you create a project that is supported for iOS only. But when you were running the project, there was no supported iOS device. So, try opening a iOS simulator and retry.

**Comment by sarashawky** [comment]
[flutter_run_output.txt](https://github.com/flutter/flutter/files/9403046/flutter_run_output.txt)

Sorry for that, please find the logs attached

**Comment by huycozy** [comment]
Hi @sarashawky, thanks for providing the logs, but it seems to have worked normally when your device (iPhone 11) is attached and the application was running. 
Could you please describe what happened on the application then? It'll be great if you can provide a recorded video. 
Thanks!

**Comment by sarashawky** [comment]
Hi @huycozy, Thanks for your support, please note that the application can run on simulator, but it didn't build or run on physical devices , below is the flutter logs when run on physical device and the logs when build ios in xcode

[flutter_run_output.txt](https://github.com/flutter/flutter/files/9414937/flutter_run_output.txt)

[Build target Runner_2022-08-24T11-43-05.txt](https://github.com/flutter/flutter/files/9414941/Build.target.Runner_2022-08-24T11-43-05.txt)

**Comment by huycozy** [comment]
Hi @sarashawky 
Based on the updated logs in https://github.com/flutter/flutter/issues/109960#issuecomment-1225485895:

> Target debug_unpack_ios failed: Exception: Failed to codesign /Users/cashcall/Desktop/untitled1/build/ios/Debug-iphoneos/Flutter.framework/Flutter with identity 5DB0110AF5EACC1C64074008A18B40A063CC3FC5.

I see there's an open issue addressing the case you described #106876 and takes a look at https://github.com/flutter/flutter/issues/106876#issuecomment-1181916833 that give you a workaround for this issue.
Closing this issue as a duplicate, so please follow up on it for further updates. You can leave there your comment and react an upvote to the original comment will help to raise the issue. Thank you!
