### ISSUE TITLE
Cannot find 'GeneratedPluginRegistrant' in scope

### ISSUE THREAD

**Issue by ashishazilen** [flutter/flutter#109981]
![Screenshot 2022-08-22 at 11 55 54 AM](https://user-images.githubusercontent.com/96577878/185853216-ca05b84a-7ca1-4292-913d-192d82b6e6bc.png)

iOS Application getting crash

**Comment by darshankawar** [comment]
@ashishazilen 
Same as https://github.com/flutter/flutter/issues/109979#issuecomment-1222328587

Closing due to lack of info / details. Please provide all requested details when opening an issue.
