### ISSUE TITLE
1.5% AOT size regression between 8a2d337 and 38b3e89

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#10996]
We've added 135Kb to the IPA size of the `basic_material_app_ios__size` benchmark (1.5%), and 37Kb to `aot_snapshot_size_total` of the `flutter_gallery__build` benchmark.

Between these engine revisions we went from `dart_revision` [65a5707](https://github.com/dart-lang/sdk/tree/65a5707189dec6c5e0174cbc821acfb90f0c9b3f) to [3c543bb](https://github.com/dart-lang/sdk/tree/3c543bb210711dd6761d592a863fd6f32e1f1279).

The changes in the engine's Dart code were minimal between these revisions: https://github.com/flutter/engine/compare/8a2d337...38b3e89

I'm not that worried about the 1.5% regression itself, but I'm wondering if we have a low snapshot size density per line of Dart code. IOW, can a 150LoC Dart change add 37Kb/135Kb to the app size?

/cc @rmacnak-google 

Dashboard:

<img width="778" alt="size-regression" src="https://user-images.githubusercontent.com/211513/27598575-c80d05f8-5b1a-11e7-9689-4cff2a4c1b05.png">

**Comment by Hixie** [comment]
(The release_size_in_bytes being red is tracked at https://github.com/flutter/flutter/issues/10698.)

**Comment by rmacnak-google** [comment]
There's not a linear relationship between the size of the source program and the snapshot. We have global optimizations like detecting unique implementors of selectors or interfaces and tree shaking, and any global optimization can be affected by small changes in the source program. Still, I think it's more likely the size increase is due to a change in the VM than in the framework.

**Comment by Hixie** [comment]
@jason-simmons said he's started looking at this to work out if it's a specific VM commit that caused it.

**Comment by jason-simmons** [comment]
I noticed a couple of recent changes that correlated with slight increases in AOT snapshot size:
  * https://github.com/dart-lang/sdk/commit/cec963f028198ec5871840491ba78b096ad0b819
  * https://github.com/dart-lang/sdk/commit/bb527cb89e554388ae986fa754705c5b7710a561

**Comment by yjbanov** [comment]
Closing. I don't think we'll be able to track this down any more and we've seen improvements since this was filed.
