### ISSUE TITLE
it's always on my cell phone, This happened to some other phones, but not all of them

### ISSUE THREAD

**Issue by Horrible122** [flutter/flutter#109994]
it's always on my cell phone, This happened to some other phones, but not all of them
When I create a new project, there was still a problem with my phone
It's normal on the simulator

![image](https://user-images.githubusercontent.com/41510983/118224820-7979b900-b4b6-11eb-986a-e1a73f7367ec.png)
[√] Flutter (Channel beta, 2.2.0-10.3.pre, on Microsoft Windows [Version 10.0.19042.928], locale zh-CN)
    • Flutter version 2.2.0-10.3.pre at D:\flutter
    • Framework revision 06e2fd6357 (5 days ago), 2021-05-08 11:28:22 -0700
    • Engine revision a123e75c60
    • Dart version 2.13.0 (build 2.13.0-211.14.beta)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at D:\androidSDK\android-sdk_r24.4.1-windows\android-sdk-windows
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = D:\androidSDK\android-sdk_r24.4.1-windows\android-sdk-windows
    • Java binary at: D:\jdk1.8\bin\java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] IntelliJ IDEA Ultimate Edition (version 2020.1)
    • IntelliJ at D:\IntelliJ IDEA\IntelliJ IDEA 2020.1.1
    • Flutter plugin version 56.0.1
    • Dart plugin version 201.7223.99

[√] VS Code
    • VS Code at C:\Users\86183\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (3 available)
    • vivo X20A (mobile) • 572a1c03 • android-arm64  • Android 8.1.0 (API 27)
    • Chrome (web)       • chrome   • web-javascript • Google Chrome 90.0.4430.212
    • Edge (web)         • edge     • web-javascript • Microsoft Edge 90.0.818.56

! Doctor found issues in 1 category.

_Originally posted by @childDai in https://github.com/flutter/flutter/issues/82430#issuecomment-841012492_

**Comment by Horrible122** [comment]
Exactly the same Issue! no need of other information!

**Comment by huycozy** [comment]
Hi @Horrible122 
Do you have this issue with exactly Flutter version and affected device same as @childDai?
If so, please try upgrading Flutter SDK to the latest and retry to see if the issue is still reproduced.
