### ISSUE TITLE
[CP] fix flutter not finding custom device

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#109958]
### issue_link

https://github.com/flutter/flutter/issues/108883

### Commit Hash

c6aeaa305c6ec86ff3148f375f0d9b68f7e1477c

### Target

beta

### pr_link

https://github.com/flutter/flutter/pull/109957

### Impacted Users

Customers using custom embedders

### Impact Description

Custom device tooling does not work without this fix.

### Workaround

The only workaround would be to use master channel.

### Risk

low

### Test Coverage

yes

### Validation Steps

This fix has been working on master channel for ~3 weeks.

**Comment by itsjustkevin** [comment]
This is a small change with tests already passing on the cherry-pick PR.  Marking this as approved.  

CC: @XilaiZhang @CaseyHillers
