### ISSUE TITLE
[CP] Enable tooling custom device support on beta and stable channel

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#110029]
### issue_link

https://github.com/flutter/flutter/issues/108787

### Commit Hash

bd6b5cef9515a0d4b8bb34fa8c546a4ed3bcbf8c

### Target

beta

### pr_link

https://github.com/flutter/flutter/pull/109959

### Impacted Users

Customers with custom embedders

### Impact Description

Customers with custom embedders of the Engine are unable to use tooling support for custom devices on beta and stable channels. Wanting to cherry-pick this to avoid waiting until EOY for this to be available under the regular schedule.

### Workaround

Using master channel, but that is a big hassle.

### Risk

low

### Test Coverage

yes

### Validation Steps

The feature flag works on beta and stable channels.

**Comment by zanderso** [comment]
@itsjustkevin

**Comment by itsjustkevin** [comment]
@christopherfujino can you take a second look at this and the associated pr?

**Comment by christopherfujino** [comment]
> @christopherfujino can you take a second look at this and the associated pr?

:+1:

**Comment by christopherfujino** [comment]
request and PR approved
