### ISSUE TITLE
Engine does not appear to correctly apply memory pressure for Dart wrapper types

### ISSUE THREAD

**Issue by rmacnak-google** [flutter/flutter#11007]
When I look up at the open persistent handles in Observatory, I notice that every Picture and Paragraph claims to have an external size of 16B. External size is passed to the Dart VM during Dart_NewWeakPersistentHandle, it is used to decide when to do garbage collections. Currently it seems this size is based on sizeof(blink::Picture), but it should be based on the size of the underlying resource for the GC to correctly react to a accumulating Picture Dart wrappers.

**Comment by eseidelGoogle** [comment]
I presume the size can be updated after creation as well?  This should be straightforward to fix.

**Comment by rmacnak-google** [comment]
There's currently no API to update the external size associated with a weak handle, but it would be straightforward to add if needed.
