### ISSUE TITLE
Emoji & Symbols panel doesn't snap to TextField cursor position

### ISSUE THREAD

**Issue by janiselfert** [flutter/flutter#110010]
**Steps to Reproduce**

1. Create new project
2. Replace main.dart with contents below
3. flutter run (platform macOS)
4. Focus TextField and optionally type something
5. Open macOS "Emojis & Symbols" panel (e.g.  Click "Show Emojis & Symbols" in the macOS menu bar input menu)

**Expected results:** 
Emoji & Symbols panel should open and then automatically snap to the text cursor, just like it does when running as a web app.

**Actual results:** 
Emoji & Symbols panel opens, but doesn't snap to text cursor, it just appears centred on the screen.

**main.dart**
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Emojis & Symbols Panel Positioning',
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Example'),
        ),
        body: const Center(child: TextField()),
      ),
    );
  }
}
```

**Screenshots**
Actual result when running as macOS desktop app:
![Actual result (macOS)](https://user-images.githubusercontent.com/58039295/185953456-3c029338-0fb9-449f-ab67-985f9386fb11.jpg)
Expected result (here, run as a web app in chrome):
![Expected result (chrome / web)](https://user-images.githubusercontent.com/58039295/185953519-1e86509b-f179-4f49-8c31-285ba0f6ef13.jpg)

**Additional Information**
Flutter Channel stable, version 3.0.5, run on macOS 12.5.1 21G83 darwin-x64 in debug mode

**Comment by maheshmnj** [comment]
Hi @janiselfert, Thanks for filing the issue. I can reproduce the issue on the latest stable and the master channel. The emoji window is always in the center of the screen regardless of the input position. White it is at correct positon on the web.


  ### MacOS Desktop
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/31410839/186109178-fe7ac6bf-1bbf-4e9f-b406-390d934441f5.png">

### Web

<img width="515" alt="image" src="https://user-images.githubusercontent.com/31410839/186108799-59dd7bfe-5da6-4224-b52c-09ed7d5b83df.png">


similar to https://github.com/flutter/flutter/issues/101222

<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.4 21F79 darwin-arm, locale en-IN)
    • Flutter version 3.0.5 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (5 days ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-32, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.67.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.44.0

[✓] Connected device (3 available)
    • sdk gphone arm64 (mobile) • emulator-5554 • android-arm64  • Android 11 (API 30) (emulator)
    • macOS (desktop)           • macos         • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)              • chrome        • web-javascript • Google Chrome 103.0.5060.114

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

```
[✓] Flutter (Channel master, 3.1.0-0.0.pre.2186, on macOS 12.4 21F79 darwin-arm, locale en-IN)
    • Flutter version 3.1.0-0.0.pre.2186 on channel master at /Users/mahesh/Documents/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 458c7b9c65 (13 days ago), 2022-08-10 03:19:07 -0400
    • Engine revision 75e17f1a6f
    • Dart version 2.19.0 (build 2.19.0-81.0.dev)
    • DevTools version 2.16.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-32, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13C100
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.70.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.46.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 104.0.5112.101

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by LongCatIsLooong** [comment]
Unable to reproduce the issue. It seems to be working correctly on master (ddfcda73cd7effbf9f23dae08e9eca22d634776d)
<img width="396" alt="Screen Shot 2022-08-31 at 1 10 06 PM" src="https://user-images.githubusercontent.com/31859944/187772816-4174021e-b2c4-472e-936a-931f72946b01.png">

**Comment by janiselfert** [comment]
Issue is partially fixed. The Panel seems to snap to the correct position in the minimal example provided with this issue in 3.3.0 on the stable channel. Though if the TextField is placed inside of an InteractiveViewer with scale != 100% the panel will not snap correctly and still spawn somewhere on the screen. If the viewer is not scaled, it works correctly.
Probably the same issue as https://github.com/flutter/flutter/issues/110068, which was probably closed prematurely.

**Comment by KevinBrendel** [comment]
Yes, the remaining issue seems to be the same one that is causing the behavior described in https://github.com/flutter/flutter/issues/110068.

**Comment by likang** [comment]
This issue can be reproduced by add a Transform with scale and translation to widget. @LongCatIsLooong  @maheshmnj 

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    Matrix4 matrix4 = Matrix4.identity();
    matrix4.scale(2.0);
    matrix4.translate(10.0, 10.0);
    return MaterialApp(
      title: 'Emojis & Symbols Panel Positioning',
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Example'),
        ),
        body: Center(
          child: Transform(
            transform: matrix4,
            child: const SizedBox(
              width: 100,
              height: 100,
              child: TextField(),
            ),
          ),
        ),
      ),
    );
  }
}
```

**Comment by LongCatIsLooong** [comment]
`CATransform3DIsAffine` tells me the transform isn't affine while it apparently should be. Maybe `CATransform3D` is in row major order after all.

**Comment by likang** [comment]
@LongCatIsLooong great dig 👍 M33 means scale on z which indeed is not affine.

so if we scale by`matrix4.scale(2.0, 2.0, 1.0)` problem will be solved 👏

**Comment by likang** [comment]
in further, maybe we don't need let platform knows `transform` by `TextInputConnection.setEditableSizeAndTransform`, just give it a transformed rect in `TextInputConnection.setCaretRect`.

**Comment by LongCatIsLooong** [comment]
Some other functionalities still need the transform. On web the transform is used for the DOM element's css `transform` property.
