### ISSUE TITLE
[file_selector] Add Android support

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#110098]
With iOS support recently landed, we now have coverage (for the subset that is relevant everywhere, which is mostly opening files) across all platforms but Android. It would be good to have Android covered as well so it's completely cross-platform.

**Comment by csells** [comment]
Can I ask the status on this? I'd love to be able to read and write files in Android (with the user's permission, of course).

**Comment by lesnitsky** [comment]
we would like to use this plugin in FlutterFire for Firebase UI Storage, lack of android support is the only thing that is missing for our use case.

**Comment by stuartmorgan** [comment]
@lesnitsky It's in progress; @bparrishMines is in the process of updating and completing the PR that was started at https://github.com/flutter/plugins/pull/6547
