### ISSUE TITLE
[iOS] StateError painting.dart in Path.combine in _RenderCupertinoTextSelectionToolbarShape

### ISSUE THREAD

**Issue by zddarova** [flutter/flutter#110076]
Hi, I'm faced with an Exception that was reported in Sentry and I'm not sure what could be the cause, how to fix it, or reproduce it.

This issue is related to text selection on iOS. It is rare and affects a few users, but generates a lot of errors coz this is probably a UI bug and it throws an error every time the screen repaints.
It started a year ago when flutter was updated  to the 2nd version and does not depends on the device model or ios version. 
I tried to enable some accessibility settings (bold text, high contrast, zoom) but had no luck in reproducing it.
I think, this is a Flutter issue, but I have not found any similar threads in the Flutter repo and have no steps to reproduce. 

In this screen, I'm using `SelectableText` widget and `TextField`, but I'm not sure, which could throw this error,

Issue caused file is `text_selection.dart` from Cupertino library.
Class is `_RenderCupertinoTextSelectionToolbarShape`
Method `_clipPath`, `Path.combine` call, line `284`.

<details>
  <summary>Logs</summary>

Error and stack trace:
```
StateError: Bad state: Path.combine() failed.  This may be due an invalid path; in particular, check for NaN values.
  File "painting.dart", line 2616, in Path.combine
  File "text_selection_toolbar.dart", line 284, in _RenderCupertinoTextSelectionToolbarShape._clipPath
  File "text_selection_toolbar.dart", line 298, in _RenderCupertinoTextSelectionToolbarShape.paint
  File "object.dart", line 2449, in RenderObject._paintWithContext
  File "object.dart", line 141, in PaintingContext._repaintCompositedChild
  File "object.dart", line 100, in PaintingContext.repaintCompositedChild
  File "object.dart", line 995, in PipelineOwner.flushPaint
  File "binding.dart", line 499, in RendererBinding.drawFrame
  File "binding.dart", line 883, in WidgetsBinding.drawFrame
  File "binding.dart", line 363, in RendererBinding._handlePersistentFrameCallback
  File "binding.dart", line 1144, in SchedulerBinding._invokeFrameCallback
  File "binding.dart", line 1081, in SchedulerBinding.handleDrawFrame
  File "binding.dart", line 995, in SchedulerBinding._handleDrawFrame
  File "zone.dart", line 1426, in _rootRun
  File "zone.dart", line 1328, in _CustomZone.run
  File "zone.dart", line 1236, in _CustomZone.runGuarded
  File "hooks.dart", line 151, in _invoke
  File "platform_dispatcher.dart", line 308, in PlatformDispatcher._drawFrame
  File "hooks.dart", line 115, in _drawFrame
```

Flutter doctor output:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.5.1 21G83 darwin-arm, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.70.2)
[✓] Connected device (2 available)
[✓] HTTP Host Availability
```

</details>

I would appreciate any help with it, tips, or suggestion on how it could be reproduced or fixed.

**Comment by zddarova** [comment]
I have a suggestion that this issue might be related to this fix https://github.com/flutter/flutter/issues/84419#issuecomment-874353898, which we are using too. 
I've added a mounted check in order to make sure that the widget is still in the tree when we are trying to clear the controller value.
Looks like
`if (mounted) _textController.clear();`
But need to wait until this code will be delivered to production in order to check, coz I'm not having steps to reproduce this. Anyway, I'll comment here, when I see any results of this condition adding.

**Comment by exaby73** [comment]
Hello @zddarova. Thank you for filing this bug. I'll label it for further insights from the team on this.

**Comment by LongCatIsLooong** [comment]
I suspect this line https://github.com/flutter/flutter/blob/a7ba717b2fa1f2afa82131272902e60b5f3630a5/packages/flutter/lib/src/cupertino/text_selection_toolbar.dart#L265 introduced `NaN` values to the path. Are you applying any perspective transforms in the app, for example one that would make the view orthogonal to the screen?

**Comment by AndreyKomarichev10** [comment]
I don't think so. I am just using flutter built-in widgets, no packages for building chat UI, don't remember there any transformations like those you mentioned

**Comment by LongCatIsLooong** [comment]
Then the `NaN` is likely from here:
https://github.com/flutter/flutter/blob/4b91b220b83a301dd924b7775f27221a3b772569/packages/flutter/lib/src/widgets/text_selection.dart#L1212-L1232

**Comment by AndreyKomarichev10** [comment]
> I have a suggestion that this issue might be related to this fix [#84419 (comment)](https://github.com/flutter/flutter/issues/84419#issuecomment-874353898), which we are using too. I've added a mounted check in order to make sure that the widget is still in the tree when we are trying to clear the controller value. Looks like `if (mounted) _textController.clear();` But need to wait until this code will be delivered to production in order to check, coz I'm not having steps to reproduce this. Anyway, I'll comment here, when I see any results of this condition adding.

It didn't help

**Comment by kjwong** [comment]
Anyone find a solution to this? We're seeing crashes from the same error and not sure how to reproduce.

stack trace:
```
Fatal Exception: FlutterError
0  ???                            0x0 Path.combine (dart:ui)
1  ???                            0x0 _RenderCupertinoTextSelectionToolbarShape._clipPath + 318 (text_selection_toolbar.dart:318)
2  ???                            0x0 _RenderCupertinoTextSelectionToolbarShape.paint + 332 (text_selection_toolbar.dart:332)
3  ???                            0x0 RenderObject._paintWithContext + 2853 (object.dart:2853)
4  ???                            0x0 PaintingContext._repaintCompositedChild + 169 (object.dart:169)
5  ???                            0x0 PaintingContext.repaintCompositedChild + 112 (object.dart:112)
6  ???                            0x0 PipelineOwner.flushPaint + 1137 (object.dart:1137)
7  ???                            0x0 RendererBinding.drawFrame + 518 (binding.dart:518)
8  ???                            0x0 WidgetsBinding.drawFrame + 865 (binding.dart:865)
9  ???                            0x0 RendererBinding._handlePersistentFrameCallback + 381 (binding.dart:381)
10 ???                            0x0 SchedulerBinding._invokeFrameCallback + 1289 (binding.dart:1289)
11 ???                            0x0 SchedulerBinding.handleDrawFrame + 1218 (binding.dart:1218)
12 ???                            0x0 SchedulerBinding._handleDrawFrame + 1076 (binding.dart:1076)
```

We also just use the built-in SelectableText widget and don't apply any transformations.

**Comment by LongCatIsLooong** [comment]
Since this doesn't have a repro, even with the stacktrace it's difficult to pinpoint the exact cause. I'm going to add some asserts around the crash site and hopefully that will help us debug the issue.
