### ISSUE TITLE
Address null safety exclusions in flutter/packages

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter#110024]
See https://github.com/flutter/flutter/issues/110016 for context:

- [x] convert `fuchsia_ctl` to null safety: https://github.com/flutter/packages/pull/2528
- [x] convert `packages/imitation_game/imitation_tests/smiley/flutter/smiley` to null safety: https://github.com/flutter/packages/pull/2526
- [x] convert `packages/pigeon/platform_tests/android_unit_tests`, `.../ios_swift_unit_tests`, and `.../ios_unit_tests` to null safety: https://github.com/flutter/packages/pull/2526
- [x] convert `imitation_game` to null safety: https://github.com/flutter/packages/pull/2483
- [x] convert `web_benchmarks` to null safety: https://github.com/flutter/flutter/issues/98647

**Comment by mit-mit** [comment]
https://github.com/flutter/packages/pull/2506/ partially migrates `fuchsia_ctl`. Tests for it have not been migrated as they depend on mockito.

**Comment by mit-mit** [comment]
@https://github.com/akbiggs before we invest in a manual migration of the tests for  `fuchsia_ctl`, can you confirm that this package is still in use?

**Comment by srawlins** [comment]
Those tests in `fuchsia_ctl` may require some examination, as they use mockito, and mockito [more-or-less](https://github.com/dart-lang/mockito/blob/master/NULL_SAFETY_README.md) requires code-gen via `build_runner` in null safety.

The best route might be to remove all mockito usage...

in `command_line_test.dart`... I can't really tell what the use of this is... they appear to be testing the functionality of another package, `package:process`... but in any case I bet it can be replaced with stream matchers from `package:test`. https://pub.dev/packages/test#stream-matchers

The others look tricky, as they're using mockito functionality like verify etc. But manual mocks might be the solution. Implementing all the necessary methods with code that tracks whether a method was called...

**Comment by mit-mit** [comment]
From email discussion with @akbiggs and others it sounds like `` isn't used anymore, so deleting it in https://github.com/flutter/packages/pull/2528

**Comment by mit-mit** [comment]
All done :-)
