### ISSUE TITLE
Address null safety exclusions in flutter/engine

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter#110020]
See https://github.com/flutter/flutter/issues/110016 for context.

#### `flutter_frontend_server`

- [ ] `flutter_frontend_server`: migrate `bin/starter.dart:5:// @dart=2.8` & `lib/server.dart:7:// @dart=2.8`, currently blocked on: https://github.com/dart-lang/sdk/issues/49212, https://github.com/flutter/engine/pull/36417

#### `testing`

- [x] migrate `testing/symbols` to null safety: https://github.com/flutter/engine/pull/35809

#### `tools`

- [x] migrate `tools/licenses` to null safety: https://github.com/flutter/engine/pull/35882

#### `shell/platform/fuchsia` + `lib`
 
- [x] migrate `.../dart-pkg/fuchsia` to null safety: https://github.com/flutter/engine/pull/36303
- [x] migrate `.../dart_runner/embedder` to null safety: https://github.com/flutter/engine/pull/36303
- [x] migrate `.../dart_runner/vmservice` to null safety: https://github.com/flutter/engine/pull/36303
- [x] migrate `.../flutter/kernel` to null safety: https://github.com/flutter/engine/pull/36303
- [x] migrate `.../runtime/dart/profiler_symbols` to null safety: https://github.com/flutter/engine/pull/36154
- [x] migrate file exclusions:
  - `.../dart/compiler.dart:5:// @dart = 2.9`
  - `.../runtime/dart/profiler_symbols/dart_profiler_symbols.dart:5:// @dart = 2.9`
- [x] discontinue:
  -  `.../flutter/kernel/extract_far.dart:5:// @dart = 2.9`: https://github.com/flutter/engine/pull/35801
- [x] migrate `lib/snapshot` to null safety  (template used on the fuchsia platform): https://github.com/flutter/engine/pull/36378

**Comment by mit-mit** [comment]
@zanderso about the stuff under `shell/platform/fuchsia/`: I took a look with the goal of migrating it, but it's not ordinary Dart packages (there are no pubspecs), so not sure how it works. Can someone from the engine team take a look at it?

**Comment by zanderso** [comment]
@akbiggs are the Fuchsia scripts noted above still in use?

**Comment by akbiggs** [comment]
- `compiler.dart`: looks to be used to compile third_party dart pkgs for fuchsia ([compiler.dart is compiled as kernel_compiler](https://github.com/flutter/engine/blob/main/shell/platform/fuchsia/dart/BUILD.gn#L8), [kernel_compiler is used to compile dart binaries](https://github.com/flutter/engine/blob/main/shell/platform/fuchsia/BUILD.gn#L41)). I don't understand this dependency exactly but it does seem to be used. I think we should migrate it to null safety.
- `extract_far.dart`: I can't find anything referencing this in the engine, framework, fuchsia.git, infra for engine, or google3. Looking at [its history](https://github.com/flutter/engine/commits/main/shell/platform/fuchsia/flutter/kernel/extract_far.dart) it seems like it might have been just ported over from wherever this code used to live, so I think it is safe to remove. @chinmaygarde and @chaselatta FYI
- `dart_profiler_symbols.dart`: The output from this script looks to be used ([example](https://github.com/flutter/engine/blob/f3a6ee97f784e98b0f841e9fe7445bf4dac431c4/shell/platform/fuchsia/dart_runner/BUILD.gn#L195)). I think we should migrate it to null safety.

**Comment by chinmaygarde** [comment]
From Triage: The Flutter frontend server migration is blocked on updating `package:frontend_server/frontend_server.dart`.

**Comment by mit-mit** [comment]
The Fuchsia related work is now tracked in https://bugs.fuchsia.dev/p/fuchsia/issues/detail?id=108575

**Comment by khyati82** [comment]
The only thing pending here is Flutter frontend server migration which is currently being tracked via  https://github.com/dart-lang/sdk/issues/49212

**Comment by devoncarew** [comment]
> The only thing pending here is Flutter frontend server migration which is currently being tracked via [dart-lang/sdk#49212](https://github.com/dart-lang/sdk/issues/49212)

Ah, there is still a bunch of work here, but the flutter frontend server portion is blocked on that dart issue (which is being worked on).

**Comment by mit-mit** [comment]
All done 🥳

**Comment by mit-mit** [comment]
@zanderso did this get landed again?

**Comment by a-siva** [comment]
Yes the PR to make flutter frontend server null safe landed here https://github.com/flutter/engine/pull/36482.

Closing this issue.
