### ISSUE TITLE
API `/api/push-build-status-to-github` is failing due to bigquery permission issue

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#110060]
API `/api/push-build-status-to-github` is complaining bigquery permission error. This is blocking tree status collection.

```
Failed to add to BigQuery: DetailedApiRequestError(status: 403, message: Access Denied: Table flutter-dashboard:cocoon.BuildStatus: Permission bigquery.tables.get denied on table flutter-dashboard:cocoon.BuildStatus (or it may not exist).)
```

This should be related to the recent latchkey enforcement.

/cc @drewroengoogle

**Comment by keyonghan** [comment]
Seems we need editor role: https://cloud.google.com/bigquery/docs/access-control

**Comment by drewroengoogle** [comment]
@keyonghan Do you know what account needs the editor permission?

**Comment by drewroengoogle** [comment]
@sealesj Has submitted a CL to add the BigQuery Data Editor role to flutter-dashboard@

**Comment by keyonghan** [comment]
Thanks for the quick fix. Now it went through and tree status is getting back.
