### ISSUE TITLE
Make Flutter repos sound null safe

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter#110016]
This is a companion issue to https://github.com/dart-lang/sdk/issues/49169; this tracks making the various `flutter/` github repos sound null safe. This means the code both needs to be converted to a min. SDK dep of Dart 2.12, and, not exclude any files from null safety (i.e., via a language tag in the file).

This issue is meant to track the remaining tech debt towards getting the repos sound null safe (i.e., tests which were excluded from null safety during an initial conversion, ...). Exclusions which are intentional - for example, exclusions to specifically test the behavior of pre-null-safe code - aren't meant to be tracked as part of this issue.

### Repos

- [x] flutter/samples - no exclusions
- [x] flutter/website - no exclusions
- [x] flutter/codelabs - no exclusions
- [x] #110024
- [x] flutter/flutter#110017
- [x] flutter/gallery#752
- [x] flutter/devtools#4399
- [x] https://github.com/flutter/flutter/issues/110021
- [x] https://github.com/flutter/flutter/issues/71511
- [x] #110020

**Comment by devoncarew** [comment]
cc @mit-mit for fyi

**Comment by stuartmorgan** [comment]
> * flutter/packages - no exclusions

`fuchsia_ctl` has a bunch of tests with Dart 2.4 tags, and neither `imitation_game` or `web_benchmarks` has ever been converted (they use pre-2.12 constraints).

**Comment by devoncarew** [comment]
Ah, thanks. This search just looked for `// @dart = ` 2.8, 2.9, 2.10, and 2.11.

**Comment by mit-mit** [comment]
>  Exclusions which are intentional - for example, exclusions to specifically test the behavior of pre-null-safe code - aren't meant to be tracked as part of this issue.

@devoncarew where are we tracking those then? For example https://github.com/flutter/flutter/issues/110021 has only that category left.

**Comment by devoncarew** [comment]
> where are we tracking those then?

We aren't explicitly, but if you see the very end of the first comment here: https://github.com/dart-lang/sdk/issues/49169

We are asking people to annotate those types of exclusions with a special comment that we can grep for (`'// null_safety_optout_testing'`). That'll make identifying and removing all those locations a fairly time-boxed exercise.

**Comment by devoncarew** [comment]
From looking around, it doesn't look like we've used `null_safety_optout_testing` in any other repos. I suspect when we're ready to remove the intentional exclusions, we'll need to perform another git grep of the various repos.

**Comment by mit-mit** [comment]
OK, that makes sense: let's remove all known uses, and then see what's left.

**Comment by mit-mit** [comment]
All done 🥳

**Comment by mit-mit** [comment]
Reopening as https://github.com/flutter/flutter/issues/110020 was reopened
