### ISSUE TITLE
Document about CI/CD with Xcode Cloud potentially outdated due to some changes from Apple?

### ISSUE THREAD

**Issue by hayyyyyyden** [flutter/flutter#110058]
Hi, I'm new to flutter, just want to explore the CI/CD options in flutter and found out that, the [post clone script for Xcode cloud ](https://docs.flutter.dev/deployment/cd#post-clone-script)in the official document seemed not working anymore.

I copied the script here as well.

```
#!/bin/sh

# The default execution directory of this script is the ci_scripts directory.
cd $CI_WORKSPACE # change working directory to the root of your cloned repo.

# Install Flutter using git.
git clone https://github.com/flutter/flutter.git --depth 1 -b stable $HOME/flutter
export PATH="$PATH:$HOME/flutter/bin"

# Install Flutter artifacts for iOS (--ios), or macOS (--macos) platforms.
flutter precache --ios

# Install Flutter dependencies.
flutter pub get

# Install CocoaPods using Homebrew.
HOMEBREW_NO_AUTO_UPDATE=1 # disable homebrew's automatic updates.
brew install cocoapods

# Install CocoaPods dependencies.
cd ios && pod install # run `pod install` in the `ios` directory.

exit 0
```

Specifically, the last command `pod install` not working, saying `[!] No Podfile found in the project directory` in the Xcode cloud server.

I changed the script to something like these, it now worked, but not sure what is the root cause of this.

```
#!/bin/sh

# The default execution directory of this script is the ci_scripts directory.
cd $CI_WORKSPACE # change working directory to the root of your cloned repo.

# Install CocoaPods using Homebrew.
HOMEBREW_NO_AUTO_UPDATE=1 # disable homebrew's automatic updates.

# Install CocoaPods using Homebrew.
brew install cocoapods

# Install Flutter
git clone https://github.com/flutter/flutter.git --depth 1 -b stable $HOME/flutter
export PATH="$PATH:$HOME/flutter/bin"

# Install Flutter artifacts for iOS (--ios)
flutter precache --ios

# Install Flutter dependencies.
flutter pub get

# Build ios app
flutter build ios --no-codesign

exit 0
```

**Reproduce Steps:** Just follow the official document to create a new flutter project and create a workflow for Xcode Cloud.

**Expected:** The Xcode cloud will work.

**Actual Results:** The Xcode Cloud server log `[!] No Podfile found in the project directory.` and failed.

**Comment by huycozy** [comment]
Hi @hayyyyyyden, thanks for filing the issue.
I tried reproducing the issue from my side. The build is successful with the script provided in https://docs.flutter.dev/deployment/cd#custom-build-script even though there was a warning:

> Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
[!] No `Podfile' found in the project directory.

Could you please provide the full logs that contain failed messages?
