### ISSUE TITLE
Include error message in crash reports

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#11008]
We just need to add an `error_message` field [here](https://github.com/flutter/flutter/blob/3ef9909237166c0a2ec9fe2e788b0e30669216ed/packages/flutter_tools/lib/src/crash_reporting.dart#L93)

**Comment by tvolkert** [comment]
https://github.com/flutter/flutter/wiki/Flutter-CLI-crash-reporting has been updated to reflect that we capture this.

**Comment by timsneath** [comment]
Looks like this is fixed, @tvolkert? See https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/reporting/crash_reporting.dart#L110

**Comment by tvolkert** [comment]
Yep.
