### ISSUE TITLE
Accent popup doesn't appear at correct location if TextField is contained inside a scaled InteractiveViewer (macOS)

### ISSUE THREAD

**Issue by KevinBrendel** [flutter/flutter#110068]
## Steps to Reproduce

1. Execute `flutter run` on the code sample as a macOS app 
2. Focus TextField
3. Long press a letter with accents (e.g. "e") and observe that the Popup appears on the correct location
4. Scale the InteractiveViewer by scrolling anywhere on the screen (don't pinch to zoom, as Flutter doesn't support trackpad gestures properly yet)
5. Long press a letter with accents (e.g. "e") and observe that the Popup appears at the bottom left of the screen.

**Expected results:** 
The popup shows up at the correct location over the typed letter as long as the letter is visible on the screen. If the letter is not visible, the popup should at least show up somewhere inside of the Flutter window where users are more likely to find it.

**Actual results:** 
The popup always shows up at the bottom left of the screen, even if the TextField is fully visible. This can even lead to the popup being outside the Flutter window.

<details>
<summary>Code Sample</summary>

```dart

import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: InteractiveViewer(
            child: Container(
          color: Colors.white,
          child: const Center(
            child: SizedBox(
              width: 400,
              height: 200,
              child: TextField(),
            ),
          ),
        )),
      ),
    );
  }
}

```

</details>

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.5.1 21G83 darwin-arm, locale en-DE)
    • Flutter version 3.0.5 at /Users/kevin/SDKs/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (6 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/kevin/Library/Android/sdk
    • Platform android-32, build-tools 32.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.70.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.46.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.5.1 21G83 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 104.0.5112.101

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

### Correct Positioning
<img width="575" alt="image" src="https://user-images.githubusercontent.com/55455206/186119412-9b79c972-ef36-48b9-9435-35270174acf3.png">

### Wrong Positioning
<img width="411" alt="Screenshot 2022-08-23 at 11 10 04" src="https://user-images.githubusercontent.com/55455206/186119556-d999c18a-a2e8-4a1c-a986-51dcb4e0e70c.png">

**Comment by maheshmnj** [comment]
Hi @KevinBrendel,

There is a similar issue describing this case https://github.com/flutter/flutter/issues/101222, Please follow up there for further updates, Closing this issue as a duplicate. If you disagree feel free to write in the comments and we will reopen it.

Thank you.

**Comment by KevinBrendel** [comment]
@maheshmnj I am not convinced #101222 is the same issue. The issue there appears to be on the web, whereas the behavior I am experiencing here occurs on macOS, whereas in Chrome, the accent popup actually shows up at nearly the correct place, even if the InteractiveViewer is transformed.

<img width="1212" alt="Screenshot 2022-08-23 at 13 01 52" src="https://user-images.githubusercontent.com/55455206/186142190-cf7b39a4-440c-48b4-babb-c70582fe80a2.png">

**Comment by janiselfert** [comment]
This problem also seems to apply to the Emoji & Symbols Panel on macOS. It will not open at the correct location, if the InteractiveViewer is scaled.

Unscaled IV
![b0](https://user-images.githubusercontent.com/58039295/188166863-676fa4d1-c7c5-45fe-b8e6-15d5337b4436.jpg)

Scaled IV
![b1](https://user-images.githubusercontent.com/58039295/188166931-ec3b9a58-98f0-4b81-a3bf-8de6dbb97629.jpg)

**Comment by maheshmnj** [comment]
@KevinBrendel Please refer this issue https://github.com/flutter/flutter/issues/110010
