### ISSUE TITLE
Explain when you should use saveLayer with a CustomPainter

### ISSUE THREAD

**Issue by robertgirschick** [flutter/flutter#11002]
Drawing with a `BlendMode` unfortunately doesn't give the expected results. In the following case the source `Rect` should be gone and the dest `Rect` (the red one) should be cut out in the bottom right corner. Instead the source `Rect` just gets black.

```dart
class TestPaint extends CustomPainter {
	@override
	void paint(Canvas canvas, Size size) {
		canvas.drawPaint(new Paint()..color = Colors.transparent);
		canvas.drawRect(
			new Rect.fromLTWH(50.0, 100.0, 200.0, 200.0),
			new Paint()..color = Colors.red
		);
		canvas.drawRect(
			new Rect.fromLTWH(150.0, 200.0, 200.0, 200.0),
			new Paint()..color = Colors.white
				..blendMode = BlendMode.dstOut
		);
	}
}
```
![screenshot_20170627-222813](https://user-images.githubusercontent.com/11800804/27608852-428df620-5b89-11e7-91ca-cf3ac829e7f3.png)

It doesn't depend on the color of the second `Rect`. Other `BlendMode`s like `srcIn` or `dstIn` don't seem to work either. Is this a bug?

**Comment by eseidelGoogle** [comment]
@HansMuller or @Hixie would know.

**Comment by Hixie** [comment]
@chinmaygarde or @abarth are more likely to know. Blend modes are dark magic to me.

**Comment by abarth** [comment]
Blend modes that depend on the contents of the dst buffer will depend on how the scene is composited.  For example, what draws the yellow rectangle?  Is that part of the dst buffer for this custom painter?  The answer seems likely to depend on the compositing strategy.

**Comment by robertgirschick** [comment]
The yellow rectangle comes from an other underlying widget. `TestPaint` is a child to that widget. It was my understanding that in this case the two canvases are independent from each other, are they not?

So in the dst buffer for the custom painter there's nothing more than the transparent background (although it doesn't alter the outcome if it's there or not) and the two rectangles. That's why I don't understand where the black color can possibly come from.

**Comment by abarth** [comment]
> It was my understanding that in this case the two canvases are independent from each other, are they not?

Whether the two canvases are independent depends on the compositing strategy.  One way to think about a compositing strategy is as a plan for which canvases are independent from each other (and therefore can be recomposited in a different way at a later point in time).

> That's why I don't understand where the black color can possibly come from.

I suspect the canvas contains the yellow color from the parent widget.  The painting operation changes that to transparent, revealing the black that is composited behind these widgets in a separate canvas.

**Comment by robertgirschick** [comment]
I don't think the canvas is passed to the child. To figure this out I created two CustomPaints with a circle on each of the two canvases. If I skew the second canvas, only the second circle is distorted. So the second canvas seems to be independent (at least when skewing).

Is it possible that this BlendMode problem has to do with this issue #9627? It's mentioned there that the standard clear color is not transparent but black:

`canvas->clear(SK_ColorBLACK);`

So when applying a `dstOut` filter a certain region gets cleared in the process (the cut-out corner in the red rectangle), but instead of getting cleared to transparent, it gets the standard clear color black?

**Comment by Hixie** [comment]
Skew just changes the current transformation matrix for subsequent commands, so that is as expected.

**Comment by robertgirschick** [comment]
Okay, then skewing is different.

But the question remains: Is there a way to have a clean and independent transparent `CustomPainter` canvas? In classic Android, this is the standard behavior. When I add a custom `View` to a `Layout`, the `View` canvas is perfectly independent from its parent (via overriding `onDraw`).

**Comment by Hixie** [comment]
I believe that's what saveLayer gives you.

**Comment by Hixie** [comment]
I'm going to reopen this and use it to track making sure the documentation is clear on this point.

I want to update at least: CustomPaint, CustomPainter, Canvas

**Comment by imaNNeoFighT** [comment]
Hi, any news on this issue?

**Comment by Hixie** [comment]
@imaNNeoFighT how is https://api.flutter.dev/flutter/dart-ui/Canvas/saveLayer.html ?

**Comment by imaNNeoFighT** [comment]
@Hixie 
I've tried to solve @robertgirschick's sample by saveLayer(), but it didn't work, maybe I don't know how I should use it.
Could you please show me an example?

**Comment by mockturtl** [comment]
> how is https://api.flutter.dev/flutter/dart-ui/Canvas/saveLayer.html ?

Frustrating. :smile: It takes some trial and error to figure out whether "nothing happened" is the result of painting white on white, or getting the size and offsets wrong.  The nuances of anti-aliasing seem like they should be secondary to more basic examples.

**Comment by markusaksli-nc** [comment]
Leaving this open since [CustomPaint](https://api.flutter.dev/flutter/widgets/CustomPaint-class.html) still doesn't seem to have a reference to [saveLayer docs](https://api.flutter.dev/flutter/dart-ui/Canvas/saveLayer.html). This seems fixed for [CustomPainter](https://api.flutter.dev/flutter/rendering/CustomPainter/paint.html) and [BlendMode](https://api.flutter.dev/flutter/dart-ui/BlendMode-class.html).

**Comment by danagbemava-nc** [comment]
Updating the labels since the [CustomPaint](https://master-api.flutter.dev/flutter/widgets/CustomPaint-class.html) class doesn't seem to have a reference to [saveLayer docs](https://api.flutter.dev/flutter/dart-ui/Canvas/saveLayer.html)
