### ISSUE TITLE
[Google Maps Flutter] iOS Marker Error - Unable to interpret bytes as a valid image 

### ISSUE THREAD

**Issue by abeticlairon** [flutter/flutter#110120]
My app crashes when opening a GoogleMap widget on iOS but it works perfectly on Android. The issue comes from the map markers. The error message is 'Unable to interpret bytes as a valid image'. I tried tweaking the code as much as I can but without success.

Here is the steps I took:

```dart
Future<Uint8List> getBytesFromAsset(String path, int width) async {
  ByteData data = await rootBundle.load(path);
  ui.Codec codec = await ui.instantiateImageCodec(data.buffer.asUint8List(), targetWidth: width);
  ui.FrameInfo fi = await codec.getNextFrame();
  return (await fi.image.toByteData(format: ui.ImageByteFormat.png)).buffer.asUint8List();
}

Future<BitmapDescriptor> getBitmapDescriptorFromAssetBytes(String path, int width) async {
  final Uint8List imageData = await getBytesFromAsset(path, width);
  return BitmapDescriptor.fromBytes(imageData);
}
```

**Comment by danagbemava-nc** [comment]
Hi @abeticlairon, please provide the version of `google_maps_flutter` you're using as well as the output of `flutter doctor -v`.

Please also provide a complete minimal reproducible code sample (preferably in a repo we can clone) along with the output of `flutter run -v` that captures the exception you're facing. 

Thank you
