### ISSUE TITLE
Allow web Chrome tests to run on arm64 Macs

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#110113]
To take advantage of increasing LUCI Apple Silicon Mac bots capacity, web Chrome tests should be runnable on Mac arm64 hosts.

These tests are failing because there is no arm64 Chrome cipd package available:
```
  failed to resolve flutter_internal/browsers/chrome/mac-arm64@version:98.1 (line 1): no such package: flutter_internal/browsers/chrome/mac-arm64
```
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8805103520674940097/+/u/Chrome_and_driver_dependency/ensure_installed/stdout

Available packages:
https://chrome-infra-packages.appspot.com/p/flutter_internal/browsers/chrome/

Context at https://github.com/flutter/flutter/pull/109889#issuecomment-1221159698

**Comment by jmagman** [comment]
@ditman @yjbanov

**Comment by ditman** [comment]
This shouldn't be too hard! The worst bit (most tedious?) is the testing to verify that the bundle that we upload to CIPD is what we *want* (I don't know if there's a CIPD staging that we can mess up with!). This is the script that currently uploads stuff to CIPD:

* https://github.com/flutter/engine/blob/main/lib/web_ui/dev/browser_roller.dart

We might be able to add a new MacArmPlatformBinding (similar to https://github.com/flutter/engine/blob/main/lib/web_ui/dev/common.dart#L142-L190), and configure it to pull the files from here: 

https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Mac_Arm/

There's also a browser lock file that might need adding a new browser entry to:

* https://github.com/flutter/engine/blob/main/lib/web_ui/dev/browser_lock.yaml

(We probably need to specify the architecture within the browser, so we can have separate build IDs for "chrome.Mac.amd64" and "chrome.Mac.arm64", but we could just add a MacArm to Chrome to simplify stuff)

**Comment by eyebrowsoffire** [comment]
I'm already partway through a fix for this some of my work. Assigning myself.

**Comment by ditman** [comment]
@eyebrowsoffire awesome, thanks! I was going to take this on friday for a 20% hack, but if you're getting it done go for it! I can review the changes to the script if you want.

Cheers!

**Comment by jmagman** [comment]
Framework web tests passing on an arm Mac:
https://ci.chromium.org/p/flutter/builders/try/Mac%20web_tool_tests/19711?
Thanks!

**Comment by jmagman** [comment]
Now that we have more arm Mac capacity I tried to run these web tests again and I'm seeing the same tag issue again: 
https://ci.chromium.org/p/flutter/builders/try/Mac%20tool_integration_tests_1_4/19251

**Comment by ditman** [comment]
```
failed to resolve flutter_internal/browsers/chrome/mac-arm64@version:98.1 (line 1): no such tag
```

I can only see `version:105.0`, `version:107.0` and `version:110.0` for `mac-arm64` in CIPD. [Link](https://chrome-infra-packages.appspot.com/p/flutter_internal/browsers/chrome/mac-arm64/+/)?

**Comment by jmagman** [comment]
Does the .ci.yaml need to be updated to 110.0 manually?
https://github.com/flutter/flutter/blob/2ecf4ae962eab2f0063220b8b0edcc284167ad27/.ci.yaml#L108

**Comment by jmagman** [comment]
> Does the .ci.yaml need to be updated to 110.0 manually?

That tag worked when I tried it my PR https://github.com/flutter/flutter/pull/119762/files#diff-9e73abde9fff445f31e5928e80d2d3f88847e02fd8f76d46f66f147fdc82786dR3088

https://ci.chromium.org/p/flutter/builders/try/Mac%20tool_integration_tests_1_4/19255?

Is something supposed to be rolling this number?  Where did the arm 98.1 tag go?

**Comment by ditman** [comment]
> Is something supposed to be rolling this number?

It needs to be done [manually](https://github.com/flutter/engine/tree/main/lib/web_ui#ciyaml) after rolling a new version of the browser into CIPD.

> Where did the arm 98.1 tag go?

`mac-arm64` is our most recent architecture, and AFAIK it has been used to test test/verify dart2wasm stuff (@eyebrowsoffire has the full scoop on this), so it's very likely that Chrome 98 for mac-arm64 never supported enough of wasm-GC to be usable for us in automation (so it might have never been rolled to CIPD. Compare to <tt>mac-**amd64**</tt> which has versions that are 2 years old, here's [98.1](https://chrome-infra-packages.appspot.com/p/flutter_internal/browser-drivers/chrome/mac-amd64/+/GWrKN5sro6F8VDVrKcRw-Rn420E1MWklg69rnKq7ydUC)).

(Also, looking at that 98.1 roll of Chrome; it happened 11 months ago, and I think that vastly predates our work to run tests in `mac-arm64`? @jmagman you probably know the dates better than I do!)

**Comment by ditman** [comment]
Looking at the build that passed [here](https://github.com/flutter/flutter/issues/110113#issuecomment-1256632741), CIPD logs say:

```json
      {
        "instance_id": "9m6ZAVJkzdvZwIgVrn0eJTUIZ_WlRmv56Xdm3WIm3qgC", 
        "package": "flutter_internal/browser-drivers/chrome/mac-arm64"
      }
```

and

```json
      {
        "instance_id": "i4wNi2SqzrtfcQHISIaP-lRdYr-JCk46wREF0Gnzb9QC", 
        "package": "flutter_internal/browsers/chrome/mac-arm64"
      }
```

They should be these links:

* https://chrome-infra-packages.appspot.com/p/flutter_internal/browser-drivers/chrome/mac-arm64/+/9m6ZAVJkzdvZwIgVrn0eJTUIZ_WlRmv56Xdm3WIm3qgC (version:105)
* https://chrome-infra-packages.appspot.com/p/flutter_internal/browsers/chrome/mac-arm64/+/i4wNi2SqzrtfcQHISIaP-lRdYr-JCk46wREF0Gnzb9QC (version:105)

**Comment by jmagman** [comment]
Okay, as long as something isn't mysteriously deleting old tags.  

If ya'll are okay with me bumping the framework test version to 110.0 (the tests passed in presubmit), then once https://github.com/flutter/flutter/pull/119762 merges and looks happy in CI I will put out a PR for just this part: https://github.com/flutter/flutter/pull/119762/commits/849b336892ebfa6672cbb885e36a26e3dfe17534

**Comment by eyebrowsoffire** [comment]
Bumping the framework tests to 110.0 works for us. The engine unit tests need a very bleeding edge version of Chrome due to the quickly changing nature of WasmGC support in the browser. We'll probably be making another bump to Chrome 111 around February 9 when it enters Chrome's beta release channel. For future reference, when we do a version bump for the engine, should we try to bump the framework versions too while we're at it? I've mostly been leaving those versions alone until now.

**Comment by ditman** [comment]
@jmagman 110 is the version that we use for the engine testing:

https://github.com/flutter/engine/blob/edba2d078dd62e797fae875a81c096e128088911/lib/web_ui/dev/browser_lock.yaml#L16-L20

So I don't think there's any problem in you bumping that .ci.yaml file.

**Comment by ditman** [comment]
> For future reference, when we do a version bump for the engine, should we try to bump the framework versions too while we're at it? I've mostly been leaving those versions alone until now.

@eyebrowsoffire IMO we should run the framework tests in the same version as the engine ones.

(I also think that we should run the tests in the "older browser we support", but that's another story altogether :P)
