### ISSUE TITLE
expose image encoding in dart

### ISSUE THREAD

**Issue by pedia** [flutter/flutter#11016]
Image encoding is very important feature, since these functions already exists in C++ code, just expose them.

**Comment by majido** [comment]
I ended up needing this functionality for my toy project. I spend sometime looking undercover
in Skia and ended up patching the flutter engine to expose this to dart. Here is my [patch](https://github.com/majido/engine/compare/master...majido:support_image_encoding).

What works (essentially what I needed):
- Encoding to JPEG at highest quality
- Encoding happens at IO thread

Still need working:
 - Supporting other formats and quality settings.
 - Adding tracing.

Both above are simple to do but I didn't need it for my usecase. If there is interest I 
am happy to do above an upstream it.
