### ISSUE TITLE
Implement Transactions for Firebase Database

### ISSUE THREAD

**Issue by zhangandyx** [flutter/flutter#11012]
## Steps to Reproduce

`database.ref('someRef').transaction` isn't currently implemented.

## Logs

Run your application with `flutter run` and attach all the log output.

Run `flutter analyze` and attach any output of that command also.

## Flutter Doctor

Paste the output of running `flutter doctor` here.

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by Hixie** [comment]
@collinjackson, @mit-mit: Is this something we can work on in the nearish future?

**Comment by mit-mit** [comment]
Yes, would be good to add. @collinjackson ?

**Comment by sethladd** [comment]
We spoke last week with @goderbauer and @kroikie , and @kroikie mentioned he was going to take a look.

**Comment by kroikie** [comment]
[PR](https://github.com/flutter/plugins/pull/199) that implements transaction support. Should be merged in soon.

**Comment by Hixie** [comment]
@kroikie @collinjackson Is this fixed now? The PR mentioned above has landed.

**Comment by sethladd** [comment]
Closing optimistically :)

Thanks to @kroikie and @collinjackson !

**Comment by bradintheusa** [comment]
Does anyone have an example on how to use this?

**Comment by kroikie** [comment]
Hi @bradintheusa have a look at the [example](https://github.com/flutter/plugins/blob/master/packages/firebase_database/example/lib/main.dart#L105) in the firebase_database plugin.

**Comment by bradintheusa** [comment]
Much appreciated,   I was missing the `async `keyword.

**Comment by kroikie** [comment]
@zhangandyx

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/987. Any further collaboration will be done there.
