### ISSUE TITLE
Build failing across the board with infra failure: 'Install gems.mkdir gems'

### ISSUE THREAD

**Issue by darrenaustin** [flutter/flutter#110112]
The build just went red across the board with:

```
[E2022-08-23T13:10:42.436031-07:00 1917 0 application.go:140] fatal error: Bundled Python 3.8 not found. Use VPYTHON_BYPASS if prebuilt cpython not available on this platform: open /opt/s/w/ir/x/w/recipe_cleanup/tmpe7bweake/vpython/3.8/.versions/cpython3.cipd_version: no such file or directory
```

https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8805009880589844977/+/u/Install_gems/mkdir_gems/stdout

**Comment by keyonghan** [comment]
Seems there is a new vpython version pushed 2 hours ago:
https://chrome-infra-packages.appspot.com/p/infra/tools/luci/vpython/mac-amd64/+/

**Comment by keyonghan** [comment]
We have been using `latest` version for vpython, and we should pin a specific version.
https://flutter-review.googlesource.com/c/recipes/+/32820 to pin on the latest workable version.

**Comment by keyonghan** [comment]
Recipes CL landed, and re-ran failed builds. We should get back to green soon.

**Comment by keyonghan** [comment]
Issue resolved.
