### ISSUE TITLE
Flutter integration test- I want to fetch testwidget test status whether passed or failed so that i could further use that test status in my custom reports

### ISSUE THREAD

**Issue by amitkumar-qa** [flutter/flutter#110151]
Ex code:

```
group('e2e test', () {
    testWidgets('Home Page-Verify user can switch location',
        (WidgetTester tester) async {
          homeRobot = HomeRobot(tester);
          await commonHelper.runApp(tester);
          await commonHelper.userLogin(
              TestData.agencyUserEmail, TestData.agencyUserPass, tester);
          await homeRobot.setLocation(TestData.location);
    }); })
```

In above testWidgets test ---i need to get test status once above test complete, after completion , it will be passed or failed or skipped, i need that status so that i could use further in my custom reporting or may be in further use.
Please assist.

Cheers
Am

**Comment by darshankawar** [comment]
@amitkumar-qa 
Your question is better suited for support channels like StackOverflow, so please ask the same there.
Closing from here, as this is more of a code assistance question rather than a bug or feature request.
