### ISSUE TITLE
[pigeon] Flake in new "deduces package name" test

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#110109]
Hit in CI just now (https://github.com/flutter/packages/pull/2486/checks?check_run_id=7981538549):

```
00:07 +35 -1 : test/dart_generator_test.dart: deduces package name 
[E]
  FileSystemException: Deletion failed, path = '/tmp/pigeonELTPFO' (OS Error: Directory not empty, errno = 39)
  dart:async  _CustomZone.runUnary
  This test failed after it had already completed. Make sure to use [expectAsync]
  or the [completes] matcher when testing async code.
  dart:async  _CustomZone.runUnary
```

**Comment by gaaclarke** [comment]
Hey @stuartmorgan, that link in the description is a passing test, do you have a link to a failing test?

**Comment by stuartmorgan** [comment]
It's passing because I re-ran it; you can click through from there to the older runs to get to  https://cirrus-ci.com/task/5426645837283328
