### ISSUE TITLE
Migrate content handler VulkanRasterizer to use mtl::DeviceWatcher

### ISSUE THREAD

**Issue by freiling** [flutter/flutter#11013]
Having our own implementation of the device watcher protocol broke silently when the protocol was updated, causing every flutter app to wait a full second before starting on fuchsia. Swetland recommends moving to an MTL standard implementation

See https://github.com/flutter/engine/blob/master/content_handler/vulkan_rasterizer.cc#L27

**Comment by abarth** [comment]
The use case is different.  mtl::DeviceWatcher is an async wait.  This code wants a sync wait.

**Comment by freiling** [comment]
To quote Brian Swetland: "If you don't mind a dependency on mxio, the mxio watcher can easily be used to build a synchronous wait (have a callback that returns ERR_STOP when the thing you're waiting for shows up).  It also supports timeouts."

Also I think its at least worth thinking about an architecture that allows you to wait asynchronously. right now this wait happens serially with 40 ms of RuntimeHolder::CreateView. I dont know how practical this is though.

**Comment by markusaksli-nc** [comment]
Is this issue still relevant?

**Comment by freiling** [comment]
I would say probably not but I defer to the other people on this issue

**Comment by jonahwilliams** [comment]
Closing as obsolete
