### ISSUE TITLE
TextField can not accept  "obscureText: true" and "maxLines: null" together!

### ISSUE THREAD

**Issue by alisinaee** [flutter/flutter#110165]
TextField(
      obscureText: true,
      maxLines: null,
      decoration: InputDecoration(
        border: OutlineInputBorder(),
        hintText: 'Enter a search term',
      ),
    );

its not working!
you have to rewrite it as :
TextField(
      obscureText: true,
      //maxLines: null,
      decoration: InputDecoration(
        border: OutlineInputBorder(),
        hintText: 'Enter a search term',
      ),
    );

 O __ O

**Comment by danagbemava-nc** [comment]
Hi @alisinaee, `obscureText: true` is usually meant to be used for password fields, which is why it was decided that they should not be multiline. 

What is your use case for wanting to use a multiline "password" field?

**Comment by alisinaee** [comment]
Hi , this is the point , I don't want multiline with obscure so I need to pass maxLines: null, to the TextField ( i have custom TextField widget with many options so i have to sett max line to null) but flutter wont let me !
logically its right to have both maxline:null and obscureText: true, in text input so they need to fix it,
I hope you understand what I mean. tnx btw

**Comment by danagbemava-nc** [comment]
Hi @alisinaee, can you share what your code for the custom textfield looks like? 

I believe you should be able to make those two work together without needing a change in the framework.

If the field is supposed to be multiline, you could just set obscureText to false for that particular field.
