### ISSUE TITLE
Changing TextEditingController Value is resetting keyboard

### ISSUE THREAD

**Issue by vishesh005** [flutter/flutter#110164]
After changing TextField Controller Values Keyboard is resetting.

Steps to replicate :

1.  Add TextEditingController to TextField Widget.
2. Inside onChanged or build method simply check if text is number.
3. If number is text then changed its value to any character (use **TextEditingController.value = value.copyWith** function).
4. Then write some text once you switched to number mode then if you type number, your keyboard will automatically switched to qwerty.

Note : I'm currently using Flutter version 2.5.

**Comment by vishesh005** [comment]
@danagbemava-nc  Android

**Comment by danagbemava-nc** [comment]
Please provide a complete minimal reproducible code sample without any third-party dependencies so that we can verify this issue. 

Thank you
