### ISSUE TITLE
Clean up vpython deps in flutter recipes

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#110116]
The `vpython` dep is included in $PATH by default, and there is no need for use to add the dependency on top of that.

https://flutter.googlesource.com/recipes/+/refs/heads/main/recipes/devicelab/devicelab_drone.py#86

**Comment by nehalvpatel** [comment]
Addressed with [this change](https://flutter-review.googlesource.com/c/recipes/+/32931).
