### ISSUE TITLE
Regression to scrolling smoothnes on iPhone X and above

### ISSUE THREAD

**Issue by Albert221** [flutter/flutter#110178]
We have encountered a smoothness issue with our production application. The scrolling feels not butter smooth on iPhone X and above devices.

I ran the same app in profile mode and both devices (iPhone 6 with smooth scroll and Xr with not-so-smooth) had UI and raster threads no longer than 17ms without any spikes. Also no big activity on other threads. It was purely visual, not visible in the Performance panel.

Our tester reports, that on the production app (Release mode, compiled on Flutter 3.0.0, downloaded through AppCenter) the lack of smoothness is really visible (like 15fps and not 60fps). He also reports that the problem is magically gone when he turns on the screen recording (just like #104376).

| Devices with smooth scroll | Devices with **not-so-smooth** scroll |
|-|-|
| iPhone 6 (iOS 13.5.1) | iPhone XR (iOS 15.5)<br>iPhone XR (iOS 16.0) |

**Related:**
* https://github.com/flutter/flutter/issues/104376
* https://github.com/flutter/flutter/issues/95838

---

I am attaching a small example and a slow-mo (240fps) comparison of iPhone XR (left) and 6 (right) running simple `ListView.builder` on Flutter 3.0.5. I am not sure if it's visible in such a small and lightweight example, but I'll attach it anyways.

https://user-images.githubusercontent.com/4085280/186602482-14a4af6e-68c9-4eda-b059-0f69c229138a.mp4

flutter doctor of movie above

```
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.4 21F79 darwin-arm, locale en-PL)
    • Flutter version 3.0.5 at /Users/albert/fvm/versions/3.0.5
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (6 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3
```

**Comment by Albert221** [comment]
I found that iPhones X and above start to have _Touch Sample Rate_ 120Hz as opposed to 60Hz for older devices. Maybe that's the issue?

![image](https://user-images.githubusercontent.com/4085280/186451578-4505e4aa-1b28-4610-936e-a36812422555.png)

https://developer.apple.com/library/archive/documentation/DeviceInformation/Reference/iOSDeviceCompatibility/Displays/Displays.html

**Comment by danagbemava-nc** [comment]
Hi @Albert221, is there a condition that triggers the "lack of smoothness" you're experiencing, or is it a constant thing? 

Also, can you check if https://github.com/flutter/flutter/issues/96381 is similar to what you're experiencing?
