### ISSUE TITLE
flutter_math_fork null check error

### ISSUE THREAD

**Issue by aelayyuu** [flutter/flutter#110251]
flutter_math_fork null error shown as bellow

/opt/hostedtoolcache/flutter/3.0.5-stable/x64/.pub-cache/hosted/pub.dartlang.org/flutter_math_fork-0.5.0/lib/src/widgets/selectable.dart:459:[24](https://github.com/aelayyuu/koel_player/runs/8012162938?check_suite_focus=true#step:6:25): Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/opt/hostedtoolcache/flutter/3.0.5-stable/x64/packages/flutter/lib/src/scheduler/binding.dart').
      SchedulerBinding.instance!.addPostFrameCallback((_) {
                       ^
/opt/hostedtoolcache/flutter/3.0.5-stable/x64/.pub-cache/hosted/pub.dartlang.org/flutter_math_fork-0.5.0/lib/src/widgets/selection/overlay_manager.dart:138:28: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/opt/hostedtoolcache/flutter/3.0.5-stable/x64/packages/flutter/lib/src/scheduler/binding.dart').
      if (SchedulerBinding.instance!.schedulerPhase ==
                           ^
/opt/hostedtoolcache/flutter/3.0.5-stable/x64/.pub-cache/hosted/pub.dartlang.org/flutter_math_fork-0.5.0/lib/src/widgets/selection/overlay_manager.dart:140:[26](https://github.com/aelayyuu/koel_player/runs/8012162938?check_suite_focus=true#step:6:27): Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/opt/hostedtoolcache/flutter/3.0.5-stable/x64/packages/flutter/lib/src/scheduler/binding.dart').
        SchedulerBinding.instance!
                         ^
/opt/hostedtoolcache/flutter/3.0.5-stable/x64/.pub-cache/hosted/pub.dartlang.org/flutter_math_fork-0.5.0/lib/src/widgets/selection/web_selection_manager.dart:119:24: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/opt/hostedtoolcache/flutter/3.0.5-stable/x64/packages/flutter/lib/src/scheduler/binding.dart').
      SchedulerBinding.instance!
                       ^
/opt/hostedtoolcache/flutter/3.0.5-stable/x64/.pub-cache/hosted/pub.dartlang.org/flutter_math_fork-0.5.0/lib/src/widgets/selection/overlay.dart:1[41](https://github.com/aelayyuu/koel_player/runs/8012162938?check_suite_focus=true#step:6:42):26: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/opt/hostedtoolcache/flutter/3.0.5-stable/x64/packages/flutter/lib/src/scheduler/binding.dart').
    if (SchedulerBinding.instance!.schedulerPhase ==
                         ^
/opt/hostedtoolcache/flutter/3.0.5-stable/x64/.pub-cache/hosted/pub.dartlang.org/flutter_math_fork-0.5.0/lib/src/widgets/selection/overlay.dart:1[43](https://github.com/aelayyuu/koel_player/runs/8012162938?check_suite_focus=true#step:6:44):24: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/opt/hostedtoolcache/flutter/3.0.5-stable/x64/packages/flutter/lib/src/scheduler/binding.dart').
      SchedulerBinding.instance!.addPostFrameCallback(_markNeedsBuild);
                       ^
/opt/hostedtoolcache/flutter/3.0.5-stable/x64/.pub-cache/hosted/pub.dartlang.org/flutter_math_fork-0.5.0/lib/src/widgets/selection/overlay.dart:193:26: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/opt/hostedtoolcache/flutter/3.0.5-stable/x64/packages/flutter/lib/src/scheduler/binding.dart').
    if (SchedulerBinding.instance!.schedulerPhase ==
                         ^
/opt/hostedtoolcache/flutter/3.0.5-stable/x64/.pub-cache/hosted/pub.dartlang.org/flutter_math_fork-0.5.0/lib/src/widgets/selection/overlay.dart:195:24: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/opt/hostedtoolcache/flutter/3.0.5-stable/x64/packages/flutter/lib/src/scheduler/binding.dart').
      SchedulerBinding.instance!.addPostFrameCallback(_markNeedsBuild);

**Comment by stuartmorgan** [comment]
Issues with third
