### ISSUE TITLE
Failed assertion: line 2888 pos 18: '_globalKeyRegistry.containsKey(key)': is not true.

### ISSUE THREAD

**Issue by sarkaramitabh300** [flutter/flutter#110252]
I am facing this issue, searched the entire app for the duplicate global key but was not found.

```
====================================================================================================

======== Exception caught by widgets library =======================================================
The following assertion was thrown while finalizing the widget tree:
'package:flutter/src/widgets/framework.dart': Failed assertion: line 2888 pos 18: '_globalKeyRegistry.containsKey(key)': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
      BuildOwner._debugVerifyIllFatedPopulation.<anonymous closure> (package:flutter/src/widgets/framework.dart:2888:18)
      BuildOwner._debugVerifyIllFatedPopulation (package:flutter/src/widgets/framework.dart:2913:6)
      BuildOwner.finalizeTree.<anonymous closure> (package:flutter/src/widgets/framework.dart:2936:11)
      BuildOwner.finalizeTree (package:flutter/src/widgets/framework.dart:3016:8)
      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:893:19)
      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1146:15)
      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1083:9)
     _invoke (dart:ui/hooks.dart:151:10)
     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308:5)
     _drawFrame (dart:ui/hooks.dart:115:31)
(elided 5 frames from class _AssertionError and dart:async)
====================================================================================================
```

**Comment by sarkaramitabh300** [comment]
Once more exception very similar to the earlier one
======== Exception caught by widgets library =======================================================
The following assertion was thrown while finalizing the widget tree:
Multiple widgets used the same GlobalKey.

The key [LabeledGlobalKey<ScaffoldMessengerState>#6a086 _checkscaffoldKey] was used by multiple widgets. The parents of those widgets were different widgets that both had the following description:
  MediaQuery(MediaQueryData(size: Size(480.0, 1018.7), devicePixelRatio: 1.5, textScaleFactor: 1.0, platformBrightness: Brightness.light, padding: EdgeInsets.zero, viewPadding: EdgeInsets.zero, viewInsets: EdgeInsets.zero, alwaysUse24HourFormat: false, accessibleNavigation: false, highContrast: false, disableAnimations: false, invertColors: false, boldText: false, navigationMode: traditional, gestureSettings: DeviceGestureSettings(touchSlop: 8.0), displayFeatures: []))
A GlobalKey can only be specified on one widget at a time in the widget tree.
When the exception was thrown, this was the stack: 
    BuildOwner._debugVerifyGlobalKeyReservation.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:flutter/src/widgets/framework.dart:2868:13)    _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:614:13)    BuildOwner._debugVerifyGlobalKeyReservation.<anonymous closure>.<anonymous closure> (package:flutter/src/widgets/framework.dart:2815:20)      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:614:13)      BuildOwner._debugVerifyGlobalKeyReservation.<anonymous closure> (package:flutter/src/widgets/framework.dart:2811:36)
     BuildOwner._debugVerifyGlobalKeyReservation (package:flutter/src/widgets/framework.dart:2876:6)      BuildOwner.finalizeTree.<anonymous closure> (package:flutter/src/widgets/framework.dart:2935:11)
      BuildOwner.finalizeTree (package:flutter/src/widgets/framework.dart:3016:8)
      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:893:19)
      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1146:15)
     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1083:9)
     _invoke (dart:ui/hooks.dart:151:10)
     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308:5)
     _drawFrame (dart:ui/hooks.dart:115:31)
(elided 3 frames from dart:async)

**Comment by exaby73** [comment]
Hi @sarkaramitabh300, please provide a [minimal, reproducible example][1] and the output of `flutter doctor -v` as well as `flutter run -v`.

[1]: https://stackoverflow.com/help/minimal-reproducible-example

**Comment by sarkaramitabh300** [comment]
Hi, I don't know how to reproduce this issue, it's occurring randomly when I use this app for a while, and then it keeps occurring on every screen.

 **flutter doctor -v**
[✓] Flutter (Channel stable, 3.0.1, on macOS 12.5.1 21G83 darwin-x64, locale en-GB)
    • Flutter version 3.0.1 at /Users/amitabhsarkar/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (4 months ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at //Users/amitabhsarkar/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • ANDROID_HOME = //Users/amitabhsarkar/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.69.2)
    • VS Code at /Users/amitabhsarkar/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.44.0

[✓] Connected device (3 available)
    • Mi A1 (mobile)  • 0060bd9e0804 • android-arm64  • Android 9 (API 28)
    • macOS (desktop) • macos        • darwin-x64     • macOS 12.5.1 21G83 darwin-x64
    • Chrome (web)    • chrome       • web-javascript • Google Chrome 104.0.5112.101

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

**flutter run -v**
                    ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
                    The following assertion was thrown while finalizing the widget tree:
                    Multiple widgets used the same GlobalKey.
                    The key [LabeledGlobalKey<ScaffoldMessengerState>#8bb92 _checkscaffoldKey] was used by multiple
                    widgets. The parents of those widgets were different widgets that both had the following
                    description:
                      MediaQuery(MediaQueryData(size: Size(360.0, 640.0), devicePixelRatio: 3.0, textScaleFactor: 1.0,
                    platformBrightness: Brightness.light, padding: EdgeInsets.zero, viewPadding: EdgeInsets.zero,
                    viewInsets: EdgeInsets.zero, alwaysUse24HourFormat: false, accessibleNavigation: false,
                    highContrast: false, disableAnimations: false, invertColors: false, boldText: false, navigationMode:
                    traditional, gestureSettings: DeviceGestureSettings(touchSlop: 8.0), displayFeatures: []))
                    A GlobalKey can only be specified on one widget at a time in the widget tree.
                    
                    When the exception was thrown, this was the stack:
                    #0      BuildOwner._debugVerifyGlobalKeyReservation.<anonymous closure>.<anonymous closure>.<anonymous closure>
                    (package:flutter/src/widgets/framework.dart:2868:13)
                    #1      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:614:13)
                    #2      BuildOwner._debugVerifyGlobalKeyReservation.<anonymous closure>.<anonymous closure>
(package:flutter/src/widgets/framework.dart:2815:20)
                    #3      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:614:13)
                    #4      BuildOwner._debugVerifyGlobalKeyReservation.<anonymous closure> (package:flutter/src/widgets/framework.dart:2811:36)
                    #5      BuildOwner._debugVerifyGlobalKeyReservation (package:flutter/src/widgets/framework.dart:2876:6)
                    #6      BuildOwner.finalizeTree.<anonymous closure> (package:flutter/src/widgets/framework.dart:2935:11)
                    #7      BuildOwner.finalizeTree (package:flutter/src/widgets/framework.dart:3016:8)
                    #8      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:893:19)
                    #9      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:370:5)
                    #10     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1146:15)
                    #11     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1083:9)
                    #12     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:997:5)
                    #16     _invoke (dart:ui/hooks.dart:151:10)
                    #17     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308:5)
                    #18     _drawFrame (dart:ui/hooks.dart:115:31)
                    (elided 3 frames from dart:async)
                    ════════════════════════════════════════════════════════════════════════════════════════════════════
[  +43 ms] 
           Another exception was thrown: Multiple widgets used the same GlobalKey.
[+4032 ms] 
                    Another exception was thrown: Multiple widgets used the same GlobalKey.
[  +37 ms] 
           Another exception was thrown: Multiple widgets used the same GlobalKey.
[  +25 ms] 
           Another exception was thrown: Multiple widgets used the same GlobalKey.
[  +31 ms] 
           Another exception was thrown: Multiple widgets used the same GlobalKey.
[  +43 ms] 
           Another exception was thrown: Multiple widgets used the same GlobalKey.
[  +28 ms] 
           Another exception was thrown: Multiple widgets used the same GlobalKey.
[  +30 ms] 
           Another exception was thrown: Multiple widgets used the same GlobalKey.
[  +62 ms] 
           Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 2888 pos 18:
'_globalKeyRegistry.containsKey(key)':
           is not true.
[+5541 ms] 
                    Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 2888 pos 18:
'_globalKeyRegistry.containsKey(key)':
                    is not true.

**Comment by exaby73** [comment]
Without a reproducible sample, we unfortunately cannot verify and investigate the issue. If you can try to replicate it in a new project, that would be great.
