### ISSUE TITLE
[iOS] long press to move cursor is moving improperly if content, when using multiline text input

### ISSUE THREAD

**Issue by Nitingadhiya** [flutter/flutter#110245]
Better overview, please look attached video
https://user-images.githubusercontent.com/7464953/186604100-58e17df6-cbab-4a19-8559-69760e070423.mp4

**Comment by huycozy** [comment]
Hi @Nitingadhiya 
Are you referring to the gray cursor?
There are 2 related issues here: #97506 and #89228. If you're referring to the gray pointer issue, I think #89228 is more relevant.
