### ISSUE TITLE
Firebase crashes for layout are kinda useless

### ISSUE THREAD

**Issue by JCKodel** [flutter/flutter#110282]
Using the Flutter Crashlytics plugin and having some devices with issues on layout (width or height overflow), Firebase shows us this:

![image](https://user-images.githubusercontent.com/379339/186757091-229008d7-cfcc-4f0c-85bf-ca1380186229.png)

But there is no information whatsoever what widget is to blame (that would be our code), making this issue hard to track and utterly useless.

**Comment by danagbemava-nc** [comment]
Hi @JCKodel, this seems like it should be reported in the [flutter_fire repo](https://github.com/firebase/flutterfire/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc). 

As such I'll be closing this issue. If you are redirected here from there, kindly leave a comment below and I will reopen this issue. 

Thank you
