### ISSUE TITLE
New File.create optional parameter causing Dart -> Engine roll failure

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#110238]
See the failures in https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20Host%20Engine/40643/overview

Looks like they're from: https://dart-review.googlesource.com/c/sdk/+/255482

@aam

**Comment by aam** [comment]
https://github.com/flutter/engine/pull/35691 should address the failure

**Comment by aam** [comment]
Manual roll with additional fix to DEPS file landed
