### ISSUE TITLE
Wrapping a Text in SizeTransition cuts off the bottom of iOS emoji

### ISSUE THREAD

**Issue by pcomans** [flutter/flutter#11027]
## Steps to Reproduce
1) Check out the sample code for the FriendlyChat CodeLab: https://codelabs.developers.google.com/codelabs/flutter/index.html#9

2) Build offline step step_5_finishing_touches and run it on an iOS device.
3) Post emoji and observe that the bottom get cut off. Weirdly enough, the bottom does not get cut off when you toggle Debug Paint. (see screenshots)

![img_0069](https://user-images.githubusercontent.com/311774/27666554-5bc4c204-5c29-11e7-9575-7646151a4963.PNG)
![img_0070](https://user-images.githubusercontent.com/311774/27666555-5bc5b178-5c29-11e7-9332-120af961940c.PNG)

4) To run an earlier version of the same app without animation, build step_3_displaying_messages.
5) Observe that the emoji appear as normal.

Basically the code is:
broken:
```
    return new SizeTransition(
      sizeFactor: new CurvedAnimation(
        parent: animationController,
        curve: Curves.easeOut
      ),
      axisAlignment: 0.0,
      child: new Container(
        margin: const EdgeInsets.symmetric(vertical: 10.0),
        child: new Row(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: <Widget>[
            new Container(
              margin: const EdgeInsets.only(right: 16.0),
              child: new CircleAvatar(child: new Text(_name[0])),
            ),
            new Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: <Widget>[
                new Text(_name, style: Theme.of(context).textTheme.subhead),
                new Container(
                  margin: const EdgeInsets.only(top: 5.0),
                  child: new Text(text),
                ),
              ],
            ),
          ],
        ),
      )
    );
```
Working:
```
    return new Container(
      margin: const EdgeInsets.symmetric(vertical: 10.0),
      child: new Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: <Widget>[
          new Container(
            margin: const EdgeInsets.only(right: 16.0),
            child: new CircleAvatar(child: new Text(_name[0])),
          ),
          new Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: <Widget>[
              new Text(_name, style: Theme.of(context).textTheme.subhead),
              new Container(
                margin: const EdgeInsets.only(top: 5.0),
                child: new Text(text),
              ),
            ],
          ),
        ],
      ),
    );
```

## Logs

None.

## Flutter Doctor

[✓] Flutter (on Mac OS X 10.12.5 16F73, locale en-US, channel unknown)
    • Flutter at /Users/philipp/code/flutter
    • Framework revision d36e2f6191 (7 days ago), 2017-06-21 15:09:10 -0700
    • Engine revision b0dee695ec
    • Tools Dart version 1.24.0-dev.6.7

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at /Users/philipp/Library/Android/sdk
    • Platform android-25, build-tools 25.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.3.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3.3, Build version 8E3004b
    • ios-deploy 1.9.1
    • CocoaPods version 1.3.0.beta.1

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Gradle version 3.2
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Ultimate Edition (version 2017.1.4)
    • Flutter plugin version 14.0
    • Dart plugin version 171.4694.29

**Comment by Hixie** [comment]
Closing on the assumption that this is resolved with libtxt since we haven't heard other reports; if it comes up again please don't hesitate to file a bug.

**Comment by kmcgill88** [comment]
@Hixie, I've ran into this on iOS as well, Android is fine.

```dart
 Text _text() {
    return Text("😱\nFailed to Load\n🤕",
        textScaleFactor: 3.0,
        textAlign: TextAlign.center,
        softWrap: true,
        style: TextStyle(
          fontWeight: FontWeight.w400,
          color: Colors.black,
        )
    );
  }
```

cuts off the bottom of the lower emoji.
<img width="333" alt="screen shot 2018-12-12 at 9 35 53 pm" src="https://user-images.githubusercontent.com/1992370/49914211-12bfc380-fe56-11e8-813e-4944f8571f92.png">

However changing the text to `"😱\nFailed to Load\n 🤕"`. (Mind the space before 🤕) and it renders as expected.

<img width="303" alt="screen shot 2018-12-12 at 9 41 17 pm" src="https://user-images.githubusercontent.com/1992370/49914398-b4471500-fe56-11e8-952f-c8581fe27a79.png">


[✓] Flutter (Channel beta, v1.0.0, on Mac OS X 10.14.1 18B75, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[!] iOS toolchain - develop for iOS devices (Xcode 10.1)
    ✗ libimobiledevice and ideviceinstaller are not installed. To install with Brew, run:
        brew update
        brew install --HEAD usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
[✓] Android Studio (version 3.2)
[✓] VS Code (version 1.29.1)
[✓] Connected device (2 available)

**Comment by zoechi** [comment]
@kmcgill88 would you mind creating a new issue with a link to this one?
