### ISSUE TITLE
stop checking in pubspec.lock to flutter/cocoon, instead exactly pin and roll with dependabot

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#110272]
Right now the pub dependencies in flutter/cocoon are constrained with ranges, but the pubspec.lock is checked in, effectively exactly pinning. There is no established process for updating the pubspec.lock, however.

A better system would be to exactly pin each dependency in pubspec.yaml, and then rely on dependabot to autoroll these to latest in PRs that run CI tests. This would allow us to keep dependencies up to date, but also ensure each particular commit has an exactly reproducible version solve.

Would have prevented https://github.com/flutter/flutter/issues/110265#issuecomment-1227475555

**Comment by christopherfujino** [comment]
It turns out that device_doctor is already in cocoon's dependabot config: https://github.com/flutter/cocoon/blob/main/.github/dependabot.yml#L32 and that dependabot already updated package:file in app_dart https://github.com/flutter/cocoon/pull/2064/files. I'm not sure why it did not update the device_doctor.

**Comment by godofredoc** [comment]
@keyonghan can you please take a look?

**Comment by keyonghan** [comment]
Dependabot seems working okay with `device_doctor` path: https://github.com/flutter/cocoon/pulls?q=is%3Apr+is%3Aclosed+author%3Aapp%2Fdependabot+%22device_doctor%22

By default, Dependabot opens a maximum of five pull requests for version updates: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#open-pull-requests-limit. Maybe the desired version was not picked up promptly.
