### ISSUE TITLE
[web] Occasionally the navigation bar disappears on pages with input boxes

### ISSUE THREAD

**Issue by OnesWYong** [flutter/flutter#110258]
Please check out the video on this issue:

https://github.com/flutter/flutter/issues/103946

The navigation bar sometimes disappears, is there any solution to this problem?

Error screenshot：
<img width="309" alt="截屏2022-08-25 18 55 13" src="https://user-images.githubusercontent.com/103549016/186648160-e584e851-c370-4357-902b-514bf4c40130.png">

Normal screenshot：
<img width="301" alt="截屏2022-08-25 18 55 32" src="https://user-images.githubusercontent.com/103549016/186648180-a381e5fd-7dcd-4070-acb0-d71a16ec79f7.png">

**Comment by exaby73** [comment]
Hi @OnesWYong, please provide a [minimal, reproducible example][1] and the output of `flutter doctor -v` as well as `flutter run -v`.

[1]: https://stackoverflow.com/help/minimal-reproducible-example
