### ISSUE TITLE
populate_existing_damage was not defined, disabling partial repaint. If you wish to enable partial repaint, please define this callback.

### ISSUE THREAD

**Issue by jinnyum** [flutter/flutter#110231]
Question:
When the project is created and executed, the following message appears.
(populate_existing_damage was not defined, disabling partial repaint. If you wish to enable partial repaint, please define this callback.)
Why is this message appearing?

1. flutter create --platforms=windows testapp
2. open Visual Studio Code
3. run F5 windows 

**Expected results:** 

Launching lib\main.dart on Windows in debug mode...
Connecting to VM Service at ws://127.0.0.1:7460/823K-ylfN5o=/ws

**Actual results:** 

Launching lib\main.dart on Windows in debug mode...
lib\main.dart:1
[INFO:embedder.cc(136)] populate_existing_damage was not defined, disabling partial repaint. If you wish to enable partial repaint, please define this callback.
Connecting to VM Service at ws://127.0.0.1:7460/823K-ylfN5o=/ws

<details>
No additional code is entered after project creation.
</details>

<details>
  <summary>Logs</summary>

```
```

```
```

C:\flutter_projects\addfile>flutter doctor -v
[√] Flutter (Channel master, 3.1.0-0.0.pre.2476, on Microsoft Windows [Version 10.0.19044.1889], locale ko-KR)
    • Flutter version 3.1.0-0.0.pre.2476 on channel master at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 637bd0fb74 (37 minutes ago), 2022-08-24 17:52:08 -0700
    • Engine revision f10ffb4b73
    • Dart version 2.19.0 (build 2.19.0-135.0.dev)
    • DevTools version 2.16.0

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Seong\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_SDK_ROOT = C:\Users\Seong\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.18)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.32802.440
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.70.2)
    • VS Code at C:\Users\Seong\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.46.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19044.1889]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 104.0.5112.102
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 104.0.1293.63

[√] HTTP Host Availability
    • All required HTTP hosts are available
</details>

**Comment by ColdPaleLight** [comment]
cc @betrevisan

**Comment by chinmaygarde** [comment]
cc @loic-sharma @cbracken

**Comment by loic-sharma** [comment]
It looks like [this info message](https://github.com/flutter/engine/blob/ead1348803aacfaf6b5bf474f4a8b9a5eac625c4/shell/platform/embedder/embedder.cc#L135-L139) is outputted before the logging verbosity has been set. This message was [added by @betrevisan](https://github.com/flutter/engine/pull/35022) for the dirty region management work, but no embedder provides [the `populate_existing_damage` callback](https://github.com/flutter/engine/search?q=populate_existing_damage) currently. I would expect this issue reproduces on any platform that uses the embedder API, not just Windows.
