### ISSUE TITLE
Update cirrus docker image to ubuntu

### ISSUE THREAD

**Issue by yusuf-goog** [flutter/flutter#110295]
As a final migration of our devicelab hosts and VMs to docker, we need to migrate the cirrus docker image as well.

Trying to update it has led to write permissions errors in the container registry. See: https://github.com/flutter/flutter/pull/108641

Trying out a smaller test to debug permissions issues: https://github.com/flutter/flutter/pull/108741

**Comment by yusuf-goog** [comment]
Heres the specific error:
```
unauthorized: You don't have the needed permissions to perform this operation, and you may have invalid credentials. To authenticate your request, follow the steps in: https://cloud.google.com/container-registry/docs/advanced-authentication```

**Comment by godofredoc** [comment]
The permissions problem has been fixed. Added some docs about troubleshooting this kind of problems to save ourselves some time in the future.

Can you please rebase a give it another try.

**Comment by yusuf-goog** [comment]
Update completed, cirrus image is now on ubuntu.
