### ISSUE TITLE
Could `PopupMenuPosition position` from `PopupMenuButton` be added to the `PopupMenuThemeData` ? 

### ISSUE THREAD

**Issue by ValentinVignal** [flutter/flutter#110264]
## Use case

I'm using `PopupMenuButton` in my app, and for all of them, I have to specify `position: PopupMenuPosition.under` everywhere I used it. It would be useful to be able to set it in the theme instead.

## Proposal

Add an entry `PopupMenuPosition position` in the `PopupMenuThemeData`.

**Comment by exaby73** [comment]
Hello @ValentinVignal. Thank you for filing this request. Labelling for further insights from the team.
