### ISSUE TITLE
`libpath_ops.dylib` should run natively on Apple Silicon arm machines

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#110227]
The `bin/cache/artifacts/engine/darwin-x64/libpath_ops.dylib` artifact dylib only contains a x64 slice, so runs with Rosetta on an arm64 Mac.  Ship a native arm64 variant to run on Apple Silicon host machines.

https://github.com/flutter/engine/pull/34267

@dnfield @zanderso

**Comment by jonahwilliams** [comment]
It actually doesn't work at all on m1 macs, since we expect to be able to use ffi and using that to open a dynamic library that is the wrong architecture fails.

https://github.com/dnfield/vector_graphics/issues/82#issuecomment-1149020516
