### ISSUE TITLE
[Image_picker] pick photo from gallery preview

### ISSUE THREAD

**Issue by johnnypcc** [flutter/flutter#110213]
After the user selects a photo, can we have a preview of the photo (just like the camera photo preview), with the gallery of the photos un-dismissed, still behind it? So when you cancel the preview, you can still see the gallery.

**Comment by stuartmorgan** [comment]
The UI presented by `image_picker` is provided by the system, not the plugin, so request for new UI features would need to go to the developers of the systems.
