### ISSUE TITLE
Tree closed on iOS device debug symbol transfer

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#110265]
https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_ios%20flutter_gallery_ios__transition_perf/2114/overview

cc @keyonghan @christopherfujino

**Comment by christopherfujino** [comment]
Hmm, very strange Dart compilation error:

```
../../../x/w/.pub-cache/hosted/pub.dartlang.org/file-6.1.2/lib/src/interface/file.dart:15:16: Error: The method 'File.create' has fewer named arguments than those of overridden method 'File.create'.
  Future<File> create({bool recursive = false});
               ^
org-dartlang-sdk:///sdk/lib/io/file.dart:232:16: Context: This is the overridden method ('create').
  Future<File> create({bool recursive = false, bool exclusive = false});
               ^
```

**Comment by zanderso** [comment]
@aam

**Comment by zanderso** [comment]
The version of `package:file` needs to be updated.

**Comment by christopherfujino** [comment]
we're getting file 6.1.2 from process 4.2.4

**Comment by zanderso** [comment]
Engine roll revert: https://github.com/flutter/flutter/pull/110267

**Comment by zanderso** [comment]
Dart reverts https://github.com/flutter/engine/pull/35702

**Comment by christopherfujino** [comment]
> we're getting file 6.1.2 from process 4.2.4

process 4.2.4 is the latest on pub, which constrains file on ^6.0.0, and the latest available is 6.1.4. it's just the pubspec.lock that kept the latest from being resolved. I will fix this in device doctor.

**Comment by aam** [comment]
`file` package to 6.1.4 is right version, the one should be used.
Not sure I understand role of pubspec.lock in the breakage.

**Comment by christopherfujino** [comment]
Ok, rolled file 6.1.4 to device_doctor. I will retry builds now on flutter/flutter

**Comment by christopherfujino** [comment]
Re-run of a previously failing build (pre-engine revert) successfully ran the ios-debug-symbol-doctor: https://ci.chromium.org/p/flutter/builders/prod/Mac_arm64_ios%20run_release_test_macos/2153. I think this is resolved and we can restore rollers.

**Comment by christopherfujino** [comment]
> `file` package to 6.1.4 is right version, the one should be used. Not sure I understand role of pubspec.lock in the breakage.

if the device doctor didn't have a pubspec.lock checked in, pub get would have pulled in the 6.1.4 as satisfying `file: ^6.0.0`

**Comment by christopherfujino** [comment]
> > if the device doctor didn't have a pubspec.lock checked in, pub get would have pulled in the 6.1.4 as satisfying `file: ^6.0.0`
> 
> Was pubspec.lock checked in on purpose or is this something that should be changed?

On purpose, if you don't check in pubspec.lock sometimes dependencies violate semver and a new version will break your app. Although, clearly there are costs to not checking it in, so I'm not sure what the right thing to do here is.

**Comment by aam** [comment]
Yeah, makes sense. There could be breakages caused by dependencies rolling automatically, there could be breakages caused by dependencies _not_ rolling automatically. :-)
I think as long as there is known process for addressing problems caused by stuck dependencies and team is aware, it's fine.

Only other thing is that controlling dependencies via checked-in pubspec.lock is unusual. I think for the apps that decided to lock dependencies you normally would see fixed version in pubspec.yaml itself(like is done in flutter framework).
Otherwise, if you wanted to run some static analysis of packages source code to see some outdated dependencies(that you would expect to see in pubspec.yaml), you will be mislead thinking that package doesn't have fixed dependencies.

**Comment by christopherfujino** [comment]
> Only other thing is that controlling dependencies via checked-in pubspec.lock is unusual. I think for the apps that decided to lock dependencies you normally would see fixed version in pubspec.yaml itself(like is done in flutter framework). Otherwise, if you wanted to run some static analysis of packages source code to see some outdated dependencies(that you would expect to see in pubspec.yaml), you will be mislead thinking that package doesn't have fixed dependencies.

Ahh, that's a good point. Now with `pub outdated` and `pub upgrade` it's easy to periodically upgrade them. That sounds like a good solution.
