### ISSUE TITLE
iOS Safari / Chrome with TextInput - Keyboard not showing

### ISSUE THREAD

**Issue by ipainchaud** [flutter/flutter#110284]
Internal: b/258262191

We have a Flutter application which uses Text inputs.
The text inputs work fine on Desktop WEB with Chrome, Safari, Firefox, Edge, Opera, etc.
The application works well also on mobile native iOS and Android. As you click on the input field, the keyboard appear and you can capture data. This is also true on Android WEB through Chrome.

On iOS WEB using Safari **and** Chrome though, when you click on the text input, the keyboard doesn't show and makes it impossible to capture data into it.

Here is a video exposing the issue. The video shows the execution of the same app twice. The first app to execute is the Native version. The second is the WEB app through Safari.

https://user-images.githubusercontent.com/5298744/186757565-b48f2757-07e9-462e-88a5-c617acaae2e1.mp4

We are using a form in our code to facilitate the validation. This issue also happens on every other type of Text input we use.
```dart
Widget build(BuildContext context) {
  return Title(
    [...]
    child: SingleChildScrollView(
      child: ConstrainedBox(
        constraints: [setting maxWidth...]
        child: IntrinsicHeight(
          child: _body,
        ),
      ),
    ),
  );
}

Widget get _body {
  return Form(
    key: _formKey,
    child: Column(
      [...]
      children: [
        [...]
        TextFormField(
          autofillHints: [...],
          decoration: [...],
          focusNode: [...],
          keyboardType: TextInputType.number,
          onChanged: [...],
          onFieldSubmitted: [...],
          textInputAction: TextInputAction.done,
          validator: [...],
        ),
      ],
    ),
  );
}
```
### The keyboard is displayed if you leave and come back to the app

1. is on Safari and click on a text input (the keyboard doesn't display)
2. and the user switches to another app
3. and the user switches back to Safari as the focus is on an input
4. Then! the keyboard appears and let you capture your information

### Can it be related to Semantic being enabled???

I haven't been able to reproduce this through my [gist on dartpad.io](https://dartpad.dev/?id=1645d94ad66a85772ebca71913bf5c1b)
Can it be caused by the fact that we use`RendererBinding.instance.setSemanticsEnabled(true);` in our main??? (see commented code in line 7 to 10 of the gist)

We are building an accessible app so we need this `Semantic` tree enabled.
Unfortunately, Darpad.IO doesn't seem to like that call to `setSemanticsEnabled(true)` as it doesn't load for me when I uncomment those lines.

### This is not the number keypad which is displayed

When we execute the app from Android or iOS (both) and succeeds to show the keyboard, it displays the full keyboard, and not the numeric keypad.

| iOS | Android |
| --------------- | --------------- |
<img width="375" alt="PNG image" src="https://user-images.githubusercontent.com/5298744/186771909-81d004d3-b30e-45d2-9f4c-ede1598c62ec.png"> | <img width="375" alt="PNG image" src="https://user-images.githubusercontent.com/5298744/186772303-7effac4b-2681-4406-bd61-432e6512d8fc.png">

```
$ flutter analyze
Analyzing my-app...                                                
No issues found! (ran in 6.2s)
```

```
$ flutter doctor -v
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.5.1 21G83 darwin-x64, locale en-US)
    • Flutter version 3.0.5 at /usr/local/Caskroom/flutter/3.0.2/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (6 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/israelpainchaud/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2022.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin version 222.3739.24

[✓] Connected device (5 available)
    • BS 02 (mobile)                      • 3d1896e7                             • android-arm64  • Android 8.1.0 (API 27)
    • sdk gphone64 x86 64 (mobile)        • emulator-5554                        • android-x64    • Android 13 (API 33) (emulator)
    • iPhone SE (3rd generation) (mobile) • 7B3F43F4-5669-4D38-8C80-B9FB8A077928 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-5 (simulator)
    • macOS (desktop)                     • macos                                • darwin-x64     • macOS 12.5.1 21G83 darwin-x64
    • Chrome (web)                        • chrome                               • web-javascript • Google Chrome 104.0.5112.101

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

**Comment by vsomayaji** [comment]
This issue _does_ appear to be caused by [enabling accessibility](https://docs.flutter.dev/development/accessibility-and-localization/accessibility#screen-readers). To reproduce it:

1. Run the code sample below with `flutter run -d chrome`.
2. Using Xcode's Simulator (**Xcode** > **Open Developer Tool** > **Simulator**), open an iPhone simulator (I used an iPhone 13 with iOS 15.5).
3. Disable the hardware keyboard (**I/O** > **Keyboard** > **Connect Hardware Keyboard**).
4. Open Safari and browse to the web app URL.
5. Tap in the `TextField`. The keyboard will _not_ be displayed. (Hold-and-press and it will.)

If you disable accessibility (`RendererBinding.instance.setSemanticsEnabled(false)`), the issue goes away.

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';

void main() {
  WidgetsFlutterBinding.ensureInitialized();

  // Auto-enable accessibility for our Blind and Low Vision customers.
  RendererBinding.instance.setSemanticsEnabled(true);

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  final String _title = 'TextField A11y Issue';

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: _title,
      home: Scaffold(
        appBar: AppBar(
          title: Text(_title),
        ),
        body: const MyWidget(),
      ),
    );
  }
}

class MyWidget extends StatefulWidget {
  const MyWidget({Key? key}) : super(key: key);

  @override
  State<MyWidget> createState() => _MyWidgetState();
}

class _MyWidgetState extends State<MyWidget> {
  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.all(40),
      child: Column(
        children: const <Widget>[
          Text('Tap in the TextField below. In a mobile browser on iOS, if a11y is enabled, the keyboard will NOT be '
              'displayed unless you press-and-hold in the text field.'),
          SizedBox(height: 20),
          TextField(
            decoration: InputDecoration(
              border: OutlineInputBorder(),
              labelText: 'Text',
            ),
          ),
        ],
      ),
    );
  }
}
```

</details>

https://user-images.githubusercontent.com/1007109/186789601-4bac1648-b5a7-4470-8a9e-5929608984e3.mov

**Comment by huycozy** [comment]
Hi @ipainchaud 
- For iOS issue, as @vsomayaji explained above, I think this behavior is working as intended. For more information: https://support.apple.com/en-al/guide/iphone/iph3e2e3d1d/ios

	> Enter text with the onscreen keyboard
	Select a text field, then double-tap.
	The insertion point and the onscreen keyboard appear.

- For Android issue, I can reproduce it. When semantic is enabled (`RendererBinding.instance.setSemanticsEnabled(true);`), it does not display numeric keypad.

	<img width="200" src="https://user-images.githubusercontent.com/104349824/186867439-4400bc5c-c0c3-4043-bcba-6f7cc0b99ab1.png"> 
	
Could you please open a new issue for the Android case?

**Comment by ipainchaud** [comment]
Thanks for the read, it was very interesting.

> VoiceOver changes how you use the onscreen keyboard when you activate an editable text field

This says that VoiceOver changes the behavior, but doesn't explain why the keyboard doesn't appear even when we don't have VoiceOver enabled.


About the Android case: I'll open another issue.

**Comment by huycozy** [comment]
Hi @ipainchaud 
I tested this again. Without enabling `RendererBinding.instance.setSemanticsEnabled(true);` but enabling `VoiceOver`, the keyboard doesn't seem to show up even when `double-tap`/`hold and press` on the TextField whilst the iOS app (Flutter) does it right with `double-tap` (please see in demo)

<details>
<summary>Demo</summary>

| Web | iOS |
| --------------- | --------------- |
<video src="https://user-images.githubusercontent.com/104349824/187117511-a2a6fd04-8d7d-4bc1-a2c7-2f6f24fa4f39.MP4"/> | <video src="https://user-images.githubusercontent.com/104349824/187117231-0bb43637-706b-4856-a4af-58c694637df4.MP4"/>

</details>

When enabling `RendererBinding.instance.setSemanticsEnabled(true);`, `hold and press` on the TextField will bring up the keyboard (as @vsomayaji mentioned above)

Do you have the same behavior?

**Comment by vsomayaji** [comment]
@huycozy I confirmed that if accessibility is _not_ enabled and you're using VoiceOver with a Flutter web app on iOS, nothing seems to work correctly. It makes sense that a Flutter iOS app isn't affected, as the semantic tree is always built on mobile.

Our issue is that we _always_ need to enable accessibility on web, even for our customers that are not using a screen reader. (Our philosophy is that accessibility isn't something that you should have to "opt in" to.) And that means that users who are not familiar with the hold-and-press requirement on text fields will be blocked when they tap in a text field and the keyboard is not displayed. 😦 Any thoughts on a fix/workaround?

**Comment by ipainchaud** [comment]
The issue is actually worst than that @vsomayaji @huycozy. 

We all agree that if you have enable `RendererBinding.instance.setSemanticsEnabled(true);` it works as expected with VoiceOver with a `double tap`. 

As @vsomayaji explained, we always enable the semantic tree, but with the `RendererBinding.instance.setSemanticsEnabled(true);` enabled, there is actually no way to get the keyboard without VoiceOver at all -- even with the `double tap`.

**Comment by huycozy** [comment]
@ipainchaud @vsomayaji, thanks for providing more information. Labeling this issue for further opinions/insights from the team.
This issue is reproducible on the latest `stable` and `master` channels.

- `setSemanticsEnabled(true)`: the keyboard doesn't show, but `press-and-hold` on the TextField will bring the keyboard up (not the numeric keypad)
- `setSemanticsEnabled(false)`: the keyboard shows numeric keypad as expected

<details>
<summary>Demo</summary>

| Safari iOS (enable semantic) | Safari iOS (disable semantic) |
| --------------- | --------------- |
<video src="https://user-images.githubusercontent.com/104349824/187591585-b34c945d-8cf6-4a5e-988f-a1a0be788582.MP4"/> | <video src="https://user-images.githubusercontent.com/104349824/187591593-0f1b8c1e-92bb-4465-8241-c4f3ae9d832e.MP4"/>

</details>

<details>
<summary>Sample code</summary>

```dart
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';
import 'package:flutter/services.dart';

void main() {
  WidgetsFlutterBinding.ensureInitialized();
  if (kIsWeb) {
    // Auto-enable accessibility for screen reader users
    RendererBinding.instance.setSemanticsEnabled(true);
  }

  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    const String title = 'TextInput not showing Keyboard on mobile WEB - Issue';
    return MaterialApp(
      title: title,
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: title),
    );
  }
}

class MyHomePage extends StatefulWidget {
  final String title;

  const MyHomePage({
    Key? key,
    required this.title,
  }) : super(key: key);

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final GlobalKey<FormState> _formKey = GlobalKey<FormState>();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Form(
          key: _formKey,
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              const Text(
                'please enter a number',
              ),
              TextFormField(
                keyboardType: TextInputType.number,
              ),
            ],
          ),
        ),
      ),
    );
  }
}

```
</details>

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 3.3.0, on macOS 12.5 21G72 darwin-x64, locale en-EE)
    • Flutter version 3.3.0 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffccd96b62 (28 hours ago), 2022-08-29 17:28:57 -0700
    • Engine revision 5e9e0e0aa8
    • Dart version 2.18.0
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13E113
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2020.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.70.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.46.0

[✓] Connected device (3 available)
    • iPhone 13 (mobile) • 2526BC1A-435D-4B08-B99C-44B928F2517B • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-4 (simulator)
    • macOS (desktop)    • macos                                • darwin-x64     • macOS 12.5 21G72 darwin-x64
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 104.0.5112.101

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

```bash
[✓] Flutter (Channel master, 3.1.0-0.0.pre.2592, on macOS 12.5 21G72 darwin-x64, locale en-EE)
    • Flutter version 3.1.0-0.0.pre.2592 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 069f504297 (3 hours ago), 2022-08-30 18:20:09 -0700
    • Engine revision 0ef08a8525
    • Dart version 2.19.0 (build 2.19.0-152.0.dev)
    • DevTools version 2.16.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13E113
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2020.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.70.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.46.0

[✓] Connected device (3 available)
    • iPhone 13 (mobile) • 2526BC1A-435D-4B08-B99C-44B928F2517B • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-4 (simulator)
    • macOS (desktop)    • macos                                • darwin-x64     • macOS 12.5 21G72 darwin-x64
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 104.0.5112.101

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```
</details>

**Comment by yjbanov** [comment]
Possibly related: https://github.com/flutter/flutter/issues/96199

**Comment by yjbanov** [comment]
Although, if this is only happening with `setSemanticsEnabled(true)` then maybe it's something else.

**Comment by jacobsimionato** [comment]
I updated this priority to P2 to be consistent with internal bug b/254706139 which is impacting a Google customer launch. We're trying the workaround the issue by making semantics opt-in, however the customer would prefer for semantics to be enabled by default.

**Comment by vsomayaji** [comment]
@jacobsimionato that's great to hear! We at Aira agree with your customer: semantics _should_ be enabled by default. In fact, we'd love to see that become the Flutter Web default someday. 😉

**Comment by nbayati** [comment]
I am actively working on this. It seems to be a result of bugs in our `SemanticsTextEditingStrategy` and some features that we haven't implemented yet in the semantic mode.
We have a partial fix that allows the keyboard to show up, but there are still some cases that needs investigating, including: 
- We're unable to move the cursor once the input gets focused.
- The input placement is wrong once the keyboard shows up.

I'll keep this thread updated as I get more insight.

**Comment by nbayati** [comment]
Still working on the placement issue. It seems like the viewport information that we communicate to the framework are wrong, but it still needs some more investigation.

**Comment by yjbanov** [comment]
It will take some time to solve this issue fully, but the most critical part of it has been extracted into a separate issue here: https://github.com/flutter/flutter/issues/115099. That one is P2. This one can be P3 for now.
