### ISSUE TITLE
FlutterDriver: no way to wait until a screenshot is ready

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#11021]
Collecting a screenshot with `driver.screenshot()` after calling `driver.waitUntilNoTransientCallbacks()`  doesn't guarantee that the current frame's display list will have reached the GPU before the screenshot is taken.

**Comment by yjbanov** [comment]
I am going to use https://github.com/flutter/flutter/pull/12896 as a non-ideal but hopefully good enough solution for this.
