### ISSUE TITLE
Enable "strict-casts" for flutter/packages

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#110290]
In the analysis options for fluttter/packages, the `strict-casts` is currently turned off:

https://github.com/flutter/packages/blob/97ae0e1c86d07576debbbd4fd67d2cc2a8c0bff0/analysis_options.yaml#L10

This is an unnecessary difference to the master analysis options file in the flutter/flutter repository. We should enable `strict-casts` in flutter/packages and fix all violations.

**Comment by stuartmorgan** [comment]
This was fixed during the repo merge alignment.
