### ISSUE TITLE
There are many red square warning around oversize image

### ISSUE THREAD

**Issue by zhangjun920912** [flutter/flutter#110243]
Commonly, In our application ,we use 3x.webp image, but there are many red square warning around oversize image ,it's diffcult to adjust UI with other UI developer, I want to remove it ,but can't find the method to resolve it,please help me to resolve it,thank you!

Here is my code: 
         Image.asset(
            HotelUtil.getImagePath('icon_hotel_detail_map.webp'),
            height: Dimens.image_height26,
            width: Dimens.image_width26,
          )

and the phenomena：
<img width="469" alt="截屏2022-08-25 下午2 51 34" src="https://user-images.githubusercontent.com/17971736/186595480-8a78a1cd-2e40-479c-94aa-9b09cfae8cc0.png">

**Comment by huycozy** [comment]
Hi @zhangjun920912, 
Which platform are you having this issue?
Please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this. Also, please provide the output of `flutter doctor -v` as well.
Thank you!

**Comment by zhangjun920912** [comment]
@huycozy Hello, both platform has this issue on my device;
Here is output of flutter doctor -v:
jzhang28@jzhang28deiMac ~ % flutter doctor -v
[✓] Flutter (Channel stable, 2.2.0, on macOS 11.4 20F71 darwin-x64, locale zh-Hans-CN)
    • Flutter version 2.2.0 at /Users/jzhang28/Library/flutter
    • Framework revision b22742018b (1 year, 3 months ago), 2021-05-14 19:12:57 -0700
    • Engine revision a9d88a4d18
    • Dart version 2.13.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/jzhang28/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/jzhang28/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.0, Build version 13A233
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 51.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[!] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio 2.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] Connected device (2 available)
    • iPhone 11 (mobile) • 84CA982E-C1C6-4CFE-9F3D-E9FCA9C7D5C4 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 104.0.5112.101

! Doctor found issues in 1 category.

**Comment by zhangjun920912** [comment]
Here are my code about map:
///获取酒店ICON标识
  Widget getHotelMapIconWidget() {
    return Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: <Widget>[
          Image.asset(
            HotelUtil.getImagePath('icon_hotel_detail_map.webp'),
            height: Dimens.image_height26,
            width: Dimens.image_width26,
          ),
          Container(
            margin: EdgeInsets.only(top: Dimens.gap_dp3),
            child: Text(
              '地图',
              style: TextStyle(
                  fontSize: Dimens.font_sp11,
                  color: HotelColors.hotel_main_color,
                  fontWeight: FontWeight.w500),
            ),
          ),
        ]);
  }

**Comment by huycozy** [comment]
Hi @zhangjun920912 
>Hello, both platform has this issue on my device;

Do you mean Android and iOS?

I tried loading this `.webp` image: https://www.gstatic.com/webp/gallery/1.webp, and see that it loaded normally on Android.

<details>
<summary>Demo</summary>

<img width="400" src="https://user-images.githubusercontent.com/104349824/187193456-b52d373a-2237-4eb3-97f7-e5bcb0d81fc5.png">

</details>

Please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) and the image you're having the issue, so that we may verify this.

**Comment by zhangjun920912** [comment]
yes,both of platform;
Follow is my whole code:
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:trip_common/trip_common.dart';

class MyHomePage extends StatefulWidget {
  @override
  State<StatefulWidget> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  _MyHomePageState();

  @override
  String getPageId() {
    return 'MyHomePage';
  }
  @override
  void initState() {
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        leading: IconButton(
          icon: Icon(
            Icons.arrow_back_ios,
            color: Colors.white,
          ), //自定义图标
          onPressed: () {
            Navigator.pop(context);
          },
        ),
        title: const Text('MyHomePage'),
      ),
      body: Center(
        child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              Image.asset(
                'assets/hotel/images/zhixing/icon_hotel_detail_map.webp',
                height: 26,
                width: 26,
              ),
              Container(
                margin: EdgeInsets.only(top: 3),
                child: Text(
                  '地图',
                  style: TextStyle(
                      fontSize: 11,
                      color: Color(0xff198cff),
                      fontWeight: FontWeight.w500),
                ),
              ),
            ]),
      ),
    );
  }
}

**Comment by zhangjun920912** [comment]
<img width="355" alt="截屏2022-08-29 下午8 05 34" src="https://user-images.githubusercontent.com/17971736/187197274-82e18672-8433-4aba-a320-731473d68f02.png">

**Comment by zhangjun920912** [comment]
@huycozy I asked my other colleagues, they said it's a phenomenon for checking triple big images. Commonly, we use x3 images in our application, example, when we need image 10*10,but our UI developer give us 30*30 image for our display. And we use flutter-boots in our app

**Comment by huycozy** [comment]
@zhangjun920912 please also provide `icon_hotel_detail_map.webp` file.

**Comment by zhangjun920912** [comment]
![icon_hotel_detail_map](https://user-images.githubusercontent.com/17971736/187208116-0b928845-0f0e-4f7f-b6f5-38443c90698b.png)
this image is 75*75,but I set image size is 26*26

**Comment by huycozy** [comment]
@zhangjun920912 
The image you provided is `.png` image, it's not `.webp` format as your sample code. I also tried with `.png` and this is the result. The image is displayed normally.

<details>
<summary>Demo</summary>


<img width="551" alt="Screenshot 2022-08-30 at 09 13 04" src="https://user-images.githubusercontent.com/104349824/187333265-f98eef68-af6a-4d34-85bd-d85bd1f3467f.png">

</details>

<details>
<summary>Sample code</summary>

```dart
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      localizationsDelegates: const [
        GlobalMaterialLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        DefaultCupertinoLocalizations.delegate,
      ],
      supportedLocales: const [
        Locale('en'),
      ],
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  State createState() => _MyHomePageState();
}

class _MyHomePageState extends State {
  _MyHomePageState();

  @override
  String getPageId() {
    return 'MyHomePage';
  }

  @override
  void initState() {
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        leading: IconButton(
          icon: Icon(
            Icons.arrow_back_ios,
            color: Colors.white,
          ), //自定义图标
          onPressed: () {
            Navigator.pop(context);
          },
        ),
        title: const Text('MyHomePage'),
      ),
      body: Center(
        child: Column(mainAxisAlignment: MainAxisAlignment.center, children: [
          Image.asset(
            'assets/187208116-0b928845-0f0e-4f7f-b6f5-38443c90698b.png',
            height: 26,
            width: 26,
          ),
          Container(
            margin: EdgeInsets.only(top: 3),
            child: Text(
              '地图',
              style: TextStyle(fontSize: 11, color: Color(0xff198cff), fontWeight: FontWeight.w500),
            ),
          ),
        ]),
      ),
    );
  }
}

```
</details>

Assuming that the issue is not by the image format, maybe it is related to the 3rd library like `flutter-boots` you mentioned above, try removing it and check again.
