### ISSUE TITLE
When compiling libapp.so and libflutter.so with NDK, the "-fstack-protector-all" and "-fPIC" are not added to the  Android.mk.

### ISSUE THREAD

**Issue by wahahaha18** [flutter/flutter#110233]
Question:
Sorry, I have a problem.
I compiled the android apk with flutter.
I found that my app was at risk after being tested by a formal institution.
The test results suggest that my app has security risks, and the repair suggestion is "When compiling So files with NDK, add '-fstack-protector-all' and '-fPIC' to the Android.mk."

The files involved are the following:
.lib/arm64-v8a/libapp.so
.lib/arm64-v8a/libflutter.so
.lib/armeabi-v7a/libapp.so

My development environment is:
Flutter 2.5.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 18116933e7 (10 months ago) • 2021-10-15 10:46:35 -0700
Engine • revision d3ea636dc5
Tools • Dart 2.14.4

I hope you can add '-fstack-protector-all' and '-fPIC', because this is related to whether my APP can be approved by customers

**Comment by huycozy** [comment]
Hi @wahahaha18, thanks for filing the issue. 
I see there are some filed issues addressing the case you described #72800. Also, there are some related issues you can follow:  #99905, #4368, #87952
Closing this issue as a duplicate, so please follow up on these issues for further updates. You can leave there your comment and react an upvote to the original comment will help to raise the issue. Thank you!
