### ISSUE TITLE
Desktop needs bidirectional scroll.

### ISSUE THREAD

**Issue by pouyakary** [flutter/flutter#110283]
## Steps to Reproduce

> **TL;DR** &mdash; InteractiveViewer has no mouse support and SingleChilScrollView is not bidirectional.

I'm trying to write a note app where you can put widgets on the screen and have some fun. For the bidirectional scrolling it seems that only the `InteractiveViewer` does the job. However the problem is that `InteractiveViewer` has no means for scrolling with the mouse. You have to **drag** the screen to apply the transition. And if you try to scroll with the mouse nothing happens. `SingleChilScrollView` has great support for mouse, but it has no bidirectional scrolling option. Desktop suffers from not having a bidirectional scroll solution. Can you please do something about this?

<details>
<summary>Code sample</summary>

```dart
return InteractiveViewer(
  constrained:  false,
  scaleEnabled: false,

  child: SizedBox(
    height: height,
    width:  width,

    // Horizontal Scroll
    child: Stack(
      children: board.elements.map((sticky) =>
        BoardElementView(
          element:  sticky
        )
      ).toList(),

    ),
  )
);
```

</details>

<img width="1063" alt="Screen Shot 2022-08-26 at 12 24 07 AM" src="https://user-images.githubusercontent.com/2157285/186755876-363d0fc7-453a-44a8-b3a8-740d19bcf250.png">

**Comment by huycozy** [comment]
Hi @pouyakary 
I see there's an open issue addressing the case you described #64210
Closing this issue as a duplicate, so please follow up on it for further updates. You can leave there your comment and react an upvote to the original comment will help to raise the issue. Thank you!
