### ISSUE TITLE
`flutter build macos-framework` doesn't work with custom engine (M1 Mac)

### ISSUE THREAD

**Issue by dubik** [flutter/flutter#110335]
I use `beta` channel for the `flutter` which has a new command `build macos-framework`. I can build framework just fine if I use flutter's engines. However, I get issues when I compile engine myself.
I checked version of the engine from:

```flutter --version
Flutter 3.3.0-0.5.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision 096162697a (4 days ago) • 2022-08-22 15:34:14 -0700
Engine • revision ad3d868e0d
Tools • Dart 2.18.0 (build 2.18.0-271.7.beta) • DevTools 2.15.0
```

I followed wiki to compile engine on MacOS M1. I create `.gclient` file, and then:
`cd src/flutter && git checkout ad3d868e0d`
I built the engine and created new project:
`flutter --local-engine=host_debug_unopt create calculator`
I can run project just fine with `flutter --local-engine=host_debug_unopt run` but if I try
to build framework:
`flutter --local-engine=host_debug_unopt build macos-framework`

I get:
```
Changing current working directory to: /private/tmp/calculator

💪 Building with sound null safety 💪

Building macOS frameworks in debug mode...
Exception: Binary
/private/tmp/calculator/build/macos/framework/Debug/FlutterMacOS.framework/Versions/A/Flutter
MacOS does not contain x86_64 arm64. Running lipo -info:
Non-fat file:
/private/tmp/calculator/build/macos/framework/Debug/FlutterMacOS.framework/Versions/A/Flutter
MacOS is architecture: x86_64
```

Wiki doesn't really mention anything related to M1. Should I build somehow arm flavor of flutter engine if yes, how?

@jmagman could you help?
Thanks.

**Comment by cbracken** [comment]
If you're building for M1 mac, you'll want to use `host_debug_unopt_arm64` since `host_debug_unopt` is an x64 build. To do that:
```
% ./tools/gn --unoptimized --mac-cpu=arm64
% autoninja -C ../out/host_debug_unopt_arm64
```

Note that we're trying to remove macOS target assets from the host build so eventually you'll need to build `mac_debug_unopt_arm64` using the `--mac --mac-cpu=arm64` options, but host builds should work fine today.

I'll get the wiki updated, but things should work fine if you use the arm64 engine. Let me know if you run into any issues.

**Comment by dubik** [comment]
Thanks Chris. Unfortunately that didn't fix the problem. If I build arm64 version of engine, `flutter --local-engine host_debug_unopt_arm64 build macos-framework` complains:
```
flutter --local-engine=host_debug_unopt_arm64 build macos-framework            ✔  10:11:17 

💪 Building with sound null safety 💪

Building macOS frameworks in debug mode...
Exception: Binary /private/tmp/calculator/build/macos/framework/Debug/FlutterMacOS.framework/Versions/A/FlutterMacOS does
not contain x86_64 arm64. Running lipo -info:
Non-fat file: /private/tmp/calculator/build/macos/framework/Debug/FlutterMacOS.framework/Versions/A/FlutterMacOS is
architecture: arm64


 ├─Building App.xcframework and FlutterMacOS.xcframework...        10.2s
The App.xcframework build failed.
```
So now that script complains that it can't find `x86_64` version of `FlutterMacOS.framework` which makes sense because it tries to build `xcframework` which contains both. If I don't specify custom engine, it builds fine, and it builds two variants:
```
flutter build macos-framework                                                  ✔  10:14:28 

💪 Building with sound null safety 💪

Building macOS frameworks in debug mode...
 ├─Building App.xcframework and FlutterMacOS.xcframework...         6.2s
 └─Moving to build/macos/framework/Debug
Building macOS frameworks in profile mode...
Building App.framework for x86_64...
Building App.framework for arm64...
 ├─Building App.xcframework and FlutterMacOS.xcframework...        14.2s
 └─Moving to build/macos/framework/Profile
Building macOS frameworks in release mode...
Building App.framework for x86_64...
Building App.framework for arm64...
 ├─Building App.xcframework and FlutterMacOS.xcframework...        11.3s
 └─Moving to build/macos/framework/Release
Frameworks written to /private/tmp/calculator/build/macos/framework.
```

I think, somehow, I need to pass 2 engine builds to `flutter` command. Something like `flutter --local-engine=host_debug_unopt_arm64, host_debug_unopt build macos-framework`. How can I do that?

Btw, I have no issues running an application with rosetta or arm with `flutter --local-engine=host_debug_unopt<_arm64> run`, only `build macos-framework` is a problem.

**Comment by dubik** [comment]
I think I'm starting to understand what's going on. I looked at CI script which builds `FlutterMacOS.framework` and it seems like it builds both `arm` and `x64` and uses a tool `create_macos_framework.py` to make a "fat" framework.

It would be nice if the `build macos-framework` command would put only a single platform into `FlutterMacOS.xcframework` if the custom engine is used.

**Comment by cbracken** [comment]
> It would be nice if the `build macos-framework` command would put only a single platform into `FlutterMacOS.xcframework` if the custom engine is used.

That seems like a super reasonable request and probably not a ton of work. For host builds, we can use `lipo -archs foo` to check the architectures present in a binary then strip the generated one to match the engine binary in use.

**Comment by jmagman** [comment]
This is related to https://github.com/flutter/flutter/issues/100804 and #100917, which was similar work done for `run` and `build`.  But `build macos-frameworks` is hardcoding the archs without taking the local engine into account:
https://github.com/flutter/flutter/blob/7f1a8f79489412ff992b8ba0aaecc386fe628557/packages/flutter_tools/lib/src/commands/build_macos_framework.dart#L196-L199

I actually bet iOS has the same problem, but no one has tried with a local engine:
https://github.com/flutter/flutter/blob/7f1a8f79489412ff992b8ba0aaecc386fe628557/packages/flutter_tools/lib/src/commands/build_ios_framework.dart#L425

**Comment by jmagman** [comment]
@dubik would you mind giving this a try on master on top of https://github.com/flutter/flutter/pull/110564?

**Comment by jmagman** [comment]
@dubik see also https://github.com/flutter/flutter/issues/74735 for outstanding work to run the engine on macOS add-to-app.

**Comment by dubik** [comment]
@jmagman thanks a lot, it worked fine.
