### ISSUE TITLE
ui.Canvas does not have a restoreToCount method

### ISSUE THREAD

**Issue by flar** [flutter/flutter#110324]
ui.Canvas implements `getSaveCount()` which returns the size of the internal save(Layer) stack, but it does not provide any methods to use that information. Typically a save/restore type of graphics object will provide a `restoreToCount(save_count)` method to quickly roll back a number of outstanding/unmatched save methods - often useful when the execution of a method had some of its save or saveLayer calls invoked conditionally so that a single "restore to the save count when we started" call can replace a nest of conditional restores at the end of that sequence.

**Comment by ColdPaleLight** [comment]
Talked with @guoguo338 offline and he's going to file a PR for it.

**Comment by ColdPaleLight** [comment]
Fixed by linked PR
