### ISSUE TITLE
Can flutter be applied in embedded devices for free

### ISSUE THREAD

**Issue by fayfive** [flutter/flutter#110397]
I want to know If I use in embedded device, which license does flutter follow?
Is it still free event I use flutter commercially？
Thanks!

**Comment by jonahwilliams** [comment]
You can find information on the licenses of flutter and it's dependencies at https://docs.flutter.dev/resources/faq#which-software-licenses-apply-to-flutter-and-its-dependencies

**Comment by fayfive** [comment]
That means flutter just has only one license whatever I use it on my embedded devices nor the devices you have Fitted?

**Comment by fayfive** [comment]
Thanks!
