### ISSUE TITLE
CupertinoTextField should support handle order swapping like Native iOS

### ISSUE THREAD

**Issue by ksballetba** [flutter/flutter#110306]
CupertinoTextFeild:

https://user-images.githubusercontent.com/30322203/186804383-0c05d340-ceed-4cc1-8a1d-d9df6882b6fd.mov

Native iOS UITextField:

https://user-images.githubusercontent.com/30322203/186804649-7e8cf3c9-80f8-49e9-b8af-316fbd787b96.mov

can reproduce in any cupertino text field

**Comment by ksballetba** [comment]
cc @justinmc

**Comment by justinmc** [comment]
Confirmed that native iOS does allow handle order swapping (iPad iOS 15).
