### ISSUE TITLE
TextFormField's onSaved method signature should be changed

### ISSUE THREAD

**Issue by iLoveDocs** [flutter/flutter#110376]
### Minimum reproducible code:
```dart
final GlobalKey<FormState> _globalKey = GlobalKey();

@override
Widget build(BuildContext context) {
  return Scaffold(
    body: Column(
      children: [
        Form(
          key: _globalKey,
          child: TextFormField(onSaved: print),
        ),
        ElevatedButton(
          onPressed: () => _globalKey.currentState!.save(),
          child: Text('Save'),
        ),
      ],
    ),
  );
}
```

### Steps to reproduce: 

Don't enter anything (or bring the `TextFormField` in focus) and press the `Save` button, you'll notice an empty string is printed on the console. It should rather be either `null` (as the `onSaved` signature suggests) or the signature should be changed from 

```dart
final FormFieldSetter<T>? onSaved;
```

to 

```dart
final ValueChanged<T>? onSaved;
```

**Comment by exaby73** [comment]
Hello @iLoveDocs. The signature suggests that the field `onSave` is optional, not the `T` within. This is expected behavior. Closing this issue as this is not an issue with Flutter. If you disagree, please comment and we can reopen it. Thank you.

**Comment by iLoveDocs** [comment]
@exaby73 

I know the field is optional, I am not saying to change

```dart
final FormFieldSetter<T>? onSaved;
```

to 

```dart
final FormFieldSetter<T> onSaved;
```

I'm saying we should change the signature (typedef) from `FormFieldSetter` to `ValueChanged`. I think this issue should be therefore opened. Thanks

**Comment by exaby73** [comment]
@iLoveDocs That change would force you to add `onSaved` to all your `TextField`s. That is not wanted behavior.

**Comment by iLoveDocs** [comment]
@exaby73 

> That change would force you to add onSaved to all your TextFields. 

And how? I am not saying we need to make the the parameter non nullable. 

Can you please make other members get into this thread, maybe I didn't make you understand it properly.

**Comment by exaby73** [comment]
`FormFieldSetter` is a `typedef` that's used by many other widgets. In the case of a `TextField`, I think it will never be `null` but for example, a `DropdownButtonFormField` may have a `null` value. This change would break a lot of APIs so this is not a feasible request. Keeping it closed for those reasons.

https://github.com/flutter/flutter/blob/202f5771f49837b6663e2cd5fd3dbc0c543cc39e/packages/flutter/lib/src/widgets/form.dart#L231-L234

**Comment by iLoveDocs** [comment]
@exaby73 

Did I say we should change `FormFieldSetter` signature? No!

I think you still didn't understand what the thread is all about. For the `TextFormField`, we should change

```dart
final FormFieldSetter<T>? onSaved;
```

to 

```dart
final ValueChanged<T>? onSaved;
```

Can you please let other members have their say on this thread? Thanks

**Comment by exaby73** [comment]
The `onSaved` property is inherited from `FormField`. `FormField` is also implemented in [`CupertinoTextFormFieldRow`](https://api.flutter.dev/flutter/cupertino/CupertinoTextFormFieldRow-class.html), [`DropdownButtonFormField`](https://api.flutter.dev/flutter/material/DropdownButtonFormField-class.html). This would break their APIs.

`FormField` is inherited here:

https://github.com/flutter/flutter/blob/723b82e4f0f3652dfaffb6e9bbc714e069da2976/packages/flutter/lib/src/material/text_form_field.dart#L87

In `TextFormField`'s constructor, there is a reference to `super.onSaved` here:

https://github.com/flutter/flutter/blob/723b82e4f0f3652dfaffb6e9bbc714e069da2976/packages/flutter/lib/src/material/text_form_field.dart#L131

This is where `onSaved` comes from in `FieldField`:

https://github.com/flutter/flutter/blob/723b82e4f0f3652dfaffb6e9bbc714e069da2976/packages/flutter/lib/src/widgets/form.dart#L280

From `FormField`'s docs ([here](https://api.flutter.dev/flutter/widgets/FormField-class.html)), you can see the implementers mentioned

>Implementers
[CupertinoTextFormFieldRow](https://api.flutter.dev/flutter/cupertino/CupertinoTextFormFieldRow-class.html), [DropdownButtonFormField](https://api.flutter.dev/flutter/material/DropdownButtonFormField-class.html), [TextFormField](https://api.flutter.dev/flutter/material/TextFormField-class.html)
