### ISSUE TITLE
camera_web: minimum browser version supported

### ISSUE THREAD

**Issue by deepak786** [flutter/flutter#110363]
Ref: https://github.com/flutter/flutter/issues/107467

It is not clear the minimum browser version supported by the camera package.
When I posted the previous issue, the screenshots about the web supported version on the camera_web package were different i.e. the browser versions were different.

For e.g: 
- Minimum Chrome version was 101
- Minimum Edge version was also 101
- Minimum iOS safari version was 15.3

![Untitled](https://user-images.githubusercontent.com/14223997/186960391-bd0685ee-5d35-469f-a5dd-12edcb8a8c0c.png)

Now the browser version screenshots shows minimum version 102, 102, 15.4 respectively based on the above example.

![Screen Shot 2022-08-26 at 11 06 19 PM](https://user-images.githubusercontent.com/14223997/186960963-2a8cad1f-5699-486e-a1f3-f92f45848189.png)

So after researching, I found that:
The above images are embedded from https://caniuse.bitsofco.de/ with daily updates. So it's fine.

According to this https://caniuse.com/mdn-api_mediarecorder, the minimum iOS Safari version supported is 14 for recording.
But the recording using the camera package does not work on iOS Safari browser having version less than 15.3. I don't know if it's an issue in the camera package or not.

So what is the minimum browser version supported by the camera_web package for each browser? and If its an issue in camera package that it is not working on below 15.3 iOS safari then I can create a separate issue ticket.

**Comment by stuartmorgan** [comment]
> When I posted the previous issue, the screenshots about the web supported version on the camera_web package were different i.e. the browser versions were different.
> 
> For e.g:
> 
> * Minimum Chrome version was 101
> * Minimum Edge version was also 101
> * Minimum iOS safari version was 15.3

The embeds are not showing minimum versions, they are showing the last N versions of each of those browsers. For minimum versions, you need to click through to the full table linked just above each embed.

> According to this https://caniuse.com/mdn-api_mediarecorder, the minimum iOS Safari version supported is 14 for recording. But the recording using the camera package does not work on iOS Safari browser having version less than 15.3.

Please file an issue with details.

> So what is the minimum browser version supported by the camera_web package for each browser?

There is no single version, which is why the readme breaks it down by the browser technology required for each feature, and links to the information about browser support for those features.

**Comment by deepak786** [comment]
@stuartmorgan Thanks for the information.
It was not clear properly in https://github.com/flutter/flutter/issues/107467
