### ISSUE TITLE
[Impeller] Enable attachment validation.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#110385]
Currently, there are instances where load and store actions are specified on render pass attachments with device transient storage modes. This is an error. However, enabling validations for these makes rendering fail completely. Fix existing incorrect uses and enable this validation.

**Comment by bdero** [comment]
These rules to not yet handle Multisample resolve.

Also, do the Metal docs indicate that the Clear load action not OK for device transient textures in Metal? Does it get zero initialized when DontCare is used?

**Comment by chinmaygarde** [comment]
> Also, do the Metal docs indicate that the Clear load action not OK for device transient textures in Metal?

From [the docs for `MTLStorageModeMemoryless`](https://developer.apple.com/documentation/metal/mtlstoragemode/mtlstoragemodememoryless):

```
Memoryless resources can be used only as temporary render targets in a
render pass (in effect, MTLTexture objects configured and used with a
MTLRenderPassAttachmentDescriptor object). You can’t load the texture’s
contents at the start of the render pass (MTLLoadActionLoad), nor may
you store its contents (MTLStoreActionStore) at the end of the render
pass.
```

Also, these validation trip on M1 macOS but curiously not on iOS (as we have discovered).

> Does it get zero initialized when DontCare is used?

Per the docs, presumably not. But again, I am not sure how we got away with this on iOS given the very clear guidance. Also, why the validation trip on M1 macOS but not on iOS.

**Comment by bdero** [comment]
This sounds to me like `MTLLoadActionLoad` is invalid, but `MTLLoadActionClear` isn't. I tried switching from `Clear` to `DontCare` for all the transient textures and can confirm `DontCare` doesn't zero initialize the textures.

The docs seem pretty clear and everything we're doing seems to actually be valid. I'll swing around and add rules for multisample resolve so we can test out if anything needs adjusting.
