### ISSUE TITLE
this camera flutter need official guide to convert CameraImage to File，thanks！

### ISSUE THREAD

**Issue by Superyanggod** [flutter/flutter#110332]
## Proposal

I need to convert CameraImage to image in file form in stream

**Comment by darshankawar** [comment]
I think this is similar to https://github.com/flutter/flutter/issues/26348 and a temporary solution is: https://github.com/flutter/flutter/issues/26348#issuecomment-453044033 which you can use and see if it works in your case.

Closing this in favor of linked issue. If you disagree, write in comments and I'll reopen it.
