### ISSUE TITLE
Shadow rendering appears "sharper" than expected

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#11035]
Since [the last Skia roll](https://github.com/flutter/engine/pull/3820), we've noticed a change in our shadow rendering where certain shadows appear varying degrees of sharper than they were before.

Below are some example before & after screenshots:

## On Android Emulator
```
GLES: Google (VMware, Inc.), Android Emulator OpenGL ES Translator (Gallium 0.4 on llvmpipe (LLVM 3.5, 256 bits)), OpenGL ES 2.0 (3.0 Mesa 10.4.2 (git-))
```

![skia-roll](https://user-images.githubusercontent.com/15253456/27653355-ae1144fa-5bf3-11e7-80ec-e1f94f95adde.gif)
*(the corners of the cards specifically look off)*

![rounded-button](https://user-images.githubusercontent.com/15253456/27654162-3bf82c78-5bf6-11e7-93a6-4905bcd4ec58.gif)

## On iPhone 7 physical device

![iphone-7](https://user-images.githubusercontent.com/15253456/27697378-e6997f08-5ca8-11e7-8634-a2d03f6063ed.gif)

**Comment by eseidelGoogle** [comment]
In the roll bug @jvanverth suggested that this may be due to PhysicalModalLayer not taking devicePixelRatio into account.  (Although unclear if that would manifest on the emulator in question.)

This is another bug where having some better ability to dump device graphics info might be useful. :)

**Comment by tvolkert** [comment]
@eseidel we have that info 😄 

[device_info.txt](https://github.com/flutter/flutter/files/1112912/device_info.txt)

**Comment by jvanverth** [comment]
Do you use SkPictures to playback to Skia, or do you render directly? We made some changes to how shadow state is recorded in an SkPicture which may be related to this.

**Comment by tvolkert** [comment]
> Do you use SkPictures to playback to Skia, or do you render directly?
> We made some changes to how shadow state is recorded in an SkPicture
> which may be related to this.

/cc @chinmaygarde

**Comment by chinmaygarde** [comment]
We create `SkPicture`s (actually a hierarchy of pictures) first from a recording canvas and play back those pictures on a separate rendering canvas.

**Comment by chinmaygarde** [comment]
To be clear, we use `SkCanvas::drawPicture` instead of `SkPicture::playback` on the rendering canvas.

**Comment by jvanverth** [comment]
I think that might be it, then. We fixed some bugs in playback that you may have been relying on. I'll see if I can tweak the params in PhysicalModelLayer to get back to what you had before.

**Comment by jvanverth** [comment]
So I've verified that the SkPicture fixes did cause this change -- so it's technically more correct, but may not be the look you want. I think the correct fix is to apply the pixel ratio, but I'm not sure how to access that down in PhysicalLayerModel.

**Comment by goderbauer** [comment]
Shadows under dialogs also look kinda strange. Looking at the material spec, they are not supposed to stop that abruptly. Not sure if that's caused by what's discussed in this issue or a separate issue. 

![image](https://user-images.githubusercontent.com/1227763/28041506-9683ea1a-657e-11e7-8434-507ff14a9912.png)

**Comment by eseidelGoogle** [comment]
@goderbauer is the above a regression?

**Comment by goderbauer** [comment]
Yes, I think so. The screenshot in my previous post was taken at HEAD on master. On the current alpha branch (~3 weeks behind), the shadows look a lot better:

![img_0004](https://user-images.githubusercontent.com/1227763/28080114-9dad2bca-661f-11e7-9f4a-b9dfa42061fe.PNG)

**Comment by eseidelGoogle** [comment]
We got another report of the bad dialog shadows from @theobouwman over Gitter just now.

**Comment by sethladd** [comment]
And this report: https://github.com/flutter/flutter/issues/11285

**Comment by jvanverth** [comment]
So I'm trying to figure out how Flutter is using the shadow code by tracing through it and in particular trying to understand how the shadows are transformed.  As a simple example, I'm looking at the FAB page under Buttons in the Gallery. 

First, it looks like it renders the tab content under the blue bar via Dart at default resolution, and I assume recording it to an SkPicture. This is for the the FAB shadow. 

Then it looks like it's trying to render the shadow for the top bar, but with a matrix scale of 2 to match the resolution (I'm running this on a Retina iPad). This is via the GPURasterizer. My guess is that the SkPIcture for the tab content is correspondingly scaled up by 2 when it's played back -- is that correct? Here are the stack traces I'm seeing, if that's helpful.

FAB Shadow:

* thread #10, name = 'ui_thread', stop reason = breakpoint 3.1
  * frame #0: 0x0000000100183c8c Flutter`flow::PhysicalModelLayer::DrawShadow(canvas=0x000000014016bc00, path=0x000000017004e0e8, color=4278190080, elevation=12, transparentOccluder=false) at physical_model_layer.cc:101 [opt]
    frame #1: 0x00000001001908d8 Flutter`tonic::DartDispatcher<tonic::IndicesHolder<0ul, 1ul, 2ul, 3ul>, void (blink::Canvas::*)(blink::CanvasPath const*, unsigned int, double, bool)>::Dispatch(this=0x000000016e368408, func=<unavailable>)(blink::CanvasPath const*, unsigned int, double, bool)) at dart_args.h:144 [opt]
    frame #2: 0x0000000100190858 Flutter`void tonic::DartCall<void (blink::Canvas::*)(blink::CanvasPath const*, unsigned int, double, bool)>(func=<unavailable>, args=<unavailable>)(blink::CanvasPath const*, unsigned int, double, bool), _Dart_NativeArguments*) at dart_args.h:176 [opt]
    frame #3: 0x0000000100750ff4 Flutter`dart::NativeEntry::AutoScopeNativeCallWrapperNoStackCheck(args=0x000000016e368890, func=(Flutter`blink::Canvas_drawShadow(_Dart_NativeArguments*) at canvas.cc:63))(_Dart_NativeArguments*)) at native_entry.cc:185
    frame #4: 0x0000000100903aa0 Flutter`dart::InvokeNativeAutoScopeWrapper(thread=0x00000001400f3e00, sim=<unavailable>, f=(Flutter`blink::Canvas_drawShadow(_Dart_NativeArguments*) at canvas.cc:63), args=0x000000016e368890)(_Dart_NativeArguments*), dart::NativeArguments*) at simulator_dbc.cc:967
    frame #5: 0x00000001008fefa0 Flutter`dart::Simulator::Call(this=0x000000017026b740, code=<unavailable>, arguments_descriptor=<unavailable>, arguments=<unavailable>, thread=<unavailable>) at simulator_dbc.cc:1968
    frame #6: 0x00000001006654d8 Flutter`dart::DartEntry::InvokeFunction(function=<unavailable>, arguments=0x0000000104e048a0, arguments_descriptor=0x00000001055831e4, current_sp=<unavailable>) at dart_entry.cc:118
    frame #7: 0x0000000100940500 Flutter`::Dart_Invoke(target=<unavailable>, name=<unavailable>, number_of_arguments=0, arguments=<unavailable>) at dart_api_impl.cc:4059
    frame #8: 0x000000010058d2b8 Flutter`tonic::DartInvokeField(target=<unavailable>, name=<unavailable>, args=<unavailable>) at dart_invoke.cc:16 [opt]
    frame #9: 0x000000010019c8d4 Flutter`blink::Window::BeginFrame(this=0x000000017008fe60, frameTime=<unavailable>) at window.cc:233 [opt]
    frame #10: 0x00000001001a07b0 Flutter`shell::Engine::BeginFrame(this=0x000000017419ac30, frame_time=(ticks_ = 319467448352916)) at engine.cc:240 [opt]
    frame #11: 0x000000010019db44 Flutter`shell::Animator::BeginFrame(this=0x00000001740eb400, frame_time=<unavailable>) at animator.cc:68 [opt]
[...]

And for the top bar:

* thread #9, name = 'gpu_thread', stop reason = breakpoint 3.1
  * frame #0: 0x0000000100183c8c Flutter`flow::PhysicalModelLayer::DrawShadow(canvas=0x0000000140101c00, path=0x000000016e2dc948, color=4278190080, elevation=4, transparentOccluder=false) at physical_model_layer.cc:101 [opt]
    frame #1: 0x0000000100183b60 Flutter`flow::PhysicalModelLayer::Paint(this=0x00000001700efe00, context=0x000000016e2dcbc8) at physical_model_layer.cc:72 [opt]
    frame #2: 0x0000000100182200 Flutter`flow::ContainerLayer::PaintChildren(this=<unavailable>, context=0x000000016e2dcbc8) const at container_layer.cc:47 [opt]
    frame #3: 0x0000000100183bf0 Flutter`flow::PhysicalModelLayer::Paint(this=0x00000001700efd00, context=0x000000016e2dcbc8) at physical_model_layer.cc:87 [opt]
    frame #4: 0x0000000100182200 Flutter`flow::ContainerLayer::PaintChildren(this=<unavailable>, context=0x000000016e2dcbc8) const at container_layer.cc:47 [opt]
    frame #5: 0x0000000100184498 Flutter`flow::TransformLayer::Paint(this=0x00000001702c24c0, context=0x000000016e2dcbc8) at transform_layer.cc:41 [opt]
    frame #6: 0x000000010018276c Flutter`flow::LayerTree::Paint(this=0x00000001702280a0, frame=<unavailable>) at layer_tree.cc:68 [opt]
    frame #7: 0x00000001001ac330 Flutter`shell::GPURasterizer::DrawToSurface(this=0x00000001701c7080, layer_tree=0x00000001702280a0) at gpu_rasterizer.cc:138 [opt]
    frame #8: 0x00000001001ac128 Flutter`shell::GPURasterizer::DoDraw(this=0x00000001701c7080, layer_tree=unique_ptr<flow::LayerTree, std::__1::default_delete<flow::LayerTree> > @ 0x000000016e2dcc98) at gpu_rasterizer.cc:115 [opt]
[...]

**Comment by jvanverth** [comment]
The dialog issue appears to be something else. If I press "OK" on the dialog and then move my finger outside of it before lifting up again, the shadow refreshes and looks fine. Similarly, if I place a breakpoint in the shadow code and hit the FAB to bring up the dialog, after stepping through all the breakpoints the shadow looks fine.

**Comment by Hixie** [comment]
We believe this specific issue is resolved. If there are specific other issues with shadows please file new bugs so that we can track them independently. Thanks!
