### ISSUE TITLE
The profile picture for autoroller accounts should be more interesting

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#110304]
The accounts here https://github.com/skia-flutter-autoroll and here https://github.com/engine-flutter-autoroll autoroll a bunch of dependencies.

They should have more interesting GitHub profile pictures.

I vote for wizard dash:

![wizard_dash](https://user-images.githubusercontent.com/6343103/186801371-edd141ce-9595-4ace-9a55-1da102065843.png)

**Comment by guidezpl** [comment]
Proposing https://github.com/engine-flutter-autoroll and https://github.com/fluttergithubbot. 

Would also like to see https://github.com/apps/flutter-dashboard be renamed to Dash :)

**Comment by keyonghan** [comment]
@godofredoc Do you have the edit access to these accounts?

**Comment by godofredoc** [comment]
No, we need to reach out to the skia team to get access to those accounts and document them as bots.

**Comment by zanderso** [comment]
@rmistry

**Comment by rmistry** [comment]
Done:
* https://github.com/skia-flutter-autoroll
* https://github.com/engine-flutter-autoroll 

(I prioritize anything to do with awesome avatars)

**Comment by zanderso** [comment]
Hooray! Thank you, @rmistry!

**Comment by guidezpl** [comment]
Nice! @godofredoc do you have access to https://github.com/apps/flutter-dashboard? It's usually the first bot folks interact with when opening PRs (it auto-labels), and it could use a clearer name and better avatar.

**Comment by godofredoc** [comment]
I do have access, changing the avatar is doable but changing the name may require changes in many places as it is hardcoded in systems we control and some others we don't control. For the image should I use the same one?

**Comment by CaseyHillers** [comment]
Changing the flutter-dashboard avatar has made it less clear what is Flutter CI in the GitHub checks.

![image](https://user-images.githubusercontent.com/2148558/186966362-9e5c8c95-aac1-4e7c-b0c2-8f4c47f41981.png)

Can we revert it back to the Flutter logo?

**Comment by godofredoc** [comment]
back to the flutter logo, please let me know how would you like to proceed.

**Comment by zanderso** [comment]
Things look great to me in the current state with Dash in the GitHub profile images. Thanks all!
