### ISSUE TITLE
How to detect memory leaks?

### ISSUE THREAD

**Issue by Inisit** [flutter/flutter#110322]
我编写的应用(大型项目),存在内存泄漏,内存一直居高不下, 创建的widget实例一直在增加,无法被GC回收掉, 有没有什么办法能准确定位到内存泄漏的代码位置? 就例如Android原生的LeakCanary的功能.

Translation:

The application I wrote (large-scale project) has memory leaks, the memory is always high, and the created widget instances keep increasing and cannot be recycled by GC. Is there any way to accurately locate the code location of the memory leak? For example, Android Native LeakCanary functionality.

![image](https://user-images.githubusercontent.com/24307544/186845488-37778e8e-bf72-4e64-917e-e3d181b0d07e.png)

**Comment by darshankawar** [comment]
@Inisit 
There are several articles and documents out there that shows how to detect memory leaks.

https://stackoverflow.com/questions/57674085/how-to-find-memory-leaks-in-flutter/62471179#62471179
https://github.com/flutter/flutter/issues/46050

https://docs.flutter.dev/development/tools/devtools/memory
https://www.alibabacloud.com/blog/exploring-memory-leaks-in-flutter-from-the-rendering-process_597736

There's also a community plugin that you can try and see if it suits your purpose: https://pub.dev/packages/leak_detector

And follow-up in this open issue for updates: https://github.com/flutter/devtools/issues/3951

Closing from here.
