### ISSUE TITLE
SharedPreferencesStorePlatform expects too narrow an exception when illegally implemented

### ISSUE THREAD

**Issue by stereotype441** [flutter/flutter#110364]
The `SharedPreferencesStorePlatform.instance` setter contains logic to try to detect when the class has been illegally subtyped using `implements` rather than `extends`.  This logic tries to invoke the private method `_verifyProvidesDefaultImplementations`, and checks if it results in a `NoSuchMethod` exception.  This works most of the time because a class that subtypes `SharedPreferencesStorePlatform` using `implements` can't possibly provide its own implementation of `_verifyProvidesDefaultImplementations`, so the invocation will be dispatched to `noSuchMethod`.  But there's a loophole: the class could bypass the check by having its own implementation of `noSuchMethod` that didn't throw an exception.

In order to close loopholes like this one, the Dart language will soon be changed so that attempts to invoke an unimplemented private method on a class in another library will result in an exception getting thrown.  That exception will most likely different from `NoSuchMethodError`.

So to prepare for this, the logic in `SharedPreferencesStorePlatform.instance` needs to be generalized to treat any exception thrown by `_verifyProvidesDefaultImplementations` as evidence that the class was illegally subtyped.

**Comment by stuartmorgan** [comment]
The fact that we're not using the shared logic is just a bug that we have for historical reasons: https://github.com/flutter/flutter/issues/98709

We should fix this by moving to the standard approach instead of further tweaking the custom historical implementation.

**Comment by stuartmorgan** [comment]
Closing as obsolete since the issue I mentioned above was fixed.
