### ISSUE TITLE
Linux firebase_release_smoke_test running for up to ~2 hours

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#110412]
This is a presubmit check that runs on Engine rolls, and I assume on other framework PRs as well.

It often runs for ~1 hour, and occasionally runs for up to 2 hours.

https://ci.chromium.org/p/flutter/builders/try/Linux%20firebase_release_smoke_test

It looks like the recipe is trying to set a 2 minute timeout here:

https://flutter.googlesource.com/recipes/+/refs/heads/main/recipes/firebaselab/firebaselab.py#117

but maybe that is just for the network request?

I wonder if there has been a change to which devices are "highly available" and the list here needs an update:

https://flutter.googlesource.com/recipes/+/refs/heads/main/recipes/firebaselab/firebaselab.py#42

cc @dnfield

**Comment by yusuf-goog** [comment]
@zanderso the increased durations seem to happen between 2022-08-26 7:37 PM (PDT) and 2022-08-27 6:50 AM (PDT).

It looks like the `--timeout` is for test run only, not accounting for device setup time.

Are you concerned about the timeout not being honored?

**Comment by zanderso** [comment]
@yusuf-goog I'm concerned that this test is taking a long time. The fact that `--timeout` doesn't appear to set an overall timeout for the whole test is just a piece of info that seemed like it might be useful for debugging.

**Comment by dnfield** [comment]
I revived an old thread with the firebase team to see if they have an update

**Comment by yusuf-goog** [comment]
@dnfield can you please add a link to the thread here

**Comment by yusuf-goog** [comment]
Setting to P3, because this test has been running at ~20mins for days. Leaving this open for followup from the issue @dnfield mentioned.

**Comment by yusuf-goog** [comment]
Assigning to @dnfield for issue follow up.

**Comment by dnfield** [comment]
Followed up with FTL team again, original message got lost somewhere, expecting an update today.

**Comment by dnfield** [comment]
Looking at recent runs, it looks like runtime is back down to about 18-30 minutes (with low 20s being most common).

FTL team says these are our queue times right now:



model | version | count | avg queue time | max queue time
-- | -- | -- | -- | --
Nexus6P | 26 | 18 | 0:02:05 | 0:07:04
Nexus5 | 21 | 18 | 0:02:06 | 0:07:04
Nexus5 | 23 | 18 | 0:02:06 | 0:07:04
Nexus6P | 25 | 18 | 0:02:06 | 0:07:04
Nexus6P | 27 | 18 | 0:02:06 | 0:07:04
Nexus5 | 19 | 18 | 0:01:54 | 0:06:14
NexusLowRes | 29 | 18 | 0:02:06 | 0:07:13
griffin | 24 | 18 | 0:03:25 | 0:07:44
blueline | 28 | 18 | 0:03:18 | 0:07:44
Nexus5 | 22 | 18 | 0:02:06 | 0:07:04
redfin | 30 | 140 | 0:01:35 | 0:13:19

**Comment by keyonghan** [comment]
Seems a transient issue related to FTL capacity. Ever since then, tests have been executed within 25mins range. Closing here.
Please reopen if you see this issue again.
