### ISSUE TITLE
Support camera_windows orientation (custom, lock, unlock)

### ISSUE THREAD

**Issue by cickpoo0121** [flutter/flutter#110445]
## Use case

     When I rotate my external camera, then a camera preview is also rotated.

## Proposal

     I hope we can at least set a default orientation. Thanks

**Comment by huycozy** [comment]
Hi @cickpoo0121, thanks for filing the issue. 
I see there's an open issue addressing the case you described #97540
Closing this issue as a duplicate, so please follow up on it for further updates. You can leave there your comment and react an upvote to the original comment will help to raise the issue. Thank you!
