### ISSUE TITLE
Allow engine_v2 recipes to fetch a build configuration from monorepo repository

### ISSUE THREAD

**Issue by whesse** [flutter/flutter#110481]
As with the engine_v2 coordinator recipe engine_v2 when it runs a flutter/engine build, I would like
the coordinator to download the build properties for the monorepo builds from a .json configuration
file in the monorepo repository.

This can be done by adding flexibility to the build properties download step, so it checks out the monorepo repository
instead of the engine repository. Exactly the same check as is used in 

https://flutter.googlesource.com/recipes/+/refs/heads/main/recipes/engine_v2/builder.py#207

can be added when downloading the config, to checkout monorepo instead of flutter/engine, and download from a path in that repo.

**Comment by keyonghan** [comment]
Has this been implemented?
