### ISSUE TITLE
flutter web app with Firefox 

### ISSUE THREAD

**Issue by charlesHenryPATARD** [flutter/flutter#110458]
Hi,

I wrote an app for web device. When I execute a `flutter run` command app works fine with all browsers (Chrome, Edge, Firefox). When I deploy with `flutter build web` on NodeJS server, the application doesn't work with Firefox. 

Here the error log with Firefox : 

![image](https://user-images.githubusercontent.com/2980963/187146408-1760879b-8945-4346-93df-e9aca945232a.png)

Version of Firefox 91.13.0esr

My flutter doctor : 

`[✓] Flutter (Channel stable, 3.0.3, on CentOS Linux 7 (Core) 3.10.0-1062.4.1.el7.x86_64, locale fr_FR.UTF-8)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✓] Chrome - develop for the web
[!] Linux toolchain - develop for Linux desktop
    ✗ pkg-config 0.29.0 or later is required.
[!] Android Studio (not installed)
[✓] IntelliJ IDEA Community Edition (version 2021.2)
[✓] VS Code (version 1.60.2)
[✓] Connected device (2 available)
[✓] HTTP Host Availability
`

**Comment by exaby73** [comment]
Hello @charlesHenryPATARD. Can you provide the following information:

- A [complete and minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).
- Detailed reproduction steps. If possible, try to deploy on a static CDN like [Netlify](https://netlify.com) and confirm whether the issue persists. 
- Output of `flutter doctor -v`

**Comment by charlesHenryPATARD** [comment]
Hi,

The bug is no page load with Firefox after a build and deploy web app. The same app works fine with Chrome and Edge.
In `flutter run` the app works fine.

-  A [complete and minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).

 I Execute `flutter run` and then display the dev tools of Chrome
 
![image](https://user-images.githubusercontent.com/2980963/187908977-7f157306-e4ef-4b47-918b-96b9acabdf4b.png)

Then I copy paste the flutter run url (example  http://localhost:40336/#/) in firefox. The app is displayed and works fine, but I've got this error in dev tools console : 

![image](https://user-images.githubusercontent.com/2980963/187909545-278563ad-a2f5-473e-a2b4-799afa32a44b.png)

After this steps I run a `flutter build web` and deploy the app on NodeJs server

When I display my app on Chrome everything is ok but on Firefox : 

![image](https://user-images.githubusercontent.com/2980963/187146408-1760879b-8945-4346-93df-e9aca945232a.png)

The 
- `flutter doctor -v`

[✓] Flutter (Channel stable, 3.0.3, on CentOS Linux 7 (Core) 3.10.0-1062.4.1.el7.x86_64, locale fr_FR.UTF-8)
    • Flutter version 3.0.3 at /home/patard/Logiciels/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 676cefaaff (2 months ago), 2022-06-22 11:34:49 -0700
    • Engine revision ffe7b86a1e
    • Dart version 2.17.5
    • DevTools version 2.12.2

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Chrome - develop for the web
    • Chrome at google-chrome

[!] Linux toolchain - develop for Linux desktop
    • clang version 3.4.2 (tags/RELEASE_34/dot2-final)
    • cmake3 version 3.17.5
    • ninja version 1.10.2
    • pkg-config version 0.27.1
    ✗ pkg-config 0.29.0 or later is required.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] IntelliJ IDEA Community Edition (version 2021.2)
    • IntelliJ at /home/patard/Logiciels/Intellij/idea-IC-212.5080.55
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.60.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.27.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • CentOS Linux 7 (Core) 3.10.0-1062.4.1.el7.x86_64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 93.0.4577.82

[✓] HTTP Host Availability
    • All required HTTP hosts are available

It's not a Flutter/Dart issue but a build JavaScript issue.

**Comment by exaby73** [comment]
Can you please provide a code sample so that I may verify this issue? Also, can you test on the latest stable `3.3.0` and confirm if the issue still persists?

**Comment by charlesHenryPATARD** [comment]
You want to test my app ? I can give you my code but you can't use it.
We use locale databases and one dart package that we wrote. I think that we have some trouble with our package. I need to make some tests and I will let you know.

**Comment by exaby73** [comment]
I do not need your app's code but rather a [complete and minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). A code sample which you are using to reproduce the issue. This could be a demo project too. If it's reproducible with the default counter app, please do mention that too.

**Comment by charlesHenryPATARD** [comment]
It's not reproducible with demo app. This is the reason why I think that we have introduced a bug with our homemade package.

**Comment by exaby73** [comment]
Unfortunately, without a way to reproduce this issue, we cannot verify and investigate it further. If you are able to produce a sample, please do post it here so that I can verify it. Thank you.

**Comment by charlesHenryPATARD** [comment]
Hi,

As I said in previous posts, we developped a Logger for flutter. I commented all calls to our Logger in my app and then deploy it. It's works now with firefox.

I give you our Logger code and yopu can try to use it in a testing app of your choice.

[logger.zip](https://github.com/flutter/flutter/files/9565138/logger.zip)

To use it you have to create a class like this : 

`import 'package:web_logger/web_logger.dart';

class AppLogger
{
    static WebLogger logger = new WebLogger();
}`

and then in each .dart file you can add a trace like this : 

`AppLogger.logger.enterMethodParam("blabla");

    AppLogger.logger.exitMethod();`

or with levels 
`AppLogger.logger.info("blabla");
AppLogger.logger.error("blabla");
AppLogger.logger.warning("blabla");
AppLogger.logger.verbose("blabla");
....
`
Thank you.

**Comment by exaby73** [comment]
Have you found the source of the issue? We would need a code sample that reproduces this issue. Unfortunately, the zip file you provided is too large with too much unnecessary code so I cannot really verify the issue. Could you provide a sample with minimal code, and without any 3rd party libraries included so that we can verify whether this is an error with Flutter or not.

**Comment by charlesHenryPATARD** [comment]
@exaby73 I have a other question for you.

Do the server and the client need to have an access to the internet ? 

I tested to deploy a web flutter on a local server that have no connection to the internet and the app doesn't works properly. Just because it's try to get the Material Icons on the web.

In the other side, I tried to use an app with a client that do not have access to the internet. The client try to download the canavaskit.js.

**Comment by exaby73** [comment]
> Do the server and the client need to have an access to the internet ?

If you use Canvaskit, yes the app will download the fonts and Canvaskit files from external URLs, meaning you need the internet. But if you use the HTML renderer by running `flutter run -d chrome --web-renderer html` or `flutter build web --web-renderer html`, it will download only the static files served on server you've deployed to, meaning you don't need internet past the files that Flutter generated

**Comment by charlesHenryPATARD** [comment]
Thank you @exaby73 for your answer, 
I will try to build my app with `--web-renderer` option. I think that we can close the issue.
