### ISSUE TITLE
Must elinux flutter run on the GPU?

### ISSUE THREAD

**Issue by fayfive** [flutter/flutter#110433]
Because I think that many embedded device have no GPU.
I want to know if elinux flutter can run on CPU?

**Comment by iapicca** [comment]
isn't this an issue with [flutter-elinux](https://github.com/sony/flutter-elinux/issues)?

**Comment by fayfive** [comment]
Sorry， I don't know you're together.
It seems that nobody answer me, so I come  here.

**Comment by iapicca** [comment]
not sure it's the place for this discussion, but just in case... cc @HidenoriMatsubayashi

**Comment by stuartmorgan** [comment]
Issues with third-party embeddings need to be reported to their developers, rather than to the Flutter project.
