### ISSUE TITLE
Severe scrolling glitch in [CustomScrollView]

### ISSUE THREAD

**Issue by b3nni97** [flutter/flutter#110400]
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. Quickly scroll to the bottom of the list and then quickly fling up a bit. (See video)
3. Sometimes step 2 has to be repeated several times so that the bug is visible

**Expected results:** 
The list should stop normally without jumps to other widgets.
**Actual results:** 
The list suddenly jumps to a completely different item

The problem was reproduced on an **iPhone X** on the **latest Maste**r Branch. I can't say whether the problem exists only for iOS.

<details>
<summary>Code sample</summary>

```dart
void main() {
  runApp(SimpleScrollApp());
}

class SimpleScrollApp extends StatelessWidget {
  final List<double> randomHeights = [
    500,
    700,
    400,
    400,
    300,
    200,
    300,
    500,
    900,
    500
  ];

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: CustomScrollView(
        slivers: [
          SliverList(
            delegate: SliverChildBuilderDelegate(
              (context, index) {
                return Container(
                  margin: EdgeInsets.all(12),
                  color: Colors.blue,
                  height: randomHeights[index],
                  child: Center(
                    child: Text(
                      index.toString(),
                    ),
                  ),
                );
              },
              childCount: randomHeights.length,
            ),
          ),
        ],
      ),
    );
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel master, 3.1.0-0.0.pre.2507, on macOS 12.4 21F79 darwin-arm, locale de-DE)
    • Flutter version 3.1.0-0.0.pre.2507 on channel master at /Users/x/Desktop/Programming/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9d8a29c97a (22 hours ago), 2022-08-26 03:02:31 -0400
    • Engine revision 1bc5d8c59e
    • Dart version 2.19.0 (build 2.19.0-141.0.dev)
    • DevTools version 2.16.0

[✓] Xcode - develop for iOS and macOS (Xcode 13.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F17a
    • CocoaPods version 1.11.3
```

</details>

https://user-images.githubusercontent.com/18357332/187016329-8acfcfc2-f56b-468c-b93d-f1eeae806a64.MP4

**Comment by amuchand47** [comment]
It's working perfectly on Android Device!

**Comment by au-top** [comment]
The same problem occurs in listview. As far as I know, this problem requires the latest pre version

And my friends in `3.1.0-0.0.pre 1228` flutter version no such problem


https://github.com/flutter/flutter/issues/110340

**Comment by iapicca** [comment]
@b3nni97 are you running it in `debug` mode?
what's the result with `flutter run --release`?

**Comment by b3nni97** [comment]
Hi @iapicca,

I can reproduce the bug in any mode.

Yes #110340 looks similar, also makes sense since ListView uses CustomScrollView internally.

**Comment by adilwahla** [comment]
@b3nni97 Hey use Scroll listener and scroll event 

```
_scrollListener() {
    if (_controller.offset >= _controller.position.maxScrollExtent &&
        !_controller.position.outOfRange) {
      setState(() {
        message = "reach the bottom";
      });
    }
    if (_controller.offset <= _controller.position.minScrollExtent &&
        !_controller.position.outOfRange) {
      setState(() {
        message = "reach the top";
      });
    }
  }
```
setstate() is your function :)
get completre insight here 
https://medium.com/@diegoveloper/flutter-lets-know-the-scrollcontroller-and-scrollnotification-652b2685a4ac

hope so closes #110400

**Comment by b3nni97** [comment]
@adilwahla  No, I think you misunderstand something. It should not be the task of the developer to call setstate at the beginning and at the end of the list. Besides, I don't see how that would solve the problem at all. 

As written in #110344 the bug is not reproducible with an older version and it should not be recommended to use a hacky workaround.

**Comment by knopp** [comment]
Might be helpful if you could bisect which commit exactly caused this.

**Comment by huycozy** [comment]
Hi @b3nni97 and anyone else facing this issue.
I can reproduce this issue on master channel `3.1.0-0.0.pre.2552` with provided sample code. On stable channel `3.0.5`, it works normally.
I also see there's an open issue addressing the case you described #110340 and it also happens on the latest master channel.
Closing this issue as a duplicate, so please follow up on it for further updates. You can leave there your comment and react an upvote to the original comment will help to raise the issue. 
Thank you!
