### ISSUE TITLE
Flutter not found the devices

### ISSUE THREAD

**Issue by Iamjustin25** [flutter/flutter#110476]
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.5, on Kali GNU/Linux Rolling 5.18.0-kali2-amd64, locale ar_EG.UTF-8)
Checking Android licenses is taking an unexpectedly long time...[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2021.2)
[✓] Android Studio
[✓] VS Code (version 1.70.1)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

• No issues found!

i use Kali Linux and when i use Vscode he dont find any devices like my Phone or emulator

![Screenshot_2022-08-29_15-25-04](https://user-images.githubusercontent.com/91855195/187211818-7f4dabb5-0365-433c-b06d-acf9a9f6980c.png)

**Comment by huycozy** [comment]
Hi @Iamjustin25 
What is the output of `flutter devices`? And please provide the output of `flutter doctor -v` as well. Thank you!

**Comment by Iamjustin25** [comment]
> أهلاً@Iamjustin25 ما هو ناتج `flutter devices`؟ ويرجى تقديم ناتج `flutter doctor -v`أيضًا. شكرًا لك!

flutter devices
3 connected devices:

4d006569ec9e5200 (mobile) • 4d006569ec9e5200 • android-arm    • Android 4.4.4 (API 19)
Linux (desktop)           • linux            • linux-x64      • Kali GNU/Linux Rolling
5.18.0-kali2-amd64
Chrome (web)              • chrome           • web-javascript • Google Chrome 103.0.5060.114

flutter devices -v
[ +118 ms] executing: uname -m
[  +44 ms] Exit code 0 from: uname -m
[        ] x86_64
[   +7 ms] executing: [/home/jus/development/flutter/] git -c log.showSignature=false log -n 1
--pretty=format:%H
[  +30 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] f1875d570e39de09040c8f79aa13cc56baab8db1
[   +1 ms] executing: [/home/jus/development/flutter/] git tag --points-at
f1875d570e39de09040c8f79aa13cc56baab8db1
[+1118 ms] Exit code 0 from: git tag --points-at f1875d570e39de09040c8f79aa13cc56baab8db1
[        ] 3.0.5
[  +19 ms] executing: [/home/jus/development/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +5 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/home/jus/development/flutter/] git ls-remote --get-url origin
[   +4 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +133 ms] executing: [/home/jus/development/flutter/] git rev-parse --abbrev-ref HEAD
[   +4 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[ +134 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +16 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +125 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[  +45 ms] executing: /home/jus/Android/Sdk/platform-tools/adb devices -l
[ +114 ms] List of devices attached
                    4d006569ec9e5200       device usb:1-1.2 transport_id:1
[   +5 ms] 3 connected devices:
           
[   +3 ms] /home/jus/Android/Sdk/platform-tools/adb -s 4d006569ec9e5200 shell getprop
[  +72 ms] ro.hardware = sc8830
[        ] ro.build.characteristics = phone
[ +250 ms] 4d006569ec9e5200 (mobile) • 4d006569ec9e5200 • android-arm    • Android 4.4.4 (API 19)
[   +3 ms] Linux (desktop)           • linux            • linux-x64      • Kali GNU/Linux Rolling
           5.18.0-kali2-amd64
[   +1 ms] Chrome (web)              • chrome           • web-javascript • Google Chrome
103.0.5060.114
[   +3 ms] executing: /home/jus/Android/Sdk/platform-tools/adb devices -l
[   +7 ms] List of devices attached
           4d006569ec9e5200       device usb:1-1.2 transport_id:1
[  +22 ms] "flutter devices" took 743ms.
[ +260 ms] ensureAnalyticsSent: 253ms
[   +2 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 0

**Comment by huycozy** [comment]
@Iamjustin25 
As far as I can see, `flutter devices` is working as expected. Looks like the issue comes from VS Code. 
Which VS Code version are you using? And please provide the output of `flutter doctor -v` as well. Thanks!

**Comment by Iamjustin25** [comment]
@huycozy 
yes when i open vscode and search for see any devices and dont found anything like my Screenshot

VS Code (version 1.70.1)

flutter doctor -v
[✓] Flutter (Channel stable, 3.0.5, on Kali GNU/Linux Rolling 5.18.0-kali2-amd64, locale ar_EG.UTF-8)
    • Flutter version 3.0.5 at /home/jus/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (7 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

Checking Android licenses is taking an unexpectedly long time...[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /home/jus/Android/Sdk/
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /home/jus/Downloads/android-studio/jre/bin/java
    • Java version openjdk version "11.0.12" 2021-07-20
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Debian clang version 14.0.6-2
    • cmake version 3.23.3
    • ninja version 1.11.0
    • pkg-config version 0.29.2

[✓] Android Studio (version 2021.2)
    • Android Studio at /home/jus/Downloads/android-studio
    • Flutter plugin version 69.0.2
    • Dart plugin version 212.5744
    • Java version openjdk version "11.0.12" 2021-07-20

[✓] Android Studio
    • Android Studio at /home/jus/Downloads/android-studio/
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /home/jus/Downloads/android-studio/
    • Java version openjdk version "11.0.12" 2021-07-20

[✓] VS Code (version 1.70.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.46.0

[✓] Connected device (3 available)
    • 4d006569ec9e5200 (mobile) • 4d006569ec9e5200 • android-arm    • Android 4.4.4 (API 19)
    • Linux (desktop)           • linux            • linux-x64      • Kali GNU/Linux Rolling
      5.18.0-kali2-amd64
    • Chrome (web)              • chrome           • web-javascript • Google Chrome 103.0.5060.114

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Comment by huycozy** [comment]
Hi @Iamjustin25, thanks for providing more information. Based on the `flutter doctor -v` output, looks like it's fine from flutter side. I see there are some issues that have been solved in [Dart-Code repository](https://github.com/Dart-Code/Dart-Code/):
- https://github.com/Dart-Code/Dart-Code/issues/1634
- https://github.com/Dart-Code/Dart-Code/issues/3409

Please open the issue in the dedicated [Dart-Code](https://github.com/Dart-Code/Dart-Code/issues/) so that you will have better support there.
Closing, as this isn't an issue with Flutter itself.  
Thank you!
