### ISSUE TITLE
Google Maps android unusable

### ISSUE THREAD

**Issue by NikosTsesmelis** [flutter/flutter#110467]
As mentioned in https://github.com/flutter/flutter/issues/105965 google maps in android crashes with said exception.

There is this fix described here https://github.com/flutter/flutter/issues/105965#issuecomment-1224473127 which indeed fixes the crashes but introduces a behaviour similar to this bug here https://github.com/flutter/flutter/issues/103686 (which seemed like it was fixed on beta).

This happens when using the fix and setting the latest rendered.
https://user-images.githubusercontent.com/100851392/187184031-8c6f86bb-83ef-4ffd-95a2-cd63ab90ae2e.mp4

Also there is also a bug with the padding https://github.com/flutter/flutter/issues/43721 that makes it impossible to upgrade the google_maps_flutter plugin above version 2.1.7 which means that if these are fixed on the plugin we will be unable to actually update to latest version.

We have been working on this app for a year and it was supposed to go live 2 months ago.

Biggest problem is that it doesn't seem like these bugs are even a priority and they don't seem to be fixed any time soon.

What don't know what to do. Can these somehow get priority so we can upload?

[✓] Flutter (Channel beta, 3.3.0-0.5.pre, on macOS 12.3.1 21E258 darwin-arm, locale en-GR)
    • Flutter version 3.3.0-0.5.pre on channel beta at /Users/nikostsesmelis/Tools/flutter/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 096162697a (6 days ago), 2022-08-22 15:34:14 -0700
    • Engine revision ad3d868e0d
    • Dart version 2.18.0 (build 2.18.0-271.7.beta)
    • DevTools version 2.15.0

**Comment by stuartmorgan** [comment]
Please see https://github.com/flutter/flutter/wiki/Issue-hygiene#escalating-an-issue-that-has-the-wrong-priority for information about escalating issues.

Closing as we don't use new issues for escalations, and the bugs discussed here are all already tracked.
