### ISSUE TITLE
Video player (file) randomly fails to initialize

### ISSUE THREAD

**Issue by Shawn-sudo** [flutter/flutter#110453]
[video_player](https://pub.dev/packages/video_player) randomly fails to initialize. I specifically used `VideoPlayerController.file(filepathwhatever)` on iOS real device.

### What happens once it occurs
Once it fails, attempts to initialize and start playing other VideoPlayers also fail for 5-6 times. Then suddenly everything seems to be working fine, with seekbar position updated (fetch from `videoPlayerController.position` once a 100 milliseconds) and play/pause state updated (`videoPlayerController.addLisenter(codeforupdatingthestatehere)`). However, sound doesn't come out. 

#### Steps to reproduce
This error seems to occur randomly, and I cannot comprehend what the log is saying, so I'll just share what I did.
1. Put bunch of random audio/video files in a local directory on iOS real device 
2. Manage `VideoPlayerController` for each audio/video in `Map<String, VideoPlayerController> videoPlayers`. The key (String) can be the file path.
3. Randomly play those audios/videos. Before `.play()`, call `await theVideoPlayerController.initialize()` if it hasn't been initialized. Also before `.play()` `.pause()` for all the other players that are playing (`await Future.forEach(videoPlayers.values, (videoPlayer) async {if (check if the videoPlayer is playing) {videoPlayer.pause()}})`).
4. Randomly call dispose for some `VideoPlayerController`. After calling `.dispose()`, make it null to indicate that the controller needs to be declared again.
5. Do those actions super fast, and the error would occur one day

#### Weird interactions with screen recording 
(This is just an observation, not the main issue) Weirdly, when I start screen recording, the sound comes out at about 25% volume from the real device. When the screen recording ends, the sound doesn't come out again. The screen recorded result contains the sound with 100% volume though. This may indicate that it's an issue of interacting with audio session.
[audio_session](https://pub.dev/packages/audio_session) exists in the `pubspec.yaml`, but the app use it only to listen to audio interruptions: it never calls audio_session's `.configure(configure audio session here)` or `.setActive(true/false)`

#### Devices
This has never occurred on iOS simulator, at least for me.

#### How I used [video_player](https://pub.dev/packages/video_player)
Let me tell you the specific use case of [video_player](https://pub.dev/packages/video_player) on my app. My app initializes `VideoPlayerController` when the corresponding widget initializes. For example, `PostViewer` (personal code), which is usually a children of a `ListView`, is used to show video containing posts. On a `PostViewer`'s `initState()`, the corresponding `VideoPlayer` is initialized. On the `PostViewer`'s `dispose()`, the corresponding `VideoPlayer` is disposed (`videoPlayer.dispose()`) so that I don't keep too many `VideoPlayerController` alive at once (https://github.com/flutter/flutter/issues/25558).

### Log
```
2022-08-28 22:43:34.719677-0400 Runner[27653:1994460] [as]    AudioSessionClient.cpp:156   Unable to talk to server: error 0x10000003 (268435459)
2022-08-28 22:43:34.720017-0400 Runner[27653:1994460] [avas]     AVAudioSession_iOS.mm:778   Synchronous connection to media server failed. Starting asynchronous connection attempt for session 0x280aafb50.
2022-08-28 22:43:34.720131-0400 Runner[27653:1994460] [avas] AVAudioSessionUtilities.h:178   AudioSessionGetProperty ('rsid') failed with error: '!ini'
2022-08-28 22:43:34.720165-0400 Runner[27653:1994460] [avas] AVAudioSessionUtilities.h:202   AudioSessionGetProperty ('rsid') failed with error: '!ini'
2022-08-28 22:43:35.191907-0400 Runner[27653:1994185] [VERBOSE-2:ui_dart_state.cc(198)] Unhandled Exception: PlatformException(VideoError, Failed to load video: The operation could not be completed, null, null)
2022-08-28 22:43:35.192095-0400 Runner[27653:1994185] [VERBOSE-2:ui_dart_state.cc(198)] Unhandled Exception: PlatformException(VideoError, Failed to load video: The operation could not be completed, null, null)
2022-08-28 22:43:35.217692-0400 Runner[27653:1994460] [hapi]         CHHapticEngine.mm:455   -[CHHapticEngine setupUnsharedAudioSessionAndReturnError:]: Failed to set category on audio session
2022-08-28 22:43:35.217830-0400 Runner[27653:1994460] [Feedback] failed initializing core haptics engine for <_UIFeedbackCoreHapticsHapticsOnlyEngine: 0x2823d09a0>: Error Domain=NSOSStatusErrorDomain Code=1836282486 "(null)"
2022-08-28 22:46:59.528290-0400 Runner[27653:1994365] [connection] nw_read_request_report [C5] Receive failed with error "Operation timed out"
2022-08-28 22:46:59.528664-0400 Runner[27653:1994365] [connection] nw_read_request_report [C5] Receive failed with error "Operation timed out"
```
I can see haptic (`HapticFeedback`) related logs here, but I don't think haptic-calling function was called when the error occurred. My app calls `HapticFeedback.impact()` only when a button is pushed, and I was only scrolling through a post feed that I made 🤔.
Wish this log be helpful for you to understand my situation tho. I can barely understand what is going on there 😵‍💫.

**Comment by huycozy** [comment]
Hi @Shawn-sudo, thanks for filing the issue. 
Please provide more information so that we may verify this properly.
Which `video_player` plugin version are you using? Does this issue happen with Android?
Also, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) and the output of `flutter doctor -v`. In this case, it would be better if you could push the sample code into a Github repository and make it public.
Thank you!

**Comment by Shawn-sudo** [comment]
Hi! thanks for your reply.

I'm using video_player version 2.4.5

For minimal reproducible code sample, I can share you the code that I wrote for managing video players: https://gist.github.com/Shawn-sudo/2666790fa21723829376cbae5eea52c3
More descriptions in the gist

flutter doctor -v:
```
shawn@Shawns-MacBook-Pro atrablechat % flutter doctor -v
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.5 21G72 darwin-arm, locale en-US)
    • Flutter version 3.0.5 at /Users/shawn/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (7 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/shawn/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.70.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.46.0

[✓] Connected device (3 available)
    • iPhone 13 Pro Max (mobile) • 336C6F53-76FB-4F59-9564-56EFD537A868 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-5 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 12.5 21G72 darwin-arm
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 104.0.5112.101

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
This has happened only in real device (my phone), but my phone is not in the connected device list. It's iPhone 13 running iOS 15.6.1

**Comment by huycozy** [comment]
Hi @Shawn-sudo, thanks for providing more information but the [gist you provided](https://github.com/flutter/flutter/issues/110453#issuecomment-1230307547) is not a minimal reproducible code sample. Please access https://stackoverflow.com/help/minimal-reproducible-example to know how to create such a sample code, so that we can directly copy-paste, and run to verify this issue.

**Comment by Shawn-sudo** [comment]
@huycozy Ye I gotta give you the full code that is launch-able right away 😼.

I just have a concern, though. This error randomly occurs for me. This sometimes occurs often but sometimes doesn't occurs at all. Even if you succeed to reproduce it, it would only throw the error that is shown in the log. Before we continue putting some efforts into this issue, can we (or anybody who wants to) understand what went wrong looking the log there?

If the log is insufficient, I can make the full error-reproducible code and share it.

**Comment by Shawn-sudo** [comment]
Reading the log, I've just found out that there's no such file as AVAudioSessionUtilities.h in [video_player_avfoundation](https://github.com/flutter/plugins/tree/main/packages/video_player/video_player_avfoundation). 
Searching it, I found a similar question [AVAudioSession sudden interruptions for no explicit reason](https://developer.apple.com/forums/thread/663604?answerId=640484022#640484022), but it has no solution there
[A similar question's answer](https://stackoverflow.com/a/31838886/13537773)

The error is only from AudioSession and HapticEngine.

I guess something went wrong, but not directly due to video_player

Probably audio_session randomly calls a wrong configuration, causing the strange behavior (my app does use audio_session, but it never calls `audioSession.configure()` or `.setActive()`)
Probably some flutter-native bridging channel name overlaps

hmm ig the log is insufficient to solve this bug

**Comment by huycozy** [comment]
Hi @Shawn-sudo 
Based on your logs, I can't find a similar/duplicate issue that was filed before. This may be a new issue of `video_player`.
There is an open issue that also failed to load video #56665 but it's about playing `network` file. 
Are there full logs that you can provide us? 
It will be better if you can provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this issue (Please don't share your full source code, it will make the investigation harder). 
Thank you!

**Comment by Shawn-sudo** [comment]
@huycozy hmm🤔🧐
I'm just confused making the minimal reproducible code. 
I mean, i don't know exactly in what circumstances the error occurs. I only know that i used multiple VideoPlayerController.file(), so should i have to make a minimal sample app that loads and play multiple audios and videos in certain local directory?

**Comment by huycozy** [comment]
@Shawn-sudo 
>so should i have to make a minimal sample app that loads and play multiple audios and videos in certain local directory?

Yes. It would be great if you could provide such an example. There is also an example from `video_player` plugins [here](https://github.com/flutter/plugins/tree/main/packages/video_player/video_player/example). You can fork and modify it according to your case then push to your Github repository. By this way, it won't take much effort to create a minimal reproducible code. Thanks for your efforts.

**Comment by Shawn-sudo** [comment]
@huycozy Thanks for your efforts too! Really appreciate it.
Btw, I was debugging my app today, and sadly (or fortunately), this error didn't occur at all. I'll make the minimal sample app after I find a specific circumstance to reproduce this error.

Also, can you add `p:video_player` label if you have an authority to do it? I don't have the authority to do it, so yea.
Thank you!

**Comment by huycozy** [comment]
@Shawn-sudo 
>Btw, I was debugging my app today, and sadly (or fortunately), this error didn't occur at all.

It may be related to the device you are testing, please do the test on all devices you have and try to find one that the issue is reproducible all the time.

>Also, can you add p:video_player label if you have an authority to do it? I don't have the authority to do it, so yea.

Unfortunately I can't label the issue right now as the issue is not clear. When labelling an issue, it's not only has an affected plugin's label, but also the relevant labels, such as: affected environment/device, which version can be reproducible, backward compatible or not, etc.
