### ISSUE TITLE
BoxDecoration's gradient update not reflected in Container widget.

### ISSUE THREAD

**Issue by SahajRana** [flutter/flutter#110434]
Hi Flutter team, 

I want to bring your attention to this bug, where the BoxDecoration's gradient update is not reflected in the `Container` widget. 
![Screenshot (495)](https://user-images.githubusercontent.com/16938202/187077221-ffbb1778-6285-4dfa-b55d-0d166bc147e8.png)

I think it is happening because the `==` in the line `if (value == _decoration)` is not correctly checking the gradient values.
This problem is there for quite some time now, & I have to make changes to flutter SDK on my end every time I update the Flutter version. 

So, I thought to put it here as well. Please let me know, I can add the PR as well. 

To reproduce it you would have to use GlobalKey in the parent of that container.

Something like,

```
 return key.currentWidget??Container(
    key: key,
    child: MyContainer(),
  );
```
Note: MyContainer is a stateful widget.

Then, inside `MyContainer`'s `build(...)` method,
```
 return Container(
    decoration: BoxDecoration(gradient: ...)
  );
```

And then you change the gradient dynamically.

**Comment by danagbemava-nc** [comment]
Hi @SahajRana,

Can you please provide your `flutter doctor -v` and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we can verify this?

Thank you
