### ISSUE TITLE
fix Typeahead related debug warnings

### ISSUE THREAD

**Issue by rlimberger** [flutter/flutter#110446]
When debugging a minimal Flutter (stable) application in vscode you will observe the following wiring in the debug console:

```
: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
../…/src/flutter_typeahead.dart:632
- 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../development/flutter/packages/flutter/lib/src/widgets/binding.dart').
package:flutter/…/widgets/binding.dart:1
    WidgetsBinding.instance!.removeObserver(this);
```

These warnings stem from a package named `Typeahead` that Flutter seems to be depending on. These warnings are distracting and misleading when trying to debug one's own application.

Please update the version of the Typeahead package. 

Thank you.

**Comment by jonahwilliams** [comment]
Flutter does not depend on any typeahead packages. The complete set of dependencies for the SDK can be found here: https://github.com/flutter/flutter/blob/master/packages/flutter/pubspec.yaml

Ultimately you'll need to raise the issue with the maintainers of the typeahead package. If you're not depending on that directly, then you could look up the correct transitive dependency using `dart pub deps`.
