### ISSUE TITLE
Toggle Select Widget Mode Doesnt Stop

### ISSUE THREAD

**Issue by emreozsoy** [flutter/flutter#110439]
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2.I opened "Flutter Inspection" and "Toggle select click mode",
3. Then when I stopped my project "Toggle select click mode" didn't lost.

**Comment by exaby73** [comment]
Hello @emreozsoy. I do not see a code sample attached to your comment. Please provide the following information:

- A [complete and minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).
- The output of `flutter doctor -v`

Thank you.
