### ISSUE TITLE
Save us from setting up CORS & it's long list of close friends & relatives

### ISSUE THREAD

**Issue by KimAloy** [flutter/flutter#110472]
Coding in flutter is a breeze... until you try deploying the web app to Firebase. It's a jungle, only the fittest survive, those of us who are novice, that's days upon days of trying to host the website on Firebase. 

All I really want to actually do is simply run "firebase deploy" and whatever it takes to actually deploy the web app should be handled without my knowledge whatsoever... the installing of node.js and updating "npm install -g firebase-tools" and running gs://bucket, and worrying if on this "firebase init" turn I should enter Y/n, or realizing that I have to re-auth my google account, then I must switch between Google Cloud SDK and cmd and Android Studio terminals. After all this, the images simply don't appear in the desktop/laptop browser!

The life of a novice flutter web developer shouldn't be this hard just to deploy to Firebase.

Thank you

**Comment by danagbemava-nc** [comment]
Hi @KimAloy, the setup and delivery process to firebase and firebase related tools are not controlled by the flutter team and any difficulties you face in using those tools should be reported to the appropriate repo. 

Closing as this is not an issue with flutter.

Thank you
