### ISSUE TITLE
Flutter web firebase storage images showing in mobile chrome browser but not in desktop/laptop browser

### ISSUE THREAD

**Issue by KimAloy** [flutter/flutter#110471]
Firebase Storage images are showing in the mobile phone chrome browser as expected, but running the same web app in the desktop/laptop chrome browser on Windows PC, no images appear at all.

I've set up CORS correctly (4 times in fact). I think that if CORS weren't correctly set up, then running the web app in the mobile chrome browser wouldn't show pictures.

Please try running this web app link on in your mobile browser and then your desktop/laptop browser & take a look... https://kisakye-online-services.web.app/

Here's a sample URL for one of the images: https://firebasestorage.googleapis.com/v0/b/kisakye-online-services.appspot.com/o/Kisakye%2FDriving%20Glasses%20-%202022-08-27%2013%3A57%3A46.563?alt=media&token=d3408061-c51f-4b18-b5b4-e801072162d7

Thanks

**Comment by huycozy** [comment]
Hi @KimAloy
I open [your website](https://kisakye-online-services.web.app) but it displays normally on both mobile browser and desktop browser (please see in demo):

<details>
<summary>Demo</summary>

- Source image:
![Screenshot 2022-08-30 at 11 10 12](https://user-images.githubusercontent.com/104349824/187347357-6788145a-eeca-4c1e-8002-d3637372df9c.png)


- Open web on mobile browser:
![Screenshot 2022-08-30 at 11 00 35](https://user-images.githubusercontent.com/104349824/187346237-1ffd595a-0ee1-47e4-8a46-4bf7266fda98.png)

- Open web on desktop browser:

| MacOS | Windows |
| --------------- | --------------- |
<img width="400" src="https://user-images.githubusercontent.com/104349824/187346262-1282aed3-813c-4b1d-9472-ac37efca77ce.png"> | <img width="400" src="https://user-images.githubusercontent.com/104349824/187347446-7464644f-5124-43c0-96d3-84a1e7f7abce.PNG">

</details>

Please provide detailed device information and the output of `flutter doctor -v` as well.

**Comment by KimAloy** [comment]
I've updated google chrome desktop browser and now the images are showing fine.
Thank you very much @huycozy for the quick assistance.

**Comment by huycozy** [comment]
Glad to see you solved it. Close the issue as solved. Thank you!
