### ISSUE TITLE
[ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: PlatformException(sign_in_failed, com.google.android.gms.common.api.ApiException: 10: , null, null)

### ISSUE THREAD

**Issue by wontlearn2codewithme** [flutter/flutter#110435]
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. Login screen shows off allowing me to use the google sign in
![image](https://user-images.githubusercontent.com/81021336/187078073-cf2646aa-eaaa-4489-b4ab-88dffeaa717c.png)
3. using Google sign in returns the following error:
E/flutter (10487): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: PlatformException(sign_in_failed, com.google.android.gms.common.api.ApiException: 10: , null, null)
E/flutter (10487): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
E/flutter (10487): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:167:18)
E/flutter (10487): <asynchronous suspension>
E/flutter (10487): #2      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:367:43)
E/flutter (10487): <asynchronous suspension>
E/flutter (10487): #3      GoogleSignIn._callMethod (package:google_sign_in/google_sign_in.dart:247:30)
E/flutter (10487): <asynchronous suspension>
E/flutter (10487): #4      GoogleSignIn.signIn.isCanceled (package:google_sign_in/google_sign_in.dart:377:5)
E/flutter (10487): <asynchronous suspension>
E/flutter (10487): 
**Expected results:**
The home screen of the app
![image](https://user-images.githubusercontent.com/81021336/187078138-8ed4846e-de15-4f5e-9a92-cd3e1372a53a.png)

**Actual results:** 
It won't navigate to the next screen and stay in login page.

<details>
<summary>Code sample</summary>

```dart
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';
import 'package:google_sign_in/google_sign_in.dart';
import 'package:myapp/services/auth.dart';

class Login extends StatelessWidget {
  const Login({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Container(
        padding: const EdgeInsets.all(30),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.stretch,
          mainAxisAlignment: MainAxisAlignment.spaceEvenly,
          children: [
            const FlutterLogo(
              size: 150,
            ),
            Flexible(
              child: LoginButton(
                color: Colors.deepPurple,
                iconData: FontAwesomeIcons.userNinja,
                text: 'Continue as guest',
                loginMethod: AuthService().anonymousLogin,
              ),
            ),
            Flexible(
              child: LoginButton(
                color: Colors.blue,
                iconData: FontAwesomeIcons.google,
                text: 'Sign in with your Google account',
                loginMethod: AuthService().googleLogin,
              ),
            ),
          ],
        ),
      ),
    );
  }

  Future<void> anonymousLogin() async {
    try {
      await FirebaseAuth.instance.signInAnonymously();
    } on FirebaseAuthException catch (e) {
      debugPrint(e.toString());
    }
  }

  Future<void> signOut() async {
    await FirebaseAuth.instance.signOut();
  }

  Future<void> googleLogin() async {
    try {
      final googleUser = await GoogleSignIn().signIn();
      if (googleUser == null) {
        return;
      }
      final googleAuth = await googleUser.authentication;
      final authCredential = GoogleAuthProvider.credential(
        accessToken: googleAuth.accessToken,
        idToken: googleAuth.idToken,
      );
      await FirebaseAuth.instance.signInWithCredential(authCredential);
    } on FirebaseAuthException catch (e) {
      debugPrint(e.toString());
    }
  }
}

class LoginButton extends StatelessWidget {
  final Color color;
  final IconData iconData;
  final String text;
  final Function loginMethod;

  const LoginButton(
      {Key? key,
      required this.color,
      required this.iconData,
      required this.text,
      required this.loginMethod})
      : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Container(
      margin: const EdgeInsets.only(
        bottom: 10,
      ),
      child: ElevatedButton.icon(
        onPressed: () => loginMethod(),
        icon: Icon(
          iconData,
          color: Colors.white,
          size: 20,
        ),
        label: Text(
          text,
          textAlign: TextAlign.center,
        ),
        style: TextButton.styleFrom(
          padding: const EdgeInsets.all(24),
          backgroundColor: color,
        ),
      ),
    );
  }
}

```

</details>

<details>
  <summary>Logs</summary>
Error log:
E/flutter (10487): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: PlatformException(sign_in_failed, com.google.android.gms.common.api.ApiException: 10: , null, null)
E/flutter (10487): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
E/flutter (10487): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:167:18)
E/flutter (10487): <asynchronous suspension>
E/flutter (10487): #2      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:367:43)
E/flutter (10487): <asynchronous suspension>
E/flutter (10487): #3      GoogleSignIn._callMethod (package:google_sign_in/google_sign_in.dart:247:30)
E/flutter (10487): <asynchronous suspension>
E/flutter (10487): #4      GoogleSignIn.signIn.isCanceled (package:google_sign_in/google_sign_in.dart:377:5)
E/flutter (10487): <asynchronous suspension>
E/flutter (10487): 

flutter run --verbose is too big to paste it as is here, I've created a pastebin https://pastebin.com/CE4d02zF
```
```

```
Analyzing myapp...                                                      

   info • Unused import: 'package:myapp/home/home.dart' • lib/main.dart:5:8 • unused_import
   info • Unused import: 'package:myapp/topics/topics_drawer.dart' • lib/profile/profile.dart:4:8 • unused_import
   info • Unused import: 'package:provider/provider.dart' • lib/profile/profile.dart:5:8 • unused_import
   info • Unused import: '../services/models.dart' • lib/profile/profile.dart:8:8 • unused_import
   info • Do not use BuildContexts across async gaps • lib/profile/profile.dart:137:17 • use_build_context_synchronously
   info • The import of 'package:flutter/cupertino.dart' is unnecessary because all of the used elements are also provided by the import of 'package:flutter/material.dart' •
          lib/shared/loading.dart:1:8 • unnecessary_import
   info • Don't import implementation files from another package • lib/shared/loading.dart:3:8 • implementation_imports
   info • The import of 'package:flutter/src/foundation/key.dart' is unnecessary because all of the used elements are also provided by the import of 'package:flutter/cupertino.dart' •
          lib/shared/loading.dart:3:8 • unnecessary_import
   info • Don't import implementation files from another package • lib/shared/loading.dart:4:8 • implementation_imports
   info • The import of 'package:flutter/src/widgets/framework.dart' is unnecessary because all of the used elements are also provided by the import of 'package:flutter/cupertino.dart' •
          lib/shared/loading.dart:4:8 • unnecessary_import

10 issues found. (ran in 2.0s)
```

```
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.5.1 21G83 darwin-arm, locale es-ES)
    • Flutter version 3.0.5 at /Users/victorgarciaexposito/projects/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (hace 7 semanas), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/victorgarciaexposito/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = /Users/victorgarciaexposito/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer/.
    • CocoaPods version 1.11.2

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.70.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.46.0

[✓] Connected device (2 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64 • Android 12 (API 31) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64  • macOS 12.5.1 21G83 darwin-arm

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

</details>

**Comment by Onein** [comment]
To use google_sign_in in debug builds you need to add the SHA1 fingerprint from your debug certificate to your google-services.json

Take a look at https://developers.google.com/android/guides/client-auth

**Comment by wontlearn2codewithme** [comment]
Hi Tim, thanks for your fast answer.

I already did it, as well as checking the Google Cloud OAuth consent. You
may find the evidences in the screenshots below:
[image: image.png]

result from executing signingReport
Starting a Gradle Daemon (subsequent builds will be faster)

> Task :app:signingReport
Variant: debug
Config: debug
Store: /Users/victorgarciaexposito/.android/debug.keystore
Alias: AndroidDebugKey
MD5: 48:CD:95:AB:A5:1E:06:3D:CD:66:D1:05:DC:AF:DB:7C
SHA1: A6:1B:27:3C:06:BE:C8:00:34:EC:50:FC:81:7D:C7:88:4B:B4:1B:E9
SHA-256:
D6:26:47:B5:4A:52:7D:97:D8:80:73:3E:88:70:8A:00:CE:7F:C4:6D:1D:18:69:62:95:3C:13:02:A2:7C:A6:9C
Valid until: lunes, 20 de noviembre de 2051
----------
Variant: release
Config: debug
Store: /Users/victorgarciaexposito/.android/debug.keystore
Alias: AndroidDebugKey
MD5: 48:CD:95:AB:A5:1E:06:3D:CD:66:D1:05:DC:AF:DB:7C
SHA1: A6:1B:27:3C:06:BE:C8:00:34:EC:50:FC:81:7D:C7:88:4B:B4:1B:E9
SHA-256:
D6:26:47:B5:4A:52:7D:97:D8:80:73:3E:88:70:8A:00:CE:7F:C4:6D:1D:18:69:62:95:3C:13:02:A2:7C:A6:9C
Valid until: lunes, 20 de noviembre de 2051
----------
Variant: profile
Config: debug
Store: /Users/victorgarciaexposito/.android/debug.keystore
Alias: AndroidDebugKey
MD5: 48:CD:95:AB:A5:1E:06:3D:CD:66:D1:05:DC:AF:DB:7C
SHA1: A6:1B:27:3C:06:BE:C8:00:34:EC:50:FC:81:7D:C7:88:4B:B4:1B:E9
SHA-256:
D6:26:47:B5:4A:52:7D:97:D8:80:73:3E:88:70:8A:00:CE:7F:C4:6D:1D:18:69:62:95:3C:13:02:A2:7C:A6:9C
Valid until: lunes, 20 de noviembre de 2051
----------
Variant: debugAndroidTest
Config: debug
Store: /Users/victorgarciaexposito/.android/debug.keystore
Alias: AndroidDebugKey
MD5: 48:CD:95:AB:A5:1E:06:3D:CD:66:D1:05:DC:AF:DB:7C
SHA1: A6:1B:27:3C:06:BE:C8:00:34:EC:50:FC:81:7D:C7:88:4B:B4:1B:E9
SHA-256:
D6:26:47:B5:4A:52:7D:97:D8:80:73:3E:88:70:8A:00:CE:7F:C4:6D:1D:18:69:62:95:3C:13:02:A2:7C:A6:9C
Valid until: lunes, 20 de noviembre de 2051
----------

> Task :cloud_firestore:signingReport
Variant: debugAndroidTest
Config: debug
Store: /Users/victorgarciaexposito/.android/debug.keystore
Alias: AndroidDebugKey
MD5: 48:CD:95:AB:A5:1E:06:3D:CD:66:D1:05:DC:AF:DB:7C
SHA1: A6:1B:27:3C:06:BE:C8:00:34:EC:50:FC:81:7D:C7:88:4B:B4:1B:E9
SHA-256:
D6:26:47:B5:4A:52:7D:97:D8:80:73:3E:88:70:8A:00:CE:7F:C4:6D:1D:18:69:62:95:3C:13:02:A2:7C:A6:9C
Valid until: lunes, 20 de noviembre de 2051
----------

> Task :firebase_auth:signingReport
Variant: debugAndroidTest
Config: debug
Store: /Users/victorgarciaexposito/.android/debug.keystore
Alias: AndroidDebugKey
MD5: 48:CD:95:AB:A5:1E:06:3D:CD:66:D1:05:DC:AF:DB:7C
SHA1: A6:1B:27:3C:06:BE:C8:00:34:EC:50:FC:81:7D:C7:88:4B:B4:1B:E9
SHA-256:
D6:26:47:B5:4A:52:7D:97:D8:80:73:3E:88:70:8A:00:CE:7F:C4:6D:1D:18:69:62:95:3C:13:02:A2:7C:A6:9C
Valid until: lunes, 20 de noviembre de 2051
----------

> Task :firebase_core:signingReport
Variant: debugAndroidTest
Config: debug
Store: /Users/victorgarciaexposito/.android/debug.keystore
Alias: AndroidDebugKey
MD5: 48:CD:95:AB:A5:1E:06:3D:CD:66:D1:05:DC:AF:DB:7C
SHA1: A6:1B:27:3C:06:BE:C8:00:34:EC:50:FC:81:7D:C7:88:4B:B4:1B:E9
SHA-256:
D6:26:47:B5:4A:52:7D:97:D8:80:73:3E:88:70:8A:00:CE:7F:C4:6D:1D:18:69:62:95:3C:13:02:A2:7C:A6:9C
Valid until: lunes, 20 de noviembre de 2051
----------

> Task :google_sign_in_android:signingReport
Variant: debugAndroidTest
Config: debug
Store: /Users/victorgarciaexposito/.android/debug.keystore
Alias: AndroidDebugKey
MD5: 48:CD:95:AB:A5:1E:06:3D:CD:66:D1:05:DC:AF:DB:7C
SHA1: A6:1B:27:3C:06:BE:C8:00:34:EC:50:FC:81:7D:C7:88:4B:B4:1B:E9
SHA-256:
D6:26:47:B5:4A:52:7D:97:D8:80:73:3E:88:70:8A:00:CE:7F:C4:6D:1D:18:69:62:95:3C:13:02:A2:7C:A6:9C
Valid until: lunes, 20 de noviembre de 2051
----------

> Task :path_provider_android:signingReport
Variant: debugAndroidTest
Config: debug
Store: /Users/victorgarciaexposito/.android/debug.keystore
Alias: AndroidDebugKey
MD5: 48:CD:95:AB:A5:1E:06:3D:CD:66:D1:05:DC:AF:DB:7C
SHA1: A6:1B:27:3C:06:BE:C8:00:34:EC:50:FC:81:7D:C7:88:4B:B4:1B:E9
SHA-256:
D6:26:47:B5:4A:52:7D:97:D8:80:73:3E:88:70:8A:00:CE:7F:C4:6D:1D:18:69:62:95:3C:13:02:A2:7C:A6:9C
Valid until: lunes, 20 de noviembre de 2051
----------

> Task :sign_in_with_apple:signingReport
Variant: debugAndroidTest
Config: debug
Store: /Users/victorgarciaexposito/.android/debug.keystore
Alias: AndroidDebugKey
MD5: 48:CD:95:AB:A5:1E:06:3D:CD:66:D1:05:DC:AF:DB:7C
SHA1: A6:1B:27:3C:06:BE:C8:00:34:EC:50:FC:81:7D:C7:88:4B:B4:1B:E9
SHA-256:
D6:26:47:B5:4A:52:7D:97:D8:80:73:3E:88:70:8A:00:CE:7F:C4:6D:1D:18:69:62:95:3C:13:02:A2:7C:A6:9C
Valid until: lunes, 20 de noviembre de 2051
----------

Deprecated Gradle features were used in this build, making it incompatible
with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation
warnings and determine if they come from your own scripts or plugins.

See
https://docs.gradle.org/7.4/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 6s
7 actionable tasks: 7 executed

Screenshot from Google Cloud OAuth consent

[image: image.png]

any better ideas on how to solve this or any step i could be
misguided/wrong? Thanks again for your time and effort.

**Comment by darshankawar** [comment]
@wontlearn2codewithme 
Please follow-up in below similar issues and check underlying comments / solutions mentioned in them to see if they help in your case:

https://github.com/flutter/flutter/issues/75224
https://github.com/flutter/flutter/issues/33393

Closing this in favor of above.
