### ISSUE TITLE
Recipes should install arm version of Ruby on arm64 Mac bot

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#110561]
In https://github.com/flutter/flutter/pull/109889 I'm seeing the Ruby `ffi` bus error on Mac ARM hosts because the arm64 version of Ruby is not being installed.  I'd like to run tests that need Ruby installed without having to set `arm64_ruby` dependency in the config (https://flutter-review.googlesource.com/c/recipes/+/30040), since it could be run on arm64 or x64 bots, depending on capacity.  

https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8804808600117899185/+/u/run_module_test_ios/test_stdout

```
[module_test_ios] [STDOUT] stdout: [   +1 ms]     /opt/s/w/ir/x/w/gems/ruby/2.6.0/gems/ffi-1.15.5/lib/ffi/library.rb:275: [BUG] Bus Error at 0x0000000101030000
[module_test_ios] [STDOUT] stdout:                ruby 2.6.8p205 (2021-07-07 revision 67951) [universal.arm64e-darwin21]
[module_test_ios] [STDOUT] stdout: 
[module_test_ios] [STDOUT] stdout:                -- Crash Report log information --------------------------------------------
[module_test_ios] [STDOUT] stdout:                   See Crash Report log file under the one of following:
[module_test_ios] [STDOUT] stdout:                     * ~/Library/Logs/DiagnosticReports
[module_test_ios] [STDOUT] stdout:                     * /Library/Logs/DiagnosticReports
[module_test_ios] [STDOUT] stdout:                   for more details.
[module_test_ios] [STDOUT] stdout:                Don't forget to include the above Crash Report log file in bug reports.
[module_test_ios] [STDOUT] stdout: 
[module_test_ios] [STDOUT] stdout:                -- Control frame information -----------------------------------------------
[module_test_ios] [STDOUT] stdout:                c:0049 p:---- s:0307 e:000306 CFUNC  :attach
[module_test_ios] [STDOUT] stdout:                c:0048 p:0258 s:0301 e:000300 METHOD /opt/s/w/ir/x/w/gems/ruby/2.6.0/gems/ffi-1.15.5/lib/ffi/library.rb:275
[module_test_ios] [STDOUT] stdout:                c:0047 p:0050 s:0281 e:000280 CLASS  /opt/s/w/ir/x/w/gems/ruby/2.6.0/gems/ethon-0.15.0/lib/ethon/libc.rb:17
[module_test_ios] [STDOUT] stdout:                c:0046 p:0007 s:0278 e:000277 CLASS  /opt/s/w/ir/x/w/gems/ruby/2.6.0/gems/ethon-0.15.0/lib/ethon/libc.rb:7
[module_test_ios] [STDOUT] stdout:                c:0045 p:0007 s:0275 e:000274 TOP    /opt/s/w/ir/x/w/gems/ruby/2.6.0/gems/ethon-0.15.0/lib/ethon/libc.rb:2 [FINISH]
```

Instead of requiring the `arm64_ruby` dep, derive it from the fact that Ruby is needed, and the `cpu` is `arm64`.

https://flutter.googlesource.com/recipes/+/refs/heads/main/recipe_modules/flutter_deps/api.py#297
https://flutter.googlesource.com/recipes/+/refs/heads/main/recipe_modules/flutter_deps/api.py#324

cc @keyonghan

**Comment by keyonghan** [comment]
> Instead of requiring the arm64_ruby dep, derive it from the fact that Ruby is needed, and the cpu is arm64.

Does `cpu: arm64` mean an arm bot?

To install arm64 ruby on either x64 or arm64, we need to have a flag letting recipe know whether the ruby is needed. A property defined from target config sounds a good fit.

**Comment by jmagman** [comment]
> Does `cpu: arm64` mean an arm bot?

Yes, but good point, that property won't be set if the config is supposed to run on arm or x64.  Is there any way to tell the `cpu` of the bot without having it be passed into the recipe?

> To install arm64 ruby on either x64 or arm64, we need to have a flag letting recipe know whether the ruby is needed. A property defined from target config sounds a good fit.

It seems like the recipe already knows that Ruby is needed, if `gems` is a dependency.  All the `arm64_ruby` deps checks are happening in `gems()`:
https://flutter.googlesource.com/recipes/+/refs/heads/main/recipe_modules/flutter_deps/api.py#283

However I think the `arm64_ruby` dep should be deprecated, and instead `cpu: arm64` should be checked instead.  This will allow the right version of Ruby to be installed

**Comment by keyonghan** [comment]
I guess we can simply install arm64_ruby for any `arm` testbeds, no matter it's a devicelab one, or a host only one?

Recipes `platform` module supports `platform.arch` which returns `arm` for all arm bots. Is this enough? Or we need to be as accurate as `arm64`?

Another thing we want to validate is: most existing `Mac_arm64_ios` targets are running against regular `ruby`, and we want to make sure they are running okay on the `arm64_ruby` when switched to depend on `cpu`.

**Comment by godofredoc** [comment]
I believe most of the workflows are using the ruby version provided by xcode rather than the system one.

**Comment by jmagman** [comment]
> I guess we can simply install arm64_ruby for any `arm` testbeds, no matter it's a devicelab one, or a host only one?

It would be needed for any builder that requires `gems` dependency, devicelab or host only.

> Recipes `platform` module supports `platform.arch` which returns `arm` for all arm bots. Is this enough? Or we need to be as accurate as `arm64`?

`arm` would work.

> Another thing we want to validate is: most existing `Mac_arm64_ios` targets are running against regular `ruby`, and we want to make sure they are running okay on the `arm64_ruby` when switched to depend on `cpu`.

How is this working then? I would have expected the ffi bus crash? https://ci.chromium.org/p/flutter/builders/prod/Mac_arm64_ios%20build_ios_framework_module_test/1053

**Comment by keyonghan** [comment]
> How is this working then? I would have expected the ffi bus crash? https://ci.chromium.org/p/flutter/builders/prod/Mac_arm64_ios%20build_ios_framework_module_test/1053

That I am not sure..

Validated all existing `Mac_arm64_ios` builders pass for arm64ruby. Recipes change to rely on cpu:
https://flutter-review.googlesource.com/c/recipes/+/33541

**Comment by keyonghan** [comment]
https://flutter-review.googlesource.com/c/recipes/+/33541 landed, and CI is running okay. Closing as complete. Please reopen if anything else if missing.

**Comment by jmagman** [comment]
Thanks @keyonghan, this worked!
