### ISSUE TITLE
in_app_purchase problem with subscription that not supported querySkuDetailsAsync()

### ISSUE THREAD

**Issue by piotrstefani** [flutter/flutter#110580]
I have in_app_purchase in version 3.0.7. I have few subscription setted in google play console some time ago and they are working fine. Now I have put a new subscription in google play console and there is a problem because queryProductDetails method return that there is no sub with specific(new ones) id's(this new one i have in 'notFoundIDs' array). What I have spotteed is that my old subscriptions has adnotation about back compatibility with 'querySkuDetailsAsync()' and this new one havn't it. Does anyone have a same issue?

**Comment by huycozy** [comment]
Hi @piotrstefani, 
Sorry, I don't understand what you mean in the description, could you please describe the issue step-by-step?
Also, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this. And please provide the output of `flutter doctor -v` as well.
Thank you!

**Comment by piotrstefani** [comment]
Hi @huycozy 
I have two subscription in google play console:
First with productId - 'test1'. I have made it a few months ago and it's work fine(when I call `await _inAppPurchase.queryProductDetails({'test1}); `I receiving properly data). This subscription has annotation in google play console about backward compatiblity with `querySkuDetailsAsync()` method.

Second one with productId 'test2'. I have did it a few days ago, it hasn'y any information about this backward compatiblity and it's not showing up in my app.

I don't know why this new subscription isn't return with 

` await _inAppPurchase.queryProductDetails({'test2});`

The only thing different from test1 is this information about querySkuDetailsAsync() in google play console.

`╔════════════════════════════════════════════════════════════════════════════╗
║ A new version of Flutter is available!                                     ║
║                                                                            ║
║ To update to the latest version, run "flutter upgrade".                    ║
╚════════════════════════════════════════════════════════════════════════════╝

[✓] Flutter (Channel stable, 2.10.2, on macOS 12.1 21C52 darwin-arm, locale pl-PL)
    • Flutter version 2.10.2 at /Users/piotrstefani/fvm/versions/2.10.2
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 097d3313d8 (6 months ago), 2022-02-18 19:33:08 -0600
    • Engine revision a83ed0e5e3
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/piotrstefani/Library/Android/sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] Connected device (2 available)
    • SM M127F (mobile) • RF8RB0M2S8R • android-arm64  • Android 11 (API 30)
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 104.0.5112.101

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
`

**Comment by huycozy** [comment]
Hi @piotrstefani 
What is the output of `await _inAppPurchase.queryProductDetails({'test2});`?
Also, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this.
Thank you!

**Comment by piotrstefani** [comment]
@huycozy 
productDetailResponse.productDetails is empty;
productDetailResponse.notFoundIDs return test2;
productDetailResponse.error is empty;

Not sure if this will be enough but...
```

  final InAppPurchase _inAppPurchase = InAppPurchase.instance;
  late StreamSubscription<List<PurchaseDetails>> _subscription;
 List<ProductDetails> _products = [];
  bool _loading = true;
  List<PurchaseDetails> _purchases = <PurchaseDetails>[];

const List<String> _kProductIds = ["test1", "test2"];
@override
  void initState() {
    final Stream<List<PurchaseDetails>> purchaseUpdated = _inAppPurchase.purchaseStream;
    _subscription = purchaseUpdated.listen((List<PurchaseDetails> purchaseDetailsList) {
      _listenToPurchaseUpdated(purchaseDetailsList);
      _purchases = purchaseDetailsList;
    }, onDone: () {
      _subscription.cancel();
    }, onError: (Object error) {
      // handle error here.
    });
    initStoreInfo();
    super.initState();
  }
 Future<void> initStoreInfo() async {
    final bool isAvailable = await _inAppPurchase.isAvailable();
    if (!isAvailable) {
      setState(() {
        _products = <ProductDetails>[];
      });
    }

    if (Platform.isIOS) {
      final InAppPurchaseStoreKitPlatformAddition iosPlatformAddition =
          _inAppPurchase.getPlatformAddition<InAppPurchaseStoreKitPlatformAddition>();
      await iosPlatformAddition.setDelegate(ExamplePaymentQueueDelegate());
    }
    final ProductDetailsResponse productDetailResponse = await _inAppPurchase.queryProductDetails(_kProductIds.toSet());
    if (productDetailResponse.productDetails.isNotEmpty) {
      setState(() {
        _products = productDetailResponse.productDetails;
        for (int i = 0; i < _kProductIds.length; i++) {
          if (_verifyPurchases(_kProductIds[i])) {
            setState(() {
              _selectedIndex = i;
            });
          }
        }
        _loading = false;
      });
      return;
    }
  }
```

**Comment by huycozy** [comment]
@piotrstefani 
>(when I call await _inAppPurchase.queryProductDetails({'test1}); I receiving properly data).

>productDetailResponse.productDetails is empty;
productDetailResponse.notFoundIDs return test2;
productDetailResponse.error is empty;

In this case, `productDetailResponse.productDetails` should return at least 1 item (test1). Can you re-check on Play Console that there are two products in `In-app products` section? (test1 and test2)

From my side, there are two products and they are returned when debugging:
<details>
<summary>Demo</summary>

<img width="580" alt="Screenshot 2022-08-31 at 23 25 38" src="https://user-images.githubusercontent.com/104349824/187730006-8857d40e-6fb8-4f77-aaa5-a438c7dc9f9f.png">
</details>
