### ISSUE TITLE
Xcode installation on bots do not include default simulator runtime in the framework

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#110543]
These logs show `flutter_internal/ios/xcode/mac` and `flutter_internal/ios/xcode/ios` being installed, but not the corresponding `ios_runtime` package, which includes the iOS simulator runtime that matches that Xcode version.
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8804806691052681793/+/u/install_xcode/stdout
```
[P12179 18:58:48.592 action_plan.go:163 I] In root:
[P12179 18:58:48.592 action_plan.go:175 I]   to update:
[P12179 18:58:48.592 action_plan.go:177 I]     flutter_internal/ios/xcode/mac (KsuhkEd8wy6ByBw9GeM1dI6T_zY08dWhbS26q4IGtIMC -> cL0iunZRZxSY8Q0bCLGb-deBZ4ZCLI7fun8EgKGsz7UC)
[P12179 18:58:48.592 action_plan.go:177 I]     flutter_internal/ios/xcode/ios (C0CJehG6krz2kPiqhRtnxEvaN6UV4fbcdQHbtiA4VQoC -> qqL6geMoQuE7y0qAWizc1bnPjFtvavQxC6cn5lSt0DMC)
```

This is resulting in test failures as the expected simulator runtime is unavailable https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8804806691052681793/+/u/run_plugin_dependencies_test/test_stdout:
```
[plugin_dependencies_test] [STDOUT] stdout:     xcodebuild: error: The run destination Any iOS Device is not valid for Running the scheme 'Runner'.
[plugin_dependencies_test] [STDOUT] stdout:     	iOS 16.0 is not installed. To use with Xcode, first download and install the platform
```

When I run the same `mac_toolchain` command locally (https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8804806691052681793/+/u/install_xcode/execution_details) on a `depot_tools` [checkout from today](https://chromium-review.googlesource.com/c/chromium/tools/depot_tools/+/3863963) I do see `ios_runtime` being installed:
```
$ mac_toolchain install -kind ios -xcode-version 14a5294e -output-dir test-14a5294e-download/Xcode.app -cipd-package-prefix flutter_internal/ios/xcode '-with-runtime=True'
[P20460 15:02:04.592 action_plan.go:163 I] In root:
[P20460 15:02:04.593 action_plan.go:169 I]   to install:
[P20460 15:02:04.593 action_plan.go:171 I]     flutter_internal/ios/xcode/mac:cL0iunZRZxSY8Q0bCLGb-deBZ4ZCLI7fun8EgKGsz7UC
[P20460 15:02:04.593 action_plan.go:171 I]     flutter_internal/ios/xcode/ios:qqL6geMoQuE7y0qAWizc1bnPjFtvavQxC6cn5lSt0DMC
[P20460 15:02:04.593 client.go:1890 I] Dry run, not actually doing anything.
[P20512 15:02:05.251 action_plan.go:163 I] In root:
[P20512 15:02:05.251 action_plan.go:169 I]   to install:
[P20512 15:02:05.251 action_plan.go:171 I]     flutter_internal/ios/xcode/mac:cL0iunZRZxSY8Q0bCLGb-deBZ4ZCLI7fun8EgKGsz7UC
[P20512 15:02:05.251 action_plan.go:171 I]     flutter_internal/ios/xcode/ios:qqL6geMoQuE7y0qAWizc1bnPjFtvavQxC6cn5lSt0DMC
[P20512 15:02:05.251 instancecache.go:189 I] Using temporary instance cache at /Users/m/xcode-cipd/test-14a5294e-download/Xcode.app/.cipd/tmp/dl_2555098529
 • [fetch 1/2] Fetched flutter_internal/ios/xcode/mac:cL0iunZRZxSY8Q0bCLGb-deBZ4ZCLI7fun8EgKGsz7UC in 81.7s
 • [fetch 2/2] Fetched flutter_internal/ios/xcode/ios:qqL6geMoQuE7y0qAWizc1bnPjFtvavQxC6cn5lSt0DMC in 0.9s
 • [unzip 1/2] Deployed flutter_internal/ios/xcode/mac:cL0iunZRZxSY8Q0bCLGb-deBZ4ZCLI7fun8EgKGsz7UC in 37.2s
 • [unzip 2/2] Deployed flutter_internal/ios/xcode/ios:qqL6geMoQuE7y0qAWizc1bnPjFtvavQxC6cn5lSt0DMC in 2.3s
[P20512 15:04:07.680 client.go:2127 I] All changes applied.
Packages:
  flutter_internal/ios/xcode/ios_runtime:MdZtRSDgehNcVVlroSXWVAaoq6ch3D6bv_r0s_NDgcMC
[P21752 15:04:10.694 action_plan.go:163 I] In root:
[P21752 15:04:10.694 action_plan.go:169 I]   to install:
[P21752 15:04:10.694 action_plan.go:171 I]     flutter_internal/ios/xcode/ios_runtime:MdZtRSDgehNcVVlroSXWVAaoq6ch3D6bv_r0s_NDgcMC
[P21752 15:04:10.694 client.go:1890 I] Dry run, not actually doing anything.
[P21767 15:04:11.177 action_plan.go:163 I] In root:
[P21767 15:04:11.177 action_plan.go:169 I]   to install:
[P21767 15:04:11.177 action_plan.go:171 I]     flutter_internal/ios/xcode/ios_runtime:MdZtRSDgehNcVVlroSXWVAaoq6ch3D6bv_r0s_NDgcMC
[P21767 15:04:11.177 instancecache.go:189 I] Using temporary instance cache at /Users/m/xcode-cipd/test-14a5294e-download/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/.cipd/tmp/dl_1203370802
 • [fetch] Fetched flutter_internal/ios/xcode/ios_runtime:MdZtRSDgehNcVVlroSXWVAaoq6ch3D6bv_r0s_NDgcMC in 141.4s
...
```
Blocking https://github.com/flutter/flutter/pull/110302

**Comment by jmagman** [comment]
Is `/opt/s/w/ir/cache/osx_sdk/mac_toolchain` out of date?

**Comment by jmagman** [comment]
@godofredoc any idea what's going on here?

**Comment by godofredoc** [comment]
If runtimes is set the default runtime is being deleted because there is no way to know if the default runtime is the same one we are trying to install. https://cs.opensource.google/flutter/recipes/+/main:recipe_modules/osx_sdk/api.py;l=198

**Comment by jmagman** [comment]
> If runtimes is set the default runtime is being deleted because there is no way to know if the default runtime is the same one we are trying to install. https://cs.opensource.google/flutter/recipes/+/main:recipe_modules/osx_sdk/api.py;l=198

`runtime_versions` wasn't set, I just updated that PR to try it as a workaround.

This is the original commit: https://github.com/flutter/flutter/pull/110302/commits/083065e46a159624cb30ca4ba4364ad17c5004c7

**Comment by jmagman** [comment]
> `runtime_versions` wasn't set, I just updated that PR to try it as a workaround.

Here's the swarming task for the linked `install_xcode` command, you can see that property isn't set: https://chromium-swarm.appspot.com/task?id=5cf0af7a4a08c310&o=true&w=true

**Comment by jmagman** [comment]
You can see the same command working as expected in the engine (again, no `runtime_versions` set):

https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8804449615568574945/+/u/install_xcode/execution_details
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8804449615568574945/+/u/install_xcode/stdout

```
Packages:
  flutter_internal/ios/xcode/ios_runtime:MdZtRSDgehNcVVlroSXWVAaoq6ch3D6bv_r0s_NDgcMC
[P32450 17:39:42.235 action_plan.go:163 I] In root:
[P32450 17:39:42.235 action_plan.go:175 I]   to update:
[P32450 17:39:42.235 action_plan.go:177 I]     flutter_internal/ios/xcode/ios_runtime (xbExNWHTJfpNf8vDNXhmLNx9sjfFvAl4ed74gTrXl3cC -> MdZtRSDgehNcVVlroSXWVAaoq6ch3D6bv_r0s_NDgcMC)
[P32450 17:39:42.235 client.go:1890 I] Dry run, not actually doing anything.
[P32451 17:39:42.450 action_plan.go:163 I] In root:
[P32451 17:39:42.450 action_plan.go:175 I]   to update:
[P32451 17:39:42.450 action_plan.go:177 I]     flutter_internal/ios/xcode/ios_runtime (xbExNWHTJfpNf8vDNXhmLNx9sjfFvAl4ed74gTrXl3cC -> MdZtRSDgehNcVVlroSXWVAaoq6ch3D6bv_r0s_NDgcMC)
```

**Comment by jmagman** [comment]
Adding the default `runtime_versions` version worked, but shouldn't be necessary, and wasn't necessary on the engine run.
```
      runtime_versions: >-
        [
          "ios-16-0_14a5294e"
        ]
```

**Comment by godofredoc** [comment]
This is probably related to caches, once we use a build with runtime_versions in a given cache namespace we need to use it for all builders otherwise the local caches default runtime version will not be deterministic.

**Comment by jmagman** [comment]
> once we use a build with runtime_versions in a given cache namespace we need to use it for all builders

Where did that property come from though, `runtime_versions` was never set in the framework (until I updated my PR after I filed this issue to see if I could work around it).

**Comment by jmagman** [comment]
Maybe it's seeing the cached default runtime from the order Xcode version?

**Comment by jmagman** [comment]
@godofredoc do you think specifying the runtime is an acceptable workaround for now?  Will that cause collisions for the default caches that don't specify it?
https://github.com/flutter/flutter/pull/110302/files#diff-9e73abde9fff445f31e5928e80d2d3f88847e02fd8f76d46f66f147fdc82786dR2364

@CaseyHillers may also have an opinion.

**Comment by CaseyHillers** [comment]
How does the framework get runtimes? I see the engine specifies it explicitly in the ci.yaml, but I can't find any references in flutter/flutter's ci.yaml.

After sampling a few Mac Flutter tasks, I don't see any named caches for the runtimes (the engine correctly shows them)

**Comment by jmagman** [comment]
> How does the framework get runtimes?

It should be getting the default one associated with the Xcode version, and `mac_toolchain` handles that, like this:

https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8804449615568574945/+/u/install_xcode/execution_details
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8804449615568574945/+/u/install_xcode/stdout

```
Packages:
  flutter_internal/ios/xcode/ios_runtime:MdZtRSDgehNcVVlroSXWVAaoq6ch3D6bv_r0s_NDgcMC
[P32450 17:39:42.235 action_plan.go:163 I] In root:
[P32450 17:39:42.235 action_plan.go:175 I]   to update:
[P32450 17:39:42.235 action_plan.go:177 I]     flutter_internal/ios/xcode/ios_runtime (xbExNWHTJfpNf8vDNXhmLNx9sjfFvAl4ed74gTrXl3cC -> MdZtRSDgehNcVVlroSXWVAaoq6ch3D6bv_r0s_NDgcMC)
[P32450 17:39:42.235 client.go:1890 I] Dry run, not actually doing anything.
[P32451 17:39:42.450 action_plan.go:163 I] In root:
[P32451 17:39:42.450 action_plan.go:175 I]   to update:
[P32451 17:39:42.450 action_plan.go:177 I]     flutter_internal/ios/xcode/ios_runtime (xbExNWHTJfpNf8vDNXhmLNx9sjfFvAl4ed74gTrXl3cC -> MdZtRSDgehNcVVlroSXWVAaoq6ch3D6bv_r0s_NDgcMC)
```

 I'm not sure why it's working in the engine but not the framework.  I was thinking maybe `mac_toolchain` is out of date there and isn't downloading the default runtime?

**Comment by jmagman** [comment]
This is adding ~8 minutes to many framework tests, even when cached:
https://ci.chromium.org/p/flutter/builders/prod/Mac%20build_tests_1_4/6504

<img width="408" alt="Screen Shot 2022-08-31 at 10 01 21 AM" src="https://user-images.githubusercontent.com/682784/187737251-0ad76128-896a-4142-b9a3-ec0110ff0c6b.png">

**Comment by keyonghan** [comment]
> Is `/opt/s/w/ir/cache/osx_sdk/mac_toolchain` out of date?

We have been using latest version of mac_toolchain: https://cs.opensource.google/flutter/recipes/+/main:recipe_modules/osx_sdk/api.py;l=48

> If runtimes is set the default runtime is being deleted because there is no way to know if the default runtime is the same one we are trying to install. https://cs.opensource.google/flutter/recipes/+/main:recipe_modules/osx_sdk/api.py;l=198

We are removing all existing `runtime` (`default` one+`customized` ones) and re-install `customized` ones: https://cs.opensource.google/flutter/recipes/+/main:recipe_modules/osx_sdk/api.py;l=199, which seems not necessary. This only adds extra time to the whole build. I am wondering if we can check existence of customized `runtime`, and skip the remove+re-install if yes.

**Comment by keyonghan** [comment]
There shouldn't be any difference between engine and framework tasks, as they share the same version, same mac_toolchain, etc. Ran LEDs on all existing tasks (that have customized runtime `ios-16-0_14a5294e`) by removing this runtime dependency, all passed and installed the default runtime correctly:
- [Mac build_tests_1_4](https://ci.chromium.org/raw/build/logs.chromium.org/flutter/led/keyonghan_google.com/0e4727893bad881cf1d2ba98fa734469ff0475e8e7c007bd2c6bdbdeb4af4cd1/+/build.proto?server=chromium-swarm.appspot.com)
- [Mac build_tests_2_4](https://ci.chromium.org/raw/build/logs.chromium.org/flutter/led/keyonghan_google.com/c290ad5dfa30ed3dbe2ab7b7a3e3bad3593688c8d750b8400bd357ce27b0bcf4/+/build.proto?server=chromium-swarm.appspot.com)
- [Mac build_tests_3_4](https://ci.chromium.org/raw/build/logs.chromium.org/flutter/led/keyonghan_google.com/fc4e617cfef18051c5557876b8efbefc3ace21cd893b5b121713d62208a070a6/+/build.proto?server=chromium-swarm.appspot.com)
- [Mac build_tests_4_4](https://ci.chromium.org/raw/build/logs.chromium.org/flutter/led/keyonghan_google.com/45f4800489ebbdbc367623c290d1ef8ff190904889e08cdcbee83045db8139c0/+/build.proto?server=chromium-swarm.appspot.com)
- [Mac module_test_ios](https://ci.chromium.org/raw/build/logs.chromium.org/flutter/led/keyonghan_google.com/e1f9acdf8d3ed7b17eae1026f4a4ffa5a06779a5aa09d2cd500cadf40096a5f1/+/build.proto?server=chromium-swarm.appspot.com)
- [Mac plugin_lint_mac](https://ci.chromium.org/raw/build/logs.chromium.org/flutter/led/keyonghan_google.com/cf1613271b2c1af09d73f80941caf70f112e5570611ebfcfe53d8e4f51275598/+/build.proto?server=chromium-swarm.appspot.com)
- [Mac plugin_test_ios](https://ci.chromium.org/raw/build/logs.chromium.org/flutter/led/keyonghan_google.com/1a40d1c170dbbfb81d06dfb02b0af1f3f20358312f6ab3590cbe5c42c81465b2/+/build.proto?server=chromium-swarm.appspot.com)
- [Mac tool_host_cross_arch_tests](https://ci.chromium.org/raw/build/logs.chromium.org/flutter/led/keyonghan_google.com/b563bb657175d6ac9d8b09e7fe3ab195ffb58ac7343da7667b7b34fb55c6ee78/+/build.proto?server=chromium-swarm.appspot.com)
- [Mac tool_integration_tests_1_4](https://ci.chromium.org/raw/build/logs.chromium.org/flutter/led/keyonghan_google.com/2e0051dad5480f78bc1ac67193d6086ac65b633dbffbe8f5c5a5eb8d839f6cb1/+/build.proto?server=chromium-swarm.appspot.com)
- [Mac tool_integration_tests_2_4](https://ci.chromium.org/raw/build/logs.chromium.org/flutter/led/keyonghan_google.com/9079dcf3eda03f54465f35c608cf5ae1f1d8fcd731ec55af98bc165299df03b9/+/build.proto?server=chromium-swarm.appspot.com)
- [Mac tool_integration_tests_3_4](https://ci.chromium.org/raw/build/logs.chromium.org/flutter/led/keyonghan_google.com/16cf72d941dcb2323fe9aa4653df69353a5c551006356b183149260dfeeb76b8/+/build.proto?server=chromium-swarm.appspot.com)
- [Mac tool_integration_tests_4_4](https://ci.chromium.org/raw/build/logs.chromium.org/flutter/led/keyonghan_google.com/fd35aed1395fe46b75350fd5a1025580b531c4bc841f77bb5a9e5e84987d9586/+/build.proto?server=chromium-swarm.appspot.com)

Also ran 10 times for a specific builder: Mac plugin_dependencies_test, all passed as well.

I would assume this bug (not running default runtime) is a temporary issue with `mac_toolchain`. If there is some issue when installing the runtime, we should followup with toolchain team to investigate why the runtime is missing.

Opening https://github.com/flutter/flutter/pull/111492 to remove those runtime, as they have increased the total validation a lot (even doubled for some targets)

**Comment by jmagman** [comment]
Hm, weird it's working now.  Thanks for checking again @keyonghan!

**Comment by jmagman** [comment]
https://github.com/flutter/flutter/pull/111492 merged.  Closing.
