### ISSUE TITLE
itemBuilder of PageView.builder does not return "index" properly.

### ISSUE THREAD

**Issue by tuyen123khac** [flutter/flutter#110566]
My PageView is not specified "itemCount" so it could be swipe infinitely.
Sometimes, when swiping, the `index` which is returned from `itemBuilder` is wrong.

`
PageView.builder(
             itemBuilder: (context, index) {
                Log.d('index $index');
}
)
`
For example, My current index is 23. I swipe back and it should be 22, but sometimes it's 21 .
Do we any work around solution for this before fixing?

**Comment by danagbemava-nc** [comment]
Hi @tuyen123khac,

Can you please provide your `flutter doctor -v` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?

Thank you

**Comment by tuyen123khac** [comment]
Hi @danagbemava-nc ,
Here is my flutter doctor log. The minimal complete reproducible code sample is the one I provided on description. It's really basic and occur intermittently.


[✓] Flutter (Channel stable, 3.0.5, on macOS 11.6.1 20G224 darwin-arm, locale en)
    • Flutter version 3.0.5 at /Users/vktuyen/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (7 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/vktuyen/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/vktuyen/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Users/bin/google-chrome)
    ! /Users/bin/google-chrome is not executable.

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] IntelliJ IDEA Community Edition (version 2021.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.70.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.46.0

[✓] Connected device (2 available)
    • Nokia 7 2 (mobile) • D0AA002307J82812686 • android-arm64 • Android 11 (API 30)
    • macOS (desktop)    • macos               • darwin-arm64  • macOS 11.6.1 20G224 darwin-arm

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

**Comment by danagbemava-nc** [comment]
Hi @tuyen123khac,

A newer version of flutter was recently released. Can you upgrade to the latest version of flutter to see if you still experience this issue? 

If you do, please provide the updated output of `flutter doctor -v`. 

Thank you
