### ISSUE TITLE
Allow to set the Dart VM --timeline_streams flag from Flutter tools

### ISSUE THREAD

**Issue by B3rn475** [flutter/flutter#11053]
When running `flutter run --profile` right now it is not possible to preset the enabled Streams in the Timeline.
Adding a `--timeline_streams` parameter to `flutter run` will reduce time wasted during the Flutter application performance optimization development cycle.

Related: https://github.com/dart-lang/sdk/issues/29275

**Comment by jason-simmons** [comment]
The --trace-startup flag in flutter_tools will pass a "--timeline_streams=Compiler,Dart,Embedder,GC" option to the VM.

**Comment by xster** [comment]
It would be good to have a similar flag but that doesn't stop the app after the first frame and keeps running with the trace streams on while the app ran

**Comment by Hixie** [comment]
We would welcome a patch to do this but it's not clear why this is necessary. We're going to close this bug for now. If anyone wants this feature please don't hesitate to open a new bug explaining the use case in more detail.
