### ISSUE TITLE
Scaffold drag gesture triggers in system gesture area

### ISSUE THREAD

**Issue by kevmo314** [flutter/flutter#110568]
## Steps to Reproduce

Create a Scaffold with a sidebar and enable drag gestures.

See video from user: https://youtu.be/RfcyrFYFCLM?t=214

**Expected results:**

Gestures in the system gesture area shouldn't trigger the side drawer.

**Actual results:**

The code here: https://github.com/flutter/flutter/blob/7ded3d91daf9478126b902b9508f1aeb9fb91e3a/packages/flutter/lib/src/material/drawer.dart#L604-L612

Suggests that the gesture detector extends beneath the system gesture insets area. This doesn't follow the guideline indicated in the documentation: https://api.flutter.dev/flutter/widgets/MediaQueryData/systemGestureInsets.html

"Apps should avoid locating gesture detectors within the system gesture insets area."

**Comment by exaby73** [comment]
Hello @kevmo314. Thank you for filing this issue. Can you please provide the following information?

- A [complete and minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).
- The output of `flutter doctor -v`
