### ISSUE TITLE
Navigator transactions that occur close together will cause one of those transactions to be lost.

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#1105]
Possibly intended behaviour?

**Comment by abarth** [comment]
I think we only do one transaction per frame.  We added this behavior because otherwise you can get yourself into logically inconsistent states (e.g., closing a dialog twice).

/cc @Hixie

**Comment by abarth** [comment]
You can use http://docs.flutter.io/flutter/widgets/Navigator/openTransaction.html to do multiple navigation operations in one transaction.

**Comment by Hixie** [comment]
Can you elaborate on what you're trying to do?

**Comment by apwilson** [comment]
I was doing the openTransation thing to one pop and then one push.  If I do them outside of a single openTransaction callback they both don't happen.  This feels like bad behaviour as if you do a push or pop in one part of your code and then do another in another part of the code w/o a frame occurring  you're now in an unexpected state.  Can't we queue them up or something?

**Comment by apwilson** [comment]
Basically, my workaround is to make sure whenever I do more than one navigator push/pop in a function I needed to create a new function that does that sequence.  This is error prone as I may have forgotten one of the many places I do something similar.  It's also error prone if some other class grabs my navigator and does its own thing that I don't know about.

**Comment by apwilson** [comment]
After talking with @Hixie I'm okay with closing this one.
