### ISSUE TITLE
Webview not loading websites, Frame load interrupted , error code 102

### ISSUE THREAD

**Issue by trojancode** [flutter/flutter#110573]
Webview is not loading some websites. It returns error code 102, Frame load interrupted.

Error Description:-

`Error Domain=WebKitErrorDomain Code=102 "Frame load interrupted" UserInfo={_WKRecoveryAttempterErrorKey=<WKReloadFrameErrorRecoveryAttempter: 0x600003a70340>, NSErrorFailingURLStringKey=https://www.google.com/search?q=facebook.+com&oq=&aqs=chrome.1.46i39i199i362i465j35i39i362l5j46i39i199i362i465j35i39i362l8.-1j0j7&client=ms-android-samsung-ss&sourceid=chrome-mobile&ie=UTF-8&safe=active/, NSErrorFailingURLKey=https://www.google.com/search?q=facebook.+com&oq=&aqs=chrome.1.46i39i199i362i465j35i39i362l5j46i39i199i362i465j35i39i362l8.-1j0j7&client=ms-android-samsung-ss&sourceid=chrome-mobile&ie=UTF-8&safe=active/, NSLocalizedDescription=Frame load interrupted}`

The url i tried to load :- https://google.com/search?q=facebook.+com&oq=&aqs=chrome.1.46i39i199i362i465j35i39i362l5j46i39i199i362i465j35i39i362l8.-1j0j7&client=ms-android-samsung-ss&sourceid=chrome-mobile&ie=UTF-8&safe=active/

**Comment by exaby73** [comment]
Hello @trojancode. Thank you for filing this issue. Can you please provide the following information?

- A [complete and minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).
- The output of `flutter doctor -v`
- The output of `flutter run-v`
