### ISSUE TITLE
Why doesn't Google Playstore accept obfuscated Flutter apps?

### ISSUE THREAD

**Issue by elieobeid7** [flutter/flutter#110579]
If I [obfuscate][1] the dart code by running this command

    flutter build appbundle --obfuscate --split-debug-info=build/app/outputs/symbols

I get [this error][2]

    You cannot remove all production APKs and Android App Bundles

But if I run 

    flutter build appbundle --split-debug-info=build/app/outputs/symbols

I get no errors and I can publish the app, why?

No one was able to answer [the question ](https://stackoverflow.com/questions/73520201/why-doesnt-google-playstore-accept-obfuscated-flutter-apps )on StackOverflow,  so I opened a support ticket request to google play console support and they said that their support team isn’t trained to provide technical support for app development questions.

  [1]: https://docs.flutter.dev/deployment/obfuscate
  [2]: https://stackoverflow.com/questions/63694475/you-cannot-remove-all-production-apks-and-android-app-bundles

**Comment by exaby73** [comment]
Hello @elieobeid7. Thank you for filing this issue. When you uploaded the app, did you upload an APK or an app bundle? Also can you provide your output to `flutter doctor -v`?

**Comment by elieobeid7** [comment]
@exaby73 I always use appbundle. I never use apk


The output of `flutter doctor -v`


```
[✓] Flutter (Channel stable, 3.0.5, on Microsoft Windows [Version 10.0.22000.856], locale en-US)
    • Flutter version 3.0.5 at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (7 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at C:\Users\elieo\AppData\Local\Android\sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop for Windows (Visual Studio Community 2022 17.2.6)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.2.32630.192
    • Windows 10 SDK version 10.0.22000.0
    ✗ Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop
      development with C++" workload, and include these components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK

[✓] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[✓] VS Code (version 1.70.2)
    • VS Code at C:\Users\elieo\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.46.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22000.856]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 104.0.5112.102
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 104.0.1293.70

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

**Comment by exaby73** [comment]
Could you provide the following information?

- Is this issue reproducible with the default counter application?
- Can you provide some detailed reproduction steps? Include the following:
  - If you upload a normal app (no obfuscation), and then the obfuscated one, does it reproduce vs if you upload a obfuscated build the first time, does it reproduce?
  - Are you submitting to the production track or some other track like internal testing? If you are submitting to the production track, does this error occur when you submit to internal testing for example

**Comment by elieobeid7** [comment]
@exaby73 

1. This issue reproducible with the default counter application

2. The issue happened I uploaded a normal app and then obfuscated the next version. I can't obfuscate the first build because I only have one application on playstore, which would require me to create another app and submit it for approval. So the first few versions were not obfuscated.

3. I'm submitting it to the production track, haven't tested it with the internal testing.

**Comment by huycozy** [comment]
Hi @elieobeid7
- Are there any error messages else? If yes, please provide full details. Also, can you capture the error screen and share it here?
- I think this issue is not unique to Flutter, it used to happen with Android native, see: https://stackoverflow.com/questions/51431495/in-google-play-it-says-you-need-to-upload-an-apk-or-android-app-bundle-for-thi, and try workaround in [comment](https://stackoverflow.com/a/51437570/5921933)

**Comment by elieobeid7** [comment]
@huycozy 

1- I'll provide a full capture and screenshot tonight

2- this is simar to the comment left on my question on StackOverflow. As I said I  discarded the release multiple times and tried re-uploading the app, but the issue wasn't fixed. The issue was only fixed when I created an app without obfuscating.

Also, in the question you linked to, the user isn't even trying to obfuscate the app.  He just did something wrong and couldn't;t upload his app.

But I did try to discard the release multiple times and create a new release, also I tried increasing the version number.

**Comment by elieobeid7** [comment]
Also I don't understand why I'm being asked for all this info and workarounds, This is hands down the easiest issue on this entire issue tracker to reproduce

1. Run `flutter build appbundle --obfuscate --split-debug-info=build/app/outputs/symbols` 
2. Upload it to playstore
3. If it gets uploaded close this issue
4. If it doesn't;t get uploaded, that's all you need to know


There are no weird edge cases, no debugging, nothing, this is hands down the most straightforward, easy-to-reproduce issue on the flutter GitHub issue tracker.
