### ISSUE TITLE
[M3] [FilledButton] Issue with text style color

### ISSUE THREAD

**Issue by YazeedAlKhalaf** [flutter/flutter#110542]
When I give the theme a primary color, the FilledButton widget does not use the onPrimary color I provide for the FilledButton text TextStyle.

Here is a picture of the issue:
![Screenshot 2022-08-30 005252](https://user-images.githubusercontent.com/41989385/187305656-19c596b1-6f08-4809-871b-f8dcc115f0db.png)

As you can see, the text color is not what the onPrimary color I specified is. 
A photo showing my theme color scheme code:
![Screenshot 2022-08-30 005423](https://user-images.githubusercontent.com/41989385/187305840-79dc2fb0-e884-4183-a31e-b99a63c7148e.png)

I expect the text color to be white, now it is black.

This code is running on the latest master at the time of opening the issue:
```
Flutter 3.1.0-0.0.pre.2565 • channel master • https://github.com/flutter/flutter.git
Framework • revision b4c0a125b6 (45 minutes ago) • 2022-08-29 14:13:08 -0700
Engine • revision ed6bb2e2e7
Tools • Dart 2.19.0 (build 2.19.0-147.0.dev) • DevTools 2.16.0
```

**Comment by danagbemava-nc** [comment]
Hi @YazeedAlKhalaf, thanks for reporting this. 

Please provide a complete minimal reproducible code sample so that we can investigate further. 

Thank you

**Comment by YazeedAlKhalaf** [comment]
Closing this issue as there is now issue, it was a mistake on my side.
Thanks!
