### ISSUE TITLE
Conductor is setting git remotes to use https

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#110524]
When running the latest release, I was prompted for my username and password.

Instead, it should rely on ssh as MFA usually has difficulty over the basic auth.

**Comment by christopherfujino** [comment]
Not sure how this happened, unless it was manually overridden? https://github.com/flutter/flutter/blob/master/dev/conductor/core/lib/src/repository.dart#L580

**Comment by CaseyHillers** [comment]
>  Not sure how this happened, unless it was manually overridden? 

The issue is with the mirror remote. The upstream remote is fine

**Comment by christopherfujino** [comment]
Ahh, so is the feature request for the conductor substitute https-style input arguments to ssh?
