### ISSUE TITLE
Add Stepper margin property also to horizontal version

### ISSUE THREAD

**Issue by philipptrenz** [flutter/flutter#110592]
## Use case

With https://github.com/flutter/flutter/pull/86067, an option for setting margin for the stepper contents using the vertical version was introduced. First, it is misleading that margin only affects the vertical variant. On the other hand, the adjustability in the horizontal variant seems to me at least as useful, especially if the step content is vertically scrollable, as in my use case.

## Proposal

Replacing hard coded padding in https://github.com/flutter/flutter/blob/7e12b37111d20dfe49ed0c538aefdd25e75d5319/packages/flutter/lib/src/material/stepper.dart#L811 by wrapping the ListView with a Container, which respects a set `margin` from the Stepper class:

```dart
// ...
Expanded(
  child: Container(
    margin: widget.margin ??
        const EdgeInsets.all(24.0),
    child: ListView(
      physics: widget.physics,
      children: <Widget>[
        AnimatedSize(
          curve: Curves.fastOutSlowIn,
          duration: kThemeAnimationDuration,
          child: Column(crossAxisAlignment: CrossAxisAlignment.stretch, children: stepPanels),
        ),
        _buildVerticalControls(widget.currentStep),
      ],
    ),
  ),
),
// ...
```

**Comment by danagbemava-nc** [comment]
I believe this is requesting the same thing as https://github.com/flutter/flutter/issues/108530. 

Please upvote the original issue

Closing from here as duplicate. 

If you disagree, kindly leave a comment below and I will reopen this. 

Thank you
