### ISSUE TITLE
Fonts look ugly in Sample Catalog screenshots

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#11059]
Maybe the screenshots are just very low-res?  My only concern is that individuals would assume Flutter is ugly based on these.

https://flutter.io/catalog/samples/

@HansMuller @sethladd

**Comment by zoechi** [comment]
Do you think there is still something to do.
Looks good to me.

**Comment by zoechi** [comment]
I assume this issue is stale.
