### ISSUE TITLE
CI/CD release flavor build error, but working fine on local machine

### ISSUE THREAD

**Issue by dishank-betaflux** [flutter/flutter#110685]
I am getting a simple yet complex error. The same code is working fine on my local machine.

Let me explain,
- I am using github actions. As we know the release build require key.properties and keystore.jks file. I base64 encrypted those files and those files are working perfectly fine. I tested the base64 text and converted locally  and tested running build releases from those converted files. So not sure why this error coming.

I am not sure what's wrong here. Please save my time if someone from flutter team can take a look and point me to right direction. 

Where to find flutter community for chatting purpose?

<img width="1024" alt="Screenshot 2022-08-31 at 8 35 37 PM" src="https://user-images.githubusercontent.com/100115206/187733103-ce4d0b69-6944-492a-b5f6-d147647cf50d.png">

**Comment by darshankawar** [comment]
@dishank-betaflux 
Check [this](https://stackoverflow.com/a/71301322) SO solution and see if it helps in your case. If not, I suggest you to reach out to your CI/CD provider for further resolution, as, per your comment, it is working properly locally.

Closing from here.
