### ISSUE TITLE
`flutter-devicelab-mac-10` is quarantined "Not enough free disk space on /. 202667.4mib < 204800.0mib"

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#110641]
`flutter-devicelab-mac-10` is in the staging pool.

```
Quarantined | Not enough free disk space on /. 202667.4mib < 204800.0mib
```
https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-10

**Comment by yusuf-goog** [comment]
emptied trash, which recovered necessary free space.
