### ISSUE TITLE
DateTime.now().millisecondsSinceEpoch return an incorrent timestamp, It is not the same as android/iOS gets

### ISSUE THREAD

**Issue by lhzmrl** [flutter/flutter#110659]
It happens by accident in a production environment.
the code just like this:
```dart
int timestamp = DateTime.now().millisecondsSinceEpoch;
```
Our backend checks the timestamp in the request, which should not be too far from the actual time,but sometimes the timestamp is a few minutes earlier, sometimes it's a few minutes later.But there is no problem with the timestamp obtained by Android/iOS.

Our environment like this:
```yaml
environment:
  sdk: ">=2.10.0 <3.0.0"
  flutter: ">=2.2.0"
```
Is there any reported issues like this?Can you give me some suggestions?

**Comment by darshankawar** [comment]
@lhzmrl 
I think this need to be reported in dedicated repo, I see that you have already raised there, so please follow-up in it for further updates. If you get directed here, write in comments and I'll reopen it.

Closing for now.
