### ISSUE TITLE
[CP] [Android] Synchronize incorrect metaState using post-synchronization

### ISSUE THREAD

**Issue by dkwingsmt** [flutter/flutter#110692]
### issue_link

https://github.com/flutter/flutter/issues/110640

### Commit Hash

a56d98ea78719e8ec54af8f3325740aadb953f1c

### Target

stable

### pr_link

https://github.com/flutter/engine/pull/35842

### Impacted Users

Likely all Android users

### Impact Description

Occasionally when the user presses action keys (such as "Select All") the app crashes.

### Workaround

Not that I'm aware of.

### Risk

high

### Test Coverage

yes

### Validation Steps

When executing the reproduction steps described in https://github.com/flutter/flutter/issues/110640, the app doesn't crash.

**Comment by bleroux** [comment]
Unfortunately, this cherry pick does not fix the related issue https://github.com/flutter/flutter/issues/110640
It seems to be a similar edge case related to how the GBoard keyboard emits a key event for ShiftLeft key but it is not exactly the same edge case (as the one fixed in https://github.com/flutter/engine/pull/34827).

**Comment by AlexV525** [comment]
#110640 actually contains two exceptions with the assertion error, they're quite similar at the first look, but they're both valid fixes.

**Comment by itsjustkevin** [comment]
@dkwingsmt could you take a look at this?

**Comment by bleroux** [comment]
I agree with @AlexV525, the fixed I made for https://github.com/flutter/flutter/issues/110640 is based on this fix. 
So to properly fixed https://github.com/flutter/flutter/issues/110640 both fixes should be cherry picked (this CP and https://github.com/flutter/flutter/issues/111537)

**Comment by dkwingsmt** [comment]
Yes, I agree that both PR should be CP'd.
