### ISSUE TITLE
[Flutter 3.3] ListView in TabBars with trackpads / ScrollConfiguration (macOS)

### ISSUE THREAD

**Issue by Sesa1988** [flutter/flutter#110675]
## Steps to Reproduce

1. Create TabBar and Lists as content
2. Try to scroll via Trackpad

**Expected results:** Scrolling does not work, only between tabs.

**Actual results:** Scrolling also works on its child lists.

https://github.com/Sesa1988/trackpad-scrolling-issue-3-3-0/tree/main/trackpad_issue

https://user-images.githubusercontent.com/26410357/187715440-f247f9d4-4120-4ca6-b01e-ae5e33e9c19d.mov

**Fix**

if you used **ScrollConfiguration** Widget before you have to add **PointerDeviceKind.trackpad** in order to achive a similar result. Is this the expected behaviour? Seems weird to set dragDevices.trackpad in order to scroll a list?

https://user-images.githubusercontent.com/26410357/187716262-72cfc262-3206-4481-aedf-6cb9f843bf13.mov

**Comment by Sesa1988** [comment]
I assume thats the expected behaviour and the previous implementation was not complete, can probably be closed.

**Comment by exaby73** [comment]
Hello @Sesa1988. Thank you for filing this issue. Can you please provide the following information?

- The output of `flutter doctor -v`

**Comment by Sesa1988** [comment]
Hi @exaby73 

[✓] Flutter (Channel stable, 3.3.0, on macOS 12.5.1 21G83 darwin-x64, locale en-DE)
    • Flutter version 3.3.0 on channel stable at /Users/user/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffccd96b62 (3 days ago), 2022-08-29 17:28:57 -0700
    • Engine revision 5e9e0e0aa8
    • Dart version 2.18.0
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc3)
    • Android SDK at /Users/user/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0-rc3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13E500a
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.70.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.46.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.5.1 21G83 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 105.0.5195.52

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Comment by exaby73** [comment]
Hello @Sesa1988. By removing `ScrollConfiguration`, I can scroll as expected. By adding `ScrollConfiguration` and adding `DragDevices.trackpad` also works.

As for you question whether this is expected, I believe it is. From the documentation for [`dragDevices`](https://api.flutter.dev/flutter/widgets/ScrollBehavior/dragDevices.html):

> The device kinds that the scrollable will accept drag gestures from.

So, yes you would have to specify `DragDevices.trackpad` for Flutter to recognize the trackpad for scrolling. Since this is working as expected, I am closing this issue. If you disagree, please comment and I can reopen it. Thank you.
