### ISSUE TITLE
Dart -> Engine roll failing on analyzer breaking changes

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#110670]
Starting in https://github.com/flutter/engine/pull/35827

For example the build https://ci.chromium.org/ui/p/flutter/builders/try/Mac%20Host%20Engine/42313/overview

```
lib/apicheck.dart:39:54: Error: The getter 'name' isn't defined for the class 'ClassDeclaration'.
 - 'ClassDeclaration' is from 'package:analyzer/dart/ast/ast.dart' ('../../../third_party/dart/pkg/analyzer/lib/dart/ast/ast.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'name'.
    if (unitMember is ClassDeclaration && unitMember.name.name == className) { // ignore: deprecated_member_use
                                                     ^^^^
lib/apicheck.dart:43:44: Error: The getter 'name' isn't defined for the class 'VariableDeclaration'.
 - 'VariableDeclaration' is from 'package:analyzer/dart/ast/ast.dart' ('../../../third_party/dart/pkg/analyzer/lib/dart/ast/ast.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'name'.
            final String fieldName = field.name.name; // ignore: deprecated_member_use
                                           ^^^^


!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!


Failed Command:

/opt/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/bin/dart --disable-dart-dev /opt/s/w/ir/cache/builder/src/flutter/tools/api_check/test/apicheck_test.dart /opt/s/w/ir/cache/builder/src/flutter
```

Looks like it is maybe: https://dart.googlesource.com/sdk.git/+/d8df88cbe41457af0c5de4875ba428a72d66c78f

cc @a-siva @scheglov @bwilkerson

**Comment by bwilkerson** [comment]
Yes, I believe that that's the CL that caused the breakage.

**Comment by scheglov** [comment]
FWIW, I ran presubmit in google3, and it was green. If this code is not in google3, I have no way to know that there are any code in the wild that has to be changed.

Do you need my help to update this code, or do you know what to do?

**Comment by scheglov** [comment]
Ah, you have a fix, good.
Why did not ignore deprecations?

**Comment by zanderso** [comment]
The manual roll is hitting another analysis issue: https://github.com/flutter/engine/pull/35834. It should be easy to fix, but is it correct?
```
Analyzing testing...

   info - scenario_app/lib/src/platform_echo_mixin.dart:13:8 - Document all public members. - public_member_api_docs

1 issue found.
```

**Comment by zanderso** [comment]
@scheglov Please also keep an eye on this console https://ci.chromium.org/p/dart/g/flutter/console. The 'fa' column is red at the moment.

**Comment by zanderso** [comment]
Dart's 'fa' bot (https://ci.chromium.org/p/dart/g/flutter/console) is still red, so I am leaving this open, and not restarting the roller.

**Comment by bwilkerson** [comment]
I'm not sure what the right path forward here is. The first build that failed appears to be https://ci.chromium.org/p/dart/builders/ci.sandbox/flutter-analyze/17269 (please correct me if I'm wrong; I'm fairly new at looking at these results). The failure message is:
```
Analyzing gallery...

warning - lib/feature_discovery/feature_discovery.dart:246:32 - The receiver can't be null, so the null-aware operator '?.' is unnecessary. Try replacing the operator '?.' with '.'. - invalid_null_aware_operator
```

That appears to be a valid problem, but I'm not sure where it came from.

The CL associated with that build modifies some tests in the analysis server, which can't have impacted the analysis of any code.

Are these bots run on every commit to the gallery code, or only when there's a CL on the Dart SDK side?

**Comment by bwilkerson** [comment]
And I just noticed that the very next build has three additional diagnostics:

```
Analyzing gallery...

warning - lib/feature_discovery/feature_discovery.dart:246:32 - The receiver can't be null, so the null-aware operator '?.' is unnecessary. Try replacing the operator '?.' with '.'. - invalid_null_aware_operator
   info - lib/studies/crane/theme.dart:29:5 - 'errorColor' is deprecated and shouldn't be used. Use colorScheme.error instead. This feature was deprecated after v2.6.0-11.0.pre.. Try replacing the use of the deprecated member with the replacement. - deprecated_member_use
   info - lib/studies/shrine/theme.dart:33:5 - 'errorColor' is deprecated and shouldn't be used. Use colorScheme.error instead. This feature was deprecated after v2.6.0-11.0.pre.. Try replacing the use of the deprecated member with the replacement. - deprecated_member_use
   info - lib/themes/material_demo_theme_data.dart:15:7 - 'backgroundColor' is deprecated and shouldn't be used. Use colorScheme.background instead. This feature was deprecated after v3.3.0-0.5.pre.. Try replacing the use of the deprecated member with the replacement. - deprecated_member_use
```

But that commit was for the CFE, so none of that code is run by `flutter analyze`, so it similarly seems unlikely to be the culprit.

**Comment by zanderso** [comment]
This appears to be resolved. The roller is moving again.
