### ISSUE TITLE
通过url_launcher打开一个刚创建的flutter项目会把原来的程序卡死并且还会报数据库死锁，新项目没做任何变动

### ISSUE THREAD

**Issue by 2022747973** [flutter/flutter#110639]
通过点击打开副屏新项目，点击事件里面没写任何访问sqlite数据库操作，新项目也没有写
String filePath = 'C:/Users/Administrator/Desktop/demo10/demo10.exe';
final Uri uri = Uri.file(filePath);
if (await File(uri.toFilePath()).exists()) {
if (await launchUrl(uri,mode:LaunchMode.externalApplication)) {
//发送数据到副屏
//_socketScreen([]);
}else{
print("启动副屏失败！url:${uri.toString()}");
showToast("启动副屏失败！url:${uri.toString()}");
}
} else {
print("副屏文件文件不存在！");
}
![image](https://user-images.githubusercontent.com/94525695/187573818-cbbc5ad5-c746-4b7a-bc44-555245f1a799.png)
![image](https://user-images.githubusercontent.com/94525695/187573841-e60b6228-5eea-457d-bb10-e2d55cfb52ea.png)

**Comment by huycozy** [comment]
Hi @2022747973 
Please provide the information indicated below:
- A [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
- The output of `flutter doctor -v`
- Reproduction steps, Expected results, Actual results
- `url_launcher` plugin version you are using

**Comment by 2022747973** [comment]
原来那个问题我已经通过使用url_launcher_windows 插件解决了，但是为何无法关闭打开的副屏项目，报错尚未实现
url_launcher: ^6.0.10
url_launcher_windows: ^3.0.1

// Copyright 2013 The Flutter Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// ignore_for_file: public_member_api_docs

import 'dart:async';
import 'package:flutter/material.dart';
import 'package:url_launcher/url_launcher.dart';
import 'package:url_launcher_platform_interface/url_launcher_platform_interface.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'URL Launcher',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'URL Launcher'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);
  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  Future<void>? _launched;


  Future<void> _launchInBrowser(String url) async {
    //if (await UrlLauncherPlatform.instance.canLaunch(url)) {
      await UrlLauncherPlatform.instance.launch(
        "C:/Users/Administrator/Desktop/demo10/demo10.exe",
        useSafariVC: false,
        useWebView: false,
        enableJavaScript: false,
        enableDomStorage: false,
        universalLinksOnly: false,
        headers: <String, String>{},
      );
    // } else {
    //   throw 'Could not launch $url';
    // }
  }


  Future<void> _launchInBrowser1(String url) async {
    UrlLauncherPlatform.instance.closeWebView();
  }

  Widget _launchStatus(BuildContext context, AsyncSnapshot<void> snapshot) {
    if (snapshot.hasError) {
      return Text('Error: ${snapshot.error}');
    } else {
      return const Text('123');
    }
  }

  @override
  Widget build(BuildContext context) {
    const String toLaunch = 'C:/Users/Administrator/Desktop/demo10/demo10.exe';
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: ListView(
        children: <Widget>[
          Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              const Padding(
                padding: EdgeInsets.all(16.0),
                child: Text(toLaunch),
              ),
              ElevatedButton(
                onPressed: () => setState(() {
                  _launched = _launchInBrowser(toLaunch);
                }),
                child: const Text('Launch in browser'),
              ),
              ElevatedButton(
                onPressed: () => setState(() {
                  _launched = _launchInBrowser1(toLaunch);
                }),
                child: const Text('Launch in browser1'),
              ),
              const Padding(padding: EdgeInsets.all(16.0)),
              FutureBuilder<void>(future: _launched, builder: _launchStatus),
            ],
          ),
        ],
      ),
    );
  }
}
![企业微信截图_16619472488048](https://user-images.githubusercontent.com/94525695/187673688-86579ea8-11f8-424d-a875-06ec824060c2.png)
[demo10.zip](https://github.com/flutter/flutter/files/9461313/demo10.zip)

**Comment by 2022747973** [comment]
你好，已经在GitHub上面回复你了，请注意查看




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年8月31日(星期三) 晚上7:05
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [flutter/flutter] 通过url_launcher打开一个刚创建的flutter项目会把原来的程序卡死并且还会报数据库死锁，新项目没做任何变动 (Issue #110639)






***@***.***
请提供下列资料：

A完整和最小可重复的代码示例

的输出结果是：扑动医生-v

再现步骤，预期结果，实际结果

url_launcher您正在使用的插件版本

—
直接回复此邮件，在GitHub上查看，或取消订阅.
***@***.***与&gt;.

**Comment by huycozy** [comment]
@2022747973 
>原来那个问题我已经通过使用url_launcher_windows 插件解决了，但是为何无法关闭打开的副屏项目，报错尚未实现

_"It turns out that I have solved the problem by using the url_launcher_windows plugin, but why can't I close the open sub-screen project, the error has not been implemented"_  - Google translate

It seems you are asking for assistance on personal code rather than reporting a Flutter bug. 
In order to clarify the issue, please provide all the information mentioned at https://github.com/flutter/flutter/issues/110639#issuecomment-1232791402. This will not only help you but also other people having similar issue.
Thank you!
