### ISSUE TITLE
Flutter 3.3.0 Fractional translation bugged my app.

### ISSUE THREAD

**Issue by Far-Se** [flutter/flutter#110648]
## Steps to Reproduce

1. Upgrade flutter to 3.3.0
2. Build for Windows

**Expected results:** 
No pixel snapping
**Actual results:** 
Pixel snapping on mouse movement.

I've managed to fix it by adding a pixel on container (26px), but that makes no sense, I had 25px or lower anywhere in the children. This is a bug that appear after upgrade:

> After determining that this pixel snapping was no longer necessary for performance on newer iPhone models, [we’ve removed this pixel snapping](https://github.com/flutter/flutter/issues/103909) from the Flutter Engine to improve desktop fidelity

There should be a way to enable that from pubspec.yaml
<summary>Video</summary>

Look at top of the app, it's a container with a row with inkwell>icon as children.

https://user-images.githubusercontent.com/20853986/187618205-af66746a-ed1b-4470-9310-95da4b777460.mp4

**Comment by darshankawar** [comment]
@Far-Se 
Thanks for the report. It may not be specific to 3.3.0 upgrade, as I see a similar issue related to fractional translationhttps://github.com/flutter/flutter/issues/107733.  See https://github.com/flutter/flutter/issues/107733#issuecomment-1220406270 You may share your findings in that issue for better tracking.

Closing from here in favor of linked issue. If you disagree, write in comments and I'll reopen it.
