### ISSUE TITLE
Implement Android 13 page transition

### ISSUE THREAD

**Issue by jesusrp98** [flutter/flutter#110664]
## Use case

On Android 13, a new page transition animation has been introduced (like on prior years).

https://user-images.githubusercontent.com/8961959/187672596-7fb82dcd-abde-41b1-a919-cc445fc3e020.mp4

## Proposal

Implement a new page transition builder, that mimick Android 13's new native page transition.

**Comment by lotusgate** [comment]
Isn't this something that should be added to the [Material 3](https://github.com/orgs/flutter/projects/19/views/2) Project?
It feels like an important part for the native android feel.

**Comment by songyan-microprogram** [comment]
This issue appears to be a request to extend the `PageTransitionsBuilder` class to define a default page transition that's similar to the one provided by Android T.
