### ISSUE TITLE
Engine -> Framework roll blocked on skia diffs

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#110684]
https://github.com/flutter/flutter/pull/110609

It looks like they are probably due to the CanvasKit roll https://github.com/flutter/engine/pull/35747

cc @yjbanov

**Comment by yjbanov** [comment]
All except "magnifier position" seems related to anti-aliasing. I'm not sure if the magnifier position diff is an improvement or a regression. Is there an easy way to look up a non-web golden? I'm not sure what it's supposed to look like.
