### ISSUE TITLE
[Impeller] Fidelity pass on ColorFilter blend modes.

### ISSUE THREAD

**Issue by ingmferrer** [flutter/flutter#110672]
## Steps to Reproduce

1. Execute `flutter run` on the code sample

**Expected results:**
Image with opacity

**Actual results:**
Dark image

<details>
<summary>Code sample</summary>

```dart
Container(
  decoration: BoxDecoration(
    image: DecorationImage(
      image: const AssetImage(
        'assets/background/medicinals.png',
      ),
      fit: BoxFit.cover,
      colorFilter: ColorFilter.mode(
        kJewelColor.withOpacity(0.25),
        BlendMode.darken,
      ),
    ),
  ),
),
```

</details>

<details>
  <summary>Logs</summary>

```
No errors at all using --verbose
```

```
Analyzing flutter_app...                                           
No issues found! (ran in 4.1s)
```

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.0, on macOS 12.3.1 21E258 darwin-x64, locale
    en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version
    32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!
```

</details>

<details>
<summary>Screenshot with colorFilter</summary>

![Simulator Screen Shot - iPhone 13 Pro Max - 2022-08-31 at 07 24 50](https://user-images.githubusercontent.com/6753534/187704068-fa771045-6977-43bb-b9a8-cc626202dfdd.png)

</details>

<details>
<summary>Screenshot without colorFilter</summary>

![Simulator Screen Shot - iPhone 13 Pro Max - 2022-08-31 at 07 25 10](https://user-images.githubusercontent.com/6753534/187704123-ef01d3c7-1d96-4abd-a19a-a1f3bc09854d.png)

</details>

Tested on iOS simulator and physical device. Flutter 3.3. Impeller is enabled.

**Comment by jonahwilliams** [comment]
Impeller is still under development, and should only be used if you are willing to use master channel.

**Comment by ingmferrer** [comment]
@jonahwilliams oh yeah I'm aware of that but I'm pretty sure early adopters will find this bug and this thread for reference.

**Comment by jonahwilliams** [comment]
Does this reproduce on master?

**Comment by ingmferrer** [comment]
Yup, it's happening on both stable and master channels.

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 3.1.0-0.0.pre.2592, on macOS 12.3.1 21E258 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!
```

**Comment by jonahwilliams** [comment]
Thanks!

**Comment by cliftonlabrum** [comment]
I turned on Impeller in my Flutter 3.3.3 project to try it out, and this bug was immediately apparent. Most of my SVG icons that I color via code were no longer the right color.

Here's a description of my issue that I mistakenly assumed was a [flutter_svg](https://pub.dev/packages/flutter_svg) bug: https://github.com/dnfield/flutter_svg/issues/781

**Comment by jonahwilliams** [comment]
Here is an example app that can be used for a side-by-side Impeller/Skia comparison of blend mode behavior:

import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  static const String _title = 'Flutter Code Sample';

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: _title,
      home: Scaffold(
        appBar: AppBar(title: const Text(_title)),
        body: const MyStatelessWidget(),
      ),
    );
  }
}

class MyStatelessWidget extends StatelessWidget {
  const MyStatelessWidget({super.key});

  @override
  Widget build(BuildContext context) {
    return SingleChildScrollView(
      child: Column(
        children: <Widget>[
          for (BlendMode blend in BlendMode.values)
            Stack(children: <Widget>[
              ColorFiltered(
                colorFilter: ColorFilter.mode(
                  Colors.red.withAlpha(100),
                  blend,
                ),
                child: Image.network(
                  'https://flutter.github.io/assets-for-api-docs/assets/widgets/owl-2.jpg',
                ),
              ),
              Text(blend.name, style: const TextStyle(fontSize: 20)),
            ],
          ),
        ],
      ),
    );
  }
}


From modulate on, they diverage significantly

**Comment by ColdPaleLight** [comment]
I've looked into this before and I found that advanced blend doesn't handle alpha correctly.

To fix this issue we must modify all advanced blend shaders.
