### ISSUE TITLE
[Material 3] App bar doesn't change color while scrolling when TabBarView is used.

### ISSUE THREAD

**Issue by michalkubizna** [flutter/flutter#110626]
Normally App bar changes its color when scrolling the body of the scaffold unless TabBarView is used, in which case it doesn't do anything.

**Comment by danagbemava-nc** [comment]
Hi @michalkubizna,

Can you please provide your `flutter doctor -v` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?

Thank you
