### ISSUE TITLE
New feature of shader not implemented in 3.3

### ISSUE THREAD

**Issue by eutech-electronics** [flutter/flutter#110776]
I saw FragmentProgram changes and i wanted to give it a try.

I have tried to follow this example: https://github.com/zanderso/fragment_shader_example

but i cant compile because FragmentProgram.fromAsset doesn't exists.
It seems that the changes are not loaded in the release.

Flutter doctor:

[√] Flutter (Channel stable, 3.3.0, on Microsoft Windows [Versione 10.0.22000.918], locale it-IT)
    • Flutter version 3.3.0 on channel stable at C:\Users\deste\Documents\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffccd96b62 (3 days ago), 2022-08-29 17:28:57 -0700
    • Engine revision 5e9e0e0aa8
    • Dart version 2.18.0
    • DevTools version 2.15.0

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc1)
    • Android SDK at C:\Users\deste\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.0-rc1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.3.2)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.3.32819.101
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] VS Code (version 1.70.2)
    • VS Code at C:\Users\deste\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Versione 10.0.22000.918]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 104.0.5112.102
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 104.0.1293.63

[√] HTTP Host Availability
    • All required HTTP hosts are available

**Comment by darshankawar** [comment]
@eutech-electronics 
From the example's documentation, it is written that:

`To run on platforms other than macOS, first run the appropriate flutter create command to generate their platform specific files.`

You seem to be trying to run on Windows, so try the above and see if using it, you see expected behavior or not.

**Comment by eutech-electronics** [comment]
I have done it. But to make it run i had to update flutter to the master branch.

**Comment by darshankawar** [comment]
So does it work now expected ?

**Comment by eutech-electronics** [comment]
yes.

the only thing was i tought it was in the stable release reading this article: https://medium.com/flutter/whats-new-in-flutter-3-3-893c7b9af1ff

**Comment by darshankawar** [comment]
thanks. Closing this as not an issue and resolved per above.

**Comment by Moncader** [comment]
@darshankawar 
This is not yet resolved in my opinion.

The release announcement clearly stated that FragmentProgram.fromAsset is included in 3.3.
However, it is not. It only exists in the master channel.

The medium article that flutter.dev links to [here](https://docs.flutter.dev/development/tools/sdk/release-notes) should be fixed.
