### ISSUE TITLE
Cocoon is not respecting the batch schedule logic

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#110716]
All tasks are expected to follow batch schedule of a size of 6. No multiple `In Progress` (yellow box) tasks are expected for a single target (same column). 

Here is the current dashboard snapshot:
<img width="1227" alt="Screen Shot 2022-08-31 at 2 08 41 PM" src="https://user-images.githubusercontent.com/54558023/187783014-54d5762d-7aa8-473d-bdf3-0cf971ee4537.png">

**Comment by keyonghan** [comment]
Is this related to recent webhook to pub/sub? /cc @CaseyHillers

**Comment by CaseyHillers** [comment]
I have no guesses to why pubsub would cause this. I'm investigating the logs to see if there's anything there.

Interesting, there's both double queued tasks, and tasks not being run. Seems like both edge cases are being violated.

![image](https://user-images.githubusercontent.com/2148558/187787524-c1cc7967-2386-4d33-8027-8a50b03b312a.png)

**Comment by keyonghan** [comment]
The scheduler always schedules new commit task when an earlier failure happens (within the batch size). It fails to check if any In Progress task exists. We should add a logic to check if any running task before scheduling.
