### ISSUE TITLE
Package autoroller bot has a certificate issue

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#110736]
https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20packages_autoroller/1200/overview

The tree is closed on this issue.

**Comment by zanderso** [comment]
From chat, @godofredoc is working on this.

**Comment by godofredoc** [comment]
Setting the linux package roller to bringup=true while the keys are regenerated. https://github.com/flutter/flutter/pull/110739

**Comment by godofredoc** [comment]
Secrets have been regnerated with the new keychains.

**Comment by godofredoc** [comment]
The package autoroller is back to a passing state.
