### ISSUE TITLE
[Impeller] Allow expressing the full text-rendering intent using Display Lists.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#110729]
Flutter is migrating to an internal display list format as a replacement for SkPictures recorded through SkCanvas.  However, Flutter uses SkParagraph to layout and paint text, and SkParagraph paints using SkCanvas.

Flutter’s DisplayList provides an implementation of SkCanvas that can translate calls made by SkParagraph into DisplayList objects.  But some objects used by SkCanvas do not provide the APIs needed to recover the object’s parameters and construct an equivalent DisplayList object.

[go/skparagraph-flutter-wishlist](http://go/skparagraph-flutter-wishlist)

**Comment by chinmaygarde** [comment]
Update from @jason-simmons: @jason-simmons posted a prototype of the new SkParagraph painting interface at https://skia-review.googlesource.com/c/skia/+/579056

He's been waiting for comments from comments from folks on vacation but is going to return to it soon.

Currently the major question is around the use of `SkPaint` in the implementation of the engine `Paint`/`Canvas`/etc. APIs.  Is there a plan to replace this with `DlPaint`?

This is relevant for text painting because text foreground/background styles are defined using `Paint` objects.  If we internally store the `Paint` as an `SkPaint`, then the display list implementation will have no way to extract things like filters that are stored within the `SkPaint`.

**Comment by jason-simmons** [comment]
The new text painting interface has landed.
