### ISSUE TITLE
Performance is improveable by removing redundant null checks on hot paths of RenderObject

### ISSUE THREAD

**Issue by fzyzcjy** [flutter/flutter#110764]
Please see https://github.com/flutter/flutter/pull/110765 for descriptions 

## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @fzyzcjy, should this still be opened? I'm asking because you closed https://github.com/flutter/flutter/pull/110765
