### ISSUE TITLE
Face Id Is not Working in Android with the help of Plugins

### ISSUE THREAD

**Issue by ShanuM123** [flutter/flutter#110747]
We implemented this local auth plugin to use this feature Fingerprint & FaceId but the issue is it takes the first priority a Fingerprint to unlock our developed app in flutter & if we switch off the fingerprint in our device and active a face id (enable in device) then in our developed app, its showed No biometric is enabled, (Only in Android Devices)

**Comment by danagbemava-nc** [comment]
Hi @ShanuM123,

Can you please provide your `flutter doctor -v` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?

Also, what version of `local_auth` are you using? 
What device(s) are you experiencing this issue on?

Thank you

**Comment by stuartmorgan** [comment]
What version of `local_auth_android` are you using (you can check with `flutter pub deps -s compact`)?

We'll also need the code to reproduce this as requested above; it's not clear which API you are calling exactly.
