### ISSUE TITLE
a problem in flutter3

### ISSUE THREAD

**Issue by wtjperi2003** [flutter/flutter#110737]
I created a app with flutter at TV. when I upgrade flutter to 3. I found a rendering problem. just look at the video. everytime I change my focus it will ... my english is poor, i dont know how to describe it . And there is no such problem in flutter2

https://user-images.githubusercontent.com/10322892/187814882-a4d13cfd-c1ad-45b9-a4d9-555f15ff19d5.mp4

**Comment by danagbemava-nc** [comment]
Hi @wtjperi2003, please provide the output of `flutter doctor -v` as well as a complete minimal reproducible code sample. 

Is this issue in release mode only or does it occur in debug mode as well?

Thank you
