### ISSUE TITLE
CupertinoPicker disposes controller

### ISSUE THREAD

**Issue by stevethehu** [flutter/flutter#110731]
https://github.com/flutter/flutter/issues/90123#issuecomment-922942619_

This behavior seems inconsistent with other Widgets that accept a controller, such as material.TextField. It also seems generally unexpected as the CupertinoPicker is essentially claiming ownership of the controller whether or not the caller intends to release ownership.

**Comment by darshankawar** [comment]
@stevethehu 
Can you provide `flutter doctor -v`, a minimal reproducible code sample, error log (if any) along with actual vs expected behavior that describes the issue you reported ?

**Comment by moffatman** [comment]
The issue is misunderstood, it doesn't dispose its controller improperly, but instead it fails to remove subscription to the controller within `_RenderCupertinoPickerSemantics`.
