### ISSUE TITLE
Guide: how to handle flutter version in pubspec.yaml to comply with analyzer (dart:typed_data) [3.3.0]

### ISSUE THREAD

**Issue by Gustl22** [flutter/flutter#110762]
## Steps to Reproduce

If you have a section which imports these two directives:
```
import 'dart:typed_data';
import 'package:flutter/services.dart';
```

with Flutter [3.3.0] you get the the linting error, like wanted via PR #104231: 
```
The import of 'dart:typed_data' is unnecessary because all of the used elements are also provided by the import of 'package:flutter/services.dart'
```

So far so good, but if the user has a lower flutter version installed, the package `dart:typed_data` has to be imported.

I [searched](https://github.com/flutter/plugins/search?q=import+%27dart%3Atyped_data%27%3B) the flutter/plugins repository, and there are many comments which state to [remove the linting exception](https://github.com/flutter/plugins/blob/main/packages/camera/camera_avfoundation/test/type_conversion_test.dart#L5).

So what is the recommended way of handling this? Simply bump the minimum flutter version in `pubspec.yaml` to 3.3.0? But isn't it too early and intrusive to force the developer to do that? 

**Expected results:** 
Don't know what to expect, that's the problem :)

**Actual results:** 
- bump the minimum flutter version and force the developer to upgrade flutter
- ignore the analyzer linting error via `// ignore: unnecessary_import`

<details>
<summary>Code sample</summary>

```dart
import 'dart:typed_data';
import 'package:flutter/services.dart';
```

</details>

<details>
  <summary>Logs</summary>

```
   info - The import of 'dart:typed_data' is unnecessary because all of the used elements are also provided by the import of 'package:flutter/foundation.dart' - lib\src\audio_cache.dart:3:8 -
          unnecessary_import
   info - The import of 'dart:typed_data' is unnecessary because all of the used elements are also provided by the import of 'package:flutter/services.dart' - lib\src\audioplayer.dart:2:8 -
          unnecessary_import

```

```
[√] Flutter (Channel stable, 3.3.0, on Microsoft Windows [Version 10.0.22622.586], locale de-DE)
    • Flutter version 3.3.0 on channel stable at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffccd96b62 (2 days ago), 2022-08-29 17:28:57 -0700
    • Engine revision 5e9e0e0aa8
    • Dart version 2.18.0
    • DevTools version 2.15.0

[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at C:\src\android\Sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • ANDROID_SDK_ROOT = C:\src\android\Sdk
    • Java binary at: C:\Program Files\Java\jdk-15.0.2\bin\java
    • Java version OpenJDK Runtime Environment (build 15.0.2+7-27)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Build Tools 2022 17.3.0)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools
    • Visual Studio Build Tools 2022 version 17.3.32804.467
    • Windows 10 SDK version 10.0.19041.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] IntelliJ IDEA Ultimate Edition (version 2022.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2021.2
    • Flutter plugin version 69.0.5
    • Dart plugin version 222.3345.108

[√] VS Code (version 1.66.2)
    • VS Code at C:\Users\Gustl\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22622.586]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 104.0.5112.102
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 104.0.1293.54

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

</details>

**Comment by stuartmorgan** [comment]
> So what is the recommended way of handling this?

Changing your minimum required Flutter version or `// ignore`ing the warning are both valid options; it's entirely up to you as a package author what versions of Flutter you want to support in your latest version.

> * bump the minimum flutter version and force the developer to upgrade flutter

Unless you have some mechanism by which you are forcing people to use the latest version of your package, nobody is forced to do anything. Assuming you set your minimum Flutter constraint correctly, the only way someone would be "forced" by your package to upgrade Flutter would be if they ignored both `flutter pub upgrade` (which would automatically do the right thing, which is not to try to use an incompatible version) and `flutter pub outdated` (which would tell them the latest version isn't compatible with their project) and tried to force-update to the latest version, and then was unwilling to undo that change when the resolver failed.

> * ignore the analyzer linting error via `// ignore: unnecessary_import`

If you want to support older versions of Flutter, this works fine, as evidenced by the code you found in flutter/plugins.

**Comment by Gustl22** [comment]
Thank you @stuartmorgan, you helped a lot!
