### ISSUE TITLE
Flutter svg issue

### ISSUE THREAD

**Issue by amarildo2001** [flutter/flutter#110728]
I installed flutter svg package and first my svg was shown. Now it shows error as below. Does someone knows how to solve this issue?

Failed to detect image file format using the file header.
File header was [0x3c 0x3f 0x78 0x6d 0x6c 0x20 0x76 0x65 0x72 0x73].
Image source: encoded image bytes

**Comment by darshankawar** [comment]
@amarildo2001 
Since you are using `flutter_svg` package, I suggest you to open this issue in dedicated repo: https://github.com/dnfield/flutter_svg/issues

If you get directed here indicating this is a flutter framework issue, write in comments and I'll reopen it.
