### ISSUE TITLE
Firebase plugins should use latest sub-version

### ISSUE THREAD

**Issue by lukef** [flutter/flutter#11070]
It's highly likely that developers will want to update to the latest point releases (or point point) releases so I'd suggest using the a wildcard for the dependency definition. e.g.:

`compile 'com.google.firebase:firebase-core:11.0.+'`

It should be safe to assume that releases at this level won't break compatibility.

**Comment by mit-mit** [comment]
cc @collinjackson

**Comment by collinjackson** [comment]
@lukef fixed this in flutter/plugins#168

**Comment by kroikie** [comment]
@lukef

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/986. Any further collaboration will be done there.
