### ISSUE TITLE
Proposal: provide a way to customise Transform's alignment property of the `InteractiveViewer`

### ISSUE THREAD

**Issue by pedromassango** [flutter/flutter#110779]
## Use case

Currently, there is no way to center-align a widget inside `InteractiveViewer`.

## Proposal
Provide a way to change the transform's alignment that lies within InteractiveViewer.

https://github.com/flutter/flutter/blob/759d0e1b20c1759f2d6469e9e6d16b545a2e0792/packages/flutter/lib/src/widgets/interactive_viewer.dart#L1091-L1096

**Comment by pedromassango** [comment]
Cc @justinmc

**Comment by darshankawar** [comment]
Thanks for the report @pedromassango and hi :-)
