### ISSUE TITLE
[CupertinoFormSection] We need the ability to change the divider indent on the left, in the case when there is an icon.

### ISSUE THREAD

**Issue by ziqq** [flutter/flutter#110773]
I hope this will be enough.

![image](https://user-images.githubusercontent.com/20646071/187909002-d2797a9c-6cfc-45da-811c-a76439adb192.png)

**Comment by exaby73** [comment]
Hello @ziqq. Thank you for filing this issue. Can you please provide the following information?

- A [complete and minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).
- The output of `flutter doctor -v`

**Comment by ziqq** [comment]
Hello @exaby73.

<details>
  <summary>flutter doctor</summary>

[√] Flutter (Channel stable, 3.0.5, on Microsoft Windows [Version 10.0.19044.1889], locale ru-RU)
    • Flutter version 3.0.5 at P:\.dev\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (7 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\ziqq\AppData\Local\Android\sdk
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 4.1)
    • Android Studio at C:\Users\ziqq\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\201.7199119
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[!] Android Studio
    • Android Studio at C:/Program Files/Git/snap/android-studio/current/android-studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    X android-studio-dir = C:/Program Files/Git/snap/android-studio/current/android-studio       
    X Android Studio not found at C:/Program Files/Git/snap/android-studio/current/android-studio
    • Try updating or re-installing Android Studio.
    • Consider removing your android-studio-dir setting by running:
      flutter config --android-studio-dir=

[√] VS Code (version 1.70.2)
    • VS Code at C:\Users\ziqq\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.46.0

[√] Connected device (4 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)       • windows       • windows-x64    • Microsoft Windows [Version 10.0.19044.1889]   
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 104.0.5112.102
    • Edge (web)              • edge          • web-javascript • Microsoft Edge 104.0.1293.54

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 3 categories.
</details>

<details>
  <summary>Minimal Exaple</summary>

[flutter_example_cupertino_form_section.zip](https://github.com/flutter/flutter/files/9475519/flutter_example_cupertino_form_section.zip)
</details>

**Comment by exaby73** [comment]
Could you explain the exact feature you are suggesting to implement? What's missing in the current implementation?

**Comment by ziqq** [comment]
> Could you explain the exact feature you are suggesting to implement? What's missing in the current implementation?

I want to fix devider position if i use icon. Like ios settings.

**Comment by exaby73** [comment]
Could you give an example of the expected results vs the actual results? Is this missing from Flutter that is mentioned in [Apple's design guidelines](https://developer.apple.com/design/human-interface-guidelines/guidelines/overview)?

**Comment by ziqq** [comment]
All you need is the ability to change this parameter

![image](https://user-images.githubusercontent.com/20646071/188896207-20103859-2395-4c4f-903a-2a0b4988dbe5.png)

**Comment by exaby73** [comment]
@ziqq There is a `margin` property on `CupertinoFormSection`. I am not sure what you want to change. You have `CupertinoFormSection` in the title but suggestion a change to another widget?

**Comment by Namitto** [comment]
@Namitto

**Comment by ziqq** [comment]
@exaby73  I have suggestion  to change margin at children divider.

**Comment by exaby73** [comment]
Thank you @ziqq for the information. Labelling this request for further insights from the team.

**Comment by skiryuk** [comment]
Is there any progress on this issue?

**Comment by skiryuk** [comment]
Is there any progress on this issue?

**Comment by SakshamSahu** [comment]
Hi @ziqq ! I am new to open source can so can you tell me where can I find CupertinoFormSection code file in Flutter Repository ?

**Comment by ziqq** [comment]
Hey @SakshamSahu, this question should be closed as the issue was resolved a long time ago with an update flutter, thx.
