### ISSUE TITLE
[Windows] System theme integration is broken

### ISSUE THREAD

**Issue by loic-sharma** [flutter/flutter#110700]
A Flutter windows app should be able to follow the system's theme:

1. **Theme awareness**. At startup, the app should be able to detect whether the system theme is in light or dark mode
2. **React to system changes**. If you switch your system theme, the app and its window should switch accordingly.

This was implemented in https://github.com/flutter/engine/pull/29303 but seems to have regressed.

**Comment by loic-sharma** [comment]
It looks like [this was implemented but is now broken](https://github.com/flutter/engine/blob/f0f8d10b8809b5a88a133a4d25bff5630ede6b0e/shell/platform/windows/settings_plugin.cc#L31).

**Comment by moko256** [comment]
Hello, I'm trying to fix this. I set dark to Windows, ran this code below with engine's master (d8928a0), and set light after the app start.

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(
    MaterialApp(
      theme: ThemeData.light(),
      darkTheme: ThemeData.dark(),
      home: const Scaffold(
        body: Center(
          child: TextField(
            decoration: InputDecoration(hintText: "Text"),
          ),
        ),
      ),
    ),
  );
}
```


The point 1 seems working on Windows 10 (21H2 19044.1949) and WIndows 11 (21H2 22000.856).  @loic-sharma Would you please run this code above after select dark mode on Windows, and check the app use the style for dark theme?


The point 2 is implemented by #29303 but the #35019 seems break this. The current SettingsPlugin doesn't open the registry key that it is used to watching the changes. [(code)](https://github.com/flutter/engine/blob/4e6bb5da58beb65258a2641b85c599d910789331/shell/platform/windows/settings_plugin.cc#L31-L39)
The old SettingsPluginWin32 contained the code to open the key in the constructor. [(code)](https://github.com/flutter/engine/blob/c4f583d1baaadaa3a65502382c4e3745d5e937d4/shell/platform/windows/settings_plugin_win32.cc#L24-L34)

**Comment by xster** [comment]
To keep monitoring but for the time being, b/241221790 is marked as a launch blocker for user

**Comment by gspencergoog** [comment]
Closing because the fixing PR https://github.com/flutter/engine/pull/35902 has landed.
