### ISSUE TITLE
[go_router] Support passing context and state to redirect, to routes generated by [go_router_builder]

### ISSUE THREAD

**Issue by danielmahon** [flutter/flutter#110795]
## Use case

The latest v5 `go_router` supports passing context and state to the route redirects but it does not work with routes generated by `go_router_builder`.

## Proposal

Update the method signature of `redirect` in `GoRouteData`

**Comment by kuhnroyal** [comment]
Same as https://github.com/flutter/flutter/issues/111909?

**Comment by danielmahon** [comment]
closing in favor of https://github.com/flutter/flutter/issues/111909
