### ISSUE TITLE
Flutter stuck on Built build\app\outputs\flutter-apk\app-debug.apk

### ISSUE THREAD

**Issue by zakblacki** [flutter/flutter#110771]
I've been trying to install my project on my physical device using IDE android studio 
but it stuck on Built build\app\outputs\flutter-apk\app-debug.apk

- If I try to launch using terminal command 
`flutter run`  it works fine without issue (although after installing the terminal is stuck I have to terminate it Ctrl+X)
- if I try to launch from  root/android folder project it also work fine.

Issue appears only when launching flutter app from IDE 
Edit : I'm using latest android ide version and flutter 3.3.0
Please note I also have both, flutter plugin from IDE and flutter installed on computer not sure if there could be
compatibility issues 

I have also followed recommendation from [stackoverflow](https://stackoverflow.com/questions/53394504/flutter-stuck-at-installing-build-app-outputs-apk-app-apk) but same issue.

**Comment by darshankawar** [comment]
@zakblacki 
Can you provide `flutter doctor -v` and `flutter build apk -v` ? The verbose log will be huge so you can put that in a text file and share it here. Make sure the log contains the entry where the process is stuck.

Also, can you try from command line outside of IDE and see if you still get same behavior or not ?

**Comment by zakblacki** [comment]
> @zakblacki Can you provide `flutter doctor -v` and `flutter build apk -v` ? The verbose log will be huge so you can put that in a text file and share it here. Make sure the log contains the entry where the process is stuck.
> 
> Also, can you try from command line outside of IDE and see if you still get same behavior or not ?

Launching from outside IDE  give almost same behavior. only difference the app install and launch successfully. 
(unlike the IDE the app install but stuck on blackscreen) but I'm wondering why the command line does not return or finish after installing 
here is the screenshot : 

![image](https://user-images.githubusercontent.com/29728429/187929485-3bb504d8-f217-4db0-8ba0-349f3ccbd672.png)


Here are the logs  :  

[buildLog.txt](https://github.com/flutter/flutter/files/9470296/buildLog.txt)

Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
(If you could provided a fix for this warning assets would be nice as well knowing I'm not using firewall) 

[√] Flutter (Channel stable, 3.3.0, on Microsoft Windows [Version 10.0.19044.1889], locale en-US)
    • Flutter version 3.3.0 on channel stable at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffccd96b62 (3 days ago), 2022-08-29 17:28:57 -0700
    • Engine revision 5e9e0e0aa8
    • Dart version 2.18.0
    • DevTools version 2.15.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\zakbl\AppData\Local\Android\Sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = C:\Users\zakbl\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] VS Code (version 1.70.2)
    • VS Code at C:\Users\zakbl\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (2 available)


    • Chrome (web) • chrome • web-javascript • Google Chrome 105.0.5195.54
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 104.0.1293.70

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Comment by darshankawar** [comment]
> One more thing I would like to report another issue this is completely different but I've having this for years now.
> Even with the IDE or using command line

Please open a new issue with all required details so that it can be tracked properly.

Regarding your original issue, I looked at the verbose log you shared, and didn't find anything unusual and also noticed that the build succeeds and the process shuts down with exit code 0 properly:

```
√  Built build\app\outputs\flutter-apk\app-release.apk (33.0MB).
[   +2 ms] "flutter apk" took 238,835ms.
[ +187 ms] ensureAnalyticsSent: 185ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 0
``` 

I see that you are accessing from China, so please check if there's any firewall or proxy settings which might be prohibiting to complete the process or making it stuck.



> Launching from outside IDE give almost same behavior. only difference the app install and launch successfully.

This indicates the framework process is working properly and it may be related to the IDE you are using.



> (unlike the IDE the app install but stuck on blackscreen)

Are you using splash screen in your app ? If so, please take a look at this document and see if you are correctly implementing it or not. https://docs.flutter.dev/development/ui/advanced/splash-screen#android-launch-screen

I suggest you to raise this issue in support channels like StackOverflow, as I see, there are similar questions raised and solved:

https://stackoverflow.com/questions/54701359/flutter-run-stuck-at-installing-build-app-outputs-apk-app-apk
https://stackoverflow.com/questions/53394504/flutter-stuck-at-installing-build-app-outputs-apk-app-apk?page=2&tab=Votes

Also, you can reach out to the IDE plugin's repo as it seems to be related to the IDE and not the flutter tool. 
Closing from here. If you disagree, write in comments and I'll reopen it.

**Comment by zakblacki** [comment]
> > One more thing I would like to report another issue this is completely different but I've having this for years now.
> > Even with the IDE or using command line
> 
> Please open a new issue with all required details so that it can be tracked properly.
> 
> Regarding your original issue, I looked at the verbose log you shared, and didn't find anything unusual and also noticed that the build succeeds and the process shuts down with exit code 0 properly:
> 
> ```
> √  Built build\app\outputs\flutter-apk\app-release.apk (33.0MB).
> [   +2 ms] "flutter apk" took 238,835ms.
> [ +187 ms] ensureAnalyticsSent: 185ms
> [   +1 ms] Running shutdown hooks
> [        ] Shutdown hooks complete
> [        ] exiting with code 0
> ```
> 
> I see that you are accessing from China, so please check if there's any firewall or proxy settings which might be prohibiting to complete the process or making it stuck.
> 
> > Launching from outside IDE give almost same behavior. only difference the app install and launch successfully.
> 
> This indicates the framework process is working properly and it may be related to the IDE you are using.
> 
> > (unlike the IDE the app install but stuck on blackscreen)
> 
> Are you using splash screen in your app ? If so, please take a look at this document and see if you are correctly implementing it or not. https://docs.flutter.dev/development/ui/advanced/splash-screen#android-launch-screen
> 
> I suggest you to raise this issue in support channels like StackOverflow, as I see, there are similar questions raised and solved:
> 
> https://stackoverflow.com/questions/54701359/flutter-run-stuck-at-installing-build-app-outputs-apk-app-apk https://stackoverflow.com/questions/53394504/flutter-stuck-at-installing-build-app-outputs-apk-app-apk?page=2&tab=Votes
> 
> Also, you can reach out to the IDE plugin's repo as it seems to be related to the IDE and not the flutter tool. Closing from here. If you disagree, write in comments and I'll reopen it.

I'm definitely not accessing from China or using firewall proxy this is very disturbing confusing since [my public IP]([105.101.159.103](https://whatismyipaddress.com/ip/105.101.159.103)) is showing in my current country location...

As I have mentioned previously root/android worked fine 
command line despite installing and launching it does not give back user input it stay stuck 
I have also tested on a new flutter clean project same issue (both IDE and command line)
I even tested with another phone 
So at this point I'm guessing it's either my windows or flutter 

I will try reinstalling flutter and see if this resolves it.

![image](https://user-images.githubusercontent.com/29728429/188158941-7c0b4712-4401-4c99-b6e0-28bfdb8b87aa.png)
