### ISSUE TITLE
Cannot install plugin tools

### ISSUE THREAD

**Issue by arashbi** [flutter/flutter#11075]
## Steps to Reproduce

flutter git:(master) ✗ pub global activate flutter_plugin_tools 

## Logs

Resolving dependencies... 
Package http has no versions that match >=0.11.3+13 <0.12.0 derived from:
- flutter_plugin_tools 0.0.1-dev depends on version ^0.11.3+13

## Flutter Doctor

[✓] Flutter (on Mac OS X 10.11.6 15G1510, locale en, channel master)
    • Flutter at /Users/arash/Src/flutter
    • Framework revision 7ba1879bfc (18 hours ago), 2017-07-01 14:16:36 -0700
    • Engine revision 8ad1576f27
    • Tools Dart version 1.24.2

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at /Users/arash/tools/android-sdk
    • Platform android-25, build-tools 25.0.3
    • ANDROID_HOME = /Users/arash/tools/android-sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[-] iOS toolchain - develop for iOS devices (Xcode 8.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.1, Build version 8B62, 
    ✗ Your Mac needs to enabled for developer mode before using Xcode for the first time.
      Run 'sudo DevToolsSecurity -enable' or open Xcode
    • ios-deploy 1.9.1
    • CocoaPods version 1.2.1

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.1.4)
    • Flutter plugin version 15.0
    • Dart plugin version 171.4694.29

**Comment by devoncarew** [comment]
If you're running `pub global activate` directly, it's using the version of the dart sdk that's on your path, which may be different than the version shipped with flutter (you can run `dart --version` to see the version on your path). I suspect that you have an old version of dart, and pub is having trouble resolving a version of package:http that will work with it. You'll probably want to update your path to include `path/to/flutter/bin/cache/dart-sdk/bin`, or could try running `flutter packages pub global activate flutter_plugin_tools`.

**Comment by arashbi** [comment]
That worked! but now I cannot run the tool . when I try to format, it gives me this error:

> pub global run flutter_plugin_tools format
> Unhandled exception:
> Invalid argument(s): Uri http://localhost:64119/flutter_plugin_tools.dart must have scheme 'file:'.
> #0      PosixStyle.pathFromUri (package:path/src/style/posix.dart:44:5)
> #1      Context.fromUri (package:path/src/context.dart:963:18)
> #2      fromUri (package:path/path.dart:387:32)
> #3      FormatCommand._getGogleFormatterPath (package:flutter_plugin_tools/src/format_command.dart:108:19)
> <asynchronous suspension>
> #4      FormatCommand.run (package:flutter_plugin_tools/src/format_command.dart:33:46)
> <asynchronous suspension>
> #5      CommandRunner.runCommand (package:args/command_runner.dart:194:27)
> <asynchronous suspension>
> #6      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109:29)
> #7      new Future.sync (dart:async/future.dart:206)
> #8      CommandRunner.run (package:args/command_runner.dart:109:11)
> #9      main (package:flutter_plugin_tools/src/main.dart:37:17)
> #10     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
> #11     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
>

**Comment by devoncarew** [comment]
Hmm, I'm less familiar with the `flutter/plugin_tools` repo, but @goderbauer is :) .

Can you paste the output of `dart --version` here? I suspect that you do have an older version of dart on your path, and that's causing these other issues.

**Comment by mit-mit** [comment]
I believe you need to make sure flutter is in path before dart. Take a look at https://github.com/flutter/plugins/blob/master/.travis.yml

**Comment by goderbauer** [comment]
To run the plugin tools, you want to make sure that you've a current installation of Flutter and that flutter is in your path. (e.g. you can just run the `flutter` command from any terminal). After that, you can just use the dart version that comes bundled with Flutter to install and run the plugin tools:

```
$ <path-to-flutter>/bin/cache/dart-sdk/bin/pub global activate flutter_plugin_tools
$ <path-to-flutter>/bin/cache/dart-sdk/bin/pub global run flutter_plugin_tools format
```

I'll document this better with the plugin tools.

As an alternative to running the formatter, you can just apply the diff that travis creates for the formatting problems to your PR.

**Comment by mit-mit** [comment]
@arashbi does this resolve your issue, and can we close this issue?

**Comment by mit-mit** [comment]
Closing, @arashbi please re-open if your issue wasn't resolved.
