### ISSUE TITLE
FirebaseSortedList throws UnsupportedError when updating list item

### ISSUE THREAD

**Issue by BoaNeo** [flutter/flutter#11081]
The FirebaseSortedList class throws UnsupportedError in the []= operator (line 70) which it itself uses in the _onChildChanged callback. This causes an error whenever a change is made in Firebase while the app is monitoring the given collection.

I've removed the throw and provided a straight forward implementation of the method. This works for me in my current use case, so I'm not sure why this exception is thrown in the first place?

  @override
  void operator []=(int index, DataSnapshot value) {
    _snapshots[index] = value;
  }

If the exception is intentional to prevent external modification of the list, then maybe line 97 should be 

    _snapshots[index] = event.snapshot;

instead of

  this[index]=event.snapshot

Which directly triggers the exception.

**Comment by Hixie** [comment]
@goderbauer claims to have fixed it.
