### ISSUE TITLE
Flutter forces JAVA_HOME to android studio's default JDK #108804

### ISSUE THREAD

**Issue by arteminthesky** [flutter/flutter#110807]
Duplicate of #108804

Hi. On my Jenkins i found the problem with jdk. The problem is Flutter forces JAVA_HOME as founded default JDK in Android Studio.app ([Determine JDK](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/android/android_studio.dart#L449), [Force JAVA_HOME](https://github.com/flutter/flutter/blob/c99f60b82f03db3c4a6cfee2a53ffb73e53ab431/packages/flutter_tools/lib/src/android/gradle.dart#L442))
I think this is not expected behavior when i don't want to use Studio's settings.

Is there a way to not rewrite JAVA_HOME in case it's already set? 

## Steps to Reproduce

1. Run `flutter build apk` command
2. See log output
3. See `<JDK> -version` command

**Actual result:**
Flutter used default JDK from Android Studio
Gradle throws error since default JDK contains Java 1.8 (Java 11 is required)

**Expected result:**
Flutter uses JAVA_HOME (in case it's defined)

## Logs

<details>

```
[✓] Flutter (Channel unknown, 3.0.0, on Mac OS X 10.15.4 19E287 darwin-x64, locale en-GB)
    • Flutter version 3.0.0 at ***
    • Upstream repository unknown
    • Framework revision ee4e09cce0 (3 months ago), 2022-05-09 16:45:18 -0700
    • Engine revision d1b9a6938a
    • Dart version 2.17.0
    • DevTools version 2.12.2

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Applications/Android/sdk/
    • Platform android-32, build-tools 30.0.3
    • ANDROID_HOME = /Applications/Android/sdk/
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[!] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Applications/Xcode-12.4.app/Contents/Developer
    ✗ Flutter requires Xcode 13 or higher.
      Download the latest version or update via the Mac App Store.
    ! CocoaPods 1.10.1 out of date (1.11.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] Connected device (1 available)
    • macOS (desktop) • macos • darwin-x64 • Mac OS X 10.15.4 19E287 darwin-x64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 3 categories.
```
</details>

**Comment by chapsan2001** [comment]
Reproduced on master branch, seems like my JAVA_HOME (Java 18.0.0.1) is ignored.

```[ +776 ms] executing: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java -version
[  +52 ms] Exit code 0 from: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java -version
[        ] openjdk version "11.0.11" 2021-04-20
           OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
           OpenJDK 64-Bit Server VM (build 11.0.11+0-b60-7772763, mixed mode)
```

## Flutter Doctor

<details>
[✓] Flutter (Channel master, 3.5.0-0.0.pre.16, on macOS 12.3 21E230 darwin-arm64, locale ru-RU)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

• No issues found!
</details>

**Comment by arteminthesky** [comment]
There is error happens when outdated AS (with jdk 1.8) used on the Jenkins node (or another environment). But this AS is needed for another project.

**Comment by exaby73** [comment]
I can reproduce this issue.

### Reproducible on

- `Stable (3.3.0)`
- `Master (3.4.0-19.0.pre.38)`

### Info

```powershell
> java --version
java 17.0.4 2022-07-19 LTS
Java(TM) SE Runtime Environment (build 17.0.4+11-LTS-179)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.4+11-LTS-179, mixed mode, sharing)
```


```powershell
# Powershell equivalent of `echo $JAVA_HOME`
> echo $ENV:JAVA_HOME
C:\Program Files\Common Files\Oracle\Java\javapath
```

```powershell
> fvm flutter build apk -v
# ...
[  +54 ms] 💪 Building with sound null safety 💪
[  +15 ms] Running Gradle task 'assembleRelease'...
[   +3 ms] Using gradle from C:\Users\Nabeel\dev\nevercode\issue_110807\android\gradlew.bat.
[  +11 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
[ +155 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
[        ] openjdk version "11.0.12" 2021-07-20
           OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
           OpenJDK 64-Bit Server VM (build 11.0.12+7-b1504.28-7817840, mixed mode)
# ...
```

### Flutter Doctor

<details><summary><code>flutter doctor -v</code> (Stable)</summary>

```
[✓] Flutter (Channel stable, 3.3.0, on Microsoft Windows [Version 10.0.22000.918], locale en-IN)
    • Flutter version 3.3.0 on channel stable at C:\Users\Nabeel\fvm\versions\stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffccd96b62 (3 days ago), 2022-08-29 17:28:57 -0700
    • Engine revision 5e9e0e0aa8
    • Dart version 2.18.0
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\android-sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2022 17.3.2)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.3.32819.101
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[✓] VS Code (version 1.70.2)
    • VS Code at C:\Users\Nabeel\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.46.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22000.918]
    • Chrome (web)      • chrome  • web-javascript • unknown
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 104.0.1293.70

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

<details><summary><code>flutter doctor -v</code> (Master)</summary>

```
[✓] Flutter (Channel master, 3.4.0-19.0.pre.38, on Microsoft Windows [Version 10.0.22000.918], locale en-IN)
    • Flutter version 3.4.0-19.0.pre.38 on channel master at C:\Users\Nabeel\fvm\versions\master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9fce42fca8 (14 minutes ago), 2022-09-02 05:45:20 -0400
    • Engine revision 022ebd2e61
    • Dart version 2.19.0 (build 2.19.0-154.0.dev)
    • DevTools version 2.16.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\android-sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2022 17.3.2)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.3.32819.101
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[✓] VS Code (version 1.70.2)
    • VS Code at C:\Users\Nabeel\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.46.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22000.918]
    • Chrome (web)      • chrome  • web-javascript • unknown
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 104.0.1293.70

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by arteminthesky** [comment]
As I see, we have 2 options to fix the problem:
1. Add some parameter to flutter build apk/appbundle command (for example, --use-java-home)
2. Always use JAVA_HOME don't overwrite it in case it is not empty.

Second option can produce many problems for users, not all people think about their java environment and don't know about which java used by flutter under the hood while building. In this case it's good that flutter uses AS java.

**Comment by christopherfujino** [comment]
cc @TahaTesser would you happen to know if there is a bug here in our Java detection logic?

**Comment by TahaTesser** [comment]
I don't think this is a bug. [Android Studio setup](https://docs.flutter.dev/get-started/install/macos#android-setup) provides Android platform dependencies which include bundled Java and there is no extra step to install Java separately hence `flutter_tools` relies on Android Studio's dependencies. 

> Second option can produce many problems for users, not all people think about their java environment and don't know about which java used by flutter under the hood while building. In this case it's good that flutter uses AS java.

Agree, that this is working as intended. 

- If `JAVA_HOME` detection is prioritized over default JDK, it could create build issues.
- Adding a parameter to override Java used for the build is a better solution IMO, similar to `flutter config --android-sdk`.

**Comment by arteminthesky** [comment]
@TahaTesser @christopherfujino can i try to implement first option (additional parameter in flutter config/build command)?

**Comment by christopherfujino** [comment]
> I don't think this is a bug. [Android Studio setup](https://docs.flutter.dev/get-started/install/macos#android-setup) provides Android platform dependencies which include bundled Java and there is no extra step to install Java separately hence `flutter_tools` relies on Android Studio's dependencies.
> 
> > Second option can produce many problems for users, not all people think about their java environment and don't know about which java used by flutter under the hood while building. In this case it's good that flutter uses AS java.
> 
> Agree, this is working as intended.
> 
> * If `JAVA_HOME` detection is prioritized over default JDK, it could create build issues.
> * Adding a parameter to override Java used for the build is a better solution IMO, similar to `flutter config --android-sdk`.

@GaryQian can you think of any reason this wouldn't be a good idea?

**Comment by raghavsatyadev** [comment]
I am facing this issue on my latest Android Studio Flamingo | 2022.2.1 Canary 2

Its working for stable studio but not for canary

```
C:\Work\Software\Android\FlutterSDK>flutter doctor -v
[√] Flutter (Channel master, 3.4.0-33.0.pre.40, on Microsoft Windows [Version 10.0.22000.978], locale en-IN)
    • Flutter version 3.4.0-33.0.pre.40 on channel master at C:\Work\Software\Android\FlutterSDK
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9bf849184d (85 minutes ago), 2022-09-28 07:37:29 -0400
    • Engine revision c78c35f9de
    • Dart version 2.19.0 (build 2.19.0-250.0.dev)
    • DevTools version 2.17.0

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Work\Software\Android\SDK
    • Platform android-33, build-tools 33.0.0
    • Java binary at:
      C:\Users\MobileProgramming\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-1\213.7172.25.2113.9014738\jre\bi
      n\java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2021.3)
    • Android Studio at
      C:\Users\MobileProgramming\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-1\213.7172.25.2113.9014738
    • Flutter plugin version 70.0.3
    • Dart plugin version 213.7371
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[!] Android Studio (version 2022.2)
    • Android Studio at
      C:\Users\MobileProgramming\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\222.4167.29.2221.9093980
    • Flutter plugin version 70.0.5
    • Dart plugin version 222.4167.21
    X Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[√] VS Code (version 1.69.0-insider)
    • VS Code at C:\Users\MobileProgramming\AppData\Local\Programs\Microsoft VS Code Insiders
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (4 available)
    • Moto G 5 Plus (mobile) • ZY223VVK5V • android-arm    • Android 8.1.0 (API 27)
    • Windows (desktop)      • windows    • windows-x64    • Microsoft Windows [Version 10.0.22000.978]
    • Chrome (web)           • chrome     • web-javascript • Google Chrome 105.0.5195.127
    • Edge (web)             • edge       • web-javascript • Microsoft Edge 105.0.1343.50

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.
```

<details>
<summary> 
<h3>Flutter Plugin Error Logs</h3>
</summary>
com.intellij.diagnostic.PluginException: Cannot create extension (class=io.flutter.FlutterStudioInitializer) [Plugin: io.flutter]
	at com.intellij.serviceContainer.ComponentManagerImpl.createError(ComponentManagerImpl.kt:945)
	at com.intellij.openapi.extensions.impl.XmlExtensionAdapter.doCreateInstance(XmlExtensionAdapter.kt:70)
	at com.intellij.openapi.extensions.impl.XmlExtensionAdapter.createInstance(XmlExtensionAdapter.kt:31)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processAdapter(ExtensionPointImpl.java:475)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processAdapters(ExtensionPointImpl.java:423)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.computeExtensionList(ExtensionPointImpl.java:251)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.getExtensionList(ExtensionPointImpl.java:245)
	at com.intellij.openapi.extensions.ExtensionPointName.getExtensionList(ExtensionPointName.java:39)
	at com.android.tools.idea.AndroidInitialConfigurator.activateAndroidStudioInitializerExtensions(AndroidInitialConfigurator.java:52)
	at com.android.tools.idea.AndroidInitialConfigurator.<init>(AndroidInitialConfigurator.java:30)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.intellij.serviceContainer.ConstructorInjectionKt.instantiateUsingPicoContainer(constructorInjection.kt:47)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClassWithConstructorInjection(ComponentManagerImpl.kt:890)
	at com.intellij.serviceContainer.MyComponentAdapter.doCreateInstance(MyComponentAdapter.kt:35)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:119)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:73)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance$default(BaseComponentAdapter.kt:66)
	at com.intellij.serviceContainer.ComponentManagerImpl$createInitOldComponentsTask$1.run(ComponentManagerImpl.kt:393)
	at com.intellij.idea.ApplicationLoader$prepareStart$1.run(ApplicationLoader.kt:217)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:881)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:513)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:75)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:118)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:42)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:402)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
Caused by: java.lang.ClassNotFoundException: io.flutter.FlutterStudioInitializer PluginClassLoader(plugin=PluginDescriptor(name=Flutter, id=io.flutter, descriptorPath=plugin.xml, path=~\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\222.4167.29.2221.9093980.plugins\flutter-intellij, version=70.0.5, package=null, isBundled=false), packagePrefix=null, instanceId=129, state=active)
	at com.intellij.serviceContainer.ComponentManagerImplKt.doLoadClass(ComponentManagerImpl.kt:1468)
	at com.intellij.serviceContainer.ComponentManagerImplKt.access$doLoadClass(ComponentManagerImpl.kt:1)
	at com.intellij.serviceContainer.ComponentManagerImpl.loadClass(ComponentManagerImpl.kt:835)
	at com.intellij.openapi.extensions.impl.InterfaceExtensionImplementationClassResolver.resolveImplementationClass(InterfaceExtensionImplementationClassResolver.kt:24)
	at com.intellij.openapi.extensions.impl.XmlExtensionAdapter.doCreateInstance(XmlExtensionAdapter.kt:49)
	... 43 more
</details>

**Comment by exaby73** [comment]
Depuping with https://github.com/flutter/flutter/issues/106416
