### ISSUE TITLE
No results reported to SkiaPerf for two days

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#110864]
For example: https://flutter-flutter-perf.skia.org/e/?begin=1661729192&end=1662073891&queries=sub_result%3D90th_percentile_frame_rasterizer_time_millis%26sub_result%3D99th_percentile_frame_rasterizer_time_millis%26sub_result%3Daverage_frame_rasterizer_time_millis%26sub_result%3Dworst_frame_rasterizer_time_millis%26test%3Dnew_gallery_impeller_ios__transition_perf&requestType=0

@keyonghan It looks like this problem goes beyond the one benchmark where build_test was being tested.

**Comment by zanderso** [comment]
The last commit I am seeing results for across several benchmarks is https://github.com/flutter/flutter/commit/1f236a9b6f647c435410dc5516b4b5873cb46a2e

**Comment by keyonghan** [comment]
Looking at `Mac_ios new_gallery_impeller_ios__transition_perf`, the metrics were uploaded to GCS:
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8804121187428848721/+/u/Upload_metrics/upload_results/stdout
Metrics do exist in GCS as well.
Seems something wrong with Skia getting the data.

**Comment by yusuf-goog** [comment]
Contacting skia team to determine if there is an event on their end.

**Comment by yusuf-goog** [comment]
https://bugs.chromium.org/p/skia/issues/detail?id=13718 for follow up.

**Comment by godofredoc** [comment]
Configurations have been updated and missing data has been processed.
