### ISSUE TITLE
[go_router] multi/partial nested stack support

### ISSUE THREAD

**Issue by noga-dev** [flutter/flutter#110823]
I'd like to revive [this ](https://github.com/csells/go_router/discussions/222) discussion and highlight that we still don't have support for nested multi stack nav in go_rotuer like in this example: 

![1_uzUPFNAImoqdz9tFbUT1WQ](https://user-images.githubusercontent.com/2067558/188028403-caf0aedb-c75e-4465-9b68-35e6076822de.gif)

(image source: https://medium.com/flutter-senior/app-state-vs-go-router-for-flutter-navigation-397316f30dcb)

**Comment by darshankawar** [comment]
@noga-dev 
Check out this similar issue: https://github.com/flutter/flutter/issues/99126 and I suggest you to follow-up in it for further updates and you may share your findings / questions in that issue for better tracking.

Closing this as a duplicate. If you disagree, write in comments and I'll reopen it.
