### ISSUE TITLE
Flutter web can't handle URL encodings

### ISSUE THREAD

**Issue by sirwes** [flutter/flutter#110813]
I have a flutter app enabled for android, iOS, and web. I have a link that sends users to the page on the web version if they don't have the mobile app. The link works as expected for iOS and android and it redirects to the website as expected.

The URL I redirect them to looks something like this: https://my.url/#/mypagename?myparameter=1234&mysecondparam=2345.
This URL works and brings me right to the page if I key it in exactly how you see it above.

But if I click the link on an iphone or imac (android and pc work fine) and the redirect happens, the URL changes to https://my.url/%23/mypagename?myparameter%3D1234%2Bmysecondparam%3D2345 and I'm brought to a blank web page.
This behavior also happens if I key the URLs in manually exactly as described - the first one brings me to the page and the second one brings me to a blank screen on iOS devices.

It seems that the URL encodings for special characters makes it so that the flutter web engine doesn't recognize where to go. At least that's my guess.
See the url encodings here: https://www.eso.org/~ndelmott/url_encode.html

Expected fix
A URL with URL-encoded special characters should return the same webpage as the normal URL

Additional context
The page the URL references isn't the default or "first" page and it has function parameter requirements.
Also, sometimes I get a 404 error when trying to access the URL-encoded page that says 
> Additionally, a 404 error was encountered while trying to use an ErrorDocument to handle the request

**Comment by danagbemava-nc** [comment]
Hi @sirwes,

Can you please provide your `flutter doctor -v` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?

Thank you
