### ISSUE TITLE
[CP] Fix Windows accessibility crash on ReorderableListView 

### ISSUE THREAD

**Issue by loic-sharma** [flutter/flutter#110820]
### issue_link

https://github.com/flutter/flutter/issues/103808

### Commit Hash

https://github.com/flutter/engine/commit/ead1348803aacfaf6b5bf474f4a8b9a5eac625c4

### Target

stable

### pr_link

https://github.com/flutter/engine/pull/35875

### Impacted Users

Windows users that use an accessibility tool

### Impact Description

Windows app crash if accessibility is enabled on an app that uses a widget with custom semantic actions (like `ReorderableListView`).

### Workaround

Avoid widgets like `ReorderableListView` on Windows.

### Risk

low

### Test Coverage

yes

### Validation Steps

Enable a screen reader and start an app that hasa `ReorderableListView` widget: https://github.com/flutter/flutter/issues/103808#issuecomment-1144347869

**Comment by itsjustkevin** [comment]
Approved based on LGTM from @cbracken at https://github.com/flutter/engine/pull/35875.
