### ISSUE TITLE
Arabic text having duplicate letters when having different color in RichText

### ISSUE THREAD

**Issue by deadlyrazer** [flutter/flutter#110875]
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. copy paste code and run.

**Expected results:**
![arabictextnormal](https://user-images.githubusercontent.com/43774856/188116251-daa8618c-a16d-4fb8-998f-fcfd1d4bd0e2.png)

**Actual results:** 
The extra letter is not in the string yet it gets added.
![arabictextbug](https://user-images.githubusercontent.com/43774856/188116345-0936de54-cea2-4e31-a9ea-3225df0a2a8d.png)

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
void main() {
  runApp(MyApp());
}
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: ArabicTextIssue(),
    );
  }
}

class ArabicTextIssue extends StatelessWidget {
  const ArabicTextIssue({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: RichText(
          textAlign: TextAlign.justify,
          textDirection: TextDirection.rtl,
          text: const TextSpan(
            children: [
              TextSpan(
                text: "فَ",
                style: TextStyle(color: Colors.black),
              ),
              TextSpan(
                text: 'مَن جَآ',
                style: TextStyle(color: Colors.red),
              ),
              TextSpan(
                text: "َهُ",
                style: TextStyle(color: Colors.black),
              ),
            ],
            style: TextStyle(
              fontSize: 50,
            ),
          ),
        ),
      ),
    );
  }
}
```

</details>
<details>  <summary>Issue Detail</summary>

### Reproduction detail
This issue's present in android, windows and browser.

It does **not** happen when all the `TextSpan` surrounding the broken text are the same color.
For example, when the middle `TextSpan` is `Colors.black` instead of red, then the issue is no more as seen in expected results image.

#### Furthermore
In *another* arabic font, it happens again, even though there are only 2 letters, 1 text span for each letter.
![image](https://user-images.githubusercontent.com/43774856/188219158-5c9f5c9f-73cc-41ed-b4f0-f017fd7de30e.png)

 Same thing happens in this example if we replace `ك` with `ل` or `غ` or `ع`.
 I'm *assuming* this happens in **this example** with 2 letters — because when the letter is by itself it looks like so
 ![image](https://user-images.githubusercontent.com/43774856/188220343-00408063-8147-4a5a-a47d-352baad43a99.png)
 However when attached with the letter after (`ا`), because of the language, it needs to joined and transforms like this `ك`  to   `كا`  it uses some other style for the first letter and because of that it gets broken.

<details> 
     <summary>  Issue in another font code</summary>

[Font download link](https://onedrive.live.com/?authkey=%21AGLHph%5FSltZGH2g&cid=132F7C6739128CF9&id=132F7C6739128CF9%212575&parId=root&action=locate)

```dart
RichText(
                text: TextSpan(
                  children: [
        
                    TextSpan(
                      text: "ك",
                      style: TextStyle(color: Colors.red),
                    ),
                    TextSpan(
                      text: "ا",
                      style: TextStyle(color: Colors.black),
                    ),
                  ],
                  style: TextStyle(
                    fontSize: 70,
                    fontFamily: 'nastaleeq',
                  ),
                ),
              )
```

</details>
</details>

<details>
  <summary>Logs</summary>

```
[√] Flutter (Channel master, 3.4.0-19.0.pre.36, on Microsoft Windows [Version 10.0.22000.856], locale en-US)
    • Flutter version 3.4.0-19.0.pre.36 on channel master at C:\Development\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 66ec13fab4 (10 hours ago), 2022-09-02 03:57:22 -0400
    • Engine revision 0b7842b4d4
    • Dart version 2.19.0 (build 2.19.0-154.0.dev)
    • DevTools version 2.16.0

[!] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at C:\Users\user\AppData\Local\Android\sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    ! Some Android licenses not accepted. To resolve this, run: flutter doctor --android-licenses

[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[√] Visual Studio - develop for Windows (Visual Studio Build Tools 2019 16.11.11)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
    • Visual Studio Build Tools 2019 version 16.11.32228.343
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] VS Code (version 1.71.0)
    • VS Code at C:\Users\user\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.48.0

[√] Connected device (2 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22000.856]
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 104.0.1293.70

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.
```

</details>

**Comment by deadlyrazer** [comment]
@jason-simmons Can you please look into this issue? Will be much appreciated.

**Comment by danagbemava-nc** [comment]
Issue is reproducible on `stable` and `master`. 

<details>
<summary>screenshots</summary>

| different colors | all black | 
| -- | -- | 
| <img src="https://user-images.githubusercontent.com/88313112/188387645-83ab26ad-982e-4d6a-ab80-4c24e05961ab.png" /> | <img src="https://user-images.githubusercontent.com/88313112/188387675-4c5af94a-fae9-4dcb-b7af-a9f3e3f83748.png" /> |

</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.3.0, on macOS 12.5 21G72 darwin-arm, locale en-GB)
    • Flutter version 3.3.0 on channel stable at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffccd96b62 (6 days ago), 2022-08-29 17:28:57 -0700
    • Engine revision 5e9e0e0aa8
    • Dart version 2.18.0
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F100
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.71.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (4 available)
    • Nexus (mobile)         • 00008020-001875E83A38002E            • ios            • iOS 15.6.1 19G82
    • iPhone 13 Pro (mobile) • 6E074BA5-191C-47D4-892F-FD96AFC34148 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.5 21G72 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 104.0.5112.101

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

```
[✓] Flutter (Channel master, 3.4.0-19.0.pre.72, on macOS 12.5 21G72 darwin-arm64, locale en-GB)
    • Flutter version 3.4.0-19.0.pre.72 on channel master at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 202f5771f4 (7 hours ago), 2022-09-04 20:28:23 -0400
    • Engine revision b94120dfe9
    • Dart version 2.19.0 (build 2.19.0-168.0.dev)
    • DevTools version 2.17.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F100
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.71.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (4 available)
    • Nexus (mobile)         • 00008020-001875E83A38002E            • ios            • iOS 15.6.1 19G82
    • iPhone 13 Pro (mobile) • 6E074BA5-191C-47D4-892F-FD96AFC34148 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.5 21G72 darwin-arm64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 104.0.5112.101

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by aakansharamesh42** [comment]
Hi, can you assign this issue to me.

**Comment by jason-simmons** [comment]
This issue can be reproduced with this simplified example.

It generates an SkParagraph width comparison assertion in `TextLine::iterateThroughVisualRuns`.

```
void main() {
  runApp(RichText(
    textDirection: TextDirection.rtl,
    text: const TextSpan(
        children: [
        TextSpan(
            text: '\u062c\u064e\u0627\u0653',
            style: TextStyle(color: Colors.red),
        ),
        TextSpan(
            text: '\u064e\u0647\u064f',
            style: TextStyle(color: Colors.white),
        ),
        ],
        style: TextStyle(fontSize: 50),
    ),
  ));
}
```

The text in this example is a 14-byte string when encoded in UTF-8.  The red segment contains UTF-8 bytes 0-7, and the white segment is bytes 8-13.

SkShaper/HarfBuzz outputs these glyphs from this text:
```
Glyph id=445 cluster=0
Glyph id=78 cluster=2
Glyph id=426 cluster=4
Glyph id=78 cluster=4
Glyph id=71 cluster=10
Glyph id=79 cluster=12
```

SkParagraph uses the cluster values to map UTF-8 indexes to glyphs in order to calculate which glyphs should be painted red versus white.

For the white (indexes 8-13) range there is no cluster that starts at index 8.  So SkParagraph looks backward and considers the clusters starting at index 4 to cover part of the 8-13 range.  These clusters are also part of the red (indexes 0-7) range, so they are painted in both the red and white segments.

I'm not familiar with Arabic and do not know why HarfBuzz is calculating these clusters for this text.  I tried upgrading to the latest HarfBuzz but got the same results.

@Rusino Not sure what should be done about this.  Maybe it would be feasible for something like `TextLine::iterateThroughSingleRunByStyles` to track which clusters have been consumed so that a particular cluster is not mapped to multiple styles?

**Comment by aakansharamesh42** [comment]
Where should I PR the code?

**Comment by deadlyrazer** [comment]
> Where should I PR the code?

Did you manage to fix it?

**Comment by aakansharamesh42** [comment]
> > Where should I PR the code?
> 
> Did you manage to fix it?

Yes

**Comment by deadlyrazer** [comment]
> > > Where should I PR the code?
> > 
> > 
> > Did you manage to fix it?
> 
> Yes

Can you send the code or file so I can test it further to see the performance in huge texts and see if it breaks anything else?
And the steps as well if you don't mind if it's complicated.

**Comment by aakansharamesh42** [comment]
Wh

> > > > Where should I PR the code?
> > > 
> > > 
> > > Did you manage to fix it?
> > 
> > 
> > Yes
> 
> Can you send the code or file so I can test it further to see the performance in huge texts and see if it breaks anything else? And the steps as well if you don't mind if it's complicated.

Where do you want me to send the code

**Comment by deadlyrazer** [comment]
> Wh
> 
> > > > > Where should I PR the code?
> > > > 
> > > > 
> > > > Did you manage to fix it?
> > > 
> > > 
> > > Yes
> > 
> > Can you send the code or file so I can test it further to see the performance in huge texts and see if it breaks anything else? And the steps as well if you don't mind if it's complicated.
> 
> Where do you want me to send the code

Here, just zip the files and upload them on a cloud somewhere and paste the link.

**Comment by aakansharamesh42** [comment]
https://drive.google.com/file/d/1I-DBsjgo2EBSbTHNMNHyRom9O3vcm4IX/view?usp=sharing

> > Wh
> > > > > > Where should I PR the code?
> > > > > 
> > > > > 
> > > > > Did you manage to fix it?
> > > > 
> > > > 
> > > > Yes
> > > 
> > > 
> > > Can you send the code or file so I can test it further to see the performance in huge texts and see if it breaks anything else? And the steps as well if you don't mind if it's complicated.
> > 
> > 
> > Where do you want me to send the code
> 
> Here, just zip the files and upload them on a cloud somewhere and paste the link.

https://drive.google.com/file/d/1I-DBsjgo2EBSbTHNMNHyRom9O3vcm4IX/view?usp=sharing

**Comment by aakansharamesh42** [comment]
https://drive.google.com/file/d/1I-DBsjgo2EBSbTHNMNHyRom9O3vcm4IX/view?usp=sharing

**Comment by deadlyrazer** [comment]
> https://drive.google.com/file/d/1I-DBsjgo2EBSbTHNMNHyRom9O3vcm4IX/view?usp=sharing

All you did was "َهُ" remove the extra character from here, which I knew before as well and could've done so.

**Comment by saad197** [comment]
Can also reproduce. I really hope it is fixed soon.
