### ISSUE TITLE
How Do I Install Flutter??

### ISSUE THREAD

**Issue by DevBeatDad** [flutter/flutter#110871]
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

<details>
<summary>Logs</summary>

```
```

```
```

</details>

**Comment by ak19992017** [comment]
Refer to Flutter website

**Comment by bernaferrari** [comment]
https://docs.flutter.dev/get-started/install

**Comment by aakansharamesh42** [comment]
Is this issue still open? Do you require any further assistance?

**Comment by darshankawar** [comment]
Closing as above link should help to answer your question.
