### ISSUE TITLE
[Flutter 3.3] crash at app start on iOS using the Impeller

### ISSUE THREAD

**Issue by Tom3652** [flutter/flutter#110839]
## Steps to Reproduce

I have read the release notes and the medium articles about `flutter 3.3` and there was mentioned the use of `Impeller` as a new engine. 
I wanted to try it in my app by adding the following lines to the `Info.plist`: 

```
  <key>FLTEnableImpeller</key>
  <true/>
```

But as soon as i run my app it crashes with this exception : 

```
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x50)
    frame #0: 0x000000010b5a4474 Flutter`flutter::DisplayListBuilder::restore() + 20
Flutter`flutter::DisplayListBuilder::restore:
->  0x10b5a4474 <+20>: ldp    x9, x8, [x0, #0x50]
    0x10b5a4478 <+24>: sub    x9, x8, x9
    0x10b5a447c <+28>: asr    x9, x9, #5
    0x10b5a4480 <+32>: mov    x10, #-0x5555555555555556
```

I have run it 3 times and saw this crash 3 times.  
I have removed the lines from the `Info.plist` and my app is working fine again. 

I have also changed the way i handle errors. Before, i was using the `runZoneGuarded` method and catch everything inside, now i am using the `PlatformDispatcher` : 

```
PlatformDispatcher.instance.onError = (error, stack) {
    LogManager.e("Error from outside Flutter : $error \n $stack");
    if (Firebase.apps.isNotEmpty) {
      FirebaseCrashlytics.instance.recordError(error, stack);
    }
    return true;
  };
``` 

I am aware that `Impeller` is under work and this is only for testing purposes that i have tried it in my app and make an issue to help you guys. 
However, my app is actually very big and has maaaaany dependencies and i have not time right now to try them one by one to see if there is a conflict or something. 

**Expected results:** 

The app should run normally like it's running without Impeller.

**Actual results:** 

The app crashes by using the Impeller.

```

[✓] Flutter (Channel stable, 3.3.0, on macOS 12.5.1 21G83 darwin-x64, locale fr-FR)
    • Flutter version 3.3.0 on channel stable at /Users/foxtom/Desktop/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffccd96b62 (3 days ago), 2022-08-29 17:28:57 -0700
    • Engine revision 5e9e0e0aa8
    • Dart version 2.18.0
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/foxtom/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F100
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.70.2)
    • VS Code at /Users/foxtom/Desktop/Visual Studio Code.app/Contents
    • Flutter extension version 3.46.0

[✓] Connected device (3 available)
    • Now You See Me (mobile) • 00008020-001204401E78002E • ios            • iOS 15.6.1 19G82
    • macOS (desktop)         • macos                     • darwin-x64     • macOS 12.5.1 21G83 darwin-x64
    • Chrome (web)            • chrome                    • web-javascript • Google Chrome 104.0.5112.101

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

**Comment by exaby73** [comment]
Hello @Tom3652. Are you using a physical device or a simulator? Does this issue reproduce on both for you?

**Comment by jonahwilliams** [comment]
impeller should only be used if you are willing to work on master channel. If you try there, does this issue reproduce still?

**Comment by Tom3652** [comment]
Hi @exaby73, the crash only occurs on my physical device. 
On the simulator with my app i only see a black screen but no crash and the following line in the debug logs : 

```
[VERBOSE-2:ios_context_metal_impeller.mm(22)] Using the Impeller rendering backend.
```

On the counter app it also shows a black screen on the iOS simulator but is working on the physical device. 

Hi @jonahwilliams, i have switched to the master channel but my app doesn't compile because of `google_mobile_ads` and i need to do many changes in my code, so i will stick to the stable channel for now.

Note : the counter app is working on iOS physical device on channel master.

**Comment by jonahwilliams** [comment]
The stable channel version of Impeller is quite old and does not support platform views. If you're able to reproduce the issue on master channel in the future, please don't hesitate to refile the issue. But for now I would not expect stable channel impeller to be fully functional

**Comment by Tom3652** [comment]
I have indeed Platform Views drawn at my app start. Thanks for the answer.
