### ISSUE TITLE
Touch Offsets in embedded FlutterViewController

### ISSUE THREAD

**Issue by fe9lix** [flutter/flutter#11080]
hi! i've been experimenting with embedding FlutterViewController into an existing iOS app (based on the flutter_view example). if the flutter view is set to a position different than the origin (0,0), touch locations will be offset. it appears that flutter uses global window touch coordinates and does not convert them to the local coordinate system of the flutter surface. bug or intended behavior?

**Comment by eseidelGoogle** [comment]
Sounds like a bug?  @cbracken might know.

**Comment by cbracken** [comment]
Thanks for reporting! I'll put together a small app and try to repro.

**Comment by fe9lix** [comment]
@cbracken You can test it in the flutter_view example: Just move the container view that embeds FlutterViewController 100 pt down. Then try tapping the "+" increment button. The button will only trigger if you touch 100 pt above...

**Comment by cbracken** [comment]
This should be fixed by Flutter/engine#4425.
