### ISSUE TITLE
`flutter pub outdated` output is not colored as `dart pub outdated`

### ISSUE THREAD

**Issue by jibbers42** [flutter/flutter#110884]
## Use case
When using `flutter pub outdated` the output isn't colored as in `dart pub outdated`. The plain text in the flutter output makes it more difficult to see the issues vs the red text in the dart output.

Flutter:
![image](https://user-images.githubusercontent.com/797824/188238851-4830a07c-1e74-4d53-81c8-9a0d1190ff4a.png)

Dart:
![image](https://user-images.githubusercontent.com/797824/188238808-ef4d6600-f7c4-4e6b-ba17-a0eefac78bd6.png)

## Proposal
Enable the same colored output in the flutter tool.

**Comment by darshankawar** [comment]
@jibbers42 
I verified by running `flutter pub outdated --color` which shows colored output as below:

<img width="646" alt="Screenshot 2022-09-05 at 11 22 59 AM" src="https://user-images.githubusercontent.com/67046386/188369932-18c3260e-18ba-424f-ac93-9a695a965638.png">


I am on latest master : `Channel master, 3.4.0-19.0.pre.72`. Please try the same.

Closing for now, as, it works as expected. If you disagree, write in comments and I'll reopen it.

**Comment by jibbers42** [comment]
Looking at your command, when I use the `--color` flag, it does out put color. However, dart does not require me to use the flag. It would be nice for flutter to output color by default as well.

Windows Terminal
Version: 1.14.2282.0

Edition	Windows 11 Pro
Version	21H2
OS build	22000.918
Experience	Windows Feature Experience Pack 1000.22000.918.0

**Comment by darshankawar** [comment]
Please take a look at https://github.com/flutter/flutter/issues/57411 and follow-up in it for further updates.
