### ISSUE TITLE
[Impeller] Implement Image.toByteData

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#110829]
Currently this fails with "Image was null" in

https://github.com/flutter/engine/blob/main/lib/ui/painting/image_encoding.cc#L63

**Comment by ozz-rjq** [comment]
having the same issue

**Comment by chinmaygarde** [comment]
@CoderDake This issue was prioritized for an upcoming release. Let us know if you need help or aren't able to make progress on this in the near future. Happy to help in whatever way we can.

**Comment by CoderDake** [comment]
@chinmaygarde sorry for the confusion, I think I may have accidentally assigned myself to this issue last week. I've removed myself.

**Comment by chinmaygarde** [comment]
@ColdPaleLight were you planning on rounding out support for this after https://github.com/flutter/flutter/issues/114413? If not, we can take a look too. Thanks!

**Comment by ColdPaleLight** [comment]
> @ColdPaleLight were you planning on rounding out support for this after #114413? If not, we can take a look too. Thanks!

Yes, I'll take a look and file a PR recently.
