### ISSUE TITLE
When using flutter Canvas, there is no API similar to clearing Canvas. Is there any way to fix it?

### ISSUE THREAD

**Issue by z244370114** [flutter/flutter#110831]
## Use case

The clearRect() function can specify the x, y position and width and height of the starting point to clear the canvas；
context.clearRect(0, 0, w, h);

## Proposal

Hope to have related API

**Comment by FusoraTech** [comment]
You mean fill a rect with a color?

**Comment by exaby73** [comment]
Hello @z244370114. The [`Canvas`](https://api.flutter.dev/flutter/dart-ui/Canvas-class.html) API is from the `dart:ui` library. This feature request would be better raised in [dart-lang/sdk](https://github.com/dart-lang/sdk). Closing this issue for same reason. If you disagree, please comment and I can reopen it. Thank you.
