### ISSUE TITLE
because wxwork_helper depends on both path_provider_windows 2.1.2 and win32 2.1.0, version solving failed.

### ISSUE THREAD

**Issue by baneyue** [flutter/flutter#110834]
Because win32 >=2.0.0-nullsafety.11 <2.3.8 depends on ffi ^1.0.0 and path_provider_windows >=2.1.0 depends on ffi ^2.0.0, win32 >=2.0.0-nullsafety.11 <2.3.8 is incompatible with path_provider_windows >=2.1.0.
So, because wxwork_helper depends on both path_provider_windows 2.1.2 and win32 2.1.0, version solving failed.
pub get failed (1; So, because wxwork_helper depends on both path_provider_windows 2.1.2 and win32 2.1.0, version solving failed.)

**Comment by stuartmorgan** [comment]
Version conflicts are an expected part of a versioned package ecosystem; this is not a bug. You'll need to use compatible versions of the packages you depend on.
