### ISSUE TITLE
New Flutter project templates shouldn't reference dependencies that aren't in the standard Flutter package

### ISSUE THREAD

**Issue by strangedreamsNY** [flutter/flutter#110946]
The latest Flutter Project template in Android Studio contains a dependency reference to `flutter_lint` which isn't included as a part of the standard Flutter Installation. This can cause issues when attempting to start a new project while not connected to the internet since Android Studio doesn't support `pub get` in 'offline' mode and running `flutter pub get --offline` in Chipmunk builds isn't picked up by the IDE. This leaves you unable to use code inspection, build runners, or other dart lang features needed to work on your project.   It would be helpful in the future to not include references to libraries or packages that aren't a part of the standard Flutter environment.

[flutter_doctor.txt](https://github.com/flutter/flutter/files/9485337/flutter_doctor.txt)

Flutter Plugin 70.0.2

Android Studio Chipmunk | 2021.2.1 Patch 2
Build #AI-212.5712.43.2112.8815526, built on July 10, 2022
Runtime version: 11.0.12+0-b1504.28-7817840 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 11.6.8
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Registry: external.system.auto.import.disabled=true
Non-Bundled Plugins: Jetbrains TeamCity Plugin (2021.2.99602), Dart (212.5744), io.flutter (70.0.2)

**Comment by exaby73** [comment]
Hello @strangedreamsNY. This issue is related to the IntelliJ plugin for Flutter, therefore, it might be better if it was raised in [flutter-intellij](https://github.com/flutter/flutter-intellij). Closing as this is not an issue with Flutter itself.

**Comment by strangedreamsNY** [comment]
Just ran a quick check and I can verify that this is behavior of Flutter itself and _not_ limited to any plugins or 3rd party providers.
Running the following command: `flutter create demo --project-name demo_app --template=app --offline` results in the error message; "_Because demo_app depends on flutter_lints any which doesn't exist (could not find package flutter_lints in cache), version solving failed._"

**Comment by exaby73** [comment]
Looks like from to error, you need to cache `flutter_lints`. You can see how to add a package into your cache [here](https://dart.dev/tools/pub/cmd/pub-cache). Basic gist of it is, you'll need to run `flutter pub cache add flutter_lints` while being connected to a network in order for the pub tool to download it, and then you should be able run that command.
