### ISSUE TITLE
'Canary versions are unsupported' message comes too late to be useful 

### ISSUE THREAD

**Issue by strangedreamsNY** [flutter/flutter#110943]
[The](url) error message that the Flutter Plugin doesn't support canary versions of Android Studio appears only after starting a new Flutter Project and is too late to be helpful or useful. This is a warning that should appear on the 'New Flutter Project' screen to warn a user first. Further, it's unclear whether this message is accurate given the release notes on the [Flutter Plugin home page](https://plugins.jetbrains.com/plugin/9212-flutter) which suggests that as of version 69, Canary Build 221 is supported in addition to the 2022.2.2 EAP.  

Flutter Plugin 70.0.4

Android Studio Electric Eel | 2022.1.1 Canary 10
[flutter_doctor.txt](https://github.com/flutter/flutter/files/9485246/flutter_doctor.txt)

Build #AI-221.6008.13.2211.8963757, built on August 18, 2022
Runtime version: 11.0.15+0-b2043.56-8887301 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 11.6.8
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Registry:
    external.system.auto.import.disabled=true
    ide.text.editor.with.preview.show.floating.toolbar=false

Non-Bundled Plugins:
    Dart (221.6008.17)
    io.flutter (70.0.4)
    Jetbrains TeamCity Plugin (2022.4.108706)

**Comment by exaby73** [comment]
Hello @strangedreamsNY. This issue is related to the IntelliJ plugin for Flutter, therefore, it might be better if it was raised in [flutter-intellij](https://github.com/flutter/flutter-intellij). Closing as this is not an issue with Flutter itself.
