### ISSUE TITLE
Some images cannot be displayed correctly when use app:srcCompat=

### ISSUE THREAD

**Issue by Waylon-Firework** [flutter/flutter#110965]
As shown in Image 1, FlutterFragmentActivity extends FragmentActivity instead of AppCompatActivity, therefore, in our code, we should use android:src= instead of app:srcCompat= to load images.

![image](https://user-images.githubusercontent.com/95599645/188352266-eea78faf-0037-4e85-ba41-896a8ef5c0a2.png)
![image](https://user-images.githubusercontent.com/95599645/188352288-4aef162c-df22-449f-a756-bcf08dd6ac76.png)

**Comment by huycozy** [comment]
Hi @Waylon-Firework, 
Could you please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this? Also, please provide the output of `flutter doctor -v` as well.
Thank you!
