### ISSUE TITLE
Selecting 'New Flutter Project' doesn't take you to the New Flutter Project screen.

### ISSUE THREAD

**Issue by strangedreamsNY** [flutter/flutter#110942]
The 'New Project' screen that opens when you click 'New Flutter Project' always defaults to the last selected project.

Steps to Reproduce:
- Start Android Studio
- Click 'New Flutter Project'
- Select on of the Generator Template on the left. Ex: "Android" or "IDE Plugin"
- Click 'Cancel'
- Click 'New Flutter Project'. 
[flutter_doctor.txt](https://github.com/flutter/flutter/files/9485248/flutter_doctor.txt)

Expected: A screen that allows me to select the parameters and values for a new Flutter project
Actual: Whatever was last selected.

The new New Project screen doesn't seem to be accessible from the standard 'New Project' button and I'm not sure why Android Studio has template generators for things like IDEA Plugins, but regardless, I would have anticipated a button that says 'New Flutter Project' to begin creating a Flutter Project and other Project types to have their access, like from the New Project button if that's going to be a focus or aspect of Android Studio going forward.

Android Studio Electric Eel | 2022.1.1 Canary 10
Build #AI-221.6008.13.2211.8963757, built on August 18, 2022
Runtime version: 11.0.15+0-b2043.56-8887301 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 11.6.8
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Registry:
    external.system.auto.import.disabled=true
    ide.text.editor.with.preview.show.floating.toolbar=false

Non-Bundled Plugins:
    Dart (221.6008.17)
    io.flutter (70.0.4)
    Jetbrains TeamCity Plugin (2022.4.108706)

**Comment by exaby73** [comment]
Hello @strangedreamsNY. This issue is related to the IntelliJ plugin for Flutter, therefore, it might be better if it was raised in [flutter-intellij](https://github.com/flutter/flutter-intellij). Closing as this is not an issue with Flutter itself.
