### ISSUE TITLE
[impeller] impellerc crashes when compiling uint uniform

### ISSUE THREAD

**Issue by ds84182** [flutter/flutter#110961]
repro:
```glsl
#version 310 es

layout(location = 0) uniform uint foo;
layout(location = 0) out vec4 fragColor;

void main() {}
```

however changing uint -> int works

cc @zanderso

**Comment by ds84182** [comment]
Actually this happens if a `uint` appears anywhere in a program, including uint constants (suffixed with `u`)

**Comment by ds84182** [comment]
Looks like int and uint aren't really supported in SKSL. Though that shouldn't limit anyone who wants to use them in impeller. Will leave this open since hard crashing is still a bug.

**Comment by zanderso** [comment]
@ds84182 Could you share any logs here please?

**Comment by ds84182** [comment]
@zanderso I don't get any log output from impellerc, most likely because I'm on Windows.

**Comment by zanderso** [comment]
@jonahwilliams was this among the crashes you fixed?

**Comment by jonahwilliams** [comment]
No, this crash is different. on macOS:

```
[ERROR:flutter/fml/backtrace.cc(108)] Caught signal SIGABRT during program
execution.
Frame 0: 0x104158f0c
std::_LIBCPP_ABI_NAMESPACE::__shared_ptr_emplace<>::~__shared_ptr_emplace()
Frame 1: 0x104393dec spirv_cross::join<>()
Frame 2: 0x1043914a8 spirv_cross::CompilerGLSL::variable_decl()
Frame 3: 0x1043925f4 spirv_cross::CompilerGLSL::variable_decl()
Frame 4: 0x1041600b0 impeller::compiler::CompilerSkSL::emit_uniform()
Frame 5: 0x104160bdc impeller::compiler::CompilerSkSL::emit_uniform_resources()
Frame 6: 0x10415f4cc impeller::compiler::CompilerSkSL::emit_resources()
Frame 7: 0x10415edb0 impeller::compiler::CompilerSkSL::compile()
Frame 8: 0x10411c13c impeller::compiler::Compiler::Compiler()
Frame 9: 0x104118fd0 impeller::compiler::Main()
Frame 10: 0x10411a37c main
Frame 11: 0x10550908c start

```

Might just be the SPIRV_CROSS_THROW from the glsl compiler and instead we need to exit earlier. Needs some investigation
