### ISSUE TITLE
Allow customization of LinearProgressIndicator's colors

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#11096]
Request from customer:six

"""
Something like:
  const LinearProgressIndicator.withColors({this.foreground, this.background ....})
would be really nice to have, as currently the colors are always taken from context.

Or maybe it is possible to specify the colors explicitly?
"""

**Comment by tvolkert** [comment]
Internal bug ID: 63379449

**Comment by Hixie** [comment]
We would presumably just provide the colors as constructor arguments like everything else (defaulting to current behaviour), I don't see why it would have to be a new constructor.

**Comment by tvolkert** [comment]
Agreed

**Comment by sroddy** [comment]
I just checked that the LinearProgressIndicator widget already works with backgroundColor and valueColor arguments. It seems to me that they are just not exposed in the constructor and they are not passed to super() call.

```dart
  const LinearProgressIndicator({
    Key key,
    double value,
    Color backgroundColor,
    Animation<Color> valueColor,
  }) : super(key: key, value: value, backgroundColor: backgroundColor, valueColor: valueColor);
```

**Comment by mehmetf** [comment]
Looks like this is fixed.
