### ISSUE TITLE
[in_app_purchase] Android version 5 library deprecated most of the methods but in app purchase using deprecated methods in code

### ISSUE THREAD

**Issue by alihassan143** [flutter/flutter#110986]
https://developer.android.com/google/play/billing/release-notes
billing clients changes most of the methods but flutter plugin using some deprecated skudetails methods replace the classes with new purchase details class in billing flow

**Comment by huycozy** [comment]
Hi @alihassan143 
From what's in your description, it looks like you're requesting for the similar thing with this issue #107370, right?

**Comment by alihassan143** [comment]
yes

**Comment by huycozy** [comment]
@alihassan143 Thanks for your response.
Closing this issue as a duplicate, so please follow up on #107370 for further updates. You can leave there your comment and react an upvote to the original comment will help to raise the issue. Thank you!
