### ISSUE TITLE
[adaptive_scaffold] `NavigationDestination` with icon + label overflows within navigation rail.

### ISSUE THREAD

**Issue by a-wallen** [flutter/flutter#110901]
<img width="224" alt="Screen Shot 2022-09-02 at 11 50 12 PM" src="https://user-images.githubusercontent.com/44445638/188259401-36b13804-4cce-458b-8d9f-bcb80f951504.png">

**Expected results:** The AppBar sizes to the same width as the largest element in the NavigationListView

**Actual results:**  Overflow Error

## Steps to Reproduce

<details>
<summary>Code sample</summary>

1. Clone [flutter/packages](https://github.com/flutter/packages) into the folder of your choice (at the time of writing, `AdaptiveScaffold` has not been released.
2. Add adaptive_scaffold to the flutter project:
```yaml
dependencies
    adaptive_scaffold:
        path: <path_to_the_packages_repo>/packages/adaptive_scaffold/
```
3. Add the following to`main.dart`

```dart
import 'package:flutter/material.dart';
import 'package:adaptive_scaffold/adaptive_scaffold.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: AdaptiveScaffold(
        destinations: [
          NavigationDestination(icon: Icon(Icons.home), label: "ABCDEFGHIJKLMNOP"),
          NavigationDestination(icon: Icon(Icons.home), label: "ABCDEFGHIJKLMNOP")
        ],
      ),
    );
  }
}
```

</details>

To be clear, this wouldn't be a problem if the `label:` property allowed a widget. If that were the case, any user could specify the way that the widget renders whenever there was an overflow error. Right now, the `label:` property is a string, which makes it impossible to account for a long `NavigationDestination.label`

**Comment by aliasgar4558** [comment]
It seems like an issue with "NavigationRail" widget in case of extended view. I will try to add some fix into it.

**Comment by dkwingsmt** [comment]
Here's another reproduction that doesn't rely on the adaptive scaffold package:

<img width="493" alt="image" src="https://github.com/flutter/flutter/assets/1596656/0367e829-5d74-48ca-a256-ecfff3820d7b">

How to test it:
1. Open `examples/api/lib/material/navigation_rail/navigation_rail.1.dart`
https://github.com/flutter/flutter/blob/6fb281fa731503eaa9d08c07001216429e7b6db9/examples/api/lib/material/navigation_rail/navigation_rail.1.dart#L69-L75
3. Change line 73 to a really long label, such as 
```dart
              destinations: const <NavigationRailDestination>[
                NavigationRailDestination(
                  icon: Icon(Icons.favorite_border),
                  selectedIcon: Icon(Icons.favorite),
                  label: Text('LongLongLongLongLongLongLongLongLongLongLongLongLongLongLongLongLongLongLongLongLongLong'),
                ),
```
4. Run it, for example, 
```
flutter run ~/dev/flutter/examples/api/lib/material/navigation_rail/navigation_rail.1.dart -d chrome
```
5. Make the window really small
