### ISSUE TITLE
why don't `init FlutterEngine` use `ensureInitializationCompleteAsync` Api in order to not block the `UiThread` ?

### ISSUE THREAD

**Issue by sailor1861** [flutter/flutter#110904]
I find must new FlutterEngine in UiThread when init FlutterEngine.
And FlutterEngine will call flutterLoader.ensureInitializationComplete(context, dartVmArgs)，
in order to wait all assets prepared, bit this process cost many time;

so, init FlutterEngine will block UiThread；

And， I also find a Api flutterLoader.ensureInitializationCompleteAsync, but has no caller;

my question is:
In order to don't block the UiThread
why don't init FlutterEngine use ensureInitializationCompleteAsync Api?

**Comment by darshankawar** [comment]
Keeping this issue open for further insights from engine team.

/cc @chinmaygarde

**Comment by chinmaygarde** [comment]
If the non-blocking version is suitable for use in the application, the embedder is free to use it.
