### ISSUE TITLE
Android Studio 'Pub Get' needs an 'offline' mode. 

### ISSUE THREAD

**Issue by strangedreamsNY** [flutter/flutter#110945]
Running `Pub Get` from Android Studio doesn't work when you are offline even if you've created the project in offline mode. Running `flutter pub get --offline` from a terminal does get Android Studio to pick up dependencies and references now if the relevant libraries are in pub cache, but this only works in Dolphin and not in previous Chipmunk builds.  

Flutter Plugiun 70.0.4

Android Studio Electric Eel | 2022.1.1 Canary 10
Build #AI-221.6008.13.2211.8963757, built on August 18, 2022
Runtime version: 11.0.15+0-b2043.56-8887301 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 11.6.8
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Registry:
    external.system.auto.import.disabled=true
    ide.text.editor.with.preview.show.floating.toolbar=false

Non-Bundled Plugins:
    Dart (221.6008.17)
    io.flutter (70.0.4)
    Jetbrains TeamCity Plugin (2022.4.108706)

[flutter_doctor.txt](https://github.com/flutter/flutter/files/9485329/flutter_doctor.txt)

**Comment by exaby73** [comment]
Hello @strangedreamsNY. This issue is related to the IntelliJ plugin for Flutter, therefore, it might be better if it was raised in [flutter-intellij](https://github.com/flutter/flutter-intellij). Closing as this is not an issue with Flutter itself.
