### ISSUE TITLE
Failed to setup Skia Gr context

### ISSUE THREAD

**Issue by simusco** [flutter/flutter#11094]
Launching lib\main.dart on Samsung Galaxy S6, 5 1 0, API 22, 1440x2560 in debug mode...
Built build\app/outputs/apk/app-debug.apk (21.7MB).
I/flutter ( 1942): [INFO:gpu_surface_gl.cc(51)] Failed to setup Skia Gr context.
Application finished.

**Comment by eseidelGoogle** [comment]
@simusco is this an emulator?

@chinmaygarde or @brianosman what are the right instructions for how to gather the right GPU information here?

**Comment by brianosman** [comment]
Is this reproducible? That error suggests that just creating the GrContext is failing, which limits how much information you can scrape from within Flutter - typically you would ask the GrContext. We do test Skia on that device - it's got a relatively recent Mali GPU (T7xx).

**Comment by programadorthi** [comment]
Here is happening the same error. I just has created the getting started myapp.

Flutter install the application in my emulator but it freeze in the black screen.

**I am using Windows 10 Pro and Android Emulator Samsung Galaxy Tab API 17.**

Launching lib/main.dart on Android SDK built for x86 in debug mode...
Running 'gradle assembleDebug'...
Built build\app/outputs/apk/app-debug.apk (21.7MB).
Installing build\app/outputs/apk/app.apk...           2.1s
I/flutter ( 3002): [INFO:gpu_surface_gl.cc(51)] Failed to setup Skia Gr context.
Syncing files to device Android SDK built for x86...  1.5s

**In my Nexus 5X API 25 emulator it works very well.**

Launching lib/main.dart on Android SDK built for x86 in debug mode...
Running 'gradle assembleDebug'...                     2.0s
Built build\app/outputs/apk/app-debug.apk (21.7MB).
Installing build\app/outputs/apk/app.apk...           1.6s
I/Choreographer( 4441): Skipped 67 frames!  The application may be doing too much work on its main thread.
D/EGL_emulation( 4441): eglMakeCurrent: 0xa89855a0: ver 2 0 (tinfo 0xa8983e70)
Syncing files to device Android SDK built for x86...  2.0s

**Comment by mzimmerm** [comment]
I am getting the same error in emulator:

Launching lib/main.dart on Android SDK built for x86 in debug mode...
Running 'gradle assembleDebug'...
Built build/app/outputs/apk/app-debug.apk (21.6MB).
I/flutter ( 2243): [INFO:gpu_surface_gl.cc(51)] Failed to setup Skia Gr context.
Syncing files to device Android SDK built for x86...

This is when launching the demo flutter app (counter), using API level 17, hardware emulation. The application shows completely black after this error. When I change to API level 24, the application works

**Comment by eseidelGoogle** [comment]
This is the kind of bug where something like https://github.com/flutter/flutter/issues/11402 might be useful. :)

**Comment by mzimmerm** [comment]
I guess. BTW, I do not mind this issue at all as long as some SDKs work for me in emulation (and some do). Found this googling and wanted to add it does not seem unique for the reporter. Thanks.

**Comment by ljfreelancer88** [comment]
I encountered the same issue in emulator and able to fixed by changing the configuration in AVD. Under **Emulated Perfomance**, set Graphics to **Hardware - GLES 2.0**

**Comment by zarinfam** [comment]
I am using Windows 10 Pro and I have the same problem on Android Emulator API level 17.

**Comment by MartinTello** [comment]
I am using Windows 10 Education and I have the same problem on Android Emulator API level 16.

**Comment by eseidelGoogle** [comment]
`flutter run --enable-software-rendering` should work as a work-around.  CC @mit-mit, @cbracken @chinmaygarde  I thought that we had decided to make Android Emulators default to software rendering? (I can't seem to find the issue tracking that)?

**Comment by MartinTello** [comment]
@eseidelGoogle that work, i just find it in https://github.com/flutter/flutter/issues/9108

**Comment by Argenisx** [comment]
Jajaja I had the same problem  , I created my virtual machine and ran the test drive from this url https://flutter.io/get-started/test-drive/#androidsstudio not worked in android studio , I had write the option --enable-software-rendering and it works!!!. Why not works like in the official documentation? @eseidel

**Comment by chinmaygarde** [comment]
Filed https://github.com/flutter/flutter/issues/15451 to track whether we should flip the defaults on software rendering on emulators.

**Comment by Keshava11** [comment]
For Android Studio or IntelliJ users, this is same as what @eseidelGoogle suggested 

1. **from command line** 
$ <in_project_root>   flutter run --enable-software-rendering

2. **from Run/Edit configurations menu in IDE**
![flutterrun_additional_args](https://user-images.githubusercontent.com/6568707/37343985-10fe811a-26ef-11e8-9a83-66d7836dfcc9.png)

**Comment by aymentoumi** [comment]
For Visual Studio Code users add the following line to _launch.json_ : 
**"args": ["--enable-software-rendering", "-d", "all"]**

**Comment by chinmaygarde** [comment]
@aymentoumi: Thanks for the pointer. Though I don't think "-d all" is related to software rendering.

**Comment by aymentoumi** [comment]
@chinmaygarde "-d all" means _all devices_ and it's optional if you use only one emulator.

**Comment by zabih-alipour** [comment]
Thanks @eseidelGoogle, I have same problem and solved

**Comment by sushil-gh** [comment]
I am a newbie and facing similar problems.  I followed instructions given on https://flutter.io/setup-windows/. I created an android virtual device  with Emulated Performance = select Hardware - GLES 2.0.
Few relevant parameters of emulator are :
Name: Nexus_5X_API_16
CPU/ABI: Google APIs Intel Atom (x86)
Target: google_apis [Google APIs] (API level 16)
hw.accelerometer: yes
hw.device.name: Nexus 5X
image.sysdir.1: system-images\android-16\google_apis\x86\
tag.id: google_apis
hw.cpu.ncore: 2
hw.gpu.enabled: yes

When I run the test app as instructed on the above website, I get the following trace:
Launching lib\main.dart on emulator-5554 in debug mode...
Initializing gradle...
Resolving dependencies...
Running 'gradlew assembleDebug'...
Built build\app\outputs\apk\debug\app-debug.apk (24.8MB).
Installing build\app\outputs\apk\app.apk...
I/FlutterActivityDelegate( 2521): onResume setting current activity to this
E/flutter ( 2521): [ERROR:flutter/shell/gpu/gpu_surface_gl.cc(39)] Failed to setup Skia Gr context.
Syncing files to device emulator-5554...

At this point, the emulator starts but remains blank.

I tried “flutter run --enable-software-rendering” and it seemed to work.  However, with HW rendering, it does not. Any tip on how to make it work?

Thanks in advance.

**Comment by cbracken** [comment]
Closing this for the moment; the remainder should be covered by #15451. We recently updated startup messages for Android emulator runs to help clarify how to switch between software and hardware rendering as well.

**Comment by josvos** [comment]
Just as an update for watchers of this closed issue: see also issue #18601, the problem also/still occurs on physical (older) devices. For more details see my last comment in issue #18601.

**Comment by nvminhtu** [comment]
> For Visual Studio Code users add the following line to _launch.json_ :
> **"args": ["--enable-software-rendering", "-d", "all"]**

or run command line:

`flutter run --enable-software-rendering`

Both of them work for me. Thanks all!

**Comment by garfnadeck** [comment]
> `flutter run --enable-software-rendering` should work as a work-around. CC @mit-mit, @cbracken @chinmaygarde I thought that we had decided to make Android Emulators default to software rendering? (I can't seem to find the issue tracking that)?

Thank you very much my friend :)

**Comment by pengchunlin** [comment]
> For Android Studio or IntelliJ users, this is same as what @eseidelGoogle suggested
> 
> 1. **from command line**
>    $ <in_project_root>   flutter run --enable-software-rendering
> 2. **from Run/Edit configurations menu in IDE**
>    ![flutterrun_additional_args](https://user-images.githubusercontent.com/6568707/37343985-10fe811a-26ef-11e8-9a83-66d7836dfcc9.png)

not work for me

**Comment by cswxzx** [comment]
I have same problem

**Comment by fzyzcjy** [comment]
Hi, I have the problem with a **real machine (not Android simulator)** bought in 2017 (which is not too old). Thus, why my phone do not support hardware rendering? Will this harm performance? Will many phones do not support hardware rendering, so that Flutter apps will crash on them?? Thanks!

**Comment by elmissouri16** [comment]
enable software rendering can be a workaround for debugging but how about release mode ??

**Comment by BREN0-MORAIS** [comment]
> > Para usuários do Visual Studio Code, adicione a seguinte linha ao _launch.json_ : 
> > **"args": ["--enable-software-rendering", "-d", "all"]**
> 
> ou execute a linha de comando:
> 
> `flutter run --enable-software-rendering`
> 
> Ambos trabalham para mim. Obrigado a todos!

Obrigado me Ajudo

**Comment by kidfrom** [comment]
> `flutter run --enable-software-rendering` should work as a work-around. CC @mit-mit, @cbracken @chinmaygarde I thought that we had decided to make Android Emulators default to software rendering? (I can't seem to find the issue tracking that)?

Hi, I need to support API 16. It seems this issue present in API 16 (Google APIs) and API 19 (Google APIs).

Is there recommended way to build the apk with `--enable-software-rendering` with `flutter` command. Thank you.

[Reference to possible solution](https://stackoverflow.com/questions/50127070/flutter-build-apk-with-enable-software-rendering)
