### ISSUE TITLE
BoxShadow dy offset calculation, Windows

### ISSUE THREAD

**Issue by kirill-21** [flutter/flutter#110959]
After updating to **Flutter 3.3.0** there is a 1px border around the app in some of my projects. It does not appear in all apps so i guess it's an issue.
### **Problem description is in the first comment**

After update: (image in right corner)
![image](https://user-images.githubusercontent.com/63228361/188336183-9db5ee44-5114-4d6b-9edf-6843c22fbbe5.png)

Before update(Flutter 3.0.5): (image in right corner)
![image](https://user-images.githubusercontent.com/63228361/188336029-3545e8c6-0971-4ec0-a7b5-17e8613119cf.png)

After update: (image in right corner)
![image](https://user-images.githubusercontent.com/63228361/188335888-7e780932-6af9-4320-86c0-43276915e245.png)

Before update(Flutter 3.0.5): (image in right corner)
![image](https://user-images.githubusercontent.com/63228361/188335910-59f9dda2-42e2-446c-81c5-b243d4bd5938.png)

**Comment by kirill-21** [comment]
This happens because Container's BoxShadow dy offset calculation is broken. Even if move shadow 1px or 9px to the bottom it stays on the same place.

Offset 1px:
![image](https://user-images.githubusercontent.com/63228361/188336540-1ba7b6ed-9aa3-4374-b0c0-637ce907742e.png)

Offset 8px:
![image](https://user-images.githubusercontent.com/63228361/188336561-2c3ee0d1-9352-43ad-ad48-ab88d968ffc3.png)

**Comment by exaby73** [comment]
Hello @kirill-21. I couldn't notice any difference in the images you provided. Could you highlight exactly what I am supposed to be looking at?

Could you also provide a [complete and minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) so that I may verify the issue. Thank you.

**Comment by kirill-21** [comment]
Border:
![image](https://user-images.githubusercontent.com/63228361/188437167-f08463bc-5888-41a9-a2ec-9ee9c6e81117.png)

No border:
![image](https://user-images.githubusercontent.com/63228361/188437296-d2d7cab4-772b-4e68-ba05-81f7897f5033.png)

Images should be zoomed to see the difference. 

Easy way to reproduce the issue: go to win32_windows.cpp in windows folder, then change
```c++
HWND window = CreateWindow(
      window_class, title.c_str(), WS_OVERLAPPEDWINDOW | WS_VISIBLE,
      Scale(origin.x, scale_factor), Scale(origin.y, scale_factor),
      Scale(size.width, scale_factor), Scale(size.height, scale_factor),
      nullptr, nullptr, GetModuleHandle(nullptr), this);
```
to
```c++
HWND window = CreateWindow(
      window_class, title.c_str(), WS_OVERLAPPED,
      Scale(origin.x, scale_factor), Scale(origin.y, scale_factor),
      Scale(size.width, scale_factor), Scale(size.height, scale_factor),
      nullptr, nullptr, GetModuleHandle(nullptr), this);
```
so that default windows drag window disappears.

and this to switch block in Win32Window::MessageHandler:
```c++
```

Add these packages to dependencies: (To remove default 1px border on Windows 11)
```
  win32: ^2.7.0
  ffi: ^2.0.1
```

**Comment by kirill-21** [comment]
> Hello @kirill-21. I couldn't notice any difference in the images you provided. Could you highlight exactly what I am supposed to be looking at?
> 
> Could you also provide a [complete and minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) so that I may verify the issue. Thank you.

Maybe I misidentified the problem and in fact it is related to https://github.com/flutter/flutter/issues/110957, because i use animated opacity in my custom appbar, and therefore app layouts itself 1px lower(from top, bottom, left and right) (randomly on one of the sides) than the actual app form
![image](https://user-images.githubusercontent.com/63228361/188448118-87a922de-423d-46f2-8d14-5b551220b15c.png)

![studio64_3z62wdSTKJ](https://user-images.githubusercontent.com/63228361/188448697-dabb761b-e6c6-46a3-bbfe-449096533472.gif)

**Comment by kirill-21** [comment]
> 

I'm getting the same error since flutter 3.3.0 but it does not affect the app, you can still use it

**Comment by exaby73** [comment]
For me, the logs tell me that app is running, but a window doesn't appear

**Comment by kirill-21** [comment]
> For me, the logs tell me that app is running, but a window doesn't appear

![image](https://user-images.githubusercontent.com/63228361/188478971-7a677cb4-7d36-4fb8-a225-d04d1437d48e.png)
Change this to FLUTTER_RUNNER_WIN32_WINDOW, seems that you have different class name

**Comment by exaby73** [comment]
Okay I was able to run the application, though I could notice a slight 1 pixel border appearing when dragging the window. Unfortunately, I wasn't able to capture it but yes, I can reproduce it on stable. Though, on the master channel, I couldn't notices any border. Could you confirm whether or not this bug reproduces on master?

**Comment by kirill-21** [comment]
> reproduce

I tested another issue on master channel (20 minutes ago) and issue with border did not disappear there

**Comment by exaby73** [comment]
Just to confirm, do you find this issue reproducible on master or not?

**Comment by kirill-21** [comment]
> Just to confirm, do you find this issue reproducible on master or not?

Yes, it's reproducible on all channels

**Comment by exaby73** [comment]
Okay thank you for the information. I can reproduce this issue.

### Reproducible on

- `Stable (3.3.0)`
- `Master (3.4.0-19.0.pre.86)`

### Info

For code sample, please follow steps highlighted here: https://github.com/flutter/flutter/issues/110959#issuecomment-1236940188

### Flutter Doctor

<details><summary><code>flutter doctor -v</code> (Stable)</summary>

```
[✓] Flutter (Channel stable, 3.3.0, on Microsoft Windows [Version 10.0.22000.918], locale en-IN)
    • Flutter version 3.3.0 on channel stable at C:\Users\Nabeel\fvm\versions\stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffccd96b62 (7 days ago), 2022-08-29 17:28:57 -0700
    • Engine revision 5e9e0e0aa8
    • Dart version 2.18.0
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\android-sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2022 17.3.2)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.3.32819.101
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[✓] VS Code (version 1.71.0)
    • VS Code at C:\Users\Nabeel\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.46.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22000.918]
    • Chrome (web)      • chrome  • web-javascript • unknown
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 105.0.1343.27

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

<details><summary><code>flutter doctor -v</code> (Master)</summary>

```
[✓] Flutter (Channel master, 3.4.0-19.0.pre.86, on Microsoft Windows [Version 10.0.22000.918], locale en-IN)
    • Flutter version 3.4.0-19.0.pre.86 on channel master at C:\Users\Nabeel\fvm\versions\master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a04e6b7618 (49 minutes ago), 2022-09-06 02:08:10 -0400
    • Engine revision 623b80157c
    • Dart version 2.19.0 (build 2.19.0-171.0.dev)
    • DevTools version 2.17.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\android-sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2022 17.3.2)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.3.32819.101
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[✓] VS Code (version 1.71.0)
    • VS Code at C:\Users\Nabeel\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.46.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22000.918]
    • Chrome (web)      • chrome  • web-javascript • unknown
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 105.0.1343.27

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by jonahwilliams** [comment]
Cherry pick request for fix is https://github.com/flutter/flutter/issues/111145

**Comment by jonahwilliams** [comment]
We've released a hotfix that restores pixel snapping. It would be great if you could verify that this fixes your application.

**Comment by kirill-21** [comment]
> 

Yes, there is no border anymore

**Comment by jonahwilliams** [comment]
great!
