### ISSUE TITLE
[adaptive_scaffold] asserts that navigation rail items cannot be less than two items

### ISSUE THREAD

**Issue by a-wallen** [flutter/flutter#110902]
The layout procedure responsible for the left navigation bar should resemble the `Drawer` APIs. If we set the number of `NavigationDestination`s on AdaptiveScaffold to some arbitrary number, we must have some comprehensive reason for why we do not allow an empty sidebar or one element in the sidebar.

Give a better error message whenever the rules of the `NavigationDestination` items are less than the number required.

## Steps to Reproduce

<details>
<summary>Code sample</summary>

1. Clone [flutter/packages](https://github.com/flutter/packages) into the folder of your choice (at the time of writing, `AdaptiveScaffold` has not been released.
2. Add adaptive_scaffold to the flutter project:
```yaml
dependencies
    adaptive_scaffold:
        path: <path_to_the_packages_repo>/packages/adaptive_scaffold/
```
3. Add the following to`main.dart`

```dart
import 'package:flutter/material.dart';
import 'package:adaptive_scaffold/adaptive_scaffold.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: AdaptiveScaffold(
        destinations: [
          NavigationDestination(icon: Icon(Icons.home), label: "ABCDEFGHIJKLMNOP")
        ],
      ),
    );
  }
}
```

</details>

**Comment by aliasgar4558** [comment]
Added assertion, we can mark this issue as Closed.

**Comment by aliasgar4558** [comment]
@a-wallen -  Can you please mark this bug as closed?
