### ISSUE TITLE
CupertinoButton.filled not can 0 padding vertical

### ISSUE THREAD

**Issue by Mryuksel101** [flutter/flutter#110989]
CupertinoButton.filled cannot fill 0 vertically but 0 padding horizontal works

**Comment by exaby73** [comment]
Hello @Mryuksel101. Thank you for filing this issue. Can you please provide the following information?

- A [complete and minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).
- The output of `flutter doctor -v`
