### ISSUE TITLE
Problem facing while using date range picker.

### ISSUE THREAD

**Issue by akashlilhare** [flutter/flutter#110958]
I am using flutter 3.3.0, following is the doctor summary.

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.3.0, on Microsoft Windows [Version 10.0.22000.856], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc3)
[√] Chrome - develop for the web
[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2021.2)
[!] Android Studio
    X android-studio-dir = C:\Program Files\Android\Android Studio
    X Unable to determine bundled Java version.
[√] IntelliJ IDEA Community Edition (version 2020.2)
[√] VS Code (version 1.70.2)
[√] Connected device (4 available)
[√] HTTP Host Availability
```

------------------------------------------------------------------------------------------------------------
I try to use official date range picker, but text of top bar is not visible in light mode. In dark mode It is running fine.

`         DateTimeRange? dateSelected = await 
               showDateRangePicker(
               context: context,
               firstDate: DateTime(2019, 01, 01),
               lastDate: DateTime.now());
`

![range_picker](https://user-images.githubusercontent.com/39927872/188336153-2af368e5-2862-4fdb-b4a3-eb606b658f38.jpeg)

**Comment by 92Andy** [comment]
Hi @akashlilhare, it looks like simply the font is white for the `helpText`. Did you try to set the `onPrimary` property in `ColorScheme` to black?

The call `showDateRangePicker(...)` uses internally by default the `_CalenderRangePickerDiaglog` widget, which can be found in `lib/src/material/date_picker.dart` . In this widget for example the following is defined: 

`final Color headerForeground = colors.brightness == Brightness.light
      ? colors.onPrimary
      : colors.onSurface;`
      
By default, `colors.onPrimary` is set to `Color(0xffffff)`/white and `colors.onSurface` is set to `Color(0xff000000)`/black.
Meaning, in the app, if the Brightness property in `ColorScheme` is set to `Brightness.light` and the `onPrimary` property is set to white, then the text (helpText) will be displayed in white.

I hope I can help you with this 😉

**Comment by exaby73** [comment]
Hello @akashlilhare. Please follow the debugging steps highlighted by @92Andy in https://github.com/flutter/flutter/issues/110958#issuecomment-1236820631. Thanks @92Andy for the insights. If you are still reproducing this issue, an you please provide the following information:

- A [complete and minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).
- The output of `flutter doctor -v`
