### ISSUE TITLE
Unable to Read an Exif header If the Image is captured through Image steam.

### ISSUE THREAD

**Issue by shantaramk** [flutter/flutter#110971]
## Use case
We want to read and write in the exif header from the captured image through Image steam.

### **Input sample taken from Image Stream:**
![sample](https://user-images.githubusercontent.com/7990309/188317564-9407bd54-e59e-495b-a62d-1e48d11253d9.jpg)

### **Exif Info:**  
<img width="910" alt="Screenshot 2022-09-04 at 7 41 17 PM" src="https://user-images.githubusercontent.com/7990309/188317903-9f1c9ea4-8273-403b-a820-c147c31a1e5c.png">

**Note**: 
 Under **More Info** Section, **Exif** Tab is missing 

### **Output:**  

While reading the EXIF data for the given Image, I got blank data

`image.exif : {}`

## Proposal

There should be an exif header if the image is captured from Image Steam.

**Comment by exaby73** [comment]
Hello @shantaramk. Thank you for filing this issue. Can you please provide the following information?

- A [complete and minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).
- The output of `flutter doctor -v`
