### ISSUE TITLE
dead CSS properties

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#111]
<a href="https://github.com/Hixie"><img src="https://avatars.githubusercontent.com/u/551196?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Hixie](https://github.com/Hixie)**
_Monday Jul 20, 2015 at 20:33 GMT_
_Originally opened as https://github.com/flutter/engine/issues/155_

----

_From @Hixie on February 19, 2015 18:19_

Looking through CSSProperties.in I noticed the following properties which should probably be dead already and might be safe to remove:

- `caption-side`
- `empty-cells`
- `orphans`
- `widows`
- `page-break-before`
- `page-break-after`
- `page-break-inside`
- `table-layout`
- `speak` (?)

_Copied from original issue: domokit/mojo#50_

**Comment by abarth** [comment]
We no longer have any CSS properties.
