### ISSUE TITLE
Emojis wont render when using non-normal font weights

### ISSUE THREAD

**Issue by lukef** [flutter/flutter#11108]
If you have a `Text` widget and you're using a `TextStyle` which specifies a `fontWeight` that is `!= 400` then any emojis in the text string will not be rendered.

**Comment by eseidelGoogle** [comment]
Ouch.  @cbracken or @chinmaygarde may know (both worked on our emoji support iirc).  Do you know if this is specific to iOS or Android?

**Comment by jason-simmons** [comment]
Reproduced this on Android.  Looking into it now.

**Comment by jason-simmons** [comment]
This is happening at the Skia level.

I traced it to SkScalerContext::getMetrics yielding an error for the emoji glyph when using a bold weight.  With the weight applied, getMetrics flows through the fGenerateImageFromPath -> devPath.getBounds().roundOut() path, and getBounds returns an empty rectangle.

We'll need support from the Skia team.  Should we be going down this path when rendering a color bitmap glyph?

**Comment by bungeman** [comment]
https://bugs.chromium.org/p/skia/issues/detail?id=4904

**Comment by eseidelGoogle** [comment]
Confirming: @collinjackson @lukef is this blocking development?  I presume the workaround is to just not use a bold font?

**Comment by lukef** [comment]
Not blocking

**Comment by najeira** [comment]
Emojis with FontWeight.w500 works in my app. but with FontWeight.w600 does not work.

**Comment by chinmaygarde** [comment]
Update: This has been fixed in Skia. I need to confirm that it has been rolled into the engine and fixed.

**Comment by najeira** [comment]
In alpha 0.0.19, I confirmed that emojis are displayed with FontWeight.bold in both Android emu and iOS sim.

**Comment by cbracken** [comment]
@najeira thanks for confirming! Please re-open if you see issues again.

**Comment by owenmech** [comment]
I am experiencing this issue. They will not display above FontWeight.w500
