### ISSUE TITLE
Engine -> Framework roll blocked due to LUCI results not making their way to github

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#111043]
https://github.com/flutter/flutter/pull/111026

has three jobs pending, but clicking through to LUCI shows that they finished 8 hours ago.

I am going to land the roll manually, but filing this in case follow-up investigation is needed.

cc @GaryQian

**Comment by nehalvpatel** [comment]
It looks like these two subsequent PRs got autosubmitted correctly:
- https://github.com/flutter/flutter/pull/111044
- https://github.com/flutter/flutter/pull/111046

**Comment by nehalvpatel** [comment]
![image](https://user-images.githubusercontent.com/159021/188749945-886e6cfe-2b80-47a1-8d33-0d0e19b5a6d0.png)

GitHub's services have been intermittent today and I'm trying to access some logs to confirm if that's the culprit here.

**Comment by nehalvpatel** [comment]
I found nothing conclusive, but this seems to be a transient issue.
