### ISSUE TITLE
Request for video stream

### ISSUE THREAD

**Issue by emanuelzallikodelabs** [flutter/flutter#111089]
If you can add any solution for the video stream I can not load the video without fixed minutes

**Comment by danagbemava-nc** [comment]
Hi @emanuelzallikodelabs, I believe this should be already supported. Although there is an issue open that seeks to improve the behaviour being tracked in https://github.com/flutter/flutter/issues/107882. 

Can you provide a minimal sample that captures the issues you're experiencing and also share the issues you're experiencing? 

Please also provide the version of `video_player` you're using along with the output of `flutter doctor -v`. 

Thank you
