### ISSUE TITLE
Rolling engine produces analyzer warnings in IntelliJ

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#11100]
Rolling the engine to https://github.com/flutter/engine/commit/eb467a8b852e607dbf5dc0cab662e89b1495c516 causes various analyzer errors when opening packages/flutter in IntelliJ (see below). Two commits before (https://github.com/flutter/engine/commit/2062ca14ec55934ac27b6a1e69031c44daae1e54) these errors are not present. The commit in between (https://github.com/flutter/engine/commit/66fbebaca3a7bae3fe957c4c829009330a412082) is probably the culprit, but not all artifacts exist for it in cloud storage. Therefore, I wasn't able to confirm that that's actually the culprit.

There are 117 analyzer errors. None of them seem correct. I am including the first few below:
```
error: The switch case expression type 'AnimationStatus' can't override the == operator. (case_expression_type_implements_equals at [flutter] lib/src/animation/animation.dart:104)
error: The switch case expression type 'SemanticsAction' can't override the == operator. (case_expression_type_implements_equals at [flutter] lib/src/cupertino/slider.dart:338)
error: The argument type 'ValueChanged(bool) → void' can't be assigned to the parameter type 'Object'. (argument_type_not_assignable at [flutter] lib/src/cupertino/switch.dart:248)
error: The switch case expression type 'AnimationStatus' can't override the == operator. (case_expression_type_implements_equals at [flutter] lib/src/cupertino/switch.dart:271)
error: The argument type 'DebugPrintCallback(String, {wrapWidth: int}) → void' can't be assigned to the parameter type 'Object'. (argument_type_not_assignable at [flutter] lib/src/foundation/debug.dart:24)
```

IntelliJ also complains that the Analyzer crashed:

Analyzer Feedback from IntelliJ

# Version information

- `IDEA IC-171.4694.70`
- `1.25.0-dev.4.0`
- `IC-171.4694.70, JRE 1.8.0_112-release-736-b21x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.12.5 unknown, screens 1920x1200`

# Exception

Please append the contents of:
file:///private/var/folders/t2/r2h8ytq53_x45hn80bhpb0ww0044f6/T/report2.txt

```
Dart analysis server, SDK version 1.25.0-dev.4.0, server version 1.18.1, error: Analysis failed: /Users/goderbauer/dev/flutter/packages/flutter/lib/src/animation/animations.dart context: exception_20170706_165647_825
NoSuchMethodError: The getter 'superclass' was called on null.
Receiver: null
Tried calling: superclass
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:43)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      _OverrideChecker._extendsErrorLocation (package:analyzer/src/task/strong/checker.dart:1599)
#3      _OverrideChecker._checkInterfacesOverrides (package:analyzer/src/task/strong/checker.dart:1439)
#4      _OverrideChecker._checkInterfacesOverrides (package:analyzer/src/task/strong/checker.dart:1442)
#5      _OverrideChecker._checkAllInterfaceOverrides (package:analyzer/src/task/strong/checker.dart:1286)
#6      _OverrideChecker.check (package:analyzer/src/task/strong/checker.dart:1251)
#7      CodeChecker.visitClassDeclaration (package:analyzer/src/task/strong/checker.dart:295)
#8      ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1906)
#9      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7990)
#10     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2502)
#11     CodeChecker.visitCompilationUnit (package:analyzer/src/task/strong/checker.dart:314)
#12     LibraryAnalyzer._computeVerifyErrors (package:analyzer/src/dart/analysis/library_analyzer.dart:277)
```

/cc @rmacnak-google as author of the commits in question
/cc @devoncarew

**Comment by goderbauer** [comment]
I also filed the analyzer crash separately: https://github.com/dart-lang/sdk/issues/30097

**Comment by goderbauer** [comment]
`flutter analyze --flutter-repo --watch` exposes the same errors.
`flutter analyze --flutter-repo` runs without issues.

**Comment by devoncarew** [comment]
> flutter analyze --flutter-repo --watch exposes the same errors.

This command uses the analysis server to generate errors -

> flutter analyze --flutter-repo runs without issues.

And this command uses the dartanalyzer cli tool.

**Comment by goderbauer** [comment]
To make sure that this is not just a problem with my local system, I created a PR that rolls the engine. Travis is as unhappy as my system: https://github.com/flutter/flutter/pull/11106.

**Comment by goderbauer** [comment]
I did some bisecting. The breakage starts with https://github.com/dart-lang/sdk/commit/62bc61b367b14bfe3a265eaddcce0574e0059985.

@lrhn, @brianwilkerson, @floitsch: Anything we need to do in Flutter-land to adopt to that change?

**Comment by goderbauer** [comment]
Change in question has been reverted: https://codereview.chromium.org/2968413002. I verified that Flutter is working again as expected now.
