### ISSUE TITLE
[adaptive_scaffold]: `appBar` parameter takes `AppBar?` instead of `PreferredSize?`

### ISSUE THREAD

**Issue by a-wallen** [flutter/flutter#111008]
`appBar` parameter takes `AppBar?` instead of `PreferredSize?`. When developers migrate from Scaffold to AdaptiveScaffold, it it won't be as seamless as it could be since these two apis don't match.

**Comment by bernaferrari** [comment]
I don't know what adaptive scaffold is, but I think it could take just a Widget. PreferableSize is too much trouble and no other widget implements it. I think it should be relaxed.

**Comment by a-wallen** [comment]
@bernaferrari https://github.com/flutter/packages/tree/main/packages/adaptive_scaffold

**Comment by nilsreichardt** [comment]
I opened a PR for this ticket: https://github.com/flutter/packages/pull/2617 👍
