### ISSUE TITLE
Engine tree closed on timing out bot update step

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#111039]
https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20Engine%20Drone/99875/overview

From https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20Android%20AOT%20Engine/17952/overview

**Comment by nehalvpatel** [comment]
This new build looks like it finished properly: https://ci.chromium.org/p/flutter/builders/prod/Linux%20Android%20AOT%20Engine/17955

Still monitoring.
