### ISSUE TITLE
Invalid kernel binary: Indicated size is invalid.

### ISSUE THREAD

**Issue by thiskiller** [flutter/flutter#111078]
when run my app，it run success, but I get a error
my flutter version is 2.5.0

../../runtime/vm/kernel_loader.cc: 349: error: Invalid kernel binary: Indicated size is invalid.
version=2.14.0 (stable) (Mon Sep 6 13:47:59 2021 +0200) on "macos_x64"
pid=76090, thread=6915, isolate_group=main(0x7f7ee4045600), isolate=main(0x7f7ee400ca00)
isolate_instructions=10b11eac0, vm_instructions=10b11eac0
  pc 0x000000010b386b94 fp 0x000070000c0eb4f0 dart::Profiler::DumpStackTrace(void*)+0x64
  pc 0x000000010b11ec94 fp 0x000070000c0eb5d0 dart::Assert::Fail(char const*, ...)+0x84
  pc 0x000000010b2d3a91 fp 0x000070000c0eb620 dart::kernel::KernelLoader::index_programs(dart::kernel::Reader*, dart::GrowableArray<long>*)+0x131
  pc 0x000000010b2d2d9e fp 0x000070000c0ebb30 dart::kernel::KernelLoader::LoadEntireProgram(dart::kernel::Program*, bool)+0x12e
  pc 0x000000010b878ad7 fp 0x000070000c0ebc30 Dart_LoadScriptFromKernel+0x247
  pc 0x000000010b0fad6b fp 0x000070000c0ebcc0 main+0x3db
  pc 0x000000010b0f936a fp 0x000070000c0ebd90 dart::bin::RunMainIsolate(char const*, char const*, dart::bin::CommandLineOptions*)+0x79a
  pc 0x000000010b0f9dd4 fp 0x000070000c0ebe40 dart::bin::main(int, char**)+0x834
  pc 0x000000010b235b3e fp 0x000070000c0ebeb0 dart::BootstrapNatives::DN_TransferableTypedData_materialize(dart::Thread*, dart::Zone*, dart::NativeArguments*)+0x5ce
  pc 0x000000010b411618 fp 0x000070000c0ebf30 dart::ThreadPool::WorkerLoop(dart::ThreadPool::Worker*)+0x148
  pc 0x000000010b411a7d fp 0x000070000c0ebf60 dart::ThreadPool::Worker::Main(unsigned long)+0x5d
  pc 0x000000010b38155f fp 0x000070000c0ebfb0 dart::OSThread::GetMaxStackSize()+0xaf
  pc 0x00007fff6d066109 fp 0x000070000c0ebfd0 _pthread_start+0x94
 pc 0x00007fff6d061b8b fp 0x000070000c0ebff0 thread_start+0xf
-- End of DumpStackTrace

Fllutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, 2.5.0, on Mac OS X 10.15.7 19H1922 darwin-x64, locale zh-Hans-CN)
[!] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[!] Xcode - develop for iOS and macOS
    ! CocoaPods 1.7.5 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] Android Studio (version 4.1)
[✓] Android Studio (version 2021.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2020.2.3)
[✓] VS Code (version 1.70.0)
[✓] VS Code (version 1.55.0)
[✓] VS Code (version 1.52.0)
[✓] VS Code (version 1.52.0)
[✓] Connected device (2 available)

please help me，thanks

**Comment by exaby73** [comment]
Hello @thiskiller. Thank you for filing this issue. Could you upgrade to the latest stable SDK for Flutter (`3.3.0`) and confirm if this error still persists. If it does, please provide a [complete and minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) so that I may verify the issue. Thank you.
