### ISSUE TITLE
Flutter 3.3 , web on release mode throws dart.js exception and doesn't initiate

### ISSUE THREAD

**Issue by TMSantos** [flutter/flutter#111022]
![Screenshot 2022-09-06 at 10 52 04](https://user-images.githubusercontent.com/5798822/188604869-55082248-4266-41ef-a502-b4a31b783e94.png)

Running in localhost works.
Running in --release mode doesn't work.

Flutter 3.3, dart 2.8.0

**Comment by TMSantos** [comment]
It seems to happen with Flutter 3.0.5 as well

--debug works
--profile doesn't work
--release doesn't work

**Comment by TMSantos** [comment]
flutter doctor -v
[✓] Flutter (Channel stable, 3.3.0, on macOS 12.5.1 21G83 darwin-arm, locale en-PT)
    • Flutter version 3.3.0 on channel stable at /Users/tiagosantos/dev_tools/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffccd96b62 (7 days ago), 2022-08-29 17:28:57 -0700
    • Engine revision 5e9e0e0aa8
    • Dart version 2.18.0
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/tiagosantos/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = /Users/tiagosantos/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/tiagosantos/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13C90
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 63.2.4
    • Dart plugin version 213.5744.122

[✓] VS Code (version 1.70.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.5.1 21G83 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 105.0.5195.52

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Comment by danagbemava-nc** [comment]
Hi @TMSantos, please provide a complete minimal reproducible code sample along with steps to reproduce so that we can investigate this. 

Thank you

**Comment by TMSantos** [comment]
hi @danagbemava-nc , after some investigation, I concluded that the error comes from https://pub.dev/packages/keycloak_flutter package.

Not related to flutter 3.3
