### ISSUE TITLE
Remove Icon from ExpansionPanel if we want.

### ISSUE THREAD

**Issue by ramirezsebas** [flutter/flutter#111096]
## Use case

The use case is related to the usage of the expansion panel.
I am using a drawer with an expansion panel list and expansion panel. The reason I am using ExpansionPanelList and ExpansionPanel is that it gives me the ability to close the other expansion panel when selecting one. I think using ExpansionTile seems much harder to achieve that functionality.

What I want to achieve is to delete the icon on the far right. 
![Captura de Pantalla 2022-09-07 a la(s) 11 26 13](https://user-images.githubusercontent.com/61977214/188917533-f3360c6f-ca1a-45a5-af60-3cf0f41e2b9d.png)

My first workaround was wrapping the ExpansionPanelList with a theme widget and changing the disabledColor to transparent which works but since the icon is still there, it doesn't let me use the whole space.
 
![Captura de Pantalla 2022-09-07 a la(s) 11 27 30](https://user-images.githubusercontent.com/61977214/188917792-fc62221c-725a-4771-ab7c-9b2608015c4d.png)

## Proposal

It would be nice if we could delete the icon if we want by passing an attribute or a named constructor.

What I was thinking is that we can first create a new attribute to the ExpansionPanel class that indicates if you want to have the icon.

```dart
/// Inidicates whether an expansion panel will have an icon.
/// Only used when creating an expansion panel with [ExpansionPanel.withNoIcon].
final bool? hasIcon;
```
Then we initialize hasIcon to true in the constructor of ExpansionPanel, so we don't affect the original functionality.

```dart
/// Creates an expansion panel to be used as a child for [ExpansionPanelList].
  /// See [ExpansionPanelList] for an example on how to use this widget.
  ///
  /// The [headerBuilder], [body], and [isExpanded] arguments must not be null.
  ExpansionPanel({
    required this.headerBuilder,
    required this.body,
    this.isExpanded = false,
    this.canTapOnHeader = false,
    this.backgroundColor,
  })  : this.hasIcon = true,
        assert(headerBuilder != null),
        assert(body != null),
        assert(isExpanded != null),
        assert(canTapOnHeader != null);
```

After that, we create a named constructor that will initialize hasIcon to false.
So whenever we want to delete the icon, we invoke the named constructor. 
What I have noticed is that if canTapOnHeader = false then there will be no way to expand the panel, so in the named constructor we would initialize it to true.
```dart
  /// Creates an expansion panel to be used as a child for [ExpansionPanelList].
  /// The expansion panel does not render an icon.
  /// See [ExpansionPanelList] for an example on how to use this widget.
  ///
  /// The [headerBuilder], [body], and [isExpanded] arguments must not be null.
  ExpansionPanel.withNoIcon({
    required this.headerBuilder,
    required this.body,
    this.isExpanded = false,
    this.backgroundColor,
  })  : this.canTapOnHeader = true,
        this.hasIcon = true,
        assert(headerBuilder != null),
        assert(body != null),
        assert(isExpanded != null);
```

So, since we have the new attribute hasIcon we can use it to add the icon to the header if we want, which is created on line 413 in expansion_panel.dart.
```dart
 Widget header = Row(
        children: <Widget>[
          Expanded(
            child: AnimatedContainer(
              duration: widget.animationDuration,
              curve: Curves.fastOutSlowIn,
              margin: _isChildExpanded(index)
                  ? widget.expandedHeaderPadding
                  : EdgeInsets.zero,
              child: ConstrainedBox(
                constraints: const BoxConstraints(
                    minHeight: _kPanelHeaderCollapsedHeight),
                child: headerWidget,
              ),
            ),
          ),
         //This is the condition that would inidicate if we add the icon to the header
          if (child.hasIcon != null && child.hasIcon!) expandIconContainer,
        ],
      );
```

Then I would use it in the children of the ExpansionPanelList
```dart
_navItems.map(
            (e) {
              return ExpansionPanel.withNoIcon(
                headerBuilder: (BuildContext context, bool isExpanded) {
                  return Column(
                    crossAxisAlignment: CrossAxisAlignment.center,
                    children: [
                      DrawerListTile(
                        label: e.label,
                        leadingIcon: e.leadingIcon,
                      ),
                      CustomDivider()
                    ],
                  );
                },
                isExpanded: e.isExpanded,
                body: Column(
                  children: e.children
                      .map(
                        (e) => DrawerListTile(
                          label: e.label,
                          onPress: e.onPress,
                        ),
                      )
                      .toList(),
                ),
              );
            },
          ).toList(),
```

![Captura de Pantalla 2022-09-07 a la(s) 11 23 33](https://user-images.githubusercontent.com/61977214/188916920-8b0fd40a-57fc-44d5-b9a9-c97535f7893e.png)

## Conclusion
So that would be my feature request, it worked in my case, it would be nice to have some feedbacks to know if the proposed solution is good, bad or can be improved. Thanks!

**Comment by huycozy** [comment]
Hi @ramirezsebas, thanks for filing a detailed issue. 
But I see there's an open issue addressing the case you described #108973
Closing this issue as a duplicate, so please follow up on it for further updates. You can leave there your comment and react an upvote to the original comment will help to raise the issue. Thank you!

**Comment by masus04** [comment]
@ramirezsebas Would you consider replacing the boolean `hasIcon` flag with an `Icon` that defaults to the current Icon and if set is replaced by the passed icon? An null `Icon` could be passed in order to ignore it.

**Comment by ramirezsebas** [comment]
@masus04 Yeah! That seems like a better solution! There is another issue that proposes that idea to make the ExpansionPanel more customizable. https://github.com/flutter/flutter/issues/108973.
