### ISSUE TITLE
[SelectionArea] with custom actions and actions widget overlay builder

### ISSUE THREAD

**Issue by phamconganh** [flutter/flutter#111001]
## Use case
When select text and has feature translated as google translate extension on browser

## Proposal
`SelectionArea` should have params `actions`, and actions widget `builder` with `position` and `direction`

**Comment by danagbemava-nc** [comment]
Hi @phamconganh, I'm not sure I fully understand what you're requesting. Can you provide a bit more information to make this clear?

**Comment by phamconganh** [comment]
@danagbemava-nc, in the latest release, Flutter has a `SelectionArea` to get selectable widgets. My requirement is the case where the user selects the `text` then the app shows the pop-ups (e.g. show an icon `button` for the `submitted` data for `translation` as some extension `like` `google translate` on chrome). So `SelectionArea` should have parameters for `custom actions` and not just `copy` and `select all` as it is now, and should have a `builder` with position and orientation popup overlay to show the developer's custom widget on selection.

**Comment by danagbemava-nc** [comment]
Thanks for the clarification.

**Comment by goderbauer** [comment]
@chunhtai

**Comment by chunhtai** [comment]
This looks like can be solved by https://github.com/flutter/flutter/pull/107193/files#diff-24359f8e68613891e848c22ce4f0ac32f7da39dfafd1b7d377fdfac5429e5d36

See the example selectable region toolbar example in the pr.
@phamconganh Can you double check if that can solve your use case?

**Comment by Renzo-Olivares** [comment]
Hi @phamconganh, does the `contextMenuBuilder` parameter in `SelectionArea` fit your needs or is this issue related to something else?

**Comment by phamconganh** [comment]
Hi @Renzo-Olivares, problem solved. So I will close this issue.
