### ISSUE TITLE
Cannot access logs from LUCI runs

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#111048]
e.g. https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_ios%20flutter_view_ios__start_up/5783/overview

I can't access https://storage.googleapis.com/flutter_logs/flutter/a04e6b7618700f7b1cadee23f82ef11e693ef44c/flutter_view_ios__start_up/988a44ed-d3f7-4762-983e-5ad9a03c4639/b4873f14ffb248dfcb00c8cb7fdd4cdcff87f1f0.log

/cc @godofredoc

**Comment by keyonghan** [comment]
Are you able to view: [https://storage.cloud.google.com/flutter_logs/flutter/a04e6b7618700f7b1cadee23f82ef11e693ef44c/flutter_view_ios__start_up/988a44ed-d3f7-4762-983e-5ad9a03c4639/b4873f14ffb248dfcb00c8cb7fdd4cdcff87f1f0.log](https://storage.cloud.google.com/flutter_logs/flutter/a04e6b7618700f7b1cadee23f82ef11e693ef44c/flutter_view_ios__start_up/988a44ed-d3f7-4762-983e-5ad9a03c4639/b4873f14ffb248dfcb00c8cb7fdd4cdcff87f1f0.log?_ga=2.65453102.-1078460685.1662088473)

**Comment by keyonghan** [comment]
The above link is for authenticated access.

Seems the bucket was switched to `Not public`, which makes it not accessible via the public endpoint: https://storage.googleapis.com

**Comment by dnfield** [comment]
The authenticated link only works if I'm logged into my corp google account, which doesn't seem like the right ACL for this - we want people to be able to read these logs without working for Google.

**Comment by dnfield** [comment]
(I also got the unauthenticated link from the LUCI build page, so if we really need people to log into view logs then we need to update luci - but again I'm hoping these can just be moved back to public and am assuming this was part of the bucket rename).

**Comment by godofredoc** [comment]
Yes, this was because when we moved the bucket we didn't move it to public. Let me fix that.

**Comment by godofredoc** [comment]
waiting on approval for an exemption to make the bucket public.

**Comment by godofredoc** [comment]
The changes to allow public access to the bucket haven't been approved yet.

**Comment by Hixie** [comment]
latest update: Google folks managing this on the backend have asked for a potential improvement that might help with security.

**Comment by godofredoc** [comment]
The bucket is now public again. @dnfield can you please take a look to see if this now working as intended?

**Comment by dnfield** [comment]
I am able to access the bucket, thanks!
