### ISSUE TITLE
I'm having trouble connecting Visual Studio Code to my phone

### ISSUE THREAD

**Issue by rabee-abu-michael** [flutter/flutter#111049]
Hello my friends, I am having trouble connecting the phone in Visual Studio Code, the connection was successful, but when I click run, I get an error
I tried : flutter cleane | flutter pub get | flutter upgrade

ERROR :
 
Launching lib\main.dart on SM A035F in debug mode...
lib\main.dart:1

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:packageDebug'.
> A failure occurred while executing com.android.build.gradle.tasks.PackageAndroidArtifact$IncrementalSplitterRunnable
   > com.android.ide.common.signing.KeytoolException: Failed to read key AndroidDebugKey from store "C:\Users\michael\.android\debug.keystore": Integrity check failed: java.security.NoSuchAlgorithmException: Algorithm HmacPBESHA256 not available

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 16m 16s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm).
![Screenshot 2022-09-01 190702](https://user-images.githubusercontent.com/100477396/188744309-e7d31b26-d568-4471-a28d-ba11e88b645f.png)

**Comment by huycozy** [comment]
@rabee-abu-michael 
Your question is best suited for support channels like StackOverflow, so please ask the same there for solutions if any. Additionally, you may check if this [StackOverflow answer ](https://stackoverflow.com/questions/67631927/error-building-aab-flutter-android-integrity-check-failed-java-security-n) helps resolve the issue.

Closing from here as this isn't a framework issue.
