### ISSUE TITLE
[in_app_purchase][android]: Playstore upload fails with "We've detected this app uses an unsupported version of Play billing. Please upgrade to Billing Library version 4 or newer to publish this app."

### ISSUE THREAD

**Issue by pshukla0506** [flutter/flutter#111081]
## Use case
I am using the [In-app purchase](https://pub.dev/packages/in_app_purchase) library with the latest version of the library **"in_app_purchase: ^3.0.7"** but when I am trying to upload a new bundle on the Play store at that time, It throws an error as below.
**"We've detected this app uses an unsupported version of Play billing. Please upgrade to Billing Library version 4 or newer to publish this app."**

## Proposal
![Screenshot from 2022-09-07 15-27-57](https://user-images.githubusercontent.com/113022428/188850527-b491942f-5c48-4027-9779-194cc85203fc.png)

### **Play store console:**
![Screenshot from 2022-09-07 15-29-02](https://user-images.githubusercontent.com/113022428/188850578-68d4dac2-1bd2-4534-93ad-f891ebdc7572.png)

Can anyone please help me to resolve this quickly?
Your quick response is highly appreciated
**Thanks in Advance!**

**Comment by danagbemava-nc** [comment]
Hi @pshukla0506, can you share the version of `in_app_purchase_android` you're using? (You can find this in your pubspec.lock)

Please also share your `AndroidManifest.xml` and if possible, what your merged manifest looks like. You can see this by opening the `AndroidManifest.xml` file in `Android Studio` and clicking on `merged manifest`. 

Please also provide the output of `flutter doctor -v`. 

Thank you

**Comment by pshukla0506** [comment]
> Hi @pshukla0506, can you share the version of `in_app_purchase_android` you're using? (You can find this in your pubspec.lock)
> 
> Please also share your `AndroidManifest.xml` and if possible, what your merged manifest looks like. You can see this by opening the `AndroidManifest.xml` file in `Android Studio` and clicking on `merged manifest`.
> 
> Please also provide the output of `flutter doctor -v`.
> 
> Thank you


Hi @danagbemava-nc 
Version information:

**Comment by pshukla0506** [comment]
> Hi @pshukla0506, can you share the version of `in_app_purchase_android` you're using? (You can find this in your pubspec.lock)
> 
> Please also share your `AndroidManifest.xml` and if possible, what your merged manifest looks like. You can see this by opening the `AndroidManifest.xml` file in `Android Studio` and clicking on `merged manifest`.
> 
> Please also provide the output of `flutter doctor -v`.
> 
> Thank you

Hi @danagbemava-nc 
Please find the required details.

### Version information:
```
in_app_purchase_android:
    dependency: transitive
    description:
      name: in_app_purchase_android
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.2.2+6"
```
### AndroidManifest.xml:

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="seem.hk">

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />

    <queries>
        <intent>
            <action android:name="android.intent.action.VIEW" />
            <data android:scheme="https" />
        </intent>
        <intent>
            <action android:name="android.intent.action.DIAL" />
            <data android:scheme="tel" />
        </intent>
        <intent>
            <action android:name="android.intent.action.SENDTO" />
            <data android:scheme="smsto" />
        </intent>
    </queries>

    <application
        android:name="${applicationName}"
        android:icon="@mipmap/ic_launcher"
        android:label="Seem">
        <activity
            android:name=".MainActivity"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:exported="true"
            android:hardwareAccelerated="true"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:windowSoftInputMode="adjustResize">
            <!-- Specifies an Android theme to apply to this Activity as soon as
                 the Android process has started. This theme is visible to the user
                 while the Flutter UI initializes. After that, this theme continues
                 to determine the Window background behind the Flutter UI. -->
            <meta-data
                android:name="io.flutter.embedding.android.NormalTheme"
                android:resource="@style/NormalTheme" />
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
        <!-- Don't delete the meta-data below.
             This is used by the Flutter tool to generate GeneratedPluginRegistrant.java -->
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />

        <meta-data
            android:name="com.google.firebase.messaging.default_notification_icon"
            android:resource="@drawable/ic_launcher" />

       <!-- <meta-data
            android:name="com.google.firebase.messaging.default_notification_color"
            android:resource="@color/colorPrimary" />
-->
        <meta-data
            android:name="com.google.firebase.messaging.default_notification_channel_id"
            android:value="seem" />
        <!--Live-->
        <!--<meta-data
            android:name="com.google.android.gms.ads.APPLICATION_ID"
            android:value="ca-app-pub-8655226367611360~6686542015" />-->
        <!--Test-->
        <meta-data
            android:name="com.google.android.gms.ads.APPLICATION_ID"
            android:value="ca-app-pub-2775167923660951~8963955336" />
    </application>
</manifest>
```

**Comment by danagbemava-nc** [comment]
Hi @pshukla0506, kindly run `flutter pub upgrade` to upgrade your `in_app_purchase_android`. The latest version is `0.2.3+3` and the in_app_purchase_android plugin was updated to play billing 5 in `0.2.3`. After upgrading, please try uploading the appbundle again and feedback on whether or not it is accepted. 

Thank you

**Comment by pshukla0506** [comment]
Thanks @danagbemava-nc It is working now.
