### ISSUE TITLE
Duplicate class androidx.lifecycle.ViewModelLazy found in modules jetified-lifecycle-viewmodel-ktx-2.3.1-runtime (androidx.lifecycle:lifecycle-viewmodel-ktx:2.3.1) and lifecycle-viewmodel-2.5.1-runtime (androidx.lifecycle:lifecycle-viewmodel:2.5.1)

### ISSUE THREAD

**Issue by r4doshka** [flutter/flutter#111071]
after updating to the latest version, I had a problem when trying build app

[✓] Flutter (Channel stable, 3.3.0, on macOS 12.5.1 21G83 darwin-arm (Rosetta), locale ru-RU)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc5)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.71.0)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

<img width="961" alt="Снимок экрана 2022-09-07 в 13 05 08" src="https://user-images.githubusercontent.com/13236408/188811552-abdb074c-d7eb-450e-81e9-f62bb8bfcba4.png">

**Comment by danagbemava-nc** [comment]
Hi @r4doshka, please provide the following

- Your `android/app/build.gradle` & `android/build.gradle`
- Your pubspec.yaml
- The output of `flutter run -v` or `flutter build apk -v` (depending on the command you run). The output of this may be huge, so kindly put it into a .txt file and attach it here. 

Thank you

**Comment by r4doshka** [comment]
i solved my problem, it was due to the fact that I clicked upgrade dependencies through android studio. thx

<img width="787" alt="Снимок экрана 2022-09-08 в 11 15 01" src="https://user-images.githubusercontent.com/13236408/189040081-4131b60c-c566-4af8-acea-896c89a6c562.png">

**Comment by danagbemava-nc** [comment]
Closing this as solved

**Comment by 0xj0hn** [comment]
same issue.
I've also upgraded dependencies through `flutter pub upgrade` but I have the error yet
check my [issue](https://github.com/flutter/flutter/issues/111256) out.
@danagbemava-nc

**Comment by sebrojas14** [comment]
> i solved my problem, it was due to the fact that I clicked upgrade dependencies through android studio. thx
> 
> <img alt="Снимок экрана 2022-09-08 в 11 15 01" width="787" src="https://user-images.githubusercontent.com/13236408/189040081-4131b60c-c566-4af8-acea-896c89a6c562.png">

so, how dou you resolve it?
