### ISSUE TITLE
Theme `primaryColor` is applied to `CupertinoActionSheet` but not `CupertinoAlertDialog`

### ISSUE THREAD

**Issue by crizant-mpower** [flutter/flutter#111097]
When `isDestructiveAction` is set to `false`, the action buttons of `CupertinoActionSheet` uses the `primaryColor` defined in the theme:
https://github.com/flutter/flutter/blob/58ec4839159ea24eafe200d9c1ff41e35f720fa0/packages/flutter/lib/src/cupertino/dialog.dart#L696

But contrastly in `CupertinoAlertDialog`, when `isDestructiveAction` is set to `false`, `CupertinoColors.systemBlue` is used instead:
https://github.com/flutter/flutter/blob/58ec4839159ea24eafe200d9c1ff41e35f720fa0/packages/flutter/lib/src/cupertino/dialog.dart#L1716

Since the usage of these two widgets are very similar, should we unify the behavior?
I'm happy to submit PRs if you guys have a decision on this.

**Comment by exaby73** [comment]
Hello @crizant-mpower. Thank you for filing this request. Labelling for further insights from the team.

**Comment by MitchellGoodwin** [comment]
Merged in and closed.
