### ISSUE TITLE
Add WRITER role for "flutter/web/canvaskit_bundle"

### ISSUE THREAD

**Issue by loic-sharma** [flutter/flutter#111123]
Hello, I would like to roll CanvasKit using these instructions: https://github.com/flutter/engine/tree/main/lib/web_ui#rolling-canvaskit

This requires the `WRITER` role to update the `flutter/web/canvaskit_bundle` CIPD package. Could this be granted to my account, `user:sharma.loic@gmail.com`?

**Comment by godofredoc** [comment]
@yjbanov is this something that can be automated as a post-submit build?

**Comment by nehalvpatel** [comment]
@loic-sharma Can you try the auth and remaining steps with your corporate account?

**Comment by loic-sharma** [comment]
Thanks, that worked!
