### ISSUE TITLE
Probleme of apk

### ISSUE THREAD

**Issue by wrjcs** [flutter/flutter#111179]
Hello,
I just change the version in pubspec.yaml, and I recompile the apk.
old version:2.0.0+5
new version:3.0.0+1
I install with adb install, I got the error code:Failure [INSTALL_FAILED_VERSION_DOWNGRADE]

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.3.0, on Microsoft Windows [version 10.0.22621.457], locale fr-FR)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.10.3)
[√] Android Studio (version 4.2)
[√] VS Code (version 1.71.0)
[√] Connected device (4 available)
[√] HTTP Host Availability
anyone can help me?

**Comment by darshankawar** [comment]
@wrjcs 
When you change the version and tried to recompile , it might be taking up the cached version, so try to uninstall the `package name` and install again which should resolve the issue.

`adb shell pm uninstall "packagename"` then `adb install`.

Closing from here. If you face similar issue again, please ask it on support channels like StackOverflow.
