### ISSUE TITLE
Rebuild full widgets when use TextFormField inside BottomSheet  

### ISSUE THREAD

**Issue by Harbey127** [flutter/flutter#111122]
When use TextFormField inside bottom sheet and click on TextFormField, it rebuild full widget from builder bottom sheet parameter to end. I note that rebuild four times when click on and four time when back.

**Comment by Harbey127** [comment]
When use TextFormField inside bottom sheet and click on TextFormField, it rebuild full widget from builder bottom sheet parameter to end. I note that rebuild four times when click on and four time when back.

**Comment by exaby73** [comment]
Hello @Harbey127. Thank you for filing this issue. Can you please provide the following information?

- A [complete and minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).
- The output of `flutter doctor -v`
- The output of `flutter run-v`
