### ISSUE TITLE
[camera] Add Recorder class to CameraX plugin

### ISSUE THREAD

**Issue by camsim99** [flutter/flutter#111191]
### Overview
Part of https://github.com/flutter/flutter/issues/111138.

In the CameraX library, the [`Recorder`](https://developer.android.com/reference/androidx/camera/video/Recorder) class is used to save video recordings, and thus, will be essential to videos captured by the CameraX plugin.

The following is a running list of the fields and methods required for adding the `Recorder` class to the CameraX plugin.

#### Fields

- [ ] `static final QualitySelector DEFAULT_QUALITY_SELECTOR`

#### Instance Methods
- [x] `onSurfaceRequested(SurfaceRequest request)`
- [x] `PendingRecording prepareRecording(...)`*

 *One version needs to be picked and any classes passed as an argument will need to be additionally wrapped.

**Comment by gmackall** [comment]
This is done in https://github.com/flutter/packages/pull/3467
