### ISSUE TITLE
[camera] Add ProcessCameraProvider class to CameraX plugin

### ISSUE THREAD

**Issue by camsim99** [flutter/flutter#111127]
### Overview
In the CameraX library, the [`ProcessCameraProvider`](https://developer.android.com/reference/androidx/camera/lifecycle/ProcessCameraProvider) class is used to bind the various CameraX use cases to the lifecycle of any lifecycle-aware component. Thus, this class is essential to initiating any camera use case (taking a picture, taking a video, etc.) in the CameraX plugin.

### Requirements
The following is a running list of the methods required for adding the `ProcessCameraProvider` class to the CameraX plugin.

#### Instance Methods
- [x] `Camera bindToLifecycle(...)`
- [x] `List<CameraInfo> getAvailableCameraInfos()`
- [x] `boolean isBound(UseCase useCase)`
- [x] `void unbind(UseCase... useCases)`
- [x] `void unbindAll()`

#### Static Methods

- ~[ ] `static void configureInstance(CameraXConfig cameraXConfig)` (depends on https://github.com/flutter/flutter/issues/111134)~ Didn't need this for feature parity.
- [x] `static ListenableFuture<ProcessCameraProvider> getInstance(Context context)`

**Comment by iapicca** [comment]
is it a [camera](https://pub.dev/packages/camera) of [cameraX](https://github.com/yanshouwang/camerax/issues) issue?
