### ISSUE TITLE
Update some devicelab iPhones to iPhone11 and iOS 16

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#111131]
After iOS 16 is released on September 12, update devicelab phones after validating all tests succeed.

cc @yusuf-goog

**Comment by jmagman** [comment]
iOS 16 has been released.  Additionally each device will need developer mode enabled https://developer.apple.com/documentation/xcode/enabling-developer-mode-on-a-device

**Comment by yusuf-goog** [comment]
I can upgrade one device on Monday, for testing. Once thats complete I can upgrade additional/all devices.

**Comment by yusuf-goog** [comment]
Installed apple configurator on mac-4 staging bot.
Installed configurator cmd line tools.

Running upgrade on connected ios device:
```cfgutil update```

**Comment by yusuf-goog** [comment]
Ran the update, and it updated to only 15.7. Looks like the iphone 6s devices aren't supported by iOS 16:

iPhone 14 iPhone 14 Plus iPhone 14 Pro iPhone 14 Pro Max iPhone 13 iPhone 13 mini iPhone 13 Pro iPhone 13 Pro Max iPhone 12 iPhone 12 mini iPhone 12 Pro iPhone 12 Pro Max iPhone 11 iPhone 11 Pro iPhone 11 Pro Max iPhone XS iPhone XS Max iPhone XR iPhone X iPhone 8 iPhone 8 Plus iPhone SE (2nd generation or later)

**Comment by jmagman** [comment]
This will also require replacing the iPhons 6ses with already-purchased iPhone 11 phones.  That will also impact performance benchmarks as the new phones are faster.

From a conversation last summer with @godofredoc: 

> I think they officially support for 5 years, and legally have to repair in California for 7 years (https://www.latimes.com/business/la-fi-lazarus-20151211-column.html).  The 5-7 year support is "vintage" and older is "obsolete" https://support.apple.com/en-us/HT201624.  The iPhone 6S  (released 5 years ago) will probably become "vintage" soon.
> ...
>  iPhone 11 has the lowest for phones released in 2019 if we want to squeeze in another year.

Benchmark comparisons:
https://browser.geekbench.com/ios_devices/iphone-6s
https://browser.geekbench.com/ios_devices/iphone-11

**Comment by yusuf-goog** [comment]
I am prepping the iphone11 devices and will start the upgrade along with ios16. mac-4 device is targeted first.

**Comment by jmagman** [comment]
> This will also require replacing the iPhons 6ses with already-purchased iPhone 11 phones.

Actually, it sounds like we may need to keep some iPhone 6Ses in the lab for particular Impeller benchmarks.  We're working with the engine team to decide that ratio.  In the meantime, would be great to have an iPhone 11 / iOS 16 in staging to validate the tests all pass.

**Comment by yusuf-goog** [comment]
new iPhone11 device setup and swapped into mac-4. Waiting on provisioning profile CL to be submitted.

**Comment by yusuf-goog** [comment]
@jmagman iphone11 is now up at flutter-devicelab-mac-4.

**Comment by jmagman** [comment]
```
$ led get-builder 'luci.flutter.try:Mac_ios native_platform_view_ui_tests_ios' | led edit -d id=flutter-devicelab-mac-4 | led edit -d pool=luci.flutter.staging | led edit -d device_os=iOS-16 | led edit -d cpu=arm64 |  led launch
```
https://chromium-swarm.appspot.com/task?id=5d7b8691fa4d4a10
https://chromium-swarm.appspot.com/task?id=5d7b873755839d10
https://chromium-swarm.appspot.com/task?id=5d7b87b5c3d44310

**Comment by jmagman** [comment]
@yusuf-goog the devices need Developer Mode turned on:
```
	Ineligible destinations for the "infra-dialog" scheme:
		{ platform:iOS, id:00008030-00180D063A20C02E, name:iPhone, error:To use iPhone for development, enable Developer Mode in Settings → Privacy & Security.  }
```
"enable Developer Mode in Settings → Privacy & Security", then reboot the phone.  After reboot it will have another dialog that asks if you want to enable Developer Mode.

**Comment by jmagman** [comment]
We decided that we still need some impeller benchmarks to run on iPhone 6s / iOS 15.  So far they have only identified two benchmarks, so we will need to keep at least 2 iPhone 6s in the devicelab in the prod pool, and at least 1 in staging in case the benchmarks are marked flaky.  https://github.com/flutter/flutter/issues/112121

**Comment by yusuf-goog** [comment]
Running builds to validate macOS 12.6 and iPhone11, sample build:

```led get-builder 'luci.flutter.prod:Mac_ios animation_with_microtasks_perf_ios__timeline_summary' |led edit -d pool=luci.flutter.staging | led edit -d device_os=iOS-16 | led edit -d cpu=arm |  led edit -d id=flutter-devicelab-mac-4 | led launch```

**Comment by yusuf-goog** [comment]
@jmagman can you please look at these two failures as well:  `Mac_ios microbenchmarks_ios` and `Mac_ios microbenchmarks_impeller_ios`

**Comment by jmagman** [comment]
Already on it.

**Comment by jmagman** [comment]
new_gallery_impeller_ios__transition_perf https://ci.chromium.org/swarming/task/5d99cc055ab3f610?server=chromium-swarm.appspot.com
new_gallery_ios__transition_perf https://ci.chromium.org/swarming/task/5d99cc54fce2fc10?server=chromium-swarm.appspot.com

https://github.com/flutter/flutter/pull/112502 should fix the other two.

**Comment by jmagman** [comment]
> new_gallery_impeller_ios__transition_perf https://ci.chromium.org/swarming/task/5d99cc055ab3f610?server=chromium-swarm.appspot.com new_gallery_ios__transition_perf https://ci.chromium.org/swarming/task/5d99cc54fce2fc10?server=chromium-swarm.appspot.com

They still failed, need to roll the gallery SHA: https://github.com/flutter/flutter/pull/112509

**Comment by jmagman** [comment]
https://github.com/flutter/flutter/pull/112502 merged:
`microbenchmarks_ios` https://ci.chromium.org/swarming/task/5d9a36bf6712cb10?server=chromium-swarm.appspot.com
`microbenchmarks_impeller_ios` https://ci.chromium.org/swarming/task/5d9a36dd1147a310?server=chromium-swarm.appspot.com

**Comment by yusuf-goog** [comment]
Rerunning tests now.

**Comment by jmagman** [comment]
> Rerunning tests now.

The transition perf tests will still fail until https://github.com/flutter/flutter/pull/112509 merges.

**Comment by jmagman** [comment]
Work has begun at https://github.com/flutter/flutter/issues/117237

**Comment by jmagman** [comment]
Need to update to Xcode 14.2 in the lab to support 16.2 https://github.com/flutter/flutter/issues/117505

**Comment by jmagman** [comment]
https://github.com/flutter/flutter/issues/117505 has merged.

**Comment by jmagman** [comment]
@yusuf-goog is there any more work to do here, or shall I close?

**Comment by yusuf-goog** [comment]
Yes, all iphone11 assets that we have have been deplpyed.
