### ISSUE TITLE
Support for splashRadius in Material 3

### ISSUE THREAD

**Issue by ShourovRoy** [flutter/flutter#111109]
In AppBar material 3 the IconButton into the actions widget list is not so convincing at all in 3.3. The splash radius must be supported thing in all versions.

**Comment by exaby73** [comment]
Hello @ShourovRoy. Could you provide the following information:

- A [complete and minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) the demonstrates this and how does this compare the M2 implementation.
- The output of `flutter doctor -v`.
