### ISSUE TITLE
[macOS text input] pinyin candidate view doesn't dismiss itself when the composing text is deleted

### ISSUE THREAD

**Issue by LongCatIsLooong** [flutter/flutter#111113]
## Steps to Reproduce

The problem seems to be pinyin (simplified chinese) specific. 

https://user-images.githubusercontent.com/31859944/188939284-feb18a0d-89c5-4718-91e6-944dbd0a559a.mov

reproducible on the tip of the master branch.

**Comment by justinmc** [comment]
(From triage) also noticed that it's not updating at all when the backspace key is pressed.  It should go from two characters to one before disappearing.

**Comment by justinmc** [comment]
Maybe this is because the delete key is consumed by Shortcuts in the framework?

**Comment by LongCatIsLooong** [comment]
Doesn't seem to happen any more. Closing.

https://github.com/flutter/flutter/assets/31859944/8ded9422-c2f6-42cf-99b5-aa6c338e9e64
