### ISSUE TITLE
maxLength is not working in case of emoji 

### ISSUE THREAD

**Issue by pranavo72bex** [flutter/flutter#111174]
**MaxLength in Textfield is not working. Emoji length is not considered in Textfield.**

**_Formatter does not currently count Unicode grapheme clusters_**

`[✓] Flutter (Channel unknown, 2.10.5, on macOS 12.5.1 21G83 darwin-arm, locale
    en-NP)
[✓] Android toolchain - develop for Android devices (Android SDK version
    32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.71.0)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

**I tried this solution [Link](https://dev.to/stack-labs/flutter-utf8-textfield-length-limiter-and-char-counter-31o7) but it is not good solution to do**

**Comment by iapicca** [comment]
I tried a [repro code](https://dartpad.dartlang.org/?id=b0bc58fa91bb6a51ca9b11026b220d4c) based more or less on the link provided, there are a bunch of weird behaviours.
It would be nice if `emoji` were first class citizens using [textfield](https://api.flutter.dev/flutter/material/TextField-class.html)

**Comment by pranavo72bex** [comment]
> I tried a [repro code](https://dartpad.dartlang.org/?id=b0bc58fa91bb6a51ca9b11026b220d4c) based more or less on the link provided, there are a bunch of weird behaviours
> (e.g: type 9 chars, add emoji pressing fab, delete the first char).
> It would be nice if `emoji` were first class citizens using [textfield](https://api.flutter.dev/flutter/material/TextField-class.html)

Hope they address this issue and fix it

**Comment by iapicca** [comment]
> > I tried a [repro code](https://dartpad.dartlang.org/?id=b0bc58fa91bb6a51ca9b11026b220d4c) based more or less on the link provided, there are a bunch of weird behaviours
> > (e.g: type 9 chars, add emoji pressing fab, delete the first char).
> > It would be nice if `emoji` were first class citizens using [textfield](https://api.flutter.dev/flutter/material/TextField-class.html)
> 
> Hope they address this issue and fix it

actually I'm confused...
removing the implementation adapted from the link you provided

> **I tried this solution [Link](https://dev.to/stack-labs/flutter-utf8-textfield-length-limiter-and-char-counter-31o7) but it is not good solution to do**

everything seems to work just fine... am I missing something?

**Comment by exaby73** [comment]
Hello @pranavo72bex. Sorry for the late response. I can see @iapicca's findings... This looks like an error in the input formatters. Is there a simpler example which reproduces the issue you described? I'm not too familiar with text encoding so I won't be able to tell where the error is.

**Comment by iapicca** [comment]
> This looks like an error in the input formatters.
> [...]
>  I'm not too familiar with text encoding so I won't be able to tell where the error is.

what error are you observing? 
I commented out every reference to the implementation w/ `Utf8Encoder` 
and works just fine as far as I can see

**Comment by exaby73** [comment]
@iapicca Sorry I guess I didn't explain well enough. I agree with your statement and can see when commenting out the custom input formatters, the code works. I cannot be sure if the (logical) error exists within the input formatter or if this is an encoding issue with `dart:convert`.

**Comment by pranavo72bex** [comment]
@iapicca  @exaby73  Any update regarding this issue 🙏

**Comment by iapicca** [comment]
@pranavo72bex 
as far as I can see there is no issue, what problem are you experiencing in my update repro code? (see [post](https://github.com/flutter/flutter/issues/111174#issuecomment-1241220576))

> actually I'm confused... removing the implementation adapted from the link you provided
> 
> > **I tried this solution [Link](https://dev.to/stack-labs/flutter-utf8-textfield-length-limiter-and-char-counter-31o7) but it is not good solution to do**
> 
> everything seems to work just fine... am I missing something? ([repro code](https://dartpad.dartlang.org/?id=b0bc58fa91bb6a51ca9b11026b220d4c) updated, you can still uncomment the other stuff)
