### ISSUE TITLE
Source code for dart:core patch files missing on Windows in stable 3.3

### ISSUE THREAD

**Issue by DanTup** [flutter/flutter#111189]
In Flutter 3.3, source code for some SDK libraries (that were available in Flutter 3.0) appear missing when running on Windows.

To reproduce:

- Create a new Flutter counter app
- Add `assert(false)` into the `incrementCounter` function
- Run the app with Windows as the target
- Ensure debug settings are set to include SDK libraries (in VS Code this can be done by clicking on "Debug my code" in the status bar and toggling it to "Debug my code + sdk + packages")
- Click on the FAB button to trigger the assert

When using Flutter 3.0, you will break inside the source for dart:core/errors_patch.dart:

![flutter_3_0_working](https://user-images.githubusercontent.com/1078012/189153063-60b9d8ed-ff76-4ea9-8f88-ffe8164afcd3.png)

But when doing the same on Flutter 3.3 you get an error that the source is not available:

![flutter_3_3_broken](https://user-images.githubusercontent.com/1078012/189153140-3ed9194e-2c65-4aad-be04-79dbe055608e.png)

VS Code gets this source code via the VM Service. When the debugger breaks, we're given an ID of the script for the top frame. If we cannot map this to a local source on disk, we send a `getObject` request to get the source code. In both versions above, this request is the same (besides isolate IDs, of course):

![same_requests](https://user-images.githubusercontent.com/1078012/189153383-b73789ed-7cb4-4478-b905-f70d6262ce49.png)

However, in the response from the VM Service when using Flutter 3.3, the `"source"` field is missing:

![difference](https://user-images.githubusercontent.com/1078012/189153495-12d4555d-a904-4be2-b1c2-adaa3b555998.png)

I wasn't able to reproduce this on my Mac, so I suspect this is Windows specific.

Relevant VM Service requests:

- [Flutter 3.0 (working)](https://github.com/flutter/flutter/files/9527897/flutter_3_0_working.txt)
- [Flutter 3.3 (not working)](https://github.com/flutter/flutter/files/9527895/flutter_3_3_broken.txt)

I'm not certain whether this is a Flutter or Dart issue, but based on a similar issue in the past I think it may be Flutter. If not, please let me know and I can re-raise this in the Dart repo.

**Comment by exaby73** [comment]
Hello @DanTup. Thanks for raising this issue. Labelling for further insights from the team.

**Comment by point-source** [comment]
I'm also seeing this when certain exceptions are hit on a codebase that previously did not exhibit this behavior. Currently getting this output from vscode when invalid image data is passed to an Image widget: `Could not load source 'dart:ui/painting.dart': <source not available>.`
