### ISSUE TITLE
Trying Android 16 But warning "Flutter requires Android SDK 29 and the Android BuildTools 28.0.3"

### ISSUE THREAD

**Issue by AndreMikulec** [flutter/flutter#111158]
Hi,

I am attempting to install Flutter with Android SDK 16.
(Android 16 is allowed.)

I am following:
Windows install
https://docs.flutter.dev/get-started/install/windows

From
flutter_windows_3.3.0-stable.zip
I have extracted to `C:\flutter`.

I added to my SYSTEM Path:
`C:\flutter\bin`

According to this
https://docs.flutter.dev/development/tools/sdk/release-notes/supported-platforms
I can choose
`Android	API 16 (Android 4.1) & above	All`

I have installed Android studio:

The Android SDK location is the following (and this is correct):

`C:\Users\AnonymousUser\AppData\Local\Android\Sdk`

In the SDK Manager in the SDK Platforms tab I have chosen

```
                              API Level
                              ----------
[x] Android 4.1 (Jelly Bean)  16
```
In the SDK Manager in the SDK Tools tab I have chosen

[x] Android SDK Build-Tools 33
[x] Android SDK Command-line Tools (latest)
[x] Android Emulator
[x] Android SDK Platform Tools 33.0.3
[x] Google USB Driver
[x] Intel x86 Emulator Accelerator (HAXM installer)

When I run `flutter doctor -v`, I am getting back the following [!]:

```
[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\AnonymousUser\AppData\Local\Android\sdk
    X Flutter requires Android SDK 29 and the Android BuildTools 28.0.3
      To update the Android SDK visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions.
    • All Android licenses accepted.
```

What do I need to do next?

Thanks,
Andre Mikulec

**Comment by exaby73** [comment]
Hello @AndreMikulec. Flutter may allow you to build apps for API 16, but for Flutter to function, you may need to install the SDK for API 29. Please try that and confirm if you still have an issue.

The link you mentioned ([Supported Platforms](https://docs.flutter.dev/development/tools/sdk/release-notes/supported-platforms)), means these are devices on which Flutter would run as a target, not as a host.

**Comment by AndreMikulec** [comment]
Using the above features: SDK - Android 4.1 (Jelly Bean) API  16
and Flutter 3.3.0 ( Google Tested Platform Android 11 API 30 )
I built an .apk that ran in BlueStacks 5 emulating Android 7.0 (Nougat) API 24 .

O.K. I understand.  I am closing this ticket.
