### ISSUE TITLE
[flutter 3.3] isolate error when using generator: invalid argument: illegal argument in isolate message : (object is a suspendstate)

### ISSUE THREAD

**Issue by peterweb2005** [flutter/flutter#111184]
i have a future builder, listen to (future argument is) a iterator generator, 
then show the red screen

**Comment by exaby73** [comment]
Hello @peterweb2005. Thank you for filing this issue. Can you please provide the following information?

- A [complete and minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).
- The output of `flutter doctor -v`
- The output of `flutter run-v`

**Comment by peterweb2005** [comment]
current workaround

```
//Iterable<HorseCombo> extractHorseComboList(data.HorseRace race) sync* {
Future<List<HorseCombo>> extractHorseComboList(data.HorseRace race) async {

... (also coding: new list & add item to the list & return the list, to replace yield)
```
