### ISSUE TITLE
webview_flutter  Image Sticking

### ISSUE THREAD

**Issue by lisen87** [flutter/flutter#111161]
When using flutter 3.0, WebView encounters residual image problems. Flutter 2.10.3 is good。
This is an example of loading a 3D file using WebView modelviewer，This is using the modelviewer address ：https://modelviewer.dev/

1 , Using WebView_ Flutte any version
2,html :

```dart
          <html>
              <script type="module" src="https://unpkg.com/@google/model-viewer/dist/model-viewer.min.js"></script>
              <script>
                          function sendProgress (message){
                            progress.postMessage(message)
                          }
              </script>
              <style>
                   #lazy-load-poster {
                }
                #button-load {
                }
                  model-viewer {
                    width: 100%;
                    height: 100%;
                    margin: -10;
                    padding: -10;
                    background-color: transparent;
                  }
                   model-viewer#reveal {
                    --poster-color: transparent;
                   }
              </style>
              <!-- Use it like any other HTML element -->
              <body style='margin:0;padding:0'>
              <div class="demo" style="background: transparent; overflow-x: hidden;">
                  <model-viewer id='dimension-demo'
                                src="http://51xingkong.oss-cn-qingdao.aliyuncs.com/6904a922e6b60ab8ee20a14e9ff97c80%20_1_.gltf"
                                shadow-intensity="1" camera-controls auto-rotate interaction-prompt="none"
                                camera-orbit="0deg 90deg 105%"
                                scale="1.2 1.2 1.2"
                                exposure="1.0"
                                rotation-per-second="20deg" auto-rotate-delay=1000
                                style="background-color: transparent;">
                      <div slot="poster" style="background: transparent;"></div>
                      <div slot="poster"></div>
                      <div slot="progress-bar"></div>
                  </model-viewer>
              </div>
              <script type="module">
                    const modelViewer = document.querySelector('#dimension-demo');
                    modelViewer.addEventListener('progress', (e) => {
                      sendProgress(e.detail.totalProgress)
                    });
              </script>
              </body>
       </html>
```
3,
   ```dart
        WebView(
            javascriptChannels: <JavascriptChannel>[
              JavascriptChannel(
                  name: 'progress',
                  onMessageReceived: (JavascriptMessage message) async {
                    
                  }),
            ].toSet(),
            backgroundColor: Colors.transparent,
            initialUrl: Uri.dataFromString(html,
                mimeType: 'text/html',
                encoding: Encoding.getByName('utf-8'))
                .toString(),
            javascriptMode: JavascriptMode.unrestricted,
          )

   ```

4，
This is fluent 3.0：
<img width="400" src="https://user-images.githubusercontent.com/20718263/189017642-e0eb6c05-8e46-43f8-b293-ed5883dcd7a6.png">

This is fluent 2.0：
<img width="400" src="https://user-images.githubusercontent.com/20718263/189017722-532d2fd3-c970-4d6f-8590-0a171cc95db7.png">

**Comment by huycozy** [comment]
Hi @lisen87 
Please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this. In this case, please push the sample code to a Github repository and make it public. Also, please provide the output of `flutter doctor -v` as well.
Thank you!

**Comment by lisen87** [comment]
@huycozy
Thank you for your answer！

flutter doctor -v

Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
[√] Flutter (Channel stable, 3.0.5, on Microsoft Windows [版本 10.0.18363.1556], locale zh-CN)
    • Flutter version 3.0.5 at F:\flutter\flutter_windows_3.0.5-stable\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (8 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[!] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at C:\Users\lisen\AppData\Local\Android\sdk
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] Connected device (3 available)
    • Redmi 8A (mobile) • af8330ef0306 • android-arm    • Android 9 (API 28)
    • Windows (desktop) • windows      • windows-x64    • Microsoft Windows [版本 10.0.18363.1556]
    • Edge (web)        • edge         • web-javascript • Microsoft Edge 105.0.1343.27

[√] HTTP Host Availability
    • All required HTTP hosts are available

**Comment by lisen87** [comment]
我已将示例代码提交到github，这是 项目地址  https://github.com/lisen87/image_sticking

**Comment by lisen87** [comment]
I have submitted the sample code to GitHub. This is the project address

https://github.com/lisen87/image_sticking

**Comment by huycozy** [comment]
@lisen87 Thanks for the sample code but the web is not displayed when I ran it.

<details>
<summary>Demo</summary>

![Simulator Screen Shot - iPad (9th generation) - 2022-09-09 at 10 49 20](https://user-images.githubusercontent.com/104349824/189268184-6a4b3582-f0d4-4f93-a274-406582592828.png)

</details>

It could be related to the network. Please make sure the asset is public so that we may verify this.

**Comment by lisen87** [comment]
@huycozy  
Yes, I have revised the network download problem again. The sample code has been updated to GitHub: https://github.com/lisen87/image_sticking , please try again it.

In addition, The following is the mobile phone information with problems

![1](https://user-images.githubusercontent.com/20718263/189274217-bcc538c3-e372-413c-b36b-adc10d328ffb.png)

![2](https://user-images.githubusercontent.com/20718263/189275119-ed162623-96b9-4420-9f4f-fec2247f7774.png)

**Comment by huycozy** [comment]
Hi @lisen87, thanks for updating sample code.
But I can not reproduce the issue on the latest `stable` and `master` channels.

<details>
<summary>Demo</summary>

| iOS | Android (Galaxy Tab A7) | Android (Realme 6) 
| --------------- | --------------- | --------------- |
<video src="https://user-images.githubusercontent.com/104349824/189301148-facd3bb2-afba-4bb1-ac25-68ccdc5bb999.mp4"/> | <video src="https://user-images.githubusercontent.com/104349824/189301167-bac43e6c-4a73-49c7-9a18-72cee683d4e4.mp4"/> | <video src="https://user-images.githubusercontent.com/104349824/189301182-70f021a2-a1f9-4e5d-82a7-d22ecf2c3dec.mp4"/>

</details>

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 3.3.1, on macOS 12.5.1 21G83 darwin-x64, locale en-VN)
    • Flutter version 3.3.1 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4f9d92fbbd (31 hours ago), 2022-09-06 17:54:53 -0700
    • Engine revision 3efdf03e73
    • Dart version 2.18.0
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13E113
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2020.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.71.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.5.1 21G83 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 105.0.5195.102

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

```bash
[✓] Flutter (Channel master, 3.4.0-19.0.pre.153, on macOS 12.5.1 21G83 darwin-x64, locale en-VN)
    • Flutter version 3.4.0-19.0.pre.153 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d2434a2b60 (4 hours ago), 2022-09-08 15:39:07 -0700
    • Engine revision 4096e133ef
    • Dart version 2.19.0 (build 2.19.0-177.0.dev)
    • DevTools version 2.17.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13E113
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2020.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.71.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.5.1 21G83 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 105.0.5195.102

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```
</details>

As far as I can see, you are using the old Flutter version `3.0.5`, the latest Flutter stable is `3.3.1` and the master is `3.4.0`. Please try upgrading them and retry to see if this issue still reproduces.

**Comment by lisen87** [comment]
I just used the latest SDK to test, and there is no problem. thank you
