### ISSUE TITLE
Re-work Java plugin API to more clearly delineate sync vs async operations

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#11111]
Right now, the `MethodCallHandler` interface looks like the following:

```java
public interface Result {
  void success(Object result);
  void error(String errorCode, String errorMessage, Object errorDetails);
  void notImplemented();
}

public interface MethodCallHandler {
  void onMethodCall(MethodCall call, Result result);
}
```

This API is very async in nature, which makes it a little mismatched for synchronous use cases:
* There's no compile-time enforcement that you ever complete the result (either successfully or with an error)
* The channel implementation will handle uncaught errors by sending them back to Dart as `PlatformException` instances, but it obviously can't do the same in asynchronous callbacks, where uncaught exceptions will crash the application.

These limitations are necessary for asynchronous operations, but the disparity between how synchronous plugins and asynchronous ones interact with this API feels a little clunky (e.g. #11110).

What if we changed it to the following:

```java
public abstract class Result<T> {
  public static <T> Result<T> of(T value);
  public static <T> Result<T> async(ResultCallback<T> callback);
}

public interface ResultCallback<T> {
  void success(T result);
  void error(String errorCode, String errorMessage, Object errorDetails);
}

public interface MethodCallHandler<T> {
  Result<T> onMethodCall(MethodCall call) throws Exception;
}
```

With the proposed API:
* It's clear that `onMethodCall()` can throw an exception and that the channel implementation will handle it
* `onMethodCall()` implementations will have compile-time enforcement that they return a result.
* Synchronous plugins can simply return `Result.of(value)` in their `onMethodCall()` implementations.
* Asynchronous plugins will have to explicitly return `Result.async(callback)` to opt-in to the asynchronous limitations (e.g. no compile-time enforcement that you ever actually complete the result), which is fine since that's always inherent in async code.
* the existing `Result.notImplemented()` goes away in favor of just throwing `UnsupportedOperationException` in `onMethodCall()`.

/cc @mravn-google @mehmetf

**Comment by collinjackson** [comment]
As someone who has forgotten to call `result.success(null)` in the past, I like this change.

I wonder if while we are at it we should overload `success()` to allow code to indicate whether it's returning `null` or a `void` value. This isn't very useful today, but could be useful in Dart 2.0 where `Future<Void>` is a thing.

**Comment by tvolkert** [comment]
> overload success() with an argument-free version to allow Java plugins
> to indicate whether they are returning null or a void

Java generics allow for `ResultCallback<Void>`, in which case the compiler ensures that you call `success(null)`.  The syntax is a little forced (like many things in Java), but it works in the existing proposal.

**Comment by collinjackson** [comment]
So synchronous methods with no result would `return Result<Void>.of(null);`. I guess that's ok, but a shorthand abbreviation might be nice.

I think it won't be common for all of a plugins methods to happen to have a value of the same return type, or least not common enough to make MethodCallHandler a generic to enforce it.

As long as we are going to make a breaking change to plugins, I wonder if we can remove the giant switch statement that every current `MethodCallHandler` has to have, and instead use code generation to dispatch method calls to annotated methods of the `MethodCallHandler`. On the iOS side, we could do a similar thing with selectors.

**Comment by tvolkert** [comment]
> I think it won't be common for all of a plugins methods to happen
> to have a value of the same return type

Yeah you may be right.  We could just make the interface:

```
public interface MethodCallHandler {
  Result<?> onMethodCall(MethodCall call) throws Exception;
}
```

> ... use code generation to dispatch method calls to annotated methods

I like this a lot.  However, it increases the scope of this change quite a bit.  It also poses questions like:
* What do we use for the IDL?
* Do we codify the protocol by which plugins pass arguments from Dart to OEM code?  Right now it's up to each plugin.  For example, those that take a single argument often just pass it directly, whereas ones that take multiple typically pass a map of named arguments.  Do we enforce the map pattern in order to make the auto-dispatch code work?

I'm tempted to say let's hold off on such a change, but on the other hand, breaking changes to the plugin API are painful, so there's something to be said for making them all at once.  @collinjackson WDYT?

**Comment by collinjackson** [comment]
Hmm. Well, if we wanted to be less ambitious, we could do something like this...

```
@MethodCall
void foo(Map<String, ?> arguments) {
  int bar = (int) arguments.get("bar");
  // ... do something with bar ...
}
```

Then if Dart tries to invoke that method with anything other than a Map populated with String keys, it should complain (ideally at compile time, but at least at runtime), and the codegen would convert that method to automatically return a new Result<Void>.of(null);, so if Dart tries to read the return value it would complain.

Async methods could be annotated @AsyncMethodCall and get an additional `ResultCallback` argument.

I agree that it's scope creep, and I'm fine with forward with the initial breaking change if you feel strongly that it's the right thing to do. I just feel like this might be a good opportunity to make a wish list of plugin API changes now that a fair amount of actual plugin code has been written and we have decided to break it.

**Comment by kirbyfan64** [comment]
While on the note of sync vs async, one thing that has been bugging me is `invokeMethod` returning a `Future`. As handy as that is, for simple use cases (e.g. where the Java code is guaranteed to return almost immediately), it does nothing but be a major annoyance.

**Comment by collinjackson** [comment]
More than annoying, it makes some native APIs impossible to efficiently emulate as wrappers (this has come up in the implementations of Firebase Database and Firebase Remote Config). Unfortunately, I don't think we can easily untangle the async-ness of plugin calls. The native code is running on a different thread from the Dart code, and pausing the Dart VM while the native code executes doesn't seem like a recipe for good performance.

**Comment by mravn-google** [comment]
The current API was designed to be 1) straightforward Java and 2) easily mapped to its ObjC counterpart. Breaking it and replacing it with a more involved solution should solve a real problem.

The proposed async API is not clear to me. Rather than giving your async result value to a provided callback, you have to return a Result wrapping a callback that you provide yourself? Who calls that callback?

**Comment by mehmetf** [comment]
Most of these LGTM. Some comments:

We should allow `onMethodCall` to return null instead of `new Result<Void>.of(null);`. Plugin framework can handle the null case in any way it wants.

I like the codegen approach to dispatching method calls. However let me creep your scope a bit more: We need to think about Dart. Currently, there's a nice symmetry between Dart/ObjC/Java where string consts are used to refer to methods. Changing this to method annotations on Native side breaks this symmetry in a big way and makes the overall plugin architecture harder to understand. I would be more okay with the change if we can generate the Dart interface and call that. That is, instead of

`PlatformChannel.call('myMethod', {'arg1', 'value1'});`

do the following which is properly type checked

`MyPlugin.myMethod(value1)`.

With proper preprocessing in place, possibilities are endless. You can even check that ObjC/Java implementations of the same method has the same signature (since they both need to map to the same Dart signature).

@mravn-google The current architecture is very flexible, however IMHO it does not lend itself to development-at-scale. It is too easy to make mistakes; such as forgetting to call result.success() or messing up the names of args or methods (since they are just string consts) or forgetting to return after result.error() gets called deep into one of your methods. It would be beneficial if we made an effort to make plugin control flow a bit more traditional (i.e. type checked method calls, sane return/throws semantics etc).

**Comment by mravn-google** [comment]
Godegen brings its own complexities (on build tooling for a start) and we should retain a simple API that does not force those complexities on projects that don't already face them for other reasons. Engineering large-scale, stricter, or opinionated layers on top of a simple/flexible mechanism is fine, of course. I may be wrong, but I don't expect most individual plugins to be large-scale efforts in need of such layers.

**Comment by mehmetf** [comment]
That's a fair point.

Before Todd created this issue, he and I discussed that there is no meaningful "midpoint" solution. We either say the current solution is good enough and let it be or we go full bore. 

I am okay with either. May be the points we made above are not worth the effort. There's also the complexity of making it work with google3 rolls.

**Comment by tvolkert** [comment]
> Who calls that callback?

You're right - as suggested above, it doesn't work! 😮   I originally had the following, which (with some private API mixed in there not shown below) can be made to work.

```
public final class MethodChannel {
  public static abstract class Result<T> {
    public static <T> Result<T> of(T value);
    public static <T> AsyncResult<T> async();
  }

  public static final class AsyncResult<T> extends Result<T> {
    public void success(T result);
    public void error(String errorCode, String errorMessage, Object errorDetails);
  }

  public interface MethodCallHandler<T> {
    Result<T> onMethodCall(MethodCall call) throws Exception;
  }
}
```

That being said, maybe as Mehmet says it's not worth the effort.  This all spawned from https://github.com/flutter/engine/pull/3851, which was borne out of the desire in the google_sign_in plugin to be able to throw an exception that would propagate to Dart with a meaningful error code, message, and details.  That PR triggered a larger discussion, which resulted in this proposal.

> There's also the complexity of making it work with google3 rolls.

I'm not worried about that -- I could just roll Flutter and all updated plugins atomically into Google.

------

I guess at this point, the open questions are:
1. Do we think the proposed API is *holistically* an improvement at all, when we consider the disparity it'll create with the Objective C API?
2. If it is, is the improvement worth the effort?

If the answer isn't "yes" to both, we should probably just keep the API as-is.

Thoughts?

**Comment by mehmetf** [comment]
It is at least worth scoping and designing. I don't buy the argument that most plugins do not need this. We are not just improving some corner case; the problems described above exists in all plugin. The sheer number of plugins popping up internally and externally (~50 by my latest count) implies that there's a benefit to make the framework easier to reason with.

However, I would not prioritize it high. The current system works and is not fundamentally broken.

Perhaps we can consider it for Flutter 2.0? :-)

**Comment by collinjackson** [comment]
Personally, I don't think it's worth changing the API just to distinguish sync vs async methods, but I could see the benefit as part of a larger change that refactored both Java and iOS.

One potential compromise would be to build Todd's API proposal on top of the existing MethodChannel; provide a new abstract class PluginMethodCallHandler that plugins could extend if they want to opt in to more opinionated calling conventions and type checking. This class (which implements `MethodCallHandler`) would dispatch method calls to subclasses' registered methods, and its registration mechanism could distinguish sync and async methods, allow declaring types, etc.

**Comment by tvolkert** [comment]
https://gist.github.com/tvolkert/c61a398919b341637e85ed9a15fa4ea5

FTR, that's an _extremely_ rough sketch of the what the originally proposed API might look like.  However, it sounds like the consensus is that it's only worth it if we increase the scope to be part of a larger refactor.

**Comment by tvolkert** [comment]
@bparrishMines is this still relevant?

**Comment by bparrishMines** [comment]
cc @blasten @cyanglaz 

@tvolkert I don't believe it is currently on our team's radar. After reading through the comments I agree with the idea that these improvements to the API may not help enough to justify breaking changes. I think the current API achieves its goal by being a simple to use, cross-platform solution and it would be easier to keep the API on both platforms similar for the time being.

I think we're now focused on building more involved solutions such as [pigeon](https://pub.dev/packages/pigeon) or [reference](https://pub.dev/packages/reference).

**Comment by tvolkert** [comment]
Sounds good - I'll close this as obsolete.
