### ISSUE TITLE
[Impeller] Make Matrix::MakeColumn and MakeRow constexpr factories.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#111165]
Impeller matrices use column-major storage and the constructor expect arguments in the same order. This is confusing to API users who may be used to arguments to be in row-major storage order. Just have named constexpr factories so this is easier to reason about. Perhaps even remove the current constructors (likely to be a larger change now though).

**Comment by ColdPaleLight** [comment]
@guoguo338 would like to file a PR to fix it.

**Comment by chinmaygarde** [comment]
@ColdPaleLight Roger. Thanks! I just move [any issues on the dashboard](https://github.com/orgs/flutter/projects/21/views/1) that have assignees to the "In Progress" section. If you are not working on it for any reason, feel free to un-assign so I can move it back :)

**Comment by ColdPaleLight** [comment]
Closing it via linked PR
