### ISSUE TITLE
[In_app_purchases] Need to upgrade to Billing Library 4 - Google Console won't accept Billing 3 any more.

### ISSUE THREAD

**Issue by saeedtemraz** [flutter/flutter#111261]
[In_app_purchases] Need to upgrade to Billing Library 4 - Google Console won't accept Billing 3 any more.

**Comment by darshankawar** [comment]
@saeedtemraz 
Per this merged PR, the billing library has been migrated to v5 already: https://github.com/flutter/plugins/pull/5405

Please check the same and use latest plugin version (if not already) to get latest updates.

Closing for now, as this is already addressed and fixed. If you disagree, write in comments and I'll reopen it.

**Comment by SalsabeelaHasan** [comment]
Hello @darshankawar, there is no indication in the release note of the plugin that the billing SDK has been updated to 4 or 5, can you tell me which version of the plugin is carrying these updates? Thanks.

**Comment by darshankawar** [comment]
@SalsabeelaHasan 
Please check this: https://pub.dev/packages/in_app_purchase_android/changelog#023
