### ISSUE TITLE
[CP] revert removal of opacity layers

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#111208]
### issue_link

https://github.com/flutter/flutter/issues/111145

### Commit Hash

7e1e840 

### Target

stable

### pr_link

https://github.com/flutter/flutter/pull/111207

### Impacted Users

All desktop developers

### Impact Description

See https://github.com/flutter/flutter/issues/111145

Severe graphical artifacts on low DPR devices

### Workaround

There is no work around.

### Risk

low

### Test Coverage

yes

### Validation Steps

Build and run the example app in https://github.com/flutter/engine/pull/35981 on a low DPR device.

Note: this is a request for a corresponding framework change, but both the engine and framework change need to be in the same release. The framework change is not risky, the engine change is riskier.

**Comment by itsjustkevin** [comment]
Merged in Flutter 3.3.2.
