### ISSUE TITLE
Add Flutter version and branch as accessible global values inside of a Flutter app.

### ISSUE THREAD

**Issue by gspencergoog** [flutter/flutter#111204]
It would be useful to be able to access the version of Flutter that an app was built with, as well as the channel that it was built from.

Since the tool already knows this information, it should be easy to add dart defines that would then be referenced from globals inside of Flutter.

This would enable showing the version in the about box, predicating running skipped tests on the version number, showing a "beta" banner, or other uses.

On the master channel, the branch should be filled out, but the version is the empty string, since master versioning is not determinate.  On unknown branches, the channel should be "unknown", and the version will be the empty string.

**Comment by jonahwilliams** [comment]
I believe we specifically declined to add this feature in the past

**Comment by chinmaygarde** [comment]
Right, see https://github.com/flutter/flutter/issues/26037#issuecomment-749143370 for past iterations of this.

**Comment by gspencergoog** [comment]
The use case I have is the following.  Perhaps it's enough to change the past opinion, perhaps not.

There tests in the `flutter/packages` repo (which runs its tests on both stable and beta) that I would like to be skipped only until the Flutter version is past a certain version (so that a feature that is required for the test to pass is in stable), and then start running them, so that they automatically "unskip" when they are now able to pass. Alternatively, it could just fail the test once it's past the value so that we can re-evaluate the skip when the roll to the new version happens.

In addition, it would be nice to be able to allow people to see the Flutter version/branch that an app was built on in the About dialog to help with reporting.

**Comment by christopherfujino** [comment]
Unassigning myself pending consensus that we should actually implement this

**Comment by gspencergoog** [comment]
I'm going to close this.  We'd probably end up regretting adding it.
