### ISSUE TITLE
getString in html dart package is shown as error 

### ISSUE THREAD

**Issue by adityamv7** [flutter/flutter#11127]
getString in HttpRequest class of dart html is shown as undefined 
I have used the following code 
```dart
void loadData() {
  var url = "";

  // call the web server asynchronously

  var request = HttpRequest.getString(url).then(onDataLoaded);

}

void onDataLoaded(String responseText) {
  var jsonString = responseText;
  print(jsonString);
}

main() {
  loadData();
}
```

**Comment by eseidelGoogle** [comment]
Flutter doesn't expose `dart:html`:
https://flutter.io/faq/#can-flutter-run-any-dart-code

The HttpRequest class in Flutter is from dart:io:
https://docs.flutter.io/flutter/dart-io/HttpRequest-class.html

**Comment by Hixie** [comment]
@adityamv7 When filing bugs please don't ignore the template in the new issue page; we need information such as the output from `flutter analyze` to diagnose the problem.

**Comment by adityamv7** [comment]
Duly noted @eseidelGoogle  @Hixie  
I had to change the code to make it error free

**Comment by Hixie** [comment]
We don't really understand the issue here. If you are still running into this please file a new bug with more detail. Thanks.
