### ISSUE TITLE
[cross_file] No option to delete/rename file

### ISSUE THREAD

**Issue by adil192** [flutter/flutter#111218]
## Use case

`cross_file` already provides read and write functions. However, it is lacking delete/rename functions.

## Proposal

```dart
import 'package:cross_file/cross_file.dart';

final file = XFile('assets/hello.txt');

file.delete();
// or..
file.renameTo('assets/bye.txt');
```

```dart
// base.dart
abstract class XFileBase {
  Future<void> renameTo(String path) {
    throw UnimplementedError('renameTo() has not been implemented.');
  }
  Future<void> delete(String path) {
    throw UnimplementedError('delete() has not been implemented.');
  }
}

// io.dart
class XFile extends XFileBase {
  Future<void> renameTo(String path) async {
    await saveTo(path);
    await delete();
  }
  Future<void> delete(String path) async {
    await _file.delete();
  }
}
```

**Comment by exaby73** [comment]
Hello @adil192. Thank you for filing this request. Labelling for further insights from the team.

**Comment by adil192** [comment]
It seems I misunderstood the purpose of this package. I assumed it'd be creating a virtual filesystem for the web but upon refactoring my app, `cross_file` only downloads the file when saved instead of saving it to the given path.
