### ISSUE TITLE
[CP] Fix custom engine embedding build failure

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#111296]
### issue_link

https://github.com/flutter/flutter/issues/110936

### Commit Hash

c294429770081f43db967db96132e13260aa4210

### Target

stable

### pr_link

https://github.com/flutter/engine/pull/36054

### Impacted Users

Users creating custom engine embeddings building with gcc

### Impact Description

The build of custom embeddings based on the 3.3 stable branch of the engine are currently broken if they use an up-to-date gcc.

### Workaround

Various hacks are possible, but not desirable.

### Risk

low

### Test Coverage

yes

### Validation Steps

The customer validated that the patch fixes the build.

**Comment by itsjustkevin** [comment]
Approved by @jason-simmons in https://github.com/flutter/flutter/issues/96282.

**Comment by itsjustkevin** [comment]
Merged in Flutter 3.3.2.
