### ISSUE TITLE
Un-pin sqlite3 version in engine recipe

### ISSUE THREAD

**Issue by nehalvpatel** [flutter/flutter#111226]

**Comment by nehalvpatel** [comment]
This will be resolved when an alternative Obj-C doc generation tool is adopted.

**Comment by nehalvpatel** [comment]
A stopgap workaround that still uses the same doc generation tool but un-pins the sqlite3 version will be landed some time this week.

**Comment by keyonghan** [comment]
This done as well?

**Comment by nehalvpatel** [comment]
Yup, this is completed.
