### ISSUE TITLE
Move jazzy as a dependency in .ci.yaml

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#111212]
To unblock engine tree: https://github.com/flutter/flutter/issues/111193, we retrieved cipd directly in the engine recipes: https://flutter-review.googlesource.com/c/recipes/+/33681

We should move the logic to deps module to be consistent with any other deps.

**Comment by keyonghan** [comment]
@nehalvpatel Do you wan to pick up this one? It would give you a good understanding of the recipes.

**Comment by nehalvpatel** [comment]
Yes, that sounds great. I can carry this forward.

**Comment by nehalvpatel** [comment]
Closing as the CIPD workaround logic has been reverted.
