### ISSUE TITLE
(index):92 Failed to load app from service worker. Falling back to plain <script> tag.

### ISSUE THREAD

**Issue by JCzz** [flutter/flutter#111247]
I have build flutter to web as described [here][1]:

    flutter build web

serving the flutter app:

    python3 -m http.server 80

This works on localhost, but as soon as I move it to production with domain name - I get blank white screen and error:

    (index):92 Failed to load app from service worker. Falling back to plain <script> tag.

or
    
    loading from service worker timed out

Do you know what to do to get flutter web up and running in production?

  [1]: https://docs.flutter.dev/deployment/web#building-the-app-for-release
```
flutter --version
Flutter 3.3.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 4f9d92fbbd (2 days ago) • 2022-09-06 17:54:53 -0700
Engine • revision 3efdf03e73
Tools • Dart 2.18.0 • DevTools 2.15.0

```

**Comment by exaby73** [comment]
Hello @JCzz. The `base-href` argument is not for setting the domain but rather the base path of the application. What are you trying to achieve here? How are the URLs of the application supposed to look like?

**Comment by JCzz** [comment]
hi @exaby73 

Thanks for reaching out, I have change/updated the question for simplicity - just using `python3 -m http.server 80`.

Basically it is from any domain, but I am serving from Kubernetes Knative services. 
It is just serving from containers. The services generated from Knative is like `https://helloworld-go.default.mydomain.dev`

**Comment by exaby73** [comment]
What's the base href you are setting in that case?

**Comment by JCzz** [comment]
I am leaving as default, as you told.

If you have some where to deploy a container under a domain, you can just do the following:

1. `flutter build web`
2. To verify on localhost `docker run --rm -it -p 8080:80 $(docker build -q -f $DOCKERFILE .)`
Dockerfile
```
FROM alpine:3.12

ENV PYTHONUNBUFFERED=1
RUN apk add --update --no-cache python3 && ln -sf python3 /usr/bin/python
RUN python3 -m ensurepip
RUN pip3 install --no-cache --upgrade pip setuptools

WORKDIR /app
COPY ./web/ .
EXPOSE 80
WORKDIR /app
CMD ["python3", "-m", "http.server", "80"]
```
3. Now try to deploy the same container to a domain

**Comment by exaby73** [comment]
You need to copy the `./build/web` folder and not the `./web` folder. Could you try that and see if that fixes your issue?

**Comment by JCzz** [comment]
Good suggestion, but I am actually using the build/web. I have just copied it to a folder relative to my Docker.

To speed up the process, I am now referencing directly to `build/web` in my Dockerfile.

I am constantly testing this to make it work. It is so strang, I can run Flutter locally in a docker container, but as soon I deploy it to Kubernetes under a domain. Other sample sites, non-flutter works...

**Comment by exaby73** [comment]
I can't really reproduce this issue since I do not have enough knowledge to set up and use a Kuberntes Cluster (I believe that's what it's called). Labelling for further insights from the team.

**Comment by JCzz** [comment]
Ok thanks, I have tried with:

go:
```
func main() {
	handler := mux.NewRouter()
	fs := http.FileServer(http.Dir("./app/build/web/"))

	handler.PathPrefix("/").Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Access-Control-Allow-Origin", "*")
		w.Header().Set("Access-Control-Allow-Methods", "GET,PUT,PATCH,POST,DELETE")
		w.Header().Set("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept")
		fs.ServeHTTP(w, r)
	})).Methods("GET")
log.Fatal(http.ListenAndServe(":80", handler))
}
```

python3(Access-Control-Allow):
`CMD ["python3", "-m", "http.server", "80"]`

nginx:

```
user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log notice;
pid        /var/run/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout  65;

    #gzip  on;

                listen 443 ssl http2;
                server_name mydomain.com;

                include ssl/wildcard;

                add_header Access-Control-Allow-Origin $cors_origin_header always;
                add_header Access-Control-Allow-Credentials $cors_cred;
                add_header "Access-Control-Allow-Methods" "GET, POST, OPTIONS, HEAD";
                add_header "Access-Control-Allow-Headers" "Authorization, Origin, X-Requested-With, Content-Type, Accept";

                if ($request_method = 'OPTIONS' ) {
                  return 204 no-content;

    include /etc/nginx/conf.d/*.conf;
}
```

**Comment by JCzz** [comment]
https://stackoverflow.com/questions/73706498/flutter-web-not-working-when-running-on-k8s-knative-istio-metallb/73708495?noredirect=1#comment130160968_73708495

**Comment by exaby73** [comment]
@JCzz From these, where you able to find the source of the issue?

**Comment by JCzz** [comment]
@exaby73 Unfortunately not

It is so strange, I just tried with a nodejs server, as one mentioned in one of the discussions, but still the same. Please let me know if I can help  with anything. Do you have contacts to anyone who have deployed to kubernetes?

Thanks

**Comment by exaby73** [comment]
Unfortunately, the least we can do is wait for someone on the team to investigate the issue

**Comment by JCzz** [comment]
Just an update, you dont need a domain. Just expose flutter web app as a LoadBalancer/NodePort service

**Comment by JCzz** [comment]
Hi @exaby73 

Put this one on hold as I am getting more and more convinced, that this is more a network issue than it is Flutter. I will come back, and if you feel like it you can close it as you please.

**Comment by JCzz** [comment]
Not a Flutter issue -it was a network issue
