### ISSUE TITLE
GeoFire Support (Firebase)

### ISSUE THREAD

**Issue by bramvbilsen** [flutter/flutter#11121]
Manually geosorting with Firebase is a pain. GeoFire would be a convenient tool to have. Perhaps we can add this plugin to FlutterFire!

**Comment by GorillaMitts** [comment]
Yes, I use geofire in my app, and it's great. We are currently researching a switch to flutter. This would make my life much easier!

**Comment by sethladd** [comment]
Here's the current GeoFire for Flutter: https://github.com/bramvbilsen/Flutter-GeoFire

**Comment by bramvbilsen** [comment]
I have not had the chance to work on the iOS version though. I hope I'll find a mac computer that I can use for some time next week so I can start working on it!

**Comment by GorillaMitts** [comment]
Let me know if you need any help. I am new to flutter, but I really like
geofire and would like to help get it up and running reliably on both
platforms.


Curtis C. Dyal
Technical Director
FanDy Soft LLC
www.fandysoft.com

**Comment by bramvbilsen** [comment]
That would be awesome! All of the Dart and Java code are already finished, so feel free to write the iOS part if you find the time! If you have any question about the already implemented code or how I went about getting something from native to Dart, feel free to let me know!

**Comment by ch-muhammad-adil** [comment]
@bramvbilsen  any luck with iOS platform  ??

**Comment by bramvbilsen** [comment]
@ch-muhammad-adil The problem was that there was an issue with using swift in plugins when I started creating it. I stopped developing the plugin because of that. But, I did create my own geo query plugin that can be used with Flutter amd Firebase. It pretty much uses the same api as the Java version of GeoFire so go there for docs. I have not written any yet :)

**Comment by ch-muhammad-adil** [comment]
@bramvbilsen I appreciate that, I am just new to Flutter and learning things at the moment, what i have figured that there are still many plugins need to be developed for flutter.  
:)

**Comment by rlee1990** [comment]
Any news on this?

**Comment by bramvbilsen** [comment]
@rlee1990 I would suggest using Firestore. There already is a plugin for Flutter that enables geoqueries with it.

**Comment by rlee1990** [comment]
@bramvbilsen I was hoping I didn't have to since the app was done with firebase real-time database but I see i will need to Thanks.

**Comment by aniketmlk6** [comment]
@bramvbilsen Please develop this

**Comment by bramvbilsen** [comment]
@aniketmlk6  @rlee1990 The Dart code and Android code were already working months ago. It might need an update to Dart 2.0. But honestly, most of the code is done with the exception being iOS. So feel free to fork it and finish it. I really do not have time to do this rn + my project who needed this switched to Firestore so I really do not have a need for it anymore.

**Comment by kroikie** [comment]
@bramvbilsen

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/985. Any further collaboration will be done there.
