### ISSUE TITLE
Add TextFormField example to the dart api docs

### ISSUE THREAD

**Issue by branflake2267** [flutter/flutter#11126]
I think it would be handy to see an example of how to implement the TextFormField in the dart api docs. 

Maybe something like this might be nice to see...
```
new TextFormField(
  decoration: const InputDecoration(
    icon: const Icon(Icons.person),
    hintText: 'What do people call you?',
    labelText: 'Name *',
  ),
  onSaved: (String value) {},
  validator: (String value) {
    if (value.contains("@")) return "Do not use the @ char.";
    return null;
  },
);
```

**Comment by sethladd** [comment]
@Hixie would you accept this as a PR?

**Comment by Hixie** [comment]
I'm all in favour of more documentation, sure.

**Comment by shihaohong** [comment]
This was resolved with https://github.com/flutter/flutter/pull/23680
