### ISSUE TITLE
html dom dart clashes with text dart error

### ISSUE THREAD

**Issue by adityamv7** [flutter/flutter#11128]
If i use html dom.dart then an error appears in the **Text** field of the title of appbar stating that 
name Text is defined in both text.dart and dom.dart

**Comment by nanowang** [comment]
You may wanna try the following

```dart
import 'package:html/parser.dart' as html show parse;
import 'package:html/dom.dart' as html;
```

**Comment by eseidelGoogle** [comment]
What is "html dom.dart"?  Can you link to that file?

**Comment by Hixie** [comment]
What does `flutter analyze` say?

**Comment by adityamv7** [comment]
It is in html package from dart team Mr @eseidelGoogle 
https://pub.dartlang.org/packages/html

Unforunately not Mr @Hixie  but i had checked with flutter doctor there no were no upgrades available

**Comment by eseidelGoogle** [comment]
Ah, Dart supports using named imports:

```dart
import 'package:html/dom.dart' as dom;
import 'package:flutter/material.dart as material;
```

Now `material.Text` and `dom.Text` would be separate and not clash.  I recommend only giving one of them a prefix, and not both to save yourself some typing.

**Comment by Hixie** [comment]
@adityamv7 Please let us known is Eric's answer above was insufficient. Thanks!
