### ISSUE TITLE
[CP] Remove context assertion from Android platform views using Virtual Display

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#111274]
### issue_link

https://github.com/flutter/flutter/issues/110146

### Commit Hash

dfe5c9e

### Target

stable

### pr_link

https://github.com/flutter/engine/pull/36046

### Impacted Users

Android developers using affected plugins

### Impact Description

Some Android plugins that worked in Flutter 2.x completely fail to work (due to a regression in Flutter 3.0).

### Workaround

Plugin developers would have to make a significant change to their plugin, which would likely have other side effects. There is no workaround for clients of the plugins if the developers don't do that.

### Risk

low

### Test Coverage

yes

### Validation Steps

Run the example in https://github.com/flutter/flutter/issues/110146. The video should render.

**Comment by itsjustkevin** [comment]
From the issue context this seems to be a high priority fix, but the cherry pick is fairly large.  Are we assessing this as low risk @stuartmorgan?

**Comment by stuartmorgan** [comment]
Ugh, it re-targetted the branch to main and I didn't notice. Let me fix that.

**Comment by stuartmorgan** [comment]
Okay, now it should look more reasonable :)

Note SingleViewPresentation.java is the only production change; the rest is test code.

**Comment by itsjustkevin** [comment]
@stuartmorgan thank you, this one scared me a bit!

@ditman would you be the right person to take a second look?

**Comment by itsjustkevin** [comment]
Merged in Flutter 3.3.2.
