### ISSUE TITLE
Remove @SuppressWarning workaround in FlutterActivity

### ISSUE THREAD

**Issue by GaryQian** [flutter/flutter#111295]
A `@SuppressWarning` annotation was added to workaround a google3 bug (https://b.corp.google.com/issues/243609613) where the linter is not properly running against API 33.

This should be removed once b/243609613 is fixed.

**Comment by justinmc** [comment]
b/243609613 was closed last year and https://github.com/flutter/engine/pull/49093 will remove the suppressionwarning and close this issue.
