### ISSUE TITLE
No good exception when plural parsing fails in gen_l10n.

### ISSUE THREAD

**Issue by Zverik** [flutter/flutter#111293]
So this is two issues actually, but the first is the important one:

1. When building a localization file fails because of some exception, the error message does not indicate what to look for: no hint at the process (generating etc etc), no file name (like `app_no.arb`), no message key or line number.
2. When somebody makes a typo in a plural message value, or just writes a single word there, generation fails with an obscure error message.

I'd like some catching and processing for the first one, and maybe defaults with warnings for the second one.

## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=HQ626136BC --start-paused --dart-define=flutter.inspector.structuredErrors=true lib/main.dart
```

## Steps to Reproduce
1. Use generated l10n files from arb.
4. For a plural value, in some of the translations just write a plain word insted of `{plural, count, ...}`.
5. Do `flutter run` or anything that rebuilds the localizations.

## Logs

See https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/localizations/gen_l10n.dart#L285

RangeError: RangeError (end): Invalid value: Not in inclusive range 0..4: -1
```
#0      RangeError.checkValidRange (dart:core/errors.dart:356:9)
#1      _StringBase.substring (dart:core-patch/string_patch.dart:400:27)
#2      _replaceWithVariable (package:flutter_tools/src/localizations/gen_l10n.dart:299:46)
#3      _generatePluralMethod (package:flutter_tools/src/localizations/gen_l10n.dart:284:25)
#4      _generateMethod (package:flutter_tools/src/localizations/gen_l10n.dart:419:12)
#5      LocalizationsGenerator._generateBaseClassFile.<anonymous closure> (package:flutter_tools/src/localizations/gen_l10n.dart:1129:14)
#6      MappedIterator.moveNext (dart:_internal/iterable.dart:391:20)
#7      Iterable.join (dart:core/iterable.dart:431:23)
#8      LocalizationsGenerator._generateBaseClassFile (package:flutter_tools/src/localizations/gen_l10n.dart:1142:41)
#9      LocalizationsGenerator._generateCode (package:flutter_tools/src/localizations/gen_l10n.dart:1238:46)
#10     LocalizationsGenerator.writeOutputFiles (package:flutter_tools/src/localizations/gen_l10n.dart:1313:47)
#11     generateLocalizations (package:flutter_tools/src/localizations/gen_l10n.dart:69:9)
#12     GenerateLocalizationsTarget.build (package:flutter_tools/src/build_system/targets/localizations.dart:56:5)
#13     _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:839:27)
<asynchronous suspension>
#14     Future.wait.<anonymous closure> (dart:async/future.dart:521:21)
<asynchronous suspension>
#15     _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:777:32)
<asynchronous suspension>
#16     FlutterBuildSystem.buildIncremental (package:flutter_tools/src/build_system/build_system.dart:680:16)
<asynchronous suspension>
#17     ResidentRunner.runSourceGenerators (package:flutter_tools/src/resident_runner.dart:1178:18)
<asynchronous suspension>
#18     HotRunner.run (package:flutter_tools/src/run_hot.dart:374:7)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 3.0.5, on Fedora Linux 35 (KDE Plasma) 5.18.11-100.fc35.x86_64, locale ru_RU.UTF-8)
    • Flutter version 3.0.5 at /home/zverik/progr/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (8 недель назад), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /home/zverik/Android/Sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /home/zverik/progr/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✗] Linux toolchain - develop for Linux desktop
    • clang version 13.0.1 (Fedora 13.0.1-1.fc35)
    • cmake version 3.22.2
    ✗ ninja is required for Linux development.
      It is likely available from your distribution (e.g.: apt install ninja-build), or can be downloaded from https://github.com/ninja-build/ninja/releases
    • pkg-config version 1.8.0
    ✗ GTK 3.0 development libraries are required for Linux development.
      They are likely available from your distribution (e.g.: apt install libgtk-3-dev)

[✓] Android Studio (version 2021.2)
    • Android Studio at /home/zverik/progr/android-studio
    • Flutter plugin version 69.0.2
    • Dart plugin version 212.5744
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] Connected device (2 available)
    • XQ CC54 (mobile) • HQ626136BC • android-arm64 • Android 12 (API 31)
    • Linux (desktop)  • linux      • linux-x64     • Fedora Linux 35 (KDE Plasma) 5.18.11-100.fc35.x86_64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 2.0.0+29
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 18116933e77adc82f80866c928266a5b4f1ed645
### Plugins
device_info_plus-4.1.2
device_info_plus_linux-3.0.0
device_info_plus_macos-3.0.0
device_info_plus_web-3.0.0
device_info_plus_windows-4.0.0
dynamic_color-1.4.0
flutter_secure_storage-5.1.2
flutter_secure_storage_linux-1.1.1
flutter_secure_storage_macos-1.1.1
flutter_secure_storage_web-1.0.2
flutter_secure_storage_windows-1.1.2
flutter_web_auth-0.4.1
geolocator-9.0.1
geolocator_android-4.1.0
geolocator_apple-2.2.1
geolocator_web-2.1.6
geolocator_windows-0.1.1
macos_ui-1.7.4
path_provider-2.0.11
path_provider_android-2.0.20
path_provider_ios-2.0.11
path_provider_linux-2.1.7
path_provider_macos-2.0.6
path_provider_windows-2.1.3
sensors_plus-1.3.4+1
sensors_plus_web-1.1.1
share_plus-4.0.10+1
share_plus_linux-3.0.0
share_plus_macos-3.0.1
share_plus_web-3.0.1
share_plus_windows-3.0.1
shared_preferences-2.0.15
shared_preferences_android-2.0.12
shared_preferences_ios-2.1.1
shared_preferences_linux-2.1.1
shared_preferences_macos-2.0.4
shared_preferences_web-2.0.4
shared_preferences_windows-2.1.1
sqflite-2.0.3+1
url_launcher-6.1.5
url_launcher_android-6.0.17
url_launcher_ios-6.0.17
url_launcher_linux-3.0.1
url_launcher_macos-3.0.1
url_launcher_web-2.0.13
url_launcher_windows-3.0.1

**Comment by darshankawar** [comment]
Thanks for the report @Zverik 
I believe this is fixed as part of https://github.com/flutter/flutter/issues/87851 and https://github.com/flutter/flutter/pull/102431.

I see that you are on 3.0.5, but the fix is part of latest release : 3.3.0 as mentioned in release notes:

<img width="1061" alt="Screenshot 2022-09-12 at 11 47 33 AM" src="https://user-images.githubusercontent.com/67046386/189586067-84d3f78b-f7ef-41d7-90e7-fbb8d8aeb1de.png">


https://docs.flutter.dev/development/tools/sdk/release-notes/release-notes-3.3.0

I suggest you to upgrade to latest stable or master and try again to see if you still get same behavior or not.

**Comment by Zverik** [comment]
This doesn't look related: the language code is fine, it's a string inside a language file that's broken. Will test it this week with the 3.3.0.

**Comment by jmagman** [comment]
@eliasyishak be aware when you pin issues it pins it for everyone 🙂

**Comment by eliasyishak** [comment]
> @eliasyishak be aware when you pin issues it pins it for everyone 🙂

Of course it does 🤦‍♂️, back to bookmarks for me
