### ISSUE TITLE
[Engine] Flatland hit-region size can overflow when transformed (rotated/translated)

### ISSUE THREAD

**Issue by SahilMadan** [flutter/flutter#111292]
Currently, flatland external view embedder specifies a hit-region size of FLT_MAX. When rotated or translated, this region is multiplied by some transformation matrix and will overflow. This has been addressed in flatland by reducing the hit-region size, and the same should be done in Flutter engine.

**Comment by chinmaygarde** [comment]
cc @akbiggs

**Comment by SahilMadan** [comment]
For clarity, I've opened this bug so that I can attach to pull request. No action required from others yet.
