### ISSUE TITLE
Android PlatformView scrolls slowly.

### ISSUE THREAD

**Issue by toda-bps** [flutter/flutter#111268]
Android PlatformView scrolling slow since https://github.com/flutter/flutter/commit/087750f2f277c82e7e1a38cc113a49204efd9108

```
Roll Flutter Engine from 16fb19e72f88 to 9c3c233e2639 (1 revision) (#109532)
https://github.com/flutter/flutter/commit/087750f2f277c82e7e1a38cc113a49204efd9108
```

Related PR: https://github.com/flutter/engine/pull/34182

engine commit: https://github.com/flutter/engine/commit/9c3c233e2639bbb984b27937653b4335d50ee0a9
```
Fix PlatformView multiple pointer crash caused by toMotionEvent (#34182)
https://github.com/flutter/engine/commit/9c3c233e2639bbb984b27937653b4335d50ee0a9
```

---

Example: HUAWEI MediaPad M5 SHT-W09 9.1.0.360(C635E8R1P2)

Good: https://github.com/flutter/flutter/commit/20ffb32fa7ac1d378787b9ab2dc8ec5209e722cc (previous commit of https://github.com/flutter/flutter/commit/087750f2f277c82e7e1a38cc113a49204efd9108)

https://user-images.githubusercontent.com/17119410/189375618-790d9121-fd28-4455-86f6-92fc67d6db82.mov

Bad: https://github.com/flutter/flutter/commit/087750f2f277c82e7e1a38cc113a49204efd9108

https://user-images.githubusercontent.com/17119410/189375814-30e485e2-1d11-4bca-8a10-a56ac7d3c3fc.mov

---

Sample app's code:

```dart
import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

void main() => runApp(const _App());

@immutable
class _App extends StatelessWidget {
  const _App();

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(),
        body: const WebView(
          initialUrl: 'https://flutter.dev/',
          javascriptMode: JavascriptMode.unrestricted,
        ),
      ),
    );
  }
}
```

**Comment by huycozy** [comment]
Hi @toda-bps which flutter version are you using? Please provide the output of `flutter doctor -v`.

**Comment by toda-bps** [comment]
@huycozy `flutter doctor -v` with https://github.com/flutter/flutter/commit/087750f2f277c82e7e1a38cc113a49204efd9108 checked out.

```
$ flutter doctor -v
[!] Flutter (Channel unknown, 3.1.0-0.0.pre.2275, on macOS 12.5.1 21G83 darwin-x64, locale ja-JP)
    ! Flutter version 3.1.0-0.0.pre.2275 on channel unknown at /System/Volumes/Data/buildroot/flutter_master
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at https://flutter.dev/docs/get-started/install.
    ! Unknown upstream repository.
      Reinstall Flutter by following instructions at https://flutter.dev/docs/get-started/install.
    • Framework revision 087750f2f2 (4 weeks ago), 2022-08-15 09:38:17 -0400
    • Engine revision 9c3c233e26
    • Dart version 2.19.0 (build 2.19.0-96.0.dev)
    • DevTools version 2.16.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform
      update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /path/to/Library/Android/sdk
    • Platform android-32, build-tools 32.0.0
    • ANDROID_SDK_ROOT = /path/to/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode13.4.1.app/Contents/Developer
    • Build 13F100
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.71.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (3 available)
    • SHT W09 (mobile) • JJN6R18C03001065 • android-arm64  • Android 9 (API 28)
    • macOS (desktop)  • macos            • darwin-x64     • macOS 12.5.1 21G83 darwin-x64
    • Chrome (web)     • chrome           • web-javascript • Google Chrome 105.0.5195.102

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

**Comment by huycozy** [comment]
Hi @toda-bps
Could you please try upgrading to the latest Flutter stable/master channel to see if this issue still reproduces? The latest Flutter stable is `3.3.1` and the master is `3.4.0`. 

This is the demo from my device (Pixel 3a, Android 12). 

<details>
<summary>Demo</summary>


https://user-images.githubusercontent.com/104349824/189813467-d0ef86b5-e3ad-4099-bc95-b90d01c0af07.mp4


</details>

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 3.3.1, on macOS 12.5.1 21G83 darwin-x64, locale en-VN)
    • Flutter version 3.3.1 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4f9d92fbbd (31 hours ago), 2022-09-06 17:54:53 -0700
    • Engine revision 3efdf03e73
    • Dart version 2.18.0
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13E113
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2020.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.71.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.5.1 21G83 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 105.0.5195.102

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

```bash
[✓] Flutter (Channel master, 3.4.0-19.0.pre.218, on macOS 12.5.1 21G83 darwin-x64, locale en-VN)
    • Flutter version 3.4.0-19.0.pre.218 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 967b51fbcd (2 hours ago), 2022-09-12 21:32:24 -0400
    • Engine revision 2689b40c50
    • Dart version 2.19.0 (build 2.19.0-191.0.dev)
    • DevTools version 2.17.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13E113
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2020.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.71.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (5 available)
    • Pixel 3a (mobile)      • 964AY0WL20                               • android-arm64  • Android 12 (API 32)
    • iPhone (mobile)        • d9a94afe2b649fef56ba0bfeb052f0f2a7dae95e • ios            • iOS 15.5 19F77
    • iPhone 13 Pro (mobile) • 67052ED0-6AEE-4A9A-B301-EAB9874D8241     • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-4 (simulator)
    • macOS (desktop)        • macos                                    • darwin-x64     • macOS 12.5.1 21G83 darwin-x64
    • Chrome (web)           • chrome                                   • web-javascript • Google Chrome 105.0.5195.102

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by toda-bps** [comment]
I've found that I can't reproduce the problem on the Android emulator, even with master(bbc42632).

* For example: `Android SDK built for x86 64 (mobile) • emulator-5554    • android-x64    • Android 9 (API 28) (emulator)`

This issue may only occur on certain devices.

@huycozy Do you have any HUAWEI device?

**Comment by ermolaev** [comment]
you can see similar issue https://github.com/flutter/flutter/issues/106190

**Comment by huycozy** [comment]
Hi @toda-bps 
>@huycozy Do you have any HUAWEI device?

I don't have a HUAWEI device. 
I also tried running on my another device (Samsung Galaxy Tab A7 Lite, Android 12) on master channel `3.4.0-19.0.pre.245` and don't see scrolling behavior as noticeably slow as yours either. (plugin version: `webview_flutter: ^3.0.4`)

What is `webview_flutter` plugin version are you using? 
And can you please attach a timeline trace as well? Refer to guideline in: https://github.com/flutter/flutter/issues/74833#issue-795394794

**Comment by toda-bps** [comment]
> What is webview_flutter plugin version are you using?

webview_flutter: 3.0.4 
webview_flutter_android: 2.10.0

```
webview_flutter:
  dependency: "direct main"
  description:
    name: webview_flutter
    url: "https://pub.dartlang.org"
  source: hosted
  version: "3.0.4"
webview_flutter_android:
  dependency: transitive
  description:
    name: webview_flutter_android
    url: "https://pub.dartlang.org"
  source: hosted
  version: "2.10.0"
```

> And can you please attach a timeline trace as well? Refer to guideline in: https://github.com/flutter/flutter/issues/74833#issue-795394794

Here is a timeline trace using 3.4.0-19.0.pre.266.

[dart-timeline-2022-9-15_3.4.0-19.0.pre.266.json.txt](https://github.com/flutter/flutter/files/9570678/dart-timeline-2022-9-15_3.4.0-19.0.pre.266.json.txt)

Here is a timeline trace using 3.3.2.

[dart-timeline-2022-9-15_3.3.2.json.txt](https://github.com/flutter/flutter/files/9570677/dart-timeline-2022-9-15_3.3.2.json.txt)

Scrolling behavior still seems to be an issue with 3.4.0-19.0.pre.266.  
I think it's not that the scrolling is slow, but some touch events are missing and the acceleration is lacking.

**Comment by huycozy** [comment]
@toda-bps thanks for providing the detail.
I would like to summarise the issue (from your above comments) as below:

- Sample code and demo: https://github.com/flutter/flutter/issues/111268#issue-1367946293
- This issue is reproduced on the master (https://github.com/flutter/flutter/commit/bbc42632a0845e6222903b1a508f5e1400ba29fe). However, it does not reproduce on stable(3.3.1)
- This issue may only occur on certain devices: `HUAWEI MediaPad M5 SHT-W09 9.1.0.360(C635E8R1P2)`
- Plugin version: `webview_flutter: 3.0.4` and `webview_flutter_android: 2.10.0`
- Timeline trace: https://github.com/flutter/flutter/issues/111268#issuecomment-1247424081

Labeling this issue for further investigation/insight from the team. Thank you!

**Comment by stuartmorgan** [comment]
@mengdouer do you have any thoughts on why this change would affect performance?
/cc @dnfield and @wangying3426 who reviewed in case either of you have thought as well.

**Comment by dnfield** [comment]
Ther'es probably something going wrong with the way the touch is getting tracked now.

The PR seemed to make sense because there's a case where reporting the wrong kind of event to the system results in problems.

@iskakaushik worked on this once upon a time I think, and may know more.

**Comment by mengdouer** [comment]
This is not obvious after testing it on my HUAWEI mobile phone. It may only be reproduced on Huawei tablets. Now I don't know why it will affect performance and I will continue to pay attention to it.

**Comment by orestesgaolin** [comment]
I know it may sound odd, but I tried to record stuttering of a webview in Android Flutter app with `scrcpy` but while the lower framerate is clearly visible when not recording, the moment I run `scrcpy -r videos/webview-2.10.4.mp4` it switches to fluent native-level framerate, not different from opening the page in Chrome. I tried to reproduce this using webview_flutter example app, but it doesn't happen there.

| No scrcpy/adb connection | Running scrcpy |
| ----- | ----- |
| https://user-images.githubusercontent.com/16854239/202657837-dd316339-6ae4-4afd-b3a5-68f95ebb9cab.mp4 | https://user-images.githubusercontent.com/16854239/202657890-1abec66a-84b0-4cc9-8eda-41d69f1ddb9d.mp4 |




Details:
- Android 13, Samsung S21
- webview_flutter_android 2.10.4
- running in release mode
- initial page https://flutter.dev
- the webview is put inside a `TabBarView` like follows:

```dart
TabBarView(
  physics: const NeverScrollableScrollPhysics(),
  children: [
    WebView(
      backgroundColor: Color(0xFFFFFFFF),
      onWebViewCreated: (controller) {
      
      },
      onPageStarted: (url) {
       
      },
      javascriptMode: JavascriptMode.unrestricted,
      initialUrl: 'https://flutter.dev', 
    ),
    WebView(
      backgroundColor: Color(0xFFFFFFFF),
      javascriptMode: JavascriptMode.unrestricted,
      onWebViewCreated: (controller) {
       
      },
      onPageStarted: (url) {
     
      },
      initialUrl: 'https://flutter.dev',
    ),
  ],
)
```

```
[✓] Flutter (Channel stable, 3.3.7, on macOS 12.6 21G115 darwin-arm, locale pl-PL)
    • Flutter version 3.3.7 on channel stable at /Users/dominik/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e99c9c7cd9 (2 weeks ago), 2022-11-01 16:59:00 -0700
    • Engine revision 857bd6b74c
    • Dart version 2.18.4
    • DevTools version 2.15.0

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/dominik/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.73.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.52.0

[✓] Connected device (3 available)
    • SM G991B (mobile) • R5CR617G51T • android-arm64  • Android 13 (API 33)
    • macOS (desktop)   • macos       • darwin-arm64   • macOS 12.6 21G115 darwin-arm
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 107.0.5304.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

**Comment by toda-bps** [comment]
I've confirmed that this issue still exists in [3.7.0](https://github.com/flutter/flutter/tree/3.7.0).

By the way, the Android API has `MotionEvent.getPointerCount()`.

* https://developer.android.com/reference/android/view/MotionEvent#getPointerCount()

I think the correct fix is to change `touch.pointerCount` to `trackedEvent.getPointerCount()` instead of changing `trackedEvent.getAction()` to `touch.action`.

Also, for [`pointerProperties` and `pointerCoords`](https://github.com/flutter/engine/blob/9c3c233e2639bbb984b27937653b4335d50ee0a9/shell/platform/android/io/flutter/plugin/platform/PlatformViewsController.java#L631-L632) when using trackedEvent, is it correct to use "MotionEvent.PointerCoords" and "MotionEvent.PointerProperties"?

* https://developer.android.com/reference/android/view/MotionEvent.PointerProperties
* https://developer.android.com/reference/android/view/MotionEvent.PointerCoords

**Comment by toda-bps** [comment]
I pushed a patch that I myself have been using for the last 10 months.

https://github.com/toda-bps/engine/commit/e98d51859f6a08b53a28bf03dcefff9559bb78b2

This code solves my problem.

However, I have not reproduced the original issues addressed in https://github.com/flutter/engine/pull/34182 in my environment, so I am not sure if this fix solves all issues including original issues.

Does anyone have an environment where I can test this issue and my code?

**Comment by toda-bps** [comment]
I have confirmed that this issue has been fixed at https://github.com/flutter/flutter/commit/51633fe95c6e5232ed2f6d47426e67d04623dec1 with my device.

thank you very much ☺️
