### ISSUE TITLE
[in_app_purchase] Cancel android/ios subscription

### ISSUE THREAD

**Issue by wryczko** [flutter/flutter#111369]
## Use case

I have received an email from google saying that from now on applications with option to buy a subscription should also implement an in app feature, which would give user an easy way to unsubscribe. 

![Capture](https://user-images.githubusercontent.com/3628429/189534847-5bf3af30-ca9e-4e54-ae65-4572582203c4.PNG)

Currently the only way for user to cancel subscription is to go to google account options outside of my application.

## Proposal

Implement a method to cancel and pause subscription (nonconsumable) for both android and ios.

**Comment by darshankawar** [comment]
There's already similar issue open: https://github.com/flutter/flutter/issues/58834, please follow-up in it for further updates.
Closing this as a duplicate.
