### ISSUE TITLE
Flutter engine should not use codeset as Locale.scriptCode on Linux

### ISSUE THREAD

**Issue by Yesterday17** [flutter/flutter#111341]
### Description
On linux desktop, Locales are in the form `language[_territory][.codeset][@modifier]`.
https://github.com/flutter/engine/blob/ce4156d519b94989684f508542b7cf644b6e7d67/shell/platform/linux/fl_engine.cc#L79-L112

Flutter engine parsed the string, but assigned `codeset` to `scriptCode`:
https://github.com/flutter/engine/blob/ce4156d519b94989684f508542b7cf644b6e7d67/shell/platform/linux/fl_engine.cc#L142

Codeset is not a valid `scriptCode` in most cases. In addition, on modern linux systems, it may contain `-`(`UTF-8`), which may break some locale parsers based on regular expression.

### Related
https://github.com/Tienisto/slang/issues/102

**Comment by gspencergoog** [comment]
cc @robert-ancell

**Comment by robert-ancell** [comment]
There is a good discussion about mapping Unix locales to BCP-47 in https://wiki.openoffice.org/wiki/LocaleMapping
