### ISSUE TITLE
Framework tree closed on canvaskit skia gold diffs

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#111398]
At top of tree https://github.com/flutter/flutter/commit/7ad47233a9a38b2847f6a4f4cbcd90690adab10e

Logs at the top of: https://ci.chromium.org/p/flutter/builders/prod/Linux%20web_canvaskit_tests_5

cc @yjbanov

**Comment by zanderso** [comment]
Since the Engine roll is quite far behind, I'd suggest only disabling the flaky datepicker tests while debugging this while everything else can move forward.

**Comment by zanderso** [comment]
The test has been disabled and the tree is back open, so downgrading this to P3. @yjbanov feel free to close this and track getting the tests reenabled elsewhere if that's more convenient.

**Comment by yjbanov** [comment]
The test has been disabled
