### ISSUE TITLE
Need a way to verify flaky golden test fixes

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#111325]
Currently if a golden test is flaky we just skip it, e.g.:

* https://github.com/flutter/flutter/pull/87589
* https://github.com/flutter/flutter/pull/111114

Let's say the flake is fixed (perhaps in Skia or in the engine). Skia Gold has a handy feature that, for a given test, shows how stable generated goldens are by giving each golden variant a unique color. For example, in the screenshot below the black, orange, and green circles indicate that the test generated three variations of a golden, i.e. it is flaky:

<img width="98" alt="Screen Shot 2022-09-02 at 1 51 39 PM" src="https://user-images.githubusercontent.com/211513/189461337-62bd5f84-9b6b-4b8b-a88e-7a8c5f188cd7.png">

A non-flaky golden test will show a continuous string of dots of the same color, e.g.:

<img width="323" alt="Screen Shot 2022-09-09 at 5 28 18 PM" src="https://user-images.githubusercontent.com/211513/189461416-82f0d9a2-2259-4dbb-961c-7811455059d3.png">

Unfortunately, we can't use this feature because when we skip a test we stop sending to Skia Gold entirely. The only option is to speculatively unskip the test and hope that it's no longer flaky. The cost of a mistake is closed tree, P0s, wasted time, and other sadness.

## Feature request

Add an optional parameter to `matchesGoldenFile`: `{ bool isFlaky = false }`. When set to `true` we continue generating the golden, and we continue sending it to Skia Gold, but we don't fail the test. This has the same effect as skipping it, but it allows us to monitor it over time, and when the flake is fixed the `isFlaky` argument can be removed.

Additionally, `flutter test` could print a warning to the console about the flaky golden, and we can include these in our technical debt calculation.

**Comment by Piinks** [comment]
For reference, there has been some discussion in this thread: https://discord.com/channels/608014603317936148/1017957368182624297

**Comment by rrousselGit** [comment]
On that note, it might be reasonable to accept a certain % of variation.  
Currently a test would fail, even if there's a 0.1% difference between images. An error margin could help

I also remember seeing some image diff projects using machine learning to detect false positives in golden diffs (as that's not a Flutter-specific problem). Maybe that's something to look into

**Comment by yjbanov** [comment]
@rrousselGit We allow fuzzy matching of images for the HTML renderer on the web, where we have limited control over how browsers render pixels, and they are frequently flaky. However, for Skia, including CanvasKit, we expect pixel-perfect output. With a couple of exceptions all our goldens are stable. We treat the exceptions as bugs.

We also found that using percentage was quite risky. Sometimes a golden would be made of a lot of empty space around and/or inside the content, so even 0.1% could turn out quite big. Instead, we use absolute pixel counts and color deltas.

**Comment by yjbanov** [comment]
Reopening since the fix was rolled back.

**Comment by Piinks** [comment]
I am un-assigning myself right now as I am not actively working on this issue. Landing https://github.com/flutter/flutter/pull/115004 would close this again, but it is blocked on #93263. We can revisit #115004 after that is resolved.

**Comment by ricardoamador** [comment]
It looks like https://github.com/flutter/flutter/pull/115004 is not blocking this issue but that this is blocked directly by https://github.com/flutter/flutter/issues/93263. Is that correct?

**Comment by Piinks** [comment]
Can confirm! #115004 would fix this issue, but is blocked on #93263

**Comment by yjbanov** [comment]
@harryterkelsen is overhauling how we take screenshots, so I'm going to hold off on anything screenshot related for now.
