### ISSUE TITLE
Add Non-Dart Dependencies on Flutter(Desktop) build

### ISSUE THREAD

**Issue by ljfreelancer88** [flutter/flutter#111355]
I have a situation where I need to use Python3 and pip to install packages to leverage Flutter Desktop.

Kindly add a feature where I can define on build time that I need non-dart dependencies. Then when a client install that piece of software, it will get(example: install python, pip install <package>, curl -sSL <URL> | bash... etc.)

Thank you in advance.

**Comment by stuartmorgan** [comment]
Runtime installation of software is out of scope for Flutter. This is something that interested members of the community could build as a package.
