### ISSUE TITLE
[pigeon] simplify apple platform tests with `pod lib lint`

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#111399]
https://github.com/flutter/packages/pull/2587 introduced a simpler model for platform tests using `pod lib lint`, used by macos.  We should migrate the iOS and iOS swift tests to use the same model which would reduce the number of files in those tests greatly.

**Comment by jmagman** [comment]
Plugins used to use `pod lib lint` to run the native unit tests, see the `test_specs` and scripting introduced in flutter/plugins#2115 and then moved to https://github.com/flutter/plugin_tools/pull/69.  `webview_flutter` flutter/plugins#2445 and `in_app_purchase` flutter/plugins#2125 also used `test_specs` 

This was replaced by the `xctest` command in https://github.com/flutter/plugin_tools/pull/116 and totally removed in flutter/plugins#4005.

**Comment by gaaclarke** [comment]
> Plugins used to use `pod lib lint` to run the native unit tests, see the `test_specs` and scripting introduced in [flutter/plugins#2115](https://github.com/flutter/plugins/pull/2115) and then moved to [flutter/plugin_tools#69](https://github.com/flutter/plugin_tools/pull/69). `webview_flutter` [flutter/plugins#2445](https://github.com/flutter/plugins/pull/2445) and `in_app_purchase` [flutter/plugins#2125](https://github.com/flutter/plugins/pull/2125) also used `test_specs`
> 
> This was replaced by the `xctest` command in [flutter/plugin_tools#116](https://github.com/flutter/plugin_tools/pull/116) and totally removed in [flutter/plugins#4005](https://github.com/flutter/plugins/pull/4005).

I'm not sure that will help us in our case.  If we can avoid having a flutter plugin at all it reduces the footprint and complexity of the platform tests.  I'll pick stuarts brain next time I'm talking with him to see what he thinks since he has a foot in both of these worlds.

**Comment by jmagman** [comment]
Just giving you bread crumb trail so you don't need to reinvent the wheel.

**Comment by stuartmorgan** [comment]
> If we can avoid having a flutter plugin at all it reduces the footprint and complexity of the platform tests.

Capturing from discussion elsewhere: I would much rather we have a plugin and then test it all the usual ways we test plugins. This has in particular come up in discussion of integration tests: https://github.com/flutter/flutter/issues/111505

So I would prefer to close this issue.

**Comment by stuartmorgan** [comment]
I'm doing the restructuring discussed in https://github.com/flutter/flutter/issues/111505, unifying Pigeon's platform test scaffolding structuring with the platform test structure we use for all of our plugins, so I'm going to close this.
