### ISSUE TITLE
ImageStream : Bad state: Stream has been disposed. 

### ISSUE THREAD

**Issue by Tom3652** [flutter/flutter#111342]
## Steps to Reproduce

I have no idea how to reproduce it but it seems quite frequent as i have 30 errors like this in my Crashlytics dashboard from my users in `release`.

I guess this must have something to do with the disposal of an `Image` widget that is badly handled from Flutter `3.x.x`.
I had not this error in Flutter `2.x.x` and had not changed any code. I am simply displaying `Image` in `ListView.builder` and in some page and when the user back to another page (`Navigator.pop`) i guess this must dispose the `ListView` and maybe the images. 

![Capture d’écran 2022-09-10 à 10 57 15](https://user-images.githubusercontent.com/32631467/189476415-9e908066-9501-4ccd-b758-1b541e8d306a.png)

**Expected results:** 

Not see this error.

**Actual results:** 

Sounds like the `ImageStream` is not recreated, like if the `Image` was still in memory while it's expected to be evicted from memory and completely reset. 

<details>
  <summary>Logs</summary>

```
Bad state: Stream has been disposed. An ImageStream is considered disposed once at least one listener has been added and subsequently all listeners have been removed and no handles are outstanding from the keepAlive method. To resolve this error, maintain at least one listener on the stream, or create an ImageStreamCompleterHandle from the keepAlive method, or create a new stream for the image.
```

```
[✓] Flutter (Channel stable, 3.3.1, on macOS 12.5.1 21G83 darwin-x64, locale fr-FR)
    • Flutter version 3.3.1 on channel stable at /Users/foxtom/Desktop/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4f9d92fbbd (3 days ago), 2022-09-06 17:54:53 -0700
    • Engine revision 3efdf03e73
    • Dart version 2.18.0
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/foxtom/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F100
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.71.0)
    • VS Code at /Users/foxtom/Desktop/Visual Studio Code.app/Contents
    • Flutter extension version 3.46.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.5.1 21G83 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 105.0.5195.102

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by hm122** [comment]
I am seeing this error in Sentry too. First seen since the Flutter upgrade at 3.3.0/1. 

```
Bad state: Stream has been disposed.
An ImageStream is considered disposed once at least one listener has been added and subsequently all listeners have been removed and no handles are outstanding from the keepAlive method.
To resolve this error, maintain at least one listener on the stream, or create an ImageStreamCompleterHandle from the keepAlive method, or create a new stream for the image.
```

**Comment by darshankawar** [comment]
Thanks for the report @Tom3652 
A similar issue was fixed as part of https://github.com/flutter/flutter/issues/77576 and https://github.com/flutter/flutter/pull/94902 and was available in stable 2.10. version:

<img width="872" alt="Screenshot 2022-09-12 at 12 14 01 PM" src="https://user-images.githubusercontent.com/67046386/189589588-ec4930f7-5e83-42b6-b6c2-c0c6966090e5.png">

Can you take a look at that issue and probably https://github.com/flutter/flutter/issues/77576#issuecomment-795022467 which has repro steps and see if using it, the same error is triggered ?

**Comment by meomap** [comment]
I've got same errors after upgrading to stable `3.3.0`. My previous version was `3.0.5` and I've never seen it before.

For me, only several android devices are affected 
```
SM-X205 139 crashes
SM-A715F 54
RMX2180 20
RMX2040 7
SM-A716S 3
```

**Comment by Tom3652** [comment]
I can't reproduce it with the above comment @darshankawar 
I must add compared to the sample code in the comment that i am not doing anything myself. 

Flutter is supposed to do the job (disposing and evicted images that are not no longer on the screen when scrolling a `ListView.builder`) and it was working fine before `3.x.x`. 
If this is now not a default behavior anymore, this would be nice to know about it in the documentation (such as handling the image lifecycle ourselves)

In my beta app version in flutter `2.10.x`, i have never had not such error and my app code didn't change after upgrading to `3.x.x` regarding images.

**Comment by darshankawar** [comment]
Thanks for the feedback @Tom3652 . I see there's similar issue reported https://github.com/flutter/flutter/issues/110953 and OP has given potential solutions on how to avoid it, so I suggest you to follow-up in it, share your findings in it for further updates.

@meomap Same for you. You may share your observation in that issue, so that we will have one single issue to track for the error reported.

Closing this in favor of https://github.com/flutter/flutter/issues/110953

Note: I have informed [huycozy](https://github.com/huycozy) to revisit and label that issue for team to look at.
