### ISSUE TITLE
Draggable "feedback" not working as expected.

### ISSUE THREAD

**Issue by saurabhdhingra** [flutter/flutter#111367]
Hi I am trying to make a draggable widget and the "feedback" widget is not working as expected. Some screenshots to explain the issue : -

1. The draggable when not being dragged. 
![Simulator Screen Shot - iPhone 13 - 2022-09-11 at 18 18 15](https://user-images.githubusercontent.com/75309640/189528492-d3cfc00e-8972-4e2d-99e1-92cb2d2831e6.png)

2. When it is being dragged. 
![Simulator Screen Shot - iPhone 13 - 2022-09-11 at 18 18 17](https://user-images.githubusercontent.com/75309640/189528495-cfb688f4-465b-44d3-b890-1ee10b5268af.png)

Here's the code I am using to produce my draggable widget : - 

```
Widget cell(
    double height,
    double width,
  ) {
    return Padding(
      padding: EdgeInsets.all(width * 0.02),
      child: Draggable<String>(
        data: "Schedule",
        // ignore: sort_child_properties_last
        child: Container(
          height: height * 0.1202 - width * 0.04,
          width: width * 0.36,
          decoration: BoxDecoration(
            color: Colors.blue[200],
            borderRadius: const BorderRadius.all(
              Radius.circular(20.0),
            ),
          ),
          child: const Center(child: Text("Schedule")),
        ),
        feedback: Container(
          height: height * 0.1202 - width * 0.04,
          width: width * 0.36,
          decoration: BoxDecoration(
            color: Colors.blue[200],
            borderRadius: const BorderRadius.all(
              Radius.circular(20.0),
            ),
          ),
          child: const Center(child: Text("Schedule")),
        ),
        childWhenDragging: DottedBorder(
          borderType: BorderType.RRect,
          radius: const Radius.circular(20),
          dashPattern: const [10, 10],
          color: Colors.grey,
          strokeWidth: width * 0.005,
          child: Container(
            height: height * 0.1202 - width * 0.05,
            width: width * 0.35,
            decoration: const BoxDecoration(
              color: Colors.white,
              borderRadius: BorderRadius.all(
                Radius.circular(20.0),
              ),
            ),
          ),
        ),
      ),
    );
  }

```

**Comment by navaronbracke** [comment]
What do you mean by `the "feedback" widget is not working as expected`? Are you talking about the red text with a yellow underline? You'll likely need to wrap the feedback widget in a `DefaultTextStyle`.

**Comment by exaby73** [comment]
Hello @saurabhdhingra. Thank you for filing this issue. Can you please provide the following information?

- A [complete and minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).
- The output of `flutter doctor -v`
- The output of `flutter run-v`

**Comment by saurabhdhingra** [comment]
Hi guys, thanks for taking a look at my problem. I just had to add the default text style in the text widget. I was confused because it's the first time I have come across such a problem. 

I would request @exaby73 to check why the Text widget given as child to the child of the feedback property is behaving like this. 

Thank you.

**Comment by exaby73** [comment]
Without any logs, it would be tough to investigate this issue. On a hunch though, you were probably missing a `Scaffold` in the widget tree which provided a `DefaultTextStyle `.
