### ISSUE TITLE
Flutter root implement flutter aar module

### ISSUE THREAD

**Issue by feeza10250** [flutter/flutter#111335]
## Use case

I can run flutter aar module from flutter root.

Initially I tried the add to flutter native method, but modified it via chanel to go start activity (FlutterActivity), define FlutterEngine and set an entrypoint that does not use main , it did not find the specified entrypoint.

*** I don't call main because it will look at root's main

**Comment by darshankawar** [comment]
@feeza10250 
Can you provide `flutter doctor -v`, a minimal code sample that shows the actual result and detailed proposal that will help to resolve the current behavior ?

**Comment by feeza10250** [comment]
@darshankawar 
flutter project current old version 1.22.6

<img width="772" alt="Screen Shot 2565-09-12 at 13 15 13" src="https://user-images.githubusercontent.com/20635185/189585570-ca115d43-854b-4887-9f89-f00cd28a92d3.png">

**Comment by darshankawar** [comment]
> flutter project current old version 1.22.6

You are on obsolete version of Flutter. Latest version is 3.3.1. I recommend to upgrade to latest version and try your scenario once again to see if it already works or not.
If not, write in comments and I'll reopen it. Closing for now.
