### ISSUE TITLE
[webview_flutter] Can't copy text via Javascript navigator.clipboard.writeText

### ISSUE THREAD

**Issue by Aulig** [flutter/flutter#111388]
## Steps to Reproduce

1. Run the code sample on Android
2. Click the "Copy Text" button

**Expected results:** 
The text should be copied to the clipboard.

**Actual results:** 
Log message: [INFO:CONSOLE(0)] "Uncaught (in promise) NotAllowedError: Write permission denied."

Here's a relevant Stackoverflow post with a solution: https://stackoverflow.com/questions/61243646/clipboard-api-call-throws-notallowederror-without-invoking-onpermissionrequest

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {

    return const MaterialApp(
      home: SafeArea(
        child: WebView(
          initialUrl: "https://www.w3schools.com/howto/howto_js_copy_clipboard.asp",
          javascriptMode: JavascriptMode.unrestricted,
        ),
      ),
    );
  }
}
```

</details>

<details>
  <summary>Logs</summary>

Full log is too long for github, so here's the only relevant line:
```
[   +1 ms] I/chromium(16542): [INFO:CONSOLE(0)] "Uncaught (in promise) NotAllowedError: Write permission denied.", source: https://www.w3schools.com/howto/tryit.asp?filename=tryhow_js_copy_clipboard (0)
```

```
Analyzing webviewtest...
No issues found! (ran in 3.4s)
```

```
[√] Flutter (Channel stable, 3.3.0, on Microsoft Windows [Version 10.0.19044.1889], locale de-DE)
    • Flutter version 3.3.0 on channel stable at D:\Programme\Flutter\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffccd96b62 (13 days ago), 2022-08-29 17:28:57 -0700
    • Engine revision 5e9e0e0aa8
    • Dart version 2.18.0
    • DevTools version 2.15.0

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc4)
    • Android SDK at D:\Programme\AndroidSDK
    • Platform android-33, build-tools 31.0.0-rc4
    • ANDROID_HOME = D:\Programme\AndroidSDK
    • ANDROID_SDK_ROOT = D:\Programme\AndroidSDK
    • Java binary at: D:\Programme\AndroidStudio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop for Windows (Visual Studio Build Tools 2019 16.11.7)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
    • Visual Studio Build Tools 2019 version 16.11.31911.196
    • Windows 10 SDK version 10.0.19041.0
    X Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop development with C++" workload, and include these components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK

[√] Android Studio (version 2021.2)
    • Android Studio at D:\Programme\AndroidStudio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] IntelliJ IDEA Community Edition (version 2020.2)
    • IntelliJ at D:\Programme\IntelliJ IDEA Community Edition 2020.2
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19044.1889]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 105.0.5195.102
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 105.0.1343.27

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

</details>

**Comment by exaby73** [comment]
Hello @Aulig. This looks like an issue with permissions in the browser itself, and not Flutter. Is this issue reproducible in a non-Flutter application?

**Comment by Aulig** [comment]
No, with a regular desktop browser (Chrome, Firefox) this works fine.

With mobile Chrome, it only works on this page https://www.w3schools.com/howto/howto_js_copy_clipboard.asp but not https://www.w3schools.com/howto/tryit.asp?filename=tryhow_js_copy_clipboard - I have adjusted the sample code accordingly.

In the Android flutter webview neither work though.

**Comment by exaby73** [comment]
Could you provide a [complete and minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) so that I can verify the issue?

**Comment by Aulig** [comment]
Sure, what else do you need aside from the code sample in the OP? Use that as the main.dart and add the webview dependency in pubspec of course but that should be all

**Comment by exaby73** [comment]
Basically, it would be better if your code same could include the necessary files for the web site itself. I simple html and js file that could be used to reproduce it locally instead of relying on a 3rd party website that could change it's code/layout in the future making this issue unactionable.

**Comment by Aulig** [comment]
Ah I understand, thanks for the clarification. I've tried doing that but unfortunately copying text to the clipboard requires that the website is served via https, which isn't possible for local files I think. See https://stackoverflow.com/questions/51805395/navigator-clipboard-is-undefined

Here's a minimal HTML sample based on the w3schools page in case that gets deleted:
```html
  <!DOCTYPE html>
  <html>
  <head>
  <title>Page Title</title>
  </head>
  <body>
    <input type="text" value="Hello World" id="myInput">
    
    <button onclick="copyText()">Copy text</button> 
    <script>
      function copyText() {
        var copyText = document.getElementById("myInput");
      
        copyText.select();
        copyText.setSelectionRange(0, 99999);
      
        navigator.clipboard.writeText(copyText.value);
      
        alert("Copied the text: " + copyText.value);
      } 
    </script>
  </body>
  </html>
```

**Comment by exaby73** [comment]
## Triage report

I can reproduce this issue. But I am not sure if this is something in Flutter's control or if this is dependent on the implementing native webview. Labelling for further insights from the team.

### Logs

```
I/chromium( 5770): [INFO:CONSOLE(0)] "Uncaught (in promise) NotAllowedError: Write permission denied.", source: https://www.w3schools.com/howto/howto_js_copy_clipboard.asp (0)
```

**Comment by Aulig** [comment]
Sounds good, thank you! This Stackoverflow post makes it seem like it could be solved by webview_flutter I think: https://stackoverflow.com/questions/61243646/clipboard-api-call-throws-notallowederror-without-invoking-onpermissionrequest

Not 100% sure though.

**Comment by stuartmorgan** [comment]
There's no way to make navigator.clipboard work in the plugin if it doesn't work in webview itself; we're just wrapping the webview.

The workaround you've linked to involves adding a different interface that's manually set up to do clipboard actions. That's not something we would add to the plugin itself (and even if we did, it wouldn't be very useful since nobody would know that this alternate API was there), but there's no reason you can't add it in your own code by setting up a JavaScript channel for the webview, and implementing it via Flutter's `Clipboard` class.

**Comment by Aulig** [comment]
Thanks for the quick feedback and the tip with the javascript channel. I'll go for that then!
