### ISSUE TITLE
Webview disable pinch zoom but prevent scroll

### ISSUE THREAD

**Issue by Yash-Techniverse** [flutter/flutter#111397]
I have to disable webviw zoom on web platform so for that I'm using webviewx package there is one property SourceType.urlBypass I use that and then I can call js method but that not load proper formatted content on webview. And when try to use SourceType.url then content load proper formatted but I can't call js method on that so I'm not able to disable webview pich zoom in and zoom out.
Is there anything, So using that I can disable Pinch zoom in and zoom out of webview.
And one thing is disable zoom in zoom out only, not scroll.

**Comment by danagbemava-nc** [comment]
Webviewx is a third-party plugin. Any issues related to that should be reported on their repo. 

You may also ask this question on StackOverflow to see if anyone in the community has done what you're trying to do. 

Closing from here as this is an issue with a third-party plugin. 

Thank you
