### ISSUE TITLE
Stepper CONTINUE and CANCEL buttons cannot be configured.

### ISSUE THREAD

**Issue by andryfailli** [flutter/flutter#11133]
## Steps to Reproduce

Place a stepper inside a flutter hello world app.
You cannot configure the text inside CONTINUE and CANCEL buttons.
Two parameters _continueButton_ and _cancelButton_ in the constructor can be useful.
At least, add a parameter to hide the buttons.

## Flutter Doctor

```
[√] Flutter (on Microsoft Windows [Versione 6.1.7601], locale it-IT, channel alpha)
    • Flutter at C:\Users\Andrea\git\flutter
    • Framework revision d36e2f6191 (3 weeks ago), 2017-06-21 15:09:10 -0700
    • Engine revision b0dee695ec
    • Tools Dart version 1.24.0-dev.6.7

[√] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at C:\Users\Andrea\AppData\Local\Android\sdk
    • Platform android-25, build-tools 25.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[√] Android Studio (version 2.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Gradle version 3.2
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[√] Connected devices
    • XT1068 • ZX1D22Q4BC • android-arm • Android 6.0 (API 23)
```

**Comment by eseidelGoogle** [comment]
Are you looking to localize those buttons (if so, that's a more general issue in our framework). Or are you looking to replace them with unrelated text?

**Comment by andryfailli** [comment]
You're right, the localization issue maybe should be treated as a general topic for all the framework.
In my case, I'm only prototyping, so localization is not an important issue for now.
Let's focus on removing / replacing the CONTINUE and CANCEL buttons.

I am trying to build an horizontal stepper like [this](https://storage.googleapis.com/material-design/publish/material_v_11/assets/0B7WCemMG6e0VWHR4aEhxMjctVzg/components_acux_stepper_feedback.mp4) with buttons arranged in a row fixed at bottom of the screen for back and forth navigation.
In this case, the CONTINUE and CANCEL buttons should be replaced by NEXT and BACK buttons.

Looking at [stepper.dart on line 500](https://github.com/flutter/flutter/blob/c55097da7d0d3b0165c5988ff7adb3eaed614a61/packages/flutter/lib/src/material/stepper.dart#L500), I see that the `_buildHorizontal()` function invokes `_buildVerticalControls()` not `_buildHorizontalControls()` as I expected, infact `_buildVerticalControls(),` does not exists.

I've implemented `_buildHorizontalControls()` with bottom fixed back and forth buttons on my flutter fork, see PR [https://github.com/flutter/flutter/pull/11165](11165) and the result is shown in the attachment 

![droid screen-1](https://user-images.githubusercontent.com/324620/28118242-962bb6e0-6710-11e7-8744-c4a7377d7e72.png)

I've also added `onStepBack` callback as an optional parameter.

**Comment by Nik99** [comment]
Any news on this ?

**Comment by soliven25** [comment]
I did like below. Is there any better way?

controlsBuilder: (BuildContext context, {VoidCallback onStepContinue, VoidCallback onStepCancel}) {
            return Row(
              children: <Widget>[
                Container(          
                  child: null,
                ),
                Container(
                  child: null,
                ),
              ],
            );
          },

**Comment by komputerboy** [comment]
Hi all,
Any news how to change button Continue and Cancel text in Stepper widget?

**Comment by keshava19** [comment]
A parameter to hide the continue and cancel button will be useful.

Use case would be, when you want to display data in a step.

**Comment by evanave** [comment]
Found this elsewhere, but now I can't find the source again...
`controlsBuilder: (BuildContext context, {VoidCallback onStepContinue, VoidCallback onStepCancel}) {
            return Row(
              mainAxisSize: MainAxisSize.max,
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: <Widget>[
                RaisedButton(
                  onPressed: onStepCancel,
                  child: const Text('Back!'),
                ),
                RaisedButton(
                  onPressed: onStepContinue,
                  child: const Text('Next!'),
                ),
              ],
            );
          }`

**Comment by rafalolszewski94** [comment]
Source for the example is on Flutter docs: https://docs.flutter.io/flutter/material/Stepper/controlsBuilder.html

But, it lacks some configuration, like conditionally show controls on each step.
Example: hide controls on last step (as you are finishing the steps)

**Comment by yvanvds** [comment]
@rafalolszewski94 Nothing keeps you from implementing that logic within the controlsBuilder. For example: 

```dart
controlsBuilder: (BuildContext context, {VoidCallback onStepContinue, VoidCallback onStepCancel}) {
        return Padding(
          padding: const EdgeInsets.only(top: 16.0),
          child: Row(
            mainAxisSize: MainAxisSize.max,
            mainAxisAlignment: MainAxisAlignment.start,
            children: <Widget>[
              _currentStep == 4 // this is the last step
              ? 
                RaisedButton.icon(
                icon: Icon(Icons.create),
                onPressed: _createProject,
                label: Text('CREATE'),
                color: Colors.green,
              )
              : RaisedButton.icon(
                icon: Icon(Icons.navigate_next),
                onPressed: onStepContinue,
                label: Text('CONTINUE'),
                color: Colors.pink,
              ),
              FlatButton.icon(
                icon: Icon(Icons.delete_forever),
                label: const Text('CANCEL'),
                onPressed: onStepCancel,
              )
            ],
          ),
        );
      },
```

**Comment by EJunit** [comment]
thanks!

**Comment by LongKhoa0706** [comment]
> I did like below. Is there any better way?
> 
> ```dart
> controlsBuilder: (BuildContext context, {VoidCallback onStepContinue, VoidCallback onStepCancel}) {
>     return Row(
>         children: <Widget>[
>             Container(
>                 child: null,
>             ),
>             Container(
>                 child: null,
>             ),
>         ],
>     );
> },
> ```

it't worked :D

**Comment by krisztianodor** [comment]
If you manipulate stuffs step specifically in the controlsBuilder, it can cause unwanted flashes at step changes.

For example if you'd like to display the cancel button only if currentStep > 0 and you are on step 0, then when you are moving to step 1, the cancel button is being displayed for a few ms.

I'd suggest that you should disable the controlsbuilder completely with a fake widget:

`controlsBuilder: (BuildContext context, {VoidCallback onStepContinue, VoidCallback onStepCancel}) => SizedBox.shrink(),`

 and implement your own controls directly in the step content parameter.

**Comment by PrakashNaidu2662** [comment]
> I did like below. Is there any better way?
> 
> ```dart
> controlsBuilder: (BuildContext context, {VoidCallback onStepContinue, VoidCallback onStepCancel}) {
>     return Row(
>         children: <Widget>[
>             Container(
>                 child: null,
>             ),
>             Container(
>                 child: null,
>             ),
>         ],
>     );
> },
> ```

Thank you. It solved my problem.

**Comment by a7medpa** [comment]
> You're right, the localization issue maybe should be treated as a general topic for all the framework.
> In my case, I'm only prototyping, so localization is not an important issue for now.
> Let's focus on removing / replacing the CONTINUE and CANCEL buttons.
> 
> I am trying to build an horizontal stepper like [this](https://storage.googleapis.com/material-design/publish/material_v_11/assets/0B7WCemMG6e0VWHR4aEhxMjctVzg/components_acux_stepper_feedback.mp4) with buttons arranged in a row fixed at bottom of the screen for back and forth navigation.
> In this case, the CONTINUE and CANCEL buttons should be replaced by NEXT and BACK buttons.
> 
> Looking at [stepper.dart on line 500](https://github.com/flutter/flutter/blob/c55097da7d0d3b0165c5988ff7adb3eaed614a61/packages/flutter/lib/src/material/stepper.dart#L500), I see that the `_buildHorizontal()` function invokes `_buildVerticalControls()` not `_buildHorizontalControls()` as I expected, infact `_buildVerticalControls(),` does not exists.
> 
> I've implemented `_buildHorizontalControls()` with bottom fixed back and forth buttons on my flutter fork, see PR [https://github.com/flutter/flutter/pull/11165](11165) and the result is shown in the attachment
> 
> ![droid screen-1](https://user-images.githubusercontent.com/324620/28118242-962bb6e0-6710-11e7-8744-c4a7377d7e72.png)
> 
> I've also added `onStepBack` callback as an optional parameter.

I know this is an old post but I was wondering how you got the buttons to sticky in the controlsBuilder like that? I looked at your pull request but I can't manage to figure that out.

**Comment by craiglabenz** [comment]
Closing this issue, as `controlsBuilder` exposes customization options.
