### ISSUE TITLE
package:flutter/src/rendering/object.dart': Failed assertion: line 1627 pos 12: '_debugCanPerformMutations': is not true.

### ISSUE THREAD

**Issue by ahad21** [flutter/flutter#111344]
<details>
<summary>logs</summary>

```
======== Exception caught by animation library =====================================================
The following assertion was thrown while notifying listeners for AnimationController:
'package:flutter/src/rendering/object.dart': Failed assertion: line 1627 pos 12: '_debugCanPerformMutations': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      RenderObject.markNeedsLayout (package:flutter/src/rendering/object.dart:1627:12)
#3      RenderBox.markNeedsLayout (package:flutter/src/rendering/box.dart:2370:11)
#4      new RenderAnimatedSize.<anonymous closure> (package:flutter/src/rendering/animated_size.dart:99:9)
#5      AnimationLocalListenersMixin.notifyListeners (package:flutter/src/animation/listener_helpers.dart:155:19)
#6      AnimationController._animateToInternal (package:flutter/src/animation/animation_controller.dart:602:9)
#7      AnimationController.forward (package:flutter/src/animation/animation_controller.dart:461:12)
#8      RenderAnimatedSize._layoutStable (package:flutter/src/rendering/animated_size.dart:303:19)
#9      RenderAnimatedSize.performLayout (package:flutter/src/rendering/animated_size.dart:224:9)
#10     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#11     RenderPositionedBox.performLayout (package:flutter/src/rendering/shifted_box.dart:437:14)
#12     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#13     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#14     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1376:11)
#15     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#16     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#17     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#18     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#19     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#20     RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:213:28)
#21     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#22     RenderSliverEdgeInsetsPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:137:12)
#23     RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:371:11)
#24     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#25     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:510:13)
#26     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1580:12)
#27     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1489:20)
#28     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1757:7)
#29     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:887:18)
#30     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:504:19)
#31     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:892:13)
#32     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:370:5)
#33     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1146:15)
#34     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1083:9)
#35     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:997:5)
#39     _invoke (dart:ui/hooks.dart:151:10)
#40     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308:5)
#41     _drawFrame (dart:ui/hooks.dart:115:31)
(elided 5 frames from class _AssertionError and dart:async)
The AnimationController notifying listeners was: AnimationController#390e4(⏮ 1.000; paused)
====================================================================================================

======== Exception caught by animation library =====================================================
The following assertion was thrown while notifying listeners for AnimationController:
'package:flutter/src/rendering/object.dart': Failed assertion: line 1627 pos 12: '_debugCanPerformMutations': is not true.
```
</details>

**Comment by ahad21** [comment]
app> flutter doctor -v
[√] Flutter (Channel stable, 3.0.5, on Microsoft Windows [Version 10.0.22000.856], locale en-US)
    • Flutter version 3.0.5 at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (9 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at C:\Users\h\AppData\Local\Android\sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.2.0)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.2.32505.173
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] VS Code (version 1.71.0)
    • VS Code at C:\Users\h\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.48.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22000.856]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 105.0.5195.102
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 105.0.1343.33

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Comment by ahad21** [comment]
flutter run --verbose
[  +48 ms] executing: [C:\src\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +41 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] f1875d570e39de09040c8f79aa13cc56baab8db1
[        ] executing: [C:\src\flutter/] git tag --points-at f1875d570e39de09040c8f79aa13cc56baab8db1
[  +30 ms] Exit code 0 from: git tag --points-at f1875d570e39de09040c8f79aa13cc56baab8db1
[        ] 3.0.5
[   +5 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +23 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\src\flutter/] git ls-remote --get-url origin
[  +21 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +71 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref HEAD
[  +24 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +52 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +35 ms] executing: C:\Users\h\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +33 ms] List of devices attached
[   +5 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +6 ms] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +47 ms] No supported devices connected.
[  +20 ms] The following devices were found, but are not supported by this project:
           Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22000.856]
           Chrome (web)      • chrome  • web-javascript • Google Chrome 105.0.5195.102
           Edge (web)        • edge    • web-javascript • Microsoft Edge 105.0.1343.33
           If you would like your app to run on web or windows, consider running `flutter create .` to generate projects for these platforms.
           
[   +6 ms] "flutter run" took 172ms.
[  +13 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:484:7)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1298:5)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1183:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #6      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
           <asynchronous suspension>
           #7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #8      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #9      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #11     main (package:flutter_tools/executable.dart:94:3)
           <asynchronous suspension>
           
           
[ +259 ms] ensureAnalyticsSent: 257ms
[   +3 ms] Running shutdown hooks
[   +1 ms] Shutdown hooks complete
[   +1 ms] exiting with code 1

**Comment by ahad21** [comment]
══╡ EXCEPTION CAUGHT BY ANIMATION LIBRARY ╞═════════════════════════════════════════════════════════
                    The following assertion was thrown while notifying listeners for AnimationController:
                    'package:flutter/src/rendering/object.dart': Failed assertion: line 1627 pos 12:
                    '_debugCanPerformMutations': is not true.
                    
                    Either the assertion indicates an error in the framework itself, or we should provide substantially
                    more information in this error message to help you determine and fix the underlying cause.
                    In either case, please report this assertion by filing a bug on GitHub:
                      https://github.com/flutter/flutter/issues/new?template=2_bug.md
                    
                    When the exception was thrown, this was the stack:
                    #2      RenderObject.markNeedsLayout (package:flutter/src/rendering/object.dart:1627:12)
                    #3      RenderBox.markNeedsLayout (package:flutter/src/rendering/box.dart:2370:11)
                    #4      new RenderAnimatedSize.<anonymous closure> (package:flutter/src/rendering/animated_size.dart:99:9)
                    #5      AnimationLocalListenersMixin.notifyListeners (package:flutter/src/animation/listener_helpers.dart:155:19)
                    #6      AnimationController._animateToInternal (package:flutter/src/animation/animation_controller.dart:602:9)
                    #7      AnimationController.forward (package:flutter/src/animation/animation_controller.dart:461:12)
                    #8      RenderAnimatedSize._layoutStable (package:flutter/src/rendering/animated_size.dart:303:19)
                    #9      RenderAnimatedSize.performLayout (package:flutter/src/rendering/animated_size.dart:224:9)
                    #10     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
                    #11     RenderPositionedBox.performLayout (package:flutter/src/rendering/shifted_box.dart:437:14)
                    #12     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
                    #13     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
                    #14     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1376:11)
                    #15     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
                    #16     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
                    #17     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
                    #18     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
                    #19     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
                    #20     RenderSliverList.performLayout.advance (package:flutter/src/rendering/sliver_list.dart:249:18)
                    #21     RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:281:12)
                    #22     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
                    #23     RenderSliverEdgeInsetsPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:137:12)
                    #24     RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:371:11)
                    #25     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
                    #26     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:510:13)
                    #27     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1580:12)
                    #28     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1489:20)
                    #29     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1757:7)
                    #30     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:887:18)
                    #31     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:504:19)
                    #32     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:892:13)
                    #33     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:370:5)
                    #34     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1146:15)
                    #35     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1083:9)
                    #36     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:997:5)
                    #40     _invoke (dart:ui/hooks.dart:151:10)
                    #41     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308:5)
                    #42     _drawFrame (dart:ui/hooks.dart:115:31)
                    (elided 5 frames from class _AssertionError and dart:async)
                    
                    The AnimationController notifying listeners was:
                      AnimationController#d9803(⏮ 1.000; paused)
                    ════════════════════════════════════════════════════════════════════════════════════════════════════
[  +19 ms]
           Another exception was thrown: 'package:flutter/src/rendering/object.dart': Failed assertion: line 1627 pos 12: '_debugCanPerformMutations': is not
true.
[        ]
           Another exception was thrown: 'package:flutter/src/rendering/object.dart': Failed assertion: line 1627 pos 12: '_debugCanPerformMutations': is not
true.
[        ]
           Another exception was thrown: 'package:flutter/src/rendering/object.dart': Failed assertion: line 1627 pos 12: '_debugCanPerformMutations': is not
true.
[        ]
           Another exception was thrown: 'package:flutter/src/rendering/object.dart': Failed assertion: line 1627 pos 12: '_debugCanPerformMutations': is not
true.
[        ]
           Another exception was thrown: 'package:flutter/src/rendering/object.dart': Failed assertion: line 1627 pos 12: '_debugCanPerformMutations': is not
true.

**Comment by danagbemava-nc** [comment]
Hi @ahad21,

A newer version of flutter was recently released. Can you upgrade to the latest version of flutter to see if you still experience this issue? 

If you do, please provide the updated output of `flutter doctor -v` and a complete minimal reproducible code sample. 

Thank you

**Comment by ahad21** [comment]
I think the exact error is. 

======== Exception caught by widgets library =======================================================
The following assertion was thrown while applying parent data.:
Incorrect use of ParentDataWidget.

The ParentDataWidget Expanded(flex: 1) wants to apply ParentData of type FlexParentData to a RenderObject, which has been set up to accept ParentData of incompatible type StackParentData.

Usually, this means that the Expanded widget has the wrong ancestor RenderObjectWidget. Typically, Expanded widgets are placed directly inside Flex widgets.
The offending Expanded is currently placed inside a Stack widget.

The ownership chain for the RenderObject that received the incompatible parent data was:
  RepaintBoundary ← Lottie ← FutureBuilder<LottieComposition> ← LottieBuilder ← Expanded ← Visibility ← Stack ← Center ← Builder ← MediaQuery ← ⋯
When the exception was thrown, this was the stack:
#0      RenderObjectElement._updateParentData.<anonymous closure> (package:flutter/src/widgets/framework.dart:5960:11)
#1      RenderObjectElement._updateParentData (package:flutter/src/widgets/framework.dart:5977:6)
#2      RenderObjectElement.attachRenderObject (package:flutter/src/widgets/framework.dart:5999:7)

**Comment by danagbemava-nc** [comment]
Hi @ahad21, the error you've posted above is different from the initial one you reported. The error you've posted above is because you've used an Expanded as a direct child of a Stack. `Expanded` is only meant to be used in `Row`, `Column` or `Flex`.
