### ISSUE TITLE
Un-pin url_launcher_android in flutter/flutter

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#111304]
PR with broken build tests: https://github.com/flutter/flutter/pull/111197/files#diff-9aeff568c87b1d587222c343afb84ef72fc07e0692d50ecb3de670e5606f9505R46

I believe it is this change: https://github.com/flutter/plugins/pull/6194. Note, something similar happened in https://github.com/flutter/flutter/issues/109397 with path_provider_android, and what happened was that the change was reverted upstream and a new version released.

I imagine we will eventually need to find a way to get the migrated versions of these plugins passing flutter/flutter CI.

**Comment by christopherfujino** [comment]
I will work around this by pinning url_launcher_android so that the pub autoroller can continue

**Comment by christopherfujino** [comment]
cc @GaryQian and @stuartmorgan

**Comment by GaryQian** [comment]
These gradle bumps that skip many version have been causing us pain elsewhere as well. It'll take a slow process to eventually get everything upgraded and passing. We should probably just revert for now and hold off on dependabot gradle bumps

**Comment by stuartmorgan** [comment]
Why are we reverting public packages instead of just pinning in the CI?

**Comment by stuartmorgan** [comment]
> These gradle bumps that skip many version have been causing us pain elsewhere as well. It'll take a slow process to eventually get everything upgraded and passing.

If we keep reverting because of flutter/flutter CI, how will we make progress on this?

Unless we think this will affect clients other that flutter/flutter CI it seems like pinning allows us to make progress for everything else with minimal impact.

**Comment by christopherfujino** [comment]
> > These gradle bumps that skip many version have been causing us pain elsewhere as well. It'll take a slow process to eventually get everything upgraded and passing.
> 
> If we keep reverting because of flutter/flutter CI, how will we make progress on this?
> 
> Unless we think this will affect clients other that flutter/flutter CI it seems like pinning allows us to make progress for everything else with minimal impact.

So I am pinning: https://github.com/flutter/flutter/pull/111309. I'm ok with not reverting provided that work on eventually landing the newer versions with the new gradle is prioritized. Eventually a pinned dependency will hold back other packages with shared transitive dependencies from being upgraded.

**Comment by stuartmorgan** [comment]
Have we root-caused either this or the previous case yet to understand what exactly broke and why? We should definitely prioritize that to make sure we understand client effects and paths forward.

**Comment by stuartmorgan** [comment]
@GaryQian Could you take a look at what exactly the issue was, so we know what we need to do before making future plugin gradle version changes?

**Comment by stuartmorgan** [comment]
Re-titling and re-labeling since at this point it looks this is an issue with updating flutter/flutter example projects rather than a problem with the plugin itself.
