### ISSUE TITLE
The argument type 'Object?' can't be assigned to the parameter type 'String'.

### ISSUE THREAD

**Issue by iiamElina** [flutter/flutter#111361]
The argument type 'Object?' can't be assigned to the parameter type 'String'. Ln46
The argument type 'Object?' can't be assigned to the parameter type 'Widget?'. Ln49

```
import 'package:flutter/material.dart';

import '../widgets/main_drawer.dart';
import './favorites_screen.dart';
import './categories_screen.dart';
import '../models/meal.dart';

class TabsScreen extends StatefulWidget {
  final List<Meal> favoriteMeals;

  TabsScreen(this.favoriteMeals);

  @override
  _TabsScreenState createState() => _TabsScreenState();
}

class _TabsScreenState extends State<TabsScreen> {
  late List<Map<String, Object>> _pages;
  int _selectedPageIndex = 0;

  @override
  void initState() {
    _pages = [
      {
        'page': CategoriesScreen(),
        'title': 'Categories',
      },
      {
        'page': FavoritesScreen(widget.favoriteMeals),
        'title': 'Your Favorite',
      },
    ];
    super.initState();
  }

  void _selectPage(int index) {
    setState(() {
      _selectedPageIndex = index;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(_pages[_selectedPageIndex]['title']),
      ),
      drawer: MainDrawer(),
      body: _pages[_selectedPageIndex]['page'],
      bottomNavigationBar: BottomNavigationBar(
        onTap: _selectPage,
        backgroundColor: Theme.of(context).primaryColor,
        unselectedItemColor: Colors.white,
        selectedItemColor: Theme.of(context).accentColor,
        currentIndex: _selectedPageIndex,
        // type: BottomNavigationBarType.fixed,
        items: [
          BottomNavigationBarItem(
            backgroundColor: Theme.of(context).primaryColor,
            icon: const Icon(Icons.category),
            label: Text('Categories') as String,
          ),
          BottomNavigationBarItem(
            backgroundColor: Theme.of(context).primaryColor,
            icon: const Icon(Icons.star),
            label: const Text('Favorites') as String,
          ),
        ],
      ),
    );
  }
}

```

**Comment by superciccio** [comment]
` label: const Text('Favorites') as String,` ->  ` label:'Favorites',`

**Comment by iiamElina** [comment]
> ` label: const Text('Favorites') as String,` -> ` label:'Favorites',`

it doesn't work :(

**Comment by superciccio** [comment]
sorry the problem is here, 
     `   title: Text(_pages[_selectedPageIndex]['title']),`
and
` _pages[_selectedPageIndex]['page']`

the IDE you'r using should give an hint on the solution. basically **_pages[_selectedPageIndex]['title']** it doesnt know that will return a String so you can do as String 
 and for **_pages[_selectedPageIndex]['page']** same, it doenst know it will be a Widget.
 
 I hope that helps!

**Comment by iiamElina** [comment]
> sorry the problem is here, ` title: Text(_pages[_selectedPageIndex]['title']),` and ` _pages[_selectedPageIndex]['page']`
> 
> the IDE you'r using should give an hint on the solution. basically **_pages[_selectedPageIndex]['title']** it doesnt know that will return a String so you can do as String and for **_pages[_selectedPageIndex]['page']** same, it doenst know it will be a Widget.
> 
> I hope that helps!

as Widget work but as String not :(
i stiil have error on this: Text(_pages[_selectedPageIndex]['title']),

**Comment by iiamElina** [comment]
> sorry the problem is here, ` title: Text(_pages[_selectedPageIndex]['title']),` and ` _pages[_selectedPageIndex]['page']`
> 
> the IDE you'r using should give an hint on the solution. basically **_pages[_selectedPageIndex]['title']** it doesnt know that will return a String so you can do as String and for **_pages[_selectedPageIndex]['page']** same, it doenst know it will be a Widget.
> 
> I hope that helps!


thank you it's done <3
