### ISSUE TITLE
[in_app_purchase] The app is using old version of billing client

### ISSUE THREAD

**Issue by PawlikMichal25** [flutter/flutter#111368]
I'm using the newest (3.0.7) version of [in_app_purchase](https://pub.dev/packages/in_app_purchase) plugin, but I'm getting following warning in the Developer Console:

> We've detected that this app is using an old version of Google Play Billing. From 1 November 2022, all app updates must use Billing Library version 4 or newer.

Screenshot:
<img width="950" alt="Screenshot 2022-09-11 at 10 44 50" src="https://user-images.githubusercontent.com/15315707/189519117-79bb022e-443d-477a-b927-3b2516956920.png">

I see that library is using 5.0.0 of billing client https://github.com/flutter/plugins/blob/main/packages/in_app_purchase/in_app_purchase_android/android/build.gradle#L56 but when I ran APK analyzer on my app bundle I saw in AndroidManifest:
```
        <meta-data
            android:name="com.google.android.play.billingclient.version"
            android:value="3.0.2" />
```

I'm not overriding billing client dependency in my app's build.gradle and the app is using `targetSdkVersion 32`.
<details>
  <summary>flutter doctor -v</summary>
  
  
  ```
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.5.1 21G83 darwin-x64, locale en-PL)
    • Flutter version 3.0.5 at /Users/michal/Dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (9 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/michal/Library/Android/sdk
    • Platform android-32, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2022.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 70.0.5
    • Dart plugin version 222.3739.24

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.5.1 21G83 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 105.0.5195.102

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
  ```
  
</details>

**Question:**
- Is this a bug in `in_app_purchase` library?
- Should I somehow override the billingclient.version or ignore the warning in Developer Console?

**Comment by stuartmorgan** [comment]
See https://github.com/flutter/flutter/issues/110742#issuecomment-1233695204 for upgrade instructions.

Closing as a duplicate.
