### ISSUE TITLE
[video_player] Green bar on the side of screen with video_player flutter

### ISSUE THREAD

**Issue by innovatoraakash** [flutter/flutter#111358]
There is some green sidebar in some of the video in video_player flutter. It works fine in mobile but green bar appears when played on android tv.
![image](https://user-images.githubusercontent.com/35760466/189517265-aea814fe-cd50-4aed-afe5-a2ba8a66d75e.png)

My code sample

```
class VideoWidget extends StatelessWidget {
  const VideoWidget({Key? key, required this.controller}) : super(key: key);
  final VideoPlayerController controller;

  @override
  Widget build(BuildContext context) {
    return Container(alignment: Alignment.topCenter, child: buildVideo());
  }

  Widget buildVideo() => Stack(
        fit: StackFit.expand,
        children: <Widget>[
          buildVideoPlayer(),
        ],
      );

  Widget buildVideoPlayer() => buildFullScreen(
        child: AspectRatio(
          aspectRatio: controller.value.aspectRatio,
          child: VideoPlayer(controller),
        ),
      );

  Widget buildFullScreen({
    required Widget child,
  }) {
    final size = controller.value.size;
    final width = size.width;
    final height = size.height;
  
    return FittedBox(
      fit: BoxFit.fill,
      child: SizedBox(width: width,height: height, child: child),
    );
  }
} 
```
Flutter version: 3.0.2 ,
 Video Player version:2.4.5,
 Box  Android version: 10 and 11.1 ,
Tested Android box model: X96Q and MBOX

**Comment by superciccio** [comment]
just a quick thing to try, can you compare `final width = size.width;` with `MediaQuery.of(context).size.width`

**Comment by innovatoraakash** [comment]
> width

I have tried all the usecase but there is nothing to do with MediaQuery.of(context).size.width

**Comment by moffatman** [comment]
Likely an issue with device hardware decoder. Does it happen on all video files?

**Comment by innovatoraakash** [comment]
> Likely an issue with device hardware decoder. Does it happen on all video files?

@moffatman  there is no such error with NativeVideoView package but all other popular player like video_player, Chewie gives green bar on some of the video but not in all case

**Comment by huycozy** [comment]
Hi @innovatoraakash
I see there are some open issue addressing the case you described #46460, #55090 (most similar), #99273. Also, please take a look at https://github.com/flutter/flutter/issues/99273#issuecomment-1206830011 which refers to #85583 and notified that it's has been fixed on master channel. 

Closing this issue as a duplicate, so please follow up on it for further updates. You can leave there your comment and react an upvote to the original comment will help to raise the issue. Thank you!
