### ISSUE TITLE
[shared_preferences] Reload instance

### ISSUE THREAD

**Issue by TheCarpetMerchant** [flutter/flutter#111345]
Please add a method to reload the data from the disk.

Use case : workmanager updating data, which needs to be available in the app.

**Comment by stuartmorgan** [comment]
That is what the `reload` method does.

Closing as the requested functionality already exists.

**Comment by TheCarpetMerchant** [comment]
Note : It seems I am fucking blind. Sorry, Stuart, thanks for the help.
