### ISSUE TITLE
Expose a mounted-like flag on BuildContext

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#111488]
The popular `use_build_context_synchronously` lint suggests to check for `mounted` before using the `context` after an asynchronous gap. However, `mounted` only exists on `StatefullWidget`s. At the same time, `StatelessWidget`s suffer under the same problem: The `context` can become invalid after an asynchronous gap and there is currently no way to check whether it is still valid since there is no `mounted` property. A work-around is to turn the `StatelessWidget` into a `StatefulWidget`.

We should expose some kind of a property on `BuildContext` directly to check whether the context is still valid to simplify usage of `context` after an asynchronous gaps in these use cases.

**Comment by goderbauer** [comment]
If we decide to do that, we will also have to update the `use_build_context_synchronously` lint to account for this new valid usage. cc @pq

**Comment by chunhtai** [comment]
Some APIs in flutter pass context to different objects, which can't use the statefulWidget workaround. TextSelectionOverlay, RouteInformationParser are some of those examples.

I think adding a flag can be useful in those cases.
