### ISSUE TITLE
Update `Slider` to support Material 3

### ISSUE THREAD

**Issue by darrenaustin** [flutter/flutter#111451]
As part of the [Material 3 specification](https://m3.material.io/components/sliders/overview) there are updates to slider's  visuals:

<img width="400" alt="unnamed-3" src="https://user-images.githubusercontent.com/19588/189829701-c7a7da87-4128-4c09-b69b-63f653fcb44a.png">

We should update the `Slider` widget to support this Material 3 look and tokens.

**Comment by TahaTesser** [comment]
Can I take this?

**Comment by darrenaustin** [comment]
@TahaTesser thanks for volunteering. This one may be a bit more involved as the slider is pretty complicated. If you have any issues let me or @Piinks know and we can try to help.

**Comment by TahaTesser** [comment]
Update:
Making progress on this, aiming to file PR by next week.

**Comment by TahaTesser** [comment]
Update:
Need to do some fine tweaks and write tests.

**Comment by TahaTesser** [comment]
This needs https://github.com/flutter/flutter/pull/112922 to be fixed.

**Comment by TahaTesser** [comment]
https://github.com/flutter/flutter/issues/113367 fixes overlay issues on desktop for M3 support.

**Comment by TahaTesser** [comment]
Update:
Writing test (I found out there is no test for all the default color values, there is one that does test colors when using a theme).
Aiming to file a PR by tomorrow.

**Comment by TahaTesser** [comment]
https://github.com/flutter/flutter/pull/114079 landed today.
Working on part 2, which will close this issue.
Aiming to file a PR by tomorrow.
