### ISSUE TITLE
Add Snackbar width property to SnackbarThemeData

### ISSUE THREAD

**Issue by RedRozio** [flutter/flutter#111419]
## Use case

On for example flutter web on desktop, the snackbar is fullwidth, which looks off as 90% of the snackbar is just empty. To fix this I had to add the width like 400 to every snackbar in my app. By adding this prop to the SnackbarThemeData, this could be standard through the app.

Else the snackbar could have a minimumFit property or something, that shrinks the snackbar to the minimum size for the content.

## Proposal

The current solution introduces boilerplate and looks off. Introduce a width property on the SnackbarThemeData or a minimumWidth prop that shrinks the snackbar.

Thank you Flutter for amazing work! <3

**Comment by exaby73** [comment]
Hello @RedRozio. Thanks you for filing this request. Labelling for further insights from the team.
