### ISSUE TITLE
[tool_crash] StateError: Bad state: No context with the running Dart application.

### ISSUE THREAD

**Issue by Platton96** [flutter/flutter#111471]
## Command
```
flutter run -d chrome --web-renderer html --web-hostname localhost --web-port 9999 --dart-define COUNTRY_CODE=NL --dart-define BRAND=telenet --dart-define CONFIG_SERVICE_BASE_URL=http://localhost:3333/baseurl --dart-define ENVIRONMENT=preprod --dart-define OS=tizen --web-renderer html --dart-define DEBUG_USERS=true
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
StateError: Bad state: No context with the running Dart application.
```
#0      RemoteDebuggerExecutionContext.id (package:dwds/src/debugging/execution_context.dart:55:7)
<asynchronous suspension>
#1      AppInspector._getExtensionRpcs (package:dwds/src/debugging/inspector.dart:538:20)
<asynchronous suspension>
#2      AppInspector._initialize (package:dwds/src/debugging/inspector.dart:97:34)
<asynchronous suspension>
#3      AppInspector.initialize (package:dwds/src/debugging/inspector.dart:160:5)
<asynchronous suspension>
#4      ChromeProxyService.createIsolate (package:dwds/src/services/chrome_proxy_service.dart:216:18)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 2.10.3, on macOS 12.4 21F79 darwin-x64, locale en-BY)
    • Flutter version 2.10.3 at /Users/Siarhei_Kulbeda/fvm/versions/2.10.3
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (7 months ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/Siarhei_Kulbeda/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /Users/Siarhei_Kulbeda/Desktop/projects/horizon_x/scripts/web/chrome_unsafe.sh

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.70.1)
    • VS Code at /Users/Siarhei_Kulbeda/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (3 available)
    • AOSP TV on x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • macOS (desktop)         • macos         • darwin-x64     • macOS 12.4 21F79 darwin-x64
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 105.0.5195.102

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 4.45.5700+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: master
**Creation framework version**: 2fe9623c363a8404dd804f47e7fe09c360f4f49a
### Plugins
connectivity_plus-2.1.0
connectivity_plus_linux-1.1.0
connectivity_plus_macos-1.2.4
connectivity_plus_tizen-1.1.0
connectivity_plus_web-1.2.3
connectivity_plus_windows-1.2.2
device_info_plus-2.1.0
device_info_plus_linux-2.1.1
device_info_plus_macos-2.2.3
device_info_plus_tizen-1.1.0
device_info_plus_web-2.1.0
dynatrace_flutter_plugin
firebase_analytics-8.3.1
firebase_core-1.6.0
firebase_core_web-1.7.1
firebase_crashlytics-2.1.1
firebase_performance-0.7.0
flutter_acpanalytics-2.0.1
flutter_acpcore-2.0.0
flutter_inappwebview-5.3.2
flutter_keyboard_visibility-5.0.3
flutter_keyboard_visibility_web-2.0.0
flutter_local_notifications-9.0.0-dev.2
flutter_web_auth
geocoding-2.0.1
geolocator-8.2.0
geolocator_android-3.1.8
geolocator_apple-2.2.1
geolocator_web-2.1.6
geolocator_windows-0.1.1
horizon_accessibility
horizon_ad_tracking
horizon_analytics
horizon_chromecast
horizon_device_info
horizon_display_mode
horizon_in_app_flow
horizon_offline
horizon_platform_migration
horizon_player
horizon_sim_info
horizon_viper
horizon_voice_recognition
in_app_review-2.0.3
launch_review-3.0.1
location-4.3.0
location_web-3.1.1
motion_sensors
network_info_plus-2.1.2
network_info_plus_linux-1.1.0
network_info_plus_macos-1.3.0
network_info_plus_tizen-1.1.2
network_info_plus_web-1.0.1
network_info_plus_windows-1.0.2
orientation-1.3.0
package_info_plus-1.3.0
package_info_plus_linux-1.0.5
package_info_plus_macos-1.3.0
package_info_plus_tizen-1.0.1
package_info_plus_web-1.0.5
path_provider-2.0.2
path_provider_linux-2.1.5
path_provider_macos-2.0.0
path_provider_tizen-2.0.2
path_provider_windows-2.0.7
permission_handler-8.3.0
secure_storage
shared_preferences-2.0.6
shared_preferences_cpe
shared_preferences_ios
shared_preferences_linux-2.1.1
shared_preferences_macos-2.0.4
shared_preferences_web-2.0.0
shared_preferences_windows-2.1.1
sqflite-2.0.2+1
sqlite3_flutter_libs-0.5.0
tv_framework
url_launcher-6.1.4
url_launcher_android-6.0.17
url_launcher_ios-6.0.17
url_launcher_linux-3.0.1
url_launcher_macos-3.0.1
url_launcher_web-2.0.4
url_launcher_windows-3.0.1
video_player-2.1.10
video_player_web-2.0.12

**Comment by danagbemava-nc** [comment]
Hi @Platton96, this issue was previously reported and was tracked in https://github.com/flutter/flutter/issues/95916.
It has since been fixed and the fix is available on the latest version of flutter. 

I'll be closing this issue since it has already been fixed on the latest version of flutter.
If you still experience this issue on the master channel or later versions of flutter, kindly file a new issue.

Thank you!
