### ISSUE TITLE
Platform specific text selection handle

### ISSUE THREAD

**Issue by alardizabal** [flutter/flutter#11148]
The current TextFormField text selection handle is Android-inspired. It would make the experience feel more native if on iOS, the text selection handle appeared as in the below screenshot... The handles visually are most noticeable, but the cut/copy/paste, etc. options, if made to look more native as well, would be even better.

![img_2180](https://user-images.githubusercontent.com/3614291/28045495-7d14e606-65ab-11e7-9afd-2330770a07e8.PNG)

**Comment by eseidelGoogle** [comment]
@xster or @cbracken may be interested in this?

**Comment by xster** [comment]
#9507 is actually needed to submit this fix too. Since collapsed selections in iOS just shows a cursor bar with no draggable handle like Android, it would be too difficult to move the cursor around without the long-press to show magnifier affordance.

**Comment by xster** [comment]
There's a number of follow-up polish for text selection for both platforms opened in:
#11274, #11261, #11254, #9507

But this main issue is complete
