### ISSUE TITLE
How to deploy on the LAN with flutter web?

### ISSUE THREAD

**Issue by fayfive** [flutter/flutter#111439]
I develop the web client app with flutter.
I need to deploy it on the LAN not internet. That means the server and the client can't connect the internet.
But I find that it should connect to the `https://unpkg.com/canvaskit-wasm@0.33.0/bin/canvaskit.wasm``https://unpkg.com/canvaskit-wasm@0.33.0/bin/canvaskit.js` and `https://fonts.gstatic.com/s/roboto/v20/KFOmCnqEu92Fr1Me5WZLCzYlKw.ttf`
How to pack all the file when I `flutter build web`?

**Comment by exaby73** [comment]
Hello @fayfive.

I see that the `build/web` includes the `canvaskit.wasm` file but it's still being download from unpkg. A workaround for what you're trying to do is to use the HTML renderer by running `flutter build web --web-renderer html`. There are no calls to any external URLs in my testing (with the default counter app).

As for changing the source of `canvaskit.wasm` from unpkg to the local bundled one, I'll label for further insights from the team. Thank you for filing this issue.

**Comment by fayfive** [comment]
`flutter build web --web-renderer html` works well

**Comment by yjbanov** [comment]
For now, the HTML renderer (`--web-renderer=html`) is the best option. You can configure Flutter Web to use the bundled version of CanvasKit (https://github.com/flutter/engine/blob/06fe761f60a0fcf1c72e4220f31c9b5030022c89/lib/web_ui/lib/src/engine/configuration.dart#L13). However, font fallbacks still come from fonts.google.com, so you'd need to supply a sufficient coverage of fonts with the app. We're working on fixing fonts too, but today there's no good support for local fonts.

**Comment by yjbanov** [comment]
I'm going to close this issue, since our existing issues already cover the LAN use-case.
