### ISSUE TITLE
send message to whatsapp group.

### ISSUE THREAD

**Issue by AbodiSadiqGitHub** [flutter/flutter#111409]
I want to send a message to whatsapp group.
I tried but it open the whatsapp but does not bring the message.
this is my code:

void openwhatsapp(String body) async {
    var whatsappNumber = phoneNumber;
    var whatsappURl_android = "https://chat.whatsapp.com/JiATE6rTObME5UXacTIfcw?text=hello";
      if (await canLaunch(whatsappURl_android)) {
        await launch(whatsappURl_android);
      } else {
        //  SnackBar: whatsapp no installed
    }
  }

my device is android

I need help, please.

**Comment by stuartmorgan** [comment]
The `url_launcher` plugin simply passes the URL to the host system; it has no control over what the action taken from that point is. If the URL is being passed to WhatsApp but not doing the correct thing from there, you'll need to report that to the WhatsApp developers.

**Comment by AbodiSadiqGitHub** [comment]
First, Thanks alot for answer.

If i send to phone number it works well.
But if i send to group link like above, it open the whatsapp without take the parameter.
I want the right way to open group and send parameter.

If you want my anydesk number I will give you.
