### ISSUE TITLE
[Impeller] Programmatically invoke Metal frame captures.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#111421]
Currently, a slow frame has to be captured manually in the Xcode GPU frame debugger for further analysis. This gets tedious and sometimes the frame rate is not consistent (even with the raster cache disabled). Metal allows for the [programmatic capture of GPU workloads](https://developer.apple.com/documentation/metal/debugging_tools/capturing_gpu_command_data_programmatically?language=objc). Impeller must be able to capture problematic frames for offline analysis.

**Comment by luckysmg** [comment]
I think this func has been added by flutter/engine#36499. Maybe this issue can be closed^_^
