### ISSUE TITLE
Update `BottomSheet` to support Material 3

### ISSUE THREAD

**Issue by darrenaustin** [flutter/flutter#111448]
As part of the [Material 3 specification](https://m3.material.io/components/bottom-sheets/overview) there are updates to bottom sheet's  visuals:

<img width="400" alt="unnamed-1" src="https://user-images.githubusercontent.com/19588/189825600-d2a8a8ba-b3d9-483c-9d45-edfcdb06e89d.png">

We should update the `BottomSheet` widget to support this Material 3 look and tokens.

**Comment by guidezpl** [comment]
Reopening for supporting the new max-width of 640dp and an optional drag handle with an accessible 48dp hit target.

**Comment by guidezpl** [comment]
[Design doc](https://docs.google.com/document/d/1pFUxu-f3OPJBmS71OdM_NasRriUdEm6y5PqiMD5WlME/edit?resourcekey=0-TgYM7DRGqRSJ3BCb5SKZ_Q) which can be used as a starting point for the handle feature. The author is no longer working on this project.

**Comment by gnprice** [comment]
> [Design doc](https://docs.google.com/document/d/1pFUxu-f3OPJBmS71OdM_NasRriUdEm6y5PqiMD5WlME/edit?resourcekey=0-TgYM7DRGqRSJ3BCb5SKZ_Q) which can be used as a starting point for the handle feature.

That doc doesn't seem to be public. Is it possible to make it public?

**Comment by guidezpl** [comment]
I'm afraid not, (surprisingly) there's confidential info in there. @hangyujin has access
