### ISSUE TITLE
More default `FormField`s

### ISSUE THREAD

**Issue by FMorschel** [flutter/flutter#111413]
## Use case

I'm trying to create a more complex form using `PopupMenuButton`, `Checkbox` and `CheckboxListTile`. But I have to rely on packages for "`Form` validations" in those fields (for example, accepting EULA is necessary). E.g.: https://pub.dev/packages/checkbox_formfield and https://pub.dev/packages/select_form_field

## Proposal

I would like to see some of these features implemented by Flutter with widgets like `TextFormField` or similar. I would like my project to have the same pattern for dealing with form fields and the same look to the outcome of errors. So I leave here my suggestion for the widgets that I'm using and maybe even some others like `DateFormField` or [`DateRangeFormField`](https://pub.dev/packages/date_range_form_field)

**Comment by leoshusar** [comment]
You might be happy with the [reactive_forms](https://pub.dev/packages/reactive_forms) package.
I am using it for all my forms, they also have it modular, so when I created my own input widget, I was able to implement it to be compatible with this package. (I'm not affiliated with the author)

**Comment by exaby73** [comment]
Hello @FMorschel. This looks like an issue solved by loads of packages that the community has already built. Although Flutter comes in-built with a lot of widgets, expected all of them to be there is infeasible. Also, the use case of accepting EULA is a relatively simple one to validate using Flutter's in-build `Form`. 

For the above reasons, I am closing this issue. If you disagree, please comment and I can reopen it. Thank you.
