### ISSUE TITLE
User confused about what "thumb" meant in Slider API docs

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#11145]
From a chat window:

What is a "thumb" in the context of the Slider widget? https://docs.flutter.io/flutter/material/Slider-class.html
Is it the circle that one drags+drops, on the slider?
Ah ok, it is.

**Comment by gspencergoog** [comment]
The docs now have a sentence for that: "The "thumb", which is a shape that slides horizontally when the user drags it."
