### ISSUE TITLE
Allow certain post-submit steps to run as pre-submit steps in framework PRs

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#111418]
## Use cases

1) I'm editing an integration test that is only run as a post-submit step.  I know exactly what step is affected and I'd like to run it as a presubmit step to make sure I don't accidentally break it while in the process of responding to PR feedback.
2) I'm doing a code review and I have concerns that it breaks something, so I'll add a presubmit task from postsubmit tasks.

## Ideas

Maybe there is a special annotation to PR's that will promote a task from a post submit task to a presubmit task, maybe a comment to a bot that turns it on?  `@postbot presubmit //dev/devicelab/bin/tasks/channels_integration_test_macos.dart`.

Going one step further we could potentially automatically detect which tasks were affected, but that is probably a bit more work to implement since I'm not sure the bookkeeping to detect that is readily available.

cc @godofredoc

**Comment by Hixie** [comment]
Can you run the step locally?

**Comment by Hixie** [comment]
Or alternatively, does the `ci.yaml` file provide us with enough control over the process now to just temporarily control where things run in a PR?

**Comment by gaaclarke** [comment]
> Can you run the step locally?

Sometimes the number of downstream variants makes it unfeasible to run everything locally.

> Or alternatively, does the ci.yaml file provide us with enough control over the process now to just temporarily control where things run in a PR?

I don't think so.  It's not easy at least.  `.ci.yaml` is just for presubmit tasks and there isn't a clear path to migrate something to and from it.

**Comment by Hixie** [comment]
How do we configure post-submit tasks today? Maybe we should move that to the repo under test.

**Comment by ricardoamador** [comment]
Why don't you just add this to presubmit?

**Comment by matanlurey** [comment]
Closed via https://github.com/flutter/cocoon/pull/3256.
