### ISSUE TITLE
Document outgoing events on platform channels page

### ISSUE THREAD

**Issue by xster** [flutter/flutter#11146]
https://flutter.io/platform-channels is great for polling the platform but the push event receiving part with EventChannel doesn't seem documented yet.

**Comment by zoechi** [comment]
@goderbauer if you're admin in the GitHub repo then GitHub provides a feature to move from one repo to another. 
I'm not, so I use ZenHub browser extension that adds a button to copy issues from one repo to another.

**Comment by zoechi** [comment]
Issue moved to [flutter/website #2129](https://github.com/flutter/website/issues/2129) via [**ZenHub**](https://www.zenhub.com/)
