### ISSUE TITLE
Expose whether Skia or Impeller backend is running through service extension

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#111408]
This would allow devtools observatory to include this information in their performance pages and will help us triage reported issues with the backends if the users make a mistake with the flags.

FYI @zanderso @dnfield

**Comment by dnfield** [comment]
There are a bunch of events that impeller emits that Skia never would... we probably already have this, although not as a specific field.

For example, stuff with `Entity` or `Contents` on the raster thread, or anything for tessellation...

**Comment by zanderso** [comment]
Wait, does this need to be in the timeline? If this is only needed in debug or profile mode, then could it instead use a VM service extension? The VM service extension could just return the value of https://github.com/flutter/engine/blob/main/lib/ui/natives.dart#L140.

**Comment by jonahwilliams** [comment]
Ahh, doesn't need to be in the timeline. We could do a service extension too.

@dnfield I don't really think tooling should try to reverse engineer the renderer chosen based on the kind of timeline events present.

**Comment by dnfield** [comment]
If it's that we want tooling to do it, then a service extension would be the way to go.

**Comment by dnfield** [comment]
We already set a private bool in dart:ui (which seems unused and should probably be removed) called `_impellerEnabled`, we could instead expose that information over the VM service protocol.
