### ISSUE TITLE
Ios older version issue

### ISSUE THREAD

**Issue by suerela** [flutter/flutter#111472]
We are encountering some problems in our project that we are currently developing. After installing the application, we encounter problems such as freezing and throwing from the application in iOS 13 and older versions. It throws the user abruptly, especially when navigating the app. Does this have something to do with ios versions or Flutter versions? The program does not give any errors. I am using iphone 6 so i think it has to do with the ram of the phone. 
While navigating in the application, it throws it from the application even while waiting for any data to come or when I want to refresh the page. I'll be happy if you can help me

https://user-images.githubusercontent.com/102950896/189899385-c3776384-b9e5-42b9-86df-59b34d5c84d8.mp4

**Comment by danagbemava-nc** [comment]
Hi @suerela, please provide the output of `flutter doctor -v`.

What other versions of iOS are you experiencing this issue on? 

Can you provide a complete minimal reproducible code sample? 

Do you have any crash reports or incident reports that you can share with us?

**Comment by suerela** [comment]
Unfortunately. There is no response as it does not give any error. That's why I can't give the code.

**Comment by danagbemava-nc** [comment]
Hi @suerela, please provide the output of `flutter doctor -v`.

Also, is this issue in `release` or `debug` mode? 

What other versions of iOS are you experiencing this issue on?

**Comment by suerela** [comment]
Hayır, AppStore'dan yüklediğimde aynı sorun oluyor. İPhone'dan itibaren 12.4 - 12.5 Iphone sürümlerinde oluyor.

**Comment by suerela** [comment]
@danagbemava-nc  Do you think this has something to do with flutter or iphone versions or ram?

**Comment by danagbemava-nc** [comment]
Hi @suerela, I'm not sure what the issue might be. Can you try following https://developer.apple.com/documentation/xcode/acquiring-crash-reports-and-diagnostic-logs to see if you can pull any crash logs for us?
