### ISSUE TITLE
[CP] Allow tests to load from current package using packages/ prefix

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#111411]
### issue_link

https://github.com/flutter/flutter/issues/111285

### Commit Hash

 cd83477

### Target

stable

### pr_link

https://github.com/flutter/flutter/pull/111410

### Impacted Users

Package authors testing assets

### Impact Description

Unit tests that load assets must not specify package prefix, this previously worked.

### Workaround

Conditionally name assets based on test or production.

### Risk

low

### Test Coverage

yes

### Validation Steps

Unit tests attached in PR.

**Comment by itsjustkevin** [comment]
@dnfield could you take a look at this cherry pick request please?

**Comment by dnfield** [comment]
LGTM

**Comment by nicholasspencer** [comment]
thanks!

**Comment by itsjustkevin** [comment]
Merged in Flutter 3.3.2.
