### ISSUE TITLE
Memory Problem when Opening Pages and Animations

### ISSUE THREAD

**Issue by mliciu** [flutter/flutter#111435]
Two part problem

1. Animation
I realized there was a problem when I was trying to test my flutter animation on a Pixel 5 emulator.
I left it running and when I came back, it had frozen my pc.
It took up all the memory.
I had to close vs code and the emulator with Task Manager from Desktop.
I rebooted the App (it takes about 662 MB of space)
But when I play the animation it keeps increasing with 10 MB jumps and it doesn't stop until I leave the page

 Why does the animation require so much memory?

2. Pages
I was wondering if this was specific to the animation, so I kept the Task Manager open and tested it with random pages
Let's say that when I open the app, I arrive at the intro page.
Then I click a button and go to test page. (test page is a stateful widget [doesn't even have to be my Loading widget])
Here is what I saw in Task Manager:
I start with 662 MB on the intro page
I opened test page using Navigator.push
It took maybe 1MB at most. (total: 663 MB)
I clicked on the back button at the bottom of the phone and went to the previous page (intro page).
This also added some MB  (total: 664 MB)
Then when I go back on the test page
It adds some MB again  (total: 665 MB)

I don't understand this behavior.
Does it not keep test page in memory?
Why does it need to recreate it again the second time?
Why is the memory never released?

I tried using Navigator.pushReplacement, no changes to memory
I tried adding maintainState: false, no changes to memory

![animation1](https://user-images.githubusercontent.com/63110862/189791357-01d9b474-bf53-43f8-9fc1-9b64a6b88488.jpg)
![animation2](https://user-images.githubusercontent.com/63110862/189791356-1cf3bbaf-6d1d-4c35-b010-5dff4a3ecd6a.jpg)
![animation3](https://user-images.githubusercontent.com/63110862/189791353-cf75a385-da96-4c56-9f9f-baa1c302d692.jpg)

**Comment by exaby73** [comment]
Hello @mliciu. In your sample code, you are creating new animations 5 times per build. If your screen is refreshing 60 FPS, then you are creating 300 animations per second without disposing them. You should be creating the animations once in `initState()` and disposing them in `dispose()` to avoid memory leaks.

This is not an issue with Flutter itself. If you need additional assistance, I recommend looking at StackOverflow or resource available at https://flutter.dev/community. Since this is not a bug or feature request, I am closing this issue. If you disagree, please comment and I can reopen it. Thank you.

**Comment by mliciu** [comment]
That's what I thought too for the animation, but what about the page Navigation behavior?

**Comment by mliciu** [comment]
@exaby73 
I did as suggested
Put the animation inside initState()
But there were no changes to the memory it consumed

![image](https://user-images.githubusercontent.com/63110862/189938366-0f568e6f-b31c-44e3-a261-3a55e7b1ec7e.png)
![image](https://user-images.githubusercontent.com/63110862/189938530-f81619a5-c1b4-4519-8d1d-474da2f4e894.png)
![image](https://user-images.githubusercontent.com/63110862/189938477-4f158a69-3c19-4233-b1d8-2aba54c62512.png)


I let the animation run for 30 seconds and still there is a spike in memory
![image](https://user-images.githubusercontent.com/63110862/189938692-9908e1c5-23bb-4b4d-8ca1-cc02f60859de.png)
![image](https://user-images.githubusercontent.com/63110862/189938988-28a17bbe-b36e-4643-8158-a0ed44940df7.png)

**Comment by exaby73** [comment]
Please provide a [complete and minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) in the form of text so that I can verify the issue.

**Comment by mliciu** [comment]
I added the first page with the navigation because that's how I had it built in my widget tree.


[minimal_animation_example.txt](https://github.com/flutter/flutter/files/9558720/minimal_animation_example.txt)

**Comment by exaby73** [comment]
Hello @mliciu. Using your sample code, I kept the application open for over an hour. Memory usage never went above 246MB on debug more. Tested on an Android Emulator.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/50555895/190112714-cc0f05d9-e157-418c-a4d7-b405d5e6dd9c.png)

</details>

**Comment by mliciu** [comment]
Just to make sure, but when you ran the app, did you click on the button to
start the animation?
Because the animation was the one causing the problems for me.

**Comment by exaby73** [comment]
Yes. The four disappearing dots appeared and I kept that page open for over an hour

**Comment by mliciu** [comment]
Ok thank you
It must be a problem with my computer, not flutter
