### ISSUE TITLE
[Widget test] Make `IndexedStack` hide non-active children from finder

### ISSUE THREAD

**Issue by simolus3** [flutter/flutter#111478]
## Use case

An `IndexedStack` only ever shows one of its children. Other children aren't rendered or hit-tested. In this sense, I think these other children could be considered off-stage.

However, a finder in widget tests will still find every children:

```dart
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  testWidgets('should only find current widget', (WidgetTester tester) async {
    // Only the `1` text widget will be shown
    await tester.pumpWidget(Directionality(
      textDirection: TextDirection.ltr,
      child: IndexedStack(
        index: 1,
        children: [for (var i = 0 ; i < 10;i++) Text('$i')],
      ),
    ));

    expect(find.text('1'), findsOneWidget);
    expect(find.text('2'), findsNothing); // This currently fails, I believe it should pass
    expect(find.text('2', skipOffstage: false), findsOneWidget); // This should continue to pass
  });
}
```

## Proposal

I believe it would be more intuitive for `IndexedStack` to override `debugVisitOnstageChildren` so that it only reports the currently-active child.

**Comment by bartekpacia** [comment]
Might be related to #114063.

**Comment by ahmdaeyz** [comment]
Is there a workaround to test if only widgets of a certain index are visible?
