### ISSUE TITLE
Using the long-press copy function in the scroll view, the pop-up box and the 2nd anchor point will be at the top of the view, displayed above the appbar, and the UI is a bit ugly

### ISSUE THREAD

**Issue by YunFeng-Huang** [flutter/flutter#111463]
在开发 复制黏贴时发现如下问题：

<img width="300" alt="WeChatc05d695f92d736d0d449ae931a0945cf" src="https://user-images.githubusercontent.com/40824282/189877415-c9f189a1-9c60-4a4f-9a74-28a8c8e6c2c0.png">

TextSelectionControls
在滚动视图里使用长按复制功能，弹框和2端锚点都会在视图的最高层，显示在appbar之上，ui上有点难看，非滚动视图里使用可以遮盖住

---

_Translated via Google Translate:_

When developing copy and paste, the following problems were found:

_Image_

TextSelectionControls
Use the long-press copy function in the scroll view, the pop-up box and the 2-end anchor point will be at the top of the view, displayed above the appbar, the UI is a bit ugly, and it can be covered when used in a non-scroll view.

**Comment by exaby73** [comment]
Hello @YunFeng-Huang. Thank you for filing this issue. Can you please provide the following information?

- A [complete and minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).
- The output of `flutter doctor -v`

**Comment by exaby73** [comment]
I have found a duplicate to this issue. Marking as same of https://github.com/flutter/flutter/issues/59229
