### ISSUE TITLE
[google_signin] Provide branded Widget, update Field Trippa code lab

### ISSUE THREAD

**Issue by tiloc** [flutter/flutter#111464]
## Use case
I have built an app which is accessing Google Photos APIs, in a very similar manner to the Field Trippa code lab.
https://codelabs.developers.google.com/codelabs/google-photos-sharing

The app got rejected by Google during the OAuth Consent Screen verification, due to violation of Google's branding guidelines. Specifically, the "Connect with Google Photos" button as depicted here: https://codelabs.developers.google.com/codelabs/google-photos-sharing#2
is in violation of the following guideline: https://developers.google.com/identity/branding-guidelines#top_of_page

## Proposal
I am proposing the following:
1. Update the code lab to be in compliance with Google's own guidelines.
2. Provide a Widget as part of the google_signin package that implements a sign-in button which is in full compliance with Google's branding guideline.

**Comment by exaby73** [comment]
Hello @tiloc. The purpose of the codelabs is not for building a production ready application, but rather to focus on learning certain concept. It's the job of the developer then to make the app production ready which includes implementing the compliant UI. If you are looking for drop in ready buttons which are compliant, might I suggest looking into using packages like [social_login_buttons](https://pub.dev/packages/social_login_buttons).

For the above reasons, I am closing this issue. If you disagree, please comment and I can reopen it. Thank you.

**Comment by tiloc** [comment]
thanks for your feedback. While I would of course hope that a code lab was more "copy&paste-ready" for later production apps, I can see your point.

Regarding the social_login_buttons package, those buttons are also clearly in violation of Google's guidelines (wrong padding, wrong alignment, wrong font). I would therefore still like to propose that the 1st party google_signin plugin also comes with a button widget that is perfectly aligned with the guidelines from that same party.

**Comment by exaby73** [comment]
@tiloc Since the issue you raised was mainly targeted towards the codelab, for this feature request, it would be better to raise as a new issue altogether. Keeping this issue closed for the same reason.
