### ISSUE TITLE
3.3.1 problem with flutter run --profile

### ISSUE THREAD

**Issue by jerryhamby** [flutter/flutter#111589]
I’m trying to seen my app to my iPhone 7 (15.7) and I keep seeing 
Flutter sending it to Chrome, thinking it’s a web app.

flutter run --profile
Launching lib/main.dart on Chrome in profile mode...
Compiling lib/main.dart for the Web...      

Is this a know issue??? 
This worked before, what an I doing wrong?

**Comment by soarescaique** [comment]
Try to update your Xcode Version to 14, then open Xcode and try to find your iPhone model at Devices tab. It should work.

**Comment by jerryhamby** [comment]
Thanks for the quick reply.
I tried what you suggested but I'm not having any luck. Tried all suggestions.
This is what I keep seeing:

Failed to prepare the device for development
This operation can fail if the version of the OS on the device is incompatible with the installed version of Xcode. You may also need to restart your Mac and device in order to correctly detect compatibility.

iOS 15.7 (19H12)
Model: iPhone 7 (Model 1660, 1778, 1779, 1780
Capacity: 23.15 GB (2.7 GB available)
Serial Number: DNPTQ1D——-
Identifier: 456c236df4f6f0d0c0ad79ece—————   

PS:
I have 2 computers and I see the same problem on both:
* iMac 5k (Intel)   Monterey 12.6 
* 16” Macbook (Silicon)   Monterey 12.6

**Comment by exaby73** [comment]
Hello @jerryhamby. Could you post the output of `flutter doctor -v` in the form of text?

**Comment by jerryhamby** [comment]
To exaby73 :
Today the device will not show up in Flutter, even thought it's attached.
Here is what I get with doctor. Let me know if this text file works.

[send later.txt](https://github.com/flutter/flutter/files/9576524/send.later.txt)

**Comment by exaby73** [comment]
Can you try the debugging steps highlighted [here](https://stackoverflow.com/questions/64974291/xcode-error-failed-to-prepare-device-for-development)?
