### ISSUE TITLE
what is wrong?

### ISSUE THREAD

**Issue by iMahdiyarw** [flutter/flutter#111552]
Error lines: 45-46-47

import 'package:flutter/material.dart';

import '../widgets/image_input.dart';

class AddPlaceScreen extends StatefulWidget {
  static const routeName = '/add-place';

  @override
  _AddPlaceScreenState createState() => _AddPlaceScreenState();
}

class _AddPlaceScreenState extends State<AddPlaceScreen> {
  final _titleController = TextEditingController();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Add a New Place'),
      ),
      body: Column(
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: <Widget>[
          Expanded(
            child: SingleChildScrollView(
              child: Padding(
                padding: EdgeInsets.all(10),
                child: Column(
                  children: <Widget>[
                    TextField(
                      decoration: InputDecoration(labelText: 'Title'),
                      controller: _titleController,
                    ),
                    SizedBox(height: 10,),
                    ImageInput(),
                  ],
                ),
              ),
            ),
          ),
          ElevatedButton.icon(
            icon: Icon(Icons.add),
            label: Text('Add Place'),
            onPressed: () {},
            elevation: 0,
            materialTapTargetSize: MaterialTapTargetSize.shrinkWrap,
            color: Theme.of(context).colorScheme.secondary,
          ),
        ],
      ),
    );
  }
}

**Comment by timcreatedit** [comment]
The API of `ElevatedButton` is different:

```dart
...
          ElevatedButton.icon(
            icon: Icon(Icons.add),
            label: Text('Add Place'),
            onPressed: () {},
            style: ElevatedButton.styleFrom(
              elevation: 0,
              tapTargetSize: MaterialTapTargetSize.shrinkWrap,
              backgroundColor: Theme.of(context).colorScheme.secondary,
            ),
          ),
...
```

**Comment by iMahdiyarw** [comment]
> The API of `ElevatedButton` is different:
> 
> ```dart
> ...
>           ElevatedButton.icon(
>             icon: Icon(Icons.add),
>             label: Text('Add Place'),
>             onPressed: () {},
>             style: ElevatedButton.styleFrom(
>               elevation: 0,
>               tapTargetSize: MaterialTapTargetSize.shrinkWrap,
>               backgroundColor: Theme.of(context).colorScheme.secondary,
>             ),
>           ),
> ...
> ```

Thanks for help.
