### ISSUE TITLE
Add presubmit analyze_flutter_gallery analysis

### ISSUE THREAD

**Issue by athomas** [flutter/flutter#111538]
Originally reported in https://github.com/dart-lang/sdk/issues/49950
```
Analyzing gallery...

   info - lib/studies/reply/app.dart:148:5 - 'bottomAppBarColor' is deprecated and shouldn't be used. Use BottomAppBarTheme.color instead. This feature was deprecated after v3.3.0-0.6.pre.. Try replacing the use of the deprecated member with the replacement. - deprecated_member_use
   info - lib/studies/reply/app.dart:195:5 - 'bottomAppBarColor' is deprecated and shouldn't be used. Use BottomAppBarTheme.color instead. This feature was deprecated after v3.3.0-0.6.pre.. Try replacing the use of the deprecated member with the replacement. - deprecated_member_use

2 issues found.
```

Is there no analysis presubmit for Flutter Gallery?

**Comment by keyonghan** [comment]
> Agreed that next step is ensuring that flutter/flutter PRs get a presubmit analysis check of the Gallery so that deprecations don't cause false positives for Dart.

Is this something suitable for `Linux analyze`? /cc @HansMuller

**Comment by godofredoc** [comment]
We do this in customer_testing, do we need something more elaborated?

**Comment by goderbauer** [comment]
Closing this as we are in the process of shutting down gallery.

cc @gspencergoog
