### ISSUE TITLE
Firebase Auth uses or overrides a deprecated API

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#11154]
When compiling an app with the Firebase Auth plugin, I get the following warning:

```
Note: C:\Users\goderbauer\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\firebase_auth-0.1.1\android\src\main\java\io\flutter\firebaseauth\FirebaseAuthPlugin.java uses or overrides a deprecated API.
```

We should probably move to a non-deprecated API.

/cc @collinjackson

**Comment by sawsankgraham** [comment]
import io.flutter.firebaseauth.FirebaseAuthPlugin;
import io.flutter.plugins.firebase.database.FirebaseDatabasePlugin;
import io.flutter.plugins.firebase.storage.FirebaseStoragePlugin;
import io.flutter.plugins.googlesignin.GoogleSignInPlugin;

When compiling why does my IDE say that the above import statements are not resolved?

**Comment by collinjackson** [comment]
I believe this was fixed in flutter/plugins#233

**Comment by mokhosh** [comment]
Is it normal that I'm still getting this?

**Comment by zoechi** [comment]
@mokhosh depends on the Flutter version you're using

**Comment by mokhosh** [comment]
@zoechi Channel beta, v0.3.2

**Comment by zoechi** [comment]
@mokhosh that's quite dated. Upgrade to newer `beta` or `dev`

**Comment by amlbar** [comment]
I still get this message `overrides a deprecated API` and the package `firebase_auth 0.5.10` causes the app to stop running.

```
Running 'gradlew assembleDebug'...
Note: /Users/amielbarino/development/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.5.10/android/src/main/java/io/flutter/plugins/firebaseauth/FirebaseAuthPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Built build/app/outputs/apk/debug/app-debug.apk.
Installing build/app/outputs/apk/app.apk...
```

```
MacBar:hello_world amielbarino$ flutter --version
Flutter 0.4.4 • channel beta • https://github.com/flutter/flutter.git
Framework • revision f9bb4289e9 (2 weeks ago) • 2018-05-11 21:44:54 -0700
Engine • revision 06afdfe54e
Tools • Dart 2.0.0-dev.54.0.flutter-46ab040e58
```

Any help about this issue?

**Comment by chrisd1997** [comment]
Same issue right here.

Currently using Flutter version: 0.4.4 beta and Firebase 0.5.10

**Comment by peterzagoranski** [comment]
+1

**Comment by Asoseil** [comment]
same for me with firebase auth 0.5.11

**Comment by rohan20** [comment]
+1

**Comment by jmnyv** [comment]
Still getting the issue on:

Flutter 0.5.7 • channel dev • https://github.com/flutter/flutter.git
firebase_auth: 0.5.15

**Comment by allanwolski** [comment]
Same issue right here.

**Comment by rgeurgas** [comment]
Still getting the issue on:

Flutter 0.6.0 • channel beta • https://github.com/flutter/flutter.git
firebase_auth: 0.5.19

**Comment by zoechi** [comment]
Reopening because this is still an issue.

**Comment by rkunboxed** [comment]
Same here.
Flutter: 0.8.2
Firebase Auth: 0.5.20

**Comment by jobthirimu** [comment]
I am getting the below:

Note: C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-0.6.2+1\android\src\main\java\io\flutter\plugins\firebaseauth\FirebaseAuthPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

Kindly assist.

**Comment by IDani95** [comment]
Same here
  firebase_auth: ^0.6.6

`Note: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-0.6.6\android\src\main\java\io\flutter\plugins\firebaseauth\FirebaseAuthPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.`

**Comment by Achileas** [comment]
Hello, Can some one help I have the same issue saying:

Note: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-0.6.6\android\src\main\java\io\flutter\plugins\firebaseauth\FirebaseAuthPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

**Comment by Achileas** [comment]
`Note: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-0.6.6\android\src\main\java\io\flutter\plugins\firebaseauth\FirebaseAuthPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.`

**Comment by RajatKD** [comment]
Same issue exist in flutter 1.0 stable release.

**Comment by RajatKD** [comment]
Note: C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-0.6.6\android\src\main\java\io\flutter\plugins\firebaseauth\FirebaseAuthPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-0.6.6\android\src\main\java\io\flutter\plugins\firebaseauth\FirebaseAuthPlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-0.2.5+1\android\src\main\java\io\flutter\plugins\firebase\core\FirebaseCorePlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

**Comment by WeellingtonCesa** [comment]
> Same here
> 
> ```
> 
> Doctor summary (to see all details, run flutter doctor -v):
> [√] Flutter (Channel beta, v1.0.0, on Microsoft Windows [versÃ£o 10.0.17134.407], locale pt-BR)
> [√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
> [√] Android Studio (version 3.2)
> [√] VS Code (version 1.29.1)
> [√] Connected device (1 available)
> 
> 
> firebase_auth: ^0.6.6
> ```

Here for me, it presents the message but it is working. My problem is with cloud_firestore now.

**Comment by WeellingtonCesa** [comment]
Here for me, it presents the message but it is working. My problem is with cloud_firestore now.

> Same here
> 
> ```
> 
> Doctor summary (to see all details, run flutter doctor -v):
> [√] Flutter (Channel beta, v1.0.0, on Microsoft Windows [versÃ£o 10.0.17134.407], locale pt-BR)
> [√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
> [√] Android Studio (version 3.2)
> [√] VS Code (version 1.29.1)
> [√] Connected device (1 available)
> 
> 
> firebase_auth: ^0.6.6
> ```

**Comment by DanMossa** [comment]
Getting this issue with 
`firebase_auth-0.6.6`
firebase_core-0.2.5+1`

**Comment by thuutien** [comment]
This problem happens on Android with Firebase cloud store package

**Comment by joaovic** [comment]
> Getting this issue with
> `firebase_auth-0.6.6`
> `firebase_core-0.2.5+1`

Same here. 
### When building the apk on Linux (Linux Mint 19), the app does not sign on Moto X4 Device running Android Pie, but do sign in a emulated device or older cel phones with older Android versions.

`Launching lib/main.dart on Android SDK built for x86 in debug mode...`
`Initializing gradle...`
`Resolving dependencies...`
`Gradle task 'assembleDebug'...`
`registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)`
`registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)`
`registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)`
`registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)`
`registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)`
`Note: /home/joao/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.6.6/android/src/main/java/io/flutter/plugins/firebaseauth/FirebaseAuthPlugin.java uses or overrides a deprecated API.`
`Note: Recompile with -Xlint:deprecation for details.`
`Note: /home/joao/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.6.6/android/src/main/java/io/flutter/plugins/firebaseauth/FirebaseAuthPlugin.java uses unchecked or unsafe operations.`
`Note: Recompile with -Xlint:unchecked for details.`
`Note: /home/joao/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.2.5+1/android/src/main/java/io/flutter/plugins/firebase/core/FirebaseCorePlugin.java uses unchecked or unsafe operations.`
`Note: Recompile with -Xlint:unchecked for details.`
`Built build/app/outputs/apk/debug/app-debug.apk.`


### When building the apk on Windows (Git Bash Shell on Windows 10), the app do sign on all devices

`Initializing gradle...`
`Resolving dependencies...`
`Gradle task 'assembleDebug'...`
`registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)`
`registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)`
`registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)`
`registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)`
`registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)`
`Built build\app\outputs\apk\debug\app-debug.apk.`

**Comment by monucode** [comment]
I was able to solve with the following way -

By default, Flutter supports Android SDK v16 (Jelly Bean, released 2012), but multidex doesn't really work with Jelly Bean (though, it's possible). Configuring Jelly Bean to work is beyond the scope of this codelab, so we'll change the minimum target SDK version from v16 to v21 (Lollipop, released 2014).

Change the minimum target SDK version:-
    Open android/app/build.gradle, then find the line that says minSdkVersion 16.
    Change that line to minSdkVersion 21.

**Comment by kedhas** [comment]
mine is at v21 but i still get that warning in red, but the app works fine though.

**Comment by kedhas** [comment]
I was refering to the deprecated API issue

**Comment by tikodrack** [comment]
when creating the APK, plenty of red warnings were reported (this very same deprecated API issue), but nevertheless despite the warnings, the APK did work fine...

so, presently I'm planning to simply ignore the warnings, but it would sure be nice if this issue would be resolved, for increased safety and peace of mind...

**Comment by Basher7** [comment]
same error in my project......

> Note: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\connectivity-0.4.2\android\src\main\java\io\flutter\plugins\connectivity\ConnectivityPlugin.java uses or overrides a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.
> Note: Some input files use unchecked or unsafe operations.
> Note: Recompile with -Xlint:unchecked for details.

**Flutter Doctor Status......**
> D:\Development\VS\XpertMemos\XpertMemo_flutter>flutter doctor -v
> [√] Flutter (Channel stable, v1.2.1, on Microsoft Windows [Version 10.0.17763.316], locale en-US)
>     • Flutter version 1.2.1 at C:\src\flutter
>     • Framework revision 8661d8aecd (2 weeks ago), 2019-02-14 19:19:53 -0800
>     • Engine revision 3757390fa4
>     • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)
> 
> [√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
>     • Android SDK at C:\Users\XpertLab_10\AppData\Local\Android\sdk
>     • Android NDK location not configured (optional; useful for native profiling support)
>     • Platform android-28, build-tools 28.0.3
>     • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
>     • All Android licenses accepted.
> 
> [√] Android Studio (version 3.2)
>     • Android Studio at C:\Program Files\Android\Android Studio
>     • Flutter plugin version 31.3.1
>     • Dart plugin version 181.5656
>     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
> 
> [√] VS Code (version 1.31.1)
>     • VS Code at C:\Users\XpertLab_10\AppData\Local\Programs\Microsoft VS Code
>     • Flutter extension version 2.22.3
> 
> [√] Connected device (1 available)
>     • roar V150 • 90515004334661495338 • android-arm • Android 7.0 (API 24)
> 
> • No issues found!

**Comment by frixou89** [comment]
> Change the minimum target SDK version:-
> Open android/app/build.gradle, then find the line that says minSdkVersion 16.
> Change that line to minSdkVersion 21.

This worked for me

**Comment by nhwilly** [comment]
@frixou89  Thanks for responding...

Cleaned the project,  Rebuilt and got this:
```
Launching lib\main.dart on Android SDK built for x86 in debug mode...
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
Note: C:\Users\bill\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\firebase_core-0.4.0+6\android\src\main\java\io\flutter\plugins\firebase\core\FirebaseCorePlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: C:\Users\bill\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\package_info-0.4.0+4\android\src\main\java\io\flutter\plugins\packageinfo\PackageInfoPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
```
One appears to be the `PackageInfo` plugin.  I must be behind on something, but I can't figure out what...

**Comment by collinjackson** [comment]
It looks like the original firebase_auth compile warnings were fixed in #963. I've opened PRs #1883 for the firebase_core warning fix, #1884 for the package_info warning fix, and https://github.com/flutter/plugins/pull/1885 for the registerResGeneratingTask fix.

Closing this issue as the original issue is resolved and also it should be fine to ignore the warnings.

**Comment by kroikie** [comment]
@goderbauer

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/984. Any further collaboration will be done there.

**Comment by TaykYoku** [comment]
the warning still remains..

Note: /Users/lyto/Applications/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.4.3+1/android/src/main/java/io/flutter/plugins/firebase/core/FirebaseCorePlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
