### ISSUE TITLE
[Impeller] Support COLRv1 fonts in impeller backend

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#111599]
Today this already works in Skia, we should make impeller support it as well. 

In order to get basic rendering support, the following diff is needed:

```
diff --git a/impeller/entity/shaders/glyph_atlas.frag b/impeller/entity/shaders/glyph_atlas.frag
index f41d9a181d..f07e591f19 100644
--- a/impeller/entity/shaders/glyph_atlas.frag
+++ b/impeller/entity/shaders/glyph_atlas.frag
@@ -19,5 +19,5 @@ void main() {
   frag_color = texture(
     glyph_atlas_sampler,
     v_unit_vertex * scale_perspective + offset
-  ).aaaa * v_text_color;
+  ) * v_text_color;
 }
diff --git a/impeller/typographer/backends/skia/text_render_context_skia.cc b/impeller/typographer/backends/skia/text_render_context_skia.cc
index aab49ed2fe..98d199738d 100644
--- a/impeller/typographer/backends/skia/text_render_context_skia.cc
+++ b/impeller/typographer/backends/skia/text_render_context_skia.cc
@@ -107,7 +107,7 @@ static std::shared_ptr<SkBitmap> CreateAtlasBitmap(const GlyphAtlas& atlas,
                                                    size_t atlas_size) {
   TRACE_EVENT0("impeller", __FUNCTION__);
   auto bitmap = std::make_shared<SkBitmap>();
-  auto image_info = SkImageInfo::MakeA8(atlas_size, atlas_size);
+  auto image_info = SkImageInfo::MakeN32Premul(atlas_size, atlas_size);
   if (!bitmap->tryAllocPixels(image_info)) {
     return nullptr;
   }
@@ -168,7 +168,7 @@ static std::shared_ptr<Texture> UploadGlyphTextureAtlas(
 
   TextureDescriptor texture_descriptor;
   texture_descriptor.storage_mode = StorageMode::kHostVisible;
-  texture_descriptor.format = PixelFormat::kA8UNormInt;
+  texture_descriptor.format = PixelFormat::kR8G8B8A8UNormInt;
   texture_descriptor.size = ISize::MakeWH(atlas_size, atlas_size);
 
   if (pixmap.rowBytes() * pixmap.height() !=
   ```
   
open question: can we optimize the atlases and only use MakeN32Premul for color fonts?
   
Follow ups: do we need to do any different color source handling compared to skia

**Comment by bdero** [comment]
Does this reduce apparent frame performance at all on the advanced blend dome in Wondrous? I think there's a good chance it'll have little impact despite the increased texture size. If it causes Skia to do a lot more work than it probably will.

If perf is good, we could just land this without switching to a smaller atlas for the time being.

**Comment by jonahwilliams** [comment]
unconditionally using 32bit atlases regresses average raster time on wonders by about 15% in local testing, just on the caurosel page without going into advanced blend. I think we should probably opt into this behavior only when we detect one of these fonts

**Comment by jonahwilliams** [comment]
"fun" fact about these fonts, Skia appears to be parsing XML and running SVG related code while drawing them. This actually makes it quite slow to use one of these fonts in impeller today. Its @dnfield 's nightmare . I guess vector format == svg

<img width="1281" alt="Screen Shot 2022-09-14 at 8 15 53 PM" src="https://user-images.githubusercontent.com/8975114/190305945-b2cfc5ed-5526-4134-a9e8-664623128681.png">

**Comment by dnfield** [comment]
Those funcs with SVG in the name look to be in CoreText somewhere...

**Comment by jonahwilliams** [comment]
Is the assumption that we are generating some metadata for this and caching it? Because these fonts are crazy slow in impeller right now...

**Comment by jonahwilliams** [comment]
Here is the trace. Font used is Nabla

[colr_impeller.trace.zip](https://github.com/flutter/flutter/files/9571617/colr_impeller.trace.zip)

**Comment by jonahwilliams** [comment]
This is the output of strings on Nabla: https://gist.github.com/jonahwilliams/90c493b1b9b036a85021dba9a53d1954

**Comment by dnfield** [comment]
IMHO we should prioritize this relatively low for now. There are other things we can do to fix text, and it's not clear to me it will ever be possible to make this format all that fast in its current incarnation.
