### ISSUE TITLE
Missing call method channel in Module Flutter SDK exception when adding AAR to existing Android project

### ISSUE THREAD

**Issue by anhkhoi159** [flutter/flutter#111546]
1. Create a new flutter module with "flutter create -t module module_name"
2. Add a plugin to the module, I added webview_flutter and shared_preferences, but any plugin will cause an error
3. Create an AAR file by : Flutter build aar
4. Take the AAR from the ./android/Flutter/build/outpurs/aar/flutter_release-1.0.aar and add it to my existing Android project.
5. Add the code to launch the flutter view from here: https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps
Run app and see WebView error 
![image](https://user-images.githubusercontent.com/55753138/190129729-d8684299-ea2d-4df2-976a-478fa0e1372f.png)

**Comment by exaby73** [comment]
Hello @anhkhoi159. Could you expand on step 4? I am not a native android dev, so forgive me, but I do not know how to include AAR files in a native project. Could you provide some detailed steps so that I may verify the issue?

**Comment by anhkhoi159** [comment]
> Hello @anhkhoi159. Could you expand on step 4? I am not a native android dev, so forgive me, but I do not know how to include AAR files in a native project. Could you provide some detailed steps so that I may verify the issue?

I build AAR file from flutter and add in LIBS folder of Native project, then I add in dependencies of Native project

**Comment by exaby73** [comment]
Could you provide detailed steps to achieve this? Again, I am not a native dev so I am not sure how to add dependencies, or which exact folder I am supposed to put the AAR into.

**Comment by anhkhoi159** [comment]
> Could you provide detailed steps to achieve this? Again, I am not a native dev so I am not sure how to add dependencies, or which exact folder I am supposed to put the AAR into.

@exaby73  I add AAR file into libs folder . And then I add dependencies in gradle file.
![image](https://user-images.githubusercontent.com/55753138/190336336-351e12e2-62f1-4b11-8bd6-e822536b90b4.png)

![image](https://user-images.githubusercontent.com/55753138/190336190-9af41d60-99d6-4e67-b547-b890fe87b09b.png)

**Comment by exaby73** [comment]
Could you include a public repository that I can use to test this issue? I am unable to run the app with the steps you've provided.

**Comment by exaby73** [comment]
@anhkhoi159 Have you tried the steps highlighter [here](https://docs.flutter.dev/development/add-to-app/android/project-setup#using-android-studio)?
