### ISSUE TITLE
[CP] Fatal crash with `java.lang.AssertionError` when selecting text in `TextField`

### ISSUE THREAD

**Issue by AlexV525** [flutter/flutter#111537]
### issue_link

https://github.com/flutter/flutter/issues/110640

### Commit Hash

https://github.com/flutter/engine/commit/fe5b84ae3f29b9bec8dd88a80e14e5c244b48963

### Target

stable

### pr_link

https://github.com/flutter/engine/pull/35924

### Impacted Users

all Flutter devs upgraded to 3.3

### Impact Description

The Flutter Android app will fatally crash when using text fields with IME's operations, such as selecting all, partial selecting, etc.

### Workaround

No

### Risk

low

### Test Coverage

yes

### Validation Steps

A few reproducible screen recordings are submitted in the issue, we can follow steps in any of them to see if it's reproducible.

**Comment by itsjustkevin** [comment]
@HansMuller and @justinmc could you take a look at this cherry-pick request?

**Comment by HansMuller** [comment]
I've asked Chun-Heng and Justin to review this CP.

**Comment by justinmc** [comment]
I'm on board with cherry picking this 👍 .  It's a pretty major crash and the fix (https://github.com/flutter/engine/pull/35924) looks low-risk to me.

Also CC @dkwingsmt who reviewed the PR as well.

**Comment by chunhtai** [comment]
SGTM with cherry-picking this change.

**Comment by dkwingsmt** [comment]
SGTM with this CP.

**Comment by itsjustkevin** [comment]
@AlexV525 can you open a PR with the included cherry-picks against `flutter-3.2-candidate.5` and update your pr_link with that PR?

**Comment by AlexV525** [comment]
> @AlexV525 can you open a PR with the included cherry-picks against `flutter-3.2-candidate.5` and update your pr_link with that PR?

As @bleroux mentioned, the commit's changes are based on another one, maybe @dkwingsmt can submit the PR first? I can make this one after that.

**Comment by AlexV525** [comment]
I've submitted a PR that CPing both commits. https://github.com/flutter/engine/pull/36288

**Comment by itsjustkevin** [comment]
@AlexV525 PR is merged.  Will close this issue when the cherry-picks are picked up in the next release.

**Comment by CaseyHillers** [comment]
Released in https://github.com/flutter/flutter/releases/tag/3.3.3
