### ISSUE TITLE
Exception: Android toolchain - develop for Android devices exceeded maximum allowed duration of 0:10:00.000000

### ISSUE THREAD

**Issue by MourningRaptor** [flutter/flutter#111576]
`flutter doctor` gives the following error:
`Checking Android licenses is taking an unexpectedly long time...[☠] Android toolchain - develop for Android devices (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know
      about this issue at https://github.com/flutter/flutter/issues.
    ✗ Exception: Android toolchain - develop for Android devices exceeded maximum allowed duration of 0:10:00.000000
`

I have installed the latest Android SDK Command-line Tools in Android Studio
I have tried setting the location of SDK via `flutter config --android-sdk /Users/mooreihu/Library/Android/sdk`

I have tried running `flutter doctor --android-licenses`, and it hangs indefinitely. I never reached a timeout or anything like that.

I am not sure what else to try, haven't found much on this specific issue online. Thank you for any help!

Here is my complete flutter doctor -v output:
```
[✓] Flutter (Channel stable, 3.3.1, on macOS 12.5.1 21G83 darwin-arm, locale en-US)
    • Flutter version 3.3.1 on channel stable at /Users/mooreihu/Downloads/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4f9d92fbbd (8 days ago), 2022-09-06 17:54:53 -0700
    • Engine revision 3efdf03e73
    • Dart version 2.18.0
    • DevTools version 2.15.0

Checking Android licenses is taking an unexpectedly long time...[☠] Android toolchain - develop for Android devices (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please
      let us know about this issue at https://github.com/flutter/flutter/issues.
    ✗ Exception: Android toolchain - develop for Android devices exceeded maximum allowed duration of
      0:10:00.000000
    • 

[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A309
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Community Edition (version 2022.1.3)
    • IntelliJ at /Users/mooreihu/Library/Application
      Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5921.22/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.69.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.5.1 21G83 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 105.0.5195.102

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

**Comment by huycozy** [comment]
Hi @MourningRaptor 
Do you have this issue when you first install Flutter or after upgrading to a newer version of Flutter?

Also, could you try this workaround to see if it can help? https://github.com/flutter/flutter/issues/33649#issuecomment-497656242
>update your Android SDK build tools and restart your PC

**Comment by MourningRaptor** [comment]
> #33649 (comment)

Hi @huycozy, thank you for the response.

This is the first time I have installed Flutter. I did see that post, and I tried the command. But this is all I get:
`sdk % flutter doctor --android-licenses

`
It hangs indefinitely; nothing ever happens.

I did try to run  `sudo flutter doctor --android-licenses`. It gave me a warning that it isn't wise to use sudo, but the licenses appeared. I approved them, restarted my laptop, but got the same thing when running `flutter doctor`.

The last thing I tried was `sudo flutter doctor`. I know this is not recommended, but it does pass that stage (although it has an issue with cocoapods).

I am on MacOS Monterrey 12.5.1

**Comment by MourningRaptor** [comment]
> cd /Users/mooreihu/Library/Android/ && ls -l

```
bin % cd /Users/mooreihu/Library/Android/ && ls -l 
total 0
drwxr-xr-x  18 mooreihu  staff  576 Sep 14 11:35 sdk
```

**Comment by huycozy** [comment]
Hi @MourningRaptor, thanks for responding. Labeling this issue for further investigation.

**Comment by MourningRaptor** [comment]
I was able to solve this by using Java 8 instead of Java 11! Flutter doctor is all green.

**Comment by GaryQian** [comment]
Thanks for figuring out it was the Java version, I'm sure this will be helpful for someone in the future
