### ISSUE TITLE
Test that `flutter run` doesn't introduce new debug spew

### ISSUE THREAD

**Issue by timsneath** [flutter/flutter#111577]
I think I'm right in saying that https://github.com/flutter/flutter/issues/110948 was able to emerge undetected in stable because we don't have a test that verifies `flutter run` does not spew out an unexpected error. 

Can we add such a test? Here is the failing condition:

```
[C:\src\wintext] flutter run -d windows
Launching lib\main.dart on Windows in debug mode...
Building Windows application...
[ERROR:flutter/shell/platform/windows/direct_manipulation.cc(137)] CoCreateInstance(CLSID_DirectManipulationManager, nullptr, CLSCTX_INPROC_SERVER, IID_IDirectManipulationManager, &manager_) failed
[INFO:embedder.cc(136)] populate_existing_damage was not defined, disabling partial repaint. If you wish to enable partial repaint, please define this callback.
Syncing files to device Windows...                                  58ms
```

We should have been able to pick this up with CI by identifying unexpected text between the Build command and the Sync command. I suspect a test like this might pick up a whole category of potential failures that might only otherwise be detected with manual testing.

/cc @loic-sharma for thoughts.

**Comment by jonahwilliams** [comment]
This sort of test is going to fail a lot, because some of the output flutter run includes is not from the flutter tool or engine, but from the other platform tools that we depend on, like Gradle and the Android SDK. These can have messaging the slightly differs accross versions, and updates out of band with the Flutter SDK.

**Comment by loic-sharma** [comment]
We recently added a test to the engine to ensure it doesn't have unexpected output:

https://github.com/flutter/engine/blob/2d62ba3e1b92beb6bbe90aabcbff2578ed551a11/shell/platform/windows/flutter_windows_unittests.cc#L43-L67

Ideally once https://github.com/flutter/flutter/issues/110948 is fixed we'd add a similar test to the Flutter tool.

> This sort of test is going to fail a lot, because some of the output flutter run includes text that is not from the flutter tool or engine, but from the other platform tools that we depend on, like Gradle and the Android SDK. 

This is a good point. Perhaps the test should check there aren't obvious errors? I'll give this some more thought

**Comment by jonahwilliams** [comment]
Its possible we could specifically grep for the engine prefixes for debug logs too

**Comment by loic-sharma** [comment]
Added in https://github.com/flutter/flutter/pull/116798
