### ISSUE TITLE
doc to bind external api?

### ISSUE THREAD

**Issue by benoitc** [flutter/flutter#1115]
i would try to add gps features to a test app, is there any doc or example to do such thing?

**Comment by sethladd** [comment]
Sorry, I don't think there is a formal doc on how to bind to system services. There are a bunch of examples in the repo. This is an area we plan to improve and make accessible to developers.

Definitely join us at flutter-dev@googlegroups.com where it's easier to chat with us. We'd love to know what you're planning.

Going to close this issue in favor of https://github.com/flutter/flutter.github.io/issues/50 but we really appreciate the question!
