### ISSUE TITLE
`ThemeData.light()/ThemeData.dark()` in M3 doesn't generate correct colors for some components.

### ISSUE THREAD

**Issue by QuncCccccc** [flutter/flutter#111520]
If the `ThemeData` is set to `ThemeData.light(useMaterial3: true)`, the colors in some components are not correct.

`ThemeData.light(useMaterial3: true)` and `ThemeData.dark(useMaterial3: true)`:
<img width="350" alt="Screen Shot 2022-09-13 at 3 59 00 PM" src="https://user-images.githubusercontent.com/36861262/190024041-77e91063-bbfe-4571-b032-b1aeae902bd8.png"><img width="350" alt="Screen Shot 2022-09-13 at 3 57 49 PM" src="https://user-images.githubusercontent.com/36861262/190023734-ed59b7b6-b58f-4668-bff4-91be983f6a23.png">

`ThemeData(colorSchemeSeed: Colors.blue, useMaterial3: true)`:
<img width="450" alt="Screen Shot 2022-09-13 at 3 31 23 PM" src="https://user-images.githubusercontent.com/36861262/190020824-47f15be5-171c-4bca-8770-af21fafd8d57.png">

**Comment by guidezpl** [comment]
Demo is looking 🔥. I think this is a good opportunity for us to switch the default M3 color from `blue` to the purple used in M3 specs and in some samples.
