### ISSUE TITLE
[pigeon] Condense serialization formats

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#111503]
(Capturing from offline discussion for tracking, and to capture further discussion in one place.)

Currently Pigeon serializes objects as dictionaries where the keys are string versions of the field name, and the value is the value. This is a common way to do manual platform channel serialization because it's the most intuitive to maintain, but it's extremely inefficient (as discussed some [here](https://github.com/flutter/flutter/issues/105233#issuecomment-1145173099)). A more efficient approach is to just serialize the fields as an array; unlike doing it by hand, the fact that you have to do index-matching across languages (which is very error-prone to maintain, as well as confusing to read, when done manually) is a non-problem with Pigeon, because it's all generated code that people don't need to read as a normal part of plugin maintenance. And since Pigeon isn't a multi-version-compatible system, but requires that both sides be generated with the same pigeon version, we don't get any runtime advantage from the string keys.

We should change all of the dictionary serialization to array-based serialization (as is already done for function arguments). Most importantly object serialization, but we should also do it for responses (currently they use a dictionary, while the corresponding Flutter-level method channel system uses an array and just looks at the length of the array to know if it's an error or success, which we can also do).

In discussions, @gaaclarke has suggested that we should implement a handshake during API setup to guarantee that the two sides of the channel are using the same version of Pigeon. I think that's a nice-to-have, but not a blocker for adopting this, since it's already the case that mismatched Pigeon versions can blow up in surprising ways.

/cc @tarrinneal

**Comment by gaaclarke** [comment]
I think it's worth considering skipping this optimization and jumping right to generating custom codecs.  It's similar work but would eliminate the runtime checks when serializing.

Also something to consider is going from `Dictionary<String, Object>` to `Dictionary<int, Object>` instead of `List<Object>`.  This eliminates the runtime cost of transmitting the Strings but is a bit more fault resistant than `List<Object>` since the key can be some value hash or the name of the parameter, maybe some like `make32BitHash(name) << 32 | parameterEnumeration` to make sure we don't have collisions.

**Comment by stuartmorgan** [comment]
> I think it's worth considering skipping this optimization and jumping right to generating custom codecs. It's similar work

Can you elaborate on what custom codecs would actually look like? I had been thinking about this again recently and it wasn't actually clear to me what the value of custom codecs is over just an array.

> but would eliminate the runtime checks when serializing.

Which runtime checks would it eliminate relative to arrays? (I actually think we should eliminate runtime checks regardless, but the problem seems the same either way.)

> but is a bit more fault resistant than `List<Object>` since the key can be some value hash or the name of the parameter

What fault would that prevent that a one-time handshake wouldn't? Pigeon is only designed to work with exact version matches, and arbitrarily bad things can happen if that's violated. Unless we have plans to change that (which has never been on the roadmap AFAIK), adding per-field identifiers seems like added complexity and inefficiency with no real-world benefit.

**Comment by gaaclarke** [comment]
> Which runtime checks would it eliminate relative to arrays? (I actually think we should eliminate runtime checks regardless, but the problem seems the same either way.)

So, right now everything transmitted over the channels uses the StandardMessageCodec.  Here is an example of the runtime checks for dart: https://github.com/flutter/engine/blob/b74af4c5a46da08ff32071d49780a2fa486e1877/lib/web_ui/lib/src/engine/services/message_codecs.dart#L343.  Those exist for for every platforms implementation of `StandardMessageCodec.encode`.

We can keep the same wireformat since the decoder doesn't have runtime checks but just remove the runtime checks for each encode implementation, one per method.  It would look something like this.

```dart
class BypassEncoder {
  const BypassEncoder();

  @override
  ByteData? encodeMessage(dynamic message) {
    // Just bypass this to avoid throwing away type information at runtime.
    return message;
  }
}

ByteData? _addEncodeArguments(double x, double y) {
  final WriteBuffer buffer = WriteBuffer();
  // Note: if we also wrote a custom decoder we could probably eliminate the List as well.
  // Look at this compared to StandardMessageCodec.encodeValue, no recursion and no runtime checks.
  buffer.putUint8(_valueList);
  writeSize(2);
  buffer.putUint8(_valueFloat64);
  buffer.putFloat64(x);
  buffer.putUint8(_valueFloat64);
  buffer.putFloat64(y);
  return buffer.done();
}

Future<double> add(double x, double y) async {
  BasicMessageChannel  channel = BasicMessageChannel(codec: BypassEncoder());
  return await channel.send(_addEncodeArguments(x, y)) as double;
}
```

> What fault would that prevent that a one-time handshake wouldn't?

Yep, a handshake would solve it also.  If we plan on doing that it isn't a big deal but it's probably not worth diving into unless we decide not to make the custom encoder.

**Comment by stuartmorgan** [comment]
> Here is an example of the runtime checks for dart:

Oh, I see, thanks. (I thought you meant the "did we get the expected type" runtime checks during decoding which is why I was confused.)

> It would look something like this

Ah, so not so much a custom codec as custom hand-rolled encoding (with the codec just there as a dummy). That's definitely way more work than using a list though; we either have to do that in addition to converting to a list (to make what you've shown work), or we have to write new decoders for every language. Implementing and testing a full decoder isn't trivial (having done it a couple of times for the standard codec).

It's still worth considering in the longer term certainly, but switching to arrays is low-hanging fruit. It will dramatically reduce message size in most cases with relatively little effort.

**Comment by gaaclarke** [comment]
> we either have to do that in addition to converting to a list (to make what you've shown work)

You mean changing the usage to a List is almost the same work as adjusting the callsites to use `_addEncodeArguments` but doesn't require the generation of `_addEncodeArguments`?  Yea, it's more work but it's faster too.  If we don't do it, we should at least implement using the List with the idea that it could get replaced (try to segregate the logic into a function that can be rewritten for example).

> we have to write new decoders for every language

Yea, I'm not advocating the custom decoders.

> It's still worth considering in the longer term certainly, but switching to arrays is low-hanging fruit. It will dramatically reduce message size in most cases with relatively little effort.

Yea, true.  I'll let you guys work out what size investment you want to make.

**Comment by stuartmorgan** [comment]
> You mean changing the usage to a List is almost the same work as adjusting the callsites to use `_addEncodeArguments` but doesn't require the generation of `_addEncodeArguments`?

Yes, and in fact:

> Yea, I'm not advocating the custom decoders.

if we de don't do custom decoders, then we have to make exactly the same changes either way to every non-Dart generator whichever version we do, because (unless we don't fix the thing this issue is about, which is the unnecessarily large message size) the `_addEncodeArguments` would be manually building a List.

So just switching to List makes it much easier to do custom encoding later, with minimal duplicate work even in the longer term.
