### ISSUE TITLE
 Scanning for devices is taking a long time...[☠] Connected device (the doctor check crashed)

### ISSUE THREAD

**Issue by TechnoTeluguMaurya** [flutter/flutter#111540]
Scanning for devices is taking a long time...[☠] Connected device (the doctor check crashed)
    X Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know
      about this issue at https://github.com/flutter/flutter/issues.
    X Exception: Connected device exceeded maximum allowed duration of 0:10:00.000000

**Comment by exaby73** [comment]
Hello @TechnoTeluguMaurya. Thank you for filing this issue. Can you please provide the following information?

- The output of `flutter doctor -v`
