### ISSUE TITLE
[Windows][a11y] Screen Reader not announcing the state of Switch

### ISSUE THREAD

**Issue by cbracken** [flutter/flutter#111525]
Minimal repro:
```dart
Scaffold(
  appBar: AppBar(
    // Here we take the value from the MyHomePage object that was created by
    // the App.build method, and use it to set our appbar title.
    // We also apply a custom font, ProductSans.
    title: Text(widget.title, style: TextStyle(fontFamily: 'ProductSans')),
  ),
  body: Column(
    children: [
      Switch(
        value: value,
        onChanged: onChanged,
      ),
    ],
  ),
);
```

Run NVDA or any other screen reader on the windows machine.

Press tab to move the focus to Switch

Actual: Reading as button and not tell the state of the switch

Expected : Should tell the state of the switch.

**Comment by cbracken** [comment]
@yaakovschectman and @loic-sharma may have some leads on this.

**Comment by yaakovschectman** [comment]
The `Switch` has semantics marking its role as a push button. Which role listed on https://docs.microsoft.com/en-us/windows/win32/winauto/user-interface-element-reference do we actually want switches to have? I do not think there is a dedicated role for switches like this, and I also do not think push buttons are supposed to have a toggleable state like our switches do. Functionally, they seem similar to checkboxes, even though they are different visually.

**Comment by loic-sharma** [comment]
Using the same role as a checkbox seems reasonable, the [Material design guidelines](https://material.io/components/switches#usage) describe switches as a checkbox for mobile & tablets:

> Use switches to turn an item on or off, especially on mobile instead of a checkbox.

**Comment by cbracken** [comment]
Agreed checkbox seems like the right semantics. [On the web](https://www.w3.org/TR/wai-aria-1.1/#switch) these are treated as having similar behaviour to checkboxes but with on/off status rather than checked/unchecked.  It seems reasonable to implement this as having checkbox semantics and then, if we need to fine-tune later, we can look at what chrome does for the switch role if necessary.

**Comment by yaakovschectman** [comment]
Closing for [flutter/engine#36177](https://github.com/flutter/engine/pull/36177)
