### ISSUE TITLE
Can a flutter package be built in a single javascript file as a library that can be imported into another web application?

### ISSUE THREAD

**Issue by OMaiZaregoto** [flutter/flutter#111549]
## Use case
Hi there,
I'm in a team which is developing our own cusomized flutter widgets. It has been for about 2 years. There are about 60-70 widgets developed as plugin package in our project.

However, recently, another team working with Web(using Angular) is wondering whether our developed flutter widgets can be imported to their web applications, so that both of us will save a lot of efforts to re-develop web-based widgets.

## Proposal
Although I'm not sure the issue type I've chosen is right, but here is my question：
Is Flutter now has the feature that supporting to build plugin package into a single javascript file as a library that can be imported into another web application? Or maybe there is a future plan about it?

Yours,
Sincerely

**Comment by exaby73** [comment]
Hello @OMaiZaregoto. Currently, the way Flutter works is that once the application is loaded, it takes over the entire body of the document. Adding a Flutter app into your webapp would basically overwrite your app and Flutter would take over. You could, for example, use an `iframe` to display a Flutter app that only has your widget. But that would require you to download multiple MB of data every time you use a widget.

Also, a lot of widgets in-built into Flutter require certain ancestors to be present. One such ancestor is `Material` which is provided by the `Scaffold` widget. 

Something similar to your use case is discussed in https://github.com/flutter/flutter/issues/32329. The tl;dr; is: rendering a Flutter app in a specified HTML element, similar to how React (and I believe Angular) does it. This could be the solution to your problem but it's yet to be something Flutter supports.

**Comment by OMaiZaregoto** [comment]
> 

Hi @exaby73 ，Thanks for your reply.
However, according to your reply , I think maybe there's something unclear about my problem. So I'll try to re-describe it.

In my case, another team using Angular(or may be React, etc.) wants to use our **flutter widgets** in their codes, which means they hope to import our **flutter widgets** as a **javascript library** to develop their product. 

For example, they write the `<script>` tag to import a **javascript file**, and **create a widget instance** in javascript, like what we do with jQuery: `var widget = new FlutterWidget()`;
Another example, they install a **flutter widget lib** using **npm** or **yarn**, and then use it in their javascript or typescript code.

Finally, the **flutter widget lib** will be packaged with their Angular(or may be React, etc.) project and be deployed on a server.

In a conclusion, I'm wondering is there any way to support the scene I described.

Yours,
Sincerely

**Comment by exaby73** [comment]
Hey @OMaiZaregoto. Thanks for the response.

What you're describing is currently not supported, and doesn't look like it would be feasible to support in the future. The closest implementation for this is to embed a Flutter application into an `iframe` and use the [`window.postMessage()`](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage) API to communicate between the two. 

You could write a wrapper around dynamically creating this `iframe` and pointing the URL to a Flutter web app hosted somewhere which would (kind of) be what you want the API to look like.

But since this is not a valid/feasible feature request, I am closing this issue. If you disagree, please comment and I can reopen it.
