### ISSUE TITLE
Material 3 Switch thumb size and motion isn't quite to spec

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#111663]
https://github.com/flutter/flutter/issues/103536#issuecomment-1243481591

Expected | Actual |
--- | --- | 
![image](https://user-images.githubusercontent.com/6655696/189622674-1ec7cbda-1603-4fd1-a87c-db56c1f14dca.png) | ![image](https://user-images.githubusercontent.com/6655696/189622937-771a1078-9870-45be-841d-f1660f299cef.png)

**Comment by HansMuller** [comment]
@guidezpl - can you explain how the "motion isn't quite to spec"?

**Comment by guidezpl** [comment]
I shared the full motion spec with @QuncCccccc, in short https://direct.googleplex.com/#/spec/291220003&293060003
