### ISSUE TITLE
[Impeller] Document how to enable validation layers using the tools in the Vulkan SDK.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#111611]
Validation layers can be enabled explicitly in code or via the GUI tools in the Vulkan SDK that allow inserting and enabling layers. Device profiles can also be configured using this tool.

Document (with screenshots) how to do this in the Impeller wiki.

**Comment by iskakaushik** [comment]
@chinmaygarde if this is completely in the context of Android, would you think that these would suffice here: https://github.com/flutter/engine/blob/main/impeller/docs/android_validation_layers.md ?

**Comment by chinmaygarde** [comment]
I think so. Thanks!
