### ISSUE TITLE
[Impeller] Come up with a heuristic/strategy for when to use different types of text rendering strategies.

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#111640]
Once SDF is implemented, we'll need a good heuristic for when to use it.

This will probably come down to something like the point size of the `TextRun` as well as the painting style (i.e. if it's stroked or not).

However, a single `TextFrame` might contain multiple runs with different point sizes. We'll probably have to refactor the API to create atlases for both SDF _and_ bitmap (or use a single atlas, but then communicate to users of the API whether a given glyph at a given size is SDF or bitmap).

In the initial pass at implementing SDF, I'm going to punt on this and require callers to specify which type of atlas they want to create.

**Comment by jonahwilliams** [comment]
Another caveat: if we're drawing an emoji (or less commonly a COLR font) then we can't use SDFs as far as I know

**Comment by jonahwilliams** [comment]
From my investigation, I've found that neither Path nor SDF rendering are really applicable with the kinds of workloads we have today. Skia itself only uses SDFs for very large (160pt+) fonts. Path rendering and SDFs are also quite slow compared to what we have access to for software rendering.

I'm closing this bug for now, as the answer seems to be "render in software even harder"
