### ISSUE TITLE
Import Webview by aar to Native Android is failed 

### ISSUE THREAD

**Issue by anhkhoi159** [flutter/flutter#111630]
1. Create a new flutter module with "flutter create -t module module_name"
2. Add a plugin to the module, I added webview_flutter and shared_preferences, but any plugin will cause an error
3. Create an AAR file by : Flutter build aar
4. Take the AAR from the ./android/Flutter/build/outpurs/aar/flutter_release-1.0.aar and add it to my existing Android project.
5. Add the code to launch the flutter view from here: https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps
Run app and see WebView error
![image](https://user-images.githubusercontent.com/55753138/190295670-045b7d3e-0230-4eeb-800c-f88877d5fd5a.png)

**Comment by exaby73** [comment]
Hello @anhkhoi159. Please refrain from raising multiple issues for the same bug. Closing in favor of https://github.com/flutter/flutter/issues/111546

**Comment by anhkhoi159** [comment]
> Hello @anhkhoi159. Please refrain from raising multiple issues for the same bug. Closing in favor of #111546

hi @exaby73  https://github.com/anhkhoi159/mymoduleapp this is my project, pls help me check

**Comment by exaby73** [comment]
@anhkhoi159 This issue was closed as a duplicate. Please follow up on the original https://github.com/flutter/flutter/issues/111546
