### ISSUE TITLE
iOS 16 text selection menu

### ISSUE THREAD

**Issue by justinmc** [flutter/flutter#111671]
iOS 16 has changed the text selection menu.

| iOS 16 | Flutter |
| --- | --- |
| <video width="250" src="https://user-images.githubusercontent.com/389558/190456663-ecb9fb40-94c3-405d-801e-422ebedb6754.mp4" /> | <video width="250" src="https://user-images.githubusercontent.com/389558/190457810-387c35f7-8c93-489b-a5fa-8ce3c7b32e7f.mov" /> |

The main differences I see are:

  * Light mode version.
  * New show/hide animation.
  * The overflow button uses a slightly different icon.

### Reference

  * An article that talks about it:
    - https://www.macstories.net/stories/ios-16-the-macstories-review/2/#content
   * There's also a new button:
     - https://github.com/flutter/flutter/issues/111672

  - [x] Light mode: https://github.com/flutter/flutter/pull/115805
  - [ ] In/out animation

CC @MitchellGoodwin

**Comment by goderbauer** [comment]
iOS 16 also integrates a handy unit converter in the selection menu as seen in the second set of screenshots here: https://www.macstories.net/stories/ios-16-the-macstories-review/14/#content

**Comment by justinmc** [comment]
Thanks, here's the issue I just created for the unit converter button: https://github.com/flutter/flutter/issues/111672
And an older issue with other missing buttons: https://github.com/flutter/flutter/issues/107578

**Comment by justinmc** [comment]
Here are some good screenshots of the native toolbar from a duplicate issue (https://github.com/flutter/flutter/issues/113584):

| Native iOS 16 light mode | Native iOS 16 dark mode |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/389558/197072104-65dbee59-40b9-4472-9747-e2cffc2e5025.png) | ![image](https://user-images.githubusercontent.com/389558/197072249-87f06945-9fd9-4836-87f2-ad4ee1c047bf.png) |

**Comment by justinmc** [comment]
Update: We still don't have the in/out animation as indicated in the description of this issue. However, it is possible to use the native menu itself if wanted as of https://github.com/flutter/flutter/pull/148265.

**Comment by Piinks** [comment]
> We still don't have the in/out animation as indicated in the description of this issue.

@justinmc is that the same as https://github.com/flutter/flutter/issues/54470?

**Comment by victorsanni** [comment]
@justinmc closing as the second part of this issue is represented in #54470.
