### ISSUE TITLE
[CP] Make ImpellerC handle unicode characters in paths

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#111689]
### issue_link

https://github.com/flutter/flutter/issues/107590

### Commit Hash

b6f4f8dd4a5647d0c6da39fce85ff380218a1d1f

### Target

stable

### pr_link

https://github.com/flutter/engine/pull/36158

### Impacted Users

Flutter devs who have non-ASCII characters in project paths

### Impact Description

Tool crashes on building Flutter projects.

### Workaround

Rename directory to not contain unicode characters.

### Risk

low

### Test Coverage

no

### Validation Steps

We are working on automated tests for this (e.g. including unicode characters in testing done on CI).

To validate, on a Windows machine, introduce a unicode character into the project path and try to run `flutter run -d windows`.

**Comment by zanderso** [comment]
The PR link should be a PR to do the CP into the release branch. I think in this case that would be https://github.com/flutter/engine/tree/flutter-3.2-candidate.5

**Comment by jason-simmons** [comment]
Created a cherry pick PR: https://github.com/flutter/engine/pull/36185

**Comment by zanderso** [comment]
CP lgtm cc @christopherfujino @itsjustkevin this fixes the highest frequency tooling crasher.

**Comment by itsjustkevin** [comment]
Merged into stable as https://github.com/flutter/engine/commit/24efd81e3ebdf417041f044059a0682f8b570972.

**Comment by CaseyHillers** [comment]
Released in https://github.com/flutter/flutter/releases/tag/3.3.3
