### ISSUE TITLE
`//flutter/fml/backtrace.h` doesn't support Windows.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#111614]
The [implementation is empty currently](https://github.com/flutter/engine/blob/a26a6656ce68d76cbc969d707f26e98916481276/fml/backtrace_stub.cc#L19) as it defaults [to the stub on Windows](https://github.com/flutter/engine/blob/a26a6656ce68d76cbc969d707f26e98916481276/fml/BUILD.gn#L102).

Not having this gets in the way of debugging Windows specific crashes like https://github.com/flutter/flutter/issues/107590.

We should add an implementation for Windows and get rid of the stub.

**Comment by chinmaygarde** [comment]
@loic-sharma @cbracken @zanderso: Do you know how backtrace reporting and core dumps work on Windows? My familiarity with Windows isn't great.

**Comment by cbracken** [comment]
I swore we had a bug for this. Agreed this would be very useful; I've added to the desktop project. I'm not familiar with Windows core dumps, but we'll get somebody familiar with it.

**Comment by moko256** [comment]
I'm investigating this. I found `CaptureStackBackTrace`, a Windows version of execinfo's `backtrace`. The `absl::Symbolize` is already supporting Windows.

I'll wire-up these and create PR.
