### ISSUE TITLE
[Impeller] Document how to capture and profile GPU workloads on Vulkan / OpenGL ES.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#111607]
Similar to how we document the steps to [capture](https://github.com/flutter/engine/blob/d24e5d7c394111f04756b5326dc9312de7c11d16/impeller/docs/xcode_frame_capture.md) and [read](https://github.com/flutter/engine/blob/d24e5d7c394111f04756b5326dc9312de7c11d16/impeller/docs/read_frame_captures.md) GPU workloads on Metal, we should have detailed documentation for the Vulkan and OpenGL ES. There is no one good way to do this so the following tools will need to be investigated.

* RenderDoc
* ARM Mali Debugger
* Android GPU Inspector
* Snapdragon Profiler
* NVidia Nsight

**Comment by iskakaushik** [comment]
RenderDoc frame capture is documented over here: https://github.com/flutter/engine/blob/main/impeller/docs/renderdoc_frame_capture.md
