### ISSUE TITLE
Icons.whatsapp removed 

### ISSUE THREAD

**Issue by Abhijit-Revamp** [flutter/flutter#111667]
Any reason the WhatsApp icon is removed from icons.dart?
Commit #111092

**Comment by huycozy** [comment]
@bobosette I think this [comment](https://github.com/flutter/flutter/issues/103202#issuecomment-1120079080) can explain this change.
/cc @guidezpl for clarification

**Comment by guidezpl** [comment]
I won't speculate as to why, but it's no longer available https://fonts.google.com/icons?icon.query=whatsapp&icon.set=Material+Symbols, https://fonts.google.com/icons?icon.query=whatsapp&icon.set=Material+Icons.
