### ISSUE TITLE
flutter doctor timing out on flutter/flutter CI build

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#111686]
1. For the engine roll PR https://github.com/flutter/flutter/pull/111655
2. For the Windows windows_home_scroll_perf__timeline_summary pre-submit check https://ci.chromium.org/ui/p/flutter/builders/try/Windows%20windows_home_scroll_perf__timeline_summary/10543/overview
3. The flutter doctor step was timed out 3 times after 5 minutes

Because the doctor schedules many asynchronous validators at once and then awaits them each one by one, it is not obvious from the logs what was hanging. In addition, the doctor validators themselves have a 10 minute timeout, after which it will log which validator timed out. We should either extend the LUCI/recipe level 5 minute timeout, or reduce the doctor level one.

**Comment by christopherfujino** [comment]
2 out of the last 7 engine roll PRs were closed because of this issue

**Comment by keyonghan** [comment]
Some failed builds in post-submit CI: https://github.com/flutter/flutter/issues/111566

**Comment by nehalvpatel** [comment]
Are you still working on this? @christopherfujino

**Comment by christopherfujino** [comment]
Closing this as it seems like hte issue is resolved
