### ISSUE TITLE
[CP] Ensure pre-rolled opacity children see snapped matrix

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#111693]
### issue_link

110957

### Commit Hash

3284e30 

### Target

stable

### pr_link

https://github.com/flutter/engine/pull/36181

### Impacted Users

desktop users

### Impact Description

Pixel snapping when using animated opacity layers at certain DPRs and screen sizes

### Workaround

No workaround.

### Risk

low

### Test Coverage

yes

### Validation Steps

Automated tests confirm the snapped matrix is used.

**Comment by itsjustkevin** [comment]
@dnfield could you review this cherry pick and the associated pr?

**Comment by dnfield** [comment]
LGTM

**Comment by itsjustkevin** [comment]
@jonahwilliams and @dnfield it was pointed out to me by @zanderso that I missed this cherry-pick.  Apologies, it is merged and will be picked up in the next release.
