### ISSUE TITLE
[image_picker] make the video compress optional or disable completely 

### ISSUE THREAD

**Issue by rlueders** [flutter/flutter#111698]
The Image Picker's video compression should be optional or disabled completely.  In my usecase, my app is opening a video to to perform some editing for the user, then saves the edited video back to the user's gallery. Below are the reasons compression causes a problem. 

1. It is not possible to retain the original/full quality of the original input video in the edited output video. This is because the plugin has already compressed the video before it is even edited. In most cases, the users would like to retain the original quality of the video. 
2. The compression process appears to be stripping & changing the meta data of the video. This is a problem because my app uses ffprobe to make use of the video's metadata as part of the editing process. The video returned to the app is basically a totally different video than what was selected (different resolution, metadata, etc.).
3. The compression injects and additional and substantial delay in the file open process (especially for larger files) while the users waits for the video to compress. Meanwhile the users has not even asked for their video to be compressed. 
4. It is different from android. The same package on android does not compress videos. Platform differences like this greatly reduce the value of Flutter as developers must still handle different behavior for different platforms.

**Comment by huycozy** [comment]
Hi @rlueders, thanks for filing the issue. 
I see there's an open issue addressing the case you described #24954
Closing this issue as a duplicate, so please follow up on it for further updates. You can leave there your comment and react an upvote to the original comment will help to raise the issue. Thank you!
