### ISSUE TITLE
allow choosing ResolutionPreset in imagePicker

### ISSUE THREAD

**Issue by QTree-app** [flutter/flutter#111653]
would be nice to have the ability to choose a Resolution preset when taking a picture with imagePicker - same as in the camera package.

**Comment by exaby73** [comment]
Hello @QTree-app. I am not sure if that's the same since the `camera` plugin embeds a camera view inside the Flutter app while `image_picker` opens the OS default camera app to take the picture

**Comment by QTree-app** [comment]
ho. I get it. didn't know that. thanks for the quick response!
