### ISSUE TITLE
I am trying to initialize multiple cameras at once in flutter application , Is there a way to do it?

### ISSUE THREAD

**Issue by SaleemSirreyh** [flutter/flutter#111690]
I am trying to initialize multiple cameras at once in flutter application , Is there a way to do it?

**Comment by danagbemava-nc** [comment]
Hi @SaleemSirreyh, this is currently not supported. There is an issue open requesting this feature in https://github.com/flutter/flutter/issues/51928. 

Kindly follow up in the issue linked above for updates. 

Closing from here as duplicate. 

Thank you
