### ISSUE TITLE
[pigeon] Java generator code with some warning

### ISSUE THREAD

**Issue by 5peak2me** [flutter/flutter#111634]
**some method such as below has lint warnings**

```java
protected Object readValueOfType(byte type, ByteBuffer buffer) {
   ··· omit ···
}
protected void writeValue(ByteArrayOutputStream stream, Object value) {
   ··· omit ···
}
```

**Comment by huycozy** [comment]
Hi @5peak2me, thanks for filing the issue. 
I see there are some open issues addressing the case you described #110769, #59116
Closing this issue as a duplicate, so please follow up on it for further updates. You can leave there your comment and react an upvote to the original comment will help to raise the issue. Thank you!

**Comment by 5peak2me** [comment]
Thanks！
