### ISSUE TITLE
Expansion Panels in Tab View break due to global keys

### ISSUE THREAD

**Issue by BenSower** [flutter/flutter#11166]
## Steps to Reproduce
Create a tab view, filled with ExpansionPanelLists. 
This breaks, since ExpansionPanelList give their children ValueKeys based on their respective position in the children array (e.g. 0,2,4...). Expansion_panel.dart, line 147: `key: new ValueKey<int>(i * 2)` (i being the array-index). Since these are then being converted into _MergeableMaterialSliceKeys and therefor GlobalKeys in mergable_material.dart, one cannot "have" more than one expansion panel at a time. The index is being used to allow for an easier looping over the ListItems

Do you think this could be solved by passing an optional unique key to each ExpansionPanelList, which would then be passed through to _MergableMaterialSliceKeys and properly handled there instead of polluting the global namespace with very un-unique int-based Keys?

```
import 'package:flutter/material.dart';

void main() {
  runApp(new MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: 'Flutter Demo',
      theme: new ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: new MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => new _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> with SingleTickerProviderStateMixin {
  TabController _controller;

  @override
  void initState() {
    super.initState();
    _controller = new TabController(vsync: this, length: 2, initialIndex: 0);
  }

  ExpansionPanelList _getExpansionPanel(String body) {
    print(body);
    return new ExpansionPanelList(
      expansionCallback: (int index, bool isExpanded) {},
      children: <ExpansionPanel>[
        new ExpansionPanel(
            body: new Text('Body'),
            isExpanded: true,
            headerBuilder: (BuildContext context, bool isExpanded) {
              return new Text(body);
            }),
      ],
    );
  }

  @override
  Widget build(BuildContext context) {
    return new Scaffold(
        appBar: new AppBar(title: new Text(widget.title)),
        body: new Column(
          children: ['one', 'two'].map(_getExpansionPanel).toList(),
        ));
  }
}
```

## Logs
```
I/flutter ( 1364): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 1364): The following assertion was thrown building DefaultTextStyle(inherit: false; color:
I/flutter ( 1364): Color(0xdd000000); family: "Roboto"; size: 14.0; weight: 400; baseline: alphabetic):
I/flutter ( 1364): Multiple widgets used the same GlobalKey.
I/flutter ( 1364): The key _MergeableMaterialSliceKey([<0>]) was used by multiple widgets. The parents of those widgets
I/flutter ( 1364): were different widgets that both had the following description:
I/flutter ( 1364):   DefaultTextStyle(inherit: false; color: Color(0xdd000000); family: "Roboto"; size: 14.0; weight:
I/flutter ( 1364):   400; baseline: alphabetic)
I/flutter ( 1364): A GlobalKey can only be specified on one widget at a time in the widget tree.
I/flutter ( 1364): 
```

## Flutter Doctor
```
[✓] Flutter (on Linux, locale en_US.UTF-8, channel alpha)
    • Flutter at /home/ben/Desktop/Dev/flutter/flutter
    • Framework revision d36e2f6191 (3 weeks ago), 2017-06-21 15:09:10 -0700
    • Engine revision b0dee695ec
    • Tools Dart version 1.24.0-dev.6.7

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at /home/ben/Android/Sdk
    • Platform android-25, build-tools 25.0.3
    • Java binary at: /usr/local/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] Android Studio (version 2.3)
    • Android Studio at /usr/local/android-studio
    • Gradle version 3.2
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] Connected devices
    • SM G920F • 05157df52d643b04 • android-arm • Android 7.0 (API 24)
```

**Comment by Hixie** [comment]
Another solution would be to salt the keys when they are converted to global keys, e.g. by combining the value with the State or BuildContext that is creating them.

**Comment by ds84182** [comment]
What about global key namespaces to wrap manual salting with an easy to use API?

Something like:

```dart
Widget build(BuildContext context) {
  final GlobalKeyNamespace namespace = new GlobalKeyNamespace(salt: context);
  // The salt can be any object
  return new Widget(key: namespace.keyFor("another value here"));
}
```

keyFor would return something like a "NamespacedGlobalKey" which can be used like a normal GlobalKey, except that when two of them are compared it also compares the salts given to their namespace.

**Comment by Hixie** [comment]
Interesting idea.

**Comment by BenSower** [comment]
Alternatively, is there a way to solve this Problem
```
// The parent hierarchy can change and lead to the slice being
// rebuilt. Using a global key solves the issue.
(mergable_material.dart 613)
```
more elegantly and avoid having to use another layer of abstraction entirely?

**Comment by Skylled** [comment]
Has any more thought been given to this problem?

I was hoping to have a few `ExpansionPanelList`s on separate Cards in a `ListView`.

Perhaps `ExpansionPanelList` could take in an optional string `prefix` and change all `ValueKey<int>`s to `ValueKey<String>`s?

I only took a cursory look, but I didn't immediately see any reasons why the keys needed to be `int`.

**Comment by Hixie** [comment]
The easiest solution is just to create a `ValueKey<Foo>` where `Foo` takes the state of the ExpansionPanelLists and an int (and has suitable const constructor, operator==, and hashCode implementations). That should be easy to implement (and easy to test, just make sure that what doesn't work today, works with the patch!). We would happily accept such a PR.

**Comment by Skylled** [comment]
I can't seem to find a way, without introducing complexity, to get reproducible keys. Expanding a panel seems to reinitialize the containing list and generates a new `hashCode`, which is the only identifying property I've found. (I'm using an implementation based on the [flutter_gallery example](https://github.com/flutter/flutter/blob/def0b4203acdb8b74f5581ae149693b985143ad6/examples/flutter_gallery/lib/demo/material/expansion_panels_demo.dart).)

I can't find anything to give to `Foo` to indicate the same initial widget.

I've thought about overriding the hashCode getter, using `hashList(children)` but that would be a breaking change to anything based on the gallery demo, as it uses `.map().toList()` to generate the children so their hashCodes are all changed.

I'm sure my understanding of Flutter/Dart is just lacking.

When I was able to get reproducible keys, using a rudimentary `string keyPrefix` and `new ValueKey<String>("$keyPrefix${i * 2 - 1}")` method, everything worked flawlessly, but I know there's likely a more elegant/idiomatic way of doing it.

I'd like to learn more here, but need some direction.

**Comment by Hixie** [comment]
Something like this (I haven't tried compiling this but it should work modulo some typos):

```dart
class _SaltedKey<S, V> extends LocalKey {
  const _SaltedKey(this.salt, this.value);

  final S salt;
  final V value;

  @override
  bool operator ==(dynamic other) {
    if (other.runtimeType != runtimeType)
      return false;
    final _SaltedKey<S, V> typedOther = other;
    return salt == typedOther.salt
        && value == typedOther.value;
  }

  @override
  int get hashCode => hashValues(runtimeType, salt, value);

  @override
  String toString() {
    final String saltString = S == String ? '<\'$salt\'>' : '<$salt>';
    final String valueString = V == String ? '<\'$value\'>' : '<$value>';
    return '[$saltString $valueString]';
  }
}
```

You would create it something like `new _SaltedKey<ExpansionPanelListState, int>(this, index)`.

**Comment by Skylled** [comment]
Is there something else I'm not understanding? ExpansionPanelList is a stateless widget.

**Comment by Hixie** [comment]
Oops, sorry, I didn't look at the actual case. If you need to create a salted key from a stateless widget, use the BuildContext as the salt instead of the State. The effect is the same.
