### ISSUE TITLE
Flutter TextFormField InputFormatters not working as expected. - FilteringTextInputFormatter.allow not working with regular expressions.

### ISSUE THREAD

**Issue by MungaraJay** [flutter/flutter#111731]
I was trying to add a simple regular expression in my TextFormField inputFormatters. But, it's not working as it should.

```
TextFormField(
  inputFormatters: [
     FilteringTextInputFormatter.allow(RegExp(r'^(?:3|5|6|7|8|9|)[0-9]{7}$'))
  ],
)
```

Expected results:

it should match and allow as per expected expression

Actual results:

Not letting add any kind of user input.

When trying with the dartpad this expression seems to be working fine. But, with FilteringTextInputFormatter.allow inputFormatters not seems to be working.

Can anyone please help with this?

Thanks

**Comment by darshankawar** [comment]
@MungaraJay 
Please check below comments on the usage of `FilteringTextInputFormatter` and see if it helps to answer your. qeustion:

https://github.com/flutter/flutter/issues/107223#issuecomment-1179430378
 https://github.com/flutter/flutter/issues/107223#issuecomment-1179431134
 https://github.com/flutter/flutter/issues/78100#issuecomment-1179443330

Also check this update to the documentation for reference:

 https://github.com/flutter/flutter/pull/107848/files
