### ISSUE TITLE
Changes that break test_runner aren't caught in presubmit checks

### ISSUE THREAD

**Issue by ianloic** [flutter/flutter#11176]
https://github.com/flutter/engine/pull/3833 breaks the fuchsia build because of this error in the host (Linux) test_runner build:
```
../../flutter/shell/testing/test_runner.cc:17:19: error: no member named 'Attach' in 'shell::PlatformView'
 platform_view_->Attach();
 ~~~~~~~~~~~~~~  ^
```
This should be caught by travis builds and reflected in the dashboards.

**Comment by jason-simmons** [comment]
The engine Travis script doesn't build the engine binaries for any platform - it runs dartanalyzer on the engine's Dart code and runs the license checker script.  The Chromium buildbot scripts build the engine, but that doesn't run until a change is submitted.

@yjbanov

**Comment by zoechi** [comment]
Is this issue still relevant?

**Comment by kf6gpe** [comment]
This will be fixed when we extract the Flutter runner into the engine; work being done as part of FL-250.

**Comment by kf6gpe** [comment]
FL-250 is tracked in github as https://github.com/flutter/flutter/issues/33991

**Comment by iapicca** [comment]
Hi @ianloic 
given the merged  PR 
is this issue still meant to be open?

**Comment by iskakaushik** [comment]
duplicate of: https://github.com/flutter/flutter/issues/44826
