### ISSUE TITLE
iOS simulator is not working . Also not working for emulator.

### ISSUE THREAD

**Issue by Akshay2941** [flutter/flutter#111743]
Expected ios/Runner.xcodeproj but this file is missing.
<img width="1440" alt="Screenshot 2022-09-16 at 17 53 59" src="https://user-images.githubusercontent.com/102019720/190638236-58441ab0-9236-4ddc-82a9-31fb7344f049.png">

**Comment by darshankawar** [comment]
@Akshay2941 
Can you provide `flutter doctor -v` ? Is that the new flutter project you created ? or an existing one ?
Does `Runner` folder has `Info.plist` ? 
If you run `flutter create .`, does the said file get created ?
Can you also provide `pubspec.yaml` and `.metadata`  file ?
Also, `cd` to the project that's missing the Xcode project, and attach `flutter create -v`.

**Comment by Akshay2941** [comment]
<img width="1440" alt="Screenshot 2022-09-20 at 20 18 27" src="https://user-images.githubusercontent.com/102019720/191290373-8d85e367-0ecc-4d6d-b2b2-bad36d99f624.png">


it's new flutter project.
in the beginning it was working but I think I might have deleted that .xcodeproj file

**Comment by Akshay2941** [comment]
<img width="1440" alt="Screenshot 2022-09-20 at 20 25 40" src="https://user-images.githubusercontent.com/102019720/191292103-481b93f4-dfaf-43d5-b5d9-57c114296bf6.png">


Yes, Runner folder has Info.plist file

**Comment by Akshay2941** [comment]
<img width="1440" alt="Screenshot 2022-09-20 at 20 28 01" src="https://user-images.githubusercontent.com/102019720/191292687-f11d1268-bcdc-4495-9a0c-1726af95e2c6.png">

NO, the said file is not creating.

**Comment by Akshay2941** [comment]
<img width="1440" alt="Screenshot 2022-09-20 at 20 31 19" src="https://user-images.githubusercontent.com/102019720/191293572-34107b6a-a2d5-4092-91a4-c6b7dc00168a.png">



Pubspec.yaml

**Comment by Akshay2941** [comment]
Also, cd to the project that's missing the Xcode project, 


about this I am not sure how to do this.

**Comment by Akshay2941** [comment]
also , the .gitignore sign is disable.

**Comment by Akshay2941** [comment]
and for Android


<img width="1440" alt="Screenshot 2022-09-20 at 20 54 13" src="https://user-images.githubusercontent.com/102019720/191299339-7efa97b7-85aa-41d5-b6f0-67b4bdfab098.png">

**Comment by darshankawar** [comment]
The Android emulator error is `install_failed_insufficient_storage` meaning there's no free space in the emulator you are using, so free up some space by deleting unused apps and then try, which should resolve Android emulator error.

Regarding iOS, please don't post screenshots of the details requested. Provide the same in text format so that we can use it properly.

I see that you are on Xcode 14, did you upgrade Xcode recently ? If so, did it work before upgrading ?

**Comment by Akshay2941** [comment]
it was resolved.
