### ISSUE TITLE
Tap Area inconsistent based on color

### ISSUE THREAD

**Issue by Hari-07** [flutter/flutter#111730]
## Steps to Reproduce

1. Execute `flutter run` on [Dartpad link](https://dartpad.dev/?id=37321ff7bb81fdc0bfe0c3d3bd6d195e)
2. Tap on the red area, then Tap on the white area to the right of the first element
3. Gestures get detected only in the region where there's color even though its the exact same widget structure thus layout should have worked properly

**Expected results:** 
Taps should have worked in either case

**Actual results:** 
Taps only work when there's a color

[Dartpad link](https://dartpad.dev/?id=37321ff7bb81fdc0bfe0c3d3bd6d195e)

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by darshankawar** [comment]
@Hari-07 
Try adding `behavior: HitTestBehavior.translucent,` which should resolve the behavior. With this, it detects the tap when you tap on area other than `red` color and it recognizes it. I verified the same on the same dartpad link you shared above.

Closing as this should resolve the issue. If you disagree, write in comments and I'll reopen it.

**Comment by Hari-07** [comment]
The default behavious [HitTestBehavior.deferToChild](https://api.flutter.dev/flutter/rendering/HitTestBehavior.html) says the tap is recognised if one of its children is hit by the tap. Here the child of the GestureDetector is a Container. The Container's size should never be determined by its color , as such this still seems like a bug to me

**Comment by bleroux** [comment]
From Container documentation (https://api.flutter.dev/flutter/widgets/Container-class.html):
"By default, containers return false for all hit tests. If the [color](https://api.flutter.dev/flutter/widgets/Container/color.html) property is specified, the hit testing is handled by [ColoredBox](https://api.flutter.dev/flutter/widgets/ColoredBox-class.html), which always returns true. If the [decoration](https://api.flutter.dev/flutter/widgets/Container/decoration.html) or [foregroundDecoration](https://api.flutter.dev/flutter/widgets/Container/foregroundDecoration.html) properties are specified, hit testing is handled by [Decoration.hitTest](https://api.flutter.dev/flutter/painting/Decoration/hitTest.html)."
