### ISSUE TITLE
Add onShowPopupMenu on PopupMenuButton

### ISSUE THREAD

**Issue by andrewwakeling** [flutter/flutter#111704]
## Use case

We want to know when users are opening the popup menu so we can fire an analytics event reliably.

## Proposal

Add a `onShowPopupMenu` function which is invoked each time the popup menu is displayed to the user.

See previous discussion about this here: https://github.com/flutter/flutter/issues/21773

**Comment by danagbemava-nc** [comment]
Hi @andrewwakeling, https://github.com/flutter/flutter/pull/103753 added an `onOpened` callback to the `PopupMenuButton`, does this not suffice for your use case? 

This feature is currently only available on the `master` channel.
