### ISSUE TITLE
Signing errors on macOS pod bundle resources on Xcode 14 "Signing for "x" requires a development team."

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#111755]
macOS version of https://github.com/flutter/flutter/issues/111475.

> Since I upgraded to Xcode 14, my Flutter project doesn't run because of Signing issues of iOS pods
> 
> Error:
> 
> ```
> Could not build the precompiled application for the device.
> Error (Xcode): Signing for "DKPhotoGallery-DKPhotoGallery" requires a development team. Select a development team in the Signing & Capabilities editor.
> {path to project folder}/ios/Pods/Pods.xcodeproj
> 
> Error (Xcode): Signing for "DKImagePickerController-DKImagePickerController" requires a development team. Select a development team in the Signing & Capabilities editor.
> {path to project folder}/ios/Pods/Pods.xcodeproj
> 
> Error (Xcode): Signing for "TOCropViewController-TOCropViewControllerBundle" requires a development team. Select a development team in the Signing & Capabilities editor.
> {path to project folder}/ios/Pods/Pods.xcodeproj
> ```
> 
> My project's dependencies (to reproduce the problem, the error is from one of these dependencies and the corresponding iOS Pod)
> flutter doctor -v:
> [✓] Flutter (Channel stable, 3.3.1, on macOS 12.6 21G115 darwin-arm, locale en-NL)

Need to find an example plugin that reproduces this, as google_sign_in is not supported on macOS.

**Comment by jmagman** [comment]
@cbracken this will cause macOS apps not to build if any dependencies contain a resource bundle.  https://github.com/flutter/flutter/issues/111475 iOS variant was a `customer: crowd`.

**Comment by jmagman** [comment]
The iOS fix was https://github.com/flutter/flutter/pull/111714.  The same change needs to be made to https://github.com/flutter/flutter/blob/1b583a837d692e73488a8ea6b8ab696d1e75bc41/packages/flutter_tools/bin/podhelper.rb#L96  I would have just done this myself in the same PR but there's no good existing macOS tests for this area so it would have taken much longer, and I wanted to get the iOS change out ASAP.

**Comment by cbracken** [comment]
Thanks; picking this up now on the macOS side.

**Comment by cbracken** [comment]
Great news is this was fixed by @jmagman in https://github.com/flutter/flutter/pull/82048 1.5 years ago!
