### ISSUE TITLE
Add the ability of random access to drawing operations in DisplayList.

### ISSUE THREAD

**Issue by endless7** [flutter/flutter#111736]
There is a rTree in DisplayList now. DisplayList organizes the drawing operations in an array now. With the ability of random access to drawing operations we can use rTree better.

The ability of random access to drawing operations also benefits [#108715](https://github.com/flutter/flutter/issues/108715)

**Comment by ColdPaleLight** [comment]
related issue https://github.com/flutter/flutter/issues/92740
cc @flar

**Comment by flar** [comment]
We can have random access via storing offsets, but that isn't very safe. The question is how much does it cost us to iterate through the array and only execute the items that are selected by the RTree search? I'm marking this as very low priority until we can get at least culling of the ops we executing working.

**Comment by endless7** [comment]
> We can have random access via storing offsets, but that isn't very safe. The question is how much does it cost us to iterate through the array and only execute the items that are selected by the RTree search? I'm marking this as very low priority until we can get at least culling of the ops we executing working.

This issue is related to the rtree of dl we talked before. And I want to land the rtree of dl with the ability of random access.

**Comment by flar** [comment]
> This issue is related to the rtree of dl we talked before. And I want to land the rtree of dl with the ability of random access.

Why is random access necessary? How much does iteration with no execution really cost that we need to completely redesign a mechanism to achieve random access lookup?

**Comment by flar** [comment]
Now that https://github.com/flutter/engine/pull/38429 is merged, can this be closed?

**Comment by ColdPaleLight** [comment]
> Now that [flutter/engine#38429](https://github.com/flutter/engine/pull/38429) is merged, can this be closed?

Yes, it can be closed.
