### ISSUE TITLE
[LSP]VS Code automatically prompt parameter types

### ISSUE THREAD

**Issue by git2321231** [flutter/flutter#111718]
After I executed the flutter upgrade yesterday, VS Code added a function to automatically prompt parameter types (yellow blocks on the figure). How can I turn this function off? This seems to be related to LSP? I really don't need this hint.Someone help me please.

![截屏2022-09-16 10 40 18](https://user-images.githubusercontent.com/11640176/190545052-49cee9c2-92b6-4bbd-a715-8969182793c2.png)

flutter doctor -v:

[✓] Flutter (Channel master, 3.4.0-19.0.pre.273, on macOS 12.5 21G72 darwin-x64, locale zh-Hans-CN)
    • Flutter version 3.4.0-19.0.pre.273 on channel master at /Users/hanshow/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 05e0dc2e44 (19 hours ago), 2022-09-15 03:42:24 -0400
    • Engine revision 8134f565c7
    • Dart version 2.19.0 (build 2.19.0-201.0.dev)
    • DevTools version 2.17.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/hanshow/Library/Android/sdk
    • Platform android-31, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A309
    • CocoaPods version 1.11.2

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.71.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (1 available)
    • iPhone 14 Pro Max (mobile) • E9F5DD14-1AB4-4B97-9CBA-0B234CF9D7CC • ios • com.apple.CoreSimulator.SimRuntime.iOS-16-0 (simulator)

[✓] HTTP Host Availability
    • All required HTTP hosts are available

**Comment by danagbemava-nc** [comment]
Hi @git2321231, this is a feature of vscode which was enabled by the dart SDK. You can disable this by going to your settings in vscode and disabling `inlay hints`. 

I'll be closing this as it is not a flutter issue. 

Thank you

**Comment by git2321231** [comment]
@danagbemava-nc Thank you!

**Comment by DanTup** [comment]
Sorry for the bother. I hadn't noticed VS Code defaulted to always showing these. I had set mine to "offUnlessPressed" (which means they only show up while Ctrl+Option is held down) while testing and assumed it was opt-in.

I'm going to [override the default for Dart](https://github.com/Dart-Code/Dart-Code/issues/4162) in the next extension update.

**Comment by DanTup** [comment]
I've pushed a patch release of the Dart extension (v3.48.4 and pre-release v3.49.20220916) that overrides this default. Please let me know if you still see this showing up by default after installing one of those and reloading.

With the new default, they'll only show up while Ctrl+Option(Alt?) are held down.

**Comment by git2321231** [comment]
@DanTup Yes, it works! Thanks for repairing so quickly!

**Comment by DanTup** [comment]
Great, thanks for confirming!
