### ISSUE TITLE
[Impeller] Support gradients with overlapping stops on non-SSBO backends.

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#111775]
Currently the overflow indicator creates a LinearGradient with stops 0.25, 0.25, 0.75, 0.75. We can't draw this correctly today, because our gradient implementation cannot handle the required hard color transition. In this case, we need to both insert 0.0 and 1.0 color stops and values and fall back to a different implementation of the shader that uses a binary search

**Comment by jonahwilliams** [comment]
No, this still isn't implented

**Comment by jonahwilliams** [comment]
This is done for the SSBO gradients, but not for texture gradients. Since we're not shipping anything that uses the texture gradients yet we're still good but we'll need to do something for openGL

**Comment by jonahwilliams** [comment]
Dropping to P3 since this is GLES only

**Comment by flar** [comment]
I thought this was adjusted in the DlGradient classes, but it looks like they just copy the values along. We should probably normalize the stops and colors at the DL level to avoid having to do it on each use.

**Comment by jonahwilliams** [comment]
Fixed via https://github.com/flutter/engine/pull/56441
