### ISSUE TITLE
Getting this error and flutter clean is not helping can anyone help

### ISSUE THREAD

**Issue by amitupadhyay11** [flutter/flutter#111781]
Function call

  static const platform = MethodChannel("flutter.native/helper");
  String _responseFromNativeCode = 'Waiting for Response...';
  Future<void> responseFromNativeCode() async {
    String response = "";
    try {
      
      final String result = await platform.invokeMethod("helloFromNativeCode");
      response = result;
    } on PlatformException catch (e) {
      // response = "Failed to Invoke: '${e.message}'.";
      final String result = await platform.invokeMethod("helloFromNativeCode");
      response = result;
      log(response.toString());
    }
    setState(() {
      _responseFromNativeCode = response;
    });
  }

```dart
```

MainActivity.java 

import android.os.Bundle;
import io.flutter.plugin.common.MethodChannel;
import io.flutter.plugins.GeneratedPluginRegistrant;
import io.flutter.embedding.engine.FlutterEngine;
import android.content.Context;
import android.content.Intent;
import android.content.IntentFilter;
import android.os.BatteryManager;
import io.flutter.embedding.android.FlutterActivity;
import io.flutter.embedding.engine.FlutterEngine;
import androidx.annotation.NonNull;
import io.flutter.plugin.common. BinaryMessenger;
import io.flutter.plugin.common.MethodChannel;
import io.flutter.embedding.android.FlutterActivity;

public class MainActivity extends FlutterActivity {
    private static final String CHANNEL = "flutter.native/helper";

    private  MethodChannel channel;
    @Override
    public void configureFlutterEngine(@NonNull FlutterEngine flutterEngine){
        super.configureFlutterEngine(flutterEngine);
        BinaryMessenger messenger=flutterEngine.getDartExecutor().getBinaryMessenger();
        channel =new MethodChannel(messenger,CHANNEL);

        channel.setMethodCallHandler((call,result)->{
            if(call.equals("helloFromNativeCode"))
            {
              String ans=helloFromNativeCode();
              result.success(ans);
            }
        });
    }
    private String helloFromNativeCode() {
    return "Hello from Native Android Code";
  }
}

<details>
  <summary>Logs</summary>

```
```

```
```

![image](https://user-images.githubusercontent.com/95909475/190783680-c65a6c8b-a1ec-4a05-85e8-4b6b26c0f320.png)

```
```

</details>

**Comment by huycozy** [comment]
Hi @amitupadhyay1, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this. In this case, it's related to Android native code, so please push the sample code to a GitHub repository and make it public. Also, please provide the output of `flutter doctor -v` as well.
Thank you!
