### ISSUE TITLE
`impellerc` should be codesigned for macOS

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#111764]
`impellerc` is being executed on the host machine, so should be codesigned/notarized on macOS to avoid the "Developer unknown" popup when the SDK is downloaded from the website (because it is quarantined).

https://github.com/flutter/flutter/blob/25e88cb1542d858f144ea10ffe372719e877ea15/packages/flutter_tools/lib/src/build_system/targets/shader_compiler.dart#L171-L173

Instead of being in 
https://github.com/flutter/flutter/blob/25e88cb1542d858f144ea10ffe372719e877ea15/dev/conductor/core/lib/src/codesign.dart#L183
it should be in 
https://github.com/flutter/flutter/blob/25e88cb1542d858f144ea10ffe372719e877ea15/dev/conductor/core/lib/src/codesign.dart#L140

Introduced in https://github.com/flutter/flutter/pull/102551

**Comment by jmagman** [comment]
cc @itsjustkevin @CaseyHillers

**Comment by christopherfujino** [comment]
Technically both `binariesWithEntitlements` and `binariesWithoutEntitlements` are codesigned, the difference is whether we codesign them with this set of entitlements: https://github.com/christopherfujino/codesign.py/blob/master/Entitlements.plist:

```


<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>com.apple.security.cs.allow-jit</key>
        <true/>
        <key>com.apple.security.cs.allow-unsigned-executable-memory</key>
        <true/>
        <key>com.apple.security.cs.allow-dyld-environment-variables</key>
        <true/>
        <key>com.apple.security.network.client</key>
        <true/>
        <key>com.apple.security.network.server</key>
        <true/>
        <key>com.apple.security.cs.disable-library-validation</key>
        <true/>
    </dict>
</plist>
```

Which impellerc may not even need. Also note, this is a very crude system, ideally we would track per binary which entitlements are necessary.

**Comment by christopherfujino** [comment]
*However*, we are not verifying that impellerc is codesigned because of https://github.com/flutter/flutter/issues/95297

**Comment by jmagman** [comment]
Okay, never mind, it is codesigned and notarized, and doesn't need the entitlements:
```
$ spctl -a -vvv -t install  bin/cache/artifacts/engine/darwin-x64/impellerc
bin/cache/artifacts/engine/darwin-x64/impellerc: accepted
source=Notarized Developer ID
```
Ran without the pop-up.  Apologies for the noise.

**Comment by christopherfujino** [comment]
Maybe the action item here then is to update: https://github.com/christopherfujino/codesign.py/blob/master/codesign.py. I'm assuming this was codesigned by local changes to this script, but we should push these back to github @XilaiZhang

**Comment by XilaiZhang** [comment]
yep so it was signed based on the pull request to https://github.com/christopherfujino/codesign.py/blob/master/codesign.py

**Comment by XilaiZhang** [comment]
https://github.com/christopherfujino/codesign.py/pulls

**Comment by christopherfujino** [comment]
sync'd with @XilaiZhang offline; it turns out what is being used in production is neither codesign.py master branch nor the PR, but local changes on the bot. Xilai will open a PR against christopherfujino/codesign.py to merge these changes upstream, which will resolve this issue.

**Comment by jmagman** [comment]
https://github.com/christopherfujino/codesign.py/pull/3 wasn't correct, it needs to codesign the arm64 iOS framework.  @XilaiZhang 

I'll reopen this to track that the codesign script should reflect master's file list.

**Comment by Asquare17** [comment]
@jmagman is there a solution for this issue?  On macOS  the "Developer unknown" popup shows when I try to run the sample app

**Comment by Asquare17** [comment]
I think the issue still exist on 3.3.4. @jmagman 

Reproduction steps:
Install flutter SDK macOS(intel) 3.3.4
Run the sample counterr app
Macos shows the popup "Developer unknown" for impellerc.

**Comment by diver2** [comment]
If this helps anyone, issue still on 3.3.7

**Comment by jmagman** [comment]
Hm, I'm still not seeing it, I downloaded 3.3.7, ran `/path/to/downloadedflutter/bin/flutter create` then `/path/to/downloadedflutter/bin/flutter run --enable-impeller` on a physical phone, and I didn't see any developer unknown pop up, and the counter app ran fine.

Binary is codesigned and notarized.  `otool -l` shows reasonable `LC_LOAD_DYLIB` paths (which was a cause of this issue for other binaries).  Could you open Console, start streaming logs, and reproduce the issue? I would expect logs from the subsystems XprotectService, trustd, and syspolicyd right when the pop up appears.  If you see those logs can you paste them here?

**Comment by jmagman** [comment]
@Asquare17 or @diver2 were you able to try this?  I wasn't able to reproduce this.

> Could you open Console, start streaming logs, and reproduce the issue? I would expect logs from the subsystems XprotectService, trustd, and syspolicyd right when the pop up appears. If you see those logs can you paste them here?

**Comment by bahag-mortazavim** [comment]
Hi guys,
I have installed a fresh MacOS ventura 13.2 and then installed flutter 3.7.0 on it. 
Followed the instruction of flutter official page to do that. And even when I run "flutter doctor" command, everything passed fine without any issue.
But when I try to run the app on any Simulator either ios or android, I am getting the error message regarding "impellerc" file. This is the error message I am getting:

<img width="256" alt="Screenshot 2023-01-31 at 16 07 31" src="https://user-images.githubusercontent.com/88193269/215797769-0552b8f9-09ed-424b-a684-e8f129c0782b.png">

<img width="611" alt="Screenshot 2023-01-31 at 16 06 48" src="https://user-images.githubusercontent.com/88193269/215797810-592bdd61-a8ce-4c9f-b311-cf15ec60eb69.png">

I appreciate any hence that can help. Thanks a lot

**Comment by christopherfujino** [comment]
> Hi guys, I have installed a fresh MacOS ventura 13.2 and then installed flutter 3.7.0 on it. Followed the instruction of flutter official page to do that. And even when I run "flutter doctor" command, everything passed fine without any issue. But when I try to run the app on any Simulator either ios or android, I am getting the error message regarding "impellerc" file. This is the error message I am getting:
> 
> <img alt="Screenshot 2023-01-31 at 16 07 31" width="256" src="https://user-images.githubusercontent.com/88193269/215797769-0552b8f9-09ed-424b-a684-e8f129c0782b.png">
> 
> <img alt="Screenshot 2023-01-31 at 16 06 48" width="611" src="https://user-images.githubusercontent.com/88193269/215797810-592bdd61-a8ce-4c9f-b311-cf15ec60eb69.png">
> 
> I appreciate any hence that can help. Thanks a lot

Awesome, thanks for sharing this! I believe this is the same as https://github.com/flutter/flutter/issues/116703

**Comment by jmagman** [comment]
I wasn't able to reproduce this before because the x64 stable artifacts are codesigned, but the arm ones are not.
https://storage.googleapis.com/flutter_infra_release/releases/stable/macos/flutter_macos_3.7.1-stable.zip
```
$ codesign -d -vv ./artifacts/engine/darwin-x64/impellerc
...
Signature size=8979
Authority=Developer ID Application: FLUTTER.IO LLC (S8QB4VV633)
Authority=Developer ID Certification Authority
Authority=Apple Root CA
Timestamp=Jan 31, 2023 at 3:52:49 PM
Info.plist=not bound
TeamIdentifier=S8QB4VV633
```

https://storage.googleapis.com/flutter_infra_release/releases/stable/macos/flutter_macos_arm64_3.7.1-stable.zip
```
Signature=adhoc
Info.plist=not bound
TeamIdentifier=not set
```

Created https://github.com/flutter/flutter/pull/119971 to run codesigning verification from on both architectures.

**Comment by jmagman** [comment]
Next steps: 
1. Codesign and reupload the stable artifacts.
2. Update process at go/flutter-manual-codesign (sorry for the non-public link)
3. Validate engine v2 scripts will codesign both.

**Comment by christopherfujino** [comment]
> 3. Validate engine v2 scripts will codesign both.

Engine v2 will be much more reliable, as gn will output the list of targets which will then be fed as an input into the new codesign script.

**Comment by jmagman** [comment]
```
bin/cache/artifacts/engine/darwin-x64/impellerc: accepted
source=Notarized Developer ID
origin=Developer ID Application: FLUTTER.IO LLC (S8QB4VV633)
```
Stable version 3.7.2 arm64 SDK zipped artifacts are codesigned.  The codesigning script has been updated, and there are now verification tests that run on x64 and arm64 bots that should keep this from happening again.  Closing.
