### ISSUE TITLE
Hardware keyboard error

### ISSUE THREAD

**Issue by Abdullajon711** [flutter/flutter#111853]
This error occurs on hold left shift in the pressed state in windows application.

A KeyRepeatEvent is dispatched, but the state shows that the physical key is not pressed. If this occurs in real application, please report this bug to Flutter. If this occurs in unit tests, please ensure that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This was the event: KeyRepeatEvent#b1772(physicalKey: PhysicalKeyboardKey#700e1(usbHidUsage: "0x000700e1", debugName: "Shift Left"), logicalKey: LogicalKeyboardKey#00102(keyId: "0x200000102", keyLabel: "Shift Left", debugName: "Shift Left"), character: null, timeStamp: 91:29:24.728562)
'package:flutter/src/services/hardware_keyboard.dart':
Failed assertion: line 432 pos 16: '_pressedKeys.containsKey(event.physicalKey)'

**Comment by huycozy** [comment]
Hi @Abdullajon711, thanks for filing the issue.
I see there's an open issue addressing the case you described https://github.com/flutter/flutter/issues/107972 that has detailed reproduction steps and also has some reports for `Shift` key.
Closing this issue as a duplicate, so please follow up on it for further updates. You can leave there your comment and react an upvote to the original comment will help to raise the issue. Thank you!
