### ISSUE TITLE
Flutter Hot reload not working on save (android studio)

### ISSUE THREAD

**Issue by ricophie03** [flutter/flutter#111825]
I'm currently using android studio as a IDE for developing flutter app.  Here is the version of my android studio :
 - Android Studio Arctic Fox | 2020.3.1 Patch 4
And I'm using flutter ver 65.2.1 and Dart ver 203.8452.
When I'm trying to hot reload my app on save, the dart analysis showed : "Reload not performed, Analysis found issues", but when I'm opened the dart analysis, there is 0 error shown. But when I'm clicking the hot reload button or using the keyboard shortcut, the hot reload working fine. 
I have checked my android studio settings for flutter and I have checked the function for 'Perform hot reload on save'. This is really bugging me, since I have no issues regarding this hot relaod months ago. Maybe it's the package problem ? Thanks in advance

**Comment by danagbemava-nc** [comment]
Hi @ricophie03, can you check if https://github.com/flutter/flutter-intellij/issues/6311 is similar to your case?
