### ISSUE TITLE
Running tester.tap throws "Timer is still pending" error

### ISSUE THREAD

**Issue by jxmorris12** [flutter/flutter#11181]
## Steps to Reproduce

I'm using `flutter_test` to tap a button and make sure it sets a global value correctly. However, the button also loads some data in the background after a delay. The delayed load looks something like this:

```
Future delayedResponse(List response) async {
  return new Future.delayed(const Duration(milliseconds: 500), () => response));
}
```

It's a delay to make the app appear asynchronous even though all of the data (so far) is loaded synchronously. However, since this isn't a `Timer`, I can't 'cancel' it when the button is disposed. So when I run some basic test code that looks like this:

```
WidgetWithId item;
testWidgets('Tapping item with id saves as current global id', (WidgetTester tester) async {
  await launchApp(item, tester); // pumps widget and creates MaterialApp with item as its child
  await tester.tap(find.byWidget(item)); // pretend to tap the item
  await tester.pump();

  expect(global_state.currentId == item.id, isTrue);
});
```

I thought that the `tester.pump()` call would wait for the button's asynchronous request (the `Future.delayed` call) to complete before continuing. However, I get an error saying "A Timer is still pending after the widget tree was disposed." I didn't even explicitly use a Timer.

Perhaps this isn't a bug with `flutter_test` but I need to account for this quirk somehow in my code. If that's the case, what is the best way to run this specific test without throwing an error?

## Logs

```
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following assertion was thrown running a test:
A Timer is still pending even after the widget tree was disposed.
'package:flutter_test/src/binding.dart': Failed assertion: line 632 pos 7:
'_fakeAsync.nonPeriodicTimerCount == 0'

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new

When the exception was thrown, this was the stack:
#2      AutomatedTestWidgetsFlutterBinding._verifyInvariants (package:flutter_test/src/binding.dart:632:7)
#3      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:451:7)
<asynchronous suspension>
#7      TestWidgetsFlutterBinding._runTest (package:flutter_test/src/binding.dart:428:14)
#8      AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:606:24)
#14     AutomatedTestWidgetsFlutterBinding.runTest (package:flutter_test/src/binding.dart:604:16)
#15     testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:57:24)
#16     Declarer.test.<anonymous closure>.<anonymous closure> (package:test/src/backend/declarer.dart:148:19)
<asynchronous suspension>
#17     Invoker.waitForOutstandingCallbacks.<anonymous closure> (package:test/src/backend/invoker.dart:206:15)
<asynchronous suspension>
#21     Invoker.waitForOutstandingCallbacks (package:test/src/backend/invoker.dart:203:5)
#22     Declarer.test.<anonymous closure> (package:test/src/backend/declarer.dart:146:29)
<asynchronous suspension>
#23     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test/src/backend/invoker.dart:351:23)
<asynchronous suspension>
#38     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:366)
#39     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:394)
#40     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
(elided 27 frames from class _AssertionError, class _FakeAsync, package dart:async, package
dart:async-patch, and package stack_trace)

```

## Flutter Doctor
[✓] Flutter (on Linux, locale en_US.UTF-8, channel alpha)
    • Flutter at /usr/local/jxmorris12/flutter
    • Framework revision 6f77b4a9a7 (4 weeks ago), 2017-06-14 17:27:08 -0700
    • Engine revision 18fdfb86bb
    • Tools Dart version 1.24.0-dev.6.7

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.0)
    • Android SDK at /usr/local/jxmorris12/Android/Sdk
    • Platform android-26, build-tools 26.0.0
    • Java binary at: /usr/local/jxmorris12/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] Android Studio (version 2.3)
    • Android Studio at /usr/local/jxmorris12/android-studio
    • Gradle version 3.2
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Ultimate Edition (version 2017.1)
    • Flutter plugin version 15.1
    • Dart plugin version 171.4424

[✓] Connected devices
    • None

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by jxmorris12** [comment]
I changed it to pump a duration significantly longer than that callback and I am facing the same error.

**Comment by Hixie** [comment]
Have you checked whether the delayed future is triggering?

**Comment by jxmorris12** [comment]
need to figure this out internally, framework is working (mostly) as expected

**Comment by guitcastro** [comment]
Hello,

I'm having the same problem using this code:

    await Future.any([
      Future.delayed(const Duration(milliseconds: 300)),
       _keyboardToggled()
    ]);

It's seems that, when one of my delayed are leaked because of the any operator, any idea how to deal with it?

**Comment by maheshmnj** [comment]
> Future.delayed probably uses a Timer internally.
> 
> flutter_test uses a fake clock. When you call pump(), there's an argument you can pass that says by how much to advance the clock. Since you passed nothing, it defaults to zero time, and doesn't advance the clock. If you pass it a duration of, say, 1 second, it will trigger the delayed future.

I had a Future.delayed(5 secs ) in my initstate so my tests were failing with some Pending Timers error fast forwarding the time by adding this works for me.
```
    await tester.pumpAndSettle(const Duration(seconds: 5));
```
