### ISSUE TITLE
`Draggable` happens on right click and scroll click.

### ISSUE THREAD

**Issue by bernaferrari** [flutter/flutter#111850]
I'm making an app and don't like that Draggable is valid for left click, scroll click and right click. IMO it should be left click only, with the option to configure other clicks.

What do you think?
a) Should it be configurable for my needs?
b) Should the default be left-click only or everything is allowed?

I don't like it will interfere with MenuBar/etc.

https://user-images.githubusercontent.com/351125/190941982-7279e029-24b1-4b32-8811-c8d10c51f4b5.mov

```
[✓] Flutter (Channel stable, 3.3.2, on macOS 11.4 20F71 darwin-x64, locale en-BR)
    • Flutter version 3.3.2 on channel stable at /usr/local/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e3c29ec00c (5 days ago), 2022-09-14 08:46:55 -0500
    • Engine revision a4ff2c53d8
    • Dart version 2.18.1
    • DevTools version 2.15.0
```

**Comment by huycozy** [comment]
Hi @bernaferrari, thanks for filing the issue and making a PR.
However, I see there's a similar issue addressing the case you described #89962
Closing this issue as a duplicate. Please update the PR's description to refer to #89962, so that the issue can be tracked.
Thank you for your contribution!
