### ISSUE TITLE
A KeyRepeatEvent is dispatched, but the state shows that the physical key is not pressed. 

### ISSUE THREAD

**Issue by BeamsHakeem** [flutter/flutter#111803]
Somtimes flutter windows hit this error, 
that few minutes keyboard is not working 
after restart only it will work.

A KeyRepeatEvent is dispatched, but the state shows that the physical key is not pressed. If this occurs in real application, please report this bug to Flutter. If this occurs in unit tests, please ensure that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This was the event: KeyRepeatEvent#85966(physicalKey: PhysicalKeyboardKey#700e2(usbHidUsage: "0x000700e2", debugName: "Alt Left"), logicalKey: LogicalKeyboardKey#00104(keyId: "0x200000104", keyLabel: "Alt Left", debugName: "Alt Left"), character: null, timeStamp: 906:59:47.132301)
'package:flutter/src/services/hardware_keyboard.dart':
Failed assertion: line 432 pos 16: '_pressedKeys.containsKey(event.physicalKey)'

**Comment by huycozy** [comment]
Hi @BeamsHakeem, thanks for filing the issue. 
I see there's an open issue addressing the case you described #107972 that has detailed reproduction steps and also has some reports for `Alt` key.
Closing this issue as a duplicate, so please follow up on it for further updates. You can leave there your comment and react an upvote to the original comment will help to raise the issue. Thank you!
