### ISSUE TITLE
【image_picker】app throw PlatformException(channel-error, Unable to establish connection on channel., null, null)

### ISSUE THREAD

**Issue by wlingf** [flutter/flutter#111864]
version:0.8.5+3, iphone14, ios16, simulator, use ImagePicker().pickImage api, throw PlatformException(channel-error, Unable to establish connection on channel., null, null)

**Comment by danagbemava-nc** [comment]
Hi @wlingf, thanks for filing the issue. Please provide a complete minimal reproducible code sample along with steps to reproduce so that we can verify this. 

Please also provide the output of `flutter doctor -v`. 

Thank you
