### ISSUE TITLE
Tooltips in framework widgets should be localized

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#11182]
e.g. https://github.com/flutter/flutter/blob/0a915d6faf804a015d6e0a66b87b9d0f3083f524/packages/flutter/lib/src/material/date_picker.dart#L480

We should provide localized strings for all user-visible strings encoded in the framework, and they should automatically select the right bundle based on the current locale.

**Comment by Hixie** [comment]
This is possible now, and we provide a default localization.

We should now be able to create a flutter_i18n package or flutter_localization package or whatnot that provides strings for other languages.

**Comment by HansMuller** [comment]
As of https://github.com/flutter/flutter/pull/12062 all of the tooltips in flutter whose values aren't for debuggingd/diagnostics have been localized.

**Comment by HansMuller** [comment]
There's a separate issue about moving the material localization into a separate optional package: https://github.com/flutter/flutter/issues/12050
