### ISSUE TITLE
Arm64 binaries of FlutterEmbedder.framework not available

### ISSUE THREAD

**Issue by skyostil** [flutter/flutter#111827]
As described in [Custom Flutter Engine Embedders](https://github.com/flutter/flutter/wiki/Custom-Flutter-Engine-Embedders), the flutter_infra_release storage bucket provides builds of the embedder engine for Linux, Windows and Mac. Unfortunately, only x86-64 binaries are available for Mac, which means embedder apps targeting for Apple M1 or later must resort to Rosetta emulation (or build the engine manually).

Would it be possible to provide prebuilt darwin-arm64 engine binaries too?

**Comment by godofredoc** [comment]
\cc @jmagman

**Comment by jmagman** [comment]
Replace `darwin-x64` with `darwin-arm64` in the URLs.

**Comment by skyostil** [comment]
Thanks, but that doesn't seem to work. For example, for engine rev 3ad69d7be3, this [x64 link](https://storage.googleapis.com/flutter_infra_release/flutter/3ad69d7be3a7231aab5525db322fc699f098315f/darwin-x64/FlutterEmbedder.framework.zip) works but the corresponding [arm64 one](https://storage.googleapis.com/flutter_infra_release/flutter/3ad69d7be3a7231aab5525db322fc699f098315f/darwin-arm64/FlutterEmbedder.framework.zip) doesn't.

**Comment by jmagman** [comment]
I got this confused with https://github.com/flutter/flutter/pull/110291, but you're right we aren't building `FlutterEmbedder` for arm.

@zanderso is this as easy as adding

```
    UploadArtifacts(
        api,
        'darwin-arm64', ['out/host_debug/FlutterEmbedder.framework.zip'],
        archive_name='FlutterEmbedder.framework.zip'
    )
```
here?
https://flutter.googlesource.com/recipes/+/refs/heads/main/recipes/engine/engine.py#1276

Meaning, does this already produce arm artifacts (I'm not on my arm machine atm or I would just try it)?
https://github.com/flutter/engine/blob/ff05a31f5b53fad6a35ad731cbefaaa5845d7d7e/shell/platform/embedder/BUILD.gn

**Comment by chinmaygarde** [comment]
From Triage: @zanderso is checking if this is done. But maybe we should also be lipoing it up for a universal binary?
