### ISSUE TITLE
(Willing to PR) `_debugReportException` should be `_reportException` indeed, otherwise seems misleading to the readers because it is not debug-only

### ISSUE THREAD

**Issue by fzyzcjy** [flutter/flutter#111874]
## Steps to Reproduce

Hi thanks for the wonderful framework! When reading the source code, I see:

https://github.com/flutter/flutter/blob/05c70528752ac4a675ad19447b0483dc695779f5/packages/flutter/lib/src/rendering/object.dart#L1531-L1550

and various places which calls it. The problem is, if I understand correctly, "debugSomething" always means "this thing is only valid when in debug mode and will disappear in release mode", such as debugDoingThisResize, debugDoingThisLayout, etc. For completeness, I briefly glances through other symbols/functions with name ` debug` and `_debug.*(` in `rendering/objects.dart`, and find that they are used inside `assert(...)` or used with `kDebugMode`.

However, this method name indeed reports error unconditionally, i.e. report both in debug and release. That is pretty reasonable, because we surely want error reports in release builds. The problem is the naming - the name seems confusing to the readers IMHO.

Thus, I propose to simply rename _debugReportException to _reportException.

I am willing to make a PR. However, given that this is just a code renaming, I wonder whether I should create a PR?

1. Execute `flutter run` on the code sample 
2. ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by exaby73** [comment]
Hello @fzyzcjy. Thank you for filing this proposal. Labelling for further insights from the team.

**Comment by fzyzcjy** [comment]
@exaby73 Hello, you are welcome

**Comment by fzyzcjy** [comment]
Oh I forgot to PR for this. As said in https://github.com/flutter/flutter/pull/114003#discussion_r1006161464, 

> Methods starting with debug or _debug should only be called from within an assert or guarded by kIsDebug.

So I should PR to make this tiny change
