### ISSUE TITLE
Add factory constructors for filled, tonal, outlined icon buttons

### ISSUE THREAD

**Issue by akshdeep-singh** [flutter/flutter#111800]
# Proposal
`IconButton.filled`, `IconButton.outlined`, etc.

Relevant: #103528, #104357

**Comment by danagbemava-nc** [comment]
Hi @akshdeep-singh, are these the factories that you are referring to?

https://master-api.flutter.dev/flutter/material/FilledButton/FilledButton.icon.html
https://master-api.flutter.dev/flutter/material/FilledButton/FilledButton.tonal.html
https://master-api.flutter.dev/flutter/material/OutlinedButton/OutlinedButton.icon.html

**Comment by akshdeep-singh** [comment]
Hi @danagbemava-nc, no I am not referring to them.

If you check, below 3 are different:
- [ElevatedButton](https://master-api.flutter.dev/flutter/material/ElevatedButton/ElevatedButton.html)
- [ElevatedButton.icon()](https://master-api.flutter.dev/flutter/material/ElevatedButton/ElevatedButton.icon.html)
- [IconButton()](https://master-api.flutter.dev/flutter/material/IconButton/IconButton.html)

I am talking about `IconButton` here.

**Comment by HansMuller** [comment]
@QuncCccccc, @darrenaustin - perhaps the solution here is the "variants", as we've discussed for the button classes.

**Comment by darrenaustin** [comment]
Rather than creating a bunch of classes for this we could instead opt for `IconButton.filled`, `IconButton.outlined`, etc factory constructors that just configure the icon button as needed for the variant. For theming we could do something similar to what is described here https://github.com/flutter/flutter/issues/107946#issuecomment-1193422262.

**Comment by realitymolder** [comment]
> #107946 (comment)

Yes, that would be great. Is there an ETA for that? I saw that first issues regarding the "missing" buttons started since April

**Comment by guidezpl** [comment]
FYI I've updated this proposal to reflect the desired solution

**Comment by rydmike** [comment]
Having ready made factories to easily create the different M3 `IconButton` styles depicted in the Material 3 guide and specification, would be very useful and save a lot of time in many projects. 

https://m3.material.io/components/icon-buttons/overview

![Screenshot 2023-02-10 at 3 44 29](https://user-images.githubusercontent.com/39990307/217979328-17abbdb7-eb7b-4fc7-8607-59c65fd0c65c.png)

Same applies to Cards:

https://m3.material.io/components/cards/overview

![Screenshot 2023-02-10 at 3 44 51](https://user-images.githubusercontent.com/39990307/217979355-50574674-1e46-4663-a7d5-4726fc9f3bb7.png)

For the common Material buttons we got them in Flutter 3.7. Apparently there was a change of views on it after this discussion and rationale https://github.com/flutter/flutter/issues/104357#issuecomment-1151725647

Same applies here to `IconButton` and `Card`.

**Comment by MichaelPriebe** [comment]
I find it strange that the "support" for these types of buttons and cards are literally just making them yourself. Definitely need constructors.
