### ISSUE TITLE
Error: Unsupported operation: dart:isolate is not supported on dart4web

### ISSUE THREAD

**Issue by AliKarimiENT** [flutter/flutter#111870]
Hello I'm working on my test project and I face this issue when I want to load data 
![image](https://user-images.githubusercontent.com/57004354/190991277-26bd2604-9d69-4e7e-ab01-e2873cd262d1.png)

The code is visible here
https://github.com/AliKarimiENT/Dart-course/blob/master/lib/main.dart

The codes are here
![image](https://user-images.githubusercontent.com/57004354/190990978-3f24c8fc-8181-475e-b7a3-0d2ba1a42634.png)

The project is open source and you can check it
https://github.com/AliKarimiENT/Dart-course

**Comment by Run10Break1** [comment]
I can see you run the flutter project on the web("chrome"), but isolate is not supported on the web yet

check this: https://api.flutter.dev/flutter/dart-isolate/dart-isolate-library.html

**Comment by darshankawar** [comment]
@AliKarimiENT 
Per above comment, the `dart: isolate` library doesn't support web yet. See [this](https://github.com/flutter/flutter/issues/39998) similar issue for your reference and the chart shown in [this](https://github.com/flutter/flutter/issues/39998#issue-490489986) description to know which library is supported on web and which isn't.

Based on above comment, I am closing this. If you disagree, write in comments and I'll reopen it.
