### ISSUE TITLE
Rename label "p: adaptive_scaffold" to "p: "flutter_adaptive_scaffold"

### ISSUE THREAD

**Issue by nilsreichardt** [flutter/flutter#111832]
First, the package has been named "adaptive_scaffold". However, nobody checked before that this name is already taken (see https://github.com/flutter/packages/pull/2545#issuecomment-1247079137). In https://github.com/flutter/packages/pull/2600 the package has been renamed to "flutter_adaptive_scaffold". But the label still has the old name. 

Therefore, we should rename it to "flutter_adaptive_scaffold".

Otherwise, is the link the in the `pubspec.yaml` useless:

https://github.com/flutter/packages/blob/main/packages/flutter_adaptive_scaffold/pubspec.yaml#L4

**Comment by stuartmorgan** [comment]
@gspencergoog Would you prefer to rename the label, or change the query in the pubspec? We don't always match exactly (e.g., `webview`, `maps`).

**Comment by gspencergoog** [comment]
Rename the label.  There was nothing submitted under the old label, since it was never actually published under the incorrect name.

**Comment by a-wallen** [comment]
I also noticed that this PR still has the `p: adaptive_scaffold` label. Are we interested in changing that one as well? https://github.com/flutter/packages/pull/2617

**Comment by a-wallen** [comment]
Thanks for all the help @stuartmorgan 👍
