### ISSUE TITLE
Unable to load asset 

### ISSUE THREAD

**Issue by ahmedg451** [flutter/flutter#111878]
I'm unable to load images to my app although I tried many solutions
my code
```
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        backgroundColor: Colors.amber,
        appBar: AppBar(
          backgroundColor: Colors.amber[900],
          title: const Text("hi"),
        ),
        
        body:   Image(image: AssetImage("images/ab.png"),
        ),

      ),
    );
  }
}
```

this is my `pubspec.yaml`
![Screenshot from 2022-09-19 13-23-02](https://user-images.githubusercontent.com/112572637/191007850-f42b33c3-eddb-48a5-b50f-f2e9947c4e04.png)
flutter doctor
![Screenshot from 2022-09-19 13-24-30](https://user-images.githubusercontent.com/112572637/191007952-77b470ff-74a2-4c9b-8610-10bbe5212bc2.png)

1- I used `$ flutter clean` and then `$ flutter pub get`.

2- I updated flutter SDK.

3- I mention only the folder (images).

4- I used a smaller image.

5- I restarted my laptop.

6- I run my code in another IDE.

but nothing is working for me, so can anyone help me?
thanks in advance

**Comment by jnelle** [comment]
Try this https://github.com/FlutterGen/flutter_gen

**Comment by darshankawar** [comment]
> AssetImage("images/ab.png"),

@ahmedg451 Does `ab.png` exist in your project ?

Check [this](https://docs.flutter.dev/development/ui/assets-and-images) document for reference and see if it helps.

**Comment by zTomz** [comment]
have you recompiled the app? @ahmedg451

**Comment by iapicca** [comment]
looks like the path in your `AssetImage` is incorrect ([source](https://docs.flutter.dev/development/ui/assets-and-images#loading-text-assets
))
```diff
-        body:   Image(image: AssetImage("images/ab.png"),
+        body:   Image(image: AssetImage("assets/images/ab.png"),
```

**Comment by ahmedg451** [comment]
> have you recompiled the app? @ahmedg451

yes, I deleted the project and copied it then it work fine
thank u for your  help 😊

**Comment by ahmedg451** [comment]
> Try this https://github.com/FlutterGen/flutter_gen

I will try it
thanks for ur answer blush

**Comment by ahmedg451** [comment]
I deleted the project and rewritten it then it work fine
