### ISSUE TITLE
Can we remove `_ambiguate` in the "plugins" repository?

### ISSUE THREAD

**Issue by nilsreichardt** [flutter/flutter#111841]
The [plugins](https://github.com/flutter/plugins) repository has a 41 calls of a `_ambiguate` method. Flutter 3 is now stable and we have already the next stable release. Is it time to remove the `_ambiguate` method? In the code it says 

> "TODO(ianh): Remove this once we roll stable in late 2021."

**Comment by nilsreichardt** [comment]
cc: @ianh

**Comment by stuartmorgan** [comment]
Yes, this can be removed now. Thanks for filling this!

**Comment by nilsreichardt** [comment]
Should I do everything in one PR or for every package a separate PR?

**Comment by stuartmorgan** [comment]
Either is fine; 41 instances of a straightforward changes won't be hard to review.

**Comment by stuartmorgan** [comment]
New instances have been added for new framework changes, so these will have to be evaluated in a case by case basis now; not all are removable.

**Comment by stuartmorgan** [comment]
Most of the remaining usage in for `WidgetsBinding.instance`, which can be removed. The other cases will need to be checked for when the API changed.
