### ISSUE TITLE
Only run postsubmit tests on changed packages in flutter/plugins and flutter/packages

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#111885]
Something that came up in the drafting of [the proposal to merge flutter/plugins and flutter/packages](https://docs.google.com/document/d/1VihAgx1e-X_H8VRc9WmUv_7qqsi81eeHrrhwhHgwtjQ/edit?usp=sharing) is that we could potentially switch post-submit tests to match pre-submit tests in terms of only running for changed packages rather than all packages. Quoting from the doc:

> The run-all-on-post-submit policy exists in order to find out-of-band (OOB) breakages as soon as possible, rather than them being latent until someone happens to touch affected packages. Having them be latent, as was previously the case, had several drawbacks:
> - Pinpointing the regression source can be much more difficult without information about when it happened.
> - The issues would randomly show up in PRs, rather than being surfaced very obviously to the whole team (and notably, to the gardener).
>
> However, a significant amount of work has been done since this policy was instituted to reduce possible sources of out-of-band breakages. We have also added the roller, which:
> - runs daily
> - runs all tests
> - is monitored
>
> Given that, we could strongly consider moving back to having post-submit still only run for changed packages, and rely on the roller to surface OOB failures.

The main effects would be:
- Faster/cheaper post-submit runs
- Random OOB breakage would generally be found first in the flutter/flutter->flutter/p* roller (even though it wouldn't be related to the roll) rather than in tree-closing post-submit test failure as currently happens (even though it isn't related to the commit), because the roller always runs all tests.
  - On the plus side, OOB breakage would be less likely to interfere with auto-publish.
  - On the down side, it could be harder to determine the source of breakages (currently if it's post-submit it's almost certainly OOB, and if it's in the roller it's almost certainly due to a Flutter change in the roll, but those would be mixed together in the new model.)

I'm curious what gardeners (@bparrishMines @cyanglaz @ditman @camsim99 @tarrinneal) think of this. It's something that we can do at any point, so if we want to do it, it would be better to do before merging repos.

**Comment by ditman** [comment]
The only instance I've seen where the same policy as presubmit wouldn't be enough is the one that allowed merging a bunch of dependabot updates to java (?) packages and it decided that no tests needed to run. (I guess this is a problem with the presubmit itself, and not this proposal)

In any case, I think this is a good idea. We can try it and see if we need to revert commits more often than before :)

**Comment by stuartmorgan** [comment]
Yes, in that case the post-submit tests would still have run, because the problem was that something in infra itself failed to schedule the presubmits, not that our logic skipped packages.

**Comment by ditman** [comment]
> something in infra itself failed to schedule the presubmits

YIKES! I thought it was our logic decided that all checks needed to be skipped.

**Comment by bparrishMines** [comment]
Some of our packages depend some of our other packages. Would it be possible to also run tests for all packages that depend on a changed package?

**Comment by stuartmorgan** [comment]
We have `pathified_analyze`, so we're already doing that to some extent.

Since our inter-package dependencies are all pub-based, post-submit tests for the PR that changes package X already aren't going to catch problems (other than `pathified_analyze`), because they are pre-publish. Usually when we mess something up with publishing it'll be the *next* PR's post-submit tests that fail.

So this would be a special case of the more general effect of OOB breakages being potentially found later (since they would show up in the roll instead). Although, I was looking and we don't actually have all that many commits per day most days, so "found in the roll" won't necessarily be much later "found in the next PR's post-submit". And as someone mentioned in offline discussion, we could up the frequency of the roller slightly to compensate for that (e.g., 2 or 3 rolls per day).

**Comment by stuartmorgan** [comment]
We're going to go ahead and give this a try, and see how it goes. If we find that it's worse, we can evaluate next steps, either reverting on adjusting the roller frequency to compensate.

(I think that between most commits being both much faster in post-submit, and much less flaky, it'll be a significant net positive and we won't want to revert it.)
