### ISSUE TITLE
[Windows] Can not change app's FriendlyAppName on windows taskbar

### ISSUE THREAD

**Issue by jinfagang** [flutter/flutter#111807]
![image](https://user-images.githubusercontent.com/21303438/190853700-355a89be-9349-4dd5-a84c-eea67edc19b1.png)

this tooltips, can ont be changed, also can not see anywhere doced.

I changed here not work.

![image](https://user-images.githubusercontent.com/21303438/190853716-c189d0d0-c42d-4eee-be62-29d432f957c9.png)

**Comment by huycozy** [comment]
Hi @jinfagang, thanks for filing the issue. 
I see there's an open issue addressing the case you described #30712, and take a look at https://github.com/flutter/flutter/issues/30712#issuecomment-1122620289 that gave a workaround for this.

<details>
<summary>Demo</summary>

![Capture](https://user-images.githubusercontent.com/104349824/190990555-481698ff-4ba6-4ba1-842d-eb61a5d04cbb.PNG)

</details>

Closing this issue as a duplicate, so please follow up on it for further updates. You can leave there your comment and react an upvote to the original comment will help to raise the issue. Thank you!

**Comment by jinfagang** [comment]
@huycozy Hi, please reopen this.

Your linked has nothing to do with my question, it';s window title, I didn';t have issue on window title.....

**Comment by huycozy** [comment]
@jinfagang Sorry for missing `tooltips` in the description. I was focused on your screenshot (it's windows configuration). I reopen this issue for further discussion.
As far as I can see, are you looking to configure this on MacOS? If so, please update the issue's title to match it. Thank you!

**Comment by jinfagang** [comment]
@huycozy Hi, this is windows. The `tooltips` the mouse hover on application icon docketed on bar, it shows `A new flutter project` I want to know how to change it ti my app's name.

**Comment by huycozy** [comment]
Hi @jinfagang 
Please check this SO answer that can help: https://stackoverflow.com/a/65741577
- Demo:

![Screenshot 2022-09-20 111919](https://user-images.githubusercontent.com/104349824/191166670-71480d4e-690f-45a6-abf0-15af091d8d9b.png)

**Comment by jinfagang** [comment]
@huycozy Hi followed remove the build and rebuilt, but not work, also changed the description

**Comment by huycozy** [comment]
@jinfagang 
>old file description cashed in windows registry (under HKEY_CLASSES_ROOT\Local Settings\Software\Microsoft\Windows\Shell\MuiCache) and is not updated when first issue fixed manually.

Try following the above guideline from SO thread:
- Delete the old `...FriendlyAppName` in Registry Editor
- Update `FileDescription` so that new value is different from the old value
- Rebuild & run the application
