### ISSUE TITLE
[go_router_builder] Add go_router v5 support to go_router_builder

### ISSUE THREAD

**Issue by chunhtai** [flutter/flutter#111909]
go_router_builder should support  new feature added into go_router_v5

These include
- shellRoute API
- async and buildcontext redirect.

**Comment by hawkkiller** [comment]
@chunhtai made PR https://github.com/flutter/packages/pull/2672

**Comment by chunhtai** [comment]
@hawkkiller thanks!

**Comment by ClaireDavis** [comment]
Do we have any idea on when this might be supported?  I'd love to start using shell routes in my enterprise app!

**Comment by lucavenir** [comment]
Will this also introduce a way to write `redirect` methods inside `ShellRouteData`? Or is it already possible to define a redirect function on shell routes?

**Comment by thipokch** [comment]
Maybe bump this up to v6?

**Comment by adamsowinski** [comment]
This is a show stopper for using go_router_builder for me.

**Comment by ClaireDavis** [comment]
Looks like this is complete? https://github.com/flutter/packages/pull/2977

**Comment by lucavenir** [comment]
@ClaireDavis no it isn't; this is also about `ShellRoute` which - to my knowledge - isn't available to the builder

**Comment by ycherniavskyi** [comment]
@ClaireDavis, as @lucavenir wrote, it isn't for sure. We hope to switch to `go_router_builder` after mentioned PR merged, but unfortunately not. That is why for now, `go_router_builder` is useless if you want to get all `go_router` functionality.
