### ISSUE TITLE
Is it possible to expand an ExpansionListTile by default?

### ISSUE THREAD

**Issue by BenSower** [flutter/flutter#11194]
If I have multiple ExpansionListTiles, can I expand one right from the start, similar to ExpansionPanels default parameter `bool isExpanded: false`?

**Comment by Hixie** [comment]
cc @HansMuller

**Comment by HansMuller** [comment]
Good point, you _should_ be able to do that, there's just no API for it. I'll add it.

**Comment by zoechi** [comment]
I couldn't find ExpansionListTile.
I assume it is https://docs.flutter.io/flutter/material/ExpansionTile/ExpansionTile.html which has `initiallyExpanded`

**Comment by awhitford** [comment]
This looks like it should be closed now.

**Comment by sballew** [comment]
`initiallyExpanded` provides this behavior. This issue should be closed.

**Comment by HansMuller** [comment]
Thanks @awhitford @sballew - yes this issue should have been closed long ago. Closing it now!
