### ISSUE TITLE
Trigger ios-usb-dependencies builder to run weekly

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#111994]
Run [ios-usb-dependencies](https://ci.chromium.org/p/flutter/builders/prod/ios-usb-dependencies) builder weekly.

This uploads the iOS vendored artifacts to an `ios-usb-dependencies/unsigned` bucket, which is not used by the Flutter tool (still needs to be codesigned, validated, and uploaded to the signed bucket.  See go/flutter-manual-codesign and `./codesign.py --ios-deploy` (maybe?) and https://flutter-review.googlesource.com/c/recipes/+/32660/

So I was wrong in https://flutter-review.googlesource.com/c/infra/+/32700/comment/9f5b198c_272b6c0d/, I believe we should run this more often.

cc @keyonghan

**Comment by keyonghan** [comment]
https://flutter-review.googlesource.com/c/infra/+/34161 to bump to weekly.

**Comment by nehalvpatel** [comment]
Closing as it looks like this was addressed.
