### ISSUE TITLE
a11y: nested accessibility elements cause trouble.

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#11192]
Imagine that the following two nested accessibility elements are both focusable (could be a table row that is tappable, with a little icon to the right thats tappable separately):

```
--------------------------------
|                    -------   | 
| e1                 |  e2 |   |
|                    -------   |
--------------------------------
```

On iOS, there is currently no way to focus the nested e2 element with accessibility means.
On Android, it seems like only the nested element is accessible (although that's not consistent).

**Comment by Hixie** [comment]
What do you mean by "focusable" here? Keyboard focus on accessibility focus?

**Comment by goderbauer** [comment]
Accessibility Focus.

**Comment by goderbauer** [comment]
On Android it looks like we can fix the problem by properly using `setFocusable` (https://github.com/flutter/flutter/issues/11179).

On iOS it looks like if a container (like e2 in the picture above) identifies as an accessibility element (`isAccessibilityElement` returns `YES`), iOS refuses to focus on anything within the container (see https://stackoverflow.com/questions/38849389/voiceover-parent-and-child-views-as-accessibility-elements). The second answer also contains a suggested workaround, which basically involves flattening the hierarchy.

**Comment by goderbauer** [comment]
The Android fix is in https://github.com/flutter/engine/pull/4067. The iOS fix is in progress.
