### ISSUE TITLE
[CP] Avoid sending a zero matrix to the engine

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#111915]
### issue_link

https://github.com/flutter/flutter/issues/110671

### Commit Hash

36a5a0f

### Target

stable

### pr_link

https://github.com/flutter/flutter/pull/111914

### Impacted Users

iOS users with a11y turned on

### Impact Description

Hard application crash when certain types of widget trees are used and a11y services are enabled.

### Workaround

None known.

### Risk

low

### Test Coverage

yes

### Validation Steps

Run tests added to framework in patch.https://github.com/dnfield/flutter/pull/new/flutter-3.2-candidate.5

**Comment by HansMuller** [comment]
Looks like a good fix for a CP.

**Comment by itsjustkevin** [comment]
Reopening:  Will close once shipped.

**Comment by CaseyHillers** [comment]
Released in https://github.com/flutter/flutter/releases/tag/3.3.3
