### ISSUE TITLE
Update `TabBar` to support Material 3

### ISSUE THREAD

**Issue by TahaTesser** [flutter/flutter#111962]
| M2 | M3 |
| --------------- | --------------- |
| <img src="https://user-images.githubusercontent.com/48603081/191256567-3fec1e03-e924-46a5-995b-f2caf32875e9.png" height="450" /> | <img src="https://user-images.githubusercontent.com/48603081/191256571-b7ee44b9-6e27-42cd-a2d3-51cbcf69a6cc.png" height="450" /> |

We should update the `TabBar` widget to support this Material 3 look and [tokens](https://github.com/flutter/flutter/blob/master/dev/tools/gen_defaults/data/navigation_tab_primary.json).

Specs: https://m3.material.io/components/tabs/specs

**Comment by TahaTesser** [comment]
cc: @darrenaustin

**Comment by darrenaustin** [comment]
> Could you please add this issue to #91605?

Done. Thx.

**Comment by TahaTesser** [comment]
Making progress on this. It seems that the `TabBarIndicatorSize.label` isn't the same M3.

(left native and right Flutter)
![Screenshot 2022-09-22 at 14 23 40](https://user-images.githubusercontent.com/48603081/191734455-32992988-3faf-4293-aad0-18ed5caad80e.png)


I will wait for complete specs on https://m3.material.io/
Any suggestions? @darrenaustin

**Comment by chaudharydeepanshu** [comment]
Also when setting ```useMaterial3: true``` the tab bar is not choosing the right colors from the theme.

| useMaterial3: false | useMaterial3: true |
| ------------- | ------------- |
| ![WhatsApp Image 2022-09-26 at 10 51 09 AM](https://user-images.githubusercontent.com/85361211/192199752-1d71a6c3-320d-43cb-952e-bac921c26881.jpeg)  | ![WhatsApp Image 2022-09-26 at 10 51 09 AM (1)](https://user-images.githubusercontent.com/85361211/192199756-50556afd-4dec-49bb-83bd-f205645cad7f.jpeg)  |

**Comment by TahaTesser** [comment]
[Design specs](https://m3.material.io/components/tabs/specs is available, working NOW on this to match the specs.

**Comment by TahaTesser** [comment]
Finishing a PR for this by tomorrow

**Comment by TahaTesser** [comment]
Hi @darrenaustin! 

I'm creating an M3 indicator shape and I need the shape token for the new indicator.

https://github.com/flutter/flutter/blob/637e5bce662fb43459d409e13ba5a7fb2c3fa930/dev/tools/gen_defaults/data/navigation_tab_primary.json#L8-L9

https://m3.material.io/components/tabs/specs mentions it. Could you please update tokens for `navigation_tab_primary`?





![Screenshot 2022-10-20 at 16 26 08](https://user-images.githubusercontent.com/48603081/196961263-833b45b7-f902-40d6-a4eb-de5642d9ac74.png)

**Comment by TahaTesser** [comment]
I just noticed it's 3,3,0.0. Is this shape from a token? 
I don't see a such shape in https://m3.material.io/styles/shape/shape-scale-tokens.
Closest one is `md.sys.shape.corner.extra-small.top` with `4dp,4dp,0dp,0dp,` value.

cc: @guidezpl

**Comment by TahaTesser** [comment]
I have a quick question, `preferredSize` uses hard cost const values such as `_kTabHeight`.

https://github.com/flutter/flutter/blob/c0f822976fe27ac5da893e30bb236ea78aad42ca/packages/flutter/lib/src/material/tabs.dart#L152-L162

For M3, I need to check if the `theme.useMaterial3` is true and returns a different tab height for M3. 
`preferredSize` doesn't use context and I can't use private variables otherwise `TabBar` class be a const class anymore.

**Comment by Piinks** [comment]
Oh wow great question. I will take a look and see if there is a way to do this...

**Comment by Piinks** [comment]
So my first thought is it would likely need to be done via wrapper classes... just like Scrollbar is a wrapper class.

Scrollbar is a class that returns a _MaterialScrollbar or a CupertinoScrollbar based on the theme.

https://github.com/flutter/flutter/blob/46d29084eea2101f89b327d12be643a1f1cd7b41/packages/flutter/lib/src/material/scrollbar.dart#L217

Here, you might want to make TabBar a stateless widget, that (based on `Theme.of(context).useMaterial3`) returns either a..
-  _TabBar (renaming the old stateful widget, maintaining the old preferredSize)
- _Material3TabBar (new stateful widget, having the new preferredSize)

I haven't seen your refactor for M3 here yet, but it may also be easier to read the new and old as separate classes anyways. 
However, if the _TabBarState is still virtually the same between them, it might be a good idea for them to each share the same State class. I am doing something similar in #113793. 

There are probably a couple of different ways you could do this... that's just the first that came to mind. Let me know what you think or how it works out. :)

**Comment by guidezpl** [comment]
> I just noticed it's 3,3,0.0. Is this shape from a token?

No, it's defined on its own.

**Comment by darrenaustin** [comment]
> The new https://m3.material.io/components/tabs/specs page mentions it. Could you please update tokens for `navigation_tab_primary`?

I just pulled the latest from the token db and I don't see a new entry for the indicator's shape. This may be something that will come later (there are several layout params are being added in updates to the db). For now, can we hard code this into the template with the values from the spec? Maybe put a comment in the template to indicate that these values should be coming from the DB when they are available?

**Comment by TahaTesser** [comment]
> For now, can we hard code this into the template with the values from the spec? Maybe put a comment in the template to indicate that these values should be coming from the DB when they are available?

Perfect, will do this.

**Comment by TahaTesser** [comment]
Update: 
Working on this https://github.com/flutter/flutter/issues/111962#issuecomment-1286143324

**Comment by TahaTesser** [comment]
@Piinks 
This is a great suggestion but `TabBar` cannot be just a simple stateless widget since the `bottom` parameter of the `AppBar` expects the `PreferredSizeWidget` type of `TabBar`. Unlike `Scrollbar`, `Switch`, and `AnimatedList`. 

My main challenge is keeping `TabBar`  a `PreferredSizeWidget` and `const` widget while getting different `preferredSize` based on M2 and M3 context. 

> _TabBar (renaming the old stateful widget, maintaining the old preferredSize)
> _Material3TabBar (new stateful widget, having the new preferredSize)

These private widgets don't have to be `PreferredSizeWidget` and I can return different configurations just like you suggested but the main `Tabar` has to be `PreferredSizeWidget` that returns `preferredSize`, this doesn't have any context to return different sizes.

**Comment by Piinks** [comment]
I am inquiring with some folks to see if we can just update preferredSize to match the M3 spec. It would be a small breaking change, just a few pixels. I will let you know what I hear back from stakeholders. 
In that case, we would want to spin up a migration guide that just clarifies the change, the motivation, and how to configure to use the old sizes. The implementation of preferredSize in TabBar might need to be tweaked and have a test that verifies you can configure it to the old sizes.  

Before you write a bunch of code though - let me see if this is an ok approach. 👍

**Comment by TahaTesser** [comment]
@Piinks 
Appreciate it!

**Comment by TahaTesser** [comment]
@Piinks 
We can also consider adding a flag like this [useLegacyColorScheme](https://master-api.flutter.dev/flutter/material/BottomNavigationBar/useLegacyColorScheme.html)
Eventually, M2 will be deprecated and we can remove this old size and this flag.

**Comment by Piinks** [comment]
> We can also consider adding a flag like this [useLegacyColorScheme](https://master-api.flutter.dev/flutter/material/BottomNavigationBar/useLegacyColorScheme.html).
(this was https://github.com/flutter/flutter/pull/107924 to BottomNavigationBar just a month ago)

> Eventually, M2 will be deprecated and we can remove this old size and this flag.

Could this work in the TabBar case? Setting a flag on TabBar would not be accessible from `TabBar.preferredSize`, would it? Maybe that means it would have to be a flag on Tab? Not sure.

I think this exposes an issue we might be able to fix a totally different way. The purpose of preferred size is to allow the parent to query what size the child would like to be if it were unconstrained. Preferred size does not currently allow us to incorporate theming, there is no context available, so it has to be manually set on the individual widget. 

The spec will almost certainly change again, so I am wondering if we should consider making this a bit more future proof, less breaking changes and deprecations for developers to churn through. 

I played around with making preferredSize a method with context instead of a getter..
```dart
// from
Size get preferredSize;

// to
Size preferredSize(BuildContext context);
```

This would totally be breaking, but could fix this once and for all future changes to the spec.

But then!! While I was testing the impact and going through the preferred size cases in the framework, I found something else that may be **_exactly_** what we are looking for:

https://github.com/flutter/flutter/blob/db381d75b19573fd3337548fc298ff80aeefdffc/packages/flutter/lib/src/material/app_bar.dart#L236

Maybe this static method is what we need not just for AppBar, but for all preferred size widgets so we can provide a context when appropriate. 

I would see if we can make `AppBar.preferredHeightFor` --> `PreferredSize.preferredSizeFor` or some such. That way all preferred size widgets would inherit the method. Let me know what you think, I know I don't have it 100% figured out in my head, but I think this feels like the right direction to head in. :)

**Comment by TahaTesser** [comment]
@Piinks 
Appreciate your comment! 

>  we should consider making this a bit more future proof,

I totally agree. Future-proofing is needed so we don't have to make breaking changes every time.

**Comment by TahaTesser** [comment]
@Piinks 
I've explored the idea for `preferredSizeFor`, I love this idea. This looks perfect for checking theme however I am not if you're suggesting adding `preferredSizeFor` to `PreferredSize` (stateless widget)  or `PreferredSizeWidget` (abstract class). `PreferredSizeWidget` is implemented by widgets and it needs overriding `preferredSize`.

If we add `preferredSize` to the `PreferredSizeWidget` then we would have one of them as redundant.

```dart
  Size get preferredSize;

  ///
  Size preferredSizeFor(BuildContext context);
```
If we add `preferredSizeFor` to `PreferredSize`. This is a widget and it's not extended. Also `bottom` parameter expects `PreferredSizeWidget`.

**Comment by Piinks** [comment]
> If we add preferredSize to the PreferredSizeWidget then we would have one of them as redundant.

Yeah I was thinking we could either have clear docs on both, maybe the existing one is fixed, and the fallback for is the context-based one is null? So if preferredSizeFor(context) checks and finds SomeTheme.perferredSize is null then use preferredSize?

Or, we could deprecate the old one is favor of the new context based one. WDYT?

**Comment by TahaTesser** [comment]
Any ideas? @darrenaustin

**Comment by Piinks** [comment]
Hmm I really want to avoid legacy flags, they could end up being one of many in the future if we need to make other changes to the widget. Let me take a closer look at PreferredSizeWidget et al. We might just want to make this change for the good of the API separate from M3 changes.

**Comment by TahaTesser** [comment]
After a discussion with Piinks, we decided to land without the minor preferred size update, it will be done later in a separate issue.
I have the other changes ready to go, need tests and I will file the tomorrow with tests

**Comment by chaudharydeepanshu** [comment]
You mean that we won't be updating the preferred size change by material guidelines in the new widget?

**Comment by chaudharydeepanshu** [comment]
Yeah that would be better. Thanks for clarifying.

**Comment by chaudharydeepanshu** [comment]
@TahaTesser hey, any update on the PR?

**Comment by guidezpl** [comment]
https://m3.material.io/components/tabs/overview describes another type of `TabBar`

![image](https://user-images.githubusercontent.com/6655696/213259961-513929bc-8044-4525-9b02-97c84ebcb299.png)

Reopening this issue for tracking purposes. Googlers, note we've already implemented this internally and can simply open source the implementation.

**Comment by nrlvm** [comment]
<img width="296" alt="Снимок экрана 2023-01-27 в 15 41 00" src="https://user-images.githubusercontent.com/109414629/215067053-5c947ffb-df88-4a8f-ac07-c86d9cceab9d.png">

hi , sorry to bother you but could you tell how to remove bottom border while using m3 ?

**Comment by guidezpl** [comment]
StackOverflow is your friend :) https://stackoverflow.com/questions/56465498/remove-flutter-tabbar-bottom-border. If that doesn't work, please file a new issue and mention this one.

**Comment by TahaTesser** [comment]
@guidezpl 
I was told I can help with landing https://github.com/flutter/flutter/issues/111962#issuecomment-1387496896. Feel free to reach out to me on Discord.

**Comment by anthonymoretti** [comment]
On stable channel in a text-only tab the text doesn't appear to be vertically centered (as per [Layout](https://m3.material.io/components/tabs/specs#471acc02-600f-4fe2-8651-70549d4a6679)). I think it's pushed up by half the indicator height, so it's 1.5 too high. I currently work around it by using `child` rather than `label` and padding the top of the text by 1.5.

**Comment by anthonymoretti** [comment]
I filed issue #123112. The height seems to be ever so slightly off too.

![Tab issue](https://user-images.githubusercontent.com/3210808/226632598-cf01058d-3bec-4a02-92de-4ec8517929b7.png)
