### ISSUE TITLE
[url_launcher_android] Issue regarding REQUEST_INSTALL_PACKAGES permission after uploading the application to PlayStore

### ISSUE THREAD

**Issue by tel-kho** [flutter/flutter#111947]
## Steps to Reproduce

Upload an application using the package url_launcher/url_launcher_android on the PlayStore

**Expected results:** Uploading my application without a Google alert

**Actual results:** I received an alert saying that my application is not compliant with one or more of Google Developer Program Policies.

The reason is that my application seems to use [REQUEST_INSTALL_PACKAGES](https://developer.android.com/reference/android/Manifest.permission#REQUEST_INSTALL_PACKAGES) permission. I checked my AndroidManifest, I never use this permission.
I searched online how to find where in my application permissions are used even by me or other packages, and I found this:

![image](https://user-images.githubusercontent.com/56344804/191186577-cfa3587b-6da6-4016-9935-cada0bfbe8b1.png)

in the file "/My_Flutter_App/build/app/outputs/logs/manifest-merger-release-report.txt".

I already tried to fill their form trying to explain where in my application this permission is used, in vain. They sent me this instead:

![image](https://user-images.githubusercontent.com/56344804/191187424-81274a2b-338d-4786-bff4-212a8da50662.png)

and I cannot remove it from my manifest of course.

Does anyone know what to do in this situation?

</details>

<details>

```
```

```
```

[✓] Flutter (Channel stable, 3.3.0, on macOS 12.6 21G115 darwin-x64, locale fr-QA)
    • Flutter version 3.3.0 on channel stable at /Users/.../flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffccd96b62 (3 weeks ago), 2022-08-29 17:28:57 -0700
    • Engine revision 5e9e0e0aa8
    • Dart version 2.18.0
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc3)
    • Android SDK at /Users/.../Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A309
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.71.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.6 21G115 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 105.0.5195.125

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

</details>

**Comment by danagbemava-nc** [comment]
Hi @tel-kho, please provide the versions of `url_launcher` and `url_launcher_android` that you are using. You can find the version of `url_launcher_android` in your `pubspec.lock` file. 

Thank you

**Comment by tel-kho** [comment]
> Hi @tel-kho, please provide the versions of `url_launcher` and `url_launcher_android` that you are using. You can find the version of `url_launcher_android` in your `pubspec.lock` file.
> 
> Thank you

Hello, yes sure:

  url_launcher:
    dependency: "direct main"
    description:
      name: url_launcher
      url: "https://pub.dartlang.org"
    source: hosted
    version: "6.1.5"
  url_launcher_android:
    dependency: transitive
    description:
      name: url_launcher_android
      url: "https://pub.dartlang.org"
    source: hosted
    version: "6.0.19"

**Comment by danagbemava-nc** [comment]
Hi @tel-kho, if you create a new project and add the `url_launcher` plugin, do you see the `REQUEST_INSTALL_PACKAGES` permission in your merged manifest? You can see this in `Android Studio` when you open `AndroidManifest.xml` and click on the `Merged Manifests` tab. 

I did this with a new project and I do not see that permission. I also do not see that permission used in the source for `url_launcher` or `url_launcher_android`.

**Comment by stuartmorgan** [comment]
> I searched online how to find where in my application permissions are used even by me or other packages, and I found this:
> 
> ![image](https://user-images.githubusercontent.com/56344804/191186577-cfa3587b-6da6-4016-9935-cada0bfbe8b1.png)
> 
> in the file "/My_Flutter_App/build/app/outputs/logs/manifest-merger-release-report.txt".

That file has the opposite order of how you are reading it; the permission (or other entry) comes first, and then the description of where it comes from. The two lines you've shown are the end of a previous section that you've trimmed out, which would say what is being included from `url_launcher_android`, and then the start of a new section that would tell you where `REQUEST_INSTALL_PACKAGES` came from (which you've also trimmed out). You need to look at the part below that excerpt to see what the source is.

Closing as this isn't coming from `url_launcher`, or anywhere else in the plugins repository, so isn't a Flutter bug.

**Comment by tel-kho** [comment]
> > I searched online how to find where in my application permissions are used even by me or other packages, and I found this:
> > ![image](https://user-images.githubusercontent.com/56344804/191186577-cfa3587b-6da6-4016-9935-cada0bfbe8b1.png)
> > in the file "/My_Flutter_App/build/app/outputs/logs/manifest-merger-release-report.txt".
> 
> That file has the opposite order of how you are reading it; the permission (or other entry) comes first, and then the description of where it comes from. The two lines you've shown are the end of a previous section that you've trimmed out, which would say what is being included from `url_launcher_android`, and then the start of a new section that would tell you where `REQUEST_INSTALL_PACKAGES` came from (which you've also trimmed out). You need to look at the part below that excerpt to see what the source is.
> 
> Closing as this isn't coming from `url_launcher`, or anywhere else in the plugins repository, so isn't a Flutter bug.

Yes, you are totally right, my bad the problematic permission is from another package: open_file
I made some research and indeed there is already [an issue](https://github.com/flutter/flutter/issues/108011) made about it and [another](https://github.com/crazecoder/open_file/issues/204) linked to the package itself.

Thank you all for your time
