### ISSUE TITLE
Linux 7, 14, 24 and 25 are dead and not sshable

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#111984]
This needs a lab visit.

<img width="1093" alt="Screen Shot 2022-09-20 at 9 56 17 AM" src="https://user-images.githubusercontent.com/54558023/191318954-42fb46b0-ea85-4cdf-ada5-76c52ef5fb23.png">
<img width="1111" alt="Screen Shot 2022-09-20 at 9 56 21 AM" src="https://user-images.githubusercontent.com/54558023/191318970-bfcf036b-19ca-4669-9313-3a7ac50a38e0.png">
<img width="1092" alt="Screen Shot 2022-09-22 at 11 20 26 AM" src="https://user-images.githubusercontent.com/54558023/191822405-bad9d434-4942-4eb2-bbdf-bdaef1be9a73.png">
<img width="1089" alt="Screen Shot 2022-09-20 at 9 56 26 AM" src="https://user-images.githubusercontent.com/54558023/191318982-0450b006-bb3c-46c6-8d7e-61af07af49ec.png">

**Comment by yusuf-goog** [comment]
replaced linux-25, and filed ticket to update mac address for ssh. salt master is not accepting key.

replaced linux-14, and filed ticket to update mac address for ssh. salt master is not accepting key.

linux-24 is not suffering from ssd issues. the host is up and ssh'able. Opening ticket to track that separately.

replaced linux-7, and filed ticket to update mac address for ssh. salt master is not accepting key.

mac address change request: t/214400329

**Comment by ricardoamador** [comment]
24 appears to be back online.
![image](https://user-images.githubusercontent.com/32242716/192346188-90009095-732d-4212-822e-fd1e642b308f.png)

**Comment by keyonghan** [comment]
Linux 7 is back;

Linux 14 need to authorize device:
```
adb devices -l
List of devices attached
ZY2244FCDB             unauthorized usb:3-3 transport_id:1
```

Linux 25 doesn't show any device:
```
adb devices -l
List of devices attached
```

**Comment by yusuf-goog** [comment]
Will take a look tomorrow at the devices when I get to the lab.

**Comment by ricardoamador** [comment]
Linux 7 is still dead.

**Comment by yusuf-goog** [comment]
linux-25 device was turned off, turned it on.
linux-7 device was stuck on auth screen, accepted.

**Comment by yusuf-goog** [comment]
linux-14 device needed auth.

**Comment by yusuf-goog** [comment]
linux-27 host was powered off.
mac-36 host was hung, rebooted.
linux-27 device was stuck on update screen. cleared that and its back.
