### ISSUE TITLE
[go_router] Provide a GoRouterState parameter to route-level redirect in GoRouteData

### ISSUE THREAD

**Issue by ezet** [flutter/flutter#111949]
## Use case

We rely on go_router with route-level redirects and use the `state` parameter to obtain information required to perform the correct redirections. This works fine with vanilla go_router, but the route-level redirect methods generated by `go_router_builder` does not provide a `state` parameter in the method definition.

We would really like to use `go_router_builder` for the static type checking, but this issue is blocking us from using it.

## Proposal
Add `GoRouterState state` as a parameter to the route-level `redirect` method definitions.
This would be a breaking change, but appears to me to be a crucial missing link between go_router API and the builder library.

**Comment by ezet** [comment]
After reviewing the current implementation of `GoRouterData`, I realize the previous proposal maybe isn't the best. A better idea might be to add a new method, similar to `buildPageWithState`.

Add `redirectWithState(GoRouterState state)` to `GoRouteData`. This avoids introducing breaking change, and provides an opt-in.

I suspect this would require changes to both `go_router` and `go_router_builder` ? I am not familiar enough with code generation in dart. If someone could point me in the right direction on how to implement the code generation part of this, I could possibly provide PRs for both libraries to support this.

**Comment by ezet** [comment]
I've looked at this, and unfortunately it does not. That proposal concerns the top-level redirect function on `GoRouter`, while my concern is with the route-level redirects, defined by `GoRouteData.redirect()`.

After some more investigation, I think my proposal can be implemented without any changes in `go_router_builder`, all required changes can be done in `GoRouteData` in the `go_router` package.

## New proposal
Add the following new method to `GoRouteData`:
```
  /// An optional redirect function for this route.
  ///
  /// Subclasses must override one of [build], [buildPageWithState], or
  /// [redirect].
  ///
  /// Corresponds to [GoRoute.redirect].
  String? redirectWithState(GoRouterState state) => redirect();
```

and change
`String? redirect(GoRouterState state) => factoryImpl(state).redirect();`
to
`String? redirect(GoRouterState state) => factoryImpl(state).redirect(state);`

This follows the same pattern as was done with `buildPage` and `buildPageWithState`, which introduced a similar change. In addition, we could deprecate `redirect()` and reference the new method, as was done with `buildPage`.

The change would be backwards compatible, and enable opt-in for the new feature by overriding `redirectWithState()` instead of `redirect()`.

I would be happy to provide a PR for this if the solution is acceptable.

**Comment by chunhtai** [comment]
duplicates of https://github.com/flutter/flutter/issues/110795
