### ISSUE TITLE
After recent update getting error on DraggableScrollableSheet

### ISSUE THREAD

**Issue by lastmeta** [flutter/flutter#111979]
I hadn't updated flutter for about 4-6 months I think. A few days ago I updated to the latest version and something that was working in my app began to fail. after checking my commit history for anything that might have caused it I believe it's due to the update.
The error:
```
Exception has occurred.
_AssertionError ('package:flutter/src/widgets/draggable_scrollable_sheet.dart': 
Failed assertion: line 170 pos 7: 
'isAttached': 
DraggableScrollableController is not attached to a sheet.
A DraggableScrollableController must be used in a DraggableScrollableSheet before any of its methods are called.)
```

The affected code: 
```
    ...
            DraggableScrollableSheet(
              initialChildSize: minHeight,
              minChildSize: minHeight,
              maxChildSize: min(1.0, max(minHeight, getMaxExtent(context))),
              controller: dController,
              builder: (context, scrollController) {
                bloc.scrollObserver.add(dController.size);
                return CoinDetailsGlidingSheet(
                  bloc.nullCacheView ? null : MetadataView(),
                  dController,
                  scrollController,
                );
              }),
```

It maybe that I was using `DraggableScrollableSheet` and its `DraggableScrollableController` in a dangerous configuration from the start and a recent update of flutter fixed a vulnerability related to those widgets?

Anyway, You can see what I'm trying to do here, observe the DraggableScrollableController.size value. Is there a more correct way to do it?

**Comment by TatsuUkraine** [comment]
not the best way to have side effects in the build method. There might be 2 options: add check [dController.isAttached](https://api.flutter.dev/flutter/widgets/DraggableScrollableController/isAttached.html) before `size` property is used

or subscribe to `dController` since it's `Listenable` somewhere in `initState` or something like that, in order to track size changes

https://api.flutter.dev/flutter/widgets/DraggableScrollableController-class.html
```
A [DraggableScrollableController](https://api.flutter.dev/flutter/widgets/DraggableScrollableController-class.html) is a [Listenable](https://api.flutter.dev/flutter/foundation/Listenable-class.html). It notifies its listeners whenever an attached sheet changes sizes. It does not notify its listeners when a sheet is first attached or when an attached sheet's parameters change without affecting the sheet's current size. It does not fire when [pixels](https://api.flutter.dev/flutter/widgets/DraggableScrollableController/pixels.html) changes without [size](https://api.flutter.dev/flutter/widgets/DraggableScrollableController/size.html) changing. For example, if the constraints provided to an attached sheet change.
```
