### ISSUE TITLE
"Timeout while attempting to retrieve Uri for Observatory" is causing Debug/Hot Reload not to work

### ISSUE THREAD

**Issue by luke14free** [flutter/flutter#11195]
## Steps to Reproduce
I just did a clean install of flutter following the install instructions

Then:

`flutter create myapp`

And:
`flutter run` 

In the myapp directory, but after a while I get `Error waiting for a debug connection: Exception: Timeout while attempting to retrieve URL for Observatory
Error launching application on iPhone 5s.` and the process exits (but the app continues running on the simulator).

## Logs

Run log:
```
🤖  :myapp luca$ flutter run
Launching lib/main.dart on iPhone 5s in debug mode...
Running Xcode build...                               11.6s
	    CFBundleIdentifier = "com.yourcompany.myapp";
	    PackageType = Developer;
	    SimulatorRootPath = "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk";
	    SimulatorUserPath = "/Users/luca/Library/Developer/CoreSimulator/Devices/7516F988-8A75-42A1-BB3E-562B09803648/data";
	}
	state->old_bundle: /Users/luca/Library/Developer/CoreSimulator/Devices/7516F988-8A75-42A1-BB3E-562B09803648/data/Containers/Bundle/Application/D43EF85C-FF17-4CC0-86EA-50D12337AC01/Runner.app
	state->new_bundle: /Users/luca/IdeaProjects/myapp/build/ios/Release-iphonesimulator/Runner.app
	state->dst_bundle: /Users/luca/Library/Developer/CoreSimulator/Devices/7516F988-8A75-42A1-BB3E-562B09803648/data/Library/Caches/com.apple.mobile.installd.staging/temp.Pq7Wra/extracted/Payload//Runner.app, binaryDiff flag: FALSE
		dst_ipa: /Users/luca/Library/Developer/CoreSimulator/Devices/7516F988-8A75-42A1-BB3E-562B09803648/data/Library/Caches/com.apple.mobile.installd.staging/temp.Pq7Wra/extracted
	    arguments =     (
	        "--enable-dart-profiling",
	        "--flx=/Users/luca/IdeaProjects/myapp/build/app.flx",
	        "--dart-main=/Users/luca/IdeaProjects/myapp/lib/main.dart",
	        "--packages=/Users/luca/IdeaProjects/myapp/.packages",
	        "--enable-checked-mode",
	        "--observatory-port=8100",
	        "--diagnostic-port=8101"
	    );
	    environment =     {
	    };
	}
		retryTimeout: 120.000000 (default write com.apple.CoreSimulatorBridge LaunchRetryTimeout <value>)
		bootTimeout: 300.000000 (default write com.apple.CoreSimulatorBridge BootRetryTimeout <value>)
		bootLeeway: 120.000000 (default write com.apple.CoreSimulatorBridge BootLeeway <value>)
		Note: Use 'xcrun simctl spawn booted defaults write <domain> <key> <value>' to modify defaults in the booted Simulator device.
	Simulator booted at: 2017-07-13 10:21:45 +0000
	Current time: 2017-07-13 10:26:00 +0000
	Within boot leeway: NO
Error waiting for a debug connection: Exception: Timeout while attempting to retrieve URL for Observatory
Error launching application on iPhone 5s.
```

Analyze:
```
🤖  :myapp luca$ flutter analyze
Analyzing /Users/luca/IdeaProjects/myapp...
No issues found!
Ran in 4.2s
```

## Flutter Doctor
```
🤖  :myapp luca$ flutter doctor
[✓] Flutter (on Mac OS X 10.12 16A323, locale en-US, channel alpha)
    • Flutter at /Users/luca/flutter
    • Framework revision d36e2f6191 (3 weeks ago), 2017-06-21 15:09:10 -0700
    • Engine revision b0dee695ec
    • Tools Dart version 1.24.0-dev.6.7

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.2)
    • Android SDK at /Users/luca/Library/Android/sdk
    • Platform android-25, build-tools 25.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b05)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3, Build version 8E162
    • ios-deploy 1.9.1
    • CocoaPods version 1.2.0

[✓] Android Studio (version 2.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Gradle version 2.14.1
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b05)

[✓] IntelliJ IDEA Community Edition (version 2017.1.5)
    • Flutter plugin version 15.1
    • Dart plugin version 171.4694.29

[✓] Connected devices
    • iPhone 5s • 7516F988-8A75-42A1-BB3E-562B09803648 • ios • iOS 10.3 (simulator)
```

**Comment by eseidelGoogle** [comment]
That message means that `flutter` failed to connect to your app running inside the simulator.  That is unexpected (especially since they're running on the same computer).  Your Flutter version is the latest alpha (3 weeks old) which I've not heard of having this sort of connection problem.  You might try restarting your computer or @cbracken may have other tips?

**Comment by cbracken** [comment]
I'd definitely be curious to hear whether quitting and restarting the simulator (or rebooting, the simulator starts a bunch of daemons that we've previously seen hang once in a while) helps here.

**Comment by luke14free** [comment]
Tried both restarting the mac and the simulator. Nothing changed. :-( @cbracken

**Comment by cbracken** [comment]
@luke14free Thanks for checking. Would you mind pasting the results of `flutter run -v` (verbose mode)? That would help identify how far things get.

**Comment by luke14free** [comment]
@cbracken yes sorry for the delay: https://gist.github.com/luke14free/5d366b6aa97f31befb37283caca11d59

**Comment by luke14free** [comment]
the issue seems to be:

```[     +367 ms] [SYS LOG] Jul 16 10:06:57 --- last message repeated 9 times ---
[            ] [SYS LOG] Jul 16 10:06:57 🤖   StatusBarApp[501]: RTCheckForHang:[Case 1]: No Wireless NIC Plug in
[     +250 ms] [SYS LOG] Jul 16 10:06:57 🤖   diagnosticd[317]: Unexpected xpc type [<bool: 0x7fffb8df9ac8>: false]
```

**Comment by luke14free** [comment]
I uninstalled the driver but still no luck, the "No Wireless NIC Plug in" disappeared but now I think that the error is `Refusing to execute/trust quarantined program/file: com.invisionlabs.CraftManagerHelper` which is something I have no idea of how to fix

**Comment by cbracken** [comment]
Thanks! This is useful. It looks like somehow we're picking up a whole bunch of logs we don't care about and missing out on the simulator logs we do care about. 

A couple more things that might help:
1. In order to rule out a simulator-state related issue, can you try with a simulator device other than the 5S -- say an iPhone 6S?
1. Just to verify, there are no physical devices connected, correct?

**Comment by luke14free** [comment]
apologies for the delay of my answer, yes and yes @cbracken

**Comment by luke14free** [comment]
quick update: everything works on a real device. it's just the simulators that have problems

**Comment by Hixie** [comment]
We have no idea how to further debug this problem from here. Does this work for other non-Flutter apps?

We're going to close this bug because we don't know how to progress with it.

If you're able to provide more details, please do file a new bug to let us know.
