### ISSUE TITLE
[TextField] Cast Error Null Value on Numeric TextFields

### ISSUE THREAD

**Issue by dlondonog** [flutter/flutter#111939]
A Cast Error is appearing when you use a numeric keyboard on Numeric TextFields.

## Steps to Reproduce

```
import 'package:flutter/material.dart';

class Prueba extends StatefulWidget {
  const Prueba({Key? key}) : super(key: key);

  @override
  State<Prueba> createState() => _PruebaState();
}

class _PruebaState extends State<Prueba> {

  final numController             = TextEditingController();

  @override
  Widget build(BuildContext context) {

    return Scaffold(
      appBar: AppBar(
        title: const Text('Test'),
      ),
      body: TextField(
        controller: numController,
        keyboardType: TextInputType.number
      )
    );
  }
```

**Expected results:** 
With the Flutter update I started noticing that numeric text boxes get an error when they are empty.
I managed to reduce the code to the minimum expression to identify the source of the error and apparently it is at the moment of defining the keyboard (**TextInputType.number**)

**Actual results:** 

When I tap the box to enter the number on an Android Physical Device, this is the error that appears on console:

> ════════ Exception caught by services library ════════
> 
> The following _CastError was thrown during method call TextInputClient.performPrivateCommand: Null check operator used on a null value
> 
> When the exception was thrown, this was the stack #0 EditableTextState.performPrivateCommand package:flutter/…/widgets/editable_text.dart:2155 #1 TextInput._handleTextInputInvocation package:flutter/…/services/text_input.dart:1821 #2 TextInput._loudlyHandleTextInputInvocation package:flutter/…/services/text_input.dart:1701 #3 MethodChannel._handleAsMethodCall package:flutter/…/services/platform_channel.dart:536 #4 MethodChannel.setMethodCallHandler. package:flutter/…/services/platform_channel.dart:529 #5 _DefaultBinaryMessenger.setMessageHandler. package:flutter/…/services/binding.dart:387 #6 _invoke2 (dart:ui/hooks.dart:186:13) #7 _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:42:5) #8 _Channel.push (dart:ui/channel_buffers.dart:132:31) #9 ChannelBuffers.push (dart:ui/channel_buffers.dart:329:17) #10 PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:599:22) #11 _dispatchPlatformMessage (dart:ui/hooks.dart:89:31) call: MethodCall(TextInputClient.performPrivateCommand, [13, {data: {}, action: Normal_Mode}])

If I don't include a numeric keyboard, the error disappears.

@Chance included the following comments in [StackOverflow link](https://stackoverflow.com/questions/73776860/how-to-avoid-cast-error-null-value-on-numeric-textfields?noredirect=1#comment130279967_73776860):

> It was good to open an issue for this problem on the flutter channel, another detail that **this problem appears on android and samsung devices have an error in 100% of the cases**. In version 3.3 there are some very critical problems on the part of flutter, such as the pageview line 455 value being initialized null and causing white screen where there is tabview or pageview.
> 
> Line 2155 editable_text: widget.onAppPrivateCommand!(action, data);. Yet another case of a null statement that fails. Interim fix made in flutter code: if(widget.onAppPrivateCommand != null)widget.onAppPrivateCommand!(action, data);.

**Comment by danagbemava-nc** [comment]
Hi @dlondonog, are you experiencing this on a Samsung device?

Please also provide the output of `flutter doctor -v`. 

Thank you

**Comment by sostenesgomes** [comment]
+1

**Comment by dlondonog** [comment]
> Hi @dlondonog, are you experiencing this on a Samsung device?
> 
> Please also provide the output of `flutter doctor -v`.
> 
> Thank you

[✓] Flutter (Channel stable, 3.3.2, on macOS 12.6 21G115 darwin-x64, locale es-419)
    • Flutter version 3.3.2 on channel stable at /Users/dlondono/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e3c29ec00c (6 days ago), 2022-09-14 08:46:55 -0500
    • Engine revision a4ff2c53d8
    • Dart version 2.18.1
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/dlondono/Library/Android/sdk
    • Platform android-33, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A309
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.71.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (3 available)
    • iPhone 14 Pro Max (mobile) • 3FC36180-5816-44D6-9517-C46C03DBAC80 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-16-0 (simulator)
    • macOS (desktop)            • macos                                • darwin-x64     • macOS 12.6 21G115 darwin-x64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 105.0.5195.125

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Comment by danagbemava-nc** [comment]
Hi @dlondonog, what device(s) are you experiencing this issue on?

**Comment by dlondonog** [comment]
> Hi @dlondonog, what device(s) are you experiencing this issue on?

I could identify the issue on Samsung (SM J260MU)...

[✓] Flutter (Channel stable, 3.3.2, on macOS 12.6 21G115 darwin-x64, locale es-419)
    • Flutter version 3.3.2 on channel stable at /Users/dlondono/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e3c29ec00c (6 days ago), 2022-09-14 08:46:55 -0500
    • Engine revision a4ff2c53d8
    • Dart version 2.18.1
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/dlondono/Library/Android/sdk
    • Platform android-33, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A309
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.71.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (4 available)
    • SM J260MU (mobile)         • e27c069a                             • android-arm    • Android 8.1.0 (API 27)
    • iPhone 14 Pro Max (mobile) • 3FC36180-5816-44D6-9517-C46C03DBAC80 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-0
      (simulator)
    • macOS (desktop)            • macos                                • darwin-x64     • macOS 12.6 21G115 darwin-x64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 105.0.5195.125

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Comment by ladookie4343** [comment]
I'm also experiencing the same issue on a Samsung device (SM G950U)

**Comment by danagbemava-nc** [comment]
Thanks for the info. There's a similar issue already open tracking this issue in https://github.com/flutter/flutter/issues/97634. 

Kindly follow up in the linked issue for updates. 

Closing from here as duplicate. 

Thank you
