### ISSUE TITLE
run " flutter create --template module flutter_module "     no engine floder   in  .ios  

### ISSUE THREAD

**Issue by fanhaofei1234** [flutter/flutter#111959]
flutter sdk  3.3.2

ios project   not found   Flutter.h

**Comment by huycozy** [comment]
Hi @fanhaofei1234 
>ios project not found Flutter.h

Please provide full logs so that we can investigate the issue (if it's too long, please save it into a file and attach it here). Also, please provide detailed steps to reproduce this issue as well. Thanks!

**Comment by z234009184** [comment]
the same issue
