### ISSUE TITLE
Ability to override just "some" of default TextStyle attributes in CupertinoTextThemeData

### ISSUE THREAD

**Issue by ramtinq** [flutter/flutter#111953]
`CupertinoTextThemeData`'s `TextStyle` should maintain default values when setting some attributes.

Example:
If you just want to change the default text color throughout the app:
```
return CupertinoApp(
        title: 'Test App',
        theme: const CupertinoThemeData(
            textTheme: CupertinoTextThemeData(
                primaryColor: CupertinoColors.black,
                textStyle: TextStyle(
                  color: CupertinoColors.darkBackgroundGray, /// here
                ))),
...
```

This will result change in `fontSize` across the whole app which is not intended behavior. There should be some way to adjust only a selection of `TextStyle` attributes, like text color, keeping other `TextStyle`'s default values, like fontSize untouched.

Thank you for all the great work.

**Comment by danagbemava-nc** [comment]
Hi @ramtinq, this seems like a bug, can you provide a complete minimal reproducible code sample along with the output of `flutter doctor -v`? 

Thank you
