### ISSUE TITLE
Can't scroll through whole viewport using ScrollBar.

### ISSUE THREAD

**Issue by knopp** [flutter/flutter#111968]
Run the example below and keep scrolling using the scrollbar from beginning to end multiple times. Eventually you should stop seeing the red lines at the beginning and end. 

This is a regression after https://github.com/flutter/flutter/pull/111250 . I think this is caused by multiple factors though. Viewport dimensions in flutter tend to change depending on current scroll position and sliver layout and often is just an approximation. Scroll offset during scrollbar dragging is adjusted relatively after each movement which compounds the error. Eventually this causes problem at the scroll boundaries.

I think possible solution would be to force position.minScrollExtent and position.maxScrollExtent at scrollbar boundaries. With the complication of position.maxScrollExtent being an approximation that might change once actually scrolled to end. 

Perhaps the end position could be determined through several layout iterations (if the viewport dimensions keep changing).

cc @TahaTesser 

```bash
flutter pub add flutter_lorem
```

```dart
import 'package:flutter/material.dart';
import 'package:flutter_lorem/flutter_lorem.dart';

void main() {
  runApp(const MaterialApp(
    title: 'Flutter Demo',
    home: MyHomePage(),
  ));
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  late List<String> items;

  @override
  void initState() {
    super.initState();
    items = List<String>.generate(
        100, (i) => lorem(paragraphs: 1, words: Object.hash(i, null) % 100));
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: CustomScrollView(
        slivers: [
          SliverToBoxAdapter(
            child: Container(
              height: 2,
              color: Colors.red,
            ),
          ),
          SliverList(
            delegate: SliverChildBuilderDelegate(
              (context, index) => Padding(
                padding: const EdgeInsets.all(20),
                child: Text(items[index]),
              ),
              childCount: items.length,
            ),
          ),
          SliverToBoxAdapter(
            child: Container(
              height: 2,
              color: Colors.red,
            ),
          ),
        ],
      ),
    );
  }
}
```

**Comment by TahaTesser** [comment]
Investigating this. 

cc: @Piinks

**Comment by TahaTesser** [comment]
@Piinks 
Agreed! I will investigate more and hopefully reland with regression tests

**Comment by knopp** [comment]
I think the original PR was not necessarily wrong. This just points to a deeper problem with how scrollbar interacts with scroll position. You shouldn't need to overdrag a scrollbar in order to get to actual viewport boundaries.

**Comment by TahaTesser** [comment]
> You shouldn't need to overdrag a scrollbar in order to get to actual viewport boundaries.

Exactly. I did some initial testing with the code sample you've provided and compared it to to App Store app scrollbar. Scrollbar reached down without over-drag.

**Comment by Piinks** [comment]
I think in this case, the maxScrollExtent is not precise because unless there are fixed, predetermined metrics, the scroll view will estimate the max extent. 

Here is some more context:
- https://github.com/flutter/flutter/issues/97676
- https://github.com/flutter/flutter/issues/95028

In cases where Flutter can't determine the exact max extent ahead of time, you may want to allow overdrag. Or, what may be needed here is edge scrolling, like with text selection. Where dragging the scrollbar to the end but there is still more extent to reveal, holding the pointer there at the end will animate the scroll view further forward.. Not sure which is best, I will leave that up to @TahaTesser to explore. :)

**Comment by knopp** [comment]
I suggested some of possible options in original comment. 

I think the `minScrollExtent` should be more or less always correct. So when the scrollbar is at top position it should always be at minScrollExtent, regardless of possible error accumulated on the way.

`maxScrollExtent` is trickier, since you can know for sure what it is only when trailing children are materialized. That's where I suggested possible iterative approach, i.e. when reaching end set the scroll position to max scroll extent multiple times in a row. This may take multiple layout passes to settle, perhaps even multiple frames, but it would still be better than relying on manually overdraging the scrollview. 

I think no matter how good the estimation is, there are still going to be corner cases.

**Comment by knopp** [comment]
Also to consider - we have a custom version of `SliverList`, that supports variable item extents with very long lists. This is currently not doable with flutter `SliverList` because to jump at any offset it needs to materialize and layout all items before. 

We instead esitmate target index from scroll offset and then generate items in cached area. When scrolling up the scroll offset is periodically adjusted to account of error in our estimation vs actual item height. It works very well, but in some cases confuses Flutter scrollbars even more than regular `SliverList` :)

**Comment by TahaTesser** [comment]
@Piinks  @knopp 
This helps a lot! I'm looking forward to figuring this out.

**Comment by Piinks** [comment]
> This may take multiple layout passes to settle, perhaps even multiple frames

This sounds like it would be very expensive and potentially have performance issues. Layout in flutter is single pass in order to maintain fast and efficient performance.

**Comment by knopp** [comment]
> > This may take multiple layout passes to settle, perhaps even multiple frames
> 
> This sounds like it would be very expensive and potentially have performance issues. Layout in flutter is single pass in order to maintain fast and efficient performance.

There are possibly multiple passes in sliver layout when correcting scroll offset, though those are usually not complete passes.

I meant more something like scheduling additional frame with new offset while user is pressing down at the end of scrollbar, i.e. something that user would do when overdragging, just automatically. But I understand how that might be bit questionable.

**Comment by knopp** [comment]
Other possible option would be hint in SliverConstraint that scrolling is at the end, in which case SliverList may be able to correct scroll offset to actually reach the very end of content. Again, this might need several passes, but when scrolling to end SliverList already materializes and lays out all children, so this operation is already heavy, I don't think those few extra missing children would be much of an overhead.
