### ISSUE TITLE
Add Headers to M3 Demo App

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#111999]
It would be cool if https://flutter-experimental-m3-demo.web.app/#/ would tell me the names of the components that are showcased in the component tab. Maybe we could add some headers (e.g. IconButton, Chip, etc) for the individual sections?

Maybe we can even add links to the API docs for these components so developers can find out easily how to add the particular component to their own app?

/cc @QuncCccccc @darrenaustin

**Comment by darrenaustin** [comment]
I have thought about suggesting headers myself. The original intent was to have a dense single screen to show off all the components and how they look in M3. Now that the number and size of the components has grown, perhaps that is unreasonable. Or perhaps we only show the labels when we are on a larger device. @QuncCccccc when you get a chance to add the multi-column layout for larger displays, perhaps you can look at adding header? Also, if we want them to be links we will need to add a dependency to launch them.
