### ISSUE TITLE
[go_router] nested navigation support for subpages with different paths

### ISSUE THREAD

**Issue by nyarian** [flutter/flutter#111932]
Greetings, and, first of all, thanks for all your work and such a great package.

It does not seem that go_router supports nested navigation for subpages having different subpaths (say, "/settings" and "/entity", where settings and entities list are nested pages).

There are issues which discuss [multiple routers support](https://github.com/csells/go_router/discussions/78) (so each of the tab maintains its own navigation stack) and [nested navigation support](https://gorouter.dev/nested-navigation), but these don't really cover the issue being described, as the first is unrelated due to this issue having nothing to do with nested navigation stacks, and the second covers the case when subpages with different URLs fall under the same path as only ":fid" argument being passed changes.

<details>
  <summary>Test case description</summary>
As an example, let's have a simple app which has "entities list" and "settings" tabs: there is a home page with a nested navigation controller (bottom nav bar, navigation rail, navigation drawer, etc.) and the "entities list" and "settings" pages are nested inside the home page, so that they are being presented inside the home page (say, between the app bar and bottom navigation bar). The URLs should be "/entity" and "/settings" respectively. Here's the proper initial state of the app:

URL: "#/entity" or "#/settings"
WidgetsApp
  - HomePage (entities list | settings)

Once any item from the list of items in the "entities list" page is tapped, an entity details should be added to the top of the stack. The URL should be "/entity/:id":

URL: "#/entity/1"
WidgetsApp
  - HomePage (entities list)
  - EntityDetailsPage

Switching between tabs happens via `context.go('/settings')` and `context.go('/entity')` respectively. Pushing the entity details page happens with `context.go('/entity/$id')`.
</details>

Strictly speaking, it does not seem to be possible to configure go_router adequately for handling such a case. Below is a set of possible configurations that strive to achieve both the technical goal and clean implementation (but all of which fail to have both).

<details>
  <summary>"Idiomatic" configuration</summary>

It would be an (imho) idiomatic solution from the APIs standpoint, but it obviously does not achieve the goal. A configuration like this will have obviously erroneous, as `go`-ing to a URL such as `/entity/1` will spawn an unwanted intermediate stand-alone "entity" page, and navigating between the tabs will create and push additional routes, too, instead of updating the existing `HomePageState` instance.

```dart
  GoRouter(
    initialLocation: '/',
    routes: [
      GoRoute(
        path: '/',
        builder: (context, state) => const HomePage(),
        routes: [
          GoRoute(
            path: 'settings',
            builder: (context, state) => const SettingsPage(),
          ),
          GoRoute(
            path: 'entity',
            builder: (context, state) => const EntitiesPage(),
            routes: [
              GoRoute(
                path: ':id',
                builder: (context, state) => EntityDetailsPage(
                  id: state.params['id']!,
                ),
              )
            ],
          ),
        ],
      ),
    ],
  )
```

Initial:
URL: "/"
WidgetsApp
  - HomePage (entities list)
  
Upon going to the "settings" tab:
URL: "/settings"
WidgetsApp
  - HomePage (entities list)
  - SettingsPage <-- undesired, we only want for the home page to change it's nested page
  
Upon going to an entity details from the entities list nested page:
URL: "/entity/1"
WidgetsApp
  - HomePage (entities list)
  - EntitiesPage <-- undesired, we already have it as a nested page inside HomePage
  - EntityDetailsPage (id: 1)
</details>

<details>
  <summary>Path parameter workaround</summary>
  
It achieves the technical goal, but is far from idiomatic and convenient. This makes the actual thing technically possible: when another bottom bar's option is tapped, the navigation call results into the same `HomePageState`'s `didUpdateWidget` method being called with the widget that has the another "nested page" index. On the other hand, it makes the subroutes configuration a total erroneous mess: because we can't specify the subroute's parent explicitly, a thing such as "settings/1" is possible and opens the entity details page, and handling that manually implies checking the full route path and validating whether such a combination is possible, which shifts the internal navigation logic away from GoRouter, and that defeats the purpose of the package.

```dart
  GoRouter(
    initialLocation: '/',
    routes: [
      GoRoute(
        path: '/',
        redirect: (state) => '/entity',
        builder: (context, state) => throw UnimplementedError(), // Required because of the temporary issue in go_router 4.5.0
      ),
      GoRoute(
        path: '/:nested(entity|settings)', // We allow "/entity" and "/settings" routes
        builder: (context, state) {
          final nested = state.params['nested'] ?? 'none';
          final mapping = {
            'entity': const HomePage(),
            'settings': const HomePage(page: 1),
          };
          return mapping[nested] ?? const HomePage();
        },
        routes: [
          GoRoute(
            path: ':id',
            builder: (context, state) => EntityDetailsPage(
              id: state.params['id']!,
            ),
          ),
        ],
      ),
    ],
  )
```

On the actual results when using the programmed navigation options it's all as desired.
</details>

<details>
  <summary>Path-to-query-param configuration</summary>

This configuration achieves the technical goal just as the second one, but leaves the internal navigation logic to GoRouter as it should in exchange of not having the proper URLs for nested pages. We don't have `/entity` and `/settings` anymore, instead these are `/?subroute=entity` and `/?subroute=settings`, and these are just not URLs that are needed. 

```dart
  GoRouter(
    initialLocation: '/',
    routes: [
      GoRoute(
        path: '/entity',
        redirect: (state) => '/?subroute=entity',
        builder: (context, state) => throw UnimplementedError(),
      ),
      GoRoute(
        path: '/settings',
        redirect: (state) => '/?subroute=settings',
        builder: (context, state) => throw UnimplementedError(),
      ),
      GoRoute(
        path: '/',
        builder: (context, state) {
          final subroute = state.queryParams['subroute'] ?? 'none';
          final mapping = {
            'entity': 0,
            'settings': 1,
          };
          return HomePage(page: mapping[subroute] ?? 0);
        },
        routes: [
          GoRoute(
            path: 'entity/:id',
            builder: (context, state) => EntityDetailsPage(
              id: state.params['id']!,
            ),
          ),
        ],
      ),
    ],
  )
```
</details>

I haven't found neither could come up myself with any other options to make it happen. All the described ones have their pros and cons, but ultimately these are workarounds and are far from proper solutions.

It seems that having an API for stating that `/settings` and `/entity` pages are not stand-alone, but rather are nested inside the home page, would be nice to have, but I don't see how it could be added without bloating the existing ones.

Any ideas?

<details>
  <summary>Full code sample</summary>
  
```dart
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';

void main() => runApp(const GoRouterApplication());

class GoRouterApplication extends StatelessWidget {
  const GoRouterApplication({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
      routerDelegate: _router.routerDelegate,
      routeInformationParser: _router.routeInformationParser,
      routeInformationProvider: _router.routeInformationProvider,
    );
  }

  // Messed URLs configuration
  static final _router = GoRouter(
    initialLocation: '/',
    routes: [
      GoRoute(
        path: '/entity',
        redirect: (state) => '/?subroute=entity',
        builder: (context, state) => throw UnimplementedError(),
      ),
      GoRoute(
        path: '/settings',
        redirect: (state) => '/?subroute=settings',
        builder: (context, state) => throw UnimplementedError(),
      ),
      GoRoute(
        path: '/',
        builder: (context, state) {
          final subroute = state.queryParams['subroute'] ?? 'none';
          final mapping = {
            'entity': 0,
            'settings': 1,
          };
          return HomePage(page: mapping[subroute] ?? 0);
        },
        routes: [
          GoRoute(
            path: 'entity/:id',
            builder: (context, state) => EntityDetailsPage(
              id: state.params['id']!,
            ),
          ),
        ],
      ),
    ],
  );

  // Workaround configuration
  // static final _router = GoRouter(
  //   initialLocation: '/',
  //   routes: [
  //     GoRoute(
  //       path: '/',
  //       redirect: (state) => '/entity',
  //       builder: (context, state) => throw UnimplementedError(),
  //     ),
  //     GoRoute(
  //       path: '/:nested(entity|settings)',
  //       builder: (context, state) {
  //         final nested = state.params['nested'] ?? 'none';
  //         final mapping = {
  //           'entity': const HomePage(),
  //           'settings': const HomePage(page: 1),
  //         };
  //         return mapping[nested] ?? const HomePage();
  //       },
  //       routes: [
  //         GoRoute(
  //           path: ':id',
  //           builder: (context, state) => EntityDetailsPage(
  //             id: state.params['id']!,
  //           ),
  //         ),
  //       ],
  //     ),
  //   ],
  // );

  // Default configuration
  // static final _router = GoRouter(
  //   initialLocation: '/',
  //   routes: [
  //     GoRoute(
  //       path: '',
  //       builder: (context, state) => const HomePage(),
  //       routes: [
  //         GoRoute(
  //           path: 'settings',
  //           builder: (context, state) => const SettingsPage(),
  //         ),
  //         GoRoute(
  //           path: 'entity',
  //           builder: (context, state) => const EntitiesPage(),
  //           routes: [
  //             GoRoute(
  //               path: ':id',
  //               builder: (context, state) => EntityDetailsPage(
  //                 id: state.params['id']!,
  //               ),
  //             )
  //           ],
  //         ),
  //       ],
  //     ),
  //   ],
  // );
}

class HomePage extends StatefulWidget {
  final int page;

  const HomePage({this.page = 0, super.key});

  @override
  State<HomePage> createState() => _HomePageState();

  @override
  void debugFillProperties(DiagnosticPropertiesBuilder properties) {
    super.debugFillProperties(properties);
    properties.add(IntProperty('page', page));
  }
}

class _HomePageState extends State<HomePage> {
  late int _page;

  @override
  void initState() {
    super.initState();
    _page = widget.page;
  }

  @override
  void didUpdateWidget(covariant HomePage oldWidget) {
    super.didUpdateWidget(oldWidget);
    _page = widget.page;
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Home')),
      body: _pageToIndex[_page]!,
      bottomNavigationBar: BottomNavigationBar(
        currentIndex: _page,
        onTap: (index) => _indexToCall[index]!.call(context),
        items: const [
          BottomNavigationBarItem(
            icon: Icon(Icons.person),
            label: 'Entities',
          ),
          BottomNavigationBarItem(
            icon: Icon(Icons.settings),
            label: 'Settings',
          ),
        ],
      ),
    );
  }

  static const _pageToIndex = {
    0: EntitiesPage(),
    1: SettingsPage(),
  };

  static final _indexToCall = <int, void Function(BuildContext)>{
    0: (ctx) => ctx.go('/entity'),
    1: (ctx) => ctx.go('/settings'),
  };
}

class SettingsPage extends StatelessWidget {
  const SettingsPage({super.key});

  @override
  Widget build(BuildContext context) {
    return const Center(child: Text('Settings'));
  }
}

class EntitiesPage extends StatelessWidget {
  const EntitiesPage({super.key});

  @override
  Widget build(BuildContext context) {
    return Center(
      child: Column(
        mainAxisSize: MainAxisSize.min,
        children: [
          OutlinedButton(
            onPressed: () => context.go('/entity/1'),
            child: const Text('Go to entity 1 details'),
          ),
        ],
      ),
    );
  }
}

class EntityDetailsPage extends StatelessWidget {
  final String id;

  const EntityDetailsPage({
    required this.id,
    super.key,
  });

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Entity Details')),
      body: Center(child: Text('Entity #$id')),
    );
  }

  @override
  void debugFillProperties(DiagnosticPropertiesBuilder properties) {
    super.debugFillProperties(properties);
    properties.add(StringProperty('id', id));
  }
}
```
</details>

**Comment by huycozy** [comment]
Hi @nyarian, thanks for filing the issue.
Did you try implementing a solution with `ShellRoute`? It's added recently to support multiple navigation stacks, please see #108141, #99126

**Comment by nyarian** [comment]
Hey @huycozy. I wasn't viewing the issue from the 'multiple stacks' POV as a single root destination is needed to be displayed inside the container with no internal subroutes, but I went ahead and moved everything to ShellRoute implementation. And it turned out to work, thank you!

Though there is a small one: I wanted to complete the sample for potential future readers and tried to apply the slide animation for the tab change, so the animations issue popped up: typical bottom bar navigation right-to-left and left-to-right slide transitions would make sense for this example (just like in the previous examples I've shared), but, alas, internal navigator uses the default right-to-left slide transition (which makes sense given the implementation details), and the custom `pageBuilder` for a ShellRoute's subroutes just does not seem to work (the animation gets ignored at all; tried to use secondaryAnimation, too - no luck). Is there something I misunderstood in the API? The same `pageBuilder` configuration works perfectly for the details page, which is outside of the `ShellRoute`'s scope.

<details>
<summary>Here's the complete code snippet: just uncomment the `pageBuilder`s and comment `builder`s</summary>

import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';

void main() => runApp(const GoRouterApplication());

class GoRouterApplication extends StatelessWidget {
  const GoRouterApplication({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
      routerDelegate: _router.routerDelegate,
      routeInformationParser: _router.routeInformationParser,
      routeInformationProvider: _router.routeInformationProvider,
    );
  }

  static final _router = GoRouter(
    navigatorKey: _rootNavigator,
    initialLocation: '/',
    routes: [
      GoRoute(
        path: '/',
        redirect: (state) => '/entity',
        builder: (context, state) => throw UnimplementedError(),
      ),
      ShellRoute(
        navigatorKey: _homeNavigator,
        builder: (context, state, child) => HomePage(child: child),
        routes: [
          GoRoute(
            path: '/entity',
            builder: (context, state) => const EntitiesPage(),
            // pageBuilder: (context, state) => CustomTransitionPage<void>(
            //   child: const EntitiesPage(),
            //   transitionsBuilder: (context, primary, _, child) {
            //     final tween = Tween<Offset>(
            //       begin: const Offset(-1, 0),
            //       end: Offset.zero,
            //     ).chain(CurveTween(curve: Curves.linear));
            //     return SlideTransition(
            //       position: primary.drive(tween),
            //       child: child,
            //     );
            //   },
            // ),
            routes: [
              GoRoute(
                path: ':id',
                parentNavigatorKey: _rootNavigator,
                builder: (_, state) =>
                    EntityDetailsPage(id: state.params['id']!),
              ),
            ],
          ),
          GoRoute(
            path: '/settings',
            builder: (context, state) => const SettingsPage(),
            // pageBuilder: (context, state) => CustomTransitionPage<void>(
            //   child: const SettingsPage(),
            //   transitionsBuilder: (context, primary, _, child) {
            //     final tween = Tween<Offset>(
            //       begin: const Offset(1, 0),
            //       end: Offset.zero,
            //     ).chain(CurveTween(curve: Curves.linear));
            //     return SlideTransition(
            //       position: primary.drive(tween),
            //       child: child,
            //     );
            //   },
            // ),
          ),
        ],
      ),
    ],
  );

  static final _rootNavigator = GlobalKey<NavigatorState>(debugLabel: 'root');
  static final _homeNavigator = GlobalKey<NavigatorState>(debugLabel: 'home');
}

class HomePage extends StatelessWidget {
  final Widget child;

  const HomePage({required this.child, super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Home')),
      body: child,
      bottomNavigationBar: BottomNavigationBar(
        currentIndex: _calculateSelectedPageIndex(context),
        onTap: (value) => _onPageIndexChanged(context, value),
        items: const [
          BottomNavigationBarItem(
            icon: Icon(Icons.person),
            label: 'Entities',
          ),
          BottomNavigationBarItem(
            icon: Icon(Icons.settings),
            label: 'Settings',
          ),
        ],
      ),
    );
  }

  int _calculateSelectedPageIndex(BuildContext context) {
    final GoRouter route = GoRouter.of(context);
    final String location = route.location;
    return _locationMapping[location] ?? 0;
  }

  void _onPageIndexChanged(BuildContext context, int value) {
    GoRouter.of(context).go(_indexMapping[value]!);
  }

  static const _locationMapping = {
    '/entity': 0,
    '/settings': 1,
  };

  static final _indexMapping =
      _locationMapping.map((key, value) => MapEntry(value, key));
}

class SettingsPage extends StatelessWidget {
  const SettingsPage({super.key});

  @override
  Widget build(BuildContext context) {
    return const Center(child: Text('Settings'));
  }
}

class EntitiesPage extends StatelessWidget {
  const EntitiesPage({super.key});

  @override
  Widget build(BuildContext context) {
    return Center(
      child: Column(
        mainAxisSize: MainAxisSize.min,
        children: [
          OutlinedButton(
            onPressed: () => context.go('/entity/1'),
            child: const Text('Go to entity 1 details'),
          ),
        ],
      ),
    );
  }
}

class EntityDetailsPage extends StatelessWidget {
  final String id;

  const EntityDetailsPage({
    required this.id,
    super.key,
  });

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Entity Details')),
      body: Center(child: Text('Entity #$id')),
    );
  }

  @override
  void debugFillProperties(DiagnosticPropertiesBuilder properties) {
    super.debugFillProperties(properties);
    properties.add(StringProperty('id', id));
  }
}

</details>

**Comment by huycozy** [comment]
Hi @nyarian 
Glad you solved this issue with `ShellRoute`.

>and the custom pageBuilder for a ShellRoute's subroutes just does not seem to work (the animation gets ignored at all; tried to use secondaryAnimation, too — no luck). Is there something I misunderstood in the API?

It seems this issue is related to ShellRoute's animation itself. Please file a new issue for this.
In the new issue, please clarify some points below (it will be helpful for us when verifying the issue):
- Does this issue only happen when using ShellRoute?
- A [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
- The output of `flutter doctor -v`
- Reproduction steps, Expected results, Actual results

Thank you!

**Comment by nyarian** [comment]
Yeah, better I file a new issue for animations given the original routing and URLs problem is resolved. Thank you!
