### ISSUE TITLE
APK works but device is "not available for your device" when published as AAB through Google Play

### ISSUE THREAD

**Issue by fuglede** [flutter/flutter#111987]
If I create an APK using `flutter build apk`, I can install and run my Flutter application (which is more or less the basic app template with a few charts added), but if I follow the [steps to publish the Android app](https://docs.flutter.dev/deployment/android) using `flutter build appbundle`, and add it to an internal test in Google Play Console, then everything is smooth (signing works, the Google Play Console "real life" tests run without errors) until I try to install the app; here, I'm told that my devices are compatible (and indeed they show up as compatible on the very long list on Google Play Console), yet I'm told that "This app is not available for your device".

| | |
| --------------- | --------------- |
<img width="400" src="https://user-images.githubusercontent.com/6169306/191330938-421a8475-5b45-4cbe-8c52-bccda556e07c.png"> | <img width="400" src="https://user-images.githubusercontent.com/6169306/191330931-4eed5c13-5b86-4d6c-948b-964fb8b8dd20.png">

So, I can't really tell if this is a Flutter issue or a Google Play issue, but I figured I'd start here.

**Comment by huycozy** [comment]
Hi @fuglede 
I see that there are a few reasons for this issue that may need to check from your side (for eg: Device Incompatibility, Regional Restrictions, Outdated Android Version, Insufficient Storage Space, etc) so please check this article and see if there are some hints can help: https://www.makeuseof.com/tag/cant-download-certain-apps-play-store/

Go deeper with Flutter side, please try installing your output `aab` file (appbundle) into your device using [bundletool](https://developer.android.com/studio/command-line/bundletool) to see if there is an issue with that.

And please provide the information indicated below:
- Affected devices info (model, Android OS)
- The content of `android/app/build.gradle)
- The output of `flutter doctor -v`

Thank you!

**Comment by fuglede** [comment]
@huycozy Thanks for the reference. Everything on that list looks good (device has Android 11 and app requires 4.1, Google Play is configured to use the same region (Denmark) as for people for whom the app works, app requires 7 MB and I have 17 GB free, app requires no special features (and the only added permission is `android.permission.INTERNET`), I've cleared the Google Play cache a bunch of times).

Will try `bundletool` when I get the chance.

One thing that's curious is that if I access the internal test link through Chrome on Android, I get a completely different view in Play Store, and here, the app is listed as "not available", and the device as incompatible (the discrepancy from the other view is a Google Play bug on its own, I suppose):

![signal-2022-09-21-130922_002](https://user-images.githubusercontent.com/6169306/191489474-e650761e-eb24-446c-b4c0-96ce1b6b3bba.png)
![signal-2022-09-21-130922_003](https://user-images.githubusercontent.com/6169306/191489480-dae5c9f0-8b7e-4f31-b4e7-ee59f8a16ea2.png)

> Affected devices info (model, Android OS)

See models in OP; the phone is on Android 11.

> The content of `android/app/build.gradle`

```
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '7'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"
def keystoreProperties = new Properties()
def keystorePropertiesFile = rootProject.file('key.properties')
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}
android {
    compileSdkVersion flutter.compileSdkVersion
    ndkVersion flutter.ndkVersion

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        applicationId "dk.fuglede.electricity_prices"
        minSdkVersion flutter.minSdkVersion
        targetSdkVersion flutter.targetSdkVersion
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }

    signingConfigs {
        release {
            keyAlias keystoreProperties['keyAlias']
            keyPassword keystoreProperties['keyPassword']
            storeFile keystoreProperties['storeFile'] ? file(keystoreProperties['storeFile']) : null
            storePassword keystoreProperties['storePassword']
        }
    }
    buildTypes {
        release {
            signingConfig signingConfigs.release
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
}
```

> The output of `flutter doctor -v`

```
 flutter doctor -v
[✓] Flutter (Channel stable, 3.3.2, on Debian GNU/Linux bookworm/sid 5.19.0-1-amd64, locale en_US.UTF-8)
    • Flutter version 3.3.2 on channel stable at /home/sfj/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e3c29ec00c (7 days ago), 2022-09-14 08:46:55 -0500
    • Engine revision a4ff2c53d8
    • Dart version 2.18.1
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /home/sfj/Android/Sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /home/sfj/android/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Linux toolchain - develop for Linux desktop
    • Debian clang version 14.0.6-2
    • cmake version 3.24.1
    • ninja version 1.11.1
    • pkg-config version 0.29.2

[✓] Android Studio (version 2021.3)
    • Android Studio at /home/sfj/android
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.71.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.48.0

[✓] Connected device (1 available)
    • Linux (desktop) • linux • linux-x64 • Debian GNU/Linux bookworm/sid 5.19.0-1-amd64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

**Comment by fuglede** [comment]
> Go deeper with Flutter side, please try installing your output aab file (appbundle) into your device using [bundletool](https://developer.android.com/studio/command-line/bundletool) to see if there is an issue with that.

I tried

```
$ java -jar ~/bundletool-all-1.11.2.jar build-apks --bundle=build/app/outputs/bundle/release/app-release.aab --output=app.apks
$ java -jar ~/bundletool-all-1.11.2.jar install-apks --apks=app.apks --adb=~/Android/Sdk/platform-tools/adb --device-id PNX[...]
```

This makes the app available on the phone and it works as expected. I then tried removing the app and running the above again; and again, the app shows up and works as expected.

Is this what you had in mind?

**Comment by fuglede** [comment]
I managed to resolve the issue through this truly bizarre sequence of steps:

1. Create a new Google Play account (actually using this new account would be a showstopper, so we don't want to do that at the end of the day, but we'll get there).
2. Invite the new account to the internal test.
3. Log into the new account on the phone.
4. Access the internal test through one of the version-specific links, hidden somewhere in the depths of Google Play Console (e.g. https://play.google.com/apps/test/dk.fuglede.electricity_prices/5).
5. This time around there _is_ an install button. Clicking it, however, prompts me to verify my age. Click the link to verify my age.
6. This opens a browser which (since I used Google Play from the browser with my previous account) _importantly_ is logged into my old account.
7. Complete the verification (I used the credit card option which was particularly painful since most cards are debit cards around here).
8. Go back to Google Play and laugh at the fact that the new account still doesn't have it's age verified since we accidentally did it for the old account.
9. Switch account back to the old one.
10. Everything works now.

So, I suppose the issue was that the existing account didn't have its age verified, but a rather terrible bug in Google Play wouldn't ever tell me what the problem was, or allow me to do anything about it without creating a new account. So, I suppose this isn't Flutter-related at all.

**Comment by huycozy** [comment]
@fuglede Glad you solved it. 
Next time, you can also ask for help on channels like https://support.google.com/googleplay/community for issues related to Google Play.
Given your last message, I feel safe to close this issue, if you disagree please write in the comments and I will reopen it.
Thank you!

**Comment by fuglede** [comment]
Thanks, I'll keep that in mind if I run into similar issues another time!
