### ISSUE TITLE
[web] SweepGradient fidelity between CanvasKit and HTML renderers when applied to a stroke

### ISSUE THREAD

**Issue by cmkweber** [flutter/flutter#111993]
## Steps to Reproduce

SweepGradient shaders applied to a stroke are being clipped on web when using the html renderer.

**Observe the clipping on the Circle in the lower right:**

![Sweep](https://user-images.githubusercontent.com/45799422/191338693-8545c880-1a97-4e88-9402-478b173ed535.jpg)

<details>
<summary>Code sample</summary>

[DartPad](https://dartpad.dev/0ac5d9f703651907831ca4f62971d85a)

Sample must be built with HTML renderer and I don't see anyway to configure that in DartPad.
</details>

<details>
  <summary>Logs</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, 3.4.0-19.0.pre.347, on Microsoft Windows [Version 10.0.19043.1889], locale en-US)
This is taking an unexpectedly long time...[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0-rc2)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.2.3)
[√] Android Studio (version 3.6)
[√] VS Code, 64-bit edition (version 1.71.2)
[√] Connected device (3 available)
[√] HTTP Host Availability

• No issues found!
```
</details>

**Comment by danagbemava-nc** [comment]
Hi @cmkweber, there's an existing issue addressing this bug in https://github.com/flutter/flutter/issues/84328. 

Kindly follow up in the issue linked above for updates.

Closing from here as duplicate. 

Thank you
