### ISSUE TITLE
[go_router] ShellRoute should allow child ShellRoute instances

### ISSUE THREAD

**Issue by johnpryan** [flutter/flutter#111981]
In order to update the [navigation_and_routing sample](https://github.com/flutter/samples/issues/1436), we need to place a ShellRoute within another ShellRoute. The route config should be something like this (I took out the builders out for brevity):

```dart
    return MaterialApp.router(
      routerConfig: GoRouter(
        initialLocation: '/books/popular',
        routes: [
          ShellRoute(
            routes: [
              ShellRoute(
                navigatorKey: booksNavigatorKey,
                routes: [
                  GoRoute(
                    path: '/books/popular',
                    routes: [
                      GoRoute(
                        parentNavigatorKey: booksNavigatorKey,
                        path: 'book/:bookId',
                      ),
                    ],
                  ),
                  GoRoute(
                    path: '/books/new',
                    routes: /* ... */
                  ),
                  GoRoute(
                    path: '/books/all',
                    routes: /* ... */
                  ),
                ],
              ),
              GoRoute(
                path: '/authors',
              ),
              GoRoute(
                path: '/settings',
              ),
            ],
          ),
          GoRoute(
            path: '/signin',
          ),
        ],
      ),
    );
```

But the ShellRoute  constructor is [asserting](https://github.com/flutter/packages/blob/main/packages/go_router/lib/src/route.dart#L442) that it's children are instances of `GoRoute`, but conceptually it should be OK to place a ShellRoute within another, otherwise, there's no way to display a nested TabBar within a Scaffold with a BottomNavigationBar, for example:

<img width="612" alt="Screen Shot 2022-09-20 at 9 11 02 AM" src="https://user-images.githubusercontent.com/1145719/191309911-e2897e6f-7ce1-4057-bdd7-93ad3fef8132.png">

**Comment by parsa10** [comment]
I suppose this Issue is Duplicated : #111976

**Comment by parsa10** [comment]
#111967

**Comment by 70nybl4nc0** [comment]
Thanks this feature @johnpryan! I just found a related issue #112181
