### ISSUE TITLE
The splash screen phenomenon occurs when the webview sets the backgroundColor value to Colors.transparent

### ISSUE THREAD

**Issue by 1549742101** [flutter/flutter#111952]
When I use the webview_flutter component, setting the background color of the webview to a transparent color is no problem on most Android phones, but some models have a splash screen phenomenon, and the models that appear are:
1. PDA, Android version: 9.0, CPU: mt6761 4 core 2.0G
2. Redmi 4X (N2G47H), Android version: 7.1.2
3. SM-N960F (QP1A.190711.020), Android version: 10 (QP1A.190711.020.N960FXXU9FVG2)
recover code：
```
      WebView(
        initialUrl: url,
         backgroundColor: Colors.transparent,
     )
```

| error page | normal page |
| --------------- | --------------- |
<img width="300" src="https://user-images.githubusercontent.com/49146003/191220396-3ced3afa-1252-4992-8908-452ea0da096f.jpg"> | <img width="300" src="https://user-images.githubusercontent.com/49146003/191220433-58b98a09-447d-42ab-9543-6e0fe79a0cb2.jpg">

please help me,thanks

**Comment by 1549742101** [comment]
this project use get manage state,i want camera use in background

**Comment by huycozy** [comment]
Hi @1549742101, 
Which `webview_flutter` plugin version are you using?

>this project use get manage state,i want camera use in background

For the issue to be workable, it needs to be reproducible with a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code. Please provide such a sample. Also, please provide the output of `flutter doctor -v` as well.

Thank you!

**Comment by 1549742101** [comment]
Flutter assets will be downloaded from https://storage.flutter-io.cn/. Make sure you trust this source!
[√] Flutter (Channel stable, 3.0.5, on Microsoft Windows [版本 10.0.19044.2006], locale zh-CN)
    ? Flutter version 3.0.5 at D:\java\flutter
    ? Upstream repository https://github.com/flutter/flutter.git
    ? Framework revision f1875d570e (10 weeks ago), 2022-07-13 11:24:16 -0700
    ? Engine revision e85ea0e79c
    ? Dart version 2.17.6
    ? DevTools version 2.12.2
    ? Pub download mirror https://pub.flutter-io.cn/
    ? Flutter download mirror https://storage.flutter-io.cn/

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    ? Android SDK at D:\java\Android                                                                     
    ? Platform android-33, build-tools 33.0.0
    ? Java binary at: D:\Program\toolbox\apps\AndroidStudio\ch-0\213.7172.25.2113.9014738\jre\bin\java   
    ? Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    ? All Android licenses accepted.

[√] Chrome - develop for the web
    ? Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2021.2)
    ? Android Studio at D:\Program\toolbox\apps\AndroidStudio\ch-0\212.5712.43.2112.8815526
    ? Flutter plugin version 69.0.2
    ? Dart plugin version 212.5744
    ? Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] Android Studio (version 2021.3)
    ? Android Studio at D:\Program\toolbox\apps\AndroidStudio\ch-0\213.7172.25.2113.9014738
    ? Flutter plugin version 70.0.3
    ? Dart plugin version 213.7371
    ? Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[√] IntelliJ IDEA Ultimate Edition (version 2021.3)
    ? IntelliJ at D:\Program\toolbox\apps\IDEA-U\ch-0\213.7172.25
    ? Flutter plugin version 70.0.3
    ? Dart plugin version 213.7371

[√] IntelliJ IDEA Ultimate Edition (version 2022.2)
    ? IntelliJ at D:\Program\toolbox\apps\IDEA-U\ch-1\222.4167.29
    ? Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    ? Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] Connected device (3 available)
    ? 2201122C (mobile) ? cf2401ea ? android-arm64  ? Android 12 (API 31)
    ? Windows (desktop) ? windows  ? windows-x64    ? Microsoft Windows [版本 10.0.19044.2006]
    ? Chrome (web)      ? chrome   ? web-javascript ? Google Chrome 102.0.5005.63

[√] HTTP Host Availability
    ? All required HTTP hosts are available

! Doctor found issues in 1 category.

**Comment by 1549742101** [comment]
webview_flutter: ^3.0.4

**Comment by huycozy** [comment]
@1549742101 please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this

**Comment by 1549742101** [comment]
I found the reason, because of using the camera as the background and the web page using animation, the rendering engine of the old mobile phone can't keep up, I try to use other ways to avoid this problem, thank you

**Comment by huycozy** [comment]
@1549742101 Can you confirm that the original issue has been resolved? Or is the issue being solved by your own implementation?

**Comment by 1549742101** [comment]
I changed it to another way

**Comment by huycozy** [comment]
@1549742101 
I feel safe to close this issue now. Once you have this issue again, please provide information as we discussed above and write in the comments and I will reopen it. Thank you!
