### ISSUE TITLE
Inform developer when a character is used that has no glyph in the available fonts

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#112]
<a href="https://github.com/cpu-chromium"><img src="https://avatars.githubusercontent.com/u/12821707?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [cpu-chromium](https://github.com/cpu-chromium)**
_Tuesday Jul 21, 2015 at 20:03 GMT_
_Originally opened as https://github.com/flutter/engine/issues/189_

---

https://github.com/domokit/sky_engine/blob/master/sky/sdk/example/mine_digger/lib/main.dart

On Linux it shows the correct character, a flag; not so in android 
```dart
new StyledText(elements : [Game.textStyles[5], '\u2691'])
```
However, `u2600` works in android
```dart
new StyledText(elements : [Game.textStyles[3], '\u2600'])
```

This can be as simple as the default font not having that codepoint. In this case it would be good to have that pointed at develop time.

Note the text styles defined as:
```dart
textStyles.add(new TextStyle(color: const Color(0xFF555555), fontWeight: bold));
textStyles.add(new TextStyle(color: const Color(0xFF0094FF), fontWeight: bold));
textStyles.add(new TextStyle(color: const Color(0xFF13A023), fontWeight: bold));
textStyles.add(new TextStyle(color: const Color(0xFFDA1414), fontWeight: bold));
textStyles.add(new TextStyle(color: const Color(0xFF1E2347), fontWeight: bold));
textStyles.add(new TextStyle(color: const Color(0xFF7F0037), fontWeight: bold));
textStyles.add(new TextStyle(color: const Color(0xFFE93BE9), fontWeight: bold));
```

**Comment by FlutterIssues** [comment]
<a href="https://github.com/cpu-chromium"><img src="https://avatars.githubusercontent.com/u/12821707?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [cpu-chromium](https://github.com/cpu-chromium)**
_Tuesday Jul 21, 2015 at 20:14 GMT_

----

Chrome has the same behavior, showing 2600 but not 2691. Apparently stock android only has Roboto and Noto fonts. But an android app can embed ttf fonts, so this bug could mutate into providing font support outside these two fonts.

**Comment by FlutterIssues** [comment]
<a href="https://github.com/Hixie"><img src="https://avatars.githubusercontent.com/u/551196?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Hixie](https://github.com/Hixie)**
_Thursday Jul 23, 2015 at 01:00 GMT_

----

See #228 for general embedded font support.

**Comment by eseidelGoogle** [comment]
What is our current behavior?  Presumably we substitute a different font?

**Comment by tvolkert** [comment]
@jason-simmons does the switch to libtxt change the feasibility of this?

**Comment by dnfield** [comment]
I'm going to close this. We definitely support using different fonts now, and I don't believe we plan to add support for replacing missing characters from a font (Chrome doesn't do it either).
