### ISSUE TITLE
`ScrollBar` moves slower than the mouse when dragging it to scroll

### ISSUE THREAD

**Issue by knopp** [flutter/flutter#112072]
This one is bit different from https://github.com/flutter/flutter/issues/111968. It happens with current main in cases where `SliverList` items extents keep increasing.

Main reason for this is that `ScrollBar._updateScrollPosition` adjusts viewport position by using relative scroll offset. In pathological cases like this the error keeps increasing to the point where not even overdrag is enough to reach end.

I'm wondering why ScrollBar is written like that. Setting `pixels` to `minExtent + (absoluteScrollPosition * (maxExtent - minExtent))` would alleviate this (`absoluteScrollPosition` being in range of 0.0-1.0). But I'm not sure how this would work with overdrag.

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MaterialApp(
    title: 'Flutter Demo',
    home: MyHomePage(),
  ));
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  void initState() {
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: CustomScrollView(
        slivers: [
          SliverToBoxAdapter(
            child: Container(
              height: 2,
              color: Colors.red,
            ),
          ),
          SliverList(
            delegate: SliverChildBuilderDelegate(
              (context, index) => Padding(
                padding: const EdgeInsets.all(10),
                child: Container(
                  color: Colors.green,
                  height: index.toDouble(),
                ),
              ),
              childCount: 1000,
            ),
          ),
          SliverToBoxAdapter(
            child: Container(
              height: 2,
              color: Colors.red,
            ),
          ),
        ],
      ),
    );
  }
}
```

**Comment by knopp** [comment]
cc @Piinks, @TahaTesser

**Comment by exaby73** [comment]
Hello @knopp. I cannot reproduce this issue. When scrolling multiple times, I am still able to see the red lines. Could you please provide some more details? How do I reliably reproduce this issue and which version and/or platform is this reproducible for you? Thank you.

**Comment by knopp** [comment]
> Hello @knopp. I cannot reproduce this issue. When scrolling multiple times, I am still able to see the red lines. Could you please provide some more details? How do I reliably reproduce this issue and which version and/or platform is this reproducible for you? Thank you.

Can you maximize window and retry? You should see that the scrollbar is getting further away from mouse cursor as you scroll down. If there is no space below the window you don't be able to reach the end.

**Comment by exaby73** [comment]
Right I noticed that behavior. I have to reset my mouse multiple times to scroll fully. Posting a full triage report in a few minutes. Thanks for the information :)

**Comment by xu-baolin** [comment]
Actually, this is a performance issue of Flutter, when dragging the bar, building the sliver items will take a lot of time and cause frame loss.

Workaround,
set `CustomScrollView.cacheExtent` to `double.maxFinite` can work as you want.

CC @Piinks

**Comment by knopp** [comment]
> Actually, this is a performance issue of Flutter, when dragging the bar, building the sliver items will take a lot of time and cause frame loss.
> 
> Workaround, set `CustomScrollView.cacheExtent` to `double.maxFinite` can work as you want.
> 
> CC @Piinks

That will cause Flutter to eagerly build and layout entire content of the SliverList. Currently SliverList has a problem that in order to scroll through it it needs to build and layout all items regardless of whether they are displayed, but this is not a solution. It's also a separate issue.

**Comment by Piinks** [comment]
I don't think this is a scrollbar issue, it is likely more to do with the fact that when the children of the list have variable extents (like in the sample code above), Flutter estimates what the maximum extent is, and updates it as the list grows and it has more information to inform that estimate.

For this issue, it sounds like the scrollbar should perform some version of edge scrolling, where dragging it at the edge when it has not reached the end triggers the scroll position forward.
Or, the way we estimate the maximum scroll offset could be updated/changed/modified to allow the user to configure.

If the later, this is the issue to follow: https://github.com/flutter/flutter/issues/97676

**Comment by knopp** [comment]
In my opinion the primary issue is that scroll position update is always relative. So the relative scrollbar movement gets translated according to *current* scroll extent estimation and added to scroll position. But scroll extent estimation, especially at the very beginning, is (or at least should be) much worse than towards the end. But with current approach this is never really corrected.

I've been playing with scrollbars a bit and I had much better experience when settings scroll position directly to `pixels` = `minExtent + absoluteScrollPosition * (maxExtent - minExtent)`. That's because the further you scroll, the more accurate extent estimation would be. 

So for example towards the end, when you are at 95%, doing layout for `pixels = minExtent + 0.95 * (maxExtent - minExtent)` will probably update geometry with a decently accurate `maxExtent`. 

Repeat this couple of times (96, 97, 98, 99%) and the maxExtent should be very close to actual value.

After that, scrolling towards the very end, at `pixels = minExtent + 1.0 * (maxExtent - minExtent)`, you should end at the end of viewport. Without (or with minimal) edge scrolling.
