### ISSUE TITLE
Strange analyzer error: undefined field believed to belong to a private Flutter sdk class

### ISSUE THREAD

**Issue by DaveShuckerow** [flutter/flutter#11202]
I have the following code, which references a field called 'controller' but does not define it.  This naturally crashes at runtime.  However, the analyzer isn't picking up that this field is undefined.

```dart
class SearchFieldState extends State<SearchField> {
  FocusNode _focusNode;
  FocusNode get _effectiveFocusNode =>
      widget.focusNode ?? (_focusNode ??= new FocusNode());

  @override
  Widget build(BuildContext context) {
    final TextStyle style = widget.style ?? Theme.of(context).textTheme.subhead;
    Widget child = new Text('empty', style: style);
    if (widget.decoration != null) {
      child = new AnimatedBuilder(
        animation:
            new Listenable.merge(<Listenable>[_effectiveFocusNode, controller]),
        builder: (BuildContext context, Widget child) {
          return new InputDecorator(
            decoration: widget.decoration,
            baseStyle: widget.style,
            textAlign: widget.textAlign,
            isFocused: _effectiveFocusNode.hasFocus,
            isEmpty: widget.text.isEmpty,
            child: child,
          );
        },
        child: child,
      );
    }
    return new GestureDetector(child: child);
  }
}

```

I'm using external Flutter tools, and this occurs in both IntelliJ and Atom.

When I press ctrl+B to go to the source of the 'controller' field, it links to this: https://github.com/flutter/flutter/blob/c55097da7d0d3b0165c5988ff7adb3eaed614a61/packages/flutter/lib/src/material/bottom_navigation_bar.dart#L469

**Comment by DaveShuckerow** [comment]
I realize this might not be a Flutter-specific issue, but I'm unaware of where best to report an analyzer bug like this.  I'm happy to move this discussion to a more appropriate repo if need be.

**Comment by eseidelGoogle** [comment]
@devoncarew is a good person to ask if this is the right place for this.

**Comment by devoncarew** [comment]
This is likely an issue for the sdk repo (https://github.com/dart-lang/sdk). Do you mind creating a mini-repro for this (likely a repo that we could clone)? The `controller` field linked to is in a private class (`_Circle`), so should not be visible outside the library.

**Comment by DaveShuckerow** [comment]
The code that produced this error is at this commit:
https://github.com/DaveShuckerow/flap/blob/bd1dcdf5780c767099f413a59f4951ad8f464961/widgets/lib/src/search/search_field.dart#L25

**Comment by Hixie** [comment]
@DaveShuckerow @devoncarew I'm going to close this issue since it doesn't sound Flutter-specific, please make sure you've filed bugs in the appropriate repos to track this. Thanks!
