### ISSUE TITLE
InputDecorator should change the default text style to match the TextField style

### ISSUE THREAD

**Issue by DaveShuckerow** [flutter/flutter#11201]
Currently, with the style unchanged, the style is a body style.  TextFields have a default style of textTheme.subhead.

InputDecorator should match this, so that when I do the following

```dart
new InputDecorator(
  decoration: const InputDecoration(),
  child: new Text('I look like a text field!'),
);
```

the widget would look exactly like the a TextField with the same contents.

**Comment by Hixie** [comment]
cc @HansMuller

**Comment by YeungKC** [comment]
I think maybe it shouldn't be done, the api doc for InputDecorator describes: 
  
> InputDecorator displays the visual elements of a Material Design text field around its input child. The visual elements 
themselves are defined by an InputDecoration object and their layout and appearance depend on the baseStyle, textAlign, 
isFocused, and isEmpty parameters.

cc @Hixie @DaveShuckerow @justinmc

**Comment by justinmc** [comment]
Yeah I think this issue may be irrelevant nowadays.  I'm ok to close this if no one else objects.
