### ISSUE TITLE
Does Flutter 3 not support https self-signed certificates?

### ISSUE THREAD

**Issue by kenanwangyi** [flutter/flutter#112052]
I can use self-signed certificates for network requests in the development environment of flutter 2.5.3, but after upgrading to flutter 3, it will report an error:

HandshakeException: Handshake error in client (OS Error:
       UNSUPPORTED_PROTOCOL(handshake_client.cc:697))

Does Flutter3 not support https self-signed certificates? Or how to set it up?

**Comment by exaby73** [comment]
Hello @kenanwangyi. Thank you for filing this issue. Can you please provide the following information?

- A [complete and minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).
- The output of `flutter doctor -v`
- The output of `flutter run-v`

**Comment by kenanwangyi** [comment]
Hello

I use HttpClient to make network requests, the code is as follows, our server uses a self-signed certificate https, which belongs to the internal network address and cannot be accessed from the external network temporarily.When I initiate a network request, it prompts  'HandshakeException: Handshake error in client (OS Error:
UNSUPPORTED_PROTOCOL(handshake_client.cc:697))' .

Does Flutter 3 not support https self-signed certificates? Or how to set it up?

`try {
      HttpClient httpClient = new HttpClient();
      httpClient.badCertificateCallback =
          (X509Certificate cert, String host, int port) {
        return true;
      };
      var url = "https://api-dev.yeedev.com/oauth/token";
      HttpClientRequest request = await httpClient.postUrl(Uri.parse(url));
      HttpClientResponse response = await request.close();
      String responseBody = await response.transform(utf8.decoder).join();
      if (response.statusCode == HttpStatus.ok) {
        print('success');
        print(response.headers);
        print(responseBody);
      }
    } catch (e) {
      print("fail：$e");
    }
  }`







1. **flutter doctor -v**

[!] Flutter (Channel unknown, 3.3.0, on macOS 12.6 21G115 darwin-x64, locale zh-Hans-CN)
    ! Flutter version 3.3.0 on channel unknown at /Users/fudong/fvm/versions/3.3.0
    ! Upstream repository unknown
    • Framework revision ffccd96b62 (3 weeks ago), 2022-08-29 17:28:57 -0700
    • Engine revision 5e9e0e0aa8
    • Dart version 2.18.0
    • DevTools version 2.15.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/fudong/Library/Android/sdk
    • Platform android-32, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F17a
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.71.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.6 21G115 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 93.0.4577.63

HTTP Host availability check is taking a long time...[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.



2.  **flutter run -v** (part of the content)
[ +228 ms] success
[        ] Application launched on the device. Waiting for observatory url.
[+3599 ms] [VERBOSE-2:FlutterObservatoryPublisher.mm(101)] Failed to register observatory port with mDNS with
error -65555.
[        ] [VERBOSE-2:FlutterObservatoryPublisher.mm(103)] On iOS 14+, local network broadcast in apps need to
be declared in the app's Info.plist. Debug and profile Flutter apps and modules host VM services on the local
network to support debugging features such as hot reload and DevTools. To make your Flutter app or module
attachable and debuggable, add a '_dartobservatory._tcp' value to the 'NSBonjourServices' key in your
Info.plist for the Debug/Profile configurations. For more information, see
https://flutter.dev/docs/development/add-to-app/ios/project-setup#local-network-privacy-permissions
[   +1 ms] Observatory URL on device: http://127.0.0.1:60045/
[   +8 ms] Attempting to forward device port 60045 to host port 62185
[        ] executing: /Users/fudong/fvm/versions/3.3.0/bin/cache/artifacts/usbmuxd/iproxy 62185:60045 --udid
1f3c8472cde01fe391647650af39cf2268bf37d5 --debug
[+1011 ms] Forwarded port ForwardedPort HOST:62185 to DEVICE:60045
[        ] Forwarded host port 62185 to device port 60045 for Observatory
[   +3 ms] Installing and launching... (completed in 16.8s)
[   +2 ms] Caching compiled dill
[  +76 ms] Connecting to service protocol: http://127.0.0.1:62185/
[ +214 ms] Launching a Dart Developer Service (DDS) instance at http://127.0.0.1:0, connecting to VM service
at http://127.0.0.1:62185/.
[ +107 ms] DDS is listening at http://127.0.0.1:62193/GtVvHuBLxVM=/.
[   +1 ms] [VERBOSE-2:FlutterObservatoryPublisher.mm(101)] Failed to register observatory port with mDNS with
error -65555.
[        ] [VERBOSE-2:FlutterObservatoryPublisher.mm(103)] On iOS 14+, local network broadcast in apps need to
be declared in the app's Info.plist. Debug and profile Flutter apps and modules host VM services on the local
network to support debugging features such as hot reload and DevTools. To make your Flutter app or module
attachable and debuggable, add a '_dartobservatory._tcp' value to the 'NSBonjourServices' key in your
Info.plist for the Debug/Profile configurations. For more information, see
https://flutter.dev/docs/development/add-to-app/ios/project-setup#local-network-privacy-permissions
[  +60 ms] Successfully connected to service protocol: http://127.0.0.1:62185/
[  +28 ms] DevFS: Creating new filesystem on the device (null)
[  +21 ms] DevFS: Created new filesystem on the device
(file:///private/var/mobile/Containers/Data/Application/FE59A625-07BE-4907-82D2-BCB4C3F2B00C/tmp/flutter_appcL
fQ9l/flutter_app/)
[   +2 ms] Updating assets
[ +236 ms] Syncing files to device Fu iPhone...
[   +1 ms] Compiling dart to kernel with 0 updated files
[        ] Processing bundle.
[   +1 ms] <- recompile package:flutter_app/main.dart a4c4349d-2db2-4d1d-9238-4a14ce9b6d6e
[        ] <- a4c4349d-2db2-4d1d-9238-4a14ce9b6d6e
[   +2 ms] Bundle processing done.
[ +153 ms] Updating files.
[        ] DevFS: Sync finished
[   +1 ms] Syncing files to device Fu iPhone... (completed in 159ms)
[        ] Synced 0.0MB.
[   +1 ms] <- accept
[   +3 ms] Connected to _flutterView/0x11883b020.
[   +3 ms] Flutter run key commands.
[   +1 ms] r Hot reload. 🔥🔥🔥
[        ] R Hot restart.
[        ] h List all available interactive commands.
[        ] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[        ] q Quit (terminate the application on the device).
[        ] Running with unsound null safety
[        ] For more information see https://dart.dev/null-safety/unsound-null-safety
[        ] An Observatory debugger and profiler on Fu iPhone is available at:
http://127.0.0.1:62193/GtVvHuBLxVM=/
[        ] The Flutter DevTools debugger and profiler on Fu iPhone is available at:
           http://127.0.0.1:9103?uri=http://127.0.0.1:62193/GtVvHuBLxVM=/
[+8776 ms] flutter: 请求失败：HandshakeException: Handshake error in client (OS Error: 
[        ] 	UNSUPPORTED_PROTOCOL(handshake_client.cc:697))

**Comment by exaby73** [comment]
Labelling for further insights from the team.

**Comment by Hixie** [comment]
Transferred to Dart: https://github.com/dart-lang/sdk/issues/53159
