### ISSUE TITLE
Auto submit bot should validate PR mergeable status based on up-to-date PR info

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#112018]
One validation from auto submit bot is check PR mergeable status. Based on https://docs.github.com/en/rest/pulls/pulls#get-a-pull-request
```
The value of the mergeable attribute can be true, false, or null. If the value is null, then GitHub has started a background job to compute the mergeability. After giving the job time to complete, resubmit the request. When the job finishes, you will see a non-null value for the mergeable attribute in the response. If mergeable is true, then merge_commit_sha will be the SHA of the test merge commit.
```
The initial PR info sent out via webhook may not have the mergeable status correctly. And the auto submit bot should use latest `mergeable` status when validating.

Code: https://github.com/flutter/cocoon/blob/main/auto_submit/lib/validations/conflicting.dart#L20
Context: https://github.com/flutter/engine/pull/36301

**Comment by ricardoamador** [comment]
I was mistaken. There is a check for mergeable in the backend but not in autosubmit. I will get this implemented.

**Comment by keyonghan** [comment]
Thanks @ricardoamador !
