### ISSUE TITLE
flutter run should not sign iOS apps with Mac certificates

### ISSUE THREAD

**Issue by collinjackson** [flutter/flutter#11200]
## Steps to Reproduce

Connect iOS device and flutter run.

```
Multiple valid development certificates available (your choice will be saved):
  1) Mac Developer: jackson@google.com (7DGS4ZGNBJ)
  2) iPhone Developer: Google Development (3F4Y5873JF)
  3) iPhone Developer: Alex Jackson (5SXPVWLENR)
  a) Abort
Please select a certificate for code signing [1|2|3|a]: 2
```

I think it should have defaulted to an iPhone Developer certificate and not shown me the Mac developer one, since I'm building for iOS.

(Why I have a developer certificate for Alex Jackson is a long story.)

## flutter doctor
```
[✓] Flutter (on Mac OS X 10.12.5 16F73, locale en-US, channel unknown)
    • Flutter at /Users/jackson/git/flutter
    • Framework revision 4d6298d486 (3 days ago), 2017-07-10 04:18:44 -0700
    • Engine revision 8ad1576f27
    • Tools Dart version 1.25.0-dev.4.0

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.0)
    • Android SDK at /Users/jackson/Library/Android/sdk/
    • Platform android-26, build-tools 26.0.0
    • ANDROID_HOME = /Users/jackson/Library/Android/sdk/
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.3.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3.3, Build version 8E3004b
    • ios-deploy 1.9.1
    • CocoaPods version 1.2.1

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.1.4)
    • Flutter plugin version 15.0
    • Dart plugin version 171.4694.29

[✓] Connected devices
    • Jacksonphone • 9030c4fbeb16a1981b3e685fbf21521d79ed6ac1 • ios • iOS 10.3.2
```

**Comment by Hixie** [comment]
cc @xster

**Comment by xster** [comment]
Note to future self: it doesn't seem like `security find-identity` has a category for target types. It'll have to be a manual name filter.

**Comment by Svoka** [comment]
And what if i build for mac?

**Comment by xster** [comment]
Right, the intent of the bug is to show macos certificates when building for macos and ios certificates when building for ios.

**Comment by christopherfujino** [comment]
I'm a little uncomfortable with filtering these results based on a regex, as this would be prone to break with any new Xcode release (see https://github.com/flutter/flutter/pull/37733/files). But admittedly, the current experience is very confusing ux-wise.

**Comment by jmagman** [comment]
`Apple Developer` for all platforms is the type to use in Xcode 11 and later, though you can still generate the other types.  This problem will mostly go away.
![Screen Shot 2020-12-10 at 6 16 59 PM](https://user-images.githubusercontent.com/682784/101853080-e659e300-3b13-11eb-8f04-85ff8e204832.png)
 is the norm now, this problem

**Comment by bkonyi** [comment]
Since there's been a way to create `Apple Development` signing keys for a few years now, I'm going to assume this isn't worth investing time in.
