### ISSUE TITLE
M3 Demo app: Make whole body scrollable

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#112000]
When visiting https://flutter-experimental-m3-demo.web.app/#/ currently you can only scroll the components via trackpad or mouse wheel when the mouse pointer is hovering over the small section of components in the middle. I think the scrollview should extend to include the entire body of the application so you can scroll the body when the mouse pointer is anywhere within the body. This would also display the scrollbars at the right edge of the screen (where it is expected) instead of at the middle.

![image](https://user-images.githubusercontent.com/1227763/191358030-3da2a70d-8e28-460b-8e34-34f8c0d1016d.png)

/cc @QuncCccccc @darrenaustin

**Comment by darrenaustin** [comment]
In addition to this, as we have already discussed, we should adapt this layout to multi-column when the display is wide enough to that there isn't so much dead space in the first place.
