### ISSUE TITLE
firebase_database multi-location updates

### ISSUE THREAD

**Issue by dac3971** [flutter/flutter#11205]
I only see a set method in the firebase_database package.  Is there a way to write atomic multi-location updates in Flutter?

**Comment by lschmierer** [comment]
Thats what you are looking for, I guess: https://github.com/flutter/plugins/pull/152

**Comment by dac3971** [comment]
@lschmierer that looks like what I'm looking for.  Forgive me, but I'm a new user - how do I go about writing this update command in my Flutter app?  Is it not in the latest firebase-database version?

**Comment by lschmierer** [comment]
https://github.com/flutter/plugins/pull/152 uis merged so will be in next release

**Comment by dac3971** [comment]
Thanks!
