### ISSUE TITLE
Switch thumb radius decreases by 1 px when it moves to the middle.

### ISSUE THREAD

**Issue by QuncCccccc** [flutter/flutter#112026]
The thumb radius in Material 2 Switch decreases a little when it moves to the middle of the track. But in Material 3, the thumb radius should stay the same.

Expected:
https://user-images.githubusercontent.com/36861262/191396770-b8fc0267-dfdf-4460-b885-051b085346cf.MP4
<img width="96" alt="Screen Shot 2022-09-20 at 7 06 50 PM" src="https://user-images.githubusercontent.com/36861262/191398098-98376eb9-7b59-48bc-9a54-fc166e483858.png">

Actual:
https://user-images.githubusercontent.com/36861262/191396754-6523ac57-d9e5-4b85-a858-9cc77f2f21c3.MP4
<img width="87" alt="Screen Shot 2022-09-20 at 7 06 14 PM" src="https://user-images.githubusercontent.com/36861262/191398112-3e2a5264-cd07-4455-a3cb-1452b82cf620.png">

**Comment by MaxYablochkin** [comment]
> The thumb radius in Material 2 Switch decreases a little when it moves to the middle of the track. But in Material 3, the thumb radius should stay the same.
> 
> Expected:
> https://user-images.githubusercontent.com/36861262/191396770-b8fc0267-dfdf-4460-b885-051b085346cf.MP4
> <img width="96" alt="Screen Shot 2022-09-20 at 7 06 50 PM" src="https://user-images.githubusercontent.com/36861262/191398098-98376eb9-7b59-48bc-9a54-fc166e483858.png">
> 
> 
> Actual:
> https://user-images.githubusercontent.com/36861262/191396754-6523ac57-d9e5-4b85-a858-9cc77f2f21c3.MP4
> <img width="87" alt="Screen Shot 2022-09-20 at 7 06 14 PM" src="https://user-images.githubusercontent.com/36861262/191398112-3e2a5264-cd07-4455-a3cb-1452b82cf620.png">
> 
> 
> 

Thanks

**Comment by MaxYablochkin** [comment]
> > The thumb radius in Material 2 Switch decreases a little when it moves to the middle of the track. But in Material 3, the thumb radius should stay the same.
> > 
> > Expected:
> > https://user-images.githubusercontent.com/36861262/191396770-b8fc0267-dfdf-4460-b885-051b085346cf.MP4
> > <img width="96" alt="Screen Shot 2022-09-20 at 7 06 50 PM" src="https://user-images.githubusercontent.com/36861262/191398098-98376eb9-7b59-48bc-9a54-fc166e483858.png">
> > 
> > 
> > Actual:
> > https://user-images.githubusercontent.com/36861262/191396754-6523ac57-d9e5-4b85-a858-9cc77f2f21c3.MP4
> > <img width="87" alt="Screen Shot 2022-09-20 at 7 06 14 PM" src="https://user-images.githubusercontent.com/36861262/191398112-3e2a5264-cd07-4455-a3cb-1452b82cf620.png">
> > 
> > 
> > 
> 
> Thanks 

🇺🇦

**Comment by huycozy** [comment]
Hi @QuncCccccc, thanks for filing the issue. This issue is reproducible on the latest `stable` and `master` channels.

<details>
<summary>Demo</summary>

https://user-images.githubusercontent.com/104349824/191494035-0a064313-a5f6-4346-8a4b-e5c7575d99fc.mov

</details>

<details>
<summary>Sample code</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        useMaterial3: true,
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: Scaffold(
        body: Container(
          alignment: Alignment.center,
          child: Switch(
            thumbColor: MaterialStateProperty.all(Colors.amber),
            inactiveTrackColor: Colors.blueGrey,
            value: false,
            onChanged: (value) {},
          ),
        ),
      ),
    );
  }
}
```
</details>

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 3.3.2, on macOS 12.6 21G115 darwin-x64, locale en-VN)
    • Flutter version 3.3.2 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e3c29ec00c (6 days ago), 2022-09-14 08:46:55 -0500
    • Engine revision a4ff2c53d8
    • Dart version 2.18.1
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13E113
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.71.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.6 21G115 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 105.0.5195.125

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

```bash
[✓] Flutter (Channel master, 3.4.0-19.0.pre.406, on macOS 12.6 21G115 darwin-x64, locale en-VN)
    • Flutter version 3.4.0-19.0.pre.406 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d98b0c9c7c (30 minutes ago), 2022-09-20 23:35:24 -0400
    • Engine revision 38fef0572f
    • Dart version 2.19.0 (build 2.19.0-223.0.dev)
    • DevTools version 2.17.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A309
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.71.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (3 available)
    • Pixel 3a (mobile) • 964AY0WL20 • android-arm64  • Android 12 (API 32)
    • macOS (desktop)   • macos      • darwin-x64     • macOS 12.6 21G115 darwin-x64
    • Chrome (web)      • chrome     • web-javascript • Google Chrome 105.0.5195.125

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```
</details>

**Comment by MaxYablochkin** [comment]
> Hi @QuncCccccc, thanks for filing the issue. This issue is reproducible on the latest `stable` and `master` channels.
> 
> <details>
> <summary>Demo</summary>
> 
> https://user-images.githubusercontent.com/104349824/191494035-0a064313-a5f6-4346-8a4b-e5c7575d99fc.mov
> 
> </details>
> 
> <details>
> <summary>Sample code</summary>
> 
> ```dart
> import 'package:flutter/material.dart';
> 
> void main() {
>   runApp(const MyApp());
> }
> 
> class MyApp extends StatelessWidget {
>   const MyApp({Key? key}) : super(key: key);
> 
>   @override
>   Widget build(BuildContext context) {
>     return MaterialApp(
>       title: 'Flutter Demo',
>       theme: ThemeData(
>         useMaterial3: true,
>         primarySwatch: Colors.blue,
>         visualDensity: VisualDensity.adaptivePlatformDensity,
>       ),
>       home: Scaffold(
>         body: Container(
>           alignment: Alignment.center,
>           child: Switch(
>             thumbColor: MaterialStateProperty.all(Colors.amber),
>             inactiveTrackColor: Colors.blueGrey,
>             value: false,
>             onChanged: (value) {},
>           ),
>         ),
>       ),
>     );
>   }
> }
> ```
> </details>
> 
> <details>
> <summary>flutter doctor -v</summary>
> 
> ```bash
> [✓] Flutter (Channel stable, 3.3.2, on macOS 12.6 21G115 darwin-x64, locale en-VN)
>     • Flutter version 3.3.2 on channel stable at /Users/huynq/Documents/GitHub/flutter
>     • Upstream repository https://github.com/flutter/flutter.git
>     • Framework revision e3c29ec00c (6 days ago), 2022-09-14 08:46:55 -0500
>     • Engine revision a4ff2c53d8
>     • Dart version 2.18.1
>     • DevTools version 2.15.0
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
>     • Android SDK at /Users/huynq/Library/Android/sdk
>     • Platform android-33, build-tools 31.0.0
>     • ANDROID_HOME = /Users/huynq/Library/Android/sdk
>     • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
>     • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
>     • All Android licenses accepted.
> 
> [✓] Xcode - develop for iOS and macOS (Xcode 13.3)
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • Build 13E113
>     • CocoaPods version 1.11.3
> 
> [✓] Chrome - develop for the web
>     • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
> 
> [✓] Android Studio (version 2021.2)
>     • Android Studio at /Applications/Android Studio.app/Contents
>     • Flutter plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/9212-flutter
>     • Dart plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/6351-dart
>     • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
> 
> [✓] IntelliJ IDEA Community Edition (version 2022.1.1)
>     • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
>     • Flutter plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/9212-flutter
>     • Dart plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/6351-dart
> 
> [✓] VS Code (version 1.71.2)
>     • VS Code at /Applications/Visual Studio Code.app/Contents
>     • Flutter extension version 3.48.0
> 
> [✓] Connected device (2 available)
>     • macOS (desktop) • macos  • darwin-x64     • macOS 12.6 21G115 darwin-x64
>     • Chrome (web)    • chrome • web-javascript • Google Chrome 105.0.5195.125
> 
> [✓] HTTP Host Availability
>     • All required HTTP hosts are available
> 
> • No issues found!
> 
> ```
> 
> ```bash
> [✓] Flutter (Channel master, 3.4.0-19.0.pre.406, on macOS 12.6 21G115 darwin-x64, locale en-VN)
>     • Flutter version 3.4.0-19.0.pre.406 on channel master at /Users/huynq/Documents/GitHub/flutter_master
>     • Upstream repository https://github.com/flutter/flutter.git
>     • Framework revision d98b0c9c7c (30 minutes ago), 2022-09-20 23:35:24 -0400
>     • Engine revision 38fef0572f
>     • Dart version 2.19.0 (build 2.19.0-223.0.dev)
>     • DevTools version 2.17.0
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
>     • Android SDK at /Users/huynq/Library/Android/sdk
>     • Platform android-33, build-tools 31.0.0
>     • ANDROID_HOME = /Users/huynq/Library/Android/sdk
>     • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
>     • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
>     • All Android licenses accepted.
> 
> [✓] Xcode - develop for iOS and macOS (Xcode 14.0)
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • Build 14A309
>     • CocoaPods version 1.11.3
> 
> [✓] Chrome - develop for the web
>     • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
> 
> [✓] Android Studio (version 2021.2)
>     • Android Studio at /Applications/Android Studio.app/Contents
>     • Flutter plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/9212-flutter
>     • Dart plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/6351-dart
>     • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
> 
> [✓] IntelliJ IDEA Community Edition (version 2022.1.1)
>     • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
>     • Flutter plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/9212-flutter
>     • Dart plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/6351-dart
> 
> [✓] VS Code (version 1.71.2)
>     • VS Code at /Applications/Visual Studio Code.app/Contents
>     • Flutter extension version 3.48.0
> 
> [✓] Connected device (3 available)
>     • Pixel 3a (mobile) • 964AY0WL20 • android-arm64  • Android 12 (API 32)
>     • macOS (desktop)   • macos      • darwin-x64     • macOS 12.6 21G115 darwin-x64
>     • Chrome (web)      • chrome     • web-javascript • Google Chrome 105.0.5195.125
> 
> [✓] HTTP Host Availability
>     • All required HTTP hosts are available
> 
> • No issues found!
> 
> ```
> </details>

@huycozy 
The beginning of the discussion of this problem is indicated in this comment👇

https://github.com/flutter/flutter/issues/103536#issuecomment-1253030219
