### ISSUE TITLE
Update builders to macOS Monterey 12.5 to run release Xcode 14

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#112007]
> Xcode 14 requires a Mac running macOS Monterey 12.5 or later.

https://developer.apple.com/documentation/xcode-release-notes/xcode-14-release-notes

14.1 will also require 12.5.
https://developer.apple.com/documentation/xcode-release-notes/xcode-14_1-release-notes

macOS Ventura has not yet released.

**Comment by yusuf-goog** [comment]
@jmagman I will put in a request to upgrade a couple VMs to 12.5 as a initial test. Once they are validated, we can go ahead and upgrade the rest of the fleet.

**Comment by yusuf-goog** [comment]
@jmagman would it be ok to go to 12.6? This would make some of the logistics much easier.

**Comment by yusuf-goog** [comment]
@jmagman confirmed offline that 12.6 is acceptable.

**Comment by yusuf-goog** [comment]
Upgraded mac-4 to macOS 12.6

**Comment by yusuf-goog** [comment]
build270-m9	also upgraded to 12.6

**Comment by godofredoc** [comment]
@yusuf-goog is this complete now?

**Comment by yusuf-goog** [comment]
macOS 12.6 is deployed across the fleet.
