### ISSUE TITLE
Xcode warning: Run script build phase 'Run Script' will be run during every build because it does not specify any outputs

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#112015]
iOS version at https://github.com/flutter/flutter/issues/108321 fixed with https://github.com/flutter/flutter/pull/108331

New warnings in Xcode 14 beta 3 on a new `flutter create` project:

```
$ flutter build macos
Running "flutter pub get" in test_create...                        467ms
...

warning: Run script build phase 'Run Script' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'Flutter Assemble' from project 'Runner')
Building macOS application...
```

<img width="448" alt="Screen Shot 2022-07-25 at 2 31 00 PM" src="https://user-images.githubusercontent.com/682784/180877587-77e79c21-4ef4-4463-af0d-8fb5e72c81eb.png">

Unchecking adds:
```diff
		9740EEB61CF901F6004384FC /* Run Script */ = {
			isa = PBXShellScriptBuildPhase;
+			alwaysOutOfDate = 1;
			buildActionMask = 2147483647;
```

Xcode isn't handling input/output, `flutter` is, so it is correct to be unchecked.

This is happening on macOS (only `Runner` target, not `Flutter Assemble`, which is using inputs/outputs so the option should be checked).

Update templates and add a migration.  Note this check box exists on Xcode 13 so we don't need to increase the minimum version to 14 before doing this.

**Comment by jmagman** [comment]
cc @cbracken

**Comment by omarzl** [comment]
We had the same warning using custom script phases so we did the same change: `alwaysOutOfDate = 1;`
Now we don't have a warning, instead we have a note:
```
note: Run script build phase 'XX' will be run during every build because the option to run the script phase "Based on dependency analysis" is unchecked
```
Still quite annoying 🙁

**Comment by jmagman** [comment]
I forgot I already did the `macos_assemble.sh embed` migration in July as part of https://github.com/flutter/flutter/pull/108331.  It's the `Run Script` that's complaining, which doesn't make any sense because it does specify an output so that should be checked.

<img width="646" alt="Screen Shot 2022-09-23 at 4 33 52 PM" src="https://user-images.githubusercontent.com/682784/192069514-2ce7beb4-941f-4ebe-8ee5-7ebc84349b75.png">

Is this an Xcode bug where it's not counting the output xcfilelist?

**Comment by jmagman** [comment]
@omarzl  if you set `alwaysOutOfDate = 1;` on the assemble `Run Script` you should remove that, that Flutter script phase is doing proper dependency analysis with inputs and outputs.

In a Flutter macOS project I can't get the warning to even show up after deleting DerivedData.  I don't think there's anything to be done here.
