### ISSUE TITLE
reland fxbug.dev/94000: Set Opacity and Scale Flatland Values for Flatland Embedder

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#112014]
The PR https://github.com/flutter/engine/pull/36109 had to be reverted because it broke fuchsia tests.  Please reland it with the broken test fixed.

The broken test: https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20Fuchsia%20FEMU/11891/overview
The revert: https://github.com/flutter/engine/pull/36305

**Comment by gaaclarke** [comment]
Looking at the build dashboard, this PR may not have caused the failure, but it was a flake introduced earlier today and it got unlucky in post commit tests.  The first time it showed up was https://github.com/flutter/engine/commit/7b73e53b4a15b59590db13fc80933517b65ab08b.

**Comment by chinmaygarde** [comment]
@akbiggs Not sure if @cfontas is the right assignee. Can we reland this?

**Comment by akbiggs** [comment]
Relanded in https://github.com/flutter/engine/commit/3a28e8afeffd6f8dbb7e111df7a70c8d78e846f3, I forgot to close.
