### ISSUE TITLE
Linux Fuchsia FEMU shell_tests is flaking

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#112017]
The first example is here: 
https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20Fuchsia%20FEMU/11876/overview

I reverted https://github.com/flutter/engine/pull/36109 thinking it introduced the failure, but it looks more like a flake after looking more closely at the dashboard.

<img width="828" alt="Screen Shot 2022-09-20 at 4 09 31 PM" src="https://user-images.githubusercontent.com/30870216/191380475-0e866659-0e77-4786-a90c-2c83c7c373e8.png">

**Comment by gaaclarke** [comment]
@cfontas maybe you have an idea since your PR was also fuchsia related and was effected?

**Comment by gaaclarke** [comment]
Looking through the commits that landed today.  One doesn't seem obvious to me.  Normally I'd suggest doing a bisect.  I'm not sure if that is easy to do for you with the fuchsia toolchain.

**Comment by iskakaushik** [comment]
Seems like the first instance of these has started after https://github.com/flutter/engine/pull/36247/. Is it possible to symbolicate https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8802421798905976737/+/u/FEMU_Test/test:_Run_FEMU_Test_Suite_shell_tests__3_/syslog to understand what is going on?

cc: @akbiggs

**Comment by akbiggs** [comment]
Symbolized emulator_log using `ffx debug symbolize` (after running `ffx debug symbolize --auth`) but it doesn't give much more information https://gist.githubusercontent.com/akbiggs/a8b8eae4c3e9e70a141f8eb87edbb47e/raw/cafc15702026dd260d45768a4ca0fe50b2e060a5/gistfile1.txt

Should we revert the Fuchsia SDK roll back a few days and pause it?

**Comment by akbiggs** [comment]
Ah, looking at adjacent tests this is https://github.com/flutter/flutter/issues/59816. We should disable this test on Fuchsia.

**Comment by akbiggs** [comment]
This should be fixed after https://github.com/flutter/engine/pull/36320, closing but please reopen if this continues happening.
