### ISSUE TITLE
[Impeller] Preserve benchmarks on capacity constrained iPhone 6s devices.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#112121]
Per @jmagman, iPhone 6s devices in the device lab are going to be slowly phased out in favor of iPhone 11. This issue tracks preserving some Impeller benchmarks for as long as possible (expected to be a few more months). The benchmarks:
* fullscreen_textfield_perf_impeller_ios__e2e_summary
* list_text_layout_impeller_perf__e2e_summary
* complex_layout_scroll_perf_bad_impeller_ios__timeline_summary
* new_gallery_impeller_ios__transition_perf

The rest may be migrated to iPhone 11 immediately.

**Comment by chinmaygarde** [comment]
cc @dnfield @zanderso @jmagman

**Comment by jmagman** [comment]
https://github.com/flutter/flutter/issues/111131#issuecomment-1254387044

**Comment by jmagman** [comment]
cc @yusuf-goog

**Comment by zanderso** [comment]
In addition to the ones that Chinmay mentioned let's also keep these on 6s.

* complex_layout_scroll_perf_bad_impeller_ios__timeline_summary
* new_gallery_impeller_ios__transition_perf

I'll add these to the list at the top of the issue.

**Comment by jmagman** [comment]
We will need to maintain iPhone 6s in the lab in both the staging (in case tests are marked flaky) and prod pools.

**Comment by chinmaygarde** [comment]
Is there anything else to do on this front?

**Comment by yusuf-goog** [comment]
We will keep a few iphone6s in the lab, to cover running the above tests. Nothing more is required at this moment.

**Comment by chinmaygarde** [comment]
Sounds good. Looks like there is nothing more to do ATM. Closing.
