### ISSUE TITLE
[impeller] fullscreen_textfield_perf_impeller_ios__e2e_summary benchmark regressed

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#112107]
[Skia Perf](https://flutter-flutter-perf.skia.org/e/?begin=1663713613&end=1663774150&keys=X4515258389ce36547a969aafc5545137&selected=commit%3D31206%26name%3D%252Carch%253Dintel%252Cbranch%253Dmaster%252Cconfig%253Ddefault%252Cdevice_type%253DiPhone_6s%252Cdevice_version%253DiOS-15.5%252Chost_type%253Dmac%252Csub_result%253Daverage_frame_rasterizer_time_millis%252Ctest%253Dfullscreen_textfield_perf_impeller_ios__e2e_summary%252C&xbaroffset=31206) data.

Suspected engine roll: https://github.com/flutter/flutter/pull/112032
Suspected engine PR: https://github.com/flutter/engine/pull/36171

**Comment by dnfield** [comment]
Came back down after the revert. Thanks Yegor!
