### ISSUE TITLE
[Impeller] Smoke test Chalk GPU performance

### ISSUE THREAD

**Issue by bdero** [flutter/flutter#112135]
Currently, we're CPU bottlenecked on text and possibly UI thread issues, but we can still preemptively find GPU performance issues by walking through each screen and taking single frame GPU captures.

This does require some care to avoid red herrings -- occasionally captured frames may render with half the GPU cores, for example.

Disabling atlas generation by commenting the Skia text draws is also a fine way to temporarily stop us from starving the GPU on the raster thread and make multi-frame profiling captures clearer.

**Comment by chinmaygarde** [comment]
Closing this as completed. We have action items from this investigation.
