### ISSUE TITLE
Dart DevTools exited with code -4058. Would you like to try reactivating DevTools?

### ISSUE THREAD

**Issue by doszhvn** [flutter/flutter#112189]
![fl](https://user-images.githubusercontent.com/111976446/191794746-b1da6264-ecba-4fa9-accd-03a77aef7262.png)
An error occurs while creating a flutter project: Dart DevTools exited with code -4058. What can be a common problem?

**Comment by Lsaier** [comment]
Only problem is the one u gotta personally deal with. N that’s urself bro

**Comment by doszhvn** [comment]
> Only problem is the one u gotta personally deal with. N that’s urself bro

I searched 1000 resources, I can't find a solution

**Comment by doszhvn** [comment]
> 

Yes bro. Loading activation devtools doesn't end when clicking on reactivate devtools

**Comment by exaby73** [comment]
Could you post the entire output of `flutter doctor -v`?

**Comment by doszhvn** [comment]
> Не могли бы вы опубликовать весь вывод `flutter doctor -v`?

![image](https://user-images.githubusercontent.com/111976446/191965968-8d0222bf-c1b7-45ee-b069-bc30b48fb9c4.png)

**Comment by exaby73** [comment]
@doszhvn Please post the output in text. You can directly copy and paste it here.
