### ISSUE TITLE
salt master is not auto accepting devicelab win minions keys

### ISSUE THREAD

**Issue by yusuf-goog** [flutter/flutter#112128]

**Comment by yusuf-goog** [comment]
The windows salt minion hostnames are of the format flutter-win-1 and not as currently specified flutter-devicelab-windows-1. Putting a CL to fix.

**Comment by yusuf-goog** [comment]
http://go/tircl/589530

**Comment by godofredoc** [comment]
@ricardoamador this is the problem fixed yesterday
