### ISSUE TITLE
[google_maps_flutter] setMapStyle error on Android, show road strokes when shouldn't

### ISSUE THREAD

**Issue by xmany** [flutter/flutter#112120]
## Steps to Reproduce

google_maps_flutter: 2.2.0
flutter: 3.3.2
Issue only exists on Android, it works fine on iOS

1. Define a map style JSON file with road stroke off:
(My may style configuration file was generated on https://mapstyle.withgoogle.com)

```
  {
    "featureType": "road",
    "elementType": "geometry.stroke",
    "stylers": [
      {
        "visibility": "off"
      }
    ]
  }
```

Or define the road style as "simplified", e.g.:

```
{
    "featureType": "road.arterial",
    "stylers": [
      {
        "visibility": "simplified"
      }
    ]
  },
```
2. Load the json file when app starts;

3. Add a `GoogleMap` widget in the app, set map style in the `onMapCreated` callback

```
mapController.setMapStyle(mapStyle);
```

4. GoogleMap will follow the map style, except the road strokes are **VISIBLE** and look terrible.

| Android | IOS |
| --------------- | --------------- |
<img width="400" src="https://user-images.githubusercontent.com/57887009/191621213-bd0eb49f-8bde-4d70-b5d8-35e4d01909f2.jpeg"> | <img width="400" src="https://user-images.githubusercontent.com/57887009/191621179-8a4961a7-2b20-4ae9-8a3e-c48f25fe2768.PNG">

flutte doctor -v

```
[✓] Flutter (Channel stable, 3.3.2, on macOS 12.6 21G115 darwin-arm, locale en-AU)
    • Flutter version 3.3.2 on channel stable at /Users/jimmy/dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e3c29ec00c (7 days ago), 2022-09-14 08:46:55 -0500
    • Engine revision a4ff2c53d8
    • Dart version 2.18.1
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/jimmy/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/jimmy/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A309
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.71.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (3 available)
    • SM G986B (mobile) • xxxxxx • android-arm64  • Android 12 (API 31)
    • macOS (desktop)   • macos       • darwin-arm64   • macOS 12.6 darwin-arm
    • Chrome (web)      • chrome      • web-javascript • Google Chrome yyyyyy

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

**Comment by huycozy** [comment]
Hi @xmany, thanks for filing the issue.
But I can not reproduce the issue on the latest `stable` and `master` channels.

Plugin version: `google_maps_flutter: ^2.2.0`
Device info: `Samsung Galaxy Tab A7 Lite, Android 12 OneUI 4.1, SM-T225`
Map style JSON:
```json
[
  {
    "featureType": "road.arterial",
    "stylers": [
      {
        "visibility": "simplified"
      }
    ]
  }
]
```

<details>
<summary>Demo</summary>

![Screen Shot 2022-09-22 at 19 28 58](https://user-images.githubusercontent.com/104349824/191747031-26867e30-462e-4bea-8b40-4ffa1144e707.png)

</details>

<details>
<summary>Sample code</summary>

Using plugin's sample code with updated map style JSON file content as above: https://github.com/flutter/plugins/blob/main/packages/google_maps_flutter/google_maps_flutter/example/lib/map_ui.dart

</details>

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 3.3.2, on macOS 12.6 21G115 darwin-x64, locale en-VN)
    • Flutter version 3.3.2 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e3c29ec00c (6 days ago), 2022-09-14 08:46:55 -0500
    • Engine revision a4ff2c53d8
    • Dart version 2.18.1
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13E113
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.71.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.6 21G115 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 105.0.5195.125

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

```bash
[✓] Flutter (Channel master, 3.4.0-19.0.pre.436, on macOS 12.6 21G115 darwin-x64, locale en-VN)
    • Flutter version 3.4.0-19.0.pre.436 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 0906c14dd7 (40 minutes ago), 2022-09-21 21:35:31 -0400
    • Engine revision 836dfd6549
    • Dart version 2.19.0 (build 2.19.0-226.0.dev)
    • DevTools version 2.17.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A309
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.71.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (3 available)
    • SM T225 (mobile) • R9JT3004VRJ • android-arm64  • Android 12 (API 31)
    • macOS (desktop)  • macos       • darwin-x64     • macOS 12.6 21G115 darwin-x64
    • Chrome (web)     • chrome      • web-javascript • Google Chrome 105.0.5195.125

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```
</details>

Which Android device are you testing?
Also, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this. 
Thank you!

**Comment by xmany** [comment]
> Hi @xmany, thanks for filing the issue.
> But I can not reproduce the issue on the latest `stable` and `master` channels.
> 
> Plugin version: `google_maps_flutter: ^2.2.0`
> Device info: `Samsung Galaxy Tab A7 Lite, Android 12 OneUI 4.1, SM-T225`
> Map style JSON:
> ```json
> [
>   {
>     "featureType": "road.arterial",
>     "stylers": [
>       {
>         "visibility": "simplified"
>       }
>     ]
>   }
> ]
> ```
> 
> <details>
> <summary>Demo</summary>
> 
> ![Screen Shot 2022-09-22 at 19 28 58](https://user-images.githubusercontent.com/104349824/191747031-26867e30-462e-4bea-8b40-4ffa1144e707.png)
> 
> </details>
> 
> <details>
> <summary>Sample code</summary>
> 
> Using plugin's sample code with updated map style JSON file content as above: https://github.com/flutter/plugins/blob/main/packages/google_maps_flutter/google_maps_flutter/example/lib/map_ui.dart
> 
> </details>
> 
> <details>
> <summary>flutter doctor -v</summary>
> 
> ```bash
> [✓] Flutter (Channel stable, 3.3.2, on macOS 12.6 21G115 darwin-x64, locale en-VN)
>     • Flutter version 3.3.2 on channel stable at /Users/huynq/Documents/GitHub/flutter
>     • Upstream repository https://github.com/flutter/flutter.git
>     • Framework revision e3c29ec00c (6 days ago), 2022-09-14 08:46:55 -0500
>     • Engine revision a4ff2c53d8
>     • Dart version 2.18.1
>     • DevTools version 2.15.0
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
>     • Android SDK at /Users/huynq/Library/Android/sdk
>     • Platform android-33, build-tools 31.0.0
>     • ANDROID_HOME = /Users/huynq/Library/Android/sdk
>     • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
>     • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
>     • All Android licenses accepted.
> 
> [✓] Xcode - develop for iOS and macOS (Xcode 13.3)
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • Build 13E113
>     • CocoaPods version 1.11.3
> 
> [✓] Chrome - develop for the web
>     • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
> 
> [✓] Android Studio (version 2021.2)
>     • Android Studio at /Applications/Android Studio.app/Contents
>     • Flutter plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/9212-flutter
>     • Dart plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/6351-dart
>     • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
> 
> [✓] IntelliJ IDEA Community Edition (version 2022.1.1)
>     • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
>     • Flutter plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/9212-flutter
>     • Dart plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/6351-dart
> 
> [✓] VS Code (version 1.71.2)
>     • VS Code at /Applications/Visual Studio Code.app/Contents
>     • Flutter extension version 3.48.0
> 
> [✓] Connected device (2 available)
>     • macOS (desktop) • macos  • darwin-x64     • macOS 12.6 21G115 darwin-x64
>     • Chrome (web)    • chrome • web-javascript • Google Chrome 105.0.5195.125
> 
> [✓] HTTP Host Availability
>     • All required HTTP hosts are available
> 
> • No issues found!
> 
> ```
> 
> ```bash
> [✓] Flutter (Channel master, 3.4.0-19.0.pre.436, on macOS 12.6 21G115 darwin-x64, locale en-VN)
>     • Flutter version 3.4.0-19.0.pre.436 on channel master at /Users/huynq/Documents/GitHub/flutter_master
>     • Upstream repository https://github.com/flutter/flutter.git
>     • Framework revision 0906c14dd7 (40 minutes ago), 2022-09-21 21:35:31 -0400
>     • Engine revision 836dfd6549
>     • Dart version 2.19.0 (build 2.19.0-226.0.dev)
>     • DevTools version 2.17.0
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
>     • Android SDK at /Users/huynq/Library/Android/sdk
>     • Platform android-33, build-tools 31.0.0
>     • ANDROID_HOME = /Users/huynq/Library/Android/sdk
>     • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
>     • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
>     • All Android licenses accepted.
> 
> [✓] Xcode - develop for iOS and macOS (Xcode 14.0)
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • Build 14A309
>     • CocoaPods version 1.11.3
> 
> [✓] Chrome - develop for the web
>     • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
> 
> [✓] Android Studio (version 2021.2)
>     • Android Studio at /Applications/Android Studio.app/Contents
>     • Flutter plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/9212-flutter
>     • Dart plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/6351-dart
>     • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
> 
> [✓] IntelliJ IDEA Community Edition (version 2022.1.1)
>     • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
>     • Flutter plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/9212-flutter
>     • Dart plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/6351-dart
> 
> [✓] VS Code (version 1.71.2)
>     • VS Code at /Applications/Visual Studio Code.app/Contents
>     • Flutter extension version 3.48.0
> 
> [✓] Connected device (3 available)
>     • SM T225 (mobile) • R9JT3004VRJ • android-arm64  • Android 12 (API 31)
>     • macOS (desktop)  • macos       • darwin-x64     • macOS 12.6 21G115 darwin-x64
>     • Chrome (web)     • chrome      • web-javascript • Google Chrome 105.0.5195.125
> 
> [✓] HTTP Host Availability
>     • All required HTTP hosts are available
> 
> • No issues found!
> 
> ```
> </details>
> 
> Which Android device are you testing?
> Also, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this. 
> Thank you!
> 
> 

Thanks for the reply, I will provide more stuff including a minimal project tomorrow

In the meantime, the issue will appear when zooming in a bit, in your screenshot it was quite zoomed out, that may not trigger the issue.

**Comment by huycozy** [comment]
Hi @xmany 
I was zooming in and see it looks fine (please see in demo)
<details>
<summary>Demo</summary>

<img width="542" alt="Screen Shot 2022-09-23 at 09 50 50" src="https://user-images.githubusercontent.com/104349824/191883760-60867499-0986-463f-93bf-2c85e05953b8.png">
</details>

>Thanks for the reply, I will provide more stuff including a minimal project tomorrow

Thanks! That will be helpful for us to verify the issue.

**Comment by xmany** [comment]
> Hi @xmany I was zooming in and see it looks fine (please see in demo)
> 
> Demo
> > Thanks for the reply, I will provide more stuff including a minimal project tomorrow
> 
> Thanks! That will be helpful for us to verify the issue.

Hi, Sorry for being super late, the issue persists and I have a minimal project now

https://github.com/xmany/testmap2

Enable the following lines in the style file will cause the stroke to be hyper visible:
```
  {
    "featureType": "road",
    "stylers": [
      {
        "visibility": "simplified"
      }
    ]
  },
  {
    "featureType": "road.arterial",
    "stylers": [
      {
        "visibility": "simplified"
      }
    ]
  },
```

Explicitly disabling strokes will do the same as well.

**Comment by huycozy** [comment]
@xmany thanks, now I can reproduce the issue with sample code in https://github.com/xmany/testmap2.
There is a difference between Android and iOS as below demo. 
Plugin version: `google_maps_flutter: ^2.2.1`

<details>
<summary>Demo (Android + iOS)</summary>

| Android | iOS |
| --------------- | --------------- |
<img width="400" src="https://user-images.githubusercontent.com/104349824/194769548-a1e6d403-63ad-4103-a50c-13e2f20a3eeb.png"> | <img width="400" src="https://user-images.githubusercontent.com/104349824/194769561-7d690019-4e50-4606-a94d-fd2854420d16.png">

</details>

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.3.4, on macOS 12.6 21G115 darwin-x64, locale en-VN)
    • Flutter version 3.3.4 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision eb6d86ee27 (23 hours ago), 2022-10-04 22:31:45 -0700
    • Engine revision c08d7d5efc
    • Dart version 2.18.2
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode14.0.1.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2022.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 70.0.5
    • Dart plugin version 222.4167.21

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.71.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.6 21G115 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 105.0.5195.125

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

```bash
[✓] Flutter (Channel master, 3.5.0-3.0.pre.5, on macOS 12.6 21G115 darwin-x64, locale en-VN)
    • Flutter version 3.5.0-3.0.pre.5 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9ca314afd0 (12 minutes ago), 2022-10-06 23:06:11 -0400
    • Engine revision a4174f29a7
    • Dart version 2.19.0 (build 2.19.0-286.0.dev)
    • DevTools version 2.18.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode14.0.1.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2022.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 70.0.5
    • Dart plugin version 222.4167.21

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.71.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (5 available)
    • SM T225 (mobile)           • R9JT3004VRJ                              • android-arm64  • Android 12 (API 31)
    • iPhone (mobile)            • d9a94afe2b649fef56ba0bfeb052f0f2a7dae95e • ios            • iOS 15.7 19H12
    • iPhone 14 Pro Max (mobile) • 332079AF-E895-4685-910E-7B1E18B0C6B8     • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-0 (simulator)
    • macOS (desktop)            • macos                                    • darwin-x64     • macOS 12.6 21G115 darwin-x64
    • Chrome (web)               • chrome                                   • web-javascript • Google Chrome 106.0.5249.103
    ! Error: iPhone is busy: Fetching debug symbols for iPhone. Xcode will continue when iPhone is finished. (code -10)

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```
</details>


Labeling this issue for further investigation.

**Comment by stuartmorgan** [comment]
The plugin just passes the style string directly to the Google Maps SDK. If the styling feature works in general, and it's just that specific style that's not being honored, then that's an issue in the SDK rather than the plugin, and you'll need to report it as a Google Maps SDK issue.
