### ISSUE TITLE
[google_maps_flutter] Some polygons have wrong fill color on iOS 

### ISSUE THREAD

**Issue by piotruela** [flutter/flutter#112150]
In my app for some of the polygons I view on google map fill color is ignored and they have translucent blue fill color. It happens only on iOS and always on the same polygons. (On Android all of the polygons are viewed correctly). It's the same issue as on react native described here: [similar react native issue](https://github.com/react-native-maps/react-native-maps/issues/3057). 
![image](https://user-images.githubusercontent.com/37781044/191678204-04ff121f-850d-4e63-94a3-680c7367a008.png)
Those glitchy polygons does not consume any tap events. When I display tile overlays over them, original tile overlay color is changed to incorrect.

**Comment by darshankawar** [comment]
@piotruela 
Can you provide `flutter doctor -v`, plugin version and a minimal code sample that shows the behavior you are seeing along with actual vs expected result ?
