### ISSUE TITLE
Copying `InheritedWidget` example leads to `avoid_renaming_method_parameters`

### ISSUE THREAD

**Issue by robiness** [flutter/flutter#112136]
Simply copying the InheritedWidget [example](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/framework.dart#L1599-L1616) leads to an [`avoid_renaming_method_parameters`](https://dart-lang.github.io/linter/lints/avoid_renaming_method_parameters.html) lint warning.

The implementation uses the name `oldWIdget`:
https://github.com/flutter/flutter/blob/0cd381015965aef25344a17605078acbee73f920/packages/flutter/lib/src/widgets/framework.dart#L1736
while the example still uses just `old`:
https://github.com/flutter/flutter/blob/0cd381015965aef25344a17605078acbee73f920/packages/flutter/lib/src/widgets/framework.dart#L1615

**Comment by darshankawar** [comment]
Thanks for the report and the fix.
