### ISSUE TITLE
"BUILDING shared_preferences/shared_preferences/example for web" timing out in flutter->plugin roll

### ISSUE THREAD

**Issue by cyanglaz** [flutter/flutter#112195]
Roll PR: https://github.com/flutter/plugins/pull/6461

Failure log: https://cirrus-ci.com/task/5933934784544768?logs=build#L132

```
Building for: web
BUILDING shared_preferences/shared_preferences/example for web
Running command: "flutter build web" in /tmp/cirrus-ci-build/packages/shared_preferences/shared_preferences/example
Downloading Web SDK...                                           2,822ms
Downloading CanvasKit...                                           511ms
Running "flutter pub get" in example...                             6.4s
💪 Building with sound null safety 💪
Upgrading .gitignore
Compiling lib/main.dart for the Web...                          
Timed out!
```

**Comment by cyanglaz** [comment]
cc @stuartmorgan @ditman

**Comment by stuartmorgan** [comment]
Does it repro locally at the same `flutter` hash?

**Comment by cyanglaz** [comment]
It built successfully for me locally at 463ee3d58ccf089c92e3c51d302b2796b9d43a66

**Comment by ditman** [comment]
The failing task seems to be `CHANNEL:stable`, so I don't think this has to do (directly) with the roll?

Wouldn't this build be using the `.ci/flutter_stable.version` pin? (f1875d570e39de09040c8f79aa13cc56baab8db1)

**Comment by ditman** [comment]
The other run failed with a (known) flake of the video player web lifecycle, I think this was a different flake in the same shard.

**Comment by ditman** [comment]
The build has passed now: https://cirrus-ci.com/task/5841667411410944

**Comment by stuartmorgan** [comment]
If the timeout version of the flake only happened once, let's assume this was a fluke and close it. If it happens again we can investigate further.

**Comment by ditman** [comment]
The `video_player_web` flake has definitely happened in the past. The other one, I'm not entirely sure.
