### ISSUE TITLE
showDialog with barrierDismissible: false not being honored 

### ISSUE THREAD

**Issue by kssujithcj** [flutter/flutter#112179]
## Steps to Reproduce
- Create an application which shows dialog using showDialog() of material/dialog.dart of source code and send barrierDismissible as false.
- On Android 12, onBackPress by a user closes the dialog, on older versions of Android, the behavior is as expected (doesn't close dialog).
- I am using Flutter version: Channel stable, 2.10.4 and android compile and target sdk version 31

**Comment by exaby73** [comment]
Hello @kssujithcj. Please upgrade to the latest stable version of Flutter (3.3.2) and confirm if this issue still exists.

**Comment by kssujithcj** [comment]
On Flutter 3.0.0 also it is the same behavior. Sorry for the confusion. I think I wasn't using the bool properly.
Barrier dismissible will only block dialog closing, on taping outside of the dialog. But it is never intended to block onBackpress()
Solution is to use WillPopScope as mentioned [here](https://stackoverflow.com/a/63633010). 

Sorry again and Thank you for your time.

**Comment by exaby73** [comment]
No issues @kssujithcj. Please don't be discouraged from raising issues in the future if you feel there is a bug. Thanks anyways :)
