### ISSUE TITLE
The ci yaml roller should rebase to TOT when rolling config changes

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#112127]
Current state: ci.yaml roller rolls whatever is in the current commit.

Problem: earlier rolled ci yaml configs will be rolled back if the later landed commit doesn't rebase to TOT. This will cause latency of config changes, and cause confusion as well. The real change could be rolled back and forth depending on the commits' statuses.

Possible solution: rebase the commit to TOT in the ci yaml roller builder whenever a roller is happening.

Context: https://github.com/flutter/flutter/issues/112117

**Comment by CaseyHillers** [comment]
I sent https://flutter-review.googlesource.com/c/recipes/+/50200 to fix the roller to pick up HEAD instead of roll at a specific SHA.
