### ISSUE TITLE
Removing `cpu` from Mac tests in .ci.yaml still runs only on x64 machines

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#112117]
After https://github.com/flutter/flutter/pull/109889 I expected `Mac ` hostonly tests to run on either arm or x64 depending on capacity.  However the `cpu` dimension is still set to `x86`

Example:
https://github.com/flutter/flutter/blob/d98c263e3058d30731da0ffea19db4f8c0c10862/.ci.yaml#L2473-L2484
https://github.com/flutter/flutter/blob/d98c263e3058d30731da0ffea19db4f8c0c10862/.ci.yaml#L73-L79

When it ran it still has `"cpu": "x86"` set:
https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20dart_plugin_registry_test/7264/overview

And the swarming task only shows x64 bots as able to run it:
https://chromium-swarm.appspot.com/task?id=5d7adb0db77c1a10&o=true&w=true
https://chromium-swarm.appspot.com/botlist?c=id&c=task&c=cpu&c=os&c=status&d=asc&f=pool%3Aluci.flutter.prod&f=os%3AMac-12&f=cpu%3Ax86&f=device_type%3Anone&s=id

Is there a `cpu` default set in `infra` somewhere?

@keyonghan

**Comment by keyonghan** [comment]
Your change does remove the `cpu:x86` dimension: https://flutter-review.googlesource.com/c/infra/+/34205/2/config/generated/flutter/luci/cr-buildbucket.cfg#59474.

But following landed commits (which are not rebased on top of your PR) forced the roller to roll back to earlier CI configs...

This is a TD, and filed https://github.com/flutter/flutter/issues/112127 to track.

**Comment by jmagman** [comment]
Well we know this worked eventually because the tests started flaking https://github.com/flutter/flutter/issues/112130 🙂 

Closing, https://github.com/flutter/flutter/issues/112127 to track the ci config thrash.
