### ISSUE TITLE
[mobile]how to disable scrollview when pinch zoom in image

### ISSUE THREAD

**Issue by isomizer** [flutter/flutter#112144]
I am using the lib [pinch_zoom_release_unzoom](https://pub.dev/packages/pinch_zoom_release_unzoom) to pinch zoom image. I create it inside SingleChildScrollView but when user use 2 finger to pinch zoom image. it very difficult to zoom because sometime page is Scrollable. so I want to solve this problem

**Comment by darshankawar** [comment]
@isomizer 
Your question is better suited for support channels like StackOverflow, so please ask the same there.
Closing from here, as this is not a bug or a feature request.
