### ISSUE TITLE
hot reload benchmark regression from recent Dart SDK roll

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#112110]
[Skia Gold data](https://flutter-flutter-perf.skia.org/e/?begin=1663723404&end=1663777807&keys=X598ec58a17043de7c4b54d50c867aa15&selected=commit%3D31211%26name%3D%252Carch%253Darm%252Cbranch%253Dmaster%252Cconfig%253Ddefault%252Cdevice_type%253DiPhone_6s%252Cdevice_version%253DiOS-15.5%252Chost_type%253Dmac%252Csub_result%253DhotReloadVMReloadMillisecondsAfterChange%252Ctest%253Dhot_mode_dev_cycle_macos_target__benchmark%252C&xbaroffset=31211)

Suspected Dart SDK roll: https://github.com/flutter/engine/pull/36315

**Comment by jason-simmons** [comment]
Duplicate of https://github.com/flutter/flutter/issues/112177
