### ISSUE TITLE
hotReloadVMReloadMillisecondsAfterChange  - Hot reload time increase from 50 to 51

### ISSUE THREAD

**Issue by iskakaushik** [flutter/flutter#112177]
[This benchmark](https://flutter-flutter-perf.skia.org/e/?begin=1663723404&end=1663777807&keys=X598ec58a17043de7c4b54d50c867aa15&selected=commit%3D31211%26name%3D%252Carch%253Darm%252Cbranch%253Dmaster%252Cconfig%253Ddefault%252Cdevice_type%253DiPhone_6s%252Cdevice_version%253DiOS-15.5%252Chost_type%253Dmac%252Csub_result%253DhotReloadVMReloadMillisecondsAfterChange%252Ctest%253Dhot_mode_dev_cycle_macos_target__benchmark%252C&xbaroffset=31211) was extremely stable.

<img width="1348" alt="image" src="https://user-images.githubusercontent.com/1006071/191772911-01462693-23dd-42d9-aba6-8fa23f4e9d6a.png">

Seems to have increased with: https://github.com/flutter/engine/pull/36315

[Another benchmark](https://flutter-flutter-perf.skia.org/e/?begin=1663777160&end=1663796864&keys=X7159d7556b1615d5fe43c4e34c490a09&selected=commit%3D31223%26name%3D%252Carch%253Darm%252Cbranch%253Dmaster%252Cconfig%253Ddefault%252Cdevice_type%253DiPhone_6s%252Cdevice_version%253DiOS-15.5%252Chost_type%253Dmac%252Csub_result%253DhotReloadVMReloadMillisecondsAfterLargeChange%252Ctest%253Dhot_mode_dev_cycle_macos_target__benchmark%252C&xbaroffset=31223) that increased:

`hotReloadVMReloadMillisecondsAfterLargeChange`

<img width="355" alt="image" src="https://user-images.githubusercontent.com/1006071/191773623-08de7257-50a1-44b6-89ba-84938cea93d4.png">

cc: @a-siva , @zanderso

**Comment by iskakaushik** [comment]
Not sure if this should be a P0 given the minor increase, but marking it so per policy of benchmark regression.

**Comment by iskakaushik** [comment]
There are more benchmarks that regressed for hot-reload as well: https://flutter-flutter-perf.skia.org/e/?begin=1663777160&end=1663796864&keys=X7159d7556b1615d5fe43c4e34c490a09&selected=commit%3D31223%26name%3D%252Carch%253Darm%252Cbranch%253Dmaster%252Cconfig%253Ddefault%252Cdevice_type%253DiPhone_6s%252Cdevice_version%253DiOS-15.5%252Chost_type%253Dmac%252Csub_result%253DhotReloadVMReloadMillisecondsAfterLargeChange%252Ctest%253Dhot_mode_dev_cycle_macos_target__benchmark%252C&xbaroffset=31223

**Comment by a-siva** [comment]
This seems to be a set of changes in the Dart roll https://dart.googlesource.com/sdk.git/+log/33c0f62f0964..7f7b7f28120f

From this set there are only two VM changes
- 9598547 [VM/Library] - Adjust next probe to be a quadratic probe in _HashBase by asiva · 2 days ago
- 7f40a29 [vm] Fix debug/arm64c build by Alexander Markov · 2 days ago
- 83ab5d5 [vm] Remove dynamic field unboxing in JIT by Vyacheslav Egorov · 2 days ago

I don't believe the debug/arm64c build fix change could have caused it.

Need to check the other two changes to see if they could have made a difference, I am suspecting the quadratic probe change could have caused it. I will revert it and see if that fixes it.

**Comment by a-siva** [comment]
I have created a revert CL here https://dart-review.googlesource.com/c/sdk/+/260747, once it lands and rolls into Flutter we can recheck and see if the regression here is addressed.

**Comment by a-siva** [comment]
It appears that the minor regression is due to 83ab5d5 [vm] Remove dynamic field unboxing in JIT
This CL is a nice refactoring and I don't believe should be reverted.
At this point I am inclined to take the minor regression if folks here agree.

**Comment by zanderso** [comment]
sgtm. Do you know why that refactoring caused the regression?
