### ISSUE TITLE
Flutter web: The console show alert message when the HTTP response status codes is failed

### ISSUE THREAD

**Issue by SittiphanSittisak** [flutter/flutter#112155]
I am using the API in Flutter. Sometimes the server will return failed HTTP response status codes and Flutter always auto-generated the alert message and show the API URL in the console. I don't want to show the API URL this alert message makes the app look incomplete from the user's perspective.
I used try/catch but those messages still display in the console.

This message shown in the console looks like this:
![image](https://user-images.githubusercontent.com/59549741/191691391-5986b040-782a-4df2-a21c-4775e5b2ff3e.png)

**Comment by exaby73** [comment]
Hello @SittiphanSittisak. This is normal behavior for the browser. The console ideally isn't something that a user should ever look at anyways. But this issue is not an issue with Flutter. Therefore, I am closing it. If you disagree, please comment and I can reopen it. Thank you.

**Comment by Lsaier** [comment]
Comment

**Comment by SittiphanSittisak** [comment]
Thank you for your response. Can you give a way that can clear the console in Flutter-web?

**Comment by exaby73** [comment]
You can use `console.clear()` from the `dart:html` library. Though be careful running that code in a non-web app, else it will throw an `UnimplementedError`

**Comment by SittiphanSittisak** [comment]
Everything is clear!

I am using:
```
import 'package:universal_html/html.dart';
window.console.clear();
```
