### ISSUE TITLE
[go_router_builder] Allow the user to specify a type converter of the parameters

### ISSUE THREAD

**Issue by ValentinVignal** [flutter/flutter#112152]
This is kind of an extension to https://github.com/flutter/flutter/issues/108437

## Use case

I'm using go router builder and I have a route with optional parameters:

```dart
enum MyEnum {
  myFirstEntry,
  mySecondEntry,
}

@TypedGoRoute<MyRoute>(path: '/my-path')
class MyRoute extends GoRouteData {
  const MyRoute({
    this.myBoolean = false,
    this.myEnum,
  });

  final bool myBoolean;

  final MyEnum? myEnum;

  @override
  Widget build(BuildContext context) => const MyScreen();
}
```

If I want `myBoolean` to be true, it forces the `url` to be `my-boolean=true`. But I might want another formatting, like `myBoolean=true` (parameter not in `kebab-case`) or `my-boolean=t` (`t` instead of `true`).

There is the same issue with `myEnum`, it forces the url parameter to be `my-enum` (but I could want to keep `myEnum`) and the values to be `kebab-case` like `my-first-route` (but I could want to keep `myFirstEntry` : `myEnum=myFirstEntry`).

In my case, those parameters are set by a thrid party of my app and I cannot control them or change them, which prevents me from using go_router_builder.

## Proposal

It could be nice to allow us to specify the formatting/create a converter like [`json_serializable`](https://pub.dev/packages/json_serializable) and [`JsonConverter`](https://pub.dev/documentation/json_annotation/latest/json_annotation/JsonConverter-class.html).

```dart
enum MyEnum {
  myFirstEntry,
  mySecondEntry,
}

@TypedGoRoute<MyRoute>(path: '/my-path')
class MyRoute extends GoRouteData {
  const MyRoute({
    this.myBoolean = false,
    this.myEnum,
  });
  
  @TypedGoRouteParameter<bool>(name: 'my-boolean')
  final bool myBoolean;
  
  @MyEnumConverter()
  final MyEnum? myEnum;

  @override
  Widget build(BuildContext context) => const MyScreen();
}


class MyEnumConverter extends TypedGoRouteParameter<MyEnum> {
  class MyEnumConverter(super.name);

  @override
  String? toUrlString(MyEnum myEnum) {
    // Return the correct format here.
    // If `null` is returned, fall back to the existing behavior.
  }

  @override
  MyEnum? fromUrlString(String value) {
    // Return the correct value here.
    // If `null` is returned, fall back to the existing behavior.
  }
}
```

**Comment by chunhtai** [comment]
looks like this can be solved by https://github.com/flutter/flutter/issues/110781
