### ISSUE TITLE
Update `Divider`  to support Material 3 

### ISSUE THREAD

**Issue by TahaTesser** [flutter/flutter#112169]
Specs: https://m3.material.io/components/divider/specs

![image](https://user-images.githubusercontent.com/48603081/192213962-f91d991d-3d17-4655-b765-dea8d9789a15.png)

We should update the `Divider` widget to support this Material 3 look and tokens.

**Comment by TahaTesser** [comment]
cc: @darrenaustin 
Please see https://github.com/flutter/flutter/pull/111495#discussion_r977588568

Could you please add this issue to https://github.com/flutter/flutter/issues/91605?

**Comment by darrenaustin** [comment]
> cc: @darrenaustin Please see [#111495 (comment)](https://github.com/flutter/flutter/pull/111495#discussion_r977588568)

I have added the divider tokens with #112323. Would you be interested in taking this issue?

> Could you please add this issue to #91605?

Done, thx!

**Comment by TahaTesser** [comment]
> Would you be interested in taking this issue?

Absolutely!

**Comment by TahaTesser** [comment]
Reverted https://github.com/flutter/flutter/pull/112471
