### ISSUE TITLE
Firebase Analytics should be able to automatically log PageRoute transitions

### ISSUE THREAD

**Issue by collinjackson** [flutter/flutter#11216]
Internally we have a Google Analytics plugin that defines `RouteObserver`.

We should define a public `RouteObserver` in Flutter so that Firebase Analytics can use it.

Firebase Analytics should implement a class that extends `NavigatorObserver` that developers can add to the `navigatorObservers` of their `MaterialApp` if they want to wire up automatic logging of page transitions.

**Comment by kroikie** [comment]
@collinjackson

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/983. Any further collaboration will be done there.
