### ISSUE TITLE
ChangeNotifier should get method removeListeners()

### ISSUE THREAD

**Issue by mobikats** [flutter/flutter#112112]
I discovered [this proposal](https://github.com/flutter/flutter/issues/52404) while searching for a method "removeListeners". 

The danger of unintended removal of listeners seems miniscule to me - we just want this method to avoid exceptions when disposing of change notifier objects, and at the moment it looks like we need to write a bunch of boilerplate to do something that the Framework object should just be doing itself in dispose.

iOS frameworks had this exact same issue in the past, and eventually solved it by making disposed objects with listeners simply do the admin of removing them themselves. 

Flutter should do the same here - make the dispose method do the work, as [@technolion proposed](https://github.com/flutter/flutter/issues/52404#issue-579257976) (or add a method to do it at least).

**Comment by darshankawar** [comment]
Thanks for the report. Treating this as a potential proposal and keeping this issue open to get insights from team since the original issue is 2 years old and to know if team's stand is still the same or if this can be done.

**Comment by mobikats** [comment]
Thanks @darshankawar 
My guess is that most devs simply live with the exception, since it is caught and can be unnoticed.
Having it tidy up itself would be ideal, second best would be a "removeAllListeners()" method that can be called. 
But having to manually track and remove listeners oneself seems like a bunch of boilerplate the framework should be doing. 
(My 2 cents anyway :))

**Comment by goderbauer** [comment]
> we just want this method to avoid exceptions when disposing of change notifier objects

Disposing a ChangeNotifier with listeners should be fine. Also, I believe we now allow removingListeners after an object has been disposed.

It's not really clear to me what this asking for. Do you have some sample code where you need this new method?
