### ISSUE TITLE
Warnings in assets-for-api-docs repo: 'headline4' is deprecated, 'bodyText2' is deprecated

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#112114]
```
   info - lib/src/container.dart:49:24 - 'headline4' is deprecated and shouldn't be used. Use headlineMedium instead. This feature was deprecated after v3.1.0-0.0.pre.. Try replacing the use of the deprecated member with the replacement. - deprecated_member_use
   info - lib/src/curve.dart:267:46 - 'bodyText1' is deprecated and shouldn't be used. Use bodyLarge instead. This feature was deprecated after v3.1.0-0.0.pre.. Try replacing the use of the deprecated member with the replacement. - deprecated_member_use
   info - lib/src/implicit_animations.dart:136:37 - 'headline4' is deprecated and shouldn't be used. Use headlineMedium instead. This feature was deprecated after v3.1.0-0.0.pre.. Try replacing the use of the deprecated member with the replacement. - deprecated_member_use
   info - lib/src/theme_data.dart:71:23 - 'bodyText2' is deprecated and shouldn't be used. Use bodyMedium instead. This feature was deprecated after v3.1.0-0.0.pre.. Try replacing the use of the deprecated member with the replacement. - deprecated_member_use
```
https://cirrus-ci.com/task/4541298282594304

Blocking https://github.com/flutter/assets-for-api-docs/pull/199

cc @Piinks #109817

**Comment by Piinks** [comment]
Running `dart fix --apply` should resolve all of those. Or I could open a separate PR to migrate them tomorrow.

We should also add this analysis to the presubmit checks in flutter/flutter via flutter/tests, I was surprised it was not represented there already. Otherwise we'll break this repo and be none the wiser (like now!). I'll file another issue for that.

**Comment by hellohuanlin** [comment]
@Piinks After running `dart fix --apply`, i got these issues: 

```

  error - lib/src/basic_shapes.dart:170:26 - In constant expressions, operands of this operator must be of type 'num'. - const_eval_type_num
  error - lib/src/basic_shapes.dart:171:24 - In constant expressions, operands of this operator must be of type 'num'. - const_eval_type_num
  error - lib/src/basic_shapes.dart:593:27 - In constant expressions, operands of this operator must be of type 'num'. - const_eval_type_num
   info - lib/src/container.dart:49:24 - 'headline4' is deprecated and shouldn't be used. Use headlineMedium instead. This feature was deprecated after v3.1.0-0.0.pre.. Try replacing the use of the deprecated member with the replacement. - deprecated_member_use
   info - lib/src/curve.dart:267:46 - 'bodyText1' is deprecated and shouldn't be used. Use bodyLarge instead. This feature was deprecated after v3.1.0-0.0.pre.. Try replacing the use of the deprecated member with the replacement. - deprecated_member_use
   info - lib/src/implicit_animations.dart:136:37 - 'headline4' is deprecated and shouldn't be used. Use headlineMedium instead. This feature was deprecated after v3.1.0-0.0.pre.. Try replacing the use of the deprecated member with the replacement. - deprecated_member_use
   info - lib/src/theme_data.dart:71:23 - 'bodyText2' is deprecated and shouldn't be used. Use bodyMedium instead. This feature was deprecated after v3.1.0-0.0.pre.. Try replacing the use of the deprecated member with the replacement. - deprecated_member_use
```

**Comment by Piinks** [comment]
Oh, it looks like it applied some other fixes that are maybe not quite complete.
I just looked at adding this the flutter/tests (https://github.com/flutter/flutter/issues/112116) and just running flutter analyze for the repo returns 13767 issues, so it is unsurprising this is in a bit of a state. 🤣 

The original text migrations from the error above are just simple renames:

- headline4 can just be renamed to headlineMedium
- bodyText1 is renamed bodyLarge
- bodyText2 is bodyMedium

**Comment by hellohuanlin** [comment]
> Oh, it looks like it applied some other fixes that are maybe not quite complete. I just looked at adding this the flutter/tests (#112116) and just running flutter analyze for the repo returns 13767 issues, so it is unsurprising this is in a bit of a state. 🤣
> 
> The original text migrations from the error above are just simple renames:
> 
> * headline4 can just be renamed to headlineMedium
> * bodyText1 is renamed bodyLarge
> * bodyText2 is bodyMedium

But these are only `info`, not errors. The first 3 are errors.
