### ISSUE TITLE
flutter doctor output is confusing for missing Android SDK packages 

### ISSUE THREAD

**Issue by DanTup** [flutter/flutter#11225]
I've been setting up flutter on my MacBook and had a similar issue to when setting up on Windows... I run `flutter doctor` and get output like this:

```text
[-] Android toolchain - develop for Android devices
    • Android SDK at /Users/danny/Dev/android
    • ANDROID_HOME = /Users/danny/Dev/android
    ✗ Android SDK is missing command line tools; download from https://goo.gl/XxQghQ
    • Try re-installing or updating your Android SDK,
      visit https://flutter.io/setup/#android-setup for detailed instructions.
```

I'd downloaded the SDK and used `sdkmanager` to install the things I thought I needed (platform-tools, build-tools, etc.). The message above just says I need "command line tools" and links to the Android Studio install page.

What was actually missing is the `platform` package, which I installed using `sdkmanager "platforms;android-26"`.

I remember having similar confusion on Windows; it wasn't obvious what I still needed to install. It would be great if "command line tools" in the message could be extended to be more specific about what's missing. Since Android Studio isn't the only flutter IDE it should be easy for someone that doesn't want to install it to get set up.

**Comment by ice1000** [comment]
Same. On Ubuntu 16.04.

**Comment by samayo** [comment]
Same problem. God, can't anything work out of the box anymore

**Comment by samayo** [comment]
@DanTup  How did you end up installing the missing library?

**Comment by DanTup** [comment]
@samayo It's been a while now, but in the OP I wrote:

> What was actually missing is the `platform` package, which I installed using `sdkmanager "platforms;android-26"`.

I believe that last part was the exact command; though it's possible I'd already installed some of the other packages too. If you run `sdkmanager --list` it'll show you all the packages both installed and available. Here's my installed section (note: the `Path` column gets truncated and apparently there's no way to fix that!)

```text
Dannys-MacBook:~ danny$ sdkmanager --list
Installed packages:
  Path                              | Version | Description                       | Location                         
  -------                           | ------- | -------                           | -------                          
  build-tools;25.0.3                | 25.0.3  | Android SDK Build-Tools 25.0.3    | build-tools/25.0.3/              
  build-tools;26.0.0                | 26.0.0  | Android SDK Build-Tools 26        | build-tools/26.0.0/              
  emulator                          | 26.1.3  | Android Emulator                  | emulator/                        
  patcher;v4                        | 1       | SDK Patch Applier v4              | patcher/v4/                      
  platform-tools                    | 26.0.0  | Android SDK Platform-Tools        | platform-tools/                  
  platforms;android-25              | 3       | Android SDK Platform 25           | platforms/android-25/            
  platforms;android-26              | 2       | Android SDK Platform 26           | platforms/android-26/            
  system-images;a...google_apis;x86 | 5       | Google APIs Intel x86 Atom Sys... | system-images/a...oogle_apis/x86/
  tools                             | 26.0.2  | Android SDK Tools                 | tools/              
```

HTH!

**Comment by imtusharrai** [comment]
Android toolchain - develop for Android devices $ANDROID_HOME to that location.?[0m0)
                                                                                                                                                                             
[√] Flutter (on Microsoft Windows [Version 10.0.16299.248], locale en-IN, channel dev)

**Comment by samayo** [comment]
Can't believe anyone bothers to use this library. I tried to make it work for three weeks and finally decided to let it go. Installing this library and writting basic hello world almost gave me a stroke.

**Comment by mikolajpp** [comment]
This issue can be resolved by installing standard android SDK via android-studio on linux. 

Linux distributions of android-sdk are missing many required files, such as build.prop and others.

**Comment by mikolajpp** [comment]
Using the newest android-sdk available on Archlinux you can easily setup the environment:
```
venus% ANDROID_HOME=~/Android/ bin/flutter doctor                   
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v0.1.8-pre.24, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] Android Studio (version 3.0)
[✓] IntelliJ IDEA Community Edition (version 2017.3)
```

**Comment by mikolajpp** [comment]
That's true, but it is some solution for now :-)
There is another thread about improving error messages, which could lead to some improvements in this area, see #15017

**Comment by zoechi** [comment]
@mholtman the flutter travis scripts installs it using `sdkmanager`, you can look it up there (if I correctly understand your question)

**Comment by DanTup** [comment]
> the flutter travis scripts installs it using sdkmanager, you can look it up there (if I correctly understand your question)

Oh wow, why didn't I think of this? I spent ages trying to figure out which packages to install to get things working, but they're all listed in the CI scripts!

https://github.com/flutter/flutter/blob/master/dev/bots/travis_setup.sh

Thanks! :D

**Comment by mholtman** [comment]
@zoechi That was exactly what I was looking for. Thank you very much!

**Comment by solarkraft** [comment]
Linux: Downloaded Android Studio, ran it once, Flutter doctor complains about licenses and forwards me right to accepting them. That's convenient. 
Knowing I had to do it wasn't.

**Comment by ravernkoh** [comment]
I am running ArchLinux 4.16. I have installed the `android-studio` and `flutter` package from the AUR however I am still running into the error for the lack of command-line tools. Checking the SDK folder it does indeed contain the `sdkmanager` and other tools.
```
[✓] Flutter (Channel beta, v0.2.8, on Linux, locale en_US.UTF-8)
    • Flutter version 0.2.8 at /opt/flutter
    • Framework revision b397406561 (4 weeks ago), 2018-04-02 13:53:20 -0700
    • Engine revision c903c217a1
    • Dart version 2.0.0-dev.43.0.flutter-52afcba357

[!] Android toolchain - develop for Android devices
    • Android SDK at /home/ravern/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    ✗ Android SDK is missing command line tools; download from https://goo.gl/XxQghQ
    • Try re-installing or updating your Android SDK,
      visit https://flutter.io/setup/#android-setup for detailed instructions.

[✓] Android Studio (version 3.1)
    • Android Studio at /opt/android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[!] Connected devices
    ! No devices available

! Doctor found issues in 2 categories.
```

**Comment by DanTup** [comment]
@ravernkoh This looks like the same issue described in the top post; did you try the command that fixed it for me?

> What was actually missing is the platform package, which I installed using `sdkmanager "platforms;android-26"`

**Comment by ChetanAudipudy** [comment]
@bobfourie I'm having this same issue, I have my sdk installed in a different drive. how do I go about changing the env var to point to a new location?

**Comment by bobfourie** [comment]
@ChetanAudipudy For windows 10 , the easiest way is just to hit the Start button and search for "enviro..", it should show "Edit the system environment variables"
[https://superuser.com/questions/949560/how-do-i-set-system-environment-variables-in-windows-10](url)

**Comment by HaLuZaR** [comment]
Haha FLUTTER, WHAT BULLSHIT.... JUST ERRORS... just dont use this shitty framework or what it is.

**Comment by etznap** [comment]
The problem is , are the variables, in my case, i use archlinux + androidstudio(AUR) + flutter (AUR), i got same problem and the solution for my case was, adding the next lines to the .bashrc file:

export ANDROID_HOME=/home/{user}/Android/Sdk
export PATH=/home/{user}/Android/Sdk:$PATH
export PATH=/home/{user}/Android/Sdk/platform-tools:$PATH
export PATH=/home/{user}/Android/Sdk/tools:$PATH
export PATH=/home/{user}/Android/ndk-build:$PATH

replace {user} with your system user.

My problem was, that i was mixing standalone packages , so i uninstalled android-sdk and stuff from AUR, and manage everything from android studio, and it works well. In fact the "    • Android NDK location not configured (optional; useful for native profiling support) " message is fixing by installing from android studio also.

Hope it helps, greetins from Mexico

**Comment by zoeyfan** [comment]
@DanTup, I am triaging our bug database, and found this from 2017. Is this still relevant? I don't recall seeing it in latest build. If you agree, please close it.

**Comment by DanTup** [comment]
Looks like the message was improved in https://github.com/flutter/flutter/pull/23884. Thanks!

**Comment by SETSinsperion** [comment]
Greetings and have a great day, if you're facing the problem in 2021 "cmdline-tools component is missing" upgrading Flutter in Linux I follow the next steps:
1. Make sure you have the Android SDK paths "/tools" and "/platform-tools in your PATH environment variable.
2. Start the Android Studio SDK Manager and follow the steps to install the latest version of "Android SDK CommandLine Tools" https://stackoverflow.com/a/64162776
#HappyCoding
