### ISSUE TITLE
Remove single window assumption from SceneBuilder

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#112202]
The Scene created by the SceneBuilder has a single window assumption backed in:

https://github.com/flutter/engine/blob/9a830e011cb92565b55aac3d1e03ee1c1da835f6/lib/ui/compositing/scene.cc#L40-L44

In the code above it grabs the first window and reads the physical size and device pixel ratio of it. In the multi window world, we will need to create Scenes for multiple different windows, so that assumption has to go.

Ideas:
1) The physical size and device pixel ratio are injected into the Scene when it is rendered into a specific FlutterView by passing it to `FlutterView.render`. At that point, it is clear to what FlutterView the scene belongs and the values can be read of that view.
2) The SceneBuilder provides an option to configure the physical size and the dpr for the Scene (either by providing setters or by taking these values as arguments to `SceneBuilder.build`).

If we go down route 2, we should make these parameters optional first and default them to the values read from the first window. Then, once the framework has been migrated to set these parameters based on the view the scene is gonna be rendered into, the parameters should become required and the single window assumption is removed from the Scene.

**Comment by goderbauer** [comment]
Another option would be to just take the FlutterView as an argument to SceneBuilder.build as in "build the scene for this FlutterView".

**Comment by a-wallen** [comment]
After trying approach 1, I've decided to take approach 2. If the Scene is built without the assumption that there is a single window, `toImageSync` and `toImage` may be called without the `Scene`'s layer tree having any viewport metrics.

**Comment by jonahwilliams** [comment]
> Another option would be to just take the FlutterView as an argument to SceneBuilder.build as in "build the scene for this FlutterView".

I commented on the PR too, but I don't think this makes sense. Scenes can also be "built" and converted to textures that are not attached to any particular window. See: https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/rendering/layer.dart#L1428-L1505

**Comment by dkwingsmt** [comment]
> Scenes can also be "built" and converted to textures that are not attached to any particular window.

I've been exploring this option, but I found out that, although `toImage` and `toImageSync` does not use the size of the window, they do use the pixel ratio of the window. Both methods eventually call `LayerTree::Flatten`, which uses the dimension passed in (which are the width and height from `toImage`/`toImageSync`) as well as the pixel ratio of the layer tree (which is the pixel ratio of window 0).

I still like this idea though, and I think it's better to add a `pixelRatio` parameter to `toImage`/`toImageSync`. However, we still need to keep the current behavior by using window 0's pixel ratio by default, even though in a multi-view Flutter app window 0 might not exist.

My current plan is that upon app start, we record the pixel ratio of window 0, and use it as the default pixel ratio forever, even after window 0 is destroyed.

**Comment by jonahwilliams** [comment]
Scene.toImage already accepts a pixel ratio argument.

**Comment by dkwingsmt** [comment]
Uhh, I don't see it here? https://github.com/flutter/engine/blob/main/lib/ui/compositing.dart#L47

**Comment by jonahwilliams** [comment]
Look in the framework wrappers of this code

**Comment by jonahwilliams** [comment]
lib/src/rendering/layer.dart

**Comment by dkwingsmt** [comment]
The document for `toImage`/`toImageSync` says
```
  /// The [pixelRatio] describes the scale between the logical pixels and the
  /// size of the output image. It is independent of the
  /// [dart:ui.FlutterView.devicePixelRatio] for the device, so specifying 1.0
  /// (the default) will give you a 1:1 mapping between logical pixels and the
  /// output pixels in the image.
```

Meanwhile, the pixel ratio in `Flatten` and `Preroll` are `device_pixel_ratio`. It seems to me that they are not the same.
