### ISSUE TITLE
[iOS] TabBar is not tappable

### ISSUE THREAD

**Issue by ollydixon** [flutter/flutter#112295]
`Flutter 3.3.1 • channel stable`

Test users are reporting a bug that they cannot tap the TabBar on iOS.

Testing on MacOS, Web & Android users can tap the tab bar.

The code looks like so:

```
return Scaffold(
      body: Column(
        mainAxisSize: MainAxisSize.min,
        children: <Widget>[
          TabBar(
            controller: _tabController,
            tabs: [
              Tab(text: lang.list),
              Tab(text: lang.addEdit),
            ],
          ),
          Flexible(
            child: TabBarView(
              controller: _tabController,
              children: [
                Text("test),
                Text("test),
              ],
            ),
          ),
        ],
      ),
    );
```

It's expected that users can tap the tab bar and it changes index.

Also "onTap" property for the tabbar no longer works.

**Comment by ollydixon** [comment]
I found the bug.

Having 2 Scaffolds in the widget tree breaks some widgets on iOS.

**Comment by darshankawar** [comment]
@ollydixon 
Can you provide a runnable code sample with 2 Scaffolds that we can use which shows the error you are reporting ?
