### ISSUE TITLE
Severe regressions in start-up, memory and hot reload w/engine roll to 431a251

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#11220]
Roll https://github.com/flutter/flutter/pull/11157 seems to have caused pretty bad regressions on many metrics, with the most severe being app start-up time now pretty consistently exceeding 1 second, which was mostly <700ms. The benchmark is flaky, but I also ran on my personal phone and noticing start-up slowness.

This benchmark is temporarily disabled on iOS, so this is observed on Android only.

@rmacnak-google

**Comment by tvolkert** [comment]
There are 18 commits to the engine repo included in that roll:

```
d2d152f20 Fix a11y scroll direction (#3841)
f0c3ebfb8 Send text input action events on Fuchsia (#3843)
9d6d69fe1 GN: Use a depfile when generating the core snapshot. (#3844)
8d5372a82 Do not try to apply selections outside the length of the text (#3845)
2062ca14e Avoid spurious descheduling when posting message loop tasks. (#3812)
66fbebaca Changes to get the profiler working for C code on Android. (#3847)
eb467a8b8 Don't enable_profiling for x86 Android. (#3848)
db8241ed0 [content handler] Use the non-deprecated name for ioctl_vfs_watch_dir (#3849)
89d16cc4a Use Dart_Closure instead of looking up _getMainClosure (#3850)
9117705b3 Roll Dart to 1bfd01c1f7a57fed039ce8ab95df2a5f14cf63b6 (#3852)
f02133b5f Rename licenses README to get nice formatting on Github (#3853)
130aecefa [content_handler] Silence mx::object::get_address() deprecation warning (#3854)
a4fa55884 [fuchsia] Be less specific about location of flutter_runner in flutter_app template (#3855)
d67b614a2 Allow SIGQUIT to toggle the vm-service server a la command line Dart. (#3857)
dd634d349 Revert "Allow SIGQUIT to toggle the vm-service server a la command line Dart. (#3857)" (#3859)
456d746eb Do not enter text for key events that are not associated with a character (#3860)
98807038a [content handler] Fix waiting for GPU. (#3858)
431a25115 Revert "Avoid spurious descheduling when posting message loop tasks. (#3812)" (#3862)
```

**Comment by tvolkert** [comment]
Just looking at that list, the most likely culprit is:

```
9117705b3 Roll Dart to 1bfd01c1f7a57fed039ce8ab95df2a5f14cf63b6 (#3852)
```

**Comment by tvolkert** [comment]
In turn, there were 109 commits to Dart in that range.

https://gist.github.com/tvolkert/236bf030bd2e0c7dd7e966c5fb70e26c

@rmacnak-google can you have a look?

**Comment by jason-simmons** [comment]
Some of this may be due to the introduction of the profiler:
    https://github.com/flutter/engine/commit/66fbebaca3a7bae3fe957c4c829009330a412082

**Comment by Hixie** [comment]
I think we should revert this Dart roll for now.

**Comment by aam** [comment]
Regarding "introduction of the profiler" hypothesis - commenting out "gn_args['enable_profiling'] = args.runtime_mode != 'release'" from tools/gn(effectively disabling profiler) improves 
timeToFirstFrameMicros for flutter_gallery__start_up on my local Pixel device by ~10%:

with 'enable_profiling'
  "timeToFirstFrameMicros": 718683
  "timeToFirstFrameMicros": 636159,
  "timeToFirstFrameMicros": 669369,
  "timeToFirstFrameMicros": 698522

without enable_profiling:
  "timeToFirstFrameMicros": 641075,
  "timeToFirstFrameMicros": 607830,
  "timeToFirstFrameMicros": 620167,

**Comment by Hixie** [comment]
It's not just making it slower, it also making it significantly more noisy, which is a problem.

**Comment by a-siva** [comment]
I believe all the regressions have been addressed, can this be closed?
