### ISSUE TITLE
Flutter App Crash on new Xcode 14.0 and iOS 16

### ISSUE THREAD

**Issue by RoyalCoder88** [flutter/flutter#112233]
Hi friends,

Before I used Xcode 13.4.1 no problems, after upgrade to xCode 14.0, my app crashes after build, I don't know why :( I get these errors:
```
UnityFramework`::InitializeMemory():
    0x10ce33f08 <+0>:   stp    x20, x19, [sp, #-0x20]!
    0x10ce33f0c <+4>:   stp    x29, x30, [sp, #0x10]
    0x10ce33f10 <+8>:   add    x29, sp, #0x10
    0x10ce33f14 <+12>:  adrp   x8, 7435
    0x10ce33f18 <+16>:  add    x8, x8, #0xa28            ; guard variable for MemoryManager::InitializeMemory()::s_initializeMemory
    0x10ce33f1c <+20>:  ldarb  w8, [x8]
    0x10ce33f20 <+24>:  tbz    w8, #0x0, 0x10ce33f88     ; <+128> at MemoryManager.cpp:528:5
    0x10ce33f24 <+28>:  adrp   x0, 7435
    0x10ce33f28 <+32>:  add    x0, x0, #0x9e0            ; MemoryManager::InitializeMemory()::s_initializeMemory
    0x10ce33f2c <+36>:  bl     0x10d3f14c4               ; ::Lock() at Mutex.cpp:61:5
    0x10ce33f30 <+40>:  adrp   x19, 7589
    0x10ce33f34 <+44>:  ldr    x8, [x19, #0xa40]
    0x10ce33f38 <+48>:  cbnz   x8, 0x10ce33f70           ; <+104> [inlined] ~AutoLock at Mutex.h:34:31
    0x10ce33f3c <+52>:  adrp   x8, 7324
    0x10ce33f40 <+56>:  ldr    x0, [x8, #0xb18]
    0x10ce33f44 <+60>:  mov    w9, #0x8330
    0x10ce33f48 <+64>:  movk   w9, #0x4, lsl #16
    0x10ce33f4c <+68>:  add    x9, x0, x9
    0x10ce33f50 <+72>:  str    x9, [x8, #0xb18]
    0x10ce33f54 <+76>:  adrp   x8, 7435
    0x10ce33f58 <+80>:  add    x8, x8, #0x9e0            ; MemoryManager::InitializeMemory()::s_initializeMemory
    0x10ce33f5c <+84>:  cmp    x9, x8
    0x10ce33f60 <+88>:  b.hi   0x10ce33ffc               ; <+244> [inlined] ~AutoLock + 20 at Mutex.h
    0x10ce33f64 <+92>:  bl     0x10ce34c4c               ; ::MemoryManager() at MemoryManager.cpp:834
    0x10ce33f68 <+96>:  str    x0, [x19, #0xa40]
    0x10ce33f6c <+100>: bl     0x10ce34008               ; ::InitializeFallback() at MemoryManager.cpp:892
    0x10ce33f70 <+104>: adrp   x0, 7435
    0x10ce33f74 <+108>: add    x0, x0, #0x9e0            ; MemoryManager::InitializeMemory()::s_initializeMemory
    0x10ce33f78 <+112>: bl     0x10d3f14cc               ; ::Unlock() at Mutex.cpp:68:5
    0x10ce33f7c <+116>: ldp    x29, x30, [sp, #0x10]
    0x10ce33f80 <+120>: ldp    x20, x19, [sp], #0x20
    0x10ce33f84 <+124>: ret    
    0x10ce33f88 <+128>: adrp   x0, 7435
    0x10ce33f8c <+132>: add    x0, x0, #0xa28            ; guard variable for MemoryManager::InitializeMemory()::s_initializeMemory
    0x10ce33f90 <+136>: bl     0x10e5c48f0               ; symbol stub for: __cxa_guard_acquire
    0x10ce33f94 <+140>: cbz    w0, 0x10ce33f24           ; <+28> [inlined] AutoLock at Mutex.h:33:59
    0x10ce33f98 <+144>: adrp   x0, 7435
    0x10ce33f9c <+148>: add    x0, x0, #0x9e0            ; MemoryManager::InitializeMemory()::s_initializeMemory
    0x10ce33fa0 <+152>: bl     0x10d3f1474               ; ::Mutex() at Mutex.cpp:46
    0x10ce33fa4 <+156>: adrp   x0, 1470
    0x10ce33fa8 <+160>: add    x0, x0, #0x49c            ; ::~Mutex() at Mutex.cpp:47
    0x10ce33fac <+164>: adrp   x1, 7435
    0x10ce33fb0 <+168>: add    x1, x1, #0x9e0            ; MemoryManager::InitializeMemory()::s_initializeMemory
    0x10ce33fb4 <+172>: adrp   x2, -323
    0x10ce33fb8 <+176>: add    x2, x2, #0x0
    0x10ce33fbc <+180>: bl     0x10e5c48a8               ; symbol stub for: __cxa_atexit
    0x10ce33fc0 <+184>: adrp   x0, 7435
    0x10ce33fc4 <+188>: add    x0, x0, #0xa28            ; guard variable for MemoryManager::InitializeMemory()::s_initializeMemory
    0x10ce33fc8 <+192>: bl     0x10e5c48fc               ; symbol stub for: __cxa_guard_release
    0x10ce33fcc <+196>: b      0x10ce33f24               ; <+28> [inlined] AutoLock at Mutex.h:33:59
    0x10ce33fd0 <+200>: mov    x19, x0
    0x10ce33fd4 <+204>: adrp   x0, 7435
    0x10ce33fd8 <+208>: add    x0, x0, #0xa28            ; guard variable for MemoryManager::InitializeMemory()::s_initializeMemory
    0x10ce33fdc <+212>: bl     0x10e5c48e4               ; symbol stub for: __cxa_guard_abort
    0x10ce33fe0 <+216>: b      0x10ce33ff4               ; <+236> [inlined] ~AutoLock + 12 at Mutex.h
    0x10ce33fe4 <+220>: mov    x19, x0
    0x10ce33fe8 <+224>: adrp   x0, 7435
    0x10ce33fec <+228>: add    x0, x0, #0x9e0            ; MemoryManager::InitializeMemory()::s_initializeMemory
    0x10ce33ff0 <+232>: bl     0x10d3f14cc               ; ::Unlock() at Mutex.cpp:68:5
    0x10ce33ff4 <+236>: mov    x0, x19
    0x10ce33ff8 <+240>: bl     0x10e5c4380               ; symbol stub for: _Unwind_Resume
->  0x10ce33ffc <+244>: brk    #0x1
    0x10ce34000 <+248>: bl     0x10ccfb884               ; __clang_call_terminate
    0x10ce34004 <+252>: bl     0x10ccfb884               ; __clang_call_terminate
```
![Screenshot 2022-09-19 at 22 35 07](https://user-images.githubusercontent.com/6507433/191863032-859d026c-ed20-46ce-91c5-8b7ba25577e8.png)

I'm stuck for 3 days now :( I tried a lot of fixes nothing works :( any guidance, help or suggestions will be much appreciated!

**Comment by danagbemava-nc** [comment]
Hi @RoyalCoder88,

Can you please provide your `flutter doctor -v` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?

Please also provide your `pubspec.yaml`, `Podfile`,  and `Podfile.lock` files.  

Thank you

**Comment by RoyalCoder88** [comment]
Hi @danagbemava-nc 

It's not a particular issue it's a big problem, also on Unity's [forum](https://forum.unity.com/forums/ios-and-tvos.27/)

Regarding my project here you go:
------------------------------------------------------------------------------------------------------------------------------------------
**flutter doctor:**

> [✓] Flutter (Channel stable, 3.3.1, on macOS 12.6 21G115 darwin-arm, locale en-GB)
    • Flutter version 3.3.1 on channel stable at /Users/razvanu/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4f9d92fbbd (3 weeks ago), 2022-09-06 17:54:53 -0700
    • Engine revision 3efdf03e73
    • Dart version 2.18.0
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/razvanu/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode-14.1.0-Beta.2.app/Contents/Developer
    • Build 14B5024i
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.71.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (2 available)
    • Buraca’s iPhone (mobile) • 00008110-001645D43C8A801E • ios            • iOS 16.0 20A362
    • Chrome (web)             • chrome                    • web-javascript • Google Chrome 105.0.5195.125

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
------------------------------------------------------------------------------------------------------------------------------------------
**flutter run --verbose:**
[verbose.txt](https://github.com/flutter/flutter/files/9638921/verbose.txt)

------------------------------------------------------------------------------------------------------------------------------------------
**sample code:**
[sampleCode_Main.txt](https://github.com/flutter/flutter/files/9638937/sampleCode_Main.txt)

------------------------------------------------------------------------------------------------------------------------------------------
**pubspec.yaml:**
[pubspec.yaml.txt](https://github.com/flutter/flutter/files/9638944/pubspec.yaml.txt)

------------------------------------------------------------------------------------------------------------------------------------------
**Podfile:**
[Podfile.txt](https://github.com/flutter/flutter/files/9638946/Podfile.txt)

------------------------------------------------------------------------------------------------------------------------------------------
**Podfile.lock:**
[Podfile.lock.txt](https://github.com/flutter/flutter/files/9638949/Podfile.lock.txt)

Thanks in advance!

**Comment by danagbemava-nc** [comment]
Hi @RoyalCoder88, given that this issue is coming from `Unity` I'm not sure there's anything for the flutter team to do with regards to this. 

As such I'm going to have to close this issue as this is not a flutter issue. 

Thank you
