### ISSUE TITLE
[Impeller] Migrate the Embedder API to use Impeller.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#112230]
Migrating to Impeller will not change the public Embedder API in any way. But, Impeller needs to be wired up as a backend.

**Comment by chinmaygarde** [comment]
From the Impeller Weekly sync: This would also allow us to use the embedder test harnesses on Mac as Impeller smoke tests. Elevating priority and assigning.

**Comment by chinmaygarde** [comment]
Making good progress on this. Should land this for Metal this week.

**Comment by jmagman** [comment]
@chinmaygarde I see you unassigned yourself, did you have any updates about this?  It's a blocker for https://github.com/flutter/flutter/issues/112232.

**Comment by chinmaygarde** [comment]
I think I messed up the priorities. Will put this back on the docket for January.

Re. https://github.com/flutter/flutter/issues/112232, the Impeller migration will not affect the embedder API. So you should be able to complete the switch of iOS to that API without the Impeller transition getting in the way. When Impeller becomes the default however, this will definitely be a blocker. We'll have this issue sorted well before then hopefully.

I'm curious how you're orchestrating the migration in https://github.com/flutter/flutter/issues/112232. I expect a temporary shim to allow you to swap between the Embedder API and the current embeddings. But, I could be mistaken. Happy to have a call with @cyanglaz and others with sort it out.

**Comment by cyanglaz** [comment]
> I'm curious how you're orchestrating the migration in #112232. I expect a temporary shim to allow you to swap between the Embedder API and the current embeddings.

Yes, it will be something similar to how we enable impeller. I'm going to prepare a doc for the migration and I'd be appreciate to have a call to sort it out after the initial draft doc is ready.

**Comment by chinmaygarde** [comment]
Sounds good. Let's have a quick sync when you are done with the doc.

**Comment by chinmaygarde** [comment]
This was completed by @jonahwilliams and the desktop embedder on macOS is already using it and is ready for preview.

**Comment by jonahwilliams** [comment]
Technically we don't support opting into impeller if you select kSoftware or kVulkan.
