### ISSUE TITLE
Move updateSemantics from PlatformDispatcher to FlutterView

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#112221]
In a multi view world we will be creating separate semantics trees for each view. For this, the `updateSemantics` should move from the singleton `PlatformDispatcher` to the individual `FlutterView`s. 

Once the framework has been moved over, the old `updateSemantics` on the PlatfromDispatcher can be removed.

**Comment by a-wallen** [comment]
@goderbauer what do you think the tests should look like for this?

**Comment by goderbauer** [comment]
Do we have any tests covering PlatformDispatcher.updateSemantics? Those could be re-purposed, but with calling FlutterView.updateSemantics instead.

I think ultimately, you want a test to ensure that any information passed to FlutterView.updateSemantics is forwarded properly to the embedder API and invokes the expected callbacks there, e.g. https://github.com/flutter/engine/blob/966f249fb132df0f91d326c022adaa0f8d52dd77/shell/platform/embedder/embedder.h#L1740

**Comment by a-wallen** [comment]
Reopening as https://github.com/flutter/engine/pull/37388 reverted the issue that closed this.
