### ISSUE TITLE
Investigate missing dev mode switch on iphone11

### ISSUE THREAD

**Issue by yusuf-goog** [flutter/flutter#112224]
The iphone11 (https://github.com/flutter/flutter/issues/111131) we added to mac-4 is not in dev mode, and is missing the expected Dev mode switch under System Preferences > Privacy & Security.

**Comment by yusuf-goog** [comment]
The developer profile seems to have been setup correctly for the device.

**Comment by yusuf-goog** [comment]
Checking another of our iphone11 devices, and its missing the option as well. It just got a new iOS update, applying that to see if it resolves the issue.

Also installing xcode on mac-4 to see if it detects the issue on the connected device, and possibly has some option to enable the dev mode button.

**Comment by yusuf-goog** [comment]
Xcode on mac-4 detects the device and presents warning to enable Developer mode on it. There are not actions that can be taken from xcode.

**Comment by yusuf-goog** [comment]
@jmagman

**Comment by yusuf-goog** [comment]
updated the other iphone11 to 16.0.2 and still don't see the dev mode option.

**Comment by jmagman** [comment]
What "developer profile" did you set up? I don't think my iOS test devices that are working have any profiles installed.

**Comment by yusuf-goog** [comment]
I used, "match Development *" which is type: Development.

**Comment by yusuf-goog** [comment]
The other iphone11 doesn't have any profile installed

**Comment by jmagman** [comment]
@yusuf-goog gave me an iPhone 11, which was running on iOS 15 something.  I updated to 16.0.2, and I see Developer Mode in Privacy and Security. I turned it on, Xcode seems happy.
<img src="https://user-images.githubusercontent.com/682784/191879131-204dc75c-3c77-4770-a3b1-4a2fa49cc43e.png" width=500>

**Comment by yusuf-goog** [comment]
Looks like the process for ios 16 devices is to:

- connect device to a mac host
- select "Trust"
- then get out and go back into Settings > Privacy & Security and you see the button appear.
- turn dev mode on, it will ask to restart the device.
- after restart there will be another dialog that asks you to turn dev mode on.
