### ISSUE TITLE
[video_player] Huawei devices (still) play .webm videos at 1/4 of screen width

### ISSUE THREAD

**Issue by Kallirroi** [flutter/flutter#112200]
I know https://github.com/flutter/flutter/issues/62783 exists already, but it looks like it was closed without being addressed (plus a bit old right now) so I'm opening a new issue.  Basically exactly same problem as you see below.

Using `video_player: ^2.4.7` for rendering videos. 

Thanks!

<img width="1044" alt="Screen Shot 2022-09-22 at 6 54 16 PM" src="https://user-images.githubusercontent.com/10440556/191806797-97b18d71-b0d0-4aac-a725-2b67f73ee062.png">

<details>
<summary>Code sample</summary>
<pre>
<code>
ValueListenableBuilder(
  valueListenable: controller!,
  builder: (
    BuildContext context,
    VideoPlayerValue videoResult,
    Widget? child,
  ) {
    return Stack(
      alignment: Alignment.bottomCenter,
      children: <Widget>[
        // * Video
        GestureDetector(
          onTap: () {
            setState(() => _showPlayButton = !_showPlayButton);
            Future.delayed(
              defaultTransitionDuration,
              () => handleVideoTap(),
            );
          },
          child: videoResult.isInitialized
              ? VideoPlayer(controller!)
              : const Center(child: CircularProgressIndicator()),
        ),
        // * Scrubber
        if (videoResult.isInitialized)
          VideoProgressIndicator(
            controller!,
            allowScrubbing: true,
            padding: const EdgeInsets.only(bottom: 32.0),
          ),
      ],
    );
  },
),
</code>
</pre>
</details>

<details>
  <summary>flutter doctor -v</summary>
<pre>
<code>
[✓] Flutter (Channel stable, 2.10.3, on macOS 12.6 21G115 darwin-x64, locale en-CA)
    • Flutter version 2.10.3 at /usr/local/flutter
    • Upstream repository git@github.com:flutter/flutter.git
    • Framework revision 7e9793dee1 (7 months ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/[redacted]/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/redacted]/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] IntelliJ IDEA Community Edition (version 2021.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin version 212.5284.31

[✓] VS Code (version 1.71.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (2 available)
    • LYA L29 (mobile) • LHS7N19109000817 • android-arm64  • Android 10 (API 29)
    • Chrome (web)     • chrome           • web-javascript • Google Chrome 105.0.5195.125

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
</pre>
</code>
</details>

**Comment by woodybury** [comment]
+ 1 for this. same issue w/ small video and green background for webm

**Comment by huycozy** [comment]
Hi @Kallirroi
Please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this. Also, please provide the output of `flutter run -v` as well. If the log is too long, please save it into a file and attach it here.

As far as I can see, you are using the old Flutter version `2.10.3`, the latest Flutter stable is `3.3.2` and the master is `3.4.0`. Please try upgrading them and retry to see if this issue still reproduces.

Thank you!

**Comment by woodybury** [comment]
thanks @huycozy I just tried updating to 3.3.2 and my `.webm` are still rendered same as @Kallirroi screenshot. Will work on a better code sample.

**Comment by huycozy** [comment]
@woodybury Please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this. Also, please provide the output of `flutter doctor -v` as well. Thank you!
