### ISSUE TITLE
Update ICU library dependency

### ISSUE THREAD

**Issue by filmil** [flutter/flutter#112227]
## Use case

Keeps the ICU library dependency up with the times.

Similar to the last one that I did, see here: https://github.com/flutter/flutter/issues/105342

## Proposal

I wil update the ICU library version noted in the DEPS file, and deal with the licensing.

Please assign me to the issue.

This time around, the update will need to happen in two steps, to ensure we have builds of Flutter engine with several interesting commit IDs for the ICU library.

**Comment by pablojimpas** [comment]
ICU4X 1.0 has been released: https://blog.unicode.org/2022/09/announcing-icu4x-10.html

Will it be considered for a future version of Flutter?

**Comment by dnfield** [comment]
> ICU4X 1.0 has been released: https://blog.unicode.org/2022/09/announcing-icu4x-10.html
> 
> Will it be considered for a future version of Flutter?

Yes. I think we should open a dedicated bug for that though.
