### ISSUE TITLE
[Windows] TextField() can't enter text after regaining focus in Windows program.

### ISSUE THREAD

**Issue by wxw-9527** [flutter/flutter#112259]
## Steps to Reproduce

1. Add a ` TextField() `to the page. Text can be entered normally using the keyboard. 
2. Then switch to another program, But don't close the Flutter program.
3. Switch back to the Flutter program, `TextField()` cannot continue to use the keyboard to enter text.

**Comment by danagbemava-nc** [comment]
Hi @wxw-9527, please provide the output of `flutter doctor -v`. 

Can you also share a recording that captures this issue?

Please also provide the code sample that you reproduce this issue with. 

I attempted to reproduce this but it doesn't reproduce for me.

<details>
<summary>recording</summary>

https://user-images.githubusercontent.com/88313112/191950521-f3d2fc63-684d-45ff-ad9a-0078e487cbca.mp4

</details>

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const SimpleSample());
}

class SimpleSample extends StatelessWidget {
  const SimpleSample({Key? key}) : super(key: key);
  @override
  Widget build(BuildContext context) {
    return MaterialApp(theme: ThemeData(), home: const PopupView());
  }
}

class PopupView extends StatefulWidget {
  const PopupView({Key? key}) : super(key: key);

  @override
  State<PopupView> createState() => _PopupViewState();
}

class _PopupViewState extends State<PopupView> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(child: TextField(),)
    );
  }
}
```
</details>

**Comment by wxw-9527** [comment]
I am very sorry that it was my mistake. 
When I disable windows title bar, removed a line of code `SetWindowLongPtr(window, GWLP_USERDATA, reinterpret_cast<LONG_PTR>(window_struct->lpCreateParams))` in `win32_window.cpp`.
