### ISSUE TITLE
[web] - Cache not clearing after update

### ISSUE THREAD

**Issue by Macacoazul01** [flutter/flutter#112236]
I don't if there's a way to do so or if i'm having a bug on my app, but after i update the version on pubspec.yaml, like:

from: `version: 1.0.0+1`
to: `version: 1.0.1+2`

The browser doesn't see this site as a new one, so it keeps the old cache, creating some bugs on the app (if something that is a breaking change was implemented). Is there a way of forcing the browser to clean the cache after an update?

my doctor:
```
[√] Flutter (Channel stable, 3.3.2, on Microsoft Windows [versao 10.0.22000.978], locale pt-BR)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2021.2)
[√] VS Code (version 1.71.2)
[√] Connected device (3 available)
[√] HTTP Host Availability

! Doctor found issues in 1 category.
```

**Comment by danagbemava-nc** [comment]
Hi @Macacoazul01, this is currently not supported but there's a feature request to add this feature being tracked in https://github.com/flutter/flutter/issues/63500. 

Kindly follow up in the issue linked for updates. 

Closing from here as duplicate. 

Thank you
