### ISSUE TITLE
[google_sign_in_web] Migrate from Google Sign-In to Google Identity Services

### ISSUE THREAD

**Issue by Ones-and-zeroz** [flutter/flutter#112282]
## Use case
My flutter web app uses the 'google_sign_in' package to authenticate the users. I received an email telling me to migrate to the new Google Identity Services (GIS) before March 31, 2023. The 'google_sign_in' package must update for GIS. There is nothing to do but wait for the package to update.

**Comment by Ones-and-zeroz** [comment]
https://github.com/flutter/flutter/issues/88084#issuecomment-1203372174

**Comment by darshankawar** [comment]
@Ones-and-zeroz 
I think it's better to follow-up in the original issue for tracking properly, as Flutter team member already said he is actively working on migration: https://github.com/flutter/flutter/issues/88084#issuecomment-1245848862

Please follow-up in same issue for further updates.
