### ISSUE TITLE
Allow ShellRoute in a ShellRoute

### ISSUE THREAD

**Issue by jopmiddelkamp** [flutter/flutter#112220]
## Use case

I'm trying to setup an app with a shell for a BottomNavigationBar (Shell 1). Then the page of the first tab of this navigation bar should contain a TabBar (Shell 2).

<img width="391" alt="image" src="https://user-images.githubusercontent.com/1774351/191839039-bcf6163d-46e8-4528-b079-e99d32f461ad.png">

## Proposal

Add support for a ShellRoute as child of a ShellRoute.

<img width="572" alt="image" src="https://user-images.githubusercontent.com/1774351/191838716-790671dc-3a93-47af-9dad-6191b85281f4.png">

**Comment by huycozy** [comment]
Hi @jopmiddelkamp, thanks for filing the issue. 
I see there's an open issue addressing the case you described #111981 that has been completed recently and is available on `go_router: ^5.0.1` (https://pub.dev/packages/go_router/changelog)
Closing the issue as a duplicate. Thank you!
