### ISSUE TITLE
[Impeller] Remove TargetPlatform::kFlutterSPIRV in the shader compiler.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#112241]
This was necessary when we had a runtime conversion from SPIRV to SKSL in the engine. But now, ImpellerC can generated SKSL directly. So [there is no need to have this path](https://github.com/flutter/engine/blob/174a6b2429229844ff2477b827e399e8e23f6b8a/impeller/compiler/compiler.cc#L309) which has optimizations disabled due to the incorrect OpPhi handling.

We should remove this and [also enable optimizations](https://github.com/flutter/engine/blob/174a6b2429229844ff2477b827e399e8e23f6b8a/impeller/compiler/compiler.cc#L325) in the generated SKSL that seem to be disabled for no reason even now.

**Comment by chinmaygarde** [comment]
cc @zanderso @dnfield @jonahwilliams. We should be able to get rid of this option and enabled SKSL optimizations now that we have an SKSL path right?

**Comment by jonahwilliams** [comment]
Yes, all of the tooling paths are converted to provided SkSL now.

**Comment by zanderso** [comment]
Even after this we may still need to play around with the backend options to avoid generating things SkSL doesn't support: https://bugs.chromium.org/p/skia/issues/detail?id=13518.

**Comment by chinmaygarde** [comment]
Roger. Presumably, the SKSL processing at runtime will apply the same optimizations.
