### ISSUE TITLE
Icontheme parameter of Chip Widget not applying for Icons used as avarar

### ISSUE THREAD

**Issue by salpers** [flutter/flutter#112257]
Hi, when providing IconThemeData for a chip widget, the specified style properties are not applied to icons used with the chip widget. 

## Steps to Reproduce

1. Execute `flutter run` on the code sample 

**Expected results:** Icon with the Icontheme applied -> Color of the icon in white.

**Actual results:** Icontheme is not applied -> Icon defaults to black. 
![image](https://user-images.githubusercontent.com/23464191/191911915-dd70aeb4-bf61-4fdb-938a-b3c93808c6f1.png)

<details>
<summary>Code sample</summary>

    import 'package:flutter/material.dart';
    
    void main() {
      runApp(const MyApp());
    }
    
    class MyApp extends StatelessWidget {
      const MyApp({super.key});
    
      @override
      Widget build(BuildContext context) {
        return const MaterialApp(
          title: 'Flutter Demo',
          home: MyHomePage(),
        );
      }
    }
    
    class MyHomePage extends StatefulWidget {
      const MyHomePage({super.key});
    
      @override
      State<MyHomePage> createState() => _MyHomePageState();
    }
    
    class _MyHomePageState extends State<MyHomePage> {
      @override
      Widget build(BuildContext context) {
        return const Scaffold(
          body: Center(
              child: Chip(
            iconTheme: IconThemeData(color: Colors.white),
            avatar: Icon(Icons.error),
            label: Text("test"),
          )),
        );
      }
    }

</details>

<details>
  <summary>Logs</summary>

flutter doctor -v

[√] Flutter (Channel stable, 3.3.2, on Microsoft Windows [Version 10.0.19044.2006], locale de-DE)       
    • Flutter version 3.3.2 on channel stable at C:\Users\sebia\Src\flutter_windows_2.5.3-stable\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e3c29ec00c (9 days ago), 2022-09-14 08:46:55 -0500
    • Engine revision a4ff2c53d8
    • Dart version 2.18.1
    • DevTools version 2.15.0

[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at C:\Users\sebia\AppData\Local\Android\sdk
    • Platform android-32, build-tools 32.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2021.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[√] IntelliJ IDEA Ultimate Edition (version 2021.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2021.2.3
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin version 212.5632

[√] VS Code (version 1.71.1)
    • VS Code at C:\Users\sebia\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (4 available)
    • Pixel 5 (mobile)  • adb-09051FDD400418-Vs3GfS._adb-tls-connect._tcp • android-arm64  • Android 13 (API 33)
    • Windows (desktop) • windows                                         • windows-x64    • Microsoft Windows [Version 10.0.19044.2006]
    • Chrome (web)      • chrome                                          • web-javascript • Google Chrome 105.0.5195.127
    • Edge (web)        • edge                                            • web-javascript • Microsoft Edge 105.0.1343.42

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

</details>

**Comment by chitgyi** [comment]
@salpers because forgot to pass `iconTheme` object to `RawChip` widget 

<img width="492" alt="Screen Shot 2022-09-23 at 4 16 19 PM" src="https://user-images.githubusercontent.com/26025566/191934811-a2e26de5-7197-4427-9494-4ca97d8d0b76.png">

**Comment by exaby73** [comment]
Hi @salpers 
I see there's an open issue addressing the case you described https://github.com/flutter/flutter/issues/111828
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
