### ISSUE TITLE
Camera plugin requesting audio access in web even with enableAudio set to false

### ISSUE THREAD

**Issue by omartinma** [flutter/flutter#112277]
## Steps to Reproduce

1. Set enableAudio to false
2. Debug example in the plugin.

**Expected results:** 

Only camera permission should be requested and not the microphone.

**Actual results:** 

<img width="468" alt="image" src="https://user-images.githubusercontent.com/11978998/191995900-baed994a-d266-4df0-acaf-b826268af122.png">

<details>
<summary>Code sample</summary>

Reproducible on official example https://github.com/flutter/plugins/tree/main/packages/camera/camera/example

</details>

<details>
  <summary>Logs</summary>

```
Not any exception
```

```
Analyzing example...                                                    

   info • Avoid redundant argument values • integration_test/camera_test.dart:165:20 • avoid_redundant_argument_values
   info • Avoid redundant argument values • integration_test/camera_test.dart:220:22 • avoid_redundant_argument_values
   info • Avoid redundant argument values • integration_test/camera_test.dart:252:20 • avoid_redundant_argument_values

3 issues found. (ran in 1.5s)
```

```
[✓] Flutter (Channel stable, 3.3.1, on macOS 12.1 21C52 darwin-arm, locale en-ES)
    • Flutter version 3.3.1 on channel stable at /Users/oscarmartin/fvm/versions/3.3.1
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4f9d92fbbd (2 weeks ago), 2022-09-06 17:54:53 -0700
    • Engine revision 3efdf03e73
    • Dart version 2.18.0
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/oscarmartin/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F100
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.71.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.1 21C52 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 105.0.5195.125

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by abhi-shek2000** [comment]
The user should be able to set permission when availableCameras() function is called.

**Comment by ditman** [comment]
As @abhi-shek2000 said, it seems we're unconditionally requesting all permissions on the `availableCameras` call, here:

https://github.com/flutter/plugins/blob/ded5528fa0224f943f9bd92f25e9ff1260f59490/packages/camera/camera_web/lib/src/camera_web.dart#L98-L111

It seems to me, that we do that so the next `enumerateDevices` call contains more useful information, [see here](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/enumerateDevices#examples).

Passing a boolean with audio enabled or not to enumerateDevices is probably OK! (However, I'm not sure what will happen if the programmer later says: OK, now I want the microphone! That might trigger a second permissions request?)

**Comment by omartinma** [comment]
@ditman good point about the second permission request. 

However, IMO, the developer should decide whether to ask for this permission or not, I mean, they will know in advance if they need it. 

Also, from a user perspective, it will be a bit awkward to be asked for audio permission when there is no need for the context of that application. It seems a bit intrusive from a security point of view as well.

**Comment by ditman** [comment]
> from a user perspective, it will be a bit awkward to be asked for audio permission when there is no need for the context of that application. It seems a bit intrusive from a security point of view as well.

I totally agree, if we want the user to be able to specify "audio yes/no" in the first usage, I think we'll need to modify [the platform interface](https://github.com/flutter/plugins/blob/main/packages/camera/camera_platform_interface/lib/src/platform_interface/camera_platform.dart#L41-L48) so we can pass a camera constraints object there (or a boolean).

A simpler way may be to just never request microphone permissions when enumerating the cameras at all. @omartinma Have you tried setting [this](https://github.com/flutter/plugins/blob/main/packages/camera/camera_web/lib/src/camera_web.dart#L103) to false (or not pass Audio at all) to see if the browser doesn't request camera + microphone permissions?

**Comment by omartinma** [comment]
> @omartinma Have you tried setting [this](https://github.com/flutter/plugins/blob/main/packages/camera/camera_web/lib/src/camera_web.dart#L103) to false (or not pass Audio at all) to see if the browser doesn't request camera + microphone permissions?

I tried setting it to false or not passing the audio at all and I'm still getting the microphone permission popup

**Comment by ditman** [comment]
If it's not the permission request before the device enumeration, this might be the behavior of getUserMedia or enumerateDevices then. I know there's a way to granularly request for permissions with the Permissions API (camera and microphone separately), but the camera plugin doesn't use that. I need to play more with this API in raw JS to say more :/

**Comment by omartinma** [comment]
> If it's not the permission request before the device enumeration, this might be the behavior of getUserMedia or enumerateDevices then. I know there's a way to granularly request for permissions with the Permissions API (camera and microphone separately), but the camera plugin doesn't use that. I need to play more with this API in raw JS to say more :/

I just tried out this example in pure JS and it is not requesting microphone permissions https://usefulangle.com/post/352/javascript-capture-image-from-camera

**Comment by omartinma** [comment]
@ditman  I managed to remove the audio popup from availableCameras. You can check this draft PR [here](https://github.com/flutter/plugins/pull/6533/files).

I'm debugging now because the pop up is now splitter in 2.


https://user-images.githubusercontent.com/11978998/193809347-035177b2-fa6e-48d4-933f-f24bddbf64d3.mov

**Comment by maciejbrzezinski** [comment]
Hello, any updates here?

**Comment by pogorv12** [comment]
Hello! 
I saw that PR was achieved and should be moved to packages now. Could it be expected in the nearest time?

**Comment by maciejbrzezinski** [comment]
I've created a [pull request](https://github.com/flutter/packages/pull/4263) for the issue, @ditman can you have a look?

**Comment by ditman** [comment]
@maciejbrzezinski it's in my list! Apologies for the delay, I'm still catching up with older reviews for web plugins!
