### ISSUE TITLE
Version Solving Failed

### ISSUE THREAD

**Issue by 024x** [flutter/flutter#112339]
Because audio_recorder <0.0.5 requires SDK version >=1.8.0 <2.0.0 and audio_recorder >=0.0.5 <1.0.0 depends on path_provider ^0.4.1, audio_recorder <1.0.0 requires path_provider ^0.4.1.
And because google_fonts >=2.0.0 depends on path_provider ^2.0.0, google_fonts >=2.0.0 is incompatible with audio_recorder <1.0.0.
And because audio_recorder >=0.0.6 depends on file ^5.0.4 and shared_preferences_linux >=2.0.0 depends on file ^6.0.0, one of google_fonts >=2.0.0 or audio_recorder any or shared_preferences_linux >=2.0.0 must be false.
And because utool depends on shared_preferences ^2.0.15 which depends on shared_preferences_linux ^2.0.1, google_fonts >=2.0.0 is incompatible with audio_recorder.
So, because utool depends on both google_fonts ^3.0.1 and audio_recorder any, version solving failed.

i am trying to use latest versions of audio_recorder, path_provider , google_fonts ,shared_preferences

**Comment by stuartmorgan** [comment]
This error message is indicating that the version of `audio_recorder` you are trying to use depends on old versions of common dependencies (path_provider, file), and so isn't compatible with the latest version of other packages. If that's the latest version of `audio_recorder`, then you'll need to contact the developer about updating, or fork it to update the dependencies yourself.

Closing as this is not a Flutter bug.
