### ISSUE TITLE
FTL_LOG statements not showing up on iOS

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#11238]
It looks like since we [stopped forwarding `stdout` to syslog](https://github.com/flutter/engine/pull/3797) on iOS, our `stdout` logging is getting swallowed on iOS.

One very visible manifestation of this is that uncaught Dart exceptions are currently [logged using FTL_LOG](https://fuchsia.googlesource.com/tonic/+/82075233dc0cd23b1c8af5f694eb86dd9bd10f35/logging/dart_error.cc#15), which on iOS just [logs to stderr](https://fuchsia.googlesource.com/ftl/+/c82beba4670d9e88fbd1e4fc38b798ff2ca24ac6/logging.cc#84).  The net result is that uncaught Dart exceptions don't show up anywhere in the logs on iOS.

I have a local patch to FTL that will make FTL_LOG send the logs to `syslog` on iOS.

FYI @abarth @cbracken

**Comment by cbracken** [comment]
+1 to the proposed fix, that'll cover iOS 8-10, but IIRC won't work for iOS 11+. That's a separate issue that we've already got an open issue for (#10602).

**Comment by tvolkert** [comment]
https://fuchsia-review.googlesource.com/#/c/39627/

**Comment by cbracken** [comment]
We're good to close this now, correct?

**Comment by tvolkert** [comment]
The fix has landed in FTL and been rolled into the engine repo.  I was waiting 'til we rolled the engine into Flutter to close this.
