### ISSUE TITLE
[go_router_builder] Make generated enums' parameters case-insensitive

### ISSUE THREAD

**Issue by Ayman-Barghout** [flutter/flutter#112371]
## Use case

It'd be better if all our routes are case insensitive, but that's not the case with generated enum parameters, they default to lower kebab-case, this means if one letter gets capitalized by mistake the user will be greeted with an error page instead of the correct page.

The rest of the URL is case insensitive though since `go_router` and `go_router_builder` generated routes are case-insensitive, so it is a bit suboptimal to have only enums being case sensitive.

## Proposal
Probably allow generated enums to be case-insensitive so it wouldn't matter which letter is capitalized, as long as the URL is correct it points to the corresponding page.

Finally, thank you very much for the great work done on this package!

**Comment by ValentinVignal** [comment]
This could maybe fall under https://github.com/flutter/flutter/issues/112152 ?

**Comment by chunhtai** [comment]
this can be solved by https://github.com/flutter/flutter/issues/110781
