### ISSUE TITLE
Nested Material app breaks flutter web url in navigation

### ISSUE THREAD

**Issue by ivofernandes** [flutter/flutter#112359]
## Steps to Reproduce
1. Create a named route between two different widgets
2. Run in flutter web, navigation should work perfectly at this step
3. Create a nested material route inside the widget of the navigation
4. Now suddenly the child material app overrides the parent material url in the browser

Created this repository to see the bug
https://github.com/ivofernandes/routes

**Expected results:**

As the child material app does not have any navigation and the parent material app has navigation, the child should not mess with the parent navigation

**Actual results:** 
The url of the browser gets to the root url as there is a material app showing the home

This code is enough to test and reproduce the bug
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData.dark().copyWith(primaryColor: Colors.lightGreen),
      onGenerateRoute: (settings) {
        if (settings.name == '/page1')
          return MaterialPageRoute(
            builder: (context) {
              return Page1();
            },
            settings: RouteSettings(name: '/page1'),
          );

        if (settings.name == '/page2')
          return MaterialPageRoute(
            builder: (context) {
              return Page2();
            },
            settings: RouteSettings(name: '/page2'),
          );
      },
      initialRoute: '/page1',
    );
  }
}

class Page1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: SafeArea(
        child: Scaffold(
          body: Column(
            children: [
              const Text('Page1'),
              MaterialButton(
                color: Theme.of(context).primaryColor,
                onPressed: () => Navigator.of(context).pushNamed('/page2'),
                child: Text('Go to page 2'),
              ),
            ],
          ),
        ),
      ),
    );
  }
}

class Page2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return SafeArea(
        child: Scaffold(
          body: Column(
            children: [
              const Text('Page2'),
              MaterialButton(
                color: Theme.of(context).primaryColor,
                onPressed: () => Navigator.of(context).pushNamed('/page1'),
                child: Text('Go to page 1'),
              ),
            ],
          ),
        ),
     
    );
  }
}

```

**Comment by ivofernandes** [comment]
Exactly and if it has a nested material app breaks the navigation url, without a nested material app everything works fine, any idea why?

Maybe a the child material app could look up in the widget tree and as it has no relevant navigation, and the parent actually have some navigation logic, the child material app could just leave the url as it was?

**Comment by iapicca** [comment]
@ivofernandes 
the docs describes the navigator  of a [material app](https://api.flutter.dev/flutter/material/MaterialApp-class.html) as "top level"
what is the use case for nesting it?

**Comment by maRci002** [comment]
Why do you nest a `MaterialApp` inside `MaterialApp`?

Anyway the problem is that `MaterialApp` creates `WidgetsApp` under the hood which creates the root `Navigator` which will set `Navigator.reportsRouteUpdateToEngine` to `true`. Since now you have 3x `Navigator` which tries to report the current url the outcome is unpredictable.

Read the [Navigator.reportsRouteUpdateToEngine](https://api.flutter.dev/flutter/widgets/Navigator/reportsRouteUpdateToEngine.html) documentation:

> If there are multiple navigators in the widget tree, at most one of them can set this property to true (typically, the top-most one created from the [WidgetsApp](https://api.flutter.dev/flutter/widgets/WidgetsApp-class.html)). Otherwise, the web engine may receive multiple route update messages from different navigators and fail to update the URL bar.

**Comment by ivofernandes** [comment]
It's true that there are not a lot of good reasons to have nested material apps, the reason it happened to me is that I copied stuff from a package example, but maybe I should close this issue as it's more matter of curiosity than an issue.

Thanks for the deep explaining about this issue :)
