### ISSUE TITLE
Disable mouse right click on `Draggable`

### ISSUE THREAD

**Issue by bambinoua** [flutter/flutter#112386]
## Use case

I am implementing a feature which allows to place RTC video renderers on videowall using drag&drop. User can take draggable items from outside of videowall or move already dropped items (widgets) inside videowall, i.e. virtually the code of `DropTarget` is:
```dart
Draggable(
  ...
  child: DropTarget(
    ...
  ),
),
```
To remove dropped widget I use `Listener` and mouse right click which calls the context menu with removal action.

The problem is if the user wants to remove the dropped widget from videowall then the `feedback` widget of wrapping `Draggable` is shown before the context menu. And this is certainly no go.

## Proposal
Add a boolean parameter to `Draggable` which will disable D&D mode on mouse right button.

**Comment by exaby73** [comment]
Hello @bambinoua. Thank you for filing this issue. Can you please provide the following information?

- A [complete and minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).
- The output of `flutter doctor -v`

Please provide the information in the form of text. See how to make collapsible sections with Markdown [here](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-collapsed-sections).

**Comment by bambinoua** [comment]
After some experiment I was able to achieve the required result. The example is:
```dart
GestureDetector(
  onSecondaryTapDown: (details) {
    // 1. Use empty callback to disable D&D on mouse right button
    // 2. Call `showMenu` to show context menu
  },
  child: Draggable(
    ...
    child: DropTarget(
      ...
    ),
  ),
),
```
So I think this issue can be closed.
