### ISSUE TITLE
toImageSync change causing render time regressions on impeller

### ISSUE THREAD

**Issue by iskakaushik** [flutter/flutter#112394]
https://github.com/flutter/engine/pull/36365

See examples: https://flutter-flutter-perf.skia.org/e/?begin=1663957159&end=1664003605&keys=Xda3abdce1c48200226b57052b96e48ad&selected=commit%3D31276%26name%3D%252Carch%253Dintel%252Cbranch%253Dmaster%252Cconfig%253Ddefault%252Cdevice_type%253DMoto_G__4_%252Cdevice_version%253Dandroid-24%252Chost_type%253Dlinux%252Csub_result%253Daverage_frame_rasterizer_time_millis%252Ctest%253Dnew_gallery_impeller__transition_perf%252C&xbaroffset=31276

cc: @dnfield

**Comment by iskakaushik** [comment]
https://flutter-flutter-perf.skia.org/e/?begin=1663713613&end=1663774150&keys=X4515258389ce36547a969aafc5545137&num_commits=50&request_type=1&xbaroffset=31206 is another one that regressed.

**Comment by jonahwilliams** [comment]
Before the implementation of toImageSync, the android gallery was not rendering anything during android page transitions. This may not be a regression

**Comment by iskakaushik** [comment]
Got it, given that this is expected. I'll accept the regression. Thanks @jonahwilliams !
