### ISSUE TITLE
[Impeller] Support external textures on iOS.

### ISSUE THREAD

**Issue by ljmatan** [flutter/flutter#112364]
https://pub.dev/packages/camera package output is blank if using impeller engine. 

Minimal example can be found in package README

Flutter doctor: 

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 3.4.0-19.0.pre.192, on macOS 12.0.1 21A559
    darwin-arm64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.71.0)
[✓] VS Code (version 1.72.0-insider)
[✓] Connected device (3 available)
    ! Device emulator-5554 is offline.
[✓] HTTP Host Availability

• No issues found!

Also an issue with [✓] Flutter (Channel master, 3.4.0-30.0.pre.18, on macOS 12.0.1 21A559 darwin-arm64, locale en-GB)

**Comment by ColdPaleLight** [comment]
related issue: https://github.com/flutter/flutter/issues/112365
