### ISSUE TITLE
[assets-for-api-docs] Improve the experience of creating diagrams

### ISSUE THREAD

**Issue by PixelToast** [flutter/flutter#112314]
This is a proposal to significantly change the API for creating diagrams in the [assets-for-api-docs](https://github.com/flutter/assets-for-api-docs) repo. I believe this is a prerequisite for a hot-reloadable diagram viewer (#21034) and generally makes the diagram building experience much better.

cc @gspencergoog

## Background

The process for creating new diagrams today is as follows:

1. Create a widget that implements [DiagramMetadata](https://github.com/flutter/assets-for-api-docs/blob/a57dbd294600c9069a6ad424ff4e83eff25a615d/packages/diagrams/lib/src/diagram_step.dart#L86)
2. Override the `name` getter with the diagram's name
3. Subclass [DiagramStep](https://github.com/flutter/assets-for-api-docs/blob/a57dbd294600c9069a6ad424ff4e83eff25a615d/packages/diagrams/lib/src/diagram_step.dart#L29), using the diagram for the type parameter
4. Add a constructor to initialize `super.controller`
5. Override the `category` getter with the folder name e.g. `material`, `cupertino`, `dart-ui`
6. Override the `diagrams` getter to return a list of diagram widgets
7. Override `generateDiagram` with boilerplate that calls `controller.drawDiagramToFile`
8. Add the DiagramStep to the big list in `packages/diagram_generator/lib/main.dart`

A minimal example looks like:

```dart
class MyDiagram extends StatelessWidget implements DiagramMetadata {
  const MyDiagram({super.key});

  @override
  final String name = 'blue';

  @override
  Widget build(BuildContext context) {
    return Container(
      width: 100,
      height: 100,
      color: Colors.blue,
    );
  }
}

class MyDiagramStep extends DiagramStep<MyDiagram> {
  MyDiagramStep(super.controller);

  @override
  final String category = 'squares';

  @override
  Future<List<MyDiagram>> get diagrams async => const <MyDiagram>[
        MyDiagram(),
      ];

  @override
  Future<File> generateDiagram(MyDiagram diagram) async {
    controller.builder = (BuildContext context) => diagram;
    return controller.drawDiagramToFile(File('${diagram.name}.png'));
  }
}
```

Most diagrams have the exact same implementation of `generateDiagram`, but some animated widgets use it to simulate timed gestures, like `alert_dialog`:

```dart
  @override
  Future<File> generateDiagram(AlertDialogDiagram diagram) async {
    controller.builder = (BuildContext context) => diagram;

    controller.advanceTime();

    final Future<File> result = controller.drawAnimatedDiagramToFiles(
      end: _totalDuration,
      frameRate: 60,
      name: diagram.name,
      category: category,
    );

    await Future<void>.delayed(_pauseDuration);

    final RenderBox target =
        _openDialogKey.currentContext!.findRenderObject()! as RenderBox;
    final Offset targetOffset =
        target.localToGlobal(target.size.center(Offset.zero));
    final TestGesture gesture = await controller.startGesture(targetOffset);
    await Future<void>.delayed(_pauseDuration);
    await gesture.up();

    await Future<void>.delayed(_openDuration + _pauseDuration);

    return result;
  }
```

Each diagram step's `generateDiagram` being responsible for generating a `File` unfortunately means we can't use these animations in a live environment (like a diagram preview app), `DiagramController.startGesture` also depends on `DiagramFlutterBinding` which is incompatible with a live binding.

The above example uses a global `splashKey` to identify widgets in the diagram, this is not good practice and may interfere with diagrams co-existing in the widget tree or being replayed multiple times.

## Proposal

This proposal has a two objectives: Simplify the API and make it compatible with a live binding.

#### Simplify DiagramStep

The first change is to reduce the responsibility of `DiagramStep` by removing `generateDiagram` / `generateDiagrams` and instead letting the properties of each `DiagramMetadata` determine how they are generated.

The new definition of `DiagramStep` and `DiagramMetadata` is as follows:

```dart
// No longer has a type parameter or controller
abstract class DiagramStep {
  String get category;
  Set<DiagramPlatform> get platforms => DiagramPlatform.values.toSet();
  Future<List<DiagramMetadata>> get diagrams;
}

mixin DiagramMetadata on Widget {
  String get name;
  double get frameRate => 60.0;
  Duration? get duration => null;
  Duration get startAt => Duration.zero;

  // The setUp method is called after the widget is built, blocking
  // the diagram from being captured until it finishes. This is
  // mostly used for pre-loading images with `precacheImage`.
  Future<void> setUp(GlobalKey key) async {}
}
```

Only two methods are ever called for diagrams to a file, `drawDiagramToFile` and `drawAnimatedDiagramToFiles`, so instead of `DiagramStep` calling them directly, the diagram generator will call them by itself:

```dart
        // Diagram is animated if it has a duration
        if (diagram.duration != null) {
          await controller.drawAnimatedDiagramToFiles(
            end: diagram.duration!,
            frameRate: diagram.frameRate,
            category: step.category,
            name: diagram.name,
            start: diagram.startAt,
          );
        } else {
          await controller.drawDiagramToFile(
            File('${diagram.name}.png'),
            timestamp: diagram.startAt,
          );
        }
```

The new API reduces the minimal example at the top of this doc to:

```dart
class MyDiagram extends StatelessWidget with DiagramMetadata {
  const MyDiagram({super.key});

  @override
  final String name = 'blue';

  @override
  Widget build(BuildContext context) {
    return Container(
      width: 100,
      height: 100,
      color: Colors.blue,
    );
  }
}

class MyDiagramStep extends DiagramStep {
  @override
  final String category = 'squares';

  @override
  Future<List<MyDiagram>> get diagrams async => const <MyDiagram>[
        MyDiagram(),
      ];
}
```

#### Migrate gestures to widget

Instead of starting gestures in `DiagramStep` with `DiagramController`, we should have diagrams do it themselves initState:

```dart
  // Tap gesture for alert_dialog
  Future<void> startAnimation() async {
    await Future<void>.delayed(_pauseDuration);
    final RenderBox target =
        _openDialogKey.currentContext!.findRenderObject()! as RenderBox;
    final Offset targetOffset =
        target.localToGlobal(target.size.center(Offset.zero));

    // Construct WidgetController directly, we might want to wrap this in
    // an InheritedWidget in case the generator wants to change gesture
    // behavior.
    final WidgetController controller =
        LiveWidgetController(WidgetsBinding.instance);
    final TestGesture gesture = await controller.startGesture(targetOffset);
    await Future<void>.delayed(_pauseDuration);
    await gesture.up();
  }

  @override
  void initState() {
    super.initState();
    startAnimation();
  }
```

Animations would work properly in a live binding, and `GlobalKey`s (`openDialogKey` above) can be private instead of global.

#### Diagram step list

The diagram generator knows what diagrams to build with a massive list in `packages/diagram_generator/lib/main.dart`, we should instead export a global list somewhere in the `diagrams` package:

```dart
final List<DiagramStep> allDiagramSteps = <DiagramStep>[
  AdjustDragOffsetDiagramStep(),
  AlertDialogDiagramStep(),
  AlignDiagramStep(),
  AnimationStatusValueDiagramStep(),
  ...
```

####  Move fonts to diagrams

Many fonts can be found in `packages/diagram_generator/fonts` which are available for diagrams to use, but they no longer work when running an application outside of `diagram_generator`.

To fix this, we can move the fonts to `packages/diagrams` and add `package: 'diagrams'` to any `TextStyle`s that use custom fonts:

```dart
Text(
  '$mode',
  style: const TextStyle(
    inherit: false,
    fontFamily: kMonospaceFont,
    color: Colors.black,
    fontSize: 10.0,
    fontWeight: FontWeight.w900,
    package: 'diagrams', // Add this line
  ),
)
```

#### Less inheritance

Because `DiagramStep` no longer cares about the super type of each diagram, they are no longer forced to extend a redundant class:

```dart
// No longer necessary, ColorSwatchDiagram and ColorListDiagram can
// implement DiagramMetadata themselves.
abstract class ColorDiagram extends StatelessWidget
    implements DiagramMetadata {
  const ColorDiagram({super.key});
}

class ColorSwatchDiagram extends ColorDiagram { ... }
class ColorListDiagram extends ColorDiagram { ... }

class ColorsDiagramStep extends DiagramStep<ColorDiagram> { ... }
```

## Other solutions considered

My first thought was to split `DiagramController` into an abstract interface, an implementation that writes files, and an implementation that can be used by diagram viewers.

There are a few problems with this approach:

1. It requires the least amount of work, but we still need to touch a significant amount of code refactoring diagrams steps to not rely on `File`s.
2. The API will likely be improved in the future anyway, for example setting `builder` is not as nice as just passing a widget to `drawDiagramToFile`.
3. Widgets can be disposed before their animation completes in a diagram viewer, current implementations of `generateDiagram` will throw exceptions if that happens. This issue can be solved by refactoring animations to be inside widgets rather than `DiagramStep`s.
4. After fixing the above problems, the only purpose of implementing `generateDiagram` is to pass parameters like animation duration / framerate to the `DiagramController`, something that can be done much cleaner with getters on `DiagramMetadata`.

**Comment by gspencergoog** [comment]
@PixelToast This is a great proposal. I'm all for it.

The diagram generation was built a long time ago... and it's due for an update. I agree with most of the points you've made here, and would love to see them implemented. I especially like the idea of enabling a reloadable diagram viewer. The generator has come a long way: it has been around since 2017 (rewritten several times), and we want it to continue to serve us into the future.

**Comment by PixelToast** [comment]
That's awesome to hear, some of the work is already done I will shoot a PR out sometime in the next week 😃
