### ISSUE TITLE
[tool_crash] FileSystemException: Deletion failed, OS Error: No such file or directory, errno = 2

### ISSUE THREAD

**Issue by ljmatan** [flutter/flutter#112396]
## Command
```
flutter build ios-framework --output=/Users/threeofthem/Projects/ADAC iOS/Flutter
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Deletion failed, OS Error: No such file or directory, errno = 2
```
#0      _Directory._deleteSync (dart:io/directory_impl.dart:201:7)
#1      FileSystemEntity.deleteSync (dart:io/file_system_entity.dart:427:7)
#2      _File._deleteSync (dart:io/file_impl.dart:295:50)
#3      FileSystemEntity.deleteSync (dart:io/file_system_entity.dart:427:7)
#4      ForwardingFileSystemEntity.deleteSync (package:file/src/forwarding/forwarding_file_system_entity.dart:70:16)
#5      ForwardingFileSystemEntity.deleteSync (package:file/src/forwarding/forwarding_file_system_entity.dart:70:16)
#6      Template.render.<anonymous closure> (package:flutter_tools/src/template.dart:269:32)
#7      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:617:13)
#8      Template.render (package:flutter_tools/src/template.dart:248:24)
#9      IosProject._overwriteFromTemplate (package:flutter_tools/src/xcode_project.dart:469:14)
<asynchronous suspension>
#10     IosProject._regenerateFromTemplateIfNeeded (package:flutter_tools/src/xcode_project.dart:396:9)
<asynchronous suspension>
#11     IosProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/xcode_project.dart:320:5)
<asynchronous suspension>
#12     FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:355:7)
<asynchronous suspension>
#13     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1360:7)
<asynchronous suspension>
#14     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1209:27)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#16     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 3.3.2, on macOS 12.0.1 21A559 darwin-arm, locale en-GB)
    • Flutter version 3.3.2 on channel stable at /Users/threeofthem/SDKs/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e3c29ec00c (12 days ago), 2022-09-14 08:46:55 -0500
    • Engine revision a4ff2c53d8
    • Dart version 2.18.1
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/threeofthem/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F17a
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] VS Code (version 1.71.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] VS Code (version 1.72.0-insider)
    • VS Code at /Applications/Visual Studio Code - Insiders.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (3 available)
    • iPhone 13 Pro (mobile) • 06784F3B-852F-4A10-A66B-235E0BA9938A • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.0.1 21A559 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 105.0.5195.125

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

## Flutter Application Metadata
**Type**: module
**Version**: 1.0.0+1
**Material**: true
**Android X**: true
**Module**: true
**Plugin**: false
**Android package**: com.example.ia_flutter
**iOS bundle identifier**: com.example.iaFlutter
**Creation channel**: stable
**Creation framework version**: e3c29ec00c9c825c891d75054c63fcc46454dca1
### Plugins
path_provider-2.0.11
path_provider_android-2.0.20
path_provider_ios-2.0.11
path_provider_linux-2.1.7
path_provider_macos-2.0.6
path_provider_windows-2.1.3

**Comment by abdelrahmanelmarakby** [comment]
maybe you want to change the ADAC iOS folder name to ADAC_iOS then run the command like this ` flutter build ios-framework --output=/Users/threeofthem/Projects/ADAC_iOS/Flutter` the space is not translated into space in the terminal I think
@ljmatan

**Comment by huycozy** [comment]
Hi @ljmatan 
Could you try the solution @abdelrahmanelmarakby mentioned above or create a new project in a directory without space in its path?

**Comment by ljmatan** [comment]
Thank you both for your responses. 

The actual command was `flutter build ios-framework --output='/Users/threeofthem/Projects/ADAC iOS/Flutter'`. I don't know why the apostrophes were removed in the report template.

**Comment by huycozy** [comment]
@ljmatan Did you try the solutions we mentioned above?

**Comment by ljmatan** [comment]
No, sorry, it was a one-off, bu the command was definitely `flutter build ios-framework --output='/Users/threeofthem/Projects/ADAC iOS/Flutter'`

**Comment by iapicca** [comment]
possibly related to
https://github.com/flutter/flutter/issues/68958
https://github.com/flutter/flutter/issues/91559

**Comment by huycozy** [comment]
@ljmatan 
>No, sorry, it was a one-off, bu the command was definitely flutter build ios-framework --output='/Users/threeofthem/Projects/ADAC iOS/Flutter'

Can you elaborate on the issue more clearly? Does it only happen once? And now it doesn't happen anymore after you try the above solutions?

**Comment by ljmatan** [comment]
@huycozy what would you like me to elaborate? This error report template was not generated by me.

"One-off" would mean it had happened once, yes. After removing the package that was causing this issue to which I'm still waiting your response: https://github.com/flutter/flutter/issues/112459

Also, what you've suggested is not a solution, it's a workaround at best for something that's worked before. 

Responding just for the sake of closing a ticket is not the point of this board, I hope you'll understand that.

**Comment by huycozy** [comment]
@ljmatan 
>what would you like me to elaborate? This error report template was not generated by me.
"One-off" would mean it had happened once, yes. After removing the package that was causing this issue to which I'm still waiting your response: https://github.com/flutter/flutter/issues/112459

Please confirm that the issue goes away after you remove the space from the folder name `ADAC iOS` or remove the package in your other issue #112459 for further investigation.

Also, there have been similar issues in the past, and we need to clear up every detail before we can solve it: https://github.com/flutter/flutter/issues/51138#issuecomment-591157214. As you can see the OP of that issue was trying to help us by testing and confirming it in detail.
