### ISSUE TITLE
Preloaded data without Circular Progress Indicator 

### ISSUE THREAD

**Issue by shashikiran918** [flutter/flutter#112376]
can anyone help me how to get preloaded data after hitting apis(button pressed) when navigating to next page . before navigating to next page i can load  data of that page. so that  i can  reduce delay in loading data.

**Comment by darshankawar** [comment]
@shashikiran918 
Your question is better suited for support channels like StackOverflow, so please ask the same there.
Closing from here, as this is more of a `how to` support question instead of a bug or feature request report.
