### ISSUE TITLE
Firebase plugins could make Google Play Services available

### ISSUE THREAD

**Issue by collinjackson** [flutter/flutter#11237]
From the [docs](https://firebase.google.com/docs/cloud-messaging/android/client#sample-play):

> Apps that rely on the Play Services SDK should always check the device for a compatible Google Play services APK before accessing Google Play services features. It is recommended to do this in two places: in the main activity's onCreate() method, and in its onResume() method. The check in onCreate() ensures that the app can't be used without a successful check. The check in onResume() ensures that if the user returns to the running app through some other means, such as through the back button, the check is still performed.
> 
> If the device doesn't have a compatible version of Google Play services, your app can call `GoogleApiAvailability.makeGooglePlayServicesAvailable()` to allow users to download Google Play services from the Play Store.

The google_sign_in plugin already [ensures](https://github.com/flutter/plugins/blob/master/packages/google_sign_in/android/src/main/java/io/flutter/plugins/googlesignin/GoogleSignInPlugin.java#L458) Google Play Services is present and I think the Firebase Android plugins should as well -- they could attach lifecycle listeners to the activity to check for `onCreate` and `onResume` automatically.  (We could also expose a Dart API for it, but I'd rather not since it's Android specific.)

I don't think there's an easy way for plugins to prevent the Flutter app from starting up but the plugins could queue up method calls until the error is resolved.

This issue is based on a conversation with @lukef although I think Posse has already worked around it.

**Comment by collinjackson** [comment]
FYI @tvolkert @goderbauer

**Comment by tvolkert** [comment]
We could easily add more [listener hooks](https://github.com/flutter/engine/blob/b91d2f1bb4b2cb6e69fb773b7f51639ebb90fd58/shell/platform/android/io/flutter/plugin/common/PluginRegistry.java#L110) to `PluginRegistry.Registrar` to be notified of things like `onCreate()` and `onResume()`

/cc @mravn-google

**Comment by collinjackson** [comment]
We already have several plugins using `registrar.activity().getApplication().registerActivityLifecycleCallbacks()` to listen for lifecycle events like `onCreate` and `onResume`, so I don't think additional plugin framework support is needed to this bug.

The Flutterfire plugins just need to use the `GoogleApiAvailability` API to throw an appropriate error dialog and delay processing method calls until the error is dealt with.

**Comment by kroikie** [comment]
@collinjackson

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/982. Any further collaboration will be done there.
