### ISSUE TITLE
pigeon with ClassCastException

### ISSUE THREAD

**Issue by hello-soon** [flutter/flutter#112384]
BasicMessageChannel#dev.flutter.pigeon.CommonFlutterApi.showMoreSettingSheet: Failed to handle message reply
    java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long

in dart
![image](https://user-images.githubusercontent.com/62131847/192291366-9a9faaed-dd8a-4409-af54-53c046e63aad.png)

gen code in java
<img width="1182" alt="image" src="https://user-images.githubusercontent.com/62131847/192291704-b14319a7-61b4-4982-9e1f-8670d669f6cf.png">

-------------------
pigeon: 3.1.0
-------------------

[✓] Flutter (Channel stable, 2.10.5, on macOS 12.6 21G115 darwin-x64, locale zh-Hans-HK)
    • Flutter version 2.10.5 at /Users/admin/Library/Android/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (5 个月前), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/admin/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = /Users/admin/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[!] Android Studio
    • Android Studio at /Applications/AndroidStudioRC1.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] VS Code (version 1.71.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • Pixel 4 (mobile)  • 9B071FFAZ00B4K                       • android-arm64  • Android 11 (API 30)
    • iPhone 8 (mobile) • 0BF3383A-6C59-4DAD-93F7-7031D707540E • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-5 (simulator)
    • Chrome (web)      • chrome                               • web-javascript • Google Chrome 105.0.5195.125

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

**Comment by exaby73** [comment]
Hello @hello-soon. Thanks for filing this issue. Can you confirm if this issue is still persistent on the latest stable, 3.3.2?

**Comment by stuartmorgan** [comment]
Generated Pigeon code doesn't depend on Flutter version, so it will still happen.

**Comment by hello-soon** [comment]
after update to flutter 3.3.2, pigeon: 4.2.0
it maybe fix

<img width="1017" alt="image" src="https://user-images.githubusercontent.com/62131847/192415734-06bfc740-cbd8-4c09-90ac-7bd486da1bfb.png">

**Comment by stuartmorgan** [comment]
Oops, I missed that this was fixed in 3.2.6.
