### ISSUE TITLE
[Windows]app crashed when call std::make_unique<flutter::FlutterViewController>

### ISSUE THREAD

**Issue by yongyu-wang** [flutter/flutter#112383]
hello, I had a diffcult problem when I wanna create a FlutterViewController instance in my plugin, when I call these code , the app will crash:
(my intention is to create a new window and show some video on it)
`  flutter::DartProject project(L"data");
  project.set_dart_entrypoint_arguments({"projection_window", std::to_string(id), std::move(args)});  
  flutter_controller_ = std::make_unique<flutter::FlutterViewController>(frame.right - frame.left, frame.bottom - frame.top, project);`

what bother me even more is I can't get any information for this crash. when I debug this crash in VS, it only shows ‘not loaded flutter_windows.dll.pdb’.
![image](https://user-images.githubusercontent.com/86452370/192286416-afad1121-0092-4ffb-85eb-87a44c0c32c9.png)

Could you please tell me how to fix this issue, or how can I get more debug information?

**Comment by exaby73** [comment]
Hello @yongyu-wang. Thank you for filing this issue. Can you please provide the following information?

- A [complete and minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).
- The output of `flutter doctor -v`
- The output of `flutter run-v`

Please provide the information in the form of text. See how to make collapsible sections with Markdown [here](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-collapsed-sections).

**Comment by yongyu-wang** [comment]
You can reproduce this issue by run the example of this plugin, and click the button "Create a new world":
https://pub.dev/packages/desktop_multi_window

that's so weird that I can run this serveral months ago, maybe the flutter sdk is 3.0.5 or lower. And I had update to newest version this week, this problem occured.

By the way, this is My flutter doctor info: 
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.3.2, on Microsoft Windows [Version 10.0.19044.2006], locale zh-CN)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.3.2)
[√] Android Studio (version 2021.2)
[√] VS Code (version 1.71.0)
[√] Connected device (4 available)
[√] HTTP Host Availability

• No issues found!

**Comment by exaby73** [comment]
Closing this issue in favor of https://github.com/flutter/flutter/issues/110661. If you disagree, please comment and I can reopen it. Thank you.
