### ISSUE TITLE
[image_picker][ios]:Restrict the maximum count of images the user can pick/select

### ISSUE THREAD

**Issue by luvishq** [flutter/flutter#112332]
Hi, 

I see there were earlier request to restricts the count of images users can select on image -pick 

#85772

I know on Android it's isn't possible , can we release the support iOS if that is possible. It was asked to upvote the thread to get this being worked on but the issue was closed.

Opening another issue so that people upvote this to get the feature made .

**Comment by luvishq** [comment]
cc @darshankawar

**Comment by darshankawar** [comment]
Treating this as a ios specific feature for `image_picker` plugin and based on below comments:

https://github.com/flutter/flutter/issues/85772#issuecomment-884137114
https://github.com/flutter/flutter/issues/85772#issuecomment-887614127

**Comment by luvishq** [comment]
Any update when this would be addressed ? @stuartmorgan @darshankawar

**Comment by stuartmorgan** [comment]
Please see https://github.com/flutter/flutter/wiki/Issue-hygiene#when-will-my-bug-be-fixed

**Comment by jmagman** [comment]
I think this was meant to be closed 🙂
