### ISSUE TITLE
macOS: Scrolling doesn't work properly in low power mode

### ISSUE THREAD

**Issue by knopp** [flutter/flutter#112333]
This a weird one. Should be reproducible with any sufficiently long scroll view. But for me it only happens on battery, with low power mode (macOS 12.6, MacBook Pro 14").

During repeating swipes, at some point macOS will stop sending `- (void)scrollWheel:(NSEvent*)event` event when two fingers are down on trackpad, but it will keep sending appropriate `-(void)touchesMovedWithEvent:(NSEvent*)event` message (with two touches as expected).

I have no idea why this only happens in low power mode. I also don't know if this can be reproduced on older macs.

I tried disabling resting touches but it made no difference.

**Comment by knopp** [comment]
cc @moffatman

**Comment by moffatman** [comment]
Seems like a macOS bug, it behaves weirdly in other apps as well such as Chrome and Finder

**Comment by knopp** [comment]
Indeed. I was unable to reproduce it in Safari (that's why I initially thought it might be a Flutter bug), but I eventually did manage to reproduce it in both Safari and Finder.

**Comment by knopp** [comment]
I'm reopening this. I'm getting this now even in regular (not low power) mode. Safari and Finder are affected to a degree, but it's lot less disruptive than scrolling flutter content.

**Comment by knopp** [comment]
It seems that every once in a while, scroll event is missing the began/changed phases, but it still continues with the momentum phase. This would explain why Safari is much less affect. It misses the regular scrolling event, but it still continues the scroll with the momentum phase events, instead of abruptly coming to stop like Flutter does.

**Comment by knopp** [comment]
Apparently this is not a [new issue](https://developer.apple.com/forums/thread/690790). It's been around for quite some time now so I'm not holding my breath to see it fixed any time soon. I think we may need a workaround to at least not send the inertia cancellation event if there may be momentum events coming (thus reusing previous inertia).

**Comment by moffatman** [comment]
Can you clarify, what's the expected sequence of events, and what's the error-case sequence?

**Comment by knopp** [comment]
> Can you clarify, what's the expected sequence of events, and what's the error-case sequence?

Sure! 

### Normal sequence

- Touches Began (sends cancellation event)
- NSEvent ScrollWheel, phase=Began, momentumPhase=None
- NSEvent ScrollWheel, phase=Changed, momentumPhase=None (repeated)
- NSEvent ScrollWheel, phase=Ended, momentumPhase=None
- NSEvent ScrollWheel, phase=None, momentumPhase=Began (after lift)
- NSEvent ScrollWheel, phase=None, momentumPhase=Changed (repeated)
- NSEvent ScrollWheel, phase=None, momentumPhase=Ended

### Patological sequence (in low power mode, sometimes)

- Touches Began (sends cancellation event)
- NSEvent ScrollWheel, phase=None, momentumPhase=Began (after lift)
- NSEvent ScrollWheel, phase=None, momentumPhase=Changed (repeated)
- NSEvent ScrollWheel, phase=None, momentumPhase=Ended

You can see that here regular scroll view event (while tracking) are missing. There are still momentum events, but Flutter ignores those (Safari probably doesn't, that's why the behavior is less disruptive).

Note that `touchesMoved:` events are processed as expected, it's just that for whatever reason these are not turned into ScrollWhell events.

The main issue here is that Touches Began cancels the momentum completely, so scrolling comes to an abrupt stop and doesn't resume until user lifts fingers.

From the top of my head I can see two possible workarounds: Detect low power mode, and either delay the cancellation event a bit until we know that there wasn't a fling, to at least reuse existing momentum, or try turning `touchesMoved:` into ScrollWheel event.

**Comment by knopp** [comment]
This *seem* to be fixed in macOS Ventura, but there is another issue: `ScrollInertiaCancel` event is not dispatched at all. The reason is that `touchesBeganWithEvent:` is invoked after `system_scroll_inertia_active` has been already set to false.

@moffatman, do you remember the reason for not simply sending ScrollInertiaCancel event during `momentumPhase=Ended`?

**Comment by moffatman** [comment]
We don't want to send an event at all times that scroll inertia ends, only when it's cancelled early. That's because if the scroll physics is faster on native macOS than Flutter (which is the case until you have my new physics in flutter 3.4), it will always cancel the Flutter physics early. I haven't updated to Ventura yet, will do so soon and check this out. I have an idea of how to keep the same behaviour even with this new sequence change.

**Comment by knopp** [comment]
To make things worse, there are quirks with low power mode on Ventura as well. With low power mode, sometimes there is `touchesBeganWithEvent:` delivered during scroll momentum, i.e. the following sequence:

* NSEvent ScrollWheel, phase=Began, momentumPhase=None
* NSEvent ScrollWheel, phase=Changed, momentumPhase=None (repeated)
* NSEvent ScrollWheel, phase=Ended, momentumPhase=None
* NSEvent ScrollWheel, phase=None, momentumPhase=Began (after lift)
* **touchesBeganWithEvent:** (note that cocoa momentum continues despite this event)
* NSEvent ScrollWheel, phase=None, momentumPhase=Changed (repeated)
* NSEvent ScrollWheel, phase=None, momentumPhase=Ended

I seem to be only able to reproduce this in low power mode. It results in scrolling stopping abruptly. Hopefully this should be easier to work around than scroll events missing completely in macOS 12.6).

**Comment by knopp** [comment]
For what is worth, this works for me as a workaround on Ventura (both regular and low power mode): https://github.com/knopp/engine/commit/890dcf3613e2b80efe6d9bfdcff5a1853c168501

**Comment by moffatman** [comment]
I just tried it out, you actually could get it in the next event loop sometimes. So I would recommend dispatch after ~5ms?

**Comment by knopp** [comment]
Maybe not use dispatch_async for this, but instead store time of last `momentumPhase=Changed` and if touchesBeganWithEvent: comes within 5ms for it send the event? Something like this: https://github.com/flutter/engine/commit/e1ba2cdf1b9a04fb41f3f234e5068274af2fd9bd

I don't like using dispatch_after for stuff like this because there is no cancelation. So during repeated events you might get dispatch_after invoking block that was scheduled previously changing state when you don't expect it.
