### ISSUE TITLE
hotreload time regression

### ISSUE THREAD

**Issue by iskakaushik** [flutter/flutter#112395]
see: https://flutter-flutter-perf.skia.org/e/?begin=1663777160&end=1663796864&keys=X7159d7556b1615d5fe43c4e34c490a09&selected=commit%3D31223%26name%3D%252Carch%253Darm%252Cbranch%253Dmaster%252Cconfig%253Ddefault%252Cdevice_type%253DiPhone_6s%252Cdevice_version%253DiOS-15.5%252Chost_type%253Dmac%252Csub_result%253DhotReloadVMReloadMillisecondsAfterLargeChange%252Ctest%253Dhot_mode_dev_cycle_macos_target__benchmark%252C&xbaroffset=31223

**Comment by iskakaushik** [comment]
https://github.com/flutter/flutter/pull/110908 seems to be the issue per skia perf. cc: @justinmc any ideas why it might be the case?

**Comment by iskakaushik** [comment]
another benchmark that regressed: https://flutter-flutter-perf.skia.org/e/?begin=1663723404&end=1663777807&keys=X598ec58a17043de7c4b54d50c867aa15&selected=commit%3D31211%26name%3D%252Carch%253Darm%252Cbranch%253Dmaster%252Cconfig%253Ddefault%252Cdevice_type%253DiPhone_6s%252Cdevice_version%253DiOS-15.5%252Chost_type%253Dmac%252Csub_result%253DhotReloadVMReloadMillisecondsAfterChange%252Ctest%253Dhot_mode_dev_cycle_macos_target__benchmark%252C&xbaroffset=31211

**Comment by justinmc** [comment]
Did this end up not being a concern?  I wouldn't think that https://github.com/flutter/flutter/pull/110908 would affect hotreload time.
