### ISSUE TITLE
camera preview and captured image donesn't look same

### ISSUE THREAD

**Issue by Nasirdev74** [flutter/flutter#112344]
I'm using the camera package to take picture. my CameraPreview widget is not full screen, It has a custom height. when I open the camera Its show a small area which is fine. but when I take a picture, the picture is bigger than the camera preview.  So the camera preview and taken picture is different. 

I want the captured image to be same as it shows on camera preview widget. 

```
capturedImage = File((await cameraController!.takePicture()).path);

Transform.scale(
scale: cameraController!.value.aspectRatio,
child: AspectRatio(
aspectRatio: cameraController!.value.aspectRatio,
child: Center(
child: CameraPreview(cameraController!),
),
),
),

```
any idea on it ??

**Comment by darshankawar** [comment]
@Nasirdev74 
Can you provide `flutter doctor -v`, camera plugin version, platform (ios or android) on which you are running, actual result along with complete minimal code sample ?

**Comment by Nasirdev74** [comment]
I solved my issue using below code 

```
Transform.scale(
scale: 2/6,
child: AspectRatio(
aspectRatio: cameraController!.value.aspectRatio,
child: Center(
child: CameraPreview(cameraController!)))),
```
