### ISSUE TITLE
Google Sign In PlatformException Android

### ISSUE THREAD

**Issue by theobouwman** [flutter/flutter#11231]
## Problem

On Android an `PlatformException` gets printed to the console after selecting an account from the Google Sign In popup.

## Steps to Reproduce

- Create a new Flutter application
- Add the Google Sign In plugin (https://pub.dartlang.org/packages/google_sign_in - v0.3.1)

## Logs

When you select an Google account from the popup this will be printed to the console:
```
I/flutter (27876): PlatformException(status, Status{statusCode=DEVELOPER_ERROR, resolution=null}, null)
```

## Flutter Doctor

```
[✓] Flutter (on Mac OS X 10.12.5 16F73, locale nl-NL, channel alpha)
    • Flutter at /development/flutter
    • Framework revision d36e2f6191 (3 weeks ago), 2017-06-21 15:09:10 -0700
    • Engine revision b0dee695ec
    • Tools Dart version 1.24.0-dev.6.7

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.0)
    • Android SDK at /Users/theobouwman/Library/Android/sdk
    • Platform android-26, build-tools 26.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.3.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3.3, Build version 8E3004b
    • ios-deploy 1.9.0
    • CocoaPods version 1.1.1

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Gradle version 3.2
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Ultimate Edition (version 2017.1.5)
    • Flutter plugin version 15.1
    • Dart plugin version 171.4694.29
```

**Comment by ride4sun** [comment]
I see the same behavior on Android
[](https://wxaktw-ch3302.files.1drv.com/y4mPs773CB_1fftWSmkL-vy3qH53Vv-1e-YnbdxiMfWH4xYJ-ug0W9sippShZzwMSc9ePZcGmvbcUK_SBAHhuD9fg6XXEaKv1PUKf8x6fu7kfuS1caz2RMGrZY3cM8bK4U2x95uCHCADzfCs2blKqwA_MBJ7Ww6kgEbYpkZXzUcG0hILZlB-WlQ4iFeRFo4aIWKR5Pm9AVQByegs8EJizyMrA?width=1511&height=623&cropmode=none)

**Comment by ride4sun** [comment]
This is the calling function:
![alt](https://wxavtw-ch3302.files.1drv.com/y4m1mnyAdi2jAghqHOg_67Rn2jusMpi88OuHMfwE-tDOciyGrnC_qaZVkSLzdeno2-UKOqAcAXqexwqPMiNdlGkSF7GABbOYZgFrjtpFPLLLu6T-6GstUwM6BWJ80FPyQ8zANeDDn4yEJ7rcNXXFAyJk2pqdRebjQedvaqMUxDQAejLWAy0CmoJHfdWs9-QDTxGytjz86vre6WK3n8rR3Y0cw?width=594&height=295&cropmode=none)

**Comment by ride4sun** [comment]
Microsoft Windows [Version 10.0.15063]
(c) 2017 Microsoft Corporation. All rights reserved.

C:\Projects\lookatmybaby>flutter doctor
[√] Flutter (on Microsoft Windows [Version 10.0.15063], locale en-US, channel alpha)
    • Flutter at c:\sdks\flutter
    • Framework revision d36e2f6191 (3 weeks ago), 2017-06-21 15:09:10 -0700
    • Engine revision b0dee695ec
    • Tools Dart version 1.24.0-dev.6.7

[√] Android toolchain - develop for Android devices (Android SDK 26.0.0)
    • Android SDK at C:\Users\ride4\AppData\Local\Android\sdk
    • Platform android-26, build-tools 26.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[√] Android Studio (version 2.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Gradle version 3.2
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[√] IntelliJ IDEA Community Edition (version 2017.1)
    • Flutter plugin version 15.1
    • Dart plugin version 171.4694.29

[√] Connected devices
    • Nexus 5 • 03b71506f0b4f6b6 • android-arm • Android 6.0.1 (API 23)


C:\Projects\lookatmybaby>

**Comment by goderbauer** [comment]
Did you follow the steps outlined in the README for [Android integration](https://github.com/flutter/plugins/tree/master/packages/google_sign_in#android-integration) and/or [iOS integration](https://github.com/flutter/plugins/tree/master/packages/google_sign_in#ios-integration)?

**Comment by theobouwman** [comment]
@goderbauer yes. I am using Firebase

**Comment by tvolkert** [comment]
If you watch `adb logcat` while you attempt to sign in, does it contain any more info (the flutter logs are a filtered version of `adb logcat`, so it's possible something relevant is getting filtered out)?

Generally speaking, status code `DEVELOPER_ERROR` indicates that the application is misconfigured somehow.

**Comment by theobouwman** [comment]
@tvolkert there was indeed a misconfiguration. I forgot to add the SHA1 key to the Firebase App in the Console.

When I viewed the ADB logs the error message was much more readable.

cc @ride4sun

**Comment by ride4sun** [comment]
Yes, I did the same as@theobouwman I think the documentation could be a bit better pointing out that you have add a SHA1 for each development Maschine

**Comment by goderbauer** [comment]
@ride4sun: Feel free to send a PR with clarifications of the instructions to https://github.com/flutter/plugins/blob/master/packages/google_sign_in/README.md.

**Comment by jagan999** [comment]
I added the SHA1 key as well as indicated above but I continue to get the same DEVELOPER_ERROR

**Comment by jagan999** [comment]
Btw, with the Flutter plugin to Android Studio, I'm never able to view logcat. It keeps saying Configure Android.

**Comment by koami** [comment]
Was my bad I generated a sha key for the test version instead of using the debug sha.
