### ISSUE TITLE
Navigator's static functions that take a context should assert that the context has an ancestor that's a Navigator  and indicate that's a problem if not.

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#1123]

**Comment by Hixie** [comment]
Right now if you call Navigator.pop(context) and no NavigatorState can be found from that context, then we crash, no? Are you not seeing a crash?

**Comment by jimbeveridge** [comment]
The problem is that it's hard for the developer that hits this crash to know the cause. If the condition can be detected, along with a comment in the code that says "if this asserts, then you need a parent Navigator", then life is made easier for consumers of Flutter.

**Comment by Hixie** [comment]
ah, OK.

**Comment by abarth** [comment]
Looks like we have a reasonable message now:

```
        throw new WidgetError('openTransaction called with a context that does not include a Navigator. The context passed to the Navigator.openTransaction() method must be that of a widget that is a descendant of a Navigator widget.');
```
