### ISSUE TITLE
WebGL: INVALID_OPERATION: delete: object does not belong to this context canvaskit.js:231 

### ISSUE THREAD

**Issue by ramiro85** [flutter/flutter#112467]
flutter doctor -v
[✓] Flutter (Channel stable, 3.3.2, on Ubuntu 20.04.3 LTS 5.15.0-46-generic, locale en_US.UTF-8)
    • Flutter version 3.3.2 on channel stable at ~/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e3c29ec00c (13 days ago), 2022-09-14 08:46:55 -0500
    • Engine revision a4ff2c53d8
    • Dart version 2.18.1
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at ~/Android/Sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: ~/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[✓] Android Studio (version 2021.1)
    • Android Studio at ~/android-studio
    • Flutter plugin version 70.0.1
    • Dart plugin version 211.7817
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code (version 1.65.2)
    • VS Code at ~/code
    • Flutter extension version 3.40.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 20.04.3 LTS 5.15.0-46-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 105.0.5195.125

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Comment by danagbemava-nc** [comment]
Hi @ramiro85, please provide a complete minimal reproducible code sample along with the steps to reproduce the issue. 

Please also provide any relevant logs. 

Thank you

**Comment by ramiro85** [comment]
I solved it! Thanks anyway!!

**Comment by ramiro85** [comment]
It was my data not flutter. Thanks
