### ISSUE TITLE
[Impeller] Run Vulkan unit-tests by default.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#112423]
Currently, running the unit-tests requires the `--enable-impeller-vulkan` GN option enabled. Now that we have landed the Vulkan backend and are iterating on it in tree, perhaps it is time to remove the need for this flag.

**Comment by chinmaygarde** [comment]
cc @iskakaushik WDYT?

**Comment by iskakaushik** [comment]
Agreed. Is there a way to enable some tests but not all to start with? I'll see if there is a way to do this incrementally for Vulkan.

**Comment by chinmaygarde** [comment]
@iskakaushik Are you still working on this? Feel free to unassign yourself if not. I can take a closer look at this too.

**Comment by iskakaushik** [comment]
Yup. https://github.com/flutter/buildroot/pull/639 was a prerequisite for this. Seems like you rolled `buildroot` in https://github.com/flutter/engine/pull/36901. I will continue working on this.

**Comment by chinmaygarde** [comment]
@iskakaushik Just catching up on old issues. Are there any blockers to doing this and removing the Vulkan opt-in on the host unit-tests?

**Comment by chinmaygarde** [comment]
This is fixed.
