### ISSUE TITLE
`VsyncWaiter` schedules unneeded extra `AwaitVSync` callbacks for one frame

### ISSUE THREAD

**Issue by fzyzcjy** [flutter/flutter#112439]
Please see https://github.com/flutter/engine/pull/36406 for details.

_Copied from PR_

Consider the following sequence:

* ScheduleSecondaryCallback(id1, callback1)
* ScheduleSecondaryCallback(id2, callback2)

Then, without this fix, the AwaitVSync will be called twice. Then, FireCallback will be called twice at the beginning of the next frame. But we know that FireCallback calls all primary and secondary callbacks, so being called twice just waste some computation resource.

By the way, the following sequences are all ok without bugs:

* AsyncWaitForVsync
* ScheduleSecondaryCallback(id1)
* ScheduleSecondaryCallback(id2)

or

* ScheduleSecondaryCallback(id1)
* AsyncWaitForVsync
* ScheduleSecondaryCallback(id2)

**Comment by zanderso** [comment]
Was this fixed by https://github.com/flutter/engine/pull/36406 ?

**Comment by fzyzcjy** [comment]
Yes
