### ISSUE TITLE
flutter-gold test is taking up to 50 minutes to complete.

### ISSUE THREAD

**Issue by ricardoamador** [flutter/flutter#112435]
The flutter-gold test is taking up to 50 minutes to complete and holding up merging for up to 2 hours.

See this issue: https://github.com/flutter/engine/pull/36431

appengine logs: https://pantheon.corp.google.com/logs/query;query=resource.type%3D%22gae_app%22%0Aresource.labels.module_id%3D%22auto-submit%22%0A-%22_check%22%0A-%22Health%22%0A%2236431%22;timeRange=2022-09-25T03:14:39.260Z%2F2022-09-27T01:01:20.187000001Z;summaryFields=:false:32:beginning;cursorTimestamp=2022-09-27T01:01:20.187Z?serviceId=auto-submit&project=flutter-dashboard

**Comment by bernaferrari** [comment]
Is there a heatmap for where it is spending most time on?

**Comment by ricardoamador** [comment]
I do not believe so. Not that I have seen.

**Comment by drewroengoogle** [comment]
Updating since it's been almost two weeks - Is this still occurring?

**Comment by ricardoamador** [comment]
Closing as not an issue. I looked through the logs at the most commits and it is taking anywhere from 42 minutes to 50 minutes for this test to run.

**Comment by ricardoamador** [comment]
For some more information on the flutter-gold test itself: 
There is a cron job that runs every 5 minutes to see if all other checks are complete, and when they are, it just makes a request to the Gold server to get a yes-or-no if images passed, and then it makes the check green.
