### ISSUE TITLE
The spacing of leading and middle widgets is a bit off on Android

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#11248]
I noticed that the layout of the app bar is a bit off. Unfortunately, I cannot find any specs for toolbar on material site anymore. The main issue is the margin between leading and middle widgets which seem to be too large:

https://github.com/flutter/flutter/blob/7ba1879bfce18094b5b5fba8aa20a8487f3d0322/packages/flutter/lib/src/widgets/navigation_toolbar.dart#L77

This is a Flutter app: 
![image](https://user-images.githubusercontent.com/6687929/28254141-e2c62250-6a5e-11e7-8a0e-cc38a790a1e4.png)

This is an Android app:
![image](https://user-images.githubusercontent.com/6687929/28254147-ec4ae91e-6a5e-11e7-81d9-5804b4023017.png)

The text is too far to the right (by about 4dp) and the icon is not centered.

**Comment by TahaTesser** [comment]
Hi @mehmetf 
Given the mentioned issues are closed
Is this issue still valid?
Thank you
