### ISSUE TITLE
Bad state: Flutter is not available when rebuilding stocks i18n files

### ISSUE THREAD

**Issue by franklinharper** [flutter/flutter#11244]
## Steps to Reproduce

1. cd examples/stocks
2. pub run intl_translation:generate_from_arb   --output-dir=lib/i18n   --generated-file-prefix=stock_   --no-use-deferred-loading   lib/*.dart   lib/i18n/*.arb

The output is
```
Bad state: Flutter is not available.
package:pub/src/flutter.dart 29       packagePath
package:pub/src/source/sdk.dart 108   BoundSdkSource.getDirectory
package:pub/src/system_cache.dart 97  SystemCache.load
package:pub/src/entrypoint.dart 589   Entrypoint._assertLockFileUpToDate
package:pub/src/entrypoint.dart 521   Entrypoint.assertUpToDate
package:pub/src/entrypoint.dart 106   Entrypoint.packageGraph
package:pub/src/executable.dart 125   _executableUrl.<async>
This is an unexpected error. Please run

    pub --trace run intl_translation:generate_from_arb --output-dir=lib/i18n --generated-file-prefix=stock_ --no-use-deferred-loading lib/main.dart lib/stock_arrow.dart lib/stock_data.dart lib/stock_home.dart lib/stock_list.dart lib/stock_row.dart lib/stock_settings.dart lib/stock_strings.dart lib/stock_symbol_viewer.dart lib/stock_types.dart lib/i18n/stocks_en.arb lib/i18n/stocks_es.arb

and include the logs in an issue on https://github.com/dart-lang/pub/issues/new
```

## Logs

stocks [master]$ pub --trace run intl_translation:generate_from_arb --output-dir=lib/i18n --generated-file-prefix=stock_ --no-use-deferred-loading lib/main.dart lib/stock_arrow.dart lib/stock_data.dart lib/stock_home.dart lib/stock_list.dart lib/stock_row.dart lib/stock_settings.dart lib/stock_strings.dart lib/stock_symbol_viewer.dart lib/stock_types.dart lib/i18n/stocks_en.arb lib/i18n/stocks_es.arb
Bad state: Flutter is not available.
package:pub/src/flutter.dart 29          packagePath
package:pub/src/source/sdk.dart 108      BoundSdkSource.getDirectory
package:pub/src/system_cache.dart 97     SystemCache.load
package:pub/src/entrypoint.dart 589      Entrypoint._assertLockFileUpToDate
package:pub/src/entrypoint.dart 521      Entrypoint.assertUpToDate
package:pub/src/entrypoint.dart 106      Entrypoint.packageGraph
package:pub/src/executable.dart 125      _executableUrl.<async>
===== asynchronous gap ===========================
dart:async                               _Completer.completeError
package:pub/src/executable.dart 180      _executableUrl.<async>
===== asynchronous gap ===========================
dart:async                               Future.Future.microtask
package:pub/src/executable.dart          _executableUrl
package:pub/src/executable.dart 81       runExecutable.<async>
===== asynchronous gap ===========================
dart:async                               Future.Future.microtask
package:pub/src/executable.dart          runExecutable
package:pub/src/command/run.dart 68      RunCommand.run.<async>
===== asynchronous gap ===========================
dart:async                               Future.Future.microtask
package:pub/src/command/run.dart         RunCommand.run
package:args/command_runner.dart 177     CommandRunner.runCommand.<fn>
dart:async                               Future.Future.sync
package:args/command_runner.dart 130     CommandRunner.runCommand
package:pub/src/command_runner.dart 128  PubCommandRunner.runCommand.<async>.<fn>
dart:async                               Future.Future.sync
package:pub/src/utils.dart 72            captureErrors.<fn>
package:stack_trace                      Chain.capture
package:pub/src/utils.dart 86            captureErrors
package:pub/src/command_runner.dart 128  PubCommandRunner.runCommand.<async>
dart:async                               _SyncCompleter.complete
package:pub/src/command_runner.dart 214  PubCommandRunner._validatePlatform.<async>
---- Log transcript ----
FINE: Pub 1.22.1
ERR : Bad state: Flutter is not available.
FINE: Exception type: StateError
ERR : package:pub/src/flutter.dart 29          packagePath
    | package:pub/src/source/sdk.dart 108      BoundSdkSource.getDirectory
    | package:pub/src/system_cache.dart 97     SystemCache.load
    | package:pub/src/entrypoint.dart 589      Entrypoint._assertLockFileUpToDate
    | package:pub/src/entrypoint.dart 521      Entrypoint.assertUpToDate
    | package:pub/src/entrypoint.dart 106      Entrypoint.packageGraph
    | package:pub/src/executable.dart 125      _executableUrl.<async>
    | ===== asynchronous gap ===========================
    | dart:async                               _Completer.completeError
    | package:pub/src/executable.dart 180      _executableUrl.<async>
    | ===== asynchronous gap ===========================
    | dart:async                               Future.Future.microtask
    | package:pub/src/executable.dart          _executableUrl
    | package:pub/src/executable.dart 81       runExecutable.<async>
    | ===== asynchronous gap ===========================
    | dart:async                               Future.Future.microtask
    | package:pub/src/executable.dart          runExecutable
    | package:pub/src/command/run.dart 68      RunCommand.run.<async>
    | ===== asynchronous gap ===========================
    | dart:async                               Future.Future.microtask
    | package:pub/src/command/run.dart         RunCommand.run
    | package:args/command_runner.dart 177     CommandRunner.runCommand.<fn>
    | dart:async                               Future.Future.sync
    | package:args/command_runner.dart 130     CommandRunner.runCommand
    | package:pub/src/command_runner.dart 128  PubCommandRunner.runCommand.<async>.<fn>
    | dart:async                               Future.Future.sync
    | package:pub/src/utils.dart 72            captureErrors.<fn>
    | package:stack_trace                      Chain.capture
    | package:pub/src/utils.dart 86            captureErrors
    | package:pub/src/command_runner.dart 128  PubCommandRunner.runCommand.<async>
    | dart:async                               _SyncCompleter.complete
    | package:pub/src/command_runner.dart 214  PubCommandRunner._validatePlatform.<async>
---- End log transcript ----

## Flutter Doctor

stocks [master]$ flutter doctor
[✓] Flutter (on Mac OS X 10.12.5 16F73, locale en-US, channel master)
    • Flutter at /Users/frank/proj/flutter/flutter-sdk
    • Framework revision 5756d62931 (17 hours ago), 2017-07-14 18:33:20 -0700
    • Engine revision f56da86f98
    • Tools Dart version 1.25.0-dev.4.0

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.0)
    • Android SDK at /Users/frank/Library/Android/sdk/
    • Platform android-26, build-tools 26.0.0
    • ANDROID_HOME = /Users/frank/Library/Android/sdk/
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.3.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3.3, Build version 8E3004b
    • ios-deploy 1.9.1
    • CocoaPods version 1.2.1

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.1.4)
    • Flutter plugin version 15.0
    • Dart plugin version 171.4694.29

[✓] Connected devices
    • None

**Comment by franklinharper** [comment]
The same problem occurs with a simple test app created by 'flutter create'.

**Comment by eseidelGoogle** [comment]
That's an error from pub saying that FLUTTER_ROOT isn't set (or maybe it's FLUTTER_HOME?) in the environment.

I think we have `fluter pub run` for this sort of thing?  Not sure if that was actually built.  FYI @yjbanov who is looking at i18n.

**Comment by sethladd** [comment]
Any updates on this one?

**Comment by yjbanov** [comment]
@eseidelGoogle is almost correct. `pub` needs `FLUTTER_ROOT` to locate Flutter. We do that as part of `flutter packages` command. The correct command should be:

```
flutter packages pub run intl_translation:generate_from_arb --output-dir=lib/i18n --generated-file-prefix=stock_ --no-use-deferred-loading lib/.dart lib/i18n/.arb
```

**Comment by HansMuller** [comment]
The up to date instructions for generating the stocks example's localizations are in [stocks/lib/i18n/regenerate.md](https://github.com/flutter/flutter/blob/master/examples/stocks/lib/i18n/regenerate.md)

**Comment by HansMuller** [comment]
examples/stocks/README should point to [stocks/lib/i18n/regenerate.md](https://github.com/flutter/flutter/blob/master/examples/stocks/lib/i18n/regenerate.md), just to increase the likelihood that a developer will find it.
