### ISSUE TITLE
Firebase database plugin doesn't cancel listeners when StreamSubscription is cancelled

### ISSUE THREAD

**Issue by KevinTheGray** [flutter/flutter#11247]
If you cancel a StreamSubscription is does indeed stop listening in flutter, but the listener is still listening some how.  I noticed this when I canceled a stream, changed the auth state so I get a permission denied for that node which requires auth, and saw the error messages.

## Steps to Reproduce
1. Add a value/child listener to a node
2. Cancel it
3. Force it to get a permission denied error.  If it were cancelled, I assume it wouldn't get that error.
## Flutter Doctor

```
[✓] Android toolchain - develop for Android devices (Android SDK 26.0.0)
    • Android SDK at /Users/KG/Library/Android/sdk
    • Platform android-26, build-tools 26.0.0
    • ANDROID_HOME = /Users/KG/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.3.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3.3, Build version 8E3004b
    • ios-deploy 1.9.1
    • CocoaPods version 1.2.1

[✓] Android Studio
    • Android Studio at /Applications/Android Studio 3.0 Preview.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-884-b01)

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.1.5)
    • Flutter plugin version 15.1
    • Dart plugin version 171.4694.29

```

**Comment by collinjackson** [comment]
I'd like to take a look at this once we get through blockers. Do you remember if you were testing on iOS or Android?

**Comment by KevinTheGray** [comment]
I don't remember, I'll try to reproduce on both and let you know

**Comment by mravn-google** [comment]
I have reproduced an error message on Android:
```
W/SyncTree(19152): Listen at /counter failed: DatabaseError: This client does not have permission to perform this operation
```
There seems to be several issues at play:
1. On stream cancellation, the Android side will remove the listener added when Stream `listen` was called. But it is removed from the root node, not the child node to which it was added (in my case: `/counter`), because `path` and `parameters` are not sent from the Dart side with the remove method call.
1. If `keepSynced` has been set, it needs to be unset too. Cancelling the stream is not enough.
1. The Android handler for `keepSynced` never returns a result to Dart, leaving the Future hanging.

PR is coming up.

**Comment by mravn-google** [comment]
Same issues on iOS

**Comment by kroikie** [comment]
@KevinTheGray

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/981. Any further collaboration will be done there.

**Comment by shinewanna** [comment]
I'm also facing this issue, it'll raised our billing.
Is somebody fixed this issue?

**Comment by catalunha** [comment]
I have a same problem in my code. what is the solution ?
