### ISSUE TITLE
Improve debuggability of Widgets returned from extension factory methods

### ISSUE THREAD

**Issue by blaugold** [flutter/flutter#112468]
## Use case

Many widgets have a single child and enhance that child in some way. Extensions on `Widget` that define methods which wrap the receiver in another widget enable a style of Flutter code that requires much less nesting and is more readable to some.

Take this example of a widget tree written in the traditional Flutter style:

```dart
Center(
  child: Padding(
    padding: EdgeInsets.all(8),
    child: Text('Hello World'),
  ),
);
```

With the help of an extension on `Widget`, it can be rewritten like so:

```dart
Text('Hello World')
  .padding(EdgeInsets.all(8))
  .center();
```

```dart
extension WidgetExtensions on Widget {
  Widget center() => Center(child: this);
  Widget padding(EdgeInsetsGeometry padding) =>
      Padding(padding: padding, child: this);
}
```

There are some downsides for this style (that I'm aware of):

1. The factory methods in extensions cannot return `const` widgets, even if the receiver is `const`.
    I don't think this is a big problem, since more often than not the receiver cannot be `const` in the first place.
    It might be possible to introduce simplified `const` extension methods in Dart, that only allow calling a `const` constructor.
2. Code in the described style does not mirror the element tree in the same way the more traditional style does.
3. Recorded widget instance creation locations point to the bodies of extension methods, which is not useful to developers.

This issue is about the last point.

## Proposal

I would like to have the ability to mark an extension method as a widget factory. Debug tools would use the call site of such methods when they need the location of a widget instance in the source code.

**Comment by iapicca** [comment]
I suspect it's on dart's plate
https://github.com/dart-lang/language/issues/2444
https://github.com/dart-lang/language/issues/723

**Comment by exaby73** [comment]
Hello @blaugold. This issue doesn't look like it is specific to Flutter, but rather a language feature. Might I suggest raising an issue in [dart-lang/sdk](https://github.com/dart-lang/sdk) instead.

Closing this issue as this is not a proposal related to Flutter itself. If you disagree, please comment and I can reopen it. Thank you.
