### ISSUE TITLE
[CP] Convert the ImpellerC command line arguments to UTF-8 on Windows

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#112497]
Note this is a follow up to https://github.com/flutter/flutter/issues/111689, which was already merged to the RC branch. It was discovered that there was an additional issue when trying to update CI to include a unicode char in the path: https://flutter-review.googlesource.com/c/recipes/+/34140

### issue_link

https://github.com/flutter/flutter/issues/107590

### Commit Hash

[6d0f53a33532b1c5a426776fe52afb178f8a58dd](https://github.com/flutter/engine/pull/36335)

### Target

stable

### pr_link

https://github.com/flutter/engine/pull/36451

### Impacted Users

Flutter developers on Windows developing in non-ascii file paths

### Impact Description

While building a flutter app on Windows in a file path with non-ascii characters, the tool will crash.

### Workaround

Rename directory to not contain unicode characters.

### Risk

low

### Test Coverage

no

### Validation Steps

To validate, on a Windows machine, introduce a unicode character into the project path and try to run flutter run -d windows.

**Comment by itsjustkevin** [comment]
This seems like it should be merged to beta and stable.  Am I wrong here?

**Comment by christopherfujino** [comment]
SGTM. I'm guessing we should also include https://github.com/flutter/flutter/issues/111689

**Comment by christopherfujino** [comment]
@zanderso can I get an approval for this CP?

**Comment by christopherfujino** [comment]
or @chinmaygarde ?

**Comment by zanderso** [comment]
CP lgtm

**Comment by CaseyHillers** [comment]
Released in https://github.com/flutter/flutter/releases/tag/3.3.3
