### ISSUE TITLE
Better API for triggering SemanticsActions in tests

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#112413]
The API to trigger semantics actions from tests right now is not very discoverable:

https://github.com/flutter/flutter/blob/2aa348b9407e96ffe4eca8e8f213c7984afad3f7/packages/flutter/test/widgets/gesture_detector_semantics_test.dart#L36

Instead of requiring developers to figure that out, we should provide an easier way. Similarly to `WidgetTester.tap` [1] and `WidgetTester.tapAt` [2] we should provide a simple API on `WidgetTester` itself to trigger semantics actions in tests based on finders. With such an API, people could be writing something like the following in their tests:

```dart
  await tester.performSemanticsAction(find.text('click me'), SemanticsAction.tap);
```

[1] https://master-api.flutter.dev/flutter/flutter_test/WidgetController/tap.html
[2] https://master-api.flutter.dev/flutter/flutter_test/WidgetController/tapAt.html

**Comment by goderbauer** [comment]
Implementing this would also be helpful for the multi window project: the `pipelineOwner` attribute on the binding is going away as part of that project, so all tests, which are currently relying on `tester.binding.pipelineOwner.semanticsOwner` to perform semantics actions need to be migrated anyways. Would be good to migrate them straight to a more sensible API on widget tester instead of migrating them to what's replacing the `pipelineOwner` attribute. 

(Under the hood, the API on WidgetTester can still be based on `pipelineOwner` for now. Once the multi window stuff is ready, we would then have a single place to migrate that over to the new API instead of doing it for every single test that triggers semantics actions.)

**Comment by pdblasi-google** [comment]
@goderbauer

Yeah, I'd be happy to look into this. This actually gave me an idea for improving the API for #107866 as well. What would you think about adding a `semantics/semanticsTester` property to `WidgetTester` that could include various semantics related APIs?

It'd be implemented with a `SemanticsTester` class, which could help organize out those specific needs. I've been trying to make a `Finder` in #107866 for a simulated semantics traversal, but the API isn't quite right. It'd fit better in either `WidgetTester` or a dedicated `SemanticsTester`, so I could create an initial `SemanticsTester` as part of #107866 and add in new functionality for this ticket when I get to it.

**Comment by goderbauer** [comment]
What API are you envisioning for that semantics/semanticsTester property? Could it live right on WidgetTester as a first-class citizen like most of the other testing related API?

**Comment by pdblasi-google** [comment]
I was thinking that the semantics property would be implemented with a separate class, but be exposed through WidgetTester. The end result would look something like this while writing tests:

```
tester.semantics.tap(find.byKey(key));
```

To make things nicer, I had thought to split out the separate SemanticActions into different methods, but a `tester.semantics.performAction` could be an alternative or simply included as well.

Personally, I think having this separated out through a property and separate class makes things more readable, discoverable, and prevents us from having to prefix every method with `semantics*` to differentiate it from the current `WidgetTester` methods. It also makes it easier for us to expand on our semantics testing API more consistently, lowering the overall maintenance burden.

**Comment by goderbauer** [comment]
I like that idea!

**Comment by pdblasi-google** [comment]
Awesome! I'll start on that idea with #107866 and expand on it here for semantics interactions!
