### ISSUE TITLE
Windows web_tool_tests is flaky on execution timeout over 30 mins threshold

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#112440]
Task `Windows web_tool_tests ` has been flaky (timeout) 4 out of recent 100 runs. It's execution time is close to the threshold 30 mins. Sounds time to increase or reshard the tests?

https://ci.chromium.org/ui/p/flutter/builders/prod/Windows%20web_tool_tests/8364/overview
https://ci.chromium.org/ui/p/flutter/builders/prod/Windows%20web_tool_tests/8326/overview
https://ci.chromium.org/ui/p/flutter/builders/prod/Windows%20web_tool_tests/8322/overview
https://ci.chromium.org/ui/p/flutter/builders/prod/Windows%20web_tool_tests/8328/overview

**Comment by zanderso** [comment]
Should we shard these? For example, `expression_evaluation_web_test.dart` is ~10-15 minutes all by itself. @christopherfujino for thoughts.

**Comment by christopherfujino** [comment]
Makes sense, I see a 1 minute difference between a timing out build and a green one.
