### ISSUE TITLE
Allow dependency injection with GoRoute generator

### ISSUE THREAD

**Issue by cedvdb** [flutter/flutter#112482]
As far as I've tried it today, the go router generator, only recognize injected params that should be part of the url, that is you cannot inject anything else like into your route. 
  
Something more lenient around the lines of this could be used:

```dart

@TypedRoute()
class ProductsRoute extends GoRoute { 
   final ServiceContainer services;
   final AppRouteFactory routeFactory;

   @override
   final String path = '/products';

   ProductsRoute(this.services);

   @override
   Widget build(BuildContext context) => Container();

   @override
   void redirect() => services.authentication.isUserAuthenticated ? null : routeFactory.login();
}

@TypedRoute(params: {'id': int })
class ProductDetailsRoute extends GoRoute {
   final ServiceContainer services;
   @override
   final String path = '/products/:id';

   ProductDetailsRoute(this.services);

   @override
   Widget build(BuildContext context) => Container();
}
```

The generator is not even required here, it's just to auto generate a `go` function, which can be hand written.

```dart

class ProductsRoute extends GoRoute { 
   final ServiceContainer services;  
   final AppRouteFactory routeFactory;

   @override
   final String path = '/products';

   ProductDetailsRoute(this.services);

   @override
   Widget build(BuildContext context) => Container();

   Future<void> go(BuildContext context) => context.go(path);

   @override
   void redirect() => services.authentication.isUserAuthenticated ? null : routeFactory.login();
}

class ProductDetailsRoute extends GoRoute {
   final ServiceContainer services;
   @override
   final String path = '/products/:id';

   ProductsRoute(this.services);

   @override
   Widget build(BuildContext context) => Container();

   Future<void> go(BuildContext context, int id) => context.go(path.replace(':id', id.toString()));
}
```

To know which route is part of the stack you can use the fact that this is just a function of the path really. `/products/:id` contains 2 screens in the stack because the URL says so. Which is how a directory structure works, which conveniently, is also what an url is (supposed) to be, ie a path.  Or you can use a stack property or whatever.

Further more the distinction between GoRoute and GoRouteData seems to be an implementation details, with the only reason for it to be split in the public API, to accomodate the internals.

**Comment by exaby73** [comment]
Hello @cedvdb. Thank you for filing this request. Labelling for further insights from the team.
