### ISSUE TITLE
Various tool tests flake when `flutter pub get` appears in STDOUT

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#112478]
Examples here:
https://ci.chromium.org/ui/p/flutter/builders/try/Windows%20tool_integration_tests_5_6/7945/overview
https://ci.chromium.org/ui/p/flutter/builders/try/Windows%20tool_integration_tests_5_6/7946/overview

I'm guessing this is related to the order the tests run in. Most of the time we get lucky and pub has already run?

cc @christopherfujino @Hixie

**Comment by christopherfujino** [comment]
I think there was some regression here (maybe in our test infra), as there have been several tool integration tests flaking.. This requires further investigation.

**Comment by Hixie** [comment]
`overall_experience_test` expects its tests to be run in a particular order (it's marked noshuffle) and the first test ignores messages about pub (and building the tool, etc).

Unfortunately, the first test is skipped on windows, so that's probably the problem.

**Comment by Hixie** [comment]
(why it would have worked for so long only to regress now is unclear)

**Comment by christopherfujino** [comment]
I think this was fixed
