### ISSUE TITLE
Question - Is it possible to combine dismissible and non-dismissible items in a list view?

### ISSUE THREAD

**Issue by kostaa** [flutter/flutter#11245]
I would like to combine dismissible and non-dismissible items in a list view. The former one will be an instance of the Dismissible class that wraps a ListTile, the latter one just a plain ListTile instance. Will this cause any issues when combined in the ListView this way?

Alternatively is there a way to prevent the Dismissible from being dismissed?

**Comment by HansMuller** [comment]
Combining Dismissable() items with ListTiles not wrapped with a Dismissable widget is OK.

**Comment by kostaa** [comment]
Great! thanks for your help
