### ISSUE TITLE
[tool_crash] SentinelException

### ISSUE THREAD

**Issue by goutham-tez** [flutter/flutter#112461]
## Command
```
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
SentinelException
```
#0      new _OutstandingRequest (package:vm_service/src/vm_service.dart:1746:45)
#1      VmService._call (package:vm_service/src/vm_service.dart:2262:21)
#2      VmService.reloadSources (package:vm_service/src/vm_service.dart:2117:7)
#3      _reloadDeviceSources (package:flutter_too

**Comment by danagbemava-nc** [comment]
Hi @goutham-tez, there's an existing issue tracking this in https://github.com/flutter/flutter/issues/96746. 

Kindly follow up in the issue linked above for updates. 

Closing from here as duplicate. 

Thank you
