### ISSUE TITLE
[CP] App fatally crashes when using CachedNetworkImage

### ISSUE THREAD

**Issue by AlexV525** [flutter/flutter#112527]
### issue_link

https://github.com/flutter/flutter/issues/110715

### Commit Hash

dart-lang/sdk@71ec88a4c6270b100e2bc90f6204b2651d2f860e

### Target

stable

### pr_link

https://github.com/flutter/engine/pull/36060

### Impacted Users

All stable users

### Impact Description

https://github.com/flutter/flutter/issues/110715#issuecomment-1235358168

### Workaround

No.

### Risk

low

### Test Coverage

yes

**Comment by AlexV525** [comment]
https://github.com/flutter/engine/pull/36060 actually rolls a dev Dart SDK, and https://github.com/dart-lang/sdk/commit/71ec88a4c6270b100e2bc90f6204b2651d2f860e is the commit to the stable branch.

**Comment by itsjustkevin** [comment]
Hey @AlexV525 could you open this cherry-pick request in the [dart-lang/sdk](https://github.com/dart-lang/sdk) repo?  As this is a request for a dart change, we need to track it there for the right attention to be on it.

**Comment by AlexV525** [comment]
@itsjustkevin The commit is landed on https://github.com/dart-lang/sdk/commit/71ec88a4c6270b100e2bc90f6204b2651d2f860e, should I open a new request then?

**Comment by itsjustkevin** [comment]
Doing some digging, this change landed in the [Dart 2.18.1](https://github.com/dart-lang/sdk/commit/c42a304ce78f37b717cc055abc503023871a7013) release, which was included in the Flutter 3.3.1 release 15 days ago.

Continuing my investigation, this dart PR was never reverted.
