### ISSUE TITLE
Implement a default FlutterFragment 

### ISSUE THREAD

**Issue by lukef** [flutter/flutter#11253]
For hybrid apps you might want to run flutter via a fragment. Not sure if this is possible.

**Comment by b-strauss** [comment]
see #10072

**Comment by xster** [comment]
For the record, #10072 is the reverse of the desired functionality. Instead of an Fragment->Activity adapter, we'd want a Fragment to be used as a Fragment by its parent.

**Comment by Hixie** [comment]
This is not something we're likely to work on in the comings months but patches are certainly welcome.
cc @mravn-google

**Comment by PaulWoitaschek** [comment]
I count this as the fundamental that's necessary so flutter can take off. 

Large apps will never start using flutter because you can't just start with one feature and expand progressively. Everything would have to be rewritten at once.

**Comment by matthew-carroll** [comment]
This Fragment now exists within the Android embedding refactor.  That refactor lives in a staging branch and will be merged upon completion.  The overall project for the refactor is here:
https://github.com/flutter/flutter/projects/27

Do not use any part of the refactor until it is merged to master.
