### ISSUE TITLE
Codesign is failing on libpath_ops.dylib missing

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#112520]
`./codesign.py 5c984c26ebc4a0a8897305d3c6bef70ced91090d`

Cannot find file /Users/flutter/codesign/1664338615_session/darwin-x64_artifacts.zip.staging/libpath_ops.dylib from config

**Comment by CaseyHillers** [comment]
This is preventing https://github.com/flutter/flutter/pull/112510 from being merged

**Comment by godofredoc** [comment]
\cc godofredoc

**Comment by XilaiZhang** [comment]
If I remember correctly this had been solved by the pull request under fujino/codesign.py

**Comment by christopherfujino** [comment]
The issue here is actually that Casey is running the version of the script that expects libpath_ops.dylib to be present, but it was introduced after flutter-3.2-candidate.5 was branched.

**Comment by christopherfujino** [comment]
Closing this as resolved. If you hit this, you're probably doing a cherrypick to a 3.3 hotfix, and you should codesign with codesign_stable.py instead.

**Comment by CaseyHillers** [comment]
@XilaiZhang please update the release workflow docs to include this

**Comment by XilaiZhang** [comment]
Sure,  created https://critique.corp.google.com/cl/477856270

**Comment by Hixie** [comment]
@XilaiZhang that CL landed, should we close this issue?

**Comment by XilaiZhang** [comment]
yes sir
