### ISSUE TITLE
M3 `CircularProgressIndicator` is not able to make its size larger than its default size.

### ISSUE THREAD

**Issue by QuncCccccc** [flutter/flutter#112583]
@QuncCccccc I am not able to make `CircularProgressIndicator` larger than its default size.

_Originally posted by @akshdeep-singh in https://github.com/flutter/flutter/issues/112139#issuecomment-1257071981_

**Comment by elkhalifte** [comment]
U can simply use it inside SizedBox and give the sizedbox a height and width.

**Comment by QuncCccccc** [comment]
> U can simply use it inside SizedBox and give the sizedbox a height and width.

The title might be misleading, just modified it:) This issue is used to track the problem that the M3 CircularProgressIndicator is not able to have a larger size after migration.
