### ISSUE TITLE
devicelab linux-27 device is quarantined due to device doctor failures

### ISSUE THREAD

**Issue by yusuf-goog** [flutter/flutter#112598]
```Quarantined: device doctor healthcheck error: b"error: protocol fault (couldn't read status): Connection reset by peer\nUnhandled exception:\nExecutable adb failed with exit code 1.\n#0 fail (package:device_doctor/src/utils.dart:35)\n#1 eval (package:device_doctor/src/utils.dart:109)\n<asynchronous suspension>\n#2 Future.timeout.<anonymous closure> (dart:async/future_impl.dart:870)\n<asynchronous suspension>\n#3 AndroidDeviceDiscovery._deviceListOutputWithRetries.<anonymous closure> (package:device_doctor/src/android_device.dart:54)\n<asynchronous suspension>\n#4 RetryOptions.retry (package:retry/retry.dart:131)\n<asynchronous suspension>\n#5 AndroidDeviceDiscovery._deviceListOutputWithRetries (package:device_doctor/src/android_device.dart:52)\n<asynchronous suspension>\n#6 AndroidDeviceDiscovery.discoverDevices (package:device_doctor/src/android_device.dart:74)\n<asynchronous suspension>\n#7 AndroidDeviceDiscovery.checkDevices (package:device_doctor/src/android_device.dart:104)\n<asynchronous suspension>\n#8 main (file:///b/s/w/ir/x/w/cocoon/device_doctor/bin/main.dart:67)\n<asynchronous suspension>\n"```

**Comment by yusuf-goog** [comment]
@keyonghan can you please look at this

**Comment by keyonghan** [comment]
It's back by itself..

**Comment by ricardoamador** [comment]
The log is filled with these messages: 
```
Sep 28 15:56:14 flutter-devicelab-linux-27 systemd[19172]: Startup finished in 20ms.
Sep 28 15:56:14 flutter-devicelab-linux-27 systemd[1]: Started User Manager for UID 1000.
Sep 28 15:56:31 flutter-devicelab-linux-27 python3[720]: 720 2022-09-28 22:56:31.808 E: device doctor healthcheck error: b'* daemon not running; starting now at tcp:5037\n* daemon started successfully\n'
Sep 28 15:56:37 flutter-devicelab-linux-27 python3[720]: 720 2022-09-28 22:56:37.316 E: device doctor healthcheck error: b'* daemon not running; starting now at tcp:5037\n* daemon started successfully\n'
Sep 28 15:57:38 flutter-devicelab-linux-27 python3[720]: 720 2022-09-28 22:57:38.307 E: device doctor healthcheck error: b"error: protocol fault (couldn't read status): Connection reset by peer\nUnhandled exception:\nExecutable adb failed with exit code 1.\n#0      fail (package:device_doctor/src/utils.dart:35)\n#1      eval (package:device_doctor/src/utils.dart:109)\n<asynchronous suspension>\n#2      Future.timeout.<anonymous closure> (dart:async/future_impl.dart:870)\n<asynchronous suspension>\n#3      AndroidDeviceDiscovery._deviceListOutputWithRetries.<anonymous closure> (package:device_doctor/src/android_device.dart:54)\n<asynchronous suspension>\n#4      RetryOptions.retry (package:retry/retry.dart:131)\n<asynchronous suspension>\n#5      AndroidDeviceDiscovery._deviceListOutputWithRetries (package:device_doctor/src/android_device.dart:52)\n<asynchronous suspension>\n#6      AndroidDeviceDiscovery.discoverDevices (package:device_doctor/src/android_device.dart:74)\n<asynchronous suspension>\n#7      AndroidDeviceDiscovery.checkDevices (package:device_doctor/src/android_device.dart:104)\n<asynchronous suspension>\n#8      main (file:///b/s/w/ir/x/w/cocoon/device_doctor/bin/main.dart:67)\n<asynchronous suspension>\n"
Sep 28 15:58:45 flutter-devicelab-linux-27 python3[720]: 720 2022-09-28 22:58:45.720 E: device doctor healthcheck error: b'* daemon not running; starting now at tcp:5037\n* daemon started successfully\n'
```

**Comment by yusuf-goog** [comment]
@ricardoamador @keyonghan is there anything else needed for this? Can we close?

**Comment by keyonghan** [comment]
This seems happening intermittently and recovers by itself later. Let's move to TD to track if any wider impact.

**Comment by ricardoamador** [comment]
No longer an issue. Bot is back in the staging lab and is active.
