### ISSUE TITLE
help me with this error [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(null-error, Host platform returned null value for non-null return value., null, null)

### ISSUE THREAD

**Issue by luisjulian3** [flutter/flutter#112533]
```
Using hardware rendering with device sdk gphone64 x86 64. If you notice graphics artifacts, consider enabling software rendering with
"--enable-software-rendering".
Launching lib/main.dart on sdk gphone64 x86 64 in debug mode...
Running Gradle task 'assembleDebug'...                             14.0s
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
Installing build/app/outputs/flutter-apk/app.apk...              1,629ms
E/flutter (10968): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(null-error, Host platform returned null value for non-null return value., null, null)
E/flutter (10968): #0      FirebaseCoreHostApi.optionsFromResource (package:firebase_core_platform_interface/src/pigeon/messages.pigeon.dart:242:7)
E/flutter (10968): <asynchronous suspension>
E/flutter (10968): #1      MethodChannelFirebase.initializeApp (package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart:89:25)
E/flutter (10968): <asynchronous suspension>
E/flutter (10968): #2      Firebase.initializeApp (package:firebase_core/src/firebase.dart:43:31)
E/flutter (10968): <asynchronous suspension>
E/flutter (10968): #3      main (package:login_screen/main.dart:12:3)
E/flutter (10968): <asynchronous suspension>
E/flutter (10968): 
Syncing files to device sdk gphone64 x86 64...                     248ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

💪 Running with sound null safety 💪
```

**Comment by darshankawar** [comment]
> E/flutter (10968): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(null-error, Host platform returned null value for non-null return value., null, null)
> E/flutter (10968): #0      FirebaseCoreHostApi.optionsFromResource (package:firebase_core_platform_interface/src/pigeon/messages.pigeon.dart:242:7)
> E/flutter (10968): <asynchronous suspension>
> E/flutter (10968): #1      MethodChannelFirebase.initializeApp (package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart:89:25)
> E/flutter (10968): <asynchronous suspension>
> E/flutter (10968): #2      Firebase.initializeApp (package:firebase_core/src/firebase.dart:43:31)
> E/flutter (10968): <asynchronous suspension>
> E/flutter (10968): #3      main (package:login_screen/main.dart:12:3)
> E/flutter (10968): <asynchronous suspension>
> E/flutter (10968):

Looking at this error, it seems you have not properly configured and intialized Firebase in your app.
Take a look at [this](https://stackoverflow.com/questions/72895721/firebasecloudmessaging-platformexception-platformexceptionnull-error-host-p) link and underlying solutions and check if that helps. 

If above doesn't help and you are seeing same error (assuming you are using Firebase and initializing it in your app), open issue in dedicated repo by providing all requested details in the new issue template: https://github.com/firebase/flutterfire/issues

Closing from here, as this looks more of a config issue.
