### ISSUE TITLE
[go_router] ShellRoute has "path" parameter in example in the documentation

### ISSUE THREAD

**Issue by lukkob** [flutter/flutter#112537]
According to the example which can be found in pub.dev documentation there's _path_ parameter in _ShellRoute_ constructor. I think it was added here by mistake as it's not true.

<img width="661" alt="Screenshot 2022-09-28 at 12 27 49" src="https://user-images.githubusercontent.com/2481960/192756508-309a32fa-c909-4804-b0a6-ab19a2ffdc67.png">

Link to the line which should be removed: https://pub.dev/documentation/go_router/latest/go_router/ShellRoute-class.html#:~:text=ShellRoute(-,path%3A%20%27/%27%2C,-builder%3A%20(BuildContext%20context

**Comment by danagbemava-nc** [comment]
Thanks for spotting that.
