### ISSUE TITLE
Flutter dart packaging

### ISSUE THREAD

**Issue by mlf2020** [flutter/flutter#112517]
Whether components of a plugin or package can be packaged (without source code), similar to native integration which can rely on either source code integration or Framework/AAR integration. I wonder if it is possible to rely on the packaged plugin or package in the pubspec.yaml file of the Flutter module? (So far the code pulled down through the  `flutter pub get` is in the form of source code)

**Comment by danagbemava-nc** [comment]
Hi @mlf2020, this is currently not possible. Moreover, this is not the correct place to file this issue. Kindly file an issue on the [pub repo](https://github.com/dart-lang/pub) if you want pub to support this. 

Closing from here as this isn't a flutter issue. 

Thank you

**Comment by mlf2020** [comment]
OK,thanks!
