### ISSUE TITLE
Camera view comes blank in Android 13 - No way to make it work

### ISSUE THREAD

**Issue by elmar001** [flutter/flutter#112521]
When camera opened for taking photo, camera view comes empty only in Android 13 device. It is not a glitch, force stop/killing app and opening again do not solve the issue. Camera and location permissions already granted and double checked. Unfortunately, cannot see log for now as that phone has only release version of the app. But the app and camera works without problem in Android 10 - Heawei P30 Pro, Android 11 - LG K51S, Android 12 - Samsung Galaxy A13 and iPhones.

Package version:   camera: ^0.10.0+1
Problem observed in: Android 13
Device: Google Pixed 4a

**Comment by elmar001** [comment]
This is what I can see in terminal when it happens:
E/flutter ( 6188): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: CameraException(error, Attempt to invoke virtual method 'int android.media.EncoderProfiles$VideoProfile.getWidth()' on a null object reference)
E/flutter ( 6188): #0      AndroidCamera.createCamera (package:camera_android/src/android_camera.dart:112:7)
E/flutter ( 6188): <asynchronous suspension>
E/flutter ( 6188): #1      CameraController.initialize (package:camera/src/camera_controller.dart:295:19)
E/flutter ( 6188): <asynchronous suspension>


-------------------
flutter doctor -v shows this:
[✓] Flutter (Channel stable, 2.10.5, on macOS 12.6 21G115 darwin-arm, locale
    en-AU)
    • Flutter version 2.10.5 at /users/elmar/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (5 months ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version
    33.0.0-rc3)
    • Android SDK at /Users/elmar/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] VS Code (version 1.71.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (3 available)
    • Pixel 4a (mobile) • 0B111JEC221689 • android-arm64  • Android 13 (API 33)
    • SM A135F (mobile) • R58T421WPYN    • android-arm    • Android 12 (API 31)
    • Chrome (web)      • chrome         • web-javascript • Google Chrome
      106.0.5249.61

[✓] HTTP Host Availability
    • All required HTTP hosts are available

**Comment by huycozy** [comment]
@elmar001 
>E/flutter ( 6188): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: CameraException(error, Attempt to invoke virtual method 'int android.media.EncoderProfiles$VideoProfile.getWidth()' on a null object reference)

This log is quite similar to the log in https://github.com/flutter/flutter/issues/109769#issue-1342800452. 
Could you please try upgrading your Flutter SDK to the latest stable channel (`3.3.3`) and try again? (Just to make sure that the issue still replicates on the new SDK version). Thanks!

**Comment by elmar001** [comment]
Thanks @huycozy. 
Sorry, I have many packages which may not fully work with Flutter sdk 3.3.3. So upgrading does not look like an option for now. Seems like there are several new release of this package recently. Is the issue fixed in any of them (for example latest version - camera: ^0.10.0+3) or fix is not possible without SDK update?

**Comment by huycozy** [comment]
>Is the issue fixed in any of them (for example latest version - camera: ^0.10.0+3) or fix is not possible without SDK update?

@elmar001 
The Flutter SDK upgrading is just to check if the log you get is exactly the same as #109769's log. 
As above thoughts, I find this issue quite similar to #109769 if you also look at its log. In case they are duplicated, you should follow up on #109769 for further updates. That issue has been labeled and many people also commented there, that will help to raise the issue.

**Comment by elmar001** [comment]
Thanks, seems like the same issue.

**Comment by huycozy** [comment]
@elmar001 Closing this issue as a duplicate, so please follow up on it for further updates. You can leave there your comment and react an upvote to the original comment will help to raise the issue. Thank you!
