### ISSUE TITLE
[iOS16] [video_player] [Web] Canvaskit in safari and chrome shows a black line on the video frame

### ISSUE THREAD

**Issue by negotoyolo** [flutter/flutter#112514]
I am having some issues viewing apps that display videos Deployed in Flutter Web, on iOS16 or later.
(Maybe just canvaskit surely)

1. safari and chrome show a black line on the border of the video. The frequency is often, and when I record the screen or take a screenshot on my iphone, the line is gone. Therefore, I will post a picture from outside.

2. The display is not correct in chrome. (Often)

I have tried stable,dev,master channel but it was not resolved.
I am using video_player: ^2.4.7.

## Steps to Reproduce

``

1. Deploy code sample to the web.(and set canvaskit)
2. Check the display in chrome and safari on iOS 16 or later. (Reload if unable to reproduce)

**Expected results:** 
Erase the black border. (Safari and chrome)
Fix the display. (chrome)

**Actual results:** 

| border(safari) | border(chrome) | view(chrome) |
| --------------- | --------------- | --------------- |
<img width="400" src="https://user-images.githubusercontent.com/50433979/192671679-d3e1f396-5d9a-46eb-92c2-72de3127ff61.jpg"> | <img width="400" src="https://user-images.githubusercontent.com/50433979/192671692-bb0b371a-51f5-4940-bc57-33f603a40c42.jpg"> | <img width="400" src="https://user-images.githubusercontent.com/50433979/192671710-77519703-307c-4734-bb12-dcbba31ba397.PNG">

<details>

<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:video_player/video_player.dart';

Future<void> main() async {
  runApp(const App());
}

class App extends StatelessWidget {
  const App({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const VideoApp();
  }
}

class VideoApp extends StatefulWidget {
  const VideoApp({Key? key}) : super(key: key);

  @override
  _VideoAppState createState() => _VideoAppState();
}

class _VideoAppState extends State<VideoApp> {
  late VideoPlayerController _controller;

  @override
  void initState() {
    super.initState();
    _controller = VideoPlayerController.network(
      'https://user-images.githubusercontent.com/50433979/192675261-50545583-37f7-49d6-8cae-952f51fcb617.mp4',
    )..initialize().then((_) {
        setState(() {});
      });
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Video Demo',
      home: Scaffold(
        backgroundColor: Colors.white,
        body: Center(
          child: _controller.value.isInitialized
              ? AspectRatio(
                  aspectRatio: _controller.value.aspectRatio,
                  child: VideoPlayer(_controller),
                )
              : Container(),
        ),
        floatingActionButton: FloatingActionButton(
          onPressed: () {
            setState(() {
              _controller.value.isPlaying
                  ? _controller.pause()
                  : _controller.play();
            });
          },
          child: Icon(
            _controller.value.isPlaying ? Icons.pause : Icons.play_arrow,
          ),
        ),
      ),
    );
  }

  @override
  void dispose() {
    super.dispose();
    _controller.dispose();
  }
}


```

</details>

<details>
  <summary>Logs</summary>

```
[√] Flutter (Channel master, 3.4.0-33.0.pre.10, on Microsoft Windows [Version 10.0.19044.1889], locale ja-JP)
    • Flutter version 3.4.0-33.0.pre.10 on channel master at E:\Hack\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4a8dbbd382 (16 hours ago), 2022-09-27 04:53:38 -0400
    • Engine revision 0631c3f870
    • Dart version 2.19.0 (build 2.19.0-243.0.dev)
    • DevTools version 2.17.0

[X] Windows Version (Unable to confirm if installed Windows version is 10 or greater)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Yu Oohama\AppData\Local\Android\Sdk
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop for Windows (Visual Studio Professional 2019 16.4.2)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional
    • Visual Studio Professional 2019 version 16.4.29613.14
    • Windows 10 SDK version 10.0.17763.0
    X Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop development with C++" workload, and include these components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK

[√] Android Studio (version 2021.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[√] VS Code (version 1.71.2)
    • VS Code at C:\Users\Yu Oohama\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.48.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19044.1889]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 105.0.5195.127
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 105.0.1343.50

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 3 categories.
```

</details>

<details>
  <summary>Here is the video for uploading here.</summary>

https://user-images.githubusercontent.com/50433979/192675261-50545583-37f7-49d6-8cae-952f51fcb617.mp4
</details>

**Comment by huycozy** [comment]
Hi @YuOohama, thanks for filing the issue. But I can not reproduce the issue on the latest `stable` and `master` channels with `video_player: ^2.4.7`

I tested with iOS simulators:
- iPhone 14 (iOS 16.0)
- iPhone 14 Pro Max (iOS 16.0)

<details>
<summary>Demo</summary>

| iPhone 14 | iPhone 14 Pro Max |
| --------------- | --------------- |
<img width="400" src="https://user-images.githubusercontent.com/104349824/192729723-81cb7eab-7be3-4ebc-8bcc-b8a7c34cc706.png"> | <img width="400" src="https://user-images.githubusercontent.com/104349824/192729748-257745fa-743f-422f-bf3a-2424c4aeea9e.png">

</details>

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 3.3.2, on macOS 12.6 21G115 darwin-x64, locale en-VN)
    • Flutter version 3.3.2 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e3c29ec00c (6 days ago), 2022-09-14 08:46:55 -0500
    • Engine revision a4ff2c53d8
    • Dart version 2.18.1
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13E113
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.71.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.6 21G115 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 105.0.5195.125

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

```bash
[✓] Flutter (Channel master, 3.4.0-33.0.pre.32, on macOS 12.6 21G115 darwin-x64, locale en-VN)
    • Flutter version 3.4.0-33.0.pre.32 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7ce121fed9 (89 minutes ago), 2022-09-27 21:40:12 -0400
    • Engine revision 46009cbe3d
    • Dart version 2.19.0 (build 2.19.0-247.0.dev)
    • DevTools version 2.17.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A309
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.71.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (3 available)
    • SM T225 (mobile) • R9JT3004VRJ • android-arm64  • Android 12 (API 31)
    • macOS (desktop)  • macos       • darwin-x64     • macOS 12.6 21G115 darwin-x64
    • Chrome (web)     • chrome      • web-javascript • Google Chrome 105.0.5195.125

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```
</details>

Which device are you testing for this issue? Can you retry on the emulator to see if the issue is still reproducible?

**Comment by YuOohama** [comment]
@huycozy Thanks for the reply.
First, did you set it to canvaskit at the time of deploy? This problem could only be at canvaskit. Then again, I don't have a Mac on hand, so I can't use the iOS simulator. I may be able to try it in a few days.
I am able to reproduce this on the actual device at hand, an iPhone13mini (iOS 16.0.2).

**Comment by huycozy** [comment]
Hi @YuOohama 
>did you set it to canvaskit at the time of deploy?

Yes, I used `canvaskit` renderer. I also try on my physical device iPhone 7 (iOS 15.7) and don't see the issue. Can you retry with the latest flutter stable channel? The latest version is `3.3.3`.

**Comment by YuOohama** [comment]
@huycozy 
I finally got to use my mac. From the results, it seems to be a problem specific to the iPhone mini series. I could see the border issue on the actual 13mini and on the simulator 12mini and 13mini, but not on the other devices. can you please try it on the 13mini?

**Comment by huycozy** [comment]
@YuOohama I tested on iPad mini, iOS 16.0 (I don't have any iPhone mini emulator using iOS 16.0) but still can not replicate it.

<details>
<summary>Demo (iPad mini)</summary>

<img width="400" src="https://user-images.githubusercontent.com/104349824/194207773-59d71068-ddea-4edf-8be2-46c9381be33b.png">

</details>

Please help to clarify something as below:
- Does this issue only happen with `canvaskit` renderer? Does it display well with `HTML`?
- Can you try with another video to see if it's still happening?
- Has it worked as intended before? Or does it only happen with the latest `video_player` and Flutter SDK version?

**Comment by YuOohama** [comment]
> * Does this issue only happen with `canvaskit` renderer? Does it display well with `HTML`?
Yes.

**Comment by huycozy** [comment]
>More than that, I have a display collapse of chrome on iOS16 canvaskit, is this a problem only with my iPhone13mini?

@negotoyolo this is the result from my physical device (iPhone 7, iOS 15.7), it displays normally. I'm not sure if this issue is only reproduced on a specific device.

<details>
<summary>Demo</summary>

<img width="350" src="https://user-images.githubusercontent.com/104349824/195249719-cb2b1838-d0dd-49df-a4dd-ae7a6f0f214c.png">

</details>

Can you provide deployed web page so that I can verify it? 
Also, you can try to deploy that video (only video asset) into a web server and open it with Chrome on your device to compare with Flutter web app.

**Comment by negotoyolo** [comment]
@huycozy 
https://flutter-play-ground-1ff92.web.app/#/
Deployed here.

The build command is this
"flutter build web --web-renderer canvaskit --release"

<details>

<summary>Code</summary>



```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const App());
}

class App extends StatelessWidget {
  const App({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Container(
          color: Colors.red,
        ),
      ),
    );
  }
}
```

</details>

These are the images as seen from the actual iPhone13 mini (IOS 16.0.3) and the actual iPad mini 6gen (iPad OS 15.7).
The image is shifted upward. Furthermore, it is drawn up by the amount of shifting and can be scrolled back to normal.
![image](https://user-images.githubusercontent.com/50433979/195260469-9a12f5ea-a349-492d-8143-326a1d76c945.png)
![IMG_0020](https://user-images.githubusercontent.com/50433979/195260475-20b63459-46d0-498d-bbcf-90f584b7cac8.png)

**Comment by huycozy** [comment]
>These are the images as seen from the actual iPhone13 mini (iOS 16.0.3) and the actual iPad mini 6gen (iPad OS 15.7).
The image is shifted upward. Furthermore, it is drawn up by the amount of shifting and can be scrolled back to normal.

@negotoyolo Would you mind if you file a new issue for this so that it's separated from the original issue? This may be a rendering issue on a common widget rather than plugin issue (video_player).
