### ISSUE TITLE
[animations] Let test time be accurate (originally has 1us shift)

### ISSUE THREAD

**Issue by fzyzcjy** [flutter/flutter#112612]
Fixed by https://github.com/flutter/packages/pull/2657, please see description there

## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @fzyzcjy, should this remain open? I'm asking because the PR linked to this issue has been closed.
