### ISSUE TITLE
Request to support webview on desktop platforms macOS, Linux, Windows

### ISSUE THREAD

**Issue by BppleMan** [flutter/flutter#112698]
## Use case

I am developing an application, which needs to use the ability to interact with webview. Currently webview-flutter only supports mobile iOS/Android. When I want to implement a simple desktop-webview by myself, I cannot hosting [desktop native view] in PlatformView, currently flutter only provides the function of hosting [mobile native view] in PlatformView.

**Comment by danagbemava-nc** [comment]
See 

https://github.com/flutter/flutter/issues/41725
https://github.com/flutter/flutter/issues/37597
https://github.com/flutter/flutter/issues/41726

Closing from here as duplicate.
