### ISSUE TITLE
Icons download and file_download are the same

### ISSUE THREAD

**Issue by cgutierr-zgz** [flutter/flutter#112642]
## Use case

I was having a look at the Material Icons at [https://fonts.google.com/icons](https://fonts.google.com/icons)
And I found that the icon `download` and `file_download` are the same, weirdly the only one matching the Material Icons from the web is the `file_download_outlined`
I guess the ones in the web are actually updated but not here

## Proposal

Update the Icons accordingly (I'm assuming there's prolly a ton more of this)

**Comment by huycozy** [comment]
@cgutierr-zgz Looks like you propose adding more missing icons from Google Fonts website, right? Please see this issue and leave there your comment: #99973

**Comment by cgutierr-zgz** [comment]
Hi @huycozy, nope, the problem is that the icons exists, but they are either out of date or wrong

**Comment by huycozy** [comment]
Hi @cgutierr-zgz As responded at https://github.com/flutter/flutter/issues/99973#issuecomment-1263234980, please take a look at #102560 for further updates.
Closing this issue as a duplicate. If you disagree, please write in the comments and I will reopen it. Thank you!
