### ISSUE TITLE
[Proposal] Camera resolution support outside the presets

### ISSUE THREAD

**Issue by nm-jiwonhae** [flutter/flutter#112615]
## Proposal
I would like the camera resolution to the one with 4:3 aspect ratio, similar to that of Android CameraX (https://developer.android.com/training/camerax/configuration#automatic-resolution). As far as I know, in CameraX, it searches for all the camera resolution supported by the camera and returns the one with the closest aspect ratio the user wants to use. I am not too sure whether similar method is offered in AVCaptureDevice, or AVCaptureSession though

**Comment by huycozy** [comment]
@nm-jiwonhae 
I see there are some similar issues to this proposal: #80393, #45665, #15953. Please see if there is any closest issue to your case.

**Comment by nm-jiwonhae** [comment]
They are very similar! 
In conjunction with the aspect ratio suggestion, I think in Android resolution set by the aspect ratio is determined by the device capability. 
(https://android.googlesource.com/platform/frameworks/support/+/27d045fbd961cb27edcacd2b93bd756adf5546e5/camera/camera2/src/main/java/androidx/camera/camera2/impl/SupportedSurfaceCombination.java)

**Comment by huycozy** [comment]
@nm-jiwonhae thanks for confirming. Please leave there your comment and react an upvote to the original comment will help to raise the issue. 
Closing this issue as a duplicate. Thank you!
