### ISSUE TITLE
Flutter widget is randomly disappearing when app is opened or restarted in release mode

### ISSUE THREAD

**Issue by anton-definit** [flutter/flutter#112638]
My image galley app is facing a strange issue. The widget (ReorderableWrap) which is responsible for displaying the actual image gallery after successful login is only showed sometimes/randomly. This is only happening in release mode, not in debug mode (flutter run --release).

By printing the length of the list holding the widgets to be displayed, I can verify that the list isn't empty at any times.

**What I have tried so far (as far as I remember):**

 - Changing the ReorderableWrap to a normal Wrap widget, and even a simple Column
 - Changing the gradle and kotlin version in app/build.gradle. I have tried updating and downgrading different version. 
 - Added delays before navigating to the GalleryScreen widget even though all related functionality is awaited.
 - Disable Android hardwareacceleration
 - Disable minification and shrink in manifest
 - Deleted gradle cache, both in user and in project directory
 - Switching Flutter versions: v3.0.5, v3.3.1 and v3.3.3 (current stable version)

**Steps on how/when I am facing the issue:**

 1. Running `flutter clean`
 2. Building the app successfully `flutter run --release`
 3. When the app is opened either the widget (ReorderableWrap) is displayed or not displayed.
 4. I close the app and open it again multiple times a the same thing is happening (the widget (ReorderableWrap) is displayed or not displayed).

**Code**

    import 'package:flutter/material.dart';
    import 'package:flutter_riverpod/flutter_riverpod.dart';
    import 'package:reorderables/reorderables.dart';
    import 'package:seekings_app/models/sub_gallery_level2_model.dart';
    import 'package:seekings_app/providers/gallery/gallery_provider.dart';
    import 'package:seekings_app/providers/loading_overlay/loading_overlay_provider.dart';
    import 'package:seekings_app/repository/seekings_plugin/plugin_sync_repo.dart';
    import 'package:seekings_app/shared_helpers/helper_screen.dart';
    import 'package:seekings_app/shared_static_classes/static_style.dart';
    
    class GalleryScreen extends ConsumerStatefulWidget {
      const GalleryScreen({Key? key}) : super(key: key);
    
      @override
      GalleryScreenState createState() => GalleryScreenState();
    }
    
    class GalleryScreenState extends ConsumerState<GalleryScreen> {
      @override
      void initState() {
        super.initState();
        var galleryNotifier = ref.read(galleryNotifierProvider);
        galleryNotifier.galleryIsVisible = true;
        galleryNotifier.buildWidgetList(); // <--- Filling galleryNotifier.galleryWidgetList with items
      }
    
      @override
      Widget build(BuildContext context) {
        var galleryNotifier = ref.watch(galleryNotifierProvider);
        var loadingOverlayNotifier = ref.read(loadingOverlayNotifierProvider);
    
        print(galleryNotifier.galleryWidgetList); // <--- Verifies that items are present in the list
    
        List<BottomNavigationBarItem> galleryMenu = [
          const BottomNavigationBarItem(
            label: "Ret galleri",
            icon: Icon(
              Icons.edit_note,
              color: StaticStyle.seekingsGreen,
            ),
          ),
          const BottomNavigationBarItem(
            label: "Opret galleri",
            icon: Icon(
              Icons.add,
              color: StaticStyle.seekingsGreen,
            ),
          ),
          const BottomNavigationBarItem(
            label: "Tilføj billeder",
            icon: Icon(
              Icons.add_photo_alternate,
              color: StaticStyle.seekingsGreen,
            ),
          ),
          const BottomNavigationBarItem(
            label: "Udgiv galleri",
            icon: Icon(
              Icons.share,
              color: StaticStyle.seekingsGreen,
            ),
          )
        ];
    
        if (galleryNotifier.currentGallery is SubGalleryLevel2) {
          galleryMenu.removeAt(1);
        }
    
        return Scaffold(
          floatingActionButton: galleryNotifier.galleryHasBeenModified && galleryNotifier.galleryIsVisible
              ? SizedBox(
                  width: HelperScreen(context).width - HelperScreen(context).screenPadding * 2,
                  child: Card(
                    elevation: 20,
                    color: StaticStyle.darken(StaticStyle.seekingsGreen),
                    child: ListTile(
                      dense: true,
                      title: StaticStyle.smallText("Tryk her for at gemme dine ændringer", bold: true, color: Colors.white, centered: true),
                      onTap: !loadingOverlayNotifier.loading
                          ? () async {
                              galleryNotifier.onTapGallerySync();
                              loadingOverlayNotifier.setLoad(true);
                              await PluginSyncRepo().setSyncData(galleryNotifier);
                              loadingOverlayNotifier.setLoad(false);
                            }
                          : null,
                    ),
                  ),
                )
              : null,
          bottomNavigationBar: !galleryNotifier.provideGalleryOverview && galleryNotifier.galleryIsVisible
              ? BottomNavigationBar(
                  type: BottomNavigationBarType.fixed,
                  unselectedFontSize: 12,
                  selectedFontSize: 12,
                  selectedItemColor: StaticStyle.darkGrey,
                  unselectedItemColor: StaticStyle.darkGrey,
                  onTap: (index) {
                    if (galleryNotifier.currentGallery != null) {
                      if (galleryNotifier.currentGallery is SubGalleryLevel2) {
                        switch (index) {
                          case 0:
                            galleryNotifier.onTapGalleryEdit(context, galleryNotifier.currentGallery!);
                            break;
                          case 1:
                            galleryNotifier.onTapGalleryAddImages(context, galleryNotifier.currentGallery!);
                            break;
                          case 2:
                            galleryNotifier.onTapSocialMediaPublish(context, galleryNotifier.currentGallery!);
                            break;
                          default:
                        }
                      } else {
                        switch (index) {
                          case 0:
                            galleryNotifier.onTapGalleryEdit(context, galleryNotifier.currentGallery!);
                            break;
                          case 1:
                            galleryNotifier.onTapGalleryAddFolder(context, galleryNotifier.currentGallery!);
                            break;
                          case 2:
                            galleryNotifier.onTapGalleryAddImages(context, galleryNotifier.currentGallery!);
                            break;
                          case 3:
                            galleryNotifier.onTapSocialMediaPublish(context, galleryNotifier.currentGallery!);
                            break;
                          default:
                        }
                      }
                    }
                  },
                  items: galleryMenu,
                )
              : null,
          body: SingleChildScrollView(
            child: Padding(
              padding: EdgeInsets.all(HelperScreen(context).screenPadding),
              child: SizedBox(
                width: double.infinity,
                child: Column(children: [
                  !galleryNotifier.provideGalleryOverview && galleryNotifier.currentGallery != null
                      ? Column(
                          children: [
                            Container(
                              width: HelperScreen(context).widthNoPadding,
                              decoration: const BoxDecoration(
                                color: StaticStyle.lighterGrey,
                                borderRadius: BorderRadius.all(
                                  Radius.circular(3),
                                ),
                              ),
                              child: SingleChildScrollView(
                                scrollDirection: Axis.horizontal,
                                child: Container(
                                  padding: const EdgeInsets.all(5),
                                  child: Row(
                                    children: galleryNotifier.getBreadcrumbString(),
                                  ),
                                ),
                              ),
                            ),
                            const SizedBox(height: 10),
                            galleryNotifier.currentGallery!.images.isNotEmpty
                                ? Container(
                                    width: HelperScreen(context).widthNoPadding,
                                    decoration: BoxDecoration(
                                      color: StaticStyle.lighten(StaticStyle.lighterGrey),
                                      borderRadius: const BorderRadius.all(
                                        Radius.circular(3),
                                      ),
                                    ),
                                    child: Padding(
                                      padding: const EdgeInsets.all(5.0),
                                      child: StaticStyle.smallText("Træk i billederne for sortering. Dobbeltklik for markering."),
                                    ),
                                  )
                                : const SizedBox(),
                            StaticStyle.headerText(galleryNotifier.currentGallery!.name),
                            galleryNotifier.selectedImages.isNotEmpty
                                ? Container(
                                    padding: const EdgeInsets.only(top: 10, bottom: 5),
                                    margin: const EdgeInsets.only(bottom: 15),
                                    decoration: const BoxDecoration(
                                        color: Colors.white,
                                        borderRadius: BorderRadius.all(
                                          Radius.circular(8),
                                        ),
                                        boxShadow: [
                                          BoxShadow(blurRadius: 20, color: Colors.black26)
                                        ]),
                                    child: Column(
                                      children: [
                                        galleryNotifier.selectedImages.length > 1 ? StaticStyle.normalText("Hvad vil du gøre med de " + galleryNotifier.selectedImages.length.toString() + " valgte billeder?", bold: true, color: StaticStyle.seekingsBlue) : StaticStyle.normalText("Hvad vil du gøre med det valgte billede?", bold: true, color: StaticStyle.seekingsBlue),
                                        const SizedBox(height: 10),
                                        BottomNavigationBar(
                                          elevation: 0,
                                          backgroundColor: Colors.transparent,
                                          type: BottomNavigationBarType.fixed,
                                          unselectedFontSize: 12,
                                          selectedFontSize: 12,
                                          selectedItemColor: StaticStyle.darkGrey,
                                          unselectedItemColor: StaticStyle.darkGrey,
                                          onTap: (index) {
                                            switch (index) {
                                              case 0:
                                                galleryNotifier.onTapDeleteSelectedImages(context);
                                                break;
                                              case 1:
                                                galleryNotifier.onTapPublishSelectedImages(context);
                                                break;
                                              default:
                                            }
                                          },
                                          items: [
                                            BottomNavigationBarItem(
                                              label: "Slet " + galleryNotifier.selectedImages.length.toString() + " billede" + (galleryNotifier.selectedImages.length > 1 ? "r" : ""),
                                              icon: const Icon(
                                                Icons.delete,
                                                color: Colors.red,
                                              ),
                                            ),
                                            BottomNavigationBarItem(
                                              label: "Udgiv " + galleryNotifier.selectedImages.length.toString() + " billede" + (galleryNotifier.selectedImages.length > 1 ? "r" : ""),
                                              icon: Icon(
                                                Icons.share,
                                                color: StaticStyle.lighten(StaticStyle.facebookBlue, 0.2),
                                              ),
                                            ),
                                          ],
                                        ),
                                      ],
                                    ),
                                  )
                                : const SizedBox(),
                          ],
                        )
                      : Column(
                          crossAxisAlignment: CrossAxisAlignment.center,
                          children: [
                            StaticStyle.headerText("Dine billedgallerier"),
                            StaticStyle.normalText("Her kan du administrere alle dine billedgallerier", centered: true),
                            const SizedBox(height: 20),
                            ElevatedButton(
                              child: const Text("Opret et nyt hovedgalleri"),
                              style: ElevatedButton.styleFrom(
                                primary: StaticStyle.seekingsGreen,
                              ),
                              onPressed: () async {
                                galleryNotifier.onTapGalleryAddFolder(context, galleryNotifier.currentGallery);
                              },
                            ),
                            const SizedBox(height: 20),
                          ],
                        ),
    
                  // Widget that is showing randomly:
                  ReorderableWrap(
                    children: galleryNotifier.galleryWidgetList,
                    needsLongPressDraggable: true,
                    onReorder: (oldIndex, newIndex) => galleryNotifier.onReordering(oldIndex, newIndex),
                  ),
                ]),
              ),
            ),
          ),
        );
      }
    }

**App dependencies**

      cupertino_icons: ^1.0.2
      flutter_riverpod: ^1.0.4
      device_info_plus: ^4.0.0
      percent_indicator: ^4.2.2
      pin_code_fields: ^7.4.0
      flutter_spinkit: ^5.1.0
      url_launcher: ^6.1.0
      # rest_client: ^2.1.4
      rest_client: ^2.1.5+3
      crypto: ^3.0.2
      catcher: ^0.7.0
      uuid: ^3.0.6
      flutter_facebook_auth: ^4.4.1+1
      intl: ^0.17.0
      image_picker: ^0.8.5+3
      connectivity_plus: ^2.3.2
      json_annotation: ^4.5.0
      reorderables: ^0.5.0
      cached_network_image: ^3.2.2
      string_validator: ^0.3.0
      image: ^3.2.0
      path_provider: ^2.0.11
      package_info_plus: ^1.4.2
      camera: ^0.10.0+1
      dropdown_button2: ^1.7.2
      get_storage: ^2.0.3
      gallery_saver: ^2.3.2
      heic_to_jpg:
        git:
          url: https://github.com/anton-definit/heic_to_jpg
      flutter_image_compress: ^1.1.3

**Other information**

 - Flutter version: 3.3.3
 - Dart version: 2.18.2
 - Gradle version: `com.android.tools.build:gradle:7.3.0`
 - Gradle wrapper version: 7.5.1
 - Kotlin version: 1.7.10

I hope someone has any idea on how to solve this issue or at least are able to point in some direction on what to do.

Please let me know if you need more information or code snippets to understand the problem.

**Comment by danagbemava-nc** [comment]
Hi @anton-definit, please provide a complete minimal reproducible code sample without any third-party packages so that we can investigate this. 

Thank you
