### ISSUE TITLE
WillPopScope not working with go_router

### ISSUE THREAD

**Issue by mahboobahmed6577** [flutter/flutter#112684]
WillPopScope(
      onWillPop: () async {
        log('WillPopScope: working in call');
        return new Future(() => true);
      }
child: Scaffold())

I am using go_router for navigating through pages in Web. Here onWillPop seems to be never called. How can we listen when back button pressed on WEB.

**Comment by huycozy** [comment]
@mahboobahmed6577 Thanks for the report! This is a known issue being tracked at #102408 as it is directed from https://github.com/flutter/flutter/issues/99706#issuecomment-1112678801.
Closing this issue as a duplicate, so please follow up on it for further updates.
