### ISSUE TITLE
ErrorWidget class example doesn't work

### ISSUE THREAD

**Issue by gh-pap** [flutter/flutter#112688]
## Steps to Reproduce

Run the dartpad embedded at the top of this page https://api.flutter.dev/flutter/widgets/ErrorWidget-class.html and click the (funnier name than they thought) button "Error Prone".

**Expected results:** 
I expected to see the the exception message 'oh no, an error' as a yellow-on-blue message.

**Actual results:** 
Just a blank screen (and the console says 'Script error.')

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by huycozy** [comment]
Hi @gh-pap, I also see it doesn't work as expected on that website. But it works well on local machine (web platform).

<details>
<summary>Demo</summary>

<img width="725" alt="Screen Shot 2022-09-30 at 17 11 07" src="https://user-images.githubusercontent.com/104349824/193248153-11b51d5d-13da-41f1-831b-35945d15adc6.png">
</details>

Can you retry on your local machine?

**Comment by huycozy** [comment]
@gh-pap It seems that it's a DartPad issue since the issue is also reproducible on `dartpad.dev`, you can try it on https://dartpad.dev/?id=f1915c87cab02aaf40d006190e99c7be.
If you have the same behavior, please open the issue in the dedicated [dart-pad's repository](https://github.com/dart-lang/dart-pad/issues). Thanks!

**Comment by gh-pap** [comment]
Yes, it works well on my local machine (web platform). And yes, it doesn't work on dartpad.dev. I'll raise a ticket there. Thanks for your help.

**Comment by gh-pap** [comment]
Raised this as a dartpad issue (https://github.com/dart-lang/dart-pad/issues/2381)
