### ISSUE TITLE
[web] use trusted types in the engine

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#112654]
We should change the engine to use the [trustedTypes](https://developer.mozilla.org/en-US/docs/Web/API/Trusted_Types_API) API, if available, to load CanvasKit. This will enable developers to enforce trusted types in their apps.

We should also enforce trusted types in our own tests to make sure our own code does not violate trusted type policies.

Google internal issue: b/193141863

**Comment by ditman** [comment]
flutter.js will also need to use TT for this to be fully complete. I'm going to try to use the counter app (no plugins, no deferred loading) as a verification mechanism.

**Comment by ditman** [comment]
I've created a new issue for flutter/flutter.
