### ISSUE TITLE
flutter-win-6 is dead and not ssh-able, has ssd failure

### ISSUE THREAD

**Issue by ricardoamador** [flutter/flutter#112644]
![image](https://user-images.githubusercontent.com/32242716/193080682-1c8bf7fe-dadd-4feb-afef-032ec24a0f40.png)

**Comment by ricardoamador** [comment]
I was unable to ssh to the machine.

**Comment by ricardoamador** [comment]
@yusuf-goog Would you mind taking a look next time you are in the lab?

**Comment by yusuf-goog** [comment]
This machine has hit the SSD failure. will need to be swapped out. Possible
on monday, since we should still have win capacity?

**Comment by ricardoamador** [comment]
Leaves one windows bot in the staging pool. It has been out of commission for 3 Weeks. Should be fine for a couple more days.

**Comment by ricardoamador** [comment]
Tracking in the mentioned issue.
