### ISSUE TITLE
Large regression in DevFS sync time

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#112640]
https://flutter-flutter-perf.skia.org/e/?begin=1663717510&end=1664452663&keys=X7334e3d3acaad001c0f0f3e5c8edd413&requestType=0&selected=commit%3D31329%26name%3D%252Carch%253Darm%252Cbranch%253Dmaster%252Cconfig%253Ddefault%252Cdevice_type%253DiPhone_6s%252Cdevice_version%253DiOS-15.5%252Chost_type%253Dmac%252Csub_result%253DhotReloadInitialDevFSSyncMilliseconds%252Ctest%253Dhot_mode_dev_cycle_macos_target__benchmark%252C&xbaroffset=31328

Due to https://github.com/flutter/flutter/pull/110721 and https://github.com/flutter/flutter/pull/112602

@jonahwilliams @andrewkolos @jason-simmons

**Comment by jonahwilliams** [comment]
First thing to verify is whether we're syncing the expected assets or not

**Comment by jonahwilliams** [comment]
I think we can get this performance back by caching more of the IO work in the asset directory cache. Example diff:

```
diff --git a/packages/flutter_tools/lib/src/asset.dart b/packages/flutter_tools/lib/src/asset.dart
index 17b728cd02..6ced08b927 100644
--- a/packages/flutter_tools/lib/src/asset.dart
+++ b/packages/flutter_tools/lib/src/asset.dart
@@ -1019,6 +1019,7 @@ class _AssetDirectoryCache {
 
   final FileSystem _fileSystem;
   final Map<String, List<String>> _cache = <String, List<String>>{};
+  final Map<String, List<File>> _variantsPerFolder = <String, List<File>>{};
 
   List<String> variantsFor(String assetPath) {
     final String directory = _fileSystem.path.dirname(assetPath);
@@ -1030,25 +1031,22 @@ class _AssetDirectoryCache {
     if (_cache.containsKey(assetPath)) {
       return _cache[assetPath]!;
     }
-
-    final List<FileSystemEntity> entitiesInDirectory = _fileSystem.directory(directory).listSync();
-
-    final File assetFile = _fileSystem.file(assetPath);
-    final List<String> pathsOfVariants = <String>[
-      // It's possible that the user specifies only explicit variants (e.g. .../1x/asset.png),
-      // so there does not necessarily need to be a file at the given path.
-      if (assetFile.existsSync())
-        assetPath,
-      ...entitiesInDirectory
+    if (!_variantsPerFolder.containsKey(directory)) {
+      _variantsPerFolder[directory] = _fileSystem.directory(directory)
+        .listSync()
         .whereType<Directory>()
         .where((Directory dir) => _assetVariantDirectoryRegExp.hasMatch(dir.basename))
         .expand((Directory dir) => dir.listSync())
         .whereType<File>()
+        .toList();
+    }
+    final File assetFile = _fileSystem.file(assetPath);
+    final List<File> potentialVariants = _variantsPerFolder[directory]!;
+    return _cache[assetPath] = <String>[
+      assetPath,
+      ...potentialVariants
         .where((File file) => file.basename == assetFile.basename)
         .map((File file) => file.path),
     ];
-
-    _cache[assetPath] = pathsOfVariants;
-    return pathsOfVariants;
   }
 }
```

**Comment by jonahwilliams** [comment]
It also appears that calling `.basename` is _very_ expensive, which is quite surprising. If we can re-arrange this code to not use it we'll probably go faster. It bottoms out to Directory._current which hits the filesystem.

**Comment by jonahwilliams** [comment]
With @jason-simmons fix we're down to just _slightly_ slower than we were before:

![image](https://user-images.githubusercontent.com/8975114/193177896-58e6e635-9680-4696-a28c-cd3028c81467.png)


https://github.com/flutter/flutter/pull/112651 will cache more agressively and should reduce this even further

**Comment by jonahwilliams** [comment]
I think we're back to (and possibly below) the old performance numbers: https://flutter-flutter-perf.skia.org/e/?begin=1661583600&end=1664567615&queries=sub_result%3DhotReloadInitialDevFSSyncMilliseconds&xbaroffset=31328

![image](https://user-images.githubusercontent.com/8975114/193355321-a60f54f9-65b4-4c71-b320-25bc04687c63.png)

**Comment by zanderso** [comment]
Thanks, all! Great work.
