### ISSUE TITLE
Flutter Studio App for making Flutter apps on Android Tablets and iPad.

### ISSUE THREAD

**Issue by Mesum-Hussain** [flutter/flutter#112680]
## Use case

Tablets are becoming good enough nowadays for performing heavy tasks like app development. Even the operating systems on them are improving to enable multitasking workflows. I think Flutter should also work on them.

But coding on a virtual keyboard is really not ideal and using a keyboard case is just a workaround which I think people shouldn't need to use while trying to do some serious work on their Tablet alone.

## Proposal

Flatter should make an app for Tablets (let's call it Flutter Studio App) to make Flutter apps with, which eliminates the need of typing code. Maybe a Node based visual scripting language like in Unreal Engine or a new kind of visual language should be used to make program files, which are essentially a graphical diagram in a file representing the Flutter program. A project folder can contain many such files, and it should appear in the Flutter Studio App in a directory tree on the left side of the screen (maybe in a Navigation Drawer), just like any other traditional code editor. Those graphical files should be converted to the Flutter code by the Flutter Studio App while compiling the project. Flutter Studio App should also be able to read a Flutter project which wasn't written using it, and display it in the graphical diagram format so that the user can edit a codebase too.
Git should also be supported.
Text input should be reduced as much as possible to avoid the need of an external keyboard and whatever little text input is needed (for variable names, function names, etc) should be manageable by the virtual keyboard.

It would be even better if the Flutter Studio App showed a small preview window of the app in development in the real time while we make changes in the program files.

This could be the official solution from Flutter, for development on touchscreen smart devices. Essentially making it the first framework to support development on Tablets and Phones, by providing a tailored interface suitable for such devices.

**Comment by stuartmorgan** [comment]
> Essentially making it the first framework to support development on Tablets and Phones

This isn't really possible; Flutter doesn't compile native applications directly, but leverages existing platform toolchains to compile and bundle the application. Building a Flutter application for iOS, for example, uses Xcode, do can't run on a iPad since Xcode doesn't exist for iPad.

Closing as this is not feasible until there is first-party support for self-hosted development on these platforms.

**Comment by Mesum-Hussain** [comment]
> > Essentially making it the first framework to support development on Tablets and Phones
> 
> This isn't really possible; Flutter doesn't compile native applications directly, but leverages existing platform toolchains to compile and bundle the application. Building a Flutter application for iOS, for example, uses Xcode, so can't run on a iPad since Xcode doesn't exist for iPad.
> 
> Closing as this is not feasible until there is first-party support for self-hosted development on these platforms.

I understand. Xcode is probably coming to iPad soon if the rumours are to be believed. 

But what about Android apps though? As far as I know, Flutter doesn't really require Android Studio to make those apps on other platforms like Windows and Linux. From my limited experience with Flutter, I know that I can create Android apps using VS Code and Flutter CLI tools. Is there any way to do the same on an Android Tablet, and as a matter of fact on an iPad? Can't we create at least Android apps on Android Tablets and iPads?

**Comment by stuartmorgan** [comment]
There are other fundamental problems with what you are describing. For instance, iOS doesn't allow applications to run other processes, so there's no way to run a build system even if one were available.

This simply isn't feasible at this point, which is why you don't see self-hosted development support for these platforms currently.

**Comment by Mesum-Hussain** [comment]
> iOS doesn't allow applications to run other processes, so there's no way to run a build system even if one were available.
> 
> This simply isn't feasible at this point, which is why you don't see self-hosted development support for these platforms currently.

What about Android though? Can it be made possible to at least make Android apps on Android using Flutter?
I have already seen some proprietary apps somehow managing to allow users to make basic Android apps, so it's a proven concept at least. And apparently Node JS also works using Termux app, so React Native apps can be made too.
But I am not sure about the feasibility of doing it with Flutter.
