### ISSUE TITLE
Dart -> Engine roll blocked on analyze_snapshot mac link error

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#112687]
https://github.com/flutter/engine/pull/36515

https://ci.chromium.org/ui/p/flutter/builders/try/Mac%20iOS%20Engine%20Release/545/overview

```
FAILED: clang_x64/analyze_snapshot 
clang++ -isysroot /opt/s/w/ir/cache/osx_sdk/XCode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk -mmacosx-version-min=10.13.0 -rdynamic -fembed-bitcode -arch x86_64 -nostdlib++ -stdlib=libc++ -Wl,-dead_strip -Wl,-search_paths_first -L. -Wl,-rpath,@loader_path/. -Wl,-rpath,@loader_path/../../.. -Wl,-pie -Wl,-add_empty_section,__CUSTOM,__space_for_note  -Xlinker -rpath -Xlinker @executable_path/Frameworks -o clang_x64/analyze_snapshot -Wl,-filelist,clang_x64/analyze_snapshot.rsp  -ldl -lpthread -framework CoreFoundation -framework Security -framework Foundation -framework CoreServices
ld: could not open bitcode temp file: (null) for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

The current theory from chat is that https://github.com/dart-lang/sdk/commit/b0c4ddf9196738d9c8a162521b61bcefb7aa4c0a is doing something incompatible with bitcode.

Possibly the addition of `ldflags = [ "-Wl,-add_empty_section,__CUSTOM,__space_for_note" ]` to the linker flags.

@jason-simmons @a-siva @sstrickl

**Comment by sstrickl** [comment]
I've made [CL 262161](https://dart-review.googlesource.com/c/sdk/+/262161) to revert the linker flag (as well as the clang DEPS changes those enabled, since we were no longer overwriting parts of the `__text` section) until we can figure out how to reintroduce it in this case.

**Comment by chinmaygarde** [comment]
This is related to https://github.com/flutter/flutter/issues/112726 and was reverted.
