### ISSUE TITLE
when i pinch on the trackpad, the pointerCount should be 2, but get 1

### ISSUE THREAD

**Issue by zhujiageng** [flutter/flutter#112635]
## problem
when two-finger gesture update on trackpad, the pointerCount in UpdateDetails is not as expected. it should be 2, but get 1. 

## Steps to Reproduce

1. run this code
``` dart
import 'package:flutter/material.dart';

void main() {
  runApp(const App());
}

class App extends StatelessWidget {
  const App({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      title: 'Trackpad Gesture',
      home: HomePage(),
    );
  }
}

class HomePage extends StatefulWidget {
  const HomePage({super.key});

  @override
  State<HomePage> createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: GestureDetector(
        onScaleUpdate: (details) {
          // when i pinch on the trackpad, the pointerCount should be 2, but get 1
          print('onScaleUpdate, pointerCount:${details.pointerCount}');
        },
      ),
    );
  }
}
```

2. put two fingers on trackpad to trigger gestures, pinch or pan

**Expected results:**
the pointerCount logged should be 2

**Actual results:**
the pointerCount logged is 1

## flutter env
Flutter 3.3.0 • channel unknown • unknown source
Framework • revision ffccd96b62 (4 weeks ago) • 2022-08-29 17:28:57 -0700
Engine • revision 5e9e0e0aa8
Tools • Dart 2.18.0 • DevTools 2.15.0

**Comment by moffatman** [comment]
The operating system usually doesn't say how many fingers are used on the trackpad, it could be 2, 3, or more. So the value will never be trustworthy. I probably should have set it to 2 instead of 1 though. Out of curiosity what are you using the value for?

**Comment by zhujiageng** [comment]
@moffatman trackpad has two pan gesture types, the one is one finger click and drag, the one is two finger scroll, not clicked. i want to use the pointerCount to distinguish between the two. 
i use pan gesture to draw line, but the two-finger pan can't change the cursor, so every draw start with the same origin point, it's not my expect. so i just want disable the two-finger pan gesture.

**Comment by moffatman** [comment]
OK. All the two-finger pan gesture will have deviceType set to `PointerDeviceKind.trackpad`. And click-and-drag will have a different deviceType like `PointerDeviceKind.mouse` or `PointerDeviceKind.touch`. If you are using flutter 3.4 beta, there is an easy parameter on `GestureDetector` to filter the devices. If not, you can see here for some more examples of different methods: https://docs.flutter.dev/release/breaking-changes/trackpad-gestures

**Comment by danagbemava-nc** [comment]
Hi @zhujiageng, does https://github.com/flutter/flutter/issues/112635#issuecomment-1262987876 help you achieve what you want to achieve?

Hi @moffatman should this be treated as a proposal instead?

**Comment by moffatman** [comment]
Sure, it can be a proposal, I'm not sure if it's the right behavior or not. I couldn't decide during development whether to put 1 or 2, then forgot about it.
