### ISSUE TITLE
Overscroll stretch animation makes SliverAppBar stretch when pinned is true

### ISSUE THREAD

**Issue by Joaaofiilho** [flutter/flutter#112691]
When using a _SliverAppBar_ with the property _pinned_ set to true, the overscroll stretch animation stretches the SliverAppBar instead of just the other content of the screen.

When not using a SliverAppBar inside a CustomScrollView (aka the most popular way: a scaffold with an appbar and a body), it behaves differently: Only the body stretches.

Current behavior (SliverAppBar inside a CustomScrollView):

https://user-images.githubusercontent.com/26173202/193195619-e0a19db0-977c-4a92-a09b-5c593fdf497a.mp4

Expected behavior (Scaffold with the app bar and body properties set):

https://user-images.githubusercontent.com/26173202/193195736-938d7536-b37a-4597-b352-3dff90c0cbe0.mp4

_I thought a bit before posting this issue: "Is that really an issue or just intended?" but I came to a conclusion: If the user specifically wrote that it wants the appbar to be pinned, I think it expects it to behave as a regular app bar would (like me did 😁). So... It's your choices to decide if it is an issue or not!_

----

```
[√] Flutter (Channel stable, 3.3.3, on Microsoft Windows [versÆo 10.0.22000.856], locale pt-BR)
[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[√] Chrome - develop for the web
[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2021.2)
[√] VS Code (version 1.70.2)
[√] Connected device (4 available)
    ! Device RQ8N5001GPD is not authorized.
      You might need to check your device for an authorization dialog.
[√] HTTP Host Availability

! Doctor found issues in 2 categories.
```

**Comment by huycozy** [comment]
Hi @Joaaofiilho, 
Thanks for the report! This is a known issue being tracked at #104437 (the OP is using `SliverAppBar.medium`/ `SliverAppBar.large` which has `pinned = true` by default).
Closing this issue as a duplicate, so please follow up on it for further updates.
