### ISSUE TITLE
[Dart] analysis_option.yaml bug - analyser-exclude option doesn't seems to work with folders with a '(' in there name

### ISSUE THREAD

**Issue by nicolasmol** [flutter/flutter#112659]
Environment
```
Flutter 3.3.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision e3c29ec00c (il y a 2 semaines) • 2022-09-14 08:46:55 -0500
Engine • revision a4ff2c53d8
Tools • Dart 2.18.1 • DevTools 2.15.0
System:    Kernel: 5.15.0-48-generic x86_64 bits: 64 compiler: N/A Desktop: Cinnamon 5.2.7 
           wm: muffin dm: LightDM Distro: Linux Mint 20.3 Una base: Ubuntu 20.04 focal 
```
Bug found: 
Just look at this screen capture.
Those two folders do have the exact same content.
The one on the right has "(" int it's name. There the exclude seems not to be taken into account.
![image](https://user-images.githubusercontent.com/61077647/193111672-3269cf58-3982-41c1-9b59-31de66cf8914.png)

**Comment by danagbemava-nc** [comment]
Hi @nicolasmol, this issue should be reported on the dart-lang repo. 

Here's the link https://github.com/dart-lang/sdk/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc.

Closing from here as this is not a flutter issue. 

Thank you

**Comment by nicolasmol** [comment]
Ok cool.
Done
