### ISSUE TITLE
Uncaught FormatException: SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON

### ISSUE THREAD

**Issue by Bryanmuloni** [flutter/flutter#112632]
Hi team,
I am facing this error after deploying to Firebase, on localhost everything works quite well and fails in release mode on Firebase hosting. It has confused me if the problem is on Flutter or Firebase. This came about after adding support for localization in English, Spanish, French, and Arabic.
![invalid_json_error](https://user-images.githubusercontent.com/12647392/193007592-e03f0ab5-fb2a-4bdc-aaa9-76b2576a8526.PNG)
![main_js_file](https://user-images.githubusercontent.com/12647392/193008072-eb572f73-37dd-4410-9a93-34d70abd4ed4.PNG)

**Comment by huycozy** [comment]
@Bryanmuloni please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this. Also, please provide the output of `flutter doctor -v` as well.
Thank you!

**Comment by minhlivemore** [comment]
I got the same issue, everything is fine on local but cannot deploy
Flutter Web Bootstrap: Programmatic
main.dart.js:4077 Uncaught FormatException: SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
    at Object.c (http://localhost:8080/main.dart.js:4077:3)
    at Object.al9 (http://localhost:8080/main.dart.js:5876:9)
    at zq.cL (http://localhost:8080/main.dart.js:29366:17)
    at http://localhost:8080/main.dart.js:18262:22
    at a3p.a (http://localhost:8080/main.dart.js:5234:63)
    at a3p.$2 (http://localhost:8080/main.dart.js:27829:14)
    at a2z.$1 (http://localhost:8080/main.dart.js:27823:21)
    at a1m.Ue (http://localhost:8080/main.dart.js:28475:32)
    at a1m.v0 (http://localhost:8080/main.dart.js:28477:21)
    at a_O.$0 (http://localhost:8080/main.dart.js:28110:11)

**Comment by MaurizioSodano** [comment]
Hi, I am experiencing the same problem, using Flutter, Firebase hosting and google_maps_flutter dependency. 
In localhost I have no problems. The applications starts, show the maps and apply the style correctly. When hosted on firebase it behaves differently throwing the same exception.

the output of flutter doctor -v is this:

`[√] Flutter (Channel stable, 3.3.3, on Microsoft Windows [Versione 10.0.22621.521], locale it-IT)
    • Flutter version 3.3.3 on channel stable at C:\Users\MaurizioSodano\fvm\default
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18a827f393 (3 days ago), 2022-09-28 10:03:14 -0700
    • Engine revision 5c984c26eb
    • Dart version 2.18.2
    • DevTools version 2.15.0

[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at C:\Users\MaurizioSodano\AppData\Local\Android\sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] IntelliJ IDEA Community Edition (version 2021.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.3.2
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code, 64-bit edition (version 1.71.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.48.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 106.0.5249.91
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 105.0.1343.53
    ! Device emulator-5554 is offline.

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!`

the reprodicible sample is here https://github.com/MaurizioSodano/flutter_firebase_issue

And the steps to reproduce are written in the Readme.md:
1. get a google_maps_api_key https://developers.google.com/maps/documentation/javascript/get-api-key
2. put this key in web/index.html <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY"></script>
3. run the application: flutter run -d chrome
4. it should run without problem
5. create a firebase project
6. enable the firebase hosting
7. link your code to firebase project : firebase init hosting (remember to use build/web as public directory)
8. build your flutter code: flutter build web
9. deploy on your hosting space: firebase hosting:channel:deploy map-style-issue 
10. open the hosting site and enable the developer mode
11. inspect the error on the web console, you should see this error: Uncaught FormatException: SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
