### ISSUE TITLE
[CP] Revert egl presentation time

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#112603]
### issue_link

https://github.com/flutter/flutter/issues/110885

### Commit Hash

d7b64e2d942fa1635cff3a7a0bc47859d096afd5

### Target

stable

### pr_link

https://github.com/flutter/engine/pull/36491

### Impacted Users

All Android developers

### Impact Description

Frames will be scheduled below the target frame rate on devices with a refresh rate greater than 60hz. This is very noticable during scrolling.

### Workaround

There is no workaound.

### Risk

low

### Test Coverage

yes

### Validation Steps

Run the example app linked in https://github.com/flutter/flutter/issues/112503 on a high frame rate android device (Pixel 6) and observe the scrolling behavior as it slows down.

**Comment by itsjustkevin** [comment]
@zanderso could we get a review here?

**Comment by zanderso** [comment]
CP lgtm

**Comment by WingCH** [comment]
There seems to be no temporary solution to this problem 😵
 Hope it can be merged to the stable branch as soon as possible

**Comment by jonahwilliams** [comment]
This has landed
