### ISSUE TITLE
pow doesn't work properly with some very specific numbers

### ISSUE THREAD

**Issue by swumatmusit** [flutter/flutter#112613]
1. try to calculate by using specific numbers
2.0.034 * pow(10,18) returns 34000000000000004
3. other sets of numbers(e.g 0.34 * pow(10,18) or 0.033 * pow(10,18)) works properly
4. 0.034 * pow(10,1n) returns weird values

**Expected results:** 34000000000000000

**Actual results:** 34000000000000004

<details>
<summary>Code sample</summary>

          print(0.34 * pow(10,18)); // 340000000000000000.0
          print(0.033 * pow(10,18)); // 33000000000000000.0
          print(0.034 * pow(10,18)); // 34000000000000004.0 <- this one
          print(0.035 * pow(10,18)); // 35000000000000000.0
          print(0.034 * pow(10,19)); // -287189298506124770.0
          print(0.034 * pow(10,20)); // 264053507469376260.0
          // using BigInt did not help
```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by mraleph** [comment]
That's how floating point arithmetic works, consider reading https://floating-point-gui.de/

If you want arbitrary precision use decimal arithmetic instead through a third party package.
