### ISSUE TITLE
Tabbular App Bar fails in one project but succeeds in another

### ISSUE THREAD

**Issue by hungrymonkey** [flutter/flutter#11267]
## Steps to Reproduce

I am learning how to create mobile apps at the moment. I cannot give an in-depth bug report. I am reporting a bug because similar code does not render.

In lib/views/main.dart, setting the TabBarView seems to fail in one application but succeed in another. Of course, I can manually create a widget list and not use a switch and map statements. I wonder if this code is worthy of a bug report.

working build 

https://github.com/hungrymonkey/pregnant_watermelon/tree/567712d47f31e26b53eb6ebc203f73324e404248

https://github.com/hungrymonkey/pregnant_watermelon/blob/567712d47f31e26b53eb6ebc203f73324e404248/lib/main.dart

failed build

https://github.com/hungrymonkey/weather_app/blob/df30be259af667ffd06546eb73795031a5b7a881/lib/main.dart

https://github.com/hungrymonkey/weather_app/tree/df30be259af667ffd06546eb73795031a5b7a881

Step to repoduce
1. download weather_app project
2. Build it
3. Run it
3. TabBarView fails and leave a blank page
4. Error is thrown
```
I/flutter (31980): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (31980): The following assertion was thrown during performLayout():
I/flutter (31980): 'package:flutter/src/widgets/sliver.dart': Failed assertion: line 215: 'child != null': is not true.
I/flutter (31980): 
I/flutter (31980): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (31980): more information in this error message to help you determine and fix the underlying cause.
I/flutter (31980): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (31980):   https://github.com/flutter/flutter/issues/new
```
Expected Results
Reproduce the same steps with pregnant watermelon commit 7fbb55828d3b0986fcee559bde351a119803bf1b

The TabBarView renders properly. 

I am wondering what am I doing differently between pregnant_watermelon and  weather_app. The code is almost the same but one fails and the other succeeds. The pages does not matter because I change the page in pregnant_watermelon to the same all MyHomePage and it succeeded.

Either throw warning sign in pregnant_watermelon or throw a better error in my_weather app to figure out what is going on.

## Logs

Run your application with `flutter run` and attach all the log output.

Run `flutter analyze` and attach any output of that command also.

[flutter_run_log.txt](https://github.com/flutter/flutter/files/1156094/flutter_run_log.txt)

[analyze_log.txt](https://github.com/flutter/flutter/files/1156100/analyze_log.txt)

## Flutter Doctor

Paste the output of running `flutter doctor` here.

```
 [✓] Flutter (on Linux, locale en_US.UTF-8, channel alpha)
    • Flutter at /home/rice/flutter
    • Framework revision d36e2f6191 (4 weeks ago), 2017-06-21 15:09:10 -0700
    • Engine revision b0dee695ec
    • Tools Dart version 1.24.0-dev.6.7

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.0)
    • Android SDK at /home/rice/Android/Sdk
    • Platform android-26, build-tools 26.0.0
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] Android Studio (version 2.3)
    • Android Studio at /opt/android-studio
    • Gradle version 3.2
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.1)
    • Flutter plugin version 15.1
    • Dart plugin version 171.4694.29

[✓] Connected devices
    • SM G900P • 8e90eeee • android-arm • Android 7.1.2 (API 25)
```

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by Piinks** [comment]
Hi @hungrymonkey, 
It seems some of your reference links are now broken, and when running the weather app you provided, it produced a very different error. 
Are you still experiencing this issue? I realize it was some time ago and there may have been a change that resolved this issue.

**Comment by hungrymonkey** [comment]
Hi @Plinks, 

Yes, the links are broken. I deleted the project a long time ago. 

The bug is nested scaffolds. I believe another flutter maintainer has commented any nested scaffolds behavior is undefined.  

You can close this bug whenever you wish since this bug has many duplicates.

**Comment by Piinks** [comment]
Ah. Thank you for clarifying. I'm going to see if I can find one of these dupes that we can refer to before closing. Thanks!

**Comment by hungrymonkey** [comment]
@piinks The issue is pretty common.

https://github.com/flutter/flutter/issues/23106

**Comment by Piinks** [comment]
Thanks much! I will close this issue then. :)
