### ISSUE TITLE
Double tap a word in a TextField to select it

### ISSUE THREAD

**Issue by Ivaskuu** [flutter/flutter#11279]
On Android you can double tap a word in a text field to select it, but in a flutter TextField this doesn't seem to work. You need to long press to select it.

## Steps to Reproduce

- Add a new TextField
- Write some words
- Double tap a word

**Comment by joelfaul** [comment]
This seems to be a duplicate of [#9288](https://github.com/flutter/flutter/issues/9288) which contains a full discussion of the topic.

**Comment by zoechi** [comment]
@joelfaul thanks. Closing as dup.
