### ISSUE TITLE
First letter capital in a TextField

### ISSUE THREAD

**Issue by Ivaskuu** [flutter/flutter#11278]
It would be nice to have an option to have the first letter in a TextField capital (A instead of a).

## Steps to Reproduce

- Add a TextField
- Click the TextField

**Comment by eseidelGoogle** [comment]
This was implemented at least for iOS I believe (by @cbracken).  Unsure what the status is for Android?

**Comment by cbracken** [comment]
I definitely implemented support for this on the engine side but I don't *think* I've plumbed the auto-capitalisation setting through to the framework yet. Shouldn't be much work at all though.

**Comment by cbracken** [comment]
Related #10632, which I've started working on.

**Comment by watzon** [comment]
What's the status on this? And are there any workarounds for the time being?

**Comment by Hixie** [comment]
We aren't currently working on this, though we would welcome patches if anyone has the time to contribute one. It shouldn't be too difficult to implement if the engine side is indeed already implemented.

**Comment by cbracken** [comment]
FWIW this should be the default behaviour for all text fields with keyboard type of `text` or `multiline`, except for password fields (with `obscureText` set to `true`).

**Comment by perezd** [comment]
Looks like this could be closed:
https://github.com/flutter/flutter/issues/10632
https://docs.flutter.io/flutter/material/TextField/textCapitalization.html

**Comment by cbracken** [comment]
Yep!

**Comment by nhat108** [comment]
```
TextField(
textCapitalization: TextCapitalization.sentences,
)
```

**Comment by michaeldelcid** [comment]
Does this also work on flutter web or is it strictly IOS/android?

**Comment by nturgut** [comment]
@cbracken  @michaeldelcid This also works on Flutter web: https://github.com/flutter/engine/blob/bf6d7b4e48bfb6abfdb70fb5943a5ac87bd3dd26/lib/web_ui/lib/src/engine/text_editing/text_capitalization.dart#L14

We noticed a bug on IOS Safari (https://github.com/flutter/engine/blob/bf6d7b4e48bfb6abfdb70fb5943a5ac87bd3dd26/lib/web_ui/lib/src/engine/text_editing/text_capitalization.dart#L64), otherwise all browsers should work.

**Comment by bhanuka96** [comment]
This one is okay. https://github.com/flutter/flutter/issues/11278#issuecomment-519432374 but problem is user can type lowercase.

My Solution for this

**TextInputFormatter** 
```
class FirstUpperCaseTextFormatter extends TextInputFormatter {
  @override
  TextEditingValue formatEditUpdate(TextEditingValue oldValue, TextEditingValue newValue) {
    return newValue.copyWith(text: newValue.text.capitalizeFirstofEach);
  }
}
```
**capitalizeFirstofEach extenstion**
```
extension CapExtension on String {
  String get capitalizeFirstofEach => this.split(" ").map((str) => str.inCaps).join(" ");
}
```
**Any TextFields**
```
 textCapitalization: TextCapitalization.sentences,
 inputFormatters: [FirstUpperCaseTextFormatter()],
```
