### ISSUE TITLE
[android][platform views] Magnifier not working with TLHC

### ISSUE THREAD

**Issue by delfme** [flutter/flutter#112712]
Hello! Android magnifier doesnt work properly. I noticed the issue with editText widget but it is not working for every type of View.

## Steps to Reproduce

**1) Execute `flutter run` on the code sample**

Lib folder is also available here
https://drive.google.com/file/d/1mL3YV9kRTDJ8HwAtfywQW47jN9KLSBCn/view?usp=sharing

**Main.dart** 

```
import 'dart:io' show Platform;
import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/gestures.dart';
import 'package:flutter/rendering.dart';
import 'package:flutter/services.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'EditText Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
        appBar: AppBar(
          title: Text('EditText - Platform View'),
        ),
        body: Center(
          child: Padding(
            padding: EdgeInsets.fromLTRB(40, 0, 40, 0),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              mainAxisAlignment: MainAxisAlignment.center,
              children: const <Widget>[
                const Text('Android EditText:'),
                SizedBox(height: 8),
                SizedBox(
                  height: 50,
                  child: NativeTextBox(),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}

class NativeTextBox extends StatelessWidget {
  const NativeTextBox({super.key});

  @override
  Widget build(BuildContext context) {
    const String viewType = 'native-widget';
    const Map<String, dynamic> creationParams = <String, dynamic>{};
    if(!Platform.isAndroid) {
      return Text('Implemented only for Android!');
    }

    return PlatformViewLink(
      viewType: viewType,
      surfaceFactory:
          (context, controller) {
        return AndroidViewSurface(
          controller: controller as AndroidViewController,
          gestureRecognizers: const <Factory<OneSequenceGestureRecognizer>>{},
          hitTestBehavior: PlatformViewHitTestBehavior.opaque,
        );
      },
      onCreatePlatformView: (params) {
        return PlatformViewsService.initSurfaceAndroidView(
          id: params.id,
          viewType: viewType,
          layoutDirection: TextDirection.ltr,
          creationParams: creationParams,
          creationParamsCodec: const StandardMessageCodec(),
          onFocus: () {
            params.onFocusChanged(true);
          },
        )
          ..addOnPlatformViewCreatedListener(params.onPlatformViewCreated)
          ..create();
      },
    );
  }
}
```

**Expected results:**
Magnifier glass should display magnified text as in this video below.

https://user-images.githubusercontent.com/53510751/193296334-3a9359f8-8d0a-4558-943d-25067e0dbd7f.mp4

**Actual results:** 
Here is a video showing the issue. It is worth noticing that the magnifier widget appears on the proper gesture, but its background is transparent, its position seems not correct, and it doesn’t display the magnified text. From other tests I noticed that magnifier glass do not work with every type of view, not just the textfield.

https://user-images.githubusercontent.com/53510751/193295448-f8373d30-5e19-4566-bf40-3c56777e75fe.mp4

Flutter doctor:
[✓] Flutter (Channel stable, 3.3.2, on macOS 12.2 21D49 darwin-arm, locale en-IT)
[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

**Comment by phanvankhaicd** [comment]
I update newest version Flutter, It work well :3

**Comment by delfme** [comment]
Thanks for letting me know. Is it stable channel or master?

**Comment by danagbemava-nc** [comment]
Hi @delfme, please provide the corresponding native code for the platform-view.

Thank you

**Comment by delfme** [comment]
@phanvankhaicd It is not working with flutter 3.3.3.

@danagbemava-nc I did nothing on the native side, but here it is:

```
package com.example.flutter_platform_views_example;

import io.flutter.embedding.android.FlutterActivity;
import io.flutter.embedding.engine.FlutterEngine;
import android.content.Context;
import android.view.View;
import android.widget.EditText;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import io.flutter.plugin.platform.PlatformView;
import io.flutter.plugin.common.StandardMessageCodec;
import io.flutter.plugin.platform.PlatformViewFactory;
import java.util.Map;

public class MainActivity extends FlutterActivity {
    @Override
    public void configureFlutterEngine(@NonNull FlutterEngine flutterEngine) {
        flutterEngine
            .getPlatformViewsController()
            .getRegistry()
            .registerViewFactory("native-widget", new NativeViewFactory());
    }
}

class NativeView implements PlatformView {
   @NonNull private final EditText editor;

    NativeView(@NonNull Context context, int id, @Nullable Map<String, Object> creationParams) {
        editor = new EditText(context);
    }

    @NonNull
    @Override
    public View getView() {
        return editor;
    }

    @Override
    public void dispose() {}
}

class NativeViewFactory extends PlatformViewFactory {

  NativeViewFactory() {
    super(StandardMessageCodec.INSTANCE);
  }

  @NonNull
  @Override
  public PlatformView create(@NonNull Context context, int id, @Nullable Object args) {
    final Map<String, Object> creationParams = (Map<String, Object>) args;
    return new NativeView(context, id, creationParams);
  }
}
```

**Comment by delfme** [comment]
Tested also from master and it doesnt work. @phanvankhaicd can you share a video of it working? 

@danagbemava-nc I tested it from two different machines on both stable and master channels.

**Comment by huycozy** [comment]
@delfme thanks for providing the sample code. This issue is reproducible on the latest `stable` and `master` channels.
I also have the same result as above.

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 3.3.3, on macOS 12.6 21G115 darwin-x64, locale en-VN)
    • Flutter version 3.3.3 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18a827f393 (10 hours ago), 2022-09-28 10:03:14 -0700
    • Engine revision 5c984c26eb
    • Dart version 2.18.2
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode14.0.1.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2022.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 70.0.5
    • Dart plugin version 222.4167.21

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.71.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (4 available)
    • SM T225 (mobile)           • R9JT3004VRJ                          • android-arm64  • Android 12 (API 31)
    • iPhone 14 Pro Max (mobile) • 332079AF-E895-4685-910E-7B1E18B0C6B8 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-0 (simulator)
    • macOS (desktop)            • macos                                • darwin-x64     • macOS 12.6 21G115 darwin-x64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 105.0.5195.125

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

```bash
[✓] Flutter (Channel master, 3.4.0-37.0.pre.14, on macOS 12.6 21G115 darwin-x64, locale en-VN)
    • Flutter version 3.4.0-37.0.pre.14 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 35afe1bdac (45 minutes ago), 2022-10-03 18:41:23 -0700
    • Engine revision 83c68740e3
    • Dart version 2.19.0 (build 2.19.0-268.0.dev)
    • DevTools version 2.17.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode14.0.1.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2022.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 70.0.5
    • Dart plugin version 222.4167.21

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.71.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (3 available)
    • SM T225 (mobile) • R9JT3004VRJ • android-arm64  • Android 12 (API 31)
    • macOS (desktop)  • macos       • darwin-x64     • macOS 12.6 21G115 darwin-x64
    • Chrome (web)     • chrome      • web-javascript • Google Chrome 105.0.5195.125

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```
</details>

Labeling this issue for further investigation from the team!

**Comment by delfme** [comment]
Is there a workaround to make magnifier work before the bug gets fixed?

**Comment by JoseBarreto1** [comment]
here also the android magnifier not working

**Comment by delfme** [comment]
@JoseBarreto1 I have made other tests and this looks more serious than excepted. Android magnifier is not working everywhere. For example, it is broken also when applied to an Image (to let the user magnify image spots) or a note (for text selection).

Bad news is that magnifier is auto-enabled by android for all textView and we cannot dispose it. Hence the user will notice the bug. @huycozy It would be helpful if flutter could disable magnifier somehow until bug is fixed.

**Comment by delfme** [comment]
Can someone at Google please have a look at this? It should be easy to fix at low level, but if not fixed it makes impossible to use native widgets that support the magnifier lense, because bug is severe and user will report this issue / assign to app a 1-star review.

**Comment by delfme** [comment]
[Update] To whom it may concern.

Just discovered that magnifier lens works on Hybrid Composition (so I’m updating issue title). Also, noticed a weird thing. HC textfield widget takes a bit more to load than TLHC equivalent, but then it performs faster. How that can be?

To notice performance issue with TLHC, just extend code to support multiline, onChange pass textfield’s height to Dart in order to setState on new line to update UI, you will see that communication is somehow faster with HC.

**Comment by delfme** [comment]
Unfortunately, HC loading time is so big that makes it unusable. A fix for TLHC is much needed.

**Comment by delfme** [comment]
@blasten @stuartmorgan hope you dont mind me mentioning but would you be so kind as to shed some light on this? 🙏 Is there a way to have magnifier work also with TLHC?

**Comment by stuartmorgan** [comment]
Please don't ping random people.

**Comment by johnmccutchan** [comment]
An alternative to using HC mode is to switch Flutter from using a SurfaceView to a TextureView. In that case the magnifier renders correctly.

**Comment by delfme** [comment]
Hello @johnmccutchan how that would be doable in this case?

I mean on dart side we have
```
return PlatformViewLink(
  viewType: NativeTextInput.viewType,
  surfaceFactory: (context, controller) => AndroidViewSurface(
    controller: controller as AndroidViewController,
    hitTestBehavior: PlatformViewHitTestBehavior.opaque,
    gestureRecognizers: const <Factory<OneSequenceGestureRecognizer>>{},
  ),
  onCreatePlatformView: (PlatformViewCreationParams params) {
    return PlatformViewsService.initExpensiveAndroidView(
        id: params.id,
        viewType: NativeTextInput.viewType,
```

We would enable TLHC via `initSurfaceAndroidView`
```
  onCreatePlatformView: (PlatformViewCreationParams params) {
     return PlatformViewsService.initSurfaceAndroidView( 
```

But that breaks the Magnifer.

On the native side we use android editText :
```
import android.view.View
import android.widget.EditText
...
override fun getView(): View {
    return editText
}
```

**Comment by johnmccutchan** [comment]
You do this in the Java side, FlutterActivity has an overridable method:

```
@NonNull
  @Override
  public RenderMode getRenderMode() {
    return RenderMode.texture;
  }
```

**Comment by delfme** [comment]
@johnmccutchan can you please provide a sample code? We cant make our textfield work with the magnifer without using HC.
PS: our native side is in kotlin, but anything would be useful.

**Comment by delfme** [comment]
If that is okay for you, will add here a sample code to let you try your idea there. We would like to dismiss HC.

**Comment by delfme** [comment]
![4369BAB5-712F-45D9-AFF7-86FCCFBDF57E](https://github.com/flutter/flutter/assets/53510751/f6121f56-f2e5-40a4-b0c5-086b021f1c4b)


Here it is 
https://github.com/delfme/flutter_native_text_view_sample
Magnifier works only with HC
https://github.com/delfme/flutter_native_text_view_sample/blob/c2ba598a5f58ee8c7bb2c0d8f526c99c8805f76d/lib/flutter_native_text_view.dart#L171-L174

**Comment by delfme** [comment]
I think it is worth to also make a point here, that is not technical yet meaningful.
We have being coding a sort of premium messaging app with the look&feel level of Whatsapp, just to give a reference. 

Text widget is great and we use it almost everywhere inside app - like labels, menu, titles, etc..
But when it comes to "note" or "text editor" we go native, coz users expect that thing from a premium app. So Platform View, with proper use, is such a big thing for us.

**Comment by johnmccutchan** [comment]
In this file:

https://github.com/delfme/flutter_native_text_view_sample/blob/main/example/android/app/src/main/kotlin/dev/henryleunghk/flutter_native_text_view_example/MainActivity.kt

You need to override the getRenderNode method as I explained in this comment:

https://github.com/flutter/flutter/issues/112712#issuecomment-1806031597

**Comment by delfme** [comment]
Thx @johnmccutchan I confirm his idea is working!
For those who might need a code sample, here it is:

```
import io.flutter.embedding.android.FlutterActivity
import io.flutter.embedding.android.RenderMode

class MainActivity : FlutterActivity() {
    override fun getRenderMode(): RenderMode {
        return RenderMode.texture
    }
}
```
