### ISSUE TITLE
Unable to prevent the mouse from scrolling listview

### ISSUE THREAD

**Issue by au-top** [flutter/flutter#112741]
## Steps to Reproduce

1.  use mouse scroll wheel

**Expected results:** listview  no scroll

**Actual results:** listview scroll

<details>
<summary>Code sample</summary>

```dart
 ScrollConfiguration(
      behavior: ScrollConfiguration.of(context).copyWith(dragDevices: {PointerDeviceKind.touch}),
      child:ListView.builder(
            ......
       )
)

```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by aashish-d** [comment]
For making ListView no scroll use
ListView.builder(
              physics: NeverScrollableScrollPhysics(),)

**Comment by au-top** [comment]
> NeverScrollableScrollPhysics

good but 
What if I want to use gestures instead of wheels

If 'NeverScrollableScrollPhysics' is set, all scrolling will be turned off

**Comment by aashish-d** [comment]
yes, this will turned off scrolling for listView

**Comment by huycozy** [comment]
@au-top Please see if this issue is similar to yours/can solve your issue: https://github.com/flutter/flutter/issues/35723

**Comment by au-top** [comment]
yes he is  similar

**Comment by huycozy** [comment]
@au-top thanks for confirming. 
Closing this issue as a duplicate, so please follow up on it for further updates. You can leave there your comment and react an upvote to the original comment will help to raise the issue. Thank you!
