### ISSUE TITLE
firebase_auth fails silently if SHA Fingerprint is not added

### ISSUE THREAD

**Issue by pauldemarco** [flutter/flutter#11277]
## Steps to Reproduce

1. Attempt to use firebase_auth without first adding the android key to the firebase fingerprints list.
2. Notice that is silently fails with no indicative warning.

I only consider this an issue since it's not mentioned in the setup docs and it took me quite a bit to figure out.

**Comment by kroikie** [comment]
@pauldemarco

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/979. Any further collaboration will be done there.
