### ISSUE TITLE
[go_router] Redirect examples in documentation use incorrect method signature

### ISSUE THREAD

**Issue by ryan-andrew** [flutter/flutter#112754]
All of the examples in the documentation for the `redirect` field on the `GoRouter` class now use the incorrect signature.

One such example from the docs:

```dart
final GoRouter _router = GoRouter(
  routes: <GoRoute>[
    GoRoute(
      path: '/',
      redirect: (_) => '/family/${Families.data[0].id}',
    ),
    GoRoute(
      path: '/family',
      pageBuilder: (BuildContext context, GoRouterState state) => ...,
    ),
    GoRoute(
      path: '/:username',
      pageBuilder: (BuildContext context, GoRouterState state) => ...,
    ),
  ],
);
```

The `GoRouterRedirect` callback now takes a `BuildContext` in addition to the `GoRouterState` that was there before.

For the examples to compile, we would need to  change the constructor parameter to something like:

```dart
redirect: (_, __) => '/family/${Families.data[0].id}',
```

**Comment by stuartmorgan** [comment]
https://github.com/flutter/flutter/issues/102679 should be fixed for go_router as part of fixing this, to prevent this kind of issue in the future.

**Comment by chunhtai** [comment]
Hi @stuartmorgan this is in API doc string, does code excerpt supports doc string?

**Comment by stuartmorgan** [comment]
Ah, I didn't realize it was in code. I think the repo tooling currently only looks at md files, but it could potentially be expanded to code files.
