### ISSUE TITLE
Migrate new version

### ISSUE THREAD

**Issue by RenaSki** [flutter/flutter#112749]
## Steps to Reproduce

1. ... I have a project using an older version of Flutter, and I'm trying to migrate to a new version of Flutter. I get an error that says "Yor Flutter application is created using an older version of the Android embedding. It is being deprecated in favor of Android embedding v2. Follow the steps at https://flutter.dev/go/android-project-migration " when I run the code. However, a URL given in the console doesn't exist anymore. How do I migrate my project to the new version of Flutter?
2. 
3. ...
4. ...

## Logs

<details>
<summary>Logs</summary>

```
```

[√] Flutter (Channel stable, 2.10.5, on Microsoft Windows [Version 10.0.22000.978], locale en-US)
    • Flutter version 2.10.5 at C:\flutter_windows_2.10.5-stable\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (6 months ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[!] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK a
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at 

[!] Visual Studio - develop for Windows (Visual Studio Community 2022 17.3.3)
    • Visual Studio at 
    • Visual Studio Community 2022 version 17.3.32825.248
    • Windows 10 SDK version 10.0.19041.0
    X Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop
      development with C++" workload, and include these components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK

[√] Android Studio (version 2021.3)
    • Android Studio at 
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[√] VS Code (version 1.71.2)
    • VS Code at 
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22000.978]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 105.0.5195.127
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 105.0.1343.42

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.
```
```

</details>

**Comment by darshankawar** [comment]
@RenaSki 
This has been already fixed as part of https://github.com/flutter/website/issues/7267.
You will need to upgrade to latest stable to see the change.
Closing.
