### ISSUE TITLE
[iOS] App is disconnecting when running profile mode

### ISSUE THREAD

**Issue by martingeorgiu** [flutter/flutter#112708]
I wasn't able to reproduce this error with a clear repository. However, on my project, which sadly I cannot share, it is occurring every time. The issue is that if I run my app in profile mode on iOS and then start to use some of the Dart DevTools features like "CPU Profiler" or inspecting "Performance" after circa 5 sec the app disconnects. When I run it in verbose mode, the only output is:

```
[+18759 ms] Service protocol connection closed.
[        ] Lost connection to device.
[   +2 ms] "flutter run" took 226,324ms.
[ +100 ms] ensureAnalyticsSent: 98ms
[        ] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 0
```

Even though it is somehow connected to my app, there seems to be some issue with the Dart DevTools which accidentally disconnects the app when trying to analyze the app.

<details>
  <summary>Logs</summary>
[log-output.txt](https://github.com/flutter/flutter/files/9684956/log-output.txt)

```
Analyzing ikem-online-app...                                    

warning • The include file 'package:lint/analysis_options.yaml' in '/Users/georgiu/code/flutter/ikem-online-app/flutter-cpp-modules/detect_rectangle/analysis_options.yaml' can't be found when analyzing '/Users/georgiu/code/flutter/ikem-online-app/flutter-cpp-modules/detect_rectangle' • flutter-cpp-modules/detect_rectangle/analysis_options.yaml:1:10 • include_file_not_found
   info • 'primary' is deprecated and shouldn't be used. Use foregroundColor instead. This feature was deprecated after v3.1.0. • lib/core/ui/screens/opening_screen.dart:79:29 • deprecated_member_use
   info • The import of 'dart:typed_data' is unnecessary because all of the used elements are also provided by the import of 'package:flutter/services.dart' • lib/core/ui/screens/pdf_attachment_screen.dart:1:8 • unnecessary_import
   info • 'primary' is deprecated and shouldn't be used. Use foregroundColor instead. This feature was deprecated after v3.1.0. • lib/core/ui/themes/app_theme.dart:22:7 • deprecated_member_use
   info • 'primary' is deprecated and shouldn't be used. Use backgroundColor instead. This feature was deprecated after v3.1.0. • lib/core/ui/themes/app_theme.dart:35:7 • deprecated_member_use
   info • 'primary' is deprecated and shouldn't be used. Use foregroundColor instead. This feature was deprecated after v3.1.0. • lib/core/ui/widgets/attachment_view.dart:130:19 • deprecated_member_use
   info • 'primary' is deprecated and shouldn't be used. Use foregroundColor instead. This feature was deprecated after v3.1.0. • lib/lab_results/ui/widgets/lab_value_filter.dart:62:21 • deprecated_member_use
   info • 'primary' is deprecated and shouldn't be used. Use backgroundColor instead. This feature was deprecated after v3.1.0. • lib/prescriptions/ui/screens/prescription_detail_screen.dart:151:31 • deprecated_member_use

8 issues found. (ran in 3.0s)
```

```
[✓] Flutter (Channel stable, 3.3.2, on macOS 12.6 21G115 darwin-arm, locale en-CZ)
    • Flutter version 3.3.2 on channel stable at /Users/georgiu/.fvm/versions/3.3.2
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e3c29ec00c (2 weeks ago), 2022-09-14 08:46:55 -0500
    • Engine revision a4ff2c53d8
    • Dart version 2.18.1
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/georgiu/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/georgiu/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/georgiu/Library/Android/sdk
    • Java binary at: /Users/georgiu/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/213.7172.25.2113.9014738/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Users/georgiu/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/212.5712.43.2112.8815526/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] Android Studio (version 2021.3)
    • Android Studio at /Users/georgiu/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/213.7172.25.2113.9014738/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.2.2)
    • IntelliJ at /Users/georgiu/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Ultimate Edition (version 2022.2.2)
    • IntelliJ at /Users/georgiu/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/222.4167.29/IntelliJ IDEA.app
    • Flutter plugin can be installed from:

      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.71.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.6 21G115 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 105.0.5195.125

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

</details>

**Comment by huycozy** [comment]
Hi @martingeorgiu 
For the issue to be workable, it needs to be reproducible with a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code. Please provide such a sample.
Thank you!

**Comment by martingeorgiu** [comment]
Hello @huycozy, sure that's understandable. I did more digging and realized that the disconnecting was caused by `CircularProgressIndicator` in `SizeTransition` widget. Even though the widget was hidden it was still triggering frame builds 60 times per second, so the Performance tab in Dart DevTools became quite bloated after a while. Then when I wanted to look into one of the frames, the Dart DevTools just couldn't handle it and broke off the WS connection.

I've created a minimal reproducible code sample here https://github.com/martingeorgiu/repainting_poc. But it only showcases this strange behaviour of `SizeTransition` that if the children are animated one (like is `CircularProgressIndicator`) it will still trigger the repaints 60 times per second. However, I couldn't create such a minimal reproducible code sample that would showcase the disconnecting, which was the original goal of this issue (even though in my complex app after commenting out `CircularProgressIndicator`, I can use Dart DevTools with no issues once again).

With that in mind, I would like to change this issue from "trying to figure out why the app disconnects" to "why Flutter animates hidden widgets" as that is an issue in and of itself.

**Comment by huycozy** [comment]
@martingeorgiu I ran your sample code but can not reproduce this issue. 
It looks like the issue doesn't always happen on your side. You may need to specify `Steps to reproduce` in advance so that we may verify it. 
Also, please try again on the latest stable `3.3.3` or master `3.4.0` channel to see if the issue still occurs.

**Comment by martingeorgiu** [comment]
Hmm, that's interesting. When I run the repo I've provided on the latest stable version `3.3.4` in profile mode and open the Performance tab in Dart DevTools, there are new frames keep being created (it seems that 60 times per second). You're sure that you cannot reproduce it? I can send you a screen recording if you would have some difficulties reproducing the issue, but it is quite straightforward.

**Comment by huycozy** [comment]
>there are new frames keep being created (it seems that 60 times per second)

@martingeorgiu I can see the same thing from my side, but it's not accidentally disconnected (only this is different with your case). Please try to create a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that shows the disconnecting behavior. Thank a lot!

**Comment by martingeorgiu** [comment]
Hi @huycozy,

sorry for replying a bit late, but there is a small misunderstanding. I've already written that I wasn't able to create the minimum reproducible code example for the _disconnecting_, but I was able to create a minimum reproducible code example for the _repainting_.

> However, I couldn't create such a minimal reproducible code sample that would showcase the disconnecting, which was the original goal of this issue (even though in my complex app after commenting out CircularProgressIndicator, I can use Dart DevTools with no issues once again).
> 
> With that in mind, I would like to change this issue from "trying to figure out why the app disconnects" to "why Flutter animates hidden widgets" as that is an issue in and of itself.

So if it is possible, I would like to change this issue from aiming at the disconnection to the repainting. (the fact that the repainting caused the disconnection in my wast app, I wouldn't bother with as for now)

**Comment by huycozy** [comment]
Hi @martingeorgiu 
I think it will be better if you can file a new issue for that case for others can understand the issue. And when opening a new issue, please try to provide all or some of the information indicated in the template so that we can address this issue properly. Thank you!

**Comment by martingeorgiu** [comment]
Sure thing:)
