### ISSUE TITLE
Update API documentation guidelines

### ISSUE THREAD

**Issue by InMatrix** [flutter/flutter#11275]
Based on user study findings, sample code and images in API docs help developers learn how to use the API and decide whether the API is relevant to their task. We'd like to encourage such practice by updating the style guide accordingly.

Specifically, I'd like to request adding the following content to the [Documentation comments (dartdocs)](https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#documentation-comments-dartdocs) section:

### Provide sample code
Sample code helps developers learn your API quickly. Writing sample code also helps you think through how your API is going to be used by app developers. 

For example, below is the sample code for building an infinite list of children with the ListView widget:

```dart
new ListView.builder(
  padding: new EdgeInsets.all(8.0),
  itemExtent: 20.0,
  itemBuilder: (BuildContext context, int index) {
    return new Text('entry $index');
  },
) 
```

### Provide illustrations, diagrams or screenshots

For any widget that draws pixels on the screen, showing how it looks like in its API doc helps developers decide if the widget is useful and learn how to customize it. 

Example:

* A diagram for the AppBar widget
![image](https://flutter.github.io/assets-for-api-docs/material/app_bar.png)

* A screenshot for the Card widget
![image](https://user-images.githubusercontent.com/348942/28338544-2c3681b8-6bbe-11e7-967d-fcd7c830bf53.png)

**Comment by Hixie** [comment]
You should definitely feel free to add this to the style guide directly.

One thing I would add for the illustrations is that we should require that all illustrations be easily reproducible, e.g. by running a Flutter app. That's actually how the current examples are made.

**Comment by InMatrix** [comment]
Will do.

Does the reproducibility requirement apply to the annotated diagram like the one for AppBar? I guess it was hand-crafted?

**Comment by Hixie** [comment]
Yes, especially to diagrams like the AppBar. It's generated by code:
https://github.com/flutter/assets-for-api-docs/blob/master/material/app_bar.dart

**Comment by InMatrix** [comment]
Done! Closed by https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#provide-sample-code
