### ISSUE TITLE
Add warning that `RenderRepaintBoundary.toImage` and `OffsetLayer.toImage` is slow

### ISSUE THREAD

**Issue by fzyzcjy** [flutter/flutter#112759]
Please see https://github.com/flutter/flutter/pull/112757 for details

## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by goderbauer** [comment]
(Triage): This issue doesn't really have much content and the PR stands on its own. I am going to close this one.

**Comment by fzyzcjy** [comment]
> Doc fixes don't need to have an issue associated with it

I see :) Next time I will not file an issue. I filed it simply because it is required in the PR template
