### ISSUE TITLE
Steam Deck support

### ISSUE THREAD

**Issue by svprdga** [flutter/flutter#112750]
## Use case

I would like to be able to compile applications for the linux target and have them work correctly on Steam Deck.

Currently when compiling an application for linux (tested with Flutter 3.0.5 and 3.3.3) the resulting bundle has a dependency on glibc v2.34. The current Steam OS software (3.3.1) ships with glibc v2.33, so when trying to run a binary generated by Flutter it fails indicating that it needs the new version of the library.

## Proposal

It would be nice to have some way to be able to compile for Steam Deck. Maybe telling Flutter to use glibc 2.33 or similar (I don't know if this is technically possible).

**Comment by stuartmorgan** [comment]
The current first-party Linux target is intended for desktop support, and has minimum requirements that are designed for that environment. For other Linux-based targets that aren't desktop environments, there are other third-party Linux embeddings that may be more suitable.

**Comment by svprdga** [comment]
> The current first-party Linux target is intended for desktop support, and has minimum requirements that are designed for that environment. For other Linux-based targets that aren't desktop environments, there are other third-party Linux embeddings that may be more suitable.

Could you please enumerate any of these other third-party embeddings that I could use for that purpose?

By the way, I don't know why you don't consider the Steam Deck as a desktop environment, when switching it to desktop mode it behaves pretty much as any other Linux distribution.
