### ISSUE TITLE
Dart -> Engine rolls failing on crasher in ffi unit test

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#112726]
On the first roll that contains the revert for https://github.com/flutter/flutter/issues/112687, here: https://github.com/flutter/engine/pull/36539, some ffi unit tests are failing:

https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20Unopt/19261/overview

https://dart.googlesource.com/sdk.git/+/d9c442bce8d13bb4db977e738d795b753ce84168 is in the roll and mentions ffi, but I don't actually know that it's related: @dcharkes 

cc @a-siva

**Comment by jason-simmons** [comment]
Confirmed that the segfaults in `tonic_unittests`/`FfiNativeTest.FfiBindingCallClassMemberMethod` and in `plugin_utilities_test.dart` started with https://dart.googlesource.com/sdk.git/+/d9c442bce8d13bb4db977e738d795b753ce84168

**Comment by dcharkes** [comment]
Thanks for triaging @jason-simmons!

Thanks for the revert @zanderso.

Our tonic tests covered a case we didn't cover in the Dart SDK: Returning a Smi in a Dart_Handle through dart FFI.

https://github.com/flutter/engine/blob/13326ff842c881a125899edef481c09e69fb8d9a/third_party/tonic/tests/ffi_native_unittest.cc#L36

We didn't account for that in the reverted CL, causing us to try to use the Smi as a memory address for finding the class id (to check if that class id was an error cid). Dereferencing a Smi leads to segfaults. 🙃 

The problem has been rectified and the reland is up for review https://dart-review.googlesource.com/c/sdk/+/262342.

**Comment by chinmaygarde** [comment]
This was reverted.

**Comment by dcharkes** [comment]
(The change (with fix) has relanded in the Dart SDK.)
