### ISSUE TITLE
Cannot scroll in DataTable documentation example

### ISSUE THREAD

**Issue by jibbers42** [flutter/flutter#112755]
The example has 10 rows, but you can't scroll to the rows out of view. Scrolling isn't the point of the example, but there are rows out of view and showing scrolling would be helpful for less experienced users.

https://api.flutter.dev/flutter/material/DataTable-class.html#material.DataTable.2

**Comment by ferndot** [comment]
I have a proposed fix for this over in https://github.com/flutter/flutter/pull/113194

**Comment by mr-rsr** [comment]
Can i fix this issue

**Comment by Chinmay-KB** [comment]
I would like to work on this. I understand this PR just requires some tests or is there something more to do as well?

**Comment by Chinmay-KB** [comment]
So it's just a test which does drag + checks if the item below are visible? Or something more too?

**Comment by TahaTesser** [comment]
> So it's just a test which does drag + checks if the item below are visible? Or something more too?

Yes, just scroll to update the visible items. We'll also need to document the performance implications of SinglleChildScrollView with DataTable. If you're not sure, I can find another issue for you.

**Comment by TahaTesser** [comment]
> Any place you would suggest me to figure out the performance implications? I'd like to dig through it instead of an easier bug @TahaTesser


Look at the "Performance considerations" section https://master-api.flutter.dev/flutter/material/ListTile-class.html. 
We just need a similar description for using `SingleChildScrollView` on a `DataTable` with a large number of rows. No extra code example is needed. 

cc: @Piinks

**Comment by Chinmay-KB** [comment]
I am working on the test. One issue I faced is that because the list is too small, all the items are already visible on the screen.So the initial assertion of first item being visible and last not being visible cannot be made. I can either
- Increase the list count (Works with list size 20)
- Set a surface size for the test to run
What should be the approach here?

I am proceeding with increasing the list count for now, will change if necessary

**Comment by Anianonymous** [comment]
Hey, 
I am interested to solve this. Can you please assign me this task?

**Comment by TahaTesser** [comment]
@Anianonymous 

Please see the linked PR [above ](https://github.com/flutter/flutter/issues/112755#ref-pullrequest-1827565702), this is being fixed.

You can search for similar issues in the Flutter repository.

**Comment by Anianonymous** [comment]
> The example has 10 rows, but you can't scroll to the rows out of view. Scrolling isn't the point of the example, but there are rows out of view and showing scrolling would be helpful for less experienced users.
> 
> https://api.flutter.dev/flutter/material/DataTable-class.html#material.DataTable.2

https://api.flutter.dev/flutter/material/DataTable-class.html#material.DataTable.2
I initialised value as numsItems as 100 I can scroll down easily and I wraaped the SizedBox with SingleChildScrollView.
I hope solved your issue @jibbers42
