### ISSUE TITLE
When start typing after `@override`, I want all override-able functions to appear as suggestions.

### ISSUE THREAD

**Issue by RoarGronmo** [flutter/flutter#112763]
## Use case

In my IDE (in this case Android Studio Dolphin)
```
Android Studio Dolphin | 2021.3.1
Build #AI-213.7172.25.2113.9014738, built on August 31, 2022
Runtime version: 11.0.13+0-b1751.21-8125866 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 8
Registry:
    external.system.auto.import.disabled=true
    ide.text.editor.with.preview.show.floating.toolbar=false

Non-Bundled Plugins:
    org.jetbrains.kotlin (213-1.7.20-RC-release-187-AS6777.52)
    Dart (213.7433)
    io.flutter (70.2.3)

```
I want the IDE to bring up suggestions of override able functions when having started typing function type (i.e. `void`) after the `@override` line. This would have made it very easy to explore "unknown" functions in the libraries as well.

## Proposal

Please bring up suggestions as you do in other circumstances, 

![image](https://user-images.githubusercontent.com/11217296/193446089-1b270be9-c35e-4b0a-93c7-633a4b74a153.png)

![image](https://user-images.githubusercontent.com/11217296/193446115-d762b9e0-907f-460d-af82-a54b50121fd5.png)

**Comment by darshankawar** [comment]
@RoarGronmo Thanks for the report, but I think you will need to report this in either flutter's intellij plugin repo or in dart lang repo.
Please see similar issue for your reference:

https://github.com/flutter/flutter-intellij/issues/1110

Closing from here. If you disagree, write in comments and I'll reopen it.

**Comment by RoarGronmo** [comment]
Thanx for reminding, on the other hand, that issue you mentioned was rather old (2017). They may have forgot...

I'll try to make another "call" to them !

Keep on !
