### ISSUE TITLE
[local_auth] localAuthentication.authenticate  only checks for biometric even if we set biometricOnly:false

### ISSUE THREAD

**Issue by rddewan** [flutter/flutter#112796]
I removed all the finger and only set PIN but it gets a exception with `NotAvailable`, It only check for the biometric , PIN is ignored? 

```
Future<bool> authenticate() async {
    bool didAuthenticate = false;

    try {
        
        didAuthenticate = await _localAuthentication.authenticate(
          localizedReason: 'Authenticate To Continue',
          options: const AuthenticationOptions(
            useErrorDialogs: false,
            stickyAuth: true, 
            biometricOnly: false,          
          ),
        );
        
      } on PlatformException catch (e) {
        
        switch (e.code) {
          case  auth_error.notAvailable:
            
            break;
          case  auth_error.lockedOut:
            
            break;
          case  auth_error.notEnrolled:
            
            break;
          case  auth_error.passcodeNotSet:
            
            break;
          default:
        } 
      }

    return didAuthenticate;      
   
  }
```

If we set `useErrorDialogs: true` it always  shows  Biometric required dialog
```
didAuthenticate = await _localAuthentication.authenticate(
          localizedReason: 'Authenticate To Continue',
          options: const AuthenticationOptions(
            useErrorDialogs: true,
            stickyAuth: true, 
            biometricOnly: false,          
          ),
```

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.2, on macOS 12.6 21G115 darwin-arm, locale en-TH)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.71.2)
[✓] Connected device (5 available)
[✓] HTTP Host Availability

**Comment by exaby73** [comment]
Hello @rddewan. Thank you for filing this issue. Can you please provide the following information?

- A [complete and minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).
- The output of `flutter doctor -v`
- The output of `flutter run-v`

Please provide the information in the form of text. See how to make collapsible sections with Markdown [here](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-collapsed-sections).

**Comment by rddewan** [comment]
I guess it's my device problem , I tested it on AVD it works with Pin and Fingerprint
