### ISSUE TITLE
ICU Message Refactoring

### ISSUE THREAD

**Issue by thkim1011** [flutter/flutter#112709]
See #112390 for more context. Essentially, we need to refactor the `Message` class in `gen_l10n_types.dart` if we want to support proper placeholder type inference. The high level idea is that we need to
1. Parse each translation for a given message.
2. Figure out how each placeholder is being used.
3. If there is a conflict (i.e. placeholder is used for both plural (which must be type 'num') and select (which must be type 'String'), then throw an error.
4. Otherwise if type is not explicitly defined, then set it to 'num' if only used in plurals and placeholders or set it to 'String' if only used in selects and placeholders.

To do step 1, we need the `Message` class to own all of the translations for the message. We should be able to do this by changing `LocalizationsGenerator.loadResources`. Then we can also deprecate the old behavior for inferring placeholder types which doesn't work properly.

**Comment by christopherfujino** [comment]
Drive by comment (haven't given it much thought), have you considered a parser migration where the new parser is introduced alongside the legacy one, controlled by some boolean value? This way if there is a serious bug in it in a stable release, we can easily revert back to the legacy version.
