### ISSUE TITLE
[CP] Suppress invalid DWDS errors in Flutter tool

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#112886]
### issue_link

https://github.com/flutter/flutter/issues/111136 and https://github.com/flutter/flutter/issues/109792 (duplicates)

### Commit Hash

[3b6e3a693](https://github.com/flutter/flutter/commit/3b6e3a693836cf0675355eb009a0455d1e237e1c)

### Target

stable

### pr_link

https://github.com/flutter/flutter/pull/112887

### Impacted Users

Flutter for web developers

### Impact Description

When launching the flutter for web app, repeated log messages of `Locations: No module for http://localhost:5555/dart_sdk.js` in the browser console.

### Workaround

Ignore the log messages. The application still works, however legitimate debug logs may be obscured.

### Risk

low

### Test Coverage

yes

### Validation Steps

1. Debug example/hello_world in VSCode on Chrome
1. set a breakpoint at runApp and start debugging
1. there should be no warnings in the debug console window when the breakpoint is hit

**Comment by christopherfujino** [comment]
@itsjustkevin & @zanderso WDYT about this? It's an annoyance, but a very low-risk fix.

**Comment by zanderso** [comment]
CP lgtm in a vacuum, but if this is the only fix, I don't think we should cut a release just for it. Are there other CPs lined up?

**Comment by christopherfujino** [comment]
Xilai just merged cherrypicks to the framework RC branch 2 hours ago, so i suspect there are no others lined up.
