### ISSUE TITLE
Flutter SDK should cache version to disk

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#112833]
Currently the Flutter CLI tool determines a release's version based on git tags. This is not ideal because tags are not immutable, not all fetch workflows also fetch tags, and it has added a lot of complexity to the tool in terms of needing to invoke git sub-commands, which in addition slow down the tool (https://github.com/flutter/flutter/pull/111392).

Instead, releases should check in the version and channel data into a JSON file, and the tool should just read this in at runtime.
 
Related to https://github.com/flutter/flutter/issues/91318 and https://github.com/flutter/flutter/issues/63106.

**Comment by jensjoha** [comment]
In the rejection of https://github.com/flutter/flutter/pull/111392 it was stated that this would be prioritized for Q4 --- so what's the status of this?

**Comment by eliasyishak** [comment]
Following here as this can help simplify getting flutter version and channel info for analytics

**Comment by christopherfujino** [comment]
Investigate everything that depends on the top level Flutter SDK `version` file, and if we can change the format to include more fields.

**Comment by eliasyishak** [comment]
> Investigate everything that depends on the top level Flutter SDK `version` file, and if we can change the format to include more fields.

Could we instead create another file for tracking version and channel, ie. `version.json`? That'll ensure we don't break anything that depends on that file?

**Comment by christopherfujino** [comment]
> > Investigate everything that depends on the top level Flutter SDK `version` file, and if we can change the format to include more fields.
> 
> Could we instead create another file for tracking version and channel, ie. `version.json`? That'll ensure we don't break anything that depends on that file?

Good idea :) https://github.com/flutter/flutter/pull/124558
