### ISSUE TITLE
Make dartpad embed or contents on api.flutter.dev resizeable

### ISSUE THREAD

**Issue by davidhicks980** [flutter/flutter#112839]
## Use case
Make it easier to explore more complicated embedded code samples. 

## Proposal

Any of the following:
* Make dartpad on the api docs larger vertically and/or horizontally
* Give the option to resize the outer limits of embedded dartpad
* Make text resizable.
* Allow users to hide the right or left side bar

### Before
![image](https://user-images.githubusercontent.com/59215665/193719234-01657328-7c15-4dc4-b70f-9279c57e92a8.png)

### After
![image](https://user-images.githubusercontent.com/59215665/193719199-1f7eeb8c-636f-42fd-8849-e6d2f32a2f28.png)

**Comment by darshankawar** [comment]
@davidhicks980 
I think you will need to report this in dart pad's dedicated repo: https://github.com/dart-lang/dart-pad/issues
Closing from here. If you disagree, write in comments and I'll reopen it.
