### ISSUE TITLE
iOS Deploy instructions missing instruction to set a unique Bundle Name

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#11287]
In reference to https://flutter.io/ios-release/

We don't seem to talk about setting a Bundle Name. I have to go into here:

<img width="879" alt="runner_xcodeproj" src="https://user-images.githubusercontent.com/5479/28345985-bd8deb96-6be2-11e7-833d-7aa7f5dc148d.png">

to set a unique Bundle Name.

Maybe we can document that step? Should help the next person :)

**Comment by mit-mit** [comment]
Isn't that the same setting as this one, which we already mention?

"`Display Name:` the name of the app to be displayed on the home screen and elsewhere."

**Comment by sethladd** [comment]
It appears that Display Name and Bundle Name are different. I changed Display Name, but the App Store was still complaining. Only until I changed Bundle Name did I get the App Store to stop complaining.

**Comment by sethladd** [comment]
Here's the Display Name setting. This is distinct from Bundle Name:
<img width="672" alt="screen shot 2017-07-19 at 9 46 29 am" src="https://user-images.githubusercontent.com/5479/28379046-34ba9c9e-6c67-11e7-9326-d96353cf178a.png">

**Comment by mit-mit** [comment]
OK, I just noticed that if you change the Display Name property, then the Bundle name is also updated?

**Comment by mit-mit** [comment]
cc @cbracken

**Comment by cbracken** [comment]
It looks like the required steps are on the [iOS releasing guide](https://flutter.io/ios-release/) to me.

One of the first steps is "Register a Bundle ID", which describes how to register a new Bundle ID.

Later, in the "Review Xcode project settings" section, under the "In the Identity section" subsection, you're asked to verify the Bundle Identifier.

**Comment by cbracken** [comment]
Closing since, as noted above, I believe all required steps are present in the releasing guide under the *Review Xcode project settings* section. Please re-open if that's not the case, or if you can think of better wording.
