### ISSUE TITLE
Update scroll paging logic in Scrollbar

### ISSUE THREAD

**Issue by Piinks** [flutter/flutter#112893]
https://github.com/flutter/flutter/pull/105497 exposes the default computation of the page scroll increment of a ScrollAction.
This logic was duped in RawScrollbar to page the Scrollable when clicking the track. 

When https://github.com/flutter/flutter/pull/105497 lands, we should use the newly exposed methods in RawScrollbar and remove the duplicated code. 👍

**Comment by tomohiko-tanihata** [comment]
@Piinks I added a fix for this in https://github.com/flutter/flutter/pull/121481.

**Comment by Piinks** [comment]
Hey @tomohiko-tanihata thank you! I will take a look!
