### ISSUE TITLE
[camera] Camera starts lagging on android after startImageStream & stopImageStream (A resource failed to call release.)

### ISSUE THREAD

**Issue by RobertApikyan** [flutter/flutter#112856]
## Details

On Android, camera preview starts lagging after starting and stopping image stream a few times, and the "await cameraController.stopImageStream()" never completes, and I see this message in the logs "W/System  ( 1327): A resource failed to call release. ". 

## Here is the video 
I'm experiencing this even on camera app example. 
Iv'e added a button that starts/stops the image stream. After few tries to start and stop the image stream, the preview starts lagging. 

https://user-images.githubusercontent.com/17802092/193770604-0b078425-f82a-480e-a9aa-65fff3126164.mp4

## Here is the code to reproduce

1. Replace this code in the camera sample in the main.dart class (camera 0.10.0+3).  
    https://gist.github.com/RobertApikyan/f9bc5a212272d955ff8a069de10d7fd4
3. Run the app on Android device. 
4. Toggle the start/stop stream button a few times.
5. Finally, left the stream enabled, and you will see the lagging screen similar to video

## Platform
**Target Platform: Android**
**Target OS version/browser: Android 11**
**Devices: Galaxy A70**

## Logs

<details>
<summary>Logs</summary>

Performing hot restart...
Syncing files to device SM A705FN...
Restarted application in 2,742ms.
I/ViewRootImpl@657baa0[FlutterActivity]( 5336): ViewPostIme pointer 0
I/ViewRootImpl@657baa0[FlutterActivity]( 5336): ViewPostIme pointer 1
I/Camera  ( 5336): close
I/CameraManagerGlobal( 5336): Camera 0 facing CAMERA_FACING_BACK state now CAMERA_STATE_IDLE for client io.flutter.plugins.cameraexample API Level 2
I/CameraManagerGlobal( 5336): Camera 0 facing CAMERA_FACING_BACK state now CAMERA_STATE_CLOSED for client io.flutter.plugins.cameraexample API Level 2
W/s.cameraexampl( 5336): Long monitor contention with owner main (5336) at void android.hardware.camera2.impl.CameraDeviceImpl.close()(CameraDeviceImpl.java:1334) waiters=0 in void android.hardware.camera2.impl.CameraDeviceImpl$CameraDeviceCallbacks.onCaptureStarted(android.hardware.camera2.impl.CaptureResultExtras, long) for 317ms
I/Camera  ( 5336): open | onClosed
W/Camera  ( 5336): The selected imageFormatGroup is not supported by Android. Defaulting to yuv420
I/CameraManagerGlobal( 5336): Camera 0 facing CAMERA_FACING_BACK state now CAMERA_STATE_OPEN for client io.flutter.plugins.cameraexample API Level 2
I/Camera  ( 5336): startPreview
I/Camera  ( 5336): CameraCaptureSession onConfigured
I/Camera  ( 5336): Updating builder settings
D/Camera  ( 5336): Updating builder with feature: ExposureLockFeature
D/Camera  ( 5336): Updating builder with feature: ExposurePointFeature
D/Camera  ( 5336): Updating builder with feature: ZoomLevelFeature
D/Camera  ( 5336): Updating builder with feature: AutoFocusFeature
D/Camera  ( 5336): Updating builder with feature: NoiseReductionFeature
I/Camera  ( 5336): updateNoiseReduction | currentSetting: fast
D/Camera  ( 5336): Updating builder with feature: FocusPointFeature
D/Camera  ( 5336): Updating builder with feature: ResolutionFeature
D/Camera  ( 5336): Updating builder with feature: SensorOrientationFeature
D/Camera  ( 5336): Updating builder with feature: FlashFeature
D/Camera  ( 5336): Updating builder with feature: ExposureOffsetFeature
D/Camera  ( 5336): Updating builder with feature: FpsRangeFeature
I/Camera  ( 5336): refreshPreviewCaptureSession
I/CameraManagerGlobal( 5336): Camera 0 facing CAMERA_FACING_BACK state now CAMERA_STATE_ACTIVE for client io.flutter.plugins.cameraexample API Level 2
I/ViewRootImpl@657baa0[FlutterActivity]( 5336): ViewPostIme pointer 0
I/ViewRootImpl@657baa0[FlutterActivity]( 5336): ViewPostIme pointer 1
I/CameraManagerGlobal( 5336): Camera 0 facing CAMERA_FACING_BACK state now CAMERA_STATE_IDLE for client io.flutter.plugins.cameraexample API Level 2
I/Camera  ( 5336): startPreviewWithImageStream
W/s.cameraexampl( 5336): Long monitor contention with owner main (5336) at void android.hardware.camera2.impl.CameraDeviceImpl.waitUntilIdle()(CameraDeviceImpl.java:1283) waiters=0 in void android.hardware.camera2.impl.CameraDeviceImpl$4.run() for 314ms
I/Camera  ( 5336): CameraCaptureSession onConfigured
I/Camera  ( 5336): Updating builder settings
D/Camera  ( 5336): Updating builder with feature: ExposureLockFeature
D/Camera  ( 5336): Updating builder with feature: ExposurePointFeature
D/Camera  ( 5336): Updating builder with feature: ZoomLevelFeature
D/Camera  ( 5336): Updating builder with feature: AutoFocusFeature
D/Camera  ( 5336): Updating builder with feature: NoiseReductionFeature
I/Camera  ( 5336): updateNoiseReduction | currentSetting: fast
D/Camera  ( 5336): Updating builder with feature: FocusPointFeature
D/Camera  ( 5336): Updating builder with feature: ResolutionFeature
D/Camera  ( 5336): Updating builder with feature: SensorOrientationFeature
D/Camera  ( 5336): Updating builder with feature: FlashFeature
D/Camera  ( 5336): Updating builder with feature: ExposureOffsetFeature
D/Camera  ( 5336): Updating builder with feature: FpsRangeFeature
I/Camera  ( 5336): refreshPreviewCaptureSession
I/Camera  ( 5336): CameraCaptureSession onClosed
I/CameraManagerGlobal( 5336): Camera 0 facing CAMERA_FACING_BACK state now CAMERA_STATE_ACTIVE for client io.flutter.plugins.cameraexample API Level 2
W/System  ( 5336): A resource failed to call release. 
I/Camera  ( 5336): CameraCaptureSession onClosed
W/System  ( 5336): A resource failed to call release. 
I/ViewRootImpl@657baa0[FlutterActivity]( 5336): ViewPostIme pointer 0
I/ViewRootImpl@657baa0[FlutterActivity]( 5336): ViewPostIme pointer 1
I/Camera  ( 5336): startPreview
I/CameraManagerGlobal( 5336): Camera 0 facing CAMERA_FACING_BACK state now CAMERA_STATE_IDLE for client io.flutter.plugins.cameraexample API Level 2
I/Camera  ( 5336): CameraCaptureSession onConfigured
I/Camera  ( 5336): Updating builder settings
W/s.cameraexampl( 5336): Long monitor contention with owner main (5336) at void android.hardware.camera2.impl.CameraDeviceImpl.waitUntilIdle()(CameraDeviceImpl.java:1283) waiters=1 in void android.hardware.camera2.impl.CameraDeviceImpl$4.run() for 337ms
D/Camera  ( 5336): Updating builder with feature: ExposureLockFeature
D/Camera  ( 5336): Updating builder with feature: ExposurePointFeature
D/Camera  ( 5336): Updating builder with feature: ZoomLevelFeature
D/Camera  ( 5336): Updating builder with feature: AutoFocusFeature
D/Camera  ( 5336): Updating builder with feature: NoiseReductionFeature
I/Camera  ( 5336): updateNoiseReduction | currentSetting: fast
D/Camera  ( 5336): Updating builder with feature: FocusPointFeature
D/Camera  ( 5336): Updating builder with feature: ResolutionFeature
D/Camera  ( 5336): Updating builder with feature: SensorOrientationFeature
D/Camera  ( 5336): Updating builder with feature: FlashFeature
D/Camera  ( 5336): Updating builder with feature: ExposureOffsetFeature
D/Camera  ( 5336): Updating builder with feature: FpsRangeFeature
I/Camera  ( 5336): refreshPreviewCaptureSession
I/Camera  ( 5336): CameraCaptureSession onClosed
W/System  ( 5336): A resource failed to call release. 
I/CameraManagerGlobal( 5336): Camera 0 facing CAMERA_FACING_BACK state now CAMERA_STATE_ACTIVE for client io.flutter.plugins.cameraexample API Level 2
I/ViewRootImpl@657baa0[FlutterActivity]( 5336): ViewPostIme pointer 0
I/ViewRootImpl@657baa0[FlutterActivity]( 5336): ViewPostIme pointer 1
I/CameraManagerGlobal( 5336): Camera 0 facing CAMERA_FACING_BACK state now CAMERA_STATE_IDLE for client io.flutter.plugins.cameraexample API Level 2
I/Camera  ( 5336): startPreviewWithImageStream
W/s.cameraexampl( 5336): Long monitor contention with owner main (5336) at void android.hardware.camera2.impl.CameraDeviceImpl.waitUntilIdle()(CameraDeviceImpl.java:1283) waiters=0 in void android.hardware.camera2.impl.CameraDeviceImpl$4.run() for 337ms
W/s.cameraexampl( 5336): Long monitor contention with owner main (5336) at void android.hardware.camera2.impl.CameraDeviceImpl.waitUntilIdle()(CameraDeviceImpl.java:1283) waiters=1 in void android.hardware.camera2.impl.CameraDeviceImpl$CameraDeviceCallbacks.onResultReceived(android.hardware.camera2.impl.CameraMetadataNative, android.hardware.camera2.impl.CaptureResultExtras, android.hardware.camera2.impl.PhysicalCaptureResultInfo[]) for 328ms
I/Camera  ( 5336): CameraCaptureSession onConfigured
I/Camera  ( 5336): Updating builder settings
D/Camera  ( 5336): Updating builder with feature: ExposureLockFeature
D/Camera  ( 5336): Updating builder with feature: ExposurePointFeature
D/Camera  ( 5336): Updating builder with feature: ZoomLevelFeature
D/Camera  ( 5336): Updating builder with feature: AutoFocusFeature
D/Camera  ( 5336): Updating builder with feature: NoiseReductionFeature
I/Camera  ( 5336): updateNoiseReduction | currentSetting: fast
D/Camera  ( 5336): Updating builder with feature: FocusPointFeature
D/Camera  ( 5336): Updating builder with feature: ResolutionFeature
D/Camera  ( 5336): Updating builder with feature: SensorOrientationFeature
D/Camera  ( 5336): Updating builder with feature: FlashFeature
D/Camera  ( 5336): Updating builder with feature: ExposureOffsetFeature
D/Camera  ( 5336): Updating builder with feature: FpsRangeFeature
I/Camera  ( 5336): refreshPreviewCaptureSession
I/Camera  ( 5336): CameraCaptureSession onClosed
I/CameraManagerGlobal( 5336): Camera 0 facing CAMERA_FACING_BACK state now CAMERA_STATE_ACTIVE for client io.flutter.plugins.cameraexample API Level 2
W/System  ( 5336): A resource failed to call release. 
I/ViewRootImpl@657baa0[FlutterActivity]( 5336): ViewPostIme pointer 0
I/ViewRootImpl@657baa0[FlutterActivity]( 5336): ViewPostIme pointer 1
I/Camera  ( 5336): startPreview
I/CameraManagerGlobal( 5336): Camera 0 facing CAMERA_FACING_BACK state now CAMERA_STATE_IDLE for client io.flutter.plugins.cameraexample API Level 2
I/Camera  ( 5336): CameraCaptureSession onConfigured
I/Camera  ( 5336): Updating builder settings
D/Camera  ( 5336): Updating builder with feature: ExposureLockFeature
D/Camera  ( 5336): Updating builder with feature: ExposurePointFeature
D/Camera  ( 5336): Updating builder with feature: ZoomLevelFeature
D/Camera  ( 5336): Updating builder with feature: AutoFocusFeature
D/Camera  ( 5336): Updating builder with feature: NoiseReductionFeature
I/Camera  ( 5336): updateNoiseReduction | currentSetting: fast
D/Camera  ( 5336): Updating builder with feature: FocusPointFeature
D/Camera  ( 5336): Updating builder with feature: ResolutionFeature
D/Camera  ( 5336): Updating builder with feature: SensorOrientationFeature
D/Camera  ( 5336): Updating builder with feature: FlashFeature
D/Camera  ( 5336): Updating builder with feature: ExposureOffsetFeature
D/Camera  ( 5336): Updating builder with feature: FpsRangeFeature
I/Camera  ( 5336): refreshPreviewCaptureSession
W/s.cameraexampl( 5336): Long monitor contention with owner main (5336) at void android.hardware.camera2.impl.CameraDeviceImpl.waitUntilIdle()(CameraDeviceImpl.java:1283) waiters=0 in void android.hardware.camera2.impl.CameraDeviceImpl$CameraDeviceCallbacks.onCaptureStarted(android.hardware.camera2.impl.CaptureResultExtras, long) for 335ms
W/s.cameraexampl( 5336): Long monitor contention with owner main (5336) at void android.hardware.camera2.impl.CameraDeviceImpl.waitUntilIdle()(CameraDeviceImpl.java:1283) waiters=1 in void android.hardware.camera2.impl.CameraDeviceImpl$4.run() for 336ms
I/Camera  ( 5336): CameraCaptureSession onClosed
I/CameraManagerGlobal( 5336): Camera 0 facing CAMERA_FACING_BACK state now CAMERA_STATE_ACTIVE for client io.flutter.plugins.cameraexample API Level 2
I/ViewRootImpl@657baa0[FlutterActivity]( 5336): ViewPostIme pointer 0
I/ViewRootImpl@657baa0[FlutterActivity]( 5336): ViewPostIme pointer 1
I/CameraManagerGlobal( 5336): Camera 0 facing CAMERA_FACING_BACK state now CAMERA_STATE_IDLE for client io.flutter.plugins.cameraexample API Level 2
I/Camera  ( 5336): startPreviewWithImageStream
I/Camera  ( 5336): CameraCaptureSession onConfigured
I/Camera  ( 5336): Updating builder settings
W/s.cameraexampl( 5336): Long monitor contention with owner main (5336) at void android.hardware.camera2.impl.CameraDeviceImpl.waitUntilIdle()(CameraDeviceImpl.java:1283) waiters=0 in void android.hardware.camera2.impl.CameraDeviceImpl$CameraDeviceCallbacks.onCaptureStarted(android.hardware.camera2.impl.CaptureResultExtras, long) for 356ms
D/Camera  ( 5336): Updating builder with feature: ExposureLockFeature
D/Camera  ( 5336): Updating builder with feature: ExposurePointFeature
D/Camera  ( 5336): Updating builder with feature: ZoomLevelFeature
W/s.cameraexampl( 5336): Long monitor contention with owner main (5336) at void android.hardware.camera2.impl.CameraDeviceImpl.waitUntilIdle()(CameraDeviceImpl.java:1283) waiters=1 in void android.hardware.camera2.impl.CameraDeviceImpl$4.run() for 356ms
D/Camera  ( 5336): Updating builder with feature: AutoFocusFeature
D/Camera  ( 5336): Updating builder with feature: NoiseReductionFeature
I/Camera  ( 5336): updateNoiseReduction | currentSetting: fast
D/Camera  ( 5336): Updating builder with feature: FocusPointFeature
D/Camera  ( 5336): Updating builder with feature: ResolutionFeature
D/Camera  ( 5336): Updating builder with feature: SensorOrientationFeature
D/Camera  ( 5336): Updating builder with feature: FlashFeature
D/Camera  ( 5336): Updating builder with feature: ExposureOffsetFeature
D/Camera  ( 5336): Updating builder with feature: FpsRangeFeature
I/Camera  ( 5336): refreshPreviewCaptureSession
I/Camera  ( 5336): CameraCaptureSession onClosed
I/CameraManagerGlobal( 5336): Camera 0 facing CAMERA_FACING_BACK state now CAMERA_STATE_ACTIVE for client io.flutter.plugins.cameraexample API Level 2
W/System  ( 5336): A resource failed to call release. 
W/System  ( 5336): A resource failed to call release. 
I/ViewRootImpl@657baa0[FlutterActivity]( 5336): ViewPostIme pointer 0
I/ViewRootImpl@657baa0[FlutterActivity]( 5336): ViewPostIme pointer 1
I/Camera  ( 5336): startPreview
W/libc    ( 5336): Unable to set property "debug.sf.dequeuebuffer" to "1": connection failed; errno=13 (Permission denied)
E/BufferQueueProducer( 5336): [ImageReader-720x480f23m1-5336-11](id:14d800000011,api:4,p:1036,c:5336) waitForFreeSlotThenRelock: timeout
I/CameraManagerGlobal( 5336): Camera 0 facing CAMERA_FACING_BACK state now CAMERA_STATE_IDLE for client io.flutter.plugins.cameraexample API Level 2
W/s.cameraexampl( 5336): Long monitor contention with owner main (5336) at void android.hardware.camera2.impl.CameraDeviceImpl.waitUntilIdle()(CameraDeviceImpl.java:1283) waiters=0 in void android.hardware.camera2.impl.CameraDeviceImpl$4.run() for 1.300s
W/s.cameraexampl( 5336): Long monitor contention with owner main (5336) at void android.hardware.camera2.impl.CameraDeviceImpl.waitUntilIdle()(CameraDeviceImpl.java:1283) waiters=1 in void android.hardware.camera2.impl.CameraDeviceImpl$CameraDeviceCallbacks.onCaptureStarted(android.hardware.camera2.impl.CaptureResultExtras, long) for 1.231s
I/Camera  ( 5336): CameraCaptureSession onConfigured
I/Camera  ( 5336): Updating builder settings
D/Camera  ( 5336): Updating builder with feature: ExposureLockFeature
D/Camera  ( 5336): Updating builder with feature: ExposurePointFeature
D/Camera  ( 5336): Updating builder with feature: ZoomLevelFeature
D/Camera  ( 5336): Updating builder with feature: AutoFocusFeature
D/Camera  ( 5336): Updating builder with feature: NoiseReductionFeature
I/Camera  ( 5336): updateNoiseReduction | currentSetting: fast
D/Camera  ( 5336): Updating builder with feature: FocusPointFeature
D/Camera  ( 5336): Updating builder with feature: ResolutionFeature
D/Camera  ( 5336): Updating builder with feature: SensorOrientationFeature
D/Camera  ( 5336): Updating builder with feature: FlashFeature
D/Camera  ( 5336): Updating builder with feature: ExposureOffsetFeature
D/Camera  ( 5336): Updating builder with feature: FpsRangeFeature
I/Camera  ( 5336): refreshPreviewCaptureSession
I/Camera  ( 5336): CameraCaptureSession onClosed
W/System  ( 5336): A resource failed to call release. 
I/CameraManagerGlobal( 5336): Camera 0 facing CAMERA_FACING_BACK state now CAMERA_STATE_ACTIVE for client io.flutter.plugins.cameraexample API Level 2
I/ViewRootImpl@657baa0[FlutterActivity]( 5336): ViewPostIme pointer 0
I/ViewRootImpl@657baa0[FlutterActivity]( 5336): ViewPostIme pointer 1
I/CameraManagerGlobal( 5336): Camera 0 facing CAMERA_FACING_BACK state now CAMERA_STATE_IDLE for client io.flutter.plugins.cameraexample API Level 2
I/Camera  ( 5336): startPreviewWithImageStream
I/Camera  ( 5336): CameraCaptureSession onConfigured
I/Camera  ( 5336): Updating builder settings
W/s.cameraexampl( 5336): Long monitor contention with owner main (5336) at void android.hardware.camera2.impl.CameraDeviceImpl.waitUntilIdle()(CameraDeviceImpl.java:1283) waiters=0 in void android.hardware.camera2.impl.CameraDeviceImpl$4.run() for 348ms
D/Camera  ( 5336): Updating builder with feature: ExposureLockFeature
D/Camera  ( 5336): Updating builder with feature: ExposurePointFeature
W/s.cameraexampl( 5336): Long monitor contention with owner main (5336) at void android.hardware.camera2.impl.CameraDeviceImpl.waitUntilIdle()(CameraDeviceImpl.java:1283) waiters=1 in void android.hardware.camera2.impl.CameraDeviceImpl$CameraDeviceCallbacks.onResultReceived(android.hardware.camera2.impl.CameraMetadataNative, android.hardware.camera2.impl.CaptureResultExtras, android.hardware.camera2.impl.PhysicalCaptureResultInfo[]) for 340ms
D/Camera  ( 5336): Updating builder with feature: ZoomLevelFeature
D/Camera  ( 5336): Updating builder with feature: AutoFocusFeature
D/Camera  ( 5336): Updating builder with feature: NoiseReductionFeature
I/Camera  ( 5336): updateNoiseReduction | currentSetting: fast
I/Camera  ( 5336): CameraCaptureSession onClosed
D/Camera  ( 5336): Updating builder with feature: FocusPointFeature
D/Camera  ( 5336): Updating builder with feature: ResolutionFeature
D/Camera  ( 5336): Updating builder with feature: SensorOrientationFeature
D/Camera  ( 5336): Updating builder with feature: FlashFeature
D/Camera  ( 5336): Updating builder with feature: ExposureOffsetFeature
D/Camera  ( 5336): Updating builder with feature: FpsRangeFeature
I/Camera  ( 5336): refreshPreviewCaptureSession
I/CameraManagerGlobal( 5336): Camera 0 facing CAMERA_FACING_BACK state now CAMERA_STATE_ACTIVE for client io.flutter.plugins.cameraexample API Level 2
W/System  ( 5336): A resource failed to call release. 
I/ViewRootImpl@657baa0[FlutterActivity]( 5336): ViewPostIme pointer 0
I/ViewRootImpl@657baa0[FlutterActivity]( 5336): ViewPostIme pointer 1
I/Camera  ( 5336): startPreview
W/libc    ( 5336): Unable to set property "debug.sf.dequeuebuffer" to "1": connection failed; errno=13 (Permission denied)
E/BufferQueueProducer( 5336): [ImageReader-720x480f23m1-5336-11](id:14d800000011,api:4,p:1036,c:5336) waitForFreeSlotThenRelock: timeout
I/CameraManagerGlobal( 5336): Camera 0 facing CAMERA_FACING_BACK state now CAMERA_STATE_IDLE for client io.flutter.plugins.cameraexample API Level 2
I/Camera  ( 5336): CameraCaptureSession onConfigured
I/Choreographer( 5336): Skipped 76 frames!  The application may be doing too much work on its main thread.
I/Camera  ( 5336): Updating builder settings
W/s.cameraexampl( 5336): Long monitor contention with owner main (5336) at void android.hardware.camera2.impl.CameraDeviceImpl.waitUntilIdle()(CameraDeviceImpl.java:1283) waiters=0 in void android.hardware.camera2.impl.CameraDeviceImpl$4.run() for 1.288s
D/Camera  ( 5336): Updating builder with feature: ExposureLockFeature
D/Camera  ( 5336): Updating builder with feature: ExposurePointFeature
D/Camera  ( 5336): Updating builder with feature: ZoomLevelFeature
W/s.cameraexampl( 5336): Long monitor contention with owner main (5336) at void android.hardware.camera2.impl.CameraDeviceImpl.waitUntilIdle()(CameraDeviceImpl.java:1283) waiters=1 in void android.hardware.camera2.impl.CameraDeviceImpl$CameraDeviceCallbacks.onCaptureStarted(android.hardware.camera2.impl.CaptureResultExtras, long) for 1.222s
D/Camera  ( 5336): Updating builder with feature: AutoFocusFeature
D/Camera  ( 5336): Updating builder with feature: NoiseReductionFeature
I/Camera  ( 5336): CameraCaptureSession onClosed
I/Camera  ( 5336): updateNoiseReduction | currentSetting: fast
D/Camera  ( 5336): Updating builder with feature: FocusPointFeature
D/Camera  ( 5336): Updating builder with feature: ResolutionFeature
D/Camera  ( 5336): Updating builder with feature: SensorOrientationFeature
D/Camera  ( 5336): Updating builder with feature: FlashFeature
D/Camera  ( 5336): Updating builder with feature: ExposureOffsetFeature
D/Camera  ( 5336): Updating builder with feature: FpsRangeFeature
I/Camera  ( 5336): refreshPreviewCaptureSession
I/CameraManagerGlobal( 5336): Camera 0 facing CAMERA_FACING_BACK state now CAMERA_STATE_ACTIVE for client io.flutter.plugins.cameraexample API Level 2
W/System  ( 5336): A resource failed to call release. 

```
```

Roberts-MacBook-Pro:example robert$ fvm flutter doctor -v 
[✓] Flutter (Channel stable, 3.3.2, on macOS 12.5 21G72 darwin-x64, locale en-AM)
    • Flutter version 3.3.2 on channel stable at /Users/robert/desktop/projects/flutter_versions/3.3.2
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e3c29ec00c (3 weeks ago), 2022-09-14 08:46:55 -0500
    • Engine revision a4ff2c53d8
    • Dart version 2.18.1
    • DevTools version 2.15.0

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/robert/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F100
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2019.3.5)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin version 193.7547

[✓] Connected device (3 available)
    • SM A705FN (mobile) • R58MB1CZHER • android-arm64  • Android 11 (API 30)
    • macOS (desktop)    • macos       • darwin-x64     • macOS 12.5 21G72 darwin-x64
    • Chrome (web)       • chrome      • web-javascript • Google Chrome 105.0.5195.125

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```
```

</details>

**Comment by huycozy** [comment]
Hi @RobertApikyan 
I tested with my two devices and see that there is only lagging at the time start/stop the image stream. I didn't have the same behavior as your demo video (from 0:30-0:35). Are there any other logs in the console at that time?

- Pixel 3a, Android 12
- Samsung Galaxy Tab A7 Lite, Android 12 OneUI 4.1, SM-T225

May be related/similar based on the logs: #108941

**Comment by RobertApikyan** [comment]
I have it on Samsung galaxy A70 model, I will try to grab some more logs, but in general the main logs are there

**Comment by huycozy** [comment]
@RobertApikyan I think this issue is duplicated of #108941 when its OP has also reproduced it by `start and stop image stream`, please see: https://github.com/flutter/flutter/issues/108941#issuecomment-1205074639
