### ISSUE TITLE
Performance impact despite Navigator.push - is this normal?

### ISSUE THREAD

**Issue by cekrozl1** [flutter/flutter#112824]
## 2 seemingly opposite effects 

I have this app which has a bunch of lottie animations which are creating a lot of performance issues, which is what I would like to solve.
Here is a video of the behaviour I can't wrap my head around:

https://user-images.githubusercontent.com/86661185/193678459-65b25459-c172-4e70-b067-77b0800c562a.mov

Here is what's happening in this video:
1. From 0:00 to 00:03 - all of the lottie animations are displayed and centered on the screen. The device cannot keep up the 60 FPS with some 25ms/frame because of all the lottie animations. I'm fine with that
2. 0:03 to 00:07 - the lottie animations are then manually moved out of sight and the performances stabilise at 60 FPS
3. 00:07 to 00:11 - the navigation to other pages and the execution of activities stays roughly within the 60 FPS - a few janks here and there but nothing significant
4. 00:11 to 00:13 - the lottie animations are centered again and the performance drops again. So far, it's consistant
5. 00:13 to 00:21 - a new page is pushed and here happens something strange. The fact that the lottie animations are centered on the first page has now an impact on the other pages, despite the fact that the lottie animations are no longer visible. Unlike the step 2 where the animations are hidden manually by scrolling or sliding, **the lottie animations hidden with Navigator.push don not seem to improve performance**
6. 00:21 to end - showing the consistency of the behaviour once more by manually hiding the animations again and seeing the performances improve

**Expected results:** 
I would imagine that since the Navigator.push is hiding the lottie widgets there shouldn't be an impact the currently displayed pages - the ones pushed to the Navigator

**Actual results:** 
The lottie widgets have a Render impact when hidden with Navigator.push but not when manually hidden by sliding them out of the screen.

**Question** 
Is this the expected behaviour from the Flutter framework?
Shouldn't Flutter ignore the Render of widgets from the pages which are not currently displayed?
Is there something I can do with Flutter to stop rendering the lottie animations improve the performances after Navigator.push - besides push and replace because I need the previous page when I go back?

I wanted to check this first with the Flutter team before poking the Lottie guys.

Thank you !

<details>

```
❯ flutter doctor -v
[✓] Flutter (Channel stable, 3.3.0, on macOS 12.5 21G72 darwin-x64, locale en-BE)
    • Flutter version 3.3.0 on channel stable at /Users/cekrozl1/Desktop/OneSpan/MSS/FLUTTER/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffccd96b62 (5 weeks ago), 2022-08-29 17:28:57 -0700
    • Engine revision 5e9e0e0aa8
    • Dart version 2.18.0
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/cekrozl1/Library/Android/sdk
    • Platform android-33, build-tools 30.0.3
    • ANDROID_HOME = /Users/cekrozl1/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13E113
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.71.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (3 available)
    • SM G973F (mobile) • R58N42DX67H • android-arm64  • Android 12 (API 31)
    • macOS (desktop)   • macos       • darwin-x64     • macOS 12.5 21G72 darwin-x64
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 105.0.5195.125

[✓] HTTP Host Availability
    • All required HTTP hosts are available
```

</details>

**Comment by jonahwilliams** [comment]
What lottie package are you using?

**Comment by jonahwilliams** [comment]
Also, in general when routes are offstage the ticker is disabled so animations should not be running - and lottie_flutter uses a ticker to drive its animations so they should also stop: https://github.com/xvrh/lottie-flutter/blob/fc450a88f48d9cec57f1bb5b56a997bf37066bc3/lib/src/lottie.dart#L326

**Comment by cekrozl1** [comment]
Hi @jonahwilliams !

That was a fast answer. It is indeed the package you mentioned above. 

If I understand correctly

> when routes are offstage the ticker is disabled so animations should not be running

means that I should continue investigating because something else is wrong in my app.

I will verify if the [page transition package](https://pub.dev/packages/page_transition) isn't performing something unexpected when transitioning to other pages. I'll let you know EOD.

**Comment by cekrozl1** [comment]
Hi @jonahwilliams,

Here is another video which confirms what you said about offstage routes:

https://user-images.githubusercontent.com/86661185/193762512-070ec2e2-4ded-4411-83f2-9497b542298e.mov

While 10 of these files are hard to render, a single one is not an issue for Flutter and putting it on a different page is likely stopping the animations from the previous page since the performances improve.

**Comment by cekrozl1** [comment]
Hi @jonahwilliams,

I added [page_transition](https://pub.dev/packages/page_transition) to the mix and this happened:

https://user-images.githubusercontent.com/86661185/193764494-3278c68a-ad02-4a92-ae18-5c887bc03b27.mov

The part that changed is commented out here:
```dart
ElevatedButton(
        child: const Text('Open route'),
        onPressed: () {
          Navigator.push(context,
              PageTransition(child: SecondRoute(), type: PageTransitionType.bottomToTop)
              // MaterialPageRoute(builder: (context) => const ),
              );
        },
      ),
```

I guess I'll raise this issue to the [page_transition](https://pub.dev/packages/page_transition) team next. 
It seems like the culprit to me but what do you think?

**Comment by cekrozl1** [comment]
Using the MaterialPageRoute fixed the issue in the original app too !

**Comment by huycozy** [comment]
Hi @cekrozl1 
For the issue to be workable, it needs to be reproducible with a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code. 

From your last comment, it seems the issue can be solved by using MaterialPageRoute and the original issue may come from 3rd plugin/package you used. Is this issue safe to close from here?

**Comment by cekrozl1** [comment]
Hi @huycozy !

I just wanted to start with the basics which was the answer to the question "what happens to animations when a new page is pushed". @jonahwilliams answered and it shows on the videos, which allowed me to dig further.

-> Thanks for the support and shoutout to the Flutter team !
