### ISSUE TITLE
add trailing commas and indentation

### ISSUE THREAD

**Issue by jasimameen** [flutter/flutter#112806]
Add trailing commas and reindentation at
https://github.com/flutter/flutter/blob/d0007a5547c09d495b449c7a74e855687e0a824f/examples/hello_world/lib/arabic.dart#L7

**Comment by christopherfujino** [comment]
Thank you for contributing! However, this does not appear to be a valid issue with the Flutter SDK and thus I am closing it.

**Comment by christopherfujino** [comment]
Please note also that this repository has not opted in to Hacktoberfest, so you will not get any credit for any PRs merged.
