### ISSUE TITLE
setTrustedCertificatesBytes not working on IOS 

### ISSUE THREAD

**Issue by what2003** [flutter/flutter#112830]
I use self signed certification(and with client side verification) for ssl https purpose, works perfectly on Android and Postman, but not IOS!!!

setTrustedCertificatesBytes with rootCA.crt (pem, p12):
IOS  : ' HandshakeException: Handshake error in client (OS Error: CERTIFICATE_VERIFY_FAILED: application verification failure(handshake.cc:393))' 

setTrustedCertificatesBytes with rootCA.der:
IOS Android : ' BAD_PKCS12_DATA(pkcs8_x509.c:657), errno = 0' 

If I use setTrustedCertificates, can not load the assets file:  (OS Error: No such file or directory, errno = 2)

>  ByteData bytes = await rootBundle.load('assets/ca/client.p12');
    ByteData rootPem = await rootBundle.load('assets/ca/rootCA.p12');
 (_dio.httpClientAdapter as DefaultHttpClientAdapter).onHttpClientCreate =
        (client) {
      SecurityContext sc = SecurityContext(withTrustedRoots: false);
      sc.setTrustedCertificatesBytes(rootPem.buffer.asUint8List(),
          password: 'A#1kQ98!I2hwi12wB!ISC\$5');
      sc.useCertificateChainBytes(bytes.buffer.asUint8List(),
          password: 'A31q4fVWe\$@*bTCYT%^5!64*HBJ');
      sc.usePrivateKeyBytes(bytes.buffer.asUint8List(),
          password: 'A31q4fVWe\$@*bTCYT%^5!64*HBJ');
      HttpClient httpClient = HttpClient(context: sc);
      // httpClient.badCertificateCallback =
      //     (X509Certificate cert, String host, int port) => true;
      return httpClient;
    };

stuck here for couple days, please tell me this is a bug

**Comment by huycozy** [comment]
Hi @what2003, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this. Also, please provide the output of `flutter doctor -v` as well. Thank you!

May be related/similar: #87717

**Comment by what2003** [comment]
https://github.com/what2003/flutter_application_1
ssl files all in assets/ca, my server api is working fine, please check it out.

> ╰─$ flutter doctor -v      
Building flutter tool...
[✓] Flutter (Channel stable, 3.3.4-0.0.pre.1, on macOS 11.6 20G165 darwin-x64, locale zh-Hans-CN)
    • Flutter version 3.3.4-0.0.pre.1 on channel stable at /Users/jack/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 27d7ec9563 (11 minutes ago), 2022-10-04 10:59:06 -0500
    • Engine revision 5c984c26eb
    • Dart version 2.18.2
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/jack/Library/Android/sdk
    • Platform android-33, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13A233
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.71.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (3 available)
    • SM G975U (mobile)    • R58M304QW1Z                              • android-arm64  • Android 11 (API 30)
    • 吴杰的 iPhone7 (mobile) • eed6e3b2d815420621d441672707634130e89e16 • ios            • iOS 15.0.1 19A348
    • Chrome (web)         • chrome                                   • web-javascript • Google Chrome 104.0.5112.101

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Comment by huycozy** [comment]
Hi @what2003, thanks for providing the sample code. 

But from what I can see, you're using `dio` package for network requests. It's similar to someone using `http` package [here](https://github.com/flutter/flutter/issues/87717#issuecomment-893347166) that should be opened in `http` repository. If you still want to use `dio`, please open the issue in the dedicated [repository](https://github.com/flutterchina/dio).

For the issue to be workable, it needs to be reproducible with a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code. Please provide such a sample.
Thank you!

**Comment by what2003** [comment]
https://github.com/what2003/flutter_application_1
Sorry for 3rd party plugins, now it is pure flutter, and only one page, please check it out!
Thank you! @huycozy

**Comment by huycozy** [comment]
@what2003 thanks for updating the sample code. I also see there's an open issue addressing the case you described #50699. There is also someone who fixed the issue by various workaround. Please check that issue if it can help.

**Comment by what2003** [comment]
Thanks @huycozy , #50699 is a different problem, after many times test, clearly "setTrustedCertificatesBytes" is not performed on IOS, easy to reproduce.

**Comment by huycozy** [comment]
@what2003 I label this issue for further investigation/insight from the team due to this case using a self-signed certificate whilst #50699 uses GoDaddy.

This issue is reproducible on the latest `stable` and `master` channels with [sample code](https://github.com/what2003/flutter_application_1).

<details>
<summary>Completed exception logs</summary>

```dart
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: HandshakeException: Handshake error in client (OS Error: 
	CERTIFICATE_VERIFY_FAILED: application verification failure(handshake.cc:393))
#0      _SecureFilterImpl._handshake (dart:io-patch/secure_socket_patch.dart:99:46)
#1      _SecureFilterImpl.handshake (dart:io-patch/secure_socket_patch.dart:142:25)
#2      _RawSecureSocket._secureHandshake (dart:io/secure_socket.dart:911:54)
#3      _RawSecureSocket._secureHandshake (dart:io/secure_socket.dart:914:15)
<asynchronous suspension>
#4      _RawSecureSocket._tryFilter (dart:io/secure_socket.dart:1040:13)
<asynchronous suspension>
```
</details>

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.3.4, on macOS 12.6 21G115 darwin-x64, locale en-VN)
    • Flutter version 3.3.4 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision eb6d86ee27 (23 hours ago), 2022-10-04 22:31:45 -0700
    • Engine revision c08d7d5efc
    • Dart version 2.18.2
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode14.0.1.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2022.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 70.0.5
    • Dart plugin version 222.4167.21

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.71.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.6 21G115 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 105.0.5195.125

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

```bash
[✓] Flutter (Channel master, 3.5.0-3.0.pre.5, on macOS 12.6 21G115 darwin-x64, locale en-VN)
    • Flutter version 3.5.0-3.0.pre.5 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9ca314afd0 (12 minutes ago), 2022-10-06 23:06:11 -0400
    • Engine revision a4174f29a7
    • Dart version 2.19.0 (build 2.19.0-286.0.dev)
    • DevTools version 2.18.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode14.0.1.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2022.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 70.0.5
    • Dart plugin version 222.4167.21

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.71.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (5 available)
    • SM T225 (mobile)           • R9JT3004VRJ                              • android-arm64  • Android 12 (API 31)
    • iPhone (mobile)            • d9a94afe2b649fef56ba0bfeb052f0f2a7dae95e • ios            • iOS 15.7 19H12
    • iPhone 14 Pro Max (mobile) • 332079AF-E895-4685-910E-7B1E18B0C6B8     • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-0 (simulator)
    • macOS (desktop)            • macos                                    • darwin-x64     • macOS 12.6 21G115 darwin-x64
    • Chrome (web)               • chrome                                   • web-javascript • Google Chrome 106.0.5249.103
    ! Error: iPhone is busy: Fetching debug symbols for iPhone. Xcode will continue when iPhone is finished. (code -10)

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```
</details>

**Comment by what2003** [comment]
Wasted time to reporting bug,  only result is my server exposed here now getting someone's attack.
This flutter security issue makes every flutter build app face MITM attack risk. 
Appreciate  Google, but BIG disappointed by this team get paid not doing their jobs!

**Comment by jmagman** [comment]
@what2003 please refer to our [code of conduct](https://github.com/flutter/flutter/blob/master/CODE_OF_CONDUCT.md) in regards to respectful, welcoming communication.

https://github.com/what2003/flutter_application_1 is a 404.

**Comment by kandrelczyk** [comment]
I'm having the exact same issue. setTrustedCertificatesBytes doesn't work on iOS.

**Comment by jmagman** [comment]
@kandrelczyk are you able to provide a minimal reproducible code sample app then? When I investigated this issue the one that was previously provided is no longer available (my 404 comment).

**Comment by kandrelczyk** [comment]
@jmagman here you go: https://github.com/kandrelczyk/flutter-selfsigned-example

All this app does is make a http call to https://185.156.23.215:8443/test which uses a self-signed cert. The root CA is added to security context using setTrustedCertificatesBytes. When running is iOS simulator it results in:

[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: HandshakeException: Handshake error in client (OS Error: 
	CERTIFICATE_VERIFY_FAILED: application verification failure(handshake.cc:393))

I've manually verified the cert with the CA and it's correct. I've also added the rootCA to OS X keychain and tested with curl. It works. I've tried both p12 and PEM formats for the CA, both give me the same error. This could be some silly error on my side but I've went through all the docs and can't find any issue. It really looks like the new SecurityContext is just not used by the HttpClient.

**Comment by habull1101** [comment]
Until now, I still have this issue. I got an error _CERTIFICATE_VERIFY_FAILED: application verification failure(handshake.cc:393))_

Has this issue been resolved yet? **If not, what is the workround alternative?**

**Comment by zeevgrim** [comment]
I'm having the exact same issue. setTrustedCertificatesBytes doesn't work on iOS.

**Comment by brianquinlan** [comment]
@kandrelczyk Thanks very much for the example. As far as I can tell, only DER formatted certificates are acceptable on iOS.

You already have the DER file in your assets directory (`rootCA.der`) so could you change the path in `main.dart` and try again?

**Comment by kandrelczyk** [comment]
Hi @brianquinlan ,

When I try to use the rootCA.der file I'm getting following error:

```
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: TlsException: Failure trusting builtin roots (OS Error: 
	BAD_PKCS12_DATA(pkcs8_x509.c:657), errno = 318767204)
#0      _SecurityContext.setTrustedCertificatesBytes (dart:io-patch/secure_socket_patch.dart:249:26)
#1      main (package:selfsigned/main.dart:12:11)
```

Looks like setTrustedCertificatesBytes requires p12 and as far as I know you can't convert a DER to a p12, not usuing openssl.

**Comment by brianquinlan** [comment]
@kandrelczyk Thanks for trying this. Let me take a more detailed look.

**Comment by brianquinlan** [comment]
Running @kandrelczyk 's example on macOS (I assume that the connection is supposed to fail?):

```
Building macOS application...
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: SocketException: Connection failed (OS Error: Operation not permitted, errno = 1), address = 185.156.23.215, port = 8443
#0      _NativeSocket.startConnect (dart:io-patch/socket_patch.dart:721:35)
#1      _RawSocket.startConnect (dart:io-patch/socket_patch.dart:1914:26)
#2      RawSocket.startConnect (dart:io-patch/socket_patch.dart:27:23)
#3      RawSecureSocket.startConnect (dart:io/secure_socket.dart:297:22)
#4      SecureSocket.startConnect (dart:io/secure_socket.dart:77:28)
#5      _ConnectionTarget.connect (dart:_http/http_impl.dart:2482:26)
#6      _HttpClient._getConnection.connect (dart:_http/http_impl.dart:2924:12)
#7      _HttpClient._getConnection (dart:_http/http_impl.dart:2929:12)
#8      _HttpClient._openUrl (dart:_http/http_impl.dart:2784:12)
#9      _HttpClient.getUrl (dart:_http/http_impl.dart:2627:48)
#10     main (package:selfsigned/main.dart:15:32)
<asynchronous suspension>
```

running on iOS:

```
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: HandshakeException: Handshake error in client (OS Error:
	CERTIFICATE_VERIFY_FAILED: application verification failure(handshake.cc:393))
#0      _SecureFilterImpl._handshake (dart:io-patch/secure_socket_patch.dart:99:46)
#1      _SecureFilterImpl.handshake (dart:io-patch/secure_socket_patch.dart:142:25)
#2      _RawSecureSocket._secureHandshake (dart:io/secure_socket.dart:918:54)
#3      _RawSecureSocket._secureHandshake (dart:io/secure_socket.dart:921:15)
<asynchronous suspension>
#4      _RawSecureSocket._tryFilter (dart:io/secure_socket.dart:1047:13)
<asynchronous suspension>
```

**Comment by brianquinlan** [comment]
The failure when I switch the version to use the `.der` file (same on iOS/macOS):

```
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: TlsException: Failure trusting builtin roots (OS Error:
	BAD_PKCS12_DATA(pkcs8_x509.c:609), errno = 318767204)
#0      _SecurityContext.setTrustedCertificatesBytes (dart:io-patch/secure_socket_patch.dart:249:26)
#1      main (package:selfsigned/main.dart:12:11)
<asynchronous suspension>
```

**Comment by kandrelczyk** [comment]
Hi @brianquinlan ,

I didn't try running it on macOS so not sure what's causing the SocketException. The HandshakeException seen on iOS is the reported issue.

**Comment by brianquinlan** [comment]
> Hi @brianquinlan ,
> 
> I didn't try running it on macOS so not sure what's causing the SocketException. The HandshakeException seen on iOS is the reported issue.

I was able to create a working example using a PEM file:
https://github.com/kandrelczyk/flutter-selfsigned-example/compare/main...brianquinlan:flutter-selfsigned-example:modified-test?expand=1

After converting to a DEX file (`openssl x509 -outform der -in assets/cert/trusted_certs.pem -out assets/cert/trusted_certs.der`), I get the exception on macOS, iOS and Android:

```
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: TlsException: Failure trusting builtin roots (OS Error:
	BAD_PKCS12_DATA(pkcs8_x509.c:609), errno = 318767204)
#0      _SecurityContext.setTrustedCertificatesBytes (dart:io-patch/secure_socket_patch.dart:249:26)
#1      main (package:selfsigned/main.dart:14:11)
```

Does someone have a self-contained example that works on Android but does *not* work on iOS?
