### ISSUE TITLE
Remove recursion from the framework's trees

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#112888]
In local testing replacing `Element.renderObject`'s recursive implementation with an iterative implementation was 30% faster for AOT and 97% faster for JIT on x86_64, in the case where only one object was checked.  (https://github.com/flutter/flutter/pull/112885).  The difference should be even more dramatic for deeper use cases.

For most code this optimization isn't important but framework's most trafficked objects should be purged of recursion: ie `framework.dart` and `object.dart` (Widget, Element, RenderObject, etc.).

**Comment by jonahwilliams** [comment]
I don't think we can or want to remove _all_ recursion. For example, most of the build/first build recursion usage in the Element class also for new Element subclasses to be introduced outside of the framework and work correctly.

**Comment by gaaclarke** [comment]
Yea, thinking about it a bit too, it might not be so much that recursion is the issue in the example I have listed in the description, but may be more the fact that I removed a closure invocation.  As I pointed out in https://github.com/flutter/flutter/pull/112871/files there are still some optimizations that aren't happening with closures.

We can at least audit the easy ones to test like `Element.renderObject`.

**Comment by gaaclarke** [comment]
I tried the change on `Element.reassemble` and didn't get the same benefit with a tree of 1024 nodes.  The iterative version matched the recursive.  I think `Element.renderObject` was a special case where usually we didn't have to recurse and were able to eliminate the closure invocation.  I also tried a DoubleLinkedQueue but got the same results.  It isn't worth investigating that any further.

<details>
<summary>benchmark:</summary>

```dart
// @dart=2.12
import 'dart:collection';

class Element {
  List<Element> children = <Element>[];
  bool _needsBuild = false;

  void markNeedsBuild() {
    _needsBuild = true;
  }

  void reassemble() {
    final Queue<Element> elements = Queue<Element>();
    elements.addLast(this);
    while (elements.isNotEmpty) {
      Element current = elements.removeFirst();
      current.markNeedsBuild();
      current.visitChildren(elements.addLast);
    }
  }

  void reassemble2() {
    markNeedsBuild();
    visitChildren((Element child) {
      child.reassemble();
    });
  }

  void visitChildren(void Function(Element) func) {
    children.forEach(func);
  }
}

Element _makeElement(int width, int depth) {
  Element element = Element();
  if (depth > 1) {
    for (int i = 0; i < width; ++i) {
      element.children.add(_makeElement(width, depth - 1));
    }
  }
  return element;
}

void main() {
  Element foo = _makeElement(2, 10);
  int numIterations = 100000;
  {
    Stopwatch stopWatch = Stopwatch();
    stopWatch.start();
    for (int i = 0; i < numIterations; ++i) {
      foo.reassemble();
    }
    stopWatch.stop();
    print('${foo._needsBuild} reassemble ${stopWatch.elapsedMicroseconds / numIterations.toDouble()} µs');
  }
  {
    Stopwatch stopWatch = Stopwatch();
    stopWatch.start();
    for (int i = 0; i < numIterations; ++i) {
      foo.reassemble2();
    }
    stopWatch.stop();
    print('${foo._needsBuild} reassemble2 ${stopWatch.elapsedMicroseconds / numIterations.toDouble()} µs');
  }
}
```

</details>

**Comment by gaaclarke** [comment]
I'm going to close this.  I looked through framework.dart and object.dart for places where we create a recursive closure and invoke it with `(this)` like `Element.renderObject` did and I don't see anymore.  It's not worth investigating this anymore.
