### ISSUE TITLE
Bundle the locally-built CanvasKit in Flutter tool

### ISSUE THREAD

**Issue by hterkelsen** [flutter/flutter#112825]
We are now building CanvasKit in the Flutter engine and on LUCI. We should get the CanvasKit engine artifacts and bundle it with `flutter_web_sdk` when we download the Web SDK in the Flutter tool.

**Comment by hterkelsen** [comment]
This is mostly addressed by https://github.com/flutter/flutter/pull/113072 which will use the prebuilt CanvasKit once it has been made available

**Comment by yjbanov** [comment]
Fixed by https://github.com/flutter/flutter/pull/118654
