### ISSUE TITLE
Missing data for new_gallery__crane_perf on SM-A025V

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#112804]
Missing data for most of Sept. for new_gallery__crane_perf on SM-A025V

https://flutter-flutter-perf.skia.org/e/?begin=1654615420&end=1664812044&keys=X4fd116764a3ad8548527a9b3e1e8163b&requestType=0&xbaroffset=31398

@keyonghan @yusuf-goog  Is this known/intentional?

**Comment by keyonghan** [comment]
Checked a couple of data points between 09/01 and 09/27, we do have corresponding metrics.
E.g.: [5a7b0bdf13d2a70b93f7710b5e93173cc86c493c (09/21)](https://pantheon.corp.google.com/storage/browser/_details/flutter-skia-perf-prod/flutter-flutter/2022/09/21/03/d98b0c9c7cdd9f9fa7493558c489e90fd21c30f8/new_gallery__crane_perf_intel_linux_SMA025V_values.json;tab=live_object?project=flutter-infra-staging)

@yusuf-goog Do you mind create a SKIA bug (https://bugs.skia.org/) to track anything wrong from their side?

**Comment by yusuf-goog** [comment]
Created: https://bugs.chromium.org/p/skia/issues/detail?id=13790

**Comment by keyonghan** [comment]
Actually we are not missing any date. There are two types of device_version testbeds (android-29 and android-30). Here is the chart with both:
https://flutter-flutter-perf.skia.org/e/?begin=1660546800&end=1665071244&queries=device_type%3DSM-A025V%26sub_result%3D99th_percentile_frame_rasterizer_time_millis%26test%3Dnew_gallery__crane_perf&requestType=0&selected=commit%3D31478%26name%3D%252Carch%253Dintel%252Cbranch%253Dmaster%252Cconfig%253Ddefault%252Cdevice_type%253DSM-A025V%252Cdevice_version%253Dandroid-30%252Chost_type%253Dlinux%252Csub_result%253D99th_percentile_frame_rasterizer_time_millis%252Ctest%253Dnew_gallery__crane_perf%252C&xbaroffset=31398

**Comment by zanderso** [comment]
@keyonghan how do we get this benchmark to report its result as a single series in SkiaPerf?

**Comment by zanderso** [comment]
Raising to P2 to track down why this (and other?) benchmarks are toggling back and forth between different series.

**Comment by keyonghan** [comment]
Does the `device_version` matter from benchmark perspective? If not, we can simply drop this tag to combine those two data sequences.

**Comment by zanderso** [comment]
Two things:
1. It likely doesn't matter, and we should drop the tag.
2. Benchmarks should be pinned to a single `device_version` at a time, and not toggle between two different versions.

**Comment by keyonghan** [comment]
As for 1, I forgot to mention earlier, it may cause data discontinuity as earlier data does contain the device_version tag.
As for 2, will it be too granular to pin the device_version? Currently for linux, we pin only on device_type level (e.g. motog4, samsung a02). /cc @yusuf-goog do you know if all our samsung a02 come with same API version?

**Comment by keyonghan** [comment]
@zanderso Do those two points mentioned above SG to you? I want to make sure we are on the same page before moving forward with corresponding changes.

**Comment by zanderso** [comment]
1. As we've discussed previously a few times, it is okay to cause a discontinuity if it is only going to happen once, and then not happen again for a good long time. How confident are you that that will be the case here?
2. Runs with different OS version should appear in the same series, but we should keep as many devices as possible on the same OS version on the off chance that OS version does affect benchmark performance.

**Comment by keyonghan** [comment]
As for 1. Whenever we are not bringing the `device_version` tag back, this is a one-time change.

As for 2. Based on Skia, different OS version data would not appear in the same series (we can view them as a same series by un-selecting the os tag, but the alert is triggered only on separate os series). 
I will take a look how our fleets look like based on device os.

**Comment by keyonghan** [comment]
All MotoG4 are with android 24, whereas samsung ones are with android 30 or 31. Since we have only two bots of samsung A02 and two bots of samsung S10, pining to a fixed version will cause capacity to half. I will defer the pining device version until we have more capacity.

For now I will first drop the device_version from Skia benchmark.

**Comment by keyonghan** [comment]
https://flutter-review.googlesource.com/c/recipes/+/34941 to drop device_version tag.
