### ISSUE TITLE
Crashed: com.apple.main-thread EXC_BREAKPOINT 0x0000000101522608

### ISSUE THREAD

**Issue by siddew201** [flutter/flutter#112846]
We are getting crash in production and it is not reproducible. Any help is appreciable.

Flutter 3.0.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision https://github.com/flutter/flutter/commit/ee4e09cce01d6f2d7f4baebd247fde02e5008851 (5 months ago) • 2022-05-09 16:45:18 -0700
Engine • revision d1b9a6938a
Tools • Dart 2.17.0 • DevTools 2.12.2

## Logs

Crashed: com.apple.main-thread
0  TCPApp                         0xe12608 NeuFlutterEngine.setup() + 41 (NeuFlutterEngine.swift:41)
1  TCPApp                         0x6b6d84 NeuEngineCache.getEngine(identifier:) + 18 (NeuEngineCache.swift:18)
2  TCPApp                         0x55e7b4 partial apply for closure #1 in FlutterAnalyticsProvider.eventTracker(eventType:payload:funcName:) + 27 (FlutterAnalyticsProvider.swift:27)
3  TCPApp                         0x8f10 thunk for @escaping @callee_guaranteed () -> () (<compiler-generated>)
4  libdispatch.dylib              0x63094 _dispatch_call_block_and_release
5  libdispatch.dylib              0x64094 _dispatch_client_callout
6  libdispatch.dylib              0x10d40 _dispatch_main_queue_drain
7  libdispatch.dylib              0x10990 _dispatch_main_queue_callback_4CF$VARIANT$mp
8  CoreFoundation                 0x4dab4 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 12
9  CoreFoundation                 0xafd8 __CFRunLoopRun + 2544
10 CoreFoundation                 0x1dc30 CFRunLoopRunSpecific + 572
11 GraphicsServices               0x1988 GSEventRunModal + 160
12 UIKitCore                      0x4e5c50 -[UIApplication _run] + 1080
13 UIKitCore                      0x27f3d0 UIApplicationMain + 336
14 TCPApp                         0xbc5c5c main + 39 (AppDelegate.swift:39)
15 ???                            0x108f183d0 (Missing)

<details>
<summary>Logs</summary>

```
```

```
```

</details>

**Comment by huycozy** [comment]
@siddew201 Could you provide `pubspec.yaml` file content and a list of affected device information?
Also, please provide the output of flutter doctor -v as well. Thank you!

**Comment by siddew201** [comment]
Hi @huycozy Thanks for response . Please find pubspec.yml file content and affected device/OS detail below

Pubspec.yml content

version: 1.0.0+1

environment:   sdk: ">=2.16.2 <3.0.0"

dependencies:   flutter:     sdk: flutter

 collection: ^1.16.0   flutter_dotenv: ^5.0.2   mobx: ^2.0.7+4   flutter_mobx: ^2.0.6+1   routemaster: ^1.0.1   webview_flutter: ^3.0.4   json_annotation: ^4.6.0   provider: ^6.0.3   intl: ^0.17.0   easy_debounce: ^2.0.2+1   html: ^0.15.0   url_launcher: ^6.1.5   hive: ^2.2.3   hive_flutter: ^1.1.0   lottie: ^1.3.0   avatars: ^2.0.2   focus_detector: ^2.0.1   dotted_border: ^2.0.0+2   geocoding: ^2.0.5   geolocator: 8.2.1   device_info_plus: 4.1.0   visibility_detector: ^0.2.2   launchdarkly_flutter_client_sdk: ^1.1.2   new_version: ^0.3.1   cupertino_icons: ^1.0.5   modal_bottom_sheet: ^2.1.0   package_info_plus: ^1.4.2   path: ^1.8.0   chewie: ^1.3.4   video_player: ^2.4.5   youtube_player_flutter: ^8.1.0   cached_network_image: ^3.2.1   animations: ^2.0.3   expandable_page_view: ^1.0.17

dev_dependencies:   flutter_lints: ^2.0.1   json_serializable: ^6.1.1   build_runner: ^2.2.0   flutter_test:     sdk: flutter

flutter:   module:     androidX: true     androidPackage: com.tatadigital.neu_app_embed     iosBundleIdentifier: com.tatadigital.neuAppEmbed   assets:     - assets/logo_512x512.png     - assets/[logo_32x32@2x.png](mailto:logo_32x32@2x.png)

Affected Devices and CrashCount:
iPhone7 - (3)

Affected OS and CrashCount:
15.4.0 - (3 Crash)

**Comment by huycozy** [comment]
@flutter-symbolizer-bot https://github.com/flutter/flutter/issues/112846#issue-1395773092 force flutter#v3.0.0 ios release arm64

**Comment by huycozy** [comment]
@siddew201 It doesn't have a lot of Flutter logs here as I can see. Are there any remaining logs from Crashlytic tool that you can provide?
