### ISSUE TITLE
[ led + recipe ] environment set to `production` even though led uses `staging` builder

### ISSUE THREAD

**Issue by XilaiZhang** [flutter/flutter#112818]
Sometimes we would like to test a led run using a staging builder, but if the target is marked as `environment: production` in .ci.yaml, then the testing environment from .ci.yaml overrides the testing environment specified in led run, and make the led run environment obsolete. As @christopherfujino pointed out, this is due to recipe only parses the .ci.yaml target environment, and not the led environment. 

The current workaround I am using is to edit the recipe locally to have a staging environment, run led tests, and then switch back to a production environment when submitting. A recent example of failure is https://ci.chromium.org/raw/build/logs.chromium.org/flutter/led/xilaizhang_google.com/1fa0782acf35e1bb7725dad36a1266ea1db9f4d298b9507f7e54aac976751d7c/+/build.proto?server=chromium-swarm.appspot.com. 

cc @godofredoc

**Comment by godofredoc** [comment]
I'll take a look in most cases prod led builds are not allowed but sometimes they are useful for LUCI managers to validate builds.

**Comment by christopherfujino** [comment]
I think here the request as to be able to do a staging build of a target whose `properties.environment == Production` in .ci.yaml, like https://github.com/flutter/engine/blob/main/.ci.yaml that uses engine_v2/engine_v2 recipe.

**Comment by godofredoc** [comment]
We may be able to get rid of the environment property as I introduced it as a quick way of calculating the drone names.

**Comment by godofredoc** [comment]
> We may be able to get rid of the environment property as I introduced it as a quick way of calculating the drone names. We can use the bucket name for the same purpose.

**Comment by XilaiZhang** [comment]
> We may be able to get rid of the environment property as I introduced it as a quick way of calculating the drone names.
cool, yeah would be great if we can add documentation on how the drone properties thawed from self.m.properties.thaw() as well

**Comment by godofredoc** [comment]
Fixed with: https://flutter-review.googlesource.com/c/recipes/+/35164
