### ISSUE TITLE
[flutter_tools] Tool should verify contents of SDK once per version

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#112875]
On Windows, we get many errors where files that are part of the Flutter SDK repository are missing (e.g. https://github.com/flutter/flutter/issues/112872). I believe this is because sometimes unzipping the pre-built release package with Windows' default unzipping mechanism can silently fail, only extracting part of the archive.

The tool should verify that all of the files in the flutter/flutter repo are present on disk, and persist this to the persistent tool state so that it only needs to be verified once per version.

**Comment by christopherfujino** [comment]
Actually, it's valid to have a dirty git checkout while running the tool, so not sure what to do here. Also note, if this is a doctor validator, the doctor may fail trying to cache artifacts.

**Comment by christopherfujino** [comment]
> Actually, it's valid to have a dirty git checkout while running the tool, so not sure what to do here. Also note, if this is a doctor validator, the doctor may fail trying to cache artifacts.

I think we should crash, with a note that if this intended set a `flutter config` setting to allow a dirty checkout.

**Comment by eliasyishak** [comment]
@christopherfujino following – curious as to how this problem is solved
