### ISSUE TITLE
Remove `strip_bitcode` logic from engine scripts

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#112896]
> Starting with Xcode 14, bitcode is no longer required for watchOS and tvOS applications, and the App Store no longer accepts bitcode submissions from Xcode 14.

Most bitcode usage was removed in https://github.com/flutter/engine/pull/36596.  Also remove `strip_bitcode` logic.  See https://github.com/flutter/engine/pull/36496

https://github.com/flutter/engine/blob/2b8d506dff6d3f3bc9517cf5fe358d1d094fbcc5/sky/tools/macos.gni#L18-L20
```
# When we stop building with bitcode enabled, this template and the
# strip_bitcode.py script can be deleted and users can call copy() instead.
```

cc @cbracken

**Comment by cbracken** [comment]
I've got a patch together that covers the part of this that involves blowing away `strip_bitcode` and the surrounding script and template; just working through verifying the build outputs now.
