### ISSUE TITLE
Shadow on iOS's Gallery's Card screen has white/light line immediately under app bar

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#11285]
Here's a screenshot from gallery's Card screen on iPhone. Notice the white/light line immediately under the app bar.
<img width="530" alt="screen shot 2017-07-18 at 5 05 38 pm" src="https://user-images.githubusercontent.com/5479/28344880-607c802c-6bdb-11e7-88d2-616fb7e7de00.png">

Most apps on iOS have a very light shadow, but for the apps that do have a Material shadow (like, Calendar), notice the shadow doesn't have a light line under the app bar:
<img width="522" alt="screen shot 2017-07-18 at 5 06 49 pm" src="https://user-images.githubusercontent.com/5479/28344924-983733a4-6bdb-11e7-988f-135f68ee3d14.png">

Note: the main screen of the gallery looks good. There's something happening when we go into a sub-screen.

**Comment by xster** [comment]
Probably the same issue as #11035

**Comment by eseidelGoogle** [comment]
@jvanverth is looking at #11035 as we speak to my knowledge.

**Comment by sethladd** [comment]
Just tested, looks fixed!
