### ISSUE TITLE
Help for understanding flutter scrollable

### ISSUE THREAD

**Issue by pooriana** [flutter/flutter#112932]
Hi everyone .
I was working with scrollables and viewports in flutter and i can't realize how the scrollable widget notified when the scrollPosition change and cause the viewport scroll offset change! (my question is about updating the drag not start and end)
I realized that this method timeline invokes when the user dragging (touch moves on screen) :

Scrollable::_handleUpdate ->
ScrollDragController::update ->
ScrollPositionWithSingleContext::applyUserOffset ->
ScrollPositionWithSingleContext::setPixels ->
ScrollPosition::setPixels 

in ScrollPosition::setPixels i see that just bubble up the notification for NotificationListeners and notifyListeners for call the callback functions that registered. 
there is no registered callback from scrollables and i recognize that by default only ScrollController::notifyListeners registered. which the scrollable widget even not listening to scroll controller class to be notified .
am i missing something ? 
if not, how scrollable widget notifies when scrolled and rebuild itself to expose new scroll position to viewport.
sorry for my poor English.

**Comment by darshankawar** [comment]
@pooriana 
Thanks for the report, but I think your question is better suited for support channels like StackOverflow or Flutter's discord channel where you can get the help.
This repo is essentially to track bugs and feature requests so I am going ahead and closing this.
