### ISSUE TITLE
[android] PlatformView renders on top of everything after orientation change

### ISSUE THREAD

**Issue by ppiatkowski-here** [flutter/flutter#112929]
## Details
**Flutter 3.3.3**
**Target Platform: Android**
We're using Platform View. It uses SurfaceView to render camera preview. We're using Hybrid Composition mode (initExpensiveAndroidView)

## Steps to reproduce
1. Install this app on Android device [hybrid_composition_camera_example.zip](https://github.com/flutter/flutter/files/9714180/hybrid_composition_camera_example.zip)
2. Manually add camera permissions to this app (hc_app). It will not ask for permissions. Sorry about that.
3. Run the app
4. Tap 'Press me' button on home page.
5. You will be navigated to a second screen which does NOT have a platform view.
6. Rotate device to switch to landscape.

## Expected
App switches to landscape. I still see the second screen. I don't see camera preview platform view.

## Actual
App switches to landscape. Camera preview (platform view) is visible even though it is not in a widget hierarchy of this screen. It looks like it's rendered on top of everything. Camera preview takes up about half of the screen. When you switch back to portrait the camera preview will take up almost whole screen.

## GIF of repro steps 
![hybrid_composition_issue](https://user-images.githubusercontent.com/87531400/194023367-8c8b309a-5d85-49e2-b9bb-af126ebd145b.gif)

This is the app that reproduces the issue
[hybrid_composition_camera_example.zip](https://github.com/flutter/flutter/files/9714283/hybrid_composition_camera_example.zip)

## Additional notes
When using Virtual Display mode we don't have this issue but we have other issues on Android 12. We have been using Virtual Display and we are trying to switch to Hybrid Composition because of Android 12 issues.

## Logs

<details>
<summary>Logs</summary>

```
Analyzing hybrid_composition_camera_example...
No issues found! (ran in 3.2s)
```

```
[✓] Flutter (Channel stable, 3.3.3, on macOS 12.4 21F79 darwin-x64, locale en-PL)
    • Flutter version 3.3.3 on channel stable at /Users/pawel/bin/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18a827f393 (7 days ago), 2022-09-28 10:03:14 -0700
    • Engine revision 5c984c26eb
    • Dart version 2.18.2
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/pawel/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = /Users/pawel/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13C100
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.71.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (3 available)
    • SM A326B (mobile) • RFCR90FDRCM • android-arm64  • Android 12 (API 31)
    • macOS (desktop)   • macos       • darwin-x64     • macOS 12.4 21F79 darwin-x64
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 105.0.5195.125
    ! Error: Could not locate device support files. iPhone XR may be running a version of iOS that is not supported by this version of Xcode. You can download the latest version of Xcode
      from the Mac App Store or developer.apple.com. (code 601)

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by ppiatkowski-here** [comment]
Modifying MainActivity.kt like below seems to help as a workaround. But please keep in mind that this app is just an example. In reality we have a plugin with this issue. We need a plugin-level solution.
```
class MainActivity: FlutterActivity() {
    override fun configureFlutterEngine(flutterEngine: FlutterEngine) {
        flutterEngine
                .platformViewsController
                .registry
                .registerViewFactory("com.example.nativeView", NativeViewFactory())
    }

+    override fun onCreate(savedInstanceState: Bundle?) {
+        getIntent().putExtra("background_mode", "transparent");
+        super.onCreate(savedInstanceState);
+    }
+	
+    override fun onFlutterTextureViewCreated(flutterTextureView: FlutterTextureView) {
+        // We do not actually need a transparent TextureView.
+        flutterTextureView.setOpaque(true);
+       super.onFlutterTextureViewCreated(flutterTextureView);
+    }
}
```

**Comment by ppiatkowski-here** [comment]
I think this might be connected to https://github.com/flutter/flutter/issues/112917. 
Repro steps described there also reproduce this issue without the need for orientation change.
Repro steps being:
1. Tap 'Press me'
2. Tap home button
3. From the task list choose the app again

**Comment by exaby73** [comment]
Hello @ppiatkowski-here. Is this issue reproducible when resuming the app from the background? See https://github.com/flutter/flutter/issues/89558

**Comment by marius-campan** [comment]
Hi @exaby73 This issue is reproducible also when resuming from background.

**Comment by huycozy** [comment]
@ppiatkowski-here Can you also update your sample code to use `initSurfaceAndroidView` instead? Just to make sure two issues are duplicated. (because once they are duplicated, we need to close this issue to anyone can update to a single issue https://github.com/flutter/flutter/issues/89558)

>Is it possible to raise the priority?

Once many people face the issue (as noted by the number of upvotes and comments) this is possible.

**Comment by ppiatkowski-here** [comment]
@huycozy 

In Flutter 3.3 `initSurfaceAndroidView` is not the same function as `initSurfaceAndroidView` a year ago when the other issues were raised. If I switch to initSurfaceAndroidView now while using Flutter 3 it will not use Hybrid Composition mode but will fall back to Virtual Display mode as described here https://github.com/flutter/flutter/pull/109161. @stuartmorgan could you confirm that initExpensiveAndroidView in Flutter 3.3 is equivalent of initSurfaceAndroidView in Flutter 2?

**Comment by stuartmorgan** [comment]
> @stuartmorgan could you confirm that initExpensiveAndroidView in Flutter 3.3 is equivalent of initSurfaceAndroidView in Flutter 2? Meaning that they select Hybrid Composition mode.

Yes, that's correct.

**Comment by huycozy** [comment]
Hi @ppiatkowski-here 
In case you still keep using Hybrid Composition mode, please follow #89558 for further updates. You can leave there your comment and react an upvote to the original comment will help to raise the issue. 

In case you switch to Virtual Display but still have another issue on Android 12, please file a new issue for that. I'm not sure if issue #109690 can be related, but if you see it can do, please follow it and leave there your comment too. 

If you feel this issue is safe to close, please do, so that issues are solved in a single issue. Thanks!

**Comment by marius-campan** [comment]
#109690 doesn't seem to be related since the attached example app returns directly a SurfaceView as platform view.

Switching the app to using initSurfaceAndroidView does indeed lead to other issues on changing orientation, but only on the SurfaceView app page, like loosing the camera feed entirely to a page 
with a static color like in the attached screenshot ![VirtualDisplay_SurfaceView_onRotation](https://user-images.githubusercontent.com/60092793/194478162-46ce5b8f-ee05-4db1-a425-d4a9f306be62.jpg)

**Comment by ppiatkowski-here** [comment]
The issue is not fixed but I'm closing this as a duplicate of https://github.com/flutter/flutter/issues/89558
If you have the same problem please leave a comment in that ticket and react 👍 on the original comment there to help get it prioritized.
