### ISSUE TITLE
HTML Report for integration_test results

### ISSUE THREAD

**Issue by anfruiz** [flutter/flutter#112977]
When I execute my tests with integration_test package, I just have an xml file with the results with minimum information.

Is possible to have a html report like serenity or allure report, with live evidence or something like that?

**Comment by darshankawar** [comment]
@anfruiz 
See if [this](https://medium.com/testvagrant/flutter-integration-test-junit-report-generation-with-gitlab-integration-cebf389e011e) helps in your case.
