### ISSUE TITLE
Networking in MacOS.  info out of date

### ISSUE THREAD

**Issue by WorikQCI** [flutter/flutter#112901]
i struck being unable to connect with network on MacOS.

This...
https://github.com/flutter/flutter/issues/47606#issuecomment-568264294

is out of date.  The page refered to (that it refers to) does not mention this problem, such that it helps.

I have solved th problem but the docs are stale

**Comment by stuartmorgan** [comment]
> This... [#47606 (comment)](https://github.com/flutter/flutter/issues/47606#issuecomment-568264294)
> 
> is out of date. [...] I have solved th problem but the docs are stale

That's a three-year old comment in an issue; issue comments aren't documentation.

The [actual documentation](https://docs.flutter.dev/development/platform-integration/macos/building#entitlements-and-the-app-sandbox) is up to date.
