### ISSUE TITLE
Upload to TestFlight issue. Flutter 3.3.3

### ISSUE THREAD

**Issue by yaroslav13** [flutter/flutter#112989]
The builds of ios IPA finished successfully. Used this command 

`
fvm flutter build ipa --release --flavor prod --split-debug-info=ios_symbols --dart-define=BUILD_TYPE=prod --dart-define=MOCK_LOCATION=real  
`
 
Uploading to the Testflight using Transporter or just Xcode or fastline also successfully. 

But new versions don't display in Testflight. Nothing helps. 

When downgrade version to 2.10.3 everything works properly and the build displays on Testflight.

**Comment by danagbemava-nc** [comment]
Hi @yaroslav13, I'm not sure if this is a flutter issue considering everything works fine including the upload. It could just be a matter of waiting for some time before the new build shows up in testflight. 

What do you see in the `TestFlight` section when you upload the app (after waiting a couple of minutes/hours)?

I did upload a test app to `TestFlight` and the new version is visible in testflight. 

<details>
<summary>screenshot</summary>

<img width="1176" alt="Screenshot 2022-10-06 at 10 20 58" src="https://user-images.githubusercontent.com/88313112/194290039-408bea68-41e2-43a7-9916-7607e42ed744.png">

</details>

**Comment by yaroslav13** [comment]
The previous branch with 2.10.3 was successfully uploaded and displayed in the Testflight section. After updating flutter and all dependencies - uploading finished successfully but the build doesn't appear in Testflight (more 5 day waiting). Errors/warnings from Testflight - nothing
