### ISSUE TITLE
[iOS][in_app_purchase][SandBox] NSLocalizedFailureReason: An unknown error occurred

### ISSUE THREAD

**Issue by SalsabeelaHasan** [flutter/flutter#112988]
## Detailes:
Flutter version: 3.3.2
in_app_purchase: 3.0.7
iOS version: happen in all versions, in last test i use 15.7 version.
purchase type: buyNonConsumable.
Dart version: 2.18.1.
Xcode versio: 14.0.1
CocoaPods version: 1.11.3

## Steps to Reproduce
i'm trying to do a fake subscription using the sandbox account, the purchase process using buyNonConsumable function is completed successfully (the native dialog that said: "your purchase was successful" is popping),
but when it come to get the PurchaseDetails, there is no verificationData or any thing, except this error :  

`
{NSUnderlyingError: {domain: ASDErrorDomain, userInfo: {NSLocalizedDescription: Unhandled exception, NSLocalizedFailureReason: An unknown error occurred, NSUnderlyingError: {domain: AMSErrorDomain, userInfo: {NSUnderlyingError: {domain: AMSErrorDomain, userInfo: {AMSEngagementPresented: true, NSLocalizedDescription: Engagement Request Cancelled}, code: 6}, NSLocalizedFailureReason: The dialog was cancelled, AMSURL: https://sandbox.itunes.apple.com/WebObjects/MZBu
`

i cant handle this error, please help!. 

**Expected results:** 
retrieve data from PurchaseDetails when i use sandbox account. 

**Actual results:**  
NSUnderlyingError.

![IMG_0008](https://user-images.githubusercontent.com/62775384/194176453-13f14212-2192-4f38-8513-0ec7ef65cb80.PNG)

**Comment by danagbemava-nc** [comment]
Hi @SalsabeelaHasan, please provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the error you're facing so that we can verify this issue. 


Thank you

Thank you

**Comment by SalsabeelaHasan** [comment]
Hi @danagbemava-nc , 
starting with buyNonConsumable function : 
```  
 final ProductDetails productDetails = await getUserChoiceSubscriptionProductDetails(_kId);
    final PurchaseParam purchaseParam = PurchaseParam(productDetails: productDetails);
    if(Platform.isIOS){
      finishPrevTransactions().whenComplete(() =>{
        InAppPurchase.instance.buyNonConsumable(purchaseParam: purchaseParam).catchError((err) async {
          if (err is PlatformException && err.code == "storekit_duplicate_product_object") {
            _refreshIOSTransactions();
            print('error acquired doPurchase: msg : storekit_duplicate_product_object');
          }else{
            print('error acquired doPurchase: msg : $err ');
          }
          throw Exception('error acquired doPurchase : code : ${(err as PlatformException).code ?? "no code"}');
        }).then((value){
                      //the then value = true, and the process done successfully. 
                      Navigator.pushNamed(navigatorKey.currentContext, '/MySubscriptionsScreen');
        })
      });
      
  static Future finishPrevTransactions() async {
    var transactions = await SKPaymentQueueWrapper().transactions();
    // print("transactions = ${transactions.length}");
    if(transactions.length != 0){
      for(int i =0; i < transactions.length; i++){
        SKPaymentQueueWrapper().finishTransaction(transactions[i]);
      }
    }
  }  
```
the, the purchases stream that exist in main.dart file, will call a function named "verifyIosPurchase", that we use it to get the purchases details and verify, the error occurred in it :

```
static verifyIosPurchase(BuildContext context ,PurchaseDetails purchase,VerifyReceiptCallBack callBack) async {
    if(Platform.isIOS){
      if(purchase?.verificationData?.serverVerificationData?.isNotEmpty??false){
          //send the purchase detailes to our backend to save it.
     }else{
        //here is the error.
         throw Exception('::::::: Purchase :: verifyIosPurchase :: purchase.error?.details :: ${purchase.error?.details}');
}
}
}

```

**Comment by danagbemava-nc** [comment]
Hi @SalsabeelaHasan, I'm curious. After the "You're all set" dialog appears, do you see any other dialog? Your error seems to indicate that an engagement request was rejected. `The dialog was cancelled`

**Comment by SalsabeelaHasan** [comment]
Hi @danagbemava-nc ,
no other dialogs appear, just successful  dialog, then in the logs i see an exception as I explained earlier.

**Comment by SalsabeelaHasan** [comment]
should i do an experiment for catch the reason? maybe change  code, or test in release build .. etc?

**Comment by danagbemava-nc** [comment]
Hi @SalsabeelaHasan, I cannot reproduce your error. I tested a modified version of the plugin example and attempted to get the server data and there was no issue. Btw, you do not need the null checks on the verficationData as verificationData is not nullable.

**Comment by SalsabeelaHasan** [comment]
> Hi @SalsabeelaHasan, I cannot reproduce your error. I tested a modified version of the plugin example and attempted to get the server data and there was no issue. Btw, you do not need the null checks on the verficationData as verificationData is not nullable.
> 
> Can you provide any additional information that will help in reproducing the issue?

Hi @danagbemava-nc , are you using a plugin example or the code that I send?

**Comment by danagbemava-nc** [comment]
> Hi @danagbemava-nc , are you using a plugin example or the code that I send?
can you share the link that showed a code you tested?

I added the part about retrieving the verificationData to the plugin example since I do not have your `getUserChoiceSubscriptionProductDetails` method as well as the other methods that you have defined in your code. 

The plugin example can be found in https://pub.dev/packages/in_app_purchase/example

I replaced 

```dart
Future<bool> _verifyPurchase(PurchaseDetails purchaseDetails) {
    // IMPORTANT!! Always verify a purchase before delivering the product.
    // For the purpose of an example, we directly return true.
    return Future<bool>.value(true);
  }
```

with 

```dart
Future<bool> _verifyPurchase(PurchaseDetails purchaseDetails) {
    // IMPORTANT!! Always verify a purchase before delivering the product.
    // For the purpose of an example, we directly return true.
    if(Platform.isIOS){
      print(purchaseDetails.verificationData.serverVerificationData);
    }
    return Future<bool>.value(true);
  }
```

so I can print the verificationData. 

Btw, I see the code below in your sample. This is not the correct syntax for defining functions in dart. You only use the arrow if you are doing a one-line function, otherwise, you do not need the arrow.  

```
  finishPrevTransactions().whenComplete(() =>{
```
