### ISSUE TITLE
Used Control+C to copy text in textboxField in Flutter Windows

### ISSUE THREAD

**Issue by collinsNyakoni** [flutter/flutter#112927]
Used Control+C to copy text in textboxField in Flutter Windows

ERROR I GOT:

A KeyRepeatEvent is dispatched, but the state shows that the physical key is not pressed. If this occurs in real application, please report this bug to Flutter. If this occurs in unit tests, please ensure that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This was the event: KeyRepeatEvent#de25e(physicalKey: PhysicalKeyboardKey#700e0(usbHidUsage: "0x000700e0", debugName: "Control Left"), logicalKey: LogicalKeyboardKey#00100(keyId: "0x200000100", keyLabel: "Control Left", debugName: "Control Left"), character: null, timeStamp: 21:35:10.463212)
'package:flutter/src/services/hardware_keyboard.dart':
Failed assertion: line 432 pos 16: '_pressedKeys.containsKey(event.physicalKey)'

**Comment by darshankawar** [comment]
@collinsNyakoni 
This issue has already been fixed as part of https://github.com/flutter/flutter/issues/108646 and the fix is available on latest master, beta and hopefully stable. 
If you are not on latest versions of either channel, please upgrade and try again to see the change.
Closing.
