### ISSUE TITLE
[CP] Add a script to post-process docs. 

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#112967]
### issue_link

https://github.com/flutter/flutter/issues/111921

### Commit Hash

8fbd87065a60db50843dd77b01a91cae80af82d6

### Target

stable

### pr_link

https://github.com/flutter/flutter/pull/112228

### Impacted Users

release engineering team

### Impact Description

This is required to be able to release updated api docs on hotfixes to stable branch.

### Workaround

Do not release updated api docs in hotfixes. These docs should not changing too much in hotfix releases. 

### Risk

low

### Test Coverage

yes

### Validation Steps

After landing we can run the builder manually to validate docs are actually deployed.

**Comment by itsjustkevin** [comment]
@CaseyHillers and @XilaiZhang could you take a look at this cherry-pick?

**Comment by CaseyHillers** [comment]
Lgtm for approval

**Comment by itsjustkevin** [comment]
@godofredoc could you open a cherry-pick to the release branch please?  Your PR link points to the original PR.
