### ISSUE TITLE
AdaptiveLayout should allow more control over internal animations

### ISSUE THREAD

**Issue by oravecz** [flutter/flutter#112938]
## Use case

The existing internal animations to switch between a BottomNavigationBar and NavigationRail are distractingly slow at their current settings of 1s duration. I may be an anomaly, but I would like to see the default be in the neighborhood of 200ms to convey the subtlety of the effect, but without making the user pause to think, "Wow, this is moving really slow".

## Proposal

Ideally, exposing the animationController would allow most control, but I'd be satisfied with externalizing the duration.

**Comment by exaby73** [comment]
Hello @oravecz. If I am understanding correctly, are you proposing to add a animation duration field to control the animation when switching between, for example, `BottomNavigationBarItem`s?

**Comment by oravecz** [comment]
Yes, if the API is still in flux, I would recommend changing `internalAnimations` from a `bool` to a `Duration` or to an `int` holding milliseconds.

**Comment by exaby73** [comment]
Thank you for the information. Labelling the issue
