### ISSUE TITLE
Have some really basic widgets in widgets library

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#1129]
I think we should introduce ~~a layer between "widget" and "material", probably named "gui", that introduces the opinion that there are~~ [certain common widget types](https://en.wikipedia.org/wiki/Widget_(GUI)#List_of_common_generic_widgets), and define~~s~~ abstract interfaces for each one (e.g. an abstract "GUIButton" type that has an onPressed handler), and that stores UI-agnostic logic (e.g. the TabBarSelection class), but that doesn't actually introduce opinion about what the widgets should look like. Then, "material" would inherit from those where it makes sense.

This would make it much easier to introduce new widget sets, as used for example by the game.

----
(List from the comment below:)
- [ ] button: just has onPressed, disabled
- [ ] checkbox: just has onChanged
- [ ] radio button: value, groupValue, onChanged, enabled, handleChanged
- [ ] dropdown button: just has the list of items, the current value, onChanged, maybe _handleTap in some more generic form; and a DropDownMenuItem with child and value
- [ ] input: some of the more generic parts (not the material look and feel, e.g. not placeholder, the error reporting UI, though most of that isn't implemented yet anyway)
- [ ] tabs: the TabSelection widget, and basic infrastructure around that

**Comment by abarth** [comment]
Why not just put that into widgets.dart?

**Comment by Hixie** [comment]
My thinking was that you might want to not use these widgets. They introduce an opinion about what widget APIs should look like, but there's no reason you would want to use this opinion.

**Comment by abarth** [comment]
Would you move drag_target there too?  What about scrollable?  I guess I'm asking how to decide whether a given widget belongs in widgets in gui.

**Comment by Hixie** [comment]
Yeah, good question.

**Comment by Hixie** [comment]
Ok, I'm convinced that you're right. If we do this, it should be in widgets.api.

Looking at what it would be:
- [ ] button: just has onPressed, disabled
- [ ] checkbox: just has onChanged
- [ ] radio button: value, groupValue, onChanged, enabled, handleChanged
- [ ] dropdown button: just has the list of items, the current value, onChanged, maybe _handleTap in some more generic form; and a DropDownMenuItem with child and value
- [ ] input: some of the more generic parts (not the material look and feel, e.g. not placeholder, the error reporting UI, though most of that isn't implemented yet anyway)
- [ ] tabs: the TabSelection widget, and basic infrastructure around that

That's about it. I don't think a single build() function can actually be abstracted out. I'm not sure how valuable this actually ends up being since there's just not that much that can be truly reused.

Maybe an alternative that would be better for people who want to make their own widget set would be to make a truly basic widget set with zero bells and whistles, which would form a good starting point for people to copy and paste from. Then, if we find there's common code between that library and the material library, we move the common bits to widgets.

**Comment by Hixie** [comment]
I'm going to close this on the basis that it's too speculative. If we find we need this when we actually build another widget set let's revisit it.
