### ISSUE TITLE
The Xcode14 will recompile a lot of files even not change any files.

### ISSUE THREAD

**Issue by luckysmg** [flutter/flutter#112928]
## Steps to Reproduce
1. Use Xcode 14
2. Setup the env and compile engine according to [wiki](https://github.com/flutter/flutter/wiki/Compiling-the-engine#compiling-for-ios-from-macos)
3. compile ios engine.
4. Wait for compile to complete.
5. Close the terminal or wait somes minutes.
6. compile ios engine again.

### Result:
**A lot of files recompile again, but I didn't modify any code in these file.**

**This will not repo on Xcode 13 but can repo on Xcode 14.**
- [x]  I have reinstall Xcode and restart my mac.

**Comment by tummyhuang** [comment]
same problem，is there any progress？

**Comment by luckysmg** [comment]
Any updates for this?

**Comment by huycozy** [comment]
Hi @luckysmg Sorry for replying late. Labeling the issue for further investigation from the team.

**Comment by jmagman** [comment]
I have definitely seen this too, it wastes a lot of time.  @zanderso where would this investigation start, file a ninja bug against chromium?

**Comment by zanderso** [comment]
@luckysmg @jmagman Could you give the exact `flutter/tools/gn` command line that causes this to repro? I didn't a quick check of an `ios_debug` build at tip-of-tree, and this didn't happen.

**Comment by luckysmg** [comment]
I run this shell in engine dictionary

```
cd src
./flutter/tools/gn --ios --unoptimized
./flutter/tools/gn --unoptimized

ninja -C out/ios_debug_unopt && ninja -C out/host_debug_unopt
```

**Comment by jmagman** [comment]
It doesn't _always_ happen when I `gn`/`ninja`, maybe 1/3 of the time, often if there's a few minutes between runs.

**Comment by luckysmg** [comment]
@jmagman Yes. For me this can repo more frequently..😭😭

**Comment by zanderso** [comment]
I haven't been able to reproduce this with Xcode 14. Two debugging options. 

Easy:
After an unexpected rebuild: Attach the result of https://github.com/nico/ninjatracing, and I'll take a look. That will explain what is rebuilding unexpectedly, but not necessarily why.

Hard:
During an unexpected rebuild: Run ninja with the `-d explain` flag. That will produce some possibly difficult to interpret output that will explain why the rebuild is happening.

**Comment by luckysmg** [comment]
Here 

https://github.com/nico/ninjatracing/issues/28

**Comment by chinmaygarde** [comment]
Some things to try:
* In the build output, check to see how many files are being recompiled. If its all of them with a message that says the some build.ninja hash was different, then you probably have multiple versions of ninja installed. Check with `which -a ninja`. I know homebrew likes to install ninja silently.
* Don't re-invoke `flutter/tools/gn` in the interim (as that will re-generate the Xcode project) but add the `-d explain` tag like @zanderso  mentioned.

**Comment by luckysmg** [comment]
1. `which -a ninja` out: `/Users/wjr/depot_tools/ninja` is install by depot tools
2. Yes. I recomplie the engine with invoking `flutter/tools/gn` every time..... **Now I just invoke it only when needed. And it works fine😄.** 

Emm but I invoked it every time when using Xcode13.....But I don't know why Xcode 14 will mark them dirty🤔.............

**Comment by vashworth** [comment]
I have the same issue. It sometimes recompiles a bunch of files and sometimes only a few, even though I've only been working in one file.

Command I run: `./flutter/tools/gn --no-goma --ios --simulator --unoptimized --simulator-cpu=arm64 && ninja -C out/ios_debug_sim_unopt_arm64`

File I've been editing: https://github.com/flutter/engine/blob/main/shell/platform/darwin/ios/framework/Source/FlutterViewController.mm

Easy solution/ninjatracing:
[trace.txt](https://github.com/flutter/flutter/files/9973460/trace.txt)
Btw: When I generated this, it had recompiled 2309 files.

Running `which -a ninja` returns: `/Users/vashworth/Development/depot_tools/ninja`

Xcode version 14.0.1

**Comment by chinmaygarde** [comment]
From the traces, it looks like a full invalidation of either the host or target tools.
<img width="1840" alt="Screenshot 2022-11-09 at 10 09 37 AM" src="https://user-images.githubusercontent.com/44085/200907850-7bdf41f9-930a-4741-bc32-ffb2952e1491.png">
Can you ask Ninja for an explanation via the `-d explain` flag? The instructions on how to do this and view the results in Xcode are:
<img width="1840" alt="Screenshot 2022-11-09 at 10 17 14 AM" src="https://user-images.githubusercontent.com/44085/200909769-1a63b605-d0b3-44b3-b82c-aaa76a98dde1.png">
<img width="1840" alt="Screenshot 2022-11-09 at 10 16 31 AM" src="https://user-images.githubusercontent.com/44085/200909811-cb4e4c1c-1ed5-4149-ba19-0b35c63b2867.png">
Beware that the build steps will be re-generated after each Ninja run so you'll need to add the flag again.

If you see this outside of Xcode, you can add the -d explain on the command line manually.

**Comment by vashworth** [comment]
I ran outside of Xcode in the terminal
[explain.txt](https://github.com/flutter/flutter/files/9974672/explain.txt)

**Comment by jmagman** [comment]
> If you see this outside of Xcode, you can add the -d explain on the command line manually.

@chinmaygarde Not sure if those logs help, it thinks everything is dirty but doesn't explain why...
```
ninja explain: command line changed for clang_arm64/obj/third_party/flatbuffers/grpc/src/compiler/flatc.cpp_generator.o
ninja explain: clang_arm64/obj/third_party/flatbuffers/grpc/src/compiler/flatc.cpp_generator.o is dirty
ninja explain: command line changed for clang_arm64/obj/third_party/flatbuffers/grpc/src/compiler/flatc.go_generator.o
ninja explain: clang_arm64/obj/third_party/flatbuffers/grpc/src/compiler/flatc.go_generator.o is dirty
```

**Comment by zanderso** [comment]
Does Xcode do any sort of indexing that might be updating file access timestamps? Updating file timestamps could confuse ninja.

**Comment by zanderso** [comment]
cc @yjbanov @nbayati

**Comment by dkwingsmt** [comment]
I've managed to make `ninja` print the commands that are changed. It turns out they're using different XCode SDK versions:
```
Before: /Users/tongmu/goma/gomacc  ../../buildtools/mac-x64/clang/bin/clang++ -MD -MF obj/out/host_debug_unopt/gen/flutter/fml/_fl_fml_fixtures._fl__fl_fml_fixtures.o.d -DUSE_OPENSSL=1 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_FORTIFY_SOURCE=2 -D_LIBCPP_DISABLE_AVAILABILITY=1 -D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS -D_DEBUG -I../.. -Igen -I../../third_party/libcxx/include -I../../third_party/libcxxabi/include -I../../build/secondary/third_party/libcxx/config -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.sdk -mmacosx-version-min=10.14.0 -fno-strict-aliasing -fstack-protector-all -arch x86_64 -fcolor-diagnostics -Wall -Wextra -Wendif-labels -Werror -Wno-missing-field-initializers -Wno-unused-parameter -Wno-unused-but-set-parameter -Wno-unused-but-set-variable -Wno-implicit-int-float-conversion -Wno-c99-designator -Wno-deprecated-copy -Wno-psabi -Wno-unqualified-std-cast-call -Wno-non-c-typedef-for-linkage -Wno-range-loop-construct -Wunguarded-availability -Wno-deprecated-declarations -fvisibility=hidden -stdlib=libc++ -Wstring-conversion -Wnewline-eof -O0 -g2 -fvisibility-inlines-hidden -std=c++17 -fno-rtti -nostdinc++ -nostdinc++ -fvisibility=hidden -fno-exceptions  -c gen/flutter/fml/_fl__fl_fml_fixtures.cc -o obj/out/host_debug_unopt/gen/flutter/fml/_fl_fml_fixtures._fl__fl_fml_fixtures.o
Currnt: /Users/tongmu/goma/gomacc  ../../buildtools/mac-x64/clang/bin/clang++ -MD -MF obj/out/host_debug_unopt/gen/flutter/fml/_fl_fml_fixtures._fl__fl_fml_fixtures.o.d -DUSE_OPENSSL=1 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_FORTIFY_SOURCE=2 -D_LIBCPP_DISABLE_AVAILABILITY=1 -D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS -D_DEBUG -I../.. -Igen -I../../third_party/libcxx/include -I../../third_party/libcxxabi/include -I../../build/secondary/third_party/libcxx/config -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk -mmacosx-version-min=10.14.0 -fno-strict-aliasing -fstack-protector-all -arch x86_64 -fcolor-diagnostics -Wall -Wextra -Wendif-labels -Werror -Wno-missing-field-initializers -Wno-unused-parameter -Wno-unused-but-set-parameter -Wno-unused-but-set-variable -Wno-implicit-int-float-conversion -Wno-c99-designator -Wno-deprecated-copy -Wno-psabi -Wno-unqualified-std-cast-call -Wno-non-c-typedef-for-linkage -Wno-range-loop-construct -Wunguarded-availability -Wno-deprecated-declarations -fvisibility=hidden -stdlib=libc++ -Wstring-conversion -Wnewline-eof -O0 -g2 -fvisibility-inlines-hidden -std=c++17 -fno-rtti -nostdinc++ -nostdinc++ -fvisibility=hidden -fno-exceptions  -c gen/flutter/fml/_fl__fl_fml_fixtures.cc -o obj/out/host_debug_unopt/gen/flutter/fml/_fl_fml_fixtures._fl__fl_fml_fixtures.o
```

**Comment by dkwingsmt** [comment]
**Temporary solution:** Go to `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/` and remove all SDKs but the latest one. (For debugging purposes, I renamed them instead of removing.)

Although it'd be better to check out why `gn` would cause a different SDK version to be chosen.

**Comment by jmagman** [comment]
In Xcode 13.4 it doesn't have the symlink without the minor version:
```
drwxr-xr-x  7 m  primarygroup  224 May 27  2022 MacOSX.sdk
lrwxr-xr-x  1 m  primarygroup   10 May 27  2022 MacOSX12.3.sdk -> MacOSX.sdk
```
In Xcode 14 I see macOS 12 and 12.3 but they are both symlinked to the same directory.
```
drwxr-xr-x  7 m  primarygroup  224 Sep 20 14:34 MacOSX.sdk
lrwxr-xr-x  1 m  primarygroup   10 Sep 20 14:34 MacOSX12.3.sdk -> MacOSX.sdk
lrwxr-xr-x  1 m  primarygroup   10 Sep 20 14:34 MacOSX12.sdk -> MacOSX.sdk
```
In Xcode 14.1 beta 3 (the newest one I have installed) it's 13 and 13.0:
```
drwxr-xr-x  7 m  primarygroup  224 Oct  4 15:31 MacOSX.sdk
lrwxr-xr-x  1 m  primarygroup   10 Oct  4 15:30 MacOSX13.0.sdk -> MacOSX.sdk
lrwxr-xr-x  1 m  primarygroup   10 Oct  4 15:30 MacOSX13.sdk -> MacOSX.sdk
```

on that version:
```
$ cd src/build/mac
$ python find_sdk.py --print_sdk_path 10.14
/Users/m/Applications/Xcode-14-1_beta3.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.0.sdk
13.0
```
which is correct.  I wonder why that command would be thrashing between different versions...

Maybe there's a bug in the `best_sdk` logic and it's not stably returning the newest
https://github.com/flutter/buildroot/blob/d8c99053ab3ea5aa8560a453462566229a812ea7/build/mac/find_sdk.py#L73-L74
https://github.com/flutter/buildroot/blob/d8c99053ab3ea5aa8560a453462566229a812ea7/build/mac/find_sdk.py#L26-L28

**Comment by jmagman** [comment]
Yup, even running that `find_sdk.py` back-to-back it's swapping between `MacOSX13.sdk` and `MacOSX13.0.sdk`.

`xcodebuild -showsdks -json` is returning the same `sdkVersion` and `canonicalName` for different `sdkPath`s:
```
  {
    "canonicalName" : "macosx13.0",
...
    "sdkPath" : "/Users/magder/Applications/Xcode-14-1_beta3.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.sdk",
    "sdkVersion" : "13.0"
  },
  {
    "canonicalName" : "macosx13.0",
...
    "sdkPath" : "/Users/magder/Applications/Xcode-14-1_beta3.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.0.sdk",
    "sdkVersion" : "13.0"
  },
```
and the order isn't stable, so it keeps swapping which path is last.

**Comment by jmagman** [comment]
Great investigation @dkwingsmt!  PR out at https://github.com/flutter/buildroot/pull/652.  Would you be able to re-add the old symlink and confirm that PR fixes the issue for you?  

Or @luckysmg or @vashworth may be able to validate that fix?

**Comment by dkwingsmt** [comment]
I placed the symlink back and can verify I have not met this issue any more for now. :)

**Comment by jmagman** [comment]
Buildroot roll at https://github.com/flutter/engine/pull/37991

**Comment by luckysmg** [comment]
Very Thanks @jmagman for working on this (*^▽^*)

**Comment by jmagman** [comment]
And thanks @dkwingsmt for cracking the case!
