### ISSUE TITLE
Card rounded corners should be modifiable.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#11298]
The [Card](https://docs.flutter.io/flutter/material/Card-class.html) widget has a small rounded corner and an elevation. This causes a physical model layer to be introduced in the scene builder. 

Physical model layers are expensive to render because they cause render target switches. There are optimizations in place where these switches can be avoided if the card does not render any shadow or if the rounded corner radii are zero.

In the card, the shadow can be disabled by changing the elevation to zero. However, there is no way to change the corner radii. Applications tend to use cards even when they don't need to and change to elevation to zero. However, because of the presence of rounded corner the optimization in the physical model layer cannot be applied.

Using the [checkboardOffscreenLayers](https://docs.flutter.io/flutter/rendering/RenderPerformanceOverlay/checkerboardOffscreenLayers.html) diagnostic option makes it extremely obvious which parts of the view hierarchy are causing expensive switches. But because the card is not configurable, the only available option for the developer to fix performance issues in the cards is to not use them at all (instead of intelligently switching the same based on use case).

**Comment by Hixie** [comment]
It's not clear why one would use a card at all if it has zero elevation? Isn't that just a Material at that point?

**Comment by SebastiaandenBoer** [comment]
As per Material guidelines, one should not omit rounded corners of cards as they are specifically mentioned not to be tiles. If the implementation requires a card-like structure (as in square and divided), there are numerous other possibilities such as `Material`, `Container` and others. Perhaps this is what you're looking for?

**Comment by Hixie** [comment]
Card takes arbitrary shapes now.
