### ISSUE TITLE
Get error when run flutter app on android 

### ISSUE THREAD

**Issue by mohamedbasha275** [flutter/flutter#112956]
- **Problem**
When trying to run the app it's failed
- **Error**

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkReleaseDuplicateClasses'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
   > Duplicate class com.google.android.exoplayer2.ui.DownloadNotificationHelper found in modules jetified-exoplayer-core-2.18.1-runtime (com.google.android.exopla
yer:exoplayer-core:2.18.1) and jetified-exoplayer-ui-2.12.3-runtime (com.google.android.exoplayer:exoplayer-ui:2.12.3)
     Duplicate class com.google.android.exoplayer2.ui.package-info found in modules jetified-exoplayer-common-2.18.1-runtime (com.google.android.exoplayer:exoplaye
r-common:2.18.1) and jetified-exoplayer-ui-2.12.3-runtime (com.google.android.exoplayer:exoplayer-ui:2.12.3)

     Go to the documentation to learn how to <a href="d.android.com/r/tools/classpath-sync-errors">Fix dependency resolution errors</a>.

### Pubspec File 
environment:
  sdk: ">=2.17.5 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.3
  http: ^0.13.4
  shared_preferences: ^2.0.15
  font_awesome_flutter: ^10.1.0
  change_app_package_name: ^1.1.0
  carousel_slider: ^4.1.1
  pusher_channels_flutter: ^2.0.1
  intl: ^0.17.0
  vimeo_video_player: ^0.0.4 #make problem with zoom
  #vimeo_player_flutter: ^0.0.3+2
  awesome_dialog: ^3.0.2
  flutter_zoom_sdk: ^1.1.0+4`

### Notes:
The  problem happens when using `vimeo_video_player` with  `flutter_zoom_sdk` if don't use  `vimeo_video_player` the app works right

**Comment by darshankawar** [comment]
> The problem happens when using `vimeo_video_player` with `flutter_zoom_sdk` if don't use `vimeo_video_player` the app works right

`vimo_video_player` is a third party plugin so I think you will need to report this in dedicated repo: https://github.com/prahack/vimeo_player/issues

Closing from here. If you think this issue is due to framework, write in comments and I'll reopen it.
