### ISSUE TITLE
Flutter benchmark dashboard does not clearly indicate what configuration each benchmark is running

### ISSUE THREAD

**Issue by rmacnak-google** [flutter/flutter#11299]
E.g., no benchmark indicates whether it is running debug, profile or release. Most benchmarks do not indicate whether they are running on Android, iOS or a desktop OS. No benchmark indicate what hardware (e.g., Nexus 5X) it is running on. The dashboard also does not provide a link to the benchmark source.

**Comment by iapicca** [comment]
Hi @rmacnak-google is this issue still meant to be open?

**Comment by rmacnak-google** [comment]
Yes, this issue has not been addressed.

**Comment by Hixie** [comment]
I believe this is moot now that we use skiaperf.
