### ISSUE TITLE
Flutter Engine for Flutter version < 3.3.0 cannot be Built Because Fuchsia libcxx Repository Got Removed

### ISSUE THREAD

**Issue by SSW-SCIENTIFIC** [flutter/flutter#112919]
## Steps to Reproduce

1. Try to build any version of Flutter Engine older than flutter/engine@43883a6850ea4fc2678871ac0b0dfe88fcf40601 (I think this covers all of version < 3.3.0 releases).

## Logs

<details>
<summary>Logs</summary>

This log is from Bitbake, and tried to build flutter/engine@caaafc5604ee9172293eb84a381be6aadd660317.

```
src/third_party/libcxx (ERROR)
----------------------------------------
[0:02:11] Started.
_____ src/third_party/libcxx at 7524ef50093a376f334a62a7e5cebf5d238d4c99

________ running 'git init --bare /workdir/download/gn/https__github.com_flutter_engine.git/src/third_party/_gclient_gittmp_libcxxepH2pD' in '/workdir/download/gn/https__github.com_flutter_engine.git'

[0:02:11] hint: Using 'master' as the name for the initial branch. This default branch name
[0:02:11] hint: is subject to change. To configure the initial branch name to use in all
[0:02:11] hint: of your new repositories, which will suppress this warning, call:
[0:02:11] hint: 
[0:02:11] hint:         git config --global init.defaultBranch <name>
[0:02:11] hint: 
[0:02:11] hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
[0:02:11] hint: 'development'. The just-created branch can be renamed via this command:
[0:02:11] hint: 
[0:02:11] hint:         git branch -m <name>
[0:02:11] Initialized empty Git repository in /workdir/download/gn/https__github.com_flutter_engine.git/src/third_party/_gclient_gittmp_libcxxepH2pD/
[0:02:11] 
________ running 'git -c core.deltaBaseCacheLimit=2g clone --no-checkout --progress --verbose https://fuchsia.googlesource.com/third_party/libcxx --template=/workdir/download/gn/https__github.com_flutter_engine.git/src/third_party/_gclient_gittmp_libcxxepH2pD /workdir/download/gn/https__github.com_flutter_engine.git/src/third_party/_gclient_libcxx_BZyc9p' in '/workdir/download/gn/https__github.com_flutter_engine.git'

[0:02:11] Cloning into '/workdir/download/gn/https__github.com_flutter_engine.git/src/third_party/_gclient_libcxx_BZyc9p'...
[0:02:12] fatal: repository 'https://fuchsia.googlesource.com/third_party/libcxx/' not found
[0:02:13] 
________ running 'git -c core.deltaBaseCacheLimit=2g clone --no-checkout --progress --verbose https://fuchsia.googlesource.com/third_party/libcxx --template=/workdir/download/gn/https__github.com_flutter_engine.git/src/third_party/_gclient_gittmp_libcxxepH2pD /workdir/download/gn/https__github.com_flutter_engine.git/src/third_party/_gclient_libcxx_BZyc9p' in '/workdir/download/gn/https__github.com_flutter_engine.git' attempt 2 / 4
```

</details>

This build error is triggered by the removal of https://fuchsia.googlesource.com/third_party/libcxx, so does not affected to newer (<= 3.3.0) releases.
Is this situation (cannot build > 3.3.0 releases) expected?

Thank you.

**Comment by exaby73** [comment]
Hello @SSW-SCIENTIFIC. Thank you for filing this issue. Labelling for further insights from the team.

**Comment by fersnort** [comment]
Hi there,

Any update on this @exaby73 ?

**Comment by jwinarske** [comment]
@SSW-SCIENTIFIC If you were locked to upstream you would already have this:
https://github.com/meta-flutter/meta-flutter/blob/dunfell/recipes-graphics/flutter-engine/flutter-engine_git.bb#L139

**Comment by exaby73** [comment]
@SSW-SCIENTIFIC Please look at the [issue hygiene](https://github.com/flutter/flutter/wiki/Issue-hygiene) for information about how the team handles new issues and prioritizes them.

**Comment by HidenoriMatsubayashi** [comment]
I think all external developers building the engine are encountering this issue.

**Comment by jwinarske** [comment]
My build matrix is passing:
https://github.com/meta-flutter/meta-flutter/pull/203

There are changes beyond this issue required to build.  It's been that way since the beginning.  The easy work around to address this issue is to remove the `fuchsia` folder prior to compiling; as i referenced above.

**Comment by swift-kim** [comment]
@jwinarske Do you run `gclient sync` before your CI build? If you run the build with already fetched dependencies on your self-hosted runner, you should not have this problem.

**Comment by SSW-SCIENTIFIC** [comment]
@jwinarske 
In the Yocto build context, exactly, this issue triggers **fetch** error during `gn` fetcher execution, not compile error.

**Comment by ardera** [comment]
@jwinarske For me, the aarch64 build works OOB with the toolchain & sysroot that's bundled with the engine. I only apply some small patches to make armv7 and cpu-specific tuning work.

The error happens when fetching the sources, so before you even have a chance to delete the `fuchsia` directory

**Comment by jwinarske** [comment]
@swift-kim yes

Spec:
https://github.com/meta-flutter/meta-flutter/blob/f489eb48bc2cace17e025e27172c20546406c05a/lib/gn.py#L48

Config/Sync
https://github.com/meta-flutter/meta-flutter/blob/f489eb48bc2cace17e025e27172c20546406c05a/lib/gn.py#L67

I don't hit this problem with my config.

**Comment by HidenoriMatsubayashi** [comment]
The latest version (top of tree) seems fine. But it's reproducible on flutter **3.3.4.**

```shell
$ git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
$ export PATH=$PATH:$(pwd)/depot_tools
```

create .gclient:
```
solutions = [
  {
    "managed": False,
    "name": "src/flutter",
    "url": "https://github.com/flutter/engine.git@c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631",
    "custom_deps": {},
    "deps_file": "DEPS",
    "safesync_url": "",
    "custom_vars" : {
      "download_android_deps" : False,
      "download_windows_deps" : False,
    },
  },
]
```

```shell
$ gclient sync
```

**Comment by jwinarske** [comment]
I get a repro with this
```
gclient.py config --spec 'solutions = [
  {
    "managed": False,
    "name": "src/flutter",
    "url": "https://github.com/flutter/engine.git",
    "custom_vars" : {
      "download_android_deps" : False,
      "download_windows_deps" : False,
      "download_linux_deps" : False,
    },
  },
]'

gclient.py sync --shallow --no-history -R -D --revision c08d7d5efc9aa6eb3c30cfb3be6dc09bca5e7631 -j48 -v
```

```
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/raid10/github-ci/_work/flutter/src/third_party/libcxx'
WARNING: subprocess '"git" "-c" "core.deltaBaseCacheLimit=2g" "clone" "--no-checkout" "--progress" "--verbose" "https://fuchsia.googlesource.com/third_party/libcxx" "--template=/mnt/raid10/github-ci/_work/flutter/src/third_party/_gclient_gittmp_libcxx7_ydwaun" "/mnt/raid10/github-ci/_work/flutter/src/third_party/_gclient_libcxx_lg0e4qij"' in /mnt/raid10/github-ci/_work/flutter failed; will retry after a short nap...
```

My builds for eb6d86ee27deecba4a83536aa20f366a6044895c are passing:
```
commit eb6d86ee27deecba4a83536aa20f366a6044895c (HEAD -> stable, tag: 3.3.4, origin/stable, origin/flutter-3.2-candidate.5)
```

What method are people using to determine the commit hash?  Perhaps that's the mix-up.

**Comment by chinmaygarde** [comment]
Following up on the removal of the old upstream repo.

**Comment by SSW-SCIENTIFIC** [comment]
I think this issue has been solved by bringing back the repository https://fuchsia.googlesource.com/third_party/libcxx by #113293 .
