### ISSUE TITLE
To be able to set alignment for both directions in `SizeTransition` widget 

### ISSUE THREAD

**Issue by akshdeep-singh** [flutter/flutter#112946]
## Use case

To be able to set alignment for both directions when using `SizeTransition` widget.

Currently, alignment for only 1 direction (`axisAlignment`) can be set.

## Proposal

Expose `AlignmentDirectional` argument (having default `-1.0`) used inside `SizeTransition.build` method:
```dart
if (axis == Axis.vertical) {
  alignment = AlignmentDirectional(-1.0, axisAlignment);
} else {
  alignment = AlignmentDirectional(axisAlignment, -1.0);
}
```

**Comment by exaby73** [comment]
Hello @akshdeep-singh. Thank you for filing this request. Labelling for further insights from the team.

**Comment by goderbauer** [comment]
Can you not just wrap the `SizeTransition` in an `Align` widget to get the desired alignment there?

**Comment by akshdeep-singh** [comment]
`SizeTransition` uses `Align` widget, and the parameter can be easily exposed. Why wrap it in an extra `Align` widget?

Though it can be done, but having an `Align` widget on top of another `Align` widget, both having different alignments doesn't seems to be a good solution to me.

**Comment by goderbauer** [comment]
In Flutter we prefer composability over building every possible functionality into a single widget. Since you can achieve this by composing existing widgets, I am going to close this one.
