### ISSUE TITLE
Broken link in `android/app/build.gradle` of a new Flutter project

### ISSUE THREAD

**Issue by puf** [flutter/flutter#112983]
The `android/app/build.gradle` of a new Flutter project contains:

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.example.myapp"
        // You can update the following values to match your application needs.
        // For more information, see: https://docs.flutter.dev/deployment/android#reviewing-the-build-configuration.

The link is incorrect. The page still exists, but the anchor changed and is now: https://docs.flutter.dev/deployment/android#reviewing-the-gradle-build-configuration

**Comment by domesticmouse** [comment]
PTAL @anderdobo

**Comment by darshankawar** [comment]
Thanks for the report. Seeing same behavior upon creating new Flutter project.

**Comment by anderdobo** [comment]
Seeing the same behavior for a new Flutter project and looking forward to the WIP fix to the correctly anchored link called out by Puf.
