### ISSUE TITLE
[CP] Flutter apps crash when emojis and Korean text are combined

### ISSUE THREAD

**Issue by cyanglaz** [flutter/flutter#112963]
### issue_link

https://github.com/flutter/flutter/issues/111494

### Commit Hash

[ba1c87a](https://github.com/flutter/engine/commit/ba1c87a07cfb9ded6e2603bf1cf991b0cbabb855)

### Target

stable

### pr_link

https://github.com/flutter/engine/pull/36807

### Impacted Users

end-customers who types in Korean on iPhone running on iOS 16. Although not tested, other languages that have similar behavior might also be affected, such as Japanese.

### Impact Description

on iOS 16, app crashes when an emoji followed by multiple Korean characters combining into one. 

### Workaround

No.

### Risk

Medium

### Test Coverage

yes

### Validation Steps

1. Ensure to add Korean keyboard in the simulator or iPhone. (can be tested with iOS 16 simulator or iPhone device running on iOS 16): 
2. Launch a flutter app with the below sample code 
3. Type in an emoji in the text field
4. Type in Korean characters ㅇ ㅏ
5. Observe app crashes when ㅇ ㅏ combined.

**code sample**

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Korean Emoji Crash'),
        ),
        body: const Center(child: TextField()),
      ),
    );
  }
}
```
</details>

**Comment by itsjustkevin** [comment]
@LongCatIsLooong and @jmagman could you review this cherry-pick request?
