### ISSUE TITLE
In Swipe Away, if you swipe a card while scrolled to the bottom, the bottom card isn't pinned to the bottom

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#113]
<a href="https://github.com/Hixie"><img src="https://avatars.githubusercontent.com/u/551196?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Hixie](https://github.com/Hixie)**
_Tuesday Jul 21, 2015 at 22:26 GMT_
_Originally opened as https://github.com/flutter/engine/issues/197_

----

In Swipe Away, if you swipe a card while scrolled to the bottom, the bottom card isn't pinned to the bottom. Instead, it moves up, then moves down. It should just stay down and the top cards should move down. We are probably just not updating the scroll behaviour on each frame or something.

cc @HansMuller

**Comment by HansMuller** [comment]
No longer a bug.
