### ISSUE TITLE
Issue: 'flutter create' always creates an "test" directory with a code-error inside

### ISSUE THREAD

**Issue by regetskcob** [flutter/flutter#113018]
When I create a new project using "flutter create" there is a "test" directory created which includes a widget_test.dart. This test file contains an error just from the beginning. The only way for newbies to fix this is deleting the file or the whole test-directory, but I don't think this is the original intention of this dir.

<img width="1146" alt="Screenshot 2022-10-06 at 11 34 52" src="https://user-images.githubusercontent.com/52231719/194279332-e8e8d3f8-21cb-448c-b0cb-4504fde2af6b.png">

**Comment by DanTup** [comment]
@regetskcob it looks like there may be errors in the `lib/main.dart` file that might be related to this. Can you open the Problems view (View -> Problems) and post a screenshot of all three errors listed in there?

In `lib/main.dart` there should be code like this:

```dart
class MyApp extends StatelessWidget {
  const MyApp({super.key});
```

But I think there may be other errors in there (which may be causing this error).

**Comment by darshankawar** [comment]
@regetskcob 
Along with above comment, I am unable to replicate this after creating a new flutter proejct using latest master verson.

<img width="932" alt="Screenshot 2022-10-06 at 6 14 38 PM" src="https://user-images.githubusercontent.com/67046386/194316138-b2c7cf97-7056-44ec-945b-8ea76fe6dbc2.png">
 
Can you provide `flutter doctor -v` ?
