### ISSUE TITLE
Flutter is not accessible in my android studio set up on Windows 11

### ISSUE THREAD

**Issue by arvindkumar749** [flutter/flutter#113038]
## Steps to Reproduce

1. Flutter is in my C drive and we can normally access it on Android Studio for our Mobile Application development. But when I am trying to run the Command (flutter doctor) in Android Studio terminal, it is giving me error Access is denied to that folder in which Flutter is present.

2. My system is on Windows 11 and it is giving me error and one of my Collogues is using Windows 10 and on which there is no error.

## Logs

<details>
<summary>Logs</summary>

```
```

C:\src\flutter>flutter doctor -v
**'git rev-parse HEAD' is not recognized as an internal or external command,
operable program or batch file.
'DIR /B /O:D "C:\src\flutter\packages\flutter_tools\pubspec.yaml" "C:\src\flutter\packages\flutter_tools\pubspec.lock"' is not recognized as an internal or external command,
operable program or batch file.
[√] Flutter (Channel stable, 3.3.4, on Microsoft Windows [Version 10.0.22000.978], locale en-US)
    • Flutter version 3.3.4 on channel stable at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision eb6d86ee27 (34 hours ago), 2022-10-04 22:31:45 -0700
    • Engine revision c08d7d5efc
    • Dart version 2.18.2
    • DevTools version 2.15.0

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\arvind.kumar.saharan\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    X Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at
      https://github.com/flutter/flutter/issues.
    X Exception: null. The flutter tool cannot access the file or directory.
      Please ensure that the SDK and/or project is installed in a location that has read/write permissions for the current user.
    • #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
      #1      _throwFileSystemException (package:flutter_tools/src/base/error_handling_io.dart:820:3)
      #2      _handleWindowsException (package:flutter_tools/src/base/error_handling_io.dart:810:3)
      #3      _run (package:flutter_tools/src/base/error_handling_io.dart:582:7)
      <asynchronous suspension>
      #4      AndroidLicenseValidator.licensesAccepted (package:flutter_tools/src/android/android_workflow.dart:394:31)
      <asynchronous suspension>
      #5      AndroidLicenseValidator.validate (package:flutter_tools/src/android/android_workflow.dart:321:13)
      <asynchronous suspension>
      #6      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:24)
      <asynchronous suspension>

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Build Tools 2022 17.3.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools
    • Visual Studio Build Tools 2022 version 17.3.32901.215
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[√] IntelliJ IDEA Community Edition (version 2022.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2022.2.3
    • Flutter plugin version 70.2.5
    • Dart plugin version 222.4345.14

[√] VS Code (version 1.71.2)
    • VS Code at C:\Users\arvind.kumar.saharan\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22000.978]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 106.0.5249.103
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 106.0.1370.34

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.**

C:\src\flutter>

</details>

**Comment by arvindkumar749** [comment]
and in normal terminal, flutter doctor android licenses is giving me Access is denied error, below are the logs for the same

C:\src\flutter>flutter doctor --android-licenses
'git rev-parse HEAD' is not recognized as an internal or external command,
operable program or batch file.
'DIR /B /O:D "C:\src\flutter\packages\flutter_tools\pubspec.yaml" "C:\src\flutter\packages\flutter_tools\pubspec.lock"' is not recognized as an internal or external command,
operable program or batch file.
null. The flutter tool cannot access the file or directory.
Please ensure that the SDK and/or project is installed in a location that has read/write permissions for the current user.

C:\src\flutter>

**Comment by huycozy** [comment]
Hi @arvindkumar749 
I see there's an open issue addressing the case you described #70216
Closing this issue as a duplicate, so please follow up on it for further updates. You can leave there your comment and react an upvote to the original comment will help to raise the issue. Thank you!
