### ISSUE TITLE
[Integration Test] iOS deeplink test failed with background

### ISSUE THREAD

**Issue by ostk0069** [flutter/flutter#113017]
## Steps to Reproduce

1. write e2e test with [Integration testing](https://docs.flutter.dev/testing/integration-tests)
2. open deeplink by using [url_launcher](https://pub.dev/packages/url_launcher)

Android works what I expected but iOS doesn't.

**Expected results:** 

open deeplink with out app failed and shows the page what I want.

**Actual results:** 

open deeplink with out app failed with error:

```
[BackgroundTask] Background Task 50 ("Flutter debug task"), was created over 30 seconds ago. In applications running in the background, this creates a risk of termination. Remember to call UIApplication.endBackgroundTask(_:) for your task in a timely manner to avoid this.
```

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
analyszer does not show any errors
```

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.3, on macOS 12.5 21G72 darwin-arm, locale ja-JP)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.70.1)
[✓] Connected device (3 available)
[✓] HTTP Host Availability
```

</details>

**Comment by ostk0069** [comment]
> Can you provide a minimal code sample that shows the current behavior ?

sample code is really simple.
Also need environment to get work with [Integration testing](https://docs.flutter.dev/testing/integration-tests)

```dart
void main() {
  testWidgets('launch deeplink', (widgetTester) {
    launchUrl(Uri('deeplink which opens this app'), mode: LaunchMode.externalApplication);
    expect(find.byType(HomePage), findsOneWidget);
  });
}
```

**Comment by darshankawar** [comment]
> open deeplink with out app failed with error:

@ostk0069 A similar error has been fixed recently, https://github.com/flutter/flutter/issues/109655. So can you try the same scenario on latest master and see if you get same error or expected behavior ?

**Comment by ostk0069** [comment]
@darshankawar 
https://github.com/flutter/flutter/issues/109655 looks not similar with this.
This problem happens in iOS 15 and xcode 13.

**Comment by darshankawar** [comment]
@ostk0069
Can you provide exact steps to replicate this behavior ?
