### ISSUE TITLE
My Bag

### ISSUE THREAD

**Issue by xurshid20222** [flutter/flutter#113008]
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>

class CheckPayment extends ConsumerStatefulWidget {
  const CheckPayment({Key? key}) : super(key: key);

  @override
  ConsumerState<CheckPayment> createState() => _CheckPaymentState();
}

class _CheckPaymentState extends ConsumerState<CheckPayment> {
  @override
  Widget build(BuildContext context) => Scaffold(

    backgroundColor: AppColors.cF2F4F7,
    appBar: AppBar(
      toolbarHeight: 90,
      backgroundColor: AppColors.white,
      elevation: 0,
      leading: Row(
        mainAxisAlignment: MainAxisAlignment.start,
        crossAxisAlignment: CrossAxisAlignment.center,
        children: [
          const SizedBox(width: 24),
          GestureDetector(
            onTap: (){
              ref.read(checkVM).checkCardNumberController.clear();
              ref.read(checkVM).checkCardPaymentController.clear();
              Navigator.pop(context);

            },
            child: Container(
              height: 40,
              width: 40,
              decoration: BoxDecoration(
                border: Border.all(color: AppColors.cEAEFF3),
                borderRadius: BorderRadius.circular(10),
              ),
              child: const Center(
                child: Icon(
                  Icons.arrow_back_ios_new,
                  size: FontSize.size16,
                  color: AppColors.c33409E,
                ),
              ),
            ),
          ),
        ],
      ),
      leadingWidth: 100,
      centerTitle: true,
      title: Text(Words.checkPayment.tr(context), style: const AppTextStyle().titleMedium?.copyWith(color: AppColors.c3554D1)),
    ),
    body: Stack(
      children: [
        Padding(
          padding: const EdgeInsets.only(top: 33, ),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              //#companyImage
              Transform.translate(offset: const Offset(7, 0),
                child:  AppImages.transformUniversalBank,
              ),
              const SizedBox(height: 17,),
              Padding(
                padding: const EdgeInsets.symmetric(horizontal: 24),
                child: Text(Words.cardNumberOrPhone.tr(context), style: Theme.of(context).textTheme.labelMedium?.copyWith(color: AppColors.c12154C),),
              ),
              //#cardNumber
              const TransformCheckTextField(),
              Padding(
                padding: const EdgeInsets.symmetric(horizontal: 24),
                child: Text(Words.holloway.tr(context), style: Theme.of(context).textTheme.bodyMedium?.copyWith(fontWeight: FontWeight.w600, color: AppColors.c878B9A),),
              ),
              const SizedBox(height: 31,),
              Padding(
                padding: const EdgeInsets.symmetric(horizontal: 24),
                child: Text(Words.paySumma.tr(context), style: Theme.of(context).textTheme.labelMedium?.copyWith(color: AppColors.c12154C),),
              ),
              //#summa
              const CheckSummaTextField(),
              Padding(
                padding: const EdgeInsets.symmetric(horizontal: 24),
                child: Text.rich(
                  TextSpan(
                    text: Words.limit.tr(context),
                    style: Theme.of(context).textTheme.bodyMedium?.copyWith(fontWeight: FontWeight.w600, color: AppColors.c878B9A),
                    children:  <InlineSpan>[
                      TextSpan(
                        text: '1 000 000 000',
                        style: Theme.of(context).textTheme.bodyMedium?.copyWith(fontWeight: FontWeight.w600, color: AppColors.c878B9A),
                      ),
                    ],
                  ),
                ),
              ),
              const SizedBox(height: 60,),
              Padding(
                padding: const EdgeInsets.symmetric(horizontal: 24),
                child: Text.rich(
                  TextSpan(
                    text: Words.pressing.tr(context),
                    style: Theme.of(context).textTheme.bodySmall?.copyWith(fontWeight: FontWeight.w500, color: AppColors.black, fontSize: 12),
                    children:  <InlineSpan>[
                      TextSpan(
                        text: Words.translate.tr(context),
                        style: Theme.of(context).textTheme.bodySmall?.copyWith(fontWeight: FontWeight.w500, color: AppColors.c3554D1, fontSize: 12),
                      ),
                      TextSpan(
                        text: Words.youAgree.tr(context),
                        style: Theme.of(context).textTheme.bodySmall?.copyWith(fontWeight: FontWeight.w500, color: AppColors.black, fontSize: 12),
                      ),
                      TextSpan(
                        text: Words.publicOffer.tr(context),
                        style: Theme.of(context).textTheme.bodySmall?.copyWith(fontWeight: FontWeight.w500, color: AppColors.c3554D1, fontSize: 12,),
                      ),
                    ],
                  ),
                  textAlign: TextAlign.center,
                ),
              ),
              const SizedBox(height: 20,),
              const SelectCard(),
            ],
          ),
        ),

      ],
    ),

    resizeToAvoidBottomInset: false,
    floatingActionButton:  TransformButton(onPressed: () {
      AwesomeDialog(
        context: context,
        dialogType: DialogType.noHeader,
        headerAnimationLoop: false,
        bodyHeaderDistance: 0,
        padding:  const EdgeInsets.all(0),
        animType: AnimType.bottomSlide,
        body: const FiledDialog(),
        buttonsTextStyle: const TextStyle(color: Colors.black),
        showCloseIcon: false,
        width: double.infinity,

      ).show();
    },),
    floatingActionButtonLocation: FloatingActionButtonLocation.centerFloat,
  );
}

<summary>Code sample</summary>

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

</details>

'package:flutter/src/widgets/framework.dart': Failed assertion: line 6292 pos 12: 'child == _child': is not true.
What a problem?

**Comment by Bazni** [comment]
Hey,

Did you write `@OverRide` in your code or is it just the formatting that is broken? 
You have to write `@override`.

Can your issue be a bit better formatted?

**Comment by xurshid20222** [comment]
https://user-images.githubusercontent.com/97846891/194245031-097241a0-62a0-46ca-9300-a364d9be622c.mp4

**Comment by xurshid20222** [comment]
After going to the second page, I get this error when I go back and go again

**Comment by xurshid20222** [comment]
> Hey,
> 
> Did you write `@OverRide` in your code or is it just the formatting that is broken? You have to write `@override`.
> 
> Can your issue be a bit better formatted?

**Comment by xurshid20222** [comment]
### **I think there is a problem with the TextField

I made TextField a separate widget**

**Comment by xurshid20222** [comment]
https://user-images.githubusercontent.com/97846891/194248072-4817a276-8889-4c74-9b95-c178cb8387a5.mp4

**Comment by xurshid20222** [comment]
No it is not working. Second video was recorded that I have commented the textfield of second page so it looks like working but as soon as I put the text field to the second page and fill it with number then going back to the first page is good but again going to the second page exception is here....

**Comment by huycozy** [comment]
Hi @xurshid20222. It seems your question is best suited for support channels like StackOverflow, so please ask the same there for solutions if any.
If you are proposing a change, please use the appropriate new issue template and fill out the requested details so that we can address this issue properly.

Closing for now.

**Comment by xurshid20222** [comment]
thank you for your advice
