### ISSUE TITLE
Text selection toolbars don't render correctly on iOS simulators

### ISSUE THREAD

**Issue by xster** [flutter/flutter#11302]
On head, text selection toolbars look like:
![screen shot 2017-07-19 at 1 26 47 pm](https://user-images.githubusercontent.com/156888/28388694-6ccaaa7c-6c88-11e7-9dea-ee5a2eeb6e60.png)

Works ok on iOS and Android physical devices.

**Comment by eseidelGoogle** [comment]
Is it just the extra addition of the floating card?  Or is that card supposed to be rendered but at a different size/location?

**Comment by xster** [comment]
Text is missing vs device
![select](https://user-images.githubusercontent.com/156888/28390195-e6e276c8-6c8d-11e7-829f-07250eb8fc11.png)

**Comment by xster** [comment]
Was likely a skia issue but not on head anymore.
