### ISSUE TITLE
Run Integration Performance Benchmark with Firebase Test Lab

### ISSUE THREAD

**Issue by simeuth** [flutter/flutter#113085]
Hello team, I just want to confirm something, currently, I'm working on a benchmark tooling for our flutter app,  and I found this https://docs.flutter.dev/cookbook/testing/integration/profiling, we want to run our benchmark with Firebase Test Lab. is that possible? 

I've read this as well (https://github.com/flutter/flutter/tree/main/packages/integration_test#using-flutter-driver-to-run-tests), but I found no clue on where we set the flutter driver when we run it with Firebase Test Lab

**Comment by preyalameta02** [comment]
yes it is possible

**Comment by huycozy** [comment]
>but I found no clue on where we set the flutter driver when we run it with Firebase Test Lab

@simeuth Do you mean setting to run specific test file? It's supported with `-Ptarget=<path_to_test>.dart`, let's see: https://github.com/flutter/flutter/tree/main/packages/integration_test#firebase-test-lab

**Comment by simeuth** [comment]
@huycozy yes i know if i want to run a specific test we can use `-Ptarget`, but if the test needs to be run with test driver. where do i attach the driver?  

for some context if i run it with on device directly
```
flutter drive \
  --driver=test_driver/integration_test.dart \
  --target=integration_test/foo_test.dart
```

**Comment by huycozy** [comment]
>yes it is possible

@preyalameta02 Could you please share more details?

>I've read this as well (https://github.com/flutter/flutter/tree/main/packages/integration_test#using-flutter-driver-to-run-tests), but I found no clue on where we set the flutter driver when we run it with Firebase Test Lab

@simeuth It seems `flutter driver` doesn't support running on Firebase Test Lab currently. Please see: https://issuetracker.google.com/issues/115927909?pli=1

**Comment by simeuth** [comment]
nice catch there @huycozy, so it seems not supported yet yah,
and for alternative, we think of another solution to build our own device farm.

oh yah any detail for that @preyalameta02?
