### ISSUE TITLE
[CP] Cherry pick "fixes FadeInImage for an edge case"

### ISSUE THREAD

**Issue by chunhtai** [flutter/flutter#113036]
### issue_link

https://github.com/flutter/flutter/issues/111011

### Commit Hash

165cb0b9862cd4fece21bd9e8621dd981fa28242

### Target

stable

### pr_link

https://github.com/flutter/flutter/pull/113035

### Impacted Users

end-customers

### Impact Description

App crashes when using FadeInImage

### Workaround

No

### Risk

low

### Test Coverage

yes

### Validation Steps

unit tests

**Comment by HansMuller** [comment]
LGTM
