### ISSUE TITLE
Flutter benchmark dashboard should run benchmarks in release mode

### ISSUE THREAD

**Issue by rmacnak-google** [flutter/flutter#11300]
The performance of release mode is ultimate what counts. We hope that any performance regression that happens in release mode will also be reflected in profile mode, but that might not always happen. There may also be regressions that only affect profile mode, since profile mode enables developer tools that are not enabled in release mode.

**Comment by rmacnak-google** [comment]
See also https://github.com/flutter/flutter/issues/10998 for the specific case of memory.

**Comment by Hixie** [comment]
We also care about performance regressions in debug mode. And profile mode, for that matter. Test all the modes!

**Comment by iapicca** [comment]
hi @rmacnak-google is this issue still meant to be open?

**Comment by rmacnak-google** [comment]
Yes, this issue has not been addressed.

**Comment by exaby73** [comment]
Hello @rmacnak-google. Is this issue still reproducible?

**Comment by exaby73** [comment]
Re-opening this issue and marking it as a proposal

**Comment by Hixie** [comment]
I'm going to close this one on the basis that we have a bunch of tests in various modes now, and it's impractical for us to run more tests arbitrarily.
