### ISSUE TITLE
url_launcher iOS App Store link don't work

### ISSUE THREAD

**Issue by blue492** [flutter/flutter#113013]
Hi, I am using url_launcher in my flutter app to open an app in iOS App Store, in ios device
Url: https://apps.apple.com/se/app/instagram/id389801252 

I enabled `mode: LaunchMode.externalNonBrowserApplication`  to launch the app directly in App Store, it worked before but not now.
launchUrl return false
The same function works well in Android devices but not in iOS

```
 if (await canLaunchUrl(Uri.parse(url))) {
      if(externalNonBrowserApplication == true){ 
        await launchUrl(Uri.parse(url), mode: LaunchMode.externalNonBrowserApplication);
      }
      else {
        await launchUrl(Uri.parse(url)); 
      }
    } else {
      print('Could not launch $url');
    }
```

Flutter version: 3.3.4
url_launcher: 6.1.6
iOS: 16

**Comment by Gayathri-GA** [comment]
@blue492  you can give a try with this package
[external_app_launcher](https://pub.dev/packages/external_app_launcher)

**Comment by huycozy** [comment]
@blue492 I can not reproduce this issue from my side, you can try this completed sample code and confirm it's working as expected.

<details>
<summary>Sample code</summary>

```dart
import 'package:flutter/material.dart';
import 'package:url_launcher/url_launcher.dart';

final Uri _url = Uri.parse('https://apps.apple.com/se/app/instagram/id389801252');

void main() => runApp(
  const MaterialApp(
    home: Material(
      child: Center(
        child: ElevatedButton(
          onPressed: _launchUrl,
          child: Text('Show Flutter homepage'),
        ),
      ),
    ),
  ),
);

Future<void> _launchUrl() async {
  if (!await launchUrl(_url)) {
    throw 'Could not launch $_url';
  }
}
```
</details>

**Comment by blue492** [comment]
@huycozy did you tried in iOS 16 device with externalNonBrowserApplication = true? when clicked did you get instagram app in Apple Store?

**Comment by huycozy** [comment]
@blue492 I don't have a physical device (iOS 16). I test on iOS 15.7, it opened AppStore (Instagram app). Do you run above sample code on your device?

**Comment by blue492** [comment]
@huycozy did you tried in ios 16 device? 

> @blue492 I don't have a physical device (iOS 16). I test on iOS 15.7, it opened AppStore (Instagram app). Do you run above sample code on your device?

Yes I did, it same problem. My code above worked well on iOS 15.7 but not in iOS 16

**Comment by huycozy** [comment]
> Try to run it on ios 16 simulator device, what you get?

@blue492 The simulator does not have AppStore, so this won't work. https://developer.apple.com/forums/thread/16361
Did you try it on a physical device that has iOS 16?

**Comment by blue492** [comment]
> > Try to run it on ios 16 simulator device, what you get?
> 
> @blue492 The simulator does not have AppStore, so this won't work. https://developer.apple.com/forums/thread/16361 Did you try it on a physical device that has iOS 16?

@huycozy Yes I tried on a physical device that has iOS 16

**Comment by blue492** [comment]
I solved the issue by adding externalApplication 

`await launchUrl(Uri.parse(url), mode: LaunchMode.externalApplication);`
