### ISSUE TITLE
[CP] Wait for non-empty layout in platform view placeholder

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#113041]
### issue_link

https://github.com/flutter/flutter/issues/111255

### Commit Hash

5c38125

### Target

stable

### pr_link

https://github.com/flutter/flutter/pull/113040

### Impacted Users

Apps trying to use platform views in deferred-layout scenarios

### Impact Description

Throws an assertion error, and the platform view never appears.

### Workaround

Requires changing layout to prevent having a transient empty size, which can be non-trivial.

### Risk

low

### Test Coverage

yes

### Validation Steps

Run the sample in https://github.com/flutter/flutter/issues/111255. The webview should appear.

**Comment by itsjustkevin** [comment]
@mossmana could you take a look at this cherry-pick request?

**Comment by itsjustkevin** [comment]
@justinmc could you review this cherry-pick?

**Comment by justinmc** [comment]
I just LGTM'ed the PR.  Looks low-risk and worthy of cherry pick, though I'm no platform view expert.
