### ISSUE TITLE
Last list item in stocks list shouldn't have a row under it

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#1130]
Either the last list item in stocks list shouldn't have a row under it, or the first one should have a row above it. Not sure which, but either way it's inconsistent right now and that makes it ugly. (Most obvious in the PORTFOLIO pane.)

**Comment by abarth** [comment]
Maybe the MaterialList should custom paint the lines?  Then it could draw them in between the items.  Currently we the items themselves paint the lines and they don't know if they're first or last.

**Comment by Hixie** [comment]
This is moot these days.
