### ISSUE TITLE
MediaQuery.of(context).size value return is not same after rotation

### ISSUE THREAD

**Issue by fooshen-chong** [flutter/flutter#113096]
## Steps to Reproduce
 
`MediaQuery.of(context).size` value return is not the same after rotated.

**Expected results:**
` MediaQuery.of(context).size.height` during portrait mode should be the same with ` MediaQuery.of(context).size.width` in landscape mode

**Actual results:**
value is different (783 vs 807), I'm not sure if im missing out anything because in Ipad both value is same but in tested in Android `Pixel 3a API 33 arm64` the value is different.

<details>
<summary>Code sample</summary>
Attached with minimal reproducible sample :

```
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(
        title: 'Logical height',
      ),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: Stack(
      children: [
        Align(
          alignment: Alignment.centerRight,
          child: Container(
            width: 20,
            height: MediaQuery.of(context).size.height,
            color: Colors.red,
            child: RotatedBox(
              quarterTurns: 3,
              child: Center(
                  child: Text(
                      'logical pixel : ${MediaQuery.of(context).size.height}')),
            ),
          ),
        ),
        Align(
          alignment: Alignment.bottomCenter,
          child: Container(
              height: 20,
              width: MediaQuery.of(context).size.width,
              color: Colors.green,
              child: Center(
                  child: Text(
                      'logical pixel : ${MediaQuery.of(context).size.width}'))),
        ),
      ],
    ));
  }
}

```

</details>

<img width="495" alt="Screenshot 2022-10-07 at 7 31 11 PM" src="https://user-images.githubusercontent.com/74953833/194543450-7b5fe370-2125-4b9d-aed3-a3ddda5dc74a.png">

<img width="894" alt="Screenshot 2022-10-07 at 7 31 28 PM" src="https://user-images.githubusercontent.com/74953833/194543488-09cf3434-a7ae-41ab-a8f8-201cf301a7eb.png">

**Comment by exaby73** [comment]
Hello @fooshen-chong. This is happening because the bottom navigation bar is taking up space. This is working as expected. Closing this issue for the same reason.
