### ISSUE TITLE
I have an issue while building macos app in M1 chip macbook. And so I cannot build app...

### ISSUE THREAD

**Issue by Lazizbek97** [flutter/flutter#113011]
when i run flutter build macos, result: 
`--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:macOS, arch:arm64, id:00008103-000805CA1A30801E }
{ platform:macOS, arch:x86_64, id:00008103-000805CA1A30801E }
warning: Run script build phase 'Run Script' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'Runner' from project 'Runner')`

I have attached images so that my issue will be more clear. Thanks.
![Screen Shot 2022-10-06 at 12 09 30](https://user-images.githubusercontent.com/91660256/194238963-533c2d42-8d65-420d-9169-56256739e275.png)
![Screen Shot 2022-10-06 at 12 08 32](https://user-images.githubusercontent.com/91660256/194239024-d2702ae5-a638-44cd-b1af-e416c4850591.png)

As you can see in picture, there is no issue for 'flutter doctor -v'

**Comment by Lazizbek97** [comment]
No didn't (

**Comment by danagbemava-nc** [comment]
Hi @Lazizbek97, please provide the output of `flutter doctor -v` as well as the full output of `flutter build macos -v`. The output of this may be huge, so kindly put it into a .txt or .log file and attach it here. 

Please do not provide screenshots of logs or flutter doctor -v. Provide those outputs in properly formatted text. 

Thank you

**Comment by Lazizbek97** [comment]
`lazizbekfayziev@Lazizbeks-MacBook-Air billz_cashier_desktop % flutter doctor -v
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.6 21G115 darwin-arm, locale en-UZ)
    • Flutter version 3.0.5 at /Users/lazizbekfayziev/dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (3 months ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/lazizbekfayziev/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.71.2)
    • VS Code at /Users/lazizbekfayziev/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.6 21G115 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 106.0.5249.103

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!`

flutter build macos -v: 
[flutter build macos -v.txt](https://github.com/flutter/flutter/files/9724872/flutter.build.macos.-v.txt)

**Comment by danagbemava-nc** [comment]
Hi @Lazizbek97, your logs show that the project built successfully. 

Is your issue the warning you see when the build starts? Or is it something else?

**Comment by Lazizbek97** [comment]
While i run flutter build macos -v, it shows successful build message. But if i run just flutter build macos, it shows warning and stop building. 

In both cases, after build complete,  there's not new built app in "Build" folder.

**Comment by danagbemava-nc** [comment]
Hi @Lazizbek97, kindly upgrade to the latest version of flutter to see if you still experience this issue. If you do, please provide the updated output of `flutter doctor -v`. The latest version of stable is 3.3.4. Please also provide the verbose logs of you building the app on the new stable version. 

Thank you
