### ISSUE TITLE
Run the Scenario app tests on an iOS simulator on arm64

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#113056]
@jmagman @cyanglaz fyi

We want to have better coverage of running on a simulator on iOS, since this is a common development mode for engineers particularly at Google.

We'd also like to run these tests with Impeller enabled to make sure it works there.

**Comment by jmagman** [comment]
@dnfield you did this with https://github.com/flutter/engine/pull/41141, right?

**Comment by dnfield** [comment]
Yes
