### ISSUE TITLE
../../third_party/dart/runtime/vm/message_snapshot.cc: 576: error: expected: !lib.IsNull()

### ISSUE THREAD

**Issue by dmitry-fbm** [flutter/flutter#113183]
## Steps to Reproduce

This is reappearance of #111804. Cannot reproduce it myself but see multiple crash logs in Google Console:
```
Thread ../../third_party/dart/runtime/vm/message_snapshot.cc: 576: error: expected: !lib.IsNull()
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
pid: 0, tid: 0 >>> com.mycompany.myapp <<<

backtrace:
  #00  pc 0x000000000008bebc  /apex/com.android.runtime/lib64/bionic/libc.so (abort+168)
  #01  pc 0x0000000000696484  /data/app/~~YYVrKi2b6tz_bO39I7G8iQ==/com.mycompany.myapp-gYw3hOvUTePiI5ouHC12Sw==/split_config.arm64_v8a.apk!libflutter.so
  #02  pc 0x00000000006ea7bc  /data/app/~~YYVrKi2b6tz_bO39I7G8iQ==/com.mycompany.myapp-gYw3hOvUTePiI5ouHC12Sw==/split_config.arm64_v8a.apk!libflutter.so
  #03  pc 0x00000000006eefc0  /data/app/~~YYVrKi2b6tz_bO39I7G8iQ==/com.mycompany.myapp-gYw3hOvUTePiI5ouHC12Sw==/split_config.arm64_v8a.apk!libflutter.so
  #04  pc 0x00000000006d7a84  /data/app/~~YYVrKi2b6tz_bO39I7G8iQ==/com.mycompany.myapp-gYw3hOvUTePiI5ouHC12Sw==/split_config.arm64_v8a.apk!libflutter.so
  #05  pc 0x00000000006dde88  /data/app/~~YYVrKi2b6tz_bO39I7G8iQ==/com.mycompany.myapp-gYw3hOvUTePiI5ouHC12Sw==/split_config.arm64_v8a.apk!libflutter.so
  #06  pc 0x00000000005b3e4c  /data/app/~~YYVrKi2b6tz_bO39I7G8iQ==/com.mycompany.myapp-gYw3hOvUTePiI5ouHC12Sw==/split_config.arm64_v8a.apk!libflutter.so
  #07  pc 0x000000000068d918  /data/app/~~YYVrKi2b6tz_bO39I7G8iQ==/com.mycompany.myapp-gYw3hOvUTePiI5ouHC12Sw==/split_config.arm64_v8a.apk!libflutter.so
  #08  pc 0x00000000003460cc  /data/app/~~YYVrKi2b6tz_bO39I7G8iQ==/com.mycompany.myapp-gYw3hOvUTePiI5ouHC12Sw==/split_config.arm64_v8a.apk!libflutter.so
  #09  pc 0x0000000000349658  /data/app/~~YYVrKi2b6tz_bO39I7G8iQ==/com.mycompany.myapp-gYw3hOvUTePiI5ouHC12Sw==/split_config.arm64_v8a.apk!libflutter.so
  #10  pc 0x0000000000018184  /system/lib64/libutils.so (android::Looper::pollInner(int)+916)
  #11  pc 0x0000000000017d84  /system/lib64/libutils.so (android::Looper::pollOnce(int, int*, int*, void**)+116)
  #12  pc 0x0000000000017510  /system/lib64/libandroid.so (ALooper_pollOnce+104)
  #13  pc 0x0000000000349764  /data/app/~~YYVrKi2b6tz_bO39I7G8iQ==/com.mycompany.myapp-gYw3hOvUTePiI5ouHC12Sw==/split_config.arm64_v8a.apk!libflutter.so
  #14  pc 0x0000000000347d8c  /data/app/~~YYVrKi2b6tz_bO39I7G8iQ==/com.mycompany.myapp-gYw3hOvUTePiI5ouHC12Sw==/split_config.arm64_v8a.apk!libflutter.so
  #15  pc 0x00000000000f1194  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+264)
  #16  pc 0x000000000008d7f0  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+68)
```

Started after upgrade to Flutter 3.3.3.

**Comment by darshankawar** [comment]
@dmitry-fbm 
From the logs, it looks similar to https://github.com/flutter/flutter/issues/109248 which was fixed at dart side and most probably be available in latest master version. Is there a way for you to confirm this by switching to latest master and see if you still get same error log or not ?

**Comment by dmitry-fbm** [comment]
> Is there a way for you to confirm this by switching to latest master and see if you still get same error log or not ?
@darshankawar hello, so far it appeared only in production apps which I wouldn't risk to switch to master. If however you can give me the steps to reproduce it locally I can test in both stable and master branches. 
____
Is there an estimation when the change may go live? So far few other critical issues said fixed in master (for instance, #110631, #111382) never been included in hotfixes.

**Comment by darshankawar** [comment]
> Is there an estimation when the change may go live? So far few other critical issues said fixed in master (for instance, #110631, #111382) never been included in hotfixes.

Usually, if the fix is a low-risk to be cherry-picked, then it is considered as a candidate for hotfixes. You may read about it here: https://github.com/flutter/flutter/wiki/Hotfixes-to-the-Stable-Channel

> If however you can give me the steps to reproduce it locally I can test in both stable and master branches.

I think based on the error log you shared earlier, it will be difficult to know the exact steps to replicate the crash, but since it matches with https://github.com/flutter/flutter/issues/109248, it has the steps / video that shows the error, so you may probably try the same at your end and confirm.

**Comment by dmitry-fbm** [comment]
@darshankawar Yea I'm afraid there is not a lot of info in #109248 to reproduce it locally. We don't do any downloads; our use of `IsolateNameServer` is very different and most of the time doesn't cause problems. In our case the issue is intermittent, relatively small percentage of users face it - our dev team in particular neither could reproduce it in debug nor release builds.

**Comment by darshankawar** [comment]
@flutter-symbolizer-bot https://github.com/flutter/flutter/issues/113183#issue-1402250606 flutter#v3.3.3 force android release arm64

**Comment by darshankawar** [comment]
Based on above logs, keeping this issue open and labeling for further insights from the team.

**Comment by mraleph** [comment]
Without knowing what exactly your code is doing with isolates it is hard to guess what exactly is going wrong. As https://github.com/flutter/flutter/issues/109248#issuecomment-1215822688 explains you might need to put `@pragma('vm:entry-point')` at classes which you are sending between isolates.

**Comment by chinmaygarde** [comment]
@mraleph Are the situation in which entrypoint annotations are necessary documented? Also, is it possible to emulate the failures due to missing entrypoint annotations in debug modes. As it stands, it may be too easy to run into these errors and also hard to trace where the error was made.

**Comment by mraleph** [comment]
@chinmaygarde the rule of thumb is that you need this annotation whenever you look a program entity (a library, a class or a member) reflectively by its name. This occurs in two cases: when Flutter engine looks something up by name through Dart VM's C API or when sending messages across isolate group boundaries. 

I think there are currently two different use cases where Flutter developers need to be aware about `@pragma('vm:entry-point')`. 

1. When embedding Flutter engine and using API like [`-runWithEntrypoint`](https://api.flutter.dev/objcdoc/Classes/FlutterEngine.html#/c:objc(cs)FlutterEngine(im)runWithEntrypoint:). 
2. When working with _callback handles_ ([PluginUtilities.getCallbackHandle](https://api.flutter.dev/flutter/dart-ui/PluginUtilities/getCallbackHandle.html)). 

The first case is already documented. The documentation for the second case is missing AFAICS. To make the second case more bullet-proof we can add more strict checking into the API to make it an early error to call `getCallbackHandle` on a function not annotated with the pragma entry-point.

The assertion which the user is hitting here is neither the first or the second case. I think it is a consequence of a bug which @rmacnak-google has fixed in https://github.com/dart-lang/sdk/commit/b3a569ea8d3ef39a9982076f34107638fe867d20. 

If you have two isolates A and B two situations are possible: 

1. A & B belong to the same group => almost any object (with few special exceptions) can be sent between these two groups.
2. A & B belong to different groups => only builtin types can be sent and this will be verified on the sender side.

Before @rmacnak-google's fix the sender accidentally skipped the verification while doing the cross isolate group send leading to the crash on the receiving side. This crash can be "plastered over" by the entry-point pragma so that receiving side can deserialise the message, but on the main branch sender will actually get a rejection when trying to send. 

This brings me to the question. Users seem to expect that they can send arbitrary objects between two different isolate groups, but this is not going to work on the main branch. Is it actually by design that there are multiple isolate groups running in some cases or it is accidental? I would assume that most (if not all) Flutter applications ship with a single AOT snapshot so creating multiple isolate groups only makes sense if you need multiple threads of execution running without GC interference.

**Comment by champeauxr** [comment]
@mraleph I'm seeing this issue when sending a map containing a list via a `SendPort`/`ReceivePort` across isolates in different flutter engines.

If I send this map using `SendPort.send()`, it works fine.
```
{
   "sendPort": SendPort,
   "table":"profiles",
   "command":"insertMany",
   "values": {
      "uniqueId": "[rc22@email.com](mailto:rc22@email.com)",
      "firstName":"Rich",
      "lastName":"Champeaux",
      "dateOfBirth":104400000,
      "active":0,
      "isDependent":0,
      "startedEmancipation":0,
      "isEmancipated":0,
      "locale":"en-US",
      "analyticsConsent":null,
      "thirdPartyConsentFirebase":null,
      "dhpConsent":"consent"
   }
}
```

however, if I send this message, it crashes with the `!lib.IsNull()` assertion:

```
{
   "sendPort": SendPort,
   "table":"profiles",
   "command":"insertMany",
   "values": [
      {
         "uniqueId": "[rc22@email.com](mailto:rc22@email.com)",
         "firstName":"Rich",
         "lastName":"Champeaux",
         "dateOfBirth":104400000,
         "active":0,
         "isDependent":0,
         "startedEmancipation":0,
         "isEmancipated":0,
         "locale":"en-US",
         "analyticsConsent":null,
         "thirdPartyConsentFirebase":null,
         "dhpConsent":"consent"
      }
   ]
}
```

The only difference between these two maps is that the `values` entry in the one that crashes is a list containing a map, while it is just the map in the one that succeeds.

There's nothing for me to annotate with `@pragma('vm:entry-point')`

**Comment by dmitry-fbm** [comment]
Let me clarify few things:
* Our use of isolates is very limited, the most of it is done by external libs. Quick search through the code points out to firebase libs and flutter_local_notifications.
* There is just one place in our code where `@pragma('vm:entry-point')` could be reasonably added; it's already there and never helped.
* As been written before, the issue is intermittent with relatively small number of users affected - which suggests that the code itself is likely fine but there are some yet unknown circumstances where flutter (or dart) fails - like specific OS flavor, hardware or data payload.

**Comment by mraleph** [comment]
@champeauxr That's unexpected. Is it deterministic? How do you construct the data you send (e.g. just a bunch of lists and maps?) What's your Flutter version (output of `flutter doctor -v` would be helpful). 

You message also seems to contain `"sendPort": SendPort,`. Is it intentional that you are sending a `SendPort` type literal here?

Do you build your application with default flags or do you use things like `--obfuscate` and `--split-debug-info`?

@dmitry-fbm newer versions of Flutter are going to report a much more informative message instead of `!lib.IsNull()` so hopefully that can shed light on this, given that the problem is intermittent.

**Comment by champeauxr** [comment]
@mraleph I'm using Flutter 3.3.4. We're upgrading from 3.0.2 and it works fine on that version. Here's the `flutter --version` output:

> Flutter 3.3.4 • channel stable • https://github.com/flutter/flutter.git
> Framework • revision eb6d86ee27 (2 weeks ago) • 2022-10-04 22:31:45 -0700
> Engine • revision c08d7d5efc
> Tools • Dart 2.18.2 • DevTools 2.15.0

Yes, it is very deterministic. If right before the `SendPort.send()`, I replace the list from the "values" member in the map with the first item in the list, it succeeds. Something like this:
```
message['values'] = message['values'][0]
```

If I let the list go through, it crashes. The debugger says the actual type of the list is `_GrowableList`.

We have an isolate created in a separate `FlutterEngine` from the main app engine. The code in main app engine gets a `SendPort` for a service running on that isolate using the `IsolateNameServer` and we use it to send messages containing commands to be run. The caller creates a `RecievePort` to receive a response from the service and in the message is a `SendPort` for that `ReceivePort` that the service sends the response to.

The commands are essentially database type commands, such as `query`, `insert`, `insertMany`, etc. The "values" parameter in the message is a list of entities that were already transformed into maps using the `toJson` method generated by the `freezed` package.

The list of entities comes to this code as an `Iterable<Map<String, Object?>>` and is converted to a list using the `toList()` method:

```
  @override
  Future<int> insertMany(
      String table, Iterable<Map<String, Object?>> values) async {
    return await service.sendCommand(
        table, 'insertMany', <String, dynamic>{
      'values': values.toList(),
    });
  }
```

The `sendCommand` method creates the message and sends it as follows:
```
        final message = <String, dynamic>{
          'sendPort': receivePort.sendPort,
          'table': table,
          'command': command,
          ...arguments,
        };

        sendPort.send(message);
```

The service isolate subscribes to it's `ReceivePort` as follows:
```
    _streamSubscription = _receivePort.asyncMap(_handleMessage).listen((_) {});
```

For my debugging, I print the `message` object just before calling `sendPort.send()` in my `sendCommand` method in the main isolate and I also print the `message` object as the first action in my `_handleMessage` method in the service isolate. When things succeed, I will see both message objects printed. However, if the "values" memeber is a list I see the message printed from `sendCommand()`, but then a crash and I never see the message received in `_handleMesssage()`.
> 2022-10-19 10:05:30.327 4065-4122/? I/flutter: *********************** sendCommand: {sendPort: SendPort, table: profiles, command: insertMany, values: [{uniqueId: rc22@email.com, firstName: Rich, lastName: Champeaux, dateOfBirth: 104400000, active: 0, isDependent: 0, startedEmancipation: 0, isEmancipated: 0, locale: en-US, analyticsConsent: null, thirdPartyConsentFirebase: null, dhpConsent: consent}]}
> 2022-10-19 10:05:30.328 4065-4164/? E/Dart: ../../third_party/dart/runtime/vm/message_snapshot.cc: 576: error: expected: !lib.IsNull()
>     --------- beginning of crash

But, if I replace the "values" list with just the first item (which is a map), like this:
```
        if (table == "profiles" && command == "insertMany") {
          message['values'] = message['values'][0];
        }
        print("*********************** sendCommand: $message");
        sendPort.send(message);
```

Then the message makes it through the `ReceivePort` to the `_handleMessage` method and gets printed:

> 2022-10-19 10:17:43.769 5435-5496/? I/flutter: *********************** sendCommand: {sendPort: SendPort, table: profiles, command: insertMany, values: {uniqueId: rc22@email.com, firstName: Rich, lastName: Champeaux, dateOfBirth: 104400000, active: 0, isDependent: 0, startedEmancipation: 0, isEmancipated: 0, locale: en-US, analyticsConsent: null, thirdPartyConsentFirebase: null, dhpConsent: consent}}
> 2022-10-19 10:17:43.770 5435-5540/? I/flutter: *********************** _handleMessage: {sendPort: SendPort, table: profiles, command: insertMany, values: {uniqueId: rc22@email.com, firstName: Rich, lastName: Champeaux, dateOfBirth: 104400000, active: 0, isDependent: 0, startedEmancipation: 0, isEmancipated: 0, locale: en-US, analyticsConsent: null, thirdPartyConsentFirebase: null, dhpConsent: consent}}

If we use a `FlutterEngineGroup` and all of our engines are created using the same engine group, then this particular call of `sendCommand` works. However, we also use the `workmanager` package, which creates it's own `FlutterEngine` that is not part of our engine group and will still cause the app to crash when the "values" member in the message is a list.

**Comment by mraleph** [comment]
@champeauxr I think I figured out what is happening based on your code. Thanks! It's a bit obscure, added a [comment](https://github.com/dart-lang/sdk/issues/50243#issuecomment-1285164523) to address this problem. Could you check if the crash goes away if you do `List.of(values)` rather than `values.toList()` in `insertMany`?

**Comment by champeauxr** [comment]
@mraleph Yes, using `List.of()` instead of `toList()` resolves the issue for me. Thank you!

**Comment by dmitry-fbm** [comment]
Hello gentlemen. This is getting P0 priority to me - and I believe to everyone else who use FCM. Recent stats show over 9% (!!!) of sessions ended up with crash. Not 100% sure but looks like upgrade to 3.3.6 made it even worse - while nothing in release notes is related. Please prioritize this fix - as far as I can see there are some solutions offered in #113825.

**Comment by hoangdat** [comment]
We have the problem:
```
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
pid: 0, tid: 0 >>> com.linagora.android.teammail <<<

backtrace:
  #00  pc 0x0000000000450654  /vendor/lib64/egl/libGLESv2_samsung.so
  #01  pc 0x00000000003fc560  /vendor/lib64/egl/libGLESv2_samsung.so
  #02  pc 0x00000000003fee08  /vendor/lib64/egl/libGLESv2_samsung.so
  #03  pc 0x00000000003feff4  /vendor/lib64/egl/libGLESv2_samsung.so
  #04  pc 0x0000000000400ae4  /vendor/lib64/egl/libGLESv2_samsung.so
  #05  pc 0x00000000002af870  /vendor/lib64/egl/libGLESv2_samsung.so
  #06  pc 0x000000000024c9c8  /vendor/lib64/egl/libGLESv2_samsung.so (GL_DrawElementsInstanced+264)
  #07  pc 0x000000000053a458  /data/app/~~tPy0o3WtFr_tyW9cPADPqg==/com.linagora.android.teammail-rT04wFvq0qwKcwcTr8NRXA==/split_config.arm64_v8a.apk!libflutter.so
  #08  pc 0x0000000000509e94  /data/app/~~tPy0o3WtFr_tyW9cPADPqg==/com.linagora.android.teammail-rT04wFvq0qwKcwcTr8NRXA==/split_config.arm64_v8a.apk!libflutter.so
  #09  pc 0x0000000000506ddc  /data/app/~~tPy0o3WtFr_tyW9cPADPqg==/com.linagora.android.teammail-rT04wFvq0qwKcwcTr8NRXA==/split_config.arm64_v8a.apk!libflutter.so
  #10  pc 0x0000000000504774  /data/app/~~tPy0o3WtFr_tyW9cPADPqg==/com.linagora.android.teammail-rT04wFvq0qwKcwcTr8NRXA==/split_config.arm64_v8a.apk!libflutter.so
  #11  pc 0x00000000004f2778  /data/app/~~tPy0o3WtFr_tyW9cPADPqg==/com.linagora.android.teammail-rT04wFvq0qwKcwcTr8NRXA==/split_config.arm64_v8a.apk!libflutter.so
  #12  pc 0x00000000004ae7ec  /data/app/~~tPy0o3WtFr_tyW9cPADPqg==/com.linagora.android.teammail-rT04wFvq0qwKcwcTr8NRXA==/split_config.arm64_v8a.apk!libflutter.so
  #13  pc 0x00000000004af1dc  /data/app/~~tPy0o3WtFr_tyW9cPADPqg==/com.linagora.android.teammail-rT04wFvq0qwKcwcTr8NRXA==/split_config.arm64_v8a.apk!libflutter.so
  #14  pc 0x00000000003ca18c  /data/app/~~tPy0o3WtFr_tyW9cPADPqg==/com.linagora.android.teammail-rT04wFvq0qwKcwcTr8NRXA==/split_config.arm64_v8a.apk!libflutter.so
  #15  pc 0x0000000000644394  /data/app/~~tPy0o3WtFr_tyW9cPADPqg==/com.linagora.android.teammail-rT04wFvq0qwKcwcTr8NRXA==/split_config.arm64_v8a.apk!libflutter.so
  #16  pc 0x000000000056dcc0  /data/app/~~tPy0o3WtFr_tyW9cPADPqg==/com.linagora.android.teammail-rT04wFvq0qwKcwcTr8NRXA==/split_config.arm64_v8a.apk!libflutter.so
  #17  pc 0x000000000056dcf8  /data/app/~~tPy0o3WtFr_tyW9cPADPqg==/com.linagora.android.teammail-rT04wFvq0qwKcwcTr8NRXA==/split_config.arm64_v8a.apk!libflutter.so
  #18  pc 0x000000000057cf54  /data/app/~~tPy0o3WtFr_tyW9cPADPqg==/com.linagora.android.teammail-rT04wFvq0qwKcwcTr8NRXA==/split_config.arm64_v8a.apk!libflutter.so
  #19  pc 0x000000000057caa8  /data/app/~~tPy0o3WtFr_tyW9cPADPqg==/com.linagora.android.teammail-rT04wFvq0qwKcwcTr8NRXA==/split_config.arm64_v8a.apk!libflutter.so
  #20  pc 0x0000000000586a38  /data/app/~~tPy0o3WtFr_tyW9cPADPqg==/com.linagora.android.teammail-rT04wFvq0qwKcwcTr8NRXA==/split_config.arm64_v8a.apk!libflutter.so
  #21  pc 0x00000000003173a4  /data/app/~~tPy0o3WtFr_tyW9cPADPqg==/com.linagora.android.teammail-rT04wFvq0qwKcwcTr8NRXA==/split_config.arm64_v8a.apk!libflutter.so
  #22  pc 0x000000000031a994  /data/app/~~tPy0o3WtFr_tyW9cPADPqg==/com.linagora.android.teammail-rT04wFvq0qwKcwcTr8NRXA==/split_config.arm64_v8a.apk!libflutter.so
  #23  pc 0x0000000000016918  /system/lib64/libutils.so (android::Looper::pollInner(int)+912)
  #24  pc 0x0000000000016520  /system/lib64/libutils.so (android::Looper::pollOnce(int, int*, int*, void**)+112)
  #25  pc 0x0000000000017160  /system/lib64/libandroid.so (ALooper_pollOnce+100)
  #26  pc 0x000000000031aaa4  /data/app/~~tPy0o3WtFr_tyW9cPADPqg==/com.linagora.android.teammail-rT04wFvq0qwKcwcTr8NRXA==/split_config.arm64_v8a.apk!libflutter.so
  #27  pc 0x00000000003190d8  /data/app/~~tPy0o3WtFr_tyW9cPADPqg==/com.linagora.android.teammail-rT04wFvq0qwKcwcTr8NRXA==/split_config.arm64_v8a.apk!libflutter.so
  #28  pc 0x00000000000b3020  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+264)
  #29  pc 0x000000000005288c  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64)
```
with SDK:
```
Flutter 3.0.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision fb57da5f94 • 2022-05-19 15:50:29 -0700
Engine • revision caaafc5604
Tools • Dart 2.17.1 • DevTools 2.12.2
```

**Comment by mraleph** [comment]
@hoangdat file a separate issue please, this has nothing to do with this one.

**Comment by jamesdixon** [comment]
I agree with @dmitry-fbm -- we use isolates in our app and we can't go past 3.0.5 due to this issue. If this is truly fixed in `master`, any idea when we might see a release?

**Comment by mkustermann** [comment]
Flutter releases ~ quarterly on stable channel, so it may take some time until the next release.

@jamesdixon Could you check whether this if fixed for you on master channel (switch via: `flutter channel master`)?

**Comment by moda20** [comment]
Hi i am still on flutter 3.3.10 and i am having this issue with release build for android. Is this fixed in a stable version ? 
Also @mraleph the move from `.toList()` to `list.of()` miraculously fixed the issue for now.

**Comment by mraleph** [comment]
@moda20 if changing `toList` to `List.of` fixes this issue then this is an instance of https://github.com/dart-lang/sdk/issues/50243#issuecomment-1285164523 which is fixed in the next stable release (so should be fixed on beta now).

**Comment by marcoheine** [comment]
I have the same error.

On debug mode everything works, but on release mode the app crash.

I get this error in Google Play Console:

Android 9 (SDK 28)
Samsung XCover 4
Flutter 3.0.5

../../third_party/dart/runtime/vm/message_snapshot.cc: 576: error: expected: !lib.IsNull()

pid: 0, tid: 20459 >>> de.xxx.xxx<<<

backtrace:
#00 pc 0x000000000001cf76 /system/lib/libc.so (abort+58)
https://github.com/flutter/flutter/pull/1 pc 0x0000000000da4857 /data/app/de.xxx.xxx-Q9ZGG4Pd-ePqhoPmNirEOA==/split_config.armeabi_v7a.apk

**Comment by dmitry-fbm** [comment]
UPD: the bug is gone after update to Flutter 2.3.9. Note that we applied all the tricks suggested here too, but none helped before the update.

**Comment by mraleph** [comment]
I am then going to optimistically close it and hope that some combination of fixes that we did in various parts has managed to squash it.
