### ISSUE TITLE
Tool should throw when trying to get a gen snapshot path without target platform

### ISSUE THREAD

**Issue by xster** [flutter/flutter#11312]
getArtifactPath has an optional `platform`. Can lead to bugs like https://github.com/flutter/flutter/pull/11263#issuecomment-316553712 where `build flx` tries to resolve the snapshotter path into a non existent directory https://github.com/flutter/flutter/blame/master/packages/flutter_tools/lib/src/flx.dart#L43

**Comment by zoechi** [comment]
Is this still relevant? 
Looks like a lot has changed here.

**Comment by BondarenkoStas** [comment]
Is this still relevant?

**Comment by zanderso** [comment]
This appears to have been addressed.
