### ISSUE TITLE
Convert flutter ios project to swift 5.0 by default autmatically

### ISSUE THREAD

**Issue by Ghazanfarrajpoot** [flutter/flutter#113122]
we currently have to do it manually and it's not efficient considering it would be much better if enabled by default, also make the flutter project atleast xcode 12 compatible by default not the old version 8

**Comment by stuartmorgan** [comment]
The Swift version in the template has been 5.0 for the last three years (https://github.com/flutter/flutter/pull/41882, https://github.com/flutter/flutter/pull/44324). Could you elaborate on what you want to be using 5 that isn't?

> also make the flutter project atleast xcode 12 compatible by default not the old version 8

What problem are you trying to solve with this proposal? (Note that it's currently 9, not 8, in the template).

**Comment by Ghazanfarrajpoot** [comment]
i have xcode 13 installed on macbook 2013 pro, while archiving the app, it says would you like to switch to swift 5.

**Comment by stuartmorgan** [comment]
If you have a project that predates the update to the template, you'll need to update it yourself; it's not something we can do automatically without risking breaking products. Any new projects are already using the modern default. (Note that this is exactly the same behavior you'd get making a project in Xcode itself, where the defaults are set when you create the project.)

Closing as there's no further work on the Flutter side here.
