### ISSUE TITLE
Huawei harmonyOS system frame loss is very serious

### ISSUE THREAD

**Issue by WangYiOS** [flutter/flutter#113152]
Simple list scrolling on Huawei harmonyOS system with severe frame drop. Please, the authorities, pay attention.

Please use Huawei harmonyOS system, test a simple scrolling list, you will know how serious the frame jitter

===============

flutter开发的app,在华为harmonyOS手机上失帧抖动非常严重！！！请官方人员重视啊。

**Comment by au-top** [comment]
我是 hm2.0 没有发现这个问题
我的环境和设备
```
 • FRL AN00a (mobile) • EYDNW20A27001031 • android-arm64  • Android 10 (API 29)

Flutter (Channel master, 3.4.0-34.0.pre.8, on Microsoft Windows [版本 10.0.22621.521], locale zh-CN)
    • Flutter version 3.4.0-34.0.pre.8 on channel master at D:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5c522996be (9 days ago), 2022-09-29 13:04:19 +0800
    • Engine revision c003042e52
    • Dart version 2.19.0 (build 2.19.0-252.0.dev)
    • DevTools version 2.17.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn
```

**Comment by stuartmorgan** [comment]
HarmonyOS isn't one of Flutter's supported platforms. If there are issues with its ability to run Android applications well, you'd need to report that to the OS developers.
