### ISSUE TITLE
Netlify shows Page Not Found error with Flutter apps using GoRouter

### ISSUE THREAD

**Issue by masteradit** [flutter/flutter#113140]
I have created an app using Flutter v3, and I am using GoRouter to handle all the routes. When I run the app on localhost, everything is working fine. But when I try to go to `/signIn` page after uploading it to Netlify, it shows a "Page Not Found" error.

URL: https://63406985ec088a30cd8c9de8--allmity-beta.netlify.app/

When you open the above URL, you will automatically be redirected to https://63406985ec088a30cd8c9de8--allmity-beta.netlify.app/signIn.

But when you go to https://63406985ec088a30cd8c9de8--allmity-beta.netlify.app/signIn directly, it will show the error.

**Comment by masteradit** [comment]
Here's the output of `flutter doctor -v`:

```terminal
[✓] Flutter (Channel stable, 3.3.4, on macOS 12.6 21G115 darwin-arm, locale
    en-IN)
    • Flutter version 3.3.4 on channel stable at
      /Users/aditluhadia/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision eb6d86ee27 (3 days ago), 2022-10-04 22:31:45 -0700
    • Engine revision c08d7d5efc
    • Dart version 2.18.2
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/aditluhadia/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.72.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (3 available)
    • iPhone 14 Pro Max (mobile) • C51FD84A-1762-4E8E-940A-BDDED47D3D5A • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-16-0 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-arm64   • macOS 12.6 21G115 darwin-arm
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 105.0.5195.125

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

**Comment by mohsinhijazee** [comment]
> I have created an app using Flutter v3, and I am using GoRouter to handle all the routes. When I run the app on localhost, everything is working fine. But when I try to go to `/signIn` page after uploading it to Netlify, it shows a "Page Not Found" error.
> 
> URL: https://63406985ec088a30cd8c9de8--allmity-beta.netlify.app/
> 
> When you open the above URL, you will automatically be redirected to https://63406985ec088a30cd8c9de8--allmity-beta.netlify.app/signIn.
> 
> But when you go to https://63406985ec088a30cd8c9de8--allmity-beta.netlify.app/signIn directly, it will show the error.

Basically, Flutter web app is a SPA and all the "routing" happens in the code (in memory) so it's not that one can directly go to a certain page. I'm not sure how it would be working on local setup, maybe development tooling makes some adjustments but otherwise, I would expect it to behave the same as the routes aren't files on the file system that any CDN/web server can serve from there.

**Comment by huycozy** [comment]
@mohsinhijazee 
Did you try another hosting (such as Firebase hosting)? Or does the issue only happen with Netlify? Also, which `go_router` version are you using?

Please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this. Thank you!

**Comment by mohsinhijazee** [comment]
@huycozy hey thanks for the response. I don't think it's a bug. That's how SPAs behave.

**Comment by huycozy** [comment]
>That's how SPAs behave.

@mohsinhijazee I'm not sure about this without verifying it by a sample code. Can you try building your web app in another hosting to confirm?

**Comment by masteradit** [comment]
Sorry for the delayed response. I am outside right now, I will share a completed and minimal reproducible code sample once I reach home.

**Comment by masteradit** [comment]
I was able to fix the error by adding a 200 redirect rule in `netlify.toml` file to redirect all requests to `/`.

Here's a helpful resource: https://www.netlify.com/blog/2019/01/16/redirect-rules-for-all-how-to-configure-redirects-for-your-static-site/
