### ISSUE TITLE
Widget catalog seems to be missing DropdownButton?

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#11319]
I don't see [DropdownButton](https://docs.flutter.io/flutter/material/DropdownButton-class.html) anywhere in https://flutter.io/widgets/ ?

**Comment by mit-mit** [comment]
cc @sethladd

**Comment by sethladd** [comment]
Thanks for the report!

If someone is interested, this is the file to update: https://github.com/flutter/website/blob/master/_data/catalog/widgets.json

**Comment by zoechi** [comment]
Issue moved to [flutter/website #1855](https://github.com/flutter/website/issues/1855) via [**ZenHub**](https://www.zenhub.com/)
