### ISSUE TITLE
Performance problem, iPhone 14 Pro

### ISSUE THREAD

**Issue by marcinFDT** [flutter/flutter#113111]
Hi, I tried to check performance on iPhone 14 Pro with flutter app, but there is an FPS dropdown to 45-55FPS from time to time on that simple app attached below. I just scroll down through the items, with standard scroll speed. I thought it might be a problem with ListView so I switched it to SliverFixedExtentList where the size of the tile is known, but the same result. Sometimes frame needs 47ms to render
It's very similar to my problem https://stackoverflow.com/questions/69797486/flutter-random-slowdowns

 https://gist.github.com/marcinFDT/f08bfbea9aa543df39519e90cb75b4a0

**Target Platform:** iOS
**Target OS version/browser:** iOS 16.0.2
**Devices:** iPhone 14 Pro

## Logs
<img width="560" alt="Zrzut ekranu 2022-10-7 o 19 50 34" src="https://user-images.githubusercontent.com/105284552/194619306-4dae633a-0c5b-4578-955d-e5daa966714a.png">

[dart_devtools_2022-10-07_19_46_49.735.json.zip](https://github.com/flutter/flutter/files/9736122/dart_devtools_2022-10-07_19_46_49.735.json.zip)

<!--
     flutter analyze  
Analyzing performance_app...                                            
No issues found! (ran in 1.3s)

flutter doctor -v

[✓] Flutter (Channel master, 3.5.0-3.0.pre.11, on macOS 12.6 21G115 darwin-arm64, locale pl-PL)
    • Flutter version 3.5.0-3.0.pre.11 on channel master at /Users/marcin/Desktop/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f36b9c5b28 (2 hours ago), 2022-10-07 12:02:24 -0400
    • Engine revision 7de65af6f8
    • Dart version 2.19.0 (build 2.19.0-288.0.dev)
    • DevTools version 2.18.0

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/marcin/Library/Android/sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] Connected device (3 available)
    • iPhone (Marcin)  (mobile) • 00008120-000A04210AEB401E • ios            • iOS 16.0.2 20A380
    • macOS (desktop)           • macos                     • darwin-arm64   • macOS 12.6 21G115 darwin-arm64
    • Chrome (web)              • chrome                    • web-javascript • Google Chrome 105.0.5195.125
    ! Error: Apple Watch (Marcin) needs to connect to determine its availability. Check the connection between the device and its companion iPhone, and the connection
      between the iPhone and Xcode. Both devices may also need to be restarted and unlocked. (code 1)

[✓] HTTP Host Availability
    • All required HTTP hosts are available

**Comment by huycozy** [comment]
Hi @marcinFDT, could you specify something below?

- Does this issue happen on lower iOS versions or different devices? 
- Which Flutter channel are you testing? 
- Could you retry on the latest master channel to see if the issue still reproduces?

Please provide the output of `flutter doctor -v` as well. Thank you!

**Comment by huycozy** [comment]
Hi @marcinFDT, could you specify some points below?

- Does this issue happen on lower iOS versions or different devices? 
- Which Flutter channel are you testing? 
- Could you retry on the latest master channel to see if the issue still reproduces?

Please provide the output of `flutter doctor -v` as well. Thank you!

**Comment by huycozy** [comment]
Hi @marcinFDT, please help to clarify the issue in more detail:

- Does this issue happen on lower iOS versions or different devices?
- Which Flutter channel are you testing?
- Could you retry on the latest master channel to see if the issue still reproduces?

Please provide the output of flutter doctor -v as well. Thank you!

**Comment by marcinFDT** [comment]
Hey!

1. I tested that code also on Samsung A53 5G and the FPS was around 100-120 no bigger fps drops, so it was working pretty good and much better than iPhone (it's not as expensive a phone as iPhone 14 Pro)

I tested it on IP XS Max and it also had fps drops, but not as big as on IP 14 Pro. (IP 14 Pro supports frames up to 120, XS up to 60fps, so I guess that is the difference). But still that simple list should work perfectly on iOS devices, it's just a text list, nothing crazy :P 

What is interesting, on Android I had an fps drop for like one frame. On iOS, those drops are for like 20/30 next frames.  I'll attach an image from that Samsung phone so you can compare it to that previous screenshot

![Zrzut ekranu 2022-10-10 o 16 08 33](https://user-images.githubusercontent.com/105284552/194885411-591bd2c0-35fe-459b-b2d9-0817b8818f03.png)

I'm using flutter commercially for more than 2 years, and there was always a problem with stable performance on iOS devices, especially that bouncing animation when you are at the end/start of the scrollable list.

Unfortunately, I didn't do tests on the earlier iOS version. It will take me a lot of time to install iOS 15 but as far as I remember scroll was never that smooth with Flutter, especially when that bouncing animation comes.  I was a Swift Developer so I could easily compare that native performance with Flutter.

2. Profile mode 

3. I was testing that on the latest master 
 
4.
flutter doctor -v
[✓] Flutter (Channel master, 3.5.0-3.0.pre.11, on macOS 12.6 21G115
    darwin-arm64, locale pl-PL)
    • Flutter version 3.5.0-3.0.pre.11 on channel master at
      /Users/marcin/Desktop/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f36b9c5b28 (3 days ago), 2022-10-07 12:02:24 -0400
    • Engine revision 7de65af6f8
    • Dart version 2.19.0 (build 2.19.0-288.0.dev)
    • DevTools version 2.18.0

[✓] Android toolchain - develop for Android devices (Android SDK version
    32.1.0-rc1)
    • Android SDK at /Users/marcin/Library/Android/sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.13+0-b1751.21-8125866)

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.6 21G115 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 105.0.5195.125

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Comment by huycozy** [comment]
>Unfortunately, I didn't do tests on the earlier iOS version. It will take me a lot of time to install iOS 15 but as far as I remember scroll was never that smooth with Flutter, especially when that bouncing animation comes. 

@marcinFDT Could you take a look at issue #103847 and check if it's similar to this issue? There are also some reports of this issue on iOS 16.0.

**Comment by marcinFDT** [comment]
@huycozy 
Yup, it looks exactly like my problem. So I guess we can close my ticket and be focused and the first one. 
Thanks ;)

**Comment by huycozy** [comment]
@marcinFDT 
Yes, please follow up on it for further updates and leave there your comment/investigation or react an upvote to the original comment will help to raise the issue. 
Closing this issue as a duplicate. Thank you!
