### ISSUE TITLE
Material Page transition will draw outside of the navigator

### ISSUE THREAD

**Issue by chunhtai** [flutter/flutter#113130]
## Steps to Reproduce

```dart
import 'package:flutter/material.dart';

final GlobalKey<NavigatorState> key = GlobalKey<NavigatorState>();
void main() => runApp(MaterialApp(
  home: Row(
    children: [
      Container(width: 100, color: Colors.red,),
      Container(width: 100 ,child: Navigator(
        key: key,
        onGenerateRoute: (RouteSettings settings) {
          return MaterialPageRoute<void>(builder: (_) {
            return Scaffold(
              appBar: AppBar(title: Text(settings.name?? '')),
              body: ElevatedButton(
                child: Text(settings.name ?? ''),
                onPressed: () {
                  key.currentState!.pushNamed('/a');
                },
              ),
            );
          });
        },
      ))
    ]
  ),
));
```

1. press the button and the page transition will move outside of the navigator container.

## Logs

<details>
<summary>Logs</summary>

```
```

```
```

</details>

**Comment by chunhtai** [comment]
I would like to add on that this breaks most of the Nest navigation+navigationRail use case

**Comment by chunhtai** [comment]
internal test failure revert-> https://github.com/flutter/flutter/pull/114442

**Comment by dnfield** [comment]
Internal customer expects their custom nagivator usage to not clip. The patch as written adds a clip where there did not used to be one, which clipped off shadows and looked bad.

We can give them an escape hatch by adding `Clip clipBehavior` to `Navigator`, which would get passed on to `Overlay`s, and the internal customer could choose `Clip.none` to maintain previous behavior. Once they get opted in, we can reland #113770
