### ISSUE TITLE
How chrome extensions be enabled when flutter web debugging?

### ISSUE THREAD

**Issue by hosseinkhojany** [flutter/flutter#113186]
It's a huge problem for everybody. I can't even test any WEB3 apps, because metamask is also not possible to use. I think google did it purposely.

**Comment by darshankawar** [comment]
@hosseinkhojany 
Please check [this](https://github.com/flutter/flutter/issues/43809) issue and [this](https://stackoverflow.com/questions/67958169/how-chrome-extensions-be-enabled-when-flutter-web-debugging) StackOverflow link for your reference.
Closing from here.

**Comment by hosseinkhojany** [comment]
why you closed man!

**Comment by hosseinkhojany** [comment]
Why does the extension destroy the flutter?

**Comment by darshankawar** [comment]
@hosseinkhojany 
If you are looking to have this feature added to web framework, please file a new issue using feature request template and fill out requested details. 
Thanks.

**Comment by hosseinkhojany** [comment]
Why are you everywhere, man? >ــ<
firebase_messaging
flutter  
xyz..
