### ISSUE TITLE
[go_router] Add a way to easily retrieve parameters from router location

### ISSUE THREAD

**Issue by ronw98** [flutter/flutter#113100]
## Use case
Let's say I have a tab view that is using route parameters to know which tab it's on:
`/home/tab1`
`/home/tab2`

1. On either tab1 or tab2 I want to push a TabPage but land on the tab if TabPage is popped. If I go to this page from tab2 I need to do something like
`router.go(/home/tab2/tabPage)`

It is relatively easy because when I call `router.go` I know which tab the app is on.

2. I now add a Tab2SubPage with the following route: `/home/:tab/tabPage/tabSubPage`

I no longer have the information on which tab I initially clicked when going to TabPage. The only way to push the route I want
`router.go(/home/tab2/tabPage/tabSubPage)` is to parse the current location (`/home/tab2/tabPage`), before navigating to the new page, to retrieve the initial tab.

## Proposal
In this case it would be nice to have access to either the router state with the params or, even better, have a method `Map<String, dynamic> paramsForRoute(String route)`. In step 2 of the use case I would just have to do
```dart
final initialTab = router.paramsForRoute('/home/:tab');
router.go('/home/$initialTab/tabPage/tabSubPage');
```

**Comment by exaby73** [comment]
Hello @ronw98. Why not use [`GoRouterState.params`](https://pub.dev/documentation/go_router/latest/go_router/GoRouterState/params.html)? You can access the params that way from the [`GoRoute.builder`](https://pub.dev/documentation/go_router/latest/go_router/GoRoute/builder.html) property's `state` argument and pass it down your widget tree or use a state management solution like provider to access the param anywhere in your widget tree.
