### ISSUE TITLE
FLUTTER WEB - Error: FormatException: Unexpected extension byte (at offset 0)

### ISSUE THREAD

**Issue by NikGrmek** [flutter/flutter#113180]
Hey Everyone! I've been struggling with this error for past few days, and I can't seem to find any useful answers online, so any help would be much appreciated!

I'm working with Flutter Web, and I am using [universal_io](https://pub.dev/packages/universal_io) package due to dart:io not being supported on the web. With help of an [Image](https://pub.dev/packages/image) package I am converting selected image from Jpg to Png and am trying to convert recieved **Unit8List** of an converted image to an **File variable**. However converting **Unit8List** to **File** doesn't seem to work.

**I KEEP GETTING THIS ERROR:**
`Error: FormatException: Unexpected extension byte (at offset 0) `

Full Error: 
<img width="1014" alt="image" src="https://user-images.githubusercontent.com/61195383/194753638-6b7747c9-bd26-4f8e-803e-3ef7d6836d02.png">

**WHAT I'M DOING:**
I am trying to convert an **Unit8List** to an **File** Variable with this line: `File convertedFile = File.fromRawPath(png);` with `png` being an Unit8List.

**FULL CODE:**
```
convertFiles() async {   
    //1. Requesting file from the internet [✓ works]   
    http.Response response = await http.get(
        Uri.parse(folderFiles[openFileIndex.value]["link"]),   
    );    

    //2. Decoding WEBP image with "Image" package [✓ works]   
    var image = img.decodeWebP(response.bodyBytes);    

    //3. Encoding decoded WEBP file as an PNG [✓ works]   
    Uint8List png = img.encodePng(image!) as Uint8List;    

    //4. Trying to convert file bytes(Unit8List) to a File Variable [✗ error]   
    File convertedFile = File.fromRawPath(png); 
}
```
VSCode screenshot: 
![code](https://user-images.githubusercontent.com/61195383/194753802-b911a207-87be-4f94-af70-78b8049701e2.png)

**WHAT I TRIED:**
I've tried everything I've seen on the internet including moving to **Master** channel and **Upgrading Flutter**, but none of those things solved the problem.

**FLUTTER DOCTOR:**
```
Doctor summary (to see all details, run flutter doctor -v): 

[✓] Flutter (Channel master, 3.5.0-4.0.pre.23, on macOS 12.6 21G115 darwin-arm64, locale en-SI) 
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0) 
[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1) 
[✓] Chrome - develop for the web 
[✓] Android Studio (version 2021.3) 
[✓] VS Code (version 1.71.2) 
[✓] Connected device (2 available) 
[✓] HTTP Host Availability  

• No issues found!
```

**Comment by exaby73** [comment]
Hello @NikGrmek. Thank you for filing this issue. Can you please provide the following information?

- A [complete and minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). Please exclude any 3rd party libraries in the sample code.
- The output of `flutter doctor -v`
- The output of `flutter run-v`

Please provide the information in the form of text. See how to make collapsible sections with Markdown [here](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-collapsed-sections).
