### ISSUE TITLE
When stocks list is empty, we should show a grayed out splash image instead

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#1131]
- [ ] MaterialList should have a Widget argument that is used when the list is empty as an alternative to the list (maybe "fallback").
- [ ] Stocks app should use that when the list is empty (e.g. when the search matches nothing).

**Comment by abarth** [comment]
placeholder?

We should probably also pull data down from the network on demand instead of loading the whole nasdaq on launch.

**Comment by Hixie** [comment]
placeholder sounds good.

Filed https://github.com/flutter/flutter/issues/1135 for that last thing.

**Comment by abarth** [comment]
Why should this be a feature of lists?  It seems like the stocks app could just build a different thing when it doesn't have any items...  Maybe it should be a feature of MaterialList if this is a pattern in material.

**Comment by Hixie** [comment]
Yeah this is material-specific.

**Comment by Hixie** [comment]
MaterialList is gone now. This is easy to do in an application if we want it. Stocks never has no stocks so I'm going to close this.
