### ISSUE TITLE
`SliverGrid` has a zero `SliverConstraints.crossAxisExtent` on startup in release mode

### ISSUE THREAD

**Issue by gspencergoog** [flutter/flutter#113109]
When I was building `SliverAnimatedGrid`, I ran into an issue where, in release mode only, the sample I wrote would throw an exception because of a divide by zero in `sliver_grid.dart` when calculating the child cross-axis extent [here](https://github.com/flutter/flutter/blob/f36b9c5b28a61500dcc58396050de4a4284fcede/packages/flutter/lib/src/rendering/sliver_grid.dart#L469). The same code ran just fine in debug mode, and did not trigger the preceding assert as it would have if the `SliverConstraints.crossAxisExtent` were zero.

I added a check to make sure that the count was clamped at a minimum of one, but we should figure out why it was different in release mode and debug mode and try to figure out how to write a test for it. I didn't write a test at the time because I couldn't figure out how to test something that only happens in a release build.

**Comment by gspencergoog** [comment]
cc @Piinks

**Comment by jonahwilliams** [comment]
Because release mode is fast enough that we can initially render with a 0 size window.

**Comment by gspencergoog** [comment]
I figured it was something like that.

**Comment by goderbauer** [comment]
+1 to what Jonah is saying above. That is the correct extent the list has at that moment in time and sliver implementations need to handle a zero extend correctly. Is there actually any action left to for this bug?

**Comment by Piinks** [comment]
I think the change @gspencergoog made in https://github.com/flutter/flutter/pull/112982 is right for this case. I'll remove the TODO in my follow up PR https://github.com/flutter/flutter/pull/113793
