### ISSUE TITLE
url_launcher doesn't works in release but yes in develop

### ISSUE THREAD

**Issue by cnksoft** [flutter/flutter#113190]
Hello team. I'm using the url_launcher plugin into my PWA (Web) app. Works perfect in developing but in release, after build the release and upload to my server, the url_launcher doesn't do anything.

My code is as simple as:

await launchUrlString("https://stackoverflow.com/questions/ask");

I have tested several other suggestions, but if like the plugin doesn't work for my domain or subdomain.

I'm runing it into a domain like: www.domain.es/apps/myapp/
And build it as follow:
flutter build web --base-href "/apps/myapp/" --release

I have tested with directly calling js open method and works.
    import 'dart:js' as js;
    js.context.callMethod('open', ['https://stackoverflow.com/questions/ask']);

So, I'm not sure what is failing. If the manifest.json was bad configured, I think the direct js call also dont works, But works perfectly.

Any suggestions?

If possible there can be an issue?

If possible need to configure the path in the web manifest.json file?

thanks very much in advance,

Regards,

**Comment by danagbemava-nc** [comment]
Hi @cnksoft, please provide the following information
 - Your flutter doctor -v output
 - The version of `url_launcher` & `url_launcher_web` you're using
 - The code sample you're using
 - The platform(s) you're experiencing this issue on
 
Thank you
