### ISSUE TITLE
[Impeller] `testOneOverlayAndTwoIntersectingOverlays` scenario test fails with impeller turned on, does not show platform view overlays

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#113251]
`testOneOverlayAndTwoIntersectingOverlays` is failing with impeller turned on.

The test  shows "a simple platform view with one overlay and two overlays that intersect with each other and the platform view."

https://github.com/flutter/engine/blob/a59351f31aa18a7eafebfbbffcad46c0154287f5/testing/scenario_app/lib/src/platform_view.dart#L237

```
$ ./flutter/tools/gn --no-goma --unoptimized --ios --simulator && ninja -C out/ios_debug_sim_unopt scenario_app
$ open out/ios_debug_sim_unopt/scenario_app/Scenarios/Scenarios.xcodeproj
```
Add `FLTEnableImpeller` => `YES` to `ios_debug_sim_unopt/scenario_app/Scenarios/Scenarios/Info.plist`.

Run `-[UnobstructedPlatformViewTests testOneOverlayAndTwoIntersectingOverlays]` 
Should look like this:
<img width="375" alt="success_testOneOverlayAndTwoIntersectingOverlays_1_BE4DD8BD-04E5-47EE-A357-50AB9535F162" src="https://user-images.githubusercontent.com/682784/194980043-936cec4b-a59e-434b-991a-689c2be8075b.png">

but with impeller on is missing the circle overlays:

<img width="375" alt="fail_testOneOverlayAndTwoIntersectingOverlays_1_6200B9E7-7E4C-4645-9A6A-7D573BAA6044" src="https://user-images.githubusercontent.com/682784/194980064-2793e9a0-436d-419e-9013-bb8067d39ca5.png">

See flutter/engine#17049

**Comment by chinmaygarde** [comment]
Update: Finding an owner for this.

**Comment by iskakaushik** [comment]
@jmagman : I tried reproducing this on an iPhone 8 simulator.

I saw that the expected image is matching the actual:

This is what I'm seeing:
![image](https://user-images.githubusercontent.com/1006071/198712830-376e46f4-198b-4572-aafa-3473f1fc2811.png)

Tested one engine version: ff7bdf86d0d3c251f2d219ce7e5f88a1a30b0948

To make sure that I was using the impeller variant, I added some additional prints to confirm this. Let me know if you are still seeing this issue.

**Comment by iskakaushik** [comment]
Lowering the priority until a reproduction is confirmed.

**Comment by jmagman** [comment]
It was reproducing in CI.  If it's fixed then remove this line and the comment above it and this can be closed:
https://github.com/flutter/engine/blob/30d57deea8a674f326c24fa98887b846c15fb37c/testing/scenario_app/run_ios_tests.sh#L62

**Comment by jmagman** [comment]
I am no longer reproducing the missing circles, but there is a new failure:
<img width="561" alt="Screen Shot 2022-11-02 at 12 52 44 PM" src="https://user-images.githubusercontent.com/682784/199589409-2db174f0-b4f8-44c3-b111-3b0d95cb69ac.png">

```
error: -[UnobstructedPlatformViewTests testOneOverlayAndTwoIntersectingOverlays] : ((overlay1.frame.origin.x) equal to (150)) failed: ("75") is not equal to ("150")
```
https://github.com/flutter/engine/blob/a46b72126bb8245dd9d107a4515636e97aef6f9f/testing/scenario_app/ios/Scenarios/ScenariosUITests/UnobstructedPlatformViewTests.m#L161

The test passes on the same simulator when Impeller is off.
Frame failing (impeller on)
```
{{75.0, 150.0}, {150.0, 100.0}}
```
Succeeding (impeller off)
```
{{150.0, 150.0}, {75.0, 75.0}}
```

**Comment by jmagman** [comment]
@iskakaushik do you want a new bug for the frame expectation failure since the overlays are indeed showing up, or do you want to re-use this one?

**Comment by jmagman** [comment]
Failing app tree (impeller on):
```
 →Application, 0x132704500, pid: 83932, label: 'Scenarios'
    Window (Main), 0x132705440, {{0.0, 0.0}, {375.0, 667.0}}
      Other, 0x114e12a40, {{0.0, 0.0}, {375.0, 667.0}}
        Other, 0x114e12df0, {{0.0, 0.0}, {375.0, 667.0}}
          Other, 0x114e12b50, {{0.0, 0.0}, {375.0, 667.0}}, identifier: 'flutter_view'
            Other, 0x114e12c60, {{0.0, 0.0}, {250.0, 250.0}}
              Other, 0x114e12f00, {{0.0, 0.0}, {250.0, 250.0}}
                Other, 0x114e13010, {{0.0, 0.0}, {250.0, 250.0}}, identifier: 'platform_view[0]'
                  TextView, 0x114e138a0, {{25.0, 25.0}, {250.0, 250.0}}, value: platform view
            Other, 0x14263f160, {{75.0, 150.0}, {150.0, 100.0}}, identifier: 'platform_view[0].overlay[0]'
              Other, 0x142641bb0, {{0.0, 0.0}, {375.0, 667.0}}, identifier: 'platform_view[0].overlay_view[0]'
```
Succeeding (impeller off)
```
 →Application, 0x117a04700, pid: 84160, label: 'Scenarios'
    Window (Main), 0x117a04810, {{0.0, 0.0}, {375.0, 667.0}}
      Other, 0x106e04100, {{0.0, 0.0}, {375.0, 667.0}}
        Other, 0x106e044b0, {{0.0, 0.0}, {375.0, 667.0}}
          Other, 0x106e04210, {{0.0, 0.0}, {375.0, 667.0}}, identifier: 'flutter_view'
            Other, 0x106e04320, {{0.0, 0.0}, {250.0, 250.0}}
              Other, 0x106e045c0, {{0.0, 0.0}, {250.0, 250.0}}
                Other, 0x106e046d0, {{0.0, 0.0}, {250.0, 250.0}}, identifier: 'platform_view[0]'
                  TextView, 0x106e047e0, {{25.0, 25.0}, {250.0, 250.0}}, value: platform view
            Other, 0x106e048f0, {{150.0, 150.0}, {75.0, 75.0}}, identifier: 'platform_view[0].overlay[0]'
              Other, 0x106e04a00, {{0.0, 0.0}, {375.0, 667.0}}, identifier: 'platform_view[0].overlay_view[0]'
            Other, 0x106e04b10, {{75.0, 225.0}, {50.0, 25.0}}, identifier: 'platform_view[0].overlay[1]'
              Other, 0x106e04c20, {{0.0, 0.0}, {375.0, 667.0}}, identifier: 'platform_view[0].overlay_view[1]'
```
The second overlay and view are missing with impeller on.

**Comment by iskakaushik** [comment]
@jmagman I will re-use this one
