### ISSUE TITLE
[Dio] 下载文件时，如何获取文件名字和文件后缀？

### ISSUE THREAD

**Issue by BYDU** [flutter/flutter#113216]
在我查看api中看到如下介绍，请问具体如何获取文件名字和文件后缀呢？

await dio.download(
      url,

      (HttpHeaders headers){

        // parse `content-disposition ` here
        return "$filename"
      },
    );

**Comment by stuartmorgan** [comment]
Issues with third-party plugins need to be reported to their developers.
