### ISSUE TITLE
just-installed Xcode Eula message is weird

### ISSUE THREAD

**Issue by shamrin** [flutter/flutter#11320]
I've installed flutter, it all went fine. I haven't done mobile app development before, so I was installing both Xcode and Android Studio in the background. Android Studio finished first. The example worked great. However, when Xcode finished it's part,  `flutter run` failed with a weird message:

```
$ flutter run


Agreeing to the Xcode/iOS license requires admin privileges, please re-run as root via sudo.


```

`flutter doctor` produced the same message:

```
$ flutter doctor


Agreeing to the Xcode/iOS license requires admin privileges, please re-run as root via sudo.


````

Adding `sudo` produced a helpful message, but with an annoying "Woah!" warning:

```
$ sudo flutter doctor
Password:
   Woah! You appear to be trying to run flutter as root.
   We strongly recommend running the flutter tool without superuser privileges.
  /
📎

You have not agreed to the Xcode license agreements, please run 'xcodebuild -license' (for user-level acceptance) or 'sudo xcodebuild -license' (for system-wide acceptance) from within a Terminal window to review and agree to the Xcode license agreements.
```

(Yes, both backslash and clip icon were really there: `📎`.)

Related: #1905

**Comment by Hixie** [comment]
@cbracken claims we've fixed this.
