### ISSUE TITLE
CalendarDatePicker does not render currentDate as current when disabled

### ISSUE THREAD

**Issue by lclaesen** [flutter/flutter#113277]
The CalendarDatePicker marks the current day (the value of `CalendarDatePicker.currentDate`) with a BoxDecoration, but unfortunately does so only when that date is selectable, i.e. (1) lies between the `startDate` and `endDate` and (2) satisfies the `selectableDatePredicate`.

There is no reason why it should do so (nor is this documented behavior). It is perfectly normal e.g. that the currentDate is a Sunday, but selection is restricted to week days; in that case, `currentDate` should appear both as disabled and decorated as being current. Or that selection is possible starting the day after current.

![CalendarDatePicker-bug](https://user-images.githubusercontent.com/83348892/195058279-b286497a-7953-43f9-926b-25a8bd970faf.PNG)

## Steps to Reproduce

Execute `flutter run` on the code sample 

**Expected results:** 
`currentDate` should be displayed as disabled (not selectable because outside of the calendar range) and still be marked with a `BoxDecoration` as the current day (as it is displayed when inside the calendar range).

**Actual results:** 
`currentDate` is not decorated as such.
<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: MyWidget(),
        ),
      ),
    );
  }
}

class MyWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return CalendarDatePicker(
      firstDate: DateTime(2020, 1, 3),
      lastDate: DateTime(2020, 1, 31),
      currentDate: DateTime(2020, 1, 2), // not between first and last
      initialDate: DateTime(2020, 1, 5),
      onDateChanged: (_) {}
    );
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by exaby73** [comment]
## Triage report

I can reproduce this issue. I wasn't able to find a workaround for this. Labelling the issue.

<details>
<summary>Code sample (same as OP)</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: MyWidget(),
        ),
      ),
    );
  }
}

class MyWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return CalendarDatePicker(
      firstDate: DateTime(2020, 1, 3),
      lastDate: DateTime(2020, 1, 31),
      currentDate: DateTime(2020, 1, 2), // not between first and last
      initialDate: DateTime(2020, 1, 5),
      onDateChanged: (_) {}
    );
  }
}
```

</details>
