### ISSUE TITLE
ExpansionTile bug

### ISSUE THREAD

**Issue by Ignacio1224** [flutter/flutter#113285]
Hello,
I found a bug with "ExpansionTile" widget.
I'm using a list of this widgets inside a "Column", the problem is the styling of this widgets.
Using the property "collapsedBackgroundColor" to set the background color when is collapsed depending on a state variable for each one, all colors are the same or the last one in the list.
If I wrap the "ExpansionTile" with "Container" having a "BoxDecoration" and the color property depending to the state variable, there are all correct, but loosing the "ExpansionTile" style properties.

Feel free to contact me if you have a doubt or for more explanation and resources.
icabrera.alumex@gmail.com

```
Column(
        children: businessActions.keys.toList().map(
          (Business b) {
            return PendingActionExpansionTile(
              businessActions: businessActions[b]!,
              business: b,
              businessTheme: getBusinessColor(state: b.state),
            );
          },
        ).toList(),
      )

class PendingActionExpansionTile extends StatefulWidget {
  final Business business;
  final List<BusinessAction> businessActions;
  final BusinessTheme businessTheme;

  const PendingActionExpansionTile({
    super.key,
    required this.business,
    required this.businessActions,
    required this.businessTheme,
  });

  @override
  State<PendingActionExpansionTile> createState() =>
      _PendingActionExpansionTileState();
}

class _PendingActionExpansionTileState
    extends State<PendingActionExpansionTile> {
    @override
      Widget build(BuildContext context) {
        return Padding(
          padding: const EdgeInsets.only(bottom: 8.0),
          child: Column(
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(8.0),
                child: Container(
                  decoration: BoxDecoration(color: widget.businessTheme.background), // <----- this line (remove the container and does not work)
                  child: ExpansionTile(
                    //textColor: widget.businessTheme.background,
                    //collapsedBackgroundColor: widget.businessTheme.background,
                    //collapsedTextColor: widget.businessTheme.foreground,
                    //iconColor: widget.businessTheme.background,
                    //collapsedIconColor: widget.businessTheme.foreground,
                    title: Text(
                      "${widget.business.id} ${widget.business.description}",
                      style: const TextStyle(
                        fontWeight: FontWeight.bold,
                      ),
                    ),
                    children: const []
                  ),
                ),
              ),
            ],
          ),
        );
  }
}
```
Regards

**Comment by huycozy** [comment]
@Ignacio1224 
Please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this. Also, please provide the output of `flutter doctor -v` as well. Thank you!

**Comment by Ignacio1224** [comment]
I hope you accept my apologies, it was my mistake.
I don't know what happened but now, a day later, after restarted the system it is working well.

(Sometimes the machines works of mysterious ways)
Thanks!

**Comment by huycozy** [comment]
@Ignacio1224 It's ok. By the way, when filing a new issue next time, please try to follow [issue template](https://github.com/flutter/flutter/issues/new/choose).
