### ISSUE TITLE
[video_player_web] Video Player does not send http headers on web

### ISSUE THREAD

**Issue by jriegraf** [flutter/flutter#113200]
The Video_Player Plugin does not send http headers on web.

## Steps to Reproduce

1. Execute `flutter run -d chrome` on the code sample 
2. Open Chrome devtools on network tab
3. Find request which fetches the video

**Expected results:**
See the `Authorization` header the `Request Headers` section

**Actual results:** 
`Authorization` header not included in the request

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:video_player/video_player.dart';

void main() => runApp(const VideoApp());

class VideoApp extends StatefulWidget {
  const VideoApp({Key? key}) : super(key: key);

  @override
  _VideoAppState createState() => _VideoAppState();
}

class _VideoAppState extends State<VideoApp> {
  late VideoPlayerController _controller;

  @override
  void initState() {
    super.initState();
    _controller = VideoPlayerController.network(
        'https://flutter.github.io/assets-for-api-docs/assets/videos/bee.mp4',
        httpHeaders: {'Authorization': 'Bearer abc'})
      ..initialize().then((_) {
        setState(() {});
      });
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Video Demo',
      home: Scaffold(
        body: Center(
          child: _controller.value.isInitialized
              ? AspectRatio(
                  aspectRatio: _controller.value.aspectRatio,
                  child: VideoPlayer(_controller),
                )
              : Container(),
        ),
        floatingActionButton: FloatingActionButton(
          onPressed: () {
            setState(() {
              _controller.value.isPlaying
                  ? _controller.pause()
                  : _controller.play();
            });
          },
          child: Icon(
            _controller.value.isPlaying ? Icons.pause : Icons.play_arrow,
          ),
        ),
      ),
    );
  }

  @override
  void dispose() {
    super.dispose();
    _controller.dispose();
  }
}

```

</details>

<details>

Flutter Doctor
```

[✓] Flutter (Channel stable, 3.3.4, on macOS 12.6 21G115 darwin-arm, locale en-DE)
    • Flutter version 3.3.4 on channel stable at /Users/julian/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision eb6d86ee27 (5 days ago), 2022-10-04 22:31:45 -0700
    • Engine revision c08d7d5efc
    • Dart version 2.18.2
    • DevTools version 2.15.0

```

Video Player Plugin
`video_player: ^2.4.7`
`video_player_web: 2.0.12` (from pubspec.lock)

**Comment by darshankawar** [comment]
@jriegraf 
Check [this](https://github.com/flutter/flutter/issues/83602) similar issue and the [response](https://github.com/flutter/flutter/issues/83602#issuecomment-854992361) from team member and see if it helps / gives you an idea as why the plugin may not be sending the http headers.

**Comment by jriegraf** [comment]
Thanks @darshankawar for your reply. I understand the problem. I would like to suggest throwing an error message when using httpHeaders on the web platform or at least mentioning the issue in the documentation. This might save some people some time.

**Comment by darshankawar** [comment]
Thanks for the update. Can you update your issue title and make it as a proposal as below:



> I would like to suggest throwing an error message when using httpHeaders on the web platform or at least mentioning the issue in the documentation
