### ISSUE TITLE
Build "new" flutter gallery during presubmit build shard

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#113248]
Clone and build [flutter/gallery](https://github.com/flutter/gallery) as part of at least one of the build shards, like
https://github.com/flutter/flutter/blob/117407b0fa3601bea80f4a49ab152ac698cf42bc/.ci.yaml#L199

Right now it's only being built post-submit.  Would have prevented tree breakage https://github.com/flutter/flutter/issues/113245.

**Comment by jmagman** [comment]
Around here:
https://github.com/flutter/flutter/blob/32b51d9fcaf110106457f3ece8860507957ce539/dev/bots/test.dart#L558

**Comment by guidezpl** [comment]
Closing in favor of https://github.com/flutter/flutter/issues/100980
