### ISSUE TITLE
Ios device local image rendering deformation

### ISSUE THREAD

**Issue by kutian** [flutter/flutter#113278]
We received feedbacks from users after our project development went live, they said that the bottom of some round images were flat. By taking a screenshot and using the drawing tool to overlay another same size image on top of it, we found that there were extra areas on the bottom half of the image that were causing the image to be rendered distorted. This is shown in the red area of the image below.

| | |
| --------------- | --------------- |
<img width="400" src="https://package.lanxin.cn/client/Screenshots_2022-10-11_18.30.27.png"> | <img width="400" src="https://package.lanxin.cn/client/Flutter_Cicle_20221011065633.png">

Minimum sample code：
`        
icon = Image.asset("packages/flutter_assets/assets/images/3.0x/bot_add.png",color: model.color ?? null ,fit: BoxFit.contain,);
`

flutter doctor -v
```
[✓] Flutter (Channel unknown, 3.0.0, on macOS 12.5 21G72 darwin-arm (Rosetta),
    locale zh-Hans-CN)
    • Flutter version 3.0.0 at /Users/mahao/workspace/flutter/3.0.0
    • Upstream repository unknown
    • FLUTTER_GIT_URL = https://gitee.com/mirrors/Flutter.git
    • Framework revision ee4e09cce0 (5 个月前), 2022-05-09 16:45:18 -0700
    • Engine revision d1b9a6938a
    • Dart version 2.17.0
    • DevTools version 2.12.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/mahao/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = /Users/mahao/Library/Android/sdk
    • Java binary at: /Volumes/Macintosh HD/Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)

[✓] Android Studio (version 2021.2)
    • Android Studio at /Volumes/Macintosh HD/Applications/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.71.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.44.0

[✓] VS Code (version 1.69.2)
    • VS Code at /Volumes/Macintosh HD/Applications/Visual Studio
      Code.app/Contents
    • Flutter extension version 3.44.0

[✓] Connected device (3 available)
    • Mahao test (mobile) • 518fff1769e8d6cc3b01b0d795ef9bf12d950cb4 • ios
      • iOS 15.4.1 19E258
    • macOS (desktop)     • macos                                    •
      darwin-arm64   • macOS 12.5 21G72 darwin-arm (Rosetta)
    • Chrome (web)        • chrome                                   •
      web-javascript • Google Chrome 106.0.5249.103
    ! Error: Mahao test is busy: Fetching debug symbols for Mahao test. Xcode
      will continue when Mahao test is finished. (code -10)

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

**Comment by huycozy** [comment]
@kutian I'm not sure can understand your first screenshot. Is it the zoom of a widget in the 2nd screenshot?
Could you provide the original image assets?
Also, you may try upgrading Flutter SDK to the latest and retry to see if the issue still reproduces. The latest Flutter stable is `3.3.4` and master is `3.5.0`.

**Comment by kutian** [comment]
Yes, it is the zoom of a widget (the first red dot, on the left of "ALL") in the 2nd screenshot. As you can see, there are extra areas at the bottom of this image. Here are our original image assets.
[images.zip](https://github.com/flutter/flutter/files/9760846/images.zip)

**Comment by huycozy** [comment]
@kutian Can you please point out the `extra areas` on this image? It will be better if you can draw a markup on this captured image. 

<img width="568" alt="Screen Shot 2022-10-12 at 12 05 14" src="https://user-images.githubusercontent.com/104349824/195254703-cd802711-8d4e-4186-a2f5-08388263055e.png">

Also, please also provide `red dot` original image asset. The `images.zip` only contains `bot_add.png` which is green icon.

**Comment by kutian** [comment]
[Flutter_Images.zip](https://github.com/flutter/flutter/files/9769928/Flutter_Images.zip)

**Comment by huycozy** [comment]
@kutian I suspect that two images have a slight difference that can cause this problem (with and without resolution). Do you think so?

| bot_add_red | bot_add |
| --------------- | --------------- |
<img width="200" src="https://user-images.githubusercontent.com/104349824/195542055-34374f99-3b1c-4a2e-a98a-d05c11c67153.png"> | <img width="200" src="https://user-images.githubusercontent.com/104349824/195542066-4641eb6a-dd76-4e08-ad2a-5bd755c6f25f.png">

------
Also, please try running below sample code (The green image overlaps the red image in a Stack and vice versa (you can update the code yourself)):

<details>
<summary>Sample code</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: Scaffold(
        body: Center(
          child: Stack(
            children: [
              Image.asset('assets/bot_add_red.png', fit: BoxFit.contain),
              Image.asset('assets/bot_add.png', fit: BoxFit.contain),
            ],
          ),
        ),
      ),
    );
  }

}

```
</details>

<img width="200" src="https://user-images.githubusercontent.com/104349824/195543143-8da6c883-1323-4f58-bde9-4de2d781a1db.png"> <img width="200" src="https://user-images.githubusercontent.com/104349824/195544173-715cc66e-965c-4e91-adb8-e2689a984178.png">

As I see, the mismatched areas are not just at the bottom as your case. So, the issue may come from the implementation code. 
So, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this.
