### ISSUE TITLE
When stocks list is loading, we should show a loading indicator

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#1132]
- [ ] Implement pull-to-refresh (https://github.com/flutter/flutter/issues/425)
- [ ] Show the refreshing UI when the stocks list is loading

**Comment by eseidelGoogle** [comment]
Similarly when stocks fail to load (which it does from time to time).

**Comment by Hixie** [comment]
We show how to do this on the stock symbol page. Not much point doing it on the home page as well.
