### ISSUE TITLE
Commits missing from cocoon dashboard

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#113247]
Commit 21fab6f960 is missing from the dashboard.  It caused a post-submit failure, but I couldn't tell the failure started with that commit since there wasn't a row for it.

![Screen Shot 2022-10-10 at 5 59 56 PM](https://user-images.githubusercontent.com/682784/194974663-82fa0043-9ebe-4d30-b1ec-7e1511218866.png)

117407b0fa <- my avatar, the revert
883c1fe68c <- dash roll avatar, engine roll, tests first start failing in dashboard
21fab6f960 <- missing from dashboard
4be0cfcb3f <- back & white avatar

Missing commits make it difficult to spot which tests are failing.

**Comment by drewroengoogle** [comment]
It seems the `get-status` endpoint is also not returning the missing commit. @godofredoc or @keyonghan, who would be the most knowledgable about the dashboard api?

**Comment by keyonghan** [comment]
It failed to [save commit+tasks to datastore:](https://pantheon.corp.google.com/logs/query;query=resource.type%3D%22gae_app%22%0Aresource.labels.module_id%3D%22default%22%0Aresource.labels.version_id%3D%22version-c94e577%22%0A%22Retrieved%20.ci.yaml%20for%20flutter%2Fflutter%2F21fab6f960a6fd2702bca2501032dd16f34fe114%22;timeRange=2022-10-08T21:07:53.134Z%2F2022-10-11T02:07:53.134Z;cursorTimestamp=2022-10-10T23:13:52.467Z?serviceId=default&project=flutter-dashboard)

```
Uncaught error in request handler: NoSuchMethodError: Class 'GrpcError' has no instance getter 'statusCode'.
Receiver: Instance of 'GrpcError'
Tried calling: statusCode
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:38:5)
#1      RequestHandler.service.<anonymous closure> (package:cocoon_service/src/request_handling/request_handler.dart:71:32)
<asynchronous suspension>
#2      SubscriptionHandler.service.<anonymous closure> (package:cocoon_service/src/request_handling/subscription_handler.dart:134:19)
<asynchronous suspension>
#3      SubscriptionHandler.service (package:cocoon_service/src/request_handling/subscription_handler.dart:133:5)
<asynchronous suspension>
#4      main.<anonymous closure>.<anonymous closure> (file:///app/bin/server.dart:279:9)
<asynchronous suspension>
```

Related code: https://github.com/flutter/cocoon/blob/main/app_dart/lib/src/service/scheduler.dart#L123
I am expecting to see this exception catch: https://github.com/flutter/cocoon/blob/main/app_dart/lib/src/service/scheduler.dart#L157, which doesn't show in the log though.

We can try adding more logs before saving the entries to datastore to see if the error does happen in the try block.

**Comment by drewroengoogle** [comment]
@keyonghan Have you seen this happen before or is this the first time?

**Comment by keyonghan** [comment]
> @keyonghan Just so I have better context, have you seen this happen before or is this the first time we've had a missing commit?

This is the first time though AFAIK.

> https://github.com/flutter/flutter/commit/21fab6f960a6fd2702bca2501032dd16f34fe114 reappeared, it's in the dashboard now.

This may be owing to the pub/sub queue keep trying. But we need to take a look at the logs to see how it went.

**Comment by drewroengoogle** [comment]
I'm going to close for now because this hasn't reoccurred and I haven't been able to reproduce or see anything weird in the logs. Please don't hesitate to reopen if this issue occurs again
