### ISSUE TITLE
fuchsia.googlesource.com/third_party/libcxx was deleted

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#113293]
Relatively recent engine versions including 3.3 branch refer to this repo, which was deleted, and now it is not possible to build these versions, e.g. for hotfixes. See https://github.com/flutter/engine/pull/36621

@godofredoc @CaseyHillers

**Comment by drewroengoogle** [comment]
@godofredoc is going to talk to Fuchsia to undelete the repository, and @CaseyHillers is looking at getting a copy of the repo available to us.

**Comment by godofredoc** [comment]
Fuchsia team is bringing the repository back for a couple of weeks while we fork it and build the hotfix.

**Comment by godofredoc** [comment]
@zanderso the repository should be back. We'll create a fork of it on flutter.googlesource.com

**Comment by godofredoc** [comment]
Can you please take a look and if it works correctly can you please reassign to me for creating the fork?

**Comment by godofredoc** [comment]
Moving to P2 as the repository is back

**Comment by jason-simmons** [comment]
Would it be possible to make the libcxx repository permanently accessible at fuchsia.googlesource.com?

Developers sometimes need to build older versions of the engine where the `DEPS` file references a fuchsia.googlesource.com URL (see https://github.com/flutter/flutter/issues/112919).  It would be preferable if those commits could still be built without manually applying patches.

**Comment by CaseyHillers** [comment]
For third party deps, we should really add them to flutter.googlesource.com/third_party. It's the only way we can guarantee the repos won't be deleted.

/cc @sealesj whose looking at securing the engine deps who might be interested in adding this as a lint

**Comment by zanderso** [comment]
I have verified that the restored repo works. `gclient sync` on a checkout of flutter-3.2-candidate.4 is successful.

**Comment by zanderso** [comment]
@CaseyHillers I don't think we need a special purpose lint for that. Instead we can remove `fuchsia.googlesource.com` from the allowed hosts list, and `gclient verify`(?) will check it for us. Also, unfortunately, we can't go back in time and make the change retroactively, so our only option to keep old commits building is to complain when their dependencies are inadvertently deleted.

**Comment by Hixie** [comment]
It's a problem if we can't build older versions of Flutter. We should be able to always build any version of Flutter we've ever released.

**Comment by godofredoc** [comment]
I agree the desirable state is to be able to always build old versions but in practice we can't guarantee that we will be able to build branches older than the current stable. In addition to that depending on repositories or mirrors that we don't control makes it even more difficult.

After mirroring fuchsia.googlesource.com/third_party/libcxx to flutter.googlesource.com/third_party/libcxx we should move  the dependencies to the flutter mirror.

**Comment by godofredoc** [comment]
@nehalvpatel can you please help us with this fork? you can find instructions here: go/flutter-thirdparty-fork

**Comment by nehalvpatel** [comment]
Sure, I will start working on it today

**Comment by nehalvpatel** [comment]
I have set it up at flutter.googlesource.com/third_party/libcxx

**Comment by godofredoc** [comment]
Thanks @nehalvpatel, we can close this bug. @zanderso if we hit this issue again we can update the failing PR to pull from the flutter third party mirror.
