### ISSUE TITLE
[Impeller] `testFontRenderingWhenSuppliedWithBogusFont` scenario test fails with impeller turned on, does not render bogus font as system font

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#113250]
`testFontRenderingWhenSuppliedWithBogusFont` is failing with impeller turned on.

The test "tries to draw some text in a bogus font. Should end up drawing in the system default font."
```dart
    final ParagraphBuilder paragraphBuilder =
        ParagraphBuilder(ParagraphStyle(fontFamily: "some font that doesn't exist"))
          ..pushStyle(TextStyle(fontSize: 80))
          ..addText('One more thing...')
          ..pop();
    final Paragraph paragraph = paragraphBuilder.build();
```
https://github.com/flutter/engine/blob/05ff95d4496fa5f4bc1591fdbd06bfb1bcc249fe/testing/scenario_app/lib/src/bogus_font_text.dart#L12

```
$ ./flutter/tools/gn --no-goma --unoptimized --ios --simulator && ninja -C out/ios_debug_sim_unopt scenario_app
$ open out/ios_debug_sim_unopt/scenario_app/Scenarios/Scenarios.xcodeproj
```
Add `FLTEnableImpeller` => `YES` to `ios_debug_sim_unopt/scenario_app/Scenarios/Scenarios/Info.plist`.

Run `-[BogusFontTextTest testFontRenderingWhenSuppliedWithBogusFont]` 
Should look like this:
<img src="https://user-images.githubusercontent.com/682784/194978414-1a85ecbc-ff8a-4fad-a6cb-f30b7390d6ab.png" width=300>
but with impeller on shows a black screen:
<img src="https://user-images.githubusercontent.com/682784/194978448-ff727ed5-d4d2-407b-81db-4e356f0ee435.png" width=300>

See flutter/engine#22033 and https://github.com/flutter/flutter/issues/60013

**Comment by zanderso** [comment]
Fixed in https://github.com/flutter/engine/commit/1ec7b89f3a6b92dc1888724cb2a4dceda8cb1af1
