### ISSUE TITLE
Utilize `flutter_smooth` which makes 60FPS no matter how slow build/layout is, combining Dart JIT, to implement code push / hot update / out of band updates 

### ISSUE THREAD

**Issue by fzyzcjy** [flutter/flutter#113281]
**Disclaimer**: This is a very rough idea. https://github.com/fzyzcjy/flutter_smooth is still WIP (though I hope I can finish it within days).

## Background

https://github.com/flutter/flutter/issues/14330 is the [most upvoted issue of the whole Flutter (and is 34% more popular than the second most)](https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc), but it is not on the roadmap. React native has hot reload, which, I have to admit though I love Flutter, is a *huge* advantage over Flutter, and many people choose RN instead of Flutter because of that. Therefore, it would be great to support hot reload.

## The problem

As is pointed out [here](https://github.com/flutter/flutter/issues/14330#issuecomment-485565194) (this is linked from the root post of that issue), @Hixie says:

> To comply with our understanding of store policies on Android and iOS, any solution would be limited to JIT code on Android and interpreted code on iOS. We are not confident that the performance characteristics of such a solution on iOS would reach the quality that we demand of our product. (In other words, "it would be too slow".)

In the section below I will discuss how flutter_smooth may help.

As for other points, it is unrelated to flutter_smooth so I only briefly discuss (probably my points have been discussed before as well).

> There are some serious security concerns ...

RN did well :) I strongly believe Flutter and Google definitely will never do a worse job than RN and Facebook.

> There is currently no out-of-the-box open source hosting solution for ...

If it is supported, community (surely including me) can create one, so this point will not be a problem.

## Proposal 1

In https://github.com/fzyzcjy/flutter_smooth, I try to make it run at 60FPS smooth, no matter how heavy the build/layout is. You can check the design doc, demo video, etc, there.

This sounds a perfect match for the JIT. Suppose we have an AOT (i.e. current) app that runs well, and now consider what happens when we change it to JIT. The rasterizer thread will be the same speed (since it is C++ not Dart), so we have no problem. It is only the UI thread running Dart code that may be slower due to JIT. However, given flutter_smooth, the slowness does not introduce any jank in visual appearance. The users can still (for example) enter a page, scroll a list view, etc, at full FPS. Surely, for CPU intensive work using Dart, any speed drop will be un-acceptable, but for those cases we may just exclude them from hot update. 

<small>Btw as for JIT/interpreted speed, seems that JavaScript has no problem, so I guess Dart should be OK as well. Anyway I am not a compiler expert so this is just a guess.</small>

## Proposal 2

If making the whole thing JIT/interpreted is slow, we may do it partially. We know the whole Flutter framework Dart code will usually not change across hot updates (and they take up a big portion in the final artifact), so they may be AOTed and not hot updated. Even further, we know most app code will not change except for a small portion in a hot update (otherwise it is a huge change to app and a normal update may be acceptable), so let's keep all code be AOTed, except for that small updated part fallback to JIT/interpreted.

Since most code change usually are business logic code, like changing content of a home screen, the slowdown due to AOT becoming JIT seems to be very limited, i.e. only little slowdown. It is because, those business logic code seems not to be very slow. Indeed they are just a bunch of `build`s that creates a lot of other widgets (which are cheap), while the real heavy work (like how to layout a tree) are in Flutter framework or in seldom-change app code and are AOTed.

This also seem to suit flutter_smooth to a greater extent. If the paint phase is too slow, flutter_smooth can do nothing currently. This is not a problem for *normal* apps, because empirically, most app jank at build and layout phase, not paint phase. However, if the JIT/interpreted is so slow in proposal 1 that even paint phase starts to jank, then proposal 1 does not work. But proposal 2 still works, because the paint phase is usually done by Flutter framework code (or custom RenderObjects - but few people change their custom RenderObjects a lot in everyday updates), so they can still be AOTed and run at full speed. Indeed, I suspect most code change will be app logic code, such as `MyPage`, `MyComponent`, etc. Therefore, it is the build phase (including initState, build, etc) of these business logic code that will slow down because they fallback to JIT/interpreted in a hot update. flutter_smooth can handle such slowness.

Not sure whether Dart supports mixed AOT+JIT/interpreted now. Surely, I myself alone cannot contribute that since it is too big. But given that Dart compiler creates AOT mode years ago because Flutter needs it, I guess Google has the ability to add "AOT+JIT/interpreted mixed mode" :)

**Comment by Hixie** [comment]
The reason #14330 is not implemented is not a technical one -- there are several ways we could implement it, and we've experimented with several in the past -- it's a policy one. I just posted an update there to clarify that.

**Comment by fzyzcjy** [comment]
@Hixie I see and reply there. Thank you!

**Comment by dnfield** [comment]
I'm going to close this so it doesn't continue to come up on new feature scans in favor of #14330.

**Comment by fzyzcjy** [comment]
@dnfield Sure - then I may report somewhere else later when there is progress about this approach. Btw, what is "feature scan"? Is it this one https://github.com/flutter/flutter/labels/new%20feature - which has 2000 issues so I guess it is not manually scanned

**Comment by dnfield** [comment]
Various subteams meet periodically to look at issues tagged with `new feature`.
