### ISSUE TITLE
`(MDnsClient).start()` should not fail when a single interface bind fails

### ISSUE THREAD

**Issue by Erhannis** [flutter/flutter#113258]
multicast_dns: ^0.3.2+2
Flutter (Channel stable, 3.3.2, on Microsoft Windows [Version 10.0.19044.2006], locale en-US)

While this is triggered by a specific error I'm encountering, one of the key factors seems pretty clear, so I'm filing an issue on that rather than my specific error.

If the `bind` triggered by this line
https://github.com/flutter/packages/blob/a7e3410f3d5a9f1f7a46967aa45c8d05f5f1bd06/packages/multicast_dns/lib/multicast_dns.dart#L135
throws an exception, the entire `start` method fails.  It seems to me like letting a single bad/broken/occupied interface fail all the others is undesirable.  I'm not sure what form you want the solution to take - I don't know what idioms and general outcomes you prefer.  You could wrap the inside of the loop at https://github.com/flutter/packages/blob/a7e3410f3d5a9f1f7a46967aa45c8d05f5f1bd06/packages/multicast_dns/lib/multicast_dns.dart#L132 with a try/catch; doing so makes my code work.  (Like [so](https://github.com/flutter/packages/commit/72d9111407f09bfa25b47d357e22f2f2be7408a2).)  Perhaps you prefer not to write to the logs, or perhaps you have a logging system you use.  Or perhaps you'd prefer to return the list of successfully bound interfaces, or return a list of failures.  Up to you.

An example stack trace, btw, in Windows, is
```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: SocketException: Failed to create datagram socket (OS Error: The requested address is not valid in its context.

, errno = 10049), address = , port = 5353
#0      _NativeSocket.bindDatagram (dart:io-patch/socket_patch.dart:1015:7)
<asynchronous suspension>
#1      MDnsClient.start (package:multicast_dns/multicast_dns.dart:135:40)
<asynchronous suspension>
#2      autoconnect (package:hm305p_remote/HM305PConnector.dart:27:3)
...
```

## Steps to Reproduce

I don't know how to reproduce the problem on another computer, but I assert reproduction is unnecessary for this bug.  `bind` can throw, and throwing will exit `start`, and IMO this should not occur.

**Expected results:** 

If an interface fails to bind, instead throwing an exception, the other interfaces will bind successfully and the failures will not prevent `start` from completing successfully.

**Actual results:** 

An interface fails to bind, throws an exception, and `start` is aborted.

**Comment by huycozy** [comment]
@Erhannis 
I see there's an open issue addressing the case you described #53477. Please share your findings or react an upvote to the original comment will help to raise the issue.
Closing this issue as a duplicate, so please follow up on it for further updates. Thanks!
