### ISSUE TITLE
App Can't launch without internet connection

### ISSUE THREAD

**Issue by akshaynjarangal** [flutter/flutter#113265]
Hello Flutter team , When internet is Disconnected on Mobile,then start the debugging, the App will be freezing on native white splash screen , when internet is ON, app will work, what is the issue, 

Flutter version 3.3.4

**Comment by exaby73** [comment]
Hello @akshaynjarangal. Thank you for filing this issue. Can you please provide the following information?

- A [complete and minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). Ideally, a single `main.dart` file that can be run directly.
- The output of `flutter doctor -v`
- The output of `flutter run-v`

Please provide the information in the form of text. See how to make collapsible sections with Markdown [here](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-collapsed-sections).

**Comment by akshaynjarangal** [comment]
👋 @exaby73 , it's firebase cloud messaging and flutter local notifications functions are called before runApp , that's the reason for the issue, then the functions are called after runApp, it's solved.
