### ISSUE TITLE
Allow `Slider` to be "slide only" like YouTube mobile progress bar

### ISSUE THREAD

**Issue by liumcse** [flutter/flutter#113370]
## Use case

I would like to request a feature on the `Slider` widget where you can configure it to be "slide only", so that users can only change the value by tap-and-drag. If users just tap anywhere without dragging, it's no-op.

It's similar to the progress bar on YouTube app, you tap anywhere on the progress bar it won't change the video position - you have to slide. Here's a recording to YouTube's sliding behavior: https://drive.google.com/file/d/1kYEIxFB02E-avJCYsk5KWUPtANqzP_C_/view?usp=share_link

## Proposal

```dart
/// Option 1: A boolean parameter
Slider(
  slideOnly: true
);

/// Option 2: An enum for interaction style
Slider(
  interactionStyle: SliderInteractionStyle.DRAG_ONLY;
);

enum SliderInteractionStyle {
  DEFAULT,
  DRAG_ONLY,
  // ...
}
```

**Comment by Piinks** [comment]
This might be good to have as an enum, specifying what kind of slider interaction is permissible.

**Comment by Piinks** [comment]
Hey @werainkhatri! Great to see you again. Thanks for picking this up. :)

**Comment by liumcse** [comment]
Thank you @werainkhatri for picking this up! I've updated the issue to include a recording. Thank you!

**Comment by werainkhatri** [comment]
> Thanks for picking this up. :)

new API issues have kinda become my forte. sorry for delaying this tho, wasn't able to make time for writing a design doc as there are many ways to approach the issue while trying to code it up.

> I've updated the issue to include a recording

thanks, that was very helpful!

finally, i have written one, please check it out and comment any questions / suggestions / feedback.

https://docs.google.com/document/d/151iaqbK-rZSRI34NdkvfIk4RkzOpAevoJ87TwiXfTpM/edit?resourcekey=0-o0Gx6nrgl-fpw7_zUdMaQA#
(will replace this with the go link soon...)
