### ISSUE TITLE
libApp.so size confuse (arm32 > arm64)

### ISSUE THREAD

**Issue by zjrwdl** [flutter/flutter#113359]
We are parsing flutter apk size and confused by the follow phenomenon:
libapp.so (arm32)  > libapp.so(arm64) 
<img width="764" alt="image" src="https://user-images.githubusercontent.com/6874049/195493837-4a9d18b0-9f24-4622-ae32-68b237261afa.png">

you can test by create a flutter apk demo in steps below :
flutter create apk_size_test
flutter build apk --target-platform android-arm 
flutter build apk --target-platform android-arm64
compare two apks size

generally speaking , with the same code, compile product size for arm64 should be larger than that for arm32.

@mraleph  @mkustermann

**Comment by mkustermann** [comment]
> generally speaking , with the same code, compile product size for arm64 should be larger than that for arm32.

Why do you assume code for arm64 should generally be larger than arm32?

The instruction encodings are quite different in some aspects as well as available register set - some things may be smaller on arm32 (e.g. pushing many registers to the stack with one instruction) some may be larger (e.g. int64 arithmetic): Dart uses wrap-around int64 integers semantic. Here's an example of a C program compiled with clang to arm32/arm64:
```c
int64_t mul(int64_t a, int64_t b) {
    return a * b;
}
```
arm32:
```
mul(long long, long long):
        push    {r4, lr}
        umull   r12, lr, r2, r0
        mla     r4, r2, r1, lr
        mla     r1, r3, r0, r4
        mov     r0, r12
        pop     {r4, lr}
        bx      lr
```
and arm64
```
mul(long, long):  
        mul     x0, x1, x0
        ret
```


(The assumption is more valid for memory consumption, because pointers are 8 bytes instead of 4)

**Comment by zjrwdl** [comment]
> > generally speaking , with the same code, compile product size for arm64 should be larger than that for arm32.
> 
> Why do you assume code for arm64 should generally be larger than arm32?
> 
> The instruction encodings are quite different in some aspects as well as available register set - some things may be smaller on arm32 (e.g. pushing many registers to the stack with one instruction) some may be larger (e.g. int64 arithmetic): Dart uses wrap-around int64 integers semantic. Here's an example of a C program compiled with clang to arm32/arm64:
> 
> ```c
> int64_t mul(int64_t a, int64_t b) {
>     return a * b;
> }
> ```
> 
> arm32:
> 
> ```
> mul(long long, long long):
>         push    {r4, lr}
>         umull   r12, lr, r2, r0
>         mla     r4, r2, r1, lr
>         mla     r1, r3, r0, r4
>         mov     r0, r12
>         pop     {r4, lr}
>         bx      lr
> ```
> 
> and arm64
> 
> ```
> mul(long, long):  
>         mul     x0, x1, x0
>         ret
> ```
> 
> (The assumption is more valid for memory consumption, because pointers are 8 bytes instead of 4)

thanks for answer

**Comment by mraleph** [comment]
I am just going ahead and close this. As @mkustermann explained above the difference is somewhat expected.
