### ISSUE TITLE
Purchase dash_subscription_doubler not found

### ISSUE THREAD

**Issue by lim-enhui** [flutter/flutter#113380]
I am following the https://codelabs.developers.google.com/codelabs/flutter-in-app-purchases#7 but i could not get the subscription

Given the same repository for complete code I would like to know if there is any misconfiguration for google console

<img width="1409" alt="Screenshot 2022-10-13 at 8 54 32 PM" src="https://user-images.githubusercontent.com/13527348/195601909-63334b51-21b3-4e72-915b-d94bd351b7e5.png">

**Comment by danagbemava-nc** [comment]
Hi @lim-enhui, have you uploaded an appbundle to a testing track?
Have you also added the account you're testing with as a `License tester`?

Are you getting any errors in your console? 
If so, kindly share the error.

Kindly share the output of `flutter doctor -v` as well as the version of `in_app_purchase` & `in_app_purchase_android` that you're using. 

Thank you

**Comment by lim-enhui** [comment]
The subscription finally shows. It took a day to reflect though. Thanks.
