### ISSUE TITLE
MouseRegion, event.kind is no longer accurate on Flutter 3.3.3

### ISSUE THREAD

**Issue by lecuivre-alban** [flutter/flutter#113332]
After upgrade Flutter from 3.0.4 to 3.3.3, the code in the following example is no longer working.
Previously this bit of code could be use to determine if the user is using a touch device, a mouse, etc..

With Flutter 3.3.3 the event.kind stays the same, `PointerDeviceKind.mouse`

## Steps to Reproduce

1. Execute `flutter run` on the code sample, on a device with a touchscreen 
2. Even on a device with a touchscreen, the text display stay `PointerDeviceKind.mouse`

**Expected results:** 
- display `PointerDeviceKind.touch`

**Actual results:** 

<details>
<summary>Code sample</summary>

```dart

void main(){
  runApp(
    const MaterialApp(
      home: MyApp(),
    ),
  );
}

class MyApp extends StatefulWidget {
  const MyApp({super.key});
  
  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  PointerDeviceKind pointerKind = PointerDeviceKind.unknown;
  final ValueNotifier<int> count = ValueNotifier(0);
  
  @override
  void dispose(){
    count.dispose();
    super.dispose();
  }
  
  void _updatePointerKind(PointerDeviceKind event){
    count.value = count.value + 1;
    if(event != pointerKind){
      setState((){
        pointerKind = event;
      });
    }
  }
  
  @override
  Widget build(BuildContext context){
    return Scaffold(
      body: MouseRegion(
        onEnter: (details) => _updatePointerKind(details.kind),
        onEHover: (details) => _updatePointerKind(details.kind),
        child: Center(
          child: Column(
            children: [
              ValueListenableBuilder<int>(
                valueListenable: count,
                builder: (context, value, _){
                  return Text("Function called $value times");
                },
              ),
              Text("Pointer kind : $pointerKind"),
            ]
          ),
        ),
      ),
    );
  }
}
```

</details>

**Comment by lecuivre-alban** [comment]
Windows computer, using a touchscreen

**Comment by exaby73** [comment]
Unfortunately, I do not have a touchscreen device to verify this issue. On Android, it seems to work fine. @lecuivre-alban Can you confirm if this issue is occurring on master channel too?

**Comment by moffatman** [comment]
I tried it out on my windows laptop, it works as expected (showing PointerDeviceKind.touch for touch screen). This is on master channel.

**Comment by lecuivre-alban** [comment]
I have updated to Flutter 3.3.6 and the issue is still happening.
For some reasons the callbacks of MouseRegion are not called on two devices I have been testing on (Windows 10 & 11).

**I found a workaround using GestureDetector.**

I have updated the code sample to be exaclty what I have been using while facing the issue.
