### ISSUE TITLE
Images are not sharp on desktop apps on external monitor

### ISSUE THREAD

**Issue by dbacic** [flutter/flutter#113366]
First of all, I would want to say thanks for keeping Flutter such a great language to work with!

# The Problem

I added support for windows and macOS for my existing mobile app made with flutter (which has millions of users) and I saw an issue with image rendering.

When I run the app it's opened on the main (laptop) screen and the images are sharp but moving the app to the external monitor the photos lose their sharpness. I was using .svg and thought that the problem was with the flutter_svg package but then I used .png and the issue is the same.

I tried finding some similar issue [here](https://github.com/flutter/flutter/issues/89605) but no luck, only this one which I couldn't reproduce (tried to remove the SizedBox or replace it with Container but it's the same).

_Screenshots (top as it should be (on the main monitor), bottom pixelated on an external monitor)._

<img width="430" alt="Screenshot 2022-10-13 at 11 16 10" src="https://user-images.githubusercontent.com/75118314/195557214-bb75a851-0693-4a40-bfab-efe759667a55.png">

![Screenshot 2022-10-13 at 11 16 24](https://user-images.githubusercontent.com/75118314/195557217-74cab1ab-e7f3-4b1a-9cac-3e3652250ff3.png)

## Steps to Reproduce

This is the code:

```Column(
  children: [
    SizedBox(
      height: 88.8,
      child: Padding(
        padding:
            const EdgeInsets.fromLTRB(24, 24, 48, 24),
        child:
            Assets.images.misc.gsLogo.svg(height: 46),
      ),
 ),
```

_flutter doctor -v_ output:

```
[✓] Flutter (Channel stable, 3.3.3, on macOS 12.6 21G115 darwin-arm, locale en-RS)
    • Flutter version 3.3.3 on channel stable at /Users/darkobacic/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18a827f393 (2 weeks ago), 2022-09-28 10:03:14 -0700
    • Engine revision 5c984c26eb
    • Dart version 2.18.2
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/darkobacic/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A309
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.72.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (3 available)
    • SM N970F (mobile) • R58M80X1C2A • android-arm64  • Android 12 (API 31)
    • macOS (desktop)   • macos       • darwin-arm64   • macOS 12.6 21G115 darwin-arm
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 106.0.5249.103

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```
If you need more information please let me know,
thanks!

**Comment by dbacic** [comment]
Hi @huycozy, thanks for responding! :) I have just checked on beta and master, it's the same as on stable channel (I did even a clean and pub get to be sure in the project).

The results are the same (I downloaded a random png from the web 840 × 769px) and used it in a clean (empty) new Flutter project. 

Here is the retina display (2560x1600):
<img width="912" alt="Screenshot 2022-10-13 at 14 51 24" src="https://user-images.githubusercontent.com/75118314/195601774-2a4f2450-190c-4d6c-a30e-6bfa13a06c13.png">

And here a Dell 27" (full hd 1920x1080) monitor:
![Screenshot 2022-10-13 at 14 51 21](https://user-images.githubusercontent.com/75118314/195601887-05c64993-c9f6-45ff-9ec6-02911869a07c.png)

If you get closer or zoom in you can see that the rendering of lines and edges of the png is terrible on the full hd monitor.

The source code can be found [here](https://github.com/dbacic/flutter-desktop-image-rendering-issue-external-monitor). I tested this clean app only on Macbook Air M1, but my project I also tested on a Windows (Razer 5 CPU) and it's the same behaviour. 

If you need anything else, I'm more than happy to assist :)

**Comment by huycozy** [comment]
@dbacic 
By default, `filterQuality` is `FilterQuality.low`, so please try `FilterQuality.medium` to see if it makes a difference. 

Also, when taking a look again on your first screenshots, I also see that the status bar is pixelated too:

| | |
| --------------- | --------------- |
<img width="400" src="https://user-images.githubusercontent.com/104349824/195801814-2f2a9e38-b0d8-40a5-941a-a9c9c1d0a6be.png"> | <img width="400" src="https://user-images.githubusercontent.com/104349824/195801876-0740b971-27a4-4c07-961d-1d1592f70f23.png">

Can you provide another screenshot on different application (Chrome browser for example) when displaying on two monitors?

**Comment by dbacic** [comment]
@huycozy  I tried with `filterQuality.high` but that did not help. You are right about the slightly pixelated status bar, when I lean toward the monitor I can see some pixels but it's not as bad as when renreding the image. Here you can see on the left the laptop screen and on the right monitor (at the same zoom level, it's retina@13" vs full hd@27").

<img width="1419" alt="Screenshot 2022-10-14 at 10 50 24" src="https://user-images.githubusercontent.com/75118314/195805653-6a4308f1-958c-40d4-a29d-e807bc4cfa55.png">

And here is the Chrome screenshot on both screens with an image of a line opened. (again top mac bottom monitor)
<img width="1438" alt="Screenshot 2022-10-14 at 10 50 11" src="https://user-images.githubusercontent.com/75118314/195806055-dc8532c5-e666-4a12-8847-b281ebc654e3.png">


![Screenshot 2022-10-14 at 10 49 56](https://user-images.githubusercontent.com/75118314/195806107-8b6ae9ba-bf0d-413f-864f-71592a94ffa5.png)

PS: I also tried to change from HDMI to Display Port but that didn't change anything (just to mention that both cables go to an adapter to USB C).

**Comment by huycozy** [comment]
@dbacic 
I also see a clear difference in [your demo with the Chrome app](https://github.com/flutter/flutter/issues/113366#issuecomment-1278702040); the Chrome tab title and status bar are pixelated same as above demo:

- Mac:
<img width="800" src="https://user-images.githubusercontent.com/104349824/196082551-581904d1-f7d8-4236-859f-6c018084914f.png">

- External monitor:
<img width="800" src="https://user-images.githubusercontent.com/104349824/196082548-5f0fed6d-ab10-452a-8324-faab8595741d.png">

I think that this is not an issue from Flutter side. We are therefore reluctantly going to close this bug for now.
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away! Thanks for your contribution.
