### ISSUE TITLE
Flutter framework size analyze tool

### ISSUE THREAD

**Issue by 337240552** [flutter/flutter#113363]
## Use case
Binary analyze tool like [this](https://storage.googleapis.com/flutter_infra/flutter/5a4bd0de69fbceb36ccecfcbf8c81dc8d94ea949/android-arm64-release/sizes/index.html), found in  another [issue](https://github.com/flutter/flutter/issues/43517) post by @dnfield .

We are doing flutter framework tailoring and need a binary analysis tool. 
 

## Proposal
I saw that Google's analysis tool is very powerful. It can be divided into components. Can this component be released together with the source code of the flutter engine? Or provide a binary package. Open source bloaty is also powerful, but it cannot be done at the component level.
 
<img width="1002" alt="binary analyze tool" src="https://user-images.githubusercontent.com/329210/195537911-d02653df-b743-4ad5-8174-e670a9e3c98d.png">

**Comment by goderbauer** [comment]
@kenzieschmoll Does devtools provide a size analysis tool?

**Comment by kenzieschmoll** [comment]
Yes it does: https://docs.flutter.dev/development/tools/devtools/app-size

**Comment by 337240552** [comment]
> Yes it does: https://docs.flutter.dev/development/tools/devtools/app-size

@goderbauer @kenzieschmoll 
Devtools is used to analyze business code. In fact, we need a tool that can analyze the components of the flutter engine. After researching, the screenshot I sent was generated by a tool in chrome. It would be nice if it could be integrated into the flutter engine.

**Comment by huycozy** [comment]
Based on the recent comment above, looks like this is suited for `engine` team. Adding `engine` labels again, please update if it's not appropriate.

**Comment by chinmaygarde** [comment]
> In fact, we need a tool that can analyze the components of the flutter engine

The engine tree-maps are produced per commit https://github.com/flutter/flutter/wiki/Engine-disk-footprint#treemaps. Though, there was a recent issue where the location of the tree-maps on the cloud storage bucket was unexpected. https://github.com/flutter/flutter/issues/136011. An example of this [for a recent commit is here](https://storage.googleapis.com/flutter_infra_release/flutter/12def739b1f63ccaf5b859714d9f552e9e6fe348/android-arm64-release/sizes/index.html).

Closing this as fixed.
