### ISSUE TITLE
Ability to run Dart script before Running or Building

### ISSUE THREAD

**Issue by hndrbrm** [flutter/flutter#113364]
### Use commit or tag from git revision as version shows on the Application.

I found in [Stackoverflow](https://stackoverflow.com/questions/63888873/show-git-last-commit-hash-and-current-branch-tag-in-flutter-app) the solution is categorized into two type:

1. Using some platform-based script such as bash (ubuntu), cmd (windows), zsh (macos) to run the `git` and get the needed information. Then put the information in a file which will be read in the application. For example the information put into .env file or .dart file. Both will be used in the compiling process.

  The problem in here is the Terminal-based script, i need to maintain the script for each terminal which is cmd, powershell, bash, zsh, fish, dash, etc. And also need to put some comment about how to use each of them. So the app builder need to match their existing terminal with the appropriate script. For example by putting the correct script on the .git/hook/ or on the .env

2. Put the .git/* into part of the Assets. And read the information directly in the application.

  The problem in here is the structure of the .git file will be exposed as Assets, such as .git/HEAD, .git/refs/*.

### Able to run dart script before compiling.
Since dart is multiplatform, the problem with terminal-based script is done replaced by dart script. And since we could create custom file for git information, we could hide the structure-exposed problem.

**Comment by exaby73** [comment]
Hello @hndrbrm. You can write a terminal based script that runs a dart file. The syntax is the same for all, it being `dart <file_name>.dart`. Why not use this instead?

**Comment by hndrbrm** [comment]
> Hello @hndrbrm. You can write a terminal based script that runs a dart file. The syntax is the same for all, it being `dart <file_name>.dart`. Why not use this instead?

I am avoiding using Terminal-based script since in a longterm, it force us to maintain 3 terminal for 3 platform:
cmd for windows e.g. prebuild.bat, bash for linux and zsh for macos like prebuild.sh.

The solution for now, is to put the prebuild.dart as part of the source, something like tools/prebuild.dart. Then add instruction to the readme, for the future maintainer, that to build the application they need to run the script something like `dart tools/prebuild.dart` in their terminal.

It means its manually (and prone to human error).
If the build system in the flutter framework could include running dart in the beginning of the build process, then the instruction on the readme is not necessary anymore. Since its now guaranteed to be run by the build system.

**Comment by christopherfujino** [comment]
@iapicca is there anything unique in this proposal not covered by either https://github.com/flutter/flutter/issues/90612 or https://github.com/flutter/flutter/issues/112727?

**Comment by iapicca** [comment]
> @iapicca is there anything unique in this proposal not covered by either https://github.com/flutter/flutter/issues/90612 or https://github.com/flutter/flutter/issues/112727?

Just the ability to trigger such custom script on "flutter build"

**Comment by christopherfujino** [comment]
> > @iapicca is there anything unique in this proposal not covered by either #90612 or #112727?
> 
> Just the ability to trigger such custom script on "flutter build"

https://github.com/flutter/flutter/issues/112727 describes a system for running custom code at build time.

**Comment by iapicca** [comment]
> > > @iapicca is there anything unique in this proposal not covered by either #90612 or #112727?
> > 
> > Just the ability to trigger such custom script on "flutter build"
> 
> https://github.com/flutter/flutter/issues/112727 describes a system for running custom code at build time.

Oh, sorry. Then this looks like a dupe
