### ISSUE TITLE
[go router] add roadmap link to readme 

### ISSUE THREAD

**Issue by momrak** [flutter/flutter#113372]
**Question**
Is there some place to see the roadmap or the direction go_router will be taken now after development is done by the Flutter team?

I guess the `ShellRoute` was the first larger thing that was planned. It would be great to have an overview similar to the Dart Language Funnel https://github.com/dart-lang/language/projects/1 

Might be there is some place with this already, it is just a bit harder to find now that go_router lies under flutter/packages

**Comment by chunhtai** [comment]
We have created a project https://github.com/orgs/flutter/projects/17/views/1 to prioritize issues. We have not finish planning for Q4 so issue priority may change. The plan is to move issues we want to work on in the quarter to P0.

**Comment by chunhtai** [comment]
I will close this as fixed, feel free to reopen if you have more questions.

**Comment by momrak** [comment]
> We have created a project https://github.com/orgs/flutter/projects/17/views/1 to prioritize issues. We have not finish planning for Q4 so issue priority may change. The plan is to move issues we want to work on in the quarter to P0.

The URL takes me to a 404 page. Should it be open?

**Comment by chunhtai** [comment]
It is public now, let me know if you still can't see it.

**Comment by momrak** [comment]
It works now. Thank you!

Maybe it could be linked to in the Readme or something so that it was easy for people to find?

**Comment by chunhtai** [comment]
good idea
