### ISSUE TITLE
Flutter firebase assertion by filing a bug 

### ISSUE THREAD

**Issue by kabirinfoga** [flutter/flutter#113383]
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by iapicca** [comment]
@kabirinfoga if it'a an issue with firebase maybe should be opened [here](https://github.com/firebase/flutterfire/issues)

**Comment by stuartmorgan** [comment]
@kabirinfoga You have been asked [twice](https://github.com/flutter/flutter/issues/113071) [before](https://github.com/flutter/flutter/issues/111814) not to file empty issue reports.
