### ISSUE TITLE
Convert AnimatedList to a sliver

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#11339]
AnimatedList uses a pattern we know is bad: it provides the scroll view. This means, for example, that there's no way to combine the AnimatedList with a SliverGrid.

We should refactor AnimatedList to be a SliverAnimatedList.

cc @HansMuller

**Comment by passsy** [comment]
I'd love to have an `AnimatedGrid` to build things like this: 

![https://github.com/ollija/react-native-sortable-grid](https://camo.githubusercontent.com/92da15984757b6f2233e8a6b69c9e0e060d154f0/687474703a2f2f692e67697068792e636f6d2f67634238595956744c324273412e676966)

**Comment by passsy** [comment]
//cc @HansMuller

**Comment by goderbauer** [comment]
We should re-apply https://github.com/flutter/flutter/pull/28834, which adds a SliverAnimatedList, but was reverted due to a merge conflict.

@passsy  that sounds like a separate feature request. You probably want to file a new feature request for that.
