### ISSUE TITLE
onResume and onMessage mixed up

### ISSUE THREAD

**Issue by ZhangBanger** [flutter/flutter#11333]
## Steps to Reproduce

Flutter is firing an onResume when the app is foregrounded and onMessage when the app is backgrounded. The behavior isn't consistent.

## Logs
...coming back from background
I/flutter (28252): onMessage: {profileId: 

Run `flutter analyze` and attach any output of that command also.

## Flutter Doctor

/home/andy/code/flutter/bin/flutter --no-color doctor
[✓] Flutter (on Linux, locale en_US.UTF-8, channel alpha)
    • Flutter at /home/andy/code/flutter
    • Framework revision d36e2f6191 (4 weeks ago), 2017-06-21 15:09:10 -0700
    • Engine revision b0dee695ec
    • Tools Dart version 1.24.0-dev.6.7

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at /home/andy/Android/Sdk
    • Platform android-25, build-tools 25.0.3
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] Android Studio (version 2.3)
    • Android Studio at /opt/android-studio
    • Gradle version 3.2
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Ultimate Edition (version 2017.2)
    • Flutter plugin version 15.1
    • Dart plugin version 172.3317.48

[✓] Connected devices
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 7.0 (API 24) (emulator)

Process finished with exit code 0

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by Hixie** [comment]
What are onResume and onMessage?

**Comment by ZhangBanger** [comment]
My mistake, meant to post this in flutter plugins.
