### ISSUE TITLE
Expose RenderEditable painter to EditableText

### ISSUE THREAD

**Issue by liangxianzhe** [flutter/flutter#113308]
## Use case

I'm using EditableText/TextFeild in multi-user collaborative editing, and I hope to show multiple blinking cursors, similar to Google docs.

## Proposal

After reading all related source code, I found that RenderEditable has two parameters [`painter` and `foregroundPainter`](https://github.com/flutter/flutter/blob/18a827f393/packages/flutter/lib/src/rendering/editable.dart#L281-L282), which are not used by any framework widgets. I feel these two parameters are designed for such use cases.

The problem is in order to use these two parameters, I have to fork and maintain a forked EditableText and TextField. Would it make sense to expose these two parameters to EdtiableText and maybe TextField, like [this](https://github.com/liangxianzhe/flutter/commit/ebe614f3e8e514fe2c4ea6b30741b47593078406)? Thanks!

**Comment by justinmc** [comment]
CC @LongCatIsLooong

**Comment by LongCatIsLooong** [comment]
Since you already have a working implementation do you mind opening a PR and upstreaming the changes? Also one thing of note is that currently the logic for computing the cursor location is optimized for only one cursor -- multiple cursors would constantly invalidate the cache.

**Comment by liangxianzhe** [comment]
Thanks for the reply. Will send out a PR soon. 

As for the cache invalidation, how about adding a boolean parameter like `useCache` to `RenderEditable.getLocalRectForCaret` and `TextPainter.getOffsetForCaret`? Otherwise, I will eat the cost. It seems not super expensive.

**Comment by liangxianzhe** [comment]
Closing since @LongCatIsLooong says a better API is WIP https://github.com/flutter/flutter/pull/129895#issuecomment-1666160326
