### ISSUE TITLE
 Flutter API Documentation WEBPAGE BUG

### ISSUE THREAD

**Issue by skillkrio** [flutter/flutter#113387]
The footer of the webpage are placed at center of the page and only half screen is visible. Hard to read the documentation
![webbug](https://user-images.githubusercontent.com/30119763/195629824-8ea44029-f704-4603-ad73-1e7ca3e5420d.png)

**Comment by iapicca** [comment]
@skillkrio if the issue is about the website maybe could be posted [here](https://github.com/flutter/website/issues)

**Comment by skillkrio** [comment]
The pr made on different page
