### ISSUE TITLE
Tree closed on repo checkout failures

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#113360]
For example https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_ios%20complex_layout_scroll_perf_ios__timeline_summary/7421/overview.

**Comment by zanderso** [comment]
cc @godofredoc

**Comment by drewroengoogle** [comment]
@godofredoc I'm not sure I understand how flutter commits in github are also applied to https://flutter.googlesource.com/mirrors/flutter/, but this specific [commit](https://github.com/flutter/flutter/commit/c738c8aa961670929f90124ace71b7d9b263e002) does not seem to be reflected in the mirror at all.

**Comment by godofredoc** [comment]
Is already there https://flutter.googlesource.com/mirrors/flutter/+/c738c8aa961670929f90124ace71b7d9b263e002

**Comment by drewroengoogle** [comment]
> Is already there https://flutter.googlesource.com/mirrors/flutter/+/c738c8aa961670929f90124ace71b7d9b263e002

This morning Keyong manually triggered the copy over to GoB, so I'm curious to see if this was an outage of some sort of if there is still an issue going on.

**Comment by keyonghan** [comment]
This is the tracking bug: b/253442727
Manually landed https://github.com/flutter/flutter/pull/113389 to green the tree.

**Comment by keyonghan** [comment]
Uh.. the newly landed commit was not mirrored to Gob neither.. Bumping the gob bug.

**Comment by drewroengoogle** [comment]
The issue was found and it looks like it was resolved.

There was a CL that moved the config file that copies git commits to GoB, and by moving the config file it unregistered the automatic process. We registered the config file again and it looks like the most recent commit is back to green. Will look to close tomorrow assuming the tree stays green.

**Comment by drewroengoogle** [comment]
Commits have been moving to GoB as expected - resolving this! Feel free to reopen if this changes.
