### ISSUE TITLE
Framework invocations of saveLayer should show the checkerboard diagnostic

### ISSUE THREAD

**Issue by jason-simmons** [flutter/flutter#11332]
Some rendering objects in the framework Dart code may call Canvas.saveLayer (notably ClipRRect and PhysicalModel with a rounded rectangle shape).

The framework's usage of saveLayer doesn't currently support the checkerboardOffscreenLayers diagnostic flag.  We should make the framework draw the checkerboard in these cases.

@chinmaygarde

**Comment by Hixie** [comment]
@chinmaygarde Do you still want this?

**Comment by chinmaygarde** [comment]
Yes please.

**Comment by Hixie** [comment]
We ditched the checkerboard features, so closing this.
