### ISSUE TITLE
Continually scrolling a long list in iOS is unnatural (compared to OEM)

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#11338]
Comparing a very recent build of the Gallery (three days ago?) on iOS, compared to GMail on iOS with a long list of emails:

* In Gmail, I can continually flick my thumb up and keep up the velocity of the scrolling.
* In Gallery home screen, often times a flick up seems to "restart" the scroll. The velocity isn't kept up, it's almost like it's restarting.

This was on an iPhone 6S.

**Comment by sethladd** [comment]
cc @xster

**Comment by xster** [comment]
Deduping into #11066
