### ISSUE TITLE
`Slider` thumb overlay doesn't behave properly on desktop

### ISSUE THREAD

**Issue by TahaTesser** [flutter/flutter#113367]
### Description

When working on https://github.com/flutter/flutter/issues/111451, I found `Slider` doesn't behave properly on desktop platforms.
It behaves as it does on mobile, while `Slider` is slightly different in behavior on desktop. 

This is a comparison between Flutter and [MWC Slider demo](https://material-components.github.io/material-web/demos/slider/).

### 1.  Unfocused `Slider` shows thumb overlay when hovering outside the thumb.

When `Slider` is initially unfocused,  hovering outside the thumb area brings the thumb overlay.

#### Material Web

https://user-images.githubusercontent.com/48603081/195550171-be4d8b15-e27e-4711-a2bb-da74bf4cf81a.mov

#### Flutter

https://user-images.githubusercontent.com/48603081/195550204-13a14d2a-add2-4d57-a654-c17ca7f4ccbe.mov

#### Material Web

https://user-images.githubusercontent.com/48603081/195550906-5f1bd761-669d-44cc-8a2b-9f16af0e3206.mov

#### Flutter

https://user-images.githubusercontent.com/48603081/195550963-61084eb2-1a02-4532-a8a3-044ae9ed7d6b.mov

**Comment by exaby73** [comment]
Hello @TahaTesser. Thank you for the detailed issue. Labelling it for the team to take further.
