### ISSUE TITLE
Remove default podFile setting of use_frameworks!

### ISSUE THREAD

**Issue by bohowu** [flutter/flutter#113369]
## Use case

create sample flutter project
check podFile setting, there is use_frameworks! in setting

After remove use_frameworks!, launch time improve dramatically. Because my app depends on many packages.

## Proposal

Remove the use_frameworks! for podFile
Since CocoaPods support swift static libraries after 1.5.0.
And Apple recommended use a max of 6 dynamic frameworks, remove use_frameworks! for default use static libraries seems better.

I refer to the article
https://bpoplauschi.github.io/2021/10/25/Advanced-static-vs-dynamic-libraries-and-frameworks.html
for the max of 6 dynamic frameworks saying.

Thank you.

**Comment by dodatw** [comment]
I have same experience.
After remove use_frameworks! in PodFile. 
The cold start improve dramatically.

This setting is come from sample project.
Is there any side effect to use static library on flutter project ?

**Comment by darshankawar** [comment]
Keeping this issue open for further insights from the team on this potential proposal.

/cc @jmagman

**Comment by jmagman** [comment]
It's not on by default in Objective-C Flutter projects.  However, we err on the side of keeping the app compiling in all cases, and we've seen issues with static Swift libraries, so it's on by default there.

You should feel free to remove it in your own project if you want and it works.

**Comment by dodatw** [comment]
> It's not on by default in Objective-C Flutter projects. However, we err on the side of keeping the app compiling in all cases, and we've seen issues with static Swift libraries, so it's on by default there.
> 
> You should feel free to remove it in your own project if you want and it works.

Wow, could you help share which kind issue you seen with static Swift libraries?
We are switched to static library, It maybe have potential issue.

**Comment by jmagman** [comment]
> We are switched to static library, It maybe have potential issue.

If it compiles it's unlikely you're hitting any issues.

https://github.com/flutter/flutter/issues/25676#issuecomment-532464440

Our `create` templates prefer do the safest rather than the optimal so our users don't get stuck debugging inscrutable module or missing resource errors. However you are welcome to edit the Podfile and Xcode projects, as long as you don't remove the bits that actually inject Flutter into your app.
