### ISSUE TITLE
Haytifx

### ISSUE THREAD

**Issue by scorpion-4128** [flutter/flutter#113351]
Il m'arrive une chose dans mon projet. une fois que je veux lancer ca sur l emulateur Android voicice qu'on dit:

Launching lib\main.dart on Android SDK built for x86 in debug mode...
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Failed to find Build Tools revision 29.0.2

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 29s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by huycozy** [comment]
@scorpion-4128 
Please see these StackOverflow answers for more details:
- https://stackoverflow.com/questions/62778318/failed-to-find-build-tools-revision-29-0-2-android-studio
- https://stackoverflow.com/questions/69167522/error-could-not-determine-the-dependencies-of-task-appcompiledebugjavawithja

Closing as this is neither a Flutter bug nor a feature request. If you disagree, please write in the comments and I will reopen it.
