### ISSUE TITLE
pubspec.yaml platform dependencies error

### ISSUE THREAD

**Issue by zjrwdl** [flutter/flutter#113311]
We are parsing flutter app size with cmd  "flutter build apk --analyze-size " and get result below:

...
package:dbus                                                        183 KB
...

dbus plugin is not as expected, so we checked  plugin dependecies:

|-- connectivity_plus 2.2.2
|   |-- connectivity_plus_linux 1.3.1
|   |   |-- connectivity_plus_platform_interface...
|   |   |-- flutter...
|   |   |-- meta...
|   |   '-- nm 0.5.0
|   |       '-- dbus 0.7.3
|   |           |-- args...
|   |           |-- ffi...
|   |           |-- meta...
|   |           '-- xml...

**_the problem is that why android apk contains linux plugin._**

we checked connectivity_plus plugin pubspec.yaml  describles as :
https://github.com/fluttercommunity/plus_plugins/blob/main/packages/connectivity_plus/connectivity_plus/pubspec.yaml

<img width="568" alt="image" src="https://user-images.githubusercontent.com/6874049/195251770-73830584-fbbe-483c-b90a-bc83d8357216.png">

according to officail docs , only linux app can find connectivity_plus_linux, however why android apk packaged linux plugin.https://docs.google.com/document/d/1LD7QjmzJZLCopUrFAAE98wOUQpjmguyGTN2wd_89Srs

so i guess it would be some error with dependencies process which is not match with official docs description.

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.5, on macOS 11.6 20G165 darwin-x64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

**Comment by exaby73** [comment]
## Triage report

I can reproduce this issue. The steps I took:

1. Create a new Flutter app
1. Add `connectivity_plus` (possibly any plugin that supports linux) via `flutter pub add connectivity_plus`
1. Run `flutter build apk --analyze-size --target-platform android-arm64`

<details>
<summary>Logs from step 3</summary>

```
app-release.apk (total compressed)                                          6 MB
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  META-INF/
    CERT.SF                                                                 3 KB
    CERT.RSA                                                              1014 B
    MANIFEST.MF                                                             2 KB
  classes.dex                                                             267 KB
  lib/
    arm64-v8a                                                               6 MB
    Dart AOT symbols accounted decompressed size                            3 MB
      package:flutter                                                       2 MB
      dart:core                                                           246 KB
      dart:ui                                                             203 KB
      dart:typed_data                                                     177 KB
      dart:collection                                                      98 KB
      dart:async                                                           76 KB
      dart:ffi                                                             59 KB
      dart:convert                                                         50 KB
      dart:io                                                              38 KB
      dart:isolate                                                         23 KB
      package:vector_math/
        vector_math_64.dart                                                23 KB
      dart:developer                                                        7 KB
      dart:math                                                             2 KB
      package:issue_113311/
        main.dart                                                           2 KB
      file:/
        /
          /
            C:/
              Users/
                Nabeel/
                  dev/
                    nevercode/
                      issue_113311/
                        .dart_tool/
                          flutter_build/
                            dart_plugin_registrant.dart                    787 B
      package:plugin_platform_interface/
        plugin_platform_interface.dart                                     756 B
      package:collection/
        src/
          priority_queue.dart                                              703 B
      dart:vmservice_io                                                    634 B
      package:connectivity_plus_linux/
        src/
          connectivity.dart                                                484 B
      package:connectivity_plus_platform_interface/
        connectivity_plus_platform_interface.dart                          479 B
  assets/
    flutter_assets                                                        199 KB
  AndroidManifest.xml                                                       1 KB
  res/
    CG.png                                                                  1 KB
  resources.arsc                                                           23 KB
  kotlin/
    collections                                                             1 KB
    kotlin.kotlin_builtins                                                  4 KB
    reflect                                                                 1 KB
```

</details>

From the above logs, you can see `connectivity_plus_linux` being included even though the plugin isn't being used in the application. If I am not wrong, this should have been removed during the tree shaking phase.

**Comment by stuartmorgan** [comment]
> this should have been removed during the tree shaking phase

Currently Dart doesn't support tree shaking on `Platform` conditionals.

**Comment by stuartmorgan** [comment]
@mraleph What is the specific customer request here? I was just keeping this open for docs; https://github.com/flutter/flutter/issues/99412 is tracking the core issue of including the code, which seems more likely to be what someone would care about being fixed.

**Comment by mraleph** [comment]
@stuartmorgan sorry, I missed that this is documentation specific issue. Labeled https://github.com/flutter/flutter/issues/99412 as `customer: penguin` as well. 

We are in process of looking at tree-shaking of platform specific code.

**Comment by zjrwdl** [comment]
> https://docs.google.com/document/d/1LD7QjmzJZLCopUrFAAE98wOUQpjmguyGTN2wd_89Srs/edi

https://docs.google.com/document/d/1LD7QjmzJZLCopUrFAAE98wOUQpjmguyGTN2wd_89Srs/edi

**Comment by zjrwdl** [comment]
> > the problem is that why android apk contains linux plugin.
> 
> There's no such thing as a platform-specific dependency at the Dart level. It's in your apk because, as shown in the lower red box in your screenshot, it's a dependency of the `connectivity_plus` package.
> 
> This is mostly a duplicate of #99412, but before closing it as such:
> 
> > according to officail docs , only linux app can find connectivity_plus_linux,
> 
> This is definitely not true, and we shouldn't have docs saying it is. Could you link to the specific documentation you are referring to?

https://docs.google.com/document/d/1LD7QjmzJZLCopUrFAAE98wOUQpjmguyGTN2wd_89Srs/edi

**Comment by stuartmorgan** [comment]
Could you quote the specific part you are referring to? I don't see that in the design doc.

**Comment by stuartmorgan** [comment]
The auto-close was correct; without knowing what docs say what the comments above say they claim (which I was unable to find), we can't update them.

**Comment by exaby73** [comment]
Okay thank you for the clarification. I reopened it based on the following comment since I though this issue still needed tracking.

> I was just keeping this open for docs; https://github.com/flutter/flutter/issues/99412 is tracking the core issue of including the code, which seems more likely to be what someone would care about being fixed.

**Comment by stuartmorgan** [comment]
Given an answer to my follow-up question about the docs issue it would need to be tracked as an issue to fix the docs, but without that information there's nothing actionable here.
