### ISSUE TITLE
Audio is not playing [video_player]

### ISSUE THREAD

**Issue by elRubenof** [flutter/flutter#113429]
When I play a video with video_player widget, it will play it with no sound because of the audio codec. I use remote videos with url.

![Left Playing Audio Right No Playing Audio](https://user-images.githubusercontent.com/52919665/195813622-d4cb71f5-e459-4609-bb28-d3c57aadec57.png)

* Left Image video is playing correctly with sound.
* Right Image, video is not playing sound.

The difference is the audio codec (mp4a / mega)

**Comment by darshankawar** [comment]
@elRubenof 
Can you provide `flutter doctor -v`, plugin version along with platform on which you are seeing this behavior ?
A minimal code sample would be helpful as well to analyze the issue properly.

Thanks.

**Comment by darshankawar** [comment]
> I use the flutter_video ^2.4.7 version.

This is actually `video_player` plugin name. Can you try with this https://pub.dev/packages/video_player_avfoundation plugin which is official ios implementation for video player and see if it helps in your case ?
