### ISSUE TITLE
Failed to package /Users/<user>/<project>    Command PhaseScriptExecution failed with a nonzero exit code

### ISSUE THREAD

**Issue by safaley** [flutter/flutter#113445]
Can anyone fix this issue ? I have been stuck since 3 days and can't find any solution anywhere. This happens to all the projects old, cloned and even new flutter project.I just can't run any app from Xcode but from andriod it would run.

Running Xcode build...                                                  
Xcode build done.                                           23.3s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **

Xcode's output:
↳
    Writing result bundle at path:
        /var/folders/y8/x1m1v9xx37535jrh1j4spr6m0000gn/T/flutter_tools.K7iiqX/flutter_ios_build_temp_dirXMtKLi/tempo
        rary_xcresult_bundle

    Failed to package /Users/safaley/StudioProjects/mi_card_flutter.
    Command PhaseScriptExecution failed with a nonzero exit code
    note: Building targets in dependency order
    warning: Run script build phase 'Run Script' will be run during every build because it does not specify any
    outputs. To address this warning, either add output dependencies to the script phase, or configure it to run
    in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'Runner' from
    project 'Runner')
    warning: Run script build phase 'Thin Binary' will be run during every build because it does not specify any
    outputs. To address this warning, either add output dependencies to the script phase, or configure it to run
    in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'Runner' from
    project 'Runner')

    Result bundle written to path:
        /var/folders/y8/x1m1v9xx37535jrh1j4spr6m0000gn/T/flutter_tools.K7iiqX/flutter_ios_build_temp_dirXMtKLi/tempo
        rary_xcresult_bundle

Could not build the application for the simulator.
Error launching application on iPhone SE (3rd generation).

**Comment by waleedzakria** [comment]
Not working for me also while building ios or ipa

**Comment by huycozy** [comment]
@safaley There are many reasons for failed build, so please try to provide more information so that we can verify the issue.

Firstly, does this issue happen with the default Flutter sample code? 
Also, please share the output of `flutter run -v`? If the log is too long, please save it into a file and attach it here.

@waleedzakria you might want to take a look at this issue #113260 if you're archiving ipa file.

**Comment by safaley** [comment]
[error.txt](https://github.com/flutter/flutter/files/9801716/error.txt)
@huycozy here is the file this issue also happen with default flutter sample and i have done reset reinstalled xcode nothing works.

**Comment by huycozy** [comment]
>[   +9 ms] Target debug_unpack_ios failed: Exception: Binary
               /Users/safaley/Desktop/flutter_projects/magic-8-ball-flutter/build/ios/Debug-iphonesimulator/Flutter.framework/Flutter does not exist, cannot thin

@safaley 
Thank for providing output logs. I see there's an open issue addressing the case you described #100438 and please take a look at https://github.com/flutter/flutter/issues/100438#issuecomment-1082276393.

Closing this issue as a duplicate, so please follow up on it for further updates. Thank you!
