### ISSUE TITLE
insufficient locking on mac when upgrading the sdk

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter#11348]
It looks like the locking we do in the `bin/flutter` script doesn't take effect on the mac:

https://github.com/flutter/flutter/blob/master/bin/flutter#L74

If so, we should add locking for the mac.

**Comment by mit-mit** [comment]
@devoncarew can you elaborate on what the effect of this is, and how to repro it?

**Comment by devoncarew** [comment]
The sdk can get corrupted if you start a flutter upgrade, that upgrade brings in a new dart sdk, and the sdk is already in use elsewhere.

**Comment by mit-mit** [comment]
OK, tagging milestone 3, we want to be stable.

**Comment by Hixie** [comment]
@devoncarew Are you aware of any way to do this on Mac?

**Comment by devoncarew** [comment]
I haven't done a lot of digging, but I don't think there's a native binary that does what we want. We might need to write a small C app, commit the binary into our repo, and call that from the `bin/flutter` script. /cc @xster @cbracken

**Comment by cbracken** [comment]
One option might be `shlock`, which ships with macOS. It's not quite identical either syntactically or semantically, but is designed for roughly the same purpose.

**Comment by jcollins-g** [comment]
I never miss an opportunity to write shell scripts. ;-)

One way to do this is to use hardlinks instead of flock/shlock.  That's portable on both platforms and atomic even on NFSv3.  A relatively small in-line shell implementation can then work for both and not require shipping a binary.

**Comment by jcollins-g** [comment]
shlock seems to be implemented using hardlinks, making it a suitable fallback.  I don't know if shlock is available on all relevant Linux platforms, so just to be safe I'll make this fall back to shlock when flock isn't present.

**Comment by jcollins-g** [comment]
Oh, and forgot to mention:  shlock also relies on PIDs which is not so good for shared NFS directories.  So, people upgrading the same flutter directory via NFS from two different Macs are still uncovered by locking with this proposal.  Still better than nothing, which is what Mac users currently have.
