### ISSUE TITLE
horizontal drags are detected on gesture detector vertical drag callbacks

### ISSUE THREAD

**Issue by dipakp2726** [flutter/flutter#113416]
## description
i am draging horizontal but i am receiving callbacks at gesture detectors vertical drag callbacks

reproducible code
```
testWidgets('Should not detect horizontal drags', (tester) async {
    var dragStarted = 0;
    var dragDown = 0;
    var dragUpdated = 0;
    var dragEnd = 0;
    var dragCancel = 0;

    await tester.pumpWidget(
      GestureDetector(
        onVerticalDragCancel: () {
          dragCancel++;
        },
        onVerticalDragDown: (details) {
          dragDown++;
        },
        onVerticalDragStart: (details) {
          dragStarted++;
        },
        onVerticalDragEnd: (details) {
          dragEnd++;
        },
        onVerticalDragUpdate: (details) {
          dragUpdated++;
        },
      ),
    );

    await tester.dragFrom(const Offset(10, 10), const Offset(50, 10));

    expect(dragDown, 1);
    expect(dragStarted, 1);
    expect(dragEnd, 1);
    // expect(dragCancel, 1);
    expect(dragUpdated, 2);
  });

```

## expected behaviour
should not receive horizontal drags

## actual behaviour
it receives callback on horizontal drag

**Comment by huycozy** [comment]
@dipakp2726 
You can try adding this horizontal callback to see its tests run as expected:

<details>
<summary>Sample code</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  testWidgets('Should not detect horizontal drags', (tester) async {
    var dragStarted = 0;
    var dragDown = 0;
    var dragUpdated = 0;
    var dragEnd = 0;
    var dragCancel = 0;
    var dragHozUpdate = 0;

    await tester.pumpWidget(
      GestureDetector(
        onVerticalDragCancel: () {
          dragCancel++;
        },
        onVerticalDragDown: (details) {
          dragDown++;
        },
        onVerticalDragStart: (details) {
          dragStarted++;
        },
        onVerticalDragEnd: (details) {
          dragEnd++;
        },
        onVerticalDragUpdate: (details) {
          dragUpdated++;
        },
        onHorizontalDragUpdate: (details) {
          dragHozUpdate++;
        },
      ),
    );

    await tester.dragFrom(const Offset(10, 10), const Offset(50, 10));

    expect(dragDown, 1);
    expect(dragStarted, 1);
    expect(dragEnd, 1);
    // expect(dragCancel, 1);

    expect(dragUpdated, 2);
    // expect(dragHozUpdate, 0);

  });

}
```
</details>

**Comment by dipakp2726** [comment]
i did its not working as expected

**Comment by dipakp2726** [comment]
in above code it should receive dragHozUpdate instead of dragUpdated ,but it receives dragUpdated

**Comment by huycozy** [comment]
@dipakp2726 
This is the test result when there is only `dragUpdated` check from my side:

<details>
<summary>Sample test code (updated)</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  testWidgets('Should not detect horizontal drags', (tester) async {
    var dragStarted = 0;
    var dragDown = 0;
    var dragUpdated = 0;
    var dragEnd = 0;
    var dragCancel = 0;
    var dragHozUpdate = 0;

    await tester.pumpWidget(
      GestureDetector(
        onVerticalDragCancel: () {
          dragCancel++;
        },
        onVerticalDragDown: (details) {
          dragDown++;
        },
        onVerticalDragStart: (details) {
          dragStarted++;
        },
        onVerticalDragEnd: (details) {
          dragEnd++;
        },
        onVerticalDragUpdate: (details) {
          dragUpdated++;
        },
        onHorizontalDragUpdate: (details) {
          dragHozUpdate++;
        },
      ),
    );

    await tester.dragFrom(const Offset(10, 10), const Offset(50, 10));

    // expect(dragDown, 1);
    // expect(dragStarted, 1);
    // expect(dragEnd, 1);
    // expect(dragCancel, 1);

    expect(dragUpdated, 2);
    // expect(dragHozUpdate, 0);

  });

}
```
</details>

<details>
<summary>Test result</summary>

```bash
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure was thrown running a test:
Expected: <2>
  Actual: <0>
```
</details>

Can you share your test result? Also, which Flutter version are you using? Please provide the output of `flutter doctor -v` as well.

**Comment by dipakp2726** [comment]
i rechecked my results are also same.

**Comment by dipakp2726** [comment]
but it only works when i have both horizontal and verticle detecotors,

doest work when i have only horizontal/verticle detecotors

**Comment by goderbauer** [comment]
@Piinks

**Comment by drown0315** [comment]
```
    // Returns if the drag is horizontal
    if (details.delta.dx.abs() > details.delta.dy.abs()) return;
```
dx.abs > dy.abs recognized as horioznal drag and dy. abs > dx.abs recognized as vertical drag seems properly.

**Comment by drown0315** [comment]
![image](https://user-images.githubusercontent.com/108989782/218994973-100b4201-21d2-4a53-8b19-9b1566dc21ca.png)
reference by: https://docs.flutter.dev/development/ui/advanced/gestures#gesture-disambiguation

The current official document defines gesture recognition as above.

**Comment by Renzo-Olivares** [comment]
Hi @dipakp2726, thanks for reporting this issue. The main reason that you are experiencing this behavior when using only one either vertical/horizontal callbacks is because the gesture automatically wins the gesture arena because there are no other gestures competing with it so the gesture arena automatically declares it the winner. When you add both vertical/and horizontal callbacks the behavior works as expected because the gestures are competing in the arena, only declaring victory when the threshold on the axis has been met.

One thing you can do is set `onlyAcceptDragOnThreshold` property of `DragGestureRecognizer` to `true`, and this will achieve the behavior you are expecting using only one horizontal/or vertical callbacks. One note is that you will have to use `RawGestureDetector` and pass it the recognizers you want to support. Let me know if this solves your issue.
