### ISSUE TITLE
Xcode 14.0.1 iOS 16 - Flutter app opens to blank white screen

### ISSUE THREAD

**Issue by globemediaofficial** [flutter/flutter#113489]
```
Analyzing ios...                                                        
No issues found! (ran in 4.9s)
```

```
[✓] Flutter (Channel stable, 3.3.4, on macOS 12.6 21G115 darwin-x64, locale en-US)
    • Flutter version 3.3.4 on channel stable at /Users/cjm/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision eb6d86ee27 (11 days ago), 2022-10-04 22:31:45 -0700
    • Engine revision c08d7d5efc
    • Dart version 2.18.2
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/cjm/Library/Android/sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.67.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.32.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.6 21G115 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 106.0.5249.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>
I have been using flutter for a couple years now so I've come across blank screens before. What usually works is to delete the iOS folder, use "flutter create ." in the project folder, and run the app. However, that didn't fix it this time. I also deleted the app on my device and re-installed it. Still, the app launches to a blank white screen. No matter how long it sits open, the white screen stays. When I build it in Xcode and the app launches, nothing is printed in the debugging console, not even an error. It stays blank. I tried updating the Flutter SDK and tried all three channels but that didn't fix it. When I run the app on web through android studio it works as expected so I think something is wrong with Runner on iOS. The app worked fine on iOS before Xcode 14 and iOS 16 so that likely has something to do with the issue.

**Comment by exaby73** [comment]
Hello @globemediaofficial. Thank you for filing this issue. Can you please provide the following information?

- A [complete and minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). Ideally, a single `main.dart` file that can be run directly.
- The output of `flutter doctor -v`
- The output of `flutter run-v`

Please provide the information in the form of text. See how to make collapsible sections with Markdown [here](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-collapsed-sections).

**Comment by HuuCodelight** [comment]
@globemediaofficial Faced the same issue,
upgrade from flutter 3.3.4 -> 3.3.5 and it's Works

**Comment by globemediaofficial** [comment]
@HuuCodelight i did upgrade flutter but even that didn’t fix it. Turns out it was probably never an issue with Flutter… I deleted the iOS Support folder in the Xcode directory and the next time I ran the app it worked. Something was wrong with the iOS 16 support files.
