### ISSUE TITLE
Screen data rebuild itself from parent when the app opens from background

### ISSUE THREAD

**Issue by Emad403** [flutter/flutter#113490]
After navigating from one page to another (this only happens when there are at least 2 pages in the navigation stack) and passing some data to the child page if you put the app in the background and move open it again the data is recreated from parent page and any change that happened in the child page will be lost

```
Navigator.push(
  MainRouter.mainNavigatorKey.currentContext!,
  MaterialPageRoute(
    builder: (context) => CategoryDetailScreen(
      isCompany: false,
      model: samplelModel,
      connectionColor: ffffff,),
  ),
);
```
Step to reproduce 
1. Navigate from one screen to another with parameters
2. Change the data on the second screen (widget.isCompany = true)
3. Minimize the app
4. open the app again
the navigation from the parent screen gets called again(the above code) and this makes the widget.isCompany false again 
this only happens when the navigation stack has more than 2
screen 1 -> screen 2 works fine
screen 1 -> screen 2 -> screen 3 this one is not  

Flutter (Channel stable, 3.3.2, on macOS 12.6 21G115 darwin-x64, locale en-US)
    • Flutter version 3.3.2 on channel stable at 
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e3c29ec00c (4 weeks ago), 2022-09-14 08:46:55 -0500
    • Engine revision a4ff2c53d8
    • Dart version 2.18.1
    • DevTools version 2.15.0

**Comment by exaby73** [comment]
Hello @Emad403. Thank you for filing this issue. Can you please provide the following information?

- A [complete and minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). Ideally, a single `main.dart` file that can be run directly.
- The output of `flutter doctor -v`
- The output of `flutter run-v`

Please provide the information in the form of text. See how to make collapsible sections with Markdown [here](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-collapsed-sections).
