### ISSUE TITLE
Regarding Zoom In and Out

### ISSUE THREAD

**Issue by Avinash-kommareddy** [flutter/flutter#113492]
Hi Team,

I am using this plugin in flutter, using IPhone 13 pro max, while zoom in and out it is zooming too late, is there any option to do.

**Comment by darshankawar** [comment]
@Avinash-kommareddy 
Which plugin are you refering to ? 
Your question is better suited for support channels like StackOverflow, so please ask the same there. If you find any genuine issue with the flutter first party plugin you are using, please open new issue using template and fill out requested details.

Closing for now.
