### ISSUE TITLE
[go_router]Using Shell router subroutes with same parent key

### ISSUE THREAD

**Issue by edcogue** [flutter/flutter#113406]
I'm trying to use shell router with a subroutes using the root navigator key (because I want to display any of these screens on top of the one with shell route. The router is coded as follows:
```dart
final GlobalKey<NavigatorState> _rootNavigatorKey =
    GlobalKey<NavigatorState>(debugLabel: 'root');
final GlobalKey<NavigatorState> _shellNavigatorKey =
    GlobalKey<NavigatorState>(debugLabel: 'shell');

class AppRouter {
  static final router = GoRouter(
    // redirect: ((context, state) => "/first"),
    initialLocation: "/first",
    navigatorKey: _rootNavigatorKey,
    routes: [
      ShellRoute(
          navigatorKey: _shellNavigatorKey,
          builder: (context, state, child) {
            return HomePage(child: child);
          },
          routes: [
            GoRoute(
                parentNavigatorKey: _rootNavigatorKey,
                path: "/first",
                pageBuilder: (context, state) =>
                    const NoTransitionPage(child: NavigateToListPage()),
                routes: [
                  GoRoute(
                      path: "itemslist",
                      builder: (context, state) => ItemListPage(),
                      routes: [
                        GoRoute(
                          parentNavigatorKey: _rootNavigatorKey,
                          path: "item",
                          builder: (context, state) =>
                              ItemPage(product: state.extra as Product),
                        )
                      ])
                ]),
            GoRoute(
              path: "/second",
              pageBuilder: (context, state) =>
                  const NoTransitionPage(child: BottomMenuPage()),
            ),
            GoRoute(
              path: "/third",
              pageBuilder: (context, state) =>
                  const NoTransitionPage(child: BottomMenuSecondPage()),
            ),
          ])
    ],
  );

```
These code is not working because it says that the parentNavigatorKey of the routes are the same. The main goal is to displayed both /first/itemlist and /first/itemlist/item on top of widget inside shellroute. Is there any way to do it using shell route?

**Comment by exaby73** [comment]
Hello @edcogue . Thank you for filing this issue. Can you please provide the following information?

- A [complete and minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). Ideally, a single `main.dart` file that can be run directly.
- The output of `flutter doctor -v`
- The output of `flutter run-v`
- `go_router` version

Please provide the information in the form of text. See how to make collapsible sections with Markdown [here](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-collapsed-sections).
