### ISSUE TITLE
Use `git gc` when packaging for download

### ISSUE THREAD

**Issue by kevmoo** [flutter/flutter#113401]
`git gc --prune=now --aggressive` saves over 100MB

It's slow, but likely worth it!

See https://git-scm.com/docs/git-gc

**Comment by CaseyHillers** [comment]
https://cs.opensource.google/flutter/flutter/+/master:dev/bots/prepare_package.dart can be updated to prune the repo. I'm currently running some benchmarks if there's anything more optimal than the defaults in `git gc`.

One example, I think we can remove commit objects which would get the `.git` from 190MB to <1MB

\cc @christopherfujino

**Comment by CaseyHillers** [comment]
We could do `git clone --depth 1` to remove all the extra commits. However, users that want to become contributors will need to run a `git fetch --all` to get the missing refs.

**Comment by christopherfujino** [comment]
> We could do `git clone --depth 1` to remove all the extra commits. However, users that want to become contributors will need to run a `git fetch --all` to get the missing refs.

I'm pretty sure we explicitly cannot do this, there are certain git operations that we call that will fail if you're in a shallow clone. I can't remember them off the top of my head. I **think** we could potentially do it after https://github.com/flutter/flutter/issues/112833 is implemented, though.

`git gc --prune=new --aggressive` SGTM though!

**Comment by christopherfujino** [comment]
> `git gc --prune=new --aggressive` saves over 100MB
> 
> It's slow, but likely worth it!

cc @godofredoc, who I know would like to speed up packaging.

**Comment by kevmoo** [comment]
FYI: should be `--prune=now` 😄 
Also FYI: depending on the machine, `gc --aggressive` can be MINUTES. Not sure how much that matters.

**Comment by godofredoc** [comment]
This is great! I'm definitely up for anything making packaging faster.

**Comment by christopherfujino** [comment]
Unfortunately running this would actually make the packaging slower, and I was wondering if that would be a deal breaker.

**Comment by CaseyHillers** [comment]
It's a bad comparison, but on my M1 mac it takes <1 min to run. Since it's an O(minutes) I think the trade offs are reasonable, and I'll continue to investigate ways we can shrink the packages.

**Comment by CaseyHillers** [comment]
This is implemented in this weeks release.

Previous: https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8801128044821647073/+/u/prepare__create_and_publish_a_flutter_archive/stdout

New: https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8799839059726138433/+/u/prepare__create_and_publish_a_flutter_archive/stdout

It saved 100MB+ of space on Mac, and doesn't have a noticeable impact on the packaging time.
