### ISSUE TITLE
Sliding page transitions in the body of adaptive_layout trample the primary navigation

### ISSUE THREAD

**Issue by oravecz** [flutter/flutter#113435]
## Steps to Reproduce

Sorry that I don't have reproducible code that I can share. I am using go_router's ShellRoute to apply an `AdaptiveLayout`, and the body of the adaptive layout are subroutes in my ShellRoute.

I noticed the examples for `AdaptiveScaffold` or `AdaptiveLayout` animate the body in place via a FadeTransition, and this works well for me. But as soon as I animate the body using a SlideTransition (the default when running on MacOS or iOS), the body slides out to the left and when it gets to the NavigationRail in the primary navigation slot, animates over the top. 

I have tries setting the body to a Scaffold, and tried not using a Scaffold. When it is a Scaffold, the animation looks a bit cleaner, but the AppBar runs over the primary navigation.

Hoping this description and the accompanying video demonstrates the problem sufficiently to indicate where to look for the problem.

(This movie has audio describing the problem)

https://user-images.githubusercontent.com/297712/195868316-c7b9906f-1150-46ef-99a9-d8b7236ed0b1.mov

<details>

fvm flutter doctor -v

```
[✓] Flutter (Channel stable, 3.3.1, on macOS 12.5.1 21G83 darwin-arm, locale en-US)
    • Flutter version 3.3.1 on channel stable at /Users/jimcook/fvm/versions/3.3.1
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4f9d92fbbd (5 weeks ago), 2022-09-06 17:54:53 -0700
    • Engine revision 3efdf03e73
    • Dart version 2.18.0
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/jimcook/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 70.0.5
    • Dart plugin version 222.4167.21

[✓] VS Code (version 1.54.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (3 available)
    • iPhone 14 Pro Max (mobile) • 7AD961F4-7448-4C6D-8412-EE94538CEAC7 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-0 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 12.5.1 21G83 darwin-arm
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 106.0.5249.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by huycozy** [comment]
Hi @oravecz 
Can you share a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that's showing on your demo video? (It looks like a minimal sample code)

Also, which `flutter_adaptive_scaffold` version are you using? And please retry on the latest Flutter stable and master channel to see if the issue still reproduces.
