### ISSUE TITLE
The Flutter web dev experience keeps forcing me back to `/` 

### ISSUE THREAD

**Issue by atrauzzi** [flutter/flutter#113484]
## Steps to Reproduce

 - Use `usePathUrlStrategy();`
 - Use `go_router` with a single non-root (`/`) route
 - Run your project as a web project
 - Attempt to navigate to a URI other than `/`
 - The desired route will be correctly shown, however...
 - ...depending on how fast your system is, the client will renavigate to `/` without any user activity, making it impossible to access any route other than root

[Screencast from 2022-10-15 08:47:05 AM.webm](https://user-images.githubusercontent.com/115199/195989942-1e6ae573-9b47-4434-b82b-bf6388c00d39.webm)

---

Interestingly, if I go to my regular Chrome browser and visit the exact same route, I'm never redirected.  So this feels like some kind of glitch in either the debugging experience, or the bundled chromium browser.

Sidenote: If the `web-server` target was still an option in android studio for debugging, I'd simply use that to get around this, but unfortunately, [this option was unceremoniously removed](https://github.com/flutter/flutter/issues/75088).

---

Some additional information:

  - If I put `initialLocation` to be `/login` and then navigate to `/login?client_id=zxczxc123`, I'm eventually bumped back to `/login`.  Is this a bug in `go_router`?

**Comment by exaby73** [comment]
Hello @atrauzzi. Thank you for filing this issue. Can you please provide the following information?

- A [complete and minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). Ideally, a single `main.dart` file that can be run directly.
- The output of `flutter doctor -v`

Please provide the information in the form of text. See how to make collapsible sections with Markdown [here](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-collapsed-sections).

**Comment by atrauzzi** [comment]
Sorry, I don't have time to scaffold all that together.

**Comment by exaby73** [comment]
Unfortunately, without a reproducible sample, we cannot take this issue any further. If you can, please do post one so that this issue can be verified.

**Comment by atrauzzi** [comment]
That's not always possible. I know it seems like standard practice, but it's not great for users who may not even know what's wrong to recreate their issue.

**Comment by exaby73** [comment]
> it's not great for users who may not even know what's wrong to recreate their issue.

I understand your point of view but please do understand that we do not provide support with users' code. The Github issues are for issue reports. There are many high priority issues so if an issue cannot be reproduced, it will unlikely to be picked up by someone to fix since there are other, reproducible and important issues in the backlog too. The reason I asked for a reproducible sample is because I couldn't reproduce it. If I can't, and you can provide a code sample, unfortunately, there is nothing for the team to act on.
