### ISSUE TITLE
Styling of the TabBar in the top toolbar of the Scaffold when use Material 3 theme

### ISSUE THREAD

**Issue by yegor-pelykh** [flutter/flutter#113482]
When use 'Material 3' theme mode, TabBar looks incompatible and Tab indicators have wrong color.

## Steps to Reproduce

1. Turn on Material 3 theme mode by setting `useMaterial3` flag of `ThemeData` to true
2. Set your color scheme

**Results:** TabBar looks incompatible and Tab indicators have wrong color.

Flutter version: 3.3.4

In fact, I don't even see the specs on the [Material 3 site](https://m3.material.io) for the TabBar (tabs in top App bar). But the fact is that the TabBar is already used in many applications. And the transition of these applications to Material 3 will be impossible without a total revision of the controls used.
By the way, I don't even see the suitable controls that could replace the Material 2 tabs in the top app toolbar.
What are your plans for these tabs and similar controls that are available in many applications, but unfortunately not described in the Material 3 specs?

Related to #91605.

**Comment by TahaTesser** [comment]
Hi @yegor-pelykh
`TabBar` currently doesn't support Material 3. The indicator color is a known [issue](https://github.com/flutter/flutter/issues/103642).
Closing as duplicate.
