### ISSUE TITLE
[flutter_adaptive_scaffold] Add fuchsia platform on mobile

### ISSUE THREAD

**Issue by fredgrott** [flutter/flutter#113497]
I am writing a set of articles on the flutter adaptive scaffold package and noticed a coding error in the breakpoints file:

`const Set<TargetPlatform> _desktop = <TargetPlatform>{
  TargetPlatform.fuchsia,
  TargetPlatform.linux,
  TargetPlatform.macOS,
  TargetPlatform.windows
};
const Set<TargetPlatform> _mobile = <TargetPlatform>{
  TargetPlatform.iOS,
  TargetPlatform.android
};
`

notice that there is no entry in mobile for fuchsia. Should there be an entry in mobile for the fuchsia platform since it runs on mobile platforms?

**Comment by huycozy** [comment]
@fredgrott Labeling this issue as a proposal. Thanks!

**Comment by a-wallen** [comment]
Fuchsia breaks our current model since it's the only `TargetPlatform` that's cross-platform. 
 
cc @gspencergoog, I think that we should remove the platform-specific logic from this package as it adds another dimension of adaptivity that will increase the complexity of this package.

**Comment by gspencergoog** [comment]
> Fuchsia breaks our current model since it's the only TargetPlatform that's cross-platform.

What about the web?  That's pretty cross-platform.

Aren't there small mobile (phones) and large mobile (tablets)?

**Comment by a-wallen** [comment]
> What about the web? That's pretty cross-platform.

Yeah, I totally forgot about that one.

> Aren't there small mobile (phones) and large mobile (tablets)?

Right. That's why I think we should remove concerns about the platform from the package. 

```dart
  /// A window whose width is less than 600 dp and greater than 0 dp.
  static const Breakpoint small = WidthPlatformBreakpoint(begin: 0, end: 600);

  /// A window whose width is greater than 0 dp.
  static const Breakpoint smallAndUp = WidthPlatformBreakpoint(begin: 0);

  /// Remove this.
  static const Breakpoint smallDesktop =
      WidthPlatformBreakpoint(begin: 0, end: 600, platform: _desktop);

  /// Remove this.
  static const Breakpoint smallMobile =
      WidthPlatformBreakpoint(begin: 0, end: 600, platform: _mobile);
```

**Comment by gspencergoog** [comment]
But might it be the case that you want things to adapt on a phone, but not adapt on a web page? I think we recently had a customer that found that the designers didn't like their adapting to the mobile size on the desktop, even though it was a better UI for the size of the window.

**Comment by a-wallen** [comment]
> But might it be the case that you want things to adapt on a phone, but not adapt on a web page (or a desktop app)? 

If we remove dimensions of platform adaptivity from the package, clients can still adapt to the platform.

Before (current):
```dart
SlotLayout(
  config: <Breakpoint, SlotLayoutConfig?>{
    Breakpoints.mediumMobile: SlotLayout.from(
      key: const Key('mobile'),
      builder: (_) {}
    ),
    Breakpoints.mediumDesktop: SlotLayout.from(
      key: const Key('desktop'),
      builder: (_) {}
    ),
  },
),
```

After removing breakpoints like `Breakpoints.mediumMobile` & `Breakpoints.mediumDesktop` in favor of no platform adaptivity.

```dart
SlotLayout(
  config: <Breakpoint, SlotLayoutConfig?>{
    Breakpoints.medium: SlotLayout.from(
      key: const Key('mobile'),
      builder: (_) {
	  	switch (TargetPlatform platform) {
			// here we are delegating platform adaptivity to the client rather than handling it in the library ourselves
        }
      }
    ),
  },
),
```

**Comment by gspencergoog** [comment]
As for the initial question posed in this issue, I think we probably should move Fuchsia to mobile, if only to keep it consistent with the testing infrastructure: currently `TargetPlatformVariant.mobile()` includes Fuchsia. You can argue that Fuchsia is both desktop and mobile, or neither, so I don't think it makes a practical difference.
