### ISSUE TITLE
Test ownership check failed.  Builders missing owner: [Mac verify_binaries_codesigned]

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#113473]
```
# Test ownership check failed.
Builders missing owner: [Mac verify_binaries_codesigned]
Please define ownership in https://github.com/flutter/flutter/blob/master/TESTOWNERS
```
Tree is closed.
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8800284695857286689/+/u/validate_test_ownership/stdout

Also seen in presubmit:
https://ci.chromium.org/p/flutter/builders/try/Linux%20test_ownership/1428?

Not sure why this only just started failing, this has been commented out forever
https://github.com/flutter/flutter/blob/a707d05e9d4c7ec95403444e04a65cd69c0da3b0/TESTOWNERS#L302

**Comment by drewroengoogle** [comment]
Does this line just need to be uncommented? I'm also confused why this just started failing.

**Comment by keyonghan** [comment]
The PR: https://github.com/flutter/cocoon/pull/2206 was reverted in https://github.com/flutter/cocoon/pull/2220.
Rerun passed, and tree is green. Lowering to P3.

/cc @ricardoamador could you help follow up with the culprit?

**Comment by ricardoamador** [comment]
Yes, I will take a look.

**Comment by ricardoamador** [comment]
The issue here is with using the protobuf wrappers is that when we get the targets they are filtered by the branch. So when we run the integration tests, etc, we cannot get the information for that target since the branch is a candidate branch.
