### ISSUE TITLE
showDatePicker - expose callback or change notifier when user changes entry mode (calendar / input)

### ISSUE THREAD

**Issue by mikeesouth** [flutter/flutter#113423]
## Use case

I'm using showDatePicker() to let users select dates in my application when they create objects, sometimes they create 20+ objects in a go and choose a date for each. The date picker allows us to set initial entry mode, like this: `initialEntryMode: DatePickerEntryMode.input` (input or calendar) and that's great. For most users I want "calendar" entry mode so I choose that as default. But if a user prefers input mode, then he/she creates the first object and switches from calendar entry mode to input entry mode by clicking the pen symbol.
![image](https://user-images.githubusercontent.com/18122438/195789744-a8ed463e-f5a1-4e6f-b60d-b4ded7f52973.png)

Then enters a date, closes the date picker and creates the object. Then opens next object and again - it's in calendar mode. Click pen, enter date, save object, create next - again in calendar mode.

A workaround would be to expose this setting to the user: `What's your preferred way to select dates, calendar or input?` but that's too specific for my application and I personally appreciate applications that remembers my choices rather than forcing me to configure every setting in detail.

## Proposal

Expose a callback or change notifier when the user switches between entry mode calendar and input, this way we can store the preferred input method in application state and open the next date picker with the preferred entry mode already set (using the existing `initialEntryMode` parameter).

**Comment by hasnentai** [comment]
Hi @mikeesouth, Please have a look at PR #119116 and the video attached below. This is what is expected right ? if not do help me with more inputs.
@Piinks Please review the PR and help me if anything is implemented in the wrong way. Happy to learn more here while contributing to the Flutter repo 😄 .


https://user-images.githubusercontent.com/26821037/214497266-31f98f8e-e32c-452b-be7d-fafd6cb62e21.mov
