### ISSUE TITLE
Handle Homebrew vs Rubygems setups

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#11341]
@jfine wrote:
>I ran into an issue with the Homebrew install because I was using a Ruby version manager...
>
>```
> ❯ pod setup
> dyld: lazy symbol binding failed: Symbol not found: _rb_str_new_static
>   Referenced from: /Users/jared/.gem/ruby/2.4.1/gems/json-2.1.0/lib/json/ext/generator.bundle
>   Expected in: flat namespace
>
> dyld: Symbol not found: _rb_str_new_static
>   Referenced from: /Users/jared/.gem/ruby/2.4.1/gems/json-2.1.0/lib/json/ext/generator.bundle
>   Expected in: flat namespace
>
> [1]    39800 abort      pod setup
>```
>
>Suggesting updating instructions to add installation via RubyGems. This is also the officially recommended way to install CocoaPods.

They provided a patch to fix this in https://github.com/flutter/flutter/pull/10960

My problem was that as a user, I'd have no idea which option to use, so it actually in a way makes things more confusing. If there was a way we could pick one or the other, we could just give the "right" answer. If we weren't sure, but were pretty sure, we could add "(recommended based on an examination of your configuration)" or something next to the one we thought was the right solution.

**Comment by jonahwilliams** [comment]
Thanks to @christopherfujino , we no longer require or mention brew in https://flutter.dev/docs/get-started/install/macos . Closing as obsolete

**Comment by jonahwilliams** [comment]
... At least I think it is obsolete, will ask tomorrow

**Comment by christopherfujino** [comment]
Yes, it's obsolete. Only references to `brew` in our codebase are user messages if the user doesn't have `curl` or `lcov`. We officially do not depend on homebrew.
