### ISSUE TITLE
Labelising AppBar Leading icons

### ISSUE THREAD

**Issue by voipworld** [flutter/flutter#113469]
## Labelising AppBar Leading Buttons
i opened a issue according to this subject but i was unable to provide more descriptions as there was no more diagnostic data at that time.
i'm reopening the issue with some description that will probably help the flutter team fix this issue.
### the issue:
the issue is any appbar leading like drawer icon, back button, or also the popup menu icon is not spoken to the screen reader, because of the iconButton tooltype not spoken.
talkback will detect the icon and describe it using AI. but other screen readers wont get it.
### how did i fix it?
i implemented my own leading button for my drawer using text button, here's the reproducible code:
```dart
      appBar: AppBar(
    leading: Builder(
      builder: (BuildContext context) {
        return TextButton.icon(
          icon: const Icon(Icons.menu),
label: Text('Menu'),
          onPressed: () {
            Scaffold.of(context).openDrawer();
          },
        );
      },
    ),
centerTitle: true,
        title: Text('My App'),
      ),
```
...
this code include only the appbar as its the one that have the issue.
#### note:
replacing the label text with MaterialLocalizations.of(context).openAppDrawerTooltip also get read, so its not a localization issue.
### Flutter Doctor output:
[√] Flutter (Channel stable, 3.3.4, on Microsoft Windows [version 10.0.19044.2130], locale fr-FR)
    • Flutter version 3.3.4 on channel stable at d:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision eb6d86ee27 (10 days ago), 2022-10-04 22:31:45 -0700
    • Engine revision c08d7d5efc
    • Dart version 2.18.2
    • DevTools version 2.15.0

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc1)
    • Android SDK at c:\android_sdk
    • Platform android-33, build-tools 33.0.0-rc1
    • ANDROID_HOME = c:\android_sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.1.1)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.1.32228.430
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] VS Code (version 1.72.0)
    • VS Code at C:\Users\tayeb meftah\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.50.0

[√] Connected device (4 available)
    • M2007J20CG (mobile) • de62a437 • android-arm64  • Android 11 (API 30)
    • Windows (desktop)   • windows  • windows-x64    • Microsoft Windows [version 10.0.19044.2130]
    • Chrome (web)        • chrome   • web-javascript • Google Chrome 106.0.5249.119
    • Edge (web)          • edge     • web-javascript • Microsoft Edge 103.0.1264.77

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Comment by exaby73** [comment]
Hello @voipworld. Thank you for raising this issue. Could you tell me the steps to reproduce this? Which screen reader are you using if not TalkBack, and are there any pre-requites needed to reproduce this?

**Comment by voipworld** [comment]
hello,
thank you for taking time to look at this issue.
we use Commentary screen reader (CSR), its a chinese developed screen
reader, mostly distributed outside of the playstore.
to reproduce the issue, just create app with two pages. with any kind
of button like TextButton, navigate to the new screen.
if you want to go back, you should get the back button spoken, but its not.
similarly, the drawer and the popup menu icon in the appbar have same issue.
i'll reproduce the issue in MacOs and see the VoiceOver behavior.

**Comment by exaby73** [comment]
Would be great if you can give me a link to the screen reader you are using. I cannot find it

**Comment by voipworld** [comment]
Hello,
I discovered the issue myself, no need to install any app my friend.
The exact issue is that the toolType property of any widget is not providing feedback to the screen reader itself.
Try to add a iconButton or any button that support toolType and try to read it.
Even the default flutter app is not reading the increment button.

**Comment by exaby73** [comment]
Using Talkback (which is only screen reader I have installed), the tooltip for the increment button is being read as expected. I cannot reproduce what you said. If this issue is not properly reproducible, it becomes unactionable for the team. Please provide detailed steps I can use to reproduce this issue. Thank you.
