### ISSUE TITLE
[animations] PageTransitionSwitcher produces weird padding glitch/twitch on animating between widgets [android & windows]

### ISSUE THREAD

**Issue by AleXoTroN** [flutter/flutter#113408]
## Steps to Reproduce

**Expected results:**
I expected it to animate without those padding twitches.

**Actual results:**
There are padding twitches.
Its not coming from any of my other widgets. I tried to remove every entire padding in my app so there is no but it still happens.

Here is a youtube video with flutter payout inspector turned on:
https://www.youtube.com/shorts/FdQnl0CJX8c

<details>
  <summary>Code example</summary>

You just need to setup a PageTransitionSwitcher in a Scaffold like in the following example:
```ruby
body: Padding(
        padding: const EdgeInsets.only(top: 128),
        child: PageTransitionSwitcher(
          reverse: currentWidget == home_page,
          duration: Duration(milliseconds: 400),
          transitionBuilder: (Widget child, Animation<double> animation, Animation<double> scnd_animation) {
            return FadeThroughTransition(
              animation: animation,
              secondaryAnimation: scnd_animation,
              child: child,
            );
          },
          child: currentWidget,
        ),
      ),//
```

Then setup two widgets for the pages that you want to switch between. Page one is for example that one (Animated Grid List):

```ruby
first_page = Container(
      padding: EdgeInsets.zero,
      key: Key("CONTAINER2"),
      child: AnimationLimiter(
        child: GridView.builder(
          shrinkWrap: true,
          physics: BouncingScrollPhysics(),
          addAutomaticKeepAlives: false,
          padding: EdgeInsets.fromLTRB(16, 0, 16, 96),
          itemCount: categories.length,
          gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount: 2),
          itemBuilder: (context, index){
            return AnimationConfiguration.staggeredList(
              duration: Duration(milliseconds: 1100),
              position: index,
              child: ScaleAnimation(
                  curve: Curves.easeOutCirc,
                duration: Duration(milliseconds: 220),
                  child: AnimatedSize(
                      curve: Curves.easeInOutCirc,
                      duration: Duration(milliseconds: 400),
                      vsync: this,
                      child: Text("Test Text))),
            );
          },
        ),
      ),
    );
```

Then setup two widgets for the pages that you want to switch between. Page two is for example is a duplicate of first_page but with another string in the text widget:

```ruby
second_page = Container(
      padding: EdgeInsets.zero,
      key: Key("CONTAINER2"),
      child: AnimationLimiter(
        child: GridView.builder(
          shrinkWrap: true,
          physics: BouncingScrollPhysics(),
          addAutomaticKeepAlives: false,
          padding: EdgeInsets.fromLTRB(16, 0, 16, 96),
          itemCount: categories.length,
          gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount: 2),
          itemBuilder: (context, index){
            return AnimationConfiguration.staggeredList(
              duration: Duration(milliseconds: 1100),
              position: index,
              child: ScaleAnimation(
                  curve: Curves.easeOutCirc,
                duration: Duration(milliseconds: 220),
                  child: AnimatedSize(
                      curve: Curves.easeInOutCirc,
                      duration: Duration(milliseconds: 400),
                      vsync: this,
                      child: Text("Second Test Text"))),
            );
          },
        ),
      ),
    );
```

And if you just switch the currentWidget to another, it has that weird padding glitches as you can also see in the video link below. Its just very anoying because it just happens in every app where i use the PageTransitionSwitcher and it does not matter which animation i use for switching:
```ruby
setState((){
    currentWidget = second_page;
});
```

```dart
```

</details>

<details>
  <summary>Logs</summary>
There are just no widget specific logs

flutter doctor -v output:

> flutter doctor -v
[√] Flutter (Channel stable, 3.3.4, on Microsoft Windows [Version 10.0.25217.1000], locale de-DE)
    • Flutter version 3.3.4 on channel stable at D:\Programs\flutter\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision eb6d86ee27 (9 days ago), 2022-10-04 22:31:45 -0700
    • Engine revision c08d7d5efc
    • Dart version 2.18.2
    • DevTools version 2.15.0
>
>Checking Android licenses is taking an unexpectedly long time...[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at D:\SDKs\android-sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: D:\Programs\Android Studio BBP2\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.
>
>[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
>
>[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.2.6)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.2.32630.192
    • Windows 10 SDK version 10.0.20348.0
>
>[√] Android Studio (version 2021.3)
    • Android Studio at D:\Programs\Android Studio BBP2
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
>
>[√] Connected device (3 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 13 (API 33) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.25217.1000]
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 106.0.1370.37
>
>[√] HTTP Host Availability
    • All required HTTP hosts are available
>
>! Doctor found issues in 1 category.

</details>

**Comment by huycozy** [comment]
Hi @AleXoTroN, can you please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this?
