### ISSUE TITLE
Android 13 -  Flutter app never opens with "flutter run" command

### ISSUE THREAD

**Issue by elmar001** [flutter/flutter#113421]
In Android 13 when  "flutter run" command entered process seems stucked on the last step like the following:

Running Gradle task 'assembleDebug'...                             34.1s
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
Installing build/app/outputs/flutter-apk/app.apk...              1,003ms'

If you wait it will never open. Only way to make it work is, finding the app in the phone and opening it manually and then everything works.
The issue is reproduceable in both physical device Google Pixel 4A and simulator of Google Pixel 4A with API 33.

**Comment by huycozy** [comment]
@elmar001 
Do you set `targetSdkVersion` to `33`? If so, please take a look at this issue #105764 and notice to https://github.com/flutter/flutter/issues/105764#issuecomment-1224583437 (issue is fixed in master and beta channels).

**Comment by abinvs-2019** [comment]
Have you tried in other simulator?.

**Comment by netskillzgh** [comment]
Same problem here, if you run --verbose you will get : Activity class {my-package/my-package.MainActivity} does not exist.

Tested beta/master.

**Comment by elmar001** [comment]
I tried with another emulator: Nexus 4. It does not even run - the following error show up:
Running Gradle task 'assembleDebug'...                              7.1s
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
Installing build/app/outputs/flutter-apk/app.apk...                235ms
Error: ADB exited with exit code 1
Performing Streamed Install

adb: failed to install
/Users/elmar/redxAppMisc/MobileApp/redx_beta/build/app/outputs/flutter-apk/app.a
pk:
Exception occurred while executing 'install':
android.os.ParcelableException: java.io.IOException: Requested internal only,
but not enough space
	at android.util.ExceptionUtils.wrap(ExceptionUtils.java:34)
	at
	com.android.server.pm.PackageInstallerService.createSession(PackageInstallerSer
	vice.java:595)
	at
	com.android.server.pm.PackageManagerShellCommand.doCreateSession(PackageManager
	ShellCommand.java:3434)
	at
	com.android.server.pm.PackageManagerShellCommand.doRunInstall(PackageManagerShe
	llCommand.java:1446)
	at
	com.android.server.pm.PackageManagerShellCommand.runInstall(PackageManagerShell
	Command.java:1408)
	at
	com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellC
	ommand.java:221)
	at
	com.android.modules.utils.BasicShellCommandHandler.exec(BasicShellCommandHandle
	r.java:97)
	at android.os.ShellCommand.exec(ShellCommand.java:38)
	at
	com.android.server.pm.PackageManagerService$IPackageManagerImpl.onShellCommand(
	PackageManagerService.java:5954)
	at android.os.Binder.shellCommand(Binde
Error launching application on sdk gphone64 arm64.

**Comment by elmar001** [comment]
> @elmar001 Do you set `targetSdkVersion` to `33`? If so, please take a look at this issue #105764 and notice to [#105764 (comment)](https://github.com/flutter/flutter/issues/105764#issuecomment-1224583437) (issue is fixed in master and beta channels).

Yes, that is right. It is set to use 33. Got it, thanks for the clarification.

**Comment by huycozy** [comment]
@elmar001 
Thanks for confirming. I'll be closing this issue since it has already been fixed on the beta/master channel. If you still experience this issue on the beta/master channel, kindly leave a comment below and I will reopen this. Thank you!
