### ISSUE TITLE
Question: Can path_provider works with windows 7

### ISSUE THREAD

**Issue by ckilee** [flutter/flutter#113447]
Can path_provider: https://pub.dev/packages/path_provider works with windows 7?

**Comment by stuartmorgan** [comment]
The Flutter team does not test plugin with any version earlier that Windows 10; see https://docs.flutter.dev/development/tools/sdk/release-notes/supported-platforms

If you have issues with using it on Windows 7 you are welcome to send PRs, but we don't actively support it.
