### ISSUE TITLE
Stocks app is starting up with the tab view being empty and not draggable.

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#1134]
I haven't checked, but it feels like maybe the list is not filling the whole space?

cc @abarth, @HansMuller

**Comment by abarth** [comment]
The list will shrinkwrap the zero items.  Not sure if the container forces its height.

**Comment by Hixie** [comment]
It looks like it doesn't realize when it gets more data.

**Comment by abarth** [comment]
I can take a look at this, but maybe not tomorrow.

**Comment by Hixie** [comment]
Maybe related, when stocks comes up, if you try to drag to switch tabs, the drawer moves, then the gesture system asserts.

**Comment by HansMuller** [comment]
I don't think this is the problem you're seeing (which I haven't been able to reproduce) but. I introduced a typo in the tabs scrolling code yesterday.  The fix is: https://github.com/flutter/flutter/pull/1142
