### ISSUE TITLE
Default "hello world" app moved to some embedded linux -> failing FlutterEngineInitialize

### ISSUE THREAD

**Issue by bwofsi** [flutter/flutter#113428]
## Steps to Reproduce
1. Execute `flutter create sampleapp`, `cd sampleapp` and `flutter 
2. Copy to the target system: 
build/linux/x64/debug/bundle/sampleapp
build/linux/x64/debug/bundle/lib/libflutter_linux_gtk.so
3. Running on the target system:
LD_LIBRARY_PATH=. ./sampleapp

**Expected results:**
The application running.

**Actual results:**
While the app works without any issues on the development machine, on the target embedded machine, an empty windows opens and on the console the error is written:
```
embedder.cc (1218): 'FlutterEngineInitialize' returned 'kInvalidArguments'. Not running in AOT mode but could not resolve the kernel binary.

** (sampleapp:5512): WARNING: **: 15:42:23.915: Failed to start Flutter engine: Failed to initialize Flutter engine
```

**Flutter version:** 3.3.4

If I found the correct location in the code: https://github.com/flutter/engine/blob/flutter-3.3-candidate.12/shell/platform/embedder/embedder.cc#L1218
Is there any chance to narrow down the cause for you flutter devs?
Maybe I could bring GDB to work on that embedded device, but not sure wether that would deliver additional information?

**Comment by darshankawar** [comment]
@bwofsi 
Please check [this](https://stackoverflow.com/a/62087380) answer and see if it helps in your case.

**Comment by bwofsi** [comment]
Whoa, that was surely one of the fastest solved issues for me!

Thank you so much!
(And I promise I won't overlook misspelled Google results!)
