### ISSUE TITLE
JXL (JPEG XL) Image Support

### ISSUE THREAD

**Issue by Mis1eader-dev** [flutter/flutter#113476]
A modern and efficient image format that is currently in its final stages of standardization, it can be implemented and supported by Flutter so by the time it is the new standard, it is fully functional.
[libjxl](https://github.com/libjxl/libjxl)

**Comment by iapicca** [comment]
sounds like a good idea for a package rather than a first party feature
how does it compare to [webp](https://en.wikipedia.org/wiki/WebP)?

**Comment by Mis1eader-dev** [comment]
> sounds like a good idea for a package rather than a first party feature
> how does it compare to [webp](https://en.wikipedia.org/wiki/WebP)?

I do agree with you to an extent, the thing about JXL is it is a superset of JPEG in a way, and some might say it is a replacement of JPEG.

As far as I can see, it can make a big difference for web and embedded servers or limited bandwidth networks.

- [Here](https://cloudinary.com/blog/how_jpeg_xl_compares_to_other_image_codecs) is a comparison of JXL against other image formats, including webp.

- [Generation loss from re-encoding - YouTube](https://youtu.be/w7UDJUCMTng)

- [Speed and size comparison - YouTube](https://youtu.be/inQxEBn831w)

**Comment by chinmaygarde** [comment]
Flutter has support for falling for using codecs on the device for codecs it doesn't ship with in the Flutter Engine binary. If the device supports that codec, so will Flutter apps automatically.

But we don't want to add this additional codec as it will increase the engine binary size for all application and it seems like Chrome is dropping support for it too.

If the application really wishes to support this format, I recommend a plugin.

Closing this as a Wont-Fix.
