### ISSUE TITLE
Verify downloaded content during installation and upgrade

### ISSUE THREAD

**Issue by xmine64** [flutter/flutter#113448]
Hi! I have an unstable connection and downloaded content by flutter tools may be corrupted, but the tools don't verify that and I ran into problems that can be fixed by deleting cache. It is nice to add something like checksum or signature to check if the required files are downloaded correctly.

**Comment by huycozy** [comment]
Hi @xmine64, please provide the output of `flutter doctor -v` so that we may verify this.

**Comment by huycozy** [comment]
@xmine64 
I'm not a robot:). I'm asking for the output of `flutter doctor -v` in order to investigate the issue better. 

Given your last message, I feel safe to close this issue as solved. Please don't hesitate to comment on the bug if you have any more information for us, we will reopen it! Thanks!

**Comment by xmine64** [comment]
> I'm not a robot

Well sorry that's first thing that everyone ask and my issue is not related to current status of my installation.

> Given your last message, I feel safe to close this issue as solved.

I'm not saying I have a problem right now, I asked to add something like checksum to check if files are downloaded correctly, because on an unstable connection like mine it's possible to corrupt the installation during upgrade.

**Comment by huycozy** [comment]
@xmine64 I reopen this issue for further investigation.

>Also flutter doctor won't work at all when the installation is broken (I get an error like "The file is not a valid executable").

You may try upgrading the master channel every day to check this. When you get this error, please provide the completed error message so that we have enough information to verify the issue.

**Comment by xmine64** [comment]
I just requested to add a verification method like checksum to verify the files are downloaded correctly. I'm not reporting any bug.

**Comment by huycozy** [comment]
@xmine64 What is your current Flutter version? Please check this issue #38980 if it's similar. The issue may have been solved on the new Flutter versions.

**Comment by xmine64** [comment]
Yes it's exactly what I was asking for. If it's fixed then I close this. Thanks!
