### ISSUE TITLE
Add an easy hook to provide the FlutterBinaryMessenger when using FlutterAppDelegateRegistrar

### ISSUE THREAD

**Issue by xster** [flutter/flutter#11349]
`FlutterAppDelegate`'s default `FlutterAppDelegateRegistrar` assumes that the messenger should be the app delegate's `window.rootViewController`. But it makes it hard to use when the `FlutterViewController` isn't the app's root view controller without copy pasting stuff out of the `FlutterAppDelegate.m`. Maybe let `FlutterAppDelegateRegistrar` ask the app delegate for an overridable messenger instead of assuming `rootViewController`.

**Comment by stuartmorgan** [comment]
Closing as obsolete; the class described doesn't appear to exist any more.
