### ISSUE TITLE
plugin local_auth breaks build process

### ISSUE THREAD

**Issue by Tomucha** [flutter/flutter#113533]
The minute I add local_auth to my project an try to run it (flutter run) I end up with:

```
* What went wrong:
Execution failed for task ':app:mergeDebugJavaResource'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > More than one file was found with OS independent path 'META-INF/com.android.tools/proguard/coroutines.pro'

```

Just adding `local_auth: ^2.1.2` to dependencies breaks the project.

------------------
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.5.1 21G83 darwin-arm, locale en-CZ)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2022.1.4)
[✓] VS Code (version 1.71.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

**Comment by huycozy** [comment]
@Tomucha 
Please check this SO answers if it can help: https://stackoverflow.com/questions/52518378/more-than-one-file-was-found-with-os-independent-path-meta-inf-proguard-android

If it is not helpful, can you share your `android\app\build.gradle` file content? Also, does this issue happen on the Flutter default sample project (counter app)?

**Comment by huycozy** [comment]
Glad to see you solved it. Close the issue as solved. Thank you!
