### ISSUE TITLE
Uncaught ReferenceError: _flutter is not defined

### ISSUE THREAD

**Issue by hmj2414** [flutter/flutter#113512]
Hello, I am using Flask to make web via Flutter.
Frontend developer  made web server using spring framework, and I want to change it to Flask framework.
During rendering index.html built by Flutter, I got an error in my browser(Chrome) like below.

![flutter browser](https://user-images.githubusercontent.com/35605980/196099027-8d59ca66-cc1c-4dfe-8435-3983e02dcaab.png)

And my directory is 
![directory](https://user-images.githubusercontent.com/35605980/196099081-ede6b69b-2546-4479-9c00-3c167b1e141c.png)

Is there anyone who can help me with handling this error? Thank you very much!

**Comment by darshankawar** [comment]
@hmj2414 
Check [this](https://github.com/flutter/flutter/issues/107448) similar issue and see if it helps in your case.
Also, looking at the details you provided, it seems you are using lot of custom and third party implementation so it is tough to know what could be exactly causing the issue.

I suggest you to ask this question on support channels like StackOverflow for further resolution.
Closing from here. If you think there's a genuine bug in the framework, please provide a complete minimal reproducible code sample without any third party plugins that triggers the error reported.
