### ISSUE TITLE
Slider does not show value indicator when focused.

### ISSUE THREAD

**Issue by TahaTesser** [flutter/flutter#113538]
### Description

When working on other `Slider` issues, I noticed discrete `Slider` does not show the value indicator when focused.

<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      themeMode: ThemeMode.light,
      theme: ThemeData(
        useMaterial3: true,
        brightness: Brightness.light,
        colorSchemeSeed: const Color(0xff6750a4),
      ),
      darkTheme: ThemeData(
        useMaterial3: true,
        brightness: Brightness.dark,
        colorSchemeSeed: const Color(0xff6750a4),
      ),
      home: const SliderExample(),
    );
  }
}

class SliderExample extends StatefulWidget {
  const SliderExample({super.key});

  @override
  State<SliderExample> createState() => _SliderExampleState();
}

class _SliderExampleState extends State<SliderExample> {
  double sliderValue = 40;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Slider'),
      ),
      body: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: <Widget>[
          const Text('Continuous'),
          Slider(
            value: sliderValue,
            max: 100,
            label: sliderValue.round().toString(),
            onChanged: (double value) {
              setState(() {
                sliderValue = value;
              });
            },
          ),
          const SizedBox(height: 10),
          const Text('Discrete'),
          Slider(
            value: sliderValue,
            max: 100,
            divisions: 5,
            label: sliderValue.round().toString(),
            onChanged: (double value) {
              setState(() {
                sliderValue = value;
              });
            },
          ),
        ],
      ),
    );
  }
}

``` 
	
</details>

### Material web slider demo
![ezgif com-gif-maker](https://user-images.githubusercontent.com/48603081/196216806-103cd520-f716-4a97-bc0f-2c90bcf416f7.gif)

### Flutter
 
![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/48603081/196216891-80a756d4-fe24-45b6-ba0a-58c44a9378fc.gif)

(This is compared to https://material-components.github.io/material-web/demos/slider/)

Perhaps this is a regression.

**Comment by Flutter-Libya** [comment]
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      themeMode: ThemeMode.light,
      theme: ThemeData(
        useMaterial3: true,
        brightness: Brightness.light,
        colorSchemeSeed: const Color(0xff6750a4),
      ),
      darkTheme: ThemeData(
        useMaterial3: true,
        brightness: Brightness.dark,
        colorSchemeSeed: const Color(0xff6750a4),
      ),
      home: const SliderExample(),
    );
  }
}

class SliderExample extends StatefulWidget {
  const SliderExample({Key? key}) : super(key: key);

  @override
  State<SliderExample> createState() => _SliderExampleState();
}

class _SliderExampleState extends State<SliderExample> {
  double sliderValue = 40;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Slider Example'),
      ),
      body: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: <Widget>[
          const Text('Continuous Slider'),
          _buildContinuousSlider(),
          const SizedBox(height: 10),
          const Text('Discrete Slider'),
          _buildDiscreteSlider(),
        ],
      ),
    );
  }

  Widget _buildContinuousSlider() {
    return Slider(
      value: sliderValue,
      max: 100,
      label: sliderValue.round().toString(),
      onChanged: (double value) {
        _updateSliderValue(value);
      },
    );
  }

  Widget _buildDiscreteSlider() {
    return Slider(
      value: sliderValue,
      max: 100,
      divisions: 5,
      label: sliderValue.round().toString(),
      onChanged: (double value) {
        _updateSliderValue(value);
      },
      onFocusChange: (bool focused) {
        _handleDiscreteSliderFocusChange(focused);
      },
    );
  }

  void _updateSliderValue(double value) {
    setState(() {
      sliderValue = value;
    });
  }

  void _handleDiscreteSliderFocusChange(bool focused) {
    // Implement desired behavior when discrete slider gains or loses focus
    if (focused) {
      // Show value indicator when focused
      // You can customize this behavior as needed
    } else {
      // Handle other behavior when focus is lost
    }
  }
}
