### ISSUE TITLE
[local_auth] Details about the package

### ISSUE THREAD

**Issue by Lawati97** [flutter/flutter#113528]
I would like to understand more about how can I know which biometric is displayed for registration and is there a way to specify which biometrics such as only touch ID (before I select I would confirm if the device supports it or not!)

**Comment by Lawati97** [comment]
@danagbemava-nc  so I am trying to implement local auth but if device support face authentication and fingerprint authentication can I select which one to use?

**Comment by danagbemava-nc** [comment]
iOS devices (at present) only have either face ID or Touch ID and as far as I can tell, you there isn't an API that will allow you to select which one you want to use so it's not possible for iOS. 

Android, on the other hand, allows you to specify a biometric type. See https://source.android.com/docs/security/features/biometric for the options. However, currently, this has not been implemented yet. You can query for the existence of either STRONG or WEAK biometric, but the option to add either to authenticate hasn't been added yet. That is being tracked in https://github.com/flutter/flutter/issues/81169

Does this answer your question?

**Comment by Lawati97** [comment]
Yes it does! Thank you!
