### ISSUE TITLE
Support for basic formatting in Text widget via html or markdown

### ISSUE THREAD

**Issue by lukef** [flutter/flutter#11355]
Not sure how hard it is but had a client request for basic (bold, italic, underline) formatting support in the text widget. I'm guessing that using html `<strong>/<b>, etc` or a markdown equivalent would be the best approach.

**Comment by Hixie** [comment]
Let me know if that's not sufficient!

**Comment by sethladd** [comment]
There's also this doc request: https://github.com/flutter/flutter/issues/6559
