### ISSUE TITLE
flutter slow on recent PowerVR GPUs

### ISSUE THREAD

**Issue by ardera** [flutter/flutter#113596]
Hello,
my company is currently working together with Texas Instruments to make flutter run on their AM62xx boards. We found that the performance is not that good, and as it turns out it's worse than it could be, because skia enables (apparently) unnecessary GL workarounds when it finds a PowerVR GPU.

I also filed a [skia issue](https://bugs.chromium.org/p/skia/issues/detail?id=13791) for this but I thought having it as a flutter issue might be good as well, since it primarily manifests itself to the user as "flutter rendering slowly on that platform". Lmk if you think the skia issue is enough.

## Details

1. Use a board with a recent PowerVR GPU (like the [Texas Instruments SK-AM62](https://www.ti.com/tool/SK-AM62))
2. Build a system for it using yocto, meta-flutter and my [flutter-pi patches](https://github.com/ardera/flutter-pi/tree/feature/ti-am62xx)
3. Run the included flutter gallery app on the board
4. Discover that FPS are pretty bad (maybe 10FPS), even though the GPU is not that far away from the VideoCore GPU in a Pi 4.
5. Profile & find out that most of the CPU time is spent inside some functions like `SoftwarePathRenderer::draw`, with `drawTextBlob` a bit up the call stack.
6. Turns out skia enables lots of workarounds on PowerVR Rogue GPUs: https://github.com/google/skia/blob/8941e05187e88a97d1db8434d5ec484304b66081/src/gpu/ganesh/gl/GrGLCaps.cpp#L4266-L4275 (just search for `kPowerVRRogue` in that file)
7. If you disable all the workarounds, it still renders perfectly fine but now at 50-60FPS.

I think those workarounds are primarily in place for older PowerVR GPUs, some (maybe even all) of them might be unnecessary on newer GPUs & drivers, like the AXE-1-16M that's present on the SK-AM62.

**Comment by huycozy** [comment]
Hi @ardera, which Flutter version are you facing this issue?

**Comment by ardera** [comment]
@huycozy This is with latest flutter stable `3.3.4`, but all the skia workarounds are still there in latest skia, so you'll also face this in flutter master

**Comment by huycozy** [comment]
@ardera I'm not sure I can go deeper with this since I'm not familiar with embedded devices. I will label this issue for further investigation from the team. Thanks!

**Comment by ardera** [comment]
> @ardera I'm not sure I can go deeper with this since I'm not familiar with embedded devices. I will label this issue for further investigation from the team. Thanks!

Yep sure, I mean it's impossible to reproduce this anyway without a PowerVR GPU.

**Comment by zanderso** [comment]
@egdaniel @bsalomon Is there any way to make the PowerVR carveout finer-grained?

**Comment by bsalomon** [comment]
Absolutely! What we'd need is the GL_VERSION and GL_RENDERER strings from a newer device that works OK and then we can add detection for a newer driver version.

**Comment by ardera** [comment]
@bsalomon 
This is the output of kmscube on the SK-AM62xx (dunfell):
```
root@am62xx-evm:~# kmscube -D /dev/dri/card0
Using display 0x31023d90 with EGL version 1.5
===================================
EGL information:
  version: "1.5"
  vendor: "Mesa Project"
  client extensions: "EGL_EXT_client_extensions EGL_EXT_device_base EGL_EXT_device_enumeration EGL_EXT_device_query EGL_EXT_platform_base EGL_KHR_client_get_all_proc_addresses EGL_KHR_debug EGL_EXT_platform_device EGL_EXT_platform_wayland EGL_KHR_platform_wayland EGL_MESA_platform_gbm EGL_KHR_platform_gbm EGL_MESA_platform_surfaceless"
  display extensions: "EGL_ANDROID_native_fence_sync EGL_EXT_buffer_age EGL_EXT_create_context_robustness EGL_EXT_image_dma_buf_import EGL_EXT_image_dma_buf_import_modifiers EGL_EXT_image_gl_colorspace EGL_EXT_yuv_surface EGL_IMG_context_priority EGL_KHR_cl_event2 EGL_KHR_config_attribs EGL_KHR_create_context EGL_KHR_fence_sync EGL_KHR_get_all_proc_addresses EGL_KHR_gl_colorspace EGL_KHR_gl_renderbuffer_image EGL_KHR_gl_texture_2D_image EGL_KHR_gl_texture_3D_image EGL_KHR_gl_texture_cubemap_image EGL_KHR_image EGL_KHR_image_base EGL_KHR_image_pixmap EGL_KHR_no_config_context EGL_KHR_partial_update EGL_KHR_reusable_sync EGL_KHR_surfaceless_context EGL_EXT_pixel_format_float EGL_KHR_wait_sync EGL_MESA_configless_context EGL_MESA_drm_image EGL_MESA_image_dma_buf_export EGL_WL_bind_wayland_display EGL_IMG_cl_image "
===================================
OpenGL ES 2.x information:
  version: "OpenGL ES 3.1 build 1.15@6133109"
  shading language version: "OpenGL ES GLSL ES 3.10 build 1.15@6133109"
  vendor: "Imagination Technologies"
  renderer: "PowerVR Rogue AXE-1-16M"
  extensions: "GL_APPLE_texture_format_BGRA8888 GL_EXT_blend_minmax GL_EXT_buffer_storage GL_EXT_clip_control GL_EXT_color_buffer_float GL_EXT_color_buffer_half_float GL_EXT_compressed_ETC1_RGB8_sub_texture GL_EXT_conservative_depth GL_EXT_copy_image GL_EXT_discard_framebuffer GL_EXT_draw_buffers GL_EXT_draw_buffers_indexed GL_EXT_draw_elements_base_vertex GL_EXT_EGL_image_array GL_EXT_float_blend GL_EXT_gpu_shader5 GL_EXT_memory_object GL_EXT_memory_object_fd GL_EXT_multi_draw_arrays GL_EXT_multisampled_render_to_texture GL_EXT_multisampled_render_to_texture2 GL_EXT_occlusion_query_boolean GL_EXT_polygon_offset_clamp GL_EXT_read_format_bgra GL_EXT_robustness GL_EXT_separate_shader_objects GL_EXT_shader_framebuffer_fetch GL_EXT_shader_group_vote GL_EXT_shader_implicit_conversions GL_EXT_shader_io_blocks GL_EXT_shader_non_constant_global_initializers GL_EXT_shader_pixel_local_storage GL_EXT_shader_pixel_local_storage2 GL_EXT_shader_texture_lod GL_EXT_shadow_samplers GL_EXT_sparse_texture GL_EXT_sRGB_write_control GL_EXT_texture_border_clamp GL_EXT_texture_buffer GL_EXT_texture_cube_map_array GL_EXT_texture_format_BGRA8888 GL_EXT_texture_format_sRGB_override GL_EXT_texture_rg GL_EXT_texture_shadow_lod GL_EXT_texture_sRGB_decode GL_EXT_texture_sRGB_R8 GL_EXT_texture_sRGB_RG8 GL_EXT_YUV_target GL_IMG_framebuffer_downsample GL_IMG_multisampled_render_to_texture GL_IMG_program_binary GL_IMG_read_format GL_IMG_shader_binary GL_IMG_texture_format_BGRA8888 GL_IMG_texture_npot GL_KHR_blend_equation_advanced GL_KHR_blend_equation_advanced_coherent GL_KHR_debug GL_KHR_robustness GL_OES_compressed_ETC1_RGB8_texture GL_OES_depth24 GL_OES_depth_texture GL_OES_draw_buffers_indexed GL_OES_draw_elements_base_vertex GL_OES_EGL_image GL_OES_EGL_image_external GL_OES_EGL_image_external_essl3 GL_OES_EGL_sync GL_OES_element_index_uint GL_OES_fragment_precision_high GL_OES_get_program_binary GL_OES_gpu_shader5 GL_OES_mapbuffer GL_OES_packed_depth_stencil GL_OES_required_internalformat GL_OES_rgb8_rgba8 GL_OES_sample_shading GL_OES_sample_variables GL_OES_shader_image_atomic GL_OES_shader_io_blocks GL_OES_shader_multisample_interpolation GL_OES_standard_derivatives GL_OES_surfaceless_context GL_OES_texture_border_clamp GL_OES_texture_buffer GL_OES_texture_cube_map_array GL_OES_texture_float GL_OES_texture_half_float GL_OES_texture_npot GL_OES_texture_stencil8 GL_OES_texture_storage_multisample_2d_array GL_OES_vertex_array_object GL_OES_vertex_half_float"
===================================
```

I can also test on kirkstone if you want, the driver may be different there.

**Comment by dnfield** [comment]
@bsalomon says https://skia-review.googlesource.com/c/skia/+/596218 will fix this.

**Comment by bsalomon** [comment]
That change has now landed and rolled to Flutter Engine.

**Comment by Hixie** [comment]
@ardera Please check this out on `master` and let us know if it's fixed! Thanks for the report!

**Comment by ardera** [comment]
Okay, just tested, I can confirm it's a lot better. Thanks, I appreciate the fast fix!

Though not 100% sure if it's the same as having all the other workarounds disabled too.
Also, when looking at it in [PVRCarbon](https://developer.imaginationtech.com/pvrcarbon/), I got lots of performance warnings about render target switches. The skia "reduce ops task splitting feature"[^1] helped reduce that, but it's disabled in the engine[^2] (because it increases peak graphics memory usage, AFAIK).

Should I provide some more concrete performance numbers (I'm not even sure how much that improved things) and submit issues for that too?

[^1]: https://bugs.chromium.org/p/skia/issues/detail?id=10877
[^2]: https://github.com/flutter/engine/blob/ad52b15741e7a538353f99b3e60525b912a234b5/shell/common/context_options.cc#L36

**Comment by bsalomon** [comment]
I can't speak for the reduce-ops-task decision, but if other workarounds don't seem to be required and disabling them improves performance I'd be interested in disabling them in Skia.

**Comment by chinmaygarde** [comment]
I'm closing this issue as it was tracking removal of features being disabled on PVR GPUs. If there are other improvement backend by use cases to be made, lets file separate issues for clarity.
