### ISSUE TITLE
testWidgets hangs if resources created in setUp

### ISSUE THREAD

**Issue by craiglabenz** [flutter/flutter#113506]
The following test hangs until the global 30s timeout. The scenario is a chain of `StreamControllers`, with a `Completer` that is resolved when the final `StreamController` receives its event. However, IFF the controllers are initialized in `setUp`, and IFF the test method is `testWidgets` (this behavior is not seen with the `test/test` package's `test()` method), then the last output below will be `"pre-wait"`.

```dart
import 'dart:async';
import 'package:flutter_test/flutter_test.dart';

late StreamController<int> controller;
late StreamController<int> controller2;

void main() {
  setUp(() {
    controller = StreamController<int>();
    controller2 = StreamController<int>();

    controller.stream.listen(controller2.add);
  });

  testWidgets(
    'Await StreamControllers initialized in setUp',
    (tester) async {
      final completer = Completer<void>();
      controller2.stream.listen((_) {
        print('pre-complete');
        completer.complete();
        print('post-complete');
      });

      controller.add(0);

      print('pre-wait');
      await completer.future;
      print('post-wait');

      expect(true, true);
    },
  );
}
```

Output:

```
pre-wait
pre-complete
post-complete
TimeoutException after 0:00:30.000000: Test timed out after 30 seconds.
dart:isolate  _RawReceivePortImpl._handleMessage

✖ 
Exited (1)
```

cc @felangel @slightfoot

**Comment by maks** [comment]
I think this maybe a variation of the "run widget tests async" faq, for which the answer is to wrap with `runAsync`:
```dart
testWidgets(
    'Await StreamControllers initialized in setUp',
    (tester) async {
      await tester.runAsync(() async {
        final completer = Completer<void>();
        controller2.stream.listen((_) {
          print('pre-complete');
          completer.complete();
          print('post-complete');
        });

        controller.add(0);

        print('pre-wait');
        await completer.future;
        print('post-wait');

        expect(true, true);
      });
    },
  );
```
courtesy of  @zoechi : https://stackoverflow.com/a/52177385/85472

**Comment by exaby73** [comment]
Hello @craiglabenz. Is the solution @maks posted a viable one? If so, could this be documented better?

**Comment by craiglabenz** [comment]
Yes it does fix the issue, @exaby73. Thanks, @maks! We can close for now, but I'm going to take a personal AI to understand this better and get it documented.

**Comment by slightfoot** [comment]
Can we reopen this.. as I don't believe this is the solution exactly. It requires more discussion.

**Comment by craiglabenz** [comment]
What are you thinking, @slightfoot? Are you aware of a different scenario this doesn't solve?
