### ISSUE TITLE
App Size compression when using FFmpeg Kit

### ISSUE THREAD

**Issue by rennylangat** [flutter/flutter#113505]
FFMpeg Kit is a very effective library for devs that are working on multimedia applications. There is however one issue when one uses it. The app size of the app increases considerably; both on the releases and debug mode. I recently used it and the app went from 24MB to a whooping 80MB even after excluding some C libraries the app should not compile with. If anyone has a solution for this it is highly appreciated otherwise I think it is time to check on this issue.

**Comment by danagbemava-nc** [comment]
This issue should be reported on the repo for the plugin that you are using. 

Closing from here as this is not a flutter issue. 

Thank you
