### ISSUE TITLE
Better diagnostics with nested Scaffolds

### ISSUE THREAD

**Issue by hungrymonkey** [flutter/flutter#11350]
## Steps to Reproduce

1. Run the below code
2. click on text box
3. type anything
4. Although the ui recieve user input, the text box does not appear
5. unhover text box and we can see whatever the user typed.

I do not know if we are allow to nest Scaffolds and add an inputtextbox to the inner most scaffold box.

I am using nested scaffold because the outer scaffold is the navigation tabbed bar and the inner scaffold for another tabbed page.

Please tell us what you were doing and what went wrong. If you are running flutter tools from the command line, please try adding the `-v` or `--verbose` option to gather more information.

If the problem is with your application's rendering, please attach a screenshot and any relevant source code.

```dart
import 'package:flutter/material.dart';

	void main() {
	  runApp(new MyApp());
	}

	class MyApp extends StatelessWidget {
	  // This widget is the root of your application.
	  @override
	  Widget build(BuildContext context) {
	    return new MaterialApp(
	      title: 'Flutter Demo',
	      theme: new ThemeData(
		// This is the theme of your application.
		//
		// Try running your application with "flutter run". You'll see
		// the application has a blue toolbar. Then, without quitting
		// the app, try changing the primarySwatch below to Colors.green
		// and then invoke "hot reload" (press "r" in the console where
		// you ran "flutter run", or press Run > Hot Reload App in
		// IntelliJ). Notice that the counter didn't reset back to zero;
		// the application is not restarted.
		primarySwatch: Colors.blue,
	      ),
	      home: new MainApp(),
	    );
	  }


	}


	class MainApp extends StatefulWidget {
	  MainApp({Key key}) : super(key: key);

	  // This widget is the home page of your application. It is stateful,
	  // meaning that it has a State object (defined below) that contains
	  // fields that affect how it looks.

	  // This class is the configuration for the state. It holds the
	  // values (in this case the title) provided by the parent (in this
	  // case the App widget) and used by the build method of the State.
	  // Fields in a Widget subclass are always marked "final".

	  @override
	  _MainApp createState() => new _MainApp();
	}
	class _MainApp extends State<MainApp>{



	  @override
	  Widget build(BuildContext context) {
	    return new Scaffold(
	      appBar: new AppBar(
		  title: new Text("first scaffold"),
		  actions: <Widget>[
		    new IconButton(
		      icon: new Icon(Icons.home),
		      onPressed: () {
		        ()=>print("ignore upper bar");
		      },
		    ),
		  ]
	      ),
	      //this code seems to be make the input box disappear while typing
	      body: new Scaffold(
		  body: new TextField(
		onChanged: (String s)=>print("clicked search" + s),
		decoration: const InputDecoration(
		icon: const Icon(Icons.search),
		),
	      ),
	    ),


	    );
	  }
	}
```

![screenshot_20170722-165246](https://user-images.githubusercontent.com/771339/28495357-f45ae092-6efe-11e7-871d-88e612bce0d5.png)

Affected application using the code above

```
    body:  new TextField(
        onChanged: (String s)=>print("clicked search" + s),
        decoration: const InputDecoration(
        icon: const Icon(Icons.search),
        ),
      ),
```

![screenshot_20170722-165328](https://user-images.githubusercontent.com/771339/28495359-04bf4162-6eff-11e7-8312-64a02e307ea8.png)

Unaffected screenshot by removing the scaffold.

If you are getting an exception in the logs, and your code is implicated in the first few frames, then please include the source code for the functions involved.

## Logs

Run your application with `flutter run` and attach all the log output.

`Launching lib/main.dart on SM G900P in debug mode...
Running 'gradle assembleDebug'...                    12.2s
Built build/app/outputs/apk/app-debug.apk (26.8MB).
Installing build/app/outputs/apk/app.apk...           8.5s
Syncing files to device SM G900P...                   4.9s

🔥  To hot reload your app on the fly, press "r". To restart the app entirely, press "R".
An Observatory debugger and profiler on SM G900P is available at: http://127.0.0.1:8106/
For a more detailed help message, press "h". To quit, press "q".
I/flutter (29089): clicked searchh
I/flutter (29089): clicked searchhh
I/flutter (29089): clicked searchhhj
`

Run `flutter analyze` and attach any output of that command also.

## Flutter Doctor

Paste the output of running `flutter doctor` here.
`flutter doctor
[✓] Flutter (on Linux, locale en_US.UTF-8, channel alpha)
    • Flutter at /home/rice/flutter
    • Framework revision d36e2f6191 (4 weeks ago), 2017-06-21 15:09:10 -0700
    • Engine revision b0dee695ec
    • Tools Dart version 1.24.0-dev.6.7

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.0)
    • Android SDK at /home/rice/Android/Sdk
    • Platform android-26, build-tools 26.0.0
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] Android Studio (version 2.3)
    • Android Studio at /opt/android-studio
    • Gradle version 3.2
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.1)
    • Flutter plugin version 15.1
    • Dart plugin version 171.4694.29

[✓] Connected devices
    • SM G900P • 8e90eeee • android-arm • Android 7.1.2 (API 25)
`
> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by Hixie** [comment]
I'd strongly recommend refactoring your application to not have to nest scaffolds.

But we should figure out what's going on and either fix it or document it, certainly.

**Comment by hungrymonkey** [comment]
I already re factored it, since I can reproduce it reliability. I already figured out a workaround.

I am just annoyed that there isnt an error message whatsoever.

**Comment by Hixie** [comment]
Yeah we should definitely make this better.

**Comment by hungrymonkey** [comment]
Btw, thanks for this framework. It was easier to learn than pure android.

**Comment by Rockvole** [comment]
I think this could be improved just with better naming. Perhaps something like PageScaffold instead of Scaffold. 

Scaffold to me is something which you can plug things into, but doesnt signify that its for a whole page in an App. So, having a Scaffold inside a Scaffold which contains a textfield and a button would seem logical to me. But if it was called PageScaffold it would make me think its for a whole page only.
Just my 2c
