### ISSUE TITLE
[CP] Null exception fix

### ISSUE THREAD

**Issue by justinmc** [flutter/flutter#113550]
### issue_link

https://github.com/flutter/flutter/issues/111095

### Commit Hash

d728539

### Target

stable

### pr_link

https://github.com/flutter/flutter/pull/113553

### Impacted Users

Android apps with text editing

### Impact Description

A null exception is thrown for users of text editing on Android.

### Workaround

  1. Patch the Flutter framework directly with this one line fix: https://github.com/flutter/flutter/pull/107683/files#diff-f5f93c879cef9a102adbf148583de9f3d9a05f9678fdcad7bde106f62200bb34

or

  2. Upgrade to master or any release that includes the fix PR (https://github.com/flutter/flutter/pull/107683).

### Risk

medium

### Test Coverage

yes

### Validation Steps

If this test passes, then the fix works: https://github.com/flutter/flutter/blob/f02cfd48dffe618da5cb74fdca58ecfaf4aa1c9e/packages/flutter/test/widgets/editable_text_test.dart#L425

**Comment by aprzedecki** [comment]
Would be great to include it in 3.4.0 release.

**Comment by itsjustkevin** [comment]
@LongCatIsLooong could you take a look at this cherry-pick request?

**Comment by absar** [comment]
Can it be prioritized, it's regressing allover

**Comment by HansMuller** [comment]
LGTM

**Comment by justinmc** [comment]
Can this be closed now that the PR is merged or is the process to wait? https://github.com/flutter/flutter/pull/113553

**Comment by CaseyHillers** [comment]
> Can this be closed now that the PR is merged or is the process to wait? https://github.com/flutter/flutter/pull/113553

We wait until it has officially shipped to users. I expect us to remain on schedule, and ship this tomorrow (11/02) at 10 AM PST. Afterwards, I'll close the CP requests that were merged.

The reason we do this is occasionally a breakage is revealed in CI, and we have to revert a CP.

**Comment by CaseyHillers** [comment]
This was released in 3.3.7
