### ISSUE TITLE
Engine rolls failing due to bot m9 device setup issue, iOS 16 simulator runtime is missing

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#113539]
The builds here:

https://ci.chromium.org/ui/p/flutter/builders/try/Mac%20module_test_ios/19507/overview
https://ci.chromium.org/ui/p/flutter/builders/try/Mac%20plugin_test_ios/10656/overview

both failed due to issues setting up the device. It looks like both failures are from the same bot.

**Comment by nehalvpatel** [comment]
Taking a look now.

**Comment by zanderso** [comment]
Ahh, I see. Thanks for clarifying. In any case, it looks like there's a configuration or corruption issue of some sort.

**Comment by nehalvpatel** [comment]
Yes, definitely. I've posted some more in #113548 and am continuing to look into it.

**Comment by nehalvpatel** [comment]
Huh, looks like the roller's subsequent #113549 got merged.

**Comment by nehalvpatel** [comment]
For these tests, there are hundreds of error logs saying `com.apple.platform.watchos' is an unknown platform identifier`. Some searching indicates that this is because [Xcode failed to download symbol files](https://developer.apple.com/forums/thread/3380).

**Comment by nehalvpatel** [comment]
Actually, looks like a bunch of Mac bots are failing tasks because of similar issues. Saw some logs that mentioned `'com.apple.platform.appletvos' is an unknown platform identifier.`

This could be related to Apple servers having intermittent issues delivering symbols?

**Comment by jmagman** [comment]
> Actually, looks like a bunch of Mac bots are failing tasks because of similar issues. Saw some logs that mentioned `'com.apple.platform.appletvos' is an unknown platform identifier.`
> 
> This could be related to Apple servers having intermittent issues delivering symbols?

That is harmless Xcode spew and wouldn't cause issues.

This is the error:
```
iOS 16.0 is not installed. To use with Xcode, first download and install the platform
```
and the iOS 16 simulator runtime isn't installed:
```
== Runtimes ==
== Devices ==
```
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8800049303561604241/+/u/list_simulators/stdout

Should look like:
```
== Runtimes ==
iOS 16.0 (16.0 - 20A5339d) - com.apple.CoreSimulator.SimRuntime.iOS-16-0
== Devices ==
```

**Comment by jmagman** [comment]
Maybe related to https://bugs.chromium.org/p/chromium/issues/detail?id=1373792 https://chromium-review.googlesource.com/c/infra/infra/+/3949129 but that was reverted 4 days ago https://chromium-review.googlesource.com/c/infra/infra/+/3954022

**Comment by nehalvpatel** [comment]
That's interesting. So it seems like that patch might also have unrelated problems on macOS?

Although, the error in this log is a little confusing: https://logs.chromium.org/logs/infra-internal/buildbucket/cr-buildbucket/8800453334844672401/+/u/load_packages_from_desired_repos/git_checkout/stdout

The file path there uses forward slashes instead of Windows-style backwards, and it doesn't start with a drive, which is kind of unusual for Windows.

Maybe the file length issue is not Windows-specific?

**Comment by jmagman** [comment]
I don't know about that, just a guess since it's a recent `mac_toolchain` change, but I'm not sure the timing makes any sense.  It's likely failing intermittently because some bots have the simulator runtime cached but others don't.  Not sure if clearing the Xcode cache will make it start passing on the failing bots or start failing on the passing bots.

**Comment by nehalvpatel** [comment]
Yea, that'd be a good test. I don't have SSH access to the bots so I can't trigger a cache clear. I submitted a request for access but likely won't be able to get approval until tomorrow.

Is there a way to inspect the cache otherwise? I'm curious to see if the runtime is there or not.

**Comment by nehalvpatel** [comment]
Quick link to failing Mac tasks: https://chromium-swarm.appspot.com/tasklist?c=name&c=created_ts&c=pending_time&c=duration&c=bot&c=pool-tag&c=state&d=desc&et=1666043676901&f=pool-tag%3Aluci.flutter.try&f=state%3ACOMPLETED_FAILURE&f=os-tag%3AMac-12&k=os-tag&s=created_ts&st=1665956501000

A good amount of them have the `iOS 16.0 is not installed` issue.

**Comment by godofredoc** [comment]
Moving to P2 as this is not impacting all the builds

**Comment by zanderso** [comment]
7 out of the last 8 engine roll attempts have failed on this issue, so I think this was correctly marked P0.

**Comment by godofredoc** [comment]
Are the rolls failing on a different test? https://ci.chromium.org/p/flutter/builders/try/Mac%20module_test_ios is shown all green

**Comment by godofredoc** [comment]
Same with plugin tests: https://ci.chromium.org/p/flutter/builders/try/Mac%20plugin_test_ios

**Comment by zanderso** [comment]
I'm not sure what you mean by all green, but from the above discussion, my understanding is that any test that needs a simulator could potentially fail if the bot it runs on is in a bad state.

**Comment by nehalvpatel** [comment]
We think it's related to specific bots having polluted Xcode runtimes cache and are looking into the cause.

I've narrowed it down to these four bots:
- build841-m9
- build866-m9
- build892-m9
- build903-m9

**Comment by godofredoc** [comment]
This is most likely caused by some builds using simulator runtimes property and polluting the cache. We should either remove that functionality or using it everywhere to make it consistent.

**Comment by nehalvpatel** [comment]
I think in the meantime, we could quarantine these bots?

**Comment by godofredoc** [comment]
@zanderso we probably need to update the documentation for ticket queue bug priorities https://github.com/flutter/flutter/wiki/Infra-Ticket-Queue but we meant to assign P0s for cases where the tree is completely broken, P1 for something that is impacting the trees and that the gardener will be actively work on, and P2s something that will be addressed after the P0s and P1s are fixed.

**Comment by zanderso** [comment]
The engine sheriff playbook says that we should mark roller blockages as P0 since they indicate a build breakage. This policy is consistent with https://github.com/flutter/flutter/wiki/Issue-hygiene#priorities.

**Comment by nehalvpatel** [comment]
It looks like these bots can't be manually quarantined. We're testing a temp fix right now with the intention of working on a permanent fix afterwards.

A workaround for now is to re-run tasks on a non-effected bot.

**Comment by jmagman** [comment]
> This is most likely caused by some builds using simulator runtimes property and polluting the cache. 

That's only used on one engine builder, and I believe a lot of work was done to separate out those caches.  But it's been using that for a very long time, why would this have just started?
https://github.com/flutter/engine/blob/afcf153d28cee2e107c61354b84051d6fec7cf12/.ci.yaml#L326

**Comment by godofredoc** [comment]
It has been failing all the time since we implemented that functionality the reason is now failing more frequently is because there are more builders with polluted caches and 3 retries are not enough anymore to consistently pass builds.

**Comment by godofredoc** [comment]
https://flutter-review.googlesource.com/c/recipes/+/34860 will fix the problem to the expense of more cold xcode caches.

**Comment by nehalvpatel** [comment]
> https://flutter-review.googlesource.com/c/recipes/+/34860 will fix the problem to the expense of more cold xcode caches.

This Xcode cache change was blocked from rolling due to the problematic "cross_arch_tests" tests described in PR #113569. That PR has landed on flutter/flutter and the autoroller is rolling it into flutter/plugins (https://github.com/flutter/plugins/pull/6588), but I'm not sure if we're blocked by that.

Once the Xcode cache change's tryjobs resolve successfully and it lands, we should be getting the iOS 16 simulator properly on all relevant tasks going forward.

**Comment by zanderso** [comment]
Engine rolls appear to still be failing on this issue https://github.com/flutter/flutter/pull/113653

**Comment by nehalvpatel** [comment]
Looking now to verify that this recipe change has rolled to the bots.

**Comment by godofredoc** [comment]
The recipe change will start recovering the instances where the cache is polluted. I'd expect the full recovery to take a couple of days but we should definitely see this failures less frequently.

**Comment by godofredoc** [comment]
@ricardoamador @nehalvpatel to clean the caches you can use something like:

`led get-builder 'luci.flutter.try:Mac module_test_ios' > fix.json` adding a new property to the `$flutter/osx_sdk` property of the json file.

Before:
```
"$flutter/osx_sdk": {
                      "sdk_version": "14a5294e"
 }
```

After:
```
"$flutter/osx_sdk": {
        "sdk_version": "14a5294e",
        "cleanup_cache": true
 }
```

And finally run in the failing build using something like:

`cat fix.json | led edit -d id=build888-m9 | led edit-system -p 20 | led launch -modernize`

**Comment by ricardoamador** [comment]
Good to know! Thank you for this information.

**Comment by zanderso** [comment]
The Engine rolls have been failing for the past 12+ hours. I have stopped the autoroller to try to get some of them landed manually. I'm worried that other failures are being masked by this issue. Is there an ETA on when the bots will be in a good state?

**Comment by godofredoc** [comment]
Sent a CL for the nuclear option but we really need to decide how to proceed here. https://flutter-review.googlesource.com/c/infra/+/34884

Available options:

* Increase in execution time by 5 mins
* Remove all the uses of xcode with runtimes
* Remove all the uses of xcode runtimes with default runtimes
* Allocate a couple of SWE quarters to implement xcode runtimes properly(not sure we can afford this before Q3 2023).

**Comment by nehalvpatel** [comment]
I've kicked off tasks with the `cleanup_cache` command on 3 bots that are still in a bad state. (build866-m9, build892-m9, build903-m9)

**Comment by zanderso** [comment]
If it's only 5 minutes, then we can temporarily increase cycle times.

**Comment by keyonghan** [comment]
Just F.Y.I. our 90th% Mac host only targets queue time has been above 10mins (our SLO is 5 mins) for a while. I would expect this extra 5 min in every build execution to increase our queue time further.

**Comment by jmagman** [comment]
Has anyone reached out to the `mac_toolchain` folks to see if anything changed on their end?  This was stable for awhile.  Removing all tests that that use the iOS simulator would be a huge amount of our test coverage.

**Comment by zanderso** [comment]
Removing iOS simulator coverage is not an option. For starters it is required by internal customers.

**Comment by godofredoc** [comment]
Most likely they were never stable but just hidden by retries and by the fact that bots were slowly getting into a bad state until we hit critical mass.

The proposal is not to remove the tests but have a single CIPD package including all the simulators. This is how we used to provide xcode and proven to be stable.

**Comment by godofredoc** [comment]
@zanderso can we re-enable the rolls? I'd like to monitor if always cleaning the cache fixes the problem.

**Comment by jmagman** [comment]
It's not just engine rolls, a lot of framework PRs hit this as well, for example https://ci.chromium.org/p/flutter/builders/try/Mac%20build_tests_1_4/29861.

> Most likely they were never stable but just hidden by retries and by the fact that bots were slowly getting into a bad state until we hit critical mass.

We would have caught that by these tests being flaky.  It seems like it really exploded a few days ago.  The `mac_toolchain` people may know if anything changed recently that could cause the simulator caching logic to change.

**Comment by godofredoc** [comment]
Sound

> It's not just engine rolls, a lot of framework PRs hit this as well, for example https://ci.chromium.org/p/flutter/builders/try/Mac%20build_tests_1_4/29861.

This is expected, bots are shared between engine and framework builds and tests.

> 
> > Most likely they were never stable but just hidden by retries and by the fact that bots were slowly getting into a bad state until we hit critical mass.
> 
> We would have caught that by these tests being flaky. It seems like it really exploded a few days ago. The `mac_toolchain` people may know if anything changed recently that could cause the simulator caching logic to change.

Automated retries would definitely hide these issues. Caches are managed at the bot level mac_toolchain does not include any logic for caching.

**Comment by godofredoc** [comment]
> the stacked failures I was worried about. We ca



> @godofredoc The engine rolls have hit the stacked failures I was worried about. We can't just restart the autoroller since the PRs will definitely fail due to those other issues. Instead, when those issues are resolved, I'm going to manually create small rolls and shepherd them in before restarting.

Sounds good, @nehalvpatel can you please monitor failures in mac builders to ensure things are cleaning up properly.

**Comment by jmagman** [comment]
> This is expected, bots are shared between engine and framework builds and tests.

The engine->framework roll is in the framework, not the engine. 

Also: why is this only happening in the try pool?  I haven't seen it happen in prod.

**Comment by godofredoc** [comment]
> > This is expected, bots are shared between engine and framework builds and tests.
> 
> The engine->framework roll is in the framework, not the engine.
> 
> Also: why is this only happening in the try pool? I haven't seen it happen in prod.

Good question, potential reasons: prod builds not jumping back and forth in between old/new commits, less traffic in prod compared to try?

**Comment by godofredoc** [comment]
Seems like the failure is coming from a release candidate branch that does not have the logic to clean the caches.

**Comment by jmagman** [comment]
> prod builds not jumping back and forth in between old/new commits, less traffic in prod compared to try?

Maybe someone put out a PR branched on a really old commit and that corrupted the cache for all the bots used to build those tests?

**Comment by godofredoc** [comment]
> > prod builds not jumping back and forth in between old/new commits, less traffic in prod compared to try?
> 
> Maybe someone put out a PR branched on a really old commit and that corrupted the cache for all the bots used to build those tests?

Release candidate branch builds do this all the time

**Comment by jmagman** [comment]
Then maybe we need to go back to explicit caches? https://github.com/flutter/flutter/pull/103175

**Comment by zanderso** [comment]
Trying to roll the Engine one commit https://github.com/flutter/flutter/pull/113727. Is this the same failure?

**Comment by godofredoc** [comment]
That build does not have the cleanup_cache property.

**Comment by jmagman** [comment]
> Then maybe we need to go back to explicit caches? #103175
> 
> ```
> {"name": "osx_sdk_13a233", "path": "osx_sdk"},
> ```

@CaseyHillers has context for this

**Comment by godofredoc** [comment]
> > Then maybe we need to go back to explicit caches? #103175
> > ```
> > {"name": "osx_sdk_13a233", "path": "osx_sdk"},
> > ```
> 
> @CaseyHillers has context for this

I'd recommend to take a different approach and  create a design doc before applying more patches. Most of the things we have tried so far have either increased execution time or introduce flakiness.

**Comment by godofredoc** [comment]
A bug for removing the complexity of how properties are passes to cocoon, backend, infra configs and recipes: https://github.com/flutter/flutter/issues/113732

**Comment by zanderso** [comment]
Sorry if this is still expected, but I'm still seeing this issue: https://ci.chromium.org/ui/p/flutter/builders/try/Mac%20build_tests_1_4/29956/overview.

**Comment by godofredoc** [comment]
Just landed a couple of changes, we may need a rebase to pick up the changes in .ci.yaml. For new builds we are expecting a `clean_cache` in the `$flutter_osx_sdk` property.

![image](https://user-images.githubusercontent.com/54371434/197008388-1f534f0e-1d3d-49e2-bad5-944313732db7.png)

**Comment by godofredoc** [comment]
New builders are picking up the property correctly:

![image](https://user-images.githubusercontent.com/54371434/197033389-c51afc49-9539-48ca-b638-41ca92b243e2.png)

**Comment by godofredoc** [comment]
@keyonghan can you please help us get some info about the increase in execution, queue time? this will help prioritize the work needed to remove the caches cleanup.

**Comment by godofredoc** [comment]
@zanderso everything seems to be working correctly now, can we close this bug? we'll open a new one to track the work to remove the cache cleanup step.

**Comment by zanderso** [comment]
sgtm.
