### ISSUE TITLE
Null in _suggestions

### ISSUE THREAD

**Issue by ManishKumarChudasama** [flutter/flutter#113608]
final _suggestions = <WordPair>[];

should have at least one wordpair:
final _suggestions = <WordPair>[WordPair.random()];

otherwise null safety will be invalid.

**Comment by danagbemava-nc** [comment]
Hi @ManishKumarChudasama, I assume you're following the [Write your first flutter app codelab](https://docs.flutter.dev/get-started/codelab#step-2-use-an-external-package). 

If that is the case `_suggestions` has a type of `<WordPair>[]` which means that the list does not allow any null entries. So it is not necessary to add any items to the list to enforce null safety. 

The type of the list already enforces that. 

See https://dart.dev/null-safety/understanding-null-safety for more information on how null safety works in dart. 

I'll be closing this as there is nothing wrong with the codelab code. 

Thank you
