### ISSUE TITLE
in_app_purchase not fetching available products in iOS for live version. It works fine in both Sandbox and Testflight.

### ISSUE THREAD

**Issue by abinmittu** [flutter/flutter#113696]
I have a subscription added and got approved in iOS. I am able to complete a purchase in sandbox as well as in Test Flight. But  in live version ```InAppPurchase.instance.queryProductDetails``` returns an empty list. I have seen multiple people reporting this issue. If anyone knows a solution to this, please help.

**Comment by danagbemava-nc** [comment]
Hi @abinmittu, have you completed all the required setup steps in the appstore? 

Do you get any errors in whatever monitoring system you're using?

**Comment by abinmittu** [comment]
Yes. I have completed all the required steps. I'm using version 3.0.7. I'm not sure if it is some issue from Apple's side. Because a lot of people are complaining in their developer forum ([https://developer.apple.com/forums/thread/13324](https://developer.apple.com/forums/thread/13324)). Some said it will take 24-48 hours after the approval for IAP to show up.

**Comment by danagbemava-nc** [comment]
How long has it been since the upload to the store? 

I'm not sure this is an issue from the plugin because if it was an issue with the plugin, it probably wouldn't have worked in testflight or locally
