### ISSUE TITLE
Implement Stepper horizontal back and forth navigation buttons (just needs tests)

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#11361]
@andryfailli provided a patch to implement Stepper horizontal back and forth navigation buttons, it just needs tests before we can land it: https://github.com/flutter/flutter/pull/11165
See also #11133.

**Comment by sethladd** [comment]
Looks like the PR for this issue was closed. Should we close this issue?

**Comment by Hixie** [comment]
@sethladd The issue was opened because the PR was closed.

**Comment by Alexays** [comment]
Steppers in general don't have a test yet ?

**Comment by craiglabenz** [comment]
Closing this, as #23310 formalized customization options for stepper controls.
