### ISSUE TITLE
[codelabs]: Boring to Beautiful Code snippets marked up incorrectly

### ISSUE THREAD

**Issue by wednesdei** [flutter/flutter#113649]
The following codelab:

https://codelabs.developers.google.com/codelabs/flutter-boring-to-beautiful#2

Uses a dark-to-light icon that changes the background of the code snippet section from dark to light. It should be a copy icon, which copies the code snippet to the clipboard. 

Please replace theme changing icon + action to copy icon + copy action

**Comment by domesticmouse** [comment]
Fix is in flight.

Googlers: cl/513441101

**Comment by wednesdei** [comment]
I was working on a new codelab today and noticed the same issue here: https://codelabs.developers.google.com/codelabs/flutter-animated-responsive-layout?hl=en#0 

![Screenshot 2023-03-02 132514](https://user-images.githubusercontent.com/44120439/222544694-7f110593-d24c-49be-9b5c-7ca1cdb4a0d6.png)

Does the fix apply to all the existing codelabs, or just the one I identified above? Thanks for making the fix :)

**Comment by domesticmouse** [comment]
Looks like I need to dig deeper

**Comment by domesticmouse** [comment]
Googlers: cl/513733889

**Comment by domesticmouse** [comment]
Running cl/533658168 as an update to see if the codelabs backend is fixed. I can't see the differences in the generated markdown. 

le sigh

**Comment by domesticmouse** [comment]
The missing copy icon issue is tracked in https://github.com/flutter/flutter/issues/128081
