### ISSUE TITLE
[image_picker] `NSPhotoLibraryUsageDescription` is still required if uploading to the App Store

### ISSUE THREAD

**Issue by alex-sandri** [flutter/flutter#113603]
In [`image_picker`'s README](https://github.com/flutter/plugins/blob/main/packages/image_picker/image_picker/README.md) is stated:

> This permission is not required for image picking on iOS 11+ if you pass `false` for `requestFullMetadata`.

And while this is true for testing, when uploading the app build to the App Store after a few minutes of processing I received this email:

> Dear Developer,
>
> We identified one or more issues with a recent delivery for your app, "*app-name*" *app-version* (*app-build-number*). Please correct the following issues, then upload again.
>
> ITMS-90683: Missing Purpose String in Info.plist - Your app‘s code references one or more APIs that access sensitive user data. The app‘s Info.plist file should contain a NSPhotoLibraryUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. If you're using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. For details, visit: https://developer.apple.com/documentation/uikit/protecting_the_user_s_privacy/requesting_access_to_protected_resources
>
> Best regards,
>
> The App Store Team

I suggest updating the README with some note about production builds as I don't think that there is a way to avoid this issue without removing functionality from the plugin (but I'm not an iOS dev so I might be wrong).

**Comment by exaby73** [comment]
Hello @alex-sandri. Thank you for raising this issue. Labelling it for further insights from the team.

**Comment by jmagman** [comment]
This note is from https://github.com/flutter/plugins/pull/5915.  @PiotrMitkowski were you able to publish your app without `NSPhotoLibraryUsageDescription` at some point?

**Comment by PiotrMitkowski** [comment]
@jmagman right now my app is in closed beta, so we were able only to Apple Testflight. For this step, it wasn't complaining that I need to add `NSPhotoLibraryUsageDescription` (I've received the email with warnings, but there was nothing about the mentioned description). We're going public in a couple of weeks, so I can get back to the topic once it's done.

**Comment by PiotrMitkowski** [comment]
@jmagman I confirm, that I've received the same information, as @alex-sandri after my recent upload to TestFlight. Even if the app itself doesn't need the permissions and `NSPhotoLibraryUsageDescription` value, it still contains the iOS native code for opening the gallery in mode that requires both permissions and the description.

I think that we can mention it in the docs - if `requestFullMetadata` is `false`, the gallery permission isn't required, but `NSPhotoLibraryUsageDescription` still has to be provided to fulfill the Apple AppStore guidelines
