### ISSUE TITLE
Codecov should only report on PRs with `packages/flutter` changes

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#113625]
The script is only measuring `packages/flutter` test coverage, but that report is commenting on PRs with no changes to `packages/flutter`
https://github.com/flutter/flutter/blob/bd4376ca0ad5b46c42b374a0db007f82c0879426/.github/workflows/coverage.yml#L24

For example, my `packages/flutter_tools` PR reported there was no coverage change. https://github.com/flutter/flutter/pull/113585#issuecomment-1281670730

https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-including-paths

**Comment by jmagman** [comment]
cc @godofredoc

**Comment by christopherfujino** [comment]
I'm thinking this might be leftover config from when we enabled this for tool PRs.

**Comment by jmagman** [comment]
> I'm thinking this might be leftover config from when we enabled this for tool PRs.


You mean I hit something transient with that PR and it's now resolved?  If so we can close this and my PR and reopen if we see it again.

**Comment by godofredoc** [comment]
I would expect that, but I like that we are limiting the workflow to changes in the packages directory, it is currently very expensive to run on every commit (~90m).

**Comment by godofredoc** [comment]
Can we close this bug?

**Comment by jmagman** [comment]
SGTM, will reopen if I spot this again.

**Comment by jmagman** [comment]
Hm I hit this again https://github.com/flutter/flutter/pull/114558#issuecomment-1331264682

**Comment by godofredoc** [comment]
Closing as non reproducible. Please reopen if you see this again.
