### ISSUE TITLE
auto label is removed, Something went wrong while executing your query

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#113646]
> auto label is removed for flutter/flutter, pr: 113627, Failed to merge pr#: 113627 with Something went wrong while executing your query. Please include `C93A:9606:154FCFD:2BAD573:634F02FA` when reporting this issue..

https://github.com/flutter/flutter/pull/113627#issuecomment-1282922317

**Comment by jmagman** [comment]
Happened a second time on the same PR:
https://github.com/flutter/flutter/pull/113627#issuecomment-1282996968

**Comment by ricardoamador** [comment]
This seems different. I have never seen that error before. I'll take a look.

**Comment by ricardoamador** [comment]
I have opened an issue with Github. Apparently this is some kind of issue within their backend an the graphql client. I will make updates here when I hear back from them.

**Comment by nehalvpatel** [comment]
Hey, any updates on this? @ricardoamador. It looks like this issue has not happened since.

**Comment by ricardoamador** [comment]
Yeah we can close this. I made a change to use ssh and we won't see this issue any longer.
