### ISSUE TITLE
Rename `luci-flutter` GitHub check to something LUCI-agnostic

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#113624]
This check shouldn't require understanding what the Chromium LUCI CI system is in order to understand it is the status of the top-of-tree post-submit tests, and that it being red doesn't mean you have a problem with your PR.  Rename to something that doesn't reference "LUCI".  

Ideas:
- Top-of-tree tests
- Top-of-tree closure
- Post-submit tests
- HEAD test status

**Comment by Hixie** [comment]
* main-branch-status
* main-branch-closure
* tree-status

**Comment by jmagman** [comment]
Cirrus's equivalent action is clearer, `submit-queue` with the note "Cirrus CI failed on main".  
<img width="316" alt="Screen Shot 2022-10-18 at 12 40 17 PM" src="https://user-images.githubusercontent.com/682784/196528002-a13a9c7c-fc60-4b9e-bb7d-961c50aadd10.png">

If the API allows a note like that it would be great to add more clarity:

"tree-status -- CI tests failed on master branch"

**Comment by stuartmorgan** [comment]
Dup of https://github.com/flutter/flutter/issues/92931?

**Comment by jmagman** [comment]
Sounds like it, closing.
