### ISSUE TITLE
firebase_core :      not supported Issue

### ISSUE THREAD

**Issue by shivapardheep** [flutter/flutter#113600]
Xcode 14.0.1  not supported firebase_core, in Flutter sdk: ">=2.17.6 <3.0.0" . How to solve this?

**Comment by exaby73** [comment]
Hello @shivapardheep. This issue is better raised in the [flutterfire repository](https://github.com/firebase/flutterfire). Please raise it there as this doesn't have anything to do with Flutter itself. Closing this issue for the same reason. Thank you.
