### ISSUE TITLE
`luci-flutter` GitHub check "Details" link should link to cocoon Flutter dashboard, not LUCI console

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#113617]
Currently links to https://ci.chromium.org/p/flutter/g/flutter/console, should link to https://flutter-dashboard.appspot.com/#/build.  

Non-Googlers do not seem to have access to the former?

**Comment by jmagman** [comment]
@godofredoc where does this link come from? I thought it would be in cocoon but I don't see it...

**Comment by keyonghan** [comment]
Now both framework and engine are using go/flutter-build, we should update the link: https://github.com/flutter/cocoon/blob/main/app_dart/lib/src/request_handlers/push_build_status_to_github.dart#L65

BTW: we are migrating plugins/packages to LUCI, and after that all should be consistent.

**Comment by jmagman** [comment]
Ah, the `${slug.name}` tricked my cocoon grepping, I looked for it! 🙂
