### ISSUE TITLE
auto-submit bot should leave `autosumit` label when PR doesn't meet approvers requirement

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#113638]
Today, if a PR has the `autosubmit` label but does not meet the required two flutter hackers approving, the bot will comment an explanatory message and remove the `autosubmit` label. However, if the PR laters gets the required approvals, someone will have to re-add the `autosubmit` label. Instead, the bot should never remove the label, so that once a PR with the label receives the required approvals, the bot will merge it.

**Comment by christopherfujino** [comment]
cc @ricardoamador

**Comment by keyonghan** [comment]
Maybe we want to add a threshold to remove the label if no response, otherwise auto submit bot just repeats processing same PR again and again.

**Comment by ricardoamador** [comment]
For the rules here:
* If changes are requested then the label is removed automatically.
* Team Members (flutter-hackers) will never have the label removed for review as they count towards the review.
* Non-Team Members will need at least one review at the time the label is added to not have it removed.

**Comment by ricardoamador** [comment]
Closing as fixed based on this change: https://github.com/flutter/cocoon/pull/2922
