### ISSUE TITLE
_HeroFlight._performAnimationUpdate(heroes.dart:566). Null Check Operator used on null value

### ISSUE THREAD

**Issue by lukeshomni** [flutter/flutter#113604]
I am using Hero for animating images.

<details>
<summary>Error</summary>

Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: Null check operator used on a null value. Error thrown Instance of 'ErrorDescription'.
       at _HeroFlight._performAnimationUpdate(heroes.dart:566)
       at _HeroFlight._handleAnimationUpdate(heroes.dart:586)
       at AnimationLocalStatusListenersMixin.notifyStatusListeners(listener_helpers.dart:233)
       at AnimationLocalStatusListenersMixin.notifyStatusListeners(listener_helpers.dart:233)
       at ReverseAnimation._statusChangeHandler(animations.dart:292)
       at AnimationLocalStatusListenersMixin.notifyStatusListeners(listener_helpers.dart:233)
       at AnimationLocalStatusListenersMixin.notifyStatusListeners(listener_helpers.dart:233)
       at AnimationController._checkStatusChanged(animation_controller.dart:815)
       at AnimationController._tick(animation_controller.dart:831)
       at Ticker._tick(ticker.dart:238)
       at SchedulerBinding._invokeFrameCallback(binding.dart:1146)
       at SchedulerBinding.handleBeginFrame.<fn>(binding.dart:1059)
       at _LinkedHashMapMixin.forEach(_LinkedHashMapMixin.java)
       at SchedulerBinding.handleBeginFrame(binding.dart:1057)
       at SchedulerBinding._handleBeginFrame(binding.dart:976)

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

[✓] Flutter (Channel stable, 3.3.2, on macOS 12.6 21G115 darwin-arm, locale en-GB)
    • Flutter version 3.3.2 on channel stable at /Users/lukeshkolhe/downloads/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e3c29ec00c (5 weeks ago), 2022-09-14 08:46:55 -0500
    • Engine revision a4ff2c53d8
    • Dart version 2.18.1
    • DevTools version 2.15.0

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/lukeshkolhe/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A309
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] Connected device (4 available)
    • ASUS Z01RD (mobile)    • J9AAGF11F9909VN                      • android-arm64  • Android 10 (API 29)
    • iPhone 14 Pro (mobile) • 351368F3-CF0D-4300-9D9F-3F1F60FDAE39 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-0 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.6 21G115 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 105.0.5195.125

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```
```

</details>

**Comment by exaby73** [comment]
Hello @lukeshomni. Thank you for filing this issue. Can you please provide the following information?

- A [complete and minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). Ideally, a single `main.dart` file that can be run directly.
- The output of `flutter run-v`

Please provide the information in the form of text. See how to make collapsible sections with Markdown [here](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-collapsed-sections).

**Comment by lukeshomni** [comment]
Hello @exaby73 Sorry for the inconvenience. This is my first time creating an issue.

Above issue is not really reproducible. I have added Firebase Crashlytics in my app. It never appears while debugging. This exception gets logged only in production. 
This issue occurs when user visits scanItemScreen from product screen. both have hero widget with a image inside.
<details><summary>product.dart</summary>
<p>

```
class ProductCard extends StatelessWidget {
  const ProductCard({
    Key? key,
  }) : super(key: key);
  @override

  Widget build(BuildContext context) {
    return Column(
      children: [
        Padding(
          padding: const EdgeInsets.only(top:14.0),
          child: GestureDetector(
            onTap: () async {
                visitScanItemPage(context);
              }
            },
            child: Card(
              shape: RoundedRectangleBorder(
                borderRadius: const BorderRadius.all(Radius.circular(8)),
              child: Padding(
                padding: const EdgeInsets.only(top:12.0),
                child: Column(
                  children: [
                    IntrinsicHeight(
                      child: Row(
                        children: [
                          Padding(
                            padding: const EdgeInsets.only(left:24.0),
                            child: Hero(
                              tag: locationItem.id!,
                              child: OmnifulImage(
                                itemName: locationItem.product?.name?? '',
                                url:locationItem.product!.image?.path,
                                width: 87,
                                height: 87,
                                fit: BoxFit.fitHeight,
                                isBundle: locationItem.isBundle == 1,
                                expandable: true,
                              )
                            ),
                          ),
                        ],
                      ),
                    ),
                  ],
                ),
              ),
            ),
          ),
        )
      ],
    );
  }
  visitScanItemPage(BuildContext context, BatchHubLocationsItem locationItem, PickingModel pickingModel) async {
    final results = await Navigator.of(context).pushNamed(ScanItemWidget.tag);
  }
}
```
</p>
</details>
<details><summary>scan_item.dart</summary>
<p>

```

class ScanItemWidget extends StatelessWidget {
  const ScanItemWidget({Key? key}) : super(key: key);
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        backgroundColor: Colors.white,
        body: SafeArea(
            child: ListView(
          children: [
            Padding(
              padding: const EdgeInsets.all(16.0),
              child: Card(
                shape: const RoundedRectangleBorder(
                    borderRadius: BorderRadius.all(Radius.circular(8))
                ),
                child: Row(
                  children: [
                    Padding(
                      padding: const EdgeInsets.only(left:24.0, right: 24, top: 8, bottom: 8),
                      child: Hero(
                          tag: locationItem.id!,
                          child: OmnifulImage(
                            url:locationItem.product?.image?.path,
                            width: 90,
                            height: 90,
                            isBundle: locationItem.isBundle == 1,
                            itemName: locationItem.product?.name,
                            expandable: true,
                          )
                      ),
                    )
                  ],
                ),
              ),
            )
          ],
        )));
  }

```
</p>
</details>

**Comment by exaby73** [comment]
Unfortunately, with a reproducible sample, this issue will be tough to take action on. Have you tried reproducing it on release mode?
