### ISSUE TITLE
TextField cursor color does not match state spec in error state

### ISSUE THREAD

**Issue by esouthren** [flutter/flutter#113750]
`TextField`s in error states should have a cursor color which matches other error themed colors:

Material 2 Spec:
![34VHXF3dJcX4VzJ (1)](https://user-images.githubusercontent.com/15033982/196933304-e21b2ea7-b10d-43d0-a451-05e12ccee115.png)

Material 3 Spec:
![AUuETGJ23o4Gs6m](https://user-images.githubusercontent.com/15033982/196933061-29e6dd61-29d9-49ef-be88-6934cb935fa4.png)

However, this is not set in the Material theme and falls back to [`colorScheme.primary`]:(https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/app.dart#L931) 

Current implementation:
![5yZF8fphsHEkqET](https://user-images.githubusercontent.com/15033982/196934491-618dc8d7-a12f-42b1-9a26-771e13786ea4.png)

The `TextField` widget derives its `cursorColor` property from itself, or defers to a `TextSelectionTheme`. The `InputDecoration` which supplies themed properties to the `TextField` does not have a `selectionTheme` field. I would propose adding it to `InputDecoration`.

**Comment by Piinks** [comment]
@TahaTesser or @bleroux are either of you interested in adding this to your queue? No worries if not. :)

**Comment by TahaTesser** [comment]
> @TahaTesser or @bleroux are either of you interested in adding this to your queue? No worries if not. :)

Thanks! Will take a look.
