### ISSUE TITLE
Infra failure in Mac_ios complex_layout_ios__start_up

### ISSUE THREAD

**Issue by hellohuanlin** [flutter/flutter#113718]
The tree is closed now. Looks like the infra failure is quite flaky (2 infra fails recently): https://ci.chromium.org/p/flutter/builders/prod/Mac_ios%20complex_layout_ios__start_up

message: 

Infra Failure: Step('Upload metrics.upload results') (retcode: 64)

**Comment by nehalvpatel** [comment]
Have you seen this since? Looks like it was a flake. It would be helpful next time if you could link to the build in question. Thanks!

**Comment by ricardoamador** [comment]
Closing as this is a year old and no response was provided. Please reopen if this occurs again and add to the ticket queue.

**Comment by keyonghan** [comment]
Test has been passing consistently. Closing as obsolete.
