### ISSUE TITLE
[google_maps_flutter] While resizing google map on dark mode on iOS strange white background is visible.

### ISSUE THREAD

**Issue by axilos** [flutter/flutter#113721]
This bug happens on iOS (real iPhone and iOS Simulator). On Android (real phone and simulator) looks fine.

## Steps to Reproduce

1. Use the latest 2.2.1 version of Google Maps for Flutter.
2. Put GoogleMap widget anywhere in your code.
3. Try to resize it up and down.

Take a look on the screenshot taken during GoogleMap resizing.

![Screenshot_3](https://user-images.githubusercontent.com/1719544/196780660-8a09aa6d-c739-4111-a4d8-3768585879d1.png)

**Comment by darshankawar** [comment]
@axilos Thanks for the report. There's similar issue open describing your case, https://github.com/flutter/flutter/issues/106335, so please follow-up in it for further updates.
Closing as duplicate. If you disagree, write in comments and I'll reopen it.
