### ISSUE TITLE
Text editing RTL

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#11375]
Text fields need to have a bidi cursor that shows what direction they are going in.

**Comment by Hixie** [comment]
Specifically:
- [ ] It should be possible to tap between LTR text and RTL text on both ends. For example in "3WERBEH english2 1WERBEH", you should be able to tap on either end of the english text.
- [ ] On Android, when a cursor is between text of different directions, it should show the cursor in both locations. The side that is near the LTR text should be a half-cursor on the bottom, the part that is near the RTL text should be a half-cursor on the top.

**Comment by srix55** [comment]
Any updates on RTL support for widgets? I'm writing an app that displays in both arabic & english.

**Comment by Hixie** [comment]
rtl is basically done, this is one of the few remaining issues.

**Comment by justinmc** [comment]
@Hixie Do you know where you got the idea of 2 cursors at a bi-di boundary? Is this still the behavior that we want for Flutter?

@LongCatIsLooong Suggested putting the cursor under the character that would be deleted with a backspace. Maybe that's unconventional, though.

**Comment by Hixie** [comment]
It's what Android did when I filed the bug. I don't know if they still do it.

Our text fields should be identical to the platform text fields (at least by default, but in general I think these are complicated enough that we shouldn't further complicate them by adding our own twist on these behaviours, just implementing all the platforms' default behaviours is confusing enough as it is).

**Comment by justinmc** [comment]
I agree about keeping the same behavior as the platform. I think I can close this issue unless you see anything we're still missing.

It looks like native Android no longer has 2 cursors for bi-di (this is Keep):

<img width="200" src="https://github.com/flutter/flutter/assets/389558/01d5e715-d57e-49ff-b874-4d6555e07fdc" />

Also it seems like it's possible to place the cursor wherever I tap in bi-di text in Flutter now:

[Screencast from 2024-03-22 10-49-39.webm](https://github.com/flutter/flutter/assets/389558/c79dbe5c-e338-46f8-884b-5933acc2b609)

**Comment by justinmc** [comment]
To be clear, Flutter still has problems with RTL text editing, but those are tracked in other issues.
