### ISSUE TITLE
[proposal] Provide GUI for flutter_tools

### ISSUE THREAD

**Issue by AlexV525** [flutter/flutter#113739]
Consider adding a user interface when using flutter_tools, or maybe another naming tool.

## Use case

Provides all functionalities that the CLI-based tools do. #39939 and #63619 are only proposing GUI for the Flutter installer.

Similar or sub-tools are:
- https://github.com/YazeedAlKhalaf/Flutter_Installer
- https://github.com/fluttertools/sidekick

## Proposal

Today Flutter plugins in IDEs provide a flexible experience when creating and managing projects. It could be a good point that Flutter has its own GUI tool, to provide statistical data, or manipulate projects' basic info. It's still argumentative whether it's a good proposal, but we can discuss it. 😃 Also, I'm willing to make such a tool if the proposal is approved.

**Comment by darshankawar** [comment]
@AlexV525 
I think this proposal is similar to below open issues:

https://github.com/flutter/flutter/issues/63619
https://github.com/flutter/flutter/issues/39939

So I suggest to follow-up in them for further updates. I will close this in favor of linked issue. If you disagree or think your proposal is different from above, please write in comments and I'll reopen it.

**Comment by AlexV525** [comment]
@darshankawar Thanks for the triage! But I think here we are targeting a wider section that **provides all functionalities that the CLI-based tools do**, not only as an installer. Would it be helpful in explaining my proposal?

**Comment by darshankawar** [comment]
Thanks for the feedback @AlexV525. 

> Would it be helpful in explaining my proposal?

Sure. You may also link the issues I shared above for reference so that the team would get more idea as how your proposal is different from them.

Reopening.

**Comment by christopherfujino** [comment]
@AlexV525 what would the added value be in an officially-maintained GUI? There are already the officially supported IDE plugins which are essentially GUIs, and the ecosystem is free to create open source tools such as sidekick.

**Comment by gspencergoog** [comment]
(Desktop Triage) The consensus of the triage attendees agrees with Chris: the community is free to create GUI interfaces, and we already maintain a GUI for two IDEs. We'll leave this open for discoverability purposes, but it is not a priority for implementation.

**Comment by AlexV525** [comment]
> what would the added value be in an officially-maintained GUI?

> There are already the officially supported IDE plugins which are essentially GUIs, and the ecosystem is free to create open source tools such as sidekick.

> and we already maintain a GUI for two IDEs. We'll leave this open for discoverability purposes

There are two major reasons why I think we can have an official GUI.

### Flutter is typically an interface toolkit

When it uses a Flutter-based from the first start step, it can well-impressed users like Hey, Flutter builds Flutter.

### Plugins for IDEs are lacking high-level integration with most of the features

Maintaining plugins for two IDEs is as expected, for now, since they're related to development management, such as running/testing configurations, part of DevTools, Flutter Outline, command runner, etc.
But other things like Flutter config, dependencies version management, l10n management, screenshot captures and management. Well, a lot of management stuff can be done, and a desktop app makes Flutter tools GUI-friendly for desktop users (because users on desktops prefer clicking, rather than typing all the time). More generally, GUI is what Flutter goods at, and CLI is what Dart goods at.

**Comment by christopherfujino** [comment]
I am going to close this as unplanned. I think for those who want a more visual experience than the CLI tool, the VSCode extension is the recommended, supported method.
