### ISSUE TITLE
`test.dart` error output is repeated at end of test run 3x

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#113790]
The test harness runs failing tests 3 times to check if they are flakes.  This causes the error message to be repeated three times at the end of the run.

Example:
```
Not all build targets cached after second run.
The target performance data was: {"targets":[{"name":"gen_localizations","skipped":true,"succeeded":true,"elapsedMilliseconds":5},
...
Not all build targets cached after second run.
The target performance data was: {"targets":[{"name":"gen_localizations","skipped":true,"succeeded":true,"elapsedMilliseconds":5},
...
Not all build targets cached after second run.
The target performance data was: {"targets":[{"name":"gen_localizations","skipped":true,"succeeded":true,"elapsedMilliseconds":5},
```
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8800186219406896625/+/u/run_test.dart_for_build_tests_shard_and_subshard_1_3/test_stdout

This pushed the  `For your convenience, the error messages reported above are repeated here:` header off the GitHub snippet:
https://github.com/flutter/flutter/pull/112733/checks?check_run_id=8913158233

![Screen Shot 2022-10-20 at 1 23 28 PM](https://user-images.githubusercontent.com/682784/197050505-5b730303-32c0-4404-a345-1ef2c9dc4fb7.png)

cc @Hixie  #109206

**Comment by Hixie** [comment]
I'm not sure what any part of this message means ("Not all build targets cached after second run. The target performance data was: [...]"). Is it useful? Can we drop it entirely?

(FWIW, I would rather we re-run only passing tests and consider any test failing the moment it fails, than ever rerun failing tests. If we run a test and it fails, then we know it's a failing test, even if it might pass sometimes.)

**Comment by jmagman** [comment]
> I'm not sure what any part of this message means ("Not all build targets cached after second run. The target performance data was: [...]"). Is it useful? Can we drop it entirely?

I'm not familiar with that test at all, so maybe it is useful to someone.  It's more that it was a relatively long output, and printing it 3x adds noise.

**Comment by Hixie** [comment]
I haven't noticed this recently (and other people in the triage meeting say the same thing), but in general for this kind of bug, if you see it, I encourage you to fix it, because otherwise it's not likely to get solved. The `test.dart` script is communal property and doesn't have an owner.
