### ISSUE TITLE
Calling `WidgetTester.startGesture` with a trackpad kind throws

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#113773]
Reproduction:

```
testWidgets('trackpad', (WidgetTester tester) async {
  await tester.startGesture(const Offset(50, 50), kind: PointerDeviceKind.trackpad);
});
```

results in

```

══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following assertion was thrown running a test:
'package:flutter/src/gestures/events.dart': Failed assertion: line 1440 pos 15: '!identical(kind,
PointerDeviceKind.trackpad)': is not true.

When the exception was thrown, this was the stack:
#2      new PointerDownEvent (package:flutter/src/gestures/events.dart:1440:15)
#3      TestPointer.down (package:flutter_test/src/test_pointer.dart:139:12)
#4      TestGesture.down.<anonymous closure> (package:flutter_test/src/test_pointer.dart:459:35)
#7      TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:71:41)
#8      TestGesture.down (package:flutter_test/src/test_pointer.dart:458:27)
#9      WidgetController.startGesture (package:flutter_test/src/controller.dart:898:18)
<asynchronous suspension>
<asynchronous suspension>
(elided 5 frames from class _AssertionError, dart:async, and package:stack_trace)

The test description was:
  trackpad
════════════════════════════════════════════════════════════════════════════════════════════════════
Test failed. See exception logs above.
The test description was: trackpad
```

@dkwingsmt @moffatman

**Comment by moffatman** [comment]
Would it be better to add a new startTrackpadGesture, or make startGesture, moveBy, and others send the trackpad-specific events if we have trackpad kind?

**Comment by dkwingsmt** [comment]
Yeah. Do any real devices dispatch down events with `trackpad`? If not we should add an assertion.

**Comment by moffatman** [comment]
There is no device which will dispatch down events with trackpad. Anyone synthesizing those events in a test is testing the wrong thing. But this is kind of a special case compared to the other device types, so it would be good to have a clear assertion error message, and alternative methods with the same convenience to test some sequence of movements.

**Comment by dkwingsmt** [comment]
Yeah. But I wonder if `startTrackpadGesture` is a good idea. IIRC real devices will dispatch normal-kinded events and trackpad-kinded events on the same `.device` number, and if so, shouldn't the test just create a normal pointer (such as `touch`?) and panzoom emulation will automatically dispatch events of the same device# for kind `.trackpad`.

**Comment by dnfield** [comment]
Here's an example of a test that used to pass but is failing: https://github.com/superlistapp/super_editor/blob/87d922e326314aedcb2bd3136b48c9deb50658dc/super_editor/test/super_editor/supereditor_scrolling_test.dart#L11

How would you write this test?

**Comment by moffatman** [comment]
That test was written months after the assertion change, I don't think it ever could have passed. And it never tested actual trackpad gestures functionality (by sending panZoom etc events). But it's true that it can't be done with `TestGesture` at the moment, only with the slightly more low-level `TestPointer`. So that should be fixed so it's easier to write tests of trackpad gesture functionality.

**Comment by dnfield** [comment]
The assertion change didn't roll into stable until after that test was written. It passes on an older stable.

**Comment by dnfield** [comment]
(I don't know enough about this to know whether it was actually testing the right thing or not though)

**Comment by moffatman** [comment]
Ah, I checked and the original enum changes including `PointerDeviceKind.trackpad` were in 3.0, but nothing else until 3.3. 
See here for some example of testing with other methods: https://github.com/flutter/flutter/blob/59d26c481acca4e5b086dc6502b45ca31b273c25/packages/flutter/test/gestures/drag_test.dart#L1510

**Comment by dnfield** [comment]
Yes - I think for this issue it would be sufficient to just document what the right way to test this modality is, and to add some asserts so that when users do the wrong thing they get directed to the right thing.
