### ISSUE TITLE
local_auth package is not working with PIN/Pattern

### ISSUE THREAD

**Issue by andreslowenstein** [flutter/flutter#113777]
## Steps to Reproduce

Hi, i'm using local_auth 2.1.2 in my proyect.
When I use an emulator with Android <10, I have this issue.
I only set up a pattern, but when I call the function authenticate (with biometricOnly: false), the screen displays this
![image](https://user-images.githubusercontent.com/61715819/197017163-439e5788-74a5-4ba3-aac1-2bdb15056f66.png)

As you can see, I have a pattern setted
![image](https://user-images.githubusercontent.com/61715819/197017260-6839c896-a88d-42a0-adea-29899c4c91ad.png)

The strange thing is that when I download a project made exactly the same way (this is the video https://www.youtube.com/watch?v=h0XewJmWb04), it works for me in any version of android. Therefore I understand that there is a problem in my project.

I can't show my code because it's confidential, but believe me it's identical to how it's done in the video.

Flutter doctor
![image](https://user-images.githubusercontent.com/61715819/197020594-96fceb61-6ce8-4ad9-a5e7-ba8bb494d4b9.png)

**Comment by darshankawar** [comment]
@andreslowenstein 
I think this issue is similar to https://github.com/flutter/flutter/issues/108945.
Another issue that was closed in favor of the linked one above: https://github.com/flutter/flutter/issues/112519 and also see if this possible solution works in your case: https://github.com/flutter/flutter/issues/112519#issuecomment-1260372762

Closing as duplicate. If you disagree, write in comments and I'll reopen it.

**Comment by andreslowenstein** [comment]
@darshankawar I've tried with that solution but it wont solved my problem. I think the problem is in my AndroidManifest.xml or in my MainActivity.kt. It was modified for reasons unknown to me because it was done by a co-worker.
Do you see anything strange? I've already implemented FlutterFragment in my MainActivity.

**MainActivity**
`
package *****

import androidx.annotation.NonNull
import io.flutter.embedding.android.FlutterFragmentActivity
import io.flutter.embedding.android.FlutterActivity
import io.flutter.embedding.engine.FlutterEngine

import io.flutter.plugin.common.MethodChannel
import io.flutter.plugins.GeneratedPluginRegistrant

import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.EventChannel.EventSink

import android.content.Intent
import android.content.Context


import android.content.BroadcastReceiver


class MainActivity: FlutterFragmentActivity () {

    private val CHANNEL = "wallet/channel"
    private val EVENTS = "wallet/events"
    private var startString: String? = null
    private var linksReceiver: BroadcastReceiver? = null

    override fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine) {
        GeneratedPluginRegistrant.registerWith(flutterEngine)
        val intent2 = getIntent()
        startString = intent2.data?.toString()
        MethodChannel(flutterEngine.dartExecutor.binaryMessenger, CHANNEL).setMethodCallHandler { call, result ->
            if (call.method == "nani") {
                if (startString != null) {
                    result.success(startString)
                }
            }
        }
        EventChannel(flutterEngine.dartExecutor.binaryMessenger, EVENTS).setStreamHandler(
            object : EventChannel.StreamHandler {
                override fun onListen(args: Any?, events: EventSink) {
                    linksReceiver = createChangeReceiver(events)
                }

                override fun onCancel(args: Any?) {
                    linksReceiver = null
                }
            }
        )
    }

  override fun onNewIntent(intent: Intent) {
      super.onNewIntent(intent)
      if (intent.action === Intent.ACTION_VIEW) {
          linksReceiver?.onReceive(this.applicationContext, intent)
      }
  }

  fun createChangeReceiver(events: EventSink): BroadcastReceiver? {
      return object : BroadcastReceiver() {
          override fun onReceive(context: Context, intent: Intent) { // NOTE: assuming intent.getAction() is Intent.ACTION_VIEW
              val dataString = intent.dataString ?:
              events.error("UNAVAILABLE", "Link unavailable", null)
              events.success(dataString)
          }
      }
  }
}
`

**AndroidManifest**
`<manifest xmlns:android="http://schemas.android.com/apk/res/android"
	xmlns:tools="http://schemas.android.com/tools"
	package="com.ayj.wallet">
	
	<uses-permission android:name="android.permission.READ_CONTACTS" />
	<uses-permission android:name="android.permission.WRITE_CONTACTS" />
	<uses-permission android:name="android.permission.INTERNET" />
	<uses-permission android:name="android.permission.CAMERA" />
	<uses-permission android:name="android.permission.USE_FINGERPRINT" />

	<uses-permission android:name="android.permission.VIDEO_CAPTURE" />

	
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
	<application android:label="Fértil Suma" android:icon="@mipmap/launcher_icon" android:usesCleartextTraffic="true">
		<activity 
		android:exported="true"
		android:name=".MainActivity" 
		android:launchMode="singleInstance" 
		android:theme="@style/LaunchTheme" 
		android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode" 
		android:hardwareAccelerated="true" 
		android:windowSoftInputMode="adjustResize">
			
			

			<meta-data android:name="io.flutter.embedding.android.SplashScreenDrawable" android:resource="@drawable/launch_background" />

			
			<meta-data android:name="io.flutter.embedding.android.NormalTheme" android:resource="@style/NormalTheme" />


			<intent-filter>
				<action android:name="android.intent.action.MAIN" />
				<category android:name="android.intent.category.LAUNCHER" />
			</intent-filter>
			<intent-filter android:autoVerify="true" android:label="link_pago">
				<action android:name="android.intent.action.VIEW" />
				<category android:name="android.intent.category.DEFAULT" />
				<category android:name="android.intent.category.BROWSABLE" />
				
				<data android:scheme="https" />
				<data android:host="links.fertilsuma.com.ar" />
				<data android:pathPrefix="/app"/>
			</intent-filter>
			<intent-filter android:autoVerify="true" android:label="link_pago">
				<action android:name="android.intent.action.VIEW" />
				<category android:name="android.intent.category.DEFAULT" />
				<category android:name="android.intent.category.BROWSABLE" />
				
				<data android:scheme="http" />
				<data android:host="links.fertilsuma.com.ar" />
				<data android:pathPrefix="/app" />
			</intent-filter>


		</activity>
		<activity android:name="com.apptreesoftware.barcodescan.BarcodeScannerActivity" />
		<provider
			android:name="com.pichillilorenzo.flutter_inappwebview.InAppWebViewFileProvider"
			android:authorities="${applicationId}.flutter_inappwebview.fileprovider"
			android:exported="false"
			android:grantUriPermissions="true">
			<meta-data
				android:name="android.support.FILE_PROVIDER_PATHS"
				android:resource="@xml/provider_paths" />
		</provider>
		
		
		
		
		
		

	</application>
	<meta-data android:name="flutterEmbedding" android:value="2" />
</manifest>
`
