### ISSUE TITLE
Dialog and TimePicker/DatePicker RTL

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#11377]
These hopefully won't require much change but e.g. buttons in dialogs should be flipped around.

**Comment by abarth** [comment]
Inspecting the code for the DatePicker turned up one obvious issue with the next/prev month buttons.  I didn't see anything else, but we'll probably need to actually look at the UI.

**Comment by Hixie** [comment]
This looks like it's working great, but I'm leaving open to look at it again once we've confirmed the Icon RTL issue is resolved.
