### ISSUE TITLE
Google Maps Flutter setMapStyle not taking effect on Terrain Map Type

### ISSUE THREAD

**Issue by ARASHz4** [flutter/flutter#113749]
Custom style not effect when use Terrain Map Type in Google Map

**Comment by exaby73** [comment]
Hello @ARASHz4. Thank you for filing this issue. Can you please provide the following information?

- A [complete and minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). Ideally, a single `main.dart` file that can be run directly.
- The output of `flutter doctor -v`
- The output of `flutter run-v`

Please provide the information in the form of text. See how to make collapsible sections with Markdown [here](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-collapsed-sections).
