### ISSUE TITLE
Dropdown RTL

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#11370]

**Comment by Hixie** [comment]
The Dropdown widget needs to put the button on the other side in RTL.

**Comment by abarth** [comment]
We also need to flip the animation horizontally.

**Comment by Hixie** [comment]
The animation is horizontally symmetric, it turns out. But the alignment of the text was off.

**Comment by Hixie** [comment]
Fixed by https://github.com/flutter/flutter/pull/13040.
