### ISSUE TITLE
Tabs RTL

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#11372]
Tabs need to overflow left, align right, etc, in RTL.
See https://material.io/guidelines/usability/bidirectionality.html#bidirectionality-ui-mirroring-overview

**Comment by Hixie** [comment]
Also, in particular right now when I have RTL mode enabled, on the "Floating action button" demo in the gallery, the tab indicator paints wrong except for the left-most tab ("BLUE").

**Comment by abarth** [comment]
The RTL scrolling support should do most of what we need.  These pieces of code might also need some changing:

 * `_IndicatorPainter`
 * `_scrollToControllerValue`
