### ISSUE TITLE
[pigeon] Generated code for Kotlin and generated code for Dart not synced what triggering PlatformException

### ISSUE THREAD

**Issue by SERDUN** [flutter/flutter#113736]
My Dart host API
````
abstract class PHostApi {
  @async
  void setUp(POptions options);
}
 ````
  Part of Generated code for Kotlin 
```
...
   @Suppress("UNCHECKED_CAST")
   fun setUp(binaryMessenger: BinaryMessenger, api: PHostApi?) {    
       run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.PHostApi.setUp", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val wrapped = hashMapOf<String, Any?>()
            try {
              val args = message as List<Any?>
              val optionsArg = args[0] as POptions
              api.setUp(optionsArg) {
                reply.reply(null)
              }
            } catch (exception: Error) {
              wrapped["error"] = wrapError(exception)
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }    
    }
...
    
```

Part of Generated code for Dart
```
class PHostApi {

  Future<void> setUp(POptions arg_options) async {
    final BasicMessageChannel<Object?> channel =
        BasicMessageChannel<Object?>('dev.flutter.pigeon.PHostApi.setUp', codec, binaryMessenger: _binaryMessenger);
    final Map<Object?, Object?>? replyMap = await channel.send(<Object?>[arg_options]) as Map<Object?, Object?>?;
    if (replyMap == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyMap['error'] != null) {
      final Map<Object?, Object?> error = (replyMap['error'] as Map<Object?, Object?>?)!;
      throw PlatformException(
        code: (error['code'] as String?)!,
        message: error['message'] as String?,
        details: error['details'],
      );
    } else {
      return;
    }
  }
  }
  ```

  
  
Since our function "setUp" in PHostApi doesn't return anything, the kotlin side  just calls the callback with a null argument, which is interpreted as an error on the flutter side, I think the kotlin side should call the callback with an empty Map
```
           reply.reply(wrapped)
```

version: pigeon 4.2.3 

[✓] Flutter (Channel master, 3.5.0-9.0.pre.19, on macOS 12.6 21G115 darwin-x64, locale en)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.63.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

**Comment by huycozy** [comment]
Hi @SERDUN 
Thanks for the report! This is a known issue being tracked at #113187. 
Closing this issue as a duplicate, so please follow up on it for further updates.

**Comment by SERDUN** [comment]
> Hi @SERDUN Thanks for the report! This is a known issue being tracked at #113187. Closing this issue as a duplicate, so please follow up on it for further updates.

After the updated plugin it's fixed my request only part. 
Maybe I have been not clear.

But look.

In native code when the function is completed   callback use null as the argument 

```
 api.setUp(optionsArg) {
                                reply.reply(null)
                            }
```
 
it's logical because the dart function in the host API returns void
`Future<void> setUp(POptions arg_options) async {`

But if we look at more details host function 

```
final Map<Object?, Object?>? replyMap =
        await channel.send(<Object?>[arg_options]) as Map<Object?, Object?>?;
    if (replyMap == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    }
```

When I have null in "replyMap" I have an exception but all is correct.

For example, in java generation code using an empty map and all correct  and no exception for the same host function
