### ISSUE TITLE
[CP] Fix unimplemented NotifyingLogger.supportsColor

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#113765]
### issue_link

https://github.com/flutter/flutter/issues/113631

### Commit Hash

https://github.com/flutter/flutter/commit/e4b979679006a3a3a1160658892d9d93a67f5cc9

### Target

beta

### pr_link

[[Beta CP] Implement NotifyingLogger.supportsColor (#113635) #113768
](https://github.com/flutter/flutter/pull/113768)

### Impacted Users

Flutter developers using an IDE plugin will fail to flutter pub get

### Impact Description

Given that no users have reported this thus far, it may not visibly surface to the user; however, the tool process is crashing before pub get is allowed to fetch necessary pub packages.

This is the top crasher on beta 3.4.0-34.1.pre.

### Workaround

Run `flutter pub get` from the terminal in their app directory.

### Risk

low

### Test Coverage

yes

**Comment by christopherfujino** [comment]
@zanderso can you review this CP request?

**Comment by zanderso** [comment]
CP lgtm

**Comment by CaseyHillers** [comment]
@christopherfujino I'm closing this out as we'll be cutting a new beta next week that includes this fix.
