### ISSUE TITLE
Adjusting sample rate for sensor data (Sensors_plus package) when building for web?

### ISSUE THREAD

**Issue by bjornwinther1996** [flutter/flutter#113755]
There has been a discussion about adjusting the sample rate for sensor data in the Sensors_plus flutter package (https://github.com/flutter/flutter/issues/25971). (Sensors_plus is the only sensor package for web).

Following the above thread, I managed to adjust the rate when building for **Android**, by changing SENSOR_DELAY_NORMAL to SENSOR_DELAY_GAME. 

**Now my question is:** Is there a way to adjust the sampling rate when building for web?

**Comment by huycozy** [comment]
Hi @bjornwinther1996, `sensors_plus` is a third-party plugin, I would suggest filing that issue in its [plus_plugins repository](https://github.com/fluttercommunity/plus_plugins/issues). Closing as this is not related to Flutter.
