### ISSUE TITLE
[go_router] Make info of entire stack of routes accessible

### ISSUE THREAD

**Issue by TristanKing0** [flutter/flutter#113747]
## Use case
Often times a stack of routes is more complex than simple sub-routes and can loop around indefinitely, for example if I go from a job screen to a client screen (the client the job was for), to another job screen (another job done for the client), and then to a client on that screen, and so on.

There's no current way that I'm aware of to access the entire stack information, so that I could for example display it on a navigation bar as say [ Job 12 > SomeClient > Job 17 > AnotherClient ] and tap on any one to pop all the way back to it.

## Proposal
Expose the information of the whole current stack. Or maybe this needs to be a change to the sub-routes themselves? For example, a link from one sub-route to another that's declared higher up to allow for circular routing.

**Comment by chunhtai** [comment]
RouteMatchList is public now
