### ISSUE TITLE
drawAtlas no longer working

### ISSUE THREAD

**Issue by vlidholt** [flutter/flutter#1137]
It appears to be the case that Canvas drawAtlas is no longer working. In the game, the background stars are no longer draw, neither are particle systems.

To reproduce, run the game ( https://github.com/flutter/game ) and see no stars in the background of the main or game screen.

**Comment by abarth** [comment]
I probably broke it.

**Comment by sethladd** [comment]
Thanks for catching this, @vlidholt !

**Comment by abarth** [comment]
Looking now.

**Comment by abarth** [comment]
I haz fix.

**Comment by abarth** [comment]
Should be fixed now.
