### ISSUE TITLE
[web] Support `--no-prebuilt-dart-sdk` in the web engine

### ISSUE THREAD

**Issue by mdebbar** [flutter/flutter#113772]
Recently, the web engine build became reliant on prebuilt dart sdks (see https://github.com/flutter/engine/pull/36336, https://github.com/flutter/engine/pull/36851 and https://github.com/flutter/flutter/pull/113759).

That means we always use prebuilts and ignore the `--no-prebuilt-dart-sdk` flag.

This issue is about adding support for the `--no-prebuilt-dart-sdk` flag. If the flag is set, we build a dart sdk with the default host toolchain.

**Comment by dcharkes** [comment]
This is making the Flutter Dart HHH bot red currently.

https://ci.chromium.org/p/dart/g/flutter-hhh/console

```

Generating GN files in: out/host_debug
ERROR at //flutter/web_sdk/BUILD.gn:257:34: Undefined identifier in string expansion.
      "file:///" + rebase_path("$host_prebuilt_dart_sdk/.."),
                                 ^---------------------
"host_prebuilt_dart_sdk" is not currently in scope.
See //flutter/web_sdk/BUILD.gn:277:1: whence it was called.
_compile_outline("flutter_dartdevc_kernel_sdk_outline") {
^--------------------------------------------------------
See //flutter/BUILD.gn:97:26: which caused the file to be included.
        public_deps += [ "//flutter/web_sdk" ]
                         ^------------------
```

https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8799722016116422561/+/u/gn_--full-dart-sdk_--no-prebuilt-dart-sdk/stdout

Please consider reverting

* https://github.com/flutter/engine/pull/36851 

until this is addressed.

cc @eyebrowsoffire

**Comment by jason-simmons** [comment]
Landed https://github.com/flutter/engine/pull/36926

**Comment by whesse** [comment]
This issue does not seem to have been resolved completely, as building the wasm_release target with the --no-prebuilt-dart-sdk flag does not work.  The prebuilt_dart_sdk variable is unconditionally set to true in https://github.com/flutter/engine/pull/36851/files#diff-fed47f409f6a27a39fe7b0e6b3ebbceb645d295259e350614afeb8c0a3eecae2R636

Further work on making the wasm_release target build without a prebuilt Dart SDK is tracked in a new issue https://github.com/flutter/flutter/issues/119513 , and this issue can remain closed.
