### ISSUE TITLE
video_player plugin is accessing microphone

### ISSUE THREAD

**Issue by wijesijp** [flutter/flutter#113734]
In my flutter application I am using video_player ^2.0.0

I am using it to play video file from URL.

In my application I also have a video chat feature.

What I noticed was when  a video is playing with video_player, it is accessing the microphone also.

I am unable to use microphone with my chat application because it is being used by video_player.

Is there a way to disable microphone usage by video_player?

I don't see why the video_player would require access to the microphone.

**Comment by darshankawar** [comment]
@wijesijp 
Can you provide `flutter doctor -v`, a minimal code sample, platform on which you are seeing this behavior ?
Thanks.

**Comment by wijesijp** [comment]
[✓] Flutter (Channel stable, 2.5.3, on macOS 12.6 21G115 darwin-arm, locale en-LK)

    • Flutter version 2.5.3 at /Users/chamika/development/flutter

    • Upstream repository https://github.com/flutter/flutter.git

    • Framework revision 18116933e7 (1 year ago), 2021-10-15 10:46:35 -0700

    • Engine revision d3ea636dc5

    • Dart version 2.14.4



[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0)

    • Android SDK at /Users/chamika/Library/Android/sdk

    ✗ cmdline-tools component is missing

      Run `path/to/sdkmanager --install "cmdline-tools;latest"`

      See https://developer.android.com/studio/command-line for more details.

    ✗ Android license status unknown.

      Run `flutter doctor --android-licenses` to accept the SDK licenses.

      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.



[!] Xcode - develop for iOS and macOS

    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.

      Download at: https://developer.apple.com/xcode/download/

      Or install Xcode via the App Store.

      Once installed, run:

        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer

        sudo xcodebuild -runFirstLaunch

    • CocoaPods version 1.11.3



[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)

    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.



[✓] Android Studio (version 2021.3)

    • Android Studio at /Applications/Android Studio.app/Contents

    • Flutter plugin can be installed from:

      🔨 https://plugins.jetbrains.com/plugin/9212-flutter

    • Dart plugin can be installed from:

      🔨 https://plugins.jetbrains.com/plugin/6351-dart

    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)



[✓] VS Code (version 1.72.2)

    • VS Code at /Applications/Visual Studio Code.app/Contents

    • Flutter extension can be installed from:

      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter



[!] Connected device

    ! No devices available

I can't share code sample since it is used in commercial project 

When we try to access the microphone from our code we get 

_warning in module (source) reported: capture device could not be opened_

**Comment by darshankawar** [comment]
@wijesijp 
You are on older version of framework. Current version is 3.3.5. Also latest video_player plugin version is 2.4.7, so I suggest you to upgrade your setup to latest and try again to see if you still get same behavior or not.
