### ISSUE TITLE
While adding wrong value in date picker ui not properly shown in web 

### ISSUE THREAD

**Issue by MurtuzaSrashtaSoft** [flutter/flutter#113712]
While adding wrong value in date picker ui not properly shown in web 

SDK Detail

```
environment:
  sdk: '>=2.10.0 <2.20.0'
```

![Screenshot 2022-10-19 at 10 26 20 PM](https://user-images.githubusercontent.com/64843262/196756116-3074abae-048b-4d87-a0fc-e1aacbfd6a80.png)

**Comment by huycozy** [comment]
@MurtuzaSrashtaSoft, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this. Also, please provide the output of `flutter doctor -v` as well.
