### ISSUE TITLE
after upgrading flutter to 3.3.5. uppercase text P is not showing proper

### ISSUE THREAD

**Issue by bipin5711** [flutter/flutter#113889]
today i upgraded the flutter but the capital P and R text are breaking.

![image](https://user-images.githubusercontent.com/58762094/197346392-b447a4e9-97fa-419d-a883-b884eb477b9d.png)

![image](https://user-images.githubusercontent.com/58762094/197346523-71af280a-a88e-4b3f-9ed5-a4657d0815b1.png)

for fontweight 400 working fine but for 600 not working

const Text(
                        strRiverlandsRanch,
                        style: TextStyle(
                            color: colorDark2,
                            fontSize: 15,
                            fontWeight: FontWeight.w600),
                      ),
                      const Text(
                        strRiverlandsRanch,
                        style: TextStyle(
                            color: colorDark2,
                            fontSize: 13,
                            fontWeight: FontWeight.w400),
                      ),

**Comment by vcqn** [comment]
I don't experience the same issue:
![image](https://user-images.githubusercontent.com/46611348/197346772-0ed239f4-5bc8-4e8c-8447-3def1f3d24df.png)

**Comment by huycozy** [comment]
@bipin5711 
I also can not reproduce this issue on latest `stable` and `master` channel. Please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this. Also, please provide the output of `flutter doctor -v` as well.

**Comment by jason-simmons** [comment]
This may be similar to https://github.com/flutter/flutter/issues/112546

Try upgrading to the Flutter master branch
