### ISSUE TITLE
Error (Xcode): unable to spawn process '/usr/bin/gcc-4.0' (No such file or directory)

### ISSUE THREAD

**Issue by Siddeshwaraswamy** [flutter/flutter#113869]
## Steps to Reproduce
Created a fresh app using the following commands 

> flutter create test_flutter_app
> cd test_flutter_app

When I run the app using the command `flutter run`, I am getting the following error. 

```
Launching lib/main.dart on iPhone 14 Plus in debug mode...
Running Xcode build...                                                  
 └─Compiling, linking and signing...                        868ms
Xcode build done.                                            5.6s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    Writing result bundle at path:
    	/var/folders/32/bv7w9h090ddcq2y0n9b0g5x00000gp/T/flutter_tools.PcZNtf/flutter_ios_build_temp_dirBPqBjR/temporary_xcresult_bundle

    error: unable to spawn process '/usr/bin/gcc-4.0' (No such file or directory) (in target 'Runner' from project 'Runner')
    /Users/<user>/Library/Developer/Xcode/DerivedData/Runner-hcbnozmyxeuwuyfzmoumgzabukle/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.bu
    ild/Objects-normal/x86_64/GeneratedPluginRegistrant.dia:1:1: warning: Could not read serialized diagnostics file: error("Failed to open diagnostics file") (in
    target 'Runner' from project 'Runner')
    error: unable to spawn process '/usr/bin/gcc-4.0' (No such file or directory) (in target 'Runner' from project 'Runner')
    /Users/<user>/Library/Developer/Xcode/DerivedData/Runner-hcbnozmyxeuwuyfzmoumgzabukle/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.bu
    ild/Objects-normal/x86_64/Runner_vers.dia:1:1: warning: Could not read serialized diagnostics file: error("Failed to open diagnostics file") (in target
    'Runner' from project 'Runner')
    note: Building targets in dependency order
    warning: Run script build phase 'Run Script' will be run during every build because it does not specify any outputs. To address this warning, either add
    output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target
    'Runner' from project 'Runner')
    warning: Run script build phase 'Thin Binary' will be run during every build because it does not specify any outputs. To address this warning, either add
    output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target
    'Runner' from project 'Runner')

    Result bundle written to path:
    	/var/folders/32/bv7w9h090ddcq2y0n9b0g5x00000gp/T/flutter_tools.PcZNtf/flutter_ios_build_temp_dirBPqBjR/temporary_xcresult_bundle


Error (Xcode): unable to spawn process '/usr/bin/gcc-4.0' (No such file or directory)
```

I googled a lot to find some solution for this, but couldn't find anything useful. And reinstalled xcode, flutter, and simulator but nothing is working. But if I build it from xcode using the "Runner.xcworkspace", it works fine. 

## Flutter Doctor 

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.5, on macOS 12.6 21G115 darwin-x64, locale en-US)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
[✓] Chrome - develop for the web
[!] Android Studio (not installed)
[✓] VS Code (version 1.62.0)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

! Doctor found issues in 2 categories.

Any help is appreciated.

**Comment by huycozy** [comment]
@Siddeshwaraswamy 
Please share the output of command: `ls /usr/bin/ | grep gcc`. And please check if there is any `gcc` settings in environment variable from `.bashrc`, `.bash-profile`, `.zshrc`, or `.profile`. 

Also, you may want to check [this answer](https://coderwall.com/p/6-wusg/fix-for-make-usr-bin-gcc-4-2-no-such-file-or-directory) if it's helpful.

**Comment by Siddeshwaraswamy** [comment]
Found the issue. Thanks for your suggestion on .bash_profile. I copy/pasted some bash screen settings which had references to gcc, and after deleting that code everything started working fine. Thank you so much.

**Comment by Siddeshwaraswamy** [comment]
Thank you so much @huycozy 🙏
