### ISSUE TITLE
Remove REQUEST_INSTALL_PACKAGES permission from my project

### ISSUE THREAD

**Issue by Lazizbek97** [flutter/flutter#113886]
Google rejects my app updates because of REQUEST_INSTALL_PACKAGES permission. When i have checked it was inside the open_file package that is located  ->> /flutter/.pub-cache/hosted/pub.dartlang.org/open_file-3.2.1/android/src/main/AndroidManifest.xml.
I cleaned the project with 'flutter clean' and removed that package manually.(even replaced it with open_file_safe package ).
But when I run the project or build appbundle, it will appear again.

inside pubspec.yaml file, there is no such package.
I'm going to delete that permission, so that google accepts my next app updates.
<img width="1086" alt="Screen Shot 2022-10-22 at 16 51 32" src="https://user-images.githubusercontent.com/91660256/197338452-84c4d6c9-de90-4803-a5eb-2801d78bfe97.png">

I have attached that package's AndroidManifest.xml file.
[](url)

**Comment by huycozy** [comment]
@Lazizbek97 

>inside pubspec.yaml file, there is no such package.

There may be another package using `open_file` internally. You can check the Merged Manifests portion of the AndroidManifest.xml to see if you find that permission is being used in your project.

Please see old related issues: #108011, #111947 that may help you find clues. Also, I find there is an open issue on `open_file` repository that addressing this case: https://github.com/crazecoder/open_file/issues/204.

Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it. Thanks!
