### ISSUE TITLE
[web] font data fix regressed main.dart.js gz size by ~80 KB

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#113898]
It was important to land https://github.com/flutter/engine/pull/35646 asap, but it regressed the size of compressed `main.dart.js` by ~80 KB, even for trivial apps (since character ranges are always loaded). We should find a more optimal way of supplying character range data.

[Skia perf regression](https://flutter-flutter-perf.skia.org/e/?begin=1657752846&end=1666453395&queries=test%3Dweb_size__compile_test&requestType=0&selected=commit%3D30685%26name%3D%252Carch%253Dintel%252Cbranch%253Dmaster%252Cconfig%253Ddefault%252Cdevice_type%253DMoto_G__4_%252Cdevice_version%253Dandroid-24%252Chost_type%253Dlinux%252Csub_result%253Dbasic_material_app_dart2js_size%252Ctest%253Dweb_size__compile_test%252C)

<img width="770" alt="font-data-size" src="https://user-images.githubusercontent.com/211513/197364512-6d44cbb0-c19b-453e-809f-251cfba13120.png">

cc @hterkelsen

**Comment by mdebbar** [comment]
Filed a separate issue for lazy loading of font fallback data: https://github.com/flutter/flutter/issues/119547

Closing this one for now.
