### ISSUE TITLE
Transform.translate and GestureDetector Nesting causes onPanUpdate onPanStart onPanEnd, which cannot be used

### ISSUE THREAD

**Issue by zhangweihong** [flutter/flutter#113813]
**Transform. The transformation** of translate will lead to the failure of events of **GestureDetector** nested in child nodes, which is not only related to OnPan events。

**Comment by danagbemava-nc** [comment]
Hi @zhangweihong,

Can you please provide your `flutter doctor -v`  and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?

Please also provide the steps to reproduce.

Thank you
