### ISSUE TITLE
Opening the drawer in the Flutter Gallery app has RangeError (iOS)

### ISSUE THREAD

**Issue by xster** [flutter/flutter#11386]
Doesn't happen to gallery on head. 

`RangeError: Invalid value: Not in range 0..7, inclusive: 8` in the kitchen sync.

**Comment by Hixie** [comment]
@sethladd: @eseidel told me to assign it to you. :-P

**Comment by sethladd** [comment]
Is there a test for this?

Meanwhile, if it's not broken in HEAD, we can close this. Will push a new Gallery^H^H^H^HKitchenSink once perf/scrolling has been improved.

**Comment by sethladd** [comment]
Closing because the issue states this is fixed on HEAD
