### ISSUE TITLE
flutter detect if system is win10 or win11

### ISSUE THREAD

**Issue by jinfagang** [flutter/flutter#113832]
flutter detect if system is win10 or win11

**Comment by darshankawar** [comment]
@jinfagang 
Does this https://api.flutter.dev/flutter/dart-io/Platform-class.html help in your case ?

Can you also elaborate as how exactly are you looking for Flutter to detect it ?

**Comment by campovski** [comment]
`Platform` is insufficient. Take a look at [device_info_plus](https://pub.dev/packages/device_info_plus) plugin, that should solve your problem.

**Comment by stuartmorgan** [comment]
Flutter itself doesn't provide exact OS version detection as a built-in on any platform, so this is out of scope. As noted above, there are plugins for this.
