### ISSUE TITLE
`AnimationController`: Null check operator used on a null value

### ISSUE THREAD

**Issue by mzdm** [flutter/flutter#113895]
```java
E/flutter (15158): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
E/flutter (15158): #0      AnimationController.stop (package:flutter/src/animation/animation_controller.dart:785)
E/flutter (15158): #1      AnimationController.value= (package:flutter/src/animation/animation_controller.dart:367)
E/flutter (15158): #2      AnimationController.reset (package:flutter/src/animation/animation_controller.dart:388)
E/flutter (15158): #3      _NepanikarButtonState._onTap (package:nepanikar/widgets/nepanikar_button.dart:93)
E/flutter (15158): <asynchronous suspension>
```

## Steps to Reproduce

This obviously comes from the Flutter framework and should be(?) an easy fix. I think there should be an additional null check in animation_controller.dart:785 

```diff
- _ticker!.stop(canceled: canceled);
+ _ticker?.stop(canceled: canceled);
```

Since the project is open source, the causing widget is https://github.com/cesko-digital/nepanikar/blob/6b5ef3f520ea011346a973fb992dfe5892811b37/lib/widgets/nepanikar_button.dart. I can do reproducible sample if it is needed..

Flutter 3.3.2, channel stable

**Comment by jonahwilliams** [comment]
See: https://github.com/cesko-digital/nepanikar/blob/6b5ef3f520ea011346a973fb992dfe5892811b37/lib/widgets/nepanikar_button.dart#L90-L93

You call reset after an await, but you don't check if mounted. The problem is that your widget may have been disposed by that point, and your animation controller no longer has a ticker

**Comment by mzdm** [comment]
> See: https://github.com/cesko-digital/nepanikar/blob/6b5ef3f520ea011346a973fb992dfe5892811b37/lib/widgets/nepanikar_button.dart#L90-L93
> 
> You call reset after an await, but you don't check if mounted. The problem is that your widget may have been disposed by that point, and your animation controller no longer has a ticker

Oh ye you're right, it was a user error in the end.. thanks for the rapid response! 💙
