### ISSUE TITLE
Provision for simultaneous left and right navigation drawers absent in Scaffold widget

### ISSUE THREAD

**Issue by 5u3it** [flutter/flutter#11388]
Flutter's Scaffold documentation mentions that right navigation drawer is possible.
However, there is no provision to have both left and right navigation drawers to co-exist in a Scaffold.

https://flutter.io/widgets/material/ (in Scaffold documentation)
https://material.io/guidelines/layout/structure.html#structure-ui-regions (displayed in mobile structure mock-up)

**Comment by abarth** [comment]
Note: For RTL support, we should give this a name other than "right drawer".  In RTL, this secondary drawer should be on the left.

**Comment by sethladd** [comment]
PR from @5u3it is up: https://github.com/flutter/flutter/pull/12686

**Comment by HansMuller** [comment]
This feature was added, as "endDrawer" here: https://github.com/flutter/flutter/pull/12686
