### ISSUE TITLE
Consider using common prefixes for related components or group them differently

### ISSUE THREAD

**Issue by aghassemi** [flutter/flutter#1139]
For instance instead of 

```
GridViewport
MaxTileWidthGrid
ScrollableGrid
```

consider

```
GridViewport
GridWithMaxTileWidth
GridScrollable
```

Autocomplete in the IDE is one of the main ways for API discovery in my opinion and increasingly more important for APIs with a large surface area like Flutter. Having a common prefix for related components makes the discovery more effective as developer can quickly see different related components and can make a better decision on which one to use.

Another approach could be named (regular/factory) constructors on a common abstract class:

```
Gird.Scrollable
Grid.WithMaxTileWith
```

Alternatively I think having a thinner and more hierarchical namespace can replace the common prefix as well:

```
import 'package/flutter/material/gird' as grid.
grid.Scrollable
grid.WithMaxTileWidth
```

@abarth @sethladd

**Comment by Hixie** [comment]
We should do this sooner rather than later if we do it.

We should probably audit our docs to see what needs grouping, if anything.

**Comment by abarth** [comment]
Possible groups:

 - [ ] CustomLayout
 - [ ] Grid-related classes
 - [ ] Drag-and-drop classes
 - [ ] Curves
 - [ ] Table-related classes
 - [ ] Viewports
 - [ ] Route-related classes
 - [ ] Animation subclasses

I wonder if this could be better addressed by making dartdoc better.  For example, maybe you could tag classes and then be able to see all the classes associated with a tag.  That might allow for multi-way associations (e.g., something that is both related to grids and to viewports).

**Comment by abarth** [comment]
I guess that wouldn't help the autocomplete part...

**Comment by Hixie** [comment]
I think we should close this as too general.

On the whole, many of our related classes have very similar names. When they differ in their prefix, it's for good reasons, e.g. fitting the "FooBar" pattern for classes that extend Bar.

**Comment by abarth** [comment]
I did fix the specific issue with grid, so I'm ok closing this issue.
