### ISSUE TITLE
Andriod Studio(Doctor Crashed)

### ISSUE THREAD

**Issue by ameen-11** [flutter/flutter#113920]
☠] **Android Studio (the doctor check crashed)**
    X Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know
      about this issue at https://github.com/flutter/flutter/issues.
    X FileSystemException: Exists failed, path = 'C:\Program Files\Android\Android Studio" .plugins' (OS Error: The
      filename, directory name, or volume label syntax is incorrect.
      , errno = 123)****

**Comment by exaby73** [comment]
Hello @ameen-11. Can you post the full logs of `flutter doctor -v`?
