### ISSUE TITLE
Flutter run with --local-engine fails to build Error: Member not found: 'FragmentProgram.compile'.

### ISSUE THREAD

**Issue by MikePendo** [flutter/flutter#113939]
## Steps to Reproduce

1. Get local engine build according to instruction[ Development Environtment]( https://github.com/flutter/flutter/wiki/Setting-up-the-Engine-development-environment)
2. Compile the Engine 
3. Create test app 
4. run `flutter run --local-engine=ios_debug_sim_unopt`
I am getting 
## Logs
```
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    Writing result bundle at path:
        /var/folders/tn/44xg6n4d4533cjnk1t0df3bh0000gp/T/flutter_tools.v83Wqf/flutter_ios_build_temp_dirjkyHOF/temporary_xcresult_bundle

    ../../flutter/packages/flutter/lib/src/material/ink_sparkle.dart:532:41: Error: Member not found: 'FragmentProgram.compile'.
        _program = await ui.FragmentProgram.compile(spirv: data.buffer);
                                            ^^^^^^^
    ../../flutter/packages/flutter/lib/src/material/ink_sparkle.dart:558:21: Error: The method 'shader' isn't defined for the class 'FragmentProgram'.
     - 'FragmentProgram' is from 'dart:ui'.
    Try correcting the name to the name of an existing method, or defining a method named 'shader'.
        return _program.shader(
                        ^^^^^^
    Failed to package /Users/michaelrozenblat/Desktop/flutter_sample_app/test.
    Command PhaseScriptExecution failed with a nonzero exit code
    note: Building targets in dependency order
    warning: Run script build phase 'Thin Binary' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script
    phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'Runner' from project 'Runner')
    warning: Run script build phase 'Run Script' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script
    phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'Runner' from project 'Runner')

    Result bundle written to path:
        /var/folders/tn/44xg6n4d4533cjnk1t0df3bh0000gp/T/flutter_tools.v83Wqf/flutter_ios_build_temp_dirjkyHOF/temporary_xcresult_bundle
```

Flutter doctor -v:
 ```
Flutter (Channel stable, 3.3.3, on macOS 12.6 21G115 darwin-x64, locale en-IL)
    • Flutter version 3.3.3 on channel stable at /Users/mr/Desktop/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18a827f393 (4 weeks ago), 2022-09-28 10:03:14 -0700
    • Engine revision 5c984c26eb
    • Dart version 2.18.2
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/mr/Library/Android/sdk
    • Platform android-32, build-tools 32.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode-14.0.1.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.72.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (3 available)
    • iPhone 14 Pro (mobile) • 9D126FE8-96BA-4CE2-A35E-6B3BDBBC0DE8 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-0 (simulator)
    • macOS (desktop)        • macos                                • darwin-x64     • macOS 12.6 21G115 darwin-x64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 106.0.5249.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```
I have tried to clean, I reinstall the Engine from the scratch I tried to checkout the engine version to the exact flutter version I have on my Mac 3.3.3 [checkout](https://github.com/flutter/flutter/releases/tag/3.3.3) (although its not written in the docs, as far as I understand the _client sync_  should take the correct versions/branches). I have tried to put all the repos to master (engine and build root and build from there assuming there was some mismatch between the dart SDK and the engine)
Always getting the same error.
Please Help!

### Edit 
Found Similar issue [110786](https://github.com/flutter/flutter/issues/c)

**Comment by exaby73** [comment]
Hello @MikePendo. Unfortunately, I do not have a local engine to test this locally. Labelling this issue for further insights from the team.

**Comment by MikePendo** [comment]
@exaby73 
Thanks maybe some one else has?
General question should I checkout the engine (for specific commit) when building it (as I dont see it in the instructions).
Also when we build the Engine how is that related to correct dart SDK (assuming engine build is only for the native part)

**Comment by MikePendo** [comment]
@exaby73 maybe u have an idea what I can try ?

**Comment by mraleph** [comment]
The error typically indicates mismatch between your Flutter engine and Flutter framework. Make sure that your `src/flutter` is checked out at 5c984c26eb and the rest of the repo is synced with `gclient sync -f -D`. 

After that rebuild `ios_debug_sim_unopt` and `host_debug` configurations. 

Things should work after that, I think.

**Comment by zanderso** [comment]
The advice from @mraleph is sound. Closing this for now, but feel free to re-open if it doesn't work.

**Comment by MikePendo** [comment]
I have tried the exact same thong yesterday with `-f -D ` and still get the following error.
Now If I am trying it right
```
./flutter/tools/gn --ios --simulator --unoptimized
./flutter/tools/gn --unoptimized
ninja -C out/ios_debug_sim_unopt && ninja -C out/host_debug_unopt
```
 I am getting:
```
ninja: Entering directory `out/ios_debug_sim_unopt'
[3111/5848] ACTION //flutter/impeller/runtime_stage:flatc_runtime_stage_flatbuffers(//build/toolchain/mac:clang_x64)
FAILED: clang_x64/gen/flutter/impeller/runtime_stage/runtime_stage_flatbuffers.h
python3 ../../build/gn_run_binary.py clang_x64/flatc --warnings-as-errors --cpp --cpp-std c++17 --cpp-static-reflection --gen-object-api --filename-suffix _flatbuffers -o clang_x64/gen/flutter/impeller/runtime_stage ../../flutter/impeller/runtime_stage/runtime_stage.fbs
```

**Comment by MikePendo** [comment]
I will delete all the repos and will try to set everything from scratch once again

**Comment by mraleph** [comment]
@MikePendo before you delete everything we could try to diagnose. What does 

```
../../build/gn_run_binary.py clang_x64/flatc --warnings-as-errors --cpp --cpp-std c++17 --cpp-static-reflection --gen-object-api --filename-suffix _flatbuffers -o clang_x64/gen/flutter/impeller/runtime_stage ../../flutter/impeller/runtime_stage/runtime_stage.fbs
```

actually print if you try to run this manually from `out/ios_debug_sim_unopt`? If `clang_x64/flatc` is simply missing then maybe there is a bug in the `BUILD.gn` files.

**Comment by MikePendo** [comment]
Sure if it helps u to understand the problem 
I get:
`../../build/gn_run_binary.py: command not found`
BUT I do see that script

**Comment by MikePendo** [comment]
u r right (I should think about python):
`Traceback (most recent call last):
  File "/Users/mr/Desktop/engine/src/out/ios_debug_sim_unopt/../../build/gn_run_binary.py", line 23, in <module>
    subprocess.check_output(args, stderr=subprocess.STDOUT, universal_newlines=True)
  File "/usr/local/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/local/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/local/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 1845, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: './clang_x64/flatc'`

**Comment by MikePendo** [comment]
Did it help? Do u want me to run something else before I start set up everything from scratch

**Comment by mraleph** [comment]
@MikePendo What happens if you do `ninja -C . clang_x64/flatc`?

**Comment by MikePendo** [comment]
<img width="1586" alt="Screen Shot 2022-10-24 at 15 40 35" src="https://user-images.githubusercontent.com/56674958/197611501-72d9ab79-0bff-4920-a257-7df126658d80.png">

**Comment by MikePendo** [comment]
Still cant build
```
src git:(6af51ff) ninja -C out/ios_debug_sim_unopt && ninja -C out/host_debug_unopt
ninja: Entering directory `out/ios_debug_sim_unopt'
[2276/2726] ACTION //flutter/impeller/runtime_stage:flatc_runtime_stage_flatbuffers(//build/toolchain/mac:clang_x64)
FAILED: clang_x64/gen/flutter/impeller/runtime_stage/runtime_stage_flatbuffers.h
python3 ../../build/gn_run_binary.py clang_x64/flatc --warnings-as-errors --cpp --cpp-std c++17 --cpp-static-reflection --gen-object-api --filename-suffix _flatbuffers -o clang_x64/gen/flutter/impeller/runtime_stage ../../flutter/impeller/runtime_stage/runtime_stage.fbs

[2289/2726] CXX clang_x64/obj/third_party/skia/src/gpu/ganesh/ops/gpu.DashOp.o
ninja: build stopped: subcommand failed.
```

**Comment by MikePendo** [comment]
What binary should be build in calling_x64?
Do u want me too try something else ? Or will reset/fetch everything from scratch?

**Comment by mraleph** [comment]
This is very mysterious. Did `out/ios_debug_sim_unopt/clang_x64/flatc` disappear somehow? I don't understand why it fails. 

You could try to refetch things from scratch, though I doubt it will help.

**Comment by MikePendo** [comment]
@mraleph I am sorry somebody just contact me from security and they were blocking :
`Command Line: ./clang_x64/flatc --warnings-as-errors --cpp --cpp-std c++17 --cpp-static-reflection --gen-object-api --filename-suffix _flatbuffers -o clang_x64/gen/flutter/impeller/runtime_stage ../../flutter/impeller/runtime_stage/runtime_stage.fbs`
It still doesnt explains why I couldn't build the app with local engine when it compiled succefully yesterday 
As I did use the hash u provided (3.3.3) and `-D -f` on sync

**Comment by MikePendo** [comment]
> Did out/ios_debug_sim_unopt/clang_x64/flatc disappear somehow
Yes I was also looking for that file ... and could understand :)
