### ISSUE TITLE
IconButton does not provide control over splash color

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#11397]
Posse has asked for this.  Noted that FlatButton does allow controlling splash color:
https://docs.flutter.io/flutter/material/FlatButton-class.html
https://docs.flutter.io/flutter/material/IconButton-class.html

Thoughts? @Hixie @HansMuller

**Comment by Hixie** [comment]
We should certainly be consistent.

**Comment by HansMuller** [comment]
I'll do this. I need a b3k from i18n.

**Comment by HansMuller** [comment]
Fixed in https://github.com/flutter/flutter/pull/11524
