### ISSUE TITLE
[web][canvaskit] Images Disappear after Container have a image or color as background decoration

### ISSUE THREAD

**Issue by alijboor** [flutter/flutter#113933]
when give a Container  a background while i'm using platformViewRegistry.registerViewFactory & ImageElement 

the background appear above the image.

`    ui.platformViewRegistry.registerViewFactory(
        link,
        (int viewId) => ImageElement()
          ..src = link
);
    return link.isEmpty ? _errorImage : SizedBox(
        width: 50,
        height: 50,
        child: HtmlElementView(viewType: link));
`

image appear like that :
![image](https://user-images.githubusercontent.com/59504151/197509825-7a0e972a-0519-4a4d-83aa-db941a04b892.png)

and if i drag the image it shown under the background like this:

this image when i drag the image by mouse 

![image](https://user-images.githubusercontent.com/59504151/197509715-0c81e41e-6b52-4848-b017-412a3b099864.png)

**Comment by alijboor** [comment]
@yjbanov & @ditman

**Comment by alijboor** [comment]
flutter doctor -v
[√] Flutter (Channel stable, 3.3.1, on Microsoft Windows [Version 10.0.19044.2130], locale en-US)
    • Flutter version 3.3.1 on channel stable at C:\Users\HP\development\sdks\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4f9d92fbbd (7 weeks ago), 2022-09-06 17:54:53 -0700
    • Engine revision 3efdf03e73
    • Dart version 2.18.0
    • DevTools version 2.15.0

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc3)
    • Android SDK at C:\Users\HP\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.0-rc3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2021.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[√] VS Code (version 1.70.2)
    • VS Code at C:\Users\HP\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.36.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19044.2130]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 106.0.5249.119
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 106.0.1370.52

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

**Comment by exaby73** [comment]
Hello @alijboor. Please refrain from mentioning team members directly. Please provide a [complete and minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) so that I may verify the issue

**Comment by alijboor** [comment]
The ponds table:

CREATE TABLE person
(
      name varchar(30)
      , age int
);
Some sample data:

INSERT INTO person (name, age)
VALUES ('ali', 20)
     , ('mohammad', 19);


My query so far:

SELECT COUNT(name)
FROM person;


The output I'm getting:

value
2

**Comment by exaby73** [comment]
Sorry but I need a reproducible example for Flutter, not SQL. Can you please provide a sample application that doesn't use any 3rd party libraries?

**Comment by alijboor** [comment]
> Sorry but I need a reproducible example for Flutter, not SQL. Can you please provide a sample application that doesn't use any 3rd party libraries?

import 'package:flutter/material.dart';
import 'package:lapapp/home.dart';
import 'package:splashscreen/splashscreen.dart';

class Splashed extends StatelessWidget {
  const Splashed({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return SplashScreen(
      seconds: 6,
      navigateAfterSeconds:
          Directionality(textDirection: TextDirection.rtl, child: HomePage()),
      title: Text(
        'Home Lab Group',
        textScaleFactor: 2,
      ),
      image: Image.asset("images/logo.png"),
      loadingText: Text("تحميل ..."),
      photoSize: 100.0,
      loaderColor: Colors.blue,
    );
  }
}

**Comment by exaby73** [comment]
@alijboor Please read [complete and minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). I need a code sample I can run directly. Your code sample does not include a `main()`, and you are importing widgets from other files which are not included as part of the comment you posted. How am I supposed to run this code?

**Comment by alijboor** [comment]
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Welcome to Flutter',
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Welcome'),
        ),
        body: const Center(
          child: Text('Hello World From me'),
        ),
      ),
    );
  }
}
