### ISSUE TITLE
Document how to check if profile/release/debug mode in dart

### ISSUE THREAD

**Issue by emesx** [flutter/flutter#11392]
Please add the option to check what mode (slow, profile or release) the Flutter app is running in.
Scenario: I want to append the mode to some analytics we collect (so it has to be exposed to the Dart layer).

**Comment by Hixie** [comment]
If you're in release mode, `const bool.fromEnvironment("dart.vm.product")` will be true.
If you're in debug mode, `assert(() { ...; return true; });` will execute `...`.
If you're in profile mode, neither of the above will happen.

**Comment by Hixie** [comment]
But we should document that somewhere, or configure a variable accordingly or something.

**Comment by devoncarew** [comment]
There is a `profile()` method in progress here: https://github.com/flutter/flutter/pull/10966/files#diff-fa691172dd6cfc02a53caddd6ead6320

**Comment by emesx** [comment]
A variable / getter sounds reasonable, thanks!

**Comment by rock3r** [comment]
Any news on this?

**Comment by zoechi** [comment]
@rock3r won't happen short term as there is a simple workaround.

**Comment by rock3r** [comment]
@zoechi looks like there's a hack, yes, but it doesn't really seem great to me that there is no "is debug" or "mode = release/debug/profile" accessible to users.

I'm talking about an actual public API for this rather than some obscure and undocumented hack that relies on side effects. Seems very odd to me that a user friendly framework like flutter has nothing for this very simple and common scenario. I'd even be happy if the API internally used those hacks, as long as it's presented externally as a public API.

**Comment by zoechi** [comment]
I got that, but the workaround is easy enough and if you are working with Flutter since a while you might have noticed that a few other features that probably provide value to more developers are also missing ;-) So first things first.

**Comment by rock3r** [comment]
Sure, I understand priorities are different. Could think about doing a PR for that if you want though, it's such an easy win. Just point out where you'd like the API to live ;)

**Comment by zoechi** [comment]
Not my call. Perhaps @Hixie

**Comment by Matzu89** [comment]
@rock3r would be a good PR, quite surprised this is not already in there (explicitly). 

For me it makes sense to have this under the flutter package (`https://github.com/flutter/flutter/tree/master/packages/flutter/lib`), but let's wait for @Hixie to confirm this. Meanwhile, quickest way to get this into the repo might be by updating the docs :)

**Comment by jonahwilliams** [comment]
cc @goderbauer  - I believe the problem with exposing these as getters is that they didn't tree shake properly

**Comment by andrewackerman** [comment]
The debug workaround @Hixie provided doesn't seem to work anymore as written. To get it to work, I had to "call" the anonymous function as well. .ie. :

    assert(() { ...; return true; }());

**Comment by gspencergoog** [comment]
Yes, I just added `kReleaseMode` as a more discoverable public constant (in "package:flutter/framework.dart").  It proved too difficult to implement the equivalents (as const values, at least) for `kDebugMode` and `kProfileMode` in all contexts, so I didn't do that. They could easily be implemented as getters or functions, but they wouldn't be usable in const contexts.

The good news is that usually only `kReleaseMode` needs to be const for most use cases (e.g. to allow dead code removal, which is mainly only needed in release mode).

**Comment by mono0926** [comment]
I put this code and can be accessed globally.

```dart
BuildMode buildMode = (() {
  if (const bool.fromEnvironment('dart.vm.product')) {
    return BuildMode.release;
  }
  var result = BuildMode.profile;
  assert(() {
    result = BuildMode.debug;
    return true;
  }());
  return result;
}());
```

**Comment by jonahwilliams** [comment]
@mono0926 That will tell you the buildMode but I don't believe it will lead to any dead code being removed from the app

**Comment by patelkrunal78** [comment]
This Might Help You

assert(() {
if (navigator == null && !nullOk) {
   throw new FlutterError(
   'Navigator operation requested with a context that does not include a Navigator.n'
    'The context used to push or pop routes from the Navigator must be that of a '
      'widget that is a descendant of a Navigator widget.'
    );
  }
 return true;
}());

Find at https://icetutor.com/question/check-if-running-app-is-in-debug-mode/

**Comment by mono0926** [comment]
> Yes, I just added kReleaseMode as a more discoverable public constant (in "package:flutter/framework.dart"). It proved too difficult to implement the equivalents (as const values, at least) for kDebugMode and kProfileMode in all contexts, so I didn't do that. They could easily be implemented as getters or functions, but they wouldn't be usable in const contexts.
> https://github.com/flutter/flutter/issues/11392#issuecomment-461604949

I noticed that `kDebugMode` and `kProfileMode` were added at https://github.com/flutter/flutter/pull/31696 .

So, this issue could be closed.

**Comment by maheshmnj** [comment]
> I put this code and it can be accessed globally.
> 
> ```dart
> BuildMode buildMode = (() {
>   if (kReleaseMode) {
>     return BuildMode.release;
>   }
>   var result = BuildMode.profile;
>   assert(() {
>     result = BuildMode.debug;
>     return true;
>   }());
>   return result;
> }());
> ```

can someone please explain how to use it?

**Comment by maheshmnj** [comment]
> > I put this code and it can be accessed globally.
> > ```dart
> > BuildMode buildMode = (() {
> >   if (kReleaseMode) {
> >     return BuildMode.release;
> >   }
> >   var result = BuildMode.profile;
> >   assert(() {
> >     result = BuildMode.debug;
> >     return true;
> >   }());
> >   return result;
> > }());
> > ```
> 
> can someone please explain how do I use it in my app?
