### ISSUE TITLE
[web] Make flutter tool play nicely with `--local-engine=wasm_release`

### ISSUE THREAD

**Issue by mdebbar** [flutter/flutter#113966]
These are the known issues with using `--local-engine=wasm_release`:

- [x] Flutter tool always tries to find a `host_` prefixed folder in `out/`.
- [x] Flutter tool assumes a dart-sdk is built into `out/wasm_release` which isn't the case.
- [x] Flutter tool always compiles shaders, which can't be done with `wasm_release` because it has no impeller.
- [x] The dart compiler tries to find `out/wasm_release/dart-sdk/libraries.json` (in addition to `out/wasm_release/flutter_web_sdk/libraries.json`) which doesn't exist.
- [ ] `flutter build web --local-engine=wasm_release` is broken.

**Comment by mdebbar** [comment]
@eyebrowsoffire after your PR, I think all the items listed in this issue are fixed, right?

**Comment by eyebrowsoffire** [comment]
I still need to fix `flutter build --web --local-engine`, which is still broken. I have a plan though, but it's going to require some changes on the engine side too.

**Comment by mdebbar** [comment]
Ok, I added it to the list.

**Comment by yjbanov** [comment]
This is done.
