### ISSUE TITLE
RTL terminology

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#11394]
@abarth 

Giving coordinates using top/bottom/left/right is... (physical? absolute?)
Giving coordinates using start/end or leading/trailing is... (logical? relative?)
The horizontal axis orientation is described by the `TextDirection` enum, with values `rtl` and `ltr`.
The vertical axis orientation is described by the `...` enum, with values `down` and `up`.

**Comment by Hixie** [comment]
I'd rather avoid the terms "physical", "logical", "absolute", "relative", "BASE", "flow", "block progression direction", and "inline progression direction", which are terms that either make no sense to anyone except CSS experts, or that have confusion overloaded meanings either in CSS or in Flutter already.

**Comment by abarth** [comment]
> Giving coordinates using top/bottom/left/right is

Visual

> Giving coordinates using start/end or leading/trailing is

Semantic

> The vertical axis orientation is described by the ... enum, with values down and up.

We might also need a term that is horizontal/vertical agnostic but represents rtl/up and ltr/down.  If we're clever, we'll be able to use that term for the vertical name too.

**Comment by abarth** [comment]
> The vertical axis orientation is described by the ... enum, with values down and up.

ReadingDirection with increasing / decreasing ?  As in, the user is reading in the direction of increasing numerical values on the foo axis.

**Comment by abarth** [comment]
Also possible: LayoutDirection with increasing / decreasing, which might be a better fit for vertical since the user might not actually be reading from bottom to top.

**Comment by abarth** [comment]
> Giving coordinates using start/end or leading/trailing is... (logical? relative?)

These could also be "reading" if we don't use the term reading for (4).

**Comment by b-strauss** [comment]
my 2 cents:

1: Visual
2: Logical

😄

**Comment by Hixie** [comment]
Logical doesn't work because it conflicts with "logical pixels" (vs device pixels).

**Comment by b-strauss** [comment]
But that's something completely different. Is it a good idea to avoid generic terms that make sense, just because they already have been used in a different context, for terms that may make less sense?

**Comment by abarth** [comment]
@b-strauss The trouble is they're both operative for these properties.  The units for "left" and "start" are "logical pixels".

**Comment by b-strauss** [comment]
Yeah, I hadn't thought of that. Maybe:

> Giving coordinates using top/bottom/left/right is... (physical? absolute?)

Explicit

> Giving coordinates using start/end or leading/trailing is...

Implicit

**Comment by Hixie** [comment]
The current proposals for the BASE vs TBLR terminology (including some I considered but hadn't mentioned here before):

* BASE vs TBLR: nobody knows what that means.
* Logical vs Physical: confusing because we use those terms for whether the device pixel ratio is involved.
* Relative vs Absolute: confusing because "relative" could mean an offset from another widget and "absolute" could mean an offset from the screen coordinate space.
* Semantic vs Visual: confusing because "visual" is already overloaded to mean the non-logical order in bidi text and the kind of legacy encoding that is stored "backwards" in memory, and "semantic" is already used to refer to our accessibility/indexing layer.
* Reading vs Visual: confusing because it's not intuitive that these aren't the same thing.
* Implicit vs Explicit: confusing because "implicit" values are normally those that are defaulted to something, and "explicit" values are usually those that aren't, but in this case you could have implicit values that aren't being defaulted and explicit values that are being omitted.
* ReadingOrder vs PaintingOrder: confusing because painting order is usually the z-axis order.

The main place where I'd expect to see this term in the API, aside from the documentation, is in the class names or constructor names for variants of EdgeInsets, FractionalOffset, Positioned, etc (depending on what approach we take). This means that it's more important to have a good term for the logical mode than the physical mode, because the physical mode will likely be the default in the API (since doing anything else would be a breaking change):

```dart
new FractionalOffset(left: 0.0)
new FractionalOffset.logical(start: 0.0)
new LogicalFractionalOffset(start: 0.0)
```

So maybe we could use an entirely different category of terms:

```dart
new FractionalOffset(left: 0.0)
new FractionalOffset.fromDirection(start: 0.0)
new DirectionalFractionalOffset(start: 0.0)
new FractionalOffset.bidi(start: 0.0)
new BidiAwareFractionalOffset(start: 0.0)
```

**Comment by abarth** [comment]
```dart
new FractionalOffset.from(start: 0.0)
```

?

**Comment by b-strauss** [comment]
```dart
new DirectionalFractionalOffset(start: 0.0);
```

I like that.

```dart
new FractionalOffset.directional(start: 0.0);
```

**Comment by Hixie** [comment]
Turns out I can't use the constructor approach because I'd need it to return an instance of a class that isn't FractionalOffset (it has to be a peer for this whole thing to work).

Current best idea (naming courtesy of @HansMuller):

```dart
   class FractionalOffsetGeometry {
     FractionalOffset resolve(TextDirection direction);
   }
   class FractionalOffset extends FractionalOffsetGeometry {
     // ... everything it has today ...
     FractionalOffset resolve(TextDirection direction) => this;
   }
   class FractionalOffsetDirectional extends FractionalOffsetGeometry {
     FractionalOffsetDirectional(this.start, this.y);
     final double start;
     final double y;
     FractionalOffset resolve(TextDirection direction) {
       switch (direction) {
         case TextDirection.ltr: return new FractionalOffset(start, y);
         case TextDirection.rtl: return new FractionalOffset(1.0 - start, y);
       }
     }
   }
```

**Comment by Hixie** [comment]
The name `FractionalOffsetGeometry` appears in APIs that accept either kind, so it has to be something nice and approachable. I don't think `FractionalOffsetBase` or `AbstractFractionalOffset` work well for this (those would fit my normal patterns for base classes).

The name `FractionalOffsetDirectional` appears in call sites that are bidi-aware. It has to sort alphabetically near `FractionalOffset` so that people find them together.

**Comment by b-strauss** [comment]
@Hixie can't you use a named factory constructor that returns a subtype of FractionalOffset that is FractionalOffsetDirectional?

**Comment by Hixie** [comment]
It needs to be a subtype of the base class of FractionalOffset to make it work the way I was thinking of making it work. See https://github.com/flutter/flutter/issues/11357 for the specific issue of FractionalOffset in an RTL world. (If you have other ideas for how to make that work I'm open to hearing them.)

**Comment by Hixie** [comment]
Latest work on this is at https://github.com/flutter/flutter/pull/11570.

**Comment by Hixie** [comment]
Directionality landed.
