### ISSUE TITLE
Image RTL

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#11391]
Image should take a way to autoflip in RTL.

**Comment by abarth** [comment]
Also, the alignment should be directional.

**Comment by abarth** [comment]
I'm not sure if there's a better idiom for flipping the rasterization than giving the canvas a matrix.

Also, some of the material design icons are supposed to flip automatically.

**Comment by abarth** [comment]
Looks like the icon flipping is #11368

**Comment by Hixie** [comment]
I imagine this will just be a boolean on Image that, if the ambient directionality is rtl, flips the image using a scaleX(-1) transform. (This boolean would be ignored if null, and if true or false would require a direcitonality.) Maybe the API is that you provide an imageDirection and it has to match the textDirection? I guess it'd be less confusing to just have the boolean.

**Comment by Hixie** [comment]
(plus the alignment issue, as you noted)

**Comment by abarth** [comment]
Also, RawImage, Image, and FadeInImage.

**Comment by Hixie** [comment]
I have a patch that adds `bool matchTextDirection` to DecorationImage, Image, and FadeInImage, and adds a `bool flipHorizontally` to `paintImage`, RawImage, and RenderImage. It also adds a `textDirection` to ImageConfiguration.

Still needs tests and the alignment to be made directional on DecorationImage, Image, and FadeInImage.

**Comment by Hixie** [comment]
https://github.com/flutter/flutter/compare/master...Hixie:image-rtl is my WIP.

**Comment by abarth** [comment]
Looks promising.

**Comment by Hixie** [comment]
Ok the patch is updated and does the alignment too now.

Just needs tests. Any ideas what I should test? I can't test the actual image rendering very well without reference tests...

**Comment by abarth** [comment]
I would test the matrix that you end up pushing onto the canvas and the balancing between save/restore using the display list testing machinery.  If you want to go nuts, you can teach that code how to keep track of the transform stack.
