### ISSUE TITLE
calling keyboard.service.hide() twice in a row causes a crash

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#114]
<a href="https://github.com/Hixie"><img src="https://avatars.githubusercontent.com/u/551196?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Hixie](https://github.com/Hixie)**
_Thursday Jul 23, 2015 at 00:29 GMT_
_Originally opened as https://github.com/flutter/engine/issues/226_

----

The Java side of this isn't null-checking fields. It assumes its API contract is going to be followed.

services/keyboard/src/org/chromium/mojo/keyboard/KeyboardServiceImpl.java

**Comment by abarth** [comment]
Appears to be fixed.
