### ISSUE TITLE
[IOS][platform_views] Scrolling a page containing platform views has noticeable jitter on Promotion devices

### ISSUE THREAD

**Issue by 0xZOne** [flutter/flutter#114010]
There is noticeable jitter when scrolling pages containing platform views on the iPhone 13 pro. 
However, it's very smooth on non-ProMotion devices, at least barely juddering, like the iPhone 8.

## Steps to Reproduce

1. `git clone -b task/issue_114010 git@github.com:0xZOne/flutter_boost.git` 
2. `cd flutter_boost/example`
3. `flutter run`
4. Follow the video below

https://user-images.githubusercontent.com/26625149/197768511-ce2c651c-ebb2-44cd-9a5c-222f50d20388.MP4

<details>
  <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel main, 3.5.0-10.0.pre.17, on macOS 12.6 21G115 darwin-x64, locale zh-Hans-CN)
    • Flutter version 3.5.0-10.0.pre.17 on channel main at /Users/zero/fvm/versions/main
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 59d26c481a (5 days ago), 2022-10-20 20:05:08 -0400
    • Engine revision f24ea1a04d
    • Dart version 2.19.0 (build 2.19.0-324.0.dev)
    • DevTools version 2.18.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc1)
    • Android SDK at /Users/zero/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc1
    • ANDROID_HOME = /Users/zero/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code (version 1.72.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (2 available)
    • 艾尔玛的iPhone (2) (mobile) • 00008110-001A30960238401E • ios        • iOS 15.5 19F77
    • macOS (desktop)         • macos                     • darwin-x64 • macOS 12.6 21G115 darwin-x64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by huycozy** [comment]
Hi @0xZOne Can you check this issue #107486 to see if it is similar to your case?

If this issue is separated from #107486, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this. Your sample code above contains many references code (I'm not sure if it's necessary to replicate the issue or not). 

Thank you!

**Comment by 0xZOne** [comment]
> Hi @0xZOne Can you check this issue #107486 to see if it is similar to your case?
> 
> If this issue is separated from #107486, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this. Your sample code above contains many references code (I'm not sure if it's necessary to replicate the issue or not).
> 
> Thank you!

Yes, it is very similar. The issue can also be reproduced using https://github.com/Nico3652/native_view_project.

**Comment by huycozy** [comment]
@0xZOne Given your message, I feel safe to close this issue as a duplicate. Issue #107486 is being handled and has the appropriate labels. 

If you disagree please write in the comments and I will reopen it. Thank you!
