### ISSUE TITLE
[Impeller] Summarize the list of driver workarounds in Skia.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#114027]
One of the initial hurdles in making the case for Impeller was that one of the more difficult-to-get-right elements would be to account for the list of GPU driver and vendor specific workarounds in Skia. A lot of the decisions were impacted by reading [how and what Skia works around](https://github.com/google/skia/blob/b7d48198f1fc7058cfd022daf55fc5e6264883d8/src/gpu/ganesh/gl/GrGLCaps.cpp#L93).

A lot of the workarounds don't make sense with Impeller and some of them [seem to be overly broad](https://github.com/flutter/flutter/issues/113596).

This issue tracks documenting the themes of the issues being worked around and cross-referencing the bugs associated with these workarounds.

**Comment by dnfield** [comment]
This will vary for GL, Metal, and Vulkan right?

**Comment by chinmaygarde** [comment]
Right, the GrCaps subclasses. Though, only the GL ones seem fully fleshed out.

**Comment by chinmaygarde** [comment]
We can always refer to the caps for the latest view. I don't think there is any action item here.
