### ISSUE TITLE
Deprecated API problems

### ISSUE THREAD

**Issue by cliffclimber-721** [flutter/flutter#114057]
Hi, I'm now developing a simple application with Flutter, but I can see some errors, and this error shows "XMLHttpRequestError".
And on my terminal, I can see

"**You have created a new client application that uses libraries for user authentication or authorization that will soon be deprecated. New clients must use the new libraries instead; existing clients must also migrate before these libraries are deprecated. See the
[Migration Guide](https://developers.google.com/identity/gsi/web/guides/gis-migration) for more information.**"
## Steps to Reproduce

1. I'm now using server with Nodejs latest version. If "nom run dev" executes, next, "flutter run -d chrome --web-port 3000" executes.
2. I also checked with Thunder Client whether it works well or not; but it posts well(res.status(200))

<img width="568" alt="Screen Shot 2022-10-26 at 4 21 11 PM" src="https://user-images.githubusercontent.com/80508931/197960571-e5a1663e-8dd5-4ec0-b3c7-6ab7bc1c8bb6.png">
This is my log of "flutter doctor -v", no matters.

**Comment by exaby73** [comment]
Hello @cliffclimber-721. Could you provide a [complete and minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) so that I can investigate and verify the issue?

**Comment by cliffclimber-721** [comment]
<img width="1107" alt="Screen Shot 2022-10-27 at 12 27 21 AM" src="https://user-images.githubusercontent.com/80508931/198068780-144a8932-df8a-4940-9732-f9aa032bcf22.png">
Hi, I just saw your reply, and my log was this.

**Comment by exaby73** [comment]
Sorry but I need a code sample to run. Preferably a single `main.dart` file I can run directly to reproduce this issue

**Comment by amorenew** [comment]
are you using google auth? then maybe this related
https://github.com/flutter/flutter/issues/88084

**Comment by ditman** [comment]
@cliffclimber-721 can you check in your app, what's the version of the following package: `google_sign_in_web`? It needs to be >= than `0.10.1`. [Changelog](https://pub.dev/packages/google_sign_in_web/changelog#0101).

(If it isn't, try to upgrade the package by running: `flutter pub upgrade`)

Check the issue that @amorenew mentioned above for more info!
