### ISSUE TITLE
ability to change arrow to radio in ExpansionPanelRadio

### ISSUE THREAD

**Issue by soufiane0123** [flutter/flutter#114064]
## Proposal

![image](https://user-images.githubusercontent.com/111284741/197998264-c6c52aa5-019e-47a1-bb46-42ffc6465624.png)

change to 

![image](https://user-images.githubusercontent.com/111284741/197997904-d1f64a87-233b-400d-90e8-86293a4c737d.png)

**Comment by exaby73** [comment]
Hello @soufiane0123. This is how it is intended to be. If you need custom icons, you can implement them yourself. This change does not seem like a valid one. Closing this issue for the same reason.
