### ISSUE TITLE
webview_flutter cant open gallery to choose file in android

### ISSUE THREAD

**Issue by mahdiqdi** [flutter/flutter#114007]
i know some issues are open about webview_flutter and its problem about choosing file.plz solve this hilarious problem.i need this one to choose file in webview

**Comment by danagbemava-nc** [comment]
This is a known issue that is being tracked in https://github.com/flutter/flutter/issues/27924. 

Kindly follow up in the issue for updates.

Closing from here as duplicate. 

Thank you
