### ISSUE TITLE
quiting the flutter run process no longer stops the app on the device

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter#11409]
To repro:

- flutter run
- issue a restart
- type 'q' (for quit)

The app doesn't quit. The restart above is necessary for this to repro, so I'm guessing that we're losing track of the isolate to send messages to after the full restart.

**Comment by Hixie** [comment]
When fixing this, please add a test. The following test could be trivially tuned to additionally test this case:
https://github.com/flutter/flutter/blob/master/dev/devicelab/bin/tasks/commands_test.dart

**Comment by devoncarew** [comment]
Gotcha. I've made progress on this issue - I've restored the app quit on exit behavior, largely by removing some caching (though, I'm not sure why the caching was no longer consistent). I'll look at updating that test.
