### ISSUE TITLE
Clip fix regressed Impeller raster times on Android

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#114021]
The fix here https://github.com/flutter/flutter/pull/113770 regressed the raster times of the `list_text_layout_impeller_perf__e2e_summary` benchmark:

https://flutter-flutter-perf.skia.org/e/?begin=1666280999&end=1666307527&keys=X4dfec7919bc8bf5ff16c3a0b23e31e3d&num_commits=50&request_type=1&xbaroffset=31668

@jonahwilliams @dnfield @iskakaushik

**Comment by zanderso** [comment]
`new_gallery_impeller__transition_perf` also regressed.

**Comment by jonahwilliams** [comment]
Is clipping on Android with impeller enabled particularly slow? @chinmaygarde 

I notice there don't seem to be any iOS or non-impeller regressions so I'm inclined to keep this for now...

**Comment by zanderso** [comment]
Yeah, if https://github.com/flutter/flutter/pull/113770 fixed a real bug, we should keep it. I opened this issue so that we can track that the benchmark recovers as we make progress on the backend for Android.

**Comment by chinmaygarde** [comment]
> Is clipping on Android with impeller enabled particularly slow?

No, clips should be "free" with the stencil buffers already being present. Perhaps we aren't clearing the render target correctly after the clip causing a load? Should become apparent after profiling. We can keep this open till we get to Android performance. Can we also add a note about the device here this happens on please?

**Comment by zanderso** [comment]
It looks like the benchmark recovered, at some point, so I'll close this.
