### ISSUE TITLE
pub publish not working

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#11407]
## Steps to Reproduce

1. Create a package
1. Run `flutter pub pub publish`

=> flutter prints out status and then just hangs just prior to publishing

1. Run `pub publish`

=> Upload succeeds

## Logs

```
   | Nothing output on stderr.
IO  : Spawning "tar --format=ustar --create --gzip --directory /Users/mit/dev/mit-plugins/packages/image_picker/. @/dev/stdin" in /Users/mit/dev/mit-plugins/packages/image_picker/.
FINE: Showing confirm message:
    | Looks great! Are you ready to upload your package

```

**Comment by mravn-google** [comment]
`pub publish` is an interactive shell script, but the Flutter tooling process wrapper handles neither unfinished lines written to standard output (e.g. "Are you ready to upload your package (y/n)? ") nor wiring of standard input.

Fortunately, `pub publish` has a `--force` directive that turns off interactivity.
