### ISSUE TITLE
Update `ListTile` to support Material 3

### ISSUE THREAD

**Issue by TahaTesser** [flutter/flutter#114006]
![image](https://user-images.githubusercontent.com/48603081/197764713-44b4bb9a-236e-47f7-886f-ec49ad1ef44b.png)

Specs: https://m3.material.io/components/lists/overview 

For testing, try `ListItem` from Compose

**Comment by TahaTesser** [comment]
cc: @guidezpl @darrenaustin 
Could please add this to https://github.com/flutter/flutter/issues/91605

**Comment by TahaTesser** [comment]
@darrenaustin 
I can see the following [changes](https://m3.material.io/components/lists/overview#0d2dff28-83e1-4c09-94b6-d750db2b9911), including height and element alignments changes, naming scheme changes such as  `Title` is now called `Headline`.

I propose a new widget `ListItem` that matches M3 specs and has M3 naming scheme and this will also get rid of legacy issues such as https://github.com/flutter/flutter/issues/1858, https://github.com/flutter/flutter/issues/1857.

**Comment by TahaTesser** [comment]
> `ListItem` is a pretty heavy-duty way to introduce size and style changes. Can't all of changes be safely introduced via useMaterial3 defaults?

Certainly, What about the naming scheme? We can keep the current `title` and `subtitle` names?

**Comment by HansMuller** [comment]
Although we have migrated names in the past (TextTheme), I think in this case it would be best to leave `title` and `subtitle` as they are, since they're pretty self-explanatory.

**Comment by TahaTesser** [comment]
> Although we have migrated names in the past (TextTheme), I think in this case it would be best to leave `title` and `subtitle` as they are, since they're pretty self-explanatory.

Perfect! Thanks for the feedback. I have worked on this widget before so I am excited to migrate it.

**Comment by TahaTesser** [comment]
Getting PR ready by Monday (21 Nov)

**Comment by TahaTesser** [comment]
Finalizing a PR for this and will file it tomorrow!

**Comment by TahaTesser** [comment]
Part 1 landed. 
I'm working on the final PR for this issue and separate documentation PR, this will come after the holidays, will get the PRs ready for this on the first week of Jan.

**Comment by hawkkiller** [comment]
Great to see it

**Comment by TahaTesser** [comment]
In https://github.com/flutter/flutter/pull/116194, Matching ListTile background color with M3 specs caused issues and it has been reverted and was also reported here https://github.com/flutter/flutter/issues/117700.

We should avoid adding fixed default non-transparent background color, just like M3 ListTile.

**Comment by TahaTesser** [comment]
Few more tests, will file the  PR tomorrow.
