### ISSUE TITLE
Impeller raster time regression in color_filter_and_fade_perf

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#114022]
https://flutter-flutter-perf.skia.org/e/?begin=1666383819&end=1666546895&keys=Xfd0501cf6a99fb6c4060f853af542f65&num_commits=50&request_type=1&xbaroffset=31691

Looks like this regressed on https://github.com/flutter/engine/pull/36914

@jonahwilliams

**Comment by jonahwilliams** [comment]
I can reproduce the performance locally, confirming that a revert improves performance

**Comment by jonahwilliams** [comment]
actually when I run this with a local engine, I get numbers that are comparable to the old benchmark values. Only with prebuilts do I get the worse performance. I am on a local engine that has the rect change too...

**Comment by jonahwilliams** [comment]
Reverting it still improves performance further. We should investigate what is causing this performance difference between the prebuilts and local engine too though. prebuilts should always be faster due to LTO.

**Comment by jonahwilliams** [comment]
oops, fix is https://github.com/flutter/engine/pull/37005
