### ISSUE TITLE
[Impeller] Investigate runtime flag for Impeller toggling

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#114197]
customer: money is interested in experimenting with Impeller on iOS (pending development verification of visual correctness). It would probably be easier for them to run an experiment if they can do a runtime flag that does not require distributing different binaries.

I think that this is already possible if you update your embedding, so this might just be that we should update https://github.com/flutter/engine/blob/main/impeller/README.md#try-impeller-in-flutter with some instructions about how to do this for customers who want to do experiments based approaches to rolling this out.

Looking at https://github.com/flutter/engine/blob/main/shell/platform/darwin/ios/framework/Source/FlutterDartProject.mm it seems like it might be difficult for an application to arbitrarily modify settings short of just creating all the settings itself.

@chinmaygarde @zanderso fyi

**Comment by chinmaygarde** [comment]
Hmm, today there are only two ways of enabling Impeller on iOS. Either via the run configuration that [adds a "command line" flag](https://github.com/flutter/engine/blob/e7696f4f03cc46f026cb1bc56bdd8c9536b06de9/shell/platform/darwin/ios/framework/Source/FlutterDartProject.mm#L55), or, updating the [`Info.plist` in the Flutter application bundle](https://github.com/flutter/engine/blob/e7696f4f03cc46f026cb1bc56bdd8c9536b06de9/shell/platform/darwin/ios/framework/Source/FlutterDartProject.mm#L163).

In the past, I don't think we've exposed any other ways for embedders to toggle experiemental flags on a per shell launch basis. If we wanted to do this however, we'd need to allow the additional options (perhaps an `NSDictionary`) to be passed to the [`FlutterDartProject` ctor](https://github.com/flutter/engine/blob/e7696f4f03cc46f026cb1bc56bdd8c9536b06de9/shell/platform/darwin/ios/framework/Headers/FlutterDartProject.h#L23) or perhaps make the project be mutable and allow setting options on it. The configured project could then be used to launch a new Flutter Engine instance with the choice of rendering backend.

I am not sure if you meant being able to swap the rendering backend post engine launch. But that would be significantly harder and not something we want to add support for.

**Comment by dnfield** [comment]
No, it's fine if it's something required at startup and can't be changed.

It's _possible_ to do this on iOS and Android today, but not very easy and would require a bunch of code copying from FlutterDartProject.mm to set up all the defaults on settings. I think it'd be enough to just let users modify the default settings for this. @jmagman or @cyanglaz WDYT?

**Comment by jonahwilliams** [comment]
Now that we're compiling shaders per target platform there are build implications for allowing runtime switching. If this is an option we add it should never be exposed as a default, otherwise we'd need to change the shader bundling/resolution strategy to support bundling both SkSL and Impeller/TargetPlatform shaders

**Comment by dnfield** [comment]
@jonahwilliams don't we already have that problem?  Does the tool read your info plist?

**Comment by jonahwilliams** [comment]
Yes it does.

**Comment by jonahwilliams** [comment]
And no, this would make it worse. The challenge today is bundlig the right version of each shader. If we allow runtime toggling we will have to bundle both versions.

**Comment by zanderso** [comment]
@jonahwilliams would it help if we modified `impellerc` to always include SkSL in the `.iplr` file. Then the engine could select the right field of the flatbuffer (SkSL or native shader) for the backend that is chosen at engine startup. Would this be too much size overhead? How would this approach fit in with the Web support?

**Comment by jonahwilliams** [comment]
I don't think the size overhead would be significant. As an optimization, we could remove the SkSL variant if we're certain we're building impeller only, or remove the impeller version if we're certain we're not.

This would solve the problem of the --enable-impeller runtime flag, which would leave an app installed that could start up with the wrong shaders (switching from impeller to skia).

Sounds like a good idea to me?

**Comment by chinmaygarde** [comment]
Agreed on the size overhead. It'd be minimal. In the interim, as folks are doing runtime switching, this sounds like a good idea to me too.

**Comment by jonahwilliams** [comment]
So we've discussed this a bit more on and off:

1. toggling at runtime (while the app is running) is infeasible because engine objects cannot always safely switch between backends, and the initialization code is non-trivial

2. toggling at startup is already possible via cmd line arguments to the engine, manifest settings, and intent flags.
