### ISSUE TITLE
Navigator.pop(context, true) fails 

### ISSUE THREAD

**Issue by kroikie** [flutter/flutter#11411]
## Steps to Reproduce

- Push a named route
- Pop route returning a value with `Navigator.pop(context, value)`. Eg:

      Navigator.pop(context, 12);

## Details

If the value used is an int then the error would be:

    type 'int' is not a subtype of type 'Null' of 'result' where
    int is from dart:core
    Null is from dart:core

if the value used is a bool then the error would be:

    type 'bool' is not a subtype of type 'Null' of 'result' where
    bool is from dart:core
    Null is from dart:core

Popping the route without the value works as expected.

## Logs

When the exception was thrown, this was the stack:
#0      TransitionRoute&&LocalHistoryRoute.didPop (package:flutter/src/widgets/routes.dart:328:17)
#1      NavigatorState.pop (package:flutter/src/widgets/navigator.dart:1094:15)
#2      Navigator.pop (package:flutter/src/widgets/navigator.dart:590:34)
#3      DetailsScreen.build.<anonymous closure> (/Users/arthurthompson/Library/Developer/CoreSimulator/Devices/7262DC0C-44DE-4BF1-B29F-E3A9B2AE8C39/data/Containers/Data/Application/2FDE417A-5F43-4512-BDA1-1F7F7233428D/tmp/firstflutterbmBye7/firstflutter/lib/details.dart:18:23)
#4      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:296:14)
#5      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:71:24)
#6      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:149:9)
#7      TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:92:7)
#8      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:272:9)
#9      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:73:12)
#10     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:11)
#11     BindingBase&SchedulerBinding&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:127:19)
#12     BindingBase&SchedulerBinding&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:105:22)
#13     BindingBase&SchedulerBinding&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:86:7)
#14     BindingBase&SchedulerBinding&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:45:7)
#15     BindingBase&SchedulerBinding&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:38:5)
#16     _dispatchPointerDataPacket (file:///b/build/slave/Mac_Engine/build/src/flutter/lib/ui/hooks.dart:55)
Handler: onTap
Recognizer:
  TapGestureRecognizer#3c971(GestureRecognizerState.possible)

## Flutter Doctor

[✓] Flutter (on Mac OS X 10.12.6 16G29, locale en-US, channel alpha)
    • Flutter at /Users/arthurthompson/opt/flutter
    • Framework revision d36e2f6191 (5 weeks ago), 2017-06-21 15:09:10 -0700
    • Engine revision b0dee695ec
    • Tools Dart version 1.24.0-dev.6.7

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at /Users/arthurthompson/opt/android/sdk
    • Platform android-26, build-tools 25.0.3
    • ANDROID_HOME = /Users/arthurthompson/opt/android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.3.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3.3, Build version 8E3004b
    • ios-deploy 1.9.1
    • CocoaPods version 1.2.1

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Gradle version 3.2
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Ultimate Edition (version 2017.1.3)
    • Flutter plugin version 15.0
    • Dart plugin version 171.4424.63

[✓] Connected devices
    • iPhone 7 Plus • 7262DC0C-44DE-4BF1-B29F-E3A9B2AE8C39 • ios • iOS 10.3 (simulator)

**Comment by Hixie** [comment]
I think if you update to master this should be fixed. Hopefully we'll roll alpha soon and that should get you a fix on alpha too.

**Comment by kroikie** [comment]
Indeed it is fixed in master. Thanks!

**Comment by santiagohdzb** [comment]
I'm having this issue on 1.9.1+hotfix.6

```
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.14.6 18G103, locale es-MX)
    • Flutter version 1.9.1+hotfix.6 at /Users/j.santiagohernandez/Development/Flutter
    • Framework revision 68587a0916 (2 months ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/j.santiagohernandez/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.7.5

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 40.2.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.40.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.6.0
```

Error message:
`type 'int' is not a subtype of type 'Null' of 'result'`

Here's the stack:
```
I/flutter (28254): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (28254): The following assertion was thrown building
I/flutter (28254): Navigator-[LabeledGlobalKey<NavigatorState>#18afb](dirty, state: NavigatorState#d42e9(tickers:
I/flutter (28254): tracking 3 tickers)):
I/flutter (28254): 'package:flutter/src/widgets/navigator.dart': Failed assertion: line 2247 pos 12: '!_debugLocked':
I/flutter (28254): is not true.
I/flutter (28254): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (28254): more information in this error message to help you determine and fix the underlying cause.
I/flutter (28254): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (28254):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (28254): User-created ancestor of the error-causing widget was:
I/flutter (28254):   MaterialApp
I/flutter (28254):   
lib/main.dart:24
I/flutter (28254): When the exception was thrown, this was the stack:
I/flutter (28254): #2      NavigatorState.build 
package:flutter/…/widgets/navigator.dart:2247
I/flutter (28254): #3      StatefulElement.build 
package:flutter/…/widgets/framework.dart:4047
I/flutter (28254): #4      ComponentElement.performRebuild 
package:flutter/…/widgets/framework.dart:3941
I/flutter (28254): #5      Element.rebuild 
package:flutter/…/widgets/framework.dart:3738
I/flutter (28254): #6      BuildOwner.buildScope 
package:flutter/…/widgets/framework.dart:2348
I/flutter (28254): #7      WidgetsBinding.drawFrame 
package:flutter/…/widgets/binding.dart:760
I/flutter (28254): #8      RendererBinding._handlePersistentFrameCallback 
package:flutter/…/rendering/binding.dart:280
I/flutter (28254): #9      SchedulerBinding._invokeFrameCallback 
package:flutter/…/scheduler/binding.dart:1033
I/flutter (28254): #10     SchedulerBinding.handleDrawFrame 
package:flutter/…/scheduler/binding.dart:975
I/flutter (28254): #11     SchedulerBinding._handleDrawFrame 
package:flutter/…/scheduler/binding.dart:891
I/flutter (28254): #15     _invoke  (dart:ui/hooks.dart:249:10)
I/flutter (28254): #16     _drawFrame  (dart:ui/hooks.dart:207:3)
I/flutter (28254): (elided 5 frames from class _AssertionError and package dart:async)
I/flutter (28254): ════════════════════════════════════════════════════════════════════════════════════════════════════

```
