### ISSUE TITLE
Gradient looks Darker on Android vs. iOS

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#11410]
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(new MaterialApp(
    home: new Scaffold(
      appBar: new AppBar(
        title: new Text("Android looks Darker"),
      ),
      body: new SizedBox.expand(
          child: new DecoratedBox(
        decoration: new BoxDecoration(
          gradient: new LinearGradient(
            begin: FractionalOffset.bottomCenter,
            end: FractionalOffset.topCenter,
            stops: <double>[0.2, 0.6, 1.0],
            colors: <Color>[
              new Color(0xCC000000),
              new Color(0x55000000),
              new Color(0x00FFFFFF)
            ],
          ),
        ),
      )),
      // For color comparison:
      floatingActionButton: new FloatingActionButton(
        onPressed: null,
        child: new Icon(Icons.add),
      ),
    ),
  ));
}
```

This report came in from Posse.  @chinmaygarde believes this is due to color correction never triggering on Android devices.  @brianosman

**Comment by eseidelGoogle** [comment]
@chinmaygarde offered this diagnosis offline:

"""
After more investigation, it turns out that sRGB support is enabled on iOS but not on Android. sRGB support on Android is enabled via a check in the extensions here https://github.com/flutter/engine/blob/8ee1910ca9b20874022a7e931fdb9e7bb1baa62a/shell/platform/android/android_context_gl.cc#L220. I was able to find no Android device that reports that extension being present. Note however that adb shell dumpsys SurfaceFlinger does report that extension as being present. It is just not conveyed over to the application. @jason-simmons think it the EGL library hiding certain extensions from user applications.

From what I can tell, we are performing color correct rendering on iOS and cant perform the same on Android because the device says the extension is not present. Not sure how to proceed on this.
"""

**Comment by eseidelGoogle** [comment]
@brianosman if you have a suggested workaround for how to achieve more similar looking coloring on Android and iOS that's also welcome. :)

**Comment by eseidelGoogle** [comment]
Here is the iPhone Simulator (iPhone SE):
![flutter_03](https://user-images.githubusercontent.com/11857803/28632233-b54f7abe-71e4-11e7-9f09-8cf3302ad5d8.png)

vs. a physical Moto G4:
![flutter_04](https://user-images.githubusercontent.com/11857803/28632235-b738b3b8-71e4-11e7-9555-f46b2668f06f.png)

**Comment by Hixie** [comment]
@j9brown any ideas?

**Comment by eseidelGoogle** [comment]
This turns out this also affects images in Posse's app.  Some images look extremely dark on Android vs. fine on iOS due to us not enabling color-correct Skia on Android.

**Comment by eseidelGoogle** [comment]
With flutter/flutter@ead51eae68 on the same Moto G4 it's now:
![flutter_01](https://user-images.githubusercontent.com/11857803/28837808-f75df7ce-76a2-11e7-9881-7b667a8c1433.png)

**Comment by chinmaygarde** [comment]
That patches addressing this issue have landed.

**Comment by MichaelM97** [comment]
For me, an issue with colours looking different still appears to be apparant.
```
import 'package:flutter/material.dart';

void main() {
  runApp(
    MaterialApp(
      home: Scaffold(
        body: Center(
          child: FlatButton(
            color: const Color(0xFFFE9700),
            shape: StadiumBorder(),
            child: Text('Click me!'),
            onPressed: () {},
          ),
        ),
      ),
    ),
  );
}
```
iOS looks as expected:
<img width="295" alt="iOS" src="https://user-images.githubusercontent.com/22373058/63551558-63cb9f80-c52d-11e9-8b27-3de8c1f111d9.png">

Android makes the colour appear darker/more vibrant:
<img width="206" alt="Android" src="https://user-images.githubusercontent.com/22373058/63551557-63cb9f80-c52d-11e9-9b6d-cf10d98e3734.png">

**Comment by eseidelGoogle** [comment]
This was closed over 2 years ago. :)  Would you be willing to open a new bug so we can look at your issue separately @MichaelM97?  A closed bug is unlikely to get the necessary attention.  Thanks.

**Comment by MichaelM97** [comment]
@eseidelGoogle Done #39113 :)
