### ISSUE TITLE
Flutter web Chinese shows that xx XXX XXX is just beginning to display   

### ISSUE THREAD

**Issue by gionlime** [flutter/flutter#114145]
Flutter web Chinese shows that xx XXX XXX is just beginning to display

 
![屏幕截图(5)](https://user-images.githubusercontent.com/91245043/198256036-985ed666-c1b9-4e03-9e50-1c14a79235d7.png)

**Comment by huycozy** [comment]
Hi @gionlime, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this. Also, please provide the output of `flutter doctor -v` as well.
