### ISSUE TITLE
Run Flutter Release on Simulator

### ISSUE THREAD

**Issue by ahmdmau** [flutter/flutter#114126]
Hi team, currently I'm working on integrating flutter into the native app, I have a question. Is it possible to run the release version of the flutter module xcframework on the simulator?

**Comment by danagbemava-nc** [comment]
Hi @ahmdmau, this is currently not possible but there is an existing issue tracking the implementation of this feature in https://github.com/flutter/flutter/issues/11754. 

Kindly follow up there for updates. 

Closing from here as duplicate. 

Thank you
