### ISSUE TITLE
[video_player] Phone call interruption bug

### ISSUE THREAD

**Issue by joedonchev** [flutter/flutter#114190]
The video playback is paused if interrupted by a phone call. That's fine.

But the VideoPlayerController still reports "isPlaying" (true), but the video is not playing.

I used [audio_session](https://pub.dev/packages/audio_session) plugin to listen for interruptions and then explicitly pause() the video, so that when the user attempt to resume the video after the call, all is good.

**Comment by danagbemava-nc** [comment]
Hi @joedonchev, what version of `video_player` are you experiencing this bug with? 

Also, what platform(s) are you experiencing this issue on?

Please also provide the output of `flutter doctor -v` as well. 

Thank you

**Comment by joedonchev** [comment]
Hi, 

video_player: ^2.4.7

Physical iPhone 12 with iOS 16.0.3

```
[✓] Flutter (Channel stable, 3.3.5, on macOS 12.6 21G115 darwin-arm, locale
    en-BG)
    • Flutter version 3.3.5 on channel stable at /Users/chavdardonchev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d9111f6402 (9 days ago), 2022-10-19 12:27:13 -0700
    • Engine revision 3ad69d7be3
    • Dart version 2.18.2
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/chavdardonchev/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.72.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.6 21G115 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 106.0.5249.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

**Comment by danagbemava-nc** [comment]
Hi @joedonchev, I forgot to request this earlier, can you provide a complete minimal reproducible code sample so that we can investigate this issue?

Thank you

**Comment by joedonchev** [comment]
Hi, yes,

It doesn't really matter how do you start a video.
It just matters the "_controller.value.isPlaying" value after the video playback was interrupted by a phone call.
In my case it's still "true" after the video was automatically paused.
It should be "false".

```
late VideoPlayerController _controller;

Future<void> _startVideo() async {
  _controller = VideoPlayerController.network('somevideourl...');
  await _controller.initialize();
}

void _checkIfPlaying() {
  if (_controller.value.isInitialized){
    print('isPlaying: ${_controller.value.isPlaying}');
  }
}
```

**Comment by danagbemava-nc** [comment]
Hi @joedonchev, the code sample you have provided is not complete. Please provide a complete minimal reproducible code sample that we can run so we can investigate this issue. 

Thank you

**Comment by joedonchev** [comment]
I'm sorry, are you familiar with Flutter, or you're just a bot?
I don't have a minimal code right now, and no time to prepare it.
Again, there's Nothing special in the code, just run any video using the video_player plugin, interrupt it with phone call and see what's the "isPlaying" saying.
I just report the bug. You can investigate it and fix it any way you like!
Bye!

**Comment by danagbemava-nc** [comment]
Hi @joedonchev, we request the code sample not because we cannot write the code or are not familiar with flutter but because in some cases where complete code samples are provided, the issue is not always reproducible. 

Providing the complete code sample you're experiencing the issue with makes it so that we all start from the same point and reduces the difference only to set up and other environmental differences.

Please provide a complete minimal code sample when you can. 

Thank you
