### ISSUE TITLE
Flutter profile buildtype aar causing crash on Android with failure to init the VM

### ISSUE THREAD

**Issue by kyujin** [flutter/flutter#114162]
Our android app is setup to use flutter as add to app. Our android custom buildtype is setup to use flutter profile aar. Currently whenever we build this custom build on android, when we open a flutter screen it crashes with the logs below. This started happening with flutter sdk version 3.3. Currently I have tested with 3.3.5 and still an issue.

```
10-27 11:31:33.938 29002 29002 F DEBUG   : signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
10-27 11:31:33.938 29002 29002 F DEBUG   : Abort message: '[FATAL:flutter/shell/common/shell.cc(143)] Check failed: vm. Must be able to initialize the VM.
10-27 11:31:33.938 29002 29002 F DEBUG   : '
10-27 11:31:33.938 29002 29002 F DEBUG   :     x0  0000000000000000  x1  0000000000007044  x2  0000000000000006  x3  0000007fc9ba4100
10-27 11:31:33.938 29002 29002 F DEBUG   :     x4  6b6467722e6d6e6c  x5  6b6467722e6d6e6c  x6  6b6467722e6d6e6c  x7  7f7f7f7f7f7f7f7f
10-27 11:31:33.938 29002 29002 F DEBUG   :     x8  00000000000000f0  x9  0000007b57ba70b0  x10 0000000000000000  x11 ffffff80fffffbdf
10-27 11:31:33.938 29002 29002 F DEBUG   :     x12 0000000000000001  x13 0000000000000061  x14 0000007fc9ba2fb0  x15 0000003759efa620
10-27 11:31:33.938 29002 29002 F DEBUG   :     x16 0000007b57c44050  x17 0000007b57c21bd0  x18 0000007b68736000  x19 0000000000007044
10-27 11:31:33.938 29002 29002 F DEBUG   :     x20 0000000000007044  x21 00000000ffffffff  x22 0000000000000000  x23 0000000000000000
10-27 11:31:33.938 29002 29002 F DEBUG   :     x24 0000007fc9ba5168  x25 b4000078d8cdbaa0  x26 0000000000000000  x27 0000000000000000
10-27 11:31:33.938 29002 29002 F DEBUG   :     x28 b4000078d8ce5400  x29 0000007fc9ba4180
10-27 11:31:33.938 29002 29002 F DEBUG   :     lr  0000007b57bd472c  sp  0000007fc9ba40e0  pc  0000007b57bd475c  pst 0000000000001000
10-27 11:31:33.938 29002 29002 F DEBUG   : backtrace:
10-27 11:31:33.938 29002 29002 F DEBUG   :       #00 pc 000000000004f75c  /apex/com.android.runtime/lib64/bionic/libc.so (abort+168) (BuildId: 53a228529316d67f22e241dd17ea9b9e)
```

<img width="1184" alt="Screen Shot 2022-10-27 at 11 41 44 AM" src="https://user-images.githubusercontent.com/2309236/198336119-50a3528e-cdfd-427e-8f87-a97b9b839270.png">

**Comment by huycozy** [comment]
Hi @kyujin 

>This started happening with flutter sdk version 3.3. Currently I have tested with 3.3.5 and still an issue.

It means the issue doesn't happen on older Flutter versions, doesn't it? If so, what is that version?

Can you provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this? Also, please provide the completed log if any. Thank you!

**Comment by kyujin** [comment]
Previous flutter version when it worked.
environment:
  sdk: "2.17.6"
  flutter: "3.0.5"

Android app build gradle file,

```gradle
 beta {
            minifyEnabled false
            signingConfig signingConfigs.debug
            manifestPlaceholders = [appIcon: '@mipmap/nf_icon_beta']
            debuggable true
            matchingFallbacks = ['profile']
        }

...
repositories {
    maven { url '../../flutterapp/build/host/outputs/repo' }
 ...

`betaImplementation 'com.neuroflow.neuroflow_module:flutter_profile:1.0'`

}

```

With the current flutter version the profile aar doesnt seem to work(crash on flutter screen) with the android beta build.
  sdk: "2.18.2"
  flutter: "3.3.5"

When we update our gradle file to use the release flutter aar for our beta build , no issues.

**Comment by kyujin** [comment]
When you say completed log are you asking for log when it works successfully or more log of when it crashes?

**Comment by huycozy** [comment]
Hi @kyujin 
Can you provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this? 

>When you say completed log are you asking for log when it works successfully or more log of when it crashes?

Sorry, I mean if there is full log of crash, please provide all of them.

**Comment by huycozy** [comment]
@kyujin Please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this. Also, please retry on the latest `master` channel to see if the issue still persists. Thank you!
