### ISSUE TITLE
[Proposal] Switch widget improvements

### ISSUE THREAD

**Issue by MaxYablochkin** [flutter/flutter#114273]
#91605

## Proposal
`1. Animation of the behavior of icons ❌✔️ (but probably others too, which I'm sure is not easy)`

`2. Ability to add and change the icon for the on state of this switch`
![Screenshot_3](https://user-images.githubusercontent.com/102767277/198743175-56ef35f9-0a5c-4376-9403-2b609cae2ea0.png)
![Screenshot_2](https://user-images.githubusercontent.com/102767277/198743192-d349e481-69a2-4739-a1ed-1e4f186a7bfc.png)

Demo from Material Design: https://youtu.be/b6FTDYrJWRA
https://m3.material.io/components/switch/guidelines#2495f276-189c-4d51-a9df-88e89e8e8185
https://m3.material.io/components/switch/specs#803dc934-1893-4c31-a1a6-a15d80ed849f

**Comment by huycozy** [comment]
Hi @MaxYablochkin 

>1. Animation of the behavior of icons

Can you be more specific about this? 

>2. Ability to add and change the icon for the on state of this switch

Is this the same as the 3rd proposal?

**Comment by MaxYablochkin** [comment]
Only 1 and 2 are relevant, I will remove the rest.

**Comment by MaxYablochkin** [comment]
> Hi @MaxYablochkin
> 
> > 1. Animation of the behavior of icons
> 
> Can you be more specific about this?
> 
> > 2. Ability to add and change the icon for the on state of this switch
> 
> Is this the same as the 3rd proposal?

1. Something like AnimatedIcon, but it was seen in the video documentation https://youtu.be/b6FTDYrJWRA.

**Comment by huycozy** [comment]
@MaxYablochkin thanks for updating. Labeling the issue as a proposal.

**Comment by MaxYablochkin** [comment]
https://m3.material.io/components/switch/guidelines#2495f276-189c-4d51-a9df-88e89e8e8185
https://m3.material.io/components/switch/specs#803dc934-1893-4c31-a1a6-a15d80ed849f
