### ISSUE TITLE
Add Navigator 2.0 support for bottom sheets

### ISSUE THREAD

**Issue by webnickell** [flutter/flutter#114232]
Currently we have `showModalBottomSheet` , here we can push page imperatively. But there is no pages for dialogs in `Navigator` pages api. We need to create own classes which extends `Page<T>`, but actually I can't event use modalBottomSheet, because it uses private class `_ModalBottomSheetRoute<T>`. I need to copy it from source code instead of direct using.

**Comment by darshankawar** [comment]
@webnickell 
Please check if [this](https://github.com/flutter/flutter/issues/87352) issue is similar to your proposal.
