### ISSUE TITLE
Apple rejected Flutter application for using google_maps_flutter ?

### ISSUE THREAD

**Issue by wijesijp** [flutter/flutter#114210]
In my application I am using google_maps_flutter: ^2.1.8

I have the map integrated within a widget and I used it for 

- showing markers
- navigation 

At no point in the application it opens an external map application, Google Maps or Maps application installed on iOS.
The map is embedded within the application.

When I submit the application to Apple Store, it was rejected with following reason.

```
Guideline 4.0 - Design

Your app's location feature is not integrated with the built-in mapping functionality, which limits users to a third-party maps app.

Next Steps

To resolve this issue, please revise your app to give users the option to launch the native Apple Maps app.
```

They provide this screenshot 
https://drive.google.com/file/d/1bF9P7Pqc-Rg77MXws9oW1nbnQzFFSxDi/view?usp=sharing

This is the point where application asks users for permission.

I understand if our application opens map application installed on device we have to provide users option to launch the native Apple Maps app. But we do NOT open other map application from our app.

Is this review incorrect?
or 
we can not use google_maps_flutter within our application for iOS releases?

**Comment by stuartmorgan** [comment]
> Is this review incorrect?

Questions about App Store reviews need to be addressed to Apple, as we have no control over that process.
