### ISSUE TITLE
[go_router] [proposal] deprecate imperative api - make go_router declarative only

### ISSUE THREAD

**Issue by iapicca** [flutter/flutter#114216]
## Use case

the reasons behind this proposal are:

- reduce complexity of the package
- `go_router` imperative api overlaps `navigator 2.x` api
- imperative navigation will be still available using [navigatorKey]( https://github.com/flutter/flutter/issues/109479)

## Proposal

remove all imperative methods from [go_router](https://pub.dev/packages/go_router) and supersede the issue https://github.com/flutter/flutter/issues/99112

**Comment by iapicca** [comment]
> @iapicca That could be a good idea, but I think it will be possible only after the support for relative routes #108177 otherwise this could result in having two completely different navigation patterns, different ways of passing arguments, navigation event tracking, etc.

this sounds reasonable

> **_I personally found myself using both declarative and imperative navigation, pushing routes in situations where relative routes would probably solve my problem._**

copied from this [reply](https://github.com/flutter/flutter/issues/99112#issuecomment-1294768658), 

@Skogsfrae 
(I'd move the conversation here  as I don't want to spam arguments against 
the implementation of imperative api  on an issue that aims to implement it 😄 )

I think the underlying questions is `why do we need an imperative api?`
as you did I have sometimes used both with the use cases for the imperative api being:

- passing arguments (the use case you referenced)
- return a value on pop  https://github.com/flutter/flutter/issues/100969
- (bonus issue if we consider `pop()` being imperative) https://github.com/flutter/flutter/issues/110149

I have no argument that in some cases devs will need "hack" and rely on imperative api,
but rather than  "duplicate" the feature in the `go_router` package
I see more value in supporting the most common use cases for using imperative api directly into `go_router`

**Comment by tp** [comment]
@iapicca How would that look in practice? I get the declarative routing definitions (which exists now), but even calling `GoRouter.of(context).go('/page2')` is imperative, right? Or did you have something else in mind?

Personally I am very interested in purely declarative (and state driven) routing for Flutter.  
I have implemented an in-house version of such an approach in a medium-sized app. Initially with URL-based routing I ran into issues giving a URL to every case (which seemed cumbersome and limited in the kind of data we can pass, whereas each case is easily described by the app state already). Now I have dropped the whole URL requirement, and just have a simple mapping of `internal state -> Navigator.pages`. For the few cases where links are useful (some incoming deep links and share sheets), I just generate one that most closely matches the currently displayed page/state.

Would be happy to share more about that approach if it's of interest to you. Though as it's not URL-driven it might be too far off to be applicable here.

I just wondered how you would envision to get `go_router` more/fully declarative.

**Comment by Skogsfrae** [comment]
Well, I think the main reason to use imperative apis, at the moment, is the way go router builds its route stack:

```dart
GoRouter(
    routes: [
        GoRoute(
            path: '/',
            routes: [
                GoRoute(
                    path: 'page1',
                    routes: [
                        GoRoute(
                            path: 'sub-page1',
                        ),
                    ],
                ),
                GoRoute(
                    path: 'page2',
                    routes: [
                        GoRoute(
                            path: 'sub-page2',
                        ),
                    ],
                ),
            ],
        ),
    ],
);
```

by calling `GoRouter.of(context).go('/page2/sub-page2')` from `/page1/sub-page1`, go router purges the current navigation stack

```
/
/page1
/page1/sub-page1
```

and replaces it with

```
/
/page2
/page2/sub-page2
```

making it impossible to go back to the previous page, at least in mobile and desktop development (I don't know if the browser history comes to help in this scenario for web development).

Using `push` from the same start point, go router doesn't touch the current stack, but just adds the pushed route on top of it:

```
/
/page1
/page1/sub-page1
/page2/sub-page2
```

This is my use case since I can reach the same page from different areas of the app, and when popping the current route I'd like to get back from where I was before the navigation.

**Comment by chunhtai** [comment]
I think this is the direction we should go, but we don't have go to this extreme. We can still keep GoRouter.push/replace. but underneath we just do Navigator.push/replace. That way developers can still use their routing table but without messing up the declarative nature of goRouter. The pushed route will remain a pageless route, so that they won't be visible to GoRouter.

The problem with that is the end product of the route parsing is a page object. Even if we can get the Route object from Page.createRoutes, it will be treated as page-based route in Navigator. We will need to modify the code in flutter/flutter, which is not a big deal but we need to wait for next stable release.

**Comment by Colman** [comment]
What exactly is the point of context.go()? I don't ever see a case where you'd want to clear the nav stack and push every sub-route as an individual entry. When I click a link in the browser such as: https://github.com/flutter/flutter/pull/114362, the browser **doesn't** set the nav stack to this which is what the declarative approach does:

https://github.com
https://github.com/flutter
https://github.com/flutter/flutter
https://github.com/flutter/flutter/pull
https://github.com/flutter/flutter/pull/114362

Instead it just sets it to this:
https://github.com/flutter/flutter/pull/114362

When I click the same link in an external program such as discord, it also the nav stack to this:
https://github.com/flutter/flutter/pull/114362

It doesn't push the sub routes as individual items. I would think that a deep link into an app should work the same as this example. However, with go router it pushes each sub route as a separate entry even though we didn't navigate from those routes.

In my opinion, sub routes should just indicate how the app or website is logically structured, it shouldn't necessarily indicate **how** you got to a certain route. So when the declarative/go method pushes the sub routes on the stack as if we came from those routes, I get confused. It also worries me that there's a proposal to deprecate the imperative api when that's the only way to prevent your history from getting cleared.

**Comment by nicelogic** [comment]
i have a supplement
Imperative navigation：   final bool? result = await context.push<bool>('/page2');
is error-prone
push, pop is ok
but if “go” to page2, then pop, there is no way to fetch pop result
may cause page1 can't refresh state

**Comment by jopmiddelkamp** [comment]
I'm currently researching go_router for a mobile/web hybrid application and this made me feel a bit like @Colman explained as well.. For me it feels like removing support for imperative navigation makes building a mobile/web hybrid a bit difficult on the mobile end.. Or I'm missing something.. Would you maybe be so kind to reply on this @chunhtai? I'm really curious what your view on this topic is and how you see declarative routing in the context of a mobile/web hybrid.
