### ISSUE TITLE
i have installed flutter on mac, but  Running "flutter pub get" in flutter_tools... is all i get for 3 hrs when i run flutter doctor

### ISSUE THREAD

**Issue by Talasoft2022** [flutter/flutter#114276]
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

<details>
<summary>Logs</summary>

```
```

```
```

</details>

**Comment by iapicca** [comment]
@Talasoft2022 

I'm trying to deduce the issue from the title
> i have installed flutter on mac, but Running "flutter pub get" in flutter_tools... is all i get for 3 hrs when i run flutter doctor 

can please post the output of `flutter doctor -v` 
then run and post the output of
```bash
flutter create issue_114276 && \
cd issue_114276 && \
flutter run -d chrome
```

**Comment by Talasoft2022** [comment]
@Iapicca.
thank you for your response. It finally returned an output today after i reboot the system, which it was not doing before. I think i can find a way to complete the set up

**Comment by iapicca** [comment]
> @iapicca. thank you for your response. It finally returned an output today after i reboot the system, which it was not doing before. I think i can find a way to complete the set up

@Talasoft2022 
sounds like good news I guess, but not much of a bug report
if you need help with the installation maybe you can get assistance on [discord](https://discord.com/invite/N7Yshp4)

**Comment by darshankawar** [comment]
Closing based on above OP's and above comment.
