### ISSUE TITLE
[Windows][Desktop]: Unable to delete/backspace/Ctrl+A  text in TextField widget after switching to Burmese(Myanmar) keyboard input

### ISSUE THREAD

**Issue by yarzaryeni** [flutter/flutter#114223]
I found similar issue( #81257) for Chinese language and that case is already closed. But similar issue is still happening to Burmese scripts. I am creating an app that has a TextField, for Desktop Windows 11.  

### Issue Scenarios
- There is no issue => when I only type in  Burmese (Without combining with English words). 
- Arise the issue sometimes but not always => I type some English characters at the beginning, then switch to Burmese and keep writing only Burmese. 
- Always arise the issue => After typing some Burmese characters and I switch to English.

### The issue
When the issue arise, all of this happen together
- cannot delete text
- cannot use backspace
- cannot select all using Ctrl+A
- cannot move cursor using arrow keys

> Sometimes, I don't even have to type in Burmese. This issue arises just after I switched input language to Burmese. I am  using physical keyboard.

### Strange Scenarios
- If I type some Thai characters before I write any Burmese character, I can continue to type any combination of Burmese and English characters.  The issue only arise when I type in only Burmese and English combination. 

I tested the same project on Chrome browser and Android emulator, there is no issue. This issue is particularly happening on Windows. 

My flutter version info 
```
flutter --version
Flutter 3.3.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision d9111f6402 (9 days ago) • 2022-10-19 12:27:13 -0700
Engine • revision 3ad69d7be3
Tools • Dart 2.18.2 • DevTools 2.15.0
```

My code -
```
class TextArea extends StatelessWidget {
  const TextArea({super.key});
  @override
  Widget build(BuildContext context) {
    return const Padding(
      padding: EdgeInsets.all(10.0),
      child: TextField(
        maxLines: 50,
        keyboardType: TextInputType.multiline,
      ),
    );
  }
}
```

**Comment by huycozy** [comment]
Hi @yarzaryeni, thanks for filing the issue. I see there is an issue but the behavior is different than yours. 

Below are the steps I tried:
1. Switch to Burmese keyboard input
2. Run sample code
3. Input some text to TextField and then press `Space` key
4. The exception occurs from the console log

I still can delete or select all text normally. 

<details>
<summary>Logs</summary>

```
════════ Exception caught by scheduler library ═════════════════════════════════
The following assertion was thrown during a scheduler callback:
'package:flutter/src/widgets/editable_text.dart': Failed assertion: line 3014 pos 16: '!composingRange.isValid || composingRange.isCollapsed': is not true.
package:flutter/…/widgets/editable_text.dart:3014
2

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack
#2      EditableTextState._updateComposingRectIfNeeded
package:flutter/…/widgets/editable_text.dart:3014
#3      EditableTextState._updateComposingRectIfNeeded.<anonymous closure>
package:flutter/…/widgets/editable_text.dart:3020
#4      SchedulerBinding._invokeFrameCallback
package:flutter/…/scheduler/binding.dart:1175
#5      SchedulerBinding.handleDrawFrame
package:flutter/…/scheduler/binding.dart:1113
#6      SchedulerBinding._handleDrawFrame
package:flutter/…/scheduler/binding.dart:1015
#7      _invoke (dart:ui/hooks.dart:148:13)
#8      PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:318:5)
#9      _drawFrame (dart:ui/hooks.dart:115:31)
(elided 2 frames from class _AssertionError)
════════════════════════════════════════════════════════════════════════════════
```
</details>

<details>
<summary>flutter doctor -v (stable & master)</summary>

```bash
[√] Flutter (Channel stable, 3.3.6, on Microsoft Windows [Version 10.0.19043.2130], locale en-US)
    • Flutter version 3.3.6 on channel stable at C:\WIP\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6928314d50 (5 days ago), 2022-10-25 16:34:41 -0400
    • Engine revision 3ad69d7be3
    • Dart version 2.18.2
    • DevTools version 2.15.0

[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at C:\AndroidSDK
    • Platform android-32, build-tools 32.0.0
    • ANDROID_HOME = C:\AndroidSDK
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.2.6)
    • Visual Studio at D:\DOWNLOADWORK\VS2022
    • Visual Studio Community 2022 version 17.2.32630.192
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[!] Android Studio (version 2022.1)
    • Android Studio at C:\Program Files\Android\Android Studio Electric Eel 2022.1.1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    X Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[√] VS Code (version 1.72.2)
    • VS Code at C:\Users\ADMIN\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.50.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19043.2130]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 106.0.5249.121
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 103.0.1264.77

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

```bash
[!] Flutter (Channel master, 3.5.0-10.0.pre.166, on Microsoft Windows [Version 10.0.19043.2130], locale en-US)
    • Flutter version 3.5.0-10.0.pre.166 on channel master at C:\WIP\flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4f3f932a68 (7 hours ago), 2022-10-30 17:44:24 -0400
    • Engine revision f91119f84f
    • Dart version 2.19.0 (build 2.19.0-353.0.dev)
    • DevTools version 2.18.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git"
      directly to perform update checks and upgrades.

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at C:\AndroidSDK
    • Platform android-32, build-tools 32.0.0
    • ANDROID_HOME = C:\AndroidSDK
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.2.6)
    • Visual Studio at D:\DOWNLOADWORK\VS2022
    • Visual Studio Community 2022 version 17.2.32630.192
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[!] Android Studio (version 2022.1)
    • Android Studio at C:\Program Files\Android\Android Studio Electric Eel 2022.1.1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    X Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[√] VS Code (version 1.72.2)
    • VS Code at C:\Users\ADMIN\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.50.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19043.2130]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 106.0.5249.121
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 103.0.1264.77

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.
```
</details>

Can you retry on the latest Flutter `stable` and `master` channels and check the similar behavior?

**Comment by yarzaryeni** [comment]
> 
Hi Huycozy,
Thanks you for your reply. I will test again as you suggested and reply you soon.

**Comment by yarzaryeni** [comment]
> I found similar issue( #81257) for Chinese language and that case is already closed. But similar issue is still happening to Burmese scripts. I am creating an app that has a TextField, for Desktop Windows 11.
> ### Issue Scenarios
> 
>     * There is no issue => when I only type in  Burmese (Without combining with English words).
> 
>     * Arise the issue sometimes but not always => I type some English characters at the beginning, then switch to Burmese and keep writing only Burmese.
> 
>     * Always arise the issue => After typing some Burmese characters and I switch to English.
> 
> 
> ### The issue
> 
> When the issue arise, all of this happen together
> 
>     * cannot delete text
> 
>     * cannot use backspace
> 
>     * cannot select all using Ctrl+A
> 
>     * cannot move cursor using arrow keys
> 
> 
> > Sometimes, I don't even have to type in Burmese. This issue arises just after I switched input language to Burmese. I am  using physical keyboard.
> 
> ### Strange Scenarios
> 
>     * If I type some Thai characters before I write any Burmese character, I can continue to type any combination of Burmese and English characters.  The issue only arise when I type in only Burmese and English combination.
> 
> 
> I tested the same project on Chrome browser and Android emulator, there is no issue. This issue is particularly happening on Windows.
> 
> My flutter version info
> 
> ```
> flutter --version
> Flutter 3.3.5 • channel stable • https://github.com/flutter/flutter.git
> Framework • revision d9111f6402 (9 days ago) • 2022-10-19 12:27:13 -0700
> Engine • revision 3ad69d7be3
> Tools • Dart 2.18.2 • DevTools 2.15.0
> ```
> 
> My code -
> 
> ```
> class TextArea extends StatelessWidget {
>   const TextArea({super.key});
>   @override
>   Widget build(BuildContext context) {
>     return const Padding(
>       padding: EdgeInsets.all(10.0),
>       child: TextField(
>         maxLines: 50,
>         keyboardType: TextInputType.multiline,
>       ),
>     );
>   }
> }
> ```
Hi Huycozy,

I tried with the flutter version you suggested (3.6.6) and the problem still remain on my machine, Windows 11. However, when I tested on Windows 8 and Windows 10 virtual machines using the same EXE file, I have no issue. Currently, I don't have a chance to test on another windows 11 machine. If you are using Windows 11 and have not this issue, it might specifically be the problem with my machine only. Thank you so much for taking your time to check the problem.

**Comment by Hixie** [comment]
@yarzaryeni Do you see the exception that @huycozy is seeing, as well as the issue you describe? Or do you not get the exception?

Do you know if you have any special IME setup on your machine?

Testing on another Windows 11 machine to determine what might be the cause would be great.

Also if you could post your `flutter doctor -v` (like @huycozy) that would be great.
