### ISSUE TITLE
Incorrect recoloring of the background color of the switch and ball

### ISSUE THREAD

**Issue by MaxYablochkin** [flutter/flutter#114274]
#91605

Incorrect recoloring of the background color of the switch called "Track" and the "Thumb" ball.

![1](https://user-images.githubusercontent.com/102767277/198752297-f67b422e-8d05-412d-ba0b-2b0bc0567d02.png)
![2](https://user-images.githubusercontent.com/102767277/198752300-950c22cb-83fc-4c37-9cde-d6234a3077b9.png)
![3](https://user-images.githubusercontent.com/102767277/198752314-5fab6dad-9b98-4a66-a0fe-2276677f2bf6.png)
![4](https://user-images.githubusercontent.com/102767277/198752315-b6efb0f9-c956-4c90-b603-0a0711fd2527.png)

For an enabled switch, when the ball hits the border of the switch, the background color of the switch is repainted to a darker shade, and when the ball returns from the border to its original enabled position, the background is repainted to a lighter shade, and this happens on the last frames of the animation. The same applies to the animation of turning off the switch, as well as the of the ball itself.

**Comment by huycozy** [comment]
Hi @MaxYablochkin, I can not reproduce the issue on the latest `stable` and `master` channels.

| First time | Second time |
| --------------- | --------------- |
<img width="400" src="https://user-images.githubusercontent.com/104349824/198999824-d36488e3-ccc3-45d5-b609-45e3f6c58d2a.png"> | <img width="400" src="https://user-images.githubusercontent.com/104349824/198999841-ce32898b-9d54-4053-9af7-ddc964434c9a.png">

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.3.6, on macOS 12.6 21G115 darwin-x64, locale en-VN)
    • Flutter version 3.3.6 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6928314d50 (30 hours ago), 2022-10-25 16:34:41 -0400
    • Engine revision 3ad69d7be3
    • Dart version 2.18.2
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode14.0.1.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Community Edition (version 2022.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 70.0.5
    • Dart plugin version 222.4167.21

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.72.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (3 available)
    • SM T225 (mobile) • R9JT3004VRJ • android-arm64  • Android 12 (API 31)
    • macOS (desktop)  • macos       • darwin-x64     • macOS 12.6 21G115 darwin-x64
    • Chrome (web)     • chrome      • web-javascript • Google Chrome 107.0.5304.62

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

```bash
[!] Flutter (Channel master, 3.5.0-10.0.pre.166, on macOS 12.6 21G115 darwin-x64, locale en-VN)
    • Flutter version 3.5.0-10.0.pre.166 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4f3f932a68 (5 hours ago), 2022-10-30 17:44:24 -0400
    • Engine revision f91119f84f
    • Dart version 2.19.0 (build 2.19.0-353.0.dev)
    • DevTools version 2.18.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode14.0.1.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Community Edition (version 2022.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 70.0.5
    • Dart plugin version 222.4167.21

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.72.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.6 21G115 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 107.0.5304.87

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```
</details>

Which Flutter version are you using? Please retry on the latest stable or master channel to check if the issue still reproduces.

**Comment by MaxYablochkin** [comment]
This issue is observed during the radio button animation for any states, the colors of the radio button do not change correctly. This affects Unselected Track Color, Selected Track Color, Unselected Thumb Color, Selected Thumb Color. The color tones of each seem to have two colors, while the animation is playing, and at the end when the animation is over. It is noticeable, there is something wrong with the colors.

![Screenshot_1667223774](https://user-images.githubusercontent.com/102767277/199048507-0822ff3f-b003-4ca5-ab48-573a85a511f4.png)
![Screenshot_1667223782](https://user-images.githubusercontent.com/102767277/199048510-2aa0c82a-44f0-4eb8-9ff4-588a6b06267f.png)
![Screenshot_1667223679](https://user-images.githubusercontent.com/102767277/199048644-71a9f6ef-6516-42d3-9614-1bdafe2d6472.png)
![Screenshot_1667223709](https://user-images.githubusercontent.com/102767277/199048639-50eeeaf5-07e8-46e9-89fd-d7097171ffb6.png)


```
[✓] Flutter (Channel master, 3.5.0-10.0.pre.169, on Microsoft Windows [Version 10.0.22000.1165], locale ru-UA)
    • Flutter version 3.5.0-10.0.pre.169 on channel master at C:\Flutter-SDK\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 24dfdec3e2 (5 hours ago), 2022-10-31 06:54:24 -0400
    • Engine revision 08954650b9
    • Dart version 2.19.0 (build 2.19.0-353.0.dev)
    • DevTools version 2.18.0

[✗] Windows Version (Unable to confirm if installed Windows version is 10 or greater)

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at C:\Users\yablo\AppData\Local\Android\sdk
    • Platform android-TiramisuPrivacySandbox, build-tools 32.1.0-rc1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2022 17.3.6)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.3.32929.385
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2021.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Community Edition (version 2021.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.2.1
    • Flutter plugin version 70.2.2
    • Dart plugin version 212.5744

[✓] VS Code (version 1.72.2)
    • VS Code at C:\Users\yablo\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.50.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22000.1165]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 106.0.5249.121
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 107.0.1418.26

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

**Comment by huycozy** [comment]
@MaxYablochkin Quite strange, I can't reproduce this. Can you provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) and `Reproduction steps` so that we may verify this?

**Comment by MaxYablochkin** [comment]
> This issue is observed during the radio button animation for any states, the colors of the radio button do not change correctly. This affects Unselected Track Color, Selected Track Color, Unselected Thumb Color, Selected Thumb Color. The color tones of each seem to have two colors, while the animation is playing, and at the end when the animation is over. It is noticeable, there is something wrong with the colors.
> 
> variant1	variant2
> <img alt="" width="400" src="https://user-images.githubusercontent.com/102767277/199048507-0822ff3f-b003-4ca5-ab48-573a85a511f4.png">	<img alt="" width="400" src="https://user-images.githubusercontent.com/102767277/199048510-2aa0c82a-44f0-4eb8-9ff4-588a6b06267f.png">
> variant1	variant2
> <img alt="" width="400" src="https://user-images.githubusercontent.com/102767277/199048644-71a9f6ef-6516-42d3-9614-1bdafe2d6472.png">	<img alt="" width="400" src="https://user-images.githubusercontent.com/102767277/199048639-50eeeaf5-07e8-46e9-89fd-d7097171ffb6.png">
> ```
> [✓] Flutter (Channel master, 3.5.0-10.0.pre.169, on Microsoft Windows [Version 10.0.22000.1165], locale ru-UA)
>     • Flutter version 3.5.0-10.0.pre.169 on channel master at C:\Flutter-SDK\flutter
>     • Upstream repository https://github.com/flutter/flutter.git
>     • Framework revision 24dfdec3e2 (5 hours ago), 2022-10-31 06:54:24 -0400
>     • Engine revision 08954650b9
>     • Dart version 2.19.0 (build 2.19.0-353.0.dev)
>     • DevTools version 2.18.0
> 
> [✗] Windows Version (Unable to confirm if installed Windows version is 10 or greater)
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
>     • Android SDK at C:\Users\yablo\AppData\Local\Android\sdk
>     • Platform android-TiramisuPrivacySandbox, build-tools 32.1.0-rc1
>     • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
>     • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
>     • All Android licenses accepted.
> 
> [✓] Chrome - develop for the web
>     • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe
> 
> [✓] Visual Studio - develop for Windows (Visual Studio Community 2022 17.3.6)
>     • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
>     • Visual Studio Community 2022 version 17.3.32929.385
>     • Windows 10 SDK version 10.0.19041.0
> 
> [✓] Android Studio (version 2021.3)
>     • Android Studio at C:\Program Files\Android\Android Studio
>     • Flutter plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/9212-flutter
>     • Dart plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/6351-dart
>     • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
> 
> [✓] IntelliJ IDEA Community Edition (version 2021.2)
>     • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.2.1
>     • Flutter plugin version 70.2.2
>     • Dart plugin version 212.5744
> 
> [✓] VS Code (version 1.72.2)
>     • VS Code at C:\Users\yablo\AppData\Local\Programs\Microsoft VS Code
>     • Flutter extension version 3.50.0
> 
> [✓] Connected device (3 available)
>     • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22000.1165]
>     • Chrome (web)      • chrome  • web-javascript • Google Chrome 106.0.5249.121
>     • Edge (web)        • edge    • web-javascript • Microsoft Edge 107.0.1418.26
> 
> [✓] HTTP Host Availability
>     • All required HTTP hosts are available
> 
> ! Doctor found issues in 1 category.
> ```

I'll try one more attempt to show the problem😁
This problem is quite difficult to catch, but it is only noticeable when the thumb is animated, and incorrect color switching affects the ones described above.
![Screenshot_2022_11_01_13_47_50_988_com_example_flutter_switch_material3](https://user-images.githubusercontent.com/102767277/199319732-b04d1499-6ab5-470a-b09d-18a28771af78.jpg)
![Screenshot_2022_11_01_13_47_47_670_com_example_flutter_switch_material3](https://user-images.githubusercontent.com/102767277/199319737-a481b921-3589-489b-93ac-4e871ca15e44.jpg)

![Screenshot_2022_11_01_17_45_23_524_com_example_flutter_switch_material3](https://user-images.githubusercontent.com/102767277/199319904-4506c0a2-0def-439d-9b80-1064264aa312.jpg)
![Screenshot_2022_11_01_17_45_19_780_com_example_flutter_switch_material3](https://user-images.githubusercontent.com/102767277/199319907-2b30d64c-5680-4ca4-92e5-d8b8e03db107.jpg)

**Comment by huycozy** [comment]
Hi @MaxYablochkin, I still can not reproduce this issue.
Does this issue happen randomly? Or you can always reproduce it?
Also, I'm not sure if this issue happens on specific devices or not. Please provide affected device info and the output of `flutter doctor -v`. Thanks!

**Comment by MaxYablochkin** [comment]
Hi @huycozy 👋🤝
I catch this problem again and again without any difficulty, and I can reproduce on Android or Web, but I don't know for other devices. Interestingly, I don't see this color problem when dragging the switch with my finger, but in the case of a single click, this problem is visible.

```
[✓] Flutter (Channel master, 3.5.0-12.0.pre.28, on Microsoft Windows [Version 10.0.22000.1165], locale ru-UA)
    • Flutter version 3.5.0-12.0.pre.28 on channel master at C:\Flutter-SDK\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 24dfdec3e2 (2 days ago), 2022-10-31 06:54:24 -0400
    • Engine revision 08954650b9
    • Dart version 2.19.0 (build 2.19.0-353.0.dev)
    • DevTools version 2.18.0

[✗] Windows Version (Unable to confirm if installed Windows version is 10 or greater)

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at C:\Users\yablo\AppData\Local\Android\sdk
    • Platform android-TiramisuPrivacySandbox, build-tools 32.1.0-rc1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2022 17.3.6)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.3.32929.385
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2021.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Community Edition (version 2021.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.2.1
    • Flutter plugin version 70.2.2
    • Dart plugin version 212.5744

[✓] VS Code (version 1.72.2)
    • VS Code at C:\Users\yablo\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.50.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22000.1165]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 106.0.5249.121
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 107.0.1418.26

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

**Comment by huycozy** [comment]
Hi @MaxYablochkin, I label this issue for further insights from the team. Sorry about asking `flutter doctor -v` twice (I missed it from your 2nd comment)
