### ISSUE TITLE
Extend drawing in lifecycles in iOS

### ISSUE THREAD

**Issue by xster** [flutter/flutter#11421]
We're stopping animations too soon and restarting animations too late on iOS during native view transitions.

On the way out, we stop the animator on the engine side right at viewWillDisappear. It's probably too early since the next view controller's transition animation still leaves the flutter view partly visible. 

![udw4mi645za](https://user-images.githubusercontent.com/156888/28651764-9a5343f4-7238-11e7-9cd7-cb6db1943cc6.png)

Probably easier fix, just defer the call for the right effect in the engine directly. Though it would still be nice to introduce a new AppLifecycleState for users to know (or reuse inactive?). 

On the way back, we don't recreate a surface on the engine side or requests frames on the framework side until viewDidAppear when the transitions settled. 

![nnggojebg3a](https://user-images.githubusercontent.com/156888/28651899-7744b9dc-7239-11e7-8d64-bd0f95d8f4aa.png)

Would be nice to add a new AppLifecycleState for this as well. It's currently not handled or transmitted to the framework. 

Send to framework and let the framework start requesting frame on new signal.

**Comment by Hixie** [comment]
Seems like the "in the background but still visible" state that we already have (inactive) describes the two new states you describe above pretty well, so I'd re-use it for both (and update the docs accordingly). @cbracken may have opinions.

**Comment by xster** [comment]
For record, on the way out, Android does more or less the same thing. The animations stop as soon as the native transition is started. But the transition is fast enough that it's not noticeable. 

On the way in, Android goes to resumed as soon as the second activity goes away. 

I was somewhat worried about merging OS signals viewWillDisappear and applicationWillResignActive into one dart-side signal in case the user wants to react differently without writing native code. 

Though it's also somewhat edge case-y since I think the only way the user will end up in this situation (wanting to do something special with viewWillDisappear)  is if the user already wrote a hybrid app with native code. And we already merge view and app lifecycles with 'paused' and 'resumed' on iOS and Android. Will reuse and update docs.

**Comment by Hixie** [comment]
The problem with having three enum values for these three states is that it'll mean that people will implement the logic in one of the states and not the other two and their app will be buggy.

What's the use case for doing something different in these three states?

**Comment by xster** [comment]
Which 3 states are you referring to? I think we're already saying the same thing :)

I'll reuse the inactive state for both application will resign and view will disappear.

Have a fix in-progress that mostly works the way expected on simulator. Has a bug on physical devices where the rendering scales are off. Still trying to figure out.

**Comment by Hixie** [comment]
The three states I was referring to are "application is visible in background but does not have focus, because the phone is up", "application is visible but an animation is in progress to hide it", and "application is visible and an animation is in progress to fully show it".

**Comment by xster** [comment]
I meant we'll have one state like you suggested for all 3 you stated in https://github.com/flutter/flutter/issues/11421#issuecomment-318519429 (since there's already prior art for both merging directionality and view + app lifecycle events). 

Turns out the issue for the scaling problem was due to the sequentiality of the OS calls to viewWillAppear, viewDidLayoutSubviews and viewDidAppear. It wasn't affecting simulators because some elements from viewDidLayoutSubviews were not used. 

Because the operations originating from viewDidLayoutSubviews are posted on the UI queue and now possibly behind all the other tasks that come from creating the surface during viewWillAppear, it's possible an entire frame is fully rendered with the wrong viewport dimensions before the correct values are updated. 

Fix in https://github.com/flutter/engine/pull/3934
