### ISSUE TITLE
有没有使用flutter做智慧大屏的？类似这种

### ISSUE THREAD

**Issue by gionlime** [flutter/flutter#114209]
有没有使用flutter做智慧大屏的？类似这种
![image](https://user-images.githubusercontent.com/91245043/198500511-6aee880d-aa78-4266-b594-a78ba1b2f841.png)
![image](https://user-images.githubusercontent.com/91245043/198500535-d702afe8-4fbc-40b5-8f7b-eeeedb65275b.png)

![src=http___img zcool cn_community_014bde6176566911013e8943034b8e gif refer=http___img zcool](https://user-images.githubusercontent.com/91245043/198500699-8584db5f-e516-45ea-8460-6d852a19b2ac.gif)

**Comment by zohar-soul** [comment]
What do you want to say?

**Comment by lrd7512369** [comment]
这种你用vue去做呗，你这个很明显也不需要跨平台，何必用flutter呢

**Comment by stuartmorgan** [comment]
This is off-topic, as we have [explained before](https://github.com/flutter/flutter/issues/93446#issuecomment-965939357).
