### ISSUE TITLE
[CP] Adds a release_candidate variable to DEPS

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#114266]
### issue_link

https://github.com/flutter/flutter/issues/113931

### Commit Hash

85f6a6fc604df2943d6f061c4ba95d2485131737

### Target

stable

### pr_link

https://github.com/flutter/engine/pull/37132/

### Impacted Users

dart developers

### Impact Description

This change is required to unblock dart sdk CP to hotfix branch.

### Workaround

No workaround

### Risk

low

### Test Coverage

yes

### Validation Steps

Automated tests on presubmit validate these changes.

**Comment by CaseyHillers** [comment]
Can you link the recipes CP as well?

**Comment by CaseyHillers** [comment]
Friendly ping. Today's the last day for engine PRs to be submitted to make this weeks release.

**Comment by godofredoc** [comment]
CP to recipes branch: https://flutter-review.googlesource.com/c/recipes/+/35302

**Comment by CaseyHillers** [comment]
The CP request LGTM
