### ISSUE TITLE
Add the `--config-only` flag on `flutter build macos`

### ISSUE THREAD

**Issue by dion-gionet** [flutter/flutter#114251]
## Use case
Not sure if there's already an issue open for this, I couldn't find it, but I believe the `--config-only` flag should be added on `flutter build macos` just like `flutter build ios`. To be used in conjunction with fastlane on CI/CD for example.

## Proposal
Add the `--config-only` flag on `flutter build macos`, same as  `flutter build ios`

**Comment by darshankawar** [comment]
Closing this as duplicate of https://github.com/flutter/flutter/issues/84018
