### ISSUE TITLE
[web] Failed to load the canvaskit

### ISSUE THREAD

**Issue by deepak786** [flutter/flutter#114289]
One user is facing this issue when he opened the Flutter web app. So he is not able to use the app.

![Screen Shot 2022-10-29 at 4 49 13 PM](https://user-images.githubusercontent.com/14223997/198829034-d1126bfc-b61b-4f78-9cd7-e3ed5beb2e58.png)

Note: I don't have reproducible steps.

**Comment by darshankawar** [comment]
@deepak786 
Please check [this](https://github.com/flutter/flutter/issues/114230) issue and underlying comments and see if they help in your case.

**Comment by deepak786** [comment]
@darshankawar It was the issue in UNPKG and it is fixed already. Also seems to be working fine for our user.
