### ISSUE TITLE
[web] [google_maps_flutter_web] Slider over map causes the map to move

### ISSUE THREAD

**Issue by bw-flagship** [flutter/flutter#114217]
## Steps to Reproduce

1. Execute `flutter run` on the code sample (see "Code sample" section below
2. Move the slider

**Expected results:** 
The map in the background should not move

**Actual results:** 
The map in the background moves

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      title: 'Maps Bug Demo',
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  double _value = 5;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Stack(
        children: [
          const GoogleMap(
            initialCameraPosition: CameraPosition(
              target: LatLng(
                51.5160895,
                -0.1294527,
              ),
              zoom: 17,
            ),
          ),
          Center(
            child: Container(
              color: Colors.red,
              height: 100,
              width: 200,
              child: Slider(
                  value: _value,
                  min: 0,
                  max: 10,
                  onChanged: (value) {
                    setState(() {
                      _value = value;
                    });
                  }),
            ),
          ),
        ],
      ),
    );
  }
}

```

</details>

<details>
  <summary>Logs</summary>

(.........) -> cut logs before because too long for github
[        ] MetadataProvider: Loaded debug metadata for module: packages/google_maps_flutter_platform_interface/src/types/utils/map_configuration_serialization.dart
[        ] MetadataProvider: Loaded debug metadata for module: packages/google_maps_flutter_platform_interface/src/types/tile_overlay_updates.dart
[        ] MetadataProvider: Loaded debug metadata for module: packages/googlemapsbugdemo/main.dart
[        ] MetadataProvider: Loaded debug metadata for module: packages/google_maps_flutter/google_maps_flutter.dart
[        ] MetadataProvider: Loaded debug metadata for module: packages/google_maps_flutter_android/google_maps_flutter_android.dart
[        ] MetadataProvider: Loaded debug metadata for module: packages/google_maps_flutter_android/src/google_maps_flutter_android.dart
[        ] MetadataProvider: Loaded debug metadata for module: packages/google_maps_flutter_android/src/google_map_inspector_android.dart
[        ] MetadataProvider: Loaded debug metadata (sound null safety)
[   +2 ms] DwdsInjector: Injected debugging metadata for entrypoint at http://localhost:49430/main_module.bootstrap.js
[+1488 ms] ChromeProxyService: Initializing expression compiler for main_module.bootstrap.js with sound null safety: true
[  +30 ms] DevHandler: Debug service listening on ws://127.0.0.1:57556/R5VPr6mLsQQ=/ws

[   +7 ms] DevHandler: VmService proxy responded with an error:
           {jsonrpc: 2.0, id: 9, error: {code: -32601, message: Method not found, data: {jsonrpc: 2.0, method: _setStreamIncludePrivateMembers, id: 9, params: {streamId: Stdout, includePrivateMembers: false}}}}
[   +1 ms] This app is linked to the debug service: ws://127.0.0.1:57556/R5VPr6mLsQQ=/ws
[        ] DevHandler: VmService proxy responded with an error:
           {jsonrpc: 2.0, id: 10, error: {code: -32601, message: Method not found, data: {jsonrpc: 2.0, method: _setStreamIncludePrivateMembers, id: 10, params: {streamId: Stderr, includePrivateMembers: false}}}}
[        ] DevHandler: VmService proxy responded with an error:
           {jsonrpc: 2.0, id: 11, error: {code: -32601, message: Method not found, data: {jsonrpc: 2.0, method: _setStreamIncludePrivateMembers, id: 11, params: {streamId: Isolate, includePrivateMembers: false}}}}
[   +1 ms] DevHandler: VmService proxy responded with an error:
           {jsonrpc: 2.0, id: 12, error: {code: -32601, message: Method not found, data: {jsonrpc: 2.0, method: _setStreamIncludePrivateMembers, id: 12, params: {streamId: Extension, includePrivateMembers: false}}}}
[   +1 ms] Debug service listening on ws://127.0.0.1:57556/R5VPr6mLsQQ=/ws
[        ] 💪 Running with sound null safety 💪
Debug service listening on ws://127.0.0.1:57556/R5VPr6mLsQQ=/ws
[  +67 ms] DevHandler: VmService proxy responded with an error:
           {jsonrpc: 2.0, id: 16, error: {code: -32601, message: Method not found, data: {jsonrpc: 2.0, method: _setStreamIncludePrivateMembers, id: 16, params: {streamId: Debug, includePrivateMembers: false}}}}
[        ] DevHandler: VmService proxy responded with an error:
           {jsonrpc: 2.0, id: 17, error: {code: -32601, message: Method not found, data: {jsonrpc: 2.0, method: _setStreamIncludePrivateMembers, id: 17, params: {streamId: Extension, includePrivateMembers: false}}}}
[        ] DevHandler: VmService proxy responded with an error:
           {jsonrpc: 2.0, id: 18, error: {code: -32601, message: Method not found, data: {jsonrpc: 2.0, method: _setStreamIncludePrivateMembers, id: 18, params: {streamId: Logging, includePrivateMembers: false}}}}
[   +7 ms] DevHandler: VmService proxy responded with an error:
           {jsonrpc: 2.0, id: 22, error: {code: -32601, message: Method not found, data: {jsonrpc: 2.0, method: _setStreamIncludePrivateMembers, id: 22, params: {streamId: Isolate, includePrivateMembers: false}}}}
[ +376 ms] Flutter Web Bootstrap: Programmatic

```

<!--
     Run `flutter analyze` and attach any output of that command below.
     If there are any analysis errors, try resolving them before filing this issue.
-->

```
Analyzing googlemapsbugdemo...                                          
No issues found! (ran in 1.2s)
```

<!-- Finally, paste the output of running `flutter doctor -v` here. -->

```
[!] Flutter (Channel unknown, 3.3.5, on macOS 13.0 22A380 darwin-arm, locale
    en-DE)
    ! Flutter version 3.3.5 on channel unknown at
      /users/bweber/Development/flutter
    ! Upstream repository unknown
    • Framework revision d9111f6402 (9 days ago), 2022-10-19 12:27:13 -0700
    • Engine revision 3ad69d7be3
    • Dart version 2.18.2
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/bweber/Library/Android/sdk
    • Platform android-33, build-tools 30.0.3
    • Java binary at: /Users/bweber/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/212.5712.43.2112.8815526/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Users/bweber/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/212.5712.43.2112.8609683/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] Android Studio (version 2021.2)
    • Android Studio at /Users/bweber/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/212.5712.43.2112.8815526/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.72.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (4 available)
    • Pixel 6 (mobile)      • 21121FDF600967                           • android-arm64  • Android 13 (API 33)
    • MyRealiPhone (mobile) • 379b967bb17aa779d9db993cf9a4e935e416fb28 • ios            • iOS 15.6.1 19G82
    • macOS (desktop)       • macos                                    • darwin-arm64   • macOS 13.0 22A380 darwin-arm
    • Chrome (web)          • chrome                                   • web-javascript • Google Chrome 107.0.5304.87
    ! Error: MyRealiPhone is busy: Fetching debug symbols for MyRealiPhone. Xcode will continue when MyRealiPhone is finished. (code -10)

[✓] HTTP Host Availability
    • All required HTTP hosts are available

```

</details>
![MapsSlideDemo](https://user-images.githubusercontent.com/89379862/198555716-caafd5a1-66a0-4796-9f45-dcb0b8a8fd74.gif)

**Comment by bw-flagship** [comment]
![MapsSlideDemo](https://user-images.githubusercontent.com/89379862/198554691-e55d4dc9-a2b0-40a4-8a74-cd7e1ba9cc17.gif)

Somehow the gif is not displayed in my main comment, so i post it again here

**Comment by TahaTesser** [comment]
Hi @bw-flagship 
This is not just Slider but many gestures, please see https://github.com/flutter/flutter/issues/73830#issuecomment-760588189 for more details.
Closing as duplicate.
