### ISSUE TITLE
it would be nice if the device lab tasks could be run directly

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter#11425]
To run a devicelab task locally for testing, I do:

```
dart bin/run.dart -t commands_test
```

When I try and run a task directly (`dart bin/tasks/commands_test.dart `), I see:

```
SEVERE: 2017-07-27 08:39:49.239191: Task did not start in 0:00:10.000000.
```

I'm not sure why it doesn't work when run directly, but this would be a nice feature to have when iterating locally on a task.

@yjbanov

**Comment by yjbanov** [comment]
`dart bin/run.dart -t bin/tasks/commands_test.dart`

**Comment by devoncarew** [comment]
Just to be clear, this issue wasn't about using `run.dart -t`, but executing the the test script directly (`dart bin/tasks/commands_test.dart`).

**Comment by yjbanov** [comment]
Ah, I misunderstood. Unfortunately, there are no plans to support it due to the way devicelab infra works.
