### ISSUE TITLE
[plugin][local_auth] Incorporate cryptography into biometric authentication workflow

### ISSUE THREAD

**Issue by Petri-Oosthuizen** [flutter/flutter#114220]
## Use case

I would like to encrypt and decrypt sensitive data using the user's biometrics. This data should only be accessible by the user who has set the biometric auth on their device. I'm familiar with [flutter_secure_storage](https://pub.dev/packages/flutter_secure_storage) but would like a layer on top of this. This can be done on Android as seen in the [Use a cryptographic solution that depends on authentication](https://developer.android.com/training/sign-in/biometric-auth#crypto) biometric auth section. 

## Proposal

Return a secret key after a successful authentication which can be used to perform encryption and decryption.

**Comment by stuartmorgan** [comment]
`local_auth` isn't intended for encryption use cases. This use case would be best served by a plugin designed for secure storage, incorporating biometrics into its design.
