### ISSUE TITLE
[web] Run web engine unit tests compiled to webassembly

### ISSUE THREAD

**Issue by eyebrowsoffire** [flutter/flutter#114241]
We need to modify our test harness to allow us to compile our web engine unit tests to WebAssembly and run them. Current progress on this work is happening here: https://github.com/flutter/engine/pull/36255

**Comment by iapicca** [comment]
see also
- https://github.com/flutter/flutter/issues/41062

**Comment by eyebrowsoffire** [comment]
Fixed with https://github.com/flutter/engine/pull/36255
