### ISSUE TITLE
[Impeller] GPU usage regressions for rrect blur fast path

### ISSUE THREAD

**Issue by bdero** [flutter/flutter#114249]
When improving the fidelity of the blur approximation in https://github.com/flutter/engine/commit/f7a45172b6f484819b690749214aebf16974735b, this (predictably) increased GPU utilization for some benchmarks. On the Moto G4, this resulted in worse raster time performance (most likely because we're GPU bound).

If we need to make this faster in the future, we have lots of legroom to do so at the marginal cost of fidelity.
* Reduce the Y direction sample size. 5 looks virtually indistinguishable with the slow blur when compared side-by-side, but 4 also looks quite acceptable.
* Use a less accurate erf approximation (Skia also uses a simpler logistic sigmoid for some shadows).

Benchmarks:
* https://flutter-flutter-perf.skia.org/e/?begin=1666394947&end=1666978259&keys=X22f7df96495e5154c7d0e597ee8137d8&requestType=0&selected=commit%3D31798%26name%3D%252Carch%253Dintel%252Cbranch%253Dmaster%252Cconfig%253Ddefault%252Cdevice_type%253DiPhone_6s%252Cdevice_version%253Dnone%252Chost_type%253Dmac%252Csub_result%253Daverage_gpu_usage%252Ctest%253Dtiles_scroll_perf_impeller_ios__timeline_summary%252C&xbaroffset=31798
* https://flutter-flutter-perf.skia.org/e/?begin=1666908302&end=1666977899&keys=X44bbcf60fd50936e079a6fd88e886cc5&selected=commit%3D31798%26name%3D%252Carch%253Dintel%252Cbranch%253Dmaster%252Cconfig%253Ddefault%252Cdevice_type%253DMoto_G__4_%252Cdevice_version%253Dnone%252Chost_type%253Dlinux%252Csub_result%253D90th_percentile_frame_rasterizer_time_millis%252Ctest%253Dnew_gallery_impeller__transition_perf%252C&xbaroffset=31798

**Comment by davidhicks980** [comment]
I apologize if this is not related, but it sounds like it may be. I've been implementing a Cupertino Menu and have found Impeller blur to  >2x as slow.


Current: 
https://user-images.githubusercontent.com/59215665/222547441-d2b4d0cf-dcb2-47dc-b38f-ca1062618d63.mp4

Impeller:
https://user-images.githubusercontent.com/59215665/222547456-c91e384d-1e7b-4a83-9d57-c6344b63ada4.mp4

Removing blur fixes the issue.

The relevant snippet is:

```dart
class _MenuSurface extends StatelessWidget {
  const _MenuSurface({required this.child});
  final Widget child;

  static final ImageFilter filter = ImageFilter.compose(
    inner: ImageFilter.blur(sigmaX: 16, sigmaY: 16),
    outer: ColorFilter.matrix(
      ColorFilterGenerator.saturationAdjustMatrix(
        value: 1.1,
      ),
    ),
  );

  @override
  Widget build(BuildContext context) {
    return Stack(children: [
      if (CupertinoMenu.kBackgroundColor.alpha != 0xFF)
        ClipRRect(
          borderRadius: BorderRadius.all(Radius.circular(13)),
          child: BackdropFilter(
            filter: filter,
            child: SizedBox.expand(),
          ),
        ),
      Container(
        clipBehavior: Clip.hardEdge,
        decoration: const BoxDecoration(
          borderRadius: BorderRadius.all(Radius.circular(13)),
          color: CupertinoMenu.kBackgroundColor,
          boxShadow: [
            BoxShadow(
              spreadRadius: 30,
              blurRadius: 50,
              color: Color.fromARGB(25, 0, 0, 0),
            ),
          ],
        ),
        child: child,
      )
    ]);
  }
}
```

I wish I could provide a solution but I'm certain you all are far more acquainted with the challenges of making something like this performant. I would be curious to hear about whether the Flutter team would consider implementing something more approximate like the Kawase algorithm, or whether this is a non-starter?

**Comment by bdero** [comment]
This particular issue was resolved some time ago and is outdated. Backdrop blurs use a different path.

The RRect blur is using a faster erf approximation now and the sample count has been adjusted, which pulled the benchmarks back down ~half way towards their original low value, but kept the blurs looking correct.

If you're running into worse performance than Skia for backdrop blurs on the master channel, please file an issue with a reproduction and info about the devices you're testing with! We've recently landed changes to better prevent filters from processing offscreen content, but there still might be lingering cases where that can occur, for example.
