### ISSUE TITLE
[camera] web camera controller return webm mimetype of recorded video, with no duration data

### ISSUE THREAD

**Issue by Navdeep-Goyal** [flutter/flutter#114285]
When recording video with camera controller, it return XFile, which has mimeType of webm. There is loss of some information like duration of video.

Also, not able to record mp4 videos with camera controller on web.

**Comment by darshankawar** [comment]
@Navdeep-Goyal 
Can you provide `flutter doctor -v`, camera plugin version along with complete minimal code sample that shows the current behavior ?
