### ISSUE TITLE
[web] ☂️ Implement skwasm renderer

### ISSUE THREAD

**Issue by eyebrowsoffire** [flutter/flutter#114243]
This tracks fully implementing the `Renderer` API using the skwasm wasm module.

**Comment by iapicca** [comment]
see also
- https://github.com/flutter/flutter/issues/41062

**Comment by eyebrowsoffire** [comment]
I'm going to treat this as an umbrella for the remaining pieces to get this feature parity with CanvasKit:
https://github.com/flutter/flutter/issues/126339
https://github.com/flutter/flutter/issues/126340
https://github.com/flutter/flutter/issues/126341
https://github.com/flutter/flutter/issues/126342
https://github.com/flutter/flutter/issues/126345

**Comment by eyebrowsoffire** [comment]
Done with https://github.com/flutter/engine/pull/43011
