### ISSUE TITLE
How can I debug a large and slow display list?

### ISSUE THREAD

**Issue by matthew-carroll** [flutter/flutter#114306]
I'm trying to diagnose and improve the performance of my Flutter app. I'm rendering pages of a document, which involves rendering a whole bunch of tiny `Paragraph` objects, as well as a lot of repositioning.

I'm consistently seeing lag in the display list dispatch:
![Screen Shot 2022-10-28 at 7 36 02 PM](https://user-images.githubusercontent.com/7259036/198856290-e85c4f99-74e0-4bfe-b911-3af31d2d6625.png)

How can I inspect and analyze the display list to see if I can achieve better performance?

I've tried re-arranging various `Canvas` calls in the hope that it would result in a smaller display list, but I haven't seen any difference in the lag. Without understanding what's happening in that display list, I'm operating blind.

**Comment by chinmaygarde** [comment]
* The volume of individual un-batched draw calls will affect dispatch performance. Rearranging draw calls is probably not going to help. Reducing the number might.
* `--trace-skia` might give you more insights into whats happening below dispatch.

**Comment by matthew-carroll** [comment]
Thanks. I ran with `--trace-skia`. Here's a screenshot of what I'm seeing:

![Screen Shot 2022-11-09 at 4 06 52 PM](https://user-images.githubusercontent.com/7259036/200968490-f83ac1d9-7aab-4108-b2b3-dd7635ac7c0e.png)

I see a couple of takeaways here. There's this one big call to `drawTextBlob()` that takes 104ms. But also there's a whole bunch of tiny calls, most of which are also calls to `drawTextBlob()`. This isn't unexpected, because we're rendering document pages, which contains lots of text. That text is broken into tiny chunks.

I'm wondering if there's any way to overcome this performance problem. When I see all the little text blob calls, I think that maybe I should try to group a bunch of those text snippets together into `Paragraph` objects that contains more text, so that we're not measuring a large number of tiny snippets. However, we can see that there's already a very long-running `drawTextBlob()`, which suggests that creating `Paragraph`s with more text might further exacerbate the perf issue.

I'm also confused as to why I'm seeing such a long-running `drawTextBlob()`. There's not a single `Paragraph` object on this page of the document that contains more than a few characters...

**Comment by dnfield** [comment]
Skia will break up `drawTextBlob` whenever the font changes, for example if you have emojis or other characters from a fallback font.

IOW, a single `ui.Paragraph` object can result in hundreds of `SkCanvas::drawTextBlob` calls, particularly if you end up with a string that's something like `<emoji><space><emoji><space>` etc. where the space and emoji come from different fonts. 

I don't think there's a way to do this without a custom build, but you could try instrumenting the code some to figure out what glyphs are actually in that call. It's likely, however, that it's just taking time creating the glyph atlas and uploading a texture for it.

**Comment by matthew-carroll** [comment]
@dnfield my working theory has been that the shear number of `ui.Paragraph` objects is probably the culprit. However, your description suggests that maybe that's not the problem after all. Are there any adjustments I can make in terms of what's rendered to help diagnose that, without doing custom engine builds? For example, if I change the font so that everything is Roboto, and the render time is still large, does that tell us the problem is the number of `ui.Paragraph`s, rather than the creation of the glyph atlas and texture upload?

**Comment by dnfield** [comment]
You'd probably want to do some kind of CPU profiling to see where time is actually getting spent, and you may have better luck with platform specific tools (Perfetto, Instruments) since the native C++ code is likely what's more expensive here.

Even if you specify Roboto as the font for all your paragraph objects, SkParagraph will still fallback if it can't find the glyph you're asking for in Roboto (e.g. if you have an emoji, or if you have some other unicode character that it can't find there).

I'm pretty sure we could be doing better around how we handle text blob calls, but I've really only looked into it for the Impeller backend (which isn't really benefiting from broken up SkTextBlobs) rather than Skia (which might be benefitting). Also keep in mind that depending what platform you're on, the tracing itself has overhead...

**Comment by matthew-carroll** [comment]
We ended up testing our assumption about `Paragraph` objects by implementing our own glyph rendering. That experiment proved that the problem was the number of `Paragraph`s in the display list. We don't see any obvious way to use Flutter's existing text painting APIs to accomplish our goals, so we're going to render our own glyphs.

It would still be nice if there were a way to inspect the display list, but I'm going to close this because we're moving in different direction.
