### ISSUE TITLE
Create a web doc page for lifecycles

### ISSUE THREAD

**Issue by xster** [flutter/flutter#11431]
Would be nice to have a page dedicated to both internal flutter lifecycles and platform lifecycle events with diagrams. 

The internal stuff is already at https://flutter.io/widgets-intro/#responding-to-widget-lifecycle-events. Could just re-summarize visually.

**Comment by Hixie** [comment]
The page is https://master-docs-flutter-io.firebaseapp.com/flutter/dart-ui/AppLifecycleState-class.html
We should definitely add suitable diagrams to that page though.

**Comment by sethladd** [comment]
Do we link to AppLifecycleState from /widgets-intro ?

**Comment by Hixie** [comment]
I don't know but we certainly should! :-)

**Comment by xster** [comment]
Might still be worth having an 'editorial'/'guide' style page like Android/iOS have in https://developer.apple.com/library/content/documentation/iPhone/Conceptual/iPhoneOSProgrammingGuide/TheAppLifeCycle/TheAppLifeCycle.html, https://developer.android.com/guide/components/activities/activity-lifecycle.html besides the API references

**Comment by Sfshaza** [comment]
More correct link to API doc:  https://docs.flutter.io/flutter/dart-ui/AppLifecycleState-class.html

**Comment by zoechi** [comment]
Issue moved to [flutter/website #1987](https://github.com/flutter/website/issues/1987) via [**ZenHub**](https://www.zenhub.com/)
