### ISSUE TITLE
dart:html not support webkitEnterFullscreen

### ISSUE THREAD

**Issue by HG9558** [flutter/flutter#114386]
I am using Flutter for development. Now there is a scenario. I need to click on a video to achieve a full screen display effect. In Chrome browser, I can use Request FullScreen, but it doesn't work in safari browser. I tried to use webkitEnterFullscreen and it generated an error, here is my error message.

<img width="861" alt="image" src="https://user-images.githubusercontent.com/22909991/199140205-e97d2e06-f65a-43b7-82a6-3a0ebb94c5b9.png">

**Comment by exaby73** [comment]
Hello @HG9558. `dart:html` is not maintained by the Flutter team. Therefore this issue is not valid for this repo. Please raise this issue in https://github.com/dart-lang/sdk instead. Closing for those reasons. Thank you.
