### ISSUE TITLE
ListView with ListTiles bleeds outside its boundary

### ISSUE THREAD

**Issue by sriram-srinivasan** [flutter/flutter#114390]
A single column with two widgets, a listview and a status text box. If the list tile has a background colour, it bleeds into the space for the text box. 

https://dartpad.dartlang.org/?id=ae3f211b40d6c78716b6da5a2d8051a1

The ugly workaround is to have the text box in a container with a background colour, but that's only hiding a potential problem.

**Comment by sriram-srinivasan** [comment]
To add to above, it is ListTile-specific. Replacing it with a container composite does not have this issue.

**Comment by exaby73** [comment]
Hello @sriram-srinivasan. This is working as expected. This is happening because the `tileColor` is being painted on the nearest `Material` which happens to be on the `Scaffold`. You can fix this by wrapping your `ListView` with a `Material`. See code sample below.

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {

  @override
  Widget build(BuildContext context) {

    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.end,
          children: [
            Expanded(child: _buildList()),
            _buildMessageBar()
          ]
        ),
      ),
    );
  }
  Widget _buildList() {
    return Material(
      child: ListView.builder(
        itemCount: 200,
        itemBuilder: (BuildContext context, int i) {
          return Padding(
            padding: const EdgeInsets.all(4),
              child: ListTile(
                title: Text("Tile #$i", style: Theme.of(context).textTheme.bodyText1),
                tileColor: Colors.lightGreen.withOpacity(0.1),
              )
          );
        }
      ),
    );
  }

  Widget _buildMessageBar() {
    return const SizedBox(height: 50, child: Text("This is a status message bar"));
  }
}
```

</details>

Since this is working as expected, I am closing this issue. Thank you.

**Comment by sriram-srinivasan** [comment]
Thanks for the rapid response. I don't understand why it is supposed to work that way. I'm surprised that a tile color is painted anywhere outside itself. Why does it have to seek out the closest enclosing Material widget and paint all over it?
