### ISSUE TITLE
[Proposal] Should we provide MacOS style widgets under `cupertino.dart`?

### ISSUE THREAD

**Issue by navaronbracke** [flutter/flutter#114300]
Currently the Cupertino widgets library only provides an iOS style `CupertinoAlertDialog`, among other iOS style widgets.
There are no MacOS equivalents available in the widgets catalogue.

## Use case

Consider the following code, which shows a dialog for the current platform using existing widgets from the SDK.
If I were to show a MacOS style dialog for `TargetPlatform.macOS`, I'd have to write my own dialog.

```
  switch (Theme.of(context).platform) {
    case TargetPlatform.android:
    case TargetPlatform.fuchsia:
    case TargetPlatform.linux:
    case TargetPlatform.windows:
      return showDialog<T>(
        builder: (context) => AlertDialog(/* configuration */),
        context: context,
      );
    case TargetPlatform.iOS:
    case TargetPlatform.macOS:
      return showCupertinoDialog(
        builder: (context) => CupertinoAlertDialog(/* configuration */),
        context: context,
      );
  }
```

Example of such a dialog from VSCode:

![Screenshot 2022-10-29 at 20 55 29](https://user-images.githubusercontent.com/23480364/198848325-6a576a13-494c-47d4-bb57-f9b64cb6f191.png)

## Proposal

I'd propose to re-evaluate what exactly should be in the `cupertino` widgets library.

Currently it provides _some_ iOS-style widgets (probably not the newer ones defined by Apple).
It does not provide anything that follows the MacOS style (dialogs, buttons, etc.)

Should we even include MacOS style widgets in the SDK itself?
Maybe we can get away with adding a (first-party*) widgets library for MacOS style widgets?
The same happened for windows with `fluent_ui`, so why not?

*Since cupertino is part of the SDK, I'm not sure if this should be first-party or not.
  There is a reason why the plus plugins are a thing.

**Comment by jonahwilliams** [comment]
We have no current plans to expand the widget libraries to include macOS desktop widgets. IF you're interested in these, I would recommend checkking out https://pub.dev/packages/macos_ui
