### ISSUE TITLE
Publish Flutter engine in online maven repo

### ISSUE THREAD

**Issue by JFixby** [flutter/flutter#11439]
Hello,

Can you please publish an official Flutter API stub artifact on a maven repo?

Here is an example of Android API stub: https://mvnrepository.com/artifact/com.google.android/android/4.1.1.4
That helps to compile your java libraries against the Android API.

Would be nice to have similar for Flutter.
Here is a working example of such artifact: https://github.com/Scarabei/Flutter

```
This is not functional and only provides stubbed implementations of the Flutter API.
All methods in all classes throw a runtime exception. Because an Android app runs
on a device, it will never use these libraries for execution, but the API compatibility
allows an app to be compiled as if it was the real library.
```

**Comment by eseidelGoogle** [comment]
This is probably an @mravn-google or @jason-simmons question. :)

**Comment by sethladd** [comment]
cc @mit-mit

**Comment by Hixie** [comment]
Can you elaborate on why you want this?

**Comment by JFixby** [comment]
Usage scenario assuming Flutter API stub is published on a repo:

1) API user writes a library that imports Flutter API as a dependency. It is one line in a ```build.gradle``` file:
```
dependencies {
    compile "com.google:flutter-api:2017-07-24-5278588d80"
}
```
2) The library compiles its Java-classes against the API and goes to a repo.

Here is an example of such class: [android emplementation of a Flutter plugin](https://github.com/Scarabei/Scarabei/blob/master/scarabei-red-android-flutter/src/com/jfixby/scarabei/red/flutter/example/ExamplePlugin.java#L9)

The class depende on the ```io.flutter.plugin.common`.*``
```Java
package com.jfixby.scarabei.red.flutter.example;

import com.jfixby.scarabei.android.api.Android;
import com.jfixby.scarabei.api.log.L;

import io.flutter.plugin.common.MethodCall;
import io.flutter.plugin.common.MethodChannel.MethodCallHandler;
import io.flutter.plugin.common.MethodChannel.Result;

public class ExamplePlugin implements MethodCallHandler {

	@Override
	public void onMethodCall (final MethodCall call, final Result result) {
		L.d("ExamplePlugin.onMethodCall", call.method);
		if (call.method.equals("getPlatformVersion")) {
			final String message = "Android " + android.os.Build.VERSION.RELEASE + " " + Android.getSystemInfo();
			result.success(message);
		} else {
			result.notImplemented();
		}
	}
}
```

4) Library user imports the ```ExamplePlugin``` into his Android project using ```gradle``` and binds it to implement Android part of a Flutter plugin [example activity](https://github.com/Scarabei/Scarabei/blob/master/scarabei-red-android-flutter/src/com/jfixby/scarabei/red/flutter/example/ExampleFlutterActivity.java#L31)

**Comment by JFixby** [comment]
>no need all the android framework settings i.e. project files, resources, gradle build settings and the manifest.
>android framework is no needed too and the library is published to be available via gradle and to be reused in different android apps
>otherwise each flutter plugin contains a full android project and requires a lot of attention to it's config files.

**Comment by JFixby** [comment]
> There are basically two options for including external libraries in your Android application. The first is to manually copy the jars into the libs directory within your project and update the classpath. The disadvantage is that you have to manage the dependencies manually. Alternatively, a third party plugin such as the Maven Android Plugin can be utilized to automatically include the dependencies from a Maven repository.

> In order to build an android application on the command line (and therefore in continuous integration environments..) the standard way is to use build systems. One of the most common systems with many additional benefits beyond ant is Apache Maven. Gradle understand this repository format and can retrieve artifacts from it. 

Currently users that want to build their Android project with Gradle need to publish the flutter.jar artifact into their private repository server or at minimum into their private local repository.

**Comment by matthew-carroll** [comment]
@mravn-google @Hixie Should this ticket have an "existing apps" tag?

**Comment by Hixie** [comment]
If you think this is relevant to a particular label, you should definitely add the label.

**Comment by mravn-google** [comment]
Added the existing apps label. A Flutter API artifact could be used in add2app scenarios to provide an API similar to that currently included in the Flutter Module project template. That would relieve the template of a rather non-standard responsibility (providing Java source code that the app author is not supposed to edit---instead of a pre-built jar).

There is a choice of what to put into such an artifact rather than Flutter Engine. One goal could be to relieve Flutter Engine of volatile dependencies on Android support libs (which are updated frequently for reasons not related to Flutter).

**Comment by neiljaywarner** [comment]
@JFixby  can you please restore your link to exampleactivity if you have time or post it here?
@matthew-carroll is this related to https://github.com/flutter/flutter/issues/25979 ? If it isn't quite i don't want to clutter the new issue ... and of course, if this is icebox/long term then hopefully it won't block other efforts. thanks!

**Comment by JFixby** [comment]
[ExampleFlutterActivity](https://github.com/Scarabei/Scarabei/blob/master/scarabei-red-android-flutter/src/com/jfixby/scarabei/red/flutter/plugins/example/ExampleFlutterActivity.java#L31)

[ExamplePlugin](https://github.com/Scarabei/Scarabei/blob/master/scarabei-red-android-flutter/src/com/jfixby/scarabei/red/flutter/plugins/example/ExamplePlugin.java)

**Comment by jmagman** [comment]
@blasten

**Comment by JFixby** [comment]
Nobody asked for my opinion, but honestly, this whole Flutter thing looks like a disaster to me.

**Comment by neiljaywarner** [comment]
Jfixby
Sorry I did not acknowledge you fulfilling my request. I appreciate it.

Perhaps flutter's approach produces some of its success and some of its weaknesses..

**Comment by blasten** [comment]
@JFixby we have started generating Maven artifacts. We will be updating the docs by the end of this month, so you can set the dependency on the embedding directly from Gradle.

**Comment by neiljaywarner** [comment]
When it is something really solid that works on iOS and Android both really well please make a huge deal about it in the conferences and YouTube channel and Twitter feed and all of that... It should be able to get to a point where an ordinary iOS or Android app could use it without caring or even really knowing what it was written in right?

**Comment by dnfield** [comment]
I'm a little late on the scene here, but I arrived via another issue I'm subscribed to.

@JFixby - I'd encourage you to review [Flutter's code of conduct](https://github.com/flutter/flutter/blob/master/CODE_OF_CONDUCT.md).  There are a number of people working very hard on Flutter as a whole and on this specific issue. There are many non-trivial parts of it to solve. You're certainly identifying real issues that everyone wants to see improved, but comments like your most recent one are not very helpful in reaching the goals we all share or respecting the work that we're doing.

**Comment by blasten** [comment]
This is already implemented. http://download.flutter.io/ is the repository.
