### ISSUE TITLE
GoRouter queryParams parser doesn't follow RFC standard 

### ISSUE THREAD

**Issue by parnurzeal** [flutter/flutter#114397]
I've read about the query params usage for # strategy.

I found out that ppl usually get confused what is the right one between the following two:
```
http://www.whatever.com?var=val#anchor
```
or
```
http://www.whatever.com#anchor?var=val
```
[Ref to Stackoverflow question](https://stackoverflow.com/questions/12682952/proper-url-forming-with-a-query-string-and-an-anchor-hashtag)

The first one is being correct but GoRouter implements the later one.

Is there any reason GoRouter doesn't follow the RFC standard? Should it be fixed?

**Comment by exaby73** [comment]
Hello @parnurzeal. Thank you for raising this issue. Labelling for further insights from the team.

**Comment by chunhtai** [comment]
I think this is a limitation on hashURLStrategy. For path strategy, segment is not supported I think

**Comment by parnurzeal** [comment]
I think the main question for me is to know if flutter team think this should be fixed or not. 

My team needs to share the URL pattern to our clients to redirect correctly to our website with query params so we need to know that Flutter will stick to the current one or fix the API to match the RFC standard.

**Comment by chunhtai** [comment]
I don't think we will fix the current behavior for hasURLStrategy. I would suggest using https://api.flutter.dev/flutter/package-flutter_web_plugins_url_strategy/PathUrlStrategy-class.html instead

**Comment by jacobsimionato** [comment]
Hi @chunhtai, I believe this is making it difficult for a Google app to migrate to go_router, seeing as they were using the default # URL strategy with their Flutter web app and so their existing links are in the unsupported format. Would you consider reopening this in order to make the migration path for existing Flutter users easier?
