### ISSUE TITLE
I need to use a positioned widget on stack to make direction to some containers but it was an error and the containers are hiden from UI, any one can help please

### ISSUE THREAD

**Issue by bellaismail** [flutter/flutter#114308]
RenderBox was not laid out: RenderConstrainedBox#1be25 relayoutBoundary=up2 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1979 pos 12: 'hasSize'

**Comment by iapicca** [comment]
@bellaismail 
if you need help with your app better ask on [discord](https://discord.com/invite/N7Yshp4), if you are reporting a bug please provide a code sample

**Comment by darshankawar** [comment]
@bellaismail 
Based on above comment and also looking at issue description, it looks more like a support question rather than a bug report, so please reach out on discord or StackOverflow for solution.

Closing.
