### ISSUE TITLE
sms_autofill: ^2.2.0 when press any key into textbox

### ISSUE THREAD

**Issue by gadgetsteach** [flutter/flutter#114315]
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by iapicca** [comment]
I'm pretty sure issues with [sms_autofill](https://pub.dev/packages/sms_autofill)  should be opened [here](https://github.com/jaumard/sms_autofill/issues)

**Comment by stuartmorgan** [comment]
Issues with third-party packages need to be reported to their authors.
