### ISSUE TITLE
[google_sign_in] iOS PlatformException (PlatformException(missing-config, GoogleService-Info.plist file not found, null, null)) 

### ISSUE THREAD

**Issue by abdelrahman-abied** [flutter/flutter#114304]
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(missing-config, GoogleService-Info.plist file not found and clientId was not provided programmatically., null, null)
#0      StandardMethodCodec.decodeEnvelope
package:flutter/…/services/message_codecs.dart:653
#1      MethodChannel._invokeMethod
package:flutter/…/services/platform_channel.dart:296
<asynchronous suspension>
#2      GoogleSignIn._callMethod
package:google_sign_in/google_sign_in.dart:271
<asynchronous suspension>
#3      GoogleSignIn.signIn.isCanceled
package:google_sign_in/google_sign_in.dart:407
<asynchronous suspension>

**Comment by danagbemava-nc** [comment]
Hi @abdelrahman-abied, what version of `google_sign_in` are you using? 

Please provide the output of `flutter doctor -v`. 

Also, did you follow the setup instructions in the plugin readme or did you do the initialization through `flutterfire configure`?
