### ISSUE TITLE
CheckboxListTile doesn't have an enabled option

### ISSUE THREAD

**Issue by Ivaskuu** [flutter/flutter#11438]
The trick that I am using right now is using a __normal ListTile__  with the __trailing parameter__  as a normal Checkbox.

**Comment by Hixie** [comment]
Can you clarify what you are requesting here? What would the "enabled option" do? How are you achieving what you want with a normal ListTile with the trailing parameter as a normal Checkbox?

**Comment by Pacane** [comment]
This option is kind of already there, if you don't pass a `onChanged` callback to the checkbox.
