### ISSUE TITLE
Recipes auto-roller has not run in the past few months

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#114376]
See https://cs.opensource.google/flutter/recipes/+/main:infra/config/recipes.cfg;bpv=0 hasn't been updated

There's been a few manual rolls, but this should automatically be done. This prevents new changes from getting into Flutter recipes

**Comment by keyonghan** [comment]
https://flutter-review.googlesource.com/c/recipes/+/35305

**Comment by keyonghan** [comment]
The auto roller is back: https://flutter-review.googlesource.com/c/recipes/+/35540, with fix: https://flutter-review.googlesource.com/c/infra/+/35521
