### ISSUE TITLE
CAMERA + GOOGLE_ML_KIT NOT WORKING IN SPECIFIC DEVICES

### ISSUE THREAD

**Issue by Nemasio** [flutter/flutter#114353]
Hello, this issue comes all the way from GOOGLE_ML_KIT package, its not working the face detection, in specific devices.
From what i understand its an issue with the CAMERA package not streaming analyzable images, becouse of the type of images this devices use.
For flutter doctors and more information on the issue, its on the other post:
https://github.com/bharat-biradar/Google-Ml-Kit-plugin/issues/285

**I created a NEW post/thread becouse i think its a CAMERA package issue of FLUTTER, not a GOOGLE_ML_KIT one.**

I have Face detection on my app workingfor 3 days now. And i came up with a **list of devices where the library is NOT working** (Ranked from TOP to BOTTOM in amount of devices that have my app, and where none of the users with this devices could do face detection.)

motorola, moto g(30) 553
motorola, moto g(9) power 547
motorola, moto g(9) play 545
motorola, moto g51 5G 538
motorola, moto g52 401
motorola, moto e(7) plus 396
samsung, SM-A235M 377
samsung, SM-G975F 157
motorola, motorola one hyper 139
motorola, moto g82 5G 124
lge, LM-X540 116
TCL, T671E 111
motorola, Moto G (5S) Plus 102
samsung, SM-A750G 100
samsung, SM-J701M 92
lge, LM-X525 77
motorola, motorola one 72
samsung, SM-G991B 69
samsung, SM-N975F 66
samsung, SM-J700M 62
lge, LM-X210 57
lge, LM-X430 57
lge, LM-X520 55

Still waiting on a fix for face detection, or for the camera library fix, to start detecting faces. 
Anyone has any news about this ?? Any posible solution for THIS devices??

**Comment by huycozy** [comment]
Hi @Nemasio 
>From what i understand its an issue with the CAMERA package not streaming analyzable images, becouse of the type of images this devices use.

Can you be more specific about this? Please provide the information indicated below so that we can verify the issue properly:
- A [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
- Reproduction steps, Expected results, Actual results
- The affected camera plugin version

Thank you!
