### ISSUE TITLE
Theme color error when enables material3

### ISSUE THREAD

**Issue by AzulEterno** [flutter/flutter#114316]
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. ... 
3. ... 

**Expected results:** 
![image](https://user-images.githubusercontent.com/75287037/198871719-e8c77e8a-bd9b-46c0-bb65-780a4d5f1301.png)
When material3 is off. When material3 is enabled it should be like something simliar.
**Actual results:** 
![image](https://user-images.githubusercontent.com/75287037/198871823-9b7d4b2d-7d6c-47ee-8cdc-1d65a7981ce5.png)

It's fixed into this color.

<details>

<summary>Code sample</summary>

          ThemeData newTm = ThemeData(
              useMaterial3: data.enable_material_3, primarySwatch: Colors.amber
              //getMaterialColorFromColor(Color(data.main_theme_color)),
              );

          //print("Current locale: ${_storedLocaleList[data.use_locale_index]}");
          return MaterialApp(
            scaffoldMessengerKey: gRootScaffoldMessengerKey,
            onGenerateTitle: (context) =>
                AppLocalizations.of(context)!.app_title,
            theme: newTm,...);

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by huycozy** [comment]
Hi @AzulEterno 
>When material3 is off. When material3 is enabled it should be like something simliar.

I'm not sure I understand this. Can you be more specific? 

Please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this. Also, please provide the output of `flutter doctor -v` as well.
