### ISSUE TITLE
DatabaseReference.onValue never returns on a high-latency network

### ISSUE THREAD

**Issue by pcomans** [flutter/flutter#11435]
## Steps to Reproduce
This is a problem in firebase_database.
I encountered this problem when I was working with Firebase references while tethered to my phone's hotspot.

We have a function that awaits DatabaseReference#once() and noticed that the app hangs indefinitely when reaching that codepoint. It seems like the Future returned by DatabaseReference#onValue never gets completed.

I can the same query using the Firebase JS SDK and was able to get a result, albeit with significant (~5s) delay.

Is there a timeout in the firebase_database code that would make the Future fail silently?
## Logs
none

## Flutter Doctor
[✓] Flutter (on Mac OS X 10.12.5 16F73, locale en-US, channel unknown)
    • Flutter at /Users/philipp/code/flutter
    • Framework revision d36e2f6191 (5 weeks ago), 2017-06-21 15:09:10 -0700
    • Engine revision b0dee695ec
    • Tools Dart version 1.24.0-dev.6.7

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.0)
    • Android SDK at /Users/philipp/Library/Android/sdk
    • Platform android-26, build-tools 26.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.3.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3.3, Build version 8E3004b
    • ios-deploy 1.9.1
    • CocoaPods version 1.3.0.beta.1

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Gradle version 3.2
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Ultimate Edition (version 2017.2)
    • Flutter plugin version 15.1
    • Dart plugin version 172.3317.48

[✓] Connected devices
    • Android SDK built for x86 • emulator-5554                        • android-x86 • Android 7.0 (API 24) (emulator)
    • iPhone SE                 • B42ADC67-E52E-43A9-A3B1-B5AC81D7E2F9 • ios         • iOS 10.3 (simulator)

**Comment by Hixie** [comment]
cc @collinjackson

**Comment by collinjackson** [comment]
You could use [Future.timeout](https://api.dartlang.org/stable/1.24.2/dart-async/Future/timeout.html) for this. Would that solve your issue?

**Comment by pcomans** [comment]
@collinjackson that would solve the problem if this were an isolated instance but we see cases where **any** call to DatabaseReference.onValue could fail silently and bring the app to a halt. In my opinion, this should be handled by the framework which should should throw an error when the call times out.

I'm happy to discuss this more.
In the meantime, we will wrap invocations that are in the critical path of our app (e.g. loading screens waiting for server results) in `Future.timeout`.

**Comment by collinjackson** [comment]
You may find this [StackOverflow answer](https://stackoverflow.com/a/25367451) helpful.

We're doing the same thing as the iOS and Android Firebase SDKs as far as I know.

**Comment by pcomans** [comment]
@collinjackson Thank you. We will use this in instances where a future timing out constitutes a fatal error.

**Comment by collinjackson** [comment]
I'm closing this issue because I don't think we should add a default timeout to the plugin, but I do appreciate the feedback. Further comments are very welcome.

**Comment by kroikie** [comment]
@pcomans

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/978. Any further collaboration will be done there.
