### ISSUE TITLE
iOS 15 Flutter 2.10.4 got crash because of GrMtlCommandBuffer.mm line 190

### ISSUE THREAD

**Issue by mazoRen** [flutter/flutter#114337]
Steps to Reproduce
100% of the users crashed when the app is in the foreground.
100% of the users crashed on iOS 15.6.1
The crash got reported to the Firebase console.
I haven't found a way to reproduce it.

the firebase console output:
Crashed: io.flutter.1.raster
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x00000008f924b080

```
`Crashed: io.flutter.1.raster
0  libobjc.A.dylib                0x39d0 objc_retain + 16
1  Flutter                        0x2930d8 GrMtlCommandBuffer::commit(bool) + 190 (GrMtlCommandBuffer.mm:190)
2  Flutter                        0x297970 GrMtlGpu::submitCommandBuffer(GrMtlGpu::SyncQueue) + 216 (GrMtlGpu.mm:216)
3  Flutter                        0x1997a0 GrGpu::submitToGpu(bool) + 706 (GrGpu.cpp:706)
4  Flutter                        0x5b380 SkCanvas::onFlush() + 512 (SkCanvas.cpp:512)
5  Flutter                        0x516c78 std::__1::__function::__func<flutter::GPUSurfaceMetal::AcquireFrameFromCAMetalLayer(SkISize const&)::$_1, std::__1::allocator<flutter::GPUSurfaceMetal::AcquireFrameFromCAMetalLayer(SkISize const&)::$_1>, bool (flutter::SurfaceFrame const&, SkCanvas*)>::operator()(flutter::SurfaceFrame const&, SkCanvas*&&) + 72 (scoped_nsobject.h:72)
6  Flutter                        0x48f838 flutter::SurfaceFrame::Submit() + 43 (surface_frame.cc:43)
7  Flutter                        0x3cc584 flutter::Rasterizer::DrawToSurfaceUnsafe(flutter::FrameTimingsRecorder&, flutter::LayerTree&) + 2592 (memory:2592)
8  Flutter                        0x3ccaa0 std::__1::__function::__func<flutter::Rasterizer::DrawToSurface(flutter::FrameTimingsRecorder&, flutter::LayerTree&)::$_8, std::__1::allocator<flutter::Rasterizer::DrawToSurface(flutter::FrameTimingsRecorder&, flutter::LayerTree&)::$_8>, void ()>::operator()() + 497 (rasterizer.cc:497)
9  Flutter                        0x2fd380 fml::SyncSwitch::Execute(fml::SyncSwitch::Handlers const&) const + 501 (mutex:501)
10 Flutter                        0x3cc078 flutter::Rasterizer::DrawToSurface(flutter::FrameTimingsRecorder&, flutter::LayerTree&) + 1831 (functional:1831)
11 Flutter                        0x3cdadc std::__1::__function::__func<flutter::Rasterizer::Draw(std::__1::unique_ptr<flutter::FrameTimingsRecorder, std::__1::default_delete<flutter::FrameTimingsRecorder>>, std::__1::shared_ptr<flutter::Pipeline<flutter::LayerTree>>, std::__1::function<bool (flutter::LayerTree&)>)::$_2, std::__1::allocator<flutter::Rasterizer::Draw(std::__1::unique_ptr<flutter::FrameTimingsRecorder, std::__1::default_delete<flutter::FrameTimingsRecorder>>, std::__1::shared_ptr<flutter::Pipeline<flutter::LayerTree>>, std::__1::function<bool (flutter::LayerTree&)>)::$_2>, void (std::__1::unique_ptr<flutter::LayerTree, std::__1::default_delete<flutter::LayerTree>>)>::operator()(std::__1::unique_ptr<flutter::LayerTree, std::__1::default_delete<flutter::LayerTree>>&&) + 401 (rasterizer.cc:401)
12 Flutter                        0x3ccd68 flutter::Rasterizer::Draw(std::__1::unique_ptr<flutter::FrameTimingsRecorder, std::__1::default_delete<flutter::FrameTimingsRecorder>>, std::__1::shared_ptr<flutter::Pipeline<flutter::LayerTree>>, std::__1::function<bool (flutter::LayerTree&)>) + 2577 (memory:2577)
13 Flutter                        0x3d4e14 std::__1::__function::__func<fml::internal::CopyableLambda<flutter::Shell::OnAnimatorDraw(std::__1::shared_ptr<flutter::Pipeline<flutter::LayerTree>>, std::__1::unique_ptr<flutter::FrameTimingsRecorder, std::__1::default_delete<flutter::FrameTimingsRecorder>>)::$_13>, std::__1::allocator<fml::internal::CopyableLambda<flutter::Shell::OnAnimatorDraw(std::__1::shared_ptr<flutter::Pipeline<flutter::LayerTree>>, std::__1::unique_ptr<flutter::FrameTimingsRecorder, std::__1::default_delete<flutter::FrameTimingsRecorder>>)::$_13>>, void ()>::operator()() + 1831 (functional:1831)
14 Flutter                        0x2fbbf0 fml::MessageLoopImpl::FlushTasks(fml::FlushType) + 124 (ref_ptr.h:124)
15 Flutter                        0x2ff1bc fml::MessageLoopDarwin::OnTimerFire(__CFRunLoopTimer*, fml::MessageLoopDarwin*) + 81 (message_loop_darwin.mm:81)
16 CoreFoundation                 0xae678 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 32
17 CoreFoundation                 0x32654 __CFRunLoopDoTimer + 1064
18 CoreFoundation                 0x2ce00 __CFRunLoopDoTimers + 320
19 CoreFoundation                 0xb4b0 __CFRunLoopRun + 1936
20 CoreFoundation                 0x1ebc8 CFRunLoopRunSpecific + 600
21 Flutter                        0x2ff088 fml::MessageLoopDarwin::Run() + 52 (message_loop_darwin.mm:52)
22 Flutter                        0x2fe848 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, fml::Thread::Thread(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&)::$_0>>(void*) + 96 (message_loop_impl.cc:96)
23 libsystem_pthread.dylib        0x19ac _pthread_start + 148
24 libsystem_pthread.dylib        0xe68 thread_start + 8`
```

flutter doctor
[✓] Flutter (Channel stable, 2.10.4, on macOS 12.6 21G115 darwin-arm, locale
    en-CN)
    • Flutter version 2.10.4 at /Users/who/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (7 months ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/who/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.72.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] VS Code (version 1.70.0)
    • VS Code at /Users/who/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (2 available)
    • iPhone XS (mobile) • 00008020-000415CA3E50003A • ios            • iOS 16.0.2
      20A380
    • Chrome (web)       • chrome                    • web-javascript • Google
      Chrome 106.0.5249.119

[!] HTTP Host Availability
    ✗ HTTP host https://maven.google.com/ is not reachable. Reason: An error occurred
      while checking the HTTP host: Operation timed out

! Doctor found issues in 1 category.

**Comment by mazoRen** [comment]
> @mazoRen Can you provide `flutter doctor -v` on which this crash is occuring ? Also, looking at the error log, it seems to be similar to #96207

I've already edited it

**Comment by darshankawar** [comment]
@mazoRen 
Stable 2.10.4 is an old version. Current is 3.3.6. Can you upgrade to latest and check if the same crash occurs on latest version too ? If so, then we can make this issue actionable, because even if this is a genuine crash on 2.10.4, the potential fix would be made taking the latest version of stable.
