### ISSUE TITLE
[google_sign_in] PlatformException(sign_in_failed, w.b: 10: , null, null)

### ISSUE THREAD

**Issue by faiqkhan480** [flutter/flutter#114491]
![image](https://user-images.githubusercontent.com/50393046/199449199-2c3aa150-7fcd-4b5e-8341-f7928667b153.png)

Google Sign In work fine in debug but not work on release mode.

**Comment by wwalkingg** [comment]
Maybe Sha1 key is not in your release app

**Comment by faiqkhan480** [comment]
Sha 1 key is Added, it is working on debug.

**Comment by exaby73** [comment]
Hello @faiqkhan480. Are you using different signing key for release builds? For example: Have you configured a different jks file in your `app/build.gradle` file?

**Comment by faiqkhan480** [comment]
I create the release Key, & I use the release signing config in app/build.gradle.

![image](https://user-images.githubusercontent.com/50393046/199482813-1a77d567-d354-4e35-a8e3-c0987725e7c1.png)

**Comment by exaby73** [comment]
What I believe is happening here, is that in debug mode, Flutter is using the default keystore for which you have probably added the SHA-1 in Firebase. Can you confirm if you have added the SHA-1 for your release key as well?

**Comment by faiqkhan480** [comment]
@exaby73 Where do I get the release SHA-1 key..? I think I don't use SHA-1 when I create a released config.

**Comment by exaby73** [comment]
You can follow [this documentation](https://developers.google.com/android/guides/client-auth) to add the release SHA-1 key.

**Comment by faiqkhan480** [comment]
Thnks...

**Comment by exaby73** [comment]
Glad I could help. I have closed the issue as solved. If you disagree with my decision, please comment and I can reopen the issue

**Comment by faiqkhan480** [comment]
Ok...
