### ISSUE TITLE
I have used url_launcher: ^6.1.6 to open url in web browser in readers app but ios has rejected app stated this reasons in the mail 

### ISSUE THREAD

**Issue by jigar541patel** [flutter/flutter#114407]
## Steps to Reproduce

Your "reader" app uses the External Link Account entitlement to link out for account creation and management but does not meet all requirements for using this entitlement.

Specifically, we found that your app does not meet the following requirement(s):

Your app does not use the External Link Account API to populate the modal sheet before every instance of linking out for account creation and management.
 [Url for External Link Account](https://developer.apple.com/documentation/storekit/external_link_account)

Configure the SKExternalLinkAccount property list key.
Use the ExternalLinkAccount type’s canOpen property and open() method.
**The link shows there is 2 things to implement first one we have done and second one is Use the ExternalLinkAccount type’s canOpen property and open() method I am not able to find this same thing in flutter in url launcher library can anyone help me how to implement canOpen and open() like iOS in flutter. I am sharing code of flutter were we open url **

**Expected results:** how can I get approval from iOS support as they found library not using canopen() and open() in iOS code as they found code not complying with there requirement

**Actual results:** I want to know is their way to implement the ExternalLinkAccount type’s canOpen property and open() method in flutter as asked by Apple support to get approval for app.(note: code is working fine able to open url in iOS in browser)

<details>
<summary>

```
_launchURL() async `{`
    const url = 'https://www.bonusround.ca/signup';
    if (await canLaunchUrl(Uri.parse(url))) {
      Navigator.pop(context);
      await launchUrl(Uri.parse(url), mode: LaunchMode.externalApplication);
    } else {
      throw 'Could not launch $url';
    }
  }

```  
  </summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by stuartmorgan** [comment]
> Use the ExternalLinkAccount type’s canOpen property and open() method I am not able to find this same thing in flutter in url launcher library

This is [a separate API](https://developer.apple.com/documentation/storekit/externallinkaccount) unrelated to the functionality that `url_launcher` provides access to, so it's not part of this plugin.

> I want to know is their way to implement the ExternalLinkAccount type’s canOpen property and open() method in flutter

You would need to either implement it [directly in your application](https://docs.flutter.dev/development/platform-integration/platform-channels), or find/write a plugin that wraps that API.

Closing as this is not in scope for `url_launcher`.
