### ISSUE TITLE
[macOS] Code signature invalid

### ISSUE THREAD

**Issue by SebAubin** [flutter/flutter#114425]
Hi, we use a third party library in our project (dylib) and since I made an update to macOS Ventura, I can't use it. It keeps telling me this error:

```
'/Users/user/Documents/github/project_name/build/macos/Build/Products/Debug/OurApp.app/Contents/Frameworks/libCrypto.dylib' (code signature invalid in <E4C1AF42-616D-372B-BF20-C37B4E8DDFBA> 
```

I'm trying to load a dylib with dart:ffi like this:
```
DynamicLibrary.open("libCrypto.dylib");
```

## Steps to Reproduce

1. Have a third party library included in your project.
2. Build normally in Debug 

</details>

<details>
  <summary>Logs</summary>

```
Analyzing macos...
No issues found! (ran in 0.7s)
```

```
[✓] Flutter (Channel stable, 3.3.6, on macOS 13.0 22A380 darwin-arm (Rosetta), locale en-CA)
    • Flutter version 3.3.6 on channel stable at /Users/saubin/Documents/github/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6928314d50 (7 days ago), 2022-10-25 16:34:41 -0400
    • Engine revision 3ad69d7be3
    • Dart version 2.18.2
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/saubin/Library/Android/sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • Java binary at: /Users/saubin/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/213.7172.25.2113.9123335/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Users/saubin/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/212.5712.43.2112.8512546/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] Android Studio (version 2021.3)
    • Android Studio at /Users/saubin/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/213.7172.25.2113.9123335/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.72.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (4 available)
    • SM G781W (mobile)             • RFCN90XEYXM               • android-arm64  • Android 12 (API 31)
    • iPhone Workspace Seb (mobile) • 00008101-0019542C02A1001E • ios            • iOS 15.6.1 19G82
    • macOS (desktop)               • macos                     • darwin-arm64   • macOS 13.0 22A380 darwin-arm (Rosetta)
    • Chrome (web)                  • chrome                    • web-javascript • Google Chrome 107.0.5304.87

[✓] HTTP Host Availability
    • All required HTTP hosts are available
```

</details>

**Comment by huycozy** [comment]
Hi @SebAubin 
Can you share the output of `flutter run -v`? If the log is too long, please save it into a file and attach it here. 
Also, is that possible to provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)? Thank you!

**Comment by huycozy** [comment]
>[ +240 ms] [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument(s): Failed to load dynamic libra ry
 
>'libDevolutionsCrypto.dylib': dlopen(libDevolutionsCrypto.dylib, 0x0001): tried: 'libDevolutionsCrypto.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibDevolutionsCrypto.dylib' (no such file), 

Hi @SebAubin, thanks for providing the output log. As I see, it seems that the library file does not exist as the error message is given. Please fix it and retry.

**Comment by SebAubin** [comment]
Hi, yes I did see that but I think that when you include a dylib into an Xcode project it searches for multiple location for its cache and stuff. If you look at the line 1099 you'll see "(code signature invalid in <8E69F228-9B9B-3B8D-95C5-C88A0F1E773B>" and I think that is my problem. Nothing has changed in my project in terms of path for libs. For me, it seems to be the new version of Xcode or something like that causes the problem.

**Comment by huycozy** [comment]
@SebAubin Can you try adding the `dylib` into a new XCode project and check if the issue still persists? Also, what is the version of Xcode that was working well before?

**Comment by SebAubin** [comment]
Hi, it seems to work fine in another project. Weird, thanks for your help.

**Comment by huycozy** [comment]
Given your last message, I feel safe to close this issue, if you disagree please write in the comments and I will reopen it.
Thank you!
