### ISSUE TITLE
Observatory crashes when installing to an Android device using ADB port forwarding

### ISSUE THREAD

**Issue by DaveShuckerow** [flutter/flutter#11441]
## Steps to Reproduce

I've set up [ADB port-forwarding](http://go/adb-port-forward-guide) and tried to run a Flutter app this way, building it on a workstation and forwarding ADB to a Pixel plugged into a laptop.

Other ADB commands work correctly (I can run adb devices on the workstation and detect the Pixel as connected). 

The app starts, and locally to the laptop, I can run `flutter logs` to see the actual logs.

The app starts, but the run command fails after this, which means that hot reload will not work in this setup.

## Logs
```console
Launching lib/main.dart on Pixel in debug mode...
Installing leafy.apk...  4.7s
Unhandled exception:
Exception: Error connecting to observatory: WebSocketChannelException: WebSocketChannelException: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 50096
#0      throwToolExit (package:flutter_tools/src/base/common.dart:29)
#1      VM.invokeRpcRaw (package:flutter_tools/src/vmservice.dart:733)
<asynchronous suspension>
#2      VM._fetchDirect (package:flutter_tools/src/vmservice.dart:563)
<asynchronous suspension>
#3      ServiceObject.reload (package:flutter_tools/src/vmservice.dart:411)
<asynchronous suspension>
#4      VMService.getVM (package:flutter_tools/src/vmservice.dart:239)
#5      FlutterDevice.getVMs (package:flutter_tools/src/resident_runner.dart:97)
<asynchronous suspension>
#6      ResidentRunner.connectToServiceProtocol (package:flutter_tools/src/resident_runner.dart:559)
<asynchronous suspension>
#7      ColdRunner.run (package:flutter_tools/src/run_cold.dart:63)
<asynchronous suspension>
#8      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:339)
<asynchronous suspension>
#9      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:220)
<asynchronous suspension>
#10     RunCommand.verifyThenRunCommand (package:flutter_tools/src/commands/run.dart:227)
<asynchronous suspension>
#11     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:162)
<asynchronous suspension>
#12     CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#13     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:277)
<asynchronous suspension>
#14     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#15     new Future.sync (dart:async/future.dart:222)
#16     CommandRunner.run (package:args/command_runner.dart:109)
#17     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:161)
#18     run.<anonymous closure> (package:flutter_tools/executable.dart:142)
<asynchronous suspension>
#19     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#20     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#21     _rootRun (dart:async/zone.dart:1120)
#22     _CustomZone.run (dart:async/zone.dart:1001)
#23     runZoned (dart:async/zone.dart:1467)
#24     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#25     run (package:flutter_tools/executable.dart:114)
<asynchronous suspension>
#26     main (package:flutter_tools/executable.dart:67)
<asynchronous suspension>
#27     main.<anonymous closure> (file:///build/work/7803d26f580997e096b222ffceb40a3e/google3/blaze-out/host/bin/mobile/flutter/tools/snapshot.build/mobile/flutter/tools/flutter_tools.dart:21)
#28     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#29     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#30     _rootRun (dart:async/zone.dart:1120)
#31     _CustomZone.run (dart:async/zone.dart:1001)
#32     runZoned (dart:async/zone.dart:1467)
#33     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#34     main (file:///build/work/7803d26f580997e096b222ffceb40a3e/google3/blaze-out/host/bin/mobile/flutter/tools/snapshot.build/mobile/flutter/tools/flutter_tools.dart:20)
<asynchronous suspension>
#35     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#36     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

## Flutter Doctor

g3 tooling

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by eseidelGoogle** [comment]
@tvolkert is probably the best expert here.

**Comment by Hixie** [comment]
Can you give us a lot more detail about your setup? How are you forwarding ports, for example? We also use port forwarding internally so it may be conflicting.

**Comment by Hixie** [comment]
(https://github.com/flutter/flutter/issues/11444 has a similar error message in a very different environment.)

**Comment by seleznova** [comment]
I use Ubuntu 16.04 and running the app in IntelliJ IDEA have a very similar problem:

```
Launching lib/main.dart on TegraNote P1640 in debug mode...
Initializing gradle...
Resolving dependencies...
Running 'gradlew assembleDebug'...
Built build/app/outputs/apk/app-debug.apk (21.2MB).
Unhandled exception:
Exception: Error connecting to observatory: WebSocketChannelException: WebSocketChannelException: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:8104/ws
#0      throwToolExit (package:flutter_tools/src/base/common.dart:29)
#1      VM.invokeRpcRaw (package:flutter_tools/src/vmservice.dart:738)
<asynchronous suspension>
#2      VM._fetchDirect (package:flutter_tools/src/vmservice.dart:566)
<asynchronous suspension>
#3      ServiceObject.reload (package:flutter_tools/src/vmservice.dart:414)
<asynchronous suspension>
#4      VMService.getVM (package:flutter_tools/src/vmservice.dart:243)
#5      FlutterDevice.getVMs (package:flutter_tools/src/resident_runner.dart:81)
<asynchronous suspension>
#6      ResidentRunner.connectToServiceProtocol (package:flutter_tools/src/resident_runner.dart:543)
<asynchronous suspension>
#7      HotRunner.attach (package:flutter_tools/src/run_hot.dart:106)
<asynchronous suspension>
#8      HotRunner.run (package:flutter_tools/src/run_hot.dart:206)
<asynchronous suspension>
#9      AppDomain.startApp.<anonymous closure> (package:flutter_tools/src/commands/daemon.dart:413)
<asynchronous suspension>
#10     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#11     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#12     _rootRun (dart:async/zone.dart:1120)
#13     _CustomZone.run (dart:async/zone.dart:1001)
#14     runZoned (dart:async/zone.dart:1467)
#15     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#16     AppInstance._runInZone (package:flutter_tools/src/commands/daemon.dart:769)
#17     AppDomain.startApp (package:flutter_tools/src/commands/daemon.dart:411)
<asynchronous suspension>
#18     RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:260)
<asynchronous suspension>
#19     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:220)
<asynchronous suspension>
#20     RunCommand.verifyThenRunCommand (package:flutter_tools/src/commands/run.dart:227)
<asynchronous suspension>
#21     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:162)
<asynchronous suspension>
#22     CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#23     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:277)
<asynchronous suspension>
#24     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#25     new Future.sync (dart:async/future.dart:222)
#26     CommandRunner.run (package:args/command_runner.dart:109)
#27     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:161)
#28     run.<anonymous closure> (package:flutter_tools/executable.dart:142)
<asynchronous suspension>
#29     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#30     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#31     _rootRun (dart:async/zone.dart:1120)
#32     _CustomZone.run (dart:async/zone.dart:1001)
#33     runZoned (dart:async/zone.dart:1467)
#34     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#35     run (package:flutter_tools/executable.dart:114)
<asynchronous suspension>
#36     main (package:flutter_tools/executable.dart:67)
<asynchronous suspension>
#37     main (file:///home/mary/flutter/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
#38     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#39     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```
Running flutter doctor I see:
```
[✓] Flutter (on Linux, locale en_GB.UTF-8, channel alpha)
    • Flutter at /home/mary/flutter/flutter
    • Framework revision bbcfb8d51a (4 days ago), 2017-08-01 14:50:29 -0700
    • Engine revision f2af347363
    • Tools Dart version 1.25.0-dev.7.0

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.1)
    • Android SDK at /home/mary/Android/Sdk
    • Platform android-26, build-tools 26.0.1
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] Android Studio (version 2.3)
    • Android Studio at /opt/android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.2)
    • Flutter plugin version 16.0
    • Dart plugin version 172.3544.34

[✓] Connected devices
    • TegraNote P1640 • 0521014104468001B795 • android-arm • Android 5.1 (API 22)

```
Also, in Android Studio my apps are running smoothly. 
How to solve this problem?
Thanks in advance for help.

**Comment by eseidelGoogle** [comment]
`flutter run -v` will may show you more information.

**Comment by DaveShuckerow** [comment]
I have an update: The Flutter tooling is attempting to use a different port than ADB to talk to observatory.  I tried forwarding the port Flutter used in the error log, but Flutter used a different port on the next run.

I'll sync with Hixie about this.

**Comment by DaveShuckerow** [comment]
Root cause explanation:
The Flutter tool uses a separate port to talk to a Flutter app from the observatory.  This can be specified while running a Flutter app with the flag `--observatory-port`.  This port needs to be forwarded along with the adb port (5037 by default).  

I adjusted my port forwarding script to forward port 48314 as well as port 5037, and then when running the app, I passed the flag `--observatory-port=48314`.  This corrected the problem.

**Comment by KarimMohamed2005** [comment]
Please Give Us More Info About The Error

**Comment by nghieppv** [comment]
Try use IPv4 (192.168.x.x) address instead for localhost or 127.0.0.1

**Comment by yasencoder** [comment]
> ## Steps to Reproduce
> I've set up [ADB port-forwarding](http://go/adb-port-forward-guide) and tried to run a Flutter app this way, building it on a workstation and forwarding ADB to a Pixel plugged into a laptop.
> 
> Other ADB commands work correctly (I can run adb devices on the workstation and detect the Pixel as connected).
> 
> The app starts, and locally to the laptop, I can run `flutter logs` to see the actual logs.
> 
> The app starts, but the run command fails after this, which means that hot reload will not work in this setup.
> 
> ## Logs
> ```
> Launching lib/main.dart on Pixel in debug mode...
> Installing leafy.apk...  4.7s
> Unhandled exception:
> Exception: Error connecting to observatory: WebSocketChannelException: WebSocketChannelException: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 50096
> #0      throwToolExit (package:flutter_tools/src/base/common.dart:29)
> #1      VM.invokeRpcRaw (package:flutter_tools/src/vmservice.dart:733)
> <asynchronous suspension>
> #2      VM._fetchDirect (package:flutter_tools/src/vmservice.dart:563)
> <asynchronous suspension>
> #3      ServiceObject.reload (package:flutter_tools/src/vmservice.dart:411)
> <asynchronous suspension>
> #4      VMService.getVM (package:flutter_tools/src/vmservice.dart:239)
> #5      FlutterDevice.getVMs (package:flutter_tools/src/resident_runner.dart:97)
> <asynchronous suspension>
> #6      ResidentRunner.connectToServiceProtocol (package:flutter_tools/src/resident_runner.dart:559)
> <asynchronous suspension>
> #7      ColdRunner.run (package:flutter_tools/src/run_cold.dart:63)
> <asynchronous suspension>
> #8      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:339)
> <asynchronous suspension>
> #9      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:220)
> <asynchronous suspension>
> #10     RunCommand.verifyThenRunCommand (package:flutter_tools/src/commands/run.dart:227)
> <asynchronous suspension>
> #11     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:162)
> <asynchronous suspension>
> #12     CommandRunner.runCommand (package:args/command_runner.dart:194)
> <asynchronous suspension>
> #13     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:277)
> <asynchronous suspension>
> #14     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
> #15     new Future.sync (dart:async/future.dart:222)
> #16     CommandRunner.run (package:args/command_runner.dart:109)
> #17     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:161)
> #18     run.<anonymous closure> (package:flutter_tools/executable.dart:142)
> <asynchronous suspension>
> #19     AppContext._run (package:flutter_tools/src/base/context.dart:76)
> <asynchronous suspension>
> #20     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
> #21     _rootRun (dart:async/zone.dart:1120)
> #22     _CustomZone.run (dart:async/zone.dart:1001)
> #23     runZoned (dart:async/zone.dart:1467)
> #24     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
> #25     run (package:flutter_tools/executable.dart:114)
> <asynchronous suspension>
> #26     main (package:flutter_tools/executable.dart:67)
> <asynchronous suspension>
> #27     main.<anonymous closure> (file:///build/work/7803d26f580997e096b222ffceb40a3e/google3/blaze-out/host/bin/mobile/flutter/tools/snapshot.build/mobile/flutter/tools/flutter_tools.dart:21)
> #28     AppContext._run (package:flutter_tools/src/base/context.dart:76)
> <asynchronous suspension>
> #29     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
> #30     _rootRun (dart:async/zone.dart:1120)
> #31     _CustomZone.run (dart:async/zone.dart:1001)
> #32     runZoned (dart:async/zone.dart:1467)
> #33     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
> #34     main (file:///build/work/7803d26f580997e096b222ffceb40a3e/google3/blaze-out/host/bin/mobile/flutter/tools/snapshot.build/mobile/flutter/tools/flutter_tools.dart:20)
> <asynchronous suspension>
> #35     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
> #36     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
> ```
> 
> ## Flutter Doctor
> g3 tooling
> 
> > For more information about diagnosing and reporting Flutter bugs, please see https://flutter.io/bug-reports/.

Hello, I look forward to your help. I also encountered this problem. How did you solve it?
