### ISSUE TITLE
websocket not upgraded error

### ISSUE THREAD

**Issue by paras7735** [flutter/flutter#11444]
I am new to flutter and followed the steps for the sample app on an emulator.While the app installs correctly flutter run stops and hot reload does not work and I am not able to see any console logs as well.I am using a university network which is behind a proxy.

## Logs
```terminal
flutter run
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Running 'gradle assembleDebug'...                    13.0s
Built build\app/outputs/apk/app-debug.apk (21.7MB).
Installing build\app/outputs/apk/app.apk...           2.1s
Unhandled exception:
Exception: Error connecting to observatory: WebSocketChannelException: WebSocketChannelException: WebSocketException: Connection to 'http://127.0.0.1:8124/ws#' was not upgraded to websocket
#0      throwToolExit (package:flutter_tools/src/base/common.dart:29)
#1      VM.invokeRpcRaw (package:flutter_tools/src/vmservice.dart:670)
<asynchronous suspension>
#2      VM._fetchDirect (package:flutter_tools/src/vmservice.dart:500)
<asynchronous suspension>
#3      ServiceObject.reload (package:flutter_tools/src/vmservice.dart:348)
<asynchronous suspension>
#4      VMService.getVM (package:flutter_tools/src/vmservice.dart:176)
#5      FlutterDevice.getVMs (package:flutter_tools/src/resident_runner.dart:89)
<asynchronous suspension>
#6      ResidentRunner.connectToServiceProtocol (package:flutter_tools/src/resident_runner.dart:537)
<asynchronous suspension>
#7      HotRunner.attach (package:flutter_tools/src/run_hot.dart:93)
<asynchronous suspension>
#8      HotRunner.run (package:flutter_tools/src/run_hot.dart:193)
<asynchronous suspension>
#9      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:329)
<asynchronous suspension>
#10     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:210)
<asynchronous suspension>
#11     RunCommand.verifyThenRunCommand (package:flutter_tools/src/commands/run.dart:217)
<asynchronous suspension>
#12     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:156)
<asynchronous suspension>
#13     CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:277)
<asynchronous suspension>
#15     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#16     new Future.sync (dart:async/future.dart:206)
#17     CommandRunner.run (package:args/command_runner.dart:109)
#18     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:161)
#19     run.<anonymous closure> (package:flutter_tools/executable.dart:142)
<asynchronous suspension>
#20     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#21     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#22     _rootRun (dart:async/zone.dart:1120)
#23     _CustomZone.run (dart:async/zone.dart:1001)
#24     runZoned (dart:async/zone.dart:1467)
#25     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#26     run (package:flutter_tools/executable.dart:114)
<asynchronous suspension>
#27     main (package:flutter_tools/executable.dart:67)
<asynchronous suspension>
#28     main (file:///E:/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
#29     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#30     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

```terminal
 flutter analyze
Analyzing E:\myapp2...
No issues found!
Ran in 6.9s

## Flutter Doctor
 flutter doctor
[√] Flutter (on Microsoft Windows [Version 10.0.15063], locale en-US, channel alpha)
    • Flutter at E:\flutter
    • Framework revision d36e2f6191 (5 weeks ago), 2017-06-21 15:09:10 -0700
    • Engine revision b0dee695ec
    • Tools Dart version 1.24.0-dev.6.7

[√] Android toolchain - develop for Android devices (Android SDK 26.0.0)
    • Android SDK at D:\Android\sdk
    • Platform android-26, build-tools 26.0.0
    • ANDROID_HOME = D:\Android\sdk
    • Java binary at: D:\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[√] Android Studio (version 2.3)
    • Android Studio at D:\Android\Android Studio
    • Gradle version 3.2
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[√] IntelliJ IDEA Ultimate Edition (version 2017.2)
    • Flutter plugin version 15.1
    • Dart plugin version 172.3317.48

[√] Connected devices
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 7.1.1 (API 25) (emulator)
```

**Comment by eseidelGoogle** [comment]
It might be some sort of firewall running on your computer which is preventing the flutter tool (also running on your computer) from connecting to the emulator at 127.0.0.1 (which is your computer).

I've never seen that particular exception before unfortunately.

**Comment by Hixie** [comment]
Do you know what firewall software you have running?

**Comment by JDoe34** [comment]
Hello, I am facing the same issue. OS Windows 7, Windows firewall, behind corporate proxy. Flutter doctor shows no issues. Any further data that would help you narrowing down potential root causes ?

**Comment by igitur** [comment]
Same problem here. I've set up my proxy server in a few places, but I think I have to add `127.0.0.1` as a proxy exclusion. But which proxy settings are used? Gradle's in `gradle.properties`?

**Comment by shanewignall** [comment]
I was able to resolve this issue by adding a Windows environment variable called **NO_PROXY** with a value of **127.0.0.1,localhost**.

I had to restart Visual Studio Code after creating this environment variable for the changes to take effect.

**Comment by Hixie** [comment]
Can you get a TCP trace of the failed connection? It would be good to compare a successful connection to a failed connection.

**Comment by Murtuzakabul** [comment]
Let me collect the log using Wireshark, I'll post it here very soon

**Comment by Murtuzakabul** [comment]
Here is the wireshark log of the app

**Comment by Murtuzakabul** [comment]
[wsharkcapture.zip](https://github.com/flutter/flutter/files/1994261/wsharkcapture.zip)

**Comment by Murtuzakabul** [comment]
I did some research and summarized two requests

Working one

GET /client HTTP/1.1
Host: 192.168.1.37
Connection: Upgrade
Pragma: no-cache
Cache-Control: no-cache
Upgrade: websocket
Origin: chrome-extension://pfdhoblngboilpfeibdedpjgfnlcodoo
Sec-WebSocket-Version: 13
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.170 Safari/537.36
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.9
Sec-WebSocket-Key: ouTy2cAv7Du/LfDP0zFSlQ==
Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits

HTTP/1.1 101 Switching Protocols
Connection: Upgrade
Date: Fri, 11 May 2018 14:17:16 GMT
Server: Kestrel
Upgrade: websocket
Sec-WebSocket-Accept: V8vCh+hwhn4M4D+IX4JZuWkcnNc=

Non working one: 

GET /client HTTP/1.1
user-agent: Dart/2.0 (dart:io)
connection: Upgrade
cache-control: no-cache
accept-encoding: gzip
content-length: 0
sec-websocket-version: 13
host: 192.168.1.37
sec-websocket-extensions: permessage-deflate; client_max_window_bits
sec-websocket-key: 0Db/dlrGHU/gQam9r80Q6g==
upgrade: websocket

HTTP/1.1 200 OK
Connection: close
Date: Fri, 11 May 2018 14:57:38 GMT
Server: Kestrel
Content-Length: 0


The only difference I could make out is when dart lib requests, all the header starts with small case which probably causes the web server to ignore them and process it as a regular web request.

e.g. Connection: Upgrade vs connection: Upgrade

Is there any way to change the header emitted by dart lib and test this hypothesis.

**Comment by eseidelGoogle** [comment]
cc @zanderso

**Comment by Murtuzakabul** [comment]
There is yet another issue reported 
https://github.com/dart-lang/sdk/issues/25120

It states that this behavior is by design. However, It would be great to have control over emitted headers.

**Comment by zoechi** [comment]
@DanTup do you think this is a dup of #19056 ?

**Comment by DanTup** [comment]
They both look like something is breaking the connection before it gets converted to a websocket; but since there are so many reasons this might happen and the errors are different, it's hard to say.

Some thoughts about things that could go wrong:

1. A firewall/proxy not supporting web sockets properly - possibly can be confirmed using something like https://websocketstest.com/ (as far as I can tell, that one tests over HTTP which is probably best, since a bad proxy/firewall is probably more likely to be inspecting/messing with unencrypted connections).

2. Proxy is proxying traffic to localhost - this sounds a bit crazy, but a user above reported bypassing proxy for localhost fixed the issue. If we're listening on localhost and the proxy is off-machine, I'm not sure it could possibly connect back. A possible way to test this is to just create a Hello World `.dart` script and put a breakpoint in it and debug - we use the same kinda of web socket connection to localhost to debug against the standard VM (this could eliminate any flutter-specific issue).

There's also a possible complication of port-forwarding to the device. I'm not sure how it works with the Emulator, but I believe for a real device a port is forwarded from localhost to the device - if this is the same for the emulator, there's the possibility that a proxy/firewall could be getting in there too. Might be more complicated to confirm this though, so better to try the things that are easier to test first.

**Comment by Ali-Azmoud** [comment]
I have the same problem here. I can't connect to my localhost websocket.
when I open my localhost website from browser, websocket connection is OK, but flutter always return this message with a bunch of exceptions to me

`I/flutter (18613): null
E/flutter (18613): [ERROR:flutter/shell/common/shell.cc(184)] Dart Error: Unhandled exception:
E/flutter (18613): WebSocketChannelException: WebSocketChannelException: WebSocketException: Connection to 'http://192.168.191.1:3335#' was not upgraded to websocket
E/flutter (18613): #0      new IOWebSocketChannel._withoutSocket.<anonymous closure> (package:web_socket_channel/io.dart:83:24)
E/flutter (18613): #1      _invokeErrorHandler (dart:async/async_error.dart:13:29)
E/flutter (18613): #2      _HandleErrorStream._handleError (dart:async/stream_pipe.dart:286:9)
E/flutter (18613): #3      _ForwardingStreamSubscription._handleError (dart:async/stream_pipe.dart:168:13)
E/flutter (18613): #4      _RootZone.runBinaryGuarded (dart:async/zone.dart:1326:10)
E/flutter (18613): #5      _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:355:15)
E/flutter (18613): #6      _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:373:16)
E/flutter (18613): #7      _BufferingStreamSubscription._addError (dart:async/stream_impl.dart:272:7)
E/flutter (18613): #8      _SyncStreamController._sendError (dart:async/stream_controller.dart:767:19)
E/flutter (18613): #9      _StreamController._addError (dart:async/stream_controller.dart:647:7)
E/flutter (18613): #10     _RootZone.runBinaryGuarded (dart:async/zone.dart:1326:10)
E/flutter (18613): #11     _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:355:15)
E/flutter (18613): #12     _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:373:16)
E/flutter (18613): #13     _BufferingStreamSubscription._addError (dart:async/stream_impl.dart:272:7)
E/flutter (18613): #14     _SyncStreamController._sendError (dart:async/stream_controller.dart:767:19)
E/flutter (18613): #15     _StreamController._addError (dart:async/stream_controller.dart:647:7)
E/flutter (18613): #16     new Stream.fromFuture.<anonymous closure> (dart:async/stream.dart:117:18)
E/flutter (18613): #17     _RootZone.runBinary (dart:async/zone.dart:1384:54)
E/flutter (18613): #18     _FutureListener.handleError (dart:async/future_impl.dart:143:20)
E/flutter (18613): #19     Future._propagateToListeners.handleError (dart:async/future_impl.dart:654:47)
E/flutter (18613): #20     Future._propagateToListeners (dart:async/future_impl.dart:675:24)
E/flutter (18613): #21     Future._completeError (dart:async/future_impl.dart:494:5)
E/flutter (18613): #22     Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:542:7)
E/flutter (18613): #23     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter (18613): #24     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
`

I also tried these ips: 192.168.191.1 ( which is my pc ip ), 10.0.2.2 to access my pc localhost
I set a `NO_PROXY` env var to windows, restarted my pc, restart android studio.
I turned of any software and firewall which may block the connection.

There's one thing left, hit my head as hard as possible to my room's wall !!!!

can anybody help me

**Comment by zoechi** [comment]
@Ali-Azmoud 

> when I open my localhost website from browser

how exactly do you open it? With the browser on the device/emulator? What URL are you using exactly?

**Comment by Ali-Azmoud** [comment]
in browser

in NodeJS app, I use the following configurations

`// .env file
ip: 127.0.0.1, ( also tried 0.0.0.0 to accept other than localhost requests )
port : 3335
`

And in the browser url address:

`http://127.0.0.1:3335` or `http://localhost:3335` which both works fine and Websocket request upgrades successfully

from my Emulator chrome
`http://127.0.01:3335 // if I forward my adb port it works fine.`
`http://10.0.2.2:3335` works fine
`http://192.168.191.1:3335` works fine

but none of them works in flutter. But I don't know how it can connect to `ws://echo.websocket.org` without any problem !

I tried my app with all possible ways in 2 pc, both same result.

**Comment by zoechi** [comment]
> I don't know how it can connect to ws://echo.websocket.org

In your previous comment you wrote

>  it works when I connect to ws://echo.websocket.org

which seems to say the opposite.

> but none of them works in flutter.

I'd try in a plain Dart project without Flutter to see if there is some compatibility issue between Dart websocket client and your Node server.

**Comment by Ali-Azmoud** [comment]
@zoechi 

Sorry for that, my english is not good enough.

My flutter app which is a clone of `Flutter Documentations  websocket example` works well with url `ws://echo.websocket.org` but it doesn't work with my localhost. ( summary of my two comments )

**Comment by zoechi** [comment]
@Ali-Azmoud thanks for clarification. I'd try to connect with a plain Dart project to reduce the possible causes of the issue.

**Comment by DanTup** [comment]
Here's a simple Dart script that connects to echo.websocket.org and then also hosts a local web socket and tries to connect (both using `localhost`, which may resolve to `127.0.0.1` or `::1`, and `127.0.0.1` directly). If you save it in a `.dart` file then run it with `dart <filename.dart>` it may help understand what's failing:

```dart
import 'dart:io';

var port = 3456;

main() async {
  print('HTTP_PROXY: ${Platform.environment['HTTP_PROXY']}');
  print('NO_PROXY: ${Platform.environment['NO_PROXY']}');
  print('');

  await test('ws://echo.websocket.org');
  await test('wss://echo.websocket.org');

  await Future.forEach(['localhost', '127.0.0.1'], (String address) async {
    final server = await startLocalServer(address, ++port);
    await test('ws://$address:$port');
    await server.close();
  });

  print('Completed!');
}

Future<HttpServer> startLocalServer(String address, int port) async {
  final server = await HttpServer.bind(address, port);
  print('Server listening at ${server.address.address}:$port');
  server.transform(WebSocketTransformer()).listen((WebSocket client) {
    client.listen((data) => client.add(data));
  });
  return server;
}

Future<void> test(String url) async {
  print('Connecting to $url');
  final ws = await WebSocket.connect(url);
  send(ws, 'TEST STRING');
  await receive(ws, 'TEST STRING');
  await ws.close();
  print('');
}

void send(WebSocket ws, String s) {
  print('SEND: $s');
  ws.add(s);
}

Future<void> receive(WebSocket ws, String s) async {
  final msg = await ws.first.timeout(const Duration(seconds: 1));
  print('RCV: $msg');
  if (msg != s) {
    throw 'Expected "$s" but got "$msg"';
  }
}
```

The output looks something like this:

```
HTTP_PROXY: null
NO_PROXY: null

Connecting to ws://echo.websocket.org
SEND: TEST STRING
RCV: TEST STRING

Connecting to wss://echo.websocket.org
SEND: TEST STRING
RCV: TEST STRING

Server listening at ::1:3457
Connecting to ws://localhost:3457
SEND: TEST STRING
RCV: TEST STRING

Server listening at 127.0.0.1:3458
Connecting to ws://127.0.0.1:3458
SEND: TEST STRING
RCV: TEST STRING

Completed!
```

**Comment by csells** [comment]
@DanTup I'm having this same issue on my machine. Your code works, i.e. when I'm connecting a Dart WebSocket client to a Dart WebSocket server, it works (as does connecting to echo.websocket.org). However, I have an existing WebSocket server running on localhost written in another language (.NET) that I can connect to via my browser but NOT with the Dart WebSocket client. Any ideas about how to use the Dart WebSocket client to a non-Dart WebSocket server running on localhost?

**Comment by DanTup** [comment]
@csells Interesting - are you able to share the .NET code that runs your socket server? (and which OS/runtime you're running it with) and I can see if I can repro and see what's going on.

**Comment by csells** [comment]
Sure. It's the Fibs.Net proxy server on GitHub running on Mac. There's a Java FIBS server clone included for testing without spamming fibs.com. Let me know if the readme is incomplete.

On Mar 2, 2019 1:02 AM, Danny Tuppeny <notifications@github.com> wrote:

@csells<https://github.com/csells> Interesting - are you able to share the .NET code that runs your socket server? (and which OS/runtime you're running it with) and I can see if I can repro and see what's going on.

**Comment by DanTup** [comment]
@csells I had a quick test, and it seems to be that your server doesn't recognise the request as a WebSocket request if it contains `Content-Length: 0`.

I modified your code like this:

```cs
static async Task Acceptor(HttpContext hc, Func<Task> n, IServiceProvider provider) {
      Console.WriteLine("Accepting!");
      Console.WriteLine("Sockets supported? " + (hc.Features.Get<IHttpWebSocketFeature>() != null));
      if (!hc.WebSockets.IsWebSocketRequest) {
        Console.WriteLine("Not a socket request :(");
        foreach(var header in hc.Request.Headers) {
          Console.WriteLine(header.Key + " = " + header.Value);
        }
        return;
      }
```

This prints that `IsWebSocketRequest=false` for the Dart client. Taking those headers, you can repro using `curl`:

## Fails:

```
curl -i -N \
	-H "Connection: Upgrade" \
	-H "Upgrade: websocket" \
	-H "Host: localhost" \
	-H "sec-websocket-version: 13" \
	-H "sec-websocket-extensions: permessage-deflate; client_max_window_bits" \
    -H "sec-websocket-key: f2zyXfuOFlK+GaYh1/HqnQ==" \
	http://localhost:5000/fibs
```

## Works:

```
 curl -i -N \
	-H "Connection: Upgrade" \
	-H "Upgrade: websocket" \
	-H "Host: localhost" \
	-H "Content-Length: 0" \
	-H "sec-websocket-version: 13" \
	-H "sec-websocket-extensions: permessage-deflate; client_max_window_bits" \
    -H "sec-websocket-key: f2zyXfuOFlK+GaYh1/HqnQ==" \
	http://localhost:5000/fibs
```

The only difference here is the Content-Length header. I had a quick search, and think this may be a .NET issue`. I had a quick search and found a PR that looks like it should fix this:

https://github.com/aspnet/KestrelHttpServer/pull/2217

The last comment suggests it shipped in .NET Core 2.1. I don't know what's being used here, though I see a 2.0.3 in your csproj - if that's where this is coming from, maybe upgrading it to >= 2.1 will fix.

Hope this helps!

**Comment by DanTup** [comment]
@csells I just changed the csproj to 2.2.2 (and 2.2 at the top) and re-restored, and I can now connect with CURL. Give it ago :-)

**Comment by csells** [comment]
excellent! thanks very much.

**Comment by akinschen** [comment]
> @zoechi
> 
> in NodeJS app, I use the following configurations
> 
> > .env file
> > ip: 127.0.0.1, ( also tried 0.0.0.0 to accept other than localhost requests )
> > port : 3335
> 
> And in the browser url address:
> 
> `http://127.0.0.1:3335` or `http://localhost:3335` which both works fine and Websocket request upgrades successfully
> 
> from my Emulator and chrome browser
> `http://127.0.01:3335 // if I forward my adb port it works fine.`
> `http://10.0.2.2:3335` works fine
> `http://192.168.191.1:3335` works fine
> 
> from my real android device, chrome browser
> `http://192.168.191.1:3335` works fine
> 
> but none of them works in flutter. But I don't know how it can connect to `ws://echo.websocket.org` without any problem !
> 
> I tried my app with all possible ways in 2 pc, both same result.

Did you fix the problem ? I am now suffering the same problem.
It sees that there is a lot problems with Flutter...

**Comment by DanTup** [comment]
@Ali-Azmoud @akinschen Are either of you able to provide a small runnable sample of the node server and the Dart code that's failing to connect to it so that I can run it locally?

**Comment by Willven** [comment]
I found manually specifying the 'Origin' header of web socket connection request solved this issue for me.

**Comment by akinschen** [comment]
> @Ali-Azmoud @akinschen Are either of you able to provide a small runnable sample of the node server and the Dart code that's failing to connect to it so that I can run it locally?
Sorry,I don't have the sample code, But I used Openfire as the Web Socket Server.  Openfire is an opensource XMPP Server , and it supports websocket...

**Comment by akinschen** [comment]
> I found manually specifying the 'Origin' header of web socket connection request solved this issue for me.
Good news~~

**Comment by akinschen** [comment]
> @Ali-Azmoud @akinschen Are either of you able to provide a small runnable sample of the node server and the Dart code that's failing to connect to it so that I can run it locally?
I have finally solved my problems after added some header  manually.
```
    Map myheaders=new Map<String,dynamic>();
    myheaders["Origin"]="file://";
    myheaders["sec-websocket-protocol"]="xmpp";
```
In my case,  "sec-websocket-protocol"="xmpp" is the MUST,  because I am going to connect  to an XMPP Server.

 Thank you.

**Comment by DanTup** [comment]
This issue has become a little overloaded. The original error message contained "Error connecting to observatory" which relates to Flutter trying to connect to Observatory (both the client and server are controlled by Flutter/Dart). The more recent comments are issues connecting Dart code to non-Dart servers (which should work, but if it doesn't, is likely a very different issue to the Observatory one).

So this issue doesn't remain open forever because it's not clear what it is, let's keep it focused on failures to connect *to Observatory*. If anyone is still having this issue, please comment below an include the full output of `flutter doctor -v`.

For anyone having issues connecting to their own/third party servers using Dart, if could be something like the above (eg. you need to pass specific headers for the server to accept the connection), but if you do believe it's a Dart bug, please open a new issue (here or in dart-lang/sdk) including the Dart code and info about the server so that it can be reproduced (feel free to CC me). Thanks!

**Comment by rajeshzmoke** [comment]
```
 [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: WebSocketChannelException: WebSocketChannelException: WebSocketException: Connection to 'http://192.168.46.20:8080#' was not upgraded to websocket
E/flutter (29104): #0      new IOWebSocketChannel._withoutSocket.<anonymous closure> 
package:web_socket_channel/io.dart:83
E/flutter (29104): #1      _invokeErrorHandler  (dart:async/async_error.dart:17:29)
E/flutter (29104): #2      _HandleErrorStream._handleError  (dart:async/stream_pipe.dart:286:9)
E/flutter (29104): #3      _ForwardingStreamSubscription._handleError  (dart:async/stream_pipe.dart:168:13)
E/flutter (29104): #4      _rootRunBinary  (dart:async/zone.dart:1144:38)
E/flutter (29104): #5      _CustomZone.runBinary  (dart:async/zone.dart:1037:19)
E/flutter (29104): #6      _CustomZone.runBinaryGuarded  (dart:async/zone.dart:939:7)
E/flutter (29104): #7      _BufferingStreamSubscription._sendError.sendError  (dart:async/stream_impl.dart:355:15)
E/flutter (29104): #8      _BufferingStreamSubscription._sendError  (dart:async/stream_impl.dart:373:16)
E/flutter (29104): #9      _BufferingStreamSubscription._addError  (dart:async/stream_impl.dart:272:7)
E/flutter (29104): #10     _SyncStreamController._sendError  (dart:async/stream_controller.dart:768:19)
E/flutter (29104): #11     _StreamController._addError  (dart:async/stream_controller.dart:648:7)
E/flutter (29104): #12     _rootRunBinary  (dart:async/zone.dart:1144:38)
E/flutter (29104): #13     _CustomZone.runBinary  (dart:async/zone.dart:1037:19)
E/flutter (29104): #14     _CustomZone.runBinaryGuarded  (dart:async/zone.dart:939:7)
E/flutter (29104): #15     _BufferingStreamSubscription._sendError.sendError  (dart:async/stream_impl.dart:355:15)
E/flutter (29104): #16     _BufferingStreamSubscription._sendError  (dart:async/stream_impl.dart:373:16)
E/flutter (29104): #17     _BufferingStreamSubscription._addError  (dart:async/stream_impl.dart:272:7)
E/flutter (29104): #18     _SyncStreamController._sendError  (dart:async/stream_controller.dart:768:19)
E/flutter (29104): #19     _StreamController._addError  (dart:async/stream_controller.dart:648:7)
E/flutter (29104): #20     new Stream.fromFuture.<anonymous closure>  (dart:async/stream.dart:117:18)
E/flutter (29104): #21     _rootRunBinary  (dart:async/zone.dart:1144:38)
E/flutter (29104): #22     _CustomZone.runBinary  (dart:async/zone.dart:1037:19)
E/flutter (29104): #23     _FutureListener.handleError  (dart:async/future_impl.dart:140:20)
E/flutter (29104): #24     Future._propagateToListeners.handleError  (dart:async/future_impl.dart:651:47)
E/flutter (29104): #25     Future._propagateToListeners  (dart:async/future_impl.dart:672:24)
E/flutter (29104): #26     Future._completeError  (dart:async/future_impl.dart:491:5)
E/flutter (29104): #27     Future._asyncCompleteError.<anonymous closure>  (dart:async/future_impl.dart:539:7)
E/flutter (29104): #28     _rootRun  (dart:async/zone.dart:1124:13)
E/flutter (29104): #29     _CustomZone.run  (dart:async/zone.dart:1021:19)
E/flutter (29104): #30     _CustomZone.runGuarded  (dart:async/zone.dart:923:7)
E/flutter (29104): #31     _CustomZone.bindCallbackGuarded.<anonymous closure>  (dart:async/zone.dart:963:23)
```

**Comment by celsoncustodio** [comment]
Eu consegui resolver, colocando o endereço ip do meu pc no servidor nodejs e o mesmo ip no flutter

**Comment by yemistar** [comment]
if anyone is still having this problem. check this guy code [https://github.com/Flavsditz/websocket_sandbox](url) hopefully it helps.

**Comment by bus710** [comment]
If anyone is still having this problem, check this code out:
https://github.com/gorilla/websocket/tree/master/examples/echo 

I originally had the same issue as others when I was using Golang's default net/http websocket but I could solve with Gorilla package's websocket with the upgrader.

I suspect that the server should have a websocket upgraded already to serve the websocket cloent of dart:io and web_socket_channel so that the code in the link may help somebody.

(Sorry for being late to the discussion)

**Comment by riskyRahul** [comment]
PS E:\VSCodeProject\quickstartgame> flutter run -d Chrome
Launching lib\main.dart on Chrome in debug mode...
Building application for the web...                               124.5s
Attempting to connect to browser instance..
  303.0s (!)
Failed to establish connection with the application instance in Chrome.
This can happen if the websocket connection used by the web tooling is unabled to correctly establish a connection, for example due toa firewall.

**Comment by shraddhajogani** [comment]
Connection to 'http://10.5.11.88:7777/socketcluster/#' was not upgraded to websocket

**Comment by riskyRahul** [comment]
Launching lib\main.dart on Chrome in debug mode...
Building application for the web...
Attempting to connect to browser instance..
Finished with error: Failed to establish connection with the application instance in Chrome.
This can happen if the websocket connection used by the web tooling is unabled to correctly establish a connection, for example due to a firewall.

**after run**  
> flutter run -d Chrome

**Comment by riskyRahul** [comment]
**after run**
> flutter run -d Chrome

Launching lib\main.dart on Chrome in debug mode...
Building application for the web... 124.5s
Attempting to connect to browser instance..
303.0s (!)
Failed to establish connection with the application instance in Chrome.
This can happen if the websocket connection used by the web tooling is unabled to correctly establish a connection, for example due toa firewall.

**Comment by zanderso** [comment]
Hi folks, as mentioned above, this issue is overloaded, and has been closed quite some time back. If you're still having problems, please file a new issue with full information.
