### ISSUE TITLE
[in_app_purchase] restorePurchases() does not restore unconsumed consumables

### ISSUE THREAD

**Issue by jimmyff** [flutter/flutter#114495]
When making a consumable purchase, if I set the `autoConsume: false` I would expect the purchase to be returned when I run `restorePurchases()` with the `PurchaseDetails` property `pendingCompletePurchase==true`. 

However the purchase does not come through at all.

I'm trying to ensure no purchases go missing however I can find no way to restore unconsumed consumables via the client? 

On a side note, I think having the setting `autoConsume` default to `true`  just asking for missing purchases.

**Comment by huycozy** [comment]
Hi @jimmyff 
Which `in_app_purchase` plugin version are you using? Can you provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this? Thanks!

**Comment by jimmyff** [comment]
Hey @huycozy, 
The [example project](https://github.com/flutter/plugins/tree/main/packages/in_app_purchase/in_app_purchase/example) is enough to reproduce this issue and could be considered the minimum reproducible code sample.

The inline documentation says: `Consumed products are no longer considered to be "owned" by payment platforms and will not be delivered by calling [restorePurchases].` -This suggests that setting `autoConsume` to `false` would return the purchases when you call `restorePurchases` however this does not happen.

Once I have received a purchase receipt for a consumable product with auto consume = false. If I fail to process it first time (due to a bug in my client app, user closes the app, device powers off etc) not only is this unrecoverable via `restorePurchases` but the app store (google play in this instance) blocks subsequent purchases of this item saying the item is already owned.

**Comment by danagbemava-nc** [comment]
Hi @jimmyff, what platform(s) are you experiencing this issue on? Please provide the plugin version for the underlying storefront plugin of the platform you experience this issue on. 

Please also provide the output of `flutter doctor -v`.

Thank you
