### ISSUE TITLE
Multiple testWidgets tests are not working in flutter integration test

### ISSUE THREAD

**Issue by jagadeeshpurplle** [flutter/flutter#114417]
Hey all, 

I'm using google flutter integration driver to automate the flutter mobile app.

I want to write multiple `widgetTests` in a single `main_test.dart` file.

First test is running successfully, but when second test starts i see `Test starting...`(attached screenshot below) screen in emulator, but actually not moving forward to launch the app screen.
<img width="231" alt="Screenshot 2022-11-01 at 6 26 39 PM" src="https://user-images.githubusercontent.com/25878053/199239862-dc570b95-1164-46d1-9878-085fc5c2b885.png">

And finally, getting below error saying that `Bad state: No element` as app itself is not loaded.!

```
Failure Details:
Failure in method: check value increments
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞═════════════════
The following StateError was thrown running a test:
Bad state: No element

When the exception was thrown, this was the stack:
#0      Iterable.single (dart:core/iterable.dart:654:25)
#1      WidgetController.element (package:flutter_test/src/controller.dart:114:30)
#2      WidgetController.ensureVisible (package:flutter_test/src/controller.dart:1210:73)
#3      main.<anonymous closure>.<anonymous closure> (file:///Users/tummalacharlajagadeesh/Desktop/Sparrow/synapse-cards-mobile/synapse-cards-mobile/integration_test/sanity_test.dart:87:20)
<asynchronous suspension>
```

Here is my `main_test.dart` file
<details><summary>CLICK ME</summary>
<p>

```

import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:get_it/get_it.dart';
import 'package:integration_test/integration_test.dart';
import 'package:sparrowmobile/flavor/uat.dart' as app;


void main() {
  final binding = IntegrationTestWidgetsFlutterBinding.ensureInitialized();
  binding.framePolicy = LiveTestWidgetsFlutterBindingFramePolicy.fullyLive;
  
  group('sanity test suite', () {
    //runs before each test
    setUp(() async {
      app.main();
    });

    //runs after each test
    tearDown(() async {
      final getIt = GetIt.instance;
      await getIt.reset();
    });

    testWidgets('sample test', (tester) async {
      await tester.pumpAndSettle(const Duration(seconds: 5));

      // ensure title is visible
      await tester.ensureVisible(find.byKey(const ValueKey('startButton')));
      await tester.tap(find.byKey(const ValueKey('startButton')));
      await tester.pumpAndSettle();
      expect(find.text('Home Screen'), findsOneWidget);
      expect(find.text('Transactions'), findsOneWidget);
    });

    testWidgets('check value increments', (tester) async {
      await tester.pumpAndSettle(const Duration(seconds: 10));

      //ensure title is visible
      await tester.ensureVisible(find.byKey(const ValueKey('startButton')));
      await tester.tap(find.byKey(const ValueKey('startButton')));
      await tester.pumpAndSettle();
    });

  });
}
```

</p>
</details>

Can anybody help me in running multiple widgetTests in a single main test file?

**Comment by exaby73** [comment]
Hello @jagadeeshpurplle. You can run multiple `testWidgets` in a single file. Looks like an error in your test file from the stack trace:

```console
#3      main.<anonymous closure>.<anonymous closure> (file:///Users/tummalacharlajagadeesh/Desktop/Sparrow/synapse-cards-mobile/synapse-cards-mobile/integration_test/sanity_test.dart:87:20)
```

Please check this code. If you are still experiencing this issue, please provide the following information?

- A [complete and minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). Ideally, a single `main.dart` file that can be run directly.
- The output of `flutter doctor -v`
- The output of `flutter run-v`

Please provide the information in the form of text. See how to make collapsible sections with Markdown [here](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-collapsed-sections).

**Comment by jagadeeshpurplle** [comment]
> Hello @jagadeeshpurplle. You can run multiple `testWidgets` in a single file. Looks like an error in your test file from the stack trace:
> 
> ```
> #3      main.<anonymous closure>.<anonymous closure> (file:///Users/tummalacharlajagadeesh/Desktop/Sparrow/synapse-cards-mobile/synapse-cards-mobile/integration_test/sanity_test.dart:87:20)
> ```
> 
> Please check this code. If you are still experiencing this issue, please provide the following information:
> 
> * A [complete and minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). Ideally, a single `main.dart` file that can be run directly.
> * The output of `flutter doctor -v`
> * The output of `flutter run-v`
> 
> Please provide the information in the form of text. See how to make collapsible sections with Markdown [here](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-collapsed-sections).

Yes @exaby73 , at 
```
#3      main.<anonymous closure>.<anonymous closure> (file:///Users/tummalacharlajagadeesh/Desktop/Sparrow/synapse-cards-mobile/synapse-cards-mobile/integration_test/sanity_test.dart:87:20)
```
, it failed because its trying to locate that element when the app itself not loaded yet. I mean the `Test starting...` screen which i attached above was not moving forward.

May be the after executing first test case, the app might be not closed completely?

**Comment by exaby73** [comment]
> Please check this code. If you are still experiencing this issue, please provide the following information:
>
> - A [complete and minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). Ideally, a single main.dart file that can be run directly.
> - The output of flutter doctor -v
> - The output of flutter run-v
>
> Please provide the information in the form of text. See how to make collapsible sections with Markdown [here](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-collapsed-sections).

Please provide the information requested
