### ISSUE TITLE
Run version of `Mac Unopt` on arm64 Mac, run tests on arm Mac and against arm simulators

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#114452]
- Run on arm64 Macs via `cpu` property in `.ci.yaml`
- Ensure there is sufficient capacity in all pools
- Build the simulator with `--simulator-cpu arm64`
- Build host with `--mac-cpu arm64`
- Set the `FLUTTER_ENGINE` and `--variant` to `host_debug_unopt_arm64` or `ios_debug_sim_arm64` respectively when testing

This would detect toolchain regressions like https://github.com/flutter/flutter/issues/114440, as well as detect arm simulator and desktop regressions in the engine before it reaches the framework.

Continue to test `Mac Unopt` on a separate x64 builder.

**Comment by jmagman** [comment]
cc @dnfield @godofredoc @zanderso

**Comment by jmagman** [comment]
I believe goma does not work on arm hosts so this will probably be slow...

**Comment by jmagman** [comment]
We could start with just building the simulator without testing anything.  That would at least catch things like clang no longer working for arm Macs https://github.com/flutter/flutter/issues/114440

**Comment by jmagman** [comment]
> We could start with just building the simulator without testing anything. That would at least catch things like clang no longer working for arm Macs #114440

Oh and that would also mean we don't to install the simulator runtimes, which takes awhile.

**Comment by jmagman** [comment]
cc @cbracken

**Comment by cbracken** [comment]
For x-ref purposes: We'll need to land https://github.com/flutter/flutter/issues/103386, and specifically https://github.com/flutter/flutter/issues/115322 to get the tests, in order to make this happen.

**Comment by jmagman** [comment]
Done on https://github.com/flutter/engine/pull/41141.
