### ISSUE TITLE
Can not get my existing iOS app working with flutter

### ISSUE THREAD

**Issue by mikeyunpeng** [flutter/flutter#114454]
## Steps to Reproduce

I followed the option C in https://docs.flutter.dev/development/add-to-app/ios/project-setup
I first run `flutter build ios-framework --cocoapods --output=some/path/MyApp/Flutter/`
And in Flutter folder, I only see following created:

- Debug
    - App.xcframework
    - Flutter.podspec
- Profile
- Release

I expect FlutterPluginRegistrant.xcframework is also created as expected by following the option c in the doc above.
However, the FlutterPluginRegistrant.xcframework is missing from the output.

Then I adde pod 'Flutter', :podspec => 'some/path/MyApp/Flutter/Debug/Flutter.podspec' to my pod file
I run podinstall and build the xcworkspace. The build is successful.

However because FlutterPluginRegistrant is missing, I won't be able to call
`GeneratedPluginRegistrant.register(with: self.flutterEngine);` in AppDelegate
When I open my existing iOS app, it can not load the flutter demo screen.

**Expected results:** Able to load flutter demo screen from my existing iOS app

**Actual results:** I don't see any flutter demo screen is loaded and rendered.

**Comment by mikeyunpeng** [comment]
Here is flutter doctor result
 my_flutter % flutter doctor -v

┌─────────────────────────────────────────────────────────┐
│ A new version of Flutter is available!                  │
│                                                         │
│ To update to the latest version, run "flutter upgrade". │
└─────────────────────────────────────────────────────────┘
[✓] Flutter (Channel stable, 3.3.4, on macOS 12.6.1 21G217 darwin-x64, locale en-US)
    • Flutter version 3.3.4 on channel stable at /Users/mikwang/work/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision eb6d86ee27 (4 weeks ago), 2022-10-04 22:31:45 -0700
    • Engine revision c08d7d5efc
    • Dart version 2.18.2
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/mikwang/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = /Users/mikwang/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/mikwang/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13A233
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.1.2)
    • IntelliJ at /Applications/LI IntelliJ IDEA 2021.1.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (3 available)
    • iPhone 11 (mobile) • B5E6A7E2-4697-4304-BA4F-5B30469BD6D2 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • macOS (desktop)    • macos                                • darwin-x64     • macOS 12.6.1 21G217 darwin-x64
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 107.0.5304.87

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Comment by danagbemava-nc** [comment]
Hi @mikeyunpeng, if you are not using plugins in your flutter module, you do not need to call `GeneratedPluginRegistrant.register()`. 

See https://docs.flutter.dev/development/add-to-app/ios/add-flutter-screen#create-a-flutterengine for more information.

**Comment by mikeyunpeng** [comment]
@danagbemava-nc However, I followed the option C step by step with very simple hello world sample app.  When I tap the button to open the FlutterViewController, the view is transparent and doesn't show anything.  Can you let me know what you need to help me debug this issue as Flutter integration is very important for my company app now. Thanks

**Comment by mikeyunpeng** [comment]
Here is the screenshot of the sample app to open FlutterViewcontroller
![Nov-02-2022 13-54-29](https://user-images.githubusercontent.com/91577150/199600753-dc9eb93b-e923-49a0-84e4-ba0904cdbeae.gif)

**Comment by mikeyunpeng** [comment]
Here is the screenshot of code to open FlutterViewController
![Screen Shot 2022-11-02 at 1 56 27 PM](https://user-images.githubusercontent.com/91577150/199600929-aad94511-49ce-40e1-8bf1-8e3fbf893a7e.png)
![image](https://user-images.githubusercontent.com/91577150/199600993-adc98697-a579-4728-8cbf-0df3a655ba05.png)

**Comment by mikeyunpeng** [comment]
So I didn't do an customization as I just follow step by step from Option C to add the Flutter framework and add code to show FlutterUI from an existing iOS app.  The app is just a sample app created from XCode.  And I just add the instructed code from the https://docs.flutter.dev/development/add-to-app/ios/add-flutter-screen

As you see from above screenshot, I can't open the demo FlutterUI after I tap the button.

**Comment by mikeyunpeng** [comment]
by the way, I have fixed this issue.  I think I need to add the app.xcframework and embed to the XCode project.  That's why the flutter app is not loaded because it's missing the app framework.
