### ISSUE TITLE
internal builds do not have enough capacity to complete in 1h

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#114478]
Internal builds have limited linux capacity that along with building without goma is causing a few builder to time out.

We need to find a way to increase the timeout for internal builds only. An idea is a property that can be propagated all the way to the 3rd level subbuilds.

**Comment by godofredoc** [comment]
\cc @yusuf-goog

**Comment by godofredoc** [comment]
A timeout increase for this builders is acceptable as long as we are increasing the timeouts for main builds.

**Comment by yusuf-goog** [comment]
Will the timeout increase on the main builds work in this case? If a sub task is timing out (e.g. `Linux linux_android_debug_engine`)?

**Comment by godofredoc** [comment]
No, it needs to be propagated to the subbuilds.
