### ISSUE TITLE
[CP] Handle privatecommand messages that pass no data

### ISSUE THREAD

**Issue by absar** [flutter/flutter#114462]
### issue_link

https://github.com/flutter/flutter/issues/113973

### Commit Hash

a832a72

### Target

stable

### pr_link

https://github.com/flutter/flutter/pull/114461

### Impacted Users

Android devices where privatecommand messages pass no data

### Impact Description

Tapping `TextFormField` throws _CastError was thrown during method call TextInputClient.performPrivateCommand type 'Null' is not a subtype of type 'Map<String, dynamic>'. It is thrown every time user taps in a text field, which floods crashlytics with crash logs.

### Workaround

No workaround on stable branch Flutter 3.3, the only fix is to downgrade to Flutter 3.0.x

### Risk

low

### Test Coverage

yes

### Validation Steps

Check https://github.com/flutter/flutter/issues/113973

**Comment by absar** [comment]
hi @justinmc based on your suggestion in https://github.com/flutter/flutter/pull/112590#issuecomment-1299073469 I have opened this CP request and PR https://github.com/flutter/flutter/pull/114461 please give it a look

**Comment by justinmc** [comment]
Thank you!

CC @itsjustkevin for approving this as a cherry pick.
