### ISSUE TITLE
Add const constructor to TextInputFormatter

### ISSUE THREAD

**Issue by hurelhuyag** [flutter/flutter#114401]
## Use case

Currently, form controls are const constructible. But there is single thing preventing it to const construct. It is TextInputFormatter. 

## Proposal

Add const constructor to `TextInputFormatter`
```
abstract class TextInputFormatter {
  const TextInputFormatter();

  // rest of codes
}
```
This makes subclasses of `TextInputFormatter` are const constructible.

**Comment by shogohida** [comment]
Hi, I wanted to contribute to this issue and made a pull request! I'm still waiting for checks so I'll make it ready later
