### ISSUE TITLE
Rejected by the store for using the "REQUEST_INSTALL_PACKAGES" permission even using the REMOVE tag

### ISSUE THREAD

**Issue by marcelomfranca** [flutter/flutter#114423]
I checked the android manifest merge log file and it had the permission included by the "image picker" package, so I used the following solution:

<uses-permission android:name="android.permission.REQUEST_INSTALL_PACKAGES" tools:node="remove"/>

Looking at the log, in fact now this permission is being applied by my project's manifest with the "remove tag", but I continue with the store rejection.

Still rejected, please some help?

Flutter version is: 2.10.5

**Comment by stuartmorgan** [comment]
`image_picker` does not include this permission. You should re-check the merge log, as people often read it backward: the source of a permission is *after* the permission, not before it.

Closing as there are no Flutter-team-owned plugins using this permission; you'll need to find the plugin that's actually including it and contact the authors.

**Comment by marcelomfranca** [comment]
> `image_picker` does not include this permission. You should re-check the merge log, as people often read it backward: the source of a permission is _after_ the permission, not before it.
> 
> Closing as there are no Flutter-team-owned plugins using this permission; you'll need to find the plugin that's actually including it and contact the authors.

You is right the package was open_file. Thanks.
