### ISSUE TITLE
`material/bottom_app_bar.dart` is out of sync with `gen_defaults/lib/bottom_app_bar.dart`

### ISSUE THREAD

**Issue by TahaTesser** [flutter/flutter#114405]
### Description

When you execute `dart dev/tools/gen_defaults/bin/gen_defaults.dart` on the `master` branch, It should not make any changes to `packages/flutter` unless a new template is added for a PR.

However, I see this `bottom_app_bar.dart` is out of sync with` gen_defaults/lib/bottom_app_bar.dart` on master after https://github.com/flutter/flutter/pull/106525. 
(I also noticed this with other recently landed classes but they seemed to be fixed now).

### Steps to reproduce
1. `git clone git@github.com:flutter/flutter.git`

2. `cd flutter` and `dart dev/tools/gen_defaults/bin/gen_defaults.dart`

#### The shape is out of sync.

![Screenshot 2022-11-01 at 10 34 47](https://user-images.githubusercontent.com/48603081/199195350-10ea7da2-d2ba-4bf2-a656-46ee150b4b88.png)

**Comment by TahaTesser** [comment]
cc: @darrenaustin @elbeicktalat

**Comment by darrenaustin** [comment]
Ooops. I missed this in the review. The tokens were updated on master and so we need to regenerate them with the latest from master. As this PR already got reverted this morning for another reason (#106525), I will go ahead and fix this when I attempt to reland the original PR. Thanks for pointing this out.
