### ISSUE TITLE
The color of the thumb does not change when pressed on Android, and the overlayColor for the thumb is not highlighted during animation.

### ISSUE THREAD

**Issue by MaxYablochkin** [flutter/flutter#114415]
#91605
#103536

## Current implementation
![Screenshot_1667299667](https://user-images.githubusercontent.com/102767277/199220354-b3a8495b-749f-46cd-884e-3a2f4808e088.png)
![Screenshot_1667298644](https://user-images.githubusercontent.com/102767277/199220351-bb74ecc2-983f-40bd-9167-e72ec8278f8a.png)

## Desired implementation
![Screenshot_12](https://user-images.githubusercontent.com/102767277/199220450-b986d34a-f71d-44ca-b0cc-ae936b02ebbc.png)
![Screenshot_10](https://user-images.githubusercontent.com/102767277/199220464-9dd3695d-cf12-48cb-9e56-6cb9e759eebb.png)

**Comment by huycozy** [comment]
Hi @MaxYablochkin 
>overlayColor for the thumb is not highlighted during animation.

Can you share which part of specs for this? I can't see it from https://m3.material.io/components/switch/specs.

**Comment by MaxYablochkin** [comment]
> Привет@MaxYablochkin
> 
> > overlayColor для большого пальца не выделяется во время анимации.
> 
> Можете ли вы поделиться, какая часть спецификаций для этого? Я не вижу его с https://m3.material.io/components/switch/specs .

https://m3.material.io/components/switch/specs#789e476d-c903-4452-a2ec-8e001a6390c1
https://m3.material.io/components/switch/specs#34f9a158-a2b3-4c15-841b-578978126788

**Comment by MaxYablochkin** [comment]
> Привет@MaxYablochkin
> 
> > overlayColor для многих не воспринимается во время анимации.
> 
> Можете ли вы поделиться, какая часть свойственна этому? Я не вижу его с https://m3.material.io/components/switch/specs .

Looked a little at XML🙂
In the XML, holding down the thumb brings up an overlay that animates slowly so it looks like it's showing the entire path of the track. So I may have been wrong. But still, when you quickly click on the thumb, you can't see that the overlay appears.

**Comment by huycozy** [comment]
@MaxYablochkin 
>But still, in flutter, when you quickly press the thumb, you can’t see that the overlay appears, but only when you hold it down. It's more of a matter of InkRipple, or physics in flutter.

I'm not sure I can see this issue. Currently, I'm seeing behavior similar to the sample https://m3.material.io/components/switch/guidelines#2495f276-189c-4d51-a9df-88e89e8e8185. So leave this for further insights from the team.


>The color of the thumb does not change when pressed on Android

With the first issue, I can reproduce it on the latest `master` channel. It seems the issue only happens on Android but not on Web or macOS

<details>
<summary>Demo (android and web)</summary>

| Android | Web |
| --------------- | --------------- |
<video src="https://user-images.githubusercontent.com/104349824/199400109-ec6f7779-9434-4db7-aeb2-ed853967dc6d.mov"/> | <video src="https://user-images.githubusercontent.com/104349824/199400115-a10a35d2-f98a-43cd-9cae-a2634dfcd4a7.mov"/>

</details>

<details>
<summary>Sample code</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        useMaterial3: true,
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: Scaffold(
        body: Center(
          child: Switch(
            onChanged: (bool value) {},
            value: false,
          ),
        ),
      ),
    );
  }
}

```
</details>

<details>
<summary>flutter doctor -v (master)</summary>

```bash
[!] Flutter (Channel master, 3.5.0-12.0.pre.69, on macOS 12.6 21G115 darwin-x64, locale en-VN)
    • Flutter version 3.5.0-12.0.pre.69 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 97d0247d59 (51 minutes ago), 2022-11-02 04:31:00 +0200
    • Engine revision 81f5c30b23
    • Dart version 2.19.0 (build 2.19.0-359.0.dev)
    • DevTools version 2.18.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode14.0.1.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Community Edition (version 2022.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 70.0.5
    • Dart plugin version 222.4167.21

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.72.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (3 available)
    • SM T225 (mobile) • R9JT3004VRJ • android-arm64  • Android 12 (API 31)
    • macOS (desktop)  • macos       • darwin-x64     • macOS 12.6 21G115 darwin-x64
    • Chrome (web)     • chrome      • web-javascript • Google Chrome 107.0.5304.87

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```
</details>
