### ISSUE TITLE
[Material] Switch widget crashes on desktop due to cast error on gesture

### ISSUE THREAD

**Issue by loic-sharma** [flutter/flutter#114542]
An internal Google team is getting `_CastError: gesture` exceptions in `_MaterialSwitchState._handleDragEnd` on macOS.

Internal Google link [b/257491764](https://b.corp.google.com/257491764).

Example crash: `_CastError: gesture`

```
#0 _MaterialSwitchState._handleDragEnd (package:flutter/src/material/switch.dart:696)
#1 DragGestureRecognizer._checkEnd.<anonymous closure> (package:flutter/src/gestures/monodrag.dart:521)
#2 GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:253)
#3 DragGestureRecognizer._checkEnd (package:flutter/src/gestures/monodrag.dart:521)
#4 DragGestureRecognizer.didStopTrackingLastPointer (package:flutter/src/gestures/monodrag.dart:426)
#5 OneSequenceGestureRecognizer.stopTrackingPointer (package:flutter/src/gestures/recognizer.dart:446)
#6 DragGestureRecognizer._giveUpPointer (package:flutter/src/gestures/monodrag.dart:435)
#7 DragGestureRecognizer.handleEvent (package:flutter/src/gestures/monodrag.dart:354)
#8 PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:98)
#9 PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:143)
#10 _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:624)
#11 PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:141)
#12 PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:127)
#13 GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:460)
#14 GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:440)
#15 RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:334)
#16 GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:395)
#17 GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:357)
#18 GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:314)
#19 GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:295)
#20 _invoke1 (dart:ui/hooks.dart:164)
#21 PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:361)
#22 _dispatchPointerDataPacket (dart:ui/hooks.dart:91)
```

**Comment by gspencergoog** [comment]
It seems like the `!` on [this line](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/switch.dart#L696) should probably be `widget.onChanged?.call(!widget.value);` instead.  The `_CastError` is probably happening because of the non-null operator casting to a non-nullable type.

**Comment by gspencergoog** [comment]
To clarify: I suspect (I have not verified it) that there is a case where the `onChanged` is set to `null` when the switch gets disabled, but that the `GestureDetector` sends events between the frame where it is set to null and the next one (or maybe just during the animation for disabling), meaning that the callback gets called after the switch widget has been modified to have a null `onChanged` but before it is fully done being disabled. There's probably a reason why it happens just on drag end, and not on drag update.

In any case, checking the callback for being null before calling it seems like an OK thing to do.

**Comment by QuncCccccc** [comment]
> To clarify: I suspect (I have not verified it) that there is a case where the `onChanged` is set to `null` when the switch gets disabled, but that the `GestureDetector` sends events between the frame where it is set to null and the next one (or maybe just during the animation for disabling), meaning that the callback gets called after the switch widget has been modified to have a null `onChanged` but before it is fully done being disabled. There's probably a reason why it happens just on drag end, and not on drag update.
> 
> In any case, checking the callback for being null before calling it seems like an OK thing to do.

Thanks so much for the explanation! It makes sense to me. Will add a check to the callback!

**Comment by whiskeyPeak** [comment]
Given that the PR has been merged, this can probably be closed now.
