### ISSUE TITLE
Bad navigation in Flutter Gallery (Android)

### ISSUE THREAD

**Issue by wmleler** [flutter/flutter#11455]
## Steps to Reproduce

Run Flutter Gallery app on an Android phone.
Select "Animation" demo.
Select one of the four sub-panels, like "Seating".
THEN: press either the back button for the phone, or the back arrow in the upper left corner.

Result: the app goes back to the main page, instead of going back to the Animation demo main page.

Note that running the iOS simulator under IntelliJ, the back button or arrow does take you back to the previous screen.

Also, running it on the 6P as a device works fine. It is just the Flutter Gallery app from the play store. Is the Flutter gallery app out of date?

**Comment by sethladd** [comment]
Thanks for the report!

If we have "critical mass" of features and fixes, I'm happy to push a new version of Gallery.

**Comment by guidezpl** [comment]
Closing as obsolete
