### ISSUE TITLE
[Impeller] Bundling Vulkan support for Impeller on Android is expected to cause a size regression

### ISSUE THREAD

**Issue by iskakaushik** [flutter/flutter#114531]
I’m looking at linking Vulkan on Android builds by default, this will make it easier to switch between

- Skia
- Impeller + Vulkan
- Impeller + GLES

This is as opposed to adding a new variant. Doing so does bring about a size increase:

### Before (android_release_arm64):
- flutter.jar - 5.2M
- libflutter.so - 149M  (unstripped)

### After (android_release_arm64 with Vulkan):
- flutter.jar - 5.35M
- libflutter.so - 151M (unstripped)

**Comment by iskakaushik** [comment]
Capturing discussion:

1. Seems acceptable on first look.
2. Look at the CI for the tree-maps to see where the size increase is coming from.
3. Notify relevant parties and rollers.

**Comment by zanderso** [comment]
In theory, SkiaPerf should flag the Engine -> Framework roll commit when this hits the framework. (If that doesn't happen, then we will need to adjust the filters there.)

**Comment by chinmaygarde** [comment]
Hmm, the ~150k increase is larger than we've observed from the other backends at ~100k. But, it's acceptable and likely attributed to VMA. I can't think of anything else that would cause this.

When we land this, can we pull and attach the engine size tree-maps to this issue for analysis. I do this using `gsutil cp -R gs://flutter_infra_release/flutter/<ENGINE_SHA_GOES_HERE>/android-arm-release/sizes .`. But its a public bucket and there is probably a web interface I don't know how to access.

**Comment by dnfield** [comment]
I posted this on the PR, but the linked PR didn't seem to have much effect on the binary size overall. Is there more to come?

**Comment by iskakaushik** [comment]
@dnfield Thanks for taking a look. I am not sure why there is a discrepancy between my local builds vs the ones on CI. But this is good news.  It might be that CI was building with a different set of flags. These were mine:

`./flutter/tools/gn --android --android-cpu=arm64 --runtime-mode=release`

I then took a look at the size of `flutter.jar`. Would appreciate if you could give it a shot locally to see if it's my setup issue.

**Comment by jason-simmons** [comment]
I did a quick analysis of the difference in object file sizes when building an android_release engine with the `AndroidSurfaceVulkanImpeller` #ifdef in `AndroidSurfaceFactoryImpl::CreateSurface` enabled.

The increased size comes mostly from Vulkan-related code in the engine (`flutter/vulkan`, `gpu_surface_vulkan`, `android_surface_vulkan_impeller`, `flutter_vma`) and Skia (`src/gpu/vk` and `src/gpu/ganesh/vk`)

**Comment by dnfield** [comment]
There's probably a Skia define to ask it not to build with Vulkan right? If we're not actually using Vulkan on Skia we shouldn't need to build any more of it.

**Comment by dnfield** [comment]
yeah in `flutter/tools/gn` we should not set `skia_use_vulkan` to true

**Comment by jason-simmons** [comment]
`skia_use_vulkan=True` is required by some of the `flutter/vulkan` sources (such as the dependency on `GrVkBackendContext` in `https://github.com/flutter/engine/blob/main/vulkan/vulkan_window.cc`)

But most of the Skia Vulkan code is stripped out of the final linked binary.

In the linked `libflutter.so`, it looks like most of the size increase is coming from `impeller_entity_shaders_vk_data`

**Comment by chinmaygarde** [comment]
| But most of the Skia Vulkan code is stripped out of the final linked binary.

Thanks for checking!

| it looks like most of the size increase is coming from impeller_entity_shaders_vk_data

Perfect. Thats expected.

**Comment by zanderso** [comment]
Here is a link to the relevant benchmark in SkiaPerf: https://flutter-flutter-perf.skia.org/e/?queries=sub_result%3Dlibflutter_compressed_bytes%26test%3Dhello_world_android__compile

**Comment by chinmaygarde** [comment]
Closing this as completed.
