### ISSUE TITLE
Casting from dyamic type to int? does not work for SliverChildBuilderDelegate

### ISSUE THREAD

**Issue by ravetisy** [flutter/flutter#114510]
When trying to give the item count for SliverChildBuilderDelegate widget, something like this :
childCount: data_from_provier['foobar']?.length ?? 0. Then flutter says during build that the type int? is not compatible 

The same int? property have the ListView.Builder( itemCount ?) the same logic worked for ListView.

**Comment by ravetisy** [comment]
<img width="790" alt="image" src="https://user-images.githubusercontent.com/31383327/199520672-9ee8c86a-2683-47a4-b64d-5bbd72541a83.png">

**Comment by iapicca** [comment]
@ravetisy 

1. you forgot to cast the iterable
```dart
const receivedData = {
  'currentOrder': [0, 1, 2, 3],
  'meaningOfLife': 42,
};

void main() {
  print((receivedData['currentOrder'] as Iterable).length);
}
```

2. probably 'current_oder' is a typo

<details>
  <summary>your screenshot</summary>

> <img alt="image" width="790" src="https://user-images.githubusercontent.com/31383327/199520672-9ee8c86a-2683-47a4-b64d-5bbd72541a83.png">

</details>


3. parsing stuff in the ui layer is simply bad (and error prone, see point `.2`), 
I recommend something like [this](https://docs.flutter.dev/development/data-and-backend/json#serializing-json-inside-model-classes)

**Comment by huycozy** [comment]
Hi @ravetisy, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this. Also, please provide the output of `flutter doctor -v` as well. Thanks!

**Comment by ravetisy** [comment]
Thank for responses, I will try. As the code is constantly  changing and still nor released I wont be able to provide example. IN few weeks we will finish and I will try to retest and if issues exists I will provide.
