### ISSUE TITLE
[Impeller] Incorrect glyph bounds calculations may cause glyph contents to bleed into one another.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#114563]
This only happens when the glyphs bounds are incredibly tight. Due to either a rounding error or incorrect glyph bounds calculation or positioning, contents from certain glyphs in the glyph atlas may bleed into one another.

![Screen Shot 2022-11-02 at 5 09 24 PM](https://user-images.githubusercontent.com/44085/199639390-4b04f304-05f4-4453-b70a-be7bb29682bc.png)
![Screen Shot 2022-11-02 at 5 42 44 PM](https://user-images.githubusercontent.com/44085/199639406-d7ebe11b-64e1-4227-8c73-d7c773d0c721.png)

**Comment by chinmaygarde** [comment]
Screenshots from @bdero s investigation.

**Comment by bdero** [comment]
@chinmaygarde May I take this one off your plate while you're tracking down the tricky flakes?

**Comment by chinmaygarde** [comment]
Yes please!
