### ISSUE TITLE
SDK Missing 

### ISSUE THREAD

**Issue by imperio001** [flutter/flutter#114565]
Hello, I hope someone can help me,

update my mac m1 to MAC os Ventura and i get below errors, i already update flutter
When I run the following command the error goes away but flutter doesn't compile

```
sudo xcode-select -switch /Library/Developer/CommandLineTools
```

With the following command the error returns

```
sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
```

```
2022-11-02 21:05:00.955 xcodebuild[4247:63011] Writing error result bundle to /var/folders/35/n1zspt317p37byhfbdztr9mr0000gn/T/ResultBundle_2022-02-11_9-05-0000 p.m..xcresult
xcodebuild: error: SDK "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk" cannot be located.
git: error: Failed to determine realpath of '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk' (errno=No such file or directory)
git: error: sh -c '/Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk -find git 2> /dev/null' failed with exit code 16384: (null) (errno=No such file or directory)
xcode-select: Failed to locate 'git', requesting installation of command line developer tools.
```

**Comment by huycozy** [comment]
Hi @imperio001 
Can you provide the output of command: `xcode-select -p`?

**Comment by imperio001** [comment]
> Hi @imperio001
> Can you provide the output of command: `xcode-select -p`?
the output is 
/Applications/Xcode.app/Contents/Developer 

this is happening in Xcode 14.1 on 14.1 and Mac OS Ventura 

On Xcode 14 
uilding native extensions. This could take a while...
ERROR:  Error installing ffi:
        ERROR: Failed to build gem native extension.

    current directory: /Library/Ruby/Gems/2.6.0/gems/ffi-1.15.5/ext/ffi_c
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby -I /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0 -r ./siteconf20221103-7075-1xkhb0i.rb extconf.rb
checking for ffi.h... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided con

**Comment by darshankawar** [comment]
> ERROR:  Error installing ffi:
>         ERROR: Failed to build gem native extension.
> 
>     current directory: /Library/Ruby/Gems/2.6.0/gems/ffi-1.15.5/ext/ffi_c
> /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby -I /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0 -r ./siteconf20221103-7075-1xkhb0i.rb extconf.rb
> checking for ffi.h... *** extconf.rb failed ***
> Could not create Makefile due to some reason, probably lack of necessary
> libraries and/or headers.  Check the mkmf.log file for more details.  You may
> need configuration options.

@imperio001 
This seems to be pointing to `ffi` package, so take a look at this issue and see if it helps in your case: https://github.com/ffi/ffi/issues/922

**Comment by limajr** [comment]
I've solved a similar problem by exporting the correct path for the SDKROOT:

`export SDKROOT=$(xcrun -sdk macosx --show-sdk-path)
`

**Comment by ityetti** [comment]
Or you can just add missing symlink.
<img width="395" alt="12 3" src="https://user-images.githubusercontent.com/26219171/206306216-fd7dddf6-7ebd-4c6b-aa69-d516b1b0645b.png">

**Comment by xleon** [comment]
In my case the issue was the .zshrc file pointing to and old SDK. Updating it to the latest fixed it: 
![image](https://user-images.githubusercontent.com/145087/207118929-fa14dbff-0339-4a4b-91d1-052b2c70e5c0.png)

**Comment by imperio001** [comment]
Thanks @xleon  that was my mistake

**Comment by AptechMediaSolution** [comment]
> I've solved a similar problem by exporting the correct path for the SDKROOT:
> 
> `export SDKROOT=$(xcrun -sdk macosx --show-sdk-path) `

this work for me also thanks
