### ISSUE TITLE
cloud_firestore should support `setLogLevel(...)`

### ISSUE THREAD

**Issue by yfujiki** [flutter/flutter#114503]
Flutter `cloud_firestore` does not seem to support `setLogLevel(...)`, which can be used to debug network communication between flutter app and Firestore. Since Firestore communication is not over HTTP/S, packet sniffer doesn't work, and there is no way to debug network communication.

Corresponding libraries for other platform (iOS/Android) has it, so why not for Flutter?

**Comment by danagbemava-nc** [comment]
Hi @yfujiki, kindly report this issue on the [flutterfire repo](https://github.com/firebase/flutterfire/issues?q=is:issue+is:open+sort:updated-desc) so that the team can look into this. 

Closing from here as this doesn't seem like a flutter issue. 

Thank you

**Comment by yfujiki** [comment]
@danagbemava-nc My bad 🤦🏻‍♂️ Will do.
