### ISSUE TITLE
[Windows][A11y] Investigate cost and benefit of implement IAccessible2 for Windows accessibility

### ISSUE THREAD

**Issue by yaakovschectman** [flutter/flutter#114547]
We currently use IAccessible/MSAA for Windows accessibility in the Flutter engine. This is a rather outdated interface, and leaves some functionality to be desired. For example, #113960 requires functionality that is not present in our current approach.  
There are at least two options to update our approach: UI Automation, and IAccessible2. UI Automation is a separate system from IAccessible, and would require a considerable amount of boilerplate in the AX code we use. IAccessible2 is a supplemental interface to IAccessible which we may be able to implement in our AX nodes without requiring the same amount of boilerplate and rewrite.  
We will need to investigate this approach and come up with estimates of its cost and benefit, and to understand the minimum implementation required to test and to release.

**Comment by MrBirb** [comment]
Related: [94782](https://github.com/flutter/flutter/issues/94782)
