### ISSUE TITLE
Review flutter/sentry and flutter/crashy w.r.t. Flutter repo standards

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#11454]
Please, review the following repositories w.r.t. our repository standards:

-  https://github.com/flutter/sentry
-  https://github.com/flutter/crashy

/cc @eseidelGoogle @Hixie

**Comment by Hixie** [comment]
After discussing this with @goderbauer, we came to the conclusion that it would be great to put sentry, css_colors, flutter_image, and flutter_markdown into a single repository called "packages". Would you mind doing so? Then I could do the reviews in the PRs where you do that.

**Comment by Hixie** [comment]
(not sure what should happen to crashy. Maybe an example in sentry?)

**Comment by yjbanov** [comment]
I'll start with a repo. Where to put crashy could be a phase 2 discussion.

**Comment by yjbanov** [comment]
There doesn't seem to be too much pressure to do this in the near term. So I'll close this for now.
