### ISSUE TITLE
deferred-components (boxComponent) build directory cannot find app.so-2.part.so file

### ISSUE THREAD

**Issue by hc1991** [flutter/flutter#114562]
Refer to the [deferred-components](https://docs.flutter.dev/perf/deferred-components) demo to write a boxComponent

yaml config
![image](https://user-images.githubusercontent.com/17923307/199638121-1ac65fc4-b894-4e52-abff-3bb6fcf16372.png)

$flutter build appbundle
Deferred components gen_snapshot validation passed.
Running Gradle task 'bundleRelease'...                              5.3s
√ Built build\host\outputs\bundle\release\app-release.aab (8.1MB).

deferred_components_loading_units.yaml 
![image](https://user-images.githubusercontent.com/17923307/199638176-48cc0721-86cf-4cd0-a297-2eebc784eace.png)

The app.so-2.part.so of the buildoutput is not as expected

build\host\intermediates\flutter\
![image](https://user-images.githubusercontent.com/17923307/199637655-ce51a468-d198-4b66-865e-e2f7eeb5feb5.png)

build\boxComponent\intermediates\flutter\
![image](https://user-images.githubusercontent.com/17923307/199637919-ec878936-e4fd-4140-8078-3906533ee262.png)

the app.so-2.part.so appears in the host build directory, not the boxComponent build directory

**Comment by newBrone22** [comment]
i have same problem, what should i to do, to fix this problem?

**Comment by ldz5029** [comment]
same question. Looking forward to a sulotion.

**Comment by vivoliguang** [comment]
has any solution?

**Comment by exaby73** [comment]
Hello @hc1991. Following the documentation, I am successfully able to build and run the application. I went through all steps, including building the appbundle and installing it for local testing. Could you share the complete output of `flutter build appbundle -v`?
