### ISSUE TITLE
[Proposal][In_App_Purchase] Option To Send Additional Data

### ISSUE THREAD

**Issue by vatsa1101** [flutter/flutter#114529]
## Use case
I want to store additional data along with the purchase details in my database. For example, I want to store the source within the app from where the user purchased a product but there is no option to send additional data while buying a product and then receiving it in the stream along with the purchase details

## Proposal
there should be an option to send additional data in the buyConsumable or buyNonConsumable function along with the ProductDetails and this data should then be received in the purchase stream along with the PurchaseDetails which will make it easy for us to store additional data in our server along the purchaseDetails

**Comment by SpajicM** [comment]
I've faced a similar use case few months ago, and this is not a Flutter issue. The underlying IAP platform APIs don't really have the fields to send arbitrary data, and this is especially true for Apple, they're intentionally opaque for privacy reasons.

**Comment by stuartmorgan** [comment]
Closing, as adding functionality that the underlying APIs don't provide is out of scope for the plugin.
