### ISSUE TITLE
Proposal: run `flutter pub get` before `flutter pub run` is necessary

### ISSUE THREAD

**Issue by pedromassango** [flutter/flutter#114505]
## Use case

When running ` flutter pub run build_runner watch --delete-conflicting-outputs` I often get the following error message:
The pubspec.lock file has changed since the .dart_tool/package_config.json file was generated, please run "flutter pub get" again.

## Proposal

Run `flutter pub get` if necessary to avoid this error message and improve UX.

**Comment by christopherfujino** [comment]
Thank you for this proposal!

However, `flutter pub run` really just delegates to `pub run` (see https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/commands/packages.dart#L37C1-L38C1), so this would need to be filed against pub's issue tracker: https://github.com/dart-lang/pub/issues

**Comment by pedromassango** [comment]
Can we forward this to that project?

**Comment by christopherfujino** [comment]
> Can we forward this to that project?

If "we" is me, I don't not have such powers.

**Comment by pedromassango** [comment]
> If "we" is me, I don't not have such powers.

![Screenshot 2023-08-10 at 10 06 17 AM](https://github.com/flutter/flutter/assets/33294549/f1096b19-8693-44f0-93e5-a5e5fed8432b)


Maybe @Hixie does?

**Comment by Hixie** [comment]
I mean, anyone can just file the new issue. :-)
