### ISSUE TITLE
flutter build ipa --export-options-plist not work.

### ISSUE THREAD

**Issue by dylan-kwon** [flutter/flutter#114583]
`--export-options-plist` does not work when trying to deploy IOS in CI environment.

This is my ExportOptions.plist.
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>compileBitcode</key>
	<true/>
	<key>destination</key>
	<string>export</string>
	<key>method</key>
	<string>ad-hoc</string>
	<key>provisioningProfiles</key>
	<dict>
		<key>MY_APP_IDENTIFIER</key>
		<string>MY_PROVISIONING_PROFILE_NAME</string>
	</dict>
	<key>signingCertificate</key>
	<string>Apple Distribution</string>
	<key>signingStyle</key>
	<string>manual</string>
	<key>stripSwiftSymbols</key>
	<true/>
	<key>teamID</key>
	<string>MY_TEAM_ID</string>
	<key>thinning</key>
	<string>&lt;none&gt;</string>
</dict>
</plist>
```
I get an error when I try to build like this:
`were found: Xcode couldn't find any iOS App Development provisioning profiles matching`

But when I try to deploy with `automatically manage signing` turned off in xcode, it succeeds.

Distribution is possible in this way, but it is cumbersome to turn off and turn on auto-signing during the development and distribution process.

What I'm curious about is that I tried to build using `--export-options-plist`, why use `iOS App Development provisioning profiles` instead of using the profile specified in `ExportOptions.plist`?

**Comment by huycozy** [comment]
Hi @dylan-kwon 
Thanks for the report! This is a known issue being tracked at #113977. There is also a workaround at https://github.com/flutter/flutter/issues/113977#issuecomment-1292813495 that you may want to try. 
Closing this issue as a duplicate, so please follow up on it for further updates.
