### ISSUE TITLE
Codelab: Indentation strange

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#11466]
Many code snippets have a strange indentation.

Example: in the snippet below, the lines marked with arrows should have the same indentation.

![image](https://user-images.githubusercontent.com/1227763/28849376-99a62d08-76cb-11e7-87f3-36d3db60d6cf.png)

@LarkAscending

**Comment by LarkAscending** [comment]
Much experimentation w/IntelliJ settings. IntelliJ docs no help. Much searching for others w/this issue - none found. 
This happens when pasting to Gmail as well as Google Docs...
Have asked Dart DevRel team for advice.

**Comment by goderbauer** [comment]
On https://codelabs.developers.google.com/codelabs/flutter/#7 search for "Modify the _buildTextComposer method." to find the example above.

**Comment by zoechi** [comment]
Issue moved to [flutter/website #1977](https://github.com/flutter/website/issues/1977) via [**ZenHub**](https://www.zenhub.com/)
