### ISSUE TITLE
No gist was found on CheckboxListTile

### ISSUE THREAD

**Issue by yeasin50** [flutter/flutter#114677]
### Page URL

https://api.flutter.dev/flutter/material/CheckboxListTile-class.html

### Describe the problem

![image](https://user-images.githubusercontent.com/46500228/199797918-c7b27706-e7b9-43f3-903c-312e6014cc78.png)

**Comment by danagbemava-nc** [comment]
Hi @yeasin50, this has been fixed on the master channel. So for you now you can access it using https://master-api.flutter.dev/flutter/material/CheckboxListTile-class.html. 

Closing from here as this has been fixed on master. 

Thank you
