### ISSUE TITLE
UI Codelab: Analyzer complains about MyApp in Tests

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#11469]
Doing the codelab on master (which soon will be the new alpha) gives the following analyzer warning in InteilliJ after step https://codelabs.developers.google.com/codelabs/flutter/#3.

```
error: Undefined class 'MyApp'. (undefined_class at [foo] test/widget_test.dart:15)
```

As this is in a (generated) test, the functionality of the codelab itself is not affected. It's just confusing. 

@LarkAscending

**Comment by LarkAscending** [comment]
See https://github.com/flutter/flutter-intellij/issues/1429
/cc @pq

**Comment by LarkAscending** [comment]
For now, added this note to [Step 3](https://codelabs.developers.google.com/codelabs/flutter/#2)

```If your project includes a test directory that contains the file widget_test.dart, remove this file before continuing.```
