### ISSUE TITLE
google_sign_in: GoogleUserCircleAvatar should support using Icon/Image as placeholder

### ISSUE THREAD

**Issue by namiwang** [flutter/flutter#11461]
This is a straightforward feature request.

Currently `GoogleUserCircleAvatar` only supports an `url` in case the user actually got no avatar.

It would be nice to use a local asset or `Icons.account_circle` for that.

---

Additionally, it provides no solution for the `loading` phase of the avatar, leading to only a black-hole in the first place.

I guess that's another issue, maybe it will get such feature from `flutter_image` in the future?

**Comment by mit-mit** [comment]
Thanks for the suggestion @namiwang. Are you by chance interested in contributing a patch for this?

**Comment by namiwang** [comment]
@mit-mit 

Ah sure, I'd like to dig in and try to do so.

It'd be a great help for me if anybody could "point the way", though. :)

**Comment by mit-mit** [comment]
@goderbauer @collinjackson either of you have some tips?

**Comment by goderbauer** [comment]
You probably want to look at https://github.com/flutter/plugins/blob/master/packages/google_sign_in/lib/widgets.dart#L24 and make it take an [`Image`](https://docs.flutter.io/flutter/widgets/Image-class.html) as a `placeholderPhoto` parameter. You then need to use that image appropriately in the `build` method: https://github.com/flutter/plugins/blob/master/packages/google_sign_in/lib/widgets.dart#L104

You could also use a [`FadeInImage`](https://docs.flutter.io/flutter/widgets/FadeInImage-class.html) to solve your second issue. That one supports showing a placeholder image until the actual target image is loaded.

Hope that helps.

**Comment by namiwang** [comment]
@goderbauer Thanks! It helps a lot!

**Comment by zoechi** [comment]
Sounds like a support request that was solved.
