### ISSUE TITLE
M3 Navigation widgets use wrong ripple

### ISSUE THREAD

**Issue by rares45** [flutter/flutter#114618]
Navigation widgets (NavigationBar and NavigationRail) seem to use a not-spec ripple effect that also is wrongly clipped.

## Steps to Reproduce

1. Create a NavigationBar or NavigationRail 
2. .Hover an item

**Expected results:**
I expected to see an M3 spec ripple on the pill.

This is the [spec](https://m3.material.io/components/navigation-bar/specs#8f59e48a-a2b9-4584-b50d-d24e9e982d04l): 
![image](https://user-images.githubusercontent.com/42469755/199763620-2619b65a-f3aa-4f1a-87cb-424ae3e2516f.png)

**Actual results:** 
![image](https://user-images.githubusercontent.com/42469755/199764848-ae2deb68-e0f0-4cf3-8914-94d8459280d1.png)
As you can see on the third item the ripple is not only behind the "pill" but is behind the entire item, as I said is clipped wrong and it doesn't even go behind the system navigation with the rest of the NavigationBar.

<details>
<summary>To be mentioned</summary>

The exact same problem is present with NavigationRail.
![image](https://user-images.githubusercontent.com/42469755/199766417-c1a03126-23cb-4be8-8d9c-b6b7433af2f2.png)<h6>The dot represents a device camera </h6>

Some apps adapted this design for the ripple, that extends behind the system navigation:
![image](https://user-images.githubusercontent.com/42469755/199767184-1320b36a-59c6-464d-a030-8e4dca3b22ff.png)
And it would be an amazing thing if this could be implemented in some way.

</details>

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        bottomNavigationBar: NavigationBar(
          labelBehavior: NavigationDestinationLabelBehavior.onlyShowSelected,
          selectedIndex: 0,
          destinations: const [
            NavigationDestination(
              icon: Icon(Icons.home),
              label: 'Page 1',
            ),
            NavigationDestination(
              icon: Icon(Icons.abc),
              label: 'Page 2',
            ),
          ],
          onDestinationSelected: (_) {},
        ),
      ),
    );
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel beta, 3.4.0-34.1.pre, on Ubuntu 22.10 5.19.0-23-generic, locale en_GB.UTF-8)
    • Flutter version 3.4.0-34.1.pre on channel beta at /home/rares/.apps/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 71520442d4 (4 weeks ago), 2022-10-05 16:38:28 -0500
    • Engine revision db0cbb2145
    • Dart version 2.19.0 (build 2.19.0-255.2.beta)
    • DevTools version 2.18.0

Checking Android licenses is taking an unexpectedly long time...[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /home/rares/.apps/android-sdk/
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /home/rares/.apps/jetbrains-toolbox/apps/AndroidStudio/ch-0/213.7172.25.2113.9123335/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 15.0.2-1
    • cmake version 3.24.2
    • ninja version 1.11.0
    • pkg-config version 0.29.2

[✓] Android Studio (version 2021.3)
    • Android Studio at /home/rares/.apps/jetbrains-toolbox/apps/AndroidStudio/ch-0/213.7172.25.2113.9123335
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.72.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.52.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 22.10 5.19.0-23-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 107.0.5304.87

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by exaby73** [comment]
## Triage report

I can reproduce this issue. The ripple effect applies to the entire button.

<details>
<summary>Code Sample (same as OP)</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        bottomNavigationBar: NavigationBar(
          labelBehavior: NavigationDestinationLabelBehavior.onlyShowSelected,
          selectedIndex: 0,
          destinations: const [
            NavigationDestination(
              icon: Icon(Icons.home),
              label: 'Page 1',
            ),
            NavigationDestination(
              icon: Icon(Icons.abc),
              label: 'Page 2',
            ),
          ],
          onDestinationSelected: (_) {},
        ),
      ),
    );
  }
}
```

</details>

**Comment by HansMuller** [comment]
Maybe related: https://github.com/flutter/flutter/issues/114301

**Comment by TahaTesser** [comment]
https://github.com/flutter/flutter/issues/114301 is different than this issue.

`NavigationBar` has InkWell that wraps both the label and icon. 

https://github.com/flutter/flutter/blob/d587fe487c0f27bc54898dc89bf07ce0cc7b2a23/packages/flutter/lib/src/material/navigation_bar.dart#L435-L447

![119037004-703d9000-b97f-11eb-9e70-150df794cd71](https://user-images.githubusercontent.com/48603081/201629623-e4c6e395-dd72-47f6-9d4c-372dbe12fcff.gif)



The earliest [version](https://github.com/flutter/flutter/pull/83047) of `NavigationBar` specs has a square ripple

![image](https://user-images.githubusercontent.com/48603081/201629295-441422d2-aa80-4984-8685-8e982a8e3178.png)

 Then some users reported circular splash (It was inconsistent with specs but it was present in native apps and I noticed this in some Android apps too)

 
 
Now that splash is updated and checking Play Store and Google Files navigation bar, I can confirm this latest ripple effect.

![image](https://user-images.githubusercontent.com/48603081/201629413-0c6ffe13-d4c4-4082-985a-7c90a0ae6054.png)

**Comment by TahaTesser** [comment]
@guidezpl 
Do you concur with https://github.com/flutter/flutter/issues/114618#issuecomment-1313395603? If you access to `NavigatorBar` specs history.
I don't have screenshots from the previous specs page to prove it, but I've been following this.

**Comment by guidezpl** [comment]
That's correct @TahaTesser 

In particular, note the changes:
- Label https://m3.material.io/components/navigation-bar/guidelines#935d4e62-b4e8-4d5e-8b87-6a39ec479c85
- Behavior https://m3.material.io/components/navigation-bar/guidelines#935d4e62-b4e8-4d5e-8b87-6a39ec479c85

**Comment by TahaTesser** [comment]
As mentioned, InkWell wraps the icon and label but the new change only shows ripple on the icon. 
I'm working on a fix that matches this behavior. An InkWell that wraps the entire item but shows ripple only on label.


![ezgif com-gif-maker](https://user-images.githubusercontent.com/48603081/201974328-d5f4a50e-9d58-4158-8917-b6721ad4b52c.gif)

**Comment by rydmike** [comment]
Also found this older related issue: https://github.com/flutter/flutter/issues/113870, showing the large ink ripple on `NavigationBar` in Material 3 mode:

![default-navbar-M3](https://user-images.githubusercontent.com/39990307/202193657-3d80bedf-37f3-4b86-828c-615fafa165a1.gif)

The current M3 spec does not show or mention it, nor do native apps that use this navigation bar style have it:

https://m3.material.io/components/navigation-bar/guidelines#bd6c5e81-4699-4652-9e3a-b03aa97b8b4b

![spec-version](https://user-images.githubusercontent.com/39990307/202193812-0f6875c9-e2c1-4595-af0a-b60624bb6896.gif)

**Comment by guidezpl** [comment]
Yeah that M2 style ripple should not be there.

**Comment by TahaTesser** [comment]
@rydmike  
There is some inconsistency as mentioned before.

In the specs, after slowing down frames, I can see there is no ripple

> Yeah that M2 style ripple should not be there.

Both Google Components and Google files show a ripple on the indicator, like this https://github.com/flutter/flutter/issues/114618#issuecomment-1315569567
![ezgif com-gif-maker](https://user-images.githubusercontent.com/48603081/202206133-083c3c65-80ef-45e1-adce-ac7012604a28.gif)


While Play Store doesn't 


![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/48603081/202206144-f9018d55-cbd4-4123-ad20-82ac80f88591.gif)


@guidezpl 

Should we disable ripple just like the specs or add a flag that can disable it? As I want to land a PR, asap :)

**Comment by rydmike** [comment]
Thanks @guidezpl sounds like the obvious choice! 😉 Looking forward to it @TahaTesser! 🔥💙 

OT, but M3 spec compliance related, but concerning Chip: https://github.com/flutter/flutter/issues/115364

**Comment by TahaTesser** [comment]
States [specs](https://m3.material.io/components/navigation-bar/specs#465dd07e-5315-4c9f-8d37-aba92887a693) clearly have ripple in indicator shape. Also while [guidelines](https://m3.material.io/components/navigation-bar/guidelines) page contradicts this. 

To me, it makes sense to have states so that hover and the press are detected.

![image](https://user-images.githubusercontent.com/48603081/202249585-231cd837-c00c-4ff5-adf1-a7fb1226ff1d.png)

Play Store seems broken to me. Having no ripple breaks hover detection as well. Even the cursor is broken on the Play Store, see https://github.com/flutter/flutter/issues/114618#issuecomment-1317105553

**Comment by rares45** [comment]
The PR doesn't seem to fix the entire issue as it also mentions Navigation Rail that has the exact some problem.

**Comment by TahaTesser** [comment]
> The PR doesn't seem to fix the entire issue as it also mentions Navigation Rail that has the exact some problem.

Good catch, this slipped as I was focused on `NavigationBar` when testing, I will update `NavigationRail` in separate issue.
