### ISSUE TITLE
Retry skia perf upload on failure

### ISSUE THREAD

**Issue by cbracken** [flutter/flutter#114635]
In https://ci.chromium.org/ui/p/flutter/builders/prod/Linux_android%20flutter_test_performance/5856/overview we ran into the following infra failure after the test had completed, while uploading results to Skipa Perf.
```
Results to upload to skia perf: {CommitBranch: master, CommitSha: a440c4689fd600a450f0fca0b42c4b76fcfff4ff
, BuilderName: Linux_android flutter_test_performance, NewStatus: Succeeded, ResultData: {without_change_elapsed_time_ms: 2572.0, implementation_change_elapsed_time_ms: 10576.0, interface_change_elapsed_time_ms: 10460.0, with_coverage_time_ms: 2712.0}, BenchmarkScoreKeys: [without_change_elapsed_time_ms, implementation_change_elapsed_time_ms, interface_change_elapsed_time_ms, with_coverage_time_ms]}
Benchmark tags to upload to skia perf: {arch: intel, device_type: Moto G (4), device_version: none, host_type: linux}
Connection closed before full header was received
```

We should consider adding some retry logic to this step in case of a one-off connection error.

**Comment by christopherfujino** [comment]
This is https://flutter.googlesource.com/recipes/+/refs/heads/main/recipes/devicelab/devicelab_drone.py#284 in the recipes, we can use the api.retry.wrap() to retry this https://flutter.googlesource.com/recipes/+/refs/heads/main/recipe_modules/retry/api.py#54

**Comment by ricardoamador** [comment]
Fixed here: https://flutter-review.googlesource.com/c/recipes/+/46661
