### ISSUE TITLE
Add compilation/analyze of samples to CI checks

### ISSUE THREAD

**Issue by fzyzcjy** [flutter/flutter#114600]
For example, when reading https://api.flutter.dev/flutter/material/ThemeExtension-class.html I see:

![image](https://user-images.githubusercontent.com/5236035/199716530-b664ba7c-702a-405f-ab6d-31e77b2f41c5.png)

![image](https://user-images.githubusercontent.com/5236035/199716479-25240d93-c3ca-4f7c-a14e-c1ab4fda14b1.png)

So the official sample does not compile.

If the CI checks all these code samples, this will never happen in a stable release (or even on master branch)

**Comment by goderbauer** [comment]
THese are analyzed and we are adding tests for these now.
