### ISSUE TITLE
Modify 1P releases to branch first and then roll

### ISSUE THREAD

**Issue by khyati82** [flutter/flutter#114626]
This is part of SLSA 1 compliance work as per the roadmap go/flutter-slsa-compliance-roadmap

**Comment by godofredoc** [comment]
@drewroengoogle @keyonghan this is related to the failing branch service.

**Comment by CaseyHillers** [comment]
@itsjustkevin is this still needed? We branch whenever we start a roll, and we tag when a roll has been submitted.

**Comment by godofredoc** [comment]
Yes, this is still needed. Dart-internal builds expect the recipes branch to exist before the engine or flutter branches are created. 

![image](https://user-images.githubusercontent.com/54371434/229636976-24e5458d-7153-4e69-b58d-da1a36a296ff.png)

**Comment by godofredoc** [comment]
Can we remove the branching process to frob tooling and remove from cocoon?

**Comment by CaseyHillers** [comment]
https://github.com/flutter/cocoon/pull/2808 is the cocoon PR to migrate webhook logic to an RPC

Next steps are to update google testing to call the RPC

**Comment by CaseyHillers** [comment]
I sent cl/537938846 for the Google Testing patch

**Comment by CaseyHillers** [comment]
@godofredoc @sealesj this is complete

**Comment by CaseyHillers** [comment]
Reopening as the endpoint is failing due to the recipe commit time not being parsed correctly. I'll send a PR to fix it.
