### ISSUE TITLE
[engine] Missing symbols in embedder_exports.lst

### ISSUE THREAD

**Issue by swift-kim** [flutter/flutter#114657]
The linker script [embedder_exports.lst](https://github.com/flutter/engine/blob/main/shell/platform/embedder/embedder_exports.lst) has recently been added to the engine repo but it doesn't export the following symbols declared in [embedder.h](https://github.com/flutter/engine/blob/main/shell/platform/embedder/embedder.h):

- `kFlutterSemanticsNodeIdBatchEnd`
- `kFlutterSemanticsCustomActionIdBatchEnd`

My custom embedder implementation uses the symbol `kFlutterSemanticsNodeIdBatchEnd` and is failing build for this reason.

https://github.com/flutter-tizen/embedder/actions/runs/3384058505/jobs/5620589180

I think `kFlutter*;` should be added to the global section in the linker script. Also maybe the issue https://github.com/flutter/flutter/issues/106453 can be closed now.

cc @jason-simmons

**Comment by loic-sharma** [comment]
FYI, I'd recommend moving your embedder to the new update semantics embedder API introduced by https://github.com/flutter/engine/pull/37129. Here's the relevant changes for the macOS embedder: https://github.com/flutter/engine/pull/37404.

**Comment by swift-kim** [comment]
@loic-sharma Thank you for the information. We will check and make updates if necessary (maybe after the next Flutter stable release). cc @wanchao-xu
