### ISSUE TITLE
ci.yaml validation stuck pending in PR check

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#114633]
Has been stuck awhile...
https://github.com/flutter/flutter/pull/114099

![Screen Shot 2022-11-03 at 11 15 01 AM](https://user-images.githubusercontent.com/682784/199802309-a2760777-2c0e-4f8c-9ab9-8d905c42d8a4.png)

cc @vashworth

**Comment by keyonghan** [comment]
Reset the pre-submit checks to unblock.

Looking through the backend, there were no useful logs related to this stuck.
If the `ci.yaml validation` check was created correctly, we should be able to see `If this check is stuck pending, push an empty commit to retrigger the checks` in the `Details` link.

My guess is it hit uncaught exception when creating the check run: https://github.com/flutter/cocoon/blob/main/app_dart/lib/src/service/scheduler.dart#L285

**Comment by ricardoamador** [comment]
This issue duplicates: https://github.com/flutter/flutter/issues/114087
