### ISSUE TITLE
Assets sometimes aren't bundled

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#1146]
I frequently find that when I'm running stocks, random assets will say (in the logs):
```
[WARNING:asset_bundle_impl.cc(45)] Requested asset 'action/drawable-xxhdpi/ic_backup_black_24dp.png' does not exist.
```
...and not actually render.

It seems very intermittent. It's also not always the same icons.

**Comment by Hixie** [comment]
This seems to happen more for icons that I didn't try to load early in the app's lifetime. It's almost like there's a deadline and any images not loaded before that deadline can't be loaded.

**Comment by HansMuller** [comment]
I don't have anything to add except that I run into this all the time as well. In my experience it's intermittent and unpredictable.

**Comment by krisgiesing** [comment]
I believe this was fixed by https://github.com/flutter/engine/pull/2360.

**Comment by krisgiesing** [comment]
Closing as I can no longer repo, assigning to Jason for credit :)
