### ISSUE TITLE
Error: Target of URI doesn't exist: 'package:food_recipe/models/recipe.dart' 

### ISSUE THREAD

**Issue by RenaSki** [flutter/flutter#114665]
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. ... 
3. ... 

**Expected results:** 
I would like to import 'package:food_recipe/models/recipe.dart' 
**Actual results:** 
I get an error that says the Target of URI doesn't exist: 'package:food_recipe/models/recipe.dart' when I import it. How should I fixt it?

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by darshankawar** [comment]
> I get an error that says the Target of URI doesn't exist: 'package:food_recipe/models/recipe.dart'

This probably indicates your pub cache could be corrupted. You may try `flutter pub cache repair` followed by `flutter clean`.
Closing from here. Please check on support channels like StackOverflow for similar issue resolution.
