### ISSUE TITLE
Regression in platform_channels_benchmarks_ios

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#114697]
SkiaPerf is reporting a regression in the `platform_channel_basic_standard_2host_large` metric in the `platform_channels_benchmarks_ios` benchmark:

https://flutter-flutter-perf.skia.org/e/?begin=1667407387&end=1667497579&keys=X5e47c6ddc02a34ef472402b64fcb11b8&num_commits=50&request_type=1&xbaroffset=31889

The associated commit is the engine roll at https://github.com/flutter/flutter/pull/114534. That commit contains a Skia roll, which is likely unrelated and an ARC migration change https://github.com/flutter/engine/pull/37219.

cc @cyanglaz @jmagman @gaaclarke

**Comment by cyanglaz** [comment]
I guess because in https://github.com/flutter/engine/pull/37219 we changed to copying everything, the performance would expertly go down. I'm going to revert it first and try locally if there are anything besides copying reduces the performance.
