### ISSUE TITLE
[Platform- Windows] FileSystemException: Cannot create file path, OS Error: The system cannot find the file specified., errno = 2

### ISSUE THREAD

**Issue by AniketMalik** [flutter/flutter#114609]
## Description
I created a Windows application which throws FileSystemException on a device but works fine with others window's devices.
Please see the screenshot of the error attached below:

![Capture 2](https://user-images.githubusercontent.com/33630047/199736952-86410d20-cc77-4efb-b800-42acaf8b43d6.PNG)
![Capture](https://user-images.githubusercontent.com/33630047/199736964-e40f6d1a-c702-46d2-830f-2fee0a3248bb.PNG)

## Device Specification
![Capture 4](https://user-images.githubusercontent.com/33630047/199737515-6784c1e2-f52a-4400-8a76-500a9e538dd3.PNG)

**Comment by exaby73** [comment]
Hi @AniketMalik 
I see there's an open issue addressing the case you described https://github.com/flutter/flutter/issues/65242
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by exaby73** [comment]
Can you please provide a [complete and minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)?

**Comment by AniketMalik** [comment]
The file export function uses the following code:

```dart
      String? filePath = await FilePicker.platform.saveFile(
        dialogTitle: 'Save to',
        fileName: 'saved_templates.hive',
      );

      if (isBlank(filePath)) {
        return;
      }
      final File savedTemplatesBoxFile = File(boxPath!);
      final File backupFile = File(filePath!);
      if (await backupFile.exists()) {
      } else {
        await backupFile.create();
      }
      // Saved templates box file COPY TO backup file
      await savedTemplatesBoxFile.copy(backupFile.path);
```

It works perfectly on all the other windows machines while not working on the one shared above.

**Comment by AniketMalik** [comment]
The issue was caused by windows defender as it blocked the access to the file system.
