### ISSUE TITLE
[Impeller] Verify transition animations with custom fragment program.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#114652]
Impeller implements the fragment program API. At the last weekly, it was an action item to verify custom transition animations using fragment programs with the Impeller backend. This is a tracking bug for that verification pass.

**Comment by chinmaygarde** [comment]
@zanderso said he was going to attempt this. Zach, if you don't have the cycles for this, feel free to reassign! Just want to make sure we don't miss this.

**Comment by chinmaygarde** [comment]
@zanderso Cleaning up issues on the dashboard. I recall this as a being done. May I close it?

**Comment by zanderso** [comment]
Yes, this was done.
