### ISSUE TITLE
Garbage logs when using Flutter web with IntelliJ + Breakpoints.

### ISSUE THREAD

**Issue by Pacane** [flutter/flutter#114659]
Using Flutter Web 3.3.4 and IntelliJ 2022.2 on MacOS with the Flutter plugin 70.2.5, also an issue with 71.0.5.

After adding a breakpoint and reaching an exception, I keep getting tons of lines of logs in my IntelliJ console saying

```

Locations: No module for http://localhost:54124/dart_sdk.js
Locations: No module for http://localhost:54124/dart_sdk.js
Locations: No module for http://localhost:54124/dart_sdk.js
Locations: No module for http://localhost:54124/dart_sdk.js
Locations: No module for http://localhost:54124/dart_sdk.js
Locations: No module for http://localhost:54124/dart_sdk.js
Locations: No module for http://localhost:54124/dart_sdk.js
Locations: No module for http://localhost:54124/dart_sdk.js
Locations: No module for http://localhost:54124/dart_sdk.js
Locations: No module for http://localhost:54124/dart_sdk.js
Locations: No module for http://localhost:54124/dart_sdk.js
Locations: No module for http://localhost:54124/dart_sdk.js
Locations: No module for http://localhost:54124/dart_sdk.js
Locations: No module for http://localhost:54124/dart_sdk.js
Locations: No module for http://localhost:54124/dart_sdk.js
Locations: No module for http://localhost:54124/dart_sdk.js
Locations: No module for http://localhost:54124/dart_sdk.js
```

and so on.

The project was launched using IntelliJ's run flutter run configuration, using Chrome (web) device.

edit: I've been able to trigger this more often if I trigger an overflow error in my Flutter app, while watching the logs / have a breakpoint in the same file as the widget overflowing.

it's not 100% reproducible, but I've been able to reproduce it quite consistently in the past days.

<img width="864" alt="image" src="https://user-images.githubusercontent.com/2762440/199869679-ce7771b4-63a3-4111-806b-43443f865817.png">

**Comment by Pacane** [comment]
could be a dupe of https://github.com/flutter/flutter/pull/112887/files possibly? Just found out about this...

**Comment by darshankawar** [comment]
@Pacane 
That is correct. This is already fixed and available on latest master, beta and I believe on stable as well. See [this](https://github.com/flutter/flutter/issues/111136#issuecomment-1267636384) comment.

If you are not on latest versions, please upgrade to see the fix. Closing for now, as this is already fixed.
