### ISSUE TITLE
Cant wrap my class inside my position widget

### ISSUE THREAD

**Issue by PBamford9** [flutter/flutter#114681]
I created a Class that has a listview, but as soon as i call it in my position widget on the home page, there's no code error but it gives me the followimg damn errors in my console. 

```
''RenderCustomMultiChildLayoutBox object was given an infinite size during layout",
 ''RenderPhysicalModel object was given an infinite size during layout.''
_RenderInkFeatures object was given an infinite size during layout.
RRect argument contained a NaN value.
'dart:ui/painting.dart':
Failed assertion: line 37 pos 10: '<optimized out>'
```

here is the position widget how it is displayed:
```
Positioned(
                top: 575,
                  child: LandingPage(),
              ),
```

landing page is the class and here is its code
```
import 'package:flutter/material.dart';
class LandingPage extends StatefulWidget {
  const LandingPage({Key? key}) : super(key: key);

  @override
  State<LandingPage> createState() => _LandingPageState();
}

class _LandingPageState extends State<LandingPage> {
  List<Map<String, dynamic>> matches=[
    {
      "type":"LIVE",
      "teams":{
        "teama":"PWD Bamenda",
        "teamb":"Coton sport",
        "teamascore":"5",
        "teambscore":"2",
      },
    },
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Container(
        //margin: EdgeInsets.only(top: 300),
        width: 260,
        height: 220,
        child: ListView.builder(
          scrollDirection: Axis.horizontal,
          itemCount: matches.length,
          itemBuilder: (context, index){
            return Container(
              margin: EdgeInsets.only(right: 15,top: 10, left: 15, bottom: 20),
              padding: EdgeInsets.all(14),
              decoration: BoxDecoration(
                color: Colors.red,
                borderRadius: BorderRadius.circular(17)
              ),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  SizedBox(
                      width: 65,
                      height: 31,
                      child: ElevatedButton(
                        onPressed: (){},
                          style: ElevatedButton.styleFrom(
                              backgroundColor: Colors.green.shade900,
                              shape: RoundedRectangleBorder(
                                borderRadius: BorderRadius.circular(7),
                              )
                          ),
                          child: Text('${matches[index]['type']}',style: TextStyle(
                            color: Colors.yellow,
                            fontSize: 14,
                          ),
                          )
                      )
                  ),
                  SizedBox(height: 10,),
                  Row(
                    mainAxisAlignment: MainAxisAlignment.start,
                    children: [
                      Image.asset('assets/pwde.png', height: 50, width: 50,),
                      SizedBox(width: 26,),
                      Text('VS', style: TextStyle(
                        color: Colors.green.shade900,
                      ),),
                      SizedBox(width: 26,),
                      Image.asset('assets/coton.png', height: 50, width: 50,),

                    ],
                  ),
                  SizedBox(height: 10),
                  Row(
                    children: [
                      Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          Text('${matches[index]['teams']['teama']}', style: TextStyle(
                            color: Colors.yellow,
                            fontSize: 15
                          ),),
                          SizedBox(height: 10),
                          Text('${matches[index]['teams']['teamb']}',style: TextStyle(
                              color: Colors.yellow,
                              fontSize: 15
                          ),),
                        ],
                      ),
                  SizedBox(width: 60),
                  Column(
                    children: [
                      Text('${matches[index]['teams']['teamascore']}',style: TextStyle(
                          color: Colors.yellow,
                          fontSize: 15
                      ),),
                      SizedBox(height: 10),
                      Text('${matches[index]['teams']['teambscore']}',style: TextStyle(
                          color: Colors.yellow,
                          fontSize: 15
                      ),),
                      ],
                     ),
                    ]
                  ),

                ],
              ),
            );
          },
        ),
      ),
    );
  }
}

```

**Comment by darshankawar** [comment]
@PBamford9 
Can you provide `flutter doctor -v` ? Also, where in your provided code, are you using `Positioned` widget ?

**Comment by PBamford9** [comment]
Good, The positioned widget code is in my homepage code, and i used it around line 137, so i simply called the landing page as a child into the positioned widget and had those series of errors.

here is the code 

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_projects/Pages/home/homee.dart';
import 'package:flutter_projects/Pages/home/widgets/fixture_card.dart';

class Homepage extends StatefulWidget {
  const Homepage({Key? key}) : super(key: key);

  @override
  State<Homepage> createState() => _HomepageState();
}

class _HomepageState extends State<Homepage> {
  var matches=[
    {
      "type":"live",
       "teams":{
        "teama":"pwd bamenda",
         "teamb":"coton sport",
       },
    },
    {
      "type":"Offline",
      "teams":{
        "teama":"bafut boys",
        "teamb":"douala sport",
      },
    }
  ];
 matchloop(){
   for(var i=0;i<matches.length;i++){
     print(matches[i]['type']);
   }
 }

  @override
  Widget build(BuildContext context) {
    /*SystemChrome.setSystemUIOverlayStyle(SystemUiOverlayStyle(
      statusBarColor: Colors.transparent,
    ));*/
    return Scaffold(
      body:
        SingleChildScrollView(
          child: Stack(
            children: [
              Column(
                children: [
                  Container(
                    height: MediaQuery.of(context).size.height -340,
                    width: MediaQuery.of(context).size.width ,
                    decoration: BoxDecoration(
                      borderRadius: BorderRadius.only(
                        bottomRight: Radius.circular(35),
                        bottomLeft: Radius.circular(35)
                      ),
                      //color: Colors.amber
                      image: DecorationImage(
                        image: AssetImage('assets/Japoma9.jpg'),
                        fit: BoxFit.cover,
                        colorFilter:  ColorFilter.mode(Colors.black.withOpacity(0.4),
                        BlendMode.darken
                        )
                      )
                    ),
                    child: Padding(
                      padding: const EdgeInsets.fromLTRB(8.0,0,0,0),
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          SizedBox(height: 90,),
                          Text('Get to know all Stadiums, in Cameroon.', style: TextStyle(
                              color: Colors.amberAccent,
                              fontSize: 34,
                              fontWeight: FontWeight.w500
                          )
                          ),
                          SizedBox(height: 20,),
                          Text('Why only Knowing?. RESERVE a stadium now \nand get to feel the \nsensation of an activity in the stadium.',
                              style: TextStyle(
                                color: Colors.white,
                                fontWeight: FontWeight.w500,
                                fontSize: 19,
                              )
                          ),
                        ],
                      ),
                    ),
                  ),
                  SizedBox(
                    height: MediaQuery.of(context).size.height,
                  ),
                ],
              ),
              Positioned(
                top: 477,
                right: 20,
                child: Column(
                  mainAxisAlignment: MainAxisAlignment.end,
                  children: [
                    //SizedBox(height: 124,),
                    SizedBox(
                      width: 150,
                      height: 50,
                      child: ElevatedButton(
                        onPressed: () {
                          matchloop();
                        },
                        style: ElevatedButton.styleFrom(
                            backgroundColor: Colors.red,
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(15),
                            )
                        ),
                        child: Text('Reserve now', style: TextStyle(
                          color: Colors.yellow,
                          fontSize: 19,
                        )
                        ),
                      ),
                    ),
                  ],
                ),
              ),
              //start fixture section
              Positioned(
                top: 520,
                left: 25,
                child: Text('Fixtures', style: TextStyle(
                  color: Colors.black,
                  fontWeight: FontWeight.w700,
                  letterSpacing: 0.5,
                  fontSize: 25
                )
                ),
              ),
              SizedBox(width: 15,),
              Positioned(
                top: 575,
                  child: LandingPage(),
              ),
              Positioned(
                top: 810,
                left: 25,
                child: Text('Latest', style: TextStyle(
                    color: Colors.black,
                    fontWeight: FontWeight.w700,
                    letterSpacing: 0.5,
                    fontSize: 25
                )
                ),
              ),
            ],
          ),
        ),
    );
  }
}

**Comment by darshankawar** [comment]
@PBamford9 
Looking at the code sample, I see that you have used `Positioned` widget inside `Stack`, the Stack widget doesn't know how big to expand and hence you are getting the reported error ie, `RenderCustomMultiChildLayoutBox object was given an infinite size during layout.`
See [this](https://stackoverflow.com/a/69184063) solution and check if it helps in your case.
