### ISSUE TITLE
[go_router] `GoRouter` should expose path, parameters and query parameters for cases where `BuildContext` is inaccessible

### ISSUE THREAD

**Issue by ahmednfwela** [flutter/flutter#114642]
I am using a controller-based architecture with a dependency injection system (using `get_it`) and I have controllers/services that need to listen to and access the current router state (path + parameters + query parameters) based entirely on the `GoRouter` instance, and without having a way to get `BuildContext`.
in v5.1.3 this is currently not possible.

There is a hacky workaround for this tho:

1. add listener to `goRouter`
2. on listener callback access the `RouteMatch` using `goRouter.routerDelegate.currentConfiguration.last` (notice that RouteMatch isn't exposed in the library, so you have to `import 'package:go_router/src/match.dart';`)
3. now you can access `RouteMatch.decodedParams`, `queryParams` and `extra`

**Comment by chunhtai** [comment]
Do you have some code that how would you want to use get_it with go_router?

**Comment by ahmednfwela** [comment]
@chunhtai I have updated the original question for more clarification

**Comment by ahmednfwela** [comment]
> Do you have some code that how would you want to use get_it with go_router?

I am using `injectable` to register `GoRouter`, sample: 
```dart
@module
abstract class RegisterModule {
  @lazySingleton
  GoRouter getRouter(GoRouterRefreshService goRouterRefreshService) => GoRouter(
        initialLocation: AppRouteNames.initialRoute,
        refreshListenable: goRouterRefreshService,
        routes: [
          //routes...
        ],
      );
}
```

**Comment by ahmednfwela** [comment]
@chunhtai I see that in version 9.0.0 the location parameter got removed, and also you can no longer listen to `GoRouter`, so it breaks my workaround.

this makes `GoRouter` unusable without `BuildContext` at the moment (since in the [migration guide](https://flutter.dev/go/go-router-v9-breaking-changes), it's stated that the workaround might change in the future).

**Comment by chunhtai** [comment]
I created a pr to open up internal classes like GoRouterDelegate and RouteMatchList and make them a stable API. This is something I have been planning to do for a while.
https://github.com/flutter/packages/pull/4380

The workaround in migration guide will be stable, and I will update the migration guide after it merge

**Comment by chunhtai** [comment]
v9.0.1 is landed and migration guide updated
