### ISSUE TITLE
`ListTile` dartpad examples throw "Error loading gist"

### ISSUE THREAD

**Issue by TahaTesser** [flutter/flutter#114795]
https://api.flutter.dev/flutter/material/ListTile-class.html

![Screenshot 2022-11-07 at 10 50 06](https://user-images.githubusercontent.com/48603081/200266364-449e57e3-5365-40eb-952f-589224b8271f.png)

This seems to work fine on [master](https://master-api.flutter.dev/flutter/material/ListTile-class.html) APIs but fails to load gist itself on stable.

**Comment by TahaTesser** [comment]
cc: @gspencergoog

**Comment by gspencergoog** [comment]
cc @domesticmouse

**Comment by domesticmouse** [comment]
I'm guessing the gist configured in the API docs doesn't exist? What is the target gist ID?

/cc @johnpryan

**Comment by domesticmouse** [comment]
Looks to me like the URL of the DartPad embed is https://dartpad.dev/embed-flutter.html?split=60&run=true&null_safety=true&sample_id=material.ListTile.5&sample_channel=master

@johnpryan should this work? I don't see a gist ID in this URL.

**Comment by johnpryan** [comment]
This is using the `sample_id` parameter, not the `id` paramter. We should probably double check that there's a sample called `material.ListTile.5` on the master channel.

**Comment by domesticmouse** [comment]
It's working on master, but failing on stable. I'm guessing there isn't a sample called `material.ListTile.5` in the stable SDK at this point?

**Comment by gspencergoog** [comment]
You're correct, there isn't one being generated on the master channel.

It only generates these on master:

```
material.ListTile.2.dart
material.ListTile.2.json
material.ListTile.3.dart
material.ListTile.3.json
material.ListTile.7.dart
material.ListTile.7.json
material.ListTile.8.dart
material.ListTile.8.json
material.ListTile.selected.1.dart
material.ListTile.selected.1.json
```

I assume this is because something changed in those examples.

This is where our use of a single location for the samples breaks down, and it would be good to have the IDE plugins and Dartpad have a way to look in multiple places for samples (both stable and master, for instance).

I wonder if this is related to @godofredoc's recent changes to how docs are published: perhaps we used to merge the snippets directory at the top of the docs tree, and now we replace it?

**Comment by godofredoc** [comment]
This is probably related to my changes. API documentation was changed to be built on post-submit of the release branch candidates and to only post-process the version header/footer during the release process to stable.

@gspencergoog is there some code in the documentation generation script that I can change to make flutter-candidate-* branches ~= stable?

**Comment by gspencergoog** [comment]
@domesticmouse I also still think there's something wrong with the channel selection in Dartpad: when I go to [the `MenuAnchor` example](https://master-api.flutter.dev/flutter/material/MenuAnchor-class.html#material.MenuAnchor.1), I expect that the samples will work (they were added September 28th, more than a month ago), but they still have errors related to missing classes that were added at the same time, but aren't in stable yet.

The iframe on that page is:
```html
<iframe class="snippet-dartpad" src="https://dartpad.dev/embed-flutter.html?split=60&amp;run=true&amp;null_safety=true&amp;sample_id=material.MenuAnchor.1&amp;sample_channel=master">
</iframe>
```

And if I go directly to [https://dartpad.dev/embed-flutter.html?split=60&run=true&null_safety=true&sample_id=material.MenuAnchor.1&amp;sample_channel=master](https://dartpad.dev/embed-flutter.html?split=60&amp;run=true&amp;null_safety=true&amp;sample_id=material.MenuAnchor.1&amp;sample_channel=master), it fails to run.

**Comment by gspencergoog** [comment]
@godofredoc  and I are going to chat this afternoon about the publishing part.

**Comment by domesticmouse** [comment]
Im guessing the DartPad embed front end doesn't understand channels.

**Comment by johnpryan** [comment]
@gspencergoog there are two query parameters, `sample_channel` is the the channel to load the sample from, and `channel` is the channel to use for compilation. Adding a `channel=master` parameter fixed it for me:

https://dartpad.dev/embed-flutter.html?split=60&run=true&null_safety=true&sample_id=material.MenuAnchor.1&sample_channel=master&channel=master

**Comment by gspencergoog** [comment]
Ahh, OK.  I'll see if I can add that parameter to the docs generation.

**Comment by godofredoc** [comment]
Fix for processing release candidate branch api docs as stable: https://flutter-review.git.corp.google.com/c/recipes/+/35881

**Comment by gspencergoog** [comment]
This appears to be fixed now.

**Comment by TahaTesser** [comment]
This doesn't seem to be fixed 
https://master-api.flutter.dev/flutter/material/ListTile-class.html

![Screenshot 2022-12-14 at 17 25 23](https://user-images.githubusercontent.com/48603081/207636942-cb06f9db-3096-4d20-9de0-4ec97027d934.png)

and now `NavigationDrawer` has the same issue.
https://master-api.flutter.dev/flutter/material/NavigationDrawer-class.html

![Screenshot 2022-12-14 at 17 19 47](https://user-images.githubusercontent.com/48603081/207637084-1e9eaea3-6477-41a1-bc72-e930d1c8350b.png)

**Comment by domesticmouse** [comment]
Please retry, both are working for me.

**Comment by TahaTesser** [comment]
Wow, they're working now. Something fixed?

When I reopened the issue my colleague reproduced the problem as well from a different location.

**Comment by domesticmouse** [comment]
There is an inherent probabilistic nature to DartPad. Especially `master` channel.
