### ISSUE TITLE
Would like to support saving offline crashes for latter reporting with Sentry

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#11478]
We don't need to necessarily write this patch ourselves, but it's likely to be a common request when attempting to do crash reporting.  FYI @yjbanov 

Currently Posse is using Sentry and does not have this support. FYI @KevinTheGray

**Comment by yjbanov** [comment]
`SentryClient` takes a custom [`Client httpClient`](https://github.com/flutter/sentry/blob/6230c79281df215b6b819f4b60fae0930df5b446/lib/sentry.dart#L59). You can implement one (or find in pub, if one exists) that stores reports locally and returns success right away. Of course, if we want implement such client ourselves, that's fine too.

**Comment by Hixie** [comment]
Closing as something we are not likely to provide as a first-party offering, but that is already possible.
We'd accept patches to enable this, though.
