### ISSUE TITLE
showBottomSheet over bottomNavigationBar

### ISSUE THREAD

**Issue by a7mad911** [flutter/flutter#114749]
when i use showBottomSheet i want it to cover the bottomNavigationBar and FAB
also the FAB position change as pic show
![WhatsApp Image 2022-11-05 at 5 17 29 PM](https://user-images.githubusercontent.com/61091816/200124565-a072e93e-8335-4d1a-8954-432554d51796.jpeg)

i dont want to use showModalBottomSheet because i want the user to interact with the map

**Comment by darshankawar** [comment]
@a7mad911 
Your question is better suited for support channels like StackOverflow, so please ask the same there for existing solutions.
Closing from here.
