### ISSUE TITLE
flutter create throws error

### ISSUE THREAD

**Issue by Iammitarth** [flutter/flutter#114754]
$ flutter create my_app1
Running "flutter pub get" in flutter_tools...                       3.4s
Creating project my_app1...

Oops; flutter has exited unexpectedly: "FileSystemException: Cannot open file, path = 'C:\Users\87504\Development\sdks\flutter\packages\flutter_tools\templates\template_manifest.json' (OS Error: The system cannot find the path specified.
, errno = 3)".
A crash report has been written to C:\Users\87504\Desktop\New folder\flutter_03.log.
This crash may already be reported. Check GitHub for similar crashes.
https://github.com/flutter/flutter/issues?q=is%3Aissue+FileSystemException%3A+Cannot+open+file%2C+path+%3D+%27C%3A%5CUsers%5C87504%5CDevelopment%5Csdks%5Cflutter%5Cpackages%5Cflutter_tools%5Ctemplates%5Ctemplate_manifest.json%27+%28OS+Error%3A+The+system+cannot+find+the+path+specified.%0D%0A%2C+errno+%3D+3%29

To report your crash to the Flutter team, first read the guide to filing a bug.
https://flutter.dev/docs/resources/bug-reports

Create a new GitHub issue by pasting this link into your browser and completing the issue template. Thank you!
https://github.com/flutter/flutter/issues/new?title=%5Btool_crash%5D+FileSystemException%3A+Cannot+open+file%2C+OS+Error%3A+The+system+cannot+find+the+path+specified.%0D%0A%2C+errno+%3D+3&body=%23%23+Command%0A%60%60%60%0Aflutter+create+my_app1%0A%60%60%60%0A%0A%23%23+Steps+to+Reproduce%0A1.+...%0A2.+...%0A3.+...%0A%0A%23%23+Logs%0AFileSystemException%3A+Cannot+open+file%2C+OS+Error%3A+The+system+cannot+find+the+path+specified.%0D%0A%2C+errno+%3D+3%0A%60%60%60%0A%230++++++_File.throwIfError+%28dart%3Aio%2Ffile_impl.dart%3A635%3A7%29%0A%231++++++_File.openSync+%28dart%3Aio%2Ffile_impl.dart%3A479%3A5%29%0A%232++++++_File.readAsBytesSync+%28dart%3Aio%2Ffile_impl.dart%3A539%3A18%29%0A%233++++++_File.readAsStringSync+%28dart%3Aio%2Ffile_impl.dart%3A584%3A18%29%0A%234++++++ForwardingFile.readAsStringSync+%28package%3Afile%2Fsrc%2Fforwarding%2Fforwarding_file.dart%3A96%3A16%29%0A%235++++++ErrorHandlingFile.readAsStringSync.%3Canonymous+closure%3E+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Ferror_handling_io.dart%3A222%3A22%29%0A%236++++++_runSync+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Ferror_handling_io.dart%3A597%3A14%29%0A%237++++++ErrorHandlingFile.readAsStringSync+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Ferror_handling_io.dart%3A221%3A12%29%0A%238++++++CreateBase._computeTemplateManifest+%28package%3Aflutter_tools%2Fsrc%2Fcommands%2Fcreate_base.dart%3A690%3A37%29%0A%239++++++CreateBase._templateManifest+%28package%3Aflutter_tools%2Fsrc%2Fcommands%2Fcreate_base.dart%3A677%3A43%29%0A%2310+++++CreateBase._templateManifest+%28package%3Aflutter_tools%2Fsrc%2Fcommands%2Fcreate_base.dart%29%0A%2311+++++CreateBase.renderMerged+%28package%3Aflutter_tools%2Fsrc%2Fcommands%2Fcreate_base.dart%3A486%3A25%29%0A%2312+++++CreateBase.generateApp+%28package%3Aflutter_tools%2Fsrc%2Fcommands%2Fcreate_base.dart%3A511%3A29%29%0A%2313+++++CreateCommand.runCommand+%28package%3Aflutter_tools%2Fsrc%2Fcommands%2Fcreate.dart%3A314%3A37%29%0A%3Casynchronous+suspension%3E%0A%2314+++++FlutterCommand.run.%3Canonymous+closure%3E+%28package%3Aflutter_tools%2Fsrc%2Frunner%2Fflutter_command.dart%3A1209%3A27%29%0A%3Casynchronous+suspension%3E%0A%2315+++++AppContext.run.%3Canonymous+closure%3E+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Fcontext.dart%3A150%3A19%29%0A%3Casynchronous+suspension%3E%0A%2316+++++CommandRunner.runCommand+%28package%3Aargs%2Fcommand_runner.dart%3A209%3A13%29%0A%3Casynchronous+suspension%3E%0A%2317+++++FlutterCommandRunner.runCommand.%3Canonymous+closure%3E+%28package%3Aflutter_tools%2Fsrc%2Frunner%2Fflutter_command_runner.dart%3A281%3A9%29%0A%3Casynchronous+suspension%3E%0A%2318+++++AppContext.run.%3Canonymous+closure%3E+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Fcontext.dart%3A150%3A19%29%0A%3Casynchronous+suspension%3E%0A%60%60%60%0A%60%60%60%0A%5B%E2%9C%93%5D+Flutter+%28Channel+stable%2C+3.3.7%2C+on+Microsoft+Windows+%5BVersion+10.0.19044.2130%5D%2C+locale+en-IN%29%0A++++%E2%80%A2+Flutter+version+3.3.7+on+channel+stable+at+C%3A%5CUsers%5C87504%5CDevelopment%5Csdks%5Cflutter%0A++++%E2%80%A2+Upstream+repository+https%3A%2F%2Fgithub.com%2Fflutter%2Fflutter.git%0A++++%E2%80%A2+Framework+revision+e99c9c7cd9+%284+days+ago%29%2C+2022-11-01+16%3A59%3A00+-0700%0A++++%E2%80%A2+Engine+revision+857bd6b74c%0A++++%E2%80%A2+Dart+version+2.18.4%0A++++%E2%80%A2+DevTools+version+2.15.0%0A%0A%5B%E2%9C%93%5D+Android+toolchain+-+develop+for+Android+devices+%28Android+SDK+version+33.0.0%29%0A++++%E2%80%A2+Android+SDK+at+C%3A%5CUsers%5C87504%5CAppData%5CLocal%5CAndroid%5Csdk%0A++++%E2%80%A2+Platform+android-33%2C+build-tools+33.0.0%0A++++%E2%80%A2+Java+binary+at%3A+C%3A%5CProgram+Files%5CAndroid%5CAndroid+Studio%5Cjre%5Cbin%5Cjava%0A++++%E2%80%A2+Java+version+OpenJDK+Runtime+Environment+%28build+11.0.13%2B0-b1751.21-8125866%29%0D%0A++++%E2%80%A2+All+Android+licenses+accepted.%0A%0A%5B%E2%9C%93%5D+Chrome+-+develop+for+the+web%0A++++%E2%80%A2+Chrome+at+C%3A%5CProgram+Files%5CGoogle%5CChrome%5CApplication%5Cchrome.exe%0A%0A%5B%E2%9C%97%5D+Visual+Studio+-+develop+for+Windows%0A++++%E2%9C%97+Visual+Studio+not+installed%3B+this+is+necessary+for+Windows+development.%0A++++++Download+at+https%3A%2F%2Fvisualstudio.microsoft.com%2Fdownloads%2F.%0A++++++Please+install+the+%22Desktop+development+with+C%2B%2B%22+workload%2C+including+all+of+its+default+components%0A%0A%5B%E2%9C%93%5D+Android+Studio+%28version+2021.3%29%0A++++%E2%80%A2+Android+Studio+at+C%3A%5CProgram+Files%5CAndroid%5CAndroid+Studio%0A++++%E2%80%A2+Flutter+plugin+can+be+installed+from%3A%0A++++++%F0%9F%94%A8+https%3A%2F%2Fplugins.jetbrains.com%2Fplugin%2F9212-flutter%0A++++%E2%80%A2+Dart+plugin+can+be+installed+from%3A%0A++++++%F0%9F%94%A8+https%3A%2F%2Fplugins.jetbrains.com%2Fplugin%2F6351-dart%0A++++%E2%80%A2+Java+version+OpenJDK+Runtime+Environment+%28build+11.0.13%2B0-b1751.21-8125866%29%0D%0A%0A%5B%E2%9C%93%5D+VS+Code+%28version+1.71.2%29%0A++++%E2%80%A2+VS+Code+at+C%3A%5CUsers%5C87504%5CAppData%5CLocal%5CPrograms%5CMicrosoft+VS+Code%0A++++%E2%80%A2+Flutter+extension+can+be+installed+from%3A%0A++++++%F0%9F%94%A8+https%3A%2F%2Fmarketplace.visualstudio.com%2Fitems%3FitemName%3DDart-Code.flutter%0A%0A%5B%E2%9C%93%5D+VS+Code+%28version+1.72.0-insider%29%0A++++%E2%80%A2+VS+Code+at+C%3A%5CUsers%5C87504%5CAppData%5CLocal%5CPrograms%5CMicrosoft+VS+Code+Insiders%0A++++%E2%80%A2+Flutter+extension+can+be+installed+from%3A%0A++++++%F0%9F%94%A8+https%3A%2F%2Fmarketplace.visualstudio.com%2Fitems%3FitemName%3DDart-Code.flutter%0A%0A%5B%E2%9C%93%5D+Connected+device+%283+available%29%0A++++%E2%80%A2+Windows+%28desktop%29+%E2%80%A2+windows+%E2%80%A2+windows-x64++++%E2%80%A2+Microsoft+Windows+%5BVersion+10.0.19044.2130%5D%0A++++%E2%80%A2+Chrome+%28web%29++++++%E2%80%A2+chrome++%E2%80%A2+web-javascript+%E2%80%A2+Google+Chrome+106.0.5249.91%0A++++%E2%80%A2+Edge+%28web%29++++++++%E2%80%A2+edge++++%E2%80%A2+web-javascript+%E2%80%A2+Microsoft+Edge+107.0.1418.35%0A%0A%5B%E2%9C%93%5D+HTTP+Host+Availability%0A++++%E2%80%A2+All+required+HTTP+hosts+are+available%0A%0A%21+Doctor+found+issues+in+1+category.%0A%0A%60%60%60%0A%0A%23%23+Flutter+Application+Metadata%0ANo+pubspec+in+working+directory.%0A&labels=tool%2Csevere%3A+crash

whenever i try to create app it shows this

**Comment by darshankawar** [comment]
Let's track this in https://github.com/flutter/flutter/issues/114755 as it has stacktrace.
Closing this as duplicate.
