### ISSUE TITLE
`timeout` argument to `test` ignored

### ISSUE THREAD

**Issue by WorikQCI** [flutter/flutter#114776]
## Steps to Reproduce

For a test that times out after 30s use `timeout:Timeout.parse("120s")` arguent to `test(..)`.

It is ignored

<img width="1561" alt="image" src="https://user-images.githubusercontent.com/95715668/200198816-48026337-b786-49d7-82c8-8bd28a345b13.png">

**Expected results:** 

I expected the test to take more time.

This is difficult to reproduce because tests do not take a deterministic amount of time (my tests are communicating with a server over the Internet)

**Actual results:** 

Screen shot above

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by WorikQCI** [comment]
This is intermittent.  Sometimes it works.

Sigh

**Comment by exaby73** [comment]
Hello @WorikQCI. Please provide a [complete and minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)
