### ISSUE TITLE
[google_maps_flutter] App Crashes frequently with an NPE or IllegalStateException. 

### ISSUE THREAD

**Issue by olofumark** [flutter/flutter#114779]
Hi, i'm using google_maps_flutter: ^2.2.1 and experiencing random crashes. 
Running on Android 10.

## Steps to Reproduce
Different routes hosts their own individual GoogleMap widget and switching/navigating back and forth causes this crash. 
The app suddenly quit, leaving error logs on the console.

**Expected results:** 
Expected full stability.

**Actual results:** 
These were the results: (sometimes one, sometimes the other)

(1)
```
E/flutter: [ERROR:flutter/fml/platform/android/jni_util.cc(204)] java.lang.IllegalStateException: Platform view hasn't been initialized from the platform view channel.
        at io.flutter.plugin.platform.PlatformViewsController.initializePlatformViewIfNeeded(PlatformViewsController.java:732)
        at io.flutter.plugin.platform.PlatformViewsController.onDisplayPlatformView(PlatformViewsController.java:791)
        at io.flutter.embedding.engine.FlutterJNI.onDisplayPlatformView(FlutterJNI.java:1380)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:336)
        at android.os.Looper.loop(Looper.java:215)
        at android.app.ActivityThread.main(ActivityThread.java:7547)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)
A/flutter: [FATAL:flutter/shell/platform/android/platform_view_android_jni_impl.cc(1469)] Check failed: fml::jni::CheckException(env).
A/libc: Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 13697 (ng.ninego.app), pid 13697 (ng.ninego.app)

(2)
E/AndroidRuntime: FATAL EXCEPTION: GLThread 10845
    Process: ng.ninego.app, PID: 21345
    java.lang.NullPointerException: Attempt to get length of null array
        at java.nio.ByteBufferAsIntBuffer.put(ByteBufferAsIntBuffer.java:122)
        at com.google.maps.api.android.lib6.gmm6.vector.gl.buffer.j.l(:com.google.android.gms.dynamite_mapsdynamite@224212030@22.42.12 (100408-0):5)
        at com.google.maps.api.android.lib6.gmm6.vector.gl.buffer.j.o(:com.google.android.gms.dynamite_mapsdynamite@224212030@22.42.12 (100408-0):1)
        at com.google.maps.api.android.lib6.gmm6.vector.gl.buffer.j.g(:com.google.android.gms.dynamite_mapsdynamite@224212030@22.42.12 (100408-0):3)
        at com.google.maps.api.android.lib6.gmm6.vector.gl.drawable.ai.s(:com.google.android.gms.dynamite_mapsdynamite@224212030@22.42.12 (100408-0):27)
        at com.google.maps.api.android.lib6.gmm6.vector.gl.drawable.ao.s(:com.google.android.gms.dynamite_mapsdynamite@224212030@22.42.12 (100408-0):10)
        at com.google.maps.api.android.lib6.gmm6.vector.bz.s(:com.google.android.gms.dynamite_mapsdynamite@224212030@22.42.12 (100408-0):29)
        at com.google.maps.api.android.lib6.gmm6.vector.bs.b(:com.google.android.gms.dynamite_mapsdynamite@224212030@22.42.12 (100408-0):151)
        at com.google.maps.api.android.lib6.gmm6.vector.av.run(:com.google.android.gms.dynamite_mapsdynamite@224212030@22.42.12 (100408-0):48)

```

<details>
<summary>Code sample</summary>

```
GoogleMap(
                                          minMaxZoomPreference: MinMaxZoomPreference(0, 16),
                                          zoomControlsEnabled: false,
                                          myLocationEnabled: true,
                                          buildingsEnabled: true,
                                          circles: Set.from([Circle(
                                              circleId: CircleId("circley1"),
                                              center: LatLng(pickup.latitude, pickup.longitude),
                                              radius: 32,
                                              strokeColor: primary1(),
                                              strokeWidth: 0,
                                              fillColor: primary1().withOpacity(0.1)
                                          )
                                          ]),

                                          compassEnabled: false,
                                          tiltGesturesEnabled: false,
                                          markers: _markers,
                                          polylines: _polylines,
                                          mapType: MapType.normal,
                                          initialCameraPosition: initialCameraPosition,

                                          onTap: (LatLng loc) {
                                            //pinPillPosition = -100;
                                          },
                                          onMapCreated: (GoogleMapController controller) {
                                            print("On map created........");
                                            _mapController = controller;
                                            _controller.complete(controller);
                                            zoomToCurrentLocation();
                                          },
                                          onCameraMove: (position){
                                            //CAMERA_LOCATION = position.target;
                                          },
                                          onCameraIdle: () async{

                                          },
                                        ),
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

[✓] Flutter (Channel stable, 3.3.7, on Ubuntu 18.10 4.18.0-10-generic, locale
    en_NG)
    • Flutter version 3.3.7 on channel stable at
      /home/gigastone/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e99c9c7cd9 (5 days ago), 2022-11-01 16:59:00 -0700
    • Engine revision 857bd6b74c
    • Dart version 2.18.4
    • DevTools version 2.15.0

[!] Android toolchain - develop for Android devices (Android SDK version
    32.1.0-rc1)
    • Android SDK at /root/Android/Sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/linux#android-setup for
      more details.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✗] Linux toolchain - develop for Linux desktop
    ✗ clang++ is required for Linux development.
      It is likely available from your distribution (e.g.: apt install clang),
      or can be downloaded from https://releases.llvm.org/
    • cmake version 3.12.1
    ✗ ninja is required for Linux development.
      It is likely available from your distribution (e.g.: apt install
      ninja-build), or can be downloaded from
      https://github.com/ninja-build/ninja/releases
    • pkg-config version 0.29.1
    ✗ GTK 3.0 development libraries are required for Linux development.
      They are likely available from your distribution (e.g.: apt install
      libgtk-3-dev)

[✓] Android Studio (version 4.1)
    • Android Studio at /usr/local/android-studio
    • Flutter plugin version 52.0.1
    • Dart plugin version 201.9245
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.58.2)
    • VS Code at /usr/share/code
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • TECNO CD8j (mobile) • 053332505F000316 • android-arm64  • Android 10 (API
      29)
    • Linux (desktop)     • linux            • linux-x64      • Ubuntu 18.10
      4.18.0-10-generic
    • Chrome (web)        • chrome           • web-javascript • Google Chrome
      91.0.4472.114

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.

</details>

Thanks so much.

**Comment by darshankawar** [comment]
Looking at the error log, it seems to be similar to https://github.com/flutter/flutter/issues/112542, so please follow-up in it for further updates. It does not look specific to `google_maps_flutter`, but with platform-views.

Closing as duplicate.
