### ISSUE TITLE
How to create a search field in Flutter?

### ISSUE THREAD

**Issue by mycar98765** [flutter/flutter#114730]
I am using the [`flutter_riverpod`](https://pub.dev/packages/flutter_riverpod) package. I'm using it for a search field and it's showing an error when searching for something. I asked [a question](https://stackoverflow.com/q/74316651/16124033) about the error but couldn't fix it. Is there any other way to create a search field in Flutter using the [`flutter_riverpod`](https://pub.dev/packages/flutter_riverpod) package?

Here is some code:

User interface code:

```
TextFormField(
  …
  onChanged: (search) => controller.updateSearch(search),
  onSaved: (search) {
    search == null ? null : controller.updateSearch(search);
  },
),
```

----------

```
itemBuilder: (context, index) {
 if (mounted) {
    return name.contains(state.search) ? ListTile(title: Text(name)) : Container();
  }

  return Container();
},
```

Controller code:

```
class Controller extends StateNotifier<State> {
Controller() : super(State());

void updateSearch(String search) => state = state.copyWith(search: search);

}

final controllerProvider = StateNotifierProvider.autoDispose< Controller, State>((ref) {
  return Controller();
});
```

State code:

```
class State {
  State({this.search = "", this.value = const AsyncValue.data(null)});

  final String search;
  final AsyncValue<void> value;
  bool get isLoading => value.isLoading;

  State copyWith({String? search, AsyncValue<void>? value}) {
    return State(search: search ?? this.search, value: value ?? this.value);
  }
}
```

Is there something wrong with the code above? If yes, what is the way to create the seach field using the [`flutter_riverpod`](https://pub.dev/packages/flutter_riverpod) package? If not, why am I getting the error message (go to [this question](https://stackoverflow.com/q/74316651/16124033) to see the error message)?

If I can't create a search field using the [`flutter_riverpod`](https://pub.dev/packages/flutter_riverpod) package in Flutter, how can I create a search field (I hope maybe without using any package and without using `setState` function)?

Feel free to comment if you need more information!

How to fix this error? I would appreciate any help. Thank you in advance!

**Comment by stuartmorgan** [comment]
For help with your own project's code, please try one of the resources at https://flutter.dev/community#community-grid, as the issue tracker is only for bug reports and feature requests for Flutter itself.

Closing as this is not request for Flutter.
