### ISSUE TITLE
Compatibility

### ISSUE THREAD

**Issue by jaesmoke** [flutter/flutter#114769]
Can flutter work on a 4gb ram machine?

**Comment by iapicca** [comment]
@jaesmoke 
I believe that this kind of questions belong on [discord channel](https://discord.com/invite/N7Yshp4)

> Can flutter work on a 4gb ram machine?

probably yes, I have 3 recommendation:
 1. use linux (don't use [snapcraft](https://snapcraft.io/flutter), install flutter the[ right way](https://docs.flutter.dev/get-started/install/linux#install-flutter-manually))
 2. debug on physical device (not on emulator)
 3. don't use android studio (it uses a tons of RAM)

**Comment by darshankawar** [comment]
As suggested above, please ask such questions on support channels.
Closing from here.

**Comment by jaesmoke** [comment]
ok thanks :)
