### ISSUE TITLE
Async stack traces missing from Sentry crash reports

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#11479]
The reports we've so far seen from Posse's use of our Sentry crash reporting plugin suggest that either our Sentry plugin is not correctly uploading async stacks, or async stacks are not working in AOT mode.  We don't yet know which.

@yjbanov @a-siva @rmacnak-google

**Comment by yjbanov** [comment]
So, I _think_ the sentry client was sending all the frames, but it wasn't encoding asynchronous gaps. Here's a fix for that: https://github.com/flutter/sentry/pull/1. We should still verify that async stack traces are enabled in Flutter AOT mode.

**Comment by yjbanov** [comment]
Ok, I just ran a sample app in three modes and observing that in `--release` mode only we are missing async stack traces.

Release:

<img width="427" alt="release" src="https://user-images.githubusercontent.com/211513/28883329-e350624c-7762-11e7-9ab6-0c4018aff75f.png">

Profile:

<img width="640" alt="profile" src="https://user-images.githubusercontent.com/211513/28883340-eb425b5e-7762-11e7-9678-60b628f0a299.png">

Debug:

<img width="655" alt="debug" src="https://user-images.githubusercontent.com/211513/28883349-f04d5ae0-7762-11e7-92d9-3e961e8d8c1b.png">

**Comment by eseidelGoogle** [comment]
I recommend reaching out to @rmacnak-google or @a-siva they would know.

**Comment by a-siva** [comment]
The flag is not turned on in release mode.

**Comment by yjbanov** [comment]
I'll add it. @rmacnak-google showed me where to do that.

**Comment by yjbanov** [comment]
`package:sentry` supports async stacks as of `0.0.4`. Flutter will produce async stacks as of https://github.com/flutter/flutter/commit/7d3a1f961686ca4471682f008514b7cfb83b1391.
