### ISSUE TITLE
Flutter windows Application with webview freezes after 30minutes minimized

### ISSUE THREAD

**Issue by NickYoung-max** [flutter/flutter#114790]
flutter doctor
[√] Flutter (Channel stable, 3.0.5, on Microsoft Windows [版本 10.0.19044.2130], locale zh-CN)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.2.6)
[√] Android Studio (version 2021.2)
[√] Connected device (3 available)
[√] HTTP Host Availability

• No issues found!

 windows application use webview-windows-0.2.0. When I open a webview,it's running well, then I minimized the application. After 30 minutes and open it from taskbar, the app freezes. (minimized it less then 30 minutes,it's running well)

**Comment by danagbemava-nc** [comment]
Hi @NickYoung-max, `webview_windows` is a third-party plugin, and any issues that stem from using said plugin should be reported on their repo. 

I'll be closing this as this doesn't seem to be a flutter issue. 

Thank you

**Comment by NickYoung-max** [comment]
> Hi @NickYoung-max, `webview_windows` is a third-party plugin, and any issues that stem from using said plugin should be reported on their repo.
> 
> I'll be closing this as this doesn't seem to be a flutter issue.
> 
> Thank you

it's flutter interface freeezes,not webview.I am not sure is it a issue of flutter or webview_windows,so I reported on you two repo.If possible,can you help to make a check in flutter?

**Comment by danagbemava-nc** [comment]
Does the freeze occur without you using the webview plugin?

**Comment by NickYoung-max** [comment]
> Does the freeze occur without you using the webview plugin?

no ,without using the webview,there is no freeze occur,that is what really bother me.I just open a webview ,why the flutter UI can be impressed(freeze) after minimizing 30 minutes? Is it possible that the UI thread of the flutter is suspended?

**Comment by NickYoung-max** [comment]
Hi danagbemava-nc,I finally found the code in webview_windows that cause the problem. the initialize method in webview has the code like behind:

     final reply = await _pluginChannel.invokeMapMethod<String, dynamic>('initialize');
      _textureId = reply!['textureId'];
      _methodChannel = MethodChannel('$_pluginChannelPrefix/$_textureId');
      _eventChannel = EventChannel('$_pluginChannelPrefix/$_textureId/events');
      _eventStreamSubscription = _eventChannel.receiveBroadcastStream().listen((event) {
      ....
  });

 when I remove the code _eventChannel.receiveBroadcastStream().listen((event), freezes gone but webview can't be open.Finally I stop and suspend the webview controller before I minimize the app,that solve the freezes problem. I wonder that is it possible the flutter method _eventChannel.receiveBroadcastStream().listen((event) cause the problem?

**Comment by danagbemava-nc** [comment]
You should report this information on the webview_windows repo so they can take a look. Ideally, streams are supposed to cancel when they're not being used
