### ISSUE TITLE
Changing the home screen wallpaper crashes/restarts games and many Flutter apps on Android 12+

### ISSUE THREAD

**Issue by AKB0N** [flutter/flutter#114711]
On Android 12+

1. If we open flutter app
2. Go to the home screen of the phone to change the wallpaper
3. Switch back to our flutter app, the app restarts.

It seems it is related to the Material You theming.

<details>
<summary>flutter doctor</summary>

[√] Flutter (Channel beta, 3.4.0-34.1.pre, on Microsoft Windows [Version 10.0.22000.1098], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2021.3)
[√] IntelliJ IDEA Community Edition (version 2021.3)
[√] Connected device (3 available)
[√] HTTP Host Availability

</details>

**Comment by exaby73** [comment]
Hello @AKB0N. Can you share a video demonstrating this behavior?

**Comment by Abhijithksabu** [comment]
same issue happens for me. whichever flutter package i use the app crashes while changing the wallpaper

**Comment by rakib205** [comment]
Any fix?

**Comment by iapicca** [comment]
@rakib205 @Abhijithksabu 
this issue is closed, I recommend to open a new issue 
providing all the info mentioned [here](https://github.com/flutter/flutter/issues/new?assignees=&labels=&template=2_bug.md&title=)
otherwise the issue will be not workable and closed as such 
(like this one)
