### ISSUE TITLE
kToolbarHeight with Iphone 14 Max Pro due Dynamic Island is not correct

### ISSUE THREAD

**Issue by redDwarf03** [flutter/flutter#114770]
I have an appbar in my flutter app. I'm use an padding to display a container
```
Padding(
padding: const EdgeInsets.only(
top: kToolbarHeight + kTextTabBarHeight,)
```

With Android and all iphone devices, that's ok like this image
![image](https://user-images.githubusercontent.com/68340133/200181111-3faed5b3-5423-451e-b38e-9a331d456f3c.png)

But with Iphone pro 14 max and Dynamic Island feature, my padding is not working correctly (see image)
![image](https://user-images.githubusercontent.com/68340133/200181160-0be02900-ae2b-4f09-bca0-74797445f983.png)

Should i have to add a constant in my padding to support iphone 14 max pro ?

**Comment by EArminjon** [comment]
Have you tried : 

```dart
Padding(
  padding: const EdgeInsets.onyl(
    top: MediaQuery.of(context).viewPadding.top,
  ),
),
```

**Comment by redDwarf03** [comment]
Sorry but same issue/behavior

**Comment by EArminjon** [comment]
Can you share a reproductible minimale code ? It will help the flutter team ;)

**Comment by iapicca** [comment]
> > Have you tried :
> > 
> > ```dart
> > Padding(
> >   padding: const EdgeInsets.onyl(
> >     top: MediaQuery.of(context).viewPadding.top,
> >   ),
> > ),
> > ```
> > 
> > MediaQuery.of(context).viewPadding.top should have the height of the status bar.
>
> Sorry but same issue/behavior

@redDwarf03 I think @EArminjon is correct

```dart
import 'package:flutter/material.dart';

class ToolbarPlaceholder extends StatelessWidget {
  const ToolbarPlaceholder({super.key});

  @override
  Widget build(context) => Positioned(
        height: kToolbarHeight,
        width: MediaQuery.of(context).size.width,
        top: MediaQuery.of(context).viewPadding.top,
        child: const Placeholder(),
      );
}

void main() => runApp(
      MaterialApp(
        home: Material(
          child: Stack(
            children: const [ToolbarPlaceholder()],
          ),
        ),
      ),
    );
```
![Simulator Screen Shot - iPhone 14 Pro Max - 2022-11-07 at 10 00 35](https://user-images.githubusercontent.com/45637986/200256988-1045932c-a1be-4eab-9895-5ebd60e25c29.png)

**Comment by danagbemava-nc** [comment]
Hi @redDwarf03, does the sample above help you out? If not, please provide a complete minimal reproducible code sample along with the output of `flutter doctor -v` so we can investigate this issue. 

Thank you
