### ISSUE TITLE
Stop calling Flutter "functional" or "functional reactive"

### ISSUE THREAD

**Issue by wmleler** [flutter/flutter#11474]
## Steps to Reproduce

Open https://flutter.io/widgets-intro/
Notice that the first line of text claims that Flutter is a "functional-reactive framework". And then immediately says things like "Widgets describe what their view should look like given their current configuration and state". That is not functional. Later, this page gives examples using stateful widgets, which are not functional. The only examples that are functional are the ones that have no state at all, and while constants are by definition functional, they aren't very interesting examples.

Just calling it a "reactive framework" would be fine.

Need to find all other places where we claim Flutter is functional and remove them. It isn't true, and even if it were, it doesn't help to call it functional and only invites arguments.

A bigger issue is why don't we have some examples that actually are functional reactive? Even the sample app (the counter) could be made to be functional. The FAB would produce a stream of events, and the text would display the output of a function that takes the stream as input and outputs (a stream of) the lengths of the input stream.

It would also be nice to have at least one example that uses RxDart.

As it is, Flutter seems to be strongly favoring stateful (non-functional) user interfaces. I'd really like to see a page that explains how to build a functional UI in Flutter.

**Comment by Hixie** [comment]
It's not "reactive" either, strictly speaking (as defined by https://en.wikipedia.org/wiki/Reactive_programming).

It's roughly as functional-reactive as React Native.

In practice, nothing in programming is functional. There has literally never been a useful program written using a pure-functional system. The term "functional" is used to mean "things that roughly attempt to approximate the functional ideals", which Flutter certainly does (the State of a StatefulWidget is an implementation detail; when you use it, you use it as if it was pure-functional, creating a new description each time).

**Comment by wmleler** [comment]
I didn't submit this bug to get into a discussion about functional programming.

I simply want us to stop calling Flutter functional, especially when we immediately follow this by talking about changing state.

> It's roughly as functional-reactive as React Native.
I did a quick search and as far as I can tell React Native doesn't call itself functional or functional-reactive.

Yes, I am aware of the ongoing debate about the differences between "reactive" and "reactive programming". I haven't seen us use the term "reactive programming" wrt Flutter, so for now I think we are fine.

Can we just agree to stop calling Flutter functional (or "functional reactive")? Does anyone see any benefit at all to us using that term?

**Comment by sethladd** [comment]
I think it's fine to mostly scrub "functional". There may be cases where we are inspired by "functional", and we shouldn't shy away from that. Please go ahead and send a PR that accomplishes your goal. Thanks!

**Comment by Hixie** [comment]
I disagree that we are not functional, and I think that's a discussion that we should have before we make decisions on such matters.

**Comment by Hixie** [comment]
To clarify: I don't necessarily object to changing this text. What I'm asking for is that we make sure we are on the same page as a team before making changes like this.

**Comment by abarth** [comment]
Here's a reasonable description of what we're doing:

https://en.wikipedia.org/wiki/Reactive_programming#Interaction_with_Mutable_State

**Comment by Sfshaza** [comment]
I should have added this issue to this PR: https://github.com/flutter/website/pull/646

Fixed.
