### ISSUE TITLE
How to build a app lock application using flutter

### ISSUE THREAD

**Issue by Melvin-2007** [flutter/flutter#114731]
I am looking to create a application using flutter that can put locks on other apps according to users choice. So can anyone tell me how to do this using flutter ? Is there any plugins out there ?

The app must work like this "when someone opens a locked app it should show a lock screen before opening the app, if the password is correct the application will be opened else it should show the password is incorrect".

**Comment by stuartmorgan** [comment]
For help with your own project's code, please try one of the resources at https://flutter.dev/community#community-grid, as the issue tracker is only for bug reports and feature requests for Flutter itself.

Closing as this is not request for Flutter.

**Comment by Melvin-2007** [comment]
Thanks for your help !
