### ISSUE TITLE
Execution failed for task ':sign_in_with_apple:parseDebugLocalResources'. 

### ISSUE THREAD

**Issue by kazerdira** [flutter/flutter#114777]
i tried to use the flutter stripe dependecy , then i had to upgrade gradle and kotlin i struggled with upgrading gradle ,they supposed to me to delete gradle-wrapper.jar,  after that when i use flutter run then it get created byitself as damaged file, and  i am getting this error.

i am using firebase , and its features 

```
Launching lib\main.dart on CPH2043 in debug mode...
lib\main.dart:1

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':sign_in_with_apple:parseDebugLocalResources'.
> Could not resolve all files for configuration ':sign_in_with_apple:androidApis'.
   > Failed to transform android.jar to match attributes {artifactType=android-platform-attr, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
      > Execution failed for PlatformAttrTransform: C:\Users\Dell\AppData\Local\Android\sdk\platforms\android-28\android.jar.
         > C:\Users\Dell\AppData\Local\Android\sdk\platforms\android-28\android.jar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 49s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)
```

**Comment by darshankawar** [comment]
> i tried to use the flutter stripe dependecy , then i had to upgrade gradle and kotlin i struggled with upgrading gradle ,they supposed to me to delete gradle-wrapper.jar, after that when i use flutter run then it get created byitself as damaged file, and i am getting this error.
> 
> i am using firebase , and its features

@kazerdira This shows probably a misconfiguration which led to the issue you are reporting. Can you try to delete the gradle cache, clean it and see if it helps ? The log is pointing to `Android\sdk\platforms\android-28`, so try to probably upgrade to android-29 or above and check. It also looks to be not related to Flutter framework, but a conflict with `sign_in_with_apple` external library with gradle.

**Comment by darshankawar** [comment]
Coming back to this issue, 
Since it is pointing to `Could not resolve all files for configuration ':sign_in_with_apple:androidApis'.` that probably indicates the plugin `sign_in_with_apple` library does not support the upgrade gradle and Kotlin versions you are on and hence the error.
See a related error message that will give you more idea:
```

The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.
The following dependencies do not satisfy the required version:
project ':sign_in_with_apple' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.50
```
Closing this as not a Flutter issue. If you disagree, write in comments and I'll reopen it.

**Comment by kazerdira** [comment]
but i dont understand even I have inside C:\Users\Dell\AppData\Local\Android\Sdk\platforms  : list of folders which are 
android-28 
android-28.delete
android-29
android-30
android-31
android-32
android-33  , but when  i compile it uses only android 28

**Comment by kazerdira** [comment]
and this this my buildgradle

def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"
apply plugin: 'com.google.gms.google-services'

android {
    compileSdkVersion 33

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.example.lookunik1"
        minSdkVersion 29
        targetSdkVersion 32
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation platform('com.google.firebase:firebase-bom:30.4.1')
    implementation 'com.google.firebase:firebase-analytics'
}

**Comment by kazerdira** [comment]
it works with deleting Android-28 and Android-28.delete folder , then after compiling it creates its Android-28 , thank you [darshankawar](https://github.com/darshankawar)
