### ISSUE TITLE
Copy/Paste Text Selection UI elements need elevation on fuchsia.

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#11470]
Right now these elements are within an Overlay above the text but don't show up due to elevation.

**Comment by eseidelGoogle** [comment]
See also https://github.com/flutter/flutter/issues/11302, likely related?

**Comment by kf6gpe** [comment]
cc @mklim @justinmc

**Comment by apwilson** [comment]
I believe this is obsolete.
