### ISSUE TITLE
In window8(9200), Get a black screen

### ISSUE THREAD

**Issue by nikohpng** [flutter/flutter#114791]
## Steps to Reproduce
In win11, I build a flutter demo (like `flutter create demo`). Then, I make release to run it in window8.

In win11, everything is ok. But I only get black screen in win8 and I can't get any error log.

## Develop enviroment
[√] Flutter (Channel stable, 3.3.4, on Microsoft Windows [版本 10.0.22000.1098], locale zh-CN)
[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Professional 2019 16.11.11)
[√] Android Studio (version 2021.1)
[√] IntelliJ IDEA Ultimate Edition (version 2020.1)
[√] VS Code (version 1.72.2)
[√] Connected device (3 available)
[√] HTTP Host Availability

**Comment by exaby73** [comment]
Hello @nikohpng. Running the app on Windows 8 on debug mode, do you get any error logs?

**Comment by exaby73** [comment]
Can you provide the entire logs of `flutter run -v` and `flutter doctor -v` from your Windows 8 machine?

**Comment by nikohpng** [comment]
I will build development env. I may reply later.

**Comment by nikohpng** [comment]
I can't build development enviroment, because vs(2017、2019) can't supported in win8 

and flutter3 can't run `flutter doctor` in  win8

maybe, I can't do it. can you give me some help?

**Comment by exaby73** [comment]
I'll label this issue for further insights from the team

**Comment by chinmaygarde** [comment]
AFAIK, we don't support Windows 8 as a development platform (but we can deploy). So we cannot offer guidance here without any logs or backtraces. Closing as inactionable.
