### ISSUE TITLE
keyboard delete Key is error

### ISSUE THREAD

**Issue by gyy19931212** [flutter/flutter#114823]
A KeyRepeatEvent is dispatched, but the state shows that the physical key is not pressed. If this occurs in real application, please report this bug to Flutter. If this occurs in unit tests, please ensure that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This was the event: KeyRepeatEvent#189b5(physicalKey: PhysicalKeyboardKey#700e1(usbHidUsage: "0x000700e1", debugName: "Shift Left"), logicalKey: LogicalKeyboardKey#00102(keyId: "0x200000102", keyLabel: "Shift Left", debugName: "Shift Left"), character: null, timeStamp: 98:56:45.945507)
'package:flutter/src/services/hardware_keyboard.dart':
Failed assertion: line 432 pos 16: '_pressedKeys.containsKey(event.physicalKey)'

**Comment by gyy19931212** [comment]
windows app

**Comment by huycozy** [comment]
@gyy19931212 Thanks for filing the issue. I see there's an open issue addressing the case you described #106475 with the same error log.
Closing this issue as a duplicate, so please follow up on it for further updates.
