### ISSUE TITLE
Website needs a Responsive UI page

### ISSUE THREAD

**Issue by Skylled** [flutter/flutter#11487]
#6398 made a GitHub [Wiki page](https://github.com/flutter/flutter/wiki/Creating-Responsive-Apps) with information about creating a responsive UI, but now it is full of broken links and needs a makeover on Flutter.io

(I'll browse through the wiki for other pages that haven't been replaced on Flutter.io and update here.)

**Comment by Hixie** [comment]
Looks like the links were fixed back in December.

**Comment by Hixie** [comment]
Is there anything left to do here?

**Comment by Sfshaza** [comment]
I manually checked each link on this page (including the sidebar). No broken links. Closing.
