### ISSUE TITLE
url_launcher docs should tell people to check canLaunch before calling launch

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#11480]
Posse's app uses a mailto: handler to open an email to support.  We've seen at least one crash report from this.  The details object is null:
```
PlatformException(Error, Error while launching mailto:foo@bar.com, null)
```

**Comment by eseidelGoogle** [comment]
Posse is seeing a lot of PlatofrmExceptions failing to launch mailto: handlers.  Unclear why.  Fixing something like this might help understand why.  @yjbanov

**Comment by eseidelGoogle** [comment]
Posse is not asking for this necessarily, but since these mailto (when mailing support!) are one of the more common crashers to their app, it seems definitely worth our time to investigate and fix.

**Comment by szakarias** [comment]
Before calling `launch`, `canLaunch` should be called to check whether there is an installed app that can handle a given scheme. For instance in the case of an iOS simulator it is not possible to handle mailto since the mail application is not available.

**Comment by Hixie** [comment]
We believe the issue here is mis-use of the API, so we will take this as an action to update our documentation, but we don't think we need to change anything. As such I'm taking the `customer: critical` label off.

**Comment by mit-mit** [comment]
The API docs already have this information:
https://www.dartdocs.org/documentation/url_launcher/0.4.2+1/url_launcher/launch.html

I updated the [package readme](https://github.com/flutter/plugins/tree/master/packages/url_launcher) to also have it in https://github.com/flutter/plugins/pull/194.  Closing this bug as fixed.

**Comment by Hixie** [comment]
I think we can do a lot better than that. We should have sample code there at a minimum. We should also be more explicit, for example phrasing it as "Before calling this method, consider calling the [canLaunch] method. This avoids the risk of [launch] failing, ..." with examples of how it might fail, etc. We should also talk about how the URL should be properly escaped.

Also this page seems to lack documentation:
https://www.dartdocs.org/documentation/url_launcher/0.4.2+1/url_launcher/url_launcher-library.html

**Comment by timsneath** [comment]
url_launcher page now seems to have documentation on this scenario (see references to `canLaunch` here: https://pub.dev/documentation/url_launcher/latest/). 

Closing this bug for now.
