### ISSUE TITLE
[Impeller] Apps with Platform views are extra funky

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#114870]
At ToT, running the example in https://github.com/flutter/flutter/issues/114712

![flutter_02](https://user-images.githubusercontent.com/8975114/200471716-09123d62-6117-45e0-8854-93e85b180de8.png)

**Comment by jonahwilliams** [comment]
bisected to https://github.com/flutter/flutter/pull/114710

**Comment by jonahwilliams** [comment]
@iskakaushik could you take a look at this?

**Comment by jonahwilliams** [comment]
I suspect https://github.com/flutter/engine/pull/37315 might have swapped a triangle strip for triangles on clips or something.

**Comment by iskakaushik** [comment]
yup, will do

**Comment by jonahwilliams** [comment]
FYI I confired with a local revert that https://github.com/flutter/engine/pull/37315 is the culprit
