### ISSUE TITLE
Crashy example should show how to use package_info to include release information

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#11482]
Posse wired up Sentry crash reporting but it didn't include their app version information. Certainly something they could figure out how to add themselves, but it may also be worth it for us to update our crashy example to show how to do this.  My understanding is that our package_info plugin should make this possible: https://github.com/flutter/plugins/tree/master/packages/package_info

FYI @yjbanov @KevinTheGray

**Comment by yjbanov** [comment]
Also https://github.com/flutter/plugins/tree/master/packages/device_info

**Comment by collinjackson** [comment]
I think probably there should be a way to convert the device info to a `Map<String, String>` so that clients can easily report it to the crash reporting service of their choice.

**Comment by Hixie** [comment]
cc @mravn-google 

Who owns Crashy now?

**Comment by yjbanov** [comment]
I haven't transferred it to anyone, so probably it's still me. I just stopped actively maintaining it.

**Comment by marandaneto** [comment]
We've (Sentry.io) released a Prelease for Flutter Apps.

This package includes support to native crashes through Sentry's native SDKs: (Android and iOS). It will capture errors in the native layer, including (Java/Kotlin/C/C++ for Android and Objective-C/Swift for iOS).

Also, we set the `release` automatically using the `package_info` package.

https://pub.dev/packages/sentry_flutter/

try out and let us know if you find any issues :)

@yjbanov I'd gladly submit a PR to `Crashy` if that's ok in a few weeks once sentry_flutter is stable/GA :)

**Comment by ueman** [comment]
The crashy app repository was archived in favor of the Sentry Flutter example. I guess this issue can be closed.
