### ISSUE TITLE
[go_router] namedLocation was depreciated in minor version, is a breaking change and breaks redirect

### ISSUE THREAD

**Issue by Ax0elz** [flutter/flutter#114832]
The latest minor version of go_router takes out namedLocation without mentioning it in the change log, which breaks my current redirect. It finally add GoRouterState to context which I very much would like to have but I still need the namedLocaiton to redirect back to the original url using queryParams. 

I am trying to gain clarity why that was taken out and what the new solution is supposed to be?

Here is an example of part of the code where that is used:
`
refreshListenable: _GoRouterRefreshStream<PreFlightCheckState>(
          BlocProvider.of<PreFlightCheckCubit>(context).stream),
      redirect: (context, state) {
        final onLoadingPage = state.subloc == loadingRoutePath;

        if (BlocProvider.of<PreFlightCheckCubit>(context).state.authenticationState is Unknown) {
          if (!onLoadingPage) {
            return state.namedLocation(
              loadingRouteName,
              queryParams: {if (state.subloc != homePath) returnUrl: state.location},
            );
          }
        } else if (BlocProvider.of<PreFlightCheckCubit>(context).state.authenticationState
            is UnAuthenticated) {
          final onRegistrationPage = state.subloc == registerRoutePath;
          if (onRegistrationPage) {
            return null;
          }

          final requestedReturnUrl = state.queryParams[returnUrl];
          if (requestedReturnUrl.isNotNullOrEmpty &&
              _returnUrlAllowsAnonymousAccess(returnUrl: requestedReturnUrl!)) {
            return requestedReturnUrl;
          }

          final targetRouteRequiresAuthentication = !_anonymousRoutes.contains(state.subloc);
          if (targetRouteRequiresAuthentication || onLoadingPage) {
            return state.namedLocation(
              loginRouteName,
              queryParams: {
                if (requestedReturnUrl.isNotNullOrEmpty) returnUrl: requestedReturnUrl!
              },
            );
          }
        } else {
          final currentlyOnLoginPage = state.subloc == loginRoutePath;
          final currentlyOnToCPage = state.subloc == tocPath;
          final currentlyOnSignupPage = state.subloc == signUpRoutePath;
          final currentlyOnCoverageLookupPage = state.subloc == coveragePath;

          if (currentlyOnLoginPage ||
              currentlyOnToCPage ||
              onLoadingPage ||
              currentlyOnCoverageLookupPage ||
              currentlyOnSignupPage ||
              !BlocProvider.of<PreFlightCheckCubit>(context).state.termsAndConditionsAccepted ||
              !BlocProvider.of<PreFlightCheckCubit>(context).state.coverageVerified) {
            if (!BlocProvider.of<PreFlightCheckCubit>(context).state.coverageVerified) {
              return currentlyOnCoverageLookupPage
                  ? null
                  : state.namedLocation(
                      coverageRouteName,
                      queryParams: {
                        if (returnUrlNotEmpty(state.queryParams[returnUrl]))
                          returnUrl: state.queryParams[returnUrl]!
                      },
                    );
            }
`

**Comment by huycozy** [comment]
Hi @Ax0elz 
In order to verify the issue properly, please provide the information indicated below:
- Current `go_router` version 
- A [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code.
- The output of `flutter doctor -v`
- Reproduction steps, Expected results, Actual results

Thank you!

**Comment by Ax0elz** [comment]
go_router version 5.1.2

```
[✓] Flutter (Channel stable, 3.3.7, on macOS 13.0 22A380 darwin-arm, locale en-US)
    • Flutter version 3.3.7 on channel stable at /Users/ax0elz/Dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e99c9c7cd9 (6 days ago), 2022-11-01 16:59:00 -0700
    • Engine revision 857bd6b74c
    • Dart version 2.18.4
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/ax0elz/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version openjdk version "11.0.10" 2021-01-19
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version openjdk version "11.0.10" 2021-01-19

[✓] IntelliJ IDEA Community Edition (version 2019.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.73.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.52.0



• No issues found!

```

namedLocation needed to return to original url. 
QueryParams are also  not getting passed down to loginRoute redirect. I later downgraded to go_router version 5.0.0 where namedLocation was not depreciated and it still was not passing query params after loading page.

Reproduction code:

```
redirect: (context, state) {
        final onLoadingPage = state.subloc == loadingRoutePath;

        if (authenticationState is Unknown) {
          if (!onLoadingPage) {
            return state.namedLocation(
              loadingRouteName,
              queryParams: {if (state.subloc != homePath) returnUrl: state.location},
            );
          }
        } else if (authenticationState
            is UnAuthenticated) {
          final targetRouteRequiresAuthentication = !_anonymousRoutes.contains(state.subloc);
          if (targetRouteRequiresAuthentication || onLoadingPage) {
            return state.namedLocation(
              loginRouteName,
              queryParams: {
                if (requestedReturnUrl.isNotNullOrEmpty) returnUrl: requestedReturnUrl!
              },
            );
          }
        }
        return null;
```

**Comment by huycozy** [comment]
Hi @Ax0elz 
I saw you closed the issue. Did you solve it? If not so, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code along reproducible steps. Thank you!
