### ISSUE TITLE
Virtual Keyboard closes instantly

### ISSUE THREAD

**Issue by architsangal** [flutter/flutter#114885]
I was testing my webpage - https://architsangal.github.io/Portfolio/
I noticed that the virtual keyboard disappear instantly when I try to type in the text field. Everything works fine where no virtual keyboard is required i.e. in my laptop, etc. but the problem arises in mobile browser or when using browser in iPad.

## Steps to Reproduce

1. Open the link - https://architsangal.github.io/Portfolio/ in a mobile browser.
2. Scroll Down to the bottom to 'Get In Touch' Section
3. Try typing in something in the text box.

**Expected results:** Text getting typed

**Actual results:** Text is not getting typed

Similar Problem but different technology: https://github.com/software-mansion/react-native-screens/issues/1342
In my case, this problem appears in safari, chrome, firefox on iPad and mobile

Code base: https://github.com/architsangal/Portfolio

Please let me know if any further information is required. Thanks.

**Comment by huycozy** [comment]
Hi @architsangal, thanks for filing the issue. But your code base is complicated code which makes it difficult to find the cause. 

For the issue to be workable, it needs to be reproducible with a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code. Please provide such a sample. And please provide the output of `flutter doctor -v` as well.

Also, you can try using a single/simple TextField() to check if the issue still reproduces.
