### ISSUE TITLE
[go_router] Allows redirect only GoRoute in RouteMatchList

### ISSUE THREAD

**Issue by levitanong** [flutter/flutter#114807]
The documentation for GoRoute's constructor says:
`- One of either [builder] or [pageBuilder] must be provided.`

Suggesting that `builder` must be provided *even if* `redirect` is provided.

However, the assertions seem to indicate that it's okay to forgo passing `builder` as long as `redirect` is provided:
```
assert(pageBuilder != null || builder != null || redirect != null,
            'builder, pageBuilder, or redirect must be provided'),
```

In practice, I get "No routeBuilder provided to GoRoute" if I provide `redirect` but not `builder`, so that seems to support the constructor's documentation rather than the assertions. If this is all intentional, then perhaps the assertion should be updated to 

```
assert(pageBuilder != null || builder != null,  'builder or pageBuilder must be provided)
```

**Comment by exaby73** [comment]
Hello @levitanong. Could you please provide links to the documentation and code you have referenced?

**Comment by levitanong** [comment]
@exaby73 thanks for responding!
 
The constructor docstring: https://github.com/flutter/packages/blob/main/packages/go_router/lib/src/route.dart#L120
The assert: https://github.com/flutter/packages/blob/main/packages/go_router/lib/src/route.dart#L131

**Comment by exaby73** [comment]
Thank you for the information. Labeling the issue for further insights from the team.

**Comment by bambinoua** [comment]
@exaby73 is it really correct what @levitanong asked? What if I need navigation like:
```
/tasks - has no page to display (just opens submenu with `task1` and `task2`
/tasks/task1 - has a page to display 
/tasks/task2 - has a page to display
```
i.e.
```
GoRouter(
  path: '/tasks',
  name: '/tasks',
  redirect: (_, __) => null,
  routes: [
    GoRouter(
      path: 'task1',
      name: '/tasks/task1'
      pageBuilder: (_, state) => MaterialPage(child: Task1()),
    ),
    GoRouter(
      path: 'task2',
      name: '/tasks/task2'
      pageBuilder: (_, state) => MaterialPage(child: Task2()),
    ),
  ],
)
```
Why do I need to specify `builder` or `pageBuilder` for `tasks` route if it does not need to display something?

Yes, now I need to workaround to avoid the `No routeBuilder provided to GoRoute` message:
```
GoRouter(
  path: '/tasks',
  name: '/tasks',
  redirect: (_, __) => null,
      pageBuilder: (_, state) => MaterialPage(child: const Placeholder()), // why do I need this?
)
```
and maybe the problem is not in `assert` only?

**Comment by exaby73** [comment]
How would you display a list of pages without providing a widget to display it? `go_router` doesn't give you any UI to display a list of pages

**Comment by bambinoua** [comment]
It is common used practice when when user clicks on some parent sidebar item which does not redirect to any page (contains anchor # in `href` attribute) and just opens the list of child sidebar items.
So my item `tasks` does not change the browser location and just opens the popoup list or activates an dropdown animated list with children `task1` and `task2`. Click on child item redirect to new URL `tasks/task1` or `tasks/task2`.

**Comment by parnurzeal** [comment]
I think this is a bug as @bambinoua  pointed out.

The assertion allows either one of `builder, pageBuilder, or ridirect` to be provided but in the code. It doesn't allow `redirect` hence the exception `No routeBuilder provided to GoRoute`.

**Comment by xster** [comment]
Setting to P2 based on b/286339825
