### ISSUE TITLE
Clean recipe's revert should be allowed as TBR

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#114866]
With the recent changes to the gerrit codereview plugins we lost the ability to revert CL as TBR and code reviews are being enforced.

**Comment by godofredoc** [comment]
@keyonghan FYI

**Comment by keyonghan** [comment]
Taking a look.

**Comment by keyonghan** [comment]
We need to add one more operator to `overrideIf`. Checking with GOB team on how to add that.

**Comment by keyonghan** [comment]
https://flutter-review.git.corp.google.com/c/All-Projects/+/35963 to fix.

**Comment by keyonghan** [comment]
The fix was landed. Presumably this is fixed. Closing now, and please reopen if you see this repro.
