### ISSUE TITLE
[Impeller] Some try jobs are failing on segfaults internal to the Metal shader compiler.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#114872]
This doesn't seem to be happening on post-submits as I couldn't find any failures in the past 200 runs.

But both @jason-simmons and @flar have reported the following failures in the Apple Metal shader compiler:
* https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8798119691463670465/+/u/test:_Host_Tests_for_host_profile/stdout
* https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8798139573040246465/+/u/test:_Host_Tests_for_host_profile/stdout
* https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8798139573040246465/+/u/test:_Host_Tests_for_host_profile__2_/stdout
* https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8798139573040246465/+/u/test:_Host_Tests_for_host_profile__3_/stdout
* https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8798135684776124433/+/u/test:_Host_Tests_for_host_profile__2_/stdout
* https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8798135684776124433/+/u/test:_Host_Tests_for_host_profile__3_/stdout

The specific shader or test case doesn't seem to matter.

**Comment by chinmaygarde** [comment]
[Another instance](https://ci.chromium.org/ui/p/flutter/builders/try/Mac%20Unopt/21235/overview) on a try-job on [this patch](https://github.com/flutter/engine/pull/37415) by @ColdPaleLight

**Comment by flar** [comment]
Do we use a different bank of bots for try-jobs vs post-submit?

**Comment by cyanglaz** [comment]
[This](https://ci.chromium.org/ui/p/flutter/builders/try/Mac%20Engine%20Drone/18676/overview) also looks like the same issue, https://github.com/flutter/engine/pull/37434

**Comment by zanderso** [comment]
Marking P2 since this is affecting rolls.

**Comment by flar** [comment]
This cost us 5 Fuchsia Linux SDK rolls in a row. All of the failed attempts appear to have been on build3NN-m9 bots. The couple of runs I've seen succeed have been on build8NN-m9 bots. We've seen this type of pattern before when a race condition was involved in a test. The build3NN bots seem to have slightly different timing that uncovered the race condition whereas the other bots sailed through it with luck.

**Comment by flar** [comment]
Every single failure in the description was being run on a build3NN-m9 bot.

**Comment by flar** [comment]
Examining the last 25 runs in both the Mac Unopt and Mac Host Engine tasks, they fail 100% of the time on a buid3NN bot and succeed 100% of the time on a buld8NN bot.

While this could be a software installation issue on that bank of bots, the fact that it can sometimes pass on 1 of the Impeller tests and fail on the 2nd or 3rd (of 100s of Impeller tests in a run), indicates that it is probably a race condition similar to what we saw last week when we had the same pattern. In that case we found an actual race condition in the test that was tending to fail on the build3NN bank of bots.

**Comment by zanderso** [comment]
It sounds like this PR https://github.com/flutter/engine/pull/37498 helped the crash happen more reliably on host_profile on CI.

**Comment by zanderso** [comment]
@jason-simmons is going to try to repro locally, but we'll likely need more Metal expertise to diagnose and fix, so I'll assign this to @chinmaygarde to look at when he is back from OOO.

**Comment by zanderso** [comment]
@chinmaygarde Any luck on this one?

**Comment by chinmaygarde** [comment]
I haven't been able to reproduce this. Tried to restrict resources too. I've verified that we are doing the right things with callbacks and such. My suspicion is that there may be a race in the Metal framework w.r.t device teardown and compiler callback invocation. If I am not able to resolve this soon, I'll just switch to synchronous compilation on host platforms. This will delay engine launch by a bit on the host unit-tests but should side-step the races. That's the fallback plan if nothing else works though.

**Comment by zanderso** [comment]
@chinmaygarde Are there any risks involved in landing the workaround eagerly? Would we be losing any test coverage of the code that we use for iOS?

**Comment by chinmaygarde** [comment]
I'm going to submit the patch to make shader loading synchronous on host platforms today.

**Comment by chinmaygarde** [comment]
My observation was that this was happening less frequently on pre-submits and never on post-submits. Jason and I did notice this was happening on multiple machines on the try-bots. @godofredoc: Is the pool of machines for the pre and post submits different?

**Comment by godofredoc** [comment]
The pools are different but the specs of the machines are the same.

**Comment by chinmaygarde** [comment]
This happened on a try-job yesterday. I'm going to apply the speculative fix anyway today.

**Comment by jason-simmons** [comment]
A version of this error is still happening on the Mac Host Engine try builders:

```
[ RUN      ] Play/RuntimeStageTest.CanCreatePipelineFromRuntimeStage/Metal
2022-12-14 09:15:00.856 impeller_unittests[52441:257157] Metal GPU Validation Enabled
[ERROR:flutter/fml/backtrace.cc(108)] Caught signal SIGSEGV during program execution.
Frame 0: 0x7ff80a078177 newRenderPipeline()
Frame 1: 0x7ff80a104b7c __233-[MTLCompiler createVertexStageAndLinkPipelineWithFragment:fragmentVariant:vertexFunction:serializedVertexDescriptor:descriptor:destinationArchive:options:reflection:compileStatistics:fragmentCompileTimeData:error:completionHandler:]_block_invoke.1436
Frame 2: 0x7ff80a103f3e -[MTLCompiler createVertexStageAndLinkPipelineWithFragment:fragmentVariant:vertexFunction:serializedVertexDescriptor:descriptor:destinationArchive:options:reflection:compileStatistics:fragmentCompileTimeData:error:completionHandler:]
Frame 3: 0x7ff80a10681c __128-[MTLCompiler newRenderPipelineStateWithDescriptorInternal:options:reflection:destinationBinaryArchive:error:completionHandler:]_block_invoke_3
Frame 4: 0x7ff80a105a42 -[MTLCompiler newRenderPipelineStateWithDescriptorInternal:options:reflection:destinationBinaryArchive:error:completionHandler:]
Frame 5: 0x7ff80a074c75 -[MTLCompiler newRenderPipelineStateWithDescriptor:options:reflection:error:completionHandler:]
Frame 6: 0x7ff80a0cabe3 -[_MTLDevice newRenderPipelineStateWithDescriptor:options:reflection:error:]
Frame 7: 0x7ff801e6fa44 -[MTLGPUDebugDevice newRenderPipelineStateWithDescriptor:options:reflection:error:]
Frame 8: 0x105903876 impeller::PipelineLibraryMTL::GetPipeline()
Frame 9: 0x104fa1d89 impeller::testing::RuntimeStageTest_CanCreatePipelineFromRuntimeStage_Test::TestBody()
Frame 10: 0x105a4974c testing::Test::Run()
Frame 11: 0x105a4a705 testing::TestInfo::Run()
Frame 12: 0x105a4b425 testing::TestSuite::Run()
Frame 13: 0x105a5a02d testing::internal::UnitTestImpl::RunAllTests()
Frame 14: 0x105a59a84 testing::UnitTest::Run()
Frame 15: 0x105180daf main
Frame 16: 0x10791b52e start
```

**Comment by chinmaygarde** [comment]
@jason-simmons Do you have the link to the failing run handy? Need to keep investigating.

**Comment by jason-simmons** [comment]
See various recent runs on https://ci.chromium.org/p/flutter/builders/try/Mac%20Host%20Engine

example: https://ci.chromium.org/ui/p/flutter/builders/try/Mac%20Host%20Engine/47374/overview

**Comment by chinmaygarde** [comment]
I'm reverting the speculative fix.

**Comment by a-siva** [comment]
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8794756679990114945/+/u/test:_Host_Tests_for_host_profile__2_/stdout
shows the error
[FATAL:flutter/impeller/base/validation.cc(31)] Library was collected before a pending pipeline creation could finish
Could be related.
