### ISSUE TITLE
Impeller on ipad mini 2 using iOS 12

### ISSUE THREAD

**Issue by jjboy91** [flutter/flutter#114884]
Hello,

So I am trying to identify the cause of performances issues I'm seeing on my app on old devices running iOS 12.
When I run the command line : `flutter run --profile --enable-impeller --trace-skia`, janks are appearing at every frame while without impeller I have some janks but only a few.

Is this normal behaviour from impeller ?

How can I better identify what is causing janks ?

Thanks !

## Details

[with impeller](https://user-images.githubusercontent.com/19731153/200548493-49071528-462e-4f1f-ad20-1136db77ad98.png)
[without impeller](https://user-images.githubusercontent.com/19731153/200550185-f1bc7889-f5e3-4ab5-a6fa-a6c88f476e06.png)
[devtools-perf.zip](https://github.com/flutter/flutter/files/9960455/devtools-perf.zip)

`flutter analyze` didn't returned anything relevant

`flutter doctor -v` :

[✓] Flutter (Channel master, 3.5.0-8.0.pre.13, on macOS 12.6 21G115 darwin-x64, locale fr-FR)
    • Flutter version 3.5.0-8.0.pre.13 on channel master at /Users/idm/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 1e4d56ec7a (3 weeks ago), 2022-10-17 01:58:03 -0400
    • Engine revision f6aef9b30f
    • Dart version 2.19.0 (build 2.19.0-312.0.dev)
    • DevTools version 2.18.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/idm/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.72.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.52.0

[✓] Connected device (3 available)
    • iPad de Mickael (mobile) • 449a48279fd3aed768002dbb55baf769cd3aed9d • ios            • iOS 12.5.6 16H71
    • macOS (desktop)          • macos                                    • darwin-x64     • macOS 12.6 21G115 darwin-x64
    • Chrome (web)             • chrome                                   • web-javascript • Google Chrome 107.0.5304.87

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Comment by huycozy** [comment]
Hi @jjboy91, does this issue happen on the Flutter default sample project (counter app)? If not so, can you provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this?
