### ISSUE TITLE
Unable to interact with elements (textbox and button) which as "visible : false" in flutter app.

### ISSUE THREAD

**Issue by Subin367** [flutter/flutter#114890]
![Issue](https://user-images.githubusercontent.com/106580100/200573861-b0b786ac-1316-4bb3-b624-be60e092571d.png)

At first my automation script was working well, at that time version of my xcode was 13.4.1, iOS version was 15.2 and Mac OS was 12.3.1 and then my iPhone got updated with 16.1, so I have to updated my xcode to 14.1 and Mac OS to 12.6. Now I am unable to interact with elements like textbox and buttons in my app during test execution, this is happening in places where the visible is false for the element.

The Appium server and Appium inspector versions are (1.22.3 and 2022.9.1)

**Comment by danagbemava-nc** [comment]
Hi @Subin367, please provide a complete minimal reproducible code sample along with detailed steps to reproduce the issue so that we can investigate this.

Please also provide the output of `flutter doctor -v`. 

Please also provide any other information that might be relevant. 

Thank you
