### ISSUE TITLE
crashy example should show how to include flutter version in crash reports

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#11481]
Posse wired up Sentry crash reporting but it didn't include the Flutter version information.  Certainly something they could figure out how to add themselves, but it may also be worth it for us to update our crashy example to show how to do this (and make sure it's possible, since I'm not sure we expose the flutter version information into Dart at all).

FYI @yjbanov @KevinTheGray

**Comment by jmagman** [comment]
This issue is referencing the [crashy](https://github.com/flutter/crashy) repo.

**Comment by bruno-garcia** [comment]
Crashy was archived
