### ISSUE TITLE
path_provider vs external USB storage

### ISSUE THREAD

**Issue by Kajikoslav** [flutter/flutter#114801]
When i plug external USB storage to phone, path_provider found path at Motorola phones only (i tested Motorola android 12 and Motorola android 11). When i plug USB storage to Nokia X10 (Android 12) or Samsung A40 (Android 11) then storage path is empty and not found. 
Flutter doctor without issues, Flutter version 3.3.6, path_provider: ^2.0.11, compileSdkVersion 33 minSdkVersion 28 targetSdkVersion 33.... i try manifest with android:requestLegacyExternalStorage="true" and without that strange feature and no effect. I use:
List<Directory>? externalDir = await getExternalStorageDirectories();
Pls some help?

**Comment by darshankawar** [comment]
See this open issue for your reference: https://github.com/flutter/flutter/issues/40504. Since there's no support for external storage yet in framework, you might be seeing the behavior. Please follow-up in it for further updates.
Closing.
