### ISSUE TITLE
[Impeller] Deprecate --trace-skia flag and instead have a --trace-graphics flag.

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#114853]
By default, Flutter tells Skia to do very little tracing, since it can impact application performance significantly. However, sometimes it is helpful to view more verbose Skia tracing to diagnose where it is spending CPU time during rendering (e.g. in a long `Canvas::flush` call or during display list dispatching).

We should adopt a similar strategy for Impeller. Rather than creating a `--trace-impeller` flag, it would be easier for developers to just have a `--trace-graphics` flag. This would either turn on Skia tracing when Skia is used or extra tracing in Impeller when impeller is used. It could also potentially turn on other per-frame traces in the engine that are typically too expensive to leave on all the time if we found it necessary.

We should also audit impeller-based tracing and see if there are traces that should be kept off by default as we get closer to declarign it ready for GA.

/cc @chinmaygarde @jonahwilliams @gaaclarke @zanderso @christopherfujino

**Comment by dnfield** [comment]
(I'm less concerned with the name(s) of the flag than that we eventually avoid multiple-trace-events-per-frame from Impeller and that we have a good way to turn that on when needed)

**Comment by chinmaygarde** [comment]
IMHO, the current tracing system which effectively ignores trace categories isn't as flexible as it could be. And, we are re-inventing stuff that projects like Perfetto have solved. I'd rather integrate with Perfetto and have as many traces as we want but each within discrete categories. For categories that are disabled, [the performance overhead is negligible](https://perfetto.dev/docs/instrumentation/track-events#performance). We could then have tracing present but disabled in all modes (even release modes which some g3 clients have requested support for).

But, fundamentally, I agree with the ask here in this bug. I also don't particularly care if we alias trace-skia to mean trace-graphics if that makes the transition easier. So far, with Impeller, we haven't really done too much profiling with traces. Instead, resorting to native profilers and frame capture tools.

**Comment by dnfield** [comment]
Right now, it's more expensive to use the Dart VM timeline recorder than using native tracing on Android via Perfetto. It's also likely more expensive than using Signposts, though I haven't measured that (I think @gaaclarke might have). We should try to drive that down for sure, but it will likely take time to get there.

**Comment by gaaclarke** [comment]
Yea signposts are faster from what I recall.  Dart's timeline recorder eats up a lot of time querying the thread time.  Presumably signposts can be more efficient about synchronizing with the kernel since the thread time never has to reach userland.

**Comment by chinmaygarde** [comment]
Do we need this at all? I don't recall timeline tracing every being all that useful for GPU workloads. We are already judicious with the number of traces we add. I don't think we need ways to toggle traces from different subsystems.

**Comment by jonahwilliams** [comment]
I don't think we need this. If folks want to trace engine workloads they should use platform native sampling profilers. Dart timeline events have too much overhead.
