### ISSUE TITLE
Video rendered with a green bar on android when transformed from iOS

### ISSUE THREAD

**Issue by Tom3652** [flutter/flutter#114800]
## Steps to Reproduce

In order to reproduce the bug, even with a reproductible code sample, you need to have a Firebase project (to play the video from Network on an Android device) 

1. Run the sample code on iOS device
2. Pick a video (no matter which aspect ratio i have tested landscape or portrait)
3. Wait for the log `UPLOAD COMPLETE`
4. Run the sample code on Android device
5. See the green bar at the bottom of the video

In my opinion, a video that has been transformed through `AVAssetExportSession` from the Swift code is not rendered correctly on Android.  
In my app this is a core feature as i need to compress videos from any device and display them on any device.
A potential fix might be to correct the transform on Android side if needed.

Note : in my tests i always have the green bar at the bottom, but in my production app i do see the green bar on the right side sometimes. It actually depends on the video orientation as well.

**Expected results:** 

No green bar should appear on Android. 

**Actual results:** 

There is a green bar at the bottom of the video. 

<details>
<summary>Code sample</summary>

```dart
import 'dart:async';
import 'dart:io';

import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_storage/firebase_storage.dart';
import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';
import 'package:path_provider/path_provider.dart';
import 'package:uuid/uuid.dart';
import 'package:video_compress/video_compress.dart';
import 'package:video_player/video_player.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();
  runApp(const TestApp());
}

class TestApp extends StatefulWidget {
  const TestApp({Key? key}) : super(key: key);

  @override
  State<TestApp> createState() => _TestAppState();
}

class _TestAppState extends State<TestApp> {

  VideoPlayerController? _controller;
  String url = "";

  Future<void> _test() async {
    if (Platform.isIOS) {
      XFile? file = await ImagePicker().pickVideo(source: ImageSource.gallery);
      if (file != null) {
        MediaInfo first = await VideoCompress.getMediaInfo(file.path);
        print("First info : $first");
        _controller = VideoPlayerController.file(File(file.path));
        await _controller!.initialize();
        setState(() {
          _controller!.play();
        });
        await Future.delayed(const Duration(seconds: 5));
        Directory temp = await getTemporaryDirectory();
        MediaInfo? info = await VideoCompress.compressVideo(
            path: file.path, output: "${temp.path}/${const Uuid().v4()}.mp4");
        if (info != null) {
          FirebaseStorage.instance.ref().child("test").putData(
              File(info.path!).readAsBytesSync(),
              SettableMetadata(contentType: "video/mp4")).then((p0) {
                print("UPLOAD COMPLETE");
          });
          print("Info : ${info.toJson()}");
          _controller = VideoPlayerController.file(File(info.path!));
          await _controller!.initialize();
          setState(() {
            _controller!.play();
          });
        }
      }
    }
    else {
      url = await FirebaseStorage.instance.ref().child("test").getDownloadURL();
      _controller = VideoPlayerController.network(url);
      await _controller!.initialize();
      setState(() {
        _controller!.play();
      });
    }
  }

  @override
  void initState() {
    _test();
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: _controller != null && _controller!.value.isInitialized
            ? VideoPlayer(_controller!)
            : const SizedBox()
      ),
    );
  }
}
```

</details>

<details>

```
[✓] Flutter (Channel stable, 3.3.7, on macOS 13.0 22A380 darwin-x64, locale fr-FR)
    • Flutter version 3.3.7 on channel stable at /Users/foxtom/Desktop/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e99c9c7cd9 (5 days ago), 2022-11-01 16:59:00 -0700
    • Engine revision 857bd6b74c
    • Dart version 2.18.4
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/foxtom/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.73.0)
    • VS Code at /Users/foxtom/Desktop/Visual Studio Code.app/Contents
    • Flutter extension version 3.46.0

[✓] Connected device (3 available)
    • moto g 8 power (mobile) • ZY22BNDW2C • android-arm64  • Android 11 (API 30)
    • macOS (desktop)         • macos      • darwin-x64     • macOS 13.0 22A380 darwin-x64
    • Chrome (web)            • chrome     • web-javascript • Google Chrome 107.0.5304.87

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

The dependencies : 

```
  firebase_core:
  firebase_storage:
  video_player:
  image_picker:
  uuid:
  video_compress:
    git:
      url: https://github.com/Tom3652/VideoCompress.git
  path_provider:
```

</details>

**Comment by exaby73** [comment]
Hi @Tom3652 
I see there's an open issue addressing the case you described https://github.com/flutter/flutter/issues/55090
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by Tom3652** [comment]
Hi @exaby73, indeed i have came across these existing issues first, but i am actually providing a way to reproduce the error at 100%.
It may be specific to an iOS transformation which doesn't seem to be the case on the issue you mentioned or any i have found in this repo. 

I would like you to reopen it please.

**Comment by exaby73** [comment]
Can you provide a sample repo that has the compressed video in it as an asset?

**Comment by Tom3652** [comment]
I am not sure what do you want, here is the asset : 

https://user-images.githubusercontent.com/32631467/200383248-04b54fcc-828a-4c73-8de3-52b162dcd285.mp4

And played from `VideoPlayerController.asset("assets/test.mp4");` gives the same output with the green bar indeed.

I have gave you a way to `produce` videos with green bar on Android, and give you the last video i have used for my tests.

**Comment by exaby73** [comment]
I need a [complete and minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). Basically, I want an minimal app that doesn't include any 3rd party libraries including Firebase.

**Comment by Tom3652** [comment]
I know why you need a minimal and complete reproductible example, but firebase is only here to be able to host the file online to be able to see the result on Android, as many of my production users see this bug. 

There are two things now : 
- Use the repro code i have made to see the real issue (`image_picker` is only here to pick any video, and doesn't impact the issue, i have also tried using `photo_manager` and got the same result but `image_picker` shows less code) 

- Tell me how can i achieve what you ask without uploading the file. This is not possible to save files to the `asset` folder from flutter code as it appears to be read only 

I have already taken the time to make the minimal and complete reproductible example, but this is a non-trivial bug that i have investigated from the swift code...

**Comment by exaby73** [comment]
## Triage report

I can reproduce this on an API 33 emulator. In fact, the video seems to completely be green with glitches all over. See video demonstration below. The video seems to play perfectly, with any green borders on my physical, Android 12 device. Labeling this issue for further insights from the team.

Asset downloaded from https://github.com/flutter/flutter/issues/114800#issuecomment-1305999680

<details>
<summary>Code Sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:video_player/video_player.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Video played from iOS transformation'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  late VideoPlayerController _controller;

  @override
  void initState() {
    super.initState();
    _controller = VideoPlayerController.asset('assets/video.mp4')
      ..initialize()
      ..setVolume(0)
      ..setLooping(true)
      ..play();
  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text(widget.title)),
      body: Center(
        child: VideoPlayer(_controller),
      ),
    );
  }
}
```

</details>

<details>
<summary>Video demonstration</summary>

https://user-images.githubusercontent.com/50555895/200787439-ec31ff3e-150f-43d2-a00b-98681a8223f3.mp4

</details>

**Comment by stuartmorgan** [comment]
> i have came across these existing issues first, but i am actually providing a way to reproduce the error at 100%.

It's still better for us to consolidate discussion to one place. I've added a reference to this issue from there, so that people investigating can include the repro case here.
