### ISSUE TITLE
Scribble mixin regressed fullscreen_textfield_perf_impeller_ios__e2e_summary worst frame

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#114898]
The regression is noisy but quite large: 2ms -> 52ms.

https://flutter-flutter-perf.skia.org/e/?begin=1665557975&end=1667870223&keys=X7998211eeaebf12251a948e3ed58f88f&queries=arch%3Dintel%26branch%3Dmaster%26config%3Ddefault%26device_type%3DiPhone_6s%26device_version%3DiOS-15.5%26device_version%3Dnone%26host_type%3Dmac%26sub_result%3Dworst_frame_build_time_millis%26test%3Dfullscreen_textfield_perf_impeller_ios__e2e_summary&requestType=0&selected=commit%3D31956%26name%3D%252Carch%253Dintel%252Cbranch%253Dmaster%252Cconfig%253Ddefault%252Cdevice_type%253DiPhone_6s%252Cdevice_version%253Dnone%252Chost_type%253Dmac%252Csub_result%253Dworst_frame_build_time_millis%252Ctest%253Dfullscreen_textfield_perf_impeller_ios__e2e_summary%252C&xbaroffset=31957

cc @justinmc @chinmaygarde

**Comment by jonahwilliams** [comment]
I'm having difficulty reproducing this locally, which leads me to believe it may be a statistical artifact.

Before the scribble mixin relanded, I'm seeing a ~30-40ms frame build, then a ~30-40ms raster time. Afterwards, I see the same times approximately

**Comment by jonahwilliams** [comment]
Perhaps we were missing the first frame before but now we're not? Needs more investigation

**Comment by zanderso** [comment]
There are some internal test failures that also seem to be timing related. Possibly getting reverted in https://github.com/flutter/flutter/pull/115146.

**Comment by zanderso** [comment]
The change was reverted, and the benchmark recovered.

**Comment by justinmc** [comment]
I'll try to take a look at how this could have affected benchmarks before I try to reland it.
