### ISSUE TITLE
Stocks app doesn't align with material grid at all...

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#1148]
Turn on the grid in the settings and browse around the app. Many parts of the app aren't actually aligned to the material grid.

Some of this will be the stocks app, but I think a lot of it might be defaults in the widgets.

**Comment by Hixie** [comment]
We haven't had any complaints about this and we're not likely to work on it any time soon, so we're going to close this bug for now and wait specific actionable requests.

**Comment by eseidelGoogle** [comment]
Should we remove the MaterialGrid feature if our framework doesn't match it?
