### ISSUE TITLE
Update `CircleAvatar` to support Material 3

### ISSUE THREAD

**Issue by TahaTesser** [flutter/flutter#114811]
![image](https://user-images.githubusercontent.com/48603081/200322331-604a92c2-3175-487c-b01b-cbb103eee47f.png)

Specs: https://m3.material.io/components/lists/specs

related https://github.com/flutter/flutter/issues/114006

**Comment by TahaTesser** [comment]
@darrenaustin 
Could you please add this to the Material 3 issue?

**Comment by TahaTesser** [comment]
@HansMuller 
Could you please add this to the Material 3 issue? If needed.

**Comment by HansMuller** [comment]
> @HansMuller Could you please add this to the Material 3 issue? If needed.

Done - https://github.com/flutter/flutter/issues/91605
