### ISSUE TITLE
api.flutter.dev has a robots.txt blocking search engine indicies

### ISSUE THREAD

**Issue by eseidel** [flutter/flutter#114900]
https://api.flutter.dev/robots.txt is intentional?  I think that's part of why api searches for flutter are so wonky.

Came across by searching https://www.google.com/search?q=inherited+widget+flutter and it finding api.flutter.dev as the first hit, but it telling me that it has no description due to the robots.txt.

@gspencergoog 
@Hixie

**Comment by gspencergoog** [comment]
Whoa.  That *is* the intentional robots file for https://master-api.flutter.dev, since we didn't want that to become the definitive site for search results, but it definitely shouldn't be the case for api.flutter.dev. Perhaps something publishing to that site is copying the one off of the master-api site?

**Comment by gspencergoog** [comment]
@CaseyHillers @christopherfujino Do you know how publishing the docs is copying from the master site, and if it's copying this file?

**Comment by christopherfujino** [comment]
let me investigate

**Comment by CaseyHillers** [comment]
@godofredoc is this related to your recent changes to the packaging builder?

**Comment by godofredoc** [comment]
Yes, this is related to my optimizations of the documentation deployment process. Taking a look.

**Comment by godofredoc** [comment]
Fix: https://flutter-review.git.corp.google.com/c/recipes/+/35881

**Comment by eseidel** [comment]
I suspect this is expected, but FYI this is still the case:
https://api.flutter.dev/robots.txt is still there.

I noticed this afternoon when searching for "ChangeNotifier flutter" and not getting any api.flutter.dev links:
https://www.google.com/search?q=changenotifier+flutter

**Comment by Hixie** [comment]
@godofredoc that link isn't accessible outside corp, is there a public link for people who want to follow along?

**Comment by godofredoc** [comment]
Recipes CL used to be public, opened https://github.com/flutter/flutter/issues/115195 to investigate.

The CL landed a few hours ago. https://ci.chromium.org/p/flutter/builders/prod/Linux%20docs_publish/7560 is regenerating the docs and will be published soon.

**Comment by godofredoc** [comment]
Update: this is fixed.

[robots.txt](https://api.flutter.dev/robots.txt) content
```
# All robots welcome!
```

**Comment by godofredoc** [comment]
I'll double check with @gspencergoog on Monday to ensure everything is working properly.

**Comment by gspencergoog** [comment]
This seems to be corrected now.

**Comment by eseidel** [comment]
https://www.google.com/search?q=inherited+widget+flutter now shows api.flutter.dev as the first result.  Thanks!
