### ISSUE TITLE
Wrong colors only on older device

### ISSUE THREAD

**Issue by perlatus** [flutter/flutter#11499]
Easiest way to reproduce is using [zoomable_image/example](https://github.com/perlatus/flutter_zoomable_image/tree/master/example). I see this in my e1547 app as well, but not in Gallery, to my surprise. Wrong colors don't appear outside of the flutter apps. 

Maybe related to #11492?

# Screenshots
## Nexus 5x with the correct colors
![Good, Nexus 5x](https://perlat.us/img/flutter_zoomable-image-weird-color_Nexus5x.png)

## Verizon Galaxy SIII with incorrect colors
![Bad, Verizon Galaxy SIII](https://perlat.us/img/flutter_zoomable-image-weird-color_SCH-I535.png)

# Flutter Doctor
```
(( 00:30:26 )) ~/.../clone/flutter
» % flutter doctor
[✓] Flutter (on Linux, locale en_US.UTF-8, channel master)
    • Flutter at ((snip))/code/clone/flutter
    • Framework revision 58f47bd906 (4 hours ago), 2017-08-02 17:34:23 -0700
    • Engine revision 1de56a33d2
    • Tools Dart version 1.25.0-dev.7.0

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at ((snip))/opt/android-sdk
    • Platform android-25, build-tools 25.0.3
    • ANDROID_HOME = ((snip))/opt/android-sdk
    • Java binary at: ((snip))/opt/android-studio-dev/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b736)

[✓] Android Studio (version 2.3)
    • Android Studio at ((snip))/opt/android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] Android Studio (version 2.4)
    • Android Studio at ((snip))/opt/android-studio-dev
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b736)

[✓] Android Studio
    • Android Studio at /opt/android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[-] IntelliJ IDEA Community Edition (version 2017.1)
    ✗ Flutter plugin version 13.0 - the recommended minimum version is 14.0.0
    • Dart plugin version 171.4424
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[✓] Connected devices
    • SCH I535 • 14495d54 • android-arm • Android 4.4.2 (API 19)
```

**Comment by eseidelGoogle** [comment]
@chinmaygarde @jason-simmons this is likely related to the color-correction patch.

**Comment by eseidelGoogle** [comment]
This is a Galaxy S3, which we have one in our bank of devices:
https://www.amazon.com/Samsung-Galaxy-S3-SCH-I535-Verizon/dp/B00GWR8YSA

**Comment by eseidelGoogle** [comment]
The color correction patch which likely caused this is https://github.com/flutter/engine/commit/ddaa125ca7845ee177ceca6078d0aae3a675c4a6.

**Comment by perlatus** [comment]
I'm seeing the colors on an S3 running CM12.1 (Android 5.1.1) rather than the Verizon firmware.

No clue what makes the S3 special, but I'm not seeing the issue on my other test devices (these are OK):
- SM S766C (Samsung Galaxy Stardust)
- VS980 4G (Verizon LG G2)

**Comment by eseidelGoogle** [comment]
Is "S3" the full title of the device?

**Comment by perlatus** [comment]
What I meant to say is that I have two Verizon Galaxy S3s (the one you linked), one running stock (screenshot and first post) and the other running CM12.1; both of them have the color problem.

**Comment by chinmaygarde** [comment]
I am investigating this today. The [color correctness patches](https://github.com/flutter/engine/commit/ddaa125ca7845ee177ceca6078d0aae3a675c4a6) should have correctly handled all fallback cases. But it is possible I missed something. Will try to get a hold of this device variant.

**Comment by perlatus** [comment]
Yes, though it might not be worth it to fix if the S3 is the only device that has this problem. It's pretty dated at this point.

**Comment by perlatus** [comment]
Tried running it again against latest flutter beta and the colors are correct now. I think this is fixed.
