### ISSUE TITLE
Display name missing when building

### ISSUE THREAD

**Issue by jjboy91** [flutter/flutter#114975]
Hello,

When I run the command : `flutter build ipa --release --bundle-sksl-path flutter_02.sksl.json` or `flutter build ipa --release  `

It gives me a warning : Display Name: Missing and after the installation the name is 'Runner'..

I have checked the value on Xcode and it is properly indicated.

When I create the ipa using XCode it's working as intended.
Is there a way to include SKSL in Xcode ?

`flutter doctor -v`
<details>

[✓] Flutter (Channel master, 3.5.0-12.0.pre.175, on macOS 12.6 21G115 darwin-x64, locale fr-FR)
    • Flutter version 3.5.0-12.0.pre.175 on channel master at /Users/idm/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 92f10ed712 (13 hours ago), 2022-11-08 17:57:52 -0800
    • Engine revision e7d7edab98
    • Dart version 2.19.0 (build 2.19.0-374.0.dev)
    • DevTools version 2.19.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/idm/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.73.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.52.0

[✓] Connected device (3 available)
    • iPad (2) (mobile) • 0d90cccda2e8ecbf09cb57bbe0219aaf441b212d • ios            • iOS 15.6 19G71
    • macOS (desktop)   • macos                                    • darwin-x64     • macOS 12.6 21G115 darwin-x64
    • Chrome (web)      • chrome                                   • web-javascript • Google Chrome 107.0.5304.87

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
</details>

Where should I look to solve this ? 

Thanks !

**Comment by danagbemava-nc** [comment]
Hi @jjboy91, does this issue occur in a new `flutter create`d app, or is it an issue with only your project? 

Please provide the full verbose output of `futter build ipa --release -v`. The output may be huge so kindly put it into a .txt file and attach it here. 

Btw, have you made any changes to the `CFBundleName` or the display name of your project?

**Comment by mg** [comment]
Hi, I am experiencing this as well.``flutter build ipa --release" complains about missing display name but the value is correct both in XCode and App Store connect

<img width="758" alt="image" src="https://user-images.githubusercontent.com/1972/218275255-79e2ebde-054d-48ad-bfba-9dd5e3ea4d83.png">

This is a project I created 3 years ago with ``flutter create``. CFBundleName in Runner/Info.plist is correct (18XXc).

**Comment by mg** [comment]
[✓] Flutter (Channel stable, 3.7.3, on macOS 12.6.3 21G419 darwin-x64, locale en-IS)
    • Flutter version 3.7.3 on channel stable at /Users/mg/Projects/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9944297138 (3 days ago), 2023-02-08 15:46:04 -0800
    • Engine revision 248290d6d5
    • Dart version 2.19.2
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/mg/Library/Android/sdk/
    • Platform android-33, build-tools 33.0.1
    • ANDROID_HOME = /Users/mg/Library/Android/sdk/
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.74.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • iPhone 14 Pro Max (mobile) • AC7D1080-401F-4380-B8CE-07FD7D1623AF • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-1 (simulator)
    • macOS (desktop)            • macos                                • darwin-x64     • macOS 12.6.3 21G419 darwin-x64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 109.0.5414.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
