### ISSUE TITLE
url_launcher plugin has issue.

### ISSUE THREAD

**Issue by vernalclareai** [flutter/flutter#114936]

**Comment by vernalclareai** [comment]
String redirectLink = "https://api.whatsapp.com/send?phone=" +
        wAPhone +
        "&text=" +
        sandBoxText;
    if (!await launchUrl(Uri.parse(redirectLink))) throw 'Could not launch $scanUrl';
   
This function detected as unknown scheme url.
await launch(redirectLink) worked properly, but this function is deprecated now.
 This issue will be resolved in future version?
Thanks.

**Comment by huycozy** [comment]
Hi @vernalclareai 
To be more precise, please provide the information indicated below:
- Which `url_launcher` version are you using?
- A [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
- The output of `flutter doctor -v`
- Reproduction steps
- Which environment did this issue happen in? (Android/iOS/Web/MacOS/Windows/Linux)

Thank you!

**Comment by vernalclareai** [comment]
Platform : Only Android , iOS worked

Lib version : 6.1.0

Code : 
String redirectLink = "https://api.whatsapp.com/send?phone=" + wAPhone + "&text=" +sandBoxText;
await launch(redirectLink) worked correctly, but this function is deprecated now.

await launchUrl(Uri.parse(redirectLink)) not worked.

-flutter doctor -v

```
[✓] Flutter (Channel stable, 3.0.2, on macOS 12.6 21G115 darwin-x64, locale
    en-US)
    • Flutter version 3.0.2 at /Volumes/Data/Tools/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cd41fdd495 (5 months ago), 2022-06-08 09:52:13 -0700
    • Engine revision f15f824b57
    • Dart version 2.17.3
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/ying/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = /Users/ying/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.73.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • iPhone X (mobile) • 14600fa331f0aedd721951a90a5b901b4225f1ed • ios            • iOS 16.1 20B82
    • macOS (desktop)   • macos                                    • darwin-x64     • macOS 12.6 21G115 darwin-x64
    • Chrome (web)      • chrome                                   • web-javascript • Google Chrome 106.0.5249.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available
```

-Video Recording:
https://www.awesomescreenshot.com/video/12347346?key=aa09a0e0d74d940903be8bf11e59e3e3

**Comment by huycozy** [comment]
@vernalclareai Are you intending to open Whatsapp app? You can try using this parameter on `launchUrl`: `mode: LaunchMode.externalApplication`

<details>
<summary>Sample code</summary>

```dart
if (!await launchUrl(url, mode: LaunchMode.externalApplication)) {
  throw 'Could not launch $url';
}
```
</details>

**Comment by vernalclareai** [comment]
oh, great.
Let me try.
