### ISSUE TITLE
There seems to be a problem with parsing some json into a nested list

### ISSUE THREAD

**Issue by MdeBruin93** [flutter/flutter#114970]
The original problem is listed here:
https://stackoverflow.com/questions/74367969/flutter-parsing-data-to-nested-list-results-in-unhandled-exception-unsupporte

So today I decided to test this error on my Windows machine and just go for the web version of Flutter. For some reason it did not cause any issue. So far I haven't tested the solution on an Android device (neither physical or emulator) but it seems like there is a bug with deserializing lists into objects.

## Steps to Reproduce

- Create a Flutter project with both json_serializable and build_runner packages
- Create a class with the `@JsonSerializable()` annotation.
- Create a second class with the `@JsonSerializable()` annotation.
- Create a final field of type List<SecondClass> in your first class.
- Generate a fromJson method by using the buildrunner package.
- Put a JSON string into the fromJson method of your first class. It will throw an error

**Expected results:** 

A full initialized object containing the values from the JSON string.

**Actual results:** 

An error message indicating a list was created that was not growable:
"Unhandled Exception: Unsupported operation: Cannot add to a fixed-length list"

<details>
<summary>Code sample</summary>

`import 'package:equatable/equatable.dart';
import 'package:json_annotation/json_annotation.dart';

import 'user_game_language.dart';

part 'user.g.dart';

@JsonSerializable()
class User extends Equatable {
  /// Empty user which represents an unauthenticated user.
  static const empty = User(id: "", firebaseId: "", name: "", userName: "", gameLanguages: []);

  /// The current user's email address.
  // final String email;

  /// The current user's id.
  final String id;

  /// The current user's firebaseId.
  final String firebaseId;

  /// The current user's name (display name).
  final String name;

  /// The current user's username (identifier for adding as a friend).
  final String userName;

  /// The list of game languages the user is willing to participate in.
  final List<UserGameLanguage> gameLanguages;

  /// {@macro user}
  const User({required this.id, required this.firebaseId, required this.name, required this.userName, required this.gameLanguages});

  factory User.fromJson(Map<String, dynamic> json) => _$UserFromJson(json);

  bool get isEmpty => this == User.empty;
  bool get isNotEmpty => this != User.empty;

  @override
  List<Object> get props => [id, name, userName];
  Map<String, dynamic> toJson() => _$UserToJson(this);
}`

`part of 'user.dart';

const _$UserResponseCodeEnumMap = {
  UserResponseCode.ok: 0,
  UserResponseCode.notFound: 1,
  UserResponseCode.created: 2,
  UserResponseCode.conflict: 3,
};

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

User _$UserFromJson(Map<String, dynamic> json) => User(
      id: json['id'] as String,
      firebaseId: json['firebaseId'] as String,
      name: json['name'] as String,
      userName: json['userName'] as String,
      gameLanguages: (json['gameLanguages'] as List<dynamic>).map((e) => UserGameLanguage.fromJson(e as Map<String, dynamic>)).toList(),
    );

Map<String, dynamic> _$UserToJson(User instance) => <String, dynamic>{
      'id': instance.id,
      'firebaseId': instance.firebaseId,
      'name': instance.name,
      'userName': instance.userName,
      'gameLanguages': instance.gameLanguages.map((e) => e.toJson()).toList(),
    };`

`import 'package:json_annotation/json_annotation.dart';

part 'user_game_language.g.dart';

enum GameLanguage {
  @JsonValue(0)
  english,

  @JsonValue(1)
  dutch
}

@JsonSerializable()
class UserGameLanguage {
  final int priority;
  final GameLanguage gameLanguage;

  UserGameLanguage(this.priority, this.gameLanguage);

  factory UserGameLanguage.fromJson(Map<String, dynamic> json) => _$UserGameLanguageFromJson(json);
  Map<String, dynamic> toJson() => _$UserGameLanguageToJson(this);

  @override
  String toString() {
    return "Priority $priority, GameLanguage $gameLanguage";
  }
}
`

`// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'user_game_language.dart';

const _$GameLanguageEnumMap = {
  GameLanguage.english: 0,
  GameLanguage.dutch: 1,
};

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

UserGameLanguage _$UserGameLanguageFromJson(Map<String, dynamic> json) => UserGameLanguage(
      json['priority'] as int,
      $enumDecode(_$GameLanguageEnumMap, json['gameLanguage']),
    );

Map<String, dynamic> _$UserGameLanguageToJson(UserGameLanguage instance) => <String, dynamic>{
      'priority': instance.priority,
      'gameLanguage': _$GameLanguageEnumMap[instance.gameLanguage]!,
    };
`

`    var langs = (json["model"]["gameLanguages"] as List<dynamic>).map((e) => UserGameLanguage.fromJson(e)).toList();
      var userlanggame = UserGameLanguage(1, GameLanguage.english);
      langs.add(userlanggame);
      ILoggingService.instance.info(langs.toString());`

</details>

<details>
  <summary>Logs</summary>

[√] Flutter (Channel stable, 3.3.7, on Microsoft Windows [Version 10.0.22621.819], locale nl-NL)
    • Flutter version 3.3.7 on channel stable at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e99c9c7cd9 (8 days ago), 2022-11-01 16:59:00 -0700
    • Engine revision 857bd6b74c
    • Dart version 2.18.4
    • DevTools version 2.15.0

    • Flutter extension version 3.52.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22621.819]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 107.0.5304.88
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 107.0.1418.35

[√] HTTP Host Availability
    • All required HTTP hosts are available

</details>

**Comment by danagbemava-nc** [comment]
Hi @MdeBruin93, `build_runner` and `json_serializable` are third-party packages. Any issues that stem from using them should be reported on their dedicated repos. 

In light of this, I'll be closing this issue as this is out of the scope of the flutter repo. 

Thank you

**Comment by MdeBruin93** [comment]
Hi @danagbemava-nc , I don't think the included code contains anything that is not plain Dart code. So I've used those packages to generate the file and code, but it's still plain Dart code for as far as I can tell.

**Comment by danagbemava-nc** [comment]
Then the issue should be reported on the dart/sdk repo as that will be the best place for issues with the language itself.

**Comment by MdeBruin93** [comment]
Ok, thanks for your reply. I will report the issue there, thank you and have a good one.
