### ISSUE TITLE
Debugging doc is out of date

### ISSUE THREAD

**Issue by Sfshaza** [flutter/flutter#11491]
Travis complained about these broken links in debugging/index.md:

*  External link https://docs.flutter.io/flutter/rendering/Layer/debugFillDescription.html failed: 404 No error
*  External link https://docs.flutter.io/flutter/widgets/Widget/debugFillDescription.html failed: 404 No error

I removed these links to make Travis happy, but Ian tells me that the page needs updating.

@jacob314

**Comment by jacob314** [comment]
Created pull request to address this.
https://github.com/flutter/website/pull/647
