### ISSUE TITLE
Scrollable TabBar ignores taps while transition is in progress

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#11495]
## Steps to reproduce
1. Open the gallery app
1. Enable slow animations in the hamburger menu
1. Go to the "Scrollable Tabs" demo
1. Click on the last tab.
1. While transition is in progress, tap on the first tab again

## Result
The last tap is ignored.

The reason for this is probably that the Scrollable introduces an IgnorePointer widget that is set to ignore while the animation is in progress.

**Comment by goderbauer** [comment]
I landed a partial fix for this in #11503. That one will make TabBars more responsive if a click on a tab doesn't trigger a scroll animation.

If a click on a tab triggers a scroll animation, it's a different story: Currently, tabs become unresponsive to clicks while the scroll animation is in progress because instead the click will stop the animation (this is the default behavior for scrolling). However, I think we need to differentiate between two types of scroll animations:

1. A scroll animation that was triggered by a user-issued scroll gesture (e.g. a fling from the user). In this case, a click should stop the animation and not trigger a tab switch (i.e. you get the default scrolling behavior).
2. The scroll animation was triggered because the user clicked on a different tab (it then animates to scroll the selected tab into the center). During this animation, a click on another tab should actually switch to that tab (the rational is: the user didn't trigger the scroll, so it's kinda surprising that a click on another tab is ignored)

The behavior seemed to be what the OEM Material TabBar is doing on iOS. It makes the TabBar feel way more responsive.

**Comment by VladyslavBondarenko** [comment]
Persists with current master `1.21.0-6.0.pre.129`

<details>
 <summary>code sample</summary>

```
import 'package:flutter/material.dart';
import 'package:flutter/scheduler.dart';

void main() {
  timeDilation = 5;
  runApp(TabBarDemo());
}

class TabBarDemo extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: DefaultTabController(
        length: 10,
        child: Scaffold(
          appBar: AppBar(
            bottom: TabBar(
              tabs: List.generate(10, (index) => Tab(text: 'Tab title')),
              isScrollable: true,
            ),
            title: Text('Tabs Demo'),
          ),
          body: TabBarView(
            children: List.generate(10, (index) => Center(child: Text('Tab content'))),
          ),
        ),
      ),
    );
  }
}
```

</details>

<details>
 <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.21.0-6.0.pre.129, on Mac OS X 10.15.6 19G73, locale en-GB)
    • Flutter version 1.21.0-6.0.pre.129 at /Users/nevercode/dev/flutter
    • Framework revision 30aef0a3b9 (12 hours ago), 2020-07-30 14:20:21 -0700
    • Engine revision a9910e409c
    • Dart version 2.10.0 (build 2.10.0-1.0.dev 24c7666def)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/nevercode/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (5 available)
    • Redmi Note 7 (mobile)       • 6345c469                                 • android-arm64  • Android 9 (API 28)
    • Nevercode’s iPhone (mobile) • b668e524315069f3db3661ac11ff1f66afafebdb • ios            • iOS 13.6
    • macOS (desktop)             • macos                                    • darwin-x64     • Mac OS X 10.15.6 19G73
    • Web Server (web)            • web-server                               • web-javascript • Flutter Tools
    • Chrome (web)                • chrome                                   • web-javascript • Google Chrome 84.0.4147.105

• No issues found!
```

</details>

**Comment by Piinks** [comment]
I am going to de-dupe this with [#42588](https://github.com/flutter/flutter/issues/42588) to consolidate. Please follow that issue for updates, thank you!
