### ISSUE TITLE
Chip label is unreadable

### ISSUE THREAD

**Issue by paolosoares** [flutter/flutter#11496]
## Steps to Reproduce

1. Create an app with a Chip:
```
new Chip(label: new Text('Potatossaurus'))
```
2. Check its tooltip message. It should be something like:
```
Tooltip("Delete "Text("Potatossaurus")""; vertical offset: 24.0; position: below)
```
I believe the intended message should be "Delete Potatossaurus". That's complicated, though, because there's no common way of widget to describe itself, specially since a Chip's label can be any type of widget.

**Comment by Hixie** [comment]
Oh my. That's unfortunate.

**Comment by Hixie** [comment]
We could maybe pull the text out of the semantics logic...

**Comment by paolosoares** [comment]
I suggest introducing the tool tip message as a optional parameter. 

It would also help with providing internationalized tool tips.

**Comment by Hixie** [comment]
I've just changed it to "Delete" for now.
