### ISSUE TITLE
[CP][Infra] Use 3pp go dashing package

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#114944]
### issue_link

https://github.com/flutter/flutter/issues/114906

### Commit Hash

https://flutter-review.git.corp.google.com/c/recipes/+/35820

### Target

stable

### pr_link

https://flutter-review.git.corp.google.com/c/recipes/+/35841

### Impacted Users

Infra cannot build the docs without this swap

### Impact Description

Docs will not be updated with new hotfixes.

### Workaround

No.

### Risk

low

### Test Coverage

yes

### Validation Steps

This will get the docs builders back to green on infra

**Comment by CaseyHillers** [comment]
\cc @godofredoc @itsjustkevin I created this to track the infra CPs necessary for the docs builders to pass

**Comment by godofredoc** [comment]
We need another CP for docs to work correctly. Let me send it

**Comment by godofredoc** [comment]
Link to flutter/flutter cherry pick: https://github.com/flutter/flutter/pull/114947

**Comment by CaseyHillers** [comment]
Released in 3.3.8
