### ISSUE TITLE
Consider faster (maybe less accurate) way of handling color on older devices

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#11492]
When we improved our color correctness on older Android devices, we took a ~10% performance hit on rasterization.

We should consider a faster way to approximate color correctness for older devices. For example, we could color-correct images on decode (where it's particularly noticeable), but not worry about color-correct gradients. It's likely older devices don't have a precise idea of their screen's color response anyway.

**Comment by eseidelGoogle** [comment]
FYI @chinmaygarde @j9brown

**Comment by chinmaygarde** [comment]
The render to texture phase was removed in https://github.com/flutter/engine/pull/4355.
