### ISSUE TITLE
Android Emulator Not An Option In Flutter

### ISSUE THREAD

**Issue by CharlesCleveJr** [flutter/flutter#11493]
I've updated all the components and and `flutter upgrade` but can not get my android emulator to be an option like iOS emulator is.  I've updated my Android Studio components thinking that may be it but it didn't work either.  Here is my flutter doctor...

Macbooks-MacBook-Pro:~ Macbook$ flutter doctor
[✓] Flutter (on Mac OS X 10.11.6 15G1010, locale en, channel alpha)
    • Flutter at /Users/Macbook/flutter
    • Framework revision bbcfb8d51a (25 hours ago), 2017-08-01 14:50:29 -0700
    • Engine revision f2af347363
    • Tools Dart version 1.25.0-dev.7.0

[✓] Android toolchain - develop for Android devices (Android SDK 23.0.1)
    • Android SDK at /Users/Macbook/Library/Android/sdk
    • Platform android-23, build-tools 23.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.2.1)
    • Xcode at /Users/Macbook/Downloads/Xcode.app/Contents/Developer
    • Xcode 8.2.1, Build version 8C1002
    • ios-deploy 1.9.1
    • CocoaPods version 1.0.1

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.2)
    • Flutter plugin version 16.0
    • Dart plugin version 172.3317.48

[✓] Connected devices
    • None

**Comment by eseidelGoogle** [comment]
Does your emulator show up in `adb devices`?

**Comment by CharlesCleveJr** [comment]
No..  Can you point out how to navigate and add them.

**Comment by devoncarew** [comment]
@CharlesCleveJr, I would open Android Studio, and from there go to `Tools > Android > AVD Manager`. That will allow you to create AVDs (if none currently exist), and launch them.

Once AVDs exist, you can open them from the IntelliJ device selector (just like the IOS simulator option). That functionality will show up if you're on the `master` channel of flutter (and may have just been pushed to the `alpha` channel).

**Comment by Hixie** [comment]
Closing as covered by https://github.com/flutter/flutter/issues/13379
