### ISSUE TITLE
biometricOnly: true / I wish the phone pin & pattern only function was added as an option

### ISSUE THREAD

**Issue by jaeminlee-dev** [flutter/flutter#114954]
## Use case
​​​​​​​​​​​When developing a function to log in by receiving the authentication information of the mobile phone, there was a need to save the authentication information.
The phone pin, pattern, and biometric must be stored separately.
AuthenticationOptions(biometricOnly: true) I couldn't find a function that can authenticate only a pattern other than this.

## Proposal
phone pin & pattern only function add as an option

**Comment by stuartmorgan** [comment]
> there was a need to save the authentication information.
> The phone pin, pattern, and biometric must be stored separately.

I'm not clear on what this means; `local_auth` doesn't provide you any data to store, it just indicates success/failure. So I'm not sure what the use case here actually is.

> phone pin & pattern only function add as an option

iOS doesn't provide any API for this, and the Android docs discourage it, so this isn't something we would build into `local_auth`.
