### ISSUE TITLE
Configure Cirrus CI as workload identity provider to avoid quarter GCP key renewal

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#114916]
With https://github.com/cirruslabs/cirrus-ci-docs/issues/979 being supported from Cirrus, we should be unblocked to enable workload identity federation. This will enable us workloads access to Google Cloud resources without using a service account key which need renewal every 3 months.

Doc to configure Cirrus CI as an identity provider: https://github.com/cirruslabs/cirrus-ci-docs/blob/master/docs/guide/supported-computing-services.md#workload-identity-federation
Google cloud doc: https://cloud.google.com/iam/docs/workload-identity-federation#impersonation

After that, we need to update the `gcp_credentials` in different repositories' .cirrus.yaml.

**Comment by yusuf-goog** [comment]
@keyonghan is this something your working on, or do you need someone to be assigned.

**Comment by keyonghan** [comment]
> @keyonghan is this something your working on, or do you need someone to be assigned.

No, this is not on my plate right now. Feel free to move around or pick it up. 
I guess @godofredoc moved this to ticket queue to call attention? This is more like TD.

**Comment by godofredoc** [comment]
The reason this is in the ticket queue is because we have a gallery-flutter-dev request that have been open for over a year and it will require the same workflow.

**Comment by ricardoamador** [comment]
Are we using a new service account for this or are we reusing one that we already have?

**Comment by ricardoamador** [comment]
I am guessing this is what the internal tracking bug needs to enable:
![image](https://user-images.githubusercontent.com/32242716/232166781-9675b153-faf7-48e0-b8eb-7d96305029c3.png)

**Comment by godofredoc** [comment]
That is correct!

**Comment by ricardoamador** [comment]
Okay cool. Then I just need to follow up again on the buganizer issue.

**Comment by ricardoamador** [comment]
I'm going to move this to blocked but leave it assigned to myself so that I can follow up.

**Comment by ricardoamador** [comment]
Well since we are removing cirrus, we can close this. @godofredoc okay to close this now?

**Comment by godofredoc** [comment]
Done!
