### ISSUE TITLE
Medium and large AppBars with Material 3

### ISSUE THREAD

**Issue by JGeek00** [flutter/flutter#114907]
https://github.com/flutter/flutter/issues/91605

I have developed an application using the Material 3 theme. According to the material.io documentation, the AppBar implementation in Flutter is finished, but I don't see how to implement that new medium and large AppBars on my app using Flutter.
https://m3.material.io/components/top-app-bar/overview

Could someone help me? Thanks.

**Comment by danagbemava-nc** [comment]
Hi @JGeek00, see the links below for how to implement this.

https://api.flutter.dev/flutter/material/SliverAppBar/SliverAppBar.large.html
https://api.flutter.dev/flutter/material/SliverAppBar/SliverAppBar.medium.html

I'll be closing this as it is already documented in the framework. 

Thank you

**Comment by JGeek00** [comment]
Thanks @danagbemava-nc
