### ISSUE TITLE
Samsung Keyboard Issue

### ISSUE THREAD

**Issue by m1narulal1** [flutter/flutter#114974]
I'm facing this issue with Samsung keyboard. When I trying to Delete some text, but it's not deleting. It's happening when I'm dismiss keyboard once. For the first time it's working. But if dismissed once after that it's not working. Attached video given Please check and resolve.

https://user-images.githubusercontent.com/97874972/200847302-98ce9b45-91e9-44db-846f-0dbac83691b9.mp4

**Comment by huycozy** [comment]
Hi @m1narulal1, 
Does the issue persist on a minimal sample code with only a TextField? If not so, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this. 
Also, please provide the output of `flutter doctor -v` and device information as well.

**Comment by m1narulal1** [comment]
TextField:
Padding(
                                padding: const EdgeInsets.all(24.0),
                                child: CustomTextField(
                                    hintText:
                                        (accountTypes[1].isSelected == false)
                                            ? selectedAccountType!
                                                .paymentTypeDescription.tr
                                                .toString()
                                            : selectedMobileAccountType!
                                                    .paymentTypeDescription
                                                    .isNotEmpty
                                                ? selectedMobileAccountType!
                                                    .paymentTypeDescription.tr
                                                    .toString()
                                                : selectedAccountType!
                                                    .paymentTypeDescription.tr
                                                    .toString(),
                                    textController: accountTypeController,
                                    suffixIcon: Offstage(),
                                    focusNode: FocusNode()),
                              ),
CustomTextField Class:
import 'package:flutter/material.dart';
import 'package:get/get_utils/src/extensions/internacionalization.dart';
import 'package:titosapp/util/CustomColor.dart';
import 'package:titosapp/util/TextStyles.dart';

class CustomTextField extends StatelessWidget {
  final TextEditingController textController;

  //final Function onChanged;
  final String hintText;
  final bool obscureText;
  final bool autofocus;
  final TextInputType keyboardType;
  final bool readOnly;
  final FocusNode focusNode;
  final Color fillColor;
  Widget suffixIcon;

  CustomTextField(
      {this.obscureText = false,
      this.hintText = '',
      required this.textController,
      this.autofocus = false,
      this.keyboardType = TextInputType.text,
      this.readOnly = false,
      required this.suffixIcon,
      required this.focusNode,
      this.fillColor = CustomColor.colorGrey});

  Widget build(BuildContext _context) {
    return Container(
      child: TextFormField(
        focusNode: focusNode,
        cursorColor: Colors.black,
        keyboardType: keyboardType,
        obscureText: obscureText,
        controller: textController,
        decoration: InputDecoration(
          suffixIconConstraints: BoxConstraints(minHeight: 30, minWidth: 30),
          contentPadding: EdgeInsets.all(15),
          isDense: true,
          filled: true,
          fillColor: CustomColor.colorGrey,
          suffixIcon: Padding(
            padding: const EdgeInsets.only(right: 15.0),
            child: suffixIcon,
          ),
          hintText: hintText.tr,
          hintStyle: TextStyles.textStyleRegular,
          focusedBorder: OutlineInputBorder(
            borderSide: BorderSide.none,
            borderRadius: BorderRadius.circular(5),
            // borderSide: BorderSide(color: CustomColor.myCustomBlack, width: 2),
          ),
          enabledBorder: OutlineInputBorder(
            borderSide: BorderSide.none,

            borderRadius: BorderRadius.circular(5),
            // borderSide: BorderSide(color: CustomColor.myCustomBlack, width: 2),
          ),
          border: OutlineInputBorder(
            borderSide: BorderSide.none,

            borderRadius: BorderRadius.all(Radius.circular(5)),
            // borderSide:
            //     BorderSide(color: CustomColor.myCustomBlack, width: 2)
          ),
        ),
      ),
    );
  }
}
flutter doctor -v
[✓] Flutter (Channel stable, 3.3.6, on macOS 13.0 22A380 darwin-arm, locale en-IN)
    • Flutter version 3.3.6 on channel stable at /Users/technoexponentios9/Dev/Flutter/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6928314d50 (2 weeks ago), 2022-10-25 16:34:41 -0400
    • Engine revision 3ad69d7be3
    • Dart version 2.18.2
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/technoexponentios9/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] Connected device (3 available)
    • Minarul’s iPhone (mobile) • 00008020-000A742201E8402E • ios            • iOS 16.1 20B82
    • macOS (desktop)           • macos                     • darwin-arm64   • macOS 13.0 22A380 darwin-arm
    • Chrome (web)              • chrome                    • web-javascript • Google Chrome 107.0.5304.87

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Comment by huycozy** [comment]
@m1narulal1 
For the issue to be workable, it needs to be reproducible with a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code. Please provide such a sample.
Also, you can try creating a simple sample code with only a TextField to check if the issue still persists.
