### ISSUE TITLE
Windows bots need Salt Configuration Updates

### ISSUE THREAD

**Issue by ricardoamador** [flutter/flutter#114939]
The windows bots in the prod and staging pools need updates to the configuration in order to bring them back online. The salt minion cannot talk with the master. We need to set the config so that the minion starts on reboot.

flutter-win-1
flutter-win-2
flutter-win-3
flutter-win-4
flutter-win-5
flutter-win-6

https://docs.saltproject.io/salt/install-guide/en/latest/topics/install-by-operating-system/windows.html

**Comment by ricardoamador** [comment]
flutter-win-3 has been updated and is able to access the salt master. However the password for the swarming user has expired.

**Comment by ricardoamador** [comment]
Windows 1,2, and 4 have been updated. Win-6 is unreachable and Win-5 cannot be vnc'ed.

**Comment by nehalvpatel** [comment]
Any update on this?

**Comment by nehalvpatel** [comment]
6 should be reachable now

**Comment by yusuf-goog** [comment]
This should be complete now.
