### ISSUE TITLE
Remove external dependencies from Flutter like fonts.gstatic.com

### ISSUE THREAD

**Issue by IchordeDionysos** [flutter/flutter#115072]
## Use case

When building B2B applications using Flutter, often there is a need for putting all domains on an allow-list.

This becomes complicated when Flutter tries to fetch from certain domains to get additional resources examples of this include:
- unkpg.com (for fetching CanvasKit resources)
- [fonts.gstatic.com](https://github.com/search?q=repo%3Aflutter%2Fengine+gstatic&type=code)
- fonts.googleapis.com (https://fonts.googleapis.com/css2?family=Noto+Sans+Symbols)

## Proposal

Instead of fetching from a third-party domain, include the resources required in the final build output directory during the build process, so I can be served from the Web App that hosts Flutter instead of relying on an external resource/domain.

Then the assets would be fetched from:
`/flutter_assets/fonts/s/roboto/v20/KFOmCnqEu92Fr1Me5WZLCzYlKw.ttf` instead of `https://fonts.gstatic.com/s/roboto/v20/KFOmCnqEu92Fr1Me5WZLCzYlKw.ttf`

**Comment by exaby73** [comment]
Hello @IchordeDionysos. For cavaskit, you can use `--dart-define=FLUTTER_WEB_CANVASKIT_URL=/canvaskit/` to use the bundled canvaskit. As far as I am aware, there isn't any option for configuring fonts. As a workaround, you could use a proxy layer like nginx for this.

Labeling this issue for further insights from the team

**Comment by yjbanov** [comment]
This is covered by the following two issues:

- https://github.com/flutter/flutter/issues/112827
- https://github.com/flutter/flutter/issues/85793
