### ISSUE TITLE
[CP] 35960: Process docs as stable on release candidate branches.

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#115098]
### issue_link

https://github.com/flutter/flutter/issues/114900

### Commit Hash

745cefff908d46f93a8c8fca84c720d8d46a7295

### Target

beta

### pr_link

https://flutter-review.git.corp.google.com/c/recipes/+/35961

### Impacted Users

all api documentation users

### Impact Description

Docs not being indexed by search engines.

### Workaround

None

### Risk

low

### Test Coverage

yes

### Validation Steps

Tested manually

**Comment by itsjustkevin** [comment]
@CaseyHillers

**Comment by itsjustkevin** [comment]
@godofredoc  Do we still need this cherry-pick?

**Comment by godofredoc** [comment]
If flutter-3.4-candidate.34 is not going to be promoted to stable we can close this CP request.
