### ISSUE TITLE
[go_router] `GoRouteData` has incorrect link to typed routes documentation

### ISSUE THREAD

**Issue by m-causevic** [flutter/flutter#115078]
On the docs page for the [`GoRouteData` ](https://pub.dev/documentation/go_router/latest/go_router/GoRouteData-class.html) class, there's a link mentioned in the description, which is supposed to go to https://gorouter.dev/typed-routing but that page doesn't seem to exist, because I get redirected to https://pub.dev/packages/go_router. I had no luck finding any docs or examples on the topic of typed routing. 

I am also aware of the existence of [`TypedGoRoute`](https://pub.dev/documentation/go_router/latest/go_router/TypedGoRoute-class.html) class whose purpose, as it seems to me, is to be used as an annotation with code generation tools. Unfortunately, I really don't have a clue how this is supposed to be utilised in a project, so an example usage or more detailed docs would be of great help. 

Thanks

**Comment by exaby73** [comment]
Hello @m-causevic. You can find the documentation for this [here](https://pub.dev/packages/go_router_builder). Closing this issue as this is not a valid one. If you disagree with my decision, please comment and I can reopen it. Thank you

**Comment by m-causevic** [comment]
> Hello @m-causevic. You can find the documentation for this [here](https://pub.dev/packages/go_router_builder). Closing this issue as this is not a valid one. If you disagree with my decision, please comment and I can reopen it. Thank you

Thank you for pointing me to the go_router_builder package, now it all makes perfect sense! I still think it would be nice if the broken link in `GoRouteData` docs was fixed, e.g. to lead to the go_router_builder package page.

**Comment by exaby73** [comment]
I can see the link is incorrect. Thank you

**Comment by chunhtai** [comment]
fixed by https://github.com/flutter/packages/pull/2789
