### ISSUE TITLE
DeviceLab Mac_ios builds fail intermittently due to codesign failure

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#115035]
This is happening on multiple bots and causes flakes:
Mac6: https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_ios%20complex_layout_ios__compile/7832/overview
mac-25: https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_ios%20color_filter_and_fade_perf_impeller_ios__e2e_summary/1270/overview
Mac-27: https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_ios%20integration_test_test_ios/7445/overview

```
Exception: Error (Xcode): Target release_unpack_ios failed: Exception: Failed to codesign
```

**Comment by ricardoamador** [comment]
Closing as a duplicate. The code signing investigation and fix is being tracked in 115000.

**Comment by keyonghan** [comment]
Some observation:
1)Each bot (which hit the codesign issue) would resume by itself and run subsequent ~10-20 tests successfully and then may hit the issue again.
2)From the log side, I do not see much useful info, but below about `Failed to build iOS app`
```
[   +7 ms] Failed to build iOS app
[backdrop_filter_perf_impeller_ios__timeline_summary] [STDOUT] stderr: [        ] Could not build the precompiled application for the device.
[backdrop_filter_perf_impeller_ios__timeline_summary] [STDOUT] stderr: [   +2 ms] Error (Xcode): [   +6 ms] Target profile_unpack_ios failed: Exception: Failed to codesign /opt/s/w/ir/x/w/recipe_cleanup/tmpmm3tldiv/flutter sdk/dev/benchmarks/macrobenchmarks/build/ios/Profile-iphoneos/Flutter.framework/Flutter with identity aaaaaaaaa.
[backdrop_filter_perf_impeller_ios__timeline_summary] [STDOUT] stderr: 
```

For 1) I vnc to the bot, and found sometimes the bot is with many duplicated certificates. Not sure if this may cause the failure when the number goes beyond a limit.
![Screen Shot 2022-11-10 at 9 14 58 AM](https://user-images.githubusercontent.com/54558023/201162455-06dd9257-561c-47fb-8f34-98ee015f58b1.png)
For 2) is there any way we can enable more logs? /cc @jmagman I would like to repro locally on a bot to see any findings. The certificate is indeed valid returning the same identify as the one complained in the log.
```
security find-identity -p codesigning -v
  1) aaaaaaaa "Apple Development: Flutter Devicelab (aaaaaaa)"
     1 valid identities found
```

**Comment by keyonghan** [comment]
This is heavily affecting multiple tests, bumping to P1.

**Comment by keyonghan** [comment]
There has been a bug from our salt provisioning script, which caused duplicated certificates to be installed. I suspect this caused the `keychain unlock` issue.

Submitted salt/618547

**Comment by keyonghan** [comment]
Haven't seen any flake due to code sign error since the salt fix CL. Closing.
