### ISSUE TITLE
Paint.cc methods to fill an SkPaint or a DlPaint are inefficient for the Paragraph code

### ISSUE THREAD

**Issue by flar** [flutter/flutter#115034]
For historic reasons, the methods in the native object for ui.Paint can fill a native SkPaint or DlPaint object with the corresponding native attributes, but the interface was created to serve the needs of the ui.Canvas native methods. To that end, the methods will assume that the native paint objects are filled with defaults before they transfer the values from the ui.Paint arrays. This meets the needs of the ui.Canvas native methods which will create a new SkPaint on each method call.

For the paragraph code, the TextStyle native object has SkPaint/DlPaint fields, and needs them initialized from the ui.Paint object, but those fields may be reused and contain stale data from a previous run - so the methods that update the style object must first transfer the data from the ui.Paint object into a "fresh" native paint object and then copy that temp object into the field. It would be more convenient if the field could be more directly initialized by the ui.Paint filler method.

See: https://github.com/flutter/engine/blob/722414a267dab88e9d347a15adcbd5c5667c0956/lib/ui/text/paragraph_builder.cc#L472
See: https://github.com/flutter/engine/blob/722414a267dab88e9d347a15adcbd5c5667c0956/lib/ui/text/paragraph_builder.cc#L481

**Comment by endless7** [comment]
Hi, @flar. Is it appropriate for https://github.com/flutter/engine/pull/37955? Or I need to check every value and set them nil if the `DartByteData` didn't contain it?

**Comment by flar** [comment]
I'm going to close this issue as I don't think there is a simple way to make this faster without a lot of restructuring of various objects or adding a lot of code for minimal benefit.
