### ISSUE TITLE
Running flutter doctor output Error: Error when reading 'packages/flutter_tools/.packages': The system cannot find the file specified.  bin/cache/flutter_tools.snapshot: Error: Error when reading 'bin/cache/flutter_tools.snapshot': The system cannot find the file specified.

### ISSUE THREAD

**Issue by henseljahja** [flutter/flutter#115067]
OS:
Edition	Windows 11 Pro
Version	22H2
Installed on	‎11/‎5/‎2022
OS build	22621.819
Experience	Windows Feature Experience Pack 1000.22636.1000.0

Flutter Version : 3.3.8

I just downloaded and installed the Flutter 3.3.8 and extract it into D:\tools\flutter, but when im trying to run flutter doctor, it always output

```
Building flutter tool...
Running pub upgrade...
Cannot open file, path = 'pubspec.lock' (OS Error: The parameter is incorrect.
, errno = 87)
Error (66): Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (9 tries left)
```
and outputing those till it breaks, currently i have no admin privileges for this machine, does anyone have a solution?

**Comment by ravimandal06** [comment]
System Variable issues:

Edit the environment variable path in system properties 
add new flutter bin path in system variable 
ex:  <    C:\src\flutter\flutter\bin    >

**Comment by henseljahja** [comment]
> System Variable issues:
> 
> Edit the environment variable path in system properties add new flutter bin path in system variable ex: < C:\src\flutter\flutter\bin >

Already did, heres the output
```
PS C:\Users\hensel.jahja> where.exe flutter dart
D:\flutter\bin\flutter
D:\flutter\bin\flutter.bat
D:\flutter\bin\dart
D:\flutter\bin\dart.bat
```

**Comment by henseljahja** [comment]
Closed,

So I've been usingthe flutter sdk from the [Flutter Releases Page](https://docs.flutter.dev/development/tools/sdk/releases), but ive switched to clone the flutter repo master channel instead, and the problem gone, dont know why this behavior happend.
