### ISSUE TITLE
 Error (Xcode): failed to emit precompiled header .../Runner/Runner-Bridging-Header.h'

### ISSUE THREAD

**Issue by seitzventures** [flutter/flutter#115071]
I spent almost a week on this. It just makes no sense. I always get the same error. 

Runner
```
failed to emit precompiled header '/Users/.../Xcode/DerivedData/Runner-degwsatxwslssqfnajocckejvrqi/Build/Intermediates.noindex/PrecompiledHeaders/Runner-Bridging-Header-swift_3QLD7RMWSDAD0-clang_2DSDA8C9CPQUA.pch' for bridging header '.../ios/Runner/Runner-Bridging-Header.h'

in file included from .../ios/Runner/Runner-Bridging-Header.h:1:
.../ios/Runner/GeneratedPluginRegistrant.h
.../ios/Runner/GeneratedPluginRegistrant.h:10:9 'Flutter/Flutter.h' file not found

```

**Comment by seitzventures** [comment]
`name: xyz
description: A new Flutter project.

publish_to: "none"

version: 1.0.0

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  amazon_cognito_identity_dart_2: ^3.0.0
  animated_text_kit: ^4.2.1
  async: ^2.8.2
  audio_session: ^0.1.6+1
  auto_size_text: ^3.0.0
  bloc: ^8.0.3
  bloc_concurrency: ^0.2.0
  bloc_test: ^9.0.1
  build_runner: ^2.1.7
  cached_network_image: ^3.2.0
  carousel_slider: ^4.0.0
  collection: ^1.16.0
  connectivity_plus: ^2.1.0
  cupertino_icons: ^1.0.4
  custom_sliding_segmented_control: ^1.4.0
  device_info: ^2.0.3
  devicelocale: ^0.5.0
  dio: ^4.0.4
  distance:
    path: packages/distance
  either:
    path: packages/either
  equatable: ^2.0.3
  firebase_analytics: ^9.3.3
  firebase_auth: ^3.3.3
  firebase_auth_mocks: ^0.8.1
  firebase_core: ^1.10.5
  firebase_crashlytics: ^2.8.1
  firebase_database: ^9.0.3
  fl_chart: ^0.55.1
  flow_builder: ^0.0.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  flutter_displaymode: ^0.4.0
  flutter_launcher_icons: ^0.9.2
  flutter_localizations:
    sdk: flutter
  flutter_speed_dial: ^6.0.0
  flutter_svg: ^1.0.0
  flutter_tts: ^3.2.2
  flutter_vector_icons: ^2.0.0
  freezed_annotation: ^2.0.3
  geolocator: ^9.0.0
  get_it: ^7.2.0
  google_fonts: ^3.0.1
  google_maps_flutter: ^2.2.1
  gps_service:
    path: packages/gps_service
  gpx: ^2.1.0
  http: ^0.13.4
  hydrated_bloc: ^9.0.0-dev.3
  image_picker: ^0.8.4+5
  in_app_purchase: ^3.0.1
  in_app_purchase_android: ^0.2.3+5
  injectable: ^1.5.3
  intl: ^0.17.0
  json_annotation: ^4.7.0
  json_serializable: ^6.1.1
  just_audio: ^0.9.18
  location: ^4.4.0
  lzma: ^1.0.1
  ms_undraw: ^3.1.0+3
  oauth2: ^2.0.0
  package_info_plus: ^1.4.0
  path_provider: ^2.0.8
  rxdart: ^0.27.3
  shared_preferences: ^2.0.11
  shimmer: ^2.0.0
  speed:
    path: packages/speed
  syncfusion_flutter_charts: ^20.2.50
  uni_links: ^0.5.1
  url_launcher: ^6.0.17
  video_player: ^2.2.7
  visibility_detector: ^0.3.3
  volume_controller: ^2.0.4
  volume_watcher: ^2.0.1

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: 2.1.0+1
  injectable_generator: ^1.5.4
  mockito: ^5.0.16

flutter:
  uses-material-design: true

  assets:
    - assets/debug/
    - assets/
    - assets/illustrations/
    - assets/audio/
  ...
    - assets/audio/de/general/
    - assets/audio/en/general/
    - assets/coach/
    - assets/feed_page/
    - assets/profile_page/
    - assets/icon/
    - assets/logo/
    - assets/notification/
    - assets/iap_page/
    - assets/run_select_page/
...
    - assets/splash_page/
    - assets/svg/
    - assets/svg/icons/
    - assets/test/
    - assets/welcome_page/

  fonts:
    - family: SF-Pro
      fonts:
        - asset: fonts/SF-Pro-Display-Medium.ttf
        - asset: fonts/SF-Pro-Display-Bold-Italic.ttf
          style: italic
          weight: 700

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
`

**Comment by seitzventures** [comment]
`# Uncomment this line to define a global platform for your project

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  platform :ios, '12.0'
  use_frameworks!
  use_modular_headers!

  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
  pod 'Firebase/Crashlytics'
  pod 'Firebase/Analytics'

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

target 'xyz' do
  platform :watchos, '8.0'
  use_frameworks!
  use_modular_headers!
  
  pod 'Firebase/Crashlytics'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
        '$(inherited)',
        'AUDIO_SESSION_MICROPHONE=0'
      ]
    end
  end
end
`

**Comment by darshankawar** [comment]
@seitzventures 
In order to properly analyze this issue, please provide `flutter doctor -v`, complete error log in properly formatted text.

**Comment by beneelonsz** [comment]
`Flutter (Channel stable, 3.3.8, on macOS 13.0 22A380 darwin-arm, locale
    de-DE)
    • Flutter version 3.3.8 on channel stable at /Users/elon/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 52b3dc25f6 (35 hours ago), 2022-11-09 12:09:26 +0800
    • Engine revision 857bd6b74c
    • Dart version 2.18.4
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/elon/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.73.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.52.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.0 22A380 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 107.0.5304.87

[✓] HTTP Host Availability
    • All required HTTP hosts are available`

**Comment by seitzventures** [comment]
``Flutter (Channel stable, 3.3.8, on macOS 13.0 22A380 darwin-arm, locale
de-DE)
• Flutter version 3.3.8 on channel stable at /Users/elon/development/flutter
• Upstream repository https://github.com/flutter/flutter.git
• Framework revision https://github.com/flutter/flutter/commit/52b3dc25f6471c27b2144594abb11c741cb88f57 (35 hours ago), 2022-11-09 12:09:26 +0800
• Engine revision 857bd6b74c
• Dart version 2.18.4
• DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
• Android SDK at /Users/elon/Library/Android/sdk
• Platform android-33, build-tools 33.0.0
• Java binary at: /Applications/Android
Studio.app/Contents/jre/Contents/Home/bin/java
• Java version OpenJDK Runtime Environment (build
11.0.13+0-b1751.21-8125866)
• All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
• Xcode at /Applications/Xcode.app/Contents/Developer
• Build 14B47b
• CocoaPods version 1.11.3

[✓] Chrome - develop for the web
• Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
• Android Studio at /Applications/Android Studio.app/Contents
• Flutter plugin can be installed from:
🔨 https://plugins.jetbrains.com/plugin/9212-flutter
• Dart plugin can be installed from:
🔨 https://plugins.jetbrains.com/plugin/6351-dart
• Java version OpenJDK Runtime Environment (build
11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.73.1)
• VS Code at /Applications/Visual Studio Code.app/Contents
• Flutter extension version 3.52.0

[✓] Connected device (2 available)
• macOS (desktop) • macos • darwin-arm64 • macOS 13.0 22A380 darwin-arm
• Chrome (web) • chrome • web-javascript • Google Chrome 107.0.5304.87

[✓] HTTP Host Availability
• All required HTTP hosts are available``

**Comment by seitzventures** [comment]
Here is the terminal output....

[Failed to build iOS app.txt](https://github.com/flutter/flutter/files/9982321/Failed.to.build.iOS.app.txt)

**Comment by darshankawar** [comment]
@seitzventures 
Looking at the error log, the errors are pointing to third party plugins. So I suggest you to make sure all plugins you are using in your `pubspec.yaml` are on latest versions and then try to clear your flutter cache, flutter clean, make sure your pods are uptodate and try again to see if you still get the error or not.

This seems to be a caching issue.

**Comment by darshankawar** [comment]
Maybe try to recreate your `ios` folder and see if it helps.
I will close this issue for now, as this seems to be config / cache issue. If you are consistently able to replicate it using new project with any of the flutter first party plugins or framework code, write in comments and I'll reopen it.
