### ISSUE TITLE
Support for onDisconnect() in firebase_database

### ISSUE THREAD

**Issue by pauldemarco** [flutter/flutter#11508]
This is a feature request to add **[onDisconnect()](https://firebase.google.com/docs/database/android/offline-capabilities#how-ondisconnect-works)** to the [firebase_database](https://pub.dartlang.org/packages/firebase_database) plugin.

**Comment by pauldemarco** [comment]
I needed this for android today so I quickly implemented: https://github.com/pauldemarco/plugins

(Tests and iOS **not** included)

**Comment by rmarau** [comment]
@pauldemarco 
I've just picked your code and updated to the current master branch. Also added ios support. https://github.com/rmarau/plugins/

**Comment by rlee1990** [comment]
@rmarau @pauldemarco  any update on this

**Comment by rmarau** [comment]
https://github.com/flutter/plugins/pull/653 closes this issue.

**Comment by kroikie** [comment]
@pauldemarco

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/977. Any further collaboration will be done there.
