### ISSUE TITLE
(Xcode Build Failed) Could not build the precompiled application for the device. Swift Compiler Error (Xcode): Using bridging headers with module interfaces is unsupported

### ISSUE THREAD

**Issue by RainPixels** [flutter/flutter#115077]
Hi friends,

My Flutter doctor -v:

[✓] Flutter (Channel stable, 3.3.7, on macOS 13.0 22A380 darwin-arm, locale en-GB)
    • Flutter version 3.3.7 on channel stable at /Users/razvanu/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e99c9c7cd9 (9 days ago), 2022-11-01 16:59:00 -0700
    • Engine revision 857bd6b74c
    • Dart version 2.18.4
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/razvanu/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode-14.1.0-Release.Candidate.2.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.73.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.52.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 107.0.5304.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

• My pubspec.yaml:
[pubspec_yaml.txt](https://github.com/flutter/flutter/files/9980488/pubspec_yaml.txt)

• Error log text:
[error_log.txt](https://github.com/flutter/flutter/files/9980595/error_log.txt)

• Screenshot:
<img width="1504" alt="200957217-529f7907-c369-4d0f-bee7-4d9685facf7a" src="https://user-images.githubusercontent.com/103572833/201089411-68e2c407-e905-48ba-b9a3-d75acf6fce81.png">

###**THE PROBLEM**

After upgrading the Firebase packages, the iOS running/building fails (even after downgrading the packages, before no problems),
also I'm using Precompiled Firestore iOS SDK xcframework files extracted from the Firebase iOS SDK repository release downloads, tagged by Firebase iOS SDK version and presented as a consumable podspec, [firestore-ios-sdk-frameworks](https://github.com/invertase/firestore-ios-sdk-frameworks ) to speed up the build time on iOS.
I updated the firestore-ios-sdk-frameworks from **9.6.0** to **10.0.0**.

Please help me or guide me how to fix this issue, thanks in advance!

**Comment by exaby73** [comment]
Hello @RainPixels. This issue seems like an issue with Flutterfire rather than Flutter. I think it's best if this issue is raised in https://github.com/firebase/flutterfire/issues. Therefore, I am closing this issue. If you disagree, please comment and I can reopen this issue. Thank you.
