### ISSUE TITLE
Screen flickering on Android since Flutter 3.0.5

### ISSUE THREAD

**Issue by cj3479** [flutter/flutter#115089]
When I use my app .Sometimes it occur flickering screen on android platform.  It is Occasionally, I haven't stable path to reproduce the bug, the below is record scree

https://user-images.githubusercontent.com/9412601/201158166-50bcc95c-5420-473a-822d-de07953d5491.mp4

The below is android logcat.  Hope it helpful

[adb_logcat.txt](https://github.com/flutter/flutter/files/9983069/adb_logcat.txt)

[adb_logcat_1.txt](https://github.com/flutter/flutter/files/9983067/adb_logcat_1.txt)

flutter doctor -v
✓] Flutter (Channel stable, 3.0.5, on macOS 12.6 21G115 darwin-arm, locale zh-Hans-CN)
    • Flutter version 3.0.5 at /Users/chengjian/soft/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (4 个月前), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

**Comment by cj3479** [comment]
> When I use my app .Sometimes it occur flickering screen on android platform. It is Occasionally, I haven't stable path to reproduce the bug, the below is record scree
> 
>  4.mp4 
> The below is android logcat. Hope it helpful
> 
> [adb_logcat.txt](https://github.com/flutter/flutter/files/9983069/adb_logcat.txt)
> 
> [adb_logcat_1.txt](https://github.com/flutter/flutter/files/9983067/adb_logcat_1.txt)
> 
> flutter doctor -v ✓] Flutter (Channel stable, 3.0.5, on macOS 12.6 21G115 darwin-arm, locale zh-Hans-CN) • Flutter version 3.0.5 at /Users/chengjian/soft/flutter • Upstream repository https://github.com/flutter/flutter.git • Framework revision [f1875d5](https://github.com/flutter/flutter/commit/f1875d570e39de09040c8f79aa13cc56baab8db1) (4 个月前), 2022-07-13 11:24:16 -0700 • Engine revision e85ea0e79c • Dart version 2.17.6 • DevTools version 2.12.2

@zanderso

**Comment by huycozy** [comment]
Hi @cj3479 
To be more precise, please provide the information indicated below:
- Does this issue happen on the Flutter default sample project (counter app) on your device? 
- Device information (OS, model)
- The output of `flutter doctor -v`

Also, as far as I can see, you are using the old Flutter version `3.0.5`, the latest Flutter stable is `3.3.8` and the master is `3.6.0`. Please try upgrading them and retry to see if this issue still reproduces.

Thank you!

**Comment by cj3479** [comment]
> > When I use my app .Sometimes it occur flickering screen on android platform. It is Occasionally, I haven't stable path to reproduce the bug, the below is record scree
> > 4.mp4
> > The below is android logcat. Hope it helpful
> > [adb_logcat.txt](https://github.com/flutter/flutter/files/9983069/adb_logcat.txt)
> > [adb_logcat_1.txt](https://github.com/flutter/flutter/files/9983067/adb_logcat_1.txt)
> > flutter doctor -v ✓] Flutter (Channel stable, 3.0.5, on macOS 12.6 21G115 darwin-arm, locale zh-Hans-CN) • Flutter version 3.0.5 at /Users/chengjian/soft/flutter • Upstream repository https://github.com/flutter/flutter.git • Framework revision [f1875d5](https://github.com/flutter/flutter/commit/f1875d570e39de09040c8f79aa13cc56baab8db1) (4 个月前), 2022-07-13 11:24:16 -0700 • Engine revision e85ea0e79c • Dart version 2.17.6 • DevTools version 2.12.2
> 
> @zanderso can you help to see?

1. No. It never happen on the Flutter default sample project (counter app) on your device
2. Android 12 ,  Pixel 4
3. flutter doctor -v
✓] Flutter (Channel stable, 3.0.5, on macOS 12.6 21G115 darwin-arm, locale zh-Hans-CN)
• Flutter version 3.0.5 at /Users/chengjian/soft/flutter
• Upstream repository https://github.com/flutter/flutter.git
• Framework revision https://github.com/flutter/flutter/commit/f1875d570e39de09040c8f79aa13cc56baab8db1 (4 个月前), 2022-07-13 11:24:16 -0700
• Engine revision e85ea0e79c
• Dart version 2.17.6
• DevTools version 2.12.2


By the way. I upgrade skia to 3.3.7 and the issue does't reproduces  for the time being, but because the issue is accidental.
I am not sure whether 3.3.7  actually solve the issue

**Comment by cj3479** [comment]
> Hi @cj3479 To be more precise, please provide the information indicated below:
> 
> * Does this issue happen on the Flutter default sample project (counter app) on your device?
> * Device information (OS, model)
> * The output of `flutter doctor -v`
> 
> Also, as far as I can see, you are using the old Flutter version `3.0.5`, the latest Flutter stable is `3.3.8` and the master is `3.6.0`. Please try upgrading them and retry to see if this issue still reproduces.
> 
> Thank you!

- No. It never happen on the Flutter default sample project (counter app) on your device
- Android 12 , Pixel 4
- flutter doctor -v
✓] Flutter (Channel stable, 3.0.5, on macOS 12.6 21G115 darwin-arm, locale zh-Hans-CN)
• Flutter version 3.0.5 at /Users/chengjian/soft/flutter
• Upstream repository https://github.com/flutter/flutter.git
• Framework revision https://github.com/flutter/flutter/commit/f1875d570e39de09040c8f79aa13cc56baab8db1 (4 个月前), 2022-07-13 11:24:16 -0700
• Engine revision e85ea0e79c
• Dart version 2.17.6
• DevTools version 2.12.2
By the way. I upgrade skia to 3.3.7 and the issue does't reproduces for the time being, but because the issue is accidental.
I am not sure whether 3.3.7 actually solve the issue

**Comment by iapicca** [comment]
> * Flutter (Channel stable, 3.0.5, on macOS 12.6 21G115 darwin-arm, locale zh-Hans-CN)

@cj3479 
maybe is worth trying a `flutter upgrade -f`

**Comment by huycozy** [comment]
>By the way. I upgrade skia to 3.3.7 and the issue does't reproduces for the time being, but because the issue is accidental.

@cj3479 Please also retry on the latest master (`3.6.0`) channel. 
Also, it should be actionable with clear steps to reproduce the problem. Please try to dig into the issue by removing the 3rd plugins/packages if any, and isolating each element in the screen to find out where the issue is coming from (as it doesn't happen on the Flutter default sample project).

**Comment by shingohu** [comment]
3.0.5-3.3.8 all have this problem,this problem exists in iOS and Android, especially when platformview exists

**Comment by cj3479** [comment]
> > By the way. I upgrade skia to 3.3.7 and the issue does't reproduces for the time being, but because the issue is accidental.
> 
> @cj3479 Please also retry on the latest master (`3.6.0`) channel. Also, it should be actionable with clear steps to reproduce the problem. Please try to dig into the issue by removing the 3rd plugins/packages if any, and isolating each element in the screen to find out where the issue is coming from (as it doesn't happen on the Flutter default sample project).

It it not easy to reproduce the issue, I will upgrade the flutter check whether the issue exist
