### ISSUE TITLE
[Impeller] Generated shaders always use high precision.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#115044]
[Static analysis of Impeller shaders](https://github.com/chinmaygarde/malioc_impeller_reports) shows that ImpellerC [always uses high precision in generated shaders](https://github.com/chinmaygarde/malioc_impeller_reports/blob/8689f9cfe478b7e8dd0af867de7e70f60e021854/shaders/advanced_blend_exclusion.frag#L16). In all cases analyzed, this was entirely unnecessary. On lower end devices using [GPUs like Mali T720](https://github.com/chinmaygarde/malioc_impeller_reports/blob/8689f9cfe478b7e8dd0af867de7e70f60e021854/reports/Mali-T720/frag/advanced_blend_exclusion.frag.txt), this causes stack spills. These shaders will cause higher power draw and have lower throughput.

ImpellerC must default to using `mediump` for generated shaders and respect precision qualifiers in shader code.

**Comment by jonahwilliams** [comment]
This leaves `v_position` as highp, but I think we might want that?

**Comment by chinmaygarde** [comment]
We think this is fixed for all backends but Metal.

**Comment by chinmaygarde** [comment]
IMO, the situation now is more nuanced and we have the ability to control prevision on a per backend basis. Closing this as completed. cc @bdero @jonahwilliams in case there are missing items not already tracked in other issues.
