### ISSUE TITLE
differences between `flutter build aar` and `flutter build aar --release`

### ISSUE THREAD

**Issue by manza7014** [flutter/flutter#115051]
i have a same problem  as  this issue said [flutter build aar --release ,--release not work](https://github.com/flutter/flutter/issues/47762)
for the  answer below
 ```
jonahwilliams-macbookpro2:codegen jonahwilliams$ flutter build aar -h
Build a repository containing an AAR and a POM file.

By default, AARs are built for `release`, `debug` and `profile`.
The POM file is used to include the dependencies that the AAR was compiled against.
To learn more about how to use these artifacts, see https://flutter.dev/go/build-aar
```
_Originally posted by @jonahwilliams in https://github.com/flutter/flutter/issues/47762#issuecomment-582223344_
i want to ask what are the differences  between `flutter build aar` and `flutter build aar --release`

**Comment by jonahwilliams** [comment]
flutter build aar builds all variants. Flutter build aar --release only builds the release variant

**Comment by manza7014** [comment]
> flutter build aar builds all variants. Flutter build aar --release only builds the release variant
https://github.com/flutter/flutter/issues/47762#issuecomment-581729227
when run `flutter build aar --release` 
result:
```
manza:flutter_fund yongfeng.li$ clear
manza:flutter_fund yongfeng.li$ f build aar --release

💪 Building with sound null safety 💪

Running Gradle task 'assembleAarDebug'...                          18.7s
✓ Built build/host/outputs/repo.
Running Gradle task 'assembleAarProfile'...                        17.3s
✓ Built build/host/outputs/repo.
Running Gradle task 'assembleAarRelease'...                        11.7s
✓ Built build/host/outputs/repo.

Consuming the Module
  1. Open <host>/app/build.gradle
  2. Ensure you have the repositories configured, otherwise add them:

      String storageUrl = System.env.FLUTTER_STORAGE_BASE_URL ?: "https://storage.googleapis.com"
      repositories {
        maven {
            url '/Users/yongfeng.li/develop/WorkSpace/office-work/ysfund/flutter_fund/build/host/outputs/repo'
        }
        maven {
            url "$storageUrl/download.flutter.io"
        }
      }

  3. Make the host app depend on the Flutter module:

    dependencies {
      debugImplementation 'com.yskj.flutter_fund:flutter:1.0:debug'
      profileImplementation 'com.yskj.flutter_fund:flutter:1.0:profile'
      releaseImplementation 'com.yskj.flutter_fund:flutter:1.0:release'
    }


  4. Add the `profile` build type:

    android {
      buildTypes {
        profile {
          initWith debug
        }
      }
    }

To learn more, visit https://flutter.dev/go/build-aar
manza:flutter_fund yongfeng.li$ 

```

**Comment by manza7014** [comment]
> flutter build aar builds all variants. Flutter build aar --release only builds the release variant

obviously it's not only release variant,i don't know why

**Comment by manza7014** [comment]
@jonahwilliams

**Comment by jonahwilliams** [comment]
right, sorry - by default it builds all variants. so build aar --release and build aar do the same thing. You need to disable debug and profile with build aar --no-profile --no-debug

**Comment by manza7014** [comment]
ok, thanks

> right, sorry - by default it builds all variants. so build aar --release and build aar do the same thing. You need to disable debug and profile with build aar --no-profile --no-debug

**Comment by manza7014** [comment]
> ok, thanks
> 
> > right, sorry - by default it builds all variants. so build aar --release and build aar do the same thing. You need to disable debug and profile with build aar --no-profile --no-debug

i just want a confirm  of the official, the document is confused
