### ISSUE TITLE
A package created with the " flutter create --template=package" command, example folder is not generated

### ISSUE THREAD

**Issue by lizhuoyuan** [flutter/flutter#115057]
I used to create and upload packages. I used to have an example folder to help with testing, but now I create a package without an example folder. I don't know how to test my code.

**Comment by exaby73** [comment]
Hello @lizhuoyuan. You can run `flutter create example` and add your package in the `pubspec.yaml` using [path packages](https://dart.dev/tools/pub/dependencies#path-packages).

Could you post the full output of `flutter doctor -v` and also confirm which version have you used before that generated the example folder?

**Comment by lizhuoyuan** [comment]
Thanks for your reply, I want to show my process in full.
![image](https://user-images.githubusercontent.com/15923901/201255476-d7f7add3-4e19-493a-a47b-ad34b46b71fe.png)
and then:
<img width="373" alt="image" src="https://user-images.githubusercontent.com/15923901/201255540-113428e6-8e7b-4fb7-94d2-5ec5bb58f6f4.png">

```
flutter doctor -v
[✓] Flutter (Channel stable, 3.3.7, on macOS 13.0 22A380 darwin-x64, locale
    zh-Hans-CN)
    • Flutter version 3.3.7 on channel stable at
      /Users/lizhuoyuan/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e99c9c7cd9 (9 days ago), 2022-11-01 16:59:00 -0700
    • Engine revision 857bd6b74c
    • Dart version 2.18.4
    • DevTools version 2.15.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/lizhuoyuan/Library/Android/sdk
    • Platform android-33, build-tools 30.0.3
    • ANDROID_HOME = /Users/lizhuoyuan/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.69.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.44.0

[✓] Connected device (1 available)
    • V1938CT (mobile) • 000003f68e4afb4e • android-arm64 • Android 10 (API 29)

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

**Comment by exaby73** [comment]
Once you're in the `package_new` directory, you can create a new Flutter app using `flutter create example`. This should create a new Flutter app in a directory called `example`. You can then add the following dependency to `pubspec.yaml`.

```yaml
dependendies:
    package_new:
        path: ../
```

This you allow you to import your package like this:

```dart
import 'package:package_new/package_new.dart`;
```

Closing this issue as a solution has been provided. If you disagree, please comment and I can reopen it. Thank you.

**Comment by lizhuoyuan** [comment]
I feel that the example was generated directly before, and I want to know why the example is not generated automatically now

**Comment by exaby73** [comment]
Could you confirm which version was the example generated?
