### ISSUE TITLE
Flutter Pub get can not use Git depandent

### ISSUE THREAD

**Issue by Alembertcn** [flutter/flutter#115084]
### Evn
pubspec.yaml
name: testf
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  kittens:
   git: https://github.com/munificent/kittens.git
 ...

git --version
git version 2.33.0.windows.2

flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.2.3, on Active code page: 65001

Microsoft Windows [Version 10.0.22000.1098], locale zh-CN)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[√] Chrome - develop for the web
[√] Android Studio
[√] VS Code
[√] Connected device (2 available)

• No issues found!

flutter --version
Flutter 2.2.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f4abaa0735 (1 year, 4 months ago) • 2021-07-01 12:46:11 -0700
Engine • revision 241c87ad80
Tools • Dart 2.13.4

### Problem
when i run flutter pub get

Cannot find a Git executable.
Please ensure Git is correctly installed.
Running "flutter pub get" in testf...
pub get failed (1; Please ensure Git is correctly installed.)

run flutter pub get -v
[  +53 ms] SLVR: fact: testf is 1.0.0+1
[  +18 ms] SLVR: derived: testf
[  +54 ms] SLVR: fact: testf depends on flutter any from sdk
[   +7 ms] SLVR: fact: testf depends on kittens from git
[   +2 ms] SLVR: fact: testf depends on cupertino_icons ^1.0.2
[   +2 ms] SLVR: fact: testf depends on flutter_test any from sdk
[   +2 ms] SLVR:   selecting testf
[   +2 ms] SLVR:   derived: flutter_test any from sdk
[   +7 ms] SLVR:   derived: cupertino_icons ^1.0.2
[   +2 ms] SLVR:   derived: kittens from git
[   +2 ms] SLVR:   derived: flutter any from sdk
[  +34 ms] IO  : Spawning "cmd /c git --version" in D:\WokSpance\ht-rn\testf\.
[ +120 ms] IO  : Finished git. Exit code 0.
[   +7 ms]     | stdout:
[   +2 ms]     | | Active code page: 65001
[   +2 ms]     | | git version 2.33.0.windows.2
[   +2 ms]     | Nothing output on stderr.
[   +2 ms] IO  : Spawning "cmd /c git.cmd --version" in D:\WokSpance\ht-rn\testf\.
[  +40 ms] IO  : Finished git.cmd. Exit code 1.
[   +4 ms]     | stdout:
[   +2 ms]     | | Active code page: 65001
[   +1 ms]     | stderr:
[   +3 ms]     | | 'git.cmd' is not recognized as an internal or external command,
[   +3 ms]     | | operable program or batch file.
[   +1 ms] SLVR: Version solving took 0:00:00.337971 seconds.
[   +1 ms]     | Tried 1 solutions.
[   +2 ms] FINE: Resolving dependencies finished (0.389s).
[  +10 ms] ERR : Cannot find a Git executable.
[   +1 ms]     | Please ensure Git is correctly installed.

when i remove git depandent is ok  i dont konw why

**Comment by stuartmorgan** [comment]
This error is coming from `pub`, so you'll need to file this at https://github.com/dart-lang/pub/issues.

(I would suggest checking first though that you can reproduce it with a version that's not a year and a half old.)
