### ISSUE TITLE
Sqflite docs review

### ISSUE THREAD

**Issue by umberto-fontanazza** [flutter/flutter#115019]
Was reading the cookbook and the [docs](https://docs.flutter.dev/cookbook/persistence/sqlite#3-open-the-database) for sqflite and I'm pretty sure an `await` is missing in the code snippet.

Line 5 of the code snippet is `final database = openDatabase(` and I think it should be `final database = await openDatabase(`

**Comment by Sparko-Sol** [comment]
@umberto-fontanazza If you take a look at the code here [Code](https://docs.flutter.dev/cookbook/persistence/sqlite#5-insert-a-dog-into-the-database), they are awaiting the database instance later. 

```
// Define a function that inserts dogs into the database
Future<void> insertDog(Dog dog) async {
  // Get a reference to the database.
  final db = await database;

  // Insert the Dog into the correct table. You might also specify the
  // `conflictAlgorithm` to use in case the same dog is inserted twice.
  //
  // In this case, replace any previous data.
  await db.insert(
    'dogs',
    dog.toMap(),
    conflictAlgorithm: ConflictAlgorithm.replace,
  );
}
```

**Comment by danagbemava-nc** [comment]
Hi @umberto-fontanazza, as pointed out above, that is another way to use the future in dart. 

As such, I'll be closing this as there is nothing wrong with the code sample. 

Thank you
