### ISSUE TITLE
gradle build broken upgrading from Flutter SDK 2.8.1 -> 3.3

### ISSUE THREAD

**Issue by MapperMalte** [flutter/flutter#115007]
Actually I love flutter.

But you keep introducing breaking changes at a rate that annoys everyone to death. Great, now everything has stopped working after upgrading Flutter. Not a single thing works anymore.

I was there when you added Null Safety.

It was a pain in the ass for everyone. 

WHAT THE FUCK IS WITH YOU?

THERE ARE PEOPLE THAT NEED TO WORK WITH YOUR STUFF!

STOP FUCKING THEM OVER!

**Comment by MapperMalte** [comment]
<img width="1248" alt="Bildschirmfoto 2022-11-09 um 19 17 57" src="https://user-images.githubusercontent.com/46358193/200909555-59d33812-5641-4b9b-8147-e7f911f6ea8b.png">

See, it wont even allow me to run main anymore.

I upgraded to 3.3 and then downgraded to 2.8.1 after 3.3 fucked EVERYTHING.

And now everything is completely 100% broken.

**Comment by loic-sharma** [comment]
@MapperMalte please take a look at the code of conduct: https://github.com/flutter/flutter/blob/master/CODE_OF_CONDUCT.md

> The Flutter project expects Flutter's contributors to act professionally and respectfully. Flutter contributors are expected to maintain the safety and dignity of Flutter's social environments (such as GitHub and Discord).
>
> Specifically:
>
> * Respect people, their identities, their culture, and their work.
> * Be kind. Be courteous. Be welcoming.
> * Listen. Consider and acknowledge people's points before responding.

While I understand that unexpected breaking changes are frustrating, please keep your messages respectful, kind, and courteous.

**Comment by Hixie** [comment]
@MapperMalte You have been banned for 30 days. Please reconsider how you interact with our community before returning. Thank you.
