### ISSUE TITLE
8 idle bots but test not running

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#115017]
This test isn't being run, but it looks like there are many idle bots.

https://ci.chromium.org/p/flutter/builders/prod/Mac_ios%20new_gallery_impeller_ios__transition_perf

<img width="955" alt="Screenshot 2022-11-09 at 12 20 29 PM" src="https://user-images.githubusercontent.com/6343103/200933724-9ba46c3f-841f-4539-b8a7-6ceb5fd4ede6.png">

**Comment by dnfield** [comment]
This can happen when the bots don't have the right caches to run the tests.

**Comment by ricardoamador** [comment]
These bots have run tests since this issue was created.

**Comment by ricardoamador** [comment]
Closing as not an issue.
