### ISSUE TITLE
mac clang-tidy run took 2x average

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#115028]
One execution of mac clang-tidy took 2x the average time.

**Example:** https://ci.chromium.org/p/flutter/builders/try/Mac%20Host%20clang-tidy/1859
**Observed execution time:** 1 hour 15 mins
**Expected execution time:** ~31 min

<img width="912" alt="Screen Shot 2022-11-09 at 2 57 48 PM" src="https://user-images.githubusercontent.com/30870216/200960102-20d4e1ac-3fca-4896-a05c-67418e5b62d9.png">

**Comment by ricardoamador** [comment]
It appears that this test occasionally takes that long. There is another run of 1 hr 20 minutes in the screenshot.

**Comment by gaaclarke** [comment]
Having just worked on that code, there should be nothing that would cause the time to fluctuate so wildly.  It's more likely something is weird with that bot, some other background process occupying io or cpu resources.

**Comment by ricardoamador** [comment]
Looking at the historical runs which have taken place on many different bots the time for that test has exceeded the hour mark 13 times intermittently and has run across at least 4 different bots.

**Comment by ricardoamador** [comment]
I'll take a look in a bit.

**Comment by christopherfujino** [comment]
So in https://ci.chromium.org/p/flutter/builders/try/Mac%20Host%20clang-tidy/1859, I see `fseventsd` is running (with 0% CPU) both before and after the task. It's possible it's journaling during the lint.

@yusuf-goog do you remember what you did to try to disable fseventsd? Was it like writing a magic file somewhere on disk?

**Comment by jmagman** [comment]
Just a guess, but I bet this is some OS service grinding at the same time.  In the last process output I see more mds (Spotlight) processes working

https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8797938221161992257/+/u/OS_info__2_/stdout

PID    COMMAND          %CPU
556    mds_stores       46.9
110    mds              17.9
44947  mdworker_shared  16.8

etc.

Can we turn off Spotlight indexing on all our bots with `mdutil`?

**Comment by christopherfujino** [comment]
> Just a guess, but I bet this is some OS service grinding at the same time. In the last process output I see more md (Spotlight) processes working
> 
> https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8797938221161992257/+/u/OS_info__2_/stdout
> 
> PID COMMAND %CPU 556 mds_stores 46.9 110 mds 17.9 44947 mdworker_shared 16.8
> 
> etc.
> 
> Can we turn off Spotlight indexing on all our bots with `mdutil`?

Ahh yeah, I forgot to scroll down, nice catch

**Comment by ricardoamador** [comment]
thank you @jmagman !

**Comment by ricardoamador** [comment]
Created a bug for the Chromium team: https://bugs.chromium.org/p/chromium/issues/detail?id=1383317

**Comment by ricardoamador** [comment]
Chromium team has reportedly resolved this issue. I will keep this open for a couple of days or see in case we see the issue happen again.
