### ISSUE TITLE
[webview_flutter] use runJavascript()  run a javascript methods , this methods was repeatedly called in Android platform

### ISSUE THREAD

**Issue by 826327700** [flutter/flutter#115082]
## Steps to Reproduce

When I use **webviewController.runJavascript**  run a javascript methods , this methods was repeatedly called in Android platform.

**Expected results:** javascript methods called only one time .

**Actual results:** javascript methods called three times .

flutter version : 3.3.2
webview_flutter version: 3.0.4  

<details>
<summary>Code sample</summary>

```dart
body:WebView(
		initialUrl: "http://192.168.3.89:8080/#/",
		javascriptMode: JavascriptMode.unrestricted,
		backgroundColor:Colors.transparent,
		onWebViewCreated: (webController) {
			webviewController=webController;
		},
		onPageFinished: (url){
			webviewController.runJavascript("test()");
		},
	),
```
```js
window.test=()=>{
     console.log(Date.now())
}
```

</details>

## Screenshot
![image](https://user-images.githubusercontent.com/23014381/201122797-cc81a7b2-bc9c-407b-9ab7-5373f121a6bf.png)

**Comment by stuartmorgan** [comment]
You're calling it from `onPageFinished`; how many times is that called? You can have multiple loads for a single URL (e.g., if there are redirects).

**Comment by 826327700** [comment]
> 你是从`onPageFinished`; 这叫了多少次？您可以对单个 URL 进行多次加载（例如，如果有重定向）。

This is really the reason，thanks!
