### ISSUE TITLE
Allow directly sharing iOS and macOS plugin native code

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#115085]
See previous discussion in https://github.com/flutter/flutter/issues/52285. At that time the decision was to use symlinks, but that's kind of a pain due to https://github.com/dart-lang/pub/issues/3143, which means all files have to be symlinked, rather than the directories (which wasn't true when the decision was made initially). For non-trivial plugins that can be a lot of files (e.g., `in_app_purchase`).

I'd need to look at the logic again, but I think it would be plausible to have a pubspec.yaml entry in the platform section that would allow opting into a shared directory instead of the currently hard-code `ios` or `macos`. If it's not too much complexity, I think the maintenance benefits for plugins would be worth the effort.

See also https://github.com/flutter/flutter/issues/114179

(/cc @jmagman for thoughts)

**Comment by jmagman** [comment]
At least on the tool side I don't _think_ it would be too difficult.

Would need to handle all the `IOSPlugin` and `MacOSPlugin` usage and make a... `DarwinPlugin`?
https://github.com/flutter/flutter/blob/b31b9dc05f998eefeb3636564e416417329004e0/packages/flutter_tools/lib/src/flutter_plugins.dart#L1209-L1215

`flutter-plugins-dependencies` would have to create a new `darwin` key, for the projects to handle:
https://github.com/flutter/flutter/blob/378387b139386a0c1e089c85a8e0bcd769dcfe47/packages/flutter_tools/lib/src/xcode_project.dart#L105
https://github.com/flutter/flutter/blob/378387b139386a0c1e089c85a8e0bcd769dcfe47/packages/flutter_tools/lib/src/xcode_project.dart#L553

And then the podhelper needs to know about the new key when parsing `flutter-plugins-dependencies`:
https://github.com/flutter/flutter/blob/3c9288c6d3db7114a341cbb6ed10a45bdf7aea3c/packages/flutter_tools/bin/podhelper.rb#L292

I'm sure I'm forgetting some places.

**Comment by hellohuanlin** [comment]
this can be part of effort of swift migration for path_provider/shared_preferences/url_launcher plugins, as [discussed in the swift migration doc](https://docs.google.com/document/d/1XsaulkJA6_ZSpM7chkQLhQY25sQqhEMiqHMYzw8H85o/edit?resourcekey=0-_cUjF1c0iBvRLKfV-3gK5A&disco=AAAAcY_U4EE)

**Comment by jmagman** [comment]
The pubspec would also need to support a `darwin` field, and `pub` would need to be taught that it means iOS and macOS are supported.

**Comment by stuartmorgan** [comment]
> The pubspec would also need to support a `darwin` field, and `pub` would need to be taught that it means iOS and macOS are supported.

I was thinking that rather than a new platform field, it would be a new subfield. Something like:
```
flutter:
  plugin:
    iOS:
      pluginClass: Foo
      sharedDarwinSource: true
    macOS:
      pluginClass: Foo
      sharedDarwinSource: true
```

That way we aren't conflating conceptual platforms with the directories.

**Comment by jmagman** [comment]
Adding just that key is easier.  Got it working in draft PR https://github.com/flutter/flutter/pull/115337, it needs an end-to-end integration test.

`sharedDarwinSource` concept maybe needs a design doc?  Or maybe this issue and that PR are sufficient to get sign off from stakeholders (you me and... @cbracken?).  

Also requires documentation updates:
https://docs.flutter.dev/development/packages-and-plugins/developing-packages#step-2c-add-ios-platform-code-swifthm
https://docs.flutter.dev/development/packages-and-plugins/developing-packages#step-2e-add-macos-platform-code-swift

**Comment by cbracken** [comment]
Agreed this seems like a pretty sensible approach for code that's common across both platforms (i.e. not UIKit or AppKit specific).

You could imagine cases where there's some shared Darwin code but also some AppKit or UIKit code; in such a case we'd want to support shared Darwin code in `darwin` and the specific bits under a `macos`/`ios` directory.

**Comment by stuartmorgan** [comment]
> in such a case we'd want to support shared Darwin code in `darwin` and the specific bits under a `macos`/`ios` directory

Pods don't allow references outside of the pod root, so that gets to be problematic. My thought was that if enough is common that you're using using `sharedDarwinSource`, you just put your macOS- and iOS-specific bits in the `darwin` directory, separated out however you want (subdirs, file naming convention, etc.)
