### ISSUE TITLE
[CP] 35961: Process docs as stable on release candidate branches.

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#115097]
### issue_link

https://github.com/flutter/flutter/issues/114900

### Commit Hash

745cefff908d46f93a8c8fca84c720d8d46a7295

### Target

stable

### pr_link

https://flutter-review.git.corp.google.com/c/recipes/+/35960

### Impacted Users

all api documentation users

### Impact Description

The flutter api docs are not being indexed by search engines.

### Workaround

None

### Risk

low

### Test Coverage

yes

### Validation Steps

This has been tested manually.

**Comment by itsjustkevin** [comment]
@CaseyHillers
