### ISSUE TITLE
Android flavors_test is failing, `"app-paid-release.apk" does not exist`

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#115121]
Started on https://github.com/flutter/flutter/pull/114048
```
[flavors_test] [STDOUT] stderr: "build\app\outputs\flutter-apk\app-paid-release.apk" does not exist
```
https://ci.chromium.org/p/flutter/builders/staging/Windows_android%20flavors_test_win/1677
https://ci.chromium.org/p/flutter/builders/staging/Linux_android%20flavors_test/1

cc @a-wallen

**Comment by jmagman** [comment]
Looks like this should have been marked unflaky in August, that would have caught it: https://github.com/flutter/flutter/issues/107681#issuecomment-1208556298

**Comment by christopherfujino** [comment]
So if I'm reading this right, we have valid tests that are marked flaky and thus not blocking the tree that were never updated to accomodate test file changes? Should we just fix forward then, rather than revert (since it seems like this isn't a problem with the prod code, just the test code)?

**Comment by jmagman** [comment]
`Linux_android flavors_test` was marked flaky in https://github.com/flutter/flutter/pull/114048 since that PR changed the test.  Needed to actually follow up that it's passing in prod though...

Looks like the test should be installing the debug version, since that's what was just built, not the release version.
