### ISSUE TITLE
PictureRecorder Image Rendering Does Not Render on Chrome when Web App is Built and Deployed on Raspberry Pi aarch64

### ISSUE THREAD

**Issue by ponderMuse** [flutter/flutter#115153]
## Steps to Reproduce

Build and run below `main.dart` code on Raspberry Pi 4 (Issue only occurs when app is built and run on Raspberry Pi - prob any aarch64 would suffice to reproduce?).

1. On Raspberry Pi 4 build app using:
```
flutter channel stable
flutter upgrade
flutter config --enable-web
flutter build web --web-renderer canvaskit --release
```
2. Serve up build/web on a web server (e.g. a simple arm64v8 python http server).
3. Visit 'http://{server-ip}:{server-port}/' on a Firefox web browser and you should see a composite render of two images from `Tile_set.png` and a green circle.
4. Visit 'http://{server-ip}:{server-port}/' on a Chrome web browser and you will only see a green circle. `Tile_set.png` images are not rendered.

**Expected results:**
Visit 'http://{server-ip}:{server-port}/' on any web browser and you should see a composite render of two images from `Tile_set.png` and a green circle.

**Actual results:** 
When you visit 'http://{server-ip}:{server-port}/' on a Firefox web browser you see a composite render of the two images from `Tile_set.png` and a green circle as expected.

When you visit 'http://{server-ip}:{server-port}/' on a Chrome web browser you only see a green circle. `Tile_set.png` images are NOT rendered.

**Notes:**
In my setup the built webapp is actually run in a k8s pod in a k8s cluster running on the Raspberry Pi(s) using Docker image: `arm64v8/python:3.8.5-alpine`.

If the app is run on my dev desktop (x86_64 architecture) then the images composite renders as expected in the same two Firefox and Chrome web browsers so I believe the issue is specific to when the .js is built by Flutter on aarch64 maybe?

main.dart:

```
import 'dart:async';
import 'dart:typed_data';
import 'dart:ui' as ui;
import 'package:flutter/material.dart';
import 'package:url_strategy/url_strategy.dart';
import 'package:http/http.dart' as http;

void main() async {
  await runZonedGuarded(() async {
    WidgetsFlutterBinding.ensureInitialized();
    setPathUrlStrategy();
    runApp(const MainApp());
  }, (Object error, StackTrace stack) {
    print('error:$error stack:$stack');
  });
}

class MainApp extends StatelessWidget {
  const MainApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      debugShowCheckedModeBanner: false,
      color: Color(0xFF000000), home: TestWidget(),
    );
  }
}

class TestWidget extends StatefulWidget {
  const TestWidget({super.key});

  @override
  State<TestWidget> createState() => _TestWidgetState();
}

class _TestWidgetState extends State<TestWidget> {
  ui.Image? _image;

  @override
  void initState() {
    super.initState();
    _getImage();
  }

  @override
  Widget build(BuildContext context) {
    return _image != null
        ? CustomPaint(
      painter: TestPainter(_image!), size: const Size(60.0,60.0),
      child: SizedBox(//color: Colors.white,
          width: _image!.width.toDouble(),
          height: _image!.height.toDouble()),
    )
        : Container(width: 50, height: 50, color: Colors.red);
  }

  _getImage() async {

    http.Response response = await http.get(
      Uri.parse('https://upload.wikimedia.org/wikipedia/commons/7/77/Tile_set.png'),
    );
    Uint8List bytes = response.bodyBytes;
    ui.Image image = await decodeImageFromList(bytes);

    ui.PictureRecorder recorder = ui.PictureRecorder();
    Canvas canvas = Canvas(recorder);
    final Paint spritePaint = Paint()..color = Colors.green;

    var src0 = const Rect.fromLTWH(0, 16, 16, 16);
    var dst0 = const Rect.fromLTWH(0, 0, 16, 16);
    var src1 = const Rect.fromLTWH(0, 32, 16, 16);
    var dst1 = const Rect.fromLTWH(0, 16, 16, 16);
    canvas.drawImageRect(image, src0, dst0, spritePaint);
    canvas.drawImageRect(image, src1, dst1, spritePaint);
    ui.Picture picture = recorder.endRecording();
    _image = await picture.toImage(32, 32);

    print('_getImage() _image:$_image');
    setState(() {});
  }
}

class TestPainter extends CustomPainter {
  final ui.Image image;

  TestPainter(this.image);

  @override
  void paint(Canvas canvas, Size size) {
    final Paint spritePaint = Paint()..color = Colors.green;
    canvas.drawImage(image, Offset.zero, spritePaint);
    canvas.drawCircle(const Offset(30, 30), 10, spritePaint);
  }

  @override
  bool shouldRepaint(CustomPainter oldDelegate) {
    return true;
  }
}
```
`# flutter doctor`:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.8, on Ubuntu 20.04.5 LTS 5.4.0-1073-raspi, locale C.UTF-8)
[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Linux toolchain - develop for Linux desktop
[!] Flutter IDE Support (No supported IDEs installed)
[✓] Connected device (1 available)
[✓] HTTP Host Availability
```

Firefox Render: ![firefox-render](https://user-images.githubusercontent.com/24505954/201382135-f54fc390-f604-4e79-9646-fe13deec4f05.png)
Chrome Render: ![chrome-render](https://user-images.githubusercontent.com/24505954/201382141-b63f0856-f26e-49e8-b07a-bc3fcd422580.png)

**Comment by ponderMuse** [comment]
I think the issue I am seeing is similar to [#103803](https://github.com/flutter/flutter/issues/103803)?

I have now done a build and deploy on the Raspberry Pi device using `flutter master` (Channel master, 3.6.0-1.0.pre.37, on Ubuntu 20.04.5 LTS 5.4.0-1073-raspi, locale C.UTF-8) based on comments there and can confirm that with Flutter 3.6.x version the `PictureRecorder` `Image` renders as expected in both Firefox and Chrome.

So will carry on doing builds on the Raspberry Pis with channel master until the fix becomes available in stable.

**Comment by darshankawar** [comment]
@ponderMuse Thanks for verifying and confirming that it works on latest master. Based on above comment and per triage policy, I am going ahead and closing this as fixed. You may keep an eye on stable release notes to check if it contains the fix.
