### ISSUE TITLE
Default .gitignore for the counter app should include platform specific generated files. 

### ISSUE THREAD

**Issue by polina-c** [flutter/flutter#115106]
For example: **/macos/**/ephemeral/**

**Comment by danagbemava-nc** [comment]
Hi @polina-c, the various platform folders contain their own .gitignore files which include the generated files. 
Do they not suffice? Or is there a specific issue that you're running into?

**Comment by polina-c** [comment]
Thanks. It seems it did not work, but now I cannot repro it. Will watch.
