### ISSUE TITLE
Running flutter build web just broke with error a few hours ago

### ISSUE THREAD

**Issue by jthornjd** [flutter/flutter#115179]
Getting this error on our build server. Not sure why it's popping up. It's points to a file that is not ours. 
Target dart2js failed: Exception: Warning: The 'dart2js' entrypoint script is deprecated, please use 'dart compile js' instead.
/C:/Users/User/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/archive-3.3.3/lib/src/util/aes_decrypt.dart:1:8:
Error: Not found: 'dart:ffi'
import 'dart:ffi';
       ^
Error: Compilation failed.

**Comment by asadbekdev** [comment]
Remove import 'dart:ffi';

**Comment by stuartmorgan** [comment]
This error is coming from the `archive` package, so you'll need to report the issue to its developers.

Closing as this is not a Flutter bug.

**Comment by monster555** [comment]
It seems there's some package importing `archive: ^3.3.3`
A workaround would be to override it with the newer version, so to do this just add 
```
dependency_overrides:
  archive: ^3.3.4
```
to your `pubspec.yaml` file

**Comment by stuartmorgan** [comment]
`^3.3.3` is a range that allows any `3.x` version, so you don't need to override anything in that case. You can just run `flutter pub upgrade` to update transitive dependencies (which is something that should be fine regularly regardless).

**Comment by monster555** [comment]
That's right. In my case running `flutter pub get` did nothing (even after `flutter clean`). Just deleted my `pubspec.lock` file, then a `flutter pub get` and everything is up and running (with no `dependency_overrides`)

**Comment by jthornjd** [comment]
yep thanks for the archive breadcrumb...led me to some out of sync packages across a submodule we have

**Comment by markhorrocks** [comment]
Running flutter pub upgrade --major-versions fixed this for me.
