### ISSUE TITLE
local_auth enter password feature

### ISSUE THREAD

**Issue by tologonkudaiberdiuulu** [flutter/flutter#115148]
I am trying to implement face id feature with local_auth(version: 2.1.2) package. Yes, it's working fine. But after two tries, face recognition dialog showing enter password button like below

![telegram-cloud-photo-size-2-5438654393743425871-y](https://user-images.githubusercontent.com/47391827/201343117-0cb4376c-a303-4a96-9bb1-19bc73ebbe43.jpg)

After clicking enter password it's just throwing platform exception like in logs section. How I can make enter password feature work. Or is there way to remove this button? If can't make enter password to work, then I just want to remove this button.

<details>
<summary>Code sample</summary>

``` 
final bool authenticated = await auth.authenticate(
        localizedReason: 'Scan your fingerprint (or face or whatever) to authenticate',
        options: const AuthenticationOptions(
          useErrorDialogs: false,
          stickyAuth: true,
          biometricOnly: true,
        ),
      );
```

</details>

<details>
  <summary>Logs</summary>

<img width="539" alt="image" src="https://user-images.githubusercontent.com/47391827/201342476-922c1d1c-afe8-4b7f-9ab8-9a8705ea3c69.png">

```
```

```
```

</details>

**Comment by darshankawar** [comment]
Thanks for the report @tologonkudaiberdiuulu 
Can you provide complete error log in properly formatted text including `flutter doctor -v` and plugin version ?

**Comment by tologonkudaiberdiuulu** [comment]
[✓] Flutter (Channel stable, 3.3.8, on macOS 13.0 22A380 darwin-x64, locale en-US)
    • Flutter version 3.3.8 on channel stable at /Users/**/tools/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 52b3dc25f6 (13 days ago), 2022-11-09 12:09:26 +0800
    • Engine revision 857bd6b74c
    • Dart version 2.18.4
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc1)
    • Android SDK at /Users/**/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.73.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.52.0

[✓] Connected device (2 available)
    • macOS (desktop)           • macos                     • darwin-x64     • macOS 13.0 22A380 darwin-x64
    • Chrome (web)              • chrome                    • web-javascript • Google Chrome 107.0.5304.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

**Comment by tologonkudaiberdiuulu** [comment]
@darshankawar complete error log provided in log section in my question. And there also provided plugin version(2.1.2)

**Comment by darshankawar** [comment]
@tologonkudaiberdiuulu 
Is this on iOS correct ? The fallback on passcode was added as part of this https://github.com/flutter/flutter/issues/96390 which seems to be working fine, but if we try to enter password, it is throwing an error. Can you take a look at the PR that added the above fix and see if it helps in your case.
