### ISSUE TITLE
Why not implement a native selector for material Icons?

### ISSUE THREAD

**Issue by RenatoExpert** [flutter/flutter#115136]
## Use case
I am developing an [app](https://github.com/renatoexpert/shuei-client) that receives icon names from a server. I'd like to be totally free to use any string name, and my app will render it from materials.
I figured out flutter lacks on a dinamic selector for icons. We could implement something as we do in web javascript `document.getElementById(myString);` with few enfort.
### Eval()
```
mystring = 'abc';
myIcon = Icon(
    eval("Icons.${mystring}")
);
```
First, I tried with `eval()`. I know its not recommended. It was just for testing the concept.
After a brief search, I read that Dart do not support it.
### dart:isolate
I found an interesting [article](https://iiro.dev/how-to-eval-in-dart/) on how to do something similar to eval in Dart. But it uses a bit more complexity, maybe its like killing a cockroach with a bazooka.
Also, I am not sure if it works with flutter.
### Using a Map
There is a package on pub.dev called [string_2_icon](https://pub.dev/packages/string_2_icon).
It just gets a string key from a Map<String, iconData>.
Usage:
```
Icon(String2Icon.getIconDataFromString('account_key'), size: 48, color: Colors.blue,)
```
What it does on real:
```
Map<String, IconData> iconDataMap = {
  'abTesting': MdiIcons.abTesting,
  'abacus': MdiIcons.abacus,
  'abjadArabic': MdiIcons.abjadArabic,
  ...
  etc

class String2Icon {
  /// Method to tranform a text to icon dat
  static IconData? getIconDataFromString(String iconName) {
    String iconNameTransformed = _camelize(iconName.replaceAll('mdi', ''));
    return iconDataMap[iconNameTransformed];
  }
}
```
It works, its simple to use, but I still think its not a much smart way to do so, and also we could do it using native resources.
### dart:mirrors
Do not work with flutter :cry: 
## Proposal
Why not having a Map<String, iconData> on native flutter?
Example usage:
```
final myString = 'abc';
final myIcon = Icon(Icons[myString]);
```
Or a selector, like:
```
final myString = 'abc';
final myIcon = Icons.selector(myString);
```

**Comment by jonahwilliams** [comment]
That would remove our ability to tree shake Icons

The Icon font itself is many megabytes, and we rely on detecting the usage of Icon constants to shrink it down to a subset of icons that are appropriate for a given app. Adding any sort of String -> Icon runtime lookup would prevent us from doing this safely.
