### ISSUE TITLE
FutureBuilder is broken with `SynchronousFuture`s.

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#115171]
Will add repro momentarily, cause of rollback in https://github.com/flutter/flutter/pull/115156

**Comment by dnfield** [comment]
This test should pass

```dart
      final SynchronousFuture<String> future = SynchronousFuture<String>('flutter');
      await tester.pumpWidget(FutureBuilder<String>(
        future: future,
        builder: (BuildContext context, AsyncSnapshot<String> snapshot) {
          expect(snapshot.connectionState, ConnectionState.done);
          expect(snapshot.data, 'flutter');
          expect(snapshot.error, null);
          expect(snapshot.stackTrace, null);
          return const Placeholder();
        },
      ));
```

But does not today.

**Comment by amoffatgmi** [comment]
Is there a suggested workaround until this lands in stable?

**Comment by amoffatgmi** [comment]
It appears the following can be a poor-person's `SynchronousFuture` and appears to work correctly with `FutureBuilder` 

```dart
final fut = Future.delayed(const Duration(seconds: 0), (() => value));
```

😭

**Comment by dnfield** [comment]
@amoffatgmi that will actually turn the event loop whereas `SynchronousFuture` does not necessarily.

Unfortunately, before the patch that fixed this, you would potentially get a snapshot that said it was waiting but did actually have data. 

IMHO, the linked patch is pretty safe and you could just manually cherry pick it into your local checkout without issue. It's unlikely that we'll cherry pick it before our next stable though, unless there's evidence that this is impacting a large number of customers.
