### ISSUE TITLE
[image_picker] package stops showing permissions dialog

### ISSUE THREAD

**Issue by qbait** [flutter/flutter#115120]
When I run the default image_picker sample app, on permissions dialog is shown only once, after denying permissions, it stops showing it.
Is there a way to force image_picker to always show permissions dialog?

<img width="330" alt="Screenshot 2022-11-10 at 19 18 59" src="https://user-images.githubusercontent.com/2264901/201217638-dc3b3510-c0f8-4f48-9cee-ba976b8ca859.png">

**Comment by huycozy** [comment]
Hi @qbait 
As explained [here](https://github.com/flutter/flutter/issues/48779#issuecomment-573997233), it seems your question is best suited for support channels like StackOverflow, so please ask the same there for solutions if any. This StackOverflow answer may be helpful for this case: https://stackoverflow.com/questions/72327986/platformexceptionphoto-access-denied-the-user-did-not-allow-photo-access-nul.

You may also get some help if you post it on flutter's [community](https://flutter.dev/community) or [flutterhelp](https://www.reddit.com/r/flutterhelp/) as resources. 

Closing as this is neither a Flutter bug nor a feature request.
