### ISSUE TITLE
Error with Textfield when try input

### ISSUE THREAD

**Issue by salahaldinalhajduzce** [flutter/flutter#115108]
**When iam try to input text to textfield application return to last page on android emulator device but on ios emulator is working normally**

https://user-images.githubusercontent.com/101683175/201195452-47b6825b-f60b-4264-8a9f-908983061a06.mp4

**Comment by danagbemava-nc** [comment]
Hi @salahaldinalhajduzce,

Can you please provide your `flutter doctor -v` and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?

Thank you
