### ISSUE TITLE
Investigate `Linux ci_yaml flutter roller` failures 

### ISSUE THREAD

**Issue by Renzo-Olivares** [flutter/flutter#115110]
We are running into failures with `Linux ci_yaml flutter roller`, the tree is currently red.

Failed run: https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20ci_yaml%20flutter%20roller/6063/overview
Re-run: https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20ci_yaml%20flutter%20roller/6065/overview

I am seeing.

```
gerrit: failed to post to "https://flutter-review.googlesource.com/a/changes/infra~main~I6cb195334116b0b8ddc0e5dec789984d30733cc9/revisions/current/review" with &{map[]   map[]   [{flutter-infra@grotations.appspotmail.com CC false }] false false}, status code 400
```

**Comment by keyonghan** [comment]
@CaseyHillers Could you help take a look? Do you know why the set-reviewer not working?

Compared to last pass build, there is a fuchsia config roll which doesn't seem related.

**Comment by CaseyHillers** [comment]
I sent a revert in https://github.com/flutter/cocoon/pull/2296

I'll send the recipes fix now.

**Comment by CaseyHillers** [comment]
Infra fix is in https://flutter-review.git.corp.google.com/c/infra/+/35985 (add OWNERS permissions to the bots)

**Comment by keyonghan** [comment]
A rerun was triggered and we should be green soon.

**Comment by CaseyHillers** [comment]
https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20ci_yaml%20flutter%20roller/6070/overview is green
