### ISSUE TITLE
Investigate failures on `Linux firebase_release_smoke_test`

### ISSUE THREAD

**Issue by Renzo-Olivares** [flutter/flutter#115170]
The tree is currently red on `Linux firebase_release_smoke_test`

Failed run:
https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20firebase_release_smoke_test/9921/overview
https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20firebase_release_smoke_test/9919/overview

Failed re-run: 
https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20firebase_release_smoke_test/9923/overview
https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20firebase_release_smoke_test/9922/overview

we are seeing

```
11:48:48 Test matrix status: Error:1 Finished:7             
Robo testing complete.

│   OUTCOME    │      TEST_AXIS_VALUE       │      TEST_DETAILS      │
├──────────────┼────────────────────────────┼────────────────────────┤
│ Passed       │ Nexus5-21-en-portrait      │ --                     │
│ Passed       │ Nexus5-22-en-portrait      │ --                     │
│ Passed       │ Nexus5-23-en-portrait      │ --                     │
│ Passed       │ Nexus6P-25-en-portrait     │ --                     │
│ Passed       │ Nexus6P-26-en-portrait     │ --                     │
│ Passed       │ Nexus6P-27-en-portrait     │ --                     │
│ Passed       │ NexusLowRes-29-en-portrait │ --                     │
│ Inconclusive │ Nexus5-19-en-portrait      │ Infrastructure failure │
```

**Comment by christopherfujino** [comment]
Started a firebase test lab support thread on their slack.

**Comment by christopherfujino** [comment]
no update on slack thread, so i opened a PR to mark the test flaky

**Comment by yusuf-goog** [comment]
@christopherfujino assigning you, let me know if you need anything from us at this time, or if your waiting on a response from firebase.

**Comment by christopherfujino** [comment]
This outage was fixed Friday evening and the test has been green since then. Marking the test non-bringup in https://github.com/flutter/flutter/pull/115402
