### ISSUE TITLE
Make Chip's background colour configurable

### ISSUE THREAD

**Issue by kostaa** [flutter/flutter#11517]
Hopefully it is not the case that "you can have any colour as long as it's gray" ...

**Comment by Hixie** [comment]
I have excellent news for you: in https://github.com/flutter/flutter/pull/11498, @paolosoares contributed a patch to solve this very issue!

**Comment by Hixie** [comment]
It is done! Enjoy!

**Comment by kostaa** [comment]
What a service! Many thanks.
