### ISSUE TITLE
Can not run camera in android 13 ?

### ISSUE THREAD

**Issue by nguyenleanhkhoa** [flutter/flutter#115198]
Android 13 can not get previousSize when open camera  , so previousSize is null --> bug

**Comment by danagbemava-nc** [comment]
Hi @nguyenleanhkhoa,

Can you please provide your `flutter doctor -v` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?

Please also provide the version of `camera` and `camera_android` you're using. 

In the future, when filing an issue, kindly provide all or some of the information requested in the issue template.

Thank you

**Comment by Lamorak** [comment]
Seems like it's the same issue as [#114029](https://github.com/flutter/flutter/issues/114029)
