### ISSUE TITLE
FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by ImNyK** [flutter/flutter#115152]
hey guys, i got this error after adding intl: and google_fonts: in my pubsec.yaml folder when i try to run it

FAILURE: Build failed with an exception.

* Where:
Script 'D:\Software\Flutter\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1159

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'D:\Software\Flutter\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 20s
Running Gradle task 'assembleDebug'...                             21.7s
Exception: Gradle task assembleDebug failed with exit code 1

i tried flutter clean, pub get, pub upgrade and this problem still occur. any help would mean so much to me. thanks!

**Comment by osamaaleem** [comment]
Try deleting the pubspec.lock file and the run 'flutter pub get' again.

**Comment by ImNyK** [comment]
> 
thanks, i will try it

**Comment by ImNyK** [comment]
> Try deleting the pubspec.lock file and the run 'flutter pub get' again.

thanks, i definitely will try it

**Comment by ImNyK** [comment]
> Try deleting the pubspec.lock file and the run 'flutter pub get' again.

it still the same sir, nothing changes

**Comment by huycozy** [comment]
Hi @ImNyK 
Does the issue only happen when adding `intl` and `google_fonts `? Does it happen on the Flutter default sample project (counter app)?
Please provide the output of `flutter doctor -v`.

**Comment by Akshaykhapare** [comment]
i have this issue  how to solve it






Launching lib\main.dart on sdk gphone64 x86 64 in debug mode...
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\PROJECT\untitled\android\build.gradle' line: 26

* What went wrong:
A problem occurred evaluating root project 'android'.
> A problem occurred configuring project ':app'.
   > Could not open proj generic class cache for build file 'C:\PROJECT\untitled\android\app\build.gradle' (C:\Users\Akshay\.gradle\caches\7.4\scripts\7bxhs5bn9b9l28yhyduglatl6).
      > BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 63

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
Exception: Gradle task assembleDebug failed with exit code 1
