### ISSUE TITLE
flutter gerrit CLs are not public anymore 

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#115195]
flutter gerrit CL like  https://flutter-review.git.corp.google.com/c/recipes/+/35881 used to be public but they are not accessible anymore.

**Comment by godofredoc** [comment]
\cc @keyonghan maybe impacted by the codereview plugin migration?

**Comment by keyonghan** [comment]
Checking with GOB team if SR enforces internal access.

**Comment by yusuf-goog** [comment]
@keyonghan did you get a response from GoB team?

**Comment by godofredoc** [comment]
@athomas who mentioned there is now a public and internal urls

**Comment by athomas** [comment]
The old URLs still exist but Googlers get redirected to the internal URL, see b/258280858.

**Comment by drewroengoogle** [comment]
Sure! I'll make a bug similar to the one Alexander made for dart.

**Comment by drewroengoogle** [comment]
b/259555990 created

**Comment by godofredoc** [comment]
The urls from the navigation bar use an internal url like: https://flutter-review.git.corp.google.com/c/recipes/+/35961 before posting those urls in bugs we need to replace `git.corp.google.com` with `googlesource.com`. 

E.g. https://flutter-review.git.corp.google.com/c/recipes/+/35961 will become https://flutter-review.googlesource.com/c/recipes/+/35961 which is available publicly.

**Comment by drewroengoogle** [comment]
@godofredoc Is there anything for this bug that needs to be done still?

**Comment by godofredoc** [comment]
Sending an email to remind everyone to change the links before adding them to github bugs,
