### ISSUE TITLE
CI Issues requiring a lab visit

### ISSUE THREAD

**Issue by ricardoamador** [flutter/flutter#115127]
This is a consolidated list of all the bots that currently have issues that require a lab visit.

- flutter-win-3 
  - swarming user password has expired and needs to be updated. However the password in Valentine is not working when attempting to reset the password.

- flutter-win-5
  - Cannot vnc to the machine so the salt config file cannot be edited.

- flutter-win-6
  - This machine has hit the SSD failure. will need to be swapped out. Possible on Monday, since we should still have win capacity?
  - Cannot vnc to the machine.

- flutter-linux-2
  - The device needs to be retired or looked at in the lab. It has been failing intermittently and causing test flakiness.

- flutter-linux-13
  - The credentials for the flutter and swarming user cannot be used to log onto the bot. Not sure what the password has been changed to but the bot is not accessible through ssh.

- flutter-linux-21 and flutter-linux-23
  - Both bots are inaccessible via ssh. Xilai restarted them but they did not come back. They need to be looked at.

**Comment by ricardoamador** [comment]
Related issues that will be closed as duplicates:
https://github.com/flutter/flutter/issues/115101
https://github.com/flutter/flutter/issues/112644
https://github.com/flutter/flutter/issues/114556
https://github.com/flutter/flutter/issues/114941
https://github.com/flutter/flutter/issues/114942

**Comment by yusuf-goog** [comment]
win-3 had expired password. reset, working now.
win-5 fixed salt config, rebooted, working now.
win-6 SSD failure, will require swap out.
linux-2 test flakiness needs to be debugged. currently manually quarantined.
linux-13 potentially has SSD problems (BIOS message). It rebooted correctly. Needs to look at salt auth.
linux-21 SSD failure, needs swapping out.
linux-23 SSD failure, needs swapping out.
linux-25 rebooted, and working now.

**Comment by nehalvpatel** [comment]
I swapped win-6, linux-21, and linux-23 with new units last week. The provisioning is currently blocked on getting their keys approved on the Salt Master server.

**Comment by nehalvpatel** [comment]
linux-21 and linux-23 are back up and running as of Nov 23.

**Comment by yusuf-goog** [comment]
win-6 device needs to be authenticated.

**Comment by ricardoamador** [comment]
Nice work @nehalvpatel!

**Comment by nehalvpatel** [comment]
Is this good to close?

**Comment by ricardoamador** [comment]
As long as any outstanding issues have their own tracking bugs it is fine.

**Comment by nehalvpatel** [comment]
Actually, I just checked the bot list again and it looks like some bots are dead, including some from this issue:
- linux-25
- win-2
- win-3
- win-4
- win-5

**Comment by drewroengoogle** [comment]
@nehalvpatel I talked with Yusuf and I'm going to close this issue and create a new one with the current dead bots to keep things up to date
