### ISSUE TITLE
[in_app_purchase] [google_maps_flutter] [ios] Crash on iOS 15.5 after any buy

### ISSUE THREAD

**Issue by Denilson-source** [flutter/flutter#115265]
After buying any consumable the app will crash every time I start listening to purchase updates.

the exception throw before crash is the following:
"*** -[_NSPlaceholderData initWithContentsOfURL:options:maxLength:error:]: nil URL argument"

The issue seems to come from parsing the receipts as in the image below
<img width="458" alt="Screen Shot 2022-11-14 at 06 56 21" src="https://user-images.githubusercontent.com/58909395/201630549-f869a18b-69ca-4753-bfa9-0e67c59a35bb.png">

## Steps to Reproduce

1. Download the example
2. Add google_maps_flutter package
3. Run the code and buy a consumable

**Comment by huycozy** [comment]
Hi @Denilson-source 
To be more precise, please provide the information indicated below:
- A [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
- The output of `flutter doctor -v`
- Plugin versions of `in_app_purchase` and `google_maps_flutter`
- Reproduction steps, Expected results, Actual results
- A completed crash log in text format. If the log is too long, please save it into a file and attach it here.

Thank you!
