### ISSUE TITLE
[Crash][webview_flutter][android]  bindTextureImage: error binding external image: 0x502

### ISSUE THREAD

**Issue by SalsabeelaHasan** [flutter/flutter#115223]
## Versions
[✓] Flutter (Channel stable, 3.3.7)
[✓] webview_flutter: 3.0.4

## Steps to Reproduce

I use Web View to display a news page that contains all kinds of embeds, such as Tweets, YouTube videos, regular images, etc..
In some of these articles that contain any kind of images or embeds, especially Tweets, a crash happens.
What happens is that a part of the page is rendered, after that it stretches for a split second and the page stops, then boom.. crush!

For example, article like this is causing a crash : https://taqs.me/5iZ7

## Logs when crush happens

```
E/FrameEvents( 5987): updateAcquireFence: Did not find frame.
E/eather.main_ap( 5987): [SurfaceTexture-0-5987-3] bindTextureImage: error binding external image: 0x502
E/flutter ( 5987): [ERROR:flutter/fml/platform/android/jni_util.cc(204)] java.lang.RuntimeException: Error during updateTexImage (see logcat for details)
E/flutter ( 5987): 	at android.graphics.SurfaceTexture.nativeUpdateTexImage(Native Method)
E/flutter ( 5987): 	at android.graphics.SurfaceTexture.updateTexImage(SurfaceTexture.java:249)
E/flutter ( 5987): 	at io.flutter.embedding.engine.renderer.SurfaceTextureWrapper.updateTexImage(SurfaceTextureWrapper.java:55)
E/flutter ( 5987): 
F/flutter ( 5987): [FATAL:flutter/shell/platform/android/platform_view_android_jni_impl.cc(1319)] Check failed: fml::jni::CheckException(env).
```

**Comment by huycozy** [comment]
Hi @SalsabeelaHasan 
Do you embed the WebView in a ScrollView? If so, please check this issue if it's similar: #104889
Otherwise, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this. Thank you!

**Comment by SalsabeelaHasan** [comment]
Hi @huycozy ,
Yes, I followed up on this issue and it was resolved for me, but the weird thing is that this problem still occurs on a certain type and a few articles, and the error here is completely different from the problem of ScrollView.
Although there are articles similar to it as content, this error does not occur.

**Comment by huycozy** [comment]
Hi @SalsabeelaHasan 
>Yes, I followed up on this issue and it was resolved for me

That issue is still open and hasn't been fixed yet. If you are facing the issue will ScrollView, please follow up on it for further updates. 

>the error here is completely different from the problem of ScrollView.

In case the issue doesn't relate to ScrollView, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this. Thank you!
