### ISSUE TITLE
ListWheelScrollView not woking sometime in web

### ISSUE THREAD

**Issue by alinakhaiee** [flutter/flutter#115205]
This problem occurred on the web for me when using CupertinoDatePicker And it seems that the main problem is from the ListWheelScrollView please guide me

https://user-images.githubusercontent.com/77294515/201471446-0bbc659d-4c73-449c-b01e-305f121a273a.mov

Flutter 3.0.5 • channel stable • https://github.com/flutter/flutter.git Framework • revision f1875d570e (4 months ago) • 2022-07-13 11:24:16 -0700 Engine • revision e85ea0e79c Tools • Dart 2.17.6 • DevTools 2.12.2

![Screen Shot 2022-11-12 at 1 34 11 PM](https://user-images.githubusercontent.com/77294515/201471466-06dcbea8-47ea-4887-87d9-a944af49bfaa.png)

I tested all the code in a new project and there is nothing else inside the main page, so it is not a dependency.

**Comment by darshankawar** [comment]
@alinakhaiee 
Can you provide complete reproducible code sample without third party plugins in properly formatted text instead of in screenshots ?
Also, I suggest you to upgrade to latest stable / master and try again to see if you still face the behavior or not.

**Comment by alinakhaiee** [comment]
This problem is solved in the new update 3.3.8
thank you
