### ISSUE TITLE
Image Picker

### ISSUE THREAD

**Issue by rlee1990** [flutter/flutter#115227]
Can we please have the ability to set the useRootNavigator for Image Picker to false so that it does not cause an issue with other routes? I have an issue using this with the latest version of Auto Router and nested routes.

**Comment by darshankawar** [comment]
@rlee1990 

> I have an issue using this with the latest version of Auto Router and nested routes.

Can you elaborate by providing a minimal code sample which shows current issue and expected behavior you are looking for using the plugin ?

**Comment by rlee1990** [comment]
@darshankawar 
So I have an app that uses Auto Router with nested routes. One set of nested routes is home and a subroute of Profile and Profile Edit.
While in profile edit I use the Image Picker package to select an image or use the camera. When doing this it creates an issue with the router and removes the stack. I had the same issue with any dialog prompt. I fixed the dialog prompt issue by setting useRootNavigator to false. I suspect that Image Picker uses the root Navigator.

**Comment by darshankawar** [comment]
@rlee1990 Would be great if you could show us a minimal code sample. That way, it'll be helpful to make this issue actionable.
