### ISSUE TITLE
Starter app could include a button action

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#1152]
What do we think about using this code as the starter app that is generated for a new project? It shows you how to connect a button to state to "do something".

```
import 'package:flutter/material.dart';

void main() {
  runApp(
    new MaterialApp(
      title: "Flutter Demo",
      routes: <String, RouteBuilder>{
        '/': (RouteArguments args) => new FlutterDemo()
      }
    )
  );
}

class FlutterDemo extends StatefulComponent {
  @override
  State createState() => new FlutterDemoState();
}

class FlutterDemoState extends State {
  int counter = 0;

  void incrementCounter() {
    setState(() {
      counter++;
    });
  }

  Widget build(BuildContext context) {
    return new Scaffold(
      toolBar: new ToolBar(
        center: new Text("Flutter Demo")
      ),
      body: new Material(
        child: new Center(
          child: new Text("Button tapped $counter times.")
        )
      ),
      floatingActionButton: new FloatingActionButton(
        child: new Icon(
          icon: 'content/add'
        ),
        onPressed: incrementCounter
      )
    );
  }
}
```

**Comment by sethladd** [comment]
cc @devoncarew @abarth

**Comment by devoncarew** [comment]
+1, makes sense to me. The template code lives here: https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/commands/init.dart#L198

**Comment by sethladd** [comment]
Now that I look at this, not sure this is great. We're building the entire app in the State's build(), when really one the text inside the Center needs to change... maybe there's a better way to do this? Regardless, would love to include some interactivity in the starter template. Open to ideas.

**Comment by abarth** [comment]
That's fine.  Rebuilding widgets is cheap and what we're good at.  :)

**Comment by sethladd** [comment]
The same app now has a button that does something.
