### ISSUE TITLE
The dispose() method is not executed until the keyboard is closed

### ISSUE THREAD

**Issue by Francesco-FL** [flutter/flutter#115288]
## Steps to Reproduce

1) Run the code
2) Click on number "2" (which opens the second tab)

3) Look at the debug console, there are two "PRINT PRINT PRINT" logs executed correctly by the dispose() method

4) Clear the console logs
5) Go back to the first tab by clicking on the number "1"
6) Click on the central TextField (the device keyboard will open as a result)
7) Click on number "2" to open the second tab

8) Look at the debug console: there are no "PRINT PRINT PRINT" logs, as the dispose() method was not executed

9) Close the keyboard

10) Look at the debug console: now the "PRINT PRINT PRINT" logs are present, the dispose() method has been executed correctly

**Expected results:** The dispose() method works right away when changing tabs in both cases

**Actual results:** The dispose() method works right away in the first case, while when the keyboard is open, it must be closed before it is executed.

This means that if I want to manually close (in dispose()) the keyboard when I switch from one tab to another, I cannot do it, because dispose() is not executed.

```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget
{
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Tabs()
    );
  }
}

class Tabs extends StatelessWidget
{
  @override
  Widget build(BuildContext context) {
    return DefaultTabController(
      initialIndex: 0,
      length: 2,
      child: Scaffold(
        resizeToAvoidBottomInset: false,
    
        appBar: AppBar(
          bottom: const TabBar(
            indicatorColor: Colors.white,
            tabs: <Widget>[
              Tab(child: Text("1")),
              Tab(child: Text("2")),
            ],
          ),
        ),
    
        body: TabBarView(
          children: [
            Tab1(),
            Tab2(),
          ],
        ),
    
      ),
    );
  }
}

class Tab1 extends StatefulWidget
{  
  @override
  State<Tab1> createState() => Tab1State();
}
class Tab1State extends State<Tab1> {
  @override
  void dispose() {
    print("PRINT PRINT PRINT");
    super.dispose();
    print("PRINT PRINT PRINT");
  }
  
  @override
  Widget build(BuildContext context) => const Center(
    child: SizedBox(
      width: 100,
      height: 100,
      child: TextField()
    )
  );
}

class Tab2 extends StatelessWidget
{
  @override
  Widget build(BuildContext context) => const SizedBox();
}
```

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.3.7, on Microsoft Windows [Versione 10.0.19045.2251], locale it-IT)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.3.3)   
[√] Android Studio (version 2021.2)
[√] VS Code (version 1.73.1)      
[√] Connected device (4 available)
[√] HTTP Host Availability        

• No issues found!
```

**Comment by darshankawar** [comment]
Thanks for the detailed report @Francesco-FL. However, there's a similar issue open describing your case, https://github.com/flutter/flutter/issues/55571. You may follow-up in it and also upvote it.
Close this as a duplicate.
