### ISSUE TITLE
App is not compliant with how REQUEST_INSTALL_PACKAGES permission is allowed to be used

### ISSUE THREAD

**Issue by kadariyaujwal** [flutter/flutter#115204]
We received mail saying that our app is not compliant with how REQUEST_INSTALL_PACKAGES permission is allowed to be used.The previous version of app was accepted fine, and we only updated packages in this new version. We did not add anything new to the code.

What we tried: Added tools:node="remove" in manifest as per this answer: https://stackoverflow.com/questions/73924613/app-is-not-compliant-with-how-request-install-packages-permission-is-allowed

[Manifest Merger File link]: (https://files.fm/f/ekgrhy9h3)

[Pubspec.yaml File Link]: (https://files.fm/u/mma9y62ru)

Manifest file link: https://files.fm/u/hztdgvhe6#/view/9dyez3t8d)

We submitted an appeal after this, and they denied the appeal. It is frustating for us at this point because we have submitted app multiple times and there is nothing we can do now?

**Comment by stuartmorgan** [comment]
This permission isn't coming from Flutter; if you didn't add it, it's likely coming from one of the packages you depend on. See [previous issues](https://github.com/flutter/flutter/issues?q=is%3Aissue+REQUEST_INSTALL_PACKAGES+is%3Aclosed) for related discussions that may help you resolve this in your project.

Closing as this isn't a Flutter issue.
