### ISSUE TITLE
[web]: Text within an HtmlElementView by default is red

### ISSUE THREAD

**Issue by AsturaPhoenix** [flutter/flutter#115216]
The default body text color mentioned in #58828 as an indicator if an app forgets to pick a style may have implications with content in web platform views, e.g. [`google_maps_flutter_web`](https://pub.dev/packages/google_maps_flutter_web), even if a style is set on the Flutter side.

<img width="582" alt="image" src="https://user-images.githubusercontent.com/13222934/201490090-1df7547f-0dea-430a-a560-bec33bb54bea.png">

It's possible that the resolution would be to require embedded web platform views to do some degree of CSS reset, which might be worth calling out in documentation. There may be some related history in #67740 and #50452.

Potential documentation sites:

* https://api.flutter.dev/flutter/widgets/HtmlElementView-class.html
* Somewhere in https://docs.flutter.dev/development/platform-integration/web/

## Steps to Reproduce

https://dartpad.dev/5661e339114f8e41950451dce63ebad7

* Repros on both stable and master on DartPad.
* Repros on master on both Chrome and Edge in debug and release locally. Also tested and repro'd on Chrome with HTML renderer in debug.
* Repros with or without `textTheme: Typography.blackMountainView`.

**Expected results:** Text styling similar to user-agent default or the nearest Flutter Theme.

**Actual results:** Red text from the body text styling debug indicator.

<details>
<summary>Code sample</summary>

```dart
import 'dart:ui';
import 'dart:html';
import 'package:flutter/material.dart';

void main() {
  platformViewRegistry.registerViewFactory(
      'example', (_) => DivElement()..innerText = 'Hello, HTML!');

  runApp(MaterialApp(
      title: 'Example',
      theme: ThemeData(colorSchemeSeed: const Color(0xff000000)),
      home: Scaffold(
          appBar: AppBar(
            title: const Text('Example'),
          ),
          body: Column(children: const [
            Text('Hello, Flutter!'),
            SizedBox(
                width: 512,
                height: 512,
                child: HtmlElementView(viewType: 'example'))
          ]))));
}

```

</details>

**Comment by arnirichard** [comment]
Not sure how related this is, but default text color is red on mobile web, see text "TextSpan" on 
https://easythai.net 
is default red on mobile browser, but black on Window desktop browsers, I created repo for this (and issue #115046)
https://github.com/arnirichard/fluttertest
Please let me know if this is a separate issue and I will create a bug

**Comment by huycozy** [comment]
@AsturaPhoenix,  thanks for filing the issue. This issue is reproducible on the latest `stable` and `master` channels.
Both `canvaskit` and `html` renderers are affected. 

<details>
<summary>Demo</summary>

![Screenshot 2022-11-14 at 18 58 13](https://user-images.githubusercontent.com/104349824/201656529-97d0283a-2935-4eb2-ba97-e5cdc7ad4450.png)

</details>

<details>
<summary>Sample code (completed)</summary>

```dart
import 'dart:ui' as ui;
import 'dart:html';
import 'package:flutter/material.dart';

void main() {
  ui.platformViewRegistry.registerViewFactory(
      'example', (_) => DivElement()..innerText = 'Hello, HTML!');

  runApp(MaterialApp(
      title: 'Example',
      theme: ThemeData(colorSchemeSeed: const Color(0xff000000)),
      home: Scaffold(
          appBar: AppBar(
            title: const Text('Example'),
          ),
          body: Column(children: const [
            Text('Hello, Flutter!'),
            SizedBox(width: 512, height: 512, child: HtmlElementView(viewType: 'example'))
          ]))));
}

```
</details>

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.3.8, on macOS 13.0 22A380 darwin-x64, locale en-VN)
    • Flutter version 3.3.8 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 52b3dc25f6 (23 hours ago), 2022-11-09 12:09:26 +0800
    • Engine revision 857bd6b74c
    • Dart version 2.18.4
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Community Edition (version 2022.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 70.0.5
    • Dart plugin version 222.4167.21

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.73.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.52.0

[✓] Connected device (3 available)
    • iPhone 14 Pro Max (mobile) • 332079AF-E895-4685-910E-7B1E18B0C6B8 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-0 (simulator)
    • macOS (desktop)            • macos                                • darwin-x64     • macOS 13.0 22A380 darwin-x64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 107.0.5304.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

```bash
[!] Flutter (Channel master, 3.6.0-3.0.pre.1, on macOS 13.0 22A380 darwin-x64, locale en-VN)
    • Flutter version 3.6.0-3.0.pre.1 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cb224d10e3 (26 minutes ago), 2022-11-13 21:57:38 -0500
    • Engine revision b7567b92c7
    • Dart version 2.19.0 (build 2.19.0-394.0.dev)
    • DevTools version 2.19.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Community Edition (version 2022.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 70.0.5
    • Dart plugin version 222.4167.21

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.73.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.52.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 13.0 22A380 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 107.0.5304.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```
</details>

**Comment by huycozy** [comment]
@arnirichard Your issue is different than this one and is being tracked at #115046. Please follow up on it for further updates.

**Comment by AsturaPhoenix** [comment]
> @AsturaPhoenix as a workaround, for google maps, we add a classname of `infowindow-snippet` [here](https://github.com/flutter/plugins/blob/main/packages/google_maps_flutter/google_maps_flutter_web/lib/src/convert.dart#L207-L222) that might help you override the default from a standard stylesheet on your page.

Thanks; for now I'm just wrapping the entire platform view in a CSS reset since I had to fork it anyway to do overlays on web.

e.g. https://github.com/AsturaPhoenix/flutter-plugins/commit/bf627ad5f086c4152717f2eaf39642a48b506dfc

That snippet is interesting though; thank you; I had noticed that web lets us put HTML into an info window while Android does not, and I was curious about things.

**Comment by ditman** [comment]
@AsturaPhoenix very interesting. Another thing you could do to reset that is maybe to apply the reset to the element that we use to define the slot:

<img width="537" alt="Screen Shot 2022-11-17 at 12 15 21 PM" src="https://user-images.githubusercontent.com/1255594/202550312-ef22e57e-6d5d-4850-a028-258c07cc81d8.png">

something like:

```html
<style>
  flt-platform-view {
    all: initial;
  }
</style>
```

Maybe that fixes your platform view without you having to explicitly re-wrap them with another DIV?

**Comment by AsturaPhoenix** [comment]
> something like this somewhere in your index.html:
> 
> ```html
> <style>
>   flt-platform-view {
>     all: initial;
>   }
> </style>
> ```

@ditman I really liked how your idea would patch the problem for all web platform views rather than just Maps, but it turns out it has a hidden side effect that it's taken me a while to notice. Somehow, applying the reset on the `flt-platform-view` (rather than the map `div`) may also prevent stacked elements wrapped in `PointerInterceptor` from displaying 👆 cursors.

<img width="144" alt="image" src="https://user-images.githubusercontent.com/13222934/203734367-f1357e40-9434-464e-b5b9-fddfe23aadf8.png"><img width="122" alt="image" src="https://user-images.githubusercontent.com/13222934/203735206-f81a46ac-ef21-4f2f-8238-e827f5c9798b.png">

Not sure if that'll have any bearing on a long-term fix, but it could be a test case to keep in mind.

**Comment by ditman** [comment]
@AsturaPhoenix apologies, forgot all about the `cursor` style that we set in the body element, you may be able to extend the fix I proposed above with the following CSS:

```css
flt-platform-view {
  all: initial;
  cursor: inherit;
}
```

You can fiddle with it here, without having to rebuild your webapp, this is a pure CSS issue: https://jsfiddle.net/ditman/rk264981

**Comment by AsturaPhoenix** [comment]
@ditman No worries; this is all still pretty early prototyping so a bit of churn is fine. I think I will stick with limiting the reset to the maps div for now though just in case there are any other styles that need to make it through to the platform view for other purposes, since these are hard to notice.

**Comment by ditman** [comment]
In my latest change to the engine, I've moved the red styling away from the body tag, and into the ShadowDOM of the Flutter app, this issue should not happen anymore. Styling of the `.infowindow-snippet` needs to happen in a CSS stylesheet, and cannot be controlled via flutter though.
