### ISSUE TITLE
Update or remove remove the Metal on iOS Wiki page.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#115243]
[The wiki page](https://github.com/flutter/flutter/wiki/Metal-on-iOS-FAQ) is outdated in various ways:

- Mentions OpenGL ES which we have migrated away from.
- Notes minimum OS versions which are outdated.
- Has guidance on binary size that is now invalid since there is no OpenGL ES at all.

Since Metal is everywhere on iOS and the transition has been completed, I think we should just remove the wiki entry as it is causing confusion.

**Comment by chinmaygarde** [comment]
@zanderso, WDYT on just removing the entry?

**Comment by chinmaygarde** [comment]
cc @hy9be

**Comment by zanderso** [comment]
The whole page seems obsolete. Is there anything in it worth keeping that isn't documented elsewhere?

**Comment by chinmaygarde** [comment]
No, even the stuff about Flutter on simulators has been done. I'm removing it.
