### ISSUE TITLE
Viewing network images in webview by launchUrl causes gigantic and unable to be regulated zoom

### ISSUE THREAD

**Issue by KamilSztandur** [flutter/flutter#115291]
Tested and not working on Flutter 3.0.5, both physical and emulated devices, Android 11, Android 13. It works on emulated iOS.

## Steps to Reproduce

1. Execute 'launchUrl' method on android emulated or physical device with image url.

```dart
                IconButton(
                  onPressed: () => launchUrl(
                    Uri.parse(
                      'https://i.pinimg.com/originals/d8/39/74/d839742a057e1d111d0373fa614de906.jpg',
                    ),
                  ),
                  icon: Icon(Icons.abc),
                ),
```

**Expected results:** 

- Preview of this image which fits in screen and is zoomable.

**Actual results:** 
- Image with gigantic zoom which cannot be regulated.
 

https://user-images.githubusercontent.com/61657553/201721019-34501b15-1d30-4aac-b92f-176ab54eae53.mov

**Flutter doctor results:**

> [✓] Flutter (Channel stable, 3.0.5, on macOS 13.0 22A380 darwin-arm, locale en-PL)
>     • Flutter version 3.0.5 at /Users/kamilsztandur/fvm/versions/3.0.5
>     • Upstream repository https://github.com/flutter/flutter.git
>     • Framework revision f1875d570e (4 months ago), 2022-07-13 11:24:16 -0700
>     • Engine revision e85ea0e79c
>     • Dart version 2.17.6
>     • DevTools version 2.12.2
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
>     • Android SDK at /Users/kamilsztandur/Library/Android/sdk
>     • Platform android-33, build-tools 33.0.0
>     • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
>     • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
>     • All Android licenses accepted.
> 
> [✓] Xcode - develop for iOS and macOS (Xcode 14.0)
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • CocoaPods version 1.11.3
> 
> [✓] Chrome - develop for the web
>     • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
> 
> [✓] Android Studio (version 2021.2)
>     • Android Studio at /Applications/Android Studio.app/Contents
>     • Flutter plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/9212-flutter
>     • Dart plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/6351-dart
>     • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
> 
> [✓] VS Code (version 1.73.1)
>     • VS Code at /Applications/Visual Studio Code.app/Contents
>     • Flutter extension version 3.52.0
> 
> [✓] Connected device (4 available)
>     • sdk gphone64 arm64 (mobile) • emulator-5554                        • android-arm64  • Android 12 (API 31) (emulator)
>     • iPhone 14 Pro (mobile)      • 5453118D-46E9-4C36-AE48-73B221C131B9 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-0 (simulator)
>     • macOS (desktop)             • macos                                • darwin-arm64   • macOS 13.0 22A380 darwin-arm
>     • Chrome (web)                • chrome                               • web-javascript • Google Chrome 107.0.5304.110
> 
> [✓] HTTP Host Availability
>     • All required HTTP hosts are available
> 
> • No issues found!

**Comment by danagbemava-nc** [comment]
Hi @KamilSztandur, I believe this is the same issue described by the proposal in https://github.com/flutter/flutter/issues/112973. 

As such, I'll be closing this in favor of the issue linked above, since it does propose a solution. 

Kindly upvote the issue linked above. 

If you disagree, kindly leave a comment below and I will reopen this issue. 

Thank you
