### ISSUE TITLE
Custom Scrollbehavior does not work

### ISSUE THREAD

**Issue by Sesa1988** [flutter/flutter#115278]
I want to remove the bouncing effect from the macOS platform and I can't overwrite it.
All widgets like Columns and other are still bouncing on over scroll.

```
return MaterialApp(
      title: 'Demo',
      scrollBehavior: CustomScrollBehavior(),
      debugShowCheckedModeBanner: false,
....
);
```

I took this snippet from the documentation and adjusted it to me needs. (https://api.flutter.dev/flutter/material/MaterialScrollBehavior/buildOverscrollIndicator.html)
I set the overscroll for macOS on glowing and it doesn't effect anything.

```
import 'package:flutter/material.dart';

class CustomScrollBehavior extends ScrollBehavior {
  @override
  Widget buildOverscrollIndicator(
      BuildContext context, Widget child, ScrollableDetails details) {
    late final AndroidOverscrollIndicator indicator;
    if (Theme.of(context).useMaterial3) {
      indicator = AndroidOverscrollIndicator.stretch;
    } else {
      indicator = AndroidOverscrollIndicator.glow;
    }

    var glowing = GlowingOverscrollIndicator(
      axisDirection: details.direction,
      color: Theme.of(context).colorScheme.secondary,
      child: child,
    );

    var platform = getPlatform(context);

    if (platform == TargetPlatform.linux) return child;
    if (platform == TargetPlatform.macOS) return glowing;
    if (platform == TargetPlatform.windows) return child;
    if (platform == TargetPlatform.fuchsia) return glowing;
    if (platform == TargetPlatform.iOS) return child;
    if (platform == TargetPlatform.android) {
      if (indicator == AndroidOverscrollIndicator.stretch) {
        return StretchingOverscrollIndicator(
          axisDirection: details.direction,
          clipBehavior: details.clipBehavior ?? Clip.hardEdge,
          child: child,
        );
      }
      return glowing;
    }

    return child;
  }
}
```

**Comment by huycozy** [comment]
@Sesa1988 Can you provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this? It would be better if you can also provide a visual demo for this issue. 
And please provide the output of `flutter doctor -v` as well. Thank you!

**Comment by moffatman** [comment]
The bouncing on overscroll is not affected by the `buildOverscrollIndicator`, in fact that's controlled by the `getScrollPhysics`. You should return some `ClampingScrollPhysics` on macOS there if you don't want bouncing overscrolling.

**Comment by Sesa1988** [comment]
> The bouncing on overscroll is not affected by the `buildOverscrollIndicator`, in fact that's controlled by the `getScrollPhysics`. You should return some `ClampingScrollPhysics` on macOS there if you don't want bouncing overscrolling.

Hi, thanks for your response. 

Where can I set ClampingScrollPhysics for my whole application? MaterialApp only accepts a ScrollBehaviour and not compatible with ClampingScrollPhysics.

**Comment by moffatman** [comment]
You can try this on MaterialApp:

```dart
      scrollBehavior: const ScrollBehavior().copyWith(
        physics: const ClampingScrollPhysics(parent: RangeMaintainingScrollPhysics())
      ),
```

**Comment by moffatman** [comment]
Can you explain more what you mean? I have some improvements in Flutter 3.4 (currently in beta) to stop the scrolling when you touch the trackpad again, as well as physics which better match native apps.

**Comment by Sesa1988** [comment]
> Can you explain more what you mean? I have some improvements in Flutter 3.4 (currently in beta) to stop the scrolling when you touch the trackpad again, as well as physics which better match native apps.

Great, thats basically my issues with the current scrolling on macOS.
