### ISSUE TITLE
[Impeller] application with lots of gradients spends too much time on texture upload

### ISSUE THREAD

**Issue by bvoq** [flutter/flutter#115208]
I've modified the example https://github.com/flutter/flutter/blob/master/examples/layers/raw/spinning_square.dart to include 10'000 spinning squares each with a random color shader, redrawn each frame.

I was surprised at the incredible performance, but noticed that when I enabled `--enable-impeller` the performance drops significantly (10x roughly). Is this intended?

Here is my code for comparison:
```
import 'dart:math' as math;
import 'dart:typed_data';
import 'dart:ui' as ui;

void beginFrame(Duration timeStamp) {
  // The timeStamp argument to beginFrame indicates the timing information we
  // should use to clock our animations. It's important to use timeStamp rather
  // than reading the system time because we want all the parts of the system to
  // coordinate the timings of their animations. If each component read the
  // system clock independently, the animations that we processed later would be
  // slightly ahead of the animations we processed earlier.

  // PAINT

  const double R=3;
  final ui.Rect paintBounds = ui.Offset.zero & (ui.window.physicalSize / ui.window.devicePixelRatio);
  final ui.PictureRecorder recorder = ui.PictureRecorder();
  final ui.Canvas canvas = ui.Canvas(recorder, paintBounds);
  var rng = math.Random(213);
  for(int i=0;i<100;++i) {
    for(int j=0;j<100;++j) {
        canvas.save();
        canvas.translate(i*7.0, j*7.0);// paintBounds.width / 2.0, paintBounds.height / 2.0);

        // Here we determine the rotation according to the timeStamp given to us by
        // the engine.
        final double t = timeStamp.inMicroseconds / Duration.microsecondsPerMillisecond / 1800.0;
        canvas.rotate(2.0 * math.pi * (t % 1.0));

        canvas.drawRect(
          const ui.Rect.fromLTRB(-R, -R, R, R),
          ui.Paint()..shader = ui.Gradient.linear(
            const ui.Offset(-R,-R),
            const ui.Offset(R,R),
            const [
                ui.Color.fromARGB(255, rng.nextInt(255),rng.nextInt(255), rng.nextInt(255)),
                ui.Color.fromARGB(255, rng.nextInt(255),rng.nextInt(255), rng.nextInt(255))
            ]
          ),
          //ui.Paint()..color =  ui.Color.fromARGB(255, rng.nextInt(255),rng.nextInt(255), rng.nextInt(255)),
        );
        canvas.restore();
    }
  }
  final ui.Picture picture = recorder.endRecording();

  // COMPOSITE

  final double devicePixelRatio = ui.window.devicePixelRatio;
  final Float64List deviceTransform = Float64List(16)
    ..[0] = devicePixelRatio
    ..[5] = devicePixelRatio
    ..[10] = 1.0
    ..[15] = 1.0;
  final ui.SceneBuilder sceneBuilder = ui.SceneBuilder()
    ..pushTransform(deviceTransform)
    ..addPicture(ui.Offset.zero, picture)
    ..pop();
  ui.window.render(sceneBuilder.build());

  // After rendering the current frame of the animation, we ask the engine to
  // schedule another frame. The engine will call beginFrame again when its time
  // to produce the next frame.
  ui.PlatformDispatcher.instance.scheduleFrame();
}

void main() {
  ui.PlatformDispatcher.instance
    ..onBeginFrame = beginFrame
    ..scheduleFrame();
}
```

**Comment by jonahwilliams** [comment]
What version + device are you on?

**Comment by jonahwilliams** [comment]
I can reproduce the slowness on my end. It looks like we're spending too much time on texture upload. That would probably be from the gradient textures. There are a few different ways we could improve performance here, one would be caching the gradients, the other would be using speciaized shaders for common gradient sizes (2/3/4), another would be to use something like SSBOs (don't know if that would actually be faster though).

<img width="1253" alt="Screen Shot 2022-11-12 at 9 35 34 AM" src="https://user-images.githubusercontent.com/8975114/201487183-0a61bf16-8466-4087-9f47-8e05fa60baf0.png">

**Comment by jonahwilliams** [comment]
> I was surprised at the incredible performance, but noticed that when I enabled --enable-impeller the performance drops significantly (10x roughly). Is this intended?

Impeller is not done yet, so we expect there are going to be a number of circumstances where impeller performs worse than skia, and bug reports will help us identify those scenarios so that we can find and fix them

**Comment by jonahwilliams** [comment]
With the current texture upload performance:

![image](https://user-images.githubusercontent.com/8975114/201490908-62d2f232-2a74-4ea8-9bc4-e331869974f1.png)

With a patch to switch to a specialized 2-color shader:

![image](https://user-images.githubusercontent.com/8975114/201490940-a0f5c78e-cf4c-490b-85d7-3ab525c31343.png)


This is about as fast as Skia. Its possible we could get similar performance by recycling the textures too, I haven't investigated that

**Comment by bvoq** [comment]
> What version + device are you on?

Thank you for the quick reply! I'm very excited for the new update and sorry for the bait title.
I have tested the performance both on iOS simulator (iPhone Pro 14) and on an iPad Pro.
Great work!

**Comment by jonahwilliams** [comment]
Are you on master channel or stable/beta?

**Comment by Lsaier** [comment]
Not intended just hurt for no reason cus the spiritual battle is harder
than I could imagine
I guess the righteous actually do go thru the toughest battles to become
the strongest soldiers for God!  I am bound and determined to stay moral
and strong but also I need to get the correct help I need to do so. Lord
please bring righteous moral people to help me achieve
