### ISSUE TITLE
[Impeller]

### ISSUE THREAD

**Issue by ylloveyou** [flutter/flutter#115224]
我在iOS真机(iOS14.7的系统)测试，并且设置了impeller(FLTEnableImpeller)为true。然后显示系统表情出现灰白色图片。系统表情是采用String.fromCharCode方式呈现的，如这个表情："unicode": 128513。并且滑动时整个画面还出现闪烁的情况。

[✓] Flutter (Channel stable, 3.3.7, on macOS 11.6.4 20G417 darwin-x64, locale zh-Hans-CN)
Checking Android licenses is taking an unexpectedly long time...
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] IntelliJ IDEA Community Edition (version 2022.2.3)
[✓] VS Code (version 1.73.0)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!

**Comment by jonahwilliams** [comment]
Impeller should only be tested on the master channel. In this particular case, we fixed emojis in https://github.com/flutter/engine/pull/36161
