### ISSUE TITLE
crash happens in libflutter.so

### ISSUE THREAD

**Issue by jkl705** [flutter/flutter#115263]
can u guys tell me why is those crash happened?

[tombstone_00.txt](https://github.com/flutter/flutter/files/10000900/tombstone_00.txt)

**Comment by jkl705** [comment]
in case u need the doctor info

**Comment by jkl705** [comment]
``

**Comment by jkl705** [comment]
`[√] Flutter (Channel stable, 3.0.3, on Microsoft Windows [版本 10.0.19044.2130], locale zh-CN)
    • Flutter version 3.0.3 at D:\flutter_windows_3.0.3-stable\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 676cefaaff (5 months ago), 2022-06-22 11:34:49 -0700
    • Engine revision ffe7b86a1e
    • Dart version 2.17.5
    • DevTools version 2.12.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at D:\Android\SDK
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop for Windows (Visual Studio 生成工具 2019 16.11.20)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
    • Visual Studio 生成工具 2019 version 16.11.32929.386
    • Windows 10 SDK version 10.0.19041.0
    X The current Visual Studio installation is incomplete. Please reinstall Visual Studio.

[√] Android Studio (version 2021.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[√] IntelliJ IDEA Community Edition (version 2021.2)
    • IntelliJ at D:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.2.2
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] Connected device (4 available)
    • PCRT00 (mobile)   • emulator-5554 • android-x86    • Android 7.1.2 (API 25)
    • Windows (desktop) • windows       • windows-x64    • Microsoft Windows [版本 10.0.19044.2130]
    • Chrome (web)      • chrome        • web-javascript • Google Chrome 106.0.5249.119
    • Edge (web)        • edge          • web-javascript • Microsoft Edge 106.0.1370.52

[√] HTTP Host Availability
    • All required HTTP hosts are available
`

**Comment by jkl705** [comment]
well i get the dump , and how can i tell which code crash

[3_info.txt](https://github.com/flutter/flutter/files/10001199/3_info.txt)

**Comment by darshankawar** [comment]
@jkl705 
The version you are on is not the latest, so I suggest you to upgrade to latest stable and try again to see if same crash occurs on latest version too or not.

Also, the log txt file you shared is a bit tough to read and extract log from. Perhaps you can provide the log as shared in above format so that it'll be easier to analyze it.

@DjordjeMancic97 The log you shared looks similar to https://github.com/flutter/flutter/issues/90586, so please follow-up in it for further updates.
