### ISSUE TITLE
devicelab-mac-11 is unauthorized and cannot handshake with the swarming service

### ISSUE THREAD

**Issue by ricardoamador** [flutter/flutter#115287]
```
1340 2022-11-14 16:50:47.690 E: Failed to contact for handshake, retrying in 10 sec...
1340 2022-11-14 16:50:57.708 I: Calling /swarming/api/v1/bot/handshake
1340 2022-11-14 16:50:57.709 D: GOOGAPPUID = sha1(2022-11-14-flutter-devicelab-mac-11:/opt/s) % 1000 = 490
1340 2022-11-14 16:50:57.709 I: ts_mon hook_name='get_authentication_headers' pool='cores:12|cpu:x86-64-i7-8700B|device:iPhone8,1|display_attached:0|gce:0|gpu:8086:3e9b|hidpi:0|inside_docker:0|mac_model:Macmini8,1|machine_type:n1-standard-8|os:Mac-12.6-21G115|os:iOS-15.5|pool:default|python:3.8.10+chromium.17|ssd:1|zone:us-corp-mtv'
1340 2022-11-14 16:50:57.710 I: get_authentication_headers(): 0s
1340 2022-11-14 16:50:57.710 I: Fetched auth headers (dict_keys(['X-Luci-Machine-Token'])), they expire in -1811456 sec. Next check in 0 sec.
1340 2022-11-14 16:50:57.787 D: https://chromium-swarm.appspot.com:443 "POST /swarming/api/v1/bot/handshake HTTP/1.1" 401 None
1340 2022-11-14 16:50:57.788 W: Got a reply with HTTP status code 401 for https://chromium-swarm.appspot.com/swarming/api/v1/bot/handshake on attempt 0: 401 Client Error: Unauthorized for url: https://chromium-swarm.appspot.com/swarming/api/v1/bot/handshake
1340 2022-11-14 16:50:57.788 E: Request to https://chromium-swarm.appspot.com/swarming/api/v1/bot/handshake failed with HTTP status code 401: 401 Client Error: Unauthorized for url: https://chromium-swarm.appspot.com/swarming/api/v1/bot/handshake
1340 2022-11-14 16:50:57.788 E: Failed to contact for handshake, retrying in 20 sec...
```

**Comment by drewroengoogle** [comment]
@ricardoamador Just saw this one, do you know if this is still occurring?

**Comment by nehalvpatel** [comment]
Looks like this is still occurring: https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-11

**Comment by ricardoamador** [comment]
Okay the reason mac-11 cannot access the endpoint is that it's local token is bad. Something removed the cron job that recreated the token for access. Looking into fixing and adding the cron job back.

**Comment by ricardoamador** [comment]
The issue is now the install of m2crypto and ssl. Looking for documents to see if we can fix the install so we can create new certs through salt.

**Comment by drewroengoogle** [comment]
@ricardoamador Are there any updates to this issue?

**Comment by ricardoamador** [comment]
Not yet. I planned to get back to this but if you want to take a look in the meantime that's cool.

**Comment by nehalvpatel** [comment]
cc @yusuf-goog said this will be assigned to Kent

**Comment by kentnguyen99** [comment]
Will someone let me know who can make changes on Salt Master server to remove old keys from Salt Master server. Old mac-11 server broken so we built new mac-11 and kept getting errors below when we executed the command "salt-call version-report"  - 
"The Salt Master has cached the public key for this node, this salt minion will wait for 10 seconds to re-authenticate. 
Minion failed to authenticate with the master, has the minion key been accepted?"

**Comment by yusuf-goog** [comment]
@kentnguyen99 please contact vinny through internal ticket for salt issues.

**Comment by kentnguyen99** [comment]
Hi @felizardo,
Can you help on this service ticket?

**Comment by yusuf-goog** [comment]
@kentnguyen99 the request to Vinny needs to be an internal ticket.

**Comment by yusuf-goog** [comment]
Had to install m2crypto manually on the host (which was reimaged recently):

installed brew
then followed instructions in: https://github.com/flutter/flutter/issues/108059

host was able to apply salt states successfully: https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-11

Now hitting some device doctor errors.

**Comment by nehalvpatel** [comment]
@kentnguyen99 Any update on this?

**Comment by yusuf-goog** [comment]
Original issue is resolved. There is a device cert issue for the mac-11 phone, but that will be tracked separately. Closing this.
