### ISSUE TITLE
Phone auth feature for firebase_auth

### ISSUE THREAD

**Issue by MichaelSowah** [flutter/flutter#11527]
Phone auth support would be great inclusion, lately its one of the quickest sign process in mobile app development
 T**ext below picked from this page** https://firebase.google.com/products/auth/ l**inked in the plugin's** page
Firebase Authentication aims to make building secure authentication system easy, while improving the sign-in and onboarding experience for end users. It provides an end-to-end identity solution, supporting **Email/password accounts, phone auth, Google, Twitter, Facebook, GitHub login** and more.

**Comment by Brahmasmi** [comment]
@eseidelGoogle This seems to be a dupe of #10404 . Perhaps, we could close this.

**Comment by mit-mit** [comment]
Closing as a duplicate

**Comment by kroikie** [comment]
@MichaelSowah

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/976. Any further collaboration will be done there.
