### ISSUE TITLE
Chip does not constrain size of children

### ISSUE THREAD

**Issue by ameiyil** [flutter/flutter#11523]
## Steps to Reproduce
I'm trying to utilize the Text widget's overflow properties when I put it into a chip.
However when I do the following the chip is not constraining the size of Text and results in the Text widget being wider than the available space*:
```
new Container(
  constraints: new BoxConstraints(maxWidth: 150.0),
  child: new Chip(
    label: new Text(
      'Some text that exceeds the width of parent',
      overflow: TextOverflow.ellipsis),
    onDeleted: myDeleteFunction
)
```
It produces the following: 
<img width="273" alt="screen shot 2017-08-04 at 3 06 55 pm" src="https://user-images.githubusercontent.com/28424281/28988865-d904c1aa-7926-11e7-8d59-b7b1ae51a2b6.png">

*putting 150.0 for illustrative purposes only, my main use case is this chip in a wrap

**Current work around**
Instead I need to do something like the following - where 38 represents the extra space on the "right" including the "x" icon since I always have a onDeleted function. This, unfortunately, requires me to hard-code the 38.
```dart
new Chip(
    label: new Container(
        constraints: new BoxConstraints(
            maxWidth: 150.0 - 38.0),
        child: new Text(email,
            overflow: TextOverflow.ellipsis)),
    onDeleted: myDeleteFunction,
)
```
Which works and gives me this:
<img width="275" alt="screen shot 2017-08-04 at 3 07 08 pm" src="https://user-images.githubusercontent.com/28424281/28988873-e86d69bc-7926-11e7-954c-3f6268f086c6.png">

## Request
**Would it be possible for the label in Chip to be wrapped with an Expanded?**
Something like this:
```dart
    children.add(new Expanded(
      child: new DefaultTextStyle(
        style: _kLabelStyle,
        child: label
      )
    ));
```

**Comment by Hixie** [comment]
cc @gspencergoog who was working on chips recently.

**Comment by hiddencaliber** [comment]
Is there any update on this?

**Comment by kentcb** [comment]
Was about to report the same issue and found this one. My code is similar to @zoechi's but shows the `Chip` pushing outside its parent's boundaries:

```dart
import 'package:flutter/material.dart';
import 'package:flutter/material.dart' as material;

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Repro',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Test(),
    );
  }
}

class Test extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final shortChip = Chip(
      label: Text(
        "Hello",
        overflow: TextOverflow.clip,
      ),
      deleteIcon: const Icon(
        material.Icons.clear,
      ),
      onDeleted: () {},
    );
    final longChip = Chip(
      label: Text(
        "Here is some long text that is actually too long. Here is some long text that is actually too long",
        overflow: TextOverflow.clip,
      ),
      deleteIcon: const Icon(
        material.Icons.clear,
      ),
      onDeleted: () {},
    );

    final column = Column(
      children: <Widget>[
        shortChip,
        longChip,
      ],
      mainAxisAlignment: MainAxisAlignment.center,
    );

    final container = Container(
      color: Colors.amber,
      child: column,
      width: 200,
      alignment: Alignment.center,
    );

    final scaffold = Scaffold(
      body: container,
      appBar: AppBar(title: Text("Repro")),
    );

    return scaffold;
  }
}
```

Produces:

![Screenshot_20190430-202239](https://user-images.githubusercontent.com/1901832/56956398-602f9980-6b87-11e9-9fb9-557ac016d503.png)
