### ISSUE TITLE
Add a default plugin registrar to PluginRegistry

### ISSUE THREAD

**Issue by mravn-google** [flutter/flutter#11535]
When plugin registration is handled manually, we see code such as
```
MyPlugin.registerWith(registrarFor(MyPlugin.class.getName()));
MyOtherPlugin.registerWith(registrarFor(MyOtherPlugin.class.getName()));
```
in custom `FlutterFragmentActivity` subclasses. The plugin ID given as argument to the `registrarFor` method is used only to distinguish objects published by different plugins, but most plugins don't, and most clients probably wouldn't care anyway. For such cases, a default registrar can be used for all plugins, and the above code could be simplified to e.g.
```
MyPlugin.registerWith(defaultRegistrar());
MyOtherPlugin.registerWith(defaultRegistrar());
```

**Comment by mravn-google** [comment]
On hold. Known use of manual plugin registration is transitioning to use code generation.

**Comment by pyros2097** [comment]
Is there any new solution for this? As I need the registrar for my forked video plugin.

**Comment by stuartmorgan** [comment]
Closing as obsolete since registration is almost always generated.
