### ISSUE TITLE
Mac Web Engine failing trying to connect to a Safari instance

### ISSUE THREAD

**Issue by flar** [flutter/flutter#115309]
Examples:

https://ci.chromium.org/ui/p/flutter/builders/try/Mac%20Web%20Engine/32180/overview
https://ci.chromium.org/ui/p/flutter/builders/try/Mac%20Web%20Engine/32161/overview
https://ci.chromium.org/ui/p/flutter/builders/try/Mac%20Web%20Engine/32149/overview

**Comment by keyonghan** [comment]
F.Y.I. this test has been flaky 7 out of recent 100 runs in prod as well:
https://ci.chromium.org/p/flutter/builders/prod/Mac%20Web%20Engine?limit=100

Bumping the priority to P1. Feel free to adjust the priority as we are not enforcing the flakiness workflow for Engine repo.
/cc @zanderso

**Comment by zanderso** [comment]
The linked runs are all timeouts on:
```
Failed to load "test/skwasm/smoke_test.dart":[0m SessionNotCreatedException (500): Could not create a session: The session timed out while connecting to a Safari instance.
```

cc @eyebrowsoffire @yjbanov

**Comment by zanderso** [comment]
Also 7% flaky seems like this should be P1, yeah.

**Comment by eyebrowsoffire** [comment]
I filed https://github.com/flutter/flutter/issues/115312 yesterday, and we merged in a prospective fix today with https://github.com/flutter/engine/pull/37602

**Comment by zanderso** [comment]
@eyebrowsoffire @keyonghan I'm not seeing recent instances of this flake. Can we close this issue?

**Comment by keyonghan** [comment]
Both Prod and Try ones are passing consistently without hitting a flake in recent 50 runs. Closing.
