### ISSUE TITLE
[tool] the linter does not catch 4 spaces indentation in tools repo

### ISSUE THREAD

**Issue by hellohuanlin** [flutter/flutter#115316]
When I use 4 spaces indentation, the linter does not catch it: 
```
  globals.fs.path.absolute(
      'flutter_template_images',
      'templates',
      'app_shared',
  ),
```
This passes CI and when i run `analyze.dart` locally. we probably want to catch this. 

CC: @jmagman @christopherfujino

**Comment by jonahwilliams** [comment]
We don't use dartfmt in the flutter_tools repo, the linter does not check for style violations

**Comment by christopherfujino** [comment]
https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#in-defense-of-the-extra-work-that-hand-formatting-entails

As Jonah points out, the analyzer does not enforce formatting, that is the domain of dartfmt. And although it seems like it would be easy to write a check for this, formatting is full of edge cases (thus why we do not use dartfmt). Closing this as won't fix.
