### ISSUE TITLE
TextField IME Keyboard does not automatically capitalize the first word in a sentence.

### ISSUE THREAD

**Issue by sarah-fernandez** [flutter/flutter#11531]
## Steps to Reproduce

I fulfilled the Building Beautiful UIs with Flutter Codelab (https://github.com/flutter/friendlychat-steps/tree/master/offline_steps/step_5_finishing_touches) and started the application.

When I touch the message TextField widget to bring the IME keyboard to write, the keyboard always appears in lowercase mode instead of the expected uppercase mode.

Also after typing a "." to finish a sentence and start another, the keyboard remains in lower caps.

This happens in both Android emulators (Android API levels 21 to 26) and  Genymotion emulators (for Android API levels 23 to 25) AOSP keyboards, and with my phone (Nexus 5, API level 23) Gboard keyboard.

## Flutter Doctor

~/IdeaProjects/my_friendly_chat$ flutter doctor
[✓] Flutter (on Linux, locale en_US.UTF-8, channel master)
    • Flutter at /home/sarah/flutter
    • Framework revision 4da5e9b249 (2 days ago), 2017-08-04 17:44:20 -0700
    • Engine revision 73afec4081
    • Tools Dart version 1.25.0-dev.7.0

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.1)
    • Android SDK at /home/sarah/Android/Sdk
    • Platform android-26, build-tools 26.0.1
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-884-b01)

[✓] Android Studio (version 3.0)
    • Android Studio at /opt/android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-884-b01)

[✓] IntelliJ IDEA Community Edition (version 2017.2)
    • Flutter plugin version 16.0
    • Dart plugin version 172.3544.34

[✓] Connected devices
    • Google Nexus 6P, 7 1 0, API 25, 1440x2560 • 192.168.56.101:5555 • android-x86 • Android 7.1.1 (API 25)

Thanks in advance!

**Comment by eseidelGoogle** [comment]
See also https://github.com/flutter/flutter/issues/9363.  FYI @cbracken

**Comment by cbracken** [comment]
For fields with type `TextInputType.text` or `TextInputType.multiline` this should now be fixed on `master`. Please re-open if you're still seeing issues.

**Comment by searchy2** [comment]
`TextInputType.multiline` no longer autocapitalizes sentences. `textCapitalization: TextCapitalization.sentences` must be set in order to automatically capitalize the first word of sentences.

**Comment by Sandrichka22** [comment]
Does TextCapitalization.sentences work for non platform keyboards? And what should we do in case of a non platform keyboard?
