### ISSUE TITLE
Textformfield obscureText is not displayed as expected on iOS

### ISSUE THREAD

**Issue by sami-kouatli-act** [flutter/flutter#115359]
## Steps to Reproduce

1. Execute `flutter run` on the code sample
2. Write text inside the TextFormField

**Expected results:** 

- See the character displayed for few seconds then it is replaced by the obscure character.
- When a character is written, previous characters are directly replace by an obscure character.

**Actual results:** 
It works on Android in both Debug and Release.
It does not work as expected on iOS in both Debug and Release.

<details>
<summary> Result Android Debug Video :</summary>

![androidDebug](https://user-images.githubusercontent.com/74768807/201905137-170f3b95-a6f0-42b8-a4b7-0f9ef1390971.gif)

</details>

<details>
<summary>Result Android Release Video :</summary>

![androidRelease](https://user-images.githubusercontent.com/74768807/201905143-9543f52e-de85-48ce-bb0d-62d5096b321f.gif)

</details>

<details>
<summary>Result iOS Debug Video :</summary>

![iosDebug](https://user-images.githubusercontent.com/74768807/201905130-4b4c9260-ad57-4e6d-bbbc-46bcf78a3c8a.gif)

</details>
Result  iOS Release : 

No video but I have the same behaviour as Debug on my phone.

<details>
<summary>Code sample</summary>

```
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});
  
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});
  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Padding(
          padding: const EdgeInsets.symmetric(horizontal: 20.0),
          child: TextFormField(obscureText: true),
        ),
      ),
    );
  }
}
```

</details>

<details>
  <summary>Logs</summary>

Flutter doctor :
```
[✓] Flutter (Channel stable, 3.3.4, on macOS 13.0.1 22A400 darwin-arm, locale
    fr-FR)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] Connected device (3 available)
[✓] HTTP Host Availability
```

</details>

**Comment by huycozy** [comment]
@Naveed-dev30 Can you share a completed sample code for your solution? As I see there is no property `visiblePassword` in `TextField` and `TextFormField`.

**Comment by sami-kouatli-act** [comment]
I agree with @huycozy, there is not visiblePassword property. The only place where I see "visiblePassword" is in : `keyboardType: TextInputType.visiblePassword`. I tried it and it does not fix the issue.

**Comment by justinmc** [comment]
CC @LongCatIsLooong

**Comment by LongCatIsLooong** [comment]
I think I disabled that in a pull request because when I tested it it wasn't revealing the new characters. But it could be that I was using an external keyboard, it seems on iOS with "secure text entry" on, new characters are only temporarily revealed if the user is entering using the software keyboard. It makes sense to me to restore the old behavior, even when the user is using a hardware keyboard.

**Comment by eleomilagrosa** [comment]
Any update about this?

**Comment by Fernandomr88** [comment]
Guys, is this going to be resolved anytime this year?

**Comment by marcvanbreemen** [comment]
> if the screen is being recorded, it stops behaving like that and hides the characters again

Standard iOS behaviour for obvious reasons.

**Comment by Fernandomr88** [comment]
> > if the screen is being recorded, it stops behaving like that and hides the characters again
> 
> Standard iOS behaviour for obvious reasons.

Yup, just pointing out that this should be the standard behavior on flutter as well. I didn't see anything on flutter implementation code that prevents showing last character if the screen is being recorded/shared

**Comment by justinmc** [comment]
I tried this out on an Android emulator and iOS simulator:

| Platform | Native (Settings => Login) | Flutter (`obscureText: true`) |
| --- | --- | --- |
| Android with hardware keyboard | Briefly visible. |  :heavy_check_mark: Briefly visible. |
| Anrdoid with software keyboard | Briefly visible. | :heavy_check_mark: Briefly visible. |
| Anrdoid while recording the screen, either keyboard| Briefly visible? Can someone confirm? | :heavy_check_mark: Briefly visible. |
| iOS with hardware keyboard | Always obscured. | :heavy_check_mark: Always obscured. |
| iOS with software keyboard | Briefly visible. | :x: Always obscured. |
| iOS while recording the screen, either keyboard | Always obscured? Can someone confirm? | :heavy_check_mark: Always obscured |

To fix that one red :x: without breaking any thing else, I think the framework would need to be able to distinguish input coming from a hardware keyboard vs. a software keyboard, and it would also need to know if the screen is currently being recorded.

Does that look like an accurate assessment?

**Comment by Fernandomr88** [comment]
> 
> Anrdoid while recording the screen, either keyboard | Briefly visible **CONFIRMED** | ✔️ Briefly visible.
> -- | -- | --
> 
> iOS while recording the screen, either keyboard | Always obscured **CONFIRMED** | ✔️ Always obscured
> -- | -- | --


The rest is accurate @justinmc

**Comment by justinmc** [comment]
Agreed. Thanks for verifying the "iOS while recording" case, I've updated the table.

**Comment by optdxf** [comment]
Any update on this?
