### ISSUE TITLE
Android version code and version name missing

### ISSUE THREAD

**Issue by adityamv7** [flutter/flutter#11532]
## Steps to Reproduce

I created an app through git cmd on windows 10 Home and from last 2-3 times i observed 
the android manifest xml does not contain android versionCode and android versionName
and app does not run on emulator due this, but as soon as i add them back the app works fine

## Flutter Doctor
```
G:\flutter>flutter doctor
[√] Flutter (on Microsoft Windows [Version 10.0.14393], locale en-IN, channel alpha)
    • Flutter at G:\flutter
    • Framework revision bbcfb8d51a (5 days ago), 2017-08-01 14:50:29 -0700
    • Engine revision f2af347363
    • Tools Dart version 1.25.0-dev.7.0

[√] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at G:\sdk
    • Platform android-25, build-tools 25.0.3
    • ANDROID_HOME = G:\sdk
    • Java binary at: G:\Android\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_76-release-b03)

[√] Android Studio (version 2.2)
    • Android Studio at G:\Android
    • Java version OpenJDK Runtime Environment (build 1.8.0_76-release-b03)

[√] IntelliJ IDEA Community Edition (version 2017.2)
    • Flutter plugin version 16.0
    • Dart plugin version 172.3544.34

[√] Connected devices
    • None
```

**Comment by eseidelGoogle** [comment]
https://github.com/flutter/flutter/blob/master/packages/flutter_tools/templates/create/android.tmpl/app/src/main/AndroidManifest.xml.tmpl is the file in question.  FYI @mit-mit

**Comment by mit-mit** [comment]
cc @mravn-google

**Comment by mravn-google** [comment]
We moved this information to https://github.com/flutter/flutter/blob/master/packages/flutter_tools/templates/create/android-java.tmpl/app/build.gradle.tmpl and the Kotlin to follow how Android Studio sets up a new project on a Mac. We'll check if AS does this differently on Windows.

**Comment by mit-mit** [comment]
Sorry to hear @adityamv7. I tried to repro on Windows with flutter on the master channel and freshly updated. These steps work for me with a running Android emulator:

```
flutter create test01
cd test01
flutter run
```

Can you clarify which steps are not working for you?

**Comment by adityamv7** [comment]
@mit-mit flutter run does not work if version code and version name are not present

**Comment by mit-mit** [comment]
I believe that might be resolved in the update of the alpha channel we did yesterday. Would you mind running `flutter update` and then:

```
flutter create test01
cd test01
flutter run
```

and see if that works?

**Comment by mit-mit** [comment]
Alternatively, I see you are on the fairly old Android Studio 2.2 -- maybe update that to 2.3.3?

**Comment by adityamv7** [comment]
@mit-mit  i will try both the things and revert back here to confirm the same

**Comment by zoechi** [comment]
This issue looks stale.
