### ISSUE TITLE
Create a minimal UI or at least a .mov that shows drag and drop example(s) happening on screen

### ISSUE THREAD

**Issue by deborah-ufw** [flutter/flutter#11538]
Our dev team is using Flutter with the expectation that UI team will understand and specify existing Flutter widgets. 

However, for drag and drop, there is no UI example to visibly evaluate how the widget works, what it has as a native behavior and what it doesn't, and whether or not it can be used to solve a particular UI problem. Our product team delivers specific requirements, but we can't tell how much the drag and drop will solve out of the box, or how much customizing it will need if we use it, because there is no visible working example we can look at. 

This makes costing and evaluating a drag and drop solution, which we would like to use, difficult.

For example, does the area show a visual cue over where something user is dragging can be dropped? What kind of animation is it using? Is there a long tap option to activate drag or only a tap? Is there a shadow that has to be removed for our flat design? Etc.

There is a code example at https://github.com/flutter/flutter/blob/master/dev/manual_tests/lib/drag_and_drop.dart but this does not help us very much.

We need to see it work in a UI, even a super minimal UI, even a .mov example showing the options we can specify, in order to know what to ask for from our dev team or if we'll need to look for a different UI instead of drag and drop for our use case.

**Comment by Hixie** [comment]
`drag_and_drop.dart` isn't just a code sample, it's an application you can run and show your UI team.

**Comment by deborah-ufw** [comment]
How???

**Comment by sethladd** [comment]
@deborah-ufw hi! thanks for the feedback, we'd love to chat with you (and/or your dev team) to learn more about how you're using Flutter. If you're interested, please email me at sethladd at google dot com. Looking forward to learning more, thanks!

**Comment by deborah-ufw** [comment]
How shall we chat? 

I would like to see a visual example of the drag and drop, even if it’s a .mov. I am not sure how to use the .dart. It seems like I would have to build a UI myself to plug it into to evaluate.

Thank you,
Deborah

**Comment by sethladd** [comment]
> How shall we chat?

Send me an email (I can't seem to find your email) and we'll find a time to either Hangout or chat in person. It appears you are in Mountain View? So are we :)

**Comment by deborah-ufw** [comment]
Hi !!

I’m actually with Carnivore Studios in SF, but my GitHub email always goes to this address :). Mt. View is awesome !!!  I used to work at a startup right next door to Evernote’s original offices.

Hangout sounds like a great solution.  When works for you? I’m pretty crushed with deadline for today, but this eve or tomorrow between about 11 (after all our meets) and 7pm is wide open.

Thanks Seth!
Deborah

**Comment by sethladd** [comment]
Oh, Carnivore! Right on... ok, makes sense :)

Please email me directly (sethladd at google dot com) and we'll work it out. Thanks!

**Comment by Hixie** [comment]
To run the drag-and-drop example, you just use `flutter run` in that directory (or copy and paste the contents of the relevant file into the 'main.dart' of a `flutter create` app). Specifically for this one you'd run `flutter run -t drag_and_drop.dart` in the `dev/manual_tests` directory of the flutter repo.

**Comment by deborah-ufw** [comment]
Ok. I will give this a shot. 

This seems like it would be good to reference on the widget page, and to comment in the code of the linked .dart.

Thanks!

**Comment by markusaksli-nc** [comment]
Closing since [Draggable video](https://api.flutter.dev/flutter/widgets/Draggable-class.html) clearly demonstrates this.
