### ISSUE TITLE
engine gn scripts fail to build unit tests when building for an Arm CPU

### ISSUE THREAD

**Issue by flar** [flutter/flutter#115322]
Currently, when you build on an M1 Mac you have to manually specify a `gn` argument to build for an `arm64` CPU. Because of the way that the unit tests are enabled, this will turn off the unit test builds by default unless you manually specify the `--enable-unittests` command line argument to `gn`. This problem likely is due to the following line of code:

https://github.com/flutter/engine/blob/d366183c03c9e12b8e0845ed2f35c6c091a29627/testing/testing.gni#L15

**Comment by cbracken** [comment]
This is a sub-component of https://github.com/flutter/flutter/issues/103386. Leaving it open and treating the above as a general umbrella issue.

**Comment by cbracken** [comment]
We now have universal `gen_snapshot` executables for macOS and iOS targets. Working on the same for Android. Once that work has landed, I'll get back to this issue (which admittedly I haven't reverified in a while) which is part of the broader issue of being able to build in general on Apple Silicon macOS host machines: https://github.com/flutter/flutter/issues/103386

**Comment by cbracken** [comment]
This was resolved in flutter/engine#41215.
