### ISSUE TITLE
[ios] build-name build arg only use numeric characters in ios

### ISSUE THREAD

**Issue by mirland** [flutter/flutter#115483]
When I use the [`build-name`](https://docs.flutter.dev/deployment/ios#update-the-apps-build-and-version-numbers) flag to create my ipa file, Flutter only takes the numeric characters. 

When I execute `flutter build apk  --flavor dev --build-name 0.0.1-2c62365` the result build name is `0.0.1-2c62365`. However, If I do the same for ios `flutter build ipa  --flavor dev --build-name 0.0.1-2c62365 --export-options-plist ios/ExportOptions/dev_firebase.plist` the result application name is `0.0.1262365`. 

Flutter removed the non-number characters for ios.

## Steps to Reproduce

1. Compile an IPA using `flutter build ipa  --build-name 0.0.1-2caa3`

**Expected results:** The version name should be `0.0.1-2caa3`

**Actual results:** The version name is `0.0.123`

## Flutter Doctor
```
octor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.6, on macOS 13.0.1 22A400 darwin-arm, locale en-UY)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] Android Studio (version 2021.3)
[✓] Android Studio (version 2021.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2022.2.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2022.2.3)
[✓] VS Code (version 1.73.1)
[✓] Connected device (5 available)
[✓] HTTP Host Availability

• No issues found!
```

**Comment by mirland** [comment]
Hi @exaby73 thanks for the response, for android, I inspected the apk (and also firebase app distribution displays it in a proper way).
Firebase image: 
![image](https://user-images.githubusercontent.com/8472881/202462493-e30f8861-98ff-4d2b-a3c7-bf67c44617a4.png)

For ios I checked the `Info.plist` located in the ipa file (you can do it executing `tar -zxvOf IpaName.ipa Payload/AppName.app/Info.plist | plutil -convert xml1 -r -o - -- - | grep -A 1 CFBundleShortVersionString`). Also I checked the name displayed in firebase and it's wrong.

![image](https://user-images.githubusercontent.com/8472881/202462693-4a534c3b-84e0-4112-9592-219fca6d2e6d.png)


Also I checked the flutter code and it seems that it's [doing that](https://github.com/flutter/flutter/blob/8230ef5e85291bf9e086fdc81867786d628e4cdd/packages/flutter_tools/lib/src/build_info.dart#L516).
```dart
  if (targetPlatform == TargetPlatform.ios ||
      targetPlatform == TargetPlatform.darwin) {
    // See CFBundleShortVersionString at https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
    final RegExp disallowed = RegExp(r'[^\d\.]');
    String tmpBuildName = buildName.replaceAll(disallowed, '');
    if (tmpBuildName.isEmpty) {
      return null;
    }
    final List<String> segments = tmpBuildName
        .split('.')
        .where((String segment) => segment.isNotEmpty)
        .toList();
    while (segments.length < 3) {
      segments.add('0');
    }
    tmpBuildName = segments.join('.');
    if (tmpBuildName != buildName) {
      logger.printTrace('Invalid build-name: $buildName for iOS/macOS, overridden by $tmpBuildName.\n'
          'See CFBundleShortVersionString at https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html');
    }
    return tmpBuildName;
  }
  ```
Based on that documentation, IOS does not support a version name like `1.2.3-asd`. However, I tested and it works (I have been using it for years).
So the questions here are:
- should flutter update your build name based on IOS documentation? 
- Should flutter provide different build names for android and ios?

In my opinion Flutter shouldn't process the name that you are defining in the `build-name`, if you define something flutter should use it (it could return a warning, but it shouldn't change it). Furthermore, Flutter shouldn't return different build name depending on the platform.

If your responses are that is ok as it is now, you can just close my issue.
Again, thanks!

**Comment by darshankawar** [comment]
@mirland 
I believe the difference you are seeing on Android and iOS based on `build-name` is how it works fundamentally.
Please check below comment for more details: https://github.com/flutter/flutter/issues/27589#issuecomment-464457660
And also [this](https://github.com/flutter/flutter/issues/27589#issuecomment-573121390) comment from Flutter team for your reference.

Based on above, I am going ahead and closing it. If you disagree, write in comments and I'll reopen it.

**Comment by mirland** [comment]
From my point of view, Flutter shouldn't process the name or the version that you are defining, it's a matter of responsibility. when you set something, Flutter should just use it. However, I also understand your point, and I think it's valid. Thanks for your response and for taking the time to give me a clear response!
