### ISSUE TITLE
The plugins `google_sign_in` use a deprecated version of the Android embedding.

### ISSUE THREAD

**Issue by thaliachitziou99** [flutter/flutter#115435]
I have a problem downloading the plugin. I use `flutter version 3.3.8`. The message that I get when I run `flutter pub get` is this:

**_The plugins "google_sign_in" use a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if these plugins support the Android V2 embedding. Otherwise, consider removing them since a future release of Flutter will remove these deprecated APIs.
If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration._**

**Comment by danagbemava-nc** [comment]
Hi @thaliachitziou99, what version of `google_sign_in` are you using? I added the plugin to a project and I did not get the error. Please also provide the version of `google_sign_in_android` that you're using. 

If you are not on the latest version of the plugin, kindly upgrade to the latest version of the plugin and try again. 

Thank you

**Comment by thaliachitziou99** [comment]
> Hi @thaliachitziou99, what version of `google_sign_in` are you using? I added the plugin to a project and I did not get the error. Please also provide the version of `google_sign_in_android` that you're using.
> 
> If you are not on the latest version of the plugin, kindly upgrade to the latest version of the plugin and try again.
> 
> Thank you

I used the command `flutter pub add google_sign_in` and the version was 4.0.16. I went to the site pub dev to see if this is the latest version and it wan't. I added the right one and it worked. Thank you so much

**Comment by danagbemava-nc** [comment]
Closing this as solved.
