### ISSUE TITLE
PlatformException with image picker plugin 

### ISSUE THREAD

**Issue by AhkamKhalaaf** [flutter/flutter#115469]
i use image_picker: ^0.8.5+3 
this is my code 
  final ImagePicker _picker = ImagePicker();

    _getFromCamera() async {
      try {
        XFile? image = await _picker.pickImage(
          source: ImageSource.gallery,
        );
      } catch (e) {
        debugPrint('${e.toString()}, ');
      }
    }
,this is error 
 PlatformException(channel-error, Unable to establish connection on channel., null, null)

when i run iphone 14  simulator

**Comment by huycozy** [comment]
Hi @AhkamKhalaaf
I can not reproduce this issue from my side with the same simulator and plugin version `image_picker: ^0.8.6` and the latest Flutter stable `3.3.8`.
Can you try with `image_picker: ^0.8.6`? Also, please provide the output of `flutter doctor -v` as well.
