### ISSUE TITLE
Flutter CLI tools should understand build variants

### ISSUE THREAD

**Issue by mravn-google** [flutter/flutter#11547]
https://github.com/flutter/flutter/pull/11354 added support for Android build variants in the Flutter Gradle plugin. But Flutter CLI tooling also need to know about build variants, so that `flutter run` and friends are able to do the correct thing.

**Comment by Hixie** [comment]
Is this something we would handle by having a command line argument to pick the flavour? With some default maybe?

**Comment by mravn-google** [comment]
@Hixie Yes, I'm currently considering something simple like `flutter run --release --flavor paid`. The `flavor` option maps directly to an Android product flavor and loosely to an Xcode scheme.

Not specifying `flavor` means using the default product flavor/scheme (current behavior).

## Android

The command above makes sense if the user has added a `paid` product flavor in their `android/app/build.gradle` file (presumably along with a `free` product flavor). The Android Gradle plugin then creates tasks named `assemblePaidDebug` and `assemblePaidRelease` (and friends), and we execute the latter one to create an output file named `app-paid-release.apk`.

Details: Using the Android Gradle plugin, we build a "build variant" which is defined as a pair of a product flavor and a build type. By default, there is a single, unnamed product flavor and the build types are `debug` and `release`. The Flutter Gradle plugin adds the `profile` build type. Users can add custom product flavors whereby the default unnamed flavor disappears.

Adding the `flavor` option does not address custom build types, which are more complicated, as they would have to be mapped somehow to the Flutter build modes debug/profile/release. One path forward may be a "name override" option as in `flutter run --release --nameOverride beta` that does a release build as far as Flutter tooling is concerned, but maps to the `assembleBeta` Gradle task. With flavors that would be `flutter run --release --nameOverride beta --flavor paid`, mapping to `assemblePaidBeta`.

## iOS

The command above makes sense if the user has created a `Release (Paid)` build configuration (presumably along with `Debug (Paid)`, `Release (Free)`, and `Debug (Free)`). The user might have organized these using two schemes named `Paid` and `Free`, but that should be optional.

Details: Xcode by default creates the `Debug` and `Release` build configurations and a default scheme.

It may be good to support other build configuration naming conventions such as `Release Paid`, `Paid Release`, `Release-Paid` etc. I'll look into that.

If the user adds alternatives to `Release` and `Debug`, we could deal with that using the name override option discussed above.

**Comment by xster** [comment]
Is there a bug tracking support for building arbitrarily named build configurations inside arbitrarily named schemes? 

It seems like currently the expected build configurations' names must be named a specific way.

**Comment by mravn-google** [comment]
@xster Not that I know of. Do we need that complexity?

**Comment by xster** [comment]
Seems like Posse is already inadvertently (maybe?) doing it. I think it still coincidentally works because nobody cleaned their generated.xconfig for a long time but if they hire someone new, they might not be able to build anymore.

**Comment by chenyang88** [comment]
how should I configure Debug on VS Code about `flutter run --flavor stag` ??

**Comment by mit-mit** [comment]
@chenyang88, I suggest you open an issue on that over in https://github.com/Dart-Code/Dart-Code/issues

**Comment by knezzz** [comment]
Hi,

Shouldn't the chosen build variant also be available through Dart code?
Something like:

```dart
if(BuildInfo.flavor == 'dev'){
  return Colors.red;
}else{
  return Colors.blue;
}
```

**Comment by mravn-google** [comment]
@knezzz The build flavor is available to platform-specific code, if you choose to set that up using platform-specific means. Then you can access the flavor from Dart using platform channels. There is an example in the Flutter repo [here](https://github.com/flutter/flutter/tree/master/dev/integration_tests/flavors).

**Comment by knezzz** [comment]
@mravn-google Oh ok, great thanks, Ill try to use it like that then :)

**Comment by thaihuynhxyz** [comment]
Hi,

Could we config source set for flavors? as I develop Android Application:

> src/demoDebug/ (build variant source set)
src/debug/ (build type source set)
src/demo/ (product flavor source set)
src/main/ (main source set)

**Comment by cloudjlb** [comment]
So is the verdict that you must use either debug or release configurations for android?

**Comment by thaihuynhxyz** [comment]
Yes, I follow [Config build variant guide](https://developer.android.com/studio/build/build-variants#sourceset-build)
