### ISSUE TITLE
[Impeller] Fix SDF Text rendering on Vulkan

### ISSUE THREAD

**Issue by iskakaushik** [flutter/flutter#115461]
Repro:

`./out/host_debug_unopt/exe.unstripped/impeller_unittests --gtest_filter="*SdfText/Vulkan*" --timeout=-1`

![image](https://user-images.githubusercontent.com/1006071/202244944-af8de51d-fdd3-43a2-ad2a-1cf5f9885f83.png)

**Comment by iskakaushik** [comment]
cc: @dnfield I'm not sure why this is happening, ImgUI is able to render text reasonably, could it be because I haven't yet wired the depth stencil buffer on the Vulkan backend?

**Comment by dnfield** [comment]
I'd try to use some kind of frame capturing tools to see what the SDF texture looks like.

**Comment by bdero** [comment]
From talking to @iskakaushik, my guess is that this is a problem with the texture upload of the software generated glyph atlas. The whole atlas appears to get repeated 4 times in each case (shared by @iskakaushik): 
![image](https://user-images.githubusercontent.com/919017/202306599-78ebb1d9-715d-4d9b-99cc-3f3166087ff1.png)
![image](https://user-images.githubusercontent.com/919017/202306899-43362f4d-84f5-4c6c-b15f-b76431159588.png)
![image](https://user-images.githubusercontent.com/919017/202306940-5463682e-a405-424d-90c3-d170e6701e87.png)

**Comment by bdero** [comment]
These non-color atlases should be `PixelFormat::kA8UNormInt` -- are `A8UNormInt` textures working properly in the Vulkan backend yet?
