### ISSUE TITLE
[in_app_purchase] Getting a transactionReceipt for a SKPaymentTransactionWrapper object 

### ISSUE THREAD

**Issue by SofiSheromova** [flutter/flutter#115429]
`SKPaymentTransactionWrapper` documentation contains the lines:
- Completed transactions provide a receipt
- Dart wrapper around Store Kit's `SKPaymentTransaction`   
<img width="820" alt="image" src="https://user-images.githubusercontent.com/41895601/202160866-ca297ba6-d274-41c6-9031-e16b63c2e57f.png">  

If we go to the [`SKPaymentTransaction`](https://developer.apple.com/documentation/storekit/skpaymenttransaction?language=objc) documentation, we will see that it contains information about `transactionReceipt`.  
![image](https://user-images.githubusercontent.com/41895601/202161085-3a9a9b1c-f0dd-4e57-90e6-d11ae3850a63.png)

Unfortunately, `SKPaymentTransactionWrapper` does not contain this field. Is there any way I can get information about receipt?

Versions:
* `in_app_purchase_storekit: 0.3.3`  
* `in_app_purchase: 3.0.8`

**Comment by danagbemava-nc** [comment]
Hi @SofiSheromova, if you read the documentation for [transactionReceipt](https://developer.apple.com/documentation/storekit/skpaymenttransaction/1617722-transactionreceipt?language=objc)
 you will find that apple has deprecated that property and instead recommends that you follow any of the guides in https://developer.apple.com/documentation/storekit/in-app_purchase/original_api_for_in-app_purchase/choosing_a_receipt_validation_technique#//apple_ref/doc/uid/TP40010573. 

Does the above information help?

**Comment by SofiSheromova** [comment]
@danagbemava-nc thanks for the answer!  
I didn't really notice that the field was marked deprecated.   

I was able to get a Receipt by calling the function `SKReceiptManager.retrieveReceiptData()`

<img width="484" alt="image" src="https://user-images.githubusercontent.com/41895601/202638158-fbbbea43-f65c-4d51-8d17-b7e8c0f6efcd.png">

**Comment by danagbemava-nc** [comment]
Oh, I didn't realise there was receipt manager class in the storekit plugin. 

Closing this as solved. 

Thank you
