### ISSUE TITLE
Support for "silent login" of existing users with Firebase Auth

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#11541]
Our current customer is asking for "Silent login of existing users (awaiting a call to FirebaseAuth.instance.currentUser)"

**Comment by sethladd** [comment]
From a customer:

We want our users to be able to login with email and password and we want to retrieve this authentication from cache when the app is restarted.

We found that it takes a few moment for firebase auth to verify authentication status with the server, even when retrieving it from cache.

When trying to log an existing user in automatically, we found that auth.currentUser sometimes returns null because the login process is still ongoing.

In fact, firebase_auth.dart describes the currentUser getter this way: “Synchronously gets the cached current user, or `null` if there is none.”

We essentially need a variant of FirebaseUser.currentUser that we can await so that we can be sure that no firebase auth login is still pending

(if I got any part of the login process wrong, please let me know)

**Comment by sethladd** [comment]
cc @kroikie for thoughts on if this is "normal" behavior, or what the API should look like here.

**Comment by kroikie** [comment]
If I understand the request correctly this is a request for the implementation of getting the cached user, which is available via the onAuthStateChanged callback.

Something along the lines of this [PR](https://github.com/flutter/plugins/pull/180) could be the solution.

**Comment by sethladd** [comment]
Thanks @kroikie . If you can help us land the PR, that would be excellent.

**Comment by collinjackson** [comment]
I believe that this was fixed by #180

**Comment by kroikie** [comment]
@sethladd

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/974. Any further collaboration will be done there.
