### ISSUE TITLE
If flutter start fails because of INSTALL_FAILED_NO_MATCHING_ABIS, no error is displayed

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#1154]
Trying to run against genymotion, and when I run `flutter start`, here's what I see:

```
~/flutter/testme $ flutter start
Installing SkyShell.apk on device.
~/flutter/testme $ 
```

But nothing happens.

If I run with --very-verbose, then I see `Failure [INSTALL_FAILED_NO_MATCHING_ABIS]` and `Error type 3` and `Error: Activity class {org.domokit.sky.shell/org.domokit.sky.shell.SkyActivity} does not exist.` amongst the output.

Can we detect the error/failure, and tell the developer something like "Sorry, something went wrong. Please re-run this command with --very-verbose, copy the output, and paste it into a new issue: https://github.com/flutter/flutter/issues"

Thanks!

**Comment by eseidelGoogle** [comment]
@jason-simmons fixed our builders to produce Android x86 and x64 builds so we should no longer hit this in the common case.  I'm not sure if we give a better error message now, but it should be way harder to hit this at least.
