### ISSUE TITLE
cursor in TextField in flutter PWA  

### ISSUE THREAD

**Issue by moein-keyvani-pur** [flutter/flutter#115418]
when building PWA from the flutter app and opening it on mobile, I have a problem with the cursor, in the flutter app all things are ok but on the PWA the cursor in TextField is one behind the last character. but if add a character it adds to the end text but in UI one character is behind.
`enableInteractiveSelection: kIsWeb ? false : true,`
I assumed that the problem was due to the conflict between the Chrome cursor and the Flutter pointer. therefore
I add the above feature to my TextField but it isn't work
`[√] Flutter (Channel stable, 2.10.4, on Microsoft Windows [Version 10.0.17763.3650], locale en-US)`
`[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)`
`[√] Chrome - develop for the web`
`[!] Visual Studio - develop for Windows (Visual Studio Community 2022 17.0.5)
    ! Unable to locate a Windows 10 SDK. If building fails, install the Windows 10 SDK in Visual Studio.`
`[√] Android Studio (version 2021.1)`
`[√] VS Code (version 1.73.1)`
`[√] Connected device (2 available)`
`[√] HTTP Host Availability`
`! Doctor found issues in 1 category`

the bottom link is a gif for this problem
https://user-images.githubusercontent.com/81565043/202128010-a768f0c5-7080-4d6d-880e-96962d6da879.mp4

**Comment by huycozy** [comment]
Hi @moein-keyvani-pur 
Can you retry reproducing the issue with English alphabet?

Also, as far as I can see, you are using the old Flutter version `2.10.4`, the latest Flutter stable is `3.3.8` and the master is `3.6.0`. Please try upgrading them and retry to see if this issue still reproduces. Thank you!

**Comment by moein-keyvani-pur** [comment]
> Hi @moein-keyvani-pur Can you retry reproducing the issue with English alphabet?
> 
> Also, as far as I can see, you are using the old Flutter version `2.10.4`, the latest Flutter stable is `3.3.8` and the master is `3.6.0`. Please try upgrading them and retry to see if this issue still reproduces. Thank you!

thank you for your help, it worked
