### ISSUE TITLE
[macOS] Scrolling does not work anymore on macOS after Flutter upgrade

### ISSUE THREAD

**Issue by Sesa1988** [flutter/flutter#115428]
I updated Flutter and scrolling on macOS stopped working. It still works on all other platforms without any issue.

**Steps to reproduce**
- Start example application on macOS
- Swipe on trackpad

**Actual result**
Nothing happens

**Expected result**
Scrolling works

https://github.com/Sesa1988/easy_table_flutter

**Comment by moffatman** [comment]
Hi, in Flutter 3.3 scrolling from a trackpad has its own type of events, see here for more details: https://docs.flutter.dev/release/breaking-changes/trackpad-gestures

I took a look in your application, looks like you have done a very custom scrolling implementation. You can get the trackpad scrolling working again with the following change:

```dart
diff --git a/lib/src/table.dart b/lib/src/table.dart
index 641612e..0e88f58 100644
--- a/lib/src/table.dart
+++ b/lib/src/table.dart
@@ -198,6 +198,11 @@ class _EasyTableState<ROW> extends State<EasyTable<ROW>> {
             _focusNode.requestFocus();
           }
         },
+        onPointerPanZoomUpdate: (e) {
+          if (e.panDelta.dy != 0) {
+            _scrollControllers.vertical.position.pointerScroll(-e.panDelta.dy);
+          }
+        },
         onPointerSignal: (pointerSignal) {
           if (pointerSignal is PointerScrollEvent) {
             _onPointerScroll(pointerSignal, themeMetrics.row.height);
```

**Comment by Sesa1988** [comment]
> Hi, in Flutter 3.3 scrolling from a trackpad has its own type of events, see here for more details: https://docs.flutter.dev/release/breaking-changes/trackpad-gestures
> 
> I took a look in your application, looks like you have done a very custom scrolling implementation. You can get the trackpad scrolling working again with the following change:
> 
> ```dart
> diff --git a/lib/src/table.dart b/lib/src/table.dart
> index 641612e..0e88f58 100644
> --- a/lib/src/table.dart
> +++ b/lib/src/table.dart
> @@ -198,6 +198,11 @@ class _EasyTableState<ROW> extends State<EasyTable<ROW>> {
>              _focusNode.requestFocus();
>            }
>          },
> +        onPointerPanZoomUpdate: (e) {
> +          if (e.panDelta.dy != 0) {
> +            _scrollControllers.vertical.position.pointerScroll(-e.panDelta.dy);
> +          }
> +        },
>          onPointerSignal: (pointerSignal) {
>            if (pointerSignal is PointerScrollEvent) {
>              _onPointerScroll(pointerSignal, themeMetrics.row.height);
> ```

Thank you this works and my issue if fixed!
