### ISSUE TITLE
Remove packaging configurations from flutter infra repository

### ISSUE THREAD

**Issue by drewroengoogle** [flutter/flutter#115493]
This is the list of tasks to perform as part of cleaning up packaging configurations

- [x] Update `firebase_project` in `Linux docs_deploy` to `docs-flutter-dev`
- [x] Remove packaging configurations from flutter.googlesource.com/infra

**Comment by godofredoc** [comment]
The projects parts was addressed by creating a build for each of the beta|stable configurations.

**Comment by godofredoc** [comment]
Fixed with https://flutter-review.googlesource.com/c/infra/+/37280
