### ISSUE TITLE
DefaultTabController with NestedScrollView change tab lose information about innerBoxIsScrolled

### ISSUE THREAD

**Issue by fabiomlferreira** [flutter/flutter#115557]
In a DefaultTabController with a NestedScrollView I want to change the color of the TabBar depending on the innerBoxIsScrolled option, it works great if you scroll for example in the first tab but with it scrolled down if you change the tab the innerBoxIsScrolled change to false instead of still true.

Here is an example, this example is exactly the same we have on the https://api.flutter.dev/flutter/widgets/NestedScrollView-class.html page I only added a color to be easier to see the problem. In the official example the forceElevated have the same problem but it's more hard to see.

https://dartpad.dev/?id=e5cf3f249111a7bb001313a6c10d29b4

![Example](https://i.imgur.com/ZgayL9W.gif)

How can I keep the innerBoxIsScrolled value correct on tab change?

**Comment by exaby73** [comment]
## Triage report

I can reproduce this issue with the code sample OP provided in Dartpad on master channel. Labeling the issue for further insights from the team

**Comment by goderbauer** [comment]
cc @Piinks

**Comment by Piinks** [comment]
Hi @fabiomlferreira this is working as expected. When you switch to tab 2, the inner scroll view is no longer scrolled, it is at the zero position. That is why innerBoxIsScrolled is false.
