### ISSUE TITLE
"1 failure" isn't as helpful as it could be

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#115513]
https://cirrus-ci.com/task/5355049111519232

I'm trying to understand what "1 failure" this customer testing run is reporting. Some script has decided that there was 1 failure but neglected to leave any clues about why that decision was made. I've looked through the voluminous output a few times and don't see anything obvious. No doubt the failure is noted in the log somewhere. When one error message is buried in nearly 5000 lines of log output, reading about it it would be more efficient if the failure message was dramatically highlighted in situ.

**Comment by godofredoc** [comment]
By any chance is this also failing in LUCI? Most likely related to https://github.com/flutter/flutter/issues/115476

**Comment by HansMuller** [comment]
They do seem to be related, although in this case the "1 failure" doesn't appear to correspond to anything in the logs.

**Comment by Hixie** [comment]
This unfortunately is too old and the logs have been culled. In general, this infrastructure has no owner so if you see a problem I encourage you to debug it directly. In this particular case, that probably means doing something similar to what `test.dart` does with collecting error messages and repeating them at the bottom when something has failed.
