### ISSUE TITLE
[iOS] Lag of UIView (GMSMapView) when reacting to events from a Channel in Flutter code (randomly varying over consecutive app launches)

### ISSUE THREAD

**Issue by vidklopcic** [flutter/flutter#115542]
Due to performance issues and the poor quality of the google_maps_flutter plugin, we decided to use the native implementation of Google Maps SDK. Flutter application is overlayed on top of it. Markers and other maps overlays are rendered in Flutter, so real-time synchronization of the native Google Maps view and Flutter overlay is crucial.

In our setup both, GoogleMaps and Flutter, receive the same touch events from the system. UiWindow subclass overrides the `sendEvents` method and manually forwards all touch events to the Flutter engine, so both views react to the same events.

#### AppDelegate.swift
```Swift
@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
    override func application(
        _ application: UIApplication,
        didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
    ) -> Bool {
        ...
        self.window = AppWindow()
        self.window?.rootViewController = GoogleMapsViewController()
        self.window?.makeKeyAndVisible()
        ....
    }
}

```

#### AppWindow.swift
```Swift
class AppWindow: UIWindow {
    override func sendEvent(_ event: UIEvent) {
        super.sendEvent(event)
        var controller = self.rootViewController as! GoogleMapsViewController
        controller.onInterceptedEvents(event)        
    }
}
```

#### GoogleMapsViewController.swift
```Swift
import UIKit
import GoogleMaps

class GoogleMapsViewController: UIViewController, GMSMapViewDelegate {
    ...
    override func viewDidAppear(_ animated: Bool) {        
        ...
        flutterViewController!.binaryMessenger.setMessageHandlerOnChannel("...") {
            (message: Data!, reply: FlutterBinaryReply) -> Void in
            ...
            self.targetCamera = GMSCameraUpdate.setCamera(GMSCameraPosition(target: CLLocationCoordinate2D(latitude: lat, longitude: lng), zoom: zoom, bearing: Double(rotation), viewingAngle: 0));
        }
    }
    
    func mapView(_ mapView: GMSMapView, didChange position: GMSCameraPosition) {
        ...
        flutterViewController!.binaryMessenger.send(onChannel: "...", message: Data(referencing: data))
    }
    
    ...
    
    func onInterceptedEvents(_ event: UIEvent) {
        let touches = event.allTouches!
        flutterViewController!.view.touchesBegan(touches.filter { $0.phase == .began }, with: event)
        flutterViewController!.view.touchesMoved(touches.filter { $0.phase == .moved }, with: event)
        flutterViewController!.view.touchesEnded(touches.filter { $0.phase == .ended }, with: event)
        flutterViewController!.view.touchesCancelled(touches.filter { $0.phase == .cancelled }, with: event)
    }
}
```

### The issue
Every few app launches, it works perfectly. However, most of the time, we observe extreme lag. My hypothesis is that it has to do with frame rendering synchronization. 

I have already tried:
- Wrapping the update code on the flutter side in a `WidgetsBinding.instance.scheduleFrameCallback`, which improved things considerably, but only if I added extra 1ms delay using `Future.delayed`. Even here, I get varying levels of "smoothness".
- Sending updates to the Flutter in a `DisplayLink` callback with various delays.

I want to find a way to consistently sync execution of the Flutter callback to get consistent results in consecutive app launches (or figure out if there is some other reason for this behavior).

#### "Lucky" launch:
https://user-images.githubusercontent.com/8578790/202403839-606c6648-6d06-4b61-a379-65289a269e4c.mp4

#### "Unlucky " launch:
https://user-images.githubusercontent.com/8578790/202403858-5226fca3-d007-4585-8046-6b5b4be735db.mp4

----
```
Flutter 3.3.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision d9111f6402 (4 weeks ago) • 2022-10-19 12:27:13 -0700
Engine • revision 3ad69d7be3
Tools • Dart 2.18.2 • DevTools 2.15.0
```

**Comment by exaby73** [comment]
Hello @vidklopcic. Can you provide a [complete and minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), ideally in the form a public repo that I can run directly to verify the issue?

**Comment by vidklopcic** [comment]
Thank you for takin the time to review the issue! Here is the example repo: [ios_native_gmaps_sync_lag_flutter_demo](https://github.com/vidklopcic/ios_native_gmaps_sync_lag_flutter_demo)

Here is a video showing the demonstration of the issue using the app from this repo: [VIDEO](https://photos.app.goo.gl/mvb1PYHKr3UkGMF18). When I launch the app at 00:18, there is considerably more lag than before. It is really random. Sometimes it works/doesn't for a few minutes and then it suddenly changes. Sometimes the only thing that "helps" is locking and unlocking the screen. 

It would be really helpful to know the root cause of this changing behavior, as it could point to some other inconsistency with the timings.

**Comment by vidklopcic** [comment]
I just tried the demo on iPhone 8 and couldn't reproduce the issue. It looks like it happens only on iOS devices with ProMotion (eg. iPhone 13 Pro Max, as shown in the video above).

**Comment by huycozy** [comment]
Hi @vidklopcic thanks for providing the sample code but as I see, there is a 3rd plugin `flutter_map`. 

For the issue to be workable, it needs to be reproducible with a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code. Please provide such a sample.

Thank you!

**Comment by vidklopcic** [comment]
I pushed another update to the repo. Now without flutter_map dependency. At the bottom I also added a configurable rendering delay (call to `setState`). Now the problem is quite evident - if the Flutter render call coincides with the native Google Maps view render time, either Flutter or Google Map start skipping frames (see the video).

https://user-images.githubusercontent.com/8578790/202690350-7fe81988-6059-4694-b9a6-9a413df6b854.MP4

Could I move Flutter rendeing to a separate thread, so it wouldn't block native iOS views from updating? There still remains the issue of synchronization - it looks like that on different app launches the delay must be a bit different to coincide with native render times.

**Comment by huycozy** [comment]
Hi @vidklopcic, thanks for updating sample code. But I got a crash while running it.

```
Errors found! Invalidating cache...
2
Runner/AppDelegate.swift:69: Fatal error: Unexpectedly found nil while unwrapping an Optional value
* thread #1, queue = 'com.apple.main-thread', stop reason = Fatal error: Unexpectedly found nil while unwrapping an Optional value
    frame #0: 0x0000000185829ebc libswiftCore.dylib`_swift_runtime_on_report
libswiftCore.dylib`:
->  0x185829ebc <+0>: ret
libswiftCore.dylib`:
    0x185829ec0 <+0>: b      0x185829ebc               ; _swift_runtime_on_report
libswiftCore.dylib`:
    0x185829ec4 <+0>: adrp   x8, 465364
    0x185829ec8 <+4>: ldrb   w0, [x8, #0x2cc]
Target 0: (Runner) stopped.
```
it seems to come from implementation. Please try to solve it and update sample code if possible.

**Comment by vidklopcic** [comment]
It was a similar issue than outlined here: https://github.com/flutter/engine/pull/35592 - routed touch events were lagging compared to the rendered UIView. That's also why I couldn't observe the lag on devices without ProMotion.
