### ISSUE TITLE
nullable field in _HasWidgetLocation._location could be null

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#115582]
Per discussion with @johnniwinther, the field `_HasWidgetLocation._location` which is marked non-nullable could be nullable, for example in the case where a tear-off constructor is used, the invocation point could not be determined: https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/widget_inspector.dart#L3245.

This field should be updated to be nullable.

**Comment by goderbauer** [comment]
cc @kenzieschmoll
