### ISSUE TITLE
Unnecessary comparison with `double.nan` (2)

### ISSUE THREAD

**Issue by asashour** [flutter/flutter#115546]
Similar to #115468, there is

https://github.com/flutter/flutter/blob/7e8568be3f583139a1b9ca9d6350a3ad21e420bb/packages/flutter_test/lib/src/accessibility.dart#L600

which prevents landing of a CL for a new Dart SDK hint.

This wasn't previously detected, as I didn't know the [error log](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8797381496086398737/+/u/analyze_flutter_flutter/stdout) location.

Thanks.

**Comment by exaby73** [comment]
Hello @asashour. Thank you for filing this issue. Labeling for further insights from the team
