### ISSUE TITLE
Dart engprod needs access to gs://flutter_archives_v2

### ISSUE THREAD

**Issue by whesse** [flutter/flutter#115558]
I ran into a problem when developing the engine_v2/tester recipe for monorepo.

The Flutter engine artifacts uploaded to flutter_archives_v2 by the engine_v2 builders included a new artifact
```
  bin/internal/material_fonts.version:flutter_infra_release/flutter/fonts/3012db47f3130e62f7cc0beabff968a33cbec8d8/fonts.zip
```
I needed to copy this to the monorepo storage path,
```
  monorepo/flutter_infra_release/flutter/fonts/3012db47f3130e62f7cc0beabff968a33cbec8d8/fonts.zip
```

but only the service account that the monorepo builders use had write access to the bucket.  We have also locked
down our cloud project enough that I could not impersonate that account.

If the Flutter engprod team has access to this bucket, or individuals working on engine_v2 have access to the bucket, could
I also be given access to this bucket?

An additional request, inspired by the root cause of this need, would be to find out what builder is writing this material fonts zip file, or if it was uploaded by hand, customly.  A good way to solve this would be a document listing the layout of the flutter build archives uploaded by flutter, with each directory giving the name of the builder that is responsible for creating and uploading that file.  There are many paths in an engine upload, and no way to find out what is the source of a particular file.

**Comment by whesse** [comment]
A new example of the flutter_archives_v2 bucket not keeping up with needed artifacts is that the cipd download of web-canvaskit_bundle.zip advanced to a new tag, and this new file was not copied to either flutter_archives_v2 or flutter_archives_v2/monorepo.  To start using this bucket for CI testing, we need to automate the workflow for these special-case file uploads.

**Comment by godofredoc** [comment]
@drewroengoogle can you please grant dart-engprod temporary write access to flutter_archives_v2?

@whesse let's sync up about this next week, there are many details we need to figure out to archive artifacts for testing correctly.

**Comment by drewroengoogle** [comment]
I've granted dart-engprod the ability to request write access to flutter_archives_v2 internally by requesting to join flutter-infra-gcp-writers

**Comment by whesse** [comment]
The cipd download of web-canvaskit_bundle.zip advanced to cipd hash

61aeJQ9laGfEFF_Vlc_u0MCkqB6xb2hAYHRBxKH-Uw4C

In the future, downloads should not be needed because the bundle will be in the build web sdk. It may already be the case, and only the monorepo and possibly engine_v2 builds still need it.

I am exercising the on-demand access grant to copy the bundle from cipd to
gs://flutter_archives_v2/flutter_infra_release/cipd/flutter/web/canvaskit_bundle/+/61aeJQ9laGfEFF_Vlc_u0MCkqB6xb2hAYHRBxKH-Uw4C
and
gs://flutter_archives_v2/monorepo/flutter_infra_release/cipd/flutter/web/canvaskit_bundle/+/61aeJQ9laGfEFF_Vlc_u0MCkqB6xb2hAYHRBxKH-Uw4C

Will close this issue after success.

**Comment by whesse** [comment]
The copy went through by running the gsutil copy command on a test builder using led.
The access grant is no longer needed, but the process to request one has now been tested.

Closing the issue.
