### ISSUE TITLE
[Impeller] Allow coalescing small texture uploads just like buffers.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#115583]
Impeller avoids discrete device buffer allocations and uploads for small uniform (and SSBO) data. This comes in handy in case of the jumbo UBO scheme. However, there are some cases (for instance, when there are no SSBOs) where the same scheme for small textures can come in handy. Add a similar mechanism for small texture atlases per pass that can be built up automatically and uploaded in one shot.

Related to https://github.com/flutter/engine/pull/37654 and will be necessary for the legacy backend fix for https://github.com/flutter/flutter/issues/115208

**Comment by chinmaygarde** [comment]
cc @jonahwilliams @dnfield @bdero

**Comment by chinmaygarde** [comment]
I added this to the Android milestone since we won't be able to use SSBOs on Android with the ES backend.

**Comment by jonahwilliams** [comment]
The uploads are effectively coallesed now that we've made Hostbuffers backed by real device buffers. I don't think that will actually make creating hundreds of textures per frame fast though
