### ISSUE TITLE
[Camera] Bluetooth Audio Switched Off After Going into Camera

### ISSUE THREAD

**Issue by mingzew** [flutter/flutter#115536]
## Steps to Reproduce

1. build a project with bluetooth, camera, mic on ios. It also uses camera and video_player package
2. connect your bluetooth headphone to the device and play the a video using video_player. You should hear the sound from headphone
3. go open up camera for recording with audio recording, await for controller to initialize
4. go back to the video page, play the video again

**Expected results:** audio playing through bluetooth
**Actual results:** audio no longer goes to bluetooth headphone, it plays on device's built in speaker

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

[✓] Flutter (Channel stable, 3.0.3, on macOS 11.4 20F71 darwin-x64, locale en-US)
    • Flutter version 3.0.3 at /Users/admin/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 676cefaaff (5 months ago), 2022-06-22 11:34:49 -0700
    • Engine revision ffe7b86a1e
    • Dart version 2.17.5
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/admin/Library/Android/sdk
    • Platform android-33, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Community Edition (version 2021.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.73.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] VS Code (version 1.62.3)
    • VS Code at /Users/admin/Downloads/Visual Studio Code-1.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] VS Code (version 1.55.2)
    • VS Code at /Users/admin/Downloads/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • iphone (mobile) • 00008020-001259B63E61082E • ios            • iOS 15.3.1 19D52
    • macOS (desktop)       • macos                     • darwin-x64     • macOS 11.4 20F71 darwin-x64
    • Chrome (web)          • chrome                    • web-javascript • Google Chrome 107.0.5304.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```
```

</details>

**Comment by darshankawar** [comment]
@mingzew 
Thanks for the report. Can you confirm if this behavior also occurs in non-Flutter app ? Example, a native iOS app ?
If not, can you provide a complete minimal code sample along with `flutter doctor -v` and plugin versions you are using so that we can address it properly ?
