### ISSUE TITLE
Execution failed for task ':image_picker_android:verifyReleaseResources'.

### ISSUE THREAD

**Issue by RuberDucky** [flutter/flutter#115539]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':image_picker_android:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
   > Android resource linking failed
     ERROR:C:\Users\Lunix\.gradle\caches\transforms-3\0ce731f8c62e88af9af421907435d7da\transformed\core-1.8.0\res\values\values.xml:104:5-113:25: AAPT: error: resource 
android:attr/lStar not found.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

```
BUILD FAILED in 2m 35s
Running Gradle task 'assembleRelease'...                          157.2s
Exception: Gradle task assembleRelease failed with exit code 1
#0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
#1      AndroidGradleBuilder.buildGradleApp (package:flutter_tools/src/android/gradle.dart:406:9)
<asynchronous suspension>
#2      AndroidGradleBuilder.buildApk (package:flutter_tools/src/android/gradle.dart:184:5)
<asynchronous suspension>
#3      AndroidDevice.startApp (package:flutter_tools/src/android/android_device.dart:577:7)
<asynchronous suspension>
#4      FlutterDevice.runCold (package:flutter_tools/src/resident_runner.dart:505:33)
<asynchronous suspension>
#5      ColdRunner.run (package:flutter_tools/src/run_cold.dart:71:28)
<asynchronous suspension>
#6      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:692:26)
<asynchronous suspension>
#7      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1183:27)
<asynchronous suspension>
#8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#9      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#10     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
<asynchronous suspension>
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
<asynchronous suspension>
#13     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#15     main (package:flutter_tools/executable.dart:94:3)
<asynchronous suspension>
```

**Comment by exaby73** [comment]
Hello @RuberDucky. Thank you for filing this issue. Can you please provide the following information?

- A [complete and minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). Ideally, a single `main.dart` file that can be run directly.
- The output of `flutter doctor -v`
- The output of `flutter run -v`

Please provide the information in the form of text. See how to make collapsible sections with Markdown [here](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-collapsed-sections).

**Comment by darshankawar** [comment]
> ERROR:C:\Users\Lunix.gradle\caches\transforms-3\0ce731f8c62e88af9af421907435d7da\transformed\core-1.8.0\res\values\values.xml:104:5-113:25: AAPT: error: resource
> android:attr/lStar not found.

This probably indicates a gradle cache issue, so please try to clear it followed by `flutter clean` and also try to upgrade your framework version to latest and see if it helps.

**Comment by RuberDucky** [comment]
i did but still facing this in the release mode

**Comment by exaby73** [comment]
I found a similar issue on Medium with a solution. Can you try it and see if it works for you?

https://flutter-developer.medium.com/flutter-error-resource-android-attr-lstar-not-found-solved-1f9aa783e7e9

**Comment by RuberDucky** [comment]
* What went wrong:
Execution failed for task ':image_picker_android:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
   > Android resource linking failed
     ERROR:C:\Users\Lunix\.gradle\caches\transforms-3\0ce731f8c62e88af9af421907435d7da\transformed\core-1.8.0\res\values\values.xml:104:5-113:25: AAPT: error: resource android:attr/lStar not found.

**Comment by exaby73** [comment]
Could you provide more context on [this comment](https://github.com/flutter/flutter/issues/115539#issuecomment-1322041809)? Are these the same error logs that you had before, or is it after you allied the fix mentioned in https://github.com/flutter/flutter/issues/115539#issuecomment-1321768960?

**Comment by RuberDucky** [comment]
I tried but still got the same error!

**Comment by RuberDucky** [comment]
it's alright now I added this code android/build:Gradle I changed the sub-project to this.

subprojects {
    afterEvaluate {project ->
        if (project.hasProperty("android")) {
            android {
                compileSdkVersion 33
                buildToolsVersion "28.0.3" 
            }
        }
    }
}
