### ISSUE TITLE
[conductor] Skip tagging versions if the tag and sha match

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#115579]
The release tooling is spread across several workflows. Conductor should check if a tag needs to be applied at all.

1. Roll tooling had created 3.6.0-0.0.pre, and it should have created 3.6.0-0.1.pre instead.
2. If we ever re-use an original roll tag (no CPs), conductor should not set the tag again

**Comment by CaseyHillers** [comment]
\cc @itsjustkevin @muditatandon

**Comment by itsjustkevin** [comment]
Do we want to upsert the tag or keep the original tag point in cases where we are not hotfixing from the original branch point?

**Comment by XilaiZhang** [comment]
tagging now happens on recipe
