### ISSUE TITLE
Flutter Plugins tree is yellow indefinitely due to repeating mac tests

### ISSUE THREAD

**Issue by tarrinneal** [flutter/flutter#115534]
The latest merged commit on the Flutter Plugins repo is locking down the tree due to macos tests that are repeating indefinitely. The tests have been going for almost 3 days now. If you look for more info, it always states the tests started in the last 10 minutes.

https://github.com/flutter/plugins/commit/e500884c758c2d516baf7d5ab30639c81dd6b849

@keyonghan at request of @stuartmorgan

**Comment by keyonghan** [comment]
A cocoon fix has been submitted: https://github.com/flutter/cocoon/pull/2303. 
A new commit should green the tree. This one is ready to land: https://github.com/flutter/plugins/pull/6711. Is it safe for me to manually submit the PR?

**Comment by stuartmorgan** [comment]
If landing another commit is expected to green the tree, please do :)

**Comment by keyonghan** [comment]
Tree is open.
