### ISSUE TITLE
Impeller issues with SnapshotWidget / toImageSync

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#115580]
I'm seeing a couple of issues with `SnapshotWidget` and/or `toImageSync` under Impeller.

First, text is sometimes mangled in the image coming from `toImageSync`:

![43716E77-A97B-4BFD-A61A-8073191B9A76](https://user-images.githubusercontent.com/6343103/202526643-d5f4ccc0-385c-49ff-940a-fbccd6c193d3.PNG)

I've only been able to repro this on iOS hardware. 

Second, using the result of `toImageSync`, specifically in the `SnapshotWidget`, as a sampler in a shader, gives all black.

Sorry for the large repro, but here is my fork of flutter/gallery.

https://github.com/zanderso/gallery/commits/impeller-tis-issue

The live implementation of `snapshotPainter` in there just draws the provided image to the canvas. The commented out code in `snapshotPainter` uses the custom shader.

@jonahwilliams @bdero @dnfield

**Comment by jonahwilliams** [comment]
> Second, using the result of toImageSync, specifically in the SnapshotWidget, as a sampler in a shader, gives all black.

I've seen this too, but I don't think its the sampler - I've seen uniforms get re-arranged in unexpected ways. See also: https://github.com/flutter/engine/pull/37573

You might try hard-coding an approximate size to see if the sampler is working correctly independent of the other uniforms

**Comment by zanderso** [comment]
Could the issue be with how I'm drawing on the canvas?
```dart
    context.canvas.drawRect(
      offset & size,
      Paint()..shader = fragmentShader,
    );
```

I ask because when I modified the shader to ignore the sampler, and just return red with animating opacity, I still got a black screen.

**Comment by jonahwilliams** [comment]
otherwise your rect will end up shifted weird

**Comment by zanderso** [comment]
Rolling up to include the revert [here](https://github.com/flutter/engine/pull/37720) fix the second issue. Seeing if it also covered the first issue.

**Comment by zanderso** [comment]
The problem with text is still present after the revert. It looks like maybe `toImageSync` is seeing a stale glyph atlas?
