### ISSUE TITLE
i have downloaded and cloned dicee application but while running in my android studio it shows your project is creat3ed with older version of android embedding how to resolve it

### ISSUE THREAD

**Issue by Devendiran2612** [flutter/flutter#115527]
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by Devendiran2612** [comment]
Your Flutter application is created using an older version of the Android
embedding. It is being deprecated in favor of Android embedding v2. Follow the
steps at

https://flutter.dev/go/android-project-migration

to migrate your project. You may also pass the --ignore-deprecation flag to
ignore this check and continue with the deprecated v1 embedding. However,
the v1 Android embedding will be removed in future versions of Flutter.

**Comment by huycozy** [comment]
@Devendiran2612 
Please see this StackOverflow answer for more details: https://stackoverflow.com/questions/64425132/how-to-fix-flutter-warning-your-flutter-application-is-created-using-an-older-v

Closing as this is neither a bug nor a feature request.
