### ISSUE TITLE
[CP] Fix app crash happening in accessibility_bridge UIView access 

### ISSUE THREAD

**Issue by cog-iagentur** [flutter/flutter#115650]
### issue_link

https://github.com/flutter/flutter/issues/112545

### Commit Hash

271705d

### Target

stable

### pr_link

https://github.com/flutter/engine/pull/36580

### Impacted Users

iOS users

### Impact Description

App crash on production app. Wasn't able to reproduce ourselves but have a sizeable amount of crash logs.

### Workaround

Haven't found.

### Risk

low

### Test Coverage

yes

**Comment by itsjustkevin** [comment]
Do you have any more info on the issues you are seeing?

**Comment by Mellobrainbox** [comment]
Yes

**Comment by cog-iagentur** [comment]
Unfortunately, I don't have more information beside what has been already given in [#112545](https://github.com/flutter/flutter/issues/112545). Just that there has been noticeable amount of crashes because of this issue in our app.

**Comment by siddew201** [comment]
Hi can anyone suggest when this cp will be merged and we can have updated sdk. Actually we are facing many crashes in production. Any update will be appreciated. Thanks

**Comment by itsjustkevin** [comment]
@jmagman could you take a look at this cherry-pick request?

**Comment by siddew201** [comment]
@itsjustkevin as per @jmagman comment is there any stable hotfix build is in flight? If it is can we have this CV in that build?

**Comment by siddew201** [comment]
@XilaiZhang  I got notification that Flutter stable 3.3.10 has been released. Does this CP is available in this release. So that we can update and can check whether this crash has been resolved. Thanks

**Comment by XilaiZhang** [comment]
not this week. The cheerypick pr was merged into main branch but was not merged into the release branch.

**Comment by siddew201** [comment]
thanks for confirmation @XilaiZhang. How much time still we can expect to go this CP in release from your side. Any tentative date will work. Actually we are facing severe amount of crash due to this issue. Thanks

**Comment by XilaiZhang** [comment]
umm that is unfortunate. I think there is going to be a code freeze during the holidays which could add on to the delay. very likely going to be after January

**Comment by siddew201** [comment]
Okay fine. I request u to please consider this CP for whatever next release u guys are going to do. If there any possibility of any release before holiday that will be great but if not please take this on priority for next hotfix release. Thanks

**Comment by siddew201** [comment]
@XilaiZhang I guess In Jan you guys will come with new release. I request you to please consider this CP as priority as we are getting severe amount of crash due to this bug. Thanks

**Comment by CaseyHillers** [comment]
This CP request is missing a PR open against the stable branch. @cog-iagentur can you open a PR so it can be reviewed?

**Comment by cog-iagentur** [comment]
Can you help with this @jmagman? I am bit confused about the process here.

**Comment by jmagman** [comment]
Note to @itsjustkevin the cherry pick process docs don't say much about what to branch off for these CP PRs:

> TPM/Developer will create PR into the vX.Y.Z branch
> for Dart, this will be the beta branch until the vX.Y.Z branch support or similar is built.
> If pre-submit tests fail, a risk assessment will need to be performed with input from the cherrypick reviewers.

What's would be the engine stable candidate commit to branch off?

The fix https://github.com/flutter/engine/commit/271705dfb1a214037daff4c1e34c57271789dded is available in Flutter 3.5.0-1.0.pre.  Even though this is low-ish risk I don't think it's worth taking at this point, it's available in beta and will be in the next stable.

I'm going to close this.

**Comment by siddew201** [comment]
@jmagman we are following up for this issue since last few months and as per discussion here we were in hope to get this fix in coming hotfix releases. We are getting severe crashes due to this issue that is leaving bad impact on users. Current version is I guess 3.310 and Flutter 3.5.0-1.0.pre seems to far for release. 

Kindly look into this CP and please try to release this asap. This will great help for us. Thanks

**Comment by jmagman** [comment]
> Current version is I guess 3.310 and Flutter 3.5.0-1.0.pre seems to far for release.

The last stable version released 3.3, our minor versions are confusing.  I suggest trying the most recent beta channel ([currently 3.7.0-1.4.pre](https://docs.flutter.dev/development/tools/sdk/releases?tab=macos)) which is still within one stable version of 3.3.

**Comment by siddew201** [comment]
@jmagman I have few questions
- is this issue fixed in your recent beta channel (([currently 3.7.0-1.4.pre](https://docs.flutter.dev/development/tools/sdk/releases?tab=macos))) 
- can we use beta version in our production build?
- How much time we can expect to get this fix in your stable channel.

I hope you really understand that this issue is impacting our application very badly thats why we are following up this much. Thanks

**Comment by jmagman** [comment]
> * is this issue fixed in your recent beta channel (([currently 3.7.0-1.4.pre](https://docs.flutter.dev/development/tools/sdk/releases?tab=macos)))

Yes, it is available in any release after 3.5.0-1.0.pre, which includes 3.7.0-1.4.pre.

> * can we use beta version in our production build?

You would switch your local Flutter SDK to the `beta` channel. https://github.com/flutter/flutter/wiki/Flutter-build-release-channels#beta

> * How much time we can expect to get this fix in your stable channel.

It will be in the next stable version.  I can't speak to the timing specifically, but that should be released soon.

> I hope you really understand that this issue is impacting our application very badly thats why we are following up this much. Thanks

Definitely, I understand this is painful.  As https://github.com/flutter/flutter/wiki/Flutter-build-release-channels#will-a-particular-bug-fix-be-provided-in-a-hotfix-release points out, Flutter is distributed as a git repository, you can also locally cherry-pick any commit you want into your Flutter SDK.

**Comment by siddew201** [comment]
@jmagman can you please confirm that is this fix  available in latest stable release 3.7.0 or not.

**Comment by siddew201** [comment]
@jmagman @XilaiZhang can someone update if this fix is available in latest release?

**Comment by jmagman** [comment]
Yes, it is available in 3.7.  It was available in 3.5.0-1.0.pre, which includes 3.7.0.
https://github.com/flutter/flutter/wiki/Where's-my-Commit%3F#finding-the-framework-commit-that-contains-engine-commit-x
https://github.com/flutter/engine/commit/271705dfb1a214037daff4c1e34c57271789dded
https://github.com/flutter/flutter/commit/145904f6410dc0611db89c6554b022a9c1204dc8
