### ISSUE TITLE
[web]: <describe issue here>

### ISSUE THREAD

**Issue by radtymm** [flutter/flutter#115688]
执行flutter build web --web-renderer html 打包生成的flutter.js，flutter_service_worker.js是es6的写法，在部分浏览器里不兼容，是否支持转义成es5写法，或者支持自己修改编译的配置呢

**Comment by huycozy** [comment]
>执行flutter build web --web-renderer html 打包生成的flutter.js，flutter_service_worker.js是es6的写法，在部分浏览器里不兼容，是否支持转义成es5写法，或者支持自己修改编译的配置呢

**(Using Google translate):** 
_"Execute flutter build web --web-renderer html to package and generate flutter.js, flutter_service_worker.js is written in es6, which is incompatible in some browsers. Do you support escaping into es5 writing, or support yourself modifying the compiled configuration?"_

@radtymm Thanks for the report! This is a known issue being tracked at #95401. Closing this issue as a duplicate, so please follow up on it for further updates.
