### ISSUE TITLE
Dart Docs for Plugins don't focus on what's relevant

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#11563]
From pub.dartlang.org, when I click on the "Documentation" link for a Flutter plugin I am taken to a Dart Doc side that doesn't really focus on the plugin. Instead, it includes the documentation for a whole bunch of dart core libraries and and it also puts those docs before the relevant docs of the plugin's library. I actually have to look closely to find the docs relevant to the plugin.

When I go to a plugin's documentation, I am mainly interested in the functionality the plugin offers. Including the documentation for dart core libraries seems out of place.

Examples:
https://www.dartdocs.org/documentation/firebase_database/0.0.14/
https://www.dartdocs.org/documentation/image_picker/0.1.1/

Other non-Flutter packages don't seem to include the core libs in their dart docs, e.g. 
https://www.dartdocs.org/documentation/sentry_client/4.0.1/

/cc @mit-mit @sethladd

**Comment by mit-mit** [comment]
@danrubel is this the underlying analysis issue you are working on, or a dartdoc issue?

**Comment by danrubel** [comment]
I'm working on https://github.com/flutter/flutter/issues/10721

**Comment by mit-mit** [comment]
Do you know if that will address the present issue?

**Comment by danrubel** [comment]
I don't think so.

**Comment by mit-mit** [comment]
@jcollins-g do you think this is a dartdoc issue? How are core libs excluded for non-Flutter packages?

**Comment by jcollins-g** [comment]
https://github.com/dart-lang/dartdoc/issues/1431

**Comment by mit-mit** [comment]
Thanks @jcollins-g for helping my dusty memory here after vacation :-). Will push on getting that workaround deployed (https://github.com/astashov/dartdocs.org/pull/48)

**Comment by mit-mit** [comment]
I believe this has been resolved, see e.g. https://www.dartdocs.org/documentation/image_picker/0.1.3/index.html
