### ISSUE TITLE
firebase-get-to-know-flutter/step_06 needs to dispose pf the textEditingController

### ISSUE THREAD

**Issue by graemep-nz** [flutter/flutter#115693]
In this codelab, there needs to be a call to dispose of the textEditingController
https://firebase.google.com/codelabs/firebase-get-to-know-flutter#6

https://github.com/flutter/codelabs/blob/main/firebase-get-to-know-flutter/step_06/lib/main.dart

class _GuestBookState extends State<GuestBook> {
  final _formKey = GlobalKey<FormState>(debugLabel: '_GuestBookState');
  final _controller = TextEditingController();

**Comment by domesticmouse** [comment]
PTAL @ericwindmill

**Comment by domesticmouse** [comment]
PTAL @ericwindmill

**Comment by domesticmouse** [comment]
PTAL @ericwindmill

**Comment by ericwindmill** [comment]
Fixed by https://github.com/flutter/codelabs/pull/2256
