### ISSUE TITLE
How to close/kill the app after every test in flutter integration test?

### ISSUE THREAD

**Issue by jagadeeshpurplle** [flutter/flutter#115630]
Hi Team,

I'm using flutter integration driver to write integration tests for my mobile flutter app.

Below is the sample code of writing multiple `testWidgets` in a single `app_test.dart` file, after completion of first test execution i see the app directly opening from home screen and not from fresh app install. `Is this expected?`

I'm expecting it to open from fresh state where i can login again & proceed further.

Is there way to uninstall the app or kill the app after executing the first test case, so that my test execution always starts from fresh app open.

```
void main() {
  IntegrationTestWidgetsFlutterBinding.ensureInitialized();

  group('regression test suite', () {

    tearDown(() async {
      final getIt = GetIt.instance;
      await getIt.reset();
    });

    testWidgets('sample test', (tester) async {
      app.main();
      SLogger.i('App opened');
      await tester.pumpAndSettle(const Duration(seconds: 5));

      await tester.tap(find.byKey(const ValueKey('startButton')));
      await tester.pumpAndSettle();
      expect(find.text('Home Screen'), findsOneWidget);
      expect(find.text('Transactions'), findsOneWidget);
    });

    testWidgets('check value increments and data', (tester) async {
      app.main();
      await tester.pumpAndSettle(const Duration(seconds: 5));

      expect(find.text('Home Screen'), findsOneWidget);
      expect(find.text('Transactions'), findsOneWidget);

      await tester.tap(find.byTooltip('settingsTab'));
      await tester.pumpAndSettle();
    });
  });
}
```
Any helps?

**Comment by darshankawar** [comment]
> after completion of first test execution i see the app directly opening from home screen and not from fresh app install. `Is this expected?`

Yes, this is expected. The tests will continue to run and execute the next test.





> Is there way to uninstall the app or kill the app after executing the first test case, so that my test execution always starts from fresh app open.

I am not sure if there's an inbuilt method provided by `integration_test` that does this, or even if it is possible or not. I suggest you to reach out on support channels like StackOverflow for your questions.

Closing from here.
