### ISSUE TITLE
Bigger main.dart.js than expected on flutter web using freezed.

### ISSUE THREAD

**Issue by Pacane** [flutter/flutter#115669]
We're currently using Flutter 3.3.4 and we're having some issues with generated code size, specifically for flutter web.

The current size of our `main.dart.js` file is around 9MB (2.3MB with gzip), built with `flutter build web --release`

One interesting thing I've noticed, is that we're heavily using the package `freezed` (^2.2.0 currently).  I'm not sure whether I should open issues in the freezed repo or dart-sdk or flutter, since to me, it looks like there could be further optimizations with dart2js on this.

I do see a lot of code looking like this in the `main.dart.js`

```
$16$setEmail$setError$setFirstName$setGender$setLastName$setLoading$setMiddleName$setOrganisationId$setPassword$setPasswordRepeat$setProfessionId$setProfessionSince$setRecoveryCode$setSecurityAnswer$setTitle$setWorkplaceId(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p){return this.a.$16$setEmail$setError$setFirstName$setGender$setLastName$setLoading$setMiddleName$setOrganisationId$setPassword$setPasswordRepeat$setProfessionId$setProfessionSince$setRecoveryCode$setSecurityAnswer$setTitle$setWorkplaceId(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p)},
```

for all our classes generated with freezed. As you can see, the names aren't minimized/obfuscated much.

After some brief analysis of the generated code, I do see some occurrences of these pragma instructions

```
class __$$_SetSecurityAnswerCopyWithImpl<$Res>
    extends _$CreateProfileEventCopyWithImpl<$Res, _$_SetSecurityAnswer>
    implements _$$_SetSecurityAnswerCopyWith<$Res> {
  __$$_SetSecurityAnswerCopyWithImpl(
      _$_SetSecurityAnswer _value, $Res Function(_$_SetSecurityAnswer) _then)
      : super(_value, _then);

  @pragma('vm:prefer-inline')
  @override
  $Res call({
    Object? securityAnswer = null,
  }) {
    return _then(_$_SetSecurityAnswer(
      securityAnswer: null == securityAnswer
          ? _value.securityAnswer
          : securityAnswer // ignore: cast_nullable_to_non_nullable
              as String,
    ));
  }
}
```

I imagine those `vm:prefer-inline` pragma instructions aren't used for web? I don't even know if these are relevant to be honest.

I'm looking for potential advice on what to do here, or what else I should be looking for. Could there be a missing compilation switch on our end?

Also, I know the answer is most likely going to be "it depends" and pretty variable, but do you have a ballpark expected size (of main.dart.js) for a medium-big sized flutter web app? Am I scraping too much for performance, or is there something definitely wrong here?

cc: @kevmoo

**Comment by Pacane** [comment]
After doing some tests locally with shelf_gzip, I figured we didn't enable gzip on our production site 🤦. Turns out our main.dart.js is around 2.3MB now. Which is much more acceptable IMO.

**Comment by kevmoo** [comment]
Here's an idea. Take a look at https://developer.chrome.com/docs/devtools/coverage/

Try to use...a LOT of your app in one session. And see how much of the compiled output is hit.

Just curious...

**Comment by Pacane** [comment]
After playing with my app for a few hours, trying to hit most code paths, the coverage tool settled around 40% unused code. I could probably shave around 5-8% if I really dig deeper I feel like, but so far I haven't been able to do that.

**Comment by kevmoo** [comment]
That's good context. Our JS tree shaking algorithm can only be so aggressive, while also being conservative.

Have you enabled https://dart-lang.github.io/linter/lints/avoid_dynamic_calls.html on your code? (Don't go TOO crazy with it if you have a lot of failures. But it might be interesting to do a before/after comparison after fixing 10-20...if you have any)

**Comment by Pacane** [comment]
Yes we've enabled that.

**Comment by kevmoo** [comment]
To investigate:

1. easy way to drop pkg:intl languages that are not used
2. The weird long strings showing up in the app (pkg:freezed?)

**Comment by kevmoo** [comment]
@Pacane – can you reproduce the `freezd` thing w/ a minimal repro?

**Comment by Pacane** [comment]
So far the best I've been able to come up with was [this](https://github.com/Pacane/freezed_dart2js_repro)

I've added a symlink to build/main.dart.js in the root of the repo just so you can see it.

Turns out as you mentioned in our other discussion, we do save a bit of space by removing the toString() override feature from freezed.

Now I still see some occurrences of method names/parameters not being minimized. I suspect it is because of the way dart2js does its thing with named parameters.

In our code base we do tend to mix bloc with freezed a lot. (Representing the bloc state with a freezed DTO class, bloc events with a freezed union type).

Freezed does generate `when` and `map` methods, with the actual event names. I'm thinking this is why we're seeing non-minified names in there. Would that make sense?

**Comment by yjbanov** [comment]
There's not much we can do on the Flutter side. This issue is better suited for either Dart SDK or freezed.
