### ISSUE TITLE
[pigeon] Comments starting with `////` break compilation of generated code using C++-style blocks

### ISSUE THREAD

**Issue by marynovskyi** [flutter/flutter#115657]
After updating pigeon from 3.2.3 to 4.2.5 I'm getting error because pigeon parses comments from initial file (which is used to generate the code for Dart, Java, ObjC from). 

If I have a comment in code like this:

`///////////////////////////////////////////////////////////////////////////////
// Comment
///////////////////////////////////////////////////////////////////////////////

class SomeStuff {
}`

it results in this for Java:

`/**
   *////////////////////////////////////////////////////////////////////////////
   *////////////////////////////////////////////////////////////////////////////
   *
   * Generated class from Pigeon that represents data sent in messages.
   */
  public static class SomeStuff {
  }`

As you can see, two longs lines are being parsed for some reason and breaks the code formatting which doesn't allow to compile the project

**Comment by stuartmorgan** [comment]
> As you can see, two longs lines are being parsed for some reason

`///` is the Dart standard for doc comments, and Pigeon now carries doc comments over into generated files to make the APIs easier to consume in native code.

We'll need to add special handling when the first character of a doc comment is `/` when generating C++-style comment blocks.
