### ISSUE TITLE
iOS builds don't get app version from pubspec.yaml

### ISSUE THREAD

**Issue by JCKodel** [flutter/flutter#115670]
## Steps to Reproduce

1. Create a project with iOS support
2. Open XCode project

<img width="363" alt="image" src="https://user-images.githubusercontent.com/379339/202812838-4695da0b-f34a-4f25-89a3-e9a4860de61e.png">

Version is blank.

After altering Runner.xcodeproj/project.pbxproj from:

```
CURRENT_PROJECT_VERSION = "$(FLUTTER_BUILD_NUMBER)";
```

to

```
CURRENT_PROJECT_VERSION = "$(FLUTTER_BUILD_NUMBER)";
MARKETING_VERSION = "$(FLUTTER_BUILD_NAME)";
```

(in multiple locations), then it works:

<img width="352" alt="image" src="https://user-images.githubusercontent.com/379339/202813058-483834c1-8bc2-4399-9404-09e4b101b71d.png">

(Display Name is blank as well, but I couldn't figure out how to fix it).

## Details

* Flutter 3.3.7 stable
* XCode 14.1 (14B47b)
* MacOS Ventura 13.0.1

**Comment by arnirichard** [comment]
Can confirm this. I always run flutter build ios before xcode build to update the version number.

**Comment by exaby73** [comment]
Hello @JCKodel. Could you confirm which version of Flutter do you last remember it working as expected so that I may compare the differences?

**Comment by JCKodel** [comment]
> Hello @JCKodel. Could you confirm which version of Flutter do you last remember it working as expected so that I may compare the differences?

I'm not sure. I think 3.0

**Comment by exaby73** [comment]
I checked on 3.0.0, and also went as far back as 2.10.5. This is working as before. The build version is injected at build time, if I am not mistaken. After installing the app, the version should be correct as defined in your `pubspec.yaml`.

**Comment by arnirichard** [comment]
Just want to clarify, when archive a project in xcode the version is not taken from pubspec.yaml, I need to run flutter build ios first.
