### ISSUE TITLE
Multipart Request not waiting for response 

### ISSUE THREAD

**Issue by utkudenis** [flutter/flutter#115673]
Hi Flutter, 

I updated  my flutter project 3.0.5 to 3.3.8 but I have a problem, 
http package is 0.13.5 

code in the below do not wait to fulfill res. I checked response and it is returning 'file_name' but ı always get same value which is in the initilization on the res "", 

I didn't have any problem before the flutter upgrade.

![image](https://user-images.githubusercontent.com/68633376/202815249-bb8e87fe-b111-4c84-a860-edf9b8a2188f.png)

**Comment by utkudenis** [comment]
when ı add await, it is working fine, but also dart gives info error like 
![image](https://user-images.githubusercontent.com/68633376/202815806-12bcbe55-bf9e-4960-80e4-ff087d0b2b85.png)

![image](https://user-images.githubusercontent.com/68633376/202815769-92c5a406-3795-4502-96c6-21a4eedfbfa7.png)

**Comment by utkudenis** [comment]
what did you change? if there is an await on the upper lower function, dart was waiting for it but now, it is not waiting :(

**Comment by utkudenis** [comment]
I'm waiting your response @darshankawar

**Comment by asashour** [comment]
It is suggested to edit the question and put the code as text, not an image. And a [minimal-reproducible-example](https://stackoverflow.com/help/minimal-reproducible-example) is provided.

I also trust that the team would tackle the issues, without the need to cc specific persons, who may be not reachable, for whatever reason.

**Comment by huycozy** [comment]
Hi @utkudenis. 

Please open the issue in the [http repository](https://github.com/dart-lang/http/issues) for better support there. Closing, as this isn't an issue with Flutter itself. If you disagree, kindly leave a comment below and I will reopen it. 

Thank you!
