### ISSUE TITLE
Flutter HTTP server - serve Flutter web app 

### ISSUE THREAD

**Issue by TedCermitech** [flutter/flutter#115645]
I have a Flutter app for TVs that includes a function to run an HTTP server. Subsequently, I also have a second Flutter application that is web-based and works as a client. I would like that when the HTTP server is started on the TV, I can open a web page (Flutter web) in the browser, whose address will be in the format 
```
http://<ipaddress>:<port>/whatever
```
I tried sending the files generated by flutter after the build of the site (the build/web folder), but that gives me a blank page on the site saying that it is missing main.dart.js, which is basically the entire application (the file is generated by Flutter). I tried to get the JS file there, but that didn't work either. I also tried creating my own HTML page, but it also had a problem with the included JS files. Even when I put the JS in the HTML code, it didn't work as it should. 

When I created an HTML - CSS - JS web page to interact with the first application, it worked.

I tried communicating between the two apps when I had them running separately and it works. 

But my goal is for the user to start the HTTP server with the desired ip address and port, and then open a browser on their computer, enter the ip address and port, and the HTTP server will generate a web page for them. So that the user does not need to have the source for the web page. The web page must not be on any hosting, it should not have access to the internet, it should only communicate with the server - send data to each other.

Could you please guide me on how to achieve this? How to properly send the entire build/web folder to be displayed to the client?

**Comment by darshankawar** [comment]
@TedCermitech 
I think your question is better suited for support channels like StackOverflow or even Flutter's reddit page to get more info.
See if this link helps : https://stackoverflow.com/questions/71599660/flutter-http-server-serve-flutter-web-in-another-app (if that is not already raised by you :))

Closing from here,as this sounds more of a support question rather than a bug or feature request.

**Comment by TedCermitech** [comment]
> @TedCermitech I think your question is better suited for support channels like StackOverflow or even Flutter's reddit page to get more info. See if this link helps : https://stackoverflow.com/questions/71599660/flutter-http-server-serve-flutter-web-in-another-app (if that is not already raised by you :))
> 
> Closing from here,as this sounds more of a support question rather than a bug or feature request.

I wrote this post. I've tried a few other options, but by internal agreement we'd like to get this working. I've continued to work on other projects and have now returned to this one. Since I didn't get any response on SO, I wrote here

**Comment by TedCermitech** [comment]
Resolved - I wrote answer here 
 https://stackoverflow.com/questions/71599660/flutter-http-server-serve-flutter-web-in-another-app
