### ISSUE TITLE
Problem running the application on a mobile device

### ISSUE THREAD

**Issue by unpezdelreves** [flutter/flutter#115663]
## I am having various problems when running my application on the mobile, I have solved several but I have been stuck for a while with these two:

1. Task failed with an exception.
-----------
* What went wrong:
>Execution failed for task ':app:desugarDebugFileDependencies'.
>>\> A failure occurred while executing com.android.build.gradle.internal.tasks.DexFileDependenciesTask$DexFileDependenciesWorkerAction
   >>>\> zip file is empty 

2. Task failed with an exception.
-----------
* What went wrong:
>Execution failed for task ':app:processDebugResources'.
>>\> A failure occurred while executing com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask$TaskAction
   >>>\> Android resource linking failed
     ERROR:: AAPT: error: failed to open APK: Invalid file.

------------
I have looked at a thousand options and I have not been able to solve these two problems, if someone can help me, thank you.

**Comment by darshankawar** [comment]
The error probably indicates gradle cache issue or maybe assuming you are trying to run on emulator, then, the emulator SDK tool isn't updated. You may try to clean your gradle cache and also make sure your Android tool SDKs are on latest.

Closing from here, as this doesn't look like a framework / tool issue. If you disagree, write in comments and I'll reopen it.
