### ISSUE TITLE
Potential regression of flutter framework/engine for web forcing scrolling to slow in tests

### ISSUE THREAD

**Issue by tarrinneal** [flutter/flutter#115678]
A recent flutter -> plugins roll exposed a potential performance regression for web. 

We have altered tests to fix the roller but ideally this only temporary.

last known good: 61e927d22fe6, first known bad: 18c87274cdc9

https://cirrus-ci.com/task/6546247417856000#:~:text=The%20following%20message,one%20was%20unexpected.

I will look into this further to see if I can add more information.

**Comment by yjbanov** [comment]
@tarrinneal Since you are going to look further into this, assigning to you for triage for now so it's not in our triage queue until it's ready. Feel free to decide on a priority as part of your triage.

**Comment by yjbanov** [comment]
Even better, let's dedupe into https://github.com/flutter/flutter/issues/115679 as the other one has more details.
