### ISSUE TITLE
Error (Xcode): redefinition of module 'Firebase' /Users/sparshbansal/Development/Playground/buy_sell/ios/Pods/Firebase/CoreOnly/Sources/module.modulemap:0:7  Error (Xcode): failed to emit precompiled header '/Users/sparshbansal/Library/Developer/Xcode/DerivedData/Runner-eygfgnuelkwzzpbxozolsfdjmxit/Build/Intermediates.noindex/PrecompiledHeaders/Runner-Bridging-Header-swift_2HIAQV5EQ9XFZ-clang_289EBCJULZ6AD.pch' for bridging header '/Users/sparshbansal/Development/Playground/buy_sell/ios/Runner/Runner-Bridging-Header.h'

### ISSUE THREAD

**Issue by sparshba** [flutter/flutter#115629]
Please help me solve these errors
<img width="1792" alt="Screenshot 2022-11-18 at 1 15 11 PM" src="https://user-images.githubusercontent.com/49337034/202648561-0fc1c207-3188-4b6e-b356-9a1bf2963450.png">

<details>
<summary>dependencies</summary>

```
cupertino_icons: ^1.0.2
  flutter_signin_button: ^2.0.0
  animated_text_kit: ^4.2.2
  firebase_core: ^1.24.0
  firebase_auth: ^3.11.1 
  cloud_firestore: ^3.5.1
  location: ^4.4.0
  geocoder2: ^1.4.0
  google_sign_in: ^5.4.2
  email_validator: ^2.1.17
  open_mail_app: ^0.4.5
  country_state_city_picker: ^1.2.8
  flutter_neumorphic: ^3.2.0
  provider: ^6.0.3
  image_picker: ^0.8.6
  firebase_storage: ^10.3.11
  galleryimage: ^1.2.0
  google_maps_flutter: ^2.2.1
  geocoding: ^2.0.5
  geolocator: ^9.0.2
  like_button: ^2.0.5
  photo_view: ^0.14.0
  maps_launcher: ^2.0.1
  search_page: ^2.2.0
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @sparshba,

Please provide your `flutter doctor -v` and `flutter run --verbose` logs. The output of this may be huge so kindly put it into a .txt file and attach it here. Please also make sure that your plugins/packages are all up to date. 


Thank you

**Comment by sparshba** [comment]
Hi @danagbemava-nc 
This issue has been resolved.
But whenever i am clicking on a button the app crashes with no error.
[flutterverbose.docx](https://github.com/flutter/flutter/files/10042129/flutterverbose.docx)
[doctor.docx](https://github.com/flutter/flutter/files/10042145/doctor.docx)

Whenever i click button on this page[Button:Around Me]
[location_screen.txt](https://github.com/flutter/flutter/files/10042073/location_screen.txt)
[home_screen.txt](https://github.com/flutter/flutter/files/10042081/home_screen.txt)
