### ISSUE TITLE
Future function fetching Firebase data doesn't return the desired output

### ISSUE THREAD

**Issue by saurabhdhingra** [flutter/flutter#115767]
## The function I am using to fetch my data

```
Future<List> readTable(List<Date> dates, List<Plot> plots) async {
    List rows = [];
    await userCollection.doc(uid).collection('plots').get().then(
          (QuerySnapshot snapshot) => {
            // ignore: avoid_function_literals_in_foreach_calls
            snapshot.docs.forEach(
              (plot) async {
                List row = [];
                for (Date d in dates) {
                  List works = [];
                  print(firebaseDocumentDate(d.dateTime));
                  await userCollection
                      .doc(uid)
                      .collection('plots')
                      .doc(plot['name'])
                      .collection(firebaseDocumentDate(d.dateTime))
                      .get()
                      .then(
                    (QuerySnapshot date) {
                      for (var work in date.docs) {
                        works.add(
                          Work(
                            work.id,
                            work['category'],
                            work['worker'],
                            work['description'],
                            work['status'],
                          ),
                        );
                      }
                    },
                  );
                  row.add(works);
                }
                rows.add(row);
                print(rows);
              },
            ),
          },
        );
    return rows;
  }
```

The "Date" class

```
class Date {
  final DateTime dateTime;
  final String text;

  Date(this.dateTime, this.text);
}
```

The "Work" class

```
class Work {
  final String id;
  final String category;
  final String worker;
  final String description;
  final String status;

  Work(
    this.id,
    this.category,
    this.worker,
    this.description,
    this.status,
  );
}
```

## Firebase Cloud Firestore database

A diagram representing  my database
![Collection 'users'](https://user-images.githubusercontent.com/75309640/203100899-fd571e59-c8ec-4420-b3e5-aa9d40b5684e.png)

The output of the print statement.

`flutter: [[[], [], [], [], [], [], []], [[], [], [], [], [], [], []], [[], [], [], [], [], [], []], [[], [], [], [], [], [], []], [[], [], [], [], [], [], []], [[], [Instance of 'Work'], [], [], [Instance of 'Work'], [], []], [[], [], [], [], [], [], []]]`

But when I print the final output it is an empty list.
`flutter: []`

I have worked with a similar function on the same project.

```
  Future<List<Plot>> readPlots() async {
    List<Plot> plots = [];
    await userCollection.doc(uid).collection('plots').get().then(
          (QuerySnapshot snapshot) => {
            snapshot.docs.forEach(
              (plot) {
                plots.add(
                  Plot(plot["name"]),
                );
              },
            )
          },
        );
    return plots;
  }
```

This works well. I think the await function is so lengthy that flutter simply returns the empty list I declared in the function.

I was expecting the output that that the print statement inside the function returns.
`flutter: [[[], [], [], [], [], [], []], [[], [], [], [], [], [], []], [[], [], [], [], [], [], []], [[], [], [], [], [], [], []], [[], [], [], [], [], [], []], [[], [Instance of 'Work'], [], [], [Instance of 'Work'], [], []], [[], [], [], [], [], [], []]]`

**Comment by iapicca** [comment]
@saurabhdhingra looks like a [flutterfire](https://firebase.flutter.dev/) issue, maybe should be opened [here](https://github.com/firebase/flutterfire/issues)

**Comment by danagbemava-nc** [comment]
Hi @saurabhdhingra, as noted above this should be reported on the flutterfire repo. 

Closing this as this is out of scope for the flutter repo since firebase database is a third-party package. 

Thank you
