### ISSUE TITLE
Alignment,margin nad padding

### ISSUE THREAD

**Issue by TitikshaDaga** [flutter/flutter#11578]

**Comment by TitikshaDaga** [comment]
Coders should be able to resize,align,add margin and padding to every widget. Also match parent and wrap content should also be available.

**Comment by eseidelGoogle** [comment]
https://docs.flutter.io/flutter/widgets/Align-class.html
https://docs.flutter.io/flutter/widgets/Padding-class.html
might help you achieve your desired effects?  Flutter favors composition over inheritance:
https://flutter.io/faq/#can-i-extend-and-customize-the-bundled-widgets

**Comment by Hixie** [comment]
@TitikshaDaga Please let us know is @eseidelGoogle's comment above was not sufficient to explain how to achieve the effect you are looking for. Thanks!
