### ISSUE TITLE
add padding to DropdownButton

### ISSUE THREAD

**Issue by davidskelly** [flutter/flutter#115793]
## Use case

Inside the implementation of DropdownButton is an Inkwell. This Inkwell has a hitbox that does not cover the entire area of the button. A user can click on the button but the click is not handled.

## Proposal

Example - when implementing a custom dropdown that looks like this:
![Screenshot from 2022-11-21 16-20-15](https://user-images.githubusercontent.com/10343858/203161073-565553c2-d656-4217-9d65-747f82b80716.png)

The clickable hitbox looks like this:
![Screenshot from 2022-11-21 16-19-41](https://user-images.githubusercontent.com/10343858/203161913-fac19770-9e16-418b-b166-0b08e8b22bf0.png)

The desired hitbox should look like this:
![Screenshot from 2022-11-21 16-20-02](https://user-images.githubusercontent.com/10343858/203162038-a028b585-517b-420b-b3f3-241adbbbaf7b.png)

To accomplish this, add Padding to the Inkwell.

**Comment by exaby73** [comment]
Hello @davidskelly. Thank you for filing this issue. I can see a PR, which I went ahead and linked. Before I go ahead and label this issue, could you provide a code sample and steps to reproduce this behavior?

**Comment by davidskelly** [comment]
> Hello @davidskelly. Thank you for filing this issue. I can see a PR, which I went ahead and linked. Before I go ahead and label this issue, could you provide a code sample and steps to reproduce this behavior?

Hi @exaby73  - here is some sample code that builds the widget in question. Prior to the PR, this line `padding: EdgeInsets.symmetric(horizontal: 50),` is set in the `Container`. After the PR, this line should be moved inside the `DropdownButton` to give the same visual appearance but increase the size of the hitbox.

To reproduce:
1. Create sample app add plug in build() function.
2. Mouse over the widget - see the cursor change only when it's over the tiny hitbox.

```
@override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Container(
          // height: 50,
          // margin: const EdgeInsets.symmetric(),
          child: DropdownButtonHideUnderline(
            child: Container(
              constraints: BoxConstraints(minHeight: 50),
              decoration: BoxDecoration(
                border: Border.all(color: Colors.grey, width: 1),
                borderRadius: BorderRadius.all(Radius.circular(5)),
                color: Colors.white,
              ),
              padding: EdgeInsets.symmetric(horizontal: 50),
              child: DropdownButton(
                value: "One",
                onChanged: (newValue) {
                  onChanged(newValue);
                },
                items: ["One", "Two", "Three"]
                    .map((String value) => DropdownMenuItem(
                          value: value,
                          child: Column(
                            mainAxisAlignment: MainAxisAlignment.center,
                            crossAxisAlignment: CrossAxisAlignment.start,
                            children: [
                              Text(value),
                            ],
                          ),
                        ))
                    .toList(),
              ),
            ),
          ),
        ),
      ),
    );
  }

  void onChanged(String? newValue) {}
```
