### ISSUE TITLE
Manually install dart-sdk and download pub packages 

### ISSUE THREAD

**Issue by lyrachord** [flutter/flutter#11575]
flutter automatically do all required things. 
f.e. sdk
Indeed I often downloaded dart-sdk
but flutter owns a new piece of dart-sdk, although to copy my downloaded to flutter is not so hard

Let's make flutter configable for its requirement?

**Comment by Hixie** [comment]
Flutter uses a carefully compiled Dart SDK that is specific to the version of Flutter that you are using, which is why we manage that for you.
