### ISSUE TITLE
Make inheritFromWidgetOfExactType faster

### ISSUE THREAD

**Issue by abarth** [flutter/flutter#11572]
Once we've got RTL implemented, we should check whether there's performance on the table by special casing the TextDirection in BuildContext rather than using the generic inherited widget codepath.

**Comment by Hixie** [comment]
I'm curious to see how you would implement it. If there's a way to implement this that's faster than inherited widgets, maybe we can use it for inherited widgets too... :-)

(The interesting part is the ability to mark only the widgets that changed dirty when the directionality of a subset of the tree changes.)

**Comment by Hixie** [comment]
We need to make inheritFromWidgetOfExactType faster in general. Adding one call to this method from Theme.of is adding 200ms to the build benchmark.

**Comment by abarth** [comment]
I wonder if its the `_inheritedWidgets` lookup that is slow or messing around with `_dependencies`.  It's possible there's some room for optimization for maps keyed by `Type` objects.

**Comment by Hixie** [comment]
See also https://github.com/dart-lang/sdk/issues/31011.

**Comment by a-siva** [comment]
cc @alexmarkov

**Comment by Hixie** [comment]
I tried adding a DefaultAssetBundle.of call in the middle of RichText's create and update methods, and it barely affected the numbers (it was within the noise). So I'm going to close this. Thanks everyone who helped improve this!
