### ISSUE TITLE
Flutter is not running properly for the new installation or may be after the recent update. ('crumb' is not recognized as an internal or external command, operable program or batch file)

### ISSUE THREAD

**Issue by sudhanshuy17** [flutter/flutter#115724]
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

<details>
<summary>Logs</summary>

```
```

</details>

**Comment by sudhanshuy17** [comment]
'crumb' is not recognized as an internal or external command,
operable program or batch file.

**Comment by huycozy** [comment]
@sudhanshuy17 Please provide the output of `flutter doctor -v`.

Also, please check this SO answer if it can help to solve this: https://stackoverflow.com/questions/52411883/crumb-is-not-recognized-as-an-internal-or-external-command-operable-program-o

**Comment by sudhanshuy17** [comment]
>flutter doctor -v
'crumb' is not recognized as an internal or external command,
operable program or batch file.
[√] Flutter (Channel stable, 3.3.8, on Microsoft Windows [Version 10.0.19044.2311], locale en-US)
    • Flutter version 3.3.8 on channel stable at D:\flutter_windows_3.3.8-stable\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 52b3dc25f6 (2 weeks ago), 2022-11-09 12:09:26 +0800
    • Engine revision 857bd6b74c
    • Dart version 2.18.4
    • DevTools version 2.15.0

[!] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at C:\Users\Sudhanshu\AppData\Local\Android\sdk
    • Platform android-32, build-tools 32.0.0
    X Android SDK file not found: C:\Users\Sudhanshu\AppData\Local\Android\sdk\build-tools\32.0.0\aapt.
    • Try re-installing or updating your Android SDK,
      visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.3.6)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.3.32929.385
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] IntelliJ IDEA Community Edition (version 2021.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.3
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code (version 1.73.1)
    • VS Code at C:\Users\Sudhanshu\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19044.2311]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 107.0.5304.107
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 107.0.1418.52

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

**Comment by huycozy** [comment]
@sudhanshuy17 Have you tried solutions in above SO answers? Is there another error message after trying them?

**Comment by sudhanshuy17** [comment]
I tried that and so many other things also but noting works
