### ISSUE TITLE
`MouseRegion` does not work with `Clip`

### ISSUE THREAD

**Issue by nilsreichardt** [flutter/flutter#115771]
## Description

`MouseRegion` widget gets ignored on `Clip` widgets.

## Demo

https://user-images.githubusercontent.com/24459435/203114440-78689e40-6e20-4fa8-a3b5-75901f05768b.mov

## Steps to reproduce

1. Run this code:
```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: const [
              // This does not work :(
              MouseRegion(
                cursor: SystemMouseCursors.click,
                child: Chip(
                  label: Text("Flutter"),
                ),
              ),
              SizedBox(height: 12),
              // This works :)
              MouseRegion(
                cursor: SystemMouseCursors.click,
                child: Text("Flutter"),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
```
2. Try to hover on the `Chip` with "Flutter"

## What I would expect

I would expect that the mouse cursor changes to a clickable mouse cursor, like it's the case the with Flutter text below the chip.

## Additional information 

I tried it on `master` & `stable` and on web and macOS. For all parameter I go the issue.

**Comment by exaby73** [comment]
Hi @nilsreichardt 
I see there's an open issue addressing the case you described https://github.com/flutter/flutter/issues/58192
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
