### ISSUE TITLE
Handle navigation with FlutterFragment from Kotlin

### ISSUE THREAD

**Issue by yvanaonana** [flutter/flutter#115768]
Hello flutter team, I have integrated a FlutterFragment in my application with a BottomNavigationBar.  So one item of the BottomNavigationBar has a FragmentContainer and loads a FlutterFragment in it. This FlutterFragment is loaded by a cachedFlutterEngine and contains a certain number of pages. When a user uses the back button of the Android system when the FlutterFragment is open, the back behavior of the kotlin fragment is applied. So the app back to the previous view of the main app not to the previous view in the FlutterFragment. 

To solve this problem, I read this issue https://github.com/flutter/flutter/issues/67011 and  I try to make the navigation back in the FlutterFragment. So I used the class `OnBackPressedCallback` and I redefined the back pressed for the fragment that contains the flutter fragment like below: 

```
val onBackPressedCallback = object : OnBackPressedCallback(true) { 
        override fun handleOnBackPressed() {
                flutterEngine?.navigationChannel?.popRoute()
        }
}
```

        requireActivity().onBackPressedDispatcher.addCallback(
            viewLifecycleOwner,
            onBackPressedCallback
        )`

It works in the FlutterFragment when the user clicks on the back button of the system it makes navigation back in Flutter. The problem is when we are at the last page of Flutter. When the user clicks the back button it doesn't work and when he chooses another item of the BottomNavigationBar(like when we quit the fragment where the flutter is) all the times he has clicked on back button are applied like the application remember how many he has tried to back and apply it. 

Please any solution to leave the flutter fragment and at the same time keep the navigation back in flutter fragment ?

**Comment by huycozy** [comment]
Hi @yvanaonana, thanks for filing the issue. But issue #67011 is still in progress. I recommend you follow up on it and leave comments there (as others can know your case) to help elaborate on that feature.

I will close this issue as a duplicate. If you disagree, please write in the comments and I will reopen it. Thank you!
