### ISSUE TITLE
Android production crash in `libflutter.so`

### ISSUE THREAD

**Issue by jkl705** [flutter/flutter#115745]
i got two error msg at the same time , one is from vm, the other one is from the framework,are those two related,or just coincidences?
cuz i saw similar framework errors on production so many time and still dont know how to fix it,

```console
E/flutter (23250): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Bad state: Stream has been disposed.

E/flutter (23250): An ImageStream is considered disposed once at least one listener has been added and subsequently all listeners have been removed and no handles are outstanding from the keepAlive method.
E/flutter (23250): To resolve this error, maintain at least one listener on the stream, or create an ImageStreamCompleterHandle from the keepAlive method, or create a new stream for the image.
E/flutter (23250): #0      ImageStreamCompleter._checkDisposed (package:flutter/src/painting/image_stream.dart:602:7)
E/flutter (23250): #1      ImageStreamCompleter.reportImageChunkEvent (package:flutter/src/painting/image_stream.dart:742:5)
E/flutter (23250): #2      _RootZone.runUnaryGuarded (dart:async/zone.dart:1586:10)
E/flutter (23250): #3      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
E/flutter (23250): #4      _DelayedData.perform (dart:async/stream_impl.dart:515:14)
E/flutter (23250): #5      _PendingEvents.handleNext (dart:async/stream_impl.dart:620:11)
E/flutter (23250): #6      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:591:7)
E/flutter (23250): #7      _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
E/flutter (23250): #8      _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
E/flutter (23250): 
```

```console
F/libc    (23250): Fatal signal 11 (SIGSEGV), code 1, fault addr 0x86980030 in tid 23363 (1.raster)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'google/android_x86/x86:7.1.2/N2G47H/G955FXXU1AQJ5:/release-keys'
Revision: '0'
ABI: 'x86'
pid: 23250, tid: 23363, name: 1.raster  >>> com.speediance.faraday <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x86980030
    eax 8697c840  ebx b6e209b4  ecx 00003800  edx a8680250
    esi 0000382c  edi 00003800
    xcs 00000073  xds 0000007b  xes 0000007b  xfs 0000003b  xss 0000007b
    eip c647f3ce  ebp a6a077c8  esp a6a07788  flags 00010287
backtrace:
    #00 pc 000193ce  /system/lib/libc.so (memcpy+46)
    #01 pc 00041904  /system/lib/libstagefright_soft_gl2enc.so
    #02 pc 0002116e  /system/lib/libstagefright_soft_gl2enc.so (_ZN10GL2Encoder17s_glTexSubImage2DEPvjiiiiijjPKv+2078)
    #03 pc 0000ddf0  /system/lib/egl/libGLESv2_adreno.so (glTexSubImage2D+128)
    #04 pc 0038b1d2  /data/app/com.speediance.faraday-2/lib/x86/libflutter.so (offset 0x14a5000)
```

**Comment by jkl705** [comment]
[√] Flutter (Channel stable, 3.3.8, on Microsoft Windows [版本 10.0.19044.2130], locale zh-CN)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[√] Chrome - develop for the web
[!] Visual Studio - develop for Windows (Visual Studio 生成工具 2019 16.11.20)
    X The current Visual Studio installation is incomplete. Please reinstall Visual Studio.
[√] Android Studio (version 2021.3)
[√] Connected device (5 available)
[√] HTTP Host Availability            
                                      
! Doctor found issues in 2 categories.
PS E:\soft-app\flutter> flutter doctor -v
Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
[√] Flutter (Channel stable, 3.3.8, on Microsoft Windows [版本 10.0.19044.2130], locale zh-CN)
    • Flutter version 3.3.8 on channel stable at D:\flutter_windows_3.3.8-stable\flutter      
    • Upstream repository https://github.com/flutter/flutter.git                              
    • Framework revision 52b3dc25f6 (12 days ago), 2022-11-09 12:09:26 +0800                  
    • Engine revision 857bd6b74c                                                              
    • Dart version 2.18.4                                                                     
    • DevTools version 2.15.0                                                                 
    • Pub download mirror https://pub.flutter-io.cn                                           
    • Flutter download mirror https://storage.flutter-io.cn                                   

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at D:\Android\SDK
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop for Windows (Visual Studio 生成工具 2019 16.11.20)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
    • Visual Studio 生成工具 2019 version 16.11.32929.386
    • Windows 10 SDK version 10.0.19041.0
    X The current Visual Studio installation is incomplete. Please reinstall Visual Studio.

[√] Android Studio (version 2021.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[√] Connected device (5 available)
    • rk3568 r (mobile) • 30d91f0e3972b1cf • android-arm64  • Android 11 (API 30)
    • PCRT00 (mobile)   • emulator-5554    • android-x86    • Android 7.1.2 (API 25)
    • Windows (desktop) • windows          • windows-x64    • Microsoft Windows [版本 10.0.19044.2130]
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 107.0.5304.107
    • Edge (web)        • edge             • web-javascript • Microsoft Edge 106.0.1370.52

[√] HTTP Host Availability
    • All required HTTP hosts are available

**Comment by exaby73** [comment]
Hello @jkl705. Thank you for raising this issue. Could you provide a [complete and minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) so that I may verify the issue?

**Comment by jkl705** [comment]
> Hello @jkl705. Thank you for raising this issue. Could you provide a [complete and minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) so that I may verify the issue?

unfortunately , This crash cannot reappear stably , or u cant tell me why is the first bug happens

**Comment by exaby73** [comment]
I'm not sure of these 2 errors are related. I'll label this issue for further insights from the team. Thank you

**Comment by chinmaygarde** [comment]
I don't believe the two are related. The second error looks like device memory exhaustion. Perhaps using too many images? The driver is meant to reject these texture uploads but this one seems to be crashing. Is there are reproduction?
