### ISSUE TITLE
when upgrade 3.3.8, has a gradle error:Using insecure protocols with repositories, without explicit opt-in, is unsupported

### ISSUE THREAD

**Issue by shaomaicheng** [flutter/flutter#115765]
## Steps to Reproduce

when I upgrade flutter version to 3.3.8, when i run 
```
flutter build aar
```
I get a error:
```
Using insecure protocols with repositories, without explicit opt-in, is unsupported. Switch Maven repository 'maven2(http://mvn.hz.netease.com/artifactory/libs-snapshots)' to redirect to a secure protocol (like HTTPS) or allow insecure protocols. See https://docs.gradle.org/7.4/dsl/org.gradle.api.artifacts.repositories.UrlArtifactRepository.html#org.gradle.api.artifacts.repositories.UrlArtifactRepository:allowInsecureProtocol for more details.
```

But I check my project, it do not have any library moudle or flutter plugin's gradle file has this repository url.
how can I slove this problem？？？

**Expected results:** 

**Actual results:** 

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by shaomaicheng** [comment]
The URLs of all plug-ins are changed to https. Why does this error occur？

**Comment by huycozy** [comment]
Hi @shaomaicheng 
I can not reproduce this issue with [fullscreen sample code](https://github.com/flutter/samples/tree/main/add_to_app/fullscreen) on the latest Flutter stable `3.3.8` channel. Please try building with that sample code and confirm if the issue still persists.

**Comment by shaomaicheng** [comment]
i reslove it after i use 
```
flutter pub upgrade
```

**Comment by huycozy** [comment]
Given your last message, I feel safe to close this issue as solved, if you disagree please write in the comments and I will reopen it. Thank you!
