### ISSUE TITLE
Update `AppBar` actions according to Material 3 specs

### ISSUE THREAD

**Issue by yegor-pelykh** [flutter/flutter#115722]
If I'm not mistaken, according to the Material 3 specs, all action buttons in the `AppBar` should be 48x48 pixels in size, but in the current master, these buttons are smaller.

![pic](https://user-images.githubusercontent.com/21262076/202905342-b914a4ea-5081-4cec-9b2b-3fa02b9c3a7a.png)

Could you please have a look at this?

**UPD**: Moreover, for some reason, the display of the action in the AppBar in the [demo](https://flutter.github.io/samples/web/material_3_demo) differs from that which is obtained in my app (the **master** channel is used). On **hover** in my app it's a round button, but in your demo it's a vertically stretched button.
But again, I think it should be round and 48x48 in size.

Demo:
![pic](https://user-images.githubusercontent.com/21262076/202906046-ab99073f-2f3a-4122-b280-edebea92dbb0.png)

My app:
![pic](https://user-images.githubusercontent.com/21262076/202906082-df79b603-adf8-4f70-a0ce-972810cf9d82.png)

Related to #91605

**Comment by yegor-pelykh** [comment]
Hi @huycozy

Sorry, the source of what exactly to share?
I don't mean that a round button is wrong. I think that it should be round.
The problem is that for some reason, in the flutter demo (https://flutter.github.io/samples/web/material_3_demo), this button looks NOT round, but stretched up. Therefore, it looks confusing, because in my application it is displayed differently.

But this is one thing.

The problem I wanted to address to the flutter community is that **these buttons seem to be 48x48 pixels**.

**Comment by yegor-pelykh** [comment]
> Are you referring to Target size in this spec?

Let's say yes.
Also, there is another image demonstrating that size 48x48.
![pic](https://user-images.githubusercontent.com/21262076/203053431-518efa6d-55d7-461c-a8f7-5aa94406e8ab.png)

**Comment by huycozy** [comment]
>The problem is that for some reason, in the flutter demo (https://flutter.github.io/samples/web/material_3_demo), this button looks NOT round, but stretched up:

![203033119-8e596413-8cc0-4427-88b6-c900e70d2673](https://user-images.githubusercontent.com/104349824/203217158-453dd503-d959-4b87-9af5-186c457baf93.png)

Update: I can see this issue when running on Flutter stable `3.3.8`. It's not reproducible on the latest Flutter master `3.6.0-7.0.pre.17`. So this partial issue is fixed.

---

>these buttons need to be 48x48 pixels

Labeling this issue for further insights from the team. This issue is reproducible on the latest `stable` and `master` channels.

The button size is different between Flutter stable and master channels. 
- Stable: 40x56 (Width x Height)
- Master: 40x40 (Width x Height)

<details>
<summary>Demo (Flutter Inspector)</summary>

| stable | master |
| --------------- | --------------- |
<img width="400" src="https://user-images.githubusercontent.com/104349824/203217765-84cfe6b0-f9c9-4722-8dd1-16a339ef9fc3.png"> | <img width="400" src="https://user-images.githubusercontent.com/104349824/203216714-71f3da37-71ae-4e6b-90a6-dcc3dee4288d.png">

</details>

<details>
<summary>Sample code</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Flutter Demo',
      theme: ThemeData(
        useMaterial3: true,
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Demo AppBar'),
          actions: [
            Icon(Icons.adb),
            IconButton(onPressed: () {}, icon: Icon(Icons.more_vert)),
          ],
        ),
        body: Center(
          child: Text('Hello world!'),
        ),
      ),
    );
  }
}
```
</details>

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.3.8, on macOS 13.0 22A380 darwin-x64, locale en-VN)
    • Flutter version 3.3.8 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 52b3dc25f6 (23 hours ago), 2022-11-09 12:09:26 +0800
    • Engine revision 857bd6b74c
    • Dart version 2.18.4
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Community Edition (version 2022.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 70.0.5
    • Dart plugin version 222.4167.21

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.73.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.52.0

[✓] Connected device (3 available)
    • iPhone 14 Pro Max (mobile) • 332079AF-E895-4685-910E-7B1E18B0C6B8 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-0 (simulator)
    • macOS (desktop)            • macos                                • darwin-x64     • macOS 13.0 22A380 darwin-x64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 107.0.5304.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

```bash
[!] Flutter (Channel master, 3.6.0-7.0.pre.17, on macOS 13.0 22A380 darwin-x64, locale en-VN)
    • Flutter version 3.6.0-7.0.pre.17 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 182d6c4c94 (2 hours ago), 2022-11-21 19:51:06 -0500
    • Engine revision ddf6a20b86
    • Dart version 2.19.0 (build 2.19.0-414.0.dev)
    • DevTools version 2.19.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Community Edition (version 2022.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 70.0.5
    • Dart plugin version 222.4167.21

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.73.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.52.0

[✓] Connected device (3 available)
    • SM T225 (mobile) • R9JT3004VRJ • android-arm64  • Android 12 (API 31)
    • macOS (desktop)  • macos       • darwin-x64     • macOS 13.0 22A380 darwin-x64
    • Chrome (web)     • chrome      • web-javascript • Google Chrome 107.0.5304.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```
</details>

**Comment by QuncCccccc** [comment]
Hi @yegor-pelykh, this demo app (https://flutter.github.io/samples/web/material_3_demo) is based on the stable branch. Please check out this demo: https://flutter-experimental-m3-demo.web.app/#/ , It is based on the latest master branch.

Also want to double check which platform that you app is running on? 
By default, the web and desktop platform use `MaterialTapTargetSize.shrikWrap` which may make the buttons smaller(40x40) and the mobil platforms use `MaterialTapTargetSize.padded` which will show a normal size (48x48). If this is the problem and you still want 48x48 on all platforms, you can give a custom `style` for a specific button or just use a `IconButtonTheme` for all `IconButtons`
```
IconButton(
  style: IconButton.styleFrom(tapTargetSize: MaterialTapTargetSize.padded),
  onPressed: () {}, icon: const Icon(Icons.more_vert)
),
```

Please let me know if you still see the problem. Thanks!

**Comment by yegor-pelykh** [comment]
Hi @QuncCccccc
This is very informative, thanks!

The problem is that I usually use the PopupMenuButton in the AppBar.
In this case, apparently, this method will not work.
What to then with PopupMenuButton?

**Comment by QuncCccccc** [comment]
> Hi @QuncCccccc This is very informative, thanks!
> 
> The problem is that I usually use the PopupMenuButton in the AppBar. In this case, apparently, this method will not work. What to then with PopupMenuButton?

Probably you can use an IconButtonTheme to wrap the PopupMenuButton?
```
IconButtonTheme(
    data: IconButtonThemeData(
        style: IconButton.styleFrom(
            tapTargetSize: MaterialTapTargetSize.padded,
         )
    ),
    child: PopupMenuButton(itemBuilder: (context) {
         return [
             PopupMenuItem(child: Text('Item 0')),
             PopupMenuItem(child: Text('Item 1')),
             PopupMenuItem(child: Text('Item 2'))
         ];
    },),
),
```

**Comment by yegor-pelykh** [comment]
@QuncCccccc Perfect! It works! Thanks a lot!
