### ISSUE TITLE
Flutter, json -> map update value is not able in for statement, bug

### ISSUE THREAD

**Issue by yeahse** [flutter/flutter#115736]
After receiving the json object, (from REST api)

jsonDecode to create a List<Map<String,dynamic>> variable,

and inside for statement, do map['key'] = anyValue; Try it.

I think I found a flutter bug. Flutter version is 3

```
[ "data": [
          {
            "id": 1,
            "title": "",
            "price": null,
            "some": [
                      {
                        "needToChange": 1 (int)
                       }
                     ],
            }
         ]

List<dynamic> data = jsonDecode(res.body)['data'];
for(int i = 0 ; i < 10 ; i++){
  data['some']['needToChange'] = someArray[i]; // new int value
  print(data['some']['needToChange']); // it is changed for now but it rolls back when scope is dead
}](url)
```

`print(data['some']['needToChange']) // it results 1 nothing changed`

----------------------------------------------------------------------------------------
FULL CODE

 ```
dynamic res = await http.post(
        Uri.parse(C_URL_BASE + '/v1/post-query/abc'),
        headers: {
          "Content-Type": "application/json",
          "Accept": "application/json",
        },
        body: body);
```
    
    Map<String, dynamic> jsonData = json.decode(res.body);
    List<dynamic> myList = [];
    for (int i = 0; i < jsonData['data']['someA'].length; i++) {
      for (int k = 0; k < jsonData['data']['someB'].length; k++) {
        if (jsonData['data']['someA'][i]['nestedA'] ==
            jsonData['data']['someB'][k]['nestedB']) {
          var map = jsonData['data']['someB'][k];
          print(jsonData['data']['someA'][i]['id']);
          map.update('needToChange',
                  (value) => jsonData['data']['someA'][i]['id']);
          myList.add(map);
        }
      }
    }

    print("it begins " + myList.length.toString());
    for (int i = 0; i < myList.length; i++) {
      print(myList[i]['needToChange']); //nothing changed!!
    }

------------------------------------------------------------------
json data summary

```
"someA": [
          {
            "nestedA": 2,
            "id": 5
          },
          {
            "nestedA": 1,
            "id": 2
          },
          {
            "nestedA": 2,
            "id": 4
          },
          {
            "nestedA": 1,
            "id": 3
          },
          {
            "nestedA": 1,
            "id": 1
          }
        ],
        "someB": [
          {
            "id": 1,
            "needToChange": 111,
           },],]
```
I added more I am sure they are list please check it out

this is all I have

**Comment by huycozy** [comment]
Hi @yeahse 
It seems your question is best suited for support channels like StackOverflow, so please ask the same there for solutions if any. 
If you are proposing a change, please use the appropriate new issue template and fill out the requested details so that we can address this issue properly.

Closing for now.

**Comment by yeahse** [comment]
> Hi @yeahse 
> It seems your question is best suited for support channels like StackOverflow, so please ask the same there for solutions if any. 
> If you are proposing a change, please use the appropriate new issue template and fill out the requested details so that we can address this issue properly.
> 
> Closing for now.

 This is a BUG not about syntaxes.
