### ISSUE TITLE
[tool_crash] FileSystemException: Directory listing failed, OS Error: System nie może odnaleźć określonej ścieżki., errno = 3

### ISSUE THREAD

**Issue by macik1423** [flutter/flutter#115753]
## Command
```
flutter --no-color test --machine --start-paused --plain-name makes correct http request test\packages\warehouse_api\warehouse_api_client_test.dart
```

## Steps to Reproduce
I try to run test files from folder packages which is located out of lib folder. I moved package test file to my main test folder because when I run package test there was error "No tests were found". This is my project tree:
+--barcode_scanner_client/
|  +--lib/
|  |  +--app.dart
|  |  +--authentication
|  |  +--constants
|  |  +--home
|  |  +--inventory
|  |  +--locate_item
|  |  +--main.dart
|  |  +--menu
|  |  +--pull_item
|  |  +--router
|  |  +--services
|  |  +--util
|  |  +--warehouse
|  +--packages/
|  |  +--authentication_repository/
|  |  |  +--lib/
|  |  |  |  +--authentication_repository.dart
|  |  |  |  +--src/
|  |  |  |  |  +--authentication_repository.dart
|  |  |  +--pubspec.lock
|  |  |  +--pubspec.yaml
|  |  +--user_repository/
|  |  |  +--lib/
|  |  |  |  +--src/
|  |  |  |  |  +--models/
|  |  |  |  |  |  +--models.dart
|  |  |  |  |  |  +--user.dart
|  |  |  |  |  +--user_repository.dart
|  |  |  |  +--user_repository.dart
|  |  |  +--pubspec.lock
|  |  |  +--pubspec.yaml
|  |  +--warehouse_api/
|  |  |  +--lib/
|  |  |  |  +--src/
|  |  |  |  |  +--models/
|  |  |  |  |  +--views/
|  |  |  |  |  +--warehouse_api_client.dart
|  |  |  |  +--warehouse_api.dart
|  |  |  +--pubspec.lock
|  |  |  +--pubspec.yaml
|  |  +--warehouse_repository/
|  |  |  +--lib/
|  |  |  |  +--src/
|  |  |  |  |  +--warehouse_repository.dart
|  |  |  |  +--warehouse_repository.dart
|  |  |  +--pubspec.lock
|  |  |  +--pubspec.yaml
|  +--pubspec.lock
|  +--pubspec.yaml
|  +--README.md
|  +--test/
|  |  +--lib/
|  |  |  +--authentication/
|  |  |  |  +--bloc
|  |  |  +--helpers
|  |  |  +--home
|  |  |  +--inventory
|  |  |  +--locate_item/
|  |  |  +--login/
|  |  |  |  +--bloc
|  |  |  |  +--view
|  |  |  +--menu/
|  |  |  |  +--view
|  |  +--packages/
|  |  |  +--warehouse_api/
|  |  |  |  +--warehouse_api_client_test.dart

The error is from file warehouse_api_client_test.dart
Edit: I noted when I delete /test/packages and restore the error disappears.

## Logs
FileSystemException: Directory listing failed, OS Error: System nie może odnaleźć określonej ścieżki.
, errno = 3
```
#0      _Directory._fillWithDirectoryListing (dart:io-patch/directory_patch.dart:42:24)
#1      _Directory.listSync (dart:io/directory_impl.dart:243:5)
#2      ForwardingDirectory.listSync (package:file/src/forwarding/forwarding_directory.dart:43:12)
#3      ForwardingDirectory.listSync (package:file/src/forwarding/forwarding_directory.dart:43:12)
#4      _AssetDirectoryCache.variantsFor (package:flutter_tools/src/asset.dart:1041:78)
#5      ManifestAssetBundle._parseAssetFromFile (package:flutter_tools/src/asset.dart:866:37)
#6      ManifestAssetBundle._parseAssets (package:flutter_tools/src/asset.dart:753:9)
#7      ManifestAssetBundle.build (package:flutter_tools/src/asset.dart:261:54)
<asynchronous suspension>
#8      TestCommand._buildTestAsset (package:flutter_tools/src/commands/test.dart:474:23)
<asynchronous suspension>
#9      TestCommand.runCommand (package:flutter_tools/src/commands/test.dart:318:7)
<asynchronous suspension>
#10     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1209:27)
<asynchronous suspension>
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#12     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#13     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#15     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 3.3.8, on Microsoft Windows [Version 10.0.19042.2194], locale pl-PL)
    • Flutter version 3.3.8 on channel stable at C:\Program Files\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 52b3dc25f6 (12 days ago), 2022-11-09 12:09:26 +0800
    • Engine revision 857bd6b74c
    • Dart version 2.18.4
    • DevTools version 2.15.0

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at C:\Users\plradmkw\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.0-rc4
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop for Windows (Visual Studio Community 2022 17.4.1)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.4.33110.190
    • Windows 10 SDK version 10.0.22000.0
    ✗ Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop development with C++" workload, and include these components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK

[✓] Android Studio (version 2021.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Community Edition (version 2022.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2022.1
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.73.1)
    • VS Code at C:\Users\plradmkw\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19042.2194]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 104.0.5112.81
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 107.0.1418.35

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: ee4e09cce01d6f2d7f4baebd247fde02e5008851
### Plugins
flutter_barcode_scanner-2.0.0
flutter_plugin_android_lifecycle-2.0.7
flutter_secure_storage-6.0.0
flutter_secure_storage_linux-1.1.1
flutter_secure_storage_macos-1.1.1
flutter_secure_storage_web-1.0.2
flutter_secure_storage_windows-1.1.2
path_provider-2.0.11
path_provider_android-2.0.20
path_provider_ios-2.0.11
path_provider_linux-2.1.7
path_provider_macos-2.0.6
path_provider_windows-2.1.3
shared_preferences-2.0.15
shared_preferences_android-2.0.13
shared_preferences_ios-2.1.1
shared_preferences_linux-2.1.1
shared_preferences_macos-2.0.4
shared_preferences_web-2.0.4
shared_preferences_windows-2.1.1

**Comment by huycozy** [comment]
@macik1423 Does this issue happen with a new Flutter project and place test files in the correct directory? 
If not so, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this. Thanks!
