### ISSUE TITLE
[Impeller] impcllerc uses a SPIRV-Cross API that has been removed.

### ISSUE THREAD

**Issue by dneto0** [flutter/flutter#115785]
## Steps to Reproduce

Flutter Engine fails to build with latest dependencies.

flutter/engine impeller/compiler/spirv_sksl.cc depends on a spirv_cross::declared_undefined_values method which has been removed from SPIRV-Cross.

See https://github.com/KhronosGroup/SPIRV-Cross/pull/2062 for the removal of the API.

Dependency in flutter/engine:  
https://github.com/flutter/engine/blob/main/impeller/compiler/spirv_sksl.cc#L353 

## Logs

<details>
<summary>Logs</summary>

engine/impeller/compiler/spirv_sksl.cc:3: error: use of undeclared identifier 'declare_undefined_values'
  declare_undefined_values();
  ^
1 error generated.

```

</details>

**Comment by gaaclarke** [comment]
This was fixed in https://github.com/flutter/engine/pull/38650
