### ISSUE TITLE
Unable to make http request to custom port flutter web.

### ISSUE THREAD

**Issue by jogindergur** [flutter/flutter#115711]
I am using Flutter for a web project and I am usually able to make HTTP requests on custom ports like:

`http://13.1.1.2:3000/`

or 

`http://13.1.1.2:6000/`

but after the SDK upgrade, I am only able to make HTTP requests on only port 80.

My backend is in NodeJs with express.
so, I already set cors for all.

still unable to hit HTTP request on a port other than 80 port.
Solutions and suggestions are welcome.

**Comment by huycozy** [comment]
Hi @jogindergur, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this. Also, please provide the output of `flutter doctor -v` as well. Thank you!
