### ISSUE TITLE
Image Picker plugin [Android] feedback 

### ISSUE THREAD

**Issue by hugovangalen** [flutter/flutter#11577]
I ran into the following issues with the Image Picker plug-in on Android (for which an external library is used, com.github.esafirm.android-image-picker):

1. The hard-coded (incorrect) texts
It says "Tap to select images" while the only available mode is "single picture". (I noticed the iOS code also has hard-coded texts for the button labels.) Better would be if these options can all be passed along with the request, as these hard-coded texts are obviously totally wrong for the non-English speaking world. 
 
2. No access to device folders
The "native" image picker on Android presents a UI that gives access to other device folders. I do not see those folders with the plug-in.

3. No exposed method to "take a picture" only
In cases where taking an image is the direct action (i.e. from a button press in a GUI), it seems a bad user experience that they require an extra tap to actually take a picture. It would be nice if it can immediately drop into take-picture-mode.

4. Image output options
It would be very convenient to be able to  pass along any scaling options, so all this can be done native, rather than when receiving the full-sized image back in Flutter. Working with pixel data is slow in the VM.

**Comment by ride4sun** [comment]
I would like to add to that that the Image Picker should be extended to be a media picker and supports also videos not just images. That would keep both use cases consistent.
