### ISSUE TITLE
[flutter_localizations] doesn't understand plural and select in arb file

### ISSUE THREAD

**Issue by edeuss** [flutter/flutter#115731]
## Steps to Reproduce

1. Setup localization on base flutter create project
2. Execute `flutter run` on the code sample

**Expected results:** 

streamsF displays "1 stream"
streamsF2 displays "stream"

**Actual results:** 

streamsF displays "streams"
streamsF2 displays "streams"

Both work correcting using an ICU editor like https://devpal.co/icu-message-editor

<details>
<summary>Code sample</summary>

An example app with location setup.

```dart
import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:flutter_gen/gen_l10n/app_localizations.dart';


void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      localizationsDelegates: [
        AppLocalizations.delegate,
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
      ],
      supportedLocales: [
        Locale('en', ''),
      ],
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              AppLocalizations.of(context)!.streamsF(1),
            ),
          ],
        ),
      ),
    );
  }
}

```

app_en.arb:

```
{
"streamsF": "{count} {count, plural, zero{streams} one{stream} other{streams}}",
  "@streamsF": {
    "placeholders": {
      "count": {
        "type": "int",
        "example": "5"
      }
    }
  }
},
"streamsF2": "{count, plural, zero{streams} one{stream} other{streams}}",
  "@streamsF": {
    "placeholders": {
      "count": {
        "type": "int",
        "example": "5"
      }
    }
  },
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

[√] Flutter (Channel stable, 3.3.8, on Microsoft Windows [Version 10.0.22621.819], locale en-US)
    • Flutter version 3.3.8 on channel stable at C:\Users\Elias\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 52b3dc25f6 (12 days ago), 2022-11-09 12:09:26 +0800
    • Engine revision 857bd6b74c
    • Dart version 2.18.4
    • DevTools version 2.15.0

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\Elias\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.2.4)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.2.32602.215
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[√] VS Code (version 1.73.1)
    • VS Code at C:\Users\Elias\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.52.0

```
```

</details>

**Comment by asashour** [comment]
Would you mind posting your `flutter doctor -v`? And can you test with `master`?

There is a recent change in `master` channel, which should handle this case.

**Comment by edeuss** [comment]
@asashour I just tried switching to master, but I can't build, it gets stuck on ``Running "flutter pub get" in test...``. Can you currently build in master?

**Comment by asashour** [comment]
Yes, I am able to build a project with `master` (as of now).

**Comment by edeuss** [comment]
@asashour Ok restarted my pc, and seems to work in master. Do you know what commit fixed this issue and if it's in dev or beta by now?

**Comment by asashour** [comment]
Please see https://github.com/flutter/flutter/pull/112390

**Comment by edeuss** [comment]
@asashour Thank you!
