### ISSUE TITLE
Absurd

### ISSUE THREAD

**Issue by philmaker1** [flutter/flutter#11574]
It is completely absurd that a Dart WebGL runtime for Flutter does not exist. Dart used to have a major web intent. Publishing Flutter for the web would be more diverse. But Google doesn't really care about diversity.

**Comment by eseidelGoogle** [comment]
Thank you for the report.  I believe the issue you're looking for is https://github.com/flutter/flutter/issues/179.

We're currently more focused on 2d content and have no plans to add OpenGL bindings to Flutter as there are already great ways to share OpenGL code (e.g. C++) between iOS and Android.  As well as other more 3d-dedicated systems like Unity.

**Comment by philmaker1** [comment]
I continue to think that a Dart runtime ought to support the web. Otherwise, it's absurb. Was James Damore actually arrested for doing anything? Or was he just fired by Google?
