### ISSUE TITLE
[camera] Consider removing Guava dependency from cameraX WIP

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#115859]
See https://github.com/flutter/flutter/issues/115858 for context. Currently it's being used for ListenableFuture in this plugin. (/cc @camsim99)

**Comment by camsim99** [comment]
This plugin depends on gaining an instance of the `ProcessCameraProvider`, which requires using a `ListenableFuture`, see [`getInstance()`](https://developer.android.com/reference/androidx/camera/lifecycle/ProcessCameraProvider#getInstance(android.content.Context)). Closing for now as this will not be possible for the foreseeable future.
