### ISSUE TITLE
[pigeon] Add method to run pigeon with PigeonOptions

### ISSUE THREAD

**Issue by rotorgames** [flutter/flutter#115893]
## Use case
As an owner of the library which is using the pigeon library directly
I want to have the ability to call `Pigeon.run` method with a `PigeonOptions` argument. 

## Proposal
I suggest to add a new method into `Pigeon` class.

```dart
Future<int> runWithOptions(PigeonOptions options, {List<Generator>? generators, String? sdkPath})
```

That allows to everybody running the pigeon generator programmatically from their own libraries.

**Comment by tarrinneal** [comment]
Closing as complete as of https://github.com/flutter/packages/pull/2842
