### ISSUE TITLE
dart.io 'Platform' determining API seems to report incorrect platform when running a flutter integration test

### ISSUE THREAD

**Issue by iganev0886** [flutter/flutter#115823]
# Problem
Hi, I cannot execute an integration test using `flutter test` command on an Android device due to a third-party (AWS) component thinking that the test executes on an unsupported platform. Here is where the third-party component fails in test:
```
factory AmplifyClass() {
    if (zIsWeb || Platform.isWindows || Platform.isMacOS || Platform.isLinux) {
      throw UnsupportedError('This platform is not supported yet'); // test fails here
    }
    return MethodChannelAmplify();
  }
```
When running the integration test on an Android device, the AWS component thinks the test is being executed on a Windows platform instead of an Android. Citing from this [document](https://docs.flutter.dev/cookbook/testing/integration/introduction) the description for `flutter test`: "This command runs the app and integration tests on the target device". In that case, I would expect the Platform.isAndroid to be **true**, but instead, I am getting Platform.isWindows to be **true**. Look bellow.

## Steps to Reproduce
Platform: Windows 10

1. Create a simple Flutter project
2. Create an integration test file for Android using the official docs: https://docs.flutter.dev/cookbook/testing/integration/introduction
3. Edit the integration test file like so:
```
void main() {
  final IntegrationTestWidgetsFlutterBinding binding =
  IntegrationTestWidgetsFlutterBinding.ensureInitialized();

  print("Platform.isMacOS ${Platform.isMacOS}");
  print("Platform.isWindows ${Platform.isWindows}");
  print("Platform.isIOS ${Platform.isIOS}");
  print("Platform.isAndroid ${Platform.isAndroid}");
  print("Platform.isLinux ${Platform.isLinux}");
  ...
}
```
4. Connect an Android device
```
C:\>adb devices
List of devices attached
emulator-5554   device
``` 
5. Trigger the test
```
flutter test test\integration_test.dart -d emulator-5554
```

**Expected results:** 
```
Platform.isMacOS false
Platform.isWindows false
Platform.isIOS false
Platform.isAndroid true
Platform.isLinux false
```
**Actual results:** 
```
Platform.isMacOS false
Platform.isWindows true
Platform.isIOS false
Platform.isAndroid false
Platform.isLinux false
```

**Comment by darshankawar** [comment]
@iganev0886 
Currently, `integration_test` does not support detecting the platform of target device. There's an open issue for this https://github.com/flutter/flutter/issues/32927 in which you can follow-up on for updates and also upvote for team's attention.

Closing this as duplicate.
