### ISSUE TITLE
Let me pass in any/all flags to dart2js during flutter run/flutter build

### ISSUE THREAD

**Issue by kevmoo** [flutter/flutter#115854]
## Use case

* Specific control over the optimization level (`-OX`) for dart2js
* Ability to enable dump-info
* Ability to do a release build with `--no-minify`

## Proposal

Give me a catch-all arg to the flutter tool such as `--extra-dart2js-args` or similar

**Comment by mdebbar** [comment]
> * Ability to do a release build with `--no-minify`

Is this covered by the `profile` build? (i.e. `flutter build web --profile`)

**Comment by kevmoo** [comment]
@mdebbar some of them, yes. But it's super unclear which flags are used in which context. If I'm trying to do something specific, I'd rather just have the ability to provide them all myself.

Happy to have the flag hidden, etc.

**Comment by christopherfujino** [comment]
If we implement `--extra-dart2js-args`, we should consider what happens if the user provides a flag that the tool is already providing. In this case (where both the tool and `--extra-dart2js-args` are providing the same flag/option, should we fail, or should the explicit ones take precedence?
