### ISSUE TITLE
UI widget is buggy, some texture appear and disappears

### ISSUE THREAD

**Issue by LiangJie1-ola** [flutter/flutter#115816]
Hey, guys

I've found a bug with UI widgets as you see below:

(Please looking at the blue badge below the avatar of one girl, and there has a number label by its side)

<img width="144" alt="截屏2022-11-22 16 21 51" src="https://user-images.githubusercontent.com/113896135/203262229-d4f3587a-ae68-49a5-a895-d0296407ec18.png">

https://user-images.githubusercontent.com/113896135/203259769-21993811-b2c4-489f-9a18-117844e19dab.mov

Does flutter engine automatically free the texture and automatically load it again? 😂😂😂

And another guess is that there's some bug with the calculation of UI layout.

BTW, the counting number widget covers on the blue CSV formatted bg image.

```
[✓] Flutter (Channel stable, 3.3.4, on macOS 12.6 21G115 darwin-arm, locale zh-Hans-CN)
    • Flutter version 3.3.4 on channel stable at /Users/jakit/fvm/versions/3.3.4
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision eb6d86ee27 (7 weeks ago), 2022-10-04 22:31:45 -0700
    • Engine revision c08d7d5efc
    • Dart version 2.18.2
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/jakit/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] Connected device (3 available)
    • M2006C3LG (mobile) • MR6TKJEIC659TCGM • android-arm    • Android 10 (API 29)
    • macOS (desktop)    • macos            • darwin-arm64   • macOS 12.6 21G115 darwin-arm
    • Chrome (web)       • chrome           • web-javascript • Google Chrome 107.0.5304.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available
```

</details>

**Comment by huycozy** [comment]
Hi @LiangJie1-ola 

>(Please looking at the blue badge below the avatar of one girl, and there has a number label by its side)

I'm not sure I can see the issue here. Can you be more specific by clarifying `Actual result` and `Expected result`?

Also, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this. Thanks!
