### ISSUE TITLE
PR with new golden images failed to create a triage link which resulted in build breakage

### ISSUE THREAD

**Issue by flar** [flutter/flutter#115882]
https://github.com/flutter/flutter/pull/113673 introduces 2 new golden file tests. The golden images were included for reference for reviewers. The golden tests were run by the pre-submit tests.

But, flutter-gold did not hold up the PR, it went green without generating any triage links or waiting for the results to be triaged.

**Comment by flar** [comment]
A fresh reland of the changes also failed to produce any golden triage links: https://github.com/flutter/flutter/pull/115884

**Comment by flar** [comment]
The new reland PR also did not generate a triage link. Going to the Flutter golden dashboard, though, found a list of untriaged goldens to approve. So, the list of new goldens was registered with the system, the question is more why the pre-submit "flutter-golden" task failed to attach a comment pointing to the untriaged goldens and/or why it registered as a pass, allowing the PR to be landed?

**Comment by ricardoamador** [comment]
cc @Piinks can you please take a look at this?

**Comment by Piinks** [comment]
This issue is a year old, and I think it was resolved since it was not reported as recurring since then. There was recently some flakiness from Gold, but that is being tracked in https://github.com/flutter/flutter/issues/137177 so I think we can close this. Thank you!
