### ISSUE TITLE
Unresolved references when editing flutter android native plugin using Android studio.

### ISSUE THREAD

**Issue by wangmir** [flutter/flutter#115811]
I think it's quite old problem, but it still not resolved.

From this [link](https://docs.flutter.dev/development/packages-and-plugins/developing-packages#step-2b-add-android-platform-code-ktjava), we can see that Android plugin also can be editable using Android studio.

But, when I open the very initial android platform plugin project using Android studio.
Every reference under `io.flutter.*` are not resolved properly.

It was always same so I temporally add dependencies on the android build.gradle when implementing Android part of the plugin like,

```gradle
group 'com.example.ar_sceneview_plugin'
version '1.0-SNAPSHOT'

buildscript {
    ext.kotlin_version = '1.6.10'
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:7.1.2'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        maven {
            url 'http://download.flutter.io'
            allowInsecureProtocol=true
        }
    }
}

apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'

android {
    compileSdkVersion 31

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        minSdkVersion 16
    }
}

dependencies {
    // temporal dependency, please comment out when building flutter app.
    api "io.flutter:flutter_embedding_debug:1.0.0-f16e757d5d68c164d084b61d84e3b7cd14eacba9"
}
```

and it works, but I think it's not proper way to handle this problem.
Is there any references to edit android plugin in right way?

## Steps to Reproduce
1. `flutter create --platform=android --template=plugin plugin_test`
2. Open android project using Android studio at the path of `plugin_test/android/build.gradle`

**Expected results:** 
There are no unresolved references.

**Actual results:** 

Every flutter related references (FlutterPlugin, MethodCallHandler, MethodChannel, etc.) are shown as unresolved references.
![image](https://user-images.githubusercontent.com/6769075/203220255-b9d42b51-c196-4639-a48e-f70cc7086e1e.png)

**Comment by danagbemava-nc** [comment]
Hi @wangmir, according to the documentation, you should open the `plugin_test/example/android/build.gradle` instead of
`plugin_test/android/build.gradle`. 

See 
![Screenshot 2022-11-22 at 09 29 16](https://user-images.githubusercontent.com/88313112/203277463-d6ad0142-bdf5-4c6a-8ad8-57861bcb4adc.png)

You should be able to edit the plugin files without any issue when you open the `plugin_test/example/android/build.gradle`.  See that there are no issues below. 

<img width="500" alt="Screenshot 2022-11-22 at 09 31 51" src="https://user-images.githubusercontent.com/88313112/203278031-a59866fb-f427-4672-a711-8ced8e89a332.png">

Does this help?

**Comment by wangmir** [comment]
> Hi @wangmir, according to the documentation, you should open the `plugin_test/example/android/build.gradle` instead of `plugin_test/android/build.gradle`.
> 
> See ![Screenshot 2022-11-22 at 09 29 16](https://user-images.githubusercontent.com/88313112/203277463-d6ad0142-bdf5-4c6a-8ad8-57861bcb4adc.png)
> 
> You should be able to edit the plugin files without any issue when you open the `plugin_test/example/android/build.gradle`. See that there are no issues below.
> 
> <img alt="Screenshot 2022-11-22 at 09 31 51" width="500" src="https://user-images.githubusercontent.com/88313112/203278031-a59866fb-f427-4672-a711-8ced8e89a332.png">
> 
> Does this help?

Oh, thanks, it works :)
