### ISSUE TITLE
Describe how `alignment` work on DecorationImage

### ISSUE THREAD

**Issue by chrsfang** [flutter/flutter#11589]
## Issue

I'm using `DecorationImage` with `FractionalOffset` to crop a piece of image from my PNG file but the result seems to be shifted from the original pixels.

The original image is 100*800 resolution with each color block of size 100 * 50. The code is trying to crop each color block from the picture asset but it had some alignment problem.

The `devicePixelRatio` on my test emulator is 1.5 and the offset seems to be right after
 `offset = offset * 1.006`
which doesn't seem to be directly related to the devicePixelRatio

## Code

```dart
class PNGReaderState extends State<PNGReader>{
  double _blockWidth = 100.0;
  double _blockHeight = 50.0;
  double _stripWidth = 100.0;
  double _stripHeight = 800.0;
  final _blockOffsets = [
    0.0,
    50.0,
    100.0,
    150.0,
    200.0,
    250.0,
    300.0,
    350.0,
    400.0,
    450.0,
    500.0,
    550.0,
    600.0,
    650.0,
    700.0,
    750.0
  ];

 Widget _colorBlock(double offset) {
    return new Column(
      children: <Widget>[
        new Divider(
          height: 8.0,
        ),
        new Container(
          width: _blockWidth,
          height: _blockHeight,
          decoration: new BoxDecoration(
            image: new DecorationImage(
              fit: BoxFit.none,
              alignment: new FractionalOffset.fromOffsetAndSize(
                new Offset(
                  0.0,
                  offset,
                ),
                new Size(
                  _stripWidth,
                  _stripHeight,
                ),
              ),
              image: new Image.asset('images/test.png').image,
            ),
          ),
        )
      ],
    );
  }

  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(
        title: new Text('Test'),
      ),
      body: new ListView(
        children: _blockOffsets
            .map((offset) => _colorBlock(offset))
            .toList(),
      ),
    );
  }
}
```

## Images
Result after cropping image
![Image of emulator](https://i.stack.imgur.com/zMb46.png)
Original Image
![Image of color strip](https://i.stack.imgur.com/KWYJY.png)

**Comment by eseidelGoogle** [comment]
@Hixie or @jason-simmons  might know our rounding rules.

**Comment by Hixie** [comment]
Pretty sure this is just `alignment` not working quite as expected (the docs aren't super clear on what we intended). If you want to extract images in this way, you should probably use Canvas.drawImageRect directly.

**Comment by chrsfang** [comment]
Thanks. I'll give it a try

**Comment by Hixie** [comment]
@chrsfang Any luck?

**Comment by chrsfang** [comment]
@Hixie Canvas.drawImageRect works well for me. 
Thanks.

**Comment by Hixie** [comment]
Cool. I'll change this bug to be documentation to explain how `alignment` works and ideally specifically why it doesn't have the effect you expected here.

**Comment by ricardo-lemes** [comment]
> Tenho certeza de que isso `alignment`não está funcionando como esperado (os documentos não são muito claros sobre o que pretendíamos). Se você deseja extrair imagens dessa maneira, provavelmente deve usar o Canvas.drawImageRect diretamente.



> Pretty sure this is just `alignment` not working quite as expected (the docs aren't super clear on what we intended). If you want to extract images in this way, you should probably use Canvas.drawImageRect directly.

Can someone show an example of Canvas.drawImageRect

**Comment by ricardo-lemes** [comment]
I want to do the same thing with an image

**Comment by zoechi** [comment]
@ricardo-lemes check https://github.com/flutter/flutter/issues?utf8=%E2%9C%93&q=is%3Aissue++drawimagerect+

**Comment by ricardo-lemes** [comment]
I want to position in pixels an image inside a box or in a rectangle

**Comment by zoechi** [comment]
@ricardo-lemes Please consider asking support questions in one of the other channels listed at http://flutter.io/support .
