### ISSUE TITLE
Would like a libphonenumber plugin

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#11583]
Posse notes that it would be nice to have a libphonenumber plugin for flutter: https://github.com/googlei18n/libphonenumber

Our team specifically doesn't have to write one, but given that it's a Google-authored project, we're likely to end up with Google-authored libphonenumber flutter plugin at some point (even if there are also others).

I'm not aware of any other customers requesting this yet.

**Comment by eseidelGoogle** [comment]
The specific use case Posse is seeking to solve is simply formatting an international phone number correctly in their form field.

**Comment by Hixie** [comment]
We have no plans to do this any time soon. Maybe the libphonenumber team could offer this?

**Comment by rogchap** [comment]
I'm currently porting a React Native app to Flutter, and I use the JS version of libphonenumber for RN.

Would this plugin be specifically for Flutter or more of a port to dartlang?

What do you see as the requirements for this plugin?

Ps. I possibly could work on this plugin if I know some of the requirements.

Would a Plaftorm Channel be another approach?

My use case is for login via Phone Number and SMS sent code.

**Comment by assafsl** [comment]
It would be great to have a dart port rather than depending on native implementations

**Comment by f-person** [comment]
Right now there is a wrapper for the native implementation – https://pub.dev/packages/flutter_libphonenumber and a WIP Dart port – https://pub.dev/packages/libphonenumber.

**Comment by stuartmorgan** [comment]
It doesn't seem that there's a compelling need for the Flutter team to do this, given the existence of the packages referenced above.
