### ISSUE TITLE
FileSystemException: Directory listing failed OS Error: Invalid argument, errno = 22

### ISSUE THREAD

**Issue by chaudharydeepanshu** [flutter/flutter#115857]
I have been getting a repetitive error in crashlytics dashboard for my app but I'm unable to find the source for that as it was a very vague error.

Error:-
```
Fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: FileSystemException: Directory listing failed, path = 
'/data/user/0/com.pureinfoapps.android.apps.filestools/cache/' (OS Error: Invalid argument, errno = 22). Error thrown null.
       at FirebaseCrashlytics.recordError(firebase_crashlytics.dart:119)
       at main.<fn>(main.dart:47)
```

What does this errno=22 mean as I didn't find anything about it through searching the google.

Also, it seems that this happens only with Nexus 5X. Maybe google systems used that device to test my app?
Attaching a screenshot of crashlytics dashboard below:
![image](https://user-images.githubusercontent.com/85361211/203417763-3fb7f84a-fa3a-462e-b34c-15814ba4bbce.png)

If anyone has an idea about that then please let me know as I don't know if it is a real issue or not.

Also, link to the [app](https://play.google.com/store/apps/details?id=com.pureinfoapps.android.apps.filestools) and [repository](https://github.com/chaudharydeepanshu/files_tools) if interested in testing manually.

**Comment by exaby73** [comment]
Hello @chaudharydeepanshu. Could you check if this error occurs due to insufficient permissons? For example: if your app is trying to list a directory when the user has denied permissions

**Comment by brightseagit** [comment]
@exaby73 The error shows that issue comes when "directory listing the cache path" of the app which never needs any permission.

Also, the app requires no permission as it uses Storage Access Framework and SAF mechanism doesn't require any system permissions.

**Comment by exaby73** [comment]
Is it possible for you to provide a [complete and minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)? There isn't enough to go on here to investigate the issue further

**Comment by chaudharydeepanshu** [comment]
@exaby73 I wish I could, but I can only see this error in crashlytics of my production app as all my physical and virtual devices don't show any error on any android version. 

Here I'm attaching a snippet of code which might be the reason for the issue:-
```dart
Future<void> clearCache() async {
  Directory directory = await getTemporaryDirectory();
  final List<FileSystemEntity> entities = await directory.list().toList();        //<---------------------- Maybe the reason
  for (var entity in entities) {
    if (entity.existsSync()) {
      entity.deleteSync(recursive: true);
    }
  }
}
```

**Comment by exaby73** [comment]
This issue is not reproducible by me. There isn't much to go on here but maybe someone on the team has some insights that could help. Therefore, I am labeling this issue for visibility

**Comment by chaudharydeepanshu** [comment]
Update:

Just got this crash on a new device named GCE x86 phone.

**Comment by Hixie** [comment]
Error 22 seems to be EINVAL (Invalid Argument). No idea why you would be getting it though.

Without a way to reproduce it it is very unlikely that we'll be able to track this down though.

**Comment by chaudharydeepanshu** [comment]
Yeah, I get what you are saying.

Still, no problem, as I have only seen the above two devices in the logs of that error and both of them appear to be rooted so maybe it's just an issue with how google is testing the app. 

But also, I have been making some changes in the recent new versions and then tracking their results to see if something helps. And if I find something I will let others about it here.

**Comment by reidbaker** [comment]
If you can get a repro please let us know.

**Comment by ksilz** [comment]
I'm also getting this error after I submitted my Flutter app to the Play Store. The device that triggers it is a "Nexus 5X with Android 6.0.1". I guess this is a simulator or testing device that Google runs? I don't see this error in the wild.

```
Fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError
FileSystemException: Directory listing failed, path = '/data/user/0/com.yourhomeingoodhands.mobile.yhigh/app_flutter/issues/' (OS Error: Invalid argument, errno = 22). Error thrown Instance of 'VK'.
```

**Comment by exaby73** [comment]
@ksilz Have you tried running a local emulator with the same Android versions and trying to reproduce it with a minimal example?
