### ISSUE TITLE
Remove "Building with sound null safety" output during `run` and `build`

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#115803]
I think we should keep the `Building without sound null safety ⚠` scold until dart is ready, but can we remove the congratulatory  `💪 Building with sound null safety 💪` line on every build/run now?  Once you're building with sound null safety it's noise that distracts from actual errors.

> The emojis about null safety also took some attention away from me, which I'm not sure if it's necessary any more, since most Flutter projects are null safe at this point?  

_Originally posted by @InMatrix in https://github.com/flutter/flutter/issues/114841#issuecomment-1315920245_

**Comment by jmagman** [comment]
cc @mit-mit

**Comment by mit-mit** [comment]
I think I'd prefer to not make any changes to this the next few weeks, and then simply remove all of the null safety messages after the branch cut in a few weeks?

**Comment by jmagman** [comment]
If that's the timeline, works for me.  

> then simply remove all of the null safety messages after the branch cut in a few weeks?

Do you want a bug to track that?

**Comment by mit-mit** [comment]
I think we can just use the present bug? I linked it from https://github.com/dart-lang/sdk/issues/49530

**Comment by goderbauer** [comment]
Somewhat related: Does the tool produce a good and actionable error message when someone tries to build/run their non-null-safe app now that we're removing support for it?

**Comment by christopherfujino** [comment]
> Somewhat related: Does the tool produce a good and actionable error message when someone tries to build/run their non-null-safe app now that we're removing support for it?

[This](https://github.com/flutter/flutter/pull/118491) ensures today we fail and tell them about the soon to be deprecated `--no-sound-null-safety` flag. When I rip that flag out, I'll make sure to also include a helpful message.

**Comment by mit-mit** [comment]
PR in https://github.com/flutter/flutter/pull/120350
