### ISSUE TITLE
When we upgrade from downgraded plan, Then the both plan elite and basic are showing active. 

### ISSUE THREAD

**Issue by GujjuFlutterGuy** [flutter/flutter#115835]
Let's take a test case here.

I have two plan 
1. Elite
2. Basic

I am purchasing first Elite and then downgrading to the Basic plan. Until here it works fine.
Now I am again upgrading to the Elite plan from the Basic plan. So now the issue Is happening, That both the plans are showing active on the play store. 

Expected result here: only the new plan should show in the play store, not both.

Please see the image below. 

<img src="https://user-images.githubusercontent.com/24433003/203336558-4f124a99-7c29-4828-b80e-cd4df8904ae5.jpg" width="300" />

**Comment by GujjuFlutterGuy** [comment]
@TahaTesser

**Comment by danagbemava-nc** [comment]
Hi @GujjuFlutterGuy, 

Can you please provide your `flutter doctor -v` and the code that you use to handle your iaps? 

Please also provide the versions of `in_app_purchase` & `in_app_purchase_android` that you're using. 

Thank you

**Comment by GujjuFlutterGuy** [comment]
Sure providing. But I got a problem when I do the downgrade and then do the upgrading that time in `changeSubscriptionParam` old subscription data is not passing there, I am getting null there. So that's what I am debugging, Why the old subscription is not coming?

@danagbemava-nc Providing the details

**Comment by GujjuFlutterGuy** [comment]
flutter doctor -v

> [✓] Flutter (Channel stable, 3.3.4, on macOS 12.5.1 21G83 darwin-arm (Rosetta), locale en-IN)
>     • Flutter version 3.3.4 on channel stable at /Users/mac-mini-6/Documents/Flutter_sdk/flutter
>     • Upstream repository https://github.com/flutter/flutter.git
>     • Framework revision eb6d86ee27 (7 weeks ago), 2022-10-04 22:31:45 -0700
>     • Engine revision c08d7d5efc
>     • Dart version 2.18.2
>     • DevTools version 2.15.0
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
>     • Android SDK at /Users/mac-mini-6/Library/Android/sdk
>     • Platform android-33, build-tools 33.0.0
>     • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
>     • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
>     • All Android licenses accepted.
> 
> [✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • Build 13F100
>     • CocoaPods version 1.11.3
> 
> [✓] Chrome - develop for the web
>     • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
> 
> [✓] Android Studio (version 2021.2)
>     • Android Studio at /Applications/Android Studio.app/Contents
>     • Flutter plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/9212-flutter
>     • Dart plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/6351-dart
>     • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
> 
> [✓] VS Code (version 1.67.2)
>     • VS Code at /Users/mac-mini-6/Downloads/Visual Studio Code.app/Contents
>     • Flutter extension can be installed from:
>       🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
> 
> [✓] Connected device (3 available)
>     • Redmi Note 6 Pro (mobile) • IP_ADD • android-arm64  • Android 9 (API 28)
>     • macOS (desktop)           • macos             • darwin-arm64   • macOS 12.5.1 21G83 darwin-arm (Rosetta)
>     • Chrome (web)              • chrome            • web-javascript • Google Chrome 107.0.5304.110
> 
> [✓] HTTP Host Availability
>     • All required HTTP hosts are available

Code that I used.

```
if (Platform.isAndroid) {
      final oldSubscription = _getOldSubscription(prod, purchases);
      purchaseParam = GooglePlayPurchaseParam(
          productDetails: prod,
          applicationUserName: userId,
          changeSubscriptionParam: oldSubscription != null && isSubscribed
              ? ChangeSubscriptionParam(
                  oldPurchaseDetails: oldSubscription,
                  prorationMode: ProrationMode.immediateAndChargeProratedPrice)
              : null);
    }

```

 ```
GooglePlayPurchaseDetails? _getOldSubscription(
      ProductDetails productDetails, Map<String, PurchaseDetails> purchases) {
    GooglePlayPurchaseDetails? oldSubscription;

    if (purchases.isNotEmpty) {
      if (productDetails.id == provider.prod_Basic &&
          purchases[provider.prod_Elite] != null) {
        oldSubscription =
            purchases[provider.prod_Elite] as GooglePlayPurchaseDetails;
      } else if (productDetails.id == provider.prod_Elite &&
          purchases[provider.prod_Basic] != null) {
        oldSubscription =
            purchases[provider.prod_Basic] as GooglePlayPurchaseDetails;
      }
    }
    LogHelper.logInfo(
        stackTrace: StackTrace.current,
        "oldSubscription:- ${oldSubscription?.productID}");
    return oldSubscription;
  }
```

> in_app_purchase - 3.0.8

> in_app_purchase_android - 3.0.2


Again I am stuck on that how can get past subscription data so I can attach it to changeSubscriptionParam. Let me know @danagbemava-nc If you can help me out from this.

**Comment by danagbemava-nc** [comment]
Hi @GujjuFlutterGuy, there's a comment in the example app regarding making subscriptions in android. See 

https://github.com/flutter/plugins/blob/e911e0564f89e75babcbd43d8531bbcd13b85868/packages/in_app_purchase/in_app_purchase/example/lib/main.dart#L277-L280. 

Have you tried setting up a server to do the validation as recommended?

**Comment by GujjuFlutterGuy** [comment]
Yes, we have our server to verify the purchases.

**Comment by danagbemava-nc** [comment]
Hi @GujjuFlutterGuy, can you share some logs as you walk through the steps you have outlined to reproduce the issue? A screen recording capturing the issue would also be helpful. 
I'm experiencing some issues with iap and the moment so I cannot verify this locally.
