### ISSUE TITLE
Flutter • channel unknown • unknown source

### ISSUE THREAD

**Issue by RockyScube** [flutter/flutter#115814]
It seems to me like the git repo in your flutter install is corrupted (when you issue the `flutter` command, it issues the command `git rev-parse HEAD`, which should work in a valid git repository). Can you paste the output of `git status` and `git rev-parse HEAD` in your flutter install?

_Originally posted by @christopherfujino in https://github.com/flutter/flutter/issues/31767#issuecomment-577439348_

I've tried this command and it gave following output:
**git status **
On branch stable

No commits yet

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        .gitignore
        AUTHORS
        CODEOWNERS
        CODE_OF_CONDUCT.md
        CONTRIBUTING.md
        LICENSE
        README.md
        analysis_options.yaml
        bin/
        dartdoc_options.yaml
        dev/
        examples/
        packages/

**git rev-parse HEAD**
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
HEAD

**Comment by huycozy** [comment]
Hi @RockyScube 
Below is the output of flutter stable `3.3.8` from my end:

```
➜  flutter git:(stable) git status
On branch stable
Your branch is up to date with 'origin/stable'.

nothing to commit, working tree clean
➜  flutter git:(stable) git rev-parse HEAD
52b3dc25f6471c27b2144594abb11c741cb88f57
```

What Flutter version are you facing this issue with? Can you provide the output of `flutter doctor -v`?

**Comment by RockyScube** [comment]
For version `2.7.0` I was facing this issue. I deleted my directory and now using latest stable version so I cannot recreate it.
