### ISSUE TITLE
Improve `Finder` APIs

### ISSUE THREAD

**Issue by bartekpacia** [flutter/flutter#115874]
I don't know why the original creators of Flutter's test framework designed it the way it is designed, and I'm not blaming them in any way – they did a really great job at making testing feel like a first-class citizen in Flutter. I do like writing tests in Flutter :)

That said, I think there's some room for improvement.

# The problem

I think that `Finder` coalescing the "representation of what to search for" and the "result of performing that search" into a single concept has a few nasty consequences. I'll do my best to explain them below.

> I was wondering if I should've split this issue into a few separate ones, but I decided not to because I think that they share a common cause.

### First example (1 widget found)

When I called `Finder.toString()` for the first time in my short life, I expected it to print _what the finder searches for_, not _what it found_. Here's an example:

```dart
testWidgets("Prints finder's description", (WidgetTester tester) async {
  await tester.pumpWidget(
    const MaterialApp(home: Center(child: Text('Hello World'))),
  );
  final finder = find.text('Hello World');
  print(finder.toString());
});
```

**Actual output**

_exactly one widget with text "Hello World" (ignoring offstage widgets): Text("Hello World", dependencies: [DefaultSelectionStyle, DefaultTextStyle, MediaQuery])_

I created a Finder and want to print it, but it's already searched the widget tree and now is printing what it found? 

BTW, why so fast? I didn't even ask it to _find_. Take your time, you finder guy.

**Better output**

_widgets with text "Hello World" (ignoring offstage widgets)_

I want to print what the finder intends to find, not what it's already found. 

**Even better output**

Since offstage widgets are ignored by default, I don't think it makes sense to include this info in the `toString()`'s output. It should only be present if `skipOffstage` was set to `false`. So the perfect output of `toString()` would be:

_widgets with text "Hello World"_

PS It'd be nice to rename `skipOffstage` to `includeOffstage` and change the default value to `false`, to be consistent with Flutter's Dart code style. See also [this comment](https://github.com/flutter/flutter/pull/87197#discussion_r682136898).

**Why does it matter**

An example use case is described in [this GitHub Discussion](https://github.com/leancodepl/patrol/discussions/528).

Also, there's no way to currently print only _what the finder searches for_, without all the noise.

### Second example (>1 widgets found)

The more widgets the finder finds, the more cluttered the output becomes.

```dart
testWidgets("Prints finder's description 2", (WidgetTester tester) async {
  await tester.pumpWidget(
    MaterialApp(
      home: Center(
        child: Column(
          children: const [
            Text('Hello World'),
            Text('Hello World'),
          ],
        ),
      ),
    ),
  );
  final finder = find.text('Hello World');
  print(finder.toString());
});
```

**Actual output**

_2 widgets with text "Hello World" (ignoring offstage widgets): [Text("Hello World", dependencies: [DefaultSelectionStyle, DefaultTextStyle, MediaQuery]), Text("Hello World", dependencies: [DefaultSelectionStyle, DefaultTextStyle, MediaQuery])]_

**Better output**

_widgets with text "Hello World"_

### Third example (no widgets found)

And when the finder doesn't find any widgets, the output reads awkwardly.

```dart
testWidgets('Finder.toString() 3', (WidgetTester tester) async {
  await tester.pumpWidget(const MaterialApp());
  final finder = find.text('Hello World');
  print(finder.toString());
});
```

**Actual output**

_zero widgets with text "Hello World" (ignoring offstage widgets)_

**Better output**

_widgets with text "Hello World"_

Instead of changing `toString()` behavior, we could create a new abstract method `Finder.toRepresentation()` (inspired by [Python's repr()](https://docs.python.org/3/library/functions.html#repr)), and make all the other finders override it.

## `Finder.at()`

Let's consider the below code:

```dart
testWidgets('Finder.at() + Finder.toString() 3', (WidgetTester tester) async {
  await tester.pumpWidget(const MaterialApp());
  final finder = find.text('Hello World').at(0);
  print(finder.toString());
});
```

**Actual result**

A nasty exception is thrown:

```
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following IndexError was thrown running a test:
RangeError (index): Index out of range: no indices are valid: 0

When the exception was thrown, this was the stack:
#0      Iterable.elementAt (dart:core/iterable.dart:781:5)
#1      _IndexFinder.filter (package:flutter_test/src/finders.dart:624:28)
#3      new _GrowableList._ofOther (dart:core-patch/growable_array.dart:202:26)
#4      new _GrowableList.of (dart:core-patch/growable_array.dart:152:26)
#5      new List.of (dart:core-patch/array_patch.dart:51:28)
#6      Iterable.toList (dart:core/iterable.dart:470:12)
#7      Finder.toString (package:flutter_test/src/finders.dart:552:46)
#8      main.<anonymous closure> (file:///Users/bartek/dev/random/flutter_what_are_finders/test/widget_test.dart:57:18)
<asynchronous suspension>
<asynchronous suspension>
(elided 2 frames from dart:async-patch and package:stack_trace)

The test description was:
  Finder.at() + Finder.toString() 3
```

I've seen testers and developers encounter this problem and become confused.

**Result that would be better**

Let's see the docs for the [Finder.at()](https://api.flutter.dev/flutter/flutter_test/Finder/at.html) method:

```
(int index) → Finder

Returns a variant of this finder that only matches the element at the given index matched by this finder.
```

After reading the above, I'd expect the above test case to throw a:

```
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure was thrown running a test:
Expected: exactly one matching node in the widget tree
  Actual: _TextFinder:<zero widgets with text "1" (ignoring offstage widgets)>
   Which: means none were found but one was expected
```

but instead, it throws a `StateError`, as shown above.

**The best result**

_widget with text "Hello World" at index 0_, or even better: _first widget with text "Hello World"_

# Conclusion

- At the very last, docs of the [Finder class](https://api.flutter.dev/flutter/flutter_test/Finder-class.html) should explain _what is a finder_, not only that "it finds".
- [Finder.toString()](https://api.flutter.dev/flutter/flutter_test/Finder/toString.html) calling [Finder.evaluate()](https://api.flutter.dev/flutter/flutter_test/Finder/evaluate.html) is a bad idea.
- Flutter's test framework should differentiate between 2 (related but distinct) concepts: _the finder itself_ and _the finder's result_.
  Speaking more technically, it means:
  1. Making the [Finder](https://api.flutter.dev/flutter/flutter_test/Finder-class.html) class represent _only a finder_ (i.e what to search for in the widget tree)
  2. Creating a new `EvaluatedFinder` class containing _what the finder found_
  3. Making `Finder.evaluate` return `EvaluatedFinder`

  I realize that the last bullet point is a _huge suggestion_ - it would most certainly be a breaking change, and I'm not sure if the benefits I listed above outweigh the migration pain. I'll try to explore this in a paragraph below.

## Exploring `Finder` and `EvaluatedFinder`

[WidgetTester.tap()](https://api.flutter.dev/flutter/flutter_test/WidgetController/tap.html), [WidgetTester.enterText()](https://api.flutter.dev/flutter/flutter_test/WidgetTester/enterText.html) (and some friends) would require `EvaluatedFinder` as the first argument (instead of `Finder`).

Widget matchers (see: [matchers.dart](https://github.com/flutter/flutter/blob/master/packages/flutter_test/lib/src/matchers.dart)), such as `_FindsWidgetMatcher.matches()` would require `EvaluatedFinder` as the second argument (instead of `Finder`).

Here's an example test written using that imagined API:

```dart
testWidgets('increments count by 1', (WidgetTester tester) async {
  var count = 0;
  await tester.pumpWidget(
    MaterialApp(
      home: StatefulBuilder(
        builder: (state, setState) => Column(
          children: [
            Text('count: $count'),
            GestureDetector(
              onTap: () => setState(() => count+=5),
              child: const Text('Tap'),
            ),
            GestureDetector(
              onTap: () => setState(() => count++),
              child: const Text('Tap'),
            ),
          ],
        ),
      ),
    ),
  );

  final tapFinder = find.text("Tap");
  final tapFinderResult = tapFinder.evaluate().at(1);
  await tester.tap(tapFinderResult).tap();

  await tester.pumpAndSettle();

  final countFinder = find.text("count: 1");
  expect(countFinder.evaluate()), findsOneWidget);
});
```

It's a bit more clunky, but that's the price to be paid for separating a finder from its result. 

> I low-key think that this slightly more clunky (but mapping the problem space better) finder system should've been provided by Flutter by default, and then the current "fluent" finder system could be provided as a separate package.

### Alternative

If we don't want to break thousands of projects with millions of tests, we could take an alternative approach. The _new finder system_ would be provided as a separate package, say, `flutter_test_plus`. Since the core `flutter` package is independent of `flutter_test`, I don't see why a third party wouldn't be able to, purely technically speaking, provide such a finder system.

See also:
- https://github.com/leancodepl/patrol/issues/602
- https://github.com/leancodepl/patrol/issues/548
- https://github.com/leancodepl/patrol/discussions/528

**Comment by exaby73** [comment]
Hello @bartekpacia. Thank you for filing this very detailed proposal :) One point I personally disagree on is to keep this issue as one. I think the issue can be split into separate issues. Yes they are related, but conceptually, they are different issues altogether. Specifically, I think the following sections can be separate issues:

- `Finder.toString` should have an improved output. Though I do not think this is valid on it's own since this would cause some data to be lost. I guess the solution to this would be your proposal for `EvaluatedFinder`.
- `Finder.at` throws a `StateError`. Though, I do not think this is a valid one. I think you should have an `expect` with `findsOneWidget` before you do `Finder.at` here. This would solve your issue as well as having your code explain better what is expected in the widget tree.
- The `EvaluatedFinder` proposal, along with the suggestions for the `plus` package you mentioned. Though I am not sure how this would pan out since the `plus` packages are maintained by the community, and not the Flutter team.

All in all, this looks like a valid proposal to me, but I would love some insights from the team on this. I'm sure you do too. I am labeling this issue for visibility and further discussion. Thank you

**Comment by bartekpacia** [comment]
@exaby73, thanks for reviewing this issue! :)

I agree with you that this is quite massive and should be split. It's just that I'd like first to get some response from somebody on the team – what they think about the current Finder API, is it possible to address the problems I mentioned without breaking changes, and what they think about the `EvaluatedFinder` proposal. 

I'll be happy to create smaller, more focused issues after some Google engineer agrees that are indeed issues and should be solved somehow :) I also don't really have time to break them down – writing this big one already took quite a while. I'm sorry about this and I hope this is not a big problem!

**Comment by pdblasi-google** [comment]
@bartekpacia

As part of #123634, I'm introducing a generic base class for Finders so we can have consistent ways to interact with finders for both Elements and SemanticsNodes (and possibly other things in the future). While I was doing that, I remembered this ticket and I think it'd be a good chance to address the concerns here while minimizing breaking changes.

To summarize the proposal, I think the major concern to be addressed is to separate the concept of a "finder" with the concept of what is found. From there, most of the other concerns here fall away, except the issues with `at`, `first`, and `last`, which I think can be addressed separately, with at least some improved output if not a behavioral change.

Here's what I'm thinking:

1. Introduce `FinderBase<TCandidate>`
    * This is technically more for #123634, but it also gives us a clean place to break the API per our deprecation process with minimal impact
    * This will be the thing that "finds", and will not report on the results itself
    * Terminology in this class will also be more consistent with "finding", with members such as "find", "tryFind", and "found"
2. Introduce `FinderResult<TCandidate>`
    * This is an analog to your `EvaluatedFinder` proposal
    * To further minimize impact this will also `implement Iterable<TCandidate>` allowing it to be treated as a basic iterable when additional functionality isn't needed
    * This will report on the results of the finder, basically what `Finder` does now when you call `toString`.
3. Introduce `ElementFinder` as the new root base class for currently implemented `Finder`s.
    * This'll include the change to `includeOffstage`, and the updated `toString` method that doesn't evaluate anything

Lastly, we'll mark `Finder` as deprecated and drive users to use the `ElementFinder` class instead. After the deprecation window `Finder` will be removed, resulting in a clean break with the new polished API.

That's my plan so far, but I'd like to hear any feedback you have and I'll ping you in the PR when there's code available to review as well. Let me know what you think!

**Comment by passsy** [comment]
I love that the finder API got some improvements while staying backward compatible.

I myself created [spot](https://github.com/passsy/spot), an alternative finder API, which contained the new additions added by @pdblasi-google from the very beginning. And has many more features like chained finders and useful error messages.

```dart
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:spot/spot.dart';

void main() {
  testWidgets('Widget test with spot', (tester) async {
    // Create widget selectors for elements in the widget tree
    final scaffold = spot<MaterialApp>().spot<Scaffold>();
    final appBar = scaffold.spot<AppBar>();
    
    // Assert for values of widgets
    appBar.spot<Text>().existsOnce().hasText('Pepe');
    
    // Find widgets based on child widgets
    appBar
        .spot<IconButton>(children: [spotSingleIcon(Icons.home)])
        .existsOnce()
        .hasTooltip('home');

    // Find widgets based on parent widgets
    spot<Icon>(parents: [appBar, spot<IconButton>()])
        .existsExactlyNTimes(2)
        .all((icon) {
      icon.hasColorWhere((color) => color.equals(Colors.black));
    });

    // Interact with widgets using `act`
    final button = spotSingle<FloatingActionButton>();
    act.tap(button);
  });
}
```
