### ISSUE TITLE
Offer a caching HTTP client

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#11595]
We currently lack an HTTP client that respects cache headers ([rfc1](https://tools.ietf.org/html/rfc7234), [rfc2](https://tools.ietf.org/html/rfc5861), [rfc3](https://tools.ietf.org/html/rfc7232), maybe more). This creates a less-than-ideal situation for network image loading. We should offer a solution.

Some options:

- write our own on top of `dart:io` sockets
- wrap native [Android](https://developer.android.com/reference/android/net/http/HttpResponseCache.html) and [iOS](https://developer.apple.com/documentation/foundation/urlcache) clients as a plugin
- reuse the one from Blink

/cc @eseidelGoogle

**Comment by eseidelGoogle** [comment]
FYI @zanderso @dgrove in case either have thoughts.

**Comment by zanderso** [comment]
Extending `dart:io`'s HttpClient is also an option, but my preference would be to delay adding more features to it until we pull it out of `dart:io` into a package.

**Comment by Hixie** [comment]
My understand is that this will be resolved in due course by package:http, or layers above or below it.

I don't think Flutter itself should attempt to solve this problem as a first-party solution.

**Comment by p30arena** [comment]
@Hixie @eseidelGoogle 
Whats the status of this issue?

I saw the new http package, but couldn't find the docs about caching.
[flutter - proper way of keep alive connections and connection pooling and caching?](https://github.com/dart-lang/http/issues/209)

**Comment by Hixie** [comment]
I recommend filing a bug on Dart or on package:http. As per my comment above, I don't think Flutter itself should attempt to solve this problem as a first-party solution.

**Comment by yjbanov** [comment]
The reason I filed it here is because I thought good HTTP is critical to Flutter app developers. However, if we have reasons to believe that this is fixable in a third-party package, or we do not believe that it's critical to have, that's OK too.

**Comment by p30arena** [comment]
@Hixie @yjbanov @jonahwilliams 

Yes a fast and feature rich HTTP library is critical,
We also need more flexible Image caching,

I hesitate to write my own ImageCache https://github.com/flutter/flutter/issues/13616 for disk caching, because I think this must be handled by developers who can pay enough time and attention to its quality, and this is greatly possible for the flutter's core dev team.

BTW, I think you can help for a faster response from package:http guys by providing better details to and endorsing this issue:
https://github.com/dart-lang/http/issues/209

**Comment by p30arena** [comment]
Unexpected HTTP Caching on Real Devices but not on Emulator
https://github.com/dart-lang/sdk/issues/34966

**Comment by brianquinlan** [comment]
[`package:cupertino_http`](https://pub.dev/packages/cupertino_http) (iOS/macOS), [`package:cronet_http`](https://pub.dev/packages/cronet_http) (Android) and [`package:fetch_client`](https://pub.dev/documentation/fetch_client) (web) offer configurable caching using a common interface.

We are going to start more explicitly pushing users to these packages soon.
