### ISSUE TITLE
add getAll() method to the shared_preferences plugin

### ISSUE THREAD

**Issue by JFixby** [flutter/flutter#11596]
Hello,

Can you please add getAll() method to the `shared_preferences` plugin.

Here is the code:
https://github.com/flutter/plugins/pull/193/commits/4abd850a2bd9978ccc21531588914c9681149bd4
```
  /// Reads all values from cache
   Map<String, Object> getAll() {
     Map<String, Object> result = new Map<String, Object>();
     result.addAll(_preferenceCache);
     return result;
   }
```

Thank you.

**Comment by Hixie** [comment]
cc @mehmetf

**Comment by Hixie** [comment]
@JFixby We probably won't get to this any time soon, but assuming @collinjackson or @mehmetf agree that this is a reasonable feature request, we would certainly welcome pull requests!

**Comment by mehmetf** [comment]
Sounds reasonable to me. Please feel free to forward a PR!

**Comment by mehmetf** [comment]
This is already available.
