### ISSUE TITLE
Flutter Web : Is it really production ready ? Navigation is not functional.

### ISSUE THREAD

**Issue by EskAere** [flutter/flutter#115994]
Hi, 

Please correct me if I'm wrong, but navigation is not functional for Flutter Web !

I have been doing a few web versions of my mobile apps with Flutter Web, but none for a client, so I could tolerate navigation issues. I was waiting for navigation (and mostly Firebase tools) to get better before starting serious web projects.
However, it's been more than 2 years that Navigator 2.0 is out, and it is still not functional for web ! 

Typing url manually causing all kind of issues, or history back and forth not working properly is not acceptable. Even the Flutter Gallery website, which I expected to have a perfectly working navigation by now, does not work properly. 

I also tried using packages, like AutoRoute, but without success. You can do a decent web app, but not a perfectly working app, and I find that frustrating.

Am I missing something here ? 

Thank you for your inputs !

**Comment by Hixie** [comment]
I encourage you to seek help on a Flutter community forum like r/FlutterDev or the FlutterDev Discord. If there's something in the documentation that is lacking or if there's a concrete API that is not functioning as per the documentation, please do not hesitate to file a bug, but please include specifics and a reproducible test case. Thanks!

**Comment by zambetpentru** [comment]
On the encouraging side, I can say the Navigation works really well on Web so definitely it should all be possible for you :-)
