### ISSUE TITLE
flutter upgrade shouldn't print a warning for older flutter installations

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter#11598]
We have a warning when you run the flutter tool and your flutter sdk is older:

```
WARNING: your installation of flutter is 40 days old

To upgrade to the latest version, run "flutter upgrade".
```

However, we print this warning even when you're running the `flutter upgrade` command; we should probably skip the warning for that specific command.

**Comment by DanTup** [comment]
Looks like we already have this:

```dart
if (topLevelResults.command?.name != 'upgrade') {
  await FlutterVersion.instance.checkFlutterVersionFreshness();
}
```

And it seems to be working (skipping over) as expected, yet I still see the warning printed (and don't hit breakpoints in there). I wonder if something is spawning another process or similar. I'll see what I can find...

**Comment by DanTup** [comment]
Yep, we do this:

```dart
code = await runCommandAndStreamOutput(
  <String>[
    fs.path.join('bin', 'flutter'), '--no-color', 'precache',
  ],
  workingDirectory: Cache.flutterRoot,
  allowReentrantFlutter: true
);
```

I could add `precache` to the list of excluded commands, but it runs `doctor` further too. Would we be better adding a `--no-update-check` switch or something, and then adding it to the args of anything that's run as part of `upgrade`?
