### ISSUE TITLE
[in_app_purchase] There is a pending transaction for the same product identifier

### ISSUE THREAD

**Issue by agordeev** [flutter/flutter#115948]
[This](https://github.com/flutter/flutter/issues/60763) issue was closed, but not resolved.

The method offered is to add this:

```dart
      final transactions = await SKPaymentQueueWrapper().transactions();
      transactions.forEach((transaction) async {
        await SKPaymentQueueWrapper().finishTransaction(transaction);
      });
```

However, `SKPaymentQueueWrapper` is not exposed by the lib.
How do we handle this issue?

**Comment by exaby73** [comment]
Hello @agordeev. `SKPaymentQueueWrapper` is exposed by [`in_app_purchase_storekit`](https://pub.dev/packages/in_app_purchase_storekit) [here](https://pub.dev/documentation/in_app_purchase_storekit/latest/store_kit_wrappers/SKPaymentQueueWrapper-class.html). You can add this package as a dependency and import it from there. Do remember to only call this on iOS and not other platforms as it may throw an error. Does this solve your issue?
