### ISSUE TITLE
Charles network size is too biggere than native code version network size

### ISSUE THREAD

**Issue by hongdangodori** [flutter/flutter#115968]
</details>
Previously, the iOS app was converted to Flutter, but the same network request with the same information. In the case of an app written in native code, the size was 400 bytes, but when it was converted to Flutter, the network size was 40 kb. What is the difference? is it big?? Is there any way to reduce this size difference?
flutter version app TLS handshake size is bigger than native version
I compared the size with Charles Proxy.
<details>

**Comment by exaby73** [comment]
Hello @hongdangodori . Thank you for filing this issue. Can you please provide the following information?

- A [complete and minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). Ideally, a single `main.dart` file that can be run directly.
- The output of `flutter doctor -v`

Please provide the information in the form of text. See how to make collapsible sections with Markdown [here](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-collapsed-sections).

**Comment by hongdangodori** [comment]
doctor

**Comment by exaby73** [comment]
I am not sure how to verify this issue. I need some way of reproducing it, and verifying it in order to move further with the issue. Please provide reproduction steps so that I may do so.

**Comment by hongdangodori** [comment]
1. Any app uses the same host for https communication using Charles proxy.
2. You can see that the TLS handshake is renewed for every communication.
@exaby73

**Comment by exaby73** [comment]
Could you please provide a way to reproduce the issue without 3rd party tools or apps except for Charles? A public repo with Charles set up in docker for example is ideal
