### ISSUE TITLE
Tasks fail to get scheduled though updated as `In Progress`

### ISSUE THREAD

**Issue by flar** [flutter/flutter#115942]
The list of builds in the status page for that task is all green, but the column on the dashboard has had the same 5 or 6 gray boxes (and 1 yellow) since last night with no progress. (In that same amount of time, the entire grid of tasks back-filled except for this one column). It looks like the scheduling of these tasks stalled at some point...

https://ci.chromium.org/p/flutter/builders/prod/Linux_build_test%20flutter_gallery__transition_perf

**Comment by keyonghan** [comment]
Seems tasks are updated as `In Process` though they failed to get scheduled to run. Sounds an issue when scheduling targets. Updated the title to reflect the real issue.

With `In Progress` in the column, top recent grey ones will not be picked up by back filler (which back fills targets only when no `In Progress` entries exist). To unblock, manually updated the `In Progress` task to `New`.

For context: this is not a blocking issue in long term. The back filler checks recent 20 runs and it will start back filling grey boxes when the `In Progress` box falls out of the range. At the same time, the scheduler also forces a schedule every 6 commits even though there is an earlier `In Progress` box.

**Comment by flar** [comment]
@keyonghan to be clear, the entry in the most recent row was gray the entire night and was still gray in the morning about 10-11 hours later. It's not just the back fill that was missing, it didn't even complete the testing on the most recent commit.

**Comment by keyonghan** [comment]
Several changes/improvements about scheduler and backfiller have been landed over the past months. I expect the issue has been resolved. Please reopen if you see the issue repros.
