### ISSUE TITLE
Can't access `useMaterial3` from the theme in the `showSnackBar` method to conditionally change `SnackBar` animation for Material 3.

### ISSUE THREAD

**Issue by esouthren** [flutter/flutter#115924]
While working on https://github.com/flutter/flutter/pull/115750, I was attempting to conditionally change the duration of the SnackBar animation, depending on whether the theme was Material 3 or not. 

The Scaffold creates the animation controller for its snackbars in the `ScaffoldMessengerState` method `showSnackBar()`:
```
 _snackBarController ??= SnackBar.createAnimationController(vsync: this)
```
[(scaffold.dart)](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/scaffold.dart#L295)

`createAnimationController` is a static method of `SnackBar`:
```
  static AnimationController createAnimationController({ required TickerProvider vsync }) {
    return AnimationController(
      duration: _snackBarTransitionDuration,
      debugLabel: 'SnackBar',
      vsync: vsync,
    );
  }
 ``` 
[(snack_bar.dart)](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/snack_bar.dart#L363)

Ideally we could pass an optional `useMaterial3` parameter to this method, and change the duration accordingly. 

However, when running a Material 3 example (like `snackbar.2.dart` in the above mentioned PR) I can't seem to access a value of `Theme.of(context).useMaterial3 = true` from `ScaffoldMessengerState`, though I can from `ScaffoldState`.

Perhaps there's a trivial solution to this, but I need some insight from someone with more Scaffold familiarity.

**Comment by huycozy** [comment]
Based on the detailed information at https://github.com/flutter/flutter/issues/141646#issue-2085079840, I think this issue is a subordinate issue of https://github.com/flutter/flutter/issues/118621, should we only centralize into https://github.com/flutter/flutter/issues/118621?

**Comment by Piinks** [comment]
ScaffoldMessenger state is above the Scaffold, and above the theme, (the built in messenger is in MaterialApp). This could be worked around by adding a ScaffoldMessenger in the widget tree below the theme.
