### ISSUE TITLE
Enable flutter engine artifacts for Windows on Arm

### ISSUE THREAD

**Issue by pbo-linaro** [flutter/flutter#115983]
## Use case

To support targeting Windows on Arm platform (https://github.com/flutter/flutter/issues/62597), we need first to enable artifacts for flutter engine on this platform.

## Proposal

Engine can be cross-compiled from a x64 machine by using:
```
python3 ./flutter/tools/gn --no-goma --windows-cpu arm64
ninja -C out/host_debug_arm64
```

I'll create a patch for [recipe file](https://flutter.googlesource.com/recipes/+/refs/heads/main/recipes/engine/engine.py).
Thanks @loic-sharma for proposing to help upstream this patch.

**Comment by loic-sharma** [comment]
Hello, thanks for the patch! I apologize for the delay, I was off last week.

I kicked off a [test run](https://ci.chromium.org/raw/build/logs.chromium.org/flutter/led/loicsharma_google.com/2b5be8479030636b24c36c4e602428f415a5262d70fa7f312c8f6c6e105e79f5/+/build.proto?server=chromium-swarm.appspot.com) of your changes, that failed on the [`Zip windows-arm64 windows-arm64-embedder.zip` step](https://logs.chromium.org/logs/flutter/led/loicsharma_google.com/2b5be8479030636b24c36c4e602428f415a5262d70fa7f312c8f6c6e105e79f5/+/u/Zip_windows-arm64_windows-arm64-embedder.zip/stdout):

> IOError: [Errno 2] No such file or directory: u'C:\\b\\s\\w\\ir\\cache\\builder\\src\\out/host_debug_arm64/flutter_embedder.h'

Please let me know when you're ready for me to run another test!

**Comment by pbo-linaro** [comment]
Thanks @loic-sharma . No problem, you said you were out :)

I pushed two other commits [here](https://github.com/pbo-linaro/flutter-recipes/tree/artifacts_arm64), to fix the issue you mentioned (regarding font), and removed the embedder package for now (not sure what it is used for).

Feel free to squash commits to have a single patch. For now, I just try to keep commits splitted to track history of this patch.

**Comment by loic-sharma** [comment]
Here's the latest result: https://ci.chromium.org/raw/build/logs.chromium.org/flutter/led/loicsharma_google.com/c0e4ff1860fc1c4916a177502cc4cfb0fad1d20aa848aac5b68add72334199f0/+/build.proto?server=chromium-swarm.appspot.com

> ( 321 ms )C:\b\s\w\ir\cache\builder\src\out\host_release_arm64\zip_archives\windows-arm64\font-subset.zip not found
> ( 319 ms )Files in parent directory of safe_upload request
[WinError 3] The system cannot find the path specified: 'C:\b\s\w\ir\cache\builder\src\out\host_release_arm64\zip_archives\windows-arm64'

**Comment by pbo-linaro** [comment]
I removed the font subset as it does not seems to be built when building for windows-arm64. Still [here](https://github.com/pbo-linaro/flutter-recipes/tree/artifacts_arm64).

**Comment by loic-sharma** [comment]
Here's the latest build: https://ci.chromium.org/raw/build/logs.chromium.org/flutter/led/loicsharma_google.com/b765281e408ff608bc165ac7291626f93782efeac52f2d4936eb64a7482f9847/+/build.proto?server=chromium-swarm.appspot.com

It looks like it passed! (The final step fails, but that seems like an unrelated permission issue)

**Comment by pbo-linaro** [comment]
Ok great! I squashed all commits, and rebased it on top of master.

Could you submit it for review and post the link here?

**Comment by loic-sharma** [comment]
Here's the changelist: https://flutter-review.git.corp.google.com/c/recipes/+/37085

FYI there will be an infrastructure freeze from December 20th to January 4th due to the holidays. That might affect your ARM64 work.

**Comment by loic-sharma** [comment]
FYI, @godofredoc left a comment that you will also need to modify this: https://github.com/flutter/engine/tree/main/ci/builders

**Comment by godofredoc** [comment]
Public link to CL: https://flutter-review.googlesource.com/c/recipes/+/37085

**Comment by pbo-linaro** [comment]
From CL, it appears the "recipes" approach will be dropped in favor of a new solution, directly integrated in flutter engine repo, from January 2023. Thus, this seems to be the best approach at that time, and I'll do a PR for that.

**Comment by pbo-linaro** [comment]
Created PR on engine to add support for arm64 artifacts.
