### ISSUE TITLE
Support loading fonts

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#116]
<a href="https://github.com/Hixie"><img src="https://avatars.githubusercontent.com/u/551196?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Hixie](https://github.com/Hixie)**
_Thursday Jul 23, 2015 at 00:59 GMT_
_Originally opened as https://github.com/flutter/engine/issues/228_

----

**Comment by eseidelGoogle** [comment]
@vlidholt noted he may need to be able to load a custom font in the game.  Presumably we'll need to create a font service, since the apis on iOS and Android will be different.

**Comment by sethladd** [comment]
Making apps look consistent is part of the pitch. Can we bump up the priority? Thanks!

**Comment by eseidelGoogle** [comment]
If @abarth doesn't have time for this, it may be something meaty @jason-simmons would be willing to dive into.  This is definitely needed before anyone can ship with flutter.  Debatable as to if it's absolutely required for the hackthon.  It definitely would make apps look nicer. :)

**Comment by eseidelGoogle** [comment]
Jason has made a bunch of progress on this, including   https://github.com/flutter/flutter/pull/2029

**Comment by abarth** [comment]
@jason-simmons Did this.  We should open another bug about documenting how to use this feature.

**Comment by sethladd** [comment]
Nice!

**Comment by eseidelGoogle** [comment]
The material_gallery needs to embed a font so that could work. In general
the material package probably wants a font and we'll probably need to build
an easy way to include such.

**Comment by abarth** [comment]
Please file new bugs.
