### ISSUE TITLE
Possible mistake in a code snippet in Flutter Codelab: Get to know Firebase

### ISSUE THREAD

**Issue by DanGalkin** [flutter/flutter#116065]
On step 5. Add RSVP functionality: the 5th code snippet about updating the HomePage widget: Consumer<ApplicationState> is wrapping twice: I believe it is excessive.
<img width="489" alt="Screenshot_2" src="https://user-images.githubusercontent.com/4963513/204128766-7ab639d7-cc39-4648-a81c-95363c3426e0.png">

**Comment by iapicca** [comment]
possible dupe of https://github.com/flutter/flutter/issues/116051

**Comment by DanGalkin** [comment]
@iapicca I think this mistake shouldn't influence the work of a program, but it is confusing in terms of studying Flutter and this codelab particularly.

**Comment by exaby73** [comment]
Hello @DanGalkin. Can you confirm that the code works with only one `Comsumer` widget?

**Comment by DanGalkin** [comment]
Yes, either of them.

**Comment by exaby73** [comment]
Thanks for the input. I'll label this issue for visibility by the team

**Comment by maheshmnj** [comment]
cc: @domesticmouse

**Comment by domesticmouse** [comment]
PTAL @miquelbeltran

**Comment by miquelbeltran** [comment]
The code in the repo seems correct to me: https://github.com/flutter/codelabs/blob/main/firebase-get-to-know-flutter/step_05/lib/home_page.dart it does not wrap the whole Widget with a `Consumer`.

The error seems to be just in the codelab md file.

I'll correct that error on my PR as well: https://github.com/flutter/codelabs/pull/1333
