### ISSUE TITLE
[local_auth][Android] Face Recognition for Android

### ISSUE THREAD

**Issue by hoangde2811** [flutter/flutter#116098]
Dear developer!!
I have set up facial recognition on my Nokia phone, but when using local_auth version 2.1.2, the library says that facial recognition is not set up.
 Hope the developer check and give feedback.
Sincerely thank.

**Comment by exaby73** [comment]
Hello @hoangde2811. You have already raised this issue https://github.com/flutter/flutter/issues/116083. Please refrain from creating duplicates of the same issue. Closing this issue for the same reason
