### ISSUE TITLE
Global Overlay can not be displayed with MaterialApp.router when i use go router

### ISSUE THREAD

**Issue by omar-hadek** [flutter/flutter#116096]
i have a listener for loading status and it get notified whenever there is a loading event and display a overlay instance 
when i use home with Matrial app it works fine but when i switch to materialApp.router wiith go router the state still notified but it did not show up the overlayEntity 
here is the code

```
  ref.listen<bool>(isLoadingProvider, (_, isloading) {
      if (isloading) {
        LoadingScreen.instance().show(context: context);
      } else {
        LoadingScreen.instance().hide();
      }
    });
    final router = ref.watch(routerProvider);
    return MaterialApp.router(
      title: 'my app',
      theme: ThemeData(
        brightness: Brightness.dark,
        primarySwatch: Colors.blue,
        indicatorColor: Colors.blueGrey,
      ),
      darkTheme: ThemeData.dark(),
      themeMode: ThemeMode.dark,
      debugShowCheckedModeBanner: false,
      routeInformationParser: router.routeInformationParser,
      routerDelegate: router.routerDelegate,

    );
```

**Comment by exaby73** [comment]
Hello @omar-hadek. Thank you for filing this issue. Can you please provide the following information?

- A [complete and minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). Ideally, a single `main.dart` file that can be run directly.
- The output of `flutter doctor -v`
- The output of `flutter run -v`

Please provide the information in the form of text. See how to make collapsible sections with Markdown [here](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-collapsed-sections).
