### ISSUE TITLE
Separate fetch, compile and upload operations in the packaging tool and recipe

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#116086]
For SLSA compliance we need to separate builds into different stages: fetch, compile, upload. This requires the packaging script to generate the artifact/metadata and upload the generated files separately.

This will be implemented in two different places:

* The packaging script will need to download the metadata file and updated it locally even when the deploy option is not used.
* The packaging recipe to upload the metadata file when running from a stable/beta branch.

**Comment by godofredoc** [comment]
\cc @sealesj @christopherfujino @CaseyHillers

**Comment by godofredoc** [comment]
@sealesj can you please help with the recipe change to upload metadata if the running from stable|beta?

**Comment by sealesj** [comment]
Yes I'll make that change

**Comment by godofredoc** [comment]
Is this now complete?

**Comment by sealesj** [comment]
Yes, completed with https://flutter-review.git.corp.google.com/c/recipes/+/36680 and https://flutter-review.git.corp.google.com/c/recipes/+/36160
