### ISSUE TITLE
Wrong icon button color in code lab screen dump

### ISSUE THREAD

**Issue by mravn-google** [flutter/flutter#11604]
Building Beautiful UIs with Flutter, step 5, last Simulator screen dump. The > send button icon in the iOS view is black, but should be blue.

**Comment by Hixie** [comment]
cc @LarkAscending

**Comment by LarkAscending** [comment]
Fixed in early Sept... The black icon was a transient product issue, which got fixed post-I/O!
https://codelabs.developers.google.com/codelabs/flutter/#4
