### ISSUE TITLE
Debugging section appears too early?

### ISSUE THREAD

**Issue by mravn-google** [flutter/flutter#11605]
Building beautiful UIs with Flutter, step 5, last section on debugging:

The text refers to "the setState() methods in your [...] app", but we have not yet defined any such methods at this point.

**Comment by Hixie** [comment]
cc @LarkAscending

**Comment by LarkAscending** [comment]
Fixed in early Sept; it makes sense to debug build() methods, not setState(). New text:

Practice using the debugger by setting breakpoints on the build() methods in your Friendlychat app, then run and debug the app. You can inspect the stack frames to see the history of method calls by your app.
