### ISSUE TITLE
`getAvailableBiometrics` not detecting face and fingerprint on a Nokia phone

### ISSUE THREAD

**Issue by hoangde2811** [flutter/flutter#116083]
Dear developer!!
I have set up face recognition on android, but when using local_auth version 2.1.2, the library says that face recognition has not been set up. Hope the developer can check and give feedback.
 Sincerely thank you

**Comment by exaby73** [comment]
Hello @hoangde2811. Thank you for filing this issue. Can you please provide the following information?

- A [complete and minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). Ideally, a single `main.dart` file that can be run directly.
- The output of `flutter doctor -v`
- The output of `flutter run -v`

Please provide the information in the form of text. See how to make collapsible sections with Markdown [here](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-collapsed-sections).

**Comment by hoangde2811** [comment]
Dear  developer!!

I have used the local_auth library version 2.1.12 for authentication,
on my Nokia phone I have set up face recognition but when I use the
authenticate function and attach biometricOnly = true, the library
says that the device is not yet born. No biometrics and went to the
System Settings of my Nokia phone and forced me to set up my
fingerprint.
I hope the developer can check it again for me.
Sincerely thank you.

[image: image.png]

**Comment by exaby73** [comment]
Hello. I would need a code sample and reproduction steps in order to verify this issue. Also, it would help to get your exact device details, including your phone model and android version

**Comment by hoangde2811** [comment]
Dear developer!!
The phone I am using is Nokia 5.4 and the operating system is android 11,
my code is attached below.
Hope the developer can check and give feedback.
Sincerely thank you

[image: image.png]

**Comment by hoangde2811** [comment]
Dear developer!!
The phone I am using is Nokia 5.4 and the operating system is android 11,
my code is attached below.
Hope the developer can check and give feedback.
Sincerely thank you.

authenticated = await auth.authenticate(
          localizedReason:
          'Scan your fingerprint (or face or whatever) to authenticate',
          options:AuthenticationOptions(useErrorDialogs:true, stickyAuth:
true,biometricOnly: true)
         );

**Comment by huycozy** [comment]
@hoangde2811 Have you already set up fingerprint in Settings? If you have enrolled in both fingerprint and face recognition, there is a known issue #45775 about this, please follow up on it for further updates.

**Comment by hoangde2811** [comment]
Dear developer!!
Currently Nokia 5.4 phone has face recognition so I want users to
authenticate with face not fingerprint authentication. I've looked at issue
#45775 but I don't see any support for facial recognition authentication.
I hope the developer can help me.
Sincerely thank you.

**Comment by exaby73** [comment]
Can you provide the result of `await auth.getAvailableBiometrics()`?

**Comment by hoangde2811** [comment]
Dear developer!!
I used await auth.getAvailableBiometrics() which returns an empty table but while the Nokia 5.4 android 11 phone has both fingerprint and face recognition. When I set up face recognition, the gallery pops up a message that leads to fingerprint settings. 
Hope the developer can help me.
 Sincerely thank you.

**Comment by exaby73** [comment]
Without a way to reproduce this issue, as I do not have a Nokia phone, I cannot verify this issue. It might be an OEM issue, but I cannot say for sure. I am labeling this issue for the team to investigate further and provide insights on it. Thank you

**Comment by ruhulrahat** [comment]
Using `local_auth 2.1.2` package.  
Not getting face detection prompt, only fingerprint option showing (On Android, Techno Camon Ch6i device). 

`getAvailableBiometrics()` returns `weak` and `strong` when both fingerprint and face is enrolled on device.
`getAvailableBiometrics()` returns empty list when only face is enrolled on device.
