### ISSUE TITLE
RasterCache breaks unobstructed platform views.

### ISSUE THREAD

**Issue by knopp** [flutter/flutter#116069]
I'm currently implementing platform views for macOS, trying to ensure that there is no view above platform view unless there is actual contents (unobstructed platform views) as described at the end of [this design doc.](https://docs.google.com/document/d/1YHwVz7-F03psEzHxByGka_lIFaDV5K90BJMbNxQeK4k/edit?resourcekey=0-n4_VcUnMU-99sjJ6C1_Ycw#heading=h.62f6mxdb874n)

The way it works is that based on R-Tree obtained during drawing, individual CALayers are created each one showing appropriate part of overlay surface. This works well, until the raster cache kicks in. With raster cache, the drawing becomes one blit operation and the R-Tree region is not useful anymore.

I'm showing this on desktop, but I assume same things happens on iOS, which for example means that under some relatively opaque and unpredictable (for the user) conditions Google Ads may seemingly randomly stop working.

https://user-images.githubusercontent.com/96958/204138153-2d21d397-9760-40da-a2e4-7d6bc02664ba.mov

Blue rectangle is the platform view, yellow border means overlay CALayer. When raster cache is active, instead of 3 smaller layer overlays there is only one big.

Engine branch: https://github.com/knopp/engine/tree/macos_platform_views
Test project: https://github.com/knopp/layer_playground

Possible solution might be for raster cache to remember coverage rectangles and instead of blitting the entire surface, blit the individual rects.

@flar, @cyanglaz, @jonahwilliams

**Comment by flar** [comment]
LayerRasterCacheItem will not cache if there is a platform view. It looks like DisplayListRasterCacheItem does, though.

The Layer can't raster cache because it cannot store the platform view in the cache. DLRCI doesn't have that problem, though, so it doesn't preclude its use in the presence of a platform view. I'm not saying that it should, but there is some food for thought there.
