### ISSUE TITLE
[Windows] Crash when typing "Right Shift" continuous

### ISSUE THREAD

**Issue by hxshenaaa** [flutter/flutter#116045]
flutter version: 3.3.9
platform:Windows
steps to reproduce：
Switch to chinese input method, tap down <right shirt> continuously. then application is not responding

错误模块名称: ntdll.dll，版本: 10.0.22621.755，时间戳: 0x8a328c67
异常代码: 0xc0000374
错误偏移量: 0x000000000010c249
错误进程 ID: 0x0x34114
错误应用程序启动时间: 0x0x1D900B29B6E11D4
错误应用程序路径: C:\Program Files\YahahaStudios\Yahaha\Yahaha.exe
错误模块路径: C:\Windows\SYSTEM32\ntdll.dll
报告 ID: e7e6f192-5d34-447e-a385-ac5ea184e397
错误程序包全名: 
错误程序包相对应用程序 ID:

A KeyUpEvent is dispatched, but the state shows that the physical key is not pressed. If this occurs in real application, please report this bug to Flutter. If this occurs in unit tests, please ensure that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This was the event: KeyUpEvent#88e7c(physicalKey: PhysicalKeyboardKey#00036(usbHidUsage: "0x1600000036", debugName: "Key with ID 0x1600000036"), logicalKey: LogicalKeyboardKey#00103(keyId: "0x200000103", keyLabel: "Shift Right", debugName: "Shift Right"), character: null, timeStamp: 31:41:21.687440)
'package:flutter/src/services/hardware_keyboard.dart':
Failed assertion: line 432 pos 16: '_pressedKeys.containsKey(event.physicalKey)'

**Comment by hxshenaaa** [comment]
Version 3.0.5 is good

**Comment by chifandeyu** [comment]
2.10.3版本也是有这个问题，后面有修复过，但是更新到3.3.8版本又有这个问题。复现路径是：shift键 + ‘2’ 输入 ‘@’ 释放键的时候触发崩溃

**Comment by huycozy** [comment]
Thanks for the report! This is a known issue being tracked at #99653. Closing this issue as a duplicate, so please follow up on it for further updates.
