### ISSUE TITLE
RTree coalesces rectangles too eagerly

### ISSUE THREAD

**Issue by knopp** [flutter/flutter#116070]
`RTree::searchNonOverlappingDrawnRects` will union any rectangles that so much as touch each other:

https://user-images.githubusercontent.com/96958/204139633-322ec738-4097-4edf-ada2-88014d9d2020.mov

This has some negative implications: We think that the platform view is covered, even though there's no actual content above it. That means overlay surface is used even in case where it doesn't need to be.

I tried the following implementation that uses SkRegion instead :

```cpp
std::list<SkRect> RTree::searchNonOverlappingDrawnRects(
    const SkRect& query) const {
  std::list<SkRect> res;

  SkRegion region;
  for (const auto& p : draw_op_) {
    region.op(p.second.roundOut(), SkRegion::kUnion_Op);
  }

  SkRegion::Cliperator iterator(region, query.roundOut());

  // Vertically deband cliperator rectangles.
  while (!iterator.done()) {
    auto rect = SkRect::Make(iterator.rect());
    auto iter = res.end();
    // If there is recangle previously in rect on which this one is a vertical
    // continuation, remove the previous rectangle and expand this one
    // vertically to cover the area.
    while (iter != res.begin()) {
      --iter;
      if (iter->bottom() < rect.top()) {
        // Went too far.
        break;
      } else if (iter->bottom() == rect.top() && iter->left() == rect.left() &&
                 iter->right() == rect.right()) {
        rect.fTop = iter->fTop;
        res.erase(iter);
        break;
      }
    }
    res.push_back(rect);
    iterator.next();
  }

  return res;
}
```

https://user-images.githubusercontent.com/96958/204139838-892d9f1b-f82b-4e44-bacf-fd91dea3870f.mov

Engine branch: https://github.com/knopp/engine/tree/macos_platform_views
Test project: https://github.com/knopp/layer_playground

I'm wondering if we could use something like this instead. 

cc @flar, @blasten, @cyanglaz

**Comment by flar** [comment]
I like this idea! Is the visualization of the overlay regions something separable that can be added as well?

Also, we should probably create a DL version of the region so as to avoid another dependence on a new Sk object.

**Comment by knopp** [comment]
I added PR to address this. The visualisation is currently hardcoded in the https://github.com/knopp/engine/tree/macos_platform_views branch, but I have plans to add Info.plist property to turn it on.
