### ISSUE TITLE
Get start of the day by DateTime.date

### ISSUE THREAD

**Issue by mokhin-denis** [flutter/flutter#116094]
## Use case

Right now to get date only from **DateTime** I use
```dart
final now = DateTime.now();
final nowDate = DateTime(now.year, now.month, now.day);
print(nowDate);//2022-11-28 00:00:00.000
```

After creating an extenson
```dart
extension Date on DateTime {
    DateTime get date => DateTime(year, month, day);
}
```
2 lines of code become 1:
```dart
final nowDate= DateTime.now().date;
print(nowDate);//2022-11-28 00:00:00.000
```

## Proposal
Make the date getter as part of **DateTime** class for getting date only (start of the day).

**Comment by danagbemava-nc** [comment]
Hi @mokhin-denis, DateTime is a core dart class. 

As such this issue should be reported on the dart-lang repo. 

I'll be closing this since this feature request should be filed on the dart-lang repo. 

Thank you
