### ISSUE TITLE
Flutter Markdown Not Rendering &amp; &quot; properly

### ISSUE THREAD

**Issue by irhamd** [flutter/flutter#116089]
## Steps to Reproduce

1. Execute `flutter run` on the code sample 

**Expected results:** "Test"

**Actual results:** `&quot;Test&quot;`

<details>
<summary>Code sample</summary>

```dart
MarkdownBody(data:"&quot;Test&quot;");
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @irhamd, I believe this is documented in the https://pub.dev/packages/flutter_markdown#flutter-isnt-a-html-renderer section of the package documentation. 

&quot; et al are HTML entities 

Closing this as not supported based on the above.

Thank you
