### ISSUE TITLE
Headings in API docs are a bit drowned out by sample code

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#116039]
Could we make the font size of subheadings a bit bigger in the API docs? Maybe adding some leading margin/padding would help too?

Consider for example the API docs for ListTile.

![2022-11-25-160536_1572x1308_scrot](https://user-images.githubusercontent.com/551196/204064383-34692d14-4ba1-4bcc-9e6d-2f17e15db14c.png)

It used to be a tiny bit better (though still not ideal):

![2022-11-25-160543_1608x1246_scrot](https://user-images.githubusercontent.com/551196/204064390-a2a27a5f-a537-4508-84bb-4468a3e85342.png)

cc @gspencergoog (not sure who did the recent restyling).

**Comment by gspencergoog** [comment]
I did the restyling.  Sure, we can tweak that. I'll send a PR.
