### ISSUE TITLE
Force call of paint procedure for CustomPainer

### ISSUE THREAD

**Issue by micrcx** [flutter/flutter#11606]
Is there a possibility for the flutter to force the paint procedure for the derived from CustomPainter class? Something like 'refresh' or 'update'?

**Comment by Hixie** [comment]
Does https://master-docs-flutter-io.firebaseapp.com/flutter/rendering/CustomPainter-class.html answer your question?

**Comment by micrcx** [comment]
I solved the problem with the setState function. In the procedure _handlePanEnd (onPanEnd: _handlePanEnd) I have to perform some conversion (recognizeShape) and update the scene:
Initial code:
  void _handlePanEnd (DragEndDetails details)
   {
       _recognizeShape ();
   }
In this case, the scene was sometimes not redrawn, but I found a solution:
  void _handlePanEnd (DragEndDetails details)
   {
     setState (()
    {
      _recognizeShape ();
    });
}

In any case, thanks for the answer.
Regard,
Michael K
