### ISSUE TITLE
Document how to add deep links into an app

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#11607]
We should document how to add deep links to an app. This is the first
 use case mentioned in the larger discussion mentioned [in bug 10975](https://github.com/flutter/flutter/issues/10975#issuecomment-315862405), quoted here for easy access:

* **External URLs:** _A movie database app wants to register to take over handling URLs for its website.  Now when the user clicks on the URL the details for that movie are shown in the app instead of the browser._
Android and iOS have mechanisms that allow an app to register as a handler for external URLs.  Android uses  [App Links](https://developer.android.com/training/app-links/index.html#url-handling), and iOS uses [URL Schemes](https://developer.apple.com/library/content/documentation/iPhone/Conceptual/iPhoneOSProgrammingGuide/Inter-AppCommunication/Inter-AppCommunication.html#//apple_ref/doc/uid/TP40007072-CH6-SW1).  These mechanisms allow the app to register as a handler for URLs that can be invoked by other applications.

From a customer:

"We need a URL that will 1) take the user to a specific part in our app (a chat, for example) if they have the app installed or 2) take a user to the device specific app store and then do 1) after they install the app. I think this is called Google Play Referrer on Android "

https://github.com/flutter/flutter/issues/10452 added engine support for setting an initial route in a Flutter app, which is "deep" in the app (i.e., not the start page of the app) so this should be possible now, we just need some docs.

**Comment by eseidelGoogle** [comment]
Posse was able to add this to their recently published application.   However we definitely need an example and eventually Docs for others to be able to repeat the feat.

**Comment by sethladd** [comment]
Is this just a documentation/example request , or do we need something added to FlutterFire to get "Firebase Dynamic Links" ?

Carnivore needs ability to link into a specific screen of their app. Not sure if the technically need Firebase to do that.

**Comment by mit-mit** [comment]
This tracks docs + simple example of "basic" deep links, e.g. the ability to redirect `app:` or `http:` URLs to an app, and to have that URL communicate a "deep" page/route inside the app. We could layer Firebase Dynamic Links on top later.

**Comment by Hixie** [comment]
This is probably blocked on #11490 and the related bugs, since those will change how this will work.

**Comment by sethladd** [comment]
See also this request for an example: https://github.com/flutter/flutter/issues/9768

I wonder if we can merge the example request and the doc request into one issue.

**Comment by marwan-at-work** [comment]
@mit-mit any luck with an example for deep linking? I managed to open my flutter app from a browser with `myAppScheme://my-link?key=val` -- but I have no idea how to get `my-link` or `key=val` from the dart side. Thanks!

**Comment by sethladd** [comment]
@amirh might have some suggestions here

**Comment by mit-mit** [comment]
@marwan-at-work, no docs yet, waiting on the changes mentioned above for https://github.com/flutter/flutter/issues/11490. Maybe we can provide something interim here?

**Comment by marwan-at-work** [comment]
@mit-mit that would be great!

**Comment by alanrussian** [comment]
FYI, I think you have to use [https://developer.apple.com/library/content/documentation/General/Conceptual/AppSearch/UniversalLinks.html]("Universal Links") to route http links to apps on iOS, not URL Schemes. Universal Links seem to be the closest parallel to App Links on Android. 

mulligan is also interested in this, but probably not for launch.

**Comment by mehmetf** [comment]
Please keep in mind that we would like deep links to work for apps embedding Flutter activities into their existing applications. Let's aim to not have strong coupling between this feature and `FlutterApplication`.

**Comment by xster** [comment]
We did a round of design, specifically on how to make the API easier to use in https://docs.google.com/a/google.com/document/d/e/2PACX-1vTlkRnnfxqyVJsMb-17Foukc017aK631cCWVe4RUCa-7mXyk5JC07UCmWLKEcYb5yRLs4NJuhuNq91-/pub. 

However, I haven't had time to implement it yet and we're deprioritizing it a bit given the latest round of planning. Hopefully we'll get back to this soon.

**Comment by marinoluck** [comment]
Guys, maybe this package could help you. 
https://pub.dartlang.org/packages/uni_links

**Comment by nvcken** [comment]
@xster xs
I can't access design docs, no permission

**Comment by gedw99** [comment]
@marioluck thanks it looks really well designed

**Comment by thosakwe** [comment]
Is this possible yet with Flutter? Would definitely make OAuth flows a lot easier, without having to use webview plugins (which tend towards broken/unmaintained).

**Comment by harrzz** [comment]
What about this? 
https://github.com/flutter/plugins/tree/master/packages/firebase_dynamic_links

**Comment by thosakwe** [comment]
I’m not using Firebase, so that’s not much of a solution in this case. Thanks, though.

**Comment by gedw99** [comment]
@thosakwe whats wrong with https://pub.dartlang.org/packages/uni_links. It was suggested above.

**Comment by blaneyneil** [comment]
https://pub.dartlang.org/packages/uni_links currently doesn't handle payloads from a cold start on iOS.

**Comment by beardo01** [comment]
Has anyone tried using https://pub.dartlang.org/packages/uni_links since the last post?

**Comment by blaneyneil** [comment]
yes.  there was a small patch shortly after my above post, and it's since been handling iOS cold opens fine.

**Comment by philipgiuliani** [comment]
Yes, I implemented it in Android and iOS, and it works perfectly fine!

**Comment by GroovinChip** [comment]
How do I know what the scheme and host of my app is?

**Comment by thosakwe** [comment]
@groovinchip That’s metadata that you define yourself, see the uni_links docs for info.

**Comment by gedw99** [comment]
@GroovinChip when you run the app the screen shows the command to run from your terminal to simulate an URL being opened by the user. 
worked for me first time.

the dev @philipgiuliani  made it really easy to get going. Great stuff !

**Comment by neiljaywarner** [comment]
@sethladd  @eseidel  
1) many companies cannot use firebase at all (although any assistance in making a case for it might make me jump for joy)
2) https://pub.dartlang.org/packages/uni_links probably cannot be depended on - something this important should probably be direct from google/flutter, especially in light of this sentence "At the moment Flutter v0.4.4 does not support Universal Links" - someone who's in initial research stage instead of "committed" stage will think "time to move along, this might not be a good idea"

**Comment by thosakwe** [comment]
@neiljaywarner You can't depend on a community package?

**Comment by neiljaywarner** [comment]
@thosakwe  I apologize for strong wording. i am a fan of community for sure, and there's lots of fantastic work from the community as far as I can tell, especially on dartpub

One of the biggest assets I feel flutter/dartpub brings is its rating and organization to assist you in evaluating community plugins.

The readme looks fantastic, and I'm not saying I wouldn't use it or won't depend on it, I'm just saying a) support from google for something so foundational might be worth considering and b) it has 1-2 authors, perhaps that's a concern - but mostly c) " **_Flutter v0.4.4 does not support_**" seems like a phrase to bring to the attention of the Flutter Team - especially if uni-links is the suggested solution d) If there have been 20 or so releases since 0.4.4, that also is a concern.

The authors of the community plugin cannot be expected to keep the doc updated for a reference to the latest version of flutter, but again, something so foundational that sounds like "works vs doesn't work"

**Comment by Zhuinden** [comment]
If the `Navigator` had a function that [exposes the list of routes that are currently in the Navigator](https://github.com/flutter/flutter/issues/26184#issuecomment-466060301), then this would be reasonably simple.

But as reflection is not supported and the routes are private, it's currently a mess.

**Comment by Xgamefactory** [comment]
totally agree !
flutter team should improve flutter instead of playing in video promotions )

**Comment by hiddencaliber** [comment]
> https://pub.dartlang.org/packages/uni_links currently doesn't handle payloads from a cold start on iOS.

Can you provide any example for this? iOS deep-linking from cold start doesn't work for me.
Thanks

**Comment by blaneyneil** [comment]
i no longer use uni_links since firebase dynamic links handles them properly now.

**Comment by mihairadulescu** [comment]
still... deeplinkin is poorly documented. i`m pointed here from all issues.

**Comment by maheshmnj** [comment]
is there a way to go to a specific page using firebase dynamic link if the app is installed on the device?

**Comment by joshuamataaraya** [comment]
@maheshmnj There's a package for dynamic links on Flutter using firebase. Check thishttps://pub.dev/packages/firebase_dynamic_links

**Comment by fauzi2107** [comment]
i got error like this
<img width="1164" alt="Screen Shot 2019-10-28 at 17 43 31" src="https://user-images.githubusercontent.com/34369203/67673113-e3517100-f9ab-11e9-9fca-432190306b24.png">

this happen after i add firebase_dynamic_links, i can't build my flutter project.

**Comment by marwan-at-work** [comment]
Any updates here? Would love to see official documentation on how to deep link into a flutter app.

**Comment by RudreshNarwal** [comment]
++

**Comment by walidbagh** [comment]
Any news ?

**Comment by kendall-lu** [comment]
would love to hear an update about this

**Comment by Bricktheworld** [comment]
Umm, is this possible at all?

**Comment by csells** [comment]
I attempted to pull together everything you need to consider when it comes to handling deep linking, routing and navigation for Flutter from a web pov:

http://sellsbrothers.com/understanding-flutter-deep-links-on-the-web

I believe this is 80% of the content needed for deep linking on Flutter all up (the mobile-specific content is missing), although not in the format appropriate for the docs on flutter.dev.

**Comment by HansMuller** [comment]
CC @johnpryan

**Comment by chunhtai** [comment]
We added a document for deeplinking https://flutter.dev/docs/development/ui/navigation/deep-linking, closing this issue

**Comment by maheshmnj** [comment]
> We added a document for deeplinking https://flutter.dev/docs/development/ui/navigation/deep-linking, closing this issue

Thanks for this helpful doc but it would also be great if you could add some details on how we can fetch the deeplink in the app which launched the application so as to fetch queryparams or any additional info from the deeplink if any, so as to perform some actions on click of a deeplink.

Usecase: assume an e-commerce application and the deeplink points to a product detail page,And deeplink contains the product id which can be used to fetch the product details from the server.
On a click of a deeplink  the app will be launched and user will be navigated to that specific product detail page.
