### ISSUE TITLE
iOS issue with podfile

### ISSUE THREAD

**Issue by kalien1** [flutter/flutter#116078]
I get this when I debug-ios

 html.CanvasElement resizeImageElement(

      ^^^^^^^^^^^^^^^^^^

    ../../../../.pub-cache/hosted/pub.dartlang.org/image_picker_for_web-2.1.10/lib/src/image_resizer.dart:59:7: Error: Type 'html.ImageElement' not found.

          html.ImageElement source, double? maxWidth, double? maxHeight) {

          ^^^^^^^^^^^^^^^^^

    ../../../../.pub-cache/hosted/pub.dartlang.org/image_picker_for_web-2.1.10/lib/src/image_resizer.dart:79:27: Error: Type 'html.CanvasElement' not found.

          XFile originalFile, html.CanvasElement canvas, int? imageQuality) async {

                              ^^^^^^^^^^^^^^^^^^

    ../buildtools/flutter/packages/flutter_web_plugins/lib/src/navigation/js_url_strategy.dart:79:48: Error: Type 'html.EventListener' not found.

      external ui.VoidCallback addPopStateListener(html.EventListener fn);

                                                   ^^^^^^^^^^^^^^^^^^

    ../buildtools/flutter/packages/flutter_web_plugins/lib/src/navigation/url_strategy.dart:193:3: Error: Type 'html.Location' not found.

      html.Location get _location => html.window.location;

      ^^^^^^^^^^^^^

    ../buildtools/flutter/packages/flutter_web_plugins/lib/src/navigation/url_strategy.dart:195:3: Error: Type 'html.History' not found.

      html.History get _history => html.window.history;

      ^^^^^^^^^^^^

    ../buildtools/flutter/packages/flutter_web_plugins/lib/src/navigation/url_strategy.dart:198:28: Error: Type 'html.EventListener' not found.

      void addPopStateListener(html.EventListener fn) {

                               ^^^^^^^^^^^^^^^^^^

    ../buildtools/flutter/packages/flutter_web_plugins/lib/src/navigation/url_strategy.dart:203:31: Error: Type 'html.EventListener' not found.

      void removePopStateListener(html.EventListener fn) {

                                  ^^^^^^^^^^^^^^^^^^

    ../buildtools/flutter/packages/flutter_web_plugins/lib/src/navigation/utils.dart:7:7: Error: Type 'AnchorElement' not found.

    final AnchorElement _urlParsingNode = AnchorElement();

          ^^^^^^^^^^^^^

    ../buildtools/flutter/packages/flutter_web_plugins/lib/src/navigation/utils.dart:20:7: Error: Type 'Element' not found.

    final Element? _baseElement = document.querySelector('base');

          ^^^^^^^

    ../../../../.pub-cache/hosted/pub.dartlang.org/image_picker_for_web-2.1.10/lib/image_picker_for_web.dart:35:13: Error: 'Element' isn't a type.

      late html.Element _target;

                ^^^^^^^

    ../../../../.pub-cache/hosted/pub.dartlang.org/image_picker_for_web-2.1.10/lib/image_picker_for_web.dart:102:16: Error: 'FileUploadInputElement' isn't a type.

        final html.FileUploadInputElement input =

                   ^^^^^^^^^^^^^^^^^^^^^^

    ../../../../.pub-cache/hosted/pub.dartlang.org/image_picker_for_web-2.1.10/lib/image_picker_for_web.dart:103:53: Error: 'FileUploadInputElement' isn't a type.

            createInputElement(accept, capture) as html.FileUploadInputElement;

                                                        ^^^^^^^^^^^^^^^^^^^^^^

    ../../../../.pub-cache/hosted/pub.dartlang.org/image_picker_for_web-2.1.10/lib/image_picker_for_web.dart:207:16: Error: 'FileUploadInputElement' isn't a type.

        final html.FileUploadInputElement input = createInputElement(

                   ^^^^^^^^^^^^^^^^^^^^^^

    ../../../../.pub-cache/hosted/pub.dartlang.org/image_picker_for_web-2.1.10/lib/image_picker_for_web.dart:211:15: Error: 'FileUploadInputElement' isn't a type.

        ) as html.FileUploadInputElement;

                  ^^^^^^^^^^^^^^^^^^^^^^

    ../../../../.pub-cache/hosted/pub.dartlang.org/image_picker_for_web-2.1.10/lib/image_picker_for_web.dart:230:44: Error: 'FileUploadInputElement' isn't a type.

      List<html.File>? _getFilesFromInput(html.FileUploadInputElement input) {

                                               ^^^^^^^^^^^^^^^^^^^^^^

    ../../../../.pub-cache/hosted/pub.dartlang.org/image_picker_for_web-2.1.10/lib/image_picker_for_web.dart:239:46: Error: 'Event' isn't a type.

      List<html.File>? _handleOnChangeEvent(html.Event event) {

                                                 ^^^^^

    ../../../../.pub-cache/hosted/pub.dartlang.org/image_picker_for_web-2.1.10/lib/image_picker_for_web.dart:240:16: Error: 'FileUploadInputElement' isn't a type.

        final html.FileUploadInputElement? input =

                   ^^^^^^^^^^^^^^^^^^^^^^

    ../../../../.pub-cache/hosted/pub.dartlang.org/image_picker_for_web-2.1.10/lib/image_picker_for_web.dart:241:30: Error: 'FileUploadInputElement' isn't a type.

            event.target as html.FileUploadInputElement?;

                                 ^^^^^^^^^^^^^^^^^^^^^^

    ../../../../.pub-cache/hosted/pub.dartlang.org/image_picker_for_web-2.1.10/lib/image_picker_for_web.dart:246:44: Error: 'FileUploadInputElement' isn't a type.

      Future<PickedFile> _getSelectedFile(html.FileUploadInputElement input) {

                                               ^^^^^^^^^^^^^^^^^^^^^^

    ../../../../.pub-cache/hosted/pub.dartlang.org/image_picker_for_web-2.1.10/lib/image_picker_for_web.dart:249:37: Error: 'Event' isn't a type.

        input.onChange.first.then((html.Event event) {

                                        ^^^^^

    ../../../../.pub-cache/hosted/pub.dartlang.org/image_picker_for_web-2.1.10/lib/image_picker_for_web.dart:250:23: Error: 'File' isn't a type.

          final List<html.File>? files = _handleOnChangeEvent(event);

                          ^^^^

    ../../../../.pub-cache/hosted/pub.dartlang.org/image_picker_for_web-2.1.10/lib/image_picker_for_web.dart:253:16: Error: Undefined name 'Url'.

              html.Url.createObjectUrl(files.first),

                   ^^^

    ../../../../.pub-cache/hosted/pub.dartlang.org/image_picker_for_web-2.1.10/lib/image_picker_for_web.dart:257:36: Error: 'Event' isn't a type.

        input.onError.first.then((html.Event event) {

                                       ^^^^^

    ../../../../.pub-cache/hosted/pub.dartlang.org/image_picker_for_web-2.1.10/lib/image_picker_for_web.dart:269:47: Error: 'FileUploadInputElement' isn't a type.

      Future<List<XFile>> _getSelectedXFiles(html.FileUploadInputElement input) {

                                                  ^^^^^^^^^^^^^^^^^^^^^^

    ../../../../.pub-cache/hosted/pub.dartlang.org/image_picker_for_web-2.1.10/lib/image_picker_for_web.dart:272:37: Error: 'Event' isn't a type.

        input.onChange.first.then((html.Event event) {

                                        ^^^^^

    ../../../../.pub-cache/hosted/pub.dartlang.org/image_picker_for_web-2.1.10/lib/image_picker_for_web.dart:273:23: Error: 'File' isn't a type.

          final List<html.File>? files = _handleOnChangeEvent(event);

                          ^^^^

    ../../../../.pub-cache/hosted/pub.dartlang.org/image_picker_for_web-2.1.10/lib/image_picker_for_web.dart:275:44: Error: 'File' isn't a type.

            completer.complete(files.map((html.File file) {

                                               ^^^^

    ../../../../.pub-cache/hosted/pub.dartlang.org/image_picker_for_web-2.1.10/lib/image_picker_for_web.dart:277:18: Error: Undefined name 'Url'.

                html.Url.createObjectUrl(file),

                     ^^^

    ../../../../.pub-cache/hosted/pub.dartlang.org/image_picker_for_web-2.1.10/lib/image_picker_for_web.dart:288:36: Error: 'Event' isn't a type.

        input.onError.first.then((html.Event event) {

                                       ^^^^^

    ../../../../.pub-cache/hosted/pub.dartlang.org/image_picker_for_web-2.1.10/lib/image_picker_for_web.dart:285:12: Error: The argument type 'List<dynamic>' can't be assigned to the parameter type 'FutureOr<List<XFile>>?'.

     - 'List' is from 'dart:core'.

     - 'XFile' is from 'package:cross_file/src/types/io.dart' ('../../../../.pub-cache/hosted/pub.dartlang.org/cross_file-0.3.3+2/lib/src/types/io.dart').

            }).toList());

               ^

    ../../../../.pub-cache/hosted/pub.dartlang.org/image_picker_for_web-2.1.10/lib/image_picker_for_web.dart:301:10: Error: 'Element' isn't a type.

        html.Element? target = html.querySelector('#$id');

             ^^^^^^^

    ../../../../.pub-cache/hosted/pub.dartlang.org/image_picker_for_web-2.1.10/lib/image_picker_for_web.dart:301:33: Error: Method not found: 'querySelector'.

        html.Element? target = html.querySelector('#$id');

                                    ^^^^^^^^^^^^^

    ../../../../.pub-cache/hosted/pub.dartlang.org/image_picker_for_web-2.1.10/lib/image_picker_for_web.dart:303:18: Error: 'Element' isn't a type.

          final html.Element targetElement =

                     ^^^^^^^

    ../../../../.pub-cache/hosted/pub.dartlang.org/image_picker_for_web-2.1.10/lib/image_picker_for_web.dart:304:16: Error: Undefined name 'Element'.

              html.Element.tag('flt-image-picker-inputs')..id = id;

                   ^^^^^^^

    ../../../../.pub-cache/hosted/pub.dartlang.org/image_picker_for_web-2.1.10/lib/image_picker_for_web.dart:306:12: Error: Method not found: 'querySelector'.

          html.querySelector('body')!.children.add(targetElement);

               ^^^^^^^^^^^^^

    ../../../../.pub-cache/hosted/pub.dartlang.org/image_picker_for_web-2.1.10/lib/image_picker_for_web.dart:324:16: Error: 'Element' isn't a type.

        final html.Element element = html.FileUploadInputElement()

                   ^^^^^^^

    ../../../../.pub-cache/hosted/pub.dartlang.org/image_picker_for_web-2.1.10/lib/image_picker_for_web.dart:324:39: Error: Method not found: 'FileUploadInputElement'.

        final html.Element element = html.FileUploadInputElement()

                                          ^^^^^^^^^^^^^^^^^^^^^^

    ../../../../.pub-cache/hosted/pub.dartlang.org/image_picker_for_web-2.1.10/lib/image_picker_for_web.dart:336:32: Error: 'Element' isn't a type.

      void _injectAndActivate(html.Element element) {

                                   ^^^^^^^

    ../../../../.pub-cache/hosted/pub.dartlang.org/image_picker_for_web-2.1.10/lib/src/image_resizer.dart:26:18: Error: 'ImageElement' isn't a type.

          final html.ImageElement imageElement = await loadImage(file.path);

                     ^^^^^^^^^^^^

    ../../../../.pub-cache/hosted/pub.dartlang.org/image_picker_for_web-2.1.10/lib/src/image_resizer.dart:27:18: Error: 'CanvasElement' isn't a type.

          final html.CanvasElement canvas =

                     ^^^^^^^^^^^^^

    ../../../../.pub-cache/hosted/pub.dartlang.org/image_picker_for_web-2.1.10/lib/src/image_resizer.dart:31:12: Error: Undefined name 'Url'.

          html.Url.revokeObjectUrl(file.path);

               ^^^

    ../../../../.pub-cache/hosted/pub.dartlang.org/image_picker_for_web-2.1.10/lib/src/image_resizer.dart:40:26: Error: 'ImageElement' isn't a type.

        final Completer<html.ImageElement> imageLoadCompleter =

                             ^^^^^^^^^^^^

    ../../../../.pub-cache/hosted/pub.dartlang.org/image_picker_for_web-2.1.10/lib/src/image_resizer.dart:41:24: Error: 'ImageElement' isn't a type.

            Completer<html.ImageElement>();

                           ^^^^^^^^^^^^

    ../../../../.pub-cache/hosted/pub.dartlang.org/image_picker_for_web-2.1.10/lib/src/image_resizer.dart:42:16: Error: 'ImageElement' isn't a type.

        final html.ImageElement imageElement = html.ImageElement();

                   ^^^^^^^^^^^^

    ../../../../.pub-cache/hosted/pub.dartlang.org/image_picker_for_web-2.1.10/lib/src/image_resizer.dart:42:49: Error: Method not found: 'ImageElement'.

        final html.ImageElement imageElement = html.ImageElement();

                                                    ^^^^^^^^^^^^

    ../../../../.pub-cache/hosted/pub.dartlang.org/image_picker_for_web-2.1.10/lib/src/image_resizer.dart:46:38: Error: 'Event' isn't a type.

        imageElement.onLoad.listen((html.Event event) {

                                         ^^^^^

    ../../../../.pub-cache/hosted/pub.dartlang.org/image_picker_for_web-2.1.10/lib/src/image_resizer.dart:49:39: Error: 'Event' isn't a type.

        imageElement.onError.listen((html.Event event) {

                                          ^^^^^

    ../../../../.pub-cache/hosted/pub.dartlang.org/image_picker_for_web-2.1.10/lib/src/image_resizer.dart:59:12: Error: 'ImageElement' isn't a type.

          html.ImageElement source, double? maxWidth, double? maxHeight) {

               ^^^^^^^^^^^^

    ../../../../.pub-cache/hosted/pub.dartlang.org/image_picker_for_web-2.1.10/lib/src/image_resizer.dart:64:16: Error: 'CanvasElement' isn't a type.

        final html.CanvasElement canvas = html.CanvasElement();

                   ^^^^^^^^^^^^^

    ../../../../.pub-cache/hosted/pub.dartlang.org/image_picker_for_web-2.1.10/lib/src/image_resizer.dart:64:44: Error: Method not found: 'CanvasElement'.

        final html.CanvasElement canvas = html.CanvasElement();

                                               ^^^^^^^^^^^^^

    ../../../../.pub-cache/hosted/pub.dartlang.org/image_picker_for_web-2.1.10/lib/src/image_resizer.dart:67:16: Error: 'CanvasRenderingContext2D' isn't a type.

        final html.CanvasRenderingContext2D context = canvas.context2D;

                   ^^^^^^^^^^^^^^^^^^^^^^^^

    ../../../../.pub-cache/hosted/pub.dartlang.org/image_picker_for_web-2.1.10/lib/src/image_resizer.dart:79:32: Error: 'CanvasElement' isn't a type.

          XFile originalFile, html.CanvasElement canvas, int? imageQuality) async {

                                   ^^^^^^^^^^^^^

    ../../../../.pub-cache/hosted/pub.dartlang.org/image_picker_for_web-2.1.10/lib/src/image_resizer.dart:82:16: Error: 'Blob' isn't a type.

        final html.Blob blob =

                   ^^^^

    ../../../../.pub-cache/hosted/pub.dartlang.org/image_picker_for_web-2.1.10/lib/src/image_resizer.dart:84:23: Error: Undefined name 'Url'.

        return XFile(html.Url.createObjectUrlFromBlob(blob),

                          ^^^

    ../buildtools/flutter/packages/flutter_web_plugins/lib/src/navigation/js_url_strategy.dart:48:14: Error: Method not found: 'allowInterop'.

        getPath: allowInterop(strategy.getPath),

                 ^^^^^^^^^^^^

    ../buildtools/flutter/packages/flutter_web_plugins/lib/src/navigation/js_url_strategy.dart:49:15: Error: Method not found: 'allowInterop'.

        getState: allowInterop(strategy.getState),

                  ^^^^^^^^^^^^

    ../buildtools/flutter/packages/flutter_web_plugins/lib/src/navigation/js_url_strategy.dart:50:26: Error: Method not found: 'allowInterop'.

        addPopStateListener: allowInterop(strategy.addPopStateListener),

                             ^^^^^^^^^^^^

    ../buildtools/flutter/packages/flutter_web_plugins/lib/src/navigation/js_url_strategy.dart:51:25: Error: Method not found: 'allowInterop'.

        prepareExternalUrl: allowInterop(strategy.prepareExternalUrl),

                            ^^^^^^^^^^^^

    ../buildtools/flutter/packages/flutter_web_plugins/lib/src/navigation/js_url_strategy.dart:52:16: Error: Method not found: 'allowInterop'.

        pushState: allowInterop(strategy.pushState),

                   ^^^^^^^^^^^^

    ../buildtools/flutter/packages/flutter_web_plugins/lib/src/navigation/js_url_strategy.dart:53:19: Error: Method not found: 'allowInterop'.

        replaceState: allowInterop(strategy.replaceState),

                      ^^^^^^^^^^^^

    ../buildtools/flutter/packages/flutter_web_plugins/lib/src/navigation/js_url_strategy.dart:54:9: Error: Method not found: 'allowInterop'.

        go: allowInterop(strategy.go),

            ^^^^^^^^^^^^

    ../buildtools/flutter/packages/flutter_web_plugins/lib/src/navigation/js_url_strategy.dart:79:53: Error: 'EventListener' isn't a type.

      external ui.VoidCallback addPopStateListener(html.EventListener fn);

                                                        ^^^^^^^^^^^^^

    ../buildtools/flutter/packages/flutter_web_plugins/lib/src/navigation/url_strategy.dart:193:39: Error: Undefined name 'window'.

      html.Location get _location => html.window.location;

                                          ^^^^^^

    ../buildtools/flutter/packages/flutter_web_plugins/lib/src/navigation/url_strategy.dart:195:37: Error: Undefined name 'window'.

      html.History get _history => html.window.history;

                                        ^^^^^^

    ../buildtools/flutter/packages/flutter_web_plugins/lib/src/navigation/url_strategy.dart:198:33: Error: 'EventListener' isn't a type.

      void addPopStateListener(html.EventListener fn) {

                                    ^^^^^^^^^^^^^

    ../buildtools/flutter/packages/flutter_web_plugins/lib/src/navigation/url_strategy.dart:199:10: Error: Undefined name 'window'.

        html.window.addEventListener('popstate', fn);

             ^^^^^^

    ../buildtools/flutter/packages/flutter_web_plugins/lib/src/navigation/url_strategy.dart:203:36: Error: 'EventListener' isn't a type.

      void removePopStateListener(html.EventListener fn) {

                                       ^^^^^^^^^^^^^

    ../buildtools/flutter/packages/flutter_web_plugins/lib/src/navigation/url_strategy.dart:204:10: Error: Undefined name 'window'.

        html.window.removeEventListener('popstate', fn);

             ^^^^^^

    ../buildtools/flutter/packages/flutter_web_plugins/lib/src/navigation/utils.dart:7:7: Error: 'AnchorElement' isn't a type.

    final AnchorElement _urlParsingNode = AnchorElement();

          ^^^^^^^^^^^^^

    ../buildtools/flutter/packages/flutter_web_plugins/lib/src/navigation/utils.dart:7:39: Error: Method not found: 'AnchorElement'.

    final AnchorElement _urlParsingNode = AnchorElement();

                                          ^^^^^^^^^^^^^

    ../buildtools/flutter/packages/flutter_web_plugins/lib/src/navigation/utils.dart:20:7: Error: 'Element' isn't a type.

    final Element? _baseElement = document.querySelector('base');

          ^^^^^^^

    ../buildtools/flutter/packages/flutter_web_plugins/lib/src/navigation/utils.dart:20:31: Error: Undefined name 'document'.

    final Element? _baseElement = document.querySelector('base');

                                  ^^^^^^^^

    ../buildtools/flutter/packages/flutter_web_plugins/lib/src/plugin_registry.dart:66:8: Error: Method not found: 'webOnlySetPluginHandler'.

        ui.webOnlySetPluginHandler(handleFrameworkMessage);

           ^^^^^^^^^^^^^^^^^^^^^^^

    Unhandled exception:

    FileSystemException(uri=org-dartlang-untranslatable-uri:dart%3Ahtml; message=StandardFileSystem only supports file:* and data:* URIs)

    #0      StandardFileSystem.entityForUri (package:front_end/src/api_prototype/standard_file_system.dart:34:7)

    #1      asFileUri (package:vm/kernel_front_end.dart:652:37)

    #2      writeDepfile (package:vm/kernel_front_end.dart:792:21)

    <asynchronous suspension>

    #3      FrontendCompiler.compile (file:///opt/s/w/ir/x/w/sdk/pkg/frontend_server/lib/frontend_server.dart:615:9)

    <asynchronous suspension>

    #4      starter (file:///opt/s/w/ir/x/w/sdk/pkg/frontend_server/lib/frontend_server.dart:1433:12)

    <asynchronous suspension>

    #5      main (file:///opt/s/w/ir/x/w/sdk/pkg/frontend_server/bin/frontend_server_starter.dart:10:14)

    <asynchronous suspension>

    Failed to package .

    Command PhaseScriptExecution failed with a nonzero exit code

    note: Using new build system

    note: Planning

    note: Build preparation complete

    note: Building targets in dependency order

    /ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.5.99. (in target 'leveldb-library' from project 'Pods')

    /ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.5.99. (in target 'FMDB' from project 'Pods')

    Result bundle written to path:

    	/var/folders/32/7mnldf2s2bn_stbm1k_qbh900000gr/T/flutter_tools.jYzvWf/flutter_ios_build_temp_dirpZo8Fr/temporary_xcresult_bundle

master

**Comment by exaby73** [comment]
Hello @kalien1. Thank you for filing this issue. Can you please provide the following information?

- A [complete and minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). Ideally, a single `main.dart` file that can be run directly.
- The output of `flutter doctor -v`
- The output of `flutter run -v`

Please provide the information in the form of text. See how to make collapsible sections with Markdown [here](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-collapsed-sections).
