### ISSUE TITLE
[image_picker] [Android] On android 12 take a image HEIF fail 

### ISSUE THREAD

**Issue by Chonli** [flutter/flutter#116031]
Hello
I have a problem on a big application (not reproductible with the image_picker sample) when some users take a picture, the application crash. I don't have a log because the debugger stop when the problem arrive and the application send nothing to crashlytics. 

To describe the problem more precisely, when you open the camera, you can take a photo but when you validate the photo, the application crashes. I attach a video showing the problem. 
After investigation I found that this only happened with android 12 and HEIF quality photos.

I use flutter 3.3.x and image_picker 0.8.6.

Somebody have the same problem ? Maybe you arrive to have more trace ?

Thanks for your help.

https://user-images.githubusercontent.com/4149097/204028103-4a0497b4-e2fa-48ae-b866-80742e7ef5f2.mp4

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel stable, 2.10.5, on macOS 13.0.1 22A400 darwin-x64, locale fr-FR)
    • Flutter version 2.10.5 at /Users/adrienpally/fvm/versions/2.10.5
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (il y a 7 mois), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[!] Android toolchain - develop for Android devices (Android SDK version 32.0.0-rc1)
    • Android SDK at /Users/adrienpally/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0-rc1
    • ANDROID_HOME = /Users/adrienpally/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/adrienpally/Library/Android/sdk/
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.73.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.52.0

[✓] Connected device (3 available)
    • SM A505FN (mobile) • R58M93DGX4J • android-arm64  • Android 11 (API 30)
    • macOS (desktop)    • macos       • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)       • chrome      • web-javascript • Google Chrome 107.0.5304.121

[✓] HTTP Host Availability
    • All required HTTP hosts are available
```

</details>

**Comment by carlosalito** [comment]
I have the same issue on flutter 2.10.5

**Comment by iapicca** [comment]
@Chonli 

I think you provided some useful info that may point in the right direction for troubleshooting:

1. it may depend from the implementation, so some sort of `code sample` is needed, especially the validation part

>(not reproductible with the image_picker sample) 

>[...], you can take a photo **_but when you validate the photo, the application crashes_**

2. good thing that you narrowed down that it's 
    - `android` specific
    - `OS version specific`
    
    but **_which_** users are experiencing the issue? maybe is `device specific` as well ?

> when **_some_** users take a picture, the application crash. 

> I found that this only happened with android 12 and HEIF quality photos.

3. do you receive other crashes on `crashlytics`? (maybe is misconfigured) 
   -  can you try in `release mode` instead of debug?

> I don't have a log because the debugger stop when the problem arrive and the application send nothing to crashlytics.

**Comment by danagbemava-nc** [comment]
Hi @Chonli, as noted above. We will need a minimal complete reproducible code sample so that we can investigate this. 

Please also try to provide answers to some of the questions in https://github.com/flutter/flutter/issues/116031#issuecomment-1328075022.

Thank you
