### ISSUE TITLE
When the application is killed(by swiping up the application to the top of screen in the multitask) then a warning message will be displayed.

### ISSUE THREAD

**Issue by hassanyassiin** [flutter/flutter#116181]
## Steps to Reproduce

When trying to kill the app(when the app is in the multitask in the IOS device and I try to kill it by swiping the app to the top) then these messages will appear.

    No windows have a root view controller, cannot save application state
    [ApplicationLifecycle] UIWindows were created prior to initial application activation. This may result in incorrect visual appearance.
    - [_UIRemoteKeyboards proxy]_block_invoke Failed to access remote service: Error Domain=NSCocoaErrorDomain Code=4099        "The connection to service named com.apple. UIKit KeyboardManagement hosted was invalidated from this process." UserInfo={NSDebugDescription=The connection to service named com .apple. UIKit. KeyboardManagement. hosted was invalidated from this process.}
    - Lost connection to device.

**Expected results:** 

The app is terminated/killed without an error.

**Actual results:**

The app is terminated/killed without an error.

[✓] Flutter (Channel stable, 3.3.9, on macOS 13.0.1 22A400 darwin-arm, locale
    en-LB)
    • Flutter version 3.3.9 on channel stable at
      /Users/hassanyassin/Desktop/Flutter/Development/Tools/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b8f7f1f986 (7 days ago), 2022-11-23 06:43:51 +0900
    • Engine revision 8f2221fbef
    • Dart version 2.18.5
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/hassanyassin/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.13+0-b1751.21-8125866)

[✓] Connected device (3 available)
    • iPhone (19) (mobile) • 08f6d5d4e6ac65273a8757fc2424f2f593e6ca56 • ios
      • iOS 16.1.1 20B101
    • macOS (desktop)      • macos                                    •
      darwin-arm64   • macOS 13.0.1 22A400 darwin-arm
    • Chrome (web)         • chrome                                   •
      web-javascript • Google Chrome 107.0.5304.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Comment by huycozy** [comment]
Hi @hassanyassiin 
Did you see that error message from XCode or other IDEs? From my end, when swiping up to kill the app, there is only one message `Lost connection to device.`. Tested on iPhone 14 Pro Max (iOS 16.1).

Also, does this issue happen on the minimal/simple Flutter project (such as default sample project - counter app)?

**Comment by huycozy** [comment]
Hi @hassanyassiin 
I still can not reproduce this issue after waiting 5 min and then killing the app. Would you mind recording a video for this?
And which device are you testing on? (model, OS version). Can we reproduce this issue with an emulator device?

**Comment by hassanyassiin** [comment]
Tested on iPhone X (real device), IOS Version :16.1.1. (Getting the same error with a default flutter app)

// Here the app is being for about 1 min in the background before I Killed it in the multitask, and the error stays.

// **Note:** When testing on iPhone 14 Pro Max(Emulator) with version 16.1 the error doesn't appear.


https://user-images.githubusercontent.com/94860683/205033465-ce47cbb2-4b9c-44b3-aa84-31942c4c5817.mov


    [✓] Flutter (Channel stable, 3.3.9, on macOS 13.0.1 22A400 darwin-arm, locale
    en-LB)
    • Flutter version 3.3.9 on channel stable at
      /Users/hassanyassin/Desktop/Flutter/Development/Tools/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b8f7f1f986 (9 days ago), 2022-11-23 06:43:51 +0900
    • Engine revision 8f2221fbef
    • Dart version 2.18.5
    • DevTools version 2.15.0

    [✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/hassanyassin/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

    [✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

    [✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

    [✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.13+0-b1751.21-8125866)

    [✓] Connected device (4 available)
    • iPhone X (mobile)          • 08f6d5d4e6ac65273a8757fc2424f2f593e6ca56 •
      ios            • iOS 16.1.1 20B101
    • iPhone 14 Pro Max (mobile) • B6B4CDD3-90C8-451E-B16D-563A2EF56E5F     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-1 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-arm64   • macOS 13.0.1 22A400 darwin-arm
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 108.0.5359.71

    [✓] HTTP Host Availability
    • All required HTTP hosts are available

    • No issues found!

**Comment by huycozy** [comment]
@hassanyassiin Below is the crash log I received when following your steps at https://github.com/flutter/flutter/issues/116181#issuecomment-1333576378. It's similar to crash log from your video (as Log 1 below) but they are still different than the [log from OP](https://github.com/flutter/flutter/issues/116181#issue-1468066629). 

Even when I try opening the keyboard (as the case mentioned at https://github.com/flutter/flutter/issues/116181#issuecomment-1332060344), the crash log still the same (Log 1).

Tested on iPhone 7, iOS 15.7. 

So, please try to replicate it consistently and see if it has any pattern to replicate the issue mentioned at OP.

<details>
<summary>Log 1</summary>

```bash
Syncing files to device iPhone...
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGKILL
    frame #0: 0x00000001bb6d8aac libsystem_kernel.dylib`mach_msg_trap + 8
libsystem_kernel.dylib`mach_msg_trap:
->  0x1bb6d8aac <+8>: ret    
libsystem_kernel.dylib`mach_msg_overwrite_trap:
    0x1bb6d8ab0 <+0>: mov    x16, #-0x20
    0x1bb6d8ab4 <+4>: svc    #0x80
    0x1bb6d8ab8 <+8>: ret    
Target 0: (Runner) stopped.
Lost connection to device.
```
</details>

**Comment by darshankawar** [comment]
@hassanyassiin 
Can you check if there's any background developer setting that is causing the log to show ? It seems that the app restoration is getting impacted due to some developer settings of the device (ex:  enable kill on background developer setting)

**Comment by hassanyassiin** [comment]
@darshankawar The application Launched as the default one (the counter application), I didn't modify anything in the settings or in Xcode, even though I didn't write any code or added  packages. So I don't know from where are these errors are coming. ! Did you tested on your real device and get the same errors as the videos ?

**Comment by darshankawar** [comment]
@hassanyassiin 
Check [this](https://master-api.flutter.dev/flutter/services/RestorationManager-class.html) document and steps mentioned in it and see if it helps in your case.

**Comment by hassanyassiin** [comment]
@darshankawar Can you please check the 4 issues above that I discussed in this [comment](https://github.com/flutter/flutter/issues/116181#issuecomment-1333756960).

I will check also the document that you mentioned above, but in this [comment](https://github.com/flutter/flutter/issues/116181#issuecomment-1333756960), I have four different issues

**Comment by darshankawar** [comment]
For better tracking and triage, I suggest you to open new issues for each point you mentioned if you think they are unique and not related to each other and not already filed (you can search for existing similar issues first)

**Comment by hassanyassiin** [comment]
@darshankawar Thanks for your help, I will open new issues for each one, because I made a lot of researches about these issues and I didn't get any solution.
