### ISSUE TITLE
Fuchsia Linux SDK -> Flutter Engine Rolls failing to create CLs

### ISSUE THREAD

**Issue by iskakaushik** [flutter/flutter#116124]
Error:

```
      1534 of 1929 ████████░░ 80% (0 missing licenses)  .../internal/intrusive_container/wavl_tree_internal.h
error searching for copyright in: ../../../fuchsia/sdk/linux/pkg/fidl_cpp_wire/include/lib/fidl/cpp/wire/internal/client_continuation.h
failed to find template LICENSE
// in ../../../fuchsia/sdk/linux/pkg/fidl_cpp_wire/include/lib/fidl/cpp/wire/internal (authors=The Fuchsia Authors)
```

**Comment by iskakaushik** [comment]
cc: @akbiggs

**Comment by zanderso** [comment]
@akbiggs @bergkampben Is there any update on this issue?

**Comment by jason-simmons** [comment]
https://fuchsia.googlesource.com/fuchsia/+/0f6c1028ea9574134c983b05881c0ac926091009 landed, which should fix this

**Comment by zanderso** [comment]
Monday morning update: Not sure whether the above patch is included, but the SDK rollers are continuing to fail to create a CL due to a license check failure.

**Comment by akbiggs** [comment]
Where do we go to see these failures? I'm confused why it's happening at CL creation time instead of in the presubmits for the CL, i.e. why it's not showing up here https://autoroll.skia.org/r/fuchsia-linux-sdk-flutter-engine

**Comment by chinmaygarde** [comment]
@rmistry may be able to tell where to spot the logs. [The purported fix has landed](https://fuchsia.googlesource.com/fuchsia/+/0f6c1028ea9574134c983b05881c0ac926091009) but has not rolled in.

**Comment by rmistry** [comment]
The current failure in the logs:

```
D1205 18:57:38.789108      15 firestore.go:204] Active operations (0): 
      3009 of 3009 ██████████ 100% (0 missing licenses)  Done.                                                                        
Collecting licenses for fuchsia
      1534 of 1929 ████████░░ 80% (0 missing licenses)  .../internal/intrusive_container/wavl_tree_internal.h                
error searching for copyright in: ../../../fuchsia/sdk/linux/pkg/fidl_cpp_wire/include/lib/fidl/cpp/wire/internal/client_continuation.h
failed to find template LICENSE
// in ../../../fuchsia/sdk/linux/pkg/fidl_cpp_wire/include/lib/fidl/cpp/wire/internal (authors=The Fuchsia Authors)


D1205 18:58:37.709966      15 firestore.go:204] Active operations (0): 
D1205 18:58:38.789993      15 firestore.go:204] Active operations (0): 
      1918 of 1929 █████████░ 99% (1 missing licenses)  ../../../fuchsia/sdk/linux/pkg/zx/process.ccfailure: Had failures while collecting licenses.
#0      _collectLicensesForComponent (package:licenses/main.dart:2855:5)
<asynchronous suspension>
#1      main (package:licenses/main.dart:3028:9)
<asynchronous suspension>
```

**Comment by akbiggs** [comment]
Where do I go to view these logs? I want to understand what version of the Fuchsia SDK it's trying to roll.

**Comment by rmistry** [comment]
These rollers are in skia-infra-public and skia-infra-corp corp projects where temporary permission can be given if necessary, but typically only the Skia infra team has access. We should separately look into creating a group that has cloud logs view access. But till then, this is where it is trying to roll to:

```
I1205 18:51:14.541663      15 autoroller.go:596] lastRollRev is: NlJGkMbtZqQ6_BCpu5Mif5-14birO7qsn-VP2ULJK8MC
I1205 18:51:14.541691      15 autoroller.go:597] tipRev is:      1QmlBWEgHc9ftV0CQ0QgZIqa-xdic8DijJh74fjm1TEC
I1205 18:51:14.541698      15 autoroller.go:598] nextRollRev is: 1QmlBWEgHc9ftV0CQ0QgZIqa-xdic8DijJh74fjm1TEC
```

**Comment by akbiggs** [comment]
Thanks. I downloaded that SDK rev https://chrome-infra-packages.appspot.com/p/fuchsia/sdk/core/linux-amd64/+/1QmlBWEgHc9ftV0CQ0QgZIqa-xdic8DijJh74fjm1TEC and it doesn't have Ben's fix yet. It's only a few days old so hopefully it should be picked up soon, it looks like the roller is still trying to roll to the latest instead of some much older package.

So I think we just need to wait here for another day or two.
