### ISSUE TITLE
Would be nice to show more font rendering in Gallery

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#11615]
While listening to @GaryQian's talk last week it occurred to me there are many more text-related examples we could show in the gallery, such as:

* Colored Emoji
* RTL Text
* Large blocks of text (scrolls nicely, quickly).

**Comment by sethladd** [comment]
See also https://github.com/flutter/flutter/issues/6559

**Comment by MetalDent** [comment]
Is anyone working on this?

**Comment by eseidelGoogle** [comment]
I doubt we still need this open.  @willlarche and co. have done lots of work to update the gallery.
