### ISSUE TITLE
Failed `flutter pub get` in the legacy analyze should output error

### ISSUE THREAD

**Issue by bparrishMines** [flutter/flutter#116192]
When `flutter pub get` fails to finish in the [flutter/plugins](https://github.com/flutter/plugins) `legacy_version_analyze` test, it leads to a timeout and doesn't print out an error. 

For example, this happened when `webview_flutter_android` bumped the minimum Flutter version to `3.3.0` in https://github.com/flutter/plugins/pull/6686. When legacy analyze ran on `webview_flutter` with Flutter version `3.0.5`, the analyze test would timeout.

#### Example of current output

```
[12:45] Running for webview_flutter/webview_flutter...
Running command: "flutter pub get" in /tmp/cirrus-ci-build/packages/webview_flutter/webview_flutter
Running "flutter pub get" in webview_flutter...     

Timed out!
```

#### Desired output

```
Running "flutter pub get" in webview_flutter...                 
The current Flutter SDK version is 3.0.5.

Because webview_flutter depends on webview_flutter_android from path which requires Flutter SDK version >=3.3.0, version solving failed.
pub get failed (1; Because webview_flutter depends on webview_flutter_android from path which requires Flutter SDK version >=3.3.0, version solving failed.)
Process finished with exit code 1
```

**Comment by stuartmorgan** [comment]
Unfortunately this is a general problem with `pub get` in CI: https://github.com/flutter/flutter/issues/74700

**Comment by nehalvpatel** [comment]
Actually, this should be fixed by this PR: https://github.com/flutter/flutter/pull/115801. 😃

I'm not sure which release it will end up in yet.
