### ISSUE TITLE
Should we hero the year to the top of the dialog in the date picker?

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#11611]
Posse has received a lot of negative feedback in their app about use of the Material Design date picker (see also https://github.com/flutter/flutter/issues/11610).  One suggestion @collinjackson had is that in addition to possibly doing (https://github.com/flutter/flutter/issues/11610) we could also use a hero effect on the selected year from where it was selected to the top of the dialog to make clear that the year is selectable.  Thoughts?  @Hixie @HansMuller?

**Comment by collinjackson** [comment]
It seems like the Material date picker may be more useful for picking dates in the near future. For dates in the distant past, the day of the week isn't relevant, so perhaps a different date entry mechanism would feel more natural.

Here's an [example](https://gist.github.com/collinjackson/4e4f76143338d20efc4caeba6a7367f9) of building a date picker using [package:numberpicker](https://www.dartdocs.org/documentation/numberpicker/0.1.0/numberpicker/NumberPicker-class.html).

![screen shot 2017-08-15 at 10 15 16 am](https://user-images.githubusercontent.com/394889/29327053-a71b6552-81a2-11e7-9263-4db10ffc841d.png)
