### ISSUE TITLE
webview_flutter not working on iPhone after iOS 16.1.1 update

### ISSUE THREAD

**Issue by Alihasaan** [flutter/flutter#116100]
I am using webview_flutter 3.0.4 to load a login web page in iOS I have tried both on the simulator and on the device the app loading it shows the webpage login page for a few milliseconds and then crashes and I get this error 
`WKErrorDomain WebResourceErrorType.webContentProcessTerminated`

I am using a Webpage URL that uses OAuth 2.0 to generate a unique login challenge every time.

Flutter doctor -v output :
```
[✓] Flutter (Channel stable, 3.3.9, on macOS 13.0.1 22A400 darwin-x64, locale en-US)
    • Flutter version 3.3.9 on channel stable at /Users/test/Developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b8f7f1f986 (6 days ago), 2022-11-23 06:43:51 +0900
    • Engine revision 8f2221fbef
    • Dart version 2.18.5
    • DevTools version 2.15.0
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.
[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3
[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
[✓] VS Code (version 1.63.2)
    • VS Code at /Users/test/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.36.0
[✓] Connected device (1 available)
    • macOS (desktop) • macos • darwin-x64 • macOS 13.0.1 22A400 darwin-x64
[✓] HTTP Host Availability
```
Code Of WebView : 

```dart
WebView(
                   onWebResourceError: (error){
                     print(error.domain);
                     print(error.errorType);
                     print(error.failingUrl);
                   },
                    zoomEnabled: false,
                    initialUrl: url,
                    javascriptMode: JavascriptMode.unrestricted,
                    navigationDelegate: (NavigationRequest request) async {
                      if (request.url.contains(“authenticated?redirect”)) {
                        await unsubFromOldFCMtopics(“From LOgin”);
                        //You can do anything
                        Navigator.push(
                            context,
                            MaterialPageRoute(
                                builder: (c) => MainScreen(),
                                settings: RouteSettings(name: “main-screen”)));
                        //Prevent that url works
                        return NavigationDecision.prevent;
                      }
                      //Any other url works
                      return NavigationDecision.navigate;
                    },
                    onPageStarted: (urli) {
                     print(urli);
                    },
                    onPageFinished: (_) async {
                       print(_);
                      final gotCookies = await cookieManager.getCookies(url);
                      if (gotCookies.isNotEmpty) {
                        Provider.of<AppData>(context, listen: false)
                            .updateCookies(gotCookies[0].value.toString());
                      }
                    },
                    onWebViewCreated: (WebViewController webViewController) {
                      _Webcontroller = webViewController;
                      if (_controller.isCompleted == false) {
                        _controller.complete(webViewController);
                      }
                    },
                  )
```

Note : Also the webpage loads fine when i disable the JavascriptMode but then no buttons on the webpage work.

**Comment by danagbemava-nc** [comment]
Hi @Alihasaan, do you have this issue with a specific URL, or do you experience the issue with every URL you open?

If it is a specific URL, kindly share a complete minimal runnable sample that we can use without any major modification so that we can investigate this. 

PS: I tested a sample webview by opening the flutter.dev site on iPadOS 16.1.1 and it worked just fine.

**Comment by Alihasaan** [comment]
Hi Daniel,

Thanks for reaching out.

Yeah I have experienced this issue with the following URL

https://ti.do.si-dev.net

**Comment by danagbemava-nc** [comment]
Hi @Alihasaan, what version of iOS were you on prior to 16.1.1? 

If you started experiencing this bug after an iOS upgrade, there's a chance that this issue is not related to the plugin but possibly something in iOS.

**Comment by Alihasaan** [comment]
It works on all iOS version below 16.1.1 even works on 16.0

**Comment by danagbemava-nc** [comment]
Hi @Alihasaan, it appears that this is a bug in `WebKit` as I tried a native iOS code sample and the bug reproduced there as well. 

You may need to file a bug report with apple so they can investigate this. You can try the code sample I used for yourself to see. Just create a native ios project in XCode but do not use SwiftUI as the UI framework and replace the content of the `ViewController.swift` file with the code below. 

<details>
<summary>native code sample</summary>

```swift
//
//  ViewController.swift
//  Wb
//
//

import UIKit
import WebKit

class ViewController: UIViewController, WKNavigationDelegate {
    
    var webView: WKWebView!
    private func createWebView() {
        let preferences = WKWebpagePreferences()
        preferences.allowsContentJavaScript = true
        
        let configuration = WKWebViewConfiguration()
        configuration.defaultWebpagePreferences = preferences
        
        webView = WKWebView(frame: view.bounds, configuration: configuration)
        webView.navigationDelegate = self
        
        view.addSubview(webView)
    }
    
    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view.
        createWebView()
        
        let url = URL(string: "https://ti.do.si-dev.net/")!
        webView.load(URLRequest(url: url))
        webView.allowsBackForwardNavigationGestures = true
    }

}
```
</details>

Closing this as this is a bug in WebKit. 

Thank you

**Comment by Alihasaan** [comment]
Hi @danagbemava-nc ,
I have managed to fix this issue in Native iOS it was related to the shared worker. 
`import UIKit
import WebKit
class ViewController: UIViewController, WKNavigationDelegate {
  var webView: WKWebView!
  private func createWebView() {
    let preferences = WKWebpagePreferences()
    preferences.allowsContentJavaScript = true
    let configuration = WKWebViewConfiguration()
    configuration.defaultWebpagePreferences = preferences
    webView = WKWebView(frame: view.bounds, configuration: makeViewConfiguration())
    webView.navigationDelegate = self
    view.addSubview(webView)
  }
  override func viewDidLoad() {
    super.viewDidLoad()
    // Do any additional setup after loading the view.
    createWebView()
    let url = URL(string: “https://ti.do.si-dev.net/”)!
    webView.load(URLRequest(url: url))
    webView.allowsBackForwardNavigationGestures = true
  }
  func makeViewConfiguration() -> WKWebViewConfiguration
  {
    let configuration = WKWebViewConfiguration()
    let dropSharedWorkersScript = WKUserScript(source: “delete window.SharedWorker;“, injectionTime: WKUserScriptInjectionTime.atDocumentStart, forMainFrameOnly: false)
    configuration.userContentController.addUserScript(dropSharedWorkersScript)
    return configuration
  }
}`

Is there any way to implement this in webview_flutter ?
