### ISSUE TITLE
AdaptiveScaffold - NavigationRail color is set to transparent

### ISSUE THREAD

**Issue by ThiemoImgraben** [flutter/flutter#116182]
In the flutter_adaptive_scaffold, is the NavigationRail color set to transparent, thereby it can not be overwritten with the NavigationRailTheme.

adaptive_scaffold.dart

```
 static Builder standardNavigationRail({
    required List<NavigationRailDestination> destinations,
    double width = 72,
    int selectedIndex = 0,
    bool extended = false,
    Color backgroundColor = Colors.transparent,
    EdgeInsetsGeometry padding = const EdgeInsets.all(8.0),
    Widget? leading,
    Widget? trailing,
    Function(int)? onDestinationSelected,
    IconThemeData selectedIconTheme = const IconThemeData(color: Colors.black),
    IconThemeData unselectedIconTheme =
        const IconThemeData(color: Colors.black),
    TextStyle selectedLabelTextStyle = const TextStyle(color: Colors.black),
    NavigationRailLabelType labelType = NavigationRailLabelType.none,
  })
```

**Comment by huycozy** [comment]
@ThiemoImgraben Are you mentioning `backgroundColor`? As I see, you still can change it as the example:

https://github.com/flutter/packages/blob/d5d3b46f3f1db0cfe0a52b9396949fe195f96a6a/packages/flutter_adaptive_scaffold/example/lib/main.dart#L221-L235

**Comment by ThiemoImgraben** [comment]
Hi huycozy, in my case I'm using the default AdaptiveScaffold constructor. 
Here I would expect the NavRail to work via the app theming, which is not the case. The background color is set to transparent.

**Comment by huycozy** [comment]
@ThiemoImgraben Please check this issue #114595 if it's similar to this.
