### ISSUE TITLE
Linux docs_publish is failing on a firebase limit

### ISSUE THREAD

**Issue by Piinks** [flutter/flutter#116131]
The tree is currently closed on a firebase issue in the docs_publish task

https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20docs_publish/7775/overview

```
/b/s/w/ir/x/w/firebase/firebase: line 1: syntax error near unexpected token `<'
/b/s/w/ir/x/w/firebase/firebase: line 1: `﻿<?xml version="1.0" encoding="utf-8"?><Error><Code>ServerBusy</Code><Message>Egress is over the account limit.'
```

**Comment by Piinks** [comment]
Lowering to P1, the tree is green after rerunning the task.

**Comment by drewroengoogle** [comment]
Link to the failed build: https://ci.chromium.org/p/flutter/builders/prod/Linux%20docs_publish/7775

**Comment by drewroengoogle** [comment]
Tried going back and finding a similar issue with no success - Will keep an eye on this and see if it emerges again.
