### ISSUE TITLE
[local_auth][Ios] isDeviceSupported returns always true 

### ISSUE THREAD

**Issue by meandmymonkey7** [flutter/flutter#116179]
As you can see at LocalAuthPlugin.m file, lines 42 - 43 isDeviceSupported function is not implemented but instead value YES is always returned.

 We would need the same functionality as Android to be able to know if any authentication method is available (including passcode) not just biometrics. At some parts of our app we have the need to not actually ask for authentication but just allow some action if any authentication method is enabled. 

https://github.com/flutter/plugins/blob/main/packages/local_auth/local_auth_ios/ios/Classes/FLTLocalAuthPlugin.m

```
} else if ([@"isDeviceSupported" isEqualToString:call.method]) {
    result(@YES);
```

**Comment by huycozy** [comment]
Thanks for filing this. Labeling the issue as a proposal. Plugin version: `local_auth: ^2.1.2`.

**Comment by AkhmadRamadani** [comment]
does this issue still happening?

**Comment by bialio** [comment]
This does still occur in version 2.1.7.

**Comment by Imgkl** [comment]
Any updates? it's almost a year since this issue was first identified, is there any workarounds?
