### ISSUE TITLE
[Impeller] Allow vertex layout customization at runtime.

### ISSUE THREAD

**Issue by bdero** [flutter/flutter#116168]
Impeller's assumedly staggered vertex layout beautifully mixes with the ImpellerC's generated headers to offer predictable and easy to use default vertex binding behavior that fits the bill for most use cases. However, there are times where taking full control of the vertex layout can offer performance benefits.

Examples:
* **Structure of arrays:** For `VerticesGeometry`, the `DisplayList` vertices are given in an SOA structure, so we're forced to unnecessarily convert the data into a staggered form on the CPU before uploading to the GPU.
* **Binding vertices across multiple buffers:** In https://github.com/flutter/flutter/issues/116165, being able to bind two buffers (one with only vertex positions and another with other attributes like position and color) would allow easy reuse of position buffers for common shapes regardless of the color source.
* **Industry standard formats:** Impeller is slated to help a lot of people do great things, some of which I believe will involve consuming industry standard 3D geometry intended for efficient runtime consumption by renderers. Vertex attributes for 3D models are often stored in an SOA format which can be uploaded directly to the GPU without conversion given the ability to control the vertex layout at runtime. Some formats, such as GLTF, even offer arbitrary vertex layout customization. Without control over the vertex layout, renderers build on Impeller that consume these standards will be forced to convert the geometry to a staggered form with a specific attribute ordering prior to GPU upload.

A good design for vertex layout customization would implicitly address https://github.com/flutter/flutter/issues/102778.

**Comment by jonahwilliams** [comment]
Current set of work on this involves making the interleaved layout explicit in the impeller backend generated shaders. This will force us to expose a reasonable API for customizing vertex layout.

**Comment by bdero** [comment]
Copying from https://github.com/flutter/flutter/issues/139560:

We should mirror how vertex attributes work on the backends.

Currently, the stride is tied to a `ShaderStageBufferLayout`, which itself is tied to a specific binding. So we're forcing each binding to contain an interleaved layout, and it's not currently possible to bind a basic single-buffer SoA layout. This is important for efficiently loading common interchange formats like glTFs and is easy to accomplish on all backends.

Remove the `ShaderStageBufferLayout` concept. An array of attributes _is_ an attribute layout. The default interleaved layout output in the impellerc reflection header should just be an array of attributes.

Each attribute should have:
* a binding (the index of a bound vertex buffer -- multiple vertex buffers should be allowed),
* an offset (the byte offset of the zero index element of the attribute),
* a stride (the byte offset in-between the start of each successive element of the attribute), and
* element type information (including the byte size of an element, etc).

**Comment by bdero** [comment]
Started digging into what we've landed so far again and I think we're actually good to go in terms of the shape of the pipeline layout description itself. Similar to Metal and Vulkan, `ShaderStageBufferLayout::binding` and `ShaderStageIOSlot::binding` both refer to the index of a theoretical vertex buffer binding list. These "bindings" are actually buffer views.

The pipeline binding for Vulkan and Metal look reasonable. We just need to allow binding multiple vertex buffers per command.
