### ISSUE TITLE
[ci] Update flutter/plugins release job dependencies

### ISSUE THREAD

**Issue by ditman** [flutter/flutter#116150]
The current `lewagon/wait-on-check-action` in the `flutter/plugins` and `flutter/packages` **release** job is throwing a number of deprecation warnings coming from its dependencies:

**ruby/setup-ruby@1.81.0**

```
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using
Environment Files. For more information see:
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```

**actions/cache@v2**

```
Warning: The `save-state` command is deprecated and will be disabled soon. Please upgrade to using
Environment Files. For more information see:
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```

**We should whitelist and update `lewagon/wait-on-check-action` to a version that has updated dependencies.**

_(Reported issue: https://github.com/lewagon/wait-on-check-action/issues/76)_

**Comment by ditman** [comment]
Ah cool! I think in this case the fix needs to happen in the `lewagon/wait-on-check-action` repo, though!

**Comment by godofredoc** [comment]
Fixed `lewagon/wait-on-check-action`. Should we close this bug?

**Comment by stuartmorgan** [comment]
Sounds like it should be resolved.
