### ISSUE TITLE
Firebase podspecs should depend on a minimum Firebase version

### ISSUE THREAD

**Issue by collinjackson** [flutter/flutter#11618]
Our Firebase plugins don't specify the minimum Firebase pod version they depend on, e.g. in [firebase_database.podspec](https://github.com/flutter/plugins/blob/master/packages/firebase_database/ios/firebase_database.podspec) it just says `s.dependency 'Firebase/Database'`.

If we specified a minimum Firebase version then there would be a more helpful error message if the pod repo is out of date.

## Steps to Reproduce

Have an old Cocoapods checkout, e.g. cdc7dc8e739
Build an iOS app that relies on Firebase Database or Analytics or Messaging
Get build errors, either in the plugins (`persistenceCacheSizeBytes` and `setScreenName:screenClass:` do not exist) or in the app itself, e.g.

```
    error: no type or protocol named 'FIRMessagingDelegate'
    @interface AppDelegate : FlutterAppDelegate<FIRMessagingDelegate>
                                                ^
    1 error generated.
```

Running `pod repo update` and blowing away `Podfile.lock` and `Pods/` fixed it.

```
$ pod repo update
Updating spec repo `master`
Performing a deep fetch of the `master` specs repo to improve future performance
  $ /usr/local/git/current/bin/git -C /Users/jackson/.cocoapods/repos/master fetch origin
  From https://github.com/CocoaPods/Specs
     cdc7dc8e739..6a8d8a27f6f  master     -> origin/master
  $ /usr/local/git/current/bin/git -C /Users/jackson/.cocoapods/repos/master rev-parse --abbrev-ref HEAD
  master
  $ /usr/local/git/current/bin/git -C /Users/jackson/.cocoapods/repos/master reset --hard origin/master
  Checking out files: 100% (275161/275161), done.
  HEAD is now at 6a8d8a27f6f [Add] MapboxNavigation 0.6.1
warning: inexact rename detection was skipped due to too many files.

CocoaPods 1.3.1 is available.
To update use: `sudo gem install cocoapods`

For more information, see https://blog.cocoapods.org and the CHANGELOG for this version at https://github.com/CocoaPods/CocoaPods/releases/tag/1.3.1
```

**Comment by kroikie** [comment]
@collinjackson

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/973. Any further collaboration will be done there.
