### ISSUE TITLE
Flutter should show / instead of a black screen on iOS if you pop the last route

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#11612]
On Android, we quit the app if you pop the last route.  On iOS we show a black screen.

This came up in discussions with Posse this morning and @collinjackson suggested that maybe we should just show / instead of a black screen in the iOS case.  This happens because on iOS it's not possible to self-terminate an app.

Thoughts?  @Hixie

**Comment by Hixie** [comment]
Dupe of https://github.com/flutter/flutter/issues/9577

On iOS it is a bug in the app if it is possible to pop the last route.
