### ISSUE TITLE
The Dart -> Engine roll is stopped.

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#116107]
Beginning with the Engine -> Framework roll https://github.com/flutter/flutter/pull/116033. A change to `pub` is causing the `pub` step on Flutter CI to fail.

A revert of Dart rolls is here to unblock the Engine -> Framework roll: https://github.com/flutter/engine/pull/37934.

@jason-simmons bisected the failure to https://dart.googlesource.com/pub/+/327d9ee8425e1b33832a68112195c7ff45528c7f%5E%21/#F0

An example failure is here: https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20tool_tests_general/18462/overview

Quoted here:
```
Running "flutter pub get" in synthetic_package...                1,579ms
Resolving dependencies in ../../t/flutter_tools.WWEGNI/flutter_update_packages.EBYZVC/synthetic_package...
Error on line 1, column 42: Mapping values are not allowed here. Did you miss a colon earlier?
  ╷
1 │ name: assets_for_android_viewsdescription: Recorded touch event sequencesversion : 0.1.0author: Flutter Team <flutter-dev@googlegroups.com>homepage: http://flutter.ioenvironment:  sdk: '>=1.19.0 <3.0.0'  flutter: '>=0.1.0 <2.0.0'flutter:  assets:    - assets/touchEvents
  │                                          ^
  ╵
pub get failed
command: "/b/s/w/ir/x/w/flutter/bin/cache/dart-sdk/bin/dart __deprecated_pub --directory ../../t/flutter_tools.WWEGNI/flutter_update_packages.EBYZVC/synthetic_package get --example"
pub env: {
  "FLUTTER_ROOT": "/b/s/w/ir/x/w/flutter",
  "PUB_ENVIRONMENT": "flutter_bot:flutter_cli:update_packages",
  "PUB_CACHE": "/b/s/w/ir/x/w/.pub-cache",
}
exit code: 65
last line of pub output: "╵"
```

cc @a-siva @sigurdm @liamappelbe @iskakaushik

**Comment by zanderso** [comment]
Even after the above Dart SDK reverts, the roll is still failing with analysis errors: https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8796236498075545489/+/u/Analyze/analyze/test_stdout

**Comment by a-siva** [comment]
This is probably because of this
https://dart-review.googlesource.com/c/sdk/+/271920 which deprecates
NullThrownError

**Comment by a-siva** [comment]
Probably because of https://dart-review.googlesource.com/c/sdk/+/271920 which deprecates Nu;llThrownError

**Comment by zanderso** [comment]
The migration for the deprecation of `NullThrownError` appears non-trivial. Reverting Dart SDK to back before the deprecation: https://github.com/flutter/engine/pull/37937.

cc @lrhn.

**Comment by a-siva** [comment]
We should probably revert the deprecation CL from Dart and do the migration first in Flutter before landing this CL

**Comment by zanderso** [comment]
We should investigate why the deprecation didn't break the `fa` bot in this run: https://ci.chromium.org/ui/p/dart/builders/ci.sandbox/flutter-analyze/18030/overview.

**Comment by mit-mit** [comment]
What is the connection between an error being deprecated and a failure in pub resolution? I can't make any sense of how those two are connected?

**Comment by a-siva** [comment]
The first error was related to a pub resolution failure but the second one is analyzer failures, see https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8796236498075545489/+/u/Analyze/analyze/test_stdout

**Comment by mit-mit** [comment]
> We should probably revert the deprecation CL from Dart and do the migration first in Flutter before landing this CL

We need the deprecated in 2.19, and it's my understanding we're about to cut that build. Can we turn of whatever checking Flutter insists to do on deprecated members?

**Comment by mit-mit** [comment]
Made an attempt at fixing forward: https://github.com/flutter/flutter/pull/116122

**Comment by zanderso** [comment]
The deprecated checking is on by policy. @Hixie can give the background there, I think.

**Comment by Piinks** [comment]
Noted on https://github.com/flutter/flutter/pull/116122, there were ignores in place that were removed in a clean up (https://github.com/flutter/flutter/pull/108915/files) that appear to be needed now.

`// ignore: deprecated_member_use` should be added back to resolve this.

**Comment by mit-mit** [comment]
Adding back in https://github.com/flutter/flutter/pull/116135

**Comment by a-siva** [comment]
We are having some Dart infra issues, I am waiting for those to be resolved before starting a manual roll into the dev branch.

**Comment by zanderso** [comment]
The Dart roller is still stopped for release branch alignment, but the above two issues have been resolved, so I'm going to close this issue. Restarting the Dart roller when alignment is finished will take place next week.
