### ISSUE TITLE
[web] Cleanup: TouchEvents, MouseEvents in Pointer Binding.

### ISSUE THREAD

**Issue by ditman** [flutter/flutter#116141]
The current web engine sources Pointer (mouse/tap) events from different APIs, [depending on browser support](https://github.com/flutter/engine/blob/f326b630dd3a1efe0c225a94775530367a6dd8dd/lib/web_ui/lib/src/engine/pointer_binding.dart#L172-L174):

* PointerEvent ([caniuse](https://caniuse.com/mdn-api_pointerevent) -> **preferred API**)
* TouchEvent ([caniuse](https://caniuse.com/mdn-api_touchevent) -> fallback for Safari Mobile <13)
* MouseEvent ([caniuse](https://caniuse.com/mdn-api_mouseevent) -> fallback for Safari Desktop <13)

The feature detection is also very trivial:

* https://github.com/flutter/engine/blob/f326b630dd3a1efe0c225a94775530367a6dd8dd/lib/web_ui/lib/src/engine/pointer_binding.dart#L172-L174

The latest release of **Safari 12 (12.1.2)** happened on:

* [MacOS 10.14](https://en.wikipedia.org/wiki/Safari_version_history#Safari_12) (Mojave), which Apple hasn't supported [since October 2021](https://endoflife.date/macos)
* [iOS 12.5.5](https://en.wikipedia.org/wiki/Safari_version_history#Safari_12_2), which Apple hasn't supported [since August 2022](https://endoflife.date/ios)

### Proposal

**Let's remove `TouchEvents` and `MouseEvents` as sources of PointerEvents from the `pointer_binding.dart` file** above, to simplify it a lot, and maybe reduce a little bit the engine size along the way (this is minor).

**Comment by yjbanov** [comment]
We probably don't want to support all this in the custom element mode. Making it a P3, treating it as a soft blocker for the custom element work.

**Comment by ditman** [comment]
Follow up of: https://github.com/flutter/engine/pull/37738
