### ISSUE TITLE
[ci] Update codeql-action in flutter/plugins scorecards-analysis.yml

### ISSUE THREAD

**Issue by ditman** [flutter/flutter#116149]
I just noticed that the flutter/plugins `Scorecards analysis` action is throwing a deprecation warning from the `codeql-action/upload-sarif` action:

```
Run github/codeql-action/upload-sarif@807578363a7869ca324a79039e6db9c843e0e100
Uploading results

Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using
Environment Files. For more information see:
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```

This has already been [fixed upstream](https://github.com/github/codeql-action/pull/1301), so I think that all we need to do is to whitelist and use a newer version of the `codeql-action`, [here](https://github.com/flutter/plugins/blob/bdf1a98a12aaad6887ca73dfd738f90c030f57d2/.github/workflows/scorecards-analysis.yml#L53).

See the [changelog of the action](https://github.com/github/codeql-action/blob/main/CHANGELOG.md) to pick a new hash.

**(Note: this is not affecting flutter/packages because it's using a different version of the action? `github/codeql-action/upload-sarif@678fc3afe258fb2e0cdc165ccf77b85719de7b3c`)**

**Comment by ditman** [comment]
It seems that flutter/flutter, flutter/engine, flutter/packages and flutter/plugins are using slightly different versions of the action, those should probably be unified :/

**Comment by godofredoc** [comment]
We should probably add the autosubmit label to dependabot github action updates. 

https://github.com/flutter/plugins/pull/6712 was opened but not landed.

**Comment by ditman** [comment]
I had no idea that dependabot was reporting also on github actions themselves! Thanks for the pointer @godofredoc!

**Comment by ditman** [comment]
This is fixed now. Compare:

* Updated run: https://github.com/flutter/plugins/actions/runs/3631938479
* Outdated run: https://github.com/flutter/plugins/actions/runs/3622983950

Thanks @bparrishMines!
