### ISSUE TITLE
[google_maps_flutter] Android -  Polygons not filling with color when they overlap itselves.

### ISSUE THREAD

**Issue by feralv16** [flutter/flutter#116115]
Hello everyone, I encountered a bug that only happens on Android.
Here is an example of what's happening. On iOS, this is working as expected.
P.D. This also happens if you try to complete the polygon from the initial coordinate instead of the final one. Lets say you have an starting coordinate at (0,0) an at the end (100,200). If you try to complete the figure starting from (0,0) and adding the missing coordinates, the polygon won't be filled. A graphic example of this:
`[LatLng(0, 0),...LatLng(100,200), LatLng(1,2), LatLng(2,3),...]` This will make the polygon to not be filled.
`[LatLng(0, 0),...LatLng(100,200), LatLng(98,198), LatLng(96,195),...]` This will work as expected
**Steps to reproduce**
1) Add polygon that overlaps itself
**Expected**
- Polygon should fill with the expected color

**Actual**
- Polygon is not filled with the expected color

![image](https://user-images.githubusercontent.com/118540884/204331848-a17ee69b-f21e-44fd-96fb-ca993a4c8e98.png)

**Comment by huycozy** [comment]
Hi @feralv16 
Please provide the information indicated below:
- A [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
- Visual of expected result if it's possible
- The output of `flutter doctor -v`
- `google_maps_flutter ` plugin version 

Thank you!
