### ISSUE TITLE
List.generate for 2d/3d list bug

### ISSUE THREAD

**Issue by WizardingStudios** [flutter/flutter#116187]
If we create a 2d/3d list by this way:

```
  List recipes = List.generate(
      999,
      (i) => List.generate(
          999,
          (i) => List<Ingredient>.filled(
              0,
              Ingredient(
                  name: '',
                  carbohydrates: 0,
                  proteins: 0,
                  lipids: 0,
                  fibers: 0),
              growable: true)));
```

Please assume that Ingredient is a simple Class.

When we try to access it:

`print(recipes[0][0][0].name);`

Arriving at this point:

`print(recipes[0][0][0].`

We need to see (access) the Class properties (like kcal, name, carbohydrates...); exactly as in a one dimension list.

However, at least in VS Code, the code editor display this only: hashCode, runtimeType, toString(), noSuchMethod(...)

When I try to create the list by this way: 

```
List<List<List<Ingredient>>> ingredient =
      List.generate(999, (index) => [[]], growable: true); 
```

This bug does not exists, but I have no idea on how to fill (give a dimension) the first and the second list...

**Comment by darshankawar** [comment]
@WizardingStudios 
I think your issue is more suited for https://github.com/dart-lang/sdk/issues as it has to do with dart language and not Flutter, so please file the same in dedicated repo.
Closing from here.
