### ISSUE TITLE
video_player crash and a lot of app DidBecomeActive crash on iOS

### ISSUE THREAD

**Issue by anchaoLu** [flutter/flutter#116245]
random crash when app DidBecomeActive
there are some crash logs
<img width="678" alt="截屏2022-11-30 11 20 43" src="https://user-images.githubusercontent.com/106209730/204700490-51cf50c0-04dd-4ae8-a861-befc12e8ca9c.png">
<img width="1005" alt="203711086-2e5b7ee3-1390-4fac-80cf-f7265c23cc7c" src="https://user-images.githubusercontent.com/106209730/204700261-f39cbfd4-dfb0-4985-b335-24e31f0653be.png">
[AwesomeScreenshot-bugly-qq-v2-crash-reporting-crashes-1ed608dac0-1535003-2022-11-21_5_04.pdf.zip](https://github.com/flutter/flutter/files/10119089/AwesomeScreenshot-bugly-qq-v2-crash-reporting-crashes-1ed608dac0-1535003-2022-11-21_5_04.pdf.zip)
[AwesomeScreenshot-bugly-qq-v2-crash-reporting-crashes-1ed608dac0-1654002-2022-11-21_5_03.pdf.zip](https://github.com/flutter/flutter/files/10119091/AwesomeScreenshot-bugly-qq-v2-crash-reporting-crashes-1ed608dac0-1654002-2022-11-21_5_03.pdf.zip)
[Bugly.1.pdf](https://github.com/flutter/flutter/files/10119093/Bugly.1.pdf)
[Bugly.pdf](https://github.com/flutter/flutter/files/10119095/Bugly.pdf)

```
$ flutter doctor -v                                              
[✓] Flutter (Channel stable, 3.3.8, on macOS 12.6 21G115 darwin-arm, locale zh-Hans-CN)
    • Flutter version 3.3.8 on channel stable at /Users/luanchao/Desktop/Development/SDKS/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 52b3dc25f6 (12 days ago), 2022-11-09 12:09:26 +0800
    • Engine revision 857bd6b74c
    • Dart version 2.18.4
    • DevTools version 2.15.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/luanchao/Library/Android/sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.73.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.52.0

[✓] Connected device (3 available)
    • iPhone1 (mobile) • 00008101-001A4DC41440001E • ios            • iOS 15.6 19G71
    • macOS (desktop)  • macos                     • darwin-arm64   • macOS 12.6 21G115 darwin-arm
    • Chrome (web)     • chrome                    • web-javascript • Google Chrome 107.0.5304.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

**Comment by huycozy** [comment]
@anchaoLu Please provide the crash log in text format instead of a screenshot for better investigation. 
You may want to refer to [writing and formatting syntax](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) for beautifully formatted issue description.

Also, please provide the list of affected device info and the percentage occurrence of the crash. Thanks!

**Comment by anchaoLu** [comment]
crash log is from Tencent Bugly，there is no text log，only pdf.
and pdf contains all the devices info of the crash.
If that doesn't help, ignore it, then close this issue.

**Comment by huycozy** [comment]
@anchaoLu 
The crash log in pdf or image file will make it hard to investigate and it's not a suitable format for everyone can find it when they are encountered. 

We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away! 

Everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`. Thanks!
