### ISSUE TITLE
Expose more debugging options in stocks app

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#1162]
- [x] debugPaintSizeEnabled (only in checked mode)
- [x] turning on the statistics overlay (see https://github.com/flutter/flutter/pull/749/files)

**Comment by abarth** [comment]
I wonder if we should make this a feature of MaterialApp so that it's easy for everyone to get a stats overlay.

**Comment by Hixie** [comment]
Yeah that was my plan.

**Comment by eseidelGoogle** [comment]
So this was added only to stocks and not MaterialApp, correct?

**Comment by Hixie** [comment]
Stats overlay was added to both. The other one is just a bool so there's nothing to add to MaterialApp.
