### ISSUE TITLE
New font scaling system

### ISSUE THREAD

**Issue by chunhtai** [flutter/flutter#116231]
b/269358835

Android is proposing [new font scaling system](http://go/non-linear-font-scaling). We should make sure flutter is aligned with them.

**Comment by mhmdanas** [comment]
@chunhtai that link isn't a valid URL.

**Comment by chunhtai** [comment]
@mhmdanas The link is still confidential, and not ready to be public yet

**Comment by chunhtai** [comment]
lowering to P3, since we are targeting Q2 2023

**Comment by mariamhas** [comment]
linking PR: https://github.com/flutter/engine/pull/44907

Mostly feature complete, a few framework widgets have not been migrated.

**Comment by LongCatIsLooong** [comment]
Migration guide https://github.com/flutter/website/pull/9425

**Comment by mossmana** [comment]
@LongCatIsLooong This issue was assigned the team-android label, but it looks like most/all of the work was handled in the framework so I changed the team label to team-framework. If you're done with the work, is this an issue that can be closed?
