### ISSUE TITLE
Error waiting for a debug connection: The log reader failed unexpectedly

### ISSUE THREAD

**Issue by Pisey-Nguon** [flutter/flutter#116248]
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. I have run on simulator iOS then i found this issue but if i run on android is working fine.
3. After build done it just show white screen on iOS simulator
`Last login: Wed Nov 30 13:34:03 on console
nguonpisey@nguons-MacBook-Pro-2 tostinh_flutter % flutter run
Launching lib/main.dart on iPad Pro (12.9-inch) (4th generation) in debug
mode...
Running Xcode build...                                                  
 └─Compiling, linking and signing...                        14.5s
Xcode build done.                                           34.8s
Error waiting for a debug connection: The log reader failed unexpectedly
Error launching application on iPad Pro (12.9-inch) (4th generation).`

**Expected results:** 

**Actual results:** 

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
nguonpisey@nguons-MacBook-Pro-2 tostinh_flutter % flutter doctor -v
[✓] Flutter (Channel stable, 3.3.9, on macOS 13.0.1 22A400 darwin-x64, locale
    en-KH)
    • Flutter version 3.3.9 on channel stable at
      /Users/nguonpisey/Developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b8f7f1f986 (7 days ago), 2022-11-23 06:43:51 +0900
    • Engine revision 8f2221fbef
    • Dart version 2.18.5
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nguonpisey/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.73.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.54.0

[✓] Connected device (3 available)
    • iPad Pro (12.9-inch) (4th generation) (mobile) •
      1E355C3A-CC6E-4D2F-AE0A-0E4214FCB43B • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-13-7 (simulator)
    • macOS (desktop)                                • macos
      • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)                                   • chrome
      • web-javascript • Google Chrome 107.0.5304.121

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
nguonpisey@nguons-MacBook-Pro-2 tostinh_flutter % 
```

</details>

**Comment by darshankawar** [comment]
@Pisey-Nguon 
Can you provide `flutter doctor -v` and a minimal code sample that shows the reported issue ?
You said you are seeing this issue on iOS simulator, but from logs, you seem to be running on iPad. Please confirm on which device you are seeing the behavior.

**Comment by gabeschine** [comment]
`flutter doctor -v` output is in the _Logs_ section, which also shows that the iPad is an iOS 13.7 sim.

I'm able to reliably repro this running against any iOS 13.7 sim on an M1 MacBook Pro running `flutter run` on a vanilla Flutter app created with `flutter create`. No issues running against iOS 16.1 sims.

**Comment by Pisey-Nguon** [comment]
> @Pisey-Nguon
> Can you provide `flutter doctor -v` and a minimal code sample that shows the reported issue ?
> You said you are seeing this issue on iOS simulator, but from logs, you seem to be running on iPad. Please confirm on which device you are seeing the behavior.

this error is found on the simulator iPhone and iPad
Here is `flutter doctor -v`
```
Last login: Thu Dec  1 08:30:24 on console
nguonpisey@nguons-MacBook-Pro-2 ~ % flutter doctor -v
[✓] Flutter (Channel stable, 3.3.9, on macOS 13.0.1 22A400 darwin-x64, locale
    en-KH)
    • Flutter version 3.3.9 on channel stable at
      /Users/nguonpisey/Developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b8f7f1f986 (8 days ago), 2022-11-23 06:43:51 +0900
    • Engine revision 8f2221fbef
    • Dart version 2.18.5
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nguonpisey/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.73.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.54.0

[✓] Connected device (3 available)
    • MI 8 Lite (mobile) • 7174483 • android-arm64  • Android 12 (API 32)
    • macOS (desktop)    • macos   • darwin-x64     • macOS 13.0.1 22A400
      darwin-x64
    • Chrome (web)       • chrome  • web-javascript • Google Chrome
      107.0.5304.121

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
nguonpisey@nguons-MacBook-Pro-2 ~ % 

```

**Comment by jmagman** [comment]
This did not reproduce on my x64 Mac, but it did reproduce on my M1 Mac.  I don't see the white screen, the app actually launched, but I do see the `Error waiting for a debug connection: The log reader failed unexpectedly` error message.
When I run the command that should be getting the logs and parsing the observatory URL I see `Bad file descriptor`
```
$xcrun simctl spawn <simulator-ID> log stream --style json --predicate "eventType = logEvent AND processImagePath ENDSWITH "Runner" AND (senderImagePat ENDSWITH "/Flutter" OR senderImagePath ENDSWITH "/libswiftCore.dylib" OR processImageUUID == senderImageUUID)"
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=9):
Process spawn via launchd failed.
Bad file descriptor
Underlying error (domain=NSMachErrorDomain, code=9):
	The operation couldn’t be completed. (Mach error 9 - (os/kern) memory failure)
```
Suspect this is a bug in the simulator when calling `simctl spawn` on an x64 simulator (like iOS 13.7) on an ARM Mac.

**Comment by jmagman** [comment]
`--verbose` should be printing this error.

None of the following worked:
```
$ xcrun simctl spawn --arch=x86_64 <simulator-ID> echo hello
$ arch -x86_64 xcrun simctl spawn <simulator-ID> echo hello
$ xcrun simctl spawn --arch=x86_64 <simulator-ID> arch -x86_64 echo hello
```

**Comment by jmagman** [comment]
I'm not sure how Flutter can work around this.  I'll file a radar with Apple since it seems `xcrun simctl spawn` is just not working for x64 simulators on M1 Macs.

In the meantime, you can workaround and test on an iOS 13.7 or any older x64 simulator by running the app in Xcode from `ios/Runner.xcworkspace`, and then `flutter attach`ing on the command line.  I confirmed that works.

**Comment by jmagman** [comment]
We could stream the log from the Mac host and filter on the pid of the process running on the simulator, since it's actually running on the Mac (you can see it in Activity Monitor, for example).  Would also need to `log show` and recent logs from that pid in case the observatory logging happens between the time the app launches (and the pid is known) and when the Mac logs start streaming.   That would be a pretty big refactor of the iOS simulator log reader since it would have to only run once the process is launched and the pid is known.  

Could also stream logs from the Mac where the `processImagePath` contains the simulator identifier and the app name.  For example it would be at a path on the Mac like:
```
/Users/m/Library/Developer/CoreSimulator/Devices/<simulator-ID>/data/Containers/Bundle/Application/B2CF604D-1B5A-4ED5-91E4-360D40F8E1FB/Runner.app/Runner
```

**Comment by Pisey-Nguon** [comment]
I don't know what the actual error but if I run with the simulator iOS 16 and also a real device iOS 12 it works fine

**Comment by jmagman** [comment]
That it works on iOS 16 and a physical device makes sense.
> this is a bug in the simulator when calling `simctl spawn` on an x64 simulator (like iOS 13.7) on an ARM Mac.

**Comment by Amani-AS** [comment]
I face same issue did you solve it

**Comment by misaelriojasftf** [comment]
is this still happening? I cannot launch any 16 OS simulations... app launches but connection breaks

**Comment by misaelriojasftf** [comment]
### A workaround found 

after having the issue for error connection. app did launch but connection stopped.

<img width="565" alt="image" src="https://user-images.githubusercontent.com/48217522/216819356-c67232e8-c2ea-421d-8307-b8b6a157e3e1.png">

while doing **`flutter attach`** you will receive a list of devices. 
<img width="560" alt="image" src="https://user-images.githubusercontent.com/48217522/216819302-607833d5-3c78-45f5-a96c-5e69f6bb4763.png">

select the one you want to launch 

<img width="558" alt="image" src="https://user-images.githubusercontent.com/48217522/216819413-53249d35-5045-4094-b410-bf5b9db81f5a.png">

**(I was running the Terminal w/ Rosetta)**

**Comment by misaelriojasftf** [comment]
the issue happened after I update my mac & xcode...

I found the real fix here https://github.com/flutter/flutter/issues/111167

<img width="807" alt="image" src="https://user-images.githubusercontent.com/48217522/218194961-3fa748f0-18f2-4996-9776-36d466335fb7.png">

I did the same and now works!! 

<img width="518" alt="image" src="https://user-images.githubusercontent.com/48217522/218195060-263bfc9f-4470-4d8b-a3ce-f10f1fc6e508.png">

**Comment by misaelriojasftf** [comment]
this issue can be closed :wave:
