### ISSUE TITLE
Framework needs to be aware of physical pixels

### ISSUE THREAD

**Issue by knopp** [flutter/flutter#116278]
I'm filing this as separate from https://github.com/flutter/flutter/issues/111302, because I don't believe it is necessarily canvas related. Trying to fix this when painting to canvas is too late.

Framework currently acts as if it is rendering to surface with infinite resolution. However in practice this is not the case and on many (mostly desktop, but also mobile) devices this results in degraded experience. Below are comparison screenshot of simple screen with two rectangles having 1px (logical) border with various DPI scalings.

<details>
<summary>HTML</summary>

```html
<html>
<head></head>
<body style="background-color: black; font-family: sans-serif;">
    <div style="margin-left: 20; margin-top: 20; border: 1px solid yellow; display: inline-flex; width: 64px; height: 44px; box-sizing: border-box; background-color: rgba(255, 166, 0, 0.428); align-items: center; justify-content: center;">
        <div style="display: inline-block; border: 1px solid yellow; padding: 5px; color: white;">
            Hello
        </div>
    </div>
</body>
</html>
```
</details>

<details>
  <summary>Flutter</summary>
  
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(
    DefaultTextStyle(
      style: const TextStyle(
        fontSize: 11,
        color: Colors.white,
        decoration: TextDecoration.none,
        fontWeight: FontWeight.normal,
      ),
      child: Align(
        alignment: Alignment.topLeft,
        child: Padding(
          padding: const EdgeInsets.only(left: 20, top: 20),
          child: SizedBox(
            width: 64,
            height: 44,
            child: Container(
              decoration: BoxDecoration(
                  color: const Color.fromRGBO(255, 166, 0, 0.428),
                  border: Border.all(color: Colors.yellow, width: 1)),
              child: Center(
                child: Container(
                  decoration: BoxDecoration(
                      border: Border.all(color: Colors.yellow, width: 1)),
                  padding: const EdgeInsets.all(5),
                  // This is to make sure text has even height and can be properly shown
                  // at least on 1x scaling
                  child: Padding(
                    padding: const EdgeInsets.only(bottom: 1.0),
                    child: const Text(
                      'Hello',
                      textDirection: TextDirection.ltr,
                    ),
                  ),
                ),
              ),
            ),
          ),
        ),
      ),
    ),
  );
}
  ```
</details>

### 100% scaling

![100](https://user-images.githubusercontent.com/96958/204808311-817cd721-b6e8-4105-9709-b8890f72d774.png)

Here the borders are identical (though did need to massage the Flutter code with additional padding so that text had even height and could be centered vertically without blur; see the very last screenshot).

### 125% scaling

![125](https://user-images.githubusercontent.com/96958/204808921-f607b3d8-ad69-486a-b1c0-ddce15ace2e5.png)

Web image is crisp (border is still 1 physical pixel), Flutter borders are blurred.

### 150% scaling

![150](https://user-images.githubusercontent.com/96958/204809462-64403acd-7351-4259-aa7a-523de6dc2c4e.png)

Web image still has one physical pixel border, Flutter blurry. With 175% scaling, the border is on web still 1 physical pixel, though in some applications (WinUI) this is where 1 logical pixel turns into two physical pixels.

### 200% scaling

![200](https://user-images.githubusercontent.com/96958/204810714-0c336427-e5fa-4a67-a51a-bf9979aa8621.png)

Here Flutter and Web finally look identical.

### Bonus image: Flutter at 100%, without extra 1px padding below the text:

![100-blurry](https://user-images.githubusercontent.com/96958/204811068-4299f0f8-6f33-4908-b2b3-3a1905ce0c32.png)

Ideally, unless there is extra transform in hierarchy (i.e. scale on rotate), all layers that engine receive should be already properly pixel aligned.

**Comment by knopp** [comment]
Here is the example from above written in a way where it renders correctly at any scale (just like the web version). It is possible to do, but it shouldn't be this much work. And if I want to use Row or Column for example, I'd have to write a version of Flex, which is physical pixel aware.

```dart
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';

void main() {
  runApp(
    MaterialApp(
      home: Builder(
        builder: (context) {
          final q = MediaQuery.of(context);
          print('Rebuild at ${q.devicePixelRatio}');
          return DefaultTextStyle(
            style: const TextStyle(
              fontSize: 11,
              color: Colors.white,
              decoration: TextDecoration.none,
              fontWeight: FontWeight.normal,
            ),
            child: Align(
              alignment: const PixelAlignment(-1, -1),
              child: Container(
                margin: const EdgeInsets.only(left: 19, top: 20).pixelSnap(),
                width: 70.pixelSnap(),
                height: 44.pixelSnap(),
                decoration: BoxDecoration(
                    color: const Color.fromRGBO(255, 166, 0, 0.428),
                    border:
                        Border.all(color: Colors.yellow, width: 1).pixelSnap()),
                child: Align(
                  alignment: const PixelAlignment(0, 0),
                  child: Container(
                    decoration: BoxDecoration(
                        border: Border.all(color: Colors.yellow, width: 1)
                            .pixelSnap()),
                    padding: const EdgeInsets.all(5).pixelSnap(),
                    child: const PixelSnapSize(
                      child: Text(
                        'Hello',
                        textDirection: TextDirection.ltr,
                      ),
                    ),
                  ),
                ),
              ),
            ),
          );
        },
      ),
    ),
  );
}

double snapToPhysicalPixel(double value) {
  if (!value.isFinite) {
    return value;
  }
  final double ratio =
      WidgetsBinding.instance.renderView.configuration.devicePixelRatio;
  return (value * ratio - 0.1).round() / ratio;
}

double ceilToPhysicalPixel(double value) {
  if (!value.isFinite) {
    return value;
  }
  final double ratio =
      WidgetsBinding.instance.renderView.configuration.devicePixelRatio;
  return (value * ratio).ceil() / ratio;
}

extension PixelSnapNum on num {
  double pixelSnap() {
    return snapToPhysicalPixel(toDouble());
  }

  double pixelCeil() {
    return ceilToPhysicalPixel(toDouble());
  }
}

extension OffsetPixelSnap on Offset {
  Offset pixelSnap() {
    return Offset(dx.pixelSnap(), dy.pixelSnap());
  }
}

class PixelAlignment extends Alignment {
  const PixelAlignment(super.x, super.y);

  @override
  Offset alongOffset(Offset other) {
    return super.alongOffset(other).pixelSnap();
  }

  @override
  Offset alongSize(Size other) {
    return super.alongSize(other).pixelSnap();
  }

  @override
  Offset withinRect(Rect rect) {
    return super.withinRect(rect).pixelSnap();
  }
}

extension PixelSnapBorderSide on BorderSide {
  BorderSide pixelSnap() {
    return BorderSide(
      color: color,
      width: width.pixelSnap(),
      style: style,
      strokeAlign: strokeAlign,
    );
  }
}

extension PixelSnapBorder on Border {
  Border pixelSnap() {
    return Border(
      top: top.pixelSnap(),
      bottom: bottom.pixelSnap(),
      left: left.pixelSnap(),
      right: right.pixelSnap(),
    );
  }
}

extension PixelSnapEdgeInsets on EdgeInsets {
  EdgeInsets pixelSnap() {
    return EdgeInsets.fromLTRB(
      left.pixelSnap(),
      top.pixelSnap(),
      right.pixelSnap(),
      bottom.pixelSnap(),
    );
  }
}

/// Extens size of underlying widget to match align to pixel boundaries
class PixelSnapSize extends SingleChildRenderObjectWidget {
  const PixelSnapSize({
    super.key,
    required super.child,
  });

  @override
  RenderObject createRenderObject(BuildContext context) {
    return _RenderPixelSnapSize(null);
  }
}

class _RenderPixelSnapSize extends RenderShiftedBox {
  _RenderPixelSnapSize(super.child);

  @override
  double computeMinIntrinsicWidth(double height) {
    return super.computeMinIntrinsicWidth(height).pixelCeil();
  }

  @override
  double computeMaxIntrinsicWidth(double height) {
    return super.computeMaxIntrinsicWidth(height).pixelCeil();
  }

  @override
  double computeMinIntrinsicHeight(double width) {
    return super.computeMinIntrinsicHeight(width).pixelCeil();
  }

  @override
  double computeMaxIntrinsicHeight(double width) {
    return super.computeMaxIntrinsicHeight(width).pixelCeil();
  }

  @override
  Size computeDryLayout(BoxConstraints constraints) {
    if (child == null) {
      return constraints.constrain(Size.zero);
    }
    child!.layout(constraints, parentUsesSize: true);
    return constraints.constrain(
        Size(child!.size.width.pixelCeil(), child!.size.height.pixelCeil()));
  }

  @override
  void performLayout() {
    if (child == null) {
      size = constraints.constrain(Size.zero);
      return;
    }
    child!.layout(constraints, parentUsesSize: true);
    size = constraints.constrain(
        Size(child!.size.width.pixelCeil(), child!.size.height.pixelCeil()));
  }
}

```

**Comment by whiskeyPeak** [comment]
I think I'm be running in a very similar issue as well.

From the picture below, you can see that the right border of the right container is quasi-invisible and that both left and right borders of the left containers are blurry.

![Screenshot from 2022-11-30 18-24-28](https://user-images.githubusercontent.com/73116038/204878856-b0a575f8-4068-4e2b-92ee-3bf2bca4bfff.png)

Here's a picture showing how it ought look:

![Screenshot from 2022-11-30 18-25-35](https://user-images.githubusercontent.com/73116038/204879243-19632afc-c9d9-4ec1-82a8-bf49a7e715a1.png)

In the app, we're using the the width of the window to determine that width of the right container, whilst still having both containers position in the centre of the screen. This causes weird pixel rendering (like above) when resizing the window.

**Comment by jonahwilliams** [comment]
I don't think the framework is the right place to do this. While you can listen to changes to media query, ultimately your parent transforms may change arbitrarily and without rebuilding/repainting children. You'd only get a chance to compute the correct localToGlobal transform once.


I think we'd essentially need to adjust layout at the engine level.

**Comment by knopp** [comment]
How would you do this on engine level? Imagine that you have 100 pixel window where you need to place three children side by side, all of them perfectly pixel aligned. That would mean 33, 33 and 34 pixels for each child. This has to be done during layout. The constraints that each child gets have to reflect that and one of the children will be 1 pixel larger. There is no way to do something like this in the engine in a way where it could affect widget layout (at least unless there is a major change of how engine interacts with framework, which would be quite tricky).

What do you mean by "your parent transforms may change arbitrarily and without rebuilding/repainting children."? Is there any way this could happen without having arbitrary transform in the hierarchy? 

I mean of course arbitrary transform is going to break pixel snapping. But that's kind of to be expected. However vast majority of application that are concerned with this will most likely have only one scale at root level (devicePixelRatio) and everything else would be just translations. As long as those translations are pixel snapped, everything should layout just fine.

**Comment by Hixie** [comment]
I would recommend reframing this in terms of a problem rather than a solution. Progress is much easier to make if we first come to an agreement on what the problem we want to fix is.

**Comment by jonahwilliams** [comment]
@Hixie agreed. I think the general problem we're looking at here is "Flutter looks meh on low density screens (particularly desktop)". My understanding for how this has been solved in the past is that the frameworks have been aware of an aligned to physical pixels. This is different from how mobile devices with high dpr screens moved to a logical pixel mapping to support multiple screen sizes. I'm not aware of anything besides Chrome that handle this cross platform in a reasonable way.

@knopp Translations and Scale transforms are used arbitrarily throughout the framework. OffsetLayers absorb parent translations and give children new coordinates starting at 0.0. Expanded may scale children, same with various aligment widgets.

**Comment by knopp** [comment]
> I would recommend reframing this in terms of a problem rather than a solution. Progress is much easier to make if we first come to an agreement on what the problem we want to fix is.

That makes sense. There are several screenshot above comparing pixel scaling in Flutter vs Web Browser. Does that help demonstrating the issue?

This is how border of same logical width is painted:

Pixel scaling | logical px | physical px Flutter | physical px Web Browser | physical px WinUI | 
---|---|--|--|--|
100 % | 1 px | 1px | 1px | 1px
125 % | 1px | 1.25px | 1px | 1px
150 % | 1px | 1.5px | 1px | 1px
175 % | 1px | 1.75px | 1 px | 2px
200% | 2px | 2px | 2px | 2px

You can see that other than Flutter it is always snapped at physical pixels. It will not get blurry (like Flutter does on screenshot).

**Comment by knopp** [comment]
Translation transform should not be problem (as long as the translation amount is snapped to physical pixels). If you scale widgets at arbitrary scale then any kind of pixel alignment is probably not a concern anymore (and I doubt it would be pixel snapped on Chrome either).

**Comment by jonahwilliams** [comment]
The problem with snapping at layers is that adding/removing/changing compositing leads to jitter

**Comment by knopp** [comment]
If you snap at layout level, that snapping will not change if the transform above changes. It will be slightly off (not lead to pixel perfect rendering anymore if the transform above changes that), but still consistent so it shouldn't leat to jitter. But maybe you mean something else.

**Comment by jonahwilliams** [comment]
I was talking about at the layer level. It may not matter if you snap at the layout level, but I'm unsure. I'll take your word for it

**Comment by Hixie** [comment]
> I think the general problem we're looking at here is "Flutter looks meh on low density screens (particularly desktop)".

I think if that's the issue then we should start from a very specific minimal test case and test environment and work from there.

> There are several screenshot above comparing pixel scaling in Flutter vs Web Browser. Does that help demonstrating the issue?

Well, if the code is asking for 1.5 device pixel borders, the rendering looks correct to me. That's sort of what I mean by needing to agree on the problem. Is the problem "material buttons look fuzzy", or is the problem "when i ask for a 1.5 device pixel border i get a 1.5 pixel border", or is the problem something else?

**Comment by knopp** [comment]
> Well, if the code is asking for 1.5 device pixel borders, the rendering looks correct to me. That's sort of what I mean by needing to agree on the problem. Is the problem "material buttons look fuzzy", or is the problem "when i ask for a 1.5 device pixel border i get a 1.5 pixel border", or is the problem something else?

Where do you see the code asking for 1.5 device pixel borders? In both cases (HTML and Flutter) the code is asking for 1px (logical) border. 

This is screenshot of 1px border @ 1px device pixel ratio:
![100-blurry](https://user-images.githubusercontent.com/96958/204916200-83ab60ee-574a-4152-a4f9-9b727ea8c903.png)

**Comment by Hixie** [comment]
> Where do you see the code asking for 1.5 device pixel borders?

I don't see any code at all, hence my suggesting that we start from a specific code sample showing the problem. :-)

But yes, I consider the 4th and 5th columns in the table you show above to be a bug, and the 3rd column to be the expected result, in the absence of anything else. That doesn't mean I think Flutter UI should be blurry, though. It means that if a UI widget wants a blurry line it should get one. It means that the difference between rotating 0 radians and rotating an infinitesimally small number of radians should be identical (which I bet isn't the case for web, at least, dunno about WinUI).

It's possible to make sure that a border is sharp at every zoom level in Flutter today, by creating a widget that sizes the border based on the device pixel ratio. (That solution also avoids the weirdness during animations.) If our UIs are blurry, then maybe we should be doing that more too. But if that's the issue, we should start with that and some code samples showing the problem, and work from there.

**Comment by knopp** [comment]
The code is in original post, just needed to be expanded :)

<img width="150" alt="Screenshot 2022-11-30 at 23 21 56" src="https://user-images.githubusercontent.com/96958/204920897-bcfb814c-3773-4717-abaf-88ac885cfb70.png">

And indeed, in the post after, I put a code example that scales correctly at every level. Doing just what you suggested. It just seemed that it is maybe something that should work out of the box.

But if you consider the column 4 and 5 a bug and column 3 correct behaviour, then there really much else to discuss. I respectfully disagree, but that's about the extent of it :) This is hardly a hill I'm willing to die on, especially given that there are other ways to implement this.

**Comment by knopp** [comment]
I think this issue can be closed. This is the expected behavior.

**Comment by Hixie** [comment]
Ah, totally missed the "Flutter" bit there, had no idea what it was hiding. :-)

Yeah, that code pretty explicitly says it wants a border that is the width equal to the number of pixels in the devicePixelRatio. That's what we do.

To be clear, I'm not saying we shouldn't change anything here. If UIs are blurry, we should fix that. I'm just saying we should start from an issue that's specifically about the specific UI that's blurry despite not asking for that. (For example, a UI that just has a button in it without giving any dimensions, shouldn't be blurry.)

**Comment by whiskeyPeak** [comment]
Thanks @knopp, I tried out the package and it does fix the issue

Before:

https://user-images.githubusercontent.com/73116038/206269257-b7255c73-3e10-4762-a21a-eb3c918205a6.mp4

After:

https://user-images.githubusercontent.com/73116038/206269306-2e836910-26ed-46ba-a1f5-ef8e07304804.mp4

However, I think that relying on a 3rd-party package to have Flutter correctly render the width of the border is a sub-optimal solution at best. As things are right now, the pixel snapping issue is incredibly noticeable (as you can see from the first video) and applies to any widget basing their position on a given screen ratio. If I tell Flutter to draw a border with a 1px width, it should be able to do so. I checked other GUI frameworks like GTK and didn't run into this issue.

GTK:

https://user-images.githubusercontent.com/73116038/206272581-718f3482-2901-4819-a535-73c1cca77406.mp4

**Comment by knopp** [comment]
I don't think GTK is a great example, since it only supports integral scale factors.

I agree that this should be handled at framework level (hence the issue). WPF on Windows had pixel snapping [10 years ago](https://learn.microsoft.com/en-us/previous-versions/dotnet/netframework-3.5/aa970908(v=vs.90)). But even with that there are still problematic situations. And there are multiple third party WPF components designed to help with pixel snapping....

Given the disagreement of whether be handled by the framework, a package is a pragmatic solution that solves the problem for many situations. But it also possible that it turns out to be too rigid (i.e. maybe there should be a way to disable pixel snapping for parts of hierarchy during animations). At very least it's much easier to iterate, prototype and test new things in external package than the framework itself.
