### ISSUE TITLE
[in_app_purchase][android]: Can't show subscription plans

### ISSUE THREAD

**Issue by erperejildo** [flutter/flutter#116265]
```
in_app_purchase: ^3.0.8

[✓] Flutter (Channel stable, 3.3.8, on macOS 12.5 21G72 darwin-arm, locale en-ES)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.69.2)
[✓] Connected device (4 available)
[✓] HTTP Host Availability

• No issues found!
```

I have one subscription with 2 plans:

<img width="1421" alt="XebvY" src="https://user-images.githubusercontent.com/5629919/204764682-c0146b26-b9d9-4d71-a04f-57f7295ba4ab.png">

The IDs I have created in Flutter are these:

```
    const List<String> _androidProductIds = <String>[
      'plus',
      'pro',
      'basic', // this is the one
    ];
```

I have tried adding `basic-month` and `basic-year` but I only get the first one. How could I choose between plans within the same subscription?

**Comment by erperejildo** [comment]
> @erperejildo please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this. Thank you!

How could I do that? You need to have these subscriptions created on your account in order to see them. Not sure if there is another way to reproduce it. Let me know if not.

In other hand, the approach I follow to show them is the one you have in the example.

To give it more context I had already working other subscriptions and wanted to try the new plans and offers that Google Play provided recently.

**Comment by huycozy** [comment]
Hi @erperejildo 
>I have tried adding basic-month and basic-year but I only get the first one.

I have had similar subscriptions with plans from the account, so no worries about that. I mean the snippet/sample code that lists the subscription plans if any. It seems the [plugin sample code](https://github.com/flutter/plugins/tree/main/packages/in_app_purchase/in_app_purchase/example) only displays list of products (containing subscriptions without plans) as far as I can see.

**Comment by erperejildo** [comment]
> Hi @erperejildo
> 
> > I have tried adding basic-month and basic-year but I only get the first one.
> 
> I have had similar subscriptions with plans from the account, so no worries about that. I mean the snippet/sample code that lists the subscription plans if any. It seems the [plugin sample code](https://github.com/flutter/plugins/tree/main/packages/in_app_purchase/in_app_purchase/example) only displays list of products (containing subscriptions without plans) as far as I can see.

well, that's the thing, what I have now displays the subscriptions, simply. For example, for these 3 subscriptions I have I show them as they are.

For the new one, basic, I have these 2 new plans also but I don't know how to either show these plans or their offers. It shows the basic subscription with basic-month price.

That's the part I'm missing

**Comment by danagbemava-nc** [comment]
Hi @erperejildo, this is currently not supported by the plugin. There is a proposal to track its implementation in https://github.com/flutter/flutter/issues/110909. 

Kindly follow up in the issue linked above for updates. 

Closing from here as duplicate. 

Thank you

**Comment by jatin-web** [comment]
> ```
> in_app_purchase: ^3.0.8
> 
> [✓] Flutter (Channel stable, 3.3.8, on macOS 12.5 21G72 darwin-arm, locale en-ES)
> [✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
> [✓] Xcode - develop for iOS and macOS (Xcode 14.1)
> [✓] Chrome - develop for the web
> [✓] Android Studio (version 2021.2)
> [✓] Android Studio (version 2021.3)
> [✓] VS Code (version 1.69.2)
> [✓] Connected device (4 available)
> [✓] HTTP Host Availability
> 
> • No issues found!
> ```
> 
> I have one subscription with 2 plans:
> 
> <img alt="XebvY" width="1421" src="https://user-images.githubusercontent.com/5629919/204764682-c0146b26-b9d9-4d71-a04f-57f7295ba4ab.png">
> 
> The IDs I have created in Flutter are these:
> 
> ```
>     const List<String> _androidProductIds = <String>[
>       'plus',
>       'pro',
>       'basic', // this is the one
>     ];
> ```
> 
> I have tried adding `basic-month` and `basic-year` but I only get the first one. How could I choose between plans within the same subscription?

Hi @erperejildo, I want to show my subscription plans in the app. If you have figured it out, can you please help me with that?

**Comment by erperejildo** [comment]
> > ```
> > in_app_purchase: ^3.0.8
> > 
> > [✓] Flutter (Channel stable, 3.3.8, on macOS 12.5 21G72 darwin-arm, locale en-ES)
> > [✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
> > [✓] Xcode - develop for iOS and macOS (Xcode 14.1)
> > [✓] Chrome - develop for the web
> > [✓] Android Studio (version 2021.2)
> > [✓] Android Studio (version 2021.3)
> > [✓] VS Code (version 1.69.2)
> > [✓] Connected device (4 available)
> > [✓] HTTP Host Availability
> > 
> > • No issues found!
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I have one subscription with 2 plans:
> > <img alt="XebvY" width="1421" src="https://user-images.githubusercontent.com/5629919/204764682-c0146b26-b9d9-4d71-a04f-57f7295ba4ab.png">
> > The IDs I have created in Flutter are these:
> > ```
> >     const List<String> _androidProductIds = <String>[
> >       'plus',
> >       'pro',
> >       'basic', // this is the one
> >     ];
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I have tried adding `basic-month` and `basic-year` but I only get the first one. How could I choose between plans within the same subscription?
> 
> Hi @erperejildo, I want to show my subscription plans in the app. If you have figured it out, can you please help me with that?

as they mentioned this is not supported so I had to create independent subscriptions
