### ISSUE TITLE
Diff with selector stays in strange highlighted state

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/flutter#116293]
![Screen Shot 2022-11-18 at 10 31 37 AM](https://user-images.githubusercontent.com/43759233/202777567-f84841e9-17a2-4559-ba1e-e53c32f5564d.png)

**Comment by exaby73** [comment]
Hello @kenzieschmoll. Is there a way you can provide a [complete and minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)? I am not sure what is the exact bug here? Else, can you elaborate how you got this issue to reproduce? From the gif, I'm assuming this is the devtools?
