### ISSUE TITLE
Flutter Shortcuts physical key is pressed on a different logical key

### ISSUE THREAD

**Issue by MahmmoudSabri** [flutter/flutter#116277]
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. ... 
3. ... 

**Expected results:** IR remote works smoothly 

**Actual results:** I build flutter app for android TV, but I have issue with the IR remote when I press OK key

<details>
<summary>Code sample</summary>

``` 
 shortcuts: <LogicalKeySet, Intent>{
    LogicalKeySet(LogicalKeyboardKey.select,): const ActivateIntent(),
  },
```

</details>

<details>
  <summary>Logs</summary>

```
======== Exception caught by services library ======================================================
The following assertion was thrown during a platform message callback:
Attempted to send a key down event when no keys are in keysPressed. This state can occur if the key event being sent doesn't properly set its modifier flags. This was the event: RawKeyDownEvent#cf073(logicalKey: LogicalKeyboardKey#70077(keyId: "0x100070077", keyLabel: "", debugName: "Select"), physicalKey: PhysicalKeyboardKey#700e4(usbHidUsage: "0x000700e4", debugName: "Control Right")) and its data: RawKeyEventDataAndroid(keyLabel:  flags: 8, codePoint: 0, keyCode: 23, scanCode: 97, metaState: 0, modifiers down: {})
'package:flutter/src/services/raw_keyboard.dart':
Failed assertion: line 626 pos 12: 'event is! RawKeyDownEvent || _keysPressed.isNotEmpty
```

</details>

**Comment by exaby73** [comment]
Hello @MahmmoudSabri. Thank you for filing this issue. Can you please provide the following information?

- A [complete and minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). Ideally, a single `main.dart` file that can be run directly.
- The output of `flutter doctor -v`
- The output of `flutter run -v`

Please provide the information in the form of text. See how to make collapsible sections with Markdown [here](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-collapsed-sections).
