### ISSUE TITLE
[cocoon] Not reporting "success" after retrying a build.

### ISSUE THREAD

**Issue by ditman** [flutter/flutter#116226]
Cocoon is not reporting success for manually retried LUCI builds, for example in this run:

https://github.com/flutter/plugins/runs/9782441143

I retried manually [here](https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_x64%20ios_platform_tests_4_of_4%20master/14/overview) through the Cocoon "RERUN" button. That set the Github status "in progress" again, but once the build successfully passed, the Github issue never went green again. Instead, it's "updating" every few minutes, but it never goes to green.

Flutter Ecosystem tooling relies on the tree being *all green* for CI automation to keep going. For Flutter Rolls this is not a big issue, because they never trigger a release of any package, but if a feature PR lands and ends up in this state, our `release` procedure must be performed manually (we have no automation override), and it's sub-optimal.

**Can Cocoon report successful *retried* builds to Github as a success? Is this not a Cocoon problem and are we doing something wrong?**

**Comment by drewroengoogle** [comment]
For my understanding, did Cocoon report successful retried builds to Github in the past and is failing to now, or is this a request for an additional feature?

/cc @CaseyHillers potentially, who would know more than me

**Comment by CaseyHillers** [comment]
@ditman can you screenshot what you're clicking? I see "Retry Build" in that link, which does not work. You need to use flutter-dashboard.appspot.com to retry postsubmit builds.

We could add support for the postsubmit GitHub checks rerun functionality as well.

**Comment by ditman** [comment]
> can you screenshot what you're clicking?

I clicked this button:

<img width="651" alt="Screen Shot 2022-11-30 at 2 37 18 PM" src="https://user-images.githubusercontent.com/1255594/204923310-e6527363-c119-4536-951f-cb9ee1de04fc.png">

That updated the github status to "in progress" (as expected), and kicked off the LUCI build, but when the build finished successfully, the success was not reported to the [github run](https://github.com/flutter/plugins/runs/9782441143).

_(If you take a look at [the run](https://github.com/flutter/plugins/runs/9782441143) now, github thinks it started 5 minutes ago (??)_

**Comment by drewroengoogle** [comment]
I talked with Casey a bit and it sounds like this may be a feature that Keyong was working on that is a part of moving the plugin team to LUCI.

@stuartmorgan Do you know if this feature would be a part of that work?

**Comment by ditman** [comment]
@drewroengoogle how is this different from Cocoon reporting build successes when I don't have to restart the build by hand? That bit works fine :/

**Comment by CaseyHillers** [comment]
> @drewroengoogle how is this different from Cocoon reporting build successes when I don't have to restart the build by hand? That bit works fine :/

Up until recently, Cocoon never supported GitHub checks for postsubmit. This sounds like a bug as the feature is still in development.

**Comment by ditman** [comment]
Roger that! Thanks for the details @CaseyHillers!

**Comment by drewroengoogle** [comment]
@CaseyHillers Does it make sense to keep this issue open but move it out of the queue based the info you've provided?

**Comment by stuartmorgan** [comment]
> @stuartmorgan Do you know if this feature would be a part of that work?

I wasn't aware that there was any remaining issue with the post-submit checkin; as far as I knew it was done. The expectation we set was was that post-submit reporting from LUCI was a precondition for migration of any CI to LUCI, so I'm presuming Keyong didn't know that this didn't work either.

> (Asking since it looks like you are taking over that work from Keyong)

The plan was for Keyong to come back to finish the migration; there were a few individual tests I was considering migrating in the meantime, but that's it.

This issue puts us in a bad place: we can't revert the migration because the Cirrus macOS Intel support that we migrated these tasks away from will be eliminated on January 1st, and we can't migrate the tasks to Cirrus ARM because of bugs in the Cirrus ARM hosts that haven't been resolved, but the current situation will cause us a lot of manual pain for the team due to the disruption to autoreleases described above. Is there anyone else with Cocoon expertise who could look into this bug in the meantime?

**Comment by nehalvpatel** [comment]
Taking a look.

**Comment by nehalvpatel** [comment]
I discussed with Godofredo on chat and he suggested a different approach. I'll be working on that. Anywho, I don't want to turn this thread into an implementation discussion so I'll make a new issue. 😄

**Comment by nehalvpatel** [comment]
Awaiting final review on this PR which should fix this: https://github.com/flutter/cocoon/pull/2387

**Comment by nehalvpatel** [comment]
This should be fixed now. https://github.com/flutter/cocoon/pull/2387#issuecomment-1404259901

Please reopen if the issue continues!

**Comment by ricardoamador** [comment]
Nice work @nehalvpatel !

**Comment by ditman** [comment]
Have you ever been excited about a new CI feature? Because I'm excited about a new CI feature! Thanks people!! 🤟

**Comment by nehalvpatel** [comment]
Thank you for the kind words :)
