### ISSUE TITLE
[video_player] IOS Can not play this url

### ISSUE THREAD

**Issue by dianlemel** [flutter/flutter#116246]
Hi guys,
I have a problem with the video player. 
I run the app on the iPhone XS Max iOS 15.5 to reproduce the issue.

Use example code
https://github.com/flutter/plugins/blob/main/packages/video_player/video_player/example/lib/main.dart

play url https://a1.easemob.com/1124220810104702/demo/chatfiles/74ca9170-705f-11ed-a1b0-b52e14e745b7 
This file is mp4

<details>
  <summary>Logs</summary>

```
VideoViewModel:: Video  error: PlatformException(VideoError, Failed to load video: Operation Stopped, null, null)
```

</details>

<details>
  <summary>flutter doctor</summary>

```
[✓] Flutter (Channel stable, 3.3.7, on macOS 12.6 21G115 darwin-arm, locale zh-Hant-TW)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!
```
</details>

**Comment by danagbemava-nc** [comment]
Hi @dianlemel, this is an issue where the underlying AVPlayer itself cannot play the video from the URL so this is not an issue with the plugin. 
I tested a native iOS sample and the issue didn't play there as well. 
I tried to play it in VLC from the URL but it didn't work there as well. 

The video does play when you download and load it as an asset so this is likely an issue with the server that the video is hosted on. 

There is an issue open that is tracking improving the error message in situations like this being tracked in https://github.com/flutter/flutter/issues/56665. 

However, I'll be closing this as this will have to be fixed from the server. 

Thank you
