### ISSUE TITLE
[webview_flutter] Phyiscal keyboard arrow keys don't work on Android.

### ISSUE THREAD

**Issue by Nawbc** [flutter/flutter#116254]
- [x] I have read the [Getting Started](https://inappwebview.dev/docs/intro/) section
- [x] I have already searched for the same problem

## Environment

| Technology      | Version       |
|-----------------| ------------- |
| Flutter version |      3.3.7         |
| Webview version  |      3.0.4        |
| Android version |      12         |
| iOS version     |               |
| macOS version   |               |
| Xcode version   |               |

Device information: 
Samsung Galaxy Tab S8，physical device.

## Description

**Actual results:** 

Phyiscal keyboard arrow keys don't work, after that all the keys doesn't work.
`flutter_inappwebview`, `webview_flutter` have the same issue.

Relate to https://github.com/flutter/flutter/issues/74044  https://github.com/flutter/flutter/issues/102505

<details>
<summary>Codes</summary>

```dart
import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: WebView(
        initialUrl: 'https://vscode.dev/',
      ),
    );
  }
}
```
</details>

<details>
  <summary>Logs</summary>
[√] Flutter (Channel stable, 3.3.7, on Microsoft Windows [Version 10.0.22621.819], locale zh-CN)
    • Flutter version 3.3.7 on channel stable at C:\Users\Nawb\Documents\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e99c9c7cd9 (4 weeks ago), 2022-11-01 16:59:00 -0700
    • Engine revision 857bd6b74c
    • Dart version 2.18.4
    • DevTools version 2.15.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\Nawb\AppData\Local\Android\Sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = C:\Users\Nawb\AppData\Local\Android\Sdk
    • ANDROID_SDK_ROOT = C:\Users\Nawb\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.2.6)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.2.32630.192
    • Windows 10 SDK version 10.0.22000.0

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] VS Code (version 1.73.1)
    • VS Code at C:\Users\Nawb\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.53.20221101

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22621.819]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 107.0.5304.122
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 107.0.1418.62

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

</details>

## Images   
![录制_2022_11_30_14_20_11_889](https://user-images.githubusercontent.com/45007226/204723093-23e13e25-377b-41a0-9f35-c4baa4e93929.gif)

**Comment by huycozy** [comment]
Hi @Nawbc 
To be more precise, please provide the information indicated below:
- A [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
- The output of `flutter doctor -v`
- Reproduction steps, Expected results, Actual results

Thank you!

**Comment by huycozy** [comment]
@Nawbc Did this issue disappear or did you accidentally close it?

**Comment by huycozy** [comment]
@Nawbc This is a known issue being tracked at https://github.com/flutter/flutter/issues/102505. Please follow up on it for further updates.

**Comment by Nawbc** [comment]
> @Nawbc Did this issue disappear or did you accidentally close it?

Yep, i created a new one.
