### ISSUE TITLE
API not supported

### ISSUE THREAD

**Issue by barramon** [flutter/flutter#11625]
## Steps to Reproduce

I am programming the Fist Steps and "Hello World" but when I'm running it, after the message of hot reload you can see a warning of API not supported

![hotreload2](https://user-images.githubusercontent.com/28798426/29323652-2e9be8d6-81a7-11e7-885b-75900cc8c95e.png)

##This is my phone's info

![screenshot_20170814-125027](https://user-images.githubusercontent.com/28798426/29323574-f6474412-81a6-11e7-997c-232a0c9defa7.png)

## Flutter Doctor

![flutterdoctor](https://user-images.githubusercontent.com/28798426/29323495-aecd60f8-81a6-11e7-807a-8bf4a9175c39.png)

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by Hixie** [comment]
This is probably GPU-specific, but I don't know exactly what the issue is. We should get a Moto G3 TE and test it out.

**Comment by zoechi** [comment]
I assume this issue is stale.
Please add a comment if you are still seeing this to have it reopened.
