### ISSUE TITLE
More general approach for theming

### ISSUE THREAD

**Issue by jtdLab** [flutter/flutter#116394]
As far as i am aware theme extensions are only available via `material` library. Im interested in the design choice of this api. It feels not very clean imo. Why is there no extensions property in `CupertinoTheme`? For example to theme a `cupertino` based app which does not use any material widgets its either necessary to use a custom `InheritedWidget` or the `Theme` widget from `material` which has material related properties like different themes of material components? 

Proposal:

Move Theme/ThemeData to the `widgets` library and remove the material depending component themes but still keep the mechanism to register extensions.

Material, Cupertino, Fluent or custom library can register their component themes, colors etc via a theme extension when creating their respective MaterialApp, CupertinoApp, FluentApp, ... instead of giving them a specialized theme (CupertinoTheme, Theme, etc) with hardcoded references to component themes. 

This leads to:

Theme beeing part of widgets library where it semantically belongs.

Material, Cupertino, ... and Custom Themes can be achived via registering their component themes, colors, textstyles etc as an extension

In widget there is only the need to call `Theme.of(context).extension<Foo>()`; (for custom) and for example `Theme.of(context).extension<DividerTheme>()` for (material divider)

**Comment by darshankawar** [comment]
@jtdLab 
Check [this](https://github.com/flutter/flutter/issues/101479) issue and see if it resonates with your proposal.
