### ISSUE TITLE
Http Request

### ISSUE THREAD

**Issue by TitikshaDaga** [flutter/flutter#11636]
So i want to get data in json form from a api on button click. I am ablt to do so but there is only one problem. I am able to do so only by double clicking the button and not on a single click. On one click I get no data but on second click I get the data. Please let me know where I am wrong.

```dart
Map<String, dynamic> data;
  getJson(String username, String password) async {
    var response = await http.post(
      Uri.encodeFull(//url),
      headers: {
//headers
      },
      body: JSON.encode({"username": username, "password": password}),
    );
    if (response.body != 'Incorrect username or password')
      data = JSON.decode(response.body);
    else {
      data = null;
    }
  }

  String username, password;
  @override
  Widget build(BuildContext context) {
 RaisedButton button_signin = new RaisedButton(
        child: new Text("Sign In"),
        onPressed: () {
          print(username + " " + password);
          this.getJson(username, password);
          if (this.data != null) {
            Navigator.popAndPushNamed(context, "/HomePage");
          } else if (this.data == null) {
            showModalBottomSheet(
                context: context,
                builder: (BuildContext context) {
                  return new Container(
                    child: new Text('Invalid username or password.'),
                 height:40.0 );
                },);
          }
        });
```

**Comment by Hixie** [comment]
Change `() {` to `() async {` and change `this.getJson` to `await getJson`.

**Comment by TitikshaDaga** [comment]
@Hixie if I enter wrong username password then no data should come and  it should show me modal sheet saying invalid password or username but that is not happening after the changes u asked me to make. I made the following changes -
1) Made the getJson function return a Future<String> value
2)
 `if (response.body != 'Incorrect username or password')
{ 
    data = JSON.decode(response.body);
return 'Success'
    else {
      data = null;
return 'Fail'    }`
3)
`var result = getJson(username,password);
if (result=='Success') {
            Navigator.popAndPushNamed(context, "/HomePage");
          } else if (result=='Fail') {
            showModalBottomSheet(
                context: context,
                builder: (BuildContext context) {
                  return new Container(
                    child: new Text('Invalid username or password.'),
                 height:40.0 );
                },);
          }`
