### ISSUE TITLE
Google Testing CI check is flaky

### ISSUE THREAD

**Issue by drewroengoogle** [flutter/flutter#116357]
Example: https://github.com/flutter/flutter/pull/116218

This is mainly being tracked internally (b/260764527), but this bug card is meant to give visibility of progress on the issue

**Comment by drewroengoogle** [comment]
@muditatandon Is it okay to assign this to you?

**Comment by christopherfujino** [comment]
Internally tracked b/260764527

**Comment by nehalvpatel** [comment]
Looks like a fix was landed but it is still being reproduced. Continuing to be tracked internally.

**Comment by godofredoc** [comment]
Any updates in this bug?

**Comment by muditatandon** [comment]
Noticed that the entries were present in the database, but not being displayed on the client. Continuing work on this bug.

**Comment by ricardoamador** [comment]
Internal issue has been assigned to @XilaiZhang.

**Comment by XilaiZhang** [comment]
will close this for now since we haven't been seeing recently reported cases.
