### ISSUE TITLE
In Camera Plugin there is no option for setting 1:1 aspect ration even if we set then image stretches. 

### ISSUE THREAD

**Issue by mobileapp-infinity** [flutter/flutter#116319]
In Camera Plugin there is no option for setting 1:1 aspect ration even if we set then image stretches, Is there any way to change camera aspect ration to 1:1 with no streatches please provide way to change aspect ration.

**Comment by iapicca** [comment]
possibly related to 
- https://github.com/flutter/flutter/issues/45665

**Comment by mobileapp-infinity** [comment]
> possibly related to
> 
> * [[camera] Allow custom resolution and aspect ratio #45665](https://github.com/flutter/flutter/issues/45665)

Nooooo , I want to set camera preview to 1:1 aspect ration i tried every thing Transform.Scale, Aspect Ration Widget and many more option but noting work , **_### **Please provide solution to set 1:1 aspect ration without stretching camera preview**_**.

**Comment by iapicca** [comment]
> **_**Please provide solution to set 1:1 aspect ratio without stretching camera preview**_**.

I see only 3 options:
- stretch
- crop
- [custom aspect ratio](https://github.com/flutter/flutter/issues/116319#issuecomment-1333405067)

**Comment by darshankawar** [comment]
@mobileapp-infinity 
Please check [this](https://github.com/flutter/flutter/issues/80393) issue and see if helps in your case. Also check the issues mentioned [here](https://github.com/flutter/flutter/issues/80393#issuecomment-819318650) for your reference and confirm if follow-up in them would help for better tracking.

**Comment by mobileapp-infinity** [comment]
> @mobileapp-infinity Please check [this](https://github.com/flutter/flutter/issues/80393) issue and see if helps in your case. Also check the issues mentioned [here](https://github.com/flutter/flutter/issues/80393#issuecomment-819318650) for your reference and confirm if follow-up in them would help for better tracking.

No that not helped in my case, when can i expect that camera plugin provide aspect ration option like 1:1,4:3 etc.. and this stretch issue solved ?

**Comment by darshankawar** [comment]
The above linked issues are open and have been prioritized. They will be fixed per Flutter team's issue fix policy.
For your issue, can you provide a complete minimal code sample along with platform you are seeing this behavior (android, iOS) with `flutter doctor -v` ?

**Comment by mobileapp-infinity** [comment]
> The above linked issues are open and have been prioritized. They will be fixed per Flutter team's issue fix policy. For your issue, can you provide a complete minimal code sample along with platform you are seeing this behavior (android, iOS) with `flutter doctor -v` ?

Yes sure, I have tried below option on Android Platform please check,

1)

SizedBox(
          height: Get.width,
          width: Get.width,
          child: cameraController!.buildPreview(),
        )

2)

SizedBox(
          height: Get.width,
          width: Get.width,
          child: Transform.scale(
              scaleY: 1.7, //for fixing stretching issue
              child: cameraController!.buildPreview(),
            ),
        )

3)
SizedOverflowBox(
          size: Size(Get.width, Get.width), // aspect is 1:1
          alignment: Alignment.center,
          child: cameraController!.buildPreview(),
        )

4)
SizedBox(
          height: Get.width,
          width: Get.width,
          child: AspectRatio(
            aspectRatio: 1,
            child: cameraController!.buildPreview(),
          ),
)
and many more option but not working,
------------------------------
flutter doctor -v as below

Flutter (Channel stable, 3.3.7, on Microsoft Windows [Version 10.0.18363.1556], locale en-US)
    • Flutter version 3.3.7 on channel stable at D:\flutter_sdk 
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e99c9c7cd9 (4 weeks ago), 2022-11-01 16:59:00 -0700
    • Engine revision 857bd6b74c
    • Dart version 2.18.4
    • DevTools version 2.15.0

Checking Android licenses is taking an unexpectedly long time...[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at D:\android_sdk
    • Platform android-33, build-tools 30.0.3
    • ANDROID_HOME = D:\android_sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default
      components

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] VS Code (version 1.73.1)
    • VS Code at C:\Users\Lenovo\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.52.0

[√] Connected device (4 available)
    • M2101K6P (mobile) •  android-arm64  • Android 12 (API 31)
    • Windows (desktop) • windows  • windows-x64    • Microsoft Windows [Version 10.0.18363.1556]
    • Chrome (web)      • chrome   • web-javascript • Google Chrome 107.0.5304.122
    • Edge (web)        • edge     • web-javascript • Microsoft Edge 107.0.1418.26

[!] HTTP Host Availability
    X HTTP host "https://cocoapods.org/" is not reachable. Reason: Failed to connect to host in 10
      seconds

! Doctor found issues in 2 categories.

**Comment by darshankawar** [comment]
I believe implementing this https://github.com/flutter/flutter/issues/45665 should be able to resolve your case as well, as the original issue talks about the proposal to allow custom resolution and aspect ratio, so I suggest you to follow-up in that issue for further updates.
Closing this in favor of linked issue. If you disagree, write in comments and I'll reopen it.
