### ISSUE TITLE
[gen_l10n] Add an option to use named parameters instead of positional parameters for generated l10n files

### ISSUE THREAD

**Issue by tony-ditchlabs** [flutter/flutter#116308]
Other reports:

- https://github.com/flutter/flutter/issues/131773

---

## Use-case / Problem

Using gen_l10n, a pretty common pattern is to have a translated string with more than one placeholder. For example, an `arb` file may have the following key:

```
  "durationMinMax": "{min} to {max} minute read",
  "@durationMinMax": {
    "placeholders": {
      "max": {
        "type": "int",
        "example": "10"
      },
      "min": {
        "type": "int",
        "example": "1"
      }
    }
  }
```

Note that the order in which the placeholders are used (`min` then `max`) differ from their order in the `placeholders` map (`max` then `min`). This is just a minor optimization of a service like localizely, it alphabetizes the placeholders.

The generated method in app_localizations.dart becomes:
`String durationMinMax(int max, int min);`

It's not intuitive to the coder that the `max` should come before the `min`, so it becomes easy to make human error. Worse, if the placeholders names change in the `arb` file, they may be reordered, and the code would compile correctly, but introduce a new bug. And the problem escalates for Strings with more than two placeholders.

## Proposal

It would be beneficial for there to be a flag in `l10n.yaml` to toggle between two or three modes:

- Use only positional parameters. This would be the default, so as to not introduce any breaking changes for any users.
- Use only named parameters
- (Possibly:) Positional parameters only for translations with one argument; named parameters otherwise

This would give developers more confidence that changes in the `arb` placeholders won't introduce bugs; or if it does introduce bugs, they would be found by the Dart Analyzer, instead of by exhaustive testing or user complaints.

**Comment by philipsoeberg** [comment]
We just fell into this hole.. A dev changed `"{name} at {place}"` to `"{name} at {location}"` believing all was good, but the generator then swapped the positional arguments from `test(Object name, Object place)` to `test(Object location, Object name)` which was not caught by our CI.

Everything should be statically set, or at least have the option to do so.

**Comment by philipsoeberg** [comment]
also, for reference, if tagging placeholders with e.g. p0 p1 p2 .. p10, be aware that p10 sorts between p0 and p1.

e.g. `{p0name} {p1midname} {p2surname} {p10title}` sorts as `Object p0name, Object p10title, Object p1midname, Object p2surname`..

super confusing for ARB maintainers.

**Comment by helpisdev** [comment]
Until this functionality is added, a very nasty not user-friendly way I personally work around it is:

- Add some dummy placeholder values wherever I need named paramaters in the `.arb` files in the following format:
   ```json
  "out_of": "{_p1}{stars} out of {total}{_p2}",
  "@out_of": {
    "placeholders": {
      "_p1": {
        "type": "{dynamic"
      },
      "stars": {
        "type": "num"
      },
      "total": {
        "type": "int?"
      },
      "_p2": {
        "type": "} dynamic"
      }
    }
  },
   ```
- Then generate the translations in a script like this:
   ```bash
  #!/bin/bash

  l10n='lib/l10n'
  flutter gen-l10n
  # Remove placeholder descriptions
  find $l10n -type f -iname "*.dart" -exec sed -i "s|{_p1}||g" {} \;
  find $l10n -type f -iname "*.dart" -exec sed -i "s|{_p2}||g" {} \;
  # Remove invalid args
  find $l10n -type f -iname "*.dart" -exec sed -i "s|dynamic _p1,||g" {} \;
  find $l10n -type f -iname "*.dart" -exec sed -i "s|dynamic _p2||g" {} \;
   ```

Parameters `_p1` and `_p2` are basically added to add the `{}` characters in the right spot in the generated files, and named that way to easily sed them out afterwards. The downside of this except from being ugly, is that 1) if the `flutter gen-l10n` command is run directly then it will generate files with compilation errors, and 2) that if non-developers have to maintain the `.arb` files this could be easily messed up.

If anyone has come up with a better solution, I would love to hear it.
