### ISSUE TITLE
auto-submit bot failed: Resource not accessible by integration

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#116304]
```
Failed to merge pr#: 652 with Pull request could not be merged: Resource not accessible by integration.
```
In buildroot:
https://github.com/flutter/buildroot/pull/652#issuecomment-1332757121

See also https://github.com/flutter/flutter/issues/101008

**Comment by drewroengoogle** [comment]
Pinging @ricardoamador for when he is back from ooo - Would you have any insight on why this is occurring?

**Comment by drewroengoogle** [comment]
This seems to be some sort of permissions issue where the autosubmit bot may be missing access to merge. @godofredoc Does the autosubmit bot have an access token or something similar that may have expired?

**Comment by ricardoamador** [comment]
Have not seen this before. I can take a look.

**Comment by ricardoamador** [comment]
Definitely looks to be a permissions issue according to github. Looks like the token could have been expired when the client was used to make the merge. I am going to make a change to have the code fetch a new client, which will in turn generate a new token so the token will be fresh when the merge is attempted.
