### ISSUE TITLE
path_provider_android 2.0.22 requires gradle lockfiles to be regenerated

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#116376]
Per https://github.com/flutter/flutter/pull/115866. When I tried running `find . -type d -name 'android' | dart dev/tools/bin/generate_gradle_lockfiles.dart` locally I ran into several failures, so I temporarily pinned it to unblock the pub autoroller.

This issue is to track removing the pin, rolling `path_provider_android` forward, and re-generating the gradle lockfiles in a framework commit.

**Comment by christopherfujino** [comment]
This broke tech debt cost because `flutter update-packages --transitive-closure --consumer-only` crashes on that commit with:

```
Error on line 1, column 1 of /tmp/flutter_tools.UQYHCD/flutter_update_packages.CICGIT/flutter_upgrade_sdk/packages/flutter_web_plugins/pubspec.yaml: Missing the required "name" field.
```

**Comment by christopherfujino** [comment]
https://github.com/flutter/flutter/pull/116745 should unblock the roll, I will also land a test that runs on pre-submit to ensure `flutter update-packages --transitive-closure --consumer-only` works.

**Comment by christopherfujino** [comment]
@gmackall do you think we can also unpin `path_provider_android` after https://github.com/flutter/flutter/pull/128898 ?

**Comment by gmackall** [comment]
> @gmackall do you think we can also unpin `path_provider_android` after #128898 ?

Let me take a look to see if the same process will work
