### ISSUE TITLE
assets/dart-ui/blend_mode_darken.png is yellow

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#116393]
https://master-api.flutter.dev/flutter/dart-ui/BlendMode.html has a weird yellow tint on the `darken` image.

Seems to have broken in https://github.com/flutter/assets-for-api-docs/pull/190.

cc @gspencergoog @goderbauer

**Comment by gspencergoog** [comment]
The lighten mode was also yellow for some reason.  Fixed in https://github.com/flutter/assets-for-api-docs/pull/206.
