### ISSUE TITLE
Overlay docs don't say how to add an entry

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#11630]

**Comment by zoechi** [comment]
https://docs.flutter.io/flutter/widgets/Overlay-class.html

> The overlay lets each of these widgets manage their participation in the overlay using OverlayEntry objects.

https://docs.flutter.io/flutter/widgets/OverlayEntry-class.html

> Overlay entries are inserted into an Overlay using the OverlayState.insert or OverlayState.insertAll functions. To find the closest enclosing overlay for a given BuildContext, use the Overlay.of function.

Should there be more?

**Comment by goderbauer** [comment]
Looks like this has been addressed.
