### ISSUE TITLE
video_player codec does not support config priority (err -2147483648)

### ISSUE THREAD

**Issue by yjt1216** [flutter/flutter#116406]
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by yjt1216** [comment]
I/OMXClient(27493): Using client-side OMX mux.
I/MediaCodec(27493): [OMX.qcom.video.decoder.avc] setting surface generation to 28152838
I/ExtendedACodec(27493): setupVideoDecoder()
I/ExtendedACodec(27493): vpp-enable search is 0 and value is 0
I/ExtendedACodec(27493): Decoder will be in frame by frame mode
W/ExtendedACodec(27493): Failed to set frame packing format on component
D/SurfaceUtils(27493): set up nativeWindow 0x559bbf03d0 for 720x480, color 0x7fa30c04, rotation 0, usage 0x2002900
I/OMXClient(27493): Using client-side OMX mux.
I/ACodec  (27493): codec does not support config priority (err -2147483648)
D/AudioManager(27493): updateMediaApp() type=0 id=35836745 package=com.example.flutter_project add=true

**Comment by yjt1216** [comment]
flutter doctor -v info:

`[✓] Flutter (Channel stable, 2.8.1, on macOS 13.0.1 22A400 darwin-x64, locale
    zh-Hans-CN)
    • Flutter version 2.8.1 at /Users/wangyunzhu/flutter281/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (12 months ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/wangyunzhu/Library/Android/sdk
    • Platform android-31, build-tools 30.0.3
    • ANDROID_HOME = /Users/wangyunzhu/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
`

**Comment by exaby73** [comment]
Hello @yjt1216. Thank you for filing this issue. Can you please provide the following information?

- A [complete and minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). Ideally, a single `main.dart` file that can be run directly.
- The output of `flutter run -v`

Please provide the information in the form of text. See how to make collapsible sections with Markdown [here](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-collapsed-sections).

**Comment by yjt1216** [comment]
> Hello @yjt1216. Thank you for filing this issue. Can you please provide the following information?
> 
> * A [complete and minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). Ideally, a single `main.dart` file that can be run directly.
> * The output of `flutter run -v`
> 
> Please provide the information in the form of text. See how to make collapsible sections with Markdown [here](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-collapsed-sections).

OK！

╰─$ flutter doctor -v
[✓] Flutter (Channel stable, 2.8.1, on macOS 13.0.1 22A400 darwin-x64, locale
    zh-Hans-CN)
    • Flutter version 2.8.1 at /Users/wangyunzhu/flutter281/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (12 months ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/wangyunzhu/Library/Android/sdk
    • Platform android-31, build-tools 30.0.3
    • ANDROID_HOME = /Users/wangyunzhu/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.13+0-b1751.21-8125866)

**Comment by yjt1216** [comment]
> Hello @yjt1216. Thank you for filing this issue. Can you please provide the following information?
> 
> * A [complete and minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). Ideally, a single `main.dart` file that can be run directly.
> * The output of `flutter run -v`
> 
> Please provide the information in the form of text. See how to make collapsible sections with Markdown [here](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-collapsed-sections).



> Hello @yjt1216. Thank you for filing this issue. Can you please provide the following information?
> 
> * A [complete and minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). Ideally, a single `main.dart` file that can be run directly.
> * The output of `flutter run -v`
> 
> Please provide the information in the form of text. See how to make collapsible sections with Markdown [here](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-collapsed-sections).


I play videos through video links, and then find that this phenomenon occurs in some links
[      http://101.133.140.217:8689/uploadfile/16698875551051649729438014%E5%BE%B7%E5%93%81%E6%97%A0%E6%B0%B4%E5%8D%B0(%E4%BF%AE%E6%94%B9%E7%89%88)(2).mp4](url)

**Comment by yjt1216** [comment]
![98CA80D3-C085-45B3-8017-653DDD63AC48](https://user-images.githubusercontent.com/12771656/205536043-2ef32a5b-ccc7-453f-9c71-e0190f68ff1c.png)

**Comment by exaby73** [comment]
Hello @yjt1216. If this is a problem with Codec support, unfortunately we cannot do anything about it. `video_player` uses iOS's `AVPlayer` and for Android `ExoPlayer`. These libraries would have to support the codecs, and these are not controlled by the Flutter team. `video_player` is really just a wrapper around these libraries. Therefore, this issue is not a valid one. I suggest raising an issue in the ExoPlayer issues instead. https://github.com/google/ExoPlayer

Closing this issue for those reasons. If you disgree, please comment with your reasoning and I can reopen the issue. Thank you
