### ISSUE TITLE
Add Feature Drag and Drop And Design View

### ISSUE THREAD

**Issue by YahyaAtta** [flutter/flutter#116461]
This is My Suggestion to Flutter Team To adding Drag and Drop And Design View Like in Microsoft Visual Studio in Visual C# or Visual basic
And Please Add Backend

**Comment by satvikpendem** [comment]
These aren't Flutter specific issues. If you want drag and drop in Flutter, try [FlutterFlow](https://flutterflow.io/). It supports a backend too, or you can use your own.

**Comment by darshankawar** [comment]
@YahyaAtta 
Please check above comment and possible solution for your proposal.
Closing this issue.
