### ISSUE TITLE
Document why the build methods of State objects has the context as parameter.

### ISSUE THREAD

**Issue by B3rn475** [flutter/flutter#11649]
A doubt I had as a newcomer is related to the difference between the `contex` parameter of the `build` method of a `State` object and the `context` property.

It is cited in https://docs.flutter.io/flutter/widgets/State/build.html but being the last phrase of a long text it is difficult to identify.

Would it be possible to move the phrase upper or make it more explicit at the beginning of the page.

Would it be possible to also add a small Design Discussion related to this decision?

**Comment by zoechi** [comment]
> https://docs.flutter.io/flutter/widgets/State/build.html

> The given BuildContext contains information about the location in the tree at which this widget is being built. For example, the context provides the set of inherited widgets for this location in the tree. The BuildContext argument is always the same as the context property of this State object and will remain the same for the lifetime of this object. The BuildContext argument is provided redundantly here so that this method matches the signature for a WidgetBuilder.

I think this issue can be closed.
