### ISSUE TITLE
Flutter not working properly on ios release mode

### ISSUE THREAD

**Issue by marendra** [flutter/flutter#116466]
Dear flutter team,

i found this weird problem after ugpraded to flutter 3.3.8 and 3.3.9, before my ios release mode in flutter 3.3.7 was working fine, but after upgraded to 3.3.9, the release mode was not working, but in debug mode it worked

The function that didnt worked:
- image picker hang in gallery
- image picker tried to reach camera, the camera went black
- the websocket connection to amplify appsync did not work (im using amplify for the backend)

below my flutter doctor -v

[✓] Flutter (Channel stable, 3.3.9, on macOS 13.0.1 22A400 darwin-arm, locale en-ID)
    • Flutter version 3.3.9 on channel stable at /Users/marendra/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b8f7f1f986 (11 days ago), 2022-11-23 06:43:51 +0900
    • Engine revision 8f2221fbef
    • Dart version 2.18.5
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/marendra/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.73.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.54.0

[✓] Connected device (3 available)
    • Stella (mobile) • 00008030-0016594021D2402E • ios            • iOS 16.1.1 20B101
    • macOS (desktop) • macos                     • darwin-arm64   • macOS 13.0.1 22A400
      darwin-arm
    • Chrome (web)    • chrome                    • web-javascript • Google Chrome
      108.0.5359.94

[✓] HTTP Host Availability
    • All required HTTP hosts are available

below my dependencies in pubspec.yaml :

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  amplify_flutter: ^0.6.10
  camera: ^0.10.0+4
  amplify_authenticator: ^0.2.4 
  amplify_api: ^0.6.10
  flutter_riverpod: ^2.1.1
  permission_handler: ^10.1.0
  image_picker: ^0.8.6
  google_fonts: ^3.0.1
  flutter_form_builder:
  form_builder_validators:
  geolocator: ^9.0.1
  dio: ^4.0.6
  skeletons: ^0.0.3
  http: ^0.13.5
  font_awesome_flutter: ^10.1.0
  flutter_speed_dial: ^6.0.0
  flutter_dropdown: ^1.0.1+hotfix.1
  lottie: ^2.0.0
  carousel_slider: ^4.1.1
  amplify_auth_cognito: ^0.6.10
  flutter_launcher_icons: ^0.11.0
  uuid: ^3.0.6
  xid: ^1.0.7
  pull_to_refresh: ^2.0.0
  intl: ^0.17.0
  badges: ^2.0.3
  bubble: ^1.2.1
  grouped_list: ^5.1.2
  webview_flutter: ^3.0.4
  smooth_page_indicator: ^1.0.0+2
  firebase_core: ^2.3.0
  upgrader: ^4.8.1
  firebase_messaging: ^14.1.2
  flutter_video_info: ^1.3.1
  visibility_detector: ^0.3.3
  tiktoklikescroller: ^0.2.3
  status_view: ^0.0.2
  cached_video_player: ^2.0.3
  chewie: ^1.3.5
  ffmpeg_kit_flutter: ^5.1.0
  video_player: ^2.4.7
  video_thumbnail: ^0.5.3
  video_trimmer: ^2.0.1
  google_maps_flutter: ^2.2.1

Also bellow is code to open image picker :

InkWell(
                onTap: () async {
                  var statusPhoto = await Permission.photos.status;

                  print(statusPhoto.toString());
                  final image = await _picker.pickImage(
                      source: ImageSource.gallery, maxWidth: 1080);
                  if (image == null) return;

                  setState(() {
                    postImage = image;
                  });
                  Navigator.pop(context);
                },

below is my info.plist

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CADisableMinimumFrameDurationOnPhone</key>
	<true/>
	<key>CFBundleDevelopmentRegion</key>
	<string>$(DEVELOPMENT_LANGUAGE)</string>
	<key>CFBundleDisplayName</key>
	<string>Ecogroovi</string>
	<key>CFBundleExecutable</key>
	<string>$(EXECUTABLE_NAME)</string>
	<key>CFBundleIdentifier</key>
	<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>ecogroovi</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleShortVersionString</key>
	<string>$(FLUTTER_BUILD_NAME)</string>
	<key>CFBundleSignature</key>
	<string>????</string>
	<key>CFBundleVersion</key>
	<string>$(FLUTTER_BUILD_NUMBER)</string>
	<key>LSApplicationCategoryType</key>
	<string></string>
	<key>LSRequiresIPhoneOS</key>
	<true/>
	<key>NSAppleMusicUsageDescription</key>
	<string>this app require access to your Media</string>
	<key>NSCameraUsageDescription</key>
	<string>This app  require access to your camera.</string>
	<key>NSLocationWhenInUseUsageDescription</key>
	<string>This app needs to access Location</string>
	<key>NSMicrophoneUsageDescription</key>
	<string>This app does not require access to the microphone.</string>
	<key>NSPhotoLibraryAddUsageDescription</key>
	<string>This app requires access to the photo library.</string>
	<key>NSPhotoLibraryUsageDescription</key>
	<string>This app requires access to the photo library.</string>
	<key>UIApplicationSupportsIndirectInputEvents</key>
	<true/>
	<key>UIBackgroundModes</key>
	<array>
		<string>fetch</string>
		<string>remote-notification</string>
	</array>
	<key>UILaunchStoryboardName</key>
	<string>LaunchScreen</string>
	<key>UIMainStoryboardFile</key>
	<string>Main</string>
	<key>UISupportedInterfaceOrientations</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
	<key>UISupportedInterfaceOrientations~ipad</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationPortraitUpsideDown</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
	<key>UIViewControllerBasedStatusBarAppearance</key>
	<false/>
	<key>kTCCServiceMediaLibrary</key>
	<string>This app  require access to your Media.</string>
</dict>
</plist>

also attaching my video between debugging in using real phone

link to  video in debug mode app opening gallery and camera

https://video.bunnycdn.com/play/71625/2e2e4840-5412-4750-83b3-5339dc24a455

link to video in release mode app opening gallery

https://video.bunnycdn.com/play/71625/b3e1ee84-a995-4bfc-94ac-9d95c31566f5

link to video in release mode app opening camera

https://video.bunnycdn.com/play/71625/25601c38-9394-4928-96fc-7885163583b5

and also attached my verbose flutter run release mode

[verbose.txt](https://github.com/flutter/flutter/files/10147032/verbose.txt)

**Comment by darshankawar** [comment]
Thanks for the report @marendra 
I tried the `image_picker` plugin example and ran it on iOS device in release mode. I was able to capture picture using camera, gallery without any issues, as shown in below video:


https://user-images.githubusercontent.com/67046386/205649547-0b449bc7-32dc-40f8-9f6b-92b9c0fe0b1f.MP4


I suggest you to try the same plugin example and see if using it, you get same behavior or not.


> * the websocket connection to amplify appsync did not work (im using amplify for the backend)

This is external to plugin and framework, so please try standalone plugin example or provide a code sample without any third party plugin code that shows the reported behavior.

**Comment by marendra** [comment]
hi @darshankawar , current im using image_picker: ^0.8.6, is it the plugin the same version with you ?

**Comment by marendra** [comment]
> 



> Thanks for the report @marendra I tried the `image_picker` plugin example and ran it on iOS device in release mode. I was able to capture picture using camera, gallery without any issues, as shown in below video:
> 
>  RPReplay-Final1670247016.MP4 
> 
> I suggest you to try the same plugin example and see if using it, you get same behavior or not.
> 
> > * the websocket connection to amplify appsync did not work (im using amplify for the backend)
> 
> This is external to plugin and framework, so please try standalone plugin example or provide a code sample without any third party plugin code that shows the reported behavior.

is your pluggin using image_picker: ^0.8.6??

**Comment by marendra** [comment]
hi @darshankawar , okay i tried create new flutter project one with just only image picker, yes it worked, i suspect one of my plugins interfere with image_picker, the last time i  did was to add video features with plugins :
 video_player: ^2.4.7
  video_thumbnail: ^0.5.3
  video_trimmer: ^2.0.1
ffmpeg_kit_flutter: ^5.1.0

How i will know which one the plugin that causing the problem?
is it any easier way to find out? or I have to try one by one the plugin?

**Comment by darshankawar** [comment]
> is your pluggin using image_picker: ^0.8.6??

Yes.



> How i will know which one the plugin that causing the problem?
> is it any easier way to find out? or I have to try one by one the plugin?

`video_player` is also Flutter's first party plugin, so you can skip that, but you'll probably need to check with other 3 plugins one by one and see which one is causing the behavior.

Since using the `image_picker` and `video_player` plugin, the issue doesn't occur, I'll close for now. If you find out the external plugin conflict, you'll probably need to reach out to dedicated plugin's owner / repo for further resolution.
If you disagree, write in comments and I'll reopen it.
