### ISSUE TITLE
No permissions found in manifest for: []9

### ISSUE THREAD

**Issue by Palaceapp** [flutter/flutter#116403]
Not being able to pick image from gallery...Works well with camera and other permission

Have also given permission
 <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />

**Comment by danagbemava-nc** [comment]
Hi @Palaceapp, please provide a complete minimal reproducible code sample that we can run without making any major changes along with the output of `flutter doctor -v`. 

Please also provide the content of your `android/app/src/main/AndroidManifest.xml`.

Thank you
