### ISSUE TITLE
Update Friendlychat codelab with currentUser API for firebase_auth 0.2.0

### ISSUE THREAD

**Issue by collinjackson** [flutter/flutter#11644]
The Firebase auth API for `currentUser()` has a breaking change in flutter/plugins#180 (plugin version `0.2.0`). I think we should update the codelab because otherwise it will be confusing that the API docs don't match the codelab.

/cc @LarkAscending @mit-mit

**Comment by LarkAscending** [comment]
@filiph

**Comment by collinjackson** [comment]
I've updated the steps repo and the codelab doc, just need @LarkAscending to hit publish

**Comment by LarkAscending** [comment]
Bumped version of firebase_auth to 0.2.0 in pubspec.yaml (in Step 5) and clicked publish. Will do a full run-through to verify in the next few days.
