### ISSUE TITLE
In Android 12+, the REST API calls are very slow in flutter, In WiFi that takes 10 seconds whereas in mobile data it is less than a second

### ISSUE THREAD

**Issue by SijuKJ** [flutter/flutter#116477]
## Flutter HTTP bug

**Target Platform:** Mobile - Android
**Target OS version/browser:** Android 12 and above
**Devices:** All Android devices with Wifi Network

I am facing an issue with Flutter Android 12+ version. App-consuming REST API calls using the Flutter http plugin (Version: 0.13.5). All API calls are HTTPS service calls with the domain name. API calls take 10+ seconds for providing the response whereas the same API calls took **only less than a second in mobile data network**. The same API calls I tried using Java Client and Postman, all responses took only less than a second to get a response.  

During the troubleshooting, I tested the following scenarios using Wifi Network
1. Instead of domain I executed the API service call using the IP address, which took only less than a second  (SSL verification disabled in HTTP plugin)
2. Tested API call using connection keep-alive: true, then the first call took 10+s after that subsequent calls took only less than a second 
3. One interesting fact is that I experienced this issue only in Android 12+, the Android 11 device worked on a WiFi network, and it took less than a second for a service call.

Now I understood Wifi based API calls always take 10 Seconds + actual service call time (eg 400 ms hence it would be like 10.400 seconds). 

Is there any specific reason for this issue? 

## Logs

<details>
<summary>Logs</summary>

```
flutter doctor -v
[√] Flutter (Channel stable, 3.3.6, on Microsoft Windows [Version 10.0.22000.1219], locale en-US)
    • Flutter version 3.3.6 on channel stable at C:\Applns\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6928314d50 (6 weeks ago), 2022-10-25 16:34:41 -0400
    • Engine revision 3ad69d7be3
    • Dart version 2.18.2
    • DevTools version 2.15.0

[!] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at C:\Users\Siju\AppData\Local\Android\sdk
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.4.1)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.4.33110.190
    • Windows 10 SDK version 10.0.22000.0

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] Connected device (4 available)
    • 2201116SI (mobile) • b75ac32a6d34 • android-arm64  • Android 12 (API 31)
    • Windows (desktop)  • windows      • windows-x64    • Microsoft Windows [Version 10.0.22000.1219]
    • Chrome (web)       • chrome       • web-javascript • Google Chrome 107.0.5304.123
    • Edge (web)         • edge         • web-javascript • Microsoft Edge 107.0.1418.62

[√] HTTP Host Availability
    • All required HTTP hosts are available
```

</details>

**Comment by darshankawar** [comment]
@SijuKJ 
The difference could be most probably due to ipv4 and ipv6 requests.
See https://github.com/flutter/flutter/issues/112285#issuecomment-1257759717 comment for your reference and make sure your app is using the suitable internet protocol version which should resolve the issue.

With that being said, I am going ahead and closing it. If you disagree, write in comments and I'll reopen it.

**Comment by SijuKJ** [comment]
@darshankawar,  

Thank you so much for the reply.
I am using HTTPS protocol for communication. Usually, all frameworks (like Java HTTP clients) have the capability of specifying the IPv4 or IPv6 during DNS resolution. However, flutter has no such options. I changed the DNS server address in the wifi setting of the device to Google's default DNS server (8.8.8.8 and 8.8.4.4), then the app worked as expected. But this cannot be practical for the end users.

In Native Android and iOS, we haven't faced this issue yet.  **So what is the recommended approach/suitable protocol for resolving IPv4  and IPv6 resolution in Flutter?**  or Do I need to replace the DNS server as such? 

Flutter is the promising technology of the era. Please don't ignore such issues in the Flutter framework.

**Comment by darshankawar** [comment]
Thanks for the feedback @SijuKJ 
Please check below SO links and see if they are helpful in your case:

https://stackoverflow.com/questions/74416607/flutter-app-can-server-have-ipv4-address-and-client-ipv6-address

https://stackoverflow.com/questions/74486912/flutter-how-can-i-use-both-ipv4-and-ipv6-addresses-with-my-client

If not, feel free to raise a feature request using the template so that we can address it as applicable, although I am not sure if that will fall under Flutter or dart repo.

**Comment by SijuKJ** [comment]
@darshankawar , Thank you 👍
Sure, I will request this feature.
