### ISSUE TITLE
[camera] Android 13 CameraException

### ISSUE THREAD

**Issue by cnkygmr** [flutter/flutter#116462]
Android 13 also gives this error, This error only occurs on android 13

`Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: CameraException(error, Attempt to invoke virtual method 'int android.media.EncoderProfiles$VideoProfile.getWidth()' on a null object reference). Error thrown null.`

**Comment by danagbemava-nc** [comment]
Hi @cnkygmr, this issue is known and is being tracked in https://github.com/flutter/flutter/issues/109769.

Kindly follow up in the issue linked above for updates. 

Closing from here as duplicate. 

Thank you
