### ISSUE TITLE
[Camera] Avoid microphone permissions request

### ISSUE THREAD

**Issue by charlieforward9** [flutter/flutter#116444]
## Use case

My iOS application depends on the camera plugin, specifically video, but it does not require audio. I attempted using `CameraController(..., enableAudio = false)` to avoid having to request microphone permissions, but I learned from #106557 that `enableAudio` has no effect on mic permissions, as the hardware is accessed with the `availableCameras()` method.

I have not found a workaround here, and the Apple App Review Team has rejected my submission due to this:
<img width="991" alt="Screen Shot 2022-12-02 at 6 28 32 PM" src="https://user-images.githubusercontent.com/62311337/205406850-52a5c046-76c5-4035-bb20-09211b3797e7.png">

## Proposal

Mimic the behavior of the `enableAudio` parameter from `CameraController` in the `availableCameras()` method... in other words: 

### Proposal:  `availableCameras({enableAudio=true})` 

This would not break existing implementations, as the default is set to true, but with the ability to set it to false, video could be recorded without requesting microphone permissions. 

## Urgency

I did not foresee this obstacle, and I have 4 days to get the application on the App Store. What previously was plenty of time to prepare the presentation, has now turned into a rush to submit the product in time... please help!

If someone has a workaround, that would be a blessing! I unfortunately do not have Swift experience (yet) to fork the plugin and solve the problem myself.

**Comment by stuartmorgan** [comment]
> but I learned from #106557 that `enableAudio` has no effect on mic permissions, as the hardware is accessed with the `availableCameras()` method.

You're referencing App Store review, but the issue you've linked to is about the web implementation of `camera`, not the iOS implementation. What is the exact plugin call in your application that is triggering an audio permission request? Please provide a reproducible test case.

**Comment by charlieforward9** [comment]
@stuartmorgan thanks for getting back to me. As mentioned by @exaby73 [here](https://github.com/flutter/flutter/issues/106557#issuecomment-1167079661)...
> To me, this does not seem like a bug, but rather missing functionality.

 it seems to be a platform-independent lack of plugin functionality. Regardless, here is my minimally reproducible code sample on iOS:
``` dart

import 'package:camera/camera.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter_bloc/flutter_bloc.dart';

void main() {
  runApp(const Root());
}

class Root extends StatelessWidget {
  const Root({Key? key}) : super(key: key);
  @override
  Widget build(BuildContext context) {
    return BlocBuilder<CameraCubit, CameraState>(
        bloc: CameraCubit()..initCamera(),
        builder: (context, state) {
          return CupertinoApp(
              home: CupertinoPageScaffold(
                  child: state is CameraStandby
                      ? CameraPreview(state.controller)
                      : const Center(child: CupertinoActivityIndicator())));
        });
  }
}

class CameraCubit extends Cubit<CameraState> {
  CameraCubit() : super(CameraLoading());

  void initCamera() async {
    final cameras = await availableCameras(); //Likely implement [enableAudio = false] here
    final cameraController = CameraController(
        cameras.firstWhere(
            (camera) => camera.lensDirection == CameraLensDirection.back),
        ResolutionPreset.high,
        enableAudio: false, // Assumed this was supposed to avoid microphone permissions, was wrong
        imageFormatGroup: ImageFormatGroup.bgra8888);
    await cameraController.initialize();
    await cameraController.prepareForVideoRecording();
    emit(CameraStandby(controller: cameraController));
  }
}

@immutable
abstract class CameraState {}

class CameraLoading extends CameraState {}

class CameraStandby extends CameraState {
  final CameraController controller;
  CameraStandby({required this.controller});
}
```

**Comment by exaby73** [comment]
@charlieforward9 I think with iOS, this is different. When selecting a camera, the iOS plugin will request permissions, that too, microphone permissions will only be asked if `enableAudio` is set to `true`. See the code snippet from the plugin below:

https://github.com/flutter/plugins/blob/2a330bc0afd58900cbbc08471b9ea914914a3daa/packages/camera/camera_avfoundation/ios/Classes/CameraPlugin.m

**Comment by charlieforward9** [comment]
I have just verified that the permissions are requested in the `CameraController(...)` constructor call rather than the `availableCameras()` method call. 

However, I have continued receiving microphone permissions requests with `enableAudio = false`.

**Comment by exaby73** [comment]
Using the camera example, microphone permissions only appear to be requested with `enableAudio = true`. Could you provide a complete sample, preferably without any 3rd party libraries?

**Comment by charlieforward9** [comment]
`await cameraController.prepareForVideoRecording();`...
 
The only method I use that the camera example does not. 

Per the method docs:
> Preparing audio can cause a minor delay in the CameraPreview view on iOS. If video recording is intended, calling this early eliminates this delay that would otherwise be experienced when video recording is started...

Removing this method from my code solves the microphone permissions issue. However, despite not using audio, I still experience a small delay. This significantly affects the usability of my application, which depends on the duration of the video, to the nearest millisecond.

Therefore, the intent of this issue remains the same, but the explanation and proposal have changed: **`prepareForVideoRecording()` should not request microphone permissions if `enableAudio = false` in the parent CameraController.**

Is editing the original (slightly misleading) proposal preferred? Or would opening a fresh issue help prioritize and clarify this issue?

**Comment by exaby73** [comment]
I think we can close this issue as invalid. A new, fresh issue with a  [complete and minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) would be great :)

**Comment by charlieforward9** [comment]
@exaby73  One final question to help me ask better questions. I see you referenced the SO link to proper examples. Is the 3rd-party package what is preventing my example from being non-minimal? I would have to completely restructure my code to make it function the same without the 3rd-party package. This is the reason I chose to leave it in. Are you implying that I should have taken the time to do that?

I appreciate feedback, and thank you for helping on this issue.
