### ISSUE TITLE
MacOS font rending issue on 2015 macbooks

### ISSUE THREAD

**Issue by NickoftheSouth** [flutter/flutter#116402]
## Steps to Reproduce

Run a Flutter build on a 2015 macbook running 10.12.6.

**Expected results:** Fonts and text to be displayed normally
**Actual results:** Some custom fonts are displayed as incorrect symbols on some mac devices

<details>

We have a released app that has some font rending issues on some mac devices, so far we have had this issue reported on two macs from 2015 both running macOS Sierra 10.12.6. The app has custom fonts that are used for titles and buttons, but on some devices, the buttons are displaying with random, wrong characters.

![Screenshot from user 1](https://user-images.githubusercontent.com/4994175/205211465-fa20472f-1779-4a87-bbbb-fd3d78d9eb97.png)

![Screenshot from user 2](https://user-images.githubusercontent.com/4994175/205211165-281b42b5-a358-4f2d-87c5-7ed240a52377.png)

This issue doesn't seem to be affecting users on newer macs, and this issue has not been seen on Android, iOS, or Windows versions of the app.

The custom font is working in some instances/typefaces, and failing in others.

In this case, the font is Google's Roboto; https://fonts.google.com/specimen/Roboto

Please take a look at the attached screenshots to see an example.

I don't have direct access to any of these devices so I'm not able to run debug code, analyze, or get logs directly.

The app is available for download here; https://apps.apple.com/nz/app/safety-workkits/id1458064145

I've asked the customers to follow this guide on clearing the font cache;
https://osxdaily.com/2015/01/08/clear-font-caches-databases-mac-os-x/

but that did not solve the issue.

</details>

**Comment by darshankawar** [comment]
@NickoftheSouth 
This looks same as https://github.com/flutter/flutter/issues/57805 for which the fix is as mentioned [here](https://github.com/flutter/flutter/issues/57805#issuecomment-1185785614).
See the merged PR for your reference: https://github.com/flutter/flutter/pull/107689

Closing this as a duplicate and already fixed.
