### ISSUE TITLE
[flutter_web_plugins] HashUrlStrategy drops/overwrites query parameters

### ISSUE THREAD

**Issue by Bungeefan** [flutter/flutter#116415]
This code ignores the `pathname` and query parameters (`search`), if there is an internalUrl.

Before initial routing:
`http://localhost:45389/?example=true`
After routing:
`http://localhost:45389/#/menu`
After routing (with fix):
`http://localhost:45389/?example=true#/menu`

https://github.com/flutter/flutter/blob/ce9423028132f398f683964b9e999ec3c75ce6d3/packages/flutter_web_plugins/lib/src/navigation/url_strategy.dart#L103-L105

In our use case, it would be important to keep these parameters in the URL, even when routing in Flutter.
And as with other technologies (e.g. React Router), the parameters remain unchanged, and the hash routing is appended.

Example fix:
```dart
return "${_platformLocation.pathname}${_platformLocation.search}${internalUrl.isEmpty ? '' : '#$internalUrl'}";
```

Workaround:
Extend HashUrlStrategy with the fix and set it via `setUrlStrategy` from `flutter_web_plugins`.

**Comment by darshankawar** [comment]
Thanks for the report @Bungeefan 
Can you provide a complete minimal code sample that shows the current behavior along with `flutter doctor -v` ?

**Comment by darshankawar** [comment]
Thanks for the details. Using the code sample provided, seeing the same behavior as reported.

<details>
<summary> stable, master flutter doctor -v </summary>

```
[✓] Flutter (Channel stable, 3.3.9, on macOS 12.2.1 21D62 darwin-x64, locale
    en-GB)
    • Flutter version 3.3.9 on channel stable at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b8f7f1f986 (12 days ago), 2022-11-23 06:43:51 +0900
    • Engine revision 8f2221fbef
    • Dart version 2.18.5
    • DevTools version 2.15.0

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

[!] Flutter (Channel master, 3.7.0-1.0.pre.11, on macOS 12.2.1 21D62 darwin-x64,
    locale en-GB)
    • Flutter version 3.7.0-1.0.pre.11 on channel master at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ce94230281 (2 hours ago), 2022-12-01 19:13:07 -0800
    • Engine revision 025aefc7af
    • Dart version 2.19.0 (build 2.19.0-444.0.dev)
    • DevTools version 2.20.0
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.


[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.



```

</details>

**Comment by mdebbar** [comment]
Interesting. Is there a specific browser that this happens on?

In Chrome, if I do `history.pushState(null, null, '#foo')` it doesn't override `pathname` and `search` in the url. It just appends the hash part.

**Comment by Bungeefan** [comment]
No, as this package overwrites it specifically (by not specifying it in the update URL).
I tested it with Chrome and Firefox.

Or do you mean something else?

**Comment by mdebbar** [comment]
> No, as this package overwrites it specifically (by not specifying it in the update URL).

If you don't include query params when you update the URL, then the expected behavior is that the query params will disappear. Url strategy is a low-level class that only cares about one "path". It doesn't parse query params and it doesn't do anything special with query params.

You basically have 2 options:

1. When you update the url, make sure to include all the bits that you care about (including query params).
2. Use a high-level routing solution, e.g. [`GoRouter`](https://pub.dev/documentation/go_router/latest/topics/Get%20started-topic.html).

**Comment by Bungeefan** [comment]
@mdebbar I think there is a misunderstanding.
I don't update the URL manually, this happens through Flutter on the initial load!

Also, I understand that you want to keep it low-level, but in this case there would be no query parsing or special handling, just don't skip the already existing parameters as this is already the case when the `internalUrl` is empty
Additionally, this only applies to the HashUrlStragety as the PathUrlStrategy doesn't have the same flaw, even without special query handling. 

I am only asking to not drop a substantial part of the existing URL when routing via Hashtag!

Sidenote:
The Query Parameters, that I am talking about, are **before** the Hashtag in the URL specification, not behind, they shouldn't be affected by the fragment (the hashtag) at all.

**Comment by Bungeefan** [comment]
I think I know what went wrong.

When I mentioned "update URL", I was not talking about any route request from my side or the router, I was talking about the URL being crafted in HashUrlStrategy, as seen in the code snippet above.
The snippet fails to "specify it in the update URL"!

**Comment by Bungeefan** [comment]
@darshankawar This is not solved!
I am asking to re-open this issue as I think there was a misunderstanding with @mdebbar, this is still an issue!

**Comment by darshankawar** [comment]
Reopening based on above comment.

**Comment by zbarbuto** [comment]
BTW I found this to be a better workaround for the `prepareExternalUrl` override:

```dart
    return "${_platformLocation.pathname}${internalUrl.isEmpty ? '' : '#$internalUrl'}${_platformLocation.search}";
```

The one in the original issue would end up redirecting `example.com?foo=bar` to something like `example.com/?foo=bar#/` instead of `example.com/#/?foo=bar` which is needed to consume the query parameters in a route.

**Comment by Bungeefan** [comment]
@zbarbuto
No, I don't think that that would solve the issue, as this would move the original search part of the normal URL **behind** the Hashtag, which makes it a whole different thing and would probably cause problems.

The goal was to **keep** the original "browser" search parameters where they were and not drop them.
You would still be able to use something like `example.com/?browser_foo=bar#/home?flutter_foo=bar`.

This should be a fully usable and correct URL without impacting any existing and future Flutter routing.
It just allows the usage of plain "old" search parameters, as used in times before there were even any JavaScript.

**Comment by zbarbuto** [comment]
You're right. 

I think it might be a misunderstanding on my part (or even an issue with the routing package I'm using). When redirected to e.g. `example.com/?code=1234#/home` the route was not able to get access to the query parameter (it was null) but if it was at `example.com/#/home?code=1234` it was fine.

However if it's behind the hash as in your setup I can at least still get to it via `window.location.search`.

**Comment by Bungeefan** [comment]
Yeah, because the first query parameters are not the same as the one behind the hashtag, in fact, you can put anything behind the hashtag and parse it as you like, it just makes sense to use the same format again, therefore many JavaScript frameworks (including Flutter) use it that way.

By the way, if you want to retrieve the first query parameters without importing `dart:html` you can use `Uri.base.queryParameters` instead.
This works on all platforms without a conditional import!
