### ISSUE TITLE
[go_router] Feature request - Allow back button in AppBar to navigate like back button of Browser

### ISSUE THREAD

**Issue by hrishikesh-kadam** [flutter/flutter#116440]
## Use case

https://github.com/hrishikesh-kadam/back_button_app_bar_history
Consider the above repo as a use case.

| Branch | Firebase Hosting URL |
| --- | --- |
| `main` | https://back-button-app-bar-history--main-stable-o1xetkk1.web.app |
| `platform-specific-app-bar` | https://back-button-app-bar-history--platform-specific-app-bar-q90mmwvv.web.app |

[`compare main...platform-specific-app-bar`](https://github.com/hrishikesh-kadam/back_button_app_bar_history/compare/main...platform-specific-app-bar)

Navigate as follows on both the branch's hosting URLs -  
1. Click the URL (or `flutter run -d chrome` from the respective branch)
2. Click /page-2
3. Click /page-3
4. Click the leading back button on AppBar of Page 3.
5. Click the leading back button on AppBar of Page 2.
6. Click /page-2
7. Click /page-3
8. Click the leading back button on AppBar of Page 3.
9. Click the leading back button on AppBar of Page 2.

Observed browser's back stack
- For the `main` branch
   - /page-2
   - /page-2/page-3
   - /page-2
   - /
   - /page-2
   - /page-2/page-3
   - /page-2
   - /

- For the `platform-specific-app-bar` branch
   - Nothing 

## Proposal

Can the Flutter team provide a feature in the [go_router](https://pub.dev/packages/go_router) package,
which allows a `GoRoute` to navigate back like the browser back button for web apps instead of just popping a page.

This can annoy Android mobile users if they install a web app as PWA and navigate as mentioned above.
Some Android mobile users have the habit of pressing the System's back button till the app exits.
Here they would have to press the System's back button **9 times** to exit in the `main` branch case,  
as compared to **only once** in the `platform-specific-app-bar` branch case.

I do understand that the `main` branch case is working as expected from the History API perspective.
To achieve the expected results, I had to [Conditionally Import the Platform-specific AppBar](https://github.com/hrishikesh-kadam/back_button_app_bar_history/blob/f19dbfc99e23dc84d8fdde356dc58dda02dd9c94/lib/config/configure_web.dart).

As there is no Browser History API involvement in the other Platforms they work as intended.
That is, running both the branches' code on the Android emulator and navigating as mentioned above,  
the user would have to click System's back button **only once** to exit.

I have played with `setUrlStrategy(null)` which disables the History API,  
but I do not wish to lose the current Page's URL location indication.

We also have to take note of deep link cases.
`main` branch case - [/page-2/page-3](https://back-button-app-bar-history--main-stable-o1xetkk1.web.app/page-2/page-3)
`platform-specific-app-bar` branch case - [/page-2/page-3](https://back-button-app-bar-history--platform-specific-app-bar-q90mmwvv.web.app/page-2/page-3)
If a user opens a deep link like the above then the `main` branch case will work as intended but  
the `platform-specific-app-bar` branch case will not.
One way to make the `platform-specific-app-bar` branch case work would be to  
pre-populate `['/', '/page-2']` Pages in the Browser History by consulting `GoRouter`.

<details>
<summary>

## `flutter doctor -v`
</summary>

```
[✓] Flutter (Channel stable, 3.3.9, on Ubuntu 22.10 5.19.0-23-generic, locale en_IN)
    • Flutter version 3.3.9 on channel stable at /home/hrk/main-data/softwares/flutter/stable
    • Upstream repository https://github.com/flutter/flutter
    • Framework revision b8f7f1f986 (10 days ago), 2022-11-23 06:43:51 +0900
    • Engine revision 8f2221fbef
    • Dart version 2.18.5
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /mnt/common-data/softwares/android/sdk/linux
    • Platform android-33, build-tools 33.0.1
    • ANDROID_SDK_ROOT = /mnt/common-data/softwares/android/sdk/linux
    • Java binary at: /snap/android-studio/125/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 15.0.2-1
    • cmake version 3.24.2
    • ninja version 1.11.0
    • pkg-config version 0.29.2

[✓] Android Studio (version 2021.3)
    • Android Studio at /snap/android-studio/125/android-studio
    • Flutter plugin version 70.2.3
    • Dart plugin version 213.7433
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Community Edition (version 2022.3)
    • IntelliJ at /snap/intellij-idea-community/402
    • Flutter plugin version 71.0.6
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.73.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.52.0

[✓] VS Code (version 1.74.0-insider)
    • VS Code at /usr/share/code-insiders
    • Flutter extension version 3.54.0

[✓] Connected device (3 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 13 (API 33)
      (emulator)
    • Linux (desktop)              • linux         • linux-x64      • Ubuntu 22.10
      5.19.0-23-generic
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome
      107.0.5304.121

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by maRci002** [comment]
https://github.com/flutter/flutter/issues/70588#issuecomment-730684576
> This is by design. Any route changes in your flutter app will cause a history push in the browser. This is how gmail and many other web apps behave, so we designed it around that model.

https://github.com/flutter/flutter/issues/70588#issuecomment-730703636

> Imagine this case. you go from page A to page B, the browser also remember pageA -> pageB
> What should we expect the browser history be like after a programmatically pop?
> 
> if you think browser should go back to pageA, then it is a actually browser back, and can be achieved with plugin that calls history.go(-1).
> 
> If you think browser should remember this and create this history pageA -> pageB -> pageA, then this is what programmatically pop currently does.

You can always create your own `BackButton`:
```dart
import 'dart:html' hide VoidCallback;

class MyBackButton extends StatelessWidget {
  const MyBackButton({
    super.key,
    this.color,
    this.onPressed,
  });

  final Color? color;

  final VoidCallback? onPressed;

  @override
  Widget build(BuildContext context) {
    final navigator = Navigator.of(context);

    if (!navigator.canPop()) {
      return const SizedBox.shrink();
    }

    assert(debugCheckHasMaterialLocalizations(context));

    return IconButton(
      icon: const BackButtonIcon(),
      color: color,
      tooltip: MaterialLocalizations.of(context).backButtonTooltip,
      onPressed: () {
        if (onPressed != null) {
          onPressed!();
        } else {
          if (kIsWeb) {
            window.history.back();
          } else {
            navigator.maybePop();
          }
        }
      },
    );
  }
}
```

Then use it everywhere:
```dart
SliverAppBar(
  leading: const MyBackButton(),
  ...
);
```

**Comment by darshankawar** [comment]
Thanks for the report @hrishikesh-kadam 
Please check above comment / solution and see if it serves purpose in your case.

**Comment by coastalgit** [comment]
FYI - I achieved via a similar approach but by using Router.neglect:

```
AppBar(
        leading: GestureDetector(
          child: const Icon(Icons.close_rounded, color: Colors.white),
          onTap: () => Router.neglect(context, () => context.pop()),
        ),
      ),
```
