### ISSUE TITLE
ChangeNotifierProvider -> Consuming the Provider in a new route

### ISSUE THREAD

**Issue by nagringapp** [flutter/flutter#116482]
## Steps to Reproduce

// Create the Provider
class MyProvider extends ChangeNotifier {

}

// Initiate the provider in a screen
class MyMainPage extends StatefulWidget {
  const MyMainPage({super.key});

  @override
  State<MyMainPage> createState() => _MyMainPageState();
}

class _MyMainPageState extends State<MyMainPage> {
  @override
  Widget build(BuildContext context) {
    return ChangeNotifierProvider(
      create: (_) => MyProvider(),
      builder: (ctx, _) {
          Navigator.push(ctx, MaterialPageRoute(builder: (_) => MyPage())
      }
    );
  }
}

// Consume the Provider in the new Page
class MyPage extends StatefulWidget {
  const MyPage({super.key});

  @override
  State<MyPage> createState() => _MyPageState();
}

class _MyPageState extends State<MyPage> {
  @override
  Widget build(BuildContext context) {

    final provider = Provider.of<MyProvider>(context, listen: false);
    // !!!! ERROR !!!!

    return Container();
  }
}

**Expected results:** 
- On the MainPage I created the ChangeNotifierProvider to initiate the Provider itself
- I used the context returned from the builder to push to a new Route.
- On the new route I tried to create the provider based on the context and got an error.

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>
═══════ Exception caught by widgets library ═══════════════════════════════════
Error: Could not find the correct Provider<MyProvider> above this Consumer<MyProvider> Widget

This happens because you used a `BuildContext` that does not include the provider
of your choice. There are a few common scenarios:

- You added a new provider in your `main.dart` and performed a hot-reload.
  To fix, perform a hot-restart.

- The provider you are trying to read is in a different route.

  Providers are "scoped". So if you insert of provider inside a route, then
  other routes will not be able to access that provider.

- You used a `BuildContext` that is an ancestor of the provider you are trying to read.

  Make sure that Consumer<MyProvider> is under your MultiProvider/Provider<MyProvider>.
  This usually happens when you are creating a provider and trying to read it immediately.

  For example, instead of:

  ```
  Widget build(BuildContext context) {
    return Provider<Example>(
      create: (_) => Example(),
      // Will throw a ProviderNotFoundError, because `context` is associated
      // to the widget that is the parent of `Provider<Example>`
      child: Text(context.watch<Example>().toString()),
    );
  }
  ```

  consider using `builder` like so:

  ```
  Widget build(BuildContext context) {
    return Provider<Example>(
      create: (_) => Example(),
      // we use `builder` to obtain a new `BuildContext` that has access to the provider
      builder: (context, child) {
        // No longer throws
        return Text(context.watch<Example>().toString());
      }
    );
  }
  ```

If none of these solutions work, consider asking for help on StackOverflow:
https://stackoverflow.com/questions/tagged/flutter
```
```

```
```

```
```

</details>

**Comment by iapicca** [comment]
@nagringapp 
afaik `ChangeNotifierProvider ` is part of [provider](https://pub.dev/packages/provider) package, not of `flutter`
maybe the issue should be opened [here](https://github.com/rrousselGit/provider/issues)

**Comment by darshankawar** [comment]
As suggested above, please open issue in dedicated repo.
Closing from here.
