### ISSUE TITLE
[web] Flutter Demo served from IoT Device only shows blank page in Firefox

### ISSUE THREAD

**Issue by higaski** [flutter/flutter#116480]
I've recently played around serving the default demo application (push button thingy) from an IoT device. The application is built using the HTML renderer and has about ~3MB. Depending on the quality of the wireless connection and how much memory the IoT device is able to allocate for it's HTTP server the (initial) load times of the page can vary between 3 to 10s.

For some reason though, when load times exceed a certain amount of time, the app stops showing in Firefox and only continues to work in Chromium. Here are two screenshots with load times on the upper end of the spectrum:

Firefox, not working, blank page
![Screenshot_Mozilla Firefox_1](https://user-images.githubusercontent.com/13762516/205481670-93be59dc-8a43-47c1-9657-608463b90ea7.png)

Chromium, working, although load times are equally high
![Screenshot_Flutter Demo - Chromium_1](https://user-images.githubusercontent.com/13762516/205481674-7f879c8e-09a0-43ad-8fb9-39cdcc66b9aa.png)

Any ideas on why this is happening? The Firefox debug output shows that all necessary files have been loaded correctly so why does the page stay blank?

/edit
```sh
❯ flutter --version
Flutter 3.3.9 • channel stable • https://github.com/flutter/flutter.git
Framework • revision b8f7f1f986 (11 days ago) • 2022-11-23 06:43:51 +0900
Engine • revision 8f2221fbef
Tools • Dart 2.18.5 • DevTools 2.15.0
```

**Comment by exaby73** [comment]
Hello @higaski. Can this be reproduced by simulating slow connections through the devtools? Also, are there any logs printed in the console?

**Comment by higaski** [comment]
> Hello @higaski. Can this be reproduced by simulating slow connections through the devtools?

I've just tried various settings (2G, 3G...) but no, I can't say I can reliably reproduce the issue. I've also just seen the page load successfully after 37s... Still it keeps failing quite often on Firefox and subjectively it gets worse if the load times get longer.


> Also, are there any logs printed in the console?

Yes there are, can't believe I haven't thought about adding them.

Firefox
```
InstallTrigger is deprecated and will be removed in the future. constants.js:50:14
HTTPS-Only Mode: Not upgrading insecure request “http://wulf.local/flutter.js” because it is exempt. flutter.js
The script from “http://wulf.local/flutter.js” was loaded even though its MIME type (“text/html”) is not a valid JavaScript MIME type. index.html
Service worker not supported (or configured). 
Object { serviceWorkerVersion: "2306561284" }
flutter.js:107:17
Injecting <script> tag. flutter.js:68:17
HTTPS-Only Mode: Not upgrading insecure request “http://wulf.local/icons/Icon-192.png” because it is exempt. Icon-192.png
HTTPS-Only Mode: Not upgrading insecure request “http://wulf.local/favicon.png” because it is exempt. favicon.png
HTTPS-Only Mode: Not upgrading insecure request “http://wulf.local/main.dart.js” because it is exempt. main.dart.js
The script from “http://wulf.local/main.dart.js” was loaded even though its MIME type (“text/html”) is not a valid JavaScript MIME type. index.html
Flutter Web Bootstrap: Programmatic main.dart.js:14818:78
HTTPS-Only Mode: Not upgrading insecure request “http://wulf.local/assets/FontManifest.json” because it is exempt. FontManifest.json
HTTPS-Only Mode: Not upgrading insecure request “http://wulf.local/assets/fonts/MaterialIcons-Regular.otf” because it is exempt. MaterialIcons-Regular.otf
```

Chromium
```
flutter.js:107 Service worker not supported (or configured). {serviceWorkerVersion: '2306561284'}
_loadWithServiceWorker @ flutter.js:107
loadEntrypoint @ flutter.js:48
(anonymous) @ index.html:46
load (async)
(anonymous) @ index.html:44
main.dart.js:14818 Flutter Web Bootstrap: Programmatic
```

**Comment by higaski** [comment]
> Hello @higaski. Can this be reproduced by simulating slow connections through the devtools?

I've just tried various settings (2G, 3G...) but no, I can't say I can reliably reproduce the issue. I've also just seen the page load successfully after 37s... Still it keeps failing quite often on Firefox and subjectively it gets worse if the load times get longer.


> Also, are there any logs printed in the console?

Yes there are, can't believe I haven't thought about adding them.

Firefox
```
InstallTrigger is deprecated and will be removed in the future. constants.js:50:14
HTTPS-Only Mode: Not upgrading insecure request “http://wulf.local/flutter.js” because it is exempt. flutter.js
The script from “http://wulf.local/flutter.js” was loaded even though its MIME type (“text/html”) is not a valid JavaScript MIME type. index.html
Service worker not supported (or configured). 
Object { serviceWorkerVersion: "2306561284" }
flutter.js:107:17
Injecting <script> tag. flutter.js:68:17
HTTPS-Only Mode: Not upgrading insecure request “http://wulf.local/icons/Icon-192.png” because it is exempt. Icon-192.png
HTTPS-Only Mode: Not upgrading insecure request “http://wulf.local/favicon.png” because it is exempt. favicon.png
HTTPS-Only Mode: Not upgrading insecure request “http://wulf.local/main.dart.js” because it is exempt. main.dart.js
The script from “http://wulf.local/main.dart.js” was loaded even though its MIME type (“text/html”) is not a valid JavaScript MIME type. index.html
Flutter Web Bootstrap: Programmatic main.dart.js:14818:78
HTTPS-Only Mode: Not upgrading insecure request “http://wulf.local/assets/FontManifest.json” because it is exempt. FontManifest.json
HTTPS-Only Mode: Not upgrading insecure request “http://wulf.local/assets/fonts/MaterialIcons-Regular.otf” because it is exempt. MaterialIcons-Regular.otf
```

Chromium
```
flutter.js:107 Service worker not supported (or configured). {serviceWorkerVersion: '2306561284'}
_loadWithServiceWorker @ flutter.js:107
loadEntrypoint @ flutter.js:48
(anonymous) @ index.html:46
load (async)
(anonymous) @ index.html:44
main.dart.js:14818 Flutter Web Bootstrap: Programmatic
```

**Comment by exaby73** [comment]
It could be possible that this is being caused due to HTTP. Could you try accessing the website by IP or using a self-signed cert and HTTPS?

**Comment by higaski** [comment]
Accessing the device by IP results in the same issue, although Firefox no longer logs `HTTPS-Only Mode` messages. Switching the device to HTTPS might take me a little while, I haven't used it before.

**Comment by exaby73** [comment]
Service workers need HTTPS enabled to work on non-localhost, yes. Since I can't reproduce this, can you confirm one more thing? If the app is run on your computer, does it load on firefox?

**Comment by higaski** [comment]
Yes, running it locally works like a charm.

**Comment by exaby73** [comment]
Final thing: Could you provide information on the devices you have reproduced this on, with the steps you took to set up the web server as well?

**Comment by exaby73** [comment]
Unfortunately not :D But it's still useful information for the team to try and investigate. I'll label this issue for now, and allow the team to look at it and investigate further. If you can share any other details about the issue, please do as it can help track down a bug or solve you issue altogether

**Comment by yjbanov** [comment]
Most new Web specifications as of several years ago require [SecureContext](https://webidl.spec.whatwg.org/#SecureContext). HTTPS will effectively become a hard requirement on the web at the time goes on. If we try to support non-secure contexts our available browser API surface will dwindle, hurting app capabilities. For example, you'd think WebCodecs has nothing to do with network, but the spec still [requires](https://www.w3.org/TR/webcodecs/#imagedecoder-interface) secure context.

If you are simply debugging an app served from the IoT device, consider using an SSH tunnel so you can access it via `localhost` (which counts as a [trustworthy origin](https://w3c.github.io/webappsec-secure-contexts/#is-origin-trustworthy)). Or perhaps there's a way to configure the browser to accept the IoT device origin as trustworthy ([the spec mentions this](https://w3c.github.io/webappsec-secure-contexts/#development-environments)).

**Comment by higaski** [comment]
I probably shouldn't have used the word IoT. The device would only be reachable locally where I would consider HTTP a valid alternative. Apart from that I have tried using a self signed certificate and that didn't work either...
