### ISSUE TITLE
[path_provider] update the "path_provider_android" dependency to "2.0.22"

### ISSUE THREAD

**Issue by Nidal-Bakir** [flutter/flutter#116596]
The currently used version of `path_provider_android` is `^2.0.6`
but is not compatible with flutter 3.3.x >= 3.3.8` 

## Steps to Reproduce

1. create a new flutter project
2. add **path_provider** to **pubspec.yaml** file 
3. Execute `flutter clean` 
4. Execute `flutter build apk --split-per-abi`

#### My build.gradle

<details>
<summary>build.gradle</summary>

```
buildscript {
    ext.kotlin_version = '1.6.10'
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:7.1.2'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

</details>
<details>
<summary>app/build.gradle</summary>

```
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

android {
    compileSdkVersion 33

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.doors.app"
        minSdkVersion 21
        targetSdkVersion 33
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8:$kotlin_version"
}

```

</details>

**Expected results:**  
  The app builds and outputs the APKs without any errors. 

**Actual results:** 

> w: Runtime JAR files in the classpath should have the same version. These files were found in the classpath:
>     /home/nidal/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk8/1.6.10/e80fe6ac3c3573a80305f5ec43f86b829e8ab53d/kotlin-stdlib-jdk8-1.6.10.jar (version 1.6)
>     /home/nidal/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk7/1.6.10/e1c380673654a089c4f0c9f83d0ddfdc1efdb498/kotlin-stdlib-jdk7-1.6.10.jar (version 1.6)
>     /home/nidal/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.7.10/d2abf9e77736acc4450dc4a3f707fa2c10f5099d/kotlin-stdlib-1.7.10.jar (version 1.7)
>     /home/nidal/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-common/1.7.10/bac80c520d0a9e3f3673bc2658c6ed02ef45a76a/kotlin-stdlib-common-1.7.10.jar (version 1.7)
> w: Some runtime JAR files in the classpath have an incompatible version. Consider removing them from the classpath
> e: /home/nidal/.gradle/caches/modules-2/files-2.1/androidx.annotation/annotation/1.5.0/857678d6b4ca7b28571ef7935c668bdb57e15027/annotation-1.5.0.jar!/META-INF/annotation.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.7.1, expected version is 1.5.1.
> e: /home/nidal/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.7.10/d2abf9e77736acc4450dc4a3f707fa2c10f5099d/kotlin-stdlib-1.7.10.jar!/META-INF/kotlin-stdlib.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.7.1, expected version is 1.5.1.
> e: /home/nidal/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-common/1.7.10/bac80c520d0a9e3f3673bc2658c6ed02ef45a76a/kotlin-stdlib-common-1.7.10.jar!/META-INF/kotlin-stdlib-common.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.7.1, expected version is 1.5.1.
> w: Runtime JAR files in the classpath should have the same version. These files were found in the classpath:
>     /home/nidal/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk8/1.6.10/e80fe6ac3c3573a80305f5ec43f86b829e8ab53d/kotlin-stdlib-jdk8-1.6.10.jar (version 1.6)
>     /home/nidal/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk7/1.6.10/e1c380673654a089c4f0c9f83d0ddfdc1efdb498/kotlin-stdlib-jdk7-1.6.10.jar (version 1.6)
>     /home/nidal/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.7.10/d2abf9e77736acc4450dc4a3f707fa2c10f5099d/kotlin-stdlib-1.7.10.jar (version 1.7)
>     /home/nidal/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-common/1.7.10/bac80c520d0a9e3f3673bc2658c6ed02ef45a76a/kotlin-stdlib-common-1.7.10.jar (version 1.7)
> w: Some runtime JAR files in the classpath have an incompatible version. Consider removing them from the classpath
> Running Gradle task 'assembleRelease'...                          272.1s
> ✓  Built build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk (13.6MB).

**Comment by stuartmorgan** [comment]
> The currently used version of `path_provider_android` is `^2.0.6`

`^` indicates a range including everything before the next breaking change, so includes 2.0.22. We do not generally artificially update our minimum dependency versions; app developers should be running `flutter pub upgrade` routinely to update all of their dependencies.

> * create a new flutter project
> * add **path_provider** to **pubspec.yaml** file

These steps currently result in a project that use `path_provider_android` 2.0.22, because that's the newest version compatible with the constraints.

Closing as there is no action needed here. Clients can already get 2.0.22 just by upgrading their dependencies (for existing projects; new projects will get it by default).

**Comment by Nidal-Bakir** [comment]
@stuartmorgan 

But the error is still present! 
Even after creating a new project and running `flutter pub upgrade`.
The error still appears.

<details>
<summary>The output of flutter pub upgrade</summary>

> Resolving dependencies...
>   async 2.9.0 (2.10.0 available)
>   boolean_selector 2.1.0 (2.1.1 available)
>   characters 1.2.1
>   clock 1.1.1
>   collection 1.16.0 (1.17.0 available)
>   cupertino_icons 1.0.5
>   fake_async 1.3.1
>   ffi 2.0.1
>   file 6.1.4
>   flutter 0.0.0 from sdk flutter
>   flutter_lints 2.0.1
>   flutter_test 0.0.0 from sdk flutter
>   lints 2.0.1
>   matcher 0.12.12 (0.12.13 available)
>   material_color_utilities 0.1.5 (0.2.0 available)
>   meta 1.8.0
>   path 1.8.2 (1.8.3 available)
>   path_provider 2.0.11
>   path_provider_android 2.0.22
>   path_provider_ios 2.0.11
>   path_provider_linux 2.1.7
>   path_provider_macos 2.0.6
>   path_provider_platform_interface 2.0.5
>   path_provider_windows 2.1.3
>   platform 3.1.0
>   plugin_platform_interface 2.1.3
>   process 4.2.4
>   sky_engine 0.0.99 from sdk flutter
>   source_span 1.9.0 (1.9.1 available)
>   stack_trace 1.10.0 (1.11.0 available)
>   stream_channel 2.1.0 (2.1.1 available)
>   string_scanner 1.1.1 (1.2.0 available)
>   term_glyph 1.2.1
>   test_api 0.4.12 (0.4.16 available)
>   vector_math 2.1.2 (2.1.4 available)
>   win32 3.1.2
>   xdg_directories 0.2.0+2
> No dependencies changed.
> 12 packages have newer versions incompatible with dependency constraints.
> Try `flutter pub outdated` for more information.

</details>

### The classpath error 

 ```
Running "flutter pub get" in hello_proj...                         894ms

💪 Building with sound null safety 💪

w: Runtime JAR files in the classpath should have the same version. These files were found in the classpath:
    /home/nidal/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk8/1.6.10/e80fe6ac3c3573a80305f5ec43f86b829e8ab53d/kotlin-stdlib-jdk8-1.6.10.jar (version 1.6)
    /home/nidal/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk7/1.6.10/e1c380673654a089c4f0c9f83d0ddfdc1efdb498/kotlin-stdlib-jdk7-1.6.10.jar (version 1.6)
    /home/nidal/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.7.10/d2abf9e77736acc4450dc4a3f707fa2c10f5099d/kotlin-stdlib-1.7.10.jar (version 1.7)
    /home/nidal/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-common/1.7.10/bac80c520d0a9e3f3673bc2658c6ed02ef45a76a/kotlin-stdlib-common-1.7.10.jar (version 1.7)
w: Some runtime JAR files in the classpath have an incompatible version. Consider removing them from the classpath
e: /home/nidal/.gradle/caches/modules-2/files-2.1/androidx.annotation/annotation/1.5.0/857678d6b4ca7b28571ef7935c668bdb57e15027/annotation-1.5.0.jar!/META-INF/annotation.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.7.1, expected version is 1.5.1.
e: /home/nidal/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.7.10/d2abf9e77736acc4450dc4a3f707fa2c10f5099d/kotlin-stdlib-1.7.10.jar!/META-INF/kotlin-stdlib.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.7.1, expected version is 1.5.1.
e: /home/nidal/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-common/1.7.10/bac80c520d0a9e3f3673bc2658c6ed02ef45a76a/kotlin-stdlib-common-1.7.10.jar!/META-INF/kotlin-stdlib-common.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.7.1, expected version is 1.5.1.
w: Runtime JAR files in the classpath should have the same version. These files were found in the classpath:
    /home/nidal/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk8/1.6.10/e80fe6ac3c3573a80305f5ec43f86b829e8ab53d/kotlin-stdlib-jdk8-1.6.10.jar (version 1.6)
    /home/nidal/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk7/1.6.10/e1c380673654a089c4f0c9f83d0ddfdc1efdb498/kotlin-stdlib-jdk7-1.6.10.jar (version 1.6)
    /home/nidal/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.7.10/d2abf9e77736acc4450dc4a3f707fa2c10f5099d/kotlin-stdlib-1.7.10.jar (version 1.7)
    /home/nidal/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-common/1.7.10/bac80c520d0a9e3f3673bc2658c6ed02ef45a76a/kotlin-stdlib-common-1.7.10.jar (version 1.7)
w: Some runtime JAR files in the classpath have an incompatible version. Consider removing them from the classpath
Running Gradle task 'assembleRelease'...                           88.8s
✓  Built build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk (5.5MB).
```

**Comment by Nidal-Bakir** [comment]
Alright, I will.
