### ISSUE TITLE
`MaterialStateColor.resolveWith` cannot return `null` value.

### ISSUE THREAD

**Issue by TahaTesser** [flutter/flutter#116590]
I've come across this in previous PRs and in a recent [PR](https://github.com/flutter/flutter/pull/116194). 

Take this as an example where `Color? get selectedColor` is nullable but `MaterialStateColor.resolveWith` doesn't allow returning a null value.

In a case where we need to return a `null` so an "effectiveColor" variable can fall back to a different color for the default property.

```dart
  @override
  Color? get selectedColor => MaterialStateColor.resolveWith((Set<MaterialState> states) {
    if (states.contains(MaterialState.selected)) {
      return _themeData.colorScheme.primary;
    }
    
    // cannot return a null.
    return null;
  });
```

I would have to provide a condition to avoid getting `Colors.transparent`, like this.
```dart
  @override
  Color? get selectedColor =>  _themeData.colorScheme.primary;
   /// ....
    final Color? effectiveSelectedColor = MaterialStateProperty.resolveAs<Color?>(selectedColor, states)
      ?? MaterialStateProperty.resolveAs<Color?>(tileTheme.selectedColor, states)
      ?? MaterialStateProperty.resolveAs<Color?>(theme.listTileTheme.selectedColor, states)
      ?? (states.contains(MaterialState.selected) ? defaults.selectedColor : null);
```

I've noticed this pattern throughout the framework where `MaterialStateColor.resolveWith` often resorts to `Colors.transparent`. I would like to make sure this doesn't go unnoticed if it is by design and if there is a way to return `null`.

Here are some instances:

https://github.com/flutter/flutter/blob/921f0776874b4a66551fc4ab545f3eb9c393642c/packages/flutter/lib/src/material/menu_anchor.dart#L3712-L3719

https://github.com/flutter/flutter/blob/921f0776874b4a66551fc4ab545f3eb9c393642c/packages/flutter/lib/src/material/checkbox.dart#L844-L856

https://github.com/flutter/flutter/blob/921f0776874b4a66551fc4ab545f3eb9c393642c/packages/flutter/lib/src/material/slider.dart#L1938-L1950

**Comment by TahaTesser** [comment]
cc: @HansMuller

**Comment by HansMuller** [comment]
I think you mean that [MaterialStateColor.resolve](https://api.flutter.dev/flutter/material/MaterialStateColor/resolve.html) can't return null.

**Comment by darrenaustin** [comment]
Yeah the main use of transparent was to indicate that you didn't want a color for something that had a default. Trying to use null for that case doesn't work, as it is used to indicate that you want the default, not that you don't want any color. The main example of this is with `shadowColor` and `surfaceTintColor`. 

As for the issue at hand here, as Hans pointed out, it wouldn't make sense for `MaterialStateColor.resolve` to be able to return null as its type is `MaterialStateProperty<Color>` not `MaterialStateProperty<Color?>`. I'm going to close this as working as designed.
