### ISSUE TITLE
Engine roll caused regression to aot_snapshot_size

### ISSUE THREAD

**Issue by B3rn475** [flutter/flutter#11650]
The latest engine roll (https://github.com/flutter/flutter/commit/2e57189aa47285b191552efe845446236ade6093) has increased the size of all aot snapshots.

![image](https://user-images.githubusercontent.com/2686902/29391530-c84f661e-82ac-11e7-8264-2ef64028d382.png)
![image](https://user-images.githubusercontent.com/2686902/29391556-f6a02d50-82ac-11e7-8d89-8ccc8147a327.png)

PL https://github.com/flutter/flutter/pull/11643#issuecomment-323146015

**Comment by B3rn475** [comment]
@rmacnak-google

**Comment by rmacnak-google** [comment]
Isn't that outside of the blame window? I read the blame windows as

engine fef7d827d6e22830ee6c88e8260f118a6b3fbcd9..a246501917b8b77e856db253817ce7c2cc25b9c2
dart 15258fd7a76cbf49a1b3eb86d8695602e792abb5..491390eeaa7974f44a8931d10a899c39c0df8dda

**Comment by B3rn475** [comment]
My fault. Removed the reference

**Comment by Hixie** [comment]
Moved to https://github.com/dart-lang/sdk/issues/30472 since it seems likely to be Dart-related.
