### ISSUE TITLE
[iOS][Proposal] Provide a way to inform users about `Paste from other apps` setting

### ISSUE THREAD

**Issue by sudha-anecure** [flutter/flutter#116599]
This is the same as https://github.com/flutter/flutter/issues/112515 - since I am unable to reopen that ticker, I have opened this ticket.

iOS addressed this in iOS 16.1 where they offer a new setting for an app, called "paste from other apps". When a user does paste in the text box, we need a way to show the user a themed dialog offering the option of Always Allow vs Ask Everytime. Can you please give us this hook or capability? Our app is very annoying to use without this.

**Comment by jmagman** [comment]
See also https://github.com/flutter/flutter/issues/103163
cc @justinmc

**Comment by bugrevealingbme** [comment]
++

**Comment by justinmc** [comment]
@sudha-anecure Thanks for bringing up the changes in iOS 16.1.

Let's close this issue in order to focus conversation in https://github.com/flutter/flutter/issues/103163.  I'm digging into this problem and will post my findings over there shortly.
