### ISSUE TITLE
Some Impeller gradients/shadows end in an unexpected place

### ISSUE THREAD

**Issue by omchiii** [flutter/flutter#116584]
## Steps to Reproduce

- Switched to master branch
- Flutter upgrade
- Enable impeller in info.plist
- Run the app in release on mobile (iPhone)

**Expected results:** App running smoother with the same resolution

**Actual results:** App running a lot smoother! but with **lower resolution** or blurry

The whole app just looks different compared to non-impeller. Check screenshot

<details>
  <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 3.7.0-3.0.pre.16, on macOS 12.6 21G115 darwin-arm64, locale en-DE)
    • Flutter version 3.7.0-3.0.pre.16 on channel master at /Users/bayramo/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4ec4401338 (25 hours ago), 2022-12-05 05:29:27 -0500
    • Engine revision 4de358e2f0
    • Dart version 2.19.0 (build 2.19.0-444.0.dev)
    • DevTools version 2.20.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/bayramo/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = /Users/bayramo/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A309
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.73.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.54.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.6 21G115 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 107.0.5304.121

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

| Without enabling impeller - stable branch [3.3.9] | With enabling impeller -  (Channel master, 3.7.0-3.0.pre.16) |
| -- | -- |
| <img src="https://user-images.githubusercontent.com/53796452/205906514-997d2a7d-ff32-4466-b7de-e830b14b1b47.png" /> | <img src="https://user-images.githubusercontent.com/53796452/205906774-a9254500-27fc-4914-9323-8f007de82379.png" /> |

Check out the fonts, icons, and even the shadows in the elevated app bar. It just looks blurrier and chunkier like it's in a lower resolution

It might look like it's a little different but once you see it in hand it looks quite different, feels as if it is a web view. I suggest looking at the screenshots side by side for a better view.

**Comment by jonahwilliams** [comment]
can you attach some sample code that reproduces the issue?

**Comment by omchiii** [comment]
Okay, this one is reproducible with almost no hassle.

1. Switch to master channel
2. Flutter upgrade
3. Flutter (Channel master, 3.7.0-3.0.pre.16, on macOS 12.6 21G115 darwin-arm64, locale en-DE)
4. Create a new Flutter app with the classic template
5. Add  
        <key>FLTEnableImpeller</key>
  	<true/>
To Info.plist
6. Connect the iPhone & run the app on your iPhone using flutter run
![IMG_7247](https://user-images.githubusercontent.com/53796452/206138934-64706528-a234-40f3-92f7-c27fdae08c29.jpeg)

7. Remove         
        <key>FLTEnableImpeller</key>
  	<true/>
From Info.plist.
8. Connect the iPhone & run the app on your iPhone using flutter run
![IMG_7246](https://user-images.githubusercontent.com/53796452/206139175-e191466f-81fe-4316-b0ec-32522254c912.jpeg)

main.dart
`import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      // This call to setState tells the Flutter framework that something has
      // changed in this State, which causes it to rerun the build method below
      // so that the display can reflect the updated values. If we changed
      // _counter without calling setState(), then the build method would not be
      // called again, and so nothing would appear to happen.
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
        elevation: 40,
      ),
      body: Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: Column(
          // Column is also a layout widget. It takes a list of children and
          // arranges them vertically. By default, it sizes itself to fit its
          // children horizontally, and tries to be as tall as its parent.
          //
          // Invoke "debug painting" (press "p" in the console, choose the
          // "Toggle Debug Paint" action from the Flutter Inspector in Android
          // Studio, or the "Toggle Debug Paint" command in Visual Studio Code)
          // to see the wireframe for each widget.
          //
          // Column has various properties to control how it sizes itself and
          // how it positions its children. Here we use mainAxisAlignment to
          // center the children vertically; the main axis here is the vertical
          // axis because Columns are vertical (the cross axis would be
          // horizontal).
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headlineMedium,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
`

I can clearly see the difference in the resolution in the fonts, shadows, and overall feel. You can even zoom in on the "plus" icon for instance and see how the pixels are visible on the impeller version.

**Comment by danagbemava-nc** [comment]
There's a subtle difference in the way impeller renders the view. 

Labeling for further insight from the team. 

<details>
<summary>screenshots</summary>

| Impeller | Without Impeller |
| -- | -- |
|<img src="https://user-images.githubusercontent.com/88313112/206181579-dd4070d4-bb06-4a3e-8a54-e4e210d43301.png" /> | <img src="https://user-images.githubusercontent.com/88313112/206181582-1be11326-46f1-4c08-8307-9ee9ecda4873.png" /> |

</details>

<details>
<summary>sample without comments</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
        elevation: 40,
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headlineMedium,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}
```
</details>

<details>
<summary>flutter doctor -v</summary>

```
[!] Flutter (Channel master, 3.7.0-3.0.pre.57, on macOS 13.0.1 22A400 darwin-arm64, locale en-GB)
    • Flutter version 3.7.0-3.0.pre.57 on channel master at /Users/nexus/dev/sdks/flutters
    ! Warning: `flutter` on your path resolves to /Users/nexus/dev/sdks/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/nexus/dev/sdks/flutters. Consider adding /Users/nexus/dev/sdks/flutters/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/nexus/dev/sdks/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/nexus/dev/sdks/flutters. Consider adding /Users/nexus/dev/sdks/flutters/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ef6ead4401 (8 hours ago), 2022-12-06 23:15:24 -0500
    • Engine revision 67254d6e4b
    • Dart version 2.19.0 (build 2.19.0-467.0.dev)
    • DevTools version 2.20.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.73.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.54.0

[✓] Connected device (4 available)
    • Nexus (mobile)         • 00008020-001875E83A38002E            • ios            • iOS 16.1.2 20B110
    • iPhone 14 Pro (mobile) • 4F72110C-F38B-4CF9-93C4-4D6042148D28 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-1 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 13.0.1 22A400 darwin-arm64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 108.0.5359.94

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```
</details>

**Comment by omchiii** [comment]
@danagbemava-nc  Thank you, but it is a lot more noticeable when there is more content. Not sure if "subtle" should be the term, because it might get less prioritized?

**Comment by jmagman** [comment]
@chinmaygarde @zanderso

**Comment by jonahwilliams** [comment]
Thanks @omchiii . While it is a goal to make impeller have great fidelity, that doesn't necessarily mean we want impeller to look pixel for pixel identical. Also taking an image and zooming in to reveal pixelation is not a bug.

I'll keep this open for now so we can discuss the particular differences

**Comment by rubenferreira97** [comment]
I am also experiencing abrupt shadow transitions/gradients with Impeller. It does not feel smooth at all (it abruptly stops at a specific line). Check the screenshots (zoom it) and compare with the non Impeller version:

![abrupt1](https://user-images.githubusercontent.com/43851289/208119405-73f67bd5-be94-4900-a59e-814246eafb27.png)
![abrupt2](https://user-images.githubusercontent.com/43851289/208119406-e5824756-3b4a-47b4-b691-c958fd75a1d8.png)

**Comment by zanderso** [comment]
@rubenferreira97 Could you share your `flutter doctor` output please?

**Comment by rubenferreira97** [comment]
@zanderso Here is my `flutter doctor`:

<details>
<summary>flutter doctor -v</summary>

```
[√] Flutter (Channel master, 3.7.0-10.0.pre.18, on Microsoft Windows [Version 10.0.22621.963], locale pt-PT)
    • Flutter version 3.7.0-10.0.pre.18 on channel master at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ab47fc304c (27 minutes ago), 2022-12-16 10:50:25 -0500
    • Engine revision 29196519c1
    • Dart version 3.0.0 (build 3.0.0-21.0.dev)
    • DevTools version 2.20.0

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\Eu\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • CHROME_EXECUTABLE = C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe

[√] Visual Studio - develop for Windows (Visual Studio Build Tools 2019 16.11.22)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
    • Visual Studio Build Tools 2019 version 16.11.33130.400
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[√] VS Code, 64-bit edition (version 1.73.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.54.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22621.963]
    • Chrome (web)      • chrome  • web-javascript • unknown
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 108.0.1462.46

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by gaodeng** [comment]
any news?

**Comment by omchiii** [comment]
> any news?

This issue was just labeled/prioritized. It's too soon to ask I'm sure it will get tagged once something is done about it. Impeller is still not in stable.

**Comment by zanderso** [comment]
Text issues are covered by other issues. Let's focus this issue on the issue with the gradient/shadow. cc @jonahwilliams @bdero for investigation.

**Comment by bdero** [comment]
Thanks for trying Impeller and filing this issue! The shadow discontinuities and slight darkness should be addressed once https://github.com/flutter/engine/pull/38417 rolls into the framework.

The text being thicker/more blurry is a known issue and is currently tracked by https://github.com/flutter/flutter/issues/115041.
