### ISSUE TITLE
[CP] Remove ink_sparkle shader compilation from web builds

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#116555]
### issue_link

https://github.com/flutter/flutter/issues/115433

### Commit Hash

27281da

### Target

beta

### pr_link

https://github.com/flutter/flutter/pull/116554

### Impacted Users

web developers on chromeos

### Impact Description

web developers using chrome os will be unable to build applications targeting the web

### Workaround

No

### Risk

low

### Test Coverage

yes

### Validation Steps

Run the unit tests attached to the fix.

**Comment by itsjustkevin** [comment]
@zanderso

**Comment by zanderso** [comment]
cp lgtm.
