### ISSUE TITLE
[go_router] Add ability to pop with result using extension

### ISSUE THREAD

**Issue by TatsuUkraine** [flutter/flutter#116506]
## Use case

In release 5.2.1 `pop` method on `GoRouter` was updated to make possible pop dialogs and modals with GoRouter. Additionally interface was changed to allow passing `result` as an optional param. But the extension still uses the old interface without ability to specify result. (see https://github.com/flutter/packages/pull/2879)

## Proposal

Update [Extension pop method](https://github.com/flutter/packages/blob/main/packages/go_router/lib/src/misc/extensions.dart#L62) to match `GoRouter.pop` interface

**Comment by TatsuUkraine** [comment]
cc @chunhtai

**Comment by exaby73** [comment]
Hello @TatsuUkraine. Thank you for raising this issue. In the future, please refrain from mentioning team members out of the blue. But, I can see from the [documentation](https://pub.dev/documentation/go_router/latest/go_router/GoRouterHelper/pop.html) that the result is missing in the extension. Labeling for further insights from the team

**Comment by TatsuUkraine** [comment]
@exaby73 sorry, I looked at PR author and thought that it maybe was mistakenly missed
