### ISSUE TITLE
[CP] Remove glitches when scrolling on old Android TV devices

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#116531]
### issue_link

https://github.com/flutter/flutter/issues/113314

### Commit Hash

https://github.com/flutter/engine/commit/1603fa1bb41271366dceedaaf0663715576e18f2

### Target

beta

### pr_link

https://github.com/flutter/engine/pull/38074 

### Impacted Users

Users of older Android devices and OSes

### Impact Description

Partial repaint is not completely supported by the APIs on older Android devices and OSes. This changes increases the version requirement for enabling partial repaint.

### Workaround

There is no workaround

### Risk

low

### Test Coverage

yes

### Validation Steps

Visual artifacts on lower-end devices and older OSes are addressed.

**Comment by zanderso** [comment]
@itsjustkevin This one should be backported to 3.3. I'll make another PR.

**Comment by zanderso** [comment]
Here is the CP to 3.3 https://github.com/flutter/engine/pull/38075

**Comment by itsjustkevin** [comment]
Thanks @zanderso

**Comment by itsjustkevin** [comment]
CC @CaseyHillers and @godofredoc for approval.
FYI @muditatandon who will be the release engineer.

**Comment by CaseyHillers** [comment]
CP LGTM

**Comment by zanderso** [comment]
https://github.com/flutter/engine/pull/38075 is ready to land to the 3.3 branch.

**Comment by itsjustkevin** [comment]
Leaving this open as there is still the cherry-pick to merge to stable. 

CC: @CaseyHillers

**Comment by CaseyHillers** [comment]
@itsjustkevin @zanderso if there's a request for also CPing to stable, please open a new CP request

**Comment by itsjustkevin** [comment]
https://github.com/flutter/flutter/issues/116905 is the stable cherry-pick
