### ISSUE TITLE
Flutter Doctor after Upgrade is not up to date

### ISSUE THREAD

**Issue by Solido** [flutter/flutter#11658]
## Steps to Reproduce

`flutter upgrade`

After Flutter upgrade completed it displays Doctor stats but those are the old infos
`• Framework revision b156a0f054 (5 days ago), 2017-08-16 19:31:59 -0700`

Executing again Flutter Doctor display the real update version
`• Framework revision 47fe630e4e (11 hours ago), 2017-08-16 19:31:59 -0700`

OSX

**Comment by Hixie** [comment]
I fixed this recently.
