### ISSUE TITLE
[CP] Safari Clip Fix

### ISSUE THREAD

**Issue by ollydixon** [flutter/flutter#116574]
### issue_link

https://github.com/flutter/flutter/issues/116352

### Commit Hash

6f749e5a7d5fb8bcdc12b47b3423d58b845b79f8

### Target

stable

### pr_link

https://github.com/flutter/engine/pull/38154

### Impacted Users

All developers who use Flutter for Web

### Impact Description

Safari cannot display many widget types because of this bug. It's critical to all web based projects.

Right now Web projects on Flutter are not viable.

### Workaround

Do not use Clip, but that's not possible. Apps need Clip for border radius, ovals and much more.

### Risk

high

### Test Coverage

yes

### Validation Steps

It's fixed in Beta and tested. Just needs to be pushed out to hotfix.

Run this code
Does it play on Safari? Or is it black.

```
import 'package:flutter/material.dart';
import 'package:video_player/video_player.dart';

void main() {
  runApp(
    MaterialApp(
      home: _App(),
    ),
  );
}

class _App extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: _BumbleBeeRemoteVideo(),
    );
  }
}

class _BumbleBeeRemoteVideo extends StatefulWidget {
  @override
  _BumbleBeeRemoteVideoState createState() => _BumbleBeeRemoteVideoState();
}

class _BumbleBeeRemoteVideoState extends State<_BumbleBeeRemoteVideo> {
  late VideoPlayerController _controller;

  @override
  void initState() {
    super.initState();
    _controller = VideoPlayerController.network(
      'https://flutter.github.io/assets-for-api-docs/assets/videos/bee.mp4',
      videoPlayerOptions: VideoPlayerOptions(),
    );

    playThis();
  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return ClipRRect(
      borderRadius: BorderRadius.circular(24),
      child: Container(
        width: 320,
        height: 200,
        color: Colors.green,
        child: VideoPlayer(_controller),
      ),
    );
  }

  Future<void> playThis() async {
    await _controller.setLooping(true);
    await _controller.setVolume(0.0);
    await _controller.initialize();
    _controller.play();
  }
}
```

**Comment by itsjustkevin** [comment]
@yjbanov and @zanderso could you take a look at this cherry-pick?

**Comment by zanderso** [comment]
The linked PR should be an open PR against the release branch. @itsjustkevin I think to cherry-pick to stable, it should be `flutter-3.2-candidate.5`, right?

Not sure whether this should be cp'd though. @yjbanov's call.

**Comment by yjbanov** [comment]
This is a pretty old fix. Has it not made it into stable yet? I think it's not a high risk change. It should be a noop in all browsers, except in Safari where you can't get worse than it was before that fix.

**Comment by ollydixon** [comment]
Is it possible to get an ETA? ☺️ Professional developers are waiting on this for web to be viable since unfortunately there's a big Safari audience 🤡

**Comment by zanderso** [comment]
I have made a CP PR here https://github.com/flutter/engine/pull/38154. @ollydixon in the future when requesting a cherry-pick, you should create a PR against the target branch as part of the request. Not sure when the next hotfix release is scheduled though. We're quite late in the 3.3 cycle, and shifting to a more recent beta may be a better bet.

@itsjustkevin the ci.yaml check is failing on the CP PR, and I don't know how to fix it.
