### ISSUE TITLE
can not install flutter use "flutter doctor"

### ISSUE THREAD

**Issue by 52lemon** [flutter/flutter#11657]
## Steps to Reproduce
when i install flutter on windows system with command "flutter doctor", during the installing ,i got an
exception that "oops,flutter has existed unexpectedly"

here is the codes:

`
C:\Users\Administrator> flutter doctor
Checking Dart SDK version...
Downloading Dart SDK 1.25.0-dev.9.0...
Unzipping Dart SDK...
Updating flutter tool...
Got socket error trying to find package coverage at https://pub.dartlang.org.
Error: Unable to 'pub upgrade' flutter tool. Retrying...

等等待待 0 秒秒，，按按 CTRL+C 退退出出 ...

  â•”â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â
•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•—
  â•‘                 Welcome to Flutter! - https://flutter.io                   â•‘
  â•‘                                                                            â•‘
  â•‘ The Flutter tool anonymously reports feature usage statistics and crash    â•‘
  â•‘ reports to Google in order to help Google contribute improvements to       â•‘
  â•‘ Flutter over time.                                                         â•‘
  â•‘                                                                            â•‘
  â•‘ Read about data we send with crash reports:                                â•‘
  â•‘ https://github.com/flutter/flutter/wiki/Flutter-CLI-crash-reporting        â•‘
  â•‘                                                                            â•‘
  â•‘ See Google's privacy policy:                                               â•‘
  â•‘ https://www.google.com/intl/en/policies/privacy/                           â•‘
  â•‘                                                                            â•‘
  â•‘ Use "flutter config --no-analytics" to disable analytics and crash         â•‘
  â•‘ reporting.                                                                 â•‘
  â•šâ•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â
•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•

Downloading Material fonts...
Downloading package sky_engine...
Downloading windows-x64 tools...
Downloading android-arm-profile/windows-x64 tools...
Downloading android-arm-release/windows-x64 tools...
Downloading android-x86 tools...
Downloading android-x64 tools...
Downloading android-arm tools...
Downloading android-arm-profile tools...
Downloading android-arm-release tools...
Downloading Gradle Wrapper...

Oops; flutter has exited unexpectedly.
Crash report written to C:\Users\Administrator\flutter_01.log;
please let us know at https://github.com/flutter/flutter/issues.
`

## Logs

`
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter doctor

## exception

SocketException: SocketException: OS Error: 信号灯超时时间已到
, errno = 121, address = android.googlesource.com, port = 53286

```
#0      fetchUrl (package:flutter_tools/src/base/net.dart:18)
<asynchronous suspension>
#1      _downloadFile (package:flutter_tools/src/cache.dart:400)
<asynchronous suspension>
#2      _downloadZippedTarball.<anonymous closure> (package:flutter_tools/src/cache.dart:416)
<asynchronous suspension>
#3      _withTemporaryFile (package:flutter_tools/src/cache.dart:428)
<asynchronous suspension>
#4      _downloadZippedTarball (package:flutter_tools/src/cache.dart:415)
#5      GradleWrapper.updateInner (package:flutter_tools/src/cache.dart:389)
<asynchronous suspension>
#6      CachedArtifact.update (package:flutter_tools/src/cache.dart:223)
<asynchronous suspension>
#7      Cache.updateAll (package:flutter_tools/src/cache.dart:196)
<asynchronous suspension>
#8      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:206)
<asynchronous suspension>
#9      FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:162)
<asynchronous suspension>
#10     CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#11     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:277)
<asynchronous suspension>
#12     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#13     new Future.sync (dart:async/future.dart:222)
#14     CommandRunner.run (package:args/command_runner.dart:109)
#15     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:161)
#16     run.<anonymous closure> (package:flutter_tools/executable.dart:142)
<asynchronous suspension>
#17     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#18     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#19     _rootRun (dart:async/zone.dart:1120)
#20     _CustomZone.run (dart:async/zone.dart:1001)
#21     runZoned (dart:async/zone.dart:1467)
#22     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#23     run (package:flutter_tools/executable.dart:114)
<asynchronous suspension>
#24     main (package:flutter_tools/executable.dart:67)
<asynchronous suspension>
#25     main (file:///D:/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
#26     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

## flutter doctor

```
[✓] Flutter (on Microsoft Windows [Version 6.1.7601], locale zh-CN, channel alpha)
    • Flutter at D:\flutter
    • Framework revision b156a0f054 (5 days ago), 2017-08-11 22:01:40 -0700
    • Engine revision fef7d827d6
    • Tools Dart version 1.25.0-dev.9.0

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).
      If Android SDK has been installed to a custom location, set $ANDROID_HOME to that location.

[✗] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[✓] Connected devices
    • None

`

**Comment by eseidelGoogle** [comment]
It looks like android.googlesource.com may not be accessible from china: http://ping.chinaz.com/android.googlesource.com.

**Comment by eseidelGoogle** [comment]
https://github.com/flutter/flutter/issues/11681
