### ISSUE TITLE
TextFormField - cursor stay at the start of the line on IOS.

### ISSUE THREAD

**Issue by kovilevi98** [flutter/flutter#116521]
I am using the simple TextFormField widget from flutter/material . Unfortunately on some ios devices the cursor not moving while the user starts writing. I know it is hard to reproduce this issue, but maybe somebody already knows the solution. 
Here is the [video](https://youtube.com/shorts/fGFTeequqlc?feature=share) about the problem. 
```
TextFormField(
          focusNode: focusNode,
          decoration: InputDecoration(
              border: InputBorder.none,
              hintText: AppLocalizations.of(context)!.type_something),
          controller: widget.textController,
          scrollPadding: const EdgeInsets.all(20.0),
          keyboardType: TextInputType.multiline,
          minLines: 20,
          maxLines: 99999,
          autofocus: false,
        ),
```

**Comment by darshankawar** [comment]
@kovilevi98 
Can you provide `flutter doctor -v` and the device details on which you are seeing this behavior ?


> hintText: AppLocalizations.of(context)!.type_something)

Does this also occur without app localization ? ie, with simple plain English ?

**Comment by kovilevi98** [comment]
Thank you for the fast reply, yes the problem is still there with a sample string as well. Unfortunately, it is tough to reproduce because, it is not a constant issue, sometimes it appears on the same device sometimes it is not. (And with a physical keyboard almost every time, I can accept that problem). i.e device: Iphone 12 mini with IOS 15.1.1.
flutter doctor: 
```
[✓] Flutter (Channel unknown, 3.1.0, on Microsoft Windows [Version 10.0.19044.2251], locale hu-HU)
    • Flutter version 3.1.0 at C:\Users\Levi\Documents\flutter
    • Upstream repository unknown
    • Framework revision bcea432bce (7 months ago), 2022-05-26 09:05:34 -0700
    • Engine revision 44e5b38ee8
    • Dart version 2.18.0 (build 2.18.0-44.1.beta)
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Levi\AppData\Local\Android\sdk
    • Platform android-33, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.10)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.32126.315
    ✗ Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop
      development with C++" workload, and include these components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK

[✓] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2021.2.2
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.73.1)
    • VS Code at C:\Users\Levi\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19044.2251]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 108.0.5359.96
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 105.0.1343.53

[✓] HTTP Host Availability
    • All required HTTP hosts are available

```

**Comment by darshankawar** [comment]
> Channel unknown, 3.1.0,

Thanks for the update. Can you upgrade to latest stable or master version and try the same use case again to know if it still persist or not ?



> (And with a physical keyboard almost every time, I can accept that problem)

Do you mean with physical keyboard it replicates often ?

**Comment by kovilevi98** [comment]
Unfortunately, the issue is still there. And yes based on the user's reports with the physical keyboard it replicates more often.

**Comment by darshankawar** [comment]
Thanks for the update. Are you able to replicate this behavior consistently at your end or is this coming from production ?
If so, is there a way to get the device details on which it occurs consistently ?

**Comment by kovilevi98** [comment]
Unfortunately, non of the users could reproduce this consistently. I have just started receiving bug reports from production and am trying to collect as much data as possible from them. But still, the video is the most helpful information.

**Comment by darshankawar** [comment]
I am unable to replicate this using physical keyboard that I used to input in simulator. The cursor moves as expected.
Based on the report and video shared earlier, I am keeping this issue open for team's attention and insights.
There's a related issue but with emojis though: https://github.com/flutter/flutter/issues/50563

**Comment by goderbauer** [comment]
Can you share a runable code sample that showcases the issue?
