### ISSUE TITLE
The text widget behaves as if the maxLines property were set to 1 when the overflow property is set.

### ISSUE THREAD

**Issue by mi875** [flutter/flutter#116570]
As the title, the text widget behaves as if the maxLines property were set to 1 when the overflow property is set.
But, I set the maxLines property null.

## Sample code

```dart
Text(
    "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
    maxLines: null,
    overflow:TextOverflow.ellipsis,
 ),
```

**Comment by exaby73** [comment]
Hi @mi875 
I see there's an open issue addressing the case you described https://github.com/flutter/flutter/issues/15465
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by mi875** [comment]
As you said, the issue you mentioned is exactly same as my issue. I think this issue should be closed too. I'm sorry about that. Thank you.
