### ISSUE TITLE
[CP] PlatformViews needs clipRect

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#116529]
### issue_link

https://github.com/flutter/flutter/issues/114784

### Commit Hash

https://github.com/flutter/engine/commit/f7df812d26b761d4d337cb1e93a416dd8d8e371e

### Target

beta

### pr_link

https://github.com/flutter/engine/pull/38071

### Impacted Users

All Impeller users

### Impact Description

Addresses a performance issue with Impeller in which rendering work would be duplicated in the presence of platform views.

### Workaround

There is no workaround.

### Risk

low

### Test Coverage

yes

### Validation Steps

Inspect before/after timeline traces in an app using platform views with Impeller enabled. There will be much less work on the raster thread in the after timeline.

**Comment by zanderso** [comment]
No, not necessary to backport to 3.3.

**Comment by itsjustkevin** [comment]
CC @CaseyHillers and @godofredoc for approval.
FYI @muditatandon who will be the release engineer.
