### ISSUE TITLE
Downloading Dart SDK issue, curl: (18) transfer closed with 47657195 bytes remaining to read

### ISSUE THREAD

**Issue by lishuhao** [flutter/flutter#11651]
```
👉 hao@~ $ flutter
Downloading Dart SDK 1.25.0-dev.9.0...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
 24 60.4M   24 14.9M    0     0  52001      0  0:20:18  0:05:01  0:15:17 60587
curl: (18) transfer closed with 47657195 bytes remaining to read
```
My net is slow！I tried a lot of times.
What is the download url ? can i manually download it and place it in the right dir?

**Comment by lishuhao** [comment]
By looking at the source code I got the download url.
But can i manually download it and place it in the right dir?

**Comment by lishuhao** [comment]
I fixed it,it is my proxy problem

**Comment by Hixie** [comment]
We should more gracefully report errors of this nature.

**Comment by mmbatha** [comment]
![2019-05-23 (4)](https://user-images.githubusercontent.com/35221544/58271463-61ba3f00-7d8c-11e9-9049-fcf1e94c7617.png)
If one doesn't have `unzip` installed, running `flutter doctor` will download the dart_sdk but deem it corrupted after downloading. Perhaps, `unzip` should be a prerequisite...

**Comment by christopherfujino** [comment]
failing more gracefully was fixed in https://github.com/flutter/flutter/pull/16244.
