### ISSUE TITLE
flutter/tests need to support Dart 3

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#116671]
- [x] DanTup_tiler - Does not support null safety, removal PR https://github.com/flutter/tests/pull/179
- [x] flutter_cocoon - https://github.com/flutter/cocoon/pull/2339
- [x] flutter_gallery - https://github.com/flutter/gallery/pull/839 - https://github.com/flutter/tests/pull/180
- [x] flutter_packages
- [x] flutter_portal - https://github.com/fzyzcjy/flutter_portal/pull/94
- [ ] flutter_reactive_ble `>=2.12.0 <3.0.0` - https://github.com/flutter/tests/pull/181
- [x] flutter_svg `>=2.17.0 <3.0.0'`
- [x] provider
- [x] super_editor `>=2.12.0 <3.0.0`

**Comment by mit-mit** [comment]
https://github.com/flutter/gallery looks ready: `sdk: ">=2.17.0 <3.0.0"`

**Comment by Hixie** [comment]
Remember that any change that requires a change to flutter/tests MUST come with a migration guide that explains how people can migrate.

**Comment by mit-mit** [comment]
We already have those on the Dart site; are you suggesting we also create an entry for this on https://docs.flutter.dev/release/breaking-changes ?

**Comment by CaseyHillers** [comment]
@mit-mit that SGTM. Do you or @itsjustkevin have comms for this?

**Comment by Hixie** [comment]
Yeah, a pointer to the Dart docs from that page would be great.

**Comment by itsjustkevin** [comment]
@atsansone @MaryaBelanger how do we want to approach this?

cc @nuritzi

**Comment by CaseyHillers** [comment]
@jason-simmons sent https://github.com/flutter/tests/pull/184 to temporarily disable the ble tests. Marking this as fixed as the roll PR is unblocked in https://github.com/flutter/flutter/pull/116635

**Comment by mit-mit** [comment]
About the breaking changes docs, I think perhaps the content in https://github.com/dart-lang/sdk/issues/49530 might be helpful?

**Comment by atsansone** [comment]
@mit-mit : Are you thinking that we add a link to [this migration guide in dart.dev](https://dart.dev/null-safety/migration-guide) to the [Flutter breaking changes page](https://docs.flutter.dev/release/breaking-changes#not-yet-released-to-stable)?
