### ISSUE TITLE
Flutter animation/gif/lottie using too much gpu on windows

### ISSUE THREAD

**Issue by WxqKb** [flutter/flutter#116648]
## Details
**Target Platform:** windows-x64
**Target OS version/browser:** Windows 10
**Devices:** Windows PC

## code
` 
  Widget buildCheckingView(BuildContext context) {
    return Column(
      children: [
        SizedBox(height: 198.h),
        RepaintBoundary(
          child: CircularProgressIndicator()
          // const CheckingAnimation(),
        ),
        SizedBox(height: 32.h),
        Text('checking'.tr, style: Theme.of(context).textTheme.bodyText2),
      ],
    );
  }
`

## Step
1. Create a empty project
2. Show a widget，like CupertinoActivityIndicator、CircularProgressIndicator、Image.asset('xxx.gif')
3. View task manager, gpu usage is too high
![image](https://user-images.githubusercontent.com/48406291/206172639-146a3a48-f035-4d92-ae54-82342d038278.png)
![image](https://user-images.githubusercontent.com/48406291/206172694-04306b87-4949-423d-b9b7-5e3e89e9de4e.png)

So when we need to display a running animation in a full-screen page, the performance will become very poor.
We urgently need to fix this performance issue. Thanks

## Flutter doctor
[√] Flutter (Channel stable, 3.3.9, on Microsoft Windows [版本 10.0.19042.2251], locale zh-CN)
    • Flutter version 3.3.9 on channel stable at E:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b8f7f1f986 (2 weeks ago), 2022-11-23 06:43:51 +0900
    • Engine revision 8f2221fbef
    • Dart version 2.18.5
    • DevTools version 2.15.0

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.2.4)    
    • Visual Studio at D:\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.2.32602.215
    • Windows 10 SDK version 10.0.19041.0

**Comment by exaby73** [comment]
Hello @WxqKb. Thank you for filing this issue. Can you please provide the following information?

- A [complete and minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). Ideally, a single `main.dart` file that can be run directly.

Please provide the information in the form of text. See how to make collapsible sections with Markdown [here](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-collapsed-sections).

**Comment by WxqKb** [comment]
> Hello @WxqKb. Thank you for filing this issue. Can you please provide the following information?
> 
> * A [complete and minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). Ideally, a single `main.dart` file that can be run directly.
> 
> Please provide the information in the form of text. See how to make collapsible sections with Markdown [here](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-collapsed-sections).

`
class InstallingAnimation extends StatefulWidget {
  const InstallingAnimation({Key? key}) : super(key: key);

  @override
  State<InstallingAnimation> createState() => _InstallingAnimationState();
}

class _InstallingAnimationState extends State<InstallingAnimation>
    with TickerProviderStateMixin {
  late AnimationController _controller;
  late Animation<double> _animation;
  late Animation<double> _animationSmall;
  late int mill;

  @override
  void initState() {
    mill = DateTime.now().millisecondsSinceEpoch;
    _controller = AnimationController(
      vsync: this,
      duration: const Duration(seconds: 16),
    )..repeat();
    // 创建一个从0到360弧度的补间动画 v * 2 * π
    _animation = Tween<double>(begin: 0, end: 1).animate(_controller);
    _animationSmall = Tween<double>(begin: 1, end: 0).animate(_controller);
    super.initState();
  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return SizedBox(
      width: 206.w,
      height: 150.h,
      child: Stack(
        fit: StackFit.expand,
        children: [
          Positioned(
            top: 0,
            left: 0,
            child: RotationTransition(
              turns: _animation,
              child: Image.asset(
                AssetNames.icGearBig,
                width: 128.w,
                height: 128.w,
                fit: BoxFit.cover,
                isAntiAlias: true,
              ),
            ),
          ),
          Positioned(
            bottom: 0,
            right: 0,
            child: RotationTransition(
              turns: _animationSmall,
              child: Image.asset(
                AssetNames.icGearSmall,
                width: 86.w,
                height: 86.w,
                fit: BoxFit.cover,
                isAntiAlias: true,
              ),
            ),
          ),
        ],
      ),
    );
  }
}
`
In this example, just change the rotated image resource. The following machine takes up 70% of the GPU
Machines with low performance far exceed 100%

![image](https://user-images.githubusercontent.com/48406291/206600272-8081e715-8f88-455d-b521-f10993894005.png)

**Comment by WxqKb** [comment]
In fact, when I use the timer to draw the animation, the frame rate is controlled at 30 frames, and the gpu usage rate is only 27%. If the animation can provide the frame number parameter, this problem may be solved.

**Comment by exaby73** [comment]
Can you provide a sample in the form of a public repo? Also, it would be better if there is no 3rd party libraries. If your issue is with lottie, please raise an issue on their repository as we do not provide support for 3rd party libraries
