### ISSUE TITLE
Setting variables outside state class causing flutter app to lag and crash

### ISSUE THREAD

**Issue by madamoniem** [flutter/flutter#116696]
Hello,
I was developing my Flutter mobile application a while back, and came across an issue I would like to report. Changing the version to Flutter 2.10.5 fixes the issue, but I would like to use the latest version.

https://stackoverflow.com/questions/74526831/setting-variables-outside-state-class-causing-flutter-app-to-lag-and-crash

**Comment by exaby73** [comment]
Hello @madamoniem. Defining global variables is not recommended. I suggest you use something like `InheritedWidget` or a state management solution like provider or riverpod to manage global, app level variables.
