### ISSUE TITLE
[CP] Skia [metal] Fix issues with non-AA clip

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#116618]
### issue_link

https://github.com/flutter/flutter/issues/110628

### Commit Hash

https://skia-review.googlesource.com/c/skia/+/614058

### Target

beta

### pr_link

N/A

### Impacted Users

Flutter apple apps that use `doAntiAlias = false`

### Impact Description

Apple apps will appear to have visual jank

### Workaround

Avoid setting anti aliasing to false in apps

### Risk

low

### Test Coverage

yes

**Comment by CaseyHillers** [comment]
This is blocked on:

1. https://bugs.chromium.org/p/skia/issues/detail?id=13975 - Create skia branch
2. https://bugs.chromium.org/p/skia/issues/detail?id=13976 - CP requested revision

Once those are resolved, the release engineer can CP the skia revision.

\cc @zanderso can you review this CP request?

**Comment by zanderso** [comment]
CP lgtm

**Comment by CaseyHillers** [comment]
https://skia.googlesource.com/skia/+/refs/heads/flutter/flutter-3.7-candidate.1 is created

**Comment by CaseyHillers** [comment]
https://skia-review.googlesource.com/c/skia/+/615276 is submitted.

@XilaiZhang (release engineer for next week), can you CP this in?

**Comment by XilaiZhang** [comment]
Sure, I will remember to do a skia cp before engine cp next week

**Comment by XilaiZhang** [comment]
oh cool, did kevin cp this in for the beta release?
