### ISSUE TITLE
Have  SelectionArea's selectionControls display and function for web and mac

### ISSUE THREAD

**Issue by Hendler** [flutter/flutter#116607]
It would nice to have `selectioncontrols` available for web and macOS to create consistency between platforms.

see https://github.com/flutter/flutter/issues/116576 

https://stackoverflow.com/questions/72747672/how-to-add-toolbar-above-text-in-flutter-web
https://pub.dev/packages/selectable 

## Use case
Custom selectioncontrols may be central to an application's use cases. 

## Proposal

Sorry, this is not a very cohesive, or strict proposal. 
selectioncontrols displays and functions similarly to mobile but instead of `onTap` or `onPress`, it can triggered by `onMouseUp`. 

Sorry, I am new to flutter, and this may be something that is possible by other means, in which case perhaps the documentation is missing?

I am familiar with javascript that can be used to customize events to display a tooltip over selected text (e.g. on mouseup). Maybe this requires custom gesture control in Flutter? Perhaps this can be accomplished already with an "if web" and custom html.

Side note - `window.getSelection()` web is a simplified abstraction that seems more difficult in Flutter and requires using clipboard, exposing selected text to other applications.

**Comment by chunhtai** [comment]
I am not sure whats the proposal. Is it
1. ability to use selection control to replace web right click context menu?
2. ability to reuse the selection control widget else where such as a tooltip?

If it is 1, we need a way to disable browser right click and handle it exclusively in framework, which i think is doable. But I am not sure whether we should do it.

If it is 2, we may be able to open up some internal widget class. cc @justinmc

**Comment by Hendler** [comment]
> My impression was that we want `SelectableText` to be deprecated, now that we have [SelectableRegion](https://api.flutter.dev/flutter/widgets/SelectableRegion-class.html). SelectableText has other problems on the web. It presents itself as a text box to accessibility, which leads to awkwardness when interacting with it.
> 
> cc @chunhtai

The proposal is more about the `SelectableRegion` used in `SelectionArea` ( a subclass of SelectableRegion?). I'll change title to reflect that.

**Comment by gspencergoog** [comment]
@Hendler Does this PR address your use case? https://github.com/flutter/flutter/pull/107193

**Comment by Hendler** [comment]
> @Hendler Does this PR address your use case? #107193

I think it might! 

It's probably a separate concern to have flutter have an abstracted `window.getSelection()` ?

**Comment by gspencergoog** [comment]
Yes, it probably is a separate concern.  I'll close this issue then, and if you need the `window.getSelection()`, could you please file a separate issue?
