### ISSUE TITLE
Page refresh in web app not maintaining state in go_router

### ISSUE THREAD

**Issue by Payalpatel-wrteam** [flutter/flutter#116649]
State not maintained in page refresh in web app: 
Im using go_router for navigation in flutter web app.
If i use any state management plugin, and refresh the browser my all global states are reset. 
Even i tried the example code of go_router repository, in that also state is not maintained on page refresh.
Please provide solution asap, because without this whole app code is useless.
Im giving link of  video for reference.
https://drive.google.com/file/d/1vHnN7Q1pvZqVdaw-gopqHoe6EcUCJmJY/view?usp=share_link

**Comment by danagbemava-nc** [comment]
In the issue I linked to, the refresh happens in the browser, not from the IDE. See the video in https://github.com/flutter/flutter/issues/114597#issue-1434439769 for more context

**Comment by Payalpatel-wrteam** [comment]
hello sir, page refresh works in browser, But if the user logged in and refresh the page then login state is reset. User need to login again after each page refresh.  Is there any solution for this?

**Comment by danagbemava-nc** [comment]
Hi @Payalpatel-wrteam,

Can you please provide your `flutter doctor -v` and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)? 

Please also provide the version of go_router you're using.

Thank you
