### ISSUE TITLE
[local_auth] Biometric with local auth can be speedy?

### ISSUE THREAD

**Issue by divyaEncodework** [flutter/flutter#116698]
i have used local auth in my flutter application
but i have to press confirm button after detecting my face.
app not redirects directly to my home page like other applications like google pay etc.
can you provide any informations about that how can i remove that confirm button and directly redirect to application home page?

**Comment by danagbemava-nc** [comment]
Hi @divyaEncodework, does the confirm button only show up when you use faceID? or does it show up when you use fingerprint unlock as well? 

Also, what device are you testing on?

**Comment by divyaEncodework** [comment]
no confirm button shows up in fingerprint and face id both.
i am testing in samsung galaxy f23 5g.

**Comment by danagbemava-nc** [comment]
Hi @divyaEncodework, when you call `LocalAuthentication().authenticate(...)` do you get a response after you click on confirm, or do you get a response the moment you verify your biometric?

**Comment by divyaEncodework** [comment]
i got response when i click confirm button.

**Comment by divyaEncodework** [comment]
hey there! @danagbemava-nc i have found solution for in i just have to set  sensitiveTransaction: false in AuthOptions like this ---> 
authenticated = await auth.authenticate(
        localizedReason: 'Let OS determine authentication method',
        options: const AuthenticationOptions(
          useErrorDialogs: false,
          sensitiveTransaction: false,
        ),
      );

**Comment by danagbemava-nc** [comment]
Glad to see your issue has been resolved. 

I'll be closing this as solved. 

Thank you

**Comment by divyaEncodework** [comment]
@danagbemava-nc 
yes, sure.
Thank you
