### ISSUE TITLE
Voiceover does not know how to scroll a flutter widget into view

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#11666]
VoiceOver works in Hamilton. :)  But it doesn't know how to scroll to items offscreen (like Obj-C apps do).

I suspect you already have this tracked, but just in case.

**Comment by goderbauer** [comment]
This is covered by https://github.com/flutter/flutter/issues/1714.

tl;dr: It's fixed on Android (modulo some known bugs). How to implement the same on iOS is still unknown. Will probably need to talk to an iOS accessibility expert.
