### ISSUE TITLE
Create fuchsia_r51 branch

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#116677]
Revision: engine#d5690468da0fdf421403848bc3b948cbbda6b7c0

- [ ] Create flutter and engine branch
- [ ] Create recipe branch

**Comment by CaseyHillers** [comment]
Branching process:

```
$ git fetch --all
$ git checkout upstream/main -b fuchsia_r51
$ git reset --hard d5690468da0fdf421403848bc3b948cbbda6b7c0
$ git push upstream HEAD
```

However, that failed on

```
chillers@chillzone:~/engine$ git push upstream HEAD
Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
remote: error: GH006: Protected branch update failed for refs/heads/fuchsia_r51.
remote: error: This branch must not contain merge commits. You're not authorized to push to this branch. Visit https://docs.github.com/articles/about-protected-branches/ for more information.
To github.com:flutter/engine
 ! [remote rejected]       HEAD -> fuchsia_r51 (protected branch hook declined)
error: failed to push some refs to 'github.com:flutter/engine'
```

I'm going to debug the ACL issue, but I'll finish the release infra set up. I went and found the closest framework commit, as that's needed to generate a recipe branch. I paired it to afda8153fd2d2c32c8495ad008d6c25fa8203df1 and created the equivalent Flutter branch.

Cocoon should be able to create the recipe branch in the next few minutes.

**Comment by CaseyHillers** [comment]
\cc @itsjustkevin as FYI - this is from http://go/flutter-self-service-branches. I'll update the doc with the latest info

**Comment by godofredoc** [comment]
Is this something `pushers-beta` should have access to or only pushers-fuchsia?

**Comment by godofredoc** [comment]
@chaselatta FYI

**Comment by naudzghebre** [comment]
@akbiggs FYI

**Comment by naudzghebre** [comment]
What exactly is pushers-beta/pushers-fuchsia ?

**Comment by CaseyHillers** [comment]
Most of this discussion was moved to chat to help resolve. ACLs were resolved, and documented workflows were updated

https://github.com/flutter/engine/tree/fuchsia_r51
https://flutter.googlesource.com/recipes/+/refs/heads/fuchsia_r51
