### ISSUE TITLE
Text isn't rendering on phones when using CanvasKit on Flutter Web

### ISSUE THREAD

**Issue by eiler21** [flutter/flutter#116606]
## Steps to Reproduce

1. Build using canvaskit `flutter build web --web-renderer canvaskit` 
2. Load in Chrome on an Android phone (in my case I used OnePlus 5)

I have seen a similar thread before and it was closed. However the issue still occurs even in Flutter version 3.3.9.

| expected result | actual result |
| -- | -- |
| <img src="https://user-images.githubusercontent.com/54715355/205994601-f55d08a4-ca75-4361-8962-e6d56565615f.jpeg" /> | <img src="https://user-images.githubusercontent.com/54715355/205994671-fc14ad05-61ea-4e98-b277-75568cc87773.jpeg" /> |

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel stable, 3.3.9, on macOS 12.5 21G72 darwin-arm, locale en-EE)
    • Flutter version 3.3.9 on channel stable at /opt/homebrew/Caskroom/flutter/2.10.4/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b8f7f1f986 (2 weeks ago), 2022-11-23 06:43:51 +0900
    • Engine revision 8f2221fbef
    • Dart version 2.18.5
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/karp/Library/Android/sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] VS Code (version 1.73.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.54.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.5 21G72 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 108.0.5359.94

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by danagbemava-nc** [comment]
Hi @eiler21,

Please provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we can investigate this issue. 

Thank you

**Comment by danagbemava-nc** [comment]
Hi @eiler21, I cannot seem to reproduce your issue. I deployed the counter app using canvaskit and tested it on my Poco X3 NFC and the content rendered just fine. See the screenshot below. I'm using the Chrome inspect tool so that I can show the renderer and the content. 

I tested this in both debug and release mode and it worked just fine. 

Can you use the chrome inspect tool to see if you see any errors in your console? 

Also, what version of chrome are you using, and does this only happen on your OnePlus device or other devices are affected as well? 
And finally, what OS is your OnePlus running?

![Screenshot 2022-12-08 at 06 15 11](https://user-images.githubusercontent.com/88313112/206371979-4b0731ac-2643-4102-b267-d90eeb14e942.png)

**Comment by eiler21** [comment]
Yes, this happens only on a OnePlus phone. I will use the chrome inspect tool, check the version of Chrome and the version of the OS my phone is using a little bit later.

**Comment by danagbemava-nc** [comment]
Hi @eiler21, kindly update when you're able to test. 

Thank you
