### ISSUE TITLE
MouseRegion - Curser not changing, neither is onEnter and onExit being called for kind = PointerDeviceKind.stylus

### ISSUE THREAD

**Issue by shadman-filo** [flutter/flutter#116638]
For stylus that support hover events (like wacom / xp-pen pen-tablets on a web or Android, Samsung Galaxy Note stylus), `MouseRegion` does not respond to `onEnter` and `onExit` callbacks, and neither does it change the mouse curser (default system curser is rendered). `onHover` event is still being called with `event.kind == PointerDeviceKind.stylus`

Related to this, curser does not change to `click` when hovering over `Inkwell` or other button widgets when using any of these devices.  

### On Web

1. Connect a wacom stylus or an xp-pen pen-tablet on to your device
2. You will be able to control the system mouse curser with the connected device
3. Execute `flutter run` on the code sample

### On Android

1. Connect a wacom stylus or an xp-pen pen-tablet on to your android device using USB. 
2. You will be able to control the system mouse curser with the connected device
3. Execute `flutter run` on the code sample

### On Samsung Galaxy Note

1. Execute `flutter run` on the code sample
2. Bringing the stylus close to the screen, a dotted circle appears on the device. 
3. `MouseRegion` starts responding to `onHover` events, giving event details.

**Expected results:** 
1. `onEnter` to be called when pointer enters the `MouseRegion`
2. `onExit` to be called 

**Actual results:** 

<details>
<summary>Code sample</summary>

```dart
      MouseRegion(
        cursor: SystemMouseCursors.click,
        onEnter: (details) {
          print("onEnter: Kind: ${details.kind}");
        },
        onHover: (details) {
          print("onHover: Kind: ${details.kind}");
        },
        onExit: (details) {
          print("onExit: Kind: ${details.kind}");
        },
        child: Container(
          color: Colors.lightBlueAccent,
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              const Text(
                  'You have entered or exited this box this many times:'),
              Text(
                '$_enterCounter Entries\n$_exitCounter Exits',
                style: Theme.of(context).textTheme.headline4,
              ),
              Text(
                'The cursor is here: (${x.toStringAsFixed(2)}, ${y.toStringAsFixed(2)})',
              ),
            ],
          ),
        ),
      ),
    )
```

</details>

<details>
  <summary>Logs</summary>

### When using mouse
```
onEnter: Kind: PointerDeviceKind.mouse
onHover: Kind: PointerDeviceKind.mouse
onHover: Kind: PointerDeviceKind.mouse
onHover: Kind: PointerDeviceKind.mouse
onHover: Kind: PointerDeviceKind.mouse
onExit: Kind: PointerDeviceKind.mouse
```

### When using a wacom or xp-pen pen-tablet
(Same for using stylus on Samsung Galaxy Note)
```
onHover: Kind: PointerDeviceKind.stylus
onHover: Kind: PointerDeviceKind.stylus
onHover: Kind: PointerDeviceKind.stylus
onHover: Kind: PointerDeviceKind.stylus
```
(onEnter and onExit functions are not called)

### Output of  `flutter doctor -v`
```
[✓] Flutter (Channel stable, 3.0.3, on macOS 13.0.1 22A400 darwin-arm, locale en-IN)
    • Flutter version 3.0.3 at /opt/homebrew/Caskroom/flutter/2.0.6/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 676cefaaff (6 months ago), 2022-06-22 11:34:49 -0700
    • Engine revision ffe7b86a1e
    • Dart version 2.17.5
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/shadmananwer/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /Library/Java/JavaVirtualMachines/zulu-8.jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (Zulu 8.56.0.23-CA-macos-aarch64) (build 1.8.0_302-b08)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] IntelliJ IDEA Ultimate Edition (version 2022.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 71.0.5
    • Dart plugin version 222.4345.14

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.0.1 22A400 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 108.0.5359.94

[✓] HTTP Host Availability
    • All required HTTP hosts are available
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @shadman-filo, you appear to be on an older version of the stable channel. 

Can you upgrade to the latest version of stable/master to see whether or not this issue reproduces?

If it does, kindly provide the updated output of `flutter doctor -v`. 

> Related to this, the cursor does not change to click when hovering over Inkwell or other button widgets when using any of these devices.

Please also file a separate issue for this so it can be properly addressed. 

Thank you
