### ISSUE TITLE
[ios] Swiping a listview containing platform views has noticeable jitter on Promotion devices

### ISSUE THREAD

**Issue by 0xZOne** [flutter/flutter#116640]
After https://github.com/flutter/engine/pull/37434 landed, there is still noticeable jitter when swiping a listview containing platform views on the iPhone 13 Pro Max. However, it's very smooth on non-ProMotion devices, e.g., iPhone 8. As shown in the video below.

/cc @cyanglaz

https://user-images.githubusercontent.com/26625149/206125015-9991ea5b-a92c-4831-8abf-65a396875bb6.MP4

<ins>**Confusingly, reducing the frame rate to 80 makes the swiping smoother, but reducing it to 60 is just as bad as 120.**</ins>

According to the official documentation ([link](https://developer.apple.com/documentation/quartzcore/optimizing_promotion_refresh_rates_for_iphone_13_pro_and_ipad_pro?language=objc)), the issue seems to be that the frame rate the system finally chooses is 80, but the flutter rendering pipeline is 120. ;-)

> Core Animation arbitrates all the animations it presents on the screen and determines the refresh rate at any particular time.

<img width="818" alt="image" src="https://user-images.githubusercontent.com/26625149/206128557-266e4560-aa05-480d-8902-4c2d12db6d6c.png">

## Steps to Reproduce

1. `git clone -b task/displaylink git@github.com:0xZOne/platform_view_performance.git`
2. `cd platform_view_performance`
3. `flutter run`

Related issue: https://github.com/flutter/flutter/issues/101653

<details>
  <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel main, 3.7.0-3.0.pre.14, on macOS 12.6 21G115 darwin-x64, locale zh-Hans-CN)
    • Flutter version 3.7.0-3.0.pre.14 on channel main at /Users/zero/fvm/versions/main
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18534a8e4c (2 days ago), 2022-12-04 17:44:35 -0500
    • Engine revision 359a0a979a
    • Dart version 2.19.0 (build 2.19.0-444.0.dev)
    • DevTools version 2.20.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

Checking Android licenses is taking an unexpectedly long time...[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/zero/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • ANDROID_HOME = /Users/zero/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.73.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.54.0

[✓] Connected device (2 available)
    • 艾尔玛的iPhone (2) (mobile) • 00008110-001A30960238401E • ios        • iOS 15.5 19F77
    • macOS (desktop)         • macos                     • darwin-x64 • macOS 12.6 21G115 darwin-x64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by cyanglaz** [comment]
We might need to adjust the `preferredFrameRateRange` of the CADisplayLink on the rendering time of the last few frames. This is something we have discussed in the past.
cc @iskakaushik @zanderso 

I can work on a prototype to see if it helps. (I didn't notice the jittering when I tested on iPhone 13 pro, I might need some help testing my prototype when it is ready. :) @0xZOne

**Comment by 0xZOne** [comment]
> 
> I can work on a prototype to see if it helps. (I didn't notice the jittering when I tested on iPhone 13 pro, I might need some help testing my prototype when it is ready. :) @0xZOne

Sure. Looking forward to your prototype.  :)

**Comment by 0xZOne** [comment]
After a round of investigation, I found that function `nextDrawable` is very time-consuming. 

When the swiping page is jitter, the time consumption of this function is about 5~15ms. See the below logs for details.

> A CAMetalLayer object maintains an internal pool of textures for displaying layer content, each wrapped in a [CAMetalDrawable](https://developer.apple.com/documentation/quartzcore/cametaldrawable?language=objc) object. Use this method to retrieve the next available drawable from the pool. If all drawables are in use, the layer waits up to one second for one to become available, after which it returns nil. The [allowsNextDrawableTimeout](https://developer.apple.com/documentation/quartzcore/cametallayer/2887086-allowsnextdrawabletimeout?language=objc) property affects this behavior.

Confusingly, if the frame rate of the engine is reduced to 80hz, the time consumption of this function is negligible after the finger leaves the screen when swiping. However, after reducing to drop to 60hz, the same as at 120hz, the function will appear to be very time-consuming.


Is this an issue with the iOS operating system?  @cyanglaz 

By the way, why can't iOS specify a render target type for `kMTLTexture`? Could you take a moment to clarify? thanks. :)

![0AA435AD-5AF8-4464-940B-4AB4629233EE](https://user-images.githubusercontent.com/26625149/206637684-b7452f5a-5d48-49e3-ade6-0102b2190b68.png)

<details>
<summary>Code sample</summary>

```git
diff --git a/shell/gpu/gpu_surface_metal_skia.mm b/shell/gpu/gpu_surface_metal_skia.mm
index d61931ce06..4971a426c0 100644
--- a/shell/gpu/gpu_surface_metal_skia.mm
+++ b/shell/gpu/gpu_surface_metal_skia.mm
@@ -118,6 +118,7 @@
 
 std::unique_ptr<SurfaceFrame> GPUSurfaceMetalSkia::AcquireFrameFromCAMetalLayer(
     const SkISize& frame_info) {
+  TRACE_EVENT0("flutter", "GPUSurfaceMetalSkia::AcquireFrameFromCAMetalLayer");
   auto layer = delegate_->GetCAMetalLayer(frame_info);
   if (!layer) {
     FML_LOG(ERROR) << "Invalid CAMetalLayer given by the embedder.";
@@ -126,9 +127,12 @@
 
   auto* mtl_layer = (CAMetalLayer*)layer;
   // Get the drawable eagerly, we will need texture object to identify target framebuffer
+  fml::TimePoint start = fml::TimePoint::Now();
   fml::scoped_nsprotocol<id<CAMetalDrawable>> drawable(
       reinterpret_cast<id<CAMetalDrawable>>([[mtl_layer nextDrawable] retain]));
-
+  double cost = (fml::TimePoint::Now() - start).ToMillisecondsF();
+  if (cost > 2)
+  FML_LOG(ERROR) << "### nextDrawable: " << cost << ((cost > 4) ? "ms, Oops ~~~~~" : "");
   if (!drawable.get()) {
     FML_LOG(ERROR) << "Could not obtain drawable from the metal layer.";
     return nullptr;
```

</details>

<details>
  <summary>Logs</summary>


```
Installing and launching...                                        17.6s
Syncing files to device 艾尔玛的iPhone (2)...                           67ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

💪 Running with sound null safety 💪

An Observatory debugger and profiler on 艾尔玛的iPhone (2) is available at: http://127.0.0.1:60116/2jbQAkzvHfw=/
The Flutter DevTools debugger and profiler on 艾尔玛的iPhone (2) is available at: http://127.0.0.1:9100?uri=http://127.0.0.1:60116/2jbQAkzvHfw=/
[VERBOSE-2:gpu_surface_metal_skia.mm(135)] ### nextDrawable: 2.22821
[VERBOSE-2:gpu_surface_metal_skia.mm(135)] ### nextDrawable: 2.89075
[VERBOSE-2:gpu_surface_metal_skia.mm(135)] ### nextDrawable: 2.23504
[VERBOSE-2:gpu_surface_metal_skia.mm(135)] ### nextDrawable: 2.36892
[VERBOSE-2:gpu_surface_metal_skia.mm(135)] ### nextDrawable: 5.34812ms, Oops ~~~~~
[VERBOSE-2:gpu_surface_metal_skia.mm(135)] ### nextDrawable: 2.68696
[VERBOSE-2:gpu_surface_metal_skia.mm(135)] ### nextDrawable: 2.041
[VERBOSE-2:gpu_surface_metal_skia.mm(135)] ### nextDrawable: 2.05908
[VERBOSE-2:gpu_surface_metal_skia.mm(135)] ### nextDrawable: 2.19904
[VERBOSE-2:gpu_surface_metal_skia.mm(135)] ### nextDrawable: 6.55092ms, Oops ~~~~~
[VERBOSE-2:gpu_surface_metal_skia.mm(135)] ### nextDrawable: 6.20467ms, Oops ~~~~~
[VERBOSE-2:gpu_surface_metal_skia.mm(135)] ### nextDrawable: 2.20562
[VERBOSE-2:gpu_surface_metal_skia.mm(135)] ### nextDrawable: 7.17146ms, Oops ~~~~~
[VERBOSE-2:gpu_surface_metal_skia.mm(135)] ### nextDrawable: 3.7095
[VERBOSE-2:gpu_surface_metal_skia.mm(135)] ### nextDrawable: 6.97408ms, Oops ~~~~~
[VERBOSE-2:gpu_surface_metal_skia.mm(135)] ### nextDrawable: 7.24096ms, Oops ~~~~~
[VERBOSE-2:gpu_surface_metal_skia.mm(135)] ### nextDrawable: 2.924
[VERBOSE-2:gpu_surface_metal_skia.mm(135)] ### nextDrawable: 7.19583ms, Oops ~~~~~
[VERBOSE-2:gpu_surface_metal_skia.mm(135)] ### nextDrawable: 15.225ms, Oops ~~~~~
[VERBOSE-2:gpu_surface_metal_skia.mm(135)] ### nextDrawable: 7.3255ms, Oops ~~~~~
[VERBOSE-2:gpu_surface_metal_skia.mm(135)] ### nextDrawable: 6.86271ms, Oops ~~~~~
[VERBOSE-2:gpu_surface_metal_skia.mm(135)] ### nextDrawable: 4.11479ms, Oops ~~~~~
[VERBOSE-2:gpu_surface_metal_skia.mm(135)] ### nextDrawable: 7.6945ms, Oops ~~~~~
[VERBOSE-2:gpu_surface_metal_skia.mm(135)] ### nextDrawable: 3.24825
[VERBOSE-2:gpu_surface_metal_skia.mm(135)] ### nextDrawable: 7.76417ms, Oops ~~~~~
[VERBOSE-2:gpu_surface_metal_skia.mm(135)] ### nextDrawable: 4.89971ms, Oops ~~~~~
[VERBOSE-2:gpu_surface_metal_skia.mm(135)] ### nextDrawable: 6.28554ms, Oops ~~~~~
[VERBOSE-2:gpu_surface_metal_skia.mm(135)] ### nextDrawable: 7.70483ms, Oops ~~~~~
Application finished.
```
</details>

**Comment by 0xZOne** [comment]
With the help of the Animation Hitches tool provided by Xcode, we notice that **Vsync is unstable with jumps when a jitter occurs**. This may be the root cause of the jitter in the ProMotion devices.

![1675F4D1-610F-4AFE-88AE-45E0DA99AF4B](https://user-images.githubusercontent.com/26625149/207010994-77d656d6-da6e-4916-9c0b-497712848015.png)

Taking the 11th jitter as an example( [trace](https://github.com/0xZOne/platform_view_performance/tree/c874bf8a7d5a978d70b62872486e898a51182bf4/log/flutter_swiping_animation_hitches_116640.trace)), the frequency of VSync changes as follows: 60Hz -> 120Hz -> 80Hz -> 120Hz -> 80Hz -> 60Hz. (At this point, the finger has left the screen, and the page is in inertial scrolling.)  It is a very puzzling behavior.

![B20C0D9A-66BB-4050-A697-90FC6C7CF9C6](https://user-images.githubusercontent.com/26625149/207011117-89ecbf56-0786-418d-84d3-f1aedf0442fb.png)

**Comment by 0xZOne** [comment]
When I disable the full range of refresh rates for CADisplayLink callbacks in the demo as below:

`<key>CADisableMinimumFrameDurationOnPhone</key><false/>`

The frame rate of the Flutter engine is 60Hz as expected. **However, there is still some noticeable jitter when swiping views.**

![image](https://user-images.githubusercontent.com/26625149/208064171-fd4083e0-2a8b-49c6-a843-42e48fa4a365.png)
![image](https://user-images.githubusercontent.com/26625149/208064181-58aa102f-0d5b-419a-9723-b2c2a6ab2d62.png)

**Comment by cyanglaz** [comment]
In addition to what @0xZOne has looked:

I looked at the hitch profiler almost all the hitches during the PlatformView scrolling are type: `commit to render latency: delay frame swap`. I'm not entirely sure what caused this latency.

<img width="1669" alt="Screenshot 2022-12-22 at 4 53 59 PM" src="https://user-images.githubusercontent.com/3756895/209250318-479ec638-d75e-40a6-afb3-d814ce3805a4.png">

 I looked at the time profiler during the frame before the hitch, I didn't see anything suspicious.
<img width="1734" alt="Screenshot 2022-12-22 at 5 05 36 PM" src="https://user-images.githubusercontent.com/3756895/209251053-4d5a78bb-3697-4644-a2f0-e36761665c7f.png">

I also created an iOS app trying to mimic the PlatformView scrolling behavior and doesn't have the hitch. 
<details>
  <summary>Sample iOS ViewController.m code</summary>


```objc
//
//  ViewController.m
//  FlutterPlatformViewScrolling
//
//  Created by Chris Yang on 12/22/22.
//

#import "ViewController.h"

static const CGFloat ViewHeight = 100;
static const CGFloat ViewWidth = 200;
static const CGFloat ViewX = 30;
static const CGFloat Padding = 30;

@interface ViewController ()

@property (strong, nonatomic) NSMutableArray *platformViews;
@property (assign, nonatomic) CGFloat acc;
@property (strong, nonatomic) CADisplayLink *displayLink;

@end

@implementation ViewController

- (void)loadView {
  [super loadView];
  self.platformViews = [NSMutableArray new];
  self.view.backgroundColor = [UIColor grayColor];
  while(self.platformViews.count < 8) {
    [self addNewView];
  }
}

- (void)viewDidLoad {
  [super viewDidLoad];
  dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{
    self.displayLink = [CADisplayLink displayLinkWithTarget:self selector:@selector(updateViews)];
    [self.displayLink addToRunLoop:[NSRunLoop currentRunLoop] forMode:NSRunLoopCommonModes];
    self.displayLink.preferredFrameRateRange =
        CAFrameRateRangeMake(60, 120, 120);
    NSRunLoop *runLoop = [NSRunLoop currentRunLoop];
    while (YES) {
      [runLoop run];
    }
  });
  // Do any additional setup after loading the view.
}

- (void)updateViews {
  dispatch_async(dispatch_get_main_queue(), ^{
    if (self.acc <= 0) {
      return;
    }
    [CATransaction begin];
    CGFloat vel = self.acc;
    UIView *viewToRemove;
    for (UIView *view in self.platformViews) {
      view.frame = CGRectMake(view.frame.origin.x, view.frame.origin.y - vel, view.frame.size.width, view.frame.size.height);
      if (view.frame.origin.y + view.frame.size.height < 0) {
        viewToRemove = view;
      }
    }
    if (viewToRemove) {
      [viewToRemove removeFromSuperview];
      [self.platformViews removeObjectAtIndex:0];
      [self addNewView];
    }
    self.acc -= 1;
    [CATransaction commit];
  });
}

- (UIView *)createPlatformView {
  UITextView *view = [[UITextView alloc] initWithFrame:CGRectMake(ViewX, 0, ViewWidth, ViewHeight)];
  view.text = @"This is a platform view";
  view.backgroundColor = [UIColor redColor];
  return view;
}

- (void)addNewView {
  UIView *newView = [self createPlatformView];
  UIView *lastView = self.platformViews.lastObject;
  CGRect frame = newView.frame;
  if (lastView) {
    frame.origin.y = lastView.frame.origin.y + ViewHeight + Padding;
  } else {
    frame.origin.y = 0;
  }
  newView.frame = frame;
  [self.view addSubview:newView];
  [self.platformViews addObject:newView];
}

- (void)touchesEnded:(NSSet<UITouch *> *)touches withEvent:(UIEvent *)event {
  [super touchesEnded:touches withEvent:event];
  self.acc = 50;
}


@end


```

</details>

**Comment by 0xZOne** [comment]
<img width="1792" alt="截屏2022-12-23 12 31 31" src="https://user-images.githubusercontent.com/26625149/209271805-f4bb458f-f0a3-476e-a049-508b8ac931e8.png">


It seems unreasonable that the `-[CAMetalLayer nextDrawable]` is so time-consuming.

**Comment by cyanglaz** [comment]
> It seems unreasonable that the -[CAMetalLayer nextDrawable] is so time-consuming.

nextDrawable can wait for up to 1 second according to https://developer.apple.com/documentation/quartzcore/cametallayer/2887086-allowsnextdrawabletimeout?language=objc

**Comment by 0xZOne** [comment]
> > It seems unreasonable that the -[CAMetalLayer nextDrawable] is so time-consuming.
> 
> nextDrawable can wait for up to 1 second according to https://developer.apple.com/documentation/quartzcore/cametallayer/2887086-allowsnextdrawabletimeout?language=objc

Yes, but it's not always so time-consuming. E.g., on non-ProMotion devices.  :)

**Comment by cyanglaz** [comment]
Just found out that the maskView is construction is expensive. https://github.com/flutter/engine/blob/main/shell/platform/darwin/ios/framework/Source/FlutterPlatformViews.mm#L435-L439. Removing this line helps with the performance a lot. I'm going on a vacation and will continue looking after the vacation.

If someone can figure out a way to optimize `maskView`'s construction, it could help to reduce the jitter a lot.

**Comment by 0xZOne** [comment]
I'm afraid fixing the performance issue here won't alleviate this issue. 

Instead, the following question seems to be closer to the truth.

https://stackoverflow.com/questions/47451731/metal-uikit-synchronisation-with-presentswithtransaction

>Edit: 9-Dec-2018: Whilst the first method described above does seem to be preferential, it does still result in frequent de-synchronisation if there is a spike in CPU usage on the main thread – which is unavoidable in most situations.
>
>You can tell when this happens as the draw loop becomes starved of drawables. This causes a knock-on effect, which means the drawable for the next frame is delayed also. In the Metal Instruments panel, this results in a series of 'thread blocked waiting for next drawable' warnings.
>
>With the design above, as Metal is blocked waiting for a drawable – so is the main thread. Now touch events become delayed, resulting in a distinctive stuttering pattern for a pan gesture – even though the app is still running theoretically at a full 60fps, the blocking seems to affect the cadence at which touch events are reported – resulting in the judder effect.
>
>A subsequent CPU spike can knock things back into sequence and the app will begin performing as normal.
>
>Edit: 10-Dec-2018: And here's a small example project that demonstrates the issue. Create a new Xcode project copy and paste the contents of the two swift files (add a new file for the metal shader file) and run on device:
>
>https://gist.github.com/tcldr/ee7640ccd97e5d8810af4c34cf960284

**Comment by luckysmg** [comment]
I did some invesigation and debugging.
Add print log like this to know if the function `nextDrawable` will takes much time in `IOSSurfaceMetalSkia.mm`

<img src="https://user-images.githubusercontent.com/49340347/211453461-f7ce619b-e196-4e81-a413-d0fed32fa63e.png" width=500/>

`nextDrawable takes much time` in below table means: **There are a lot of logs printed constantly.**

### Force set the `presentsWithTransaction = NO`

Scene | nextDrawable takes much time
-------- | --------------
Without platformView  |  ✅ 
With platformView but platformView doesn't change  |  ✅ 
With platformView and it will change (PlatformView in ListView and scroll ListView) |  ✅ 

### Force set the `presentsWithTransaction = [[NSThread currentThread] isMainThread]`

Scene | nextDrawable takes much time
-------- | --------------
Without platformView  |  ✅ 
With platformView but platformView doesn't change  |  ❌
With platformView and it will change (PlatformView in ListView and scroll ListView) |  ✅ 

### Force set the `presentsWithTransaction = YES`
Scene | nextDrawable takes much time
-------- | --------------
Without platformView  |  ❌
With platformView but platformView doesn't change  |  ❌
With platformView and it will change (PlatformView in ListView and scroll ListView) |  ✅

**Comment by cyanglaz** [comment]
I removed the nextDrawable call and only let the app show PlatformView, the issue can still be seen. Example engine code without `nextDrawable`: https://github.com/flutter/engine/pull/38751

**Comment by luckysmg** [comment]
Yes...I tested this on your branch and also see jitter....Maybe not related with that....

**Comment by luckysmg** [comment]
Hi @cyanglaz.

I did some detailed debugging today.....and get some conclusions maybe valuable.

1. Without presenting metal contents, if we don't add`CATransaction`.... **The screen is very smooth.**
See patch:https://github.com/flutter/engine/compare/main...luckysmg:engine:platformView_no_present_test

2. Base on the patch above, if I present the metal content (Uncomment `did_submit &= frame->Submit();`), the jitter will reappear again.

3. Base on `2.`  If I set `metalLayer.presentsWithTransaction=false`. **The screen will be smooth.** 
    **But:**
**3.1:** It will have junk randomly because it seems that when `presentsWithTransaction=false` the `nextDrawble` funtion will take much time and will have junk constantly.....
**3.2:** The metal contents doesn't sync with platformView a little bit(because presentsWithTransaction will sync the contents with CoreAnimation)

Seems very confusing.... I'm afraid that I m not very familiar with the mechanism of `CATransaction`, so maybe you could do sth according to this information. O(∩_∩)O

**Comment by b3nni97** [comment]
If it comes to the fact that as soon as a PlatformView is displayed the frame rate is limited, I would prefer an opt-in. 
For example, if a user displays ads, he basically limits the whole app to 80 FPS, which is of course very unfortunate.

**Comment by timtangcoding** [comment]
Apart from the jittering of PlatformView cells on list, does anyone also experience flashes of PlatformView over AppBar / SliverAppBar and SliverPersistentHeader ? Thanks!



https://user-images.githubusercontent.com/16203104/216832152-6ccacee6-1312-4baa-bdd3-cb39efd41fdd.MP4


Using the sample app on top and iPhone 13 Pro, it could be observed that there are flashes over AppBar and status bar. The flashes does not appear when Settings > Accessibility > Motion > Limit Frame Rate option is switched on.

fvm flutter doctor -v
[✓] Flutter (Channel stable, 3.7.0, on macOS 12.5.1 21G83 darwin-arm64, locale en-GB)
    • Flutter version 3.7.0 on channel stable at /Users/timtang/fvm/versions/3.7.0
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b06b8b2710 (13 days ago), 2023-01-23 16:55:55 -0800
    • Engine revision b24591ed32
    • Dart version 2.19.0
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/timtang/Library/Android/sdk
    • Platform android-33, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F100
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] IntelliJ IDEA Community Edition (version 2020.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.74.0)
    • VS Code at /Users/timtang/Documents/worksBase/VSCode/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • iPhone (mobile) • 00008110-00094502348A801E • ios            • iOS 15.5 19F77
    • macOS (desktop) • macos                     • darwin-arm64   • macOS 12.5.1 21G83 darwin-arm64
    • Chrome (web)    • chrome                    • web-javascript • Google Chrome 109.0.5414.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Comment by timtangcoding** [comment]
Using the latest commit from `flutter:main`, the flash issues is greatly improved.
However, it is found that the slivers may scroll up to status bar even if `SafeArea` widget is used.


https://user-images.githubusercontent.com/16203104/216857222-18ff4fb4-9fe5-4ed3-91f0-b9b61b69b899.MP4

fvm flutter doctor -v
[✓] Flutter (Channel main, 3.8.0-4.0.pre.25, on macOS 12.5.1 21G83 darwin-arm64, locale en-GB)
    • Flutter version 3.8.0-4.0.pre.25 on channel main at /Users/timtang/fvm/versions/3.7.0
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b8f5394a5c (10 hours ago), 2023-02-04 23:06:19 -0800
    • Engine revision 2a104cdfcd
    • Dart version 3.0.0 (build 3.0.0-204.0.dev)
    • DevTools version 2.21.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/timtang/Library/Android/sdk
    • Platform android-33, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F100
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] IntelliJ IDEA Community Edition (version 2020.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.74.0)
    • VS Code at /Users/timtang/Documents/worksBase/VSCode/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • iPhone (mobile) • 00008110-00094502348A801E • ios            • iOS 15.5 19F77
    • macOS (desktop) • macos                     • darwin-arm64   • macOS 12.5.1 21G83 darwin-arm64
    • Chrome (web)    • chrome                    • web-javascript • Google Chrome 109.0.5414.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Comment by 0xZOne** [comment]
@timtangcoding  I have already filed an issue (https://github.com/flutter/flutter/issues/119485).

**Comment by timtangcoding** [comment]
> @timtangcoding  I have already filed an issue (https://github.com/flutter/flutter/issues/119485).

Great, let's follow up the issues there.
