### ISSUE TITLE
API docs need better headers

### ISSUE THREAD

**Issue by Sfshaza** [flutter/flutter#11662]
It seems very odd to me that the Flutter API docs don't have the class/package/etc name in BOLD at the top of the page. There's only a breadcrumb trail or or the URL at the top of the page and it's not visually obvious. I'd expect to see something more like what you'd see on the Dart API docs (pics included).

## Dart
![screen shot 2017-08-17 at 10 40 33 am](https://user-images.githubusercontent.com/6293442/29425558-8b26fb4e-8338-11e7-97b3-2ebd74b1d41f.png)

## Flutter
![screen shot 2017-08-17 at 10 41 17 am](https://user-images.githubusercontent.com/6293442/29425590-aad79278-8338-11e7-8ed6-8a6b95d1dd42.png)

**Comment by Hixie** [comment]
Dupe of https://github.com/dart-lang/dartdoc/issues/1441.

**Comment by sethladd** [comment]
Thanks for the report!
