### ISSUE TITLE
[path_provider] cause an error related to "kotlin-stdlib-jdk" when building the APK

### ISSUE THREAD

**Issue by Nidal-Bakir** [flutter/flutter#116659]
Flutter version: `3.3.8`
OS: `Ubuntu 20.04.5 LTS x86_64`

**NOTE:** Removing the **path_provider** from **pubspec.yaml** will resolve the issue and the build will complete normally. 

## Steps to Reproduce

1. Create a new flutter project
2. In **app/build.gradle** change **jdk7** to **jdk8** 
```
dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8:$kotlin_version"
}
```
3. Add **path_provider** to **pubspec.yaml** file 
4. Execute `flutter pub upgrade`
5. Execute `flutter clean` (make sure to run this before any flutter build)
6. Execute `flutter build apk --split-per-abi`

### flutter pub upgrade
<details>
<summary>The output of flutter pub upgrade</summary>

> Resolving dependencies...
>   async 2.9.0 (2.10.0 available)
>   boolean_selector 2.1.0 (2.1.1 available)
>   characters 1.2.1
>   clock 1.1.1
>   collection 1.16.0 (1.17.0 available)
>   cupertino_icons 1.0.5
>   fake_async 1.3.1
>   ffi 2.0.1
>   file 6.1.4
>   flutter 0.0.0 from sdk flutter
>   flutter_lints 2.0.1
>   flutter_test 0.0.0 from sdk flutter
>   lints 2.0.1
>   matcher 0.12.12 (0.12.13 available)
>   material_color_utilities 0.1.5 (0.2.0 available)
>   meta 1.8.0
>   path 1.8.2 (1.8.3 available)
>   path_provider 2.0.11
>   path_provider_android 2.0.22
>   path_provider_ios 2.0.11
>   path_provider_linux 2.1.7
>   path_provider_macos 2.0.6
>   path_provider_platform_interface 2.0.5
>   path_provider_windows 2.1.3
>   platform 3.1.0
>   plugin_platform_interface 2.1.3
>   process 4.2.4
>   sky_engine 0.0.99 from sdk flutter
>   source_span 1.9.0 (1.9.1 available)
>   stack_trace 1.10.0 (1.11.0 available)
>   stream_channel 2.1.0 (2.1.1 available)
>   string_scanner 1.1.1 (1.2.0 available)
>   term_glyph 1.2.1
>   test_api 0.4.12 (0.4.16 available)
>   vector_math 2.1.2 (2.1.4 available)
>   win32 3.1.2
>   xdg_directories 0.2.0+2
> No dependencies changed.
> 12 packages have newer versions incompatible with dependency constraints.
> Try `flutter pub outdated` for more information.

</details>

### My build.gradle

<details>
<summary>build.gradle</summary>

```
buildscript {
    ext.kotlin_version = '1.6.10'
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:7.1.2'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

</details>
<details>
<summary>app/build.gradle</summary>

```
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

android {
    compileSdkVersion 33

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.doors.app"
        minSdkVersion 21
        targetSdkVersion 33
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8:$kotlin_version"
}

```

</details>

### The classpath error 

 ```
Running "flutter pub get" in hello_proj...                         894ms

💪 Building with sound null safety 💪

w: Runtime JAR files in the classpath should have the same version. These files were found in the classpath:
    /home/nidal/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk8/1.6.10/e80fe6ac3c3573a80305f5ec43f86b829e8ab53d/kotlin-stdlib-jdk8-1.6.10.jar (version 1.6)
    /home/nidal/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk7/1.6.10/e1c380673654a089c4f0c9f83d0ddfdc1efdb498/kotlin-stdlib-jdk7-1.6.10.jar (version 1.6)
    /home/nidal/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.7.10/d2abf9e77736acc4450dc4a3f707fa2c10f5099d/kotlin-stdlib-1.7.10.jar (version 1.7)
    /home/nidal/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-common/1.7.10/bac80c520d0a9e3f3673bc2658c6ed02ef45a76a/kotlin-stdlib-common-1.7.10.jar (version 1.7)
w: Some runtime JAR files in the classpath have an incompatible version. Consider removing them from the classpath
e: /home/nidal/.gradle/caches/modules-2/files-2.1/androidx.annotation/annotation/1.5.0/857678d6b4ca7b28571ef7935c668bdb57e15027/annotation-1.5.0.jar!/META-INF/annotation.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.7.1, expected version is 1.5.1.
e: /home/nidal/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.7.10/d2abf9e77736acc4450dc4a3f707fa2c10f5099d/kotlin-stdlib-1.7.10.jar!/META-INF/kotlin-stdlib.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.7.1, expected version is 1.5.1.
e: /home/nidal/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-common/1.7.10/bac80c520d0a9e3f3673bc2658c6ed02ef45a76a/kotlin-stdlib-common-1.7.10.jar!/META-INF/kotlin-stdlib-common.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.7.1, expected version is 1.5.1.
w: Runtime JAR files in the classpath should have the same version. These files were found in the classpath:
    /home/nidal/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk8/1.6.10/e80fe6ac3c3573a80305f5ec43f86b829e8ab53d/kotlin-stdlib-jdk8-1.6.10.jar (version 1.6)
    /home/nidal/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk7/1.6.10/e1c380673654a089c4f0c9f83d0ddfdc1efdb498/kotlin-stdlib-jdk7-1.6.10.jar (version 1.6)
    /home/nidal/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.7.10/d2abf9e77736acc4450dc4a3f707fa2c10f5099d/kotlin-stdlib-1.7.10.jar (version 1.7)
    /home/nidal/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-common/1.7.10/bac80c520d0a9e3f3673bc2658c6ed02ef45a76a/kotlin-stdlib-common-1.7.10.jar (version 1.7)
w: Some runtime JAR files in the classpath have an incompatible version. Consider removing them from the classpath
Running Gradle task 'assembleRelease'...                           88.8s
✓  Built build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk (5.5MB).
```

**Comment by Nidal-Bakir** [comment]
@exaby73 

In your **app/build.gradle** change **jdk7** to Java **jdk8**

```
dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8:$kotlin_version"
}
```
So it will not complain about `kotlin-stdlib-jdk8-1.5.30.jar(version 1.5)`

The conflict will be between:
`kotlin-stdlib-jdk7-1.6.10.jar (version 1.6)` and `kotlin-stdlib-common-1.7.10.jar (version 1.7)
`

**Comment by stuartmorgan** [comment]
/cc @reidbaker 

The issue here is that we updated a dependency (via Dependabot) to a version that turns out to want some newer versions of things than we have in the template. We should
- update the template (or if not, consider downgrading the dependency in `path_provider`, but I would prefer not to do that), and
- figure out how to better test for this in flutter/plugins. E.g., why doesn't `build_all_plugins` fail in the flutter/plugins CI, since it's doing something close to the repro steps here? Is it due to edits the tooling makes to the generated app?

**Comment by Nidal-Bakir** [comment]
@stuartmorgan 
Just a side note...

If you try to rebuild the app without executing the `flutter clean` command.
The build will run without any errors!
I do not know why but when you run `flutter clean` and then `flutter build` the error will appear.

that's why I made it clear that we need to run `flutter clean` before any `flutter build `

> 4. Execute flutter clean (make sure to run this before any flutter build)

**Comment by Nidal-Bakir** [comment]
And as for now, is there any workaround? 

Thanks.

**Comment by MrMineToons** [comment]
Hello @Nidal-Bakir 

Try this (see my comment): https://github.com/flutter/flutter/issues/115477#issuecomment-1346678524

**Comment by Nidal-Bakir** [comment]
@MrMineToons 

Thanks, its working now!

**Closing based on the above comment.**

**Comment by exaby73** [comment]
@stuartmorgan I am reopening this issue based on https://github.com/flutter/flutter/issues/116659#issuecomment-1343352828. If you wish to close this issue, perhaps your proposals could be extracted to a new issue
