### ISSUE TITLE
[CP] [Impeller] Use DrawPath instead of Rect geometry when the paint style is stroke

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#116783]
### issue_link

https://github.com/gskinnerTeam/flutter-wonderous-app/issues/53

### Commit Hash

https://github.com/flutter/engine/commit/71928b6a42e68d1f12153e64cc3e03081c2fae8f

### Target

beta

### pr_link

https://github.com/flutter/engine/pull/38153

### Impacted Users

All users of Impeller

### Impact Description

Stroked rectangles rendered as filled.

### Workaround

There is no workaround

### Risk

low

### Test Coverage

yes

### Validation Steps

Run the Wonderous app and check that the box in the linked issue is rendered correctly.

**Comment by itsjustkevin** [comment]
@chinmaygarde could you take a look at this cherry-pick?

**Comment by chinmaygarde** [comment]
lgtm
