### ISSUE TITLE
Compile-time guarantee of an InheritedWidget presence in the tree

### ISSUE THREAD

**Issue by alexeyinkin** [flutter/flutter#116768]
## Use Case

If one uses [Provider](https://pub.dev/packages/provider) or any other way to call `dependOnInheritedWidgetOfExactType()`, there is no guarantee that such widget is in the tree. This leads to runtime errors.

## Proposal

There should be a tool, or a lint, or anything else to turn that into compile-time issues. Such a tool should trace the static use of widgets.

For instance, this code is correct:

```dart
class A extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Provider<Foo>.value(
      value: foo,
      child: B(),
    ),
  }
}

class B extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Consumer<Foo>(
      builder: (_, foo, child) => Text('$foo'),
    );
  }
}
```

And if the widget `B` is created in at least one location that cannot be traced up to a `Provider<Foo>`, the tool should flag those locations.

This may be hard to derive such requirement from `Consumer<Foo>` alone because it may be not clear if it calls `dependOnInheritedWidgetOfExactType()` in its code. So maybe we can introduce some annotation on widget classes that would signal such requirement:

```dart
@DependOnInheritedWidgetOfExactType(Provider<Foo>)
class B extends StatelessWidget { ... }
```

This tool would not be suitable for packages because they are not the end-users of their widgets, but it can be used on standalone apps.

Such a tool also cannot trace widgets created in:
- Conditions.
- Outside of methods called directly from `build()` method.

But even with those limitations it can be helpful.

**Comment by goderbauer** [comment]
I don't think this is actually feasible in the general case. InheritedWidgets could be inserted into the tree conditionally, so you'd have to evaluate the condition in order to figure out whether a widget is present. And the some conditions cannot be evaluated at compile time.
