### ISSUE TITLE
[webview_flutter] twitch oauth login fail through webview with error: your browser is not currently supported

### ISSUE THREAD

**Issue by herehere** [flutter/flutter#116770]
## Steps to Reproduce

1. using webview to pass info to twitch OAuth
2. on OAuth2 sending back info will get error: your browser is not currently supported.

**Expected results:** 
like safari or chrome apps on the device, they work well.

**Actual results:** 
Your browser is not currently supported. Please use an recommended browser.

<details>
<summary>
The following code works fine before 07/30/2022 but recently has this issue. we change webview_flutter to 3.0.4 still the same
sample code:

    WebView(
        onWebViewCreated: (controller) {
          if (clearCache) {
            controller.clearCache();
            CookieManager().clearCookies();
          }
        },
        userAgent: userAgent,
        initialUrl: authUrl,
        javascriptMode: JavascriptMode.unrestricted,
        navigationDelegate: (NavigationRequest request) {
          String url = request.url;
          if (url.startsWith(redirectUri)) {
            var returnedData = _getQueryParams(url);
            returnedData[CLIENT_ID_KEY] = clientID;
            returnedData[REDIRECT_URI_KEY] = redirectUri;
            returnedData[STATE_KEY] = state;

            if (clientSecret != null) {
              returnedData[CLIENT_SECRET_KEY] = clientSecret;
            }

            onDone(returnedData);
          }

          return NavigationDecision.navigate;
        });

</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

$ flutter doctor -v
[✓] Flutter (Channel unknown, 2.5.3, on macOS 12.1 21C52 darwin-x64, locale zh-Hant-TW)
    • Flutter version 2.5.3 at /Users/3a20/Library/Developer/flutter
    • Upstream repository unknown
    • Framework revision 18116933e7 (1 year, 2 months ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/3a20/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.2.1, Build version 13C100
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.72.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.52.0

</details>

![20221209_174947_2](https://user-images.githubusercontent.com/10718801/206677841-1a2e5436-0cd0-4fde-915a-8a3edf0f37ef.jpg)

**Comment by stuartmorgan** [comment]
If a site chooses not to support the system webview for a given platform, there's nothing the plugin can do about that; it's entirely up to the site's developers. You would need to report this issue to Twitch.
