### ISSUE TITLE
go_router: bad state no element

### ISSUE THREAD

**Issue by Gorter-dev** [flutter/flutter#116730]
Our app breaks using the latest version of go_router (5.2.2). When using 5.2.1 it works just fine.

I have boiled it down to: 
https://github.com/flutter/packages/commit/250adea8b209b42cd6cf4a5515ac10a9da19ca08

Line 102-105

```    
if (configuration.matches.last is ImperativeRouteMatch) {
      configuration =
          (configuration.matches.last as ImperativeRouteMatch).matches;
    }
```

In our specific case, in the first frames. configuration.matches is empty. Therefore it returns a bad state no element. I can locally resolve this by adding `configuration.matches.isNotEmpty` before the check. But I don't really know (yet) if that breaks other stuff or what the intended purporse is.

Is this something we are doing wrong when initializing go_router, a breaking API change or a oversight?

Greetz

**Comment by Gorter-dev** [comment]
See https://github.com/flutter/flutter/issues/116729 for an example (looks like every example would break) with code

**Comment by Junddao** [comment]
I also ran into the same problem.  @chunhtai  need to solve this as soon as possible. 
( I think this is critical bugs for developer to use go router.)

5.2.1 version also have pop problem...   
Can I use this package for my project??...

**Comment by chunhtai** [comment]
closing this as duplicate.
