### ISSUE TITLE
Generate Provenance For Windows in BCID Script After Available for Windows Machines

### ISSUE THREAD

**Issue by sealesj** [flutter/flutter#116749]
The provenance generation on Windows machines for BCID compliance is not yet ready, but instead of creating a failure in that scenario, generating provenance on Windows has been paused. After Windows provenance generation is available, we will resume generating on all platforms.

**Comment by sealesj** [comment]
Windows provenance generation is paused with change https://flutter-review.git.corp.google.com/c/recipes/+/37101

**Comment by godofredoc** [comment]
Fix: https://flutter-review.googlesource.com/c/recipes/+/41320
