### ISSUE TITLE
Container border color is not theme flexible.

### ISSUE THREAD

**Issue by rubywai** [flutter/flutter#116772]
Container border color is always black. It should be change from theme.

**Comment by kaangms** [comment]
> Container border color is always black. It should be change from theme.

@rubywai  Could you give a little more information on the issue?

**Comment by darshankawar** [comment]
@rubywai 
Please provide `flutter doctor -v` and complete minimal reproducible code sample that shows the current behavior you are reporting and what's the expected behavior you are looking for as well.
