### ISSUE TITLE
[go_router] configuration.matches.last when matches.length == 0

### ISSUE THREAD

**Issue by changweihua** [flutter/flutter#116701]
The same code is ok on 5.2.1 ,but it failed on 5.2.2.
It shows some things error 

 /// for use by the Router architecture as part of the RouteInformationParser
  @override
  RouteInformation restoreRouteInformation(RouteMatchList configuration) {
    if (configuration.matches.last is ImperativeRouteMatch) {
      configuration =
          (configuration.matches.last as ImperativeRouteMatch).matches;
    }
    return RouteInformation(
      location: configuration.uri.toString(),
      state: configuration.extra,
    );
  }

**Comment by exaby73** [comment]
Hello @changweihua. Thank you for filing this issue. Can you please provide the following information?

- A [complete and minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). Ideally, a single `main.dart` file that can be run directly.
- The output of `flutter doctor -v`
- The output of `flutter run -v`

Please provide the information in the form of text. See how to make collapsible sections with Markdown [here](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-collapsed-sections).

**Comment by changweihua** [comment]
I'm sorry to reply so late, but I haven't read the news these two days. I have tried the lastest version 5.2.4, it works fine.

**Comment by exaby73** [comment]
Okay thank you for the clarification. Closing this issue it's working as expected
