### ISSUE TITLE
Section assessors does not exists - First step is impossible to make

### ISSUE THREAD

**Issue by rudarabello** [flutter/flutter#116775]
[9. Bonus step: Practice what you've learned](https://firebase.google.com/codelabs/firebase-get-to-know-flutter#8)
Record an attendee's RSVP status

Right now, your app only allows people to chat when they're interested in the event. Also, the only way that you know whether someone's coming is when they say so in the chat.

In this step, you get organized and let people know how many people are coming. You add a couple of capabilities to the app state. The first is the ability for a logged-in user to nominate whether they're attending. The second is a counter of how many people are attending.

    In the lib/main.dart file, add the following lines to the **accessors** section so that the UI code can interact with this state:

**Comment by domesticmouse** [comment]
@miquelbeltran want to take a look at this one?

**Comment by miquelbeltran** [comment]
Yes, I encountered that issue as well.

Where it says:

> In the `lib/main.dart` file, add the following lines to the accessors section so that the UI code can interact with this state:

Should be

> In the `lib/main.dart` file, add the following lines to the `ApplicationState` so that the UI code can interact with this state:

Once you add that code snippet to the `ApplicationState`, you should be able to continue.

**Comment by rudarabello** [comment]
Thanks guys

**Comment by domesticmouse** [comment]
@miquelbeltran is this issue safe to close? I think we have landed this refactoring?

**Comment by miquelbeltran** [comment]
@domesticmouse yes, the issue can be closed now, the codelab code and document are up-to-date.
