### ISSUE TITLE
Rotate issue on iOS only

### ISSUE THREAD

**Issue by SwiftyFlow** [flutter/flutter#116711]
I have an app that is  by design always limited to `DeviceOrientation.portraitUp`. We don't allow any other orientations except for one screen, which is used as PDF or Image viewer, I want to allow ONLY this view to rotate freely. It works fine on Android but not on iOS.

I have added this in initState:
`      SystemChrome.setPreferredOrientations([DeviceOrientation.portraitUp, DeviceOrientation.landscapeRight, DeviceOrientation.landscapeLeft]);
`

in that case, all good on Android, but no effect on iOS it's like it has only `DeviceOrientation.portraitUp`

if I do:
```
if (Platform.isIOS) {
      SystemChrome.setPreferredOrientations([DeviceOrientation.landscapeRight, DeviceOrientation.landscapeLeft]);
    }
```

That allows landscape rotations but I cannot do portrait...

Any ideas?

Not mentioned but I do do:
```
void dispose() {
    SystemChrome.setPreferredOrientations([DeviceOrientation.portraitUp]);
    super.dispose();
  }
```

**Comment by exaby73** [comment]
Hello @SwiftyFlow. Thank you for filing this issue. Can you please provide the following information?

- A [complete and minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). Ideally, a single `main.dart` file that can be run directly.
- The output of `flutter doctor -v`
- The output of `flutter run -v`

Please provide the information in the form of text. See how to make collapsible sections with Markdown [here](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-collapsed-sections).

**Comment by SwiftyFlow** [comment]
flutter doctor -v 
[✓] Flutter (Channel master, 3.6.0-12.0.pre, on macOS 12.6 21G115 darwin-x64, locale en-AU)
    • Flutter version 3.6.0-12.0.pre on channel master at /Users/flowpottevin/Desktop/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 02de12947a (8 days ago), 2022-11-29 22:57:31 -0500
    • Engine revision d5690468da
    • Dart version 2.19.0 (build 2.19.0-443.0.dev)
    • DevTools version 2.20.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc1)
    • Android SDK at /Users/flowpottevin/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code (version 1.74.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.54.0

[✓] Connected device (2 available)
    • iPhone 14 Pro (mobile) • 3E76B56C-2A9E-4FD3-82AF-865D9EBB286A • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-1 (simulator)
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 108.0.5359.94

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Comment by SwiftyFlow** [comment]
<details><summary>CLICK ME</summary>
<p>
flutter run -v:
Not allowed to give private company data
</p>
</details>

**Comment by exaby73** [comment]
Please provide a code sample as mentioned in https://github.com/flutter/flutter/issues/116711#issuecomment-1342633418

**Comment by exaby73** [comment]
@SwiftyFlow The code you provided is long and complex. Please try to simplify the example you are providing to have the minimal code to reproduce this issue

**Comment by SwiftyFlow** [comment]
If I don't give the full logic how can we spot the error?

**Comment by SwiftyFlow** [comment]
```
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:google_fonts/google_fonts.dart';

void main() {
  WidgetsFlutterBinding.ensureInitialized();

  SystemChrome.setPreferredOrientations([DeviceOrientation.portraitUp]).then((_) {
    runApp(const MyApp());
  });
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        appBarTheme: const AppBarTheme(systemOverlayStyle: SystemUiOverlayStyle.light),
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
      routes: {
        SecondScreen.routeName: (ctx) => const SecondScreen(),
      },
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: Text(widget.title),
        ),
        body: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              const Padding(
                padding: EdgeInsets.all(20),
                child: Text(
                  'This screen should not rotate. Notice some kind of glitch when coming back from second screen in landscape. And also if coming back in portrait but then tries to rotate in landscape here.',
                  textAlign: TextAlign.center,
                ),
              ),
              ElevatedButton(
                onPressed: () {
                  Navigator.of(context).pushNamed(SecondScreen.routeName);
                },
                child: const Text('Go to second screen'),
              )
            ],
          ),
        ));
  }
}

class SecondScreen extends StatefulWidget {
  static const routeName = '/second-screen';

  const SecondScreen({Key? key}) : super(key: key);

  @override
  State<SecondScreen> createState() => _SecondScreenState();
}

class _SecondScreenState extends State<SecondScreen> {
  @override
  void initState() {
    super.initState();

    SystemChrome.setPreferredOrientations([DeviceOrientation.portraitUp, DeviceOrientation.landscapeRight, DeviceOrientation.landscapeLeft]);
  }

  @override
  void dispose() {
    SystemChrome.setPreferredOrientations([DeviceOrientation.portraitUp]);

    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Second Screen'),
      ),
      body: const Center(
        child: Padding(
          padding: EdgeInsets.symmetric(horizontal: 20),
          child: Text(
            'Only this screen should be able to rotate but it only does the very first time it shows. Never after...\n\nOnly fix: fully restart the app.',
            textAlign: TextAlign.center,
          ),
        ),
      ),
    );
  }
}
```

**Comment by SwiftyFlow** [comment]
Colours removed that's all I can do

**Comment by exaby73** [comment]
## Triage report

I can reproduce this issue on `Master (3.7.0-5.0.pre.26)` on iOS only

<details>
<summary>Code Sample (Same as OP)</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() {
  WidgetsFlutterBinding.ensureInitialized();

  SystemChrome.setPreferredOrientations([DeviceOrientation.portraitUp]).then((_) {
    runApp(const MyApp());
  });
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        appBarTheme: const AppBarTheme(systemOverlayStyle: SystemUiOverlayStyle.light),
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
      routes: {
        SecondScreen.routeName: (ctx) => const SecondScreen(),
      },
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: Text(widget.title),
        ),
        body: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              const Padding(
                padding: EdgeInsets.all(20),
                child: Text(
                  'This screen should not rotate. Notice some kind of glitch when coming back from second screen in landscape. And also if coming back in portrait but then tries to rotate in landscape here.',
                  textAlign: TextAlign.center,
                ),
              ),
              ElevatedButton(
                onPressed: () {
                  Navigator.of(context).pushNamed(SecondScreen.routeName);
                },
                child: const Text('Go to second screen'),
              )
            ],
          ),
        ));
  }
}

class SecondScreen extends StatefulWidget {
  static const routeName = '/second-screen';

  const SecondScreen({Key? key}) : super(key: key);

  @override
  State<SecondScreen> createState() => _SecondScreenState();
}

class _SecondScreenState extends State<SecondScreen> {
  @override
  void initState() {
    super.initState();

    SystemChrome.setPreferredOrientations([DeviceOrientation.portraitUp, DeviceOrientation.landscapeRight, DeviceOrientation.landscapeLeft]);
  }

  @override
  void dispose() {
    SystemChrome.setPreferredOrientations([DeviceOrientation.portraitUp]);

    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Second Screen'),
      ),
      body: const Center(
        child: Padding(
          padding: EdgeInsets.symmetric(horizontal: 20),
          child: Text(
            'Only this screen should be able to rotate but it only does the very first time it shows. Never after...\n\nOnly fix: fully restart the app.',
            textAlign: TextAlign.center,
          ),
        ),
      ),
    );
  }
}
```

</details>

**Comment by jmagman** [comment]
Related to flutter/engine#36874

**Comment by SwiftyFlow** [comment]
I don't really get what I need to do...

**Comment by jmagman** [comment]
@SwiftyFlow thank you for the detailed report, you made it easy to track down!  The fix has merged at https://github.com/flutter/engine/pull/38230, and you can follow the instructions at https://github.com/flutter/flutter/wiki/Where's-my-Commit%3F#finding-the-framework-commit-that-contains-engine-commit-x to monitor when it will be available in Flutter.  If you validate the fix, let us know here, otherwise there's nothing more for you to do. 🙂

**Comment by BetterB0y** [comment]
On Flutter 3.7.3 still there is an issue with this
