### ISSUE TITLE
[go_router] hide/unhide navigator

### ISSUE THREAD

**Issue by okaforcj** [flutter/flutter#116764]
I noticed this https://github.com/flutter/flutter/issues/99107#issuecomment-1105789364, the corresponding shellrouter has been finalised. I was wondering if/when we would get a similar rootNavigator api to encompass the enter full dialog mode while maintaining the use of gorouter @chunhtai 

## Use case
Hide navigator for some screens using a shared layout

## Proposal
Add a similar rootNavigator api for gorouter

**Comment by darshankawar** [comment]
@okaforcj 
Can you provide `flutter doctor -v` and complete minimal code sample that shows current behavior / use case you mentioned ?

**Comment by okaforcj** [comment]
> @okaforcj
> Can you provide `flutter doctor -v` and complete minimal code sample that shows current behavior / use case you mentioned ?

if you look at the linked issue, it describes the exact issue, there is no code sample as this is a feature request. It was previously created by one of the flutter collaborators and was awaiting the new shellroute api, but was never picked back up. please let me know if you need further information/clarification

**Comment by chunhtai** [comment]
if you are adding route imperatively you can still use Navigator.of(rootNavigator: true). If you are using `GoRoute` to define the route, you can use parentNavigatorKey https://pub.dev/documentation/go_router/latest/go_router/GoRoute/parentNavigatorKey.html to specify which navigator this GoRoute should be placed on. Does that solve your use case?

**Comment by okaforcj** [comment]
@chunhtai thats precisely what i needed, apologies for creating a redundant issue. Thanks for the good work you're doing
