### ISSUE TITLE
`NavigationBar` new ripple effect is mis-aligned when using non-default `NavigationDestinationLabelBehavior`

### ISSUE THREAD

**Issue by TahaTesser** [flutter/flutter#116751]
Noticed this issue randomly today. 

code sample: https://master-api.flutter.dev/flutter/material/NavigationBar-class.html

https://user-images.githubusercontent.com/48603081/206585346-8e4de991-61a9-42b4-84c2-300f40d5343a.mov

TODO:

Add non-default `NavigationDestinationLabelBehavior` tests for ink ripple with the fix.

**Comment by TahaTesser** [comment]
`NavigationRail` new ripple doesn't have this issue as it addressed all types of destination behaviors.

**Comment by TahaTesser** [comment]
cc: @HansMuller

**Comment by HansMuller** [comment]
I guess this got past us in https://github.com/flutter/flutter/pull/115499.  Thanks in advance for the fix and especially for the additional regression tests.
