### ISSUE TITLE
Restore the flutter_reactive_ble customer test after the Dart 3 roll completes

### ISSUE THREAD

**Issue by jason-simmons** [flutter/flutter#116748]
An engine roll based on a Dart 3 SDK is in progress (https://github.com/flutter/flutter/pull/116635)

The flutter_reactive_ble customer test was disabled because it relies on packages that are not compatible with Dart 3.

An update to the customer test is pending (https://github.com/PhilipsHue/flutter_reactive_ble/pull/648).  When this lands, the test should be re-enabled.

**Comment by zanderso** [comment]
@jason-simmons Can the test be re-enabled?
