### ISSUE TITLE
Can flutter team add support for Java version 11 in Android

### ISSUE THREAD

**Issue by Ghazanfarrajpoot** [flutter/flutter#116773]
We would like to use java 11 by default support

**Comment by darshankawar** [comment]
@Ghazanfarrajpoot 
Currently you can add java 11 as below:

<img width="479" alt="Screenshot 2022-12-09 at 6 38 14 PM" src="https://user-images.githubusercontent.com/67046386/206709489-77e9116a-5215-4b24-87a1-734ad3ca73a6.png">

As far as default support is concerned, I am not sure if that is feasible currently but you can use above settings and see if it helps in your case.

**Comment by Ghazanfarrajpoot** [comment]
this doesn't seems to be a reliable solution, please flutter team make use of Java version >1.8 like java 11 or java 14 so we could benefit from it, Suggestion

**Comment by christopherfujino** [comment]
> this doesn't seems to be a reliable solution, please flutter team make use of Java version >1.8 like java 11 or java 14 so we could benefit from it, Suggestion

Can you clarify why this is not a reliable solution?

**Comment by Ghazanfarrajpoot** [comment]
Java 1.8 is very old and lack many new features and performance improvements available in say java 14 or 11 etc

**Comment by reidbaker** [comment]
I believe @christopherfujino was asking why his solution to letting you enable java 11 did not work.
