### ISSUE TITLE
Make flutter web better using Impeller Engine for graphics

### ISSUE THREAD

**Issue by Ghazanfarrajpoot** [flutter/flutter#116774]
Is it possible to use Impeller engine on Flutter web. Currently the state of flutter web is very bad and performance is very poor for production web apps.

**Comment by darshankawar** [comment]
@Ghazanfarrajpoot 
Currently impeller is only available for iOS (preview) and Android support is under development, so support for web may not be available until it becomes stable. See this document for your reference: https://github.com/flutter/flutter/wiki/Impeller#availability

Closing for now.

**Comment by Ghazanfarrajpoot** [comment]
Thanks.
