### ISSUE TITLE
Dart implementation for Google Maps Routes API

### ISSUE THREAD

**Issue by spjass** [flutter/flutter#116720]
## Use case

Developer should be able to use new Google Maps Routes API for fetching directions between two or more geolocations. (computeRoutes & computeRouteMatrixes). 

## Proposal

This should be a Dart package, since there is really no need for any Flutter dependencies for the implementation.

**Comment by exaby73** [comment]
Hello @spjass. Looks like there is a community package that does this for web https://pub.dev/packages/google_maps. If you are asking for a dart only implementation, I think the better place for such a proposal is the dart repo (https://github.com/dart-lang/sdk). Closing as this has nothing to do with Flutter. If you disagree, please comment with your reasoning and I can reopen the issue. Thank you
