### ISSUE TITLE
flutter_test from sdk , flutter_localizations from sdk and flutter from sdk all depends on collection 1.16.0, need to upgrade

### ISSUE THREAD

**Issue by Mae623** [flutter/flutter#116755]
because flutter_test , flutter_localizations and flutter from sdk all depends on collection 1.16.0, so I can't upgrade analyzer to 5.3.1 , that result in I can use build_runner commonly.

When I do ' flutter pub run build_runner build' , there is the error as below:

```
Failed to build build_runner:build_runner:../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/analyzer-5.3.0/lib/src/dart/ast/ast.dart:8153:48: Error: The method 'elementAtOrNull' isn't defined for the class 'NodeListImpl<TypeAnnotationImpl>'.
 - 'NodeListImpl' is from 'package:analyzer/src/dart/ast/ast.dart' ('../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/analyzer-5.3.0/lib/src/dart/ast/ast.dart').
 - 'TypeAnnotationImpl' is from 'package:analyzer/src/dart/ast/ast.dart' ('../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/analyzer-5.3.0/lib/src/dart/ast/ast.dart').
Try correcting the name to the name of an existing method, or defining a method named 'elementAtOrNull'.
    var elementType = typeArguments?.arguments.elementAtOrNull(0)?.typeOrThrow;
                                               ^^^^^^^^^^^^^^^
```

I found this information in analyzer CHANGELOG.md:

> ## 5.3.1
> --
> 2 | * Require `collection: ^1.17.0` because we use `elementAtOrNull`.

But If I want to upgrade analyzer from 5.3.0 to 5.3.1 , I came across a conflict as below:
`Because every version of flutter_test from sdk depends on collection 1.16.0 and analyzer >=5.3.1 depends on collection ^1.17.0, flutter_test from sdk is incompatible with analyzer >=5.3.1.
So, because zilvbang_flutter depends on both analyzer ^5.3.1 and flutter_test from sdk, version solving failed.
pub get failed (1; So, because zilvbang_flutter depends on both analyzer ^5.3.1 and flutter_test from sdk, version solving failed.)`

I try to remove "  flutter_test:    sdk: flutter" in pubspec.yaml , then I found the flutter_localizations from sdk and flutter from sdk also depends on collection 1.16.0.
Please upgrade their dependencies as soon as possible, Thank you very much!

 `flutter doctor -v`
[✓] Flutter (Channel stable, 3.3.9, on macOS 13.0.1 22A400 darwin-arm, locale
    zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.73.1)
[✓] Connected device (3 available)

**Comment by darshankawar** [comment]
This seems to be happening on stable:

```
Running "flutter pub get" in test_app...                        
Because every version of flutter_test from sdk depends on collection 1.16.0 and test_app depends on collection ^1.17.0, flutter_test from sdk is forbidden.
So, because test_app depends on flutter_test from sdk, version solving failed.
pub get failed (1; So, because test_app depends on flutter_test from sdk, version solving failed.)
Process finished with exit code 1

```
But seems to be working on latest master. So can you switch to it and see if it works at your end ?

**Comment by Mae623** [comment]
> This seems to be happening on stable:
> 
> ```
> Running "flutter pub get" in test_app...                        
> Because every version of flutter_test from sdk depends on collection 1.16.0 and test_app depends on collection ^1.17.0, flutter_test from sdk is forbidden.
> So, because test_app depends on flutter_test from sdk, version solving failed.
> pub get failed (1; So, because test_app depends on flutter_test from sdk, version solving failed.)
> Process finished with exit code 1
> ```
> 
> But seems to be working on latest master. So can you switch to it and see if it works at your end ?

I solve this question after switching to master, thank you very much~

**Comment by aytunch** [comment]
@darshankawar we can not use the master branch in our company. When can we expect this to land to stable? Thanks
