### ISSUE TITLE
Keyboard goes white when obscureText = true on TextField Flutter iPhone 14pro issue (release mode)

### ISSUE THREAD

**Issue by bassamfouad-10p** [flutter/flutter#116777]
I am facing an issue when I set obscureText = true on TextField. Keyboard only on iPhone 14 devices becomes white. I am on stable channel.

**Comment by danagbemava-nc** [comment]
Hi @bassamfouad-10p, does this issue happen on only physical devices, or does this reproduce on the simulators as well? 

Please also provide a complete minimal reproducible code sample without any third-party packages/plugins so that we can investigate this. Please also provide the output of `flutter doctor -v`. 

Thank you

**Comment by bassamfouad-10p** [comment]
@danagbemava-nc Hi here is my doctor output

 Flutter (Channel stable, 3.3.9, on macOS 12.4 21F79 darwin-x64, locale en-PK)
    • Flutter version 3.3.9 on channel stable at /Users/bassamfouad/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b8f7f1f986 (3 weeks ago), 2022-11-23 06:43:51 +0900
    • Engine revision 8f2221fbef
    • Dart version 2.18.5
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/bassamfouad/Library/Android/sdk
    • Platform android-32, build-tools 32.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F100
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.74.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • iPhone 13 Pro (mobile) • DE2C0AD9-4585-4AC4-AC34-103B6DC5E3F5 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-x64     • macOS 12.4 21F79 darwin-x64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 108.0.5359.98

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

here is my code 

```
passwordTextItem(
                              context,
                              StringConstants.PASSWORD,
                              _passwordController,
                              true,
                              borderColor: borderColor,
                              inputType: TextInputType.text,
                              inputAction: TextInputAction.next,
                              onChange: (newText) {
                                _updatePasswordBorderColor(_passwordController);
                              },
                            )

Widget passwordTextItem(BuildContext context, String name,
    TextEditingController controller, bool obsecureText,
    {TextInputType inputType = TextInputType
        .text, TextInputAction inputAction = TextInputAction
        .done, int limit = 50, Color borderColor = kLightGrey, VoidCallback? callback, Function(String newText)? onChange}) {
  return Container(
    width: MediaQuery
        .of(context)
        .size
        .width,
    height: 64,
    decoration: BoxDecoration(
        color: kLightGrey,
        borderRadius: BorderRadius.all(Radius.circular(10)),
        border: Border.all(color: borderColor)
    ),
    child: TextFormField(
      controller: controller,
      obscureText: obsecureText,
      keyboardType: inputType,
      textInputAction: inputAction,
      style: const TextStyle(
        fontSize: 16,
        color: Colors.black,
      ),
      decoration: InputDecoration(
        border: OutlineInputBorder(),
        focusedBorder: InputBorder.none,
        enabledBorder: InputBorder.none,
        errorBorder: InputBorder.none,
        disabledBorder: InputBorder.none,
        contentPadding:
        EdgeInsets.only(left: 15, bottom: 11, top: 11, right: 15),
        labelText: name,
      ),
      onChanged: (newText) {
        onChange != null ? onChange(newText) : ({});
      },),
  );
}
```

**Comment by danagbemava-nc** [comment]
Hi @bassamfouad-10p, I used the code sample you provided (slightly edited to remove some unnecessary parts of the code) and tested the sample on the iOS simulator Iphone 14pro and the keyboard showed up just fine. See the recording below. Is there any additional information that you can provide?

<details>
<summary>recording</summary>

https://user-images.githubusercontent.com/88313112/207240700-d878d7bd-b9a6-4b05-b07a-dc689d8fd024.mp4
</details>


<details>
<summary>code sample used</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: HomeScreen(),
    );
  }
}

class HomeScreen extends StatelessWidget {
  HomeScreen({super.key});

  final TextEditingController _passwordController = TextEditingController();

  Widget passwordTextItem(BuildContext context, String name, TextEditingController controller, bool obsecureText,
      {TextInputType inputType = TextInputType.text,
      TextInputAction inputAction = TextInputAction.done,
      int limit = 50,
      VoidCallback? callback,
      Function(String newText)? onChange}) {
    return Container(
      width: MediaQuery.of(context).size.width,
      height: 64,
      decoration: const BoxDecoration(
        borderRadius: BorderRadius.all(
          Radius.circular(10),
        ),
      ),
      child: TextFormField(
        controller: controller,
        obscureText: obsecureText,
        keyboardType: inputType,
        textInputAction: inputAction,
        style: const TextStyle(
          fontSize: 16,
          color: Colors.black,
        ),
        decoration: InputDecoration(
          border: const OutlineInputBorder(),
          focusedBorder: InputBorder.none,
          enabledBorder: InputBorder.none,
          errorBorder: InputBorder.none,
          disabledBorder: InputBorder.none,
          contentPadding: const EdgeInsets.only(left: 15, bottom: 11, top: 11, right: 15),
          labelText: name,
        ),
        onChanged: (newText) {
          onChange != null ? onChange(newText) : ({});
        },
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: SizedBox(
          child: passwordTextItem(
            context,
            'Password',
            _passwordController,
            true,
            inputType: TextInputType.text,
            inputAction: TextInputAction.next,
            onChange: (newText) {},
          ),
        ),
      ),
    );
  }
}

```
</details>

**Comment by bassamfouad-10p** [comment]
Hi @danagbemava-nc the issue is in release mode when you create .ipa file or upload it to test flight.

**Comment by huycozy** [comment]
@bassamfouad-10p Can you share a recorded video for this issue so that we can observe its behavior? Also, please retry on the latest `master` channel to see if the issue still persists or not. Thanks!

**Comment by bassamfouad-10p** [comment]
@huycozy It is still happening on master channel on release mode.

**Comment by bassamfouad-10p** [comment]
@huycozy here is a video for it keyboard still working but goes white in password field [https://drive.google.com/file/d/1hRgIwB0f2KtrA8wWQSuilHumN0HD2wtR/view?usp=sharing](url)

**Comment by danagbemava-nc** [comment]
Labeling for further investigation based on the report above. 

I cannot reproduce this by running `flutter run --release` on my iPhone XS and I cannot verify on testflight at the moment(I will update when I can). 
A recording of the issue can be found in https://github.com/flutter/flutter/issues/116777#issuecomment-1367173183 and according to OP, this seems to be an issue with the iPhone 14 pro models.

**Comment by chinmaygarde** [comment]
Without a reproduction I don't think we can make progress on this.

**Comment by jmagman** [comment]
@tenhobi please file a new issue describing your feature request, completely filling out the template.
