### ISSUE TITLE
App crashes due to error in gradle

### ISSUE THREAD

**Issue by TitikshaDaga** [flutter/flutter#11673]
FAILURE: Build failed with an exception.

* Where:
Script '/home/power/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 320

* What went wrong:
Execution failed for task ':app:flutterBuildDebug'.
> Process 'command '/home/power/flutter/bin/flutter'' finished with non-zero exit value 255

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

Gradle build failed: 1
[flutter_09.txt](https://github.com/flutter/flutter/files/1233824/flutter_09.txt)

This is the log file

**Comment by Hixie** [comment]
Can you let us know the output of the following commands?
* `which zip`
* `ls -al /usr/bin/zip`
* `/usr/bin/zip --version`

**Comment by mit-mit** [comment]
Closing as not actionable.
