### ISSUE TITLE
Add a way to clean only one xcode scheme  

### ISSUE THREAD

**Issue by EArminjon** [flutter/flutter#116735]
## Use case

When your project have many scheme, flutter clean took too many times. Inside CI-CD, cleaning all scheme seems to be overkill and took too much ressource. Our app took more than 10min to clean all schemes. Multiply by the number of release and build, it took a lot of ressources (time, cpu, electricity).

Example : 

In my entreprise, many project have a ton of schemes...

- Debug-qa-france
- Release-qa-france
- Debug-uat-france
- Release-uat-france
- Debug-prod-france
- Release-prod-france

Imagine now having more than 10 countries. Total more than 60 schemes...

## Proposal

Adding a flag to the clean command to target a specific scheme to be clean.

**Comment by christopherfujino** [comment]
@EArminjon are you saying that running only `flutter clean` on a single app is taking over 10 minutes? If this is true, this seems like a bug in `flutter clean`, and the action item would be for it to be faster.

**Comment by darshankawar** [comment]
Thanks for the report @EArminjon 
Does the time taken occur only in CI/CD or locally as well ? Can you provide logs that shows the time taken while `flutter clean` ?

**Comment by christopherfujino** [comment]
> > @EArminjon are you saying that running only `flutter clean` on a single app is taking over 10 minutes? If this is true, this seems like a bug in `flutter clean`, and the action item would be for it to be faster.
> 
> Yes if an app have many flavor (ios scheme).
> 
> For example, inside the flutter clean command the following command is run, I added time to monitor:
> 
> ```
>  time /usr/bin/arch -arm64e xcrun xcodebuild -workspace /Users/earminjon/Documents/projects/flutter-app/ios/Runner.xcworkspace -scheme ideal clean
> Command line invocation:
>     /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -workspace /Users/earminjon/Documents/projects/flutter-app/ios/Runner.xcworkspace -scheme ideal clean
> 
> User defaults from command line:
>     IDEPackageSupportUseBuiltinSCM = YES
> 
> --- xcodebuild: WARNING: Using the first of multiple matching destinations:
> { platform:macOS, arch:arm64, variant:Designed for [iPad,iPhone], id:00006000-000C21580AE2801E }
> { platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Any iOS Device }
> { platform:iOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder, name:Any iOS Simulator Device }
> { platform:iOS Simulator, id:F05F9299-7D90-42DF-B222-458BB3146059, OS:15.5, name:iPad (9th generation) }
> { platform:iOS Simulator, id:A7DAEA41-C129-4EA8-9ECC-AB5ECBE5A1B7, OS:15.5, name:iPad Air (5th generation) }
> { platform:iOS Simulator, id:CBA2515C-9EE4-4337-84E0-15796B0C4141, OS:15.5, name:iPad Pro (9.7-inch) }
> { platform:iOS Simulator, id:0FA0DD45-2A51-415F-B7A7-16780E1DBB2D, OS:15.5, name:iPad Pro (11-inch) (3rd generation) }
> { platform:iOS Simulator, id:96D1392E-2B69-4B8F-8269-A3F958A4A623, OS:15.5, name:iPad Pro (12.9-inch) (5th generation) }
> { platform:iOS Simulator, id:47B3CB10-99FB-4342-ADB7-45DCDED0722A, OS:15.5, name:iPad mini (6th generation) }
> { platform:iOS Simulator, id:DCF3D665-ED50-4DEF-BFFB-3D5920ED3CF1, OS:15.5, name:iPhone 8 }
> { platform:iOS Simulator, id:D265D7D6-2B25-48EC-9C58-F65473B8EA83, OS:15.5, name:iPhone 8 Plus }
> { platform:iOS Simulator, id:E1A6158F-A806-4DDD-B759-17DCF23C961A, OS:15.5, name:iPhone 11 }
> { platform:iOS Simulator, id:E3ABFC07-618A-46C7-9B74-3B998644065E, OS:15.5, name:iPhone 11 Pro }
> { platform:iOS Simulator, id:FC43A450-303D-49EC-B5B8-2BE1E82FBBEB, OS:15.5, name:iPhone 11 Pro Max }
> { platform:iOS Simulator, id:20978832-C147-4475-92C9-30CEBE150DF3, OS:16.0, name:iPhone 11 Pro Max }
> { platform:iOS Simulator, id:50122CFE-BF76-43E5-B6C5-5BB2255DFE1C, OS:15.5, name:iPhone 12 }
> { platform:iOS Simulator, id:B1063702-D527-4C26-9167-32E1AEB45C38, OS:15.5, name:iPhone 12 Pro }
> { platform:iOS Simulator, id:AEAC9789-BEB2-4290-87CF-D6D2FDBF3108, OS:15.5, name:iPhone 12 Pro Max }
> { platform:iOS Simulator, id:C39B3D18-0FF7-491A-8776-AAF6C555C4B1, OS:15.5, name:iPhone 12 mini }
> { platform:iOS Simulator, id:4A2C8853-8DAF-4B4D-8F48-CC880F6530C9, OS:15.5, name:iPhone 13 }
> { platform:iOS Simulator, id:E058092C-8DC3-4303-A8DA-B801A11F6DD6, OS:15.5, name:iPhone 13 Pro }
> { platform:iOS Simulator, id:542C0B77-7214-4137-B639-4AE8CCBFE16C, OS:15.5, name:iPhone 13 Pro Max }
> { platform:iOS Simulator, id:F3D9A552-88AB-4AA3-8817-1592934650D0, OS:15.5, name:iPhone 13 mini }
> { platform:iOS Simulator, id:9D692ECE-A69D-4625-8005-EF842A14F3ED, OS:16.0, name:iPhone 14 }
> { platform:iOS Simulator, id:0FF7BC11-88E9-47F7-94FD-68D271803CBA, OS:15.5, name:iPhone SE (3rd generation) }
> { platform:iOS Simulator, id:43DCF623-D504-438E-83E8-82E65CDA5FEB, OS:16.0, name:iPhone SE (3rd generation) }
> { platform:iOS Simulator, id:EA282C9E-8CE8-49C4-8BE8-2315F0ABE666, OS:15.5, name:iPod touch (7th generation) }
> 
> ** CLEAN SUCCEEDED **
> 
> /usr/bin/arch -arm64e xcrun xcodebuild -workspace  -scheme ideal clean  9.96s user 0.76s system 86% cpu 12.351 total
> ```
> 
> The command took 10sec for only one scheme. 60 schemes * 10sec = 10min and could be more.

Ahh, I see, so this is being delegated to xcodebuild. I don't imagine we'd have any other way to speed this up other than allowing filtering per scheme. WDYT @jmagman?

**Comment by jmagman** [comment]
> I don't imagine we'd have any other way to speed this up other than allowing filtering per scheme.

That's the easiest thing I can think of, could be a hidden flag.

@EArminjon why are you running `flutter clean` so often?

**Comment by hellohuanlin** [comment]
Maybe we can do something similar to Xcode's "Clean build folder" which nukes the build folder for all targets.

**Comment by jmagman** [comment]
It's currently cleaning for each scheme:
https://github.com/flutter/flutter/blob/ca7fe334853b7bed74c8fb5b881c1a61a3757375/packages/flutter_tools/lib/src/commands/clean.dart#L84-L86
https://github.com/flutter/flutter/blob/ca7fe334853b7bed74c8fb5b881c1a61a3757375/packages/flutter_tools/lib/src/ios/xcodeproj.dart#L299-L309

**Comment by jmagman** [comment]
> Maybe we can do something similar to Xcode's "Clean build folder" which nukes the build folder for all targets.

That's what `flutter clean` does, it deletes the app `build` directory.  However it first cleans the workspace since not all cached artifacts are in that directory.

**Comment by EArminjon** [comment]
PR merged.
