### ISSUE TITLE
Rename Linux|Mac|Windows release_builder to Linux|Mac|Windows engine_release_builder

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#116796]
The builder names are not consistent with the packaging or flutter framework builders. In addition to that we should also move the engine release builders to run only on release candidate branches.

**Comment by drewroengoogle** [comment]
> In addition to that we should also move the engine release builders to run only on release candidate branches.

@godofredoc This is a change to .ci.yaml right?

**Comment by godofredoc** [comment]
No, it is an infra config in dart-internal.

**Comment by drewroengoogle** [comment]
https://dart-internal-review.git.corp.google.com/c/dart-internal/+/4100

**Comment by godofredoc** [comment]
Can we send another change for the flutter builder? s/Linux Flutter release_builder/Linux flutter_release_builder?

**Comment by godofredoc** [comment]
Fixed with https://dart-internal-review.git.corp.google.com/c/dart-internal/+/4160
