### ISSUE TITLE
'Flutter/Flutter.h' file not found.

### ISSUE THREAD

**Issue by sonibhavik** [flutter/flutter#116870]
<img width="929" alt="Screenshot 2022-12-12 at 10 32 05 AM" src="https://user-images.githubusercontent.com/35720776/206965969-17c96d80-3725-4f33-a748-a309d0f91401.png">

Hello Folks, 

When I try to run my project either in xcode or in Android studio in iOS 16.1 device then it says like  "error: 'Flutter/Flutter.h' file not found" and "error: failed to emit precompiled header ios/Runner/Runner-Bridging-Header.h".

Following are my current details:

MacOS: 13.0.1 Ventura
Flutter: 3.3.8
Dart: 2.18.4
Android Studion Chipmunk

If anyone have any valid solution to this issue which actually works then it will be very helpful.

Thanks.

**Comment by exaby73** [comment]
Hello @sonibhavik. Try selecting `Product` -> `Analyze` or use the shortcut <kbd>CMD</kbd>+<kbd>Shift</kbd>+<kbd>B</kbd>
