### ISSUE TITLE
The word "sliver" is unclear

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#11680]
Specifically the definition being sought was "sliver".  Turns out it's defined in RenderSliver:
https://master-docs-flutter-io.firebaseapp.com/flutter/rendering/RenderSliver-class.html

But lots of classes have sliver in their name w/o linking to RenderSliver.  Unsure what the best solution is here.

**Comment by pedia** [comment]
sliver is so different to the material.

**Comment by Hixie** [comment]
We have descriptions for this in various places, [slivers flutter] gives many of them. There's a whole boring show about it too.
