### ISSUE TITLE
AnimatedBuilder rebuild

### ISSUE THREAD

**Issue by WangDan1989** [flutter/flutter#116824]
```
import 'dart:math' as math;

import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  static const String _title = 'Flutter Code Sample';

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      title: _title,
      home: MyStatefulWidget(),
    );
  }
}

class MyStatefulWidget extends StatefulWidget {
  const MyStatefulWidget({super.key});

  @override
  State<MyStatefulWidget> createState() => _MyStatefulWidgetState();
}

/// AnimationControllers can be created with `vsync: this` because of TickerProviderStateMixin.
class _MyStatefulWidgetState extends State<MyStatefulWidget>
    with TickerProviderStateMixin {
  late final AnimationController _controller = AnimationController(
    duration: const Duration(milliseconds: 1),
    vsync: this,
  )..repeat();

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return AnimatedBuilder(
      animation: _controller,
      child: Container(
        width: 200.0,
        height: 200.0,
        color: Colors.green,
        child: const Center(
          child: Text('Whee!'),
        ),
      ),
      builder: (BuildContext context, Widget? child) {
        return Transform.rotate(
          angle: _controller.value * 2.0 * math.pi,
          child: child,
        );
      },
    );
  }
}

I see widget rebuild stats :
Flutter Performance ：AnimatedBuilder current screen is increasing.
soon the animation dropped the frame。


```

**Comment by darshankawar** [comment]
@WangDan1989 
Can you provide `flutter doctor -v` and on which platform are you seeing this behavior ? Can you also run in `--profile` mode and show some graphics that shows the performance behavior ?

**Comment by WangDan1989** [comment]
![Uploading BC48348C-D5CF-4755-9E99-8D9D2B09BA08.jpeg…]()

**Comment by darshankawar** [comment]
@WangDan1989 
The image you shared above didn't properly get uploaded, so we can't see anything in it. Please provide the requested details earlier so as to make this issue actionable.

**Comment by WangDan1989** [comment]
![4](https://user-images.githubusercontent.com/8241061/211763333-a30caa81-0c68-4f32-a3f2-d49661b9b7cf.jpg)

**Comment by WangDan1989** [comment]
![1](https://user-images.githubusercontent.com/8241061/211763461-1cdfd968-78d4-49cd-8ee1-91b64b21f7ce.jpg)

**Comment by WangDan1989** [comment]
![2](https://user-images.githubusercontent.com/8241061/211763526-763a2d6d-5953-46bf-b349-78ad0689ff90.jpg)

**Comment by WangDan1989** [comment]
animationController = AnimationController(vsync: this, duration: const Duration(milliseconds: 2500));
      hAnimation = Tween(begin: 90.0, end: 20.0).animate(CurvedAnimation(parent: animationController, curve: const Interval(0, 0.3))); //
      vAnimation = Tween(begin: 40.0, end: 130.0).animate(CurvedAnimation(parent: animationController, curve: const Interval(0.3, 0.8)));
      scaleAnimation = Tween(begin: 1.0, end: 5.0).animate(CurvedAnimation(parent: animationController, curve: const Interval(0, 0.8))); //
      animationController.repeat();
      
  @override
  Widget build(BuildContext context) {
    return AnimatedBuilder(
      animation: animationController,
      child: Container(
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(1),
          color: color,
        ),
        width: 2,
        height: 2,
      ),
      builder: (BuildContext context, Widget? child) {
        return Transform.translate(
          offset: Offset(hAnimation.value - scaleAnimation.value / 2, vAnimation.value - scaleAnimation.value / 2),
          child: Transform.scale(scale: scaleAnimation.value, child: child!),
        );
      },
    );
  }

**Comment by WangDan1989** [comment]
[✓] Flutter (Channel unknown, 3.0.1, on macOS 12.6.1 21G217 darwin-x64, locale zh-Hans-CN)
    • Flutter version 3.0.1 at /Users/admin/flutter
    • Upstream repository unknown
    • Framework revision fb57da5f94 (8 months ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/admin/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc4
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode13.4.1.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.74.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.56.0

[✓] Connected device (3 available)
    • iPhone (3) (mobile) • 00008101-001A393E342A001E • ios            • iOS 15.7.1 19H117
    • macOS (desktop)     • macos                     • darwin-x64     • macOS 12.6.1 21G217 darwin-x64
    • Chrome (web)        • chrome                    • web-javascript • Google Chrome 107.0.5304.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Comment by darshankawar** [comment]
@WangDan1989 
You are on old version of stable. Current is 3.3.10. I suggest you to upgrade and try the same to see if you still get same behavior or not.

**Comment by WangDan1989** [comment]
> @WangDan1989
> You are on old version of stable. Current is 3.3.10. I suggest you to upgrade and try the same to see if you still get same behavior or not.

I initially tried to upgrade to solve this problem and found that the problem still existed

**Comment by darshankawar** [comment]
Thanks for the update. I ran the code sample you provided on latest stable in `--profile` mode and below is the performance I see:


https://user-images.githubusercontent.com/67046386/211988907-ecbbf8e6-e188-4e25-9d3a-1517b2558c73.mov

In which mode are you seeing the performance spike (debug, profile or release) ?

**Comment by WangDan1989** [comment]
admin@admindeMacBook-Pro hxess % flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel unknown, 3.3.10, on macOS 12.6.1 21G217 darwin-x64, locale zh-Hans-CN)
    ! Flutter version 3.3.10 on channel unknown at /Users/admin/flutter
    ! Upstream repository unknown
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.74.3)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

! Doctor found issues in 1 category.

**Comment by WangDan1989** [comment]
> Thanks for the update. I ran the code sample you provided on latest stable in `--profile` mode and below is the performance I see:
> 
>  116824_1.mov 
> 
> In which mode are you seeing the performance spike (debug, profile or release) ?

import 'dart:math' as math;
import 'dart:math';

import 'package:flutter/material.dart';
import 'package:transform/devicedetailbody.dart';

import 'devicelefttop.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  static const String _title = 'Flutter Code Sample';

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      title: _title,
      home: MyStatefulWidget(),
    );
  }
}

class MyStatefulWidget extends StatefulWidget {
  const MyStatefulWidget({super.key});

  @override
  State<MyStatefulWidget> createState() => _MyStatefulWidgetState();
}

/// AnimationControllers can be created with `vsync: this` because of TickerProviderStateMixin.
class _MyStatefulWidgetState extends State<MyStatefulWidget> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Column(
        children: [
          Row(
            mainAxisAlignment: MainAxisAlignment.center,
            crossAxisAlignment: CrossAxisAlignment.start,
            children: const [
              DeviceLeftTop(
                direction: 1,
              ),
              DeviceLeftTop(
                direction: 1,
              ),
            ],
          ),
          Row(
            mainAxisAlignment: MainAxisAlignment.center,
            crossAxisAlignment: CrossAxisAlignment.start,
            children: const [
              DeviceLeftTop(
                direction: 1,
              ),
              DeviceLeftTop(
                direction: 1,
              ),
            ],
          ),
        ],
      ),
    );
  }
}

**Comment by WangDan1989** [comment]
import 'package:flutter/material.dart';

import 'devicelefttop.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  static const String _title = 'Flutter Code Sample';

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      title: _title,
      home: MyStatefulWidget(),
    );
  }
}

class MyStatefulWidget extends StatefulWidget {
  const MyStatefulWidget({super.key});

  @override
  State<MyStatefulWidget> createState() => _MyStatefulWidgetState();
}

/// AnimationControllers can be created with `vsync: this` because of TickerProviderStateMixin.
class _MyStatefulWidgetState extends State<MyStatefulWidget> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Column(
        children: [
          Row(
            mainAxisAlignment: MainAxisAlignment.center,
            crossAxisAlignment: CrossAxisAlignment.start,
            children: const [
              DeviceLeftTop(
                direction: 1,
              ),
              DeviceLeftTop(
                direction: 1,
              ),
            ],
          ),
          Row(
            mainAxisAlignment: MainAxisAlignment.center,
            crossAxisAlignment: CrossAxisAlignment.start,
            children: const [
              DeviceLeftTop(
                direction: 1,
              ),
              DeviceLeftTop(
                direction: 1,
              ),
            ],
          ),
        ],
      ),
    );
  }
}

**Comment by WangDan1989** [comment]
import 'dart:math';

import 'package:flutter/material.dart';

class DeviceLeftTop extends StatefulWidget {
  static const String routerName = "/DeviceLeftTop";
  final int direction;

  const DeviceLeftTop({Key? key, required this.direction}) : super(key: key);

  @override
  State<DeviceLeftTop> createState() => _DeviceLeftTopState();
}

class _DeviceLeftTopState extends State<DeviceLeftTop> with TickerProviderStateMixin {
  late AnimationController animationController;
  late Animation<double> hAnimation;
  late Animation<double> vAnimation;
  late Animation<double> scaleAnimation;

  late Animation<double> hAnimation1;
  late Animation<double> vAnimation1;
  late Animation<double> scaleAnimation1;

  @override
  void initState() {
    super.initState();
    animationController = AnimationController(vsync: this, duration: const Duration(seconds: 3));
    hAnimation = Tween(begin: -10.0, end: 60.0 - 1).animate(CurvedAnimation(parent: animationController, curve: const Interval(0, 0.3))); //
    vAnimation = Tween(begin: 40.0 - 1, end: 130.0).animate(CurvedAnimation(parent: animationController, curve: const Interval(0.3, 0.8)));
    scaleAnimation = Tween(begin: 1.0, end: 5.0).animate(CurvedAnimation(parent: animationController, curve: const Interval(0, 0.8))); //
    hAnimation1 = Tween(begin: -10.0, end: 60.0 - 1).animate(CurvedAnimation(parent: animationController, curve: const Interval(0.2, 0.5))); //
    vAnimation1 = Tween(begin: 40.0 - 1, end: 130.0).animate(CurvedAnimation(parent: animationController, curve: const Interval(0.5, 1)));
    scaleAnimation1 = Tween(begin: 1.0, end: 5.0).animate(CurvedAnimation(parent: animationController, curve: const Interval(0.2, 1))); //
    animationController.repeat();
  }

  @override
  void dispose() {
    super.dispose();
    animationController.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return SizedBox(
      width: 80.0,
      height: 120.0,
      child: ClipRect(
        child: Stack(
          children: [
            Positioned(
              left: 0,
              top: 40.0,
              width: 60.0,
              height: 80.0,
              child: CustomPaint(
                size: const Size(60.0, 80.0),
                painter: LTLineWidget(),
              ),
            ),
            AnimatedBuilder(
              animation: animationController,
              child: Container(
                decoration: BoxDecoration(
                  borderRadius: BorderRadius.circular(1),
                  color: Colors.red,
                ),
                width: 2,
                height: 2,
              ),
              builder: (BuildContext context, Widget? child) {
                return Transform.translate(
                  offset: Offset(hAnimation1.value, vAnimation1.value),
                  child: Transform.scale(scale: scaleAnimation1.value, child: child!),
                );
              },
            ),
            AnimatedBuilder(
              animation: animationController,
              child: Container(
                decoration: BoxDecoration(
                  borderRadius: BorderRadius.circular(1),
                  color: Colors.red,
                ),
                width: 2,
                height: 2,
              ),
              builder: (BuildContext context, Widget? child) {
                return Transform.translate(
                  offset: Offset(hAnimation.value, vAnimation.value),
                  child: Transform.scale(scale: scaleAnimation.value, child: child!),
                );
              },
            ),
          ],
        ),
      ),
    );
  }
}

class LTLineWidget extends CustomPainter {
  final Path _path = Path();
  final Paint _paint = Paint()
    ..color = const Color(0xFF86A9C1) //画笔颜色
    ..strokeCap = StrokeCap.round //画笔笔头类型
    ..isAntiAlias = true //是否开启抗锯齿
    ..blendMode = BlendMode.src //颜色混合模式
    ..style = PaintingStyle.stroke //画笔样式，默认为填充
    ..colorFilter = const ColorFilter.mode(Color(0xFF86A9C1), BlendMode.src) //颜色渲染模式
    ..maskFilter = const MaskFilter.blur(BlurStyle.inner, 1.0) //模糊遮罩效果
    ..filterQuality = FilterQuality.high //颜色渲染模式的质量
    ..strokeWidth = 2; //画笔的宽度复制代码  @override
  @override
  void paint(Canvas canvas, Size size) {
    // TODO: implement paint
    // 画个实心圆
    _path.addArc(const Rect.fromLTWH(60.0 - 10, 0, 10, 10), -90 * (pi / 180.0), 90 * (pi / 180.0));
    canvas.drawPath(_path, _paint);
    canvas.drawLine(const Offset(0, 0), const Offset(60.0 - 5, 0), _paint);
    canvas.drawLine(const Offset(60.0, 5), const Offset(60.0, 80.0), _paint);
  }

  @override
  bool shouldRepaint(covariant CustomPainter oldDelegate) {
    // TODO: implement shouldRepaint
    return false;
  }
}

**Comment by WangDan1989** [comment]
import 'dart:math';

import 'package:flutter/material.dart';

class DeviceLeftTop extends StatefulWidget {
  static const String routerName = "/DeviceLeftTop";
  final int direction;

  const DeviceLeftTop({Key? key, required this.direction}) : super(key: key);

  @override
  State<DeviceLeftTop> createState() => _DeviceLeftTopState();
}

class _DeviceLeftTopState extends State<DeviceLeftTop> with TickerProviderStateMixin {
  late AnimationController animationController;
  late Animation<double> hAnimation;
  late Animation<double> vAnimation;
  late Animation<double> scaleAnimation;

  late Animation<double> hAnimation1;
  late Animation<double> vAnimation1;
  late Animation<double> scaleAnimation1;

  @override
  void initState() {
    super.initState();
    animationController = AnimationController(vsync: this, duration: const Duration(seconds: 3));
    hAnimation = Tween(begin: -10.0, end: 60.0 - 1).animate(CurvedAnimation(parent: animationController, curve: const Interval(0, 0.3))); //
    vAnimation = Tween(begin: 40.0 - 1, end: 130.0).animate(CurvedAnimation(parent: animationController, curve: const Interval(0.3, 0.8)));
    scaleAnimation = Tween(begin: 1.0, end: 5.0).animate(CurvedAnimation(parent: animationController, curve: const Interval(0, 0.8))); //
    hAnimation1 = Tween(begin: -10.0, end: 60.0 - 1).animate(CurvedAnimation(parent: animationController, curve: const Interval(0.2, 0.5))); //
    vAnimation1 = Tween(begin: 40.0 - 1, end: 130.0).animate(CurvedAnimation(parent: animationController, curve: const Interval(0.5, 1)));
    scaleAnimation1 = Tween(begin: 1.0, end: 5.0).animate(CurvedAnimation(parent: animationController, curve: const Interval(0.2, 1))); //
    animationController.repeat();
  }

  @override
  void dispose() {
    super.dispose();
    animationController.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return SizedBox(
      width: 80.0,
      height: 120.0,
      child: ClipRect(
        child: Stack(
          children: [
            Positioned(
              left: 0,
              top: 40.0,
              width: 60.0,
              height: 80.0,
              child: CustomPaint(
                size: const Size(60.0, 80.0),
                painter: LTLineWidget(),
              ),
            ),
            AnimatedBuilder(
              animation: animationController,
              child: Container(
                decoration: BoxDecoration(
                  borderRadius: BorderRadius.circular(1),
                  color: Colors.red,
                ),
                width: 2,
                height: 2,
              ),
              builder: (BuildContext context, Widget? child) {
                return Transform.translate(
                  offset: Offset(hAnimation1.value, vAnimation1.value),
                  child: Transform.scale(scale: scaleAnimation1.value, child: child!),
                );
              },
            ),
            AnimatedBuilder(
              animation: animationController,
              child: Container(
                decoration: BoxDecoration(
                  borderRadius: BorderRadius.circular(1),
                  color: Colors.red,
                ),
                width: 2,
                height: 2,
              ),
              builder: (BuildContext context, Widget? child) {
                return Transform.translate(
                  offset: Offset(hAnimation.value, vAnimation.value),
                  child: Transform.scale(scale: scaleAnimation.value, child: child!),
                );
              },
            ),
          ],
        ),
      ),
    );
  }
}

class LTLineWidget extends CustomPainter {
  final Path _path = Path();
  final Paint _paint = Paint()
    ..color = const Color(0xFF86A9C1)
    ..strokeCap = StrokeCap.round
    ..isAntiAlias = true
    ..blendMode = BlendMode.src
    ..style = PaintingStyle.stroke
    ..colorFilter = const ColorFilter.mode(Color(0xFF86A9C1), BlendMode.src)
    ..maskFilter = const MaskFilter.blur(BlurStyle.inner, 1.0)
    ..filterQuality = FilterQuality.high
    ..strokeWidth = 2;

  @override
  void paint(Canvas canvas, Size size) {
    _path.addArc(const Rect.fromLTWH(60.0 - 10, 0, 10, 10), -90 * (pi / 180.0), 90 * (pi / 180.0));
    canvas.drawPath(_path, _paint);
    canvas.drawLine(const Offset(0, 0), const Offset(60.0 - 5, 0), _paint);
    canvas.drawLine(const Offset(60.0, 5), const Offset(60.0, 80.0), _paint);
  }

  @override
  bool shouldRepaint(covariant CustomPainter oldDelegate) {
    // TODO: implement shouldRepaint
    return false;
  }
}

**Comment by WangDan1989** [comment]
Less than a minute

**Comment by darshankawar** [comment]
> In which mode are you seeing the performance spike (debug, profile or release) ?

Can you provide this info ? Also, just sharing the code sample without any description or details probably won't help much. I earlier shared that I was unable to replicate the spike. Are you still seeing the same ? On which platform (Android, iOS) ? 
For Performance related issues, please try to run as mentioned in [this](https://github.com/flutter/flutter/issues/74833#issue-795394794) issue and provide the relevant details that support the claim.

**Comment by WangDan1989** [comment]
flutter doctor -v
[!] Flutter (Channel unknown, 3.3.10, on macOS 12.6.1 21G217 darwin-x64, locale zh-Hans-CN)
    ! Flutter version 3.3.10 on channel unknown at /Users/admin/flutter
    ! Upstream repository unknown
    • Framework revision 135454af32 (4 weeks ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/admin/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc4
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode13.4.1.app/Contents/Developer
    • Build 13F100
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.74.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.56.0

[✓] Connected device (3 available)
    • iPhone (3) (mobile) • 00008101-001A393E342A001E • ios            • iOS 15.7.1 19H117
    • macOS (desktop)     • macos                     • darwin-x64     • macOS 12.6.1 21G217 darwin-x64
    • Chrome (web)        • chrome                    • web-javascript • Google Chrome 107.0.5304.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

**Comment by WangDan1989** [comment]
The above code is the test code.

**Comment by WangDan1989** [comment]
I don't know why, but when I deleted the other code and just kept the action, no frames were dropped. But when I tried my project in this way, I found no effect and it was hard to understand.

**Comment by WangDan1989** [comment]
I know why, but it's confusing. When I was writing the animation I drew a line on the canvas. The reason the frame drops is because of the lines drawn.

**Comment by darshankawar** [comment]
I believe your case is similar to the one described in [here](https://github.com/flutter/flutter/issues/50012), so please follow-up in it for further updates. Closing as duplicate.
