### ISSUE TITLE
[Impeller] Partially update and reuse glyph atlases across render passes.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#116815]
Today, glyph atlases are created per render pass and discarded immediately after. This causes a lot of churn and the primary performance bottleneck in rendering text heavy applications using Impeller.

Impeller should be able to reuse glyph atlases across multiple render passes.

**Comment by jonahwilliams** [comment]
Fixed via https://github.com/flutter/engine/pull/38253

**Comment by jonahwilliams** [comment]
Reopening because https://github.com/flutter/engine/pull/38244 or similar would be required when platform views are involved
