### ISSUE TITLE
Unexpected child "shaders" found under "flutter"

### ISSUE THREAD

**Issue by feduke-nukem** [flutter/flutter#116884]
## Steps to Reproduce
 

1.  Add "flutter_shaders" to pubspec
2. Mention "shaders" under "flutter" in pubspec
3. Get error

**Expected results:** Pub get successfully

**Actual results:** Error

<details>
<img width="407" alt="image" src="https://user-images.githubusercontent.com/72284940/207038584-0c54f104-f2a9-4c1e-846e-4e2a772d96f9.png">

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by darshankawar** [comment]
@feduke-nukem 
It seems `flutter_shaders` is a new Flutter first party plugin / package, but there's not much info about it (example) or what it does basically.

You mentioned to add `shaders` in pubspec.yaml, can you provide a sample file that we can use that helps to replicate the reported issue ?

**Comment by feduke-nukem** [comment]
> @feduke-nukem It seems `flutter_shaders` is a new Flutter first party plugin / package, but there's not much info about it (example) or what it does basically.
> 
> You mentioned to add `shaders` in pubspec.yaml, can you provide a sample file that we can use that helps to replicate the reported issue ?

https://github.com/renancaraujo/glow_stuff_with_flutter/blob/main/pubspec.yaml

**Comment by jonahwilliams** [comment]
This functionality is only supported on the latest beta
