### ISSUE TITLE
Blur effect does not work over WebView widget

### ISSUE THREAD

**Issue by arnavjainn06** [flutter/flutter#116848]
### The .frosted function from the blur module doesn't seem to work on the webview widget. 
![image](https://user-images.githubusercontent.com/70736942/206891752-3881580e-df12-43c6-997b-121c319b8742.png)

### But it seems to work perfectly with other things behind it in the same stack
![simulator_screenshot_2CBE8B3B-6D3C-4BE0-A302-57C5EAD39869](https://userimages.githubusercontent.com/70736942/206891797-2b38dbd1-2a63-4c49-968f-805504f75eea.png)

### Here is my code

```
return Scaffold(
      body: Stack(
        children: [
          Container(
            // padding: EdgeInsets.only(top: 100),
            child: WebView(
              initialUrl: url,
              javascriptMode: JavascriptMode.unrestricted,
            ),
          ),
          Container(
            height: 110,
            width: double.infinity,
            child: Text('demo'),
            // color: Colors.black.withOpacity(0.7),
          ).frosted(blur: 20, frostColor: Colors.black, frostOpacity: 0.2)
        ]
      ),
    );

```

**Comment by darshankawar** [comment]
@arnavjainn06 Thanks for the report. Can you provide complete code sample ?
I am getting below compile error while trying to run your code:

<img width="553" alt="Screenshot 2022-12-12 at 2 04 03 PM" src="https://user-images.githubusercontent.com/67046386/206998624-592706c6-696c-4a52-9aea-1e2ccfcca72b.png">

I am on latest master and using latest `webview_flutter` plugin.

**Comment by arnavjainn06** [comment]
The method .frosted() comes from the package 'blur'
here's my pubspec.yaml line for the package:
`
blur: ^3.1.0
`

**Comment by darshankawar** [comment]
Thanks for the update. I see. 
You'll probably need to raise this issue in `blur` plugin's repo, as it might have a limitation on working with platform-views.
I am going ahead and closing this, since the plugin is third party.
