### ISSUE TITLE
Getting issue in carousel_slider dependencies while running app

### ISSUE THREAD

**Issue by rohansurvase12** [flutter/flutter#116821]
While I running my application I am getting error like : 

`/C:/src/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/carousel_slider-4.2.0/lib/carousel_slider.dart:311:29: Error: Member not found: 'trackpad'.
          PointerDeviceKind.trackpad`

Here are dependencies from yaml 

`version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  carousel_slider: ^4.2.0
  video_player:
`

Please suggest any solution

**Comment by stuartmorgan** [comment]
Please report issues with third-party dependencies to the package authors.

Closing as this is not a Flutter issue.

**Comment by rohansurvase12** [comment]
Ok no problem
