### ISSUE TITLE
Mechanism to show warning, when the flutter sdk is modified.

### ISSUE THREAD

**Issue by hndrbrm** [flutter/flutter#116874]
I have join into some group in Telegram about Flutter (Flutter Indonesia).

And i read in there that lot of problem occured because of the flutter source code are modified. This is usually happen for user which is in the stage of learning Flutter and using Visual Studio Code (Windows). They modified the code unintently.

Is it possible to give somekind of warning to us when the flutter sdk is somehow modified? Maybe the result of `git status` or other mechanism? so that the programmer could understand that the Flutter code is modified, when they run the project. So if some error happened, they could guess it themselves before asking to the community.

**Comment by hndrbrm** [comment]
For example like this:

If someone unintentionally change the `ChangeNotifier` code:
from `throw FlutterError(...` to `pthrow FlutterError(...`

This will make the project error even though its from the default project (counter) after creation.

![Screen Shot 2022-12-12 at 20 15 20](https://user-images.githubusercontent.com/86121106/207054195-80e910b4-62cc-4c80-bfa4-a9086b604f8d.png)

**Comment by darshankawar** [comment]
> unintentionally change the flutter framework source code, which is not supposed to be changed, for a beginner.

I think all the changes that are being made goes through PR review process and most probably those changes will be identified before changes are merged, so the typos or unintentional changes being pushed to master are very less likely.



> by adding the information about the integrity of flutter source code on the `flutter doctor`, whether the repo is intact or being modified.
> 
> Or by giving warning to the user (something like the update warning, when running `flutter run`) and give the solution `git reset --hard` which they could run when error occured because of it.

I am not sure if tracking such changes is feasible or practical to give out the warnings by the framework / tool. If you have pulled latest changes and it has some compile errors as you pointed out above due to typos for example, then the immediate remedy is to file a PR to fix it. I don't think tracking such changes at granular level is possible, so I suggest you to keep an eye on latest master / stable commits and PRs for the changes that are being made.

Based on above, I am going ahead and closing as not feasible. If you disagree, write in comments and I'll reopen it.

**Comment by hndrbrm** [comment]
> > unintentionally change the flutter framework source code, which is not supposed to be changed, for a beginner.
> 
> I think all the changes that are being made goes through PR review process and most probably those changes will be identified before changes are merged, so the typos or unintentional changes being pushed to master are very less likely.
> 
> > by adding the information about the integrity of flutter source code on the `flutter doctor`, whether the repo is intact or being modified.
> > Or by giving warning to the user (something like the update warning, when running `flutter run`) and give the solution `git reset --hard` which they could run when error occured because of it.
> 
> I am not sure if tracking such changes is feasible or practical to give out the warnings by the framework / tool. If you have pulled latest changes and it has some compile errors as you pointed out above due to typos for example, then the immediate remedy is to file a PR to fix it. I don't think tracking such changes at granular level is possible, so I suggest you to keep an eye on latest master / stable commits and PRs for the changes that are being made.
> 
> Based on above, I am going ahead and closing as not feasible. If you disagree, write in comments and I'll reopen it.

I dont think that you understand my meaning.
I don't know how to explain it. Maybe someone else with a good english could explain better.

What i mean by the change is not about PR or something like that.
Its more about the user whose learning flutter in the beginning, sometimes they modify the code of the framework, without they realizing it. Of course it will throw an error, but they will got confused by the error. They think something wrong with their code, which is not.
