### ISSUE TITLE
[Impeller] Support external texture interop for composition of GL textures in a Vulkan renderer.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#116803]

**Comment by chinmaygarde** [comment]
As discussed today in the Impeller weekly, this is not in scope for the Android Preview. cc @zanderso @johnmccutchan

**Comment by jonahwilliams** [comment]
We've decided not to do this, and the updated plan is tracked in: https://github.com/flutter/flutter/issues/139702
