### ISSUE TITLE
You uploaded an APK or Android App Bundle that was signed in debug mode. You need to sign your APK or Android App Bundle in release mode.

### ISSUE THREAD

**Issue by franquicidad** [flutter/flutter#116846]
## Steps to Reproduce

<img width="945" alt="Screen Shot 2022-12-10 at 11 09 12 PM" src="https://user-images.githubusercontent.com/28768991/206885975-95ea6482-efe0-41fe-ba38-3f92b62a5da2.png">
<img width="570" alt="Screen Shot 2022-12-10 at 11 09 02 PM" src="https://user-images.githubusercontent.com/28768991/206885978-3945f66c-34ee-4a65-9558-cb6922a9caf8.png">
<img width="928" alt="Screen Shot 2022-12-10 at 11 12 51 PM" src="https://user-images.githubusercontent.com/28768991/206886037-148dee9d-6bbb-4834-8b8c-7648c5769be4.png">

**Expected results:** 
I expected to see that the aab is approved. I followed the recommendations from flutter guide step by step. And the only possible solution in all internet and also in here GitHub is what is in my app build.gradle( as shown in the top image).
**Actual results:** 

<img width="945" alt="Screen Shot 2022-12-10 at 11 09 12 PM" src="https://user-images.githubusercontent.com/28768991/206885975-95ea6482-efe0-41fe-ba38-3f92b62a5da2.png">
Shown in the top image from play Store

**Comment by jetlye2804** [comment]
Try `flutter build apk --release` and see the result? I usually do it in that way.

**Comment by franquicidad** [comment]
@jetlye2804  it is weird what is happening. It tells us that we can upload an apk. however look at the evidence ... short words did work for me .
<img width="1208" alt="Screen Shot 2022-12-11 at 7 25 18 AM" src="https://user-images.githubusercontent.com/28768991/206903462-07aa9574-b41f-49a9-b746-cb2493689ef2.png">
<img width="568" alt="Screen Shot 2022-12-11 at 7 25 07 AM" src="https://user-images.githubusercontent.com/28768991/206903464-86a84838-5c31-4219-a22c-63d0a887266c.png">

I don't understand why I can't upload apks.

**Comment by darshankawar** [comment]
@franquicidad 
See [this](https://docs.flutter.dev/deployment/android#building-the-app-for-release) document wherein it is mentioned that app bundle is preferred when publishing to play store.
Based on it, I am going ahead and closing. If you disagree, write in comments and I'll reopen it.

**Comment by franquicidad** [comment]
Disagree @darshankawar please check my screenshots! . I also tried with the app bundle! .aar file.

<img width="637" alt="Screen Shot 2022-12-12 at 10 01 07 AM" src="https://user-images.githubusercontent.com/28768991/207078937-b824b990-da5e-4e04-b9f1-49dddeccb226.png">

**Comment by darshankawar** [comment]
@franquicidad 
Thanks for feedback. Can you provide the complete error message in properly formatted text ?

**Comment by franquicidad** [comment]
@darshankawar thank you for the help you can close it now . I signed the bundle from android studio tool and it worked.
