### ISSUE TITLE
[iPhone 14 pro] How to close the performance monitoring window

### ISSUE THREAD

**Issue by dujj** [flutter/flutter#116879]
When the application is under testflight, a performance monitoring window will appear, how to close it

Other devices do not encounter this problem, whether it is a test code, released online

Can't move, blocks UI

![cf17a79207a7a6eeb5b77003cc7accf6](https://user-images.githubusercontent.com/9443889/207030928-1fcd169b-6fd5-4e68-9c3c-17aadee68e5c.jpg)

flutter doctor:
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.9, on macOS 13.0.1 22A400 darwin-arm, locale
    zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version
    32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.73.1)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

• No issues found!

**Comment by darshankawar** [comment]
@dujj 
I am not sure if this is specific to Flutter. Do you happen to have any performance overlay enabled in your code ?
Can you confirm if using default counter app, if you upload it on testflight, do you still see the window ?

**Comment by dujj** [comment]
@darshankawar 
The same code, the problem only occurs on the device iphone14 pro.
Other models: iphone13, iPhone7 plus, do not have this problem.
Moreover, iPhone14 pro does not have this problem after the app is released to the appstore, and this problem only occurs in debug and test flight.
And use flutter create hello to create the simplest project, this problem will occur when debugging.
It can be confirmed that there is no special configuration for the project or a special switch is turned on in the code (I don’t know where the switch is).

**Comment by dujj** [comment]
I found the problem, the switch is in the settings

**Comment by dujj** [comment]
close
