### ISSUE TITLE
Tests using --fatal-warnings cannot run with a custom FLUTTER_STORAGE_BASE_URL

### ISSUE THREAD

**Issue by whesse** [flutter/flutter#116899]
The Build/Archive/Test refactoring of Flutter testing on the CI requires test builders to download Flutter engine artifacts from
a custom cloud storage bucket, not the production bucket of official Flutter downloads.

Using a custom bucket writes a Logger.error to the logger saying
"Flutter assets will be downloaded from $overrideUrl. Make sure you trust this source!"

at https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/cache.dart#L471

The --fatal-warnings flag makes a test fail if any flutter tool writes warnings or error to the logger:

https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/base/logger.dart#L235

So the tests do not pass when run with engine artifacts downloaded from the custom cloud storage bucket
https://storage.googleapis.com/flutter_archives_v2.

This could be fixed by adding a flag to suppress the error message, by making the message an logger.info message
(but it would not print out for users then), by not using the --fatal-warnings flag in tests, or by adding special
code in the logger to handle the override URL warning in the fatal warnings detection.

**Comment by whesse** [comment]
Here is some context, and links to earlier PRs and issues.

A prototype CL that enabled using artifacts from an override URL was made last year, but it just removed the URL override error warning completely: https://github.com/flutter/flutter/pull/105938/files

Some PRs where the --fatal-warnings code was implemented or changed, for reference:
https://github.com/flutter/flutter/pull/113748

https://github.com/flutter/flutter/pull/92031 , which implemented --fatal-warnings.
The bug filed requesting a --fatal-warnings option is https://github.com/flutter/flutter/issues/91325

**Comment by whesse** [comment]
Work on this is now tracked on the other issue.  Two candidate PRs have been uploaded: #128326 and #128335

**Comment by keyonghan** [comment]
https://github.com/flutter/flutter/pull/128335 has been landed. Closing.
