### ISSUE TITLE
CMake warning - policy CMP0135

### ISSUE THREAD

**Issue by Asmitta-01** [flutter/flutter#116866]
Hey
I reinstall windows on my laptop then flutter and all the needed components. I clone my project from git (i was working on it since 3 weeks) and launch it but while debugging a get this warning message: 
```
CMake Warning (dev) at C:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.24/Modules/ExternalProject.cmake:3071 (message):
  The DOWNLOAD_EXTRACT_TIMESTAMP option was not given and policy CMP0135 is
  not set.  The policy's OLD behavior will be used.  When using a URL
  download, the timestamps of extracted files should preferably be that of
  the time of extraction, otherwise code that depends on the extracted
  contents might not be rebuilt if the URL changes.  The OLD behavior
  preserves the timestamps from the archive instead, but this is usually not
  what you want.  Update your project to the NEW behavior or specify the
  DOWNLOAD_EXTRACT_TIMESTAMP option with a value of true to avoid this
  robustness issue.

Call Stack (most recent call first):
  C:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.24/Modules/ExternalProject.cmake:4167 (_ep_add_download_command)
  CMakeLists.txt:9 (ExternalProject_Add)
This warning is for project developers.  Use -Wno-dev to suppress it.
```
How can i remove this ?

**Comment by JaredEzz** [comment]
I'm also getting this issue, is it not an issue with the flutter implementation of windows?

**Comment by stuartmorgan** [comment]
@cbracken I see this with recent versions of VS; I think it just needs a CMakeList.txt migrator to add the policy (and a corresponding template update for new projects). See https://github.com/flutter/flutter/blob/fa01649a597091411458d2277b0ebe3aedf27a5a/packages/flutter_tools/templates/app_shared/windows.tmpl/CMakeLists.txt.tmpl#L9-L11 for existing policy settings for similar warnings.

**Comment by stuartmorgan** [comment]
Important repro information I had missed (because I mostly build our 1P plugin examples, and they use `FetchContent` for gtest) is that you need to be building a project that has a download step. In the original report it's `Modules/ExternalProject.cmake`, and with 1P (and I'm sure a number of 3P) plugins it's `Modules/FetchContent.cmake`.

It might be possible to set the policy in individual files (e.g., our plugin template which also uses `FetchContent`), but I'm not sure what happens if there are multiple conflicting declarations. It seems like we should probably still set this at the root level to just avoid the warning for all projects across the board.

**Comment by stuartmorgan** [comment]
Alternately, we may want to just migrate our existing `cmake_policy` to be [version-based](https://cmake.org/cmake/help/v3.15/command/cmake_policy.html#setting-policies-by-cmake-version) instead, so this kind of thing can be fixed in the future by just updating a single version number in the file.

**Comment by stuartmorgan** [comment]
> but I'm not sure what happens if there are multiple conflicting declarations

It looks like this is harmless, according to the docs:

>> CMake keeps policy settings on a stack, so changes made by the cmake_policy command affect only the top of the stack. A new entry on the policy stack is managed automatically for each subdirectory to protect its parents and siblings.

But it'll still be easiest for the ecosystem if everyone doesn't have to do this themselves, and the version-based approach seems like a sustainable way to manage this in a single place.
