### ISSUE TITLE
flutter adaptive scaffold adaptive layout example is wrong

### ISSUE THREAD

**Issue by fredgrott** [flutter/flutter#116862]
Okay,

The flutter adaptive scaffold adaptive layout example shows it naked, which then of course provide no enclosing material class wrapper as it does not include the scaffold.

One should in the adaptive layout show an enclosing scaffold with the adaptive layout being in the body slot of the scaffold. That way will get the correct wrapping Material class and the right non-null scaffold for Material Banner, Bottom sheet, snackbar, etc.

**Comment by exaby73** [comment]
Hello @fredgrott. Could you provide links to where you are referring this from? is it from the API docs on https://api.flutter.dev? Also, could you give an example of what this code is supposed to look like in your opinion?
