### ISSUE TITLE
Make cocoon SLSA L3 compliant

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#116860]
Back in Aug 2022 when we worked on SLSA compliance for the cocoon repository we where missing the policy verification.

Since then the Google Cloud and SLSA teams have collaborated to enable provenance validation workflows:

* https://cloud.google.com/build/docs/securing-builds/view-build-provenance#validate_the_provenance_metadata
*  https://slsa.dev/blog/2022/12/gcb-slsa-verification

To get to SLSA L3 we need the following:

- [x] Make the SLSA cocoon validation document public
- [x] Create a security policy
- [x] Verify provenance before deploying to AppEngine
- [x] Submit the updates for SLSA compliance verification

**Comment by godofredoc** [comment]
\cc @drewroengoogle would you like to work on this?

**Comment by godofredoc** [comment]
@khyati82 should we create a github project to start adding bugs tracking SLSA L3 for Flutter?

**Comment by drewroengoogle** [comment]
Yeah I think this would be a good project to pick up! I'll start taking a look

**Comment by khyati82** [comment]
I have created https://github.com/orgs/flutter/projects/55/views/1.
@drewroengoogle - You can start adding issues to this github project for cocoon L3 compliance work. You & @godofredoc are both admins to the board. So you can also add collaborators.

**Comment by godofredoc** [comment]
@drewroengoogle can you please update?

**Comment by drewroengoogle** [comment]
Updated the initial description with the pieces that have been complete!

**Comment by godofredoc** [comment]
@drewroengoogle should we close this one?
