### ISSUE TITLE
[CP] fix for PlatformViews lingering on the screen after being scrolled away

### ISSUE THREAD

**Issue by flar** [flutter/flutter#116809]
### issue_link

https://github.com/gskinnerTeam/flutter-wonderous-app/issues/54

### Commit Hash

a259613ab871d301834205d2a4c8da3327d95250

### Target

beta

### pr_link

https://github.com/flutter/engine/pull/38163

### Impacted Users

Flutter developers using PlatformViews

### Impact Description

PlatformViews are not disposed and linger on the screen if they scroll off of it. They will disappear if the app removes them from the layer tree it generates, but if the view was simply scrolled off the screen and is still present in the frame description due to scrolling cache extents or because the developer simply does not cull the view from the widgets, then it will linger in its last on-screen position.

### Workaround

The developers could aggressively remove the platform view from their widget trees, but scrolling tends to rely on some near-off-screen persistence due to cache extents.

### Risk

low

### Test Coverage

yes

### Validation Steps

The unit tests already verify that the fix works, but the linked issue describes reproducible steps.

**Comment by zanderso** [comment]
CP lgtm
