### ISSUE TITLE
`flutter` tool depends on urls which are not always available in China

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#11681]
This is an oft reported problem.  Making this meta-bug to coalesce reports.

**Comment by eseidelGoogle** [comment]
A common reported one is that android.googlesource.com is not reachable in China:
http://ping.chinaz.com/android.googlesource.com.
However at least one report: https://github.com/flutter/flutter/issues/11674 notes that it's reachable via https from Chrome.

**Comment by lyrachord** [comment]
That the site is accessible in chrome may owes much to its extensions of CDN-url-rewrite like

**Comment by lishuhao** [comment]
@eseidelGoogle 
` it's reachable via https from Chrome`
Maybe his chrome use proxy but terminal not use proxy.

**Comment by phyooos** [comment]
@lishuhao  You are right.
1. brew install polipo
2.export http_proxy=http://localhost:8123
   export https_proxy=http://localhost:8123

OK.!
http://www.jianshu.com/p/32dfb5289cf5

**Comment by InMatrix** [comment]
It appears that Flutter Tools call android.googlesource.com in this file: https://github.com/flutter/flutter/blob/c5999c74c06cf33d69c55cf23e0c952144632178/packages/flutter_tools/lib/src/cache.dart#L387

**Comment by wangliangrc** [comment]
A hacky solution: http://blog.csdn.net/xjwangliang/article/details/78042740

**Comment by eseidelGoogle** [comment]
We've now had 7 dupes of this bug, which may be a record. :/

**Comment by change2hao** [comment]
A simple solution:use **tunnelbear** ,the website:<https://www.tunnelbear.com>, install it and select UnitedStates. It works

**Comment by lyrachord** [comment]
@eseidelGoogle seems flutter like kotlin, blooming in China.
Indeed, another example is eclipse on which same cases occur when updating.  The fact depicts no more cares at eclipse.

Maybe flutter's integrality checking should be a loose spec so that let user handle it by himself according to the spec.

**Comment by liyinyin** [comment]
@change2hao Thanks，it works！

**Comment by InMatrix** [comment]
To summarize the workaround described in http://blog.csdn.net/xjwangliang/article/details/78042740 in English for the Flutter team, here is what the author did: 

- Download https://android.googlesource.com/platform/tools/base/+archive/0b5c1398d1d04ac245a310de98825cb7b3278e2a/templates/gradle/wrapper.tgz via browser. 
- Uncompress the tgz file to flutter/bin/cache/artifacts/gradle_wrapper
- Create gradle_wrapper.stamp in flutter/bin/cache/，and write `0b5c1398d1d04ac245a310de98825cb7b3278e2a` in it.

**Comment by InMatrix** [comment]
It looks like the packages on pub.dartlang.org, though not the website itself, is also blocked in China, which is previously reported here: https://github.com/dart-lang/pub/issues/780

**Comment by InMatrix** [comment]
Homebrew is also blocked in China, but there are mirrors: https://lug.ustc.edu.cn/wiki/mirrors/help/brew.git

**Comment by lokimx88** [comment]
could anyone send me that file ?  We canot use any VPN now.

e8aa40eddd3b91ba1a2d0c2c1e34db0f38e4290e

**Comment by eseidelGoogle** [comment]
I've asked @mravn-google to take a look at wiring up an alternative download location for wrapper.tgz, which is the most common failure.  We're currently investigating options.  Until then, workarounds are listed in earlier comments.

**Comment by InMatrix** [comment]
If you're following this issue from China, would you please try [these instructions](https://github.com/flutter/flutter/wiki/Using-Flutter-in-China) about using Flutter in China and let us know if they work for you? When you report your test results, please include your OS and province. Thanks!

**Comment by lyrachord** [comment]
It works fine. 
From CQ.
```cmd
Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
Downloading Material fonts...                        20.0s
Downloading package sky_engine...                    17.3s
Downloading common tools...                          37.2s
Downloading windows-x64 tools...                     181.9s
Downloading windows-x64 tools...                     140.7s
Downloading android-arm-profile/windows-x64 tools...  6.2s
Downloading android-arm-release/windows-x64 tools... 15.5s
Downloading android-x86 tools...                     32.4s
Downloading android-x64 tools...                     112.1s
Downloading android-arm tools...                     37.1s
Downloading android-arm-profile tools...             12.9s
Downloading android-arm-release tools...             17.6s
Downloading Gradle Wrapper...                        11.0s
[√] Flutter (on Microsoft Windows [Version 10.0.16299.64], locale zh-CN, channel master)
    • Flutter at D:\dart\flutter
    • Framework revision 3d2c214da3 (2 minutes ago), 2017-12-11 00:25:03 +0800
    • Engine revision edb0201fa2
    • Tools Dart version 1.25.0-dev.11.0
    • Engine Dart version 2.0.0-edge.a38ac7cf127f4611c873c2f2d523c06ce06b1342

[√] Android toolchain - develop for Android devices (Android SDK 27.0.0)
    • Android SDK at D:\android\SDK
    • Android NDK at D:\android\SDK\ndk-bundle
    • Platform android-27, build-tools 27.0.0
    • ANDROID_HOME = D:\android\SDK
    • Java binary at: C:\work\android\3.0\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] Android Studio (version 3.0)
    • Android Studio at C:\work\android\3.0
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] Android Studio (version 3.0)
    • Android Studio at C:\work\android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] IntelliJ IDEA Community Edition (version 2017.2)
    • Flutter plugin version 17.0
    • Dart plugin version 172.4155.35

[√] IntelliJ IDEA Community Edition (version 2017.3)
    • Flutter plugin version 19.1
    • Dart plugin version 173.3622.29

[-] Connected devices
    • None
```

BTW it seems there is a typo, x86?
```cmd
Downloading windows-x64 tools...                     181.9s
Downloading windows-x64 tools...                     140.7s
```

**Comment by InMatrix** [comment]
Thanks for testing. I'm closing this issue, since I've got multiple confirmations.

**Comment by yy1300326388** [comment]
我是这样做的
**flutter_gallery/pubspec.yaml**
```java
flutter_gallery_assets:
   git:
  #   url: https://flutter.googlesource.com/gallery-assets
     url: https://github.com/yy1300326388/gallery-assets-china
````
改变 url 为`https://github.com/yy1300326388/gallery-assets-china`
我会持续更新，并且 commit id 不会变，直接同步的 [https://flutter.googlesource.com/gallery-assets/](https://flutter.googlesource.com/gallery-assets/)的

> 看来大家都用的不错，记得点个Star [gallery-assets-china](https://github.com/yy1300326388/gallery-assets-china)

**Comment by peakcool** [comment]
@yy1300326388 Hi, I didn't find `flutter_gallery / pubspec.yaml` from the file.Can you help me?

**Comment by yy1300326388** [comment]
@peakcool 
[https://github.com/flutter/flutter/tree/master/examples/flutter_gallery](https://github.com/flutter/flutter/tree/master/examples/flutter_gallery)
