### ISSUE TITLE
[pigeon] Add documentation comment support for Enum members.

### ISSUE THREAD

**Issue by mgkdev** [flutter/flutter#116835]
## Use case

Currently, no documentation comments are generated for Enum members.

input dart

```
enum EnumState {
  /// Documentation comments for Pending
  Pending,
  /// Documentation comments for Success
  Success,
  /// Documentation comments for Error
  Error,
}
```

output(generated) dart

```
enum EnumState {
  Pending,
  Success,
  Error,
}
```

The expected behavior is as follows

```
enum EnumState {
  /// Documentation comments for Pending
  Pending,
  /// Documentation comments for Success
  Success,
  /// Documentation comments for Error
  Error,
}
```

## Proposal

- Add parsing support for Enum member documentation comment.
- Add Enum member documentation generation support for code generators (dart,java,objc,cpp,kotlin,swift).

Patch: https://github.com/flutter/packages/compare/main...mgkdev:flutter-packages:pigeon-add-doc-comment-support-for-emum-members

**Comment by tarrinneal** [comment]
Closing as complete as of https://github.com/flutter/packages/pull/2924
