### ISSUE TITLE
[go_router] The history not replace when context.replace('/details')

### ISSUE THREAD

**Issue by JDongKhan** [flutter/flutter#116873]
I run according to the code in example and change context.go('/details') to context.replace('/details'), then the chrome can pop when  press back button.

![2](https://user-images.githubusercontent.com/4929805/206986063-3f779897-0cc0-4abf-b1f4-2fd7504a2f2d.png)

https://user-images.githubusercontent.com/4929805/206986078-028e254e-31ad-4d0e-8415-72f1a73906ee.mov

go_router: ^5.2.0

[✓] Flutter (Channel stable, 3.3.9, on macOS 13.0 22A380 darwin-x64, locale zh-Hans-CN)
    • Flutter version 3.3.9 on channel stable at /Users/xx/fvm/versions/3.3.9
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b8f7f1f986 (3 weeks ago), 2022-11-23 06:43:51 +0900
    • Engine revision 8f2221fbef
    • Dart version 2.18.5
    • DevTools version 2.15.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

**Comment by darshankawar** [comment]
@JDongKhan 
I didn't completely get as what's the exact issue are you trying to report, so can you elaborate with actual vs expected behavior along with code sample ?
