### ISSUE TITLE
Flutter could provide a doNothing method to help with readability

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#11699]
It would be nice if apps had access to a default doNothing method in the same import that provides StatefulWidget.

```dart
void doNothing() {}
```

Rationale:

This is pretty common code in apps:

```dart
  setState(() {});
```

Less common, but still happens because tap handlers are required, especially in tests:

```dart
  new SomeAction(
     label: 'Do nothing'
     onTap: () {}
  );
```

With the exposure of a default doNothing method, we get:

```dart
setState(doNothing);

new SomeAction(
    label: 'Do nothing'
    onTap: doNothing,
);
```

As a bonus, we also save a tiny bit of performance since every () {} creates a new Function object. Probably not memory since that is essentially free.

@Hixie  What do you think?

Another alternative is to not require an argument to setState (or default it to doNothing) and do the same thing for the actions. I don't prefer that since there's value in emphasizing that these arguments are important and should be explicitly set to do nothing.

**Comment by Hixie** [comment]
> ```dart
>   setState(() {});
> ```

This violates the style guide. You should call setState with the state that you are setting, or, if you really can't for some reason, you should call it with a closure that contains a comment that explains what state is being set.

This avoids a tendency to pepper setState around "on principle" to "make it work".

> ```dart
>   new SomeAction(
>      label: 'Do nothing'
>      onTap: () {}
>   );
> ```

If this is common in production code this seems like a bug. Why would `SomeAction` require an argument even if it does nothing? I don't really understand.

For tests, performance at this level is not a concern.

**Comment by mehmetf** [comment]
Theoretically yes. In real life, it is not so much cut and dry. Many times we use setState() as a way of `markDirty()`. It isn't just to "make it work" either.

Examples:
- Your state might be changing elsewhere. Imagine you are doing form validation via a separate validator class. Your code might look like:
```dart
  var errorFound = validator.validate(fields);
  if (errorFound) {
    setState(() {});
  }
```
because you want to mark the form dirty to render any potential error messages. It is nice not to care about what exactly changed since your build() code should take care of that anyway.

- You might have a stream of changes you are subscribing to and you want to re-render the page on _something_ changing. Again, you might not necessarily know what changed:

```dart
    _selection.selectionChanges.listen((_) {
      setState(() {});
    });
```

or subscribing to model state changes:

```dart
    store.subscribe(() {
      setState(() {});
    });
```

We could change some of these to look like the following:

```dart
   setState(() {
      validator.validate(fields);
   });
```

This is neither practical nor readable. In general I am a big fan of code order = execution order (one of the reasons I love dart async/await pattern). I would like to say: "validate first, then mark dirty if some error was found". That, to me, is more readable than the code above.

or we could explicitly return the errors and set that:
```dart
var errors = validator.validate(fields);
setState(() {
  field1Error = errors['field1'];
  field2Error = errors['field2'];
});

again, not practical nor readable.

```dart
    _selection.selectionChanges.listen((newValue) {
      setState(() {
         currentValue = newValue;
      });
    });
```

This is _sometimes_ practical, sometimes not. I also like the principle of single source of truth. I would like my build() code to not use local state (such as `currentValue`) but refer to _selection or _model directly.  Anyway, this is not a huge deal. I am find with using () {} for these scenarios and doing a comment inside sounds like good practice. However, I wanted to highlight that there are legitimate common scenarios for not having a particular state to set.

For the second one, I agree. This particular scenario happens when you can get the action result in two different ways. The specific example is the undo action on a snackbar. Its `onTap()` is required at the moment but you can also await on the snackbar result and see if it was closed due to action (which is what we prefer to do) hence a no-op for onTap. Perhaps it is worth opening an issue just for that.

**Comment by Hixie** [comment]
> ```dart
>   var errorFound = validator.validate(fields);
>   if (errorFound) {
>     setState(() { /* The state is stored in the validator.message property */ });
>   }
> ```

> ```dart
>     _selection.selectionChanges.listen((_) {
>       setState(() { /* build method depends on _selection.foo and _selection.bar */ });
>     });
> ```

> ```dart
>     store.subscribe(() {
>       setState(() { /* build method depends on the entirety of store's state */ });
>     });
> ```

> The specific example is the undo action on a snackbar. Its `onTap()` is required at the moment but you can also await on the snackbar result and see if it was closed due to action (which is what we prefer to do) hence a no-op for onTap. Perhaps it is worth opening an issue just for that.

That seems like it would trigger a bug. What if the user taps undo, then does something that means the snackbar never goes away, e.g. bringing up a dialog or exiting the app?

**Comment by mehmetf** [comment]
I tried to reproduce what you said but it was quite hard to get the timing just right to be able to close the app before the 300ms animation completes.

The proper way to fix this would be to support undo operation all the way in the backend but that's not practical in most scenarios. So what apps typically do is:
- Do change locally.
- Show toast with undo.
- Only submit change if undo is _not_ clicked.

If the snackbar never goes away, the change is never submitted. We are okay with that if it happens less than 1% of the time. Do you foresee a different easily reproducible scenario where snackbar never goes away? Also what happens if I bring up a dialog? Does that freeze all the animations underneath, is that why snackbar does not go away?

**Comment by Hixie** [comment]
You can set the timeDilation factor to 100.0 or some such if you want to reproduce it more easily.

> Do you foresee a different easily reproducible scenario where snackbar never goes away?

Sure. Something I often do as a user is as soon as I've submitted something and received confirmation (the snackbar), I close the app.

> Also what happens if I bring up a dialog?

IIRC the Material spec requires that snackbars not go away while there's a dialog on top.

**Comment by mehmetf** [comment]
Closing in preference to following style guide.
