### ISSUE TITLE
Since last roll of engine the keyboard don't open up anymore :/

### ISSUE THREAD

**Issue by Alexays** [flutter/flutter#11690]
## Steps to Reproduce

Since last roll of engine the keyboard don't open up anymore :/
Just add an input and click on it, the keyboard will don't show up

## Logs

Run your application with `flutter run` and attach all the log output.

Launching lib/main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...                                0.8s
Resolving dependencies...                             4.2s
Running 'gradlew assembleDebug'...                    4.7s
Built build/app/outputs/apk/app-debug.apk (23.0MB).
Syncing files to device Android SDK built for x86...      
D/EGL_emulation( 3755): eglCreateContext: 0x998f5100: maj 2 min 0 rcv 2
D/EGL_emulation( 3755): eglMakeCurrent: 0x998f5100: ver 2 0 (tinfo 0x9996cce0)
D/EGL_emulation( 3755): eglMakeCurrent: 0x998f5100: ver 2 0 (tinfo 0x9996cd10)

🔥  To hot reload your app on the fly, press "r". To restart the app entirely, press "R".
An Observatory debugger and profiler on Android SDK built for x86 is available at: http://127.0.0.1:8102/
For a more detailed help message, press "h". To quit, press "q".

Run `flutter analyze` and attach any output of that command also.

Analyzing /home/rouill_a/Project/Spotitems...
No issues found!
Ran in 8.0s

## Flutter Doctor

Paste the output of running `flutter doctor` here.

[✓] Flutter (on Linux, locale en_US.UTF-8, channel master)
    • Flutter at /home/rouill_a/bin/flutter
    • Framework revision 4ce8c94e0d (11 hours ago), 2017-08-18 13:37:31 -0700
    • Engine revision a246501917
    • Tools Dart version 1.25.0-dev.11.0

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.1)
    • Android SDK at /opt/android-sdk
    • Platform android-26, build-tools 26.0.1
    • ANDROID_HOME = /opt/android-sdk
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] Android Studio (version 2.3)
    • Android Studio at /opt/android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] Connected devices
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 7.0 (API 24) (emulator)

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by Hixie** [comment]
Does this only happen on emulator?
What app were you using to test this? Does it work in the Flutter Gallery demo app?

**Comment by Alexays** [comment]
It's also happen on my phone :/
But hmm it's working in the gallery app.
In this case why in my app the keyboard show up when i'm on the alpha channel but not on master :?
I will check why, thx

**Comment by Hixie** [comment]
Interesting that it works in the gallery app.

If you learn anything about what might be causing this please do let us know. We are eager to make sure this works!

**Comment by Alexays** [comment]
Hmm ok it works in gallery app, but i created new project, paste this in Build
`new TextFormField(
          decoration: const InputDecoration(
            icon: const Icon(Icons.person),
            hintText: 'What do people call you?',
            labelText: 'Name *',
          ),
        )`
and keyboard don't show up when focus it.

**Comment by Alexays** [comment]
any idea @Hixie ?

**Comment by Hixie** [comment]
I can confirm that this worked at 0799ff5b6c8714b91b752ab2bd8ddb163f72ed44 and doesn't
on the next commit which is 2e57189aa47285b191552efe845446236ade6093.

**Comment by Hixie** [comment]
cc @cbracken since you've worked on text input before
cc @xster since you have commits in the window
cc @jason-simmons since you're amazing at tracking down regressions

**Comment by jason-simmons** [comment]
This is caused by the introduction of a FrameLayout to provide a splash screen in https://github.com/flutter/engine/commit/f187a5c219623ce06f86a95e4527ed522a02bbf6

For now, you can work around this by changing the `io.flutter.app.android.SplashScreenUntilFirstFrame` value to `false` in the activity's manifest

@xster

**Comment by jason-simmons** [comment]
One option for fixing this in the engine would be removing the launchView from the FrameLayout in the onFirstFrame listener (instead of replacing the activity's content view with the FlutterView).

That appears to cause the window insets callback to be dispatched to the FlutterView as expected

**Comment by xster** [comment]
Will check
