### ISSUE TITLE
Can we target  scroll widget? 

### ISSUE THREAD

**Issue by rabinacharya11** [flutter/flutter#116925]
Hi Flutter team, 
What an amazing framework built!! 

Recently, I was developing a socio-commerce application. In that application, I had the following

## Use case
 
1. The app has to get notifications of user comments,  reviews, orders, and likes.  
2. The client wanted me to implement :   
i.  When onTap on the list tile of the notification, the user should be sent to the respective widget ( the widgets are not static ) with a smooth scrolling effect.

## Proposal

I want flutter team to  implement this feature ( if its not already existing or being worked upon )

**Comment by darshankawar** [comment]
Thanks for the report @rabinacharya11 
We understand that you want to implement the use case you mentioned above, but proposing to have that in the framework for a specific use case is not feasible. You can check in pub.dev if there's already a plugin which offers this feature you are proposing or if you know how to implement that, feel free to create a plugin yourself that will be helpful for the community as well which can be used by them as needed.
I also suggest you to ask this question / proposal on support channels like StackOverflow where you can get existing solutions on implementing the proposal.

Based on above, I am going ahead and closing this issue.
