### ISSUE TITLE
After upgrading from 3.0.3 to 3.3.8, the 'Flutter/Flutter.h' file was not found

### ISSUE THREAD

**Issue by nepaul** [flutter/flutter#116960]
The same issue as https://github.com/flutter/flutter/issues/115619 (auto closed by the bot).

**Comment by darshankawar** [comment]
@nepaul 
The issue you linked was related to add2app. Is your case same or only with standalone Flutter app ?
In either case, would be good to get complete / verbose error log along with a sample repo that we can clone to verify this behavior.

**Comment by iapicca** [comment]
> > Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now.
> > If you find this problem please file a new issue with the same description, what happens, logs and the output of 'flutter doctor -v'. All system setups can be slightly different so it's always better to open new issues and reference the related ones.
> > Thanks for your contribution.
>
> The same issue as #115619 (auto closed by the bot).

@nepaul 
the bot closed it because missing info
I'm not sure reopening the issue without proving the required info would have any different outcome

**Comment by darshankawar** [comment]
> would be good to get complete / verbose error log along with a sample repo that we can clone to verify this behavior.

@nepaul 
Please provide these details so as to make the issue actionable.

**Comment by rexthecoder** [comment]
@darshankawar Our team has also been experiencing the same issue. 

Error (Xcode): 'Flutter/Flutter.h' file not found.
Error (Xcode): failed to emit precompiled header 

The issue started this week, sometimes, Xcode will build successfully but after the next try, it will throw an error.

**Comment by nepaul** [comment]
@darshankawar @iapicca 

- flutter doctor -v
```
[✓] Flutter (Channel stable, 3.3.9, on macOS 13.1 22C65 darwin-arm, locale en-CN)
    • Flutter version 3.3.9 on channel stable at /Users/boni/Development/flutter-sdks/3.3.9
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b8f7f1f986 (3 weeks ago), 2022-11-23 06:43:51 +0900
    • Engine revision 8f2221fbef
    • Dart version 2.18.5
    • DevTools version 2.15.0
```

- Xcode: Version 14.2 (14C18)
- pod Version: 1.11.3

- Podfile
```
flutter_application_path = '../flutter_module/'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_post_install(installer) if defined?(flutter_post_install)
    if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
      target.build_configurations.each do |config|
          config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
      end
    end
  end
end

target 'Production' do
  install_all_flutter_pods(flutter_application_path)
end
```

## Error
![image](https://user-images.githubusercontent.com/1112181/207791448-ac0c500e-1ff7-4772-92fb-4c10584707d8.png)


Before 3.3, in `Development Pods/Flutter` is 
![image](https://user-images.githubusercontent.com/1112181/207790996-870acf88-8e59-486f-9af0-e3e945fec8ac.png)
But now is 
![image](https://user-images.githubusercontent.com/1112181/207791267-5c8f5ec4-8080-4993-8204-558843c5e098.png)

**Comment by darshankawar** [comment]
@nepaul 
Can you provide complete error log in verbose mode ? ie, `flutter run -v` so that we can go through the log properly ?

Also, in your podfile, I don't see below entry, ie `flutter_additional_ios_build_settings` as below:

```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
```

Try the same and see if it helps in your case.

**Comment by nLoser** [comment]
@nepaul Hi, I have also the same issue after upgrading from 2.5.3 to 3.3.2. performed the update  according to the [Doc option A](https://docs.flutter.dev/development/add-to-app/ios/project-setup) . 
Have you solved it? I implore your help

**Comment by nLoser** [comment]
@nepaul I have fixed the problem I encountered. The iOS dependency library in question is dependent on the Flutter framework. I use the Flutter plugin to wrap it, so it is fine.

**Comment by prolificcoder** [comment]
@darshankawar I ran `flutter run -v` and was able to compile and run the iOS app with no problems. I am attaching the logs anyways, not sure if they would be any useful. 



We also got a different small set of repro steps

1. fvm global 3.3.0 (or 3.3.8)
2. inside app_module, run flutter clean
3. run flutter pub get
4. Notice no engine inside app_module/.ios/Flutter
5. Now run fvm global 3.0.1
 6. flutter clean
7. flutter pub get
8. Notice that engine is there

Also note that this issue won't happen for 3.0.5 and the engine is created as expected.

**Comment by darshankawar** [comment]
Thanks for the details @prolificcoder 
I looked at the verbose log but it doesn't have any noteworthy error log, so can't conclude anything from it.
I see that you are using `fvm` package to install sdk. `fvm` is third party to flutter, so I suggest you to try using the standalone flutter installation as mentioned in the official document and see if using it and following the steps to replicate you mentioned above, you still get the same error or not.

**Comment by prolificcoder** [comment]
@darshankawar thanks for the response. Our issue turned out to be different. We customized the podhelper.rb and the locatino of the flutter engine changed.

**Comment by shingohu** [comment]
> flutter_post_install

This configuration is not required in the document description

https://flutter.cn/docs/development/add-to-app/ios/project-setup#option-a---embed-with-cocoapods-and-the-flutter-sdk
