### ISSUE TITLE
Engine -> Framework roll failing on Dart trace event change

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#116910]
flutter/dev/tracing_tests/test/image_painting_event_test.dart is failing repeatedly in https://github.com/flutter/flutter/pull/116907 from the new field `__destinationStream` in the trace event.

https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20framework_tests_slow/2576/overview
https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20framework_tests_slow/2571/overview

Guessing it's from the Dart roll https://github.com/flutter/engine/pull/38187 and maybe from https://dart.googlesource.com/sdk.git/+/4981cbffe2f66db3a0cc8eced18085e03fbbb8ba

@bkonyi

**Comment by zanderso** [comment]
cc @christopherfujino in case the test needs to be updated.

**Comment by zanderso** [comment]
Looks like the change in Dart was reverted at https://dart-review.googlesource.com/c/sdk/+/274802. Leaving this open to monitor the rolls recovering.

**Comment by bkonyi** [comment]
FYI @CoderDake

**Comment by CoderDake** [comment]
Thanks for bringing this to my attention @bkonyi 

Sorry about this breaking your tests, You are correct that the change was reverted this morning.
It was my fault that the revert didn't go through on Friday when it should have.

Is there anything I can do to help with this as the revert stands?

**Comment by zanderso** [comment]
The forward fix worked, and the roll has landed https://github.com/flutter/flutter/pull/116920
