### ISSUE TITLE
TextField hint text does not match material placeholder text

### ISSUE THREAD

**Issue by chunhtai** [flutter/flutter#116993]
b/262226740

For A11Y, hint text should not be read after user started typing data, while label should.

Consider input:

Label: Amount to pay
hint text : 0.00
Expected: When it is empty, talkback would read "Text Field, Amount to pay, example zero dot zero zero, is editing" While not empty with 1.5 "Text Field, Amount to pay, one dot five, is editing"

We also need to make sure the coloring and styling of the hint text match the guideline

**Comment by chunhtai** [comment]
we also need to make sure the accessibility announce the placeholder correctly

**Comment by chunhtai** [comment]
asking internal client for clarifying.

**Comment by hangyujin** [comment]
The a11y issue is duplicated to https://github.com/flutter/flutter/issues/114511 and it's fixed.
