### ISSUE TITLE
[CP] Correct sampler order for shaders compiled for MTL/impeller

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#116921]
### issue_link

https://github.com/flutter/flutter/issues/116610

### Commit Hash

3140ad924dc32126b4d07ccfe0b06d0ae9746839

### Target

beta

### pr_link

https://github.com/flutter/engine/pull/38228

### Impacted Users

Impeller/Shaders

### Impact Description

Shaders that declare multiple samplers will not work correctly when targeting impeller

### Workaround

Conditionally re-order samplers in code based on impeller

### Risk

low

### Test Coverage

yes

### Validation Steps

Run unit tests in PR

**Comment by itsjustkevin** [comment]
@zanderso

**Comment by zanderso** [comment]
CP lgtm
