### ISSUE TITLE
[impellerc] add shader define for Y coordinate scale

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#116901]
For example, something like FLUTTER_Y_AXIS_SCALE. to be used by shaders to determine opengl vs metal/vulkan y-axis

**Comment by chinmaygarde** [comment]
Today, we are using uniforms passed in to the appropriate shaders to achieve this. For instance, `texture_sampler_y_coord_scale` in `texture_fill.vert`.

Not sure how valuable having a shader define would be be since it's hard to image how a flip could be applied without context.

**Comment by chinmaygarde** [comment]
Also, Vulkan applies the y-axis flip using negative viewports from VK_KHR_maintenance1. So Vulkan behaves just like Metal.
