### ISSUE TITLE
[CP] [Windows] Fix headless mode crash

### ISSUE THREAD

**Issue by loic-sharma** [flutter/flutter#116932]
### issue_link

https://github.com/flutter/flutter/issues/116753

### Commit Hash

https://github.com/flutter/engine/commit/2148fc003077f611bdf668e3631ad7f9b763333a

### Target

beta

### pr_link

https://github.com/flutter/engine/pull/38233

### Impacted Users

Windows developers that use headless mode.

### Impact Description

Flutter Windows crashes immediately if it started in headless mode.

### Workaround

Yes. The crash is caused due to incorrectly handling no Dart entry point. This can be circumvented by providing an empty entry point manually.

### Risk

low

### Test Coverage

yes

### Validation Steps

Verify that a Windows Flutter app does not crash if it has no Dart entry point.

**Comment by itsjustkevin** [comment]
@HansMuller could you look at this cherry-pick?

**Comment by HansMuller** [comment]
LGTM but I think @cbracken is the right person to sign off. Chris?

**Comment by cbracken** [comment]
Yep, we definitely want this. LGTM.
