### ISSUE TITLE
Compiling third_party/angle/src/compiler/translator/translator.BuildSPIRV.obj fails on Win10\MSVS2022Pro

### ISSUE THREAD

**Issue by aykutkilic-avl** [flutter/flutter#116966]
## Steps to Reproduce

On a MSVS 2022 Pro / Windows 10 system:
1. Check out latest version of flutter in `\engine\src\flutter` my commit# `47417ce`
2. run `gclient sync` in `\engine\src\`
3. run `python flutter\tools\gn --unoptimized`
4. run `ninja -C out\host_debug_unopt`

## Logs

<details>
<summary>Logs</summary>

```
```

```
```

</details>

```
FAILED: obj/third_party/angle/src/compiler/translator/translator.OutputSPIRV.obj
ninja -t msvc -e environment.x64 -- ../../buildtools/windows-x64/clang/bin/clang-cl.exe  /nologo /showIncludes @obj/third_party/angle/src/compiler/translator/translator.OutputSPIRV.obj.rsp /c ../../third_party/angle/src/compiler/translator/OutputSPIRV.cpp /Foobj/third_party/angle/src/compiler/translator/translator.OutputSPIRV.obj /Fdobj/third_party/angle/translator_cc.pdb
In file included from ../../third_party/angle/src/compiler/translator/OutputSPIRV.cpp:9:
In file included from ../../third_party/angle/src\compiler/translator/OutputSPIRV.h:12:
In file included from ../../third_party/angle/src\compiler/translator/Compiler.h:17:
In file included from ../../third_party/angle/include\GLSLANG/ShaderVars.h:13:
In file included from C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.34.31933\include\algorithm:11:
In file included from C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.34.31933\include\xmemory:13:
In file included from C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.34.31933\include\limits:16:
C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.34.31933\include\xstddef(106,55): error: invalid operands to binary expression ('const sh::SpirvType' and 'const sh::SpirvType')
        noexcept(noexcept(_Fake_copy_init<bool>(_Left == _Right))) /* strengthened */ {
                                                ~~~~~ ^  ~~~~~~
../../third_party/abseil-cpp\absl/container/internal/raw_hash_set.h(975,68): note: in instantiation of exception specification for 'operator()' requested here
  auto KeyTypeCanBeEq(const Eq& eq, const key_type& k) -> decltype(eq(k, k));
                                                                   ^
../../third_party/abseil-cpp\absl/container/internal/raw_hash_map.h(31,29): note: in instantiation of template class 'absl::container_internal::raw_hash_set<absl::container_internal::FlatHashMapPolicy<sh::SpirvType, sh::SpirvTypeData>, sh::SpirvTypeHash, std::equal_to<sh::SpirvType>, std::allocator<std::pair<const sh::SpirvType, sh::SpirvTypeData>>>' requested here
class raw_hash_map : public raw_hash_set<Policy, Hash, Eq, Alloc> {
                            ^
../../third_party/abseil-cpp\absl/container/flat_hash_map.h(113,30): note: in instantiation of template class 'absl::container_internal::raw_hash_map<absl::container_internal::FlatHashMapPolicy<sh::SpirvType, sh::SpirvTypeData>, sh::SpirvTypeHash, std::equal_to<sh::SpirvType>, std::allocator<std::pair<const sh::SpirvType, sh::SpirvTypeData>>>' requested here
class flat_hash_map : public absl::container_internal::raw_hash_map<
                             ^
../../third_party/angle/src\compiler/translator/BuildSPIRV.h(496,61): note: in instantiation of template class 'absl::flat_hash_map<sh::SpirvType, sh::SpirvTypeData, sh::SpirvTypeHash, std::equal_to<sh::SpirvType>>' requested here
    angle::HashMap<SpirvType, SpirvTypeData, SpirvTypeHash> mTypeMap;
                                                            ^
1 error generated.
[62/4126] CXX obj/out/host_debug_unopt/gen/third_party/dart/runtime/observatory/embedded_observatory_archive.embedded_archive_observatory.obj
ninja: build stopped: subcommand failed.
```

**Comment by huycozy** [comment]
Hi @aykutkilic-avl, can you confirm you have already set up the necessary things (environment variables, debugging tools, Python27, etc) as indicated at [compiling-for-windows](https://github.com/flutter/flutter/wiki/Compiling-the-engine#compiling-for-windows)?

**Comment by x64bugreport** [comment]
> Hi @aykutkilic-avl, can you confirm you have already set up the necessary things (environment variables, debugging tools, Python27, etc) as indicated at [compiling-for-windows](https://github.com/flutter/flutter/wiki/Compiling-the-engine#compiling-for-windows)?

Hi, I have the same problem bothering me!
Environment: vs2022+win11

**Comment by x64bugreport** [comment]
J:\deskstop\flutter-engine\engine\src>ninja -C out\host_debug_unopt -j 6
ninja: Entering directory `out\host_debug_unopt'
[442/1909] CXX obj/third_party/angle/src/compiler/translator/translator.BuildSPIRV.obj
FAILED: obj/third_party/angle/src/compiler/translator/translator.BuildSPIRV.obj
ninja -t msvc -e environment.x64 -- ../../buildtools/windows-x64/clang/bin/clang-cl.exe  /nologo /showIncludes @obj/third_party/angle/src/compiler/translator/translator.BuildSPIRV.obj.rsp /c ../../third_party/angle/src/compiler/translator/BuildSPIRV.cpp /Foobj/third_party/angle/src/compiler/translator/translator.BuildSPIRV.obj /Fdobj/third_party/angle/translator_cc.pdb
In file included from ../../third_party/angle/src/compiler/translator/BuildSPIRV.cpp:9:
In file included from ../../third_party/angle/src\compiler/translator/BuildSPIRV.h:12:
In file included from ../../third_party/angle/src\common/FixedVector.h:13:
In file included from ../../third_party/angle/src\common/debug.h:17:
In file included from C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.34.31933\include\mutex:16:
In file included from C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.34.31933\include\__msvc_chrono.hpp:12:
In file included from C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.34.31933\include\limits:16:
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.34.31933\include\xstddef(106,55): error: invalid operands to binary expression ('const sh::SpirvType' and 'const sh::SpirvType')
        noexcept(noexcept(_Fake_copy_init<bool>(_Left == _Right))) /* strengthened */ {
                                                ~~~~~ ^  ~~~~~~
../../third_party/abseil-cpp\absl/container/internal/raw_hash_set.h(976,71): note: in instantiation of exception specification for 'operator()' requested here
  auto KeyTypeCanBeEq(const Eq& eqarg, const key_type& k) -> decltype(eqarg(k, k));
                                                                      ^
../../third_party/abseil-cpp\absl/container/internal/raw_hash_map.h(31,29): note: in instantiation of template class 'absl::container_internal::raw_hash_set<absl::container_internal::FlatHashMapPolicy<sh::SpirvType, sh::SpirvTypeData>, sh::SpirvTypeHash, std::equal_to<sh::SpirvType>, std::allocator<std::pair<const sh::SpirvType, sh::SpirvTypeData>>>' requested here
class raw_hash_map : public raw_hash_set<Policy, Hash, Eq, Alloc> {
                            ^
../../third_party/abseil-cpp\absl/container/flat_hash_map.h(113,30): note: in instantiation of template class 'absl::container_internal::raw_hash_map<absl::container_internal::FlatHashMapPolicy<sh::SpirvType, sh::SpirvTypeData>, sh::SpirvTypeHash, std::equal_to<sh::SpirvType>, std::allocator<std::pair<const sh::SpirvType, sh::SpirvTypeData>>>' requested here
class flat_hash_map : public absl::container_internal::raw_hash_map<
                             ^
../../third_party/angle/src\compiler/translator/BuildSPIRV.h(496,61): note: in instantiation of template class 'absl::flat_hash_map<sh::SpirvType, sh::SpirvTypeData, sh::SpirvTypeHash, std::equal_to<sh::SpirvType>>' requested here
    angle::HashMap<SpirvType, SpirvTypeData, SpirvTypeHash> mTypeMap;
                                                            ^
1 error generated.
[447/1909] CXX obj/third_party/angle/src/compiler/translator/translator.ResourcesHLSL.obj
ninja: build stopped: subcommand failed.

**Comment by x64bugreport** [comment]
J:\deskstop\flutter-engine\engine\src>set
ALLUSERSPROFILE=C:\ProgramData
APPCODE_VM_OPTIONS=D:\jetbrainspth\vmoptions\appcode.vmoptions
APPDATA=C:\Users\UserName\AppData\Roaming
ChocolateyInstall=C:\ProgramData\chocolatey
ChocolateyLastPathUpdate=132995467792227538
CLION_VM_OPTIONS=D:\jetbrainspth\vmoptions\clion.vmoptions
CommonProgramFiles=C:\Program Files\Common Files
CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
CommonProgramW6432=C:\Program Files\Common Files
COMPUTERNAME=DESKTOP-L9UV1C2
ComSpec=C:\WINDOWS\system32\cmd.exe
DATAGRIP_VM_OPTIONS=D:\jetbrainspth\vmoptions\datagrip.vmoptions
DATASPELL_VM_OPTIONS=D:\jetbrainspth\vmoptions\dataspell.vmoptions
DEPOT_TOOLS_WIN_TOOLCHAIN=0
DEVECOSTUDIO_VM_OPTIONS=D:\jetbrainspth\vmoptions\devecostudio.vmoptions
DriverData=C:\Windows\System32\Drivers\DriverData
EXPORT_ERRORLEVEL=0
GATEWAY_VM_OPTIONS=D:\jetbrainspth\vmoptions\gateway.vmoptions
GOLAND_VM_OPTIONS=D:\jetbrainspth\vmoptions\goland.vmoptions
GOPATH=C:\Users\UserName\go
GYP_MSVS_OVERRIDE_PATH=C:\Program Files\Microsoft Visual Studio\2022\Enterprise
GYP_MSVS_VERSION = 2022
HOMEDRIVE=C:
HOMEPATH=\Users\UserName
IDEA_VM_OPTIONS=D:\jetbrainspth\vmoptions\idea.vmoptions
JETBRAINSCLIENT_VM_OPTIONS=D:\jetbrainspth\vmoptions\jetbrainsclient.vmoptions
JETBRAINS_CLIENT_VM_OPTIONS=D:\jetbrainspth\vmoptions\jetbrains_client.vmoptions
LOCALAPPDATA=C:\Users\UserName\AppData\Local
LOGONSERVER=\\DESKTOP-L9UV1C2
NUMBER_OF_PROCESSORS=8
ONCE_PATH=D:\Codeexpander\resources\app\app\nodes;C:\Users\UserName\.codeexpander\installation\node_modules\.bin;D:\Codeexpander\resources\app\app\node_modules\.bin
OneDrive=C:\Users\UserName\OneDrive
OS=Windows_NT
Path=J:\deskstop\flutter-engine\depot_tools;D:\VMware\VMware Workstation\bin\;C:\Program Files\Python310\Scripts\;C:\Program Files\Python310\;C:\Windows\system32\WBEM;C:\Program Files\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\010 Editor;C:\Program Files\SafeNet\Authentication\SAC\x64;C:\Program Files\SafeNet\Authentication\SAC\x32;C:\Program Files\Microsoft SQL Server\150\Tools\Binn\;C:\Program Files\nodejs\;C:\ProgramData\chocolatey\bin;C:\Program Files\Go\bin;C:\Users\UserName\AppData\Local\Programs\Python\Python310\Scripts\;C:\Users\UserName\AppData\Local\Programs\Python\Python310\;C:\Users\UserName\.cargo\bin;D:\X64DBG\release\x64\Python27;C:\Users\UserName\AppData\Local\Microsoft\WindowsApps;D:\JetBrains\PyCharm\bin;C:\Users\UserName\.dotnet\tools;D:\Codeexpander\resources\app\app\nodes;C:\Users\UserName\.codeexpander\installation\node_modules\.bin;D:\Codeexpander\resources\app\app\node_modules\.bin;C:\Users\UserName\AppData\Roaming\npm;C:\Users\UserName\go\bin;C:\Users\UserName\AppData\Local\Programs\Fiddler;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Bandizip\;C:\Program Files\dotnet\;C:\Program Files\Git\cmd;C:\Program Files\BinDiff\bin;D:\flutter\bin;
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.PY;.PYW
PHPSTORM_VM_OPTIONS=D:\jetbrainspth\vmoptions\phpstorm.vmoptions
PROCESSOR_ARCHITECTURE=AMD64
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 158 Stepping 9, GenuineIntel
PROCESSOR_LEVEL=6
PROCESSOR_REVISION=9e09
ProgramData=C:\ProgramData
ProgramFiles=C:\Program Files
ProgramFiles(x86)=C:\Program Files (x86)
ProgramW6432=C:\Program Files
PROMPT=$P$G
PSModulePath=C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules
PUBLIC=C:\Users\Public
SystemDrive=C:
SystemRoot=C:\WINDOWS
TEMP=C:\Users\UserName\AppData\Local\Temp
TMP=C:\Users\UserName\AppData\Local\Temp
USERDOMAIN=DESKTOP-L9UV1C2
USERDOMAIN_ROAMINGPROFILE=DESKTOP-L9UV1C2
USERNAME=QI
USERPROFILE=C:\Users\UserName
windir=C:\WINDOWS
WINDOWSSDKDIR=C:\Program Files (x86)\Windows Kits\10

**Comment by x64bugreport** [comment]
J:\deskstop\flutter-engine\engine\src>python
Python 2.7.18 (v2.7.18:8d21aa21f2, Apr 20 2020, 13:25:05) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>

**Comment by x64bugreport** [comment]
Angle this library, compile error on vs2022, resulting in compilation failure.

**Comment by aykutkilic-avl** [comment]
> I use python 3.9.13 . I used to compile peacefully until now.

I checked again. `where python` returns:
```
C:\Users\****>where python
C:\****\depot_tools\python.bat
```

**Comment by aykutkilic-avl** [comment]
The commit used for angle is `094b49db60cb48ee932a875898b57accbfa656de`.
I've fetched and compiled this version and it succeeded on the very same system.
```
> fetch angle
> git checkout 094b49db60cb48ee932a875898b57accbfa656de
> gclient sync
> gn out/Debug
> ninja -C out/Debug
ninja: Entering directory `out\Debug'
[5383/5383] STAMP obj/all.stamp
```

**Comment by huycozy** [comment]
Thanks for updating more information. Labeling this issue for further investigation from the team.

**Comment by x64bugreport** [comment]
> 094b49db60cb48ee932a875898b57accbfa656de

Unfortunately, I switched the angle to 094b49db60cb48ee932a875898b57accbfa656de and still reported an error, unable to compile! ! !

**Comment by x64bugreport** [comment]
> Thanks for updating more information. Labeling this issue for further investigation from the team.

How long does it take for the flutter team to respond to this problem?

**Comment by yefl2064** [comment]
I have the same problem, did you solve this problem? @x64bugreport

**Comment by pbissonho** [comment]
Same problem here, any solution?

**Comment by chinmaygarde** [comment]
cc @loic-sharma for guidance on which version of MSVC we use on CI and if there is a regression with later versions.

Another curious observation, I am not sure why we are using libcxx from MSVC instead of using our own like on the other platforms. Microsoft changing their headers will cause us to run into issues like this and we have different behavior to boot. See the platforms that currently use our [own libcxx here](https://github.com/flutter/buildroot/blob/4be064f79905779f501e22d315f1782930561bcf/build/config/BUILDCONFIG.gn#L316).

**Comment by chinmaygarde** [comment]
@loic-sharma may have already fixed this on ToT in https://github.com/flutter/flutter/issues/117932. I'll let him chime in on this and the custom cxx observation.

**Comment by loic-sharma** [comment]
Hello, if possible please downgrade to Visual Studio 17.2 or older. We're working on fixing the build using VS 17.4, but we're blocked on some dependencies. You can track our progress here: https://github.com/flutter/flutter/issues/117932

> cc @loic-sharma for guidance on which version of MSVC we use on CI and if there is a regression with later versions.

CIs are using VS2019 currently.

**Comment by loic-sharma** [comment]
@huycozy would it be possible to add the `a: desktop` label on these kinds of issues? That's what the desktop team uses to triage issues :)

**Comment by huycozy** [comment]
@loic-sharma I'll keep that in mind. Thanks for reminding :)

**Comment by loic-sharma** [comment]
Hello everyone, this issue should now be fixed when building using the latest `main` branch. Make sure to update your dependencies with `gclient sync -D` before building. Please let me know if you run into any follow up issues!
