### ISSUE TITLE
PageView.builder itemBuilder being called 3 times for every page change

### ISSUE THREAD

**Issue by pauldemarco** [flutter/flutter#11691]
## Steps to Reproduce

Run the following and use the chevron arrows to switch pages.
Notice the console log printing 3 times for every page change.
When going from page 1 to page 2:
> I/flutter (24852): index: 2
 I/flutter (24852): index: 1
 I/flutter (24852): index: 2

## Sample code
```dart
class AppReportsState extends State<AppReports> {
  PageController _pageController;
  int _currentIndex = 0;

  @override
  void initState() {
    super.initState();
    _currentIndex = 0;
    _pageController = new PageController(initialPage: _currentIndex);
  }

  @override
  void dispose() {
    _pageController.dispose();
    super.dispose();
  }

  void _nextPage(int delta) {
    _pageController.animateToPage(
        _currentIndex + delta,
        duration: const Duration(milliseconds: 300),
        curve: Curves.ease
    );
  }

  void _handlePageChanged(int page) {
    setState(() {
      _currentIndex = page;
    });
  }

  @override
  Widget build(BuildContext context) {
    return new PageView.builder(
      controller: _pageController,
      onPageChanged: _handlePageChanged,
      itemBuilder: (BuildContext context, int index) {
        print('index: $index');
        return new Scaffold(
          appBar: new AppBar(
            title: new Text(index.toString()),
            leading: new IconButton(
              tooltip: 'Previous day',
              icon: const Icon(Icons.arrow_back),
              onPressed: () {
                _nextPage(-1);
              },
            ),
            actions: <Widget>[
              new IconButton(
                icon: const Icon(Icons.arrow_forward),
                tooltip: 'Next day',
                onPressed: () {
                  _nextPage(1);
                },
              ),
            ],
          ),
          body: const Text('Report'),
        );
      },
    );
  }
}
```

**Comment by zoechi** [comment]
What is the expected behavior?
`build()` can be called any number of times and should be expected at any time.

**Comment by zoechi** [comment]
If `itemBuilder` returns the same instance as before then it doesn't have to be rebuilt
```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: AppReports(),
    );
  }
}

class AppReports extends StatefulWidget {
  AppReports({Key key, this.title}) : super(key: key);

  final String title;

  @override
  AppReportsState createState() => AppReportsState();
}

class AppReportsState extends State<AppReports> {
  PageController _pageController;
  int _currentIndex = 0;

  @override
  void initState() {
    super.initState();
    _currentIndex = 0;
    _pageController = PageController(initialPage: _currentIndex);
  }

  @override
  void dispose() {
    _pageController.dispose();
    super.dispose();
  }

  void _nextPage(int delta) {
    _pageController.animateToPage(_currentIndex + delta,
        duration: const Duration(milliseconds: 300), curve: Curves.ease);
  }

  void _handlePageChanged(int page) {
    setState(() {
      _currentIndex = page;
    });
  }

  final _pages = <int, Widget>{};
  @override
  Widget build(BuildContext context) {
    return PageView.builder(
      controller: _pageController,
      onPageChanged: _handlePageChanged,
      itemBuilder: (BuildContext context, int index) {
        return _pages.putIfAbsent(
          index,
          () {
            print('index: $index');
            return Scaffold(
              appBar: AppBar(
                title: Text(index.toString()),
                leading: IconButton(
                  tooltip: 'Previous day',
                  icon: const Icon(Icons.arrow_back),
                  onPressed: () {
                    _nextPage(-1);
                  },
                ),
                actions: <Widget>[
                  IconButton(
                    icon: const Icon(Icons.arrow_forward),
                    tooltip: 'Next day',
                    onPressed: () {
                      _nextPage(1);
                    },
                  ),
                ],
              ),
              body: const Text('Report'),
            );
          },
        );
      },
    );
  }
}
```

**Comment by sjmcdowall** [comment]
FWIW -- I had the same issue with .builder -- it was firing the whole build() method a dozen times for a single page change (and it was a simple simple single Container() thing under a Scaffold.. 

I simply changed to a PageView .. and provided the array of pages .. and -- ta da-- only fires build() once per transition .. so something seems flakey here ...

**Comment by huhugiter** [comment]
I found that when we have a PageView.builder like this
```
PageView.builder(
  controller: PageController(initialPage: _index),
  itemCount: _messages.length,
  scrollDirection: Axis.horizontal,
  itemBuilder: (context, index) {
    print('index $index');
    return _buildPage(_messages[index]);
  }
)
```
and if _index is the last element index
`_index = _messages.length - 1, //(here suppose _messages.length = 4) even`
It will print
```
I/flutter (11971): index 2
I/flutter (11971): index 3
```
and  if 
`_index = _messages.length - 1, //(here suppose _messages.length = 3) odd`
It will print
```
I/flutter (11971): index 2
I/flutter (11971): index 1
```
the expected behavior will like to be
`I/flutter (11971): index 3`
and
`I/flutter (11971): index 2`
and when the 
`_messages.length = 1 (just one element in list)`
It works well

**Comment by huhugiter** [comment]
I think I know the reason.
Because the _pageController.page of last page is not length - 1,
but close to length - 1. So it will build length - 1 page and length - 2 page.
For example:
```
I/flutter (10969): _pageController.page 5.999999999999999
I/flutter (10969): index 5  ConnectionState.done
I/flutter (10969): _pageController.page 5.999999999999999
I/flutter (10969): index 6  ConnectionState.done
```
this will definitely happen when initialPage is last page(if List.lenth != 1)
but sometime, it will happend even if it isn't the last page.

**Comment by lorenzoconti** [comment]
> I think I know the reason.
> Because the `_pageController.page` of last page is not `length - 1`,
> but close to `length - 1`. So it will build `length - 1` page and `length - 2` page.
> For example:
> 
> ```
> I/flutter (10969): _pageController.page 5.999999999999999
> I/flutter (10969): index 5  ConnectionState.done
> I/flutter (10969): _pageController.page 5.999999999999999
> I/flutter (10969): index 6  ConnectionState.done
> ```
> this will definitely happen when `initialPage` is last page(if `List.length != 1`)
> but sometime, it will happen even if it isn't the last page.

What could be a solution for this problem?

**Comment by singlakaran** [comment]
@huhugiter  do you have any solution for that problem?
and how to set value of _index in your solution

```
PageView.builder(
  controller: PageController(initialPage: _index),
  itemCount: _messages.length,
  scrollDirection: Axis.horizontal,
  itemBuilder: (context, index) {
    if (index != _index) {
      return Container();
    }
    print('index $index');
    return _buildPage(_messages[index]);
  }
)
```

**Comment by MatthiasRieck** [comment]
I have the same problem. It seems that using `setState` in the `onPageChanged` callback causes the unnecessary rebuilds:

```dart
class TestApp extends StatefulWidget {
  @override
  _TestAppState createState() => _TestAppState();
}

class _TestAppState extends State<TestApp> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: PageView.builder(
        itemBuilder: (context, pageIndex) {
          print('Build Page $pageIndex');
          return Center(
            child: Text('Page $pageIndex'),
            key: ValueKey(pageIndex),
          );
        },
        itemCount: 3,
        // Uncommenting onPageChanged causes significant
        // more calls to itemBuilder
        /*onPageChanged: (index) {
          setState(() {
            
          });
        },*/
      ),
    );
  }
}
```
Uncomment onPageChanged to reproduce the issue

**Comment by liyuqian** [comment]
The behavior (2 unnecessary builds and thus 3 total page builds) here looks similar to that in https://github.com/flutter/flutter/issues/14316#issuecomment-643690978

**Comment by ghenry** [comment]
> I have the same problem. It seems that using `setState` in the `onPageChanged` callback causes the unnecessary rebuilds:
> 
> ```dart
> class TestApp extends StatefulWidget {
>   @override
>   _TestAppState createState() => _TestAppState();
> }
> 
> class _TestAppState extends State<TestApp> {
>   @override
>   Widget build(BuildContext context) {
>     return Scaffold(
>       body: PageView.builder(
>         itemBuilder: (context, pageIndex) {
>           print('Build Page $pageIndex');
>           return Center(
>             child: Text('Page $pageIndex'),
>             key: ValueKey(pageIndex),
>           );
>         },
>         itemCount: 3,
>         // Uncommenting onPageChanged causes significant
>         // more calls to itemBuilder
>         /*onPageChanged: (index) {
>           setState(() {
>             
>           });
>         },*/
>       ),
>     );
>   }
> }
> ```
> 
> Uncomment onPageChanged to reproduce the issue

I see this too as I'm using `onPageChanged` to change the state needed for `BottonNavigationBar`

**Comment by alejandro-morales-gris** [comment]
Anyone know then what to do in this situation? Because not using setState on onPageChanged SOLVES the problem, but there are cases like mine, in which i have to update a value of a var with the current page index, and for what I know, you cannot use setState on itemBuilder. Also, a widget decoration depends of that value, so something has to work like setState. Any ideas?
