### ISSUE TITLE
[CP] Use Remap sampler option in flutter tool

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#116923]
### issue_link

https://github.com/flutter/flutter/issues/116610

### Commit Hash

84ed058 

### Target

beta

### pr_link

https://github.com/flutter/flutter/pull/116922

### Impacted Users

Impeller/Shaders

### Impact Description

Shaders that declare multiple samplers will not work correctly when targeting impeller

### Workaround

Conditionally re-order samplers in code based on impeller

### Risk

low

### Test Coverage

yes

**Comment by jonahwilliams** [comment]
This is just the framework side changes for the previous PR, everything else is the same

**Comment by itsjustkevin** [comment]
@zanderso

**Comment by zanderso** [comment]
CP lgtm

**Comment by jonahwilliams** [comment]
My bad, both should be beta. Updated

**Comment by itsjustkevin** [comment]
Thanks!
