### ISSUE TITLE
error in flutter build apk

### ISSUE THREAD

**Issue by Wotan6891** [flutter/flutter#116948]
hello.

I have tried everything and read everything about this error in the help forums of different expert websites and nothing helped me.

I use this: flutter build apk

in this file is the complete error

https://anonfiles.com/lfL5r5M2yd/errorflutterbuild_txt

and this is the last lines of the error:

FAILURE: Build failed with an exception.

* Where:
Script '/home/carlos/snap/flutter/common/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 1102

* What went wrong:
Execution failed for task ':app:compileFlutterBuildRelease'.
> Process 'command '/home/carlos/snap/flutter/common/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3m 7s
Running Gradle task 'assembleRelease'...                          195,0s
Gradle task assembleRelease failed with exit code 1

help me

**Comment by darshankawar** [comment]
@Wotan6891 
Looking at the error log you attached above, it seems to be failing due to compile errors as below:

```
lib/view/screens/bank/withdraw_history_screen.dart:17:25: Error: The getter 'Get' isn't defined for the class 'WithdrawHistoryScreen'.
 - 'WithdrawHistoryScreen' is from 'package:efood_multivendor_restaurant/view/screens/bank/withdraw_history_screen.dart' ('lib/view/screens/bank/withdraw_history_screen.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'Get'.
            getMenuItem(Get.find<BankController>().statusList[0], context),



lib/view/screens/bank/withdraw_history_screen.dart:55:60: Error: The getter 'tr' isn't defined for the class 'String'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'tr'.
        ) : Center(child: Text('no_withdraw_history_found'.tr));



lib/view/screens/dashboard/dashboard_screen.dart:31:3: Error: 'FlutterLocalNotificationsPlugin' isn't a type.
  FlutterLocalNotificationsPlugin flutterLocalNotificationsPlugin;
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
lib/view/screens/dashboard/dashboard_screen.dart:61:41: Error: 'RemoteMessage' isn't a type.
    FirebaseMessaging.onMessage.listen((RemoteMessage message) {
                                        ^^^^^^^^^^^^^
lib/view/screens/dashboard/dashboard_screen.dart:55:29: Error: The method 'AndroidInitializationSettings' isn't defined for the class '_DashboardScreenState'.
 - '_DashboardScreenState' is from 'package:efood_multivendor_restaurant/view/screens/dashboard/dashboard_screen.dart' ('lib/view/screens/dashboard/dashboard_screen.dart').
Try correcting the name to the name of an existing method, or defining a method named 'AndroidInitializationSettings'.
    var androidInitialize = AndroidInitializationSettings('notification_icon');
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


../../snap/flutter/common/flutter/packages/flutter/lib/src/widgets/interactive_viewer.dart:1191:10: Error: Undefined name 'Quad'.
  return Quad.points(
         ^^^^                           
```

Some of the getters or methods in your app are not being able to be identified by the tool and hence giving you so many errors. I suggest you double check the packages and plugins you are using are uptodate and are in sync with the framework.

I also noticed that you have installed flutter sdk using `snap` which is third party package. Also try to install the sdk without that package and compile, clean again and see if it helps or not.

Currently, looking at the error log, I am going ahead and closing as not a framework issue, but some conflicts in your app. If you disagree, write in comments and I'll reopen it.
