### ISSUE TITLE
Connected devices not detected 

### ISSUE THREAD

**Issue by alex9153** [flutter/flutter#116977]
[☠] Connected device (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    ✗ Exception: Connected device exceeded maximum allowed duration of 0:10:00.000000

<img width="619" alt="Снимок экрана 2022-12-13 в 16 02 17" src="https://user-images.githubusercontent.com/353832/207325547-3237e5a2-e98d-453e-aad2-42fff547515a.png">

Only reboot system fix this problem.
This error must kill necessary process automatically

**Comment by huycozy** [comment]
Hi @alex9153, does this issue only happen on VSCode? Please share the output of `flutter doctor -v`. Thanks!
