### ISSUE TITLE
How to use `Blob` in flutter web application

### ISSUE THREAD

**Issue by guchengxi1994** [flutter/flutter#116946]
I used `FilePicker` selected an image and want to convert it to Blob object on web, but the result is not right. Here is the code.
```dart
FilePickerResult? result = await FilePicker.platform.pickFiles();
    if (result != null) {
      Uint8List? fileBytes = result.files.first.bytes;
      String fileName = result.files.first.name;
      debugPrint(fileName);

      if (fileBytes != null) {
        print(fileBytes.length);
        Blob blob = Blob(fileBytes, "text/plain", 'native');
        print(blob.size);
        await js.context.callMethod(
            'putObject', ["exampledir/exampleobject.png", blob, {}]);
      }
    } else {
      // User canceled the picker
    }
```

`blob.size` is not equal to `fileBytes.length` and it cannot be used on web.

**Comment by danagbemava-nc** [comment]
Hi @guchengxi1994, is there any specific issue you're running into aside the sized being different?

**Comment by guchengxi1994** [comment]
@danagbemava-nc  I found the solusion, just modify `Blob blob = Blob(fileBytes, "text/plain", 'native');` to `Blob blob = Blob([fileBytes], "text/plain", 'native');`
