### ISSUE TITLE
Hide SkyShell.app from dock when running as part of test_sky

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#117]
<a href="https://github.com/eseidelGoogle"><img src="https://avatars.githubusercontent.com/u/11857803?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [eseidelGoogle](https://github.com/eseidelGoogle)**
_Tuesday Jul 28, 2015 at 18:25 GMT_
_Originally opened as https://github.com/flutter/engine/issues/316_

----

This appears to be how:
http://stackoverflow.com/questions/1082374/making-a-checkbox-toggle-the-dock-icon-on-and-off

Chromium's ContentShell may already have a solution for this, @dpranke would know.

**Comment by FlutterIssues** [comment]
<a href="https://github.com/dpranke"><img src="https://avatars.githubusercontent.com/u/513897?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [dpranke](https://github.com/dpranke)**
_Tuesday Jul 28, 2015 at 20:40 GMT_

----

Content Shell appears in the dock when we run the tests.

Back in the day, DRT didn't, but the code was quite different and more headless IIRC.

**Comment by abarth** [comment]
This works now.
