### ISSUE TITLE
[image_picker][Android 13][EXIF-GPS]Can not contain the gps data through [Photo picker]

### ISSUE THREAD

**Issue by howmind** [flutter/flutter#117053]
## Problems:
Cannot get GPS  data(Latitude and Longitude) from the file picked through image_picker plugin on Android 13.

The pop window picker is replaced by photo picker(the UI style is different from before)which seems new module on Android 13.

![picker_1](https://user-images.githubusercontent.com/11898173/207592149-153c41ac-eb0b-4325-94ec-89a24a45064c.jpg)

A few day ago, the same codes is workable and the wndow picker is the below style:

![picker_0](https://user-images.githubusercontent.com/11898173/207592105-823f62de-e566-4643-943f-f9664f07d622.jpg)

## Steps to Reproduce

1. run it on Android 13 with photo picker
2. ensure an image include gps data in camera folder - copy it to pc and checked its property
3. use image_picker plugin to pick the image file with gps data and print the file path
4. use android studio tool to copy the file to desktop pc and check file property

**Expected results:** 
the picked file by image_picker contains gps data

**Actual results:** 
missing the gps data in the picked file by image_picker
<img width="405" alt="Screen Shot 2022-12-14 at 10 58 56 pm" src="https://user-images.githubusercontent.com/11898173/207589870-5b46c7b1-c7e4-424c-b1e2-f08c01e9c57b.png">

[✓] Flutter (Channel stable, 3.3.9, on macOS 12.6 21G115 darwin-arm, locale en-AU)
    • Flutter version 3.3.9 on channel stable at /Users/durone/Documents/Development/SDK/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b8f7f1f986 (3 weeks ago), 2022-11-23 06:43:51 +0900
    • Engine revision 8f2221fbef
    • Dart version 2.18.5
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/durone/Documents/Development/SDK/Android
    • Platform android-33, build-tools 32.0.0
    • ANDROID_HOME = /Users/durone/Documents/Development/SDK/Android
    • ANDROID_SDK_ROOT = /Users/durone/Documents/Development/SDK/Android
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.74.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.54.0

[✓] Connected device (3 available)
    • Pixel 4 XL (mobile) • 9B251FFBA000GU • android-arm64  • Android 13 (API 33)
    • macOS (desktop)     • macos          • darwin-arm64   • macOS 12.6 21G115 darwin-arm
    • Chrome (web)        • chrome         • web-javascript • Google Chrome 108.0.5359.98

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by huycozy** [comment]
Hi @howmind, when the picker screen prompts, which image source did you select? (Google Photos or Google Drive or another?)

May be related/similar: #74615

**Comment by howmind** [comment]
> Hi @howmind, when the picker screen prompts, which image source did you select? (Google Photos or Google Drive or another?)
> 
> May be related/similar: #74615

Hi @huycozy ,  I selected it from recent images category from google photos(local storage - DCIM/Camera folder).
BTW, if image_picker is from camera, I can get GSP info in EXIF data.
I think the new Photo picker maybe protect the sensitive information for security reasons under.

**Comment by huycozy** [comment]
@howmind thanks for your response. This is a known issue being tracked at https://github.com/flutter/flutter/issues/74615. Closing this issue as a duplicate, so please follow up on it for further updates.
