### ISSUE TITLE
[DevTools] Cannot make the Widget Tree inspector to work in a specific project

### ISSUE THREAD

**Issue by Miiite** [flutter/flutter#117054]
## Steps to Reproduce

My problem is that for a specific project, my DevTools widget inspector seems to be broken.

What I do: 
1. Start the app
2. Enable the DevTools widget inspector
3. Get an uncaught exception on startup

This issue seems to be only affecting me inside my dev team. Other devs manage to make the Widget Tree inspector work properly.

## Logs

This is the exception that is being raised, whenever I enable the dart DevTools widget inspector:
```_AssertionError ('package:flutter/src/foundation/stack_frame.dart': Failed assertion: line 205 pos 12: 'match != null': Expected #42     Eval.<anonymous closure>.getRootWidgetSummaryTreeWithPreviews.<anonymous closure> () to match RegExp: pattern=^#(\d+) +(.+) \((.+?):?(\d+){0,1}:?(\d+){0,1}\)$ flags=.)```

Digging down a little bit, this is the piece of code that is raising the exception:

```
final RegExp parser = RegExp(r'^#(\d+) +(.+) \((.+?):?(\d+){0,1}:?(\d+){0,1}\)$');
    Match? match = parser.firstMatch(line);
    assert(match != null, 'Expected $line to match $parser.');
```
inside `stack_frame.dart`, and the value of the `line` variable is :
`#4639   Eval.<anonymous closure>.getRootWidgetSummaryTreeWithPreviews ()`

The end result, is that I get little to no information regarding my widget tree inside the UI:

![Screenshot 2022-12-14 at 13 52 43](https://user-images.githubusercontent.com/475526/207600213-736b2518-d00b-49b1-821a-3f44b8e56474.png)
![Screenshot 2022-12-14 at 13 52 41](https://user-images.githubusercontent.com/475526/207600221-dcc71efc-ad24-4895-af06-e1bffdb8920a.png)

```
➜ flutter doctor -v
[✓] Flutter (Channel stable, 3.3.3, on macOS 12.5.1 21G83 darwin-arm, locale en-FR)
    • Flutter version 3.3.3 on channel stable at /Users/adrien.padol/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18a827f393 (3 months ago), 2022-09-28 10:03:14 -0700
    • Engine revision 5c984c26eb
    • Dart version 2.18.2
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/adrien.padol/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A309
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.74.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.54.0

[✓] Connected device (5 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554                        • android-arm64  • Android 12 (API
      32) (emulator)
    • iPhone de Adrien (mobile)   • 00008101-0015250C3A82001E            • ios            • iOS 16.0 20A362
    • iPhone 14 Pro Max (mobile)  • 901C9E92-3E07-4D8B-A6B3-CB9275537362 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-16-0 (simulator)
    • macOS (desktop)             • macos                                • darwin-arm64   • macOS 12.5.1
      21G83 darwin-arm
    • Chrome (web)                • chrome                               • web-javascript • Google Chrome
      108.0.5359.124

[✓] HTTP Host Availability
    • All required HTTP hosts are available

```

</details>

**Comment by darshankawar** [comment]
Thanks for the report @Miiite 
I see a similar issue open in devtools dedicated repo: https://github.com/flutter/devtools/issues/4388 and I suggest you to follow-up in it for further updates and may share your findings in it. 
I will close from here for now. If you get directed here claiming that the fix need to be made in the framework itself instead of in devtools, please write in comments and I'll reopen it.

**Comment by akagupta9** [comment]
any update on it? I am also getting same issue.
