### ISSUE TITLE
`Windows windows_android_aot_engine` is stuck on `collect builds -> get`, all subtests passed

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#117021]
https://ci.chromium.org/p/flutter/builders/try/Windows%20windows_android_aot_engine/1030?

All sub-tests succeeded, the `get` step has been stuck for 2+ hours.

![Screen Shot 2022-12-13 at 2 35 07 PM](https://user-images.githubusercontent.com/682784/207459434-85f998b6-1598-41a1-8240-70a5b402d1ce.png)

**Comment by jmagman** [comment]
cc @vashworth

**Comment by godofredoc** [comment]
How frequently is this happening?

**Comment by jmagman** [comment]
No idea, saw it once and filed it.

**Comment by godofredoc** [comment]
I haven't seen any other failures like this. Setting as P3 and keeping it open for investigation.

**Comment by drewroengoogle** [comment]
I'm struggling to do any sort of additional investigation on this since the build shows no additional error information, @godofredoc Do you have any suggestions for steps that could be taken to learn more about this, or should we wait and see if this was a one-off issue?

**Comment by nehalvpatel** [comment]
Seems to be one-off. Closing for now until we encounter this again.
