### ISSUE TITLE
State.context assertion in framework.dart

### ISSUE THREAD

**Issue by luis901101** [flutter/flutter#117058]
## flutter doctor -v
```
[✓] Flutter (Channel stable, 3.3.8, on macOS 13.0 22A380 darwin-arm, locale en-US)
    • Flutter version 3.3.8 on channel stable at /Users/user/fvm/versions/3.3.8
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 52b3dc25f6 (5 weeks ago), 2022-11-09 12:09:26 +0800
    • Engine revision 857bd6b74c
    • Dart version 2.18.4
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/user/Android/SDK
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = /Users/user/Android/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
```

## Use case
In my app I use Sentry and Firebase Crashlytics for issues reporting and I have received some reports about:
```
_CastError: Null check operator used on a null value
  File "framework.dart", line 942, in State.context
  File "map_places_fragment.dart", line 200, in _MapPlacesFragmentState.loadMarkers
  File "map_places_fragment.dart", line 312, in _MapPlacesFragmentState.onMapViewUpdated
```
The cause seems obvious, the `loadMarkers` function is trying to use a `context` in some async call after widget get disposed, this is my bad.
Ok but why the report is about **Null check operator used on a null value** which confused me for a while instead of some **FlutterError about State context**.

I checked the line 942 in "framework.dart" as indicated in the report and noted that an assertion is used to check for **_element** nullability and throw the expected **FlutterError** inside the assertion, and this works fine but only in Debug mode, so in Release mode the assertion doesn't happen and that's why the **"_CastError: Null check operator used on a null value"** occurs.

## Proposal
I think it would be better not to use the assertion in the `State.context` function, I mean something simple like this:

```dart
BuildContext get context {
  if (_element == null) {
    throw FlutterError(
      'This widget has been unmounted, so the State no longer has a context (and should be considered defunct). \n'
          'Consider canceling any active work during "dispose" or using the "mounted" getter to determine if the State is still active.',
    );
  }
  return _element!;
}
```
This way it's guaranteed the expected **FlutterError** will be thrown no matter Debug, Profile or Release.

**Comment by darshankawar** [comment]
Thanks for the report and proposal @luis901101 
Looking at the framework.dart file in latest master version, currently it has below:

<img width="1016" alt="Screenshot 2022-12-15 at 11 33 28 AM" src="https://user-images.githubusercontent.com/67046386/207784961-786e02ff-c98a-46a7-8e67-fd040f3c7cb9.png">

https://github.com/flutter/flutter/blob/dbc9306380d8a72273b478b8fcc934a6014f946d/packages/flutter/lib/src/widgets/framework.dart#L946

Based on your proposal, are you saying to return `_element!` directly instead of `return true` ?

**Comment by luis901101** [comment]
> Thanks for the report and proposal @luis901101 Looking at the framework.dart file in latest master version, currently it has below:
> 
> <img alt="Screenshot 2022-12-15 at 11 33 28 AM" width="1016" src="https://user-images.githubusercontent.com/67046386/207784961-786e02ff-c98a-46a7-8e67-fd040f3c7cb9.png">
> 
> https://github.com/flutter/flutter/blob/dbc9306380d8a72273b478b8fcc934a6014f946d/packages/flutter/lib/src/widgets/framework.dart#L946
> 
> Based on your proposal, are you saying to return `_element!` directly instead of `return true` ?

Hi, what I mean is to remove assert usage, check the sample code in my proposal the idea is if element == null throw FlutterError otherwise return element!;

**Comment by goderbauer** [comment]
We do this check in an assert so it gets compiled out in release mode and keeps release builds small. The stack trace in release mode here actually seems to have enough information to reconstruct the problem.

**Comment by luis901101** [comment]
Ok, understood. But how big would be the release if that assertion were not used? It’s true that checking the stacktrace the developer should be able to find the source of the problem _(maybe an unexperienced developer could take it longer)_, but in any case it takes more time to confirm the problem just because the reported problem is not exactly the problem.
