### ISSUE TITLE
error while loading shared libraries: libflutter_linux_gtk.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by salih-okur** [flutter/flutter#117052]
## Steps to Reproduce

I have build flutter project with this command for linux.
flutter build linux --release 
I am using a dynamic library in my application. After building the project, I need to add capability to the executable file. But after adding capability, it does not work. I got this error:
flutter_application_1 error while loading shared libraries: libflutter_linux_gtk.so: cannot open shared object file: No such file or directory
 What should I do?

**Expected results:** 

**Actual results:** 

<details>
<summary>Code sample</summary>
The code add capability the file:
sudo setcap cap_sys_rawio+ep flutter_application_1

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by huycozy** [comment]
Hi @salih-okur, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) along with `Step by step` reproduction so that we may verify this. Also, please provide the output of `flutter doctor -v` as well. Thank you!
