### ISSUE TITLE
[web] rename <flt-glass-pane> to <flutter-view>

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#117034]
The tag name `<flt-glass-pane>` has become a misnomer as Flutter Web evolved. It's original role was to sit on top of the rendered content and intercept all pointer events (as if it's a "glass pane" covering a framed picture). As we changed our DOM structure to accommodate accessibility and platform views it has become the root element of the [FlutterView](https://api.flutter.dev/flutter/dart-ui/FlutterView-class.html) being rendered.

This element is also a bit of a "public API", since it lives outside the shadow root and may be matched on by CSS selectors. A valid use-case to match on it is to style platform view content that's embedded in it.

A more appropriate name for this element would be `<flutter-view>`, which:

* makes it clear that it's 1:1 to the `FlutterView` class.
* is clear - it does not involve obscure metaphors ("glass pane") or abbreviations ("flt").

Unfortunately, it may break existing CSS selectors. We should consider if a better name is worth the trouble, and/or if there are more gradual ways to introduce it.

**Comment by ditman** [comment]
> We should rename `<flt-glass-pane>` to `<flutter-view>`

This is a [trivial change](https://github.com/flutter/engine/blob/7e03ebcbee0dfb4d361618deeeb3d4595156ca65/lib/web_ui/lib/src/engine/embedder.dart#L50-L51), however it has the potential of [breaking the internet](https://github.com/search?q=%22flt-glass-pane%22&type=code)?

_Follow up for: https://github.com/flutter/engine/pull/37738_

**Comment by yjbanov** [comment]
This is fixed now.
