### ISSUE TITLE
CORS issue with Vimeo in Flutter Web (Access to XMLHttpRequest has been blocked by CORS policy) 

### ISSUE THREAD

**Issue by VasuBhav** [flutter/flutter#117048]
## Steps to Reproduce

1. We use pod_player for running Vimeo videos in our flutter web application 
2.  Within the plugin we get a cors error to hit the video API and we provide access "Access-Control-Allow-Origin" :"*" and the issue still arises 
3.  What we can do now to resolve the cors error in our web app

```
Flutter Version :  3.3.9
Dart SDK version: 2.18.5
##plugin
pod_player_new : 0.0.6
```

**Comment by iapicca** [comment]
possibly a [pod_player](https://pub.dev/packages/pod_player) [issue](https://github.com/newtaDev/pod_player/issues)

related issues:
- https://github.com/flutter/flutter/issues/32622
