### ISSUE TITLE
Support attachments in golden test failure output.

### ISSUE THREAD

**Issue by wferem1** [flutter/flutter#117051]
## Use case

When running golden tests, I would like to see the differences in my test report (e.g. JUnit). 
For JUnit, Github/Gitlab supports showing attachments inline if the `system-out` xml-element contains `[[ATTACHMENT|/path/to/some/file]]`.

## Proposal
Extend the output of the failure with the files in the `failures` subdirectory, so that for each file an attachment is added to the output, with the relative path from the project to the file.
#### current output
```
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following assertion was thrown while running async test code:
Golden "path/to/golden.png": Pixel test failed, 0.61% diff detected.
Failure feedback can be found at
/absolute/path/to/test/failures

When the exception was thrown, this was the stack:
#0      LocalFileComparator.compare (package:flutter_test/src/_goldens_io.dart:102:7)
>asynchronous suspension>
>asynchronous suspension>
(elided one frame from package:stack_trace)
════════════════════════════════════════════════════════════════════════════════════════════════════
```
#### expected output
```
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following assertion was thrown while running async test code:
Golden "path/to/golden.png": Pixel test failed, 0.61% diff detected.
Failure feedback can be found at
/absolute/path/to/test/failures
[[ATTACHMENT|/relative/path/to/test/failures/testName_masterImage.png]]
[[ATTACHMENT|/relative/path/to/test/failures/testName_testImage.png]]
[[ATTACHMENT|/relative/path/to/test/failures/testName_isolatedDiff.png]]
[[ATTACHMENT|/relative/path/to/test/failures/testName_maskedDiff.png]]

When the exception was thrown, this was the stack:
#0      LocalFileComparator.compare (package:flutter_test/src/_goldens_io.dart:102:7)
>asynchronous suspension>
>asynchronous suspension>
(elided one frame from package:stack_trace)
════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by goderbauer** [comment]
Are you suggesting that we should list the individual files in the error message instead of just the directory? Why do you think that would be helpful?

/cc @Piinks

**Comment by wferem1** [comment]
@goderbauer 
[GitLab](https://docs.gitlab.com/ee/ci/testing/unit_test_reports.html#view-junit-screenshots-on-gitlab), and [other CI tools](https://github.com/jenkinsci/junit-attachments-plugin) allow for parsing these attachments in the result of the test report, so that a link is created to this file and can be shown directly in the UI

**Comment by Piinks** [comment]
@wferem1 do you mean something like https://github.com/flutter/flutter/issues/54223?

**Comment by wferem1** [comment]
Putting the diffs in a single file would indeed help, however what I'm asking is a more custom approach (which probably only applies to JUnit reporting).

I just found out that I can implement my own GoldenFileComparator, which adds the necessary attachments to the output (and maybe try to put them in a single file instead of 4 different png's).
