### ISSUE TITLE
package:integration_test screenshot testing is broken for flutter web

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/flutter#117077]
In this example test here, https://github.com/flutter/flutter/blob/master/packages/integration_test/example/test_driver/extended_integration_test.dart, we should include a real example of image comparison (particularly for flutter web). I am trying to implement this method for DevTools flutter web integration tests and there appear to be some rough edges with the integration test package.

For example, even when this method returns true the following exception is thrown:
```
 result {"result":"true","failureDetails":[],"data":{"screenshots":[{"bytes":[]}]}}
 Unhandled exception:
 type 'Null' is not a subtype of type 'String' in type cast
 #0      integrationDriver (package:integration_test/integration_test_driver_extended.dart:103:60)
 <asynchronous suspension>
 #1      main (file:///Users/kenzieschmoll/develop/devtools/packages/devtools_app/test_driver/integration_test.dart:9:3)
 <asynchronous suspension>
```

@yjbanov

**Comment by kenzieschmoll** [comment]
Issue to track implementing real screenshot testing for web using skia gold is here: https://github.com/flutter/flutter/issues/8612.

**Comment by MarcusHolanda1** [comment]
Hello, is there any deadline/version to up this fix? I saw that the pr has already been approved.
