### ISSUE TITLE
[CP] Add release_build parameter

### ISSUE THREAD

**Issue by drewroengoogle** [flutter/flutter#117089]
### issue_link

https://github.com/flutter/flutter/issues/117086

### Commit Hash

0d0febc94d50fb1db65a7f914a5fce7ba696577e

### Target

stable

### pr_link

https://github.com/flutter/flutter/pull/117088

### Impacted Users

Flutter release team

### Impact Description

This is needed in order to successfully deploy the docs_deploy target.

### Workaround

There is currently not a workaround that I'm aware of.

### Risk

low

### Test Coverage

yes

### Validation Steps

We will rerun the release_builder recipe on this branch

**Comment by itsjustkevin** [comment]
Thanks @drewroengoogle
