### ISSUE TITLE
Fix SSL issues (android < 7.1)

### ISSUE THREAD

**Issue by redDwarf03** [flutter/flutter#117055]
With Android < 7.1, i met issue with ```CERTIFICATE_VERIFY_FAILED: certificate has expired``` error

Currently, i should 

- Add in the main.dart:

```
// Fix LetsEncrypt root certificate for Android<7.1
  final x1cert = await rootBundle.load('assets/ssl/isrg-root-x1.pem');
  SecurityContext.defaultContext.setTrustedCertificatesBytes(
    x1cert.buffer.asUint8List(),
  );
```
- Add a certificate ISRG Root X1 certificate file from https://letsencrypt.org/certs/isrgrootx1.pem to  ```isrg-root-x1.pem``` file in the project
- Add certificate declaration in pubspec.yaml asset section ```- assets/ssl/isrg-root-x1.pem```

Is it possible to directly integrate in flutter a fix for these OS ?

Thx

**Comment by huycozy** [comment]
Hi @redDwarf03 
This issue has been discussed at https://github.com/flutter/flutter/issues/91195. There is also filed issue in `dart-lang/io` repository: https://github.com/dart-lang/io/issues/83. Please check solutions there if any (I took a look and found that https://github.com/dart-lang/io/issues/83#issuecomment-940617222 might be applicable to your case).

Closing as it's not a Flutter issue itself. If you disagree, please write in the comments and I will reopen it. Thanks!
