### ISSUE TITLE
[CP] NestedScrollView+trackpad regression fix

### ISSUE THREAD

**Issue by Piinks** [flutter/flutter#117027]
### issue_link

https://github.com/flutter/flutter/issues/116486

### Commit Hash

97df2b3

### Target

beta

### pr_link

https://github.com/flutter/flutter/pull/117343

### Impacted Users

This issue affected Mac and Windows targets using a trackpad to scroll NestedScrollViews.

### Impact Description

This fixes an issue with trackpad input where  the scroll position would suddenly change when stopping the scrolling action. Stopping a trackpad scrolling activity (as in touching the trackpad to stop active scrolling) worked as expected in a other scroll views, this only affected the NestedScrollView as it has a custom position implementation that was not taken into account when the feature was first added. The linked PR fixed the issue.

### Workaround

No.

### Risk

low

### Test Coverage

yes

### Validation Steps

Scrolling and stopping in a NestedScrollView with a trackpad does not create unexpected behavior (scroll position going way off in the other direction). The regression is tested and verified.

**Comment by itsjustkevin** [comment]
@HansMuller could you take a look?

**Comment by HansMuller** [comment]
LGTM

**Comment by Piinks** [comment]
Cherry pick pull request: https://github.com/flutter/flutter/pull/117343
