### ISSUE TITLE
[codesign] revisit logic of unlocking keychain

### ISSUE THREAD

**Issue by XilaiZhang** [flutter/flutter#117002]
As pointed out by sir Godofredo, unlock keychain happens inside a `api.step` in recipe, and
1. Every step command in recipes runs in its own session(~ terminal)
2. Unlocking the key chain works only for the active session. E.g. if you open a terminal and unlock the keychain and then open a second terminal to run the command accessing the keychain will fail as the keychain has not been unlocked on the second terminal session.

On the other hand, currently unlock keychain logic is working and verified by led runs. (without the current logic led run would fail) It is possible that multiple sessions share the same keychain on the physical machine, but we would like to revisit and check this logic in the future.

**Comment by ricardoamador** [comment]
Closing as not needed.
