### ISSUE TITLE
Regression to Logo on README.md

### ISSUE THREAD

**Issue by timsneath** [flutter/flutter#117003]
https://github.com/flutter/flutter/pull/105189 changed the logo to work better on dark mode, but unfortunately it's regressed how it appears on light mode. 

Chrome 108.0.5359.98 on macOS:
<img width="886" alt="image" src="https://user-images.githubusercontent.com/2319867/207425989-e094343a-2abc-4016-a19b-fc0602ea2491.png">

Safari 16.1 (18614.2.9.1.12) on macOS:
<img width="924" alt="image" src="https://user-images.githubusercontent.com/2319867/207426159-0c8a839b-9512-495f-8383-11502e54f867.png">

/cc @cadenkriese @Hixie

**Comment by cadenkriese** [comment]
If I had to guess, it's because I sourced the image links from the brand guide page, which redirects to a CDN that may not keep the links consistent.

Any ideas for a better place to host these images?

**Comment by cadenkriese** [comment]
Yeah, this is a bug with GitHub's CSP. I've filed a ticket with them.

**Comment by cadenkriese** [comment]
They just got back to me and said they've implemented a fix. Everything seems fixed for me, @timsneath do you still have issues?

**Comment by timsneath** [comment]
Splendid!

Looking good for me on Safari 16.2 and Chrome 109.0.5414.87:
<img width="872" alt="image" src="https://user-images.githubusercontent.com/2319867/214078959-d8ec9752-d831-413d-9f5c-0f24c281e9db.png">
