### ISSUE TITLE
Code Completion not working properly anymore after upgrading to 3.3

### ISSUE THREAD

**Issue by S-Man42** [flutter/flutter#117076]
Hi,

I am not quite sure whether this is a Flutter or an Android Studio issue. Hopefully somebody can help me here, when it is a Flutter thing:

I upgraded from Flutter 2.x to 3.3.9 (at the same time I upgraded my Android Studio from 4.x to 2021.3) a few weeks ago. From that point my auto completion has not been working properly anymore.

* [CTRL] + [SPACE] still opens and display a suggestion list containing
** Flutter internal classes (I assume this is because of already imported flutter/material.dart package)
** Classes from current file
** Classes from explicitly imported files

Everything, which is not already explicitly imported into the current working file is ignored. So I am not able to use automatical imports, I need to find the correct file path by myself and have to include it manually before further writing.

I observed, an older version of my project works fine on the same setting. So I am wondering, whether a project may becomes too huge? (currently > 1000 files in the `lib` directory and > 40 external libs in `pubspec.yaml`) But why did the setup before the upgrade worked properly?

What I tried:
* Cleared/Removed every possible cache directory I could find (Flutter, Pub, Android Studio, Gradle, ...)
* Completely upgraded, removed and reinstalled the entire setup
* No PowerSafe mode
* My mates have no problems with the project having similar setups

Flutter doctor:

```
[√] Flutter (Channel stable, 3.3.9, on Microsoft Windows [Version 10.0.19045.2251], locale de-DE)
    • Flutter version 3.3.9 on channel stable at E:\Flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b8f7f1f986 (3 weeks ago), 2022-11-23 06:43:51 +0900
    • Engine revision 8f2221fbef
    • Dart version 2.18.5
    • DevTools version 2.15.0

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at E:\Android\sdk                                                                      
    • Platform android-33, build-tools 33.0.1                                                            
    • ANDROID_HOME = E:\Android\sdk                                                                      
    • Java binary at: E:\Android\Android Studio\jre\bin\java                                             
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)                        
    • All Android licenses accepted.                                                                     

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2021.3)
    • Android Studio at E:\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[√] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 13 (API 33) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.19045.2251]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 107.0.5304.107
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 103.0.1264.44

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```
(AS Dart Plugin: 213.7433, Flutter Plugin: 71.1.3)

If relevant: https://github.com/S-Man42/GCWizard/tree/master

Thanks in advance,
Mark

**Comment by huycozy** [comment]
Hi @S-Man42, [flutter-intellij](https://github.com/flutter/flutter-intellij/issues) is the correct place to file this issue since `Code Completion` should belong to Android Studio IDE issue. Closing as it's not a Flutter issue itself. Thanks!
