### ISSUE TITLE
Connectivity plugin should provide a stream for observing changes to network configuration

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#11704]
According to GIPReachability (iOS) documentation, checking network state prior to opening a network connection is not a good idea. The recommended way is to handle connection failures gracefully.

Android, OTOH, makes the opposite recommendation: https://developer.android.com/training/basics/network-ops/managing.html
"""Before you perform network operations, it's good practice to check the state of network connectivity. """

Both platforms agree that subscribing to network state changes is an acceptable way to manage network connectivity. Our plugin does not expose this functionality and it should.

As part of this fix, we will also put a disclaimer that apps should not check network connectivity prior to sending requests. Also relevant: https://github.com/flutter/flutter/issues/1051

**Comment by mit-mit** [comment]
Hi @mehmetf, still looking into this?

**Comment by mehmetf** [comment]
Yes, I plan to get to it by EOM.
