### ISSUE TITLE
[CP] Fix FragmentProgram documentation

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#117072]
### issue_link

https://github.com/flutter/engine/pull/38273

### Commit Hash

 aa78cd8

### Target

beta

### pr_link

https://github.com/flutter/engine/pull/38286

### Impacted Users

Users attempting to use new FragmentProgram API

### Impact Description

Documentation incorrectly references an old github issue that does not reflect the current state of API development instead of pointing to accurate website documents.

### Workaround

Users can always find the website from other sources, we could redirect from the github project

### Risk

low

### Test Coverage

yes

### Validation Steps

This is a documentation only change so there is low/no risk or validation needed

**Comment by zanderso** [comment]
cp lgtm
