### ISSUE TITLE
[web] Refactor Views to allow for multi-view.

### ISSUE THREAD

**Issue by ditman** [flutter/flutter#117098]
The current implementations of:

* Platform dispatcher
* View embedder
* Engine window
* Flutter view

All assume that there will only be a singleton flutter view in the page, which in a multi-window world would not be true.

The implementations can also be simplified (there's some weird inheritance relationships in the classes above).

We should refactor the above so it looks more like the following high-level diagram:

![Flutter Web View Architecture](https://user-images.githubusercontent.com/1255594/207711367-046818a5-3da8-4332-a977-c51a45182935.jpg)

**Comment by ditman** [comment]
(Dimensions Provider may be owned (and exposed) by the embedding strategy, since both share a lot in common)

**Comment by ditman** [comment]
@yjbanov [said](https://github.com/flutter/engine/pull/37738#discussion_r1047911976):

> nit: we might as well embrace the future and start referring to `FlutterView` in the docs, i.e. "The tag name that embeds a `FlutterView`."

**Comment by ditman** [comment]
This is actually being worked on right now!

**Comment by yjbanov** [comment]
We're now working through individual follow-up issues. This issue is largely fixed now.
