### ISSUE TITLE
☂️ Migrate all (web) plugins/packages to use package:web (instead of dart:html)

### ISSUE THREAD

**Issue by kevmoo** [flutter/flutter#117022]
Required to support wasm-compiled Flutter apps.

- [x] camera_web
  - https://github.com/flutter/flutter/issues/139748 
  - https://github.com/flutter/packages/pull/7012
- [x] cross_file
- [x] google_maps - https://github.com/flutter/packages/pull/5254
- [x] google_sign_in_web - https://github.com/flutter/flutter/issues/139169
- [x] image_picker - https://github.com/flutter/flutter/issues/139751
- [x] pointer_interceptor - https://github.com/flutter/flutter/issues/139753
- [x] shared_preferences_web
- [x] url_launcher_web
- [x] video_player_web - https://github.com/flutter/flutter/issues/139752
- [x] webview_flutter - https://github.com/flutter/flutter/issues/139749

Googlers: see go/wasm-ready-pkg-migrate

**Comment by ditman** [comment]
(This also affects some code in `flutter/packages`)

**Comment by ditman** [comment]
Re-titled to specify that we want to migrate plugins to use **`package:web`**, not `staticInterop`. Right?

**Comment by kevmoo** [comment]
Well, both...right? CC @joshualitt @eyebrowsoffire

**Comment by ditman** [comment]
Yes, you're right: staticInterop for custom JS SDKs, and package:web for the webIDL

**Comment by ditman** [comment]
google maps in progress here: https://github.com/flutter/packages/pull/5254

**Comment by ditman** [comment]
image_picker in progress: https://github.com/flutter/packages/pull/5799

**Comment by ditman** [comment]
video_player in progress: https://github.com/flutter/packages/pull/5800

**Comment by amrgetment** [comment]
I migrated the File picker plugin, https://github.com/miguelpruivo/flutter_file_picker/issues/1480
Not a Flutter plugin but a community plugin, I just wanted to share this news with you

**Comment by ditman** [comment]
Thanks @amrgetment!

**Comment by uldall** [comment]
Now that wasm support has gone stable, can the you provide an estimate on when the two remaining packages will support it? We use webview_flutter_web, so this is holding us back from enabling wasm. Thank you for the great work!

**Comment by ThomasAunvik** [comment]
@uldall temporarely you can use this branch: https://github.com/ThomasAunvik/flutter-packages/commit/a799099ab2a0a4ef1436332ef42615080b1036c3
```yaml
override_dependencies:
    webview_flutter_web:
    git:
      url: https://github.com/ThomasAunvik/flutter-packages.git
      ref: fixwasm OR a799099ab2a0a4ef1436332ef42615080b1036c3
      path: packages/webview_flutter/webview_flutter_web
```

currently however, you need to use the master channel from flutter to be able to use flutter:HtmlElementView for some reason.
else you get this:
![image](https://github.com/flutter/flutter/assets/9968151/f4b1ff30-08fe-4236-a3ac-a3a22e715477)

**Comment by uldall** [comment]
Thx @ThomasAunvik ! Are you planing on upstreaming the fix?

**Comment by ditman** [comment]
Created: 

* https://github.com/flutter/flutter/issues/150748

**Comment by IchordeDionysos** [comment]
@kevmoo thanks to the team for all the work 😍

Given camera is now merged, can this issue be closed?

**Comment by kevmoo** [comment]
💯 @IchordeDionysos !

**Comment by amrgetment** [comment]
That’s a great efforts , Thanks for all

**Comment by iapicca** [comment]
given this [comment](https://github.com/dart-lang/sdk/issues/56358#issuecomment-2272931080) from @r-durao-pvotal
looks like [grpc](https://github.com/grpc/grpc-dart/issues/715#issue-2312040112) is missing
