### ISSUE TITLE
Flutter packages need to move SDK upper bound above 3.0.0

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/flutter#117009]
The DevTools build is currently broken due to a flutter package (cupertino_icons) with an SDK upper bound of 3.0.0. On the last few flutter-candidate branches, the Dart version is >= 3.0.0, which causes pub version solving issues.

DevTools issue: https://github.com/flutter/devtools/issues/4943
Attempted fix for package:cupertino_icons (though if the bots do not pass, someone from the Flutter team may need to push it forward): https://github.com/flutter/packages/pull/2938

I expect this would be an issue for other packages, too, not just package cupertino_icons.

For extra information as to why DevTools runs off of the latest flutter candidate branch, we do this so that we are testing and running from the same version of Flutter that is in g3. Diverging in Flutter versions causes issues with differences in our internal and external source code.

**Comment by goderbauer** [comment]
Removing framework label since the framework already moved the bounds up.

**Comment by stuartmorgan** [comment]
This should wait until after 3.0 is stable, since otherwise breaking changes could still happen.

**Comment by a-siva** [comment]
Is this still an issue. I presume it is not related. 
Closing issue, if a problem still exists please open a new issue,
