### ISSUE TITLE
Trying to run flutter demo code 'main.dart' with a connected android emulator

### ISSUE THREAD

**Issue by andrewervin** [flutter/flutter#117020]
As said in title, I'm using flutter's dart demo code with an android emulator and running it with the hope of no bugs just to make sure everything is working correctly.  When I use the command 'flutter doctor', there are no issues which is why I'm confused why this won't work. The debug console in VS Code 2019 says this:

Launching lib\main.dart on sdk gphone64 x86 64 in debug mode...
lib\main.dart:1
√  Built build\app\outputs\flutter-apk\app-debug.apk.
Connecting to VM Service at ws://127.0.0.1:55474/aTAQVTPRjYs=/ws
E/SurfaceSyncer( 9525): Failed to find sync for id=0
W/Parcel  ( 9525): Expecting binder but got null!

If you need any additional information, please let me know. FYI I am very new to these programs.

**Comment by darshankawar** [comment]
@andrewervin 
Can you provide `flutter doctor -v` ? Also, are you using M1 machine ? Or is your machine using AMD processor ?
Do you get same error on different emulator which is not `gphone64 x86 64` or with a physical device ?
Can you also provide complete `flutter run -v` in properly formatted text ?
