### ISSUE TITLE
docs_deploy on dart-internal is not publishing docs

### ISSUE THREAD

**Issue by drewroengoogle** [flutter/flutter#117157]
This is failing because the Firebase are not enabled in the dart-internal project.

**Comment by drewroengoogle** [comment]
https://flutter-review.git.corp.google.com/c/recipes/+/37360

**Comment by godofredoc** [comment]
Fix footer:

https://flutter-review.googlesource.com/c/recipes/+/37505

**Comment by godofredoc** [comment]
Update to the footer fix: https://flutter-review.googlesource.com/c/recipes/+/37600

**Comment by godofredoc** [comment]
Reopening to land CPs to stable and beta

**Comment by godofredoc** [comment]
Beta: https://flutter-review.googlesource.com/c/recipes/+/37681

**Comment by godofredoc** [comment]
Stable: https://flutter-review.googlesource.com/c/recipes/+/37680
