### ISSUE TITLE
On Fuchsia, if a flutter app's text field requests focus before its mozart window is focused that text field will not receive key events.

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#11717]
If you later request focus ont he textfield when the mozart window *is* in focus the text field will receive key events as expected.

It seems like focus events within the flutter app are effectively ignored by mozart.

Possibly related to https://github.com/flutter/flutter/issues/10847

**Comment by Hixie** [comment]
cc @chinmaygarde

**Comment by chinmaygarde** [comment]
This has been fixed in the pending engine roll.

**Comment by Hixie** [comment]
@chinmaygarde I'm going to assume this landed in fuchsia. Please reopen if not!
