### ISSUE TITLE
Feature request: Add 'fullscreen' implementation to AlertDialog

### ISSUE THREAD

**Issue by art926** [flutter/flutter#117124]
Just like it's recently done for the regular dialog - https://github.com/flutter/flutter/pull/112261.

**Comment by darshankawar** [comment]
@art926 
Do you have a use case wherein you need full screen alert dialog ? And whether the regular dialog for which full sreen feature has been implemented, does it cover your use case ?

**Comment by goderbauer** [comment]
WDYT @TahaTesser @guidezpl since you recently did this for the other dialog variant (https://github.com/flutter/flutter/pull/112261)?

**Comment by TahaTesser** [comment]
Fullscreen is supposed to be a fully customizable dialog where you can add your own content to the dialog.

See https://m3.material.io/components/dialogs/overview
![image](https://user-images.githubusercontent.com/48603081/208682223-773d4bdc-86a1-4ab3-9200-10234881d829.png)

I don't see any reason to have the alert dialog be fullscreen.  


@art926 
Can you please provide a use case?

**Comment by guidezpl** [comment]
> I don't see any reason to have the alert dialog be fullscreen.

Agreed according to spec, I think this can be closed.

**Comment by TahaTesser** [comment]
Closing.
