### ISSUE TITLE
[Impeller] Benchmark PSO library construction in the constructor of the content context.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#117180]
If Impeller decides to add shader specialization (via specialization constants or otherwise), it will become necessary to benchmark PSO library construction. We should have such a harness in place already.

Today, PSOs can be (and are) created on a worker pool asynchronously. So we need a way to reason about setup time across multiple threads.

**Comment by jonahwilliams** [comment]
I think our start up benchmarks roughly cover this right?
