### ISSUE TITLE
IOS: failed to read asset tags: Assets.xcassets

### ISSUE THREAD

**Issue by elieobeid7** [flutter/flutter#117131]
Flutter 3.3.9, macbook air m1, macos Ventura, xcode 14.1.

This error only started happening when I updated code and flutter version and macos version.

If I run `flutter build ios --release`

I get this error

    warning: Run script build phase 'Create Symlinks to Header Folders' will be run during every build because it does not specify any
        outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking
        "Based on dependency analysis" in the script phase. (in target 'abseil' from project 'Pods')
    
        Result bundle written to path:
            /var/folders/pd/nz9mvjcs5mj49w_fvm53lr1m0000gn/T/flutter_tools.yCZKUD/flutter_ios_build_temp_dirUzfVbE/temporary_xcresult_bundle
    
    
    Error (Xcode): failed to read asset tags: The command `(cd /Users/user/Documents/projects/app/ios &&
    /Applications/Xcode.app/Contents/Developer/usr/bin/actool --print-asset-tag-combinations --output-format xml1
    /Users/user/Documents/projects/app/ios/Runner/Assets.xcassets)` exited with status 1. The command's standard output was:
    
    <?xml version="1.0" encoding="UTF-8"?>
    <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
    <plist version="1.0">
    <dict>
            <key>com.apple.actool.asset-tag-combinations</key>
            <array/>
            <key>com.apple.actool.errors</key>
            <array>
                    <dict>
                            <key>debug-description</key>
                            <string>No string key for value in object around line 9, column 0.</string>
                            <key>description</key>
                            <string>The data couldn’t be read because it isn’t in the correct format.</string>
                            <key>failure-reason</key>
                            <string>The data is not in the correct format.</string>
                    </dict>
            </array>
    </dict>
    </plist>

If I remove the reference of `Assets.xcassets` in Xcode (I don't know if I should do that), I get this error

E`rror (Xcode): unable to read input file as a property list: The operation couldn’t be completed. (XCBUtil.PropertyListConversionError error 2.)`

My info.plist

    <?xml version="1.0" encoding="UTF-8"?>
    <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
    <plist version="1.0">
    <dict>
    	<key>CADisableMinimumFrameDurationOnPhone</key>
    	<true/>
    	<key>CFBundleDevelopmentRegion</key>
    	<string>$(DEVELOPMENT_LANGUAGE)</string>
    	<key>CFBundleDisplayName</key>
    	<string>AppName</string>
    	<key>CFBundleExecutable</key>
    	<string>$(EXECUTABLE_NAME)</string>
    	<key>CFBundleIdentifier</key>
    	<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
    	<key>CFBundleInfoDictionaryVersion</key>
    	<string>6.0</string>
    	<key>CFBundleName</key>
    	<string>flutter_app</string>
    	<key>CFBundlePackageType</key>
    	<string>APPL</string>
    	<key>CFBundleShortVersionString</key>
    	<string>$(MARKETING_VERSION)</string>
    	<key>CFBundleSignature</key>
    	<string>????</string>
    	<key>CFBundleVersion</key>
    	<string>$(CURRENT_PROJECT_VERSION)</string>
    	<key>LSRequiresIPhoneOS</key>
    	<true/>
    	<key>UILaunchStoryboardName</key>
    	<string>LaunchScreen</string>
    	<key>UIMainStoryboardFile</key>
    	<string>Main</string>
    	<key>UIStatusBarHidden</key>
    	<false/>
    	<key>UISupportedInterfaceOrientations</key>
    	<array>
    		<string>UIInterfaceOrientationPortrait</string>
    		<string>UIInterfaceOrientationLandscapeLeft</string>
    		<string>UIInterfaceOrientationLandscapeRight</string>
    	</array>
    	<key>UISupportedInterfaceOrientations~ipad</key>
    	<array>
    		<string>UIInterfaceOrientationPortrait</string>
    		<string>UIInterfaceOrientationPortraitUpsideDown</string>
    		<string>UIInterfaceOrientationLandscapeLeft</string>
    		<string>UIInterfaceOrientationLandscapeRight</string>
    	</array>
    	<key>UIViewControllerBasedStatusBarAppearance</key>
    	<false/>
    </dict>
    </plist>

I tried removing the assets folder reference and adding it again, and I tried using the xcode legacy build system, and the issue wasn't solved.

**Comment by exaby73** [comment]
Hello @elieobeid7. Thank you for filing this issue. Can you please provide the following information?

- Detailed reproduction steps, along with any supporting files like the assets you use.
- From which version did you upgrade from

Please provide the information in the form of text. See how to make collapsible sections with Markdown [here](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-collapsed-sections).

**Comment by elieobeid7** [comment]
Issue solved

**Comment by exaby73** [comment]
How did you solve it? Would be helpful for anyone having the same issue in the future :)

**Comment by elieobeid7** [comment]
There was a merge conflict in the json file of the assets folder which was not detected by VSCode. Also, I removed all the crash analytics step in xcode when building.
