### ISSUE TITLE
Flutter generates build/ios/Pods.build/Release-iphonesimulator in the android folder

### ISSUE THREAD

**Issue by maykhid** [flutter/flutter#117134]
<img width="420" alt="Screen Shot 2022-12-15 at 9 47 16 AM" src="https://user-images.githubusercontent.com/54851623/207814302-56a0c49a-beeb-4fa6-b410-220c386dd675.png">

I just did a `flutter clean ` and `flutter pub get` and noticed these folders/files generated as seen in the image above in my android folder. Why did this happen? Because I feel this shouldn't happen. 

I've seen [this issue](https://github.com/flutter/flutter/issues/90446) which is similar but in their case, the files were generated in the ios folder.

My Flutter Version is 3.3.8 on channel stable.

```
Flutter (Channel stable, 3.3.8, on macOS 12.6.1 21G217 darwin-x64, locale en-US)
    • Flutter version 3.3.8 on channel stable at /Users/owner/Dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 52b3dc25f6 (5 weeks ago), 2022-11-09 12:09:26 +0800
    • Engine revision 857bd6b74c
    • Dart version 2.18.4
    • DevTools version 2.15.0

Checking Android licenses is taking an unexpectedly long time...[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/owner/Library/Android/sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F100
    • CocoaPods version 1.11.3

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.66.0)
    • VS Code at /Users/owner/Documents/Packages/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Connected device (2 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 11 (API 30) (emulator)
    • macOS (desktop)                    • macos         • darwin-x64  • macOS 12.6.1 21G217 darwin-x64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

**Comment by exaby73** [comment]
Hello @maykhid. Could you tell me which command you run that causes this to appear?

**Comment by maykhid** [comment]
Hi @exaby73 , Nothing special exactly. I just did a `flutter clean` and then I did a `flutter pub get`, I noticed those folders/files generated.

**Comment by exaby73** [comment]
Could you share some detailed reproduction steps so that I may verify the issue?

**Comment by maykhid** [comment]
<img width="220" alt="Screen Shot 2022-12-15 at 3 01 39 PM" src="https://user-images.githubusercontent.com/54851623/207880640-b48f371b-70f0-4946-8717-d3f923581d58.png">



Okay. So on Flutter 3.3.8 'stable',  you can try adding those dependencies as shown above. Run `flutter pub get` -> Then `flutter clean` -> then `flutter pub get` again.

**Comment by exaby73** [comment]
I cannot reproduce this issue. Can you reproduce this issue with the default Flutter counter app? If so, what is the steps you are taking?
