### ISSUE TITLE
NavigationRail isExtended:true destination label highlight has the wrong width

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#117126]
The destination label highlight for a M3 NavigationRail with `isExtended:true`  has the wrong width or the wrong origin.

This is a regression for `useMaterial3:true`. It's possible (I haven't checked) that it was introduced in https://github.com/flutter/flutter/pull/116108.

Here's an example that demonstrates the problem: https://dartpad.dev/?id=272d62da895a9e17c38c7f562a6d3d5f&channel=master

![Screen Shot 2022-12-14 at 6 52 49 PM](https://user-images.githubusercontent.com/1377460/207761312-a09acf6d-e6eb-4df9-9846-bf627a00ca13.png)

**Comment by HansMuller** [comment]
CC @darrenaustin 
A fix for this may need to be cherry-picked

**Comment by TahaTesser** [comment]
Apologies, I'm working on this. I'm also accounting for custom padding from destinations which also messes up highlight position. 

Maybe get rid of the _IndicatorInkWell class and move `InkResponse` to the indicator itself and wrap a custom render box with expands hitTest area of the destination. 

Something that `chip.dart` has:

https://github.com/flutter/flutter/blob/dbc9306380d8a72273b478b8fcc934a6014f946d/packages/flutter/lib/src/material/chip.dart#LL1332C17-L1332C17

I will file a PR by tomorrow with a solution that's not breakable with `extended` or `padding`, `minWidth`, or `minExtendedWidth`.

**Comment by Piinks** [comment]
I haven't been able to reproduce this yet. I wonder if there is more than one bug here. Going to the dartpad link above does not look like it is actually using material 3.

![Screen Shot 2022-12-16 at 11 58 24 AM](https://user-images.githubusercontent.com/16964204/208160024-d7f9dcb3-ef91-49d2-92ef-d3cb87df2684.png)

**Comment by TahaTesser** [comment]
This should be reproducible on the beta channel.  The current stable doesn't have [this](https://github.com/flutter/flutter/pull/116108)

**Comment by Piinks** [comment]
Yeah I have it running on master, and for some reason dartpad wont let me change the channel using the button at the bottom

**Comment by TahaTesser** [comment]
I've attempted to fix this issue: https://github.com/flutter/flutter/pull/117320 and added regression tests.

Unrelated to this regression, after the holidays, I want to streamline the `NavigationRail` class, it's not as clean and flexible as the new `NavigationBar`.
1. It doesn't have a smarter destination rendering. Everything is rendered in a column with lots of SizedBox widgets.
2. `minWidth` and `minExtended` behave weirdly. 
3. It could also fix: https://github.com/flutter/flutter/issues/104813 https://github.com/flutter/flutter/issues/116298

**Comment by Piinks** [comment]
Thanks @TahaTesser!
