### ISSUE TITLE
Dashboard Android integration tests using Firebase Test Lab

### ISSUE THREAD

**Issue by collinjackson** [flutter/flutter#11718]
flutter/engine@841cd667122fa8d10f7ab48c88d5720ccb2ace22 introduced a crash that affects any Flutter app (including the Gallery) but only on Jellybean. This is the sort of regression that Firebase Test Lab would be good at detecting. A lot of the infrastructure is already in place to do this on every pull request, but someone needs to write a script that talks to the Test Lab API and selects a device, etc. This issue tracks the progress of getting Android integration tests up on the tests dashboard.

/cc @yjbanov @jason-simmons

**Comment by neiljaywarner** [comment]
any thoughts @Hixie @collinjackson

**Comment by godofredoc** [comment]
This is complete, recipe is [here](https://cs.opensource.google/flutter/recipes/+/master:recipes/firebaselab/firebaselab.py), builder configs can be found [here](https://cs.opensource.google/flutter/infra/+/master:config/firebaselab_config.star) and example test can be found [here](https://cs.opensource.google/flutter/flutter/+/master:dev/integration_tests/abstract_method_smoke_test/).
