### ISSUE TITLE
Glyphs and the toolbar of the Text Selection are shown over the AppBar!

### ISSUE THREAD

**Issue by andromeda-center** [flutter/flutter#117141]
Glyphs and the toolbar of the Text Selection are drawn over the entire app widgets.

Steps to reproduce:
1. Create a simple mobile app (I tested in Android), and a simple scrollable multiline TextField. (or see my sample code)
2. And some lines so that the TextField becomes bigger that the viewport.
3. Select a text and wait for the glyph and toolbar of the selection to appear.
4. Scroll the text down so that the selected text hides behind the AppBar.

Expected:
the glyph and toolbar of the selected text should also disappear.

Actual:
the glyph and toolbar of the selected text drawn over the AppBar.

<details>
<summary>Sample code</summary>

```
import 'package:flutter/material.dart';

void main() =>
  runApp(MaterialApp(
    home: Scaffold(
      appBar: AppBar(title: const Text('a: TextField')),
      body: SingleChildScrollView(
        child: TextField(
          controller: TextEditingController(
            text: List.generate(150, (a)=> 'this is the line $a').join('\n')
          ),
          maxLines: null,
        ),
      ),
    ),
  ));

```
</details>

**Comment by huycozy** [comment]
@andromeda-center I see there are some issues addressing the case you described https://github.com/flutter/flutter/issues/59229, https://github.com/flutter/flutter/issues/13182
Closing as a duplication, so please follow up on them for further updates.
