### ISSUE TITLE
Packaging metadata is not uploading to the correct GCS location

### ISSUE THREAD

**Issue by drewroengoogle** [flutter/flutter#117160]
Release packages are not populated in flutter.dev.

**Comment by godofredoc** [comment]
Taking a quick look at the build, the artifacts along with its provenance are being uploaded correctly but the metadata file is uploaded to a wrong location.

**Comment by godofredoc** [comment]
Fixed with: https://flutter-review.googlesource.com/c/recipes/+/37380
