### ISSUE TITLE
Fuchsia SDK roll failing on licenses check

### ISSUE THREAD

**Issue by akbiggs** [flutter/flutter#117162]
Example failure: https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20License/8073/overview

Fixing by rolling manually, but not sure why the roller can't handle this.

**Comment by jason-simmons** [comment]
A new version of the Flutter license script landed recently (https://github.com/flutter/engine/pull/38148)

The new license script checks the list of files that were excluded from the crawl against a golden list.

The auto-roller script needs to update the golden (https://github.com/flutter/engine/blob/main/ci/licenses_golden/excluded_files)

**Comment by jason-simmons** [comment]
cc @rmistry

**Comment by rmistry** [comment]
> A new version of the Flutter license script landed recently ([flutter/engine#38148](https://github.com/flutter/engine/pull/38148))
> 
> The new license script checks the list of files that were excluded from the crawl against a golden list.
> 
> The auto-roller script needs to update the golden (https://github.com/flutter/engine/blob/main/ci/licenses_golden/excluded_files)

Which part needs to change in the rollers? (I could not tell from the above link).
The license script steps that the rollers take is [here](https://skia.googlesource.com/buildbot/+/main/autoroll/go/repo_manager/parent/pre_upload_steps.go#182).

**Comment by jason-simmons** [comment]
The Flutter license script is now writing a file called `excluded_files` in its output directory.  The roll PR should copy this output to the golden version of `excluded_files`.

The logic in:
https://skia.googlesource.com/buildbot/+/main/autoroll/go/repo_manager/parent/pre_upload_steps.go#220
should be duplicated to copy the `excluded_files` file in addition to the `licenseFileName` file

**Comment by akbiggs** [comment]
Thanks, closing. Will reopen if we see this error come up again with the script fix.
