### ISSUE TITLE
[Impeller] Re-enable impeller_unittests after shader compiler errors are addressed.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#117122]
These were disabled while we investigate the flakes reported in https://github.com/flutter/flutter/issues/114872.

**Comment by chinmaygarde** [comment]
Taking a stab at re-enbaling these. So far, we know that this issue was happening on the try-bots for a while and could not be reproduced locally or on the post-submit bots. Then it began to happen on the post submit bots as well.

So far, we have verified that the API usage is correct and instrumented with ASAN and TSAN. We think this is an issue with Metal drivers on some platforms where there is a race between device teardown and concurrent PSO construction.

If we need to gather more information on the flakes on the bots, we could try retrying on this specific failure in `run_tests.py`.

**Comment by zanderso** [comment]
x-ref https://github.com/flutter/engine/pull/40339

**Comment by gaaclarke** [comment]
I'm reopening this issue, we are seeing the shader compiler error again and there was a partial revert of that pr.

**Comment by chinmaygarde** [comment]
We are re-trying on failure and tracking in https://github.com/flutter/flutter/issues/123733.
