### ISSUE TITLE
Mac_android run_release_test is failing due to device-related errors

### ISSUE THREAD

**Issue by jason-simmons** [flutter/flutter#117100]
The framework tree is red because the Mac_android run_release_test LUCI builder is repeatedly failing.

See https://ci.chromium.org/p/flutter/builders/prod/Mac_android%20run_release_test

Errors occur when the test tries to install the application on the device.

Examples:
https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_android%20run_release_test/8198/overview ("INSTALL_FAILED_INSUFFICIENT_STORAGE")

https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_android%20run_release_test/8199/overview ("DeviceException: No Android devices detected")

**Comment by sealesj** [comment]
The bot causing these failures has been quarantined. Is this issue still occurring?

**Comment by zanderso** [comment]
@sealesj Did you trigger a re-run of the failing test?

**Comment by godofredoc** [comment]
We need to take a look at cocoon device doctor source to check if the applications are being uninstalled.

We also need to check the devices space using adb go/flutter-luci-playbook#android-install-failed-insufficient-storage

**Comment by sealesj** [comment]
Attemping to diagnose the problem on mac-22, however running into ssh errors on the bot

**Comment by drewroengoogle** [comment]
@sealesj Is there anything else that needs to be done with this issue, or is it good to close?

**Comment by sealesj** [comment]
I believe it is good to close

**Comment by drewroengoogle** [comment]
Thanks! Closing now
