### ISSUE TITLE
The backspace and delete keys are not working while debugging in the flutter windows application. 

### ISSUE THREAD

**Issue by manuvarghese236** [flutter/flutter#117296]
The backspace and delete keys are not working while debugging in the flutter windows application.

Debug information 

A KeyRepeatEvent is dispatched, but the state shows that the physical key is not pressed. If this occurs in real application, please report this bug to Flutter. If this occurs in unit tests, please ensure that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This was the event: KeyRepeatEvent#1e8d4(physicalKey: PhysicalKeyboardKey#700e1(usbHidUsage: "0x000700e1", debugName: "Shift Left"), logicalKey: LogicalKeyboardKey#00102(keyId: "0x200000102", keyLabel: "Shift Left", debugName: "Shift Left"), character: null, timeStamp: 71:37:37.874424)
'package:flutter/src/services/hardware_keyboard.dart':
package:flutter/…/services/hardware_keyboard.dart:1
Failed assertion: line 432 pos 16: '_pressedKeys.containsKey(event.physicalKey)'

**Comment by exaby73** [comment]
Hi @manuvarghese236 
I see there's an open issue addressing the case you described https://github.com/flutter/flutter/issues/116953
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
