### ISSUE TITLE
Floating Bubble Overlay for Background Running

### ISSUE THREAD

**Issue by NOTtheKRish** [flutter/flutter#117280]
Hi... I'm new to Flutter Development... I'd like to implement **Floating Bubble Overlay** for Background Service in my Taxi Booking App... What actually happens is that, **when the driver closes the app, the bubble overlay gets active** and it means that the app is running in the background... When the bubble is tapped, it should open the app... Anyone help me to accomplish this, by suggesting me the best method to implement these conditions... Thanks in Advance...

**Comment by darshankawar** [comment]
@NOTtheKRish 
Your question is better suited for support channels like StackOverflow or Flutter's reddit help page where you can ask this question and get solution / answer. You can check [this](https://stackoverflow.com/questions/72569047/how-to-make-floating-overlay-widget-looks-like-facebook-chat-head-in-flutter) and see if it helps in your case.
This repo is for tracking bugs and feature request for the framework.
Closing.
