### ISSUE TITLE
[firebase auth] verify phone number not working on release application flutter

### ISSUE THREAD

**Issue by EngrTAHAR-Noureddine** [flutter/flutter#117271]
Hi flutter developper,
i got this error when i implement package :  [firebase_auth 4.2.1](https://pub.dev/packages/firebase_auth).
this package work fine in debug mode but in release mode not working and i got this error :

`E/flutter (29344): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: type 'Null' is not a subtype of type 'String'
E/flutter (29344): #0      yB.Rmc.<anonymous closure> (VDg:660)
E/flutter (29344): #1      _RootZone.PUa (Mtg:1586)
E/flutter (29344): #2      _BufferingStreamSubscription._Thb (Htg:339)
E/flutter (29344): #3      _BufferingStreamSubscription._add (Htg:271)
E/flutter (29344): #4      _Yb._add (Itg:123)
E/flutter (29344): #5      _bc._Wgb (Itg:253)
E/flutter (29344): #6      _Yb._Wgb (Itg:153)
E/flutter (29344): #7      _RootZone.PUa (Mtg:1586)
E/flutter (29344): #8      _BufferingStreamSubscription._Thb (Htg:339)
E/flutter (29344): #9      _Pb.Rhb (Htg:515)
E/flutter (29344): #10     _Sb.hhb (Htg:620)
E/flutter (29344): #11     _Sb.ehb.<anonymous closure> (Htg:591)
E/flutter (29344): #12     _oj (Etg:40)
E/flutter (29344): #13     _pj (Etg:49)`

This is the code :
`Future<bool?> loginUser(String phone, BuildContext context) async{
    FirebaseAuth _auth = FirebaseAuth.instance;

    _auth.verifyPhoneNumber(
        phoneNumber: phone,
        timeout: const Duration(seconds: 60),
        verificationCompleted: (AuthCredential credential) async{
          Navigator.of(context).pop();

          UserCredential result = await _auth.signInWithCredential(credential);

          User? user = result.user;

          if(user != null){
            Navigator.push(context, MaterialPageRoute(
              builder: (context) => HomeScreen(user: user,)
            ));
          }else{
            print("Error");
          }

          //This callback would gets called when verification is done auto maticlly
        },
        verificationFailed: (FirebaseAuthException exception){
          print(exception);
        },
        codeSent: (String verificationId, int? forceResendingToken){
          showDialog(
            context: context,
            barrierDismissible: false,
            builder: (context) {
              return AlertDialog(
                title: const Text("Give the code?"),
                content: Column(
                  mainAxisSize: MainAxisSize.min,
                  children: <Widget>[
                    TextField(
                      controller: _codeController,
                    ),
                  ],
                ),
                actions: <Widget>[
                  TextButton(
                    child: const Text("Confirm", style: TextStyle(color: Colors.white, backgroundColor: Colors.blue),),
                    onPressed: () async{
                      final code = _codeController.text.trim();
                      AuthCredential credential = PhoneAuthProvider.credential(verificationId: verificationId, smsCode: code);

                      UserCredential result = await _auth.signInWithCredential(credential);

                      User? user = result.user;

                      if(user != null){
                        Navigator.push(context, MaterialPageRoute(
                            builder: (context) => HomeScreen(user: user,)
                        ));
                      }else{
                        print("Error");
                      }
                    },
                  )
                ],
              );
            }
          );
        },
        codeAutoRetrievalTimeout: (val){
          print(val);
        }
    );
  }`

please help me ! this is urgent and search a lot and i can't find a solution.

**Comment by mariopepe** [comment]
I am having the same issue let’s hope some one helps us

**Comment by darshankawar** [comment]
@EngrTAHAR-Noureddine 
Since this is related to `firebase_auth` plugin which is third party, please open this issue in dedicated repo: https://github.com/firebase/flutterfire/issues
Closing from here.
