### ISSUE TITLE
Perform preliminary setups on iphone11 for deployment in devicelab

### ISSUE THREAD

**Issue by yusuf-goog** [flutter/flutter#117237]
Please follow instrunctions sent via email to setup iphone11 devices for install in the devicelab.

While setting up, note device_id and label which hostname each will be assigned to, so that we can update apple provisioning profiles.

**Comment by yusuf-goog** [comment]
cc @jmagman @godofredoc

**Comment by yusuf-goog** [comment]
Provided instructions from g3doc to Kent on ios device setup.
Debuggged new device provisioning issues that came up. (Requires use of mac machine to setup new devices).
Setup one iphone11 with ios16 and swapped it in on mac-44.
Created CL with provisioning profile update for new device.

Gave Kent a new mac mini from lab inventory to use to setup new ios devices.

**Comment by yusuf-goog** [comment]
@jmagman There are 2 references to ios-15 devices in flutter (https://github.com/flutter/flutter/blob/master/.ci.yaml#L134). Do we need to remove that requirement or update to 16, now that we are starting to upgrade ios devices?

**Comment by jmagman** [comment]
I suggest 
1. Smoke test to validate the tests all pass on the new iPhone 11/ iOS 16 devices via led runs, as we did a few months ago.  
1. Update half the fleet to the new devices in all pools
1. Update the staging config `IOS_VERSION`
https://flutter.googlesource.com/infra/+/refs/heads/main/config/devicelab_staging_config.star#22
1. Let that run in staging for at least a commit or two to validate tests are passing in staging.
1. Swap flutter/flutter .ci.yaml 
https://github.com/flutter/flutter/blob/2a502363e14111f50254b116699b03206207cafd/.ci.yaml#L134
https://github.com/flutter/flutter/blob/2a502363e14111f50254b116699b03206207cafd/.ci.yaml#L146
1. Update the rest of the infra fallback values
https://flutter.googlesource.com/infra/+/refs/heads/main/config/flutter_config.star#108
https://flutter.googlesource.com/infra/+/refs/heads/main/config/iostools_config.star#61
1. Update the remaining devices in the fleet.

**Comment by yusuf-goog** [comment]
iphone11 has been deployed to mac-44 and is ready to process jobs.

**Comment by yusuf-goog** [comment]
Next steps:

Once @jmagman has a chance to validate the mac-44 setup, we will then:

- Run setup steps on 3 more iphone11 devices
- Note their device ids, and select 3 hosts from the `staging` pool to swap them out with
- Update provisioning profiles and deploy
- Swap out the iphones on the 3 selected hosts
- Monitor to see everything is up and running as expected

**Comment by yusuf-goog** [comment]
Trying to run some builds using led on mac-44, but getting errors:

`led get-builder 'luci.flutter.prod:Mac_ios hello_world_ios__compile' | led edit -d id=flutter-devicelab-mac-44 | led edit -d pool=luci.flutter.prod | led edit -d device_os=iOS-16 | led edit -d cpu=arm64 |  led launch -modernize`

The fix is to save the output of `led get-builder 'luci.flutter.prod:Mac_ios hello_world_ios__compile' ` and remove the line `cleanup_cache:true`, before piping it into the rest of the command.

**Comment by yusuf-goog** [comment]
"The device may be running a version of iOS (16.2 20C65) that is not supported by this version of Xcode". @jmagman is going to create a new xcode cipd package, and we will try to run the tests again. 

All devices are being setup now, so they should all be at 16.2 at time of deployment.

**Comment by jmagman** [comment]
Filed https://github.com/flutter/flutter/issues/117505.

**Comment by jmagman** [comment]
@yusuf-goog what specifically is this issue tracking vs https://github.com/flutter/flutter/issues/111131?

**Comment by yusuf-goog** [comment]
This issue is meant for our new lab tech. His account has not been approved yet, so he's not on this.

**Comment by kentnguyen99** [comment]
Next step to configure & setup new iPhones 11 and upgrade iOS to version 16.2.

**Comment by jmagman** [comment]
https://github.com/flutter/flutter/issues/117505 has merged.  Please keep the iPhone 6s and cables so we can use them as test devices in the future in go/flutter-device-library (@yusuf-goog to be deposited on the test device pile desk in 1808 🙂 )

**Comment by yusuf-goog** [comment]
@jmagman Testing results are looking good, with no apparent failures. We are ready to continue to step 2. listed above. 

We expect to start the swap out on Thursday morning PST.

**Comment by yusuf-goog** [comment]
We will start with the following swaps:

Prod: mac-43, 42, 41, 30, 29, 28. 
mac-44 already has an iphone11.

Staging: mac-5, 7, 13.
mac-4 already has an iphone11.

Try: mac-1, 12

Once verified, we will continue upgrade of remaining devices in the pools.

**Comment by yusuf-goog** [comment]
provisioning profile CL: go/tircl/651552

**Comment by yusuf-goog** [comment]
We installed one iphone11 device on mac-43 to validate provisioning profile changes and our install procedure are correct. It installed correctly and was able to successfully run a build.

**Comment by yusuf-goog** [comment]
https://ci.chromium.org/ui/p/flutter/builders/staging/Mac_ios_staging%20test_drone/13/overview staging test ran on new ios-16 device successfully.

**Comment by yusuf-goog** [comment]
CL for step 6.: https://flutter-review.git.corp.google.com/c/infra/+/38129

**Comment by yusuf-goog** [comment]
All iphone11 are deployed to the lab.
