### ISSUE TITLE
My application throw Exception caught by image resource service with out any image in the code while navigation

### ISSUE THREAD

**Issue by MohamedSonata** [flutter/flutter#117284]
my application is like in For loop every time while navigation to any screen throws this error  just while navigation to different screen :

i don't have any image widget in my code  

 ```
======== Exception caught by image resource service 
================================================
The following ArgumentError was thrown resolving an image codec:
Invalid argument(s): No host specified in URI file:///src

When the exception was thrown, this was the stack: 
#0      _HttpClient._openUrl (dart:_http/http_impl.dart:2694:9)
#1      _HttpClient.getUrl (dart:_http/http_impl.dart:2596:48)
#2      NetworkImage._loadAsync (package:flutter/src/painting/_network_image_io.dart:106:59)
#3      NetworkImage.loadBuffer (package:flutter/src/painting/_network_image_io.dart:67:14)
#4      ImageProvider.resolveStreamForKey.<anonymous closure> (package:flutter/src/painting/image_provider.dart:513:13)
#5      ImageCache.putIfAbsent (package:flutter/src/painting/image_cache.dart:384:22)
#6      ImageProvider.resolveStreamForKey (package:flutter/src/painting/image_provider.dart:511:81)
#7      ScrollAwareImageProvider.resolveStreamForKey (package:flutter/src/widgets/scroll_aware_image_provider.dart:106:19)
#8      ImageProvider.resolve.<anonymous closure> (package:flutter/src/painting/image_provider.dart:358:9)
#9      ImageProvider._createErrorHandlerAndKey.<anonymous closure> (package:flutter/src/painting/image_provider.dart:473:24)
#10     SynchronousFuture.then (package:flutter/src/foundation/synchronous_future.dart:41:35)
#11     ImageProvider._createErrorHandlerAndKey (package:flutter/src/painting/image_provider.dart:470:9)
#12     ImageProvider.resolve (package:flutter/src/painting/image_provider.dart:355:5)
#13     _ImageState._resolveImage (package:flutter/src/widgets/image.dart:1115:16)
#14     _ImageState.didChangeDependencies (package:flutter/src/widgets/image.dart:1065:5)
#15     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5047:13)
#16     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#17     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2667:19)
#18     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:882:21)
#19     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:378:5)
#20     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1175:15)
#21     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1104:9)
#22     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1015:5)
#26     _invoke (dart:ui/hooks.dart:150:10)
#27     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:318:5)
#28     _drawFrame (dart:ui/hooks.dart:115:31)
(elided 3 frames from dart:async)
Image provider: NetworkImage("src", scale: 1.0)
Image key: NetworkImage("src", scale: 1.0)
```

**Comment by MohamedSonata** [comment]
![VOG-L29 12_18_2022 3_59_09 PM](https://user-images.githubusercontent.com/96669613/208302538-2cdbff99-671e-4e60-a383-fefb7d8714d4.png)

**Comment by darshankawar** [comment]
@MohamedSonata 
Can you provide `flutter doctor -v`, a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) without any third party plugin code along with steps to replicate that shows this error ?

**Comment by MohamedSonata** [comment]
@darshankawar 
this the response from flutter doctor isee every thing working well 
PS C:\Users\msona\MyProjects\preduro> flutter doctor -v
[√] Flutter (Channel stable, 3.3.10, on Microsoft Windows [Version 10.0.19044.2251], locale en-US)
    • Flutter version 3.3.10 on channel stable at C:\Users\msona\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (4 days ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\msona\AppData\Local\Android\sdk
    • Platform android-31, build-tools 33.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] VS Code, 64-bit edition (version 1.66.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.40.0

[√] Connected device (4 available)
    • VOG L29 (mobile)  • 22X0219A09002077 • android-arm64  • Android 10 (API 29)
    • Windows (desktop) • windows          • windows-x64    • Microsoft Windows [Version 10.0.19044.2251]
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 108.0.5359.124
    • Edge (web)        • edge             • web-javascript • Microsoft Edge 108.0.1462.46

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.


I'm trying to use IndexedStack widget to persist the state of scroll in main layout while changeing in bottom navigationbar  
but when trying to navigate to any screen else android system throw this error ...
and when trying to use PagestorageKey evry time changing in bottomNavBar the app rebuilding the state again and all screen has some thing like animation disappear and appear again from top to bottom 

https://user-images.githubusercontent.com/96669613/208439854-bd0a0832-3473-4a31-b17d-d6ba291179c1.mp4
