### ISSUE TITLE
CupertinoPicker 

### ISSUE THREAD

**Issue by bbaiqiang** [flutter/flutter#117208]
I use 5 Cupertinopickers on this dialog, when I quickly scroll any one of them for a while, it will get stuck. and I found that when it got stuck, its rendering time became huge.
Although I have commented out any processing and refreshing of the page in onSelectedItemChanged.
How can I solve this problem? 

<img width="691" alt="WeChat2394f51cbdacee8bd9cee060e6e31b52" src="https://user-images.githubusercontent.com/94350074/208075679-9b14047b-c022-489b-8cb0-a022da721ac2.png">

<img width="434" alt="WeChatf39dba363a888f856ff72bdd4282b432" src="https://user-images.githubusercontent.com/94350074/208076327-686e8cbf-b6a3-44b8-be45-1743ecfcb37d.png">

**Comment by darshankawar** [comment]
> I use 5 Cupertinopickers on this dialog,

@bbaiqiang I am wondering why do you have these many on a single dialog ? I am not sure if this implementation is correct according to design principles.

Coming back to your issue, can you provide `flutter doctor -v`, along with a complete minimal reproducible code sample that shows the reported behavior ?

**Comment by bbaiqiang** [comment]
> 
@darshankawar thanks for your reply! I want to create some special date picker, so I tried to use multiple Cupertinopickers to achieve.

```
[✓] Flutter (Channel stable, 3.3.9, on macOS 12.6 21G115 darwin-x64, locale zh-Hans-CN)
    • Flutter version 3.3.9 on channel stable at /Users/bq/Documents/project/test/.flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b8f7f1f986 (4 weeks ago), 2022-11-23 06:43:51 +0900
    • Engine revision 8f2221fbef
    • Dart version 2.18.5
    • DevTools version 2.15.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn
```


Just pop up this sample dialog, and quickly scroll one of the CupertinoPicker for 1-2 minutes, it will get stuck


import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

class TestDialog extends StatefulWidget {
  const TestDialog({Key? key}) : super(key: key);

  @override
  State<TestDialog> createState() => _TestDialogState();
}

```
class _TestDialogState extends State<TestDialog> {
  @override
  Widget build(BuildContext context) => Dialog(
        insetPadding: const EdgeInsets.all(16),
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(24)),
        child: Container(
          padding: const EdgeInsets.all(12),
          height: 160,
          child: Row(
            children: List.generate(
              5,
              (pickerIndex) => Expanded(
                child: CupertinoPicker(
                  itemExtent: 32,
                  magnification: 1.2,
                  onSelectedItemChanged: print,
                  children: List.generate(
                    100,
                    (index) => Container(
                      alignment: Alignment.center,
                      child: Text(
                        '$pickerIndex - $index',
                        style: const TextStyle(
                          fontSize: 14,
                        ),
                      ),
                    ),
                  ),
                ),
              ),
            ),
          ),
        ),
      );
}
```

**Comment by bbaiqiang** [comment]
Oh, it's the first time I ask a question on github, so I clicked to close the question by mistake.

**Comment by darshankawar** [comment]
I ran the code sample provided on latest master using iOS simulator but was unable to replicate the reported behavior. I scrolled one of the pickers continuously for couple of minutes and it didn't get stuck. Also, other pickers also scrolled smoothly without any issues.

**Comment by bbaiqiang** [comment]
> I ran the code sample provided on latest master using iOS simulator but was unable to replicate the reported behavior. I scrolled one of the pickers continuously for couple of minutes and it didn't get stuck. Also, other pickers also scrolled smoothly without any issues.

I ran the flutter upgrade command, it is 3.3.10 now, but the problem persists. It works fine in iOS, this problem happens in macOS desktop app.

![1](https://user-images.githubusercontent.com/94350074/208381573-6738f861-504b-4591-8364-cd30fcf488b8.gif)

**Comment by darshankawar** [comment]
I tried the same on latest stable running on macOS desktop, but was unable to replicate the issue.


https://user-images.githubusercontent.com/67046386/208592055-d14df882-6c9e-4007-90c5-2705e7937e7c.mov
