### ISSUE TITLE
Different context handling at Runtime under iOS and Android

### ISSUE THREAD

**Issue by robertosw** [flutter/flutter#117212]
I did check with the plugin creator of inappwebview. This is not related to the plugin, but seems to be a problem with flutters iOS Implementation.

## Description

Outsourced functions get the BuildContext only once when the class is created. If the build function is called afterwards and the context has changed, the outsourced functions continue to access the old context. This is only an Issue under iOS, Android does not seem to care about this at all.

Example code:
```Dart
  @override
  void initState() {
    print("initState: ${context.hashCode}");
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return InAppWebView(
       onLoadStart: myLoadStartFunction,
     ),
   };

   void myLoadStartFunction(InAppWebViewController controller, WebUri? url) {
      // If you try to access the context in here, an error is thrown that this widget is unmounted. 
      // But the widget is mounted, but with a different state and BuildContext.
    }
```

**Expected behavior:**  If you relocate the functions that the WebView calls, so that they are parallel to the build method, they will still work.

**Current behavior:** `myLoadStartFunction` always accesses the old BuildContext, this can be seen if you log the context.hashCode in initState and from inside `myLoadStartFunction`

## Steps to reproduce

Code needed to reproduce seen above. BuildContext changes in my app everytime one webpage has finished loading. The new loading process will have a new BuildContext

## Temporary Solution:
Call your outsourced methods inside the build method and give them the current BuildContext
```Dart
@override
  Widget build(BuildContext context) {
    return InAppWebView(
      shouldOverrideUrlLoading: (controller, navigationAction) async => await wvLoadRequest(context, controller, navigationAction),
      onLoadStart: (controller, url) => wvLoadStart(context, controller, url),
    );
  }

  Future<NavigationActionPolicy> wvLoadRequest(BuildContext context, InAppWebViewController controller, NavigationAction navigationAction) async {...}

  void wvLoadStart(BuildContext context, InAppWebViewController controller, WebUri? url) => {Globals().currentUrl = url.toString()};
```

## Logs

`flutter analyze`: `No issues found`

 `flutter doctor -v`:
```
developer@Developers-Air ios % flutter doctor -v
[✓] Flutter (Channel stable, 3.3.8, on macOS 13.0 22A380 darwin-x64, locale de-DE)
    • Flutter version 3.3.8 on channel stable at /Users/developer/Documents/Flutter/SDK/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 52b3dc25f6 (5 weeks ago), 2022-11-09 12:09:26 +0800
    • Engine revision 857bd6b74c
    • Dart version 2.18.4
    • DevTools version 2.15.0

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] Connected device (3 available)
    • 8 Plus - 5,5 inch (mobile) • 00883CDB-9E50-47D8-B93F-DEDE933684A5 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-1 (simulator)
    • macOS (desktop)            • macos                                • darwin-x64     • macOS 13.0 22A380 darwin-x64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 108.0.5359.124

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.
```

**Comment by huycozy** [comment]
Hi @robertosw 
For the issue to be workable, it needs to be reproducible with a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code. Please provide such a sample so that we may verify it. Thank you!

**Comment by robertosw** [comment]
I will try to prove this without the use of third party plugins. My problem is, I cannot reliably trigger the "creation" of a new context in normal flutter widgets.
This way easy in this third party plugin, since the context always changed when a website finished loading.

**Comment by robertosw** [comment]
Okay.. I cannot even prove this with a universal example **using** the plugin. And I cannot get the context to change using just flutters widgets and keeping one widget alive, to see the context change.
So this has to be some weird edge case in my app.
