### ISSUE TITLE
[CP] Add a recursive flag to the zip command

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#117254]
### issue_link

https://github.com/flutter/flutter/pull/117253

### Commit Hash

0604a0e

### Target

beta

### pr_link

https://github.com/flutter/flutter/pull/117253

### Impacted Users

release engineering team

### Impact Description

Stable docs are not uploaded.

### Workaround

N/A

### Risk

low

### Test Coverage

yes

### Validation Steps

Validation in dart-internal builds

**Comment by itsjustkevin** [comment]
@godofredoc was this meant to have a cherry-pick for beta?  The pr link points to the stable branch.

**Comment by godofredoc** [comment]
Yes, let me update it!

**Comment by godofredoc** [comment]
Read only the first part of your comment in the phone, thanks for updating it.
