### ISSUE TITLE
Moving a Flutter desktop window between screens can fail

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#117247]
this problem occurs when I drag my Flutter app window from my MacBook screen to the second screen, which is much bigger. For example with the flutter_created Counter app, on the Macbook's screen:

![image](https://user-images.githubusercontent.com/1377460/208208507-3726c132-4161-46a3-b569-f0e49a9ccb92.png)

Same app after being dragged onto my ginourmous ThinkVision screen:

![image](https://user-images.githubusercontent.com/1377460/208208541-440e7226-1037-4641-9404-62f11d233f3a.png)

The two displays have a different pixel density, since the secondary monitor is about twice as big as the internal one:
```
Color LCD:
  Display Type: Built-in Liquid Retina XDR Display
   Resolution: 3456 x 2234 Retina
   Main Display: Yes
   Mirror: Off

LEN T32p-20:
   Resolution: 3840 x 2160 (2160p/4K UHD 1 - Ultra High Definition)
   UI Looks like: 3840 x 2160 @ 60.00Hz
   Mirror: Off
```

**Comment by HansMuller** [comment]
CC @moffatman - it's possible that this bug is related to https://github.com/flutter/flutter/pull/114459 however at the moment there's no evidence for that; it's just a possibility.

**Comment by stuartmorgan** [comment]
This was fixed years ago [here](https://github.com/flutter/engine/pull/13933). Do we know this is broken in the framework this time rather than this being an engine regression?

**Comment by TahaTesser** [comment]
Running into this regression on master.  This is introduced in https://github.com/flutter/flutter/commit/9aa2ea150cccdf383d204a8a76e50259b74bd7a3

**Comment by knopp** [comment]
I can reproduce the problem. Issue here is that we're using `CALayer.contentScale`, to position the surface layer, but the `contentScale` gets not automatically updated when window backing scale changed. I'll have a PR for this soon.
