### ISSUE TITLE
calling dart:developer postEvent() in profile mode causes a crash

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter#11728]
When my app is compiled in profile mode, calling `postEvent` from the `dart:developer` library causes a crash:

```
E/DartVM  (13226): ../../dart/runtime/vm/object.cc: 13854: error: unreachable code
E/DartVM  (13226): Dumping native stack trace for thread 33cc
E/DartVM  (13226):   [0xd2385159] Unknown symbol
E/DartVM  (13226):   [0xd2385159] Unknown symbol
E/DartVM  (13226): -- End of DumpStackTrace
F/libc    (13226): Fatal signal 6 (SIGABRT), code -6 in tid 13260 (ui_thread)
```

I believe this method should be supported in profile mode. The use case I have is firing events for frames, in order to support things like displaying FPS and frame info in tooling.

See https://github.com/flutter/flutter/pull/11565#issuecomment-323949532 for more details.

/cc @a-siva

**Comment by a-siva** [comment]
@B3rn475

**Comment by devoncarew** [comment]
Closing in favor of https://github.com/dart-lang/sdk/issues/30522.
