### ISSUE TITLE
[in_app_purchase] Recently created subscriptions through google play store are not identified by Example App

### ISSUE THREAD

**Issue by Charlinjoeaht** [flutter/flutter#117274]
**Package:** [in_app_purchase](https://pub.dev/packages/in_app_purchase) 3.0.8
**OS:** Android
**Problem:**
I downloaded the in_app_purchase example from [Github](https://github.com/flutter/plugins/tree/main/packages/in_app_purchase/in_app_purchase)

I created my new app recently and configured the **In-app products** and **Subscriptions**.

I did the required changes in the example app to link to my Play store app.
All the **In-app products** created in play store are working well. But, **Subscriptions** are not detecting correctly by the example app

While running the app "_[subscription_silver] not found_" error is displayed on the app

**Comment by Charlinjoeaht** [comment]
Package: [in_app_purchase 3.0.8](https://pub.dev/packages/in_app_purchase)
OS: Android

**Comment by huycozy** [comment]
Hi @Charlinjoeaht 
Does it work well before? If so, which `in_app_purchase` plugin version did it work? And please provide the complete log from `flutter run -v` so that we may verify it. Thanks!

**Comment by Charlinjoeaht** [comment]
This is the first time I am using `in_app_purchase` plugin and subscription from play store. Following is the log after running the app with `flutter run -v`

[flutter.log](https://github.com/flutter/flutter/files/10303413/flutter.log)

**Comment by huycozy** [comment]
@Charlinjoeaht I think there is something missing from your account configuration. Please check this old issue and find the information that may be helpful: https://github.com/flutter/flutter/issues/112822#issuecomment-1266740250

**Comment by jatin-web** [comment]
> **Package:** [in_app_purchase](https://pub.dev/packages/in_app_purchase) 3.0.8 **OS:** Android **Problem:** I downloaded the in_app_purchase example from [Github](https://github.com/flutter/plugins/tree/main/packages/in_app_purchase/in_app_purchase)
> 
> I created my new app recently and configured the **In-app products** and **Subscriptions**.
> 
> I did the required changes in the example app to link to my Play store app. All the **In-app products** created in play store are working well. But, **Subscriptions** are not detecting correctly by the example app
> 
> While running the app "_[subscription_silver] not found_" error is displayed on the app

I am having problems in showing the available subscriptions. Can you please help me with that?
