### ISSUE TITLE
[tracking] Speed up asset manifest loading and parsing

### ISSUE THREAD

**Issue by andrewkolos** [flutter/flutter#117228]
This issue tracks development that will speed up asset manifest loading and parsing, which will in turn speed up the first asset load that a Flutter app performs.

This was originally intended to perform as one change (https://github.com/flutter/flutter/pull/113637), with followup clean-up/tech-debt then to follow (https://github.com/flutter/flutter/issues/114913). However, due to problems with specific g3 tests, this is being split up into smaller changes.

## Background

When loading an asset for the first time, the framework has to load a file called the asset manifest, which contains information about assets available to the app (for example, where to find higher-resolution [variants of images](https://docs.flutter.dev/development/ui/assets-and-images#asset-variants)). This file is in the JSON format.

Reading the file from storage, decoding into UTF, and parsing it as JSON is generally slower than we'd like, especially since this is will all likely happen on first paint (since many apps include assets on their first screens).

The asset manifest (`AssetManifest.json`) is created at build time.

## Desired Change
The idea is to use a binary format rather than JSON for the asset manifest file. In particular, we'll use the [standard_message_codec package](https://pub.dev/packages/standard_message_codec) for encoding the manifest at build time and decoding it at runtime. This new manifest will be stored in a new file, `AssetManifest.bin`. In addition, for decoding the binary message, we'll lazily put off typecasting until we read individual keys--avoiding upfront typecasting for all entries. This will achieve a significant speedup for first asset load, especially on less powerful devices.

## Tasks

[x] Update `flutter_tools` to produce `AssetManifest.bin`. https://github.com/flutter/flutter/pull/117233
[x] After that change rolls, update g3 tool code to produce `AssetManifest.bin`.
[x] Add new framework API for consuming the asset manifest. ~~#118410~~ https://github.com/flutter/flutter/pull/119277
[x] Update framework to consume `AssetManifest.bin` ~~#118782~~ ~~#121322~~ https://github.com/flutter/flutter/pull/122505
[ ] After a full deprecation cycle and process, remove tool code that generates `AssetManifest.json`[^1]

[^1]: While AssetManifest.json is not officially documented, some users decided to depend on it based on recommendation from flutter developers. Removing it outright would break them. For example, Google Fonts [reads it](https://github.com/material-foundation/google-fonts-flutter/blob/3328a833a921f7b2e6f13fa8e2f5c06933421ccc/lib/src/asset_manifest.dart#L28) to [determine whether or not a font can be loaded from the device rather than loading it over HTTP](https://github.com/material-foundation/google-fonts-flutter/blob/3328a833a921f7b2e6f13fa8e2f5c06933421ccc/lib/src/google_fonts_base.dart#L136).

**Comment by andrewkolos** [comment]
An update since it has been a while: I still plan on starting the deprecation process soon<sup>TM</sup>.

**Comment by feinstein** [comment]
Will this solve the "blinking" problem we see when loading an image from assets? Many people use the `AssetManifest.json` to pre-cache all images into memory and avoid images/SVG suddenly appearing on screen.

**Comment by andrewkolos** [comment]
> Will this solve the "blinking" problem we see when loading an image from assets?
> 
> Many people use the `AssetManifest.json` to pre-cache all images into memory and avoid images/SVG suddenly appearing on screen. So if pre-cache will still be needed, then it would be nice to have helper functions to traverse that binary file.

Oh, I'm sorry, this issue should have been closed as completed by https://github.com/flutter/flutter/pull/122505 long ago.
This change made it into the 3.7 release, if I recall correctly, so if you have seen image loading jank since then, it's probably still an issue. You may want to file an issue if one isn't already open on the subject.
