### ISSUE TITLE
devicelab tests want ANDROID_SDK_ROOT but it is deprecated

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#117245]
If you run the devicelab tests it will complain that ANDROID_SDK_ROOT is not set.  But if you set it, you'll no longer be able to compile the flutter engine because of the following error:

```
* What went wrong:
Could not determine the dependencies of task ':app:lintDebug'.
> Several environment variables and/or system properties contain different paths to the SDK.
  Please correct and use only one way to inject the SDK location.
  
  ANDROID_HOME: /Users/aaclarke/dev/engine/src/third_party/android_tools/sdk
  ANDROID_SDK_ROOT: /Users/aaclarke/Library/Android/sdk
  
  It is recommended to use ANDROID_HOME as other methods are deprecated
```

**Comment by Hixie** [comment]
Conclusion from triage meeting discussion:
- to fix this, search for any error message in flutter/flutter that mentions "ANDROID_SDK_ROOT" and change it to "ANDROID_HOME".
- because this includes at least one change in flutter_tools, I'm assigning this to team-tool.
