### ISSUE TITLE
flutter upgrade (dart sdk download) can never complete because of incorrect curl command in update_dart_sdk.sh

### ISSUE THREAD

**Issue by sgon00** [flutter/flutter#11722]
I am in a country where accessing overseas network is very unstable (unreliable). My overseas connection is always interrupted/dropped/reset.

It becomes a serious issue when the download process can not be resumed.

I tried to execute `flutter upgrade` and it could never complete. When downloading dart sdk, it always met `curl: (56) Unexpected EOF` error message. I thought it should resume the download when I restart the upgrade process, but it didn't.
 
To further investigate the bug, I found out the `curl` command was called by the script `flutter/bin/internal/update_dart_sdk.sh`. And the `curl` command is incorrect in my linux OS. The curl command in the current `update_dart_sdk.sh` is: 
```
curl -continue-at=- --location --output "$DART_SDK_ZIP" "$DART_SDK_URL" 2>&1
```
But it should be 
```
curl --continue-at - --location --output "$DART_SDK_ZIP" "$DART_SDK_URL" 2>&1
```

__Note:__ It is `--continue-at -` instead of `-continue-at=-`

After changing the incorrect `curl` command and re-run `flutter upgrade` several times, I can finally complete the dart sdk download process. Otherwise, if it always starts to download from scratch, the dart sdk download process can never complete. 

## Flutter version

[✓] Flutter (on Linux, locale en_US.UTF-8, channel master)
    • Flutter at /home/song/opt/flutter
    • Framework revision 5462ddb917 (4 hours ago), 2017-08-21 16:17:54 -0700
    • Engine revision 600567ef15
    • Tools Dart version 1.25.0-dev.11.0

**Comment by eseidelGoogle** [comment]
Sounds like an easy win.  Thoughts @tvolkert @jason-simmons?

**Comment by ngima** [comment]
Although in my update_dart_sdk.sh
`curl --continue-at - --location --output "$DART_SDK_ZIP" "$DART_SDK_URL" 2>&1
`
I am getting this error:

> Downloading Dart SDK from Flutter engine ead227f118077d1f2b57842a32abaf105b573b8a...
> /home/ngima/Android/flutter/bin/internal/update_dart_sdk.sh: line 54: curl: command not found

**Comment by vjbharani** [comment]
i have an issue on line 40 on the above file,
  DART_SDK_BASE_URL="${FLUTTER_STORAGE_BASE_URL:-https://storage.googleapis.com}"
it says command not found if i run flutter doctor,and sdk starts downloading.
