### ISSUE TITLE
Scroll performance regression

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#11721]
The following benchmarks recently regressed when we rolled the engine in https://github.com/flutter/flutter/pull/11693:

complex_layout_scroll_perf__timeline_summary average_frame_build_time_millis
complex_layout_scroll_perf__timeline_summary average_frame_rasterizer_time_millis
complex_layout_scroll_perf__timeline_summary missed_frame_rasterizer_budget_count
flutter_gallery__transition_perf average_frame_build_time_millis
flutter_gallery__transition_perf average_frame_rasterizer_time_millis
flutter_gallery__transition_perf_with_semantics delta_average_frame_build_time_millis
microbenchmarks stock_animation_open_first_frame_average

In particular, rasterisation on some benchmarks regressed at least 5x.

Anecdotally, @eseidel also observed that scroll performance on Moto G4s today is very bad.

The engine roll in question included rolling Dart and rolling Skia.

cc @jason-simmons @chinmaygarde

**Comment by yjbanov** [comment]
The drop in frame rate is quite observable. I think we should revert unless someone already knows how to fix it quickly.

**Comment by chinmaygarde** [comment]
I will investigate. We can revert the roll in the meantime.

**Comment by jason-simmons** [comment]
This is due to a change in Skia:
    https://github.com/google/skia/commit/20af6d12eefd8d937bc13bdb7fa0a9ac86b699af

**Comment by jason-simmons** [comment]
Skia rolled this back, and we've deployed an updated engine.
