### ISSUE TITLE
Add goma warnings to the `gn` script

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#117238]
When executing `gn` with goma enabled, it should warn the user if the following aren't right:

- GOMA_DIR is set
- `$GOMA_DIR/gomacc` exists (it doesn't exist if you accidentally use depot_tools
- (if mac) FLUTTER_GOMA_CREATE_XCODE_SYMLINKS=1
- GOMA_SERVER_HOST=rbe-prod1.endpoints.fuchsia-infra-goma-prod.cloud.goog
- GOMA_SERVER_PORT=443

cc @bdero

**Comment by reidbaker** [comment]
I was following what I thought were helpful instructions when I broke my engine setup. 

Link and quote below. 
https://github.com/flutter/flutter/wiki/Compiling-the-engine
"Before that, you may need to set up GOMA_DIR environmental variable, which, depending on where you install Goma, may be in ~/goma or depot_tools/.cipd_bin."

**Comment by chinmaygarde** [comment]
Having something like a `gn doctor` command is definitely something we should do.

**Comment by chinmaygarde** [comment]
From Triage: @zanderso also mentioned another issue. We seem to be falling back to goma from depot_tools still. We should be doing what the wiki says. Another reason to have a doctor for goma.

**Comment by zanderso** [comment]
I've heard more about new team members having difficulty getting set up correctly, so I'm going to look into making improvements here after the upcoming branch cut.

**Comment by cbracken** [comment]
Re:
```
GOMA_SERVER_HOST=rbe-prod1.endpoints.fuchsia-infra-goma-prod.cloud.goog
GOMA_SERVER_PORT=443
```
Setting those should not be necessary if you've downloaded the goma toolchain linked to in our Wiki. Those are the defaults already found in goma_auth.py:
```
% grep -r GOMA_SERVER_HOST .
Binary file ./goma_fetch matches
./goma_auth.py:DEFAULT_GOMA_SERVER_HOST = 'rbe-prod1.endpoints.fuchsia-infra-goma-prod.cloud.goog'
```

**Comment by zanderso** [comment]
The logic was cleaned up a bit in https://github.com/flutter/engine/pull/40817. A correctly matching goma client download was added in https://github.com/flutter/engine/pull/41488. The logic and defaults were further refined in https://github.com/flutter/engine/pull/43584. I'm going to call this one done, but we can also follow-up with more specific improvements as needed.
