### ISSUE TITLE
Please clarify the documentation of `StatefulWidget.build` method

### ISSUE THREAD

**Issue by gintominto5329** [flutter/flutter#117264]
Hello,

In the "Performance considerations" section of StatefulWidget [documentation](https://master-api.flutter.dev/flutter/widgets/StatefulWidget-class.html), third point mentions the following:

> If a subtree does not change, cache the widget that represents that subtree and re-use it each time it can be used. To do this, assign a widget to a final state variable and re-use it in the build method. It is massively more efficient for a widget to be re-used than for a new (but identically-configured) widget to be created. Another caching strategy consists in extracting the mutable part of the widget into a [StatefulWidget](https://master-api.flutter.dev/flutter/widgets/StatefulWidget-class.html) which accepts a child parameter.

Its not clear that what is "state variable" here, and what to to assign, because "build" term is mentioned in that line, and there is also a `build` method for every widget,

I mean,

Should the user do `final Widget widget = MyWidget();` or `final Widget widget = MyWidget().build(context);`

As they both return `Widget`,

thanking you

**Comment by goderbauer** [comment]
`final Widget widget = MyWidget();` is what the doc means.

**Comment by piedcipher** [comment]
Shall we close this as solved or add the line in doc?
