### ISSUE TITLE
Screen resetting ad infinitum: Problem with vscode, flutter multiple monitors and win10

### ISSUE THREAD

**Issue by mnaught** [flutter/flutter#117288]
## Steps to Reproduce

1. launch vscode by right clicking the vsc icon and selecting New WIndow
2. use the flutter command New Flutter Project
3. specifiy folder and project name
4. result: vscode creates the project scaffolding 
5. result: the primary monitor blanks, the vscode window moves to the secondary window, the primary monitor then comes back on, then goes blank and this continues until I log out and log back in to the windows desktop.  vscode is unusable at this point because everytime the primary monitor refreshes from blank screen, the cursor resets to the primary monitor.

I should note that I get a similar less severe monitor reset symptom when I run flutter from the command line.  (see the flutter doctor section for more info.)   

also, I have been running this system for years.  I can create other project types in vscode just fine.  

## Logs

<details>
<summary>Logs</summary>

```
haven't been able to grab any output because as I say, once it starts cycling the primary monitor I can't use the desktop and must relog into the account (cannot kill vscode task either)

<!-- If possible, paste the output of running `flutter doctor -v` here. -->

```flutter doctor causes the screen to go black but then DOES stabilize and displays output.
``` but still the command window moves to the secondary monitor.
it's almost as if it's detaching the primary monitor as all windows move over to the secondary display.

C:>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.3.10, on Microsoft Windows [Version 10.0.19044.2364], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version
    31.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.0.5)
[√] Android Studio (version 2021.3)
[√] VS Code, 32-bit edition (version 1.74.1)
[√] Connected device (3 available)
[√] HTTP Host Availability

• No issues found!

</details>

**Comment by huycozy** [comment]
Hi @mnaught, thanks for reporting the issue. But I'm not sure I can imagine/replicate the 5th step. Would you mind providing a recorded video of the steps to reproduce this issue? Thanks a lot!

**Comment by mnaught** [comment]
OK here's two:
[demo 1](https://youtu.be/aKWNAAk0JTs): showing video bounce when running flutter doctor from command line, as well as the "infinite reset" which occurs on monitor one when creating a flutter project in vscode.
demo 2](https://youtu.be/SNT9d-rp1Ok): showing the same thing happens in android studio.

I realize this is probably not a vscode issue specifically.  It seems to be happening when the flutter sdk binaries are invoked either directly or via the ide.  I am trying to get better instrumentation on what's happening, but am out of ideas.  Any help appreciated, even redirects to other communities.  Thanks for looking!

**Comment by huycozy** [comment]
@mnaught Thanks for your recorded video. I have tried on my PC with two monitors LG ULTRAWIDE and DELL P2319H but can't reproduce this issue. 

As I see from your 2nd video (with Android Studio), a part of the issue also happens with Android native project (auto moved to secondary monitor). 

Could you try some experiments below?
1. Change the cable between two monitors and retry
2. Check the Refresh Rate of each monitor in Advanced display settings. Try setting them to be equal and retry.

**Comment by mnaught** [comment]
This will take some time for me to get to with the holidays.  Please leave this open.  I'll post when I've completed your suggestions! thanks.

**Comment by mnaught** [comment]
Well it doesn't seem related to multimonitor after all..
As you suggested I just tried setting both refresh rates to 60hz noninterlaced.  Same result.
I updated the nvidia video driver.
Also, I disabled 2 and ran only on monitor 1. Same result.  reset occurs in single monitor mode with flutter projects in both vscode and androidStudio.

I disabled 1 and ran only on 2.  Same result.  (this one surprised me.  I thought the big screen was likely suspect but it's happening when I run on the benq only)

I'm looking at event logs.
I am seeing DCOM errors of the type 'application specific permission settings do not grant local activation permission for the COM server applications with clsid and appids <some guids I haven't figured out how to trace.>'

These roughly correlate with my launch of the apps.

More info:  I installed from git, if that makes any difference.
I will try replacing cables when I get a chance after the holidays.
I'll also fiddle with video driver settings.
And possibly reinstall.
If there's a log that you know of I can look at in the sdk that'd be useful.
Thanks.!

**Comment by huycozy** [comment]
@mnaught I'm not sure if this issue is related to Flutter since it's also happening a part with Android Studio (native project). 
I would suggest you keep an eye on it to see if it has any pattern with minimal steps to reproduce. Reinstalling IDE or connecting the monitor with another PC/laptop may be experiments you can try.

**Comment by huycozy** [comment]
@mnaught I see that there are some reported issues that may be related to this: 

- https://issuetracker.google.com/issues/220618419?pli=1
- https://github.com/Dart-Code/Dart-Code/issues/3839
- https://github.com/flutter/flutter/issues/117506 (maybe related but it's on Linux and Flutter `stable` channel)

Can you check [Windows alternative of dmesg](https://superuser.com/questions/501982/what-is-the-equivalent-of-dmesg-on-winxp-and-later) to see if there is a log `root hub lost power or was reset`?

**Comment by mnaught** [comment]
was able to replace the hdmi cable and repro the same problem in a single screen configuration.

**Comment by huycozy** [comment]
I'm not sure whether this issue belongs to Flutter or not. I'm labeling the issue for further insights from the team. 

May be related: #117506

**Comment by mnaught** [comment]
Hi 
Thanks for the reply.    I couldn't trigger the problem with those steps.  Notes inlined:

> * Check if it occurs if you open a non-Flutter Dart project (eg. use Dart: New Project). If it does not, it might be something specific to the tools spawned for Flutter.

Result: Created dart project, no screen issues.

> 
> * If it's only Flutter, check whether running the device daemon triggers the issue:
>   
>   * Run flutter daemon from a terminal
>   * Paste in [{"id":"1","method":"emulator.getEmulators"}] and then press
>   * This should start the Flutter daemon running (which the editors use to get a realtime updated device list)
>   * After confirming if this triggers it (or not), use Ctrl+C to close

Result: 
ouput was:
Microsoft Windows [Version 10.0.19044.2364]
(c) Microsoft Corporation. All rights reserved.

C:\Users\Matt>flutter daemon
[{"event":"daemon.connected","params":{"version":"0.6.1","pid":9560}}]
[{"event":"daemon.logMessage","params":{"level":"status","message":"Starting device daemon..."}}]
[{"id":"1","method":"emulator.getEmulators"}]
[{"id":"1","result":[{"id":"Pixel_3_XL_API_31","name":"Pixel 3 XL API 31","category":"mobile","platformType":"android"}]}]

No screen issues .

> 
> * If it's only Flutter, but the above doesn't trigger it, try running DevTools
>   
>   * Run dart devtools --machine from the terminal
>   * After confirming if this triggers it (or not), use Ctrl+C to close

Result: devtools starts, opens a browser to it's UI.  No screen issues.

It still happens if I run flutter doctor, or create (or open) a flutter project in vscode or android studio.  multiscreen isn't an issue after all, if I reduce to just one monitor (either) It still triggers infinate monitor blanking.

I agree that it appears to be happening at the interface between the ides or shell and the flutter sdk.  I'm currently looking at procman traces to see if I can't localize it a bit.

**Comment by Hixie** [comment]
Can you take a video of it happening when run `flutter doctor -vv` (two `v`s)? maybe there's something that flutter doctor is doing that is triggering it, and the logs might tell us where it's happening...

If you really want to get your hands dirty you could try running `flutter doctor` in the debugger and stepping through to see what triggers it...
