### ISSUE TITLE
[webview_flutter] V4 webview migration doc

### ISSUE THREAD

**Issue by zakblacki** [flutter/flutter#117299]
Documentation not clear enough how do I upgrade the following code after V4

```
final Completer<WebViewController> _controller = Completer<WebViewController>();
WebView.platform = SurfaceAndroidWebView();

WebView(
            initialUrl: widget.url,
            javascriptMode: JavascriptMode.unrestricted,
            onWebViewCreated: (WebViewController webViewController) {
              _controller.complete(webViewController);
            },
           navigationDelegate: (NavigationRequest request) {}
            onProgress: (progress) {},
            gestureNavigationEnabled: true,
          ),
```

**Comment by zakblacki** [comment]
> @zakblacki Can you be more detailed about how unclear it is? Please check this [guideline](https://pub.dev/packages/webview_flutter#migrating-from-30-to-40) as a reference for this.

I would had preferred a concrete example instead of that

**Comment by huycozy** [comment]
Please check [usage](https://pub.dev/packages/webview_flutter#usage) section as an updated snippet code or you can find a complete sample code at [plugin example repository](https://github.com/flutter/plugins/tree/main/packages/webview_flutter/webview_flutter/example).

**Comment by zakblacki** [comment]
Yes solved 

`  WebViewController controller = WebViewController();

    controller = WebViewController()
  ..setJavaScriptMode(JavaScriptMode.unrestricted)
  ..setBackgroundColor(const Color(0x00000000))
  ..loadRequest(Uri.parse(widget.url))
  ..setNavigationDelegate(NavigationDelegate(
    onProgress: (progress) {
      if (progress >= 100) {
        setState(() {
          isLoading = false;
        });
      }
    },
  ));

 WebViewWidget(controller: controller)
`
