### ISSUE TITLE
Dispose never called when app gets killed

### ISSUE THREAD

**Issue by amityamsi** [flutter/flutter#117283]
-
     Please tell us the problem you are running into that led to you wanting
     a new feature.

I am trying to implementing some function when app get killed and i used Dispose for that as mentioned by many articles but after testing that i found out that dispose never called when app gets killed.
Dispose called when navigation or killing of screen/page and not the app
-
     Is your feature request related to a problem? Please give a clear and
     concise description of what the problem is.

-
 I am using Firebase database with Flutter for video calling and when user end the call then it will reflect in Firebase But if Phone switched off accidentally then How can i update the Firebase for end the call and notify other user that call is end 
-
     Describe the alternative solutions you've considered. Is there a package
     on pub.dev/flutter that already solves this?
-->  No yet

**Comment by stuartmorgan** [comment]
Mobile operating systems don't provide applications an opportunity to run code when they are killed in the background.

Closing as this is an OS limitation.
