### ISSUE TITLE
android4.2    library "libnative_add.so" not found.

### ISSUE THREAD

**Issue by luhuajcdd** [flutter/flutter#117306]
environment:   
android4.2 emulator  and  android4.2 device

flutter --version
Flutter 3.3.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision eb6d86ee27 (3 months ago) • 2022-10-04 22:31:45 -0700
Engine • revision c08d7d5efc
Tools • Dart 2.18.2 • DevTools 2.15.0

error: 

```
Invalid argument(s): Failed to load dynamic library 'libnative_add.so': Cannot load library: load_library(linker.cpp:745): library "libnative_add.so" not found

When the exception was thrown, this was the stack: 
#0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:12:43)
#1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:23:12)
#2      nativeAddLib (package:native_add_example/main.dart:13:26)
```

note: on android 8.1   it's ok.

code: 
native_add.cpp:
```
`#include <stdint.h>
#include <stdio.h>
#include <unistd.h>
#include <thread>
#include "AndroidLog.h"

#ifdef WIN32
#define DART_API extern "C" __declspec(dllexport)
#else
#define DART_API extern "C" __attribute__((visibility("default"))) __attribute__((used))
#endif

DART_API int32_t native_add(int32_t x, int32_t y)
{
    return x + 2 * y;
}

DART_API void callDart(void (*callback)()) {

    printf("[CPP]: 现在调用Dart函数");
    LOGD("[CPP]: 现在调用Dart函数");



    printf("now pid is %d \n", getpid());
    printf("now tid is %d \n", gettid());

    LOGD("[CPP]: now pid is %d \n", getpid());
    LOGD("[CPP]: now tid is %d \n", gettid());

    //std::thread t1(callback);
    //t1.join();

    callback();
}`
```

main.dart
```
`import 'package:flutter/material.dart';
import 'dart:async';

import 'package:flutter/services.dart';
import 'package:native_add/native_add.dart';

import 'dart:ffi' as ffi; // For FFI
import 'dart:io'; // For Platform.isX



final ffi.DynamicLibrary nativeAddLib = Platform.isAndroid
    ? ffi.DynamicLibrary.open('libnative_add.so')
    : ffi.DynamicLibrary.process();

final int Function(int x, int y) nativeAdd = nativeAddLib
    .lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Int32, ffi.Int32)>>('native_add')
    .asFunction();

late final _callDartPtr = nativeAddLib.lookup<ffi.NativeFunction<
    ffi.Void Function(ffi.Pointer<ffi.NativeFunction<ffi.Void Function()>>)>>('callDart');

late final _callDart = _callDartPtr.asFunction<void Function(ffi.Pointer<ffi.NativeFunction<ffi.Void Function()>>)>();


void dartFunction() {
  debugPrint("[Dart]: Dart 函数被调用了");
}


void main() {
  runApp(const MyApp());
}

class MyApp extends StatefulWidget {
  const MyApp({super.key});

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  String _platformVersion = 'Unknown';
  final _nativeAddPlugin = NativeAdd();

  @override
  void initState() {
    super.initState();
    initPlatformState();
    _callDart(ffi.Pointer.fromFunction(dartFunction));
  }

  // Platform messages are asynchronous, so we initialize in an async method.
  Future<void> initPlatformState() async {
    String platformVersion;
    // Platform messages may fail, so we use a try/catch PlatformException.
    // We also handle the message potentially returning null.
    try {
      platformVersion =
          await _nativeAddPlugin.getPlatformVersion() ?? 'Unknown platform version';
      debugPrint('platformVersion = ${platformVersion}');
    } on PlatformException {
      platformVersion = 'Failed to get platform version.';
    }

    // If the widget was removed from the tree while the asynchronous platform
    // message was in flight, we want to discard the reply rather than calling
    // setState to update our non-existent appearance.
    if (!mounted) return;

    setState(() {
      _platformVersion = platformVersion;
    });
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Plugin example app'),
        ),
        body: Center(
          child: Text('1 + 2 == ${nativeAdd(1, 2)}'),
        ),
      ),
    );
  }
}
`
```

```
(base) test-5:~ test$ adb devices
List of devices attached
emulator-5554	device
```

```
(base) test-5:~ test$ adb shell 
root@android:/ # ls /data/data/com.example.native_add_example/lib/
libflutter.so
libnative_add.so
```

**Comment by luhuajcdd** [comment]
@ianloic @anaisbetts @sgraham @gmoothart

**Comment by dcharkes** [comment]
@luhuajcdd Could you post the instructions for a reproduction?

`flutter create --template=plugin_ffi --platform=android` should work out of the box.

**Comment by luhuajcdd** [comment]
> @luhuajcdd Could you post the instructions for a reproduction?
> 
> `flutter create --template=plugin_ffi --platform=android` should work out of the box.

@dcharkes   
1. flutter create --template=plugin_ffi hello --platforms=android
2. cd hello/example
3. flutter run


device android4.2 : 
get error:
Invalid argument(s): Failed to load dynamic library 'libhello.so': Cannot load library: load_library(linker.cpp:745): library "libhello.so" not found

When the exception was thrown, this was the stack: 
#0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:12:43)
#1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:23:12)
#2      _dylib.<anonymous closure> (package:hello/hello.dart:44:27)
#3      _dylib (package:hello/hello.dart:50:2)
#4      _dylib (package:hello/hello.dart)
#5      _bindings (package:hello/hello.dart:53:47)
#6      _bindings (package:hello/hello.dart)
#7      sum (package:hello/hello.dart:14:26)
#8      _MyAppState.initState (package:hello_example/main.dart:24:23)
#9      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5015:57)
#10     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4853:5)
#11     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3863:16)
#12     Element.updateChild (package:flutter/src/widgets/framework.dart:3592:18)
#13     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1195:16)
#14     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:1164:5)
#15     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:1111:18)
#16     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2605:19)
#17     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:1110:13)
#18     WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:945:7)
#19     WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:925:7)
(elided 4 frames from class _RawReceivePortImpl, class _Timer, and dart:async-patch)

emulator android4.2:  get same error

**Comment by dcharkes** [comment]
```
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 3.7.0-10.0.pre.19, on Debian GNU/Linux rodete 5.19.11-1rodete1-amd64, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.60.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

$ flutter devices
3 connected devices:

Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
Linux (desktop)                    • linux         • linux-x64      • Debian GNU/Linux rodete 5.19.11-1rodete1-amd64
Chrome (web)                       • chrome        • web-javascript • Google Chrome 108.0.5359.124
```

```
$ flutter create --template=plugin_ffi hello --platforms=android
$ cd hello
$ cd example
$ flutter run -d emu
Downloading android-arm-profile/linux-x64 tools...               1,283ms
Downloading android-arm-release/linux-x64 tools...                 771ms
Downloading android-arm64-profile/linux-x64 tools...               814ms
Downloading android-arm64-release/linux-x64 tools...               776ms
Downloading android-x64-profile/linux-x64 tools...                 856ms
Downloading android-x64-release/linux-x64 tools...                 771ms
Running "flutter pub get" in example...
Resolving dependencies... 
  js 0.6.5 (0.6.6 available)
Got dependencies!
Using hardware rendering with device Android SDK built for x86. If you notice graphics artifacts, consider enabling
software rendering with "--enable-software-rendering".
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Running Gradle task 'assembleDebug'...                            117.5s
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
Installing build/app/outputs/flutter-apk/app-debug.apk...        1,217ms
Syncing files to device Android SDK built for x86...               175ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

💪 Running with sound null safety 💪

An Observatory debugger and profiler on Android SDK built for x86 is available at: http://127.0.0.1:45249/GCIdkJ181-4=/
The Flutter DevTools debugger and profiler on Android SDK built for x86 is available at:
http://127.0.0.1:9100?uri=http://127.0.0.1:45249/GCIdkJ181-4=/
```

It works as expected for me.

@luhuajcdd could you please post your `flutter doctor -v`?

**Comment by FusoraTech** [comment]
@dcharkes you are using Android 11 emulator, API 30 capable; @luhuajcdd is using Android 4.2, API 17. He said that when he tries using Android 8.1 API 27 it works. So the problem seems tied to the runtime environment, would be something breaking the system from certain API level down?

**Comment by luhuajcdd** [comment]
> 

flutter doctor -v
[✓] Flutter (Channel stable, 3.3.4, on macOS 12.5.1 21G83 darwin-x64, locale zh-Hans-CN)
    • Flutter version 3.3.4 on channel stable at /Users/sangfor/Desktop/flutter/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision eb6d86ee27 (3 months ago), 2022-10-04 22:31:45 -0700
    • Engine revision c08d7d5efc
    • Dart version 2.18.2
    • DevTools version 2.15.0
    • Flutter download mirror https://storage.flutter-io.cn

Checking Android licenses is taking an unexpectedly long time...[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/sangfor/Desktop/soft/android/sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = /Users/sangfor/Desktop/soft/android/sdk
    • Java binary at: /Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_333-b02)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    ✗ CocoaPods installed but not working.
        You appear to have CocoaPods installed but it is not working.
        This can happen if the version of Ruby that CocoaPods was installed with is different from the one being used to invoke it.
        This can usually be fixed by re-installing CocoaPods.
      To re-install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] IntelliJ IDEA Ultimate Edition (version 2021.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.72.1)
    • VS Code at /Users/sangfor/Downloads/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 4.2.2 (API 17) (emulator)
    • macOS (desktop)                    • macos         • darwin-x64     • macOS 12.5.1 21G83 darwin-x64
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 108.0.5359.94

[!] HTTP Host Availability
    ✗ HTTP host "https://pub.dev/" is not reachable. Reason: An error occurred while checking the HTTP host: Connection reset by peer

**Comment by dcharkes** [comment]
> So the problem seems tied to the runtime environment, would be something breaking the system from certain API level down?

https://docs.flutter.dev/development/tools/sdk/release-notes/supported-platforms

It looks like Android SDK 16-18 is best effort-supported, and we only test Android SDK 19 and upwards.
Android studio doesn't have an option to install an older Android emulator in the SDK manager, so it will require some more effort to figure out what is going on here.

@luhuajcdd are you in need of targeting Android SDK 17? Or could you target Android SDK 19 or higher instead?

**Comment by luhuajcdd** [comment]
> > So the problem seems tied to the runtime environment, would be something breaking the system from certain API level down?
> 
> https://docs.flutter.dev/development/tools/sdk/release-notes/supported-platforms
> 
> It looks like Android SDK 16-18 is best effort-supported, and we only test Android SDK 19 and upwards. Android studio doesn't have an option to install an older Android emulator in the SDK manager, so it will require some more effort to figure out what is going on here.
> 
> @luhuajcdd are you in need of targeting Android SDK 17? Or could you target Android SDK 19 or higher instead?

@dcharkes 

We must support 500000+devices(android 4.2)。I downloaded 4.2 from the android studio sdk and emulator yesterday。

Android 4.2 successfully loaded libflutter.so

Can you give me some suggestions to fix this problem?
Why did libflutter.so load successfully？

**Comment by dcharkes** [comment]
Does the jar contain both `libflutter.so` and `libhello.so`?

Ah, I remember issues with Android overriding the `dlopen` search paths on older Androids. Could you try the workaround mentioned in:

* https://github.com/flutter/flutter/issues/59834

**Comment by luhuajcdd** [comment]
> 

caontain both libflutter.so and libhello.so

adb devices
List of devices attached
emulator-5554	device

(base) sangfor-5:example sangfor$ adb shell
ata/com.example.hello_example/                                                <
root@android:/data/data/com.example.hello_example # ls lib/                    
libflutter.so
libhello.so

**Comment by luhuajcdd** [comment]
> Does the jar contain both `libflutter.so` and `libhello.so`?
> 
> Ah, I remember issues with Android overriding the `dlopen` search paths on older Androids. Could you try the workaround mentioned in:
> 
> * [`dart:ffi` conflicts with `System.loadLibrary` on Android API <=23 #59834](https://github.com/flutter/flutter/issues/59834)

caontain both libflutter.so and libhello.so

adb devices
List of devices attached
emulator-5554 device

(base) sangfor-5:example sangfor$ adb shell
ata/com.example.hello_example/ <
root@android:/data/data/com.example.hello_example # ls lib/
libflutter.so
libhello.so

**Comment by reidbaker** [comment]
+1 to @dcharkes said. In addition I want to bring your attention to the following design doc https://docs.google.com/document/d/1wWNly2SZRDqupSsHkBWDI_lS2MohBGEwPSXF6W05NOc/edit where we decided to raise the supported minimum android version to 19. 

That said I am not opposed to a patch fixing this issue for older devices but it wont stay relevant for long.
