### ISSUE TITLE
In App Purchase Plugin: Inconsistent / weird API for PurchaseDetails / AppStorePurchaseDetails

### ISSUE THREAD

**Issue by JohnnyRainbow81** [flutter/flutter#117394]
Hi, 
After test-buying a non-consumable at AppStore I get this PurchaseDetail from the PurchaseUpdateStream, casted into an AppStorePurchaseDetail object.

I think the following screenshot is self-explanatory. 

Which value might be the right one? Or is this a VS Code bug showing wrong data in the debugger? Well...

![Bildschirm­foto 2022-12-20 um 15 53 48](https://user-images.githubusercontent.com/23189088/208698041-7a4fb826-df48-413d-8770-46962b53c447.png)

**Comment by huycozy** [comment]
Hi @JohnnyRainbow81, does it occur when debugging on another IDE (such as Android Studio)? Can you also try printing the value in the console and checking its value?
