### ISSUE TITLE
[infra] Flutter SDK archives do not show releases after packaging

### ISSUE THREAD

**Issue by itsjustkevin** [flutter/flutter#117364]
After releasing the flutter 3.7.0-1.2.pre beta, only the mac builds appeared on the [Flutter SDK archives](https://docs.flutter.dev/development/tools/sdk/releases?tab=macos) after all packaging builds showed green.  40 minutes later the Linux packages showed.  Windows still does not appear.

cc: @godofredoc @drewroengoogle @sealesj

**Comment by itsjustkevin** [comment]
Update: Windows packages show after an hour.

**Comment by godofredoc** [comment]
The upload functionality was moved to recipes to generate provenance. The json files taking ~1h to show up is related to this comment: https://cs.opensource.google/flutter/flutter/+/master:dev/bots/prepare_package.dart;l=726?q=header&ss=flutter%2Fflutter:dev%2Fbots%2F

**Comment by godofredoc** [comment]
CP to stable recipes: https://flutter-review.googlesource.com/c/recipes/+/37540

**Comment by godofredoc** [comment]
CP to beta recipes: https://flutter-review.git.corp.google.com/c/recipes/+/37506
