### ISSUE TITLE
Unable to move Marker on Google Map (Web platform) by updating position

### ISSUE THREAD

**Issue by lokesh-bansal-lb-ha** [flutter/flutter#117391]
Current behavior : Marker is stuck at initial LatLng position but position is being updated in same Marker id. Same code is working fine on Mobile platform but not working on Web platform.

Expected behavior : Marker should move from source to destination and should look like it's moving.

Video link : https://drive.google.com/drive/folders/19pG4sXGhZ0yHMb24xpyLCbsC1Mxhv3qV?usp=sharing

Calling movePin() method periodically after few micro-seconds and updating Marker position.

Sample code:
final Set<Marker> _markers = {};
List<LatLng> tripPolylineCoordinates = [];

timer = Timer.periodic(Duration(microseconds: getDuration()), (Timer t) => movePin());

movePin() {
    if (currentIndex < tripPolylineCoordinates.length) {
      setState(() {
        latLng = LatLng(tripPolylineCoordinates[currentCarIndex].latitude, tripPolylineCoordinates[currentCarIndex].longitude);
        Marker marker = Marker(
          markerId: const MarkerId("pin"),
          position: latLng!,
          anchor: const Offset(0.5, 0.5),
          zIndex: 3,
        );
        _markers.add(marker);
        currentIndex += 1;
      });
    } else {
      pauseShowingIndex = false;
      timer?.cancel();
      increment();
    }
  }

**Comment by huycozy** [comment]
@lokesh-bansal-lb-ha Thanks for the report! This is a known issue being tracked at #83467. There is also a new PR filed recently https://github.com/flutter/plugins/pull/6753.

Closing this issue as a duplicate, so please follow up on the issue and PR for further updates.
