### ISSUE TITLE
Glitchy/ laggy scrolling - iOS 16, iPhone 14 Pro

### ISSUE THREAD

**Issue by SalmanJanvekar22** [flutter/flutter#117353]
Hey! I noticed that my flutter app was dropping frames in release mode significantly when the dynamic island is in use. Is this due to code optimization or is this a known bug on the flutter platform (maybe a bit of both?)?

Any insight/ comments are appreciated!

**Comment by SalmanJanvekar22** [comment]
Hi Darshan,

Please let me know if this gives you the information you need. The issue is essentially on any apps which are generating lists via list view builder when you have the dynamic island running (For music, calls, etc).

Flutter doctor:

`[✓] Flutter (Channel stable, 3.3.10, on macOS 12.5.1 21G83 darwin-arm, locale en-CA)
    • Flutter version 3.3.10 on channel stable at /Users/salman/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (6 days ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A309
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] VS Code (version 1.74.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.54.0

[✓] Connected device (3 available)
    • Salman’s iphone  (mobile) • 00008120-000C714E1400C01E • ios            • iOS 16.0.1 20A371
    • macOS (desktop)           • macos                     • darwin-arm64   • macOS 12.5.1 21G83 darwin-arm
    • Chrome (web)              • chrome                    • web-javascript • Google Chrome 108.0.5359.124

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.`

Code to Reproduce:
GestureDetector(
      child: Scaffold(
        key: _key,
        backgroundColor: snow,

        appBar: AppBar(
          toolbarHeight: 0,
          elevation: 0,
          backgroundColor: snow,
        ),
        body: CustomScrollView(slivers: [
          //AppBar Sliver
          SliverAppBar(
            stretch: false,
            pinned: false,
            floating: true,
            toolbarHeight: 50,
            centerTitle: false,
            elevation: 0,
            backgroundColor: snow,
            automaticallyImplyLeading: false,
            
            // Typeface
            title: Padding(
              padding: const EdgeInsets.only(left: 9.0),
              child: Image.asset(
                'assets/images/Typeface.png',
                height: 44,
              ),
            ),

            //Notifications & Chat
            actions: [
              Padding(
                padding: const EdgeInsets.only(
                  right: 30.0,
                ),
                child: Row(
                  children: [
                    GestureDetector(
                      child: Padding(
                        padding: const EdgeInsets.only(
                          right: 30.0,
                        ),
                        child: SvgPicture.asset(
                          'assets/icons/generalIcons/notifications.svg',
                          height: 20,
                          width: 20,
                        ),
                      ),
                      onTap: () {
                        print("Notifications Button Pressed");
                        // Navigator.of(context).push(CupertinoPageRoute(
                        //     fullscreenDialog: true,
                        //     builder: (context) => CreateClassType()));
                      },
                    ),
                    GestureDetector(
                      child: SvgPicture.asset(
                        'assets/icons/generalIcons/search.svg',
                        height: 20,
                        width: 20,
                      ),
                      onTap: () {
                        Navigator.push(
                            context,
                            PageTransition(
                                child: Search(),
                                type: PageTransitionType.fade,
                                isIos: false,
                                duration: Duration(milliseconds: 0),
                                reverseDuration: Duration(milliseconds: 0)));
                      },
                    ),
                  ],
                ),
              )
            ],
          ),

          MultiSliver(children: [
            Padding(
              padding:
                  const EdgeInsets.only(left: 26.0, right: 26.0, top: 15.0),
              child: Text(
                'Hi, Salman',
                style: TextStyle(
                  color: jetBlack,
                  fontFamily: 'SFDisplay',
                  fontSize: 24,
                  fontWeight: FontWeight.w600,
                ),
              ),
            ),
            Padding(
              padding: const EdgeInsets.only(left: 26.0, right: 26.0, top: 2.0),
              child: Row(
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: [
                  Text(
                    'Upcoming',
                    style: TextStyle(
                      color: jetBlack,
                      fontFamily: 'SFDisplay',
                      fontSize: 15,
                      fontWeight: FontWeight.w500,
                    ),
                  ),
                  Text(
                    'See all',
                    style: TextStyle(
                      color: ocean,
                      fontFamily: 'SFDisplay',
                      fontSize: 15,
                      fontWeight: FontWeight.w500,
                    ),
                  )
                ],
              ),
            ),
            SliverList(
                delegate: SliverChildBuilderDelegate(
              (BuildContext context, int index) {
                return Padding(
                  padding:
                      const EdgeInsets.only(top: 15.0, left: 26.0, right: 26.0),
                  child: UpcomingClassesItem(),
                );
              },
              childCount: 1,
            )),
            Padding(
              padding:
                  const EdgeInsets.only(left: 26.0, right: 26.0, top: 35.0),
              child: Text(
                'For you',
                style: TextStyle(
                  color: jetBlack,
                  fontFamily: 'SFDisplay',
                  fontSize: 18,
                  fontWeight: FontWeight.w600,
                ),
              ),
            ),
            SliverList(
                delegate: SliverChildBuilderDelegate(
              (BuildContext context, int index) {
                final Item = Item[index];
                return LocalList()
                //returns from some locally defined list - Any list with 10 items & 10+ fields to select from

              },
              childCount: classList.length,
            )),
          ])
        ]),
      ),
      onTap: () => {FocusScope.of(context).requestFocus(new FocusNode())},
    );
  }
}

**Comment by darshankawar** [comment]
Thanks for the code sample @SalmanJanvekar22 , but it still seems to contain custom code implementation and third party plugin like MultiSliver which seems to be coming from sliver_tools package if I assume correctly. We would need a complete minimal code sample without such code. Also, the laggy behavior is observed in debug mode or in profile and release mode as well ? A short video of the behavior would be helpful too.
