### ISSUE TITLE
applyBoxFit doesn't properly handle an output size of Size.zero

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#11733]
https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/painting/box_fit.dart#L127

The result is a returned size with Nans in some cases resulting in issue: https://github.com/flutter/flutter/issues/11586

**Comment by Hixie** [comment]
We might want to assert it's non-zero, and have callers handle that case specially. There's rarely any point to do anything if you're outputting to a zero rect.

**Comment by apwilson** [comment]
As mentioned offline, I would expect the returned size(s) to be Size.zero not assert.  There's legitimate use cases where the given output size is Size.zero.
