### ISSUE TITLE
Drag to select folders in a gridview in flutter

### ISSUE THREAD

**Issue by faisalansari0367** [flutter/flutter#117398]
I am trying to create a finder for the macOS using flutter
Here's a video link for the same feature
https://user-images.githubusercontent.com/61263149/208727242-533953f2-4377-4d2d-9587-42beaaab031a.mov

But I am not able to select folders and select them by dragging the mouse just like we do it on the finder
I am able to draw the rectangle but how can I select all the folders and files that are covering the selected rectangle container

I am attaching the video for the same for a better understanding

**Comment by darshankawar** [comment]
Thanks for the report @faisalansari0367 
I think your case is same / similar to [this](https://github.com/flutter/flutter/issues/30719) open proposal, so I suggest you to follow-up in it for further updates.
Closing this as a duplicate. If you disagree, write in comments and I'll reopen it.

**Comment by darshankawar** [comment]
@faisalansari0367 
You may ask this question on support channels like StackOverflow to get an existing solution from community or also check for a community plugin / package that already offers this feature.
