### ISSUE TITLE
PageTransitionBuilder return 2 times in transitionBuilder option.

### ISSUE THREAD

**Issue by baranngungor** [flutter/flutter#117392]
## Steps to Reproduce

1. I'm using the PageTransitionSwitcher. TransitionBuilder option is returning 2 times when my condition value changed. I tried with print code and i saw 2 prints on my console 

**Expected results:**  See 1 print in my transitionBuilder's return.  

**Actual results:** Saw 2 print in my transitionBuilder's return. 

<details>
<summary>Code sample</summary>

```dart
PageTransitionSwitcher(
        duration: const Duration(milliseconds: 500),
        reverse: mainCategory,
        transitionBuilder: (
          Widget child,
          Animation<double> animation,
          Animation<double> secondaryAnimation,
        ) {
          print("IS MAIN CATEGORY");
          return SharedAxisTransition(
            animation: animation,
            secondaryAnimation: secondaryAnimation,
            transitionType: _transitionType,
            child: child,
          );
        },
```

</details>
<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by darshankawar** [comment]
Thanks for the report @baranngungor 
Can you provide complete minimal reproducible code sample (ex: main.dart) along with platform on which you are seeing this behavior ?

**Comment by baranngungor** [comment]
@darshankawar  I am seeing this on Mobile Platforms. Here the code :

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Test"),
      ),
      body: Center(
        child: PageTransitionSwitcher(
          duration: const Duration(milliseconds: 500),
          reverse: mainCategory,
          transitionBuilder: (
              Widget child,
              Animation<double> animation,
              Animation<double> secondaryAnimation,
              ) {
            print("PRINT");
            return SharedAxisTransition(
              animation: animation,
              secondaryAnimation: secondaryAnimation,
              transitionType: SharedAxisTransitionType.horizontal,
              child: child,
            );
          },
          child: mainCategory
              ? Container(
              key: const Key('main'),
              child: const Text('MAIN'))
              : Container(
            key: const Key('child'),
            child: const Text('CHILD'),
          ),
        ),
      ),
    );
  }
}
```
</details>

**Comment by darshankawar** [comment]
Thanks for the update. Running the code on iOS simulator using latest master version shows only 1 print as expected:

```
Debug service listening on ws://127.0.0.1:54618/jBbqr0OCwXQ=/ws
Syncing files to device iPhone 13 Pro Max...
flutter: PRINT
```

Please check the same above using latest master or stable version because you have not mentioned what version you are on.

**Comment by baranngungor** [comment]
Thanks for answers but i am seeing same situation. That's my `flutter doctor` result : 

> Doctor summary (to see all details, run flutter doctor -v):
> [✓] Flutter (Channel stable, 3.3.10, on macOS 12.6 21G115 darwin-arm, locale tr-TR)
> [✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
> [✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
> [✓] Android Studio (version 2021.3)
> [✓] VS Code (version 1.66.2)
> [✓] Connected device (1 available)
> [✓] HTTP Host Availability
> 
> • No issues found!

And my code and console results: 
<details>
<summary>Code ScreenShot</summary>
<img width="590" alt="Ekran Resmi 2022-12-21 16 43 08" src="https://user-images.githubusercontent.com/104129460/208919750-1c01fb31-e031-4bfe-afbb-8ac7ba895103.png">
</details>

<details>
<summary>Console ScreenShot After Press Floating ActionButton</summary>
<img width="362" alt="Ekran Resmi 2022-12-21 16 43 36" src="https://user-images.githubusercontent.com/104129460/208920196-2d16777f-a70c-4b0c-95f8-7142acbf6fa9.png">
</details>

**Comment by darshankawar** [comment]
I verified on latest master, so please try by switching to that version and check again to see what you get.

`flutter channel master`
`flutter upgrade`

**Comment by baranngungor** [comment]
I am facing this error after change to master from stable channel and run flutter upgrade.
`
Request textDocument/colorPresentation failed.
  Message: File is not being analyzed
  Code: -32007
`

**Comment by darshankawar** [comment]
Try `flutter upgrade --force`

**Comment by baranngungor** [comment]
I tried but not working

**Comment by darshankawar** [comment]
Can you provide the complete log that is shown after upgrade ?

**Comment by baranngungor** [comment]
> I am facing this error after change to master from stable channel and run flutter upgrade. `Request textDocument/colorPresentation failed. Message: File is not being analyzed Code: -32007`

Here the error that i am facing

**Comment by darshankawar** [comment]
Please create a new Flutter project and then paste the code sample you shared earlier and run to see if you get the same error.
