### ISSUE TITLE
  SystemChrome.setPreferredOrientations prevent the app from changing orientation

### ISSUE THREAD

**Issue by rrousselGit** [flutter/flutter#11735]
## Steps to Reproduce

Doing 
`  SystemChrome.setPreferredOrientations([DeviceOrientation.landscapeRight, DeviceOrientation.landscapeLeft]);`
force the app permanently in `DeviceOrientation.landscapeRight` whatever the deviceOrientation really is.
Which means that when the device is on landscapeLeft, the screen still display landscapeRight. 

## Flutter Doctor

[√] Flutter (on Microsoft Windows [version 10.0.14393], locale fr-FR, channel alpha)
    • Flutter at D:\dev\flutter
    • Framework revision bbcfb8d51a (3 weeks ago), 2017-08-01 14:50:29 -0700
    • Engine revision f2af347363
    • Tools Dart version 1.25.0-dev.7.0

[√] Android toolchain - develop for Android devices (Android SDK 26.0.1)
    • Android SDK at C:\Users\rrousselet\AppData\Local\Android\sdk
    • Platform android-26, build-tools 26.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[√] Android Studio (version 2.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[√] Connected devices
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 7.0 (API 24) (emulator)

**Comment by Hixie** [comment]
I fixed this last November! https://github.com/flutter/engine/commit/bc30d7bed25100421d76ecaac8cb60d60040bafe
