### ISSUE TITLE
[CP] Fix NavigationRail highlight

### ISSUE THREAD

**Issue by Piinks** [flutter/flutter#117340]
### issue_link

https://github.com/flutter/flutter/issues/117126

### Commit Hash

5fcb48d

### Target

beta

### pr_link

https://github.com/flutter/flutter/pull/117344

### Impacted Users

Users of the Material 3 spec

### Impact Description

This fixed a regression introduced in https://github.com/flutter/flutter/pull/116108
The new Material 3 NavigationRail was rendering the highlight in the wrong location.

![image](https://user-images.githubusercontent.com/16964204/208528763-89894014-167b-46b2-9075-b86e55a93b4e.png)

### Workaround

No.

### Risk

low

### Test Coverage

yes

### Validation Steps

This dartpad reproduced the issue. https://dartpad.dev/?id=272d62da895a9e17c38c7f562a6d3d5f&channel=master

**Comment by itsjustkevin** [comment]
@HansMuller could you check out this cherry-pick request?

**Comment by HansMuller** [comment]
LGTM

**Comment by Piinks** [comment]
Cherry pick PR is https://github.com/flutter/flutter/pull/117344
