### ISSUE TITLE
I have difficulty in restoring the FlutterError.onError when exception is thrown while integration test is being run!

### ISSUE THREAD

**Issue by jagadeeshpurplle** [flutter/flutter#117311]
Hi Guys,

I have a use case where, while running the flutter integration test, the app will throw the `FirebaseException`.!

However the test is failing by below error(This exception is expected from app side), But I want to ignore this and continue the test execution.!
```
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following FirebaseException was thrown running a test:
[cloud_firestore/permission-denied] The caller does not have permission to execute the specified
operation.
```

With this [solution](https://stackoverflow.com/a/72825524/8140419) in stackoverflow, i tried but still test is failing.!

Can anybody help me in how to ignore the `exceptions` caught by `FLUTTER TEST FRAMEWORK` and continue the test execution?

Here is the error logs:
<details>
  <summary>Click me</summary>
  
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following FirebaseException was thrown running a test:
[cloud_firestore/permission-denied] The caller does not have permission to execute the specified
operation.

When the exception was thrown, this was the stack:
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:653:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:296:18)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)

The test description was:
  TC_01 Test User Login
════════════════════════════════════════════════════════════════════════════════════════════════════
01:42 +0 -1: SignIn Test Cases TC_01 Test User Login [E]                                                                                                                   
  Test failed. See exception logs above.
  The test description was: TC_01 Test User Login
  
  'package:flutter_test/src/binding.dart': Failed assertion: line 1754 pos 12: '_pendingFrame == null': is not true.
  dart:core                                                                                                              _AssertionError._throwNew
  package:flutter_test/src/binding.dart 1754:12                                                                          LiveTestWidgetsFlutterBinding.postTest
  ===== asynchronous gap ===========================
  package:stream_channel                                                                                                 _GuaranteeSink.add
  var/folders/27/r0hd8f_x0y10hx2rs6ynchbh0000gp/T/flutter_tools.TS0YqU/flutter_test_listener.7i4Jy1/listener.dart 53:22  main.<fn>
  

To run this test again: /Users/tummalacharlajagadeesh/Downloads/flutter/bin/cache/dart-sdk/bin/dart test /Users/tummalacharlajagadeesh/Desktop/Sparrow/synapse-cards-mobile/synapse-cards-mobile/integration_test/regression/regression_test.dart -p vm --plain-name 'SignIn Test Cases TC_01 Test User Login'
01:45 +0 -1: Some tests failed.       
</details>

**Comment by exaby73** [comment]
Hello @jagadeeshpurplle. Thank you for filing this issue. Can you please provide the following information?

- A [complete and minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). Ideally, a single `main.dart` file that can be run directly.
- The output of `flutter doctor -v`
- The output of `flutter run -v`

Please provide the information in the form of text. See how to make collapsible sections with Markdown [here](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-collapsed-sections).

**Comment by jagadeeshpurplle** [comment]
@exaby73 sure. I’ll build an app which can be reproducible and share here.
