### ISSUE TITLE
Autosubmit bot failing to land PRs on "Resource not accessible by integration."

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#117318]
See:

https://github.com/flutter/engine/pull/38395
https://github.com/flutter/engine/pull/38392

It looks like these have recovered, but a more informative error could be helpful.

**Comment by chinmaygarde** [comment]
This is happening in https://github.com/flutter/engine/pull/38367#issuecomment-1358091776 as well.

**Comment by zanderso** [comment]
Seeing this on more PRs, and not just from the autorollers. I increased priority to P2, but this probably won't get attention until after the holidays.

**Comment by jmagman** [comment]
Can we audit the autosubmit bot messages? They may have enough information for someone who is familiar with the autosubmit code, but these messages should give instruction to the PR author about what went wrong and what to do next.

**Comment by drewroengoogle** [comment]
@ricardoamador made a change to the autosubmit a couple weeks ago that was focused on this issue: https://github.com/flutter/cocoon/pull/2331

Ricardo, is there somewhere else within the autosubmit bot you can think of that this error may be happening? I'm not sure what type of logging we have for autosubmit that might provide more information around this.

**Comment by ricardoamador** [comment]
Let me take a look. We ultimately are reliant on the messages returned from Github, which, unfortunately had even less information than before this change.

**Comment by ricardoamador** [comment]
@zanderso have you seen this on PRs outside of the engine repository?

**Comment by zanderso** [comment]
It was a couple of weeks back now, but I don't think we saw any examples outside the engine repo, no.

**Comment by ricardoamador** [comment]
Okay this looks to be happening in packages as well:
https://github.com/flutter/packages/pull/2831
https://github.com/flutter/packages/pull/2815
@zanderso do you perhaps have admin permissions in github for those repositories? I would like to verify some permissions on the repo.

**Comment by zanderso** [comment]
No I don't have admin.

**Comment by jmagman** [comment]
@godofredoc should there be an eng prod GitHub Team for the flutter org with admin access to these repos?

**Comment by ricardoamador** [comment]
@jmagman He does. He is just out until next week. I would really like if we at least had read permissions on the settings.

**Comment by jmagman** [comment]
> @jmagman He does. He is just out until next week. I would really like if we at least had read permissions on the settings.

I know he has access, I meant you should have it too via a Team 🙂
Maybe @stuartmorgan has admin access to that repo.

**Comment by ricardoamador** [comment]
Ah okay. Yeah we do not as a team have access. I can ping Stuart to see if he has access.

**Comment by stuartmorgan** [comment]
I don't have admin access, no.

**Comment by ricardoamador** [comment]
Nooooo!!!!

**Comment by ricardoamador** [comment]
Next step is we need someone with access to verify the autosubmit app permissions in engine and packages.

**Comment by ricardoamador** [comment]
We have validated the permissions on the repositories and nothing is different between them. I did find this issue: https://github.com/actions/first-interaction/issues/10. So this looks to be a github issue that was hit when we were adjusting permissions for tasks. I am going to close this now since we have not seen it but if this is hit again please do not merge the pull request manually and notify me or the infra team so we can take a look when this happens again.
