### ISSUE TITLE
Uncaught Error: NoSuchMethodError: s is null (in Flutter web release mode Firefox)

### ISSUE THREAD

**Issue by RajSolai** [flutter/flutter#117377]
My Flutter web app was working totally fine, but this error pops up often and cannot be able to click any button, this error occurs only sometimes I could not even replicate this error :(

Below is the error statement
Uncaught Error: NoSuchMethodError: s is null

The message pointed to this line
```
s=new Error()
s.dartException=a
```

I have also added the console.logs
I do suspect some plugins for this behavior, please respond if you guys also faced a similar error or is there any way to solved this.

[console-export-2022-12-20_11-43-43.txt](https://github.com/flutter/flutter/files/10265976/console-export-2022-12-20_11-43-43.txt)

**Comment by exaby73** [comment]
Hello @RajSolai. Is this issue reproducible with the default counter app? Also, you could try to remove plugins and see if the error reproduces. If this issue is indeed from plugins, there's nothing Flutter can do and it's better to raise this issue in the repo of said plugin

**Comment by RajSolai** [comment]
Agreed @exaby73, Will check if the issue persists without the plugins

**Comment by RajSolai** [comment]
This error pops right after the main.dart.js bootstrapping, but only for some times.

**Comment by exaby73** [comment]
> This error pops right after the main.dart.js bootstrapping, but only for some times.

Is this with the counter app?

**Comment by RajSolai** [comment]
Closing this issue as it was found that the issue is not a part of flutter framework. (Clearing of Sharedpreference solved problem)
