### ISSUE TITLE
[webview_flutter] How to define encoding as utf-8 in v4?

### ISSUE THREAD

**Issue by pvc00357-git** [flutter/flutter#117346]
It's not clear how to define the encoding as utf-8 in webview_flutter v4. Could you please update the documentation? Thanks.

**Comment by stuartmorgan** [comment]
The encoding of what? Please provide specific details about your use case and what APIs you are using.

**Comment by bparrishMines** [comment]
Im guessing this is referring to the `loadData` methods for Android and iOS?
https://developer.android.com/reference/android/webkit/WebView#loadData(java.lang.String,%20java.lang.String,%20java.lang.String)
https://developer.apple.com/documentation/webkit/wkwebview/1415011-loaddata?language=objc

**Comment by stuartmorgan** [comment]
We don't expose that API though; we support loading a string, and the encoding of a string is already defined.
