### ISSUE TITLE
[Impeller] Are Metal playgrounds leaking memory?

### ISSUE THREAD

**Issue by bdero** [flutter/flutter#117339]
I noticed that Metal playgrounds start hanging for me after a couple of minutes and started looking around for clues.

The memory footprint of playgrounds increase linearly with the framerate, but the memory leak instrument fails to locate any leaked resources. 

The video below shows the playground's memory footprint expanding at ~110 MBps at 60fps until the app hangs (no idea if the hanging is related or not). When capping the framerate to 30fps, the expansion rate is halfed.

https://user-images.githubusercontent.com/919017/208527220-33fd3f67-9add-4b61-a870-7092cfba8b29.mov

I sampled a few different Metal playgrounds and they all seem to exhibit the same behavior/per-frame "leak" rate, including simple playgrounds that don't involve the Entities renderer, like `Play/RendererTest.ArrayUniforms/Metal`.

Again, I'm not sure if this is an actual leak yet because I don't fully understand the information I'm looking at, and the permanent hang that occurs after a couple of minutes may or may not be at all related. My understanding is that NSObjects are refcounted these days and there shouldn't be any garbage accumulation going on over time.

Had some trouble getting LSAN to work right this morning, but will take another swing later.

FYI @chinmaygarde

**Comment by chinmaygarde** [comment]
Instruments should be able to tell us this fairly quickly. Will take a closer look.

**Comment by bdero** [comment]
The "Leaks" instrument doesn't detect any leaks for me, and I found the the "Allocations" instrument not insightful here since it seems to just collect allocation traces as they occur (no info about freeing behavior?)

**Comment by chinmaygarde** [comment]
The playgrounds may not be leaking in the strictest sense, i.e, have objects be unreachable. I'd get snapshots in the allocations profiler and compare the growth between two snapshots.

**Comment by fanchou** [comment]
It may be similar to this  #https://github.com/ocornut/imgui/issues/2910
