### ISSUE TITLE
How to update flutter web application, not use website cache?

### ISSUE THREAD

**Issue by dengzq** [flutter/flutter#117304]
We build a flutter web application for our users these day.   But then we found that users have to disable website cache on chrome to update when a new version was published. 

How can we load the latest website resources and not use the cache when a new version was published ?  
It will be much better for our users if we solve this.

how we build flutter web:
```
flutter build web --web-renderer=html --release
```

Flutter version : 
```
Flutter 3.3.4 • channel unknown • unknown source
Framework • revision eb6d86ee27 (3 months ago) • 2022-10-04 22:31:45 -0700
Engine • revision c08d7d5efc
Tools • Dart 2.18.2 • DevTools 2.15.0
```

**Comment by huycozy** [comment]
Hi @dengzq 
This is currently not supported but there is a proposal being tracked at https://github.com/flutter/flutter/issues/63500. Closing this issue as a duplicate, so please follow up on it for further updates. Thanks!
