### ISSUE TITLE
Dependabot cannot land updates to bump references.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#117328]
Seen in https://github.com/flutter/engine/pull/38390#issuecomment-1357302967, https://github.com/flutter/engine/pull/38389#issuecomment-1357305028, and others. The specific error message is:

```
refusing to allow a GitHub App to create or update workflow
.github/workflows/scorecards-analysis.yml without workflows
permission.
```

**Comment by chinmaygarde** [comment]
I'm landing the PRs manually now.

**Comment by godofredoc** [comment]
Seems like a github transient issue. Adding a comment `@dependabot rebase` will rebase and land

**Comment by godofredoc** [comment]
Fix with updated permissions of the autosubmit bot.
