### ISSUE TITLE
Material widget Badge is missing

### ISSUE THREAD

**Issue by RCSandberg** [flutter/flutter#117451]
According to the documentation there should be a widget called Badge:

[https://api.flutter.dev/flutter/material/Badge-class.html](https://api.flutter.dev/flutter/material/Badge-class.html)
Flutter 3.3.10 • 2022-12-20 14:54 • 135454af32 • stable

But it seems to be missing... is it deprecated and removed? or is there some other problem or something that I am missing?
[https://github.com/flutter/flutter/blob/135454af32/packages/flutter/lib/src/material/badge.dart#L24](https://github.com/flutter/flutter/blob/135454af32/packages/flutter/lib/src/material/badge.dart#L24)

**Comment by huycozy** [comment]
@RCSandberg `Badge` widget was recently completed with PR https://github.com/flutter/flutter/pull/114560 and is available on the latest `beta` and `master` channels. Please switch to these channels to try it. 

Closing the issue as fixed on the beta/master channel. The fix should land on the stable channel in future releases.

**Comment by RCSandberg** [comment]
Thanks for the fast response!

It feels a bit misleadning that it is available on the documentation for stable release...
