### ISSUE TITLE
Provisioning profile change is breaking mac devicelab machines

### ISSUE THREAD

**Issue by yusuf-goog** [flutter/flutter#117400]
Change to swap out one device in the provisioning profile, has broken all mac ios devicelab machines with the error:

```Quarantined: Device doctor tool error: b'security: unable to open "/Users/swarming/Library/MobileDevice/Provisioning Profiles/0588588e-cb23-4453-8ba2-e6c692cc9453.mobileprovision\n7fa35d57-4da1-49c4-8588-417cc84c0bfb.mobileprovision" for reading: No such file or directory\n'```

**Comment by yusuf-goog** [comment]
Revert created for the provisioning file change.

**Comment by yusuf-goog** [comment]
The original change seems to have resulted in 2 provisioning files ending up on the host. E.g. on mac-44:

```bash-3.2$ ls -la  /Users/swarming/Library/MobileDevice/Provisioning\ Profiles/
total 80
drwxr-xr-x  4 swarming  swarming    128 Dec 20 10:10 .
drwxr-xr-x  3 swarming  swarming     96 Dec  2  2021 ..
-rw-r--r--  1 swarming  swarming  16731 Dec 19 18:04 0588588e-cb23-4453-8ba2-e6c692cc9453.mobileprovision
-rw-r--r--  1 swarming  swarming  16766 Nov 11 15:29 7fa35d57-4da1-49c4-8588-417cc84c0bfb.mobileprovision```

This seems to cause device_doctor to fail, when seeing 2 files:

```bash-3.2$ /opt/flutter/device_doctor/device_doctor --action healthcheck --device-os ios
security: unable to open "/Users/swarming/Library/MobileDevice/Provisioning Profiles/0588588e-cb23-4453-8ba2-e6c692cc9453.mobileprovision
7fa35d57-4da1-49c4-8588-417cc84c0bfb.mobileprovision" for reading: No such file or directory```

Removing the old file, gets device_doctor into a happy state and the host starts working:

```bash-3.2$ mv /Users/swarming/Library/MobileDevice/Provisioning\ Profiles/7fa35d57-4da1-49c4-8588-417cc84c0bfb.mobileprovision ~/
bash-3.2$ sudo /opt/flutter/device_doctor/device_doctor --action healthcheck --device-os ios```

**Comment by yusuf-goog** [comment]
There seems to be 2 underlying issues that need to be looked at:

* Why didn't the old file get cleaned up.
* Harden device_doctor to only look at the newest file in the directory (Just looking at the latest file might not be the ideal path, since raising an exception when multiple profile files are found might be the correct action).

**Comment by yusuf-goog** [comment]
cc @jmagman @godofredoc

**Comment by goderbauer** [comment]
This is presumably also the reason for https://github.com/flutter/flutter/issues/117397?

**Comment by jmagman** [comment]
@ricardoamador and I extensively discussed allowing multiple provisioning profiles in this directory in November. https://chat.google.com/room/AAAAQFWU2Go/vwo_HB2YZfQ (link to internal chat)

**Comment by jmagman** [comment]
> these look pretty much the same, I bet either works. just checking that there's at least one in there is probably sufficient. if you really want to check for the unmanaged one you could run that security command and check for
> ```
>     <key>IsXcodeManaged</key>
>     <false/>
> ```

**Comment by yusuf-goog** [comment]
Recovered some hosts by deleting the second file, to unblock queued builds.

**Comment by yusuf-goog** [comment]
manual test of the device_doctor change looks good. We are hitting some deployment workflow issues, looking into those to rollout the change to the machines.

**Comment by yusuf-goog** [comment]
Added fix to cocoon builder which was missing git_ref that was causing the artifacts to not upload.

**Comment by yusuf-goog** [comment]
Fixes have been pushed out and machines have recovered. Once salt deploys the fixes across the mac hosts, this should not happen in the future.

Closing this issue.
