### ISSUE TITLE
TextFormField/TextEditingController validation error

### ISSUE THREAD

**Issue by jt70** [flutter/flutter#11748]
If TextEditingController.text is set directly (i.e. by calling TextEditingController.text = 'some string' as opposed to typing something in), the TextFormField state gets out of sync with the TextEditingController.  This causes problems with validation (and probably saving as well).  Here is some [sample code](https://gist.github.com/jt70/f15c6004578cfb93b7de9a2671c8867a) and a screen capture that demonstrates the problem.

## Steps to Reproduce

1. Create a form that contains a TextFormField and TextEditingController.
2. Initialize the TextEditingController.text to ''.
3. In a Future call TextEditingController.text = 'some string'.
4. Call form.validate()
5. The validator for the TextFormField will receive '' as opposed to 'some string'.
6. Don't click or focus the TextFormField as this fixes the problem.

![text-form-field](https://user-images.githubusercontent.com/419198/29599544-74ed81a8-879e-11e7-815e-16dc455002aa.png)
## Flutter Doctor

C:\Users\jthomas\IdeaProjects\test_form_field>flutter doctor
[√] Flutter (on Microsoft Windows [Version 10.0.15063], locale en-US, channel alpha)
    • Flutter at C:\Users\jthomas\git-projects\flutter
    • Framework revision bbcfb8d51a (3 weeks ago), 2017-08-01 14:50:29 -0700
    • Engine revision f2af347363
    • Tools Dart version 1.25.0-dev.7.0

[√] Android toolchain - develop for Android devices (Android SDK 26.0.0)
    • Android SDK at C:\Users\jthomas\Android\sdk
    • Platform android-26, build-tools 26.0.0
    • ANDROID_HOME = C:\Users\jthomas\Android\sdk
    • Java binary at: C:\Users\jthomas\android-studio-ide-171.3870562-windows\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-736)

[√] Android Studio (version 2.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[√] Android Studio (version 2.4)
    • Android Studio at C:\Users\jthomas\android-studio-ide-171.3870562-windows\android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-736)

[√] IntelliJ IDEA Community Edition (version 2017.1)
    • Flutter plugin version 15.1
    • Dart plugin version 171.4694.29

[√] Connected devices
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 7.1.1 (API 25) (emulator)

**Comment by jt70** [comment]
Workaround - pass controller.text to the validator function and ignore the value passed in by the form. 
 
`new TextFormField(validator: (v) => _validateValue(controller.text), controller: controller,)`

**Comment by cbracken** [comment]
This sounds very related to #11713, which is rooted in inconsistency in state between the TextEditingController associated with the TextField underling the TextFormField and the string state associated with the TextFormField. #11713 specifically concerns the case where a TextEditingController *isn't* passed in, but in working on the fix, I ran into something that looks suspiciously similar to what you've hit here.

I've got a patch in progress that needs a bit more fine-tuning and testing. Thanks for reporting!

**Comment by cbracken** [comment]
This should now be fixed on master. Please re-open if you're still seeing problems.

**Comment by santosh12345** [comment]
Hi 
i am trying to pick contact number and set in TextformField, I able to pick contact and set in TextFormField,but it is showing when i am clicking at that field (TextFormField). I want to show automatically at set time. please provide your valuable input. For reference code of snippet as given below:
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:trainingsession1/billandrechage/contact_picker.dart';

class User {
  const User({this.name, this.icon});

  final String name;
  final icon;
}

class MobileRecharge extends StatefulWidget {
  _MobileRecharge createState() => new _MobileRecharge();
}

class _MobileRecharge extends State<MobileRecharge> {
  User selectedUser;
  final scafFoldKey = new GlobalKey<ScaffoldState>();
  final formKey = new GlobalKey<FormState>();
  final formKey2 = new GlobalKey<FormState>();
  final formKey3= new GlobalKey();
  final ContactPicker _contactPicker = new ContactPicker();
  String initialValue;
  List<User> users = <User>[
    User(name: 'Prepaid', icon: new Icon(Icons.save)),
    User(name: 'PostPaid', icon: new Icon(Icons.home))
  ];

  DropdownButton<User> mobileRechageType;

  Contact _contact;

  String Datavalue;

  String initialvalue;

  TextEditingController _c = new TextEditingController();

  FocusNode _textFocus = new FocusNode();
  String _text = "initial";

  bool hasFocus;



  void _onChanged(User value) {
    setState(() {
      selectedUser = value;
    });
  }

  @override
  void initState() {
_c.addListener(onChange);
_textFocus.addListener(onChange);
    mobileRechageType = new DropdownButton<User>(
      hint: new Text("Select a user"),
      value: selectedUser,
      onChanged: (User newValue) {
        _onChanged(newValue);
      },
      items: users.map((User user) {
        return new DropdownMenuItem<User>(
          value: user,
          child: new Row(children: <Widget>[new Text(
            user.name,
            style: new TextStyle(color: Colors.black),
          ),

          ]),
        );
      }).toList(),
    );
    super.initState();
    //_setInitialValueOfTextFromField("33333");
  }

  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
        debugShowCheckedModeBanner: false,
        home: new Scaffold(
            key: scafFoldKey,
            body:new Column( children: <Widget>[new Form(
              autovalidate: false,
                key: formKey,
                child: new Column(
                    children: inputField()
                ))])));
  }

  List<Widget> inputField() {
    List<Widget> inputField = new List<Widget>();
    inputField.add(new Center(
        heightFactor: 1.2,

        child: new DropdownButton<User>(
          hint: new Text("Select a user"),
          value: selectedUser,
          onChanged: (User newValue) {
            _onChanged(newValue);
          },
          items: users.map((User user) {
            return new DropdownMenuItem<User>(
              value: user,
              child: new Row(children: <Widget>[new Text(
                user.name,
                style: new TextStyle(color: Colors.black),
              ),

              ]),
            );
          }).toList(),
        )));
    for (var i = 0; i < 1; i++) {
      inputField.add(new GestureDetector(

          child: new Container(


              padding: EdgeInsets.only(right: 30.0, left: 30.0, bottom: 10.0),
              child: new TextFormField(

                focusNode: _textFocus,
                keyboardType: TextInputType.number,
                controller: _c,

              ))));
    }

    inputField.add(
      Material(
          borderRadius: BorderRadius.circular(30.0),
          shadowColor: Colors.green,
          elevation: 5.0,
          child: MaterialButton(

            onPressed: () async {
              Contact contact = await _contactPicker.selectContact();

              setState(() {

                _contact = contact;


              });
            },
            color: Colors.red,
            child: new Text("Login", style: TextStyle(color: Colors.blue)),

          )
      ),
    );





    return inputField;
  }



  void _submitForm() {
    final form=formKey.currentState;
    if(form.validate())
      {
        form.save();
      }
  }
  void onChange(){


      FocusScope.of(context).requestFocus(_textFocus);

      _c.value = new TextEditingValue(text:"33333");
      _c.selection = new TextSelection(
          baseOffset:  _contact.phoneNumber.number.length,
          extentOffset:  _contact.phoneNumber.number.length
      );


  }
}

**Comment by zoechi** [comment]
@santosh12345
I'd suggest asking on StackOverflow.
