### ISSUE TITLE
Rebuild dart2wasm target when source files change.

### ISSUE THREAD

**Issue by eyebrowsoffire** [flutter/flutter#117411]
Now that dart2wasm added support for outputting a depfile (https://github.com/dart-lang/sdk/issues/50747), we should add that as a dependency in the `Dart2WasmTarget` so that changes in source files cause a rebuild of the wasm module.

**Comment by yjbanov** [comment]
Made this a P3 for now since it's part of the overall dart2wasm project, which is a P3.

**Comment by eyebrowsoffire** [comment]
I fixed this a while ago.
