### ISSUE TITLE
Issue after updating targetSdk

### ISSUE THREAD

**Issue by Somtobro** [flutter/flutter#117440]
My app was fine....I tried updating my app on playstore...I got an error that I needed to update to targetsdkversion of 31 to support Android 12.
So I increased the value in my build.gradle file, then I got another error that in my manifest I needed to add exported:true in my activity tag
After that I'm getting some very annoying build errors and I need to update my app before 26th of this month else it will be removed from the store ..

```
FAILURE: Build failed with an exception.

* Where:
Script 'C:\src\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1256

* What went wrong:
Could not determine the dependencies of task ':app:compileFlutterBuildRelease'.
> Index 1 out of bounds for length 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 8m 53s
Running Gradle task 'assembleRelease'...                          568.7s
Gradle task assembleRelease failed with exit code 1
```

That's the error above
PLEASE TREAT WITH URGENCY!!!!!
Note that :I have tried flutter clean, deleted build still same error

Please don't close it... THERE'S NO SOLUTION TO THIS ANYWHERE
WHOS GONNA HELP IF FLUTTER CUSTOMER SERVICE DOESN'T

**Comment by huycozy** [comment]
Hi @Somtobro
Does this issue happen when you run the project with `debug` or `release` mode? Please provide the output of `flutter run -v` with corresponding mode.

**Comment by Somtobro** [comment]
It does...I can't literally build it
Even appbundle
When I switch on my PC I will do that and upload here.but that would be
later
Thanks for the response
