### ISSUE TITLE
Keyboard on iOS flashes when switching between obscured and non-obscured TextFields

### ISSUE THREAD

**Issue by CoolDude53** [flutter/flutter#117494]
This issue was originally tracked here https://github.com/flutter/flutter/issues/64628 and seemingly fixed by https://github.com/flutter/engine/pull/20805.

While the crash was fixed with this PR, there is still a strange issue that causes a flickering when switching between a `TextField` which has `isObscure` set to true and another `TextField` with `isObscure` set to false.

After some testing with the engine, the delay added in https://github.com/flutter/engine/pull/20805 causes the autofill suggestion bar to reset, triggering two quick keyboard animation show events.

https://user-images.githubusercontent.com/11463426/117580317-68e7ce00-b0c5-11eb-8b4a-c889587701b6.mov

_Originally posted by @tobycaulk in https://github.com/flutter/flutter/issues/64628#issuecomment-835843556_

**Comment by darshankawar** [comment]
@CoolDude53 
There's similar [issue](https://github.com/flutter/flutter/issues/88354) open describing this case, so please follow-up in it for further updates.
Closing this as a duplicate.
