### ISSUE TITLE
[NavigationBar] ink ripple positioned is shifted in M3 

### ISSUE THREAD

**Issue by TahaTesser** [flutter/flutter#117420]
At first, I thought it might be a resolution issue it looks like the ink ripple rendered at a different vertical offset in M3 for some reason.

https://master-api.flutter.dev/flutter/material/NavigationBar-class.html

When running the example as it is without enabling M3, ink is rendered at the right location and you can't see peeking outside but when M3 is enabled, it's slightly off. 

![Screenshot 2022-12-21 at 01 15 1](https://user-images.githubusercontent.com/48603081/208785101-e98b4f46-6d0a-4e78-a1f9-ccb4816eaec2.png)

![Screenshot 2022-12-21 at 01 12](https://user-images.githubusercontent.com/48603081/208785105-ff1d7393-7d7e-4797-88d2-b79483699577.png)

**Comment by TahaTesser** [comment]
cc: @HansMuller 
Not sure why the ink ripple is shifted in M3. It might be due to the different label sizes in M2 and M3.  
I will fix this with a better a rect.

**Comment by rydmike** [comment]
When you change the height from 80dp, the M3 default, the ink ripple shifts with offset amount up/down equal to height change diff and direction. It affects both M2 and M3 mode. The issue did not exist in stable 3.3 but has now regressed into stable 3.7. 

See example here: https://github.com/rydmike/flex_color_scheme/issues/114

**Comment by TahaTesser** [comment]
@rydmike 
Thanks for the confirmation!

**Comment by rydmike** [comment]
Sadly it did not make it into 3.7.1, nor a bunch of other important M3 fixes that exist in master, oh well, later then... 😄
