### ISSUE TITLE
Add a visualisation aid for debugging the gesture arena

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#1174]

**Comment by abarth** [comment]
A start would be to just highlight all the widgets that have active participants in the arena.

**Comment by Hixie** [comment]
> A start would be to just highlight all the widgets that have active participants in the arena.

In most cases they all have the same geometry so that might not be that useful.


I'm going to close this bug because it's not clear what kind of bug this would help with. We can revisit once we have an actual bug to debug.
