### ISSUE TITLE
Error building my app

### ISSUE THREAD

**Issue by Somtobro** [flutter/flutter#117417]
My app was fine....I tried updating my app on playstore...I got an error that I needed to update to targetsdkversion of 31 to support Android 12.
So I increased the value in my build.gradle file, then I got another error that in my manifest I needed to add exported:true in my activity tag
After that I'm getting some very annoying build errors and I need to update my app before 26th of this month else it will be removed from the store ..

```
FAILURE: Build failed with an exception.

* Where:
Script 'C:\src\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1256

* What went wrong:
Could not determine the dependencies of task ':app:compileFlutterBuildRelease'.
> Index 1 out of bounds for length 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 8m 53s
Running Gradle task 'assembleRelease'...                          568.7s
Gradle task assembleRelease failed with exit code 1
```

That's the error above
PLEASE TREAT WITH URGENCY!!!!!
Note that :I have tried flutter clean, deleted build still same error

**Comment by darshankawar** [comment]
@Somtobro 
Looking at the error you are getting, it seems to be related to gradle configuration / sync and not specific to Flutter itself.
As you mentioned, you made changes to your `targetsdkversion` and then to `manifest` file, it seems these changes made have not been reflected properly or not in sync with your gradle configuration and hence you are getting the said error.
I suggest you to run `gradlew clean build` if you are on windows, or `./gradlew clean build` on mac and then try again to see if it helps.
Closing from here, as this is not specific to Flutter. You may also ask this question on support channels like StackOverflow for further resolution.
