### ISSUE TITLE
TextDirection docs - design decisions

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#11742]
The TextDirection API docs should have a "Design discussion" section that talks about our philosophy:

* We don't want to default things to LTR because in our experience systems that do that tend to short-change RTL environments.

**Comment by abarth** [comment]
Also, we should list out where we do have an LTR bias and discuss why we're using that design.

**Comment by abarth** [comment]
Might want to mention why we have the visual properties as well (instead of forcing everything into start/end).

**Comment by Hixie** [comment]
Places where we have an LTR bias include:

* Canvas origin is on the left rather than the right or on the center.
* Rows paint their widgets left-to-right even when the mainAxisAlignment is center (or similar), if there's no explicit textDirection.
* Our default localisation will be en-US, which is LTR (and we don't use the user's default directionality).
