### ISSUE TITLE
[DESKTOP] flutter can't detect windows platform

### ISSUE THREAD

**Issue by gaetan1903** [flutter/flutter#117591]
## Steps to Reproduce

flutter devices 

```
1 connected device:

Chrome (web) • chrome • web-javascript • Google Chrome 108.0.5359.125

```

No windows detected

Hower Visual Studio already installed with C++ developpement package

![image](https://user-images.githubusercontent.com/43904633/209336382-a6beece9-d10f-4fce-8a65-9a21835199d0.png)

## Logs

<details>
<summary>Logs</summary>

```
```
[✓] Flutter (Channel stable, 3.3.9, on Microsoft Windows [version 10.0.18362.207], locale fr-FR)
    • Flutter version 3.3.9 on channel stable at C:\Users\g.bakary\gaetan1903\custom\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b8f7f1f986 (4 weeks ago), 2022-11-23 06:43:51 +0900
    • Engine revision 8f2221fbef
    • Dart version 2.18.5
    • DevTools version 2.15.0

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\g.bakary\gaetan1903\custom\Sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[✓] VS Code (version 1.74.2)
    • VS Code at C:\Users\g.bakary\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.56.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 108.0.5359.125

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.

```
```

</details>

**Comment by gaetan1903** [comment]
![image](https://user-images.githubusercontent.com/43904633/209337586-bab29cd8-93e9-4aef-a8be-63d8cf04fc8a.png)

**Comment by stuartmorgan** [comment]
What is the output of `flutter config`? It looks like you may have disable Windows support at some point.

**Comment by gaetan1903** [comment]
i installed in other computer and it's work, 

when i run `flutter doctor` it's like that flutter doesn't detect Visual Studio in my computer

**Comment by huycozy** [comment]
@gaetan1903 Can you provide the output of this command from `%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\`:

```
.\vswhere -format json -utf8 -latest -prerelease -all
```

**Comment by stuartmorgan** [comment]
@huycozy If the problem were with VS detection there would be a Windows section indicating that VS wasn't found. What we need is the `flutter config` output I requested above, which the previous reply didn't provide.

**Comment by gaetan1903** [comment]
This is what gives `flutter config`

````
Settings:
  android-sdk: C:\Users\.......\Sdk
  enable-windows-desktop: false
  enable-windows-uwp-desktop: true

Analytics reporting is currently enabled.
````

**Comment by gaetan1903** [comment]
In fact the `windows-desktop was disable on my config.

I just enable it with `flutter config --enable-windows-desktop` and it works 

![tempsnip](https://user-images.githubusercontent.com/43904633/209522299-961ff53b-6d1b-4b21-8dfc-6a82c75341f8.png)
