### ISSUE TITLE
[integration_test] takeScreenshot() Method does not work in Flutter integration_test. Android-throws `platformException` and iOS throws `MissingPluginException`

### ISSUE THREAD

**Issue by RamyaAcharya** [flutter/flutter#117593]
**Env Details:**
**Devices**: Android and iOS
**Tools and TechStack**
- Flutter 2.10.5
- engine: revision 57d3bac3dd
- Tools: Dart 2.16.2
- DevTools: 2.9.2

## Steps to Reproduce

1. Calling method `takeScreenshot()` in integration_test test script file like shown in the Snapshot below
<img width="950" alt="Image1" src="https://user-images.githubusercontent.com/27681103/209341195-dad1fca0-3c64-4976-a3a7-f5c26107061b.png">
2. test_driver/integration_test.dart:
<img width="807" alt="2" src="https://user-images.githubusercontent.com/27681103/209341634-b63e4d96-ca7a-4571-8184-47e4fb6e1c03.png">
3. Upon running on an Android device, a `platformException` is thrown. The logs are attached
<img width="1269" alt="3" src="https://user-images.githubusercontent.com/27681103/209351686-16f79733-536d-44e0-9a5c-2b9a9b040e38.png">
4. Upon running on an ios device with `await binding.convertFlutterSurfaceToImage()`, a `MissingPluginException` is thrown. The logs are attached
<img width="1247" alt="4" src="https://user-images.githubusercontent.com/27681103/209351817-595fdace-a441-4adb-8825-3617f716b50a.png">

Command to run: `flutter drive --driver=test_driver/integration_test.dart --target=integration_test/test/<test_file_name>.dart --no-sound-null-safety -d emulator-5554`

**Expected results:**
1. Should be able to use `takeScreenshot()` to take screenshots on Android and iOS devices
2. Need a way to use `flutter test` rather than `flutter drive` for taking screenshots

**Actual results:**
Android - throws `platformException` and iOS throws `MissingPluginException` while using takeScreenshot() method

**Comment by huycozy** [comment]
@RamyaAcharya Can you retry on the latest Flutter channels (stable and master) to check if the issue still persists or not? (the latest Flutter stable is `3.3.10` and master is `3.7.0`)

If the issue still persists, please provide the sample code and the log in text format instead of a screenshot for better readability/investigation. Thanks!
