### ISSUE TITLE
[webview_flutter] Expose WebResourceErrorType

### ISSUE THREAD

**Issue by feinstein** [flutter/flutter#117556]
The lib doesn't expose the `WebResourceErrorType` enum, so we can't use it for comparisons or switch-case to check the generic error type that triggered the callback.

Is this a mistake? Because I don't see the point of having this field in the `WebResourceError` object if we can't use it.

**Comment by bparrishMines** [comment]
This is a mistake. Thanks for pointing this out! This will be fixed by https://github.com/flutter/plugins/pull/6877

**Comment by feinstein** [comment]
If anyone is stuck by this, in the meantime you can import the plataform interface package and get the class reference from there, just remember to remove it later, when the fix arrives.
