### ISSUE TITLE
SnackBar is not entirely flush with the bottom

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#11758]
## Steps to Reproduce

Seeing this in the Hamilton app, on Android O. App is version 1.1.2.

![screenshot_20170822-141013](https://user-images.githubusercontent.com/13644170/29630979-e9da19dc-87f2-11e7-8775-c07c8ca5b47d.png)

**Comment by Hixie** [comment]
cc @chinmaygarde and @jason-simmons who were looking at this recently.

It basically boils down to a rounding error with floats IIRC. But I thought it was fixed.

**Comment by chinmaygarde** [comment]
There were a couple of fixes for this issue. One of them was a workaround for Skia returning different bounds for rects that were drawn with AA toggled. The other was the raster cache [introducing a rounding error](https://github.com/flutter/engine/pull/3974) when snapshotting the sub-hierarchy. Both fixes have landed recently. What is the version of the framework and the engine that displays this issue?

**Comment by mit-mit** [comment]
I tried the following program today with flutter master from today, and it does *not* have the issue on my O phone.

Collin, is the currently published Hamilton app on an older framework?

```
import 'package:flutter/material.dart';

void main() {
  runApp(new MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: 'Flutter Demo',
      home: new Scaffold(
        appBar: new AppBar(title: new Text('Demo')),
        body: new Builder(builder: (BuildContext context) {
          return new Center(
            child: new FlatButton(
              child: new Text('Push me'),
              onPressed: () {
                Scaffold
                    .of(context)
                    .showSnackBar(new SnackBar(content: new Text('Hi!')));
              },
            ),
          );
        }),
      ),
    );
  }
}

```

**Comment by collinjackson** [comment]
I'm not 100% sure which version of Flutter the Hamilton 1.2 release used, but my best guess is 47fe630e4e5a8f6595314dbf701fdb9b7be6a331. There should be another release out soon.

**Comment by Hixie** [comment]
I'm pretty sure this was fixed. I'm going to close this. Please reopen if it's not fixed whenever the Hamilton app is next updated.

**Comment by sethladd** [comment]
cc @lukef
