### ISSUE TITLE
Error calling mmap with flutter ffi

### ISSUE THREAD

**Issue by SinkinZhu** [flutter/flutter#117588]
Dear Sir

In my embedded linux flutter APP,  It call ffi.DyamicLibrary.open to load one shared library. and this library will open "/dev/binder", and call mmap function to mmap binder
But  mmap return failed, we check binder driver's mmap function, and it failed wheh check "proc->tsk != current" :
static int binder_mmap(struct file *filp, struct vm_area_struct *vma)
{
        int ret;
        struct vm_struct *area;
        struct binder_proc *proc = filp->private_data;
        const char *failure_string;
        struct binder_buffer *buffer;

        if (proc->tsk != current)
                return -EINVAL;
        ... ...
}

We have checked this shared library, and it run normally when called by linux native program.

Does anyone call the mmap function normally through ffi ？ Thanks!

**Comment by dcharkes** [comment]
@SinkinZhu What OS are you running the Flutter app on? Linux Desktop? Android? And which version? Could you post your `flutter doctor -v` please?

Also, what arguments are you passing to mmap?

       EINVAL We don't like addr, length, or offset (e.g., they are too
              large, or not aligned on a page boundary).

       EINVAL (since Linux 2.6.12) length was 0.

       EINVAL flags contained none of MAP_PRIVATE, MAP_SHARED, or
              MAP_SHARED_VALIDATE.


https://man7.org/linux/man-pages/man2/mmap.2.html

**Comment by SinkinZhu** [comment]
Dear Sir
Thank for your response.
 Flutter app is running on the embedded linux (kernel version is 4.4)，the arguments passed to mmap is "PROT_READ, MAP_PRIVATE | MAP_NORESERVE"
We have tested this function using linux native program, and it work successfully.

**Comment by dcharkes** [comment]
> We have tested this function using linux native program.

So that is on the same embedded OS, with exactly the same arguments? Could you try printing `addr`, `length`, and `offset`? Just to double check?

I'm not familiar enough with the inner workings of `mmap` to say if the multi-threaded nature of Flutter would influence it. I believe `mmap` should not be dependent on threading.

Just to double check: This issue does not reproduce on a desktop Linux? Only on an embedded Linux?

**Comment by SinkinZhu** [comment]
Dear Sir

Sorry, we have checkd, this is binder driver's issue. I will close this issue, Thanks!
