### ISSUE TITLE
Flutter run doesn't update the entry point

### ISSUE THREAD

**Issue by B3rn475** [flutter/flutter#11752]
Using __Flutter Tools__ to start the same application with two different entry points always starts the first one.

Reproduction:
- On Terminal 1
```bash
cd flutter/dev/integration_tests/ui
flutter run lib/keyboard_resize.dart
```
- On Terminal 2
```bash
cd flutter/dev/integration_tests/ui
flutter run lib/commands.dart
```

This effect is visible in the `commands_test` flakines.
If `integration_ui` and `commands_test` run on the same bot the second one uses the wrong entry point.

Related https://github.com/flutter/flutter/issues/11502

**Comment by cbracken** [comment]
Should be fixed by #11762.
