### ISSUE TITLE
BoxConstraints has a negative minimum height TextFormField 

### ISSUE THREAD

**Issue by devendertomar** [flutter/flutter#117521]
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by darshankawar** [comment]
Same as https://github.com/flutter/flutter/issues/117520#issuecomment-1362553010
