### ISSUE TITLE
FlutterPluginRegistrant framework is not found

### ISSUE THREAD

**Issue by arun-mehra29** [flutter/flutter#117599]
I am trying to add my flutter code as a module into my native applications (Android and iOS).
I tried using option B following [this](https://docs.flutter.dev/development/add-to-app/ios/project-setup) link.
Unfortunately, the registrant xc framework is not getting generated. Whereas the same registrant class is generated for Android and I am able to open a web view using flutter (library used is flutter_inappwebview). 
Any insight on what could be going wrong?

1. Output for **'flutter doctor -v'** is

`[✓] Flutter (Channel stable, 3.0.1, on macOS 12.6 21G115 darwin-arm (Rosetta), locale en-IN)
    • Flutter version 3.0.1 at /Users/arunmehra/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (7 months ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/arunmehra/Library/Android/sdk
    • Platform android-32, build-tools 32.0.0
    • ANDROID_HOME = /Users/arunmehra/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Community Edition (version 2022.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.74.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (5 available)
    • SM N970U1 (mobile)         • R58MC1FL5KY                              • android-arm64  • Android 12 (API 31)
    • Arun’s iPhone (2) (mobile) • fc80b2bcc0321401536556e99c2f28f0d03f75db • ios            • iOS 15.6.1 19G82
    • iPhone 14 Pro (mobile)     • 5EED93CA-04D6-45BB-9DD3-990ED0E64DA5     • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-1 (simulator)
    • macOS (desktop)            • macos                                    • darwin-arm64   • macOS 12.6 21G115 darwin-arm (Rosetta)
    • Chrome (web)               • chrome                                   • web-javascript • Google Chrome 108.0.5359.124

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!`

2. Snippet of the **pubspec.yaml** file is

`dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_inappwebview: ^6.0.0-beta.21`

3. Output for '**flutter build ios-framework**' is

<img width="310" alt="Screenshot 2022-12-23 at 12 21 42" src="https://user-images.githubusercontent.com/119937993/209287093-40ffb7ea-befa-4999-b027-4641a1830123.png">

**Comment by huycozy** [comment]
@arun-mehra29 
Does this issue only happen when adding `flutter_inappwebview` plugin? Can you also retry on the latest Flutter `stable` or `master` to check if the issue still perisists or not?

**Comment by arun-mehra29** [comment]
@huycozy , I have tried multiple plugins (including webview_flutter and iOS specific webview_flutter_wkwebview) and I was facing the same issue.
I will update to latest Flutter stable version and reply back.

**Comment by arun-mehra29** [comment]
Updated to the latest stable flutter and I am facing the same issue.
1. Output of 'flutter build ios-framework output and flutter --version.


`arunmehra@IE6CX654W2MW3G another_sample_project % flutter build ios-framework --output=/Users/arunmehra/FlutterProjects/another_sample_project_dependency 
Running "flutter pub get" in another_sample_project...           2,582ms
 
💪 Building with sound null safety 💪

Building frameworks for com.sample.webview.anotherSampleProject in debug mode...
 ├─Copying Flutter.xcframework...                                   72ms
 ├─Building App.xcframework...                                     14.7s
Running pod install...                                             674ms
 ├─Building plugins...                                             28.4s
 └─Moving to ../another_sample_project_dependency/Debug            107ms
Building frameworks for com.sample.webview.anotherSampleProject in profile mode...
 ├─Copying Flutter.xcframework...                                   81ms
 ├─Building App.xcframework...                                     24.6s
 ├─Building plugins...                                             26.5s
 └─Moving to ../another_sample_project_dependency/Profile           88ms
Building frameworks for com.sample.webview.anotherSampleProject in release mode...
 ├─Copying Flutter.xcframework...                                  193ms
 ├─Building App.xcframework...                                     25.4s
 ├─Building plugins...                                             25.3s
 └─Moving to ../another_sample_project_dependency/Release           88ms
Frameworks written to /Users/arunmehra/FlutterProjects/another_sample_project_dependency.

Copy the GeneratedPluginRegistrant class into your project.
See https://flutter.dev/docs/development/add-to-app/ios/add-flutter-screen#create-a-flutterengine for more information.
arunmehra@IE6CX654W2MW3G another_sample_project % flutter --version
Flutter 3.3.10 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 135454af32 (12 days ago) • 2022-12-15 07:36:55 -0800
Engine • revision 3316dd8728
Tools • Dart 2.18.6 • DevTools 2.15.0`

<img width="342" alt="Screenshot 2022-12-27 at 14 23 25" src="https://user-images.githubusercontent.com/119937993/209640234-0b1e6369-d23e-4d19-9488-5ed81511faa6.png">

**Comment by arun-mehra29** [comment]
I have another doubt, when I build the iOS framework, I get a message that **Copy the GeneratedPluginRegistrant class into your project**, I tried copy pasting the GeneratedPluginRegistrant swift file into the project as well but the dependencies of the file are not resolved, is there a particular way to copy it or include it in the project? Moreover, when creating a new flutter project, I specifically selected just 'Android and iOS' platform support but the GeneratedPluginRegistrant contains '**import FlutterMacOS**' as well, is this expected?

**Comment by huycozy** [comment]
>I have tried multiple plugins (including webview_flutter and iOS specific webview_flutter_wkwebview) and I was facing the same issue.

Can you retry removing `webview_flutter` plugin to check if the issue still persists or not? If it still persists, can you share the error message if any?

There is also a prebuilt module sample that you can try with it:  https://github.com/flutter/samples/tree/main/add_to_app/prebuilt_module

**Comment by arun-mehra29** [comment]
> Can you retry removing `webview_flutter` plugin to check if the issue still persists or not? If it still persists, can you share the error message if any?

Yes, I have tried after removing 'webview_flutter', there are no errors that I can share.

>There is also a prebuilt module sample that you can try with it: https://github.com/flutter/samples/tree/main/add_to_app/prebuilt_module

I will try with this prebuilt module and update.

**Comment by arun-mehra29** [comment]
@huycozy , I tried building iOS framework from the prebuilt module sample by `flutter build ios-framework --output=/Users/arunmehra/FlutterProjects/flutter_sample_project_dependency`
I can see the **FlutterPluginRegistrant** in the output directory


<img width="377" alt="Screenshot 2022-12-30 at 12 44 29" src="https://user-images.githubusercontent.com/119937993/210044490-d7730ac7-913c-4d7d-895c-aa154aa24bc5.png">

**Comment by huycozy** [comment]
@arun-mehra29 
I'm trying to reproduce this from a new project but I see `FlutterPluginRegistrant` is generated as expected:

<img width="400" src="https://user-images.githubusercontent.com/104349824/210064805-a90e326f-103b-4b54-b26b-11be4e098b2c.png">

As far as I can see, you are using the old Flutter version `3.0.1`, the latest Flutter stable is `3.3.10` and the master is `3.7.0`. Can you try upgrading them and retry to see if this issue still reproduces?

**Comment by arun-mehra29** [comment]
@huycozy ,
https://github.com/flutter/flutter/issues/117599#issuecomment-1365723480 in this comment the Flutter version mentioned is 3.3.0. I have already updated to the latest stable Flutter version.

**Comment by huycozy** [comment]
@arun-mehra29 Sorry I forgot to look back at that comment. I guess you miss something to the tool can recognize if you have a plugin with iOS platform code. Please check my below steps:

1. From the terminal, go to your current iOS native project, for eg: `/Users/.../reproduce_issue_ios_native_addtoapp/`
2. Create flutter module and go to module directory
```
flutter create --template module my_flutter
cd my_flutter
```
3. Add plugin to flutter module
```
flutter pub add webview_flutter
```
4. Create a new directory from your current iOS native project directory, for eg: `ios_using_prebuilt_module/Flutter`
5. Execute build ios-framework command, for eg:
```
flutter build ios-framework --xcframework --output='/Users/.../reproduce_issue_ios_native_addtoapp/ios_using_prebuilt_module/Flutter'
```

The result:

```bash
Flutter
├── Debug
│   ├── App.xcframework
│   ├── Flutter.xcframework
│   ├── FlutterPluginRegistrant.xcframework
│   ├── OrderedSet.xcframework
│   ├── flutter_inappwebview.xcframework
│   └── webview_flutter_wkwebview.xcframework
├── Profile
│   ├── App.xcframework
│   ├── Flutter.xcframework
│   ├── FlutterPluginRegistrant.xcframework
│   ├── OrderedSet.xcframework
│   ├── flutter_inappwebview.xcframework
│   └── webview_flutter_wkwebview.xcframework
└── Release
    ├── App.xcframework
    ├── Flutter.xcframework
    ├── FlutterPluginRegistrant.xcframework
    ├── OrderedSet.xcframework
    ├── flutter_inappwebview.xcframework
    └── webview_flutter_wkwebview.xcframework
```

**Comment by arun-mehra29** [comment]
@huycozy , I will try it tomorrow and update.

**Comment by arun-mehra29** [comment]
@huycozy , in your above comment, you are creating a new **module** and then adding it as a framework dependency, if I try this, it works fine but the same is not working when I am creating a new **project**.

**Comment by huycozy** [comment]
@arun-mehra29 As documentation [here](https://docs.flutter.dev/development/add-to-app/ios/project-setup), you need to create a Flutter module in order to embed Flutter into your existing application. 

I haven't tried adding Flutter project to iOS native project, if you have a document source for this, please share it. Thanks!

**Comment by arun-mehra29** [comment]
@huycozy , I have created a module and embedded it into my existing application and it works as expected. Hence, closing this issue. Thank you for your help and time. Much appreciated.
