### ISSUE TITLE
Google Sign In, signing out doesn't re-prompt account selection on Web

### ISSUE THREAD

**Issue by dhust** [flutter/flutter#117543]
When I logout, on Android, and go to sign back in it prompts me to pick an account to login with. When I run it in Chrome it just auto logs my back in without showing a list of accounts to pick from. 
I've found it to be the case that when logging out of `FirebaseAuth` (`_auth`) it will just log me back in automatically, but when I logout of `googleSignIn` too it will reprompt, but only on Android. So this works with Android but not on the web version of the app.
```
Future<void> signOut() async {
    await _auth.signOut();
    await googleSignIn.signOut();
}
```

**Comment by huycozy** [comment]
@dhust I've tried verifying this with [google_sign_in's example](https://github.com/flutter/plugins/tree/main/packages/google_sign_in/google_sign_in/example) but it still works as expected on Chrome. 

What is your current `google_sign_in` plugin version? Please try using google_sign_in's example on the latest plugin version to see if the issue still persists or not. Also, please provide the output of `flutter doctor -v` as well.

**Comment by dhust** [comment]
Ok. Thanks for that. Not sure what I ended up changing, because it looks like I changed it all back, but it's working now. :)

**Comment by huycozy** [comment]
Given your last message, I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. Thanks!
