### ISSUE TITLE
Add additional network switches for devicelab racks

### ISSUE THREAD

**Issue by yusuf-goog** [flutter/flutter#117548]
Please follow up with necessary netops team to get additional network switches installed for at least one (ideally all 3) of our additional racks in the devicelab.

**Comment by kentnguyen99** [comment]
Will do.

**Comment by kentnguyen99** [comment]
Hi @yusuf-goog Just checking... Are you still want me to following up with Network Teams on this service ticket?

**Comment by yusuf-goog** [comment]
We added our own switch to the rack. closing
