### ISSUE TITLE
Example for ThemeData extensions property does not run in Dart pad on the page

### ISSUE THREAD

**Issue by russellminnich** [flutter/flutter#117512]
https://api.flutter.dev/flutter/material/ThemeData/extensions.html#material.ThemeData.extensions.1

When I click Run in the sample in the DartPad area, I get the following error:

`line 23 • 'MyColors.lerp' ('MyColors Function(MyColors?, double)') isn't a valid override of 'ThemeExtension.lerp' ('ThemeExtension<MyColors> Function(ThemeExtension<MyColors>?, double)').[ (view docs)](https://dart.dev/diagnostics/invalid_override)
The member being overridden`

**Comment by darshankawar** [comment]
Thanks for the report @russellminnich 
I am seeing same error on latest stable while running through Android Studio, so it doesn't seem to be dartpad specific issue. 

<img width="659" alt="Screenshot 2022-12-22 at 1 25 31 PM" src="https://user-images.githubusercontent.com/67046386/209085322-3453902a-ec95-4bb4-ab8d-56e962f4a069.png">


On latest master, it does not throw the same error though. You may try to switch to latest master to get the code running. 

I'll keep this issue open for team's attention, although I think this would most probably looks like a dart lang side issue.

**Comment by guidezpl** [comment]
This is issue is fixed in the latest beta (`3.7.0-1.4.0.pre`) so I'll close this issue.
