### ISSUE TITLE
fix xcode usage in LUCI  

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#117541]
The following is the list of things to solve with a refactoring of the xcode tooling, modules and recipes:

- [x] Consolidate different xcode named caches into one `flutter_xcode` with path `osx_sdk` https://flutter-review.googlesource.com/c/infra/+/42061
- [x] Add xcode version support from recipes: https://flutter-review.googlesource.com/c/recipes/+/42160
- [x] Documentation - Update documentation with the status quo including user facing information to troubleshoot problems https://github.com/flutter/cocoon/pull/2813
- [x] Caches - Efficient caching of xcode versions in a way that once they are installed it will only take seconds on subsequent installations of the same version https://flutter-review.googlesource.com/c/recipes/+/42160
- [x] Runtime installation - support the installation of one or more runtime without impacting caches or subsequent builds https://flutter-review.googlesource.com/c/recipes/+/42160
- [x] Cache pollution - avoid modifying xcode directories to prevent cache pollution (e.g. adding files, symlinks, etc) https://flutter-review.googlesource.com/c/recipes/+/42160
- [x] Clean cache when identified as polluted https://github.com/flutter/flutter/issues/125273 https://flutter-review.googlesource.com/c/recipes/+/44761
- [x] Multiple xcode versions with different runtime combinations, ensure original caches remain unchanged when runtimes are installed. https://flutter-review.googlesource.com/c/recipes/+/42160
- [x] Consolidate flutter/osx_sdk with flutter/devicelab_osx_sdk
  - [x] supports devicelab in flutter/osx_sdk https://flutter-review.googlesource.com/c/recipes/+/43824
  - [x] adds osx_sdk property to devicelab targets https://github.com/flutter/cocoon/pull/2698 https://flutter-review.googlesource.com/c/infra/+/43921
  - [x] switch devicelab recipes to use osx_sdk module https://flutter-review.googlesource.com/c/recipes/+/43980
  - [x] remove device_osx_sdk property from devicelab targets 
  - [x] clean up devicelab_osx_sdk module https://flutter-review.googlesource.com/c/recipes/+/44001 https://flutter-review.googlesource.com/c/infra/+/44542 https://github.com/flutter/cocoon/pull/2756
- [x] Clean up obsolete/stale xcode versions: https://flutter-review.googlesource.com/c/recipes/+/42900
- [x] Simplify/consolidate xcode configurations: https://github.com/flutter/flutter/issues/127534

**Comment by godofredoc** [comment]
Research steps to prevent making the same mistakes over and over:

- [ ] Identify and document cipd behavior in LUCI bots, is cipd caching packages independently of the bot.
    * If a huge CIPD package is installed and removed does it download it again? or just copies the content from the cached zip file to the new location?
    * What is the CIPD behavior when files are locally modified/deleted/added and we try to reinstall again?
- [ ] Identify named caches and [cache]/abc behavior and document it
   * What happens when I replace the content of a named cache? e.g. I request xcode_14 to be mounted in [cache]/xcode then I replace the content of [cache]/xcode with xcode 12, what do I get the next time a build runs on that bot that request xcode_14 cache?
   * What is the behavior of [cache] folder for directories that are not matching a named cache mount? are they kept or deleted after the task?

**Comment by godofredoc** [comment]
\cc @jmagman anything that we are missing here?

**Comment by jmagman** [comment]
Note: "Runtime installation" here means the iOS simulator runtime that is installed as a separate cipd package.

Perhaps this is implicitly covered in making the caches more resilient, but some goals:

1. Assuming a correct Xcode cipd package, allow updating Xcode versions in all pools by just editing version and/or simulator runtime version in `.ci.yaml`.
2. Allow a PR with a new Xcode version to run all tests in the try pool without corrupting other tests running on the same bots.
3. Unless otherwise specified in the `.ci.yaml`, install the default runtime associated with the Xcode version (the default mac_toolchain behavior).
4. Allow different Xcode/runtime versions between engine, framework, packages, plugins repos without cross-contamination.
5. Allow running different Xcode/runtime versions against tests on different release branches without cross-contamination (newer version on master than beta or stable).

Cross-listing some previous issues:
https://github.com/flutter/flutter/issues/113539
https://github.com/flutter/flutter/issues/110543
https://github.com/flutter/flutter/issues/100921
https://github.com/flutter/flutter/issues/99429
https://github.com/flutter/flutter/issues/99039
https://github.com/flutter/flutter/issues/97303
https://github.com/flutter/flutter/issues/94780
https://github.com/flutter/flutter/issues/94474

Xcode planning brief https://docs.google.com/document/d/1QKHf2YBs21Mm89Exj0z0aOqE-GR6wYuLsiqXI-LofvQ/edit?resourcekey=0-l9DaaVR-N9SSA3B7OhhGPA

**Comment by godofredoc** [comment]
Updates:

* caches of xcode can be reused without named caches.

Examples:

* First run: https://chromium-swarm.appspot.com/task?id=5f545c4e1d142d10
* Second run: https://chromium-swarm.appspot.com/task?id=5f547c6646e97c10

The trick here is to use the xcode version as part of the path.

**Comment by jmagman** [comment]
> The trick here is to use the xcode version as part of the path.

How does that work with different simulator runtime versions?

**Comment by jmagman** [comment]
Example of two runtime versions: https://ci.chromium.org/p/flutter/builders/prod/Mac%20Unopt/9400

**Comment by godofredoc** [comment]
\cc @yusuf-goog

**Comment by keyonghan** [comment]
> Example of two runtime versions: https://ci.chromium.org/p/flutter/builders/prod/Mac%20Unopt/9400

I think we can append the runtime version to the sdk version in the path:
1) if a target doesn't need runtime, but an xcode version: 14a5294e, we use cache dir: $cache/14a5294e/XCode.app
2) if a target doesn't need runtime, but an xcode version: 14c18, we use cache dir: $cache/14c18/XCode.app
3) if a target needs a runtime: ios-13-0, and an xcode version: 14a5294e, we use cache dir: $cache/14a5294e_ios-13-0/XCode.app
4) if a target needs two runtimes: ios-13-0 and ios-16-0_14a5294e, and an xcode version: 14a5294e, we use cache dir: $cache/14a5294e_ios-13-0_ios-16-0_14a5294e/XCode.app

As of now we have only one target `Mac Unopt ` which needs one runtime.

This way, the cache dir is no difference between release branches and main/master ones. They should not cross-contaminate with each other as we are distinguishing by xcode version and runtime version. If a bot runs a target which needs a different version of xcode or runtime, it simply installs everything based on that specific version. But once it is installed, any other targets with same versions should benefit from the already installed cache.

With this proposal, we should get rid of redundant actions: clean up xcode and reinstall xcode, delete runtime, and reinstall runtime on every single build. I will play around with some LED runs, and dig a bit further about runtime install cache (which doesn't seem to work though we install the runtime under $cache) before jumping into a doc detailing all changes.

**Comment by jmagman** [comment]
> 4\. if a target needs two runtimes: ios-13-0 and ios-16-0_14a5294e, and an xcode version: 14a5294e, we use cache dir: $cache/14a5294e_ios-13-0_ios-16-0_14a5294e/XCode.app

We did have something similar to this at one point: 
https://github.com/flutter/engine/pull/31915/files#r822220027

**Comment by jmagman** [comment]
And @CaseyHillers deleted it in flutter/engine#32986 with https://github.com/flutter/flutter/issues/100259

**Comment by keyonghan** [comment]
Frankly speaking, I don't think our versioning cache ever works as expected.

The version in `name` does not make much difference. It is just a notation telling different builds/bots that the same mounted `path` is sharable. Thus the `path` is the one that matters, which is what is suggested above.

When a target runs a different xcode version, it installs that xcode to the same path `osx_sdk` though they have different `name`. This explains why we repeatedly hit the xcode version contamination when we do upgrade.

**Comment by CaseyHillers** [comment]
> The version in name does not make much difference. It is just a notation telling different builds/bots that the same mounted path is sharable. Thus the path is the one that matters, which is what is suggested above

You're right. LUCI needs to expose a way for schedulers to control the caches directly instead of relying on the LUCI configs. Everything we've done before are bandage fixes that ignore the root cause.

**Comment by jmagman** [comment]
Very happy you're working on this @keyonghan!  I added that comment above as a paper trail, we should implement or reinstate whatever caching logic prevents the bot fleet from contamination.  Happy to test or help out in any way.

**Comment by keyonghan** [comment]
With cache versioned and [config consolidated](https://github.com/flutter/flutter/issues/127534), I will mark this as fixed.
