### ISSUE TITLE
After checking AppLifecycleState onresume shared preferences issue

### ISSUE THREAD

**Issue by MrEbadAli** [flutter/flutter#117516]
When application coming from background my onresume function is called. Then if user remove his registration (clear his values from shared preferences by calling sharedpreferences.clear) and try to register again (Saving value in shared preferences). I am unable to save the values again. If I am removing the Applifecyclestate code it's working fine. Face this issue only on android.

**Comment by darshankawar** [comment]
@MrEbadAli 
In order to properly analyze the issue, please provide `flutter doctor -v`, a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) along with steps to replicate and current vs expected behavior.

**Comment by MrEbadAli** [comment]
**I am using this shared preferences plugin shared_preferences: ^2.0.15.**
```
Future<void> main() async {
  await SharedPreferences.getInstance();
  runApp(const MyApp());
}
```
**Saving the value in shared preferences in my registration class:**
e.g:
on button click i am saving this value and redirect to next screen.
`SharedPreferences.getInstance().setString("name","EbadAli");`

**On next Screen I extend my class with WidgetsBindingObserver and using this code:**

```
@override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    if(state == AppLifecycleState.resumed){
      callApi();
    }
  }

```

**And remove account button is available on next screen on click of that button I am clearing the share preference and redirect to my first registration screen**

```
SharedPreferences.getInstance().clear();
Navigator.pushAndRemoveUntil<dynamic>(
                                    context,
                                    MaterialPageRoute<dynamic>(
                                      builder: (BuildContext context) => const RegistrationPage(),
                                    ),
                                        (route) => false,
                                  );
```

After Coming I am unable to save the value on my first page registration screen again.

**If I remove only this code it's working fine.**

```
@override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    if(state == AppLifecycleState.resumed){
      callApi();
    }
  }
```





Flutter doctor is attached
<img width="821" alt="Screenshot 2022-12-22 at 2 40 45 PM" src="https://user-images.githubusercontent.com/41823250/209122166-de75991f-4311-4b39-ac78-5ef488ec9b0b.png">

**Comment by darshankawar** [comment]
@MrEbadAli 
Thanks for the update. This probably looks like more of an implementation issue rather than plugin / framework one. Please check [this](https://stackoverflow.com/questions/69065753/how-to-reload-elements-after-getting-data-from-shared-preferences) SO link and also try the [plugin example](https://github.com/flutter/plugins/blob/main/packages/shared_preferences/shared_preferences/example/lib/main.dart) and see if it helps in your case to properly implement the use case you are trying.
