### ISSUE TITLE
firebase_database: FirebaseAnimatedList should expose index to itemBuilder

### ISSUE THREAD

**Issue by pcomans** [flutter/flutter#11760]
This is regarding firebase_database 0.0.14

I noticed that the itemBuilder for FirebaseAnimatedList has the following typedef:
```
typedef Widget FirebaseAnimatedListItemBuilder(
  BuildContext context,
  DataSnapshot snapshot,
  Animation<double> animation,
);
```
The itemBuilder of AnimatedList has the following typedef:
```
typedef Widget AnimatedListItemBuilder(
  BuildContext context,
  int index, 
  Animation<double> animation,
);
```
The index of the current element being rendered is essentially being hidden by FirebaseAnimatedList. It would be very useful for creating numbered lists / striped lists etc.

Is this omission by design? Can we add index to FirebaseAnimatedListItemBuilder?

I am aware that this is a breaking change so I'm open to feedback.

**Comment by pcomans** [comment]
Pull request is here: https://github.com/flutter/plugins/pull/202

**Comment by kroikie** [comment]
@pcomans

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/972. Any further collaboration will be done there.
