### ISSUE TITLE
Display branded launch screens on start up

### ISSUE THREAD

**Issue by merlinfotsing** [flutter/flutter#11768]
## Branded launch screens on application start up

Is there a way to display branded launch screens, logo or others elements on application start up?

**Comment by eseidelGoogle** [comment]
There are various approaches to this.  https://stackoverflow.com/questions/43879103/adding-a-splash-screen-to-flutter-apps is one.

**Comment by Hixie** [comment]
We support this now. There's some documentation on the Web site about how to do it, or you can look in the files that are created by `flutter create`, they talk about it in the comments.

**Comment by merlinfotsing** [comment]
I've read the documentation. Is much better now. THX

**Comment by navneetgarggate6** [comment]
Can anyone provide more detail about this like document link or example code?

**Comment by zoechi** [comment]
@navneetgarggate6 check the StackOverflow comment above and the other documentation is in the generated code if you create a new project using `flutter create`.

**Comment by navneetgarggate6** [comment]
@zoechi it means the only way to change launch screen we need to change android or ios files?

**Comment by zoechi** [comment]
@navneetgarggate6 yes, they are shown while the app loads, so doing it in Dart would be too late.

**Comment by navneetgarggate6** [comment]
@zoechi thanks. but flutter should provide this in dart code instead of changing in android or ios.

**Comment by zoechi** [comment]
As I said, Flutter code is executed later and that would be weird to not see the splash screen until Dart code is executed. Actually bridging this gap is what a splash screen is for in the first place.
Flutter code can't work around how platforms work.

**Comment by navneetgarggate6** [comment]
The same issue is in ionic, react native handle it in a better way. Flutter should give some utility to generate android and ios files.
