### ISSUE TITLE
Mac touchpad gesture can not scroll Listview on Flutter3.3.9

### ISSUE THREAD

**Issue by cuishijie1991** [flutter/flutter#117641]
As u know, Macbook users are more used to using a trackpad than a mouse.
When I upgraded the flutter from 3.0.5 to 3.3.9, I found that the scrolling of the ListView widget could no longer be done with touchpad gestures (two fingers sliding up and down). It seems that this behavior is disabled.

There's no mention of changes to Flutter3.3 touch pad. This is a very common operation and should not be banned by default.

[✓] Flutter (Channel stable, 3.3.9, on macOS 11.6.1 20G224 darwin-x64, locale zh-Hans-CN)
• Flutter version 3.3.9 on channel stable at /Users/mac/flutter3.3
• Upstream repository https://github.com/flutter/flutter.git
• Framework revision https://github.com/flutter/flutter/commit/b8f7f1f9869bb2d116aa6a70dbeac61000b52849 (4 周前), 2022-11-23 06:43:51 +0900
• Engine revision 8f2221fbef
• Dart version 2.18.5
• DevTools version 2.15.0
• Pub download mirror https://pub.flutter-io.cn/
• Flutter download mirror https://storage.flutter-io.cn/

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
• Android SDK at /Users/mac/Library/Android/sdk
✗ cmdline-tools component is missing
Run path/to/sdkmanager --install "cmdline-tools;latest"
See https://developer.android.com/studio/command-line for more details.
✗ Android license status unknown.
Run flutter doctor --android-licenses to accept the SDK licenses.
See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
• Xcode at /Applications/Xcode.app/Contents/Developer
• Build 13A1030d
• CocoaPods version 1.11.3

[✓] Chrome - develop for the web
• Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
• Android Studio at /Applications/Android Studio.app/Contents
• Flutter plugin can be installed from:
🔨 https://plugins.jetbrains.com/plugin/9212-flutter
• Dart plugin can be installed from:
🔨 https://plugins.jetbrains.com/plugin/6351-dart
• Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.3.3)
• IntelliJ at /Applications/IntelliJ IDEA.app
• Flutter plugin version 45.1.2
• Dart plugin version 193.7547

[✓] Connected device (2 available)
• macOS (desktop) • macos • darwin-x64 • macOS 11.6.1 20G224 darwin-x64
• Chrome (web) • chrome • web-javascript • Google Chrome 108.0.5359.124

[✓] HTTP Host Availability
• All required HTTP hosts are available

! Doctor found issues in 1 category.
Process finished with exit code 0

**Comment by huycozy** [comment]
@cuishijie1991 I test with a simple `ListView` on the latest Flutter stable `3.3.10` but don't see this issue. The list scrolls normally using touchpad. 

Can you provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this?

**Comment by cuishijie1991** [comment]
> @cuishijie1991 I test with a simple `ListView` on the latest Flutter stable `3.3.10` but don't see this issue. The list scrolls normally using touchpad.
> 
> Can you provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this?

Sorry bro, I finally found out that I was wrong ! Our project overwrote WidgetsFlutterBinding in Flutter3.0.5, which caused the touch pad rolling failure after the update with flutter. Thank you for your work
