### ISSUE TITLE
[Windows] Dark theme in Windows 10 has a light title bar 

### ISSUE THREAD

**Issue by Seawolf159** [flutter/flutter#117692]
Basically everything in #107926. it's not actually fixed.

![image](https://user-images.githubusercontent.com/38156717/209716457-dd23cbae-a98d-481c-98ae-9dff2a4f3120.png)
white title bar even though my windows is set to dark mode and the app is too.

![image](https://user-images.githubusercontent.com/38156717/209716477-e9a0b719-6998-402a-b711-8d2a87043967.png)

Also i would like to make it dark regardless of what the windows system theme is. Is that possible?

Somehow managed to do it myself with the info in the other issues that have been linked.

![image](https://user-images.githubusercontent.com/38156717/209718217-57d026c2-fb8b-4678-8656-e24bdd1c8ca9.png)

had to add things in the `windows\runner\win_32_window.cpp` file:
At the top of the file 1 line above `#include <flutter_windows.h>` add this:
`#include <dwmapi.h>`
![image](https://user-images.githubusercontent.com/38156717/209718768-7ea3cd29-8890-4ef1-ae0b-b1139f756cc7.png)

add after `namespace {`
```
#ifndef DWMWA_USE_IMMERSIVE_DARK_MODE
#define DWMWA_USE_IMMERSIVE_DARK_MODE 20
#endif
```
![image](https://user-images.githubusercontent.com/38156717/209718786-d3d531ec-ee7a-4390-a756-c90be93c0fb4.png)

Below the CreateWindow function add this
```
  BOOL value = true;
  DwmSetWindowAttribute(window, DWMWA_USE_IMMERSIVE_DARK_MODE,
                        &value, sizeof(value));
```
![image](https://user-images.githubusercontent.com/38156717/209718928-226a047b-a75a-42dd-993d-bf0915b088fd.png)

**Comment by huycozy** [comment]
@Seawolf159 Thank you for filing the issue. I also can reproduce this on the latest `stable` and `master` channels.

<details>
<summary>Demo</summary>

![Capture](https://user-images.githubusercontent.com/104349824/209767944-236fe7ad-e0a7-4e7e-a63d-f2e2486a8211.PNG)

</details>

<details>
<summary>Sample code</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData.dark(),
      home: Scaffold(
        body: Container(),
      ),
    );
  }
}
```
</details>

<details>
<summary>flutter doctor -v (stable & master)</summary>

```bash
[√] Flutter (Channel stable, 3.3.10, on Microsoft Windows [Version 10.0.19045.2364], locale en-US)
    • Flutter version 3.3.10 on channel stable at C:\WIP\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (4 days ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

Checking Android licenses is taking an unexpectedly long time...[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at C:\AndroidSDK
    • Platform android-32, build-tools 32.0.0
    • ANDROID_HOME = C:\AndroidSDK
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.2.6)
    • Visual Studio at D:\DOWNLOADWORK\VS2022
    • Visual Studio Community 2022 version 17.2.32630.192
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[!] Android Studio (version 2022.1)
    • Android Studio at C:\Program Files\Android\Android Studio Electric Eel 2022.1.1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    X Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[√] VS Code (version 1.73.1)
    • VS Code at C:\Users\ADMIN\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.52.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19045.2364]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 108.0.5359.125
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 107.0.1418.35

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

```bash
[!] Flutter (Channel master, 3.7.0-13.0.pre.93, on Microsoft Windows [Version 10.0.19045.2364], locale en-US)
    • Flutter version 3.7.0-13.0.pre.93 on channel master at C:\WIP\flutter_master
    ! Warning: `flutter` on your path resolves to C:\WIP\flutter\bin\flutter, which is not inside your current
      Flutter SDK checkout at C:\WIP\flutter_master. Consider adding C:\WIP\flutter_master\bin to the front of your
      path.
    ! Warning: `dart` on your path resolves to C:\WIP\flutter\bin\dart, which is not inside your current Flutter SDK
      checkout at C:\WIP\flutter_master. Consider adding C:\WIP\flutter_master\bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d108c912cf (2 hours ago), 2022-12-27 23:15:25 -0500
    • Engine revision bfecc4b18d
    • Dart version 3.0.0 (build 3.0.0-67.0.dev)
    • DevTools version 2.20.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git"
      directly to perform update checks and upgrades.

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at C:\AndroidSDK
    • Platform android-32, build-tools 32.0.0
    • ANDROID_HOME = C:\AndroidSDK
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.2.6)
    • Visual Studio at D:\DOWNLOADWORK\VS2022
    • Visual Studio Community 2022 version 17.2.32630.192
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[!] Android Studio (version 2022.1)
    • Android Studio at C:\Program Files\Android\Android Studio Electric Eel 2022.1.1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    X Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[√] VS Code (version 1.74.2)
    • VS Code at C:\Users\ADMIN\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.56.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19045.2364]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 108.0.5359.125
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 108.0.1462.54

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.
```
</details>

/cc @loic-sharma

**Comment by loic-sharma** [comment]
@Seawolf159 Dark title bar support will be added in the next Flutter version. Apps created before the next Flutter version will need to be migrated to support dark title bars, similar to the steps you took.

<details>
<summary>Migration steps for existing projects...</summary>

⚠️ As of December 28th 2022, dark title bars is only supported on the latest `master` and `beta` release channels. If you are on `stable`, you will need to [switch to the `beta` release channel](https://docs.flutter.dev/development/tools/sdk/upgrading#switching-flutter-channels) before doing the migration.

1. Use `flutter upgrade` to update to the latest version of the Flutter SDK
2. Backup your project, possibly using git or some other version control system
3. Delete the `windows/runner/win32_window.cpp` file
4. Run `flutter create --platforms=windows .`
5. Review the changes to your `windows/runner/win32_window.cpp` file
6. Verify your app builds using `flutter build windows`

</details>

@huycozy On `beta` and `master`, overriding the `MaterialApp`'s theme will not override the title bar's theme. However, both the `MaterialApp` and the Windows title bar should use the system theme by default. Did you set your Windows system theme to dark mode? On Windows 11, you'll need to use the `Settings` app, navigate to `Personalization` and `Colors`, and select the `Dark` mode. Please let me know if I misunderstood your comment!

**Comment by huycozy** [comment]
@loic-sharma 

>Did you set your Windows system theme to dark mode? On Windows 11, you'll need to use the Settings app, navigate to Personalization and Colors, and select the Dark mode.

Yes. I tried the same setting on my Windows 10. But actually, I was using my old project to reproduce this issue (my bad). When creating a new project, the issue will not happen (the window will has a dark title bar as expected)

| old project| new project |
| --------------- | --------------- |
<video src="https://user-images.githubusercontent.com/104349824/209897168-c2a1b3aa-27ac-4214-9652-75fdddc3e276.mp4"/> | <video src="https://user-images.githubusercontent.com/104349824/209897165-af7fe9d0-4902-41e4-8b92-cf9300c4ba0e.mp4"/>

@Seawolf159 Can you retry on the latest Flutter `beta` or `master` channel and confirm this?

**Comment by Seawolf159** [comment]
With some difficulty i was able to make a test project made with the master channel. I wasn't able to build a .exe so maybe that's why i couldn't get it to change the title bar colour while the debugger was running and me changing the theme back and forth as you did @huycozy , but it did run the debugger app window with a white title bar when i my windows theme was light, and a black title bar when my windows theme was dark when i launched the debugger and it worked regardless of whether or not my application theme was dark (`theme: ThemeData.dark(),`) or default. ```(ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
      ),)```

I assumed because the issue was mentioned as fixed about 2-3 months ago, it would have been in my version by now, but i guess that's not how it works.

Also if i have my application theme set to dark (not caring about user system settings), and the windows user has the windows theme set to light, can i still force a dark title bar without doing what i did in my first mesage by changing things manually in the `windows\runner\win_32_window.cpp` file, which i guess when this update does come in, would have to be done differently?

**Comment by Seawolf159** [comment]
After trying some more, i did build an exe, but i assumed it didn't launch because it didn't work, but when i change my system theme, the application window does show up. It then doesn't swap title bar colour as i change my windows theme back and forth though. No idea what i'm doing wrong.

**Comment by loic-sharma** [comment]
> Also if i have my application theme set to dark (not caring about user system settings), and the windows user has the windows theme set to light, can i still force a dark title bar without doing what i did in my first mesage by changing things manually in the `windows\runner\win_32_window.cpp` file, which i guess when this update does come in, would have to be done differently?

Yup, if that's the desired behavior for your app you will need to modify the `win32_window.cpp` file. All the files under the `windows/runner` directory are owned by the app, you can modify them as much as you'd like!

> After trying some more, i did build an exe, but i assumed it didn't launch because it didn't work, but when i change my system theme, the application window does show up

I wasn't able to reproduce this issue. Could you provide steps on how to reproduce this using the `master` channel on a brand new Flutter project?

**Comment by Seawolf159** [comment]
Had to lower the quality to fit it in here. I hope it's clear enough.
https://user-images.githubusercontent.com/38156717/210014314-4adee9ae-35bf-4478-aff8-0970b9b9513c.mp4

**Comment by loic-sharma** [comment]
Did you follow the migration steps from my comment above? See: https://github.com/flutter/flutter/issues/117692#issuecomment-1366840701

Specifically, your app needs to handle the `WM_DWMCOLORIZATIONCOLORCHANGED` message to respond to system color mode changes. Here's the logic for a newly created Flutter app using the `master` channel:

https://github.com/flutter/flutter/blob/d3829e422b87227847806e64697267a0fc7c5919/packages/flutter_tools/templates/app_shared/windows.tmpl/runner/win32_window.cpp#L216-L218

**Comment by Seawolf159** [comment]
No i hadn't followed those steps. I've followed them now and it upgraded it to `Flutter 3.7.0-13.0.pre.118 • channel master` i created a new test app with it and the result is the same where it won't switch as my windows system theme changes and will only launch the .exe when i change my theme.

![image](https://user-images.githubusercontent.com/38156717/210017008-e3b6d32a-7948-49a5-844f-b5d5076039ad.png)

**Comment by loic-sharma** [comment]
Would you be able to share your full `runner/win32_window.cpp` file?

**Comment by lamtx** [comment]
Can we support that the title bar should respect the theme in app, instead of OS?
Steps to reproduce:
1. Change Windows theme to Dark mode.
2. Provide `ThemeMode.light` to the constructor of MaterialApp (app now uses light theme).

Actual: The title bar is dark.
Expected: The title is light.

**Comment by loic-sharma** [comment]
@lamtx That's out-of-scope for this particular issue, but, yes that's something we want to support in the future. Unfortunately, currently the Flutter framework doesn't support customizing the native window. This is something we'll likely to add as part of the multi-window work, but we don't have ETA on that.
