### ISSUE TITLE
[Icons] Flutter material icon does not match icon on material.io

### ISSUE THREAD

**Issue by kwiesmueller** [flutter/flutter#117607]
## Steps to Reproduce

When using the icon [`Icons.payments`](https://api.flutter.dev/flutter/material/Icons/payments-constant.html) the rendered icon on web and windows (I haven't checked other platforms yet) does not match the icon on the [material icon list](https://fonts.google.com/icons?icon.query=payments&icon.style=Rounded)

**Expected results:** 

Icons in the flutter library should comply with the design on material.io

**Actual results:**

At least one icon is lacking detail visible on the official material site.

![image](https://user-images.githubusercontent.com/20727293/209420783-4939c751-d67a-4560-91d3-b2672ce5d937.png)

**Comment by kwiesmueller** [comment]
Additionally I can't seem to find the icon https://fonts.google.com/icons?icon.query=swords&icon.style=Rounded&icon.platform=web

**Comment by notDmDrl** [comment]
@kwiesmueller, Flutter uses (at least for now) a legacy "Material Icons" icons (on the right of your screenshot).

The ones on the left of your screenshot are "Material Symbols" which are relatively new set of icons (see related issue https://github.com/flutter/flutter/issues/102560).

**Comment by huycozy** [comment]
@kwiesmueller I'm closing this issue in favor of #102560 as @notDmDrl mentioned above. Please follow up on it for further updates. You can leave there your comment and react an upvote to the original comment will help to raise the issue. Thank you!
