### ISSUE TITLE
wrong linked script in CodeLab

### ISSUE THREAD

**Issue by laurac8r** [flutter/flutter#117656]
[lib/main.dart](https://github.com/flutter/codelabs/blob/master/firebase-get-to-know-flutter/step_05/lib/main.dart#L54) should be [lib/home_page.dart](https://github.com/flutter/codelabs/blob/master/firebase-get-to-know-flutter/step_05/lib/home_page.dart#L54) on Step 4 in the [Firebase Get to Know Flutter Codelab](https://firebase.google.com/codelabs/firebase-get-to-know-flutter?hl=en#4) for editing the HomePage widget

**Comment by domesticmouse** [comment]
PTAL @nohe427

**Comment by miquelbeltran** [comment]
This is fixed now. The link in https://firebase.google.com/codelabs/firebase-get-to-know-flutter?hl=en#4 points to https://github.com/flutter/codelabs/blob/master/firebase-get-to-know-flutter/step_05/lib/home_page.dart#L14 as expected
