### ISSUE TITLE
Write test suite for FLX snapshotting

### ISSUE THREAD

**Issue by cbracken** [flutter/flutter#11761]
Once #11616 is reverted back into the framework, the FLX snapshotting code should be refactored to use the same generalised snapshotting class it introduced, which allows for much more testable code. `_createSnapshot` in `lib/src/flx.dart` should be refactored to use that and a comprehensive test suite written.

**Comment by Hixie** [comment]
We should just remove the FLX code entirely.

**Comment by Hixie** [comment]
This will be moot once we do https://github.com/flutter/flutter/issues/9900.

**Comment by cbracken** [comment]
This is actually done now either way (in #11820)
