### ISSUE TITLE
Shared_Preferences Cannot run with sound null safety

### ISSUE THREAD

**Issue by NewsunBanjade** [flutter/flutter#117620]
geting this issue white using Shared_preferences on flutter.

```
ERROR: Error: Cannot run with sound null safety, because the following dependencies
ERROR: don't support null safety:
ERROR:  - package:shared_preferences
ERROR:  - package:shared_preferences_platform_interface
ERROR: For solutions, see https://dart.dev/go/unsound-null-safety
```

**Comment by huycozy** [comment]
@NewsunBanjade What is your plugin version? The latest version is `shared_preferences: ^2.0.15`, please retry on the latest version to see if the issue still persists or not.

**Comment by NewsunBanjade** [comment]
I used directly add dependencies which added older version of Shared_Preferences. If anyone with same make sure you have latest version of shared_preferences
