### ISSUE TITLE
#77161 (comment)

### ISSUE THREAD

**Issue by hacker20028** [flutter/flutter#117614]
#77161 (comment) 
I watched but now it makes another error-

``` 
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:packageDebug'.
> A failure occurred while executing com.android.build.gradle.tasks.PackageAndroidArtifact$IncrementalSplitterRunnable
   > java.io.IOException: Failed to generate v1 signature

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3m 9s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

```

_Originally posted by @rupamking1 in https://github.com/flutter/flutter/issues/91312#issuecomment-935744869_

**Comment by hacker20028** [comment]
> ```
>     #77161 (comment) 
> ```
> 
> I watched but now it makes another error-
> 
> ```
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':app:packageDebug'.
> > A failure occurred while executing com.android.build.gradle.tasks.PackageAndroidArtifact$IncrementalSplitterRunnable
>    > java.io.IOException: Failed to generate v1 signature
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 3m 9s
> Exception: Gradle task assembleDebug failed with exit code 1
> Exited (sigterm)
> ```
> 
> _Originally posted by @rupamking1 in [#91312 (comment)](https://github.com/flutter/flutter/issues/91312#issuecomment-935744869)_

I am Getting the same error, can someone help me out?

**Comment by huycozy** [comment]
@hacker20028 
To be more precise, please provide the information indicated below:
- A [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) 
- The output of `flutter doctor -v` and `flutter run -v` (If the log is too long, please save it into a file and attach it here)
- Reproduction steps

Thank you!

**Comment by hacker20028** [comment]
Thanks. I actually re-installed everything again and it worked for me.
