### ISSUE TITLE
Way there is no google reCaptcha package for Flutter apps?

### ISSUE THREAD

**Issue by JosephKalash** [flutter/flutter#117677]
I am looking for google recaptcha v2 package with checkbox to implement in my flutter app but there is no single one that offer this feature?? There is already in Android and IOS. is there reason Flutter doesn't have one?

I found several ones but either outdated or not work as expected

**Comment by huycozy** [comment]
Thanks for the report! There are some known issues being tracked at #34742 and #78616. Closing this issue as a duplicate, so please follow up on these issues for further updates.
