### ISSUE TITLE
FractionallySizedBox alignment parameter can be confusing

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#11769]
[FractionallySizedBox](https://api.flutter.dev/flutter/widgets/FractionallySizedBox-class.html) can be confusing when used as the body of a Scaffold, i.e. when its size is not constrained.

In this example the Container child is NOT centered in the Scaffold body, despite the `alignment: FractionalOffset.center` specification.

```dart
new Scaffold(
  appBar: new AppBar(title: const Text('FSB')),
  body: new FractionallySizedBox(
    widthFactor: 0.5,
    heightFactor: 0.5,
    alignment: FractionalOffset.center,
    child: new Container(
      decoration: new BoxDecoration(
        border: new Border.all(
          color: Colors.blue,
          width: 4.0,
        ),
      ),
    ),
  ),
)
```

That's because the size of the FractionallySizedBox parent is otherwise unconstrained, and so it ends up being the same size as its (scaled) child.

Constraining the size of the FractionallySizedBox fixes the problem:

```dart
new Scaffold(
  appBar: new AppBar(title: const Text('FSB')),
  body: new SizedBox.expand(
    child: new FractionallySizedBox(
      widthFactor: 0.5,
      heightFactor: 0.5,
      alignment: FractionalOffset.center,
      child: new Container(
        decoration: new BoxDecoration(
          border: new Border.all(
            color: Colors.blue,
            width: 4.0,
          ),
        ),
      ),
    ),
  ),
)
```

**Comment by Thesmader** [comment]
Can I work on this issue?
