### ISSUE TITLE
[camera] Ability to manipulate Video Recording by overlaying `Widgets` on to the `ImageStream`

### ISSUE THREAD

**Issue by aytunch** [flutter/flutter#117638]
## Use case

I am using `startImageStream` and doing Mlkit manipulations and am able to show Widgets above the `CameraPreview` widget in a Stack. I want to somehow bake these overlayed widget pixels in to the recording itself. Is this possible to do in real time? Do native platform implementations support this usecase or should it be done through low level texture manipulations(in the pixel level)?
Also even if it is possible, would it be able to record a video in realtime?
also I know that `ImageStream` do not give us all the frames that end up in the video file. I think it works in a best effort manner. Would this be a shortcoming?

## Proposal

allow manipulating certain pixels of each video frame
bake a second alpha channel widget frame in to the existing video frame (like a `Stack`)

**Comment by huycozy** [comment]
Thanks for the report! This is a known issue being tracked at #18968. Closing this issue as a duplicate, so please follow up on it for further updates.
