### ISSUE TITLE
Flutter go_router Match error found during build

### ISSUE THREAD

**Issue by sergiyvergun** [flutter/flutter#117644]
I'm receiving this error every time I try to open the dynamic link

![image](https://user-images.githubusercontent.com/30001806/209495422-1cfe964f-e09d-44a2-8109-1a76b3364c28.png)

But the error is only on IOS, in Android everything works perfectly. 

This is how it navigates to the needed page from the dynamic link:

```
Navigator.push(
    context,
    MaterialPageRoute(builder: (context) => FlashcardDetailedPage(
                    flashcard: flashcard,
                    deck: deck,
                    toDownload: true,
                  )),
  );
```
How to fix this?

**Comment by huycozy** [comment]
@sergiyvergun Which `go_router` version are you using? 

Please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this. Also, please provide the output of `flutter doctor -v` as well. Thank you!
