### ISSUE TITLE
Create Android integration tests

### ISSUE THREAD

**Issue by xster** [flutter/flutter#11763]
Test native behaviours like text input and native view transitions via an integration test such as Espresso

**Comment by collinjackson** [comment]
Integration testing is also relevant for plugins; right now the native code in flutter/plugins has no test coverage. It would help catch regressions and increase the pace of development on plugins (especially FlutterFire) if there was a way to test the Android and Flutter code working together.

/cc @kroikie @sethladd

**Comment by cbracken** [comment]
@mklim has resolved this issue.

**Comment by xster** [comment]
Espresso can't verify Flutter trees in the open source release yet can it?
