### ISSUE TITLE
[in_app_purchase] iOS simulator continually asks for Apple ID Sign-In when attempting to restorePurchase

### ISSUE THREAD

**Issue by sneglia9191** [flutter/flutter#117738]
Hello, I understand the IOS in-app purchases are not supported on simulator devices, however, when calling restorePurchases on IOS, I receive a dialog box asking for Apple ID sign-in:

<img width="435" alt="image" src="https://user-images.githubusercontent.com/118394743/209832187-f06b6aa8-affd-4ae2-9855-e5d342bd1629.png">

This is the same defect as https://github.com/flutter/flutter/issues/94269 which was resolved by migrating to RevenueCat (so not really resolved)

I have tried my developer AppleID, as well as my Sandbox ID, and both are rejected.  The error I get is:

![image](https://user-images.githubusercontent.com/118394743/209832804-2d0184b3-6cfc-4de9-ab2a-c81488484269.png)

I have had to code around the call on IOS (by eliminating the call to restorePurchase), so clearly not an ideal solution.

## Steps to Reproduce

Simply create an app with in-app billing and execute on an IOS simulator.  Code to call restorePurchase something similar:

```
void restorePurchase(Function restorePurchaseResponseCallback) {
    //store the function to return purchase flow response
    _purchaseFlowResponseCallback = restorePurchaseResponseCallback;

    //this is a restore event, not a purchase
    _isPurchaseAttempt = false;

    _iap?.restorePurchases();
  }
```

The sign-in occurs on the _iap?.restorePurchase(), and the _purchaseFlowResponseCallback is never executed.

##flutter doctor -v
[✓] Flutter (Channel stable, 3.3.9, on macOS 13.1 22C65 darwin-arm, locale en-GB)
    • Flutter version 3.3.9 on channel stable at /Users/sneglia/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b8f7f1f986 (5 weeks ago), 2022-11-23 06:43:51 +0900
    • Engine revision 8f2221fbef
    • Dart version 2.18.5
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/sneglia/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] Connected device (4 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554                        • android-arm64 • Android 13 (API 33) (emulator)
    • iPhone 11 Pro (mobile)      • E8FE561B-A0EE-446D-AC1B-6D734CDAAF3F • ios           • com.apple.CoreSimulator.SimRuntime.iOS-13-7 (simulator)
    • iPhone 14 Pro (mobile)      • B5A738C6-7667-45B4-BFC3-23A6E4EA27AC • ios           • com.apple.CoreSimulator.SimRuntime.iOS-16-2 (simulator)
    • macOS (desktop)             • macos                                • darwin-arm64  • macOS 13.1 22C65 darwin-arm

[✓] HTTP Host Availability
    • All required HTTP hosts are available

**Comment by darshankawar** [comment]
@sneglia9191 
There's similar open issue describing your case, https://github.com/flutter/flutter/issues/82398, so please follow-up in it for further updates. Closing this as a duplicate.



> This is the same defect as #94269 which was resolved by migrating to RevenueCat (so not really resolved)

That was also same as the original issue I linked above in a nutshell.

**Comment by giorgio79** [comment]
Darshan why are you linking to a closed and unresolved issue? :)
