### ISSUE TITLE
TabBar ignoring the Theme's dividerColor value

### ISSUE THREAD

**Issue by williamhjcho** [flutter/flutter#117706]
## Steps to Reproduce

I'm currently on the beta channel `3.7.0-1.2.pre`

Looks like the issue is located here
https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/tabs.dart#L1071

<details>

```dart
// inserted to the MaterialApp
ThemeData(
  // ...
  tabBarTheme: TabBarTheme(
    // ...
    dividerColor: Colors.pink, // this will be ignored by the TabBar widget
  ),
);
```

</details>

**Comment by darshankawar** [comment]
Thanks for the report @williamhjcho 
There's a [draft PR](https://github.com/flutter/flutter/pull/116347) to remove the `dividerColor` from `themeData`, so once that is implemented as part of M3, we will probably get a new implementation for it as mentioned in the PR description, so I suggest you to subscribe to that PR and once new implementation is available to use, try to use that and see if it helps to resolve the issue you are reporting. What do you think ?

**Comment by williamhjcho** [comment]
Looks great!

I can get around this by just passing the `TabBar`'s instance `dividerColor` with my custom color, 
just wanted to check if this was something worth mentioning or being aware of.

Thanks for the info!
Feel free to close the issue if you don't think it's relevant anymore.

**Comment by darshankawar** [comment]
Thanks for the feedback. I'll close it for now. If anything, write in comments and I'll reopen it for tracking.
