### ISSUE TITLE
Port forwarding not working with Flutter web

### ISSUE THREAD

**Issue by AndryHTC** [flutter/flutter#117776]
I've tried different times to forward ports for pair programming with my teammate. Everything always worked flawlessly with GraphQL, Serverpod, Flutter DevTools and other services...
But the port that runs the Flutter App is the only one that never work on the remote PC, and that shows in the browser a `ERR_EMPTY_RESPONSE`.

I tried with different OSs, networks and machines but the Flutter app is the only one that never works. It's curious because even in the local PC, the only way that port works is through the shortand `localhost:[port]`, because if I try `127.0.0.1:[port]` it gives me the same error that gives to the remote PC `ERR_EMPTY_RESPONSE`. In the remote PC both `localhost:[port]` and `127.0.0.1:[port]` give `ERR_EMPTY_RESPONSE`

## Steps to Reproduce

1. Execute `flutter run -d chrome --web-port 8090`

**Expected results:** The port should work like all the others I already forward. And in the local machine should work even without the `localhost` shorthand but also with `127.0.0.1`

**Actual results:** In the remote PC where I forward my ports to, Chrome retrieves `ERR_EMPTY_RESPONSE`. And in the local machine with `127.0.0.1:8090` Chrome retrieves `ERR_EMPTY_RESPONSE`. The only way to let it work is connecting to  `localhost:8090` but ONLY in the local machine: ![image](https://user-images.githubusercontent.com/29896004/209940512-1d04f4b9-ccd9-44ba-ba87-a1771203135d.png)

**Comment by exaby73** [comment]
Hello @AndryHTC. Have you tried using your private IP instead of `127.0.0.1`?

**Comment by AndryHTC** [comment]
> Hello @AndryHTC. Have you tried using your private IP instead of `127.0.0.1`?

Yes, retrieves `ERR_EMPTY_RESPONSE` too

**Comment by exaby73** [comment]
How are you port forwarding? Through your router or tunneling?

**Comment by AndryHTC** [comment]
> How are you port forwarding? Through your router or tunnelling?

@exaby73 I'm just using the default **JetBrains CodeWithMe**'s port forwarding, I don't know the underlying functioning (and I do the same with VS Code...)

If with tunnelling you mean through an established VPN, no... We just use a normal connection with the router

**Comment by exaby73** [comment]
From [this answer in Stackoverflow](https://stackoverflow.com/questions/62195515/access-flutter-localhost-from-real-mobile-browser):

> The flutter run command launches the application using the [development compiler](https://dart.dev/tools/dartdevc) in a Chrome browser, which means that Dart code runs directly in Chrome. And you cannot really access Chrome from another machine in the network, as it doesn't act as a server.

I recommend compiling the app and hosting it using a simple web server like Python's http module. You can do that using:

```bash
flutter build web
python -m http.server --directrory build/web
```

This seems to be working as expected. Alternatively, you can try this command `flutter run -d web-server --web-port 8090`. Not sure if this will work differently than `-d chrome` but worth a shot

**Comment by AndryHTC** [comment]
@exaby73 you're very kind, I will try!

**Comment by exaby73** [comment]
Since this is working as expected, I am closing this issue. If you feel that I have made a mistake and disagree with my decision, please comment with your reasoning and I can reopen the issue. Thank you
