### ISSUE TITLE
`BorderRadius.circular` should be a const constructor

### ISSUE THREAD

**Issue by eyebrowsoffire** [flutter/flutter#117798]
I noticed the `BorderRadius.circular` constructor is not marked as const. Unless I'm missing something, it seems to me it could easily made const.

**Comment by MrBirb** [comment]
You can’t. See #91971

**Comment by exaby73** [comment]
Based on https://github.com/flutter/flutter/issues/91971, I am closing this issue as a duplicate. If you disagree, please comment and I can reopen the issue. Thank you
