### ISSUE TITLE
Inactive (onTap: null) ListTile keeps hover state until mouse out

### ISSUE THREAD

**Issue by gialdeyn** [flutter/flutter#117733]
https://user-images.githubusercontent.com/6051015/209817347-5831c484-56aa-4f5a-bdfd-cce2e86f7539.mov

## Steps to Reproduce
(I tried in web)
1. Execute `flutter run` on the code sample
2. Click on unselected item (and keep mouse cursor on it)

**Expected results:**
The ListTile immediately becomes inactive. Without any hover state and with its default background.

**Actual results:** 
The ListTile keeps some kind of hover state (with different background color) until mouse cursor leaves it.

By the way, mouse cursor type depends on active/inactive state of the ListTile and switches correctly.

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatefulWidget {
  const MyApp({super.key});

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  int selectedIndex = 0;

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: ListView(
          children: ['Title 1', 'Title 2']
              .asMap()
              .entries
              .map((entry) => ListTile(
                    title: Text(entry.value),
                    subtitle: Text(
                        entry.key == selectedIndex ? 'is selected' : 'sub'),
                    onTap: entry.key == selectedIndex
                        ? null
                        : () {
                            setState(() {
                              selectedIndex = entry.key;
                            });
                          },
                  ))
              .toList(),
        ),
      ),
    );
  }
}
```

</details>

**Comment by darshankawar** [comment]
Thanks for the report @gialdeyn 
I tried the code sample using latest master on web, but didn't observe the reported behavior.


https://user-images.githubusercontent.com/67046386/209909983-10c939dd-8927-4275-bb46-a0312a9aff7a.mov

Can you provide your `flutter doctor -v` and also confirm if this is only happening with mouse or with trackpad cursor as well ?

**Comment by gialdeyn** [comment]
> but didn't observe the reported behavior

No-no, look, you _have_ the same behavior in your video.
After click cursor type changes (because ListItem becomes inactive), but background is still gray, like it is hover state.
But after mouse out and in again there is no gray background.

**Comment by darshankawar** [comment]
Thanks for the update. Keeping this issue open for team's insights.

**Comment by ditman** [comment]
Is this reproducible in other platforms? This looks like a framework issue that should reproduce in other platforms too.

cc/ @dkwingsmt for extra insight.

**Comment by bleroux** [comment]
This is reproducible on desktop too.

**Comment by ditman** [comment]
Thanks for verifying and working on this @bleroux, I'm removing the `platform-web` label since this is not exclusively a web issue. We can add it back if there's any web-specific fixes needed!
