### ISSUE TITLE
RefreshIndicator triggers "onTap" on List items InkWell

### ISSUE THREAD

**Issue by tdittmar** [flutter/flutter#117752]
If you wrap the items of a list in an `InkWell` and the list itself is wrapped in a `RefreshIndicator`, using pull-to-refresh will trigger the `InkWell`'s `onTap` event when releasing to refresh.

## Steps to Reproduce

1. Create a `Scaffold`
2. Add a `RefreshIndicator` as its body
3. Add a `CustomScrollView` as the `RefreshIndicator`'s child
4. Add a `SliverList` to the `CustomScrollView`
5. Make each item tappable by adding an `InkWell` on each item. Make the `onTap` event print the text "TAPPED".
6. Implement an `_updateList()` method to be called by the `RefreshIndicator` upon pull-to-refresh

**Expected results:** `_updateList()` should be called and the list should update.

**Actual results:**  `_updateList()` is being called, but ALSO the text "TAPPED" is printed. If you replace the `print` statement with some route navigation, the navigation will take place instead of simply refreshing the list.

<details>
<summary>Code sample</summary>

```dart
return Scaffold(
  body: RefreshIndicator(
    child: CustomScrollView(
      slivers: [
        SliverList(
          delegate: SliverChildBuilderDelegate(
            (BuildContext context, int index) {
              final item = listData.elementAt(index);
              return InkWell(
                onTap: () { print("Tapped"); },
                child: SpecializedListItemWidget(forItem: item),
              );
            },
            childCount: listData.length,
          ),
        )
      ],
    ),
    onRefresh: () async => await _updateList(),
  ),
);
```

</details>

**Comment by huycozy** [comment]
Hi @tdittmar, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this. Also, please provide the output of `flutter doctor -v` as well. Thank you!

**Comment by tdittmar** [comment]
## Minimal code sample
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});
  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final listData = ["Entry 1", "Entry 2", "Entry 3"];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: RefreshIndicator(
        child: CustomScrollView(
          slivers: [
            SliverList(
              delegate: SliverChildBuilderDelegate(
                (BuildContext context, int index) {
                  final item = listData[index];
                  return InkWell(
                    onTap: () {
                      print("Tapped");
                    },
                    child: Container(
                        padding: const EdgeInsets.symmetric(
                          horizontal: 16,
                          vertical: 32,
                        ),
                        child: Text(item)),
                  );
                },
                childCount: listData.length,
              ),
            )
          ],
        ),
        onRefresh: () async => await _updateList(),
      ),
    );
  }

  Future<void> _updateList() async {
    print("Updated");
  }
}
```

## Output of `flutter doctor -v`

[✓] Flutter (Channel stable, 3.3.10, on macOS 13.0.1 22A400 darwin-x64, locale de-DE)
    • Flutter version 3.3.10 on channel stable at /Users/tdittmar/Projects/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (2 weeks ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/tdittmar/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.74.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.56.0

[✓] Connected device (3 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 13 (API 33) (emulator)
    • macOS (desktop)              • macos         • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 108.0.5359.124

[✓] HTTP Host Availability
    • All required HTTP hosts are available

**Comment by huycozy** [comment]
@tdittmar I was trying on the latest `stable` and `master` channels but can not see this issue (please see below demo). Two cases are working as expected. I'm verifying on `Realme 6, Android 11`. 

<details>
<summary>Demo</summary>


https://user-images.githubusercontent.com/104349824/210038328-30c2b827-7bc8-40ad-a851-8270126d0a5e.mov


</details>

Which device are you facing this issue with?
