### ISSUE TITLE
Flutter SigningConfig "release" is missing required property "storeFile"

### ISSUE THREAD

**Issue by alfietapping** [flutter/flutter#117789]
Have faced this issue multiple times now trying to build APK/App bundle with Flutter, can anyone tell what the issue is? It's saying my key.properties file is missing the store file, however it's definitely there and is 100% the correct path, looks to be either a bug in the error reporting from Flutter or the official [guide](https://docs.flutter.dev/deployment/android) is incorrect in it's setup

My build gradle:

```
def keystoreProperties = new Properties()
def keystorePropertiesFile = rootProject.file('key.properties')
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}
```

 ```
 signingConfigs {
    release {
        keyAlias keystoreProperties['keyAlias']
        keyPassword keystoreProperties['keyPassword']
        storeFile keystoreProperties['storeFile'] ? file(keystoreProperties['storeFile']) : null
        storePassword keystoreProperties['storePassword']
    }
}
buildTypes {
    release {
        signingConfig signingConfigs.release
    }
}
```

My key.properties file(this is at the android folder of the flutter project):

```
storePassword=******
keyPassword=******
keyAlias=*****
storeFile=/Users/user/keystore/my_app/*****.jks
```

**Comment by jayjah** [comment]
Your `key.properties` file should not be in the flutter root directory! Instead it should be in the android directory of your flutter project.

**Comment by alfietapping** [comment]
That code is copy & pasted from the official Flutter guide on releasing an android APK, are you saying they are wrong?

**Comment by alfietapping** [comment]
> Your `key.properties` file should not be in the flutter root directory! Instead it should be in the android directory of your flutter project.

Typo error, it's in the android folder
