### ISSUE TITLE
Target of URI hasn't been generated: ''goods.g.dart''. Try running the generator that will generate the file referenced by the URI.

### ISSUE THREAD

**Issue by maralerdene** [flutter/flutter#117724]
I want to try hive implementation. But when i add part 'goods.g.dart' it's return below error. 

_Target of URI hasn't been generated: ''goods.g.dart''. Try running the generator that will generate the file referenced by the URI._

Here is my code: 
```

import 'package:hive/hive.dart';

part 'goods.g.dart';

@HiveType(typeId: 0)
class Goods extends HiveObject {
  @HiveField(0)
  final String? title;
  @HiveField(1)
  final String? type;
  @HiveField(2)
  final int? episodes;
  @HiveField(3)
  final String? status;
  @HiveField(4)
  final String? startDate;
  @HiveField(5)
  final String? endDate;
  @HiveField(6)
  final String? startingSeason;
  @HiveField(7)
  final String? broadcastTime;

  Goods({
    this.title,
    this.type,
    this.episodes,
    this.status,
    this.startDate,
    this.endDate,
    this.startingSeason,
    this.broadcastTime,
  });
}

```

Here is my pubspec.yml

d```
ependencies:
  flutter:
    sdk: flutter

  get: ^4.6.5
  dio: ^4.0.6
  geocoding: ^2.0.5
  flutter_svg: ^1.1.5
  grouped_list: ^5.1.2
  image_picker: ^0.8.6
  carousel_slider: ^4.1.1
  cupertino_icons: ^1.0.2
  dotted_border: ^2.0.0+2
  connectivity_plus: ^3.0.2
  google_maps_flutter: ^2.2.1
  cached_network_image: ^3.2.2
  firebase_auth: ^4.1.2
  firebase_core: ^2.2.0
  cloud_firestore: ^4.2.0
  firebase_messaging: ^14.1.2
  firebase_dynamic_links: ^5.0.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  mime: ^1.0.2
  intl: ^0.17.0
  timeago: ^3.3.0
  share_plus: ^6.3.0
  flutter_typeahead: ^4.1.1
  pin_code_text_field: ^1.8.0
  geolocator: ^9.0.2
  otp_autofill: ^2.1.0
  firebase_storage: ^11.0.7
  provider: ^6.0.4
  flutter_local_notifications: ^13.0.0
  fluttertoast: ^8.1.2
  bubble: ^1.1.9+1
  flutter_native_image: ^0.0.6+1
  build_runner: ^2.3.3
  json_serializable: ^6.5.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  # Platform  Firebase App Id
  # android   1:791661109069:android:60177c57d69557add12104
  # ios       1:791661109069:ios:df96bddec0f30a40d12104

  flutter_lints: ^2.0.0
```

Please, how to fix it?

**Comment by darshankawar** [comment]
@maralerdene 
You will probably need to report this in hive plugin's [repo](https://github.com/hivedb/hive/issues) or ask this question on support channels like StackOverflow.
Closing from here.
