### ISSUE TITLE
Implement RenderStatisticsBox.alwaysNeedsCompositing

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#1177]
(derived from a review comment by @abarth on https://github.com/flutter/flutter/pull/1166)

Currently `RenderStatisticsBox` lies because it creates a layer but doesn't have the compositing bits set to say that it creates a layer. We should either set `hasLayer` to true, or explicitly set it to false with a comment explaining why.

The risk is that turning on the performance overlay can change the compositing strategy for the app. If you leave it off, but put the overlay deep in your tree, you can end up breaking things like opacity that are higher up the tree.

In practice you almost always put it at the top of the tree.

**Comment by abarth** [comment]
We should use the new alwaysNeedsCompositing here

**Comment by abarth** [comment]
This is a one-line fix now, but should probably wait until https://github.com/flutter/flutter/pull/1181/files lands.
