### ISSUE TITLE
[image_picker] App crashes when trying to pick an image with imageQuality option in 0.8.6 version or 0.8.5+3 

### ISSUE THREAD

**Issue by ngockhanhbl** [flutter/flutter#117718]
if i pass imageQuality app crash after pick image. when i remove imageQuality params option it work ok.

**Comment by huycozy** [comment]
@ngockhanhbl Thanks for the report! This is a known issue being tracked at #117670. Closing this issue as a duplicate, so please follow up on it for further updates.
