### ISSUE TITLE
Google sign-in plugin gives crash on firebase crashlytics

### ISSUE THREAD

**Issue by neeluagrawal04** [flutter/flutter#117773]
google_sign_in: ^5.3.0 (version using in app)
  Crash logged on firebase crashlytics
Fatal Exception: FlutterError
PlatformException(sign_in_failed, org.openid.appauth.general, ID Token expired, null). Error thrown null.

Fatal Exception: FlutterError
0  ???                            0x0 StandardMethodCodec.decodeEnvelope + 653 (message_codecs.dart:653)
1  ???                            0x0 MethodChannel._invokeMethod + 296 (platform_channel.dart:296)
2  ???                            0x0 MethodChannel.invokeMapMethod + 499 (platform_channel.dart:499)
3  ???                            0x0 GoogleSignIn._callMethod + 273 (google_sign_in.dart:273)
4  ???                            0x0 GoogleSignIn.signIn.isCanceled + 407 (google_sign_in.dart:407)

**Comment by exaby73** [comment]
Hello @neeluagrawal04. Is this the complete logs from crashlytics or is this it? Try formatting the logs using [code blocks](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks)

**Comment by neeluagrawal04** [comment]
yes @exaby73

**Comment by exaby73** [comment]
There are some similar issues already:

- https://github.com/flutter/flutter/issues/75224
- https://github.com/flutter/flutter/issues/33393

Please follow up on those issues. I will close this issue as a duplicate. If you disagree, please comment and I can reopen it. Thank you

**Comment by neeluagrawal04** [comment]
Hello @exaby73 the issues mentioned are different and the crash that i did logged is different. Please reopen this issue.

**Comment by exaby73** [comment]
Have you tried the steps highlighted [here](https://stackoverflow.com/questions/56188338/platformexception-platformexceptionsign-in-failed-com-google-android-gms-comm)?
