### ISSUE TITLE
Documentation indicates inaccurate next step

### ISSUE THREAD

**Issue by sebastiennoir** [flutter/flutter#117727]
The documentation [here](https://codelabs.developers.google.com/codelabs/first-flutter-app-pt2/#8) promotes _creating a simple chat application_ as a possible next steps. The link provided is to _[Take your Flutter app from boring to beautiful](https://codelabs.developers.google.com/codelabs/flutter-boring-to-beautiful)_. This codelab is not a chat application, but some music player instead.

**Comment by domesticmouse** [comment]
FYI @khanhnwin

**Comment by domesticmouse** [comment]
The codelab that contained the content that this issue is about has been deprecated and replaced with one that doesn't reference a non existant chat app codelab.
