### ISSUE TITLE
Supports load system fonts

### ISSUE THREAD

**Issue by cuishijie1991** [flutter/flutter#117811]
<img width="646" alt="截屏2022-12-30 下午4 45 35" src="https://user-images.githubusercontent.com/17976216/210051693-1aa142f1-4ef7-4264-8f84-d47eaacfc106.png">

PC system comes with a wealth of fonts. Is there a way to load and use them in your application just like the picture above?

**Comment by exaby73** [comment]
Hello @cuishijie1991. This is not something Flutter can provide. This is up to the developer to implement. For example, in windows, you can find all system installed fonts in `C:\Windows\Fonts`. Since this is not related to Flutter, I am closing this issue. Thank you
