### ISSUE TITLE
Difference between Dividers.

### ISSUE THREAD

**Issue by aliaktas-tr** [flutter/flutter#117877]
There is something wrong between Divider and VerticalDivider.

color and thickness is not working same.

Exampla Code:

>Column(
  children:[
  SizedBox(
        height: 250,
         child: VerticalDivider(color: Colors.blue))),
       SizedBox(width:150,child: Divider(color: Colors.blue, thickness: `0.3))])`
![divider](https://user-images.githubusercontent.com/51866588/210254598-7f241a71-814f-4fb3-bad5-ab8420379423.PNG)
``

**Comment by IsmailAbdirahman** [comment]
I just checked and they working fine. Check your flutter version if you are using stable version or not. 

`class DividerExample extends StatelessWidget {
  const DividerExample({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: Column(children: const [
      SizedBox(
          height: 250,
          child: VerticalDivider(
            color: Colors.red,
            thickness: 2,
          )),
      SizedBox(width: 150, child: Divider(color: Colors.red, thickness: 2))
    ]));
  }
}`

**Comment by IsmailAbdirahman** [comment]
I just checked and they working fine. Check your flutter version if you are using stable version or not. 


````
```
       class DividerExample extends StatelessWidget {
  const DividerExample({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: Column(children: const [
      SizedBox(
          height: 250,
          child: VerticalDivider(
            color: Colors.red,
            thickness: 2,
          )),
      SizedBox(width: 150, child: Divider(color: Colors.red, thickness: 2))
    ]));
  }
}

```
````

**Comment by huycozy** [comment]
@aliaktas-tr Which Flutter version are you using? Please try on the latest version (stable `3.3.10` and master `3.7.0`) with @IsmailAbdirahman's sample code as suggested above.
