### ISSUE TITLE
change fill color when focusing

### ISSUE THREAD

**Issue by mahdiqdi** [flutter/flutter#117852]
is it possible to change fill color when user focus an input?textfield changes its border when focusing but fill color doesnt change.
i searched a lot and only way was using setstate to rerender the textfield but it makes a real disaster when having a lot of inputs.
please help me to solve my problem

**Comment by znromonk** [comment]
In the docs for the `TextField`'s `InputDecoration`, it states

> This [focusColor](https://api.flutter.dev/flutter/material/InputDecoration/focusColor.html) is ignored by [TextField](https://api.flutter.dev/flutter/material/TextField-class.html) and [TextFormField](https://api.flutter.dev/flutter/material/TextFormField-class.html) because they don't respond to focus changes by changing their decorator's container color, they respond by changing their border to the [focusedBorder](https://api.flutter.dev/flutter/material/InputDecoration/focusedBorder.html), which you can change the color of.

If you want to change the fill color of a `TextField`, you might have to use `FocusNode`. If you do not want to call setState on every focus, you could use the `ValueNotifier` along with `ValueListenableBuilder`. You can create a custom widget and pass along any `TextField` properties. 

<details>
<summary> Sample Code</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: Container(
          height: 150,
          padding: const EdgeInsets.all(10),
          child: Column(
            mainAxisAlignment: MainAxisAlignment.spaceAround,
            children: [
              SizedBox(
                width: 300,
                child: MyTextWidget(
                  onChanged: (s1) {
                    print(s1);
                  },
                ),
              ),
              SizedBox(
                width: 300,
                child: MyTextWidget(
                  onChanged: (s2) {
                    print(s2);
                  },
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}

class MyTextWidget extends StatefulWidget {
  const MyTextWidget({
    super.key,
    this.onChanged,
    this.fillColor = const Color.fromRGBO(250, 250, 250, 1),
    this.focusColor = const Color.fromRGBO(240, 240, 240, 1),
  });
  final ValueChanged<String>? onChanged;
  final Color? fillColor;
  final Color? focusColor;

  @override
  State<MyTextWidget> createState() => _MyTextWidgetState();
}

class _MyTextWidgetState extends State<MyTextWidget> {
  late FocusNode _myFocusNode;
  final ValueNotifier<bool> _myFocusNotifier = ValueNotifier<bool>(false);

  @override
  void initState() {
    super.initState();

    _myFocusNode = FocusNode();
    _myFocusNode.addListener(_onFocusChange);
  }

  @override
  void dispose() {
    _myFocusNode.removeListener(_onFocusChange);
    _myFocusNode.dispose();
    _myFocusNotifier.dispose();

    super.dispose();
  }

  void _onFocusChange() {
    _myFocusNotifier.value = _myFocusNode.hasFocus;
  }

  @override
  Widget build(BuildContext context) {
    return ValueListenableBuilder(
      valueListenable: _myFocusNotifier,
      builder: (_, isFocus, child) {
        return TextField(
          focusNode: _myFocusNode,
          decoration: InputDecoration(
            filled: true,
            fillColor: isFocus ? widget.focusColor : widget.fillColor,
          ),
          onChanged: (value) => widget.onChanged,
        );
      },
    );
  }
}
```
</details>

**Comment by danagbemava-nc** [comment]
Hi @mahdiqdi, does the solution in https://github.com/flutter/flutter/issues/117852#issuecomment-1368611791 suit your use case?

**Comment by mahdiqdi** [comment]
hi there.thanks guys.this sample code suit my usecase.but what about error.we have error border but how to change that color too.i reallty appreciate you guys
@znromonk @danagbemava-nc

**Comment by znromonk** [comment]
@mahdiqdi 

You need to supply the parameters for error in `InputDecoration`. All of them are listed in [docs](https://api.flutter.dev/flutter/material/InputDecoration-class.html).

```dart
errorText: 'some error',
errorBorder: UnderlineInputBorder(
  borderSide: BorderSide(
    color: Colors.orange,
  ),
),
```

The error border will only show if `errorText` is not null.

**Comment by mahdiqdi** [comment]
no no.error color in background like focus color.(fill error color i mean)

**Comment by znromonk** [comment]
Then just change the color value accordingly. When you specify the color to fill, check if there is an error and show the appropriate color.

```dart
bool _error = false;
// check for error and change the boolean
..
// TextField widget
fillColor: _error ? Colors.red.shade100 : Colors.grey.shade100
// rest of TextField
```

**Comment by mahdiqdi** [comment]
thanks.i will use your suggestions.it was so helpful.thank you

**Comment by danagbemava-nc** [comment]
Closing this as solved. 

Thank you
