### ISSUE TITLE
[image_picker] Pick Image Method Alllows User To Pick Multi Images

### ISSUE THREAD

**Issue by oorfalimak** [flutter/flutter#117816]
Hello, 
I use these lines to pick an image from gallery:
`final ImagePicker _picker = ImagePicker();`
`final XFile? image = await _picker.pickImage(source: ImageSource.gallery);`

But in some iOS devices it works like "pickMultiImage". This means, it and allow users to select more than 1 image from gallery, and it causes a crash on return.
How can i fix this?

**Comment by exaby73** [comment]
Hello @oorfalimak. Thank you for filing this issue. Can you please provide the following information?

- A [complete and minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). Ideally, a single `main.dart` file that can be run directly.
- Plugin and OS version information
- The output of `flutter doctor -v`
- The output of `flutter run -v`

Please provide the information in the form of text. See how to make collapsible sections with Markdown [here](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-collapsed-sections).

**Comment by oorfalimak** [comment]
Thanks for the reply.  

<details><summary>The code is:</summary>
<p>

```dart
  XFile? image;
  final ImagePicker _picker = ImagePicker();
  image = await _picker.pickImage(
        source: ImageSource.camera,
        imageQuality: 90,
        maxHeight: 1024,
        maxWidth: 1024,
      );
```
</p>
</details>

<details><summary>Flutter doctor output:</summary>
<p>
[✓] Flutter (Channel stable, 3.3.10, on macOS 13.0.1 22A400 darwin-x64, locale en-TR)
    • Flutter version 3.3.10 on channel stable at /Users/ozanorfa/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (2 weeks ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc5)
    • Android SDK at /Users/ozanorfa/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0-rc5
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Community Edition (version 2022.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.74.2)
    • VS Code at /Users/ozanorfa/Desktop/Visual Studio Code.app/Contents
    • Flutter extension version 3.56.0

[✓] Connected device (3 available)
    • SM A235F (mobile) • R68TB01G4HT • android-arm64  • Android 13 (API 33)
    • macOS (desktop)   • macos       • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 108.0.5359.124

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
</p>
</details>

<details><summary>The run code outout:</summary>
<p>

Launching lib/main.dart on SM A235F in debug mode...
lib/main.dart:1
✓  Built build/app/outputs/flutter-apk/app-prod-debug.apk.
D/FlutterLocationService(14368): Creating service.
D/FlutterLocationService(14368): Binding to location service.
I/app(14368): Compiler allocated 6075KB to compile void android.view.ViewRootImpl.performTraversals()
Connecting to VM Service at ws://127.0.0.1:62256/94y0CEFLkxQ=/ws
</p>
</details>

Best regards.

**Comment by exaby73** [comment]
Please provide a complete code sample that can be run directly, including `main()`
