### ISSUE TITLE
Inside pageview flutter_gallery_3d not scrolling

### ISSUE THREAD

**Issue by sahiram036** [flutter/flutter#117813]
I am using your package inside a pageview and facing a issue is that flutter_gallery_3d view is not scrolling anymore
When I tried to scroll it, then main pageview is navigating but flutter_gallery_3d is not scrolling.

I just simply want that flutter_gallery_3d view should normally scroll as normal list and when I scroll outside then it must be navigate to next pageview screen.

**Comment by iapicca** [comment]
I see you already opened an [issue in the correct repo](https://github.com/lazyee/flutter_gallery_3d/issues/2)
I think the problem should be addressed there

**Comment by sahiram036** [comment]
> I see you already opened an [issue in the correct repo](https://github.com/lazyee/flutter_gallery_3d/issues/2) I think the problem should be addressed there

What do I do for now? should I close this issue ?

**Comment by exaby73** [comment]
Hello @sahiram036. Looks like an issue with flutter_gallery_3d and not Flutter itself. Please follow up with the issue you raised there. I am closing this issue as it's not one related to Flutter itself. Thank you
