### ISSUE TITLE
[Web/video_player] IFrameElement of iOS Display in Flutter Web

### ISSUE THREAD

**Issue by daisukenagata** [flutter/flutter#117845]
## Steps to Reproduce

**today is the latest
It occurs in Flutter3.3.10 environment. When the URL played on flutter web is loaded on iOS mobile safari, the behavior generation UI overlaps. Thank you very much for your support.**

1. Listed in pub spec ymal -> video_player: 
2. Load Chrome's URL on iOS Mobile.　: 
3.  sample code 
```
import 'dart:html';
import 'dart:ui' as ui;
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});
  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: TextButton(
        onPressed: (() {
          movie(
            'example',
            'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4',
          );
        }),
        child: const Text('action'),
      ),
    );
  }

  Future<void> movie(
    String title,
    String path,
  ) async {
    showDialog<void>(
      context: context,
      barrierDismissible: false,
      builder: (BuildContext context) {
        // ignore: undefined_prefixed_name
        ui.platformViewRegistry.registerViewFactory(
            'hello-html', (int viewId) => IFrameElement()..src = path);
        return SizedBox(
          width: MediaQuery.of(context).size.width,
          height: MediaQuery.of(context).size.width,
          child: CupertinoAlertDialog(
            title: Text(
              title,
              style: ThemeData(fontFamily: 'NotoSansJP').textTheme.titleMedium,
            ),
            content: const SizedBox(
              width: 760,
              height: 570,
              child: HtmlElementView(
                viewType: 'hello-html',
              ),
            ),
            actions: [
              CupertinoDialogAction(
                child: const Text('close'),
                onPressed: () {
                  Navigator.pop(context);
                },
              ),
            ],
          ),
        );
      },
    );
  }
}

```  

**Expected results:** 
Playback UI does not overlap
**Actual results:** 

https://user-images.githubusercontent.com/16457165/210158665-a7ea094c-7468-496b-8661-020f43743ea2.mov

<details>
  <summary>Logs</summary>

<img width="837" alt="スクリーンショット 2023-01-01 9 53 31" src="https://user-images.githubusercontent.com/16457165/210158416-3f4b5784-d5dc-4026-a243-11d93523af34.png">

```
```

```
```

</details>

**Comment by darshankawar** [comment]
Thanks for the report @daisukenagata 
I see the same behavior upon running the code sample using latest versions (stable and master). 

<img width="999" alt="Screenshot 2023-01-02 at 1 16 19 PM" src="https://user-images.githubusercontent.com/67046386/210206309-a98689cd-f071-4005-ae37-ff06b441b744.png">

The same behavior is observed if we directly run the code sample on mobile browser.

I also tried by setting `style.height` and `style.width` to below code snippet, which resulted in same behavior:

```
ui.platformViewRegistry.registerViewFactory(
            'hello-html', (int viewId) => IFrameElement()..src = path);
```

**Comment by ditman** [comment]
This code sample is not using the video_player plugin at all, it's just setting the src of an iframe to a video file. In this case, it's the browser deciding to scale the video to that size, and to render the UX on top of it. Flutter is not controlling or drawing anything inside the iframe element.

This pure HTML code (with some CSS) probably behaves similarly:

* https://jsfiddle.net/ditman/nub2yd63/

Here's a simple example from the video_player plugin, that should work on the web:

* https://github.com/flutter/plugins/blob/main/packages/video_player/video_player/example/lib/basic.dart
