### ISSUE TITLE
Outdated docstring for `TextPainter`

### ISSUE THREAD

**Issue by CicadaCinema** [flutter/flutter#117861]
It looks like some parts of docstrings here were written before the introduction of null safety:
https://github.com/flutter/flutter/blob/0b451b6dfd6de73ff89d89081c33d0f971db1872/packages/flutter/lib/src/painting/text_painter.dart#L190

https://github.com/flutter/flutter/blob/0b451b6dfd6de73ff89d89081c33d0f971db1872/packages/flutter/lib/src/painting/text_painter.dart#L195

`textAlign` is not nullable, but the docstring implies that it is.

Not sure if this is an easy fix or whether more documentation would need to be updated at the same time.

**Comment by goderbauer** [comment]
The doc string is still correct. `textAlign` cannot and must not be null. Sure, with null-safety that is already implied, but we don't have plans to change the docs since they are still correct.
