### ISSUE TITLE
NetworkImage won't load firebase images

### ISSUE THREAD

**Issue by YawarOsman** [flutter/flutter#117867]
I have tried to fetch firebase image and show it in NetworkImage in my Flutter `Web` app but it won't load the image and shows this error:

> exception was thrown: ImageCodecException: Failed to load network image.

I am using `CanvasKit` renderer

this is the code i've used:

```

class ItemCard extends StatelessWidget {
  ItemCard({super.key, required this.item, required this.onItemCardTap});
  Map<String, dynamic> item = {};
  Function() onItemCardTap;

  @override
  Widget build(BuildContext context) {
    return Consumer<BasketItems>(
      builder: (context, basketItems, child) => InkWell(
        onTap: onItemCardTap,
        overlayColor: MaterialStateProperty.all(Colors.transparent),
        child: Card(
          elevation: 10,
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius10.all,
          ),
          child: Container(
                    width: double.infinity,
                    height: 135,
                    decoration: BoxDecoration(
                      borderRadius: BorderRadius10.all.copyWith(
                          bottomLeft: Radius.zero, bottomRight: Radius.zero),
                       image: DecorationImage(
                           alignment: Alignment.topCenter,
                           fit: BoxFit.cover,
                           image: NetworkImage(
                             item['imageId'],
                           ))
                    ),
                
               ),
        ),
      ),
    );
  }
}

```

 [This is the image](https://firebasestorage.googleapis.com/v0/b/dragon-morina.appspot.com/o/images%2Fitems%2F2?alt=media&token=10e84a12-e1fb-4451-93bd-1770c4401ea5)

<details>
<summary> flutter doctor</summary>

> Doctor summary (to see all details, run flutter doctor -v):
> [✓] Flutter (Channel stable, 3.3.10, on macOS 11.7.1 20G918 darwin-x64, locale en-US)
> [✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
> [✓] Xcode - develop for iOS and macOS (Xcode 13.0)
> [✓] Chrome - develop for the web
> [✓] Android Studio (version 2021.2)
> [✓] VS Code (version 1.74.2)
> [✓] Connected device (2 available)
> [✓] HTTP Host Availability
> 
> • No issues found!

</details>

<details>
<summary> flutter --version</summary>

Flutter 3.3.10 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 135454af32 (3 weeks ago) • 2022-12-15 07:36:55 -0800
Engine • revision 3316dd8728
Tools • Dart 2.18.6 • DevTools 2.15.0

</details>

**Comment by danagbemava-nc** [comment]
Hi @YawarOsman, what you're running into is a CORS issue. Kindly see https://docs.flutter.dev/development/platform-integration/web/web-images#cross-origin-images & https://docs.flutter.dev/development/platform-integration/web/web-images#host-your-images-in-a-cors-enabled-cdn and try to follow the instructions to see if you're able to resolve your issue.

Thank you

**Comment by YawarOsman** [comment]
> Hi @YawarOsman, what you're running into is a CORS issue. Kindly see https://docs.flutter.dev/development/platform-integration/web/web-images#cross-origin-images & https://docs.flutter.dev/development/platform-integration/web/web-images#host-your-images-in-a-cors-enabled-cdn and try to follow the instructions to see if you're able to resolve your issue.
> 
> Thank you

I think the instructions isn't clear enough for me, could you please give me some explanation to resolve it? I'll appreciate you

**Comment by danagbemava-nc** [comment]
Hi @YawarOsman, kindly see https://firebase.google.com/docs/hosting/full-config#headers for how to set the headers in your firebase.json file. 

Kindly let me know if it helps.

**Comment by YawarOsman** [comment]
> 

I've set the header inside my `firebase.json` but it still don't load the images.

This is my `firebase.json` file:

```{
  "hosting": {
    "public": "build/web",
    "ignore": [
      "firebase.json",
      "**/.*",
      "**/node_modules/**"
    ],
    "headers": [ {
      "source": "**/*.@(eot|otf|ttf|ttc|woff|font.css)",
      "headers": [ {
        "key": "Access-Control-Allow-Origin",
        "value": "*"
      } ]
    } ]
  }
}
```

**Comment by YawarOsman** [comment]
it is fixed thank you so much
