### ISSUE TITLE
Ellipsis on wrong side with textDirection.rtl

### ISSUE THREAD

**Issue by countablechoice** [flutter/flutter#117831]
Given

    Text(
        '1  2  3  4  5  6  7  8  9'
        textDirection: TextDirection.rtl,
        softWrap: false,
        overflow: TextOverflow.ellipsis,
    )

I expect the ellipsis to be on the left hand side, but it is still on the right hand side.  Note that `TextOverflow.fade` works as expected.

Tested on

    $ flutter --version
    Flutter 2.10.5 • channel stable • https://github.com/flutter/flutter.git
    Framework • revision 5464c5bac7 (9 months ago) • 2022-04-18 09:55:37 -0700
    Engine • revision 57d3bac3dd
    Tools • Dart 2.16.2 • DevTools 2.9.2

with `web` target.

**Comment by danagbemava-nc** [comment]
Closing this in favor of https://github.com/flutter/flutter/issues/113453. 

Kindly follow up in the issue linked above for updates. 

Thank you
