### ISSUE TITLE
[in_app_purchase_storekit] The plugin should not crash when `[[NSBundle mainBundle] appStoreReceiptURL]` is nil

### ISSUE THREAD

**Issue by sneglia9191** [flutter/flutter#117842]
I am getting a hard crash when purchasing a non-consumable on IOS simulators with 14.X.  It does not crash on a simulator with 16.2.  It also works in the sandbox environment on a physical device running 14.8.1

The crash occurs on this exact line:

```
productDetails.launchPurchaseFlowSuccess =
        await _iap?.buyNonConsumable(purchaseParam: purchaseParam) ?? false;
```

The billing Apple Pay dialog still appears and I am able to complete the billing transaction, but the app has crashed.  The error is:

```
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[_NSPlaceholderData initWithContentsOfURL:options:maxLength:error:
```

The full error dump is

```
2022-12-31 13:00:38.558115-0500 Runner[4880:31777] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[_NSPlaceholderData initWithContentsOfURL:options:maxLength:error:]: nil URL argument'
 *** First throw call stack:
 (
 	0   CoreFoundation                      0x00007fff20420af6 __exceptionPreprocess + 242
 	1   libobjc.A.dylib                     0x00007fff20177e78 objc_exception_throw + 48
 	2   Foundation                          0x00007fff20751939 -[NSData(NSData) initWithContentsOfFile:options:error:] + 0
 	3   Foundation                          0x00007fff207512ff +[NSData(NSData) dataWithContentsOfURL:options:error:] + 49
 	4   in_app_purchase_storekit            0x000000010dad0830 -[FIAPReceiptManager getReceiptData:error:] + 96
 	5   in_app_purchase_storekit            0x000000010dad05f6 -[FIAPReceiptManager retrieveReceiptWithError:] + 134
 	6   in_app_purchase_storekit            0x000000010dad46c6 -[InAppPurchasePlugin retrieveReceiptData:result:] + 134
 	7   in_app_purchase_storekit            0x000000010dad2037 -[InAppPurchasePlugin handleMethodCall:result:] + 983
 	8   Flutter                             0x000000010e1741f5 __45-[FlutterMethodChannel setMethodCallHandler:]_block_invoke + 104
 	9   Flutter                             0x000000010dbac18a ___ZN7flutter25PlatformMessageHandlerIos21HandlePlatformMessageENSt3__110unique_ptrINS_15PlatformMessageENS1_14default_deleteIS3_EEEE_block_invoke + 86
 	10  libdispatch.dylib                   0x00000001110967ec _dispatch_call_block_and_release + 12
 	11  libdispatch.dylib                   0x00000001110979c8 _dispatch_client_callout + 8
 	12  libdispatch.dylib                   0x00000001110a5e75 _dispatch_main_queue_callback_4CF + 1152
 	13  CoreFoundation                      0x00007fff2038edbb __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
 	14  CoreFoundation                      0x00007fff2038963e __CFRunLoopRun + 2685
 	15  CoreFoundation                      0x00007fff203886d6 CFRunLoopRunSpecific + 567
 	16  GraphicsServices                    0x00007fff2bededb3 GSEventRunModal + 139
 	17  UIKitCore                           0x00007fff24690e0b -[UIApplication _run] + 912
 	18  UIKitCore                           0x00007fff24695cbc UIApplicationMain + 101
 	19  Runner                              0x0000000104a89ccf main + 63
 	20  ???                                 0x00000002050eb310 0x0 + 8674784016
 )
libc++abi.dylib: terminating with uncaught exception of type NSException
 *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[_NSPlaceholderData initWithContentsOfURL:options:maxLength:error:]: nil URL argument'
terminating with uncaught exception of type NSException
 CoreSimulator 857.14 - Device: iPhone 12 Pro Max (6D7FF6C5-3809-4475-AEC2-5C49B4B139FC) - Runtime: iOS 14.3 (18C61) - DeviceType: iPhone 12 Pro Max
 _LSContextInitReturningError() failed with error Error Domain=NSOSStatusErrorDomain Code=-10817 "(null)" UserInfo={_LSFunction=_LSSchemaConfigureForStore, ExpectedSimulatorHash={length = 32, bytes = 0x06fa6496 daaf0574 96588f97 3218198d ... 2862792f 88b4164f }, _LSLine=405, WrongSimulatorHash={length = 32, bytes = 0x2bded6e0 32f2e4de 89d64fa6 5f014c96 ... b204c4d8 0350c8ce }}

```

## Plugins
  in_app_purchase: ^3.0.8
  in_app_purchase_android: ^0.2.3+6
  in_app_purchase_storekit: ^0.3.3

## Steps to Reproduce

To reproduce, simply start an IOS emulator running version 14.3.  Initiate a billing transaction of a non-consumable.  

<details>
<summary>flutter doctor</summary>

```
Flutter (Channel stable, 3.3.9, on macOS 13.1 22C65 darwin-arm, locale en-GB)
    • Flutter version 3.3.9 on channel stable at /Users/sneglia/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b8f7f1f986 (6 weeks ago), 2022-11-23 06:43:51 +0900
    • Engine revision 8f2221fbef
    • Dart version 2.18.5
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/sneglia/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] Connected device (2 available)
    • iPhone 12 Pro Max (mobile) • 6D7FF6C5-3809-4475-AEC2-5C49B4B139FC • ios          • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64 • macOS 13.1 22C65 darwin-arm

[✓] HTTP Host Availability
    • All required HTTP hosts are available
```
</details>

**Comment by danagbemava-nc** [comment]
Hi @sneglia9191, can you share your full `pubspec.yaml`? 

Is the issue only with non-consumables or do you also experience it with consumables?

**Comment by sneglia9191** [comment]
Hello - I have not tested with consumables.  I do not have consumables in my project.  Below is my full pub spec.yaml.

name: bowl_score_keeper_flutter
description: A new Flutter project.

version: 1.0.0+2

environment:
  sdk: ">=2.17.6 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.1
  bloc: ^8.1.0
  meta: ^1.8.0
  catcher: ^0.7.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.05

  sqflite:
  path:

  ##https://pub:dev/packages/adaptive_theme:
  adaptive_theme: ^3.1.1

  #Google AdMob
  google_mobile_ads: ^2.2.0

  #iabtcf
  iabtcf_consent_info: ^3.0.0
  iabtcf_consent_info_platform_interface: ^1.0.5
  rxdart: ^0.26.0

  equatable: ^2.0.0
  shared_preferences: ^2.0.15
  in_app_purchase: ^3.0.8
  in_app_purchase_android: ^0.2.3+6
  in_app_purchase_storekit: ^0.3.3
  url_launcher: ^6.1.6
  http: ^0.13.5
  firebase_core: ^2.3.0
  firebase_crashlytics: ^3.0.6
  firebase_analytics: ^10.0.6
  logging: ^1.1.0
  intl: ^0.17.0
  app_tracking_transparency: ^2.0.3
  device_info_plus: ^7.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/help/

**Comment by danagbemava-nc** [comment]
Hi @sneglia9191, can you try commenting out the `in_app_purchase_storekit` & `in_app_purchase_android` and running `flutter pub get` again and retrying the process to see if the app crashes? 

Those 2 dependencies should be automatically included when you include `in_app_purchase`

**Comment by sneglia9191** [comment]
Hello.  I commented the two packages.  I ran a `flutter pub clean` and a `flutter pub get`. The issue still occurs.  is there something else I should do to ensure no contention?

**Comment by danagbemava-nc** [comment]
Can you try running a fresh sample to see if you're able to reproduce the issue? There were some reports of this in the past and it seemed to be caused by having `google_sign_in` and `in_app_purchase` in the app. 

Can you also share the output of `flutter pub deps -- --style=compact` from your main project? I'm wondering if any package/plugin you have may depend on it. 

Also is the video in https://github.com/flutter/flutter/issues/95166#issuecomment-992461818 similar to how it happens for you?

**Comment by sneglia9191** [comment]
Are you asking me to write a fresh application to recreate?  That will take some time to do.   I am not using `google_sign_in`  The behaviour is similar to the video from #95166.   I am still able to confirm the purchase and I get a success message, but the app hangs.  It doesn't really crash, but it becomes unusable.  If you suspect a particular dependency, I can try commenting out that logic and see what happens.

Here is my output

Dart SDK 2.18.5
Flutter SDK 3.3.9
bowl_score_keeper_flutter 1.0.0+2

dependencies:
- adaptive_theme 3.1.1 [flutter shared_preferences]
- app_tracking_transparency 2.0.3 [flutter]
- bloc 8.1.0 [meta]
- catcher 0.7.0 [flutter flutter_web_plugins fluttertoast device_info_plus device_info_plus_platform_interface package_info_plus mailer dio flutter_mailer logging sentry universal_io]
- cupertino_icons 1.0.5
- device_info_plus 7.0.1 [device_info_plus_platform_interface ffi file flutter flutter_web_plugins meta win32]
- equatable 2.0.5 [collection meta]
- firebase_analytics 10.1.0 [firebase_analytics_platform_interface firebase_analytics_web firebase_core firebase_core_platform_interface flutter]
- firebase_core 2.4.1 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_crashlytics 3.0.9 [firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface flutter stack_trace]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]
- flutter_bloc 8.1.1 [flutter bloc provider]
- google_mobile_ads 2.3.0 [meta flutter visibility_detector]
- http 0.13.5 [async http_parser meta path]
- iabtcf_consent_info 3.0.0 [flutter meta rxdart iabtcf_consent_info_platform_interface iabtcf_consent_info_web]
- iabtcf_consent_info_platform_interface 1.0.5 [flutter meta plugin_platform_interface]
- in_app_purchase 3.1.1 [flutter in_app_purchase_android in_app_purchase_platform_interface in_app_purchase_storekit]
- intl 0.17.0 [clock path]
- logging 1.1.0
- meta 1.8.0
- path 1.8.2
- rxdart 0.26.0
- shared_preferences 2.0.15 [flutter shared_preferences_android shared_preferences_ios shared_preferences_linux shared_preferences_macos shared_preferences_platform_interface shared_preferences_web shared_preferences_windows]
- sqflite 2.2.2 [flutter sqflite_common path]
- url_launcher 6.1.7 [flutter url_launcher_android url_launcher_ios url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]

dev dependencies:
- flutter_lints 2.0.1 [lints]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters collection matcher material_color_utilities meta source_span stream_channel string_scanner term_glyph]

transitive dependencies:
- _flutterfire_internals 1.0.12 [collection firebase_core firebase_core_platform_interface flutter meta]
- async 2.9.0 [collection meta]
- boolean_selector 2.1.0 [source_span string_scanner]
- characters 1.2.1
- clock 1.1.1
- collection 1.16.0
- crypto 3.0.2 [typed_data]
- device_info_plus_platform_interface 6.0.1 [flutter meta plugin_platform_interface]
- dio 4.0.6 [http_parser path]
- fake_async 1.3.1 [clock collection]
- ffi 2.0.1
- file 6.1.4 [meta path]
- firebase_analytics_platform_interface 3.3.17 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_analytics_web 0.5.1+8 [_flutterfire_internals firebase_analytics_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- firebase_core_platform_interface 4.5.2 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.1.0 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_crashlytics_platform_interface 3.3.10 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- flutter_mailer 2.0.1 [flutter]
- flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta vector_math]
- fluttertoast 8.1.2 [flutter flutter_web_plugins]
- http_parser 4.0.2 [collection source_span string_scanner typed_data]
- iabtcf_consent_info_web 3.0.0 [flutter flutter_web_plugins iabtcf_consent_info_platform_interface js]
- in_app_purchase_android 0.2.3+7 [collection flutter in_app_purchase_platform_interface json_annotation]
- in_app_purchase_platform_interface 1.3.2 [flutter plugin_platform_interface]
- in_app_purchase_storekit 0.3.4 [collection flutter in_app_purchase_platform_interface json_annotation]
- js 0.6.4
- json_annotation 4.7.0 [meta]
- lints 2.0.1
- mailer 5.3.0 [async logging intl mime path pedantic meta]
- matcher 0.12.12 [stack_trace]
- material_color_utilities 0.1.5
- mime 1.0.3
- nested 1.0.0 [flutter]
- package_info_plus 3.0.2 [ffi flutter flutter_web_plugins http meta path package_info_plus_platform_interface win32]
- package_info_plus_platform_interface 2.0.1 [flutter meta plugin_platform_interface]
- path_provider_linux 2.1.7 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_platform_interface 2.0.5 [flutter platform plugin_platform_interface]
- path_provider_windows 2.1.3 [ffi flutter path path_provider_platform_interface win32]
- pedantic 1.11.1
- platform 3.1.0
- plugin_platform_interface 2.1.3 [meta]
- process 4.2.4 [file path platform]
- provider 6.0.5 [collection flutter nested]
- sentry 6.18.1 [http meta stack_trace uuid intl]
- shared_preferences_android 2.0.14 [flutter shared_preferences_platform_interface]
- shared_preferences_ios 2.1.1 [flutter shared_preferences_platform_interface]
- shared_preferences_linux 2.1.2 [file flutter path path_provider_linux path_provider_platform_interface shared_preferences_platform_interface]
- shared_preferences_macos 2.0.4 [flutter shared_preferences_platform_interface]
- shared_preferences_platform_interface 2.1.0 [flutter plugin_platform_interface]
- shared_preferences_web 2.0.4 [flutter flutter_web_plugins shared_preferences_platform_interface]
- shared_preferences_windows 2.1.2 [file flutter path path_provider_platform_interface path_provider_windows shared_preferences_platform_interface]
- sky_engine 0.0.99
- source_span 1.9.0 [collection path term_glyph]
- sqflite_common 2.4.0+2 [synchronized path meta]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.1 [source_span]
- synchronized 3.0.0+3
- term_glyph 1.2.1
- test_api 0.4.12 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.1 [collection]
- universal_io 2.0.4 [collection crypto meta typed_data]
- url_launcher_android 6.0.22 [flutter url_launcher_platform_interface]
- url_launcher_ios 6.0.17 [flutter url_launcher_platform_interface]
- url_launcher_linux 3.0.1 [flutter url_launcher_platform_interface]
- url_launcher_macos 3.0.1 [flutter url_launcher_platform_interface]
- url_launcher_platform_interface 2.1.1 [flutter plugin_platform_interface]
- url_launcher_web 2.0.13 [flutter flutter_web_plugins url_launcher_platform_interface]
- url_launcher_windows 3.0.1 [flutter url_launcher_platform_interface]
- uuid 3.0.7 [crypto]
- vector_math 2.1.2
- visibility_detector 0.3.3 [flutter]
- win32 3.1.3 [ffi]
- xdg_directories 0.2.0+2 [meta path process]

**Comment by danagbemava-nc** [comment]
> I presume you are not able to recreate using a 14.x simulator?

Yes, I cannot do this atm. I've been attempting to do this for a while but it always fails. 

> Are you asking me to write a fresh application to recreate? That will take some time to do.

You wouldn't need to recreate all your code. You should be able to use just the example code from plugin to create a new project to see if it happens in a fresh project. You'd just need to make sure your app id matches the one registered in the store and that the ids for the products match what you have in the store

**Comment by sneglia9191** [comment]
Hello - Using the example plugin, I was able to recreate the issue installing the `catcher 0.7.0` package.  When I exclude it, there are no issues with the example.  When I add it, it causes the error.   For awareness, I was getting an error that 'fluttertoast' could not be found when building, but adding `import 'package:catcher/catcher.dart'` resolved that.

**Comment by danagbemava-nc** [comment]
Thanks for the info. 

I'm curious, was the issue with only `fluttertoast` or other plugins could not be found without the inclusion of `catcher`? I'm wondering why the inclusion of `catcher` allowed `fluttertoast` to be found.

**Comment by sneglia9191** [comment]
I tested the example by adding all my plugins.   Only catcher gave me the error with fluttertoast, and I had no other issues with the app crashing.   Below is the error I get in Xcode when trying to compile with Catcher w/o the import:

![image](https://user-images.githubusercontent.com/118394743/211308308-8af50c72-e347-4160-8e37-65aae4e9061a.png)

btw, I also tried explicitly adding the fluttertoast package as a dependency.  The same issue happened with the app crashing on purchase.  This is definitely some type of conflict between `in_app_purchase` and `catcher`.

`google_mobile_ads: ^2.2.0` also stopped the app even before the splash form but with a different error that appears unrelated:

_*** Terminating app due to uncaught exception 'GADInvalidInitializationException', reason: 'The Google Mobile Ads SDK was initialized without an application ID. Google AdMob publishers, follow instructions at https://googlemobileadssdk.page.link/admob-ios-update-plist to set a valid application ID._

**Comment by danagbemava-nc** [comment]
Hi @sneglia9191, so it seems like `catcher` depends on `fluttertoast` and might be partially responsible for the issue you faced regarding the module not being found.  I added `catcher`(without adding fluttertoast directly)  to a project and when I tried to run it I got an error that `futtertoast` could not be found. (Although other users of fluttertoast seem to have this issue, see https://github.com/ponnamkarthik/FlutterToast/issues/411). 
I also took a look at the native source code for `catcher` but the file only contains the template code. So I wonder if the issue is actually caused by `fluttertoast` rather than `catcher`. 

> *** Terminating app due to uncaught exception 'GADInvalidInitializationException', reason: 'The Google Mobile Ads SDK was initialized without an application ID. Google AdMob publishers, follow instructions at [googlemobileadssdk.page.link/admob-ios-update-plist](https://googlemobileadssdk.page.link/admob-ios-update-plist) to set a valid application ID.

Yes, this is unrelated. 

> This is definitely some type of conflict between in_app_purchase and catcher.

That seems to be the case. Can you file a report on their repo so that they can look into it? Since the presence of these third-party plugins is what causes the crash, they might have a better understanding of how to track the issue down.

**Comment by sneglia9191** [comment]
Daniel - why was this issue closed?  It is still an issue and has not been resolved.  I have isolated the issue for you to be a conflict with the [Catcher] plugin.  You confirmed yourself this appears to be the case.  You asked me to file an issue with the [Catcher] team, which I did.   Regardless of root cause, the effects are occurring in your plug-in.  I personally cannot supply you any more information. I ask that you re-open the issue and also reach out to the [Catcher] team to see how you can work together to resolve.

**Comment by cyanglaz** [comment]
The crash is caused by the receipt being nil while retrieving the receipt data: https://github.com/flutter/plugins/blob/main/packages/in_app_purchase/in_app_purchase_storekit/darwin/Classes/FIAPReceiptManager.m#L23

Not sure the exact reason, in Apple's documentation: "this property is nil if the receipt isn’t present."
We should handle the nil case.
