### ISSUE TITLE
go_router - No GoRouter found in context

### ISSUE THREAD

**Issue by BenjiFarquhar** [flutter/flutter#117866]
I have run into an issue migrating my project from the Navigator to go_router. 

My project listens to an auth status stream and navigates in the listener. That code now creates an error  

> No GoRouter found in context

The code:

    return MaterialApp.router(
      theme: lightTheme,
      debugShowCheckedModeBanner: false,
      darkTheme: darkTheme,
      routerConfig: routerConfig,
      builder: (BuildContext builderContext, Widget? child) {
        ref.watch(authStatusServiceProvider).whenData((authStatus) {
          switch (authStatus) {
            case AuthenticationStatusEnum.authenticated:
              builderContext.go(HOME);
              break;
            case AuthenticationStatusEnum.unauthenticated:
              builderContext.go(LOGGED_OUT_HOME);
              break;
            default:
              builderContext.go(LOGGED_OUT_HOME);
              break;
          }
        });
        return child!;
      },
    );

Since I did it inside MaterialApp.builder, I would have thought the context would have the go router inherited widget. Is there any way to make this work or should I scrap the auth listener entirely?

My config:

```
const FIND_VEGAN_ITEMS_PAGE = '/find-vegan-items-page';
const HOME = '/';
const LOGGED_OUT_HOME = '/logged-out-home';
const MANAGE_VEGAN_ITEMS_PAGE = '/manage-vegan-items-page';
const REGISTER_PAGE = '/register-page';
const SETTINGS = '/settings';
const SIGN_IN_PAGE = '/sign-in-page';
const SPLASH = '/splash';

final routerConfig = GoRouter(
  navigatorKey: globalKey,
  initialLocation: LOGGED_OUT_HOME,
  observers: [],
  routes: [
    GoRoute(
      path: SPLASH,
      builder: (context, state) => const SplashPage(),
    ),
    GoRoute(
      path: SIGN_IN_PAGE,
      builder: (context, state) => const SignInPage(),
    ),
    GoRoute(
      path: REGISTER_PAGE,
      builder: (context, state) => RegisterPage(),
    ),
    GoRoute(
      path: HOME,
      builder: (context, state) => const HomePage(),
    ),
    GoRoute(
      path: SETTINGS,
      builder: (context, state) => const SettingsPage(),
    ),
    GoRoute(
      path: FIND_VEGAN_ITEMS_PAGE,
      builder: (context, state) => const SearchPage(),
    ),
    GoRoute(
      path: MANAGE_VEGAN_ITEMS_PAGE,
      builder: (context, state) =>
          ManageVgnItmsPage(state.params["ref"]! as WidgetRef),
    ),
    GoRoute(
      path: LOGGED_OUT_HOME,
      builder: (context, state) => const UnauthenticatedHomePage(),
    ),
  ],
);

```

[Here is someone else with the same problem](https://stackoverflow.com/questions/74327180/go-router-and-flutter-bloc-unhandled-exception-no-gorouter-found-in-context#comment132317312_74327180).

[This](https://docs.page/csells/go_router/navigator-builder) sort of looks like what would work but I see in the [change logs that we need to migrate to use MaterialApp.builder](https://docs.google.com/document/d/10l22o4ml4Ss83UyzqUC8_xYOv_QjZEi80lJDNE4q7wM/edit?pli=1&resourcekey=0-U-BXBQzNfkk4v241Ow-vZg#), but it is not sufficient to work.

**Comment by darshankawar** [comment]
@BenjiFarquhar Thanks for the report. 

> builderContext.go(HOME);

Here, instead of `builderContext.go`, can you try `routerConfig.go` and see if it helps in your case ?

**Comment by BenjiFarquhar** [comment]
> Here, instead of `builderContext.go`, can you try `routerConfig.go` and see if it helps in your case ?

Yes, it is working when I do that. Thanks!
