### ISSUE TITLE
While adding wrong value in date picker ui not properly shown in web

### ISSUE THREAD

**Issue by MurtuzaSrashtaSoft** [flutter/flutter#117872]
@MurtuzaSrashtaSoft, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this. Also, please provide the output of `flutter doctor -v` as well.

_Originally posted by @huycozy in https://github.com/flutter/flutter/issues/113712#issuecomment-1284933164_

**Comment by MurtuzaSrashtaSoft** [comment]
[✓] Flutter (Channel stable, 2.10.5, on macOS 13.0.1 22A400 darwin-arm, locale en-IN)
    • Flutter version 2.10.5 at /Users/nalawalamurtuza/Library/Android/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (9 months ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

**Comment by danagbemava-nc** [comment]
The issue in #113712 is already being tracked in https://github.com/flutter/flutter/issues/110563. 

Kindly follow up in the issue linked above for updates. 

Closing from here as duplicate. 

Thank you

**Comment by MurtuzaSrashtaSoft** [comment]
@danagbemava-nc thank fot reply.
