### ISSUE TITLE
flutter test is missing the flag --use-application-binary, were-in flutter drive has it

### ISSUE THREAD

**Issue by iam-kj** [flutter/flutter#117889]
## Description
flutter drive has the `--use-application-binary` flag. Run flutter drive --help to see the list of commands / flags :

Specify a pre-built application binary to use when running. For Android applications, this must be the path to an APK. For iOS applications, the path to an IPA. Other device types do not yet support prebuilt application binaries.

This is very useful option get the APK file installed on Emulator while after triggering Flutter Automation Test.

> `$ flutter drive \
>   --driver test_driver/integration_test.dart --use-application-binary integration_test/outputs/app-qa-release.apk`

This skips the build and goes straight to driving the app, greatly improving test execution.

At the same time, we couldn't get this done from `Flutter Test command`. it seems to be missing the flag.

## Expected results:

It should work similar to what we have in **Flutter Drive**, skip the whole build cycle and instead install the `.apk` into emulator which is pre-built already. then kickstart the Flutter Integration test.

## Actual results:

$ flutter test integration_test --use-application-binary build/app/outputs/flutter-apk/app-debug.apk
Could not find an option named "**use-application-binary**".

Run `flutter -h` (or `flutter <command> -h`) for available flutter commands and options.
                                                                                                                                           
Tested on both the Flutter versions: 2.10.5 & 3.3.9 • channel stable • https://github.com/flutter/flutter.git

**Comment by danagbemava-nc** [comment]
Hi @iam-kj, this is a known issue and it is being tracked in https://github.com/flutter/flutter/issues/114541. 

Kindly follow up in the issue linked above for updates. 

Closing from here as duplicate. 

Thank you
