### ISSUE TITLE
[tool_crash] FileSystemException: Exists failed, OS Error: The filename, directory name, or volume label syntax is incorrect., errno = 123

### ISSUE THREAD

**Issue by ravimandal06** [flutter/flutter#117815]
## Command
```
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Exists failed, OS Error: The filename, directory name, or volume label syntax is incorrect.
, errno = 123
```
#0      _Directory.existsSync (dart:io/directory_impl.dart:94:7)
#1      ForwardingFileSystemEntity.existsSync (package:file/src/forwarding/forwarding_file_system_entity.dart:43:33)
#2      ErrorHandlingDirectory.existsSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:497:22)
#3      _runSync (package:flutter_tools/src/base/error_handling_io.dart:597:14)
#4      ErrorHandlingDirectory.existsSync (package:flutter_tools/src/base/error_handling_io.dart:496:12)
#5      ManifestAssetBundle._parseAssetsFromFolder (package:flutter_tools/src/asset.dart:818:47)
#6      ManifestAssetBundle._parseAssets (package:flutter_tools/src/asset.dart:741:9)
#7      ManifestAssetBundle.build (package:flutter_tools/src/asset.dart:261:54)
<asynchronous suspension>
#8      HotRunner._updateDevFS (package:flutter_tools/src/run_hot.dart:446:26)
<asynchronous suspension>
#9      HotRunner._reloadSources (package:flutter_tools/src/run_hot.dart:886:21)
<asynchronous suspension>
#10     HotRunner._hotReloadHelper (package:flutter_tools/src/run_hot.dart:812:16)
<asynchronous suspension>
#11     HotRunner.restart (package:flutter_tools/src/run_hot.dart:707:36)
<asynchronous suspension>
#12     TerminalHandler._commonTerminalInputHandler (package:flutter_tools/src/resident_runner.dart:1686:40)
<asynchronous suspension>
#13     TerminalHandler.processTerminalInput (package:flutter_tools/src/resident_runner.dart:1739:7)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 3.3.9, on Microsoft Windows
    [Version 10.0.22000.1335], locale en-IN)
    • Flutter version 3.3.9 on channel stable at
      C:\Users\91707\fvm\default
    • Upstream repository
      https://github.com/flutter/flutter.git
    • Framework revision b8f7f1f986 (5 weeks ago), 2022-11-23
      06:43:51 +0900
    • Engine revision 8f2221fbef
    • Dart version 2.18.5
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android
    SDK version 33.0.0-rc2)
    • Android SDK at C:\Users\91707\AppData\Local\Android\Sdk
    • Platform android-33, build-tools 33.0.0-rc2
    • ANDROID_HOME = C:\Users\91707\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android
      Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build
      11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program
      Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Build
    Tools 2019 16.9.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft
      Visual Studio\2019\BuildTools
    • Visual Studio Build Tools 2019 version 16.9.31205.134
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android
      Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.12+7-b1504.28-7817840)

[✓] VS Code (version 1.74.2)
    • VS Code at
      C:\Users\91707\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.56.0

[✓] Connected device (4 available)
    • Mi A3 (mobile)    • b46ef3f4f0c4 • android-arm64  •
      Android 11 (API 30)
    • Windows (desktop) • windows      • windows-x64    •
      Microsoft Windows [Version 10.0.22000.1335]
    • Chrome (web)      • chrome       • web-javascript •
      Google Chrome 108.0.5359.125
    • Edge (web)        • edge         • web-javascript •
      Microsoft Edge 108.0.1462.54

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.19+23
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 85684f9300908116a78138ea4c6036c35c9a1236
### Plugins
cloud_firestore_web-3.2.0
firebase_analytics-10.0.8
firebase_analytics_web-0.5.1+7
firebase_auth-4.2.2
firebase_auth_web-5.2.2
firebase_core-2.4.0
firebase_core_web-2.0.2
flutter_facebook_auth-4.4.1+1
flutter_facebook_auth_web-3.2.0
flutter_local_notifications-9.9.1
flutter_plugin_android_lifecycle-2.0.7
fluttertoast-8.1.2
google_sign_in-5.4.2
google_sign_in_android-6.1.4
google_sign_in_ios-5.5.1
google_sign_in_web-0.10.2
image_picker-0.8.6
image_picker_android-0.8.5+4
image_picker_for_web-2.1.10
image_picker_ios-0.8.6+3
package_info_plus-1.4.3+1
package_info_plus_linux-1.0.5
package_info_plus_macos-1.3.0
package_info_plus_web-1.0.6
package_info_plus_windows-2.1.0
path_provider-2.0.11
path_provider_android-2.0.22
path_provider_ios-2.0.11
path_provider_linux-2.1.7
path_provider_macos-2.0.6
path_provider_windows-2.1.3
razorpay_flutter-1.3.4
rive_common-0.0.1
share_plus-6.3.0
shared_preferences-2.0.15
shared_preferences_android-2.0.14
shared_preferences_ios-2.1.1
shared_preferences_linux-2.1.2
shared_preferences_macos-2.0.4
shared_preferences_web-2.0.4
shared_preferences_windows-2.1.2
url_launcher-6.1.7
url_launcher_android-6.0.22
url_launcher_ios-6.0.17
url_launcher_linux-3.0.1
url_launcher_macos-3.0.1
url_launcher_web-2.0.13
url_launcher_windows-3.0.1
video_player-2.4.10
video_player_android-2.3.10
video_player_avfoundation-2.3.8
video_player_web-2.0.13
wakelock-0.6.2
wakelock_macos-0.4.0
wakelock_web-0.4.0

**Comment by exaby73** [comment]
Hello @ravimandal06. Thank you for filing this issue. Can you please provide the following information?

- A [complete and minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). Ideally, a single `main.dart` file that can be run directly.
- The output of `flutter doctor -v`
- The output of `flutter run -v`

Please provide the information in the form of text. See how to make collapsible sections with Markdown [here](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-collapsed-sections).
