### ISSUE TITLE
Expanded widget missing from Layout page of widget catalog

### ISSUE THREAD

**Issue by animeshjain** [flutter/flutter#11782]
From URL: https://flutter.io/widgets/layout

I feel this catalog should also include the Expanded widget. It took me a while to discover that, and it is a valuable one.

**Comment by sethladd** [comment]
Thanks for the feedback! Patches definitely welcome :)

**Comment by Hixie** [comment]
Fixing the widget catalog is not on our near-term priority list.

**Comment by zoechi** [comment]
Issue moved to [flutter/website #1856](https://github.com/flutter/website/issues/1856) via [**ZenHub**](https://www.zenhub.com/)
