### ISSUE TITLE
On linux Flutter gtk screen goes black

### ISSUE THREAD

**Issue by giorgi94** [flutter/flutter#117853]
On Xubuntu 20, when I use the `flutter run -d linux` the application UI turns black when I interact with the `TextField` widget. To make sure that it was connected only with the text widget, I made a project with only one `TextField` and the same happened. 

This exception was thrown in the terminal

```
══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞══════════════════════════════════════════════════════════
The following assertion was thrown during a platform message callback:
A KeyRepeatEvent is dispatched, but the state shows that the physical key is not pressed. If this
occurs in real application, please report this bug to Flutter. If this occurs in unit tests, please
ensure that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This
was the event: KeyRepeatEvent#6c4fd(physicalKey: PhysicalKeyboardKey#70051(usbHidUsage:
"0x00070051", debugName: "Arrow Down"), logicalKey: LogicalKeyboardKey#00301(keyId: "0x100000301",
keyLabel: "Arrow Down", debugName: "Arrow Down"), character: null, timeStamp: 0:17:52.019000)
'package:flutter/src/services/hardware_keyboard.dart':
Failed assertion: line 432 pos 16: '_pressedKeys.containsKey(event.physicalKey)'

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack:
#2      HardwareKeyboard._assertEventIsRegular.<anonymous closure>
(package:flutter/src/services/hardware_keyboard.dart:432:16)
#3      HardwareKeyboard._assertEventIsRegular
(package:flutter/src/services/hardware_keyboard.dart:443:6)
#4      HardwareKeyboard.handleKeyEvent (package:flutter/src/services/hardware_keyboard.dart:535:5)
#5      KeyEventManager.handleRawKeyMessage (package:flutter/src/services/hardware_keyboard.dart:881:37)
#6      BasicMessageChannel.setMessageHandler.<anonymous closure>
(package:flutter/src/services/platform_channel.dart:197:49)
#7      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure>
(package:flutter/src/services/binding.dart:387:35)
#8      _invoke2 (dart:ui/hooks.dart:186:13)
#9      _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:42:5)
#10     _Channel._drainStep (dart:ui/channel_buffers.dart:224:31)
(elided 4 frames from class _AssertionError and dart:async)
════════════════════════════════════════════════════════════════════════════════════════════════════

Another exception was thrown: A KeyRepeatEvent is dispatched, but the state shows that the physical key
is not pressed. If this occurs in real application, please report this bug to Flutter. If this occurs in
unit tests, please ensure that simulated events follow Flutter's event model as documented in
`HardwareKeyboard`. This was the event: KeyRepeatEvent#6c4fd(physicalKey:
PhysicalKeyboardKey#70051(usbHidUsage: "0x00070051", debugName: "Arrow Down"), logicalKey:
LogicalKeyboardKey#00301(keyId: "0x100000301", keyLabel: "Arrow Down", debugName: "Arrow Down"),
character: null, timeStamp: 0:17:52.019000)
```
I tried running my application on Manjaro and on android emulator (in Manjaro) it run without bugs.

What can be cousing this problem?

**Comment by darshankawar** [comment]
@giorgi94 
Can you provide `flutter doctor -v` ?

**Comment by giorgi94** [comment]
Sure,


$ flutter doctor -v

[✓] Flutter (Channel stable, 3.3.10, on Ubuntu 20.04.5 LTS 5.15.0-56-generic, locale en_US.UTF-8)
    • Flutter version 3.3.10 on channel stable at /home/gio/Programs/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (3 weeks ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (1 available)
    • Linux (desktop) • linux • linux-x64 • Ubuntu 20.04.5 LTS 5.15.0-56-generic

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 3 categories.

On this machine, I don't have Android Studio, but I don't think that for desktop build it should interfere with desktop build. And Ubuntu version is

$ lsb_release -a

Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.5 LTS
Release:	20.04
Codename:	focal

**Comment by bleroux** [comment]
@giorgi94
Can you to try to reproduce this issue on master channel?
It would really help to figure out if it is already fixed.

**Comment by giorgi94** [comment]
I misspelled the widget name. It is TextField and not TextEdit. I'm used to the `Text` and `Edit` combination for naming this type of widget. Sorry if it was confusing.

Here is an example [My-Flutter-App](https://github.com/giorgi94/My-Flutter-App). I added TextField to flutter's default template.

**Comment by darshankawar** [comment]
> Can you to try to reproduce this issue on master channel?

@giorgi94 Were you able to confirm this ?

**Comment by giorgi94** [comment]
Now I cloned code from the master branch, downloaded SDK, and compiled. This error doesn't happen. So it seems to be a bug with the stable version.

Thank you for the suggestion.
