### ISSUE TITLE
Error: unziping dart-sdk-linux-64x

### ISSUE THREAD

**Issue by PolarV-UNIX** [flutter/flutter#117879]
Downloading Linux x64 Dart SDK from Flutter engine 472e34cbbcd461c748973e7e735558ab200d4f5e...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   193  100   193    0     0    264      0 --:--:-- --:--:-- --:--:--   264
[/home/polar/flutter/bin/cache/dart-sdk-linux-x64.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /home/polar/flutter/bin/cache/dart-sdk-linux-x64.zip or
        /home/polar/flutter/bin/cache/dart-sdk-linux-x64.zip.zip, and cannot find /home/polar/flutter/bin/cache/dart-sdk-linux-x64.zip.ZIP, period.

It appears that the downloaded file is corrupt; please try again.

this the all of the problem and I don't know what can I do to fix it, I try 16842032 times exaclly!! help me please

**Comment by huycozy** [comment]
@PolarV-UNIX Are you upgrading Flutter SDK? 

Can you please provide the output of `flutter doctor -v` and the complete upgrading log if any?

May be related/similar: #66243

**Comment by PolarV-UNIX** [comment]
Hi huycozy
I receive the same output exactly. the main error is this:
unzip: cannot find zipfile directory in one of /home/polar/flutter/bin/cache/dart-sdk-linux-x64.zip or
/home/polar/flutter/bin/cache/dart-sdk-linux-x64.zip.zip, and cannot find /home/polar/flutter/bin/cache/dart-sdk-linux-x64.zip.ZIP, period.

I don't what I should to do

**Comment by huycozy** [comment]
@PolarV-UNIX 
It could be due to the network you are using. Please try using another IP or switching to VPN or other settings and see if it helps.

In case you are still facing this issue, you can try [this workaround](https://github.com/flutter/flutter/issues/99890#issuecomment-1068623077):

```
rm -rf /home/polar/flutter/bin/cache
/home/polar/flutter/bin/flutter --version
```

**Comment by PolarV-UNIX** [comment]
Yes I think my network is the main problem because my country is embargo. Thank you for giving me your time.

best regard

**Comment by huycozy** [comment]
@PolarV-UNIX Please try above solutions. If they can fix the issue, feel free to close this. Thanks!

**Comment by PolarV-UNIX** [comment]
thanks I solved
