### ISSUE TITLE
[go_router] How to pop based on defined route

### ISSUE THREAD

**Issue by kashww2** [flutter/flutter#117806]
## Steps to Reproduce
I have this nested pages, and can see a dialog.
I cannot back page1 directly from the dialog after [this PR](https://github.com/flutter/packages/pull/2879).
I need to go back to page2 and then back to the page1.
But in that case, an unnecessary view build runs on page2.
Do we have a way to back page based on defined route?

**Nested page condition**
1: /in defined route(page1)
2. /page2 in defined route(page2)
3. dialog -> Pop

**Expected results:**

- Back to page1 directly from the dialog without unnecessary view build.

**Actual results:** 
- Cannot back page1 directly from the dialog.

**Comment by kashww2** [comment]
I found that we can prevent the unnecessary build by double pop.
So please let me close this ticket.

**Comment by huycozy** [comment]
Hi @kashww2 
Which version did it work before that PR? And what is your current `go_router` version?

Please also provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this. Thanks!

**Comment by kashww2** [comment]
@huycozy 
Thank you for the response!

> Which version did it work before that PR?

```
go_router: ^5.1.10
```
> what is your current go_router version?

```
go_router: ^6.0.0
```

Also this is the flutter condition.
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.10, on macOS 13.0.1 22A400 darwin-x64, locale ja-JP)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] IntelliJ IDEA Community Edition (version 2019.3)
[✓] VS Code (version 1.74.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability
```

> Please also provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this.

This is the reproducible code sample.
```
import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
      title: 'Go router demo',
      routerConfig: router,
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
    );
  }
}

class Page1 extends StatelessWidget {
  const Page1({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text("Page1")),
      body: Center(
        child: TextButton(
          onPressed: () => context.goNamed("page2"),
          child: const Text("Go to page2"),
        ),
      ),
    );
  }
}

class Page2 extends StatelessWidget {
  const Page2({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text("page2")),
      body: Center(
        child: TextButton(
          onPressed: () => _showDialog(context),
          child: const Text("show dialog"),
        ),
      ),
    );
  }

  Future<bool?> _showDialog(BuildContext context) {
    return showDialog<bool>(
        context: context,
        builder: (dialogContex) {
          return AlertDialog(
            alignment: Alignment.center,
            contentPadding:
                const EdgeInsets.symmetric(vertical: 40.0, horizontal: 20.0),
            content: Column(
              crossAxisAlignment: CrossAxisAlignment.center,
              mainAxisSize: MainAxisSize.min,
              children: const [
                Text("dialog"),
              ],
            ),
            actions: [
              TextButton(
                onPressed: () => dialogContex.pop(),
                child: const Text('OK'),
              ),
            ],
          );
        });
  }
}

final router = GoRouter(
  routes: [
    GoRoute(
      path: "/",
      name: "page1",
      builder: (context, state) => const Page1(),
      routes: <GoRoute>[
        GoRoute(
          path: "page2",
          name: "page2",
          builder: (context, state) => const Page2(),
        ),
      ],
    ),
  ],
);

```

**Comment by darshankawar** [comment]
Thanks for the code @kashww2 
What platform are you seeing this behavior on ? I ran the code on mobile and web and observed below:

`Go to Page 2 -> click on show dialog -> press back while dialog is active (?) or click on Ok to close dialog and then click on back`.  What exactly is the step to replicate along with expected behavior ?

**Comment by kashww2** [comment]
> What exactly is the step to replicate along with expected behavior ?

Expected behavior was to back to page1 after `dialogContex.pop()`on dialog.
But sorry for confusing you, actually I can handle this in application code, so please let me close this ticket.
