### ISSUE TITLE
StorkeAlign.outside looks different compared to figma's outside option

### ISSUE THREAD

**Issue by broccolism** [flutter/flutter#117829]
## Use case
Hi! I found something awkward using `StrokeAlign.outside` and `BorderRadius.circular` together.

```dart
 Container(
  ...
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(12),
          border: Border.all(
            strokeAlign: StrokeAlign.outside,
            ...
          ),
        ),
```

As it shows below, rounded border with `StrokeAlign.outside` option doesn't look natural.
I believe any rounded border on everywhere (like normal websites or programs) would be using rounded border as figma does.
![Group 3](https://user-images.githubusercontent.com/45515332/210091357-1d9932e9-1a1a-43e3-ace2-8ab089dd35f4.jpg)

## Proposal

I can draw two circles around the border, inside and outside of the box.
Their radius looks same in Flutter debug mode but I think they need to be different from each other to be natural.

If this feature already fixed or does not happen in release mode, please let me know. I'm using Flutter (Channel stable, 3.3.7)
Thanks for reading!

**Comment by bernaferrari** [comment]
Can you try reproducing on master/beta? I think this was fixed. The API is also now called `BorderSide.strokeAlignOutside`. There were a few big changes that didn't make into the last stable.

**Comment by broccolism** [comment]
@bernaferrari Thanks for reply. I found something very interesting, the error is gone while I didn't do anything special but quit and restart vscode. I didn't event fixed `strokeAlign` to `strokeAlignOutside` nor change flutter's branch.

This is my code... I'm using GetX and `OllyTextButton` is a custom button widget.

```dart
Widget _toiletTypeButton(ToiletType type) {
    return Obx(
      () => Expanded(
        child: OllyTextButton(
          selected: controller.type == type,
          onTap: () {
            controller.selectType(type);
            _scrollController.animateTo(Get.height, duration: const Duration(seconds: 1), curve: Curves.ease);
          },
          label: type.displayName,
        ),
      ),
    );
  }

```

```dart
// OllyTextButton: StatelessWidget

@override
  Widget build(BuildContext context) {
    return GestureDetector(
      onTap: () => onTap(),
      child: Container(
        width: fit == BoxFit.fill ? double.infinity : null,
        padding: _padding(),
        decoration: BoxDecoration(
          color: OllyColors.white,
          borderRadius: BorderRadius.circular(8),
          border: Border.all(
            color: selected ? selectedBorderColor : defaultBorderColor,
            width: selected ? selectedBorderWidth : defaultBorderWidth,
          ),
        ),
        child: Column(
          children: [
            _label(),
            const SizedBox(height: 4),
            _description(),
          ],
        ),
      ),
    );
  }
```

**Comment by bernaferrari** [comment]
Your previous issue was probably related to lerp, something didn't finish.

**Comment by broccolism** [comment]
Okay, I understand. I guess it occurs only in some cases... I remember this option worked normally in previous time.
Should I close this issue or not?

**Comment by bernaferrari** [comment]
You should close, if it happens again reopen.

**Comment by broccolism** [comment]
Okay, thanks for replies!
