### ISSUE TITLE
[url_launcher] Convert to Pigeon

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#117915]
Part of https://github.com/flutter/flutter/issues/117844

- [x] `url_launcher_android` - https://github.com/flutter/packages/pull/4045
- [x] `url_launcher_ios`
- [x] `url_launcher_linux` - https://github.com/flutter/packages/pull/7215
- [x] `url_launcher_macos` - https://github.com/flutter/packages/pull/3686
- [x] `url_launcher_windows`

**Comment by feinstein** [comment]
@stuartmorgan I think my issue https://github.com/flutter/flutter/issues/147909 might be related to this one
