### ISSUE TITLE
When running the integration test on flutter web it's giving minified errors on some widget. The errors does not appear when running in debug

### ISSUE THREAD

**Issue by rutaba1** [flutter/flutter#117961]
I am creating a web app and writing integration tests for it. Everything works fine when I run the app in debug model but when I run integration test, the test fails on a widget and the stack trace of the error is minified.

Here is my code to run integration test:

```
IntegrationTestWidgetsFlutterBinding.ensureInitialized();
  testWidgets("run all tests", (tester) async {
    staffWebApp.main();
    await tester.pumpAndSettle(Duration(seconds: 10));
    
  });
```

Just running the main function is failing the test

```
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  AppConfig.initialize();
  await AppConfig.initializeFirebaseApp();

  var delegate = await LocalizationDelegate.create(
      fallbackLocale: 'en_US', supportedLocales: ['en_US', 'es', 'fa']);

  setPathUrlStrategy();
  setupLocator();
  Intercom.init();
  HotjarService.initHotjar(AppConfig.model.hotJarAppId);
  NotificationService().listenForegroundMessage();

  runZonedGuarded(() async {
    Sentry.init(
      (options) {
        options.release = AppConfig.model.appVersion;
        options.dsn = AppConfig.model.sentryKey;
      },
    );
    await AppData().initAppData(forceRefreshToken: true);
    // Init your App.
    runApp(
      DevicePreview(
        enabled: AppConfig.model.enableDevicePreview,
        builder: (_) => LocalizedApp(
          delegate,
          MyApp(),
        ),
      ),
    );
  }, (exception, stackTrace) {
    Helper.mayBeCaptureSentry(exception, stackTrace: stackTrace);
  });
  OneSignalService().initOneSignal(fromMain: true);
  configLoading();
}
```

The error that I'm getting is minified. And strangely I'm not even on that screen

The following StateError was thrown running a test:
Bad state: No element

When the exception was thrown, this was the stack:
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 266:49  throw_
dart-sdk/lib/_internal/js_dev_runtime/private/js_array.dart 337:5             last]
packages/web_example/views/widgets/staff/staff_details_view.dart.js 61532:41  <fn>
dart-sdk/lib/async/future.dart 424:39                                         <fn>
dart-sdk/lib/async/zone.dart 1383:47                                          _rootRun
dart-sdk/lib/async/zone.dart 1293:19                                          run
dart-sdk/lib/async/zone.dart 1201:7                                           runGuarded
dart-sdk/lib/async/zone.dart 1241:23                                          <fn>
dart-sdk/lib/async/zone.dart 1391:13                                          _rootRun
dart-sdk/lib/async/zone.dart 1293:19                                          run
dart-sdk/lib/async/zone.dart 1225:23                                          <fn>
dart-sdk/lib/_internal/js_dev_runtime/private/isolate_helper.dart 48:19       internalCallback

The test description was:
  run all tests

**Comment by huycozy** [comment]
Hi @rutaba1 
The goal of this Github repo is not to give assistance on personal code or the whole package/plugin project, but to improve flutter reporting bugs or feature requests.

For the issue to be workable, it needs to be reproducible with a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code. Please provide such a sample.

Also, please provide the output of `flutter doctor -v` as well.

Thank you!
