### ISSUE TITLE
Undefined initialization order in display list test

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#117993]
See b/263555200

One of the ASAN errors in that bug is complaining that the statics here: https://github.com/flutter/engine/blob/main/display_list/display_list_test_utils.h#L257 may be initialized before the statics here: https://github.com/flutter/engine/blob/main/display_list/display_list_flags.cc#L83.

I suspect an easy fix may be to use C++ 20 `constexpr` and `constinit`, but I don't know enough about this code to make a specific suggestion. Another solution would be to re-arrange the test to initialize the test data explicitly rather than implicitly as static globals.

This is not high priority unless the DL unit tests start having mysterious flakes due to the compiler initializing the globals in a different order.

cc @flar

**Comment by flar** [comment]
Half of this is addressed in https://github.com/flutter/engine/pull/38649

**Comment by flar** [comment]
constexpr on the display list flags is now merged. Does that resolve the conflict? Or should we do more work on the test_utils variables?

**Comment by chinmaygarde** [comment]
The lines that the links point to have been updated and I am not sure if that means the issue is fixed. Closing this after https://github.com/flutter/engine/pull/38649. We can reopen with updates.
