### ISSUE TITLE
Can we add toString method in very class which can be used by developers ?

### ISSUE THREAD

**Issue by PashwaShah03** [flutter/flutter#117962]

**Comment by PashwaShah03** [comment]
In scaffold, while printing the Scaffold it returns the Object reference number rather than the values of the Scaffold.

**Comment by exaby73** [comment]
All classes by default inherit from `Object` which defines a `toString` method. Not sure what you're asking here, but it's maybe more relevant to raise it in the Dart SDK repository, and not the Flutter one. Closing this issue for the same reason
