### ISSUE TITLE
Flutter- Time Picker selected locale Arabic is not displaying numbers in Arabic.

### ISSUE THREAD

**Issue by jrmahesh1** [flutter/flutter#117958]
In flutter application locale is Arabic, when trying to show the time using Time Picker widget, the numbers in Time Picker is not in Arabic

**Comment by jrmahesh1** [comment]
HI @danagbemava-nc 

Log for flutter doctor -v

[√] Flutter (Channel stable, 3.3.7, on Microsoft Windows [Version 10.0.19044.2364], locale en-US)
    • Flutter version 3.3.7 on channel stable at C:\Users\jrmahesh\Downloads\flutter_windows_2.10.1-stable\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e99c9c7cd9 (10 weeks ago), 2022-11-01 16:59:00 -0700
    • Engine revision 857bd6b74c
    • Dart version 2.18.4
    • DevTools version 2.15.0

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc1)
    • Android SDK at C:\Users\jrmahesh\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.0-rc1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] VS Code (version 1.66.0)
    • VS Code at C:\Users\jrmahesh\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.40.0

[√] Connected device (4 available)
    • M2012K11AI (mobile) • fde562b6 • android-arm64  • Android 11 (API 30)
    • Windows (desktop)   • windows  • windows-x64    • Microsoft Windows [Version 10.0.19044.2364]
    • Chrome (web)        • chrome   • web-javascript • Google Chrome 104.0.5112.102
    • Edge (web)          • edge     • web-javascript • Microsoft Edge 108.0.1462.46

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.



Reproducible Code:

import 'package:flutter/material.dart';
import 'dart:ui' as ui;
import 'package:easy_localization/easy_localization.dart';

class TimePickerExample extends StatefulWidget {
  const TimePickerExample({Key? key}) : super(key: key);

  @override
  _TimePickerExampleState createState() => _TimePickerExampleState();
}

class _TimePickerExampleState extends State<TimePickerExample> {
  TimeOfDay _time = TimeOfDay.now();
  TimeOfDay? picked;
  TimeOfDay? result;

  selectTime(BuildContext context) async {
    bool isRtl = true;
    String? language = "ar-DZ";
    result = await showTimePicker(
        context: context,
        initialTime: _time,
        confirmText: StringKeys.ok.tr(),
        cancelText: StringKeys.cancel.tr(),
        helpText: StringKeys.selectTime.tr(),
        errorInvalidText:StringKeys.timeError.tr(),
        hourLabelText: StringKeys.hour.tr(),
        minuteLabelText: StringKeys.minute.tr(),
        builder: (context, child) {
          return Theme(
            data: Theme.of(context).copyWith(
              colorScheme: ColorScheme.light(primary: Colors.green),
              buttonTheme:
                  const ButtonThemeData(textTheme: ButtonTextTheme.primary),
            ),
            child: MediaQuery(
              data: MediaQuery.of(context).copyWith(
                alwaysUse24HourFormat:
                    MediaQuery.of(context).alwaysUse24HourFormat,
              ),
              child: (language == "ar-DZ")
                  ? child ?? Container()
                  : Localizations.override(
                      context: context,
                      locale: const Locale('en', 'US'),
                      child: Directionality(
                          textDirection: isRtl
                              ? ui.TextDirection.rtl
                              : ui.TextDirection.ltr,
                          child: child ?? Container()),
                    ),
            ),
          );
        });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Time Picker Example"),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            IconButton(
              iconSize: 80,
              icon: Icon(
                Icons.alarm,
                size: 80,
              ),
              onPressed: () {
                selectTime(context);
              },
            ),
            SizedBox(
              height: 60,
            ),
            Text('$_time', style: TextStyle(fontSize: 40)),
          ],
        ), // Column
      ), // Center
    );
  }
}


Screenshot:



![screenshot-1673329135734](https://user-images.githubusercontent.com/121942081/211470638-7841dd36-43c1-4930-aec1-72846891357a.png)



In the above code defined locale is Arabic, if you see in the screenshot, the numbers are not in the Arabic.

**Comment by danagbemava-nc** [comment]
Hi @jrmahesh1, your code sample contains some classes/files that we do not have access to. Kindly provide a self-contained runnable code sample without any third-party packages so that we can investigate this. 

Thank you

**Comment by jrmahesh1** [comment]
Hi @danagbemava-nc ,
The missed file is nothing but strings in keys values format and integrated easy_localization package to reflect strings in locale. please refer this link for more detail https://pub.dev/packages/easy_localization
