### ISSUE TITLE
[Platform.is*] Using of Platform.isAndroid or Platform.isIOS should either be deprecated or documentation should be clear

### ISSUE THREAD

**Issue by AbhishekDoshi26** [flutter/flutter#117992]
We all know that using `Platform.isAndroid` and `Platform.isIOS` crashes on web because these constants lie inside `dart:io` which is not supported for web and many times no one really checks which file was imported due to the usage of something.

But, many less experienced developers keep on using these for multi-platform apps because they are habitual to use it. We already have an alternative i.e. to lay down the if-else such that it checks for web first. Or, we can also use `defaultTargetPlatform == TargetPlatform.android` as this works on all platforms.

I propose either of the following:

- Deprecate Platform.is* so that we don't make silly mistakes
- Properly mention in the documentation that this should not be used in projects with web implementations.

This will really help developers to not make silly mistakes of using `Platform.is*` in multi-platform projects.

Note: Opened similar issue in [dart-lang repo](https://github.com/dart-lang/io/issues/93) too.

**Comment by stuartmorgan** [comment]
Please don't post duplicates of Dart-level issues on the Flutter repository.

Closing as there is no Flutter-level change being requested here.
