### ISSUE TITLE
Flutter kindly asked me to report this error: Bad UTF-8 encoding (U+FFFD; REPLACEMENT CHARACTER) found while decoding string:

### ISSUE THREAD

**Issue by DatabertDuck** [flutter/flutter#117952]
The following is the run window output:

<span style="color: red">This text will be displayed in red</span>
Finished with error: Bad UTF-8 encoding (U+FFFD; REPLACEMENT CHARACTER) found while decoding string: Text before and after the index: >>>nschauen. Bitte nicht lachen �<<<
. The Flutter team would greatly appreciate if you could file a bug explaining exactly what you were doing when this happened:
https://github.com/flutter/flutter/issues/new/choose
The source bytes were:
[84, 101, 120, 116, 32, 98, 101, 102, 111, 114, 101, 32, 97, 110, 100, 32, 97, 102, 116, 101, 114, 32, 116, 104, 101, 32, 105, 110, 100, 101, 120, 58, 32, 62, 62, 62, 110, 115, 99, 104, 97, 117, 101, 110, 46, 32, 66, 105, 116, 116, 101, 32, 110, 105, 99, 104, 116, 32, 108, 97, 99, 104, 101, 110, 32, 239, 191, 189, 60, 60, 60, 10]</span>

I was selecting random words (tokens) in a Corpus (String variable, containing a chat conversation)

The excerpt above: 
"Text before and after the index: >>>nschauen. Bitte nicht lachen �<<<" 
is created with the following print statement:
print("Text before and after the index: >>>${_text.substring(_indexOfWordInOriginalTextBody - 10, _indexOfWordInOriginalTextBody+20)}<<<");

The original line looks like this: 
"Essen Gilmore Girls anschauen. Bitte nicht lachen 😜"

**Comment by danagbemava-nc** [comment]
Hi @DatabertDuck,

Can you please provide your `flutter doctor -v` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?

Please also provide the necessary steps to reproduce. 

Thank you

**Comment by DatabertDuck** [comment]
Hey @danagbemava-nc,
thanks for the quick reply. I have moved on and overwritten the code that I had. I don't necessarily care so much about it anyway. Sorry, this is my first Issue opening ever. So I wasn't expecting to be able to go back and reproduce it. Thought I just might report, because the prompt asked me to. 

I am aware though, that there is a version control system in place. Just not sure, if this is already running in the background of my machine. Definitely not with github yet though. How important is fixing this issue for you? Otherwise you may as well close the ticket. ;) 

Best regards,
Jakob

**Comment by danagbemava-nc** [comment]
> How important is fixing this issue for you?

In an ideal world, we'd like to fix any issues that are reported (if possible), which is why the reproduction case is required. 

You can always file a new issue with the steps to repro if this comes up again so for now, I'll be closing this. 

Thank you
