### ISSUE TITLE
Ambiguous organization in existing files: {com.org1, com.}. The --org command line argument must be specified to recreate project.

### ISSUE THREAD

**Issue by imsahiraf** [flutter/flutter#117968]
Hi,

I am new to this flutter. I had recently started working in this field. I am having one pre-built Application to work on now I am trying to create a web with the existing app but whenever I execute **flutter create .** command, I got below error

`Ambiguous organization in existing files: {com.org1, com.org2}. The --org command line argument must be specified to recreate project.`

Can anyone please help to do some efforts from my side.

Thank you.

**Comment by darshankawar** [comment]
@imsahiraf 


> I am having one pre-built Application to work on now I am trying to create a web with the existing app

Is that a standalone flutter app or an add2app that has native module integrated with Flutter (ex: Android or iOS) ?

Can you also provide `flutter doctor -v` to know which flutter version you are on and the existing app is built on ?

Also checkout [this](https://stackoverflow.com/questions/67317234/ambiguous-organization-in-existing-files-the-org-command-line-argume) SO link and see if it helps in your case.

**Comment by imsahiraf** [comment]
I had just downloaded flutter it is the latest version and configured everything properly and I got the solution too I just have to create the new organization there one more issue I got is of Firebase Option

**Comment by darshankawar** [comment]
Good to know your issue is resolved, closing based on above comment.
