### ISSUE TITLE
mainactivity is never used 

### ISSUE THREAD

**Issue by json1994** [flutter/flutter#117956]
I want implementation a custom function use MethodChannel
see: https://docs.flutter.dev/development/platform-integration/platform-channels, but I notice the mainactivity is never used and 
method of configureFlutterEngine() don't work

**Comment by json1994** [comment]
• Flutter version 3.3.8 on channel stable at D:\Program File\fvm\versions\3.3.8
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 52b3dc25f6 (8 weeks ago), 2022-11-09 12:09:26 +0800
    • Engine revision 857bd6b74c
    • Dart version 2.18.4
    • DevTools version 2.15.0

**Comment by danagbemava-nc** [comment]
Hi @json1994,

Can you please provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we can investigate this?

I've used that document several times and I'm always able to complete the tutorial successfully with fully functioning apps. 

Thank you

**Comment by json1994** [comment]
thank you for you replay, don't know why, my project work fine, the problem  didn't come up

**Comment by json1994** [comment]
> Hi @json1994,
> 
> Can you please provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we can investigate this?
> 
> I've used that document several times and I'm always able to complete the tutorial successfully with fully functioning apps.
> 
> Thank you

thank you for you replay, don't know why, my project work fine, the problem didn't come up
