### ISSUE TITLE
[shared_preferences] Convert to Pigeon

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#117914]
Part of https://github.com/flutter/flutter/issues/117844

- [x] `shared_preferences_android`
- [x] `shared_preferences_ios`
- [x] `shared_preferences_linux` - N/A, Dart-only.
- [x] `shared_preferences_macos` - We should be able to use the same Pigeon definition as `shared_preferences_ios` here, since it's the same underlying API, just a Swift implementation.
- [x] `shared_preferences_windows` - N/A, Dart-only.

**Comment by AmanNegi** [comment]
Hey there I would like to work on the process of converting shared_preferences_android to using Pigeon.
