### ISSUE TITLE
Avoid MissingPluginException by detecting that GeneratedPluginRegistrant is out of sync with pubspec.yaml

### ISSUE THREAD

**Issue by theobouwman** [flutter/flutter#11797]
## Steps to Reproduce

- new flutter project
- add google sign in
- run on iOS

It worked before on iOS.

## Logs

```
MissingPluginException(No implementation found for method init on channel plugins.flutter.io/google_sign_in)
```

## Flutter Doctor

```
[✓] Flutter (on Mac OS X 10.12.5 16F73, locale nl-NL, channel master)
    • Flutter at /development/flutter
    • Framework revision f265301519 (2 days ago), 2017-08-25 17:21:46 -0700
    • Engine revision f5371156d2
    • Tools Dart version 1.25.0-dev.11.0

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.1)
    • Android SDK at /Users/theobouwman/Library/Android/sdk
    • Platform android-26, build-tools 26.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.3.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3.3, Build version 8E3004b
    • ios-deploy 1.9.0
    • CocoaPods version 1.1.1

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Ultimate Edition (version 2017.2)
    • Flutter plugin version 16.0
    • Dart plugin version 172.3317.48

[✓] Connected devices
    • iPhone 6 • 8BD274CA-B00F-46DB-82D6-F1ED0A312D05 • ios • iOS 10.3 (simulator)
```

**Comment by collinjackson** [comment]
I think the underlying issue is that you need to `flutter run` on the command line at least once before building in Xcode, to ensure that `GeneratedPluginRegistrant.m` is updated.

I am testing with the current Flutter master and `google_sign_in: 0.3.1`. If I run `flutter packages get` and then build with Xcode, I get the error you described. If I then `flutter run`, the error goes away.

@theobouwman, can you let me know if `flutter run` resolves your issue? If so, perhaps we should figure out if there's a way we can detect that `GeneratedPluginRegistrant.m` is out of date and show a more informative error message.

/cc @mit-mit

**Comment by grouma** [comment]
Ran into the same issue building for Android on Mac.

1. Create new flutter project
2. Run on Android device through Intellij
4. Update pubspec.yaml to add dependency to sensors plugin
5. Try to run on Android device through Intellij and get MissingPluginException

Resolved by doing a `flutter run` on the command line. This allowed me to run again on Android through Intellij.

**Comment by collinjackson** [comment]
Unassigning myself since I'm not currently working on this. /cc @mravn-google

**Comment by Hixie** [comment]
cc @mit-mit @mravn-google 

Is this a plugin framework maintenance issue that we should fix in the coming months?

**Comment by mit-mit** [comment]
Yes, I think we should.

**Comment by lanle-creates-stuff** [comment]
Does anyone know if a fix for this has been found/made? I'm having a similar issue 
 in xcode - `'google_sign_in/GoogleSignInPlugin.h' file not found` - using '  google_sign_in: "^3.0.0"'. for my flutter project.

**Comment by mravn-google** [comment]
@lanle-creates-stuff Sound more like #15099
