### ISSUE TITLE
Add option for opting out of enter route snapshotting in zoom page transition

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#117917]
This may require a small breaking change to the route settings API. We could potentially CP this but I'll need to investigate first

**Comment by Time1ess** [comment]
IMHO, I wonder if it's OK to add this option to the zoom page transition builder object itself, then we may not need breaking change while enable global opt-out instead of per-page opt-out. E.g

```
const ZoomPageTransitionsBuilder({
  this.enableEnterPageSnapshotting = true,
});

  final bool enableEnterPageSnapshotting;
```

**Comment by jonahwilliams** [comment]
This was done
