### ISSUE TITLE
Error waiting for a debug connection: The log reader stopped unexpectedly Error launching application on I2011. androird 13 not run 

### ISSUE THREAD

**Issue by kapilsharma-gts** [flutter/flutter#117971]
Update came in my mobile yesterday, flutter of android 13 is not running after this update
Running "flutter pub get" in grapic...
Launching lib\main.dart on I2011 in debug mode...
lib\main.dart:1
√  Built build\app\outputs\flutter-apk\app-debug.apk.
Installing build\app\outputs\flutter-apk\app.apk...
this is continous writing

![image](https://user-images.githubusercontent.com/111951967/210585337-ca28bf20-68ec-4e30-976e-dbb7a5f6a142.png)

![image](https://user-images.githubusercontent.com/111951967/210585494-3799133e-a6c4-4668-99fd-97d8d75fc99f.png)

![image](https://user-images.githubusercontent.com/111951967/210585685-01725c96-8719-4c2d-9a8d-a671617090c6.png)

[√] Flutter (Channel stable, 3.3.10, on Microsoft Windows [Version 10.0.19045.2364], locale en-IN)
    • Flutter version 3.3.10 on channel stable at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (3 weeks ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\pc\AppData\Local\Android\Sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = C:\Users\pc\AppData\Local\Android\Sdk
    • ANDROID_SDK_ROOT = C:\Users\pc\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio3\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 3.6)
    • Android Studio at C:\Users\pc\AppData\Local\Android\android-studio
    • Flutter plugin version 49.0.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio3
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] VS Code (version 1.74.2)
    • VS Code at C:\Users\pc\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.27.0

[√] Connected device (4 available)
    • I2011 (mobile)    • 1362242164000MV • android-arm64  • Android 13 (API 33)
    • Windows (desktop) • windows         • windows-x64    • Microsoft Windows [Version 10.0.19045.2364]
    • Chrome (web)      • chrome          • web-javascript • Google Chrome 108.0.5359.125
    • Edge (web)        • edge            • web-javascript • Microsoft Edge 108.0.1462.54

[√] HTTP Host Availability
    • All required HTTP hosts are available

**Comment by darshankawar** [comment]
@kapilsharma-gts 
I am assuming the device `I2011` is Vivo. It seems to be an issue with Vivo make and model running on Android 13 version. So this is not a Flutter specific issue, but an issue with Vivo. See [this](https://github.com/flutter/flutter/issues/117019) similar issue for your reference.
Closing as duplicate.

**Comment by kapilsharma-gts** [comment]
aab kya karna hai android 13 ka
