### ISSUE TITLE
Over 2s per frame on Levono Yoga tablet

### ISSUE THREAD

**Issue by robertgirschick** [flutter/flutter#11794]
Flutter apps work perfectly fine on my current device, a Redmi Note 4 with Android 7. In order to check compatibility I tested them on my low-end Yoga tablet running Android 4.4.2 and got very bad results.

It seems the app freezes for 2 or 3 seconds and then renders all the changes that happened before. Then it stalls again for 2 to 3 seconds and so on. I tried it with the least complex setting possible, a text field and a button, no animation. So it's not a performance issue. It must be a rendering thing. The performance overlay shows appr. 2000 ms/frame. I also tested it with your example apps like Gallery, and also with the published Newsvoice app. Same results.

I know you don't officially support tablets. But I don't see why it's a problem on these devices. After all, the tablet fulfills all requirements for flutter. If I can't be sure flutter works on most tablets (also low-end) it's difficult to use it in production.

Is this a known problem on certain devices or on specific Android versions? Any suggestions how this can be solved?

**Comment by eseidelGoogle** [comment]
Can you provide more information about the device you tested on?  Which Yoga tablet?

When you say the performance overlay showed over 2000ms per frame, was that dominated by the top bar (graphics) or bottom bar (code) time?

**Comment by robertgirschick** [comment]
I tested it on the very first Yoga tablet: [http://www.gsmarena.com/lenovo_yoga_tablet_10-5836.php](http://www.gsmarena.com/lenovo_yoga_tablet_10-5836.php)
Current version: 4.4.2. I took the `flutter create` standard app, no modifications.

It's clearly GPU, not CPU. I made a tracing for pressing the button. This is what happens in the 2 seconds:

![obs](https://user-images.githubusercontent.com/11800804/29771175-bf6d0322-8bf2-11e7-9b1f-8c6f8ed680e0.JPG)

The narrow vertical lines indicate "Frame request pending". Is this of any help?

**Comment by eseidelGoogle** [comment]
FYI @chinmaygarde.

Tablet is from Nov 2013, GPU PowerVR SGX544.

**Comment by chinmaygarde** [comment]
I'll try to get a hold of a similar device.

**Comment by eseidelGoogle** [comment]
This may straight-up be a skia bug, and we can ask @jcgregorio or other Skia folks if PowerVR SGX544 is an already covered config and/or if this is a known slowness on that device class.

**Comment by jcgregorio** [comment]
We have several PowerVR devices on the tree, including the NexusPlayer and the iPhone 6, but we don't have that exact GPU, the SGX544. You should ask on the Flutter/Skia chat so the GPU folks can chime in.

**Comment by bsalomon** [comment]
In the past we've had several different Android devices with PowerVR SGX 54x GPUs in the Skia lab. We had many issues keeping them stable while running our suites of tests due to crashes. When we realized Chrome was blacklisting using Skia's GPU backend on this class of GPUs we stopped testing them.

**Comment by chinmaygarde** [comment]
Looking on Amazon, [this listing](https://www.amazon.com/Lenovo-Yoga-Tab-Processor-ZA0H0022US/dp/B019THTH3A/ref=sr_1_3?ie=UTF8&qid=1503950551&sr=8-3&keywords=lenovo+yoga+10) seems close. I'll place an order if that is faster.

**Comment by eseidelGoogle** [comment]
@bsalomon Flutter currently has no device compatibility list.  We can build one if needed.

**Comment by xnuxer88** [comment]
Hi There,

Currently I have the same problem here.

I've already build flutter apk for release, this is from sample new project flutter increment floating button. But it seem to slow. for first load apps, it takes 7 seconds. for processing increment floating button it takes 3 seconds.

-----
Initializing gradle... 1.6s
Resolving dependencies... 4.5s
Running 'gradlew assembleRelease'...
Skipping AOT snapshot build. Fingerprint match.
Built build\app\outputs\apk\app-release.apk (7.9MB).
-----

I've installed the same installer on Samsung S7, Samsung J3, HTC One it's work fine
same as native speed.

Samsung S7 edge using GPU : Adreno 530 - G9350, Mali-T880 MP12 - G935FD, G935F, G935W8 -> works fine
HTC One using GPU : Adreno 320 -> works fine
Samsung J3 using GPU : Mali-400, Mali-T720 - USA -> works fine
Xiaomi Redmi Note 4 using GPU : Adreno 506 -> works fine
Samsung S4 using GPU : PowerVR SGX544MP3 -> slow
ASUS Zenfone 5 using GPU : PowerVR SGX544MP2 -> the slowest

Is it not solved yet?

Thank You.

**Comment by eseidelGoogle** [comment]
Thank you for the report @xnuxer88!  It looks like this bug was specifically about the Yoga tablet.  It sounds like you've encountered some device-specific performance issues with other devices.

My recommendation would be that we open bugs specific to "Samsung S4 using GPU : PowerVR SGX544MP3" and "ASUS Zenfone 5 using GPU : PowerVR SGX544MP2" and we can work with the Skia GPU team to make sure those GPUs are tested.  I don't know if we have either of those in my team's lab at the moment, but I'm sure we can get some.

Would you be willing to file individual bugs?  We're happy to investigate further, I just worry your comment will get lost at the bottom of this Yoga-specific bug if we don't break it out.

**Comment by xnuxer88** [comment]
@eseidelGoogle 👍 

Hi Eric,

Sure, already issued in 2 new bugs thread.
https://github.com/flutter/flutter/issues/14035
https://github.com/flutter/flutter/issues/14036

Thank You for your response.
Happy to help Flutter team.

**Comment by cbracken** [comment]
It's been 2.5 years since this was filed and we've landed a vast slew of performance updates across the engine since then. @robertgirschick are you still seeing problematic behaviour on the Yoga tablet? If so that would be useful to know. If not, we'll close this issue.
