### ISSUE TITLE
[camera] Convert to Pigeon

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#117905]
Part of https://github.com/flutter/flutter/issues/117844

This is a case where we may want to build more instance-tracking functionality into Pigeon itself before doing a conversion, since we currently use per-instance channels.

- [x] `camera_android`.
- [x] `camera_avfoundation`
- [x] `camera_windows`

**Comment by stuartmorgan** [comment]
@CodeDoctorDE Thanks, I missed the `--dev` flag when adding the dependency. I have a PR up to fix it, and prevent it from happening in the future.

**Comment by stuartmorgan** [comment]
I strongly recommend doing this incrementally, as I did for iOS, given the API surface size. For reference:
- https://github.com/flutter/packages/pull/6553 just converted a single host method, to get all the Pigeon plumbing wired up.
- https://github.com/flutter/packages/pull/6568 just converted the native->Dart calls. (This could easily be split into two PRs, one for global and one for per-camera calls)
- https://github.com/flutter/packages/pull/6601 converted the rest of the host APIs. (This can easily be carved up smaller; just pick one set of methods—or even a single method—migrate those as a PR, repeat.)

**Comment by yaakovschectman** [comment]
@stuartmorgan With this done for `camera_android`, should we close this issue now?

**Comment by stuartmorgan** [comment]
Yes! 🎉
