### ISSUE TITLE
demo_launcher scrolling slow on Galaxy S5

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#118]
<a href="https://github.com/spierce7"><img src="https://avatars.githubusercontent.com/u/871169?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [spierce7](https://github.com/spierce7)**
_Sunday Aug 02, 2015 at 06:44 GMT_
_Originally opened as https://github.com/flutter/engine/issues/423_

----

I've been closely following this project. At the Dart Summit talk, very high performance numbers were shown. When I load the sample app from the play store onto my Galaxy S5, or any of my co-workers devices I see fairly low frame rate. The frame rate is consistent, but it looks to only be around 15-20 fps. (The asteroids game sample appears to have very good frame rate though).

Do the original performance aspirations of 120 fps still seem feasible? Does the team feel there are optimizations that can be done to the current engine to increase the current performance significantly?

**Comment by FlutterIssues** [comment]
<a href="https://github.com/abarth"><img src="https://avatars.githubusercontent.com/u/112007?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [abarth](https://github.com/abarth)**
_Monday Aug 03, 2015 at 16:36 GMT_

----

> Do the original performance aspirations of 120 fps still seem feasible?

Yes.

> Does the team feel there are optimizations that can be done to the current engine to increase the current performance significantly?

Yes.  Currently we are drawing every pixel of every frame from scratch.  We'll eventually cache some pixels and re-use them from previous frames.  We're purposefully waiting to add caching to the graphics pipeline because we want to see how far we can push the system in its current configuration.

**Comment by FlutterIssues** [comment]
<a href="https://github.com/abarth"><img src="https://avatars.githubusercontent.com/u/112007?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [abarth](https://github.com/abarth)**
_Tuesday Aug 04, 2015 at 16:06 GMT_

----

c7f9c68a873dc680f5483f4f157d8091f97f425b should improve scrolling performance on the demo_launcher by 3x.  We'll need to check an S5 with the next release of SkyDemo to see if that fixes this issue.

**Comment by FlutterIssues** [comment]
<a href="https://github.com/abarth"><img src="https://avatars.githubusercontent.com/u/112007?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [abarth](https://github.com/abarth)**
_Thursday Oct 22, 2015 at 23:47 GMT_

----

I believe we scroll much faster than when this issue was filed, so I'm going to mark this issue as fixed.  Thanks!

**Comment by FlutterIssues** [comment]
<a href="https://github.com/spierce7"><img src="https://avatars.githubusercontent.com/u/871169?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [spierce7](https://github.com/spierce7)**
_Thursday Oct 29, 2015 at 23:52 GMT_

----

@abarth You can keep this closed if you want, but scrolling is still pretty laggy on the stock sample with the samsung s5, and also the nexus 5x I just tried it with too. After a while it seems to smooth out, but it takes some time.

**Comment by FlutterIssues** [comment]
<a href="https://github.com/abarth"><img src="https://avatars.githubusercontent.com/u/112007?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [abarth](https://github.com/abarth)**
_Friday Oct 30, 2015 at 00:12 GMT_

----

Ok, I've re-opened this issue.

**Comment by Hixie** [comment]
If it smooths-out after a while, it's probably Dart optimising the code over time.

**Comment by sethladd** [comment]
I just profiled the Stocks app, after a cold start.

Most frames are > 16ms when running in checked mode.

![screen shot 2015-12-11 at 3 50 08 pm](https://cloud.githubusercontent.com/assets/5479/11758383/277115a6-a01f-11e5-8508-ad62021f1e07.png)

In production mode, here's what I see:

![screen shot 2015-12-11 at 3 53 45 pm](https://cloud.githubusercontent.com/assets/5479/11758402/6bec6b40-a01f-11e5-8a51-bc1797f336dc.png)

Many frames are < 16, but you can see some that are bigger than 16.


After warming up the VM (scrolling up and down about 6 times), here's what I see:

![screen shot 2015-12-11 at 3 59 32 pm](https://cloud.githubusercontent.com/assets/5479/11758467/40a47422-a020-11e5-895f-848cae6dddcc.png)


I only see one long frame (oddly, right after I started tracing) and the rest are around 6ms

**Comment by abarth** [comment]
We intentionally do lots of expensive work in checked me to catch errors.  We could have an intermediate mode that had type checking but skipped the expensive checks, but that might just be more complexity.

The cold production mode trace looks pretty typical for our system today.  Background compilation will helpfull remove the green blocks, which is where a lot of the variance is coming from.

The warmed up trace look pretty typically too.  Once the VM warms up, we do a lot better.

Some tips:
- If you select one of the blocks and type "g", you'll get a bunch of vertical red lines spaced at 60 Hz.  That can help you get a sense of scale when looking at traces.
- If you use the `flutter trace` command to generate the traces instead of observatory, you'll also get tracing from the GPU thread, which can help you understand how we're doing on that side as well.

@chinmaygarde is working on getting all the trace events into observatory.  He's got some local patches that make it possible.  I'm not sure what's blocking landing them or what the bug number tracking that work is.

**Comment by chinmaygarde** [comment]
We are tracking this in https://github.com/flutter/flutter/issues/861

**Comment by eseidelGoogle** [comment]
Performance should be *much* better by now.  We also recently introduced --release and --profile modes to `flutter run` and `flutter build`.  Unfortunately they only work on Android built from Linux, but iOS and Android from Mac support should be landing within the next couple days.  Regardless, I would expect these performance concerns to have been addressed in the last 6 months. :)

Please re-open if you don't agree!
