### ISSUE TITLE
getApplicationDocumentsDirectory not working for iOS (but still working for Android)

### ISSUE THREAD

**Issue by dresserm** [flutter/flutter#11803]
Seems to have broken just after running flutter upgrade 

[VERBOSE-2:dart_error.cc(16)] Unhandled exception:
	MissingPluginException(No implementation found for method getApplicationDocumentsDirectory on channel plugins.flutter.io/path_provider)
	#0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:153:7)
	<asynchronous suspension>
	#1      getApplicationDocumentsDirectory (package:path_provider/path_provider.dart:37:40)
...

## Flutter Doctor

[✓] Flutter (on Mac OS X 10.12.6 16G29, locale en-US, channel master)
    • Flutter at /Users/dresserm/Work/flutter
    • Framework revision f235a2c104 (2 hours ago), 2017-08-28 12:50:24 -0700
    • Engine revision f5371156d2
    • Tools Dart version 1.25.0-dev.11.0

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.0)
    • Android SDK at /Users/dresserm/Library/Android/sdk
    • Platform android-26, build-tools 26.0.0
    • ANDROID_HOME = /Users/dresserm/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.3.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3.3, Build version 8E3004b
    • ios-deploy 1.9.1
    • CocoaPods version 1.2.1.beta.1

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.2.2)
    • Flutter plugin version 16.0
    • Dart plugin version 172.3757.55

[✓] Connected devices
    • iPhone SE • F9433213-273B-4984-B0F5-18CE74020947 • ios • iOS 10.3 (simulator)

**Comment by goderbauer** [comment]
@szakarias

**Comment by szakarias** [comment]
Actually all the plugins on iOS were broken because of a bug in `FlutterAppDelegate`. This has been fixed by https://github.com/flutter/engine/pull/4030 .
