### ISSUE TITLE
Recommended approach to use Lottie in Flutter? Skottie?

### ISSUE THREAD

**Issue by Albert221** [flutter/flutter#118093]
Hello, there's this comment from @goderbauer in a thread regarding Skottie, Skia-native Lottie player.

> We don't plan to expose Skottie in Flutter for the time being. The recommended approach to use Lottie in Flutter is the Rive plugin: https://twitter.com/rive_app/status/1169294765625618432

_Originally posted by @goderbauer in https://github.com/flutter/flutter/issues/20438#issuecomment-572310662_
      
But this is not valid anymore, Rive 2 landed a while ago and they removed the support for importing the Lottie files. Does Flutter team has some official or unofficial opinion on what you would consider the recommended approach for vector animations in Flutter?

**Comment by darshankawar** [comment]
@Albert221 
Although I am not sure about recommended approach for vector animations in Flutter, but have you already looked at below community packages and see if they serve your purpose ?

https://pub.dev/packages/lottie
https://pub.dev/packages/animated_svg

**Comment by jonahwilliams** [comment]
We still have no plans to add Skottie to Flutter builds.
