### ISSUE TITLE
MacOS delete file / directory ends up in "OS Error: Permission denied, errno = 13"

### ISSUE THREAD

**Issue by Yetispapa** [flutter/flutter#118056]
## Steps to Reproduce

I'm running a MacOS flutter app under MacOS. I have a button, which calls the following function:

`Directory('~/Library/some-folder').deleteSync(recursive: true);`

**Expected results:** `The files / directory should be deleted`

**Actual results:** an exception: `(OS Error: Permission denied, errno = 13)`

<details>
<summary>Code sample</summary>

In the .entitlements files be sure, to modify:

```
<key>com.apple.security.app-sandbox</key>
<false/>
```

Create a folder called `some-folder` under `~/Library`

Call this code:

`Directory('~/Library/some-folder').deleteSync(recursive: true);`

</details>

<details>
  <summary>Logs</summary>

`FileSystemException: Deletion failed, path = '/Library/some-folder' (OS Error: Permission denied, errno = 13)`

[✓] Flutter (Channel stable, 3.3.10, on macOS 13.1 22C65 darwin-arm, locale en-DE)
    • Flutter version 3.3.10 on channel stable at /Users/my-user/Development/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (3 weeks ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/my-user/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.74.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.56.0

[✓] Connected device (1 available)
    • macOS (desktop) • macos • darwin-arm64 • macOS 13.1 22C65 darwin-arm

[✓] HTTP Host Availability
    • All required HTTP hosts are available

```
```

</details>

Listing like this, works:

`Directory('~/Library/some-folder').listSync(recursive: true, followLinks: false);`

I also played around, by let the user choose the folder, by using this package [here](https://pub.dev/packages/file_picker). But i'm not sure how to implement this actually:

```
<key>com.apple.security.files.user-selected.read-write</key>
<true/>
```

Can someone help me here. If someone know the app [DaisyDisk](https://daisydiskapp.com/), I want to achieve something similar. In their first setup, you also have to choose the drive or drag n' drop it it, in order that DaisyDisk can scan it.

**Comment by exaby73** [comment]
Hello @Yetispapa. This question is better suited for sites like Stackoverflow or you can alternatively find information on https://flutter.dev/community.

Doing a quick search, I think you have to ask for `Full disk access` using native code. See [this thread](https://developer.apple.com/forums/thread/109997). MacOS is denying permission here and that is expected and there is nothing Flutter can do about it. Closing this issue for the above reasons. Thank you

**Comment by Yetispapa** [comment]
Alright. Thanks @exaby73, already found the issue. Has something todo with permission on the folder itself, not, that I can't access it.
