### ISSUE TITLE
iOS startup failure

### ISSUE THREAD

**Issue by yangthree** [flutter/flutter#118083]
I met a very strange problem. I used VSCode to do real iPhone debugging. I keep running errors. But I have no problem running it in Xcode.
My system is MACOS Ventuna and the flutter SDK version is 2.5.3, as shown in the figure below

```
Xcode build done.                                           73.0s
Failed to build iOS app
Error output from Xcode build:
↳
    --- xcodebuild: WARNING: Using the first of multiple matching destinations:
    { platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Any iOS Device }
    { platform:iOS, id:xx, name:iPhone, error:Device is busy (Fetching debug symbols for iPhone, Making iPhone ready for development) }
    { platform:macOS, arch:arm64, variant:Designed for [iPad,iPhone], id:xx }
    { platform:iOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder, name:Any iOS Simulator Device }
    { platform:iOS Simulator, id:xx, OS:16.2, name:iPhone 14 }
    { platform:iOS Simulator, id:xx, OS:16.2, name:iPhone 14 Plus }
    { platform:iOS Simulator, id:xx, OS:16.2, name:iPhone 14 Pro }
    { platform:iOS Simulator, id:xx, OS:16.2, name:iPhone 14 Pro Max }
    { platform:iOS Simulator, id:xx, OS:16.2, name:iPhone SE (3rd generation) }
    { platform:iOS Simulator, id:xx, OS:16.2, name:iPad (10th generation) }
    { platform:iOS Simulator, id:xx OS:16.2, name:iPad Air (5th generation) }
    { platform:iOS Simulator, id:xx, OS:16.2, name:iPad Pro (11-inch) (4th generation) }
    { platform:iOS Simulator, id:xx, OS:16.2, name:iPad Pro (12.9-inch) (6th generation) }
    { platform:iOS Simulator, id:xx, OS:16.2, name:iPad mini (6th generation) }
    ** BUILD FAILED **
Xcode's output:
↳
    /path/plugins/waveform/ios/Classes/SwiftWaveformPlugin.swift:100:29: warning: string interpolation produces a debug description for an optional value; did you mean to make this explicit?
```

**Comment by yangthree** [comment]
I tried this 
flutter clean,flutter pub get,pod install

**Comment by yangthree** [comment]
also, i have met this:
FormatException: Missing extension byte (at offset 74)

**Comment by yangthree** [comment]
anyone help me 😭😭😭😭😭😭😭😭😭

**Comment by danagbemava-nc** [comment]
Hi @yangthree, flutter 2.5.3 is an old version of flutter for which support is no longer provided. 

Kindly upgrade to the latest version of flutter stable (3.3.10) and do make sure that all your project dependencies and try again to see if you still experience the issue. 

If you do, please provide the update output of `flutter doctor -v` along with the following information 
- Your pubspec.yaml & pubspec.lock
- Your Podfile & Podfile.lock
- The output of `flutter run -v` (the output may be huge, so kindly put it into a .txt or .log file and attach it here)

Thank you

**Comment by yangthree** [comment]
Thank you for your reply! But the company is not allowed to upgrade the flutter SDK.

**Comment by danagbemava-nc** [comment]
Please provide the following information

- Your pubspec.yaml & pubspec.lock
- Your Podfile & Podfile.lock
- The output of flutter run -v (the output may be huge, so kindly put it into a .txt or .log file and attach it here)

Thank you

**Comment by yangthree** [comment]
I finally solved it! It's me. I ran the wrong folder.
