### ISSUE TITLE
How to debug native code ?

### ISSUE THREAD

**Issue by SuganyaRajendran0207** [flutter/flutter#118038]
My Question is really simple but couldn't find the answer so far!!

I have a flutter application and I wrote a new viewcontroller in ios platform

I opened the viewcontroller using `MethodChannel` from flutter

The Problem is I couldn't debug the viewcontroller that I wrote

In Android I can successfully debug by

    Run Debug in Android Studio
    Then Attach debugger to the app 
  
But in iOS I could not debug

    Run Debug in Android Studio
    Then I can't attach debugger option in XCode, There is no option available!
    
Any Help is appreciated and I couldn't find answer in Stackoverflow too!!

**Comment by balaji101010** [comment]
Yes I am facing the same issue 
Don't know how to debug in Xcode
As you said I can debug the android code

**Comment by balaji101010** [comment]
The Flutter team should give proper example about how to debug native code!

**Comment by darshankawar** [comment]
@SuganyaRajendran0207 
Can you check [this](https://stackoverflow.com/questions/52770209/how-to-debug-ios-native-code-in-a-flutter-plugin) link and see if it answers your question ?

**Comment by SuganyaRajendran0207** [comment]
kind of helps! thanks
we need to run the project directly from Xcode in order to debug!!
