### ISSUE TITLE
Unable to install CocoaPods

### ISSUE THREAD

**Issue by lukeirvin** [flutter/flutter#118050]
My project has recently stopped working.

I'm getting numerous messages like this:

`The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 9.0, but the range of supported deployment target versions is 11.0 to 16.2.99. (in target 'FirebaseCrashlytics' from project 'Pods')`

I've tried deleting the Podflie.lock & then re-instaling using `arch -x86_64 pod install` & I'll see this at the top:

`Writing result bundle at path:
    	/var/folders/f8/xmd2p83n0gjbk29mcqzxxmv00000gn/T/flutter_tools.pnHGn1/flutter_ios_build_temp_dirqnUU9P/temporary_xcresult_bundle
: Error: Member not found: 'FirebaseAppPlatform.verifyExtends'.
../…/src/firebase_app.dart:18
        FirebaseAppPlatform.verifyExtends(_delegate);
                            ^^^^^^^^^^^^^`

I'm at a loss on what else to try.

My Flutter Doctor:

`flutter doctor -v`:
[flutter] flutter doctor -v
[✓] Flutter (Channel stable, 3.3.10, on macOS 13.1 22C65 darwin-arm, locale en-US)
    • Flutter version 3.3.10 on channel stable at /Users/lukeirvin/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (3 weeks ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/lukeirvin/Library/Android/sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.74.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.56.0

[✓] Connected device (3 available)
    • iPhone 14 Pro Max (mobile) • 9264C232-AB9C-49BD-9CBE-A80FA501866B • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-2 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 13.1 22C65 darwin-arm
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 108.0.5359.124

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Comment by darshankawar** [comment]
> The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 9.0, but the range of supported deployment target versions is 11.0 to 16.2.99. (in target 'FirebaseCrashlytics' from project 'Pods')

@lukeirvin This message indicates you need to update your `minimum deployment target` from Xcode to the required value, ie, to `11.0` which should resolve this error.



> Writing result bundle at path: /var/folders/f8/xmd2p83n0gjbk29mcqzxxmv00000gn/T/flutter_tools.pnHGn1/flutter_ios_build_temp_dirqnUU9P/temporary_xcresult_bundle : Error: Member not found: 'FirebaseAppPlatform.verifyExtends'. ../…/src/firebase_app.dart:18 FirebaseAppPlatform.verifyExtends(_delegate); ^^^^^^^^^^^^^

Regarding this error, you'll need to upgrade all of your flutterfire plugins you are using, to the latest and greatest version.
See [this](https://github.com/firebase/flutterfire/issues/9806) similar issue for your reference.

Closing this issue, as this is not a framework bug but a setup issue at your end.
