### ISSUE TITLE
FlatButton has no debugFillProperties

### ISSUE THREAD

**Issue by lishuhao** [flutter/flutter#11808]
```
Widget widget = new FlatButton(
          onPressed: (){}, 
          child: new Text('你好')
);
print(widget);
```
In console only print `FlatButton`，i want detailed widget information ,like this `FlatButton(
          onPressed: (){}, 
          child: new Text('你好')
)`

**Comment by Hixie** [comment]
This just needs a debugFillProperties method to be implemented on FlatButton.

**Comment by Hixie** [comment]
@lishuhao To answer your question, for most objects in our framrwork just printing the object (e.g. a widget or BuildContext) should do what you want. You can often also do `print('${object.toStringDeep()}');` to get the whole subtree. For FlatButton we happen to have forgotten to implement the code that gives you specific details.

**Comment by lishuhao** [comment]
@Hixie That solved my problem. Thank you very much!!

**Comment by jonahwilliams** [comment]
This looks to be fixed, can this issue be closed?

**Comment by Hixie** [comment]
Yup!
