### ISSUE TITLE
Issue from website page 表单 Widgets点击进入详情页面404

### ISSUE THREAD

**Issue by 1335098094** [flutter/flutter#118085]
From URL: https://www.flutterchina.club/widgets/input.md

**Comment by danagbemava-nc** [comment]
Hi @1335098094, The issue you are referring to belongs to the flutter china website which must be filed here [flutterchina/website/issues](https://github.com/flutterchina/website/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc)

The flutterchina website is maintained by members of the flutterchina community, not the flutter org.

Closing as the issue doesn't belong to this repo.

Thanks
