### ISSUE TITLE
Trackpad scrolling when mouse is down on web throws an assertion

### ISSUE THREAD

**Issue by moffatman** [flutter/flutter#118051]
1. Run any flutter app on web since https://github.com/flutter/engine/pull/36346
2. Start a one-finger drag on the trackpad
3. Put a second finger on the trackpad to start scrolling
4. If this is done fast enough, it will cause an assertion failure

See https://github.com/flutter/flutter/issues/117881#issuecomment-1369438709 for log

The root cause is that the trackpad events are sent with the same device ID as mouse events (`_mouseDeviceId = -1`), so if a trackpad scroll begins when the pointer is down, a `PointerMoveEvent` might be synthesized if the location has changed (moving fast enough). 

A different device ID should be used for trackpad events, this is what's been done on other platforms (`_trackpadDeviceId = -2`?).

**Comment by yjbanov** [comment]
cc @Piinks
