### ISSUE TITLE
WebGL: INVALID_OPERATION: delete: object does not belong to this context when hot-reloading

### ISSUE THREAD

**Issue by twoco** [flutter/flutter#118020]
Just a minor issue. Not sure if this is critical now or later.

## Steps to Reproduce

1. Create a new Flutter project.
2. Choose Chrome as debug device.
3. Play around. See on browsers console. (maybe only on save/auto-reload)

**Expected results:**
No warning on console.

**Actual results:**
The warning appears mulitple times on console. It seems this only happens when app hot reloads.

> WebGL: INVALID_OPERATION: delete: object does not belong to this context (canvaskit.js:231)

No demo / minimal project required. Just start a new project. There are no changes made. I just moved the home page to a new file. But this is meaningless.

I have found another issue about that (#112467) but won't help. The guy wrote that it was his fault, not flutter. But I doubt it. Don't sure what he mean with "data" in this context. I've just created a fresh new project on a fresh installed OS and fresh installation of Chrome.

Windows 11 Pro 22H2
VS Code 1.74.2
Flutter 3.3.10
Chrome 108.0.5359.125

**Comment by danagbemava-nc** [comment]
Hi @twoco, does this issue always reproduce, or is it intermittent? 

Can you also share a recording of how you reproduce the issue and the full error logs? 

Thank you

**Comment by twoco** [comment]
I can always reproduce it. I don't think that a record helps in this case. And I have no error log. The error occurs only on Chrome. It's maybe a (security) change of the browser. Maybe something set to deprecated and should be changed in the future.

### Steps to Reproduce

Below I describe my case. The most important things are running Flutter project in Chrome. 

1. Check/Update your Software. See "Test Environment" below.
2. Create a new Flutter project. (Existing project may also work.)
3. Select "Chrome (web-javascript)" as debug device and run the project (F5 in VS Code).
4. Wait  until it's fully loaded and open the browser dev tools console.
5. Go back to your project and save the project to trigger hot reload. (CTRL + S)
6. Take a look to the browser console. You should now see the warning. It appears on every reload.
7. A hard-reload removes the warning. It only appears on hot reload. 

### Result

On `CTRL + S`:

> WebGL: INVALID_OPERATION: delete: object does not belong to this context (canvaskit.js:231)

![screenshot_console](https://user-images.githubusercontent.com/53160891/210881501-2541863c-771c-43f5-8d60-60009aa0ac61.png)


### Test Environment

Windows 11 Pro 22H2
VS Code 1.74.2
Flutter 3.3.10
Chrome 108.0.5359.125

Maybe the OS and IDE doesn't matter. You only need the latest Flutter and Chrome browser.

### Additional Information

Searching the web with this warning message brought me more information:
I found another Flutter issues (may not be related): #91881

There are also other threads on various forums. But I haven't found any official documentation about it yet.

It's the Flutter [CanvasKit](https://github.com/flutter/engine/tree/main/lib/web_ui/lib/src/engine/canvaskit) at methods like `deleteProgram`, `deleteBuffer` and `deleteFramebuffer`. I'm not sure (no experience in WebGL), the warning message is about doing delete objects which do not belong to the current context. What does this mean? Keeping context where the objects were created? For these delete methods? Maybe related to [Skia](https://skia.org/)? This is the lib behind, isn't it?

**Comment by danagbemava-nc** [comment]
Hi @twoco, thanks for the detailed info. I am able to reproduce this on the stable branch. However, when I attempt to reproduce this on the master branch, I see the error below(it sort of comes in a flash, I had to use VLC to see the error properly). 
Do you see the same thing on the master channel?

```
Error during script reloading. Firing full page reload. HotReloadFailedException: 'Mismatched anonymous define() module: function() { return CanvasKitInit; }' http://requirejs.org/docs/errors.html#mismatch'
```
