### ISSUE TITLE
`Theme.TimePickerThemeData.dayPeriodShape`'s `side.color` is NOT being respected

### ISSUE THREAD

**Issue by gintominto5329** [flutter/flutter#118036]
**Steps to Reproduce**

1. Open  [dartpad.dev](https://dartpad.dev/).
2. Copy-paste, the code sample.
3. Notice the results. 

**Expected results:**
The border color, of day period chooser (of the `TimePickerDialog`), should be red.

**Actual results:**
The color is white.

**Sample code**:
```dart
import "package:flutter/material.dart";

void main() {
  runApp(MaterialApp(
    home: MyApp(),
  ));
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final DateTime dateTime = DateTime.now();

    return Scaffold(
      body: Theme(
        data: ThemeData(
          timePickerTheme: const TimePickerThemeData(
            shape: RoundedRectangleBorder(
              side: BorderSide(
                color: Colors.red,
              ),
              borderRadius: BorderRadius.all(Radius.circular(16)),
            ),
            hourMinuteShape: RoundedRectangleBorder(
              side: BorderSide(
                color: Colors.red,
              ),
              borderRadius: BorderRadius.all(Radius.circular(12)),
            ),
            dayPeriodShape: RoundedRectangleBorder(
              side: BorderSide(
                color: Colors.red,
              ), // not work
              borderRadius: BorderRadius.all(Radius.circular(8)),
            ),
          ),
        ),
        child: MediaQuery(
          data: MediaQuery.of(context).copyWith(
            alwaysUse24HourFormat: false,
          ),
          child: TimePickerDialog(
            initialTime: TimeOfDay(
              hour: dateTime.hour,
              minute: dateTime.minute,
            ),
          ),
        ),
      ),
    );
  }
}
```

Thanks,

**Comment by darshankawar** [comment]
Thanks for the report @gintominto5329 
If you use `dayPeriodBorderSide`, then I think it works as expected:

```
dayPeriodBorderSide: BorderSide(
              color: Colors.red
            )
```

<img width="260" alt="Screenshot 2023-01-06 at 12 12 04 PM" src="https://user-images.githubusercontent.com/67046386/210945223-0f44d1be-70b6-4900-92a2-55f6732c2218.png">

Can you try the same and see if it serves your purpose ?

**Comment by gintominto5329** [comment]
Thanking you, working great now,

but I think 
```
dayPeriodBorderSide: BorderSide(
              color: Colors.red
            )
```
should be depreciated, in favor of
```
dayPeriodShape: RoundedRectangleBorder(
              side: BorderSide(
                color: Colors.red,
              ), // not work
            ),
```

So, may i have this issue converted, into a feature request for the same

**Comment by darshankawar** [comment]
Good to know the solution works for you.

> should be depreciated, in favor of

I am not sure if it would be feasible to deprecate that property, because looking  at both properties documentation, it serves different purpose:

1. `dayPeriodShape`: https://api.flutter.dev/flutter/material/TimePickerThemeData/dayPeriodShape.html  - it works on the shape of the day period that the time picker uses.
2. `dayPeriodBorderSide` : https://api.flutter.dev/flutter/material/TimePickerThemeData/dayPeriodBorderSide.html - it works on the color and weight of the day period's outline.

Let me know if above makes sense and serves your purpose.
