### ISSUE TITLE
FrameTiming of raster is not very accurate some time

### ISSUE THREAD

**Issue by luckysmg** [flutter/flutter#118088]
The DevTools can't not show correct frame histogram and also `SchedulerBinding.instance.addTimingsCallback` report is not correct when `auto frame = surface_->AcquireFrame(layer_tree.frame_size());` takes much time.

But Android studio intellj plugin can show correct things(When AS plugin show red frames, I can see the junk visually).

See also:
- https://github.com/flutter/flutter/issues/103847#issuecomment-1128242051
- https://github.com/flutter/flutter/issues/103847#issuecomment-1241560625
- https://github.com/flutter/flutter/issues/115036#issue-1442955963

https://user-images.githubusercontent.com/49340347/210971082-6fc1c547-7c08-4ace-a8a2-2f57d97b6402.mp4

**Comment by iapicca** [comment]
may affect 
- https://github.com/flutter/flutter/issues/115561

**Comment by luckysmg** [comment]
Fixed by https://github.com/flutter/engine/pull/38674.
