### ISSUE TITLE
Codelab mistake

### ISSUE THREAD

**Issue by leoybkim** [flutter/flutter#11801]
Building Beautiful UIs with Flutter Codelab, on page [5. Add a UI for composing messages](https://codelabs.developers.google.com/codelabs/flutter/#4), very last paragraph

> Practice using the debugger by setting breakpoints on the setState() methods in your Friendlychat app, then run and debug the app. You can inspect the stack frames to see the history of method calls by your app.

Need to change `setState()` to `createState()`

**Comment by Hixie** [comment]
Why?

**Comment by leoybkim** [comment]
Hi Hixie, 
I was following the tutorial from the beginning. `setState()` was not yet introduced anywhere in main.dart.  at that point in tutorial timeline. I believe it was referring to `createState()`, which was added in earlier steps. This is not an err in code but simply a typo.

**Comment by Hixie** [comment]
Ah, I see. Maybe it should say `build()` methods. Setting the breakpoint on `createState()` doesn't seem very helpful (that gets called from deep in the bowels of the framework and doesn't do anything particularly noteworthy in your code).

**Comment by Hixie** [comment]
cc @LarkAscending

**Comment by LarkAscending** [comment]
Thanks @leoybkim for finding this artifact leftover from an earlier version of the codelab. And @Hixie, for the suggested remedy.

https://codelabs.developers.google.com/codelabs/flutter/#0
has this change, and other updates as well. PTAL!
