### ISSUE TITLE
PageView is missing on the widget catalog scrolling page

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#11800]
From URL: https://flutter.io/widgets/scrolling

PageView missing.
https://docs.flutter.io/flutter/widgets/PageView-class.html

**Comment by LarkAscending** [comment]
Maybe PageView-class needs the category "Scrolling" assigned?

**Comment by zoechi** [comment]
Issue moved to [flutter/website #1857](https://github.com/flutter/website/issues/1857) via [**ZenHub**](https://www.zenhub.com/)
