### ISSUE TITLE
Problem with guesture detector

### ISSUE THREAD

**Issue by Wissperwind** [flutter/flutter#118097]
There might be a problem with the GuestureDetector on the curret version on master.
It misses a mouse cklick.
The problem was not present using the current version on stable.

I noticed the problem on flutter web using the library https://pub.dev/packages/textfield_search
I was not able to click on search results the showed up once I searched something in the textfield.

```
    const label = "Some Label";
    const dummyList = ['Item 1', 'Item 2', 'Item 3', 'Item 4', 'Item 5'];
    TextEditingController myController = TextEditingController();
    MaterialApp(
      home: Scaffold(
      body: TextFieldSearch(initialList: dummyList, label: label, controller: myController)
      ),
    )
```

Please verify that the GuestureDetector is working like intended.

**Comment by huycozy** [comment]
@Wissperwind 
For the issue to be workable, it needs to be reproducible with a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code. Please provide such a sample. Thanks!
