### ISSUE TITLE
[Add2App] by pass touch event to parent when use FlutterFragment 

### ISSUE THREAD

**Issue by dodatw** [flutter/flutter#118080]
We are trying to replace some functionality on our existing app with flutter.
I want to put `FlutterFragment` on top of other views in my activity and try to replace UI components gradually from native to flutter.

We follow step in https://docs.flutter.dev/development/add-to-app/android/add-flutter-fragment and set transparent `FlutterFragment`.

But the problem is, the touch event cannot pass from `FlutterFragment`.

What I want: If no widgets handle touch events in `FlutterFragment`, it will pass the events to parent / native layer.

Can we provide this mode for `FlutterFragment`?

We tried to integrate PlatfromView before, but PlatfromView have some limitation.
1. Cannot handle Fragments https://github.com/flutter/flutter/issues/36781
2. Android 9 and above have poor performance.

**Comment by exaby73** [comment]
Hello @dodatw. Can you provide a code sample in the form of a public repo so that I may verify the behavior?
