### ISSUE TITLE
Support cross-platform network debugging

### ISSUE THREAD

**Issue by johnpryan** [flutter/flutter#11804]
Facebook has created a tool that hooks into Chrome's devtools protocol for Android: https://github.com/facebook/stetho

It would be great to have a similar tool for network debugging that works cross-platform (like Observatory)

**Comment by eseidelGoogle** [comment]
FYI @mit-mit @zanderso 

Currently we intentionally call through to the platform networking layers. But I could imagine someone interposing above the dart:io layer to provide debugging hooks to some host-based tool like the Chrome Dev Tools.

**Comment by Hixie** [comment]
@collinjackson says he has a workaround in the meantime that he'll describe here

**Comment by collinjackson** [comment]
Here is a sketch of how you could add a hook by overriding `createHttpClient`.

```
import 'package:flutter/services.dart' show createHttpClient;
import 'package:http/http.dart';
```
...
```
  final oldCreateHttpClient = createHttpClient;
  createHttpClient = () => new _MyHttpClient(oldCreateHttpClient());
```
...
```
/// Wraps a BaseClient with custom logging
class _MyHttpClient extends BaseClient {
  _MyHttpClient(this._inner);

  final Client _inner;

  @override
  Future<StreamedResponse> send(BaseRequest request) async {
    // Log the request here
    try {
      final StreamedResponse response = await _inner.send(request);
      // Log the response here
    } catch (error) {
      // Log the error here
    }
  }
}

**Comment by jonahwilliams** [comment]
This is going to be supported by devtools, and is tracked at flutter/devtools
