### ISSUE TITLE
 CameraException(error, Attempt to invoke virtual method 'java.util.List android.media.EncoderProfiles.getVideoProfiles()' on a null object reference)

### ISSUE THREAD

**Issue by LEHOANGLONG0807** [flutter/flutter#118079]
Bug: 
 CameraException(error, Attempt to invoke virtual method 'java.util.List android.media.EncoderProfiles.getVideoProfiles()' on a null object reference)
 
 Flutter version 3.3.8
 Android 13

**Comment by danagbemava-nc** [comment]
Closing this as a duplicate of https://github.com/flutter/flutter/issues/109769. 

Kindly follow up in the issue linked above for updates. 

Thank you
