### ISSUE TITLE
The comment of the CircularProgressIndicator.adaptive() is misleading.

### ISSUE THREAD

**Issue by IsseiKanda** [flutter/flutter#118144]
Here's a comment of the CircularProgressIndicator.adaptive()

 ```
  /// Creates an adaptive progress indicator that is a
  /// [CupertinoActivityIndicator] in iOS and [CircularProgressIndicator] in
  /// material theme/non-iOS.
  ///
  /// The [value], [backgroundColor], [valueColor], [strokeWidth],
  /// [semanticsLabel], and [semanticsValue] will be ignored in iOS.
  ///
  /// {@macro flutter.material.ProgressIndicator.ProgressIndicator}
  const CircularProgressIndicator.adaptive({
    super.key,
    super.value,
    super.backgroundColor,
    super.valueColor,
    this.strokeWidth = 4.0,
    super.semanticsLabel,
    super.semanticsValue,
  }) : _indicatorType = _ActivityIndicatorType.adaptive;
```

I noticed that comment says that 

 /// The [value], [backgroundColor], [valueColor], [strokeWidth],
 /// [semanticsLabel], and [semanticsValue] will be ignored in iOS.

but it is actually not true. The backgroundColor changes the color of the CircularProgressIndicator in IOS.
This comment is misleading so it should be changed.

## Steps to Reproduce

1. Execute `flutter run` on the code sample 

**Expected results:** 

CircularProgressIndicator with no backgroundColor

**Actual results:** 

CircularProgressIndicator with a red backgroundColor

<details>
<summary>Code sample</summary>

```
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({super.key});

  @override
  Widget build(BuildContext context) {
    return const Scaffold(
      body: Center(
          child: CircularProgressIndicator.adaptive(
        backgroundColor: Colors.red,
      )),
    );
  }
}

```
</details>

![Simulator Screen Shot - iPhone 14 - 2023-01-08 at 03 01 00](https://user-images.githubusercontent.com/61398284/211164415-39e6f9df-1f49-4eb0-985d-419ac861ba39.png)

**Comment by darshankawar** [comment]
Thanks for the report. Using below code sample, the listed property values are rendered for `CircularProgressIndicator`:

<img width="128" alt="Screenshot 2023-01-09 at 1 20 32 PM" src="https://user-images.githubusercontent.com/67046386/211261618-ce6af033-6041-4095-bc56-c63dd089e095.png">

```
body: Center(
          child: CircularProgressIndicator(
            backgroundColor: Colors.blue,
            value: 0.5,
            valueColor: AlwaysStoppedAnimation(Colors.green),
            strokeWidth: 50,
          ),
      ),
```

For `CircularProgessIndicator.adaptive()`, though, except `backgroundColor`, all other properties don't render:

<img width="85" alt="Screenshot 2023-01-09 at 1 20 49 PM" src="https://user-images.githubusercontent.com/67046386/211261791-de789ba1-39ca-4b0a-9565-3fdfb363f270.png">


Maybe a similar fix needed: https://github.com/flutter/flutter/pull/81427

/cc @darrenaustin

**Comment by IsseiKanda** [comment]
Thank you for confirming the feature. I don't know if it's an expected feature but being able to change the `backgroundColor` is useful for my case.
