### ISSUE TITLE
webview (can not to load webview in android device)

### ISSUE THREAD

**Issue by emanuelzallikodelabs** [flutter/flutter#118174]
webview_flutter 4.0.1
I can not load web view just on an Android device, iOS works fine, and my code is the same as a library example.
The error I get is:

I/flutter (23989): Page resource error:
I/flutter (23989):   code: -1
I/flutter (23989):   description: net::ERR_FAILED
I/flutter (23989):   errorType: WebResourceErrorType.unknown
I/flutter (23989):   isForMainFrame: false

[✓] Flutter (Channel stable, 3.3.10, on macOS 13.1 22C65 darwin-arm, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] Android Studio (version 2021.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2022.3.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2022.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2022.3.1)
[✓] Connected device (4 available)
[✓] HTTP Host Availability

• No issues found!

**Comment by danagbemava-nc** [comment]
Hi @emanuelzallikodelabs, do you have this issue visiting a particular page or do you face this issue on any page you visit?

What device are you experiencing this issue on and what version of android is it running?

Please also provide the full code sample you're using as well as the version of `webview_flutter_android`.

Thank you
