### ISSUE TITLE
dependencies many not good 

### ISSUE THREAD

**Issue by dd9913762113** [flutter/flutter#118131]
dependencies many not good 
if u had many dependencies
how to update?
like this one ：

```
Running "flutter pub get" in ...                             
Because xml >=6.2.0 depends on petitparser ^5.1.0 and xml >=5.4.0 <6.2.0 depends on petitparser ^5.0.0, xml >=5.4.0 requires petitparser ^5.0.0.
And because webdav_client >=1.1.8 depends on xml ^6.1.0 and json_path ^0.3.0 depends on petitparser ^4.0.0, webdav_client >=1.1.8 is incompatible with json_path ^0.3.0.
So, because  depends on both json_path ^0.3.0 and webdav_client ^1.1.8, version solving failed.
pub get failed (1; So, because eso depends on both json_path ^0.3.0 and webdav_client ^1.1.8, version solving failed.)
``` 

why do not do a dependency only in  own  dependencies libraries ? 

flutter support iOS Android Windows MacOS Linux Web and so on 
but many many  libraries 
it is difficult for use or update
it is not for low version to update to high version

**Comment by stuartmorgan** [comment]
For help with your own project, try one of the resources at https://flutter.dev/community#community-grid

Closing as dependency conflicts are a project-level issue, not a Flutter bug.
