### ISSUE TITLE
Add Rust Support to Pigeon

### ISSUE THREAD

**Issue by cmedamine** [flutter/flutter#118149]
## Problem

As of the current version of Pigeon, there is no official support for Rust. This limits the ability of developers to use Rust in Flutter projects and integrate Rust code with Flutter using Pigeon.

## Solution

We request that the Flutter team consider adding support for Rust to the Pigeon package. This would allow developers to use Rust in their Flutter projects and easily communicate between Rust and Flutter using Pigeon.

## Benefits

- Rust is a popular and powerful programming language that is well-suited for systems programming and offers many benefits such as memory safety and concurrency support.
- Adding Rust support to Pigeon would enable developers to build more performant and reliable Flutter apps.
- Rust support in Pigeon would open up new possibilities for integrating Rust code into Flutter projects.

## Additional Context

We would be happy to help test and provide feedback on any Rust support implementation in Pigeon.

**Comment by stuartmorgan** [comment]
> We request that the Flutter team consider adding support for Rust to the Pigeon package.

It's not clear to me what this means. Pigeon generates convenience wrappers for Flutter's method channel system, and Flutter method channels don't support Rust. Is this request related to a third-party embedding? Please provide a link to an example of existing hand-authored code that you would want to replace with Pigeon-generated code.

**Comment by cmedamine** [comment]
Thank you for your response. Rust support in Pigeon would allow developers to use Rust code in Flutter projects and easily communicate between Rust and Flutter using Pigeon's method channel system.

As an example, consider a Flutter app that needs to perform some computationally intensive tasks, such as image processing or data analysis. Rust is a great choice for these types of tasks because it offers strong performance and concurrency support. However, integrating Rust code into a Flutter project can be challenging because of the language barrier and the need to use platform channels to communicate between the two languages.

Pigeon can help simplify this process by generating the necessary wrappers and bridging code for communicating between Rust and Flutter. This would allow developers to write Rust code and use it seamlessly in their Flutter projects, without having to manually handle the communication between the two languages.

I hope this provides a better understanding of the potential benefits of Rust support in Pigeon and how it could be used in real-world projects. Let me know if you have any further questions or need more information.

**Comment by stuartmorgan** [comment]
> However, integrating Rust code into a Flutter project can be challenging because of the language barrier and the need to use platform channels to communicate between the two languages.

There's no way to directly use platform channels between Dart and Rust, which is why I'm not clear what exactly you are requesting.

(Also, you can call directly into Rust code via FFI, so there isn't a "need to use platform channels" in general.)

> Pigeon can help simplify this process by generating the necessary wrappers and bridging code for communicating between Rust and Flutter.

As I requested above: please provide a concrete example of existing code that you envision being replaced with Pigeon-generated output, so that is clear what exactly you are expecting such a generator to do.

> I hope this provides a better understanding of the potential benefits of Rust support in Pigeon

What I'm asking for isn't a high-level goals description or motivation; I'm trying to pinpoint the details of what **exactly** you would expect this generator to do (given that what the existing generators do isn't applicable to Rust).

**Comment by cmedamine** [comment]
Thank you for your suggestion to consider using FFI instead of Pigeon for integrating Rust code into our Flutter app. While FFI can be a useful solution for integrating a small number of Rust functions into a Flutter app, I believe that Pigeon offers a number of benefits that make it a better choice for many use cases.

One of the main benefits of Pigeon is that it simplifies the process of communicating between Flutter and Rust. With Pigeon, we can avoid having to manually handle the communication between the two languages and instead use generated code to easily call Rust functions from Flutter and vice versa. This can save us a significant amount of development time and effort, and make it easier to maintain and update our codebase.

Pigeon also provides a number of advanced features that can be useful when integrating Rust code into a Flutter app. For example, Pigeon supports bidirectional communication, which allows Rust code to call Flutter code and vice versa. This can be useful for tasks such as updating the UI or passing data between the two languages. Pigeon also provides error handling and automatic serialization and deserialization of data, which can further simplify the process of communicating between Flutter and Rust.

Finally, Pigeon has a growing ecosystem and community, with a number of libraries and tools available for building Flutter apps with Rust. This can make it easier to develop and maintain our app using Rust and Pigeon.

Overall, I believe that the benefits of using Pigeon outweigh the benefits of using FFI for many use cases, and I hope that the Flutter team will consider adding Rust support to Pigeon.

**Comment by stuartmorgan** [comment]
> For example, Pigeon supports bidirectional communication, which allows Rust code to call Flutter code and vice versa.

Platform channels provide bidirectional communication. Pigeon generates wrapper code to simplify use of platform channels it does not itself provide any communication functionality.

> Pigeon also provides error handling and automatic serialization and deserialization of data

Those are also platform channel features, which Pigeon is generating utility code around.

> I hope that the Flutter team will consider adding Rust support to Pigeon.

Please provide the information I've requested above about what, concretely, you are requesting. In the form of **actual code** code that does the what you want generated code to do instead.

Without that information there is nothing for us to consider here, because there's no clear request.

**Comment by cmedamine** [comment]
Thank you for your response and for requesting more information about our request for Rust support in Pigeon. We apologize for not being more specific in our original request.

To better understand the benefits of Rust support in Pigeon, we have included an example of existing Rust code that we are currently using to communicate with Flutter using FFI:

```
// Rust code
#[no_mangle]
pub extern fn process_image(image_data: *const u8, image_size: usize, result: *mut u8) -> u32 {
    // Process the image and store the result in the `result` buffer
    // Return an error code if there was a problem
}
```

This example shows a Rust function that takes a pointer to an image buffer and the size of the image, processes the image, and stores the result in another buffer. The function is exposed to Flutter using FFI, which allows it to be called from Flutter using method channels.

We would like to use Pigeon to simplify and improve this code by generating the necessary bridging code and wrappers for communicating between Flutter and Rust. With Rust support in Pigeon, we envision being able to write Flutter code like this:

```
// Flutter code
final PigeonClient _pigeon = PigeonClient();

Future<Uint8List> processImage(Uint8List imageData) async {
  final ProcessImageResponse response = await _pigeon.send<ProcessImageRequest, ProcessImageResponse>(
      ProcessImageRequest(image_data: imageData));
  return Uint8List.fromList(response.result);
}
```

This example shows how the `process_image` function written in Rust can be called from Flutter using Pigeon. The Rust code defines the process_image function, which takes a pointer to image data and the size of the image as input, and returns a pointer to the processed image data. The Pigeon-generated code defines the `ProcessImageRequest` and `ProcessImageResponse` structs, which are used to serialize and deserialize the data passed between Flutter and Rust. The `process_image `function defined in the Pigeon-generated code takes a `ProcessImageRequest `as input and returns a `ProcessImageResponse`, and is responsible for calling the Rust `process_image `function and handling the conversion between the Rust data types and the Pigeon structs. Finally, the Flutter code uses the `PigeonClient `to send a `ProcessImageRequest`


I believe that Rust support in Pigeon would provide a number of benefits over our current approach using FFI. Some of these benefits include:

**Simplified communication:** Pigeon would generate the necessary bridging code and wrappers for communicating between Flutter and Rust, which would greatly simplify the process of calling Rust functions from Flutter and passing data between the two languages. This would make it easier to write and maintain the code, and reduce the risk of bugs.

**Improved error handling:** Pigeon would provide built-in error handling to detect and handle errors that may occur during communication between Flutter and Rust. This would make it easier to write robust code that gracefully handles errors, and reduce the risk of bugs.

**Automatic serialization/deserialization:** Pigeon would automatically handle the serialization and deserialization of data passed between Flutter and Rust. This would save us the time and effort of writing manual serialization/deserialization code, and ensure that the data is correctly converted between the two languages.

**Improved code readability:** Using Pigeon would make our code more readable and easier to understand, because it would separate the platform-specific details of communication into separate generated code files. This would make it easier for other developers to understand how our code is interacting with Rust, and make it easier to find and fix issues when they arise.

We hope that this additional information helps clarify our request for Rust support in Pigeon, and we look forward to any feedback or suggestions that the Flutter team may have. Thank you again for considering our request.

I believe that Rust support in Pigeon would provide a number of benefits over our current approach using FFI. Some of these benefits include:

**Simplified communication:** Pigeon would generate the necessary bridging code and wrappers for communicating between Flutter and Rust, which would greatly simplify the process of calling Rust functions from Flutter and passing data between the two languages. This would make it easier to write and maintain the code, and reduce the risk of bugs.

Improved error handling: Pigeon would provide built-in error handling to detect and handle errors that may occur during communication between Flutter and Rust. This would make it easier to write robust code that gracefully handles errors, and reduce the risk of bugs.

**Automatic serialization/deserialization:** Pigeon would automatically handle the serialization and deserialization of data passed between Flutter and Rust. This would save us the time and effort of writing manual serialization/deserialization code, and ensure that the data is correctly converted between the two languages.

**Improved code readability:** Using Pigeon would make our code more readable and easier to understand, because it would separate the platform-specific details of communication into separate generated code files. This would make it easier for other developers to understand how our code is interacting with Rust, and make it easier to find and fix issues when they arise.

**Comment by stuartmorgan** [comment]
> I believe that Rust support in Pigeon would provide a number of benefits over our current approach using FFI.

You keep answering the question "why should Pigeon support Rust", which is not the question I've been asking. It would help keep the discussion focused if you could avoid re-hashing the "why", and answer the specific questions I'm asking about what you want this to concretely do (which is mostly "how").

> I have included an example of existing Rust code that I'm currently using to communicate with Flutter using FFI

This is part of what I'm looking for, thanks. So to be clear then, are you requesting that Pigeon generated FFI-based bindings for calling Rust code? I'm not sure how to reconcile that with your earlier discussion of bidirectional communication.

> The function is exposed to Flutter using FFI, which allows it to be called from Flutter using method channels.

FFI and method channels are completely separate, unrelated systems. Given this conflation, I'm still unclear about what you envision this proposed generator actually generating.

> With Rust support in Pigeon, I envision being able to write Flutter code like this

The question I'm asking is what code you are expecting Pigeon to generate to allow for that. Let me make this as concrete as possible: a Pigeon definition comparable to what you've shown above would be something like:

```dart
@HostApi()
abstract class SomePigeonApi {
  Uint8List processImage(Uint8List imageData);
}
```

The corresponding Swift output (I removed a few very minor details for brevity) is:

```swift
import Foundation
import Flutter

protocol SomePigeonApi {
  func processImage(imageData: FlutterStandardTypedData) -> FlutterStandardTypedData
}

class SomePigeonApiSetup {
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: SomePigeonApi?) {
    let processImageChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.SomePigeonApi.processImage", binaryMessenger: binaryMessenger)
    if let api = api {
      processImageChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let imageDataArg = args[0] as! FlutterStandardTypedData
        let result = api.processImage(imageData: imageDataArg)
        reply(wrapResult(result))
      }
    } else {
      processImageChannel.setMessageHandler(nil)
    }
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: FlutterError) -> [Any?] {
  return [
    error.code,
    error.message,
    error.details
  ]
}
```

Please show me the corresponding output from the hypothetical Rust generator you are proposing, so that I can see what exactly it is that you are expecting here.
