### ISSUE TITLE
Wrong file link 

### ISSUE THREAD

**Issue by MarioCastellanos** [flutter/flutter#118114]
Hello, 

I have found an issue with the Get to know firebase for Flutter section located at [https://firebase.google.com/codelabs/firebase-get-to-know-flutter#4](url) within subsection 5 Add RSVP functionality. In subsection 5.3 (In the HomePage class's build method, integrate the app state with the AuthFunc widget)  the github link doesnt direct the user to the correct github file it should be sending the user to the home page but it sends the user to the main.dart. Attached is a screenshot of the subsection. The link the user should be recieving for this section is [https://github.com/flutter/codelabs/blob/master/firebase-get-to-know-flutter/step_05/lib/home_page.dart](url). 
<img width="583" alt="Screenshot 2023-01-04 at 2 39 31 PM" src="https://user-images.githubusercontent.com/25626772/210663487-2c009dcb-ad6b-4aea-a4cf-13f6f42a2a45.png">

Thank you i hope this helps future developers.

**Comment by huycozy** [comment]
@MarioCastellanos Thank you for the report but this is a known issue being tracked at #117656. Closing as a duplicate.
