### ISSUE TITLE
Emoji gets huge after font size threshold (second attempt)

### ISSUE THREAD

**Issue by mariopepe** [flutter/flutter#118147]
This is an exact replica of [110726](https://github.com/flutter/flutter/issues/110726) opened by @EnduringBeta and erroneously closed as fixed from @exaby73 on September the 1st 2022.

Today, is January the 7th 2023 and on Flutter 3.3.10, the issue is everything but fixed.
Whether or not it is solved on master, is completely irrelevant at this point, given that 3+ months passed since the time it was marked as fixed.
Also note that from September the 1st 2021, the following hotfixes have been released to stable:
- 3.3.1
- 3.3.2
- 3.3.3
- 3.3.4
- 3.3.5
- 3.3.6
- 3.3.7
- 3.3.8
- 3.3.9
- 3.3.10

**NONE OF THESE ADDRESSED THE ISSUE MENTIONED**
Hence, please keep this issue open until a hotfix to stable is deployed or a brand new version, including the fix. Until then, the issue should not be closed.

## Steps to Reproduce

1. Get this repo and the branch huge-emoji: https://github.com/EnduringBeta/flutter-bug/tree/huge-emoji
2. Deploy to a device and (probably) confirm that the counter # and hand-wave emoji are the same size.
3. Increase the font size in [main.dart](https://github.com/EnduringBeta/flutter-bug/blob/huge-emoji/lib/main.dart#L35) by ~5 and redeploy. Repeat until emoji gets dramatically bigger, out of scale of the text.

**Expected results:** Emoji stays about the same size as the text

**Actual results:** Emoji stays about the same size as the text

![](https://user-images.githubusercontent.com/4104925/187797552-8877ef0a-743e-409a-b3eb-cbdff8e8cf6d.png)

**Comment by EnduringBeta** [comment]
I believe the actual results are that the emoji gets huge, obviously.

I don't know how long something working on master would propagate to stable, so I was fine letting it be. But of course I welcome more eyes on it.

**Comment by exaby73** [comment]
Hello @mariopepe and @EnduringBeta. Sorry to hear that the issue as not been addressed yet. To request a hotfix / cherrypick into stable, see [`Requesting a cherry-pick`](https://github.com/flutter/flutter/wiki/Flutter-Cherrypick-Process#requesting-a-cherry-pick). There is a specific template used to request a cherry pick into stable. I am closing this issue but feel free to raise an issue using the [`Cherry-pick template`](https://github.com/flutter/flutter/issues/new?assignees=&labels=cp%3A+review&template=7_cherry_pick.yml&title=%5BCP%5D+%3Ctitle%3E). Thank you
