### ISSUE TITLE
[CP] Update DWDS to version `16.0.2`

### ISSUE THREAD

**Issue by elliette** [flutter/flutter#118122]
### issue_link

https://github.com/flutter/flutter/issues/117676

### Commit Hash

https://github.com/flutter/flutter/pull/118117

### Target

beta

### pr_link

https://github.com/flutter/flutter/pull/118118

### Impacted Users

All Flutter web users

### Impact Description

This hotfix  fixes the largest source of Flutter crashes on Flutter beta due to an error thrown in DWDS: https://github.com/flutter/flutter/issues/117676

The hotfix updates the version of DWDS in Flutter beta from `16.0.1` to `16.0.2`. The only change between those versions is the fix for the crash: https://pub.dev/packages/dwds/changelog#1602

### Workaround

No

### Risk

low

### Test Coverage

yes

**Comment by elliette** [comment]
FYI @christopherfujino

**Comment by CaseyHillers** [comment]
I'm marking this as approved since @christopherfujino sent the PR for it, and @elliette filed the CP request (2 parties already agreed to CP this)
