### ISSUE TITLE
Ghosting when using border with container

### ISSUE THREAD

**Issue by bibaswan-bhawal** [flutter/flutter#118140]
## Steps to Reproduce

Create a container with a black border and border-width  of 2.

**Expected results:** 
container with a black border and border width 2
**Actual results:** 
the container is created properly but I have noticed a faint white line the same width as the border width that extends from edge of the container to the edge of the screen. I'm pretty sure this is some sort of anti aliasing issue since others have described similar ghosting effects. 
<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by darshankawar** [comment]
I tried with below code sample and do see anti-aliasing on the border of the container:

<img width="572" alt="Screenshot 2023-01-09 at 12 51 21 PM" src="https://user-images.githubusercontent.com/67046386/211258147-7e1e6ba7-fe73-4540-bbfa-774d4941233f.png">

This seems to be a general anti-aliasing issue, same as described in [here](https://github.com/flutter/flutter/issues/54370). You may take a look at [this](https://github.com/flutter/flutter/issues/54370#issuecomment-611714132) comment for further reference and suggest to follow-up in that issue for further updates.

Closing as duplicate.
