### ISSUE TITLE
[go_router] go_router package conflicts with uni_links in IOS

### ISSUE THREAD

**Issue by Arthur-Zaripov** [flutter/flutter#118191]
Hello! In IOS if uni_links and go_router packages are installed, Universal Link (or Custom Scheme Links) opens the flutter app but does not go to the right page.
Example: https://my-app.com/page1. On iOS, when I click on a url, it opens my app but stays on the main screen. It does not go to the given page.
After deleting the package uni_links, the problem disappears.

**Comment by darshankawar** [comment]
@Arthur-Zaripov 
Thanks for the report. Can you please provide `flutter doctor -v` and minimal code sample including uni_links implementation that shows the behavior you are reporting ?
