### ISSUE TITLE
[Local_auth]: Add a way to choose the biometric to use when multiple methods are available

### ISSUE THREAD

**Issue by tal-72** [flutter/flutter#118172]
Hello there!

I have a login page. I have given face id and fingerprint both as an option to user to login. The issue is when both face id and fingerprint is enrolled on my device, it shows both faceid and fingerprint on opening of dialog.

When i click on fingerprint sensor, first it shows face id and then shows fingerprint sensor.
When i click on face id, first it shows face id and then shows fingerprint sensor.

But it should give face Id to login if tapped on face id and fingerprint to login if i tapped on fingerprint sensor.

Any help in this regard.
Thanks

**Comment by exaby73** [comment]
Hello @tal-72. Thank you for filing this issue. Can you please provide the following information?

- A [complete and minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). Ideally, a single `main.dart` file that can be run directly.
- The output of `flutter doctor -v`
- The output of `flutter run -v`
- Devices reproducible on

Please provide the information in the form of text. See how to make collapsible sections with Markdown [here](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-collapsed-sections).

**Comment by tal-72** [comment]
I have these two methods. 
Authenticate finger print method will be called on tapped of fingerprint icon button.
Authenticate face id will be called on tap of faceId icon button.

Now the problem is when both finger print and face id is enrolled on my device, when i tapped on fingerprint icon button, authenticate finger print method get called but dialog first shows face Id to logged in instead of fingerprint and if wrong face id is given then it fallback to fingerprint.

////********** how i want it to work ******/////

on tap of fingerprint icon button, it should only show finger print to logged in.
on tap of face id icon button, it should show only face id to logged in.

 Future<bool> authenticateFingerPrint() async {
 List<BiometricType> availableBiometrics =
        await _auth.getAvailableBiometrics();

    final isAvailable = await hasBiometrics();
    if (!isAvailable) return false;

    if (availableBiometrics.contains(BiometricType.fingerPrint)) {
      try {
        return await _auth.authenticate(
          biometricOnly: true,
          useErrorDialogs: true,
          stickyAuth: true,
          localizedReason: 'Scan Fingerprint to Authenticate',
        );
      } on PlatformException catch (e) {
        debugPrint(e.toString());
        return false;
      }
    }
    return Future.value(true);
  }

static Future<bool> authenticateFaceId() async {
 List<BiometricType> availableBiometrics =
        await _auth.getAvailableBiometrics();

    final isAvailable = await hasBiometrics();
    if (!isAvailable) return false;
    if (availableBiometrics.contains(BiometricType.face)) {
      try {
        return await _auth.authenticate(
          useErrorDialogs: false,
          sensitiveTransaction: false,
          stickyAuth: true,
          localizedReason: 'Scan Face to Authenticate',
        );
      } on PlatformException catch (e) {
        debugPrint(e.toString());
        return false;
      }
    } else 

      return Future.value(false);
    }
  }
  

![fluttter doctor](https://user-images.githubusercontent.com/101640037/211749673-f37b3a45-910d-4c3b-a72b-ff32f3190d1a.jpeg)

**Comment by exaby73** [comment]
This looks like a proposal to add a way of choosing a way to authenticate, as the `authenticate` method, by my knowledge, would use the device's preferred authentication method. While I am not sure if this is possible, I am labeling the issue as a proposal to add a way to choose the biometric authentication method.

**Comment by stuartmorgan** [comment]
As far as I can tell, iOS doesn't provide API for authenticating with a specific biometric type, in which case this is impossible to implement in the plugin. If you are aware of an OS API that allows this, let us know the details and we can re-evaluate.
