### ISSUE TITLE
Scaffold in BottomSheet has extra bottom padding

### ISSUE THREAD

**Issue by theideasaler** [flutter/flutter#118132]
I need to display a snackbar above a bottom sheet. 

And this [answer in stackoverflow](https://stackoverflow.com/a/55154960/7951209) works for me by wrapping my bottom sheet inside a `Scaffold`. But it comes with a side effect of an extra padding got added into my bottom sheet. 

For example in the sample, even if I set the height of the bottom sheet's content to only `100` the bottom sheet popped still shows extra white padding below. I have tried to use `MediaQuery.removeViewPadding` , `MediaQuery.removePadding` and 
`MediaQuery.removeViewInsets` but none of these method works.

I also tried to put my bottom sheet content as the `bottomSheet` prop of the `Scaffold` but then the padding comes to the top of my bottom sheet content.

Appreciate for any help.

## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. Tap `Test` button
3. Observe the popped bottom sheet

**Expected results:** 
The bottom sheet wrapped inside a `Scaffold` should have a height as its content's height.
<img width="350" alt="image" src="https://user-images.githubusercontent.com/17869748/211132493-1cbd6a46-32ab-4597-806c-b570d3b8e21d.png">

**Actual results:** 
<img width="376" alt="image" src="https://user-images.githubusercontent.com/17869748/211132183-569a998a-817c-42e9-95b8-887980ba7e93.png">

<details>
<summary>Code sample</summary>

```dart
@override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: TextButton(
          onPressed: () {
            showModalBottomSheet(
              context: context,
              builder: (BuildContext context) {
                return Scaffold(
                  body: Container(
                    height: 100,
                    color: Colors.black,
                  ),
                );
              },
            );
          },
          child: const Text('Test'),
        ),
      ),
    );
  }
```

</details>

**Comment by huycozy** [comment]
@theideasaler Please check this updated code if it's applicable for you

<details>
<summary>Sample code (updated code)</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: Scaffold(
        body: Center(
          child: Builder(builder: (context) {
            return TextButton(
              onPressed: () {
                showModalBottomSheet(
                  context: context,
                  builder: (BuildContext ct) => ScaffoldMessenger(
                    child: Container(
                      constraints: BoxConstraints.tight(Size.fromHeight(100)),
                      child: Overlaywidget(),
                    ),
                  ),
                );
              },
              child: const Text('Test'),
            );
          }),
        ),
      ),
    );
  }
}

class Overlaywidget extends StatefulWidget {
  const Overlaywidget({Key? key}) : super(key: key);

  @override
  State<Overlaywidget> createState() => _OverlaywidgetState();
}

class _OverlaywidgetState extends State<Overlaywidget> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Container(
          height: 100,
          color: Colors.blue,
          child: TextButton(
            child: Text(
              'Show snackbar',
              style: TextStyle(color: Colors.white),
            ),
            onPressed: () {
              ScaffoldMessenger.of(context).showSnackBar(SnackBar(
                duration: const Duration(seconds: 2),
                content: Text('Hello'),
              ));
            },
          ),
        ),
      ),
    );
  }
}

```
</details>

### Demo

https://user-images.githubusercontent.com/104349824/211265892-d24ed061-eddf-4bc4-aeb9-a7e1f6f413b6.mov

**Comment by theideasaler** [comment]
Hi @huycozy , thanks for the solution. 

I think this solution is for fixed height widget but the issue I am facing is - inside my `BottomSheet` there are some `Flexible` texts, which means the height of the bottom sheet might vary on different devices when the text gets wrapped. So  I have to make the height of the `BottomSheet` just fit the content inside it.

**Comment by huycozy** [comment]
@theideasaler I think this issue should belong to the bottom sheet issue rather than Scaffold. 

And I see there is a known issue #32747 along with a few solutions that have been given. Please find there any applicable solution if any. Perhaps the combination of using `DraggableScrollableSheet` or `isScrollControlled` might help.

**Comment by theideasaler** [comment]
@huycozy I tired those solutions before but whenever my target widget is wrapped inside a `Scaffold` there will be always an extra padding added into the bottom sheet. 

At the moment I only found wrapping my widget inside `Scaffold` allows me display snackbar above it. I am not too sure if there is any other way to let me display the snackbar above the bottom sheet.

**Comment by huycozy** [comment]
@theideasaler I tried some solutions that are posted by others (https://github.com/flutter/flutter/issues/32747#issuecomment-492657937, https://github.com/flutter/flutter/issues/32747#issuecomment-533837699) and see those answers looks fine when I pre-defined the child ratio with `DraggableScrollableSheet` or `FractionallySizedBox`.

<details>
<summary>Sample code (using DraggableScrollableSheet)</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: Scaffold(
        body: Center(
          child: Builder(builder: (context) {
            return TextButton(
              onPressed: () {
                showModalBottomSheet(
                  context: context,
                  builder: (BuildContext ct) => DraggableScrollableSheet(
                    expand: false,
                    minChildSize: .2,
                    initialChildSize: .2,
                    builder: (BuildContext context, ScrollController scrollController) {
                      return ScaffoldMessenger(
                        child: Overlaywidget(),
                      );
                    },
                  ),
                );
              },
              child: const Text('Test'),
            );
          }),
        ),
      ),
    );
  }
}

class Overlaywidget extends StatefulWidget {
  const Overlaywidget({Key? key}) : super(key: key);

  @override
  State<Overlaywidget> createState() => _OverlaywidgetState();
}

class _OverlaywidgetState extends State<Overlaywidget> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Container(
          color: Colors.blue,
          child: TextButton(
            child: Text(
              'Show snackbar',
              style: TextStyle(color: Colors.white),
            ),
            onPressed: () {
              ScaffoldMessenger.of(context).showSnackBar(SnackBar(
                duration: const Duration(seconds: 2),
                content: Text('Hello'),
              ));
            },
          ),
        ),
      ),
    );
  }
}

```
</details>

<details>
<summary>Demo (using DraggableScrollableSheet)</summary>


https://user-images.githubusercontent.com/104349824/211472770-a3eaa14a-14ef-4a72-9dc5-caeebf939c78.mov


</details>

And it seems you should control the bottom sheet height by your implementation. In case you want to have a dynamic height, it may be a proposal for bottom sheet, and please file a separate issue (proposal template) for that.

**Comment by theideasaler** [comment]
@huycozy thanks for the example. 

I think I will leave it for now and stick to the existing UX by showing a snackbar after modal bottom sheet closed - it takes too much efforts to get this small UX improvement.

For anyone who still wants displaying snackbar above a dynamic height bottom sheet, I think this [#63254 comment](https://github.com/flutter/flutter/issues/63254#issuecomment-883943303) might be useful which uses `globalScaffoldMessengerKey.currentState.showBottomSheet`, but just needs more dedicated efforts on the UI and  controller for bottomsheet's hide/show.
