### ISSUE TITLE
ExpansionPanelList should allow to set MaterialGap height

### ISSUE THREAD

**Issue by martin-braun** [flutter/flutter#118167]
## Use case

I'd like to use an `ExpansionPanelList` without any gaps / spaces between their elements.

## Proposal

I'd like to define a `gapHeight` that will be passed to the `MaterialGap` widget that is placed between the expanded `ExpansionPanel` children of the `ExpansionPanelList`.

I can set the `expandedHeaderPadding`, but it will only influence the padding of the first header. Setting `elevation` does not solve the problem either, because the `ExpansionPanelList` does this in its build function: 

```dart
if (_isChildExpanded(index) && index != 0 && !_isChildExpanded(index - 1))
items.add(MaterialGap(key: _SaltedKey<BuildContext, int>(context, index * 2 - 1)));
```

`MaterialGap` accepts a `size` property in its constructor, so I wonder why there is no property on the `ExpandedPanelList` that allows me to set the `size` of those `MaterialGap`s.

## Illustration

I don't want these `ExpandedPanel`s to move when expanding. This is the closest I can get:

![2023-01-09 5 39 35 AM](https://user-images.githubusercontent.com/24259245/211242070-2ee51b47-f78a-467c-a4f9-5bf97a4c9c77.gif)

```dart
ExpansionPanelList(
      elevation: 0,
      dividerColor: Colors.transparent,
      expandedHeaderPadding: const EdgeInsets.symmetric(vertical: 0),
      expansionCallback: (int index, bool isExpanded) {
        setState(() {
          _expanded[index] = !isExpanded;
        });
      },
      children: panels,
    );
```

## Additional context

Please see: 

- https://stackoverflow.com/questions/60555041/is-there-a-way-to-get-rid-of-the-spacing-between-expansion-panels-when-expanded
- https://stackoverflow.com/questions/72822297/how-to-remove-space-between-expanded-expansionpanels-in-expansionpanellist
- https://stackoverflow.com/questions/60463999/flutterhow-to-remove-elevation-from-expansionpanellist

**Comment by joaodos3v** [comment]
Up
