### ISSUE TITLE
Redirect does not have the transition.

### ISSUE THREAD

**Issue by KeithBacalso** [flutter/flutter#118166]
So if ever it gets into my redirect logic it does not have the default transition or even if adding custom transition to its page still no transition at all. If it is not inside the redirect logic the transition is working(wether if it is the default transition or custom one).

==== THIS IS MY  CODE ====
```dart
 redirect: (context, state) {
      final loginLocation = PAGE.signin.path;
      final registerLocation = PAGE.signup.path;
      final homeLocation = PAGE.home.path;
      final splashLocation = PAGE.splash.path;
      final onboardLocation = PAGE.onboarding.path;

      final isInitialized = userCubit.state.isInitialized;
      final isLoggedIn = userCubit.state.isLoggedIn;
      final isOnboarded = userCubit.state.isOnboarded;

      final isGoingToInitialize = state.subloc == splashLocation;
      final isGoingToLogin = state.subloc == loginLocation;
      final isGoingToRegister =
          state.subloc == '$loginLocation/$registerLocation';
      final isGoingToOnboard = state.subloc == onboardLocation;

      if (!isInitialized && !isGoingToInitialize) {
        return splashLocation;
      }

      if (isInitialized &&
          !isLoggedIn &&
          !isGoingToLogin &&
          !isGoingToRegister) {
        return loginLocation;
      }

      if (isLoggedIn && !isOnboarded && !isGoingToOnboard) {
        return onboardLocation;
      }

      if ((isLoggedIn && isGoingToLogin) ||
          (isInitialized && isGoingToInitialize) ||
          (isOnboarded && isGoingToOnboard)) {
        return homeLocation;
      }

      return null;
    },
    ```

**Comment by exaby73** [comment]
Hello @KeithBacalso. Could you provide me with the following:

- A [complete and minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). This should be a complete sample, including `main()` and the `GoRouter` instantiation
- Complete output of `flutter doctor -v`
- `go_router` version you're using

**Comment by KeithBacalso** [comment]
@exaby73 This is my `flutter doctor -v`

[√] Flutter (Channel stable, 3.3.9, on Microsoft Windows [Version
    10.0.22000.1335], locale en-PH)
    • Flutter version 3.3.9 on channel stable at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b8f7f1f986 (7 weeks ago), 2022-11-23 06:43:51 +0900
    • Engine revision 8f2221fbef
    • Dart version 2.18.5
    • DevTools version 2.15.0

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\User\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build
      11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.2.5)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.2.32616.157
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.12+7-b1504.28-7817840)

[√] VS Code (version 1.74.2)
    • VS Code at C:\Users\User\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.56.0

[√] Connected device (4 available)
    • 2109119DG (mobile) • 5252a6b7 • android-arm64  • Android 12 (API 31)
    • Windows (desktop)  • windows  • windows-x64    • Microsoft Windows
      [Version 10.0.22000.1335]
    • Chrome (web)       • chrome   • web-javascript • Google Chrome
      108.0.5359.125
    • Edge (web)         • edge     • web-javascript • Microsoft Edge
      108.0.1462.76

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!


GO ROUTER VERSION:  6.0.0

**Comment by KeithBacalso** [comment]
my main.dart code

`Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  await Hive.initFlutter();

  await Future.wait([
    Hive.openBox('onboard'),
    Hive.openBox('login'),
  ]);

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return BlocProvider(
      create: (_) => UserCubit()..initialize(),
      child: BlocBuilder<UserCubit, UserState>(
        builder: (context, state) {
          final appRouter = AppRouter(context.read<UserCubit>());

          return MaterialApp.router(
            routerConfig: appRouter.router,
            title: 'Flutter Demo',
            theme: ThemeData(
              primarySwatch: Colors.blue,
            ),
          );
        },
      ),
    );
  }
}
`

**Comment by huycozy** [comment]
Hi @KeithBacalso

Your sample code is containing 3rd plugin/package (bloc, hive). 
For the issue to be workable, it needs to be reproducible with a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code. Please provide such a sample.

Thank you!
