### ISSUE TITLE
Immutable and Offline Flutter SDK mode

### ISSUE THREAD

**Issue by carterbox** [flutter/flutter#118162]
## Use case
- Using the Flutter SDK in CI/automated build environments with read-only filesystems
- Packaging the Flutter SDK for Flatpak to be used in flatpak-builder to build a Flutter app
- Packaging the Flutter SDK for deb,rpm to be installed in the root filesystem
- Building Flutter packages on air-gapped systems / offline

The problem I am trying to solve is that it is currently not possible to ship/use the Flutter SDK as a system installation in RPM/DEB formats or as an SDK extension for a Flatpak Desktop SDK (build environment). This is because the Flutter SDK requires both write access to itself and internet access during initialization.

These two conditions are not possible for RPM/DEB/Flatpak distribution because in these formats, the end user does not have write access to the directories where the packages are installed, and in the case of Flatpak SDK Extensions, no internet access is provided while building Flatpaks.

I have tried patching the Flutter SDK to not fail when no network access is allowed, but this attempt was only partially effective. There were still some commands where I coudln't find the source of outbound web requests. Regardless, The Flutter SDK is very vehement about being able to edit its own directory, so implementing a patch for read-only filesystems is out of my depth.

### Related Issues
Request for DEB/RPM Flutter SDK https://github.com/flutter/flutter/issues/108681
Request for Flatpak Flutter SDK https://github.com/flutter/flutter/issues/41737
Attempt to create Flatpak Flutter SDK https://github.com/flathub/flathub/pull/3777

### Flutter SDK as a Dart package (devendor Dart)

First, it seems that the Flutter SDK is a Dart package, so it should be installable from pub.dev by calling `dart pub get flutter`. This approach avoids the immutable directory issue of system installations because the Dart SDK doesn't edit itself and can be installed in an immutable directory while Flutter is installed in PUB_CACHE which is located in a user-writable directory by default and can be easily moved with the environment variable. Using this functionality, Dart packages (including those which depend on Flutter) can be distributed as source packages with all of their dependencies by adding `.pub-cache` to the source archive. While indirect, this provides similar functionality to the go/rust vendor functionality. 

I would expect to get a working Flutter SDK CLI by calling `dart pub global activate flutter`.

```bash
$ dart pub global activate flutter
The current Dart SDK version is 2.18.6.

Because pub global activate depends on flutter any which requires SDK version <2.0.0, version solving failed.
```
However, the response from Dart seems to imply that while this was originally the case, for some reason Flutter is no longer distributed this way.

### Optional Network Access

Second, for offline and sandboxed builds Flutter tools should not fail just because there is no internet access. The Flutter CLI should either accept `--offline` as an option for all commands and/or just warn the user that `pub update/get` were unsuccessful and that the local cache will be used. An error should only be raised if a required package is not in the local cache AND network access is unavailable.

**Comment by huycozy** [comment]
Hi @carterbox 
With regard to `Optional Network Access`, this is a known issue being tracked at #22429. However, keeping this issue open for further insights from the team on other aspects.

**Comment by christopherfujino** [comment]
Thank you for filing this issue! However, I am going to close it as already being covered by:

1. https://github.com/flutter/flutter/issues/91318
2. https://github.com/flutter/flutter/issues/22429

I'm not sure the problem that vendoring the Flutter SDK via pub would solve. If the CI/packaging environments you're interested in allow a user writeable .pub-cache, then why can it not make the Flutter SDK directory user-writeable? Also, because the Dart SDK and Flutter SDK have different release cadences, I think the Flutter pub package would still need to vendor its own version of the Dart SDK (the Flutter SDK essentially needs to pin an exact version of the Dart SDK).

**Comment by carterbox** [comment]
@christopherfujino Thanks for redirecting me to those related issues! I will keep an eye on them. Let me try to better explain my suggestions.

> If the CI/packaging environments you're interested in allow a user writeable .pub-cache, then why can it not make the Flutter SDK directory user-writeable?

Distros packages (RPM/DEB/Flatpak) are installed into non-writable directories such as /opt /usr/local. System wide libraries such as these are not editable for security reasons. The .pub-cache is located in $HOME directories. They are user specific and created by the application as needed. In summary, system-wide packages are not compatible with the Flutter SDK because they cannot be user-writable.

The obvious solution to this is to have every user install their own copy of the Flutter SDK in their own directory. This only works if you have interent access because the Flutter SDK insists on updating itself.

> I believe the correct direction forward would be incrementally making all features of the Flutter tool that write to its install directory and/or make network calls to be configurable.

The more important of these two is offline initialization and use of the Flutter SDK. If Flutter is in offline mode, then write-access to it's own directory is moot because it doesn't have anything to update. Note, this also implies providing other archs besides x86 on the Flutter SDK downloads page.

> I'm not sure the problem that vendoring the Flutter SDK via pub would solve.

This was just my proposal/suggestion for how to implement the above goals because IMO it seems simpler in the long run for Flutter to use the existing Dart infrastructure for being updated instead of duplicating that effort with initialization scripts and managing its own cache. Let me reiterate the benefits of distributing Flutter as a normal Dart package.

Pros

- Distros don't need to package Flutter, they only need to package Dart
- Flutter can drop all of the tooling it needs to manage Dart and update itself
- Better support for non-x86 systems because other platforms just need to build the Dart SDK in order to get Flutter?

Cons

- Flutter has tight pinnings for the `environment.sdk` key in `pubspec.yaml`, so updating Dart is needed to update Flutter most of the time?
