### ISSUE TITLE
A handful of bots are dead or have issues

### ISSUE THREAD

**Issue by drewroengoogle** [flutter/flutter#118107]
CC: @nehalvpatel in case I missed any you mentioned!

This is an extension of https://github.com/flutter/flutter/issues/115127, but given the initial issue was resolved I'm taking issues brought up in the comments to its own issue

The following bots from that original issue are still dead:
* [flutter-win-2](https://chromium-swarm.appspot.com/bot?id=flutter-win-2)
* [flutter-devicelab-linux-25](https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-linux-25)
* [flutter-devicelab-linux-23](https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-linux-23)

**Comment by nehalvpatel** [comment]
I found a few more from the bot page, but I'm not sure if all of them belong on this issue:
- [flutter-devicelab-linux-2](https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-linux-2) (prod)
  - quarantined; last successful task was on 2022-11-10
- [flutter-devicelab-linux-8](https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-linux-8) (prod)
  - device healthcheck failed; last successful task was on 2023-01-04
- [flutter-devicelab-mac-26](https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-26) (prod)
  - quarantined; last successful task was on 2022-11-23

**Comment by yusuf-goog** [comment]
These should be assigned to Kent. His github account needs to get whitelisted, so you can make the assignment.

**Comment by kentnguyen99** [comment]
Will check on these..

**Comment by kentnguyen99** [comment]
flutter-win2, flutter-devicelab-linux-23 and flutter-devicelab-linux-25 have been resolved and fixed. All servers are back online and ready for service.

**Comment by yusuf-goog** [comment]
@kentnguyen99 can you please add some details on how the recovery was performed for these devices and if you found something specific that caused it?

**Comment by kentnguyen99** [comment]
To fix dead bot by power recycle cell phone  and then reconnect back to the host server.

**Comment by kentnguyen99** [comment]
flutter-devicelab-linux-2 and flutter-devicelab-linux-8 have been fixed and both servers are ready for service. Still working and looking into issue on flutter-devicelab-linux-26.

**Comment by ricardoamador** [comment]
@kentnguyen99 any updates on this?

**Comment by drewroengoogle** [comment]
It looks like every bot mentioned in this issue (besides win-2, tracked here now: https://github.com/flutter/flutter/issues/120099) is resolved, so I'll close this issue. Thanks @kentnguyen99!
