### ISSUE TITLE
Exception has occurred. _AssertionError ('package:go_router/src/router.dart': Failed assertion: line 300 pos 12: 'inherited != null': No GoRouter found in context)

### ISSUE THREAD

**Issue by ramananmuthuvel** [flutter/flutter#118179]
Exception has occurred.
_AssertionError ('package:go_router/src/router.dart': Failed assertion: line 300 pos 12: 'inherited != null': No GoRouter found in context)

Seems like there is an Exception error with the GoRouter 

go_router version 6.0.1

**Comment by danagbemava-nc** [comment]
Hi @ramananmuthuvel,

Can you please provide your `flutter doctor -v` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?

Can you also check https://github.com/flutter/flutter/issues/116855 to see if it is similar to your issue?

Thank you

**Comment by ramananmuthuvel** [comment]
it seems to same issue as the #116855
