### ISSUE TITLE
Consider moving Fuchsia content_handler out of flutter/engine

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#11818]
If we used the new Engine API to separate the fuchsia content_handler further from flutter/engine code we could move it into a fuchsia-controlled repository where changes to it could be covered by fuchsia pre-commit testing and typos like https://github.com/flutter/engine/pull/4032/files more easily avoided.

**Comment by Hixie** [comment]
cc @abarth @jason-simmons @chinmaygarde

**Comment by chinmaygarde** [comment]
This is done.
