### ISSUE TITLE
listview not working with firestore at first run

### ISSUE THREAD

**Issue by waqasaslam6** [flutter/flutter#118259]
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by ibukunoluwanap** [comment]
Your code sample and your logs are empty.

**Comment by darshankawar** [comment]
Closing as empty issue. If you have issues using cloud_firestore, please report them in dedicated repo: https://github.com/firebase/flutterfire/issues
