### ISSUE TITLE
Namespace embedder API software pixel format values

### ISSUE THREAD

**Issue by ardera** [flutter/flutter#118247]
## Use case

Some time ago I implemented configurable pixel formats for the embedder API software rendering backend: https://github.com/flutter/engine/pull/26995

Though what I didn't think about is that the enum values I chose there might be a bit too general, i.e. there's maybe some programs that use `kRGBA8888` as identifiers somewhere. (Incidentally, that's [the case for my own embedder](https://github.com/ardera/flutter-pi/blob/566db0a56354bb49bbd2437186a8141b81e3e634/include/pixel_format.h#L32-L40))

## Proposal

Rename the values of the [`FlutterSoftwarePixelFormat`](https://github.com/flutter/engine/blob/687e3cb0fbe2fd7006d8d0dcd642471c2d3363fe/shell/platform/embedder/embedder.h#L315-L343) enum and properly namespace them, to avoid name collisions:
```
kGray8 --> kGray8_FlutterSoftwarePixelFormat
kRGB565 --> kRGB565_FlutterSoftwarePixelFormat
...
```

**Comment by stuartmorgan** [comment]
> kGray8 --> kGray8_FlutterSoftwarePixelFormat

We should be consistent with other enums in that header, where we prefix the constant with the enum name: `kFlutterSoftwarePixelFormatGray8`, `kFlutterSoftwarePixelFormatRGB565`, etc.

**Comment by ardera** [comment]
You're right. I'll prepare a PR
