### ISSUE TITLE
`gen-l10n` ignores explicit `false` values for arguments

### ISSUE THREAD

**Issue by maRci002** [flutter/flutter#118203]
## Use case

There are multiple arguments for `gen-l10n` which has two syntax: `--[no-]nullable-getter` `--[no-]synthetic-package` `--[no-]use-deferred-loading` `--[no-]required-resource-attributes`.

Note: I'm going to use only `nullable-getter` in the examples just for simplicity.

In case of `l10n.yaml` configuration `nullable-getter: false` will be recognized however in case of `gen-l10n` tool the `--nullable-getter false` **won't be recognized** moreover **no error is raised**.

Steps:

1. Create app with `arb` resource file
   * **terminal**:
   `flutter create flutter_app && cd flutter_app && mkdir l10n && cd l10n && echo '{"test": "test"}' > app_en.arb`
   * **Windows cmd**
   `flutter create flutter_app && cd flutter_app && mkdir l10n && cd l10n && echo {"test": "test"} > app_en.arb`
2. Add dependencies in `pubspec.yaml`
    ``` yaml
    dependencies:
      flutter:
        sdk: flutter
      flutter_localizations:
        sdk: flutter
      intl: ^0.17.0
    ```
3. Generate `app_localizations.dart` (_note: this command will create a non synthetic package so `AppLocalizations` can be found under `lib/l10n` folder_)
    `flutter gen-l10n --nullable-getter false --no-synthetic-package --arb-dir l10n --output-dir lib/l10n --template-arb-file app_en.arb --output-localization-file app_localizations.dart --output-class AppLocalizations --preferred-supported-locales en`
5. In `main.dart` import `app_localizations.dart`
    `import 'package:flutter_app/l10n/app_localizations.dart';`
6. In a `build` method use
    `AppLocalizations.of(context).test;`

If rerunning command via `--no-nullable-getter` the **no nullable getter** should work properly:
`flutter gen-l10n --no-nullable-getter --no-synthetic-package --arb-dir l10n --output-dir lib/l10n --template-arb-file app_en.arb --output-localization-file app_localizations.dart --output-class AppLocalizations --preferred-supported-locales en`

## Proposal

- `--nullable-getter false` / `synthetic-package false` ... should just work or throw error.
- If it cannot be modified, it should be properly documented when calling to `flutter gen-l10n -h`

**Comment by thkim1011** [comment]
Hey, so the `ArgParser` that the `flutter` executable uses doesn't allow treating a flag as also an option that takes its own arguments. Rather, the `false` value you're passing in is treated as another positional argument. I've merged in a PR to throw an error when unexpected positional arguments are passed in.
