### ISSUE TITLE
Both Horizontal and Vertical Scrolling Not Enable at a time  in ListView Builder

### ISSUE THREAD

**Issue by abineshPalanisamy** [flutter/flutter#118299]
**Both Horizontal and Vertical Scrolling Not Enable in ListView Builder**
Both horizontal and vertical scrolling cannot be enabled at the same time in the ListView builder.

**Expected results**
Expected both option in scrollDirection of listView builder.

**Actual results**
In the listview builder, we only activate one direction at a time. I am unable to activate both directions.

**Used Flutter Version**
Channel stable, 3.3.10,

[√] Flutter (Channel stable, 3.3.10, on Microsoft Windows [Version 10.0.19044.2364], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Professional 2022 17.4.3)
[√] Android Studio (version 2021.3)
[√] Connected device (3 available)
[√] HTTP Host Availability

**Comment by huycozy** [comment]
@abineshPalanisamy Currently the ListView can't scroll both axes but you can achieve this with `InteractiveViewer` instead. Please see demo [here](https://github.com/flutter/flutter/issues/20175#issuecomment-573896876). 

Also, you can follow `2D Scrolling project`: https://github.com/orgs/flutter/projects/32/views/1 for more information (there is a proposal for Lazy Table could be an alternative option).

Closing the issue as above explanation.
