### ISSUE TITLE
Child views in Mozart 2.0 don't get affected by Transform

### ISSUE THREAD

**Issue by dabhaid** [flutter/flutter#11824]
## Steps to Reproduce
We have a view in Mondrian debug view that applies an isometric transform to containers holding Mozart views
(transform is line 10: https://fuchsia.googlesource.com/mondrian/+/master/lib/isometric_widget.dart)

The views worked under Mozart, but look strange post Mozart 2.0 - adding a box decorator to the container to color it red shows that container is rotated as expected, but its child Mozart view isn't. Expected behavior is the Mozart view be transformed with the container, and so rendered over the decoration, obscuring it entirely. (Second image without the Mozart views for illustration of expected orientation).

![img_20170804_181126 1](https://user-images.githubusercontent.com/1244299/29842305-460a2a52-8cbd-11e7-9e6d-192d028a7aa0.jpg)
![img_20170804_181650 1](https://user-images.githubusercontent.com/1244299/29842310-48ec534e-8cbd-11e7-8fe1-f828268e70d2.jpg)

Happy to reproduce other scenarios

## Flutter Doctor

Paste the output of running `flutter doctor` here.
Building flutter tool...
[✓] Flutter (on Mac OS X 10.12.6 16G29, locale en-US, channel unknown)
    • Flutter at /Users/djmurphy/Code/fuchsia/lib/flutter
    • Framework revision 0de87bab4a (5 days ago), 2017-08-24 12:48:41 +0200
    • Engine revision 51775c77a9
    • Tools Dart version 1.25.0-dev.11.0

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.1)
    • Android SDK at /Users/djmurphy/Code/android-sdk-macosx
    • Platform android-26, build-tools 26.0.1
    • ANDROID_HOME = /Users/djmurphy/Code/android-sdk-macosx
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.3.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3.3, Build version 8E3004b
    • ios-deploy 1.9.1
    • CocoaPods version 1.3.1

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[-] IntelliJ IDEA Community Edition (version 2017.1.3)
    ✗ Flutter plugin version 12.1 - the recommended minimum version is 16.0.0
    • Dart plugin version 163.13137
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[-] IntelliJ IDEA Ultimate Edition (version 2017.1.3)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[✓] Connected devices
    • None

**Comment by Hixie** [comment]
cc @j9brown any ideas?

**Comment by tvolkert** [comment]
Fuchsia issue: https://fuchsia.atlassian.net/projects/FL/issues/FL-22

**Comment by tvolkert** [comment]
Closing per @dabhaid
