### ISSUE TITLE
Flutter webview SSL with custom CA

### ISSUE THREAD

**Issue by lokeb** [flutter/flutter#118286]
Hi. Why is this not working with custom installed CA certificate on the device? The default webview example on the emulator works fine with the installed certificate but flutter_webview still throws handshake error.

**Comment by danagbemava-nc** [comment]
This feature is currently not supported in the webview plugin. An issue already exists for tracking the implementation of this feature in https://github.com/flutter/flutter/issues/35868. Kindly follow up in the linked issue for updates. 

Closing from here as duplicate. 

Thank you

**Comment by lokeb** [comment]
This is not the same as the other. I am not looking for a way to provide a custom CA. There is already a way to install additional root certificates or authorities into the device. Your implementation must support   the certificates installed on the device. The problem is that it’s not working with your implementation but it’s working with the natively installed webview app on the emulator. Why is that? Where is it deriving it’s root certificates from?
