### ISSUE TITLE
Invalid `Podfile` file: undefined method `exists?' for File:Class

### ISSUE THREAD

**Issue by elmar001** [flutter/flutter#118295]
Not possible to run "pod install" for Flutter iOS app any more starting from today. Is it due to Cocoapods or Flutter?

```
[!] Invalid `Podfile` file: undefined method `exists?' for File:Class.


 #  from /Users/tt/flutterApp/ios/Podfile:34
 #  -------------------------------------------
 #  
 >    flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
 #  end
 #  -------------------------------------------
```

**Comment by elmar001** [comment]
I can see some discussions regarding same issue by react native developers on Github. It is most probably Cocoapods version or deprication issue.

**Comment by elmar001** [comment]
This one solved the isssue: https://github.com/flutter/flutter/issues/109385#issuecomment-1212616254
Seema like it happens due to newer ruby version and older Flutter SDK.

**Comment by danagbemava-nc** [comment]
Closing this as solved based on https://github.com/flutter/flutter/issues/118295#issuecomment-1378270010 and considering the fact that the issue has been fixed on the master channel. See https://github.com/flutter/flutter/pull/109428 

Thank you

**Comment by wamynobe** [comment]
same problem on 2.8.0 stable with cocoapods 1.11.3. To resolve this switch cocoapods to 1.11.2 `sudo gem install cocoapods -v 1.11.2`. Remember to remove 1.11.3 version first.

**Comment by joshsambrook** [comment]
> same problem on 2.8.0 stable with cocoapods 1.11.3. To resolve this switch cocoapods to 1.11.2 `sudo gem install cocoapods -v 1.11.2`. Remember to remove 1.11.3 version first.

How do you fully remove version 1.11.3?

**Comment by KaranMehta3984** [comment]
> Closing this as solved based on [#118295 (comment)](https://github.com/flutter/flutter/issues/118295#issuecomment-1378270010) and considering the fact that the issue has been fixed on the master channel. See #109428
> 
> Thank you

@elmar001 
I changed that line but had no luck have you fixed that issue? 
I am using flutter sdk 3.0.3 
Thanks

**Comment by elmar001** [comment]
> 
I just removed question mark from the end of File.exists? and saved it. And it worked. So the line is now like this:
`return [] unless File.exists file_path`

**Comment by KaranMehta3984** [comment]
> > 
> 
> I just removed question mark from the end of File.exists? and saved it. And it worked. So the line is now like this: `return [] unless File.exists file_path`
@elmar001 
Thanks 
I did it but not worked for me so I changed it with return [] unless File.exist? file_path
Thanks for the replay

**Comment by nguyenlamzx** [comment]
I also experienced this issue after install cocoapods

[!] Invalid `Podfile` file: undefined method `exists?' for File:Class.

 #  from .../ios/Podfile:37
 #  -------------------------------------------
 #  
 >    flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
 #  end
 #  -------------------------------------------

**Comment by alidavodii** [comment]
Open a terminal in your Xcode project folder and run the commands below:

gem cleanup
brew uninstall cocoapods
sudo gem uninstall cocoapods
sudo gem install cocoapods -v 1.10.0 -n /usr/local/bin
sudo gem install cocoapods-user-defined-build-types
pod install --repo-update
NOTE! If you using react-native before pod install --repo-update delete your node_modules folder and install again using npm

**Comment by Samuel-Rodrigues** [comment]
> 

 sudo gem uninstall cocoapods

**Comment by Samuel-Rodrigues** [comment]
> > mesmo problema em 2.8.0 estável com cocoapods 1.11.3. Para resolver isso, alterne cocoapods para 1.11.2 `sudo gem install cocoapods -v 1.11.2`. Lembre-se de remover primeiro a versão 1.11.3.
> 
> Como você remove totalmente a versão 1.11.3?

```
sudo gem uninstall cocoapods
```

**Comment by Numanshakir** [comment]
Works Fine For Me 

What's the output of $ ruby -v
If you open path/to/flutter-sdk/packages/flutter_tools/bin/podhelper.rb and change this line:

- return [] unless File.exists? file_path
+ return [] unless File.exist? file_path

**Comment by justdan0227** [comment]
`> sudo gem uninstall cocoapods`

how is it that I can do the brew uninstall and the sudo gem uninstall and it tells me that cocapods is not installed, yet I can still do a pod --version and it tells me it's running 1.11.3 and
`which pod `
returns 

`/Users/xxxxxx/.gem/bin/pod`

**Comment by dangnghia2101** [comment]
brew remove rbenv
rm -rf ~/.rbenv
rm -rf `brew --prefix`/Cellar/rbenv
sudo gem install cocoapods
