### ISSUE TITLE
Dismissible should have a way to not delete the item

### ISSUE THREAD

**Issue by iBob101** [flutter/flutter#11825]
## Steps to Reproduce

See:

https://stackoverflow.com/questions/45919197/flutter-dismissible-insists-list-item-must-be-removed-from-tree

I created a Flutter app with a list of Dismissible widgets in a Listview that allows the data shown in a widget to be edited if it is swiped in one direction or deleted if it is swiped in the other direction.  However, I needed a work around for the edit one becasue a Dismissible expects the onDismissed callback to delete the widget from the list.  Ideally there should be a mechanism to indicate that this deletion is not required in some or all circumstances.  For example, instead of

```dart
onDismissed: (DismissDirection direction) {
  setState(() {
    item.deleteTsk();
    });
  ...
```

you might have

```dart
onDismissed: (DismissDirection direction) {
  if (direction == DismissDirection.endToStart){
    setState(() {
      item.deleteTsk();
      });
    ...
```

**Comment by Hixie** [comment]
Do you still want the Dismissible to shrink in the edit case?

**Comment by iBob101** [comment]
No, ideally not.

**Comment by Hixie** [comment]
What probably makes sense if for us to have a new callback that fires just before we start shrinking, and that callback can return true or false based on whether it wants the dismissible to shrink or not.

**Comment by iBob101** [comment]
Yes, perfect.

**Comment by rolurq** [comment]
Is there any updates about this feature?

**Comment by Hixie** [comment]
This is not on our short-term priority list, though we would be happy to review patches to add this functionality.

**Comment by brusinovic** [comment]
Dismissible is great, but it can be too destructive in certain scenarios.
I would like to implement "Are you sure" dialog for dismissal of some important info, but it cannot be done without undo method...

**Comment by brusinovic** [comment]
Here is a simple undo trick: **define random keys**

`key: new Key(object.actualKey + Random().nextInt(10000).toString()),`
`onDismissed: (direction) => _askDelete(object),`

_askDelete must refresh state on OK and CANCEL, and dismissible is fooled by new set of objects with every state refresh.

**Comment by Sun3** [comment]
Any updates, it would be great to have the Dismissible have multiple options to Delete or other ones. In our case Delete, Share, Save and so on. Of course without adding buttons on the ListTile, they should be hidden until the user Swipes horizontally.

Thanks.

**Comment by githubabu** [comment]
I too would like to see more options added to the background of the dismissable, it would make it so much more useful. Even an undo element, I currently undo a dismissables actions in the snack bar and while that works well there is no animation once the element is restored.

**Comment by longfellowone** [comment]
Add another for a built in undo!

**Comment by martinmc666** [comment]
Is there any other control that you can swipe left / right to show a button to press to confirm what you want to do. i.e. swipe left to see a delete button on which you can click to confirm

**Comment by eggzotic** [comment]
@martinmc666 check out flutter_slidable at https://pub.dev/packages/flutter_slidable

**Comment by jdiego0102** [comment]
> @ martinmc666 echa un vistazo a flutter_slidable en https://pub.dev/packages/flutter_slidable

Oye amigo, GRACIAS! esto ha solucionado mi problema después de estar 2 días en esto, saludos desde Cali-Colombia.

**Comment by Ahmadre** [comment]
it is possible with actual implementation: https://medium.com/flutter-community/an-in-depth-dive-into-implementing-swipe-to-dismiss-in-flutter-41b9007f1e0

**Comment by eggzotic** [comment]
> it is possible with actual implementation: https://medium.com/flutter-community/an-in-depth-dive-into-implementing-swipe-to-dismiss-in-flutter-41b9007f1e0

I think this is only true when using the confirmDismiss option - from what I can see in that article you quote. Or have I missed something? But that's not what the OP is wanting. We'd like to use Dismissible for swiping to perform actions other than removing an item (e.g. to "mark message as unread"). For this use-case I think the flutter_slidable is still the best alternative.
