### ISSUE TITLE
ShaderMask not support in web mode

### ISSUE THREAD

**Issue by zjrwdl** [flutter/flutter#118228]
Yes please if you have time!  That way this bug will get triaged and someone will look at it.

_Originally posted by @justinmc in https://github.com/flutter/flutter/issues/44152#issuecomment-867787802_

1、flutter version:
Flutter 3.3.8 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 52b3dc25f6 (9 周前) • 2022-11-09 12:09:26 +0800
Engine • revision 857bd6b74c
Tools • Dart 2.18.4 • DevTools 2.15.0

2、reproduce steps:
* flutter run -d chrome .
* set chrome to mobile browse size in develop tool .
* use code like this:

```dart
 ShaderMask(
            shaderCallback: (bounds) {
              return LinearGradient(
                 colors: [Color(0xffA475DF), Color(0xff58B4EE)],
                 ) .createShader(Offset.zero & bounds.size);
            },
            blendMode: BlendMode.srcATop,
            child: Text('test'),
   ),
```

```
exception stack:

Another exception was thrown: Assertion failed: org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/embedder.dart:520:12
──────────────────────────────────────
Another exception was thrown: PersistedOffset: is in an unexpected state.
Another exception was thrown: PersistedOffset: is in an unexpected state.
Another exception was thrown: PersistedOffset: is in an unexpected state.
Another exception was thrown: PersistedOffset: is in an unexpected state.
```

**Comment by danagbemava-nc** [comment]
Hi @zjrwdl, does the screenshot below capture the second point in your steps to reproduce? 

Can you also upgrade to the latest version of flutter stable(3.3.10) to see if you still experience this issue?

<details>
<summary>screenshot</summary>

<img width="1139" alt="Screenshot 2023-01-10 at 09 51 21" src="https://user-images.githubusercontent.com/88313112/211518751-4f90d9f3-3f90-45fa-bb89-81c6b3e8f6c1.png">

</details>

<details>
<summary>sample used</summary>

```
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: ShaderMask(
            shaderCallback: (bounds) {
              return const LinearGradient(
                colors: [Color(0xffA475DF), Color(0xff58B4EE)],
              ).createShader(Offset.zero & bounds.size);
            },
            blendMode: BlendMode.srcATop,
            child: const Text('test', style: TextStyle(fontSize: 48),),
          ),
        ),
      ),
    );
  }
}
```
</details>
