### ISSUE TITLE
[tool_crash] Tried run on oldest device and flutter crashed with message: String: <57 characters>

### ISSUE THREAD

**Issue by ndasim** [flutter/flutter#118202]
I tried to debug my application on the oldest device (Samsung SM-T287) and flutter crashed. Only a black screen appeared. Following output generated by flutter command line tool

## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=310088c61c2c5400 --start-paused --no-sound-null-safety --profile --cache-sksl --dart-define=flutter.inspector.structuredErrors=true lib/main.dart
```

## Steps to Reproduce
1. Connect oldest device, mine was Samsung SM-T287 7'' Tablet
2. And try running any application

## Logs
String: <57 characters>
```

```
```
[✓] Flutter (Channel stable, 3.3.9, on macOS 12.1 21C52 darwin-arm, locale en-GB)
    • Flutter version 3.3.9 on channel stable at /Users/ndasim/fvm/versions/3.3.9
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b8f7f1f986 (7 weeks ago), 2022-11-23 06:43:51 +0900
    • Engine revision 8f2221fbef
    • Dart version 2.18.5
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/ndasim/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F100
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.74.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.56.0

[✓] Connected device (4 available)
    • SM T287 (mobile)                     • 310088c61c2c5400 • android-arm    • Android 5.1.1 (API 22)
    • Android SDK built for arm64 (mobile) • emulator-5554    • android-arm64  • Android 10 (API 29) (emulator)
    • macOS (desktop)                      • macos            • darwin-arm64   • macOS 12.1 21C52 darwin-arm
    • Chrome (web)                         • chrome           • web-javascript • Google Chrome 108.0.5359.124

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 3.0.14+214
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 5464c5bac742001448fe4fc0597be939379f88ea
### Plugins
android_id-0.1.3+1
audio_session-0.1.13
background_fetch-1.1.2
connectivity_plus-3.0.2
device_info_plus-8.0.0
file_picker-5.2.4
flutter_background_geolocation-4.8.5
flutter_barcode_scanner-2.0.0
flutter_jailbreak_detection-4e235efd4d5df9d1994cd1d377a0093833293684
flutter_keyboard_visibility-5.4.0
flutter_keyboard_visibility_linux-1.0.0
flutter_keyboard_visibility_macos-1.0.0
flutter_keyboard_visibility_web-2.0.0
flutter_keyboard_visibility_windows-1.0.0
flutter_plugin_android_lifecycle-2.0.7
flutter_tts-3.5.3
geolocator-9.0.2
geolocator_android-4.1.4
geolocator_apple-2.2.3
geolocator_web-2.1.6
geolocator_windows-0.1.1
google_maps_flutter-2.2.3
google_maps_flutter_android-2.4.0
google_maps_flutter_ios-2.1.12
google_maps_flutter_web-0.4.0+3
heresdk-navigate-flutter-4.12.11.0.3261
image_picker-0.8.6
image_picker_android-0.8.5+4
image_picker_for_web-2.1.10
image_picker_ios-0.8.6+5
just_audio-0.9.31
just_audio_web-0.4.7
optimize_battery-0.0.4
package_info_plus-3.0.2
path_provider-2.0.11
path_provider_android-2.0.22
path_provider_ios-2.0.11
path_provider_linux-2.1.7
path_provider_macos-2.0.6
path_provider_windows-2.1.3
permission_handler-10.2.0
permission_handler_android-10.2.0
permission_handler_apple-9.0.7
permission_handler_windows-0.1.2
sentry_flutter-6.18.1
shared_preferences-2.0.15
shared_preferences_android-2.0.14
shared_preferences_ios-2.1.1
shared_preferences_linux-2.1.2
shared_preferences_macos-2.0.5
shared_preferences_web-2.0.4
shared_preferences_windows-2.1.2
sqflite-2.2.2
store_redirect-2.0.1
url_launcher-6.1.7
url_launcher_android-6.0.22
url_launcher_ios-6.0.17
url_launcher_linux-3.0.1
url_launcher_macos-3.0.1
url_launcher_web-2.0.13
url_launcher_windows-3.0.1
vibration-1.7.6
wakelock-0.6.2
wakelock_macos-0.4.0
wakelock_web-0.4.0
flutter_zebra_utility-4029f3615b6f440d77f91d1ba375fefd07f1eb82

**Comment by darshankawar** [comment]
Thanks for the report @ndasim 
Do you get any error log while running the app ? If so, can you provide the same ? 
Going by the error, it looks similar to https://github.com/flutter/flutter/issues/108812
