### ISSUE TITLE
Dragging the collapsed cursor doesn't match native

### ISSUE THREAD

**Issue by justinmc** [flutter/flutter#118268]
When dragging the collapsed cursor in a text field on Android and iOS, 1. the loupe does not appear and 2. edge scrolling doesn't work.  This is referring to dragging the cursor itself, not dragging the collapsed selection handle (which does work on Android and doesn't exist on iOS).

| Scenario | Dragging the collapsed handle | Dragging the cursor |
| --- | --- | --- |
| Flutter on Android | ✅ ![android_handle](https://user-images.githubusercontent.com/389558/211648278-48ae547d-16ca-4644-90c6-96248beee168.gif) | ❌  ![android_cursor](https://user-images.githubusercontent.com/389558/211648248-61467a4b-9e30-402d-8dc3-3fe1bc277c5f.gif)  |
| Flutter on iOS | n/a | ❌  ![ios_drag](https://user-images.githubusercontent.com/389558/211649048-7bf934ee-0fd0-46d1-a574-bcffd86a1c19.gif) |

### Steps to reproduce

 1. Run any app with multiple lines of editable text, such as the one given below.
 2. Tap to place the cursor.
 3. Perform a drag gesture on the cursor.

Expected: The cursor follows the drag, the loupe appears, and edge scrolling works.
Actual: The cursor does follow the drag, but the loupe doesn't appear, and scrolling off the edge causes the cursor to stop following the drag instead of scrolling.

<details>

<summary>Repro code</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final TextEditingController _controller = TextEditingController(
    text: 'Lorem ipsum dolor sit amet,\nconsetetur sadipscing elitr,\nsed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat,\nsed diam voluptua.\nAt vero eos et accusam et justo duo dolores et ea rebum.\nStet clita kasd gubergren,\nno sea takimata sanctus est Lorem ipsum dolor sit amet.',
  );

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            TextField(
              controller: _controller,
              minLines: 4,
              maxLines: 4,
            ),
          ],
        ),
      ),
    );
  }
}
```

</details>

**Comment by justinmc** [comment]
CC @Renzo-Olivares, you mentioned that this was probably caused by your tap and drag work.

**Comment by Renzo-Olivares** [comment]
This looks its the expected behavior on native iOS and Android. I tried in `iMessage` and the cursor will not follow the drag unless the drag begins on the cursor itself. If it doesn't the TextField just scrolls up and down.

**Comment by Renzo-Olivares** [comment]
On native Android I'm noticing that scrolling up and down, the cursor doesn't exactly move with the drag but it is placed somewhere in the current visible text view.
