### ISSUE TITLE
Clarify the check for the number of reviews that are required if author is not a member of the flutter-hackers

### ISSUE THREAD

**Issue by ricardoamador** [flutter/flutter#118354]
It would be helpful to clarify the check for the number of reviews on a PR if the author is not a member of the flutter-hackers community. Currently it does not state directly that the author needs a certain number of reviews based on who they are.

```
auto label is removed for flutter/engine, pr: 38775, due to - Please get at least one approved review if you are already a member or two member reviews if you are not a member before re-applying this label. Reviewers: If you left a comment approving, please use the "approve" review action instead.
```

We should apply a status that states the number of required reviews for the current author.

**Comment by godofredoc** [comment]
@ricardoamador is this an easy fix?

**Comment by ricardoamador** [comment]
yes it is. It is on my list of things to do but rotation is crazy this week.
