### ISSUE TITLE
☂️ Proposal to make improvements to existing new issue templates.

### ISSUE THREAD

**Issue by darshankawar** [flutter/flutter#118306]
Based on the discussion happened on [discord](https://discord.com/channels/608014603317936148/608031412401995796/1058095777274155118), we thought of proposing below ideas / improvements to the existing new issue template.

## Use case

We as triagers come across a lot of issues that are either: 

1. Empty (ie, only has template skeleton, but no details inside it)
2. Duplicate of existing open issues.

As an example, see below recent empty issues that were filed with no details that we closed due to lack of information:

https://github.com/flutter/flutter/issues/117521
https://github.com/flutter/flutter/issues/118251
https://github.com/flutter/flutter/issues/118241
https://github.com/flutter/flutter/issues/118235
https://github.com/flutter/flutter/issues/118225 

This [filter](https://github.com/flutter/flutter/issues?q=is%3Aissue+commenter%3Adanagbemava-nc+commenter%3A%22darshankawar%22+commenter%3A%22huycozy%22+label%3A%22r%3A+duplicate%22+is%3Aclosed+) for duplicates that we closed as applicable with `r: duplicate` label.

## Proposal

1. To avoid OP filing an empty issue, if we could introduce `required` fields , so that we will have enough details to act on the filed issue. As an example:

`[REQUIRED]` in front of each section or atleast for `code sample` and `logs`

2. A `Duplicate check` section, something like below: 

<img width="495" alt="Screenshot 2023-01-11 at 1 04 29 PM" src="https://user-images.githubusercontent.com/67046386/211756369-a1fb0ec5-88b4-4b34-8882-58b65f542b6a.png">

3. Improving the title / text of below template specifically:

<img width="1162" alt="Screenshot 2023-01-11 at 1 32 11 PM" src="https://user-images.githubusercontent.com/67046386/211756937-a2a14fd6-40a4-4435-914b-fc2b3298fece.png">

 
To something like `Report a bug` with description `Think you found a bug in the framework / SDK? Report it here.`, so that this will make OP to only file genuine framework related bugs and hopefully not general issue which may not be related to the framework. For that, we can direct them to `I want help writing my application` option.

## Templates

- [x] #119914
- [x] #119918
- [x] #119919
- [x] #119920
- [x] #119921
- [x] #119922
- [x] #117750

## Concluding note

We understand that above proposal is subject to how OP would look at it and whether they would make use of it or not depending on their approach to file the issue, but it will help to reduce the noise of the issues that would most likely get closed as invalid / duplicates and we would see more genuine framework related bugs.

**Comment by khyati82** [comment]
CC @Hixie

**Comment by Hixie** [comment]
Please feel absolutely empowered to adjust the templates as you see fit.

**Comment by ricardoamador** [comment]
This is not an infra issue. Any team can update templates in the repositories.

**Comment by huycozy** [comment]
Closing this issue as all templates have been migrated.
