### ISSUE TITLE
Codelabs Building a game with Flutter and Flame text mistake

### ISSUE THREAD

**Issue by korgmp3** [flutter/flutter#118341]
[Building a game with Flutter and Flame](https://codelabs.developers.google.com/codelabs/flutter-flame-game)
 on this page written that function configure is in lib/game/doodle_dash.dart
but it is in lib/game/managers/object_manager.dart file

**Comment by parlough** [comment]
\cc @khanhnwin

From step 5: Add platforms

<img width="795" alt="Code block with incorrect file label" src="https://user-images.githubusercontent.com/18372958/211997905-e45a1086-66fd-468e-a6af-70dbc6642a1a.png">

**Comment by domesticmouse** [comment]
PTAL @khanhnwin

**Comment by domesticmouse** [comment]
Another one for you @ericwindmill =)

**Comment by parlough** [comment]
This codelab has been superseded by a new [Introduction to Flame with Flutter](https://codelabs.developers.google.com/codelabs/flutter-flame-brick-breaker#0) codelab in which you "will build a game inspired by one of the classics of ‘70s video games, Steve Wozniak's [Breakout](https://en.wikipedia.org/wiki/Breakout_(video_game))". Definitely check it out!

Thanks again for reporting this :D
