### ISSUE TITLE
`TransformationController` translate, scale

### ISSUE THREAD

**Issue by FMorschel** [flutter/flutter#118332]
## Use case

I was creating a full-screen pdf viewer (using `InteractiveViewer`) and decided to create some "shortcuts" so my users have a better experience while zooming. I was struggling a lot with the `Matrix4` in order to scale with my anchor being the centre of the current frame. I was inspired by #67211.

## Proposal

I believe it would be really nice if Flutter could abstract some basic interactions with the `Matrix4` inside the `TransformationController` so that some basic transformations could be solved more easily.

I'm not 100% sure how to handle 3D cases and if they should be implemented together or after the 2D part was done. But I was imagining something like:

```dart
controller.scale(2, Alignment.center); //Scaling 2x the current image keeping the centre as an anchor instead of the topLeft
controller.translate(offset); //Translating only X and Y (at least in this case)
```

**Comment by darshankawar** [comment]
Thanks for the report @FMorschel 
I think this looks similar to https://github.com/flutter/flutter/issues/58997, so can you check that and confirm ? Accordingly, you may follow-up in that issue for further updates.

**Comment by FMorschel** [comment]
Yes it is similar, although I believe that my issue has a better name, and is more clear about what we want, I'm going to close this and follow up there.
