### ISSUE TITLE
Remove all usage of `ViewConfiguration.window` from the framework

### ISSUE THREAD

**Issue by a-wallen** [flutter/flutter#118329]
https://github.com/flutter/engine/pull/38453, removed `FlutterWindow` which caused the property `ViewConfiguration.window` to be semantically incorrect; therefore it was renamed to `ViewConfiguration.view`. Remove each usage of `ViewConfiguration.window` and replace it with `ViewConfiguration.view`.

**Comment by dkwingsmt** [comment]
I tried to remove `ViewConfiguration.window` from `bin/cache`, ran `flutter test` in `packages/flutter` and saw no compiling errors. I assume that means this issue is no more.
