### ISSUE TITLE
Proposal to add Gray to colors.dart

### ISSUE THREAD

**Issue by ronnross** [flutter/flutter#118394]
## Use case

While styling a Flutter application I came across a potential issue. I was using the `Colors` object from the `flutter/material` package. I rapidly typed `Colors.gray`. Since `Colors` uses the American spelling I assumed `Gray` would use the American spelling.  I received this warning in in my editor 

```
The getter 'gray' isn't defined for the type 'Colors'.
```

I went through several steps to figure out what I had done wrong and only have after looking at the `colors.dart` file did I discover the British spelling. I believe just being consistent and which spelling system a library choose will cut down on friction while developing.  

## Proposal

Please consider adding `gray` and `blueGray` to `colors.dart`. This would would avoid the issue above, and allow for backwards compatibility for folks already using Grey.

**Comment by bartekpacia** [comment]
See also #24722

**Comment by darshankawar** [comment]
Thanks for the report. 

<img width="252" alt="Screenshot 2023-01-13 at 11 40 46 AM" src="https://user-images.githubusercontent.com/67046386/212250278-e9d31dfc-2da8-4901-806d-4758d5e2f83c.png">

**Comment by darshankawar** [comment]
Actually, looking at https://github.com/flutter/flutter/issues/24722, it already has the same proposal:

<img width="304" alt="Screenshot 2023-01-13 at 11 45 40 AM" src="https://user-images.githubusercontent.com/67046386/212250650-69345b0d-460c-4ac3-be47-5ec92964b035.png">

So @ronnross please follow-up in the original issue for further updates. I'll close this as a duplicate.
