### ISSUE TITLE
Can't include firebase_database

### ISSUE THREAD

**Issue by chrislondon** [flutter/flutter#11831]
## Steps to Reproduce

1) Added firebase_database to my pubspec.yaml:

    firebase_database: '>=0.1.0'

2) Updated packages:

    flutter packages get

3) Imported firebase into my app

    import 'package:firebase_database/firebase_database.dart';

4) Attempted to run app

    flutter run

## Logs

`flutter run` output:

```
Running "flutter packages get" in FlutterApp...       0.3s
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...                                0.6s
Resolving dependencies...                             1.0s
Running 'gradlew assembleDebug'...                        
Note: /home/chris/.pub-cache/hosted/pub.dartlang.org/firebase_database-0.1.0/android/src/main/java/io/flutter/plugins/firebase/database/FirebaseDatabasePlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:packageDebug'.
> !zip.isFile()

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
Gradle build failed: 1
```

`flutter analyze` output:

```
Analyzing /home/chris/Development/Parakeet/FlutterApp...
No issues found!
Ran in 5.5s
```

## Flutter Doctor

```
[✓] Flutter (on Linux, locale en_US.UTF-8, channel alpha)
    • Flutter at /home/chris/Development/Atlast/flutter
    • Framework revision b156a0f054 (3 weeks ago), 2017-08-11 22:01:40 -0700
    • Engine revision fef7d827d6
    • Tools Dart version 1.25.0-dev.9.0

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at /home/chris/Android/Sdk
    • Platform android-25, build-tools 25.0.3
    • Java binary at: /home/chris/Development/Atlast/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] Android Studio (version 2.3)
    • Android Studio at /home/chris/Development/Atlast/android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.2)
    • Flutter plugin version 16.0
    • Dart plugin version 172.3968.20

[✓] Connected devices
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 5.1.1 (API 22) (emulator)
```

**Comment by chrislondon** [comment]
Nevermind,

`flutter build clean`
`flutter run`

It's now working.

**Comment by zoechi** [comment]
@AnandAron the current version is `1.0.1`, it's unlikely such an old version can still be used with other dependencies with more recent versions or a recent Flutter version.
If that doesn't fix your problem please create a new issue with full information (`flutter doctor` output, ...)

Closed issues are not monitored and comments are easily overlooked.

**Comment by OfficialSameer** [comment]
Sir My Issue

Launching lib/main.dart on Lenovo A6020a40 in debug mode...
Initializing gradle...                                       7.2s
Resolving dependencies...                                   11.4s
Gradle task 'assembleDebug'...
Note: C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_admob-0.6.1+1\android\src\main\java\io\flutter\plugins\firebaseadmob\AdRequestBuilderFactory.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_webview_plugin-0.2.1+2\android\src\main\java\com\flutter_webview_plugin\WebviewManager.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_webview_plugin-0.2.1+2\android\src\main\java\com\flutter_webview_plugin\WebviewManager.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Gradle task 'assembleDebug'... Done                         399.2s
Built build\app\outputs\apk\debug\app-debug.apk.
Installing build\app\outputs\apk\app.apk...                     -
<Hang>

Application has stopped
plz solve this

**Comment by Gursewak-Uppal** [comment]
@OfficialSameer  I changed version 0.6.1+1 to 0.5.7. It's working for me
