### ISSUE TITLE
switch documentation error

### ISSUE THREAD

**Issue by CrazyBunnyz** [flutter/flutter#118387]
![image](https://user-images.githubusercontent.com/52201618/212081175-2c11217b-e33e-48af-ae94-f63666d6c735.png)

error on documentation : 

/tmp/dartpadZGDTEW/lib/main.dart:60:11: Error: No named parameter with the name 'thumbIcon'.
          thumbIcon: thumbIcon,
          ^^^^^^^^^
flutter-sdks/stable/packages/flutter/lib/src/material/switch.dart:83:9: Context: Found this candidate, but the arguments don't match.
  const Switch({
        ^^^^^^m/52201618/212080990-b120df0f-fd3e-4710-8a0c-3efeab5f3010.png)

**Comment by danagbemava-nc** [comment]
Closing this in favor of https://github.com/flutter/flutter/issues/118161.
