### ISSUE TITLE
Maps in Flutter Aplliction

### ISSUE THREAD

**Issue by TitikshaDaga** [flutter/flutter#11839]
Hey I wanted to ask if there is a way to use the google maps api in the flutter application. I want to avoid using the static maps. Please let me know if there is a way.

**Comment by collinjackson** [comment]
Maps are covered in #73.

**Comment by TitikshaDaga** [comment]
https://github.com/FaisalAbid/flutter-google-maps/issues/1
 Can anyone resolve this??
