### ISSUE TITLE
OverFlowing in DateTimePicker with 'pt' Locale on iPhone10 (iOS 16.2)

### ISSUE THREAD

**Issue by MV1n1c1us** [flutter/flutter#118313]
## The Problem:

I'm currently using the default DateTime Range Picker from Flutter, but i'm using the Portuguese Locale inside my Material App

`supportedLocales: const [
          Locale('pt'),
  ],`

But when i select this dates, the DatePicker Date Text causes a Right Sided overFlow:

_2022-12-20 to 2023-01-01 
2022-12-22 to 2023-01-01 
2022-12-23 to 2023-01-01 
2022-12-24 to 2023-01-01 
2022-12-25 to 2023-01-01 
2022-12-26 to 2023-01-01 
2022-12-27 to 2023-01-01 
2022-12-28 to 2023-01-01 
2022-12-29 to 2023-01-01 
2022-12-30 to 2023-01-01_ 
**(Or any date after 2023-01-01)**

Days 21 and 31 Excluded, there's no overflow from them, maybe it's because the number 1 occupies less space.

This error Occurs on iPhone 10 Emulator (Did not test on any Physical Apple Devices). No overflowing ocurred in Android Emulator or Physical Devices.

## Steps to Reproduce

1. Add:
`supportedLocales: const [
          Locale('pt'),
  ],` 
to your **MaterialApp** 
2. Create a showDateRangePicker Modal Dialog and Call it From a Button (Code in code session)
3. Select any date range listed above

<details>
<summary>Code sample</summary>

```dart
//! Call this from a button of your preference.
    
    DateTimeRange? result = await showDateRangePicker(
        context: context,
        firstDate: DateTime(2022, 1, 1), 
        lastDate: DateTime(2030, 12, 31), 
        currentDate: DateTime.now(),
        saveText: 'Salvar',
    );
```

</details>

<details>
  <summary>Error Expected (Print Screen)</summary>

![B30A6CD1-C298-4651-A306-7D712B774E50](https://user-images.githubusercontent.com/87025582/211787133-9df32301-5ec1-4a98-88e0-c41ffc325471.png)

**Comment by danagbemava-nc** [comment]
Hi @MV1n1c1us,

Please provide your `flutter doctor -v`  [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)

Thank you
