### ISSUE TITLE
[camera] Image stream data is corrupt on some Android devices (Vivo, Xiaomi, Motorola)

### ISSUE THREAD

**Issue by acoutts** [flutter/flutter#118350]
## Steps to Reproduce

1. Run the example app here: https://github.com/acoutts/camera_stream_bug - it will start the image stream, convert the first frame to a color image, and then display the frame.
2. Observe the corrupted image frame if the device is prone to the issue.

I've noticed issues from some users with our app features that rely on the image stream (we use MLKit). I got my hands on some of them to test and found the image stream is producing corrupted frames on these devices, which prevents MLKit from being functional.

So far we've seen the issue on the following devices:
* Vivo V2135
* Xiaomi M2010J19CG
* Motorola moto g(50)

**Expected results:** 
The image stream should produce valid images on all devices. Here is how the sample app looks when run from a Pixel 6:
![IMG_0330](https://user-images.githubusercontent.com/9597207/211933053-afd94cea-c046-42ea-97ea-2c9c4d6d239c.jpg)

**Actual results:** 
It produces a corrupted image like this on the Vivo:
![IMG_0329](https://user-images.githubusercontent.com/9597207/211932849-9992162a-82f2-4bda-8411-629573e974b0.jpg)

This happens irrespective of the camera resolution setting.

<details>
<summary>Code sample</summary>

https://github.com/acoutts/camera_stream_bug

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
[✓] Flutter (Channel stable, 3.3.9, on macOS 13.0.1 22A400 darwin-arm, locale en-US)
    • Flutter version 3.3.9 on channel stable at /Users/andrew.coutts/Projects/flutter
    • Upstream repository git@github.com:flutter/flutter.git
    • Framework revision b8f7f1f986 (7 weeks ago), 2022-11-23 06:43:51 +0900
    • Engine revision 8f2221fbef
    • Dart version 2.18.5
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc2)
    • Android SDK at /Users/andrew.coutts/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc2
    • ANDROID_HOME = /Users/andrew.coutts/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.70.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.46.0

[✓] VS Code (version 1.75.0-insider)
    • VS Code at /Applications/Visual Studio Code - Insiders.app/Contents
    • Flutter extension version 3.56.0

[✓] Connected device (3 available)
    • Pixel 6 (mobile) • 1A051FDF6004H7 • android-arm64  • Android 12 (API 32)
    • macOS (desktop)  • macos          • darwin-arm64   • macOS 13.0.1 22A400 darwin-arm
    • Chrome (web)     • chrome         • web-javascript • Google Chrome 108.0.5359.124

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by huycozy** [comment]
Hi @acoutts 
Unfortunately, I don't have such devices and I also can not reproduce this issue on my devices (Pixel 3a, Samsung Galaxy Tab A7, Realme 6). 

But I check some existing issues and see that issue #27686 seems to be similar. Can you take a look at https://github.com/flutter/flutter/issues/27686#issue-408176271 and check if there is also wrong number of pixels on your devices?

**Comment by acoutts** [comment]
Printing some data, when I request YUV420 as the image format (the default anyways), on the Pixel 6 the U and V planes are very close to Y/2 (off by just 1). But on the Vivo, it's actually off by 129. I don't know a lot about this but it seems close to 128 which is a suspiciously "round" number.

Pixel 6:
```
Y len: 921600
U len: 460799
V len: 460799
```

Vivo:
```
Y len: 1105664
U len: 552703
V len: 552703
```

Looking at the android docs here it feels more like this image is actually YV12 format, not YUV420 as requested.
https://developer.android.com/reference/android/graphics/ImageFormat#YV12

>YV12 is a 4:2:0 YCrCb planar format comprised of a WxH Y plane followed by (W/2) x (H/2) Cr and Cb planes.

In either case it seems okay on the pixel but something is off on the Vivo.

**Comment by acoutts** [comment]
I dumped some image frames so we can look at the raw data now. I did it from the pixel 6 and vivo so we have a good/bad to compare. Both had the camera set to YUV420 and max resolution size. In both cases the camera plugin indicated from the image stream it was receiving 1280x720 images.

[yuv-images.zip](https://github.com/flutter/flutter/files/10404525/yuv-images.zip)

In both cases we requested the camera give us YUV420 frames and we then concatenated the planes as Y,U,V to create an NV21 image which is the usual routine when you want to feed camera frames into MLKit.

```dart
    final concatenated = Uint8List.fromList(
      [
        ...image.planes[0].bytes,
        ...image.planes[1].bytes,
        ...image.planes[2].bytes,
      ],
    );
```

Here is the frame from the pixel - we can easily decode it into a valid image by selecting the NV21 preset and 1280x720 as the size:
<img width="1695" alt="Screenshot 2023-01-12 at 12 55 21 PM" src="https://user-images.githubusercontent.com/9597207/212143089-a9249195-ac91-4958-96ee-d32f6d2d125a.png">

But the vivo doesn't work as expected. Using the same settings, it looks like this:
<img width="1674" alt="Screenshot 2023-01-12 at 12 58 16 PM" src="https://user-images.githubusercontent.com/9597207/212143334-3459c359-c755-4944-8e30-5cf5aee18d47.png">

Playing with it a little bit, we know the bytesPerRow (row stride) is being reported as 1536 or some reason, let's try with a width of 1536:
<img width="1678" alt="Screenshot 2023-01-12 at 12 59 03 PM" src="https://user-images.githubusercontent.com/9597207/212143495-1deb4b92-4663-4c11-991f-8f1c4b687ec7.png">

Now we have a valid grayscale image but the U and V are wrong, hence the green stripe. It seems like some kind of padding issue but I don't understand this enough yet to know what's wrong or how to fix it.

**Comment by acoutts** [comment]
It doesn't feel like this is a case where the manufacturer simply implemented the camera wrong. Both the vivo and the xiaomi have the exact same behavior with the bytesPerRow being 1536 instead of 1280 (image width),  and the image is displayed exactly the same as the screenshots above.

**Comment by acoutts** [comment]
I managed to make it work on the "broken" devices. To my surprise it only worked if I used the new padding function on the Y channel - I had to leave U/V alone.

Commit with changes:
https://github.com/acoutts/plugins/commit/37be5c54685562dd71ba41ab005224e0085c38a0

To try the patched camera, you can use:
```yaml
dependency_overrides:
  camera_android:
    git:
      url: https://github.com/acoutts/plugins.git
      path: packages/camera/camera_android
      ref: 37be5c54685562dd71ba41ab005224e0085c38a0
```

The changes modify the image stream handler like this:
```java
private void setImageStreamImageAvailableListener(final EventChannel.EventSink imageStreamSink) {
    imageStreamReader.setOnImageAvailableListener(
        reader -> {
          Image img = reader.acquireNextImage();

          // Use acquireNextImage since image reader is only for one image.
          if (img == null) return;

          List<Map<String, Object>> planes = new ArrayList<>();
          for (Image.Plane plane : img.getPlanes()) {
            Map<String, Object> yPlaneBuffer = new HashMap<>();
            yPlaneBuffer.put("bytesPerPixel", plane.getPixelStride());

            // Now process the plane byte data. We sometimes have to correct the luma channel (Y)
            // because some devices have some kind of extra padding included. From testing it seems
            // like we do not have to modify the U/V channels, just the Y channel for this case.
            if (plane.getRowStride() != img.getWidth() && plane.getPixelStride() == 1) {
              // There is some padding we have to handle
              yPlaneBuffer.put("bytes", getPixels(plane.getBuffer(), img.getWidth(), img.getHeight(), plane.getRowStride(), plane.getPixelStride()));
              yPlaneBuffer.put("bytesPerRow", Math.min(plane.getRowStride(), img.getWidth()));
            } else {
              // Just use the data as-is
              ByteBuffer buffer = plane.getBuffer();
              byte[] bytes = new byte[buffer.remaining()];
              buffer.get(bytes, 0, bytes.length);
              yPlaneBuffer.put("bytes", bytes);
              yPlaneBuffer.put("bytesPerRow", plane.getRowStride());
            }
            planes.add(yPlaneBuffer);
          }

          Map<String, Object> imageBuffer = new HashMap<>();
          imageBuffer.put("width", img.getWidth());
          imageBuffer.put("height", img.getHeight());
          imageBuffer.put("format", img.getFormat());
          imageBuffer.put("planes", planes);
          imageBuffer.put("lensAperture", this.captureProps.getLastLensAperture());
          imageBuffer.put("sensorExposureTime", this.captureProps.getLastSensorExposureTime());
          Integer sensorSensitivity = this.captureProps.getLastSensorSensitivity();
          imageBuffer.put(
              "sensorSensitivity", sensorSensitivity == null ? null : (double) sensorSensitivity);

          final Handler handler = new Handler(Looper.getMainLooper());
          handler.post(() -> imageStreamSink.success(imageBuffer));
          img.close();
        },
        backgroundHandler);
  }

  // Adopted from:
  // https://github.com/abrenoch/hyperion-android-grabber/blob/c2befd7501c72f93f5c022666266f67142fe8ba3/common/src/main/java/com/abrenoch/hyperiongrabber/common/HyperionScreenEncoder.java#L154-L177
  //
  // Will return a new byte buffer with padding accounted for.
  private byte[] getPixels(ByteBuffer buffer, int width, int height, int rowStride, int pixelStride){
    int rowPadding = rowStride - width * pixelStride;
    int offset = 0;

    ByteArrayOutputStream bao = new ByteArrayOutputStream(
            width  * height  * 3
    );

    for (int y = 0, compareHeight = height - 1; y < height; y++, offset += rowPadding) {
      if ( y > compareHeight) {
        offset += width * pixelStride;
        continue;
      }

      for (int x = 0, compareWidth = width - 1; x < width; x++, offset += pixelStride) {
        if (x > compareWidth) continue;
        if (offset > buffer.remaining()) continue;
        bao.write(buffer.get(offset));
      }
    }

    return bao.toByteArray();
  }
```

Here is the demo app running on the Xiaomi after the patch:
![image](https://user-images.githubusercontent.com/9597207/212206529-24d36294-3752-436a-8f6f-0eb9ce4ef09b.png)

**Comment by huycozy** [comment]
@acoutts Thanks for your deep investigation on this. 

My colleague also tries reproducing this with his device `Vivo V21 (Android 12)` but he doesn't see glitches but it does freeze the camera.

This issue seems to be happening on specific devices. Labeling the issue for the team's attention.

**Comment by acoutts** [comment]
I've created an abstraction around `ImageReader` to contain the new buffer trimming logic and will work on some tests for it next.

https://github.com/acoutts/plugins/blob/d2492c86feb87e424395112380a4bf3976dae75d/packages/camera/camera_android/android/src/main/java/io/flutter/plugins/camera/media/ImageStreamReader.java

**Comment by acoutts** [comment]
Added tests and a PR here: https://github.com/flutter/plugins/pull/6985

**Comment by GaryQian** [comment]
cc @camsim99

**Comment by pktwins** [comment]
Finally i have fixed this bug if anyone wants to know message me

**Comment by jomagsm** [comment]
> 

I would be grateful if you could tell me how to solve the problem

**Comment by pktwins** [comment]
Sure I will fix and give you but I need some fee because i have struggled
for it for many hours.

**Comment by kredens** [comment]
We are having this problem on the following devices:

Motorola moto G9 POWER
Samsung A23

**Comment by pktwins** [comment]
Sure I will fix , let’s have a personal chat pavantinku32@gmail.com message me in mail

**Comment by pktwins** [comment]
I fixed it by changing the configuration in image stream

**Comment by eerbee** [comment]
@pktwins is your fixing same as the PR above? just wondering

**Comment by acoutts** [comment]
Here is the latest PR to use if you want a workaround now: https://github.com/flutter/packages/pull/3277

**Comment by pktwins** [comment]
pavantinku32@gmail.com this is my mail message I fixed that issue even tested in VIVO , Redmi , MOTOROLA mobiles in all these three it’s working fine

**Comment by acoutts-nydig** [comment]
This is now merged into camera 0.10.5 - see my comment here explaining how you might implement using NV21 correctly in your use case.

https://github.com/flutter-ml/google_ml_kit_flutter/issues/287#issuecomment-1549828057

**Comment by mobtex** [comment]
> Finally i have fixed this bug if anyone wants to know message me

This works fine: https://stackoverflow.com/questions/63245975/camerax-image-analysis-convert-image-to-bytearray-or-bytebuffer/68843553#68843553

**Comment by acoutts** [comment]
@mobtex this is already implemented in the latest camera plugin version. My PR does exactly that.

**Comment by xyzacademic** [comment]
> @mobtex this is already implemented in the latest camera plugin version. My PR does exactly that.

Hello, acoutts. I update the camera plugin into 0.10.5. The nv21 works totally correct. But I meet some other issue.

I have a Samsung A23 device. If I select yuv420, the average fps is 30 around, the same as a more powerful phone. But if I select nv21, the fps is only 8~14, which is laggy. But yuv420 still has the padding resolution problem, right? I tried to feed it into MLKit pose detection, but it does not give me poses.

So is there a way to select yuv420 and then modify the function that converts CameraImage to InputImage and supports padding resolution devices also? I appreciate it.

**Comment by acoutts-nydig** [comment]
that's definitely a potential issue on lower end devices. I would say maybe you can get better performance using the camerax plugin but I'm not sure if they implemented nv21 streaming on it yet. Try giving that a shot next.

Sadly it's just the nature of only being able to stream yuv420 in camera2. Either the conversion has to happen in dart or native to nv21 and no matter what that will add latency depending on device performance.

**Comment by xyzacademic** [comment]
> that's definitely a potential issue on lower end devices. I would say maybe you can get better performance using the camerax plugin but I'm not sure if they implemented nv21 streaming on it yet. Try giving that a shot next.
> 
> Sadly it's just the nature of only being able to stream yuv420 in camera2. Either the conversion has to happen in dart or native to nv21 and no matter what that will add latency depending on device performance.

Thank you for relaying me immediately.
Yes, I am thinking if it is possible to rewrite the following function to make it supports padding resolution. It is too hard for me.

```dart
  Future<mp.InputImage?> processCameraImage(CameraImage image) async {
    final WriteBuffer allBytes = WriteBuffer();
    for (final Plane plane in image.planes) {
      allBytes.putUint8List(plane.bytes);
    }
    final bytes = allBytes.done().buffer.asUint8List();

    final Size imageSize =
        Size(image.width.toDouble(), image.height.toDouble());

    final camera = cameras[cameraIndex];
    final imageRotation =
        mp.InputImageRotationValue.fromRawValue(camera.sensorOrientation);
    if (imageRotation == null) return null;

    final inputImageFormat =
        mp.InputImageFormatValue.fromRawValue(image.format.raw);
    if (inputImageFormat == null) return null;

    final planeData = image.planes.map(
      (Plane plane) {
        return mp.InputImagePlaneMetadata(
          bytesPerRow: plane.bytesPerRow,
          height: plane.height,
          width: plane.width,
        );
      },
    ).toList();

    final inputImageData = mp.InputImageData(
      size: imageSize,
      imageRotation: imageRotation,
      inputImageFormat: inputImageFormat,
      planeData: planeData,
    );

    mp.InputImage inputImage =
        mp.InputImage.fromBytes(bytes: bytes, inputImageData: inputImageData);
    return inputImage;
    // processImage(inputImage);
  }
```

**Comment by camsim99** [comment]
Just FYI, image streaming has been implemented in the [CameraX implementation](https://pub.dev/packages/camera_android_camerax) of the camera plugin and the issue should be fixed there, as well! If anyone is willing to test it out on these devices to ensure this is the case, the feedback would be greatly appreciated!!
