### ISSUE TITLE
The tree is red on a git mirroring issue

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#118398]
`Infra Failure: Step('Checkout flutter/flutter.git checkout (4)') (retcode: 128)`

**Comment by zanderso** [comment]
cc @nehalvpatel the infra gardener

**Comment by nehalvpatel** [comment]
Taking a look now.

**Comment by nehalvpatel** [comment]
Some updates:
- I manually mirrored the latest commit and triggered a re-run of all the tasks that had checkout failures. They are about to finish up.
- I reached out to the team behind the internal mirroring service, and they think they have found the issue. They're rolling back the queue.

**Comment by nehalvpatel** [comment]
Update:
- The tree returned to green.
- The autosubmit bot merged a roller PR and it was mirrored automatically.

This seems to be fixed!

I'll close this but continue monitoring.
