### ISSUE TITLE
Debug symbols upload to google play fails because of __MACOSX

### ISSUE THREAD

**Issue by lucicam** [flutter/flutter#118305]
## Steps to Reproduce

1. Execute `flutter build appbundle` on the code sample 
2. Archive the debug symbols
3. Upload to google play

**Expected results:** 
Debug libraries successfully uploaded.

**Actual results:** 
"The native debug symbols contain an invalid directory __MACOSX. Only Android ABIs are supported."

<details>
<summary>Code sample</summary>

```dart
  cupertino_icons: ^1.0.5
  web_socket_channel: ^2.2.0
  flutter_easyloading: ^3.0.5
  google_mobile_ads: ^2.2.0
  flutter_svg: ^1.1.6
  just_audio: ^0.9.30
  connectivity_plus: ^3.0.2
  vibration: ^1.7.5
```

</details>
First of all, I'm sorry if this is the wrong place to report this. Let me know if I should report it in another place.

The first version of the app it worked to upload the debug symbols but after I have made some updates (the only major thing I did was that I added the "vibration" package) it stopped being able to upload because of that error. Can this be from that library? (it doesn't even have the macos as a supported platform.

I removed the macos folder from the project (as I don't use it and thought it might interfere). That didn't fix the issue.

Not sure what is this related to or how can I check more into it. I also can't find anything on the internet related to this. Let me know if I can provide more details.

**Comment by exaby73** [comment]
Hello @lucicam. `__MACOSX` is generated by MacOS and not Flutter. Here is a link explaining what it is: https://superuser.com/a/104501

Can you provide steps to reproduce this issue along with a [complete and minimal, reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) if applicable?
