### ISSUE TITLE
Nested TabBarViews using NestedScrollView multiple issues

### ISSUE THREAD

**Issue by mohamoha6200** [flutter/flutter#118396]
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. Scroll down the outer NestedScrollView
3. Scroll up the inner TabbarView inner tab 1 content
4. Scroll to outer tab 2
5. Scroll the area above the outer Tabbar and try to show it again by scolling the inner Colored SliverList

**Expected results:** 
The NestedScrollViews are expected to be synced.
Inner SliverAppBar to be pinned.
The Exceptions thrown to not exist. 

**Actual results:** 
 Inner scroll does not affect the outer one, NestedScrollViews are NOT in Sync.
 The outer SliverAppBar is Being Pinned as expected but the inner one is NOT.
Changing Tabs results in different exceptions : 
```
1 package:flutter/src/widgets/nested_scroll_view.dart': Failed assertion: line 776 pos 16: 'extra >= 0.0': is not true.
2 Null check operator used on a null value
3 package:flutter/src/rendering/object.dart': Failed assertion: line 3093 pos 12: '!_debugDisposed': is not true.
4 package:flutter/src/widgets/scrollable.dart': Failed assertion: line 653 pos 12: '_drag == null': is not true.
```

<details>
<summary>Code sample</summary>

(https://gist.github.com/mohamoha6200/58a3b537b367367e28b85bde3a026c4a)
```
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
[√] Flutter (Channel stable, 3.3.10, on Microsoft Windows [Version 10.0.19044.2486], locale en-US)
    • Flutter version 3.3.10 on channel stable at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (4 weeks ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\AndroidSDK
    • Platform android-33, build-tools 30.0.3
    • ANDROID_HOME = C:\AndroidSDK
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] VS Code (version 1.74.3)
    • VS Code at C:\Users\Moha Work\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.56.0

[√] Connected device (4 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)                  • windows       • windows-x64    • Microsoft Windows [Version 10.0.19044.2486]
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 108.0.5359.125
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 108.0.1462.54

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.
```

</details>

**Comment by darshankawar** [comment]
@mohamoha6200 thanks for the report.
It seems that there are multiple use cases and exceptions upon running your code sample, so a better way to track and address each of them is to file separate issue for each with all relevant details, so that it'll be easier to analyze and address them individually instead of clubbing all scenarios and exceptions together in one issue, so I encourage you to file separate issues for each.

Also, looking at some of the exceptions received, one of them is:

```
Looking up a deactivated widget's ancestor is unsafe.

To safely refer to a widget's ancestor in its dispose() method, save a reference to the ancestor by calling dependOnInheritedWidgetOfExactType() in the widget's didChangeDependencies() method.
```

This probably indicates a code implementation issue rather than the bug, so I suggest you to look for similar issues filed already and also crosscheck your implementation related to listeners and whether you are properly disposing the object per widget's lifecyle. 

Regarding other exceptions, `'_drag == null': is not true.`, please check if [this](https://github.com/flutter/flutter/issues/14452) is relevant to your case.

Take a look at [this](https://github.com/flutter/flutter/issues/79077) issue as well for your reference.

**Comment by mohamoha6200** [comment]
Thank you for the  fast reply @darshankawar 
Actually my least concern is the dispose issue since it's just a minimalistic code to easily reproduce the problem(s).
I find little to no utility in the links provided especially when some of them have yet to be solved.
I would appreciate if there was a straight answer for the possibility of having nested tabBarViews in Flutter where both the inner and outer scrolls can be synced, I'm having trouble finding any close example to my use case.

**Comment by darshankawar** [comment]
Thanks for the feedback @mohamoha6200 


> I would appreciate if there was a straight answer for the possibility of having nested tabBarViews in Flutter where both the inner and outer scrolls can be synced, I'm having trouble finding any close example to my use case.

Please take a look at below similar issues (although they are still open, but will probably give you an idea):

https://github.com/flutter/flutter/issues/54059
https://github.com/flutter/flutter/issues/81619
https://github.com/flutter/flutter/issues/40740
https://github.com/flutter/flutter/issues/36419

**Comment by darshankawar** [comment]
> is there a sample code where a tabBarView could be nested inside another tabBarView ?

See if below links help:

https://stackoverflow.com/questions/56071956/how-to-make-tabview-inside-another-tabview-in-flutter

https://stackoverflow.com/questions/67812878/navigation-within-tab-view-body-flutter

https://github.com/flutter/flutter/issues/54827
