### ISSUE TITLE
[Web] Font ligatures handled differently between web renderers

### ISSUE THREAD

**Issue by emmett-deen** [flutter/flutter#118362]
## Steps to Reproduce

1. Create a Flutter web project and use a font that supports ligatures (In this case Inter)
2. Run the project with the command line argument `--web-renderer html`
3. Run the project with the command line argument `--web-renderer canvaskit`
4. Compare
<img width="512" alt="Xnapper-2023-01-11-21 03 56" src="https://user-images.githubusercontent.com/7634149/211962111-18590fb1-4f5e-498c-a6a0-4587cef72972.png">
<img width="512" alt="Xnapper-2023-01-11-21 05 04" src="https://user-images.githubusercontent.com/7634149/211962117-f4a7a03c-b11f-49d0-94fe-b923ed0225d4.png">

**Comment by exaby73** [comment]
Hello @emmett-deen. Thank you for filing this issue. Can you please provide the following information?

- A [complete and minimal, reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example). Ideally, a single `main.dart` file that can be run directly.
- The output of `flutter doctor -v`

Please provide the information in the form of text. See how to make collapsible sections with Markdown [here](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-collapsed-sections).
