### ISSUE TITLE
Skia roll blocked by a change in canvaskit API

### ISSUE THREAD

**Issue by flar** [flutter/flutter#118375]
See https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8792198508922234593/+/u/felt_test:_chrome-unit-linux-canvaskit/stdout

**Comment by gaaclarke** [comment]
(added p0 since the skia roller is blocked on this)

**Comment by jason-simmons** [comment]
The Skia->engine roll is no longer blocked

(see https://github.com/flutter/engine/pull/38827)
