### ISSUE TITLE
`flutter-flame-game `: document mistake at Step 5 - Add platforms

### ISSUE THREAD

**Issue by NgYewChun** [flutter/flutter#118497]
At **Step 5 - Add platforms**, after  adding onMount() to lib/game/managers/object_manager.dart, 
 **void configure(int nextLevel, Difficulty config)** is belongs to object_manager.dart instead of lib/game/doodle_dash.dart

**Comment by darshankawar** [comment]
@NgYewChun 
Which codelab are you referring to ?

**Comment by NgYewChun** [comment]
ooops!!, sorry, 
here [https://codelabs.developers.google.com/codelabs/flutter-flame-game#5]

**Comment by khanhnwin** [comment]
Thanks for catching this! I've corrected it on our end to be updated :)
