### ISSUE TITLE
[camera] issue with camera plugin for android 13

### ISSUE THREAD

**Issue by aashutosh7** [flutter/flutter#118442]
I am using the latest version of this   camera: ^0.10.1 package and its crashing in android 13 , works fine for older version. 
Here's the stack trace of the crash 

`java.lang.NullPointerException: Attempt to invoke virtual method 'int android.media.EncoderProfiles$VideoProfile.getWidth()' on a null object reference`

**Comment by danagbemava-nc** [comment]
This is a known issue and it's being tracked in https://github.com/flutter/flutter/issues/109769. 

Kindly follow up in the issue linked above for updates. 

Closing from here as duplicate. 

Thank you
