### ISSUE TITLE
jazzy install failing on engine CI

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#118464]
https://ci.chromium.org/p/flutter/builders/try/Mac%20iOS%20Engine

P0 since this will stop PRs from landing.

**Comment by jmagman** [comment]
```
ERROR:  Error installing jazzy:
	sqlite3 requires Ruby version >= 2.7, < 3.3.dev. The current ruby version is 2.6.8.205.
```

**Comment by jmagman** [comment]
sqlite3 [1.6.0](https://rubygems.org/gems/sqlite3/versions/1.6.0-arm64-darwin) released today, previous version 1.3.11 required Ruby `>= 1.8.7`, this version requires `>= 2.7, < 3.3.DEV`.  sqlite3 1.5.3 requires `>= 1.9.2` which should also work?

The version of jazzy being installed on the bot is 0.14.1, which requires `sqlite3 ~> 1.3`.  It might work to install that lower sqlite3 gem version first so jazzy doesn't try to install latest sqlite3 during its install?  

There doesn't seem to be a Gemfile for this, the recipe is running `gem install jazzy:0.14.1`.
```
Executing command [
  '/usr/bin/gem',
  'install',
  'jazzy:0.14.1',
  '--platform',
  'x86_64-darwin',
  '--install-dir',
  '.',
]
```
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8792063477990332337/+/u/install_jazzy/execution_details

@godofredoc is currently working on maintaining our own Ruby cipd packages, which would let us update Ruby to a newer version, too.

@nehalvpatel infra on-call.

**Comment by zanderso** [comment]
This is now also happening on prod https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20iOS%20Engine/19993/overview

**Comment by nehalvpatel** [comment]
Taking a look now.

**Comment by jmagman** [comment]
Also, ideally this would be maintained in a Gemfile in the engine repo so updating these version wouldn't require a recipe changes, the recipe would call `gem install`.  
Example in the framework repo: https://github.com/flutter/flutter/blob/master/dev/ci/mac/Gemfile

**Comment by godofredoc** [comment]
Is it worthy to create a gem file for a single dep? once this is moved to use the dependencies module the values in .ci.yaml will be used to provide the versions of the dep.

**Comment by jmagman** [comment]
The framework example does it for one dep, cocoapods.  In the .ci.yaml case wouldn't adding a dep, like in this case a particular version of `sqlite3` gem, require a recipe change/work by the infra team?  I don't really care about the mechanism, but it should be easy for the repo under test to bump and add dependencies without touching recipes.

**Comment by godofredoc** [comment]
Makes sense, https://github.com/flutter/flutter/issues/118486 will take care of using bundler and remove this independent jazzy dep.

**Comment by nehalvpatel** [comment]
The engine tree is open now. I triggered re-runs on the failed PR checks as well.

**Comment by godofredoc** [comment]
Skia and Dart SDK rollers have been enabled.
