### ISSUE TITLE
[webview_flutter] Webview platform crashes while offline and loading URL

### ISSUE THREAD

**Issue by feinstein** [flutter/flutter#118405]
I have code that detects when there's an error in a webview and shows an error screen on top of the webview, using a `Stack`. The reason why I use a `Stack` is to avoid substituting the webview with the error screen, so the webview doesn't get disposed and its `controller` will be sending commands to a native webview that doesn't exist anymore, and this generates null reference exceptions on Android.

This works most of the time, but sometimes it's not enough. The scenario is simple, I open the webview and then I activate airplane mode in my phone, so the app is offline. Then I click on something on the webview and immediately the offline error screen appears. This error screen has a reload button.

At my first attempt the reload button would just call `controller.reload()`, but this wouldn't work all the time, after a while reload doesn't work anymore for an offline webview. So I changed to just request the current URL again. This works most of the time but still I am getting this exception sometimes:

```dart
PlatformException(NullPointerException, java.lang.NullPointerException: Attempt to invoke virtual method 'void android.webkit.WebView.loadUrl(java.lang.String, java.util.Map)' on a null object reference, Cause: null, Stacktrace: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.webkit.WebView.loadUrl(java.lang.String, java.util.Map)' on a null object reference

I/flutter (18685):              at io.flutter.plugins.webviewflutter.WebViewHostApiImpl.loadUrl(WebViewHostApiImpl.java:278)
I/flutter (18685):              at io.flutter.plugins.webviewflutter.GeneratedAndroidWebView$WebViewHostApi$-CC.lambda$setup$3(GeneratedAndroidWebView.java:749)
I/flutter (18685):              at io.flutter.plugins.webviewflutter.GeneratedAndroidWebView$WebViewHostApi$$ExternalSyntheticLambda10.onMessage(Unknown Source:2)
I/flutter (18685):              at io.flutter.plugin.common.BasicMessageChannel$IncomingMessageHandler.onMessage(BasicMessageChannel.java:217)
I/flutter (18685):              at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
I/flutter (18685):              at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageT
I/flutter (18685):
I/flutter (18685): #0      WebViewHostApi.loadUrl (package:webview_flutter_android/src/android_webview.pigeon.dart:377:7)
```

I can't post my code here, but I think the problem lies in how offline or disposed webview behaves with controllers. I imagine the commands sent to the native side should have null reference checks, and also recreate what's necessary in case the objects were removed.

If you want to reproduce this, try reloading an offline webview, or requesting urls to an offline webview. Try scenarios where the webview is disposed (e.g. substitue it with another widget), also try to place another full screen widget on top of it using a `Stack`, while you send this commands. Try activating airplane mode after the webview has loaded, but also opening the app offline already.

I have only tested it in Android so far and my general feeling is that the flutter webview lacks null check protections on that native code.

**Comment by darshankawar** [comment]
Thanks for the report and details around it @feinstein 
Looking at the exception, it seems very similar to https://github.com/flutter/flutter/issues/114500, so I suggest you to follow-up in it for further updates. That issue describes potential root-cause in depth. You may also share your findings in it for better tracking.

Closing this as a duplicate.
