### ISSUE TITLE
[web]Unable to get stack trace in Release/Profile mode in Flutter web

### ISSUE THREAD

**Issue by motucraft** [flutter/flutter#118451]
Steps to Reproduce

1. Execute `flutter run -d chrome --release` or `flutter run -d chrome --profile` on the code sample 
2. Check the Chrome console. 

**Expected results:** 

Stack traces can be checked.

**Actual results:** 

Why does `StackTrace.current` show error?
Is it not possible to get a stack trace in Release/Profile mode in Flutter web?

There does not seem to be a specific explanation in the API reference.
https://api.flutter.dev/flutter/dart-core/StackTrace-class.html

- flutter run -d chrome --release
![release](https://user-images.githubusercontent.com/35750184/212331052-1f3a334f-b4db-4549-aa57-f195180b8cc3.png)

- flutter run -d chrome --profile
![profile](https://user-images.githubusercontent.com/35750184/212331154-d03aab45-bd57-41b9-9f6b-090ac4602707.png)

- flutter run -d chrome
It works fine in Debug mode. I would like to have this stack trace even in Release/Profile mode, is that not possible?
I have an application built with `flutter build web` and I want to reference the stack trace.
![debug](https://user-images.githubusercontent.com/35750184/212335490-0ac131ec-088b-4521-aa18-0901f1370fc4.png)

Code sample

```dart
import 'package:flutter/material.dart';

void main() {
  print(StackTrace.current);
  runApp(const MaterialApp());
}
```

<details>
  <summary>flutter doctor -v</summary>

```
% flutter doctor -v
[✓] Flutter (Channel stable, 3.3.10, on macOS 13.1 22C65 darwin-arm, locale ja-JP)
    • Flutter version 3.3.10 on channel stable at /Users/osaki/fvm/versions/3.3.10
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (4 weeks ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/osaki/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /Users/osaki/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/213.7172.25.2113.9123335/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Users/osaki/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/213.7172.25.2113.9123335/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.3.1)
    • IntelliJ at /Users/osaki/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 71.3.6
    • Dart plugin version 223.8214.16

[✓] IntelliJ IDEA Ultimate Edition (version 2022.3)
    • IntelliJ at /Users/osaki/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/223.7571.182/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Ultimate Edition (version 2022.3.1)
    • IntelliJ at /Users/osaki/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/223.8214.52/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.74.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.56.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.1 22C65 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 108.0.5359.124
    ! Device emulator-5570 is offline.

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by mraleph** [comment]
There is a no standard API to get stack trace in JS. The best you could do is to take an error and ask it for its `stack` (though even that is non-standard - but at least supported in all browsers we care about). Unfortunately even `Error.stack` contains `Error` on the first line. You can try the following in Chrome Dev Tools console: 

```
> new Error().stack
'Error\n    at <anonymous>:1:1'
```

`dart2js` runtime library could probably try to remove the first line (it just takes the raw value: https://github.com/dart-lang/sdk/blob/f724d8206744505a4883fc31afd4261bdecaeaf7/sdk/lib/_internal/js_runtime/lib/js_helper.dart#L1769). I am not sure why it does not try that. /cc @sigmundch @rakudrama

**Comment by christopherfujino** [comment]
> There is a no standard API to get stack trace in JS. The best you could do is to take an error and ask it for its `stack` (though even that is non-standard - but at least supported in all browsers we care about). Unfortunately even `Error.stack` contains `Error` on the first line. You can try the following in Chrome Dev Tools console:
> 
> ```
> > new Error().stack
> 'Error\n    at <anonymous>:1:1'
> ```
> 
> `dart2js` runtime library could probably try to remove the first line (it just takes the raw value: https://github.com/dart-lang/sdk/blob/f724d8206744505a4883fc31afd4261bdecaeaf7/sdk/lib/_internal/js_runtime/lib/js_helper.dart#L1769). I am not sure why it does not try that. /cc @sigmundch @rakudrama

Do you think there's anything actionable on the Flutter tooling side for this issue?

**Comment by mraleph** [comment]
Probably not. It should be filed against Dart SDK.

**Comment by motucraft** [comment]
Thank you for your comments.
At this time, you are saying that this is not possible as a Dart specification, correct?

**Comment by christopherfujino** [comment]
> Probably not. It should be filed against Dart SDK.

SGTM, thanks.
