### ISSUE TITLE
Using Platform.isAndroid crashes on web build - a tiny simple piece of code would prevent that from happening

### ISSUE THREAD

**Issue by OSonntag** [flutter/flutter#118488]
If you use `Platform.isAndroid` you first need to check if it is not a web build. Otherwise this line crashes.

I endend up building this class and getting rid of every use of `Platform`

```dart
    
class OSTool {
  
    OSTool._();
    
    static const bool isWeb = kIsWeb;

    static final bool isAndroid = !isWeb && Platform.isAndroid;
    static final bool isIOS = !isWeb && Platform.isIOS;
    static final bool isLinux = !isWeb && Platform.isLinux;
    static final bool isWindows = !isWeb && Platform.isWindows;
    static final bool isMacOS = !isWeb && Platform.isMacOS;
    static final bool isFuchsia = !isWeb && Platform.isFuchsia;
}
```

As you can see, a tiny precondition would have solved the issue.

I suggest adding a `!kIsWeb` check into every method of the Platform component. And while your add it you might also want to add `Platform.isWeb` to it as well. As its a const you can let it const there except for the others.

**Comment by stuartmorgan** [comment]
`Platform` is part of `dart:io`, whereas `kIsWeb` is part of Flutter; it's impossible to add `kIsWeb` checks to `Platform`.

Closing as the requested change can't be made.

**Comment by OSonntag** [comment]
I know decoupling both libraries makes a lot of sense but in some cases it leads to unnesseary code lines & implicit developer knowledge. 

It is still possible to check if its a web build even without including the `kIsWeb` variable.

Amazon for example solved it this way:

```dart
/// Whether running on the Web.
///
/// Since JS does not support integers, an int and a double will be identical
/// when representing the same value. However, this will not be true for all
/// other compilation targets.
const bool zIsWeb = identical(0, 0.0);
```

It might not make sense to add `isWeb` to the `Platform` class. but it makes sense to return false in all cases where its a web build and lot let the app crash. Tiny check -> better developer experience.

(But i still think adding .isWeb to it still makes a lot of sense, but maybe thats something to be discussed)
