### ISSUE TITLE
[web] Multi-view Embedding Support

### ISSUE THREAD

**Issue by ditman** [flutter/flutter#118481]
Get the code ready to support the multi-view embedding feature. Some changes:

* Accept a `hostElements` array in the Engine configuration
* Refactor the current View Embedder so it's not a [singleton anymore](https://github.com/flutter/engine/blob/5bae18365a0142eb38b24d2037d3076057844953/lib/web_ui/lib/src/engine/embedder.dart#L361-L383).
  * Each View should know how to embed itself, or have an Embedding Strategy associated with it. See [this doc](https://github.com/flutter/flutter/issues/117098).

There's multiple assumptions made in the current view embedder that only one view is going to exist at a time (like the [`addSceneToSceneHost` method](https://github.com/flutter/engine/blob/5bae18365a0142eb38b24d2037d3076057844953/lib/web_ui/lib/src/engine/embedder.dart#L102-L112), which need to be delegated to each view implementation).

For simplicity, the new design should be something similar to:

* The platform_dispatcher continues being a singleton that coordinates the engine (in the future, this should be an actual object that gets instantiated).
  * The platform_dispatcher [contains a `Map<ViewId, View>`](https://github.com/flutter/engine/blob/5bae18365a0142eb38b24d2037d3076057844953/lib/web_ui/lib/src/engine/platform_dispatcher.dart#L142) where all the views are cached for access later.
  * The platform_dispatcher can initialize new Views depending on their configuration (create the appropriate DOM structure for the view, create the view itself), and cache it in the view cache.
  * The platform_dispatcher should receive a view Id for every view "operation".
    * Operations should fetch a view by its id, and operate on it, rather than delegate it to the view_embedder. Look how the [current implementation of `render`](https://github.com/flutter/engine/blob/5bae18365a0142eb38b24d2037d3076057844953/lib/web_ui/lib/src/engine/platform_dispatcher.dart#L663-L666) ignores the passed-in `view`.

Most of the above should be implementable in the current state of the engine, without having to wait for the full-blown multi-view setup (at least, to make it work in single-view with the refactored multi-view architecture).

**Comment by ditman** [comment]
Related: https://github.com/flutter/flutter/issues/122850

**Comment by yjbanov** [comment]
First milestone could be: we have an engine test that creates two `FlutterView` instances and renders a `Scene` into each. This way we don't have a dependency on the framework's multi-view support while making progress on the web engine side.

**Comment by NashIlli** [comment]
Any updates about this?

**Comment by ditman** [comment]
@NashIlli it's WIP.

**Comment by leoxagy12** [comment]
This would be extremely useful. I was thinking of using flutter for improving pieces of a legacy web app but the limitation of one single embedded component forbids continuing with this idea for the moment. Hope this gets completed soon as it will open many doors for flutter.

**Comment by ditman** [comment]
@leoxagy12 it's WIP, but lots of work to do. Here's an old-ish [demo](https://dit-multiview-tests.web.app).

**Comment by ditman** [comment]
> So we were thinking if a widget alone can be exposed from that flutter module that is already used by the flutter app.

@sjthn No, you won't be able to export a widget from a Flutter Web app.

You'll be able to have a flutter web app running, possibly rendering nothing, that knows how to fill in certain "divs" with whatever widget you want. This is controlled from your Flutter app.

**Comment by p-mazhnik** [comment]
Here are React demos inspired by @ditman's demo if anyone is interested:
https://p-mazhnik.github.io/flutter-embedding/expo-multiview/
https://p-mazhnik.github.io/flutter-embedding/react-multiview/

**Comment by sfshaza2** [comment]
It looks like this might require some new docs on docs.flutter.dev in Q3. Can you confirm?

**Comment by ditman** [comment]
@sfshaza2 yes! I'll write something next week (or the week after) so there's time to review.
