### ISSUE TITLE
Wrong scene composition (Canvaskit) when first embedded view is invisible (e.g. using PointerInterceptor)

### ISSUE THREAD

**Issue by lclaesen** [flutter/flutter#118452]
## Steps to Reproduce

1. Execute `flutter run --web-renderer canvaskit -d chrome` on the code sample 
2. Verify that the actual and expected results (as described below) differ
3. In the sample code: comment out the ìnsertion of the Stack item `const HtmlElementView(viewType: invisibleDivType)` and run the sample app again
4. Verify that the result is as expected.

**Expected results:** The drawer-like overlay (just a Stack item positioned to the left) should display an orange box (an HtmlElement with a simple html div colored orange). 

**Actual results:** The `HtmlElement` is not shown; it is actually hidden / covered by the a canvas element on which most of the
used framework widgets are drawn (i.e. the drawer like container and the app scaffold itself).

Please note that this issue only occurs when using the canvaskit renderer for the web.

## What seems to go wrong

What seems to happen here is that `canvaskit\embedded_views.dart` does something wrong when the first embedded view it encounters is an 'invisible' one (by which I mean: a `HtmlElementView` created by a viewFactory registered with `isVisible: false`). This results in later `HtmlElementView`s that _are_ visible not being correctly layered. As one of the attached screenshots shows, the platform view with the visible html is obfuscated by a canvas that draws what should be underneath it; i.e. the emitted scene structure is:
- flt-scene
  * flt-canvas-container: on which nothing is drawn
  * flt-platform-view-slot: for the invisible `HtmlElementView`
  * flt-platform-view-slot: for the visible `HtmlElementView`
  * flt-canvas-container: on which the scaffold and drawer are drawn

This is not a contrived situation, since `PointerInterceptor` does exactly that: it inserts an invisible `HtmlElementView` in order to ensure widgets remain responsive, even when overlayed over, let's say, an embedded iframe. Because we want drawers, modals, overlay entries, ... to be responsive irrespective of what's underneath them, we wrap them in a `PointerInterceptor`. But because of this issue, `PointerInterceptor` also disallows its child to embed a visible `HtmlElement` itself -- at least when there is no visible HtmlElement below it.

Otherwise put: we expect that our overlay entries can overlay embedded html view (and stay responsive); but we also expect that our overlay entries can embed html. And because of the current issue, we don't seem to be able to have both.  

<details>
<summary>Code sample</summary>

```dart
// ignore_for_file: avoid_web_libraries_in_flutter, undefined_prefixed_name, avoid_dynamic_calls
import 'dart:html' as html;
import 'dart:ui' as ui;
import 'package:flutter/material.dart';

const visibleDivType = 'visibleDiv';
const invisibleDivType = 'invisibleDiv';
const title = 'Flutter issue demo';

void main() {
  ui.platformViewRegistry.registerViewFactory(
      visibleDivType,
      (int viewId) => html.DivElement()
        ..style.border = 'none'
        ..style.height = '100%'
        ..style.width = '100%'
        ..style.backgroundColor = 'orange'
        ..appendText('An embedded div'),
      isVisible: true);
  ui.platformViewRegistry.registerViewFactory(
      invisibleDivType,
      (int viewId) => html.DivElement()
        ..style.height = '100%'
        ..style.width = '100%'
        ..style.backgroundColor = 'green',
      isVisible: false);
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        title: title,
        theme: ThemeData(
          primarySwatch: Colors.blue,
        ),
        home: Scaffold(
          appBar: AppBar(title: const Text(title)),
          body: const Home(),
        ));
  }
}

class Home extends StatelessWidget {
  const Home({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Stack(
      children: [
        const Center(),
        // Please comment out in order to verify that it is this
        // invisible HtmlElementView that causes the wrong layering:
        const HtmlElementView(viewType: invisibleDivType),
        Positioned(
            child: SizedBox(
          width: 400,
          child: Container(
              color: Colors.white,
              child: Column(
                mainAxisSize: MainAxisSize.max,
                children: const [
                  Text(
                      '''A dummy drawer or any other type of overlay. One would expect to see an orange div appear below.'''),
                  SizedBox(
                      width: 100,
                      height: 40,
                      child: HtmlElementView(viewType: 'visibleDiv')),
                ],
              )),
        ))
      ],
    );
  }
}
```

</details>

## Screenshots

The actual result:

![actual result](https://user-images.githubusercontent.com/83348892/212330060-80601b0a-dff2-4f28-981b-e35f45324430.png)

The expected result after commenting out the invisible Html element:

![expected result after leaving out invisible Html element](https://user-images.githubusercontent.com/83348892/212330057-eb13df00-20d6-46ee-9eb4-76d59c345bb3.png)

The flt-scene with top canvas hidden:

![flt-scene with top canvas hidden](https://user-images.githubusercontent.com/83348892/212332975-83ef32bf-559d-46d4-b200-678289ab8255.PNG)

**Comment by darshankawar** [comment]
Thanks for the detailed report. Using code sample provided and running with both renderers, observed that the behavior occurs using canvaskit. With html renderer, it works as expected.

Maybe related / similar to : https://github.com/flutter/flutter/issues/104970

<details>
<summary> stable, master flutter doctor -v </summary>

```
[✓] Flutter (Channel stable, 3.3.10, on macOS 12.2.1 21D62 darwin-x64, locale
    en-GB)
    • Flutter version 3.3.10 on channel stable at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (15 hours ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

[!] Flutter (Channel master, 3.7.0-21.0.pre.42, on macOS 12.2.1 21D62
    darwin-x64, locale en-GB)
    • Flutter version 3.7.0-21.0.pre.42 on channel master at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 1220245b33 (28 hours ago), 2023-01-14 19:53:06 -0500
    • Engine revision f790304409
    • Dart version 3.0.0 (build 3.0.0-122.0.dev)
    • DevTools version 2.20.0
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.



```

</details>

**Comment by lclaesen** [comment]
By now I can provide some extra information, confirming my previous statement, that it is 

> when the first embedded view it [the canvaskit renderer] encounters is an 'invisible' one 

that causes the issue: if one artificially inserts an (otherwise non functional) visible `HtmlElementView` as a first one (in the painting layers order), the layering is again as expected, as an extension of the sample above shows:

```dart
// ignore_for_file: avoid_web_libraries_in_flutter, undefined_prefixed_name, avoid_dynamic_calls
import 'dart:html' as html;
import 'dart:ui' as ui;
import 'package:flutter/material.dart';

const visibleDivType = 'visibleDiv';
const invisibleDivType = 'invisibleDiv';
const visibleRootDiv = 'visibleRootDiv';
const title = 'Flutter issue demo';

void main() {
  ui.platformViewRegistry.registerViewFactory(
      visibleDivType,
      (int viewId) => html.DivElement()
        ..style.border = 'none'
        ..style.height = '100%'
        ..style.width = '100%'
        ..style.backgroundColor = 'orange'
        ..appendText('An embedded div'),
      isVisible: true);
  ui.platformViewRegistry.registerViewFactory(
      invisibleDivType,
      (int viewId) => html.DivElement()
        ..style.height = '100%'
        ..style.width = '100%'
        ..style.backgroundColor = 'green',
      isVisible: false);
  // Again a visible view to be inserted before the first invisible one ...
  ui.platformViewRegistry.registerViewFactory(
      visibleRootDiv,
      (int viewId) => html.DivElement()
        ..style.height = '0px'
        ..style.width = '0px',
      isVisible: true);
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        title: title,
        theme: ThemeData(
          primarySwatch: Colors.blue,
        ),
        home: Scaffold(
          appBar: AppBar(title: const Text(title)),
          body: const Home(),
        ));
  }
}

class Home extends StatelessWidget {
  const Home({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Stack(
      children: [
        // Making sure a visible view comes first fixes the issue
        const Positioned.fill(
            child: HtmlElementView(
          viewType: visibleRootDiv,
        )),
        const Center(),
        const HtmlElementView(viewType: invisibleDivType),
        Positioned(
            child: SizedBox(
          width: 400,
          child: Container(
              color: Colors.white,
              child: Column(
                mainAxisSize: MainAxisSize.max,
                children: const [
                  Text(
                      '''A dummy drawer or any other type of overlay. One would expect to see an orange div appear below.'''),
                  SizedBox(
                      width: 100,
                      height: 40,
                      child: HtmlElementView(viewType: visibleDivType)),
                ],
              )),
        ))
      ],
    );
  }
}
```

Inserting a leading, dummy visible HtmlElement view like this might be considered as a temporary workaround for the issue; but it is only a temporary workaround --  consuming an extra canvas and WEBGL context just to make things work. A proper fix remains to ensure that `canvaskit\embedded_views.dart`  correctly groups embedded views and overlays them with canvases when the bottom embedded view is an invisible one.

**Comment by Juliotati** [comment]
oh Wow, I have the same issue too when i upgrade to Flutter `v3.7.0`
My steps to reproduce are exactly the same as @lclaesen 

# Screen recordings
### Working version `(flutter v3.3.7)`
- Both `iframes`_(stream video and chat)_ are rendered without any issues ✅ 
- Additional `iframes` are rendered without any issues ✅ 

https://user-images.githubusercontent.com/59662912/215334200-dfb20f64-65e2-4841-8570-92ea670093e8.mp4


### Broken version `(flutter v3.7.0)`

https://user-images.githubusercontent.com/59662912/215333996-6d2d2cd7-5e3a-44e6-afb3-90f0438d47f7.mp4

> Observations
- Rendering only one `iframe` seems to work, but the same issue is present when more are rendered
- `iframes` stay in view with transparency after navigation
 
assertion error points [to this link line](https://github.com/flutter/engine/blob/649362168faad2b0be78151f08b7e7dc03a0f7ce/lib/web_ui/lib/src/engine/canvaskit/embedded_views.dart#L689)

At the moment the working version with Flutter `v3.3.7` is available
at [Station web app](https://station.theselfdev.com/)

**Comment by ditman** [comment]
> I'm thinking this might in some way related to https://github.com/flutter/flutter/issues/118481 , is it?

@Juliotati no, multi-view support refers to supporting multiple HTML Element targets (divs) as "windows" of a multi-window app. In this case, I think this is a different bug in the way canvaskit handles embedding HTML elements (within flutter). [HtmlViewEmbedder](https://github.com/flutter/engine/blob/main/lib/web_ui/lib/src/engine/canvaskit/embedded_views.dart).

The confusion is understandable, the names of the classes are extremely similar, but they do very different things :) (sorry!)

**Comment by yjbanov** [comment]
Raised to P2 since it's been reported multiple times, affects simple use-cases, and looks like a recent regression. I'm looking for an owner right now.

**Comment by ditman** [comment]
As @lclaesen noted in the bug report, the "missing" view is actually being rendered into the flt-scene of the app, but it seems that it's landing in the *incorrect* order. It is currently rendered right next to the invisible slot, and before the next canvas-container, but if it were rendered *after* the canvas container, I think we'd get the desired outcome. So:

|Current|Desired|
|---|---|
| scene -> canvas, pv-slot, pv-slot, canvas | scene -> canvas pv-slot, canvas, pv-slot |

<img width="1027" alt="Screenshot 2023-02-07 at 4 19 23 PM" src="https://user-images.githubusercontent.com/1255594/217396795-12221d95-4c8a-47e4-9234-c435fde30908.png">

I'm still trying to wrap my head around the [preroll algo](https://github.com/flutter/engine/blob/main/lib/web_ui/lib/src/engine/canvaskit/embedded_views.dart#L125) to see if we need a special case of "first platform view view is invisible" or the fix belongs somewhere else :)

**Comment by ditman** [comment]
I think I've found a "solution" by splitting off all the invisible views that show up before the first visible one to its own group.

According to its dartdoc, the [`getOverlayGroups` method](https://github.com/flutter/engine/blob/main/lib/web_ui/lib/src/engine/canvaskit/embedded_views.dart#L637-L645) splits the list of platform views by groups that can share the same overlay. Each "group" is _a visible view followed by zero or more invisible views._

The "problem" seems to be that the algo doesn't handle the case where a bunch of invisible views are added *before* the first visible view. So for example (number as view Id, then V or I for Visible/Invisible):

* Happy case: `[0V, 1V, 2I, 3I, 4V, 5V]`, the expected groups are: `[[0V], [1V, 2I, 3I], [4V], [5V]]`.
* Buggy case: `[0I, 1I, 2V, 3I, 4V, 5V]`, which would produce something like... `[[0I, 1I, 2V, 3I], [4V], [5V]]` (which seems to be causing the bug described here). Note how the first group is **not _a visible view followed by zero or more invisible views_**! 
  * Compare to what I think it _should_ do: `[[0I, 1I], [2V, 3I], [4V], [5V]]`. The drawback of this is that it seems to need one extra canvasKitOverlay than the previous version of the algorithm!

<details>
<summary><tt>$ git diff</tt></summary>

```diff
diff --git a/lib/web_ui/lib/src/engine/canvaskit/embedded_views.dart b/lib/web_ui/lib/src/engine/canvaskit/embedded_views.dart
index 27694946d5..d92a179277 100644
--- a/lib/web_ui/lib/src/engine/canvaskit/embedded_views.dart
+++ b/lib/web_ui/lib/src/engine/canvaskit/embedded_views.dart
@@ -136,8 +136,7 @@ class HtmlViewEmbedder {
     // We need an overlay for the first platform view no matter what. The first
     // visible platform view doesn't need to create a new one if we already
     // created one.
-    final bool needNewOverlay = (platformViewManager.isVisible(viewId) &&
-            _context.seenFirstVisibleViewInPreroll) ||
+    final bool needNewOverlay = platformViewManager.isVisible(viewId) ||
         _context.pictureRecordersCreatedDuringPreroll.isEmpty;
     if (platformViewManager.isVisible(viewId)) {
       _context.seenFirstVisibleViewInPreroll = true;
@@ -174,8 +173,7 @@ class HtmlViewEmbedder {
       _context.visibleViewCount++;
     }
     // We need a new overlay if this is a visible view or if we don't have one yet.
-    final bool needNewOverlay = (platformViewManager.isVisible(viewId) &&
-            _context.seenFirstVisibleView) ||
+    final bool needNewOverlay = platformViewManager.isVisible(viewId) ||
         _context.pictureRecorders.isEmpty;
     if (platformViewManager.isVisible(viewId)) {
       _context.seenFirstVisibleView = true;
@@ -669,10 +667,24 @@ class HtmlViewEmbedder {
           } else {
             currentGroup = <int>[view];
           }
-        } else {
-          // We hit this case if this is the first visible view.
+        }
+        if (!foundFirstVisibleView) {
+          // First visible view found...
           foundFirstVisibleView = true;
-          currentGroup.add(view);
+          if (currentGroup.isNotEmpty) {
+            // If we've seen invisible views earlier, split them off...
+            result.add(currentGroup);
+            // If we are out of overlays, then break let the rest of the views be
+            // added to an extra group that will be rendered on top of the scene.
+            if (result.length == maxOverlays) {
+              currentGroup = <int>[];
+              break;
+            } else {
+              currentGroup = <int>[view];
+            }
+          } else {
+            currentGroup.add(view);
+          }
         }
       }
     }
```

</details>

_Disclaimer: Note the double quotes around "problem" and "solution" above. I need to discuss this potential solution with @hterkelsen to see what he thinks of it. This might be breaking other stuff that I may not be taking into account, and the code can be better; or maybe there's a better fix elsewhere so I don't have to touch the algorithm. Stay tuned!

**Comment by ditman** [comment]
After discussing with @hterkelsen, we came up with a simpler solution that handles invisible views better.

The problem with my solution above was that it wasted a canvasKit overlay if there were any invisible views before any visible views by splitting those invisible views as if any of them was visible.

The better approach is able to handle the grouping of views that I was splitting earlier (`I, I, V, I`), and cases where only invisible platform views happen in the page.

In the new implementation, overlays will only be added if there's a visible view in a group, and only visible views trigger new overlays.

<img width="937" alt="Screenshot 2023-02-08 at 7 04 51 PM" src="https://user-images.githubusercontent.com/1255594/217707597-66779ddf-a0da-4b47-8a61-2713d8cfc24c.png">

Here's the PR:

* https://github.com/flutter/engine/pull/39506

**Comment by ditman** [comment]
As of ~2h ago [commit](https://github.com/flutter/flutter/commit/2f9abd20f0b489a425862367ffe27c4833d93c9e), the fix for this is available in the flutter `master` channel.
