### ISSUE TITLE
[web] Pointer Binding Tests fail when DPI > 1 in Chrome >= 108

### ISSUE THREAD

**Issue by ditman** [flutter/flutter#118426]
It seems that a change in behavior in Chrome 108 has started scaling **synthetic** mouse events' offset position by the DPI of the screen. Our engine CI breaks when attempting to update the version of Chrome to anything greater than the current 107 version.

Here's the related Chromium bug:

* https://bugs.chromium.org/p/chromium/issues/detail?id=1407034

Accidentally discovered by @eyebrowsoffire when he ran the tests in a high DPI display in an unrelated change.

**Comment by ditman** [comment]
Some notes:

* This doesn't seem to affect our CI directly, because tests there must be always be running in DPI=1 (and we fake higher DPIs through code, not actual browser configuration)
* It seems that Chrome has always done (or attempted to do) something like this?
  * https://github.com/chromium/chromium/commit/81a26910b2b492523ef8970a135a07459fa53d8b#diff-b5f8f49500a102020d3ab688dd91e6d42d5fc249ba7f80829f8fbd1994e16c62L463-R461

**Comment by yjbanov** [comment]
This was fixed by explicitly specifying the DPR of the screen when launching Chrome in test mode.
