### ISSUE TITLE
PWA Safari restarts on continuous orientation change

### ISSUE THREAD

**Issue by vasilich6107** [flutter/flutter#118462]
## Steps to Reproduce
1. create flutter app with `flutter create`
2. build it with `flutter build web --web-renderer canvaskit`
3. deploy it somewhere(i'm using vercel.app)
4. open app in safari(i have iOs 16.2)
5. add it to home screen
6. open from home screen
7. rotate continuously between portrait and landscape(may require 10 to 20 rotations)
8. see how app restarts(the larger app is the less rotations required)

**Expected results:** 
no app restart

**Actual results:** 
app restarts

**Comment by huycozy** [comment]
Hi @vasilich6107 
Can you elaborate on this step by adding a sample code or providing a visual demo for it?

Also, please provide the output of `flutter doctor -v` as well. Thanks!

**Comment by darshankawar** [comment]
I tried using steps to replicate on iPhone 6s (OS 15.2), but was unable to replicate the reported behavior.


https://user-images.githubusercontent.com/67046386/213629048-7aacc64c-e69c-4fa9-bdc9-0dfe28bb7757.MP4


Based on the report and behavior seen, I am going ahead and keeping this issue open for team's attention.

**Comment by darshankawar** [comment]
Thanks for the update. Since it is fixed on master, I am going ahead and close this, as the fix will most likely be available in next stable version. If you disagree, write in comments and I'll reopen it.
