### ISSUE TITLE
[Impeller Scene] A model file is missing in scene_unittests

### ISSUE THREAD

**Issue by fanchou** [flutter/flutter#118440]
![image](https://user-images.githubusercontent.com/2160502/212276988-ea80784a-b260-4aa6-97fe-2a923ee274cb.png)

In addition, the memory leakage of the Playgrounds is very serious, and the test cases can hardly run.

![image](https://user-images.githubusercontent.com/2160502/212278683-5a92f2cc-8139-47ba-89e4-9c2c640011af.png)

**Comment by chinmaygarde** [comment]
cc @bdero

**Comment by bdero** [comment]
As indicated by the comment in the test, this asset is intentionally missing. The missing asset should not cause this test to fail.

```
    // TODO(bdero): Just skip this playground is the dash asset isn't found. I
    //              haven't checked it in because it's way too big right now,
    //              but this is still useful to keep around for debugging
    //              purposes.
```
