### ISSUE TITLE
add enterFullscreen functionality for video_player_web 

### ISSUE THREAD

**Issue by michalkubizna** [flutter/flutter#118404]
Entering full-screen mode operates differently on the web compared to other platforms because the screen is confined by the browser frame. To enable full-screen mode on the web, expose an 'enter full-screen function so that other packages built on top of video_player can use it and support full-screen on the web.

**Comment by darshankawar** [comment]
@michalkubizna 
There's [similar issue](https://github.com/flutter/flutter/issues/64397) in which you can follow-up for further updates and may share your views / thoughts in it.
Closing this as duplicate. If you disagree, write in comments and I'll reopen it.
