### ISSUE TITLE
[Camera] packages crashes on android 13

### ISSUE THREAD

**Issue by aashutosh-IS** [flutter/flutter#118441]
## Steps to Reproduce

I am using the latest camera: ^0.10.1 package and its crashing on devices having android version 13, it works fine for older devices.

**Expected results:** Be able to run the camera on android 13 devices

**Actual results:** Null pointer exception.

<details>
<summary>
Failed to handle method call
E/MethodChannel#plugins.flutter.io/camera_android( 2496): java.lang.NullPointerException: Attempt to invoke virtual method 'int android.media.EncoderProfiles$VideoProfile.getWidth()' on a null object reference

E/MethodChannel#plugins.flutter.io/camera_android( 2496): 	at io.flutter.plugins.camera.MethodCallHandlerImpl.instantiateCamera(MethodCallHandlerImpl.java:389)
E/MethodChannel#plugins.flutter.io/camera_android( 2496): 	at io.flutter.plugins.camera.MethodCallHandlerImpl.lambda$onMethodCall$0$MethodCallHandlerImpl(MethodCallHandlerImpl.java:82)
E/MethodChannel#plugins.flutter.io/camera_android( 2496): 	at io.flutter.plugins.camera.MethodCallHandlerImpl$$ExternalSyntheticLambda0.onResult(Unknown Source:6)
E/MethodChannel#plugins.flutter.io/camera_android( 2496): 	at io.flutter.plugins.camera.CameraPermissions.requestPermissions(CameraPermissions.java:69)
E/MethodChannel#plugins.flutter.io/camera_android( 2496): 	at io.flutter.plugins.camera.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:75)
E/MethodChannel#plugins.flutter.io/camera_android( 2496): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/MethodChannel#plugins.flutter.io/camera_android( 2496): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/MethodChannel#plugins.flutter.io/camera_android( 2496): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$DartMessenger(DartMessenger.java:319)
E/MethodChannel#plugins.flutter.io/camera_android( 2496): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MethodChannel#plugins.flutter.io/camera_android( 2496): 	at android.os.Handler.handleCallback(Handler.java:942)
E/MethodChannel#plugins.flutter.io/camera_android( 2496): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#plugins.flutter.io/camera_android( 2496): 	at android.os.Looper.loopOnce(Looper.java:226)
E/MethodChannel#plugins.flutter.io/camera_android( 2496): 	at android.os.Looper.loop(Looper.java:313)
E/MethodChannel#plugins.flutter.io/camera_android( 2496): 	at android.app.ActivityThread.main(ActivityThread.java:8741)
E/MethodChannel#plugins.flutter.io/camera_android( 2496): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.flutter.io/camera_android( 2496): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
E/MethodChannel#plugins.flutter.io/camera_android( 2496): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
</summary>

**Comment by danagbemava-nc** [comment]
This is a known issue and it's being tracked in https://github.com/flutter/flutter/issues/109769. 

Kindly follow up in the issue linked above for updates. 

Closing from here as duplicate. 

Thank you
