### ISSUE TITLE
Is this a bug?

### ISSUE THREAD

**Issue by Faamica** [flutter/flutter#118456]
## Steps to Reproduce

1. int pay = 120000;
  num payDivided = pay/10000;
  var discountRate = 20;
print('${(payDivided * ((100 - discountRate) * 0.01))}');

**Expected results:** 
9.6

**Actual results:** 
9.600000000000001

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by stuartmorgan** [comment]
This is not a bug, it is correct to within the precision of a `double`. Per Dart docs:

> Dart doubles are 64-bit floating-point numbers as specified in the IEEE 754 standard.

and this is the standard's behavior.
