### ISSUE TITLE
regression: Correct FrameTimingRecorder's raster start time.

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#118459]
https://github.com/flutter/engine/pull/38674 has caused a 60% regression in `99th_percentile_frame_rasterizer_time_millis`

## skia perf
https://flutter-flutter-perf.skia.org/e/?begin=1673564826&end=1673611108&keys=X946304b17b069f28036dc4ae9157489f&num_commits=50&request_type=1&xbaroffset=32846

## offending pr
https://github.com/flutter/engine/pull/38674

**Comment by luckysmg** [comment]
Emm I think before we record a wrong raster time......We didn't record `auto frame = surface_->AcquireFrame(layer_tree.frame_size());` in our raster time... So developer will see wrong histogram in DevTools and data from `addTimingCallback` is also wrong.....

**Comment by chinmaygarde** [comment]
I think is regression is expected as we weren't calculating to the time take to acquire the frame. This would include the call to acquire the next drawable which would make us wait on the GPU for completion.

**Comment by gaaclarke** [comment]
Does this mean that the benchmark is correct now, but was incorrect previously?  There's no extra work to make this benchmark better?

**Comment by chinmaygarde** [comment]
Right. It was incorrect previously as it didn't account for the entire
frame time.

**Comment by chinmaygarde** [comment]
Closing this as WAI and fixing a previously incorrect reading. cc @iskakaushik who is the current gardener.
