### ISSUE TITLE
iconButtonTheme is missing from stable branch but the docs are pointing that it is available

### ISSUE THREAD

**Issue by amdshrif** [flutter/flutter#118478]
The flutter docs says that iconButtonTheme is available as per ThemeData page here:
https://api.flutter.dev/flutter/material/ThemeData-class.html

and the bar in the bottom of the docs page is pointing to:
Flutter 3.3.10 • 2022-12-21 08:55 • 135454af32 • stable

but looking at the source code of the stable branch, I do not see the missing attribute here:
https://github.com/flutter/flutter/blob/stable/packages/flutter/lib/src/material/theme_data.dart

While I still see the missing iconButtonTheme in master branch but it looks like the docs and stable branches are out of sync.

the flutter version I am using is:
$ git pull         
Already up to date.
$ flutter --version
Flutter 3.3.10 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 135454af32 (4 weeks ago) • 2022-12-15 07:36:55 -0800
Engine • revision 3316dd8728
Tools • Dart 2.18.6 • DevTools 2.15.0

**Comment by danagbemava-nc** [comment]
Hi @amdshrif, this issue is known and is being tracked in https://github.com/flutter/flutter/issues/118161. 

Kindly follow up in the issue linked above for updates. 

Closing from here as duplicate. 

Thank you
