### ISSUE TITLE
remove line or shadow above tabbar

### ISSUE THREAD

**Issue by CrazyBunnyz** [flutter/flutter#118548]
im working on a UI app. manage to implement tabbar but got quite confused about a thin line above the tabbar. it's either a line or shadow, not sure. already run several code but doesn't manage to remove the line. the weird thing is, It seems to work the way i wanted on mobile ( chrome - mobile version / tablet ) but the line pop when opened in web version.

here is the problem ( that single line above the blue tabbar )
![image](https://user-images.githubusercontent.com/52201618/212614253-f3e03d4a-02a9-496b-aedb-b34e042e5161.png)
here is it, the same code when opened in mobile mode.
![image](https://user-images.githubusercontent.com/52201618/212614277-ca994ad3-6f45-42ff-9d33-000a6506a9ad.png)
perfect clear without the line.

i try 2 version of code

DefaultTabController(
      length: 2,
      child: new Scaffold(
        appBar: new PreferredSize(
          preferredSize: Size.fromHeight(kToolbarHeight),
          
          child: new Container(
            color: Theme.of(context).primaryColor,
            child: new SafeArea(
              child: Column(
                children: <Widget>[
                  new Expanded(child: new Container()),
                  new TabBar(
                    labelColor: Colors.white,
                    unselectedLabelColor: Colors.grey[700],
                    indicatorColor: Colors.white,
                    tabs: [
                      Tab(icon: Icon(Icons.chat)),
                      Tab(icon: Icon(Icons.filter_alt_outlined)),
                    ],
                  ),
                ],
              ),
            ),
          ),
        ),
        body: TabBarView(

and the second one

DefaultTabController(
      length: 2,
      child: Scaffold(
        appBar: AppBar(
          flexibleSpace: SafeArea(
            child: _tabBar,
          ),
          backgroundColor: Theme.of(context).primaryColor,
          elevation: 0,
        ),
        body: TabBarView(

both of them works, but results are the same. that thin line above the tab bar persist. i just want to remove it. can anyone help ?

**Comment by exaby73** [comment]
Hello @CrazyBunnyz. Thank you for filing this issue. Can you please provide the following information?

- A [complete and minimal, reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example). Ideally, a single `main.dart` file that can be run directly.
- The output of `flutter doctor -v`

Please provide the information in the form of text. See how to make collapsible sections with Markdown [here](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-collapsed-sections).

**Comment by CrazyBunnyz** [comment]
I solved my own question. lol. the problem lies in the header. instead of using container as the header, I just need to put the header ( container ) inside appbar first. i find it quite weird cause I don't put any decoration or style in the header. it has been solved anyway so no complain. thank you for everyone who takes their time to help me solve my problem
