### ISSUE TITLE
Force browsers to clear cache based on pubspec.yaml version in [Flutter web]

### ISSUE THREAD

**Issue by iliyami** [flutter/flutter#118583]
Hi,
Whenever we release an update and deploy it on the server, we should tell our clients to clear cache their browsers to receive the new update.
I've found a workaround solution by adding a random (or maybe a version) number to main.dart.js script tag and changing it each time we have a new release before the `flutter build web` command to force users' browser invalidates the previous version caching... 

Isn't there a similar solution to automate this process using the pubspec.yaml version?

**Comment by danagbemava-nc** [comment]
Hi @iliyami, this issue is known and is being tracked in https://github.com/flutter/flutter/issues/63500.

Kindly follow up in the issue linked above for updates. 

Closing from here as duplicate. 

Thank you
