### ISSUE TITLE
Crash on iOS 14.X simulator when using [catcher] and [in_app_purchase] together.

### ISSUE THREAD

**Issue by sneglia9191** [flutter/flutter#118500]
Via issue https://github.com/flutter/flutter/issues/117842, I have been working with the `in_app_purchase` team as it appear there is a conflict between `in_app_purchase` and the `catcher` packages.   What happens is I am getting a hard crash when purchasing a non-consumable on IOS simulators with 14.X. It does not crash on a simulator with 16.2. It also works in the sandbox environment on a physical device running 14.8.1.    Working with the `in_app_purchase` team, there is a conflict with the `catcher` plug-in.

All details and information are in issue https://github.com/flutter/flutter/issues/117842.  The `in_app_purchase` team has asked that I contact you as they can not step deeper into your code to debug.

**Comment by danagbemava-nc** [comment]
Hi @sneglia9191, did you mean to file this issue on the `catcher` repo?

**Comment by sneglia9191** [comment]
Yes, my apologies.  I just posted in the `catcher` repo.   I will close this one.
