### ISSUE TITLE
PageStorage usage

### ISSUE THREAD

**Issue by cohortor** [flutter/flutter#11851]
**Problem:** nesting 2 or more widgets in the hierarchy that both use `PageStorage` without identifiers -- e.g. an `ExpansionTile`, and a `Scrollable` -- results in widgets reading/writing into/from the same location; this in turn results in an exception, since the value types used by these widgets are different: the `ExpansionTile` reads/writes a `boolean` (isExpanded), the `ScrollController` a `double` (scrollPosition). If the types were the same, the problem would be even worse, since the code would run with unexpected behavior.

**Cause:** `PageStorage.{read,write}State()` has an optional parameter -- the "identifier" -- under which state info that needs to outlive a widget can be stored. If state is written/read without specifying an identifier, the `PageStorage` uses the `PageStorageKey` to compute an identifier as a fallback. This results in the same identifier being computed for widgets with a common `PageStorageKey` ancestor.

**Workaround (or intended use?!):** a separate `PageStorageKey` for each of these widgets.

**Suggested fix:** start using the identifier in `PageStorage.{read,write}State()`?
Also, in the current implementation, for the state to be properly restored, we are forced to specify a `PageStorageKey` for these widgets. Shouldn't all this stashing of state be handled transparently inside the widgets (without the need to explicitly give them `PageStorageKeys`), so that we are free to specify our own keys (e.g. a `GlobalKey`) when needed?

**Comment by Hixie** [comment]
Using the identifier wouldn't be enough (e.g. two ExpansionTiles would still end up colliding).

**Comment by cohortor** [comment]
It could be enough, if that identifier was a constructor argument? As it is now, this already seems to be the case (being forced to supply a unique `PageStorageKey` in the constructor), only implicitly, in a very obscure way?

If not, how about easing at least the requirement for the key type (from `PageStorageKey` to any `Key` descendant), and using that as the identifier?

I probably don't know enough flutter to suggest the best solution.

**Comment by Hixie** [comment]
cc @HansMuller

**Comment by cdharris** [comment]
I ran into this same issue with exactly the setup described, a `ExpansionTile` inside a `ListView`. I managed to work around it thanks to cohortor's help, I've made my own `ExpansionTile` and used the `identifier:` argument of `writeState` and `readState`

**Comment by Hixie** [comment]
cc @goderbauer

**Comment by pedromassangocode** [comment]
Hi @cohortor 
I see there's an open issue addressing the case you described at https://github.com/flutter/flutter/issues/10868
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.

Thank you
