### ISSUE TITLE
DraggableScrollableSheet animation stops when keyboard opens (MediaQuery updates)

### ISSUE THREAD

**Issue by altynbek132** [flutter/flutter#118582]
https://user-images.githubusercontent.com/48729942/212767580-23890209-af71-4c03-a2fd-2a6fe730c422.mp4

https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/scrollable.dart#L479
https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/draggable_scrollable_sheet.dart#L188

**Comment by danagbemava-nc** [comment]
Hi @altynbek132,

Can you please provide your `flutter doctor -v` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?

Thank you
