### ISSUE TITLE
Debugging flutter web on the Safari

### ISSUE THREAD

**Issue by iliyami** [flutter/flutter#118549]
As I have searched so far, we can not develop Flutter web or PWA on the Safari with inspectors. As this is very crucial for debugging IOS PWAs performance and related issues, I'm requesting to develop and enable this feature for us.

**Comment by darshankawar** [comment]
@iliyami 
There's similar issue open describing your case, https://github.com/flutter/flutter/issues/55323, so please follow-up in it for further updates. Also, you can take a look at [this](https://stackoverflow.com/questions/64351893/how-can-i-debug-a-flutter-web-app-on-safari-using-the-inspector) SO link for your reference.

Closing this as a duplicate.
