### ISSUE TITLE
[webview_flutter] String.prototype.replaceAll() not supported

### ISSUE THREAD

**Issue by diegosa891** [flutter/flutter#118561]
[webview_flutter] String.prototype.replaceAll() not supported

I/chromium(17269): [INFO:CONSOLE(344)] "Uncaught TypeError: pageName.replaceAll is not a function", source: http://10.10.10.80/perfanyw/js/SettingsManager.js (344)

**Comment by exaby73** [comment]
Hello @diegosa891. Thank you for filing this issue. Can you please provide the following information?

- A [complete and minimal, reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example). Ideally, a single `main.dart` file that can be run directly.
- The output of `flutter doctor -v`
- The output of `flutter run -v`

Please provide the information in the form of text. See how to make collapsible sections with Markdown [here](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-collapsed-sections).
