### ISSUE TITLE
Crash on debug build when using Vector.normalize for beta Flutter branch

### ISSUE THREAD

**Issue by HayesGordon** [flutter/flutter#118559]
Hi! As the title says: observing a crash in a debug Flutter build under certain conditions when calling `normalise` on a vector, from the `vector_math` [package](https://pub.dev/packages/vector_math).

This was initially reported for the Flutter Confetti package [here](https://github.com/funwithflutter/flutter_confetti/issues/70), for the master Flutter branch, and now for the beta branch as well. It is working in stable, and has been for the past few years.

I initially assumed it was an impeller issue, but now I'm thinking it's a compilation/debugger issue as it only happens on a debug build. Also, adding an extra print function to the `normalize` method does not result in the crash.

## Steps to Reproduce
1. Run the example from the [confetti package](https://github.com/funwithflutter/flutter_confetti) (crash confirmed on Android, iOS, macOS).
2. Play any animation, observe crash 🤕

Crash is happening here: https://github.com/funwithflutter/flutter_confetti/blob/63009ac07b51fe8376ac9011123dafb696947188/lib/src/particle.dart#L268

To resolve the crash either remove the call to `normalize()` in the **confetti** package, or locally modify the function in the **vector_math** package:
```dart
 /// Normalize this.
  double normalize() {
    final l = length;
    if (l == 0.0) {
      print('what is going on'); // added this print
      return 0.0;
    }
    final d = 1.0 / l;
    _v2storage[0] *= d;
    _v2storage[1] *= d;
    return l;
  }
```
In the above I added the print (which never gets called), and this resolves the crash 🤯

## Additional Info
This has been observed on multiple Flutter versions, environments, emulators, etc.

**Comment by exaby73** [comment]
Hello @HayesGordon. Thanks for raising this issue. Could you provide an isolated code sample for this that doesn't depend on any 3rd party library? The code should be minimal and complete. Basically, I need a [complete and minimal, reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example). Thank you

**Comment by mraleph** [comment]
I think the provided reproduction is good enough. 

@aam could you take a look at this, Alex? Seems like a compiler issue.

**Comment by jason-simmons** [comment]
This was fixed by https://dart.googlesource.com/sdk/+/ff2d661d5ba07766fc27196e98df6c6ae80444b9

**Comment by pooblej** [comment]
Issue still remains where I needed to add a print statement to stop it crashing
I have created this pull request from my branch - https://github.com/google/vector_math.dart/pull/278

pls allow this workaround or place a fix... thanks

**Comment by exaby73** [comment]
@pooblej Which version of Flutter have you tried on? The fix, I think, should be on the master channel

**Comment by pooblej** [comment]
The latest 
<img width="934" alt="Screenshot 2023-01-26 at 09 42 10" src="https://user-images.githubusercontent.com/20245750/214804493-d4b2fcdd-8b93-4948-aa81-8628671866c4.png">

**Comment by exaby73** [comment]
Please try the master channel. It may not have landed in the stable channel yet

**Comment by mraleph** [comment]
I think we should request a CP into stable for this fix given that it affects vector_math. /cc @aam

**Comment by HayesGordon** [comment]
What's the status on the CP, many users are now impacted with the release of 3.7.0: https://github.com/funwithflutter/flutter_confetti/issues/78

**Comment by exaby73** [comment]
I am not sure if a CP has been made yet. If not, maybe you could request it using the template. See https://github.com/flutter/flutter/wiki/Flutter-Cherrypick-Process#requesting-a-cherry-pick

**Comment by mraleph** [comment]
@exaby73 it has to be requested on Dart, rather than Flutter. It's a slightly [different procedure](https://github.com/dart-lang/sdk/wiki/Cherry-picks-to-a-release-channel). Let's wait for the @aam as the author of the original fix to request it.
