### ISSUE TITLE
`flutter run` hangs on "Resolving dependencies..."

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter#11856]
_From @martinkbrown on August 30, 2017 20:59_

## Steps to Reproduce

Run `flutter run`. 

## Version info from Flutter Doctor

```
PS C:\Users\nz962\git\flutter-hello-world\myapp> flutter doctor
[√] Flutter (on Microsoft Windows [Version 6.3.9600], locale en-US, channel alpha)
    • Flutter at C:\Users\nz962\git\flutter
    • Framework revision b156a0f054 (3 weeks ago), 2017-08-11 22:01:40 -0700
    • Engine revision fef7d827d6
    • Tools Dart version 1.25.0-dev.9.0

[√] Android toolchain - develop for Android devices (Android SDK 26.0.0)
    • Android SDK at C:\Users\nz962\AppData\Local\Android\sdk
    • Platform android-26, build-tools 26.0.0
    • ANDROID_HOME = C:\Users\nz962\AppData\Local\Android\sdk
    • Java binary at: C:\Users\nz962\Downloads\Software\Android3.0\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-884-b01)

[√] Android Studio (version 2.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[√] Android Studio (version 3.0)
    • Android Studio at C:\Users\nz962\Downloads\Software\Android3.0\android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-884-b01)

[√] Connected devices
    • Nexus 6P • 8XV7N16516000352 • android-arm • Android 6.0.1 (API 23)
```

## Logs
After running `flutter run -v`, I get this:

```
PS C:\Users\nz962\git\flutter-hello-world\myapp> flutter run -v
[  +23 ms] [C:\Users\nz962\git\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[ +118 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/alpha
[   +2 ms] [C:\Users\nz962\git\flutter\] git ls-remote --get-url origin
[  +70 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[   +2 ms] [C:\Users\nz962\git\flutter\] git log -n 1 --pretty=format:%H
[  +66 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] b156a0f0549a3ad3e1134638f26f472427c379be
[   +2 ms] [C:\Users\nz962\git\flutter\] git log -n 1 --pretty=format:%ar
[  +70 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[        ] 3 weeks ago
[ +603 ms] Listing devices using C:\Users\nz962\AppData\Local\Android\sdk\platform-tools\adb
[        ] C:\Users\nz962\AppData\Local\Android\sdk\platform-tools\adb devices -l
[  +43 ms] Exit code 0 from: C:\Users\nz962\AppData\Local\Android\sdk\platform-tools\adb devices -l
[        ] List of devices attached
           8XV7N16516000352       device product:angler model:Nexus_6P device:angler
[  +22 ms] C:\Users\nz962\AppData\Local\Android\sdk\platform-tools\adb -s 8XV7N16516000352 shell getprop
[ +142 ms] ro.hardware = angler
[        ] ro.build.characteristics = nosdcard
[ +626 ms] Launching lib/main.dart on Nexus 6P in debug mode...
[   +6 ms] Initializing gradle...
[        ] Using gradle from C:\Users\nz962\git\flutter-hello-world\myapp\android\gradlew.bat.
[ +258 ms] C:\Users\nz962\git\flutter-hello-world\myapp\android\gradlew.bat -v
[ +732 ms]
           ------------------------------------------------------------
           Gradle 3.3
           ------------------------------------------------------------

           Build time:   2017-01-03 15:31:04 UTC
           Revision:     075893a3d0798c0c1f322899b41ceca82e4e134b

           Groovy:       2.4.7
           Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
           JVM:          1.8.0_152-release (JetBrains s.r.o 25.152-b01)
           OS:           Windows 8.1 6.3 amd64


           Picked up _JAVA_OPTIONS: -Djava.net.preferIPv4Stack=true
[   +2 ms] Resolving dependencies...
[   +2 ms] [android\] C:\Users\nz962\git\flutter-hello-world\myapp\android\gradlew.bat app:properties
```

_Copied from original issue: flutter/flutter-intellij#1311_

**Comment by devoncarew** [comment]
Thanks for the detailed info! It looks like flutter run is hung up on the gradle build step. I don't know enough about what can commonly go wrong here. I'll cc people who know a bit more (and bump this issue over to the main flutter repo).

**Comment by martinkbrown** [comment]
The issue is with my network at work. I tried it while connected to an external network and it was successful! 

I can usually get around the proxies at work, but even Chrome has been having some trouble with DNS lookups lately, giving DNS lookup errors and certificate errors. But I thought that since `flutter doctor` worked, that the issue was not with my network, but I was wrong.

Solution: Use a different network.

**Comment by sjustesen** [comment]
I encounted above-mentioned behaviour while running a project. I was able to fix it by disabling antivirus for a while (Avast Antivirus on Windows 10 version 1709 build 16299.2)

**Comment by Trenrod** [comment]
Same issue with F-Secure on  Windows 10 Enterprise, Version10.0.15063 Build 15063.

**Comment by Cyan101** [comment]
same issue but not running any antivirus so not sure

**Comment by MalwareNinja** [comment]
i am running the same cammand on Linux ,still receiving the problem .. i am sure its not a networking or Antivirus problem .

**Comment by jakobr-google** [comment]
@Cyan101 @MalwareNinja do you get the exact same behavior - as in, `flutter run -v` seems to hang just after printing out the line about running `gradlew app:properties`, or does it hang on another line?

**Comment by Nykollas** [comment]
This worked for me:

    ./flutter_project_name/android/gradlew

    After successful build.
    Try run the project again.

**Comment by rajatthepagal** [comment]
@Nykollas  hey i wanted to know what this command does. It appears it's updating my grade that is present in the machine already from the previous android installation. Is this what it does ?? Also will report back with results if this work 👍

**Comment by rajatthepagal** [comment]
@Nykollas  Thanks man it worked just wanted to know what exactly it did. ??

**Comment by Nykollas** [comment]
This install dependencies related with the gradle build system.

**Comment by DanTup** [comment]
I just had this on Windows... I ran the `gradlew` file maually as suggested above and saw:

```
PS M:\Coding\Applications\Dart-Code\test\test_projects\flutter_hello_world> .\android\gradlew
Starting a Gradle Daemon, 2 incompatible Daemons could not be reused, use --status for details
```

And after that it was fine.

**Comment by tangdi** [comment]
Same problem when running on Mac. Running .\android\gradlew didn't solve the issue.

**Comment by mravn-google** [comment]
Sometimes it helps to delete the `android/.gradle` folder and retry.

**Comment by zdRan** [comment]
@Nykollas Thanks man it worked

**Comment by MishraUdit** [comment]
As mentioned by @Nykollas, I used the command `gradlew` under the folder structure, during the command run it downloaded various zip files and extracted it. I traced out errors each time and again ran the `gradlew` command until it prompted `Build Successful`. It may require to use the command several times to finally remove the issue by solving them manually or with the help of search.
Thank you...

**Comment by KNehe** [comment]
Is it a must for android studio to run for long the first time i run hello world,because i used gradlew command and after successful build i tried to run but still takes ages

**Comment by djfm** [comment]
On my machine it doesn't exactly hang, just takes about 3 hours... glad we have hot reload, just avoid cold start ;) Turning network off makes it start reasonably fast.

**Comment by gliheng** [comment]
I had it twice, and I ran `gradlew --debug` manually. It also stuck on resolving dependencies.
If you are in China, the reason  maybe that flutter proxy setting does not work for gradle.
You have to set it in `gradle.properties`.
I finally solved it by with this line 
`org.gradle.jvmargs=-DsocksProxyHost=127.0.0.1 -DsocksProxyPort=6444`

**Comment by melsheikh92** [comment]
It fixed with me by changing the SDK location in local.properties file.

**Comment by sanket143** [comment]
Same problem...
stuck at
```
[        ] executing: [/home/sanket143/Desktop/Verts/Android/hello/android/] /home/sanket143/Desktop/Verts/Android/hello/android/gradlew app:properties
```
flutter doctor is fine.
```
$ ./android/gradlew 
$ # BUILD SUCCESSFUL
$ # didn't worked, same problem
```
Does this requires Internet ?

**Comment by XFeiF** [comment]
Same issue with MacOS(10.14.1).   
Inspired by @gliheng , since I use shadowsocks, so I add this line to change the gradle proxy:  
```
org.gradle.jvmargs=-DhttpProxyHost=127.0.0.1 -DhttpProxyPort=1080
```
Hope it helps!

**Comment by Kakashi74** [comment]
> It fixed with me by changing the SDK location in local.properties file.

" Flutter Initializing gradle and Resolving dependencies takes a very long time " it's run bur very slowly it take at least an hour to run the App , i try to change the sdk location but no thing changed

**Comment by CN-fox** [comment]
MacOS(10.14.1) 
delete `.gradle` under home dir
`rm -rf ~/.gradle`
then 
`./flutter_project_name/android/gradlew`

**Comment by yaolynzc** [comment]
> MacOS(10.14.1)
> delete `.gradle` under home dir
> `rm -rf ~/.gradle`
> then
> `./flutter_project_name/android/gradlew`

thanks! it's worked for me.

**Comment by EbiEbiEvidence** [comment]
for me, the below works

1. `rm -rf ~/.gradle`
2. `cd flutter_your_project/android` <- go `android` directory
3. `./gradlew`
4. `./gradlew app:properties`

**Comment by Mritunjay10** [comment]
executing ./gradelw fixed the issue in linux

**Comment by KadekNusa** [comment]
> 
> 
> This worked for me:
> 
> ```
> ./flutter_project_name/android/gradlew
> 
> After successful build.
> Try run the project again.
> ```

This work for me, thanks!

**Comment by AngeloAvv** [comment]
Has someone solved this issue? In my gitlab CI/CD it gets stuck on 
`executing: [/builds/flutter/[project_name]/android/] /builds/flutter/[project_name]/android/gradlew app:properties`

And this is a very strange behavior since it's occurring with this project only, with other projects it's working flawlessly straight.

I've tried setting up a worker timeout of 3 hours but seems not to be sufficient, it gets stuck and the build fails. Tried also changing the gradlew script and the gradle wrapper version downgrading it from 5.22 to 4.10 without any result.

Any suggestions would be appreciated, thank you!

**Comment by mritunjay10** [comment]
@AngeloAvv make sure your `android/gradlew` is executable

**Comment by nelsonlobo99** [comment]
I had the same issue lately,  I got it fixed it by setting my JAVA_HOME environment variable in /etc/environment to /usr/lib/jvm/java-12-openjdk

**Comment by maheshtheknight** [comment]
> for me, the below works (macOS 10.14)
> 
> 1. `rm -rf ~/.gradle`
> 2. `cd flutter_your_project/android` <- go `android` directory
> 3. add `org.gradle.jvmargs=-DhttpProxyHost=127.0.0.1 -DhttpProxyPort=1080` on `./gradle.properties`
> 4. `./gradlew`
> 5. `./gradlew app:properties`
> 6. `cd ../`
> 7. `flutter run`

4 & 5 works for me. It was upgraded gradle version to 5.6.2, then fixed that resolving dependencies issue.

**Comment by andreadelfante** [comment]
I had this issue too with version 1.9.8.hotfix.4. A reasonable workaround could be to switch back to 1.7.8.hotfix.4.

**Comment by Mustafa-A-Muhammad** [comment]
i just deleted the .gradle in android directory and then everything went fine

**Comment by essaberYahya** [comment]
1- Set the connection to internet off
2- run flutter un (THIS  MAY TAKE 13 sec)
3- you will see error about resource because it's need internet
4- set internet on
5- run flutter run

this should be work , good lucky

**Comment by iapicca** [comment]
Hi @devoncarew is this issue still meant to be open?

**Comment by devoncarew** [comment]
This is likely obsolete now.

**Comment by jfresh194** [comment]
this work for me
run this in your project file
`brew install gradle`

**Comment by ezamagni** [comment]
I'm also having this issue in bitrise CI.
`brew install gradle` didn't work for me.

**Comment by ezamagni** [comment]
I solved with the suggested answer at https://stackoverflow.com/a/45782695/2164891
Apparently gradle can get stuck if you didn't approve all the android licenses required by the SDK.
Everything worked fine after executing the following command:
`yes | sdkmanager --licenses`

**Comment by w3cmark** [comment]
如果你试了以上的方法都没有解决，而你又刚好在中国国内的网络环境，建议你试下下面的方法，它对我有效果：

修改 `./flutter_project_name/android/build.gradle`里的`repositories`（有两处），使用国内代理。

```
repositories {
    // google()
    // jcenter()
    maven { url 'https://maven.aliyun.com/repository/google' }
    maven { url 'https://maven.aliyun.com/repository/jcenter' }
    maven { url 'http://maven.aliyun.com/nexus/content/groups/public' }
}
```
