### ISSUE TITLE
Building a game with Flutter and Flame text mistake

### ISSUE THREAD

**Issue by korgmp3** [flutter/flutter#118528]
on the page https://codelabs.developers.google.com/codelabs/flutter-flame-game#9
is written that class GameOverOverlay is situated in lib/game/widgets.dart
but it is situated in lib/game/widgets/game_over_overlay.dart

**Comment by danagbemava-nc** [comment]
![Screenshot 2023-01-16 at 07 49 23](https://user-images.githubusercontent.com/88313112/212624786-3dec37b9-0a11-48db-b661-274fb2d565c0.png)

/cc @domesticmouse

**Comment by khanhnwin** [comment]
Thank you for catching this! @domesticmouse this has also been updated, can you please regenerate the codelab whenever you have a chance? Thank you!

**Comment by domesticmouse** [comment]
@khanhnwin Please LGTM cl/505538902 =)

**Comment by khanhnwin** [comment]
Done! Should be rolled out now. Thanks folks :)
