### ISSUE TITLE
IconButtonTheme not defined

### ISSUE THREAD

**Issue by Shalom-Nankam** [flutter/flutter#118581]
so in trying to set my app theme properties, the iconButtonTheme property is not defined. It's in the documentation but not implementation. 
I use the latest stable version and material3
<img width="560" alt="Screenshot 2023-01-16 at 20 55 42" src="https://user-images.githubusercontent.com/105394231/212756999-ce0b4e57-31bd-4d7f-8ad7-f3a32f7d79fc.png">

<img width="917" alt="Screenshot 2023-01-16 at 20 56 54" src="https://user-images.githubusercontent.com/105394231/212757022-8fa279e5-fa0b-4b45-8fae-66ce6a601ebc.png">

**Comment by danagbemava-nc** [comment]
Hi @Shalom-Nankam, `iconButtonTheme` is not yet available on the stable channel. The issue with the documentation is being tracked in https://github.com/flutter/flutter/issues/118161. 

Kindly follow up there for updates. 

Closing from here as duplicate. 

Thank you
