### ISSUE TITLE
Wrong file reference in Flutter Flame Game Codelab's step 5

### ISSUE THREAD

**Issue by 3vmartinet** [flutter/flutter#118503]
1. Open https://codelabs.developers.google.com/codelabs/flutter-flame-game#4
2. Look up first occurrence of "lib/game/doodle_dash.dart" (ctrl+f / cmd+f)
3. The code snippet below the "lib/game/doodle_dash.dart" header refers to the "object_manager.dart" file, and not "doodle_dash.dart" as the header sugggests.

**Comment by danagbemava-nc** [comment]
Closing this is favor of https://github.com/flutter/flutter/issues/118497.
