### ISSUE TITLE
Large APK if minSdkVersion is 23

### ISSUE THREAD

**Issue by adil192** [flutter/flutter#118516]
##### Please tell us exactly how to reproduce the problem you are running into, and how you measured the performance.

1. Create the example app.
    ```bash
    flutter create --platforms=android android_23_test
    cd android_23_test
    ```

2. Set `minSdkVersion` to 22. The resulting APK will be 16.9 MB.
    ```bash
    nano android/app/build.gradle  # set minSdkVersion to 18 or 20 or 22 (or default)
    flutter build apk  # 16.9 MB
    ```

3. Set `minSdkVersion` to 23. The resulting APK will be 36.6 MB.
    ```bash
    nano android/app/build.gradle  # set minSdkVersion to 23 or 24 (probably anything > 22)
    flutter build apk  # 36.6 MB
    ```

**Target Platform:** Android
**Target OS version/browser:** minSdkVersion 23 (Android 6)
**Devices:** N/a

## Related issue
The APK file size of Saber (FOSS version) jumped from 30.5 MB to 65.6 MB and I narrowed it down to the `minSdkVersion` which changed from 18 to 23.
https://github.com/adil192/saber/issues/234

## Logs

<details>
<summary>flutter analyze</summary>

```
Analyzing android_23_test...                                            
No issues found! (ran in 2.4s)
```
</details>

<details>
<summary>flutter doctor -v (master)</summary>

This happened with Flutter stable 3.3.10 but I switched to master for this:

```
[✓] Flutter (Channel master, 3.7.0-21.0.pre.42, on Pop!_OS 22.04 LTS 6.0.12-76060006-generic, locale en_GB.UTF-8)
    • Flutter version 3.7.0-21.0.pre.42 on channel master at /home/adil/Documents/Sources/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 1220245b33 (3 hours ago), 2023-01-14 19:53:06 -0500
    • Engine revision f790304409
    • Dart version 3.0.0 (build 3.0.0-122.0.dev)
    • DevTools version 2.20.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /home/adil/Android/Sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.17+8-post-Ubuntu-1ubuntu222.04)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 14.0.0-1ubuntu1
    • cmake version 3.22.1
    • ninja version 1.10.1
    • pkg-config version 0.29.2

[!] Android Studio (version 2022.1)
    • Android Studio at /home/adil/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-1/221.6008.13.2211.9301383
    • Flutter plugin version 71.1.4
    • Dart plugin version 221.6008.17
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] IntelliJ IDEA Ultimate Edition (version 2022.2)
    • IntelliJ at /home/adil/.local/share/JetBrains/Toolbox/apps/IDEA-U/ch-0/222.4345.14
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.74.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.56.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Pop!_OS 22.04 LTS 6.0.12-76060006-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 108.0.5359.124

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

</details>

**Comment by exaby73** [comment]
## Triage report

I can reproduce this issue. Here's what I found:

- `minSdkVersion 22`, APK size for the default counter app is ~16MB
- `minSdkVersion 23` to `minSdkVersion 27`, APK size for the default counter app is ~36MB, a 2X increase for the same app.
- `minSdkVersion 28` to `minSdkVersion 33`, APK size for the default counter app is ~37MB

Each build, I ran `flutter clean` before running `flutter build apk`.

#### Steps to reproduce

- Create a new Flutter app with `flutter create issue_ 118516`
- Edit the `android/app/build.gradle`, changing the `minSdkVersion` to the above mentioned values
- Flutter prints the APK size once the build finishes, which corresponds to the actual size on disk I can confirm. Observe this value across builds with different `minSdkVersion` values.

**Comment by jason-simmons** [comment]
With `minSdkVersion >= 23` the Android tools will not compress the native code library files within the APK.  This applies to the Flutter engine libraries and the compiled Dart code libraries for each target platform.

See https://developer.android.com/reference/tools/gradle-api/7.1/com/android/build/api/dsl/JniLibsPackagingOptions#uselegacypackaging

**Comment by gintominto5329** [comment]
Thanks,

What could we do now. to get to previous apk size, or does it, not apply to appbundle, the new format

**Comment by GaryQian** [comment]
cc @GaryQian @reidbaker 

According to https://developer.android.com/guide/topics/manifest/application-element, under `android:extractNativeLibs`, it recommends adding the uselegacypackaging property in your app's `android/app/build.gradle` to override the default behavior. We will continue to default to android's default behavior here. Android has chosen to opt for faster load times and larger download size. If you disagree with that tradeoff, we recommend changing it in your build.gradle.
