### ISSUE TITLE
Update LICENSE for sky_engine

### ISSUE THREAD

**Issue by lubovtorina** [flutter/flutter#118672]
Hi! Since there's no option to create an issue in [engine](https://github.com/flutter/engine) directory I decided to put my question here:
It's about [sky_engine package LICENSE](https://github.com/flutter/engine/blob/main/sky/packages/sky_engine/LICENSE). As you can see there's no License file in the directiry.
Could you please put the relevant file (License file for sky_engine only) [here](https://github.com/flutter/engine/blob/main/sky/packages/sky_engine/LICENSE)?
Or can you advise where it would be more correct to ask my question?

**Comment by stuartmorgan** [comment]
> It's about [sky_engine package LICENSE](https://github.com/flutter/engine/blob/main/sky/packages/sky_engine/LICENSE). As you can see there's no License file in the directiry.

There is; it's the file you've linked to. If you are trying to view it in GitHub's web viewer you need to click "view raw"; as it says on the page:

> (Sorry about that, but we can’t show files that are this big right now.)

**Comment by stuartmorgan** [comment]
> but it contains lots of licenses, which were used for developing sky_engine, I suppose. Howewer there should be only one license for sky_engine under which it can be distributed.

I'm not sure why you believe that the licenses of the software included in a package and the license under which that package can be distributed are different things; I would suggest consulting with a lawyer about your specific needs.

**Comment by lubovtorina** [comment]
Different license types have different terms for distributing. Could you tell me what terms should we use or where can we find this information? Your file contains appache and bsd3-clause and bsd2-clause and maybe others (it's too big to read it all).

Also there is a problem on github with detecting your license (please, read "Detecting your license" chapter) 
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository

**Comment by stuartmorgan** [comment]
> Could you tell me what terms should we use or where can we find this information?

The LICENSE file is where you can find that information, as it contains all of the licenses of the software making up the Flutter engine.

> Also there is a problem on github with detecting your license (please, read "Detecting your license" chapter)
> https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository

That page specifically says that they don't handle files containing multiple licenses, and the authoritative license file for the Flutter engine cannot be anything other than a file containing multiple licenses. If you want them to change that policy, you would need to file a feature request with GitHub.
