### ISSUE TITLE
Is it possible to have kDebugMode to true in an Testflight iOS application build?

### ISSUE THREAD

**Issue by ArthurMaroulier** [flutter/flutter#118688]
Hello, is it possible to build and archive an **iOS build to Testflight** with the Flutter **kDebugMode** to **true**?

Thanks.

**Comment by maRci002** [comment]
`flutter build ios --debug`
`flutter build ipa --debug`

**Comment by darshankawar** [comment]
@ArthurMaroulier 
Check above comment / solution and see if it answers your question. Also, I suggest you to ask support questions on StackOverflow.
Closing from here.

**Comment by ArthurMaroulier** [comment]
Hello we'r aware of these, but we were facing error while building. My manager make the demand to ask the question here to be sure and do not loose time. Sorry.
