### ISSUE TITLE
A GestureDetector's onTap doesn't trigger if parent of LongPressDraggable.

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#1186]
It does work if the GestureDetector is a child of the LongPressDraggable.

**Comment by Hixie** [comment]
Odd.

**Comment by abarth** [comment]
Still seems to happen.

**Comment by abarth** [comment]
The tap recognizer just looks busted.

**Comment by abarth** [comment]
Actually, just a subtle bug in DelayedMultiDragGestureRecognizer
