### ISSUE TITLE
Dart -> Engine rolls failing due to web engine test failures

### ISSUE THREAD

**Issue by iskakaushik** [flutter/flutter#118630]
The failure is 
```
00:12 [32m+54[0m[31m -1[0m: test/canvaskit/embedded_views_test.dart: HtmlViewEmbedder does not crash when resizing the window after textures have been registered [1m[31m[E][0m[0m                                                
  ImageCodecException: Failed to decode image using the browser's ImageDecoder API.
  Image source: test
  Original browser error: Error: Failed to construct 'ImageDecoder': Failed to read the 'data' property from 'ImageDecoderInit': The provided value is not of type '(ReadableStream or [AllowShared] ArrayBuffer or [AllowShared] ArrayBufferView)'.
  org-dartlang-sdk:///lib/_internal/js_runtime/lib/js_helper.dart 1129:37   Object.wrapException
  ../../../../lib/src/engine/canvaskit/image_web_codecs.dart 207:7          <fn>
  org-dartlang-sdk:///lib/_internal/js_runtime/lib/async_patch.dart 308:19  _wrapJsFunctionForAsync.closure.$protected
  org-dartlang-sdk:///lib/_internal/js_runtime/lib/async_patch.dart 333:23  _wrapJsFunctionForAsync.<fn>
  org-dartlang-sdk:///lib/_internal/js_runtime/lib/async_patch.dart 238:3   Object._asyncStartSync
  ../../../../lib/src/engine/canvaskit/image_web_codecs.dart 137:5          CkBrowserImageDecoder._getOrCreateWebDecoder
  ../../../../lib/src/engine/canvaskit/image_web_codecs.dart 80:11          <fn>
  org-dartlang-sdk:///lib/_internal/js_runtime/lib/async_patch.dart 308:19  _wrapJsFunctionForAsync.closure.$protected
  org-dartlang-sdk:///lib/_internal/js_runtime/lib/async_patch.dart 333:23  _wrapJsFunctionForAsync.<fn>
  org-dartlang-sdk:///lib/_internal/js_runtime/lib/async_patch.dart 238:3   Object._asyncStartSync
```

logs: https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8791755201668024865/+/u/felt_test:_chrome-unit-linux/stdout
PR: https://github.com/flutter/engine/pull/38929/checks?check_run_id=10688642972

Probable commits causing this issue:

- [572d545](https://dart.googlesource.com/sdk.git/+/572d545c72a0d49f4a0d1e2f0c7ae2269dece8e1) [[dart:_js_interop] Add dart:_js_interop](https://dart.googlesource.com/sdk.git/+/572d545c72a0d49f4a0d1e2f0c7ae2269dece8e1) by Srujan Gaddam · 19 hours ago [base](https://dart.googlesource.com/sdk.git/+/refs/heads/base)
- [0673894](https://dart.googlesource.com/sdk.git/+/0673894cd932d0e7030038fdf8eac4046d2a6d71) [[pkg:js] Disallow @staticInterop synthetic and @anonymous constructor tear-offs](https://dart.googlesource.com/sdk.git/+/0673894cd932d0e7030038fdf8eac4046d2a6d71) by Srujan Gaddam · 19 hours ago
- [b9002bf](https://dart.googlesource.com/sdk.git/+/b9002bfe55c3c828be9dacf7cb6324a2ee04fd7e) [[ddc] Inline js_util transformation methods](https://dart.googlesource.com/sdk.git/+/b9002bfe55c3c828be9dacf7cb6324a2ee04fd7e) by Srujan Gaddam · 19 hours ago
- [f043318](https://dart.googlesource.com/sdk.git/+/f04331891f0124f9beffaed328eadd03b5d98280) [Update CFE expectations and fix top-level external members](https://dart.googlesource.com/sdk.git/+/f04331891f0124f9beffaed328eadd03b5d98280) by Srujan Gaddam · 19 hours ago
- [9c8051b](https://dart.googlesource.com/sdk.git/+/9c8051b3ee319aff15a08842d5c0d305c35e803a) [[pkg:js] Lower @staticInterop external anonymous and non-anonymous constructors](https://dart.googlesource.com/sdk.git/+/9c8051b3ee319aff15a08842d5c0d305c35e803a) by Srujan Gaddam · 19 hours ago
- [bb20923](https://dart.googlesource.com/sdk.git/+/bb2092368c139096519bb0633de83bf5f21a87f9) [[pkg:js] Lower external top-level package:js members](https://dart.googlesource.com/sdk.git/+/bb2092368c139096519bb0633de83bf5f21a87f9) by Srujan Gaddam · 19 hours ago
- [1e06e37](https://dart.googlesource.com/sdk.git/+/1e06e37e18b82003a3128ea86d376e71583e42bd) [[pkg:js] Lower external static @staticInterop class members](https://dart.googlesource.com/sdk.git/+/1e06e37e18b82003a3128ea86d376e71583e42bd) by Srujan Gaddam · 19 hours ago

**Comment by iskakaushik** [comment]
cc: @srujzs

**Comment by srujzs** [comment]
It looks like the change in constructor lowerings has caused this. I reverted it for a similar reason to unblock google3 here: https://dart-review.googlesource.com/c/sdk/+/279180. Is it possible to try the roll with this revert?

**Comment by iskakaushik** [comment]
The engine framework rollers are failing see https://github.com/flutter/flutter/issues/118632 , waiting for a revert https://dart-review.googlesource.com/c/sdk/+/279141 to land before restarting the roller.

**Comment by iskakaushik** [comment]
this error has now been fixed.
