### ISSUE TITLE
obscureText variable state does not change after clicking on suffixIcon

### ISSUE THREAD

**Issue by ZagumennikovYaroslav** [flutter/flutter#118600]
![image](https://user-images.githubusercontent.com/91648112/212834922-a9cce065-e325-4a26-817b-6a3d2e8e801e.png)
![image](https://user-images.githubusercontent.com/91648112/212835079-7ccddfa9-1453-45d8-809d-2b66538b5b37.png)
![image](https://user-images.githubusercontent.com/91648112/212835308-7c646bb6-6502-48e6-94a1-1def6413fdd3.png)

**Comment by danagbemava-nc** [comment]
Hi @ZagumennikovYaroslav, please provide a complete minimal reproducible code sample along with the output of `flutter doctor -v`. 

Please do not provide screenshots of the code. Provide the code in text form. 

Thank you

**Comment by ZagumennikovYaroslav** [comment]
![image](https://user-images.githubusercontent.com/91648112/212898005-323765ad-642a-43a7-83f3-62e72c1eda97.png)


Code

import 'dart:ui';

import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

void main() {
  runApp(MaterialApp(
    home: Scaffold(
      body: Auth(),
    ),
  ));
}

class Auth extends StatefulWidget {
  const Auth({Key? key}) : super(key: key);

  @override
  State<Auth> createState() => _AuthState();
}

class _AuthState extends State<Auth> {
  bool visPass = true;
  @override
  Widget build(BuildContext context) {
    return
        Container(
          color: Colors.white,
          // Так как ClipPath обрезает таким образом, что внутри выведеной формы видна картинка
          // а за границами обрезания не видно, но отрезнная часть никуда не девается
          // чтобы избавиться от отступа, был добавлен виджет Stack,который позволяет
          // лепить виджеты поверх других
          // Обрезанная картинка будет фоном приложения, а структура будет лепиться заново
          child: Stack(
            children: [

              ClipPath(
                clipper: AuthAppBarClip(),
                child: Image.asset(
                  "assets/images/fone.jpg"
                ),
              ),
              // Иконка листа, можно было найти картинку с листом, но не было
              // Внутренний отступ указывать в вещественном виде
              Container(
                height: 200,
                width: double.infinity,
                padding: EdgeInsets.only(top: 100.0),
                child: Center( child:Image.asset("assets/images/leaves2.png"),)
              ),
              Align(
                alignment: Alignment.center,
                child: Column(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: <Widget>[
                    // Собрать всё в один контейнер и покрасить его в белый, цветок вывести в этот контейнер
                          Container(
                            width: 330,
                            decoration: BoxDecoration(
                              color: Colors.white,
                              borderRadius: BorderRadius.circular(30),
                            ),
                            child: Column(
                              children: <Widget>[
                                Container(
                                  height: 100,
                                  child: Column(
                                    mainAxisAlignment: MainAxisAlignment.center,
                                    children: [
                                      Text(
                                        'Welcome back',
                                        style: GoogleFonts.poppins(
                                            fontSize: 30,
                                            fontWeight: FontWeight.bold,
                                            color: Color.fromRGBO(29, 85, 74, 1)
                                        ),
                                      ),
                                      Text(
                                        'login to your account',
                                        style: GoogleFonts.poppins(
                                            fontSize: 15,
                                            color: Color.fromRGBO(29, 85, 74, 0.5)
                                        ),
                                      )
                                    ],
                                  ),
                                ),
                                Container(
                                  child: Column(
                                    children: <Widget>[
                                      Padding(padding: EdgeInsets.only(top: 30)),
                                      Container(
                                        width:300,
                                        child: Padding(
                                          padding: EdgeInsets.symmetric(horizontal: 0),
                                          child: TextField(
                                            style: GoogleFonts.poppins(
                                                fontSize: 15,
                                                color: Color.fromRGBO(29, 85, 74, 0.5)
                                            ),

                                            decoration: InputDecoration(
                                              prefixIcon: Icon(Icons.mail_rounded, color: Color.fromRGBO(81,113, 95, 1),),
                                              border: OutlineInputBorder(
                                                  borderRadius: BorderRadius.circular(10.0)
                                              ),
                                              enabledBorder: OutlineInputBorder(
                                                  borderSide: BorderSide(color: Color.fromRGBO(217, 228, 219, 1),),
                                                  borderRadius: BorderRadius.circular(10.0)
                                              ),

                                              hintText: 'Enter Email',
                                              hintStyle: GoogleFonts.poppins(
                                                  fontSize: 15,
                                                  color: Color.fromRGBO(29, 85, 74, 0.5)
                                              ),
                                              filled: true,
                                              fillColor: Color.fromRGBO(217, 228, 219, 1),
                                            ),
                                          ),
                                        ),
                                      ),
                                      Padding(padding: EdgeInsets.only(top: 20)),
                                      Container(
                                        width:300,
                                        child: Padding(
                                          padding: EdgeInsets.symmetric(horizontal: 0),
                                          child: TextField(
                                            style: GoogleFonts.poppins(
                                                fontSize: 15,
                                                color: Color.fromRGBO(29, 85, 74, 0.5)
                                            ),
                                            obscureText: visPass,
                                            obscuringCharacter: '●',
                                            decoration: InputDecoration(
                                              prefixIcon: Icon(Icons.lock_rounded, color: Color.fromRGBO(81,113, 95, 1),),
                                              suffixIcon: IconButton(
                                                icon: Icon(Icons.visibility_off, color: Color.fromRGBO(81,113, 95, 1),),
                                                iconSize: 25,
                                                onPressed: (){
                                                  setState(() {
                                                    visPass = !visPass;

                                                  });
                                                }
                                              ),
                                              border: OutlineInputBorder(
                                                  borderRadius: BorderRadius.circular(10.0)
                                              ),
                                              enabledBorder: OutlineInputBorder(
                                                  borderSide: BorderSide(color: Color.fromRGBO(217, 228, 219, 1),),
                                                  borderRadius: BorderRadius.circular(10.0)
                                              ),

                                              hintText: 'Enter Password',
                                              hintStyle: GoogleFonts.poppins(
                                                  fontSize: 15,
                                                  color: Color.fromRGBO(29, 85, 74, 0.5)
                                              ),
                                              filled: true,
                                              fillColor: Color.fromRGBO(217, 228, 219, 1),
                                            ),

                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                                Container(
                                  alignment: Alignment.centerRight,
                                  padding: EdgeInsets.fromLTRB(0, 10, 15, 0),
                                  child: Text("Forgot Password?", style: GoogleFonts.poppins(
                                      fontSize: 15,
                                      color: Color.fromRGBO(29, 85, 74, 0.5)
                                  ),),
                                ),

                              ],
                            ),
                          ),
                        ],
                      ),
              ),
              Align(
                alignment: Alignment.centerRight,
                child: Container(
                  width: 140,
                  padding: EdgeInsets.only(bottom: 70),
                  child: Image.asset("assets/images/leaves1.png"),
                ),
              ),
            ],
          )
        );
  }
}




class AuthAppBarClip extends CustomClipper<Path> {
  @override
  Path getClip (Size size){
    final path0 = Path();
    path0.moveTo(0,size.height*0.9000000);
    path0.quadraticBezierTo(0,size.height*0.5250000,0,0);
    path0.lineTo(size.width,0);
    path0.quadraticBezierTo(size.width*1.0003333,size.height*0.5473000,size.width,size.height*0.5483250);
    path0.cubicTo(size.width*0.2489333,size.height*0.7601500,size.width*0.2171333,size.height*0.7594000,0,size.height*0.7000000);
    path0.close();
    return path0;
  }
  @override
  bool shouldReclip(covariant CustomClipper<Path> oldClipper) {
    throw UnimplementedError();
  }
}

**Comment by ZagumennikovYaroslav** [comment]
I uploaded my project to the GitHub, you can download it, it's called "plant_care" in my profile. He is public

**Comment by ZagumennikovYaroslav** [comment]
i solved the problem. It turned out that the state cannot be changed in the widget where ClipPath is present, since when the state changes, ClipPath must crop the photo each time
