### ISSUE TITLE
iOS PlatformViews: pre-determine if clipPath is necessary

### ISSUE THREAD

**Issue by cyanglaz** [flutter/flutter#118650]
We might be able to find a way to pre-determine if clip path is necessary because applying it to PlatformViews.
We did such optimization for ClipRect and ClipRRect, see example: https://github.com/flutter/engine/pull/37434

This is not as trivial as clipRect or clipRRect because there are no trivial API in SkMatrix to map a path.

**Comment by jonahwilliams** [comment]
Now that clipping is switched to the GPU accellerated clip, is this actually worth fixing? paths can be arbitrarily complex. FYI @hellohuanlin

**Comment by hellohuanlin** [comment]
I think we can close it now, marking it as fixed by https://github.com/flutter/engine/pull/53072
