### ISSUE TITLE
Calling `EventChannel::SetStreamHandler` in plugin destructor causes crash

### ISSUE THREAD

**Issue by jnschulze** [flutter/flutter#118611]
Calling `EventChannel::SetStreamHandler` (or `MethodChannel::SetMethodCallHandler`, respectively) in a plugin destructor causes an access violation:

![image](https://user-images.githubusercontent.com/720469/212888505-d5043f9c-1ce5-4bc9-bcf3-165629300b15.png)

While this is trivial to work around by not unsetting the stream handler, I think doing so should not be illegal.

Minimal reproducible example:
https://github.com/jnschulze/flutter-playground/blob/78c36485f3457b9de687b7e4b94c116d9b117176/eventchannel_win/windows/eventchannel_win_plugin.cpp#L57

Flutter version:
```
Flutter 3.7.0-21.0.pre.38 • channel master • https://github.com/flutter/flutter.git
Framework • revision 68dd63d66b (4 days ago) • 2023-01-13 15:34:33 -0800
Engine • revision a512cebdcd
Tools • Dart 3.0.0 (build 3.0.0-122.0.dev) • DevTools 2.20.0
```

**Comment by loic-sharma** [comment]
We've clarified the documentation and crash message to make this scenario clearer. I'll close this off for now but let us know if you have additional feedback!
