### ISSUE TITLE
Error (Xcode): ../../../.pub-cache/hosted/pub.dev/flutter_math_fork-0.5.0/lib/src/widgets/selection/gesture_detector_builder.dart:186:20: Error: The argument type 'void Function(TapDownDetails)' can't be assigned to the parameter type 'void Function(TapDragDownDetails)?'.

### ISSUE THREAD

**Issue by theappideasankit** [flutter/flutter#118670]
`Error (Xcode): ../../../.pub-cache/hosted/pub.dev/flutter_math_fork-0.5.0/lib/src/widgets/selection/gesture_detector_builder.dart:186:20: Error: The argument type 'void Function(TapDownDetails)' can't be assigned to the parameter type 'void Function(TapDragDownDetails)?'.`

**Comment by darshankawar** [comment]
The error is pointing to third party plugin https://pub.dev/packages/flutter_math_fork, so please file this in dedicated repo.
Closing from here.

**Comment by theappideasankit** [comment]
but i didn't use this package so why this error is showing me?

**Comment by darshankawar** [comment]
Try to clear your pub cache, and then pod install and see if it helps. It looks like a cache issue.
