### ISSUE TITLE
PopupMenuItem doesn't pop the right thing

### ISSUE THREAD

**Issue by BananaMasterz** [flutter/flutter#118625]
## Steps to Reproduce

1. Execute `flutter run` on the code sample
2. Tap the `PopupMenuButton` and then tap the top `PopupMenuItem`. Notice that nothing happens. That's because after a `PopupMenuItem` is tapped, it attempt's to pop its parent `PopupMenuButton`, this is not right as you can see since if I have a `Navigator.push` action set on the `onTap`, it pops the Screen I just pushed instead of the `PopupMenuButton`. The second `PopupMenuButton` works because I push the screen twice, so the pop is consumed by the first push.

**Expected results:**
Pop the `PopupMenuButton` and then execute the `onTap`, or wait for the pushed screen to return since the `context` used to push the screen being lost might cause issues?

**Temporary workaround until fixed:**
```dart
onTap: () => WidgetsBinding.instance.addPostFrameCallback((_) {
      Navigator.push(
        context,
        MaterialPageRoute(
          builder: (BuildContext context) {
            return const PushedScreen();
          },
        ),
      );
    })),
```
<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Row(
          mainAxisSize: MainAxisSize.min,
          children: [
            const Text('Press here'),
            const Icon(Icons.arrow_forward),
            PopupMenuButton(
              itemBuilder: (BuildContext context) {
                return [
                  PopupMenuItem(
                    child: const Text("Push me I don't work"),
                    onTap: () => Navigator.push(
                      context,
                      MaterialPageRoute(
                        builder: (BuildContext context) {
                          return const PushedScreen();
                        },
                      ),
                    ),
                  ),
                  PopupMenuItem(
                    child: const Text("Push me I work"),
                    onTap: () {
                      // Navigate
                      Navigator.push(
                        context,
                        MaterialPageRoute(
                          builder: (BuildContext context) {
                            return const PushedScreen();
                          },
                        ),
                      );
                      // Navigate again
                      Navigator.push(
                        context,
                        MaterialPageRoute(
                          builder: (BuildContext context) {
                            return const PushedScreen();
                          },
                        ),
                      );
                    },
                  ),
                ];
              },
            ),
          ],
        ),
      ),
    );
  }
}

class PushedScreen extends StatefulWidget {
  const PushedScreen({Key? key}) : super(key: key);

  @override
  State<PushedScreen> createState() => _PushedScreenState();
}

class _PushedScreenState extends State<PushedScreen> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(), // for navigation purposes
      body: const Center(child: Text('Ouch')),
    );
  }
}

```

</details>

<details>
  <summary>flutter doctor -v</summary>
[√] Flutter (Channel stable, 3.3.10, on Microsoft Windows [Version 10.0.22000.1455], locale el-GR)
    • Flutter version 3.3.10 on channel stable at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (5 weeks ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at C:\Users\Kyria\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.2.5)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.2.32616.157
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2022.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22000.1455]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 109.0.5414.74
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 108.0.1462.42

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
</details>

**Comment by danagbemava-nc** [comment]
Hi @BananaMasterz, this issue is known and is being tracked in https://github.com/flutter/flutter/issues/87766. 

Kindly follow up in the issue linked above for updates. 

Closing from here as duplicate. 

Thank you
