### ISSUE TITLE
Fuchsia Roll failing due to `FileTest.VisitFilesCanBeCalledTwice` failure

### ISSUE THREAD

**Issue by iskakaushik** [flutter/flutter#118627]
roll attempt: https://github.com/flutter/engine/pull/38945

Failure: https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20Fuchsia%20FEMU/26719/overview

Log: https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8791706323746450625/+/u/run_FEMU_test_on_x64/run_fml_tests/run_ffx_test__3_/stdout

**Comment by iskakaushik** [comment]
x-ref: https://bugs.fuchsia.dev/p/fuchsia/issues/detail?id=119323#c8

**Comment by chinmaygarde** [comment]
This is being worked on in the linked bug and still seems to be an issue as of 20 mins ago.

**Comment by jonahwilliams** [comment]
This is out of date
