### ISSUE TITLE
Expose `onSecondaryTap` in `InkWell`

### ISSUE THREAD

**Issue by mgenware** [flutter/flutter#118622]
`InkWell` is great. I like the opt-in hover effect. Right now `InkWell` doesn't have `onSecondaryTap` exposed. It has `onLongPress`, which is only useful on mobile. It would be weird to ask users to long press with mouse left button instead of using the `onSecondaryTap` on desktop to trigger a context menu.

https://github.com/flutter/flutter/blob/cc7845e71a9d2774f5e7b17b4cce6b0e16921227/packages/flutter/lib/src/material/ink_well.dart#L1236-L1244

**Comment by darshankawar** [comment]
The same is mentioned here: https://github.com/flutter/flutter/issues/116643#issuecomment-1346937940
