### ISSUE TITLE
ColorFiltered widget not working with transparency of SVG images

### ISSUE THREAD

**Issue by subzero911** [flutter/flutter#118601]
When I use a ColorFiltered widget to tone out the SVG image (`flutter_svg` library), it doesn't consider the transparency.
I tried various BlendModes, and not one is working properly.

 Normal image:
<img width="169" alt="image" src="https://user-images.githubusercontent.com/12999702/212843986-f1045c21-7dd0-4cd7-a141-25b1e5bfbba3.png">

Code sample:
<img width="448" alt="image" src="https://user-images.githubusercontent.com/12999702/212843271-74b9cae2-d6cb-485d-adac-331b76849141.png">

Result:
<img width="182" alt="image" src="https://user-images.githubusercontent.com/12999702/212843755-98dca02c-4044-40af-bc58-b94d5fd48956.png">

**Comment by darshankawar** [comment]
@subzero911 
Can you check [this](https://github.com/flutter/flutter/issues/12990) similar issue and see if it resembles your case ?

**Comment by subzero911** [comment]
@darshankawar it looks very similar to my case.
Perhaps, these topics can be merged: this topic can be closed, and it is worth clarifying in that topic that ColorFiltered also does not work with SVG.

**Comment by darshankawar** [comment]
Thanks for the feedback. Closing this in favor of the original. You may follow-up in that issue for further updates.
