### ISSUE TITLE
Setup new devicelab rack space

### ISSUE THREAD

**Issue by yusuf-goog** [flutter/flutter#118648]
Please setup a new rack as per available equipment.

Also, note how many available network connections are available from our existing switches, that we can use in the new rack.

**Comment by kentnguyen99** [comment]
Will check and work on this.

**Comment by yusuf-goog** [comment]
There are 8 available drops. 
Ordering a network switch to try and expand into the new racks, risk is shared bandwidth with existing switch.
Also ordered network cables.

**Comment by yusuf-goog** [comment]
Ordered GS348 switch.

**Comment by yusuf-goog** [comment]
We were able to secure 4 trays for the new rack, still waiting on lab team to acquire additional trays for us.
