### ISSUE TITLE
ruby failures on mac_arm64

### ISSUE THREAD

**Issue by yusuf-goog** [flutter/flutter#118760]
ios_app_with_extensions_test build on mac arm64 failing with:

```
Uncaught Exception: ValueError('Dependency %s not available. Ensure ci.yaml contains one of the following supported keys: %s')
```

See:

https://luci-milo.appspot.com/ui/p/flutter/builders/staging/Mac_arm64_staging%20ios_app_with_extensions_test/4975/overview

This is because `"dependency": "arm64ruby"` does not exist anymore.

**Comment by yusuf-goog** [comment]
CL: https://flutter-review.git.corp.google.com/c/infra/+/38124

**Comment by yusuf-goog** [comment]
The above CL moves us past the original error, but encounter:

```CIPD('ensure_installed') failed with: failed to resolve flutter/ruby/mac-arm64@latest (line 1): no such ref```

see:
https://luci-milo.appspot.com/raw/build/logs.chromium.org/flutter/led/mohsinally_google.com/79906800645a70624207aa7a393274f1bd99363743ae6a3f44716c76e26d68aa/+/build.proto

**Comment by godofredoc** [comment]
These tests are now passing consistently https://ci.chromium.org/p/flutter/builders/prod/Mac_arm64_ios%20ios_app_with_extensions_test
