### ISSUE TITLE
Flutter customer tests should not be analyzed with fatal warnings.

### ISSUE THREAD

**Issue by srawlins** [flutter/flutter#118714]
When the flutter customer tests analyze a customer repository (I believe with [`flutter_test_runner.sh`](https://github.com/flutter/cocoon/blob/main/test_utilities/bin/flutter_test_runner.sh)), warnings are treated as fatal, so when the Dart static analysis team lands new warnings, the customer tests fail. I believe they should not.

The changed behavior, which is reporting new warnings about existing code, is intentional. It should not be a cause for a break in the flutter engine CI.

The fix would be to pass `--no-fatal-warnings` to `flutter analyze`.

CC @bwilkerson @jacob314

**Comment by bwilkerson** [comment]
I'll just add that this is based on the premise that our commitment to not break the user's code is limited to certain kinds of breakages and that the tests should only be testing the breakages covered by the commitment. In the same way that we didn't promise to not introduce breaking changes to the language (such as the upcoming change to the semantics of switch statements, or the change that disallows opting back to any version before 2.12), we have not promised that we wouldn't break their code by adding new warnings in order to do a better job of helping users identify bugs in their code.

While it's necessary to look for compilation errors in order to determine whether an API change has broken the user's code, I don't believe that any warning (existing or future) needs to be checked for in order to determine that an API change is valid. If you know of any counterexamples, please let us know so that we can find another way to mitigate this situation.

**Comment by srawlins** [comment]
Ping. Should I send a PR?

**Comment by srawlins** [comment]
CC @devoncarew @goderbauer @Hixie

**Comment by goderbauer** [comment]
For context, we did a similar thing in https://github.com/flutter/tests/pull/105 where we ignored info level items. That PR description claims that warning level items "to some extent" are also relevant to determine whether API changes break customers. Has anything changed that that's no longer true?

Also, to determine what kind of coverage we would lose if we made this change: Is there a list somewhere of the warnings that would get ignored if we go forward with this?

**Comment by goderbauer** [comment]
Ideally, the customers who add their tests to flutter/tests would respond promptly in helping with fixing any issues that arise. That is our documented policy [1]. Wondering if the motivation behind this proposal is more a lack of prompt responses than a technical reason? In the former case, we should enforce the policy of removing them over reducing our coverage by ignoring warnings...

[1] https://github.com/flutter/tests#if-a-test-is-broken

**Comment by Hixie** [comment]
Why wouldn't we just go and fix the warnings?

**Comment by srawlins** [comment]
I'll note some more context: we're removing the Hint diagnostic category, and moving most Hints to be Warnings. Hints did not cause `dart analyze` to exit with a non-zero exit, but Warnings do. To continue the old behavior of not having these various diagnostics cause `dart analyze` to exit with a non-zero exit, the flag `--no-fatal-warnings` can be used.

> That PR description claims that warning level items "to some extent" are also relevant to determine whether API changes break customers. Has anything changed that that's no longer true?

Nothing has changed, I believe. I don't think warning level items ever determined whether API changes broke customers.  In Dart 2.19.0, for example, there are only [5 StaticWarningCodes](https://github.com/dart-lang/sdk/blob/2.19.0/pkg/analyzer/messages.yaml#L23040):
* [`DEAD_NULL_AWA_RE_EXPRESSION`](https://github.com/dart-lang/sdk/blob/2.19.0/pkg/analyzer/messages.yaml#L23041)
* [`INVALID_NULL_AWARE_OPERATOR`](https://github.com/dart-lang/sdk/blob/2.19.0/pkg/analyzer/messages.yaml#L23120)
* [`INVALID_NULL_AWARE_OPERATOR_AFTER_SHORT_CIRCUIT`](https://github.com/dart-lang/sdk/blob/2.19.0/pkg/analyzer/messages.yaml#L23197)
* [`MISSING_ENUM_IN_CONSTANT_SWITCH`](https://github.com/dart-lang/sdk/blob/2.19.0/pkg/analyzer/messages.yaml#L23206)
* [`UNNECESSARY_NON_NULL_ASSERTION`](https://github.com/dart-lang/sdk/blob/2.19.0/pkg/analyzer/messages.yaml#L23273)

Viewed holistically, I would claim this is more or less a random selection of "non-error" codes. There's really no difference between these and many of the Hints.

> Also, to determine what kind of coverage we would lose if we made this change: Is there a list somewhere of the warnings that would get ignored if we go forward with this?

It will be all of the existing StaticWarningCodes and the vast majority of HintCodes (source of truth is [here](https://github.com/dart-lang/sdk/blob/2.19.0/pkg/analyzer/messages.yaml#L17577)). I think the list of Hints which will continue to not be fatal by default is:

* `DEPRECATED_MEMBER_USE_FROM_SAME_PACKAGE`
* `DEPRECATED_MEMBER`
* `DIVISION_OPTIMIZATION`
* `FILE_IMPORT_INSIDE_LIB_REFERENCES_FILE_OUTSIDE`
* `FILE_IMPORT_OUTSIDE_LIB_REFERENCES_FILE_INSIDE`
* `IMPORT_DEFERRED_LIBRARY_WITH_LOAD_FUNCTION`
* `IMPORT_OF_LEGACY_LIBRARY_INTO_NULL_SAFE`
* `PACKAGE_IMPORT_CONTAINS_DOT_DOT`
* `TYPE_CHECK_IS_NOT_NULL`
* `TYPE_CHECK_IS_NULL`

Most of these should be documented at https://dart.dev/tools/diagnostic-messages.

> Wondering if the motivation behind this proposal is more a lack of prompt responses than a technical reason? In the former case, we should enforce the policy of removing them over reducing our coverage by ignoring warnings...

The motivation is both. There is a high cost to cleaning up all violations of a new warning that exist in the world before the new warning can even be written.

However, I think the reasoning stands on its own. The customer tests should not have to analyze perfectly cleanly when using Dart at HEAD and flutter at HEAD (as was, I imagine, the reasoning for using `--no-fatal-infos` already).

**Comment by Hixie** [comment]
In general I would much rather we be fixing these tests than ignoring warnings. The whole point here is to feel the pain we are putting our developers under. If these warning are painful, we should feel that pain. I wasn't especially eager for us to disable the lints, but I'm even less eager for us to disable warnings.

**Comment by hampsterx** [comment]
I have a choice to run or not run `analyze` I want some warnings in my face please!

> but I'm even less eager for us to disable warnings

Huh, it's an "analyzer", it needs to run :P

**Comment by Hixie** [comment]
I think we changed this already for most customer tests.

In general this infrastructure has no owner so if there is a needed change I recommend just filing a PR to fix it (possibly after creating a design doc and socializing it around if it's a significant or potentially controversial change).
