### ISSUE TITLE
[packages] Add support for Kotlin auto-formatting

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#118756]
It's likely that at some point we'll have Kotlin code in our 1P plugins (per https://flutter.dev/go/flutter-plugin-languages), and we are already managing some Kotlin code in Pigeon. It would be good to have an autoformatter for it the way we do for most of our other languages (see also https://github.com/flutter/flutter/issues/41129).

From initial investigation it looks like IntelliJ has a formatter, but built into the IDE. It's [apparently possible to run from the command line](https://www.jetbrains.com/help/idea/command-line-formatter.html), but it "launches an instance of IntelliJ IDEA in the background and applies the formatting". That seems problematic for a tool that we want to be lightweight to set up, and to run in CI.

The tools that came up in an initial search that better match our needs are [ktlint](https://github.com/pinterest/ktlint) and [ktfmt](https://github.com/facebook/ktfmt). We should evaluate those to see if they work for for us, and if so integrate one of them into the repo tool's `format` command.

**Comment by stuartmorgan** [comment]
I gave the two formatters above a try today, running them over the `pigeon` directory since that's pretty much our current set of kotlin code. Here results for two of our largest files (one Pigeon-generated, one hand-authored):
- `ktfmt` (2-space indent; this is the default, but [violates the official Kotlin style guidance](https://kotlinlang.org/docs/coding-conventions.html#indentation))
  - [CoreTests.gen.kt](https://github.com/stuartmorgan/packages/blob/67d8f992de7c58bc467526368fdee230f54a9d81/packages/pigeon/platform_tests/test_plugin/android/src/main/kotlin/com/example/test_plugin/CoreTests.gen.kt)
  - [TestPlugin.kt](https://github.com/stuartmorgan/packages/blob/67d8f992de7c58bc467526368fdee230f54a9d81/packages/pigeon/platform_tests/test_plugin/android/src/main/kotlin/com/example/test_plugin/TestPlugin.kt)
- `ktfmt` (4-space indent option)
  - [CoreTests.gen.kt](https://github.com/stuartmorgan/packages/blob/45bd225a4c2d87d2b9a62616d46754f08c405bcd/packages/pigeon/platform_tests/test_plugin/android/src/main/kotlin/com/example/test_plugin/CoreTests.gen.kt)
  - [TestPlugin.kt](https://github.com/stuartmorgan/packages/blob/45bd225a4c2d87d2b9a62616d46754f08c405bcd/packages/pigeon/platform_tests/test_plugin/android/src/main/kotlin/com/example/test_plugin/TestPlugin.kt)
- `ktlint` (default settings)
  - [CoreTests.gen.kt](https://github.com/stuartmorgan/packages/blob/d5576975bb415581c016732afa4c6da50d7f69f8/packages/pigeon/platform_tests/test_plugin/android/src/main/kotlin/com/example/test_plugin/CoreTests.gen.kt)
  - [TestPlugin.kt](https://github.com/stuartmorgan/packages/blob/d5576975bb415581c016732afa4c6da50d7f69f8/packages/pigeon/platform_tests/test_plugin/android/src/main/kotlin/com/example/test_plugin/TestPlugin.kt)

Some general notes:
- `ktfmt` is installed and run exactly the same way the repo tooling already installs and runs the Google Java formatter (downloading a `.jar` from [a known location](https://repo1.maven.org/maven2/com/facebook/ktfmt/0.46/) and running it), so it would be trivial to integrate. `ktlint` would probably require making a CIPD package for bots, and linking to [instructions](https://github.com/pinterest/ktlint#quick-start) for developers.
- `ktfmt` has basically no configuration options beyond 2 or 4 space indentation (could be a pro or con; currently I don't think any of us knows or cares about exact details of Kotlin formatting enough to want to argue about settings anyway though.)
- Things I notice about the output:
  - `ktlint` (at least with default options) seems to be much more aggressive about making any function declaration with more than one parameter multi-line.
  - `ktlint` seems to be more aggressive about adding vertical whitespace between definitions.

My inclination at this point would be to use `ktfmt` since it would be so easy to add to the existing tooling, and if we ever find we really dislike the output we could consider replacing it with `ktlint` for more customization. I would lean toward using two-space indentation even though it violates Kotlin conventions because I believe we use two-space in literally every other language, so not having that as one more difference when switching languages would be nice (this is in fact [the primary reason `ktfmt` defaults to that](https://github.com/facebook/ktfmt#ktfmt-uses-a-2-space-indent-why-not-4-any-way-to-change-that)), but there's an argument for following standard language conventions given that they do exist.

/cc @reidbaker and @tarrinneal for input as the two people most likely to have opinions on this.

**Comment by stuartmorgan** [comment]
(It looks like 2-space `ktfmt` would align us with internal code FWIW.)

**Comment by tarrinneal** [comment]
I strongly encourage 2 spaces, if only for my personal sanity.

**Comment by reidbaker** [comment]
I like `ktfmt` with 2 spaces. If we get more opinionated we can change later but being easier to get up and running seems like a win for now.
