### ISSUE TITLE
[web]: <describe issue here>

### ISSUE THREAD

**Issue by Refaydeen** [flutter/flutter#118779]
i have a doubt regarding flutter PWA ..is flutter PWA still working or not ,can we expect a flutter pwa upgraded package in upcoming days??

**Comment by darshankawar** [comment]
@Refaydeen 
You can check [this](https://docs.flutter.dev/deployment/web#pwa-support) section of the document for details on PWA. As mentioned in it, if you face any issues with it, please file appropriate issue for it using the link mentioned in it.

Closing this issue for now.
