### ISSUE TITLE
`flutter create` creates less menu items on macOS than the default Xcode template

### ISSUE THREAD

**Issue by mgenware** [flutter/flutter#118770]
I know I can use [PlatformMenuBar](https://api.flutter.dev/flutter/widgets/PlatformMenuBar-class.html) to update macOS menus anyway. It's just a suggestion that our default macOS app template should be more or less the same as the Xcode one to reduce friction for native macOS devs.

App created with Flutter (Channel stable, 3.3.10, on macOS 13.1 22C65 darwin-arm)
<img width="331" alt="Screenshot 2023-01-19 at 13 28 14" src="https://user-images.githubusercontent.com/11565096/213363456-928fea8b-7fc9-44a5-9a6f-f4a0b4922876.png">

App created with macOS app project with Xcode 14.2
<img width="445" alt="Screenshot 2023-01-19 at 13 26 27" src="https://user-images.githubusercontent.com/11565096/213363501-24404367-1bae-4182-8526-666221edbd3d.png">

File and Format menu items are missing in Flutter. More importantly, Xcode creates a "File -> Close window" item, which also brings CMD+W to close current window, which is one of the most used keyboard shortcuts on macOS. I have to hook up events and implement it myself in a flutter app.

**Comment by huycozy** [comment]
@mgenware As I understand, this is a proposal/new feature to build default menus on Flutter macOS app, right?

As you said above, we can implement these kind of menu with using `PlatformMenuBar`, such as:
![Screenshot 2023-01-19 at 17 56 01](https://user-images.githubusercontent.com/104349824/213424569-5014a2d6-d03f-4363-a452-5d257036c05a.png)

**Comment by mgenware** [comment]
@huycozy Yes, I can implement it myself. What I was suggestion is those default things should be implemented on template level instead of forcing developers to write the same code on every new flutter apps. Especially if you were coming from a macOS background, you would feel a bit frustrated that those things you've been taking it for granted from xcode are now missing and have to be implemented by yourself. :D

**Comment by darshankawar** [comment]
@mgenware 
I think a similar issue was raised by you earlier: https://github.com/flutter/flutter/issues/102439 :) in which you can share these findings, so that all these items are tracked in one issue, because most probably, once https://github.com/flutter/flutter/issues/102439 gets implemented, it can cover this suggestion as well.
So I suggest you to follow-up in original issue, share your findings in there.
Closing this in favor of linked issue. If you disagree, write in comments and I'll reopen it.
