### ISSUE TITLE
Can't pod install flutter module in iOS

### ISSUE THREAD

**Issue by suttipongk** [flutter/flutter#118765]
How to install the flutter module on iOS by install_all_flutter_pods with flutter_install_all_ios_pods?
I can't use install_all_flutter_pods(flutter_application_path) inside target 'Runner' do.

Found the error

[!] There are multiple dependencies with different sources for Flutter in Podfile:
Flutter (from Flutter)
Flutter (from ../my_app/.ios/Flutter/engine)

Example : PodFile
----------------------------------------------
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/goinstant/pods-specs-public'

platform :ios, '11.0'
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

flutter_application_path = '../my_app'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

target 'Runner' do
  use_frameworks!
  use_modular_headers!
  pod 'RxSwift', '6.2.0'
  pod 'RxCocoa', '6.2.0'
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

target 'Runner' do
  install_all_flutter_pods(flutter_application_path)
end

post_install do |installer|
  flutter_post_install(installer) if defined?(flutter_post_install)
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)

    target.build_configurations.each do |config|
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= []
----------------------------------------------

How to setup Cocopod for install_all_flutter_pods(flutter_application_path) and flutter_install_all_ios_pods File.dirname(File.realpath(FILE)) within target 'Runner' do?

**Comment by huycozy** [comment]
Hi @suttipongk 
Can you provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this? Also, please provide the output of `flutter doctor -v` as well. Thank you!
