### ISSUE TITLE
DecoratedBox's border doesn't rendered properly

### ISSUE THREAD

**Issue by SuhwanCha** [flutter/flutter#118777]
## Steps to Reproduce

1. Execute `flutter run` on the code sample

**Expected results:**

<img width="453" alt="image" src="https://user-images.githubusercontent.com/16171447/213400595-cd5fd87a-19a1-4593-9490-c384c437e3fe.png">

Child of `DecoratedBox` should not overwrap border.

**Actual results:**

<img width="453" alt="image" src="https://user-images.githubusercontent.com/16171447/213400880-552b5539-43f3-41b5-97ed-e3b1821d2b87.png">

Child of `DecoratedBox` overflow border.

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        title: 'Flutter Demo',
        home: Scaffold(
          appBar: AppBar(
            title: const Text('Flutter Demo Home Page'),
          ),
          body: Center(
            child: DecoratedBox(
              decoration: BoxDecoration(
                color: Colors.blue,
                borderRadius: const BorderRadius.all(Radius.circular(10)),
                border: Border.all(
                  color: Colors.red,
                  width: 10,
                ),
              ),
              child: const SizedBox(
                width: 100,
                height: 100,
                child: Text('Hello'),
              ),
            ),
          ),
        ));
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```
[!] Flutter (Channel master, 3.7.0-23.0.pre.23, on macOS 13.1 22C65 darwin-arm64, locale en-KR)
    • Flutter version 3.7.0-23.0.pre.23 on channel master at /Users/suhwancha/development/GitHub/flutter
    ! Warning: `dart` on your path resolves to /opt/homebrew/Cellar/dart/2.18.5/libexec/bin/dart, which is not inside your current Flutter SDK checkout at /Users/suhwancha/development/GitHub/flutter. Consider adding /Users/suhwancha/development/GitHub/flutter/bin
      to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d53cc4a10f (64 minutes ago), 2023-01-19 00:04:22 -0800
    • Engine revision 40f7f0f099
    • Dart version 3.0.0 (build 3.0.0-136.0.dev)
    • DevTools version 2.20.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/suhwancha/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.74.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.56.0

[✓] Connected device (2 available)
    • iPhone 14 Pro (mobile) • 8901C55B-ACF1-4F3C-A0B6-A09F5A03E555 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-2 (simulator)
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 109.0.5414.87

[✓] HTTP Host Availability
    • All required HTTP hosts are available
```

</details>

**Comment by darshankawar** [comment]
Thanks for the report. I see the same behavior using latest versions upon running the code sample as-is.
I tried to replace `DecoratedBox` with `Ink` widget, with which, we get the expected result:

<img width="179" alt="Screenshot 2023-01-19 at 6 33 51 PM" src="https://user-images.githubusercontent.com/67046386/213451905-fea84449-6d24-4985-96f4-12cc68ff3284.png">

```
child: Ink(
              decoration: BoxDecoration(
                color: Colors.blue,
                borderRadius: const BorderRadius.all(Radius.circular(10)),
                border: Border.all(
                  color: Colors.red,
                  width: 10,
                ),
              ),
              child: const SizedBox(
                width: 100,
                height: 100,
                child: Text('Hello'),
              ),
            ),
```

Another solution that you can try and check (using `DecoratedBox`) is to use `SizedBox.fromSize` and pass `size` as `Size.fromRadius` which also gives you expected result as below:

<img width="136" alt="Screenshot 2023-01-19 at 6 51 52 PM" src="https://user-images.githubusercontent.com/67046386/213453506-e9e81e0c-4599-4247-b972-977348f14a1a.png">

```
body: Center(
            child: DecoratedBox(
              decoration: BoxDecoration(
                color: Colors.blue,
                borderRadius: const BorderRadius.all(Radius.circular(10)),
                border: Border.all(
                  color: Colors.red,
                  width: 10,
                ),
              ),
              child: SizedBox.fromSize(
                size: Size.fromRadius(50),
                child: Padding(
                  padding: const EdgeInsets.all(8),
                  child: Text('Hello'),
                ),
              ),
            ),
          ),
```

**Comment by SuhwanCha** [comment]
@darshankawar It works with `Container` (expected result screenshot is taken from `Container` widget), but I think it should work with in `DecoratedBox`.

**Comment by bleroux** [comment]
From `DecoratedBox` documentation, it is explicitely stated that this is intended and that the solution is to use a `Container`.
"Container insets its child by the widths of the borders; this widget does not."
(FYI, `DecoratedBox` is one of the primitive building blocks for `Container`)

@SuhwanCha Do you have a use case where you can not rely on a Container instead of a DecoratedBox?

**Comment by SuhwanCha** [comment]
@bleroux Nope, I cannot find case that I rely on `DecoreatedBox`, but my linter complaint use decorated box instead becasuse it's const, but it works differently with Container and DecoratedBox.
We might change linter, [use_decorated_box](https://dart-lang.github.io/linter/lints/use_decorated_box.html) option not to be complained when there is `border`

**Comment by darshankawar** [comment]
Thanks for your insights @bleroux and feedback @SuhwanCha 
Based on above response, I am going ahead and closing as WAI. If you disagree, write in comments and I'll reopen it.

**Comment by bleroux** [comment]
> @bleroux Nope, I cannot find the case where I need to `DecoreatedBox` instead of Container, but my linter complaint to use DecoratedBox instead because it's const, but it works differently with Container and DecoratedBox. We might change the linter, [use_decorated_box](https://dart-lang.github.io/linter/lints/use_decorated_box.html) option not to complain when there is `border`

@SuhwanCha
That's a really good point 👍 
It would be great if you can open another issue pointing out to this linter issue (it will be more actionable than updating this existing issue because it is a very different area). Thanks!
