### ISSUE TITLE
[camera] Android 13 crash when initializing camera

### ISSUE THREAD

**Issue by engineer-ece** [flutter/flutter#118787]
I used the Version : #0.10.2, 0.10.1, 0.9.14, 0.9.12, 0.9.19
java.lang.NullPointerException: Attempt to invoke virtual method 'int android.media.EncoderProfiles$VideoProfile.getWidth()' on a null object reference

How to solve it.?

**Comment by danagbemava-nc** [comment]
Hi @engineer-ece, this issue is known and is being tracked in https://github.com/flutter/flutter/issues/109769. 

Kindly follow up in the issue linked above for updates. 

Closing from here as duplicate. 

Thank you
