### ISSUE TITLE
Migrate @FfiNative annotations to @Native

### ISSUE THREAD

**Issue by dcharkes** [flutter/flutter#118794]
We have deprecated `@FfiNative` and introduced `@Native` annotations in Dart.

This has made the Flutter engine build fail:

https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8791539566248935361/+/u/analyze_dart_ui/stdout

```
 info - compositing.dart:37:4 - 'FfiNative' is deprecated and shouldn't be used. Use Native instead. Try replacing the use of the deprecated member with the replacement. - deprecated_member_use
...
```

We can either:

a. Fix forward and land the migration in the engine, or
b. remove the deprecated annotation in the Dart SDK for now, and then do (a) with a bit more peace, or
c. revert the whole change in the Dart SDK (that's probably a bit too much).

**Comment by dcharkes** [comment]
b: https://dart-review.googlesource.com/c/sdk/+/279358

**Comment by dnfield** [comment]
(This seems to be resolved by the linked patch above, please reopen if not)
