### ISSUE TITLE
Cannot `Chrome` give access to skia, to flutter, if `targetPlatform` is web, and browser is chrome, as its also a product of google, also android

### ISSUE THREAD

**Issue by gintominto5329** [flutter/flutter#118757]
thanks

**Comment by darshankawar** [comment]
@gintominto5329 
Your issue is not clear to us as what exactly are you reporting. Please try to use new issue template and fill out requested details so that we'll have enough information to work with and address it accordingly.
Closing for now, due to lack of details and unclear description.
