### ISSUE TITLE
Cannot run "Building a fullstack movie recommendation system" Flutter codelab "backend" on Apple M1

### ISSUE THREAD

**Issue by miquelbeltran** [flutter/flutter#118788]
This is not a Flutter "framework" issue, but a Flutter codelab issue, but I couldn't find a better place for this ticket.

I've got a problem trying to run the codelab code https://github.com/flutter/codelabs/tree/main/tfrs-flutter which is available in https://codelabs.developers.google.com/tfrecommenders-flutter#0

The problem is when running the "backend" part of the codelab.

The error I think is the same as this one: https://github.com/tensorflow/serving/issues/1948 "tensorflow-serving docker container doesn't work on Macs with Apple M1 chips."

## Steps to Reproduce

1. Install Docker in Apple M1 (in my case, MBP 2021 with M1 Pro)
2. Clone `https://github.com/flutter/codelabs`
3. Navigate to `codelabs/tfrs-flutter/finished/backend`
4. Run the codelab command, as explained in Step 7 of the codelab:

```
docker run -t --rm -p 8501:8501 -p 8500:8500 -v "$(pwd)/:/models/" tensorflow/serving --model_config_file=/models/models.config
```

The following error appears: (full log attached later)

```
[libprotobuf FATAL external/com_google_protobuf/src/google/protobuf/generated_message_reflection.cc:2345] CHECK failed: file != nullptr:
terminate called after throwing an instance of 'google::protobuf::FatalException'
  what():  CHECK failed: file != nullptr:
qemu: uncaught target signal 6 (Aborted) - core dumped
/usr/bin/tf_serving_entrypoint.sh: line 3:     8 Aborted                 tensorflow_model_server --port=8500 --rest_api_port=8501 --model_name=${MODEL_NAME} --model_base_path=${MODEL_BASE_PATH}/${MODEL_NAME} "$@"
```

**Expected results:** 

The expected result is the same as explained in the Step 7 of the codelab: https://codelabs.developers.google.com/tfrecommenders-flutter#6

The docker service should run, so the Flutter app in the codelab can connect to it.

**Actual results:** 

Attached the full log below:

<details>
  <summary>Logs</summary>

```
> docker run -t --rm -p 8501:8501 -p 8500:8500 -v "$(pwd)/:/models/" tensorflow/serving --model_config_file=/models/models.config

Unable to find image 'tensorflow/serving:latest' locally
latest: Pulling from tensorflow/serving
a404e5416296: Pull complete
e0811bab055f: Pull complete
70566ae4c4ea: Pull complete
982266225230: Pull complete
cdb50cf1c58b: Pull complete
Digest: sha256:e66c1866bf6596473d56beb3ef77bf7b8b00baa0e1e80c3c428ede31da8ae066
Status: Downloaded newer image for tensorflow/serving:latest
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
[libprotobuf FATAL external/com_google_protobuf/src/google/protobuf/generated_message_reflection.cc:2345] CHECK failed: file != nullptr:
terminate called after throwing an instance of 'google::protobuf::FatalException'
  what():  CHECK failed: file != nullptr:
qemu: uncaught target signal 6 (Aborted) - core dumped
/usr/bin/tf_serving_entrypoint.sh: line 3:     8 Aborted                 tensorflow_model_server --port=8500 --rest_api_port=8501 --model_name=${MODEL_NAME} --model_base_path=${MODEL_BASE_PATH}/${MODEL_NAME} "$@"
```

(doctor output is not relevant for this ticket but including nevertheless)

```
[!] Flutter (Channel beta, 3.7.0-1.4.pre, on macOS 13.1 22C65 darwin-arm64, locale en-DE)
    • Flutter version 3.7.0-1.4.pre on channel beta at /opt/homebrew/Caskroom/flutter/3.0.5/flutter
    ! Warning: `dart` on your path resolves to /opt/homebrew/Cellar/dart/2.18.0/libexec/bin/dart, which is not inside your current Flutter SDK checkout at /opt/homebrew/Caskroom/flutter/3.0.5/flutter. Consider
      adding /opt/homebrew/Caskroom/flutter/3.0.5/flutter/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 686fe913dc (9 days ago), 2023-01-10 16:14:01 -0800
    • Engine revision ac5c83dd5f
    • Dart version 2.19.0 (build 2.19.0-444.4.beta)
    • DevTools version 2.20.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/miquel/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Community Edition (version 2022.2.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 71.2.5
    • Dart plugin version 222.4533

[✓] VS Code (version 1.74.2)
    • VS Code at /Users/miquel/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.56.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.1 22C65 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 109.0.5414.87

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

</details>

**Comment by miquelbeltran** [comment]
FYI @domesticmouse

**Comment by domesticmouse** [comment]
Hey @windmaple any updates on when TensorFlow Serving will support Apple M1?

**Comment by windmaple** [comment]
It is being worked on, but there is no ETA unfortunately. 

https://github.com/tensorflow/serving/issues/1816

**Comment by adarshneeds** [comment]
C:\Users\Adarsh>docker run -t --rm -p 8501:8501 -p 8500:8500 -v "$(pwd)/:/models/" tensorflow/serving --model_config_file=/models/models.config
docker: error during connect: this error may indicate that the docker daemon is not running: Post "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/containers/create": open //./pipe/docker_engine: The system cannot find the file specified.
See 'docker run --help'.

**Comment by domesticmouse** [comment]
> C:\Users\Adarsh>docker run -t --rm -p 8501:8501 -p 8500:8500 -v "$(pwd)/:/models/" tensorflow/serving --model_config_file=/models/models.config
> 
> docker: Error response from daemon: create $(pwd): "$(pwd)" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path.
> 
> See 'docker run --help'.

I expect this codelab was written with the understanding that the developer is using macOS or Linux. Can you try running under WSL?

**Comment by domesticmouse** [comment]
> This issue is assigned to @windmaple but has had no recent status updates. Please consider unassigning this issue if it is not going to be addressed in the near future. This allows people to have a clearer picture of what work is actually planned. Thanks!

@windmaple if this codelab remains in a broken state I'm going to start pushing towards removing this code. Can you either maintain or deprecate for May?

**Comment by windmaple** [comment]
It's not broken. It's just not applicable on Windows/M1 Mac. I'll add some text to the codelab and make it clear.

**Comment by windmaple** [comment]
> C:\Users\Adarsh>docker run -t --rm -p 8501:8501 -p 8500:8500 -v "$(pwd)/:/models/" tensorflow/serving --model_config_file=/models/models.config docker: Error response from daemon: create (pwd):"(pwd)" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path. See 'docker run --help'.

This is a separate issue and should not be discussed in this thread. 

You are using Windows. You need to adapt the docker command to Windows.

**Comment by windmaple** [comment]
I have added text in the codelab to explicitly exclude running the backend on Windows/Apple-silicon Macs. So let's close this.
