### ISSUE TITLE
Android release mode crash: message_snapshot.cc: 576: error: expected: !lib.IsNull()

### ISSUE THREAD

**Issue by marcoheine** [flutter/flutter#118710]
On debug mode everything works, but on release mode the app crash.

I get this error in Google Play Console:

Android 9 (SDK 28)
Samsung XCover 4
Flutter 3.0.5

../../third_party/dart/runtime/vm/message_snapshot.cc: 576: error: expected: !lib.IsNull()
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
pid: 0, tid: 20459 >>> de.xxx.xxx<<<

backtrace:
  #00  pc 0x000000000001cf76  /system/lib/libc.so (abort+58)
  #01  pc 0x0000000000da4857  /data/app/de.xxx.xxx-Q9ZGG4Pd-ePqhoPmNirEOA==/split_config.armeabi_v7a.apk

**Comment by darshankawar** [comment]
Thanks for the report @marcoheine 
Looking at the error log you provided, it seems to be similar to another open issue https://github.com/flutter/flutter/issues/113183 in which you can go through underlying comments and see if they help. If not, I suggest you to follow-up in that issue for further updates.
Closing this as a duplicate. If you disagree, write in comments and I'll reopen it.
