### ISSUE TITLE
Unable to find bundled Java version.

### ISSUE THREAD

**Issue by gh0st-work** [flutter/flutter#118790]
## Steps to Reproduce

1. Install Android Studio (version 2022.1)
2. Run `flutter doctor`
3. `Unable to find bundled Java version.`

Not working on win11, default install/reinstall of Android Studio v2022.1.

Solution that works:

> WINDOWS SOLVED (Android studio 2022.1)
> Go to `C:\Program Files\Android\Android Studio` then copy the content of `jbr` and paste the content into `jre` folder
> run doctor again and problem solved

from [stackoverflow](https://stackoverflow.com/a/75146150)

So need to check also `jre` folder for flutter doctor, I think in new Android Studio version folders are changed.

**Comment by TahaTesser** [comment]
duplicate of https://github.com/flutter/flutter/issues/106674
I will file a fix by tomorrow.
