### ISSUE TITLE
getTextBeforeCursor on inactive InputConnection.   Facing this issue while using  multiple text field

### ISSUE THREAD

**Issue by vijayvaghela72** [flutter/flutter#118772]
I am using one method which is return text field .

I am using same method for multiple text field generate dynamic in screen so facing this issue .

"getTextBeforeCursor on inactive InputConnection" .

I am just doing the or a accessing that value using the index parameter and save the value according to index in various variable ,

Even I am not using controller ,

So how can I solve this issue ? 

getTextBeforeCursor on inactive InputConnection.

Thank you in advance ...!

**Comment by danagbemava-nc** [comment]
This issue is known and is being tracked in https://github.com/flutter/flutter/issues/9471.

Kindly follow up in the issue linked above for updates. 

Closing this as duplicate. 

Thank you
