### ISSUE TITLE
Flutter Headless Tasks

### ISSUE THREAD

**Issue by moti0375** [flutter/flutter#118776]
## Use Case   
  Hi, 
We're looking for a way either in Android or IOS to invoke dart code when the app is totally closed and then initialized from the native side like after Boot Complete or Android Alarm or Worker task.   
     
 Consider the following situation, 
 After a Boot complete event, we want to invoke dart code (probably in an isolate) in which it will fetch data from app servers. 
This, without running or showing the app UI, and still to open a platform channel to send and receive messages from native to dart and vice versa.  

A Specifically in Android, we can define a native Boot Complete BroadcastReceiver or schedule Worker task or Alarm and in there's onReceive we want to invoke functions in the dart side (maybe through a PlatformChannel) 

## Proposal

In ReactNative, there is a solution for that, it called [Headless JS ](https://reactnative.dev/docs/headless-js-android) It allows you to [createReactNativeContextInBackground](https://appdoc.app/artifact/com.github.fangasvsass/react-native/0.53.3/com/facebook/react/ReactInstanceManager.html#createReactContextInBackground--) which will initialize the app index.js and then you can call js functions from the native code. 

   So far we found some background tasks solutions for Flutter but these required to start the app first and do some initializations in main() function. The main function is called only when app starts like when user click on app icon, or opened from notification click. 

   Another example, If the app process is dead and Android AlarmReceiver is invoked (which restarts the app process), then only the native side will be alive while the dart side is still dead, is it possible to have the ability to invoke dart code in this situation? 

Best Regards,
Moti.

**Comment by danagbemava-nc** [comment]
Hi @moti0375, is [workmanager](https://pub.dev/packages/workmanager) what you're looking for?

**Comment by moti0375** [comment]
Hi @danagbemava-nc!
Thank you for this answer, in did, it seems that the work manager solution can work. 
I've followed its code and I've succeeded to implement such thing it in my own plugin but still, this solution has a few drawbacks.

First, the app should be opened at least once for this to work! 
The native side must keep the callbackDispatcher id in a persistence storage in order to access it later if it wakes up in the background.

Calling the the callbackDispatcher from the background is not enough, and I didn't saw how you can pass parameters to it. 
You should then call again to your plugin for doing some dart logic. 

I wish Flutter team can come with well simpler and documented solution for background tasks.

**Comment by danagbemava-nc** [comment]
Hi @moti0375, it turns out there's already an issue requesting such a similar feature in https://github.com/flutter/flutter/issues/32164. 

Kindly follow up in the issue linked above for updates. 

Closing from here as duplicate. 

Thank you
