### ISSUE TITLE
Move Firebase test lab device model/SDK version from recipe to .ci.yaml

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#118736]
Firebase Test Lab had an availablity issue with a particular device model, and recommended we temporarily move to another model until the issue was resolved. https://github.com/flutter/flutter/issues/118708
This required a recipe update: https://flutter-review.git.corp.google.com/c/recipes/+/38144

Move device/SDK version logic out of recipe and into `.ci.yaml` or somewhere else in the repo under test, so they can be updated more easily by engineers without a recipe change.
https://flutter.googlesource.com/recipes/+/refs/heads/main/recipes/firebaselab/firebaselab.py#41

**Comment by jmagman** [comment]
cc @reidbaker

**Comment by godofredoc** [comment]
Fix: https://flutter-review.googlesource.com/c/recipes/+/45182
