### ISSUE TITLE
Proposal to add `margin` to MaterialBanner constructor

### ISSUE THREAD

**Issue by HELL-i** [flutter/flutter#118704]
## Use case

I would like to put an outer margin on the material banner.

```
Line 296 - 297:
    Widget materialBanner = Container(
      margin: EdgeInsets.only(bottom: elevation > 0 ? 10.0 : 0.0),

For example:
 const MaterialBanner({
    super.key,
    required this.content,
    this.contentTextStyle,
    required this.actions,
    this.elevation,
--> this.margin
```

## Proposal
The goal is to get the Material banner with outer margin to get the design like this:
![Screenshot 2023-01-18 at 17 01 19](https://user-images.githubusercontent.com/122999920/213225311-afcee733-3df0-4869-bf38-3c88fefd0990.png)

**Comment by darshankawar** [comment]
@HELL-i 
There's already a `margin` property as I see here:

https://github.com/flutter/flutter/blob/d53cc4a10f267cf054763d22e4390bcbff57068e/packages/flutter/lib/src/material/banner.dart#L340

Can you try to make use of that and see if it helps in your case ?

**Comment by HELL-i** [comment]
@darshankawar 
THX, but i want to set a margin around the material banner and not only at the bottom this can done over the elevation. 
The constructor not including the margin to override it at line 340.

https://github.com/flutter/flutter/blob/d53cc4a10f267cf054763d22e4390bcbff57068e/packages/flutter/lib/src/material/banner.dart#L97

**Comment by darshankawar** [comment]
I see, thanks for the insight. I'll treat this as a proposal to add `margin` to `MaterialBanner` widget.

**Comment by HELL-i** [comment]
THX

**Comment by hasnentai** [comment]
@HansMuller @darshankawar I would like to work on this issue

**Comment by HELL-i** [comment]
@hasnentai @HansMuller 
Here is a possible solution: https://github.com/flutter/flutter/compare/master...HELL-i:flutter:master

**Comment by hasnentai** [comment]
@HELL-i Cool I think this looks fine. Thanks for the update

**Comment by HELL-i** [comment]
@hasnentai When i have time i will add widget tests and then i will create the PR.

**Comment by hasnentai** [comment]
@HELL-i  I added the changes along with Widget Test. Additionally, I also added a margin in `withAnimation` method and Raised the PR https://github.com/flutter/flutter/pull/119005
cc: @Piinks @shihaohong
