### ISSUE TITLE
[Impeller] Vulkan: Maintain a pass bindings cache to reduce API traffic.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#118727]
Similar to the [Metal PassBindingsCache](https://github.com/flutter/engine/blob/fb80e863edfd1ef9610db791b47989c17eb467ff/impeller/renderer/backend/metal/render_pass_mtl.mm#L188), a mechanism must be present in Vulkan to reduce redundant API calls. This is relevant with some drivers for performance. Also, this greatly improves the readability of GPU trace captures.

**Comment by gaaclarke** [comment]
It looks like vulkan operates a bit different than metal, where in metal you are communicating to the API for each binding you make, but in vulkan you build up a datastructure (`vk::WriteDescriptorSet`) and pass it to the API.  So, it's not clear to me if the issue `PassBindingsCache` is solving for metal is an issue we have to solve in vulkan.  If you deduplicate a texture binding for example, it won't result in less binding calls to the API.

I recommend holding off on this until there is more evidence that it will improve performance or debugging.  (Maybe that exists but just isn't included in this issue?).  We may not even need a cache, but just use something like `std::unique` when iterating over the `impeller::Bindings` to create the descriptors.

## metal

https://github.com/flutter/engine/blob/8edd3c000a390234d0b09b2965c2b2a6a0315daa/impeller/renderer/backend/metal/render_pass_mtl.mm#L272
```objc++
  bool SetTexture(ShaderStage stage, uint64_t index, id<MTLTexture> texture) {
    auto& texture_map = textures_[stage];
    auto found = texture_map.find(index);
    if (found != texture_map.end() && found->second == texture) {
      // Already bound.
      return true;
    }
    texture_map[index] = texture;
    switch (stage) {
      case ShaderStage::kVertex:
        [encoder_ setVertexTexture:texture atIndex:index];
        return true;
      case ShaderStage::kFragment:
        [encoder_ setFragmentTexture:texture atIndex:index];
        return true;
      default:
        VALIDATION_LOG << "Cannot bind buffer to unknown shader stage.";
        return false;
    }
    return false;
  }
```

## vulkan

https://github.com/flutter/engine/blob/main/impeller/renderer/backend/vulkan/render_pass_vk.cc#L331
```c++
  std::vector<vk::WriteDescriptorSet> writes;
  auto bind_images = [&encoder,  //
                      &images,   //
                      &writes,   //
                      &desc_set  //
  ](const Bindings& bindings) -> bool {
    for (const auto& [index, sampler_handle] : bindings.samplers) {
      if (bindings.textures.find(index) == bindings.textures.end()) {
        return false;
      }

      auto texture = bindings.textures.at(index).resource;
      const auto& texture_vk = TextureVK::Cast(*texture);
      const SamplerVK& sampler = SamplerVK::Cast(*sampler_handle.resource);

      if (!encoder.Track(texture) ||
          !encoder.Track(sampler.GetSharedSampler())) {
        return false;
      }

      const SampledImageSlot& slot = bindings.sampled_images.at(index);

      vk::DescriptorImageInfo image_info;
      image_info.imageLayout = vk::ImageLayout::eShaderReadOnlyOptimal;
      image_info.sampler = sampler.GetSampler();
      image_info.imageView = texture_vk.GetImageView();

      vk::WriteDescriptorSet write_set;
      write_set.dstSet = desc_set.value();
      write_set.dstBinding = slot.binding;
      write_set.descriptorCount = 1u;
      write_set.descriptorType = vk::DescriptorType::eCombinedImageSampler;
      write_set.pImageInfo = &(images[slot.binding] = image_info);

      writes.push_back(write_set);
    }
```

**Comment by chinmaygarde** [comment]
> Maybe that exists but just isn't included in this issue...

Yeah, the descriptor set updates take care of most of this. But traces are still significantly more noisy with Vulkan (compared to Metal) because of redundant pipeline binds, stencil/scissor/scissor-reference setters. Makes the frame capture experience way worse.

Even with Metal, the bindings cache didn't yield massive performance improvements. It made the API insights Xcode warning shut up and its easier to read traces.

It could help performance on some drivers. But yeah, this is more a trace readers QOL improvement more than anything else.

I'm removing it from the milestone.

**Comment by gaaclarke** [comment]
@chinmaygarde so after https://github.com/flutter/engine/pull/42793 lands we'll be caching everything but the descriptor sets and the vertex buffers.

I avoided these for now since the descriptor sets are pretty complicated data structures.  I'm not sure how likely these are to be the same across calls.  For the vertex buffers I was afraid I'd wouldn't be able to check the equality easily on them if they are host visible.

**Comment by jonahwilliams** [comment]
I don't think we can/should do this - beyond simple checks like not calling setPipeline/viewport/scissor (the later of which aren't useful to cache as we're not using them). Most of the encoding workload can't be avoided as we must create/update descriptor sets per-draw. There are ways to structure our shaders so this isn't the case - for example by binding commonly shared data in different structs that are in another descriptor set.

But this wouldn't be compatible with the Metal/GLES renderers, and may not buy us much at all.
