### ISSUE TITLE
Firebase Testlab Tests taking too long on framework presubmits

### ISSUE THREAD

**Issue by iskakaushik** [flutter/flutter#118708]
I'm keeping an eye on the engine->fw roll pr: https://github.com/flutter/flutter/pull/118686. Most of the pending tests are firebase tests, that are taking > 1hr, previous runs have finished in < 35 mins on average.

![image](https://user-images.githubusercontent.com/1006071/213240078-310205d2-a0ea-41d1-8b56-65938941fa1d.png)

![image](https://user-images.githubusercontent.com/1006071/213240120-b9bbffdd-841a-40a1-8ce7-78ec91ab4c91.png)

link: https://ci.chromium.org/p/flutter/builders/try/Linux%20firebase_release_smoke_test

**Comment by jmagman** [comment]
The Nexus run is pretty fast:
<img width="320" alt="Screenshot 2023-01-18 at 11 03 57 AM" src="https://user-images.githubusercontent.com/682784/213271262-eb8f59be-7ce5-4358-bef5-d58e03b8d790.png">
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8791614617499498721/+/u/test_execution/gcloud_firebase__2_/execution_details

But the Pixel 3/5/Motorola XT1650 run is really slow:
<img width="322" alt="Screenshot 2023-01-18 at 11 05 47 AM" src="https://user-images.githubusercontent.com/682784/213271621-b0a22b80-90b3-4429-a832-6fab41e8fc55.png">

https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8791614617499498721/+/u/test_execution/gcloud_firebase/execution_details

One device was pending for 23 minutes, maybe a capacity issue with one of those models?
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8791614617499498721/+/u/test_execution/gcloud_firebase/stdout

**Comment by jmagman** [comment]
@sealesj infra on-call--is there some way to see if this is a Firebase Test Lab capacity issue?  There's nothing listed at https://status.firebase.google.com.   And if so, which model, and is it temporary or does a different model/SDK need to be picked?

**Comment by zanderso** [comment]
This is blocking rolls, and the engine roll is almost 30 commits behind, so I will raise this to a P0.

**Comment by godofredoc** [comment]
Issue has been mitigated, moving to P3 to land the final fix.

**Comment by ricardoamador** [comment]
@godofredoc is there a fix for this? The last comment suggests as much. Just wanted to follow up.

**Comment by godofredoc** [comment]
No, firebaselab is still working on the fix. I believe the best course of action is to select a new device that already has enough capacity in firebaselab

**Comment by ricardoamador** [comment]
Ah okay so this is reliant on the firebase team?

**Comment by godofredoc** [comment]
That is correct!

**Comment by keyonghan** [comment]
Obsolete. The test has been running without a issue: https://ci.chromium.org/p/flutter/builders/try/Linux%20firebase_release_smoke_test?limit=100
