### ISSUE TITLE
[Mac] - IME deltas get into endless loop

### ISSUE THREAD

**Issue by matthew-carroll** [flutter/flutter#118834]
There are four types of IME deltas: insertion, replacement, deletion, non-text update.

The non-text update informs an app that a text selection or composing region was changed by the user, without any content changes, and the app should update accordingly.

On Mac (and maybe other platforms), when the app sends an update to the IME, the IME responds back with a `TextEditingDeltaNonTextUpdate`, which repeats the selection and composing region that the app just sent to the IME. This creates a couple of problems.

First, if the app developer doesn't check whether the new IME value is different from the existing local `TextEditingValue`, the app developer might apply the change and send it right back to the IME, which yields an endless loop. The IME notifies the app, the app notifies the IME, the IME notifies the app, etc. And yet, it's the same value every time. This problem can be avoided if the developer knows what to look for, but it seems like an unnecessary footgun.

Second, and the bigger issue, is that IME client changes that happen quickly can cause an unavoidable endless loop with the IME. I'll illustrate with an example. Let's assume the following text field values as the user tags somebody in a text field.

    I'm tagging @M|
    I'm tagging @Matt|
    I'm tagging @Matt |

We type "I'm tagging @M", then we select a suggested name, which results in "I'm tagging @Matt". That part works fine. But as soon as the tag name is added, we have our code immediately insert a space " ". This is where the problem comes in. We'll end up in an IME loop like the following:

    I'm tagging @Matt|
    I'm tagging @Matt |
    I'm tagging @Matt|
    I'm tagging @Matt |
    I'm tagging @Matt|
    I'm tagging @Matt |

First we tell the IME that the value is "I'm tagging @Matt|". Then we immediately tell the IME that the value is "I'm tagging @Matt |". Then the IME sends us a `TextEditingDeltaNonTextUpdate` telling us the caret should be positioned as "I'm tagging @Matt|". This is different than our app-side state, so we send the value back to the IME "I'm tagging @Matt|". Then the IME catches up with our earlier message and tells us to move the caret to "I'm tagging @Matt |". So we make that change. And then this pattern continues.

It's unclear how we're supposed to differentiate IME deltas that essentially "confirm" a value we've already sent, versus IME deltas that want us to change the selection in response to user actions.

**Comment by matthew-carroll** [comment]
CC @justinmc @Renzo-Olivares

**Comment by matthew-carroll** [comment]
Looks like Angelo beat me to the punch on this issue. This is a duplicate of https://github.com/flutter/flutter/issues/118759

@justinmc @Renzo-Olivares please do take a look at that other issue. It's creating quite a few bugs across `SuperEditor` and `SuperTextField` for multiple customers.

**Comment by justinmc** [comment]
Will do, thanks for closing and for positing your details on that issue.
