### ISSUE TITLE
Flutter 3.4.0-XX.X.pre `libapp.so` snapshots breaks prior Dart VM initialization convention

### ISSUE THREAD

**Issue by perks** [flutter/flutter#118825]
Prior to this version analysis tools compiled as part of the Dart SDK for Flutter applications using `ProductSIMARM64c` were able to initialize a barebones Dart VM to load Flutter `libapp.so` snapshots and instrument them.

Now when running these tools it seems that something has changed in the way that Flutter is generating the Dart SDK VM for its engine

The following error appears:

```
VM initialization failed: Snapshot not compatible with the current VM configuration: the snapshot requires 'product no-code_comments no-dwarf_stack_traces_mode no-lazy_dispatchers dedup_instructions no-asserts arm64 android compressed-pointers null-safety' 
but the VM has 'product no-code_comments no-dwarf_stack_traces_mode no-lazy_dispatchers dedup_instructions no-asserts arm64 linux compressed-pointers null-safety'
```

With the following being the difference

(Encountered)
...  no-asserts arm64 [**android**] compressed-pointers null-safety

vs 

(Expected)
... no-asserts arm64 [**linux**] compressed-pointers null-safety

Was just wondering if there was any way to see what changes to the engine might have caused this to see if there is any remediation I can upstream on the Dart SDK end.

For reproduction purposes:

The tool in question within the Dart SDK can be found at https://github.com/dart-lang/sdk/blob/main/runtime/bin/analyze_snapshot.cc

and is compiled via

`./tools/build.py -mproduct --arch=simarm64c analyze_snapshot`

and run

`./out/ProductSIMARM64C/analyze_snapshot --pp /path/to/libapp.so`

Thank you!

**Comment by perks** [comment]
An update:

I was digging around and found the problem:
https://github.com/dart-lang/sdk/commit/3344e064168f0e51a1f127aad823fbc6a66d6f72

Essentially this means that since you cannot specify the `--os=android` flag when cross compiling simulated architectures this probably requires a change in the dart-sdk project rather than here.

Incoming fix will be landed in DartSDK soon, will update this issue as progress is made

**Comment by darshankawar** [comment]
Thanks for the report and finding the root-cause @perks 
The flutter version you mentioned in issue title is `3.4.0` which is older than current master and beta versions which are already on `3.7.0-24.0.pre.21` (master).



> Incoming fix will be landed in DartSDK soon, will update this issue as progress is made

This seems to have been fixed already, so is there a way for you to upgrade to latest master and confirm the fix ?

**Comment by perks** [comment]
Hey @darshankawar 

I don't think any changes have been made (or need to be made) on Flutter's end?

https://dart-review.googlesource.com/c/sdk/+/279391

Here is the patch to the Dart SDK that will fix the problem on that end, do not know if  anything else is needed.

`3.7.0-24.0.pre.21` shows the same behavior of having an accurate `os` string in the version string, which is ultimately correct.

Let me know if there is anything else otherwise can close this issue.

Thanks!

**Comment by darshankawar** [comment]
Thanks for the update. Yes, I think we can close from here as the issue looks more related to dart than Flutter, so will go ahead and close it. Thanks for reporting and sharing updates.
