### ISSUE TITLE
Support specification of 'share intent' in share plugin

### ISSUE THREAD

**Issue by xster** [flutter/flutter#11886]
Annotations that helps Android better suggest share targets

https://developer.android.com/about/versions/oreo/android-8.0.html#smsh

**Comment by mit-mit** [comment]
@xster is this not https://pub.dartlang.org/packages/android_intent ?

**Comment by xster** [comment]
Not quite I think. That plugin is for starting intents. This feature request is for adding metadata to share actions to better identify share recipients. The key part is the usage of the `EXTRA_CONTENT_ANNOTATIONS` flag.

**Comment by iapicca** [comment]
Hi @xster  is this issue still meant to be open?

**Comment by xster** [comment]
It is. It's still not filled in https://github.com/flutter/plugins/tree/master/packages/share/android/src/main/java/io/flutter/plugins/share

**Comment by stuartmorgan** [comment]
Closing, as share is now deprecated in favor of [share_plus](https://pub.dev/packages/share_plus).
