### ISSUE TITLE
Remove option to pass unsound null safety flag in flutter build/run commands

### ISSUE THREAD

**Issue by a-siva** [flutter/flutter#118810]
Starting in Dart3.beta, the Dart SDK will not support the option to pass in `--no-sound-null-safety flag`, Flutter would also have to change to not support this option when building/running Flutter apps

Please see https://github.com/dart-lang/sdk/issues/50348 for more details regarding the Dart SDK change.

**Comment by a-siva** [comment]
//cc @zanderso

**Comment by zanderso** [comment]
@christopherfujino

**Comment by a-siva** [comment]
Per discussion this morning in the Dart VM weekly sync

- it would be prefarable to remove the flag as opposed to hiding it in the help message
- when the change to remove this flag is made a corresponding change needs to be made which adds the flag in the internal version of the tool

**Comment by christopherfujino** [comment]
From https://github.com/flutter/flutter/issues/120122

When the support for the --no-sound-null-safety flag gets completely removed we should also remove --null-assertions because it only has meaning when running without sound null safety. It should get cleaned up for both the dev and production code paths in the flutter CLI tools.

See: https://github.com/dart-lang/sdk/issues/50711

**Comment by nshahan** [comment]
@christopherfujino 
There is one more flag we need to look at for the JS compilers (production and development). We have a flag 
`--native-null-assertions` to enforce null safety on browser APIs that return values back to the Dart program.

Going forward, we would like this enabled by default with the ability to disable it. 

Disabling is intended as a temporary workaround for cases where browser APIs change or are inconsistent and the Dart SDK is expecting a non-nullable type but a browser does return null. If this situation is encountered by a user, disabling the soundness checks would be necessary until an update to the Dart SDK can be made and the user would need to update their code to handle the null value.

There is an additional note for dart2js (web production) compiles where optimization modes will effectively override the state of this flag. If Flutter tools already enforces an optimization level `-o3` or above on production compiles without letting the user configure the option then the flag has no purpose. 

See discussion: https://github.com/dart-lang/sdk/issues/50711

**Comment by a-siva** [comment]
Flutter downloads Dart SDKs these days rather than building their own? Would Dart SDKS building without support for this option effect Flutter in anyway?

**Comment by nshahan** [comment]
Yes this flag is still relevant for both JavaScript workflows. It gets passed when compiling to from Dart to JavaScript (dart2js) and at runtime in the JavaScript bootstrapping before calling the main method (ddc).

**Comment by a-siva** [comment]
> Yes the `--native-null-assertions` flag is still relevant for both JavaScript workflows. It gets passed when compiling to from Dart to JavaScript (dart2js) and at runtime in the JavaScript bootstrapping before calling the main method (ddc).

I was referring to the `--no-sound-null-safety-flag` which the VM is planning on removing completely

**Comment by nshahan** [comment]
@christopherfujino 
Thanks! Since Flutter builds already enable by default we shouldn't expect to see any behavioral differences when we flip dart2js to enable by default as well.

**Comment by christopherfujino** [comment]
Re-opening as the PR was reverted

**Comment by christopherfujino** [comment]
This was fixed in the re-land https://github.com/flutter/flutter/pull/123031

**Comment by christopherfujino** [comment]
re-land was reverted, third attempt is https://github.com/flutter/flutter/pull/123297

**Comment by christopherfujino** [comment]
This was reverted again, currently working on a re-land
