### ISSUE TITLE
[webview-flutter] [Android] In release build onPageStarted and onPageFinished are not called when loading a page

### ISSUE THREAD

**Issue by koltai75** [flutter/flutter#118876]
## Steps to Reproduce

1.  Create a new, empty Flutter application.
2. Add the `webview_flutter` package (v4.0.1) with `flutter pub add webview_flutter`.
3. In `AndroidManifest.xml`, add `<uses-permission android:name="android.permission.INTERNET"/>` to the `manifest` part.
4. In `android/app/build.gradle`, set `compileSdkVersion` to 32 and `minSdkVersion` to 19 as it is required by the webview package.
5. Replace the contents of `main.dart` with the code sample provided below.
6. Instead of the steps above, you can also  clone this GitHub repo which I prepared following these steps: (https://github.com/koltai75/webview_bug).
7. Connect a physical Android device (I tested with Samsung Galaxy A12 SM-A127F/DSN, Android version 13) or start an emulator (I used Pixel 4 Android API 34 arm64).
8. For test **case A**, start the test application in debug mode with `flutter run` or start debugging from VS Code. After the webview loads the first page (Google), use the refresh button in the bottom right corner multiple times, it will load another page (Facebook). Repeat pressing the button multiple times.
9. For test **case B**, run the application in release mode: either with `flutter run --release` or build and apk with `flutter build apk` and install it to the phone.

**Expected results:**

The code contains `print` statements and displays snackbars on both `onPageStarted` and `onPageFinished` functions, which are set with `setNavigationDelegate` when initalizing the webview. On every page load started and finished these should display the current URL in the console and also a snackbar in the application. There is also a counter which increments on every message for easier tracking.

The expected result is when the button is repeatedly pressed, you always see that `onPageStarted` is called for the current site, the site is loaded and some time later, `onPageFinished` is called.

**Actual results:**

In debug mode (case A), everything works as expected. But in release mode (case B), after a few presses on the button, the `onPageStarted` and `onPageFinished` functions are not called anymore, the snackbars are not displayed, the `print` statements are not executed. Usually 3-4 messages are shown and then it stops. The sites are loaded in release build as well.

<details>
<summary>Code sample</summary>

```dart
// ignore_for_file: avoid_print

import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) => const MaterialApp(
        title: 'webview test',
        home: MyWebView(),
      );
}

class MyWebView extends StatefulWidget {
  const MyWebView({super.key});

  @override
  State<MyWebView> createState() => _MyWebViewState();
}

class _MyWebViewState extends State<MyWebView> {
  late final WebViewController _webViewController;
  final _uris = [Uri.https('google.com'), Uri.https('facebook.com')];
  var _whichUri = 0;
  var _counter = 1;

  @override
  void initState() {
    super.initState();
    _webViewController = WebViewController()
      ..setJavaScriptMode(JavaScriptMode.unrestricted)
      ..setNavigationDelegate(NavigationDelegate(onPageStarted: (url) {
        ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(content: Text('$_counter: onPageStarted: $url')));
        print('$_counter: onPageStarted: $url');
        _counter++;
      }, onPageFinished: (url) {
        ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(content: Text('$_counter: onPageFinished: $url')));
        print('$_counter: onPageFinished: $url');
        _counter++;
      }))
      ..loadRequest(_uris[_whichUri]);
  }

  @override
  Widget build(BuildContext context) => Scaffold(
        appBar: AppBar(
          title: const Text('webview test'),
        ),
        body: WebViewWidget(controller: _webViewController),
        floatingActionButton: FloatingActionButton(
          child: const Icon(Icons.sync),
          onPressed: () async {
            _whichUri = 1 - _whichUri;
            await _webViewController.clearCache();
            _webViewController.loadRequest(_uris[_whichUri]);
          },
        ),
      );
}
```

</details>

<details>
  <summary>Logs</summary>

Two interesting things appear in the logs. First, this is shown many times in debug run:

```
E/FrameEvents(23056): updateAcquireFence: Did not find frame.
```

And sometimes, not very often, there is an exception:
```
PlatformException (PlatformException(NullPointerException, java.lang.NullPointerException: Attempt to invoke virtual method 'void android.webkit.WebView.loadUrl(java.lang.String, java.util.Map)' on a null object reference, Cause: null, Stacktrace: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.webkit.WebView.loadUrl(java.lang.String, java.util.Map)' on a null object reference
	at io.flutter.plugins.webviewflutter.WebViewHostApiImpl.loadUrl(WebViewHostApiImpl.java:280)
	at io.flutter.plugins.webviewflutter.GeneratedAndroidWebView$WebViewHostApi$-CC.lambda$setup$3(GeneratedAndroidWebView.java:749)
	at io.flutter.plugins.webviewflutter.GeneratedAndroidWebView$WebViewHostApi$$ExternalSyntheticLambda10.onMessage(Unknown Source:2)
	at io.flutter.plugin.common.BasicMessageChannel$IncomingMessageHandler.onMessage(BasicMessageChannel.java:217)
	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8669)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
, null))
```

`flutter analyze` output:

```
Analyzing webview_bug...                                                
No issues found! (ran in 1.1s)
```

`flutter doctor` output:

```
[✓] Flutter (Channel stable, 3.3.10, on macOS 13.1 22C65 darwin-arm, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.74.3)
[✓] Connected device (2 available)
[✓] HTTP Host Availability
```

</details>

**Comment by exaby73** [comment]
Hello @koltai75. I believe you're hitting https://github.com/flutter/flutter/issues/108801. Could you confirm if this is the issue you're experiencing?

**Comment by koltai75** [comment]
Hi @exaby73 , thank you for your comment. Indeed, it seems to be a very similar issue. 

I read the thread and examined other issues linked as well.

Interestingly enough the solution mentioned [here](https://github.com/flutter/flutter/issues/108801#issuecomment-1367490174) seems to help . I don't see why it makes a difference, but as a matter of fact, declaring `NavigationDelegate` separately before creating the `WebViewController` results in the expected behaviour. But other comments there suggest that this is not a 100% solution.

I also find it strange that these methods:  `setJavaScriptMode`,  `setNavigationDelegate` and `loadRequest` are all have a future return type but I haven't seen in the documentations or any other place that they should be awaited.

**Comment by koltai75** [comment]
@exaby73 I made some further tests, and combining the workaround suggested [here](https://github.com/flutter/flutter/issues/108801#issuecomment-1367490174) with using `await` and calling every `WebViewController` initialization function separately seems to solve the problem.

I created a future function to initialize the `WebViewController` and use a `FutureBuilder` calling this function that builds the `WebViewWidget`:
```
  Future<WebViewController> _initWebView() async {
    _webViewController = WebViewController();

    final navigationDelegate = NavigationDelegate(
      onProgress: _onProgress,
      onPageStarted: _onPageStarted,
      onPageFinished: _onPageFinished,
      onWebResourceError: _onWebResourceError,
    );

    await _webViewController.setJavaScriptMode(JavaScriptMode.unrestricted);
    await _webViewController.addJavaScriptChannel('MyChannel',
        onMessageReceived: _onMessageReceived);
    await _webViewController.setNavigationDelegate(navigationDelegate);

    await WebViewCookieManager().setCookie(
      ...
    );

    await _webViewController
          .loadRequest(...);
    }

    return Future.value(_webViewController);
  }
```

**Comment by exaby73** [comment]
Since this issue is similar to https://github.com/flutter/flutter/issues/108801, I am closing it as a duplicate. You may post your findings in the original issue, as it might help someone debug it :)

**Comment by koltai75** [comment]
> Since this issue is similar to #108801, I am closing it as a duplicate. You may post your findings in the original issue, as it might help someone debug it :)

Thank you, I added a [comment there](https://github.com/flutter/flutter/issues/108801#issuecomment-1400024205).
