### ISSUE TITLE
[CP] [Impeller] Account for the transform in DLVerticesGeometry coverage

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#118850]
### issue_link

N/A

### Commit Hash

https://github.com/flutter/engine/commit/dd8c259bb4ea92e2382616304dd7028293f5f620

### Target

stable

### pr_link

https://github.com/flutter/engine/pull/39014

### Impacted Users

Impeller users

### Impact Description

drawVertices calls under Impeller do not properly account for transforms.

### Workaround

There is no workaround.

### Risk

low

### Test Coverage

yes

### Validation Steps

The drawVertices demo in the gallery works with Impeller enabled.

**Comment by CaseyHillers** [comment]
This was shipped in the 3.7 stable
