### ISSUE TITLE
High overall system load using Intellij Idea on Mac

### ISSUE THREAD

**Issue by megamattron** [flutter/flutter#11881]
## Steps to Reproduce

When Intellij Idea is open and a Flutter project is loaded I experience high overall system load (Macbook Pro running OS 10.12.6). What's odd is that I'm finding it hard to track down the offending process. The only thing I can see is an "instruments -s devices" periodically spiking to 100% CPU, but I'm not totally sure if that's the cause. As it is my laptop's fans run at full speed continuously.

If I quit Idea then system load seems to return to normal. Anyone else experiencing this?

cc @cbracken as requested in chat.

## Flutter Doctor

[✓] Flutter (on Mac OS X 10.12.6 16G29, locale en-US, channel alpha)
    • Flutter at /Users/matt/code/flutter/flutter
    • Framework revision b156a0f054 (3 weeks ago), 2017-08-11 22:01:40 -0700
    • Engine revision fef7d827d6
    • Tools Dart version 1.25.0-dev.9.0

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at /Users/matt/code/android/android
    • Platform android-25, build-tools 25.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.3.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3.3, Build version 8E3004b
    • ios-deploy 1.9.1
    • CocoaPods version 1.3.1

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Ultimate Edition (version 2017.2.2)
    • Flutter plugin version 16.0
    • Dart plugin version 172.3757.55

[✓] Connected devices
    • Pixel • FA6A10319557 • android-arm • Android 7.1.2 (API 25)

**Comment by cbracken** [comment]
Thanks for reporting!

We've definitely seen cases where running `instruments -s devices`, especially while a simulator is up and running, causes high resource usage on the host OS, in particular, when an iOS simulator is running. Closing (or restarting) the simulator seems to fix this in most cases.

libimobiledevice includes similar functionality, which gives us the same information, but with a lighter CPU load. I've put together a patch that migrates us over.

**Comment by cbracken** [comment]
This should now be fixed on master. Please re-open if you continue to see this after syncing to latest.

**Comment by megamattron** [comment]
Great news! Sorry for the newbie question, but do people usually develop based on master, or off one of the official releases? I'd love to have this fixed but wasn't sure if I'd be signing up for instability. Thanks!

**Comment by megamattron** [comment]
Forget about my question, I found the channels page with recommendations. For anyone else who finds this, go here: https://flutter.io/upgrading/

Thanks again for the fix.

**Comment by cbracken** [comment]
@megamattron Sorry for the delay in getting back to you -- and thanks for posting the link to the upgrading doc with channel recommendations! That doc covers the state-of-the-art in Flutter channel selection :-)
