### ISSUE TITLE
[Impeller] Enable Vulkan Validation Layers on CI bot

### ISSUE THREAD

**Issue by iskakaushik** [flutter/flutter#118814]
This is important to catch error earlier in the pipeline, specifically for bots that run these tests: https://github.com/flutter/engine/blob/main/ci/builders/linux_host_engine.json#L53

See logs: https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20Production%20Engine%20Drone/37335/overview

**Comment by gaaclarke** [comment]
We have this turned on for the mac execution now, it was turned don in eed12f36f5956a37fb4ba13f1b670a5d41c37edb

Validation errors aren't registered as failed tests though right now.  Maybe we should introduce that.

**Comment by gaaclarke** [comment]
I was looking at the code again yesterday and validation errors should crash conditionally because of debug_report_vk.cc.

**Comment by jonahwilliams** [comment]
Closing this as fixed
