### ISSUE TITLE
[go_router] in redirection, How to cancel routing

### ISSUE THREAD

**Issue by byungjuJin** [flutter/flutter#118885]
in redirection, How to cancel routing?
If user is not premium user, Try to not allow to move to target routing.
For example, like below.
```
redirect: (BuildContext context, GoRouterState state) {
  if (AuthState.of(context).isNotPremiumUser) {
   // cancel routing
  } else {
    return null;
  }   
},
```

In other framework Angular, it has router guard
"return true" means like "return null" in Go_router,
"return false" means cancel routing and leave so do not move.

How to do "return false" with go_router?

**Comment by darshankawar** [comment]
@byungjuJin 
I think [this](https://github.com/flutter/flutter/issues/102408) open proposal will cover your use case as well, so I suggest you to follow-up in that issue for further updates.
Meantime, for a workaround, you may ask this question on support channels like StackOverflow.
Closing this issue from here. If you disagree, write in comments and I'll reopen it.
