### ISSUE TITLE
Fix to jazzy install appears needed in 3.7 recipes

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#118805]
https://github.com/flutter/flutter/issues/118464 is still affecting the engine release branch, preventing cherry-picks, and potentially also blocking creating the release bits? Marking P0 in case this affects the release.

See: https://github.com/flutter/engine/pull/39002

cc @godofredoc

**Comment by zanderso** [comment]
cc @itsjustkevin

**Comment by zanderso** [comment]
Also affecting https://github.com/flutter/engine/pull/38988

**Comment by godofredoc** [comment]
Duplicate of https://github.com/flutter/flutter/issues/118729

**Comment by godofredoc** [comment]
Fixed, please re-run any failing tests on PRs not included in the bug. I already ran the PRs included here.
