### ISSUE TITLE
Instagram IconData value

### ISSUE THREAD

**Issue by flavorsavvor** [flutter/flutter#118855]
## Use case

I am using the Material icons for social media buttons and I noticed that there isn't an icon for Instagram. I am working around it for now, but this would have been much more useful to have this available like all the other social media icons.

## Proposal

Would love to see this added, in a future update.

**Comment by danagbemava-nc** [comment]
Hi @flavorsavvor, the icons in the material package are a mirror of what is available on https://fonts.google.com/icons?icon.set=Material+Icons. 

Given that this icon is currently unavailable on the material icons site, it cannot be added to the project. You can request that they add it to the material icons on their GitHub, but it seems like there are some legalities involved. See https://github.com/google/material-design-icons/issues?q=is:issue+sort:updated-desc+instagram+is:closed

I'll be closing this for now. 

Thank you
