### ISSUE TITLE
Unable to simplify default flutter test configuration

### ISSUE THREAD

**Issue by JaredEzz** [flutter/flutter#118823]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce

_Please tell us what you were doing and what went wrong_

It's unfortunate that the default configuration in IntelliJ for running a flutter test is to run it as `...\flutter\bin\flutter.bat --no-color test --machine --start-paused [args] test\some_test.dart`. Because I'm running tests for Flutter Web and have html imported in various places, I have to add the `--platform chrome` arg which does not work with this default config. Running just plain `flutter test --platform chrome test\some_test.dart` works great though from the command line. Would love it if there were options to simplify the default configuration - is that possible?

## Version info

Please paste the output of running `flutter doctor -v` here (available from the command
line or from `Tools > Flutter > Flutter Doctor`). It will provide the version of the
Flutter framework as well as of the IntelliJ plugin.

[√] Flutter (Channel stable, 3.3.8, on Microsoft Windows [Version 10.0.22622.575], locale en-US)
    • Flutter version 3.3.8 on channel stable at C:\Users\jared\dev\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 52b3dc25f6 (7 weeks ago), 2022-11-09 12:09:26 +0800
    • Engine revision 857bd6b74c
    • Dart version 2.18.4
    • DevTools version 2.15.0

[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at C:\Users\jared\AppData\Local\Android\sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • Java binary at: C:\Users\jared\.jdks\corretto-11.0.14\bin\java.exe
    • Java version OpenJDK Runtime Environment Corretto-11.0.14.9.1 (build 11.0.14+9-LTS)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] IntelliJ IDEA Ultimate Edition (version 2022.2)
    • IntelliJ at C:\Users\jared\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\222.4345.14
    • Flutter plugin version 71.2.6
    • Dart plugin version 223.7571.203

[√] IntelliJ IDEA Ultimate Edition (version 2022.3)
    • IntelliJ at C:\Users\jared\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\223.7571.182
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin version 222.4345.14

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22622.575]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 108.0.5359.125
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 108.0.1462.46

[√] HTTP Host Availability
    • All required HTTP hosts are available

**Comment by darshankawar** [comment]
@JaredEzz 
I am unable to replicate this error by running the said command using latest stable or master versions.
Can you try to run it on latest master and check if you still get the same behavior ?

`flutter channel master`
`flutter upgrade`
