### ISSUE TITLE
Remove support for NullSafetyMode.autodetect in the tools

### ISSUE THREAD

**Issue by a-siva** [flutter/flutter#118813]
Flutter on the web platform appears to still support the feature of auto detecting the null safety mode ( NullSafetyMode.autodetect). This needs to be removed and users should be required to explicitly opt out if there is still a need to support unsound legacy code.

**Comment by a-siva** [comment]
//cc @zanderso

**Comment by zanderso** [comment]
@christopherfujino

**Comment by christopherfujino** [comment]
I just merged https://github.com/flutter/flutter/pull/118491 yesterday which addresses this.
