### ISSUE TITLE
TextSelectionControls overlap app bars

### ISSUE THREAD

**Issue by aurokk** [flutter/flutter#118815]
Hey!

I think there is a problem with the TextSelectionControls, at least with the Cupertino ones.
I expect them to render behind App and Navigation Bars.

P.S.: There are custom TextSelectionControls and NavBar on the screenshot, but it doesn't matter, I tested the standard components and they have the same problem, the problem is in the position of the components in the render tree.

https://user-images.githubusercontent.com/7325744/213527231-f68de206-9b1b-4b62-b91d-19761b0309f2.mp4

<img width="784" alt="Screenshot 2023-01-19 at 21 21 49" src="https://user-images.githubusercontent.com/7325744/213528334-ee27334d-c1f4-4530-b2f1-13726830722a.png">

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel stable, 3.3.10, on macOS 13.0 22A380 darwin-arm, locale en-RU)
    • Flutter version 3.3.10 on channel stable at /opt/homebrew/Caskroom/flutter/3.3.10/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (5 weeks ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @aurokk, this issue is known and is being tracked in https://github.com/flutter/flutter/issues/13182. See also https://github.com/flutter/flutter/issues/59229

Kindly follow up in the issue linked above for updates. 

Closing from here as duplicate. 

Thank you
