### ISSUE TITLE
[tool_crash] UnsupportedError: Unsupported operation: Illegal character in path: C:

### ISSUE THREAD

**Issue by JaredEzz** [flutter/flutter#118806]
## Command
```
flutter --no-color test --machine --platform chrome test
```

## Steps to Reproduce
1. Run a Flutter Test on Windows with the `--platform chrome` flag in IntelliJ IDEA

## Logs
UnsupportedError: Unsupported operation: Illegal character in path: C:
```
#0      _Uri._checkWindowsPathReservedCharacters (dart:core/uri.dart:1841:11)
#1      _Uri._toWindowsFilePath (dart:core/uri.dart:2879:7)
#2      _Uri.toFilePath (dart:core/uri.dart:2854:38)
#3      JsonReporter._frameInfo.<anonymous closure> (package:test_core/src/runner/reporter/json.dart:314:19)
#4      IterableExtension.firstWhereOrNull (package:collection/src/iterable_extensions.dart:246:15)
#5      JsonReporter._frameInfo (package:test_core/src/runner/reporter/json.dart:312:35)
#6      JsonReporter._onTestStarted (package:test_core/src/runner/reporter/json.dart:145:12)
#7      _rootRunUnary (dart:async/zone.dart:1407:13)
#8      _CustomZone.runUnary (dart:async/zone.dart:1300:19)
#9      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1209:7)
#10     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#11     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#12     _SyncBroadcastStreamController._sendData (dart:async/broadcast_stream_controller.dart:377:25)
#13     _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:244:5)
#14     _rootRunUnary (dart:async/zone.dart:1399:47)
#15     _CustomZone.runUnary (dart:async/zone.dart:1300:19)
#16     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1209:7)
#17     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#18     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#19     _SyncBroadcastStreamController._sendData (dart:async/broadcast_stream_controller.dart:377:25)
#20     _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:244:5)
#21     LiveSuiteController.reportLiveTest (package:test_core/src/runner/live_suite_controller.dart:133:30)
#22     Engine._runLiveTest (package:test_core/src/runner/engine.dart:364:21)
<asynchronous suspension>
#23     Engine._runGroup (package:test_core/src/runner/engine.dart:325:13)
```
```
[✓] Flutter (Channel stable, 3.3.8, on Microsoft Windows [Version 10.0.22622.575], locale en-US)
    • Flutter version 3.3.8 on channel stable at C:\Users\jared\dev\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 52b3dc25f6 (2 months ago), 2022-11-09 12:09:26 +0800
    • Engine revision 857bd6b74c
    • Dart version 2.18.4
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at C:\Users\jared\AppData\Local\Android\sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • Java binary at: C:\Users\jared\.jdks\corretto-11.0.14\bin\java.exe
    • Java version OpenJDK Runtime Environment Corretto-11.0.14.9.1 (build 11.0.14+9-LTS)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✗] Visual Studio - develop for Windows
    ✗ Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[✓] IntelliJ IDEA Ultimate Edition (version 2022.2)
    • IntelliJ at C:\Users\jared\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\222.4345.14
    • Flutter plugin version 71.2.6
    • Dart plugin version 223.7571.203

[✓] IntelliJ IDEA Ultimate Edition (version 2022.3)
    • IntelliJ at C:\Users\jared\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\223.7571.182
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin version 222.4345.14

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22622.575]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 109.0.5414.75
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 108.0.1462.46

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.2.1+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: unknown
**Creation framework version**: ffb2ecea5223acdd139a5039be2f9c796962833d
### Plugins
cloud_firestore_web-2.8.10
cloud_functions-3.3.9
cloud_functions_web-4.3.7
connectivity_plus-3.0.2
device_info_plus-7.0.1
firebase_core-1.24.0
firebase_core_web-1.7.3
firebase_performance-0.8.3+3
firebase_performance_web-0.1.1+8
firebase_remote_config-1.0.4
firebase_remote_config_web-1.1.8
flutter_inappwebview-5.7.2+3
network_info_plus-3.0.1
package_info_plus-3.0.2
path_provider-2.0.11
path_provider_android-2.0.22
path_provider_ios-2.0.11
path_provider_linux-2.1.7
path_provider_macos-2.0.7
path_provider_windows-2.1.3
printing-5.9.3
shared_preferences-2.0.16
shared_preferences_android-2.0.14
shared_preferences_foundation-2.1.1
shared_preferences_linux-2.1.2
shared_preferences_web-2.0.4
shared_preferences_windows-2.1.2
url_launcher-6.1.7
url_launcher_android-6.0.22
url_launcher_ios-6.0.17
url_launcher_linux-3.0.1
url_launcher_macos-3.0.1
url_launcher_web-2.0.13
url_launcher_windows-3.0.1

**Comment by JaredEzz** [comment]
I'll also attach my pubspec since it seems that may be related 

```name: ostrich_cyber_risk
description: Analyze your posture. Compare your surface. Mitigate your risk.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.2.1+1

environment:
  sdk: ">=2.17.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  cloud_functions: #3.0.3
  csv: ^5.0.0
  firebase_core: ^1.13.1
  validators: #3.0.0
  chart_sparkline: ^1.0.7
  flutter_radar_chart:
    git:
      url: https://github.com/JaredEzz/flutter_radar_chart
  google_fonts: 2.1.1
  firebase_remote_config: ^1.0.4
  firebase_remote_config_web: ^1.0.4
  lottie: ^1.2.2
  carousel_slider: ^4.0.0
  youtube_player_iframe: ^2.2.2
  idb_shim: ^2.0.1
  intl: ^0.17.0
  pie_chart: ^5.3.0
  raygun4flutter: ^1.1.5
  pdf: ^3.8.1
  printing: ^5.9.1
  firebase_performance: ^0.8.2
  fl_chart:
  json_serializable: ^6.5.1
  json_annotation: ^4.7.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: #2.0.4
  mocktail: ^0.3.0
dependency_overrides:
  # overridden to avoid error on 4.5.2 with FirebaseAppPlatform.verifyExtends(_delegate); - see https://stackoverflow.com/questions/74228526/firebaseappplatform-verifyextends-error-while-running-flutter-test
  # can potentially be removed in a few versions after this is fixed
  firebase_core_platform_interface: 4.5.1
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0
  test: ^1.17.10

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - resources/
    - resources/logos/
    - resources/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
```

**Comment by darshankawar** [comment]
I am unable to replicate this tool crash, but I think looking at the command being run:

`flutter --no-color test --machine --platform chrome test`

Can you try by removing `--machine` argument ?, it seems the combination of `--machine` and `--platform` may be a factor here that could be leading to the crash.

**Comment by JaredEzz** [comment]
The machine argument cannot be removed from the IntelliJ configuration

**Comment by darshankawar** [comment]
I see, thanks for the update.

**Comment by yjbanov** [comment]
My suspicion is that this is due to Windows paths appearing in the source maps. We recently switched to platform-independent web SDK build, which should fix this, if it was caused by source maps.

Can you please try again on the latest main branch?

**Comment by JaredEzz** [comment]
I upgraded to 3.7.1 from 3.3.10 and ran `flutter --no-color test --machine --platform chrome test` again (which is the default command when using the default run configuration in IntelliJ IDEA), with the following results. I'm on the stable branch.

```
C:\Users\jared\dev\flutter\bin\flutter.bat --no-color test --machine --platform chrome test
Testing started at 11:26 AM ...

Oops; flutter has exited unexpectedly: "Unsupported operation: Illegal character in path: C:".
A crash report has been written to C:\Users\jared\IdeaProjects\isurrf_ui\flutter_17.log.
```

log contents: 
```
Flutter crash report.
Please report a bug at https://github.com/flutter/flutter/issues.

## command

flutter --no-color test --machine --platform chrome test

## exception

UnsupportedError: Unsupported operation: Illegal character in path: C:

#0      _Uri._checkWindowsPathReservedCharacters (dart:core/uri.dart:1844:11)
#1      _Uri._toWindowsFilePath (dart:core/uri.dart:2882:7)
#2      _Uri.toFilePath (dart:core/uri.dart:2857:38)
#3      JsonReporter._frameInfo.<anonymous closure> (package:test_core/src/runner/reporter/json.dart:314:19)
#4      IterableExtension.firstWhereOrNull (package:collection/src/iterable_extensions.dart:247:15)
#5      JsonReporter._frameInfo (package:test_core/src/runner/reporter/json.dart:312:35)
#6      JsonReporter._onTestStarted (package:test_core/src/runner/reporter/json.dart:145:12)
#7      _rootRunUnary (dart:async/zone.dart:1414:13)
#8      _CustomZone.runUnary (dart:async/zone.dart:1307:19)
#9      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1216:7)
#10     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#11     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#12     _SyncBroadcastStreamController._sendData (dart:async/broadcast_stream_controller.dart:377:25)
#13     _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:244:5)
#14     _rootRunUnary (dart:async/zone.dart:1406:47)
#15     _CustomZone.runUnary (dart:async/zone.dart:1307:19)
#16     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1216:7)
#17     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#18     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#19     _SyncBroadcastStreamController._sendData (dart:async/broadcast_stream_controller.dart:377:25)
#20     _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:244:5)
#21     LiveSuiteController.reportLiveTest (package:test_core/src/runner/live_suite_controller.dart:133:30)
#22     Engine._runLiveTest (package:test_core/src/runner/engine.dart:364:21)
<asynchronous suspension>
#23     Engine._runGroup (package:test_core/src/runner/engine.dart:325:13)
<asynchronous suspension>
#24     Engine.run.<anonymous closure>.<anonymous closure> (package:test_core/src/runner/engine.dart:268:13)
<asynchronous suspension>
```

## flutter doctor

```
[✓] Flutter (Channel stable, 3.7.1, on Microsoft Windows [Version 10.0.22622.575], locale en-US)
    • Flutter version 3.7.1 on channel stable at C:\Users\jared\dev\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7048ed95a5 (2 days ago), 2023-02-01 09:07:31 -0800
    • Engine revision 800594f1f4
    • Dart version 2.19.1
    • DevTools version 2.20.1

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at C:\Users\jared\AppData\Local\Android\sdk
    • Platform android-33-ext4, build-tools 33.0.1
    • Java binary at: C:\Users\jared\.jdks\corretto-11.0.14\bin\java.exe
    • Java version OpenJDK Runtime Environment Corretto-11.0.14.9.1 (build 11.0.14+9-LTS)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✗] Visual Studio - develop for Windows
    ✗ Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[✓] IntelliJ IDEA Ultimate Edition (version 2022.3)
    • IntelliJ at C:\Users\jared\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\223.8617.56
    • Flutter plugin version 71.3.6
    • Dart plugin version 223.8617.8

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22622.575]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 109.0.5414.120
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 109.0.1518.70

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.
```

```

I've also included my flutter doctor output to make sure I'm on the branch you're suggesting.
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.7.1, on Microsoft Windows [Version 10.0.22622.575], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[√] Chrome - develop for the web
[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[!] Android Studio (not installed)
[√] IntelliJ IDEA Ultimate Edition (version 2022.3)
[√] Connected device (3 available)
[√] HTTP Host Availability

! Doctor found issues in 2 categories.
```


Flutter crash report.
Please report a bug at https://github.com/flutter/flutter/issues.

## command

flutter --no-color test --machine --platform chrome test

## exception

UnsupportedError: Unsupported operation: Illegal character in path: C:

```
#0      _Uri._checkWindowsPathReservedCharacters (dart:core/uri.dart:1844:11)
#1      _Uri._toWindowsFilePath (dart:core/uri.dart:2882:7)
#2      _Uri.toFilePath (dart:core/uri.dart:2857:38)
#3      JsonReporter._frameInfo.<anonymous closure> (package:test_core/src/runner/reporter/json.dart:314:19)
#4      IterableExtension.firstWhereOrNull (package:collection/src/iterable_extensions.dart:247:15)
#5      JsonReporter._frameInfo (package:test_core/src/runner/reporter/json.dart:312:35)
#6      JsonReporter._onTestStarted (package:test_core/src/runner/reporter/json.dart:145:12)
#7      _rootRunUnary (dart:async/zone.dart:1414:13)
#8      _CustomZone.runUnary (dart:async/zone.dart:1307:19)
#9      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1216:7)
#10     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#11     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#12     _SyncBroadcastStreamController._sendData (dart:async/broadcast_stream_controller.dart:377:25)
#13     _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:244:5)
#14     _rootRunUnary (dart:async/zone.dart:1406:47)
#15     _CustomZone.runUnary (dart:async/zone.dart:1307:19)
#16     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1216:7)
#17     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#18     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#19     _SyncBroadcastStreamController._sendData (dart:async/broadcast_stream_controller.dart:377:25)
#20     _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:244:5)
#21     LiveSuiteController.reportLiveTest (package:test_core/src/runner/live_suite_controller.dart:133:30)
#22     Engine._runLiveTest (package:test_core/src/runner/engine.dart:364:21)
<asynchronous suspension>
#23     Engine._runGroup (package:test_core/src/runner/engine.dart:325:13)
<asynchronous suspension>
#24     Engine.run.<anonymous closure>.<anonymous closure> (package:test_core/src/runner/engine.dart:268:13)
<asynchronous suspension>
```

## flutter doctor

```
[✓] Flutter (Channel stable, 3.7.1, on Microsoft Windows [Version 10.0.22622.575], locale en-US)
    • Flutter version 3.7.1 on channel stable at C:\Users\jared\dev\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7048ed95a5 (2 days ago), 2023-02-01 09:07:31 -0800
    • Engine revision 800594f1f4
    • Dart version 2.19.1
    • DevTools version 2.20.1

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at C:\Users\jared\AppData\Local\Android\sdk
    • Platform android-33-ext4, build-tools 33.0.1
    • Java binary at: C:\Users\jared\.jdks\corretto-11.0.14\bin\java.exe
    • Java version OpenJDK Runtime Environment Corretto-11.0.14.9.1 (build 11.0.14+9-LTS)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✗] Visual Studio - develop for Windows
    ✗ Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[✓] IntelliJ IDEA Ultimate Edition (version 2022.3)
    • IntelliJ at C:\Users\jared\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\223.8617.56
    • Flutter plugin version 71.3.6
    • Dart plugin version 223.8617.8

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22622.575]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 109.0.5414.120
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 109.0.1518.70

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.
```

**Comment by christopherfujino** [comment]
@JaredEzz can you try again from the master branch? The fix yjbanov referenced is not yet in stable.

**Comment by JaredEzz** [comment]
I'm okay to wait until it makes it into stable. For various reasons I'd like to stay on stable for work and such

**Comment by christopherfujino** [comment]
> I'm okay to wait until it makes it into stable. For various reasons I'd like to stay on stable for work and such

So, if you don't want to try to repro on master, that is fine. However I will close this issue as not reproducible (as no maintainers have been able to reproduce), and it is not verified that the issue has actually been fixed.

You don't need to do development from master, but attempting to reproduce this on the master channel will verify that the root cause is known and has already been fixed.
