### ISSUE TITLE
iOS platform view is flashing on top of AppBar, SliverAppBar and SliverPersistentHeader widgets

### ISSUE THREAD

**Issue by timtangcoding** [flutter/flutter#118877]
## Steps to Reproduce
Using the steps on the issue (https://github.com/flutter/flutter/issues/86787), it is found that iOS PlatformView will still flash over 
AppBar, SliverAppBar and SliverPersistentHeader widgets

**Expected results:** 
 iOS PlatformView will not flash over AppBar / SliverAppBar / SliverPersistentHeader widgets

**Actual results:** 
 iOS PlatformView will flash over AppBar / SliverAppBar / SliverPersistentHeader widgets

**Output of fvm flutter doctor -v :** 
fvm flutter doctor -v
[✓] Flutter (Channel stable, 3.0.5, on macOS 11.4 20F71 darwin-x64, locale en-HK)
    • Flutter version 3.0.5 at /Users/timtangcoding/fvm/versions/3.0.5
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (6 months ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/timtangcoding/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = /Users/timtangcoding/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Community Edition (version 2021.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.74.2)
    • VS Code at /Users/timtangcoding/Documents/Softwares/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (4 available)
    • HTC U11 plus (mobile) • FA8271E00791              • android-arm64  • Android 9 (API 28)
    • iPhone (mobile)       • 00008110-00094502348A801E • ios            • iOS 15.5 19F77
    • macOS (desktop)       • macos                     • darwin-x64     • macOS 11.4 20F71 darwin-x64
    • Chrome (web)          • chrome                    • web-javascript • Google Chrome 109.0.5414.87

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Device models:** 
- iPhone 13 Pro
- iPhone 14 Pro 

https://user-images.githubusercontent.com/16203104/213665368-e881c496-400a-439d-93fb-2e961923f858.mp4

**Comment by darshankawar** [comment]
@timtangcoding 
You are on old version of stable and the issue you linked is also old which was fixed. I recommend you to upgrade to latest stable or master versions and try again to see if the issue still persists or not.

`flutter channel stable`
`flutter upgrade`

**Comment by timtangcoding** [comment]
@darshankawar 
Thanks for the prompt response!
From the original post (https://github.com/flutter/flutter/issues/86787) I thought that the PR#29930 ([ios platform view] fix overlay zPosition (https://github.com/flutter/engine/pull/29930)) has been merged since Flutter version 2.10.0-0.0.pre ? (https://github.com/flutter/flutter/commit/a27454fc8c5892bd0a314ef4b55e94960d25f9dc)
Please correct me if I am wrong.

Anyway, I would try the latest stable version and update here about the test results.

Thank you so much for the kind help!

**Comment by timtangcoding** [comment]
I have tested with flutter version 3.7.0 and seems the issues still exists on iPhone 13 Pro.
May I know if anyone else have such issue? 

@darshankawar 
**Output of fvm flutter doctor -v**
fvm flutter doctor -v
[✓] Flutter (Channel stable, 3.7.0, on macOS 12.5.1 21G83 darwin-arm64, locale en-GB)
    • Flutter version 3.7.0 on channel stable at /Users/timtang/fvm/versions/3.7.0
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b06b8b2710 (4 days ago), 2023-01-23 16:55:55 -0800
    • Engine revision b24591ed32
    • Dart version 2.19.0
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/timtang/Library/Android/sdk
    • Platform android-33, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F100
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] IntelliJ IDEA Community Edition (version 2020.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.74.0)
    • VS Code at /Users/timtang/Documents/worksBase/VSCode/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • iPhone (mobile) • 00008110-00094502348A801E • ios            • iOS 15.5 19F77
    • macOS (desktop) • macos                     • darwin-arm64   • macOS 12.5.1 21G83 darwin-arm64
    • Chrome (web)    • chrome                    • web-javascript • Google Chrome 109.0.5414.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!


https://user-images.githubusercontent.com/16203104/215114575-010b9b37-03fb-45d6-a7a6-6cf1808a83c4.MP4

**Comment by darshankawar** [comment]
Thanks for the update @timtangcoding 
I think your case is similar to https://github.com/flutter/flutter/issues/116640 so please follow-up in that issue for further updates. I suggest you to share your findings in it for better tracking as it has more in-depth analysis and discussion going on.
Closing this in favor of the linked issue. If you disagree, write in comments and I'll reopen it.

**Comment by timtangcoding** [comment]
@darshankawar 
Thanks for the suggestion. I will try to follow up the issues over there.



> Thanks for the update @timtangcoding I think your case is similar to #116640 so please follow-up in that issue for further updates. I suggest you to share your findings in it for better tracking as it has more in-depth analysis and discussion going on. Closing this in favor of the linked issue. If you disagree, write in comments and I'll reopen it.

**Comment by timtangcoding** [comment]
@darshankawar 
On flutter 3.7.0, severer flashes could be observed even when the project does not add <key>CADisableMinimumFrameDurationOnPhone</key><true/> and **Enable faster ProMotion refresh rates** (https://developer.apple.com/documentation/quartzcore/optimizing_promotion_refresh_rates_for_iphone_13_pro_and_ipad_pro?language=objc)
Thus the root cause may not be related to 120Hz Pro display ? 

The flashes issue on the sample project is greatly improved (still flashes slightly) when adding <key>CADisableMinimumFrameDurationOnPhone</key><true/> while Settings > Accessibility > Motion > Limit Frame Rate  is switched on.

**Comment by darshankawar** [comment]
I think there's already an issue being tracked for the behavior you mentioned, per the latest conversation in the linked issue.

**Comment by timtangcoding** [comment]
> I think there's already an issue being tracked for the behavior you mentioned, per the latest conversation in the linked issue.

Yes, let's follow up on this issue. (https://github.com/flutter/flutter/issues/116640)
