### ISSUE TITLE
Stuck when running "flutter doctor"

### ISSUE THREAD

**Issue by DiegoVega19** [flutter/flutter#118897]
## Steps to Reproduce

When I run flutter doctor, on a mac mini with MAC OS High Sierra, Version 10.13.6, command get stuck on "Running flutter pub get  in flutter tools".

any idea to fix that problem? is flutter compatible with this version of MAC OS?

My flutter Version
![image](https://user-images.githubusercontent.com/45367804/213765474-6bec82c3-08d9-497d-add1-6799176c5e7f.png)

the problem
![image](https://user-images.githubusercontent.com/45367804/213765580-e908060c-cca4-42c1-b1e7-c4cde162d396.png)

Thanks.

**Comment by darshankawar** [comment]
@DiegoVega19 
Can you run `flutter doctor -v` and provide the verbose log ?


> is flutter compatible with this version of MAC OS?

Ideally it should be compatible

> mac mini with MAC OS High Sierra, Version 10.13.6

Does the mac mini have proper tools already setup like platform-tools and Xcode ?
