### ISSUE TITLE
[embedder] Vulkan embedder incorrectly queries vkGetInstanceProcAddr without the vk prefix

### ISSUE THREAD

**Issue by nanokatze** [flutter/flutter#118956]
See https://github.com/flutter/engine/blob/main/shell/platform/embedder/embedder.cc#L565 and how things are passed down to glfwGetInstanceProcAddr at https://github.com/flutter/engine/blob/main/examples/vulkan_glfw/src/main.cc#L394

This does make me wonder whether the Vulkan GLFW example *ever* worked at all?

**Comment by chinmaygarde** [comment]
I believe the VK prefix is not present for all proc addresses. If so, I am not sure how the example worked before. cc @bdero who authored the example before.

But we should fix this behavior and document it either way. Perhaps by trying both the suffixed version and the plain one.

**Comment by nanokatze** [comment]
> I believe the VK prefix is not present for all proc addresses.

vkGetInstanceProcAddr is the only function that vulkan_get_instance_proc_address is used to get. All others are obtained through the newly obtained vkGetInstanceProcAddr or vkGetDeviceProcAddr.

**Comment by bdero** [comment]
I authored both the Vulkan embedder and the Vulkan GLFW embedder example; both run fine on Mac/Linux/Windows. Unfortunately, we don't have any runtime checks for any of these GLFW examples, and so breakages get discovered lazily right now.

I believe this PR likely broke the embedder? (FYI @iskakaushik): https://github.com/flutter/engine/commit/ff05a31f5b53fad6a35ad731cbefaaa5845d7d7e#diff-37c8701cb24b47259df5ef2673e076c7fa7d04feacef849ab8b835ed1bfa991cR561
