### ISSUE TITLE
flutter doesn't export RawKeyEvent?

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#11899]
Not sure if this is intentional.  I am attempting to use RawKeyboardListener https://docs.flutter.io/flutter/widgets/RawKeyboardListener-class.html , when defining my onKey, I want to provide a type for the event, but it appears the RawKeyEvent type isn't exported by default.

**Comment by eseidelGoogle** [comment]
https://docs.flutter.io/flutter/services/RawKeyEvent-class.html doesn't say I need to import anything to use it. :)

**Comment by Hixie** [comment]
RawKeyboardListener should reexport RawKeyEvent.

**Comment by eseidelGoogle** [comment]
The current way to get it is with `import 'package:flutter/services.dart';`
