### ISSUE TITLE
Raster Cache making text and images blurry/low res on fuchsia

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#11898]

**Comment by apwilson** [comment]
@chinmaygarde

**Comment by apwilson** [comment]
Good:
![good](https://user-images.githubusercontent.com/142874/29982091-3213ad3a-8f05-11e7-859d-d60e7c207a3d.jpg)

Bad:
![bad](https://user-images.githubusercontent.com/142874/29982092-321740da-8f05-11e7-9d2a-b1eb0e73a17a.jpg)

Also bad:
![also_bad](https://user-images.githubusercontent.com/142874/29982090-3201a6ee-8f05-11e7-9640-eca5fb8925da.jpg)

**Comment by apwilson** [comment]
Any update on this?

**Comment by Hixie** [comment]
@chinmaygarde is planning on looking at this but needs to set up a new fuchsia environment first.

**Comment by mikejurka** [comment]
This is resolved now.
