### ISSUE TITLE
Reland the upload of win arm64 artifacts

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#118900]
The original change was reverted in https://flutter-review.googlesource.com/c/recipes/+/38180.

The root cause of the problem is that the artifacts we were trying to upload didn't exist. They required additional ninja targets.

To prevent this from happening we need to add additional checks that the files exist on presubmit.

**Comment by godofredoc** [comment]
\cc @loic-sharma @zanderso @pbo-linaro

**Comment by pbo-linaro** [comment]
Do you need help on fixing this? In the original patch, it was just doing the same thing as the x64 platform, so I don't have a clue about what could be missing.

**Comment by godofredoc** [comment]
Fixed with: https://flutter-review.googlesource.com/c/recipes/+/38132
