### ISSUE TITLE
[iOS] svg image widget are replaced with other widget

### ISSUE THREAD

**Issue by ostk0069** [flutter/flutter#118941]
Currently, we are doing beta testing to replace swift app to flutter app.
We have found out one issue releted to UI.
Some widget are replaced with other widget which is rendered in other place.
We are currenly working on finding the way to reproduce the issue, but not yet found.
Beta tester users are up to 1100+ and this issue occured 5 times.
We tracked errors on Sentry, but we could not find any error releated to this issue.

Here are some sample image made from user's screenshot. 

UI is expected to show assets image(SVG) but other assets image(SVG) or test widget are shown.

|Bug Screenshot|Expected Screenshot|Description|
|---|---|---|
|<img src=https://user-images.githubusercontent.com/27538852/213859130-96e10189-46f8-45f9-8309-a6b79143521f.png  width=300px>|<img src=https://user-images.githubusercontent.com/27538852/213859162-605d8fee-a4ca-4f20-b61a-be8011b8edc2.png  width=300px>|svg image is replaced with other svg (check icon is replaced with red colored fork & knife icon)|
|<img src=https://user-images.githubusercontent.com/27538852/213859180-5ebefd13-e022-4bcb-b2ba-2ee810fc15ef.png  width=300px>|<img src=https://user-images.githubusercontent.com/27538852/213859162-605d8fee-a4ca-4f20-b61a-be8011b8edc2.png  width=300px>|svg image is replaced with text widget(question icon is replaced with Bo(shorten of Bob))|

here are table with each environments.
|iOS|Device|
|---|---|
|iOS 15.6.1|iPhone 12|
|iOS 16.1.1|iPhone XS|
|iOS 14.4.2|iPhone 12 mini|
iOS 16.1.2|iPhone SE 2nd|
iOS 16.2|iPhone 11|

sample code:

```dart
final assetName = 'assets/up_arrow.svg';
final svgIcon = SvgPicture.asset(
 'check',
  color: Colors.gray,
  semanticsLabel: 'check'
);
```

https://pub.dev/packages/flutter_svg

<details>
  <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.3.10, on macOS 12.5 21G72 darwin-arm, locale ja-JP)
    • Flutter version 3.3.10 on channel stable at /Users/s11080/fvm/versions/3.3.10
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (5 weeks ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/s11080/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode_14.0.1.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.74.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.5 21G72 darwin-arm
    • Chrome (web)    • chrome • web-javascript • unknown

[✓] HTTP Host Availability
    • All required HTTP hosts are available
```

</details>

**Comment by exaby73** [comment]
Hello @ostk0069. The sample code you provided, you just have the asset name as `'check'`. I think you need to have the complete path to the asset, similar to how you would with `Image.asset`.

But either way, this doesn't seem like an issue with Flutter, but rather `flutter_svg` which is not maintained by the Flutter team. I suggest you raise this issue with the package author in the respective repository (https://github.com/dnfield/flutter_svg).

I am closing this issue as this does not seem like an issue with Flutter. If you disagree, please comment with your reasoning and I can reopen the issue. Thank you

**Comment by ostk0069** [comment]
@exaby73 
Thank you for your reply.
I think if this problem only replace svg image widget to other svg image widget, flutter_svg could be the reason for this bug.
However this problem has case of replacing with Text widget which is non-related to flutter_svg code.
I'm using 1.1.6 version of https://pub.dev/packages/flutter_svg and could not find any related code there.
Is it possible to look up for this bug in flutter. eg. ios rendering engine.

**Comment by exaby73** [comment]
I would need a [complete and minimal, reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) from you to move forward with the issue. This sample, should be complete without the use of 3rd party libraries. Could you provide such a code sample?
