### ISSUE TITLE
Slow first-frame startup performance on desktop Linux

### ISSUE THREAD

**Issue by vially** [flutter/flutter#118911]
## Details

On desktop Linux, it takes a significant amount of time for the first Flutter frame to render inside the newly created window.

In practice, it means the user is looking at a blank window for a couple of seconds until the first Flutter frame is rendered (as seen in the video recording below).

This is reproducible on multiple machines (using reasonably powerful hardware), on multiple channels (`stable`/`master`) and for all build modes (`debug`/`profile`/`release`).

### Steps to reproduce

The issue is reproducible using the default Linux desktop app template without any code changes.

1. Create new demo project

```
flutter create --platforms=linux flperfdemo
```

2. Run the demo project on desktop Linux

```
flutter run -d linux
```

After the native (GTK) window is opened, it takes around 4-5 seconds for the first Flutter frame to render inside the window.

Contents of `start_up_info.json` when running with `flutter run --trace-startup --profile`:

```json
{
  "engineEnterTimestampMicros": 6724731208,
  "timeToFrameworkInitMicros": 2271098,
  "timeToFirstFrameRasterizedMicros": 4756373,
  "timeToFirstFrameMicros": 4747155,
  "timeAfterFrameworkInitMicros": 2476057
}
```

Timeline trace when running with `flutter run --profile`: https://gist.github.com/vially/fddc530844b16456bee986a56c791f2c

### Video recording

[desktop-linux-slow-first-frame.webm](https://user-images.githubusercontent.com/433598/213810110-4ff0223b-fa4b-44ab-b236-0104d68c73e8.webm)

**Target Platform:** Linux
**Target OS version/browser:** Arch Linux
**Devices:** Linux Desktop (linux-x64)
**Display server:** Wayland (sway)
**Graphic drivers:** Mesa 22.3.3
**Hardware specs:**
 - CPU: AMD Ryzen 9 3950X
 - GPU: AMD Radeon RX 6700 XT

## Logs

<details>
<summary>Logs</summary>

```
Analyzing flperfdemo...
No issues found! (ran in 2.3s)
```

```
[✓] Flutter (Channel stable, 3.3.10, on Arch Linux 6.1.6-arch1-3, locale en_US.UTF-8)
    • Flutter version 3.3.10 on channel stable at /home/vially/.local/share/flutter-sdk
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (5 weeks ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[✓] Linux toolchain - develop for Linux desktop
    • clang version 15.0.7
    • cmake version 3.25.2
    • ninja version 1.11.1
    • pkg-config version 1.8.0

[!] Flutter IDE Support (No supported IDEs installed)
    • IntelliJ - https://www.jetbrains.com/idea/
    • Android Studio - https://developer.android.com/studio/
    • VS Code - https://code.visualstudio.com/

[✓] Connected device (1 available)
    • Linux (desktop) • linux • linux-x64 • Arch Linux 6.1.6-arch1-3

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

```json
{
  "engineEnterTimestampMicros": 6724731208,
  "timeToFrameworkInitMicros": 2271098,
  "timeToFirstFrameRasterizedMicros": 4756373,
  "timeToFirstFrameMicros": 4747155,
  "timeAfterFrameworkInitMicros": 2476057
}
```

https://gist.github.com/vially/fddc530844b16456bee986a56c791f2c

</details>

**Comment by jonahwilliams** [comment]
Does this reproduce without using flutter run? flutter run, even in profile/release mode, can add measurable overhead via tracing and profiling attachments. While the goal is certainly for it to be low overhead, I don't know if we've specifically measured the delta for desktop applications

**Comment by vially** [comment]
Yes, the performance is almost the same when running the binary directly with:

```
flutter build linux --release
/build/linux/x64/release/bundle/flperfdemo
```

**Comment by jonahwilliams** [comment]
Thank you @vially !

**Comment by jonahwilliams** [comment]
There is no more shader warmup in the framework, the Warmup frame should just be an empty one, see:

https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/scheduler/binding.dart#L926-L963

If we're doing a whole bunch of first frame shader compilation I suspect that is being driven by Skia

**Comment by vially** [comment]
This is the log when running with `flutter run --profile --trace-skia`: [dart-timeline-2023-1-23.zip](https://github.com/flutter/flutter/files/10483336/dart-timeline-2023-1-23.zip)

**Comment by chinmaygarde** [comment]
Thats so odd. It doesn't seem to be Skia but filesystem access being super slow (seeks and reads in libc). Are you on a network mount perhaps?

**Comment by vially** [comment]
That's really strange indeed. I am not using a network mount.

I have two locally attached NVMe SSDs (Samsung 980 1TB) using the Btrfs file system. I'm not usually doing any IO intensive work, but for what it's worth I have never perceived any other application or operation as being slow on this machine.

But now that you mention it I remember I first noticed this slow first-frame performance on *another* machine that was also using the Btrfs file-system. Not sure if it's related or just a coincidence though.

**Comment by vially** [comment]
After some more investigation it turns out the number of fonts installed on the system has a direct impact on the startup performance of flutter apps.

For example, on ArchLinux there seems to be a significant difference in startup performance when the [ttf-google-fonts-git](https://aur.archlinux.org/packages/ttf-google-fonts-git) package is installed versus when it's not.

**Comment by vially** [comment]
The following `Dockerfile` should help reproduce this bug *consistently* on any Linux system (regardless of the fonts installed on the host):

```Dockerfile
FROM archlinux:latest

# Install Flutter dependencies
RUN pacman -Syy && \
    pacman -Syu --noconfirm && \
    pacman -S --noconfirm base-devel clang wget git ninja cmake gtk3

RUN update-mime-database /usr/share/mime

# Install and configure Flutter SDK
RUN wget -O /tmp/flutter.tar.xz https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.7.7-stable.tar.xz && \
    cd /tmp && \
    tar xf flutter.tar.xz && \
    rm flutter.tar.xz && \
    mv flutter /opt/ && \
    git config --global --add safe.directory /opt/flutter && \
    export PATH=/opt/flutter/bin:$PATH && \
    flutter config --no-enable-web --no-enable-android && \
    flutter doctor && \
    echo -e "export PATH=/opt/flutter/bin:$PATH\nexport XDG_RUNTIME_DIR=/run" >> ~/.bashrc

# Create and build demo Flutter app
RUN export PATH=/opt/flutter/bin:$PATH && \
    mkdir /app && \
    cd /app && \
    flutter create --platforms=linux flperfdemo && \
    cd flperfdemo && \
    flutter build linux --release

# Enable AUR repo and install ttf-google-fonts-git
RUN echo -e "\n\n[arcanisrepo]\nServer = http://repo.arcanis.me/x86_64\nSigLevel = DatabaseRequired PackageNever TrustedOnly" >> /etc/pacman.conf && \
    pacman-key --init && pacman-key --recv-keys E989490C && pacman-key --lsign-key E989490C && pacman -Syy && \
    pacman -Rdd --noconfirm adobe-source-code-pro-fonts && pacman -S --noconfirm ttf-google-fonts-git

ENV XDG_RUNTIME_DIR=/run

WORKDIR /app/flperfdemo

CMD ["/app/flperfdemo/build/linux/x64/release/bundle/flperfdemo"]
```

### Steps to reproduce (slow)

1. `docker build -t flperfdemo:slow .`
2. `docker run --rm -it -v "$XDG_RUNTIME_DIR/$WAYLAND_DISPLAY":"/run/$WAYLAND_DISPLAY" -v /dev/dri:/dev/dri -e WAYLAND_DISPLAY=$WAYLAND_DISPLAY flperfdemo:slow`
  Note: This step assume an active Wayland session.

https://user-images.githubusercontent.com/433598/225416515-11ddf5e3-0d6f-45ad-8186-26773bdc5b9e.mp4

### Steps to reproduce (fast)

Removing the `ttf-google-fonts-git` package makes the first frame render almost instantly.

1. Remove the following lines from the `Dockerfile`:

```diff
-# Enable AUR repo and install ttf-google-fonts-git
-RUN echo -e "\n\n[arcanisrepo]\nServer = http://repo.arcanis.me/x86_64\nSigLevel = DatabaseRequired PackageNever TrustedOnly" >> /etc/pacman.conf && \
-    pacman-key --init && pacman-key --recv-keys E989490C && pacman-key --lsign-key E989490C && pacman -Syy && \
-    pacman -Rdd --noconfirm adobe-source-code-pro-fonts && pacman -S --noconfirm ttf-google-fonts-git
```

2. `docker build -t flperfdemo:fast .`
3. `docker run --rm -it -v "$XDG_RUNTIME_DIR/$WAYLAND_DISPLAY":"/run/$WAYLAND_DISPLAY" -v /dev/dri:/dev/dri -e WAYLAND_DISPLAY=$WAYLAND_DISPLAY flperfdemo:fast`


https://user-images.githubusercontent.com/433598/225416624-4f89804d-0699-467b-9a6e-1832ce835700.mp4

**Comment by zsien** [comment]
I have the same problem, waiting for a fix

**Comment by chinmaygarde** [comment]
I think the solution of linking against the system fontconfig is desirable. But we are trying to figure out how to reason about this for custom embedders. They depend on the engine provided font-config at this time I think. @cbracken, are you able to reason about the impact of the proposed changes in the [engine](https://github.com/flutter/engine/pull/40725) and [buildroot](https://github.com/flutter/buildroot/pull/701) for third party embedders (non-desktop).

**Comment by chinmaygarde** [comment]
cc @cbracken. Can you sign off on this please? From triage: We are supportive of landing this as-is but don't know for sure about its implications for all embedded users.

**Comment by vially** [comment]
@dongfengweixiao While investigating this issue, I found a couple of different issues that were partly responsible for the slow startup performance on desktop Linux. Most of the identified problems were related to the font loading on Linux and I have submitted some pull-requests in an attempt to fix them.

However, at the time of this writing, only one of submitted pull-requests has been accepted and merged into the `master` branch (https://github.com/flutter/engine/pull/40469).

The other two pull-requests, which are caused by statically linking to the system fontconfig, are still awaiting review (https://github.com/flutter/engine/pull/40725, https://github.com/flutter/buildroot/pull/701) so it's not yet possible to test them on the flutter `master` channel.

You should be able to test them by manually applying the patches and building the engine locally (and it would be very valuable as a data point to see if it improves performance in your case), but it's [a bit more work to do that](https://github.com/flutter/flutter/wiki/Debugging-the-engine).

**Comment by vially** [comment]
> It seems that this issue has been fixed in Flutter 3.10.

That's interesting. I can still reproduce the issue on Flutter 3.10 though (both directly on the host and in a container, using a Dockerfile similar to the one posted above).

Is there any chance something else might have changed on your setup too (e.g.: number of installed fonts or fontconfig version)?

**Comment by metinUr** [comment]
I can still reproduce this issue on 3.10.1 too.

**Comment by metinUr** [comment]
@dongfengweixiao  I just tried your compiled binary and when I have 1 font installed program opens noticeably faster. Here is the screencast versus 1775 fonts.

[1_font.webm](https://github.com/flutter/flutter/assets/17551688/b0430329-6964-4970-837e-b097ce164569)

[1775_fonts.webm](https://github.com/flutter/flutter/assets/17551688/80075382-cf3f-46c5-821c-78e38df2e8f5)

my system info:
```
Operating System: openSUSE Tumbleweed 20230515
KDE Plasma Version: 5.27.5
KDE Frameworks Version: 5.106.0
Qt Version: 5.15.9
Kernel Version: 6.3.1-2-default (64-bit)
Graphics Platform: Wayland
Processors: 12 × AMD Ryzen 5 5600X 6-Core Processor
Memory: 15.5 GiB of RAM
Graphics Processor: AMD Radeon RX 6600 XT
```

**Comment by cbracken** [comment]
The fontconfig dynamic linking patches have now landed in the buildroot and engine. Closing this issue. For other startup performance issues, we should file a new, specific bug. Thanks for filing, and for the fix @vially!
