### ISSUE TITLE
ScaffoldBackgroundColor incorrectly parsed from color scheme

### ISSUE THREAD

**Issue by WesselvanDam** [flutter/flutter#118979]
I created a light and dark ThemeData objects using the [Material Theme Builder](https://m3.material.io/theme-builder#/custom) and exported it to dart code.  However, the backgroundColor of Scaffolds is not the same as the color listed as `background` in the exported code's ColorScheme.

## Steps to Reproduce

1. Run the DartPad linked in "Code sample"

**Expected results:** 
The background of Scaffolds is the same as the `background` color listed in the ColorScheme at the end of the Pad. 

**Actual results:** 
The color is much lighter. This is not preferred as a) it looks less nice, and b) it does not align with the Material 3 specifications.

![image](https://user-images.githubusercontent.com/43265483/213933665-27955bbb-e005-4ce8-bdf0-edf90c579bf4.png)
Left: `background` color specified in ColorScheme. Right: actual background color in Scaffolds.

**Code sample**

[This DartPad](https://dartpad.dev/?id=18d5fd8fca6d4bc6dfc91f77d88bd349) shows an App using a theme created by the Material Theme Builder. The app shows a Scaffold and a square that is the color of the ColorScheme's `background` property. Clearly, the color is not the same as the scaffold color.

**Comment by exaby73** [comment]
Hello @WesselvanDam. While I can reproduce this issue in stable, it seems fixed in beta and master. You can check by switching the channel in DartPad (there's a dropdown at the bottom of the page) to beta and re-running the sample. Closing this issue as it's fixed. Thank you
