### ISSUE TITLE
Support getting an asset file path from AssetBundle

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#11892]
Currently you can load from an [`AssetBundle`](https://docs.flutter.io/flutter/services/AssetBundle-class.html), and get the data inside the asset. However, in some cases you need to pass the path to the actual file holding the asset data; for example if you want to play back a video using the [video_launcher](https://pub.dartlang.org/packages/video_launcher) plugin.

**Comment by Hixie** [comment]
@mit-mit @mravn-google  I'm leaving this in the current milestone since it seems like video-related work, but please don't hesitate to move it out if it's not something you think we'll get to in the next few months.

**Comment by mit-mit** [comment]
Yes, we should keep this. Should be fairly easy once the flx work completes.

**Comment by sroddy** [comment]
Is there a workaround to get the root path of the asset directory other than getting it with a MethodChannel?

**Comment by szakarias** [comment]
No, but we are in the process of redesigning our asset API and the plan is to make it possible to get the path of a given asset. Is there a particular use case that you would like support for?

**Comment by sroddy** [comment]
No, my use case was to be able to get the absolute path of a video inside the assets in order to load it with the video player plugin

**Comment by xster** [comment]
Posse had a similar issue where after selecting an asset from Flutter, there was no easy way to pass that asset reference to the native side without reading out the asset and shuffling all the bytes across platform channel.

**Comment by mit-mit** [comment]
Yes, that's the same issue. We hope that @szakarias can get to this fairly soon

**Comment by arranf** [comment]
I also have a use case for detecting whether an asset is a part of the bundle and if not, fetching it from a remote source.

**Comment by cbracken** [comment]
@szakarias any updates?

**Comment by szakarias** [comment]
I am currently working on how we handle assets on Android which will hopefully fix the slow startup, reduce the installed size and also make it possible to get a handle on an asset in the APK, which can be passed on, for instance to the video player.

**Comment by arranf** [comment]
Thanks Sarah,
This stuff has a huge impact on my app (a lot of images and low profile
devices). I'm really thankful to everything you're doing on this issue.
Happy to help if needed.

Arran

**Comment by MichaelSowah** [comment]
Hi @szakarias any updates? where are now on this? been a couple of months now...atleast we are just trying to find out progress and there's anything we can do to help as @arranf mentioned because for some os this is one of the major blocks for bring our apps live...thanks

**Comment by szakarias** [comment]
Fixed, see the [documentation](https://flutter.io/assets-and-images/#sharing-assets-with-the-underlying-platform).

**Comment by devxpy** [comment]
I wish i had found this earlier.

**Comment by QB3L** [comment]
I'm still not clear on how this was fixed. I'm trying to bundle some PDF files for displaying in my app and need the absolute path to them in order to open them. I don't see anything in AssetBundle documentation that gives me the path to them.

**Comment by mit-mit** [comment]
The original scope of this bug was to offer an asset API for getting assets paths on the host platforms. Documentation was added for Android and iOS here: 

https://flutter.io/docs/development/ui/assets-and-images#android
https://flutter.io/docs/development/ui/assets-and-images#ios

It sounds like there is a request to have a similar API on the Dart side. That sounds reasonable, but I suggest you open a new issue for that request.

**Comment by QB3L** [comment]
Thanks for the explanation @mit-mit now it's clearer. I misunderstood the scope of this completely

**Comment by RolfHendriks** [comment]
I have another use case and it is a rather simple one. Theming. I want an automatic way to get an asset path using a dark asset variation if available, otherwise using the normal path. So I need a fast, synchronous way to check for the existence of an asset without loading it. The minimum building block I need to implement this is to get the root path for assets. I can add functionality to my plugin to do this but this seems like a basic feature that should come packaged with Flutter automatically.

**Comment by lukepighetti** [comment]
My use case is bundling a test video in my repo to use for a mock video picker service so i can do things like golden test thumbnail/film-strip widget that takes a file as argument. I don't see a way to achieve this without being able to get the path of an asset.

**Comment by augsun** [comment]
We hope that can get to this fairly soon, this question take me 1day to fine method.
