### ISSUE TITLE
[infra]  Flutter HHH bots in the Dart tree were having issues on Flutter for Web builds

### ISSUE THREAD

**Issue by a-siva** [flutter/flutter#118908]
Flutter HHH bots in the Dart tree appear to be having issues on Flutter for Web builds

The error is
Failed to download https://storage.googleapis.com/flutter_archives_v2/monorepo/flutter_infra_release/cipd/flutter/web/canvaskit_bundle/+/61aeJQ9laGfEFF_Vlc_u0MCkqB6xb2hAYHRBxKH-Uw4C. Ensure you have network connectivity and then try again

See log file
https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8791582254224257089/+/u/Run_web_tests_0_tests/stdout

Comment from @jason-simmons 
The version of CanvasKit in that log is available for download via CIPD:
https://chrome-infra-packages.appspot.com/p/flutter/web/canvaskit_bundle/+/61aeJQ9laGfEFF_Vlc_u0MCkqB6xb2hAYHRBxKH-Uw4C

The script is apparently trying to download it from a `[https://storage.googleapis.com/flutter_archives_v2/monorepo/flutter_infra_release`](https://storage.googleapis.com/flutter_archives_v2/monorepo/flutter_infra_release%60) URL.

Does something need to be done in order to mirror the CanvasKit package to that bucket on GCS?

**Comment by a-siva** [comment]
The issue is fixed now, please close the issue if you think there is no further need for investigation.

**Comment by whesse** [comment]
I'll close the issue.  A more permanent solution would involve all artifacts, and all the upload locations, and we are thinking about that.  Canvaskit uploads will be solved when all of the builds upload it to their build artifacts, which is being worked towards.
