### ISSUE TITLE
[Web]TextField is unusable within a dialog on Samsung devices

### ISSUE THREAD

**Issue by Boma123** [flutter/flutter#118976]
Hi,

Still facing this issue on 3.3.10.  Bug presents itself exactly as described / recorded in the original post and [here](https://github.com/flutter/flutter/issues/110280#issue-1351371678) with steps to reproduce. 

This seems to affect a wide range of Samsung devices - currently we are encountering this issue on four different Samsung models (S9, A52, Note 20 and A12) - all of them running the PWA on Android Chrome (not Samsung browser) with canvaskit. The bug not only makes the keyboard entry impossible but in some cases crashes the app (keyboard becomes non-reactive).

Is there a fix for this in the beta or master channel that we can try?

_Originally posted by @GaryQian in https://github.com/flutter/flutter/issues/107786#issuecomment-1267310033_
            ](https://github.com/flutter/flutter/issues/107786#issue-1306883913)

**Comment by darshankawar** [comment]
> Is there a fix for this in the beta or master channel that we can try?

@Boma123 
As mentioned in last 2 comments of original issue, the reported issue seem to have been fixed on latest master, so I suggest you to switch to it and try the same case again to see if you still get the same behavior or expected one. If it indeed fixed on master, then the fix will most likely be rolled in next release of stable.

`flutter channel master`
`flutter upgrade`

I'll close this issue for now, as it seems to have been fixed and available on master. If you still see the same behavior on latest master too, please write in comments and I'll reopen it.
