### ISSUE TITLE
ListView are disposing the stateful children when an item is inserted on the top

### ISSUE THREAD

**Issue by henriqueArrazao** [flutter/flutter#118988]
## Steps to Reproduce

1. Execute the code sample and tap on the self explanatory buttons

**Expected results:** 
Only the new item inserted should have its state replaced.

**Actual results:** 
The stateful children in the list below the one added on top are having their states replaced.
This behavior does not happen when the item is inserted on the bottom of the list.

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

int counter = 0;

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  final String title;
  const MyHomePage({super.key, required this.title});

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  List<String> items = <String>[];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Colors.white,
        foregroundColor: Colors.blue,
        actions: [
          TextButton(
            child: const Text('Clear'),
            onPressed: () {
              setState(() {
                items = [];
              });
            },
          ),
          TextButton(
            child: const Text('Pos. 1'),
            onPressed: () {
              setState(() {
                items.insert(0, (++counter).toString());
              });
            },
          ),
          TextButton(
            child: const Text('Pos. last'),
            onPressed: () {
              setState(() {
                items.add((++counter).toString());
              });
            },
          )
        ],
      ),
      body: ListView.builder(
        itemCount: items.length,
        itemBuilder: (BuildContext context, int index) {
          return ListItem(
            title: items[index],
            key: ValueKey(items[index]),
          );
        },
      ),
    );
  }
}

class ListItem extends StatefulWidget {
  final String title;
  const ListItem({
    required this.title,
    super.key,
  });

  @override
  State<ListItem> createState() => _ListItemState();
}

class _ListItemState extends State<ListItem> {
  @override
  Widget build(BuildContext context) {
    return ListTile(
      title: Text(widget.title),
      subtitle: Text('$hashCode'),
    );
  }
}

```

</details>

**Comment by jonahwilliams** [comment]
This is working as expected. if you're going to insert into existing collections of widgets, you should either:

1. handle configuration changes in the State class using didUpdateWidget (https://api.flutter.dev/flutter/widgets/State/didUpdateWidget.html)
or

2. Use keys (see https://medium.com/flutter/keys-what-are-they-good-for-13cb51742e7d)

**Comment by henriqueArrazao** [comment]
> This is working as expected. if you're going to insert into existing collections of widgets, you should either:
> 
> 1. handle configuration changes in the State class using didUpdateWidget (https://api.flutter.dev/flutter/widgets/State/didUpdateWidget.html)
>    or
> 2. Use keys (see https://medium.com/flutter/keys-what-are-they-good-for-13cb51742e7d)

1. `didUpdateWidget` is not called since it is not reusing the current state but creating a new one
2. I'm already using keys, check out the sample code please

Is the expected behavior not reuse the current children states? Am I misunderstanding something?

Tap on the "Pos. 1" button to see it happening. The tile subtitles represent the hashcode of their state.
