### ISSUE TITLE
ExpansionTile optional trailing icon

### ISSUE THREAD

**Issue by pauldemarco** [flutter/flutter#11890]
ExpansionTile has a trailing icon that rotates when expanded.
Unfortunately, I need this space for some other functionality.
It would be nice if this trailing icon could be optional, and the expansion was only triggered by a click elsewhere on the tile.

**Comment by Hixie** [comment]
We probably won't have the chance to implement this ourselves in the near future but we would definitely accept patches.

My recommendation would be to have a "trailing" argument which defaults to the current behaviour but can be set to a new widget to override the behaviour.
