### ISSUE TITLE
Slider text label color on theme change is not updated

### ISSUE THREAD

**Issue by MaxYablochkin** [flutter/flutter#118955]
#91605

The color of the text in valueIndicatorTextStyle is displayed incorrectly when changing the theme before the first drag of the slider. Similar issue with color [here](https://github.com/material-foundation/flutter-packages/issues/303)

https://user-images.githubusercontent.com/102767277/213883762-a640b28d-1a39-40cc-8c78-9d57826461aa.mp4

**Comment by exaby73** [comment]
Hello @MaxYablochkin. Thank you for filing this issue. Can you please provide the following information?

- A [complete and minimal, reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example). Ideally, a single `main.dart` file that can be run directly.
- The output of `flutter doctor -v`

Please provide the information in the form of text. See how to make collapsible sections with Markdown [here](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-collapsed-sections).

**Comment by exaby73** [comment]
## Triage report

I can reproduce this issue with `Master (3.7.0-24.0.pre.87)`. On changing the theme, the label color does not change until first update. Here's an updated code sample

<details><summary>Code Sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatefulWidget {
  const MyApp({super.key});

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  var themeMode = ThemeMode.light;

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Demo sample',
      themeMode: themeMode,
      theme: ThemeData(brightness: Brightness.light, useMaterial3: true),
      darkTheme: ThemeData(brightness: Brightness.dark, useMaterial3: true),
      home: SliderScreen(
        onThemeChange: () => setState(
          () => themeMode =
              themeMode == ThemeMode.light ? ThemeMode.dark : ThemeMode.light,
        ),
      ),
    );
  }
}

class SliderScreen extends StatefulWidget {
  const SliderScreen({super.key, required this.onThemeChange});

  final VoidCallback onThemeChange;

  @override
  State<SliderScreen> createState() => _SliderScreenState();
}

class _SliderScreenState extends State<SliderScreen> {
  double sliderValue = 0.0;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Sliders'),
        actions: [
          IconButton(
            onPressed: () => widget.onThemeChange(),
            icon: const Icon(Icons.view_day),
          )
        ],
      ),
      body: ListView.builder(
        itemCount: 10,
        itemBuilder: (context, index) {
          return Slider(
            value: sliderValue,
            onChanged: (double value) => setState(() => sliderValue = value),
            label: sliderValue.toDouble().toString(),
            divisions: 10,
          );
        },
      ),
    );
  }
}
```

</details>

<details><summary><code>flutter doctor -v</code> (Master)</summary>

```
[!] Flutter (Channel master, 3.7.0-24.0.pre.87, on macOS 13.1 22C65 darwin-arm64, locale en-US)
    • Flutter version 3.7.0-24.0.pre.87 on channel master at /Users/nabeelparkar/fvm/versions/master
    ! Warning: `dart` on your path resolves to /opt/homebrew/Cellar/dart/2.18.6/libexec/bin/dart, which is not inside your current Flutter SDK checkout at /Users/nabeelparkar/fvm/versions/master. Consider adding /Users/nabeelparkar/fvm/versions/master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c35efdaa68 (6 hours ago), 2023-01-24 02:57:00 +0100
    • Engine revision 7d3233d26d
    • Dart version 3.0.0 (build 3.0.0-154.0.dev)
    • DevTools version 2.20.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nabeelparkar/Library/Android/sdk/
    • Platform android-33, build-tools 33.0.0
    • ANDROID_SDK_ROOT = /Users/nabeelparkar/Library/Android/sdk/
    • Java binary at: /Users/nabeelparkar/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/213.7172.25.2113.9123335/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /Applications/Brave Browser.app/Contents/MacOS/Brave Browser

[✓] Android Studio (version 2021.3)
    • Android Studio at /Users/nabeelparkar/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/213.7172.25.2113.9123335/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.3.1)
    • IntelliJ at /Users/nabeelparkar/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 71.3.6
    • Dart plugin version 223.8214.16

[✓] IntelliJ IDEA Ultimate Edition (version 2022.3.1)
    • IntelliJ at /Users/nabeelparkar/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/223.8214.52/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.74.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.56.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.1 22C65 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Brave Browser 109.1.47.171

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

</details>

**Comment by rydmike** [comment]
Nice, I had seen this issue too, but had not found the time to report it yet. Nice to see it already reported and a fix landed. Thanks and great work @xu-baolin 

I will verify my use case against master too, confirm that it is fixed and that I don't see the issue anymore as well. Ping @TahaTesser, this seems to be the issue we talked about, but that I did not have time to report.

**Comment by TahaTesser** [comment]
@rydmike 
Yep, I was surprised at how simple the fix was. Thanks, @xu-baolin!

**Comment by rydmike** [comment]
I tested it as well now @TahaTesser. The issue described here, where the ValueIndicator color did not update to new theme, until you moved it appears to be gone. However, a minor related issue seems to remain. When I saw them both prior to this fix on macOS desktop earlier, I was unsure if it was same issue or different issues I observed. Seems like it were a different issues.

Here is what I found @xu-baolin:

If you leave the Slider indicator open during a theme change, it does not lerp animate with the rest of the theme change. It jumps to its new theme color after the new theme has completed its animation.

Additionally, if I use rapid enough theme changes, the ValueIndicator may get stuck in one of its older theme colors. But at least now it gets the new correct color as soon as you move it, that did not work before. It took quite a bit of moving it around or even close and open it again before.

You can see the behavior I describe above in the attached video:

https://user-images.githubusercontent.com/39990307/219035418-e52b2b9c-ad98-4ec4-b343-fd7248e0bea3.mov

(Recording made with Channel master, 3.8.0-12.0.pre.72)

To be honest though, how often do users leave a value indicator open while rapidly changing theme multiple times, which seemed to be needed to see the issue. 

On first changes it was only showing the issue where it did not change until ThemeData had completed its animation. I cut many of those changed out in the beginning of the video where it worked reasonably well when using more realistically timed intervals between theme changes. 

It might be so that if you change to a new theme fast enough, before previous theme has completed its animation, that this is the needed condition for the value indicator to get stuck in an older theme color. I was unable to determine if that is the trigger, but it seems plausible.

**Comment by xu-baolin** [comment]
> I tested it as well now @TahaTesser. The issue described here, where the ValueIndicator color did not update to new theme, until you moved it appears to be gone. However, a minor related issue seems to remain. When I saw them both prior to this fix on macOS desktop earlier, I was unsure if it was same issue or different issues I observed. Seems like it were a different issues.
> 
> Here is what I found @xu-baolin:
> 
> If you leave the Slider indicator open during a theme change, it does not lerp animate with the rest of the theme change. It jumps to its new theme color after the new theme has completed its animation.
> 
> Additionally, if I use rapid enough theme changes, the ValueIndicator may get stuck in one of its older theme colors. But at least now it gets the new correct color as soon as you move it, that did not work before. It took quite a bit of moving it around or even close and open it again before.
> 
> You can see the behavior I describe above in the attached video:
> 
> (Recording made with Channel master, 3.8.0-12.0.pre.72)
> 
> To be honest though, how often do users leave a value indicator open while rapidly changing theme multiple times, which seemed to be needed to see the issue.
> 
> On first changes it was only showing the issue where it did not change until ThemeData had completed its animation. I cut many of those changed out in the beginning of the video where it worked reasonably well when using more realistically timed intervals between theme changes.
> 
> It might be so that if you change to a new theme fast enough, before previous theme has completed its animation, that this is the needed condition for the value indicator to get stuck in an older theme color. I was unable to determine if that is the trigger, but it seems plausible.

Hi, Could you write a simple code to reproduce this issue? Glad to investigate it.

**Comment by rydmike** [comment]
Yes of course. I have it on my to-do list with a bunch of other minor M3 component issues I have not had time to report yet, mostly minor issues like this one. I'll tag you when I do.

This one should be possible to demo with a fairly simple sample. I want to do it also to make sure it is not coming from the app used above.
