### ISSUE TITLE
[go_router_builder] Allow returning null from build() method. 

### ISSUE THREAD

**Issue by iLoveDocs** [flutter/flutter#118978]
## Use case
If I want to return an existing (current) route based on a condition, I can't do that as the `build()` method doesn't support returning `Widget?`. 

Take a look at this code: 

```dart
class FooRoute extends GoRouteData {
  final bool condition;
  FooRoute(this.condition);
  
  @override
  Widget build(BuildContext context, GoRouterState state) {
    return condition ? FooScreen() : null; // I wish this was possible!
  }
}
```

I'm performing my logic inside `build()` and I want to return the existing widget if the `condition` was false. For example: 

```dart
void func() {
  FooRoute(true).go(context); // Navigates to the `FooScreen`. All good.
  FooRoute(false).go(context); // This should do nothing. 
}
```

**Comment by chunhtai** [comment]
can you do
```dart
if (condition) {
  FooRoute().go(context)
}
```

**Comment by iLoveDocs** [comment]
Yes, I can do that. But for the sake of simplicity, I created this basic example. But in practice, I am passing some `$extra` data to the `FooRoute` and using that data, I need to decide if I should let the user navigate or not. 

That code is few lines long and I call `FooRoute(...).go(context)` from different places in my app. So, I was thinking if that entire logic can be places inside the `build()`.

**Comment by dancamdev** [comment]
My 2-cents on this issue, this should be handled by a redirect instead.

```Dart
class FooRoute extends GoRouteData {
  
  @override
  String? redirect(BuildContext context, GoRouterState state) {
    final condition = state.extra as bool;
    if (!condition) return BarRoute.location;
    return null;
  }

  @override
  Widget build(BuildContext context, GoRouterState state) {
    /// The actual Foo widget.
  }
}
```

**Comment by iLoveDocs** [comment]
@dancamdev 

Sorry for the late reply. If you return `null` from `redirect`, it simply means you want to navigate to `FooRoute`. However, in my question, I want to stay on the current route, whichever that may be.

**Comment by iLoveDocs** [comment]
@chunhtai, I apologize, but that solution didn't help.

Is there a way to prevent a route from navigating to its designated destination? 
For example, if I do `FooRoute().go(context)`, I'd like to remain on the current route (whichever that might be) rather than navigating to the `FooRoute`.

 I tried your suggestion, but it wasn't successful. I encountered the following error:
> Match error found during build phase Exception. 

```dart
class FooRoute extends GoRouteData {
  @override
  String? redirect(BuildContext context, GoRouterState state) {
    return state.uri.toString();
  }

  @override
  Widget build(BuildContext context, GoRouterState state) {
    return FooScreen(); 
  }
}
```

**Comment by chunhtai** [comment]
it should work, do you have full repro and the full error message?

**Comment by iLoveDocs** [comment]
@chunhtai I've recently updated both `go_router` and `go_router_builder`:
```yaml
go_router: ^10.1.0
go_router_builder: ^2.3.0
```

While I no longer encounter errors after the update, it hasn't resolved the initial issue I was facing. Specifically, when I execute `FooRoute().go(context)`, it navigates me to the `FooScreen`. However, my intention was to prevent the navigation entirely.

Here's a snippet of my `FooRoute` class for clarity:
```dart
class FooRoute extends GoRouteData {
  @override
  String? redirect(BuildContext context, GoRouterState state) {
    return state.uri.toString(); // Has no impact. 
  }

  @override
  Widget build(BuildContext context, GoRouterState state) {
    return FooScreen();
  }
}
```

**Comment by iLoveDocs** [comment]
Yes, using the current location as a parameter was indeed the only solution. Unfortunately, I don't have access to the current location for some reason, which makes passing it in the parameter impossible. I was hoping there might be a more elegant solution or a property that I'm overlooking, which would provide me with the current route. 

By the way, I find this line a bit contradictory ;)

> The reason we should not return null widget to prevent redirect is there may be use case that you do want to return null widget as the page content

Should we consider closing this issue then, given that there are no longer plans to add such a property/functionality?

**Comment by chunhtai** [comment]
> By the way, I find this line a bit contradictory ;)

Some widgets like scaffold  are built to be able to accept null as its child widget, so It is valid for a widget build to return null sometimes.

Let's say we allow the GoRouterWidgetBuilder to be able to return null for redirecting back to original route.

Imagine for someone have two route `/a/b` and `/a/c`
where `/a` is a shell route with scaffold, the the subroute will build in the scaffold.body

in `/a/b` they want to build some thing in the body, where in `/a/c` they want to body to remain empty. In that case, they would try to return null in `/a/c`'s builder and got redirect unexpectedly.

I will closing this bug.

**Comment by iLoveDocs** [comment]
Hi @chunhtai 

> in /a/b they want to build some thing in the body, where in /a/c they want to body to remain empty. In that case, they would try to return null in /a/c's builder and got redirect unexpectedly.

I'm having difficulty understanding the example you provided. Even if we want the body to remain empty in `/a/c`, we would still need to return a widget. Returning empty from the `builder` is an error at the moment. However, if we were to allow returning `null` from the `builder`, it could solve my concern of maintaining the current route instead of navigating elsewhere. Here's an illustrative example similar to the one provided in the [repo](https://github.com/flutter/packages/blob/main/packages/go_router/example/lib/shell_route.dart). 

```dart
final GoRouter router = GoRouter(
  initialLocation: '/a',
  routes: [
    ShellRoute(
      builder: (_, __, child) => ScaffoldWithNavBar(child: child),
      routes: [
        GoRoute(
          path: '/a',
          builder: (_, __) => Scaffold(appBar: AppBar(title: Text('Screen-A'))),
          routes: <RouteBase>[
            GoRoute(
              path: 'details',
              builder: (_, __) => DetailsScreen(label: 'A'),
            ),
          ],
        ),
        GoRoute(
          path: '/b',
          builder: (_, __) => null, // <-- Allow null (currently an error)
          routes: <RouteBase>[
            GoRoute(
              path: 'details',
              builder: (_, __) => DetailsScreen(label: 'B'),
            ),
          ],
        ),
      ],
    ),
  ],
);
```

I don't foresee any problems with returning `null` from the `builder`. This would simply indicate that no navigation should occur and that the user should stay on their current route.
