### ISSUE TITLE
[Impeller] src and dst are reversed for advanced blends in FilterContents::MakeBlend Constructor

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#118903]
I would expect that:

```
ColorFilterContents::MakeBlend(
      blend_mode_,
      {FilterInput::Make(dst_contents), FilterInput::Make(src_contents_)});
```

Should behave the same with a pipeline blend and an advanced  blend. However in https://github.com/flutter/engine/pull/38985 and https://github.com/flutter/engine/pull/38335 I've observed that I actually need to switch the order to match Skia's rendering. This doesn't appear to happen with regular canvas drawing, so we must either be using a different constructor or compensating elsewhere.

**Comment by jonahwilliams** [comment]
See: https://github.com/flutter/engine/blob/master/impeller/entity/entity_pass.cc#L533-L536

It doesn't look like we ever use FilterContents::MakeBlend for pipeline blends. Is this order intentional? I would expect the vector encoding to be dst, src and not src, dst

**Comment by bdero** [comment]
I think I landed the blend filter with source being first and destination being second, and then missed this detail when reviewing the color filter which came into existence later. I agree we should choose one order and go with it. I don't have a strong preference around which order we choose. Any reason one is less confusing than the other?

**Comment by jonahwilliams** [comment]
The construct accepts N FilterInputs, in that case it would make sense to me to have dst, src, src, src, et cetera right? I don't have a strong opinion as long as it is consistent and documented

**Comment by bdero** [comment]
> The construct accepts N FilterInputs, in that case it would make sense to me to have dst, src, src, src, et cetera right?

SGTM, that seems to me like the most intuitive behavior. That's also consistent with where the blend shaders themselves ended up
