### ISSUE TITLE
Make it possible to take a picture (and have it saved)

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#119]
<a href="https://github.com/eseidelGoogle"><img src="https://avatars.githubusercontent.com/u/11857803?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [eseidelGoogle](https://github.com/eseidelGoogle)**
_Wednesday Aug 05, 2015 at 19:32 GMT_
_Originally opened as https://github.com/flutter/engine/issues/468_

----

For Fitness App 0.1

**Comment by NatoBoram** [comment]
For anyone stumbling upon this from a Google search : 
* https://pub.dartlang.org/packages/camera
