### ISSUE TITLE
[CP] Switch builds over to use iOS-16 devices

### ISSUE THREAD

**Issue by yusuf-goog** [flutter/flutter#119029]
### issue_link

https://github.com/flutter/flutter/issues/119014

### Commit Hash

f3a8ef34ec6b231d641e2c3d98c5ae21fb559deb

### Target

stable

### pr_link

https://github.com/flutter/flutter/pull/118963

### Impacted Users

Devicelab builds

### Impact Description

We have upgraded devicelab testbeds to iPhone 11 devices from iPhone 6s. 

As per quorum, it would be beneficial to roll forward all branches to use the new iPhone 11 devices (iOS-16) rather than require running on testbeds with the older iPhone 6s.

Maintaining capacity for the older devices will split our fleet and impact build times for all releases. 

Stakeholders are confident that if all ios tests pass on the new devices, it would be enough validation to switch over the branch permanently.

### Workaround

Maintain dual iPhone devices in lab, which impacts total capacity across our builds.

### Risk

low

### Test Coverage

yes

### Validation Steps

All ios tests pass on the new build.

If builds fail, we can roll back the change, which would revert all impact.

**Comment by CaseyHillers** [comment]
\cc @jmagman @zanderso can you review this CP request?

**Comment by zanderso** [comment]
CP lgtm. In this case, iOS 16 has been out for a long time, and devices all the way back to the 11s we have in the lab will have auto-updated, so to match the configuration that the large majority of iOS users will be running, we should be testing the 3.7 release branch on the iOS 16 devices.

**Comment by XilaiZhang** [comment]
Looks like Zach approved, adding the cp: approved label now

**Comment by jmagman** [comment]
Agree with Zach, let me know if you see any issues with test failures!

**Comment by CaseyHillers** [comment]
FYI @yusuf-goog this has landed in the release, and you're free to remove the iPhone 6's from the lab. Thank you for your help with this!

**Comment by yusuf-goog** [comment]
no, thank you! this will bring back much needed capacity.
