### ISSUE TITLE
Url launcher don't add plus after special code

### ISSUE THREAD

**Issue by skibos** [flutter/flutter#119056]
Hi. 

I have problem with https://github.com/flutter/plugins/tree/main/packages/url_launcher on android 12 and android 13. When I put         

```
final Uri anonymousCallUri = Uri(
          scheme: "tel",
          path: "#31#+48111111111"
        );
        
launchUrl(anonymousCallUri);
```

"+" is not added to the input in phone application. Its redirected correctly but in input there is #31#48111111111

It only behaves like this in real phone, in android emulator everything works correctly but in real phone + is not added. CompileSdkVersion is 33, Target is for 30. I added to manifest:

```
    <queries>
        <intent>
            <action android:name="android.intent.action.VIEW" />
            <data android:scheme="tel" />
        </intent>
    </queries>
```
I tried also add between + and number " " but it also doesnt work

**Comment by stuartmorgan** [comment]
All `url_launcher` is doing is handing the URL off to the OS for routing to a handler; if you believe the receiving application is handling the URL improperly (it's not clear to me what you expect the + to do there) you'd need to report it to the developer of that application.

Closing as this is beyond the control of the plugin.
