### ISSUE TITLE
[web] Optimize LUCI build by reusing build artifacts across platform-specific drones

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#119036]
Currently, for each platform (Windows, Linux, macOS) we build every artifact from sources, then run tests. This has a few problems:

* We're not yet setup to build wasm bits from sources on Windows without WSL, and this prevents us from running tests on Windows against wasm code (new CanvasKit, Skwasm).
* This is wasteful because we compile all the C++ code, dart2js, and dart2wasm code 3 times, even though the output is bit for bit identical across all platforms.

## Request

Add support for compiling all C++ to wasm, dart2js, and dart2wasm code on a single Linux bot (the choice of Linux is simply because it's faster for the price, but otherwise it doesn't matter), then run tests on platform-specific drones.

## Expected impact

This will enable running all tests on Windows bots, e.g. we can add Edge tests (currently we use Chromium as a proxy for Edge, but that's limiting because there are some corner cases in accessibility and text input in Edge).

We will use much less macOS and Windows infra capacity because it only takes a couple of minutes to run tests (as opposed to compiling all the code, which takes multiple tens of minutes).

**Comment by godofredoc** [comment]
This can be achieved with an engine_v2 build configuration file. A few months ago I landed a few changes to use the sharding module and separating the recipe logic into build/test components(https://flutter-review.git.corp.google.com/c/recipes/+/35860).

Docs:
* https://flutter.dev/go/engine-build-definition-language
* https://flutter.dev/go/engine-v2-recipes
* https://flutter.dev/go/gn-ninja-engine-artifacts

Previous work:

* [web_engine config file](https://cs.opensource.google/flutter/engine/+/main:ci/builders/web_engine.json)

When I was testing that config file there was some complexity related to felt expecting files in specific locations along the source code. Not sure how much progress has been there but if we can can generate a self contained test artifact(a zip file with everything required to run the tests) the sharding to multiple platform bots can be delegated to the engine v2 build system.

**Comment by CaseyHillers** [comment]
@keyonghan as FYI. If you're working on build+test infra, the web team has an interesting use case here. They want to build everything on a cheap linux vm, but then do the test on every possible platform+browser.

**Comment by eyebrowsoffire** [comment]
Yes, this is done!
