### ISSUE TITLE
We don't recognize Hebrew

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#11907]
When you pick the Hebrew locale on Android we don't switch to Hebrew.

**Comment by HansMuller** [comment]
Android (Java really) uses the old locale code for hebrew "iw", see http://bugs.java.com/bugdatabase/view_bug.do?bug_id=4140555

The material translations should work for both.

**Comment by Hixie** [comment]
We should automatically convert `iw` to `he` (Hebrew), `ji` to `yi` (Yiddish), and `in` to `id` (Indonesian). They were all replaced in 1989. Not sure exactly where to put this conversion. Maybe in Locale itself? Have `languageCode` (and operator==) return (or use) the value with this mapping applied, and have a new property `originalLanguageCode` that returns the one that was provided to the constructor?

**Comment by Hixie** [comment]
The code that does this would be implementing https://www.ietf.org/rfc/rfc1766.txt, which is why I think it belongs at that low level.

**Comment by HansMuller** [comment]
We do recognize Hebrew on Android as of https://github.com/flutter/flutter/pull/12021 however I'll leave this issue open until we've moved the fix to the Locale object itself.
