### ISSUE TITLE
Null check operator used on a null value in DWDS BatchedExpressionEvaluator._evaluateBatch()

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#119084]
on beta/3.7.0-1.5.pre, package:dwds version 16.0.2

```
_CastError: Null check operator used on a null value
at BatchedExpressionEvaluator._evaluateBatch(batched_expression_evaluator.dart:125)
at <asynchronous gap>(async)
```

**Comment by christopherfujino** [comment]
cc @elliette

**Comment by elliette** [comment]
This is already fixed at head. The null check operator was on `list.objectId!`, which was removed in https://github.com/dart-lang/webdev/pull/1884. We now are handling the case where it is null, see: https://github.com/dart-lang/webdev/blame/master/dwds/lib/src/services/batched_expression_evaluator.dart#L132-L137

If we get more cases of this we could potentially do a hotfix.

**Comment by christopherfujino** [comment]
> This is already fixed at head. The null check operator was on `list.objectId!`, which was removed in [dart-lang/webdev#1884](https://github.com/dart-lang/webdev/pull/1884). We now are handling the case where it is null, see: https://github.com/dart-lang/webdev/blame/master/dwds/lib/src/services/batched_expression_evaluator.dart#L132-L137
> 
> If we get more cases of this we could potentially do a hotfix.

Thanks, that sounds good to me.

**Comment by yjbanov** [comment]
Making it a P2 because it looks like a bad crash, and also so we prioritize rolling the fix into the Flutter SDK asap.

**Comment by yjbanov** [comment]
@christopherfujino would you be interested in getting this over the finish line?

**Comment by christopherfujino** [comment]
> @christopherfujino would you be interested in getting this over the finish line?

SGTM

**Comment by christopherfujino** [comment]
@elliette could you produce dwds 16.0.4 with this fix? If so, I can cherry pick it to flutter stable.

**Comment by christopherfujino** [comment]
Closing this as dwds rolled on master and this will be fixed with the next stable hotfix release: https://github.com/flutter/flutter/pull/119745
