### ISSUE TITLE
Engine -> Framework roll failing on missing artifacts

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#119069]
See the roll here https://github.com/flutter/flutter/pull/119067 failing due to:
```
Failed to download https://storage.googleapis.com/flutter_infra_release/flutter/7f38d0d4f5c2538295f3bbbc42e15ad75b191ae1/windows-x64/windows-x64-flutter.zip. Ensure you have network connectivity and then try again.
           Exception: 404
```

The changes to Windows artifact locations/paths needs a soft transition in the Flutter tool. (Or don't change the locations.)

**Comment by zanderso** [comment]
I reverted the recipe change here https://flutter-review.git.corp.google.com/c/recipes/+/38240.

**Comment by zanderso** [comment]
Keeping an eye on this roll https://github.com/flutter/flutter/pull/119070, which I think started after the recipe revert.

**Comment by christopherfujino** [comment]
> cc @christopherfujino

thanks!

**Comment by zanderso** [comment]
The roll is still failing. We will need a commit to the engine repo to trigger building and uploading new Windows artifacts following the recipe revert.

**Comment by godofredoc** [comment]
The tool expects the file to be in `7f38d0d4f5c2538295f3bbbc42e15ad75b191ae1/windows-x64/windows-x64-flutter.zip` and it was uploaded to `7f38d0d4f5c2538295f3bbbc42e15ad75b191ae1/windows-x64-debug/windows-x64-flutter.zip`

**Comment by godofredoc** [comment]
I see what the issue is, I removed:

```
-    # Legacy; remove once Flutter tooling is updated to use the -debug location.
-    PackageWindowsDesktopVariant(api, 'host_debug', 'windows-x64')
```

Adding it back and ensure that tool is migrated to the debug location.

**Comment by ricardoamador** [comment]
Thank you @godofredoc!

**Comment by godofredoc** [comment]
Reland with the fix: https://flutter-review.googlesource.com/c/recipes/+/38132

**Comment by zanderso** [comment]
An engine roll landed, so I'll close this. We can follow up on the recipe reland with a separate issue or PR.
