### ISSUE TITLE
[cocoon] Use PR number buildset (pr/git/{number}) instead of commit buildset (sha/git/{sha}) when calling getTryBuilds in rescheduleUsingCheckRunEvent

### ISSUE THREAD

**Issue by nehalvpatel** [flutter/flutter#119079]
While the current method works, it could be non-deterministic in some edge cases. We need to check if the check run event includes the PR number. If it doesn't, we could use the new `findMatchingPullRequest` method introduced in https://github.com/flutter/cocoon/pull/2402.

Snippet from example build JSON response:
```json
"tags": [
  {
    "key": "buildset",
    "value": "pr/git/118701"
  },
  {
    "key": "buildset",
    "value": "sha/git/415bd658ace8571e51c9b4b5ce37a32367afa6c7"
  },
```

Link to file: https://github.com/flutter/cocoon/blob/main/app_dart/lib/src/service/luci_build_service.dart

**Comment by keyonghan** [comment]
This has been implemented to use PR number.
