### ISSUE TITLE
Failed to set vm service URI: ext.flutter.connectedVmServiceUri: 

### ISSUE THREAD

**Issue by fidelmak** [flutter/flutter#119038]
Failed to set VM service URI: ext. flutter.connectedVmServiceUri:
this displays a white background while using Chrome(web) but displays perfectly when connected to internet 
please what could cause this?

**Comment by darshankawar** [comment]
@fidelmak 


> Failed to set VM service URI: ext. flutter.connectedVmServiceUri:

Can you provide entire log ?



> this displays a white background while using Chrome(web) but displays perfectly when connected to internet

Are you saying that the above log is shown when you are not connected to internet and then you try to run your app on web platform ?

Can you provide `flutter doctor -v`, minimal code sample along with steps to replicate ?

**Comment by fidelmak** [comment]
yes, the log is shown when not connected to the internet

**Comment by darshankawar** [comment]
> Can you provide entire log ?



> Can you provide `flutter doctor -v`, minimal code sample along with steps to replicate ?

Please provide above requested details to properly address the issue.
