### ISSUE TITLE
Hide Application when outside the desktop application is clicked

### ISSUE THREAD

**Issue by Sushma-Shrestha** [flutter/flutter#119047]
I made an utility/tray application using flutter with size around 400 x 600 and i want it to hide when i click outside the application(like windows, another application, etc.). How can we do this? I researched quite some time but i could not get the answer to this.
I wants the solution to be workable in windows, MacOS, and linux.
It's ok if the solution is different for different platform.

**Comment by sabin26** [comment]
If I understood correctly, you simply want to minimize the app when it loses focus.

You can use [window_manager](https://pub.dev/packages/window_manager) package to achieve your goal. 

1. You need to listen to window events.
  - Visit this section: [Listening events](https://pub.dev/packages/window_manager#listening-events)
  - Use the following piece of code.
 ```
@override
  void onWindowBlur() {
    // Emitted when the window loses focus.
  }
```
2. Minimize the window.
`await windowManager.minimize();`

**Comment by danagbemava-nc** [comment]
Hi @Sushma-Shrestha, does the plugin in https://github.com/flutter/flutter/issues/119047#issuecomment-1401545382 work for you?
