### ISSUE TITLE
[CP] [Impeller] Check the correct stencil coverage when deciding whether to elide a restore

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#119072]
### issue_link

N/A

### Commit Hash

https://github.com/flutter/engine/commit/730e88fb67878fbfdb9bb60545fecdb2990bc9fd

### Target

stable

### pr_link

https://github.com/flutter/engine/pull/39096

### Impacted Users

Impeller users

### Impact Description

The fix from https://github.com/flutter/engine/pull/38964 was incomplete, and left open the possibility that draw calls could be improperly culled. See screenshots on https://github.com/flutter/engine/pull/39023.

### Workaround

There is no workaround.

### Risk

low

### Test Coverage

yes

### Validation Steps

Rendering of an internal app is correct.

**Comment by zanderso** [comment]
cc @chinmaygarde @bdero for approval

**Comment by chinmaygarde** [comment]
lgtm
