### ISSUE TITLE
Output of Flutter tool, when iOS can't be built, doesn't fit 80 columns

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#11917]
Terminals seem to default to 80 chars wide, however the error message for when flutter tool can't build the iOS app is wider the 80 chars:

<img width="578" alt="screen shot 2017-09-03 at 2 10 09 pm" src="https://user-images.githubusercontent.com/5479/30002421-bdd46938-90b1-11e7-95d0-a033e012df6b.png">

**Comment by Hixie** [comment]
Long term we should implement automatic detection of the width and wrap to that width. (We need `args` to do that too.)
