### ISSUE TITLE
[Impeller] Add additional metadata for runtime shaders rather than relying on ordering.

### ISSUE THREAD

**Issue by iskakaushik** [flutter/flutter#119173]

**Comment by iskakaushik** [comment]
cc: @jonahwilliams

**Comment by jonahwilliams** [comment]
Some more context: currently we rely on the order of uniforms in the IPLR file to implicitly contain the mapping from the source shader inputs to the compiled shader. This doesn't actually hold for the metadata for MSL so we need to re-order them.
