### ISSUE TITLE
How to animate Snackbar using animation property ? 

### ISSUE THREAD

**Issue by 1Krishna16** [flutter/flutter#119160]
I have been trying to provide a custom animation to the snackbar, but no luck , i can't customize the default fade in and fade out transition unfortunately 
```
ScaffoldMessenger.of(context).showSnackBar(SnackBar(
                animation:  // here
     ));
```
There is no example even in the docs. Could you please add the animation example in the docs, to customize the default fade in and fade out animation of the snackbar.

There is package called [another_flushbar](https://pub.dev/packages/another_flushbar), it supports all types of slides and animation.
But it doesn't support fadein and fadeout animation. How can i achieve all types of animation in flutter's snackbar ?

**Comment by darshankawar** [comment]
@1Krishna16 Thanks for the report.
Have you already checked https://pub.dev/packages/animated_snack_bar to see if it serves your purpose ?

Also, your use case seems similar to https://github.com/flutter/flutter/issues/68360 in which you can follow-up for further updates.

**Comment by 1Krishna16** [comment]
@darshankawar Thanks for the reply,

[animated_snack_bar](https://pub.dev/packages/animated_snack_bar) doesn't serve the purpose unfortunately.

Ad the #68360 doesn't speak about customizing the animation.

**Comment by darshankawar** [comment]
Thanks for the feedback. I see that you seem to have found a [solution](https://stackoverflow.com/a/75237540) on how to achieve it using third party plugin.
Also check if [this](https://github.com/flutter/flutter/issues/100782) issue is relevant with your case.
