### ISSUE TITLE
ios_debug_symbol_doctor not correctly detecting unfetched debug symbols

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#119197]
For example: https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_ios%20flutter_gallery__transition_perf_e2e_impeller_ios/2315/overview

Note the output:

```
    "error" : {
      "code" : -10,
      "failureReason" : "",
      "description" : "iPhone 11 is busy: Fetching debug symbols for iPhone 11",
      "recoverySuggestion" : "Xcode will continue when iPhone 11 is finished.",
      "domain" : "com.apple.platform.iphoneos"
    },
```

**Comment by christopherfujino** [comment]
https://github.com/flutter/cocoon/blob/main/device_doctor/lib/src/ios_debug_symbol_doctor.dart#L163

**Comment by jmagman** [comment]
`iPhone is busy` should handle `iPhone 11 is busy` aka `{name} is busy`

**Comment by christopherfujino** [comment]
> `iPhone is busy` should handle `iPhone 11 is busy` aka `{name} is busy`

Writing a PR now, I'll add you as a reviewer for the exact regex
