### ISSUE TITLE
[web] PathUrlStrategy doesn't work with nested paths

### ISSUE THREAD

**Issue by Gorniv** [flutter/flutter#119111]
Steps to Reproduce
Channel master/stable

Set PathUrlStrategy on default project
Run locally and try to navigate to /a/b
Error: The script has an unsupported MIME type ('text/html').

But if you change entry point script in index.html from

<script>
  window.addEventListener('load', function(ev) {
    // Download main.dart.js
    _flutter.loader.loadEntrypoint({
      serviceWorker: {
        serviceWorkerVersion: serviceWorkerVersion,
      },
      onEntrypointLoaded: function(engineInitializer) {
        engineInitializer.initializeEngine().then(function(appRunner) {
          appRunner.runApp();
        });
      }
    });
  });
</script>
to

<script src="main.dart.js" type="application/javascript"></script>
then it works as expected

problem with:
```
class FlutterTrustedTypesPolicy {
    /**
     * Constructs the policy.
     * @param {[RegExp]} validPatterns the patterns to test URLs
     * @param {String} policyName the policy name (optional)
     */
    constructor(validPatterns, policyName = "flutter-js") {
      const patterns = validPatterns || [
        /\.dart\.js$/,
        /^flutter_service_worker.js$/
      ];
      if (window.trustedTypes) {
        this.policy = trustedTypes.createPolicy(policyName, {
          createScriptURL: function(url) {
            const parsed = new URL(url, window.location);
            const file = parsed.pathname.split("/").pop();
            const matches = patterns.some((pattern) => pattern.test(file));
            if (matches) {
              return parsed.toString();
            }
            console.error(
              "URL rejected by TrustedTypes policy",
              policyName, ":", url, "(download prevented)");
          }
        });
      }
    }
  }
```
fix:             `const parsed = new URL(url, document.baseURI);`

**Comment by darshankawar** [comment]
@Gorniv 
This seems to have been [already fixed](https://github.com/flutter/flutter/pull/118684) just yesterday :) and should be available on latest master. So try to switch to it and try your case again to see it working.

**Comment by Gorniv** [comment]
Fixed in master! Sorry)
