### ISSUE TITLE
W/Parcel  (21844): Expecting binder but got null! - Flutter 3.7.0

### ISSUE THREAD

**Issue by ermirshabani1** [flutter/flutter#119128]
After upgrading flutter to 3.7.0 from 3.3.7, I get this warning every time app starts.
IDK if this is from a package or from flutter, does anyone has the same experience? 

![image](https://user-images.githubusercontent.com/110819389/214557915-164da600-1c33-427b-b43d-a855ce2d5f1a.png)

**Comment by danagbemava-nc** [comment]
Hi @ermirshabani1, that is a message from android itself. 
It's not going to do anything to your app so it is safe to ignore it. 

It has always been there, it didn’t start with flutter 3.7.0. 

I'll be closing this as it not as a flutter issue. 

Thank you

**Comment by ermirshabani1** [comment]
> 
Hey @danagbemava-nc! Thanks for the answer.
