### ISSUE TITLE
RenderObjectElement.insertChildRenderObject() is deprecated.

### ISSUE THREAD

**Issue by kmarellapudi** [flutter/flutter#119118]
Rather than overriding insertChildRenderObject() in your RenderObjectElement subclass, override insertRenderObjectChild() instead, and DON'T call super.insertRenderObjectChild(). If you're implementing a new RenderObjectElement, you should override/implement insertRenderObjectChild(), moveRenderObjectChild(), and removeRenderObjectChild().

Stacktrace ::

The relevant error-causing widget was: 
  HomeWidget HomeWidget:file:///Users/kameshmarellapudi/development/dizest_flutter/lib/pages/landing_page.dart:28:5
When the exception was thrown, this was the stack: 
#2      Element.rebuild.<anonymous closure> (package:flutter/src/widgets/framework.dart:4606:14)
#3      Element.rebuild (package:flutter/src/widgets/framework.dart:4609:6)
#4      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2667:19)
#5      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:882:21)
#6      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:378:5)
#7      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1175:15)
#8      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1104:9)
#9      SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1015:5)
#10     _invoke (dart:ui/hooks.dart:148:13)
#11     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:318:5)
#12     _drawFrame (dart:ui/hooks.dart:115:31)

The following assertion was thrown while rebuilding dirty elements:
'package:flutter/src/widgets/framework.dart': Failed assertion: line 4606 pos 14: 'owner!._debugCurrentBuildTarget == this': is not true.

Flutter Version :: 

    • Flutter version 3.3.10 on channel stable at /Users/kameshmarellapudi/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (6 weeks ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/kameshmarellapudi/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[!] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio 2.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] IntelliJ IDEA Ultimate Edition (version 2022.3.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 71.3.6
    • Dart plugin version 223.8214.16

[✓] Connected device (3 available)
    • iPhone 14 Pro (mobile) • D9D3DA56-1621-44B1-B686-F4AFCD38013D • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-2 (simulator)
    • macOS (desktop)        • macos                                • darwin-x64     • macOS 12.6.2 21G320 darwin-x64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 109.0.5414.87

[✓] HTTP Host Availability
    • All required HTTP hosts are available

**Comment by exaby73** [comment]
Hello @kmarellapudi. Looks like you're using 3.3.10. 3.7.0 was just released. Could you confirm if this issue is still prevalent on the latest stable version. If so, please provide a [complete and minimal, reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that I can verify the issue. Thank you

**Comment by kmarellapudi** [comment]
Hi @exaby73, Tried with 3.7.0 also but the reported issue persisted. The problem seems to be with SliverGroupBuilder of the package 'flutter_group_sliver'. 

Code to reproduce this error - 

return SliverGroupBuilder(
                    margin: EdgeInsets.fromLTRB(4, 0, 4, 0),
                    padding: EdgeInsets.fromLTRB(10, 10, 10, 10),
                    decoration: BoxDecoration(color: Colors.white),
                    child: SliverGrid(
                        gridDelegate: SliverGridDelegateWithMaxCrossAxisExtent(
                            childAspectRatio: 4 / 3,
                            maxCrossAxisExtent: 800,
                            crossAxisSpacing: 6,
                            mainAxisSpacing: 6),
                        delegate:
                            SliverChildBuilderDelegate((context, int index) {
                          return Container(
                            alignment: Alignment.center,
                            child: "some widget"
                          );
                        }, childCount: 10)))

**Comment by exaby73** [comment]
Could you provide a complete sample, that can be directly run in a newly generated Flutter project by just copy-pasting the code into `main.dart`?
