### ISSUE TITLE
[url_launcher] iOS Swift migration

### ISSUE THREAD

**Issue by hellohuanlin** [flutter/flutter#119102]
Please refer to [this umbrella issue](https://github.com/flutter/flutter/issues/119015) for more details. 

This is a relatively small plugin that's easier to backfill tests and migrate. 

**Please don't forget to backfill tests to reduce the risk of regression, as [explained in the wiki](https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#testing).**

**Comment by stuartmorgan** [comment]
For anyone picking this up: see https://github.com/flutter/plugins/pull/7123 for an in-progress PR to do some of the testing backfill, which was never reviewed and landed.
