### ISSUE TITLE
`RawChip` doesn't use `ChipThemeData.showCheckmark` value

### ISSUE THREAD

**Issue by williamhjcho** [flutter/flutter#119163]
## Use case

Hello 👋 
While using the new m3 chips, it looks like the RawChip widget itself ignores the `showCheckmark` from the themes, because its instance value (priority) has a default `= true` on the constructor.

So whenever I wanted to use a `RawChip(...)`, I would have to `RawChip(showCheckmark: null, ...)` instead, so it fallbacks to the theme value.

> My current flutter version (beta channel)
```
Flutter 3.7.0-1.4.pre • channel beta • git@github.com:flutter/flutter.git
Framework • revision 686fe913dc (2 weeks ago) • 2023-01-10 16:14:01 -0800
Engine • revision ac5c83dd5f
Tools • Dart 2.19.0 (build 2.19.0-444.4.beta) • DevTools 2.20.0
```

## Proposal

A simple proposal would be [removing the default constructor value](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/chip.dart#L758) since the property is already nullable.

Also, ChoiceChip particularly will always override the showCheckmark with the [`theme.isMaterial3`](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/choice_chip.dart#L159), rather than having it defined on its [internal default variation theme](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/choice_chip.dart#L197).

---

Not sure if this is better to be a separate issue but I would also love to be able to insert a [custom constraint property](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/chip.dart#L1288-L1308), either on the theme or instance.

**Comment by exaby73** [comment]
Hello @williamhjcho. I can reproduce this issue. Indeed defaulting to true, `RawChip` ignores the parent `Theme`. I am not sure if this is intended or not, therefore I'll label it for insights from the team

https://github.com/flutter/flutter/blob/c9affdba9dcd2ac6569092509a44c9c84eba46f5/packages/flutter/lib/src/material/chip.dart#L758

**Comment by TahaTesser** [comment]
Unassigning @justinmc as this could be address in a [PR](https://github.com/flutter/flutter/pull/124779) for https://github.com/flutter/flutter/issues/124662

**Comment by GayathrideviGA** [comment]
@TahaTesser Need review [PR](https://github.com/flutter/flutter/pull/124779)

**Comment by williamhjcho** [comment]
All right, thanks for the update!
