### ISSUE TITLE
Linter reports "Don't use 'BuildContext's across async gaps" when `mounted` is checked

### ISSUE THREAD

**Issue by spydon** [flutter/flutter#119130]
## Steps to Reproduce

The linter reports "info: Don't use 'BuildContext's across async gaps." when the statement using the context is in an `if`-statement, even though `mounted` is checked.

The following reports the lint warning:
```dart
onPressed: () async {
  if (!context.mounted) return;
  if (await AlertDialog.showExitDialog(context)) {
    ...
  }
}
```

But this does not:
```dart
onPressed: () async {
  if (!context.mounted) return;
  final reply = await AlertDialog.showExitDialog(context);
  if (reply) {
    ...
  }
}
```

It doesn't matter whether `context.mounted` is used in a `StatelessWidget` or if `mounted` is used in a `StatefulWidget`, they both get the same result.

**Expected results:**

That is shouldn't report a lint warning.

**Actual results:**

"info: Don't use 'BuildContext's across async gaps."

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

[✓] Flutter (Channel stable, 3.7.0, on macOS 13.1 22C65 darwin-arm64, locale en-SE)
    • Flutter version 3.7.0 on channel stable at /Users/lukasklingsbo/bin/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b06b8b2710 (2 days ago), 2023-01-23 16:55:55 -0800
    • Engine revision b24591ed32
    • Dart version 2.19.0
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/lukasklingsbo/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] Connected device (3 available)
    • iPhone (mobile) • 18fdd79efe3c5baee0c80a4922cd2c9aa95cfe08 • ios            • iOS 13.3.1 17D50
    • macOS (desktop) • macos                                    • darwin-arm64   • macOS 13.1 22C65 darwin-arm64
    • Chrome (web)    • chrome                                   • web-javascript • Google Chrome 108.0.5359.124

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @spydon, this is being tracked in https://github.com/dart-lang/linter/issues/4007, a similar case was previously reported in https://github.com/flutter/flutter/issues/116779. 

Kindly follow up in the dart-linter issue for updates. 

Closing from here. 

Thank you
