### ISSUE TITLE
Update sample app to work with Flutter master channel

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#119138]
It looks like there's a need for a few migrations to get the sample app to build against the master channel. Currently, the iOS build fails, at least.

**Comment by jmagman** [comment]
If this is building on current stable 3.7 then this can be closed.

**Comment by felangel** [comment]
> If this is building on current stable 3.7 then this can be closed.

Closing for now since it is building on 3.7 and we have ci checks running on stable and beta channels.
