### ISSUE TITLE
fix: ScrollableColumn is an antipattern

### ISSUE THREAD

**Issue by Piinks** [flutter/flutter#119137]
**Description**

From the docs: `Creates a scrollable vertical array of children.`

The need for the widget is not clear to me yet, but it is a very very poor choice for a scrollable array of children.

This widget is a composition of a SingleChildScrollView, with an IntrinsicHeight wrapped Column. This is ripe for performance issues. Offering this widget to users to provide `children` to place inside of a SingleChildScrollView, on top of the speculative layout pass that IntrinsicHeight adds, will not lazily load children on demand.

This is what a ListView is for.

**Comment by kaiceyd** [comment]
Hey @Piinks are you planning to share a recommended approach to mitigate this issue within the Flutter framework or are you hoping we generate and share a proposal for your review?

**Comment by Piinks** [comment]
I know there are multiple use cases, so I cannot provide a recommendation for all of them. In my opinion, the replacement should be a simple ListView, but I am happy to consult if an example where this does not work can be provided. Thanks!
