### ISSUE TITLE
Clang roll issues

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#119170]
Our clang roll is 13 weeks behind. The [mac arm64 issue](https://bugs.fuchsia.dev/p/fuchsia/issues/detail?id=113913) was fixed upstream, so trying to get it started again: https://github.com/flutter/engine/pull/39132.

Issues so far:
- [ ] `-stdlib=libc++` flag from boringssl cc @rmacnak-google [logs](https://ci.chromium.org/ui/p/flutter/builders/try/Mac%20iOS%20Engine/42724/overview)
- [ ] Vulkan related linker errors cc @iskakaushik [logs](https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20Host%20Engine/47457/overview)

**Comment by jason-simmons** [comment]
The `-stdlib=libc++` flag is failing on Mac/iOS platforms when compiling C source files.  The compiler configuration scripts should restrict that flag to C++ sources.

The SwiftShader linker script references some symbols that are platform-specific and are #ifdeffed out in our build configuration.  Apparently recent versions of the linker now consider undefined symbols in a linker script to be an error by default.  This can be disabled with the `undefined-version` linker flag (see http://crbug.com/1374347)

**Comment by chinmaygarde** [comment]
The roll is going again. Closing.
