### ISSUE TITLE
[go_router_builder] Add parentNavigatorKey to generated routes.

### ISSUE THREAD

**Issue by lucasbstn** [flutter/flutter#119294]
## Use case

The GoRoute class has a parentNavigatorKey parameter which is useful to specify which Navigator to display the route's screen onto. However when using go_router_builder, there is currently no way of specifying such a key.

## Proposal

Implement a way to specify a GlobalKey<NavigatorState?> somewhere when declaring routes to be generated.
    
 Maybe overriding a getter in GoRouteData like so:

```dart
final rootNavigatorKey = GlobalKey<NavigatorState>();

@TypedGoRoute<SplashRoute>(
  path: '/splash',
)
class SplashRoute extends GoRouteData {
  const SplashRoute();

  @override
  Widget build(BuildContext context, GoRouterState state) =>
      const SplashScreen();

  @override
  GlobalKey<NavigatorState>? get parentNavigatorKey => rootNavigatorKey;
}
```

Or specifying the name of the global key like so, which would follow the pattern of how GoRoute are manually declared.
```dart
final rootNavigatorKey = GlobalKey<NavigatorState>();

@TypedGoRoute<SplashRoute>(
  path: '/splash',
  parentNavigatorKey:'rootNavigatorKey',
)
class SplashRoute extends GoRouteData {
  const SplashRoute();

  @override
  Widget build(BuildContext context, GoRouterState state) =>
      const SplashScreen();
}
```

**Comment by arnab** [comment]
Thanks for submitting the issue, @lucasbstn !

Meanwhile, have you or someone else figured out a placeholder workaround to this? Without `parentNavigatorKey`, typed GoRoutes are essentially unusable in any app where you need some routes to not render in the app shell?

**Comment by lucasbstn** [comment]
I'm using a fork of the package where I implemented what I explained above.
[Here are the small changes I made](https://github.com/lucasbstn/packages/commit/0299a0fd2f11bef1bcfaa415fd59bbdcb3c83acf)

Use it like this:
```dart
final rootNavigatorKey = GlobalKey<NavigatorState>();

@TypedGoRoute<SplashRoute>(
  path: '/splash',
  parentNavigatorKey:'rootNavigatorKey',
)
class SplashRoute extends GoRouteData {
  const SplashRoute();

  @override
  Widget build(BuildContext context, GoRouterState state) =>
      const SplashScreen();
}

**Comment by kevmoo** [comment]
This is blocking an external customer.

**Comment by johnpryan** [comment]
Here's the latest PR for adding ShellRoute support to go_router_builder: https://github.com/flutter/packages/pull/3439

**Comment by jpascasio1993** [comment]
I did some dirty hack. I created an extension method.

```dart
extension GoRouterListExtension on List<GoRoute> {
  List<GoRoute> addParentNavigationKey() => this.map((e) => GoRoute(
      path: e.path,
      parentNavigatorKey: rootNavigator,
      routes: e.routes,
      name: e.name,
      builder: e.builder,
      pageBuilder: e.pageBuilder,
      redirect: e.redirect)).toList(growable: false);
}

final appRouter = GoRouter(
    navigatorKey: rootNavigator,
    routes: [
      ...welcome.$appRoutes,
      ...login.$appRoutes,
      ...verifyCode.$appRoutes.addParentNavigationKey(),
      ...about.$appRoutes.addParentNavigationKey(),
      dashboardShellRoute,
      ...JoinFundraiser.$appRoutes.addParentNavigationKey(),
    ],
    initialLocation: '/',
    debugLogDiagnostics: true,
    redirect: _handleRedirect); 
``` 

Basically, it just maps the "$appRoutes" which is generated by the go_router_builder with the added parentNavigationKey.

I hope this helps

**Comment by stuartmorgan** [comment]
Is P2 still the right priority here? The PR doesn't appear to have been updated in the last couple of weeks.

**Comment by johnpryan** [comment]
I don't think this blocking anyone, given @jpascasio1993's workaround

**Comment by kostadin-damyanov-prime** [comment]
Is tihs being worked on? I see that the `GoRouteData.$route()` function accepts a `parentNavigatorKey` parameter but I guess it is not used by the generated code.

**Comment by johnpryan** [comment]
@kostadin-damyanov-prime which version of go_router_builder are you using? This should be working in version 1.2.0.

**Comment by kostadin-damyanov-prime** [comment]
@johnpryan I am using 1.2.1 (latest currently) and I need to pass a `parentNavigatorKey` value to a regular `@TypedGoRoute` (not a shell route). Is there an example on how to do that?

**Comment by johnpryan** [comment]
Which version of go_router are you using? parentNavigatorKey was added to TypedGoRoute in version 6.3.0

**Comment by johnpryan** [comment]
I filed an issue to add some testing: https://github.com/flutter/flutter/issues/124734

**Comment by GP4cK** [comment]
> Which version of go_router are you using? parentNavigatorKey was added to TypedGoRoute in version 6.3.0

This was a mistake actually. We realised that we couldn't use it because navigator keys are not `const`. So we removed them in 6.5.4 in favour of using static keys instead.

@kostadin-damyanov-prime, you can refer to these lines in the example for a regular `TypedGoRoute`.
https://github.com/flutter/packages/blob/6bf2ea8facf742cfa0f1785a0d8e48fb68032a56/packages/go_router_builder/example/lib/shell_route_with_keys_example.dart#L148-L169

**Comment by GP4cK** [comment]
It's also at the end of the readme: https://github.com/flutter/packages/tree/main/packages/go_router_builder#typedshellroute-and-navigator-keys
