### ISSUE TITLE
Codesign failure on iOS when using assets from a package

### ISSUE THREAD

**Issue by LauDijksterhuis** [flutter/flutter#119228]
Hello :)

Since I upgraded my Flutter version from 3.3.10 (I guess) to 3.7.0 the compiler gives me an error for running / building an app on iOS. After searching, re-adding the iOS platform, and many trial and error I found that the problem comes from using assets out of a package. 

So the project I have has 3 apps that use some of the same resources like shared code, images, fonts etc. All the shared resources have been added to the local 'shared' package. Then with in my Flutter app I use: `Image.asset('file-name', package: 'shared')` to use whatever I need. Before this works perfectly fine (and on web it still does) but on iOS-devices I get the following error, please see below: 

```
Could not build the precompiled application for the device.
Error (Xcode): Target release_ios_bundle_flutter_assets failed: Exception: Failed to codesign
/path-to/build/ios/Release-ip
honeos/App.framework/App with identity XXX
```

When commenting out all the assets in the shared package and running the app, it will install and run without any problems (except that the images don't show ofcourse)

**Comment by exaby73** [comment]
Hello @LauDijksterhuis. Could you provide some steps to reproduce this issue, with code samples with applicable?

**Comment by LauDijksterhuis** [comment]
Hi @exaby73 

Sadly I couldn't reproduce the issue with a clean project, so I guess the problem only occurs in my project.
For my own project I will move remove the images from the shared package and add them to each app seperatly

Anyway, thank you for your time.

If this problem starts to occur in another project as well I will raise a new issue.

**Comment by LauDijksterhuis** [comment]
Just adding this comment for when someone bumbs in to the same problem.

In my case, one specific SVG file was the problem. Edititing the file directly / changing the name did not work.
Opening the file in Illustrator and saving it as a new file with a new name made the error disappear... 🧐

**Comment by JustAimz** [comment]
The best way is to `flutter clean` in root directory then `pod deintegrate` in ios folder. After that delete `podfile` and `podfile.lock` then run `flutter pub get` in root directory then use VS Code to debugging run your app on live device/simulator. It will update some files in xcodeproj that will resolve issues.
