### ISSUE TITLE
Flutter 3.7.0, flutter create -> flutter run fails, on MacOS 12.4

### ISSUE THREAD

**Issue by darko-sameplace** [flutter/flutter#119248]
## Steps to Reproduce

1. Create new Flutter app, with Flutter 3.7.0, using 'flutter create my_first_app'
2. Execute `flutter run` and choose available simulator (android or iOS)

**Actual results:** 

Multiple devices found:
sdk gphone64 arm64 (mobile)         • emulator-5554                        • android-arm64  • Android 12 (API 32) (emulator)
iPhone SE (3rd generation) (mobile) • D014F969-A254-403C-BF19-9CAA5EBB5D57 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-5 (simulator)
macOS (desktop)                     • macos                                • darwin-arm64   • macOS 12.4 21F79 darwin-arm64
Chrome (web)                        • chrome                               • web-javascript • Google Chrome 109.0.5414.87
[1]: sdk gphone64 arm64 (emulator-5554)
[2]: iPhone SE (3rd generation) (D014F969-A254-403C-BF19-9CAA5EBB5D57)
[3]: macOS (macos)
[4]: Chrome (chrome)
Please choose one (To quit, press "q/Q"): 1
Using hardware rendering with device sdk gphone64 arm64. If you notice graphics artifacts, consider enabling software rendering with "--enable-software-rendering".
Launching lib/main.dart on sdk gphone64 arm64 in debug mode...

Then, MacOS shows a system message dialog:
“impellerc” can’t be opened because Apple cannot check it for malicious software. 
After closing the dialog, flutter run execution continue in console:

Target debug_android_application failed: ShaderCompilerException: Shader compilation of "/Users/darkozlatic/development/flutter/packages/flutter/lib/src/material/shaders/ink_sparkle.frag" to "/Users/darkozlatic/Documents/SamePlace/Development/Playgrounds/Flutter/my_first_app/build/app/intermediates/flutter/debug/flutter_assets/shaders/ink_sparkle.frag" failed with exit code -9.
impellerc stdout:

impellerc stderr:

FAILURE: Build failed with an exception.

```
flutter doctor 
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.0, on macOS 12.4 21F79 darwin-arm64, locale en-CZ)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] VS Code (version 1.74.3)
[✓] Connected device (4 available)
[✓] HTTP Host Availability

• No issues found!

```

</details>

<img width="372" alt="Screenshot 2023-01-26 at 18 05 59" src="https://user-images.githubusercontent.com/74680289/214902293-fe01be39-f487-4196-8136-e44d373c089b.png">

**Comment by darko-sameplace** [comment]
Not a critical, workround is to "Show in Finder" then Open...

**Comment by darko-sameplace** [comment]
Not a critical, workaround is to click on "Show in Finder" then on the file RightClick/Open...

**Comment by datamann** [comment]
> Not a critical, workaround is to click on "Show in Finder" then on the file RightClick/Open...

On our company MACs we are not allowed to change this and "RightClick/Open" does not work either, so for us, this workaround does not work and makes it impossible to use this tool completely!
This might be an issue for many people worldwide, so this is very critical!
In my opinion, these types of tools should always be known for Apple!

**Comment by excing** [comment]
Hello, How do you upgrade Xcode to 13.4 on macOS 12.4 version? Thank you.
