### ISSUE TITLE
[video_player] Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found. 

### ISSUE THREAD

**Issue by yisar** [flutter/flutter#119227]
As same as https://github.com/flutter/flutter/issues/32125

this is my video url:

```dart
https://zm.igsubs.com:83/index.php/m3u8/db6ewPyHgbkgKPaQOni3qlJJfD1uVSogc08S8DGvftVQZBe5peK7ErPAPbW2UeoWgGvM5IIpRTulzQI.m3u8
```

**Comment by exaby73** [comment]
Hello @yisar. Can you please provide error logs, and more detailed information about the issue instead of linking to a 3 year old issue that might not have updated information in it? Thank you

**Comment by yisar** [comment]
@exaby73 I've found the reason. It's video_player does not support self-signed ssl certificates. It can be downgraded to http. There are several similar problems in the issue area that have not been resolved.
