### ISSUE TITLE
Can't run iOS unit tests in engine `run_tests.py --type=objc`: `TypeError: cannot use a string pattern on a bytes-like object`

### ISSUE THREAD

**Issue by LouiseHsu** [flutter/flutter#119204]
As per [this readme](https://github.com/flutter/engine/blob/master/testing/ios/IosUnitTests/README.md ), the ios tests are can be built and run by running `flutter/testing/run_tests.py --type=objc` in `src`.

However this is the output:
```
Traceback (most recent call last):
  File "/Users/louisehsu/Development/engine/src/flutter/testing/run_tests.py", line 1154, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/louisehsu/Development/engine/src/flutter/testing/run_tests.py", line 1140, in main
    run_objc_tests(args.ios_variant, args.objc_filter)
  File "/Users/louisehsu/Development/engine/src/flutter/testing/run_tests.py", line 684, in run_objc_tests
    assert_expected_xcode_version()
  File "/Users/louisehsu/Development/engine/src/flutter/testing/run_tests.py", line 601, in assert_expected_xcode_version
    match = re.match(r'Xcode (\d+)', version_output)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/re/__init__.py", line 166, in match
    return _compile(pattern, flags).match(string)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: cannot use a string pattern on a bytes-like object
```

@jmagman

**Comment by jmagman** [comment]
I'm also reproducing this on my M1.  

https://github.com/flutter/engine/blob/a04997c81f78746fdd44f8b6b3058bcc13ef39ad/testing/run_tests.py#L600-L601

`xcodebuild -version` is returning binary `b'Xcode 14.2\nBuild version 14C18\n'`

@cbracken I thought we tracked all these cases down during the python3 migration. Any idea why this isn't reproducing in CI?
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8790962061227835665/+/u/test:_Host_Tests_for_ios_debug_sim/execution_details

**Comment by jmagman** [comment]
Adding `version_output.decode()` on my machine passes, but if it's a string in CI (or it's dropping back to python 2?) then that will fail `'str' object has no attribute 'decode'` and we'll need some duck typing.

**Comment by cbracken** [comment]
> Any idea why this isn't reproducing in CI?

Only thing I can imagine is if something's not hermetic and we're picking up a different python than the depot tools vpython (or a different version of it?)

**Comment by zanderso** [comment]
@ricardoamador has a PR out that I think will help with this https://github.com/flutter/engine/pull/39133

**Comment by ricardoamador** [comment]
PR has been merged. Please update and try your tests again.

**Comment by LouiseHsu** [comment]
The merged PR fixed it for me. Thanks @ricardoamador!
