### ISSUE TITLE
Unable to delete internal storage file in Flutter

### ISSUE THREAD

**Issue by Harsh1052** [flutter/flutter#119217]
I am trying to delete a file in Flutter using the `dart:io` library's delete method, but I am receiving a `FileSystemException `with the message "Deletion failed, the file or directory is not empty." I have confirmed that the file exists and that I have the correct permissions to delete it. I have also tried using the `deleteSync `method with the same result.

My code for deleting the file is as follows:
```
//_selectedFile is List<File>.
await Future.forEach(_selectedFile, (element) async {
      if (await element?.exists() ?? false) {   <------------------- condition returning true
        await element?.delete();
      }
    });
```
**Steps to reproduce:**

1) Create a file in a directory in your Flutter project.
2) Try to delete the file using the dart:io library's delete method.

**Expected behavior:**
The file should be successfully deleted without error because it exits in the external storage.

**Actual behavior:**
A FileSystemException is thrown with the message "Deletion failed, the file or directory is not exits."
Error:

> [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: FileSystemException: Cannot delete file, path = '/storage/emulated/0/Pictures/Image Description (1).jpg' (OS Error: No such file or directory, errno = 2)
> E/flutter (25734): #0      _File._delete.<anonymous closure> (dart:io/file_impl.dart:283:9)
> E/flutter (25734): <asynchronous suspension>
> E/flutter (25734): #1      DuplicatePhotoScreenNotifier.deleteSelectedFiles.<anonymous closure> (package:gallery_app/provider/duplicate_photo_screen_notifier.dart:69:9)
> E/flutter (25734): <asynchronous suspension>
> E/flutter (25734): #2      _RootZone.bindUnaryCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1625:12)
> E/flutter (25734): <asynchronous suspension>

**Environment:**

Flutter version :(Channel stable, 3.3.10, on Microsoft Windows [Version 10.0.19044.2486], locale en-IN)
Dart version: 2.18.6 (stable) (Tue Dec 13 21:15:14 2022 +0000) on "windows_x64"

**Comment by exaby73** [comment]
Hello @Harsh1052. Thank you for filing this issue. Can you please provide the following information?

- A [complete and minimal, reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example). Ideally, a single `main.dart` file that can be run directly.
- The output of `flutter doctor -v`
- The output of `flutter run -v`

Please provide the information in the form of text. See how to make collapsible sections with Markdown [here](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-collapsed-sections).

**Comment by Harsh1052** [comment]
Here is the reproducible code sample
```
List<File> _selectedFile = [File('Path of the File'), ...... ];
 await Future.forEach(_selectedFile, (element) async {
      if (await element?.exists() ?? false) {   <------------------- condition returning true
        await element?.delete();
      }
    });
```
<details><summary>flutter doctor -v</summary>
<p>
[√] Flutter (Channel stable, 3.3.10, on Microsoft Windows [Version 10.0.19044.2486], locale en-IN)
    • Flutter version 3.3.10 on channel stable at D:\flutter\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (6 weeks ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

Checking Android licenses is taking an unexpectedly long time...[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\elision flutter\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2022.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[√] VS Code (version 1.73.1)
    • VS Code at C:\Users\elision flutter\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (4 available)
    • SM M022G (mobile) • RZ8R201GL6L • android-arm    • Android 11 (API 30)
    • Windows (desktop) • windows     • windows-x64    • Microsoft Windows [Version 10.0.19044.2486]
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 109.0.5414.76
    • Edge (web)        • edge        • web-javascript • Microsoft Edge 109.0.1518.55

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

</p>
</details>

**Comment by exaby73** [comment]
Hello @Harsh1052. Could you provide a complete example, that can be directly run in `main.dart` and detailed steps to reproduce the issue as well?
