### ISSUE TITLE
[CP] [Impeller] Use analytical normals for stroke caps

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#119263]
### issue_link

https://github.com/flutter/flutter/issues/118945

### Commit Hash

https://github.com/flutter/engine/commit/c068a3675ac360e4b5e1acd6c8ee0f445324fd3b

### Target

stable

### pr_link

https://github.com/flutter/engine/pull/39168

### Impacted Users

Impeller users

### Impact Description

Canvas.drawArc with large stroke width has rendering artifacts

### Workaround

There is not workaround

### Risk

low

### Test Coverage

yes

### Validation Steps

Verify that Canvas.drawArc call results look correct.

**Comment by zanderso** [comment]
cc @bdero @jonahwilliams @chinmaygarde

**Comment by jonahwilliams** [comment]
LGTM
