### ISSUE TITLE
Issue from website page FAQ

### ISSUE THREAD

**Issue by dearests** [flutter/flutter#11929]
From URL: https://flutter.io/faq.md
i keep getting this issues - 

[✓] Flutter (on Linux, locale en_NG, channel alpha)
    • Flutter at /home/cyberdemon/flutter
    • Framework revision 1c372c6803 (4 days ago), 2017-08-31 15:54:45 -0700
    • Engine revision f9e00a7c72
    • Tools Dart version 1.25.0-dev.11.0

[-] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at /home/cyberdemon/Android/Sdk
    • Platform android-25, build-tools 25.0.3
    ✗ Android SDK file not found: /home/cyberdemon/Android/Sdk/build-tools/25.0.3/aapt.
    • Try re-installing or updating your Android SDK,
      visit https://flutter.io/setup/#android-setup for detailed instructions.

[✓] Android Studio (version 2.3)
    • Android Studio at /home/cyberdemon/android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.2)
    • Flutter plugin version 17.0
    • Dart plugin version 172.3968.27

[✓] Connected devices
    • None

and i can't figure out what seems to be the issues because i have my android updated

**Comment by najeira** [comment]
Did you try re-installing build-tools?

Install Android build-tools:

- open Android Studio
- select Menu > Tool > Android > SDK manager
- select SDK Tools tab
- check Show Package Details
- check Android SDK Build-tools 25.0.3

**Comment by Hixie** [comment]
@dearests Any luck?

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
