### ISSUE TITLE
Material Icons

### ISSUE THREAD

**Issue by nagringapp** [flutter/flutter#119232]
When are you guys planning to update the Material icons to align with the website https://fonts.google.com/icons

Is there any workaround to get the most updated icons?

**Comment by danagbemava-nc** [comment]
Hi @nagringapp, if there are icons you feel are missing, kindly follow the instructions in  https://github.com/flutter/flutter/issues/99973#issue-1166360809 and then leave a comment on the issue and it will be added. 

To answer your question, you can try using https://www.fluttericon.com/ to generate the icons you need for your project and include them that way until they become available in the project. 

Closing from here. 

Thank you
