### ISSUE TITLE
Flutter 3.7.0: Missing whatsapp icon

### ISSUE THREAD

**Issue by FabioPaganoAPSystem** [flutter/flutter#119202]
In Flutter 3.7.0 is no more present the whatsapp icon.

The following instruction:
Icon(Icons.whatsapp)
now gives error "The getter 'whatsapp' isn't defined for the type 'Icons'".

In previous version the whatsapp icon was present.

Thank you.

**Comment by stuartmorgan** [comment]
Duplicate of https://github.com/flutter/flutter/issues/111667
