### ISSUE TITLE
Eliminate use of libtxt in engine

### ISSUE THREAD

**Issue by flar** [flutter/flutter#119266]
Currently we are trying to get the text code weaned off of SkCanvas rendering to fully support Impeller. This is mostly done, but we still support the use of libtxt which requires SkCanvas support. Fixing those dependencies and eliminating that library will put us one step closer to eliminating DisplayListCanvasRecorder and many Skia dependencies in the engine.

(This work is already scheduled, but this issue will provide tracking info for some of the other issues filed against DisplayList.)

**Comment by chinmaygarde** [comment]
This came up a few months ago and at that time @jason-simmons remarked that he sometimes still used the flag to swap backends to check for regressions. This wasn't frequent and I suspect this has gotten even less so in the intervening months. I think we should go ahead with this given the maintenance costs but I'll let @jason-simmons chime in.

**Comment by jason-simmons** [comment]
Landed https://github.com/flutter/engine/pull/39499
