### ISSUE TITLE
integration testing issues

### ISSUE THREAD

**Issue by kimsean** [flutter/flutter#119219]
HI. I followed these intructions

https://github.com/flutter/flutter/tree/master/packages/integration_test#android-device-testing

but when i build it, i get these errors.
`
error: cannot find symbol
 public ActivityTestRule<MainActivity> rule = new ActivityTestRule<>(MainActivity.class, true, false);
`
Currently using flutter 3.3.10

**Comment by darshankawar** [comment]
Closing this as duplicate of https://github.com/flutter/flutter/issues/62237. Please upvote original issue for team's attention.
