### ISSUE TITLE
Regression in worst rasterizer frame in fullscreen textfield perf

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#119258]
It looks like something funky is going on after upgrading the devicelab to iPhone 11, iOS 16:

I've requested backfills on the missing entries.

https://flutter-flutter-perf.skia.org/e/?begin=1670882094&end=1674710702&keys=X0b560119f66c8e19df76d38b7a680c37&queries=arch%3Dintel%26branch%3Dmaster%26config%3Ddefault%26device_type%3DiPhone_11%26device_type%3DiPhone_6s%26device_version%3Dnone%26host_type%3Dmac%26sub_result%3Dworst_frame_rasterizer_time_millis%26test%3Dfullscreen_textfield_perf_impeller_ios__e2e_summary&requestType=0&selected=commit%3D33034%26name%3D%252Carch%253Dintel%252Cbranch%253Dmaster%252Cconfig%253Ddefault%252Cdevice_type%253DiPhone_11%252Cdevice_version%253Dnone%252Chost_type%253Dmac%252Csub_result%253Dworst_frame_rasterizer_time_millis%252Ctest%253Dfullscreen_textfield_perf_impeller_ios__e2e_summary%252C&xbaroffset=33030

**Comment by zanderso** [comment]
There's nothing suspicious in the missing commits. For some reason the worst frame on the iPhone 11/iOS16 is reported as much worse than the old 6s's.

**Comment by chinmaygarde** [comment]
My sense is that this is measuring a platform/device specific delay. I think we synchronize with the platform as the keyboard is coming up. I'm going to take a closer look to confirm.

**Comment by chinmaygarde** [comment]
Removing this off of the Impeller dashboard as the readings changed when the devices switched.

**Comment by jonahwilliams** [comment]
This was frame scheduling behavior changes, which we've worked around mostly with FlutterMetalLayer
