### ISSUE TITLE
In Stocks app, switching tabs should remember ListView scroll position

### ISSUE THREAD

**Issue by amardeep** [flutter/flutter#11927]
## Steps to Reproduce

Run stocks example app. Scroll in the market tab. Switch to portfolio tab and then again back to market tab. The market tab listview is scrolled to the top, instead of remembering the previous scroll position.

## Flutter Doctor
```
[✓] Flutter (on Mac OS X 10.12.5 16F73, locale en-US, channel alpha)
    • Flutter at /Users/amardeep/soft/flutter
    • Framework revision 1c372c6803 (4 days ago), 2017-08-31 15:54:45 -0700
    • Engine revision f9e00a7c72
    • Tools Dart version 1.25.0-dev.11.0

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.1)
    • Android SDK at /Users/amardeep/Library/Android/sdk
    • Platform android-26, build-tools 26.0.1
    • ANDROID_HOME = /Users/amardeep/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.3.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3.3, Build version 8E3004b
    • ios-deploy 1.9.1
    • CocoaPods version 1.2.1

[✓] Android Studio
    • Android Studio at /Applications/Android Studio 3.0 Preview.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b736)

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] Connected devices
    • iPhone 6s • 25A5BCDD-C0A9-47E2-854A-E4E395186423 • ios • iOS 10.3 (simulator)
```

**Comment by pedia** [comment]
ListView also lost scroll position in Navigate back and switch in TabController.

**Comment by iapicca** [comment]
Hi @amardeep 
I'm closing this issue as it refer to an older version of Flutter.
If you are you still experiencing this issue with the latest version of Flutter,
you may want to open a new issue or comment below;
either way please provide your updated `flutter doctor -v`.
It would be helpful to have also your` flutter run --verbose`
and a self contained app on github (or the steps to reproduce it).
Thank you

**Comment by TahaTesser** [comment]
There is no stock example in the flutter gallery
There is something similar called Rally in https://gallery.flutter.dev/#/rally but it's stocks example
Closing the issue. If you disagree, please write in the comments and I will reopen it.
Thank you
