### ISSUE TITLE
error on InkWell onTap, Failed assertion: line 4516 pos 12: '!_debugLocked': is not true.

### ISSUE THREAD

**Issue by tc1025** [flutter/flutter#119211]
The following assertion was thrown while handling a gesture:
```
'package:flutter/src/widgets/navigator.dart': Failed assertion: line 4516 pos 12: '!_debugLocked': is not true.

(elided 5 frames from class _AssertionError and dart:async)
Handler: "onTap"
Recognizer: TapGestureRecognizer#46b3e
  debugOwner: GestureDetector
  state: possible
  won arena
  finalPosition: Offset(258.0, 218.3)
  finalLocalPosition: Offset(242.0, 38.3)
  button: 1

```
It doesn't work when I try to go from InkWell to any button and use onPress.
  
Flutter Channel stable, 3.7.0
Dart version 2.19.0

**Comment by darshankawar** [comment]
@tc1025 
Can you provide minimal code sample that triggers this exception ?
By any chance can you also check if you are calling navigator before the build is called ?

**Comment by tc1025** [comment]
InkWell(
      child: Container(
        padding: EdgeInsets.symmetric(vertical: 16.h, horizontal: 16.w),
        child: Row(
          mainAxisSize: MainAxisSize.min,
          children: [
            Container(
              decoration: BoxDecoration(
                borderRadius: BorderRadius.circular(8.r),
                color: const Color(0x33F99C1E),
              ),
              padding: EdgeInsets.symmetric(vertical: 8.h, horizontal: 8.w),
              margin: EdgeInsets.only(right: 16.w),
              child: SvgPicture.asset(
                'assets/ic_calendar_event.svg',
                height: 24.h,
                width: 24.w,
              ),
            ),
            Expanded(
              child: Column(
                mainAxisSize: MainAxisSize.min,
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(
                    calendarEvent.title,
                    style: CustomDesign.text(
                      size: 14.sp,
                      textColor: const Color(0xff323232),
                      bold: true,
                    ),
                  ),
                  Padding(
                    padding: EdgeInsets.only(top: 4.h),
                    child: Text(
                      calendarEvent.content,
                      maxLines: 2,
                      overflow: TextOverflow.ellipsis,
                      style: CustomDesign.text(
                        size: 12.sp,
                        textColor: const Color(0xff969696),
                      ),
                    ),
                  ),
                ],
              ),
            ),
            Padding(
              padding: EdgeInsets.only(left: 20.w),
              child: Icon(
                Icons.chevron_right,
                size: 16.w,
                color: const Color(0xff323232),
              ),
            ),
          ],
        ),
      ),
      onTap: () {
        WidgetsBinding.instance.addPostFrameCallback((_) {
          Navigator.of(context).push(MaterialPageRoute(
              builder: (context) =>
                  CalendarDetailFragment(calendarEvent: calendarEvent,)));
        });
      },
    )
    
    here's the code @darshankawar

**Comment by tc1025** [comment]
InkWell(
      child: Container(
        padding: EdgeInsets.symmetric(vertical: 16.h, horizontal: 16.w),
        child: Row(
          mainAxisSize: MainAxisSize.min,
          children: [
            Container(
              decoration: BoxDecoration(
                borderRadius: BorderRadius.circular(8.r),
                color: const Color(0x33F99C1E),
              ),
              padding: EdgeInsets.symmetric(vertical: 8.h, horizontal: 8.w),
              margin: EdgeInsets.only(right: 16.w),
              child: SvgPicture.asset(
                'assets/ic_calendar_event.svg',
                height: 24.h,
                width: 24.w,
              ),
            ),
            Expanded(
              child: Column(
                mainAxisSize: MainAxisSize.min,
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(
                    calendarEvent.title,
                    style: CustomDesign.text(
                      size: 14.sp,
                      textColor: const Color(0xff323232),
                      bold: true,
                    ),
                  ),
                  Padding(
                    padding: EdgeInsets.only(top: 4.h),
                    child: Text(
                      calendarEvent.content,
                      maxLines: 2,
                      overflow: TextOverflow.ellipsis,
                      style: CustomDesign.text(
                        size: 12.sp,
                        textColor: const Color(0xff969696),
                      ),
                    ),
                  ),
                ],
              ),
            ),
            Padding(
              padding: EdgeInsets.only(left: 20.w),
              child: Icon(
                Icons.chevron_right,
                size: 16.w,
                color: const Color(0xff323232),
              ),
            ),
          ],
        ),
      ),
      onTap: () {
        WidgetsBinding.instance.addPostFrameCallback((_) {
          Navigator.of(context).push(MaterialPageRoute(
              builder: (context) =>
                  CalendarDetailFragment(calendarEvent: calendarEvent,)));
        });
      },
    )

here's the code @darshankawar

**Comment by tc1025** [comment]
`InkWell(
      child: Container(
        padding: EdgeInsets.symmetric(vertical: 16.h, horizontal: 16.w),
        child: Row(
          mainAxisSize: MainAxisSize.min,
          children: [
            Container(
              decoration: BoxDecoration(
                borderRadius: BorderRadius.circular(8.r),
                color: const Color(0x33F99C1E),
              ),
              padding: EdgeInsets.symmetric(vertical: 8.h, horizontal: 8.w),
              margin: EdgeInsets.only(right: 16.w),
              child: SvgPicture.asset(
                'assets/ic_calendar_event.svg',
                height: 24.h,
                width: 24.w,
              ),
            ),
            Expanded(
              child: Column(
                mainAxisSize: MainAxisSize.min,
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(
                    calendarEvent.title,
                    style: CustomDesign.text(
                      size: 14.sp,
                      textColor: const Color(0xff323232),
                      bold: true,
                    ),
                  ),
                  Padding(
                    padding: EdgeInsets.only(top: 4.h),
                    child: Text(
                      calendarEvent.content,
                      maxLines: 2,
                      overflow: TextOverflow.ellipsis,
                      style: CustomDesign.text(
                        size: 12.sp,
                        textColor: const Color(0xff969696),
                      ),
                    ),
                  ),
                ],
              ),
            ),
            Padding(
              padding: EdgeInsets.only(left: 20.w),
              child: Icon(
                Icons.chevron_right,
                size: 16.w,
                color: const Color(0xff323232),
              ),
            ),
          ],
        ),
      ),
      onTap: () {
        WidgetsBinding.instance.addPostFrameCallback((_) {
          Navigator.of(context).push(MaterialPageRoute(
              builder: (context) =>
                  CalendarDetailFragment(calendarEvent: calendarEvent,)));
        });
      },
    )`

here's the code @darshankawar

**Comment by tc1025** [comment]
`InkWell(
      child: Container(
        padding: EdgeInsets.symmetric(vertical: 16.h, horizontal: 16.w),
        child: Row(
          mainAxisSize: MainAxisSize.min,
          children: [
            Container(
              decoration: BoxDecoration(
                borderRadius: BorderRadius.circular(8.r),
                color: const Color(0x33F99C1E),
              ),
              padding: EdgeInsets.symmetric(vertical: 8.h, horizontal: 8.w),
              margin: EdgeInsets.only(right: 16.w),
              child: SvgPicture.asset(
                'assets/ic_calendar_event.svg',
                height: 24.h,
                width: 24.w,
              ),
            ),
            Expanded(
              child: Column(
                mainAxisSize: MainAxisSize.min,
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(
                    calendarEvent.title,
                    style: CustomDesign.text(
                      size: 14.sp,
                      textColor: const Color(0xff323232),
                      bold: true,
                    ),
                  ),
                  Padding(
                    padding: EdgeInsets.only(top: 4.h),
                    child: Text(
                      calendarEvent.content,
                      maxLines: 2,
                      overflow: TextOverflow.ellipsis,
                      style: CustomDesign.text(
                        size: 12.sp,
                        textColor: const Color(0xff969696),
                      ),
                    ),
                  ),
                ],
              ),
            ),
            Padding(
              padding: EdgeInsets.only(left: 20.w),
              child: Icon(
                Icons.chevron_right,
                size: 16.w,
                color: const Color(0xff323232),
              ),
            ),
          ],
        ),
      ),
      onTap: () {
        WidgetsBinding.instance.addPostFrameCallback((_) {
          Navigator.of(context).push(MaterialPageRoute(
              builder: (context) =>
                  CalendarDetailFragment(calendarEvent: calendarEvent,)));
        });
      },
    )`

**Comment by tc1025** [comment]
```
InkWell(
      child: Container(
        padding: EdgeInsets.symmetric(vertical: 16.h, horizontal: 16.w),
        child: Row(
          mainAxisSize: MainAxisSize.min,
          children: [
            Container(
              decoration: BoxDecoration(
                borderRadius: BorderRadius.circular(8.r),
                color: const Color(0x33F99C1E),
              ),
              padding: EdgeInsets.symmetric(vertical: 8.h, horizontal: 8.w),
              margin: EdgeInsets.only(right: 16.w),
              child: SvgPicture.asset(
                'assets/ic_calendar_event.svg',
                height: 24.h,
                width: 24.w,
              ),
            ),
            Expanded(
              child: Column(
                mainAxisSize: MainAxisSize.min,
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(
                    calendarEvent.title,
                    style: CustomDesign.text(
                      size: 14.sp,
                      textColor: const Color(0xff323232),
                      bold: true,
                    ),
                  ),
                  Padding(
                    padding: EdgeInsets.only(top: 4.h),
                    child: Text(
                      calendarEvent.content,
                      maxLines: 2,
                      overflow: TextOverflow.ellipsis,
                      style: CustomDesign.text(
                        size: 12.sp,
                        textColor: const Color(0xff969696),
                      ),
                    ),
                  ),
                ],
              ),
            ),
            Padding(
              padding: EdgeInsets.only(left: 20.w),
              child: Icon(
                Icons.chevron_right,
                size: 16.w,
                color: const Color(0xff323232),
              ),
            ),
          ],
        ),
      ),
      onTap: () {
        WidgetsBinding.instance.addPostFrameCallback((_) {
          Navigator.of(context).push(MaterialPageRoute(
              builder: (context) =>
                  CalendarDetailFragment(calendarEvent: calendarEvent,)));
        });
      },
    )
```

here's the code @darshankawar

**Comment by darshankawar** [comment]
Thanks for the code. I updated it to make it runnable since it was showing compile errors. Anyway, running the below updated code sample using latest master on mobile and playing around with the app didn't trigger the reported behavior.

<details>
<summary> runnable code sample </summary>

```

import 'package:flutter/material.dart';
import 'package:flutter_svg/svg.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Demo'),
      ),
      body: Center(
        child: InkWell(
          child: Container(
            padding: EdgeInsets.symmetric(vertical: 16, horizontal: 16),
            child: Row(
              mainAxisSize: MainAxisSize.min,
              children: [
                Container(
                  decoration: BoxDecoration(
                    borderRadius: BorderRadius.circular(8),
                    color: const Color(0x33F99C1E),
                  ),
                  padding: EdgeInsets.symmetric(vertical: 8, horizontal: 8),
                  margin: EdgeInsets.only(right: 16),
                  child: SvgPicture.asset(
                    'assets/flutter_logo.svg',
                    height: 24,
                    width: 24,
                  ),
                ),
                Expanded(
                  child: Column(
                    mainAxisSize: MainAxisSize.min,
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text(
                        'test',
                        style: TextStyle(
                          fontSize: 14,
                          color: const Color(0xff323232),
                          fontWeight: FontWeight.bold,
                        ),
                      ),
                      Padding(
                        padding: EdgeInsets.only(top: 4),
                        child: Text(
                          'Another test',
                          maxLines: 2,
                          overflow: TextOverflow.ellipsis,
                          style: TextStyle(
                            fontSize: 12,
                            color: const Color(0xff969696),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
                Padding(
                  padding: EdgeInsets.only(left: 20),
                  child: Icon(
                    Icons.chevron_right,
                    size: 16,
                    color: const Color(0xff323232),
                  ),
                ),
              ],
            ),
          ),
          onTap: () {
            WidgetsBinding.instance.addPostFrameCallback((_) {
              Navigator.of(context).push(MaterialPageRoute(builder: (context) => const SecondRoute()));
            });
          },
        )
      ),
    );
  }
}

class SecondRoute extends StatelessWidget {
  const SecondRoute

  ({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Second Route'),
      ),
      body: Center(
        child: ElevatedButton(
          onPressed: () {
            Navigator.pop(context);
          },
          child: const Text('Go back!'),
        ),
      ),
    );
  }
}

```

</details>


https://user-images.githubusercontent.com/67046386/215087969-12954100-0b43-4d5c-8801-829c0f98fbfa.mov

Please check if using above code still triggers the same error at your end or not. If not, please provide relevant details so that the issue is reproducible.
