### ISSUE TITLE
auto-submit bot files p1 on reverted PRs even if they were approved

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#119288]
For example: https://github.com/flutter/flutter/issues/119274

The bot should detect if a PR already received the requisite approvals and not open a P1 (that is, treat it as if it had the `autosubmit` label on it).

**Comment by godofredoc** [comment]
@ricardoamador FYI

**Comment by ricardoamador** [comment]
Okay. Should not be a hard fix.

**Comment by ricardoamador** [comment]
This is no longer needed as the filing of follow up reviews has been removed.
