### ISSUE TITLE
m2crypto salt state failing to deploy on new devicelab mac hosts

### ISSUE THREAD

**Issue by yusuf-goog** [flutter/flutter#119298]
When setting up new mac-47 host, m2crypto=0.36.0 is failing to deploy.

Manually installing 0.38.0 seems to work.

This currently only effects new machines, because existing devices already have m2crypto installed.

Potential fix is to the remove the version restriction in salt states for mac, to allow the newer version to install. But this is blocked on getting access to the salt dev server to test/deploy the change.

Working on this with salt master owners to get access.

**Comment by ricardoamador** [comment]
Possible option is to move to vpython.

**Comment by yusuf-goog** [comment]
I was able to hack a workaround if we really need to use it to get 0.36.0 installed.

But we just got access to a new salt master server, and can try pushing some changes to upgrade to the newest version of m2crypto and see if that ends up working.

**Comment by yusuf-goog** [comment]
Updated on our new salt server.
