### ISSUE TITLE
Samsung Gallery SIII mini only hits ~30fps when scrolling

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#11938]
The Samsung Gallery S III mini (in our device rack) only hits ~30fps when scrolling.

I'm using flutter_gallery on 93438245f047cb0e199a32fc6d428ee0f7f588b6.

![flutter_03](https://user-images.githubusercontent.com/11857803/30086273-2f1bd95c-924f-11e7-84ef-554637e7bb0d.png)

**Comment by eseidelGoogle** [comment]
This is a 5 year old phone:
http://www.gsmarena.com/samsung_i8190_galaxy_s_iii_mini-5033.php

Using a Mali 400 (Which is a very popular GPU).

**Comment by markusaksli-nc** [comment]
Is this still relevant?

**Comment by danagbemava-nc** [comment]
Closing this since the device in question has been discontinued.
