### ISSUE TITLE
ListBody RTL

### ISSUE THREAD

**Issue by abarth** [flutter/flutter#11930]
ListBody (and RenderListBody) need support for RTL.  We should probably implement all four AxisDirections, similar to scrolling.

**Comment by Hixie** [comment]
Do you think we should implement this with RenderListBody just having an AxisDirection instead of an Axis, or should we implement this with RenderListBody having an Axis, a TextDirection, and a VerticalDirection?

**Comment by abarth** [comment]
The clients probably want to supply `axis`, `reverse`, and an inherited `textDirection`.  For scrolling, we get away with that because we have the extra `ScrollView` widget to boil that down to an `AxisDirection`.  I'd have to look at code more closely to see if there's similar room to maneuver here.

**Comment by Hixie** [comment]
Sure, that's straight-forward. ListBody can add a `bool reverse` to its API, and boil that plus its `Axis axis` and if necessary a [Directionality.of] call to an `AxisDirection` that it then passes to the RenderListBody.

**Comment by abarth** [comment]
Depends if you want the basic widget to have an API that's so different from its render object.

**Comment by Hixie** [comment]
I think that's fine. We've long crossed that bridge with other widgets.
