### ISSUE TITLE
Fuchsia EMU emulator fails (to start up?) in flaky way

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#119356]
Failures like the following are currently happening several times a day:

https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20Fuchsia%20FEMU/27238/overview

The error message is:
```
Timed out waiting for the ffx daemon on the Overnet mesh over socket /b/s/w/ir/x/t/ascendd.
Run `ffx doctor --restart-daemon` for further diagnostics.
```

It looks like this started happening following the Fuchsia SDK roll at:

https://github.com/flutter/engine/commit/3d6b6effb775104cf691fc758f3be9a03961bb38

Marking P2 because this is intermittently closing the tree and causing presubs to fail (which blocks rolls).

I don't know whether this is an issue in Flutter infra, or an issue with the Fuchsia SDK, so I am adding tags for both.

**Comment by zanderso** [comment]
Also cc @dnfield in case this is a `fuchsia_ctl` issue.

**Comment by zanderso** [comment]
Turned on more verbose logging here https://flutter-review.git.corp.google.com/c/recipes/+/38284, and the Fuchsia team is investigating. Leaving assigned to me to track.

**Comment by godofredoc** [comment]
Blocked on changes from the Fuchsia Team and a change to recipe-engine.

**Comment by zanderso** [comment]
This is resolved.
