### ISSUE TITLE
Wrong directory location on codelab document

### ISSUE THREAD

**Issue by sunglim** [flutter/flutter#11931]
Just a minor doc issue.

`/ios/Assets.xcassets` should be `/ios/Runner/Assets.xcassets`
on https://codelabs.developers.google.com/codelabs/flutter-firebase/#4

![image](https://user-images.githubusercontent.com/756988/30048423-0a29e6be-9251-11e7-8dd4-59b82c6513c7.png)

In real
![image](https://user-images.githubusercontent.com/756988/30048468-4c3a19d4-9251-11e7-9d7c-261c2f603177.png)

**Comment by mit-mit** [comment]
cc @LarkAscending

**Comment by LarkAscending** [comment]
Good catch! The missing ios/subfolder is a throwback to the predecessor of this codelab. Fixed:
https://codelabs.developers.google.com/codelabs/flutter-firebase
