### ISSUE TITLE
Execution failed for task ':app:compileFlutterBuildDebug'

### ISSUE THREAD

**Issue by Adebayo2016** [flutter/flutter#119374]
## Steps to Reproduce

1. Project working well initially 
2. added FCM library and everything stooped working 
3. Error keeps appearing even after updating flutter 
4. Full log is attached to this.  

## Logs
FAILURE: Build failed with an exception.
[   +1 ms] * Where:
[        ] Script 'C:\Users\user\Documents\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1151
[   +1 ms] * What went wrong:
What went wrong:
[        ] Execution failed for task ':app:compileFlutterBuildDebug'.
[        ] > Process 'command 'C:\Users\user\Documents\flutter\bin\flutter.bat'' finished with non-zero exit value 1

<details>
<summary>Logs</summary>

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.7.0, on Microsoft Windows [Version 10.0.19045.2486], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    ! Some Android licenses not accepted. To resolve this, run: flutter doctor --android-licenses
[√] Chrome - develop for the web
[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2021.2)
[√] VS Code (version 1.74.2)
[√] Connected device (4 available)
[√] HTTP Host Availability

! Doctor found issues in 2 categories.

</details>
[flutter error report.txt](https://github.com/flutter/flutter/files/10523463/flutter.error.report.txt)

**Comment by huycozy** [comment]
@Adebayo2016 From your logs:

```
[  +40 ms] Running Gradle task 'assembleDebug'... (completed in 34.2s)
[+3329 ms] ../../AppData/Local/Pub/Cache/hosted/pub.dev/modal_bottom_sheet-2.1.2/lib/src/bottom_sheets/material_bottom_sheet.dart:28:13: Error: 'ModalBottomSheetRoute' is imported from both
'package:flutter/src/material/bottom_sheet.dart' and 'package:modal_bottom_sheet/src/bottom_sheet_route.dart'.
[   +7 ms]       .push(ModalBottomSheetRoute<T>(
[        ]             ^^^^^^^^^^^^^^^^^^^^^
[        ] ../../AppData/Local/Pub/Cache/hosted/pub.dev/modal_bottom_sheet-2.1.2/lib/src/bottom_sheets/material_bottom_sheet.dart:50:10: Error: A value of type 'Object?' can't be returned from an async function with return type
'Future<T?>'.
[   +1 ms]  - 'Object' is from 'dart:core'.
[        ]  - 'Future' is from 'dart:async'.
[        ]   return result;
[        ]          ^
[   +1 ms] ../../AppData/Local/Pub/Cache/hosted/pub.dev/modal_bottom_sheet-2.1.2/lib/src/bottom_sheets/bar_bottom_sheet.dart:102:13: Error: 'ModalBottomSheetRoute' is imported from both
'package:flutter/src/material/bottom_sheet.dart' and 'package:modal_bottom_sheet/src/bottom_sheet_route.dart'.
[   +1 ms]       .push(ModalBottomSheetRoute<T>(
[        ]             ^^^^^^^^^^^^^^^^^^^^^
[        ] ../../AppData/Local/Pub/Cache/hosted/pub.dev/modal_bottom_sheet-2.1.2/lib/src/bottom_sheets/bar_bottom_sheet.dart:125:10: Error: A value of type 'Object?' can't be returned from an async function with return type
'Future<T?>'.
[   +1 ms]  - 'Object' is from 'dart:core'.
[        ]  - 'Future' is from 'dart:async'.
[        ]   return result;
[        ]          ^
[+8157 ms] Exception: Gradle task assembleDebug failed with exit code 1
[   +9 ms] "flutter run" took 51,270ms.
```
It's `modal_bottom_sheet`'s issue rather than Flutter itself. Please open the issue in the dedicated [repository](https://github.com/jamesblasco/modal_bottom_sheet/issues).
For quick search results, you may follow this issue https://github.com/jamesblasco/modal_bottom_sheet/issues/311 for updates (it's already had a migration at https://github.com/jamesblasco/modal_bottom_sheet/issues/325).

Closing, as this isn't an issue with Flutter itself.
