### ISSUE TITLE
Apply ColorFilter with bounds.

### ISSUE THREAD

**Issue by SilentCatD** [flutter/flutter#119341]
## Use case

I have a widget that need to be applied the ColorFilter effect srcATop over it, but I want just a portion of the widget have this effect applied, not the whole one. This is currently my paint function.
`

```
void _paintColor(PaintingContext context, Offset offset,
      PaintingContextCallback paintChild) {
    assert(color != null);
    _handle.layer ??= ColorFilterLayer();
    _handle.layer!.colorFilter = ColorFilter.mode(
      color!,
      BlendMode.srcATop,
    );
    context.pushLayer(_handle.layer!, paintChild, offset);
  }
```

A work around for this is using ShaderMask, create a ShaderMask by LinearGradient.createShader function with the same color value, and `maskRect` to set the bound of the effect applied on the new widget.

My work around right now:

  ```
void _paintColor(PaintingContext context, Offset offset,
      PaintingContextCallback paintChild) {
   Size maskSize = ...;
   final maskRect = offset & maskSize;
    _handle.layer ??= ShaderMaskLayer();
    _handle.layer!
      ..shader = LinearGradient(
              tileMode: TileMode.decal, colors: [color, color])
          .createShader(Offset.zero & maskSize)
      ..maskRect = maskRect
      ..blendMode = BlendMode.srcATop;
    context.pushLayer(_handle.layer!, paintChild, offset);
  }
```

## Proposal

It would be nice if the ColorFilter layer have property that similar to maskRect, that allow you to set the boundaries for applying the ColorFilter effect.

**Comment by jonahwilliams** [comment]
I don't think we're going to change how compositing works for color filters. INstead consider using a backdrop filter + clip rect with your color filter instead
