### ISSUE TITLE
[image_picker]  ImagePicker and rootBundle.load returns different bytes for exactly same image

### ISSUE THREAD

**Issue by theideasaler** [flutter/flutter#119316]
## Details
I have one exactly same image in the gallery, and under `assets` folder in flutter project.

I picked the image from `ImagePicker` and load the same image from the `assets` folder. I found the bytes from `ImagePicker` is different than bytes from `rootBundle.load`. If I try to compare the checksum hash of the two files using [cypto](https://pub.dev/packages/crypto), I got two different hashes.

```dart
// Image picker
final imageFromPicker = await ImagePicker().pickImage(
      source: ImageSource.gallery,
      imageQuality: 100,
      requestFullMetadata: true,
    );
final bytesFromPicker = await imageFromPicker.readAsBytes();
final hashOfImageFromPicker = sha256.convert(bytesFromPicker).toString();

// rootBundle
final imageFromAsset = await rootBundle.load('assets/sample.png');
final bytesFromAsset = imageFromAsset.buffer.asUint8List();
final hashOfImageFromAsset = sha256.convert(bytesFromAsset).toString();

print((hashOfImageFromPicker == hashOfImageFromAsset).toString()); // false
```

However, I used this online file checksum tool https://emn178.github.io/online-tools/sha256_checksum.html and uploaded the same image from gallery on simulator, and the hash returned is same as `hashOfImageFromAsset`.  

So I was wondering if ImagePicker will modify the image content during uploading, since I observed that the bytes length from ImagePicker is slightly larger than the bytes length from `rootBundle.load`

Please let me know how I can get the original image's bytes data and get the same sha256 as `rootBundle` and the online tool.

**Target Platform:** iOS
**Target OS version/browser:** 16.2
**Devices:** iPhone14 Simulator

**Comment by darshankawar** [comment]
Thanks for the report. I'll leave this issue open for team to share their thoughts on the use case you described, as I don't have enough info / findings to share.

/cc @stuartmorgan
