### ISSUE TITLE
Add "inactiveBorderColor" to Material 3 Switch

### ISSUE THREAD

**Issue by shadowmelds** [flutter/flutter#119334]
## Use case

Like:

```dart
Switch(
  value: dark,
  inactiveBorderColor: Colors.white
  onChanged: (bool value) {
    setState(() {
      dark = value;
    });
  },
),
```

## Proposal

Now i can't change the border color😔

![微信截图_20230127225414](https://user-images.githubusercontent.com/25096408/215116447-c997a8d1-3141-49c9-9052-f4a78b3a2248.png)

**Comment by MarcAnProv** [comment]
Is there no possible way to change the border color when the switch is inactive for now? Would really like this feature as well.
