### ISSUE TITLE
I want to play long movie video in my flutter app getting slow response.

### ISSUE THREAD

**Issue by swajahathz** [flutter/flutter#119382]
I developed my movie flutter app using API for fetching data. everything running smoothly. just facing one problem with playing movie using. when I play a small video player works fine and loads fast. but when I use the long movie URL getting to much time to open the player. the first app downloads the complete video and then plays it. 

_videoPlayerController = VideoPlayerController.network(
     "https://filesamples.com/samples/video/mkv/sample_1280x720_surfing_with_audio.mkv",
    )..initialize().then((value) {

      setState(() {});
    });

please tell me any solution. this is just testing video 62 MB this video also takes time. just 1 to 2 MB video play fast. my movies file a minimum of 1 GB so they take a lot of time on loading players. I want to play video like buffering if the net is slow then start buffer. but the player shows at first take. and start the video playing.

**Comment by darshankawar** [comment]
@swajahathz 
Can you provide `flutter doctor -v`, plugin version and platform on which you are seeing this behavior ?

**Comment by swajahathz** [comment]
[√] Flutter (Channel stable, 3.3.4, on Microsoft Windows [Version 10.0.19045.2364],
    locale en-US)
    • Flutter version 3.3.4 on channel stable at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision eb6d86ee27 (4 months ago), 2022-10-04 22:31:45 -0700
    • Engine revision c08d7d5efc
    • Dart version 2.18.2
    • DevTools version 2.15.0

[√] Android toolchain - develop for Android devices (Android SDK version
    32.1.0-rc1)
    • Android SDK at C:\Users\Syed Sahab\AppData\Local\Android\sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of
      its default components

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] VS Code (version 1.75.0)
    • VS Code at C:\Users\Syed Sahab\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (4 available)
    • SM A715F (mobile) • adb-R58NC0CMWLM-YaEMb4._adb-tls-connect._tcp •
      android-arm64  • Android 13 (API 33)
    • Windows (desktop) • windows                                      •
      windows-x64    • Microsoft Windows [Version 10.0.19045.2364]
    • Chrome (web)      • chrome                                       •
      web-javascript • Google Chrome 109.0.5414.120
    • Edge (web)        • edge                                         •
      web-javascript • Microsoft Edge 109.0.1518.78

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
@darshankawar

**Comment by darshankawar** [comment]
@swajahathz 
I suggest you to upgrade to latest stable and make sure you are using latest plugin version and verify again.
Also, can you also try the same url in native app (android) and see whether you get the same behavior or not ?
