### ISSUE TITLE
Create a migration guide for Material 3

### ISSUE THREAD

**Issue by guidezpl** [flutter/flutter#119319]
https://m3.material.io/develop/flutter is the hub on material.io for Material 3 on Flutter. We should create a migration guide.

Existing guides include
- https://material.io/blog/migrating-material-3 for Android Views
- https://developer.android.com/jetpack/compose/designsystems/material2-material3 for Jetpack Compose

I should also note https://blog.codemagic.io/migrating-a-flutter-app-to-material-3/ from @TahaTesser, @HansMuller is there anything missing from it?

**Comment by TahaTesser** [comment]
I'd be happy to update the article to include anything missing.

**Comment by rydmike** [comment]
@TahaTesser the article is great as it is, but if you have the opportunity, time and energy to update it, here are my suggestions:

- The easy to use `NavigationDrawer` is mentioned, but it would be lovely to also see a teaser visual of it.
- The `DropdownMenu` is not mentioned. It would be fabulous if it could be added. This new component is really wonderful and one that has been desperately asked for by many developers. Building something like it manually has been quite a challenging task to do in the past. Now it is finally available out of the box, and it is really good! 
- The new `MenuBar` and `MenuAnchor` could deserve a mention too, with some simple visuals of them.
- This might make it a bit long, but I think it could be of general interest to point out the clever re-use of shared building blocks in `DropdownMenu`, `MenuBar` and `MenuAnchor`. Plus how the core of their flexible styling and theming capabilities is in large part built with the existing `ButtonStyleButton` and `ButtonStyle` via `MenuItemButton`, used by the already familiar Material buttons. Resulting in that menu items in all of them can have all of its  powerful props and theming capabilities. These all also make great building block for making totally custom versions as well or new variants not thought of here. Although the out-of-the box ones, are so flexible and well designed I doubt there are many reasons to do so.
- Other new and updated components that could be briefly mentioned and shown are `Badge` (could be added e.g. to the shopping cart FAB icon and mentioned) and `BottomAppBar`, that has a significantly changed style in M3.

**Comment by TahaTesser** [comment]
@rydmike Thank you so much for your valuable feedback!
