### ISSUE TITLE
TabBar Windows 10 (Desktop), cannot swipe left right using mouse.

### ISSUE THREAD

**Issue by brilliapps** [flutter/flutter#119386]
Flutter 3.7 (as far as i remember 3.3.10 was the same) As in the title.  **Not sure if i use the "swipe" word correctly** in this case i mean moving left right some content using a finger. I can of course move left right tabs of a horizontal tabbar using fingers, but not something similar using the computer's mouse or touchpad like clickDown event and moving left/right or doubleClickDown and moving left/right. Is it just me? 

Some additional information. If the foregoing is enough there is no need to read carefully what is below.
As i can remember, some gif-like animation i found today showed using mouse for swiping to see the hidden tabs IS possible, but it was a mobile device not desktop windows.
To solve this for now i needed to add buttons on the left and right of the tab bar and using the tab bar's controller tabBarTabController.animateTo(tabBarTabController.index - 1) which works fine and with this controller the tabbar didn't loose it's own natural behaviour which is great and i can see one by one the hidden tabs when the index changes. 
Hovever a related TabBarView also changes it's children according to what animateTo does with tabbar. So would need know if i can do something more just to swipe the tabs left or right using mouse without changing views as i can just do using touch gestures.
Btw. i know that not all non-flutter applications allow swiping in or left using mouse. And i did some research before adding this question, and am tired, so i appologize for this questiong if i could do even more research.

**Comment by moffatman** [comment]
You're right, by default only "touch" devices are allowed to drag content, including scroll views and page views like the `TabBarView`. You could change the default `ScrollConfiguration` in your `MaterialApp` / `CupertinoApp`.

For example:

```dart
return MaterialApp(
  scrollBehavior: const MaterialScrollBehavior().copyWith(
    dragDevices: {
      ...PointerDeviceKind.values
    }
  ),
  home: const MyHomePage()
);
```

I used `{...PointerDeviceKind.values}` to indicate all devices. But you could also choose specific devices by listing them in the set.

You can see the default devices below

https://github.com/flutter/flutter/blob/e349bdc1a2e27d5539f355be07a4c50f1fb59aab/packages/flutter/lib/src/widgets/scroll_configuration.dart#L17-L26

**Comment by brilliapps** [comment]
Yeaahh! he he. It works! It couldn't be otherwise. Thank you!
For the moment i just used this part:
```dart
scrollBehavior: const MaterialScrollBehavior()
          .copyWith(dragDevices: {...PointerDeviceKind.values}),
```
Thank you again and it seems that this exhausted everything what i need for the moment. Some other parts of my question i can figure out on my own. Tabs and tab views can shwich synchronously as they do on clicking the mentioned back and forward buttons. Swiping on windows desktop now does the job.
