### ISSUE TITLE
@mdebbar @marcosmko @fearlessambassador After going deep into this, I was able to create a workaround. I'll put my findings together and organize my code before explaining it here. Please link the new issue here if one of you files it.

### ISSUE THREAD

**Issue by Bilonik** [flutter/flutter#119395]
@mdebbar @marcosmko @fearlessambassador After going deep into this, I was able to create a workaround. I'll put my findings together and organize my code before explaining it here. Please link the new issue here if one of you files it.

_Originally posted by @behnamsattar in https://github.com/flutter/flutter/issues/86776#issuecomment-1120071250_

Hi,

How did you fix this? Having the same issue.

Thanks

**Comment by darshankawar** [comment]
@Bilonik 
Please don't open issues using comments as a reference. I recommend to use new issue template and fill out requested details so that we'll have enough info to work with.

Closing for now due to lack of details.

**Comment by mdebbar** [comment]
I'm going to unsubscribe and lock this issue. Please file a new issue from a template with some more details and a proper title.
