### ISSUE TITLE
Add support for creating `ColorScheme`s from content

### ISSUE THREAD

**Issue by guidezpl** [flutter/flutter#119333]
There are [new guidelines on content color](https://m3.material.io/styles/color/dynamic-color/user-generated-color#8af550b9-a19e-4e9f-bb0a-7f611fed5d0f), which is distinct from wallpaper-based color.

<img width="693" alt="image" src="https://user-images.githubusercontent.com/6655696/215110197-fef1bf93-0c95-40bf-ab1f-d10b8b6e11ec.png">

Already available in Material Color Utilities, we just need to provide API in the framework similar to the existing wallpaper-based color scheme creation.

**Comment by MaxYablochkin** [comment]
@guidezpl 

![image](https://user-images.githubusercontent.com/102767277/215227008-2e66507a-b3da-459f-acfb-7ecd4db756b4.png)
![image](https://user-images.githubusercontent.com/102767277/215227046-e852c9ac-545c-466c-af0c-fd0ccb830a5c.png)

The specification says that the base color scheme will be based on the content in the application, but on the other hand, the base color of the M3 scheme is purple. Ultimately, the first will complement the second? If so, would it still be possible to use the M3 base purple color without explicitly specifying a value (0xff6750a4)?
