### ISSUE TITLE
Can the error message that suggests asking issues here be removed?

### ISSUE THREAD

**Issue by mycar98765** [flutter/flutter#119383]
I get an error and it says this in the error message:

```
Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md
```

Following the error message, I asked [this issue](https://github.com/flutter/flutter/issues/119329#issue-1559734972), but it was closed. Why?

If such issue will be closed, can the error message prompting to ask issues here be removed?

**Comment by exaby73** [comment]
Closing this issue as per https://github.com/flutter/flutter/issues/119329#issuecomment-1408043261
