### ISSUE TITLE
Restrict Mac codesign and device_doctor build to non-device lab hosts

### ISSUE THREAD

**Issue by yusuf-goog** [flutter/flutter#119366]
It looks like the [Mac codesign](https://luci-milo.appspot.com/p/flutter/builders/prod/Mac%20codesign) build might not require a mobile device to run.

If so, can we restrict this build to non devicelab hosts to free up scarce resources, and instead run them on chromelab machines.

**Comment by yusuf-goog** [comment]
Potentially adding the following to builds in .ci.yaml: 
 `device_type: none`

**Comment by ricardoamador** [comment]
Is this an infra ticket queue item?

**Comment by jmagman** [comment]
@yusuf-goog are the necessary signing certs available on non-devicelab machines?

**Comment by yusuf-goog** [comment]
I say yes? because there are builds that have run successfully on non-devicelab bots:

https://luci-milo.appspot.com/ui/p/flutter/builders/prod/Mac%20codesign/226/overview

**Comment by yusuf-goog** [comment]
@ricardoamador normally I would normally say this _not_ a ticket queue item, but there is somewhat of a timebased impact, i.e., we want to remove the old iphones, and need to make sure that there are no variations of these jobs that need to run on those devices.

**Comment by yusuf-goog** [comment]
Adding mac device_doctor build as well to this list.

**Comment by yusuf-goog** [comment]
PR submitted.
