### ISSUE TITLE
Add a nav example app to the Sample Catalog

### ISSUE THREAD

**Issue by LarkAscending** [flutter/flutter#11939]
## Steps to Reproduce

The [Sample Catalog](https://flutter.io/catalog/samples/) needs an example of a multi-page app, with navigation.

See: https://groups.google.com/forum/#!topic/flutter-dev/Oc3OU1ZuN9U

/cc @Kimi-Arthur

**Comment by zoechi** [comment]
There is now 
https://flutter.io/docs/development/ui/navigation
https://flutter.io/docs/cookbook/navigation/navigation-basics
https://github.com/flutter/samples/blob/master/INDEX.md#whattodo--
https://github.com/flutter/samples/blob/master/INDEX.md#shrine-flutter-team
https://github.com/flutter/samples/blob/master/INDEX.md#flutter-gallery-flutter-team

and probably others that demonstrate navigation.
Do you think there should be more?

**Comment by iapicca** [comment]
Hi @LarkAscending 
given this [answer ](https://github.com/flutter/flutter/issues/11939#issuecomment-450178801)I feel safe to close this issue,
if you disagree please write in the comments
and I will reopen it. 
Thank you
