### ISSUE TITLE
[CP] null check error during gen_l10n

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#119385]
### issue_link

https://github.com/flutter/flutter/issues/119181

### Commit Hash

117a83a4a7178c328d296748bd93ff388724cb67

### Target

stable

### pr_link

https://github.com/flutter/flutter/pull/119384

### Impacted Users

users with generated localizations

### Impact Description

the code that parses flutter app arb files has been made to more accurately follow the spec, and thus certain syntax errors in customer app code that was accepted previously will now crash with an unfriendly error message.

### Workaround

Practically speaking no (the user would have to be able to determine the line in their configuration that was wrong without an actionable error from the tooling).

### Risk

low

### Test Coverage

yes

**Comment by zanderso** [comment]
CP lgtm
