### ISSUE TITLE
Flutter `master` channel version needs updating

### ISSUE THREAD

**Issue by timsneath** [flutter/flutter#119469]
Whenever we ship a new stable release, we need to get into the habit of bumping the `master` channel version, ideally before we publish to the `stable` channel. Otherwise we get something like the following:

```
[C:\src\fluent_ui] flutter pub get

┌─────────────────────────────────────────────────────────┐
│ A new version of Flutter is available!                  │
│                                                         │
│ To update to the latest version, run "flutter upgrade". │
└─────────────────────────────────────────────────────────┘
Running "flutter pub get" in fluent_ui...
Resolving dependencies...
The current Flutter SDK version is 3.7.0-13.0.pre.41.

Because fluent_ui requires Flutter SDK version >=3.7.0, version solving failed.
pub get failed
command: "c:\src\flutter\bin\cache\dart-sdk\bin\dart __deprecated_pub --color --directory . get --example"
pub env: {
  "FLUTTER_ROOT": "c:\src\flutter",
  "PUB_ENVIRONMENT": "flutter_cli:get",
  "PUB_CACHE": "C:\Users\timsneath\AppData\Local\Pub\Cache",
}
exit code: 1
```

Here, package https://github.com/bdlukaa/fluent_ui has updated its dependency to the latest `stable` version (3.7.0), but the `master` semver shows it as older, even though that's not really true. 

/cc @CaseyHillers

**Comment by CaseyHillers** [comment]
/cc @itsjustkevin 

The issue here is we didn't increment to 3.8 in January and saved it for February.

Kevin, regardless if we ship the Y version, we should require it gets incremented every month to prevent issues like this.

**Comment by itsjustkevin** [comment]
thanks for calling this out @timsneath.  And yes this is a correct call out @CaseyHillers!  

The logic was updated to stop this from happening but we didn't consider this edge case.  

While I do feel that updating it on a monthly basis solves some problems, we should still have some "break in case of emergency" method in case we encounter other edge cases we did not consider.

**Comment by CaseyHillers** [comment]
When we did Flutter 2 -> 3, we had a similar issue. We manually did the 3.0.0 tag, and pushed the 3.1.0.pre along with it

https://github.com/flutter/flutter/tree/flutter-3.8-candidate.0 was created.

```
Flutter 3.8.0-1.0.pre.1 • channel master • git@github.com:flutter/flutter
```
