### ISSUE TITLE
Hero should link to something that explains what a Hero Animation is

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#11941]
https://docs.flutter.io/flutter/widgets/Hero-class.html

Doesn't link to any part of the Material Design spec which explains/shows what a hero animation is.  It's not clear to me (from some minimal searching) that hero is a term which is used in Material?

**Comment by eseidelGoogle** [comment]
This is of course not to be confused with "Hero Images" which are defined in the MD spec, and refer to app-bar images: https://material.io/guidelines/style/imagery.html#imagery-ui-integration

**Comment by zoechi** [comment]
Perhaps making "hero animations" text (2x) a link to https://flutter.io/docs/development/ui/animations/hero-animations which explains it well
