### ISSUE TITLE
Please fix printing for flutter.io pages

### ISSUE THREAD

**Issue by Sfshaza** [flutter/flutter#11942]
It can be difficult to read a page printed from flutter.io. See attached example.

<img width="468" alt="screen shot 2017-09-05 at 4 02 45 pm" src="https://user-images.githubusercontent.com/6293442/30087150-d4e07786-9253-11e7-821e-ea8f328fd197.png">

**Comment by kwalrath** [comment]
Fixed by flutter/website#767.
