### ISSUE TITLE
text_input.dart:1163:8: Context: 'TextInputClient.didChangeInputControl' is defined here.

### ISSUE THREAD

**Issue by jinyuanqing** [flutter/flutter#119400]
**flutter for web.
[√] Flutter (Channel stable, 3.7.0, on Microsoft Windows [版本 10.0.22621.1105], locale zh-CN)
[X] Windows Version (Unable to confirm if installed Windows version is 10 or greater)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[√] Chrome - develop for the web
[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[!] Android Studio (version 2022.1)
    X Unable to find bundled Java version.
[√] Connected device (3 available)
[√] HTTP Host Availability**

 
**

```
/D:/beifen/flutter/packages/flutter/lib/src/services/text_input.dart:1163:8: Context: 'TextInputClient.didChangeInputControl' is defined here.

  void didChangeInputControl(TextInputControl? oldControl, TextInputControl? newControl) {}
       ^^^^^^^^^^^^^^^^^^^^^
/D:/beifen/flutter/packages/flutter/lib/src/services/text_input.dart:1184:8: Context: 'TextInputClient.performSelector' is defined here.
  void performSelector(String selectorName) {}
       ^^^^^^^^^^^^^^^

Failed to compile application.
```

**

**Comment by huycozy** [comment]
@jinyuanqing Can you provide the complete output of `flutter run -v` and a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this?

**Comment by gomcodoctor** [comment]
same issue I am facing after upgrading to flutter 3.7.0

**Comment by vladmiroshnikov** [comment]
1. delete 'build'
2. delete 'pubspec.lock'
3. flutter pub get

**Comment by gomcodoctor** [comment]
![image](https://user-images.githubusercontent.com/10648299/216325151-f30c7327-3d39-4359-8fb5-0d5dce7fe08e.png)

Same issue even after deleting build and pub lock file

**Comment by bleroux** [comment]
@gomcodoctor The error you get is related to one of your project dependency: "flutter_chips_input". I would suggest opening an issue on flutter_chips_input GitHub project to ask the author to publish a version compatible with Flutter 3.7.

**Comment by abom-me** [comment]
I have same issue , and i cant find the solution

**Comment by jinyuanqing** [comment]
> 
Sorry, I've reverted to the old version.now flutter3.3.7

**Comment by huycozy** [comment]
@jinyuanqing Without more information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug if no further response from others.

@abom-me Can you provide the complete output of `flutter run -v` and a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this?
