### ISSUE TITLE
[Feature Request] Allow geometry and color primitives to be used in non-Flutter projects

### ISSUE THREAD

**Issue by cbatson** [flutter/flutter#119424]
## Use case

Flutter, or more precisely `dart:ui`, includes several useful geometry and other primitives (examples include `Rect`, `Offset`, `Size`, `Color`, etc.) which have no dependence on the engine.

It would be handy in some scenarios, such as offline processing tools, to have access to these primitives in a non-Flutter project.

Attempting to import `dart:ui` in a pure Dart project results in an error, making these primitives inaccessible outside of Flutter.

See also [How can I use dart:ui in a command line Dart application?](https://stackoverflow.com/q/64940969) (not authored by me).

## Proposal

Perhaps leaf classes like the aforementioned with no dependence on the engine could be broken out into a separate package.

Thank you.

**Comment by jonahwilliams** [comment]
We have no plans to do this. Though these classes are not native methods, other native methods depend on their exact representation and separating into a different library or package is infeasible.
