### ISSUE TITLE
Clarify how Stack positions its children

### ISSUE THREAD

**Issue by LarkAscending** [flutter/flutter#11943]
## Steps to Reproduce

The 3rd and 4th paragraphs of the API doc for [Stack](https://docs.flutter.io/flutter/widgets/Stack-class.html) seem to contradict each other:

> Each child of a Stack widget is either positioned or non-positioned. Positioned children are those wrapped in a Positioned widget that has at least one non-null property. The stack sizes itself to contain all the non-positioned children, which are positioned according to alignment (which defaults to the top-left corner). The positioned children are then placed relative to the stack according to their top, right, bottom, and left properties.
> 
> The stack paints its children in order with the first child being at the bottom.

See https://groups.google.com/forum/#!topic/flutter-dev/Oc3OU1ZuN9U

## Discussion
The 3rd paragraph is talking about Stack sizing, as well as default alignment for non-positioned children (top-left). The 4th paragraph is talking about the order in which children are painted (bottom to top). So maybe there's no contradiction here? Still, user confusion...

Salient points seem to be:
* only non-positioned children influence the size of a Stack
* if non-positioned children do not specify an alignment, they go in the top-left corner
* positioned children are placed relative to the Stack, not relative to the non-positioned children
* for positioned children, property values determine where they're placed
* there is a use case for changing the order in which a Stack paints its children (maybe it would help to clarify why you would want to do that)

cc/@Kimi-Arthur

**Comment by cbracken** [comment]
@HansMuller @goderbauer is this still an issue?

**Comment by goderbauer** [comment]
The documentation seems correct to me.
