### ISSUE TITLE
Two-dimensional scrolling

### ISSUE THREAD

**Issue by masreplay** [flutter/flutter#119458]
Is there a way to use Two-dimensional scrolling as mentioned in this [video ](https://www.youtube.com/watch?v=UDZ0LPQq-n8
)
 before the release

**Comment by darshankawar** [comment]
@masreplay 
The feature is not ready / available yet as mentioned in the video. You may follow the project for latest updates https://github.com/orgs/flutter/projects/32

Closing this issue.
