### ISSUE TITLE
Listview builder with scroll to index feature ?

### ISSUE THREAD

**Issue by harryandroiddev** [flutter/flutter#119491]
Listview builder does not support to scroll a list to a specific item with index , i have found solution that  [ScrollablePositionedList]
can be used to scroll to specific index but it uses ItemScrollController, which does not support controller.addListener() property .
One should have both the properties .

**Comment by stevenosse** [comment]
I feel like this issue would be much more relevant on https://github.com/google/flutter.widgets/tree/master/packages/scrollable_positioned_list

**Comment by harryandroiddev** [comment]
With list view build i can detect the user scroll direction

**Comment by exaby73** [comment]
`ScrollablePositionedList` has a [`scrollDirection`](https://pub.dev/documentation/scrollable_positioned_list/latest/scrollable_positioned_list/ScrollablePositionedList/scrollDirection.html) property that allows you to set he scroll direction.

If you want to use a `ListView`, here's an example of how you can do it: https://gist.github.com/gaaclarke/4200741c4413707f0f73a887bf5d9b39

**Comment by harryandroiddev** [comment]
the scroll direction property is used to set the list direction not the scroll listener , to listen where the user is scrolling the list
