### ISSUE TITLE
library "libflutter.so" not found

### ISSUE THREAD

**Issue by YuJeong-Jang** [flutter/flutter#119490]
I dont understand what is this problum.
I already tried add  

defaultConfig {
      ...
      ndk.abiFilters "armeabi", "x86", "armeabi-v7a"
}

and 

bundle {
    abi {
        enableSplit = false
    }
}
but it is not work.

I can run, but when i upload on google store, this message occoured.

<img width="1177" alt="스크린샷 2023-01-30 오후 2 34 23" src="https://user-images.githubusercontent.com/84840432/215397593-7a36b7b9-f1b7-4b69-8051-33e877d12178.png">

and my flutter doctor attach together.
![스크린샷 2023-01-30 오후 2 55 53](https://user-images.githubusercontent.com/84840432/215398335-5deb4ce8-d0b2-47a2-a9ab-9bb30416f305.png)

**Comment by jonahwilliams** [comment]
x86 is not a supported ABI

**Comment by YuJeong-Jang** [comment]
> x86 is not a supported ABI

I deleted "x86" but still not working :(

**Comment by darshankawar** [comment]
Possibly related / similar to https://github.com/flutter/flutter/issues/57237, so @YuJeong-Jang please follow-up in it for further updates.
Closing this in favor of the linked issue. If you disagree, write in comments and I'll reopen it.
