### ISSUE TITLE
card_collection: text is all over the place

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#1194]
Launch card_collection.dart. The labels for "Item 0" and "Item 1" are in the right place but "Item 2" is above "Item 0", "Item 3" is between two of the cards, and the fourth card has two labels "Item 4" and "Item 5"...

cc @abarth since it looks like a compositor bug with lists, and that's _right_ up his alley right now. :-P

**Comment by abarth** [comment]
Yeah, I think this might be fixed in the engine release I'm doing currently.  Will check again after it lands.

**Comment by Hixie** [comment]
Pretty sure I was testing trunk/trunk, but maybe not?

**Comment by abarth** [comment]
I was so happy to get the masking working, I might have not noticed if the problem was still here.

**Comment by Hixie** [comment]
Material Gallery, Tabs demo, the icons don't move when switching pages. Smells like the same bug.

**Comment by Hixie** [comment]
Time Picker in Material Gallery is painted offset from where the layout thinks it is (as determined by hit testing). Looks like the same thing also.

**Comment by Hixie** [comment]
Commenting out the pushClipRRect logic (short-circuiting it to just call `painter(this, offset)`) fixes it.

**Comment by Hixie** [comment]
Specifically the second branch.

**Comment by Hixie** [comment]
I tried reverting that specific code to what we had before https://github.com/flutter/flutter/pull/1196 but it didn't fix it.

**Comment by Hixie** [comment]
Ok I give up. The bugs all seem to be caused by this pushClipRRect behaviour, but I can't work out exactly what the problem is.

**Comment by HansMuller** [comment]
Just FTR: the material gallery tabs and page selector demos fail in the same way.
