### ISSUE TITLE
Android Emulator results in black screen on Windows

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#11947]
We've started getting reports again:
https://github.com/flutter/flutter/issues/10617#issuecomment-326234813
https://github.com/flutter/flutter/issues/10617#issuecomment-326797703

I'm opening this new issue to track this reoccurrence.  @chinmaygarde @goderbauer @bkonyi 

@wmleler says he saw this at the instructor lead training for Flutter at Google Developer days.

**Comment by wmleler** [comment]
Most of us helping at the GDD codelab saw it.

Didn't happen on a real device. And it didn't happen to everyone on Windows
using the Android emulator, so might be difficult to reproduce. We didn't
have time to note the version of Windows or anything more about it. Sorry!

**Comment by wmleler** [comment]
One more interesting detail. If in the emulator you picked the right-hand (square) button, which shows all the apps running, the thumbnail for the Flutter app did show at least the app bar rather than a black screen, so the Flutter app does seem to be at least loading somewhere. But if you select that thumbnail and it opens the app, it still has a black screen.

**Comment by sethladd** [comment]
I saw it three independent times at the workshop.

**Comment by goderbauer** [comment]
I'll see if I can by any chance reproduce this on my Windows machine.

**Comment by eseidelGoogle** [comment]
There is `flutter doctor` output and setup details in the linked comments.

**Comment by goderbauer** [comment]
I can reproduce the black screen on Windows:
```
Android SDK built for x86 64 • emulator-5554 • android-x64 • Android 7.1.1 (API 25) (emulator)
```
with OpenGL ES API Level set to "Host maximum". It's gone when selecting "Compatibility".

**Comment by Hixie** [comment]
It's imperative that we have tests for this when we solve it. We keep having this problem.

**Comment by aakashshah94** [comment]
Having the same issue. Followed the exact steps to setup emulator. I was running emulator with api 26 and enabled hardware GLE 2.0 . still getting balck screen for every project I create.

**Comment by muku** [comment]
I experience the same issue. I'm using an Intel x86 Atom_64 system image for the emulator. API 25. My host system is running Windows 10 with intel hd 630 / nvidia gtx 1050. The app renders with software rendering.

**Comment by muku** [comment]
I found a workaround on Windows. I started my emulator from the command line passing the -gpu angle argument. It uses DirectX and works as a charm

**Comment by sethladd** [comment]
Thanks for the workaround!
