### ISSUE TITLE
ui.PlatformDispatcher.instance.sendPlatformMessage parameter reply , different value.

### ISSUE THREAD

**Issue by TrustOne** [flutter/flutter#119456]
Hello, I get error from MethodChannel, invokeMethod, and webview.
today, I Debugged my app and created new app only for error function.

and I got this result,  inside flutter/lib/src/services/binding.dart
this ->>>  Future<ByteData?> send(String channel, ByteData? message)
and inside this, -->> ui.PlatformDispatcher.instance.sendPlatformMessage(channel, message, (ByteData? reply) 
this method got different value of reply param.
see the below results,
this one is fine for param reply, which is created today for only function
![image](https://user-images.githubusercontent.com/2093148/215333204-c0f0811e-1829-40ca-a565-0ef2c686dc06.png)

and this one is my project but reply param is null
![image](https://user-images.githubusercontent.com/2093148/215333281-93f923bb-add4-4599-8b26-beb4f1f839ee.png)

same computer, same function, but...why..?

**Comment by darshankawar** [comment]
@TrustOne 
Can you provide `flutter doctor -v` and a complete minimal reproducible code sample that shows the reported behavior ?
