### ISSUE TITLE
TextField text style 'inherit' error ("'begin.inherit == end.inherit': is not true")

### ISSUE THREAD

**Issue by vuppalasivakumar** [flutter/flutter#11948]
hi guys,

for textbox if I use label text I am getting error like this in console and I am getting error in textbox text area for fraction of seconds.

and my code look like this 
```
child:new TextField(

  decoration: new InputDecoration(hintText: 'Enter your Name',hintStyle:  new TextStyle(fontSize: 18.0,color: Colors.grey[300]),labelText: 'Name'),
  style: new TextStyle(

    fontSize: 18.0,
    color: Colors.black,),


  textAlign: TextAlign.left,
),
```
error shows like this
```
Performing hot reload...
Reloaded 1 of 448 libraries in 660ms.
I/flutter (28650): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (28650): The following assertion was thrown building _AnimatedLabel(duration: 200ms, inherit: true, color:
I/flutter (28650): MaterialColor(primary value: Color(0xff9e9e9e)), size: 20.0, dirty, state:
I/flutter (28650): _AnimatedLabelState#d00b3(ticker active)):
I/flutter (28650): 'package:flutter/src/painting/text_style.dart': Failed assertion: line 329 pos 12: 'begin.inherit ==
I/flutter (28650): end.inherit': is not true.
I/flutter (28650): 
I/flutter (28650): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (28650): more information in this error message to help you determine and fix the underlying cause.
I/flutter (28650): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (28650):   https://github.com/flutter/flutter/issues/new
I/flutter (28650): 
I/flutter (28650): When the exception was thrown, this was the stack:
I/flutter (28650): #2      TextStyle.lerp (package:flutter/src/painting/text_style.dart:329:12)
I/flutter (28650): #3      TextStyleTween.lerp (package:flutter/src/widgets/implicit_animations.dart:150:41)
I/flutter (28650): #4      Tween.evaluate (package:flutter/src/animation/tween.dart:160:12)
I/flutter (28650): #5      _AnimatedLabelState.build (package:flutter/src/material/input_decorator.dart:634:30)
I/flutter (28650): #6      StatefulElement.build (package:flutter/src/widgets/framework.dart:3624:27)
I/flutter (28650): #7      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3534:15)
I/flutter (28650): #8      Element.rebuild (package:flutter/src/widgets/framework.dart:3435:5)
I/flutter (28650): #9      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2260:33)
I/flutter (28650): #10     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:503:20)
I/flutter (28650): #11     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:189:5)
I/flutter (28650): #12     BindingBase&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:695:15)
I/flutter (28650): #13     BindingBase&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:643:9)
I/flutter (28650): #14     _invoke (file:///b/build/slave/Linux_Engine/build/src/flutter/lib/ui/hooks.dart:86)
I/flutter (28650): #15     _drawFrame (file:///b/build/slave/Linux_Engine/build/src/flutter/lib/ui/hooks.dart:75)
I/flutter (28650): (elided 2 frames from class _AssertionError)
I/flutter (28650): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (28650): Another exception was thrown: 'package:flutter/src/painting/text_style.dart': Failed assertion: line 329 pos 12: 'begin.inherit == end.inherit': is not true.
I/flutter (28650): Another exception was thrown: 'package:flutter/src/painting/text_style.dart': Failed assertion: line 329 pos 12: 'begin.inherit == end.inherit': is not true.
I/flutter (28650): Another exception was thrown: 'package:flutter/src/painting/text_style.dart': Failed assertion: line 329 pos 12: 'begin.inherit == end.inherit': is not true.
I/flutter (28650): Another exception was thrown: 'package:flutter/src/painting/text_style.dart': Failed assertion: line 329 pos 12: 'begin.inherit == end.inherit': is not true.
I/flutter (28650): Another exception was thrown: 'package:flutter/src/painting/text_style.dart': Failed assertion: line 329 pos 12: 'begin.inherit == end.inherit': is not true.
I/flutter (28650): Another exception was thrown: 'package:flutter/src/painting/text_style.dart': Failed assertion: line 329 pos 12: 'begin.inherit == end.inherit': is not true.
I/flutter (28650): Another exception was thrown: 'package:flutter/src/painting/text_style.dart': Failed assertion: line 329 pos 12: 'begin.inherit == end.inherit': is not true.
I/flutter (28650): Another exception was thrown: 'package:flutter/src/painting/text_style.dart': Failed assertion: line 329 pos 12: 'begin.inherit == end.inherit': is not true.
I/flutter (28650): Another exception was thrown: 'package:flutter/src/painting/text_style.dart': Failed assertion: line 329 pos 12: 'begin.inherit == end.inherit': is not true.
I/flutter (28650): Another exception was thrown: 'package:flutter/src/painting/text_style.dart': Failed assertion: line 329 pos 12: 'begin.inherit == end.inherit': is not true.
I/flutter (28650): Another exception was thrown: 'package:flutter/src/painting/text_style.dart': Failed assertion: line 329 pos 12: 'begin.inherit == end.inherit': is not true.
I/flutter (28650): Another exception was thrown: 'package:flutter/src/painting/text_style.dart': Failed assertion: line 329 pos 12: 'begin.inherit == end.inherit': is not true.
I/flutter (28650): Another exception was thrown: 'package:flutter/src/painting/text_style.dart': Failed assertion: line 329 pos 12: 'begin.inherit == end.inherit': is not true.
I/flutter (28650): Another exception was thrown: 'package:flutter/src/painting/text_style.dart': Failed assertion: line 329 pos 12: 'begin.inherit == end.inherit': is not true.
I/flutter (28650): Another exception was thrown: 'package:flutter/src/painting/text_style.dart': Failed assertion: line 329 pos 12: 'begin.inherit == end.inherit': is not true.
I/flutter (28650): Another exception was thrown: 'package:flutter/src/painting/text_style.dart': Failed assertion: line 329 pos 12: 'begin.inherit == end.inherit': is not true.
I/flutter (28650): Another exception was thrown: 'package:flutter/src/painting/text_style.dart': Failed assertion: line 329 pos 12: 'begin.inherit == end.inherit': is not true.
I/flutter (28650): Another exception was thrown: 'package:flutter/src/painting/text_style.dart': Failed assertion: line 329 pos 12: 'begin.inherit == end.inherit': is not true.
I/flutter (28650): Another exception was thrown: 'package:flutter/src/painting/text_style.dart': Failed assertion: line 329 pos 12: 'begin.inherit == end.inherit': is not true.
I/flutter (28650): Another exception was thrown: 'package:flutter/src/painting/text_style.dart': Failed assertion: line 329 pos 12: 'begin.inherit == end.inherit': is not true.
I/flutter (28650): Another exception was thrown: 'package:flutter/src/painting/text_style.dart': Failed assertion: line 329 pos 12: 'begin.inherit == end.inherit': is not true.
I/flutter (28650): Another exception was thrown: 'package:flutter/src/painting/text_style.dart': Failed assertion: line 329 pos 12: 'begin.inherit == end.inherit': is not true.
I/flutter (28650): Another exception was thrown: 'package:flutter/src/painting/text_style.dart': Failed assertion: line 329 pos 12: 'begin.inherit == end.inherit': is not true.
```

**Comment by Hixie** [comment]
As a work-around, try replacing the two places where you say `new TextStyle(...)` with `DefaultTextStyle.of(context).style.merge(new TextStyle(...))`.

If that fixes it, then the bug is probably that we should detect that you've provided inherited styles and merge them in for you.

**Comment by vuppalasivakumar** [comment]
I had changed my code like this as u said 

 child:new TextField(

          decoration: new InputDecoration(hintText: 'please enter name',hintStyle:  DefaultTextStyle.of(context).style.merge(new TextStyle(fontSize: 18.0,color: Colors.grey[300])),labelText: 'Name',),
          style: DefaultTextStyle.of(context).style.merge(new TextStyle(

            fontSize: 18.0,
            color: Colors.black,
          )),
          keyboardType: TextInputType.number,

          textAlign: TextAlign.left,
        ),


still it showing error as

I/flutter ( 3696): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 3696): The following assertion was thrown building _AnimatedLabel(duration: 200ms, inherit: false, color:
I/flutter ( 3696): Color(0xff4caf50), family: Roboto, size: 12.0, weight: 400, baseline: alphabetic, dirty, state:
I/flutter ( 3696): _AnimatedLabelState#a84f6(ticker active)):
I/flutter ( 3696): 'package:flutter/src/painting/text_style.dart': Failed assertion: line 329: 'begin.inherit ==
I/flutter ( 3696): end.inherit': is not true.
I/flutter ( 3696): 
I/flutter ( 3696): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 3696): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 3696): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 3696):   https://github.com/flutter/flutter/issues/new
I/flutter ( 3696): 
I/flutter ( 3696): When the exception was thrown, this was the stack:
I/flutter ( 3696): #2      TextStyle.lerp (package:flutter/src/painting/text_style.dart:329)
I/flutter ( 3696): #3      TextStyleTween.lerp (package:flutter/src/widgets/implicit_animations.dart:150)
I/flutter ( 3696): #4      Tween.evaluate (package:flutter/src/animation/tween.dart:160)
I/flutter ( 3696): #5      _AnimatedLabelState.build (package:flutter/src/material/input_decorator.dart:634)
I/flutter ( 3696): #6      StatefulElement.build (package:flutter/src/widgets/framework.dart:3624)
I/flutter ( 3696): #7      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3534)
I/flutter ( 3696): #8      Element.rebuild (package:flutter/src/widgets/framework.dart:3435)
I/flutter ( 3696): #9      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2260)
I/flutter ( 3696): #10     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:503)
I/flutter ( 3696): #11     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:189)
I/flutter ( 3696): #12     BindingBase&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:695)
I/flutter ( 3696): #13     BindingBase&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:643)
I/flutter ( 3696): #14     _invoke (file:///b/build/slave/Linux_Engine/build/src/flutter/lib/ui/hooks.dart:86)
I/flutter ( 3696): #15     _drawFrame (file:///b/build/slave/Linux_Engine/build/src/flutter/lib/ui/hooks.dart:75)
I/flutter ( 3696): (elided 2 frames from class _AssertionError)
I/flutter ( 3696): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter ( 3696): Another exception was thrown: 'package:flutter/src/painting/text_style.dart': Failed assertion: line 329: 'begin.inherit == end.inherit': is not true.
I/flutter ( 3696): Another exception was thrown: 'package:flutter/src/painting/text_style.dart': Failed assertion: line 329: 'begin.inherit == end.inherit': is not true.
I/flutter ( 3696): Another exception was thrown: 'package:flutter/src/painting/text_style.dart': Failed assertion: line 329: 'begin.inherit == end.inherit': is not true.
I/flutter ( 3696): Another exception was thrown: 'package:flutter/src/painting/text_style.dart': Failed assertion: line 329: 'begin.inherit == end.inherit': is not true.
I/flutter ( 3696): Another exception was thrown: 'package:flutter/src/painting/text_style.dart': Failed assertion: line 329: 'begin.inherit == end.inherit': is not true.
I/flutter ( 3696): Another exception was thrown: 'package:flutter/src/painting/text_style.dart': Failed assertion: line 329: 'begin.inherit == end.inherit': is not true.
I/flutter ( 3696): Another exception was thrown: 'package:flutter/src/painting/text_style.dart': Failed assertion: line 329: 'begin.inherit == end.inherit': is not true.
I/flutter ( 3696): Another exception was thrown: 'package:flutter/src/painting/text_style.dart': Failed assertion: line 329: 'begin.inherit == end.inherit': is not true.
I/flutter ( 3696): Another exception was thrown: 'package:flutter/src/painting/text_style.dart': Failed assertion: line 329: 'begin.inherit == end.inherit': is not true.
I/flutter ( 3696): Another exception was thrown: 'package:flutter/src/painting/text_style.dart': Failed assertion: line 329: 'begin.inherit == end.inherit': is not true.
I/flutter ( 3696): Another exception was thrown: 'package:flutter/src/painting/text_style.dart': Failed assertion: line 329: 'begin.inherit == end.inherit': is not true.
I/flutter ( 3696): Another exception was thrown: 'package:flutter/src/painting/text_style.dart': Failed assertion: line 329: 'begin.inherit == end.inherit': is not true.
I/flutter ( 3696): Another exception was thrown: 'package:flutter/src/painting/text_style.dart': Failed assertion: line 329: 'begin.inherit == end.inherit': is not true.
I/flutter ( 3696): Another exception was thrown: 'package:flutter/src/painting/text_style.dart': Failed assertion: line 329: 'begin.inherit == end.inherit': is not true.
I/flutter ( 3696): Another exception was thrown: 'package:flutter/src/painting/text_style.dart': Failed assertion: line 329: 'begin.inherit == end.inherit': is not true.
I/flutter ( 3696): Another exception was thrown: 'package:flutter/src/painting/text_style.dart': Failed assertion: line 329: 'begin.inherit == end.inherit': is not true.
I/flutter ( 3696): Another exception was thrown: 'package:flutter/src/painting/text_style.dart': Failed assertion: line 329: 'begin.inherit == end.inherit': is not true.
I/flutter ( 3696): Another exception was thrown: 'package:flutter/src/painting/text_style.dart': Failed assertion: line 329: 'begin.inherit == end.inherit': is not true.
I/flutter ( 3696): Another exception was thrown: 'package:flutter/src/painting/text_style.dart': Failed assertion: line 329: 'begin.inherit == end.inherit': is not true.
I/flutter ( 3696): Another exception was thrown: 'package:flutter/src/painting/text_style.dart': Failed assertion: line 329: 'begin.inherit == end.inherit': is not true.
I/flutter ( 3696): Another exception was thrown: 'package:flutter/src/painting/text_style.dart': Failed assertion: line 329: 'begin.inherit == end.inherit': is not true.

**Comment by Hixie** [comment]
Pity. Ok. We'll have to track down why the text style is getting the wrong `inherit` value somewhere.

**Comment by zoechi** [comment]
No exception with 
```
[✓] Flutter (Channel dev, v1.1.7, on Mac OS X 10.14.1 18B75, locale en-AT)
```

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'foo text',
            ),
            TextField(
              decoration: new InputDecoration(
                  hintText: 'Enter your Name',
                  hintStyle:
                      new TextStyle(fontSize: 18.0, color: Colors.grey[300]),
                  labelText: 'Name'),
              style: new TextStyle(
                fontSize: 18.0,
                color: Colors.black,
              ),
              textAlign: TextAlign.left,
            ),
          ],
        ),
      ),
    );
  }
}
```
```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'foo text',
            ),
            TextField(
              decoration: new InputDecoration(
                hintText: 'please enter name',
                hintStyle: DefaultTextStyle.of(context).style.merge(
                    new TextStyle(fontSize: 18.0, color: Colors.grey[300])),
                labelText: 'Name',
              ),
              style: DefaultTextStyle.of(context).style.merge(new TextStyle(
                    fontSize: 18.0,
                    color: Colors.black,
                  )),
              keyboardType: TextInputType.number,
              textAlign: TextAlign.left,
            ),
          ],
        ),
      ),
    );
  }
}
```
I assume it's safe to close.
