### ISSUE TITLE
`flutter gen-i10n` throws `Found syntax errors.` after upgrading to 3.7.0 (mostly affecting china mirror)

### ISSUE THREAD

**Issue by bluealert455** [flutter/flutter#119435]
In flutter 3.3.10,everything is fine.
Since upgrading to 3.7.0,flutter gen-l10n throws "found syntax errors" exception.
app_en.arb:
{
    "helloWorld": "Hello World!",
    "@helloWorld": {
      "description": "The conventional newborn programmer greeting"
    }
}

app_es.arb:
{
    "helloWorld": "¡Hola Mundo!"
}

**Comment by Paguiar735** [comment]
Send us a link to the repository with a minimal working example, so we can reproduce the error ourselves.

**Comment by bluealert455** [comment]
https://github.com/bluealert455/l10n_test

**Comment by dbds** [comment]
I have the same problem ,after upgrading to 3.7.0, build fail because gen-l10n report error: found syntax errors.

**Comment by conghaonet** [comment]
I have the same problem.
`
[√] Flutter (Channel stable, 3.7.0, on Microsoft Windows [版本 10.0.19045.2486], locale zh-CN)
    • Flutter version 3.7.0 on channel stable at C:\myDev\flutter
    • Upstream repository https://github.com/flutter/flutter.git           
    • Framework revision b06b8b2710 (6 days ago), 2023-01-23 16:55:55 -0800
    • Engine revision b24591ed32                                           
    • Dart version 2.19.0                                                  
    • DevTools version 2.20.1                                              
    • Pub download mirror https://pub.flutter-io.cn                        
    • Flutter download mirror https://storage.flutter-io.cn                
                                                                           
[√] Windows Version (Installed version of Windows is version 10 or higher) 

[√] VS Code (version 1.73.0)
    • VS Code at C:\Users\haoco\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.52.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [版本 10.0.19045.2486]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 109.0.5414.120
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 109.0.1518.70

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

`

**Comment by darshankawar** [comment]
Thanks for the report. I am unable to replicate this error on latest stable or master version. I cloned the repo provided and then ran `flutter gen l10n` which didn't result in the said error.
I also have a demo app which has the setup as mentioned in [above](https://github.com/flutter/flutter/issues/119435#issuecomment-1408025548) comment using which too, I am unable to replicate the error.

There's an [issue](https://github.com/flutter/flutter/issues/119375) which throws the `Found syntax errors.` but only when we manually update one of the `.arb` files as mentioned in that issue and then trying to run the command `flutter gen l10n` throws the error which is similar to the one reported in this thread.

Please check if there's any syntax error in your `.arb` files and also check [this](https://docs.flutter.dev/development/accessibility-and-localization/internationalization#adding-your-own-localized-messages) documentation for proper config.

**Comment by fuhaixiao** [comment]
@darshankawar I have this problem too, it only happens on windows

**Comment by darshankawar** [comment]
Thanks for the details @motionz-von. Eveyone else facing this issue, can you please confirm if you see same log or you are using Flutter China mirror ?

**Comment by conghaonet** [comment]
@darshankawar 
I am using Flutter China mirror( https://storage.flutter-io.cn ).
running flutter gen-l10n -v, output:
```
[  +10 ms] executing: [C:\myDev\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +113 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] b06b8b2710955028a6b562f5aa6fe62941d6febf                                                   
[        ] executing: [C:\myDev\flutter/] git tag --points-at b06b8b2710955028a6b562f5aa6fe62941d6febf
[ +147 ms] Exit code 0 from: git tag --points-at b06b8b2710955028a6b562f5aa6fe62941d6febf
[        ] 3.7.0
[   +9 ms] executing: [C:\myDev\flutter/] git rev-parse --abbrev-ref --symbolic @{upstream}
[  +92 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{upstream}
[        ] origin/stable                                                
[        ] executing: [C:\myDev\flutter/] git ls-remote --get-url origin
[  +99 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +108 ms] executing: [C:\myDev\flutter/] git rev-parse --abbrev-ref HEAD
[ +106 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +54 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.           
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.                
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.       
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.         
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.         
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.     
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.     
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[   +2 ms] Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
[  +38 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[  +51 ms] Because l10n.yaml exists, the options defined there will be used instead.
           To use the command line arguments, delete the l10n.yaml file in the Flutter project.


[ +109 ms] "flutter gen-l10n" took 369ms.
[   +3 ms] Found syntax errors.
[        ] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      generateLocalizations (package:flutter_tools/src/localizations/gen_l10n.dart:75:5)
           #2      GenerateLocalizationsCommand.runCommand (package:flutter_tools/src/commands/generate_localizations.dart:241:24)
           #3      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1426:12)
           <asynchronous suspension>
           #4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1257:27)
           <asynchronous suspension>
           #5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #6      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:283:9)
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #9      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #10     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
           <asynchronous suspension>
           #11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #12     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>


[ +264 ms] ensureAnalyticsSent: 261ms
[        ] Running 0 shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1
```

**Comment by AndreBlumenthal** [comment]
So in my case I have syntax error because i use `{PLACEHOLDER_NAMES}` with underscores. I think the purpose of this is to have a unified approach of naming. But why are keys with underscores allowed then?
Secondly I have some placeholders in the format of `{{.Name}}`. This is, because our Go backend uses the same translations and expects this behaviour. It is debatable if this is a good approach of having shared translations.
Third, I have a translation string that shows all allowed characters for a password. So it looks like this `...(){}[]...` but this fails, because of the `{}`. But there is no way for me to escape these characters

**Comment by deczaloth** [comment]
> So in my case I have syntax error because i use `{PLACEHOLDER_NAMES}` with underscores. I think the purpose of this is to have a unified approach of naming. But why are keys with underscores allowed then? Secondly I have some placeholders in the format of `{{.Name}}`. This is, because our Go backend uses the same translations and expects this behaviour. It is debatable if this is a good approach of having shared translations. Third, I have a translation string that shows all allowed characters for a password. So it looks like this `...(){}[]...` but this fails, because of the `{}`. But there is no way for me to escape these characters

I think your issue would be more related to the issue described here:
https://github.com/flutter/flutter/issues/119375

**Comment by zakblacki** [comment]
I can confirm it's the same problem after upgrading !

**Comment by darshankawar** [comment]
Thanks for all the updates. Based on the reports, it seems to be related to mirror https://docs.flutter.dev/community/china, so labeling this issue based on it and also adding `regression` since the issue started happening after upgrading to 3.7.0.

**Comment by darshankawar** [comment]
Please see https://github.com/flutter/flutter/issues/119593 which has a potential fix.

**Comment by AlexV525** [comment]
The problem is related to any mirrors rather than China-specific, please see https://github.com/flutter/flutter/issues/119593#issuecomment-1409708288 for the temporary workaround until the PR fixes this.

**Comment by bluealert455** [comment]
Thx!
Problem solved!
Workaround from @AlexV525 in #119593
https://github.com/flutter/flutter/issues/119593#issuecomment-1409708288

PS:The message "Flutter assets will be downloaded from $overrideUrl. Make sure you trust this source!" should be a warning rather a error.

**Comment by bluealert455** [comment]
Thx!
Problem solved!
Workaround from @AlexV525 in https://github.com/flutter/flutter/issues/119593
https://github.com/flutter/flutter/issues/119593#issuecomment-1409708288

PS:The message "Flutter assets will be downloaded from $overrideUrl. Make sure you trust this source!" should be a warning rather than a error.

**Comment by remi-martin** [comment]
Same issue, [workaround](https://github.com/flutter/flutter/issues/119593#issuecomment-1409708288) not working.
```
--no-color pub get
[app_de.arb:deleteCategory_message] ICU Syntax Error: Expected "}" but found no tokens.
    {count, plural, =0{SOLL DAS ALBUM {album} WIRKLICH GELÖSCHT WERDEN} =1{SOLL DAS ALBUM {album} UND DAS ENTHALTENE FOTO WIRKLICH GELÖSCHT WERDEN} other{SOLL DAS ALBUM {album} UND SÄMTLICHE {count} FOTOS GELÖSCHT WERDEN ?}
                                                                                          ^
[app_en.arb:deleteCategory_message] ICU Syntax Error: Expected "}" but found no tokens.
    {count, plural, =0{ARE YOU SURE YOU WANT TO DELETE THE ALBUM {album} ?} =1{ARE YOU SURE YOU WANT TO DELETE THE ALBUM {album} AND ITS PHOTO ?} other{ARE YOU SURE YOU WANT TO DELETE THE ALBUM {album} AND ALL {count} PHOTOS ?}
                                                                                          ^
[app_fr.arb:deleteCategory_message] ICU Syntax Error: Expected "}" but found no tokens.
    {count, plural, =0{ÊTES VOUS SÛR DE VOULOIR SUPPRIMER L'ALBUM {album}} =1{ÊTES VOUS SÛR DE VOULOIR SUPPRIMER L'ALBUM {album} ET SA PHOTO} other{ÊTES VOUS SÛR DE VOULOIR SUPPRIMER L'ALBUM {album} ET SES {count} PHOTOS ?}
                                                                                          ^
[app_zh.arb:deleteCategory_message] ICU Syntax Error: Expected "}" but found no tokens.
    {count, plural, =0{是否确定删除相册 {album}} =1{是否确定删除相册 {album} AND ITS PHOTO} other{是否确定删除相册 {album} 和共计 {count} 张照片 ?}
                                                                                          ^
Generating synthetic localizations package failed with 1 error:

Exception: Found syntax errors.
Process finished with exit code 1
```

**Comment by AlexV525** [comment]
> It seems to be more related to plural and variables with l10n.

Your issue is not related to this one, it's the new syntax that breaks previous arb files.

**Comment by remi-martin** [comment]
> Your issue is not related to this one, it's the new syntax that breaks previous arb files.

Thanks, I deleted my message because it was just a missing "}" at the end of the String.
However I don't understand why I never had an issue with this String before as the app was built successfully several times with it and no error was thrown.

**Comment by thkim1011** [comment]
@remi-martin Previously, the `gen-l10n` tool used RegEx matching to see if a message has a plural or select, and did some replacements. If it didn't match it would silently do nothing to the string.
