### ISSUE TITLE
A way to apply a splash effect to all widgets at once in Material 2

### ISSUE THREAD

**Issue by kaboc** [flutter/flutter#119449]
## Use case

It is very common that we want all clickable widgets to have the same splash effect. Otherwise, the app looks inconsistent.

It appears that the effect type can be configured by just using `splashFactory` in ThemeData in Material 3. However, if we want to change it in Material 2, we have to specify splashFactory in each Theme setting, like `ThemeData`, `ElevatedButtonThemeData.style`, etc.

Material 2:

https://github.com/flutter/flutter/blob/e8c0e467d645c3867ef66d20d1b0f07c4ccfacdf/packages/flutter/lib/src/material/elevated_button.dart#L298

Material 3:

https://github.com/flutter/flutter/blob/e8c0e467d645c3867ef66d20d1b0f07c4ccfacdf/packages/flutter/lib/src/material/elevated_button.dart#L353

## Proposal

I understand `InkRipple` is used by default in Material 2. I don't think it means Material 2 is forcing us to always use `InkRipple`. It is actually possible to change it one by one, but why is there no way to apply it to all? It would be great if `splashFactory` specified in `ThemeData` is universally applied to all widgets.

**Comment by darshankawar** [comment]
@kaboc 
There's a similar open issue describing your case https://github.com/flutter/flutter/issues/94336, so please follow-up in it for further updates. Closing this as a duplicate.
