### ISSUE TITLE
[iOS] The app goes into crash loop after terminating it with no logs

### ISSUE THREAD

**Issue by oguzyildiz1991** [flutter/flutter#119466]
Hi, I'm working on an app with Flutter, it works fine on Android, but in iOS I'm having trouble with a crash that has no details. I'm looking for a way to see an error message so that I can investigate

## Steps to Reproduce

1. Execute `flutter run` and run the app in a real iPhone
2. The app works fine. I can background it and then come back to it, still works fine.
3. I terminate the app (swipe up the app on the "recent apps" view), the `flutter run` command terminates saying "lost connection to the device".
4. After that, the app crashes right away after starting (I see a glimpse of splash screen and that's it). I can't see any logs since `flutter run` terminated at step 3. `flutter logs` doesn't show anything either. I tried Sentry, Firebase Crashlytics, nothing is receiving any crash reports.

**Expected results:** 
See the crash logs in the terminal or get a report

**Actual results:** 
No crash logs nor reports

Any recommendations on how I can get the error details? Thank you in advance! 

Some clues:
- It does not reproduce in the simulator, only in the real device
- I added a 5s sleep at the beginning of the app (first line of `main`) and it's not waiting before it crashes, so I imagine something happens before it can even start running the flutter main
- The app is trying to do some background work, it does that fine if the app is backgrounded, but it stops if it's terminated (it's not supposed to, according to other people that use the [plugin](https://github.com/Yukams/background_locator_fixed/issues/16) I'm using)

AppDelegate.swift:
```swift
import UIKit
import Flutter
import GoogleMaps
import background_locator_2
import Firebase
import FirebaseAuth

func registerPlugins(registry: FlutterPluginRegistry) -> () {
    if (!registry.hasPlugin("BackgroundLocatorPlugin")) {
        GeneratedPluginRegistrant.register(with: registry)
    }
}

@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {
    FirebaseApp.configure()
    GMSServices.setMetalRendererEnabled(true)
    GMSServices.provideAPIKey("...")
    GeneratedPluginRegistrant.register(with: self)
    BackgroundLocatorPlugin.setPluginRegistrantCallback(registerPlugins)
    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }
}

```

**Comment by jayjah** [comment]
@oguzyildiz1991 Did you tried to run your app with Xcode? Maybe it's possible to observe any logs from Xcode. I want to mention that you can see logs from any iOS device (real device or simulator) with the `Console.app` application, which should be installed on your Mac. It's similar to `logcat` for android.

**Comment by oguzyildiz1991** [comment]
@jayjah thank you for your response. I should have mentioned, I tried running it with xcode as well, I see the same thing as `flutter run` output. But Console.app is showing some errors, thanks! I'll resolve this ticket since this was just about finding the logs
