### ISSUE TITLE
Engine builds failing on failure to find python

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#119519]
The failure is flaky. It looks like some machines have `python` and some don't.

Here's an example https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20Production%20Engine%20Drone/42854/overview

Marking P0 because the engine tree is closed, and rolls are blocked by failing presubmits.

**Comment by alexmarkov** [comment]
Dart SDK -> Flutter engine auto-roller also failed because of this issue: https://github.com/flutter/engine/runs/10976153663. Linux, Mac and Windows bots are affected.

**Comment by ricardoamador** [comment]
https://flutter-review.git.corp.google.com/c/recipes/+/38282
