### ISSUE TITLE
[CP] NavigationDrawer scrolling and safe area support

### ISSUE THREAD

**Issue by Piinks** [flutter/flutter#119556]
### issue_link

https://github.com/flutter/flutter/issues/116782

### Commit Hash

9a347fb06366632d236459a0ea972ffda36e2acc

### Target

stable

### pr_link

https://github.com/flutter/flutter/pull/119555

### Impacted Users

Any users of the material NavigationDrawer

### Impact Description

This new widget did not account for safe area or overflow. The associated change added support for both so the contents of the drawer will not overflow or be obscured by screen notches and the like.

### Workaround

Kind of, but not completely. Users that may engage their own workarounds could find themselves broken by the true fix later on if it is delayed.

### Risk

low

### Test Coverage

yes

### Validation Steps

The code sample from https://github.com/flutter/flutter/issues/116782 shows overflowing items in the drawer, running the sample with this change allows for them to scroll into view.

**Comment by CaseyHillers** [comment]
@HansMuller can you review this CP request?

**Comment by HansMuller** [comment]
LGTM
