### ISSUE TITLE
Flutter 3.7 version, ipad device, any page can be triggered, apple pencil's handwriting function

### ISSUE THREAD

**Issue by zhoushuangjian001** [flutter/flutter#119591]
Flutter 3.7 version, ipad device, any page can be triggered, apple pencil's handwriting function

**Comment by zhoushuangjian001** [comment]
Flutter version 3.7, ipad device, apple pencil's handwriting function causes the drawing to not respond in time

**Comment by danagbemava-nc** [comment]
Please do not file multiple issues for the same bug report. 

Closing this in favor of https://github.com/flutter/flutter/issues/119590
