### ISSUE TITLE
[gen-l10n] Failed to complete the generation when `FLUTTER_STORAGE_BASE_URL` is overridden

### ISSUE THREAD

**Issue by AlexV525** [flutter/flutter#119593]
### The issue is breaking every user that is using localizations and a custom `FLUTTER_STORAGE_BASE_URL`.

This also happens with `flutter pub get` if the l10n generation is synthetic.

![C 2GWA62)A7VKK 59JJ3%31](https://user-images.githubusercontent.com/15884415/215650416-3a62a1f1-2a9e-4272-aad7-49805346bc1d.png)

The tool will report `Found syntax errors` but not any actual syntax errors.

Related issues:
- #117610
- #119435
- #119585

## Root cause

When `FLUTTER_STORAGE_BASE_URL` is being overridden, the cache getter will try to raise an error to STDERR that the user is using a custom storage base.

https://github.com/flutter/flutter/blob/5b6572f96dd28dfbde8d9a7c3f73a32a45574408/packages/flutter_tools/lib/src/cache.dart#L523-L526

But using an error print will cause the generate tool recognized as an exception.

https://github.com/flutter/flutter/blob/5b6572f96dd28dfbde8d9a7c3f73a32a45574408/packages/flutter_tools/lib/src/localizations/gen_l10n.dart#L1249-L1252

And when it's using synthetic package, `flutter pub get` will also raise exceptions.

https://github.com/flutter/flutter/blob/5b6572f96dd28dfbde8d9a7c3f73a32a45574408/packages/flutter_tools/lib/src/dart/generate_synthetic_packages.dart#L61-L67

## Steps to Reproduce

1. Run `export FLUTTER_STORAGE_BASE_URL=https://storage.flutter-io.cn` in the terminal.
2. `flutter create test_l10n`
3. Setup internationalization for the project according to the [doc](https://docs.flutter.dev/development/accessibility-and-localization/internationalization).
4. `flutter pub get` or `flutter gen-l10n`

flutter doctor -v
```
Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!

[!] Flutter (Channel stable, 3.7.0, on Microsoft Windows [版本 10.0.22000.1455], locale zh-CN)
    • Flutter version 3.7.0 on channel stable at X:\SDK\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b06b8b2710 (7 days ago), 2023-01-23 16:55:55 -0800
    • Engine revision b24591ed32
    • Dart version 2.19.0
    • DevTools version 2.20.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn
```

**Comment by AlexV525** [comment]
cc @thkim1011 I'm going to submit a quick fix to use a warning instead of an error for the storage override.

**Comment by AlexV525** [comment]
Workaround steps:
1. Change the below line to `printWarning`.
https://github.com/flutter/flutter/blob/5b6572f96dd28dfbde8d9a7c3f73a32a45574408/packages/flutter_tools/lib/src/cache.dart#L523
2. Delete `flutter_tools.snapshot` and `flutter_tools.stamp` under the SDK's path and `bin/cache`.
3. Rerun any Flutter commands.

**Comment by darshankawar** [comment]
Similar issue: https://github.com/flutter/flutter/issues/119435

**Comment by conghaonet** [comment]
> Workaround steps:
> 
> 1. Change the below line to `printWarning`.
>    https://github.com/flutter/flutter/blob/5b6572f96dd28dfbde8d9a7c3f73a32a45574408/packages/flutter_tools/lib/src/cache.dart#L523
> 2. Delete `flutter_tools.snapshot` and `flutter_tools.stamp` under the `${path_to_flutter_sdk}/bin/cache`.
> 3. Rerun any Flutter commands.

It is worked!

**Comment by thkim1011** [comment]
Working on a fix right now.

**Comment by christopherfujino** [comment]
@thkim1011 thanks so much for the quick fix! Could you also request a cherrypick to the stable channel via the [issue template](https://github.com/flutter/flutter/issues/new?assignees=&labels=cp%3A+review&template=7_cherry_pick.yml&title=%5BCP%5D+%3Ctitle%3E)?

**Comment by AlexV525** [comment]
> @thkim1011 thanks so much for the quick fix! Could you also request a cherrypick to the stable channel via the [issue template](https://github.com/flutter/flutter/issues/new?assignees=&labels=cp%3A+review&template=7_cherry_pick.yml&title=%5BCP%5D+%3Ctitle%3E)?

https://github.com/flutter/flutter/issues/119678

**Comment by christopherfujino** [comment]
> > @thkim1011 thanks so much for the quick fix! Could you also request a cherrypick to the stable channel via the [issue template](https://github.com/flutter/flutter/issues/new?assignees=&labels=cp%3A+review&template=7_cherry_pick.yml&title=%5BCP%5D+%3Ctitle%3E)?
> 
> #119678

Thanks!
