### ISSUE TITLE
transitive font dependencies

### ISSUE THREAD

**Issue by subzero911** [flutter/flutter#119562]
I create a design kit package with preset fonts. I follow this instruction: https://docs.flutter.dev/cookbook/design/package-fonts

I wrote down all my fonts in package's pubspec:
<img width="629" alt="image" src="https://user-images.githubusercontent.com/12999702/215595813-5362b11f-37ee-4eee-8da3-613eaffdbbcd.png">

I also generated text constants with `fluttergen`:
<img width="628" alt="image" src="https://user-images.githubusercontent.com/12999702/215595973-f770fc20-1738-4ed4-a9b4-5e5cc7f9be17.png">

Then I use it in flutter. But in app I see default 'Roboto' fonts everywhere.
It's stated in the cookbook: https://docs.flutter.dev/cookbook/design/package-fonts#declare-the-font-assets - "please declare all the package fonts".
Indeed, if I declare all the package fonts in the head app project, it finds it:
<img width="720" alt="image" src="https://user-images.githubusercontent.com/12999702/215597286-b2208090-9276-46f0-a3f9-d8dbce8a5e42.png">
But that's not what I want! I don't want to force user to duplicate all the fonts in his pubspec. I already declared fonts in my package.
I want him to just download the package and use fonts (using generated font constants).

I believe it's an omitment of Dart: it can't transitively see fonts declared in the inner package until I explicitly add them in the pubspec.

If it's impossible, I suggest using some shorthand syntax like 
```yaml
fonts:
  import packages/mts_granat # imports all fonts from its pubspec
```

**Comment by huycozy** [comment]
>I don't want to force user to duplicate all the fonts in his pubspec. I already declared fonts in my package.

@subzero911 As my understanding, the guideline from the docs doesn't work for you and you are declaring fonts twice (in package and project `pubspec.yaml` files), right? 

Can you provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this? Also, please provide the output of `flutter doctor -v` as well.

Thank you!

**Comment by subzero911** [comment]
> As my understanding, the guideline from the docs doesn't work for you and you are declaring fonts twice (in package and project pubspec.yaml files), right?

Not exactly. The guideline describes the situation when I just added fonts into the package. And it offers to reference them in a project's pubspec with `packages/awesome_pkg/...` prefix.
In my case, I declare fonts in a package pubspec. 
Expected behaviour: project can use these fonts if I included a package, because fonts are already declared in it.
Actual behaviour: project "can't see" these fonts until I declare these fonts in a project's pubspec too.

Proposal: add a simple way to declare fonts in a project with 1 line of code:
```yaml
fonts:
  import packages/mts_granat
``` 

I'm not quite sure how to provide a code sample, as this problem related to packages and pubspecs, not to code.

**Comment by huycozy** [comment]
@subzero911 
What I mean is similar to what you are describing (you are having to declare fonts twice on both package and project to be able to use fonts)

However, it works as expected when adding `package` attribute to `TextStyle`, like this:

```
Text(
            'Font example',
            style: TextStyle(
              // font from the package
              fontFamily: 'Ginger',
              fontSize: 44,
              package: 'awesome_fonts_collection'
            ),
          )
```

Also, you don't need to declare font in project's pubspec.yaml anymore. Just try this and see the result.

**Comment by huycozy** [comment]
Glad it works for you. You may want to check the [TextStyle document](https://api.flutter.dev/flutter/painting/TextStyle-class.html) and scroll to `Custom Fonts` section. 

Closing the issue as solved.

**Comment by subzero911** [comment]
It exists in a "Custom Fonts" section but does not exists in a Class properties list.

Okay, I also see that `package` parameter exists in a ThemeData and TextTheme too.
And it applies the custom fonts to all the children TextStyles. That should be enough for app styling.
And it's not documented as well for some reason.

@huycozy I recommend to reopen an issue with a `need_documentation` label.

**Comment by subzero911** [comment]
And I also found, that copyWith/apply do not contain the `package` parameter.
So if I declared themes in a separate package, I cannot add a fonts package link to it in my app.

**Comment by huycozy** [comment]
@subzero911 I see, there is no `package` parameter in Class properties from the document. To help the issue can be transparent and clear, would you mind filing another issue for this?
