### ISSUE TITLE
What is the app.apk which results from  flutter build apk --split-per-abi?

### ISSUE THREAD

**Issue by raLaaaa** [flutter/flutter#119559]
Hey,

documentation suggests the following:

![image](https://user-images.githubusercontent.com/12799722/215590872-3d586b7b-fa04-4739-9689-9d80d65d5ca2.png)
(https://docs.flutter.dev/deployment/android)

If I run ` flutter build apk --split-per-abi` I always retrieve a `app-debug.apk` and a `app.apk` - what is the purpose of the `app.apk`? Furthermore what is the difference to the `app-debug.apk`? 

I could not find anything on the web for it. Is it correct that this file is created?

## Steps to Reproduce

Just run `flutter build apk --split-per-abi` in any project.

## Flutter Doctor

![image](https://user-images.githubusercontent.com/12799722/215591563-667779b0-d6df-4257-9f06-dedaa5abc83e.png)

**Comment by stevenosse** [comment]
Hello

Here's an answer to your questions :

When running a flutter app in debug mode, the dart code is compiled just of time (JIT), making it possible to use features like hot reload/restart. In release mode, the code is compiled ahead of time (AOT) to native code. This mode is better for performances and results into a smaller app; it also removes stuffs that are only using in development mode. 
The `app-debug.apk` file is just the build you get when running/compiling your app in debug mode.

`app.apk` -> AOT
`app-debug.apk` -> JIT

When you build your app using `--split-per-abi` param, it results into 3 separated files as mentionned in the docs, located it `PROJECT_SRC/build/app/outputs/apk/prod/release/`. These files are the optimized build for each android architecture
