### ISSUE TITLE
TextFormField: tapping on character count focuses the input field

### ISSUE THREAD

**Issue by wal33d006** [flutter/flutter#119517]
## Steps to Reproduce

1. Create a sample screen with a `TextFormField`
2. Add a value to `maxLength` parameter let's say 100, you will now see the character length text as 0/100.
3. When you tap on this counter text, the text field focuses, which is weird.

**Expected results:** 
The text field should only focus when you tap inside the text field

**Actual results:** 
Text field focuses itself on tapping the `maxLength` text

The whole green area shown in the screenshot focuses the text field on tapping.
![Screenshot 2023-01-30 at 8 41 40 PM](https://user-images.githubusercontent.com/25613623/215523477-f9f6af27-35da-4b1f-801f-d1be4c077dd6.png)

I tried creating my own `counterBuilder` and adding an empty tap to it as a workaround, it worked but only for the that widget area I created. The space on the right hand side of that text, just below the text field still focuses the field on tapping.

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by darshankawar** [comment]
Thanks for the report @wal33d006 
I think it is WAI.  Using below code sample:

```
body: Center(
        child: TextField(
          maxLength: 100,
          decoration: InputDecoration(
            border: OutlineInputBorder(),
          ),

        )
      ),
```
Since `maxLength` is part of the `TextField` and `TextFormField` widgets, any interaction with any of the properties of these 2 fields makes an impact to the input. For example, when the textfield is focussed and we start inputing, the `maxLength` value changes, so the other way round is true too.

You may check with any native app and see if the behavior is same or not.

**Comment by wal33d006** [comment]
> Thanks for the report @wal33d006 I think it is WAI. Using below code sample:
> 
> ```
> body: Center(
>         child: TextField(
>           maxLength: 100,
>           decoration: InputDecoration(
>             border: OutlineInputBorder(),
>           ),
> 
>         )
>       ),
> ```
> 
> Since `maxLength` is part of the `TextField` and `TextFormField` widgets, any interaction with any of the properties of these 2 fields makes an impact to the input. For example, when the textfield is focussed and we start inputing, the `maxLength` value changes, so the other way round is true too.
> 
> You may check with any native app and see if the behavior is same or not.

That's correct. But by design and UX, it shouldn't be like that. As a user, they would not expect to tap somewhere out of the text field and get a keyboard popping up. The focusing should strictly remain restricted to the actual visible part of the insides of the text field (which I think should not be a problem to fix).

**Comment by darshankawar** [comment]
> they would not expect to tap somewhere out of the text field and get a keyboard popping up

Ideally, a user if they see a textfield, would most probably tap inside it to make it active and the chances of them tapping on something like `maxLength` section are far less, that's my personal opinion.



> You may check with any native app and see if the behavior is same or not.

Did you get a chance to look at it ? If native behaves same way, then it makes more sense that Flutter also matches native, but if the behavior is different (ie, on native this doesn't occur, but in Flutter does), then it would probably makes sense to match it with native.

**Comment by wal33d006** [comment]
I figured out a hacky way of doing it by wrapping the `counterBuilder` widget in a `Row`, and wrapping the child in an `Expanded`, and then wrapping the whole `Row` in a `GestureDetector` and applying `behavior: HitTestBehavior.opaque`

Thanks for the responses @darshankawar
