### ISSUE TITLE
[Android][iOS] Ensure misspelled text is only highlighted once the word is not being composed

### ISSUE THREAD

**Issue by camsim99** [flutter/flutter#119534]
Currently, spell check logic [uses the composing region](https://github.com/flutter/flutter/blob/df8ad3d2cb25e658c3600ae6fa0931404c1a8ed1/packages/flutter/lib/src/widgets/spell_check.dart#L249) to determine whether a misspelled word is being composed and thus, whether or not it should be highlighted as misspelled. This approach is flawed because iOS and Android devices not using Gboard may not have a valid composing region to rely on. Therefore, this logic must be refactored as to not be reliant on the composing region.

**Comment by justinmc** [comment]
Summarizing from talking about this offline:

We thought this could be achieved by not showing the red underline for the word that the cursor is in or adjacent to.  If you're currently typing a word, we don't want to underline it.  If we're currently showing the spell check suggestions toolbar, we also don't want the red underline (right?).

Also, this approach shouldn't affect composing keyboards like Chinese Pinyin, which do not spell check the composing text.
