### ISSUE TITLE
Many LUCI tests failing `read yaml` step with `cmd0 'vpython' not found`

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#119512]
See https://github.com/flutter/plugins/pull/6984 and https://github.com/flutter/packages/pull/3112 for example, where multiple (but not all, so it seems like it's maybe only affecting some bots?) are failing. Example failure: https://ci.chromium.org/ui/p/flutter/builders/try/Mac_x64%20build_all_plugins%20master/970/overview

**Comment by ricardoamador** [comment]
https://flutter-review.git.corp.google.com/c/recipes/+/38282
