### ISSUE TITLE
wasm_release builds do not work with --no-prebuilt-dart-sdk

### ISSUE THREAD

**Issue by whesse** [flutter/flutter#119513]
The PR https://github.com/flutter/engine/pull/38448 , [web] Build multiple CanvasKit variants (using toolchain_args), has broken building without a prebuilt Dart SDK.

The gn command 

    python3 flutter/tools/gn --runtime-mode release --no-prebuilt-dart-sdk --web

now gives an error because it tries to copy from the prebuilt Dart SDK location.  This is in the target

    See //flutter/build/dart/BUILD.gn:21:3: whence it was called.
    copy_trees("_copy_trees") {

Probably because of the change to run the CanvasKit build using a separate toolchain, and not using the args passed to gn,
the flutter_prebuilt_dart_sdk flag seems to be true when this target is hit from the CanvasKit build.

To reproduce the error, you need to delete the downloaded prebuilts from src/flutter/prebuilts.

This breaks all flutter tools on builds created from a tip-of-tree Dart or a tryjob with a patched Dart, such as the monorepo builds running on the Dart CI, now that the flutter tools download the platform-independent canvaskit.  We cannot build and upload this canvaskit because the host-wasm build cannot run without a prebuilt Dart SDK.

@mdebbar @zanderso @hterkelsen @jason-simmons @godofredoc

**Comment by mdebbar** [comment]
FWIW, I tried reverting https://github.com/flutter/engine/pull/38448 locally and running `tools/gn ... --no-prebuilt-dart-sdk` and I'm still getting the error.

**Comment by mdebbar** [comment]
I'll do a git bisect to find out which commit started the problem. I'm trying to find an old commit that's "good". I went as far back as November, and I'm still getting the error. So this seems to be an old issue.

@whesse any idea when this issue started happening? I'll keep going back in history until I find a commit that's good.

**Comment by whesse** [comment]
I was misled by the fact that any gclient sync command restores the prebuilts, so I was getting successes when trying earlier builds, due to the fact that they had been restored.  So I don't know. 

I just checked, and the commit that claims to restore support for no-prebuilt-dart-sdk has the failure, and the earlier revert of the web target cannot reproduce the problem, since the --web flag isn't supported on gn.

So it looks like the failure has always been there on the new wasm target, and the commit that tried to fix it did not actually fix it.

**Comment by whesse** [comment]
There is an existing issue about this problem, that was closed when it seemed to be fixed.  But the problem now shows up again, perhaps because the fix did not make the actual --web target work with no prebuilts.

Existing issue: https://github.com/flutter/flutter/issues/113772

I think it may be better to mark this issue as a duplicate of the existing issue.

Specifically, the PR that tried to fix building the web target with the --no-prebuilt-dart-sdk flag is

https://github.com/flutter/engine/commit/224a3def01a4dc0d7efed9cad85626620f5df7b6

and the PR that introduced the web target and the new build of canvaskit with different args than the args to the GN command is
https://github.com/flutter/engine/pull/36851
which is a reland of 
https://github.com/flutter/engine/pull/36520

@eyebrowsoffire

**Comment by mdebbar** [comment]
@whesse I suggest we keep this issue since it has more details. The other issue contains some outdated information, and the PR https://github.com/flutter/engine/pull/36926 did fix part of the issue, but not all.

I just tried to set `flutter_prebuilt_dart_sdk` to the correct value, but I hit this assertion: https://dart.googlesource.com/sdk/+/refs/heads/main/runtime/BUILD.gn#116. It doesn't support the wasm `target_os` apparently.

**Comment by whesse** [comment]
Changing the line 

      gn_args['flutter_prebuilt_dart_sdk'] = True
to
      gn_args['flutter_prebuilt_dart_sdk'] = args.prebuilt_dart_sdk

and changing two lines in [dart sdk]/runtime/bin/BUILD.gn to treat the dart_target_arch "wasm" as "x64" and the dart_target_os "wasm" as "linux" causes the gn command to run without a failure.

Of course, we cannot hardcode that target "wasm" is built only on x64 linux, so some other fixes will be needed.

But then, when the wasm_release build tries to build the Dart SDK, in order to use it for some of its targets, I guess, the toolchain is not set up to build Dart, and the host and architecture detection in the Dart build process fails, in [dart sdk]/runtime/platform/globals.h.

So the entire idea behind building the wasm build and depending on a Dart SDK in building wasm and canvaskit means that we can't really build it as a separate gn build from the engine builds, with a different toolchain.

The build/archive/test separation that infra is working on depends on being able to build different targets on different machines, so it doesn't seem likely that building host_release and wasm_release on the same builder, and referring to the host_release SDK as a local-engine will work.

Unless wasm_release really does not depend on Dart, or if it could be allowed to use a checked-in Dart that is not the Dart being built, there seem to be some real architectural problems here.

**Comment by eyebrowsoffire** [comment]
The goal is to move away from host builds for the web sdk in general. Since wasm_release is not a host build, it can't build host targets, including the Dart SDK, which is why it only works with the prebuilt dart sdk.

I think maybe the more permanent solution here is to tweak our gn rules to allow the prebuilt dart sdk to come from an arbitrary location specified with a gn arg. That way, for cases like these, the dart sdk can be built in a completely separate build step, and then we can point to that built version of the dart sdk.

From the dart team's point of view, would that be a sufficient solution for the HHH bots and monorepo?

**Comment by whesse** [comment]
Would this be coming in from a cipd package or cloud storage, or does it need to be built in a directory on that builder?  Does the prebuilt Dart SDK need to be exactly the same version as the Dart in the flutter engine? Because we could download a pinned stable SDK, if it doesn't need to be the version we are building in the engine.

The problem is that we want to make a single build on each builder, and upload its artifacts to cloud storage. So doing both a host_release and wasm_release build on the same builder would be a change to the engine_v2 architecture.

**Comment by mdebbar** [comment]
I'm clearly not the owner here anymore. Whoever is working on the next step, please feel free to assign to yourself.

**Comment by eyebrowsoffire** [comment]
I'm looking into a stopgap to solve this issue.

**Comment by whesse** [comment]
I have a very simple workaround for our use case, that renames the web sdk zip file produced by host_debug to flutter-web-sdk.zip before uploading it.  The engine_v2 builder configuration allows "generator" steps run after the build but before uploading artifacts.  CLs:

https://dart-review.googlesource.com/c/monorepo/+/279689

https://github.com/flutter/buildroot/pull/678

So I think we can work on creating the best long-term solution for building the web sdk artifact on all builders.

The only real blocking case for the current implementation path is the difficulty of building it for Dart tryjobs and Dart tip-of-tree builds.  Building it on the wasm-release builder, without a prebuilt SDK, needs to get a Dart SDK from somewhere.  Keeping the web sdk build on host_debug working until a good wasm-release path is ready will work for us.

**Comment by whesse** [comment]
The new wasm_release builds have landed, including the squasm Skia wasm library.

We are working on making a build of the flutter_web engine work on monorepo, with no prebuilt dart sdk, by building the Dart-dependent parts of the engine on the host_debug builder and the wasm parts of the engine on the flutter_web_release builder, with no dependence on a Dart SDK.

The artifacts are then combined by a global generator and archive step.  This is not needed on Flutter CI and release, where the entire flutter_web engine is built on the wasm_release builder.

Because of this, the test builders triggered by an engine_v2 config need to run after the global generators and archivers, so the web test builders can use the web engine artifact.

**Comment by whesse** [comment]
Global generators on the engine_v2 system do not currently work with monorepo, because they unconditionally check out the engine source tree.

https://flutter.googlesource.com/recipes/+/refs/heads/main/recipes/engine_v2/engine_v2.py#118

They need to conditionally check out either the engine source tree or the monorepo source tree, as in the builders:

https://flutter.googlesource.com/recipes/+/refs/heads/main/recipes/engine_v2/builder.py#204

All paths in the generators and archive should be relative to the engine checkout, not to cache/builder.

**Comment by whesse** [comment]
All the issues with building the web engine for monorepo, using a separate global generator, have been resolved, and it is working.
