### ISSUE TITLE
flutter-win-5 bot has died and is not reachable via ssh

### ISSUE THREAD

**Issue by ricardoamador** [flutter/flutter#119528]
```
ricardoamador@ricardoamador-macbookpro:~/dev/recipes $ ssh -L 5900:localhost:5900 flutter@flutter-devicelab-windows-5.mtv.corp.google.com
F0130 09:25:11.776782       1 helper.go:447] Failed to initialize session: upgrading to websocket, HTTP 502 Bad Gateway: websocket: bad handshake
kex_exchange_identification: Connection closed by remote host
Connection closed by UNKNOWN port 65535
```

**Comment by ricardoamador** [comment]
This is firing low resource pool alerts.

**Comment by kentnguyen99** [comment]
Ricardo,
flutter-win-5 is up and ready for service.  Flutter-win-5 host wasn't down, it was asking prompt to upgrade software so I clicked on skip upgrade and it's starting working again.

**Comment by ricardoamador** [comment]
Thanks @kentnguyen99 ! Just curious but do you get the low resource pool alerts in your email?

**Comment by kentnguyen99** [comment]
Ricardo, We don't get the email alert when a server goes offline, just we check manually on the monitoring website.

**Comment by kentnguyen99** [comment]
flutter-win-5 has been online for the last two days, work completed.
