### ISSUE TITLE
flutter: command not found

### ISSUE THREAD

**Issue by vivonk** [flutter/flutter#11953]
I was trying to run flutter in my ubuntu  and  when I cloned flutter repository, after that I went into path 

> ~/github/flutter/bin 

And I type flutter but it's giving the error :- flutter: command not found
How I can come over to this and start building, should I clone repository in any other path and try again or something else is the better way.

**Comment by Alexays** [comment]
Just do 'export PATH=$PATH:~/github/flutter/bin' or save it in env ;)

**Comment by vivonk** [comment]
Thanks man, now it's working
