### ISSUE TITLE
[CP] NavigationBar ink ripple fixes

### ISSUE THREAD

**Issue by Piinks** [flutter/flutter#119554]
### issue_link

https://github.com/flutter/flutter/issues/117420

### Commit Hash

74645b43aa33e6328b4c05f6d58db7273b2fe17c

### Target

stable

### pr_link

https://github.com/flutter/flutter/pull/119553

### Impacted Users

All M3 users

### Impact Description

This fixes an issue with ink ripple alignment with the navigation bar when using Material 3.

In order to pick this commit, another previously cherry pick needed to be included: https://github.com/flutter/flutter/pull/117500

### Workaround

No.

### Risk

low

### Test Coverage

yes

### Validation Steps

The runnable example on https://master-api.flutter.dev/flutter/material/NavigationBar-class.html shows the issue, with this fix it no longer reproduces.

**Comment by CaseyHillers** [comment]
@HansMuller can you review this CP request?

**Comment by HansMuller** [comment]
LGTM
