### ISSUE TITLE
[CP] Fix position of ImageFilter layer when raster-cached

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#119543]
### issue_link

https://github.com/flutter/flutter/issues/119414

### Commit Hash

44362c90fcec2d080228bc251583a46dedc38b1b

### Target

stable

### pr_link

https://github.com/flutter/engine/pull/39257

### Impacted Users

All flutter users

### Impact Description

Any users with ImageFilters

### Workaround

No workaround

### Risk

medium

### Test Coverage

yes

### Validation Steps

Validate given test applications.

**Comment by jonahwilliams** [comment]
@zanderso

**Comment by zanderso** [comment]
CP LGTM
