### ISSUE TITLE
Images render blank since last roll

### ISSUE THREAD

**Issue by Alexays** [flutter/flutter#11952]
## Steps to Reproduce

Since last engine roll, all images render blank, i try to load image from package as it has been implemented recently :) but same :/

Any things have changed that I haven't noticed since the last roll ?

## Logs

No error log :/

## Flutter Doctor

[✓] Flutter (on Linux, locale en_US.UTF-8, channel master)
    • Flutter at /home/rouill_a/bin/flutter
    • Framework revision 8303fff8f9 (3 hours ago), 2017-09-06 11:53:39 +0200
    • Engine revision ceb6d05c2f
    • Tools Dart version 1.25.0-dev.11.0

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.1)
    • Android SDK at /opt/android-sdk
    • Platform android-26, build-tools 26.0.1
    • ANDROID_HOME = /opt/android-sdk
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] Android Studio (version 2.3)
    • Android Studio at /opt/android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] Connected devices
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 7.0 (API 24) (emulator)

**Comment by eseidelGoogle** [comment]
@chinmaygarde could this be the skia roll?

**Comment by chinmaygarde** [comment]
I'll investigate and let you know.

**Comment by Alexays** [comment]
Ah and also on state where are images, all is extremely laggy :/

**Comment by goderbauer** [comment]
I can confirm that the skia roll (https://github.com/flutter/engine/pull/4064) broke image rendering.

**Comment by jason-simmons** [comment]
This start with https://github.com/google/skia/commit/195c05b6d5afbd65f803816938e24eebd51292c8

Skia code is being compiled with GR_TEST_UTILS=1, but Flutter code that includes Skia headers does not enable GR_TEST_UTILS.  The inconsistency in class and constructor definitions (namely GrContextOptions) results in misconfiguration.

**Comment by brianosman** [comment]
So you're not building Skia with is_official_build enabled? Is there a reason for that?

**Comment by jason-simmons** [comment]
The Flutter build scripts were unaware of Skia's is_official_build and were not explicitly setting it.

Code internal to the Skia tree received the flags set by the skia_private config, including GR_TEST_UTILS.  The Flutter tree (excluding Vulkan) doesn't include skia_private.

We can set is_official_build=True in the flutter/tools/gn script.

**Comment by Hixie** [comment]
Looks like is_official_build is documented here: https://skia.org/user/build

The documentation says it turns off static linking (which seems bad?). It doesn't say it changes anything else (assuming we're controlling whether debug symbols are enabled separately). It's not clear to me why we would want it enabled? @brianosman Can you elaborate? Should the documentation be updated?
