### ISSUE TITLE
CupertinoSliverNavigationBar's alwaysShowMiddle now working during page transition

### ISSUE THREAD

**Issue by DavideDessi319** [flutter/flutter#119522]
## Steps to Reproduce
When I use a `CupertinoSliverNavigationBar` that transitions to a `CupertinoPageScaffold` containing a `CupertinoNavigationBar`, the hero transition looks all right, but the `middle` which should show only when the `CupertinoSliverNavigationBar` is scrolled is showing as well for a brief moment, both when pushing and popping the view.
I suppose this is the correct animation in case there's both a `largeTitle` and a `middle` visible, but it shouldn't be the case in case the `alwaysShowMiddle` property is set to false.

1. Execute `flutter run` on the code sample 
2. ... 
3. ... 

**Actual results:** 

https://user-images.githubusercontent.com/73545081/215542280-39db1728-06ad-4087-bce7-6ec11cc03c8a.mov

<details>
<summary>Code sample</summary>

Here is some code to reproduce the issue

Page one:

```dart
CupertinoPageScaffold(
      child: CustomScrollView(
        slivers: [
          CupertinoSliverNavigationBar(
            largeTitle: Text('Test large Title'),
            middle: Text('Test middle'),
            alwaysShowMiddle: false,
            automaticallyImplyLeading: false,
            backgroundColor:
                CupertinoTheme.of(context).scaffoldBackgroundColor.withOpacity(0.7),
            stretch: true,
            border: null,
          ),
        ],
      ),
    );
```

Page two

```dart
CupertinoPageScaffold(
      navigationBar: const CupertinoNavigationBar(
        middle: Text('Aggiungi'),
      ),
      child: Container(),
);
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by darshankawar** [comment]
Thanks for the report @DavideDessi319 
I came up with runnable code sample based on the code snippets you provided and ran it on iOS simulator using latest master version, but was unable to replicate the reported behavior.


https://user-images.githubusercontent.com/67046386/215698448-c770a8a6-2665-49fc-b59a-c7341866a676.mov


<details>
<summary> runnable code sample </summary>

```
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter App',
      theme: ThemeData(useMaterial3: true),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({super.key});

  @override
  Widget build(BuildContext context) {
    return CupertinoApp(
      home: Scaffold(
        body: InkWell(
          onTap: () => Navigator.of(context)
              .push(CupertinoPageRoute(builder: (context) => PageTwo())),
          child: CupertinoPageScaffold(
            child: CustomScrollView(
              slivers: [
                CupertinoSliverNavigationBar(
                  largeTitle: Text('Test large Title'),
                  middle: Text('Test middle'),
                  alwaysShowMiddle: false,
                  automaticallyImplyLeading: false,
                  backgroundColor: CupertinoTheme.of(context)
                      .scaffoldBackgroundColor
                      .withOpacity(0.7),
                  stretch: true,
                  border: null,
                ),
              ],
            ),
          ),
        ),
      )
    );
  }
}

class PageTwo extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return CupertinoPageScaffold(
      navigationBar: const CupertinoNavigationBar(
        middle: Text('Aggiungi'),
      ),
      child: Container(),
    );
  }
}

```

</details>

`Channel master, 3.7.0-31.0.pre.24`

Please check the same at your end or please provide complete code sample if above doesn't represent the case described.

**Comment by DavideDessi319** [comment]
> Thanks for the report @DavideDessi319 I came up with runnable code sample based on the code snippets you provided and ran it on iOS simulator using latest master version, but was unable to replicate the reported behavior.
> 
>  119522.mov 
> 
>  runnable code sample
> ```
> import 'package:flutter/cupertino.dart';
> import 'package:flutter/material.dart';
> 
> void main() {
>   runApp(const MyApp());
> }
> 
> class MyApp extends StatelessWidget {
>   const MyApp({super.key});
> 
>   @override
>   Widget build(BuildContext context) {
>     return MaterialApp(
>       title: 'Flutter App',
>       theme: ThemeData(useMaterial3: true),
>       home: const MyHomePage(),
>     );
>   }
> }
> 
> class MyHomePage extends StatelessWidget {
>   const MyHomePage({super.key});
> 
>   @override
>   Widget build(BuildContext context) {
>     return CupertinoApp(
>       home: Scaffold(
>         body: InkWell(
>           onTap: () => Navigator.of(context)
>               .push(CupertinoPageRoute(builder: (context) => PageTwo())),
>           child: CupertinoPageScaffold(
>             child: CustomScrollView(
>               slivers: [
>                 CupertinoSliverNavigationBar(
>                   largeTitle: Text('Test large Title'),
>                   middle: Text('Test middle'),
>                   alwaysShowMiddle: false,
>                   automaticallyImplyLeading: false,
>                   backgroundColor: CupertinoTheme.of(context)
>                       .scaffoldBackgroundColor
>                       .withOpacity(0.7),
>                   stretch: true,
>                   border: null,
>                 ),
>               ],
>             ),
>           ),
>         ),
>       )
>     );
>   }
> }
> 
> class PageTwo extends StatelessWidget {
>   @override
>   Widget build(BuildContext context) {
>     return CupertinoPageScaffold(
>       navigationBar: const CupertinoNavigationBar(
>         middle: Text('Aggiungi'),
>       ),
>       child: Container(),
>     );
>   }
> }
> ```
> 
> `Channel master, 3.7.0-31.0.pre.24`
> 
> Please check the same at your end or please provide complete code sample if above doesn't represent the case described.

Hello @darshankawar and thank you for the reply!

I'm sorry for the snipped provided, I just noticed it wasn't complete enough to replicate my situation.
I took your snipped and changed a few parts to make it set up as my app is. The problem happens when the change route also involves a hero transition between the large title and the `CupertinoNavigationBar` in the new page.

Here is the snippet to replicate the issue:

```dart
void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const CupertinoApp(
      title: 'Flutter App',
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: InkWell(
        onTap: () => Navigator.of(context)
            .push(CupertinoPageRoute(builder: (context) => const PageTwo())),
        child: CupertinoPageScaffold(
          child: CustomScrollView(
            slivers: [
              CupertinoSliverNavigationBar(
                largeTitle: const Text('Test large Title'),
                middle: const Text('Test middle'),
                alwaysShowMiddle: false,
                automaticallyImplyLeading: false,
                backgroundColor: CupertinoTheme.of(context)
                    .scaffoldBackgroundColor
                    .withOpacity(0.7),
                stretch: true,
                border: null,
              ),
            ],
          ),
        ),
      ),
    );
  }
}

class PageTwo extends StatelessWidget {
  const PageTwo({super.key});

  @override
  Widget build(BuildContext context) {
    return CupertinoPageScaffold(
      navigationBar: const CupertinoNavigationBar(
        middle: Text('Aggiungi'),
        previousPageTitle: 'Test Large Title',
      ),
      child: Container(),
    );
  }
}

```

**Comment by darshankawar** [comment]
Thanks for the updated code sample. Using it, I am able to replicate the same behavior on latest master and stable versions.

With `alwaysShowMiddle` pass as `false`, the middle text shows up upon navigation.

The field was added as part of https://github.com/flutter/flutter/issues/113542

<details>
<summary> stable, master flutter doctor -v </summary>

```
[!] Flutter (Channel stable, 3.7.0, on macOS 12.2.1 21D62 darwin-x64, locale
    en-GB)
    • Flutter version 3.7.0 on channel stable at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b06b8b2710 (28 hours ago), 2023-01-23 16:55:55 -0800
    • Engine revision b24591ed32
    • Dart version 2.19.0
    • DevTools version 2.20.1
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

[!] Flutter (Channel master, 3.8.0-1.0.pre.32, on macOS 12.2.1 21D62 darwin-x64,
    locale en-GB)
    • Flutter version 3.8.0-1.0.pre.32 on channel master at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f9daa9aac4 (53 minutes ago), 2023-02-01 22:59:24 -0500
    • Engine revision 679c4b42e2
    • Dart version 3.0.0 (build 3.0.0-192.0.dev)
    • DevTools version 2.21.1
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.



```

</details>

**Comment by DavideDessi319** [comment]
> Thanks for the updated code sample. Using it, I am able to replicate the same behavior on latest master and stable versions.
> 
> With `alwaysShowMiddle` pass as `false`, the middle text shows up upon navigation.
> 
> The field was added as part of #113542
> 
>  stable, master flutter doctor -v

Hello @darshankawar! 
Playing around with the `_TransitionableNavigationBar` class inside the `nav_bar.dart` file I was able to possibly fix this issue (I also did some regression testing and tested multiple scenarios and it seems to be working fine).
I was thinking of making my first contribution to the Flutter framework by solving this issue, I'll need to read out the Wiki, the igiene rules/best practices and write some tests but I think it would be interesting for me to do. Would it be okay for you or did you already start working on a fix for this? 

Thank you in advance!

**Comment by bleroux** [comment]
@DavideDessi319 
Contributions are welcomed!
I assigned you to the issue to notify other contributors you are working on a fix. Feel free to unassign you if you don't have time to work on it.

Please read the contribution guide. Main points are:
- Work on master channel.
- A fix requires at least one test (have a look to similar tests as inspiration.
- Do not use autoformat on Flutter code 😄.

Feel free to ping me if you need some help.

**Comment by DavideDessi319** [comment]
> @DavideDessi319 
> 
> Contributions are welcomed!
> 
> I assigned you to the issue to notify other contributors you are working on a fix. Feel free to unassign you if you don't have time to work on it.
> 
> 
> 
> Please read the contribution guide. Main points are:
> 
> - Work on master channel.
> 
> - A fix requires at least one test (have a look to similar tests as inspiration.
> 
> - Do not use autoformat on Flutter code 😄.
> 
> 
> 
> Feel free to ping me if you need some help.

Thank you very much @bleroux!! 
I'll make sure to read all the documentation and test everything properly before opening the PR 🙌

P.S. I love how welcoming all the Flutter contributors are, it for sure helps makes new people want to contribute and help! 😄
