### ISSUE TITLE
SPIKE: Utilize cocoon's readiness check to verify provenance exists

### ISSUE THREAD

**Issue by drewroengoogle** [flutter/flutter#119634]
Cocoon has a [readiness check](https://cs.opensource.google/flutter/cocoon/+/main:app_dart/lib/src/request_handlers/readiness_check.dart) that is used to verify if the server is ready to handle requests. We could utilize this check to ensure that the server has associated provenance.

Additional context here: https://github.com/flutter/cocoon/pull/2419#discussion_r1091998283

**Comment by godofredoc** [comment]
That validation would probably be really expensive to run as a readiness check and too late in the process to add value. E.g. if the service is already running the compromised binaries are already in use.

**Comment by godofredoc** [comment]
Obsolete?

**Comment by drewroengoogle** [comment]
Closing due to obsolete
