### ISSUE TITLE
No RTL support in flutter_adaptive_scaffold package

### ISSUE THREAD

**Issue by vipafattal** [flutter/flutter#119661]
No RTL support in [flutter_adaptive_scaffold](https://github.com/flutter/packages/tree/main/packages/flutter_adaptive_scaffold).

**How to reproduce?**
 
Easy, just wrap the `AdaptiveScaffold` widget with the `Directionality` widget

```dart
Directionality(
        textDirection: TextDirection.rtl,
        child: AdaptiveScaffold(
        .... 
        ),
      )
```

**Comment by darshankawar** [comment]
Thanks for the report. I think this is more of a current limitation than a bug, so I'll treat this as a proposal to support RTL.

**Comment by kyleorin** [comment]
RTL support would be great, any update on this?

**Comment by ahmednfwela** [comment]
@kyleorin I have filed PR https://github.com/flutter/packages/pull/4204
