### ISSUE TITLE
Framework tree closed on SkiaGold diff

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#119630]
See: https://ci.chromium.org/ui/p/flutter/builders/prod/Windows%20framework_tests_libraries/9200/overview

https://flutter-gold.skia.org/detail?test=material.flexible_space_bar_stretch_mode.blur_background&digest=682f7daddc094a52ba1d2ee688b6ee9e

The diffs are occurring on an engine roll that appears unrelated, and there were no diffs flagged in presubmit.

**Comment by Piinks** [comment]
Looks like another case of https://bugs.chromium.org/p/skia/issues/detail?id=14048 I updated the issue for the Gold team

The tree is currently green

**Comment by kjlubick** [comment]
`result-state.json: No result file found.`

What happened to that file? (created from goldctl auth and init)

**Comment by Piinks** [comment]
I am not sure, it may not be where we think it is. We check to make sure it exists though, and the contents are apparently empty:

https://github.com/flutter/flutter/blob/72f9cf54871a97a857d69873ffe6da0a884dd4b5/packages/flutter_goldens_client/lib/skia_client.dart#L221
