### ISSUE TITLE
Error: The method 'fromLngLatToTileIndex' isn't defined for the class 'EPSG4326'

### ISSUE THREAD

**Issue by AliPunjabi** [flutter/flutter#119610]
My code was running without any error yesterday, I upgraded by stable vesrion to latest and then switched to master and upgraded it too, after all this I went back to stable and downgraded it's version to exact previous one.. Now I am stuck here. Please have a look on my debug console logs:

 Error: The method 'fromLngLatToTileIndex' isn't defined for the class 'EPSG4326'.
../…/src/map.dart:59
- 'EPSG4326' is from 'package:latlng/src/projection.dart' ('../../../.pub-cache/hosted/pub.dartlang.org/latlng-0.1.1/lib/src/projection.dart').
package:latlng/src/projection.dart:1
Try correcting the name to the name of an existing method, or defining a method named 'fromLngLatToTileIndex'.

    final norm = projection.fromLngLatToTileIndex(controller._center);
                            ^^^^^^^^^^^^^^^^^^^^^
: Error: The method 'fromLngLatToTileIndex' isn't defined for the class 'EPSG4326'.
../…/src/map.dart:124
- 'EPSG4326' is from 'package:latlng/src/projection.dart' ('../../../.pub-cache/hosted/pub.dartlang.org/latlng-0.1.1/lib/src/projection.dart').
package:latlng/src/projection.dart:1
Try correcting the name to the name of an existing method, or defining a method named 'fromLngLatToTileIndex'.

    final mon = _projection.fromLngLatToTileIndex(_center);
                            ^^^^^^^^^^^^^^^^^^^^^
: Error: The method 'fromTileIndexToLngLat' isn't defined for the class 'EPSG4326'.
../…/src/map.dart:129
- 'EPSG4326' is from 'package:latlng/src/projection.dart' ('../../../.pub-cache/hosted/pub.dartlang.org/latlng-0.1.1/lib/src/projection.dart').
package:latlng/src/projection.dart:1

Try correcting the name to the name of an existing method, or defining a method named 'fromTileIndexToLngLat'.
    center = _projection.fromTileIndexToLngLat(mon);
                         ^^^^^^^^^^^^^^^^^^^^^

FAILURE: Build failed with an exception.

* Where:
Script '/Users/mac/Development/flutterSDK/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 1070

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command '/Users/mac/Development/flutterSDK/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 31s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

**My flutter doctor -v report**

 mac@macs-MacBook-Pro Alphatrack_1 copy % flutter doctor -v
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.4 21F79 darwin-x64, locale en-US)
    • Flutter version 2.8.1 at /Users/mac/Development/flutterSDK/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (1 year, 2 months ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/mac/Library/Android/sdk
    • Platform android-33, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.74.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.58.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 109.0.5414.119

• No issues found!

These are some configurations:
`ext.kotlin_version = "1.3.72"
lasspath 'com.android.tools.build:gradle:3.5.0'
distributionUrl=https\://services.gradle.org/distributions/gradle-6.3-all.zip
latlng: ^0.1.0
environment:
  sdk: ">=2.7.0 <3.0.0"`

**Comment by exaby73** [comment]
Hello @AliPunjabi. Looks like this method was removed from the package you're using. There is a known issue (https://github.com/flutter/flutter/issues/119091) where 3.7 ignores your package.lock file, and therefore I think your package has been upgraded to a newer version that doesn't have this method without your knowledge.

But since this is not an issue with Flutter, I am closing this issue. I suggest to open an issue with the package author. Thank you
