### ISSUE TITLE
Roll HarfBuzz mirror to 6.0.0

### ISSUE THREAD

**Issue by jason-simmons** [flutter/flutter#119682]
I'd like to roll Flutter's branch of HarfBuzz to version 6.0.0.

The HarfBuzz mirror on https://flutter.googlesource.com/third_party/harfbuzz/ needs to be updated to https://github.com/harfbuzz/harfbuzz/commit/afcae83a064843d71d47624bc162e121cc56c08b

Flutter will then add build scripts (and possibly other patches) to a branch based on the 6.0.0 commit.

**Comment by godofredoc** [comment]
https://flutter.googlesource.com/third_party/harfbuzz/ is now being auto-updated. @jason-simmons please take a look.

**Comment by jason-simmons** [comment]
At one point the https://flutter.googlesource.com/third_party/harfbuzz/ mirror contained a "flutter" branch that could be used to hold Flutter-specific patches such as build scripts.

That branch disappeared before I could push patches to it.

Can that branch be restored?  And is the branch being deleted by the mirror auto-updater?

**Comment by nehalvpatel** [comment]
@jason-simmons Is harfbuzz being auto updated now like Godofredo said? @godofredoc any info on the branch? Not sure if I can see history for who deleted a branch on GoB.

**Comment by jason-simmons** [comment]
There is an auto updater that is copying the latest HarfBuzz upstream to  https://flutter.googlesource.com/third_party/harfbuzz/

However, I need a place where I can check in Flutter-specific patches to our mirror of HarfBuzz.

I would be fine with disabling the auto updater if that would make it easier to set up a branch for Flutter patches.

**Comment by keyonghan** [comment]
Requesting the grant access to disable the auto updater.

**Comment by keyonghan** [comment]
Disabled the auto fetch for repo: https://flutter.googlesource.com/third_party/harfbuzz/.
Feel free to reopen if you need anything else.
