### ISSUE TITLE
flutter_deps recipe module should fetch an x64 jdk on arm64 mac

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#119632]
Similar to https://github.com/flutter/flutter/issues/119631

When running on an arm64 mac, the code here:

https://flutter.googlesource.com/recipes/+/refs/heads/main/recipe_modules/flutter_deps/api.py#115

attempts to fetch a mac_arm64 openjdk, which is not in CIPD, and fails. This issue could also be addressed by populating CIPD with an appropriate file there.

@godofredoc

**Comment by zanderso** [comment]
This should be helped by https://github.com/flutter/engine/pull/39375

**Comment by godofredoc** [comment]
@zanderso can we close this one?

**Comment by zanderso** [comment]
I need to try a led run or two, but I'll reopen if it isn't fixed.
