### ISSUE TITLE
Decommission flutter-devicelab-signing-2

### ISSUE THREAD

**Issue by kentnguyen99** [flutter/flutter#119671]
Our monitoring website shows flutter-devicelab-signing-2 dead for one week now.  From the network side signing-2 host is online and running fine but it is good that someone should login and check out why the website is marked as dead.

![Screenshot 2023-01-31 5 25 45 PM](https://user-images.githubusercontent.com/120754754/215923708-50e6381f-d224-4c4b-abf6-9abf807dd3d9.png)

**Comment by XilaiZhang** [comment]
Synced with Godofredo today and the conclusion is to abandon the machine. @yusuf-goog also has the context

**Comment by yusuf-goog** [comment]
@kentnguyen99 flutter-devicelab-signing-2 is no longer required and can be removed. 

Please keep the machine, and check what the disk size is. If it has the required disk, we can repurpose it as a mac builder. If not, we will decommission it.

**Comment by kentnguyen99** [comment]
Shutting down host signing-2 and removing from the rack mount has been completed.
