### ISSUE TITLE
Does Flutter consider to support AOP?

### ISSUE THREAD

**Issue by GvcZhang** [flutter/flutter#119609]
I need a function just like Android Gradle Plugin provide that i can inject other code to Java class, I think this feature is great that i can do some auto program. Does Flutter has plan to support this?

**Comment by exaby73** [comment]
Hello @GvcZhang. Can you explain what you mean by injecting code? Do you mean code that is hosted on a server that you are able to download and execute dynamically, or are you talking about static meta-programming?

**Comment by GvcZhang** [comment]
My target is that i can modify codes during compile state. Just like Android Gradle Plugin's [Transform](https://developer.android.com/reference/tools/gradle-api/7.3/com/android/build/api/transform/Transform).

**Comment by GvcZhang** [comment]
Now what i do is modify `frontend_server.dart.snapshot`, so that i can add some codes by  Flutter  AST API. The following i s pseudocode which shows my means:
```
//original code
class Demo{

     void click(){ //target method
         doSomething();
     }
}


//modified code
class Demo{

     void click(){//target method
         doAClick();// auto add
         doSomething();
     }
}
```

**Comment by exaby73** [comment]
I think this would be possible with static metaprogramming. There's already an issue open on the Dart repository (https://github.com/dart-lang/language/issues/1482).

The current way of changing / extending code is using [`build_runner`](https://pub.dev/packages/build_runner) and [`source_gen`](https://pub.dev/packages/source_gen). Packages like [`json_serializable`](https://pub.dev/packages/json_serializable) for example use this to generate code
