### ISSUE TITLE
flutter doctor can't find flutter

### ISSUE THREAD

**Issue by DevYJKwon** [flutter/flutter#119658]
## Steps to Reproduce

1. ... I downloaded stable version of zip file and unpacked in C:/src/
2. ... run flutter doctor in cmd 
3. ...

## Logs

<details>
<summary>Logs</summary>

```
```

```
```

</details>

C:\Windows\System32>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[☠] Flutter (the doctor check crashed)
    X Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know
      about this issue at https://github.com/flutter/flutter/issues.
    X Exception: Cannot find the executable for `where`. This can happen if the System32 folder (e.g.
      C:\Windows\System32 ) is removed from the PATH environment variable. Ensure that this is present and then try
      again after restarting the terminal and/or IDE.
[☠] Windows Version (the doctor check crashed)
    X Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know
      about this issue at https://github.com/flutter/flutter/issues.
    X ProcessException: Failed to find "systeminfo" in the search path.
        Command: systeminfo

**Comment by exaby73** [comment]
Hello @DevYJKwon. Can you check if the path `C:\Windows\System32` is in the PATH variable. To check it, you can follow the instructions [here](https://www.howtogeek.com/787217/how-to-edit-environment-variables-on-windows-10-or-11/)

**Comment by DevYJKwon** [comment]
@exaby73 I tried but It is still same as before

**Comment by exaby73** [comment]
Could you provide the output of `echo $env:PATH`? Please try to remove any personal information that might be in the output before sharing

**Comment by DevYJKwon** [comment]
@exaby73 

C:\Windows\system32\config\systemprofile\AppData\Local\Microsoft\WindowsApps		
C:\Program Files\dotnet\	
C:\Program Files\openJDK\jdk-19.0.1\bin	
C:\Users\Admin\AppData\Roaming\nvm	
C:\Program Files\nodejs	
C:\src\flutter\bin	
C:\Program Files\Git\cmd	
C:\Windows\System32\WindowsPowerShell\v1.0	
C:\Windows\System32	
C:\Users\Admin\AppData\Local\Microsoft\WindowsApps	
C:\Users\Admin\AppData\Local\GitHubDesktop\bin	
C:\Users\Admin\.dotnet\tools	C:\Users\Admin\AppData\Local\Programs\Microsoft VS Code\bin	C:\Users\Admin\AppData\Roaming\nvm		
C:\src\flutter\bin	
C:\Windows\System32

**Comment by exaby73** [comment]
I just noticed that you're running this command from `C:\Windows\System32` from your original comment. You should not run Flutter as a administrator. Can you try running the same command from a different folder, not from an admin terminal

**Comment by DevYJKwon** [comment]
@exaby73 Oh, now everything is working fine thank you.

**Comment by hasmin1** [comment]
Hola, yo sigo teniendo el mismo problema y seguí todos los pasos y aun así sigue igual.

**Comment by christopherfujino** [comment]
@DevYJKwon hmm, it seems the Flutter CLI tool is struggling to find any tools on the path (not just flutter, but also `where`,  and `systeminfo`). Can you share the output of `echo %PATH%`? Also try to manually run `where flutter` and `systeminfo` in your command prompt.
