### ISSUE TITLE
How to know webview scrolling is reached bottom of the page

### ISSUE THREAD

**Issue by N-sravan** [flutter/flutter#119696]
I'm using Webview to show the HTML page. When user scrolls bottom of the HTML page, I need to run some code.
 But I'm not able to find a way to get status of Webview is reached the bottom of the page.

**Comment by ravanalaskarov** [comment]
You can listen to the `scrollController.position.pixels` property and check if it equals to `scrollController.position.maxScrollExtent` to determine if the user has reached the bottom of the HTML page.

```
WebView(
initialUrl: 'https://example.com/',
onWebViewCreated: (WebViewController webViewController) {
_controller = webViewController;
_controller.addListener(() {
if (_controller.scrollY == _controller.getScrollYRange().end) {
print("Reached bottom");
// your code here when the user reaches the bottom of the page
}
});
},
)
```

**Comment by danagbemava-nc** [comment]
Hi @N-sravan, the above sample may not work in the new version of webview_flutter but there are existing issues for this already in place. 

See https://github.com/flutter/flutter/issues/31027 &  https://github.com/flutter/flutter/issues/42442.

Closing this in favor of the issues linked above. 

Thank you
