### ISSUE TITLE
FlutterTrustedTypesPolicy does not respect base href or path urls.

### ISSUE THREAD

**Issue by schultek** [flutter/flutter#119633]
## Steps to Reproduce

1. Create a new flutter project: `flutter create myapp --platform=web`
2. Build for web: `flutter build web`
3. Serve the app, e.g. `serve -s -l 3000 build/web`
  - Make sure to serve as a single-page app, so all url paths are rewritten  to `index.html`
4. Go to `localhost:3000/hello/world`

**Expected results:** 

The app runs without errors.

**Actual results:** 

<img width="815" alt="Bildschirmfoto 2023-01-31 um 16 35 16" src="https://user-images.githubusercontent.com/13920539/215805046-7878364d-d34d-46ff-89e4-96316123e61c.png">

As shown `flutter.js` tries to load both the service worker from `localhost:3000/hello/flutter_service_worker.js` and main script from `localhost:3000/hello/main.dart.js`, which are wrong urls. 

---

I already did some digging, and the culprit is this:

https://github.com/flutter/flutter/blob/2c34a88eb89628e6a80caa50dd03797f9b6aa5e5/packages/flutter_tools/lib/src/web/file_generators/flutter_js.dart#L78-L105

Especially line 92:

https://github.com/flutter/flutter/blob/2c34a88eb89628e6a80caa50dd03797f9b6aa5e5/packages/flutter_tools/lib/src/web/file_generators/flutter_js.dart#L92

Here the full page url (`window.location`) is uses as a base for the trusted url (which is used both for the service-worker and main.dart script url).

Some quick testing hinted that changing this to `window.document.baseURI` could solve this and also respect the `<base>` element. 

---

### Additional context

We have a flutter web app running on a domain like `some.domain/client` with `client` being the base href. I only noticed this bug because going to `some.domain/client/` works fine, while going to `some.domain/client` fails.

<details>

```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.0, on macOS 12.4 21F79 darwin-x64, locale de-DE)
...
```

</details>

**Comment by Caio-Rezende** [comment]
It solved for me using at the flutter loader the following:

`
          .loadEntrypoint({
            serviceWorker: {
              serviceWorkerVersion: serviceWorkerVersion,
            },
            entrypointUrl: `${window.document.baseURI}main.dart.js`,
          })`

**Comment by darshankawar** [comment]
Thanks for the report and your findings @schultek 
A related issue was fixed and merged recently that maybe helpful in your case : https://github.com/flutter/flutter/pull/118684, so can you try to switch to latest master and run your scenario again to see if the behavior persists or not ?

**Comment by schultek** [comment]
Thanks that seems to solve it.
