### ISSUE TITLE
TabBar and TabBarView is causing "Null check operator used on a null value" error

### ISSUE THREAD

**Issue by Rishikesh-278** [flutter/flutter#119693]
I'm trying to create a medium app clone. As you can read in this code, It uses FirebaseAuth to Show the image and display name. I also have a Tab option on the page. The _TabBar_ and _TabBarView_ page says it

```
class Account extends StatelessWidget {
  const Account({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return DefaultTabController(
      length: 3,
      child: Scaffold(
        appBar: AppBar(
          elevation: 0,
          backgroundColor: Colors.transparent,
          actions: [IconButton(onPressed: () {}, icon: Icon(Icons.settings))],
        ),
        body: ListView(
          children: [
            Column(
              children: <Widget>[
                ProfileDetails(context), //profile details
                const SizedBox(height: 20),
                Row(
                  mainAxisAlignment: MainAxisAlignment.spaceEvenly,
                  children: <Widget>[
                    const SizedBox(width: 15),
                    Expanded(
                      child: ElevatedButton(
                        onPressed: () {},
                        child: Text(
                          "View stats",
                          style: TextStyle(color: Colors.white),
                        ),
                        style: ElevatedButton.styleFrom(
                            fixedSize: Size.fromHeight(40),
                            elevation: 0,
                            shape: RoundedRectangleBorder(
                                borderRadius: BorderRadius.circular(50)),
                            backgroundColor: Colors.transparent,
                            side: const BorderSide(color: Colors.white, width: 1)),
                      ),
                    ), //View stats button
                    const SizedBox(width: 20),
                    Expanded(
                      child: ElevatedButton(
                        onPressed: () {},
                        child: Text(
                          "Edit profile",
                          style: TextStyle(color: Colors.white),
                        ),
                        style: ElevatedButton.styleFrom(
                            fixedSize: Size.fromHeight(40),
                            elevation: 0,
                            shape: RoundedRectangleBorder(
                                borderRadius: BorderRadius.circular(50)),
                            backgroundColor: Colors.transparent,
                            side: BorderSide(color: Colors.white, width: 1)),
                      ),
                    ), //Edit profile button
                    const SizedBox(width: 15),
                  ],
                ), //stats and edit button
              ],
            ),
            const TabBar(tabs: [
              Tab(text: "Stories"),
              Tab(text: "List"),
              Tab(text: "About")
            ]),
            const TabBarView(children: [
              stories(),
              list(),
              about(),
            ]),
          ],
        ),
      ),
    );
  }
}

Padding ProfileDetails(BuildContext context) {
  if (FirebaseAuth.instance.currentUser == null) {
    return Padding(
      padding: const EdgeInsets.fromLTRB(15, 0, 15, 0),
      child: Container(),
    );
  }

  return Padding(
    padding: const EdgeInsets.fromLTRB(15, 0, 15, 0),
    child: Container(
      child: Row(
        mainAxisAlignment: MainAxisAlignment.start,
        children: <Widget>[
          CircleAvatar(
            radius: 30,
            backgroundImage:
                (NetworkImage(FirebaseAuth.instance.currentUser!.photoURL!)),
          ),
          const SizedBox(width: 20),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(FirebaseAuth.instance.currentUser!.displayName!),
                Row(
                  children: const <Widget>[
                    Text("Followers", style: TextStyle(fontSize: 20)),
                    SizedBox(width: 5),
                    Text(".", style: TextStyle(fontSize: 20)),
                    SizedBox(width: 5),
                    Text("Following", style: TextStyle(fontSize: 20))
                  ],
                ),
              ],
            ),
          ),
        ],
      ),
    ),
  );
}

```

This above code gives me an error saying "_Null check operator used on a null value_"

But when I comment out the `TabBar` and `TabBarView` widgets, it works perfectly.

Why is this happening?

**Comment by danagbemava-nc** [comment]
Hi @Rishikesh-278, 

Please provide your `flutter doctor -v` and `flutter run --verbose` logs that capture the full error logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) without any third-party packages or plugins. 

Please also provide steps to reproduce. 

Thank you

**Comment by Rishikesh-278** [comment]
The error:- `======== Exception caught by rendering library =====================================================
The following _CastError was thrown during paint():
Null check operator used on a null value

The relevant error-causing widget was: 
  ListView ListView:file:///D:/Flutter%20course/Medium_Clone/lib/Pages/Account.dart:36:15
When the exception was thrown, this was the stack: 
#0      RenderViewportBase._paintContents (package:flutter/src/rendering/viewport.dart:676:25)
#1      RenderViewportBase.paint (package:flutter/src/rendering/viewport.dart:662:7)
#2      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2796:7)
#3      PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:155:11)
#4      PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:98:5)
#5      PaintingContext._compositeChild (package:flutter/src/rendering/object.dart:250:7)
#6      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:231:7)
#7      RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:144:15)
#8      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2796:7)
#9      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:239:13)
#10     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:144:15)
#11     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2796:7)
#12     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:239:13)
#13     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:144:15)
#14     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2796:7)
#15     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:239:13)
#16     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:144:15)
#17     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2796:7)
#18     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:239:13)
#19     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:144:15)
#20     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2796:7)
#21     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:239:13)
#22     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:144:15)
#23     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2796:7)
#24     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:239:13)
#25     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:144:15)
#26     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2796:7)
#27     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:155:11)
#28     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:98:5)
#29     PaintingContext._compositeChild (package:flutter/src/rendering/object.dart:250:7)
#30     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:231:7)
#31     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:144:15)
#32     RenderCustomPaint.paint (package:flutter/src/rendering/custom_paint.dart:616:11)
#33     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2796:7)
#34     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:239:13)
#35     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:144:15)
#36     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2796:7)
#37     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:155:11)
#38     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:98:5)
#39     PaintingContext._compositeChild (package:flutter/src/rendering/object.dart:250:7)
#40     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:231:7)
#41     RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2900:15)
#42     RenderCustomMultiChildLayoutBox.paint (package:flutter/src/rendering/custom_layout.dart:415:5)
#43     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2796:7)
#44     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:239:13)
#45     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:144:15)
#46     _RenderInkFeatures.paint (package:flutter/src/material/material.dart:609:11)
#47     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2796:7)
#48     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:239:13)
#49     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:144:15)
#50     RenderPhysicalModel.paint.<anonymous closure> (package:flutter/src/rendering/proxy_box.dart:2098:15)
#51     PaintingContext.pushClipRRect (package:flutter/src/rendering/object.dart:550:14)
#52     RenderPhysicalModel.paint (package:flutter/src/rendering/proxy_box.dart:2085:21)
#53     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2796:7)
#54     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:239:13)
#55     RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2900:15)
#56     RenderCustomMultiChildLayoutBox.paint (package:flutter/src/rendering/custom_layout.dart:415:5)
#57     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2796:7)
#58     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:239:13)
#59     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:144:15)
#60     _RenderInkFeatures.paint (package:flutter/src/material/material.dart:609:11)
#61     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2796:7)
#62     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:239:13)
#63     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:144:15)
#64     RenderPhysicalModel.paint.<anonymous closure> (package:flutter/src/rendering/proxy_box.dart:2098:15)
#65     PaintingContext.pushClipRRect (package:flutter/src/rendering/object.dart:550:14)
#66     RenderPhysicalModel.paint (package:flutter/src/rendering/proxy_box.dart:2085:21)
#67     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2796:7)
#68     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:239:13)
#69     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:144:15)
#70     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2796:7)
#71     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:239:13)
#72     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:144:15)
#73     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2796:7)
#74     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:155:11)
#75     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:98:5)
#76     PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:1116:31)
#77     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:515:19)
#78     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:884:13)
#79     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:378:5)
#80     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1175:15)
#81     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1104:9)
#82     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1015:5)
#83     _invoke (dart:ui/hooks.dart:148:13)
#84     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:318:5)
#85     _drawFrame (dart:ui/hooks.dart:115:31)
The following RenderObject was being processed when the exception was fired: RenderViewport#fce4d
...  needs compositing
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(0.0<=w<=411.4, 0.0<=h<=720.8)
...  layer: OffsetLayer#d9aa8 DETACHED
...    handles: 1
...    offset: Offset(0.0, 0.0)
...  size: Size(411.4, 720.8)
...  axisDirection: down
...  crossAxisDirection: right
...  offset: ScrollPositionWithSingleContext#fe6a1(offset: 0.0, range: null..null, viewport: 720.8, ScrollableState, AlwaysScrollableScrollPhysics -> ClampingScrollPhysics -> RangeMaintainingScrollPhysics, IdleScrollActivity#d5769, ScrollDirection.idle)
...  anchor: 0.0
RenderObject: RenderViewport#fce4d
  needs compositing
  parentData: <none> (can use size)
  constraints: BoxConstraints(0.0<=w<=411.4, 0.0<=h<=720.8)
  layer: OffsetLayer#d9aa8 DETACHED
    handles: 1
    offset: Offset(0.0, 0.0)
  size: Size(411.4, 720.8)
  axisDirection: down
  crossAxisDirection: right`

Flutter doctor -v :-
`D:\Flutter course\Medium_Clone>flutter doctor -v
[√] Flutter (Channel stable, 3.3.5, on Microsoft Windows [Version 10.0.19044.2486], locale en-IN)
    • Flutter version 3.3.5 on channel stable at c:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d9111f6402 (4 months ago), 2022-10-19 12:27:13 -0700
    • Engine revision 3ad69d7be3
    • Dart version 2.18.2
    • DevTools version 2.15.0

[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at D:/Softwares/SDks
    • Platform android-33, build-tools 32.0.0
    • Java binary at: D:\Softwares\Software Setups\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.13)
    • Visual Studio at D:\Softwares\Microsoft Visual studio\packages
    • Visual Studio Community 2019 version 16.11.32413.511
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.1)
    • Android Studio at D:\Softwares\Software Setups\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] Android Studio (version 4.1)
    • Android Studio at D:\softwares\software setups\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] Connected device (4 available)
    • SM M317F (mobile) • RZ8N92EM0PR • android-arm64  • Android 12 (API 31)
    • Windows (desktop) • windows     • windows-x64    • Microsoft Windows [Version 10.0.19044.2486]
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 109.0.5414.120
    • Edge (web)        • edge        • web-javascript • Microsoft Edge 109.0.1518.70

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
`

Getting the output of verbose is too big. Hope this helps

**Comment by danagbemava-nc** [comment]
Hi @Rishikesh-278, you are on an older version of flutter. Kindly upgrade to the latest version of flutter stable (3.7.1) to see if you still reproduce the issue. 

If you do, please provide the updated output of `flutter doctor -v` and an updated code sample **without any third-party plugins or packages**. 

Thank you
