### ISSUE TITLE
any plan to close 11,380 issue     

### ISSUE THREAD

**Issue by periva101** [flutter/flutter#119692]
we are a native mobile company, however I would like to use flutter, but I am aired 11,380 issue , so any plan to close them ?

**Comment by stuartmorgan** [comment]
See https://github.com/flutter/flutter/wiki/Issue-hygiene#issue-philosophy

We have no plan to mass-close valid, actionable issues, nor would doing so improve the quality of the code.

**Comment by periva101** [comment]
why?
@stuartmorgan

**Comment by Hixie** [comment]
I'm also happy to discuss this by e-mail if you don't want to join our Discord. To join our Discord, see the link in the contributing docs, you can ping me, my name there is @Hixie. My e-mail is ian@hixie.ch if you prefer e-mail.
