### ISSUE TITLE
the daemon failed to start

### ISSUE THREAD

**Issue by rewan999** [flutter/flutter#119621]
i have this problem 
![image](https://user-images.githubusercontent.com/105081470/215767767-08242df3-0163-4924-b2e4-e27cc7605448.jpeg)

**Comment by rewan999** [comment]
![Uploading 215768105...]![image](https://user-images.githubusercontent.com/105081470/215768106-597c1cb1-aaf0-4b73-954a-e0924d57787e.jpeg)

**Comment by rewan999** [comment]
![image](https://user-images.githubusercontent.com/105081470/215768523-86e6f1c9-2893-4824-941e-7ec896701703.jpeg)

**Comment by MTGCGuerrero** [comment]
By any chance, you cant run flutter doctor?. 
What I did was to copy and paste an older flutter version(windows 3.3.10)  over the current flutter folder that Visual Studio Code uses.
Close Visual Studio code then try to create another flutter project or run flutter doctor to see what else is missing.

**Comment by huycozy** [comment]
@rewan999 Can you elaborate on this issue by specifying `Steps to reproduce`? 

Does this issue happen on a new Flutter project (counter app)? Also, please provide the output of `flutter doctor -v` as well. Thanks!
