### ISSUE TITLE
Error (Xcode): Target debug_unpack_ios failed: Exception: Failed to copy framework (exit 23:

### ISSUE THREAD

**Issue by NextChans** [flutter/flutter#119674]
## Steps to Reproduce

1. when i 'run&debug" from vscode by iphone simulator, 
2. It is not working with error 

Error (Xcode): Target debug_unpack_ios failed: Exception: Failed to copy framework (exit 23:

How can i solve? please help me. 

## Logs

<details>
<summary>Launching lib/main.dart on iPhone SE (3rd generation) in debug mode...
lib/main.dart:1
Xcode build done.                                            6.2s
Failed to build iOS app
Error (Xcode): Target debug_unpack_ios failed: Exception: Failed to copy framework (exit 23:

Could not build the application for the simulator.
Error launching application on iPhone SE (3rd generation).
Exited</summary>

[✓] Flutter (Channel stable, 3.7.0, on macOS 13.2 22D49 darwin-arm64, locale ko-KR)
    • Flutter version 3.7.0 on channel stable at /Users/hyunchan-jang/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b06b8b2710 (8 days ago), 2023-01-23 16:55:55 -0800
    • Engine revision b24591ed32
    • Dart version 2.19.0
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/hyunchan-jang/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.74.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.58.0

[✓] Connected device (3 available)
    • iPhone SE (3rd generation) (mobile) • 402FA055-CD56-4D84-A29D-58C9A647B935 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-2 (simulator)
    • macOS (desktop)                     • macos                                • darwin-arm64   • macOS 13.2 22D49 darwin-arm64
    • Chrome (web)                        • chrome                               • web-javascript • Google Chrome 109.0.5414.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

</details>

**Comment by huycozy** [comment]
@NextChans Can you share the complete output of `flutter run -v`? If the log is too long, please save it into a file and attach it here.

**Comment by NextChans** [comment]
> @NextChans Can you share the complete output of `flutter run -v`? If the log is too long, please save it into a file and attach it here.

here is log file(attached). thank you.

[terminal_log.txt](https://github.com/flutter/flutter/files/10564191/terminal_log.txt)

**Comment by huycozy** [comment]
@NextChans Does this issue happen on a new Flutter project? Also, can you try switching to Flutter master channel, then switching back to stable channel and retry?

**Comment by NextChans** [comment]
> @NextChans Does this issue happen on a new Flutter project? Also, can you try switching to Flutter master channel, then switching back to stable channel and retry?

yes. it is new Flutter project and i did change channel and retry.. and it is working on Chrome.  thank you for your reply..

**Comment by huycozy** [comment]
>it is working on Chrome

I guess it's working on iOS too, correct? Feel free to close the issue once it's solved. Thanks!
