### ISSUE TITLE
flutter-devicelab-mac-39 & mac-40 kept loosing device on the new iphone11.

### ISSUE THREAD

**Issue by kentnguyen99** [flutter/flutter#119659]
Time to time I kept seeing flutter-devicelab-mac-39 and flutter-devicelab-mac-40 and also other Mac hosts kept losing connection for the new iphone 11 device. If  I unplug and plug iphone11 device from the host and it's starting working again.  Will someone take a look and double check on the new iphone 11 settings might be missed.

Thanks,
Kent

![Screenshot 2023-01-31 12 45 35 PM](https://user-images.githubusercontent.com/120754754/215902356-be929824-e539-409f-b9c8-daa6a3a7143d.png)

**Comment by kentnguyen99** [comment]
Adding flutter-devicelab-mac-45 to the ticket, same issue as other servers.

![Screenshot 2023-02-01 4 50 42 PM](https://user-images.githubusercontent.com/120754754/216204004-7064b5f7-7978-4471-adea-5d18a1508f1a.png)

**Comment by yusuf-goog** [comment]
@jmagman We have noticed some iphone11 devices go into this state. Is there something we can look for to root cause? 

@kentnguyen99 can confirm, but I believe unplugging and replugging them bring them back online.

@kentnguyen99 can you please check if the lock screen timeout has been disabled under settings.

**Comment by kentnguyen99** [comment]
Already checked the settings on all new iphones 11 and auto lock disabled.

**Comment by kentnguyen99** [comment]
Adding flutter-devicelab-mac-24 to the ticket, same issue as other servers.

![Screenshot 2023-02-02 9 17 03 AM](https://user-images.githubusercontent.com/120754754/216395884-be4c4684-9cc8-4e20-850a-f9260c8be89a.png)

**Comment by kentnguyen99** [comment]
Adding flutter-devicelab-mac-5 to the ticket, same issue as other servers.

![Screenshot 2023-02-02 9 39 47 AM](https://user-images.githubusercontent.com/120754754/216400795-17156044-df96-4e15-a404-b00ec293c246.png)

**Comment by yusuf-goog** [comment]
@kentnguyen99  

Without changing anything, can you look at the mobile devices and see if there is some dialog or alert showing on them?

Also, if you take one of the devices, unplug and replug, does it come back online?

**Comment by yusuf-goog** [comment]
@kentnguyen99 can you also check the battery graph under settings> battery health  in one of the phones, I want to make sure that the battery didn't did in the middle of the night.

**Comment by yusuf-goog** [comment]
Lets recover mac-6 and mac-24, to bring back prod capacity, and leave one or two of the other ones for @jmagman to look at.

**Comment by kentnguyen99** [comment]
@yusuf-goog 
I checked this morning and the error went away, both mac-39 & mac-40 can see external devices now. However, the errors pop up on other hosts, like mac-5 & mac-24.

**Comment by kentnguyen99** [comment]
@yusuf-goog 
mac-6's external device hung, I can't power the recycle device and it needs to drain the battery to reboot the device.

**Comment by yusuf-goog** [comment]
By "external" device, do you mean the mobile phone?

Its not responsive at all?

You should be able to hard reset it.

**Comment by kentnguyen99** [comment]
@yusuf-goog 
I unplug/plug the phone on mac-24, it's starting working again.

**Comment by kentnguyen99** [comment]
@yusuf-goog 

mac-6 & mac-24 both phones have been fixed, errors are gone now.

**Comment by kentnguyen99** [comment]
Adding flutter-devicelab-mac-4 to the ticket, same issue as other servers.

![Screenshot 2023-02-02 3 25 18 PM](https://user-images.githubusercontent.com/120754754/216473869-9e0f4c86-7f5a-4b5b-8699-bba30d28a098.png)

**Comment by jmagman** [comment]
@kentnguyen99 thanks for looking into this!
1. I know you said you have autolock disabled, but do the devices no passcodes set up at all?  If so, can you remove it? When it's in the disconnected state is the phone unlocked and the screen on?
2. When you unplugged and plugged the phone back in, did you see the Trust This Computer dialog on the phone? 
3. Developer mode is on in the phone settings, right? https://developer.apple.com/documentation/xcode/enabling-developer-mode-on-a-device

Next time instead of unplugging and plugging the phone back in can you try on the phone untrusting the Mac via **Settings > General > Transfer or Reset [Device] > Reset > Reset Location & Privacy** https://support.apple.com/en-us/HT202778, then unplug and plug the phone back in and re-trust?

**Comment by kentnguyen99** [comment]
@jmagman 

We don't set passcodes and autolock disabled for all new iphones 11.

Last night I followed your instructions to reset "Reset Location & Privacy" on the phone and click on "Trust" again when prompts for couples phones and they seem to be working.

**Comment by kentnguyen99** [comment]
@jmagman 

Mac-4's phone was working fine from evening last night until 11:38am it stopped working.

Are there other settings we need to revisit or check on the iphone 11?

![Screenshot 2023-02-03 11 41 53 AM](https://user-images.githubusercontent.com/120754754/216693563-fec58d25-fd36-42db-bd29-fc5ce7096211.png)

**Comment by jmagman** [comment]
Are these all unresponsive like https://github.com/flutter/flutter/issues/119659#issuecomment-1414173978? Or does the phone seem okay?

Do you have an example of the run where the device healthcheck failed that caused the quarantine?  That might help us tell what exactly failed.

**Comment by jmagman** [comment]
> Are these all unresponsive like [#119659 (comment)](https://github.com/flutter/flutter/issues/119659#issuecomment-1414173978)? Or does the phone seem okay?
> 
> Do you have an example of the run where the device healthcheck failed that caused the quarantine? That might help us tell what exactly failed.

Should have tagged @kentnguyen99 in this question so it was clear who I was asking, sorry.
