### ISSUE TITLE
[CP] Make gen-l10n error handling independent of logger state

### ISSUE THREAD

**Issue by AlexV525** [flutter/flutter#119678]
### issue_link

https://github.com/flutter/flutter/issues/119593

### Commit Hash

3884381415928d72f847dafe73e1c1e45cbdce6b

### Target

stable

### pr_link

https://github.com/flutter/flutter/pull/119679

### Impacted Users

Users that are using any overridden `FLUTTER_STORAGE_BASE_URL`

### Impact Description

The issue is breaking every user that is using localizations and a custom `FLUTTER_STORAGE_BASE_URL`. The `gen-l10n` tool will report `Found syntax errors` but not any actual syntax errors.

### Workaround

https://github.com/flutter/flutter/issues/119593#issuecomment-1409708288 or CP https://github.com/flutter/flutter/pull/119644.

### Risk

low

### Test Coverage

yes

### Validation Steps

Follow the steps to reproduce in https://github.com/flutter/flutter/issues/119593#issue-1563533629.

**Comment by christopherfujino** [comment]
This CP LGTM
