### ISSUE TITLE
Setup linux-13 and linux-28

### ISSUE THREAD

**Issue by yusuf-goog** [flutter/flutter#119643]
Please setup linux-13 and linux-28 hosts for use with salt:

1) In /etc/salt/master the hostname is set to fqdn (not sure if this is actually needed):
id: [flutter-devicelab-mac-11.mtv.corp.google.com](http://flutter-devicelab-mac-11.mtv.corp.google.com/)
2) Add the following to /etc/salt/minion:
autosign_grains:
  - fqdn

Once complete, you can apply salt states on linux-13 (since it is already authorized to connect to salt master). 

For linux-28, I will create a new CL to add it to the salt master key list, after which you can apply salt states for that machine as well.

**Comment by yusuf-goog** [comment]
linux-28 has been added to salt master auto accept list. please go ahead and apply salt states.

**Comment by yusuf-goog** [comment]
Lets leave this open till those hosts show up successfully in the swarming dashboard. E.g. https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-linux-13

* We need to resolve issues with the luci machine_tokend expiration.
* Need to create CL to move linux-28 into the swarming pools.

**Comment by yusuf-goog** [comment]
Linux-13 is back up. It was having problems authenticating to the swarming server:

```748 2023-02-02 19:10:44.662 I: ts_mon hook_name='get_authentication_headers' pool='cores:8|cpu:x86-64-avx2|cpu_governor:powersave|gce:0|gpu:8086:9a49-20.0.8|inside_docker:0|kernel:5.4.0-137-generic|kvm:1|locale:en_US.UTF-8|machine_type:n1-highcpu-8|os:Linux|os:Ubuntu-18.04.6|pool:default|python:3.8.10+chromium.17|ssd:1|zone:cloud'
748 2023-02-02 19:10:44.662 I: get_authentication_headers(): 0s
748 2023-02-02 19:10:44.662 I: Fetched auth headers (dict_keys(['X-Luci-Machine-Token'])), they expire in 2356 sec. Next check in 1786 sec.
748 2023-02-02 19:10:44.777 D: https://chromium-swarm.appspot.com:443 "POST /swarming/api/v1/bot/handshake HTTP/1.1" 403 None
748 2023-02-02 19:10:44.778 W: Got a reply with HTTP status code 403 for https://chromium-swarm.appspot.com/swarming/api/v1/bot/handshake on attempt 0: 403 Client Error: Forbidden for url: https://chromium-swarm.appspot.com/swarming/api/v1/bot/handshake
748 2023-02-02 19:10:44.778 E: Request to https://chromium-swarm.appspot.com/swarming/api/v1/bot/handshake failed with HTTP status code 403: 403 Client Error: Forbidden for url: https://chromium-swarm.appspot.com/swarming/api/v1/bot/handshake
748 2023-02-02 19:10:44.778 E: Failed to contact for handshake, retrying in 300 sec...
748 2023-02-02 19:15:44.779 I: Calling /swarming/api/v1/bot/handshake
```

This was because the hostname was not identifying as expected. The /etc/hosts file had an entry:
`127.0.1.1	 flutter-devicelab-linux-13`

And we needed to add the fqdn to it:
`127.0.1.1	flutter-devicelab-linux-13.mtv.corp.google.com flutter-devicelab-linux-13`

Rebooted the host and its back up.

**Comment by keyonghan** [comment]
Bots are up and running.
