### ISSUE TITLE
Debugger displays contents of _Uint8List incorrectly (lower nibbles only)

### ISSUE THREAD

**Issue by mh-** [flutter/flutter#119685]
This code works correctly
```
 Uint8List testList = Uint8List.fromList([0x00, 0x01, 0x0f, 0x10, 0x11, 0x1f, 0xf0, 0xf1, 0xff]);
 if (kDebugMode) {
   print(testList);
 }
```
Output:
```
flutter: [0, 1, 15, 16, 17, 31, 240, 241, 255]
```

but **in the iOS debugger, the contents of the list is displayed incorrectly, only the lower nibbles are printed**:

<img width="1245" alt="image" src="https://user-images.githubusercontent.com/6257627/215962414-40ca87a3-d7fe-45b7-bc0d-4206eba07d6c.png">

```
% flutter upgrade                                                                                                   
Flutter is already up to date on channel stable
Flutter 3.7.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision b06b8b2710 (8 days ago) • 2023-01-23 16:55:55 -0800
Engine • revision b24591ed32
Tools • Dart 2.19.0 • DevTools 2.20.1
```
<img width="377" alt="image" src="https://user-images.githubusercontent.com/6257627/215963078-535b13fc-58be-4af3-875c-645dd6de1a6e.png">

**Comment by danagbemava-nc** [comment]
Hi @mh-, I think this might be an issue with the flutter plugin for intellij as I cannot reproduce this with vscode. Do you still face the issue in vscode? If not you might have to file an issue over on the [intellij plugin repo](https://github.com/flutter/flutter-intellij/issues?q=is:issue+sort:updated-desc)

<img width="1469" alt="Screenshot 2023-02-01 at 12 23 55" src="https://user-images.githubusercontent.com/88313112/216041659-73e0a887-914f-4388-a5bc-def5c6f8c603.png">

<img width="1596" alt="Screenshot 2023-02-01 at 12 28 26" src="https://user-images.githubusercontent.com/88313112/216043770-9d65ed9d-f120-4360-a4ef-71d72ae1452e.png">

**Comment by mh-** [comment]
Sorry, I don't have a VSCode setup to try this, only Android Studio - I will file the issue in the other project.
