### ISSUE TITLE
NestedScrollView is broken. Body is scrollable even if it has no items

### ISSUE THREAD

**Issue by nzkn** [flutter/flutter#119699]
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. ... 
3. ... 

**Expected results:** 
I expect NestedScrollView body to not be scrollable when there are no items.

**Actual results:** 
NestedScrollView is scrollable. There is no way to implement RefreshIndicator with SliverAppBar, which is very discouraging, considering this is so simple feature.

<details>

<summary>Code sample</summary>

```dart
NestedScrollView(
  headerSliverBuilder: (_, __) => SliverAppBar(
    pinned: true,
    floating: true,
    flexibleSpace: SomeWidget(),
  ),
  body: RefreshIndicator(
    child: ListView.builder(
  ....
);
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by ravanalaskarov** [comment]
You can wrap the ListView.builder in a ScrollController and only allow it to scroll when there are items in it.


`final _scrollController = ScrollController();
...
NestedScrollView(
  headerSliverBuilder: (_, __) => SliverAppBar(
    pinned: true,
    floating: true,
    flexibleSpace: SomeWidget(),
  ),
  body: ListView.builder(
    controller: _scrollController,
    physics: items.isEmpty ? NeverScrollableScrollPhysics() : ScrollPhysics(),
  ....
);
`

**Comment by nzkn** [comment]
@ravanalaskarov Have you tested you example? NeverScrollableScrollPhysics doesn't block the scroll in this case

**Comment by ravanalaskarov** [comment]
@nzkn 
Check this out: 
https://dartpad.dev/?id=3ce3c0a47f7f93249048dd989df94be0

Additionally, if you want, you can set `NestedScrollView` widget's `physics` property to `NeverScrollableScrollPhysics()`.

**Comment by nzkn** [comment]
@ravanalaskarov Do you test your code before posting? Both solutions you suggested doesn't solve the issue

**Comment by huycozy** [comment]
@nzkn Please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this. Also, please provide the output of `flutter doctor -v` as well.
