### ISSUE TITLE
Improve UX for common box constraint scenarios

### ISSUE THREAD

**Issue by LarkAscending** [flutter/flutter#11962]
## Steps to Reproduce

1. Encounter a layout error; usually some variation of "Horizontal viewport was given unbounded height."
2. Do an online search to find someone else with the same error. The only page that seems to reference this problem is https://flutter.io/layout/#unbounded-constraints.
3. Can't solve the error, even once finding this page. 

Users often want to "shrink wrap" things -- basically to just tell widgets to fill the height or width they need without being more explicit than that. The ListView actually allows you to set 'shrinkWrap: true' on its children which is easy and always fixes these errors.

But Row or a Column or something else that can't just be "shrink-wrapped" in this way. Often the result is hacking something together with a LayoutBuilder and a ConstrainedBox, or something like that.

Can the framework be enhanced so Row and Column can shrinkWrap their contents, similar to ListView?
Or maybe there's another way to solve this issue?

If the framework can't address this issue, then [Dealing with box constraints in Flutter](https://flutter.io/layout/#unbounded-constraints) could be improved with some more examples of errors and more suggestions on how to fix or avoid common errors.

**Comment by markusaksli-nc** [comment]
Closing due to the improvements made to the [Dealing with box constraints](https://flutter.dev/docs/development/ui/layout/box-constraints) and the addition of [Understanding constraints](https://flutter.dev/docs/development/ui/layout/constraints).
