### ISSUE TITLE
Fix dev/tools/bin/find_commit.dart to work on release branches

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#119652]
This was originally fixed in https://github.com/flutter/flutter/pull/119648, but was not created in tip of tree.

This should be added to tip of tree with tests.

**Comment by XilaiZhang** [comment]
Ouch i don't think there is a test for find_commit.dart yet. It would take a non trivial amount of time to understand every part of find_commit and write a test for it.
