### ISSUE TITLE
goma recipe module should use x64 goma client on arm64 mac

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#119631]
In particular, Flutter recipes currently use the logic here: https://fuchsia.googlesource.com/infra/recipes/+/refs/heads/main/recipe_modules/goma/api.py#105, which fails on an arm64 mac because the mac_arm64 binary does not exist in CIPD.

This issue could also be addressed by populating a mac_arm64 goma client in CIPD.

@godofredoc

**Comment by zanderso** [comment]
Gentle ping @godofredoc. This is a blocker for engine builds using the arm64 macs.

**Comment by godofredoc** [comment]
Some updates from goma team. The goma client is deprecated and won't get arm64 support. The x64 binaries may work on arm but the server pools do not have any arm workers.

The proposed path forward is to migrate to rbe which will be using linux workers to cross compile arm targets.

**Comment by godofredoc** [comment]
Fixed with https://flutter-review.googlesource.com/c/recipes/+/39881
