### ISSUE TITLE
libtxt: TextSpan.paint to paint background colour etc

### ISSUE THREAD

**Issue by paolosoares** [flutter/flutter#11961]
flutter.io's HTML/CSS analogs section specifies that one can render a highlighter text with:

```dart
var container = new Container( // grey box
    child: new Text(
      "Lorem ipsum",
      style: bold24Roboto,
    ),
    width: 320.0,
    height: 240.0,
    color: Colors.grey[300],
  );
```

The doc itself specifies that the resulting effect is similar to:

```html
<div class="greybox">
  Lorem ipsum
</div>

.greybox {
      background-color: #e0e0e0;  /* grey 300 */
      width: 320px;
      height: 240px;
      font: 900 24px Roboto;
    }
```

However, there's no way to highlight parts of a text, analog to:

```html
Lorem <span class="greybox">ipsum</span> dolor

.greybox {
      background-color: #e0e0e0;  /* grey 300 */
      width: 320px;
      height: 240px;
      font: 900 24px Roboto;
    }
```

This blocks project mulligan.

**Comment by Hixie** [comment]
@jason-simmons volunteered to take a look and see what this would involve.

**Comment by Hixie** [comment]
We can probably do paint easily enough, though strokes and shapes would be non-trivial on the engine side.
We could do anything on the framework side but figuring out the offsets would be expensive.

**Comment by Hixie** [comment]
After further considering I'm pretty sure the solution here is to make `ui.TextStyle` take a `Paint` which it applies to each box that the span covers.

**Comment by Hixie** [comment]
We are currently considering our long-term plan for text rendering so we aren't exactly sure how we'll address this. We will have an update in a week or so.

**Comment by Hixie** [comment]
cc @jason-simmons Let me know if you need API advice on this when you get around to it.
