### ISSUE TITLE
`flavors_test_macos` is failing, timing out

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#119782]
This test was turned on in https://github.com/flutter/flutter/pull/119564 and is consistently failing on timeout.

https://ci.chromium.org/p/flutter/builders/staging/Mac%20flavors_test_macos/54
https://ci.chromium.org/p/flutter/builders/staging/Mac%20flavors_test_macos/44
![Screenshot 2023-02-01 at 7 20 08 PM](https://user-images.githubusercontent.com/682784/216223394-b6d9b9ba-00e0-4359-bfbd-df094e517d52.png)

@cbracken

**Comment by flar** [comment]
This has been red for over a month. Is it worth 30 minutes of bot time per commit to keep this active until a solution is found?
