### ISSUE TITLE
Please replace all iphone6s devices in lab with iphone11

### ISSUE THREAD

**Issue by yusuf-goog** [flutter/flutter#119742]
@kentnguyen99 release engineering has confirmed that we no longer need any old iphone 6s. Please replace any existing iphone 6s with the new iphone11 in the lab.

Keep the old iphone 6s devices in our storage.

**Comment by kentnguyen99** [comment]
I need two more new iPhone 11, not enough to cover all hosts in the lab.

**Comment by yusuf-goog** [comment]
did we get back the mac-7 iphone11 device?

**Comment by kentnguyen99** [comment]
Swapping iphone 6s to new iphone 11 to all hosts in the lab has been completed; However, we need two more new iphones 11 for host=mac-5 & mac-11.
