### ISSUE TITLE
[CP] Fix null check error in DWDS

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#119749]
### issue_link

https://github.com/flutter/flutter/issues/119084

### Commit Hash

The fix was upstream in dwds: https://github.com/dart-lang/webdev/commit/be616cd0e34b57c1852ff84fab28541d567e08a0

### Target

stable

### pr_link

https://github.com/flutter/flutter/pull/119745

### Impacted Users

Flutter for web developers debugging their apps

### Impact Description

On a request to evaluate multiple expressions, the tooling would fail and not finish the operation

### Workaround

none

### Risk

low

### Test Coverage

yes

### Validation Steps

I am not sure how to manually create the situation will a null objectId

**Comment by christopherfujino** [comment]
cc @zra for approval

**Comment by christopherfujino** [comment]
cc @zanderso for approval

**Comment by zanderso** [comment]
CP lgtm
