### ISSUE TITLE
Error of flutter: command not found in another terminal

### ISSUE THREAD

**Issue by vivonk** [flutter/flutter#11974]
Last night I solved error of flutter: command not found but now, I am again getting that same error when I closed that session and went to sample folder to run application. I type
`flutter run`

**but it gives the error, also I was unable to understand how to save that path in bash_profile**

**Comment by Hixie** [comment]
Does this help?: https://unix.stackexchange.com/questions/26047/how-to-correctly-add-a-path-to-path

**Comment by vivonk** [comment]
Thanks @Hixie

**Comment by therajanmaurya** [comment]
If any case anybody will get error This is perfect solution to add path https://flutter.io/setup-macos/#update-your-path.
