### ISSUE TITLE
InteractiveViewer to have horizontal and vertical scroll bar support

### ISSUE THREAD

**Issue by nandhakumargdr** [flutter/flutter#119787]
Making a scroll bar horizontal and vertical will be useful

## Use case

When we design a layout with InteractiveViewer that set constraints = false will become scrollable to the child size in all direction

## Proposal

In such cases, it will be good to have a horizontal and vertical scroll bar to see the limits of interactive viewer

@

**Comment by nandhakumargdr** [comment]
@justinmc  Could you please help with this?

**Comment by darshankawar** [comment]
I think a similar proposal has been discussed in this related issue: https://github.com/flutter/flutter/issues/64210 but I think it had lot of other features mentioned in it, so I'll keep this issue open and label as proposal.

**Comment by justinmc** [comment]
I talked this over with @Piinks awhile back, and we decided to keep InteractiveViewer unrelated to scrolling.  Scrolling comes with a lot of baggage and we want to keep InteractiveViewer for other use cases like image viewers, games, etc.

For your use case, you probably want to wait for @Piinks's upcoming work on 2D scrolling: https://www.youtube.com/watch?v=UDZ0LPQq-n8
