### ISSUE TITLE
flutter/packages needs flutter/plugins Cirrus secrets

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#119730]
Currently flutter/plugins has two Cirrus secrets used by FTL tests:
- A Firebase Test Lab key to allow running the tests in the first place
- A maps API key for maps integration tests

As part of [merging the repositories](https://github.com/flutter/flutter/issues/113764) those keys need to be copied over to flutter/packages.

**Comment by stuartmorgan** [comment]
@godofredoc Who has the ability to do this? Is it just repo admins, or some larger group of people?

**Comment by godofredoc** [comment]
I think only org|repo admins can do that, can you please open a bug using http://go/flutter-security-bug providing the details?

**Comment by stuartmorgan** [comment]
Filed as b/267472828, thanks.

**Comment by godofredoc** [comment]
Update the internal bug.

**Comment by stuartmorgan** [comment]
Thanks!
