### ISSUE TITLE
[infra] linux android tests queued for > 3 hours on stable hotfix release

### ISSUE THREAD

**Issue by XilaiZhang** [flutter/flutter#119751]
![Screenshot 2023-02-01 at 12 49 03 PM](https://user-images.githubusercontent.com/38773539/216160413-08340687-5e83-4d4b-accd-09f327ca6fbb.png)

This added to the release time.

**Comment by XilaiZhang** [comment]
more context: the linux andriod tests were queued for hours. It was intially pointed out by Casey that the long wait time might have come from devices competing for resources in the morning. But after waiting for more than 3 hours it is realized that there might be an actual error when these targets were queued.

**Comment by yusuf-goog** [comment]
@XilaiZhang please add a link as well as image to the relevant dashboard.

**Comment by XilaiZhang** [comment]
sure, dash board link is https://flutter-dashboard.appspot.com/#/build?taskFilter&authorFilter&messageFilter&hashFilter&showMac=true&showWindows=true&showiOS=true&showLinux=true&showAndroid=true&showStaging=false&repo=flutter&branch=flutter-3.7-candidate.1

**Comment by yusuf-goog** [comment]
Everything looks caught up now. Do you have a link to the actual build that was pending for >3 hours?

**Comment by yusuf-goog** [comment]
This seems to have resolved. reopen if its still an issue.

**Comment by XilaiZhang** [comment]
> Everything looks caught up now. Do you have a link to the actual build that was pending for >3 hours?

the 5 queued tests don't have corresponding build links, but they were queued for > 3 hours (blue square)
