### ISSUE TITLE
ci_yaml flutter roller is failing

### ISSUE THREAD

**Issue by hterkelsen** [flutter/flutter#119753]
See this recent run for an example failure: https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20ci_yaml%20flutter%20roller/7282/overview

```
[P7527 12:16:16.604 generate.go:94 I] Generating configs using lucicfg v1.38.0...
Error: open config/.lucicfgfmtrc: no such file or directory
```

**Comment by CaseyHillers** [comment]
Redirecting to Yusuf, the oncall

**Comment by yusuf-goog** [comment]
Consulting with LUCI team on this.

**Comment by yusuf-goog** [comment]
This is due to a LUCI related change, its being reverted right now.

**Comment by yusuf-goog** [comment]
Their change was submitted, I have also kicked off another build: https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20ci_yaml%20flutter%20roller/7283/overview

Build succeeded, closing.
