### ISSUE TITLE
video_player play large video gets timeout

### ISSUE THREAD

**Issue by AugustWangVeeva** [flutter/flutter#119777]
I use video_player: 2.3.0 to play video more than 2G, and after open the video, it is loading, and then gets the error:
PlatformException (PlatformException(VideoError, Failed to load video: The request timed out., null, null)

code is:
`_videoPlayerController = VideoPlayerController.network(widget.url);
    await _videoPlayerController.initialize();`
and the error is in `initialize`.

run the app on ipad.
Flutter (Channel stable, 2.8.0, on macOS 12.5.1 21G83 darwin-x64, locale zh-Hans-CN)

**Comment by darshankawar** [comment]
Thanks for the report @AugustWangVeeva 
Can you provide a sample video file of the said size that we can use to verify the behavior ?
Also is it only occuring on iPad or same error occurs on simulator / device too ?
Please also try to upgrade to latest stable or master version and run your scenario to see if you still get same error or not.

**Comment by AugustWangVeeva** [comment]
@darshankawar Thank you so much for the quick response!!
This is the video url, but it has expire date, please help to reproduce the issue before it expired.
https://cdnvis50-c2.veevacrmqa.cn/a9e00927-a862-44d9-bbcc-8aada6f2b8ca/0000000/000000/001/494/production/video.mp4?access_token=b76375521b3b67d13477d4da062b7c38f4f5204cc9ede36222523c4650e9332f&expired=1675372932

And my flutter version is 2.8, the latest version of video_player I could use is 2.3.0.

**Comment by darshankawar** [comment]
I used the given link in video_player plugin example and ran it on iOS simulator and iPad simulator, although it took time to load and finally play it, but I didn't see the reported behavior.

<img width="552" alt="Screenshot 2023-02-03 at 11 49 54 AM" src="https://user-images.githubusercontent.com/67046386/216527180-d7ccc2dd-516e-4d9d-8f44-402608fc40a1.png">

As the file size you are using is quite large, it probably bound to have some delay, lags but also check if you have enough space and memory to properly play it. I also suggest you to verify the same link on a native iOS app and see how it plays / behaves there.

**Comment by AugustWangVeeva** [comment]
Hi @darshankawar, is there any way to pass a parameter to video_player to set the timeout value? Because I really got the error 'The request timed out' when waiting for the video to play.

**Comment by darshankawar** [comment]
I don't see such parameter yet. Were you able to verify using native app ?
