### ISSUE TITLE
[CP] Do not format the messages file for `gen-l10n`

### ISSUE THREAD

**Issue by AlexV525** [flutter/flutter#119771]
### issue_link

https://github.com/flutter/flutter/issues/119594

### Commit Hash

4ae2d3b6dfafbeafeb0957aa38b6f3d3634716e3

### Target

stable

### pr_link

https://github.com/flutter/flutter/pull/119770

### Impacted Users

Who used to have untranslated fields after they upgraded to Flutter 3.7 if they use format during `gen-l10n`.

### Impact Description

The l10n tool should not use `dart format` for the untranslated message file because it cannot be formatted by dart format, which will cause the generator to fail.

![image](https://user-images.githubusercontent.com/15884415/215653924-7d9b96a8-c5ec-4850-ab0a-6d5d51b3c441.png)

See also: https://github.com/flutter/flutter/issues/119594#issue-1563556261.

### Workaround

Not use format for gen-l10n.

### Risk

low

### Test Coverage

yes

**Comment by AlexV525** [comment]
cc @christopherfujino @thkim1011

**Comment by christopherfujino** [comment]
Am I understanding it correctly that this issue only affects invocations of `flutter gen-l10n --format`? In which case, wouldn't the workaround be not using the flag `--format`?

**Comment by AlexV525** [comment]
> Am I understanding it correctly that this issue only affects invocations of `flutter gen-l10n --format`? In which case, wouldn't the workaround be not using the flag `--format`?

Yeah that's correct.

**Comment by godofredoc** [comment]
Actually moving this one back to review until somebody with more context approves it.

**Comment by thkim1011** [comment]
The consensus was that there's currently a workaround to this issue by disabling the format flag, so we should rather wait for this to land in the next release. cc @christopherfujino
