### ISSUE TITLE
[camera_android] Bump robolectric version to allow configurations for SDK >= 31

### ISSUE THREAD

**Issue by camsim99** [flutter/flutter#119752]
The [current robolectric version](https://github.com/flutter/plugins/blob/main/packages/camera/camera_android/android/build.gradle#L68) (4.5) used for the Android camera plugin does not support configuring tests to run on >= SDK 31. However, there are a number of tests in the plugin that configure tests this way, e.g. [ResolutionFeatureTest.java](https://github.com/flutter/plugins/blob/main/packages/camera/camera_android/android/src/test/java/io/flutter/plugins/camera/features/resolution/ResolutionFeatureTest.java#L193). The robolectric version should be bumped to allow these tests to run.

Having tried to bump it experimentally, I know that this causes errors concerning unsupported Mockito operations, and these will have to be fixed as well to land the bump.

Dependabot may try to bump this version and create a PR, to which this issue should be linked.

**Comment by gmackall** [comment]
@camsim99 this can be closed now that https://github.com/flutter/packages/pull/4018 has landed, right?

Does the body of the pr have to have specific wording to cause the issue to autoclose when the PR lands?

**Comment by camsim99** [comment]
> @camsim99 this can be closed now that [flutter/packages#4018](https://github.com/flutter/packages/pull/4018) has landed, right?
> 
> Does the body of the pr have to have specific wording to cause the issue to autoclose when the PR lands?

Oh yes it needed "fixes <issue_number>"! You're right though, let's close this!
