### ISSUE TITLE
Form.of() was called with a context that does not contain a Form widget.

### ISSUE THREAD

**Issue by barilki** [flutter/flutter#119823]
Hi, 
After upgrading to Flutter 3.7.0, I receive the following exception:

======== Exception caught by gesture ===============================================================
The following assertion was thrown while handling a gesture:
Form.of() was called with a context that does not contain a Form widget.

No Form widget ancestor could be found starting from the context that was passed to Form.of(). This can happen because you are using a widget that looks for a Form ancestor, but no such ancestor exists.
The context used was:

I'm using **Form.of(context)?.validate();**

**Comment by barilki** [comment]
The issue has been temporarily resolved by wrapping the Form child with
Builder(
        builder: (ctx) {
})

**Comment by darshankawar** [comment]
Thanks for the report @barilki 
Can you provide which version were you on earlier before upgrading to 3.7 ? And whether it didn't throw the said error in that version and only triggered after upgrading ?

Please provide your `flutter doctor -v` too along with minimal reproducible code sample that shows the error.
