### ISSUE TITLE
The program does not open in the release for Windows

### ISSUE THREAD

**Issue by AlexSensey** [flutter/flutter#119808]
The program in the Windows edition does not always open. Everything opens normally in debug

Very often works in the background.  if you use this code  (in file -> flutter_window.cpp)
**flutter_controller_->engine()->SetNextFrameCallback([&]() {
   this->Show();
 });**

if you use a record without   **SetNextFrameCallback** 
and just call it
**this->Show();**

Everything is also revealed in the release and there are no problems.

[#issue-1560850626](https://github.com/flutter/flutter/issues/119415)  the same topic

**Comment by exaby73** [comment]
Hi @AlexSensey
I see there's an open issue addressing the case you described https://github.com/flutter/flutter/issues/119415
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
