### ISSUE TITLE
Issue with new spell check feature for TextField.

### ISSUE THREAD

**Issue by TreyThomas93** [flutter/flutter#119868]
## Issue

> Code below works fine on Android emulator...
```dart
TextField(
    spellCheckConfiguration: const SpellCheckConfiguration()
);
```

> but when I attempt to run it on a physical device (Galaxy S20+), I get the following error:
```
_AssertionError ('package:flutter/src/widgets/editable_text.dart': Failed assertion: line 2205 pos 7: 'spellCheckService != null
      || WidgetsBinding.instance.platformDispatcher.nativeSpellCheckServiceDefined': spellCheckService must be specified for this platform because no default service available)     
```

> but when I add a __DefaultSpellCheckService__ instance to the __spellCheckService__ field, it "works", as in it no longer outputs an __*AssertionError*__.
```dart
TextField(
    spellCheckConfiguration: const SpellCheckConfiguration(
        spellCheckService: DefaultSpellCheckService(),
    )
)
```
> I am then faced with another issue. Every word typed into the __TextField__ is represented as a __*misspelled word*__.

![screenshot-1675381663389](https://user-images.githubusercontent.com/56699859/216476873-e2b95bf4-e899-4612-a590-24abe69bbd14.png)

Any help will be appreciated. Thank you.

## Versions
> Flutter 3.7.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision b06b8b2710 (10 days ago) • 2023-01-23 16:55:55 -0800
Engine • revision b24591ed32
Tools • Dart 2.19.0 • DevTools 2.20.1

**Comment by huycozy** [comment]
Hi @TreyThomas93 
I try below sample code on my device (Realme 6, Android 11) but can not reproduce this issue. Verified on the latest stable and master channels. 

<details>
<summary>Sample code</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatefulWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const Scaffold(
        body: Center(
          child: TextField(spellCheckConfiguration: SpellCheckConfiguration()),
        ),
      ),
    );
  }
}
```
</details>

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.7.1, on macOS 13.0.1 22A400 darwin-x64, locale en-VN)
    • Flutter version 3.7.1 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7048ed95a5 (11 hours ago), 2023-02-01 09:07:31 -0800
    • Engine revision 800594f1f4
    • Dart version 2.19.1
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio Dolphin 2021.3.1.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio Dolphin 2021.3.1.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[!] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.74.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.58.0

[✓] Connected device (4 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D                         • android-arm64  • Android 11 (API 30)
    • iPhone (mobile)  • d9a94afe2b649fef56ba0bfeb052f0f2a7dae95e • ios            • iOS 15.7.2 19H218
    • macOS (desktop)  • macos                                    • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)     • chrome                                   • web-javascript • Google Chrome 109.0.5414.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```

```bash
[!] Flutter (Channel master, 3.8.0-2.0.pre.43, on macOS 13.0.1 22A400 darwin-x64, locale en-VN)
    • Flutter version 3.8.0-2.0.pre.43 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3570cce58e (64 minutes ago), 2023-02-03 04:34:17 +0300
    • Engine revision 2871970337
    • Dart version 3.0.0 (build 3.0.0-196.0.dev)
    • DevTools version 2.21.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Users/huynq/Library/Java/JavaVirtualMachines/corretto-1.8.0_302/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment Corretto-8.302.08.1 (build 1.8.0_302-b08)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.74.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.58.0

[✓] Connected device (3 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D • android-arm64  • Android 11 (API 30)
    • macOS (desktop)  • macos            • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)     • chrome           • web-javascript • Google Chrome 109.0.5414.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.

```
</details>

What is your device OS version currently? Does the issue happen with this sample code? If so, please provide the complete output of `flutter run -v` so that we may verify it. Thanks!

**Comment by TreyThomas93** [comment]
@huycozy Thanks for the response. The version I tested on is  Android 13. Thanks

**Comment by luis901101** [comment]
@TreyThomas93 check if your device system language is the same as the language you are typing. I just tested and spell checker uses device system language instead of keyboard language, which is not ideal.
Anyway I just get it to work on Android but not in iOS, tested in physical Android Device with Android 8.1.0 and iOS devices with 15.7.2 and 16.2.

**Comment by huycozy** [comment]
@TreyThomas93 I tested this with `Samsung Galaxy Tab A7 Lite, Android 13` but didn't see the exception. 

Does the issue happen with this sample code at https://github.com/flutter/flutter/issues/119868#issuecomment-1415643154 or only with your code? Please also provide the complete output of `flutter run -v` so that we may verify it.

**Comment by TreyThomas93** [comment]
@huycozy 

Output from running ```flutter run -v``` on physical android device.

<details>
<summary>Output</summary>
<br>

            ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
                    The following assertion was thrown building UnmanagedRestorationScope:
                    spellCheckService must be specified for this platform because no default service available
                    'package:flutter/src/widgets/editable_text.dart':
                    Failed assertion: line 2205 pos 7: 'spellCheckService != null
                          || WidgetsBinding.instance.platformDispatcher.nativeSpellCheckServiceDefined'

                    Either the assertion indicates an error in the framework itself, or we should provide substantially
                    more information in this error message to help you determine and fix the underlying cause.
                    In either case, please report this assertion by filing a bug on GitHub:
                      https://github.com/flutter/flutter/issues/new?template=2_bug.md

                    The relevant error-causing widget was:
                      TextField TextField:file:///C:/Users/TreyT/OneDrive/Desktop/projects/sample/lib/main.dart:29:20

                    When the exception was thrown, this was the stack:
                    #2      EditableTextState._inferSpellCheckConfiguration (package:flutter/src/widgets/editable_text.dart:2205:7)
                    #3      EditableTextState.initState (package:flutter/src/widgets/editable_text.dart:2367:32)
                    #4      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5101:55)
                    #5      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4944:5)
                    ...     Normal element mounting (10 frames)
                    #15     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953:16)
                    #16     Element.updateChild (package:flutter/src/widgets/framework.dart:3682:18)
                    #17     SlottedRenderObjectElement._updateChildren (package:flutter/src/widgets/slotted_render_object_widget.dart:270:33)
                    #18     SlottedRenderObjectElement.mount (package:flutter/src/widgets/slotted_render_object_widget.dart:224:5)
                    ...     Normal element mounting (94 frames)
                    #112    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953:16)
                    #113    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6512:36)
                    #114    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6524:32)
                    ...     Normal element mounting (318 frames)
                    #432    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953:16)
                    #433    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6512:36)
                    #434    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6524:32)
                    ...     Normal element mounting (469 frames)
                    #903    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953:16)
                    #904    Element.updateChild (package:flutter/src/widgets/framework.dart:3682:18)
                    #905    RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1176:16)
                    #906    RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:1145:5)
                    #907    RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:1092:18)
                    #908    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2682:19)
                    #909    RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:1091:13)
                    #910    WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:926:7)
                    #911    WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:906:7)
                    #915    _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:192:26)
                    (elided 5 frames from class _AssertionError, class _Timer, and dart:async-patch)

</details>

<details>
<summary>Flutter Doctor</summary>
<br>

    [√] Flutter (Channel stable, 3.7.0, on Microsoft Windows [Version 10.0.22621.1105], locale en-US)
        • Flutter version 3.7.0 on channel stable at C:\Users\TreyT\OneDrive\Documents\flutter
        • Upstream repository https://github.com/flutter/flutter.git
        • Framework revision b06b8b2710 (2 weeks ago), 2023-01-23 16:55:55 -0800
        • Engine revision b24591ed32
        • Dart version 2.19.0
        • DevTools version 2.20.1
    
    [√] Windows Version (Installed version of Windows is version 10 or higher)
    
    [√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
        • Android SDK at C:\Users\TreyT\AppData\Local\Android\sdk
        • Platform android-33, build-tools 33.0.0
        • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
        • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
        • All Android licenses accepted.
    
    [√] Chrome - develop for the web
        • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe
    
    [√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.2.6)
        • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
        • Visual Studio Community 2022 version 17.2.32630.192
        • Windows 10 SDK version 10.0.19041.0
    
    [√] Android Studio (version 2021.2)
        • Android Studio at C:\Program Files\Android\Android Studio
        • Flutter plugin can be installed from:
            https://plugins.jetbrains.com/plugin/9212-flutter
        • Dart plugin can be installed from:
            https://plugins.jetbrains.com/plugin/6351-dart
        • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    
    [√] VS Code (version 1.75.0)
        • VS Code at C:\Users\TreyT\AppData\Local\Programs\Microsoft VS Code
        • Flutter extension version 3.58.0
    
    [√] Connected device (5 available)
        • SM G986U (mobile)            • R5CN10647FZ   • android-arm64  • Android 13 (API 33)
        • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 13 (API 33) (emulator)
        • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.22621.1105]
        • Chrome (web)                 • chrome        • web-javascript • Google Chrome 109.0.5414.120
        • Edge (web)                   • edge          • web-javascript • Microsoft Edge 109.0.1518.61
    
    [√] HTTP Host Availability
        • All required HTTP hosts are available
    
    • No issues found!
  
</details>

**Comment by huycozy** [comment]
@TreyThomas93 Thanks for the update. 

My colleague (@exaby73) also can not reproduce the exception on his device (Samsung S9+ (Android 10)). 


Even though the exception does not occur, I can see this is similar to the case that is described at https://github.com/flutter/flutter/issues/117167#issuecomment-1407247309. Labeling the issue for further insights.


| Samsung S9+ (Android 10) | Samsung Galaxy Tab A7 Lite, Android 13 |
| --------------- | --------------- |
<img width="400" src="https://user-images.githubusercontent.com/104349824/217199373-d9a59d37-c3b2-4bb5-a4da-520ce731f925.jpg"> | <img width="400" src="https://user-images.githubusercontent.com/104349824/217200203-5c5f21c8-e5ca-46ad-b21d-91bc911b4c20.png">


<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.7.1, on macOS 13.0.1 22A400 darwin-x64, locale en-VN)
    • Flutter version 3.7.1 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7048ed95a5 (11 hours ago), 2023-02-01 09:07:31 -0800
    • Engine revision 800594f1f4
    • Dart version 2.19.1
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio Dolphin 2021.3.1.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio Dolphin 2021.3.1.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[!] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.74.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.58.0

[✓] Connected device (4 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D                         • android-arm64  • Android 11 (API 30)
    • iPhone (mobile)  • d9a94afe2b649fef56ba0bfeb052f0f2a7dae95e • ios            • iOS 15.7.2 19H218
    • macOS (desktop)  • macos                                    • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)     • chrome                                   • web-javascript • Google Chrome 109.0.5414.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```

```bash
[!] Flutter (Channel master, 3.8.0-5.0.pre.10, on macOS 13.0.1 22A400 darwin-x64, locale en-VN)
    • Flutter version 3.8.0-5.0.pre.10 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e62abfae62 (46 minutes ago), 2023-02-06 17:52:30 -0800
    • Engine revision 2a104cdfcd
    • Dart version 3.0.0 (build 3.0.0-204.0.dev)
    • DevTools version 2.21.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Users/huynq/Library/Java/JavaVirtualMachines/corretto-1.8.0_302/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment Corretto-8.302.08.1 (build 1.8.0_302-b08)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.75.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.58.0

[✓] Connected device (3 available)
    • SM T225 (mobile) • R9JT3004VRJ • android-arm64  • Android 13 (API 33)
    • macOS (desktop)  • macos       • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)     • chrome      • web-javascript • Google Chrome 109.0.5414.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.
```
</details>

/cc @camsim99 for thoughts (as you are working on #117167)

**Comment by camsim99** [comment]
@TreyThomas93 thank you for reporting this! I see two issues: (1) we intentionally did not initially support the Samsung spell checker, but we should work now to include it and (2) we should prefer failing silently when a spell checker/platform is not supported to avoid hitting the assertion error.

Filed https://github.com/flutter/flutter/issues/120608 to support the Samsung spell checker and https://github.com/flutter/flutter/issues/120611 to better handle the assertion error in cases where the spell checker/platform is supported. Feel free to follow up there with any further thoughts or reports!

**Comment by exaby73** [comment]
As per https://github.com/flutter/flutter/issues/119868#issuecomment-1428391700, this issue has been split between two issues. I'll mark this as a duplicate of those issues. Thanks @camsim99 for the insights :)

**Comment by TreyThomas93** [comment]
Thanks @camsim99 for the help
