### ISSUE TITLE
TextFormField Bug

### ISSUE THREAD

**Issue by AndroidDesigner** [flutter/flutter#119828]
Hello.
I'm using a simple ``TextFormField`` in a Linux Flutter application.
But I dont know why **new letters are added to the left side**!
for example, I type ``abcd``, while ``dcba`` is shown in the TextFormField!

sample code:
```
//a simple statefulwidget:
TextEditingController userController = TextEditingController();

 @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Container(
        alignment: Alignment.center,
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            TextFormField(
              //textDirection: TextDirection.ltr,
              //textAlign: TextAlign.start,
              controller: userController,
              style: const TextStyle(color: Colors.black),
              decoration: const InputDecoration(
                hintText: "username",
                focusColor: Colors.white,
              ),
              onChanged: (text) {
                debugPrint("text---------->$text");
                setState(() {
                  userController.text = text;
                });
              },
            ),
          ],
        ),
      ),
    );
  }
```
what is problem?

**Comment by znromonk** [comment]
You do not need to use `setState`.  You can verify the `TextController` has the values by trying the following in your `onChanged` function. 
```dart
debugPrint("text---------->${userController.text}");
```

**Comment by darshankawar** [comment]
@AndroidDesigner 
Try above solution and see if it works in your case. If not, please provide `flutter doctor -v` and platform on which you are seeing this behavior.

**Comment by ExpertKiD** [comment]
@AndroidDesigner Using TextController and setState() are not recommended. You should consider using textController only for getting data from the form field. Furthermore, `textController` automatically tracks the changes in `FormField` so you do not need to set it manually. 

Solution:

1. Remove `setState()` call to set the `textController`.
