### ISSUE TITLE
Can we use both front and back camera simultaneously?

### ISSUE THREAD

**Issue by akashmishra242** [flutter/flutter#119858]
Is it possible to use both front and back camera simultaneously as several mobiles have this feature.

I tried this using two camera controller but as soon as 2nd camera controller gets initialized the 1st one gets disposed.
```
final List<CameraDescription> cameras = await availableCameras();
var frontCamera = cameras[0];
var backCamera = cameras[1];

final CameraController frontCameraController = CameraController(
      frontCamera,
      ResolutionPreset.medium,
      enableAudio: enableAudio,
      imageFormatGroup: ImageFormatGroup.jpeg,
    );

final CameraController backCameraController = CameraController(
      backCamera,
      ResolutionPreset.medium,
      enableAudio: enableAudio,
      imageFormatGroup: ImageFormatGroup.jpeg,
    );


return Column(
    children: [
        // Front camera is shown correctly
        CameraPreview(frontCameraController),

        // Back camera image is blank
        CameraPreview(backCameraController),
    ],
);
```

Please help me with this. 

Thank you.

**Comment by danagbemava-nc** [comment]
Hi @akashmishra242, this is currently not possible but there's an existing issue tracking the implementation of this feature in https://github.com/flutter/flutter/issues/51928.

Kindly subscribe to the original issue for updates. 

Closing from here as duplicate. 

Thank you
