### ISSUE TITLE
Add API for adding image decoders

### ISSUE THREAD

**Issue by PeterHatch** [flutter/flutter#119845]
## Use case

So I'd like JPEG XL support, and I'm looking into doing it as a plugin.  Right now it's possible, but only in a way that seems unnecessarily complicated, and significantly less convenient for any developer using the plugin.

Specifically, while Flutter has it where an Image can use any ImageProvider, and an ImageProvider can use any image decoder, there's not actually a way to add decoders.  So packages like flutter_avif end up with AvifImage that duplicates almost all the functionality of Image but uses AvifImageProviders, which likewise duplicate almost all of the functionality of their respective ImageProvider except using an AVIF decoder instead of having the engine pick one.  So more code to write and maintain, and any user of the library has to specify every time whether they want an AvifImage or a standard Image.

## Proposal

It'd like to see a way to add a new image decoder from a plugin.  This was apparently considered back when improving the way the engine handles decoders - https://github.com/flutter/engine/pull/25987 has a link to the design doc http://flutter.dev/go/image-decoding-registry, which includes (crossed out) "Maybe: Expose Dart bindings for registering new image decoders to enable image decoders to be shipped as plugins."

**Comment by darshankawar** [comment]
Thanks for the report @PeterHatch 
Can you check [this](https://github.com/flutter/flutter/issues/95285) link and see if it helps in your case ?
