### ISSUE TITLE
[CP] Fix lexer issue where select/plural/other/underscores cannot be in identifier names

### ISSUE THREAD

**Issue by thkim1011** [flutter/flutter#119863]
### issue_link

https://github.com/flutter/flutter/pull/119190

### Commit Hash

02a9c15

### Target

stable

### pr_link

https://github.com/flutter/flutter/pull/119862

### Impacted Users

Users who use the flutter i18n tools.

### Impact Description

Currently developers cannot have keywords in the names of their placeholders in *.arb files (for internationalized strings) which breaks a lot of existing user's Flutter apps.

### Workaround

Only workaround is to rename placeholders so that they don't have "select", "other", "plural", or underscores in their names.

### Risk

low

### Test Coverage

yes

### Validation Steps

Create a simple i18n app following https://docs.flutter.dev/development/accessibility-and-localization/internationalization where the placeholder contains an underscore.

**Comment by christopherfujino** [comment]
CP LGTM

**Comment by itsjustkevin** [comment]
Friendly bump @thkim1011

**Comment by godofredoc** [comment]
Moving back to review until we get an answer from @thkim1011

**Comment by christopherfujino** [comment]
I can approve this per internal discussion

**Comment by itsjustkevin** [comment]
Keeping the `cp: review` label as it is used for tracking incoming requests.
