### ISSUE TITLE
accessibility frame disappears when scrolling with two fingers

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#11982]
It is caused by `RenderIgnorePointer` which is placed between the Scrollable and its content. As soon as scrolling starts, it is instructed to ignore all pointer events, which causes `RenderIgnorePointer` to also drop all of its children semantics on the floor. Hence, the node that was accessibility focused before scrolling started is removed from the semantics tree and can no longer be focused.

https://github.com/flutter/flutter/blob/cb4a54db8fb3726bf4293b9cc5cb12ce16883803/packages/flutter/lib/src/rendering/proxy_box.dart#L775

**Comment by Hixie** [comment]
That IgnorePointer just needs to have ignoringSemantics set to false, I guess. :-)
