### ISSUE TITLE
Keyboard popping issue in flutter windows(tablet mode or touch mode)

### ISSUE THREAD

**Issue by sidhiqbakku** [flutter/flutter#119807]
Hi I'm trying to build an application for kiosk machine in windows 10. But a problem or issue is there I can't able to fix. Keyboard pops up abnormally , when ever I touches in the screen. I have tried many ways from flutter documentation to stackoverflow answers but still the issue remains.

These is the  piece of codes I tried to close keyboard manually 

I have tried wrapping the widgets and scaffold with a gesterdetector and unfocus the the focus on both  'ontap' and 'onapdown' methods.But the abnormality happening in here is the keyboard closses on mouse click but the key board pops on touch.

    
      FocusScopeNode currentFocus = FocusScope.of(context);
      if (!currentFocus.hasPrimaryFocus &&
          currentFocus.focusedChild != null) {
        FocusManager.instance.primaryFocus!.unfocus();
      
    }

**Comment by sabin26** [comment]
Did you try using GestureDetector within the builder method of MaterialApp ? If not, give it a try.

```
return MaterialApp.router(
      ...
      builder: (final BuildContext context, Widget? widget) {
        if (kioskMachine) {
          widget = GestureDetector(
            onTap: () => FocusManager.instance.primaryFocus?.unfocus(),
            child: widget,
          );
        }

        return widget ?? SizedBox.shrink();
      },
    );
```

**Comment by exaby73** [comment]
Hello @sidhiqbakku. Could you provide some details of the device you're working on? Is the host device and the target device the same? If so, the output of `flutter doctor -v` is enough

**Comment by sidhiqbakku** [comment]
> Did you try using GestureDetector within the builder of MaterialApp ? If not, give it a try.
> 
> ```
> return MaterialApp.router(
>       ...
>       builder: (final BuildContext context, Widget? widget) {
>         if (kioskMachine) {
>           widget = GestureDetector(
>             onTap: () => FocusManager.instance.primaryFocus?.unfocus(),
>             child: widget,
>           );
>         }
> 
>         return widget ?? SizedBox.shrink();
>       },
>     );
> ```

**Comment by sidhiqbakku** [comment]
flutter doctor -v
[√] Flutter (Channel stable, 3.0.1, on Microsoft Windows [Version 10.0.19044.2486], locale en-IN)
    • Flutter version 3.0.1 at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (9 months ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at D:\Software\Sdk
    • Platform android-33, build-tools 32.0.0
    • ANDROID_SDK_ROOT = D:\Software\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio1\jre\bin\java      
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.4.3)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.4.33205.214
    • Windows 10 SDK version 10.0.22000.0

[!] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    X Unable to determine bundled Java version.
    • Try updating or re-installing Android Studio.

[√] Android Studio (version 2021.3)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[√] VS Code (version 1.74.2)
    • VS Code at C:\Users\dell\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.56.0

[√] Connected device (4 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)       • windows       • windows-x64    • Microsoft Windows [Version 10.0.19044.2486]
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 109.0.5414.75
    • Edge (web)              • edge          • web-javascript • Microsoft Edge 109.0.1518.69

[√] HTTP Host Availability
    • All required HTTP hosts are available

@exaby73  this is the flutter doctor -v  outpu of the  host device

**Comment by sidhiqbakku** [comment]
@sabin26 I have tried this . No improvements

**Comment by exaby73** [comment]
@sidhiqbakku You are using an old version of Flutter. Please upgrade to the latest stable `3.7.1` and confirm if this is still an issue

**Comment by sidhiqbakku** [comment]
let me try this @exaby73

**Comment by sidhiqbakku** [comment]
Still the issue stays even after upadating to 3.7 @exaby73

**Comment by exaby73** [comment]
Since I do not have a touch screen, is it possible for you to take a video or screen recording of the issue?
