### ISSUE TITLE
findSystemLocale returns wrong locale on Windows 11

### ISSUE THREAD

**Issue by DmitrySikorsky** [flutter/flutter#119811]
## Steps to Reproduce

1. Prepare environment:

Flutter 3.7.0, Dart 2.19.0, DevTools 2.20.1, **intl 0.17.0**.

Windows 11, Ukrainian is set as UI language. Ukraine is set as the country. Language list contains 2 languages: English and Ukrainian. English is the first one.

![image](https://user-images.githubusercontent.com/6570196/216319093-79674463-463f-4001-8d4d-23f56925f23a.png)

![image](https://user-images.githubusercontent.com/6570196/216319280-84b79019-46ac-4838-9b79-2cb7bc7dcde9.png)

2. Run code:

```
Future main() async {
  String locale = await findSystemLocale();

  // locale contains 'en_US', but should contain 'uk_UA'

  runApp(MyApp());
}
```

3. Move Ukrainian language to be the first, so English will be the second, run the app again. In this case locale will be correct (uk_UA). But I believe that it is not the expected behavior. Usually English is set as the first language because sometimes it is usable to have the English keyboard as default on the opened apps, it shouldn't be considered as system locale.

It seems that it was changed some time ago, because few months ago it was working as expected for sure.

**Comment by exaby73** [comment]
Hey @DmitrySikorsky. Can you provide a full code example that can be run directly?

**Comment by DmitrySikorsky** [comment]
Yes, sure.

1. Run flutter create test
2. Replace main.dart with this one:

```
import 'package:flutter/material.dart';
import 'package:intl/intl_standalone.dart';

Future main() async {
  String locale = await findSystemLocale();

  runApp(MyApp(locale));
}

class MyApp extends StatelessWidget {
  final String locale;

  const MyApp(this.locale, {super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Incorrect locale on Windows 11',
      home: MyHomePage(locale),
    );
  }
}

class MyHomePage extends StatefulWidget {
  final String locale;

  const MyHomePage(this.locale, {super.key});

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Incorrect locale on Windows 11'),
      ),
      body: Center(
        child: Text('Locale: ${widget.locale}'),
      ),
    );
  }
}
```

3. Add intl: ^0.17.0 package.
4. Run the app on Windows.

**Actual result:** the first (top) language from the language list is returned as locale. (See the first post for the details and screenshots.)

**Expected result:** OS UI language OR OS country is returned as locale. Why: that would be strange if the OS interface has Ukrainian language selected, but when I run the app it has English UI despite it supports Ukrainian. I don't expect to get the first language user uses in his work, I expect the one that is selected as UI language.

**Comment by exaby73** [comment]
I think this issue is better raised on `intl`s repository (https://github.com/dart-lang/intl) since this function is defined there. Closing this issue as it doesn't seem to be related to Flutter  itself
