### ISSUE TITLE
Unable to build app after adding dependencies like firebase analytics

### ISSUE THREAD

**Issue by Vipul20032002** [flutter/flutter#119812]
This is the displayed error:-

Launching lib\main.dart on RMX1931 in debug mode...
Running Gradle task 'assembleDebug'...
[Fatal Error] txw2-2.2.11.pom:2:1: Content is not allowed in prolog.
[Fatal Error] istack-commons-runtime-2.21.pom:2:1: Content is not allowed in prolog.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':firebase_analytics'.
> Could not resolve all files for configuration ':firebase_analytics:classpath'.
   > Could not resolve javax.xml.bind:jaxb-api:2.2.12-b140109.1041.
     Required by:
         project :firebase_analytics > com.android.tools.build:gradle:3.5.4 > com.android.tools.build:builder:3.5.4 > com.android.tools:sdklib:26.5.4 > com.android.tools:repository:26.5.4 > org.glassfish.jaxb:jaxb-runtime:2.2.11 > org.glassfish.jaxb:jaxb-core:2.2.11
      > Could not resolve javax.xml.bind:jaxb-api:2.2.12-b140109.1041.
         > Could not parse POM https://repo.maven.apache.org/maven2/javax/xml/bind/jaxb-api/2.2.12-b140109.1041/jaxb-api-2.2.12-b140109.1041.pom
            > Resetting to invalid mark
   > Could not resolve org.glassfish.jaxb:txw2:2.2.11.
     Required by:
         project :firebase_analytics > com.android.tools.build:gradle:3.5.4 > com.android.tools.build:builder:3.5.4 > com.android.tools:sdklib:26.5.4 > com.android.tools:repository:26.5.4 > org.glassfish.jaxb:jaxb-runtime:2.2.11 > org.glassfish.jaxb:jaxb-core:2.2.11
      > Could not resolve org.glassfish.jaxb:txw2:2.2.11.
         > Could not parse POM https://repo.maven.apache.org/maven2/org/glassfish/jaxb/txw2/2.2.11/txw2-2.2.11.pom
            > Content is not allowed in prolog.
   > Could not resolve com.sun.istack:istack-commons-runtime:2.21.
     Required by:
         project :firebase_analytics > com.android.tools.build:gradle:3.5.4 > com.android.tools.build:builder:3.5.4 > com.android.tools:sdklib:26.5.4 > com.android.tools:repository:26.5.4 > org.glassfish.jaxb:jaxb-runtime:2.2.11 > org.glassfish.jaxb:jaxb-core:2.2.11
      > Could not resolve com.sun.istack:istack-commons-runtime:2.21.
         > Could not parse POM https://repo.maven.apache.org/maven2/com/sun/istack/istack-commons-runtime/2.21/istack-commons-runtime-2.21.pom
            > Content is not allowed in prolog.
> Failed to notify project evaluation listener.
   > Could not get unknown property 'android' for project ':firebase_analytics' of type org.gradle.api.Project.
   > Could not find method implementation() for arguments [project ':firebase_core'] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
   > Could not get unknown property 'android' for project ':firebase_analytics' of type org.gradle.api.Project.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 27s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by callmephil** [comment]
Have you tried re-running the firebase configuration?

I'd suggest doing:
```
flutter clean
flutter pub upgrade
flutterfire config 
```

Also, ensure that there are no issues with your flutter installation **flutter doctor -v**

If none of the above worked, try to update the gradle version in your android folder.

android/build.gradle
```
    ext.kotlin_version = '1.7.10'
    classpath 'com.android.tools.build:gradle:7.2.0'
```

android/gradle-wrapper.properties
```
distributionUrl=https\://services.gradle.org/distributions/gradle-7.5-all.zip
```

The above versions are provided by a fresh flutter project created with 3.7.1.

**Comment by Vipul20032002** [comment]
1) I tried executing the above steps but the problem still persists.
2) Also no issues were found after running flutter doctor -v

**Comment by exaby73** [comment]
Hello @Vipul20032002. Looks like this issue may be better suited to raised on https://github.com/firebase/flutterfire. Therefore, I am closing this issue. If you disagree with my decision, please comment and I can reopen the issue. Thank you
