### ISSUE TITLE
[google_maps_flutter] Not working on android in case cleartextTrafficPermitted set true

### ISSUE THREAD

**Issue by elham-rababah** [flutter/flutter#119804]
How to produce

add cleartextTrafficPermitted to AndroidManifest.xml as you can see 

<img width="502" alt="image" src="https://user-images.githubusercontent.com/19626536/216294093-dbe2d325-069f-460b-8b79-289398df0603.png">

Add you map key between application and activity 
 <meta-data android:name="com.google.android.geo.API_KEY"
            android:value="XXXX"/>

user the same example on documentation

<img width="684" alt="image" src="https://user-images.githubusercontent.com/19626536/216293181-78e72f90-e5f5-4a94-8794-7c77eed4413e.png">

class MapSample extends StatefulWidget {
  const MapSample({Key? key}) : super(key: key);

  @override
  State<MapSample> createState() => MapSampleState();
}

class MapSampleState extends State<MapSample> {
  final Completer<GoogleMapController> _controller =
  Completer<GoogleMapController>();

  static const CameraPosition _kGooglePlex = CameraPosition(
    target: LatLng(37.42796133580664, -122.085749655962),
    zoom: 14.4746,
  );

  static const CameraPosition _kLake = CameraPosition(
      bearing: 192.8334901395799,
      target: LatLng(37.43296265331129, -122.08832357078792),
      tilt: 59.440717697143555,
      zoom: 19.151926040649414);

  @override
  Widget build(BuildContext context) {
    return Container(
      height: MediaQuery.of(context).size.height* .4,
      width: MediaQuery.of(context).size.width ,
      child: GoogleMap(
        mapType: MapType.hybrid,
        initialCameraPosition: _kGooglePlex,
        onMapCreated: (GoogleMapController controller) {
          _controller.complete(controller);
        },
      ),
      // floatingActionButton: FloatingActionButton.extended(
      //   onPressed: _goToTheLake,
      //   label: const Text('To the lake!'),
      //   icon: const Icon(Icons.directions_boat),
      // ),
    );
  }

  Future<void> _goToTheLake() async {
    final GoogleMapController controller = await _controller.future;
    controller.animateCamera(CameraUpdate.newCameraPosition(_kLake));
  }
the result will be 

<img width="293" alt="image" src="https://user-images.githubusercontent.com/19626536/216293721-c72621d7-31de-4a85-a77f-751215f7e129.png">

**Comment by huycozy** [comment]
@elham-rababah 
Can you try running [google_maps sample code](https://github.com/flutter/plugins/tree/main/packages/google_maps_flutter/google_maps_flutter/example) and check if the issue still persists?

Also, which `google_maps_flutter` plugin versions are you using? And please provide the output of `flutter doctor -v` as well. Thank you!
