### ISSUE TITLE
flutter-devicelab-linux-11 dead 2 hr ago.

### ISSUE THREAD

**Issue by kentnguyen99** [flutter/flutter#119850]
flutter-devicelab-linux-11 masked as dead 2 hrs ago.

![Screenshot 2023-02-02 11 35 56 AM](https://user-images.githubusercontent.com/120754754/216432957-8125f014-59bf-4b0c-9028-66b11a15a223.png)

**Comment by kentnguyen99** [comment]
Internal hardware failure on devicelab-linux-11 and it wouldn't boot again, machine requires to replace new hardware and reinstall OS.

**Comment by yusuf-goog** [comment]
Is this the SSD corruption issue on the host machine?

**Comment by kentnguyen99** [comment]
Yes, the internal SSD hard drive corrupted and wouldn't boot again when the power recycle machine.

**Comment by yusuf-goog** [comment]
Created ticket to update linux-11 mac address for DNS entry: t/217220645

**Comment by kentnguyen99** [comment]
Machine linux-11 is up and ready for service after moving to the new Salt Master, everything is working fine now. Work completed.
