### ISSUE TITLE
pakage version defrence in pubspec.lock and pubspec.yaml and package_config.json

### ISSUE THREAD

**Issue by manarbajafar** [flutter/flutter#119913]
I downloaded the code from flutter_notification_listener package github and it worked well even in the background .. Package version 1.0.7

But when I do the same in my project, it doesn't work in the background
And when I looked for the difference..

I found that in two places in the project another version of the package was written, I did not understand why
And when I change it to 1.0.7 the change is not saved even when i clean and pub get the project

![Screenshot (883)](https://user-images.githubusercontent.com/60103703/216595281-4f713da6-49fe-4a57-9228-dd82d936a579.png)

![Screenshot (884)](https://user-images.githubusercontent.com/60103703/216595303-d5d36b77-9c93-46de-a645-e211a8822e20.png)

![Screenshot (885)](https://user-images.githubusercontent.com/60103703/216595324-c652d33c-2557-47b9-a03e-e600e5d45fb5.png)

**Comment by darshankawar** [comment]
@manarbajafar 
Please check this similar issue which has been fixed recently https://github.com/flutter/flutter/issues/119091 and probably you are hitting same scenario. I am not sure which flutter version you are on, but try upgrading to latest master or stable and run your scenario again to see if it works or not.

**Comment by stuartmorgan** [comment]
> And when I change it to 1.0.7

You haven't changed it to 1.0.7, you've changed it to `^1.0.7` which is a range as described in https://dart.dev/tools/pub/dependencies#caret-syntax

1.3.2 is in the range you've requested in your pubspec.yaml so this is expected behavior.
