### ISSUE TITLE
Respect Android and iOS "Use 24-hour format" setting

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#11994]
By default, the time of day picker uses 12- or 24-hour format based on the locale. However, there is a setting "Use 24-hour format" that forces 24-hour format no matter what locale is chosen. Flutter's `showTimePicker` should respect this option.

## Android

https://developer.android.com/reference/android/text/format/DateFormat.html#is24HourFormat(android.content.Context)

## iOS

AFAICT there's no way to get it directly. One possibility is to have the [NSDateFormatter](https://developer.apple.com/documentation/foundation/nsdateformatter) format a sample time for a locale known to use 12-hour format. If the result is 24-hour format, then the "24-hour" setting must be enabled. Otherwise, it's not.

/cc @cbracken

**Comment by cbracken** [comment]
Correct - iOS doesn't provide a straightforward means of getting at this setting (as far as I'm aware).

**Comment by eseidelGoogle** [comment]
Not sure if this helps: http://www.cocoabuilder.com/archive/cocoa/148316-24-hour-default.html

**Comment by yjbanov** [comment]
@eseidelGoogle It does reiterate that `NSDateFormatter` might be the way to go, but also that thread is from 2005, and is about macos, not ios.

**Comment by konstantintuev** [comment]
If anyone is still interested, I made a plug-in for this: [respect_24_hour](https://pub.dartlang.org/packages/respect_24_hour)
