### ISSUE TITLE
`Linux ci_yaml flutter roller` failing: "Error: key "dependencies" not in dict"

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#119973]
I tried to create two new builders (one renamed, one actually new) in https://github.com/flutter/flutter/pull/119971 and `Linux ci_yaml flutter roller` failed with:
```
[P7999 15:34:54.716 generate.go:94 I] Generating configs using lucicfg v1.37.2...
Traceback (most recent call last):
  //main.star:249:21: in <toplevel>
  //flutter_config.star:59:21: in _setup
  //lib/ci_yaml/ci_yaml.star:471:14: in _generate
  //lib/ci_yaml/ci_yaml.star:371:40: in _builders
  //lib/ci_yaml/ci_yaml.star:227:34: in _properties
Error: key "dependencies" not in dict
```
https://ci.chromium.org/p/flutter/builders/try/Linux%20ci_yaml%20flutter%20roller/2023

I'm not quite sure why, I don't think `dependencies` _should_ be required if there are none, but in this case both tasks do have a `dependencies` key.

```yml
  - name: Mac_x64 verify_binaries_codesigned
...
    properties:
      dependencies: >-
        [
          {"dependency": "xcode", "version": "14a5294e"}
        ]

  - name: Mac_arm verify_binaries_codesigned
...
    properties:
      dependencies: >-
        [
          {"dependency": "xcode", "version": "14a5294e"}
        ]
```

This is blocking https://github.com/flutter/flutter/pull/119971.

**Comment by jmagman** [comment]
Putting this in the infra queue since I'd really like https://github.com/flutter/flutter/pull/119971 to land before next week's release.

**Comment by jmagman** [comment]
Oh actually I know what happened, I misspelled the `platform_property` `Mac_arm64` as `Mac_arm`, so it didn't "inherit" correctly.  I don't think `dependencies` should be required, and maybe this can be a better error message?  

In any case this is a nice-to-have, removing from the queue.

**Comment by christopherfujino** [comment]
The "fix" to make `dependencies` optional would be upstream in lucicfg, no?

**Comment by jmagman** [comment]
I was thinking more of handling the key not being present and assuming it's empty here:
https://flutter.googlesource.com/infra/+/refs/heads/main/config/lib/ci_yaml/ci_yaml.star#227

**Comment by yusuf-goog** [comment]
@jmagman do you have a fix/workaround for the original issue, or do you need someone to look at this?

**Comment by jmagman** [comment]
This isn't blocking anything, I can file a new, more focused version of this issue if I see it again.
