### ISSUE TITLE
[CP] [Impeller] ensure 1x1 has mipcount of 1

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#119947]
### issue_link

https://github.com/flutter/flutter/issues/119245

### Commit Hash

https://github.com/flutter/engine/commit/6a92731d2edcb72dca0dc161de1da1e20a8210d8

### Target

stable

### pr_link

https://github.com/flutter/engine/pull/39365

### Impacted Users

Impeller users

### Impact Description

The mip count for a 1x1 texture would be 0, resulting in a crash in the Impeller backend.

### Workaround

There is no workaround

### Risk

low

### Test Coverage

yes

### Validation Steps

Verify that `kTransparentImage` from `package:transparent_image` works as expected under Impeller.

**Comment by zanderso** [comment]
cc @jonahwilliams @chinmaygarde

**Comment by jonahwilliams** [comment]
LGTM

**Comment by chinmaygarde** [comment]
LGTM
