### ISSUE TITLE
[go_router] Should the `refreshListenable` property be used?

### ISSUE THREAD

**Issue by bambinoua** [flutter/flutter#119929]
I understand the functionality of `refreshListenable` but should I use it or will it be deprecated in the future (as I read somewhere)?

**Comment by huycozy** [comment]
Hi @bambinoua
I'm closing this issue in favor of #116651 as your question is mentioned at https://github.com/flutter/flutter/issues/116651#issuecomment-1361282352. Please follow up on that issue for further updates or react an upvote to the original comment will help to raise the issue. Thanks!
