### ISSUE TITLE
a11y: disabled elements should expose their disabled state

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#11993]
E.g. a button that is currently no clickable should say this in the VoiceOver/TalkBack announcement.

**Comment by yjbanov** [comment]
Resources:

- https://developer.apple.com/documentation/uikit/uiaccessibilitytraitnotenabled?language=objc

**Comment by goderbauer** [comment]
Related: https://github.com/flutter/flutter/issues/11991
