### ISSUE TITLE
Documentation on `SelectableText` should mention `SelectionArea` 

### ISSUE THREAD

**Issue by nilsreichardt** [flutter/flutter#119911]
<img width="910" alt="image" src="https://user-images.githubusercontent.com/24459435/216579428-9d61d82a-0a0e-4db0-aab4-406a11124d92.png">

When you google "flutter text selection" the first result is the documentation of the `SelectableText`. When you are new to Flutter, you think that this is the way to make a text selectable. However, since a few months there is also a way to make multiple text widgets selectable (`SelectionArea`, see #95226). The documentation of `SelectableText` doesn't mention in any line of the existence of the `SelectionArea` widget, see https://api.flutter.dev/flutter/material/SelectableText-class.html)

I think it would be a good idea to also mention `SelectionArea`, when you want to add a selection for more than only one text widget. Therefore, new Flutter might explore this widget and are going to read documentation of this widget.

**Comment by nilsreichardt** [comment]
If this is something that make sense, then I can make a PR 👍

**Comment by goderbauer** [comment]
cc @chunhtai

**Comment by justinmc** [comment]
I missed this issue but I think you are so right, we should definitely be cross referencing these. PR: https://github.com/flutter/flutter/pull/143784
