### ISSUE TITLE
[CP] [Impeller] Use minimal coverage for stencil restores after overdraw prevention

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#119953]
### issue_link

https://github.com/flutter/flutter/issues/119881

### Commit Hash

https://github.com/flutter/engine/commit/67d35267c37c13495942876b985d7a8e09b0db15

### Target

stable

### pr_link

https://github.com/flutter/engine/pull/39370

### Impacted Users

Impeller users

### Impact Description

Emulated dashed lines hit a performance cliff due to stencil checks of the whole screen when only a small region was necessary.

### Workaround

There is no workaround.

### Risk

low

### Test Coverage

yes

### Validation Steps

In example in the issue, verify that Impeller performance is comparable with Skia.

**Comment by zanderso** [comment]
cc @jonahwilliams @bdero @chinmaygarde

**Comment by jonahwilliams** [comment]
LGTM

**Comment by bdero** [comment]
LGTM
