### ISSUE TITLE
Embedding API does not support string attributes.

### ISSUE THREAD

**Issue by chunhtai** [flutter/flutter#119970]
The https://api.flutter.dev/flutter/dart-ui/StringAttribute-class.html is useful to attach certain attribute to a string for accessibility focus. This information is not sent as part of embedder API https://github.com/flutter/engine/blob/18750d2452519ebe006f935d4d054f15a4949890/shell/platform/embedder/embedder.h#L1115

We should add support for this

**Comment by chunhtai** [comment]
It seems like native macOS API does not support any of [StringAttribute](https://api.flutter.dev/flutter/dart-ui/StringAttribute-class.html).

@loic-sharma Do you know whether they can be useful for Windows?

**Comment by loic-sharma** [comment]
Sorry, I don't know. @yaakovschectman would you know?

**Comment by yaakovschectman** [comment]
Whether additional arbitrary string attributes would be useful for Windows? I'm not aware by memory of any use that would apply to us.

**Comment by loic-sharma** [comment]
Implemented by https://github.com/flutter/engine/pull/44616
