### ISSUE TITLE
Flutter error on MacOS Desktop after 3.7.0 upgrade. Could not acquire Metal device.

### ISSUE THREAD

**Issue by JacoFourie** [flutter/flutter#119994]
Hi all.

I get this error on MacOS Desktop after the upgrade to flutter 3.7.0. On 3.3.10 it all works fine.
I just created a starter app and this is the error

```
jaco@Jacos-Mac desktoptest % flutter run
Multiple devices found:
macOS (desktop) • macos  • darwin-x64     • macOS 12.0 21A5248p darwin-x64
Chrome (web)    • chrome • web-javascript • Google Chrome 104.0.5112.79
[1]: macOS (macos)
[2]: Chrome (chrome)
Please choose one (To quit, press "q/Q"): 1
Launching lib/main.dart on macOS in debug mode...
Building macOS application...                                           
MBDisplay: creating data for display 0x5B81C5C0 (main) with bounds o=[0.000000, 0.000000], s=[1718.000000, 1088.000000]
2023-02-04 03:41:34.739 desktoptest[49913:822123] Could not acquire Metal device.
2023-02-04 03:41:34.748 desktoptest[49913:822123] Unable to create FlutterView; no MTLDevice or MTLCommandQueue available.
```

```
jaco@Jacos-Mac desktoptest % flutter doctor -v
[✓] Flutter (Channel stable, 3.7.1, on macOS 12.0 21A5248p darwin-x64, locale en-ZA)
    • Flutter version 3.7.1 on channel stable at /Users/jaco/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7048ed95a5 (3 days ago), 2023-02-01 09:07:31 -0800
    • Engine revision 800594f1f4
    • Dart version 2.19.1
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/jaco/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F100
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.0 21A5248p darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 104.0.5112.79

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

**Comment by JacoFourie** [comment]
Mmm so it seems they have removed OpenGL from Flutter. Now all MacOS running in a VM wont work. That was not clever.

**Comment by malisoft** [comment]
> Unable to create FlutterView; no MTLDevice or MTLCommandQueue availabl

but, we dont't have our MacOs running in a VirtualMachine, pff, i hate this breaking changes

**Comment by darshankawar** [comment]
Thanks for the report @JacoFourie 


> I just created a starter app and this is the error

I tried the same by creating starter app in 3.3.10 and then upgraded to 3.7.1 which worked properly and didn't get the error as you reported.

```
Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

💪 Running with sound null safety 💪

An Observatory debugger and profiler on macOS is available at:
http://127.0.0.1:51496/cyGlTVClAVo=/
The Flutter DevTools debugger and profiler on macOS is available at:
http://127.0.0.1:9101?uri=http://127.0.0.1:51496/cyGlTVClAVo=/


```



> Now all MacOS running in a VM wont work.

Is this only occuring running the macOS in a VM ?



> so it seems they have removed OpenGL from Flutter

According to the 3.7.0 release notes:

```
This means that apps built against stable Flutter SDKs with this release and onward will no longer work on these versions, and the minimum macOS version supported by Flutter increases to 10.14 Mojave.

As a consequence, since all versions of iOS and macOS supported by Flutter include Metal support, the OpenGL backend has been removed from both the iOS and macOS embedders.
```

**Comment by JacoFourie** [comment]
@darshankawar I only have MacOS running in a VM. I do not have access to Mac hardware so have to develop in windows and the start a VM and compile the code and run / test it in the VM. 3.3.10 works 100% inside the VM but 3.7.0 does not as it is looking for hardware that is not part of the VM. Here I can see that the OpenGL support was removed from flutter 3.7.0 https://github.com/flutter/flutter/issues/108304

**Comment by darshankawar** [comment]
Thanks for the update. I don't have the required setup to run macOS in a VM, so I am unable to verify this behavior. 
Based on the report, keeping this issue open and labeling for team's attention.

/cc @cbracken

**Comment by JacoFourie** [comment]
@darshankawar thank you. I can understand that at some point MacOS will no longer run in a VM as you need Apple hardware but to just drop OpenGL  from Flutter like this is dropping the developers who do not have the hardware yet.  We would like to plan and then buy hardware etc to compile the code. As it is now we are dead in the water after version 3.3.10.

**Comment by cbracken** [comment]
Hi @JacoFourie the removal was intentional and proposed in https://github.com/flutter/flutter/issues/114445, which was run through our standard RFC process with this RFC, which provides the background information on the removal: https://docs.google.com/document/d/1wHqr2cob78VfUKhOFEKjaUM_mnV4gL-mg3gSQCFhF7Y/edit

Unfortunately, running macOS in a VM on non-macOS hardware isn't a scenario that we intend to support, since the terms of the macOS licence agreement require that macOS only be run on Apple-labelled computers. VMWare maintains a page on [Virtualizing Apple Mac OS X](https://kb.vmware.com/s/article/1000131) which states the same.

For those running VMWare Fusion 12.0 or Parallels Desktop 15 or later on Apple physical hardware, Metal support is built in, and should just work. 

I realise this is not the answer you wanted to hear, but our research shows that less than 4% of the macOS userbase is running Mac hardware that is not Metal-capable, and the only Macs that don't yet support Metal are on Apple's [obsolete products list](https://support.apple.com/en-us/HT201624). Given the large maintenance burden of maintaining OpenGL support, and the complexity it adds to the embedder, we made the choice to drop support for it.

**Comment by gopiKrishnaPuligundla** [comment]
Hi @cbraken I am having a old physical Mac book air of early 2015 , it is running macOS Ventura 13.2.1, I am facing same issue as above

**Comment by gopiKrishnaPuligundla** [comment]
will raise a new issue

**Comment by gopiKrishnaPuligundla** [comment]
bash-3.2$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.3, on macOS 13.2.1 22D68 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

• No issues found!

**Comment by brokercl** [comment]
same issue
