### ISSUE TITLE
[CP] [Impeller] improve blur performance for Android and iPad Pro.

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#119950]
### issue_link

N/A

### Commit Hash

https://github.com/flutter/engine/commit/4b77e779312014af62a445c80aa66d84f4f247ae

### Target

stable

### pr_link

https://github.com/flutter/engine/pull/39367

### Impacted Users

Impeller users

### Impact Description

Impeller blur performance on large screens exposed a performance cliff in the gaussian blur shader that affected the Wonderous app.

### Workaround

There is no workaround.

### Risk

low

### Test Coverage

yes

### Validation Steps

Ensure blur performance in the Wonderous app is improved.

**Comment by bdero** [comment]
LGTM

**Comment by chinmaygarde** [comment]
LGTM
