### ISSUE TITLE
 Windows Version (Unable to confirm if installed Windows version is 10 or greater)

### ISSUE THREAD

**Issue by danielesk** [flutter/flutter#119927]
## Steps to Reproduce

please check logs
1. ...
2. ...
3. ...

## Logs

<details>
<summary>Logs</summary>

```
Version: Windows 11 Professional
Version: 22H2
Operating system version: 22621.1194
```

```
How do I solve the following problems?
```
![image](https://user-images.githubusercontent.com/10652829/216610311-cb680fc4-cc69-43f4-9ed2-96269cff5e17.png)
</details>

**Comment by darshankawar** [comment]
@danielesk 
This has been fixed recently and should be available on latest master : https://github.com/flutter/flutter/issues/117890
Please switch to it to see the fix working.

`flutter channel master`
`flutter upgrade`

Closing as duplicate.
