### ISSUE TITLE
Android app does not open in full screen

### ISSUE THREAD

**Issue by wesleycrispy** [flutter/flutter#119932]
## Steps to Reproduce

Here is andoid emulator that shows a black space at the bottom of the screen while on a real device it happens like above
<img width="474" alt="Screenshot 2023-02-03 at 4 25 44 PM" src="https://user-images.githubusercontent.com/106236544/216642464-20796b49-30a4-4c9c-a02b-e5fea5368916.png">

This is how it shows on my real device.
<img width="388" alt="Screenshot 2023-02-03 at 4 28 24 PM" src="https://user-images.githubusercontent.com/106236544/216642494-186e17e3-2f31-4f92-8c1d-a72882945006.png">

**Expected results:** To see the app in full screen without the black spaces top and bottom

**Actual results:** On android device and/or emulator the app initialises with black spaces and i believe its not related to any kind of widget because it happens right when the splash screen appears.

some more info:
this happens  only on android devices or emulators
on another mac this app opens as it should so its probably some local config that i am unable to find why or what.

<details>
<summary>Code sample</summary>

Its just a basic flutter app, the problem is the layout

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

[✓] Flutter (Channel stable, 3.3.10, on macOS 12.6 21G115 darwin-arm, locale en-AL)
    • Flutter version 3.3.10 on channel stable at /Users/developement/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (7 weeks ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/myname/Library/Android/sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • Java binary at: /Users/myname/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/213.7172.25.2113.9014738/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] Android Studio (version 2021.3)
    • Android Studio at /Users/myname/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/213.7172.25.2113.9014738/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.74.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.58.0

[✓] Connected device (5 available)
    • SM A125F (mobile) • 10.3.1.138:42461                              • android-arm64  • Android 11 (API 30)
    • SM A125F (mobile) • adb-R58R90TYQDV-SpWm8j._adb-tls-connect._tcp. • android-arm64  • Android 11 (API 30)
    • SM G998B (mobile) • adb-R5CR204G38J-SO4XSc._adb-tls-connect._tcp. • android-arm64  • Android 13 (API 33)
    • macOS (desktop)   • macos                                         • darwin-arm64   • macOS 12.6 21G115 darwin-arm
    • Chrome (web)      • chrome                                        • web-javascript • Google Chrome 109.0.5414.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available
</details>

**Comment by huycozy** [comment]
Hi @wesleycrispy 
I tested this on the same emulator (Pixel 4, API 33) but the issue was not happening. 

<details>
<summary>Demo</summary>

<img width="400" src="https://user-images.githubusercontent.com/104349824/216883437-2e57c4ab-3009-4126-8eac-f6c1504523f7.png">
</details>


Does the issue happen with Flutter default project (counter app)? If not so, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this.

**Comment by wesleycrispy** [comment]
@huycozy i can give you a code sample no problem , but i have to note that this happens only on my local machine it is not related to the code. The reason for this is that on another mac the same code opens up fine ( even on ios or ios emulator ) so i believe the problem is not related to the code.
Steps i followed to prove this:
Deleted all the files of code (.dart) and left only the main.dart with runApp and a basic scaffold but the error still persists.

**Comment by huycozy** [comment]
@wesleycrispy The issue should be actionable with clear steps to reproduce it. Otherwise, we are unfortunately not sure how to resolve this issue. 
So please try to provide a clear `Steps to reproduce` along with a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this. Thanks!

**Comment by Rohithgilla12** [comment]
@wesleycrispy I think this is because of `SafeArea` widget, can you remove it and give it a try?

**Comment by wesleycrispy** [comment]
here is what i did to reproduce my issue :
import 'package:flutter/material.dart';

I commented everything and only left this code!


void main() async {
  runApp(MyWidget());
}

class MyWidget extends StatelessWidget {
  const MyWidget({super.key});

  @override
  Widget build(BuildContext context) {
    return Container(
      color: Colors.red,
    );
  }
}

here is the output on android and ios simulators!

<img width="873" alt="Screenshot 2023-02-07 at 9 47 12 AM" src="https://user-images.githubusercontent.com/106236544/217196075-412991e2-48d9-4c6a-8bd0-43a8f3fa9d61.png">

**Comment by huycozy** [comment]
@wesleycrispy Can you retry on the latest Flutter channels and check if the issue still occurs? (stable 3.7.1, master 3.8.0-5.0.pre.10)

**Comment by wesleycrispy** [comment]
just tested with but i get the same results :( Flutter (Channel stable, 3.7.1).
I know the error is strange and hard to debug but is there any other suggestion ?
best regards.

**Comment by huycozy** [comment]
@wesleycrispy It could be emulator issue. There are two thoughts in my mind to test this issue that you may wanna try:
- Retry on an Android native project on that emulator
- Create another emulator and retry

**Comment by wesleycrispy** [comment]
I tried android native project and it works fine there. I also tried creating another emulator but i get the same output( also this issue happens on physical devices and only from my mac). :((((

**Comment by huycozy** [comment]
@wesleycrispy My colleagues try this on their M1 machine but also can not replicate it. 

Can you confirm this issue also happens on a newly created Flutter project? (Just to make sure there is no accidental modified code on Android native side)

**Comment by wesleycrispy** [comment]
This does not happen on a newly created Flutter project! Its the second time it has happened to me. On September i was building a project and after some weeks this error occurred to me. This is the second time, but the error somehow shows just after some time that you are working with the project ( and only on android ). I tried everything until i decided to open this issue. Its over my head for this one and you guys are my last hope! must be like the weirdest issue ever but ....

**Comment by huycozy** [comment]
@wesleycrispy The issue can come from Android native configurations. I suggest you back up `android` directory (you can compress it and save it somewhere) and then recreate it by the command `flutter create . --platforms=android`. 

Once the new android directory is re-created, retry it on your emulator. If it works by this way, try to compare your old (backup) android directory with the new one to find the cause of this.

**Comment by wesleycrispy** [comment]
what changed from :  flutter create . --platforms=android
android/build.gradle
from    ext.kotlin_version = '1.6.10'    to    ext.kotlin_version = '1.7.10'
from    classpath 'com.android.tools.build:gradle:7.1.2'  to     classpath 'com.android.tools.build:gradle:7.2.0'

that's it pretty much but what is important is that it now works as it should and i see my app on full screen.
Thank you so much for the help and best regards.
