### ISSUE TITLE
Error: Unable to find git in your PATH.  in Stable 3.7.1

### ISSUE THREAD

**Issue by eduardohr-muniz** [flutter/flutter#119993]
I'm having a problem on windows after updating flutter > 3.3.9 and up is giving the following problem, Error: Unable to find git in your PATH.
watch video below
![chrome_nLleZTzXVO](https://user-images.githubusercontent.com/90477293/216763292-fd61334f-7643-413c-8b3b-0ac9284aa445.gif)

**Comment by huycozy** [comment]
Hi @eduardohr-muniz 
Did you add C:\Windows\System32 to your PATH? Also, you may try solutions mentioned in this issue if they're helpful: https://github.com/flutter/flutter/issues/15047
