### ISSUE TITLE
[Impeller] When linear sampling text, remove half a texel from all sides of the sampling rect.

### ISSUE THREAD

**Issue by bdero** [flutter/flutter#119955]
This would allow us to remove the small amount of padding between glyphs in the atlas: https://github.com/flutter/engine/blob/16617b0a9104146bb3e821526d0d7d9ca0569e66/impeller/typographer/backends/skia/text_render_context_skia.cc#L74-L76\

I added this behavior some time ago, and then ended up removing it later while solving text transform problems/improving the sampling behavior for some text.

Note that removing half a texel from the glyph sampling UVs also requires doing the same for the vertex positions, lest we end up stretching the glyphs and making them look a bit thicker than they are. When doing this, one needs to be careful to not inadvertently cut away the edge pixels -- some tiny stretching of the vertex positions may be necessary to compensate for floating point precision and assure the edge pixels don't flicker.

**Comment by chinmaygarde** [comment]
Should we attempt this eagerly now? This seems like something that would cause subtle issues due to incorrect UV mapping.

**Comment by bdero** [comment]
This issue is outdated after the round of fixes I did last month. We should be mapping the text atlas texels to the pixel grid correctly, and it should be safe to have 1 pixel padding instead of 2.

**Comment by chinmaygarde** [comment]
Sounds good. Closing.
