### ISSUE TITLE
[in-app-purchases][Android] Billing codelabs has deprecated billing permissions

### ISSUE THREAD

**Issue by quentin7b** [flutter/flutter#120067]
Hello,

There is a mistake in the [in-app-purchases codelabs's step 3](https://codelabs.developers.google.com/codelabs/flutter-in-app-purchases#2)

It is specified that the plugin will ensure that

> This will ensure the `com.android.vending.BILLING` permission is added to the `android/app/src/main/AndroidManifest.xml` file in your Flutter application.

But since [Google Play Billing Library version deprecation](https://developer.android.com/google/play/billing/deprecation-faq), this is not added anymore.

Instead, `<uses-permission android:name="com.google.android.play.billingclient.version" />` is added.

(This might be because the codelabs was written with the `2.0.1` version of `in_app_purchases`, at the time of the issue opening we are in `3.1.1`.)

It might be nice to update the codelabs to prevent misunderstanding of what should be done by the plugin ?

**Comment by miquelbeltran** [comment]
Indeed this step is no longer required when using the current `in_app_purchase` plugin, so we should remove that from the codelab.

**Comment by miquelbeltran** [comment]
New codelab has been published now. Closing this now.
