### ISSUE TITLE
Make Gradle and all files Integrated into FlutterSDK in Android Folders Offline without additional download 

### ISSUE THREAD

**Issue by YahyaAtta** [flutter/flutter#120029]
When Create Project Flutter without having Internet Connection.
It say downloading gradle in first time and some files from Internet.
My Suggestion is Integrating Gradle and all files needed downloaded from Internet into Flutter SDK.
so it help create project and run your project without internet connection

**Comment by huycozy** [comment]
@YahyaAtta There was an issue that has been partially mentioned at https://github.com/flutter/flutter/issues/118162. I'm closing this issue in favor of #22429 which has been discussed there. 

You can leave there your comment and react an upvote to the original comment will help to raise the issue. Thank you!
