### ISSUE TITLE
Allow DragTarget() or GestureDetector() on path from e.g. Column() to Expanded()

### ISSUE THREAD

**Issue by steeeep34** [flutter/flutter#120019]
## Use case

I create an editor, which allows to create Flutter layouts visually. The editor thus allows to drop new widgets at certain places of the current widget layout.

The make widgets editable, I place editable items inside GestureDetector() widgets. Thus situations like this appear:

```
Column(                       // first item placed using editor
      children: [
        DragTarget(
          builder: (context, candidateData, rejectedData) {
            return Expanded(        // second item placed using editor inside Column()
              child: Text( 'X' ),
            );
          },
        )],
)
```
 Unfortunately, this renders an error, since Expanded() is no direct descendant of Column{}.

 Additionally, I wonder, why non-rendering widgets like GestureDetector technically interfere in such situations.

 Asked a question at SO: https://stackoverflow.com/questions/75349027/how-to-use-expanded-with-e-g-gesturedetector-on-path-from-column-to-expanded

## Proposal

Allow to place DragTarget(), GestureDetector() or such at the path from a flex widget like Column() to Expanded() widgets.

**Comment by exaby73** [comment]
Hello @steeeep34. This is working as intended since `DragTarget` is not a `Flex` widget. You could try wrapping `DragTarget` in an `Expanded` instead.

But since this working as intended, unfortunately, this is an invalid issue. Thank you

**Comment by steeeep34** [comment]
I know, that this behaves as documented. Nevertheless, I propose a feature request, not an issue.

**Comment by exaby73** [comment]
I do not think making these widgets a flex widget is a good solution as this might break existing apps' UI, and it's not clear that this widget would behave like this from the name of it. Due to this, keeping this issue closed
