### ISSUE TITLE
FractionalTranslation RTL

### ISSUE THREAD

**Issue by abarth** [flutter/flutter#12004]
translation needs to be FractionalOffsetGeometry.

**Comment by Hixie** [comment]
FractionalOffset is the wrong object for this.

**Comment by Hixie** [comment]
Either that or FractionalOffset just doesn't work in general...

cc @abarth

**Comment by abarth** [comment]
Can you say a bit more?  Why is FractionalOffset the wrong object for this?

**Comment by Hixie** [comment]
Suppose you want to offset the child 1x in the reading direction.
You use `FractionalOffsetDirectional(1.0, 0.0)`.
In LTR, it moves 1x to the right (it becomes FractionalOffset(1.0, 0.0)`).
In RTL, it moves 0x to the left (it becomes FractionalOffset(0.0, 0.0)`).

**Comment by abarth** [comment]
Got it.  The irony is that I think we invented FractionalOffset for this class.  :)

**Comment by Hixie** [comment]
It would work ok if the way we RTL'ed this was just to flip the sign. But then it wouldn't work in the other places... not that it works great there anyway...

**Comment by Hixie** [comment]
Maybe we should call this one FractionalSize

**Comment by abarth** [comment]
Or SizeFraction.  The ideal naming would probably be to call this one a FractionalOffset and call the other one Alignment, but that ship has probably sailed.

**Comment by abarth** [comment]
Looks like this code is mostly used for SlideTransition.  Often you want the widget to slide in from just outside its normal position in one dimension.

**Comment by abarth** [comment]
I guess what I'm suggesting is that the clients might work better if you they provided an `Axis` (or an `AxisDirection`) and a `double` to control the slide.

**Comment by Hixie** [comment]
haha, amusingly SlideTransition already tries to call it with an resolved FractionalOffsetGeometry... Gotta love Dart...

**Comment by Hixie** [comment]
That seems unnecessarily limiting... what if you want to slide something in from the top left, say?

**Comment by Hixie** [comment]
Or indeed, in a spiral or on a curve or something.

**Comment by Hixie** [comment]
Oh here's another option: we continue to use FractionalOffset, but the FractionalOffset.resolve function takes an argument that decides how you resolve it...

**Comment by Hixie** [comment]
(I'm having a lot of trouble coming up with a good alternative name for FractionalOffset for use here, plus I don't really want to break the SlideTransition API.)

**Comment by abarth** [comment]
Another option is to leave SlideTransition visual and make a SlideTransitionDirectional that works directionally with different arguments.

**Comment by Hixie** [comment]
Yeah that's probably the simplest solution here.

**Comment by abarth** [comment]
@Hixie This issue is assigned to you, but I feel like I have good context to work on it.  Have you started on it already?

**Comment by Hixie** [comment]
Nope, go for it. I started working on it then got stuck on FractionalOffset being the wrong object.

**Comment by Hixie** [comment]
We discussed this and examined all the clients of SlideTransition (which itself is the only client of FractionalTranslation). They fall into two camps: vertical transitions, and horizontal transitions that are driven by touch events. For the latter case, we're going to need to be careful about implementing RTL in the clients anyway, so there's no benefit to RTL support in SlideTransition.

We therefore have no clients that actually need RTL in SlideTransition. We're therefore going to close this bug and await a use case before trying to solve this problem, since there's no obvious solution.
