### ISSUE TITLE
[go_Router] queryParameters

### ISSUE THREAD

**Issue by Patrick386** [flutter/flutter#120000]
Futter web: 3.7
I want to open a page in a new tab in browser.
Forwarding parameter values to LaunchUrl will not open in go_Router.

```
  Future<void> downLoadAttachment(String dirPath, {bool isNewTab = true}) async {
    try {
         final Uri downloadUri = Uri(
          scheme: 'https',
          host: 'example.com',
          path: 'downloads/',
          queryParameters: {'id': dirPath},
      );
      await launchUrl(
        downloadUri,
        webOnlyWindowName: isNewTab ? '_blank' : '_self',
      );
    } catch (e) {
      logger.info('error:${e.toString()}');
    }
  }
```
 **https://example.com/downloads/?id=BpBWzzuuGkfI**

```
      GoRoute(
          name: 'downloads',
          path: '/downloads/:id',
          pageBuilder: (BuildContext context, GoRouterState state) {
          return NoTransitionPage<void>(
                key: state.pageKey,
                restorationId: state.pageKey.value,
                child: DownloadPage(url: state.params['id']!));
          }),
```

[✓] Flutter (Channel stable, 3.7.1, on macOS 13.0 22A380 darwin-arm64 (Rosetta), locale ko-KR)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2022.2.4)
[✓] VS Code (version 1.71.1)
[✓] VS Code (version 1.75.0)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

**Comment by iapicca** [comment]
@Patrick386 
could you provide a `runnable` code sample?

**Comment by Patrick386** [comment]
> @Patrick386 could you provide a `runnable` code sample?
sample code:
```
import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import 'package:url_launcher/url_launcher.dart';
import 'package:http/http.dart' as http;

final GoRouter _router = GoRouter(
  routes: [
    GoRoute(
      path: "/",
      builder: (context, state) => const HomePage(),
    ),
    /// http://127.0.0.1:8080/#/downloads/1234567890  << id2 format
    GoRoute(
      name: "downloads",
      path: "/downloads/:id",
      builder: (context, state) => DownloadPage(id: state.queryParams['id'] ?? 'error', id2: state.params['id'] ?? 'id2-Error',),
    ),
  ],
);

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
      routerConfig: _router,
      title: "Go router",
    );
  }
}


class HomePage extends StatelessWidget {
  const HomePage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text("Homepage"),
      ),
      body: Center(
        child: ElevatedButton(onPressed: () async {
          await ServiceAip.downloadUrlFile('1234567890');
        }, child: const Text('Downloads'),
        ),
      ),
    );
  }
}

class DownloadPage extends StatelessWidget {
  const DownloadPage({super.key, required this.id, required this.id2});
  final String id;
  final String id2;

  @override
  Widget build(BuildContext context) {

    return Scaffold(
      appBar: AppBar(
        automaticallyImplyLeading: true,
        title: const Text("Downloads"),
      ),
      body:  Center(
        child: Column(
          children: [
            const Text("Download Page"),
            Text("id:$id  / id2:$id2"),
          ],
        ),
      ),
    );
  }
}

/// cat /etc/hosts
/// 127.0.0.1
/// http://127.0.0.1:8080/#/downloads/?id=1234567890   << queryParameters 
class ServiceAip {
  static Future<void> downloadUrlFile(String id,{bool isNewTab = true}) async {

    Uri downloadUri = Uri(
      scheme: 'http',
      host: '127.0.0.1:8080',
      path: '/downloads/',
      queryParameters: {'id': id},
    );
    await launchUrl(
      downloadUri,
      webOnlyWindowName: isNewTab ? '_blank' : '_self',
    );
  }
}
```

**Comment by darshankawar** [comment]
Thanks for the report @Patrick386 
Is your issue as how to get the route history and query params ? If so, can you try using `GoRouteState.of(context)` and see if it helps in your case ?

**Comment by Patrick386** [comment]
> Thanks for the report @Patrick386 Is your issue as how to get the route history and query params ? If so, can you try using `GoRouteState.of(context)` and see if it helps in your case ?

**Flutter Web app:**
goRouter does not recognize the query parameter value passed by url_launcher. 
I want to open a page in a new window using goRouter. Is there a way?
Thank you.

**Comment by darshankawar** [comment]
@Patrick386 
See this [comment / solution](https://github.com/flutter/flutter/issues/113033#issuecomment-1272442557) and check if it helps in your case.

**Comment by Patrick386** [comment]
> @Patrick386 See this [comment / solution](https://github.com/flutter/flutter/issues/113033#issuecomment-1272442557) and check if it helps in your case.

Thank you. It seems that there are still many issues to be resolved in order to commercialize Flutter web apps. Various problems such as state loss occur when opening new windows. It seems that we will need to wait until stable support is available. Therefore, close this issue.
