### ISSUE TITLE
Touch-based fling inertia does not work when using engine embedding

### ISSUE THREAD

**Issue by Zee2** [flutter/flutter#120020]
## Summary

When using the Flutter engine embedder C API (`flutter_embedder.h`), when the `FlutterPointerDeviceKind` is `kFlutterPointerDeviceKindTouch` (i.e., using touch input), there is no scroll fling or inertia observed. When scrolling a ListView, when the "finger" leaves the "screen", there is no further inertia. The scroll stops immediately.

https://user-images.githubusercontent.com/5544935/216794808-9b91be1d-d8d7-4eda-b941-e9738c394051.mp4

I believe this is due to the C API lacking fields in the `FlutterPointerEvent` struct to describe touch _delta_ values. There is only the absolute `x` and `y` fields.

When digging through the source code for how the Android platform dispatches touch events to the Flutter engine, I noticed that it does not actually use this API. Instead, it uses the [`PointerDataPacketConverter`](https://github.com/flutter/engine/blob/2f5b7ac34415e6d94490aa28cf68761dbaa35419/lib/ui/window/pointer_data_packet_converter.cc) and a binary packet interface to embed mouse delta values. 

![image](https://user-images.githubusercontent.com/5544935/216794880-eab922f2-34ae-4bb8-8ce5-a136050fcb58.png)

The C API for Flutter embedding lacks the `physical_delta_x` and `physical_delta_y` fields, and the underlying engine implementation likely is unable to compute scroll inertia without these values.

## Steps to Reproduce

1. Embed Flutter using the C API
2. Dispatch touch events to the engine using `SendPointerEvent` with the `kMove` phase and the `kFlutterPointerDeviceKindTouch` device type
3. Observe no scroll inertia or flinging.

**Expected results:** 

Scroll flinging should work the same way it does on Android/iOS.

**Actual results:** 

No scrolling inertia, likely due to the missing physical delta fields from the C API.

<details>
<summary>Logging of individual pointer events sent to Flutter over the C API during the above screen recording</summary>

```
Adding (0.615958, 0.260847)
Hover (0.609077, 0.262936)
Hover (0.599629, 0.262196)
Hover (0.588661, 0.263521)
Hover (0.578187, 0.267594)
Hover (0.56594, 0.273915)
Hover (0.551606, 0.282605)
Down (0.540295, 0.294847)Mov (0.540295, 0.294847)
Mov (0.52402, 0.314123)
Mov (0.506194, 0.336497)
Mov (0.49136, 0.36525)
Mov (0.478065, 0.40013)
Mov (0.471733, 0.436331)
Mov (0.469626, 0.483688)
Mov (0.466506, 0.535872)
Mov (0.465543, 0.589788)
Mov (0.46465, 0.644361)
Mov (0.458974, 0.693993)
Mov (0.456731, 0.734393)
Up (0.460067, 0.761879)
Hover (0.462284, 0.787889)
Hover (0.470545, 0.802322)
Hover (0.479675, 0.812034)
Hover (0.489785, 0.817329)
Hover (0.496692, 0.819357)
Removing (0.501063, 0.820074)
Adding (0.50233, 0.809722)
Hover (0.49676, 0.809108)
Hover (0.490991, 0.80841)
Hover (0.487995, 0.803566)
Hover (0.483943, 0.800553)
Hover (0.477866, 0.793941)
Hover (0.470102, 0.787162)
Hover (0.462693, 0.777975)
Hover (0.453636, 0.764289)
Down (0.444506, 0.7477)Mov (0.444506, 0.7477)
Mov (0.434431, 0.725796)
Mov (0.423657, 0.695749)
Mov (0.412802, 0.664183)
Mov (0.406776, 0.634159)
Mov (0.401406, 0.595647)
Mov (0.403411, 0.559436)
Mov (0.409139, 0.528334)
Mov (0.419717, 0.497461)
Mov (0.438535, 0.467352)
Mov (0.461323, 0.437837)
Mov (0.488728, 0.411929)
Mov (0.515137, 0.389213)
Mov (0.54017, 0.374823)
Up (0.567696, 0.361697)
Hover (0.590687, 0.356167)
Hover (0.607056, 0.350015)
Hover (0.618185, 0.345559)
Hover (0.625103, 0.34499)
Removing (0.630029, 0.343998)
```

**Comment by moffatman** [comment]
Do you have an example I can run to see the problem, I would expect all events to still go through the converter in this case. Also, a printout of each `ui.PointerData` which arrives in dart would be helpful.

**Comment by Zee2** [comment]
Hey @moffatman , thanks so much for the super rapid response. Honestly was not expecting such prompt response for such a weird niche use case of the embedder. I'll get the logging of the dart pointerdata asap, one moment!

**Comment by Zee2** [comment]
Wow, OK, so you were right. Dart is in fact receiving physicalDeltaX/Y. Here's the entire dump of one "swipe" on the virtual touchscreen.

<details>
<summary>Expand meeee!</summary>

```
Adding (0.398795, 0.128851)
flutter: Event x/y: 204.1831817626953, 65.9715347290039
flutter: Event deltaX/Y: 0.0, 0.0
flutter: Event phase: PointerChange.add
Hover (0.398963, 0.140778)
flutter: Event x/y: 204.26910400390625, 72.07835388183594
flutter: Event deltaX/Y: 0.0859222412109375, 6.106819152832031
flutter: Event phase: PointerChange.hover
Hover (0.39851, 0.147571)
flutter: Event x/y: 204.03692626953125, 75.55628967285156
flutter: Event deltaX/Y: -0.232177734375, 3.477935791015625
flutter: Event phase: PointerChange.hover
Hover (0.398537, 0.162977)
flutter: Event x/y: 204.0511932373047, 83.44416046142578
flutter: Event deltaX/Y: 0.0142669677734375, 7.887870788574219
flutter: Event phase: PointerChange.hover
Hover (0.398272, 0.174984)
flutter: Event x/y: 203.91519165039062, 89.59203338623047
flutter: Event deltaX/Y: -0.1360015869140625, 6.1478729248046875
flutter: Event phase: PointerChange.hover
Hover (0.398237, 0.1922)
flutter: Event x/y: 203.89712524414062, 98.4062728881836
flutter: Event deltaX/Y: -0.01806640625, 8.814239501953125
flutter: Event phase: PointerChange.hover
Down (0.397904, 0.212893)Mov (0.flutter3: 9Event x/y: 203.72686767578125, 109.001213073730477
9flutter0: 4Event deltaX/Y: -0.170257568359375, 10.594940185546875,
0flutter.: 212Event phase: PointerChange.hover893
)flutter
: Event x/y: 203.72686767578125, 109.00121307373047
flutter: Event deltaX/Y: 0.0, 0.0
flutter: Event phase: PointerChange.down
flutter: Event x/y: 203.72686767578125, 109.00121307373047
flutter: Event deltaX/Y: 0.0, 0.0
flutter: Event phase: PointerChange.move
Mov (0.397078, 0.237066)
flutter: Event x/y: 203.30404663085938, 121.37761688232422
flutter: Event deltaX/Y: -0.422821044921875, 12.37640380859375
flutter: Event phase: PointerChange.move
Mov (0.39553, 0.264702)
flutter: Event x/y: 202.51145935058594, 135.52725219726562
flutter: Event deltaX/Y: -0.7925872802734375, 14.149635314941406
flutter: Event phase: PointerChange.move
Mov (0.392351, 0.30265)
flutter: Event x/y: 200.8838653564453, 154.95692443847656
flutter: Event deltaX/Y: -1.627593994140625, 19.429672241210938
flutter: Event phase: PointerChange.move
Mov (0.388723, 0.338762)
flutter: Event x/y: 199.02606201171875, 173.44627380371094
flutter: Event deltaX/Y: -1.8578033447265625, 18.489349365234375
flutter: Event phase: PointerChange.move
Mov (0.383292, 0.383201)
flutter: Event x/y: 196.24537658691406, 196.1990966796875
flutter: Event deltaX/Y: -2.7806854248046875, 22.752822875976562
flutter: Event phase: PointerChange.move
Mov (0.376063, 0.425457)
flutter: Event x/y: 192.54420471191406, 217.83387756347656
flutter: Event deltaX/Y: -3.701171875, 21.634780883789062
flutter: Event phase: PointerChange.move
Mov (0.368049, 0.470575)
flutter: Event x/y: 188.4412841796875, 240.9346160888672
flutter: Event deltaX/Y: -4.1029205322265625, 23.100738525390625
flutter: Event phase: PointerChange.move
Mov (0.359367, 0.520024)
flutter: Event x/y: 183.99594116210938, 266.25250244140625
flutter: Event deltaX/Y: -4.445343017578125, 25.317886352539062
flutter: Event phase: PointerChange.move
Mov (0.349704, 0.575064)
flutter: Event x/y: 179.04856872558594, 294.4327087402344
flutter: Event deltaX/Y: -4.9473724365234375, 28.180206298828125
flutter: Event phase: PointerChange.move
Mov (0.338041, 0.63812)
flutter: Event x/y: 173.0771942138672, 326.7173156738281
flutter: Event deltaX/Y: -5.97137451171875, 32.28460693359375
flutter: Event phase: PointerChange.move
Mov (0.327397, 0.689813)
flutter: Event x/y: 167.6275177001953, 353.1842346191406
flutter: Event deltaX/Y: -5.449676513671875, 26.4669189453125
flutter: Event phase: PointerChange.move
Up (0.318326, 0.727628)
flutter: Event x/y: 162.9828338623047, 372.5457458496094
flutter: Event deltaX/Y: -4.644683837890625, 19.36151123046875
flutter: Event phase: PointerChange.move
flutter: Event x/y: 162.9828338623047, 372.5457458496094
flutter: Event deltaX/Y: 0.0, 0.0
flutter: Event phase: PointerChange.up
Hover (0.307977, 0.760526)
flutter: Event x/y: 157.6840057373047, 389.38946533203125
flutter: Event deltaX/Y: -5.298828125, 16.843719482421875
flutter: Event phase: PointerChange.hover
Removing (0.2941, 0.792497)
flutter: Event x/y: 150.57899475097656, 405.7584533691406
flutter: Event deltaX/Y: -7.105010986328125, 16.368988037109375
flutter: Event phase: PointerChange.hover
flutter: Event x/y: 150.57899475097656, 405.7584533691406
flutter: Event deltaX/Y: 0.0, 0.0
flutter: Event phase: PointerChange.remove
```

The logs with `flutter` are the dart logs, and the ones without are from C logging the SendPointerEvent calls.

**Comment by Zee2** [comment]
I already tried some ideas, including

- Making a custom `MaterialScrollBehavior` that made sure `dragDevices` included `.touch`
- Making the `ListView` have `physics: const BouncingScrollPhysics()`
- Emulating other types of input devices
- Fooling Flutter into thinking I was on `TargetPlatform.android` or `TargetPlatform.fuschia` or any other platform
- Making sure I populate the `device` field with reasonable 0/1 values for left or right handed fingers
- Setting `FlutterPointerEvent.buttons` to `0`
- Messing with the `FlutterPointerEvent.timestamp`, pushing it into the future or past, to see if it is a timing weirdness
- Not removing the pointers at all (maybe issuing a `kRemove` was making the fling stop? Didn't seem to be the case...)
- Not firing `kHover`
- Lots of things I can't remember right now

**Comment by moffatman** [comment]
I tried running it but just got a grey screen with the floating hand, no flutter window. The dart code was running, though, I added a printout and saw it in the console. Any library I need to install manually?

Two other things you can check for me though

1. The timestamps in dart - maybe if timestamps are off in units (ms vs us?), the calculated velocity-per-second could ~=0.
2. A print at the beginning of `ScrollDragController::end` to print out the `details`. Then we can see the actual final velocity.

**Comment by Zee2** [comment]
Ah, what you're seeing is that the user's view in the 2D window is in front of that window. You can check out the controls for the simulator here: https://stereokit.net/Pages/Guides/Using-The-Simulator.html

To reorient the camera, you just hold Shift and use WASDQE + holding down right click to look around. You shouldn't need any other deps in your system, you just need to make the camera look in the right direction/position.

Oh, I think you might be onto something with the units of the timestamp. I am directly using the result of `FlutterEngineGetCurrentTime()`, which returns in nanoseconds. Looks like the pointer event requires microseconds! That might have fixed it, let me check.

**Comment by Zee2** [comment]
https://user-images.githubusercontent.com/5544935/216851287-77577a7d-9964-40d8-aad8-799629e30aa7.mp4

That was it! @moffatman you rock :) It was the wrong timestamp units. The comments on `engine_embedder.h` definitely confused me because it said to use "the same clock as `FlutterEngineGetCurrentTime`". 

![image](https://user-images.githubusercontent.com/5544935/216851320-a2ec2e49-8751-48b4-9d6e-fe9c4c6d6071.png)

But I conveniently didn't read the bit about the units :D

Thanks so much for the quick response and super helpful info. Cheers!!

**Comment by moffatman** [comment]
Nice! Happy to help, and looks like a cool project 👍
