### ISSUE TITLE
Dart -> Engine roll stopped

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#120091]
On the Dart -> Engine roll reverted here https://github.com/flutter/engine/pull/39422, Engine -> Framework rolls started failing with the error

```
14:50 +29 ~13 -1: test/integration.shard/stateless_stateful_hot_reload_test.dart: Can switch between stateless and stateful [E]                                                                        
  Exception: Hot reload request failed
  
  [{"id":3,"result":{"code":1,"message":"Reloaded 1 of 652 libraries"}}]
  
  Reassembling main.dart$main-3696557592808931 failed: ext.flutter.reassemble: (-32000) Server error
  {"exception":"type '_State' is not a subtype of type 'State<StatefulWidget>?' of 'function result'","stack":"
#0      StatefulElement._state (package:flutter/src/widgets/framework.dart)\n
#1      StatefulElement.state (package:flutter/src/widgets/framework.dart:5071:38)\n
#2      StatefulElement.reassemble (package:flutter/src/widgets/framework.dart:5077:7)\n
#3      Element.reassemble.<anonymous closure> (package:flutter/src/widgets/framework.dart:3403:13)\n
#4      SingleChildRenderObjectElement.visitChildren 
...
#389    BindingBase.reassembleApplication (package:flutter/src/foundation/binding.dart:595:12)\n
#390    BindingBase.registerSignalServiceExtension.<anonymous closure> (package:flutter/src/foundation/binding.dart:630:23)\n
#391    BindingBase.registerServiceExtension.<anonymous closure> (package:flutter/src/foundation/binding.dart:840:32)\n
<asynchronous suspension>\n","method":"ext.flutter.reassemble"}
  test/integration.shard/test_driver.dart 751:5                        FlutterRunTestDriver._throwErrorResponse
  test/integration.shard/test_driver.dart 662:7                        FlutterRunTestDriver._restart
  ===== asynchronous gap ===========================
  test/integration.shard/stateless_stateful_hot_reload_test.dart 44:5  main.<fn>
  

To run this test again: /b/s/w/ir/x/w/flutter/bin/cache/dart-sdk/bin/dart test test/integration.shard/stateless_stateful_hot_reload_test.dart -p vm --plain-name 'Can switch between stateless and stateful'

```

Starting with the Engine -> Framework roll here https://github.com/flutter/flutter/pull/120030

Example: https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20tool_integration_tests_3_4/19373/overview

**Comment by zanderso** [comment]
Maybe this one? https://dart.googlesource.com/sdk.git/+/87810072db06c1a16fdaa7bf6bb77ef4e6405af5

@alexmarkov

**Comment by zanderso** [comment]
cc @jonahwilliams who wrote the feature/test.

**Comment by alexmarkov** [comment]
Maybe we should just double check that `widget is StatefulWdiget` in `StatefulElement.reassemble` before calling `state.reassemble()`.

**Comment by zanderso** [comment]
@jonahwilliams do you know who would be a good person to take a look? Maybe @goderbauer?

**Comment by chinmaygarde** [comment]
[The VM revert](https://github.com/dart-lang/sdk/commit/134b2dca861cc35308a67fb372c0a42c410357d0) is going to take a bit to roll into the dev branches. It also identified a real issue that is being tracked separately.

**Comment by jason-simmons** [comment]
The failure occurs when hot reload invokes `WidgetsBinding.performReassemble`, which traverses the current element tree and calls `reassemble` on each element.

(The `Element.updateChild` code path referenced above has not yet run.)

The test is running an app like this:
```
import 'package:flutter/material.dart';
import 'package:flutter/scheduler.dart';
import 'package:flutter/services.dart';
import 'package:flutter/widgets.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  final ByteData message = const StringCodec().encodeMessage('AppLifecycleState.resumed')!;
  await ServicesBinding.instance!.defaultBinaryMessenger.handlePlatformMessage('flutter/lifecycle', message, (_) { });
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: Child(),
    );
  }
}

class Child extends StatefulWidget {
  State createState() => _State();
}

class _State extends State<Child> {
  @override
  Widget build(BuildContext context) {
    print('STATEFUL');
    return Container();
  }
}
```

It then replaces the `Child` and `_State` classes with:

```
class Child extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    print('STATELESS');
    return Container();
  }
}

class Other extends StatefulWidget {
  State createState() => _State();
}

class _State extends State<Other> {
  @override
  Widget build(BuildContext context) {
    print('STATEFUL');
    return Container();
  }
}
```

The test then does a hot reload.  The `reassemble` traversal reaches the `StatefulElement` associated with the old stateful `Child` widget.  That `StatefulElement` contains a `_state` field that was an instance of the old `_State` class.  But with https://github.com/dart-lang/sdk/commit/87810072db06c1a16fdaa7bf6bb77ef4e6405af5 accessing that field after hot reload throws a type error.

Is this access pattern expected to be safe in Dart?
Or is there any way to detect at runtime that the old `_State` class has disappeared?

**Comment by alexmarkov** [comment]
Hot reload keeps _data_ (state, heap) of the running program while replacing _code_. Note that type arguments of live objects are considered data and not updated. `_State` class doesn't disappear, and `StatefulElement._state` still points to an existing, old instance of `_State`.  `_State` used to extend State<Child> and type arguments of that instance are [Child]. After the update, Child is no longer a subtype of `StatefulWidget`, so old instance of `_State` is no longer assignable to `State<StatefulWidget>`. This doesn't prevent hot reload from happening, but VM adds a _load guard_ to a getter of `StatefulElement._state` field, which throws an error if program tries to access an instance which no longer conforms to a type of a field. That load guard is used to contain the soundness violation, as the rest of the program still assumes that Dart types are sound. Due to a bug which was fixed in my CL, those load guards were sometimes omitted. After the fix, load guard now correctly throws an exception.

> Is this access pattern expected to be safe in Dart?

Field access is not safe if runtime type of its value is no longer a subtype of a static type of a field (soundness of field type is violated). If you anticipate such changes, consider typing those fields more loosely - for example, use `Object?` and then test type of an object at run time. In this case, we can probably test if widget is still StatefullWidget before accessing its state.

**Comment by jonahwilliams** [comment]
Okay thinking about this some more, I had it a bit backwards but remembered:

1. We go through the entire tree and call reassemble, marking everything as dirty.
2. After reassemble we rebuild, and in the rebuild check we try to see if the types changed and dispose the widget if that happened.

The problem like @jason-simmons says is that we're now hitting the type error in 1 before we get to 2. However, if we know that the type is changed then we know that we're going to dispose and remove the entire element. In that case it is safe to early return from reassemble.

At that point, we only need a way to determine if the type of that Element/widget has changed. Making the backing storage Object? and adding a cast unfortunately has a tremendous runtime cost for web implementations. Ideally we could have a debug only path.

**Comment by jonahwilliams** [comment]
https://github.com/flutter/flutter/pull/120390 will remove part of the failing test. I would love a way to detect that this sort of change during hot reload so we can accommodate it

**Comment by alexmarkov** [comment]
> I would love a way to detect that this sort of change during hot reload so we can accommodate it

It looks like we detect that already, but at a different place:

https://github.com/flutter/flutter/blob/2239f6c8a91dff3495238f0496ea86d882a3b122/packages/flutter/lib/src/widgets/framework.dart#L3607-L3628

**Comment by jonahwilliams** [comment]
I don't think that would work here but maybe it will. We'd have to add that check to the state reassemble and early return

**Comment by a-siva** [comment]
Is this still a P0? A revert was done of https://dart-review.googlesource.com/c/sdk/+/280401 and I think the rolls have restarted.

**Comment by jonahwilliams** [comment]
No, and we've disabled the failing test so it should be safe to reland [280401](https://dart-review.googlesource.com/c/sdk/+/280401)

**Comment by alexmarkov** [comment]
Can this problem affect users? Should we solve it before relanding the change, instead of just disabling the test?
