### ISSUE TITLE
FlutterLogoDecoration RTL

### ISSUE THREAD

**Issue by abarth** [flutter/flutter#12005]
FlutterLogoDecoration#margin needs to be EdgeInsetsGeometry.

Also, not sure if FlutterLogoStyle.horizontal should put the logo on the right in RTL.

**Comment by Hixie** [comment]
Flutter's logo is LTR, so the logo image is always to the left of the text, regardless of ambient directionality.

**Comment by abarth** [comment]
Ok, so it's just the margin that we should generalize.

**Comment by Hixie** [comment]
I looked into this and concluded we should just have the consumers resolve their margins. As it turns out, the only such margin in our codebase today is horizontally symmetric.
