### ISSUE TITLE
A small change in the code shown in the code description and the code we were told to paste in code lab

### ISSUE THREAD

**Issue by IamAbhinav03** [flutter/flutter#120087]
Hi.

I was going through the code labs and found this small issue.

<img width="1420" alt="Screenshot 2023-02-06 at 8 58 04 PM" src="https://user-images.githubusercontent.com/66298497/217013057-77020fd6-938a-4005-ae52-8c6ee17339ad.png">

The code shown here ⬆️ uses Colors.green as the seed color. But in the code we were asked to paste ⬇️ use Colors.deepOrange as the seed color.

<img width="1407" alt="Screenshot 2023-02-06 at 8 57 30 PM" src="https://user-images.githubusercontent.com/66298497/217012900-56a6a53d-11b6-455c-9717-784aba6a2a3d.png">

Is it possible for me to fix this issue. If so can you guide me where to make the changes.

**Comment by darshankawar** [comment]
https://codelabs.developers.google.com/codelabs/flutter-codelab-first#3

/cc @domesticmouse

**Comment by domesticmouse** [comment]
Hey @filiph can you look at this?

**Comment by filiph** [comment]
Ah, thanks for the catch, @IamAbhinav03! Fixed. (It will take some time to propagate to the actual codelab, though.)
