### ISSUE TITLE
Expose TextPainter's preferredLineHeight in RenderParagraph

### ISSUE THREAD

**Issue by TheCarpetMerchant** [flutter/flutter#120007]
## Use case

I am repositioning a `ScrollController` to snap to the current line (making sure it's visible in its entirety).
To do this, I must know what is the actual size of a line of text, or at least the closest approximation possible.

## Proposal

Reconsider exposing TextPainter's `preferredLineHeight` on RenderParagraph as described in #65150. At the time the implementation for that particular getter was described as "sketchy", but I do not know if that is still the case (code has changed since).
For now, I am using `renderParagraph.getFullHeightForCaret(const TextPosition(offset: 0)) ?? 0`, but that is of course limited to the first character. This is the best solution I've got as of now, and would welcome any more precise way of getting this info.

**Comment by LongCatIsLooong** [comment]
I'm planning to expose [a new `TextLayout` interface on some `TextPainter` and some render objects](https://docs.google.com/document/d/12iEpfcqnHMIV6slNPrbaEkWih5cuSkH-si_OTiZ9RLw). Does this cover your proposal?

`preferredLineHeight` has not changed much it's still a bit sketchy. IIRC uses a whitespace character as a template to estimate how tall the lines in the paragraph are, which may not work well when there's rich text, or the first line or the last line needs different leading than other lines.

**Comment by TheCarpetMerchant** [comment]
I just sent an access request to that google doc.
But from what you're describing about TextPainter's `preferredLineHeight`, it's no better that what I'm already doing so I'll close this issue and keep an eye out for what you're planning with TextLayout.

Thanks !
