### ISSUE TITLE
ui.platformViewRegistry.registerViewFactory throws error after Flutter release 3.0.5

### ISSUE THREAD

**Issue by sunilguptasg** [flutter/flutter#120043]
## Steps to Reproduce

 // ignore: undefined_prefixed_name
ui.platformViewRegistry.registerViewFactory(
        <some string>,
        (int viewId) => <some element, in my case VideoElement>,
);
## Logs

at run time - 
Flutter Web factoryFunction is PlatformViewFactory || factoryFunction is ParameterizedPlatformViewFactory is not true

<details>

```
<!-- If possible, paste the output of running `flutter doctor -v` here. -->
[√] Flutter (Channel stable, 3.7.0, on Microsoft Windows [Version 10.0.19045.2486], locale en-IN)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.2.6)
[√] Android Studio (version 2021.2)
[√] VS Code (version 1.75.0)
[√] VS Code, 64-bit edition (version 1.64.0)
[√] Connected device (3 available)
[√] HTTP Host Availability
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @sunilguptasg,

Please provide your `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) along with steps to reproduce so that we can investigate this. 

Thank you
