### ISSUE TITLE
Leading ListTile icon does not match M3 specs 

### ISSUE THREAD

**Issue by Craftplacer** [flutter/flutter#120040]
## Steps to Reproduce

1. Create a ListTile with Icon (without parameters, except icon itself of course) as `leading`

**Expected results:** Color is 'on surface variant', size is 18dp

**Actual results:** Color doesn't match, size is 24dp

Code sample: https://dartpad.dev/?id=2605ca48e55d86312e3daec99e1ee950&channel=master

Reference: https://m3.material.io/components/lists/specs#7134fed0-fd57-46a6-b126-f1c47b12531b

![image](https://user-images.githubusercontent.com/22963120/216827773-dbdaa54c-b9a9-4c3d-8716-214372d138e8.png)

**Comment by exaby73** [comment]
## Triage report

I can reproduce this issue on stable (3.7.1) and master. Interestingly, the colors are different on stable and master both, and both are not the surface variant

<details><summary>Code Sample (Same as OP)</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      theme: ThemeData(useMaterial3: true),
      home: Scaffold(
        body: Column(
          children: [
            const ListTile(
              leading: Icon(Icons.person_outline),
              title: Text("Headline"),
              subtitle: Text("Supporting text"),
            ),
            ListTile(
              leading: Builder(
                builder: (context) {
                  return Icon(
                    Icons.person_outline,
                    size: 18,
                    color: Theme.of(context).colorScheme.onSurfaceVariant,
                  );
                },
              ),
              title: const Text("Headline"),
              subtitle: const Text("Supporting text"),
            ),
            ListTile(
              leading: Builder(
                builder: (context) {
                  final actual = IconTheme.of(context).color;
                  final expected =
                      Theme.of(context).colorScheme.onSurfaceVariant;
                  return Text(
                    actual == expected ? "Colors match" : "Colors don't match",
                    style: Theme.of(context).textTheme.bodyLarge,
                  );
                },
              ),
            ),
            ListTile(
              leading: Builder(
                builder: (context) {
                  final actual = IconTheme.of(context).size;
                  return Text(
                    actual == 18 ? "Sizes match" : "Sizes don't match",
                    style: Theme.of(context).textTheme.bodyLarge,
                  );
                },
              ),
            ),
          ],
        ),
      ),
    );
  }
}
```

</details>

<details>
<summary>Screenshots</summary>

#### Stable
<img width="400" src="https://user-images.githubusercontent.com/50555895/216942172-99f5368f-de1d-4fba-b1ee-10feceb78eae.png">

#### Master
<img width="400" src="https://user-images.githubusercontent.com/50555895/216942428-d1911663-2e03-4ba3-b099-997129798d89.png">

</details>

<details><summary><code>flutter doctor -v</code> (Master)</summary>

```
[!] Flutter (Channel master, 3.8.0-4.0.pre, on macOS 13.2 22D49 darwin-arm64, locale en-US)
    • Flutter version 3.8.0-4.0.pre on channel master at /Users/nabeelparkar/fvm/versions/master
    ! Warning: `dart` on your path resolves to /opt/homebrew/Cellar/dart/2.19.1/libexec/bin/dart, which is not inside your current Flutter SDK checkout at /Users/nabeelparkar/fvm/versions/master. Consider adding /Users/nabeelparkar/fvm/versions/master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b8f5394a5c (24 hours ago), 2023-02-04 23:06:19 -0800
    • Engine revision 2a104cdfcd
    • Dart version 3.0.0 (build 3.0.0-204.0.dev)
    • DevTools version 2.21.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nabeelparkar/Library/Android/sdk/
    • Platform android-33, build-tools 33.0.0
    • ANDROID_SDK_ROOT = /Users/nabeelparkar/Library/Android/sdk/
    • Java binary at: /Users/nabeelparkar/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/213.7172.25.2113.9123335/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /Applications/Brave Browser.app/Contents/MacOS/Brave Browser

[✓] Android Studio (version 2021.3)
    • Android Studio at /Users/nabeelparkar/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/213.7172.25.2113.9123335/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[!] Android Studio (version 2022.1)
    • Android Studio at /Users/nabeelparkar/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/221.6008.13.2211.9477386/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] VS Code (version 1.74.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.58.0

[✓] Connected device (3 available)
    • iPhone 14 Pro Max (mobile) • 6BC61E88-4DE0-4BCB-8599-DA5294269146 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-2 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 13.2 22D49 darwin-arm64
    • Chrome (web)               • chrome                               • web-javascript • Brave Browser 109.1.47.186

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.
```

</details>

**Comment by TahaTesser** [comment]
Hey! 
Thanks for the report. It looks like I used unselected token color instead of a regular one. 
Since my first instinct was for `ListTile` to be unselected so it should receive unselected color but now matching the regular icon color with Android in Figma, the current unselected icon color is definitely not the right one.

**Comment by TahaTesser** [comment]
As for the leading icon size, the default icon size is always been `24dp`.


I can see some inconsistencies in the specs for the leading icon.

The layout specs show `24dp` both `leading` and `trailing` icons.

![Screenshot 2023-02-10 at 16 14 52](https://user-images.githubusercontent.com/48603081/218114299-7787d106-d60a-48a9-9eae-075283bbf1c1.png)

![Screenshot 2023-02-10 at 16 20 33](https://user-images.githubusercontent.com/48603081/218115207-30939903-9ef8-4bad-81f8-81d7eb51f764.png)

When testing `ListItem` on [Android](https://m3.material.io/components/lists/overview), I can verify the icon size for the `leading` and `trailing` is in fact 24dp.
  
![Screenshot 2023-02-10 at 15 12 08](https://user-images.githubusercontent.com/48603081/218116435-f96249e6-1792-4b33-8a7b-f526f9c2b794.png)






but the leading icon token indeed is `18dp`

https://github.com/flutter/flutter/blob/001c4951b61957f94d66fe1600efe6e0aa40248b/dev/tools/gen_defaults/data/list.json#L40

![Screenshot 2023-02-10 at 16 14 29](https://user-images.githubusercontent.com/48603081/218115647-fb994f8d-29aa-432e-ba23-95956a53ac7b.png)


cc: @guidezpl 
Can you please find the reason for this?

**Comment by guidezpl** [comment]
Thanks! Filed b/269282527 for the tokens team to take a look

**Comment by TahaTesser** [comment]
https://github.com/flutter/flutter/pull/120444 fixed icon color issue, if the specs for icon size change. I will file separate for issue for it and fix. Existing icons size looks as expected to me and matches native.

**Comment by guidezpl** [comment]
FYI `md.comp.list.list-item.leading-icon.size` has been updated to 24dp in a recent tokens version

**Comment by TahaTesser** [comment]
> FYI `md.comp.list.list-item.leading-icon.size` has been updated to 24dp in a recent tokens version

Icon already defaults to 24dp. 
We can use the token anyway when its available at https://github.com/flutter/flutter/tree/master/dev/tools/gen_defaults (there is no bug to be fixed here for the icon size)

**Comment by TahaTesser** [comment]
Since this is not a bug and just a token to reflect the same default icon value but for the `ListTile`. 

Filed a separate value update tracker from the token when its available for the ListTile https://github.com/flutter/flutter/issues/132120
