### ISSUE TITLE
Context Menus on desktop should dismiss when area outside menu is clicked

### ISSUE THREAD

**Issue by 0xNF** [flutter/flutter#120059]
On Windows desktop, context menus permit dismissing via clicking anywhere that isn't the menu itself, and also via esc. This is also how Flutter's Dialog via `showDialog` works.  However, context menus don't behave this way, which leads to situations where the behavior is out of sync with desktop expectations:

[ContextClick.webm](https://user-images.githubusercontent.com/1915007/216893069-dc8e48bd-c62e-42dd-a67b-81cf8d3c5d7c.webm)

I followed the example at https://api.flutter.dev/flutter/widgets/ContextMenuController-class.html, while wrapping only the context-menu enabled widgets with the `_ContextMenuRegion` helper class.

**Comment by danagbemava-nc** [comment]
Hi @0xNF, 

Please provide your `flutter doctor -v` and the [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that you used. 

Thank you

**Comment by 0xNF** [comment]
@danagbemava-nc 

Please clone this repo and launch on Windows to see. Unlike a popup dialog which can be dismissed with barrier clicks or the esc key, this sample, adapted slightly from the official documentation, does not behave as expected on windows.

https://github.com/0xNF/flutter_context_menu_behavior

Flutter doctor:

```
[√] Flutter (Channel stable, 3.7.1, on Microsoft Windows [Version 10.0.22621.1105], locale en-US)
    • Flutter version 3.7.1 on channel stable at C:\Users\nf\Documents\nickdocs\external\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7048ed95a5 (5 days ago), 2023-02-01 09:07:31 -0800
    • Engine revision 800594f1f4
    • Dart version 2.19.1
    • DevTools version 2.20.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at C:\Users\nf\AppData\Local\Android\sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Professional 2022 17.4.4)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Professional
    • Visual Studio Professional 2022 version 17.4.33213.308
    • Windows 10 SDK version 10.0.22621.0

[√] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] VS Code, 64-bit edition (version 1.74.3)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.58.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22621.1105]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 109.0.5414.120
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 108.0.1462.76

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

**Comment by danagbemava-nc** [comment]
Hi @0xNF, I think the issue is from your code sample. From what I see in the widget inspector with your code sample, you have created several ContextMenuRegions.

<details>
<summary>screenshot</summary>

<img width="340" alt="Screenshot 2023-02-07 at 06 40 56" src="https://user-images.githubusercontent.com/88313112/217169443-3812cd3e-d49f-46d6-88d4-b850861cdc4d.png">

</details>

Can you try making the `ContextMenuRegion` the parent of the Column or rather, the direct child of the Scaffold (so there's only one ContextMenuRegion)  and try again to see if the bug still reproduces?
