### ISSUE TITLE
[CP] [Impeller] Retain embolden/skew font properties when rendering text glyphs

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#120100]
### issue_link

https://github.com/flutter/flutter/issues/119489

### Commit Hash

https://github.com/flutter/engine/commit/4fdbb0a366e76920f62d23ce220456e1c5a255ab

### Target

stable

### pr_link

https://github.com/flutter/engine/pull/39424

### Impacted Users

Impeller users

### Impact Description

Font properties were not retained properly when rendering the glyph atlas, causing text to look wonky.

### Workaround

There is no workaround

### Risk

low

### Test Coverage

yes

### Validation Steps

Ensure text with these properties set looks correct.

**Comment by zanderso** [comment]
cc @bdero @jonahwilliams @chinmaygarde

**Comment by zanderso** [comment]
I included https://github.com/flutter/engine/pull/39383 in this CP as well since it looks like these are supposed to go together.

**Comment by jonahwilliams** [comment]
LGTM
