### ISSUE TITLE
Feature request: Decouple geometry.dart from the rest of dart:ui?

### ISSUE THREAD

**Issue by emshack** [flutter/flutter#12016]
My team is working on a command-line Dart tool that we would like to use the `geometry.dart` classes Size, Rect and Offset for. Would it be possible down the line to decouple `geometry.dart` from the rest of `dart:ui` so that it could be used in a headless context? We are also using other Flutter libraries elsewhere in the project (not in the command-line tool), so writing our own versions of these classes or copying the `geometry.dart` file into our codebase would mean extra code to convert our local versions to those used by the Flutter libraries.

@mishadynin
@krisgiesing

**Comment by Hixie** [comment]
You should feel free to reuse the code, but we can't really decouple it (short of putting it in dart:core itself) because dart:ui can't depend on any packages, it's part of the VM itself.

**Comment by krisgiesing** [comment]
Hm, that's a bit of a shame. Is there a good trick for automating the conversion of the local classes to the equivalent dart:ui classes, or do we just fall back on field-by-field copies?

**Comment by Hixie** [comment]
No good trick. I would probably make your copies have "toFoo" style methods that do the right thing, but even that is problematic because obviously your version can't import dart:ui...

Maybe we should move these to dart:core?

**Comment by krisgiesing** [comment]
Yeah, for dependency reasons I think we'd need a 3rd class to do the conversion, one which knows about both sides.

Putting these in dart:core would be nice for us but I'd feel a little guilty being the sole client for something core to the language.

**Comment by eseidelGoogle** [comment]
I seem to recall it might be possible to provide additional dart: to the `dart` command line executable which possibly could work for your case.  I'd reach out to @a-siva or someone who knows the VM well to ask.

**Comment by matanlurey** [comment]
What about `dart:math`?

**Comment by krisgiesing** [comment]
Oh, dart:math does look promising - it already has a Rectangle class.

**Comment by zoechi** [comment]
Sounds like there is no change planned?
Is this issue still relevant?

**Comment by markusaksli-nc** [comment]
Closing since this no longer seems relevant. Feel free to reopen if this isn't the case.
