### ISSUE TITLE
Linux firebase_release_smoke_test failing with gsutil error

### ISSUE THREAD

**Issue by drewroengoogle** [flutter/flutter#120111]
Failures can be seen here: https://ci.chromium.org/p/flutter/builders/prod/Linux%20firebase_android_embedding_v2_smoke_test

When running the `gsutil cp` step, the output is:
```
CommandException: 
Downloading this composite object requires integrity checking with CRC32c,
but your crcmod installation isn't using the module's C extension, so the
hash computation will likely throttle download performance. For help
installing the extension, please see "gsutil help crcmod".

To download regardless of crcmod performance or to skip slow integrity
checks, see the "check_hashes" option in your boto config file.

NOTE: It is strongly recommended that you not disable integrity checks. Doing so
could allow data corruption to go undetected during uploading/downloading.
```

**Comment by christopherfujino** [comment]
This is harmless warning output. The build is failing because it returns 1, and there doesn't appear to be any logging to give a clue to why.

Seeing it on multiple firebase tests:
- https://ci.chromium.org/p/flutter/builders/try/Linux%20firebase_abstract_method_smoke_test/45153?
- https://ci.chromium.org/p/flutter/builders/try/Linux%20firebase_android_embedding_v2_smoke_test/45141?

**Comment by drewroengoogle** [comment]
I noticed the failing builds are all using the latest version of `gsutil`, while the latest green builds are using a version of `gsutil` that is about [2 years old](https://chrome-infra-packages.appspot.com/p/infra/3pp/tools/gsutil/+/cVYmHNtHsJQ9ms5QdNCq9iGaSODy2HNqLfDaZey73vgC). I'm trying to see why the build wasn't using the most recent version before, and what changed to cause the most recent version to be used now.

**Comment by christopherfujino** [comment]
> I also noticed the failing builds are all using the latest version of `gsutil`, while the latest green builds are using a version of `gsutil` that is about [2 years old](https://chrome-infra-packages.appspot.com/p/infra/3pp/tools/gsutil/+/cVYmHNtHsJQ9ms5QdNCq9iGaSODy2HNqLfDaZey73vgC). I'm trying to see why the build wasn't using the most recent version before, or what changed to cause the most recent version to be used now.

oh, that's really weird

**Comment by drewroengoogle** [comment]
I've opened a bug with the depot_tools team, as the failure is occurring from an api call to depot_tools/gsutil which worked a couple of hours ago but seems to have regressed.

**Comment by drewroengoogle** [comment]
https://flutter-review.googlesource.com/c/recipes/+/38621

**Comment by drewroengoogle** [comment]
Rerunning all failing tests now, as the first retry was successful!

**Comment by drewroengoogle** [comment]
Tree is open again. Closing issue, feel free to open if this appears again!
