### ISSUE TITLE
Share WebGL Context Across Multiple Surfaces to Avoid Maximum WebGL Context Issues

### ISSUE THREAD

**Issue by jezell** [flutter/flutter#120156]
## Use case

Because browsers limit the number of active WebGL contexts, it's not a good idea for any app to create more than one of them, let alone an undefined number of them. Because the current renderer is wasteful with WebGL resources, any app that embeds any HTML elements inside a view can quickly exhaust the available web GL contexts, which can make this useful feature of flutter on web hard to use in practice. 

## Proposal

Don't create more than one WebGL context in the first place so that users don't bump up against these limits by creating additional layers. Here's an example of a javascript framework that virtualizes webGL contexts to accomplish this:

https://github.com/greggman/virtual-webgl

All of the WebGL rendering can be done with a single context, and then the buffers can be drawn to 2d canvas elements for each surface. While some browsers do limit the amount of canvas memory that apps can use, it's a lot harder to run out of 2d canvas memory than it is to burn through 8 WebGL contexts. This strategy would ensure that a single flutter app only ever uses a single webgl context and be a big improvement to engine reliability for scenarios where people need to mix and match flutter rendered layers with HTML layers.

**Comment by yjbanov** [comment]
Thanks for writing up the proposal. This is a cool idea. A more modern version of this could be based on a `OffscreenCanvas` singleton that fans out into multiple `ImageBitmapRenderingContext`s. Ultimately WebGPU will fix this properly, but this has come up enough that we might want to look into a temporary solution, if it doesn't hurt performance too much.

**Comment by xtyxtyx** [comment]
The PR https://github.com/flutter/engine/pull/39484 is usable now. For comparison I compiled a demo app with both the current engine implementation and the modified engine that paints overlay to canvas2d:

WebGL overlay: https://flutter-overlay-gl.pages.dev
Canvas2D overlay: https://flutter-overlay-2d.pages.dev

On chromium based browsers both CPU and GPU time are nearly the same between the two implementations:

![CleanShot 2023-02-10 at 20 48 48@2x](https://user-images.githubusercontent.com/15033141/218096431-8e8901f5-b035-468f-8520-41fe7d77ee3b.png)

![CleanShot 2023-02-10 at 20 50 23@2x](https://user-images.githubusercontent.com/15033141/218096665-eae3bb62-a208-498c-ad6f-0e5c5c8dd0ab.png)


However, Safari and Firefox don't seem to have a fast path to drawImage from canvas to canvas. The `drawImage` call takes around 50~100ms in my test environment:

<img width="1489" alt="CleanShot 2023-02-10 at 20 51 27@2x" src="https://user-images.githubusercontent.com/15033141/218096808-5317f5d5-e3ed-42ef-bc56-c5a933c3169c.png">

<img width="1486" alt="CleanShot 2023-02-10 at 20 52 48@2x" src="https://user-images.githubusercontent.com/15033141/218097060-5a93dfbf-70ff-4b42-b526-df6018f0b1df.png">


I also tried to use `ImageBitmapRenderingContext` and `ImageBitmap` to see if there would be any difference. After switching to `ImageBitmapRenderingContext`, the CPU usage on Chrome increased slightly but it can still render at 60fps. On Safari `ImageBitmapRenderingContext` doesn't seem to help, `createImageBitmap` causes significant frame rate drop.

**Comment by jezell** [comment]
Awesome!

**Comment by jezell** [comment]
Firefox just pushed out GPU accelerated canvas:

It is default on MacOS / Linux as of a few days ago:

https://www.mozilla.org/en-US/firefox/110.0/releasenotes/

Would guess whether you are using 110 on mac or linux (or have it toggled on manually on Windows) would impact the rendering. They are tracking bugs here if there is a slowdown compared to the old renderer: 

https://bugzilla.mozilla.org/show_bug.cgi?id=1741501

**Comment by jezell** [comment]
Can also confirm Firefox drawImage takes a while, looks like it's tracked in the issue tracker:

https://bugzilla.mozilla.org/show_bug.cgi?id=1163426

Maybe there could be a flag to opt in to this behavior. If there was such a flag, perhaps it could be a threshold for when this behavior is enabled, for example the default could be to only turn it on in Safari and FF if greater than a certain number of webgl contexts would be created. A dropped frame rate is probably still better than the renderer barfing and the app crashing.

**Comment by Hixie** [comment]
There was a PR written to solve this issue (see link below) but unfortunately it was not completed so the PR has been closed. If anyone would like to start from that PR and apply the review comments and drive this PR to completion, you are definitely welcome to do so!

PR: https://github.com/flutter/engine/pull/39484

**Comment by yjbanov** [comment]
@harryterkelsen landed the [single GL context redesign](https://github.com/flutter/engine/pull/47241) 2 weeks ago, so I think this particular issue is fixed. Now you should be able to set the value of `canvasKitMaximumSurfaces` to a bigger number without running into the browser's WebGL context limit. However, the default overlay limit remains in place for now, since overlays still have impact on memory usage. To fix that, we'll need a separate optimization that reduces the need for overlays. More details here:

https://docs.google.com/document/d/1aCIOEEYe31HqCaCGUKsAmUu9T0U6o2zUMGpqdPEdJoQ/edit?usp=sharing

I filed https://github.com/flutter/flutter/issues/137953
