### ISSUE TITLE
RenderSliverFixedExtentBoxAdaptor can call parentData on null in underflow situation

### ISSUE THREAD

**Issue by collinjackson** [flutter/flutter#12011]
## Steps to Reproduce

[`insertAndLayoutLeadingChild`](https://github.com/flutter/flutter/blob/bfa788512eaa1970022f58f4f5e2389f7bd39ce9/packages/flutter/lib/src/rendering/sliver_multi_box_adaptor.dart#L375) can return null in underflow situations.

However, [RenderSliverFixedExtentBoxAdaptor](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/rendering/sliver_fixed_extent_list.dart#L151) calls `insertAndLayoutLeadingChild` and then calls `parentData` on the result, assuming that it's not null. Probably we should guard against underflow here and break.

The error produced is 
```
NoSuchMethodError: The getter 'parentData' was called on null
```

I'm not sure if the error is a silent one or if functionality is affected.

Full stack trace:

```
hooks.dart in _drawFrame at line 75
hooks.dart in _invoke at line 88
Called from: zone.dart in _CustomZone.runGuarded
binding.dart in BindingBase&SchedulerBinding.handleDrawFrame at line 643
binding.dart in BindingBase&SchedulerBinding._invokeFrameCallback at line 695
binding.dart in BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding._handlePersistentFrameCallback at line 189
binding.dart in BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding&WidgetsBinding.drawFrame at line 504
binding.dart in BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding.drawFrame at line 251
object.dart in PipelineOwner.flushLayout at line 1056
object.dart in RenderObject._layoutWithoutResize at line 1767
viewport.dart in RenderViewport.performLayout at line 823
viewport.dart in RenderViewport._attemptLayout at line 899
viewport.dart in RenderViewportBase.layoutChildSequence at line 248
object.dart in RenderObject.layout at line 1892
sliver_fixed_extent_list.dart in RenderSliverFixedExtentBoxAdaptor.performLayout at line 151
Called from: object_patch.dart in Object.noSuchMethod
```

I don't have a reduced test case for this yet, but we should probably try to write a test as part of fixing the bug.

## Flutter Doctor

[✓] Flutter (on Mac OS X 10.12.6 16G29, locale en-US, channel unknown)
    • Flutter at /Users/jackson/git/flutter
    • Framework revision c925b4ca22 (7 days ago), 2017-09-01 06:14:35 -0700
    • Engine revision 29e0c1c281
    • Tools Dart version 1.25.0-dev.11.0

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.1)
    • Android SDK at /Users/jackson/Library/Android/sdk/
    • Platform android-26, build-tools 26.0.1
    • ANDROID_HOME = /Users/jackson/Library/Android/sdk/
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.3.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3.3, Build version 8E3004b
    • ios-deploy 1.9.1
    • CocoaPods version 1.3.1

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.2.2)
    • Flutter plugin version 16.0
    • Dart plugin version 172.3757.55

[✓] Connected devices
    • iPhone SE • 7072C907-DBAD-44FE-8F40-0257442C51D9 • ios • iOS 10.3 (simulator)

**Comment by collinjackson** [comment]
@Hixie I wonder if this could be related to the changes you made to `insertAndLayoutLeadingChild` in #11010

**Comment by Hixie** [comment]
I don't see how it can return null in that specific case, though. We know that we're only inserting indexes that are valid at that point in the code, in theory...
