### ISSUE TITLE
[CP][web] Fix paths fetched by flutter.js

### ISSUE THREAD

**Issue by mdebbar** [flutter/flutter#120197]
### issue_link

https://github.com/flutter/flutter/issues/116360

### Commit Hash

3bf7960

### Target

stable

### pr_link

https://github.com/flutter/flutter/pull/120195

### Impacted Users

All flutter web devs that use PathUrlStrategy

### Impact Description

The flutter web app won't load if accessed through any path other than `/`.

### Workaround

Yes, there's a workaround that requires messing with the build output files. They basically need to fork the `flutter.js` file, apply the fix there, and load the forked file instead of the flutter-tool-generated one.

Although the workaround fixes the issue, I don't recommend it because the app won't pick up any future changes that we make in `flutter.js`, which could lead to mysterious bugs that are hard to track.

### Risk

low

### Test Coverage

yes

### Validation Steps

1. Create a sample app.
2. Use `PathUrlStrategy`.
3. Load the app at a non-root path (e.g. `http://localhost:xxxxx/a/b/`)
4. The app should load and work.

**Comment by itsjustkevin** [comment]
@yjbanov and @eyebrowsoffire could you take a look at this cherry-pick?

**Comment by yjbanov** [comment]
LGTM

**Comment by mdebbar** [comment]
@itsjustkevin what are the next steps to get the cherry-pick approved and merged? I see a few other CPs got the `cp: approved` and they were filed in the same time frame as this CP request. If there's anything else I need to do, please let me know.

**Comment by itsjustkevin** [comment]
Nothing more!  It is queued for the next train.
