### ISSUE TITLE
Codelab, Your First Flutter App, semanticsLabel prop doesn't work

### ISSUE THREAD

**Issue by Svengineering** [flutter/flutter#120132]
Doing the codelab tutorial https://codelabs.developers.google.com/codelabs/flutter-codelab-first#4.

For improving accessibility you're adviced in this codelab to add `semanticsLabel: pair.asPascalCase` as prop to the text of the `Card` widget in order to prevent misspelling of a random word pair when using a screenreader.

Issue: the expression `pair.asPascalCase` doesn't work for me but `${pair.first} ${pair.second}` does. (for example the pair "gross" "lawn" will be misspelled if I use `semanticsLabel: pair.asPascalCase`)

- on Android 12
- moto g(60)s
- using "TalkBack" as screenreader
- Text-To-Speech-Setting -> setting "language" set to "English (UK)"
- Android OS user language is German

**Comment by Svengineering** [comment]
Another misspelled example is the pair "Tall" and "Ice". 

It's spelled like in "malice" with `semanticsLabel: pair.asPascalCase` but sounds correct with `semanticsLabel: ${pair.first} ${pair.second}`

**Comment by domesticmouse** [comment]
@filiph another one for ya 😏

**Comment by filiph** [comment]
Thanks for the report, @Svengineering. This makes our previous guidance on this topic wrong. I'll check if there are any outstanding places where we say that Pascal case works with screen readers. And I'll fix this one.

**Comment by domesticmouse** [comment]
@filiph ping =)
