### ISSUE TITLE
Engine artifacts should include iOS dSYM files for Sentry symbolication

### ISSUE THREAD

**Issue by collinjackson** [flutter/flutter#12012]
## Steps to Reproduce

If you try to integrate the native iOS Sentry SDK in a Flutter app, it shows a warning for a missing optional debug symbol file

```
{
  "image_arch": "arm64",
  "image_uuid": "60c0470c-7643-3f23-8e7c-a34c32c00d2a",
  "message": "None",
  "image_path": "/private/var/containers/Bundle/Application/D77E1B62-16F2-4350-81EF-364171737D44/Runner.app/Frameworks/Flutter.framework/Flutter"
}
```

I think that the issue is that the Flutter engine release builds are stripped and the dSYM files are not automatically created by GYP. The build process needs to run a command like this:

`dsymutil --out=out/ios_release/Flutter.framework.dSYM out/ios_release/Flutter.framework/Flutter`

See the [WebRTC iOS libs build script](https://chromium.googlesource.com/external/webrtc/+/3d21e23df22d885b6a58720bec0f131391d40508/webrtc/build/ios/build_ios_libs.sh) for an example of this in another project.

I think the next steps are:

- [ ] update build script to create a dSYM folder for stripped builds
- [ ] make sure that the script that uploads artifacts.zip to cloud storage includes the dSYM folder
- [ ] I follow the instructions at https://github.com/flutter/engine/wiki/Symbolicating-production-crash-stacks/ to try to get the artifacts, verify that dSYM files appear there
- [ ] roll engine

I can help with these steps to test it out with the Posse app:

- [ ] update goposse/flutter to point to the rolled engine
- [ ] create a new app release in Sentry
- [ ] try manually uploading the files with a command like`$ sentry-cli upload-dsym /path/to/Flutter.framework.dSYM/`
- [ ] confirm that the Sentry warning is resolved

Finally

- [ ] add instructions to flutter/sentry showing how to add these files to a release, either from the local cache or by navigating to cloud storage and downloading them.

## Flutter Doctor

[✓] Flutter (on Mac OS X 10.12.6 16G29, locale en-US, channel unknown)
    • Flutter at /Users/jackson/git/flutter
    • Framework revision c925b4ca22 (7 days ago), 2017-09-01 06:14:35 -0700
    • Engine revision 29e0c1c281
    • Tools Dart version 1.25.0-dev.11.0

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.1)
    • Android SDK at /Users/jackson/Library/Android/sdk/
    • Platform android-26, build-tools 26.0.1
    • ANDROID_HOME = /Users/jackson/Library/Android/sdk/
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.3.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3.3, Build version 8E3004b
    • ios-deploy 1.9.1
    • CocoaPods version 1.3.1

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.2.2)
    • Flutter plugin version 16.0
    • Dart plugin version 172.3757.55

[✓] Connected devices
    • iPhone SE • 7072C907-DBAD-44FE-8F40-0257442C51D9 • ios • iOS 10.3 (simulator)

**Comment by chinmaygarde** [comment]
Engine artifacts for iOS are not stripped. Instead, we rely on Xcode to strip the same before the application is packaged and verified for submission to the store. Users are free to generate the `.dSYM` files themselves and upload them to third-party services as necessary (or not).

**Comment by collinjackson** [comment]
I talked to Chinmay to get clarification, and what he was suggesting was for developers to manually run a command like this:

```
dsymutil --out=Flutter.framework.dSYM /Users/jackson/git/flutter/bin/cache/artifacts/engine/ios-release/Flutter.framework/Flutter
```

However when I did that, I got errors:

```
warning: (x86_64) /tmp/lto.o unable to open object file: No such file or directory
warning: (arm64) /b/build/slave/Mac_Engine/build/src/out/ios_release/obj/third_party/libjpeg-turbo/libjpeg/jsimd_arm64_neon.o unable to open object file: No such file or directory
warning: (arm64) /tmp/lto.o unable to open object file: No such file or directory
warning: no debug symbols in executable (-arch x86_64)
warning: no debug symbols in executable (-arch arm64)
```

It looks like this command needs to be run on the slave and can't be run by end users. We should probably do it on the slave and only for ios-release builds (because the dSYM files will add 200-300 MB to the artifacts zip).

**Comment by Hixie** [comment]
@chinmaygarde Is this something you are working on at the moment? (If not, please unassign yourself. Thanks!)

**Comment by Hixie** [comment]
@xster do you know if this is still something Posse is looking for? If so, is it something you'd be interested in working on?

**Comment by xster** [comment]
It is. Though not necessarily for this quarter. Adding to my list

**Comment by Hixie** [comment]
@xster We're removing this from the critical list based on your last comment; let me know if that's not right. Thanks!

**Comment by johnfesa** [comment]
Mulligan ran into a problem where we'd really have benefitted from having symbolication for the Flutter engine on iOS; it cost us significant engineering time while triaging crash reports.

**Comment by goderbauer** [comment]
I am working on generating the dSYM files.

**Comment by eseidelGoogle** [comment]
Some of these instructions probably belong in https://github.com/flutter/engine/wiki/Symbolicating-production-crash-stacks (and/or some sort of helper command in `flutter` tool)?

**Comment by johnfesa** [comment]
Thanks, Michael. We'll attempt to use the symbols once the Flutter engine rev you quoted is rolled in.

**Comment by Hixie** [comment]
@johnfesa Please do let us know what further you would like from us on this front once you've tried using the symbols. Thanks!

**Comment by Hixie** [comment]
This is technically done but we still need to update the wiki to explain how to obtain these files and what to do with them.

**Comment by goderbauer** [comment]
Relevant to the topic: With #22245 we are also stripping debug symbols from `App.framework` to reduce its size. A dSYM file with the debug information is created under ` build/aot/App.dSYM`.

**Comment by johnfesa** [comment]
It would be great to get these .dSYM files automatically uploaded to the Google internal symbol server as part of the build step.

**Comment by goderbauer** [comment]
@johnfesa That would have to be added to Google's internal Flutter infrastructure (@mehmetf FYI).

**Comment by goderbauer** [comment]
Documentation has been added to https://github.com/flutter/engine/wiki/Symbolicating-production-crash-stacks#ios.

With that, this bug should be resolved.

**Comment by eseidelGoogle** [comment]
Ad we continue to remove symbols from production builds (which I support), we're definitely going to need to continue to automate more of the symbolication process (both Google-specific tooling, and the universal `flutter` tooling).

Thanks for doing this @goderbauer!

**Comment by goderbauer** [comment]
@eseidel Agreed. I filed a follow-up bug for that as discussed during the triage meeting: https://github.com/flutter/flutter/issues/22313
