### ISSUE TITLE
Support Welsh for Material Localizations

### ISSUE THREAD

**Issue by thkim1011** [flutter/flutter#120124]
Internal bug: b/256596915

An internal customer requires Welsh to be a supported language in Material. I'll be using this thread as the tracking issue.

**Comment by thkim1011** [comment]
Just as an update, the internal localizations team at Google have started the process for getting translations.

**Comment by thkim1011** [comment]
Still waiting on the internal localizations team to work out translations for Flutter.

**Comment by xster** [comment]
@thkim1011 could you give us another update on the translation status?

**Comment by thkim1011** [comment]
Still waiting on translations :\.

**Comment by goderbauer** [comment]
Triage update: There's a pending PR for this: https://github.com/flutter/flutter/pull/123575
