### ISSUE TITLE
[in_app_purchase] cannot verify PurchaseDetails verificationData.serverVerificationData received

### ISSUE THREAD

**Issue by mawjappdev** [flutter/flutter#120180]
Hi! I have been trying to implement auto-renewable subscriptions using the in_app_purchase package. I have followed all the set-up instructions available on the pub dev and app store. While attempting to verify my purchase, I keep receiving a 21002 status from https://sandbox.itunes.apple.com/verifyReceipt on postman on passing verificationData.serverVerificationData in the request body. 

According to this 
**Expected results:** an object of "receipt" from Apple 

**Actual results:** { status: 21002} // implies malformed base64 encoded receipt data

While testing out other sample receipts as seen here, https://stackoverflow.com/questions/33843281/apple-receipt-data-sample, the correct response is received on Postman. But when I pass verificationData.serverVerificationData generated using the purchaseDetails object, the serverVerificationData is much smaller than seen in the previous example and a status response of 21002 is received.

<details>
<summary>Code sample</summary>

```
InAppPurchase.instance.buyNonConsumable( purchaseParam:purchaseParam);

Future<bool> _verifyPurchase(PurchaseDetails purchaseDetails) async {
    await apple_verify_receipt(
          verificationData:
              purchaseDetails.verificationData.serverVerificationData);
}
```

</details>

**Comment by eggapple1220** [comment]
many people facing the same issue , my old receipt work , but new one failed
https://developer.apple.com/forums/thread/724587?page=1#744330022

**Comment by darshankawar** [comment]
@mawjappdev 
Please check similar issue discussed in [this](https://stackoverflow.com/questions/72249340/understand-the-serververificationdata-in-app-purchase-flutter) SO link along with underlying comments and see if it helps in your case.

**Comment by mawjappdev** [comment]
> @mawjappdev Please check similar issue discussed in [this](https://stackoverflow.com/questions/72249340/understand-the-serververificationdata-in-app-purchase-flutter) SO link along with underlying comments and see if it helps in your case.

Thank you for your response. From my understanding, in this post the problem seems to be on the server side (python) as they did not pass the receipt data in the correct format. I am using NodeJs on the backend, however I am unable to directly validate purchaseDetails.verificationData.serverVerificationData (received from flutter) with the sandbox api on postman. 

For more context: 
I have already set up the .storekit file in Xcode and I'm currently testing IAP subscriptions with products from the AppStore in a sandbox environment. This is testing is done on a real device.

- Are there any further steps I may be missing before I attempt to validate receipts with Apple?

**Comment by darshankawar** [comment]
@mawjappdev 
I think looking at this Apple forum's thread : https://developer.apple.com/forums/thread/724587?page=1#744330022, it looks like an issue from Android native side and not from Flutter's plugin, so I suggest you to share your findings in that thread and follow-up in it for further resolution.

I am going ahead and closing this as not a plugin issue. If you disagree, write in comments and I'll reopen it.
