### ISSUE TITLE
Command PhaseScriptExecution failed with a nonzero exit code flutter with xcode 13.2.1

### ISSUE THREAD

**Issue by alsayedabdelbaqeyahmed** [flutter/flutter#120181]
i try to build an ios app but I face this error "Command PhaseScriptExecution failed with a nonzero exit code"
this my code out put 

" "../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/modal_bottom_sheet-2.0.0/lib/src/bottom_sheet.dart:303:28: Error: Couldn't find constructor 'VelocityTracker'.
        _velocityTracker = VelocityTracker();
                           ^^^^^^^^^^^^^^^
Failed to package /Users/sayed/Desktop/altrapay.
Command PhaseScriptExecution failed with a nonzero exit code ""

and my flutter doctor is 
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.10, on macOS 11.6 20G165 darwin-x64, locale en-EG)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] IntelliJ IDEA Community Edition (version 2022.3)
[✓] VS Code (version 1.75.0)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

• No issues found!
what is should do

**Comment by exaby73** [comment]
Looks like `modal_bottom_sheet` was updated to a newer version without the `VelocityTracker`. See https://pub.dev/packages/modal_bottom_sheet/changelog. This is not an issue with Flutter. Therefore, I am closing it. Thank you

**Comment by alsayedabdelbaqeyahmed** [comment]
Thanks for your help but the app did not contain any package called model bottom sheet

**Comment by alsayedabdelbaqeyahmed** [comment]
> Looks like `modal_bottom_sheet` was updated to a newer version without the `VelocityTracker`. See https://pub.dev/packages/modal_bottom_sheet/changelog. This is not an issue with Flutter. Therefore, I am closing it. Thank you

Thanks for your help but the app is not cantain any package called model bottom sheet

**Comment by exaby73** [comment]
```
../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/modal_bottom_sheet-2.0.0/lib/src/bottom_sheet.dart:303:28: Error: Couldn't find constructor 'VelocityTracker'.
_velocityTracker = VelocityTracker();
^^^^^^^^^^^^^^^
Failed to package /Users/sayed/Desktop/altrapay.
Command PhaseScriptExecution failed with a nonzero exit code
```

From the stack trace, `modal_bottom_sheet` is being used. Please raise an issue with the package author as this is not an issue with Flutter
