### ISSUE TITLE
[CP] Avoid animation jank by setting FlutterViewController backgroundColor to clearColor (stable)

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#120130]
### issue_link

https://github.com/flutter/flutter/issues/103847

### Commit Hash

https://github.com/flutter/engine/commit/1b132e4

### Target

stable

Beta CP request at https://github.com/flutter/flutter/issues/120139

### pr_link

https://github.com/flutter/engine/pull/39436

### Impacted Users

iOS end users on high-end iPhones

### Impact Description

On certain iPhones (iPhone 13 and 14 Pro, Pro Max) iOS apps are janky. This very simple one-line fix seems to resolve it on these devices.

### Workaround

No.

### Risk

low

### Test Coverage

yes

### Validation Steps

Run a Flutter app with a scrolling list view on an iPhone 13/14 Pro/Pro Max and scroll to see jank.  On this fix scrolling is smooth.

**Comment by itsjustkevin** [comment]
@jonahwilliams could you take a look at this cherry-pick?

**Comment by jonahwilliams** [comment]
LGTM

**Comment by itsjustkevin** [comment]
Thanks as always @jonahwilliams!

**Comment by jmagman** [comment]
@itsjustkevin should I make another PR/issue for the beta candidate?

**Comment by itsjustkevin** [comment]
@jmagman we have not built the new beta branch yet, but as the original PR was merged after the cutoff, we will need to pick it to beta also.

**Comment by jmagman** [comment]
Created https://github.com/flutter/flutter/issues/120139 to track the beta hotfix, I will create the PR after the beta branch is tagged.

**Comment by jmagman** [comment]
This is available in 3.7.2 https://github.com/flutter/flutter/pull/120263
