### ISSUE TITLE
Determine how to avoid windows update screens on devicelab machines

### ISSUE THREAD

**Issue by yusuf-goog** [flutter/flutter#120106]
@kentnguyen99 fairly regularly, windows will have an update available which causes our windows swarming bot machines in the devicelab to go offline, because the update screen blocks logging into the system till it is cleared.

Please investigate if there is a way to make these screen not show up, or, auto cancel them.

**Comment by kentnguyen99** [comment]
I disabled services not to run updates and changed registry entry not to update for 35 days on all Win-1 through Win-6 machines, there is no permanent disabling the Windows updates completely.

**Comment by yusuf-goog** [comment]
Is there a command line we can run on schedule to push that 35 day window out?

**Comment by kentnguyen99** [comment]
I did a lot of searching on the website and did not find any Windows commands line available that can run schedule push out more 35 days.

**Comment by yusuf-goog** [comment]
@kentnguyen99 have you seen any windows bots go down for this reason in the last few months?

**Comment by kentnguyen99** [comment]
win-2  went offline because Windows was prompted to upgrade Windows 11.  I made some changes in Regedit, hopely it won't prompt to upgrade again.

**Comment by yusuf-goog** [comment]
ok, then closing this issue.

**Comment by kentnguyen99** [comment]
Adding some changes/condition in the Windows Registry on all Windows machines; Hopefully, it won't prompt to upgrade again in future.
