### ISSUE TITLE
flutter desktop app crashes

### ISSUE THREAD

**Issue by JonathanGit** [flutter/flutter#120158]
My flutter desktop should crash, but I did not analyze the specific problem from the dump file. Now I upload the [dump file](https://github.com/flutter/flutter/files/10672152/63d508df7710458c9e68b09211b0f52b1.zip), and [dll file](https://github.com/flutter/flutter/files/10672157/flutter_windows.zip). Please help me to analyze the specific crash stack? Thanks

**Comment by exaby73** [comment]
Hello @JonathanGit. Thank you for filing this issue. Can you please provide the following information?

- A [complete and minimal, reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example). Ideally, a single `main.dart` file that can be run directly.
- The output of `flutter doctor -v`
- The output of `flutter run -v`

Please provide the information in the form of text. See how to make collapsible sections with Markdown [here](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-collapsed-sections).
