### ISSUE TITLE
Add scale back option to toImageSync to reduce the image to original size.

### ISSUE THREAD

**Issue by jdevp** [flutter/flutter#120120]
I'm working on a screen recording app in Flutter. In order to keep the quality of the captured screen image, I have to scale the image as shown below. However, it makes the image data very large. How can I reduce the data size (scale back to the original size) before saving it to a file?

```
double dpr = ui.window.devicePixelRatio;
    final boundary =
        key.currentContext!.findRenderObject() as RenderRepaintBoundary;
         return getBufferSync(key);
    }
       ui.Image image = boundary.toImageSync(pixelRatio: dpr);
var rawBytes = await image.toByteData(format: ui.ImageByteFormat.rawRgba);
    Uint8List uData = rawBytes!.buffer.asUint8List();
```

If it is possible, please add the option to scale back to original size. If not, is there a work around to reduce the data while keeping the quality before saving it to a file?

toImageSync(dpr: dpr, size: original_size)

**Comment by jonahwilliams** [comment]
you can reduce the scale of  the image by reducing the dpr - this is all the dpr is controlling:

https://github.com/flutter/flutter/blob/d4c74858fd2c9e701df0b4fca424914c357c2d81/packages/flutter/lib/src/rendering/layer.dart#L1420

**Comment by jdevp** [comment]
Thanks for the quick response. Reduce the dpr will produce a bad quality image. Please read the following thread. It recommends to scale up the dpr. However, it doesn't say how to resize back to original size before saving to a file.
<-----
You're missing the device pixel ratio scaling which the framework is doing for you in the case of your custom paint. If you change your code to be like this:
    final MyCustomPainter p = MyCustomPainter(_counter);    ui.PictureRecorder recorder = ui.PictureRecorder();    Canvas canvas = Canvas(recorder);    // Make sure to apply scaling to the DPR of the window, since the framework will be scaling this picture normally in the layer tree    canvas.save();    canvas.scale(ui.window.devicePixelRatio);    p.paint(canvas, const Size(SIZE, SIZE));    canvas.restore();    final imageSize = (SIZE * ui.window.devicePixelRatio).floor();    recorder.endRecording().toImage(imageSize, imageSize).then((image) {      image.toByteData(format: ui.ImageByteFormat.png).then((ByteData? data) {        if (data != null) {          _image = data.buffer.asUint8List();          setState(() {});        }      });    });----->

Image recorded using PictureRecoder has poor quality · Issue #98953 · flutter/flutter


| 
| 
| 
|  |  |

 |

 |
| 
|  | 
Image recorded using PictureRecoder has poor quality · Issue #98953 · fl...

When using PictureRecoder on a canvas, store the result as Uint8List and display this list later using Image.mem...
 |

 |

 |




    On Monday, February 6, 2023 at 03:27:34 PM EST, Jonah Williams ***@***.***> wrote:  
 
 


you can reduce the scale of the image by reducing the dpr - this is all the dpr is controlling:

https://github.com/flutter/flutter/blob/d4c74858fd2c9e701df0b4fca424914c357c2d81/packages/flutter/lib/src/rendering/layer.dart#L1420
