### ISSUE TITLE
[CP] Infra changes to deprecate python2 from infra

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#120137]
### issue_link

N/A

### Commit Hash

* https://github.com/flutter/engine/commit/ba188d7ca2bfaf2af0d1e7be3eaadf24980dda87
* https://github.com/flutter/engine/commit/9cc2a8e8ff28f6bed5c670b344b101e3a0c12550
* https://github.com/flutter/engine/commit/aa0ff2173c6c07cc377b8c8118f006efb6030694

### Target

stable

### pr_link

* https://flutter-review.googlesource.com/c/recipes/+/38641
* https://flutter-review.googlesource.com/c/recipes/+/38680
* https://flutter-review.googlesource.com/c/recipes/+/38700
* https://flutter-review.googlesource.com/c/recipes/+/38582
* https://flutter-review.googlesource.com/c/recipes/+/38780

### Impacted Users

release engineering team

### Impact Description

Several CP to deprecate the use of python 2.7 as the dependency was removed from LUCI

### Workaround

N/A

### Risk

low

### Test Coverage

yes

### Validation Steps

Presubmit tests

**Comment by itsjustkevin** [comment]
Will we need to cherry-pick this into the beta branch once it's created?  I am assuming the point that we branch recipes will be before this change is merged.

CC: @CaseyHillers @XilaiZhang
