### ISSUE TITLE
ChoiceChip not expanding with IntrinsicWidth

### ISSUE THREAD

**Issue by cabbi** [flutter/flutter#120155]
## Steps to Reproduce
Execute `flutter run` on the code sample 
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: Scaffold(
        body: MyWidget(),
      ),
    );
  }
}

class MyWidget extends StatelessWidget {
  const MyWidget({super.key});

  @override
  Widget build(BuildContext context) {
    return Column(children: [
      IntrinsicWidth(
          child: Row(
        mainAxisAlignment: MainAxisAlignment.center,
        mainAxisSize: MainAxisSize.min,
        children: [
          Expanded(
              child: ElevatedButton(
            child: const Text('Larger Text'),
            onPressed: () {},
          )),
          Expanded(
              child: ElevatedButton(
            child: const Text('Text'),
            onPressed: () {},
          )),
        ],
      )),
      IntrinsicWidth(
          child: Row(
        mainAxisAlignment: MainAxisAlignment.center,
        mainAxisSize: MainAxisSize.min,
        children: const [
          Expanded(
              child: ChoiceChip(
            label: Text('Larger Text'),
            selected: false,
          )),
          Expanded(
              child: ChoiceChip(
            label: Text('Text'),
            selected: false,
          )),
        ],
      ))
    ]);
  }
}
```
**Expected results:**
The `ChoiceChip` having the same size as the two `ElevatedButton` does

**Actual results:** 
![image](https://user-images.githubusercontent.com/12030974/217153447-c2a56923-7e38-4927-ac73-ba69a0d71113.png)

<details>
<summary>flutter doctor -v</summary>

```
```

[√] Flutter (Channel stable,
    3.3.10, on Microsoft Windows
    [Version 10.0.22621.1105],
    locale en-CH)
    • Flutter version 3.3.10 on
      channel stable at
      c:\MySpace\Tools\flutter
    • Upstream repository
      https://github.com/flutter/f
      lutter.git
    • Framework revision
      135454af32 (8 weeks ago),
      2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[√] Android toolchain - develop
    for Android devices (Android
    SDK version 32.1.0-rc1)
    • Android SDK at
      C:\Users\fabio\AppData\Local
      \Android\sdk
    • Platform android-33,
      build-tools 32.1.0-rc1
    • Java binary at: C:\Program
      Files\Android\Android
      Studio\jre\bin\java
    • Java version OpenJDK Runtime
      Environment (build
      11.0.11+9-b60-7590822)
    • All Android licenses
      accepted.

[√] Chrome - develop for the web  
    • Chrome at C:\Program        
      Files\Google\Chrome\Applicat
      ion\chrome.exe

[√] Visual Studio - develop for
    Windows (Visual Studio        
    Community 2022 17.1.2)        
    • Visual Studio at C:\Program 
      Files\Microsoft Visual      
      Studio\2022\Community       
    • Visual Studio Community 2022
      version 17.1.32319.34       
    • Windows 10 SDK version      
      10.0.19041.0

[√] Android Studio (version       
    2021.1)
    • Android Studio at C:\Program
      Files\Android\Android Studio
    • Flutter plugin can be       
      installed from:
      
      https://plugins.jetbrains.co
      m/plugin/9212-flutter       
    • Dart plugin can be installed
      from:
      
      https://plugins.jetbrains.co
      m/plugin/6351-dart
    • Java version OpenJDK Runtime
      Environment (build
      11.0.11+9-b60-7590822)      

[√] VS Code (version 1.74.3)      
    • VS Code at
      C:\Users\fabio\AppData\Local
      \Programs\Microsoft VS Code 
    • Flutter extension version   
      3.58.0

[√] Connected device (3 available)
    • Windows (desktop) • windows 
      • windows-x64    • Microsoft
      Windows [Version
      10.0.22621.1105]
    • Chrome (web)      • chrome  
      • web-javascript • Google   
      Chrome 109.0.5414.120       
    • Edge (web)        • edge    
      • web-javascript • Microsoft
      Edge 108.0.1462.42

[√] HTTP Host Availability        
    • All required HTTP hosts are 
      available

• No issues found!
```
```

</details>

**Comment by huycozy** [comment]
Hi @cabbi
When enabling Flutter Inspector, I see the second `IntrinsicWidth` width is not full parent as the first one. You should handle this with your own implementation.

![Screenshot 2023-02-07 at 16 49 46](https://user-images.githubusercontent.com/104349824/217214557-d3059b82-3858-4cb9-9804-6ef810b25223.png)


Also, in order to increase the `ChoiceChip` width, you can wrap it by a `Container` with the preferred width (`double.infinity` for eg in this case)

![Screenshot 2023-02-07 at 17 03 33](https://user-images.githubusercontent.com/104349824/217214893-573c74bd-d3aa-4372-8f1f-856e57d276f6.png)

<details>
<summary>Sample code</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: Scaffold(
        body: MyWidget(),
      ),
    );
  }
}

class MyWidget extends StatelessWidget {
  const MyWidget({super.key});

  @override
  Widget build(BuildContext context) {
    return Column(children: [
      IntrinsicWidth(
        child: Row(
          mainAxisAlignment: MainAxisAlignment.center,
          mainAxisSize: MainAxisSize.min,
          children: [
            Expanded(
                child: ElevatedButton(
              child: const Text('Larger Text'),
              onPressed: () {},
            )),
            Expanded(
              child: ElevatedButton(
                child: const Text('Text'),
                onPressed: () {},
              ),
            ),
          ],
        ),
      ),
      IntrinsicWidth(
        child: Row(
          mainAxisAlignment: MainAxisAlignment.center,
          mainAxisSize: MainAxisSize.min,
          children: [
            Expanded(
              child: ChoiceChip(
                label: Container(width: double.infinity, child: Text('Larger Text')),
                selected: false,
              ),
            ),
            Expanded(
              child: ChoiceChip(
                label: Container(width: double.infinity, child: Text('Text')),
                selected: false,
              ),
            ),
          ],
        ),
      ),
    ]);
  }
}

```
</details>

It seems your question is best suited for support channels like StackOverflow, so please ask the same there for solutions if any.

Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it. Thank you!

**Comment by cabbi** [comment]
Hi, I did post same issue on [StackOverflow](https://stackoverflow.com/questions/75343155/choicechip-not-expanding-with-intrinsicwidth) in the past days but since there was no resolution I've "escalated" it here.

Since I'm quite new to Flutter I didn't know about Flutter Inspector. Now I know and will use it in the future.

Thanks you very much for solving my case.
