### ISSUE TITLE
Transitive package assets are breaking the build

### ISSUE THREAD

**Issue by yyoon** [flutter/flutter#12017]
When project "A" depends on project "B", where "B" has an asset defined that starts with `packages/<package_name>/...`, building project "A" crashes in the middle.

Based on my investigation, this seems to be caused by #11751. (cc/ @szakarias)

## Steps to Reproduce

From a parent directory,

1. `flutter create test_app`
1. `flutter create test_package`
1. Add `test_package` as a dependency in `test_app/pubspec.yaml`
    ```yaml
    dependencies:
      test_package:
        path: ../test_package
      flutter:
        sdk: flutter
    ```
1. Add an asset under `test_package/lib`
    `touch test_package/lib/test.txt`
1. Add this file in `test_package/pubspec.yaml`
    ```yaml
    flutter:
      uses-material-design: true
      assets:
        - packages/test_package/test.txt
    ```
1. Build `test_app`
    `cd test_app && flutter build apk`

The gradle build fails with the following crash log.

---
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter build flx --suppress-analytics --target lib/main.dart --output-file /usr/local/google/home/youngseokyoon/Programming/flutter_examples/test_app/build/app/intermediates/flutter/release/app.flx --precompiled --working-dir /usr/local/google/home/youngseokyoon/Programming/flutter_examples/test_app/build/app/intermediates/flutter/release/flx

## exception

FileSystemException: FileSystemException: Directory listing failed, path = '/usr/local/google/home/youngseokyoon/Programming/flutter_examples/test_package/packages/test_package/' (OS Error: No such file or directory, errno = 2)

```
#0      _Directory._fillWithDirectoryListing (dart:io-patch/directory_patch.dart:28)
#1      _Directory.listSync (dart:io/directory_impl.dart:202)
#2      _LocalFileSystemEntity&ForwardingDirectory.listSync (package:file/src/forwarding/forwarding_directory.dart:43)
#3      _AssetDirectoryCache.variantsFor (package:flutter_tools/src/asset.dart:407)
#4      _parseAssets (package:flutter_tools/src/asset.dart:452)
#5      AssetBundle.build (package:flutter_tools/src/asset.dart:136)
<asynchronous suspension>
#6      assemble (package:flutter_tools/src/flx.dart:110)
<asynchronous suspension>
#7      build (package:flutter_tools/src/flx.dart:79)
<asynchronous suspension>
#8      BuildFlxCommand.runCommand (package:flutter_tools/src/commands/build_flx.dart:44)
<asynchronous suspension>
#9      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:239)
<asynchronous suspension>
#10     BuildSubCommand.verifyThenRunCommand (package:flutter_tools/src/commands/build.dart:50)
<asynchronous suspension>
#11     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:181)
<asynchronous suspension>
#12     CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#13     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:276)
<asynchronous suspension>
#14     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#15     new Future.sync (dart:async/future.dart:222)
#16     CommandRunner.run (package:args/command_runner.dart:109)
#17     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:161)
#18     run.<anonymous closure> (package:flutter_tools/executable.dart:143)
<asynchronous suspension>
#19     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#20     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#21     _rootRun (dart:async/zone.dart:1120)
#22     _CustomZone.run (dart:async/zone.dart:1001)
#23     runZoned (dart:async/zone.dart:1467)
#24     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#25     run (package:flutter_tools/executable.dart:114)
<asynchronous suspension>
#26     main (package:flutter_tools/executable.dart:67)
<asynchronous suspension>
#27     main (file:///usr/local/google/home/youngseokyoon/Programming/fuchsia/lib/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
#28     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#29     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

## flutter doctor

```
[✓] Flutter (on Linux, locale en_US.UTF-8, channel unknown)
    • Flutter at /usr/local/google/home/youngseokyoon/Programming/fuchsia/lib/flutter
    • Framework revision c46347b6df (12 hours ago), 2017-09-07 22:52:36 -0700
    • Engine revision 2d7c30033d
    • Tools Dart version 1.25.0-dev.11.0

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at /usr/local/google/home/youngseokyoon/Android/Sdk
    • Platform android-25, build-tools 25.0.3
    • Java binary at: /opt/android-studio-2.3/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] Android Studio (version 2.3)
    • Android Studio at /opt/android-studio-2.3
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[-] IntelliJ IDEA Community Edition (version 2017.1)
    ✗ Flutter plugin version 13.1 - the recommended minimum version is 16.0.0
    • Dart plugin version 171.4424
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[✓] Connected devices
    • None

```

**Comment by yyoon** [comment]
cc/ @apwilson

**Comment by szakarias** [comment]
If the asset is referenced from the package itself you should specify the path relative to the`pubspec.yaml` file, that is in this case 
```yaml  
assets:
  - lib/test.txt
```
When specified in the `pubspec.yaml` of the package the assets will be bundled automatically with the app. 

If the package doesn't specify the assets itself you can choose which assets to bundle with the app by specifying them in the `pubspec.yaml` of the app. In this case you reference the assets as you did, that is 

```yaml
assets:
  - packages/test_package/test.txt
```

The docs for this can be found [here]( https://flutter.io/assets-and-images/#asset-images-in-package-dependencies). 

Thanks for the feedback, I'll go over the docs again to make it more clear. 

I am closing the issue, feel free to open it again if you have any other concerns or questions.

**Comment by yyoon** [comment]
Sorry for reopening, but I believe this is still an issue that needs to be resolved.

I understand your point that when referring to the asset in the same package, we should be just using relative paths from the project root. This was basically because I was trying (maybe too much) to provide you a minimal repro case.

So let me modify the scenario a little bit.

Project A depends on project B, and project B refers to an asset that is in project C using the `packages/` syntax, because project C doesn't specify the asset itself, which I think is a valid thing to do from B's perspective. With this setup, building A still fails with the exact same error that I provided in the original post.

**Comment by szakarias** [comment]
Fixed in  #12032.

**Comment by yyoon** [comment]
Thanks!

**Comment by szakarias** [comment]
Thanks for opening the issue!
