### ISSUE TITLE
[flutter_tools] Remove `--null-assertions` flag for web builds

### ISSUE THREAD

**Issue by nshahan** [flutter/flutter#120122]
When the support for the `--no-sound-null-safety` flag gets completely removed we should also remove `--null-assertions` because it only has meaning when running without sound null safety. It should get cleaned up for both the dev and production code paths in the flutter CLI tools.

See: https://github.com/dart-lang/sdk/issues/50711

cc @christopherfujino

**Comment by christopherfujino** [comment]
Thanks for filing this. I'm going to close this and update instead https://github.com/flutter/flutter/issues/118810 to include this (I'm working on a PR for this already).
