### ISSUE TITLE
Recipe led tests are picking up release candidate branch runs

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#120135]
Recipe led tests should be using main recipes.

Run:
https://luci-milo.appspot.com/raw/build/logs.chromium.org/flutter/led/flutter-try-builder_chops-service-accounts.iam.gserviceaccount.com/3f4abbc5ad760beeeb355cc19253868bf6ce986705a127c5a1de41bf74f53fbb/+/build.proto?server=chromium-swarm.appspot.com

![image](https://user-images.githubusercontent.com/54371434/217100058-98d6e3c6-1b49-4e37-9ad8-6a5b2d6d9a7d.png)

**Comment by drewroengoogle** [comment]
@godofredoc What command(s) did you use to run this? Anything ususual outside of the regular `led get-builder`?

**Comment by godofredoc** [comment]
This was triggered by led recipe testing:

* https://cs.opensource.google/flutter/recipes/+/main:recipes/recipes.py
* https://cs.opensource.google/flutter/recipes/+/main:recipe_modules/recipe_testing/

**Comment by godofredoc** [comment]
> Ah, so this is run on any recipes CL?

Yes, that is correct.

**Comment by drewroengoogle** [comment]
To summarize the problem - When opening a CL for recipes, the presubmit will look for any modified recipes, take the last green build, and replicate it using the modified recipe to make sure it is still passing. However, in some cases, the last green build is not on the same branch as the recipes CL is merging into, causing problems. In the case above, the last green build was on flutter-3.7-candidate.1, not main/master.

We need to change the testing to search for the last green build that is **on the same branch** as the CL is merging into.

**Comment by ricardoamador** [comment]
Related: https://github.com/flutter/flutter/issues/120287

**Comment by ricardoamador** [comment]
Waiting for release engineering to take a look at the pull request to fix this.
https://github.com/flutter/flutter/pull/120305 - fix pr

**Comment by drewroengoogle** [comment]
Finishing up a CL for this: need to write tests

**Comment by drewroengoogle** [comment]
^ This has been merged!

**Comment by drewroengoogle** [comment]
Closing, feel free to reopen
