### ISSUE TITLE
[CP] Avoid animation jank by setting FlutterViewController backgroundColor to clearColor (beta)

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#120139]
### issue_link

https://github.com/flutter/flutter/issues/103847

### Commit Hash

https://github.com/flutter/engine/commit/1b132e4

### Target

beta

Stable CP request at https://github.com/flutter/flutter/issues/120130

### pr_link

flutter/engine#39436 (that is off stable, will make a beta PR after it branches)

### Impacted Users

iOS end users on high-end iPhones

### Impact Description

On certain iPhones (iPhone 13 and 14 Pro, Pro Max) iOS apps are janky. This very simple one-line fix seems to resolve it on these devices.

### Workaround

No.

### Risk

low

### Test Coverage

yes

### Validation Steps

Run a Flutter app with a scrolling list view on an iPhone 13/14 Pro/Pro Max and scroll to see jank. On this fix scrolling is smooth.

**Comment by itsjustkevin** [comment]
Approving this based on approvals in https://github.com/flutter/flutter/issues/120130

**Comment by jmagman** [comment]
I believe this can be closed (correct me if I'm wrong @itsjustkevin), based on https://github.com/flutter/flutter/issues/120605 the beta candidate is [flutter-3.8-candidate.10](https://github.com/flutter/engine/tree/flutter-3.8-candidate.10) at https://github.com/flutter/engine/commit/2f2e2e27cb285f518fd30b837029a5cca44b2ae5, which already has the fix at https://github.com/flutter/engine/commit/1b132e4.

**Comment by itsjustkevin** [comment]
Correct!  Thank you @jmagman.
