### ISSUE TITLE
code labs 'Your first Flutter App' - documentation update

### ISSUE THREAD

**Issue by podrob** [flutter/flutter#120190]
https://codelabs.developers.google.com/codelabs/flutter-codelab-first#6

Step 7 'Add navigation rail' is missing the instruction to update the home reference within MaterialApp from `GeneratorPage()` to `MyHomePage()`. 

Without this change then the learner will not see the addition of the SafeArea and Expanded section. Suggest that the following instruction is added to the documentation: 

Make the following change:

lib/main.dart
`
class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return ChangeNotifierProvider(
      create: (context) => MyAppState(),
      child: MaterialApp(
        title: 'Namer App',
        theme: ThemeData(
          useMaterial3: true,
          colorScheme: ColorScheme.fromSeed(seedColor: Colors.red),
        ),
        home: MyHomePage(),     // ← Change to this.
      ),
    );
  }
}
`

**Comment by podrob** [comment]
I just realised what happened, I am using Visual Studio Code and decided not to copy and paste any code from the 'You first Flutter app' tutorial so did a refactor of `MyHomePage` to `GeneratorPage` which renamed the reference in MyApp MaterialApp widget also. 

My mistake, thank you for the very quick response and apologies for wasting your time.

**Comment by exaby73** [comment]
No issues @podrob :) Don't let this discourage you from raising issues if you see them
