### ISSUE TITLE
Scenario tests have become flaky

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#120239]
At around 1-2PM today the Scenario Unit tests in the engine started flaking. Generally the symptom seems to be a failure in the testWaitForFirstFrameTimeout unit tests. I've seen a few different error messages, one was just a timeout and one failed with an invalid engine configuration/missing build artifacts.

None of the recent flutter/engine changes seem relevant.

See https://ci.chromium.org/ui/p/flutter/builders/try/Mac%20Unopt/24989/overview

**Comment by jmagman** [comment]
Really wish we had screenshots https://github.com/flutter/flutter/issues/69436... Though realistically this one is likely a totally white or black screen.

**Comment by jonahwilliams** [comment]
This is still happening, recently blocking the last two skia rolls. The failures are fairly consistent:

```
Test Case '-[FlutterEngineTest testWaitForFirstFrameTimeout]' started.
2023-02-08 16:06:55.548972-0800 IosUnitTests[57766:304788] Failed to find assets path for "Frameworks/App.framework/flutter_assets"
2023-02-08 16:06:55.560407-0800 IosUnitTests[57766:305327] [VERBOSE-2:engine.cc(204)] Engine run configuration was invalid.
2023-02-08 16:06:55.561637-0800 IosUnitTests[57766:305327] [VERBOSE-2:shell.cc(606)] Could not launch engine with configuration.
2023-02-08 16:06:55.690395-0800 IosUnitTests[57766:305339] flutter: The Dart VM service is listening on http://127.0.0.1:50639/wE3XT9Fdgv4=/
<unknown>:0: error: -[FlutterEngineTest testWaitForFirstFrameTimeout] : Asynchronous wait failed: Exceeded timeout of 1 seconds, with unfulfilled expectations: "timeoutFirstFrame".
Test Case '-[FlutterEngineTest testWaitForFirstFrameTimeout]' failed (1.151 seconds).
```

Something that is building this test case or handling the artifacts has regressed. https://ci.chromium.org/ui/p/flutter/builders/try/Mac%20Unopt/25058/overview

**Comment by jason-simmons** [comment]
The `testWaitForFirstFrameTimeout` test is racy.

The test is not actually starting an application and rendering a frame.  It does create an engine and try to run it.  But the engine can not launch (as implied by the logs above about the invalid asset path and run configuration).

However, creating an engine and a shell does have the side effect of initializing Dart.  Dart startup will then launch other tasks such as starting the service isolate.

Meanwhile, the test calls `FlutterEngine.waitForFirstFrame`, which queues a background task that calls `Shell::WaitForFirstFrame` with a 100ms timeout.  There are no frames rendering, so `WaitForFirstFrame` will time out.  `FlutterEngine.waitForFirstFrame` will then queue a callback that wakes up the test.

The test is waiting for 1 second for this to complete.  But if the iOS simulator is busy with other tasks like Dart startup, then this could take longer.

Hopefully increasing the test's wait timeout will work around this.

**Comment by godofredoc** [comment]
Closing as @jonahwilliams PR seems to have fixed the issue.
