### ISSUE TITLE
Android defines test failing consistently on release branches.

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#120287]
The problem is the combination of these 3 dimensions:

* device_type:msm8952
* kvm:1
* machine_type:n1-standard-8

Example run:
https://ci.chromium.org/p/flutter/builders/prod/Linux_android%20android_defines_test/7096

@ricardoamador which of the dimensions is obsolete?

**Comment by ricardoamador** [comment]
No the target should be overriding the device_type from the platform definition. I will need to look at why this is happening. It passes consistently in presubmit.

**Comment by godofredoc** [comment]
The .ci.yaml file from the release candidate branch may be different from the one in main. https://github.com/flutter/flutter/blob/flutter-3.7-candidate.1/.ci.yaml

Maybe a missing cherry-pick?

**Comment by ricardoamador** [comment]
Can I add the changes directly to the candidate branch?

**Comment by godofredoc** [comment]
It is usually done through a CP from main to the release candidate branch. You can find the details here: https://github.com/flutter/flutter/wiki/Flutter-Cherrypick-Process

**Comment by ricardoamador** [comment]
Great! Thank you. I'll take care of this now.

**Comment by ricardoamador** [comment]
Ah I see. The use_emulator flag made it into the release branch but the supporting changes to handle that flag did not. Submitting the CP now.

**Comment by ricardoamador** [comment]
Okay this makes no sense. None of the changes to support emulators are in. Even in the ci.yaml! However the input shows that a flag is being used so it is not getting the same code as the release branch shows. In the ci.yaml linked above to the release branch it does not have the use_emulator flag. But in the task input linked above it is getting that flag.

**Comment by godofredoc** [comment]
This is related to how the scheduling works. Release candidate branches get the configurations for a given builder from the prod infra configs https://cs.opensource.google/flutter/infra/+/main:config/generated/flutter/luci/cr-buildbucket.cfg and injects the content of the local .ci.yaml

```
builders {
      name: "Linux_android android_defines_test"
      swarming_host: "chromium-swarm.appspot.com"
      dimensions: "cores:8"
      dimensions: "device_type:none"
      dimensions: "kvm:1"
      dimensions: "machine_type:n1-standard-8"
      dimensions: "os:Linux"
      dimensions: "pool:luci.flutter.prod"
````

**Comment by godofredoc** [comment]
I believe we can close this one.

**Comment by ricardoamador** [comment]
closing this as fixed.
