### ISSUE TITLE
Regression in average_gpu_usage in simple_animation_perf_ios

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#120207]
There have been two recent regressions since migrating to the iPhone 11 in the lab. The first one was small:

https://flutter-flutter-perf.skia.org/e/?begin=1672181480&end=1675553399&keys=X0d345e60408f7956175cccac38cc524f&requestType=0&selected=commit%3D32959%26name%3D%252Carch%253Dintel%252Cbranch%253Dmaster%252Cconfig%253Ddefault%252Cdevice_type%253DiPhone_11%252Cdevice_version%253Dnone%252Chost_type%253Dmac%252Csub_result%253Daverage_gpu_usage%252Ctest%253Dbackdrop_filter_perf_ios__timeline_summary%252C&xbaroffset=33206

We guessed that it was due to https://github.com/flutter/engine/pull/38989, but couldn't repro locally since the variance in gpu utilization is high.

This second one is larger:

https://flutter-flutter-perf.skia.org/e/?begin=1675463868&end=1675693416&keys=X0d345e60408f7956175cccac38cc524f&num_commits=50&request_type=1&xbaroffset=33206

There are two commits that seem like they might be related https://github.com/flutter/engine/pull/39172 and https://github.com/flutter/engine/pull/39359.

One reason GPU utilization might increase is that thanks to these changes, Flutter is now pushing frames at a higher rate. That would overall be a good thing. I'm filing this issue so that we can investigate whether that is the trade-off that we're making. Assigning @cyanglaz.

**Comment by jonahwilliams** [comment]
Looking at the commits in https://flutter-flutter-perf.skia.org/e/?begin=1675463868&end=1675693416&keys=X0de0ea40508c10467ea337e51588ebd4&selected=commit%3D33206%26name%3D%252Carch%253Dintel%252Cbranch%253Dmaster%252Cconfig%253Ddefault%252Cdevice_type%253DiPhone_11%252Cdevice_version%253Dnone%252Chost_type%253Dmac%252Csub_result%253Daverage_gpu_usage%252Ctest%253Dbackdrop_filter_perf_ios__timeline_summary%252C&xbaroffset=33206 , could it be the transparent background change too?

**Comment by zanderso** [comment]
Yes. I think that's https://github.com/flutter/engine/pull/39359 linked above.

**Comment by jonahwilliams** [comment]
oops, reading while tired. need coffee

**Comment by jonahwilliams** [comment]
I was not able to reproduce this issue on the device I have. @cyanglaz / @jmagman will need to investigate, or we can do a preemtive revert to see if devicelab metrics return to normal

**Comment by cyanglaz** [comment]
I wasn't able to reproduce the first one. I will check XCode instrument for GPU usage to see if I can find anything. 

I'm Investigating the 2nd regression now.

**Comment by cyanglaz** [comment]
https://github.com/flutter/engine/pull/39172 didn't have impact on the benchmark.

This is what I got when I revert https://github.com/flutter/engine/pull/39359: (iPhone 13pro)
`average_gpu_usage       23.04 (0.00%)   1.73 (0.00%)    13.33x`

The gpu_usage is 13.33x smaller, the opposite of the bench mark graph? Maybe setting background color to clearColor improved gpu usage on iPhone 13pro (reduced the nextDrawable time)?

The ci was running on iPhone 11, so maybe it actually behaves the opposite on a non-promotion device? 
I have an appointment after lunch, I don't have an 11 but I'll try on my X when I'm back.

**Comment by cyanglaz** [comment]
Tested on iPhone X:
`average_gpu_usage       25.55 (0.00%)   5.23 (0.00%)    4.88x`. 
Not as significant as iPhone 13pro but I do see a significant reduction of gpu usage. I'm not sure how the ci showed a complete opposite result.

Where can we see the iOS version of the iPhone 11? Both of my devices are iOS 16.2+

**Comment by jonahwilliams** [comment]
are we getting higher GPU utilization because we're pushing through more frames? Or is it just higher with no other observable effects?

I'm really uncertain how useful this measurement is. Unless there is some more concrete regression I'm inclined to accept the changes

**Comment by cyanglaz** [comment]
As @zanderso mentioned, I think high gpu usage while the app is animating is generally a good thing performance wise? Do we care about gpu life time? I don't have enough knowledge on this topic to know what other trade offs would be.

**Comment by cyanglaz** [comment]
>>are we getting higher GPU utilization because we're pushing through more frames? Or is it just higher with no other observable effects?

Maybe we can add a new measurement on total number of frames pushed?

**Comment by jonahwilliams** [comment]
we should be tracking that already, I'm not sure if that particular benchmark contains it.

**Comment by jonahwilliams** [comment]
If we have local results that show a change is an improvement in metrics we care about heavily - in this case frame time, I would trust that over benchmark results we don't know how to interpret.

**Comment by cyanglaz** [comment]
Added some other metrics including frame counts and I didn't see major differences. I don't know if we have better metrics to show janks. (A is after the PR, B is before the PR)

```
═════════════════════════╡ ••• Final A/B results ••• ╞══════════════════════════

Score   Average A (noise)       Average B (noise)       Speed-up
average_frame_build_time_millis 0.39 (0.00%)    0.40 (0.00%)    0.99x
worst_frame_build_time_millis   0.70 (0.00%)    2.19 (0.00%)    0.32x
90th_percentile_frame_build_time_millis 0.47 (0.00%)    0.47 (0.00%)    0.98x
99th_percentile_frame_build_time_millis 0.53 (0.00%)    0.55 (0.00%)    0.97x
average_frame_rasterizer_time_millis    8.26 (0.00%)    8.25 (0.00%)    1.00x
worst_frame_rasterizer_time_millis      10.07 (0.00%)   10.43 (0.00%)   0.97x
90th_percentile_frame_rasterizer_time_millis    8.44 (0.00%)    8.47 (0.00%)    1.00x
99th_percentile_frame_rasterizer_time_millis    8.87 (0.00%)    8.95 (0.00%)    0.99x
average_layer_cache_count       0.00 (0.00%)    0.00 (0.00%)    NaNx
90th_percentile_layer_cache_count       0.00 (0.00%)    0.00 (0.00%)    NaNx
99th_percentile_layer_cache_count       0.00 (0.00%)    0.00 (0.00%)    NaNx
worst_layer_cache_count 0.00 (0.00%)    0.00 (0.00%)    NaNx
average_layer_cache_memory      0.00 (0.00%)    0.00 (0.00%)    NaNx
90th_percentile_layer_cache_memory      0.00 (0.00%)    0.00 (0.00%)    NaNx
99th_percentile_layer_cache_memory      0.00 (0.00%)    0.00 (0.00%)    NaNx
worst_layer_cache_memory        0.00 (0.00%)    0.00 (0.00%)    NaNx
average_picture_cache_count     2.00 (0.00%)    2.00 (0.00%)    1.00x
90th_percentile_picture_cache_count     2.00 (0.00%)    2.00 (0.00%)    1.00x
99th_percentile_picture_cache_count     2.00 (0.00%)    2.00 (0.00%)    1.00x
worst_picture_cache_count       2.00 (0.00%)    2.00 (0.00%)    1.00x
average_picture_cache_memory    11.94 (0.00%)   11.94 (0.00%)   1.00x
90th_percentile_picture_cache_memory    11.94 (0.00%)   11.94 (0.00%)   1.00x
99th_percentile_picture_cache_memory    11.94 (0.00%)   11.94 (0.00%)   1.00x
worst_picture_cache_memory      11.94 (0.00%)   11.94 (0.00%)   1.00x
new_gen_gc_count        6.00 (0.00%)    6.00 (0.00%)    1.00x
old_gen_gc_count        0.00 (0.00%)    0.00 (0.00%)    NaNx
average_vsync_transitions_missed        1.00 (0.00%)    1.00 (0.00%)    1.00x
90th_percentile_vsync_transitions_missed        1.00 (0.00%)    1.00 (0.00%)    1.00x
99th_percentile_vsync_transitions_missed        1.00 (0.00%)    1.00 (0.00%)    1.00x
average_cpu_usage       37.51 (0.00%)   36.83 (0.00%)   1.02x
average_gpu_usage       22.28 (0.00%)   2.63 (0.00%)    8.49x
average_memory_usage    110.83 (0.00%)  110.68 (0.00%)  1.00x
90th_percentile_memory_usage    116.06 (0.00%)  116.02 (0.00%)  1.00x
99th_percentile_memory_usage    117.30 (0.00%)  117.03 (0.00%)  1.00x
30hz_frame_percentage   0.00 (0.00%)    0.00 (0.00%)    NaNx
60hz_frame_percentage   0.00 (0.00%)    0.00 (0.00%)    NaNx
80hz_frame_percentage   0.00 (0.00%)    0.00 (0.00%)    NaNx
90hz_frame_percentage   0.00 (0.00%)    0.00 (0.00%)    NaNx
120hz_frame_percentage  100.00 (0.00%)  100.00 (0.00%)  1.00x
illegal_refresh_rate_frame_count        0.00 (0.00%)    0.00 (0.00%)    NaNx
frame_count     1203.00 (0.00%) 1207.00 (0.00%) 1.00x
frame_rasterizer_count  1202.00 (0.00%) 1205.00 (0.00%) 1.00x
missed_frame_build_budget_count 0.00 (0.00%)    0.00 (0.00%)    NaNx
missed_frame_rasterizer_budget_count    0.00 (0.00%)    0.00 (0.00%)    NaNx
average_vsync_frame_lag 0.00 (0.00%)    0.00 (0.00%)    NaNx```

**Comment by jonahwilliams** [comment]
Given that there are no other regressions and the ambiguidy of this metric, I think we should accept the regression and move on. If more information comes to light we could reconsider.

**Comment by cyanglaz** [comment]
Agreed. I'm going to look into the first one.

**Comment by cyanglaz** [comment]
(Just wanted to record this result in issue so we don't lose it)
The local result of the [first regression ](https://flutter-flutter-perf.skia.org/e/?begin=1672181480&end=1675553399&keys=X0d345e60408f7956175cccac38cc524f&requestType=0&selected=commit%3D32959%26name%3D%252Carch%253Dintel%252Cbranch%253Dmaster%252Cconfig%253Ddefault%252Cdevice_type%253DiPhone_11%252Cdevice_version%253Dnone%252Chost_type%253Dmac%252Csub_result%253Daverage_gpu_usage%252Ctest%253Dbackdrop_filter_perf_ios__timeline_summary%252C&xbaroffset=33206):
A is with the https://github.com/flutter/engine/pull/38989 change and B is without the change
(There are no significant difference, tested with iPhone X)
```
═════════════════════════╡ ••• Final A/B results ••• ╞══════════════════════════

Score   Average A (noise)       Average B (noise)       Speed-up
average_frame_build_time_millis 1.09 (0.00%)    1.08 (0.00%)    1.01x
worst_frame_build_time_millis   3.44 (0.00%)    2.23 (0.00%)    1.55x
90th_percentile_frame_build_time_millis 1.26 (0.00%)    1.27 (0.00%)    0.99x
99th_percentile_frame_build_time_millis 1.40 (0.00%)    1.36 (0.00%)    1.03x
average_frame_rasterizer_time_millis    16.42 (0.00%)   16.42 (0.00%)   1.00x
worst_frame_rasterizer_time_millis      19.55 (0.00%)   20.62 (0.00%)   0.95x
90th_percentile_frame_rasterizer_time_millis    16.89 (0.00%)   16.99 (0.00%)   0.99x
99th_percentile_frame_rasterizer_time_millis    18.66 (0.00%)   18.06 (0.00%)   1.03x
average_layer_cache_count       0.00 (0.00%)    0.00 (0.00%)    NaNx
90th_percentile_layer_cache_count       0.00 (0.00%)    0.00 (0.00%)    NaNx
99th_percentile_layer_cache_count       0.00 (0.00%)    0.00 (0.00%)    NaNx
worst_layer_cache_count 0.00 (0.00%)    0.00 (0.00%)    NaNx
average_layer_cache_memory      0.00 (0.00%)    0.00 (0.00%)    NaNx
90th_percentile_layer_cache_memory      0.00 (0.00%)    0.00 (0.00%)    NaNx
99th_percentile_layer_cache_memory      0.00 (0.00%)    0.00 (0.00%)    NaNx
worst_layer_cache_memory        0.00 (0.00%)    0.00 (0.00%)    NaNx
average_picture_cache_count     2.00 (0.00%)    2.00 (0.00%)    1.00x
90th_percentile_picture_cache_count     2.00 (0.00%)    2.00 (0.00%)    1.00x
99th_percentile_picture_cache_count     2.00 (0.00%)    2.00 (0.00%)    1.00x
worst_picture_cache_count       2.00 (0.00%)    2.00 (0.00%)    1.00x
average_picture_cache_memory    11.07 (0.00%)   11.07 (0.00%)   1.00x
90th_percentile_picture_cache_memory    11.07 (0.00%)   11.07 (0.00%)   1.00x
99th_percentile_picture_cache_memory    11.07 (0.00%)   11.07 (0.00%)   1.00x
worst_picture_cache_memory      11.07 (0.00%)   11.07 (0.00%)   1.00x
new_gen_gc_count        2.00 (0.00%)    2.00 (0.00%)    1.00x
old_gen_gc_count        0.00 (0.00%)    0.00 (0.00%)    NaNx
average_vsync_transitions_missed        1.00 (0.00%)    1.00 (0.00%)    1.00x
90th_percentile_vsync_transitions_missed        1.00 (0.00%)    1.00 (0.00%)    1.00x
99th_percentile_vsync_transitions_missed        1.00 (0.00%)    1.00 (0.00%)    1.00x
average_cpu_usage       49.72 (0.00%)   49.45 (0.00%)   1.01x
average_gpu_usage       14.47 (0.00%)   14.49 (0.00%)   1.00x
average_memory_usage    104.69 (0.00%)  104.67 (0.00%)  1.00x
90th_percentile_memory_usage    108.02 (0.00%)  107.92 (0.00%)  1.00x
99th_percentile_memory_usage    109.27 (0.00%)  109.16 (0.00%)  1.00x
30hz_frame_percentage   0.00 (0.00%)    0.00 (0.00%)    NaNx
60hz_frame_percentage   100.00 (0.00%)  100.00 (0.00%)  1.00x
80hz_frame_percentage   0.00 (0.00%)    0.00 (0.00%)    NaNx
90hz_frame_percentage   0.00 (0.00%)    0.00 (0.00%)    NaNx
120hz_frame_percentage  0.00 (0.00%)    0.00 (0.00%)    NaNx
illegal_refresh_rate_frame_count        0.00 (0.00%)    0.00 (0.00%)    NaNx
frame_count     602.00 (0.00%)  603.00 (0.00%)  1.00x
frame_rasterizer_count  601.00 (0.00%)  602.00 (0.00%)  1.00x
missed_frame_build_budget_count 0.00 (0.00%)    0.00 (0.00%)    NaNx
missed_frame_rasterizer_budget_count    523.00 (0.00%)  528.00 (0.00%)  0.99x
average_vsync_frame_lag 0.00 (0.00%)    0.00 (0.00%)    NaNx```

**Comment by jmagman** [comment]
Thanks for investigating this @cyanglaz and @jonahwilliams.

Should we get rid of the gpu usage metric if we are fine with it going up and down? Or should we keep it as indicator that something happened and should still be investigated?

**Comment by jonahwilliams** [comment]
I would say we should stop tracking it if we don't know what to do with it.

**Comment by jmagman** [comment]
In this case the fix for https://github.com/flutter/flutter/issues/103847 is likely pushing more frames, so it seems like a good trade-off since there's less jank.  

I looked into this more, and I can see this metric regressing in the future on a more subtle change and investigation being require to understand why, since GPU usage does impact battery https://github.com/flutter/flutter/issues/31865#issuecomment-498537485.  I think we should keep it since it may help us track down future issues where battery is getting chewed up, but accept the regression in this case and close it.

Paper trail: 
https://github.com/flutter/flutter/issues/31865
https://github.com/flutter/flutter/issues/58197
https://github.com/flutter/engine/pull/18516
flutter/engine#18752

**Comment by cyanglaz** [comment]
Locally, I still couldn't find any regression related to the 3 commits in the first [regression on ci] (https://flutter-flutter-perf.skia.org/e/?begin=1672181480&end=1675553399&keys=X0d345e60408f7956175cccac38cc524f&requestType=0&selected=commit%3D32959%26name%3D%252Carch%253Dintel%252Cbranch%253Dmaster%252Cconfig%253Ddefault%252Cdevice_type%253DiPhone_11%252Cdevice_version%253Dnone%252Chost_type%253Dmac%252Csub_result%253Daverage_gpu_usage%252Ctest%253Dbackdrop_filter_perf_ios__timeline_summary%252C&xbaroffset=33206)

Can we try to revert the engine roll and confirm if it is really a regression caused by one of the 3 commits before digging into it more? @zanderso 

Is this hard to revert sdk rolls? (especially there are probably already more sdk rolls after that commit?) If so, we can first try to revert my engine PR in the engine to see if it resolves the regression.

**Comment by jonahwilliams** [comment]
No, I don't think its reasonable to revert the entire engine roll. We can revert commits in the engine and let those roll into framework

**Comment by cyanglaz** [comment]
https://flutter-flutter-perf.skia.org/e/?queries=arch%3Dintel%26branch%3Dmaster%26device_type%3DiPhone_11%26host_type%3Dmac%26sub_result%3Daverage_gpu_usage%26test%3Dbackdrop_filter_perf_ios__timeline_summary&selected=commit%3D33260%26name%3D%252Carch%253Dintel%252Cbranch%253Dmaster%252Cconfig%253Ddefault%252Cdevice_type%253DiPhone_11%252Cdevice_version%253Dnone%252Chost_type%253Dmac%252Csub_result%253Daverage_gpu_usage%252Ctest%253Dbackdrop_filter_perf_ios__timeline_summary%252C doesn't look like the revert fixed the ci. I don't think it was a jump that is related to the actual code.

**Comment by cyanglaz** [comment]
To sum up. I think the first average_gpu regression is not related to commits and the 2nd is. However there are no other indications that the 2nd regression has negative impacts. Is there anything else that we can do before we call it and closing the issue?

**Comment by zanderso** [comment]
The logs for the benchmarks show the same number of frames pushed both before and after (601).
before: https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_ios%20backdrop_filter_perf_ios__timeline_summary/8797/overview
after: https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_ios%20backdrop_filter_perf_ios__timeline_summary/8948/overview

You can click through to the timeline summaries in the log links step, and even download the timelines from the runs, but based on the summaries I don't think that will be useful.

This change takes average GPU utilization from ~3% to ~8%, and only this one benchmark was flagged. The culprit change solved a performance issue in other cases, so I think on balance we should accept this regression. Closing the issue.
