### ISSUE TITLE
Control time dilation in the Gallery app

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#1202]
This can help our friends in Material Design.

Thanks for taking a look!

**Comment by sethladd** [comment]
cc @HansMuller 

here's how we do it in the Stocks app: https://github.com/flutter/flutter/blob/master/examples/stocks/lib/stock_menu.dart#L65

**Comment by sethladd** [comment]
Duped by https://github.com/flutter/flutter/issues/1384 ?

**Comment by HansMuller** [comment]
Fixed in https://github.com/flutter/flutter/pull/1638
