### ISSUE TITLE
mac-31 machine is marked as dead for 20 hr ago.

### ISSUE THREAD

**Issue by kentnguyen99** [flutter/flutter#120222]
Another mac-31 machine is marked as dead for 20 hr ago.  Will someone take a close look of mac-31 machine, all the sudden the machine went dead.  Thanks.

![Screenshot 2023-02-07 10 09 27 AM](https://user-images.githubusercontent.com/120754754/217341458-e822cfc9-da37-413b-b1e0-db9d96120f34.png)

**Comment by yusuf-goog** [comment]
@kentnguyen99 lets meet this week and go through debugging session for this host and any others.

**Comment by kentnguyen99** [comment]
Machine mac-31 came back alive again and running now.  Yusuf re-ran couples software update and moved to new Salt master.
