### ISSUE TITLE
[webview_flutter] doesn't clear cookies

### ISSUE THREAD

**Issue by pavel604** [flutter/flutter#120216]
I'm maintaining an [Azure AD oAuth plugin](https://github.com/13302296C/azure_ad_oauth). Recently I migrated it from [flutter_webview_plugin](https://pub.dev/packages/flutter_webview_plugin) to `webview_flutter` V4.0.2.

After migration, I have noticed a problem: after login, I call `clearCache` and `clearLocalStorage`, but when I logout and login again - I login without any prompt, as if the cookies/cache have not been cleared.

Also, there seems to be no "Incognito" mode...

The problem is consistent between iOS(16.2) and Android(31-33) devices and between different Azure tenants. Tried Flutter 3.0 and 3.7.

### Steps to Reproduce correct behavior using `flutter_webview_plugin`

1. clone the [plugin](https://github.com/13302296C/azure_ad_oauth) and run example in __fwp branch__, providing your Azure `tenantId` and `clientId` in `example/lib/authenticator.dart`
2. Login
3. Logout
4. Hit Login button again

**Expected results:** you should be prompted for your email every time you login

**Actual results:** you are prompted for your email every time you login

### Steps to Reproduce incorrect behavior using `webview_flutter`

1. clone the [plugin](https://github.com/13302296C/azure_ad_oauth) and run example master __master branch__, providing your Azure `tenantId` and `clientId` in `example/lib/authenticator.dart`
2. Login
3. Logout
4. Hit Login button again

**Expected results:** you should be prompted for your email every time you login

**Actual results:** you are __not__ prompted for your email and you log back in using previous credentials

**Comment by exaby73** [comment]
Hello @pavel604. Could you provide a code sample that doesn't include any 3rd party libraries or services?

**Comment by pavel604** [comment]
There's no need for code sample: you are simply not calling `clearCookies` anywhere - just check the code.
You need to either:

1. port `clearCookies` and other cookie-related methods and setters to `WebViewController` class
2. Clear cookies as part of `clearCache`
3. Or, ___ideally___, create an Incognito flag in `WebViewController` class and do all that stuff behind the scenes.

The way it is now creates a security vulnerability in MFA apps.

**Comment by exaby73** [comment]
I would still need a way to reliably reproduce this in an example app :) This helps verify if the issue is fixed or not

**Comment by pavel604** [comment]
This did the trick:

```dart
await WebViewCookieManager().clearCookies();
```

The doc's don't seem to mention it, but it worked. So, to clear everything you would do something like
```dart
  Future<void> clearCache() async {
    await WebViewCookieManager().clearCookies();
    await _controller.clearCache();
    await _controller.clearLocalStorage();
  }
```
