### ISSUE TITLE
Text to speech

### ISSUE THREAD

**Issue by GeorgeChackungal** [flutter/flutter#12025]
Hi,

First and foremost, I love flutter! I am in the progress of creating a fitness app using flutter but I would like to have a text to speech component in it. Is there a way I can achieve TTS in flutter?

**Comment by dwaindibbly** [comment]
try looking at https://github.com/rxlabz/sytody to see if it is what you are looking for.

**Comment by GeorgeChackungal** [comment]
Sadly no. This example is for speech to text. I am looking for something
vice versa. IE text to speech. Thanks anyways :-)

**Comment by dwaindibbly** [comment]
well... both involve **native code**

**Comment by dwaindibbly** [comment]
by the way i think i can see an unlisten button... that unlistens you! is that an issue i see?

**Comment by GeorgeChackungal** [comment]
@dwaindibbly  - Agreed. Let me look at the implementation by sytody & see if I could same for TTS as well. If I am able to will create a Lib out of it as well :)

**Comment by GeorgeChackungal** [comment]
@dwaindibbly - Done! I was able to call the native TTS from flutter & it worked beautifully. Will publish the code/plugin once I finish!

**Comment by Hixie** [comment]
@GeorgeChackungal Is there anything you would like us to do further on this bug or can we close it?

**Comment by GeorgeChackungal** [comment]
Done!

**Comment by granoeste** [comment]
@GeorgeChackungal I also want to do TTS with my application.  It's Wonderful! I'm looking forward to publishing plugin! :thumbsup:

**Comment by GeorgeChackungal** [comment]
@granoeste  -  I am travelling for the next 2 weeks. Will get it done as soon as I am back!

**Comment by dejay12** [comment]
George any update on publishing this package?

thanks!

**Comment by hoppa12** [comment]
@granoeste

Hi, I have published a package on Github for TTS on Android for Flutter, I am new to programming,and have never used Dart/Java or Github before so maybe it isnt working properly! I will add IOS maybe next week unless George publishes a better solution in the meantime

https://github.com/hoppa12/Flutter-TTS-Service

**Comment by mehmetf** [comment]
@troyibm Plugins are designed to give you device/platform specific functionality. There's nothing wrong with SST and TTS being implemented as plugins.

You can take a look at  https://pub.dartlang.org/packages/tts or https://pub.dartlang.org/packages/flutter_tts. Both seem to support iOS.
