### ISSUE TITLE
[Pigeon] Generate public swift enumerators

### ISSUE THREAD

**Issue by jogboms** [flutter/flutter#120204]
## Use case

I am currently using `pkg:pigeon` to generate platform interfaces for a plugin and this plugin can then expose these interfaces to the host platform. 

In a certain version, generating swift code directly was introduced. This is great and provides better readability than Obj-c. One issue I noticed was that enumerators which were by default "public" in the generated Obj-c code, are now by default "internal" in the swift code. 

This is limiting as it defeats the purpose if wrappers are to be written for enumerators or if one has to keep editing the generated code. It seems like a quick fix IMHO.

## Proposal

I propose enumerators are made public by default to stay at least somewhat consistent with how the previous Obj-c implementation behaved and I also do not see this introducing a breaking change.

If the proposal is accepted, I could work on the implementation as it is a vital part of our workflow.

**Comment by stuartmorgan** [comment]
> and this plugin can then expose these interfaces to the host platform

Can you elaborate on what this means exactly? What does the use case look like exactly?

There was some related discussion in https://github.com/flutter/packages/pull/2903; generally speaking Pigeon output is subject to change, so is not something we recommend exposing in public interfaces.

**Comment by jogboms** [comment]
@stuartmorgan we currently use pigeon to generate interfaces for our add2app usecase. These interfaces are exposed to the apps themselves via a regular native flutter plugin which we could import in the host application. 
For data classes we end up wrapping anyway so as not to use the generated code directly but for things like the generated enumerators, we use them directly.

Does this clarify in any way?

**Comment by stuartmorgan** [comment]
> but for things like the generated enumerators, we use them directly

Why? I think I'm still not entirely understanding the use case here; why do you want parts of your Dart/Swift communication channel implementation to also be part of your plugin's public API?

**Comment by jogboms** [comment]
We do not expose the channel implementation as part of our plugin’s API. We only expose enumerators. Pigeon is a quick way to generate enumerators from a single point. 
What is your recommendation for enumerators then?

**Comment by stuartmorgan** [comment]
> We do not expose the channel implementation as part of our plugin’s API. We only expose enumerators.

Everything Pigeon generates is part of your platform channel implementation; that is Pigeon's purpose. Enums aren't any different from the other code it generates.

Imagine for example that at some point in the future we realize that there's a style mistake with the generated enums in Swift and fix it, changing all of the value names (an actual example that happened in one of the other language generators). Do you want that to be a breaking change to your plugin's public API?

> What is your recommendation for enumerators then?

I'm not sure what you mean. Our recommendation for Pigeon-generated code is the same for everything, enum or not: don't expose it publicly (per my earlier comment above).

**Comment by jogboms** [comment]
> Imagine for example that at some point in the future we realize that there's a style mistake with the generated enums in Swift and fix it, changing all of the value names (an actual example that happened in one of the other language generators). Do you want that to be a breaking change to your plugin's public API?

I would agree with this in all honesty but what ever changes are made to pigeon (breaking or not) would still require a bit of refactoring regardless. I don't think it is a choice a code generator should make especially for how access control is defined for generated code. At the least, we could add more annotations for much more customization.

> I'm not sure what you mean. Our recommendation for Pigeon-generated code is the same for everything, enum or not: don't expose it publicly (per my earlier comment above).

This recommendation is fine but again for a code generator, deciding on 'access control' without any customization feels a bit too much.

**Comment by stuartmorgan** [comment]
> what ever changes are made to pigeon (breaking or not) would still require a bit of refactoring regardless.

There is a fundamental difference between "updating Pigeon requires some internal changes to the plugin's implementation" and "updating Pigeon is a breaking change for all clients of the plugin". We accidentally created the latter in one of our own plugins in one case, and it was highly problematic and required another breaking change (for all clients of the plugin) to fix.

> I don't think it is a choice a code generator should make especially for how access control is defined for generated code.

By definition, all aspects of generated code are choices made by the code generator.

> At the least, we could add more annotations for much more customization.

In theory we could, but adding complexity for the sole purpose of enabling something that we view as an anti-pattern is not something we would approve for addition. If there's a good enough argument for allowing this use case, we would likely just change it directly, which would be much simpler.

> This recommendation is fine but again for a code generator, deciding on 'access control' without any customization feels a bit too much.

I don't follow; being opinionated about what use cases to enable is an important part of API design. Making it hard to do things that people shouldn't do is often a feature of a good API.

I've explained why we believe doing what you are trying to do is a bad idea. If you want to change my mind on supporting this you'd need to explain why there's a compelling need to support this use case (i.e., why it's a good idea to use Pigeon-generated code in public API).

**Comment by jogboms** [comment]
Thanks for taking the time to respond @stuartmorgan 
I have nothing extra to add to it.
