### ISSUE TITLE
[Feature Request] Load a flutter asset chunk by chunk 

### ISSUE THREAD

**Issue by EArminjon** [flutter/flutter#120203]
## Use case

In our app, we would give a database to our users to let them access our products while they are offline.
To let users access the feature as soon as possible, we put the database inside app assets.
The database size is heavy (> 200mb).
To use the database (and to do some operation inside), we 'move' it from assets to app folder after app launch.

The following code show how we achieve that.
```dart
// Read the assets database file
final ByteData data = await rootBundle.load("assets/file.db"); // 400 mb file

// Copy the database file to the app folder to be able to manipulate it (read, write, update, delete)
final Directory directory = await getApplicationDocumentsDirectory();
final String dbPath = '${directory.path}/app.db';
final List<int> bytes = data.buffer.asUint8List(data.offsetInBytes, data.lengthInBytes);
await File(dbPath).writeAsBytes(bytes);
```

As you see, `final ByteData data` will contain 400mb.  These 400mb will be put in RAM which have a huge impact of app performance (see video below). 

Despite doing this heavy task in thread using flutter_isolate package (https://pub.dev/packages/flutter_isolate), the issue persist.

Little screen to show the pick of ram : 
![Capture d’écran 2023-02-07 à 16 33 10](https://user-images.githubusercontent.com/37028599/217299930-6be240c1-e65d-4004-87eb-89ded206e557.png)

Video to show app freeze during the task : 

[untitled.webm](https://user-images.githubusercontent.com/37028599/217293149-dcdc3bc4-54ed-436d-8219-f064c4aafd78.webm)

Source code : https://github.com/EArminjon/flutter-rootbundle-issue
WebSite for generating heavy an asset file : https://pinetools.com/random-file-generator
We suggest a file of 400 mb, too high can lead of app crash.
## Proposal

A solution of this issue could be the creation of a method to read assets file chunk by chunk. We can imagine reading the file by step of X bytes and got a stream or a callback with the data read. 

We didn't see any method to achieve that, that's why we create this feature request.

**Comment by darshankawar** [comment]
@EArminjon 
Can you check [this](https://github.com/flutter/flutter/issues/26465) open issue and see if it resembles your use case too ?

**Comment by EArminjon** [comment]
> @EArminjon 
> Can you check [this](https://github.com/flutter/flutter/issues/26465) open issue and see if it resembles your use case too ?
> 

Yep it is similar, thank for the share.

The issue linked suggest to use a plugin which require duplicate the file inside iOS and Android folder. That's mean we will maintain 3 folders of assets. As a temporary solution it could work I think.

However, yep a feature to read chunk by chunk could be very interesting :'(

I wondering how Flutter games load heavy assets.

**Comment by darshankawar** [comment]
Thanks for the feedback and good to know that the linked issue helped you somewhat.
I suggest you to follow-up in that issue and also share your findings in it for better tracking. I'll close this in favor of the linked one. If you disagree, write in comments and I'll reopen it.
