### ISSUE TITLE
blurry image after flutter upgrade

### ISSUE THREAD

**Issue by merenyimiklos** [flutter/flutter#120279]
Hey, i have an issue after flutter upgrade.
I attach an image too.
In the app some pictures got blurry, not all of them. Can you check what is it?! We have 1x and 2x and 3x images too so.. we don't know what is this problem.

Can you help?

```
```
[✓] Flutter (Channel stable, 3.7.1, on macOS 12.6.3 21G419 darwin-x64, locale hu-HU)
    • Flutter version 3.7.1 on channel stable at /Users/macbookpro/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7048ed95a5 (7 days ago), 2023-02-01 09:07:31 -0800
    • Engine revision 800594f1f4
    • Dart version 2.19.1
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/macbookpro/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.75.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.58.0

[✓] Connected device (3 available)
    • iPhone 13 mini (mobile) • B2FBC6F1-F17F-4AAB-8E94-7A1F024E8568 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-2
      (simulator)
    • macOS (desktop)         • macos                                • darwin-x64     • macOS 12.6.3 21G419 darwin-x64
    • Chrome (web)            • chrome                               • web-javascript • Google Chrome 109.0.5414.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```
```

</details>

![1675856169557](https://user-images.githubusercontent.com/89610165/217543305-c473fe08-2bda-4c59-a404-dda1f385e98c.JPEG)

**Comment by huycozy** [comment]
Hi @merenyimiklos 
Can you share which Flutter version was working fine before? 

Also, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this. Thanks!

**Comment by merenyimiklos** [comment]
Hi @huycozy 
I just updated now the flutter and dart to this versions:
Flutter 3.7.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 32fb2f948e (15 hours ago) • 2023-02-08 07:30:10 -0800
Engine • revision f40b73f8a4
Tools • Dart 2.19.2 • DevTools 2.20.1

When we updated 3.7.0 we got this issue, before when we have 3.3.10 version this image bug not showing.

**Comment by huycozy** [comment]
@merenyimiklos Please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this.
