### ISSUE TITLE
Don't use 'BuildContext's across async gaps should not show for guard clause

### ISSUE THREAD

**Issue by jfacoustic** [flutter/flutter#120240]
Currently using flutter 3.7.1.  I'm getting the `Don't use 'BuildContext's across async gaps.` linter warning when trying to check if the build context is mounted (in an onPressed):

```dart
if (!context.mounted) return;
```

I'd rather not have to wrap longer blocks of code in a truthy check:

```dart
if(context.mounted) {
  if(xyz) {
    await _foo(context);
  }
}
```

**Comment by danagbemava-nc** [comment]
Hi @jfacoustic, this issue is being tracked in the linter over on https://github.com/dart-lang/linter/issues/4007. Kindly follow up there for updates. 

Closing from here. 

Thank you
