### ISSUE TITLE
asset_bundle_test failing on today's test order seed

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#120284]
See https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20tool_tests_general/9313/overview

It looks like this is happening because the failing test references `getFlutterRoot()`, which can change value depending on the order that tests run in:

https://github.com/flutter/flutter/blob/master/packages/flutter_tools/test/general.shard/asset_bundle_test.dart#L553

@mdebbar @jonahwilliams @eyebrowsoffire

**Comment by jonahwilliams** [comment]
We need to update the reverted test to use getFlutterRoot and testUsingContext.

**Comment by jonahwilliams** [comment]
Builds are no longer failing so I've dropped the priority. @andrewkolos , lets reland your PR but update the test to use flutterRoot differently

**Comment by jonahwilliams** [comment]
Fixed via https://github.com/flutter/flutter/pulls?q=is%3Apr+author%3Aandrewkolos+is%3Aclosed
