### ISSUE TITLE
[CP] Stop recursively including assets from asset folders

### ISSUE THREAD

**Issue by andrewkolos** [flutter/flutter#120208]
### issue_link

https://github.com/flutter/flutter/issues/119507

### Commit Hash

da36bd6fc02603ca446093a27f86e73dea768e82

### Target

stable

### pr_link

https://github.com/flutter/flutter/pull/120209

### Impacted Users

All Flutter devs

### Impact Description

Increased app bundle size from bundling assets that aren't used.

### Workaround

Yes. Delete (or move) unused that exist within subdirectories of asset directories.

### Risk

low

### Test Coverage

yes

### Validation Steps

1. Download [this repro project](https://github.com/andrewkolos/flutter_issue_repros/tree/main/appbundle_size_increase_119507).
2. Build the app with `flutter build apk --split-per-abi`.
3. Decompress any of the output apk files. Check the `assets/flutter_assets/assets` directory and make sure there is no directory named `unused`. Only two image files in total should be found under `assets/flutter_assets`. See the issue for more context.

**Comment by jonahwilliams** [comment]
LGTM

**Comment by jonahwilliams** [comment]
@andrewkolos you'll need to make a new PR of your change against the release branch, the right branch info can be found in the info template
