### ISSUE TITLE
Textformfields become unresponsive on web(Sometime not able to edit Textformfields ,its behave like disabled)

### ISSUE THREAD

**Issue by Adityapalmzn12** [flutter/flutter#120262]
Steps to Reproduce
1. getting data from rest api and making map<dynamic dynamic> ,
2. using map to create Textfields and assign TextEditingController which also generated using length of map and assign during the time of creation
custom code which i am using
```
TextFormField(
                  controller: editSellerController[i],
                  autofocus: false,
                  onChanged: (value) {
                    AppStrings.createDoc.update(
                      k,
                      // You can ignore the incoming parameter if you want to always update the value even if it is already in the map
                          (v) => (value.toString()),
                      ifAbsent: () => value.toString(),
                    );
                    v = value;
                    // debugPrint("New Map " + AppStrings.createDoc.values.toString());
                  },
                  validator: (val) {
                    if (val!.isEmpty) {
                      return 'Enter valid ' + k.toString();
                    }
                  },
                  decoration: InputDecoration(
                    labelText: editSellerController[i]!.value.text.isEmpty
                        ? ""
                        : editSellerController[i]!.value.text,
                    floatingLabelBehavior: FloatingLabelBehavior.never,
                    border: OutlineInputBorder(
                      borderRadius: BorderRadius.circular(18.0),
                      borderSide: BorderSide.none,
                    ),
                    filled: true,
                    fillColor: AppColors.neutralLightGrey,
                  ),
                )

```

**Comment by darshankawar** [comment]
@Adityapalmzn12 
In order to properly address this issue, please provide your `flutter doctor -v` and [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) without any third party plugin code that we can directly use and run to verify the reported behavior.

The code you shared has custom implementation which we can't use directly to properly analyze the behavior.

**Comment by Adityapalmzn12** [comment]
@darshankawar 
once we run this app on web so we create the texfromfield as dynamically according to the list of data length , but once we copy paste on that fields sometimes that fields  not be editable and also not getting any console error .


flutter doctor -v
[✓] Flutter (Channel stable, 3.7.0, on Ubuntu 20.04.5 LTS 5.15.0-58-generic, locale en_IN)
    • Flutter version 3.7.0 on channel stable at /home/Aditya.Pal/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b06b8b2710 (2 weeks ago), 2023-01-23 16:55:55 -0800
    • Engine revision b24591ed32
    • Dart version 2.19.0
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /home/Aditya.Pal/Android/Sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /snap/android-studio/125/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 2021.3)
    • Android Studio at /snap/android-studio/125/android-studio
    • Flutter plugin version 71.0.3
    • Dart plugin version 213.7433
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] Connected device (3 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 13 (API 33) (emulator)
    • Linux (desktop)              • linux         • linux-x64      • Ubuntu 20.04.5 LTS 5.15.0-58-generic
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 108.0.5359.94

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Comment by darshankawar** [comment]
> [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) without any third party plugin code that we can directly use and run to verify the reported behavior.

@Adityapalmzn12
