### ISSUE TITLE
ssh not working on win-5

### ISSUE THREAD

**Issue by yusuf-goog** [flutter/flutter#120245]
Cannot ssh into win-5, the bot seems to be up and working. 

Possibly some setting is missing to allow ssh into the host.

**Comment by kentnguyen99** [comment]
I have opened a go/guts ticket with network folks and they can investigate from the network side.

https://gutsv3.corp.google.com/#ticket/217327103

**Comment by kentnguyen99** [comment]
End-users could not ssh from outside to machine flutter-devicelab-windows-5 due to Mac Address resides on DNS server were wrong, Yusuf has been opened a service ticket to get update Mac Address on DNS server. We're waiting for a response from Tech Support when it's done.

**Comment by yusuf-goog** [comment]
mac address updated. ssh is now working.
