### ISSUE TITLE
[Impeller] Compiler fails to print out shaderc error message in cases where an error occurs with 0 errors and 0 warnings.

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#120241]
I found this while tweaking //impeller/compiler/compiler.cc to test something using a higher SPIRV version than 1.0.

In this case, I had misconfigured the Vulkan version for the SPIRV version I was using. This caused the compiler to fail and not produce any helpful output about why (just saying something like "Compilation failed. 0 error(s), 0 warning(s)").

We should update the check so it prints in this case, e.g. the error message I was seeing indicated an internal error that informed me where the mismatched spirv/environment version was.

**Comment by jonahwilliams** [comment]
From the last time I investigated this:

* By default spriv_cross uses exceptions for this.
* If exceptions are disabled it has a log an exit function, but this only runs if NDEBUG

We could send them a patch to add a mode that still logs

**Comment by dnfield** [comment]
I get a somewhat useful log by commenting out this line:

https://github.com/flutter/engine/blob/85958c2eaa90eae2f884d40c9fc552f3bb37e2d2/impeller/compiler/compiler.cc#L438

(and line 440 below it of course).
