### ISSUE TITLE
EAGLContext renderbufferStorage fail

### ISSUE THREAD

**Issue by xster** [flutter/flutter#12022]
Fails at https://github.com/flutter/engine/blob/master/shell/platform/darwin/ios/ios_gl_context.mm#L188.

**Comment by xster** [comment]
Strange that it only happens in that project and not in a boiled down version like https://github.com/xster/flutter-test/tree/master/t33_animation_with_native which does more or less the same thing of presentViewController another vc on top of the flutter view which cycles through viewDidDisappear, viewWillAppear

**Comment by xster** [comment]
Repro'ed in a reduced case with updated https://github.com/xster/flutter-test/tree/master/t33_animation_with_native using the share plugin. Seems like presentViewController with specifically UIActivityViewController (used by the share dialog) can cause the problem.

**Comment by xster** [comment]
As far as I can tell, risks for this whole general category of gl issues can be avoided by fixing #12061. With some testing, it seems to solve the problem for the 2 test cases. 

Going to focus on that approach now.

**Comment by collinjackson** [comment]
Reopening because your fix was reverted in https://github.com/flutter/engine/pull/4133

**Comment by collinjackson** [comment]
@cbracken can you take a look? @xster is OOO

**Comment by cbracken** [comment]
Will do!

**Comment by cbracken** [comment]
Re-fixed by #12396

**Comment by najeira** [comment]
https://github.com/flutter/engine/pull/4175 reverted the fix

**Comment by xster** [comment]
Seems like the code is still in the original state. Re-opening

**Comment by cbracken** [comment]
@xster thanks. This is correct. The re-land was reverted due to a performance regression.

**Comment by cbracken** [comment]
After investigation of the regressions, I've filed #13111 and re-landed the patch in the engine. I'll be rolling to the framework momentarily.

**Comment by cbracken** [comment]
Fixed again in framework in #13114.
