### ISSUE TITLE
failed to initialize camera on windows desktop

### ISSUE THREAD

**Issue by yasar-salim** [flutter/flutter#120267]
i have installed Camera Windows Plugin and used the code example provided in the example section. But when i ran the project and clicked create camera button it shows failed to initialize camera error(PlatformException(camera_error, Failed to initialize video preview, null, null)). I am using an external usb camera which is working fine with other applications.

i am attaching the screenshots of the same

![camera](https://user-images.githubusercontent.com/20369407/217469946-d0b57482-e52f-49fc-9828-d250d9763136.JPG)

![failed](https://user-images.githubusercontent.com/20369407/217470019-a80097f4-076c-4b86-b9b1-e8fab69dcc7c.JPG)

![prints](https://user-images.githubusercontent.com/20369407/217470085-49988808-c943-4687-985d-2bfaedbe709e.JPG)

**Comment by huycozy** [comment]
Hi @yasar-salim 
It works as expected from my end as below demo video.

https://user-images.githubusercontent.com/104349824/217491849-4bee6034-0ab6-461f-94af-c42a0c971fe5.mp4

Does the issue happen when running with [camera windows sample code](https://github.com/flutter/plugins/tree/main/packages/camera/camera_windows/example)? If so, please provide the complete output of `flutter run -v` so that we can verify it. 

Also, please provide the output of `flutter doctor -v` as well. Thanks!

**Comment by yasar-salim** [comment]
@huycozy  yes camera windows sample code. checked now on a laptop working fine with built in camera. 

flutter: PlatformException(camera_error, Failed to initialize video preview, null, null)

the above error is getting when clicking create camera button on both desktop and laptop(usb camera)

**Comment by huycozy** [comment]
@yasar-salim Is there any remaining log from stackstrace that you can provide to us?  Or does it only have `PlatformException`? 

Also, can you still interact with the app? Does it have any wrong behavior, like freezing?

**Comment by yasar-salim** [comment]
@huycozy  app works perfectly and this is the only error i am getting. I used droid cam as another camera source and i can switch to that and can take picture

**Comment by huycozy** [comment]
@yasar-salim Unfortunately, my PC has only one external USB camera (as you see from my above demo), it doesn't have a built-in camera so I can not verify this. 

But I see there's an open issue addressing the case you described https://github.com/flutter/flutter/issues/103897. It seems to be a similar issue, its log is not exactly the same, though. You can take a look at that issue and check all findings there.

In case it's different than this issue. Can you share your affected camera specs? (model). Please also provide the complete output of `flutter run -v` and the `pubspec.lock` file content (which contains `camera_windows` version there).
