### ISSUE TITLE
file_picker ?

### ISSUE THREAD

**Issue by dac3971** [flutter/flutter#12027]
Hi, is there currently a way to prompt to pick any type file? Or just images?

**Comment by lishuhao** [comment]
[image_picker](https://pub.dartlang.org/packages/image_picker)

**Comment by dwaindibbly** [comment]
mate, you'll need to know both how to code for Android and IOS to do that. I've been able to do it on just Android!

**Comment by dac3971** [comment]
@dwaindibbly ah ok. thanks
