### ISSUE TITLE
Material 3 Skeleton loaders

### ISSUE THREAD

**Issue by masreplay** [flutter/flutter#120285]
Like shimmer effect material 3 have [Skeleton loaders](https://m3.material.io/styles/motion/transitions/transition-patterns#9b4ed0ee-fc54-4df4-9a09-b4efb860f8ad)

https://user-images.githubusercontent.com/55885230/217576462-52dc3da4-c810-4ed9-9a0f-6fd41bd46a5c.mp4

https://user-images.githubusercontent.com/55885230/217576473-750f0991-b85b-462f-b689-79a83e7be8be.mp4

there is already implemented [example](https://docs.flutter.dev/cookbook/effects/shimmer-loading) with flutter for shimmer effect

[full code](https://github.com/flutter/codelabs/blob/afce67fcfecd02a3bde1c56e453e19c6f2d8d202/cookbook/lib/examples/ui_loading_animation.dart)

**Comment by huycozy** [comment]
Hi @masreplay 
This is a known issue being tracked at #116526. Closing this issue as a duplicate, so please follow up on it for further updates. 

Thanks!
