### ISSUE TITLE
[ci_yaml] flutter/infra starlark does not generate prod builder for release only target

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#120218]
`Mac verify_binaries_codesigned` is unable to run on postsubmit because there is no default builder for it. The `beta` and `stable` namespaced builders are reserved as backups in case a builder is deleted from tip of tree, but is needed for a release.

**Comment by XilaiZhang** [comment]
umm would be great if Casey can elaborate a little bit on the "beta and stable namespaced builders .... but is needed for a release." part
does this mean 
1. stable builder is needed for release, and we will check the run results from stable builders during release
or it means 
2. stable builder is not needed for release, we should roll infra and update the default builder.

**Comment by XilaiZhang** [comment]
casey submitted https://flutter-review.git.corp.google.com/c/infra/+/38962

the summary is that: there are two separate logics, builder logic and scheduler logic,  where builder logic = lucicfg logic. There is some intrinsic logic inside the scheduler logic that already handles enabled branches checks, regardless of the builder logic. However, the scheduler logic would only work when a builder exist. removing the branches check in builder logic will bring up the builder, and even though the branch check logic is removed from builder logic, the branch check logic will be handled in the scheduler logic.

**Comment by XilaiZhang** [comment]
post submits are running on dashboards now
