### ISSUE TITLE
[Impeller] Investigate removal of `waitUntilScheduled` in Metal backend.

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#120399]
[This](https://github.com/flutter/engine/blob/b93428ef346861e745d3e3982827c0fdeda569de/impeller/renderer/backend/metal/command_buffer_mtl.mm#L167) is necessary today because Impeller [doesn't do resource hazard tracking across render passes](https://github.com/flutter/flutter/issues/120406). This introduces bubbles in execution on the GPU which wastes available concurrency.

**Comment by chinmaygarde** [comment]
"Something something synchronization/hazard tracking/dependencies." -> https://github.com/flutter/flutter/issues/120406

**Comment by jonahwilliams** [comment]
I added some additional tracing so that we account for the waitUntiLScheduled in the SubmitCommands method. It appears that the vast majority of the time is spent just waiting. 

![image](https://user-images.githubusercontent.com/8975114/224505982-6160ac08-e4c2-44ae-9a9c-cbba843bf69a.png)

**Comment by jonahwilliams** [comment]
In the wonderous app, removing `waitUntilScheduled` reduces average raster time from 7-8ms down to 1-2ms.

**Comment by chinmaygarde** [comment]
Did you attach the wrong screenshot? That is showing the wait for the next drawable. That is the backpressure mechanism (the GPU telling us we are running ahead of its ability to render the stuff we are telling it to) and this issue isn't describing getting rid of it.

I got rid of the need for this wait as I am wiring up the Vulkan backend and have some notes on how we can do the same for Metal. We can discuss it in the weekly or an OOB sync perhaps?

**Comment by jonahwilliams** [comment]
No, take a look at the command buffer upload part. It's all waitUntilScheduled

**Comment by jonahwilliams** [comment]
Weekly sounds fine fyi, just doing some investigating

**Comment by jonahwilliams** [comment]
This is what I added for tracing, I believe it should be accurate.

```c++
@@ -164,6 +168,7 @@ bool CommandBufferMTL::OnSubmitCommands(CompletionCallback callback) {
   }
 
   [buffer_ commit];
+  TRACE_EVENT0("impeller", "CommandBufferMTL::waitUntilScheduled");
   [buffer_ waitUntilScheduled];
   buffer_ = nil;
   return true;
 ```

**Comment by chinmaygarde** [comment]
Note for myself to try to [assimilate the ordering guarantees in Metal](https://developer.apple.com/library/archive/documentation/Miscellaneous/Conceptual/MetalProgrammingGuide/Cmd-Submiss/Cmd-Submiss.html#//apple_ref/doc/uid/TP40014221-CH3-SW1).

**Comment by chinmaygarde** [comment]
Fixed by @bdero in https://github.com/flutter/engine/pull/40781. We were on the wrong lines of investigation w.r.t hazard tracking.

**Comment by chinmaygarde** [comment]
The fix was reverted in https://github.com/flutter/engine/pull/40895.
