### ISSUE TITLE
flutter/plugins unable to run Firebase Test Lab tests

### ISSUE THREAD

**Issue by tarrinneal** [flutter/flutter#120386]
The flutter/plugin tree is currently closed because trying to re-run a post-submit flake is giving the following error on FTL tests:

ERROR: Unable to execute "gcloud auth activate-service-account --key-file=/root/gcloud-service-key.json". Stderr:
Unable to activate gcloud account.
I'm seeing the same on presubmit tests on PRs.

Presumably a key expired or changed, and the plugins repository was not updated.

see https://github.com/flutter/flutter/issues/99703

**Comment by drewroengoogle** [comment]
@tarrinneal I believe we need to merge https://github.com/flutter/plugins/pull/7134. I wasn't sure if we were good to merge given the presubmits were red.

**Comment by drewroengoogle** [comment]
@tarrinneal I've merged the updated key.

Going forward I made sure to set the reminder a bit in advance in order to allow ample time to refresh the cirrus key.

**Comment by tarrinneal** [comment]
> @tarrinneal I believe we need to merge [flutter/plugins#7134](https://github.com/flutter/plugins/pull/7134). I wasn't sure if we were good to merge given the presubmits were red.

Seems like on of the red tests is due to this same firebase issue, which is strange.

**Comment by tarrinneal** [comment]
@drewroengoogle this issue doesn't seem to have been resolved https://cirrus-ci.com/task/4526641624383488?logs=firebase_test_lab#L11:~:text=%7C%7C%20Running%20for%20in_app_purchase/in_app_purchase%20%5B%400%3A00%5D

**Comment by drewroengoogle** [comment]
I noticed you reran the failures and they seem to have passed: https://cirrus-ci.com/build/6568150980886528

**Comment by tarrinneal** [comment]
> I noticed you reran the failures and they seem to have passed: https://cirrus-ci.com/build/6568150980886528
Awesome. Guess I jumped the gun on that message then! Thanks!

**Comment by drewroengoogle** [comment]
Closing now that cirrus.yml is updated. Feel free to reopen if this issue occurs again!

**Comment by tarrinneal** [comment]
We sill seem to be running into this issue: ERROR: Unable to execute "gcloud auth activate-service-account --key-file=/root/gcloud-service-key.json". Stderr:

https://cirrus-ci.com/task/6705251034595328#:~:text=ERROR%3A%20Unable%20to%20execute%20%22gcloud%20auth%20activate%2Dservice%2Daccount%20%2D%2Dkey%2Dfile%3D/root/gcloud%2Dservice%2Dkey.json%22.%20Stderr%3A

on this pr https://github.com/flutter/plugins/pull/7155#pullrequestreview-1293951605

**Comment by stuartmorgan** [comment]
> @tarrinneal I believe we need to merge [flutter/plugins#7134](https://github.com/flutter/plugins/pull/7134). I wasn't sure if we were good to merge given the presubmits were red.

This was rotating Cirrus credentials, the problem here is expired Firebase Test Lab credentials.

**Comment by drewroengoogle** [comment]
Closing now that the cirrus and firebase keys are updated
