### ISSUE TITLE
Pull Emulator changes into candidate branch to prevent test breakages

### ISSUE THREAD

**Issue by ricardoamador** [flutter/flutter#120320]
### issue_link

https://github.com/flutter/flutter/issues/120287

### Commit Hash

f989d55, 22bbdf0

### Target

stable

### pr_link

https://github.com/flutter/flutter/pull/120305#issuecomment-1423291708

### Impacted Users

Release team

### Impact Description

This is causing tests to fail for release branches.
https://ci.chromium.org/p/flutter/builders/prod/Linux_android%20android_defines_test/7096

### Workaround

None.

### Risk

low

### Test Coverage

yes

**Comment by itsjustkevin** [comment]
Keeping an eye on this in case it is needed for the beta branch also.

cc: @godofredoc @CaseyHillers

**Comment by godofredoc** [comment]
LGTM
