### ISSUE TITLE
[go_router_builder] ShellRoute and ParentNavigatorKey in generated routes

### ISSUE THREAD

**Issue by codakkk** [flutter/flutter#120383]
## Use case
1) There's no possibility to use go_router_builder to generate ShellRoutes.
2) No possibility to specify parentNavigatorKey in generated routes.

## Proposal

1) I actually have no idea 🥲
2) Should be enough to add the field to the GoRouteData class.

**Comment by danagbemava-nc** [comment]
Hi @codakkk, there's an issue tracking the implementation of `ShellRoutes` in `go_router_builder` in https://github.com/flutter/flutter/issues/111909

There's also an existing issue tracking adding `parentNavigatorKey` to `go_router_builder` being tracked in https://github.com/flutter/flutter/issues/119294. 

Kindly subscribe to the issues listed above for updates. 

Closing from here as duplicate. 

Thank you
