### ISSUE TITLE
TextFile文本放大镜bug

### ISSUE THREAD

**Issue by andya1985** [flutter/flutter#120344]
In flutter3.7.2 and 3.7.1 versions, there is a bug in the TextField control on IOS: a magnifying glass appears when you press and hold it for a long time. If you press and hold it still, the input method will hide or return to the previous page. The magnifying glass cannot disappear, and it occasionally appears on Android phones
https://user-images.githubusercontent.com/10007321/217742780-9b4074e8-a658-4a5c-82cf-0412a81e4483.mp4

。

**Comment by andya1985** [comment]
文本放大镜能力，请参阅

https://master-api.flutter.dev/flutter/material/TextField/magnifierConfiguration.html

 magnifierConfiguration 属性

**Comment by huycozy** [comment]
_"In flutter3.7.2 and 3.7.1 versions, there is a bug in the TextField control on IOS: a magnifying glass appears when you press and hold it for a long time. If you press and hold it still, the input method will hide or return to the previous page. The magnifying glass cannot disappear, and it occasionally appears on Android phones."_ - (I use Google translate, please try to describe the problem in English if possible)

Hi @andya1985, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) and the output of `flutter doctor -v` so that we may verify this.

 Also, please provide the affected platforms in detail (OS, model) as well. Thank you!

**Comment by andya1985** [comment]
> _"In flutter3.7.2 and 3.7.1 versions, there is a bug in the TextField control on IOS: a magnifying glass appears when you press and hold it for a long time. If you press and hold it still, the input method will hide or return to the previous page. The magnifying glass cannot disappear, and it occasionally appears on Android phones."_ - (I use Google translate, please try to describe the problem in English if possible)
> 
> Hi @andya1985, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) and the output of `flutter doctor -v` so that we may verify this.
> 
> Also, please provide the affected platforms in detail (OS, model) as well. Thank you!

`import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;


  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  late TextEditingController _controller;
  late FocusNode _focusNode=FocusNode();

  @override
  void initState() {
    // TODO: implement initState
    super.initState();
    _controller = TextEditingController();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[TextField(
            controller:_controller,
            focusNode:_focusNode,
            decoration: InputDecoration(
              isDense: true,
              contentPadding:
              EdgeInsets.symmetric(vertical: 5, horizontal: 15),
              hintText: "Please enter the keyword",
              hintMaxLines: 1,
            )),

          ],
        ),
      ),
    );
  }
}
`

flutter doctor -v


/Users/andya/fvm/default/bin/flutter doctor --verbose
[!] Flutter (Channel stable, 3.7.2, on macOS 13.2 22D49 darwin-arm64, locale zh-Hans-CN)
    • Flutter version 3.7.2 on channel stable at /Users/andya/fvm/versions/3.7.2
    ! Warning: `dart` on your path resolves to /opt/homebrew/Cellar/dart/2.16.2/libexec/bin/dart, which is not inside your current Flutter SDK checkout at /Users/andya/fvm/versions/3.7.2. Consider adding /Users/andya/fvm/versions/3.7.2/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 32fb2f948e (34 hours ago), 2023-02-08 07:30:10 -0800
    • Engine revision f40b73f8a4
    • Dart version 2.19.2
    • DevTools version 2.20.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[!] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/andya/Library/Android/sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • ANDROID_HOME = /Users/andya/Library/Android/sdk
    • Java binary at: /Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_341-b10)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] VS Code (version 1.63.2)
    • VS Code at /Users/andya/Downloads/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • iPhone (mobile) • ecda0145c6bc2ce4c01281b5e3135e5c6f41d4f1 • ios            • iOS 12.5.7 16H81
    • macOS (desktop) • macos                                    • darwin-arm64   • macOS 13.2 22D49 darwin-arm64
    • Chrome (web)    • chrome                                   • web-javascript • Google Chrome 109.0.5414.119

[!] HTTP Host Availability
    ✗ HTTP host "https://cocoapods.org/" is not reachable. Reason: An error occurred while checking the HTTP host: Handshake error in client

! Doctor found issues in 4 categories.
Process finished with exit code 0

**Comment by huycozy** [comment]
@andya1985 Below is the recorded video on iPhone 14 Pro, iOS 16.1 (emulator), it works as desired. 

https://user-images.githubusercontent.com/104349824/217996292-5a91ad87-6338-4a78-ae5b-631a7897470f.mov

Can you please provide the demo visual (video or gif) for the issue?

Also, your sample code doesn't contain implementation for navigating to another page whilst it's in your issue description: " _If you press and hold it still, the input method will hide or return to the previous page._". Please update the sample code corresponding to the case described above. Thanks!

**Comment by andya1985** [comment]
> @andya1985 Below is the recorded video on iPhone 14 Pro, iOS 16.1 (emulator), it works as desired. 
> 
> https://user-images.githubusercontent.com/104349824/217996292-5a91ad87-6338-4a78-ae5b-631a7897470f.mov
> 
> Can you please provide the demo visual (video or gif) for the issue?
> 
> Also, your sample code doesn't contain implementation for navigating to another page whilst it's in your issue description: " _If you press and hold it still, the input method will hide or return to the previous page._". Please update the sample code corresponding to the case described above. Thanks!
> 

https://user-images.githubusercontent.com/10007321/218009858-cae72292-f672-41cb-a514-eda0541b1210.mp4

**Comment by huycozy** [comment]
Thanks for the recorded video. It seems to be only reproducible on a physical device. 

I also test this on my `iPhone 7, iOS 15.7.2` and `Pixel 3a, Android 12` but can not reproduce the issue:

<details>
<summary>Demo - iOS</summary>


https://user-images.githubusercontent.com/104349824/218087900-d860dac5-a281-4083-b702-c3a6e1b922cf.MP4


</details>

What is your iPhone model? (And also your Android phone info since you also see it).

Also, can you try this on the latest master channel and check if the issue still occurs? 

```
flutter channel master
flutter upgrade
```

**Comment by techouse** [comment]
Possibly related https://github.com/flutter/flutter/issues/119711
