### ISSUE TITLE
New Flutter Project (application) doesn't generate main.dart

### ISSUE THREAD

**Issue by Zlearncode** [flutter/flutter#120348]
Hi,

I'm using Android Studio Electric Eel | 2022.1.1 Patch 1 (Build #AI-221.6008.13.2211.9514443, built on January 21, 2023) to create my Flutter app. However, new Flutter projects doesn't generate main.dart or lib folder. 

I'm using a m1 mac, on MacOS Monterey. Tried reinstalling flutter, android studio but with no results. What can I do to resolve this? 

Attached screenshot:
<img src="https://user-images.githubusercontent.com/124869435/217761138-a0329661-d617-414a-af87-c9781372ba9b.png">

My .zshrc is:
> export PATH="/Users/*****/Developer/flutter/bin:$PATH"

My flutter doctor -v is below:
<details>

 [✓] Flutter (Channel stable, 3.7.1, on macOS 12.5.1 21G83 darwin-arm64
    (Rosetta), locale en-SG)
    • Flutter version 3.7.1 on channel stable at
      /Users/*****/Developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7048ed95a5 (8 days ago), 2023-02-01 09:07:31 -0800
    • Engine revision 800594f1f4
    • Dart version 2.19.1
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/*****/Library/Android/sdk
    • Platform android-33-ext4, build-tools 33.0.1
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.15+0-b2043.56-8887301)

[✓] Connected device (3 available)
    • Android SDK built for arm64 (mobile) • emulator-5554 • android-arm64  •
      Android 9 (API 28) (emulator)
    • macOS (desktop)                      • macos         • darwin-arm64   •
      macOS 12.5.1 21G83 darwin-arm64 (Rosetta)
    • Chrome (web)                         • chrome        • web-javascript •
      Google Chrome 109.0.5414.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

</details>

**Comment by danagbemava-nc** [comment]
Hi @Zlearncode, does the recording below capture the steps you use to create your project?

Do you also have this issue if you run `flutter create foo`?

https://user-images.githubusercontent.com/88313112/217785870-46630573-d33f-40f2-9560-37194ed05cc3.mov

**Comment by Zlearncode** [comment]
> Hi @Zlearncode, does the recording below capture the steps you use to create your project?
> 
> Do you also have this issue if you run `flutter create foo`?
> Screen.Recording.2023-02-09.at.10.22.11.mov

Yes, the recording captured the steps I did, except that mine only showed external libraries and scratches and consoles. 

Running "flutter create foo" in terminal works fine. I don't know why my new flutter project doesn't generate all the other files and folders.
