### ISSUE TITLE
Required image icon class for custom Images

### ISSUE THREAD

**Issue by vuppalasivakumar** [flutter/flutter#12030]
Hi dev team,

I am trying to use custom image as image icon required return type icon data,
but that class is not available for right 
I already raised  query in google groups but as per that conversatation, my personal experience there is no Image icon class

If it is there please show me an example for creating custom image Icons.

**Comment by Hixie** [comment]
Does https://docs.flutter.io/flutter/widgets/ImageIcon-class.html solve your problem?

**Comment by Hixie** [comment]
Can you let us know the output of `flutter doctor`?

**Comment by Hixie** [comment]
I'm going to close this since we don't have enough information to go on here. Please don't hesitate to file a new bug if you can help us understand the issue better. Thanks!
