### ISSUE TITLE
[Impeller] Pick shorter list of profiles for engine malioc diff step.

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#120318]
Many of the profiles have very similar performance characteristics, having too much output makes it difficult to understand. Instead lets pare down the list to just two or three. Some suggestions:

*  Mali-G78 - Pixel 6 /  2020
* Mali-T880 - 2016

Its not clear if its worth going lowerspec than that? On the higher end, past a certain point its not useful because everything is too fast.

@zanderso / @chinmaygarde

**Comment by chinmaygarde** [comment]
IMO, this is a fine list to get started with. We can always tune this later.
