### ISSUE TITLE
[iOS] TextField selection toolbar buttons is overlapping the decoration

### ISSUE THREAD

**Issue by greggman** [flutter/flutter#120373]
## Steps to Reproduce

Similator set to iPhone 14 Pro, iOS 16.2
real phone is iPhone 13 Pro, iOS 16.2
In channel master as of 2023-Feb-08

1. On a Mac
 
   ```
   git clone --filter=blob:none https://github.com/flutter/samples.git`
   cd samples/form_app
   open -a Simulator
   flutter run
   ```

2. In the app pick 'autofill'
3. In the name field type a name
4. Select the name and tap the selection

**Expected results:** 

a context menu with some contrast that makes it clear it's separate from the content

<img width="413" alt="Screenshot 2023-02-09 at 00 54 10" src="https://user-images.githubusercontent.com/234804/217763776-4df7425b-1952-48bc-a777-7f97e743360b.png">

**Actual results:** 

a context menu with low contrast such that it fades into the content.

<img width="301" alt="Screenshot 2023-02-09 at 00 50 45" src="https://user-images.githubusercontent.com/234804/217763273-bf993a32-e86b-4b34-9d4f-4c49b125d253.png">

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by huycozy** [comment]
Hi @greggman, thanks for the report.
The issue is happening on a simple `TextField` only with provided decoration attribute (no need to put it inside `AutofillGroup` as above sample code). 

This issue is reproducible on the latest `stable` and `master` channels. On Android, it seems to be fine when it displays similarly to native app.

Labeling the issue for further insights.

<details>
<summary>Demo - iOS ❌</summary>

<img width="400" src="https://user-images.githubusercontent.com/104349824/218016910-74709931-5517-4788-b1dc-4e8533b1fc40.png">
</details>

<details>
<summary>Demo - Android ✅</summary>

| Flutter | Android native |
| --------------- | --------------- |
<img width="400" src="https://user-images.githubusercontent.com/104349824/218019439-c1acb92d-2eb9-4640-a499-9d434567dbae.png"> | <img width="400" src="https://user-images.githubusercontent.com/104349824/218019453-7b6c038d-b458-4767-a353-7b7896a0d5c8.png">

</details>

<details>
<summary>Sample code</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatefulWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const Scaffold(
        body: Center(
          child: TextField(
            decoration: InputDecoration(
              labelText: 'Login name',
            ),
          ),
        ),
      ),
    );
  }
}
```
</details>

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.7.3, on macOS 13.0.1 22A400 darwin-x64, locale en-VN)
    • Flutter version 3.7.3 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9944297138 (17 hours ago), 2023-02-08 15:46:04 -0800
    • Engine revision 248290d6d5
    • Dart version 2.19.2
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Users/huynq/Library/Java/JavaVirtualMachines/corretto-1.8.0_302/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment Corretto-8.302.08.1 (build 1.8.0_302-b08)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.75.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.58.0

[✓] Connected device (3 available)
    • SM T225 (mobile) • R9JT3004VRJ • android-arm64  • Android 13 (API 33)
    • macOS (desktop)  • macos       • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)     • chrome      • web-javascript • Google Chrome 110.0.5481.77

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```

```bash
[!] Flutter (Channel master, 3.8.0-8.0.pre.24, on macOS 13.0.1 22A400 darwin-x64, locale en-VN)
    • Flutter version 3.8.0-8.0.pre.24 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9996126740 (24 minutes ago), 2023-02-09 16:51:26 +0000
    • Engine revision eb346ba63f
    • Dart version 3.0.0 (build 3.0.0-218.0.dev)
    • DevTools version 2.21.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.75.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.58.0

[✓] Connected device (3 available)
    • SM T225 (mobile) • R9JT3004VRJ • android-arm64  • Android 13 (API 33)
    • macOS (desktop)  • macos       • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)     • chrome      • web-javascript • Google Chrome 110.0.5481.77

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```
</details>

**Comment by justinmc** [comment]
I think we just need to tweak the shadow here (and maybe the color).  I just loosely eyeballed the shadow when I built this widget.  Here's what I came up with:

https://github.com/flutter/flutter/blob/9cb7a151ad1658dd1d6772f6e17ed4545851e02f/packages/flutter/lib/src/cupertino/text_selection_toolbar.dart#L42-L51

And the toolbar's color is [here](https://github.com/flutter/flutter/blob/9cb7a151ad1658dd1d6772f6e17ed4545851e02f/packages/flutter/lib/src/cupertino/text_selection_toolbar_button.dart#L24) for completeness.

@MitchellGoodwin Do you have any thoughts on the values for this shadow here?  If not I'll probably just give another shot at darkening it a little bit.

**Comment by MitchellGoodwin** [comment]
> @MitchellGoodwin Do you have any thoughts on the values for this shadow here? If not I'll probably just give another shot at darkening it a little bit.

I'm not sure about the blur radius, but from quickly doing a comparison of the two images above with the Digital Color Meter, I think the right opacity value for the color should be about `0.14`.

I got that from the equation:
`Y=255 - P*(255-X)`
Where X is the old RGB value, Y is the new, and P is the opacity. I'm not sure how much I trust the Digital Color Meter though, so it probably need to be played around with more, but that's where I'd start.

**Comment by gnprice** [comment]
I'm eyeballing too, but in addition to the opacity I think there may be another difference between the shadows in the two screenshots: in the native screenshot, the shadow appears on all sides of the toolbar. In the Flutter screenshot, it seems like the shadow isn't extending above the top of the toolbar at all, and very little on the sides.

Possibly it's there and it's just faint, and making it darker would do the trick. But it may be worth playing with reducing the offset a bit too, and perhaps increasing the blur, so that it shows on the top and shows more on the sides.

**Comment by justinmc** [comment]
It looks like you're right, there's probably something off with the position of the shadow.  If I darken it to fully opaque it looks like this:

<img width="246" alt="Screenshot 2023-03-17 at 10 16 29 AM" src="https://user-images.githubusercontent.com/389558/225973927-5c74e580-b17e-4608-990f-4fa75ddace9b.png">
