### ISSUE TITLE
Flutter sample Form_app has cutoff text

### ISSUE THREAD

**Issue by greggman** [flutter/flutter#120327]
## Steps to Reproduce

1. On a Mac
 
   ```
   git clone --filter=blob:none https://github.com/flutter/samples.git`
   cd samples/form_app
   open -a Simulator
   flutter run
   ```

2. In the app pick 'autofill'
3. In the name field type a name
4. Select the name and tap the selection

**Expected results:** 

Cut, Copy, Paste appear correctly (here's native app screenshot)

![ios-cut-copy-paste-native](https://user-images.githubusercontent.com/234804/217675848-2774667c-e1e6-4db4-b51e-084684cd160e.png)

**Actual results:** 

Cut, Copy, Paste are cropped such that the descenders on the "py" of copy are cutoff

![ios-cut-copy-paste-flutter](https://user-images.githubusercontent.com/234804/217676056-6bbc08ea-965e-4c7f-9e44-35449a4cd8ce.png)

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by exaby73** [comment]
Hello @greggman. Could you provide information about the OS version, and phone you're testing on?

**Comment by greggman** [comment]
master fixes the cut off text for a new issue, very poor contrast

flutter

<img width="301" alt="Screenshot 2023-02-09 at 00 50 45" src="https://user-images.githubusercontent.com/234804/217763273-bf993a32-e86b-4b34-9d4f-4c49b125d253.png">

native

<img width="413" alt="Screenshot 2023-02-09 at 00 54 10" src="https://user-images.githubusercontent.com/234804/217763776-4df7425b-1952-48bc-a777-7f97e743360b.png">

**Comment by exaby73** [comment]
Since this is fixed in master, I will close this issue. If you still appear to have other issues, like the contrast you mentioned, please file a new bug. Thank you
