### ISSUE TITLE
[impeller] Investigate overhead of CreateOffscreenMSAA in scenes with many subpasses

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#120398]
Rough estimates on the iPad pro show that we can spend up to 4ms a frame in CreateOffscreenMSAA on the wonderous app menu toggle. Within the CPU profile, there don't seem to be any particular parts of that are slow, so we may be either measuring things incorrectly or allocating inefficently. This will be easier to investigate on Vulkan.

**Comment by chinmaygarde** [comment]
We can just fold this into the general class or render target and resource recycling issues right? Is there value in keeping this issue onen?

**Comment by jonahwilliams** [comment]
Yes, this was investigated and the discovery that memoryless textures aren't free to allocate.
