### ISSUE TITLE
Platform messages still being handled after FlutterView has been destroyed

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#12037]
https://github.com/flutter/engine/blob/51f12604f7aec7e425be41f56ce8637a948dfa3d/shell/common/engine.cc#L517
 -> https://github.com/flutter/engine/blob/51f12604f7aec7e425be41f56ce8637a948dfa3d/shell/platform/android/platform_view_android.cc#L358
 -> https://github.com/flutter/engine/blob/51f12604f7aec7e425be41f56ce8637a948dfa3d/shell/platform/android/io/flutter/view/FlutterView.java#L683

That code path can trigger when the flutter view has been detached, which in turn implies that the flutter view has been destroyed by Android.  This was observed in the GoogleSignIn plugin, where the plugin triggers an OEM-widget-based sign-in flow.  The Android OS reserves the right to destroy your view whenever it needs to to free up resources (and will re-create it as necessary), so it's valid for a full-screen sign-in flow to trigger the disposal of your FlutterView (followed by a re-creation when the sign-in completes).

**Comment by jason-simmons** [comment]
This is similar to https://github.com/flutter/engine/commit/232f4636e5d46df1f8ba2857c8668558afa697a5

The affected code path involves the Java side sending a reply to a message originated by the Dart side.  Given that the Dart side could be shut down by the time the reply is sent, this should be downgraded from an assert to a warning log.
