### ISSUE TITLE
Linux FEMU builders are reporting INFRA_FAILURE

### ISSUE THREAD

**Issue by amituttam** [flutter/flutter#120314]
See for more details: https://ci.chromium.org/p/flutter/builders/staging/Linux%20Fuchsia%20FEMU

Error: 

```
cmd0 'python' not found
```

**Comment by amituttam** [comment]
@godofredoc

**Comment by godofredoc** [comment]
Upstream change has landed: https://chromium-review.googlesource.com/c/infra/luci/recipes-py/+/4237575

**Comment by godofredoc** [comment]
Roll of the changes to flutter recipes: https://flutter-review.googlesource.com/c/recipes/+/39020

**Comment by godofredoc** [comment]
Fixed along with the recipe_bundles.
