### ISSUE TITLE
After upgrading from flutter 3.3.4 to 3.7.1, the country flags unicode stopped working

### ISSUE THREAD

**Issue by murilodag** [flutter/flutter#120368]
## Steps to Reproduce

Create an application with a Text widget and use different countries flags as unicode and test the different results using flutter 3.3.4 and 3.7.1.

Examples:
- 🇬🇧
- 🇺🇾

1. Execute `flutter run` on the code sample
2. App show the unicode separate instead of showing the flag. 

**Expected results:** Show the unicode flag 🇬🇧

**Actual results:** Show the separate unicodes without converting to the flag <img width="45" alt="image" src="https://user-images.githubusercontent.com/2996649/217876146-4d5012f6-9264-4cda-a0e5-dd8a18edb979.png">

**Comment by huycozy** [comment]
Hi @murilodag, thanks for the report! 

This is a known issue being tracked at #119536. Closing this issue as a duplicate, so please follow up on it for further updates. You can leave there your comment and react an upvote to the original comment will help to raise the issue. 

Thank you!

**Comment by murilodag** [comment]
Thanks @huycozy. I missed that ticket.
