### ISSUE TITLE
main.dart.js is not loaded from / but from relative URL on last stable version

### ISSUE THREAD

**Issue by jaumard** [flutter/flutter#120354]
Hi, 

I just updated Flutter to 3.7.0 from 3.3.10 and now I have a problem and flutter web no longer works properly. 

When launched via the IDE everything is working as expected, however if I hit refresh on browser and url is like /crm/promotion then it no longer works as it tries to load /crm/main.dart.js instead of /main.dart.js …. 

By checking the html code generated look like this was added:
```
<script type=“application/javascript” src=“http://localhost:63140/crm/main.dart.js”></script>
```

Instead of this:
```
<script type=“application/javascript” src=“http://localhost:63140/main.dart.js”></script>
```

I didn't see anything new about this on new version so is there new configuration to do or migration I have do in order for this to work correctly?
or is it a regression?

**Comment by jaumard** [comment]
PS: I've same issue when building in release mode.

**Comment by exaby73** [comment]
Hello @jaumard. Generating a new project with 3.3.10 and running in release mode 3.7.2 works as expected. Can you reproduce this issue with the steps I took? If so, can you tell me what I am missing

**Comment by jaumard** [comment]
sorry it is a duplicate of this problem https://github.com/flutter/flutter/pull/118684 I applied the workaround :)
