### ISSUE TITLE
Scroll protocol assumes ballistic scroll physics, and ClampingScrollPhysics isn't ballistic

### ISSUE THREAD

**Issue by gnprice** [flutter/flutter#120338]
Scrolling in a Flutter list on Android and other platforms often feels much slower and less responsive than it should be. This issue is a major reason why: it can make a fling go about 15% less far than it should. This issue has also gotten in the way of previous attempts to fix some other reasons why.

## Background

The framework's approach to scrolling assumes that each ScrollPhysics implementation is restartable, or ballistic. (*) The simulation is frequently restarted, and the ScrollPhysics is responsible for not letting that cause problems.

This is a lot like how the framework may frequently rebuild widgets, and if that affects behavior then that's a bug in the widget.

In the case of scrolling, this assumption is very natural because it will automatically be satisfied by any scroll physics so long as it obeys a reasonable ("ballistic") physical metaphor:
* The thing that's scrolling is a physical object in motion.
* Its velocity changes due to physical forces on it, according to Newton's second law.
* Those forces depend only on (a) its current velocity and (b) where it is in its environment.

This metaphor works great for a wide variety of springs, frictional forces, clamping barriers, and other forms of scrolling physics one could dream up. Modulo small bugs (#109675, and ~another which I'll file shortly~ #120340 which affects macOS scrolling), it works great for all of the framework's scroll physics…

((*) This assumption doesn't seem to be clearly documented; I'll file a separate issue for that (→#120341), and see about writing a docs PR for it. Fundamentally it stems from the fact that `ScrollPhysics.createBallisticAnimation` takes only (a) a velocity and (b) a `ScrollMetrics`, where the latter encodes the current position plus some facts like `ScrollMetrics.maxScrollExtent` that describe the physical environment.)

## Problem

… all, that is, except one. The trouble is that one scroll physics, ClampingScrollPhysics, breaks this assumption.

(That's the scroll physics we use by default on Android and all other non-Apple platforms.)

If you restart it — specifically if you restart it in the middle of a fling, where it uses ClampingScrollSimulation — then it slows down more.

The effect is that scrolling is often much slower and less responsive-feeling than it should be. In the repro below, a fling goes about 20% less far than it does for a native Android list. Part of that is due to #119875, but most of it (a 15% reduction) is due to this issue.

#### Related issues

* Symptom caused by this issue and several others: #16371
* Different issue causing overlapping symptoms: #119875
* Thread about the fact that we do frequently restart the simulations: #11599
  (Frequently restarting isn't a bug in itself, unless it's so often as to become a performance issue. The bug is that we do restart, even sometimes, and that the physics doesn't handle this.)
* One visible quirk of ClampingScrollPhysics and ClampingScrollSimulation is that near the end, it speeds up slightly and then abruptly stops: #113424
  This quirk would be impossible in a restartable/ballistic scroll simulation: it has to slow down at every speed, or it would never stop.

## Steps to Reproduce

1. Run the [`platform_tests/scroll_overlay`](https://github.com/flutter/platform_tests/tree/1d797b8699546f1178e3cf58de9c6cc64f825281/scroll_overlay) app on an Android device.
2. Scroll with a fling gesture: swipe rapidly upward and release. Wait a couple of seconds for the scroll to come to a stop.
   * Swipe just once, and swipe as precisely straight upward as possible, just like with #119875.
3. Observe how far the scroll went, as shown by the numbered item "Flutter n" in the Flutter-driven scrolling list.

4. Edit `lib/main.dart` to delete the line `itemCount: 1000,`. Reload, and scroll back to the top.
5. Repeat steps 2 and 3.

**Expected results:** 

The list should go the same distance, reaching the same numbered item, regardless of whether the list is infinite or merely practically infinite. (With 1000 items, we never get close to the end of the list.)

**Actual results:** 

The list goes much less far with `itemCount: 1000` present than it does without it.

Specifically, when I try this on the current version of `scroll_overlay` (at flutter/platform_tests@1d797b8699546f1178e3cf58de9c6cc64f825281), I see "Flutter 81" at the top of the screen when the fling is complete. With `itemCount: 1000,` removed, I see "Flutter 90".

(Ideally the list should also go the same distance that the Android list does: I see "Android 94" at the top of the screen. With `itemCount` removed, the remaining discrepancy is #119875.)

This means the total distance travelled with `itemCount` present is about 15% less than without it, and about 20% less than the Android list. (Just dividing (90-81)/90 would give too low an estimate, because the later items are bigger: item N is 40+N logical pixels tall. The 15% and 20% are my calculations using those actual heights.)

**How the repro works:**

This repro uses the fact that passing a non-null `itemCount` to the `ListView` constructor causes frequent restarts of the scroll's ballistic simulation, #11599, and an `itemCount` of null suppresses them. That isolates the effect of this issue from #119875 and others.

<details><summary>Details of why `itemCount` affects the repro</summary>

When `itemCount` is non-null, the underlying SliverList will estimate a max scroll offset based on the children it's laid out, so this estimate constantly changes and each `ScrollPosition.applyContentDimensions` call causes an `applyNewDimensions` call, which leads to `goBallistic` and restarting the simulation. With a null `itemCount`, the estimate is always infinite (from `SliverMultiBoxAdaptorElement.estimateMaxScrollOffset`), so it never changes and `applyNewDimensions` isn't called.

</details>

<details>
  <summary>Logs</summary>

```
$ flutter analyze
Analyzing scroll_overlay...                                             
No issues found! (ran in 0.8s)
```

```
$ flutter doctor -v
[✓] Flutter (Channel main, 3.8.0-8.0.pre.13, on Debian GNU/Linux 10 (buster) 4.19.0-23-amd64, locale en_US.UTF-8)
    • Flutter version 3.8.0-8.0.pre.13 on channel main at /home/greg/n/flutter/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2303f42250 (3 hours ago), 2023-02-08 14:24:12 -0500
    • Engine revision cc4ca6a06a
    • Dart version 3.0.0 (build 3.0.0-215.0.dev)
    • DevTools version 2.21.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /home/greg/Android/Sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /home/greg/lib/android-studio-2020.3.1.24/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 7.0.1-8+deb10u2 (tags/RELEASE_701/final)
    • cmake version 3.13.4
    • ninja version 1.8.2
    • pkg-config version 0.29

[✓] Android Studio (version 2022.1)
    • Android Studio at /home/greg/lib/android-studio-2020.3.1.24
    • Flutter plugin version 71.2.4
    • Dart plugin version 221.6096
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] Android Studio (version 2021.2)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 71.1.2
    • Dart plugin version 212.5744
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.75.0)
    • VS Code at /usr/share/code
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • Pixel 5 (mobile) • 08171FDD40025F • android-arm64  • Android 13 (API 33)
    • Linux (desktop)  • linux          • linux-x64      • Debian GNU/Linux 10 (buster) 4.19.0-23-amd64
    • Chrome (web)     • chrome         • web-javascript • Google Chrome 109.0.5414.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

## Android's scroll physics isn't ballistic either

When PR #77497 was merged in order to switch ClampingScrollSimulation to use the native Android physics (which would fix #113424 and #119875 and thereby some of the causes of #16371), it had to be reverted because of a variation on this issue. That was:
* #83632
  and its duplicate #84197

The root cause of those is that it turns out that the native Android scroll physics is also not restartable/ballistic, but in the opposite direction. Restarting the current ClampingScrollSimulation makes it slow down more, but restarting the Android scroll physics makes it keep going more, i.e. makes it slow down less.

Specifically, the Android physics starts at a deceleration of zero, and gradually decelerates more later. (See the curve at https://github.com/flutter/flutter/issues/119875#issuecomment-1414580430 , the blue Android curve in the lower-left graph showing velocity, and note that the velocity at the beginning is flat.) So if you restart it, then it returns to not decelerating — which, when it happens again and again, produces the extremely long gliding behavior seen in #83632.

(That issue title says the scroll "regains velocity", but I think that is an illusion. My eyes see that same illusion too; but when I repro the issue and log the velocity, it always gets slower, not faster. It's just that it gets slower very slowly.)

**Comment by gnprice** [comment]
I see two possible ways forward to resolve this issue and its friends. Here's one:

### Fix ClampingScrollSimulation to use a restartable, physical curve

We could fix ClampingScrollSimulation to use a curve that obeys the ballistic physical metaphor and can be restarted cleanly.

In addition to this issue itself, this solution would also fix #113424. By choosing the curve appropriately, it can fix #119875 too, travelling the exact same total distance as the Android physics does for a given starting velocity.

This option doesn't open a path to using the exact Android physics. But it fixes the issues that have previously motivated people to want to swap in those exact physics:
* #113424,
  which motivated #77497
* #119875 

So we could decide to say: if the subtle details of Android's scrolling behave in a physically nonsensical way, then that's a polish issue in Android, not in Flutter.

I have an implementation of this, which I'll send as a PR shortly. In my testing, the scrolling feels natural and responsive. (*) And when comparing to Android native behavior using the `scroll_overlay` app, the flings end in the same place.

((*) As long as you swipe vertically, that is. Swiping diagonally pulls in a separate issue I'll file shortly which is present regardless of scroll physics, and involves how we apply the max velocity.)

Even if we want to eventually pursue the second path, I think we should go ahead and merge a version of this solution soon, because:
* It fixes the major user-visible issues with the current ClampingScrollSimulation.
* The code gets simpler, and the behavior closer to Android's, than it is now. So it doesn't make the second solution any harder than it otherwise would be.

**Comment by gnprice** [comment]
Here's the other:

### Remove the assumption that scroll physics is physical

We could remove the assumption that scroll physics obeys a ballistic physical metaphor that lets it be restarted cleanly.

This will then allow us to swap in Android's curve, fixing #113424 and #119875. (Or, if we like, any other curve, including the one from the previous option [above](https://github.com/flutter/flutter/issues/120338#issuecomment-1423634724).)


#### Previous round

This is the approach taken in #107735, which was the successor to #77497.

That PR had to be reverted too, because removing this assumption is complicated. It tried to avoid changing the `ScrollPhysics` API, but:
* Some customers' custom scroll physics were broken by the change anyway, because they assumed the `position` argument would specifically be a scroll position, not just a `ScrollMetrics`: https://github.com/flutter/flutter/issues/16371#issuecomment-1241020432
* Using the existing `ScrollPhysics.createBallisticsSimulation` signature involved passing that method a mixture of the original starting position and velocity with the updated `minScrollExtent`, `maxScrollExtent`, `viewportDimension`, and `axisDirection`, in order to try to create a simulation which would carry on the original simulation in the context of the new metrics.

  But this won't always work: the new metrics may cause `createBallisticsSimulation` to make different decisions and create a completely different simulation from the original one. Because it's a mix of data from two different times, the combination may produce erratic results.

In particular, that PR introduced this symptom:
* #110400
* #110340

From #110400, which I think is a bit clearer of a report than the other:
> Quickly scroll to the bottom of the list and then quickly fling up a bit. […]
> **Actual results:** The list suddenly jumps to a completely different item

I suspect that was triggered by a change in `axisDirection`. Combining that with the original position at the start of the list would make things look to `createBallisticsSimulation` like an attempt to overscroll at the top, producing a completely different simulation from the original fling. (I haven't investigated that issue closely enough to be confident of this particular diagnosis, though.)


#### Now

I have an implementation of this approach too, which I'll send as a PR in order to show the code for discussion. It works in my testing, fixing this issue.

That PR would be a breaking change, in particular to the API that `ScrollPhysics` subclasses have to extend. I think probably any version of this solution will have to be a breaking change.

I also don't love the resulting API, though that can probably be improved.

On the plus side, this direction is the only way to make it possible to use the exact Android scroll physics.

**Comment by danagbemava-nc** [comment]
Reproducible using the code sample in  https://github.com/flutter/platform_tests/tree/1d797b8699546f1178e3cf58de9c6cc64f825281/scroll_overlay

Labeling for further insight. 

<details>
<summary>recording</summary>

| itemCount: 1000 | itemCount: null | 
| -- | -- |
| <video src="https://user-images.githubusercontent.com/88313112/217755402-0f417d76-4d1c-4bc2-b5b9-60d1ef553281.mp4" /> | <video src="https://user-images.githubusercontent.com/88313112/217755396-d48e553e-bd9e-42a4-b7da-de6070367bd6.mp4" /> |


</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.7.2, on macOS 13.1 22C65 darwin-arm64, locale en-GB)
    • Flutter version 3.7.2 on channel stable at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 32fb2f948e (17 hours ago), 2023-02-08 07:30:10 -0800
    • Engine revision f40b73f8a4
    • Dart version 2.19.2
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[!] Android Studio (version 2022.1)
    • Android Studio at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/221.6008.13.2211.9477386/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] IntelliJ IDEA Community Edition (version 2022.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.75.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.58.0

[✓] Connected device (5 available)
    • Pixel 7 (mobile)           • 28291FDH2001SA                       • android-arm64  • Android 13 (API 33)
    • TA 1021 (mobile)           • PLEGAR1790423460                     • android-arm64  • Android 9 (API 28)
    • iPhone 14 Pro Max (mobile) • 70C93773-FBEC-4F48-B648-EE61E0D00BFB • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-2 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 13.1 22C65 darwin-arm64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 109.0.5414.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.
```

```
[!] Flutter (Channel master, 3.8.0-8.0.pre.19, on macOS 13.1 22C65 darwin-arm64, locale en-GB)
    • Flutter version 3.8.0-8.0.pre.19 on channel master at /Users/nexus/dev/sdks/flutters
    ! Warning: `flutter` on your path resolves to /Users/nexus/dev/sdks/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/nexus/dev/sdks/flutters. Consider adding /Users/nexus/dev/sdks/flutters/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/nexus/dev/sdks/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/nexus/dev/sdks/flutters. Consider adding /Users/nexus/dev/sdks/flutters/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b1c4d5686e (7 hours ago), 2023-02-08 16:55:05 -0800
    • Engine revision 89c8a1393d
    • Dart version 3.0.0 (build 3.0.0-215.0.dev)
    • DevTools version 2.21.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/221.6008.13.2211.9477386/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] Android Studio (version 2022.1)
    • Android Studio at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/221.6008.13.2211.9477386/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] IntelliJ IDEA Community Edition (version 2022.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.75.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.58.0

[✓] Connected device (5 available)
    • Pixel 7 (mobile)           • 28291FDH2001SA                       • android-arm64  • Android 13 (API 33)
    • TA 1021 (mobile)           • PLEGAR1790423460                     • android-arm64  • Android 9 (API 28)
    • iPhone 14 Pro Max (mobile) • 70C93773-FBEC-4F48-B648-EE61E0D00BFB • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-2 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 13.1 22C65 darwin-arm64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 109.0.5414.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```
</details>

**Comment by grouma** [comment]
> So we could decide to say: if the subtle details of Android's scrolling behave in a physically nonsensical way, then that's a polish issue in Android, not in Flutter.

I feel like this is worth filing a bug on Android.
