### ISSUE TITLE
DropdownMenu does not scroll to highlighted item when searching

### ISSUE THREAD

**Issue by nicokoch** [flutter/flutter#120349]
## Use case
I have a `DropdownMenu` with `enableSearch = true` and a lot of items (so the Dropdown is scrollable).
When entering text in the input field, the Dropdownmenu correclty searches for the item and highlights it.

The problem is: the dropdown list does not automatically scroll to the highlighted position, which means the user cannot see that his search has valid results.

## Proposal
If the highlightedItem is outside the view (`menuHeight` is contrained), automatically scroll to the highlighted item upon search.

**Comment by exaby73** [comment]
Hello @nicokoch. Thank you for filing this issue. Can you please provide the following information?

- A [complete and minimal, reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example). Ideally, a single `main.dart` file that can be run directly.
- The output of `flutter doctor -v`

Please provide the information in the form of text. See how to make collapsible sections with Markdown [here](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-collapsed-sections).

**Comment by nicokoch** [comment]
Hi @exaby73, thanks for the quick response.
I have created a minimal, reproducible example:
<details><summary>EXAMPLE</summary>

```dart
   import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Dropdown no scroll example'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});
  final String title;
  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  List<DropdownMenuEntry<int>> _entries = [];

  @override
  void initState() {
    super.initState();
    final results = <DropdownMenuEntry<int>>[];
    for (int i = 0; i < 100; i++) {
      results.add(DropdownMenuEntry(value: i, label: i.toString()));
    }
    _entries = results;
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
          child: DropdownMenu(
        enableSearch: true,
        menuHeight: 300.0,
        dropdownMenuEntries: _entries,
      )),
    );
  }
}

```
</p>
</details>

## Instructions
In the dropdown, search for something that is outside the initial dropdown, for example "30".
In the dropdown list, the "30" will be correctly highlighted, but the list down not automatically scroll to the position of the highlight. The user has to scroll manually.

Hope this helps, best regards :-)

**Comment by exaby73** [comment]
According to the docs, this is intended as `enableSearch` is meant to only highlight. Maybe, you're looking for `enableFilter` instead?

**Comment by wkolov** [comment]
How should highlighting without scrolling be helpful in long lists?

**Comment by exaby73** [comment]
I'll label this issue as a proposal to allow scrolling to the respective highlighted item
