### ISSUE TITLE
flutter doctor --android-licenses not working due to java.lang.UnsupportedClassVersionError

### ISSUE THREAD

**Issue by mahmmd** [flutter/flutter#120388]
I am trying to accept flutter doctor --android-licenses but I am getting this error:

Error: A JNI error has occurred, please check your installation and try again Exception in thread "main" java.lang.UnsupportedClassVersionError: com/android/prefs/AndroidLocationsProvider has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0

**Comment by thurakhant** [comment]
1. Uncheck Android SDK command-line Tools (latest)
2. Check Android SDK command-line Tools 8.0
3. Click Apply
4. In Windows go to “C:\Users\USERNAME\AppData\Local\Android\Sdk\cmdline-tools” and rename the 8.0 folder to “latest”
5. Run Flutter doctor again.

**Comment by darshankawar** [comment]
@mahmmd 
Check above solutions and see if they help. Also, you can try by upgrading your jdk version to latest.
See [this](https://stackoverflow.com/questions/75328050/flutter-doctor-android-licenses-not-working-due-to-java-lang-unsupportedclassv) SO link for further resolution.

Closing from here.

**Comment by ibenettaleb** [comment]
@thurakhant Thank You 🙏

**Comment by haydin505** [comment]
> Try This (For Windows) ...
> 
> 1. Uncheck Android SDK command-line Tools (latest)
> 2. Check Android SDK command-line Tools 8.0
> 3. Click Apply
> 4. In Windows, go to “C:\Users\USERNAME\AppData\Local\Android\Sdk\cmdline-tools” and rename the 8.0 folder to “latest”
> 5. Run Flutter doctor again.

Thank you for the solution. I've been trying to find a solution for 2 hours. 🙏

**Comment by Zeeshan1572** [comment]
I have macbook kindly tell me how to resolve this

**Comment by BaoTrung37** [comment]
> 

Thank u for the solution. It work

**Comment by jhonysap** [comment]
> Eu tenho macbook por favor me diga como resolver isso

Were you able to find the solution? I've been looking for the solution for my mac for 3 days and I can't find it

**Comment by haydin505** [comment]
It's same for MacOS, just go to this `~/Library/Android/sdk/cmdline-tools` directory and change "8.0" folder to "latest" as stated above.

**Comment by daleyu** [comment]
Solution worked great. For some additional information for ease: if you are in Android studio, then you go to the more actions -> SDK manager -> and then if you check off "Hide Obsolete Packages" and "Show Package Details" then you should be able to find it in the command line tools, then you can just follow along with what is above. "mv" to rename.

**Comment by larssn** [comment]
So let me get this straight:
We're moving version `8.0` of the _Android Command-line Tools_ to the `latest` folder (which SHOULD be version `9.0`)?

I'm not sure that's a good idea. Other tools might expect the `latest` version to _actually_ be the latest version...

**Comment by haydin505** [comment]
You can always delete and install latest package so you do not need to worry about software stability. Also, if you update tools frequently, folders will be overridden when newer version released.

**Comment by joaovictornunnes** [comment]
> > Try This (For Windows) ...
> > 
> > 1. Uncheck Android SDK command-line Tools (latest)
> > 2. Check Android SDK command-line Tools 8.0
> > 3. Click Apply
> > 4. In Windows, go to “C:\Users\USERNAME\AppData\Local\Android\Sdk\cmdline-tools” and rename the 8.0 folder to “latest”
> > 5. Run Flutter doctor again.
> 
> worked on macOS M1

I couldn't find the path to change the 8.0 folder to latest.

**Comment by huseyinaydin505** [comment]
> > > Try This (For Windows) ...
> 
> > > 
> 
> > > 1. Uncheck Android SDK command-line Tools (latest)
> 
> > > 2. Check Android SDK command-line Tools 8.0
> 
> > > 3. Click Apply
> 
> > > 4. In Windows, go to “C:\Users\USERNAME\AppData\Local\Android\Sdk\cmdline-tools” and rename the 8.0 folder to “latest”
> 
> > > 5. Run Flutter doctor again.
> 
> > 
> 
> > worked on macOS M1
> 
> 
> 
> I couldn't find the path to change the 8.0 folder to latest in macOS intel.
> 
> 

I've stated the target path above. Checkout the link below.
https://github.com/flutter/flutter/issues/120388#issuecomment-1439124957

**Comment by haydin505** [comment]
> > > Try This (For Windows) ...
> 
> > > 
> 
> > > 1. Uncheck Android SDK command-line Tools (latest)
> 
> > > 2. Check Android SDK command-line Tools 8.0
> 
> > > 3. Click Apply
> 
> > > 4. In Windows, go to “C:\Users\USERNAME\AppData\Local\Android\Sdk\cmdline-tools” and rename the 8.0 folder to “latest”
> 
> > > 5. Run Flutter doctor again.
> 
> > 
> 
> > worked on macOS M1
> 
> 
> 
> I couldn't find the path to change the 8.0 folder to latest in macOS intel.
> 
> 

I've stated the target path above. Checkout the link below.
https://github.com/flutter/flutter/issues/120388#issuecomment-1439124957

**Comment by AbdelsalamHaa** [comment]
> Try This (For Windows) ...
> 
> 1. Uncheck Android SDK command-line Tools (latest)
> 2. Check Android SDK command-line Tools 8.0
> 3. Click Apply
> 4. In Windows, go to “C:\Users\USERNAME\AppData\Local\Android\Sdk\cmdline-tools” and rename the 8.0 folder to “latest”
> 5. Run Flutter doctor again.

This worked for me after so many tries to update my SDK .. etc
Thanks
