### ISSUE TITLE
Remove beta|stable configuration from flutter/infra

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#120402]
Beta | Stable configurations are not being used anymore but we are keeping them for cases when builders are deleted from the main/master but we still need to run them for release candidate branches.

Once engine is migrated to engine v2 builds and those builds enabled in dart-internal we can remove the stable | beta configs as engine v2 builds use the data from .ci.yaml to create builds instead of the info from flutter/infra.

The removal step will be executed during the cleanup stage of SLSA L1 project.

**Comment by godofredoc** [comment]
\cc @CaseyHillers

**Comment by keyonghan** [comment]
We may also need to cleanup recipes branches.

**Comment by godofredoc** [comment]
CL: https://flutter-review.googlesource.com/c/infra/+/49600

**Comment by CaseyHillers** [comment]
I sent https://flutter-review.googlesource.com/c/infra/+/50220 to reland removing the release configs. Thanks everyone for keeping the configs around so we could ship 3.10.7!
