### ISSUE TITLE
observatory web server crashing?

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter#12048]
I'm seeing some odd behavior with the observatory web server. When I go to different urls (http://127.0.0.1:8102/#/memory-dashboard, http://127.0.0.1:8102/), I get redirected to http://127.0.0.1:8102/#/vm-connect, and see what looks like a blank obs. page:

<img width="1473" alt="screen shot 2017-09-12 at 7 59 24 am" src="https://user-images.githubusercontent.com/1269969/30332876-55f436dc-9790-11e7-8b0e-1e8c7f2ea90c.png">

The timeline page (http://127.0.0.1:8102/#/timeline) does load, but doesn't seem active:

<img width="1477" alt="screen shot 2017-09-12 at 8 00 42 am" src="https://user-images.githubusercontent.com/1269969/30332943-84ae2d7a-9790-11e7-9a6c-956fce608787.png">

The app continues running fine, and I don't see any errors printed to the flutter cli.

/cc @a-siva @B3rn475

**Comment by devoncarew** [comment]
I'm on the latest flutter:

```
[✓] Flutter (on Mac OS X 10.12.6 16G29, locale en-US, channel master)
    • Flutter at /Users/devoncarew/projects/flutter/flutter
    • Framework revision fd6b9c7943 (4 hours ago), 2017-09-12 13:29:16 +0200
    • Engine revision 2d7c30033d
    • Tools Dart version 1.25.0-dev.11.0
```

**Comment by B3rn475** [comment]
Fixed in the VM https://github.com/dart-lang/sdk/commit/36226f722e63cb27e023c0a5b697ac3b0a5b310c

Rolling changes https://github.com/flutter/flutter/pull/12049

**Comment by B3rn475** [comment]
Closed by https://github.com/flutter/flutter/pull/12049
