### ISSUE TITLE
[android][platform view] Big Loading Time

### ISSUE THREAD

**Issue by delfme** [flutter/flutter#120434]
Platform View takes much time to load. This occurs even if it is a simple widget (textfield) rendered on an empty screen.

Tested on latest stable and master 3.8.0-5.0.pre.1, android 12SKQ1.211006.001, xiaomi mi lite 11  5G.

## Steps to Reproduce
Please run this simple example here:
https://github.com/delfme/flutter-native-text-input-repo

**Expected results:**
Native widget should load quickly. A small delay might be expected with platform views but here we have a simple textfield rendered on an empty screen and it takes -2 secs.

**Actual results:**
Native widget takes 1-2secs to load. You can notice it by staring at the placeholder. It sometimes might load quickly but most of times it loads slowly. Loading Demo screen multiple times consecutively makes issue even more evident.

https://user-images.githubusercontent.com/53510751/218092029-23a4cd79-a3ad-4a13-922b-6d23fc5c5b3c.MP4

**Flutter doctor:**
 [✓] Flutter (Channel master, 3.8.0-5.0.pre.1, on macOS 12.2 21D49 darwin-arm64, locale en-IT) [!] Android toolchain - develop for Android devices (Android SDK version 31.0.0) ✗ cmdline-tools component is missing Run path/to/sdkmanager --install "cmdline-tools;latest" See https://developer.android.com/studio/command-line for more details. ✗ Android license status unknown. Run flutter doctor --android-licenses to accept the SDK licenses. See https://flutter.dev/docs/get-started/install/macos#android-setup for more details. [✓] Xcode - develop for iOS and macOS (Xcode 13.4.1) [✓] Chrome - develop for the web [✓] Android Studio (version 2021.2) [✓] Connected device (3 available) [✓] HTTP Host Availability

**Comment by huycozy** [comment]
Hi @delfme 
I see that you are using `flutter_native_text_input` in your sample code. For the issue to be workable, it needs to be reproducible with a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code. Please provide such a sample.
Thank you!

**Comment by delfme** [comment]
Hi @huycozy , I noticed that I would end up writing the same plugin code, which is open and can be moved inside the repo.

Can you please have a look? From what I see, delay is not a plugin issue. It is a simple EditText with a few init code lines for text styling and set the placeholder.
https://github.com/collinjackson/flutter-native-text-input/blob/master/android/src/main/kotlin/dev/henryleunghk/flutter_native_text_input/NativeTextInput.kt

Rendering delay seems caused by android platform view (it is worth noticing we have almost no delay on iOS).

**Comment by delfme** [comment]
I created a performanceOverlay for #120435 
I attach it also here since it is the same repo.

https://user-images.githubusercontent.com/53510751/218411532-5fb031f6-850c-4bc9-8a51-55fa5e374dbc.mov

**Comment by huycozy** [comment]
@delfme You can also check my PlatformView sample code for simple EditText: https://github.com/huycozy/platformviews-demo/tree/test-textfield. 

With this example, I don't see the rendering delay as yours (the EditText hint is displaying right away when the native screen displays)

<details>
<summary>Demo</summary>


https://user-images.githubusercontent.com/104349824/218641986-1bdfd324-a65d-41af-aa62-ef82d96d4fda.mov


</details>

**Comment by delfme** [comment]
Thx @huycozy I also dont have delay by wrapping editext without plugin

https://user-images.githubusercontent.com/53510751/218644865-cb99935e-2e7c-4a89-a635-341aed76badb.MOV


Will investigate following cases:
1) it is not a delay. Maybe sth strange is done with setHint and it visually looks like a loading delay
2) delay is caused by method channel

**Comment by delfme** [comment]
I confirm it was plugin issue. Closing this. Thx for the kind support 🙏
