### ISSUE TITLE
[Deeplink Automation] Implements flutter tool to retrieve app settings from Android project

### ISSUE THREAD

**Issue by chunhtai** [flutter/flutter#120408]
As describe in internal design doc [go/flutter-deeplink-web-validator](http://goto.google.com/flutter-deeplink-web-validator) (non-public accessible)

We need to build a tool to get package name, and associate web domain

**Comment by chunhtai** [comment]
Some notes

We can get Androidmanifest by using gradle task. By inserting this task into the build.gradle under `android{..}`
```
applicationVariants.all { variant ->
        tasks.create(name: "run${variant.name.capitalize()}") {
            doFirst {
                variant.outputs.each { output ->
                    println "in output"
                    output.getProcessManifestProvider().get().doLast { task ->
                        def outputDir = task.getMultiApkManifestOutputDirectory()
                        File outputDirectory
                        if (outputDir instanceof File) {
                            outputDirectory = outputDir
                        } else {
                            outputDirectory = outputDir.get().asFile
                        }
                        File manifestOutFile = file("$outputDirectory/AndroidManifest.xml")

                        if (manifestOutFile.exists() && manifestOutFile.canRead() && manifestOutFile.canWrite()) {

                            println "manifestOutFile $manifestOutFile.text"

                        }
                    }
                }
            }
        }
    }
```

to run the task, in the project folder do `./gradlew run<variantName> process<variantName>Manifest`

for example
`./gradlew runFullDebug processFullDebugManifest`

This should print out the full xml.

Three things I need to verify:
1. is the xml already evaluate? (no parameterized value)
2. is the xml merged in case of multi manifest
3. Can we safely use `process<variantName>Manifest` it seems like a hidden task...

**Comment by chunhtai** [comment]
@reidbaker Do you have suggestions for (3) and (4) in the previous comment

**Comment by reidbaker** [comment]
I think you want that code to live in https://github.com/flutter/flutter/blob/master/packages/flutter_tools/gradle/flutter.gradle which is where we have other tasks defined. 


I think then answer to all 4 questions is you might want to follow the code [flutter.gradle#L987](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/gradle/flutter.gradle#L987) where the entire compile process is done and we are extracting the apk with a merged manifest. 

For futher reading [this stackoverflow question](https://stackoverflow.com/questions/13937123/disable-manifest-merger-in-android-gradle-build) describes how to turn off manifest merging. I wonder if you can use variant.processResources.manifestFile to get the file directly.
