### ISSUE TITLE
main (waiting):tid=1 systid=15692 ; io.flutter.plugins.camera.Camera.stopBackgroundThread(Camera.java)

### ISSUE THREAD

**Issue by madhugill** [flutter/flutter#120423]
Hi,

I am facing an issue of camera related issue.
Plugin used - camera: ^0.9.4+18

Logs-
```
main (waiting):tid=1 systid=15692
at java.lang.Object.wait(Object.java)
at java.lang.Object.wait(Object.java:442)
at java.lang.Thread.join(Thread.java:1438)
at java.lang.Thread.join(Thread.java:1519)
at io.flutter.plugins.camera.Camera.stopBackgroundThread(Camera.java)
at io.flutter.plugins.camera.Camera.close(Camera.java)
at io.flutter.plugins.camera.Camera.dispose(Camera.java)
at io.flutter.plugins.camera.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java)
at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java)
at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java)
at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0(DartMessenger.java)
at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$DartMessenger(DartMessenger.java)
at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$TsixYUB5E6FpKhMtCSQVHKE89gQ.run(-.java)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:257)
at android.app.ActivityThread.main(ActivityThread.java:8192)
at java.lang.reflect.Method.invoke(Method.java)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:626)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1015)
```

I have a list of devices for which logs have been logged into firebase crashlytics-
Vivo- V2045, vivo 1904, V2142, Y35, V2036
Samsung - Galaxy A22, Galaxy m51, galaxy 10s
Oneplus 8 pro

It is working fine on my devices Redmi note 8A dual, Mi A1, One plus 7Pro, Samsung galaxy note 10+, real me, nokia.

Problem is that it is not reproducing at our real devices. Just logs are logging into firebase crashlytics.

Kindly help me out.

Thank You.

**Comment by huycozy** [comment]
Hi @madhugill 
Based on the crash log, it's quite similar to #106493 which has been fixed recently. Please try upgrading plugin version to the latest and check if the crash still occurs or not.

**Comment by manmmohanIntello** [comment]
Hi @huycozy ,

As such the above solution. where we have tried upgrading the plugin doesn't resolved the issue. We have two Apps in which we are using 2 different versions of Camera Plugin.

App1 -- Camera Plugin Version 0.10.3
App2 -- Camera Plugin version 0.9.4+18

In both Apps the cameraController.takePicture() is throwing an error on the below mentioned devices 
Vivo- V2045, vivo 1904, V2142, Y35, V2036
Samsung - Galaxy A22, Galaxy m51, galaxy 10s.

We have tried clicking the images using the cameraController.startImageStream which is giving the images in the form of Stream. Now, the above error has gone but the issue is that in certain devices like One Plus 7Pro, One plus 9Pro, RealMe2 Pro, MI devices etc the images which are getting clicked are blurred. 
However, in certain devices like Samsung, Tecno  it is working fine.

We are using below code for clicking the images and for converting those CameraImage into the JPG Image File.

Clicking Images via Camera using startImageStream
___________________________________________________________________________________________________________ 

`await controller!.startImageStream((image) async {
        print('image steaming');
        print('image ${image.planes.last.bytes}');
        if (count < 2) {
          count++;
           return null;
         }
        controller?.stopImageStream();

        print('image steaming stopped');
        print('image planes -- ' + image.planes.length.toString());

        var img = await convertYUV420toImageColor(image);

        if (img == null) {
          return null;
        }
        await _saveImage(image, Directory("${extDir!.path}/"),
            "IMG_${DateTime.now().millisecondsSinceEpoch}.png",
            success: (filePath) {
          print('image steaming saved file');
          onComplete(filePath);
        });
      });
`
___________________________________________________________________________________________________________

convertYUV420toImageColor function code 
___________________________________________________________________________________________________________
`Future<Uint8List?> convertYUV420toImageColor(CameraImage image) async {
    try {
      final int width = image.width;
      final int height = image.height;
      final int uvRowStride = image.planes[1].bytesPerRow;
      final int uvPixelStride = image.planes[1].bytesPerPixel ?? 0;

      print("uvRowStride: " + uvRowStride.toString());
      print("uvPixelStride: " + uvPixelStride.toString());
      print('image Width -- ' + image.width.toString());
      print('image Height -- ' + image.height.toString());
      print('image P lanes -- ' + image.planes.length.toString());
      print('image Format -- ' + image.format.group.toString());
      print('image planes raw-- ' + image.format.raw.toString());
      // imgLib -> Image package from https://pub.dartlang.org/packages/image
      //var img = imglib.Image(width, height); // Create Image buffer

      final Directory directory =
          Directory('/storage/emulated/0/Download');
      var fileName = "dataFile_for_plane";

      for (int i = 0; i < image.planes.length; i++) {
        print("Saving data file");
        final File dataFile = File(
            '${directory.path}' + "/" + fileName + "_" + i.toString() + ".txt");
        var finalString = 'image Width -- ' +
            image.width.toString() +
            "\n" +
            'image Height -- ' +
            image.height.toString() +
            "\n" +
            'image Width -- ' +
            image.width.toString() +
            "\n" +
            'image Planes --' +
            image.planes[i].bytes.toString() +
            "\n" +
            'image Format -- ' +
            image.format.toString() +
            "\n" +
            'image Group -- ' +
            image.format.group.toString() +
            "\n" +
            'image planes raw --' +
            image.format.raw.toString() +
            "\n";
        await dataFile.writeAsString(finalString);
        print("Saved data file" + dataFile.path.toString());
      }
      var img = imglib.Image(height, width);

      // Fill image buffer with plane[0] from YUV420_888
      for (int x = 0; x < width; x++) {
        for (int y = 0; y < height; y++) {
          final int uvIndex =
              uvPixelStride * (x / 2).floor() + uvRowStride * (y / 2).floor();
          final int index = y * width + x;

          final yp = image.planes[0].bytes[index];
          final up = image.planes[1].bytes[uvIndex];
          final vp = image.planes[2].bytes[uvIndex];
          // Calculate pixel color
          int r = (yp + vp * 1436 / 1024 - 179).round().clamp(0, 255);
          int g = (yp - up * 46549 / 131072 + 44 - vp * 93604 / 131072 + 91)
              .round()
              .clamp(0, 255);
          int b = (yp + up * 1814 / 1024 - 227).round().clamp(0, 255);
          // color: 0x FF  FF  FF  FF
          //           A   B   G   R
          // //img.data[index] = shift | (b << 16) | (g << 8) | r;
          // if (img.boundsSafe(height - y, x)) {
          //   img.setPixelRgba(-(y + 1), x + 1, r, g, b, shift);
          // }
          if (img.boundsSafe(height - y, x)) {
            img.setPixelRgba(height - y, x, r, g, b, shift);
          }
        }
      }

      imglib.PngEncoder pngEncoder = new imglib.PngEncoder(level: 0, filter: 0);
      List<int> png = pngEncoder.encodeImage(img);
      // muteYUVProcessing = false;
      return Uint8List.fromList(png);
    } catch (e) {
      print(">>>>>>>>>>>> ERROR:" + e.toString());
    }
    return null;
  }`

___________________________________________________________________________________________________________

The above code is giving us blur images in certain devices like One Plus 9 Pro, One Plus 7 Pro, RealMe 2 Pro etc.

Any help in solving the above would be highly appreciated.

Thanks in advance.

**Comment by madhugill** [comment]
> Hi @madhugill Based on the crash log, it's quite similar to #106493 which has been fixed recently. Please try upgrading plugin version to the latest and check if the crash still occurs or not.

@huycozy 
I have gone through the raised issue #106493. 
Already tried the mentioned solutions of **@rifkyputra**. Still no fruitful achieved.
**This issue could be caused by unhandled catch error when calling initialize.
In his case he simply add .catchError and the problem is gone.**

Please suggest any other solution.

Thank You.

**Comment by huycozy** [comment]
@madhugill Can you confirm you have upgraded the plugin version to the latest but the crash still occurs? 

@manmmohanIntello 
Is this issue reproducible locally? If so, can you please share the output of `flutter run -v` and a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?

**Comment by madhugill** [comment]
@huycozy 

Yes I checked with upgraded plugin version camera 0.10.3. Still crash occurs. 

D/EGL_emulation(20657): app_time_stats: avg=120.86ms min=15.80ms max=248.38ms count=9
D/EGL_emulation(20657): app_time_stats: avg=107.76ms min=16.61ms max=298.71ms count=10
D/EGL_emulation(20657): app_time_stats: avg=113.16ms min=27.33ms max=191.62ms count=10
I/Camera  (20657): runPrecaptureSequence
I/Camera  (20657): refreshPreviewCaptureSession
D/CameraCaptureCallback(20657): CameraCaptureCallback | state: STATE_WAITING_PRECAPTURE_START | afState: 0 | aeState: 2
D/CameraCaptureCallback(20657): CameraCaptureCallback | state: STATE_WAITING_PRECAPTURE_DONE | afState: 0 | aeState: 2
I/Camera  (20657): captureStillPicture
D/Camera  (20657): Updating builder with feature: ExposureLockFeature
D/Camera  (20657): Updating builder with feature: ExposurePointFeature
D/Camera  (20657): Updating builder with feature: ZoomLevelFeature
D/Camera  (20657): Updating builder with feature: AutoFocusFeature
D/Camera  (20657): Updating builder with feature: NoiseReductionFeature
I/Camera  (20657): updateNoiseReduction | currentSetting: fast
D/Camera  (20657): Updating builder with feature: FocusPointFeature
D/Camera  (20657): Updating builder with feature: ResolutionFeature
D/Camera  (20657): Updating builder with feature: SensorOrientationFeature
D/Camera  (20657): Updating builder with feature: FlashFeature
D/Camera  (20657): Updating builder with feature: ExposureOffsetFeature
D/Camera  (20657): Updating builder with feature: FpsRangeFeature
I/Camera  (20657): sending capture request
D/CameraCaptureCallback(20657): CameraCaptureCallback | state: STATE_CAPTURING | afState: 0 | aeState: 2
D/CameraCaptureCallback(20657): CameraCaptureCallback | state: STATE_CAPTURING | afState: 0 | aeState: 5
D/CameraCaptureCallback(20657): CameraCaptureCallback | state: STATE_CAPTURING | afState: 0 | aeState: 5
D/CameraCaptureCallback(20657): CameraCaptureCallback | state: STATE_CAPTURING | afState: 0 | aeState: 5
D/CameraCaptureCallback(20657): CameraCaptureCallback | state: STATE_CAPTURING | afState: 0 | aeState: 5
I/Camera  (20657): unlockAutoFocus
I/Camera  (20657): refreshPreviewCaptureSession
D/EGL_emulation(20657): app_time_stats: avg=98.42ms min=14.10ms max=222.96ms count=12
D/CameraCaptureCallback(20657): CameraCaptureCallback | state: STATE_CAPTURING | afState: 0 | aeState: 5
D/CameraCaptureCallback(20657): CameraCaptureCallback | state: STATE_CAPTURING | afState: 0 | aeState: 5
D/CameraCaptureCallback(20657): CameraCaptureCallback | state: STATE_CAPTURING | afState: 0 | aeState: 5
D/CameraCaptureCallback(20657): CameraCaptureCallback | state: STATE_CAPTURING | afState: 0 | aeState: 5
D/CameraCaptureCallback(20657): CameraCaptureCallback | state: STATE_CAPTURING | afState: 0 | aeState: 2
D/CameraCaptureCallback(20657): CameraCaptureCallback | state: STATE_CAPTURING | afState: 0 | aeState: 5
I/Camera  (20657): open | onError
I/Camera  (20657): close
I/Camera  (20657): open | onClosed





[✓] Flutter (Channel stable, 3.3.8, on macOS 12.1 21C52 darwin-x64, locale en-IN)
[!] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    ✗ cmdline-tools component is missing
      Run path/to/sdkmanager --install "cmdline-tools;latest"
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run flutter doctor --android-licenses to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[!] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/[Xcode.app/Contents/Developer](http://xcode.app/Contents/Developer)
        sudo xcodebuild -runFirstLaunch
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.62.3)
[✓] Connected device (4 available)
[✓] HTTP Host Availability

**Comment by manmmohanIntello** [comment]
Hi @huycozy ,

Thanks for the reply. 

Yes, upon using the `await controller!.startImageStream((image)` the images are getting Blurred in the certain devices like RealMe 2 Pro, One Plus 7 Pro and One Plus 9 Pro  and MI devices.
However, in Tecno Phantom X and Samsung device it is rendering fine. Attached is the flutter logs, Video showing the issue and the complete Camera.dart file which has the code. 

Below are the links for the same.

Video showing the issue: https://drive.google.com/file/d/1qXNoLG6KtyVwZ86UaxzMx091WhqmHucX/view
Flutter Logs link: https://drive.google.com/file/d/11bUyfH0fEo-YN2GdlWwSWgA16-88YtR6/view?usp=share_link
Camera.dart complete code: https://drive.google.com/file/d/1HGYOMYcNrEOK6rH_QpiCd9cXM1w-Cjws/view?usp=sharing

Any help would be appreciated.

Thanks

**Comment by huycozy** [comment]
@madhugill Can you share the complete log output? The log provided above doesn't include crash log.

@manmmohanIntello As far as I see from your video and log, it looks like a different issue than this issue. There is no similar [crash log](https://github.com/flutter/flutter/issues/120423#issue-1579093020) on your stacktrace. I would suggest finding the existing issues in [repository issues](https://github.com/flutter/flutter/issues). If there is no similar issue, please open new file for it.

**Comment by manmmohanIntello** [comment]
@huycozy ,

thanks for the reply.

I have opened a new thread for the similar issue.

https://github.com/flutter/flutter/issues/120877

**Comment by madhugill** [comment]
I am closing this as @manmmohanIntello has opened a new thread for this.

Thank You.
