### ISSUE TITLE
[camerax] Implement focus mode configuration

### ISSUE THREAD

**Issue by camsim99** [flutter/flutter#120467]
In the camera plugin API, there are two methods related to the configuration of the focus mode. These should be implemented in the CameraX plugin:

- [ ] `setFocusMode(....)`
- [x] `setFocusPoint(..)`

**Comment by jstevensconverus** [comment]
Hello, is there an update on this issue? My company is unable to use this plugin until the issue is resolved.

**Comment by camsim99** [comment]
> Hello, is there an update on this issue? My company is unable to use this plugin until the issue is resolved.

I have just begun working on this feature; will update here when a PR is submitted for review.

**Comment by camsim99** [comment]
Looking into how we may be able to replicate auto/locked Flutter-defined focus modes and a helpful discussion that I likely will need to implement this: https://groups.google.com/a/android.com/g/camerax-developers/c/VRsER_nHeHM?pli=1.

**Comment by camsim99** [comment]
Working on implementing `setFocusMode` and it's not clear to me how to implement locked versus auto mode, so I want to write out my thoughts as of now so I can correct my assumptions as needed with this as a baseline.

***Locked mode:***
To implement locked mode in `camera_android`, we did something like 
```java
// When locking the auto-focus the camera device should do a one-time focus and afterwards
// set the auto-focus to idle. This is accomplished by setting the CONTROL_AF_MODE to
// CONTROL_AF_MODE_AUTO.
captureRequestBuilder.set(CaptureRequest.CONTROL_AF_MODE, CaptureRequest.CONTROL_AF_MODE_AUTO);
captureRequestBuilder.set(
  CaptureRequest.CONTROL_AF_TRIGGER, CaptureRequest.CONTROL_AF_TRIGGER_START); 
captureSession.capture(captureRequestBuilder.build(), null, backgroundHandler);
captureRequestBuilder.set(
  CaptureRequest.CONTROL_AF_TRIGGER, CameraMetadata.CONTROL_AF_TRIGGER_IDLE);
captureSession.setRepeatingRequest(
  captureRequestBuilder.build(), null, backgroundHandler);
```
It's my understanding that this is what is going on under the hood in CameraX when we set an AF `MeteringPoint` via [`startFocusAndMetering`](https://developer.android.com/reference/androidx/camera/core/CameraControl#startFocusAndMetering(androidx.camera.core.FocusMeteringAction)).

***Auto mode:***
To implement auto mode in `camera_android`, we did something like
```java
captureRequestBuilder.set(
    CaptureRequest.CONTROL_AF_MODE,
    recordingVideo
        ? CaptureRequest.CONTROL_AF_MODE_CONTINUOUS_VIDEO
        : CaptureRequest.CONTROL_AF_MODE_CONTINUOUS_PICTURE);
// Cancel existing AF state.
captureRequestBuilder.set(
    CaptureRequest.CONTROL_AF_TRIGGER, CameraMetadata.CONTROL_AF_TRIGGER_CANCEL);
captureSession.capture(captureRequestBuilder.build(), null, backgroundHandler);
// Set AF state to idle again.
captureRequestBuilder.set(
    CaptureRequest.CONTROL_AF_TRIGGER, CameraMetadata.CONTROL_AF_TRIGGER_IDLE);
captureSession.capture(captureRequestBuilder.build(), null, backgroundHandler);
```
To implement this with CameraX, I believe we will need to remove any AF `MeteringPoint`s from any running `FocusMeteringAction`s set via `startFocusandMetering` or, if we have only set AF `MeteringPoint`s, cancel focus and metering altogether. This is because the continuous auto focus mode is CameraX's default mode.

**Comment by camsim99** [comment]
It turns out that CameraX always uses auto focus mode, preferring `CaptureRequest.CONTROL_AF_MODE` for `CaptureRequest. CONTROL_AF_MODE_AUTO`, but may fallback to `CONTROL_AF_MODE_CONTINUOUS_VIDEO`/`CONTROL_AF_MODE_CONTINUOUS_PICTURE` based on [the source code](https://osscs.corp.google.com/androidx/platform/frameworks/support/+/androidx-main:camera/camera-camera2/src/main/java/androidx/camera/camera2/internal/FocusMeteringControl.java;drc=423251ddcc34f0938bd2741bf721acd1f5fc746f;l=197), and never sets `CaptureRequest.CONTROL_AF_TRIGGER` to `CameraMetadata.CONTROL_AF_TRIGGER_IDLE`.

To work around this, I'm going to (1) try implementing locked focus mode with Camera2 interop, and depending on the results of that and digging deeper into the philosophy of CameraX only using autofocus mode, (2) consider the pros/cons of not implementing locked focus mode.

**Comment by camsim99** [comment]
I just tried using Camera2CameraControl to manually lock the focus mode, with two attempts:

_Attempt 1 (fail):_
I added the capture request options `CameraMetadata.CONTROL_AF_TRIGGER_IDLE`  for `CaptureRequest.CONTROL_AF_TRIGGER` with [`Camera2CameraControl.addCaptureRequestOptions`](https://developer.android.com/reference/androidx/camera/camera2/interop/Camera2CameraControl#addCaptureRequestOptions(androidx.camera.camera2.interop.CaptureRequestOptions)), and I still saw autofocus.

_Attempt 2 (success?):_
I set the capture request options `CaptureRequest.CONTROL_AF_MODE_AUTO` for `CaptureRequest.CONTROL_AF_MODE` and `CameraMetadata.CONTROL_AF_TRIGGER_IDLE` for `CaptureRequest.CONTROL_AF_TRIGGER` with [`Camera2CameraControl.setCaptureRequestOptions`](https://developer.android.com/reference/androidx/camera/camera2/interop/Camera2CameraControl#setCaptureRequestOptions(androidx.camera.camera2.interop.CaptureRequestOptions)), and it actually seemed to work, though I wonder how this may conflict with the default behavior.
