### ISSUE TITLE
RichText doesn't work with fontVariations 'wght'

### ISSUE THREAD

**Issue by asaarnak** [flutter/flutter#120446]
Variable font in RichText does not work with FontVariation('wght', 700.0)

https://user-images.githubusercontent.com/808420/218133209-c106c67d-7481-4af6-852b-802b0412f53e.mp4

Fonts used: https://fonts.google.com/noto/specimen/Noto+Sans+Symbols

I created reproduceable example project here with demo video:
https://github.com/asaarnak/testVariableFonts

**Comment by jason-simmons** [comment]
The sample app is setting the `fontFamily` to `NotoSansSymbolsVariable` using the `ThemeData`.

`RichText` does not default to the style declared in the `Theme`.  So the text is being rendered with some other font family that does not support the `wght` font variation.

The `RichText` can select the variable font by specifying a `TextStyle` that uses `fontFamily: 'NotoSansSymbolsVariable'`.  Or you can extract styles from the `Theme` by using `Theme.of(context).textTheme`.

**Comment by asaarnak** [comment]
Ok. Thanks for detailed answer!
I expected Theme to forward fontFamily to RichText and work like Text widget does.
Thats why it seemed like a bug to me.
