### ISSUE TITLE
[Impeller] Refactor CustomColorAttachmentPixelFormatContext.

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#120499]
Context: https://github.com/flutter/engine/pull/39111

https://github.com/flutter/engine/pull/39111 Introduced a proxy object as a way to override the color attachment pixel format from a context (`CustomColorAttachmentPixelFormatContext`).  It was required because there was no safe way to override that value otherwise.  It's not ideal since it creates an extra layer of indirection which could be confusing when debugging.  We need to come up with a better way to split out the pixel format.  There is hope that as we work on vulkan and offscreen buffers whose pixelformat doesn't match the surface we are going to be forced to sort this out.

**Comment by chinmaygarde** [comment]
Ran into this as I was reworking the capability checks in https://github.com/flutter/engine/pull/40244 for Vulkan.

**Comment by yaakovschectman** [comment]
This has been reverted by https://github.com/flutter/flutter/pull/122527
