### ISSUE TITLE
dart:developer log is inconsistent between IDE's and platforms

### ISSUE THREAD

**Issue by JCKodel** [flutter/flutter#120474]
I was experimenting with ANSI colors in log to create a new logging package, using both `print` and `dart:developer/log` functions.

I found some inconsistences:

1) `dart:developer`.`log` doesn't work at all in web platform. Nothing is printed. (print works just fine). Console also doesn't work (meaning: running in a console using `flutter run`)

2) Consoles (including VSCode console) shows ANSI color for both `print` and `log`, but Android Studio only shows color for `print`.

Example code:

```dart
const greenForeground = "\u001b[32m";
const yellowBackground = "\u001b[43;1m";
const resetColor = "\u001b[0m";

print("${greenForeground}${yellowBackground}This is print with green foreground and yellow background.${resetColor}");
log("${greenForeground}${yellowBackground}This is dart:developer.log with green foreground and yellow background.${resetColor}");
```

VSCode output for MacOS (and maybe Android, iOS, Linux and Windows):
![image](https://user-images.githubusercontent.com/379339/218179260-4969a742-abc1-47d3-9d60-d57bd3aa8550.png)

Same for Android Studio Electric Eel (#AI-221.6008.13.2211.9477386) (notice log doesn't work with ANSI codes)
<img width="762" alt="image" src="https://user-images.githubusercontent.com/379339/218179609-82ed7030-279e-4891-a393-6d6a18b16254.png">

Running on Chrome:
This is VSCode:
<img width="589" alt="image" src="https://user-images.githubusercontent.com/379339/218179867-5d70c19c-1633-4dec-9fb3-2803d27c9563.png">

This is Chrome console (missing the `log` entry and also the green color should be dark, not bright (considering ANSI 16 colors specification)):
<img width="546" alt="image" src="https://user-images.githubusercontent.com/379339/218179938-b7ea253a-cd66-4314-91a6-31218de120b8.png">

Running on console (default MacOS Terminal app) (Notice here is the wrong yellow (should be brighter, and `log` is missing)):
MacOS build:
<img width="612" alt="image" src="https://user-images.githubusercontent.com/379339/218180426-ee60df30-7c95-4c46-9965-db5f140ad3b8.png">

Web build:
<img width="624" alt="image" src="https://user-images.githubusercontent.com/379339/218180655-3183a384-6192-4d0d-9d86-23297b7faf53.png">

Considering `print` is limited (specially on Android), `dart:developer` should provide a better cross-platform log option that is reliable no matter the platform it is running =(

<details><summary>flutter doctor</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.3, on macOS 12.6.2 21G320 darwin-x64, locale en-BR)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] VS Code (version 1.75.0)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

• No issues found!
```

</details>

**Comment by JCKodel** [comment]
> Hence, this may not be feasible per quoted comment.
>
@darshankawar I do not agree, since `print` works just fine. It's not about not being possible or feasible, it's about having the functionality already well implemented in `print`, but not in the supposed recommended package for logging.

**Comment by darshankawar** [comment]
Thanks for the feedback.

> `dart:developer` should provide a better cross-platform log option that is reliable no matter the platform it is running =(

This probably indicates the changes should be implemented at dart side.


> I found some inconsistences:
> 
> 1. `dart:developer`.`log` doesn't work at all in web platform. Nothing is printed. (print works just fine). Console also doesn't work (meaning: running in a console using `flutter run`)
> 2. Consoles (including VSCode console) shows ANSI color for both `print` and `log`, but Android Studio only shows color for `print`.

Maybe this github repo https://github.com/dart-lang/logging/issues is where you can raise this issue, because I am not sure if the changes you suggested would be applicable at framework level. What do you think ?

**Comment by JCKodel** [comment]
@darshankawar Ok, it makes sense.
