### ISSUE TITLE
[camerax] Implement resolution configuration

### ISSUE THREAD

**Issue by camsim99** [flutter/flutter#120462]
With the camera plugin, developers are able to specify a `ResolutionPreset` to choose a resolution for the camera images, preview, and video recording (see [source](https://github.com/flutter/plugins/blob/main/packages/camera/camera_platform_interface/lib/src/platform_interface/camera_platform.dart#L52)). In addition, `onCameraResolutionChanged(int cameraId)` is used to listen for changes in camera resolution (see [source](https://github.com/flutter/plugins/blob/main/packages/camera/camera_android/lib/src/android_camera.dart#L181)).

Both of these will need to be implemented in the CameraX plugin.

**Comment by iakmds** [comment]
Thank you for your efforts @camsim99, I can't wait to try out CameraX.

Regarding the resolution configuration, will it be possible to select a custom resolution apart from the presets we already have? There is also an issue (#45665) about this; I believe this is a much requested feature. Thanks again!

**Comment by camsim99** [comment]
> Regarding the resolution configuration, will it be possible to select a custom resolution apart from the presets we already have? There is also an issue (#45665) about this; I believe this is a much requested feature. Thanks again!

@iakmds thank you for pointing this out! I will track this issue to see if this is something a feature we may want to support, likely once the CameraX plugin is completed.

**Comment by iakmds** [comment]
On a side note, in case it is out of the scope to select a fully custom resolution, maybe it should be considered to get a list of all resolution presets that the specific camera supports, something like this:

![resolutions](https://user-images.githubusercontent.com/111225446/220898653-a5308f46-324b-4a69-af90-eab1c8ba8267.png)
