### ISSUE TITLE
Issue to show C with Cedilla (ç) in a Text Widget

### ISSUE THREAD

**Issue by SimoneMassai** [flutter/flutter#120447]
Hello, I'm trying to write in a simple Text Widget the world: 'Français', but as result i see instead: 'Fran��ais'.

So it seems that the C with Cedilla (ç) doesn't like to Flutter, and it give me in console the following error:

Finished with error: Bad UTF-8 encoding (U+FFFD; REPLACEMENT CHARACTER) found while decoding string: LANGUAGES: C4PLanguageConfig(label: Fran��ais, languageCode: fr, countryCode: FR)
. The Flutter team would greatly appreciate if you could file a bug explaining exactly what you were doing when this happened:
https://github.com/flutter/flutter/issues/new/choose
The source bytes were:
[76, 65, 78, 71, 85, 65, 71, 69, 83, 58, 32, 67, 52, 80, 76, 97, 110, 103, 117, 97, 103, 101, 67, 111, 110, 102, 105, 103, 40, 108, 97, 98, 101, 108, 58, 32, 70, 114, 97, 110, 239, 191, 189, 239, 191, 189, 97, 105, 115, 44, 32, 108, 97, 110, 103, 117, 97, 103, 101, 67, 111, 100, 101, 58, 32, 102, 114, 44, 32, 99, 111, 117, 110, 116, 114, 121, 67, 111, 100, 101, 58, 32, 70, 82, 41, 10]

flutter doctor:

[√] Flutter (Channel stable, 3.0.4, on Microsoft Windows [Versione 10.0.19045.2486], locale it-IT)
    • Flutter version 3.0.4 at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 85684f9300 (8 months ago), 2022-06-30 13:22:47 -0700
    • Engine revision 6ba2af10bb
    • Dart version 2.17.5
    • DevTools version 2.12.2

Checking Android licenses is taking an unexpectedly long time...[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\simone.massai\AppData\Local\Android\sdk
    • Platform android-31, build-tools 33.0.0
    • Java binary at: C:\Program Files\Android\Android Studio1\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[!] Android Studio (version 2022.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
[√] HTTP Host Availability
    • All required HTTP hosts are available

**Comment by huycozy** [comment]
Hi @SimoneMassai 
I can not reproduce the issue on Web as below demo. Please retry on the latest `stable` and `master` Flutter channels and check if it still occurs or not.

If it still occurs, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this. Thanks!

<details>
<summary>Demo (Web)</summary>

![Screenshot 2023-02-13 at 11 23 49](https://user-images.githubusercontent.com/104349824/218370050-56c97811-d49d-4fab-a76b-b428e3015907.png)

</details>

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.7.3, on macOS 13.0.1 22A400 darwin-x64, locale en-VN)
    • Flutter version 3.7.3 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9944297138 (17 hours ago), 2023-02-08 15:46:04 -0800
    • Engine revision 248290d6d5
    • Dart version 2.19.2
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Users/huynq/Library/Java/JavaVirtualMachines/corretto-1.8.0_302/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment Corretto-8.302.08.1 (build 1.8.0_302-b08)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.75.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.58.0

[✓] Connected device (3 available)
    • SM T225 (mobile) • R9JT3004VRJ • android-arm64  • Android 13 (API 33)
    • macOS (desktop)  • macos       • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)     • chrome      • web-javascript • Google Chrome 110.0.5481.77

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```

```bash
[!] Flutter (Channel master, 3.8.0-10.0.pre.31, on macOS 13.0.1 22A400 darwin-x64, locale en-VN)
    • Flutter version 3.8.0-10.0.pre.31 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 527977b6af (12 hours ago), 2023-02-12 08:54:35 -0500
    • Engine revision b7e80ad6ef
    • Dart version 3.0.0 (build 3.0.0-231.0.dev)
    • DevTools version 2.21.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.75.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.58.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 110.0.5481.77

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```
</details>

**Comment by SimoneMassai** [comment]
Hi @huycozy sorry for the late reply.
Anyway i've tried to upgrade Flutter to the last version (with cmd: **flutter upgrade**) and also Dart (with cmd: **dart pub upgrade**), then clean (**flutter clean**) and get (**flutter pub get**), but the result are the same both for **master channel** as for **stable channel**.

If you want some code, it's pretty symple: i get languages from a conf as a list of C4PLanguageConfig object (characterized by 3 field: label, languageCode, countryCode):

_const factory C4PLanguageConfig({
    @Default('English') @JsonKey(name: 'label') String label,
    @Default('en') @JsonKey(name: 'languageCode') String languageCode,
    @Default('GB') @JsonKey(name: 'countryCode') String countryCode,
  }) = _C4PLanguageConfig;_

Inside the controller of my view, i iterate on this list of C4PLanguageConfig taken from the config and add it to other list within the view itself:

/// List that will contains all languages of conf, used to populate the radio buttons
  final List<C4PLanguageConfig> languages = [];

...

 @override
  void onInit() async {
// Get languages from config and populate the list languages
    getC4PConfig.languages.forEach(
      (lang) {
        print('LANGUAGE: ${lang.toString()}');
        // Set the default language of radio button as the locale language of device
        if (lang.languageCode == languageCode) {
          languageSelected = lang.obs;
        }
        languages.add(lang);
      },
    );
...
}

Then i use this list to populate the label (that's a simple Text widget) of radio buttons in the view, and the result, running in debug mode for a Web App on Chrome, is this:
![Immagine 2023-02-15 123254](https://user-images.githubusercontent.com/11429780/219053674-d2c5e3e9-b7df-4e18-85db-534a022b958e.jpg)

Looking at **console**, i can see the **print** inside the forEach above, and i've this:

LANGUAGE: C4PLanguageConfig(label: English, languageCode: en, countryCode: GB)

Finished with error: Bad UTF-8 encoding (U+FFFD; REPLACEMENT CHARACTER) found while decoding string: LANGUAGE: C4PLanguageConfig(label: Fran��ais, languageCode: fr, countryCode: FR)
. The Flutter team would greatly appreciate if you could file a bug explaining exactly what you were doing when this happened:
https://github.com/flutter/flutter/issues/new/choose
The source bytes were:
[76, 65, 78, 71, 85, 65, 71, 69, 58, 32, 67, 52, 80, 76, 97, 110, 103, 117, 97, 103, 101, 67, 111, 110, 102, 105, 103, 40, 108, 97, 98, 101, 108, 58, 32, 70, 114, 97, 110, 239, 191, 189, 239, 191, 189, 97, 105, 115, 44, 32, 108, 97, 110, 103, 117, 97, 103, 101, 67, 111, 100, 101, 58, 32, 102, 114, 44, 32, 99, 111, 117, 110, 116, 114, 121, 67, 111, 100, 101, 58, 32, 70, 82, 41, 10]

LANGUAGE: C4PLanguageConfig(label: Italiano, languageCode: it, countryCode: IT)

So i think that the error happens before to show the text in the label of radio button, it happens directly during the forEach in onInit.

I can show you also **flutter doctor -v**:
For **MASTER**:

[√] Flutter (Channel master, 3.8.0-12.0.pre.73, on Microsoft Windows [Versione 10.0.19045.2486], locale it-IT)
    • Flutter version 3.8.0-12.0.pre.73 on channel master at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision df41e58f6f (37 minutes ago), 2023-02-15 08:30:38 -0500
    • Engine revision 1328c4bc62
    • Dart version 3.0.0 (build 3.0.0-238.0.dev)
    • DevTools version 2.21.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\simone.massai\AppData\Local\Android\sdk
    • Platform android-31, build-tools 33.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2022.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 110.0.5481.100
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 110.0.1587.41

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.


For **STABLE**:

[√] Flutter (Channel stable, 3.7.3, on Microsoft Windows [Versione 10.0.19045.2486], locale it-IT)
    • Flutter version 3.7.3 on channel stable at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9944297138 (7 days ago), 2023-02-08 15:46:04 -0800
    • Engine revision 248290d6d5
    • Dart version 2.19.2
    • DevTools version 2.20.1

[X] Windows Version (Unable to confirm if installed Windows version is 10 or greater)

Checking Android licenses is taking an unexpectedly long time...[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\simone.massai\AppData\Local\Android\sdk
    • Platform android-31, build-tools 33.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2022.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)

[√] VS Code (version 1.75.0)
    • VS Code at C:\Users\simone.massai\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.52.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Versione 10.0.19045.2486]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 110.0.5481.100
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 110.0.1587.41

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.

Looking the flutter doctor, i see one issue that is the same for stable and master, and it's about Visual Studio not installed, but i think it's not necessary for my case (anyway i develop with Android Studio, and i'm developing a Web App\Mobile App) and other issue that's only in stable channel but not in master, and it's about the Windows Version (Unable to confirm if installed Windows version is 10 or greater), but i don't think it's related to my issue.

Have you some suggestions?

Thanks in advance

**Comment by huycozy** [comment]
@SimoneMassai I'm taking a look at your screenshot, it seems to be the issue with `RadioListTile` but I'm not sure because you haven't mentioned the Widget you used. 

Below is the result and minimal sample code I tried:

<details>
<summary>Demo</summary>

![Screenshot 2023-02-16 at 10 02 00](https://user-images.githubusercontent.com/104349824/219257703-cc53581b-278e-4605-9aa0-53cadbabab55.png)

</details>

<details>
<summary>Sample code</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
        body: Center(
          child: RadioListTile(
            title: const Text("Français"),
            value: false,
            groupValue: false,
            onChanged: (value) {},
          ),
        ),
      ),
    );
  }
}
```
</details>

As you can see, the text `Français` is displayed well. And there is no error log from the console. The result is the same on Windows as well.

In order to make issue clearer for verifying, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this. You can continue modifying my sample code here. 

Also, when the issue still happens with new sample code, please provide the complete output of `flutter run -v` so that we can continue investigating the issue. Thanks!
