### ISSUE TITLE
I get `Command PhaseScriptExecution failed` when convert ios objective c plugin to macos plugin

### ISSUE THREAD

**Issue by H-Khoujani** [flutter/flutter#120441]
## Steps to Reproduce

1. I ran `flutter create -i swift test`
2. Then I deleted the macos folder and duplicated the ios folder and renamed it to macos and changed all the ios configurations to macos such as base sdk and destinations.
3. at the end when I run the project I saw this error

``Command PhaseScriptExecution failed with a nonzero exit code``

```
```

[✓] Flutter (Channel stable, 3.3.6, on macOS 13.1 22C65 darwin-arm, locale
    en-US)
    • Flutter version 3.3.6 on channel stable at
      /Users/khoujani/Documents/flutter3.3.6
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6928314d50 (4 months ago), 2022-10-25 16:34:41 -0400
    • Engine revision 3ad69d7be3
    • Dart version 2.18.2
    • DevTools version 2.15.0

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/khoujani/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.74.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.1 22C65 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 109.0.5414.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```
```

</details>

**Comment by huycozy** [comment]
Hi @H-Khoujani 
It doesn't seem like a valid approach for developing a macOS app in Flutter. Please share the document you are following here if any.
