### ISSUE TITLE
[Impeller] Allow instrumentation of allocations.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#120502]
We'd like to be able to tell how many allocations and deallocations took place in a given period of time (say a frame workload) and also generate histograms of the allocations along with an estimate of how long each allocation survived. Some requirements:

* Allow turning off this instrumentation in release modes.
  * Perhaps wrap existing allocators in a new `impeller::InstrumentedAllocator` but only in non-release modes.
* Allow dumping information on allocations to the timeline.
* Allow tracking how long each allocation survived.
  * If there are multiple short lived allocations, we could be doing something better.
  * Perhaps via delegation in the new `impeller::InstrumentedAllocator`.
* Allow additional debug information to be attached to allocations.

**Comment by chinmaygarde** [comment]
cc @bdero @jonahwilliams @dnfield

**Comment by jonahwilliams** [comment]
I hacked together something in allocator: https://github.com/flutter/engine/pull/39445/files#diff-c06f6013a7dff874764ac3521849f6acbc35a3265a977a70483330e4a25d5469R48

Off in release mode and requires a second toggle.

**Comment by chinmaygarde** [comment]
Ah, ok. I was thinking a we could wrap allocators to instrument them. But this works too.

**Comment by jonahwilliams** [comment]
I can look into doing that instead, I just wasn't sure where to start on the plumbing side of things so I took the shortest path

**Comment by jonahwilliams** [comment]
We do this via devicelab benchmarks now
