### ISSUE TITLE
i have this issue " Upstream repository https://github.com/samstickkz/login.git is not a standard remote" 

### ISSUE THREAD

**Issue by samstickkz** [flutter/flutter#120525]
i have not been able to see a good fix on youtube or anywhere... [](url) how can i fix this ?
<img width="723" alt="Screenshot 2023-02-11 at 2 20 25 PM" src="https://user-images.githubusercontent.com/39702515/218260238-6334de2a-90c6-4715-984e-9b81c77db356.png">

**Comment by darshankawar** [comment]
@samstickkz 
`Upstream repository https://github.com/samstickkz/login.git` this doesn't look like the expected repo that `flutter doctor -v` expects. Usually it should be something like below:

`Upstream repository https://github.com/flutter/flutter.git` 

Not sure how are you seeing the said repo. Have you properly installed the Flutter sdk as mentioned in the official documentation ? https://docs.flutter.dev/get-started/install/macos

I suggest you to follow the recommended approach as mentioned in the documentation and try again.
Closing for now. If the similar log persists, write in comments and I'll reopen it.
