### ISSUE TITLE
Building Beautiful UIs with Flutter - Step 8

### ISSUE THREAD

**Issue by driftavalli** [flutter/flutter#12051]
## Steps to Reproduce

The tutorial uses the defaultTargetPlatform property in order to specify which platform but this generates an error: NoSuchMethodError: Class 'FriendlyChatApp' has no instance getter 'defaultTargetPlatform'. However changing this to 'Theme.of(context).platform' used later in the tutorial seems to work. Is defaultTargetPlatform no longer valid?

## Logs

Run your application with `flutter run` and attach all the log output.

Launching lib/main.dart on Android SDK built for x86 64 in debug mode...
Initializing gradle...                                0.8s
Resolving dependencies...                             1.3s
Running 'gradlew assembleDebug'...                   10.6s
Built build/app/outputs/apk/app-debug.apk (21.2MB).
Installing build/app/outputs/apk/app.apk...           1.1s
I/flutter ( 4013): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 4013): The following NoSuchMethodError was thrown building FriendlychatApp(dirty):
I/flutter ( 4013): Class 'FriendlychatApp' has no instance getter 'defaultTargetPlatform'.
I/flutter ( 4013): Receiver: Instance of 'FriendlychatApp'
I/flutter ( 4013): Tried calling: defaultTargetPlatform
I/flutter ( 4013): When the exception was thrown, this was the stack:
I/flutter ( 4013): #0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
I/flutter ( 4013): #1      Object.noSuchMethod (dart:core-patch/object_patch.dart:46)
I/flutter ( 4013): #2      FriendlychatApp.build (file:///home/driftavalii/workspace/work.flutter/my_friendlychat/lib/main.dart:27)
I/flutter ( 4013): #3      StatelessElement.build (package:flutter/src/widgets/framework.dart:3610)
I/flutter ( 4013): #4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3555)
I/flutter ( 4013): #5      Element.rebuild (package:flutter/src/widgets/framework.dart:3456)
I/flutter ( 4013): #6      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3535)
I/flutter ( 4013): #7      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3530)
I/flutter ( 4013): #8      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899)
I/flutter ( 4013): #9      Element.updateChild (package:flutter/src/widgets/framework.dart:2702)
I/flutter ( 4013): #10     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:759)
I/flutter ( 4013): #11     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:730)
I/flutter ( 4013): #12     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:676)
I/flutter ( 4013): #13     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2240)
I/flutter ( 4013): #14     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:675)
I/flutter ( 4013): #15     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding&WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:566)
I/flutter ( 4013): #16     runApp (package:flutter/src/widgets/binding.dart:608)
I/flutter ( 4013): #17     main (file:///home/driftavalii/workspace/work.flutter/my_friendlychat/lib/main.dart:5)
I/flutter ( 4013): #18     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:265)
I/flutter ( 4013): #19     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
I/flutter ( 4013): ════════════════════════════════════════════════════════════════════════════════════════════════════
Syncing files to device Android SDK built for x86 64...      
D/EGL_emulation( 4013): eglCreateContext: 0x7fe007bcaf40: maj 2 min 0 rcv 2
D/EGL_emulation( 4013): eglMakeCurrent: 0x7fe007bcaf40: ver 2 0 (tinfo 0x7fe0101540c0)
D/        ( 4013): HostConnection::get() New Host Connection established 0x7fe007bcef00, tid 4027
W/        ( 4013): Unrecognized GLES max version string in extensions: ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_dma_v1 
D/EGL_emulation( 4013): eglMakeCurrent: 0x7fe007bcaf40: ver 2 0 (tinfo 0x7fe010154160)
I/Choreographer( 4013): Skipped 75 frames!  The application may be doing too much work on its main thread.

🔥  To hot reload your app on the fly, press "r". To restart the app entirely, press "R".
An Observatory debugger and profiler on Android SDK built for x86 64 is available at: http://127.0.0.1:8106/
For a more detailed help message, press "h". To quit, press "q".

Run `flutter analyze` and attach any output of that command also.

Analyzing /home/driftavalii/workspace/work.flutter/my_friendlychat...
  error • Undefined name 'defaultTargetPlatform' at lib/main.dart:27:14 • undefined_identifier
  error • The constructor returns type 'dynamic' that isn't of expected type 'Widget' at test/widget_test.dart:15:29 • strong_mode_invalid_cast_new_expr
  error • Undefined class 'MyApp' at test/widget_test.dart:15:33 • undefined_class
  hint • Unused import at test/widget_test.dart:10:8 • unused_import
4 issues found.
(Ran in 7.0s)

## Flutter Doctor

Paste the output of running `flutter doctor` here.

[✓] Flutter (on Linux, locale en_CA.UTF-8, channel master)
    • Flutter at /home/driftavalii/workspace/flutter
    • Framework revision 4262c1e9d3 (4 days ago), 2017-09-08 16:47:40 -0700
    • Engine revision 2d7c30033d
    • Tools Dart version 1.25.0-dev.11.0

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at /home/driftavalii/Android/Sdk/
    • Platform android-25, build-tools 25.0.3
    • ANDROID_HOME = /home/driftavalii/Android/Sdk/
    • Java binary at: /usr/local/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] Android Studio (version 2.3)
    • Android Studio at /usr/local/android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.1)
    • Flutter plugin version 16.0
    • Dart plugin version 171.4694.29

[✓] Connected devices
    • Android SDK built for x86 64 • emulator-5554 • android-x64 • Android 6.0 (API 23) (emulator)

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by itsJoKr** [comment]
Hi. Do you have this import in your file: 

`import 'package:flutter/foundation.dart';`?

**Comment by Hixie** [comment]
Using Theme.of().platform is better, but if we do suggest using defaultTargetPlatform, we will need to also say to import foundation.

**Comment by itsJoKr** [comment]
It's already written to import foundation in that codelab first time the `defaultTargetPlatform` is used. I got stuck on this same step. It's easy to overlook it, because you is usually ignore reading imports.

**Comment by driftavalli** [comment]
yeah, seems I did overlook it, importing foundation.dart does resolve it. thanks.
