### ISSUE TITLE
Factor out MaterialLocalizations now that it depends on intl

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#12050]
With DatePicker localized, we'll have moved all our `intl` dependencies into one class, MaterialLocalizations, at which point we should factor it out into its own package so that people don't have to pay any of that cost if they don't want our localization logic. (The default localization for English can just have hard-coded logic for thousands separators, etc).

Suggestion from @HansMuller (entered here by @yjbanov):

Assuming that `TimeOfDay` isn't exclusively for the material time picker, we should consider moving it and the corresponding material localization code, to the widgets library and the WidgetsLocalizations class.

**Comment by yjbanov** [comment]
FYI, added a suggestion from @HansMuller to the description, based on discussion on https://github.com/flutter/flutter/pull/12166.
