### ISSUE TITLE
Allow widgets to be marked as "dirty" for reactive UI update

### ISSUE THREAD

**Issue by lukehutch** [flutter/flutter#120545]
## Use case

Flutter needs a much simpler state-change-driven reactive UI update system. All the state-tracking systems are cumbersome. The simplest solution I have found is [this](https://suragch.medium.com/flutter-state-management-for-minimalists-4c71a2f2f0c1), but it's still more complex than it should be.

I want to create a simpler state management system for Flutter, but I can't see how to do it with the current widget system.

I created a [simple reactive dataflow library](https://github.com/lukehutch/tiny-reactive-dataflow) in Javascript that is very powerful. Events feed into sources in a DAG of value-transforming functions, and value changes that "fall out of the end of the DAG" are pushed into the DOM. This works very well for the Web.

In Flutter, classes like `ValueListenableBuilder` can do the same thing given a `ValueNotifier`. However, you have to wrap every dynamic part of your UI tree with a `ValueListenableBuilder` to use this function.

In order to build something similar to my library for Flutter, I would really like to be able to (1) record the wrapping `Widget` when a method or field is used on a specific class, e.g. if `MyValueNotifier.value` is accessed, then look to see which `Widget`'s constructor is nearest the top of the call stack; and (2) add a one-time listener that marks the wrapping `Widget` as dirty (needing to be rebuilt) if the dependent value changes, similar to how `ValueListenableBuilder` works, but applicable to any type of widget without wrapping the widget with `ValueListenableBuilder`.

## Proposal

Honestly I don't know Dart or Flutter well enough yet to know what changes would be needed to enable this, but I don't think this can be implemented without changes to Dart (for (1)) and/or Flutter (for (2)).

**Comment by Clavum** [comment]
It sounds like what you need is to create your own custom widget. It is possible without changes to Flutter. For example:

```dart
abstract class DataListener extends StatefulWidget {
  const DataListener({super.key});

  // Usages of your DataListener will implement this.
  Widget build(BuildContext context);

  @override
  State<DataListener> createState() => _DataListenerState();
}

class _DataListenerState extends State<DataListener> {
  Widget? currentWidget;

  @override
  Widget build(BuildContext context) {
    return currentWidget ?? _buildAndListen(context);
  }

  Widget _buildAndListen(BuildContext context) {
    // Somehow start listening to which value notifiers are fetched.
    final result = widget.build(context);
    // Stop listening. Now check which ones were fetched between these two lines.
    // Finally, subscribe to that data, something like
    // someValueNotifier.addListener(() => setState(() {currentWidget = null;}));
    return result;
  }
}
```

Usage would then be as simple as extending that custom widget. Now build is called on every update of the value notifier.
```dart
class SomeWidget extends DataListener {
  const SomeWidget({super.key});

  @override
  Widget build(BuildContext context) {
    return Text(someValueNotifier.value);
  }
}
```

This approach is just like how the popular package [riverpod](https://pub.dev/packages/riverpod) works. It is also the exact approach I used for [a project of mine](https://github.com/Clavum/simple_framework).

Indeed, it seems rather impossible to do this with Flutter's current capabilities without using a custom widget. However, my understanding is that to make it otherwise would essentially be bypassing Flutter's principle of widgets and their dependencies. It is perhaps better for a widget to declare its intention to use your implementation, either through a listener or extending your custom class.

**Comment by darshankawar** [comment]
@lukehutch 
Please check above comment and see if it helps in your case.

**Comment by Clavum** [comment]
> making the assumption that the build methods would be called hierarchically down the widget tree

It won't work that way. Every widget that uses your ValueNotifier will need to extend DataListener explicitly, not just a single one at the top of the tree.

The `build` method itself is not recursive. It simply returns a small list of Widgets, so the method returns as soon as that is done (microseconds). Flutter will then later build each widget until they are all built. That's my understanding, at least.

**Comment by lukehutch** [comment]
Right, well my plan was to use this custom `DataListener`  in the place of all `StatefulWidget` or `StatelessWidget` instances in the tree, so that only the minimal subset of widgets in the tree need to be recomputed.

Interesting that `build` is not recursive. So then there must be a linear queue of widgets whose `build` methods need to be run, since a `build` method can return any tree of (as-yet-unbuilt) widgets. So it sounds like when a widget tree is returned by `build`, some code traverses the tree and finds which widgets need to be scheduled for building?

Maybe I'll try rewriting this. What I'm trying to avoid is the ugly boilerplate of `ValueListenableBuilder`.

**Comment by lukehutch** [comment]
So the best I am able to do is reduce

```
ValueListenableBuilder<int>(
  valueListenable: counterValueNotifier,
  builder: (context, counterValue, child) => Text(
    '${couterValue}',
  ),
),
```

to

```
DataListener(
  builder: (context) => Text(
    '${couterValueNotifier.value}',
  ),
),
```

Which doesn't feel like a significant enough win, in terms of reducing boilerplate, to justify doing things this way.

I'll go ahead and close this. I hope one day Dart/Flutter will support automated reactivity so that all state management can be done by simply using `ValueNotifier`.

**Comment by lukehutch** [comment]
For the record this is what I came up with, and it did all work in the end, I was just hoping for a solution where `(context)` did not have to be passed into a builder lambda, to further reduce boilerplate.

```dart
import 'package:flutter/widgets.dart';

/// A reactive widget. Will be rebuilt when the value of any `ReactiveValue` object
/// read by this `ReactiveWidget` is  changed.
class ReactiveWidget extends StatefulWidget {
  final Widget Function(BuildContext context) _build;
  const ReactiveWidget(
      {super.key, required Widget Function(BuildContext context) build})
      : _build = build;

  @override
  State<ReactiveWidget> createState() => _ReactiveWidgetState();
}

/// Maintains the state of a ReactiveWidget
class _ReactiveWidgetState extends State<ReactiveWidget> {
  // The cached widget, reused if no state changes
  Widget? _cachedWidget;
  // The set of `ReactiveValue` objects for which listeners have been added
  final _listeningTo = <ReactiveValue>{};

  @override
  Widget build(BuildContext context) {
    return _cachedWidget ?? _rebuild(context);
  }

  Widget _rebuild(BuildContext context) {
    // Remove all ReactiveValue listeners when the widget tree is being rebuilt,
    // since the set of referenced ReactiveValue objects may change
    removeAllListeners();
    // Record this ReactiveWidget as being built
    ReactiveValue._currReactiveWidgetState = this;
    try {
      // Call ReactiveWidget.build()
      _cachedWidget = (context.widget as ReactiveWidget)._build(context);
      return _cachedWidget!;
    } finally {
      ReactiveValue._currReactiveWidgetState = null;
    }
  }

  // Remove all ReactiveValue listeners when disposing of this widget
  @override
  void dispose() {
    removeAllListeners();
    super.dispose();
  }

  // Remove all ReactiveValue listeners
  void removeAllListeners() {
    for (var reactiveValue in _listeningTo) {
      reactiveValue.removeListener(_listener);
    }
    _listeningTo.clear();
  }

  // Subscribe to changes in a ReactiveValue
  void _listenTo(ReactiveValue reactiveValue) {
    // Only listen to a given ReactiveValue once per ReactiveWidget
    if (_listeningTo.add(reactiveValue)) {
      // Listen to the ReactiveValue
      reactiveValue.addListener(_listener);
    }
  }

  // Add a listener to call setState when the ReactiveValue value changes
  void _listener() {
    setState(() {
      // Calling setState marks this ReactiveWidget as needing to be rebuilt.
      _cachedWidget = null;
    });
  }
}

/// A reactive value, automatically listened to by any ReactiveWidget that tries to read the value.
class ReactiveValue<T> extends ValueNotifier<T> {
  // The current ReactiveWidget that is being built
  static _ReactiveWidgetState? _currReactiveWidgetState;

  ReactiveValue(super.value);

  @override
  T get value {
    // Ensure that the wrapping ReactiveWidget is listening to value changes
    _currReactiveWidgetState?._listenTo(this);
    return super.value;
  }
}
```

**Comment by lukehutch** [comment]
Also the use of `static` for `ReactiveValue._currReactiveWidgetState` is far from ideal, and may break if the way that the widget tree is rebuilt is changed.

**Comment by lukehutch** [comment]
I put up my code as a library, in case anyone may find it useful.

https://github.com/lukehutch/flutter_reactive_widget/tree/main
