### ISSUE TITLE
Bug: text layout in Flutter web enderer html messing up on Chrome

### ISSUE THREAD

**Issue by alanguodev** [flutter/flutter#120592]
I have a Flutter web app, when I do web renderer html the text layout is fine with Safari in MacOS and totally messed up in Chrome on Mac and it looks like all the white spaces are missing. The canvaskit rendering is fine in Chrome. Attached is a sceenshot with the comparison in two browsers (left side: Chome, right side: Safari). 
![Screenshot 2023-02-13 at 11 53 19 PM](https://user-images.githubusercontent.com/88816986/218440474-b2399ba3-e4de-48b5-99bd-d3e2d7bb987a.png)

**Comment by exaby73** [comment]
Hello @alanguodev. Thank you for filing this issue. Can you please provide the following information?

- A [complete and minimal, reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example). Ideally, a single `main.dart` file that can be run directly.
- The output of `flutter doctor -v`

Please provide the information in the form of text. See how to make collapsible sections with Markdown [here](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-collapsed-sections).

**Comment by alanguodev** [comment]
I think the way your guys are thinking of fixing bugs is wrong. Only very basic bugs can have a minimal repro steps and Google should never ship a product with that types of the bugs. Most more advanced bugs are only happening at very specific conditions. The dev working on the rendering engine should have reasonable guessing what went wrong with my side-by-side screenshots of chrome and safari. It is very clear the bug has nothing to do with the application code, rather it is a very specific bug on the html renderer + chrome in Flutter.

**Comment by alanguodev** [comment]
Flutter doctor -v is perfect with no errors. I think it is very much irrelevant with Flutter doctor, which would never check anything related to rendering.

**Comment by exaby73** [comment]
We need a reproducible example to verify the bug exists, to debug the bug as rendering is a very complex part of Flutter and to test whether a fix actually fixes the issue. The reason why I ask for your doctor output is so that we have a baseline of which Flutter version this is reproducible on so that in the future, someone coming to this thread will have the information they need to reproduce the issue. Doctor output not only includes your Flutter version, but also your Chrome version, OS information. We need such information in order to debug and fix bugs. Just a screenshot is not enough to get started. Please do provide the details so that this issue can be taken further

**Comment by alanguodev** [comment]
I upgraded to Flutter 3.7 and the problem is still here. Please note the bug does not show up if I launch chrome in localhost from the VSCode debugger. The screenshot clearly showing the bug is there. In fact, the html renderer has many bugs (for example, not accurately reflect many color codes, for instance). The best way to dismiss a bug is simply to say "does not repro" but it won't help the quality of the Flutter framework code. The dev who owns the html renderer code should really look at the screenshot I gave, as I bet it would not be caught very often.

**Comment by alanguodev** [comment]
Chrome version: Version 110.0.5481.96 (Official Build) (arm64)

**Comment by exaby73** [comment]
Looking at a screenshot does not help in debugging the issue. We need to know what kind of widget tree exists that causes this issue. It's impossible to know what kind of widget tree you have. If you are not able to provide a sample to reproduce this issue, we cannot take this issue further.
