### ISSUE TITLE
BiometricType FaceID not showing instead of FingerPrint. 

### ISSUE THREAD

**Issue by sokpheng** [flutter/flutter#120581]
Hello I was using Flutter Local_auth and It seems like on some devices like OnePlus 6 and 7, I enrolled both Face and Finger Print, however When using the Authorization does allow me to use Fingerprint only, in the other hand when I tested on my Samsung S22 Ultra the Auth does allow me to use both. 

Is there a way to change from fingerprint to faceID  instead?

**Comment by stuartmorgan** [comment]
Details of specific biometric methods are managed by the OS+device; the plugin can't control the specific method using the available OS APIs.

Closing as this isn't something that can be implemented.

**Comment by stuartmorgan** [comment]
Details of specific biometric methods are managed by the OS+device; the plugin can't control the specific method using the available OS APIs.

Closing as this isn't something that can be implemented.
