### ISSUE TITLE
Flutter iOS app Size is much bigger than Android aab/apk sizes

### ISSUE THREAD

**Issue by abdu292** [flutter/flutter#120549]
I'm new to flutter and just ready to distribute my first flutter app to the test users.

The size of the android release build of the app is only 20.7mb for aab (around 7mb for individual abis) which is good.
I followed this link : https://docs.flutter.dev/deployment/android to build for android.

However the size that comes for iOS is around 83.7 mb for the same app. I was just wondering if this is normal and will be stripped of by the app store without me doing anything else.

Before posting this I of course read this [#47101 comment](https://github.com/flutter/flutter/issues/47101#issuecomment-567522077). However in the comment it says,

> This bitcode is either recompiled or stripped out automatically by the process of creating a distribution IPA. You can see this from Xcode by creating an ad hoc or development archive.

My ipa is actually from Xcode by creating an "AdHoc" archive, but with the size of 83.7 mb.
For iOS I followed this https://docs.flutter.dev/deployment/ios for most of the part.

Any help on this would be really apricated. Thanks a bunch!

**Comment by a-ibrkh** [comment]
It is totally OK that size of iOS app is bigger than the one for Android. Why it is so, you can read here https://www.quora.com/Why-are-Android-apps-smaller-in-size-than-iOS-apps

**Comment by exaby73** [comment]
Based on @a-ibrkh's comment (thank you btw), this looks like it's intended. The final app size may be lower after it's processed by Apple's servers. Kind of how an Android aab file's size does not reflect it's final size. Closing this issue due the same reason

**Comment by abdu292** [comment]
Thank you both @a-ibrkh & @exaby73  . Just wanted to know if this is normal & not a miss from me.
Thanks for the clarification & I appreciated both of your help!
