### ISSUE TITLE
Use `CFBundleName` when `CFBundleDisplayName` is missing when finding app name

### ISSUE THREAD

**Issue by mg** [flutter/flutter#120553]
Reopening #114975 

Hi, I am experiencing this as well.``flutter build ipa --release`` complains about missing display name but the value is correct both in XCode and App Store connect

<img width="1513" alt="image" src="https://user-images.githubusercontent.com/1972/218303076-2eaa1470-065e-4955-ab33-1a7123217fa9.png">

This is a project I created 3 years ago with flutter create. CFBundleName in Runner/Info.plist is correct (18XXc).

``flutter doctor -v``
```
[✓] Flutter (Channel stable, 3.7.3, on macOS 12.6.3 21G419 darwin-x64, locale en-IS)
• Flutter version 3.7.3 on channel stable at /Users/mg/Projects/flutter
• Upstream repository https://github.com/flutter/flutter.git
• Framework revision https://github.com/flutter/flutter/commit/9944297138845a94256f1cf37beb88ff9a8e811a (3 days ago), 2023-02-08 15:46:04 -0800
• Engine revision 248290d6d5
[build.txt](https://github.com/flutter/flutter/files/10715723/build.txt)

• Dart version 2.19.2
• DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
• Android SDK at /Users/mg/Library/Android/sdk/
• Platform android-33, build-tools 33.0.1
• ANDROID_HOME = /Users/mg/Library/Android/sdk/
• Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
• Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
• All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
• Xcode at /Applications/Xcode.app/Contents/Developer
• Build 14B47b
• CocoaPods version 1.11.2

[✓] Chrome - develop for the web
• Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
• Android Studio at /Applications/Android Studio.app/Contents
• Flutter plugin can be installed from:
🔨 https://plugins.jetbrains.com/plugin/9212-flutter
• Dart plugin can be installed from:
🔨 https://plugins.jetbrains.com/plugin/6351-dart
• Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.74.2)
• VS Code at /Applications/Visual Studio Code.app/Contents
• Flutter extension can be installed from:
🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
• iPhone 14 Pro Max (mobile) • AC7D1080-401F-4380-B8CE-07FD7D1623AF • ios • com.apple.CoreSimulator.SimRuntime.iOS-16-1 (simulator)
• macOS (desktop) • macos • darwin-x64 • macOS 12.6.3 21G419 darwin-x64
• Chrome (web) • chrome • web-javascript • Google Chrome 109.0.5414.119

[✓] HTTP Host Availability
• All required HTTP hosts are available

• No issues found! 
```

**Comment by antpowell** [comment]
I'm also seeing this same issue. When building in Xcode everything works and archiving ok but when using cli which is needed for CI/CD pipeline I run into this issue. I also created my project about 3 years ago.

**Comment by stuntbaboon** [comment]
Same issue for me.  I have been updating a project from May 2021 to the latest flutter version.

**Comment by stuntbaboon** [comment]
I actually just managed to resolve it by adding a 'Custom iOS Target Property' named '**Bundle display name**' in Xcode (this property wasn't set in my project).

Runner / Targets (Runner) / Info / Custom iOS Target Properties / Bundle display name

These links helped me find this: 

- https://medium.com/@the_red_ant/how-to-change-the-display-name-of-an-ios-app-7d8fc43a0584
- https://medium.com/@nagella_ranjith/change-ios-app-display-name-in-flutter-c3a9d5465c6f

**Comment by antpowell** [comment]
> I actually just managed to resolve it by adding a 'Custom iOS Target Property' named '**Bundle display name**' in Xcode (this property wasn't set in my project).
> 
> Runner / Targets (Runner) / Info / Custom iOS Target Properties / Bundle display name
> 
> These links helped me find this:
> 
> * https://medium.com/@the_red_ant/how-to-change-the-display-name-of-an-ios-app-7d8fc43a0584
> * https://medium.com/@nagella_ranjith/change-ios-app-display-name-in-flutter-c3a9d5465c6f

Perfect solution, thank you. I'm thinking CFBundleDisplayName was not part of info.plist at first only CFBundleName and something changed, and it might have been missed when upgrading Flutter versions.

**Comment by exaby73** [comment]
I think this issue is a documentation issue for migrating to 3.7

**Comment by clockwork189** [comment]
I had the same issue. When I looked at my Info.plist file, I found that I had "CFBundleName" and I didnt have "CFBundleDisplayName". Adding the following fixed it:
`
<key>CFBundleDisplayName</key>
<string>Application Name</string>// <- change this to your app name
`
Also note, if you are using multiple Info.plist files like myself (Info-Release.plist, Info-Debug.plist) to make sure to make the change in both files.

**Comment by gundrabur** [comment]
> I actually just managed to resolve it by adding a 'Custom iOS Target Property' named '**Bundle display name**' in Xcode (this property wasn't set in my project).
> 
> Runner / Targets (Runner) / Info / Custom iOS Target Properties / Bundle display name
> 
> These links helped me find this:
> 
> * https://medium.com/@the_red_ant/how-to-change-the-display-name-of-an-ios-app-7d8fc43a0584
> * https://medium.com/@nagella_ranjith/change-ios-app-display-name-in-flutter-c3a9d5465c6f

I had the same issue. This solved for me! Thanks!
