### ISSUE TITLE
android  No Java Development Kit (JDK) found;  in flutter channel stable 

### ISSUE THREAD

**Issue by samithe7** [flutter/flutter#120564]
when i use  flutter channel stable   face this problem but when use channel master  everything is ok 

## Logs

<details>
<summary>flutter doctor -v stable  channel</summary>

```
```
[✓] Flutter (Channel stable, 3.7.3, on Microsoft Windows [Version 10.0.22000.1455], locale en-US)
    • Flutter version 3.7.3 on channel stable at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9944297138 (4 days ago), 2023-02-08 15:46:04 -0800
    • Engine revision 248290d6d5
    • Dart version 2.19.2
    • DevTools version 2.20.1

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at C:\Users\samiu\AppData\Local\Android\sdk
    • Platform android-33-ext4, build-tools 33.0.2
    ✗ No Java Development Kit (JDK) found; You must have the environment variable JAVA_HOME set and the java binary in
      your PATH. You can download the JDK from https://www.oracle.com/technetwork/java/javase/downloads/.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✗] Visual Studio - develop for Windows
    ✗ Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[!] Android Studio (version 2022.1)
    • Android Studio at C:\Users\samiu\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\221.6008.13.2211.9514443
    • Flutter plugin version 72.0.2
    • Dart plugin version 221.6096
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] VS Code (version 1.75.1)
    • VS Code at C:\Users\samiu\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.58.0

[✓] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 12 (API 31) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.22000.1455]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 109.0.5414.121
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 110.0.1587.41

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 3 categories.

```
```

</details>

<details>
<summary>flutter doctor -v master channel</summary>

```
```
[✓] Flutter (Channel master, 3.8.0-10.0.pre.31, on Microsoft Windows [Version 10.0.22000.1455], locale en-US)
    • Flutter version 3.8.0-10.0.pre.31 on channel master at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 527977b6af (7 hours ago), 2023-02-12 08:54:35 -0500
    • Engine revision b7e80ad6ef
    • Dart version 3.0.0 (build 3.0.0-231.0.dev)
    • DevTools version 2.21.1

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at C:\Users\samiu\AppData\Local\Android\sdk
    • Platform android-33-ext4, build-tools 33.0.2
    • Java binary at:
      C:\Users\samiu\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\221.6008.13.2211.9514443\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✗] Visual Studio - develop for Windows
    ✗ Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[✓] Android Studio (version 2022.1)
    • Android Studio at C:\Users\samiu\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\221.6008.13.2211.9514443
    • Flutter plugin version 72.0.2
    • Dart plugin version 221.6096
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)

[✓] VS Code (version 1.75.1)
    • VS Code at C:\Users\samiu\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.58.0

[✓] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 12 (API 31) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.22000.1455]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 109.0.5414.121
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 110.0.1587.41

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```
```

</details>

**Comment by exaby73** [comment]
Hey @samithe7. What's the output if running `echo $env:JAVA_HOME` in powershell?

**Comment by samithe7** [comment]
![java](https://user-images.githubusercontent.com/53804061/218476288-859e8820-8a17-4c26-bc95-a24216fa7d03.png)

**Comment by exaby73** [comment]
You haven't set your `JAVA_HOME` variable. Please set it to the path of your JDK. See https://www.thewindowsclub.com/set-java_home-in-windows-10

**Comment by samithe7** [comment]
> You haven't set your `JAVA_HOME` variable. Please set it to the path of your JDK. See https://www.thewindowsclub.com/set-java_home-in-windows-10

if JAVA_HOME  variable  is not set  then why everything is ok in master channel  !!!

**Comment by exaby73** [comment]
Well if this is an issue with stable, it looks like it's fixed in master which means there's nothing to do here. What I am suggesting you is a workaround so that you can continue using the stable channel until this fix makes it to stable :)

**Comment by H-Tech-Dev36** [comment]
Hello man, Same error but no problem with my JAVA_MAIN what should i do plz ?

**Comment by H-Tech-Dev36** [comment]
If you have a solution and i don't read it, feel free to spam my discord : `ADN Security#0193`

**Comment by exaby73** [comment]
@H-Tech-Dev36 `JAVA_HOME` should be pointing to your JDK not JRE

**Comment by Akifcan** [comment]
Hi @exaby73 I followed insturctions on https://www.thewindowsclub.com/set-java_home-in-windows-10 but still get this error:
`flutter doctor --android-licenses
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/android/prefs/AndroidLocationsProvider has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
`

flutter doctor -v result:
```
[√] Flutter (Channel stable, 3.7.3, on Microsoft Windows [Version 10.0.22621.1105], locale en-US)
    • Flutter version 3.7.3 on channel stable at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9944297138 (8 days ago), 2023-02-08 15:46:04 -0800
    • Engine revision 248290d6d5
    • Dart version 2.19.2
    • DevTools version 2.20.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at C:\Users\AcademiaUnited2\AppData\Local\Android\sdk
    • Platform android-33-ext4, build-tools 33.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop for Windows (Visual Studio Build Tools 2019 16.11.18)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
    • Visual Studio Build Tools 2019 version 16.11.32802.440
    X The current Visual Studio installation is incomplete. Please reinstall Visual Studio.

[√] Android Studio (version 2022.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)

[√] VS Code (version 1.75.1)
    • VS Code at C:\Users\AcademiaUnited2\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22621.1105]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 109.0.5414.120
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 110.0.1587.46

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.
```

 echo $env:JAVA_HOME result:
`C:\Program Files\Java\jdk1.8.0_361`

**Comment by Akifcan** [comment]
I solved the issue. This my steps how I solved this issue.

- https://issuetracker.google.com/issues/237019251#comment6
- https://www.thewindowsclub.com/set-java_home-in-windows-10

and last I installed jdk 19: https://stackoverflow.com/questions/75238629/unsupportedclassversionerror-while-flutter-doctor-android-licenses-macos

JDK 19: https://www.oracle.com/java/technologies/downloads/#jdk19-windows
