### ISSUE TITLE
Fonts for Persian alphabets are not applying in web android

### ISSUE THREAD

**Issue by shervinbdndev** [flutter/flutter#120560]
I used GoogleFonts package for applying ABeeZee font in my project, it works well on desktop web but in mobile web the fonts are not applying
I also tried to download the font and use it from assets but still I get the same problem

here the font loaded
![Screenshot (100).png](https://user-images.githubusercontent.com/68682979/218318738-a13dbf2a-a788-4af1-9bae-68bdebafcff3.png)

but in android web fonts are not applying
![Screenshot_20230212-182200_Chrome.jpg](https://user-images.githubusercontent.com/68682979/218318533-74c40b9f-835f-4e7a-8331-76fc9cd06643.jpg)

**Comment by iapicca** [comment]
@shervinbdndev 
a code sample would be useful to reproduce the issue

**Comment by shervinbdndev** [comment]
> @shervinbdndev a code sample would be useful to reproduce the issue

This is my Text Widget that I used ABeeZee font in it:

`class ShervinBdnDevSimpleText extends StatelessWidget {
  final String text;
  final Color color;
  final double size;
  final FontWeight weight;

  const ShervinBdnDevSimpleText({
    super.key,
    required this.text,
    required this.color,
    required this.size,
    required this.weight,
  });

  @override
  Widget build(BuildContext context) {
    return Text(
      text,
      style: TextStyle(
        fontFamily: 'ABeeZee',
        color: color,
        fontSize: size,
        fontWeight: weight,
      ),
    );
  }
}`

and this is my `pubspec.yaml` section to set font in assets:

`
fonts:
    - family: ABeeZee
      fonts:
        - asset: assets/fonts/ABeeZee-Regular.ttf
        - asset: assets/fonts/ABeeZee-Italic.ttf
`

**Comment by shervinbdndev** [comment]
> @shervinbdndev a code sample would be useful to reproduce the issue

This is my Text Widget that I used ABeeZee font in it:

`class ShervinBdnDevSimpleText extends StatelessWidget {
  final String text;
  final Color color;
  final double size;
  final FontWeight weight;

  const ShervinBdnDevSimpleText({
    super.key,
    required this.text,
    required this.color,
    required this.size,
    required this.weight,
  });

  @override
  Widget build(BuildContext context) {
    return Text(
      text,
      style: TextStyle(
        fontFamily: 'ABeeZee',
        color: color,
        fontSize: size,
        fontWeight: weight,
      ),
    );
  }
}`

and this is my `pubspec.yaml` section to set font in assets:

`
fonts:
    - family: ABeeZee
      fonts:
        - asset: assets/fonts/ABeeZee-Regular.ttf
        - asset: assets/fonts/ABeeZee-Italic.ttf
`

**Comment by shervinbdndev** [comment]
if anyone knows how to solve this problem I would be really thankful

**Comment by huycozy** [comment]
Hi @shervinbdndev 
Is the issue that the text below the avatar image is not rendered?

Can you please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this? (It would be appreciated if you could make a GitHub repository since it contains some dependency assets)

Also, please provide the output of `flutter doctor -v` as well. Thank you!

**Comment by shervinbdndev** [comment]
> Hi @shervinbdndev Is the issue that the text below the avatar image is not rendered?
> 
> Can you please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this? (It would be appreciated if you could make a GitHub repository since it contains some dependency assets)
> 
> Also, please provide the output of `flutter doctor -v` as well. Thank you!

All of the texts in my project are successfully rendered **but the font is not applying to my text when I open my project in mobile web** and I don't know why ... All the texts are applying when I open my project in **Desktop Web** but when I open the same project in **Android Web** , The font that I chose, **Is not Applying**!!!!
my text contains **Persian Alphabets**
I think it has some **problem with Persian Alphabets** in **Mobile Web**

here is my project Url: [project](https://github.com/shervinbdndev/shervinbdndev.vercel.app)

And this is The output of `flutter doctor -v`

```
[✓] Flutter (Channel master, 3.8.0-7.0.pre.6, on Microsoft Windows [Version 10.0.22000.1516], locale en-US)
    • Flutter version 3.8.0-7.0.pre.6 on channel master at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a6ea64457a (6 days ago), 2023-02-07 14:45:50 +0100
    • Engine revision 5aadda2f40
    • Dart version 3.0.0 (build 3.0.0-204.0.dev)
    • DevTools version 2.21.1

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at C:\Users\Shervin\AppData\Local\Android\sdk
    • Platform android-33, build-tools 32.0.0
    • Java binary at: C:\Program Files\Java\jdk-18.0.2.1\bin\java
    • Java version Java(TM) SE Runtime Environment (build 18.0.2.1+1-1)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2022 17.1.6)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.1.32421.90
    • Windows 10 SDK version 10.0.19041.0

[!] Android Studio (version 2022.1)
    • Android Studio at E:\AndroidStudio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] VS Code (version 1.75.1)
    • VS Code at C:\Users\Shervin\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.58.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22000.1516]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 109.0.5414.120
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 109.0.1518.78

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

**Comment by huycozy** [comment]
Hi @shervinbdndev 
We would not recommend sharing a production code. 

For the issue to be workable, it needs to be reproducible with a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code. Please provide such a sample.

Also, since I'm not sure I can see the difference between your screenshots (except the text below the avatar image is not rendered), please provide `Actual results` and `Expected results` in text format if it's possible. Thank you!
