### ISSUE TITLE
[plugins][camera] lockedCaptureOrientation work on Android but not on IOS....

### ISSUE THREAD

**Issue by AntoineChauviere** [flutter/flutter#120534]
I want to lock my camera in portrait mode even if I turn my phone in landscape mode. 
So that is my main : 

```
Future<void> main() async {

  WidgetsFlutterBinding.ensureInitialized();
  final cameras = await availableCameras();
  final firstCamera = cameras.first;

  await SystemChrome.setPreferredOrientations([DeviceOrientation.portraitUp])
      .then((_) {
    runApp(
      MaterialApp(
        theme: ThemeData.dark(),
        home: MyHome(
          camera: firstCamera,
        ),
      ),
    );
  });
}
```

I have this initstate of MyHome : 

```
@override
  void initState() {
    super.initState();
    _initializeControllerFuture = _controller.initialize();
    _lockController =
        _controller.lockCaptureOrientation(DeviceOrientation.portraitUp);
  }

```
But when I turn my phone in landscape mode, it works on android but not in iOS, camera view turn in IOS...

Please help...

**Comment by darshankawar** [comment]
@AntoineChauviere 
This looks like similar to https://github.com/flutter/flutter/issues/111063, so please follow-up in that issue for further updates.
Closing this as a duplicate. Also see this similar issue for your further reference: https://github.com/flutter/flutter/issues/89216
