### ISSUE TITLE
Typo in "Your first Flutter app" step 6

### ISSUE THREAD

**Issue by itchipede** [flutter/flutter#120571]
Issue for this codelab: https://codelabs.developers.google.com/codelabs/flutter-codelab-first#5

Very small typo that might, however, take your code out of sync with the example:

```
Next, add the Like button and connect it to toggleFavorites(). For a challenge, first try to do this by yourself, without looking at the code block below.
```

The function name reference here should be `toggleFavorite()`, not Favorites.

**Comment by domesticmouse** [comment]
PTAL @filiph

**Comment by filiph** [comment]
Great catch, thank you @itchipede! Fixed (will take some time to propagate).
