### ISSUE TITLE
check the new devices connected to linux-28..36

### ISSUE THREAD

**Issue by yusuf-goog** [flutter/flutter#120500]
new testsbeds are not showing the mobile devices. Please check if auth dialog needs to be accepted on the phones.

**Comment by kentnguyen99** [comment]
I ran "adb devices" display device command and all machines showed external device phone attached to machine.

linux-28
flutter@flutter-devicelab-linux-28.mtv.corp.google.com's password: 
List of devices attached
R9HR50FGMSN	device


linux-29
flutter@flutter-devicelab-linux-29.mtv.corp.google.com's password: 
List of devices attached
R9HR500XVAM	device


linux-30
flutter@flutter-devicelab-linux-30.mtv.corp.google.com's password: 
List of devices attached
R9HR50FFCYJ	device


linux-31
flutter@flutter-devicelab-linux-31.mtv.corp.google.com's password: 
List of devices attached
R9HR500Y9HK	device


linux-32
flutter@flutter-devicelab-linux-32.mtv.corp.google.com's password: 
List of devices attached
R9HR50FGSPB	device


linux-33
flutter@flutter-devicelab-linux-33.mtv.corp.google.com's password: 
List of devices attached
R9HR50FLYVP	device


linux-34
flutter@flutter-devicelab-linux-34.mtv.corp.google.com's password: 
List of devices attached
R9HR502EQXR	device


linux-35
flutter@flutter-devicelab-linux-35.mtv.corp.google.com's password: 
List of devices attached
R9HR50FG11J	device


linux-36
flutter@flutter-devicelab-linux-36.mtv.corp.google.com's password: 
List of devices attached
R9HR50FHDNP	device
