### ISSUE TITLE
Provide a way to programmatically catch rendering errors 

### ISSUE THREAD

**Issue by steeeep34** [flutter/flutter#120542]
## Use case

My app allows to create widget trees. Sometimes, if the user inserts a widget in another widget, a rendering error happens:

![Bildschirm­foto 2023-02-12 um 13 57 51](https://user-images.githubusercontent.com/124473260/218312588-03c9b8a5-4d7e-45f6-898e-9d415414d9dd.png)

If I could catch rendering errors that happen after the rendering of the inserted widget, I could inform the user and undo the last insert operation.

## Proposal

Provide a mechanism to insert a user defined callback, which gets called when rendering errors happen.
Ideally, provide a structured description of the widget tree, so the developer could probably provide specific details to the user.

**Comment by goderbauer** [comment]
Have you tried providing a custom onError handler to get access to the error: https://master-api.flutter.dev/flutter/foundation/FlutterError/onError.html

Having said that, after an error occurs, the framework is in an unstable state and we don't guarantee that the app continue to function. We are also unlikely to change this.

**Comment by steeeep34** [comment]
Yes, I tried that. The handler is getting called very seldom. At least, I haven't found any way to expect the exception.

Thanks for pointing out the instability after a render expetion happened. Using that, I need to solve my problem some other way.

In case you have a second: Is the framework unstable, even if I render a correct widget tree the next time? Does the instability persist?

In other words: Do I need to terminate the application?

Or may I fix the widget tree and continue running the app?

**Comment by steeeep34** [comment]
> Have you tried providing a custom onError handler to get access to the error: https://master-api.flutter.dev/flutter/foundation/FlutterError/onError.html
> 
> Having said that, after an error occurs, the framework is in an unstable state and we don't guarantee that the app continue to function. We are also unlikely to change this.

OK, I See the point.

Actually, I wonder how your statement relates to the [ErrorWidget](https://api.flutter.dev/flutter/widgets/ErrorWidget-class.html), which description claims, that it gets thrown, when a build method fails:

> This widget is used when a build method fails, to help with determining where the problem lies. Exceptions are also logged to the console, which you can read using flutter logs. The console will also include additional information such as the stack trace for the exception.

**Would you provide a more detailed explanation.**

**Additionally, I'd be happy, if you could provide the [Error Handling page ](https://docs.flutter.dev/testing/errors)of the docs with further details.** 

There, I failed to read anything about somehow fundamental errors, which make the framework unstable in certain situations.
