### ISSUE TITLE
Multiline TextField causes input methods to abort composition on wrap

### ISSUE THREAD

**Issue by singularity-s0** [flutter/flutter#120557]
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. Type characters until the first line is almost full
3. Switch to Chinese input method, start composing a word until the first line overflows and wraps
4. Type one more character
5. The input method aborts composition.

Note: This is platform specific. It is known to be reproducible on Windows & macOS **Web**, but not on iOS.

**Expected results:** 
Input composition should not be interrupted on line wrap.

**Actual results:** 
Input composition is aborted.

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MainApp());
}

class MainApp extends StatefulWidget {
  const MainApp({super.key});

  @override
  State<MainApp> createState() => MainAppState();
}

class MainAppState extends State<MainApp> {
  bool a = false;

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: Scaffold(
          body: SizedBox(
              width: 100,
              child: TextField(
                maxLines: null,
                keyboardType: TextInputType.multiline,
              ))),
    );
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```
No logs
```

```
Analyzing flutter_demo...                                               
No issues found! (ran in 1.6s)
```

```
[✓] Flutter (Channel stable, 3.7.1, on macOS 13.2 22D49 darwin-x64, locale en-US)
    • Flutter version 3.7.1 on channel stable at /Users/singularity/Projects/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7048ed95a5 (6 days ago), 2023-02-01 09:07:31 -0800
    • Engine revision 800594f1f4
    • Dart version 2.19.1
    • DevTools version 2.20.1

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] VS Code (version 1.75.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.58.0

[!] Proxy Configuration
    • HTTP_PROXY is set
    ! NO_PROXY is not set

[✓] Connected device (3 available)
    • iPhone 14 Pro Max (mobile) • 9AADEBDE-B971-4B5B-9E37-A743968DAD5A • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-2 (simulator)
    • macOS (desktop)            • macos                                • darwin-x64     • macOS 13.2 22D49 darwin-x64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 109.0.5414.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 3 categories.
```

</details>

https://user-images.githubusercontent.com/12184989/218307679-d8e80e70-c961-4c9c-91f6-5ea8b9b9c94c.mov

**Comment by exaby73** [comment]
Hey @singularity-s0. Could you tell me the exact key strokes you're taking? I'm not a Chinese speaker so I'm not sure if I am typing the wrong thing. I cannot seem to reproduce this issue web (MacOS)

**Comment by singularity-s0** [comment]
> Hey @singularity-s0. Could you tell me the exact key strokes you're taking? I'm not a Chinese speaker so I'm not sure if I am typing the wrong thing. I cannot seem to reproduce this issue web (MacOS)

The keystrokes are `hhhh<space>hhhh<space>`

**Comment by exaby73** [comment]
I cannot reproduce the specific issue you mentioned. Using a chrome based browser on MacOS (M1). This may be specific to Intel based Macs. I'll ask a colleague to confirm on this tomorrow.

Interestingly, the output I get is the following:

![image](https://user-images.githubusercontent.com/50555895/218479826-328b974e-00d5-48ba-b7c7-de313faad3c8.png)

Looks like when a new line is added, the first `h` is ignored. I repeated the key strokes you mentioned in your comment above. But even if this is an issue, it's not related to the issue you raised and would be better as a new issue

**Comment by singularity-s0** [comment]
I have found out the cause of this problem. Every time the `TextField` rebuilds, text composition is aborted. And adding a new line (which increases height) triggers a rebuild.

You can verify this behavior by adding a listener to this text field, and cause the textfield to rebuild every time text is entered. You'll see that the input method keeps aborting. I can provide a demo if needed.

**Comment by exaby73** [comment]
Is this reproducible on master, because I cannot reproduce this. See my code sample below:

<details>
<summary>Code Sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MainApp());
}

class MainApp extends StatefulWidget {
  const MainApp({super.key});

  @override
  State<MainApp> createState() => _MainAppState();
}

class _MainAppState extends State<MainApp> {
  final _controller = TextEditingController();

  @override
  void initState() {
    super.initState();
    _controller.addListener(() {
      setState(() {});
    });
  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: Scaffold(
        body: SizedBox(
          width: 100,
          child: TextField(
            maxLines: null,
            keyboardType: TextInputType.multiline,
          ),
        ),
      ),
    );
  }
}
```

</details>

**Comment by singularity-s0** [comment]
Hi, looks like you forget to attach the controller to the textfield. And you also need to somehow change the constraint of the textfield. Try this sample:

You can see that with this textfield, it is impossible to compose any Chinese character, no matter what keystrokes is used.

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MainApp());
}

class MainApp extends StatefulWidget {
  const MainApp({super.key});

  @override
  State<MainApp> createState() => _MainAppState();
}

class _MainAppState extends State<MainApp> {
  final _controller = TextEditingController();

  bool show = false;

  @override
  void initState() {
    super.initState();
    _controller.addListener(() {
      setState(() {
        show = !show;
      });
    });
  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Row(
          children: [
            Expanded(
              child: TextField(
                maxLines: null,
                controller: _controller,
                keyboardType: TextInputType.multiline,
              ),
            ),
            Visibility(
              visible: show,
              child: const IconButton(
                  icon: Icon(Icons.zoom_out_sharp), onPressed: null),
            ),
          ],
        ),
      ),
    );
  }
}
```

**Comment by exaby73** [comment]
With the above example, looks like Chinese characters are not being inputted. That I think deserves a separate issue :) I still can't reproduce your original issue. I think get the weird "one character is missed" behavior I mentioned but again, that's a separate issue too.

I'll label this issue for further insights from the team. I recommend you raise new issues for the ones I mentioned above

**Comment by singularity-s0** [comment]
Thank you. Raising it as a separate issue in https://github.com/flutter/flutter/issues/120763

**Comment by yjbanov** [comment]
Deduplicating this issue into https://github.com/flutter/flutter/issues/126066, which provides a clear repro.
