### ISSUE TITLE
BottomAppBar do not react on color passed to the widget with material3 turned on

### ISSUE THREAD

**Issue by centy** [flutter/flutter#120566]
## Steps to Reproduce
1. Turn on material3 theme

2. Create widget with color passed as parameter or as custom theme
BottomAppBar(
      color: Colors.blue,
...

**Expected results:**
Toolbar has background with picked color

**Actual results:**
Color is taken from Theme.canvasColor

**Comment by exaby73** [comment]
Hello @centy. I cannot reproduce this issue. I am using the `BottomAppBar` example available [here](https://api.flutter.dev/flutter/material/BottomAppBar-class.html#material.BottomAppBar.2). I changed the color to `Colors.red` and the `BottomAppBar` reflects the color properly. Am I missing something?

**Comment by omarsahl** [comment]
@exaby73 The `color` property only has an effect when material 3 is disabled.
Try setting `useMaterial3` to `true` In the example you mentioned, if you do, the `color` property won't have any effect.

**Comment by centy** [comment]
That is very strange, I will try to do a simple example today, based on my
scenario. When I was debugging it I saw that color is not set to Material
element and that material element was using color based on type. In my case
it was color from canvas.

pon., 13 lut 2023 o 11:30 Nabeel Parkar ***@***.***>
napisał(a):

**Comment by omarsahl** [comment]
@centy As a workaround, you can wrap your `BottomAppBar` in a `Theme` widget and set the `canvasColor` to the desired color.

```dart
final theme = context.theme;
Theme(
  data: theme.copyWith(
    canvasColor: Colors.red,
  ),
  child: BottomAppBar(
    color: Colors.red,
  ),
);
```

**Comment by centy** [comment]
That is correct. it ignores color property and customizes theme for that
also

pon., 13 lut 2023 o 11:45 Omar Sahl ***@***.***> napisał(a):
