### ISSUE TITLE
[Accessibility] Snackbar isn't focused when it appears on screen

### ISSUE THREAD

**Issue by suesitran** [flutter/flutter#120568]
## Steps to Reproduce

1. Execute `flutter run` on the code sample
2. turn on Voice Over (on iOS) and Talkback (on Android)
3. Tap on first button to show Snackbar

**Expected results:** 
Accessibility focus will move to Snackbar as soon as the view is visible

**Actual results:** 
Android:
- Snackbar is not a11y focused

iOS:
- Snackbar is not a11y focused.

<details>
<summary>Code sample</summary>

```
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'A11y Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('A11y issue'),
      ),
      body: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: [
          ElevatedButton(
            child: const Text('Tap to show SnackBar'),
            onPressed: () {
              ScaffoldMessenger.of(context).showSnackBar(
                  SnackBar(content: const Text('This is a snack bar message'), action: SnackBarAction(label: 'Dismiss', onPressed: () {
                ScaffoldMessenger.of(context).hideCurrentSnackBar();
              },)));
            },
          ),
          ElevatedButton(onPressed: () {
            final OverlayEntry entry = OverlayEntry(builder: (context) => SafeArea(child: Wrap(
              children: [
                Material(
                  color: Colors.transparent,
                  child: Semantics(
                    focusable: true,
                    focused: true,
                    child: Container(
                      decoration: BoxDecoration(
                          color: Colors.black87,
                          borderRadius: BorderRadius.circular(16.0)
                      ),
                      padding: const EdgeInsets.all(16.0),
                      alignment: Alignment.topCenter,
                      margin: const EdgeInsets.all(16.0),
                      child: Text('This is an overlay toast', style: Theme.of(context).textTheme.headlineSmall?.copyWith(color: Colors.white),),
                    ),
                  ),
                ),
              ],
            )));

            Future.delayed(Duration(seconds: 3), () => entry.remove(),);
            Overlay.of(context)?.insert(entry);
          }, child: const Text('Tap to show overlay toast'))
        ],
      ),
    );
  }
}
```

</details>

<details>
  <summary>Video attached</summary>

### Android:

https://user-images.githubusercontent.com/17781268/218348677-e65469c0-b2a9-4fa4-9ee1-dd1f8cece3e9.MOV

</details>

**Comment by danagbemava-nc** [comment]
Hi @suesitran, thanks for the report. 

To make the issues easier to track, kindly file a new issue for the issue with overlays so that we can use this to track the issue with SnackBars. 

We usually prefer separate issues to be filed for separate bugs. 

Please also provide the output of flutter doctor -v. 

Thank you

**Comment by suesitran** [comment]
hi @danagbemava-nc ,

I created new issue for overlay a11y issue: https://github.com/flutter/flutter/issues/120638

**Comment by danagbemava-nc** [comment]
Hi @suesitran, do you have any reference that states that this should be the expected behavior? I tested with the Pixel Clock app and when the `Snackbar` appears on screen, the content is read but it is not focused(similar to what flutters behavior currently is). 
See the recording below


<details>
<summary>recording</summary>

https://user-images.githubusercontent.com/88313112/218659719-b9c87256-8788-4de7-b939-ca3ea7f8c443.mp4
</details>

**Comment by suesitran** [comment]
On Android, the content is read out but the snack bar is not focused. When the snack bar has action button, user needs to swipe through all components to finally reach the end of the screen where snack bar is. This is quite inconvenient for vision impaired user imho.

For iOS, the content is not read out at all, so it's totally invisible to vision impaired user

**Comment by exaby73** [comment]
Checking in the Gmail app, the snackbar that is shown after a swipe action like deleting or archiving a mail, the focus does not shift to the snack bar even though there is an undo action within it
