### ISSUE TITLE
Finished with error: ProcessException: The requested operation requires elevation

### ISSUE THREAD

**Issue by kuangyliang** [flutter/flutter#120584]
windows 10 电脑运行失败：
日志：
 Command: "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --user-data-dir=C:\Users\YL70D9~1.ZHO\AppData\Local\Temp\flutter_tools.a946fd02\flutter_tools_chrome_device.67ba3a4c --remote-debugging-port=52561 --disable-background-timer-throttling --disable-extensions --disable-popup-blocking --bwsi --no-first-run --no-default-browser-check --disable-default-apps --disable-translate http://localhost:52509

备注：
android手机可以运行，web浏览器运行后报错。

以下是我的doctor:

[√] Flutter (Channel stable, 3.7.3, on Microsoft Windows [版本 10.0.19042.1110], locale zh-CN)
    • Flutter version 3.7.3 on channel stable at E:\flutter                                   
    • Upstream repository https://github.com/flutter/flutter.git                              
    • Framework revision 9944297138 (4 days ago), 2023-02-08 15:46:04 -0800                   
    • Engine revision 248290d6d5                                                              
    • Dart version 2.19.2                                                                     
    • DevTools version 2.20.1                                                                 
                                                                                              
[X] Windows Version (Unable to confirm if installed Windows version is 10 or greater)         

[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at E:\Sdk
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2020.3)
    • Android Studio at E:\android_studio_new4
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] Android Studio (version 2021.1)
    • Android Studio at E:\android_studio_new2
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] Android Studio (version 2021.3)
    • Android Studio at E:\android_studio_new5
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[!] Android Studio (version 2022.2)
    • Android Studio at E:\android_studio_new6\android-studio-2022.2.1.9-windows\android-studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    X Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[√] Connected device (4 available)
    • CDY AN90 (mobile) • QKX4C20422025093 • android-arm64  • Android 10 (API 29)
    • Windows (desktop) • windows          • windows-x64    • Microsoft Windows [版本 10.0.19042.1110]
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 110.0.5481.78
    • Edge (web)        • edge             • web-javascript • Microsoft Edge 110.0.1587.41

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 4 categories.

**Comment by exaby73** [comment]
Hey @kuangyliang. Can you post the entire crash logs in a code block?

Please provide the information in the form of text. See how to make collapsible sections with Markdown [here](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-collapsed-sections).

**Comment by kuangyliang** [comment]
>flutter doctor -v
[√] Flutter (Channel stable, 3.7.3, on Microsoft Windows [版本 10.0.19042.1110], locale zh-CN)
    • Flutter version 3.7.3 on channel stable at E:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9944297138 (6 days ago), 2023-02-08 15:46:04 -0800
    • Engine revision 248290d6d5
    • Dart version 2.19.2
    • DevTools version 2.20.1

[X] Windows Version (Unable to confirm if installed Windows version is 10 or greater)

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at E:\Sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_SDK_ROOT = E:\.android
    • Java binary at: E:\android_studio_new6\android-studio-2022.2.1.9-windows\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.4.1+0-b2043.56-9127311)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2020.3)
    • Android Studio at E:\android_studio_new4
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] Android Studio (version 2021.1)
    • Android Studio at E:\android_studio_new2
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] Android Studio (version 2021.3)
    • Android Studio at E:\android_studio_new5
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[√] Android Studio (version 2022.2)
    • Android Studio at E:\android_studio_new6\android-studio-2022.2.1.9-windows\android-studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.4.1+0-b2043.56-9127311)

[√] Connected device (4 available)
    • CDY AN90 (mobile) • QKX4C20422025093 • android-arm64  • Android 10 (API 29)
    • Windows (desktop) • windows          • windows-x64    • Microsoft Windows [版本 10.0.19042.1110]
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 110.0.5481.97
    • Edge (web)        • edge             • web-javascript • Microsoft Edge 110.0.1587.41

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.

**Comment by exaby73** [comment]
Hey. Could you include the entire logs of `flutter run -v`?

**Comment by kuangyliang** [comment]
> Hey. Could you include the entire logs of running `flutter run -d chrome -v`?

<details><summary>Log</summary>
<p>
 flutter run -d chrome -v
[ +318 ms] executing: [E:\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +157 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 9944297138845a94256f1cf37beb88ff9a8e811a
[        ] executing: [E:\flutter/] git tag --points-at 9944297138845a94256f1cf37beb88ff9a8e811a
[ +164 ms] Exit code 0 from: git tag --points-at 9944297138845a94256f1cf37beb88ff9a8e811a
[        ] 3.7.3
[  +11 ms] executing: [E:\flutter/] git rev-parse --abbrev-ref --symbolic @{upstream}
[ +154 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{upstream}
[        ] origin/stable
[        ] executing: [E:\flutter/] git ls-remote --get-url origin
[ +150 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +159 ms] executing: [E:\flutter/] git rev-parse --abbrev-ref HEAD
[ +152 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +99 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[ +155 ms] Launching lib\main.dart on Chrome in debug mode...
[ +102 ms] Initializing file store
[   +8 ms] Skipping target: gen_localizations
[   +5 ms] Skipping target: gen_dart_plugin_registrant
[   +1 ms] Skipping target: _composite
[   +1 ms] complete
[   +1 ms] Updating assets
[  +73 ms] Waiting for connection from debug service on Chrome...
[  +62 ms] <- reset
[   +4 ms] E:\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev E:\flutter\bin\cache\dart-sdk\bin\snapshots\frontend_server.dart.snapshot --sdk-root E:\flutter\bin\cache\flutter_web_sdk/ --incremental --target=dartdevc
--experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true --output-dill C:\Users\YL70D9~1.ZHO\AppData\Local\Temp\flutter_tools.27b0016c\flutter_tool.f0fcd63a\app.dill --packages E:\flutter_workspace\test3\.dart_tool\package_config.json    
-Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-root C:\Users\YL70D9~1.ZHO\AppData\Local\Temp\flutter_tools.27b0016c\flutter_tools.93fec1f1 --filesystem-scheme org-dartlang-app
--initialize-from-dill build\b1b715402d823b7fd5c2b68d2edcb2ce.cache.dill.track.dill --platform file:///E:/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk_sound.dill --verbosity=error --sound-null-safety
[  +21 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[+17241 ms] Waiting for connection from debug service on Chrome... (completed in 17.3s)
[   +1 ms] Synced 32.8MB.       
[   +1 ms] <- accept            
[        ] Caching compiled dill
[ +106 ms] "flutter run" took 18,233ms.

[   +5 ms] Sending crash report to Google.
[+1305 ms] Crash report sent (report ID: 3a8b9ac0afca7b00)
[   +1 ms] Oops; flutter has exited unexpectedly: "ProcessException: 请求的操作需要提升。                                                                                                                                             
                                                                                                                                                                                                                                      
             Command: "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --user-data-dir=C:\Users\YL70D9~1.ZHO\AppData\Local\Temp\flutter_tools.27b0016c\flutter_tools_chrome_device.f7b88c23 --remote-debugging-port=52198
             --disable-background-timer-throttling --disable-extensions --disable-popup-blocking --bwsi --no-first-run --no-default-browser-check --disable-default-apps --disable-translate http://localhost:52152".                 
[  +16 ms] executing: E:\android_studio_new5\jre\bin\java -version
[ +206 ms] Exit code 0 from: E:\android_studio_new5\jre\bin\java -version
[        ] openjdk version "11.0.13" 2021-10-19
           OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
           OpenJDK 64-Bit Server VM (build 11.0.13+0-b1751.21-8125866, mixed mode)
[ +334 ms] executing: [E:\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%ar
[ +151 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%ar
[        ] 6 days ago
[ +164 ms] java -version
[   +6 ms] executing: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe -format json -products * -utf8 -latest -version 16 -requires Microsoft.VisualStudio.Workload.NativeDesktop Microsoft.VisualStudio.Component.VC.Tools.x86.x64
Microsoft.VisualStudio.Component.VC.CMake.Project
[ +108 ms] Exit code 0 from: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe -format json -products * -utf8 -latest -version 16 -requires Microsoft.VisualStudio.Workload.NativeDesktop
Microsoft.VisualStudio.Component.VC.Tools.x86.x64 Microsoft.VisualStudio.Component.VC.CMake.Project
[   +1 ms] []
[        ] executing: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe -format json -products * -utf8 -latest -version 16 -requires Microsoft.VisualStudio.Workload.VCTools Microsoft.VisualStudio.Component.VC.Tools.x86.x64      
Microsoft.VisualStudio.Component.VC.CMake.Project
[ +110 ms] Exit code 0 from: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe -format json -products * -utf8 -latest -version 16 -requires Microsoft.VisualStudio.Workload.VCTools
Microsoft.VisualStudio.Component.VC.Tools.x86.x64 Microsoft.VisualStudio.Component.VC.CMake.Project
[   +1 ms] []
[        ] executing: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe -format json -products * -utf8 -latest -version 16 -prerelease -requires Microsoft.VisualStudio.Workload.NativeDesktop
Microsoft.VisualStudio.Component.VC.Tools.x86.x64 Microsoft.VisualStudio.Component.VC.CMake.Project
[ +108 ms] Exit code 0 from: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe -format json -products * -utf8 -latest -version 16 -prerelease -requires Microsoft.VisualStudio.Workload.NativeDesktop
Microsoft.VisualStudio.Component.VC.Tools.x86.x64 Microsoft.VisualStudio.Component.VC.CMake.Project
[        ] []
[        ] executing: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe -format json -products * -utf8 -latest -version 16 -prerelease -requires Microsoft.VisualStudio.Workload.VCTools
Microsoft.VisualStudio.Component.VC.Tools.x86.x64 Microsoft.VisualStudio.Component.VC.CMake.Project
[ +107 ms] Exit code 0 from: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe -format json -products * -utf8 -latest -version 16 -prerelease -requires Microsoft.VisualStudio.Workload.VCTools
Microsoft.VisualStudio.Component.VC.Tools.x86.x64 Microsoft.VisualStudio.Component.VC.CMake.Project
[   +1 ms] []
[        ] executing: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe -format json -products * -utf8 -latest -prerelease -all
[  +86 ms] Exit code 0 from: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe -format json -products * -utf8 -latest -prerelease -all
[        ] []
[   +5 ms] executing: E:\Sdk\platform-tools\adb.exe devices -l
[ +155 ms] List of devices attached
                    QKX4C20422025093       device product:CDY-AN90 model:CDY_AN90 device:HWCDY-H transport_id:3
[   +5 ms] E:\Sdk\platform-tools\adb.exe -s QKX4C20422025093 shell getprop
[ +158 ms] ro.hardware = kirin820
[        ] ro.build.characteristics = default
[   +3 ms] executing: E:\Sdk\platform-tools\adb.exe devices -l
[  +69 ms] List of devices attached
           QKX4C20422025093       device product:CDY-AN90 model:CDY_AN90 device:HWCDY-H transport_id:3
[+2461 ms] A crash report has been written to E:\flutter_workspace\test3\flutter_01.log.
[        ] This crash may already be reported. Check GitHub for similar crashes.
[        ]
https://github.com/flutter/flutter/issues?q=is%3Aissue+ProcessException%3A+%E8%AF%B7%E6%B1%82%E7%9A%84%E6%93%8D%E4%BD%9C%E9%9C%80%E8%A6%81%E6%8F%90%E5%8D%87%E3%80%82%0D%0A%0A++Command%3A+%22C%3A%5CProgram+Files+%28x86%29%5CGoogle%5CChrome%5CApplic
ation%5Cchrome.exe%22+--user-data-dir%3DC%3A%5CUsers%5CYL70D9~1.ZHO%5CAppData%5CLocal%5CTemp%5Cflutter_tools.27b0016c%5Cflutter_tools_chrome_device.f7b88c23+--remote-debugging-port%3D52198+--disable-background-timer-throttling+--disable-extensions
+--disable-popup-blocking+--bwsi+--no-first-run+--no-default-browser-check+--disable-default-apps+--disable-translate+http%3A%2F%2Flocalhost%3A52152

[   +1 ms] To report your crash to the Flutter team, first read the guide to filing a bug.
[        ] https://flutter.dev/docs/resources/bug-reports

[        ] Create a new GitHub issue by pasting this link into your browser and completing the issue template. Thank you!
[  +20 ms]
https://github.com/flutter/flutter/issues/new?title=%5Btool_crash%5D+ProcessException%3A+%E8%AF%B7%E6%B1%82%E7%9A%84%E6%93%8D%E4%BD%9C%E9%9C%80%E8%A6%81%E6%8F%90%E5%8D%87%E3%80%82%0D%0A+Command%3A+%22C%3A%5CProgram+Files+%28x86%29%5CGoogle%5CChrom
e%5CApplication%5Cchrome.exe%22%2C+OS+error+code%3A+740&body=%23%23+Command%0A%60%60%60%0Aflutter+run+-d+chrome+-v%0A%60%60%60%0A%0A%23%23+Steps+to+Reproduce%0A1.+...%0A2.+...%0A3.+...%0A%0A%23%23+Logs%0AProcessException%3A+%E8%AF%B7%E6%B1%82%E7%9
A%84%E6%93%8D%E4%BD%9C%E9%9C%80%E8%A6%81%E6%8F%90%E5%8D%87%E3%80%82%0D%0A+Command%3A+%22C%3A%5CProgram+Files+%28x86%29%5CGoogle%5CChrome%5CApplication%5Cchrome.exe%22%2C+OS+error+code%3A+740%0A%60%60%60%0A%230++++++_ProcessImpl._start+%28dart%3Aio
-patch%2Fprocess_patch.dart%3A401%3A33%29%0A%231++++++Process.start+%28dart%3Aio-patch%2Fprocess_patch.dart%3A38%3A20%29%0A%232++++++LocalProcessManager.start+%28package%3Aprocess%2Fsrc%2Finterface%2Flocal_process_manager.dart%3A42%3A22%29%0A%233+
+++++ErrorHandlingProcessManager.start.%3Canonymous+closure%3E+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Ferror_handling_io.dart%3A696%3A24%29%0A%234++++++_run+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Ferror_handling_io.dart%3A568%3A20%29%0A%235+++
+++ErrorHandlingProcessManager.start+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Ferror_handling_io.dart%3A695%3A12%29%0A%236++++++ChromiumLauncher._spawnChromiumProcess+%28package%3Aflutter_tools%2Fsrc%2Fweb%2Fchrome.dart%3A260%3A53%29%0A%237++++++C
hromiumLauncher.launch+%28package%3Aflutter_tools%2Fsrc%2Fweb%2Fchrome.dart%3A225%3A36%29%0A%3Casynchronous+suspension%3E%0A%238++++++ChromiumDevice.startApp+%28package%3Aflutter_tools%2Fsrc%2Fweb%2Fweb_device.dart%3A145%3A17%29%0A%3Casynchronous+
suspension%3E%0A%239++++++ResidentWebRunner.run.%3Canonymous+closure%3E+%28package%3Aflutter_tools%2Fsrc%2Fisolated%2Fresident_web_runner.dart%3A303%3A9%29%0A%3Casynchronous+suspension%3E%0A%2310+++++asyncGuard.%3Canonymous+closure%3E+%28package%3
Aflutter_tools%2Fsrc%2Fbase%2Fasync_guard.dart%3A111%3A24%29%0A%3Casynchronous+suspension%3E%0A%60%60%60%0A%60%60%60%0A%1B%5B32m%5B%E2%9C%93%5D%1B%5B39m+Flutter+%28Channel+stable%2C+3.7.3%2C+on+Microsoft+Windows+%5B%E7%89%88%E6%9C%AC+10.0.19042.11
10%5D%2C+locale+zh-CN%29%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Flutter+version+3.7.3+on+channel+stable+at+E%3A%5Cflutter%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Upstream+repository+https%3A%2F%2Fgithub.com%2Fflutter%2Fflutter.git%0A++++%1B%5B32m%E2%80%A2%1B
%5B39m+Framework+revision+9944297138+%286+days+ago%29%2C+2023-02-08+15%3A46%3A04+-0800%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Engine+revision+248290d6d5%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Dart+version+2.19.2%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+DevTools+ve
rsion+2.20.1%0A%0A%1B%5B31m%5B%E2%9C%97%5D%1B%5B39m+Windows+Version+%28Unable+to+confirm+if+installed+Windows+version+is+10+or+greater%29%0A%0A%1B%5B32m%5B%E2%9C%93%5D%1B%5B39m+Android+toolchain+-+develop+for+Android+devices+%28Android+SDK+version
+31.0.0%29%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Android+SDK+at+E%3A%5CSdk%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Platform+android-33%2C+build-tools+31.0.0%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+ANDROID_SDK_ROOT+%3D+E%3A%5C.android%0A++++%1B%5B32m%E2%80%A2%1B%5
B39m+Java+binary+at%3A+E%3A%5Candroid_studio_new5%5Cjre%5Cbin%5Cjava%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Java+version+OpenJDK+Runtime+Environment+%28build+11.0.13%2B0-b1751.21-8125866%29%0D%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+All+Android+licenses+acce
pted.%0A%0A%1B%5B32m%5B%E2%9C%93%5D%1B%5B39m+Chrome+-+develop+for+the+web%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Chrome+at+C%3A%5CProgram+Files+%28x86%29%5CGoogle%5CChrome%5CApplication%5Cchrome.exe%0A%0A%1B%5B31m%5B%E2%9C%97%5D%1B%5B39m+Visual+Studio+
-+develop+for+Windows%0A++++%1B%5B31m%E2%9C%97%1B%5B39m+Visual+Studio+not+installed%3B+this+is+necessary+for+Windows+development.%0A++++++Download+at+https%3A%2F%2Fvisualstudio.microsoft.com%2Fdownloads%2F.%0A++++++Please+install+the+%22Desktop+de
velopment+with+C%2B%2B%22+workload%2C+including+all+of+its+default+components%0A%0A%1B%5B32m%5B%E2%9C%93%5D%1B%5B39m+Android+Studio+%28version+2021.3%29%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Android+Studio+at+E%3A%5Candroid_studio_new5%0A++++%1B%5B32m
%E2%80%A2%1B%5B39m+Flutter+plugin+can+be+installed+from%3A%0A++++++%F0%9F%94%A8+https%3A%2F%2Fplugins.jetbrains.com%2Fplugin%2F9212-flutter%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Dart+plugin+can+be+installed+from%3A%0A++++++%F0%9F%94%A8+https%3A%2F%2Fp
lugins.jetbrains.com%2Fplugin%2F6351-dart%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Java+version+OpenJDK+Runtime+Environment+%28build+11.0.13%2B0-b1751.21-8125866%29%0D%0A%0A%1B%5B33m%5B%21%5D%1B%5B39m+Android+Studio+%28version+2022.1%29%0A++++%1B%5B32m%E
2%80%A2%1B%5B39m+Android+Studio+at+E%3A%5Candroid_studio_new7%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Flutter+plugin+can+be+installed+from%3A%0A++++++%F0%9F%94%A8+https%3A%2F%2Fplugins.jetbrains.com%2Fplugin%2F9212-flutter%0A++++%1B%5B32m%E2%80%A2%1B%5B
39m+Dart+plugin+can+be+installed+from%3A%0A++++++%F0%9F%94%A8+https%3A%2F%2Fplugins.jetbrains.com%2Fplugin%2F6351-dart%0A++++%1B%5B31m%E2%9C%97%1B%5B39m+Unable+to+find+bundled+Java+version.%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Try+updating+or+re-inst
alling+Android+Studio.%0A%0A%1B%5B33m%5B%21%5D%1B%5B39m+Android+Studio+%28version+2022.2%29%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Android+Studio+at+E%3A%5Candroid_studio_new6%5Candroid-studio-2022.2.1.9-windows%5Candroid-studio%0A++++%1B%5B32m%E2%80%A
2%1B%5B39m+Flutter+plugin+can+be+installed+from%3A%0A++++++%F0%9F%94%A8+https%3A%2F%2Fplugins.jetbrains.com%2Fplugin%2F9212-flutter%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Dart+plugin+can+be+installed+from%3A%0A++++++%F0%9F%94%A8+https%3A%2F%2Fplugins.j
etbrains.com%2Fplugin%2F6351-dart%0A++++%1B%5B31m%E2%9C%97%1B%5B39m+Unable+to+find+bundled+Java+version.%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Try+updating+or+re-installing+Android+Studio.%0A%0A%1B%5B32m%5B%E2%9C%93%5D%1B%5B39m+Connected+device+%284+a
vailable%29%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+CDY+AN90+%28mobile%29+%E2%80%A2+QKX4C20422025093+%E2%80%A2+android-arm64++%E2%80%A2+Android+10+%28API+29%29%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Windows+%28desktop%29+%E2%80%A2+windows++++++++++%E2%80%A2+
windows-x64++++%E2%80%A2+Microsoft+Windows+%5B%E7%89%88%E6%9C%AC+10.0.19042.1110%5D%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Chrome+%28web%29++++++%E2%80%A2+chrome+++++++++++%E2%80%A2+web-javascript+%E2%80%A2+Google+Chrome+110.0.5481.100%0A++++%1B%5B32m%
E2%80%A2%1B%5B39m+Edge+%28web%29++++++++%E2%80%A2+edge+++++++++++++%E2%80%A2+web-javascript+%E2%80%A2+Microsoft+Edge+110.0.1587.41%0A%0A%1B%5B32m%5B%E2%9C%93%5D%1B%5B39m+HTTP+Host+Availability%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+All+required+HTTP+ho
sts+are+available%0A%0A%1B%5B33m%21%1B%5B39m+Doctor+found+issues+in+4+categories.%0A%0A%60%60%60%0A%0A%23%23+Flutter+Application+Metadata%0A%2A%2AType%2A%2A%3A+app%0A%2A%2AVersion%2A%2A%3A+1.0.0%2B1%0A%2A%2AMaterial%2A%2A%3A+true%0A%2A%2AAndroid+X
%2A%2A%3A+false%0A%2A%2AModule%2A%2A%3A+false%0A%2A%2APlugin%2A%2A%3A+false%0A%2A%2AAndroid+package%2A%2A%3A+null%0A%2A%2AiOS+bundle+identifier%2A%2A%3A+null%0A%2A%2ACreation+channel%2A%2A%3A+stable%0A%2A%2ACreation+framework+version%2A%2A%3A+9944
297138845a94256f1cf37beb88ff9a8e811a%0A%0A&labels=tool%2Csevere%3A+crash

[ +102 ms] ensureAnalyticsSent: 96ms
[        ] Running 1 shutdown hook
[  +15 ms] Shutdown hooks complete
[        ] exiting with code 1

</p>
</details>

**Comment by exaby73** [comment]
Hello @kuangyliang. I believe this is happening because you have `Flutter` installed in your `E:` drive. Please move the installation to your `C:` drive and try again. This is a know issue with Windows permissions and unfortunately, Flutter cannot do anything about it. Closing this issue for the same reasons. Thank you

**Comment by kuangyliang** [comment]
> Hello @kuangyliang. I believe this is happening because you have `Flutter` installed in your `E:` drive. Please move the installation to your `C:` drive and try again. This is a know issue with Windows permissions and unfortunately, Flutter cannot do anything about it. Closing this issue for the same reasons. Thank you


Thank you very much, I have solved it successfully。

First, I tried to install the flutter sdk on the C drive, but the browser will crash when it starts。

Then, I moved both the browser and the Flutter sdk to the F drive

Third, you need to modify the environment variables where the browser is located，otherwise AS will not find the browser

![image](https://user-images.githubusercontent.com/7835871/219251155-03c92d81-c914-4312-a5a2-c8164041eddf.png)

At this point as can start the browser, but the browser will crash。

Chrome : return “STATUS_INVALID_IMAGE_HASH”

The last step, you need to modify the regedit。
![image](https://user-images.githubusercontent.com/7835871/219251651-667f1b47-6ea7-479e-b8f3-a3634d9d95fe.png)

**Comment by kuangyliang** [comment]
![image](https://user-images.githubusercontent.com/7835871/219251794-55bdb365-0629-43bf-9096-25b1ca7530ac.png)
