### ISSUE TITLE
macos arm64 flutter build warning

### ISSUE THREAD

**Issue by toplinuxsir** [flutter/flutter#120540]
when run flutter  run -d macos
warnning as below 
```
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:macOS, arch:x86_64, id:A1E97B74-42D1-570F-8F53-184050A5E2EE }
{ platform:macOS, arch:arm64, id:A1E97B74-42D1-570F-8F53-184050A5E2EE }
```

How to select arm64 arch ? Thanks !

**Comment by iapicca** [comment]
@toplinuxsir could you provide your `flutter doctor -v`?

**Comment by danagbemava-nc** [comment]
Closing this as a duplicate of https://github.com/flutter/flutter/issues/86590. 

Kindly subscribe to the issue linked above for updates. 

Thank you
