### ISSUE TITLE
project throwing 'Flutter/Flutter.h' file not found when I convert ios objc plugin to macos

### ISSUE THREAD

**Issue by hosseinkhojany** [flutter/flutter#120528]
## Steps to Reproduce

1. I ran flutter create -i swift test
2. Then I deleted the macos folder and duplicated the ios folder and renamed it to macos and changed all the ios configurations to macos such as base sdk and destinations.
3. at the end when I run the project I saw this error

## Flutter Doctor

```

[✓] Flutter (Channel stable, 3.3.6, on macOS 13.1 22C65 darwin-arm, locale
en-US)
• Flutter version 3.3.6 on channel stable at
/Users/khoujani/Documents/flutter3.3.6
• Upstream repository https://github.com/flutter/flutter.git
• Framework revision https://github.com/flutter/flutter/commit/6928314d505d2bb4777be05e45d7808a5aa91d2a (4 months ago), 2022-10-25 16:34:41 -0400
• Engine revision 3ad69d7be3
• Dart version 2.18.2
• DevTools version 2.15.0

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
• Android SDK at /Users/khoujani/Library/Android/sdk
✗ cmdline-tools component is missing
Run path/to/sdkmanager --install "cmdline-tools;latest"
See https://developer.android.com/studio/command-line for more details.
✗ Android license status unknown.
Run flutter doctor --android-licenses to accept the SDK licenses.
See https://flutter.dev/docs/get-started/install/macos#android-setup for
more details.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
• Xcode at /Applications/Xcode.app/Contents/Developer
• Build 14B47b
• CocoaPods version 1.11.3

[✓] Chrome - develop for the web
• Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
• Android Studio at /Applications/Android Studio.app/Contents
• Flutter plugin can be installed from:
🔨 https://plugins.jetbrains.com/plugin/9212-flutter
• Dart plugin can be installed from:
🔨 https://plugins.jetbrains.com/plugin/6351-dart
• Java version OpenJDK Runtime Environment (build
11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.74.3)
• VS Code at /Applications/Visual Studio Code.app/Contents
• Flutter extension can be installed from:
🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
• macOS (desktop) • macos • darwin-arm64 • macOS 13.1 22C65 darwin-arm
• Chrome (web) • chrome • web-javascript • Google Chrome 109.0.5414.119

[✓] HTTP Host Availability
• All required HTTP hosts are available

! Doctor found issues in 1 category.</summary>

```

**Comment by darshankawar** [comment]
> 2\. Then I deleted the macos folder and duplicated the ios folder and renamed it to macos and changed all the ios configurations to macos such as base sdk and destinations.

@hosseinkhojany Curious to know why would you do this ? What exactly are you trying to achieve ? Take a look at [this](https://stackoverflow.com/a/70148000) SO link and see if it helps.

**Comment by hosseinkhojany** [comment]
> > 2. Then I deleted the macos folder and duplicated the ios folder and renamed it to macos and changed all the ios configurations to macos such as base sdk and destinations.
> 
> @hosseinkhojany Curious to know why would you do this ? What exactly are you trying to achieve ? Take a look at [this](https://stackoverflow.com/a/70148000) SO link and see if it helps.

I am developing a VPN for iOS and macOS. The VPN protocol I implemented is OpenConnect, which is written in C language and works very well in iOS with Objective C, and I want to use it in Mac OS. I would also like to have the Objective C code because it gets very busy with Swift and it is not cost effective to maintain

**Comment by darshankawar** [comment]
Thanks for the update @hosseinkhojany 
Please see if below links helps in your implementation or aligns with what you are trying to implement.

https://github.com/flutter/plugins/pull/6920
https://github.com/flutter/flutter/issues/111033
