### ISSUE TITLE
Provide a method, that determines, if an application needs to be released as open-source 

### ISSUE THREAD

**Issue by steeeep34** [flutter/flutter#120635]
## Use case

Flutter provides a widget to [show the licenses of all included pub.dev frameworks.](https://api.flutter.dev/flutter/material/LicensePage-class.html)

While my app includes around 15 frameworks, I guess more than 200 licenses get shown.

Since I'm working on a closed-source solution, checking all those licenses gets quite complicated. 
Furthermore, not each and every developer is a license expert, who immediately knows from a license name its details.

## Proposal

Please provide a method `canBeClosedSource()` as a member of `LicensePage(),` which provide a summary regarding open-/closed-source.

I'm aware of the fact, that due to the number of  licenses, the function might be incomplete at its first implementation.
Thus, it may return a tri-state value:

  TRUE - closed-source distribution allowed
  FALSE - needs to be open-sourced
  UNKNOWN - can't be determined, since some licenses can't be evaluated / are not known

**Comment by stuartmorgan** [comment]
The Flutter project cannot provide legal advice, programmatically or otherwise.

Closing as this is out of scope. The community could certainly build tools to summarize licenses heuristically if there are people interested in doing so.

**Comment by steeeep34** [comment]
OK, I see.
