### ISSUE TITLE
AppBar content has no default left padding after v0.0.15

### ISSUE THREAD

**Issue by gdomingues** [flutter/flutter#12063]
## Steps to Reproduce

- Create new app with wizard on IntelliJ
- Run app with no changes on Android emulator

| 0.0.14  | 0.0.15 |
| ------------- | ------------- |
| <img width="301" alt="before" src="https://user-images.githubusercontent.com/11051024/30359728-0ae1d1b6-9823-11e7-9aeb-95d6880b04cf.png">  | <img width="301" alt="after" src="https://user-images.githubusercontent.com/11051024/30359735-18f917e6-9823-11e7-9d6c-a87242b2eef4.png">  |

## Flutter Doctor

```
[✓] Flutter (on Mac OS X 10.12.6 16G29, locale en-US, channel alpha)
    • Flutter at /Users/germannodomingues/development/workspace/tools/flutter
    • Framework revision 701d534ba9 (8 hours ago), 2017-09-12 14:01:51 -0700
    • Engine revision 31d03de019
    • Tools Dart version 1.25.0-dev.11.0

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.1)
    • Android SDK at /Users/germannodomingues/Library/Android/sdk/
    • Platform android-26, build-tools 26.0.1
    • ANDROID_HOME = /Users/germannodomingues/Library/Android/sdk/
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.3.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3.3, Build version 8E3004b
    • ios-deploy 1.9.2
    • CocoaPods version 1.3.1

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.2.3)
    • Flutter plugin version 17.0
    • Dart plugin version 172.3968.27

[✓] Connected devices
    • Android SDK built for x86 64 • emulator-5554                        • android-x64 • Android 5.1.1 (API 22) (emulator)
    • iPhone SE                    • 3EF9C14A-6D08-4B7A-A1EA-C72AAA2A9419 • ios         • iOS 10.3 (simulator)
```

**Comment by gdomingues** [comment]
Adding padding manually makes the title aligned as before (though probably it's not the solution):

```
    AppBar appBar = new AppBar(
      title: const Padding(
        padding: const EdgeInsets.only(left: 16.0),
        child: const Text("Flutter Demo Home Page"),
      ),
    );
```

**Comment by mehmetf** [comment]
This was a deliberate decision to fix: https://github.com/flutter/flutter/issues/11963 . There are scenarios where app wants to take over the entire app bar. This was previously not possible due to automatic addition of margin even if there was no leading widget in the app bar.

Material Design isn't clear on what to do if there is no menu or back button in the toolbar. Therefore, we decided to leave it to the app to decide (e.g. some apps prefer 32dp padding).

**Comment by Hixie** [comment]
We may have to put the padding back. This affects the default template app in an ugly way.

**Comment by mehmetf** [comment]
Synced up with @yjbanov, I am working on a fix for this.

**Comment by gdomingues** [comment]
Thanks for the explanation @mehmetf .

A solution I could think of is adding a "padding" parameter to AppBar with a default value of 16dp for example, which could be overwritten by those who don't want to use it.

**Comment by mehmetf** [comment]
Thanks for the suggestion. Unfortunately this is not padding in the traditional sense. However, we are indeed going to allow the AppBar to override this value and default it to 16dp. Stay tuned.

**Comment by nisrulz** [comment]
Hi, was this fixed? If yes whats is the way to go now? Adding a padding to `title` property or something else?

**Comment by Hixie** [comment]
This was reverted to the old behaviour of having a margin. I'm not sure if we've rolled the fix to alpha yet, if this is affecting you try switching to the master channel (`flutter channel master`).
