### ISSUE TITLE
I can't debug integration test in flutter web

### ISSUE THREAD

**Issue by Liortra** [flutter/flutter#120688]
Hello everyone,

I'm building an integration test for my flutter web project with BDD. https://pub.dev/packages/bdd_widget_test 

I'm trying to debug the integration test in the android studio but I'm getting: 
'Web devices are not supported for integration tests yet.'

I tried to run with flutter_driver and attempted to put breakpoints in chrome but it does not work, 
and I don't talk about that I can't use selenium with flutter web...

Any suggestion? update about this subject?
Is someone know how to use selenium with flutter web?

**Comment by darshankawar** [comment]
@Liortra 
There's a similar issue open describing your case, https://github.com/flutter/flutter/issues/117955, so please follow-up in it for further updates. You may upvote original issue and share your findings in it for better tracking.
Closing this as a duplicate.

**Comment by Liortra** [comment]
@darshankawar thanks for the update.
