### ISSUE TITLE
`Medium top app bar` spec image has incorrect bottom padding when expanded

### ISSUE THREAD

**Issue by TahaTesser** [flutter/flutter#120672]
See:  [Medium top app bar layout](https://m3.material.io/components/top-app-bar/specs#d8cde49b-7e27-4593-b5f9-9ea433df3486)
 
In this spec image, you can see the bottom padding is 20dp

![image](https://user-images.githubusercontent.com/48603081/218685383-c9428109-664d-450b-8ccf-e227c1b7f3ce.png)

But the table with the values shows 24dp bottom padding.

![Screenshot 2023-02-14 at 10 51 06](https://user-images.githubusercontent.com/48603081/218686373-f276b330-c943-4e03-848a-dccd073495a7.png)

While Large Top Bar has the correct spec image and value in the table

See:  [Large top app bar layout](https://m3.material.io/components/top-app-bar/specs#c1de8ec3-f296-42f2-b3e8-cd0aad701f6c)

![image](https://user-images.githubusercontent.com/48603081/218686763-e4794435-ace3-4eb5-907a-7e4e44c6e910.png)

![Screenshot 2023-02-14 at 10 52 13](https://user-images.githubusercontent.com/48603081/218686653-6c30de68-9479-41ad-a768-7862ec4ee4ce.png)

I can also see the 24dp and 28dp values are provided in Androidx Compose source code
https://github.com/androidx/androidx/blob/05e4dc72e77ad1fc78063a152024a35a0392ff93/compose/material3/material3/src/commonMain/kotlin/androidx/compose/material3/AppBar.kt#L1657-L1658

**Comment by TahaTesser** [comment]
cc: @guidezpl

**Comment by guidezpl** [comment]
Thanks for the detailed issue, I filed a Google bug b/269228264 to investigate.

**Comment by scopendo** [comment]
@TahaTesser – as an aside, do you know if there is an intention to bring `SliverAppBar.large` and `.medium` equivalents to AppBar (presumably non-collapsing)?

**Comment by TahaTesser** [comment]
> @TahaTesser – as an aside, do you know if there is an intention to bring `SliverAppBar.large` and `.medium` equivalents to AppBar (presumably non-collapsing)?

If it doesn't need to be collapsed, you can just customize the regular `AppBar` to achieve the same design.

**Comment by scopendo** [comment]
> If it doesn't need to be collapsed, you can customize the regular `AppBar` to achieve the same design with [AppBar.flexibleSpace](https://master-api.flutter.dev/flutter/material/AppBar/flexibleSpace.html)

Yes, indeed.  Though that's true of many things, including `AppBar` itself.  It seems to me that it makes sense for Flutter to support the M3 design system out of the box without needing to jump through additional hoops, in some cases.

**Comment by scopendo** [comment]
@TahaTesser – it would also be useful if `SliverAppBar.medium` and `.large` would allow us to pass a background decoration to the internal flexible space bar.

**Comment by TahaTesser** [comment]
> @TahaTesser – it would also be useful if `SliverAppBar.medium` and `.large` would allow us to pass a background decoration to the internal flexible space bar.

Can you please file a new issue for this proposal?

**Comment by TahaTesser** [comment]
@guidezpl 
This is affecting fixes for two SliverAppBar issues in my backlog for the title position and text scale. 
Could you please expedite this?

**Comment by TahaTesser** [comment]
cc: @guidezpl  @Piinks @HansMuller 

`24dp` seemed too high, Undeed adding this much padding breaks the layout further.
But as I mentioned above, Compose implementation does use `24dp`.

 I digged deeper to find out what's happening with this value. Looks like [the default padding is substracted by bottom line height of the text style in the Compose source code](https://github.com/androidx/androidx/blob/05e4dc72e77ad1fc78063a152024a35a0392ff93/compose/material3/material3/src/commonMain/kotlin/androidx/compose/material3/AppBar.kt#L1386-L1390)

```kt
                        else layoutHeight - titlePlaceable.height - max(
                            0,
                            titleBottomPadding - titlePlaceable.height + titleBaseline
                        )
```

Letters such as `g`, `p`, `y` are cut off in the current Flutter implemenation. This can be observed in the official [example](https://master-api.flutter.dev/flutter/material/SliverAppBar/SliverAppBar.medium.html#material.SliverAppBar.medium.1) where `pp` lettees are cut off in the expanded `SliverAppBar.medium` state. This is more evident in this issue https://github.com/flutter/flutter/issues/104493.

I'm going ahead with my PR and implementting a similar substaction from the default padding as this will close at least 3 issues in my backlog, improve `SliverAppBar.medium` and `SliverAppBar.large` and also adding `TODO` to find an explanation for this and update code comment later.

```dart
              child: Container(
                alignment: AlignmentDirectional.bottomStart,
                // This adjusts the expanded title bottom padding.
                // The default expanded title bottom padding value is subtracted
                // by the bottom line height.
                // TODO(tahatesser): Figure out why this is done. https://github.com/flutter/flutter/issues/120672
                padding: config.expandedTitlePadding!.subtract(getExpandedTileSpacing()),
                child: expandedTitle,
              ),
```

**Comment by TahaTesser** [comment]
https://m3.material.io/components/top-app-bar/specs is fixed
