### ISSUE TITLE
Firebase Auth - link with credentials

### ISSUE THREAD

**Issue by MarcinusX** [flutter/flutter#12066]
I would like to introduce [linkWithCredentials](https://firebase.google.com/docs/reference/android/com/google/firebase/auth/FirebaseUser#linkWithCredential(com.google.firebase.auth.AuthCredential)) feature to FlutterFire.

Looking from Java perspective (haven't seen iOS version yet), to link anonymous account with credentials we need AuthCredential object. Since we don't have corresponding class in dart, I think the way to go would be to create linkWithCredential method for every provider.

#### firebase_auth.dart:
```
Future<FirebaseUser> linkWithGoogleCredential({
    @required String idToken,
    @required String accessToken,
  }) async {
    assert(idToken != null);
    assert(accessToken != null);
    final Map<String, dynamic> data = await channel.invokeMethod(
      'linkWithGoogleCredential',
      <String, String>{
        'idToken': idToken,
        'accessToken': accessToken,
      },
    );
    final FirebaseUser currentUser = new FirebaseUser._(data);
    return currentUser;
  }
```
#### FirebaseAuthPlugin.java:
```
private void handleLinkWithGoogleCredential(MethodCall call, final Result result) {
    @SuppressWarnings("unchecked")
    Map<String, String> arguments = (Map<String, String>) call.arguments;
    String idToken = arguments.get("idToken");
    String accessToken = arguments.get("accessToken");
    AuthCredential credential = GoogleAuthProvider.getCredential(idToken, accessToken);
    firebaseAuth.getCurrentUser()
            .linkWithCredential(credential)
            .addOnCompleteListener(activity, new SignInCompleteListener(result));
  }
```
Implementation is mostly copy-paste form signInWithGoogle. Not sure about this approach, what do you think?

### Questions
I will gladly try to implement this :)
I have following questions before I start:
1. Is method-per-provider approach something we would like to do?
    1. If so, should I make this for all providers or just the one I need so far? - Adding it for specific providers is mostly copy paste, so it's not a problem
2. I haven't looked for iOS version yet. Is better to try to implement this and then someone would correct me in pull request or leave it and only Android?
3. In java example I have used SignInCompleteListener, technically we don't sign in but in my opinion this works for us. Please comment it :)
4. Do I understand correctly that all errors thrown in java code can be captured only as PlatformException? In other words, we can't exactly tell what java error was thrown, right?

**Comment by MarcinusX** [comment]
@mit-mit would you like to help me a bit? :)

**Comment by mit-mit** [comment]
Hi, @MarcinusX thanks for contributing! @kroikie can you provide some insight on the questions above?

**Comment by MarcinusX** [comment]
I just noticed that there is already linkWithEmailAndPassword method.
So I assume I would just do the same as in [here](https://github.com/flutter/plugins/pull/206), right?

**Comment by mit-mit** [comment]
I don't really know these APIs personally. @kroikie can you advice?

**Comment by kroikie** [comment]
@MarcinusX

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/969. Any further collaboration will be done there.
