### ISSUE TITLE
[CP] Fix message type inconsistency between locales

### ISSUE THREAD

**Issue by AlexV525** [flutter/flutter#120679]
### issue_link

https://github.com/flutter/flutter/issues/119557

### Commit Hash

becb6bd00aab3e1a904eeb7fe9a19b57e8cfda86

### Target

stable

### pr_link

https://github.com/flutter/flutter/pull/120678

### Impacted Users

Using localizations and have unused placeholders in their ARB files

### Impact Description

When ARB files other than the template file have fields that are not using the placeholder syntax as the template do, their generated methods won't have the same signature as the template, which will cause invalid overrides that makes the project unable to run.

### Workaround

No

### Risk

low

### Test Coverage

yes

**Comment by AlexV525** [comment]
Out of this scope, @thkim1011 Can you consider announcing a late announcement about l10n's breaking change to the Flutter group? I would say it's breaking because massive codes and fields are going to be updated after the refactoring of the tool. Although we now support the standard ICU format for localizations, it does break codes that are allowed in unconstrained behavior.

**Comment by christopherfujino** [comment]
This CP LGTM.

**Comment by AlexV525** [comment]
#120848 should be addressed before landing this. @thkim1011 @itsjustkevin
