### ISSUE TITLE
Target of URI doesn't exist: 'dart:ui'. Undefined class 'Canvas'.

### ISSUE THREAD

**Issue by AKA-LinCoder** [flutter/flutter#120654]
when i installed my flutter verison , i have get some problems about Canvas 

like can not find Canvas ,Paint etc 
Undefined class 'Paint'.

```
```
this is my flutter version

[✓] Flutter (Channel stable, 3.7.3, on macOS 13.1 22C65 darwin-arm64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[!] Android Studio (version 2022.1)
    ✗ Unable to find bundled Java version.
[✓] IntelliJ IDEA Ultimate Edition (version 2022.2.1)
[✓] VS Code (version 1.74.2)
[✓] Connected device (5 available)
[✓] HTTP Host Availability

**Comment by exaby73** [comment]
Hello @AKA-LinCoder. Thank you for filing this issue. Can you please provide the following information?

- A [complete and minimal, reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example). Ideally, a single `main.dart` file that can be run directly.
- The output of `flutter run -v`

Please provide the information in the form of text. See how to make collapsible sections with Markdown [here](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-collapsed-sections).

**Comment by AKA-LinCoder** [comment]
nfg

**Comment by exaby73** [comment]
@AKA-LinCoder Please provide the above information in order for me to take the issue further

**Comment by AKA-LinCoder** [comment]
hi ， i have downgraded yesterday and upgrade today ,it look good ,so i think it is my own question，thanks
