### ISSUE TITLE
Timeout on `Mac module_host_with_custom_build_test`

### ISSUE THREAD

**Issue by loic-sharma** [flutter/flutter#120643]
This caused framework tree to close: https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20module_host_with_custom_build_test/11271/overview

**Comment by sealesj** [comment]
Looking at retry attempts which use different bots and seeing very different build times through gradle stages, however no other issues. Example: failed https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20module_host_with_custom_build_test/11271/overview and then succeeded here https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20module_host_with_custom_build_test/11272/overview with only difference being the bot.
I'm wondering if either a caching issue on the bot is leading to the slower build times

**Comment by sealesj** [comment]
Wondering if this is related to the issue mentioned in https://github.com/flutter/flutter/issues/120119

**Comment by sealesj** [comment]
@godofredoc These builds are potentially grabbing dependencies + transitive deps not being found in cache for some reason, which is causing multiple steps to run very slowly. If this is the case, in the meantime would it make sense to bump up the timeout threshold until the android dependency problem has been addressed?

**Comment by godofredoc** [comment]
Maybe related to https://github.com/flutter/flutter/issues/120119

**Comment by keyonghan** [comment]
The old tree blocking issue is resolve. Leaving the root cause to https://github.com/flutter/flutter/issues/120119
