### ISSUE TITLE
Do we really need ***Directional widgets?

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#12065]
For instance:
https://docs.flutter.io/flutter/painting/EdgeInsetsDirectional-class.html
https://docs.flutter.io/flutter/painting/EdgeInsets-class.html

It is not clear why I would ever use EdgeInsets if I want an app that behaves well under RTL. It creates unnecessary API complexity IMO and sets app developers up for odd bugs.

Even if there are cases when I want "Left" whether Directionality is LTR or RTL, I would expect that to be the exception rather than the norm.

Android attempted to solve this problem by supporting left, right, start, end parameters in the same component and warning users of left/right via a lint that they _probably_ want directional params instead. You can confirm/silence that warning by adding a \@ignore qualifier. It isn't the best solution but it worked fine. I am not sure what iOS does.

**Comment by mehmetf** [comment]
How about this for the API:

EdgeInsets() by default is directional. This is the expected behavior for insets. It does not support "left/right" but rather start and end which is a **breaking change**.

Another named ctr EdgeInsets.absolute() is non-directional. It supports left/right and makes EdgeInsets behave like it currently does.

WDYT?

**Comment by robertoscaramuzzi** [comment]
I agree with Mehmet. The API right now is
* confusing
* arguably, misleadingly named
* leads devs to pick the wrong version of EdgeInsets for their client code

**Comment by Hixie** [comment]
Most apps are never translated. For those apps we want the simplest possible API.

Even apps that are translated will have non-directional aspects, for example the Flutter Logo is always left-to-right; media playback UIs are always left-to-right, etc. For those, you need an "absolute" version of the API. For historical reasons, that's EdgeInsets -- changing that to not be absolute would be a breaking change, and we're attempting to not break apps, we've announced API stability. There are some changes we find ourselves forced to make but by and large we want to keep things unchanging.

**Comment by mehmetf** [comment]
I would like to decouple translation and LTR/RTL. You can skip translating the app but you should still obey the locale specific layout (such as menu being on the right). I assume that's what you are following for Material widgets like AppBar, right? After these changes, I assume Leafy's menu (a non-translated app) will appear on the right. So even non-translated apps should use the directional version of the API (thus making that the simplest makes sense).

I agree that there are use cases for non-directional but they are rare and are usually called out explicitly. 

Just to be clear I am not trying to say let's not have the absolute version. My point is:

- Having two EdgeInsets classes is confusing. Why not have one that handles both?
- Let's make the most common use case (directional) the "simple" API.

We can also make this a non-breaking change. I would think that most apps using EdgeInsets today with left-right would like to obey directionality. So we can deprecate the params for default ctr and set start = left and end = right and remove them sometime later.

```dart
class Test {
  final int i;
  final int x;
  final int y;
  
  const Test({
    @deprecated
    this.i,
    this.x,
    this.y,
  }); 
}

void main() {
  var t = new Test(i:5, x:6);
}
```

This causes analyzer to complain "i is deprecated and should not be used".

**Comment by mehmetf** [comment]
Here's an example of an App which is obeying the RTL with English. Note the overflow menu etc being on the left which is where the users expect it to be:

![image](https://user-images.githubusercontent.com/6687929/30386404-958befdc-985e-11e7-8a1d-ca59b6230819.png)

**Comment by Hixie** [comment]
> I would like to decouple translation and LTR/RTL.

They're very closely tied. For example, the directionality decides whether text that contains both English and Hebrew should have the final period of a sentence on the right or left. I don't think it generally makes sense to lay out an English-language app in RTL.

> Having two EdgeInsets classes is confusing. Why not have one that handles both?

It's a design trade-off. The lowest levels of the system know nothing about directionality, so they need an absolute-only version. The higher levels can do both. Our solution is to have a way to "resolve" the version that can do both into a version that is known to be absolute. One relatively clean way to do this yet also allow the two styles to be intermixed (e.g. `EdgeInsets.only(left: 2.0).add(EdgeInsetsDirectional(start: 2.0))`) is to use two separate types. There are other ways, but the design trade-offs are different.

> Let's make the most common use case (directional) the "simple" API.

The most common use case isn't directional. Honestly I suspect a small fractional of all apps ever written with Flutter will ever be written to support both RTL and LTR. Consider the Web, for example. Very few Web pages end up actually localized to both Hebrew and French, or Arabic and English.

> We can also make this a non-breaking change. [...] deprecate the params [...] and remove them sometime later.

That's a breaking change.

**Comment by mehmetf** [comment]
> I don't think it generally makes sense to lay out an English-language app in RTL.

Sure.. but my understanding (from reading the code) is that all Material widgets are supposed to use Directional padding. So my non-translated Material/Cupertino app will render English in RTL in a phone where default language is Hebrew. Is that not accurate?

Ultimately, my worry is that when I mix in high level Material widgets such as AppBar and Tabs with my own layout, it will be a mess if I don't use Directional padding even if my app is not translated. Does that make sense?

**Comment by Hixie** [comment]
If your app is American English and isn't translated (i.e. MaterialApp.supportedLocales is just `Locale('en', 'US')`) then it'll use LTR.

**Comment by mehmetf** [comment]
I see; then I agree what you have is the right approach.

@HansMuller I would give a couple of suggestions though:

- Perhaps enhance the EdgeInsets (and other documentation) to say that if app supports RTL, you probably want Directional variation.
- flutter.io should probably have a section on i18n and mention this as well.

Thanks for explaining!

**Comment by Hixie** [comment]
https://github.com/flutter/flutter/pull/12075

**Comment by robertoscaramuzzi** [comment]
One more comment/suggestion: would it make sense for discoverability to add a factory method to EdgeInsets that returns an EdgeInsetsDirectional instance?

**Comment by Hixie** [comment]
@robertoscaramuzzi that was part of the original plan (see https://github.com/flutter/flutter/issues/11394), but it doesn't work because factory constructors can only return subtypes, and this is a peer type.
