### ISSUE TITLE
[go_router] Error when trying to open a route with more than one slash via browser url

### ISSUE THREAD

**Issue by leeflix** [flutter/flutter#120624]
When trying to open a route with more than one slash e.g. "/users/new" by entering in the browser and pressing enter  I get an exception not in android studio but the browser console:

![image](https://user-images.githubusercontent.com/41200990/218568422-6d2e732a-feea-48e5-8353-b71e2effb47c.png)

It doesn't matter if I define the route or not. I am using shell router. If I use ```GoRouter.of(context).go("/users/new")``` it works.

**Comment by darshankawar** [comment]
@leeflix 
Can you try your scenario on latest master ? I think [this](https://github.com/flutter/flutter/pull/118684) fix may have already resolved your issue too, but just check once.

`flutter channel master`
`flutter upgrade`

**Comment by rmahmadkhan** [comment]
hi @leeflix 
I was also having a similar problem. 
[[go_router] Path with parameters shows blank screen when refreshed or entered from url bar (web)](https://github.com/flutter/flutter/issues/120430#top) #120430

Please also check that issue and it might help you :)

**Comment by leeflix** [comment]
Thanks @darshankawar & @rmahmadkhan. Switchwing to the master and upgrading fixes the issue.
