### ISSUE TITLE
[video_player] Video with transparent background

### ISSUE THREAD

**Issue by guyluz11** [flutter/flutter#120671]
Can we add support for videos with transparent background?.
One video coding format that supports that is [VP9](https://en.wikipedia.org/wiki/VP9).

**Comment by huycozy** [comment]
@guyluz11 Can you share the video source as an example? I try testing this with [VP9 videos](https://test-videos.co.uk/bigbuckbunny/webm-vp9) (using `video_player: ^2.5.1`). It can play well.
