### ISSUE TITLE
Timeouts on mac iOS devicelab tests

### ISSUE THREAD

**Issue by loic-sharma** [flutter/flutter#120648]
These two tests closed the framework tree by timing out:

1. https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_ios%20complex_layout_ios__start_up/9174/overview
2. https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_ios%20flutter_gallery__transition_perf_e2e_impeller_ios/2664/overview

Subsequent re-runs passed.

**Comment by keyonghan** [comment]
Marking as dup of https://github.com/flutter/flutter/issues/121231, https://github.com/flutter/flutter/issues/120808
