### ISSUE TITLE
Migrate cirrus tests to LUCI

### ISSUE THREAD

**Issue by drewroengoogle** [flutter/flutter#120626]
Instead of updating the cirrus keys every couple of months and having multiple places for tests, it may make more sense to move any tests in cirrus over to LUCI

Relevant ticket queue issue: https://github.com/flutter/flutter/issues/120386

**Comment by drewroengoogle** [comment]
CC: @godofredoc

**Comment by stuartmorgan** [comment]
Is this a duplicate of https://github.com/flutter/flutter/issues/114373, or is it about a different repository?

**Comment by drewroengoogle** [comment]
It looks like it is. Thanks! I'll close it.
