### ISSUE TITLE
The handling of the "button click" event not working - Interpretation crashes for button presses

### ISSUE THREAD

**Issue by MohamadAlahmad** [flutter/flutter#120687]
Hello .
I have an application for IPTV services such as live streaming, VOD, etc.
It was created based on Flutter SDK 3.0.1, and it works very well, so that the user can navigate between the main sections of the application and the components of each section separately, all by using the "remote control device" of the tv box , (it is also possible using the mouse through the mouse pointer) .
When I downloaded Flutter 3.7.2, the interpretation of pressing buttons through the remote control device no longer works. As when the application is running, it may respond to one or two button presses, and then it does not respond to button presses, as the application throws the following exception :

```
════════ Exception caught by services library ══════════════════════════════════
A KeyDownEvent is dispatched, but the state shows that the physical key is already pressed. If this occurs in real application, please report this bug to Flutter. If this occurs in unit tests, please ensure that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This was the event: KeyDownEvent#7e0c5(physicalKey: PhysicalKeyboardKey#f5c25(usbHidUsage: "0x000700e4", debugName: "Control Right"), logicalKey: LogicalKeyboardKey#4999d(keyId: "0x10000050c", keyLabel: "Select", debugName: "Select"), character: null, timeStamp: 0:00:19.651882)
'package:flutter/src/services/hardware_keyboard.dart':
hardware_keyboard.dart:1
Failed assertion: line 428 pos 16: '!_pressedKeys.containsKey(event.physicalKey)'

════════════════════════════════════════════════════════════════════════════════
```

Explanation : "KeyDownEvent" or "KeyUpEvent" or whatever , not KeyDownEvent specifically.
Since the content of this exception is recommended to be reported to the Flutter team , please help my friends .
Thanks all ...

**Comment by darshankawar** [comment]
@MohamadAlahmad 
Looking at the error log, it seems to be similar to https://github.com/flutter/flutter/issues/101275, so please follow-up in that issue for further updates. You may upvote the original issue and also share your findings in it for better tracking.
Closing this as a duplicate.
