### ISSUE TITLE
Infra failure on Windows_android test

### ISSUE THREAD

**Issue by loic-sharma** [flutter/flutter#120642]
Flakes have caused framework tree to close occasionally. Example failures:

https://ci.chromium.org/ui/p/flutter/builders/prod/Windows_android%20hot_mode_dev_cycle_win__benchmark/8484/overview

https://ci.chromium.org/ui/p/flutter/builders/prod/Windows_android%20basic_material_app_win__compile/8572/overview

**Comment by sealesj** [comment]
@yusuf-goog for this infra failure https://ci.chromium.org/ui/p/flutter/builders/prod/Windows_android%20hot_mode_dev_cycle_win__benchmark/8484/overview I am seeing "BOT_DIED" here https://chromium-swarm.appspot.com/bot?id=flutter-win-4 

Are there any other logs that might show more information for this? And could it be related to salt states at all? I see a previous issue with bots dying mentioning that issue

**Comment by yusuf-goog** [comment]
That particular build has an extremely low failure rate. Unless the devs have a reason to suspect that there is some real underlying problem with that one failure, I think we can close this particular issue for now.

**Comment by sealesj** [comment]
Ok thank you! Closing for now and can re-open for investigation if a bot dying incident or long build rate times are seen in the future.
