### ISSUE TITLE
How to call the new API to release memory in version 3.7

### ISSUE THREAD

**Issue by srs888001** [flutter/flutter#120686]
Flutter 3.7 version says "Therefore, in this release, the Flutter engine adds API for explicitly deallocating the native resources held by Vertices, Paragraph, and ImageShader objects.",  but I can't find out how to use it? 
who can help me?

**Comment by moffatman** [comment]
If you have a `ui.Paragraph`, you can call dispose() on it. But in general this is something handled in the framework, you shouldn't need to do anything.

**Comment by jonahwilliams** [comment]
There is not a public API for freeing memory in general. When you're done using objects that have a dispose method (Vertices, Paragraph, ImageShader), you should dispose them and the framework will more eagerly collect that memory
