### ISSUE TITLE
Fix unit tests that depend on `info` diagnostics from dart analysis

### ISSUE THREAD

**Issue by eyebrowsoffire** [flutter/flutter#120750]
The info/hint category of dart analyzer diagnostics is being removed: https://github.com/dart-lang/sdk/issues/50796

As part of that effort, one of the "info" diagnostics that we use in our unit tests (`missing_return`) was changed to a "warning" https://dart-review.googlesource.com/c/sdk/+/282164. This broke the Engine -> Framework roller when the dart sdk change bubbled up to the framework: https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8789134064052154849/+/u/run_test.dart_for_tool_integration_tests_shard_and_subshard_3_4/test_stdout

I am looking to temporarily revert this change in the dart sdk to unblock the rollers, but it will eventually need to reland. We could use a different `info` diagnostic to check these tests, but since this entire category of diagnostics is going away, we probably just need to remove some unit tests entirely, and possibly modify the tool to remove command line flags associated with `info` style diagnostics since they will no longer exist.

**Comment by zanderso** [comment]
IIUC, these tests are checking the behavior of the `--fatal-infos` and `--no-fatal-infos` flags. So they don't really care what the diagnostic is, as long as it gets flagged as `info`. Before the analyzer breaking change `missing_return` was a "hint", which would get flagged as `info`, but after the breaking change it is a "static warning", which gets flagged as `warning`. But we can adjust how the diagnostic is flagged in the `analysis_options.yaml`, and pin `missing_return` to `info`. Trying that here https://github.com/flutter/flutter/pull/120797.

**Comment by zanderso** [comment]
This is fixed by https://github.com/flutter/flutter/pull/120797
