### ISSUE TITLE
Updating initialValue in TextFormField does not rebuild TextFormField

### ISSUE THREAD

**Issue by IvoneDjaja** [flutter/flutter#120760]
Hi, I want to ask regarding the behavior of the `TextFormField`. 

Initially, `text` is null and `TextFormField` displays an empty text. After fetching the data, TextFormField should rebuild and display the data, the issue is that TextFormField is not rebuilding and it is still displaying an empty text.

Updating the `initialValue` it does not seem to rebuild to the new value. Using `controller` seems like overkill and using `key` will destroy and build the widget again, which feels unnecessary. 

After checking `didUpdateWidget` in  `TextFormField`, I find that we are only comparing the `controller`, but not comparing the `initialValue`, so it never rebuilds. Shouldn't `didUpdateWidget` check the `initialValue` as well, so that the widget can rebuild?

## Steps to Reproduce

1. Run the app on https://dartpad.dev/
2. Initially, the text variable is null and TextFormField displays empty string.
3. Taps on the refresh button in the AppBar to set data to the text variable inside a setState

**Expected results:** 
TextFormField should rebuild and display this text "sunt aut facere repellat provident occaecati excepturi optio reprehenderit".

**Actual results:** 
TextFormField is not rebuilding and it is still displaying empty string, even though the value is correctly set in the text variable.

<details>
<summary>Code sample</summary>

```dart
import 'dart:convert';

import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  String? text;

  @override
  Widget build(BuildContext context) {
    print("text: ${text}");
    return Scaffold(
      appBar: AppBar(
        title: Row(children: [
          Text(widget.title),
          IconButton(onPressed: _getData, icon: const Icon(Icons.refresh)),
        ]),
      ),
      body: Center(
        child: Column(
          children: [
            const Text('TextFormField'),
            TextFormField(
              initialValue: text,
            )
          ],
        ),
      ),
    );
  }

  Future _getData() async {
    print("Taps on the refresh button");
    final response = await http
        .get(Uri.parse("https://jsonplaceholder.typicode.com/posts/1"));
    if (response.statusCode == 200) {
      final data = jsonDecode(response.body);
      setState(() {
        text = data['title'];
      });
    }
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```
text: null
Taps on the refresh button
text: sunt aut facere repellat provident occaecati excepturi optio reprehenderit
```

```
```

```
```

</details>

<img width="951" alt="Screenshot 2023-02-15 at 3 08 29 PM" src="https://user-images.githubusercontent.com/59554430/218956900-29292295-cc73-43ee-98c7-decea55f78e8.png">

**Comment by exaby73** [comment]
Hey @IvoneDjaja. This is expected. `initialValue` does what it says... Just setting the initial value. `TextFeild` manages it's own `TextEditingController` if one is not provided and `initialValue` is only set when the widget first builds (`initState`).

The way to solve this is to use a `TextEditingController` and updating it's `text` property instead of relying on `initialValue`. This is working as expected and therefore, I am closing this issue.

PS: If you want a way to lessen your code, you can try out `useTextEditingController` from the `flutter_hooks` package :)
