### ISSUE TITLE
Appium - iOS - Building using debug-mode is not supported

### ISSUE THREAD

**Issue by marceloadsj** [flutter/flutter#120789]
Hello everyone. 1st of all, thx for your great work on this project! :)

#### Trying to use iOS and Appium

Following a research of using iOS, [Appium](https://github.com/appium-userland/appium-flutter-driver) and specific APIs like [getRenderObjectDiagnostics](https://api.flutter.dev/flutter/flutter_driver/FlutterDriver/getRenderObjectDiagnostics.html) I faced some issues that blocked me.

### Appium cannot use debug-mode iOS builds

On this ticket: https://github.com/flutter/flutter/issues/73935
We see that Appium cannot start an iOS application that was build using `debug` mode.

**Do we have a way to launch a debug-mode iOS build via flutter cli or something of those sorts?**

![image](https://user-images.githubusercontent.com/4874089/219045224-ad105b1f-f997-4a97-a3b6-2821346434a8.png)

### A possible solution is to use profile-mode

While researching on Appium Flutter Driver, I found: https://github.com/appium-userland/appium-flutter-driver/issues/115
Which describes that the solution right now is to build the iOS app in `profile` mode in order to use Appium.

### By using profile-mode iOS builds, some APIs are unavailable

But by doing that, we lose the possibility to use the API I mentioned: https://github.com/flutter/flutter/issues/70772

___

**I opened this issue following @Hixie comment here: https://github.com/flutter/flutter/issues/70772#issuecomment-797820367**

PS: Please, if a solution is 100% achievable from userland, let me know and feel free to close off this issue!

**Comment by darshankawar** [comment]
@marceloadsj 
Please check [this](https://stackoverflow.com/a/75137995) link and see if it helps in your case.

**Comment by marceloadsj** [comment]
Hello @darshankawar thanks for your reply.

Well, I did good info on those links related to "other options" of integration testing on Flutter apps.

But regarding the core issue, I couldn't find anything.

Just to be in sync, the root problem is **an iOS Flutter app built in debug-mode cannot run externally, without being from Flutter cli".

From there I had 2 options
1) check exactly why the app can't run, and see if, on Appium, I can make the debug-mode app to run via flutter cli.

2) or, forget about debug-mode and use profile-mode. But this creates a new problem: some APIs are not available in this mode. So, here the question is: is there a way to keep them in place? (APIs like `getRenderObjectDiagnostics`)

**Comment by darshankawar** [comment]
Thanks for the feedback.



> 2\. forget about debug-mode and use profile-mode. But this creates a new problem: some APIs are not available in this mode. So, here the question is: is there a way to keep them in place? (APIs like `getRenderObjectDiagnostics`)

https://github.com/flutter/flutter/issues/70772 would be the right link to follow-up on for this scenario.

> 1. check exactly why the app can't run, and see if, on Appium, I can make the debug-mode app to run via flutter cli. _This would became an Appium concern, thus this issue could be closed_

I am not sure how Flutter would fix anything for this scenario, since it seems to be requirement from iOS level itself as it can't be open in debug mode for iOS 14+, so I think the change should probably made at Appium level to support it.

Based on above, I will go ahead and close it as I don't think this would be actionable from Flutter side. If you disagree, write in comments and I'll reopen it.

**Comment by marceloadsj** [comment]
@darshankawar regarding:

`since it seems to be requirement from iOS level itself as it can't be open in debug mode for iOS 14+`

Do you have, please, any document from iOS, from Flutter or any "code", that explains what exactly is that requirement?

**Comment by marceloadsj** [comment]
Any input from @Hixie side here, please?

I'm tagging you as you asked for us to open an issue to discuss this behaviour.
https://github.com/flutter/flutter/issues/70772

Thanks!

**Comment by Hixie** [comment]
Yeah this might actually be a bug that has to be filed with Appium rather than Flutter, but let's reopen this while we figure out exactly where the fix would have to happen.

**Comment by jmagman** [comment]
The limitation is that on iOS 14+ any JIT app (Flutter iOS debug mode) needs to be launched by a debugger either from lldb or Xcode. See: 
https://github.com/flutter/flutter/issues/60657
https://github.com/flutter/flutter/issues/62518
https://github.com/flutter/engine/pull/20980

When you `flutter run` or run from a Flutter IDE plugin, the app is built under the covers with `xcodebuild`, then the `.app` bundle is being installed and launched via an lldb debugserver session by a tool called [`ios-deploy`](https://github.com/ios-control/ios-deploy) which is shipped in the flutter SDK at `bin/cache/artifacts/ios-deploy/ios-deploy`.  Appium, or any tooling, could do the same and use `ios-deploy` to launch the app with the debugger.  See https://github.com/ios-control/ios-deploy#examples or run `bin/cache/artifacts/ios-deploy/ios-deploy -h` to see the available commands and flags (`--justlaunch`, etc).

https://github.com/flutter/flutter/blob/888b7b9b19642e18e001e3edfa9438c2624d8773/packages/flutter_tools/lib/src/ios/ios_deploy.dart#L167-L198

https://github.com/flutter/flutter/blob/888b7b9b19642e18e001e3edfa9438c2624d8773/packages/flutter_tools/lib/src/ios/ios_deploy.dart#L121-L165

This is the workaround Flutter tooling uses for the iOS 14+ limitation of running a JIT app on iOS, so Appium should be able to do the same.

Does that answer your question?

**Comment by marceloadsj** [comment]
Thanks a lot everyone for your detailed explanation, I really appreciate it! <3

I believe Appium (and any other userland tooling) can use the info provided by @jmagman to be able to launch Flutter apps in debug mode.

I will close this issue and continue the discussion on Appium side. Thanks again! :)
