### ISSUE TITLE
[go_router] Query parameters persist after native back navigation

### ISSUE THREAD

**Issue by filly82** [flutter/flutter#120719]
when navigating to a route with query parameters and then going back via native back navigation (Android's back button. Android's and iOS' swipe back gesture) than the query params persist.
as mentioned here [https://github.com/flutter/flutter/issues/99122](https://github.com/flutter/flutter/issues/99122) this is by design and a general "issue" (not only on back navigation) and @chunhtai provided a solution/workaround here [https://github.com/flutter/flutter/issues/99122#issuecomment-1101725856](https://github.com/flutter/flutter/issues/99122#issuecomment-1101725856) by clearing them when necessary, but I don't see how to do that on _native back navigation_. a onBackNavigation handler seems to be required to handle that

**Comment by chunhtai** [comment]
For native iOS, it feels like you actually want to use a GoRouter.push to navigate to a new screen with query parameter, that way the query parameter will only persist on that page.
