### ISSUE TITLE
Research support for docker on LUCI to support packages repo with Emulators

### ISSUE THREAD

**Issue by ricardoamador** [flutter/flutter#120732]
The Linux tests in the packages repository run on docker in cirrus. I need to research how to get this to work in LUCI. Yusuf has an OKR for this and there may be some recipes supporting docker in the Fuchsia dependencies.

Fuchsia recipe code: https://source.corp.google.com/fuchsia-infra/fuchsia/recipes/recipe_modules/docker/api.py?q=docker&ss=piper%2FGoogle%2Ffuchsia-infra:fuchsia%2Frecipes%2F

**Comment by stuartmorgan** [comment]
I believe to a large extent these repos use Docker because that's the way to easily get dependence set up for Cirrus, rather than a specific attachment to Docker. I'm fine with non-Docker solutions; e.g., i don't think anything in the Docker for is for Android other than the FTL tests in particular (which we wouldn't need for tasks that used emulators).

**Comment by ricardoamador** [comment]
Okay. thank you for the info Stuart. That might make the initial transition easier.

**Comment by stuartmorgan** [comment]
To follow up on my comment above with a little more detail, the current use of Docker that I'm aware of:
- We use the Cirrus Flutter base image, which gives us things like Flutter itself and the necessary Android toolchains.
    - I would expect this be an already-solved problem in flutter/flutter, so doubt we need Docker for this.
- We add FTL requirements.
    - If we have FTL use in flutter/flutter then this is already solved; if not, I would expect we could address this via the normal LUCI dependency process (e.g., with a CIPD package).
- We install clang-format
    - I'm not sure we can pull out just this piece from existing engine functionality; if not a new dependency would presumably be straightforward.
- We install the Linux desktop dev tools
    - I'm almost positive we have all of this for flutter/flutter already
- We install xvfb for headless execution
    - I'm not sure if that was solved already for flutter/flutter; I know it came up there.
- We make Chrome a default browser for some `url_launcher` tests that need to check scheme handlers.
    - I'm not sure if there's a straightforward solution for this.
- We install `libgbm-dev` for `web_benchmarks`
    - I'm not familiar with the details of this.

I would expect that most, if not all, of our existing Linux tests can be migrated without Docker support based on that list.

**Comment by ricardoamador** [comment]
Hi Stuart, thank you for the info. I am intending to look into this soon. Just have a couple changes for some other features and this one is next up for me.

**Comment by stuartmorgan** [comment]
I'm going to close this since we completed the LUCI migration without Docker support.
