### ISSUE TITLE
Increase verbosity of the 'download dependencies' step

### ISSUE THREAD

**Issue by loic-sharma** [flutter/flutter#120708]
Currently the download dependencies step does not output why it failed. This makes debugging issues difficult.

Example failure that closed the framework tree today: https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20customer_testing/11337/overview

Here's the download step: https://cs.opensource.google/flutter/recipes/+/master:recipes/flutter/flutter_drone.py;l=92?q=file:recipes%2Fflutter%2Fflutter_drone.py

/cc @christopherfujino

**Comment by christopherfujino** [comment]
CL at https://flutter-review.git.corp.google.com/c/recipes/+/39280

**Comment by christopherfujino** [comment]
Closing as https://flutter-review.git.corp.google.com/c/recipes/+/39280 has merged
