### ISSUE TITLE
camera - plugin - CamcorderProfile.getAll - Android 12

### ISSUE THREAD

**Issue by Taverz** [flutter/flutter#120776]
Please, help!!
Do you need to urgently solve the problem, even if it is some kind of temporary solution or workaround?
Is it possible to somehow hardcode certain parameters or data to make the plugin work?

Device Feature:
- Android 12
- Android SDK 32
- Does not have cameras
- Lots of USB ports

Android Studio from M1-Apple

<details>
  <summary>  flutter doctor -v</summary>
  flutter doctor -v
[✓] Flutter (Channel stable, 3.7.1, on macOS 13.2 22D49 darwin-arm64, locale ru-RU)
     • Flutter version 3.7.1 on channel stable at /Users/User/Documents/devflutter/flutter
     • Upstream repository https://github.com/flutter/flutter.git
     • Framework revision 7048ed95a5 (2 weeks ago), 2023-02-01 09:07:31 -0800
     • Engine revision 800594f1f4
     • Dart version 2.19.1
     • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
     • Android SDK at /Users/User/Library/Android/sdk
     • Platform android-33, build-tools 30.0.3
     • ANDROID_HOME = /Users/User/Library/Android/sdk
     • Java binary at: /Users/User/.sdkman/candidates/java/current/bin/java
     • Java version OpenJDK Runtime Environment Zulu11.52+13-CA (build 11.0.13+8-LTS)
     • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
     • Xcode at /Applications/Xcode.app/Contents/Developer
     • Build 14B47b
     • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
     • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 2022.1)
     • Android Studio at /Applications/Android Studio.app/Contents
     • Flutter plugin can be installed from:
       🔨 https://plugins.jetbrains.com/plugin/9212-flutter
     • Dart plugin can be installed from:
       🔨 https://plugins.jetbrains.com/plugin/6351-dart
     ✗ Unable to find bundled Java version.
     • Try updating or re-installing Android Studio.

[✓] VS Code (version 1.75.0)
     • VS Code at /Users/User/Documents/Visual Studio Code.app/Contents
     • Flutter extension version 3.58.0

[✓] Connected device (3 available)
     • rk3588 (mobile) • ISCH6N81SS • android-arm64 • Android 12 (API 32)
     • macOS (desktop) • macos • darwin-arm64 • macOS 13.2 22D49 darwin-arm64
     • Chrome (web) • chrome • web-javascript • Google Chrome 109.0.5414.119

[✓] HTTP Host Availability
     • All required HTTP hosts are available

! Doctor found issues in 1 category.

</details>

1. I connected an external camera via USB.
2. I checked that the camera is working: I went into the system application camera, camera !! works.
3. Tried a simple android.hardware.camera2 example (run android code): !! works (external camera success): the camera sees and successfully displays the image from it.
4. I took the last sample code from branch=main https://github.com/flutter/plugins/tree/main/packages/camera/camera
5. Launched as Flutter debug
6. Application started successfully
7. Clicked on select EXTERNAL camera (connect via USB).
8. ERRORE : !!!!!!! android.media.CamcorderProfile.getAll // android.media.CamcorderProfile.native_get_camcorder_profiles

(I tried to change the java code but without success)

<details>
  <summary>Log errore</summary>

Launching lib/main.dart on rk3588 in debug mode...
✓ Built build/app/outputs/flutter-apk/app-debug.apk.
Connecting to VM Service at ws://127.0.0.1:56408/dxxd9TAdu50=/ws
I/CameraManagerGlobal(16481): Connecting to camera service
E/MediaProfiles(16481): The given camcorder profile camera 101 quality 0 is not found

After tap select camera EXTERNAL
-> ->
E/MethodChannel#plugins.flutter.io/camera(16481): Failed to handle method call
E/MethodChannel#plugins.flutter.io/camera(16481): java.lang.RuntimeException: Error retrieving camcorder profile params
E/MethodChannel#plugins.flutter.io/camera(16481): at android.media.CamcorderProfile.native_get_camcorder_profiles(Native Method)
E/MethodChannel#plugins.flutter.io/camera(16481): at android.media.CamcorderProfile.getAll(CamcorderProfile.java:605)
E/MethodChannel#plugins.flutter.io/camera(16481): at io.flutter.plugins.camera.features.resolution.ResolutionFeature.getBestAvailableCamcorderProfileForResolutionPreset(ResolutionFeature.java:231)
E/MethodChannel#plugins.flutter.io/camera(16481): at io.flutter.plugins.camera.features.resolution.ResolutionFeature.configureResolution(ResolutionFeature.java:278)
E/MethodChannel#plugins.flutter.io/camera(16481): at io.flutter.plugins.camera.features.resolution.ResolutionFeature.<init>(ResolutionFeature.java:53)
E/MethodChannel#plugins.flutter.io/camera(16481): at io.flutter.plugins.camera.features.CameraFeatureFactoryImpl.createResolutionFeature(CameraFeatureFactoryImpl.java:58)
E/MethodChannel#plugins.flutter.io/camera(16481): at io.flutter.plugins.camera.features.CameraFeatures.init(CameraFeatures.java:71)
E/MethodChannel#plugins.flutter.io/camera(16481): at io.flutter.plugins.camera.Camera.<init>(Camera.java:215)
E/MethodChannel#plugins.flutter.io/camera(16481): at io.flutter.plugins.camera.MethodCallHandlerImpl.instantiateCamera(MethodCallHandlerImpl.java:385)
E/MethodChannel#plugins.flutter.io/camera(16481): at io.flutter.plugins.camera.MethodC

</details>

**Comment by exaby73** [comment]
Hello @Taverz. Just to eliminate anything Flutter specific, can you reproduce this with the Master channel of Flutter as well?

**Comment by Taverz** [comment]
Hello @exaby73  .  I don't quite understand what you are talking about, can you be more specific? As I understand the error in the method call JNI .

**Comment by exaby73** [comment]
Just trying to cover all bases :) Have you tried with an Android 13 device or is that not possible?

**Comment by Taverz** [comment]
@exaby73  I ran the plugin with android 13, but it has system cameras and it worked well with them, but I couldn’t get it to switch to an external camera, so I didn’t test it.

**Comment by huycozy** [comment]
Hi @Taverz 
I see there's an open issue #42413 which says the external USB camera can not be recognized.

I will close this issue in favor of #42413, so please follow up on it for further updates. You can leave there your comment with above information that may be useful for later investigation. And also reacting an upvote to the original comment will help to raise the issue. Thank you!

**Comment by Taverz** [comment]
## Solution errore: retrieving camcorder profile params. 

## This file redacted:   
- MediaRecorderBuilder.java  
- Camera.java. 
- ResolutionFeature.java. 

## Delete field:  
- CamcorderProfile. 
- EncoderProfiles. 


## Method editing. 

```
  public MediaRecorder build() throws IOException, NullPointerException, IndexOutOfBoundsException {
    MediaRecorder mediaRecorder = recorderFactory.makeMediaRecorder();

    // There's a fixed order that mediaRecorder expects. Only change these functions accordingly.
    // You can find the specifics here: https://developer.android.com/reference/android/media/MediaRecorder.
    if (enableAudio) mediaRecorder.setAudioSource(MediaRecorder.AudioSource.MIC);
    mediaRecorder.setVideoSource(MediaRecorder.VideoSource.SURFACE);

    if (Build.VERSION.SDK_INT >= 31) {
//      EncoderProfiles.VideoProfile videoProfile = encoderProfiles.getVideoProfiles().get(0);
//      EncoderProfiles.AudioProfile audioProfile = encoderProfiles.getAudioProfiles().get(0);
      String vvvww =" WIN == " ;
//      vvvww = vvvww + " getRecommendedFileFormat "+ encoderProfiles.getRecommendedFileFormat() ;
//      if (enableAudio) {
//        vvvww = vvvww + " getCodec "+ audioProfile.getCodec();
//        vvvww = vvvww + " getBitrate "+ audioProfile.getBitrate();
//        vvvww = vvvww + " getSampleRate "+ audioProfile.getSampleRate();
//      }
//      vvvww = vvvww + " videoProfile.getCodec "+ videoProfile.getCodec();
//      vvvww = vvvww + " videoProfile.getBitrate "+ videoProfile.getBitrate();
//      vvvww = vvvww + " videoProfile.getFrameRate "+ videoProfile.getFrameRate();
//
//      vvvww = vvvww + " videoProfile.getWidth "+ videoProfile.getWidth();
//      vvvww = vvvww + " videoProfile.getHeight "+ videoProfile.getHeight();


      Log.e("EncoderProfilesWWWW", vvvww);

//      MediaRecorder.OutputFormat.DEFAULT  // encoderProfiles.getRecommendedFileFormat()
      mediaRecorder.setOutputFormat(MediaRecorder.OutputFormat.DEFAULT);
//      if (enableAudio) {
//        // 0 - 7 // 2
//        mediaRecorder.setAudioEncoder(MediaRecorder.AudioEncoder.DEFAULT); //audioProfile.getCodec());
////        mediaRecorder.setAudioEncodingBitRate(audioProfile.getBitrate());
////        mediaRecorder.setAudioSamplingRate(audioProfile.getSampleRate());
//      }
      // 0 - 5 // 3
      mediaRecorder.setVideoEncoder(MediaRecorder.VideoEncoder.DEFAULT); // mediaRecorder.setVideoEncoder(videoProfile.getCodec());
      // ??
//      mediaRecorder.setVideoEncodingBitRate(videoProfile.getBitrate());
      // 0 , 90, ...
//      mediaRecorder.setVideoFrameRate(videoProfile.getFrameRate());
      // me size
      mediaRecorder.setVideoSize(600, 600); // videoProfile.getWidth(), videoProfile.getHeight());
      mediaRecorder.setVideoSize(600, 600);
    } else {
      /// MediaRecorder.OutputFormat.RAW_AMR
      // mediaRecorder.setOutputFormat(MediaRecorder.OutputFormat.THREE_GPP);  //camcorderProfile.fileFormat);
      // if (enableAudio) {
      //   mediaRecorder.setAudioEncoder(MediaRecorder.AudioEncoder.AMR_NB);  //camcorderProfile.audioCodec);
      //   mediaRecorder.setAudioEncodingBitRate(16); //camcorderProfile.audioBitRate
      //   mediaRecorder.setAudioSamplingRate(camcorderProfile.audioSampleRate);
      // }
      // mediaRecorder.setVideoEncoder(camcorderProfile.videoCodec);
      // mediaRecorder.setVideoEncodingBitRate(camcorderProfile.videoBitRate);
      // mediaRecorder.setVideoFrameRate(camcorderProfile.videoFrameRate);
      // mediaRecorder.setVideoSize(
      //     camcorderProfile.videoFrameWidth, camcorderProfile.videoFrameHeight);
    }

    mediaRecorder.setOutputFile(outputFilePath);
    mediaRecorder.setOrientationHint(this.mediaOrientation);

    mediaRecorder.prepare();

    return mediaRecorder;
  }
```

**Comment by Taverz** [comment]
@exaby73 Solution errrore
