### ISSUE TITLE
Linux docs_publish test timeouts

### ISSUE THREAD

**Issue by loic-sharma** [flutter/flutter#120725]
The Linux docs_publish test is repeatedly reaching a 60 minute timeout: https://ci.chromium.org/p/flutter/builders/prod/Linux%20docs_publish

[Increasing the `.ci.yaml` timeout to 90 minutes](https://github.com/flutter/flutter/pull/120718) did not work, the build still times out after 60 minutes: https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20docs_test/9003/overview

@christopherfujino found that the `.ci.yaml` hasn't rolled yet: https://ci.chromium.org/p/flutter/builders/prod/Linux%20ci_yaml%20flutter%20roller

**Comment by christopherfujino** [comment]
he build dashboard has a yellow square (pending) for the `Linux ci_yaml flutter roller` build for the commit 480c54c370a651906e019f20e92d15673b6a4431, even though that doesn't show from https://ci.chromium.org/p/flutter/builders/prod/Linux%20ci_yaml%20flutter%20roller. There is plenty of idle capacity, so maybe the RPC got lost?

**Comment by godofredoc** [comment]
Clicked the re-run button and it is running https://ci.chromium.org/p/flutter/builders/prod/Linux%20ci_yaml%20flutter%20roller/7500

**Comment by loic-sharma** [comment]
Looks like the `Linux ci_yaml flutter roller` completed, I will kick off another `Linux docs_publish` as I suspect the current one will timeout after 60 minutes again.

**Comment by Hixie** [comment]
If it's literally taking an hour to build the docs/docset/whatever we need to find a way to optimize that. We don't want to be waiting an hour for shards to complete.

**Comment by loic-sharma** [comment]
@Hixie Totally agreed. This issue is more targeted towards short-term mitigation, but see this [internal conversation](https://chat.google.com/room/AAAAQFWU2Go/nA9UR7kMHYE) for long-term solutions. @godofredoc and @christopherfujino are brainstorming some interesting ideas like removing docset altogether, or moving the docset to a secondary build once we have build/test separation.

**Comment by loic-sharma** [comment]
@godofredoc The framework tree is open again. I'm not sure if you plan to do any follow-up items, so I'll leave this open. Feel free to close this when ready!

**Comment by Hixie** [comment]
might be worth having those conversations in public, i can't see that chat from this workstation. :-)

**Comment by ricardoamador** [comment]
Closing as it looks like this is resolved or there are other plans coming out of it.
