### ISSUE TITLE
Issues using Asset-Only Deferred Components in Flutter 

### ISSUE THREAD

**Issue by liamcannon36** [flutter/flutter#120743]
Hello ! I am working on uploading a Flutter app to Google Play, and I am exploring deferred components as a solution to the app's large assets. Right now , I am trying to use deferred components in the flutter starter app, but I am having some issues.

 I set up the deferred component , named df1, following this guide : https://docs.flutter.dev/perf/deferred-components . This deferred component has just one image as a test. Since it is an asset-only deferred component, I used installDeferredComponent in main.dart, passing the df1 component name. Now if my understanding is correct, the assets are loaded, and those listed in the pubspec.yaml under df1 would now be available to me. But when I build and install the app ( using bundletool) , the app builds fine but the image is not present on the screen. Below I have included pictures of  my : 

pubpsec.yaml : 

![image](https://user-images.githubusercontent.com/64112814/218903921-adedccbe-25bd-4b8f-8ae3-0ee1c1032a0e.png)

main.dart ( Where I install deferred component and where I attempt to use the asset in df1)

![image](https://user-images.githubusercontent.com/64112814/218904310-0417369a-6db0-44c6-abfe-f28ffec97551.png)

![image](https://user-images.githubusercontent.com/64112814/218904448-29996372-3136-4031-9282-2939b5c462ad.png)

deferred_components_loading_units.yaml: 

![image](https://user-images.githubusercontent.com/64112814/218905023-0d73ffc1-9a51-4dc8-a438-1cf77644d499.png)

My most pressing questions are this: 

1. Is my assumption (that installDeferredComponent) makes the assets available by string correct? I do not see any example for using this method, but that's what it seems to be doing. 

2. Are deferred components a good workaround for the size limit on Google Play? It seems like Play Asset Delivery is more suitable, but Flutter does not natively support this as far as I know. 

My somewhat related other question is : is bundletool suitable to test whether my flutter app will pass the size restriction ? 

If there is any other additional information I can supply that will help to answer my question, please let me know. Any help is greatly appreciated, as we are trying to release the app as soon as possible. Thank you !

**Comment by jonahwilliams** [comment]
In the example code you provided, you're not awaiting the result of installDeferredComponent. This is a requirement, as the assets won't be ready until that future completes - at least according to the documentation.

**Comment by liamcannon36** [comment]
> Member

Thank you , I will try this .

**Comment by liamcannon36** [comment]
@jonahwilliams 
So I added the code to await for the installDeferredComponent function to finish, and now the app is showing a black screen ( which suggests to me it cannot find the deferred component, so the await never finishes). Here is the screenshot of the code below : 

![image](https://user-images.githubusercontent.com/64112814/219418091-bc8a962a-5939-4b0b-82eb-f6731a33b7cb.png)


For the minimal reproducible code sample, I have included the whole repo( since besides the deferred component files, it is just the starter flutter app).  The zip for it is here :

[def_comps (2).zip](https://github.com/flutter/flutter/files/10758045/def_comps.2.zip)

Here is the output of my flutter doctor -v : 

[flutter_doctor_v.txt](https://github.com/flutter/flutter/files/10758094/flutter_doctor_v.txt)


Thank you !

**Comment by huycozy** [comment]
@liamcannon36 Does the project can run normally from your end? Or does the issue only happen when installing from ouput build? (aab/apk file)

As I see, your asset usage is missing `s` in the code: `AssetImage("asset/img1.png")`. Let's try with `AssetImage("assets/img1.png")` to see if it works.

Also, you are using a quite old Flutter version `2.2.2`. Please retry on the latest Flutter versions (stable `3.7.3` and master `3.8.0`) to see if the issue still persists or not.
