### ISSUE TITLE
Long black screen on Android when running the App

### ISSUE THREAD

**Issue by alwangk** [flutter/flutter#120766]
It's take long time to run the app on Android (run normally on iOS) after updgrading flutter
 from [3.3.10](https://storage.googleapis.com/flutter_infra_release/releases/stable/macos/flutter_macos_3.3.10-stable.zip) to [3.7.1](https://storage.googleapis.com/flutter_infra_release/releases/stable/macos/flutter_macos_3.7.1-stable.zip). 

do I miss something?

on main.dart

```
void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  await FlutterDownloader.initialize(
      debug:
          true, 
      ignoreSsl:
          true 
      );

  FirebaseMessaging.onMessage.listen((RemoteMessage message) {

    if (message.notification != null) {
    }
    FlutterAppBadger.updateBadgeCount(1);
  });

  FirebaseMessaging.instance.getInitialMessage().then((message) {
    if (message != null) {
      FlutterAppBadger.removeBadge();
    }
  });

  FirebaseMessaging.onBackgroundMessage(_firebaseMessagingBackgroundHandler);

  await FirebaseMessaging.instance.subscribeToTopic('news');

  bool result = await SharedService.isLoggedIn();

  if (result) {
    _defaultHome = SplashScreenLoggedInView();
  }

  runApp(const MyApp());
}
```

**Comment by opxdelwin** [comment]
can you run your app using `flutter run -v`

**Comment by exaby73** [comment]
Hello @alwangk. 2 questions: 1. Can you reproduce this with a default counter app? And 2. Are you running in release mode or debug mode?

**Comment by alwangk** [comment]
> Hello @alwangk. 2 questions: 1. Can you reproduce this with a default counter app? And 2. Are you running in release mode or debug mode?

I made new flutter project with default counter app. Its show black screen like 1 or 2 sec before on HomePage screen.

I'm running on debug mode, and yesterday I build the apk --release for internal testing and found the long black screen.

**Comment by alwangk** [comment]
> can you run your app using `flutter run -v`

yes, its running but still showing black screen

**Comment by exaby73** [comment]
@alwangk Is this reproducible on an emulator? Can you also provide the device details that it's reproducible on? And if possible, also check on other devices if it's reproducible

**Comment by alwangk** [comment]
> @alwangk Is this reproducible on an emulator? Can you also provide the device details that it's reproducible on? And if possible, also check on other devices if it's reproducible

Yes I'm running on emulator also on real device. 2 different Android device but still the same.

**Comment by opxdelwin** [comment]
From your code, I see that you're subscribing to a FCM topic in your `main` function. Is there any logs that you could share?

**Comment by huycozy** [comment]
@alwangk 

>I'm running on debug mode, and yesterday I build the apk --release for internal testing and found the long black screen.

Is this issue reproducible locally in debug mode? Or it's only reproducible on internal testing?

Could you please record a video for this issue? Also, which devices are you testing on? (OS, model)

**Comment by alwangk** [comment]
> @alwangk
> 
> > I'm running on debug mode, and yesterday I build the apk --release for internal testing and found the long black screen.
> 
> Is this issue reproducible locally in debug mode? Or it's only reproducible on internal testing?
> 
> Could you please record a video for this issue? Also, which devices are you testing on? (OS, model)

sorry I don't know what you mean about 'reproducible', but I tested in debug and release mode its return long black screen

this containts 2 videos android and ios.
Android OS 13, and iOS 16.2

https://drive.google.com/drive/folders/1tEI46Hg2c1DMJfX5z6bbDeiL5UHcMFEj

**Comment by alwangk** [comment]
Im downgrading flutter back to 3.3.10 and its run normal. Do you think I need to try upgrading to newest flutter 3.7.3?

**Comment by opxdelwin** [comment]
try flutter 3.7.3

**Comment by huycozy** [comment]
@alwangk From your recorded video, it looks like a production app instead of counter app which is built from the default Flutter project. And we are not sure if you have configured something on native side or added splash screen or used plugins.

So please retry on the default Flutter project. If it still happens after that, you may try on the latest Flutter stable (`3.7.3`) and master (`3.8.0`) channels as well.

**Comment by alwangk** [comment]
> @alwangk From your recorded video, it looks like a production app instead of counter app which is built from the default Flutter project. And we are not sure if you have configured something on native side or added splash screen or used plugins.
> 
> So please retry on the default Flutter project. If it still happens after that, you may try on the latest Flutter stable (`3.7.3`) and master (`3.8.0`) channels as well.

yes, because I wonder why its taking too long on my production apps only on Android.

I have try on the latest flutter version (3.7.4) and still the same. I try comment all firebase config on main() Then its run smoothly, but theres no way I remove firebase on my apps. 

Then I just found that if user allow location service its take too long. When user not allow location service its run smoothly. Why its only on Android device ....

**Comment by huycozy** [comment]
Unfortunately, we can not verify the production project.

For the issue to be workable, it needs to be reproducible with a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code. 

Also, I would suggest you remove 3rd party plugins or native setup (splash screen if any) to find out which one caused this.

**Comment by alwangk** [comment]
> Unfortunately, we can not verify the production project.
> 
> For the issue to be workable, it needs to be reproducible with a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code.
> 
> Also, I would suggest you remove 3rd party plugins or native setup (splash screen if any) to find out which one caused this.

It's because `geolocator` package. Fixed this by adding
```
dependency_overrides: 
    geolocator: 9.0.1 
    geolocator_android: 4.1.4
``` 


  references to this https://github.com/Baseflow/flutter-geolocator/issues/1220#issuecomment-1437994796
