### ISSUE TITLE
buttons/InkWell/gesture detector not working on FlexibleHeaderDelegate inside NestedScrollView

### ISSUE THREAD

**Issue by danijorda1** [flutter/flutter#120782]
Hello,

I am using NestedScrollView with the following structure:

Scaffold(
        body:
              NestedScrollView(

                  physics: ClampingScrollPhysics(),
                  headerSliverBuilder: (BuildContext context, bool innerBoxIsScrolled) {
                    return [
                      SliverPersistentHeader(
                        pinned: false,
                        floating: false,
                        delegate: FlexibleHeaderDelegate(
                          expandedHeight: 280*fem,
                          collapsedHeight: 0,
                          children: [
                                                **InkWell(
                                                    onTap: (){ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text("DO SOMETHING!!"),));},**
                                                    child:MyTopWidget(),
                                                )
                          ]
                        ),
                      ),
                      SliverOverlapAbsorber(
                        handle:NestedScrollView.sliverOverlapAbsorberHandleFor(context),
                        sliver: SliverPersistentHeader(
                          pinned: true,
                          delegate: FlexibleHeaderDelegate(
                            expandedHeight: 189*fem,
                            collapsedElevation: 0,
                            collapsedHeight: 189*fem,
                            backgroundColor: Color(0xfff8f8f8),
                            children: [
                              **InkWell(
                                onTap: (){ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text("DO SOMETHING HERE TOO!!"),));},**
                                child:MyTMiddleWidget(),
                              )
                            ],
                          ),
                        ),
                      ),
                    ];
                  },
                  body: ListView.builder(
                    ....
                  )
              )
    );

My issue is that onTap is not working in the containers wrapped by Inkwell inside  FlexibleHeaderDelegate

Below a video of my app. Basically I want to Navigate to another screen when user taps on "All Time" Container and on "Prizes" text.

https://user-images.githubusercontent.com/79714558/219024592-d024b276-7782-4d6a-a11a-a4f82f64b2ea.mp4

Do you know why buttons/InkWell/gesture detector aren't working on FlexibleHeaderDelegate inside NestedScrollView?

Thanks

**Comment by danijorda1** [comment]
There seems to be a similar issue [here](https://github.com/flutter/flutter/issues/68580) which was not resolved

**Comment by danagbemava-nc** [comment]
Hi @danijorda1, please provide a complete minimal reproducible code sample without any third-party packages/plugins so that we can investigate this. 

Please also provide the output of `flutter doctor -v`. 

Thank you

**Comment by danijorda1** [comment]
flutter doctor -v
[√] Flutter (Channel dev, 3.3.0-0.5.pre, on Microsoft Windows [Versi¢n 10.0.19045.2486], locale es-ES)
    • Flutter version 3.3.0-0.5.pre on channel dev at c:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 096162697a (6 months ago), 2022-08-22 15:34:14 -0700
    • Engine revision ad3d868e0d
    • Dart version 2.18.0 (build 2.18.0-271.7.beta)
    • DevTools version 2.15.0

[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at C:\Users\danij\AppData\Local\Android\sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Users\danij\AppData\Local\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual�Studio Community 2022 17.2.6)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual�Studio Community 2022 version 17.2.32630.192
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] VS Code (version 1.74.3)
    • VS Code at C:\Users\danij\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (4 available)
    • M2012K11AG (mobile) • 48d2360f • android-arm64  • Android 12 (API 31)
    • Windows (desktop)   • windows  • windows-x64    • Microsoft Windows [Versi¢n 10.0.19045.2486]
    • Chrome (web)        • chrome   • web-javascript • Google Chrome 110.0.5481.96
    • Edge (web)          • edge     • web-javascript • Microsoft Edge 109.0.1518.70

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Comment by danagbemava-nc** [comment]
Hi @danijorda1, you are using an older version of flutter. Kindly upgrade to the latest version of flutter stable (3.7.3) to see if you still experience this issue. If you do, please provide the updated output of `flutter doctor -v`. 

PS: The sample you provided above uses a third-party package, you'll need to provide a sample that doesn't use third-party libraries so that we can determine if this is an issue with the framework or an issue with the implementation by the third-party library. 

Thank you

**Comment by danijorda1** [comment]
Hi, with the latset flutter stable the issue is still present.

Flutter doctor fails on window check but seems this is an [issue](https://github.com/flutter/flutter/issues/117890) reported already:

[√] Flutter (Channel stable, 3.7.3, on Microsoft Windows [Versi¢n 10.0.19045.2486], locale es-ES)
    • Flutter version 3.7.3 on channel stable at c:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9944297138 (8 days ago), 2023-02-08 15:46:04 -0800
    • Engine revision 248290d6d5
    • Dart version 2.19.2
    • DevTools version 2.20.1

[X] Windows Version (Unable to confirm if installed Windows version is 10 or greater)

[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at C:\Users\danij\AppData\Local\Android\sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Users\danij\AppData\Local\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual�Studio Community 2022 17.2.6)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual�Studio Community 2022 version 17.2.32630.192
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] VS Code (version 1.74.3)
    • VS Code at C:\Users\danij\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (4 available)
    • M2012K11AG (mobile) • 48d2360f • android-arm64  • Android 12 (API 31)
    • Windows (desktop)   • windows  • windows-x64    • Microsoft Windows [Versi¢n 10.0.19045.2486]
    • Chrome (web)        • chrome   • web-javascript • Google Chrome 110.0.5481.96
    • Edge (web)          • edge     • web-javascript • Microsoft Edge 109.0.1518.70

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

**Comment by danijorda1** [comment]
Code sample no third parties:

import 'package:flutter/material.dart';
import 'package:sliver_header_delegate/sliver_header_delegate.dart';


class test extends StatefulWidget {
  const test({Key? key}) : super(key: key);

  @override
  State<test> createState() => _test();
}

class _test extends State<test> with TickerProviderStateMixin {



  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body:
              NestedScrollView(

                  physics: ClampingScrollPhysics(),
                  headerSliverBuilder: (BuildContext context, bool innerBoxIsScrolled) {
                    return [
                      SliverPersistentHeader(
                        pinned: false,
                        floating: false,
                        delegate: FlexibleHeaderDelegate(
                          expandedHeight: 280,
                          collapsedHeight: 0,
                          children: [
                                                Container(height: 100,color: Colors.blueGrey,child:
                                                InkWell(
                                                  onTap: (){ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text("DO SOMETHING!!"),));},
                                                  child:Center(child: Text("Top")),)//MyTopWidget(),
                                                )
                          ]
                        ),
                      ),
                      SliverOverlapAbsorber(
                        handle:NestedScrollView.sliverOverlapAbsorberHandleFor(context),
                        sliver: SliverPersistentHeader(
                          pinned: true,
                          delegate: FlexibleHeaderDelegate(
                            expandedHeight: 189,
                            collapsedElevation: 0,
                            collapsedHeight: 189,
                            backgroundColor: Color(0xfff8f8f8),
                            children: [
                              Container(height: 100,color: Colors.green,child:InkWell(
                                onTap: (){ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text("DO SOMETHING HERE TOO!!"),));},
                                child:Center(child: Text("Middle")),)//MyTMiddleWidget(),
                              )
                            ],
                          ),
                        ),
                      ),
                    ];
                  },
                  body: Container(height: 100,color: Colors.lightGreenAccent,child: Center(child: Text("Body"),),)//ListView.builder(
                   // ....
                 // )
              )
    );


}}

**Comment by huycozy** [comment]
@danijorda1 Your code sample above is still using [sliver_header_delegate](https://pub.dev/packages/sliver_header_delegate) which is a 3rd party package. Please update it without using 3rd package.
