### ISSUE TITLE
TimeOutException. On the emulator, it turns out to upload a photo, but not on the real one

### ISSUE THREAD

**Issue by Soliardi-Chyngyz** [flutter/flutter#120713]
The following happens, I call the pick Image (gallery) method, a gallery appears, but the image of the pictures is not visible, while the files themselves are visible. Then I follow the standard procedure and upload it to the server, the server cannot process the data and as a result I get a time out exception.
Maybe something related is that the gallery does not display photos and the uploader does not work?

      String fName = params.requestModel.image.path.split('/').last;
      FormData formData = FormData.fromMap({
        'image': await MultipartFile.fromFile(params.requestModel.image.path,
            filename: fName, contentType: MediaType('image', 'jpeg')),
      });
      print(getFileSizeString(bytes: params.requestModel.image.lengthSync()));

      final response = await api.dio
          .post('${http...}upload/avatar',
              data: formData,
              options: Options(
                headers: {
                  'accept': '*/*',
                  'Content-Type': 'multipart/form-data',
                },
              ));

**Comment by darshankawar** [comment]
@Soliardi-Chyngyz 
Can you provide complete error log in properly formatted text along with `flutter doctor -v` ?

It seems you are using `dio` which is third party plugin. Please try with https://pub.dev/packages/http and see if you still get same behavior or not.

**Comment by Soliardi-Chyngyz** [comment]
@darshankawar thank you
we've found issue

Wrong file service setup on our backend server

**Comment by darshankawar** [comment]
Closing as not a flutter issue.
