### ISSUE TITLE
EngineBuildV2 Linux linux_host_engine not running dart tests

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#120701]
Linux linux_host_engine is running engine tests but not dart tests.

**Comment by godofredoc** [comment]
\cc @zanderso

**Comment by zanderso** [comment]
How did you find this? What do I need to look over to verify that we aren't dropping anything else?

**Comment by godofredoc** [comment]
I found it because the GN artifacts in the old recipe were failing to find the dart binary while engine v2 was passing correctly. As part of the migration we'll be finding these issues but we need to come up with an strategy to avoid new changes landing only on the legacy recipes version.

**Comment by zanderso** [comment]
> we need to come up with an strategy to avoid new changes landing only on the legacy recipes version.

I think that's true, but I'm not sure that's what happened in this instance. `Linux Host Engine` has been running the `dart` tests since May of last year at least.

**Comment by godofredoc** [comment]
Took a look and it seems like a problem on how I've been creating/updating the configuration files. I created the initial version on `2022-03-03` which included the initial gn+ninja commands and tests. My recent updates have been more focused on the artifacts.

I can add temp functionality to log test commands and compare during the migration of the builders.
