### ISSUE TITLE
[go_router] Push `ShellRoute` from inside of other `ShellRoute`

### ISSUE THREAD

**Issue by vasilich6107** [flutter/flutter#120791]
## Use case
In `ShellRoute` example we have a [`/b/details`](https://github.com/flutter/packages/blob/main/packages/go_router/example/lib/shell_route.dart#L71) as a route that we are [pushing](https://github.com/flutter/packages/blob/main/packages/go_router/example/lib/shell_route.dart#L225) to the root stack.

I tried my best but I failed to create a working solution to push shell route instead of `/b/details`.
Lets imagine the we are replacing 
```dart
GoRoute(
  path: 'details',
  parentNavigatorKey: _rootNavigatorKey,
  builder: (BuildContext context, GoRouterState state) {
    return const DetailsScreen(label: 'B');
  },
),
```

with 

```dart
ShellRoute(
  builder: (_, __, child) {
    // fancy container with red border for demo purposes
    return Container(child: child);
  },
  routes: [
    GoRoute(
      path: 'details',
      // parentNavigatorKey: _rootNavigatorKey,
      builder: (BuildContext context, GoRouterState state) {
        return const DetailsScreen(label: 'B');
      },
    ),
  ],
)
```

In this case `parentNavigatorKey: _rootNavigatorKey` fails with error 
```
Failed assertion: line 431 pos 16: 'route.parentNavigatorKey == null || route.parentNavigatorKey == navigatorKey': is not true.
```

If i comment out the `parentNavigatorKey: _rootNavigatorKey,` I'm unable to push this `ShellRoute` block into `_rootNavigatorKey`.

## Proposal
Please implement the ability to push arbitrary `ShellRoute` into root stack in the same way as `GoRoute` can target any stack it would be great to give the same `parentNavigatorKey` option to `ShellRoute`

**Comment by darshankawar** [comment]
Thanks for the report @vasilich6107 
Please check if [this](https://github.com/flutter/flutter/issues/117154#issuecomment-1363412510) comment / solution helps in your case.

**Comment by MichaelPriebe** [comment]
I am wanting the same thing, parentNavigatorKey on ShellRoute. You can see at the end, the ShellRoute on top of the ShellRoute gets pushed to the shell navigator, causing it to split into fourths.

https://user-images.githubusercontent.com/5238952/219457160-00e669a9-fd4c-4dfb-9c88-512944981a71.mp4

**Comment by rimidalv** [comment]
It is very Important for modern app that can change their size

**Comment by aaumond** [comment]
@MichaelPriebe Was the application you show in the video made with GoRouter navigation?
I'm trying to do navigation using the same principle as you, i.e. :
- If the screen is wide, open the new page in full screen mode.
- If the screen is small, open the new page on the right-hand side of the screen, bearing in mind that the left-hand side is shared between my different pages.

How did you do it?

**Comment by MichaelPriebe** [comment]
@aaumond 
It was with a custom route where I forcefully removed the barrier, and added my own overlay entry. It pushes the content to the side if large enough and allows pointer events through to the route below it.

It is somewhat inefficient, because when you are in the small version, stuff below is still rendering, so just be aware.

I feel like there should be a built in function in Flutter to push to the secondary side of a screen, which will look the same as the normal push, but to do all this logic when the screen is either big enough or has dual/folding breakpoint.

```dart
import 'package:flutter/material.dart';
import 'package:flutter_adaptive_scaffold/flutter_adaptive_scaffold.dart';

class AdaptivePage<T> extends MaterialPage<T> {
  const AdaptivePage({
    required super.child,
    super.key,
  });

  @override
  Route<T> createRoute(BuildContext context) => _AdaptiveRoute(this);
}

class _AdaptiveRoute<T> extends PageRoute<T> with MaterialRouteTransitionMixin {
  final AdaptivePage<T> _page;

  _AdaptiveRoute(this._page) : super(settings: _page);

  @override
  Widget buildContent(BuildContext context) => _page.child;

  @override
  bool get maintainState => _page.maintainState;

  // Keeps the route below loaded
  @override
  bool get opaque => false;

  // Stops the route below it from animating
  @override
  bool get fullscreenDialog => true;

  // Remove barrier color
  @override
  Color? get barrierColor => null;

  // Remove barrier
  @override
  Iterable<OverlayEntry> createOverlayEntries() {
    final entries = super.createOverlayEntries();
    final last = entries.last;
    return [
      OverlayEntry(
        builder: (context) => AdaptiveLayout(
          internalAnimations: false,
          body: SlotLayout(
            config: {
              Breakpoints.standard: SlotLayout.from(
                key: ValueKey(this),
                builder: last.builder,
              ),
              Breakpoints.large: SlotLayout.from(
                key: const Key('IgnorePointer'),
                builder: (context) => const IgnorePointer(),
              ),
            },
          ),
          secondaryBody: SlotLayout(
            config: {
              Breakpoints.large: SlotLayout.from(
                key: ValueKey(this),
                builder: (context) {
                  return last.builder(context);
                },
              ),
            },
          ),
        ),
        maintainState: last.maintainState,
      ),
    ];
  }
}
```

```dart
import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import 'package:nexus/router/adaptive_page.dart';

class AdaptiveRoute extends GoRoute {
  AdaptiveRoute({
    required super.path,
    super.name,
    required GoRouterWidgetBuilder builder,
    super.routes,
  }) : super(
          pageBuilder: (context, state) => AdaptivePage(
            child: builder(context, state),
            key: ValueKey(path),
          ),
        );
}
```
