### ISSUE TITLE
Provide a way to get a bitmap representation of a widget tree

### ISSUE THREAD

**Issue by steeeep34** [flutter/flutter#120723]
## Use case

My app allows to edit widget trees which at the root are Screen() widgets.

I need to show a list of shrinked down Screen() widgets, so the user can select another Screen() for further editing.

I'm aware of Transform.scale(). Unfortunately, this methods shrinks the widget tree. A scale operation to say 80x60 doesn't render anything useful of a normal Flutter UI.

I'm in need of a method that renders e.g. a 800x600 Container, which includes in my case the Screen(), and after that shrinks down to a 80x60 Container to be show in the Screen()s Palette.

In general for any preview feature, a bitmap capture and scale operation would be helpful.

## Proposal

Suchlike methods would be helpful:

// returns a bitmap of the rendered widget tree
`Transform.asBitmap( Widget child )` 

// captures a bitmap of the rendered widget tree and scales down
`Transform.AsBitmapScaled( double width, double height, bool respectAspectRatio, Widget child ) `

**Comment by huycozy** [comment]
>I'm in need of a method that renders e.g. a 800x600 Container, which includes in my case the Screen(), and after that shrinks down to a 80x60 Container to be show in the Screen()s Palette.

@steeeep34 Can you please be more specific about this? Is it the same as Print Preview?

**Comment by steeeep34** [comment]
Hm, not sure how I may be more specific...

I'd like to do something like this in a build(context):

// Renders theToBePreviewedWidgte() within an 800x600 container (the intended size for later use of the image

// prepares an image and scales it down to 800x600
var previewImage = Image( 
 image: WidgetAsImage(
   width: 80,
   heißt: 80,
    child: Container(
      width: 800,
      height: 800,
      child: theToBePreviewedWidgte()
    )
))

**Comment by steeeep34** [comment]
> > I'm in need of a method that renders e.g. a 800x600 Container, which includes in my case the Screen(), and after that shrinks down to a 80x60 Container to be show in the Screen()s Palette.
> 
> @steeeep34 Can you please be more specific about this? Is it the same as Print Preview?

Do you mean the [printing package](https://pub.dev/packages/printing)?

**Comment by huycozy** [comment]
I think it's applicable to use `RenderRepaintBoundary` for solving your issue. Also, you may try finding a package on pub.dev instead if any. 

I'll be closing the issue as solved yourself. Once it's impossible and you go back with the original proposal for `Transform`, please write a comment and I will re-open the issue for further discussion.

Thank you!

**Comment by steeeep34** [comment]
OK. Just found [widgets_to_image](https://pub.dev/packages/widgets_to_image), which might do the trick.
