### ISSUE TITLE
[camerax] Implement flash mode configuration

### ISSUE THREAD

**Issue by camsim99** [flutter/flutter#120715]
In the camera plugin API, the method `Future<void> setFlashMode(int cameraId, FlashMode mode)` is used to configure the flash mode for taking pictures and recording video. This method needs to be implemented in the CameraX plugin.

For more information on how flash mode configuration works in CameraX, see [guide](https://developer.android.com/training/camerax/configuration#torch).

**Comment by FXschwartz** [comment]
@camsim99 I'd like to contribute to this one, but I see there is an ongoing project with this feature. Should we hold off until the rewrite is complete? Or is it in a stable enough place that I can create a PR?

**Comment by camsim99** [comment]
@FXschwartz I think we should hold off until the plugin is at least a little more stable and the primary use cases have been implemented. I can update this issue when it is at that point!

**Comment by camsim99** [comment]
@FXschwartz  Just FYI, I am working on a PR to implement all of the camera modes except torch mode. It's one I started a while ago because I wanted to land it on a tight timeline, but I didn't end up finishing. After that lands, we'll still need to implement support for torch mode. I am looking to confine work on that to the quarter, but if you want to work on that part, let me know!
