### ISSUE TITLE
[tool_crash] ShaderCompilerException: Shader compilation - Could not write file to build\unit_test_assets\shaders/ink_sparkle.frag.spirv

### ISSUE THREAD

**Issue by AbedSameer** [flutter/flutter#120757]
## command

flutter test

## exception

ShaderCompilerException: ShaderCompilerException: Shader compilation of "C:\flutter\packages\flutter\lib\src\material\shaders\ink_sparkle.frag" to "build\unit_test_assets\shaders/ink_sparkle.frag" failed with exit code 1.
impellerc stdout:

impellerc stderr:
Could not write file to build\unit_test_assets\shaders/ink_sparkle.frag.spirv

```
#0      ShaderCompiler.compileShader (package:flutter_tools/src/build_system/targets/shader_compiler.dart:202:9)
<asynchronous suspension>
#1      writeBundle.<anonymous closure> (package:flutter_tools/src/bundle_builder.dart:185:25)
<asynchronous suspension>
#2      Future.wait.<anonymous closure> (dart:async/future.dart:522:21)
<asynchronous suspension>
#3      writeBundle (package:flutter_tools/src/bundle_builder.dart:163:3)
<asynchronous suspension>
#4      TestCommand._buildTestAsset (package:flutter_tools/src/commands/test.dart:502:7)
<asynchronous suspension>
#5      TestCommand.runCommand (package:flutter_tools/src/commands/test.dart:329:7)
<asynchronous suspension>
#6      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1257:27)
<asynchronous suspension>
#7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#8      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#9      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:283:9)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#11     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
<asynchronous suspension>
#12     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#14     main (package:flutter_tools/executable.dart:91:3)
<asynchronous suspension>
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel stable, 3.7.3, on Microsoft Windows [Version 10.0.22621.1105], locale ar-JO)
    [32m•[39m Flutter version 3.7.3 on channel stable at C:\flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision 9944297138 (6 days ago), 2023-02-08 15:46:04 -0800
    [32m•[39m Engine revision 248290d6d5
    [32m•[39m Dart version 2.19.2
    [32m•[39m DevTools version 2.20.1

[32m[✓][39m Windows Version (Installed version of Windows is version 10 or higher)

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    [32m•[39m Android SDK at C:\Users\Abed-Sammer\AppData\Local\Android\sdk
    [32m•[39m Platform android-33, build-tools 32.0.0
    [32m•[39m Java binary at: F:\AS\jre\bin\java
    [32m•[39m Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[31m[✗][39m Visual Studio - develop for Windows
    [31m✗[39m Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[32m[✓][39m Android Studio (version 2021.3)
    [32m•[39m Android Studio at F:\AS
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[32m[✓][39m Connected device (4 available)
    [32m•[39m SM A325F (mobile) • RZ8T801SP5Z • android-arm64  • Android 13 (API 33)
    [32m•[39m Windows (desktop) • windows     • windows-x64    • Microsoft Windows [Version 10.0.22621.1105]
    [32m•[39m Chrome (web)      • chrome      • web-javascript • Google Chrome 109.0.5414.75
    [32m•[39m Edge (web)        • edge        • web-javascript • Microsoft Edge 110.0.1587.41

[32m[✓][39m HTTP Host Availability
    [32m•[39m All required HTTP hosts are available

[33m![39m Doctor found issues in 1 category.
```

**Comment by huycozy** [comment]
@AbedSameer Thanks for the report.
I can see you have this error when performing the test command. Does the same issue happen when running the project? 

Also, can you try running on the latest master channel and check if the issue still occurs or not?
```
flutter channel master
flutter upgrade
```

**Comment by AbedSameer** [comment]
that no work ,but get new error

Downloading android-arm-profile/windows-x64 tools...
Downloading android-arm-release/windows-x64 tools...
Downloading android-arm64-profile/windows-x64 tools...
Downloading android-arm64-release/windows-x64 tools...
Downloading android-x64-profile/windows-x64 tools...
Downloading android-x64-release/windows-x64 tools...
Launching lib\main.dart on SM A325F in debug mode...
Could not write file to D:\MegaFiles\Code\tahfeez-app\my_app\build\app\intermediates\flutter\debug\flutter_assets\shaders/ink_sparkle.frag.spirv

Target debug_android_application failed: ShaderCompilerException: Shader compilation of "C:\flutter\packages\flutter\lib\src\material\shaders\ink_sparkle.frag" to "D:\MegaFiles\Code\tahfeez-app\my_app\build\app\intermediates\flutter\debug\flutter_assets\shaders/ink_sparkle.frag" failed with exit code 1.
impellerc stdout:

impellerc stderr:
Could not write file to D:\MegaFiles\Code\tahfeez-app\my_app\build\app\intermediates\flutter\debug\flutter_assets\shaders/ink_sparkle.frag.spirv



FAILURE: Build failed with an exception.

* Where:
Script 'C:\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1154

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org
BUILD FAILED in 4m 26s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

**Comment by huycozy** [comment]
Thanks for the information. 

>Could not write file to D:\MegaFiles\Code\tahfeez-app\my_app\build\app\intermediates\flutter\debug\flutter_assets\shaders/ink_sparkle.frag.spirv

It could be related to permission issue. Labeling the issue for further insights. 

May be similar/duplicated of #116703 and #120684 (being in triage).
/cc @christopherfujino for thoughts

**Comment by AbedSameer** [comment]
I think the processor has a role in this data

OS Name:                   Microsoft Windows 11 Pro
OS Version:                10.0.22621 N/A Build 22621
Processor:                  AMD64 Family 23 Model 96 Stepping 1 AuthenticAMD ~1400 Mhz

**Comment by AbedSameer** [comment]
please take in mind this mistake in last slash (/)

D:\MegaFiles\Code\tahfeez-app\my_app\build\app\intermediates\flutter\debug\flutter_assets\shaders/ink_sparkle.frag.spirv
                                                                                                                                                       ----------^

it's different, looks like Linux sentences

**Comment by AbedSameer** [comment]
problem solved. 

![image](https://user-images.githubusercontent.com/68728874/219362668-571ab024-321c-4836-bfc7-5df254a4fd98.png)

Before some days I activated " Ransomware protection " in Windows 11, So Flutter and Gradle don't have access to project file to edit or create files.

you must turn this off, then clean and run your project

**Comment by christopherfujino** [comment]
> problem solved.
> 
> ![image](https://user-images.githubusercontent.com/68728874/219362668-571ab024-321c-4836-bfc7-5df254a4fd98.png)
> 
> Before some days I activated " Ransomware protection " in Windows 11, So Flutter and Gradle don't have access to project file to edit or create files.
> 
> you must turn this off, then clean and run your project

Thanks for following up. Related: https://github.com/flutter/flutter/issues/61997
