### ISSUE TITLE
Expose Platform Channels through the flutter/engine embedder api

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#12088]
My understanding is @chinmaygarde had started this work but was interrupted before he could finish.

The request is to expose platform channel functionality through:
https://github.com/flutter/engine/blob/master/shell/platform/embedder/embedder.h

So that embedders which wish to use plugins can do so.

**Comment by chinmaygarde** [comment]
This has [been implemented](https://github.com/flutter/engine/blob/7f676451ae69031ed4487187e7402706f8e0b5eb/shell/platform/embedder/embedder.h#L126). Closing.
