### ISSUE TITLE
flutter sdk 2.5.3,on ios,scrollbar contain textfield,scrollbar will move to top instead of origin right position when lose focus

### ISSUE THREAD

**Issue by lly7690** [flutter/flutter#120851]
<img width="380" alt="image" src="https://user-images.githubusercontent.com/17976067/219256913-11817b62-1374-421e-b87b-c44f7edb042d.png">
<img width="374" alt="image" src="https://user-images.githubusercontent.com/17976067/219256936-44659286-45f1-4c5e-a0ee-583499f405bc.png">
flutter sdk 2.5.3,on ios,scrollbar contain textfield,scrollbar will move to top instead of origin right position when lose focus

**Comment by darshankawar** [comment]
@lly7690 
The version you are on is very old. Current sdk version is 3.7.3. I recommend to upgrade to latest stable version and run your scenario again to see if you still get the same behavior or not. 
Closing for now, as the version you are seeing the reported behavior is old. If on latest version, you are seeing same behavior, write in comments and I'll reopen it.
