### ISSUE TITLE
(Flutter 3.3.7) when pubspec.yaml version up, cocoapods dead.

### ISSUE THREAD

**Issue by chlguswns980105** [flutter/flutter#120858]
This is a very frequent phenomenon.
I would like to know the exact cause.

## Steps to Reproduce

1. pubspec.yaml version up (3.2.3+50 => 3.2.4+51)
2. Run Without Debugging

## Env
macOS 13.0.1
vscode 1.75.1
iphone X

## Logs

```
Warning: CocoaPods not installed. Skipping pod install.
  CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
  Without CocoaPods, plugins will not work on iOS or macOS.
  For more info, see https://flutter.dev/platform-plugins
To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

Exception: CocoaPods not installed or not in valid state.
```

<details>
<summary> flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.3.7, on macOS 13.0.1 22A400 darwin-arm, locale
    ko-KR)
    • Flutter version 3.3.7 on channel stable at /Users/choihyeonjun/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e99c9c7cd9 (4 months ago), 2022-11-01 16:59:00 -0700
    • Engine revision 857bd6b74c
    • Dart version 2.18.4
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/choihyeonjun/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.75.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.58.0

[✓] Connected device (4 available)
    • LM V510N (mobile) • ---                          • android-arm64  • Android 12 (API 31)
    • iPhone (mobile)   • --- • ios            • iOS 16.1.1 20B101
    • macOS (desktop)   • macos                                    • darwin-arm64   • macOS 13.0.1 22A400 darwin-arm
    • Chrome (web)      • chrome                                   • web-javascript • Google Chrome 110.0.5481.100

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by danagbemava-nc** [comment]
Hi @chlguswns980105, you are on an older version of flutter. Kindly upgrade to the latest version of flutter stable (3.7.3) to see if you still experience this issue. If you do, please provide the updated output of `flutter doctor -v`.

**Comment by chlguswns980105** [comment]
@danagbemava-nc 
our project team manager don't wanna upgrade to new version.
can I find root of the problem with 3.3.7?
If an answer is not possible, I will close it.

**Comment by huycozy** [comment]
@chlguswns980105 I try to reproduce this issue from my end but it doesn't happen. After increasing the version in `pubspec.yaml`, and run it on iPhone, it runs normally without warning/exception log above. 

It seems something goes wrong in your local cocoapods setup. 
Which IDE are you running the project on? Does the issue happen again even after restart or clear IDE cache? (https://github.com/flutter/flutter/issues/54962#issuecomment-671009062)

Please check and try [this](https://github.com/flutter/flutter/issues/57433#issuecomment-640095378) if it works for you. 

You may also check [CocoaPods's own installation instructions](https://guides.cocoapods.org/using/getting-started.html#installation) and find out if you miss any steps there.

**Comment by chlguswns980105** [comment]
@huycozy 

1. Which IDE are you running the project on?
- vscode 1.75.1

2. Does the issue happen again even after restart or clear IDE cache?
- yes.

3. Please check and try https://github.com/flutter/flutter/issues/57433#issuecomment-640095378 if it works for you.
- In case of problems, I always try.

4. You may also check [CocoaPods's own installation instructions](https://guides.cocoapods.org/using/getting-started.html#installation) and find out if you miss any steps there.
- I'll close this issue first, and follow the instructions in #4 in the event of a problem later.
- Repeated reinstallation may cause it to run.
