### ISSUE TITLE
Flutter nested component taping issue on perfecto automation tool for ios 16 build

### ISSUE THREAD

**Issue by skghosh123** [flutter/flutter#120859]
I use flutter nested widget but while testing for perfecto automation on iOS 16 devices, tapping the screen, it is marked as a whole container not able to identify child widget. 
Here is some code sample
Container( 
       child: Column(
          children: [
            Container( 
             width: 100, 
             height: 100,
             child: Image.asset(
             'assets/images/lake.jpg',                
             fit: BoxFit.cover,              
            ),),
            Container(
              width: 100,
              height: 100,
              child: Image.asset(
                'assets/images/lake.jpg',
                fit: BoxFit.cover,
              ), 
           ),
            Container( 
             width: 100, 
             height: 100,
              child: Image.asset(
                'assets/images/lake.jpg', 
               fit: BoxFit.cover, 
             ), 
           ), 
           Container(
              width: 100, 
             height: 100,
              child: Image.asset( 
               'assets/images/lake.jpg',
                fit: BoxFit.cover, 
             ),          
           ),          
         ],       
       ),      
      ),

**Comment by exaby73** [comment]
Hello @skghosh123. Looks like an issue with Perfecto, and not with Flutter. I suggest you raise the issue with Perfecto. Closing as this does not seem like an issue with Flutter itself. Thank you
