### ISSUE TITLE
Double stacked material scaffolds shouldn't double resizeToAvoidBottomPadding

### ISSUE THREAD

**Issue by xster** [flutter/flutter#12084]
From https://groups.google.com/forum/?utm_source=digest&utm_medium=email#!topic/flutter-dev/pLub7dov2ag

With 2 layers of Scaffolds, it's possible for the resizeToAvoidBottomPadding to produce 2 paddings with the height of the on-screen keyboard. 

We should somehow avoid more than 1 padding to avoid the keyboard.

**Comment by Hixie** [comment]
We probably need to have the body of the media query provide an adjusted MediaQuery that hides the top and bottom padding when appropriate.

**Comment by d-silveira** [comment]
I confirm this, I've also hit this issue, 
not knowing where to look, It took me a long time until I ran into this ticket, which finally explained what was going on and how to work around it!

I would like to ask you to please either prioritize this, or document it visibly in the docs!
Thank you so much for your hard work, on making flutter the best mobile framework available!

**Comment by Hixie** [comment]
cc @cbracken
