### ISSUE TITLE
Bug in the Map class

### ISSUE THREAD

**Issue by jerrymfon14** [flutter/flutter#120831]
Whenever i tried to update a growable list on a map or even add a new list to a map it updates all entries.

void main(){
  List myList = [1,2,3,4,5,6,7,8,9,0,88];
  
  List tempList = [];
  Map map ={};
  
  for(int i=0; i<myList.length; i++){
    tempList.add(myList[i]);
    if(i%2 == 0){
      
      map[i.toString()] = tempList;
      print(map);
      tempList.clear();
    }
    
  }
  

  
}

**Comment by yanncabral** [comment]
Hi! It's just cause you're pointing to the same `tempList` reference. In your case, you can just create different references for each map key.

```dart
void main(){
  List myList = [1,2,3,4,5,6,7,8,9,0,88];

  List tempList = [];
  Map map = {};

  for(int i=0; i<myList.length; i++) {
    tempList.add(myList[i]);
    if(i % 2 == 0) {
      map[i.toString()] = List.from(tempList);
      print(map);
      tempList.clear();
    }
  }
}
```

**Comment by stuartmorgan** [comment]
For help with your own code, consider trying one of the resources listed at https://flutter.dev/community#community-grid

Closing as this is bug in the code sample, not in Flutter.
