### ISSUE TITLE
SystemChrome.setPreferredOrientations issues on Flutter 3.7

### ISSUE THREAD

**Issue by BetterB0y** [flutter/flutter#120875]
Tested on iPhone 13. Problem exists only on iOS.

I'm using before application starts
    SystemChrome.setPreferredOrientations([
      DeviceOrientation.portraitUp,
    ]);
    
I have one screen that in init method have:

    SystemChrome.setPreferredOrientations([
      DeviceOrientation.portraitUp,
      DeviceOrientation.landscapeLeft,
      DeviceOrientation.landscapeRight,
    ]);
    
    
I checked. In update from flutter 3.4.10 to 3.7.0 there is an issue with changing orientations. Newest version 3.7.3 still has got an issue. Where it should be blocked it tries to rotate and revert change to portraitUp. But then in screen where i want also landscape its not working, it stays in portraitUp.

**Comment by BetterB0y** [comment]
I see that on master it's working correctly. Can I ask what are the chances that it will be in next 3.7.? release?

**Comment by BetterB0y** [comment]
This is duplicated with #116711

**Comment by darshankawar** [comment]
@BetterB0y 
Thanks for the update. A stable version is released once in a quarter so the fix should be available in next stable release. 
Closing from here since this is already fixed and working on master.

**Comment by BetterB0y** [comment]
@darshankawar There is no chance to release this fix as 3.7.4?

**Comment by darshankawar** [comment]
@BetterB0y 
There's a cherry-pick [template](https://github.com/flutter/flutter/issues/new?assignees=&labels=cp%3A+review&template=7_cherry_pick.yml&title=%5BCP%5D+%3Ctitle%3E) to request changes to be hotfixed in stable, but for that you'll need to know which commit fix might have fixed the issue and most importantly not all fixes are cherry-picked. If there are more pressing issues or crashes, then they are ideal candidates for hot-fixes.
