### ISSUE TITLE
[tool_crash] ProcessException: Process exited abnormally: Command: xcrun, OS error code: -4

### ISSUE THREAD

**Issue by zhangdong** [flutter/flutter#120863]
## Command
```
flutter build ipa --export-options-plist ios_options.plist --dart-define FLUTTER_BUILD_NAME=1.0.0 --dart-define FLUTTER_BUILD_NUMBER=2
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ProcessException: Process exited abnormally:
 Command: xcrun, OS error code: -4
```
#0      RunResult.throwException (package:flutter_tools/src/base/process.dart:126:5)
#1      _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart:279:19)
<asynchronous suspension>
#2      XcodeProjectInterpreter.getInfo (package:flutter_tools/src/ios/xcodeproj.dart:321:30)
<asynchronous suspension>
#3      IosProject.projectInfo (package:flutter_tools/src/xcode_project.dart:318:29)
<asynchronous suspension>
#4      IosProject.buildSettingsForBuildInfo (package:flutter_tools/src/xcode_project.dart:278:36)
<asynchronous suspension>
#5      IosProject._parseHostAppBundleName (package:flutter_tools/src/xcode_project.dart:254:55)
<asynchronous suspension>
#6      IosProject.hostAppBundleName (package:flutter_tools/src/xcode_project.dart:243:35)
<asynchronous suspension>
#7      BuildableIOSApp.fromProject (package:flutter_tools/src/ios/application_package.dart:116:39)
<asynchronous suspension>
#8      FlutterApplicationPackageFactory.getPackageForPlatform (package:flutter_tools/src/flutter_application_package.dart:82:15)
<asynchronous suspension>
#9      _BuildIOSSubCommand.buildableIOSApp.<anonymous closure> (package:flutter_tools/src/commands/build_ios.dart:467:34)
<asynchronous suspension>
#10     _BuildIOSSubCommand.runCommand (package:flutter_tools/src/commands/build_ios.dart:504:33)
<asynchronous suspension>
#11     BuildIOSArchiveCommand.runCommand (package:flutter_tools/src/commands/build_ios.dart:295:50)
<asynchronous suspension>
#12     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1257:27)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 3.7.3, on macOS 13.2 22D49 darwin-x64, locale zh-Hans-CN)
    • Flutter version 3.7.3 on channel stable at /Users/ccMoving/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9944297138 (7 days ago), 2023-02-08 15:46:04 -0800
    • Engine revision 248290d6d5
    • Dart version 2.19.2
    • DevTools version 2.20.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/ccMoving/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • ANDROID_HOME = /Users/ccMoving/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.75.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.58.0

[✓] Connected device (4 available)
    • 22081212C (mobile)         • 370c298d                             • android-arm64  • Android 13 (API 33)
    • iPhone 14 Pro Max (mobile) • 38EADD9E-C7DC-4570-9F8A-3B5F91E6C6B7 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-2 (simulator)
    • macOS (desktop)            • macos                                • darwin-x64     • macOS 13.2 22D49 darwin-x64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 108.0.5359.124

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+2
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 135454af32477f815a7525073027a3ff9eff1bfd
### Plugins
audioplayers-3.0.1
audioplayers_android-2.0.0
audioplayers_darwin-3.0.1
audioplayers_linux-1.0.4
audioplayers_web-2.2.0
audioplayers_windows-1.1.3
camera-0.10.3
camera_android-0.10.4
camera_avfoundation-0.9.11
camera_web-0.3.1+1
disk_space-0.2.1
file_picker-4.6.1
flutter_aliplayer
flutter_bugly-0.4.4
flutter_image_compress-1.1.3
flutter_inappwebview-6.0.0-beta.22
flutter_native_splash-2.2.17
flutter_plugin_android_lifecycle-2.0.7
flutter_plugin_record_plus-0.0.15
flutter_xupdate-2.0.3
image_gallery_saver-1.7.1
image_picker-0.8.6+1
image_picker_android-0.8.5+6
image_picker_for_web-2.1.10
image_picker_ios-0.8.6+7
jitsi_meet_wrapper-0.0.6
jpush_flutter-2.4.1
location-4.4.0
location_web-3.1.1
package_info_plus-1.4.2
package_info_plus_linux-1.0.5
package_info_plus_macos-1.3.0
package_info_plus_web-1.0.6
package_info_plus_windows-1.0.5
path_provider-2.0.12
path_provider_android-2.0.22
path_provider_foundation-2.1.1
path_provider_linux-2.1.8
path_provider_windows-2.0.7
permission_handler-10.2.0
permission_handler_android-10.2.0
permission_handler_apple-9.0.7
permission_handler_windows-0.1.2
photo_manager-2.5.2
record-4.4.4
record_linux-0.4.1
record_macos-0.2.2
record_web-0.5.0
record_windows-0.7.1
shared_preferences-2.0.17
shared_preferences_android-2.0.15
shared_preferences_foundation-2.1.3
shared_preferences_linux-2.1.3
shared_preferences_web-2.0.4
shared_preferences_windows-2.1.3
sqflite-2.2.4+1
tencent_cloud_chat_sdk-5.0.8
tencent_open_file-4.0.9+1
url_launcher-6.1.9
url_launcher_android-6.0.23
url_launcher_ios-6.1.0
url_launcher_linux-3.0.2
url_launcher_macos-3.0.2
url_launcher_web-2.0.14
url_launcher_windows-3.0.3
video_player-2.5.1
video_player_android-2.3.10
video_player_avfoundation-2.3.8
video_player_web-2.0.13
video_thumbnail-0.5.3
wakelock-0.6.2
wakelock_macos-0.4.0
wakelock_web-0.4.0

**Comment by danagbemava-nc** [comment]
Hi @zhangdong, please provide the full verbose output of 
`flutter build ipa --export-options-plist ios_options.plist --dart-define FLUTTER_BUILD_NAME=1.0.0 --dart-define FLUTTER_BUILD_NUMBER=2 -v`

The output may be huge so kindly put it into a .txt/.log file and attach it here. 

Thank you

**Comment by zhangdong** [comment]
> 

thanks for your answer. it's a miraculous thing, when I use iTerm to run this command it works!!!
and I use VSCode terminal, it will report errors above.
 sorry for my bad english. Hope U can understand what i say.

**Comment by huycozy** [comment]
@zhangdong Can you please provide the complete output of the build command (verbose `-v`) as @danagbemava-nc  mentioned above so that we may investigate the issue?
