### ISSUE TITLE
What Is this Problem?

### ISSUE THREAD

**Issue by nirajann** [flutter/flutter#120884]
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by opxdelwin** [comment]
Please provide adequate details of your issue.
