### ISSUE TITLE
Edit-refresh development hangs in Xcode 9 simulators

### ISSUE THREAD

**Issue by cbracken** [flutter/flutter#12085]
## Steps to Reproduce

In a flutter application directory:
1. Use `xcode-select` to select Xcode 9.
1. Launch an Xcode 9 simulator with iOS 11.
1. `flutter run`

Expected result: edit-refresh development works as usual.
Actual result: hang waiting for observatory.

`flutter_tools` currently tails the simulator device's syslog file, which as of iOS 11 no longer contains the flutter engine logs. These are, however, now available through `/usr/bin/log`.

## Flutter Doctor
```
[✓] Flutter (on Mac OS X 10.12.6 16G29, locale en-AU, channel master)
    • Flutter at /Users/cbracken/src/flutter/flutter
    • Framework revision fa0bcce708 (26 hours ago), 2017-09-12 16:11:43 -0700
    • Engine revision 31d03de019
    • Tools Dart version 1.25.0-dev.11.0

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at /Users/cbracken/Library/Android/sdk
    • Platform android-25, build-tools 25.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 9.0)
    • Xcode at /Applications/Xcode9.0.app/Contents/Developer
    • Xcode 9.0, Build version 9A235
    • ios-deploy 1.9.2
    • CocoaPods version 1.3.1

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.2.3)
    • Flutter plugin version 17.0
    • Dart plugin version 172.3968.27
```

**Comment by rmtmckenzie** [comment]
I raised this as #11945 but it seems like this is being handled here now; should I close my issue?

**Comment by cbracken** [comment]
@rmtmckenzie Apologies -- I completely missed yours. I'll close this as a dupe of #11945 and update the patch to refer to yours as the fixed issue. Thanks for filing!

btw definitely feel free to /cc @cbracken on any iOS-related issues, though tbh I should increase the frequency of my issue scans ;-)

**Comment by cbracken** [comment]
Also, great to see a fellow Victorian!

**Comment by rmtmckenzie** [comment]
@cbracken  Thanks =) will do if I come across anything else.
