### ISSUE TITLE
Khmer text is vertically misaligned with Latin text

### ISSUE THREAD

**Issue by brahimkh** [flutter/flutter#120862]
1. Execute `flutter run` on the code sample 
2. ```  Example: Row ( children:[Text('សួរស្ដី'),Text('brahim),]) ''```
![Simulator Screen Shot - iPhone 14 Pro Max - 2023-02-16 at 15 14 57](https://user-images.githubusercontent.com/87469140/219310756-90da6551-e48f-4842-b5c9-8954748b4c07.png)

4.  English small than khmer languages 

**Actual results:** 

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
<img width="959" alt="Screen Shot 2023-02-16 at 3 31 26 PM" src="https://user-images.githubusercontent.com/87469140/219310385-dccf1570-2ae4-4244-a481-53c26f202f34.png">

```

</details>

**Comment by huycozy** [comment]
Hi @brahimkh 
Do you mean the height of English text should be equal to Khmer text? If so, I don't think it's an issue since it works like iOS native text:

| Flutter | iOS |
| --------------- | --------------- |
<img width="400" src="https://user-images.githubusercontent.com/104349824/219341071-7d103b23-f5bf-4ecb-9a3c-ca77e784a2a1.png"> | <img width="400" src="https://user-images.githubusercontent.com/104349824/219341129-09b4b481-559d-4150-a5a5-38ef95b85122.png">

**Comment by brahimkh** [comment]
Thank for response
Yes, i mean so, Do you have solution for this an issue on flutter?

**Comment by huycozy** [comment]
Hi @brahimkh 
What I mean from my comment is Flutter is rendering the text similar to iOS native text. You can take a look at the screenshots (comparing Flutter and iOS native projects) to see this. So, it means that Flutter works as expected. 

Closing as above explanation. If you disagree, please write in the comments and I will reopen it.

**Comment by gnprice** [comment]
I think there actually is a valid issue shown in the screenshots above. It's not a difference in the height or size of the text, but rather in its alignment.

Taking the Flutter and iOS-native screenshots from https://github.com/flutter/flutter/issues/120862#issuecomment-1432872062 and focusing in on the text:
| Flutter | iOS |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/28173/222335647-4070ca29-1b00-448c-8671-58e42fd4b689.png) | ![image](https://user-images.githubusercontent.com/28173/222335679-0e0f6fb1-deb6-41ca-9638-4ead4b5a2520.png)|

In the iOS screenshot, the baseline of the Latin letters lines up nicely with the baseline of the Khmer letters. But in the Flutter screenshot, the baselines don't line up. The Khmer text sits higher than the Latin text, and the combination of them looks wrong.

The same thing is happening in the two highlighted boxes in the original screenshot.

**Comment by gnprice** [comment]
This issue looks similar to #27033, and especially to the iOS screenshot at https://github.com/flutter/flutter/issues/27033#issuecomment-1323553882 .

**Comment by brahimkh** [comment]
Thank @gnprice for details about this issue,i want also meaning

**Comment by gnprice** [comment]
Reopening because this is a valid issue.

It's possible it will turn out to be a duplicate of #27033, after some debugging is done on one or both of these issues to identify the cause. But I think that's not yet clear.

**Comment by chinmaygarde** [comment]
iOS and the browsers do it the same way. Flutter is different.

**Comment by huycozy** [comment]
>In the iOS screenshot, the baseline of the Latin letters lines up nicely with the baseline of the Khmer letters. But in the Flutter screenshot, the baselines don't line up. The Khmer text sits higher than the Latin text, and the combination of them looks wrong.

Thank @gnprice for noticing this. I re-test and confirm this issue is still reproducible on the stable and master channels. It also happens when enabling Impeller. Adding `flutter doctor -v` output and corresponding labels.

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.7.6, on macOS 13.0.1 22A400 darwin-x64, locale en-EE)
    • Flutter version 3.7.6 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 12cb4eb7a0 (4 days ago), 2023-03-01 10:29:26 -0800
    • Engine revision ada363ee93
    • Dart version 2.19.3
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio
    • Android Studio at /Applications/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.75.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.60.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 110.0.5481.177

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

```bash
[!] Flutter (Channel master, 3.9.0-1.0.pre.49, on macOS 13.0.1 22A400 darwin-x64, locale en-EE)
    • Flutter version 3.9.0-1.0.pre.49 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 95387c6621 (25 hours ago), 2023-03-04 16:59:14 -0800
    • Engine revision de724e2632
    • Dart version 3.0.0 (build 3.0.0-290.0.dev)
    • DevTools version 2.22.2
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio
    • Android Studio at /Applications/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.75.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.60.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 110.0.5481.177

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
```
</details>

**Comment by jonahwilliams** [comment]
FYI @rusino for potential SkParagraph bugs.

**Comment by jonahwilliams** [comment]
IIRC if there are two separate Text widgets that will lead to two separate dart:ui Paragraph objects.

**Comment by Rusino** [comment]
Exactly! For two different paragraphs the responsibility for positioning is on the owner of these paragraphs.
Nothing I can do inside Skia. (But I could help with finding the right way to position one paragraph against the other).

**Comment by jonahwilliams** [comment]
Thanks @Rusino , that makes sense. I'd defer to one of the framework experts (Maybe @justinmc  or @LongCatIsLooong ) on how the framework positions individual paragraphs.

**Comment by LongCatIsLooong** [comment]
The `Row` widget center aligns its children by default. Use [CrossAxisAlignment.baseline](https://main-api.flutter.dev/flutter/rendering/CrossAxisAlignment.html) if you want to baseline align the text widgets.

**Comment by huycozy** [comment]
I re-visited this and saw that the issue persists on iOS target platform with original sample code (without using `CrossAxisAlignment.baseline`):

![Simulator Screenshot - iPhone 15 Pro - 2024-02-15 at 10 50 12](https://github.com/flutter/flutter/assets/104349824/2d03f69e-8872-4370-b023-e6f362e9d92a)

But the baseline displays correctly when I apply `CrossAxisAlignment.baseline` to Row as @LongCatIsLooong mentioned:

![Simulator Screenshot - iPhone 15 Pro - 2024-02-15 at 10 58 24](https://github.com/flutter/flutter/assets/104349824/4d9529e4-3a41-4e82-ba2d-b93cbfed953f)

<details>
<summary>Sample code (applied CrossAxisAlignment.baseline)</summary>

```dart
import 'package:flutter/material.dart';

void main() async {
  runApp(
    const MaterialApp(
      title: 'Flutter Demo',
      home: MyApp(),
    ),
  );
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const Scaffold(
      body: Center(
        child: Row(
          crossAxisAlignment: CrossAxisAlignment.baseline,
          textBaseline: TextBaseline.alphabetic,
          children: [
            Text('សួរស្ដី'),
            Text('brahim'),
          ],
        ),
      ),
    );
  }
}

```
</details>

**Comment by brahimkh** [comment]
> I re-visited this and saw that the issue persists on iOS target platform with original sample code (without using `CrossAxisAlignment.baseline`):
> 
> ![Simulator Screenshot - iPhone 15 Pro - 2024-02-15 at 10 50 12](https://private-user-images.githubusercontent.com/104349824/304945167-2d03f69e-8872-4370-b023-e6f362e9d92a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc5NzAxNzEsIm5iZiI6MTcwNzk2OTg3MSwicGF0aCI6Ii8xMDQzNDk4MjQvMzA0OTQ1MTY3LTJkMDNmNjllLTg4NzItNDM3MC1iMDIzLWU2ZjM2MmU5ZDkyYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxNVQwNDA0MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NDVlNzcxNDE2ZTE0OTIxYzI2MzQyZWM1OGZiMWU3NmNjYWY0MzA1ODZkNzRjYWNiMjM1NjM4ZGY2OThiNTYxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1EDlFft5pxJx_7uxY5l8TSs6qIJeUuFL7IvarzZLvw4)
> 
> But the baseline displays correctly when I apply `CrossAxisAlignment.baseline` to Row as @LongCatIsLooong mentioned:
> 
> ![Simulator Screenshot - iPhone 15 Pro - 2024-02-15 at 10 58 24](https://private-user-images.githubusercontent.com/104349824/304945606-4d9529e4-3a41-4e82-ba2d-b93cbfed953f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc5NzAxNzEsIm5iZiI6MTcwNzk2OTg3MSwicGF0aCI6Ii8xMDQzNDk4MjQvMzA0OTQ1NjA2LTRkOTUyOWU0LTNhNDEtNGU4Mi1iYTJkLWI5M2NiZmVkOTUzZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxNVQwNDA0MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lOWEyMzJmYmE1OWYwOTU4MzlkMzFjMTU1ZGNmYjQ5MzE2ODI1NGI0N2I0MGMzYTJkNGE2MDQ1OTNkZmQ4NjRkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._2OmlSKg1COzri-Aw9jjJ9hVO_Jmg6VpPRjrR90ezZU)
> 
> Sample code (applied CrossAxisAlignment.baseline)
> ```dart
> import 'package:flutter/material.dart';
> 
> void main() async {
>   runApp(
>     const MaterialApp(
>       title: 'Flutter Demo',
>       home: MyApp(),
>     ),
>   );
> }
> 
> class MyApp extends StatelessWidget {
>   const MyApp({super.key});
> 
>   @override
>   Widget build(BuildContext context) {
>     return const Scaffold(
>       body: Center(
>         child: Row(
>           crossAxisAlignment: CrossAxisAlignment.baseline,
>           textBaseline: TextBaseline.alphabetic,
>           children: [
>             Text('សួរស្ដី'),
>             Text('brahim'),
>           ],
>         ),
>       ),
>     );
>   }
> }
> ```
> 
> flutter doctor -v (stable and master)

Thanks you so much, This code is working well
