### ISSUE TITLE
Licenses script picking up untracked temporary files

### ISSUE THREAD

**Issue by tbmbob** [flutter/flutter#12081]
## Steps to Reproduce

Add an untracked file to your local branch, say "flutter/frontend_server/pubspec.lock"

Run the script in engine/src/flutter/tools/licenses:
dart lib/main.dart --src ../../.. --out ../../../out/licenses --golden ../../travis/licenses_golden

The license script picks up the temporary file, even though it shouldn't (because it's a temp file).

## Logs

TravisCI gives the following error:
License script got different results than expected for out/license_script_output/licenses_flutter.
Please rerun the licenses script locally to verify that it is
correctly catching any new licenses for anything you may have
changed, and then update this file:
flutter/sky/packages/sky_engine/LICENSE
For more information, see the script in:
https://github.com/flutter/engine/tree/master/tools/licenses
--- flutter/travis/licenses_golden/licenses_flutter	2017-09-13 21:50:48.664117396 +0000
+++ out/license_script_output/licenses_flutter	2017-09-13 21:56:20.692117396 +0000
@@ -1233,13 +1233,12 @@
ORIGIN: ../../../LICENSE
TYPE: LicenseType.bsd
FILE: ../../../flutter/DEPS
FILE: ../../../flutter/frontend_server/.packages
FILE: ../../../flutter/frontend_server/bin/starter.dart
FILE: ../../../flutter/frontend_server/lib/server.dart
-FILE: ../../../flutter/frontend_server/pubspec.lock
FILE: ../../../flutter/lib/io/dart_io.cc
FILE: ../../../flutter/lib/io/dart_io.h
FILE: ../../../flutter/lib/ui/dart_runtime_hooks.cc
FILE: ../../../flutter/lib/ui/dart_runtime_hooks.h
FILE: ../../../flutter/lib/ui/dart_ui.cc
FILE: ../../../flutter/lib/ui/dart_ui.h
The command "./travis/build.sh" exited with 1.

**Comment by Hixie** [comment]
If anyone wants to fix this, we would accept a PR, but we're not planning on fixing it otherwise, so I'm going to close this issue.
