### ISSUE TITLE
[CP] Allow select cases to be numbers

### ISSUE THREAD

**Issue by AlexV525** [flutter/flutter#120848]
### issue_link

https://github.com/flutter/flutter/issues/116459

### Commit Hash

583a812

### Target

stable

### pr_link

https://github.com/flutter/flutter/pull/120847

### Impacted Users

Using localizations and have string numbers in their ARB files

### Impact Description

See https://github.com/flutter/flutter/issues/116459 and https://github.com/flutter/flutter/pull/120678#issuecomment-1432016460.

### Workaround

No

### Risk

low

### Test Coverage

yes

**Comment by AlexV525** [comment]
This request should be addressed before landing #120679. @thkim1011 @itsjustkevin

**Comment by thkim1011** [comment]
CP LGTM

**Comment by itsjustkevin** [comment]
Thank you @thkim1011 and @AlexV525 for all of the contributions!  @christopherfujino could you weigh in on this cherry-pick as well?
