### ISSUE TITLE
Widget Testing - Image widget not found on SliverChildListDelegate

### ISSUE THREAD

**Issue by vcqn** [flutter/flutter#120824]
Hi, I noticed that my widget test does not detect an image widget if it's built inside SliverChildListDelegate. But it does detect if there's a Text widget.

I have tried to run flutter clean, then flutter pub get, and also restarted VS. Still same result.

See screenshot for example.
![image](https://user-images.githubusercontent.com/46611348/219118328-5026ae32-cc50-4ad5-b8a6-b3c057a786b8.png)

If I run these two tests, the one containing SliverToBoxAdapter runs successfully. If I were to change find.byType to look for 'Text' widget on both test cases, it'll run fine. So, the only time the first widget test fail is when I expect to find an Image.

Exception Message:
The following TestFailure was thrown running a test:
Expected: exactly one matching node in the widget tree
  Actual: _WidgetTypeFinder:<zero widgets with type "Image" (ignoring offstage widgets)>
   Which: means none were found but one was expected

Running the code on:
Win 11
VS Code version: 1.75.1
Dart version: 3.58.0
Flutter version: 3.7.3 (Also tested on 3.7.1)

**Comment by huycozy** [comment]
Hi @vcqn 
You can try adding `skipOffstage: false` and see if it works:

```
expect(find.byType(Image, skipOffstage: false), findsOneWidget);
```

**Comment by TahaTesser** [comment]
@huycozy is right, here is working test code sample with `skipOffstage`

```dart
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  testWidgets('test SliverchildListDelegate', (WidgetTester tester) async {
    await tester.pumpWidget(
      MaterialApp(
        home: Scaffold(
          body: CustomScrollView(
            slivers: <Widget>[
              SliverList(
                delegate: SliverChildListDelegate(
                  <Widget>[
                    Image.asset('assets/dash.jpeg'),
                    const Text('Hello'),
                  ],
                ),
              ),
            ],
          ),
        ),
      ),
    );
    expect(find.byType(Image, skipOffstage: false), findsOneWidget);
  });
}
```

For similar questions in the future, please refer to Stackoverflow. Closing.

**Comment by vcqn** [comment]
> Hi @vcqn You can try adding `skipOffstage: false` and see if it works:
> 
> ```
> expect(find.byType(Image, skipOffstage: false), findsOneWidget);
> ```

My god... I have spent hours on this test.
Thank you!!!!!
