### ISSUE TITLE
XMLHttpRequest Error on Flutter Web

### ISSUE THREAD

**Issue by mohsinnaqvi606** [flutter/flutter#120822]
I am facing XMLHttpRequest error when calling google places Api.
there are many solutions to enable cors but in the case of google Apis, we can't do that. So I am pretty sure the issue is with flutter web.
So please help me out to call Api from flutter web

**Comment by darshankawar** [comment]
@mohsinnaqvi606 
I think this issue is where the same discussion took place: https://github.com/flutter/flutter/issues/119297, so let's track this in that issue. I'll close this as a duplicate and reopen the original.

**Comment by ditman** [comment]
@mohsinnaqvi606 Get started here: https://developers.google.com/maps/documentation/javascript/places#GetStarted

If you want a ready-made client for the Google Places API, you may be able to use this:

* https://pub.dev/documentation/google_maps/latest/google_maps_places/google_maps_places-library.html

(It's the same JS-Interop library that we use for the Google Maps Flutter plugin)
