### ISSUE TITLE
Images coming from Camera Stream are getting Blurred in Certain devices

### ISSUE THREAD

**Issue by manmmohanIntello** [flutter/flutter#120877]
Hi,

We have two Apps in which we are using 2 different versions of Camera Plugin.

App1 -- Camera Plugin Version 0.10.3
App2 -- Camera Plugin version 0.9.4+18

In both Apps the cameraController.takePicture() is throwing an error on the below mentioned devices
Vivo- V2045, vivo 1904, V2142, Y35, V2036
Samsung - Galaxy A22, Galaxy m51, galaxy 10s.

We have tried clicking the images using the cameraController.startImageStream which is giving the images in the form of Stream. Now, the above error has gone but the issue is that in certain devices like One Plus 7Pro, One plus 9Pro, RealMe2 Pro, MI devices etc the images which are getting clicked are blurred.
However, in certain devices like Samsung, Tecno it is working fine.

We are using below code for clicking the images and for converting those CameraImage into the JPG Image File.

Clicking Images via Camera using startImageStream

```
`await controller!.startImageStream((image) async {
print('image steaming');
print('image ${image.planes.last.bytes}');
if (count < 2) {
count++;
return null;
}
controller?.stopImageStream();

    print('image steaming stopped');
    print('image planes -- ' + image.planes.length.toString());

    var img = await convertYUV420toImageColor(image);

    if (img == null) {
      return null;
    }
    await _saveImage(image, Directory("${extDir!.path}/"),
        "IMG_${DateTime.now().millisecondsSinceEpoch}.png",
        success: (filePath) {
      print('image steaming saved file');
      onComplete(filePath);
    });
  });`
```
convertYUV420toImageColor function code

```
`Future<Uint8List?> convertYUV420toImageColor(CameraImage image) async {
try {
final int width = image.width;
final int height = image.height;
final int uvRowStride = image.planes[1].bytesPerRow;
final int uvPixelStride = image.planes[1].bytesPerPixel ?? 0;

  print("uvRowStride: " + uvRowStride.toString());
  print("uvPixelStride: " + uvPixelStride.toString());
  print('image Width -- ' + image.width.toString());
  print('image Height -- ' + image.height.toString());
  print('image P lanes -- ' + image.planes.length.toString());
  print('image Format -- ' + image.format.group.toString());
  print('image planes raw-- ' + image.format.raw.toString());
  // imgLib -> Image package from https://pub.dartlang.org/packages/image
  //var img = imglib.Image(width, height); // Create Image buffer

  final Directory directory =
      Directory('/storage/emulated/0/Download');
  var fileName = "dataFile_for_plane";

  for (int i = 0; i < image.planes.length; i++) {
    print("Saving data file");
    final File dataFile = File(
        '${directory.path}' + "/" + fileName + "_" + i.toString() + ".txt");
    var finalString = 'image Width -- ' +
        image.width.toString() +
        "\n" +
        'image Height -- ' +
        image.height.toString() +
        "\n" +
        'image Width -- ' +
        image.width.toString() +
        "\n" +
        'image Planes --' +
        image.planes[i].bytes.toString() +
        "\n" +
        'image Format -- ' +
        image.format.toString() +
        "\n" +
        'image Group -- ' +
        image.format.group.toString() +
        "\n" +
        'image planes raw --' +
        image.format.raw.toString() +
        "\n";
    await dataFile.writeAsString(finalString);
    print("Saved data file" + dataFile.path.toString());
  }
  var img = imglib.Image(height, width);

  // Fill image buffer with plane[0] from YUV420_888
  for (int x = 0; x < width; x++) {
    for (int y = 0; y < height; y++) {
      final int uvIndex =
          uvPixelStride * (x / 2).floor() + uvRowStride * (y / 2).floor();
      final int index = y * width + x;

      final yp = image.planes[0].bytes[index];
      final up = image.planes[1].bytes[uvIndex];
      final vp = image.planes[2].bytes[uvIndex];
      // Calculate pixel color
      int r = (yp + vp * 1436 / 1024 - 179).round().clamp(0, 255);
      int g = (yp - up * 46549 / 131072 + 44 - vp * 93604 / 131072 + 91)
          .round()
          .clamp(0, 255);
      int b = (yp + up * 1814 / 1024 - 227).round().clamp(0, 255);
      // color: 0x FF  FF  FF  FF
      //           A   B   G   R
      // //img.data[index] = shift | (b << 16) | (g << 8) | r;
      // if (img.boundsSafe(height - y, x)) {
      //   img.setPixelRgba(-(y + 1), x + 1, r, g, b, shift);
      // }
      if (img.boundsSafe(height - y, x)) {
        img.setPixelRgba(height - y, x, r, g, b, shift);
      }
    }
  }

  imglib.PngEncoder pngEncoder = new imglib.PngEncoder(level: 0, filter: 0);
  List<int> png = pngEncoder.encodeImage(img);
  // muteYUVProcessing = false;
  return Uint8List.fromList(png);
} catch (e) {
  print(">>>>>>>>>>>> ERROR:" + e.toString());
}
return null;
}`

```
The above code is giving us blur images in certain devices like One Plus 9 Pro, One Plus 7 Pro, RealMe 2 Pro etc.
Video link of the issue, flutter logs and the Complete Camera code is attached for reference.

Video showing the issue: https://drive.google.com/file/d/1qXNoLG6KtyVwZ86UaxzMx091WhqmHucX/view
Flutter Logs: https://drive.google.com/file/d/11bUyfH0fEo-YN2GdlWwSWgA16-88YtR6/view?usp=share_link
Camera.dart complete code: https://drive.google.com/file/d/1HGYOMYcNrEOK6rH_QpiCd9cXM1w-Cjws/view?usp=sharing

Any help would be appreciated.

Thanks in advance.

**Comment by darshankawar** [comment]
@manmmohanIntello 
Please provide `flutter doctor -v` and the code sample in complete minimal reproducible format (ex: main.dart) that we can directly copy paste and run to verify.

Also, if you also could share the blurred images vs regular images as a result of this to properly address the issue.

**Comment by manmmohanIntello** [comment]
Hi @darshankawar,

The code mentioned in the previous thread is giving us blur images in certain devices like One Plus 9 Pro, One Plus 7 Pro, RealMe 2 Pro etc.
Video link of the issue, flutter logs and the Complete Camera code is attached for reference.

Video showing the issue: https://drive.google.com/file/d/1qXNoLG6KtyVwZ86UaxzMx091WhqmHucX/view
Flutter Logs: https://drive.google.com/file/d/11bUyfH0fEo-YN2GdlWwSWgA16-88YtR6/view?usp=share_link
Camera.dart complete code: https://drive.google.com/file/d/1HGYOMYcNrEOK6rH_QpiCd9cXM1w-Cjws/view?usp=sharing

**Comment by darshankawar** [comment]
@manmmohanIntello 
I can't access the google drive link as it asks for permission.
Also can you share details as which apis / OS are the listed devices are on ?
See [this](https://github.com/flutter/flutter/issues/56760) similar / related issue and check if it resembles with your case.

**Comment by manmmohanIntello** [comment]
@darshankawar , 

I have provided the access of the drive link. Also, the issue is on devices ranges from Android 10, 11, 12 and 13 on various device.

The above issue which u have pointed is separate one where Camera Preview is blurred. In my case the Preview is fine. The issue is with the images which I click, those gets blurred in certain devices.

**Comment by huycozy** [comment]
Hi @manmmohanIntello 
Thanks for providing more information but your sample code is containing many 3rd plugins/packages (such as `geolocator`, `image_cropper`) that we may not verify if the issue belongs to the camera plugin or those plugins. 

You may try [camera sample code](https://github.com/flutter/plugins/tree/main/packages/camera/camera/example) instead (and modify it if it's necessary) to see if the issue occurs.

**Comment by manmmohanIntello** [comment]
Hi, 

Thanks for the reply. I have tried the sample Camera code as well but it was also showing error. I have found a solution. Upgraded the resolution from Medium to High and now the images are appearing fine in all the devices in which we have tested the code.

So, I am marking this issue as resolved.
