### ISSUE TITLE
Custom Tensorflow lite model integration in flutter app

### ISSUE THREAD

**Issue by baimamboukar** [flutter/flutter#120871]
![image](https://user-images.githubusercontent.com/49169158/219345151-7786db5f-f9e8-4096-990e-d731cf5719ac.png)

## Use case

 I have a **tensorflow lite ML model** that I'd like to use in a flutter application.
One of my first options was to test plugins available on pub dev. Unfortunately, I was unable to find one that is still working in 2023.
Both of the major two plugins appear to have been abandoned. [tflite_flutter](https://pub.dev/packages/tflite_flutter) and [tflite](https://pub.dev/packages/tflite)

## Proposal
- Is there an official flutter package available for this use case?
- Or are there any other options for integrating Tensorflow models into a Flutter app?

**Comment by darshankawar** [comment]
@baimamboukar 
Check [this](https://firebase.google.com/docs/ml/flutter/use-custom-models) documentation and see if it helps for your use case.
Also, your question is better suited for support channels like StackOverflow, so please ask the same there.
Closing from here.
