### ISSUE TITLE
MissingPluginException(No implementation found for method getApplicationDocumentsDirectory on channel plugins.flutter.io/path_provider)

### ISSUE THREAD

**Issue by RafaelRVargas** [flutter/flutter#120915]
I'm trying to test some functionality in my app and when updating flutter to version 3.7.0 this code snippet started giving an error
```
main() async {
 TestWidgetsFlutterBinding.ensureInitialized();
  SharedPreferences.setMockInitialValues({});

setUpAll(() async {
    await initHive();
  });
test("exemple", () async {
});
}

```
```
Future<void> initHive() async {
  try {
    await Hive.initFlutter();

  } on Exception catch (_, e) {
    Groveman.error(_.toString(), error: e);
  }
```

this is the exception returned when running Hive.initFlutter():
`MissingPluginException(No implementation found for method getApplicationDocumentsDirectory on channel plugins.flutter.io/path_provider)`

**Comment by darshankawar** [comment]
@RafaelRVargas 
I see that you are using `hive` package which is third party. Does the same error occur without using it and just using `path_provider` ?

See also similar issues in dedicated repo for your reference: https://github.com/hivedb/hive/issues

**Comment by RafaelRVargas** [comment]
thanks for helping me, i found something that solved my problems in this issue https://github.com/hivedb/hive/issues/881
