### ISSUE TITLE
unawaited_futures lint is too strict

### ISSUE THREAD

**Issue by subzero911** [flutter/flutter#120902]
## The problem
When I use a future with .then , it still asks to mark a future as "unawaited" or await it.
It's too strict; if I use `.then`, it already means, that unawaiting was intentional.

## Code sample
(both `unawaited_futures` and `discarded_futures` are on):

<img width="495" alt="image" src="https://user-images.githubusercontent.com/12999702/219448613-6dedfe4a-c2e7-45b3-82a8-0f367a81640c.png">

<details>
<summary> Flutter doctor </summary>
svmolchan1@0000NBB0TX4DJ20 goldy % flutter doctor -v
[✓] Flutter (Channel stable, 3.7.3, on macOS 13.0.1 22A400 darwin-arm64, locale ru-RU)
    • Flutter version 3.7.3 on channel stable at /opt/homebrew/Caskroom/flutter/3.3.10/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9944297138 (8 days ago), 2023-02-08 15:46:04 -0800
    • Engine revision 248290d6d5
    • Dart version 2.19.2
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/svmolchan1/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.75.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.58.0

[✓] Connected device (3 available)
    • M2101K9AG (mobile) • cc706425 • android-arm64  • Android 12 (API 31)
    • macOS (desktop)    • macos    • darwin-arm64   • macOS 13.0.1 22A400 darwin-arm64
    • Chrome (web)       • chrome   • web-javascript • Google Chrome 96.0.4664.55

[✓] HTTP Host Availability
    • All required HTTP hosts are available
</details>

**Comment by moffatman** [comment]
But the future returned within `.then` is now unawaited 😆

**Comment by subzero911** [comment]
I suppose that if I use `.then` once, the whole chain shouldn't be lint-checked.

**Comment by maRci002** [comment]
https://dart-lang.github.io/linter/lints/unawaited_futures.html

> `DO` await functions that return a `Future` inside of an async function body.

https://api.flutter.dev/flutter/dart-async/Future/then.html

> Returns a new [`Future`](https://api.flutter.dev/flutter/dart-async/Future-class.html) which is completed with the result ...

So you should be explicit about if you want to ignore the `Future`.

**Comment by subzero911** [comment]
It I use `.then` block, then I am already explicit enough about not awaiting the `Future`.
If I didn't use `.then` and started Future, well, okay, I probably forgot to `await` it. But if I use `.then`, I definitely did not.

**Comment by maRci002** [comment]
In case of `unawaited_futures` you can use [ignore](https://api.dart.dev/stable/2.14.1/dart-async/FutureExtensions/ignore.html), this chain will remove lint warnings (_so you can avoid `unawaited`_).

```dart
Future<void> main() async {
  Future<void>.delayed(Duration.zero).then((value) => null).ignore();
}
```

In case of `discarded_futures` you will have to wrap your `Future` inside `unawaited`:

```dart
void main() {
  unawaited(Future<void>.delayed(Duration.zero).then((value) => null));
}
```

**Comment by darshankawar** [comment]
@subzero911 
Along with above comment, also check [this](https://github.com/flutter/flutter/issues/97410#issuecomment-1023907005) and see if it helps in your case.
