### ISSUE TITLE
i18n: Generate dedicated classes per language instead of using the map of data

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#12090]
We should merge language i18n data with locale i18n data in `gen_localizations` rather than dynamically in `MaterialLocalizations` (e.g. `material_en.arb` and `material_en_GB.arb`).

/cc @Hixie

**Comment by HansMuller** [comment]
We could also have the code generator produce private classes per locale, instead of maps: https://github.com/flutter/flutter/pull/12359#discussion_r142288455

**Comment by long1eu** [comment]
I've build a plugin that does exactly that. You can check it out here https://github.com/long1eu/flutter_i18n

**Comment by yjbanov** [comment]
Assigning to @HansMuller. I believe he's working on this as we speak.

**Comment by HansMuller** [comment]
This was done in https://github.com/flutter/flutter/pull/13653
