### ISSUE TITLE
[webview_flutter] cannot use onWebViewCreated property on 4.0.2

### ISSUE THREAD

**Issue by islinjj** [flutter/flutter#120959]
Hi, I can use onWebViewCreated property on 3.0.4

<img width="761" alt="image" src="https://user-images.githubusercontent.com/32004335/219584135-cc54d415-0e2a-4c38-8641-f23fd01299c3.png">

Is there any alternative to the onWebViewCreated property in version 4.0.2 ？

Thanks

**Comment by exaby73** [comment]
Hello @islinjj. Does awaiting `loadRequest` work for you?

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  late WebViewController _controller;

  @override
  void initState() {
    super.initState();
    _controller = WebViewController()
      ..loadRequest(Uri.parse('https://flutter.dev'))
          .then((_) => print('Loaded'));
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        leading: BackButton(
          onPressed: () async {
            if (await _controller.canGoBack()) {
              await _controller.goBack();
            }
          },
        ),
        title: Text(widget.title),
      ),
      body: Center(
        child: WebViewWidget(controller: _controller),
      ),
    );
  }
}
```

</details>

**Comment by islinjj** [comment]
Yes, I can use loadRequest. So you mean I can use loadRequest.then() instead of onWebViewCreated?

**Comment by exaby73** [comment]
I don't think they are the same here. I am not sure why this was removed, or if using `.then(). on `loadRequest` is the intended alternative, or if there is a something similar to `onWebViewCreated` that I haven't found yet . I'll label this as a bug none the less, and allow some insights from the team on this.

**Comment by stuartmorgan** [comment]
Please see https://pub.dev/packages/webview_flutter#instantiating-webviewcontroller; the relationship between the controller and the widget has changed, so an asyncronous callback to get the controller no longer makes sense.

If you have a use case you can't implement with the new APIs, please file an issue describing the use case, not the old API.
