### ISSUE TITLE
Failed assertion: line 4516 pos 12: '!_debugLocked': is not true.

### ISSUE THREAD

**Issue by kudozicecream** [flutter/flutter#120969]
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by darshankawar** [comment]
Closing as empty issue.
