### ISSUE TITLE
Banding rendering artefacts after scrolling

### ISSUE THREAD

**Issue by Takhion** [flutter/flutter#12091]
There's some terrible banding artefacts when rendering graphics after scrolling.
It's very evident when observed on a device.

![](https://user-images.githubusercontent.com/2116164/30446632-ffbb2536-9989-11e7-8105-82480245e024.png)

## Steps to Reproduce

Create an app with a `ListView` with lots of repeating elements, run it on an Android device, then scroll the list.

## Logs

Nothing relevant.

## Flutter Doctor

```
[✓] Flutter (on Mac OS X 10.12.5 16F73, locale en-DE, channel alpha)
    • Flutter at /Users/takhion/flutter
    • Framework revision 701d534ba9 (2 days ago), 2017-09-12 14:01:51 -0700
    • Engine revision 31d03de019
    • Tools Dart version 1.25.0-dev.11.0

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.1)
    • Android SDK at /Users/takhion/Android/sdk
    • Platform android-26, build-tools 26.0.1
    • ANDROID_HOME = /Users/takhion/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_76-release-b03)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.3.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3.3, Build version 8E3004b
    • ios-deploy 1.9.2
    • CocoaPods version 1.2.1

[✓] Android Studio
    • Android Studio at /Applications/Android Studio 3.0 Preview.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[✓] Android Studio (version 2.2)
    • Android Studio at /Applications/Android Studio Preview.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_76-release-b03)

[✓] Android Studio (version 2.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_76-release-b03)

[✓] Connected devices
    • Pixel • FA69N0309825 • android-arm • Android 8.0.0 (API 26)
```

**Comment by eseidelGoogle** [comment]
We've seen problems like this from the raster cache before.  @chinmaygarde or @jason-simmons might know.

**Comment by sethladd** [comment]
Is this related to custom fonts, or any fonts?

**Comment by Takhion** [comment]
@sethladd I tried with the default font and it was the same

**Comment by sethladd** [comment]
Thanks for giving it a shot with the default font!

**Comment by eseidelGoogle** [comment]
@tvolkert suggests this could be a possible resurgence of https://github.com/flutter/flutter/issues/9276.

**Comment by sethladd** [comment]
Hi @Takhion would you mind switching to master branch? We tried master here w/ a Pixel and we didn't see tearing after scroll.

**Comment by sethladd** [comment]
Also, confirming: did you test on Pixel XL or Pixel?

Also, what happens if you test on not-a-pixel? (it worked for us on a Moto G4)

We're just trying to narrow down the variables :)

**Comment by Takhion** [comment]
@sethladd OK before I only tried on a Pixel (small), now I've also tried on other phones with other Android versions and the banding is still there, although sometimes it's less visible (but I guess it depends on the pixel density). I also tried with the `master` branch and the result is the same.

**Comment by sethladd** [comment]
Thanks for the additional info. We'll keep digging here, trying to reproduce it.

**Comment by sethladd** [comment]
Ah, I can repro this on my pixel (scroll down fast, and then scroll up slowly).

```
sethladd@sethladd-macbookpro ~/Code/flutter-spike (master) $ flutter doctor
[✓] Flutter (on Mac OS X 10.12.6 16G29, locale en-US, channel alpha)
    • Flutter at /Users/sethladd/Code/flutter
    • Framework revision 701d534ba9 (3 days ago), 2017-09-12 14:01:51 -0700
    • Engine revision 31d03de019
    • Tools Dart version 1.25.0-dev.11.0

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.0)
    • Android SDK at /Users/sethladd/Library/Android/sdk
    • Platform android-26, build-tools 26.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[-] iOS toolchain - develop for iOS devices (Xcode 8.3.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3.3, Build version 8E3004b
    • ios-deploy 1.9.1
    ✗ ios-deploy out of date (1.9.2 is required). To upgrade:
        brew upgrade ios-deploy
    • CocoaPods version 1.2.0

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.2.3)
    • Flutter plugin version 16.0
    • Dart plugin version 172.3968.27

[✓] Connected devices
    • Pixel • FA6990313888 • android-arm • Android 8.0.0 (API 26)
```

**Comment by eseidelGoogle** [comment]
@jason-simmons is investigating.  It looks like we're just passing the wrong flags to skia when drawing tiles out of the raster cache.   Likely a very easy fix.

**Comment by eseidelGoogle** [comment]
Speaking with @abarth and @jamesr at lunch today, the solution we landed here is likely covering over a deeper problem in our raster cache, but one we can solve when @chinmaygarde has returned.
