### ISSUE TITLE
Dropdown widget overlaps and disables scrolling

### ISSUE THREAD

**Issue by Ch-Anas-Abdullah** [flutter/flutter#120968]
### **Summary:**
When a Flutter dropdown widget is open, it overlays other widgets and prevents scrolling. This makes it difficult to interact with widgets underneath the dropdown, especially if they contain a lot of content. Users are unable to scroll the underlying widgets even when the dropdown is open, which can be frustrating and confusing.

### **Steps to reproduce:**
Create a Flutter app with a dropdown widget and other scrolling widgets underneath it.
Open the dropdown and try to scroll the underlying widgets. Note that scrolling is disabled and the dropdown overlays the other widgets.

### **Expected behavior:**
When a dropdown widget is open, it should allow users to scroll the underlying widgets so that they can interact with them.

### **Actual behavior:**
The dropdown widget overlays and disables scrolling of the underlying widgets, preventing users from interacting with them.

### **Workaround:**
A possible workaround is to wrap the widget that contains the dropdown and the scrolling content in a GestureDetector widget and handle the scroll events in the GestureDetector. However, this workaround may not be feasible in all cases and is not an ideal solution.

https://user-images.githubusercontent.com/93251406/219647820-cfecd007-4b29-42cc-bc5d-a66c51196ae5.mp4

**Comment by darshankawar** [comment]
@Ch-Anas-Abdullah 
Thanks for the report. Can you provide `flutter doctor -v`, a complete minimal reproducible code sample that we can use that shows the reported behavior ?

Also, can you also check how is the native behavior for same scenario ? Does it allow scrolling when dropdown button is at forefront ?

**Comment by archidvigneshchimie** [comment]
@darshankawar I don't think scrolling while dropdown is active is intended behavior. No app scrolls while a dropdown is in active state as far as I have seen. It is however an issue if the dropdown is overlay-ed on a scrollview and it somehow blocks the scroll view from scrolling for some reason. In this case, op has a field embedded in scroll view
