### ISSUE TITLE
Flutter in_purchase not working release mode

### ISSUE THREAD

**Issue by joshua750** [flutter/flutter#120956]
I have test flutter official in purchase plugin issue was in this plugin it was working fine on internal test but not working on production release mode

**Comment by huycozy** [comment]
Hi @joshua750 
Please provide the information indicated below:
- What is the version of `in_app_purchase` plugin are you using?
- The affected device information (OS, model)
- The output of `flutter doctor -v` (flutter version which was used to deploy the app)
- Reproduction steps, Expected results, Actual results

Thank you!
