### ISSUE TITLE
Make better comment for Alignment and a correct calculation formula for subview's position

### ISSUE THREAD

**Issue by WonderJeffy** [flutter/flutter#120957]
there is some comment explain Alignment(x, y):
```dart
/// `Alignment(x, y)` in a rectangle with height h and width w describes
/// the point (x * w/2 + w/2, y * h/2 + h/2) in the coordinate system of the
/// rectangle.
```
but, in actually, if you want calculate  a child widget's coordinate offset when using Alignment(x, y), the correct calculation formula is `(x*(parent_width - child_width)/2, y*(parent_height - child_height)/2)`

please update this comment and calculation formula

**Comment by huycozy** [comment]
@WonderJeffy Thanks for the report.
I see there's an open issue that seems to be similar to the case you described #68680. Please take a look at that issue and see if they are similar.

**Comment by WonderJeffy** [comment]
@huycozy Thanks for your reply.And yes，I think they are the same problem.

**Comment by huycozy** [comment]
Thanks for confirming. I will close this issue in favor of https://github.com/flutter/flutter/issues/68680, so please follow up on it for further updates. You can leave there your comment and react an upvote to the original comment will help to raise the issue.
