### ISSUE TITLE
The same code is displayed inconsistently on android, window and web

### ISSUE THREAD

**Issue by dong-lufei** [flutter/flutter#120949]
```
import 'package:flutter/material.dart';

void main() {
  runApp(
    const Center(
      child: Text(
        'Hello, world!',
        textDirection: TextDirection.ltr,
      ),
    ),
  );
}
```

Why does the web version display black text on a white background (is it related to the user's system or the dark mode of the browser?). And there is an extra word in the upper left corner - the red "if"

![屏幕截图 2023-02-17 113520](https://user-images.githubusercontent.com/63916062/219544261-6d3d20dd-f4f1-4b0a-baaa-b0f9b359f1d3.png)
![window](https://user-images.githubusercontent.com/63916062/219544268-eb2f9ae9-1cfc-422e-b040-08593ef7c53d.png)
![android](https://user-images.githubusercontent.com/63916062/219544273-875f3b0a-90c9-4d92-93a3-39c0236f6740.png)

**Comment by exaby73** [comment]
Hello @dong-lufei. You need to add a `Scaffold` :). On web the default background is black, while on iOS and Android, the background is black. A `Scaffold` adds some default styling that is needed by a lot of widgets. Try wrapping your `Center` in a `Scaffold` and you should see consistency. Closing this issue as this is working as expected. Thank you
