### ISSUE TITLE
Make it clear that Flutter fully supports Community Edition of IntelliJ IDEA in the codelab intro

### ISSUE THREAD

**Issue by filiph** [flutter/flutter#12093]
Looking at [Getting started](https://flutter.io/getting-started/) and the [tutorial](https://codelabs.developers.google.com/codelabs/flutter/index.html#1) it might seem like the Flutter plugin only works in IntelliJ IDEA and not the other IntelliJ products.

> Alternatively, if you are using the IntelliJ IDEA IDE with the Flutter plugins, ... [source](https://flutter.io/getting-started/#running-your-flutter-app)

> To develop mobile apps with Flutter you need: - the Flutter SDK, - an IntelliJ IDEA IDE with Flutter plugins,  ... [source](https://codelabs.developers.google.com/codelabs/flutter/index.html#1)

I'm happily using Flutter from my IntelliJ WebStorm IDE, and I don't think I have any less awesome dev experience. I'm not sure about the other IDEs.

I can imagine a lot of developers have a non-IDEA IntelliJ IDE — they are [significantly cheaper](https://www.jetbrains.com/store/?fromMenu#edition=commercial) while not really taking anything away if you're not a Java programmer.

I'm especially thinking about users of [AppCode](https://www.jetbrains.com/objc/), but all the following flavours of IDEA could be relevant (at least for trying out Flutter):

* https://www.jetbrains.com/objc/
* https://www.jetbrains.com/clion/
* https://www.jetbrains.com/go/
* https://www.jetbrains.com/phpstorm/
* https://www.jetbrains.com/pycharm/
* https://www.jetbrains.com/pycharm-edu/
* https://www.jetbrains.com/rider/
* https://www.jetbrains.com/ruby/
* https://www.jetbrains.com/webstorm/

Unfortunately, I don't know the user bases of these, but some of them are top IDE choices for their field.

How sure are we that the Flutter plugin works with all these? If we're pretty sure, do we want to rewrite all mentions of IntelliJ IDEA to "an IntelliJ IDE"?

**Comment by eseidelGoogle** [comment]
This is a @devoncarew question. :)

**Comment by filiph** [comment]
After discussion with @sethladd, it looks like we only really support InteliJ IDEA (so WebStorm support may be going away). BUT: the Flutter plugin works 100% in the _Community Edition_ of the IDE (unlike the Dart web SDK, for example, which does not have debugging in the Community Edition). 

So I revoke my question and ask another one: do we want to make it super clear that IDEA Community Edition is supported on our sites and in our codelabs? I, for one, assumed "IntelliJ IDEA" to not include the community edition.

**Comment by sethladd** [comment]
If it's not clear, we should make it clear that the free community edition is totally sufficient :)

**Comment by devoncarew** [comment]
Yeah, we support:
- IntelliJ Community Edition (CE)
- IntelliJ IDEA

The community edition is great, in that it's free (and open source), and the Flutter plugin is fully functional there. IDEA would be useful for people that wanted to do Flutter and Dart web app development at the same time.

We currently support WebStorm. Support for that was added before flutter plugins were a thing, and it's not as functional as the other (2) supported IntelliJ products now (for instance, Java support isn't included in WebStorm).

We could support other platforms in the future. They're all built on the same set of APIs, but there is generally some additional engineering for each one. Android Studio for instance has a different project wizard and related set of APIs. Some products don't support multi-module projects, or don't include things like the `Build` menu. So right now we're just marking specific products as compatible with the Flutter plugin (so we show up in the list of available plugins in the preferences page) when we're sure we work well in that product.

**Comment by filiph** [comment]
Okay, thanks for the info. Let's make it clear, then, that CE works. I updated the title of the issue.

**Comment by ReallyWantTo** [comment]
Good to know. I'm new at flutter and was just wondering whether the free community version of IntelliJ would suffice or not. I'll go for that now,

**Comment by sethladd** [comment]
We also now support Android Studio

**Comment by sethladd** [comment]
@LarkAscending would it be possible to update the codelab to specify that either IntelliJ Community (free) or Ultimate is sufficient? Thanks!

(or, is that something I could do?)

**Comment by sethladd** [comment]
@mit-mit should we also mention in the codelab intro that we work with Android Studio? Should we indicate a preference?

**Comment by LarkAscending** [comment]
@sethladd Yes I can update the codelab to make it clear re: CE and Ultimate. 

I've been watching all the PRs go by from @devoncarew and team re: Android Studio, etc. This thread is right on the money on why a conservative approach was taken to begin with (saying we only support those 2 IDEs 100%). There's a huge grey area of support for the other IDEs and usually people try them and report their experience.

**Comment by LarkAscending** [comment]
Backing up and re-reading the thread, here's actually an important detail - the Community Edition is also branded IntelliJ IDEA. That's why it's worded the way it is today....
<img width="1504" alt="screen shot 2017-10-12 at 11 44 08 am" src="https://user-images.githubusercontent.com/23464935/31513305-d22c83de-af42-11e7-848b-e40efd3367d7.png">

**Comment by LarkAscending** [comment]
Both codelabs are updated:
https://codelabs.developers.google.com/codelabs/flutter
https://codelabs.developers.google.com/codelabs/flutter-firebase

See Step 2 for the changed text.

**Comment by sethladd** [comment]
Thanks!
