### ISSUE TITLE
[Impeller] Improve efficiency of apps with excessive overdraw.

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#120937]
Navigate to the shopping sub app in the new flutter gallery and take a frame capture. Notice that we're taking a loooong time ~18ms on the iPad to render the frame. Then look into the draw calls, and notice that we're painting the previous route too!

*EDIT: This is due to gallery using a Positioned Widget instead of a Route.*

Unclear what the problem is here. Are we missing a clip herustic? Or is this something that could be elimated by better ordering of paint commands

![image](https://user-images.githubusercontent.com/8975114/219523777-20398bdd-7d68-4bac-976a-84eff061f31a.png)

**Comment by jonahwilliams** [comment]
err not the shopping but Crane. Though it probably tracks for all of them

**Comment by jonahwilliams** [comment]
This happens with all of the routes actually.

**Comment by jonahwilliams** [comment]
This app is using the router/navigator the same way most other apps would, so it doesn't seem to be an app specific problem

**Comment by jonahwilliams** [comment]
Some sort of issue with modal routes? The route itself isn't really modal, it covers the entire screen, but perhaps it is implented with one and that is why the preivous route sticks around.

**Comment by jonahwilliams** [comment]
ahh potentially false alarm. We might still be able to do something here, but this is a but in the gallery. It thinkgs the iPad is a foldable device so it opens the sub-pass in a positioned widget instead of using a Route.

We might still use this as an opportunity to do better but its clearly a misuse of the Flutter API.

**Comment by chinmaygarde** [comment]
Closing as fixed with the linked patches. If there is something we need to track in Impeller internals, let's re-open with the specific work item.
