### ISSUE TITLE
Workshop attendees were curious why hot reload wasn't working after they change contents of main()

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#12095]
Feedback from a recent workshop. Some participants who edited the contents of main() were curious and surprised when a Hot Reload didn't notice their changes.

**Comment by sethladd** [comment]
Proposal: add a small comment to the starter app, hinting that code inside of main() is NOT hot reloaded.

**Comment by Hixie** [comment]
Yeah, that's why the template app has such a small `void main`, to push people away from expecting it to hot reload.

We could add a comment there but I'm concerned about the negative effect of having a negative comment ("hot reload doesn't work here") so early in the file, before any positive comments ("hot reload works here!").

**Comment by sethladd** [comment]
I believe @rmacnak-google and @mit-mit are working on a solution here?

**Comment by sethladd** [comment]
cc @devoncarew

**Comment by devoncarew** [comment]
@rmacnak-google has notifications for when functions are changed during a reload, but they weren't run during the reassemble (/cc @a-siva). That's hooked into the CLI now, and we have an open issue to hook it into IntelliJ (https://github.com/flutter/flutter-intellij/issues/1398).

Mechanically, it would be harder for people to make changes in the main() method of the create template if we changed it to using the function shorthand (`=>`) https://github.com/flutter/flutter/blob/master/packages/flutter_tools/templates/create/lib/main.dart.tmpl#L10

**Comment by sethladd** [comment]
I'm a fan of both displaying what was actually reloaded/not reloaded, as well as changing main to `=>`

Thanks!

**Comment by a-siva** [comment]
Please note it is not just changes to the main method that don't show up, any changes to code that has already executed and is not going to be executed after the reload will have the same issue.

To summarize "As a general rule, if the modified code is downstream of the root widget’s build method, then hot reload behaves as expected. However, if the modified code won’t be re-executed as a result of rebuilding the widget tree, its effects won’t be visible after hot reload".

**Comment by sethladd** [comment]
Thanks for the additional notes!

**Comment by Hixie** [comment]
I'm going to close this; we're dealing with issues like this in general as a high-level work item.
