### ISSUE TITLE
Customer tests are broken with recent dart analyzer changes

### ISSUE THREAD

**Issue by eyebrowsoffire** [flutter/flutter#120992]
Rolls from Engine -> Framework have been failing on customer tests coming from https://github.com/rrousselGit/provider.git. See failure here: https://cirrus-ci.com/task/6685374529929216?logs=main#L1826

This is due to changes in the dart sdk that have upgraded some info diagnostics to warning diagnostics: https://dart-review.googlesource.com/c/sdk/+/283400

We need to do the following:
1) Revert the dart SDK rolls to unblock the engine -> framework roll
2) Revert the analzyer change so that subsequent dart sdk -> engine rolls don't break downstream
3) Fix the customer test

**Comment by eyebrowsoffire** [comment]
Dart analyzer revert here: https://dart-review.googlesource.com/c/sdk/+/283923

**Comment by a-siva** [comment]
Since the Dart analyzer change has been reverted can this issue be closed?

**Comment by eyebrowsoffire** [comment]
Yes, I think we're safe to close this. The customer test was also updated, so I think the dart analyzer change can probably be relanded without breaking anything.
