### ISSUE TITLE
Large image crashes app on Safari mobile browser

### ISSUE THREAD

**Issue by geronimol** [flutter/flutter#120945]
## Steps to Reproduce
1. Build app for web.
2. Run app on Safari mobile browser.

**Expected results:** 
To see the image
**Actual results:** 
The app keeps reloading until it crashes
<details>
<summary>Code sample</summary>

```
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Image.asset('assets/template.jpg'),
    );
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```[✓] Flutter (Channel stable, 3.7.3, on macOS 11.5.2 20G95 darwin-x64, locale es-419)
    • Flutter version 3.7.3 on channel stable at /Users/geronimo/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9944297138 (8 days a
![template](https://user-images.githubusercontent.com/56521222/219536970-4e71a74f-b4aa-4d21-a4db-ae4717881c3f.jpg)
go), 2023-02-08 15:46:04 -0800
    • Engine revision 248290d6d5
    • Dart version 2.19.2
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/geronimo/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13C100
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.75.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.5.2 20G95 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 110.0.5481.100

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

</details>

Tried using another image (2.5MB high resolution jpeg) and same results.

Note: Seems to work using `FilterQuality.low`, but not always.

Example image:
![template](https://user-images.githubusercontent.com/56521222/219537581-f44d8c3e-d2e2-4934-abe1-91972b134304.jpg)

**Comment by darshankawar** [comment]
@geronimol 
Try using `cacheWidth` and `cacheHeight`. I think a good practice is to use these properties when you are using big size images.

**Comment by geronimol** [comment]
> @geronimol Try using `cacheWidth` and `cacheHeight`. I think a good practice is to use these properties when you are using big size images.

Tried this, but the problem persists.

**Comment by maRci002** [comment]
I think there is something wrong with that image when I try to open it from github via my phone (_chrome_) it loads the image but when I scoll down the screen goes to white.

https://user-images.githubusercontent.com/8436039/219700592-350b3f49-e672-45aa-8d6c-5437af7797e7.mp4

**Comment by huycozy** [comment]
Hi @geronimol 
I tested this with 3.5MB image but it's loaded well without crashing (`iPhone 7, iOS 15.7.2`).

Can you provide the source image along with device info (OS, model)? Also, can you follow this [guideline](https://www.lifewire.com/activate-the-debug-console-in-safari-445798) and check if there is any error log from the Safari console?

**Comment by geronimol** [comment]
I don't see any errors in the Safari console:
<img width="998" alt="Captura de Pantalla 2023-02-20 a la(s) 20 01 43" src="https://user-images.githubusercontent.com/56521222/220211024-0810e506-0f70-43ed-bb90-a540c750863c.png">

Tested using iPhone 6s, iOS 15.7.2 and two more devices that are not mine (don't know models) and same issue.

I must clarify that there are times that it does load, but after refreshing a few times, it crashes.

Please also look at the image resolution (10000x10000). Did you try using it?
I uploaded the build here so it can be easy to test: https://fluttertest-97325.web.app/#/

**Comment by geronimol** [comment]
> Hi @geronimol I tested this with 3.5MB image but it's loaded well without crashing (`iPhone 7, iOS 15.7.2`).
> 
> Can you provide the source image along with device info (OS, model)? Also, can you follow this [guideline](https://www.lifewire.com/activate-the-debug-console-in-safari-445798) and check if there is any error log from the Safari console?

I don't see any errors in the Safari console:
<img width="998" alt="Captura de Pantalla 2023-02-20 a la(s) 20 01 43" src="https://user-images.githubusercontent.com/56521222/220211556-8026e312-7f5d-4ab5-b054-22ba937c534d.png">


Tested using iPhone 6s, iOS 15.7.2 and two more devices that are not mine (don't know models) and same issue.

I must clarify that there are times that it does load, but after refreshing a few times, it crashes.

Please also look at the image resolution (10000x10000). Did you try using it?
I uploaded the build here so it can be easy to test: https://fluttertest-97325.web.app/#/

**Comment by huycozy** [comment]
>Please also look at the image resolution (10000x10000). Did you try using it?

Can you share the image source by attaching it here?

I try opening your deployed site on my device but it doesn't show the image, it shows an error screen instead and no error log from the console.

<details>
<summary>Error</summary>

<img width="400" src="https://user-images.githubusercontent.com/104349824/220301699-f7e3a60d-0be2-46b8-a28f-6ccd16f00b9d.png">
</details>

Can you also share the complete project which includes the web directory as well?

**Comment by geronimol** [comment]
> Can you share the image source by attaching it here?
> 
Not sure what you mean with image source. I created it using photopea.com and it is attached to the main post.

> I try opening your deployed site on my device but it doesn't show the image, it shows an error screen instead and no error log from the console.
> 
> Error
>
That is the error it shows when app is crashing.

> Can you also share the complete project which includes the web directory as well?
>
[untitled3.zip](https://github.com/flutter/flutter/files/10794390/untitled3.zip)

I also tried using `Image.network()` and the same error happened.

**Comment by darshankawar** [comment]
Thanks for the update @geronimol 
As you noted earlier, with `filterQuality: FilterQuality.low`, it works, can you also try with below values and see what you get ?
`filterQuality: FilterQuality.none`
`filterQuality: FilterQuality.high`

I am wondering if this could be related / similar to https://github.com/flutter/flutter/issues/101445

**Comment by geronimol** [comment]
> Thanks for the update @geronimol As you noted earlier, with `filterQuality: FilterQuality.low`, it works, can you also try with below values and see what you get ? `filterQuality: FilterQuality.none` `filterQuality: FilterQuality.high`
> 
> I am wondering if this could be related / similar to #101445

Tried and same issue. Some times it loads, but many times crashes

**Comment by darshankawar** [comment]
@geronimol 
Please check [this](https://github.com/flutter/flutter/issues/110331) issue and underlying [comments](https://github.com/flutter/flutter/issues/110331#issuecomment-1230505200) from team member.
