### ISSUE TITLE
Plugin: Geolocation

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#121]
<a href="https://github.com/eseidelGoogle"><img src="https://avatars.githubusercontent.com/u/11857803?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [eseidelGoogle](https://github.com/eseidelGoogle)**
_Wednesday Aug 05, 2015 at 19:34 GMT_
_Originally opened as https://github.com/flutter/engine/issues/471_

---

Some features include:
- [ ] geofencing (region monitoring)
- [ ] current/last location
- [ ] location updates
- [ ] beacons
- [ ] testable (mockable) APIs

**Comment by sethladd** [comment]
Android location APIs from Play Services: https://developers.google.com/android/reference/com/google/android/gms/location/package-summary

(the android.location APIs are not recommended. Android wants us to use the Play Services APIs for location)

**Comment by sethladd** [comment]
iOS location APIs: https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/LocationAwarenessPG/CoreLocation/CoreLocation.html

**Comment by eseidelGoogle** [comment]
No longer in scope for the hackathon.

**Comment by edelvalle** [comment]
There is right now a simple way to ask for the last known location in Android:

```
import 'dart:jni';


final Context = Java.getClass('android.content.Context');
final LocationManager = Java.getClass('android.location.LocationManager');


getLastLocation() {
    final context = new JavaObject(JniApi.getApplicationContext());
    final locationManager = context.getSystemService(Context.LOCATION_SERVICE);

    return locationManager.getLastKnownLocation(
      LocationManager.PASSIVE_PROVIDER
    );
}
```

Is there an easy way to get location udpates? Because I can not create a LocationListener from Dart and pass it to Java. :cry:

**Comment by a14n** [comment]
It is possible to [access Plateform Services](https://flutter.io/platform-services/) to request location updates. I made a little demo available at https://github.com/a14n/flutter-geolocation-demo that shows how to do that. See the [Android code](https://github.com/a14n/flutter-geolocation-demo/blob/master/android/app/src/main/java/a14n/geolocationdemo/MainActivity.java#L47-L80) that forwards locations to the [flutter part](https://github.com/a14n/flutter-geolocation-demo/blob/master/lib/main.dart#L24-L45).

**Comment by sethladd** [comment]
My understanding is that our strategy is to build out a plugin/interop layer, and then use that to allow the ecosystem (flutter team? developers?) to build a Geolocation service.

I'm going to close this issue in the meantime. However, ensuring GPS/Geolocation _can_ be exposed via plugins/interop is on the radar and important. We're just unlikely to deliver this specific API directly as part of Flutter.

**Comment by paolosoares** [comment]
This blocks customer:mulligan, as it requires the current/last location for a critical user flow.

**Comment by Hixie** [comment]
When doing this, consider writing #1432 at the same time.

**Comment by sethladd** [comment]
I'd like for us to consider making this a first party plugin. 

Cc @mit-mit

**Comment by mit-mit** [comment]
There is an initial, community-driver, location plugin here now: https://pub.dartlang.org/packages/location

**Comment by sethladd** [comment]
Going to close this now, as https://github.com/Lyokone/flutterlocation exists and it appears to work on iOS and Android. We can reopen if we need to, but for now, please use https://github.com/Lyokone/flutterlocation

**Comment by eliashdezr** [comment]
@sethladd 
That plugin is not longer maintained. Issues hasn't been resolved since last year.

**Comment by sethladd** [comment]
Thanks for the head's up! I'll reopen, to signal that the ecosystem is still searching for a geolocation plugin for Flutter.

**Comment by gorjan-mishevski** [comment]
Indeed we need. That plugin throws deprecated warnings and it doesn't work on iOS. I have no idea how I can implement geolocations. :(

**Comment by lukaspili** [comment]
We will need this for a new project starting soon.
If nothing good is available by the time we need it, we can do it (supporting both iOS and Android).

**Comment by gorjan-mishevski** [comment]
@lukaspili I would definitely be interested if you are open sourcing!

**Comment by twick00** [comment]
Absolutely interested in this, would help with it but I'm not sure where to start.

**Comment by lukaspili** [comment]
I will open source it once we have the core feature ready for ios&android, so people can build on top.
Starting the plugin development next week.

**Comment by acidjazz** [comment]
@twick00 can you elaborate on what exactly isn't working? There are others saying it works fine for them.

**Comment by Mistic92** [comment]
I checked few libs for geolocalisation and none of them is working :( 
https://github.com/Gustash/flutter_geolocation
https://pub.dartlang.org/packages/location

[√] Flutter (Channel dev, v0.2.4, on Microsoft Windows [Version 10.0.16299.309], locale pl-PL)

**Comment by haydenflinner** [comment]
Same here @Mistic92. Here's hoping @lukaspili finds time to pull through!

**Comment by gerryhigh** [comment]
I've gotten this to work on Android https://github.com/Gustash/flutter_geolocation but it fails to compile on iOS.

**Comment by Mistic92** [comment]
@gerryhigh What version and channel do you use? 

For me I'm getting 

```
[ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
                                                                           Malformed type.
                                                                           #0      AppViewState._checkUserLocation (package:mobile_flutter/appPage.dart)
                                                                           <asynchronous suspension>
                                                                           #1      AppViewState.initState (package:mobile_flutter/appPage.dart:49:5)
                                                                           #2      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3734:58)
                                                                           #3      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
```

**Comment by gerryhigh** [comment]
I'm on the beta channel. but now I have it working on both iOS and Android. On iOS I made a change to the podfile per this PR https://github.com/flutter/flutter/pull/15437/files#diff-519f1341a7393048261b00690f7c2c0eR70

My version info: 
Flutter 0.2.3 • channel beta • https://github.com/flutter/flutter.git
Framework • revision 5a58b36e36 (2 weeks ago) • 2018-03-13 13:20:13 -0700
Engine • revision e61bb9ac3a
Tools • Dart 2.0.0-dev.35.flutter-290c576264

**Comment by lukaspili** [comment]
Quick update on our location plugin for iOS and android: 
It's working great in our app, and I'm confident I will be able to extract and release the first public version tomorrow. 

It will feature at least single and continuous location requests. More features (geocoding, geofence, stream api) are planned and will come next week, along our app development. More info tomorrow.

**Comment by lukaspili** [comment]
First version is available: https://github.com/loup-v/geolocation

**Comment by Hixie** [comment]
cc @mravn-google

**Comment by Asoseil** [comment]
@lukaspili i have a build error with firebase and geolocation plugin, maybe a dependencies problem

**Comment by martijn00** [comment]
As @mit-mit pointed out we made a new Geolocation plugin, which is available at https://github.com/BaseflowIT/flutter-geolocator. If there is any feature missing or you encounter a bug, fill out an issue in the repo and we'll take a look as soon as possible!

We aim to make this the default go-to plugin for geolocation, including all requested features, and having a great documentation.

**Comment by mit-mit** [comment]
Thanks much @martijn00; I'm going to close this tracking issue with the assumption that this is now covered.

**Comment by NikhilJogdand** [comment]
How to turn on GPS on flutter ?
