### ISSUE TITLE
Questions about using webview_flutter: 4.0.4 plugin

### ISSUE THREAD

**Issue by WFCN** [flutter/flutter#121081]
When I use the method setCookie of WebViewCookieManager (WebViewCookie (name: 'xxx', value: 'yyy', domain: 'test. com')) to implement on the Android platform, the specific form is

`

     @override

     Future<void> setCookie(WebViewCookie cookie) {

     if (!_isValidPath(cookie.path)) {

     throw ArgumentError(

      'The path property for the provided cookie was not given a legal value.');

      }

     return _ cookieManager.setCookie(

     cookie.domain,

      '${Uri.encodeComponent(cookie.name)}=${Uri.encodeComponent(cookie.value)}; path=${cookie.path}',

      );

     }

`

Why not return the use of Uri. encodeComponent() to the caller,

The problem I currently face is that we want to pass the value to the cookie intact instead of Uri encodeComponent()

**Comment by exaby73** [comment]
Hello @WFCN. You can pass the `WebViewCookie` directly into `WebViewCookieManager.setCookie`. See https://pub.dev/documentation/webview_flutter/latest/webview_flutter/WebViewCookieManager/setCookie.html. In fact, there isn't any method that has `String`s as inputs. How are you setting the cookie in the first place?

**Comment by WFCN** [comment]
> 

thank  your  replay 

i used this method set cookies  before load url

`

    WebViewCookieManager cookieManager = WebViewCookieManager()

    await _cookieManager.setCookie(
      WebViewCookie(
        name: 'testKey',
        value:'testValue',
        domain: domain,
      ),
    );

`
 I checked the source code implementation on the Android platform ,like  this

     class  AndroidWebViewCookieManager
 
     @override

     Future<void> setCookie(WebViewCookie cookie) {

     if (!_isValidPath(cookie.path)) {

     throw ArgumentError(

      'The path property for the provided cookie was not given a legal value.');

      }

     return _ cookieManager.setCookie(

     cookie.domain,

      '${Uri.encodeComponent(cookie.name)}=${Uri.encodeComponent(cookie.value)}; path=${cookie.path}',

      );

     }

The source code will encode the testKey and testValue, which is good in some cases, but if there are symbols to be reserved in the testValue, such as'+'' | ', and some parts have been encoded, such as

`E4% BD% A0% E5% A5% BD% 20% 20hello | word | hello+flutter` 

so  i think  return the use of Uri. encodeComponent() to the caller,

**Comment by exaby73** [comment]
You can use [`Uri.encodeComponent`](https://api.dart.dev/stable/2.19.2/dart-core/Uri/encodeComponent.html) yourself if you need the encoded value. I don't see a valid use case to return the encoded value since you can already do that. For this reason, I will close this issue. Thank you
