### ISSUE TITLE
iPhone X: Additional horizontal inset for list view content in horizontal layouts

### ISSUE THREAD

**Issue by cbracken** [flutter/flutter#12101]
## Steps to Reproduce

On the iPhone X, List views in horizontal mode should include additional horizontal padding on either side to avoid drawing list content under the sensor housing notch.

See Apple's [Human Interface Guidelines for iPhone X](https://developer.apple.com/ios/human-interface-guidelines/overview/iphone-x).

Dependent on issue #12098

Example from Flutter Gallery:
![screen shot 2017-09-12 at 15 14 58](https://user-images.githubusercontent.com/351029/30454818-826a0d0e-9952-11e7-8afd-c5b8fda0c199.png)

## Flutter Doctor

```
[✓] Flutter (on Mac OS X 10.12.6 16G29, locale en-AU, channel master)
    • Flutter at /Users/cbracken/src/flutter/flutter
    • Framework revision dd7e313317 (51 minutes ago), 2017-09-14 12:28:21 -0700
    • Engine revision 57a1445a45
    • Tools Dart version 1.25.0-dev.11.0

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at /Users/cbracken/Library/Android/sdk
    • Platform android-25, build-tools 25.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 9.0)
    • Xcode at /Applications/Xcode9.0.app/Contents/Developer
    • Xcode 9.0, Build version 9A235
    • ios-deploy 1.9.2
    • CocoaPods version 1.3.1
```

**Comment by Hixie** [comment]
This isn't about list views. The same is true for any content.

We should probably just have the Scaffold automatically indent its body appropriately (using MediaQuery.of(padding), and updating the padding on the inside accordingly, see https://github.com/flutter/flutter/issues/12084), with a parameter to override that in case you want something else to take care of it.

**Comment by cbracken** [comment]
It's not strictly about any content -- e.g. much full-screen content such as images should not be inset, but it's definitely more general than list/grid views.

**Comment by cbracken** [comment]
ListTile and the gallery home screen done in #13545.
