### ISSUE TITLE
Styles for enums in dartdocs are missing some bold

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#121022]
Compare:
* https://master-api.flutter.dev/flutter/dart-ui/PointerDeviceKind.html
* https://api.dart.dev/stable/2.19.2/dart-io/HttpClientResponseCompressionState.html

The enums in the Flutter docs aren't bold, so it all blends in.

I'm not sure where the styles are coming from, but the problem seems to be that the Flutter docs use `Roboto Mono` for the enum name (which I agree is better than the non-mono version in the Dart docs) but font-weight 500 is not heavy enough in Mono to stand out. Changing it to 900 seems to work well. Just not sure where to do that. :-)

**Comment by exaby73** [comment]
## Triage report

I can see this issue on the master docs (`Flutter 3.8.0-14.0.pre.2 • 2023-02-19 21:57 • cc9b198213 • master`)

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/50555895/220056278-9ff71aa4-77c6-42ee-85ee-66760483cd16.png)

</details>

**Comment by dam-ease** [comment]
I can see this issue in the docs.

<details><summary>Screenshot</summary>
<p>

<img width="798" alt="Screenshot 2023-08-16 at 14 28 00" src="https://github.com/flutter/flutter/assets/53122008/53aa258c-e817-429b-9cb0-8c731cee5d67">


</p>
</details>

**Comment by huycozy** [comment]
Updating on `master 3.14.0-14.0.pre.356`:

- PointerDeviceKind enums are bold (fixed) ✅:
  <details>
  <summary>Demo</summary>
  
  <img width="400" src="https://github.com/flutter/flutter/assets/104349824/7ea399b0-0f03-48dc-ab78-eb1135b44cdf">
  
  </details>

- HttpClientResponseCompressionState enums are not bold on `2.19.2`❗:

  <details>
  <summary>Demo</summary>
  
  <img width="400" src="https://github.com/flutter/flutter/assets/104349824/c3a52454-58cb-4759-961f-e048467512af">
  
  </details>


- HttpClientResponseCompressionState enums are bold on `master` ✅: https://master-api.flutter.dev/flutter/dart-io/HttpClientResponseCompressionState.html

  <details>
  <summary>Demo</summary>
  
  <img width="400" src="https://github.com/flutter/flutter/assets/104349824/0dbbc5f0-7acb-4f8d-a383-d94e0f530728">

  </details>

Closing the issue as fixed on master API doc.
