### ISSUE TITLE
Unused variable in the example of FilterChip.

### ISSUE THREAD

**Issue by your-diary** [flutter/flutter#121028]
While reading [the official documentation of `FilterChip`](https://api.flutter.dev/flutter/material/FilterChip-class.html), I found an unused variable in the example: `bool favorite = false;`.

I don't tell if this variable is actually needed (e.g. injection or reflection purpose in test phase), so I'm posting this as an issue rather than a pull request.

location: [examples/api/lib/material/filter_chip/filter_chip.0.dart](https://github.com/flutter/flutter/blob/9944297138845a94256f1cf37beb88ff9a8e811a/examples/api/lib/material/filter_chip/filter_chip.0.dart#L33)

**Comment by TahaTesser** [comment]
Good catch!
