### ISSUE TITLE
Is there any usage information for each version of Flutter SDK?

### ISSUE THREAD

**Issue by littleGnAl** [flutter/flutter#121031]
The SDK we develop needs to be compatible with Flutter SDK 2.x. Is there any usage information for each version of Flutter SDK so that we can judge whether we can update the minimum supported Flutter SDK.

**Comment by exaby73** [comment]
Hello @littleGnAl. Flutter has [release notes](https://docs.flutter.dev/development/tools/sdk/release-notes) for each non-patch versions, and [breaking changes](https://docs.flutter.dev/release/breaking-changes) across these versions.

Maintaining documentation for old versions of Flutter is currently not supported :) Though, I think your IDE is your best tool here with the linter telling you what works and what doesn't.

My recommendation is that you do upgrade to newer versions of Flutter. The SDK not being backwards compatible might be a good thing for your users if they have to upgrade their Flutter version to use it, as new Flutter versions provide not only great new features, but also fixes a lot of bugs, some of them quite critical.

I know it's not ideal, but unfortunately, there's nothing we can do currently :) Therefore, I will close this issue. Thank you
