### ISSUE TITLE
shared_preferences :shared_preferences_android:extractDebugAnnotations

### ISSUE THREAD

**Issue by kazemini** [flutter/flutter#121080]
Hi. pls help me, i tried all the way that you think,

my flutter ver is 3.7.1 stable
flutter pub cache repair
flutter clean
flutter doctor is okay
read all issues similar
Seven days of my life were spent testing different ways, but  still get this error

my app runs perfectly without this package, but i need it ;-)

![shared_preferences ](https://user-images.githubusercontent.com/80615458/220048152-91b902af-b659-422b-82e8-d223970b5af2.png)

**Comment by exaby73** [comment]
Hello @kazemini. Thank you for filing this issue. Can you please provide the following information?

- A [complete and minimal, reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example). Ideally, a single `main.dart` file that can be run directly.
- The output of `flutter doctor -v`
- The output of `flutter run -v`

Please provide the information in the form of text. See how to make collapsible sections with Markdown [here](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-collapsed-sections).

**Comment by kazemini** [comment]
> Hello @kazemini. Thank you for filing this issue. Can you please provide the following information?
> 
>     * A [complete and minimal, reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example). Ideally, a single `main.dart` file that can be run directly.
> 
>     * The output of `flutter doctor -v`
> 
>     * The output of `flutter run -v`
> 
> 
> Please provide the information in the form of text. See how to make collapsible sections with Markdown [here](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-collapsed-sections).

**thank you!**
A series of requirements were downloaded through this command `flutter run -v`

you can see my repository [here](https://github.com/kazemini/template) & share your feedback

**Comment by exaby73** [comment]
Hello @kazemini. Was closing this issue intentional? Could you try reproducing this issue in a newly generated Flutter project?

**Comment by kazemini** [comment]
> Hello @kazemini. Was closing this issue intentional? Could you try reproducing this issue in a newly generated Flutter project?

Thanks 🙏, Problem solved with command 
```
Flutter run -v
```

**Comment by kazemini** [comment]
[t: gradle](https://github.com/flutter/flutter/labels/t%3A%20gradle)
