### ISSUE TITLE
when the native page is mixed with Flutter, hide the native tabbar on the push new page , the flutter page will be stretched during the transition to hide the tabbar animation。

### ISSUE THREAD

**Issue by zeqinjie** [flutter/flutter#121078]
when the native page is mixed with Flutter, hide the native tabbar on the push new page , the flutter page will be stretched during the transition to hide the tabbar animation。

<details>
<summary> native </summary>

```swift
channel!.setMethodCallHandler { (call: FlutterMethodCall, result: @escaping FlutterResult) in
  if call.method == "countChange" {
      if let value = call.arguments as? Int{
          print("countChange ===> \(value)")
          self.tabBarController?.setTabBarHidden(value != 0, animated: true)
      }
      result(nil)
  } else {
      result(FlutterMethodNotImplemented)
  }
}

func setTabBarHidden(_ hidden: Bool, animated: Bool) {
    guard let vc = selectedViewController else { return }
    guard tabBarHidden != hidden else { return }
    
    let frame = self.tabBar.frame
    let height = frame.size.height
    let offsetY = hidden ? height : -height

    UIViewPropertyAnimator(duration: animated ? 0.3 : 0, curve: .easeOut) {
        self.tabBar.frame = self.tabBar.frame.offsetBy(dx: 0, dy: offsetY)
        self.selectedViewController?.view.frame = CGRect(
            x: 0,
            y: 0,
            width: vc.view.frame.width,
            height: vc.view.frame.height + offsetY
        )
        
        self.view.setNeedsDisplay()
        self.view.layoutIfNeeded()
    }
    .startAnimation()
}
```
</details>

<details>
<summary> flutter </summary>

```dart
 _channel.invokeMethod<void>("countChange", ShareModel.shared.count);
```
</details>

![Simulator Screen Recording - iPhone 14 Pro - 2023-02-20 at 14 51 58](https://user-images.githubusercontent.com/8444646/220036184-fb3470f4-6078-4b05-a1dd-c75aef856634.gif)

[demo.zip](https://github.com/flutter/flutter/files/10780530/demo.zip)

**Comment by huycozy** [comment]
@zeqinjie Thanks for the report with the complete sample code. But as far as I can see, the image doesn't seem to be stretched. Perhaps it is an optical effect when there is animation transition.

Verifying on the latest Flutter stable `3.7.3`, `iPhone 7, iOS 15.7.2`.

Can you take screenshots and confirm again?

| Tabbar | No Tabbar |
| --------------- | --------------- |
<img width="400" src="https://user-images.githubusercontent.com/104349824/220124607-e0e6cc3b-f8de-4bc2-a476-5072a7c671ed.png"> | <img width="400" src="https://user-images.githubusercontent.com/104349824/220124636-d6231938-3cd2-4acd-9165-aa48f2cc1ecf.png">

**Comment by zeqinjie** [comment]
@huycozy ok thx
