### ISSUE TITLE
[Impeller] Use API validation for tests.

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#121017]
In https://github.com/flutter/flutter/issues/121015 I found a crash related to "API validation" checks.  We should make sure that we are running our impeller integration tests with API Validation turned on.

Here are the [environment for shader validation](https://developer.apple.com/documentation/metal/diagnosing_metal_programming_issues_early?language=objc).  We do have these turned on in `run_tests.py`, but I'm not sure what the one is for API validation.

**Comment by chinmaygarde** [comment]
We were using the [guidance in this doc for API validation](https://github.com/flutter/engine/blob/main/impeller/docs/metal_validation.md) but that was based on reverse engineering what Xcode does. After updating to Ventura, the steps stopped working.

**Comment by gaaclarke** [comment]
Executing the following program with metal validation on shows us the correct environment variables:

code:
```c
#include <stdio.h>
#include <stdlib.h>

int main(int argc, char *argv[], char * envp[])
{
    int i;
    for (i = 0; envp[i] != NULL; i++)
        printf("\n%s", envp[i]);
    getchar();
    return 0;
}

```

environment variables:
```
METAL_DEVICE_WRAPPER_TYPE=1
METAL_DEBUG_ERROR_MODE=0
```
