### ISSUE TITLE
TextField: delete key is ignored when using FocusNode

### ISSUE THREAD

**Issue by SuricateTrading** [flutter/flutter#121092]
When using the folowing TextField in a Windows application, it is only possible to write text, but you can't delete text.

`TextField(focusNode: FocusNode(onKeyEvent: (node, event) => KeyEventResult.skipRemainingHandlers))`

Works on Web! But not on Windows desktop application.

When using `KeyEventResult.handled`, I can't write text at all.

**Comment by huycozy** [comment]
@SuricateTrading I can see macOS app still works when using `skipRemainingHandlers`. Does it produce any error from the console? 

Also, please provide the output of `flutter doctor -v` as well. Thanks!

**Comment by SuricateTrading** [comment]
No errors in the console.

<details>
<summary>Here is my flutter doc:</summary>


Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.7.3, on Microsoft Windows [Version 10.0.19044.2486], locale de-DE)
[X] Windows Version (Unable to confirm if installed Windows version is 10 or greater)         
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)              
    X cmdline-tools component is missing                                                      
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`                               
      See https://developer.android.com/studio/command-line for more details.                 
    X Android license status unknown.                                                         
      Run `flutter doctor --android-licenses` to accept the SDK licenses.                     
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[√] Chrome - develop for the web                                                              
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.5)                
[√] Android Studio (version 4.1)                                              
[√] IntelliJ IDEA Community Edition (version 2022.3)                          
[√] VS Code (version 1.63.2)                                                  
[√] Connected device (3 available)                                            
    ! Device ce0218221c9b483104 is offline.                                   
[√] HTTP Host Availability                                                    
                                                                              
! Doctor found issues in 2 categories.   
</details>

**Comment by huycozy** [comment]
@SuricateTrading Thanks for your response but I see there's an open issue addressing the case you described #93873.

Closing this issue as a duplicate, so please follow up on it for further updates. You can leave there your comment and react an upvote to the original comment will help to raise the issue. Thank you!
