### ISSUE TITLE
RenderBox was not laid out, Failed assertion: line 2009 pos 12: 'hasSize'

### ISSUE THREAD

**Issue by savadodesigns** [flutter/flutter#121042]
What's going wrong with this layout?

## Steps to Reproduce

1. Execute `flutter run` on the code sample
2. Navigate to different route
3. Exception caught by rendering library

<details>
  <summary>Error</summary>
RenderBox was not laid out: RenderFractionalTranslation#e77c2 NEEDS-LAYOUT NEEDS-PAINT
'package:flutter/src/rendering/box.dart':
Failed assertion: line 2009 pos 12: 'hasSize'
</details>

<details>
<summary>Code sample</summary>

```
return Scaffold(
  body: Column(
    children: [
      const SafeArea(
        bottom: false,
        child: HeaderBar(),
      ),
      Expanded(
        child: SingleChildScrollView(
          controller: keys['page_scroll'] ??= ScrollController(),
          child: Container(
            padding: EdgeInsets.symmetric(
              horizontal: pagePadding / 2,
            ),
            constraints: BoxConstraints(
              maxWidth: maxWidth + pagePadding * 2,
            ),
            child: IntrinsicHeight(
              child: child,
            ),
          ),
        ),
      ),
    ],
  ),
);
```

</details>

**Comment by TahaTesser** [comment]
Hi @savadodesigns 
Can you please provide a complete runnable code sample? 
Thank you

**Comment by savadodesigns** [comment]
Hi @TahaTesser Of course that turns out to be nearly impossible. Can you think of any reason that the Scaffold fails when navigating to a new route (let's say from '/' to '/zone/:zoneid'), but on reload everything is okay? It looks like there's some trouble in the in-between time.

**Comment by savadodesigns** [comment]
Hi @TahaTesser I've found out it has something to do with using the `flutter_slidable` package. Using a Slidable() around a list of ListTiles apparently breaks stuff.

**Comment by savadodesigns** [comment]
Hi @TahaTesser this is really annoying, the problem returned, without the use of Slidable() widgets.

It seems it has something to do with RenderInkFeatures?

Full error:

======== Exception caught by rendering library =====================================================
The following assertion was thrown during paint():
Assertion failed: file:///Users/samvandoorn/Projects/flutter/packages/flutter/lib/src/rendering/box.dart:2009:12
hasSize
"RenderBox was not laid out: RenderPadding#d7c62 NEEDS-LAYOUT NEEDS-PAINT"

The relevant error-causing widget was: 
  Scaffold-[LabeledGlobalKey<ScaffoldState>#0fe73 SCAFFOLD] Scaffold:file:///Users/samvandoorn/Projects/clairify_routing/lib/main.dart:796:12
When the exception was thrown, this was the stack: 
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 266:49      throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 29:3        assertFailed
packages/flutter/src/rendering/box.dart 2009:12                                   get size
packages/flutter/src/material/ink_decoration.dart 397:26                          paintFeature
packages/flutter/src/material/material.dart 759:5                                 [_paint]
packages/flutter/src/material/material.dart 649:19                                paint
packages/flutter/src/rendering/object.dart 2853:7                                 [_paintWithContext]
packages/flutter/src/rendering/object.dart 253:12                                 paintChild
packages/flutter/src/rendering/proxy_box.dart 144:14                              paint
packages/flutter/src/rendering/proxy_box.dart 2110:15                             <fn>
packages/flutter/src/rendering/object.dart 564:14                                 pushClipRRect
packages/flutter/src/rendering/proxy_box.dart 2097:20                             paint
packages/flutter/src/rendering/object.dart 2853:7                                 [_paintWithContext]
packages/flutter/src/rendering/object.dart 253:12                                 paintChild
packages/flutter/src/rendering/proxy_box.dart 144:14                              paint
packages/flutter/src/rendering/object.dart 2853:7                                 [_paintWithContext]
packages/flutter/src/rendering/object.dart 253:12                                 paintChild
packages/flutter/src/rendering/proxy_box.dart 144:14                              paint
packages/flutter/src/rendering/object.dart 2853:7                                 [_paintWithContext]
packages/flutter/src/rendering/object.dart 169:10                                 _repaintCompositedChild
packages/flutter/src/rendering/object.dart 112:5                                  repaintCompositedChild
packages/flutter/src/rendering/object.dart 1137:31                                flushPaint
packages/flutter/src/rendering/binding.dart 518:19                                drawFrame
packages/flutter/src/widgets/binding.dart 865:13                                  drawFrame
packages/flutter/src/rendering/binding.dart 381:5                                 [_handlePersistentFrameCallback]
packages/flutter/src/scheduler/binding.dart 1289:15                               [_invokeFrameCallback]
packages/flutter/src/scheduler/binding.dart 1218:9                                handleDrawFrame
packages/flutter/src/scheduler/binding.dart 1076:5                                [_handleDrawFrame]
lib/_engine/engine/platform_dispatcher.dart 1168:13                               invoke
lib/_engine/engine/platform_dispatcher.dart 218:5                                 invokeOnDrawFrame
lib/_engine/engine/initialization.dart 190:45                                     <fn>
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 367:37  _checkAndCall
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 372:39  dcall
The following RenderObject was being processed when the exception was fired: _RenderInkFeatures#72955
...  needs compositing
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(w=1200.0, h=983.0)
...  size: Size(1200.0, 983.0)
RenderObject: _RenderInkFeatures#72955
  needs compositing
  parentData: <none> (can use size)
  constraints: BoxConstraints(w=1200.0, h=983.0)
  size: Size(1200.0, 983.0)
...  child: RenderCustomMultiChildLayoutBox#dcb77 NEEDS-PAINT
...    needs compositing
...    parentData: <none> (can use size)
...    constraints: BoxConstraints(w=1200.0, h=983.0)
...    size: Size(1200.0, 983.0)
...    child 1: RenderFlex#a3790 relayoutBoundary=up1 NEEDS-PAINT
...      needs compositing
...      parentData: offset=Offset(0.0, 0.0); id=_ScaffoldSlot.body (can use size)
...      constraints: BoxConstraints(0.0<=w<=1200.0, 0.0<=h<=983.0)
...      size: Size(1200.0, 983.0)
...      direction: vertical
...      mainAxisAlignment: start
...      mainAxisSize: max
...      crossAxisAlignment: center
...      verticalDirection: down
...      child 1: RenderPadding#bfba8 relayoutBoundary=up2 NEEDS-PAINT
...        parentData: offset=Offset(0.0, 0.0); flex=null; fit=null (can use size)
...        constraints: BoxConstraints(0.0<=w<=1200.0, 0.0<=h<=Infinity)
...        size: Size(1200.0, 110.0)
...        padding: EdgeInsets.zero
...        textDirection: ltr
...        child: RenderPositionedBox#e08f6 relayoutBoundary=up3 NEEDS-PAINT
...          parentData: offset=Offset(0.0, 0.0) (can use size)
...          constraints: BoxConstraints(0.0<=w<=1200.0, 0.0<=h<=Infinity)
...          size: Size(1200.0, 110.0)
...          alignment: Alignment.center
...          textDirection: ltr
...          widthFactor: expand
...          heightFactor: expand
...      child 2: RenderRepaintBoundary#f5d1e relayoutBoundary=up2
...        needs compositing
...        parentData: offset=Offset(0.0, 110.0); flex=1; fit=FlexFit.tight (can use size)
...        constraints: BoxConstraints(0.0<=w<=1200.0, h=873.0)
...        layer: OffsetLayer#09aeb DETACHED
...          engine layer: OffsetEngineLayer#f4d0e
...          handles: 1
...          offset: Offset(0.0, 110.0)
...        size: Size(1200.0, 873.0)
...        metrics: 99.1% useful (1 bad vs 109 good)
...        diagnosis: this is an outstandingly useful repaint boundary and should definitely be kept
...        child: RenderPointerListener#35c2b relayoutBoundary=up3
...          needs compositing
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(0.0<=w<=1200.0, h=873.0)
...          size: Size(1200.0, 873.0)
...          behavior: deferToChild
...          listeners: signal
...    child 2: RenderStack#055ea relayoutBoundary=up1
...      parentData: offset=Offset(1184.0, 967.0); id=_ScaffoldSlot.floatingActionButton (can use size)
...      constraints: BoxConstraints(0.0<=w<=1200.0, 0.0<=h<=983.0)
...      size: Size(0.0, 0.0)
...      alignment: Alignment.centerRight
...      textDirection: ltr
...      fit: loose
...      child 1: RenderTransform#d7236 relayoutBoundary=up2
...        parentData: not positioned; offset=Offset(0.0, 0.0) (can use size)
...        constraints: BoxConstraints(0.0<=w<=1200.0, 0.0<=h<=983.0)
...        size: Size(0.0, 0.0)
...        transform matrix: [0] 0.0,0.0,0.0,0.0
[1] 0.0,0.0,0.0,0.0
[2] 0.0,0.0,1.0,0.0
[3] 0.0,0.0,0.0,1.0
...        origin: null
...        alignment: Alignment.center
...        textDirection: ltr
...        transformHitTests: true
...        child: RenderTransform#0c17d relayoutBoundary=up3 NEEDS-PAINT
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(0.0<=w<=1200.0, 0.0<=h<=983.0)
...          size: Size(0.0, 0.0)
...          transform matrix: [0] 0.7,0.7,0.0,0.0
[1] -0.7,0.7,0.0,0.0
[2] 0.0,0.0,1.0,0.0
[3] 0.0,0.0,0.0,1.0
...          origin: null
...          alignment: Alignment.center
...          textDirection: ltr
...          transformHitTests: true
...    child 3: RenderPointerListener#9a639
...      parentData: offset=Offset(0.0, 0.0); id=_ScaffoldSlot.statusBar (can use size)
...      constraints: BoxConstraints(w=1200.0, h=0.0)
...      size: Size(1200.0, 0.0)
...      behavior: opaque
...      listeners: down, panZoomStart
...    child 4: RenderConstrainedBox#7e49c
...      parentData: offset=Offset(0.0, 0.0); id=_ScaffoldSlot.endDrawer (can use size)
...      constraints: BoxConstraints(w=1200.0, h=983.0)
...      size: Size(1200.0, 983.0)
...      additionalConstraints: BoxConstraints(w=0.0, h=0.0)
====================================================================================================

**Comment by TahaTesser** [comment]
Hi @savadodesigns 

No worries, we need more information to get to the bottom of this issue

> It seems it has something to do with RenderInkFeatures?

It could be, Could you please provide a minimal runnable code sample to reproduce this?

**Comment by savadodesigns** [comment]
@TahaTesser It's very difficult to produce a minimal runnable code sample. Maybe I could give you access to the private repo?

**Comment by TahaTesser** [comment]
@savadodesigns 
Unfortunately, this requires a minimal code sample to eliminate any production code issues.

**Comment by savadodesigns** [comment]
@TahaTesser I'm not able to provide that. Could you explain what the error message means? This I driving me nuts...

**Comment by TahaTesser** [comment]
Hi @savadodesigns 
It's hard to bisect the issue without a minimal code sample.  I recommend you add the missing pieces in your original coe snippet and provide a complete reproducible sample.

**Comment by savadodesigns** [comment]
Hi @TahaTesser, I understand. There’s just too much going on in the production code. Somehow I managed to fix the issue, so I’ll close the ticket.
