### ISSUE TITLE
Android Native circular progress view animation problem

### ISSUE THREAD

**Issue by ttnka76** [flutter/flutter#121095]
I have an NativeView, widget, that implement an pdf rendering page with a circular native android progress that show the load percentage.
All works well, but the circular progress animation run only when the view is redraw, for example in an PDF multipage the circular progress animation run only when switch from page to other. I think if I implements a thread that ever few ms call the redraw
of view the circular progress animation works.

**Comment by exaby73** [comment]
Hello @ttnka76. Thank you for filing this issue. Can you please provide the following information?

- A [complete and minimal, reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example). Ideally, a public Github repository that has all the necessary files to reproduce the issue
- The output of `flutter doctor -v`

Please provide the information in the form of text. See how to make collapsible sections with Markdown [here](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-collapsed-sections).
