### ISSUE TITLE
The in_app_purchase package is not showing the available subscriptions. It is only showing the available products

### ISSUE THREAD

**Issue by jatin-web** [flutter/flutter#121027]
I have followed all the steps as shown in the in_app_purhcase package documentation. But I cannot see the available subscriptions. I can only see the available products. Please help me figure out, how to fix this.

**Comment by huycozy** [comment]
Hi @jatin-web 
Which `in_app_purchase ` version are you using now? And please try using [plugin sample code](https://github.com/flutter/plugins/tree/main/packages/in_app_purchase/in_app_purchase/example) and check if the subscriptions are shown or not.

**Comment by jatin-web** [comment]
Thanks @huycozy, but I can only see the auto-renewing subscriptions, not the prepaid ones. Is there any way to get the prepaid subscriptions as well?

**Comment by huycozy** [comment]
@jatin-web Thanks for the response. For the prepaid issue, I see there's an open issue https://github.com/flutter/flutter/issues/26331. Closing as a duplication, so please follow up on it for further updates.
