### ISSUE TITLE
Extract a 'routes table' type Navigator wrapper

### ISSUE THREAD

**Issue by xster** [flutter/flutter#12108]
The material app has some nice routing functionalities like taking in a route->builder map, having an easy way to wrap a navigator with an initial page widget etc.

It'll be useful in different places like CupertinoTab and CupertinoApp. 

Extract common logic (into a mixin perhaps).

**Comment by xster** [comment]
Oh, we can probably just rename cupertino/tab_view.dart to widgets/routing_table.dart since that's pretty much all that `CupertinoTabView` does.

**Comment by xster** [comment]
Unassigning myself. Feel free to merge into other larger bugs as needed.

**Comment by iapicca** [comment]
Hi @goderbauer  is this issue still meant to be open?

**Comment by goderbauer** [comment]
We are working on this, but it is not resolved yet.

**Comment by Hixie** [comment]
I'm going to close this one on the basis that the new Router API provides a mechanism that's general and is already extracted. We might want to do this for the old API too one day, but if so, we should do it when we have a need for it.
