### ISSUE TITLE
In addition  get the flutter SDK version in the code？

### ISSUE THREAD

**Issue by yimao009** [flutter/flutter#121084]
## Proposal

In addition to using the command line tool to get the flutter&dart version, is there an API to get the flutter SDK version in the code?

**Comment by yimao009** [comment]
有没有在代码中可以获取flutter 版本的方式呢？

**Comment by huycozy** [comment]
It seems your question is best suited for support channels like StackOverflow, so please ask the same there for solutions if any. 
For quick search results, please see these StackOverflow answers: https://stackoverflow.com/questions/60581350/how-to-get-dart-and-flutter-version-within-the-app

Closing for now. If you disagree, please write in the comments and I will reopen it.

**Comment by yimao009** [comment]
你奶奶的， 知不知道自己不知道啊。
