### ISSUE TITLE
Flutter 3.7.3 flutter build windows, But have no UI when I launch my_app.exe, and we can find the app process in Task manager. What's wrong?

### ISSUE THREAD

**Issue by someboody** [flutter/flutter#121151]
## Steps to Reproduce

I follow the desktop windows guide of [https://docs.flutter.dev/](https://docs.flutter.dev/) and create a new project, then, use `flutter build  windows` to generate a executable file `my_app.exe` in the folder of `build\windows\runner\Release`, I want click it open the app, but there is no UI, the icon of `my_app` can be found in Task manager. If use `flutter build windows --debug`, the `my_app.exe` in `build\windows\runner\Debug` can works. 

## Environment
my flutter version is 3.7.3, OS is Windows 10.  
`flutter doctor` get the following message:
```shell
Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel unknown, 3.7.3, on Microsoft Windows [版本 10.0.19044.2604], locale zh-CN)
    ! Flutter version 3.7.3 on channel unknown at C:\develop\flutter\stable
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at
      https://flutter.dev/docs/get-started/install.
    ! Unknown upstream repository.
      Reinstall Flutter by following instructions at https://flutter.dev/docs/get-started/install.
[X] Windows Version (Unable to confirm if installed Windows version is 10 or greater)
[!] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Enterprise 2019 16.11.24)
[√] Android Studio (version 2021.2)
[√] VS Code (version 1.75.1)
[√] Connected device (4 available)
[!] HTTP Host Availability
    X HTTP host "https://pub.dev/" is not reachable. Reason: An error occurred while checking the HTTP host: Connection
      terminated during handshake

! Doctor found issues in 5 categories.
```

**Comment by huycozy** [comment]
Hi @someboody 
Is there any warning/error log from the console that you can notice? 
Also, can you try to check:
- Retry on the release build if it also happens?
- Resizing the window app to see if the widgets can be shown?
- Retry on the latest master channel:
```
flutter channel master
flutter upgrade
```

Thank you!

**Comment by zhkkjun** [comment]
This seems to be an issue, this release version can not run in Windows 10, you can download version [3.3.10](https://storage.flutter-io.cn/flutter_infra_release/releases/stable/windows/flutter_windows_3.3.10-stable.zip), this version is no problem.
I see there's some open issues addressing the case you described：#119808 #119415

**Comment by someboody** [comment]
@huycozy I tried with version 3.7.3, 3.7.4, the same problem happend. build debug exe file can works but release exe cannot. I tried version 3.3.10 (as @zhkkjun commented) ,it works. It seems bo be the same problem with #119415 , Thanks @zhkkjun @huycozy
