### ISSUE TITLE
PR did not run `Linux Android clang-tidy` though the python file change matched the `runIf` pattern

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#121160]
https://github.com/flutter/engine/pull/35707 changed a `.py` file, but `Linux Android clang-tidy` did not run in presubmit even though that builder has a `runIf` `- "**.py"` pattern:

https://github.com/flutter/engine/blob/3aa112c75ccba5a6064f45243e6cd84ddf220357/.ci.yaml#L243-L254

Lint errors weren't caught in presubmit, so the PR was reverted.
Why didn't the builder run in presubmit: https://github.com/flutter/engine/pull/35707/checks
Is something malformed in the .ci.yaml?

@godofredoc

**Comment by godofredoc** [comment]
Fixed with https://github.com/flutter/engine/pull/39736

**Comment by jmagman** [comment]
Hm, according to the ci.yaml the python scripts _should_ have run in `Linux Android clang-tidy` and the comment says this is because it's the fastest builder "Run pylint on the fastest clang-tidy builder."

https://github.com/flutter/engine/blob/3aa112c75ccba5a6064f45243e6cd84ddf220357/.ci.yaml#L254

So why didn't that builder run in https://github.com/flutter/engine/pull/35707?  https://github.com/flutter/engine/pull/39736  adds it to `Linux Host clang-tidy` which would make it run twice per commit?

@XilaiZhang

**Comment by jmagman** [comment]
For example, neither clang tidy builder was scheduled in https://github.com/flutter/engine/pull/39920/checks

**Comment by godofredoc** [comment]
Fixed, confirmed with https://github.com/flutter/engine/pull/39928/checks

**Comment by jmagman** [comment]
Thanks @godofredoc! Fix was really https://github.com/flutter/cocoon/pull/2506.  Am reverting the `Linux Host clang-tidy` builder `runIf` https://github.com/flutter/engine/pull/39930
