### ISSUE TITLE
InputChip doesn't get (focus)highlighted once its backgroundColor is manually set.

### ISSUE THREAD

**Issue by shrey112710** [flutter/flutter#121150]
## Steps to Reproduce

1. Run [this DartPad code](https://dartpad.dev/?id=6a8fc70c630120dda9bf00263a29c7c4)
2. Start tab-traversal by pressing the `tab` key. 

### Actual Result
Except for the first [`InputChip`](https://api.flutter.dev/flutter/material/InputChip-class.html), whose `backgroundColor` is set manually, all input chip's delete button is highlighted when they receive focus.

### Expected Result
All input chip's delete icons should be highlighted when they receive focus irrespective of whether the `backgroundColor` is set or not.

**Comment by huycozy** [comment]
@shrey112710 It does work actually. You can try setting `backgroundColor: Colors.red.withOpacity(0.3)` to see its highlighted color.

<img width="716" alt="Screenshot 2023-02-22 at 11 17 54" src="https://user-images.githubusercontent.com/104349824/220575938-9d374f1c-fd8b-47fc-8d59-ea24949469fb.png">

But it's not a good approach I think. Instead, I think it can be fixed once https://github.com/flutter/flutter/issues/73215 lands. You can take a look at that issue and leave a comment for your case will help to raise the issue.

Closing this issue in favor of #73215, so please follow up on it for further updates. Thanks!
