### ISSUE TITLE
[camerax] Implement onCameraClosing

### ISSUE THREAD

**Issue by camsim99** [flutter/flutter#121162]
In the Flutter camera plugin API, the `onCameraClosing` callback provides a way for developers to know when the camera they are using is closing. In CameraX, this maps to the point when there are no `UseCases` bound to the lifecycle controlled by the relevant `ProcessCameraProvider` instance. Using this fact, the `onCameraClosing` method needs to be implemented in the CameraX plugin.

**Comment by delfme** [comment]
Shouldnt this issue be filled on plugin’s page? https://github.com/yanshouwang/camerax

**Comment by camsim99** [comment]
> Shouldnt this issue be filled on plugin’s page? https://github.com/yanshouwang/camerax

@delfme No, this is for the [`camera_android_camerax` plugin](https://github.com/flutter/packages/tree/main/packages/camera/camera_android_camerax).
