### ISSUE TITLE
Xcode/VsCode build for iOS is too much slow

### ISSUE THREAD

**Issue by thapli9A** [flutter/flutter#121140]
Can we reopen this issue: https://github.com/flutter/flutter/issues/37582
I'm facing same in latest version. After removing firestore it's perfectly fine.

**Comment by darshankawar** [comment]
@thapli9A 
The issue you linked is very old so we recommend not to open that.
Check [this](https://github.com/firebase/flutterfire/issues/9393) issue and see if it helps in your case.
