### ISSUE TITLE
Unable to create a flutter build

### ISSUE THREAD

**Issue by bilalgodesto** [flutter/flutter#121103]
## Steps to Reproduce

1. Create new applicatin `flutter create .`
2. . Copied the packages 

<details>
<summary>Packages</summary>
  ```  
  cupertino_icons: ^1.0.2 
  firebase_core: ^2.6.1
  path_provider: ^2.0.2
  firebase_auth: ^4.2.8
  googleapis_auth: ^1.1.0
  cloud_firestore: ^4.4.2
  firebase_storage: ^11.0.13
  firebase_crashlytics: ^3.0.14
  firebase_messaging: ^14.2.4
  firebase_database: ^10.0.13
  flutter_app_badger: ^1.2.0
  provider: ^6.0.2
  image_picker: ^0.8.4
  vibration: ^1.7.3
  eraser: ^2.0.1
  multi_image_picker2: ^5.0.2
  wakelock: ^0.6.1+2
  the_apple_sign_in: ^1.1.1
  google_sign_in: ^5.0.1
  http: ^0.13.1
  shared_preferences: ^2.0.6
  photo_view: ^0.14.0
  simple_animations: ^5.0.0+3
  supercharged: ^2.1.1
  #google_maps_flutter: ^0.5.27+3
  google_maps_flutter: ^2.0.3
  audioplayers: ^3.0.1
  intl: ^0.17.0
  carousel_slider: ^4.0.0
  flutter_google_places_hoc081098: ^1.0.0-nullsafety.4
  google_maps_webservice: ^0.0.20-nullsafety.4
  location: ^4.1.1
  webview_flutter: ^4.0.2
  shape_of_view: ^1.0.2
  flutter_polyline_points: ^1.0.0
  flutter_widget_from_html: ^0.9.1
  cached_network_image: ^3.0.0
  social_share: ^2.0.4
  url_launcher: ^6.0.3
  sqflite: ^2.0.0+3
  strings: ^0.2.2
  flutter_share_me: ^1.2.0
  flutter_rating_bar: ^4.0.0
  dropdownfield: ^1.0.3
  confetti: ^0.7.0
  shimmer: ^2.0.0
  country_code_picker: ^2.0.2
  geolocator: ^9.0.2
  pinch_zoom_image_last: ^0.4.1
  adaptive_dialog: ^1.5.0+1
  rflutter_alert: ^2.0.4
  badges: ^3.0.2
  async: ^2.4.2
  country_currency_pickers: ^2.0.0
  bubble: ^1.1.9+1
  flutter_sound: ^9.1.9
  video_player: ^2.2.0
  permission_handler: ^10.2.0
  animated_widgets: ^1.1.0

  #camera: ^0.9.2+2
  camera: ^0.10.3
  page_transition: ^2.0.5
  sliding_up_panel: ^2.0.0+1
  dio: ^5.0.0

  chewie: ^1.0.0
  video_compress: ^3.1.0
  flutter_easyloading: ^3.0.0
  video_thumbnail: ^0.5.0
  #flutter_image_compress: ^0.7.0
  flutter_image_compress: ^1.0.0
  #flutter_phone_direct_caller: ^1.0.1
  flutter_phone_direct_caller: ^2.0.0
  platform_device_id: ^1.0.1
  #flutter_stripe: ^1.0.2
  flutter_stripe: ^8.0.0+1
  image_cropper: ^3.0.1
  hive: ^2.0.4
  hive_flutter: ^1.0.0
  uuid: ^3.0.4
  #add_2_calendar: ^2.1.2
  
  flutter_ringtone_player: ^3.2.0

 
  socket_io_client: ^2.0.0-beta.3-nullsafety.0
  auto_size_text: ^3.0.0

  
  easy_localization: ^3.0.0
  sign_in_with_apple: ^4.3.0
  flutter_local_notifications: ^13.0.0
  just_audio: ^0.9.20
  uni_links: ^0.5.1
  flutter_svg: ^1.0.3
  platform: ^3.1.0
  toast: ^0.3.0
  country_pickers: ^2.0.0
  progress_dialog_null_safe: ^1.0.7
  flutter_fadein: ^2.0.0 


</details>


**Expected results:** 

 Create build successfully.

**Actual results:** 

<details>
 <summary>Code sample</summary>
 ../../../flutter/packages/flutter/lib/src/widgets/editable_text.dart:572:3: Context: Found this candidate, but the arguments
    don't match.
      EditableText({
      ^^^^^^^^^^^^
    ../../../.pub-cache/hosted/pub.dartlang.org/macos_ui-1.10.0/lib/src/labels/tooltip.dart:170:47: Error: A value of type
    'OverlayState?' can't be assigned to a variable of type 'OverlayState' because 'OverlayState?' is nullable and 'OverlayState'
    isn't.
     - 'OverlayState' is from 'package:flutter/src/widgets/overlay.dart'
     ('../../../flutter/packages/flutter/lib/src/widgets/overlay.dart').
        final OverlayState overlayState = Overlay.of(
                                                  ^
    ../../../.pub-cache/hosted/pub.dartlang.org/macos_ui-1.10.0/lib/src/layout/sidebar/sidebar_items.dart:380:31: Error: Method
    'writeState' cannot be called on 'PageStorageBucket?' because it is potentially null.
     - 'PageStorageBucket' is from 'package:flutter/src/widgets/page_storage.dart'
     ('../../../flutter/packages/flutter/lib/src/widgets/page_storage.dart').
    Try calling using ?. instead.
          PageStorage.of(context).writeState(context, _isExpanded);

</details>


Finally, paste the output of running `flutter doctor -v` here.

```
[✓] Flutter (Channel stable, 3.3.9, on macOS 12.1 21C52 darwin-arm, locale en-GB)
    • Flutter version 3.3.9 on channel stable at /Users/bilalrabbi/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b8f7f1f986 (3 months ago), 2022-11-23 06:43:51 +0900
    • Engine revision 8f2221fbef
    • Dart version 2.18.5
    • DevTools version 2.15.0

Checking Android licenses is taking an unexpectedly long time...[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/bilalrabbi/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • ANDROID_HOME = /Users/bilalrabbi/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13C100
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.75.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.58.0

[✓] Connected device (3 available)
    • iPhone 12 (mobile) • 7C6BAF92-BF07-42B2-A865-516A805D5F50 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-2
      (simulator)
    • macOS (desktop)    • macos                                • darwin-arm64   • macOS 12.1 21C52 darwin-arm
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 110.0.5481.100

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by stuartmorgan** [comment]
These errors are from the `macos_ui` package; issues with third-party packages need to be reported to the developers of those packages.

**Comment by bilalgodesto** [comment]
There is no macos_ui package added in pubspec and mac desktop is already disabled

**Comment by stuartmorgan** [comment]
> There is no macos_ui package added in pubspec

It is part of your build, so something is depending on it. `dart pub deps` may be helpful if you want to figure out how to remove it.

> and mac desktop is already disabled

There is no mechanism to depend on packages only for certain platforms, so the platforms you are targeting won't change anything. All Dart code from all of your dependencies, direct or transitive, will be part of the compilation step, and errors in any of it will cause compilation to fail.
