### ISSUE TITLE
[in_app_purchases] queryPastPurchases returns empty list always

### ISSUE THREAD

**Issue by SEGVeenstra** [flutter/flutter#121134]
For our app users can get one-of-three subscriptions.
iOS handles this with the use of their Subscription Groups, but Android doesn't have that.
Instead we have to tell Android which subscription to replace with the new one.

However, the method provided by the package (`queryPastPurchases`) always returns an empty list.

- Android SDK 33
- in_app_purchase 3.1.4
- Flutter 3.3

## Steps to Reproduce

1. You'll need an app with multiple subscriptions setup
2. Purchase one subscription
3. Purchase the other subscription

**Expected results:** 
I expect that when purchasing the second subscription,  `queryPastPurchases` returns the first subscription.

**Actual results:** 
`queryPastPurchases` always returns an empty list

<details>
<summary>Code sample</summary>

```dart
if (Platform.isAndroid) {
        final androidAddition = iap.getPlatformAddition<InAppPurchaseAndroidPlatformAddition>();
        final oldPurchases = await androidAddition.queryPastPurchases(applicationUserName: identifier); // always empty!

        // There can only be one subscription active at a time.
        final currentSubscription = oldPurchases.pastPurchases.isNotEmpty ? oldPurchases.pastPurchases[0] : null;

        await iap.buyNonConsumable(
          purchaseParam: GooglePlayPurchaseParam(
            productDetails: productToBuy,
            applicationUserName: identifier,
            changeSubscriptionParam: currentSubscription != null
                ? ChangeSubscriptionParam(
                    oldPurchaseDetails: currentSubscription,
                    prorationMode: ProrationMode.immediateWithTimeProration,
                  )
                : null,
          ),
        );
      }
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
[✓] Flutter (Channel stable, 3.3.0, on macOS 13.2.1 22D68 darwin-x64, locale nl-NL)
    • Flutter version 3.3.0 on channel stable at /Users/seg/fvm/versions/3.3.0
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffccd96b62 (6 months ago), 2022-08-29 17:28:57 -0700
    • Engine revision 5e9e0e0aa8
    • Dart version 2.18.0
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc3)
    • Android SDK at /Users/seg/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code (version 1.75.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.58.0

[✓] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554                        • android-x64    • Android 13 (API 33) (emulator)
    • iPhone 14 Pro Max (mobile)   • E6DE2D30-E469-4F42-969E-BB4B95D41654 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-2 (simulator)
    • macOS (desktop)              • macos                                • darwin-x64     • macOS 13.2.1 22D68 darwin-x64
    • Chrome (web)                 • chrome                               • web-javascript • Google Chrome 110.0.5481.100

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by huycozy** [comment]
@SEGVeenstra Thanks for the detailed report. Can you check [this comment](https://github.com/flutter/flutter/issues/83342#issuecomment-850503066) if it works for you? (It also contains the migration snippet code)

**Comment by SEGVeenstra** [comment]
Hi @huycozy , thanks for the reply.

TBH that seems like a painful way to deal with this since the restore will not return the purchases itself but will push them on the stream.
This sounds like I have to always fire of the restore just to get the list and keep hold of them myself.

> Note there is an update coming soon (see PR https://github.com/flutter/plugins/pull/3944) that will make the queryPastPurchases method available again on Android devices.

this says an update was coming soon to re-enable it. But I cannot figure ou if it did or not, it has been 6mnths :/

**Comment by huycozy** [comment]
Hi @SEGVeenstra 
I think the PR has been merged and is available on `in_app_purchase_android: 0.1.1` (https://pub.dev/packages/in_app_purchase_android/changelog#011). Can you share your `pubspec.lock` to check the `in_app_purchase_android` version?

**Comment by SEGVeenstra** [comment]
```yaml
in_app_purchase_android:
    dependency: transitive
    description:
      name: in_app_purchase_android
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.2.3"
```

**Comment by huycozy** [comment]
I set the debug on `currentSubscription` and still can see the value of the previous purchase. Testing on `in_app_purchase: 3.1.5` and `in_app_purchase_android: 0.2.4+2`.

Can you retry on the latest plugin version and confirm? (You may try putting a debug point on `currentSubscription` or print the value and then check it as well)

**Comment by SEGVeenstra** [comment]
What class has the `currentSubscription` property?
I am using `queryPastPurchases` on `InAppPurchaseAndroidPlatformAddition`.

**Comment by huycozy** [comment]
>Ow, I assume you meant the currentSubscription in my code?

Yes

>Are you testing as a 'Licence tester'?

Yes

You can try using this snippet code and check if your purchased is shown or not:

<details>
<summary>Sample code (queryPastPurchase snippet code)</summary>

```dart

  List<GooglePlayPurchaseDetails> _pastPurchases = [];

  _buildQueryPastPurchase() {
    return TextButton(
      onPressed: () async {
        if (Platform.isAndroid) {
          final androidAddition = _inAppPurchase.getPlatformAddition<InAppPurchaseAndroidPlatformAddition>();
          final oldPurchases = await androidAddition.queryPastPurchases(applicationUserName: null); // always empty!

          // There can only be one subscription active at a time.
          final currentSubscription = oldPurchases.pastPurchases.isNotEmpty ? oldPurchases.pastPurchases[0] : null;

          setState(() {
            _pastPurchases = oldPurchases.pastPurchases;
          });
        }
      },
      child: Text('Query past purchase',
      ),
    );
  }

  _buildQueryPastPurchaseList() {
    return ListView.separated(
      shrinkWrap: true,
        itemBuilder: (context, index) {
          return Text(_pastPurchases[index].productID);
        },
        separatorBuilder: (context, index) => Divider(
              height: 1,
            ),
        itemCount: _pastPurchases.length);
  }

```
</details>

<details>
<summary>Demo (video)</summary>


https://user-images.githubusercontent.com/104349824/221802679-19cfdb77-15a6-4d22-a377-744774e7a37a.mov


</details>

**Comment by SEGVeenstra** [comment]
Thank you, I don't know why, but it now suddenly works.
I haven't changed anything, all I did is run it on another device :S.
Then I tried it on the previous emulator again and now it works there as well.

Thank you for your time!
