### ISSUE TITLE
[Impeller] Emojis become black occasionally

### ISSUE THREAD

**Issue by litang0908** [flutter/flutter#121128]
Some related issues:
https://github.com/flutter/flutter/issues/118866
https://github.com/flutter/flutter/issues/107413

Now i'm using latest flutter on master channel, but this issue still occurs, but it's occasionally, when switch pages and come back, it is normal again.

<img width="349" alt="image" src="https://user-images.githubusercontent.com/44760239/220268086-a71c21e6-75c9-4d92-84ee-9f55dcb3bf78.png">

<img width="352" alt="image" src="https://user-images.githubusercontent.com/44760239/220268042-41732e2b-fa3b-4675-98f9-45b860eabd48.png">

<details>
<summary>flutter doctor -v </summary>

```
Flutter (Channel master, 3.8.0-13.0.pre.98, on macOS 12.0.1 21A559 darwin-arm64, locale
    zh-Hans-CN)
    • Flutter version 3.8.0-13.0.pre.98 on channel master at /Users/tangyc/Documents/softs2/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4245389900 (2 days ago), 2023-02-18 21:53:13 -0500
    • Engine revision 1b71ea81a0
    • Dart version 3.0.0 (build 3.0.0-257.0.dev)
    • DevTools version 2.21.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0-rc1)
    • Android SDK at /Users/tangyc/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0-rc1
    • ANDROID_HOME = /Users/tangyc/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13A1030d
    • CocoaPods version 1.11.3

```

</details>

**Comment by delfme** [comment]
I upgraded to latest master today and I have same issue.

With previous master (3.8.0-5.0.pre.1) we had no issue.

![22043E9C-DE82-4791-836B-D22528F86884](https://user-images.githubusercontent.com/53510751/220703754-1b86d748-9753-418b-915e-9263451a8c90.jpeg)

**Comment by delfme** [comment]
If it may help, we have issue after rebuilding screens. In this screen emoji looks ok initially, but if I leave and enter screen it looks black. But if move app to background and then back again to foreground it looks ok. Etc…
There is sth that impair the rendering at time.

![993DF096-F5DD-4F73-AFFB-747F43C36621](https://user-images.githubusercontent.com/53510751/220705307-736ff2f5-db93-4faf-a8ce-c904606126ad.png)

**Comment by jonahwilliams** [comment]
Do either of you have a smaller example that reproduces the problem? I've tried a few combinations of text and emoji and I haven't been able to get it to trigger. 

I could still "Fix" this by finally separating the emoji and text atlases but I'd feel more comfortable if I could verify it

**Comment by jonahwilliams** [comment]
Landing a small fix to the eq or hashcodes. If you have a local engine build you could try it out to verify, otherwise it will roll through shortly

**Comment by delfme** [comment]
@jonahwilliams not sure if it is related, but noticed this other strange thing with emojis.
Please look at first 2 bubbles with 😊 and 😉 they are rendered bigger and letter “T” is bigger as well.

That doesnt occur with emoji 🤔 and 👍.

Since we didnt have these two bugs with master 3.8.0-5.0.pre.1, I thought they might be created by same commit somehow.

![9097EF24-694F-47AE-910C-C7E22362C03C](https://user-images.githubusercontent.com/53510751/220756137-412ec83f-6227-4163-9378-002fa2ce22a8.png)

**Comment by delfme** [comment]
The peculiarity of it is that they get rendered with correct size if rendered along with the emojis which are not affected by the bug.

For example, see 1 and 2 from pic below. If 😊 is rendered with 😉 then its size is correct. In 1 😊 is rendered alone and its size is bigger.

I can file separate issue for that if two issues are not linked. Because I also see emojis black (still not tested after your fix).

![E0CD9EF9-ABD2-470C-852F-BA86B40411D2](https://user-images.githubusercontent.com/53510751/220759351-1af7be95-3fa4-4aba-b29d-f3c244acf818.jpeg)

**Comment by jonahwilliams** [comment]
@delfme can you please file a new bug? Ideally we would have some sample code that can reproduce it. Without that I'll probably continue to priortize other easier to reproduce fidelity issues.

**Comment by delfme** [comment]
Thx @jonahwilliams  I tried to make a sample code but cannot reproduce issue by using simple Text elements.

Will investigate more and revert. In our app we also use textscale and other stuff, need to see what triggers the issue.

Will also check if black emoji issue is gone.

**Comment by jonahwilliams** [comment]
If you can narrow it down to the commit that introduced it via bisecting that will also be helpful

**Comment by delfme** [comment]
Fix works perfectly 👍

No need to file a new issue for emoji size coz it was our fault. We had this regression 2dd ago and didnt notice it

**Comment by jonahwilliams** [comment]
Yay, thanks for confirming!

**Comment by litang0908** [comment]
@jonahwilliams Thanks for fix this issue.

But I've just updated to the latest version of Flutter and I'm still having this problem, it's not really easy to troubleshoot, it's a bit more accidental, so I've provided a demo project to run: [github.com/litang0908/flutter_impeller_emoji_black](https://github.com/litang0908/flutter_impeller_emoji_black/)

Here is my `flutter doctor -v` :
```
Flutter (Channel master, 3.8.0-15.0.pre.41, on macOS 12.0.1 21A559 darwin-arm64, locale
    zh-Hans-CN)
    • Flutter version 3.8.0-15.0.pre.41 on channel master at /Users/tangyc/Documents/softs2/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 1155d2719d (5 hours ago), 2023-02-23 15:38:34 -0800
    • Engine revision cad5eec1b5
    • Dart version 3.0.0 (build 3.0.0-266.0.dev)
    • DevTools version 2.22.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn
```

Device Info:
```
iPhone 13 Pro.
iOS 16.2
```

It seems this PR [39794](https://github.com/flutter/engine/pull/39794) has in my flutter version.

The followings are my screenshot:

<img width="349" alt="image" src="https://user-images.githubusercontent.com/44760239/221095232-cc08d08b-e3f4-43ea-85fa-988907f85d84.png">


<img width="349" alt="image" src="https://user-images.githubusercontent.com/44760239/221095242-6ce7bb5d-292f-4ee0-a467-83be73536163.png">

The text `aaaa` in the first picture also more bold after  the emoji become normal( picture 2).

**Comment by delfme** [comment]
It also happened to me. But this time it is so random that cannot reproduce it. It happened while scrolling a list view after resuming app from background

**Comment by jonahwilliams** [comment]
Ahh I know the issue.

**Comment by litang0908** [comment]
Thanks , it's really worked.
