### ISSUE TITLE
plugin/path_provider: getTemporaryDirectory v systemTemp?

### ISSUE THREAD

**Issue by matanlurey** [flutter/flutter#12116]
The [path_provider](https://pub.dartlang.org/packages/path_provider) plugin provides a [`getTemporaryDirectory`](https://www.dartdocs.org/documentation/path_provider/0.2.1%2B1/) method.

In `dart:io`, which is available to Flutter, there is also [`Directory.systemTemp`](https://api.dartlang.org/stable/1.24.2/dart-io/Directory/systemTemp.html).

1. Is there a meaningful difference? What does `Directory.systemTemp` return?
2. If there is a difference, does it make sense to document on `getTemporaryDirecrory`?

**Comment by Hixie** [comment]
cc @a-siva @mravn-google

**Comment by stuartmorgan** [comment]
It appears that the Dart Android implementation just returns [a hard-coded path that's primarily intended to support tests](https://github.com/dart-lang/sdk/blob/d63d5d93a59b370bf5f5c277109110cb67a96b75/runtime/bin/directory_android.cc#L421-L438), while the `path_provider` version uses `getCacheDir`.

Given that there is a real difference, I don't think there's any action to take here.
