### ISSUE TITLE
DatePicker "Enter Date" field Overflowed in a large screen by 9.3 pixels

### ISSUE THREAD

**Issue by gustavocarvalhodeassis** [flutter/flutter#121166]
DatePicker "Enter Date" field Overflowed in a large screen by 9.3 pixels

**Comment by darshankawar** [comment]
@gustavocarvalhodeassis 
Can you provide `flutter doctor -v`, a minimal complete reproducible code sample that shows the behavior you are reporting along with platform on which you are seeing the same.

**Comment by gustavocarvalhodeassis** [comment]
[√] Flutter (Channel stable, 3.7.1, on Microsoft Windows [versÆo 10.0.19045.2604], locale pt-BR)
    • Flutter version 3.7.1 on channel stable at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7048ed95a5 (3 weeks ago), 2023-02-01 09:07:31 -0800
    • Engine revision 800594f1f4
    • Dart version 2.19.1
    • DevTools version 2.20.1

[X] Windows Version (Unable to confirm if installed Windows version is 10 or greater)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at C:\Users\gusta\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop for Windows (Visual Studio Community 2022 17.4.2)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.4.33122.133
    X Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop
      development with C++" workload, and include these components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK

[√] Android Studio (version 2021.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[√] VS Code (version 1.75.1)
    • VS Code at C:\Users\gusta\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.58.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [versÆo 10.0.19045.2604]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 110.0.5481.104
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 109.0.1518.61

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.

**Comment by gustavocarvalhodeassis** [comment]
[https://prnt.sc/J2a5YJld1L8b]

**Comment by gustavocarvalhodeassis** [comment]
// DATE PICKER CALL
https://prnt.sc/HCcS83QXqXXM

**Comment by darshankawar** [comment]
@gustavocarvalhodeassis 

> a minimal complete reproducible code sample that shows the behavior you are reporting along with platform on which you are seeing the same.

Please provide above and kindly do not share screenshots of the error and code. Please provide the same in properly formatted text.
