### ISSUE TITLE
[go_router_builder] Example in the README is wrong for default values

### ISSUE THREAD

**Issue by ValentinVignal** [flutter/flutter#121129]
## Steps to Reproduce

In the `README.md` of `go_router_builder`, the example is wrong for the [default values section](https://pub.dev/packages/go_router_builder#default-values):

https://github.com/flutter/packages/blob/6f1b1e899465aaeb624e28c0d90aa5dc865cef3f/packages/go_router_builder/README.md?plain=1#L182-L196

It is 

```dart
class MyRoute extends GoRouteData {
  MyRoute({this.queryParameter = 'defaultValue'});
  final String from;

  @override
  Widget build(BuildContext context, GoRouterState state) => MyScreen(from: from);
}
```

But it should be

```dart
class MyRoute extends GoRouteData {
  MyRoute({this.queryParameter = 'defaultValue'});
  final String queryParameter;

  @override
  Widget build(BuildContext context, GoRouterState state) => MyScreen(queryParameter: queryParameter);
}
```

It was introduced in https://github.com/flutter/packages/pull/2826

**Comment by stuartmorgan** [comment]
This package needs to be [updated to use code excerpts](https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#updating-code-excerpt-managed-examples) to prevent this kind of thing from happening in the future.
