### ISSUE TITLE
Container foregroundDecoration apply not correctly.

### ISSUE THREAD

**Issue by maxim-blockper** [flutter/flutter#121149]
## Steps to Reproduce

**Expected results:** Let me explain how it should work 
When you click on the planet, a dialog appears or a new screen opens. If you close the dialog or go back to the main page, the planet should not change color

**Actual results:** At the moment after clicking on a planet and the actions described above, the last planet in each galaxy (this is a normal planet sheet) is colored in the color that is specified in foregroundDecoration. ( screenshot below). Also for each planet widget I use my own unique GlobalKey().

<summary>

    return InkWell(
      onTap: () {
        //here logic opening dialog or redirect to new screen
      },
      child: Container(
        foregroundDecoration: isUnlocked
            ? const BoxDecoration(
                color: Colors.transparent,
                backgroundBlendMode: BlendMode.color,
                shape: BoxShape.circle,
              )
            : const BoxDecoration(
                color: Color(0xFFC1E5FF),
                backgroundBlendMode: BlendMode.color,
                shape: BoxShape.circle,
              ),
        child: Stack(
          alignment: Alignment.topCenter,
          children: [
            Assets.images.galaxy.planetBackground.image(
              height: 84,
              width: 80,
            ),
            CachedNetworkImage(
                      imageUrl: 'someImage',
                      width: 68,
                      height: 68,
                    ),
          ],
        ),
      ),
    );

</summary>

```
PS: i found how to fix bug with another widget 
solution not using container with foregroundDecoration.
IMO problem in foregroundDecoration.
return  ClipRRect(
        borderRadius: BorderRadius.circular(42.0),
        child: ColorFiltered(
          colorFilter: !isUnlocked
              ? const ColorFilter.mode(
                  AppColors.planetLockedColor,
                  BlendMode.color,
                )
              : const ColorFilter.mode(
                  Colors.transparent,
                  BlendMode.color,
                ),
   ),
);
```

<details>
  <summary>Logs</summary>

```
```

```
No issues found! (ran in 8.4s)
```

```
[✓] Flutter (Channel stable, 3.3.9, on macOS 12.6 21G115 darwin-arm, locale ru-BY)
    • Flutter version 3.3.9 on channel stable at /Users/maxim/flutter/flutter-sdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b8f7f1f986 (3 months ago), 2022-11-23 06:43:51 +0900
    • Engine revision 8f2221fbef
    • Dart version 2.18.5
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc1)
    • Android SDK at /Users/maxim/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] Connected device (3 available)
    • macOS (desktop)       • macos                     • darwin-arm64   • macOS 12.6 21G115 darwin-arm

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

</details>

![IMG_7138](https://user-images.githubusercontent.com/126001580/220417033-c1e74a3e-f76e-4750-b0db-e7f93fc82e05.jpg)
![IMG_7139](https://user-images.githubusercontent.com/126001580/220417045-ca9c8da6-6b23-4de7-99d3-cc381eddfce0.jpg)
![IMG_7140](https://user-images.githubusercontent.com/126001580/220417059-b2257194-f278-4d59-9cdd-17b8391ff6c5.jpg)

**Comment by huycozy** [comment]
Hi @maxim-blockper 
For the issue to be workable, it needs to be reproducible with a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code. Please provide such a sample so that we can verify the issue better. 
Thank you!
