### ISSUE TITLE
BottomNavigationBar doesn't respect backgroundColor

### ISSUE THREAD

**Issue by nilgaar** [flutter/flutter#121138]
## Steps to Reproduce

Run the sample code in a iPhone 14 emulator

**Expected results:** the _BottomNavigationBar_ is filled with the color

**Actual results:** the _BottomNavigationBar_ backgound is white

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'my_interests.dart';
import 'search.dart';

class ClientLanding extends StatefulWidget {
  const ClientLanding({Key? key}) : super(key: key);

  @override
  State<ClientLanding> createState() => _ClientLandingState();
}

class _ClientLandingState extends State<ClientLanding> {
  static const List<Widget> _landingScreens = <Widget>[
    ClientSearch(),
    ClientSearch(),
    ClientSearch(),
    ClientSearch()
  ];
  int _selectedItem = 1;

  void _onItemTapped(int index) {
    setState(() {
      _selectedItem = index;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: _landingScreens.elementAt(_selectedItem),
      ),
      bottomNavigationBar: BottomNavigationBar(
        backgroundColor: Colors.amberAccent,
        currentIndex: _selectedItem,
        items: const [
          BottomNavigationBarItem(
              label: 'Main', icon: Icon(Icons.home_rounded)),
          BottomNavigationBarItem(label: 'Search', icon: Icon(Icons.search)),
          BottomNavigationBarItem(
              label: 'My chats', icon: Icon(Icons.chat_outlined)),
          BottomNavigationBarItem(label: 't', icon: Icon(Icons.abc)),
        ],
        onTap: (index) {
          _onItemTapped(index);
        },
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () {
        },
        child: const Icon(Icons.add),
      ),
    );
  }
}

```

</details>

<details>
  <summary>Logs</summary>

No relevant logs are displayed

```
[!] Flutter (Channel stable, 3.7.3, on macOS 13.2.1 22D68 darwin-arm64, locale en-ES)
    • Flutter version 3.7.3 on channel stable at /Users/myuser/Documents/tools/flutter
    ! Warning: `dart` on your path resolves to /opt/homebrew/Cellar/dart/2.18.6/libexec/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/myuser/Documents/tools/flutter. Consider adding
      /Users/myuser/Documents/tools/flutter/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9944297138 (13 days ago), 2023-02-08 15:46:04 -0800
    • Engine revision 248290d6d5
    • Dart version 2.19.2
    • DevTools version 2.20.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to
      perform update checks and upgrades.

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/myuser/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /Library/Java/JavaVirtualMachines/jdk-17.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 17.0.6+9-LTS-190)
    ! Some Android licenses not accepted. To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] VS Code (version 1.75.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.46.0

[✓] Connected device (3 available)
    • iPhone 14 (mobile) • C57D09A2-F5A0-4516-B91E-DB6C1FF06A16 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-16-2 (simulator)
    • macOS (desktop)    • macos                                • darwin-arm64   • macOS 13.2.1 22D68 darwin-arm64
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 110.0.5481.100

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 3 categories.
```

</details>

**Comment by znromonk** [comment]
@nilgaar  As per Docs
>[BottomNavigationBarType.fixed](https://api.flutter.dev/flutter/material/BottomNavigationBarType.html), the default when there are less than four [items](https://api.flutter.dev/flutter/material/BottomNavigationBar/items.html). The selected item is rendered with the [selectedItemColor](https://api.flutter.dev/flutter/material/BottomNavigationBar/selectedItemColor.html) if it's non-null, otherwise the theme's [ColorScheme.primary](https://api.flutter.dev/flutter/material/ColorScheme/primary.html) color is used for [Brightness.light](https://api.flutter.dev/flutter/dart-ui/Brightness.html) themes and [ColorScheme.secondary](https://api.flutter.dev/flutter/material/ColorScheme/secondary.html) for [Brightness.dark](https://api.flutter.dev/flutter/dart-ui/Brightness.html) themes. If [backgroundColor](https://api.flutter.dev/flutter/material/BottomNavigationBar/backgroundColor.html) is null, The navigation bar's background color defaults to the [Material](https://api.flutter.dev/flutter/material/Material-class.html) background color, [ThemeData.canvasColor](https://api.flutter.dev/flutter/material/ThemeData/canvasColor.html) (essentially opaque white).
[BottomNavigationBarType.shifting](https://api.flutter.dev/flutter/material/BottomNavigationBarType.html), the default when there are four or more [items](https://api.flutter.dev/flutter/material/BottomNavigationBar/items.html). If [selectedItemColor](https://api.flutter.dev/flutter/material/BottomNavigationBar/selectedItemColor.html) is null, all items are rendered in white. The navigation bar's background color is the same as the [BottomNavigationBarItem.backgroundColor](https://api.flutter.dev/flutter/widgets/BottomNavigationBarItem/backgroundColor.html) of the selected item. In this case it's assumed that each item will have a different background color and that background color will contrast well with white.

Since you have four items in the nav bar, the default type is `BottomNavigationBarType.shifting`. For this type, the background color of the bar is driven by the background color of each of the `BottomNavigationBarItem`. If you want the same background color irrespective of the selection, then set the `backgroundColor` in each of the `BottomNavigationBarItem` to the same color.

Alternative is to set the `type` to `BottomNavigationBarType.fixed` and use the background color they way you already set.
