### ISSUE TITLE
Provide an API to customize `Stepper` icons

### ISSUE THREAD

**Issue by alexrintt** [flutter/flutter#121108]
## Use case

I'm working on a project that is using the `Stepper` widget along with `Step` class.

<kbd>
  <img src="https://user-images.githubusercontent.com/51419598/220196569-08157e05-f9dc-4310-b56d-77dcd4816198.png" height="200">
</kbd>
  <a href="https://user-images.githubusercontent.com/51419598/220196569-08157e05-f9dc-4310-b56d-77dcd4816198.png" height="200">Click to see full size</a>

---

The problem is that we cannot customize the icon since it's hardcoded here:

https://github.com/flutter/flutter/blob/980b3c5b0e0719fdffc3c4694c2f6fc9f2f01910/packages/flutter/lib/src/material/stepper.dart#L381-L398

This issue was already raised here https://github.com/flutter/flutter/issues/57236 before but no proposal was provided.

## Proposal

There are several ways to include this use case (custom Stepper icon), the most simple one is to provide a callback parameter and let it build each icon.

```dart
// Add option to call an icon builder.
if (widget.stepIconBuilder != null) {
  return widget.stepIconBuilder!(context, state);
}

// Current impl...
switch (state) {
  ...
}
```

We can extend this approach and instead providing a callback param to build the icon child, we provide an callback API to build the icon itself:

https://github.com/flutter/flutter/blob/980b3c5b0e0719fdffc3c4694c2f6fc9f2f01910/packages/flutter/lib/src/material/stepper.dart#L760-L765

Adding an API to build the icon:

```dart
children: <Widget>[
  SizedBox(
    height: _isLabel() ? 104.0 : 72.0,
    child: Column(
      mainAxisAlignment: MainAxisAlignment.center,
      children: <Widget>[
        if (widget.steps[i].label != null) const SizedBox(height: 24.0,),
        if (widget.buildStepIcon != null) 
          widget.stepIconBuilder(context, i, /* state, maybe? */)
        else
          Center(child: _buildIcon(i)),
        if (widget.steps[i].label != null) SizedBox(height : 24.0, child: _buildLabelText(i),),
      ],
    ),
  ),
  // ...
```

**Comment by HansMuller** [comment]
This sounds like a reasonable proposal. We're not actively working on Stepper at the moment but would welcome a PR..

**Comment by AyushBherwani1998** [comment]
@HansMuller if no one is working on the issue, I would like to work on the issue.

**Comment by alexrintt** [comment]
i don't started, so feel free, let me know if i can help.
