### ISSUE TITLE
New machine linux-28 to linux-36 could not connect to the external phone devices.

### ISSUE THREAD

**Issue by kentnguyen99** [flutter/flutter#121148]
New machine linux-28 - linux-36 could not connect to the external phone devices.

![Screenshot 2023-02-21 8 59 04 AM](https://user-images.githubusercontent.com/120754754/220415344-a1641f37-0890-4720-972f-1ea18d7c71b4.png)

**Comment by yusuf-goog** [comment]
`adb devices` is showing no devices.

I reapplied salt states to linux-28, and getting this error:

```device doctor healthcheck error: b"error: protocol fault (couldn't read status): Connection reset by peer\nUnhandled exception:\nExecutable adb failed with exit code 1.\n#0 fail (package:device_doctor/src/utils.dart:33)\n#1 eval (package:device_doctor/src/utils.dart:105)\n<asynchronous suspension>\n#2 Future.timeout.<anonymous closure> (dart:async/future_impl.dart:870)\n<asynchronous suspension>\n#3 AndroidDeviceDiscovery._deviceListOutputWithRetries.<anonymous closure> (package:device_doctor/src/android_device.dart:54)\n<asynchronous suspension>\n#4 RetryOptions.retry (package:retry/retry.dart:131)\n<asynchronous suspension>\n#5 AndroidDeviceDiscovery._deviceListOutputWithRetries (package:device_doctor/src/android_device.dart:52)\n<asynchronous suspension>\n#6 AndroidDeviceDiscovery.discoverDevices (package:device_doctor/src/android_device.dart:74)\n<asynchronous suspension>\n#7 AndroidDeviceDiscovery.checkDevices (package:device_doctor/src/android_device.dart:104)\n<asynchronous suspension>\n#8 main (file:///b/s/w/ir/x/w/cocoon/device_doctor/bin/main.dart:67)\n<asynchronous suspension>\n"```

Then rebooted linux-28, and back to the original error.

@kentnguyen99 please check the devices, make sure the auth screen is accepted.

**Comment by nehalvpatel** [comment]
Any update on the auth?

**Comment by kentnguyen99** [comment]
@nehalvpatel All machines linux-28 - linux36 are running and in production except machine linux-31 is missing from the monitoring website.  I'm working with Yusuf why linux-31 is not show on monitoring website.

**Comment by yusuf-goog** [comment]
These devices are up. closing.
