### ISSUE TITLE
webview_flutter

### ISSUE THREAD

**Issue by Sandeepbandral** [flutter/flutter#121126]
I updated the webview_flutter version to 4.0.4 but the app is not running now, every time I see the below error: 

* What went wrong:
Could not determine the dependencies of task ':webview_flutter_android:compileDebugAidl'.
> javax.xml.bind.UnmarshalException (no error message)

Anyone faced the same issue, please help!

**Comment by TSxSAHIL** [comment]
Try Running flutter clean 
Then flutter pub get

**Comment by exaby73** [comment]
Hello @Sandeepbandral. Thank you for filing this issue. Can you please provide the following information?

- A [complete and minimal, reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example). Ideally, a single `main.dart` file that can be run directly.
- The output of `flutter doctor -v`
- The output of `flutter run -v`

Please provide the information in the form of text. See how to make collapsible sections with Markdown [here](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-collapsed-sections).
