### ISSUE TITLE
[flutter_adaptive_scaffold] : selectedIcon allowed in NavigationDestination but not able to render.

### ISSUE THREAD

**Issue by aliasgar4558** [flutter/flutter#121135]
## Use case

`NavigationDestination` has an option to add `selectedIcon` which shall display when user selects that specific destination/navigation. However, it is not been able to display even if the destination is selected.

## Proposal

SelectedIcon needs to be given `toBottomNavigationBarItem` in adaptive_scaffold.dart which shall resolve the problem.

**Comment by exaby73** [comment]
Hello @aliasgar4558. Thank you for filing this issue. Can you please provide the following information?

- A [complete and minimal, reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example). Ideally, a single `main.dart` file that can be run directly.
- The output of `flutter doctor -v`

Please provide the information in the form of text. See how to make collapsible sections with Markdown [here](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-collapsed-sections).

**Comment by aliasgar4558** [comment]
hey @exaby73 , Thanks for taking interest in the issue. I have implement a fix in for the same issue which I reported. Merge request is also been raised for the same [https://github.com/flutter/packages/pull/3253]. Please do have a look at that once.

**Comment by aliasgar4558** [comment]
Hurrrayyyyy.....Closed this issue as the fix is been merged into main as version 0.1.1.
Thanks..
